### ISSUE TITLE
Running Gutenberg Dev remotely

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#10028]
I'm trying to run Gutenberg on a remote server with Docker. Everything seems to work fine, except that `localhost:8888` seems to be hardcoded. So loading any page directly works fine, but any links direct to `localhost:8888` instead of the custom domain or IP. I tried changing `bin/install-wordpress.sh`, but that doesn't seem to help. Any ideas on how to create a setting for the hostname?

**Comment by tofumatt** [comment]
We don't currently have a setting for this but we could (and should) add one. You can change `localhost` to your hostname in `bin/install-wordpress.sh` but you'd need to re-install. It's in there a bunch of times though, did you change it everywhere?

**Comment by iseulde** [comment]
Yes, I believe three occurrences. I can try it again later.

**Comment by aduth** [comment]
The main option I would sense to have an impact here is the `--url` option:

https://github.com/WordPress/gutenberg/blob/1d2d1fc9dc88c97cb8f23472b03cc6a2d8241df0/bin/install-wordpress.sh#L55

Since this controls the [`site_url` option](https://developer.wordpress.org/reference/functions/site_url/) that WordPress uses to forcefully redirect incoming requests.

Doesn't seem there's anything actionable here.
