### ISSUE TITLE
Gutenberg problems with Tasty Recipes

### ISSUE THREAD

**Issue by kb61401** [WordPress/gutenberg#10041]
**Describe the bug**
With the Gutenberg plugin (version 3.8.0) enabled, I receive the following error when I try to edit a previous post or post draft:
_Fatal error: Cannot use object of type WP_Block_Parser_Block as array in /home/content/p3pnexwpnas03_data01/01/2881501/html/wp-content/plugins/tasty-recipes/tasty-recipes.php on line 249_

**Desktop (please complete the following information):**
 - OS: [Mac 10.13.6]
 - Browser [Chrome]
 - Version [Version 69.0.3497.100]

**Comment by tofumatt** [comment]
Hi there! Thanks for filing, at first I thought this looks like an issue with the code in your plugin and not with Gutenberg itself.

I think it's worth filing this bug with the developers of Tasty Recipes, as it seems like it's likely an issue with their plugin.

It could be related to https://github.com/WordPress/gutenberg/pull/9984, which is a fix that will be available in 3.9.0, due to come out tomorrow.

Could you check if this is still happening when 3.9.0 comes out? If it does it's likely an issue with the plugin and not Gutenberg.

**Comment by kb61401** [comment]
Thanks! Will do.

**Comment by raquelmsmith** [comment]
@kb61401 we've found a fix for this issue! Can you email support@wptasty.com? We'll get you squared away 👍

**Comment by mcsf** [comment]
Thanks for the reports, and thanks to @raquelmsmith for looking at a fix. Indeed, this is an issue on Gutenberg's part: #10047.

I think it's fair to close this issue in favor of #10047, as I'm 95% certain they are the same. If not, feel free to reopen or comment.
