### ISSUE TITLE
WYSIWYG support for Gutenberg from WordPress Standardthemes

### ISSUE THREAD

**Issue by burnuser** [WordPress/gutenberg#10058]
**Is your feature request related to a problem? Please describe.**
Many Themes control Classic TinyMCE for a real WYSIWYG display with fonts and max-width for pages and posts.
Entering Gutenberg, one oft the first negative experiences compared to Classic TinyMCE is this obvious lack of WYSIWYG display with its fixed font and width.

**Describe the solution you'd like**
Add in standard WordPress Themes like Twenty Sixteen (+600.000 users) and Twenty Seventeen (+1Mio users) this full WYSIWYG support (fonts and max-width) also for Gutenberg.
1.) Demonstrate users the WYSIWYG power on their regular used themes.
2.) Learn to make this Theme customization as easy as possible (and perhaps make something better like using a variable for image-width and not a hardcoded value)
3.) Write an easy instruction for theme developers to do the same

**Describe alternatives you've considered**
There are a few plugins to get WYSIWYG fonts and/or editor max-width in Gutenberg, but only one (which allows controlling manually the max-width) is working at the moment.

**Comment by designsimply** [comment]
Recent updates such as #9008 have been added to help make this process easier. A comment at https://github.com/WordPress/gutenberg/pull/9008#issuecomment-415385581 mentions documentation and asks what is missing.

There is also a request for feedback about the strategy around styling on a more general level at #9534 and the goal for that issue is critical thinking around how styling works for multiple areas, including the editor styles and editor width which you are asking about specifically.

Since these things are new, themes may take some time to add support such as what you are asking. The right place to file a request for bundled themes such as Twenty Sixteen and Twenty Seventeen is at https://core.trac.wordpress.org/component/Bundled%20Theme. Would you be able to add your requests for Twenty Seventeen and Twenty Sixteen there?

**Comment by designsimply** [comment]
@burnuser, core Trac tickets have been opened for all of the default themes:

* Twenty Ten ([45038](https://core.trac.wordpress.org/ticket/45038))
* Twenty Eleven ([45039](https://core.trac.wordpress.org/ticket/45039))
* Twenty Twelve ([45040](https://core.trac.wordpress.org/ticket/45040))
* Twenty Thirteen ([45041](https://core.trac.wordpress.org/ticket/45041))
* Twenty Fourteen ([45042](https://core.trac.wordpress.org/ticket/45042))
* Twenty Fifteen ([45043](https://core.trac.wordpress.org/ticket/45043))
* Twenty Sixteen ([45044](https://core.trac.wordpress.org/ticket/45044))
* Twenty Seventeen ([45045](https://core.trac.wordpress.org/ticket/45045))

Thank you for bringing this up!
