### ISSUE TITLE
String "Writing" in a menu doesn't make sense.

### ISSUE THREAD

**Issue by mayukojpn** [WordPress/gutenberg#10053]
**Describe the bug**
The string "Writing" here in more menu is misleading since all options are for writing in general.

**To Reproduce**
How is "View"? These options are for how editor change its display I guess. Otherwise this strings should describe that these options are more focus on writing **behavior** itself instead of just "Writing".

**Screenshots**
![location_of_string_writing](https://user-images.githubusercontent.com/1886443/45798013-23dbb700-bce3-11e8-88c8-7df4776e2409.jpg)

**Additional context**
It will also affect translations.

**Comment by kristastevens** [comment]
Hi @mayukojpn, I think "View" is the right term here as you suggest, because it summaries the options related to how the editor displays.

**Comment by chrisvanpatten** [comment]
I had suggested calling it "Preferences" in the original ticket (#9394), but @karmatosed had some [good points](https://github.com/WordPress/gutenberg/pull/9394#issuecomment-417124373) that I thought were worth looping in here as a bit of extra context:

> I would say if we have options saying writing makes sense over preferences. I am concerned preferences is a wider term that as has been pointed out goes beyond this. The options are relating to writing/creating content.

As proposed in this ticket, "View" definitely seems like a better option than "Preferences" because it is more focussed and more clearly describes the purpose of these options.

Just for the sake of brainstorming, a few other ideas (some good, some lousy):

+ Interface
+ Look & Feel
+ Customize Editor

Just ideas… I agree though that "Writing" is a bit misleading and would love to see a change here :)

**Comment by karmatosed** [comment]
I think 'view' kind of works but then we're also merging into the second group. In past I've suggested 'mode' which isn't great either.

**Comment by mayukojpn** [comment]
Thanks for feedbacks! I guess View works well for now.

@karmatosed Do you mean you are merging 'Writing' and 'Editor'?

**Comment by karmatosed** [comment]
Merging with meaning not actually merging.
