### ISSUE TITLE
RichText Component removes HTML elements it deems 'empty'

### ISSUE THREAD

**Issue by kevinbazira** [WordPress/gutenberg#10097]
**To Reproduce**
Try to programmatically add `<span>` to RichText using the 2 options below;
1. **FAILS:** span with background image without text
```
<span style="width:256px;height:256px;display:inline-block;background-image: url('https://ps.w.org/gutenberg/assets/icon-128x128.jpg?rev=1776042');"></span>
```
2. **PASSES:** span with background image with text
```
<span style="width:256px;height:256px;display:inline-block;background-image: url('https://ps.w.org/gutenberg/assets/icon-128x128.jpg?rev=1776042');">sometext</span>
```

Please see example in code below;

```
const { registerBlockType } = wp.blocks;
const { RichText } = wp.editor;

registerBlockType( /* ... */, {
	// ...

	attributes: {
		content: {
			type: 'array',
			source: 'children',
			selector: 'p',
			default: [],
		},
	},

	edit( { className, attributes, setAttributes } ) {
	
		const addSpanWithBackgroundImageWithoutText = ( content ) => {
			
			setAttributes( { content: content.concat( <span style="width:256px;height:256px;display:inline-block;background-image: url('https://ps.w.org/gutenberg/assets/icon-128x128.jpg?rev=1776042');"></span> ) } );
		
		}
		
		const addSpanWithBackgroundImageWithText = ( content ) => {
			
			setAttributes( { content: content.concat( <span style="width:256px;height:256px;display:inline-block;background-image: url('https://ps.w.org/gutenberg/assets/icon-128x128.jpg?rev=1776042');">sometext</span> ) } );
		
		}
		
		return (
			<RichText
				tagName="p"
				className={ className }
				value={ attributes.content }
				onChange={ addSpanWithBackgroundImageWithoutText } // addSpanWithBackgroundImageWithText works fine BUT addSpanWithBackgroundImageWithoutText adds span that gets removed immediately
			/>
		);
	},

	save( { attributes } ) {
		return <RichText.Content tagName="p" value={ attributes.content } />;
	}
} );
```

In the sample code above `addSpanWithBackgroundImageWithText()` works fine BUT `addSpanWithBackgroundImageWithoutText` adds span that gets removed immediately.

Wondering what could be causing this behavior! 🤔

**Expected behavior**
Testing out of Gutenberg in a regular `.html` both options below work fine.
1. **PASSES:** span with background image without text
```
<span style="width:256px;height:256px;display:inline-block;background-image: url('https://ps.w.org/gutenberg/assets/icon-128x128.jpg?rev=1776042');"></span>
```
2. **PASSES:** span with background image with text
```
<span style="width:256px;height:256px;display:inline-block;background-image: url('https://ps.w.org/gutenberg/assets/icon-128x128.jpg?rev=1776042');">sometext</span>
```

**Additional context**
- Tested on Gutenberg Version 3.8.0

**Comment by mcsf** [comment]
Thanks for the report, @kevinbazira. This is probably something to have a better look at once #7890 lands, which should be in 4.0-rc.1 or 4.0-rc.2.

In any case, I'd like to know more about the use cases for this application of RichText — namely, when to use such specific markup in RichText instead of using a block type's `edit` and `save` functions.

**Comment by kevinbazira** [comment]
Thanks for following up @mcsf

My current use case is that, I am implementing a "custom emoticon block" that allows users to write/edit text then insert a custom emoticon (i.e span with background image) directly inside their paragraphs.

**Comment by youknowriad** [comment]
Is this still the case, RichText have been refactored since the last update here?

**Comment by mcsf** [comment]
I believe @kevinbazira's use case is now supported. I tested locally by having a block render

```js
<RichText value='A<span data-foo="bar"></span>B' />
```

and confirmed that the DOM in the editor becomes:

```html
"A"
<span data-foo="bar"></span>
"B"
```

The main references since the refactoring of RichText are:
- The component itself, [`RichText`](https://github.com/WordPress/gutenberg/blob/b5fbda755ce99fdb5e16430d0fb3fcf1f12a298e/packages/editor/src/components/rich-text/README.md)
- The new format, implemented in [`@wordpress/rich-text`](https://github.com/WordPress/gutenberg/blob/b5fbda755ce99fdb5e16430d0fb3fcf1f12a298e/packages/rich-text/README.md)

I hope this helps. Otherwise, feel free to reopen.
