### ISSUE TITLE
Copy/Paste of Markdown text does not create blocks on iOS/mobile

### ISSUE THREAD

**Issue by afragen** [WordPress/gutenberg#10114]
**Describe the bug**
Copy a text document written in Markdown and paste it into a new post. WP will automatically convert the Markdown into the corresponding blocks.

This same process does not work on iOS.

This is not using the WordPress iOS app. It is visiting the site in Safari.

**To Reproduce**
As in the description.

**Expected behavior**
I expected the same behavior as on a computer. That the pasted Markdown text would be automatically formatted into corresponding Gutenberg blocks.

**Desktop (please complete the following information):**
 - OS: iOS 12, though it happens in iOS 11
 - Browser Safari
 - Version latest

**Smartphone (please complete the following information):**
 - Device: iPad Pro 9.7
 - OS: iOS 12
 - Browser Safari
 - Version latest

**Additional context**
Gutenberg 3.9.0

**Comment by mcsf** [comment]
After some debugging, this is a Safari quirk that is also observable on macOS, instead of a specific iOS issue. The main difference lies here:

https://github.com/WordPress/gutenberg/blob/fd9bfa5b9884a7fe5993f4c19a431b32a17094e2/packages/editor/src/components/rich-text/index.js#L243

In other browsers, `clipboardData.getData( 'text/html' )` returns an empty string, whereas in Safari it returns full HTML.

## To reproduce

1. Open Notes.app in either macOS or iOS.
1. Start a fresh note and type in `Hello, _there_.`
1. Copy the note.
1. Start a new Gutenberg post.
1. Paste the note into the post.

**Observed:** `clipboardData.getData( 'text/html' )` returns `<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px 'Helvetica Neue'; color: #454545">Hello, _there_.</p>`

**Comment by youknowriad** [comment]
I haven't tested in iOS but in Safari on MacOS, pasting markdown is working properly. Anyone able to test on iOS and close the issue if needed?

**Comment by youknowriad** [comment]
For me, if I copy the markdown from a regular input/textarea (like this comment box) and paste, it works great. So I think the issue might be on the source app?

**Comment by paaljoachim** [comment]
Hey @afragen Andy

Could you retest with the newest version of WordPress and Gutenberg plugin?
Thanks! How can we move the issue onward?

**Comment by afragen** [comment]
Just tested again using 5.7-beta3 and Gutenberg Nightly. Unfortunately still the same results. Just shows plain text without automatic conversion to rich text. 

This in iPhone 12 mini using Safari.

**Comment by afragen** [comment]
I think this can be closed. 

I just copied markdown from a text app and copied it in. It worked. I think there must be something about "text" coming from Safari or what other app has the markdown text.
