### ISSUE TITLE
iThemes Security with enabled HackRepair.com blacklist blocks Gutenberg's file_get_contents() of editor stylesheet

### ISSUE THREAD

**Issue by macemmek** [WordPress/gutenberg#10113]
iThemes Security plugin reveals a possible small problem with Gutenberg.
When is activated with HackRepair.com blacklist, custom editor styles cannot be loaded because of 403 error.
Probably the plugin filters file_get_contents() request as suspicious.

Warning message:
`file_get_contents(http://mysite.com/wp-content/themes/mytheme/assets/css/editor-style.css): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden`
The line:
`wp-content/plugins/gutenberg/lib/client-assets.php:1442`

**To Reproduce**
1. Install and activate [iThemes Security](https://pl.wordpress.org/plugins/better-wp-security/) plugin
2. Go to Security -> Settings -> Banned Users -> Enable HackRepair.com blacklist and save
3. Add custom editor style in the theme with add_editor_style('/path/to/stylesheet.css' );
4. Go to post edit screen
5. See missing styles or look at PHP warnings

**Expected behavior**
No warning when editor style is requested by Gutenberg with iThemes Security and hackrepair.com list activated.

**Tip**
Setting proper user agent like: `ini_set('user_agent','Mozilla/4.0 (compatible; MSIE 6.0)');`
vanishes the error.

**Version**
Gutenberg 3.9.0

**Comment by designsimply** [comment]
Tested with WordPress 4.9.8 and Gutenberg master `70c80680b` and iThemes Security 7.2.0 ([hackrepair.com banned user setting screenshot](https://user-images.githubusercontent.com/1119271/48036267-c2ea3000-e124-11e8-8f65-fa9d2c2e3901.png)) and was unable to reproduce the problem—in my test, the custom styling added with `add_editor_style()` worked and I didn't' see any 403 error in the console or the network panels in web browser tools. Tested with Firefox 63.0 on macOS 10.13.6 and with Twenty Nineteen downloaded from https://github.com/WordPress/twentynineteen/. 

Closing for now, but please comment if you find the problem is still in play after testing with the latest versions or if you think I've made a mistake in my test!
