### ISSUE TITLE
Embed of a site's URL fallback to paragraph block doesn't work any more. 

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#10110]
**Describe the bug**
With 3.9 It seems the ability to embed website URLs from other WordPress sites is not always working and random "Sorry we could not embed that content." 

**To Reproduce**
1. Create a Post
2. embed WordPress site's url [(example)
3](https://blacktiedigital.com/can-gutenberg-replace-acf-for-page-building/). 
4. See note: "Sorry, we could not embed that content."
![screen shot 2018-09-22 at 10 57 30 am](https://user-images.githubusercontent.com/39980/45918536-6376e000-be56-11e8-8c79-45551d123ec0.png)

**Expected behavior**
Display of blog post in Embed Wordpress Card.
![screen shot 2018-09-22 at 11 05 52 am](https://user-images.githubusercontent.com/39980/45918610-881f8780-be57-11e8-911b-bdab00ff002c.png)

Previously it would at least create a paragraph block with just the URL as a link in it. 

**Screenshots**
No error message in browser console only "normal looking" messages
![screen shot 2018-09-22 at 11 15 21 am](https://user-images.githubusercontent.com/39980/45918696-e6009f00-be58-11e8-94b5-0e9e79ab6432.png)

**Desktop (please complete the following information):**
 - OS: MAC 10.13.6
 - Browser Firefox Developer
 - Version 63.0b6

**Comment by arunsathiya** [comment]
> With 3.9 It seems the ability to embed website URLs from other WordPress sites is not always working and random "Sorry we could not embed that content."

**Comment by arunsathiya** [comment]
> With 3.9 It seems the ability to embed website URLs from other WordPress sites is not always working and random "Sorry we could not embed that content."

Noting that I was able to reproduce embed failure for [the said link](https://blacktiedigital.com/can-gutenberg-replace-acf-for-page-building/) on Gutenberg 3.8 as well. It works for other WordPress blogs [like this one](https://wordpress.org/news/2018/09/the-month-in-wordpress-august-2018/). [Video](https://cloudup.com/caGu1aZ4Kne). - Test on Gutenberg 3.8.

On Gutenberg 3.9, again only the mentioned link by @bph fails, while other WordPress blog links work fine.

@bph I realize you have mentioned `is not always working` - do you intend to say that the embed for your mentioned link works intermittently? Have you also tried to embed other blog links from the same site?

**Comment by sumanw** [comment]
> With 3.9 It seems the ability to embed website URLs from other WordPress sites is not always working and random "Sorry we could not embed that content."
Agree with @arunsathiya , I was able to reproduce this same error but only for this particular link.
I have tried many other links , it works fine.
For this specific link/domain it gives error.

Desktop (please complete the following information):

OS: Windows 7
Browser Google Chrome
Version 69.0.3497.100

**Comment by designsimply** [comment]
I tested by trying to embed https://gutenbergtimes.com/update-87-faq-on-wordpress-5-0-release-gutenberg-around-the-world-and-blocks-so-many-blocks/ and it resulted in a WordPress embed card, but testing with https://blacktiedigital.com/can-gutenberg-replace-acf-for-page-building/ did not. I also tested with a different post from the same site https://blacktiedigital.com/5-important-things-to-know-about-responsive-design/ and it also did not embed.

I also tested with Gutenberg deactivated, and the same problem occurred so I don't think this problem is specific to Gutenberg.

![screen shot 2018-09-24 at 1 17 26 pm](https://user-images.githubusercontent.com/1119271/45973650-4d0a8900-bffc-11e8-8288-180863c1027e.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post-new.php running WordPress 4.9.8 and the Classic Editor tested with Firefox 62.0 on macOS 10.13.6.</sup>

The closest possibly-related bug I found after searching core Trac is at https://core.trac.wordpress.org/ticket/42733 and says WordPress Embed URLs don't work for draft and scheduled posts with pretty permalinks—but I don't think that applies to blacktiedigital.com. I am not sure what the blacktiedigital.com site might be missing in terms of what is needed to allow embeddable WordPress URLs. I did notice it seems like they have permalinks for posts set to `/%postname%/` so I tried that on another test blog of mine and embedding WordPress posts still worked so that's probably not it. I also found a reference on a make/core blog post at https://make.wordpress.org/core/2015/10/28/new-embeds-feature-in-wordpress-4-4/ which says, "WordPress’ oEmbed consumer code has been enhanced to work with any site that provides oEmbed data (as long as it matches some strict security rules)." Because of this, my guess is that the site may have done something to prevent embeds.

@bph do you think we could find some additional examples of posts that aren't working? If so, maybe it could help us narrow down what might be going wrong and we can figure out where to post.

**Comment by designsimply** [comment]
I didn't see your additional examples and am noting them here for reference:

* https://yoast.com/how-to-build-an-faq-page/
* https://atomicblocks.com/how-to-deprecate-gutenberg-editor-blocks/
* https://torquemag.io/2018/09/gutenberg-migration-guide/
* https://wptavern.com/drupal-gutenberg-project-receives-enthusiastic-reception-at-drupal-europe

I tested each of those in Gutenberg and the Classic Editor and https://atomicblocks.com/how-to-deprecate-gutenberg-editor-blocks/ doesn't get converted to an embed in either editor and the others work fine for me in both.

Regarding the formatting issues such as for https://wptavern.com/drupal-gutenberg-project-receives-enthusiastic-reception-at-drupal-europe is that happening on the front end or in Gutenberg or both?

**Comment by bph** [comment]
At first, I thought, the formatting issue with the WPTavern URL seems to be related to the blocks before and after and it happens in both. But I can just can't replicate this. It changes while editing a post. I just can nail it. 
Here is the same URL on the front end. 
![screen shot 2018-09-26 at 5 17 27 pm](https://user-images.githubusercontent.com/39980/46110205-ec707d00-c1b0-11e8-8f18-016e748e53c2.png)
![screen shot 2018-09-26 at 5 14 48 pm](https://user-images.githubusercontent.com/39980/46110226-fe522000-c1b0-11e8-88e2-9510f661470e.png)

After I saved it again and previewed it again, both variations look truncated. Everytime I try to test this with the existing post, I get different outcomes on different phases of the save process. It confuses me. I am bit frustrated. As I see it's not working right, but I can't nail it down, as the behavior is not consistent. I guess I shouldn't do the testing on a live site. 

And in between there are these massive amount of white space on URL that are not rendering.. or rendering with additional white space. 
Here is a video: http://recordit.co/LVrmXlqj8n
