### ISSUE TITLE
Gutenberg breaks gallery placement and layout

### ISSUE THREAD

**Issue by BlameDutchie** [WordPress/gutenberg#10123]
When converting a post written with the classic editor, galleries move to the right and layout changes.
 
Reproduction:

Either convert an existing post with an image gallery to a Gutenberg block post or create a new post using Gutenberg.

Using the default Wordpress gallery shortcode "[gallery type="rectangular" size="medium" link="file" ids="

Gutenberg changes this into "ul class="wp-block-gallery columns-3 is-cropped">" which obviously breaks the layout. Apparently the Gutenberg team expects site owners to dig into the CSS that comes with these Gutenberg classes to be able to override them to restore existing layout.

I don't want to turn this into a rant, but I think this is not the right way to implement Gutenberg.

Expected behavior:
Layout and position should remain the same.

**Screenshot 1 - Classic editor:**

![before_gutenberg](https://user-images.githubusercontent.com/12746371/45927488-75768280-bf2b-11e8-9f5d-d8b8497e65f5.jpeg)

**Screenshot 2 - Gutenberg:**

![after_gutenberg](https://user-images.githubusercontent.com/12746371/45927490-7effea80-bf2b-11e8-8fba-4d3dfb4106ce.jpeg)

 - OS: MacOS 10.13.6
 - Browser: Firefox 63.0b8, Chrome 69.0.3497.100
 - Wordpress: 4.9.8
 - Gutenberg: 3.9.0

**Comment by designsimply** [comment]
First, I tested adding a gallery using the classic editor and found that galleries made that way are displayed in a grid and not tiled as shown in your classic editor screenshot.

![screen shot 2018-09-24 at 3 29 31 pm](https://user-images.githubusercontent.com/1119271/45980277-c6ab7280-c00e-11e8-8521-f03703c778a5.png)
<sup>Seen at http://alittletestblog.com/2018/09/24/gallery-with-four-images/ running WordPress 4.9.8 and Gutenberg 3.9.0 using Firefox 62.0 on macOS 10.13.6.</sup>

I think this is happening because you are using a plugin that includes an option for tiled galleries. Jetpack perhaps? Can you confirm?

**Comment by BlameDutchie** [comment]
Yes, I forgot to mention that, sorry.

I am using Jetpack's `Tiled Mosaic´ option. I thought that would be obvious given the "gallery type="rectangular" short-code. My bad.

**Comment by designsimply** [comment]
It may be obvious to some! I always think it's better to check to make sure though. 🙂

I searched and found that the Jetpack project has an issue requesting support for the gallery block at https://github.com/Automattic/jetpack/issues/8527 and there is work ongoing to add a tiled gallery block to Jetpack at https://github.com/Automattic/jetpack/pull/10145. I am closing this issue because the work on the Jetpack side is where the solution needs to happen. Thanks for raising the issue!
