### ISSUE TITLE
InnerBlocks wrap nested blocks in divs

### ISSUE THREAD

**Issue by gregbia** [WordPress/gutenberg#10139]
I'm using InnerBlocks to create nested blocks for a carousel slider:

```
return (
 <div className="carousel">
     <InnerBlocks.Content />
 </div>
);
```

Is it possible to wrap each nested block added in a div?  

For example if I add paragraphs as nested blocks I get:

```
<div class="carousel">
  <p>Lorem</p>
  <p>Ipsum</p>
  <p>Dolot</p>
</div>
```

I want to achieve the following:

```
<div class="carousel">
  <div class="custom-class"><p>Lorem</p></div>
  <div class="custom-class"><p>Ipsum</p></div>
  <div class="custom-class"> <p>Dolor</p></div>
</div>

```
Where "custom-class" div was added to each nested block.

**Comment by chrisvanpatten** [comment]
@gregbia What you would need to do is actually have a second level of nesting. So a top level "Carousel" block, then second-level "Carousel Slide" blocks, and then your paragraphs/images/etc. inside that block at the third level. Let me know if that makes sense!

**Comment by gregbia** [comment]
@chrisvanpatten thank you for the feedback. I was wondering if there was a way to doing it in the code using the block API - just adding a property like a classname or style to any nested block. Using 2 nested blocks will be an extra step for the user.

**Comment by chrisvanpatten** [comment]
@gregbia Unfortunately it's not possible right now; the nested block API is pretty stable at this point. You could use `dispatch` and `select` to apply custom attributes to blocks nested inside a parent block, but that requires each block to support custom class names, which not every block actually supports.

You can see in the core columns block that it's possible to create these nested blocks without a lot of extra work for the user; you can also see an example of how to add nested blocks from a custom button over at #10296. These make it pretty easy to create a nice UI for your users that doesn't require them to go through the inserter.

Since this API is stable and not likely to change from this multi-level nesting implementation, I'll close this up but we can always revisit/reopen later if there's more demand for this!

**Comment by gregbia** [comment]
Thank you! I will try that.
