### ISSUE TITLE
How to email links on Gutenberg

### ISSUE THREAD

**Issue by ucnrs** [WordPress/gutenberg#10145]
Does any now how to create email link on Gutenberg page?

Thank you,

Lobsang
If you have a question you have a few places that you can ask this:

- Support Forums: https://wordpress.org/support/plugin/gutenberg
- Handbook: https://wordpress.org/gutenberg/handbook
- https://chat.wordpress.org #core-editor

If you are unable to ask in those places you can ask here, however you will get faster responses through those recommended places.

**Comment by Soean** [comment]
Same like in the classic editor: put `mailto:` in front of your email address, so you get: `<a href="mailto:nowhere@mozilla.org">Send email to nowhere</a>`. Source: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#Creating_an_email_link

**Comment by designsimply** [comment]
I'm closing this issue since the question has been answered. If you're still having trouble, we can continue the conversation if needed.

**Comment by AlchemyUnited** [comment]
@designsimply - I believe the issue here is, when you highlight text (e.g., in a paragraph block) and click the link icon in the toolbar, the search / suggest box does not - afaict - allow someone to enter mailto:. 

Perhaps I missed something but I had to switch the block to Edit as HTML. Then add the mailto:. Then swtich back to Edit Visually. Needless to say, that's a friction-y UX.

**Comment by Soean** [comment]
@AlchemyUnited Thanks for reporting this, can you open a new issue for it?

**Comment by AlchemyUnited** [comment]
@Soean - I wish I had the time. I've opened issues on this project before and have gotten nothing but pushback, whining, and grief for the team's representatives. It's been too many shame-on-me at this point. I'm can't help those who don't want help. Thanks tho'. Have a nice day.
