### ISSUE TITLE
Left or right aligned YouTube embed is small and disappears when selected

### ISSUE THREAD

**Issue by brandonpayton** [WordPress/gutenberg#10151]
**Describe the bug**
When a YouTube block is aligned left or right, it becomes very small, and when you click within the block's bounds, the video disappears.

This occurs with the YouTube block but not with a generic embed block with a YouTube URL.

**To Reproduce**
1. Create a post.
2. Insert a YouTube block.
3. Specify a YouTube URL for the block.
4. Left align the block and observe it is much smaller in size.
5. Click within the block boundary but outside the video and observe the video disappears.

**Expected behavior**
The video would be left aligned and would remain a reasonable size.

**Screenshots**
![shrinking-aligned-youtube-embed](https://user-images.githubusercontent.com/530877/45997152-84f0eb00-c053-11e8-873c-c588e3660018.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Browser: Chrome 
 - Version: 69.0.3497.100

**Additional context**
- Gutenberg version: 0a103bc9ab54c98084d96c5f121cd9977d3d78fa (master, soon after 3.9 release)

**Comment by saulirajala** [comment]
I can confirm this bug. I tested with Safari 12.0 on MacOS 10.13.6 with fresh WordPress install (runs in docker setup of Gutenberg).

The block data is still around, when you switch to Code editor:
<img width="1289" alt="nayttokuva 2018-10-6 kello 21 54 04" src="https://user-images.githubusercontent.com/5536354/46574846-d2a21780-c9b2-11e8-9108-70a3fef48ff8.png">

The problem seems to be with `float:left;` css-definition assigned to `.editor-block-list__layout .editor-block-list__block[data-align="left"] > .editor-block-list__block-edit`. When you set float to off, youtube embed is visible again:
<img width="1435" alt="nayttokuva 2018-10-6 kello 21 58 59" src="https://user-images.githubusercontent.com/5536354/46574873-46dcbb00-c9b3-11e8-95fb-c1ed6a22795b.png">

**Comment by brandonpayton** [comment]
This appears to be fixed. I'm able to reproduce the issue with 3.9 but no longer on master.

![youtube-block-alignment-test](https://user-images.githubusercontent.com/530877/47200764-366dfe00-d32c-11e8-80c5-cbe3de64c793.gif)
