### ISSUE TITLE
Submit for review unpublishes page when making edits

### ISSUE THREAD

**Issue by Clorith** [WordPress/gutenberg#10154]
When writing changes to a published page, I was somehow not identified as an administrator, but as an author. This means I'm not allowed to publish content, but I can make changes and request an editor or above to publish them.

Making changes to an already published page, there is no `Save draft` option, only `Switch to draft` and `Submit for Review`. When clicking `Submit for Review`, the success message actually informs you that your page has been changed to a draft, and it is then unpublished, which was not what was clicked.

This is on a multisite, making new content I can publish straight away, but any existing pre-Gutenberg content gets the review requirement.

Reproduction:
- Create a page without Gutenberg
- Publish the page
- Enable Gutenberg
- Go to edit the page (does not need to be converted to blocks or anything)
- `Submit for Review` appears instead of `Update`
- Click for review and you are informed that your page has been converted to a draft, despite not clicking that button.

Expected behavior:
When editing an already published post or page, it is expected that the page remains published, but that the changes made are submitted for review, as you do not want content to go away and be re-published after the fact when someone's had a chance to look over an edit.

** Versions **
WordPress (multisite) 4.9
Gutenberg 3.9.0

**Comment by ellatrix** [comment]
@Clorith I'm a bit confused. Do you mean a page or a post? As an author, I don't seem to have the ability to edit pages at all. In case you mean posts, authors have the ability to publish? https://wordpress.org/support/article/roles-and-capabilities/#author This all works fine to me.

Are you still experiencing the same issue?

**Comment by Clorith** [comment]
This is no longer a reproducible issue for me, as such I'll self-close the issue (if anyone else should encounter something similar we can re-investigate at that time).

**Comment by annagoodman** [comment]
I just ran into an issue very similar to this one, without the switching permissions! We have folks with the Editor permission on our site, who do not have permission to publish pages. We want them to be able to edit published pages, and have those published pages stay up while their edits are waiting for approval.

Observed behavior: 
When an Editor is editing an already published page, when they click `Submit for Review`, this message appears and the page unpublishes:
![image](https://user-images.githubusercontent.com/7978434/99019582-760a7280-2511-11eb-82ec-fec42a543e34.png)

Expected behavior:
When editing an already published post or page, it is expected that the page remains published, but that the changes made are submitted for review.

**Comment by sphere-radio-it** [comment]
@annagoodman we have the same problem. Did you find any solution for that?
