### ISSUE TITLE
Buttons don't have open in a new window option

### ISSUE THREAD

**Issue by wanderlustdaily** [WordPress/gutenberg#10219]
When you add a button there's no option to activate the "open in a new window" button.

The same button used in normal links would be appreciated.

I'm currently editing the block in HTML to resolve the issue.

**Comment by chrisvanpatten** [comment]
Hi @wanderlustdaily, thanks for the report!

We have an earlier ticket open about this issue, #8000. And, good news: we also have a fix in the works over at #10128!

Because this is being tracked in other places already, I'll close this as a duplicate but do feel free to comment on #8000 and keep an eye on #10128.
