### ISSUE TITLE
Image alignment bar is not appearing in visible screen space, it's appearing next to previous image

### ISSUE THREAD

**Issue by khushbooinani** [WordPress/gutenberg#10217]
**Describe the bug**
Using Gutenberg 3.9 Pre Release
Clicking on an Image to edit it's alignment is not showing block editing bar in visible screen space and when we scroll up, it's appearing next to another image.

**To Reproduce**
1. Add multiple images in the editor.
2. Click on multiple images to change alignment.
3. Scroll down to 2nd or 3rd image and click again to change alignment.
4. Editing bar will not appear on visible screen area.
5. Scroll up, you will see it there.

**Expected behavior**
If editing an image, editing bar should appear next to it.

**Screenshots**
![img1](https://user-images.githubusercontent.com/16896677/46161177-74827f80-c2a2-11e8-95ed-b1bdf263723e.png)
![img1-1](https://user-images.githubusercontent.com/16896677/46161193-806e4180-c2a2-11e8-86fa-7a2313182dd8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: latest(69.0.3497.100 (Official Build) (64-bit))

**Comment by iamgabrielma** [comment]
I could reproduce this with Gutenberg 4.1.1 :  

<img width="387" alt="screen shot 2018-10-30 at 13 41 02" src="https://user-images.githubusercontent.com/3812076/47770636-be7fda80-dd12-11e8-8685-3986749468bc.png">

When trying to edit the image at the bottom, the floating menu for all images show up at the top of the first image, so most of the times is not visible or easily reachable if the browser is set to normal view, this screenshot is taken at 67% zoom (otherwise does not show up).

**Comment by ellatrix** [comment]
I can't reproduce. @khushbooinani @iamgabrielma is this still an issue in the latest Gutenberg release?
