### ISSUE TITLE
Use Shortcode With-in Paragraph and Blockquote.

### ISSUE THREAD

**Issue by clicken** [WordPress/gutenberg#10241]
**Is your feature request related to a problem? Please describe.**
In the current WP editor toolbar there is a tool I added via a plug-in; This tool allows me to highlight text with-in a paragraph or with-in a blockquote and have a link automatically added. The plug-in is called BibleGateway Links Shortcode. When using the Gutenberg editor the tool isn't available in the toolbar.

**Describe the solution you'd like**
First, I would like the option to use shortcodes with-in paragraphs and the blockquotes.
Second, and equally important, is to have the plug-in tool option in the editor toolbar.

**Describe alternatives you've considered**
I haven't found any alternative solutions for this problem, except to use the current WP editor.
The plug-in tool is used on most of the post created.

Thanks!

**Comment by designsimply** [comment]
Thank you for testing Gutenberg at this stage!

Adding the BibleGateway Links Shortcode plugin link for reference: https://wordpress.org/plugins/biblegateway-links-shortcode/

> First, I would like the option to use shortcodes with-in paragraphs and the blockquotes.

Part of the goal for Gutenberg is to switch away from a dependency on shortcodes and because of that the focus for core developers will be to focus on creating the infrastructure for plugin developers to build inner blocks which will be much easier to use.

> Second, and equally important, is to have the plug-in tool option in the editor toolbar.

This is something the plugin provider will need to update. It is possible to add buttons to the editor toolbar, but it is encouraged to use the [Block API](https://wordpress.org/gutenberg/handbook/block-api/) going forward. [InnerBlocks](https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/inner-blocks/README.md) is what plugin developers in this case will want to explore.

In the short term, using the classic editor plugin will be a good option for you until an alternative plugin using blocks can be created or until the developers for the plugin you are using are able to update their plugin. I noticed the BibleGateway Links Shortcode plugin hasn't been updated in some time, but I will still encourage you to ask about a possible update in their [support forum](https://wordpress.org/support/plugin/biblegateway-links-shortcode) and mention you have tested with Gutenberg and found the plugin does not work. Thank you again for testing and reporting what you've found.
