### ISSUE TITLE
Published Different From Preview in Editor - TOTALLY DIFFERENT

### ISSUE THREAD

**Issue by prwhitney1** [WordPress/gutenberg#10309]
Just finished composing first blog post using Guttenberg.  I love it.  I specified no sidebars to make very visual.  From what I can tell, when published, it published in old format with sidebars and no 5 star review bar at bottom.  THIS SUCKS GUYS.  WANT ME TO STAY.  TELL ME WHAT I DID WRONG OR FIX QUICKLY.

**Comment by designsimply** [comment]
Okay! This was a bit easier for me to understand compared to the other issue you posted. I still need to ask a few questions in order to understand the situation better. Also a note: when you use the Fullscreen Mode (linked in the More menu in the top toolbar), that means sidebars won't be displayed while you are editing, however, whether or not you show sidebars while editing will not affect the sidebars for the site itself. Most often, whether or not sidebars show up on the site itself such as on the home page or the archives or the pages like About Us are either because the Page Template was changed or because the Theme has been updated or because the Theme Options settings have been changed.

What theme are you using?

Have you updated your theme recently?

Have you made any changes at all to the theme options?

What plugin are you using to make the 5-star review bar at the bottom of posts?

It is possible that none of the issues you've raised are related to Gutenberg. Because of that, I would like to move to https://wordpress.org/support/plugin/gutenberg to sort out the problems in a place that's better-suited for troubleshooting. GitHub is where we want to keep bugs, and if we find one we can come back here. The forum is where we can get better help for what you have described so far.

I would also like to say thank you for testing! It's exactly what we need. Seeing your reaction is helpful and I would like to work with you to help you reach your blogging goals. Let's talk at https://wordpress.org/support/plugin/gutenberg in a bit more detail and work these issues out!
