### ISSUE TITLE
Mobile: Inserting an embed zooms in on the page

### ISSUE THREAD

**Issue by alexislloyd** [WordPress/gutenberg#10310]
**Describe the bug**
When inserting an embed block, the placeholder is added and the focus is correct, but the whole page zooms in on mobile.

**To Reproduce**
1. Open or start a new post on a mobile browser (I'm using Safari on iOS 12, iPhone X)
2. Make sure there is some text above where you will insert the embed
3. Insert any embed block (haven't tested all of them, but this definitely happens with Twitter, Facebook, Vimeo, Flickr)
4. The whole viewport zooms in

**Expected behavior**
The page should remain at the same zoom level

**Screen recordings**
http://cld.wthms.co/wFxuKJ 
http://cld.wthms.co/cyjFG1

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 12.0
 - Browser: Safari

**Comment by designsimply** [comment]
Adding side-by-side before-and-after screenshots from the linked video for reference:

<img src="https://user-images.githubusercontent.com/1119271/46451519-bc068100-c764-11e8-9123-6e6b6f78801e.png" width="270"> <img src="https://user-images.githubusercontent.com/1119271/46451529-c294f880-c764-11e8-9b9e-b18c1391c81e.png" width="270">

**Comment by jasmussen** [comment]
This is likely due to the min-width of 360px that embeds have, which combined with the paddings that the editor adds to the canvas, adds up to more than the width of a mobile screen. 

The 360px min-width is necessary because some embeds simply do not support widths smaller than 360px. For example an Instagram embed completely breaks if it's smaller than that arond that number. 

Given editor styles can add any number of different paddings, including ones that aren't very mobile friendly, I'm not sure we can do that much with this ticket, since the zooming effect is "accurate".

We could _force_ the embed smaller than 360px at the mobile breakpoint, and only add that min-width _beyond_ the mobile breaktpoint, this would be trivial to do, and at least then only the embed would be broken, not the editor.

**Comment by jasmussen** [comment]
Submitted https://github.com/WordPress/gutenberg/pull/11961 to fix this.
