### ISSUE TITLE
When I paste the long text into a block block is not recognized and the text does not display

### ISSUE THREAD

**Issue by Jclk123** [WordPress/gutenberg#10349]
I type a lot of information into a block, but the block only displays the first few words. I try a different block and paste the long text into the block, but the block is not recognized and the text does not display. I do not see why the introduction of blocks was considered an advancement over the regular WordPress screen, where ALL of the text remains, and I am free to arrange it in any manner I like, inserting text, pasting text, images, and whatever - all of which is visible after saving. If there is a secret "trick" to using the blocks, I could not find it. I will return to the regular display and hope that this situation is resolved before I am forced to use Gutenberg.

**Comment by designsimply** [comment]
Where are you pasting from (i.e. Word, another app, a web page)?

Any chance you can include the full HTML of one of the paragraphs of content you are trying to paste into a reply here?

**Comment by Jclk123** [comment]
Hello.
I was pasting from Word. One of the shorter paragraphs was:


NEWPORT, OR – October 4, 2018 – A free 2-hour multimedia event, celebrating the Joy of Life, will be continuing its Oregon Coast tour in Newport, on Thursday, October 25, 2018, from 5:30 p.m.-7:30 p.m. at the Samaritan Center for Health Education, 740 SW 9th Street, Newport, OR 97365.

I did not check the HTML to see how the text came across. I only noticed that the text displayed on the Post edit screen, but not on the preview sample. To complete the post I was working on, I retyped all of the information onto the Post edit screen.

My main problem is the blocks. I have created websites using free Google Sites, and found the blocks very annoying and limiting. At the time, I was grateful for WordPress and its Word-like flexibility. Now, WordPress is going backwards, in my opinion, by introducing the limiting blocks from the free website builders into a now-limited website builder for which I am paying. Why would I choose to pay for WordPress if I can get the same limited functionality free?

Thank you for helping me understand the rationale behind the Gutenberg changes.

Jo Calk
Jclk123@outlook.com<mailto:Jclk123@outlook.com>


________________________________

**Comment by designsimply** [comment]
> I type a lot of information into a block, but the block only displays the first few words.

This shouldn't happen. I've tried testing several times and wasn't able to see the same problem happen. I tested with WordPress 4.9.8 and Gutenberg 4.5.1 using Firefox 63.0.3 on macOS 10.13.6. May I ask if you have updated to the latest version of WordPress and Gutenberg and if the problem where typing a lot of information results in only first few words displaying? Also, was that problem happening while you were editing or only once you previewed? May I also ask what OS and browser version you are using?

> I did not check the HTML to see how the text came across. I only noticed that the text displayed on the Post edit screen, but not on the preview sample.

Okay, so when pasting content from Word, it does work in the editor but did not show up in the preview? Several updates have been made since the time you posted about this, and I am wondering if that problem is now fixed for you if you update to the latest version of Gutenberg?

> Why would I choose to pay for WordPress if I can get the same limited functionality free?

The block editor does make some significant changes. Those changes are being made both in order to make editing without the use of code or shortcodes easier and in order to make content more accessible to all parts of the software, including things like menus and the customizer. There are many other reasons, these are the most relevant I can think of right now. Blocks are intended to make editing simpler as well as pave the way for future enhancements. The problems you've raised about typing and not seeing all of that content and not being able to copy content and see it in a preview are things that should not be happening so they are either bugs or some sort of conflict that I don't know how to explain yet based on the information I have for this case so far. If you're willing to update and try again, I can keep working on the issue with you and do my best to help troubleshoot.

**Comment by Jclk123** [comment]
Hi, Sheri,
I appreciate your time and effort attempting to replicate the problems I had with Gutenberg. Although I understand that I would be helping others by providing more details about my experience, I really have no desire to go back to Gutenberg, even for a test. I compare Gutenberg’s blocks to the limited functionality provided by Google Sites for their free websites. I try to understand your excitement with the “new” WordPress, but I find it much too limiting for my uses. I plan to continue with the basic WordPress for as long as I am allowed. If/When forced to use Gutenberg, I will have to make a choice whether to continue with WordPress or to switch to the free Google Sites.

No, I am not resistant to change – when it provides additional functionality. However, I don’t see WordPress as broken in any way, so I don’t see the need to “improve” it by limiting functionality. I realize I may be the only one not embracing Gutenberg, but I much prefer an open area where I can move words, parts of sentences, and full sentences around at will, without having to move between blocks to do so.

You are welcome to close my request. I just wanted to explain my frustration with Gutenberg and my decision to continue with basic WordPress. Best wishes on your new functionality.

Sincerely,
Jo Calk
Jclk123@outlook.com<mailto:Jclk123@outlook.com>


________________________________

**Comment by designsimply** [comment]
Thank you for your response and thoughtful feedback. 

Because I was unable to replicate the issues you mentioned in testing, I don't have a way forward. I am happy to re-try though if more details are provided in the future. I will also note that I'll keep an eye out for similar reports from others and, in that case, I hope to be able to re-visit the issues you've reported here. 

While I'm sorry to hear you're not interested in testing further, I completely understand. It's also worth noting that it's perfectly fine to opt to keep using the Classic Editor as long as you'd like. As for Gutenberg, in looking over your notes again I can see that I did not ask for details such as your OS and browser version and that may be relevant. If you'd like to reply and note those, I'd be happy to have that info on file here. Otherwise, it's no problem and I'll keep forging ahead until I find additional details to test with!
