### ISSUE TITLE
Add Option for Descriptions within Menu Items

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#10340]
Let's add the ability to display a lengthier description under Menu Items, similar to how the post visibility works.

![image](https://user-images.githubusercontent.com/548849/46490290-9d8c9e00-c7d5-11e8-9659-7f03e65c7c7e.png)

It would be useful to use in cases like the focus modes where it's hard for a single title to be self-explanatory.

![image](https://user-images.githubusercontent.com/548849/46490352-d0369680-c7d5-11e8-8ca0-2d5740184f4a.png)

**Comment by shaunandrews** [comment]
Two things feel off to me here:

1) A popover for this setting seems... wrong. I'm not entirely sure why, but I think its because this popover is initiated from the sidebar. There's something strange about the popover within the sidebar. What happened to our lovely accordions?

2) Radios seem... wrong, too. The private option is different from all the rest — if you choose private, WP tries to update the post right away, the other two options requires that you update the post to save the changes. It feels like the private option acts more like a button, than a radio.

**Comment by chrisvanpatten** [comment]
@shaunandrews I think @mtias is referring specifically to the description text part of the Post Visibility popover. The popover itself is already in Gutenberg 😉

**Comment by karmatosed** [comment]
I like @kjellr's descriptions to go with ones we have in sidebar. Let's also align others as part of this.

**Comment by karmatosed** [comment]
@shaunandrews maybe we can iterate on this in another issue? Totally up for that just want to get the descriptions in.

**Comment by alexislloyd** [comment]
My suggestions are below. I'm also suggesting some name edits: I think global toolbar may communicate what it is better than unified toolbar. And I took "mode" out of the other two because it doesn't seem necessary. We could change the header to "Writing mode" because they are all "modes". In addition, I'm trying to have parallelism amongst the phrasing of the descriptions, so they all start with an action verb, explaining to the user what each mode helps them **do**.

**Global toolbar**
_Access all block and document tools in a single place_

**Spotlight**
_Focus on one block at a time_

**Full Screen**
_Work without distraction_

**Comment by aduth** [comment]
Pull request (with proposed texts) at #10802
