### ISSUE TITLE
the top red text bar prompts the publish failed

### ISSUE THREAD

**Issue by sceic** [WordPress/gutenberg#10420]
**Describe the bug**
the top red text bar prompts the publish failed, but switching to the classic editor, there will be no such problem.

**To Reproduce**
1. Edit a published post, 
2. click on the publish-button 
3. See error

**Screenshots**
https://www.chiefadv.com.cn/wp-content/uploads/2018/10/%E6%8D%95%E8%8E%B7-1024x543.jpg

![-1024x543](https://user-images.githubusercontent.com/1119271/46984052-8a64b280-d0a0-11e8-9fe1-58f942aa1af9.jpg)

**Desktop (please complete the following information):**
 - OS: [win10 1803]
 - Browser [chrome]
 - Version [ 69.0.3497.100 x64]

**Additional context**
- 3.9.0 of Gutenberg.

**Comment by designsimply** [comment]
This problem doesn't happen for me in testing. Would it be possible for you to open your browser's developer tools and go to the console panel then try publishing again and reply back with any error messages that show up in the console?

It is worth noting that the classic editor and the Gutenberg editor use different mechanisms for publishing. The Gutenberg editor uses an API. If the API has been blocked by a security plugin or server setting for some reason, then this could be the cause of the problem in your case and knowing the error messages may help provide some clues about why the problem is happening for you and not for others.

**Comment by designsimply** [comment]
Please verify your API is working without problems. You can do this by adding `wp-json` to the end of your domain in the browser and checking that no errors appear.

Please try testing without other plugins active and after updating to the latest version of Gutenberg or using WordPress 5.0-RC. If you are still having problems at that point and you are able to check the console in your browser for errors by opening it first and then clicking publish to see the updating failed error. If any errors are showing, they may help to narrow down the source of the problem in your case.

Thank you!
