### ISSUE TITLE
A more obvious +Insert button?

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#1047]
I am testing: https://testgutenberg.wpkonsulterna.se/wp-admin/admin.php?page=gutenberg

I feel that the +Insert button is not easy to locate.

If I remember right there was som talk of having it to the left of a block (showing up on hover). Placing it close to where one needs to use it.

**Comment by jasmussen** [comment]
The plus icon for insert works well on WordPress.com, so this is a pattern I suspect will quickly be learned, especially since we have a label in the toolbar.

![screen shot 2017-06-07 at 12 37 42](https://user-images.githubusercontent.com/1204802/26874516-3584e0bc-4b7e-11e7-997d-dfc0861ace39.png)

You are correct, though, that mockups had an inserter on the side. For V1 of Gutenberg we have decided to simplify this flow (see discussion in #833 ), to having an inserter at the top, and an inserter at the bottom of the document.

This doesn't mean that we can't revisit this decision based on usertests. But it's likely going to be what's in V1.

**Comment by paaljoachim** [comment]
I am thinking something like this:

![inserter-button-beside-content](https://user-images.githubusercontent.com/5323259/26875124-bb11ae2a-4b80-11e7-9cc1-5a22e2a9c514.jpg)

**Comment by jasmussen** [comment]
Yep, in some of the past discussions we explored something like that indeed, in particular in #323. This is still something that can be revisited.

**Comment by jasmussen** [comment]
Closing this for now, we can always reopen.
