### ISSUE TITLE
Block spacing control plus row component

### ISSUE THREAD

**Issue by ombion** [WordPress/gutenberg#10494]
**Is your feature request related to a problem? Please describe.**

If the goal of Gutenberg is to allow full layout control and customization, then I think it's still missing an essential feature which is spacing control between blocks and layout elements. It takes extra work and time consuming having to set the spacing using custom CSS for every element on the layout.

**Describe the solution you'd like**

Most if not all major page builder editors that Gutenberg to replace down the line offer the essential spacing control function built in the UI. Every block, such as image, text, headers, button, etc should come with margin and padding options with 0 or none as default setting.

**Describe alternatives you've considered**

Alternatively and better yet, having the row component is a handy wrapper to contain a group of blocks. With each row, you can set margin, padding, and background image/color. With these feature in place, I you can use Gutenberg to compose pretty any kind of layout without having to spend a lot of time in custom CSS.

**Comment by designsimply** [comment]
I think you may be confusing block editors and page builders. Gutenberg is at heart a block editor, and by having content defined in blocks it will make creating page builders much easier in the future. Gutenberg itself, however, is currently not a page builder and so that's why those kinds of layout options aren't in place yet. In the future, some layout options will become a part of WordPress itself and will use blocks. Other third-party page builders will also adopt using blocks since they are becoming a the basic unit for content in WordPress.
