### ISSUE TITLE
Unable to insert links when clicking on an autocomplete suggesion

### ISSUE THREAD

**Issue by slimmilkduds** [WordPress/gutenberg#10496]
**Describe the bug**
When I insert a link nothing happens 

**To Reproduce**
1. add paragraph
2. select text and click add link
3. trigger the autocomplete dropdown
4. Click on a dropdown item

This has not been a problem in previous versions

**Screenshots**
![linkinsert](https://user-images.githubusercontent.com/40266703/46785345-c19a3300-cd31-11e8-8fe1-5d4831cbf27e.gif)

**Desktop (please complete the following information):**
Chrome
4.0 rc

**Comment by talldan** [comment]
The issue is that onClickOutside is being triggered when clicking on one of the autocomplete suggestions here:
https://github.com/WordPress/gutenberg/blob/f2da3e5a069c4992903be5e179f4a3ddb126f400/packages/editor/src/components/rich-text/format-toolbar/link-container.js#L176-L180

Because the dropdown suggestions aren't rendered as a direct descendent of the link-container popover, it's detected as a valid click outside.

**Comment by iseulde** [comment]
I'm a bit surprised to find that the list is not the same component as the autocomplete one.

**Comment by talldan** [comment]
Thanks for the report @slimmilkduds! The fix has now been merged and the release for 4.0 will be patched with the fix.

**Comment by slimmilkduds** [comment]
Great!
