### ISSUE TITLE
Screen Options missing or at least unique IDs

### ISSUE THREAD

**Issue by La-Geek** [WordPress/gutenberg#10511]
When you work with clients and they are unexperienced WordPress users, one common way is to remove unneeded items. So the client is less confused about all these new options.

We can do this with screen options and checkbox.
![screen_options](https://user-images.githubusercontent.com/1585416/46804841-f4f5b580-cd63-11e8-8205-9f2b86494354.gif)
 
But these screen options are missing. Okay, not the big deal, you think. You could write some code in functions.php to hide unnessary items, with display:none, But nope. They don't have unique CSS IDs or Classes, like the items in the sidepanel on left side do have for example.

![unique_css_class](https://user-images.githubusercontent.com/1585416/46805135-a4cb2300-cd64-11e8-825b-fddc248888cb.gif)

Please, either add screen options again, or implement unique CSS handles

**Comment by chrisvanpatten** [comment]
Hi @La-Geek —

We have a new option screen in progress over at #10215, and more discussion over in #10210.

I'd recommend you to take a look over there. It should be included in the next version of Gutenberg, version 4.1.

Because we have an existing issue open (and a solution in the works) I'll close this up and recommend you follow along over at those other issues :)

Thanks for the report!
