### ISSUE TITLE
Add capability to use alternate editing feature plugins such as TinyMCE Advanced

### ISSUE THREAD

**Issue by subguy** [WordPress/gutenberg#10579]

**Comment by designsimply** [comment]
Because this is a new editor written in a different way compared to TinyMCE, it won’t have the same toolbar items from the old editor. The plugins that add such items will need to be updated to the new editor.I checked the support forum for TinyMCE Advanced and noticed a comment that says doing just that is being considered as a planned update: https://wordpress.org/support/topic/continued-development-of-tinymce-advanced-after-gutenberg-becomes-default/#post-10746565

Thank you for taking the time to test Gutenberg at this stage and for making suggestions. I am going to close this issue because it is something that should be handled by plugin developers separately.
