### ISSUE TITLE
Page Settings attributes save and display issue

### ISSUE THREAD

**Issue by tfprado** [WordPress/gutenberg#10661]
I have been using the new Gutenberg editor with a WordPress installation on a local XAMPP server. On occasion the featured image tab does not show up at all. The page settings tab also does not always display properly. When it does it will often not properly upload the changes during submit, or start "auto-saving" and not allow me to publish my changes.

Switching to classic editor will sometimes lose some of the Gutenberg content but allows me to set a featured image and page settings without an issue.

**Comment by designsimply** [comment]
More information is needed and so I'm closing this issue until we can get more data.

@tfprado several updates have been made since you first posted. If it's possible for you to update to the latest version of Gutenberg and try again, please re-open this issue if you're still having trouble at that point and note which version you are testing with and drop in a screenshot of the settings tab that isn't displaying properly—I'd love to have a closer look at that.
