### ISSUE TITLE
Handbook: add "Components Package Reference" md file

### ISSUE THREAD

**Issue by drw158** [WordPress/gutenberg#10702]
Currently, the file doesn't exist, but it is referenced in the handbook.

https://wordpress.org/gutenberg/handbook/components/

https://raw.githubusercontent.com/WordPress/gutenberg/master/packages/components.md

We should add one, and also add a list of available components. It would have to be manually updated, unless someone has an alternate solution.

**Comment by gziolo** [comment]
It looks like it was fixed with the recent handbook reorganization.

https://wordpress.org/gutenberg/handbook/components/ redirects to https://wordpress.org/gutenberg/handbook/designers-developers/developers/components/.

The list of components is listed in the left side menu, example page:
https://wordpress.org/gutenberg/handbook/designers-developers/developers/components/autocomplete/
