### ISSUE TITLE
Testing: Stub all oEmbed requests with mocked versions of their expected results

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#10710]
Following up on #10709, `test/e2e/test-mu-plugins/stub-embeds.php` should be updated to return properly mocked results from the oEmbed providers we're testing.

**Comment by notnownikki** [comment]
Please see https://github.com/WordPress/gutenberg/pull/10709#pullrequestreview-165877244 - I think we need to keep an actual embed request to check that people's demo pages aren't going to be marked dirty.

**Comment by notnownikki** [comment]
I think this can be closed now.

`test/e2e/specs/demo.test.js` uses the new `setUpResponseMocking` to try to get the live embed from Vimeo, but fall back to a mock response if Vimeo is having problems. That's so we can test with a live response, but not hold up _every_ pending PR if Vimeo is down.

`test/e2e/specs/embedding.test.js` mocks every embed response, so that the test behaves in a predictable way. It also uses `setUpResponseMocking`.

`setUpResponseMocking` isn't embed specific either, so we could use it to test unexpected network behaviour, etc.
