### ISSUE TITLE
Searching for blocks with / stopped working for Cyrillic

### ISSUE THREAD

**Issue by anelkata** [WordPress/gutenberg#10775]
After I updated to v4 yesterday the / block search stopped showing hits for search terms using Cyrillic characters. Before the update this was working fine.

On typing the slash, the blocks with Cyrillic names appear in the popup, but disappear on typing a Cyrillic character after the slash. Typing a Latin character returns results as usual. The search in the + button menu is working normally and returns results for both Cyrillic and Latin.

I attach screenshots for all cases.

![1](https://user-images.githubusercontent.com/42134627/47198398-a1dbbe00-d374-11e8-9827-87fbd41dd7e7.png)
![2](https://user-images.githubusercontent.com/42134627/47198399-a1dbbe00-d374-11e8-9226-e6ba6afd6f90.png)
![3](https://user-images.githubusercontent.com/42134627/47198400-a1dbbe00-d374-11e8-9717-8f8c7f121016.png)
![4](https://user-images.githubusercontent.com/42134627/47198401-a2745480-d374-11e8-8061-009d2f211783.png)

**Comment by Soean** [comment]
Related to #10489

**Comment by mcsf** [comment]
This is a different issue from #10489.

Latin-scripted languages like German can get by with `lodash#deburr`, which — aside from allowing _u_ to "match" _ü_ — guarantees that the autocompleter input is plain ASCII. ASCII input is a requirement for the way Autocomplete currently works, since it relies on the `\w` RegExp character class to target the user's input:

https://github.com/WordPress/gutenberg/blob/a563dc773f928f924a81116b1be43cc0a79308bf/packages/components/src/autocomplete/index.js#L402

Per [MDN's page on RegExp](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Regular_expression_and_Unicode_characters):
> As mentioned above, `\w` or `\W` only matches ASCII based characters; for example, "a" to "z", "A" to "Z", "0" to "9" and "_". To match characters from other languages such as Cyrillic or Hebrew, use `\uhhhh`, where "hhhh" is the character's Unicode value in hexadecimal.

**Comment by mcsf** [comment]
Related discussion in ECMA262: https://github.com/tc39/ecma262/issues/1020

**Comment by mcsf** [comment]
Fix in #10961.
