### ISSUE TITLE
Disappearing Text/Selecting Text Causes Text to Disappear

### ISSUE THREAD

**Issue by TheCurbAu** [WordPress/gutenberg#10780]
When writing up a post, and then posting said post, sections of text disappear, and in turn, disappear from the saved draft. This has happened multiple times. 

On top of this, when cutting and pasting text from one section to another, it appears to remove sections of text around where you have pasted said text. The same goes for hyperlinking in words. 

Highlight a word, and then paste a hyperlink over the word and it may remove the entire word or the whole sentence. 

I expected it to hyperlink safely without removing a word. Alternatively, when I post a post, I don't expect sections of the text to disappear. 

![capture](https://user-images.githubusercontent.com/44286933/47204010-ba6bc880-d3b4-11e8-902d-dd9da87f0772.JPG)

Where it says 'but, ask yourself if you've played Spider-Man', there was another three or four sentences behind that. Once I hit publish, those sentences disappeared and were unrecoverable via the revision option.

**Comment by designsimply** [comment]
Thank you for testing Gutenberg and for writing in about this issue! I have been testing Gutenberg pretty extensively and have not run into this problem, so I'd like to learn a bit more about your writing environment.

May I ask your OS and browser version? I am using Firefox 62.0.3, Chrome 69.0.3497.92, and Safari 12.0 on macOS 10.13.6 and also have access to Chrome and Edge on Windows 10. I test with all of those, to varying degrees, on a regular basis.

When you cut and paste, are you using the `Command+C` and `Command+V` keyboard shortcuts for that?

At the times the text disappears, am I understanding correctly that it happens both after you hit the "Publish" button or if you paste text or a link? If you click "Save Draft" and then reload the page, does the problem with the "Publish" button go away?

Would you be able to try checking the console and network panels in your web browser tools the next time you see the problem happen to see if you can spot any errors? I am not sure whether any will show up for this case, but I do think it's worth checking if possible.

From your description, it sounds like the problem happens sometimes but not other times and that it's unpredictable. Is that right, or can you think of specific steps that will make the problem happen every single time?

Can you list your active plugins in a reply here so we have them on record for reference in case source of the problem turns out to be a plugin conflict?

**Comment by designsimply** [comment]
> If it pops up again I'll keep an eye on the console and network panels to see if anything appears.

Closing the issue since we haven't heard anything back and you mentioned the problem wasn't happening the last time you tested. If you find the problem pops up again, please re-open the issue and we'll take another look together!
