### ISSUE TITLE
Input validation for shortcode block

### ISSUE THREAD

**Issue by iamgabrielma** [WordPress/gutenberg#10790]
**Describe the bug**

If we add an URL into the shortcode block, it accepts it and the link is displayed in the site front-end.

**To Reproduce**
1. Create a shortcode block
2. Add an URL in the text field
3. Publish

**Expected behavior**
To get some error message when something that is not a shortcode is added.

**Screenshots**

**Back-end:**
![screen shot 2018-10-18 at 14 33 0011](https://user-images.githubusercontent.com/3812076/47213607-bbf1bc80-d3c5-11e8-985c-8441ace59bf3.png)

**Front-end:**
<img width="675" alt="screen shot 2018-10-18 at 14 33 00" src="https://user-images.githubusercontent.com/3812076/47213611-c14f0700-d3c5-11e8-9c0d-fa8bf3c17db1.png">

**Desktop (please complete the following information):**
 - OS: El Capitan 10.11.6
 - Browser Firefox 62.0.3
 - Gutenberg 4.0

**Additional context**

Reported originally in the comments on #7357  when I was testing something else

**Comment by swissspidy** [comment]
As mentioned in https://github.com/WordPress/gutenberg/issues/7357#issuecomment-431314136, `do_shortcode()` won't do anything to a non-shortcode string like that, but the URL is picked up by the WordPress embed handler and turns it into a proper embed.

**Comment by t-hamano** [comment]
From my understanding, I don't think this is an issue specific to the Shortcode block or Gutenberg. For example, in the Classic Editor, you can simply enter a URL that is allowed as an oEmbed provider and it will be converted to embedded content in the front end.

![shortcode](https://github.com/WordPress/gutenberg/assets/54422211/80890536-ac48-408b-9165-32c8f912d880)

I think this is expected behavior in WP core, so I'll close this issue, but if there's anything I've missed, please comment.
