### ISSUE TITLE
ugly word break für reusable blocks translation (at least for german) if default name is used

### ISSUE THREAD

**Issue by Presskopp** [WordPress/gutenberg#10808]
![image](https://user-images.githubusercontent.com/18373563/47232711-b64da400-d3d0-11e8-972d-3007cf32bd98.png)

Solution could be

```
span.editor-block-types-list__item-title {
    white-space: nowrap;
    text-overflow: ellipsis;
    overflow: hidden;
}
```

but I'm not so very happy with it

![image](https://user-images.githubusercontent.com/18373563/47232860-34aa4600-d3d1-11e8-9959-3e8cb079f479.png)

**Comment by La-Geek** [comment]
Good catch!
An easy solution would be, to set two columns for reusable blocks instead of three

`
.components-panel__body.editor-inserter__reusable-blocks-panel.is-opened .editor-block-types-list__list-item {
    width: 50%;
}
`

![2cols](https://user-images.githubusercontent.com/1585416/47235934-d1bdac80-d3da-11e8-9159-3826e76a87a9.png)

**Comment by Soean** [comment]
I have an open ticket about this topic: #8047
We will try to work on it tomorrow at the contributor day in cologne.

**Comment by La-Geek** [comment]
If hyphenator.js is no option, you could make the width more flexible:
<pre>
.editor-block-types-list__list-item {
    width: auto;
    max-width: 50%;
    min-width: 33.33%;
}
</pre>

**Comment by designsimply** [comment]
Closing to consolidate with #8047 based on @Soean's comment.

Thank you for raising the issue!
