### ISSUE TITLE
“More” and “Page break” blocks: dashed line missing in the editor.

### ISSUE THREAD

**Issue by pagelab** [WordPress/gutenberg#10817]
**Describe the bug**
The dashed line that should appear behind the “More” and “Page break” blocks is missing.

**To Reproduce**
1. Add a “More” (or “Page break”) block.
2. Inspect the block's CSS and see that there is a dashed line border specified in the `::before` pseudo element that it's not appearing on the editor. 

**Screenshots**

![screen-recording-2018-10-19-17-04-44](https://user-images.githubusercontent.com/1451087/47241706-10e00380-d3c3-11e8-9619-95347b5a1399.gif)

**Expected behavior**
The dashed line should be displayed to maintain visual compatibility with the `more` tag, used on the Classic Editor, as seen below:

![more-tag-classic-editor](https://user-images.githubusercontent.com/1451087/47241750-3240ef80-d3c3-11e8-8610-b6800b415872.png)

**Solution**
This can be solved simply by defining the z-index of the parent element (`.editor-block-list__block-edit`), as seen on the animated GIF above.

**Desktop:**
 - MacOS X 10.12
 - Chrome 69

**Additional context**
 - Gutenberg 4.0.0
 - WordPress 4.9.8
 - Twenty Seventeen.
 - No other plugins.

**Comment by swissspidy** [comment]
I thought I reported this already because I have been working on these blocks, but I guess I was wrong :-)

You're right, this should be fixed.

Also, as can be seen in your gif, the "read more" text is initially cut off. Probably something strange going on with the input field length calculation. This should be addressed too.
