### ISSUE TITLE
shift+enter bug

### ISSUE THREAD

**Issue by hosseinfarnia** [WordPress/gutenberg#10824]
Hi
When I press shift+enter at the end of a sentence and then paste a sentence from somewhere else, the pasted sentence jumps to the lower line.

**Comment by davoraltman** [comment]
I can reproduce this. When I check the HTML editor afterward, it looks like an additional <br> tag gets added.

**Comment by azaozz** [comment]
I'm not sure I understand the issue :)

Shift + Enter inserts a line break in pretty much all editors. Should the behavior be different here?

**Comment by ellatrix** [comment]
@hosseinfarnia @davoraltman Thanks for the bug report. I cannot reproduce the issue. This may be because of various fixes to rich text recently. I tried it here: https://wordpress.org/gutenberg/, and it works.

If you can still reproduce with Gutenberg **5.4**, please reopen the issue with more detailed steps to reproduce.

**Comment by hosseinfarnia** [comment]
It has been fixed.
Thanks

**Comment by davoraltman** [comment]
Looks like it's been fixed. Thank you!
