### ISSUE TITLE
Initial Letter overlaps

### ISSUE THREAD

**Issue by La-Geek** [WordPress/gutenberg#10832]
**Describe the bug**
Simple:
Two Paragraph Blocks below each other, both with inital letter. Result see screenshots

![backend](https://user-images.githubusercontent.com/1585416/47255509-9f5f8e00-d472-11e8-86d8-de36ef13f6c0.png)**Backend**

![frontend](https://user-images.githubusercontent.com/1585416/47255514-aab2b980-d472-11e8-88f6-cd5f7da814fd.png)**Frontend**

Of course, one block with initial letter also overlaps the container.

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit (recent version)
 - Browser Chrome and Firefox (recent versions)
 - Gutenberg version: 4.1

**Comment by adamleone** [comment]
Hello! 

I was able to replicate this issue: http://cld.wthms.co/czhP01 

However, this did resolve when more lines of text were put in place. http://cld.wthms.co/q8C0jw

**Comment by karmatosed** [comment]
I think we should just for now add in to have the block when dropcap is applied be height of the entire block. I suspect this has other implications for floats, columns and therefore would like to find out if this is something we need to explore differently.

**Comment by alexislloyd** [comment]
@karmatosed are you suggesting implementing @La-Geek's suggestion? I think that would work.

**Comment by karmatosed** [comment]
Removing feedback label as we have a way forward.

**Comment by designsimply** [comment]
Tested and confirmed using WordPress 4.9.8 and Gutenberg 4.2.0-rc.1 that when there are multiple short paragraphs using the drop cap option one after another the drop caps overlap in odd ways.

![screen shot 2018-11-03 at 9 28 48 am](https://user-images.githubusercontent.com/1119271/47954029-e6f21980-df4a-11e8-9127-5766b784baa7.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=15503&action=edit running WordPress 4.9.8 and Gutenberg 4.2.0-rc.1 using Firefox 63.0 on macOS 10.13.6.</sup>

**Comment by jasmussen** [comment]
This is a good ticket, and thank you, specifically, for the proposed solution shown here: https://github.com/WordPress/gutenberg/issues/10832#issuecomment-431575628

However I disagree that this is the right solution, and at the end of this comment I'm going to suggest a different approach. But the reason I disagree is that we're making a pretty bold assumption about how users author content, in order to solve the situation where the two paragraphs have background colors.

Here's what Jane Austen would've written:

![screenshot 2018-11-05 at 08 50 19](https://user-images.githubusercontent.com/1204802/47984751-d8853880-e0d7-11e8-8da9-20ae6a316d5a.png)

As you can see, not only does the overflow value cut off the I (and this will vary on a theme by theme, font by font basis), but it causes paragraph 2 to not flow around the text as it arguably should.

Here's what that looks like in master:

![screenshot 2018-11-05 at 08 51 33](https://user-images.githubusercontent.com/1204802/47984809-023e5f80-e0d8-11e8-9b1e-890e5e1b7354.png)

Okay maybe not ideal either, perhaps Jane should cut back on the dropcap usage. But arguably this is more correct.

So, what about this problem:

![screenshot 2018-11-05 at 08 54 16](https://user-images.githubusercontent.com/1204802/47984945-7a0c8a00-e0d8-11e8-8b22-6ee67ca693cb.png)

I was hoping we could elevate the z index of the first letter so it would always be on tip. But sadly, first-letter CSS doesn't allow us to do this. But the least we could do is scope the rule so only paragraphs with a background color has the overflow rule:

```
p.has-drop-cap.has-background {
    overflow: hidden;
}
```

![screenshot 2018-11-05 at 09 00 13](https://user-images.githubusercontent.com/1204802/47985214-3bc39a80-e0d9-11e8-87ff-f1fa2606253a.png)

That's still not ideal, because as you can see the padding below the dropcap is smaller. But I suppose it does fix this particular issue.

With regards to the issue reported by @designsimply in https://github.com/WordPress/gutenberg/issues/10832#issuecomment-435596471, we could add a clearing rule for that:

![screenshot 2018-11-05 at 09 01 56](https://user-images.githubusercontent.com/1204802/47985293-762d3780-e0d9-11e8-8204-6cf43a809ed7.png)

So that would be:
```
p.has-drop-cap {
    clear: left;
}
```

But that's also not a nice fix, honestly, because then you can't do this:

![screenshot 2018-11-05 at 09 03 42](https://user-images.githubusercontent.com/1204802/47985375-b7254c00-e0d9-11e8-9d94-4947c4adb506.png)

So the bottomline is: the following is probably an okay solution:

```
p.has-drop-cap.has-background {
    overflow: hidden;
}
```

But I also feel like we should be VERY careful with applying too many "fixes" to these situations. At some point we have to rely on editorial responsibility. Or we end up cauterizing legitimate layout opportunities in the name of fixing edgecases.

**Comment by La-Geek** [comment]
> but it causes paragraph 2 to not flow around the text as it arguably should.
I disagree. If you want the text flow around the initial letter, you should not use a new block (paragraph), instead use 2 linebreaks (hit strg/control and enter twice). 

> As you can see, not only does the overflow value cut off the I (and this will vary on a theme by theme, font by font basis),
Good Catch

The line-height is set to low = .68;

With this code it should not cut off the end of the initial letter:

`p.has-drop-cap {
    overflow: hidden;
}
p.has-drop-cap:not(:focus):first-letter {
    line-height: 1;
}`

**Comment by La-Geek** [comment]
Oh, in preview two linebreaks work perfect. But after saving the `<br><br>` tags are converted into a **`<p>` tag? <- In my opinion this is a separate bug.**

However, as mentioned in [#10832 comment](https://github.com/WordPress/gutenberg/issues/10832#issuecomment-435785720) it depends on font-size, font-family and browser how the first letter is placed. Dropcap is crap with the current possibilities. There exists an old polyfill from adobe "dropcap.js" but it calculates with pixels. There are variations that calculate it responsive. But as far as I know, this solutions work with a CSS class (or ID) in combination with an inline tag around the intial letter and not with the pseudo class `:first-letter`.

All would be easier, if the CSS property `initial-letter: 3` ( "3" as example) would have a good browser support, but it has not.

**Comment by annezazu** [comment]
Just wanted to leave an updated comment on this since this issue still exists in the WordPress 5.x milestone for future releases. This is up to date as of WordPress 5.6 and Gutenberg 9.8.3:

The issue of overlapping drop caps seems to be resolved:

<img width="694" alt="Screen Shot 2021-02-02 at 7 46 19 PM" src="https://user-images.githubusercontent.com/26996883/106690893-cd0f6900-658f-11eb-8e56-88ba94e951b2.png">

The issue of a second paragraph after a drop cap not flowing around the text/drop cap remains:

<img width="701" alt="Screen Shot 2021-02-02 at 7 48 39 PM" src="https://user-images.githubusercontent.com/26996883/106690978-f4663600-658f-11eb-9ece-e5d345162e93.png">

**Comment by jasmussen** [comment]
Thanks for the followup, Anne! In looking at the two screenshots you made, it seems clear to me that we can't solve the issue of overlapping dropcaps, AND the issue of the second paragraph not flowing correctly:

- By solving the overlapping dropcaps, we are forcing the 2nd paragraph to clear the first one.
- By forcing the 2nd paragraph to clear the first one, we are causing the paragraph to not flow correctly.

As far as I can see, there are only two ways to fix this:

1. Go with [this suggestion](https://github.com/WordPress/gutenberg/issues/10832#issuecomment-435785720), and apply the "clearing" only when the paragraph has a background:

```
p.has-drop-cap.has-background {
    overflow: hidden;
}
````

I'm going to try that in a quick PR. Especially because the not clearing issue breaks more than it fixes:

<img width="1250" alt="Screenshot 2021-02-03 at 09 53 36" src="https://user-images.githubusercontent.com/1204802/106722021-bc013f00-6605-11eb-9ba8-8588bbe848fb.png">

2. Decide that dropcaps should not clear at all, and that it's up to the editor of the post to ensure they use a dropcap appropriately. In other words, we allow creative freedom here. Maybe someone _wants_ to be able to do this:

<img width="990" alt="Screenshot 2021-02-03 at 09 55 33" src="https://user-images.githubusercontent.com/1204802/106722258-071b5200-6606-11eb-8edb-fa21055e70f3.png">

**Comment by jasmussen** [comment]
Created https://github.com/WordPress/gutenberg/pull/28685 as a way to address this one.
