### ISSUE TITLE
Handbook: IA Reorganization

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#10911]
This issue goes more in-depth into the Handbook IA, as mentioned in #10549:

> Rework the IA (information architecture) and navigation of the handbook to better cover the main areas outlined above. As it stands, it's incredibly confusing to navigate and has a lot of overlap between sections.

I've been taking a look at how we can reorganize the existing Handbook content into the five new categories (High Level Principles, Human Interface Guidelines: Design and Dev, Code and API Documentation, Resources and References, Onboarding).

<hr />

<ol><li>High Level Principles<ul><li><a href="https://wordpress.org/gutenberg/handbook/">Introduction</a></li><li><a href="https://github.com/WordPress/gutenberg/blob/master/docs/principles.md">Principles</a></li><li><a href="https://wordpress.org/gutenberg/handbook/design/">Design Principles</a></li></ul></li><li>Human Interface Guidelines: Design and Dev<ul><li><a href="https://wordpress.org/gutenberg/handbook/language/">The Language of Gutenberg</a></li><li><a href="https://github.com/WordPress/gutenberg/blob/master/docs/principles/the-block.md">The Block as the Interface</a><ul><li><a href="https://wordpress.org/gutenberg/handbook/design/design-patterns/">Patterns</a></li></ul></li><li>The Value of Placeholders and Guides<ul><li>Content should be grabbed from existing pages, since this information is currently interspersed between a lot of sections.<ol><li><a href="https://wordpress.org/gutenberg/handbook/language/">The Language of Gutenberg</a></li><li><a href="https://wordpress.org/gutenberg/handbook/design/block-design/">Block Design Best Practices</a> </li></ol></li></ul></li><li>Components as a Means for Consistency<ul><li>We’ll be able to grab some of this content from existing pages, but will likely have to write most of it from scratch.</li><li>Would be good to also expand on accessibility here.</li></ul></li><li>Plan best practices for block building, use examples<ul><li><a href="https://wordpress.org/gutenberg/handbook/design/block-design/">Block Design Best Practices</a></li></ul></li><li>Best practices for extending Gutenberg outside of blocks<ul><li>Registering extra sidebars</li><li>Meta boxes</li><li>etc.</li></ul></li></ul></li><li>Code and API Documentation<ul><li><a href="https://wordpress.org/gutenberg/handbook/block-api/">The Block API</a><ul><li><a href="https://wordpress.org/gutenberg/handbook/language/grammar/">The Gutenberg block grammar</a></li><li><a href="https://wordpress.org/gutenberg/handbook/block-api/attributes/">Attributes</a></li><li><a href="https://wordpress.org/gutenberg/handbook/block-api/block-edit-save/">Edit and Save</a></li><li><a href="https://wordpress.org/gutenberg/handbook/block-api/rich-text-api/">RichText API</a></li><li><a href="https://wordpress.org/gutenberg/handbook/block-api/deprecated-blocks/">Deprecated Blocks</a></li></ul></li><li><a href="https://wordpress.org/gutenberg/handbook/templates/">Templates</a></li><li><a href="https://wordpress.org/gutenberg/handbook/components/">Components</a></li><li><a href="https://wordpress.org/gutenberg/handbook/extensibility/">Extensibility</a><ul><li><a href="https://wordpress.org/gutenberg/handbook/extensibility/extending-blocks/">Extending Blocks</a></li><li><a href="https://wordpress.org/gutenberg/handbook/extensibility/extending-editor/">Extending Editor</a></li><li><a href="https://wordpress.org/gutenberg/handbook/extensibility/meta-box/">Meta Boxes </a></li><li><a href="https://wordpress.org/gutenberg/handbook/extensibility/theme-support/">Theme Support</a></li></ul></li><li><a href="https://wordpress.org/gutenberg/handbook/packages/">Packages</a><ul><li>Package List</li><li><a href="https://wordpress.org/gutenberg/handbook/data/">Data Package</a></li></ul></li></ul></li><li>Resources and References<ul><li>General<ul><li><a href="https://wordpress.org/gutenberg/handbook/reference/history/">History</a></li><li><a href="https://wordpress.org/gutenberg/handbook/reference/glossary/">Glossary</a></li><li><a href="https://wordpress.org/gutenberg/handbook/reference/faq/">FAQs</a></li><li><a href="https://wordpress.org/gutenberg/handbook/reference/release/">Release Process</a></li><li><a href="https://wordpress.org/gutenberg/handbook/reference/repository-management/">Repository Management</a></li><li><a href="https://wordpress.org/gutenberg/handbook/reference/deprecated/">Deprecated Features</a></li></ul></li><li><a href="https://wordpress.org/gutenberg/handbook/design/design-resources/">Design Resources</a></li><li>Coding Resources<ul><li><a href="https://wordpress.org/gutenberg/handbook/reference/coding-guidelines/">Coding Guidelines</a></li><li><a href="https://wordpress.org/gutenberg/handbook/reference/testing-overview/">Testing Overview</a></li><li><a href="https://wordpress.org/gutenberg/handbook/reference/scripts/">Scripts</a></li></ul></li><li><a href="https://wordpress.org/gutenberg/handbook/outreach/">Outreach</a><ul><li><a href="https://wordpress.org/gutenberg/handbook/outreach/articles/">Articles</a></li><li><a href="https://wordpress.org/gutenberg/handbook/outreach/meetups/">Meetups</a></li><li><a href="https://wordpress.org/gutenberg/handbook/outreach/talks/">Talks</a></li><li><a href="https://wordpress.org/gutenberg/handbook/outreach/resources/">Resources</a></li></ul></li></ul></li><li>Onboarding<ul><li><a href="https://wordpress.org/gutenberg/handbook/blocks/">Creating Block Types</a></li></ul></li></ol>

<hr />

Some questions:
- Does this organization make sense?
- Can we break up these categories into further sub-categories?
- Am I missing any pages?

**Comment by chrisvanpatten** [comment]
I'd love to see some documentation for post type templates and theme support moved out into "Onboarding" and see Onboarding get three sub-sections for Users, Themes, and Plugins.

This would basically serve as "If you're in Group X, here's what you need to know about Gutenberg".

The revised section would also include the "How to switch" and "How to not switch (aka Classic Editor)" documentation based on the suggestions [over here](https://github.com/WordPress/gutenberg/issues/10549#issuecomment-431624548).

One proposed structure:

+ Onboarding/Getting Started
    + What to do before updating to 5.0 (aka backup, test in a staging site if you can)
    + How to keep the Classic Editor experience (Classic editor plugin)
    + Themes (#10764)
        + Theme support options
        + Post type templates
        + Block markup and CSS classes to target
    + Plugins
        + Notes on meta box compatibility
        + Links to—or a simplification/merged version of—@danielbachhuber's documentation on hooks/functionality that are deprecated or replaced in g7g
    + Users
        + Meet the new editor UI
        + Basic FAQ/"How do I do X" section

**Comment by mtias** [comment]
Thanks @melchoyce this is great start.

I prefer "Getting Started" to "Onboarding" as a term. I also think "Getting Started" could potentially be placed under the HIG.

@chrisvanpatten I don't think we should move the documentation per se as people wanting to find out about theme support APIs should still be able to find it there without having to go through the "onboarding/getting started" section.

cc @pento how should we handle URL updates in the case of invalidating permalinks?

**Comment by mtias** [comment]
The other point to consider is how we call these top level sections from a navigation perspective, as they might not be clear enough on their own. "High Level Principles" could be just "Vision" for example.

**Comment by DrewAPicture** [comment]
Hi 👋🏻

**Handbook IA**

Looking at the proposed IA here, I think it begs a mention that care should be taken not to glom all things Gutenberg into one handbook for the sake of it. As a long time maintainer for DevHub and former docs team lead, I can tell you that keeping the responsibilities of user-facing handbooks simple is a must, if only to avoid future confusion and a rising maintenance burden.

For instance, I note that you have a Resources and References section in what is otherwise by all accounts a user-facing handbook. This information is absolutely useful ... to the _Gutenberg team_ and its contributors. As per the organizational style of the Make network on .org, each Make community has their own contributor-facing handbook. That is where the bulk of this contributor-facing information should live.

Any Gutenberg information specific to WordPress should live either in the Plugin and/or Theme Development handbooks on DevHub or as a standalone Gutenberg handbook, again, on DevHub. Hopefully that makes sense.

**"Official" Docs Reflect Latest Stable**

On another note, I don't see it mentioned but it's worth clarifying that any docs coming from parsed source should reflect only current stable code. This is a policy we follow on DevHub for core as well as in the Theme and Plugin Development handbooks.

**Comment by chrisvanpatten** [comment]
I think there is some value to keeping Gutenberg documentation centralised for at least the short term, while it's so new and since the contribution process is fairly different than the rest of core.

That said it could certainly make sense to split more cleanly into "Developing Gutenberg" and "Using Gutenberg" handbooks, but one of the challenges is that there's a degree of overlap, especially for developers. The packages and components documentation is relevant both to people developing Gutenberg and people developing _for_ Gutenberg.

I can't speak on behalf of the leads but I don't think there's necessarily any opposition to putting the Gutenberg handbook into DevHub but I know from a practical perspective we would need to sort out a way to differentiate documentation for the version of Gutenberg in _core_, vs the version that lives on in the _plugin_. Does DevHub make it possible to build and switch between multiple versions of documentation, or would that mean basically maintaining two handbooks in parallel?

Happy to discuss this further in today's #core-docs meeting at 2pm ET. I'm pretty flexible on what the final implementation looks like (and truthfully I'm not sure I have the authority to make a decision anyway) but as we start divvying up the work it would be great to settle on a definitive "this is how we're going to do it".

**Comment by danielbachhuber** [comment]
> I know from a practical perspective we would need to sort out a way to differentiate documentation for the version of Gutenberg in _core_, vs the version that lives on in the _plugin_. Does DevHub make it possible to build and switch between multiple versions of documentation, or would that mean basically maintaining two handbooks in parallel?

If we're keeping the Markdown -> WordPress workflow, then we can have two separate `manifest.json` files, one for DevHub and the other for the Make Handbook.

**Comment by chrisvanpatten** [comment]
Hi everyone —

Based on our discussion yesterday, we are going to try to split our written documentation into three handbooks:

1. Contributor Handbook (building Gutenberg)
2. User Handbook (how to publish posts, etc.)
3. Designer & Developer Handbook (how to build blocks, design themes, etc.)


With that in mind, I reorganised the IA outline again. Here's how I see it getting split up:

1. Contributor Handbook
    1. Introduction
    2. Philosophy
    3. Design
        1. Design Resources
        2. Link to HIG
    4. Develop
        1. Coding guidelines
        2. Testing
        3. Release Process
        4. Deprecations
        5. Links to components/package references
    5. General
        1. History
        2. Glossary
        3. FAQs
        4. Repository management guidelines
2. User Handbook
    1. Meet the new Editor (high level UI overview)
    2. Sticking with Classic
    3. How do I… (common FAQ)
3. Designer & Developer Handbook
    1. Building blocks and plugins
        1. Tutorials
            1. Build your first block
            2. Build your first plugin sidebar
            3. Extend a block
            4. Extend the editor
        2. Developer Reference
            1. Blocks API
            2. Plugins API
            3. Components
            4. Registered scripts
            5. Block filters
            6. Editor filters & slotfills
        3. Designer Reference
            1. Human Interface Guidelines
            2. Preparing block icons
    2. Theming for the new editor
        1. Theme support list
        2. Block HTML & CSS reference (classes to target)
        3. Editor styles
        4. Block style variations
    3. Backwards compatibility
        1. Meta boxes
        2. Important deprecations/changes from 4.x
    4. Resources
        1. Articles
        2. Meetups
        3. Talks


For the time, these handbooks should continue to be built from this GitHub repo. This also gives us some extra flexibility because we _should_ be able to have multiple targets: e.g. we build these three handbooks separately, but then _also_ build a combined handbook for the _plugin_ version of Gutenberg.

I'm looking to finalise this by tomorrow at 12pm ET, so *please comment with feedback*. This is not going to be a locked/unchangeable document but it should be good at a high level :)

**Comment by chrisvanpatten** [comment]
(Note: I'd like suggestions on the User Handbook in particular.)

**Comment by youknowriad** [comment]
@chrisvanpatten Is this issue still relevant, I feel that the reorganization happened already?

**Comment by nosolosw** [comment]
These conversations have been instrumental through the many docs iterations. We've just shipped the last iteration (can be seen at https://developer.wordpress.org/block-editor/) and the state of docs is now different than it was months ago. I believe we can close this.
