### ISSUE TITLE
Media and Text block

### ISSUE THREAD

**Issue by ajtruckle** [WordPress/gutenberg#11041]
I have just tried to use the new Gutenberg "Media and Text" block and the image that I have selected is showing too large:

![error](https://user-images.githubusercontent.com/7985331/47485655-76eedf80-d836-11e8-8467-957a15c19143.png)

It is only a small file:

![studentmaterial2](https://user-images.githubusercontent.com/7985331/47485664-7d7d5700-d836-11e8-9f6c-0b28c98bbd94.png)

So I am confused and don't know what to do.

**Comment by jorgefilipecosta** [comment]
Hi @ajtruckle thank you for reporting this issue. You should be able to use the resizer to change the image size. Maybe it was not appearing because we had a bug of not showing the resizer when unified toolbar mode was enabled. If that's the case in the last version of Gutenberg/or beta WP version this problem should be solved, or alternative you can disable the unified toolbar mode so it is possible to resize the image in the previous version.
If this problem is persisting feel free to reopen the issue so we can look further.

**Comment by ajtruckle** [comment]
I can't see a resizer. I switched off the unified toolbar and no difference. I can drag the grip in the middle to the left but i should not have to do that. The image is of a size where it should fit without distortion. I find that if images have a width greater than height then they insert fine. But if they have a height greater than width it goes funny.

Also, when you have a "image" it has a caption under it but in the media and text there is no option for the same caption, for consistency.
