### ISSUE TITLE
Autosave causes incorrect revisions history state

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#11067]
**Describe the bug**

As a WordPress user, when I convert a Classic post to Gutenberg blocks, and then autosave fires, I'd expect to be able to restore my Classic post from revision. Instead, I'm left in an indeterminate state where Gutenberg displays blocks but revisions shows the Classic post as my latest state (which means I can't restore to it).

**To Reproduce**

1. Create a post in the Classic Editor with a couple of images. Hit save between inserting each image so that there's revision history:

![image](https://user-images.githubusercontent.com/36432/47511920-fdec8980-d82f-11e8-853a-8f4b6cf965da.png)

2. Open the same post in Gutenberg and convert to blocks. Autosave will fire after a short delay:

![converttoblocks](https://user-images.githubusercontent.com/36432/47512069-47d56f80-d830-11e8-909f-6034e74b2bfd.gif)

3. If you refresh the page, Gutenberg loads the autosaved block conversion version of the post (which I think is reasonably expected). However, if you navigate to "Revisions", you'll see the Classic post as the latest saved revision:

![image](https://user-images.githubusercontent.com/36432/47512222-9420af80-d830-11e8-9fbd-e9caa4975b4c.png)

![image](https://user-images.githubusercontent.com/36432/47512247-a569bc00-d830-11e8-9128-410a94e5a51a.png)

**Expected behavior**

As a WordPress user, I'd expect to be able to restore the Classic version of my post.

**Workaround**

If you hit "Save Draft" after the block conversion, Gutenberg creates a proper revision. This means you can then restore the older Classic revision.

**Comment by danielbachhuber** [comment]
@mtias Not until next week earliest, but then that's a short week for me.

**Comment by paaljoachim** [comment]
Can we get an update on this issue?

Thanks.

**Comment by paaljoachim** [comment]
I tested.

WordPress 5.7 RC 1
Gutenberg plugin 10.0.2
Twenty Twenty One

Activated the Classic Editor plugin.
Made a new page added one image. Published.
Added another image. Updated.
Deactivated the Classic Editor plugin. 
Activated Gutenberg plugin.
Went back to the page. Converted the classic block to Gutenberg blocks.
Clicked the Revisions panel and saw a browser popup alerting me that changes had not been saved. 

![Screen Shot 2021-02-25 at 21 57 33](https://user-images.githubusercontent.com/5323259/109216249-9276a600-77b4-11eb-9f39-e3b3ffc466a8.png)

Here I am forced to either Save or to leave without saving.
It is natural to save at this stage.

I would say that this issue is not valid any longer.
Or atleast a very minor issue.
I would suggest that we close it. @danielbachhuber
