### ISSUE TITLE
Version 4.1 Shows All Post Meta Field Groups (using ACF)

### ISSUE THREAD

**Issue by riemerta6** [WordPress/gutenberg#11071]
Gutenberg 4.1 shows all Post Meta Postboxes (or ACF Field Groups) even if that Field Group is not assigned to that page. It won't show the Post Meta fields, but it will show the Group. I am using ACF Pro to create these fields, and this was not an issue in Gutenberg 4.0. I tested both versions before creating this post.

1. Activate Gutenberb 4.1
2. Go to page with ACF Field Groups
3. All Field Groups show up

Expected Behavior (Version 4.0): 
![screenshot 169](https://user-images.githubusercontent.com/43151950/47513800-043d2e80-d84d-11e8-9e55-3afc3ba7cedf.png)

Current Behavior (Version 4.1)
![screenshot 170](https://user-images.githubusercontent.com/43151950/47513806-069f8880-d84d-11e8-98c6-782eaa67e673.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 64

**Comment by mcsf** [comment]
I think this was surfaced by #10676.

I haven't dived into the ACF source code, but from testing my hunch is that this is an upstream issue, because even in Classic Editor I see **in the DOM** field groups that _aren't supposed_ to be displayed for a given post but that are kept hidden with `style="display: none;"`. Perhaps the ACF plugin loads a batch of field groups and then target specific DOM selectors to hide those that don't matter, and this match fails in Gutenberg.

/cc @noisysocks

**Comment by mcsf** [comment]
Fixed upstream per https://github.com/AdvancedCustomFields/acf/issues/77#issuecomment-434297801
