### ISSUE TITLE
Gutenberg 4.1 and 4.1.1 - Youtube video fills ENTIRE page

### ISSUE THREAD

**Issue by Pikkals** [WordPress/gutenberg#11085]
**Describe the bug**
On Gutenberg 4.1 and 4.1.1 the youtube video now fills the ENTIRE PAGE over all other paragraphs [blocks] with giant spaces in between paragraphs.  Only affects articles written in Gutenberg. 

**To Reproduce**
1. Go to 'POSTS'
2. Click on 'ALL POSTS'
3. Clickon article that is affected.
4. Scroll down to 'YOUTUBE BLOCK'
5. Go to Advance CSS
6. The following CSS appears:  wp-embed-aspect-4-3 wp-has-aspect-ratio
7. If you remove it, the youtube video returns to normal.
8. If another Admin comes into the article and updates the article, this CSS (wp-embed-aspect-4-3 wp-has-aspect-ratio) magically reappears.

Please note:  I have removed this Advanced CSS (wp-embed-aspect-4-3 wp-has-aspect-ratio) from the editor, because this is an important article at the moment and I need people to be able to read it.

**Expected behavior**
For Youtube video to display normally

**Screenshots**
![image](https://user-images.githubusercontent.com/42873768/47547294-2db19500-d8f5-11e8-8941-eb1054bb5a25.png)
![image](https://user-images.githubusercontent.com/42873768/47548439-56d42480-d8f9-11e8-8e52-f13f11d3e796.png)

[https://www.discerningtheworld.com/2018/10/24/angus-buchan-gods-divine-numerologist/](url)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser CHROME
 - VersionV 69.0.3497.100 (Official Build) (64-bit)

**Additional context**
- Gutenberg 4.1

**Comment by Pikkals** [comment]
Hi arunsathiya 

Actually on 4.0 I had this:  [https://github.com/WordPress/gutenberg/issues/10109]

It's got to do with responsive themes I think.

I will contact my Hueman Pro theme support as well, to fill them in on what's happening now.

**Comment by Pikkals** [comment]
Ok Hueman Pro have literally right this minute updated their theme to Hueman Pro 1.1.5

This was added to the theme:
* added : support for new WordPress editor, block cover image alignwide/alignfull 

It's working now with the additional CSS Class:  wp-embed-aspect-4-3 wp-has-aspect-ratio

**Comment by designsimply** [comment]
I tested with WordPress 4.9.8 and Gutenberg 4.1.1 and the Twenty Seventeen 1.7 theme using Chrome 70.0.3538.77 on macOS 10.13.6 and I do see `wp-embed-aspect-16-9 wp-has-aspect-ratio` getting added to the Settings > Block > "Additional CSS Class" field and I think that is the expected behavior. Videos look good in my test and don't explode to fill the page as you described.

Recent work has been done to remove gaps that were appearing around some videos and to change the way responsive videos work whether or not the theme opts in using `add_theme_support( 'responsive-embeds' );` ([reference](https://github.com/WordPress/gutenberg/pull/10477)). Note: if a theme has opted in, you would see a "Media Settings" panel in the sidebar for the YouTube block ([screenshot](https://user-images.githubusercontent.com/1204802/46788084-b945f600-cd39-11e8-9faf-af9862281579.png)). It's possible the Hueman Pro have been working around this or have a separate solution or that the latest update makes a change they didn't anticipate.

It would be worth letting the Hueman Pro theme authors know:

* Recent changes were made to make responsive embeds a theme option at [https://github.com/WordPress/gutenberg/pull/10477](https://github.com/WordPress/gutenberg/pull/10477)
* Does the problem happen for new posts you create after upgrading to 4.1+ or posts that previously had YouTube embed blocks or both?
* Steps to reproduce the problem.
* Note whether you have any other active plugins which could be interfering with how videos (just in case).

Thank you for testing Gutenberg and for reporting the issue!
