### ISSUE TITLE
Highlighted formatting in the toolbar doesn't match MCE inline boundaries

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#11091]
Duplicates: #11326, #13087.

**Describe the bug**
There's a minor inconsistency with the formatting toolbar and TinyMCE's inline boundaries (used to highlight formatted text).

When the caret is positioned on the left side of formatted text, within the inline boundary, the toolbar button for the active formatting is correctly shown toggled on:
![screen shot 2018-10-26 at 4 05 40 pm](https://user-images.githubusercontent.com/677833/47553227-10061f00-d939-11e8-82b7-ccdad91504ef.png)

Pressing the left arrow key once to move the caret outside of the inline boundary, the format is incorrectly still shown toggled on:
![screen shot 2018-10-26 at 3 57 50 pm](https://user-images.githubusercontent.com/677833/47553101-c1588500-d938-11e8-899d-cc7ec68e5bae.png)

Positioning the caret on the right side of formatted text, back within the inline boundary, the toolbar button is incorrectly toggled off:
![screen shot 2018-10-26 at 3 52 46 pm](https://user-images.githubusercontent.com/677833/47553118-d0d7ce00-d938-11e8-9d19-981ee3edfd34.png)

**To Reproduce**
1. Add formatted text (bold/italic/strikethrough/link) to a paragraph block.
2. Position the caret on the left of the formatted text within the inline boundary.
3. Move the mouse to display the toolbar and observe that formatting is toggled on correctly.
4. Press the left arrow key once to move outside of the inline boundary.
5. Move the mouse to display the toolbar and observe that formatting is incorrectly toggled on.
6. Position the caret on the right of the formatted text within the inline boundary.
7. Move the mouse to display the toolbar and observe that formatting is incorrectly toggled off.

**Expected behavior**
The toggle state of toolbar formats should match the position of the caret.

**Additional context**
- 4.1
- Noticed while working on #10983

**Comment by iseulde** [comment]
@talldan What's the behaviour in TinyMCE?

**Comment by talldan** [comment]
Hi @iseulde, It's a bit inconsistent in classic. It works as I would expect for links. The format is shown toggled on in the toolbar if the caret is on either the left or right side of the formatted text.

With bold, italics and strikethrough, it's the opposite to what we have in Gutenberg, at the end of the formatting the toolbar button is shown toggled on, but at the start it's toggled off.

![classic](https://user-images.githubusercontent.com/677833/47841855-ea27c100-ddf5-11e8-959f-2b884ba0e382.gif)

**Comment by iseulde** [comment]
@talldan Thanks! I think this would be good to address in #11322. Not sure if we can do it earlier than that.

**Comment by talldan** [comment]
@iseulde Seems sensible.

**Comment by gziolo** [comment]
I noticed a similar issue in 4.2-RC. Originally reported in #11326.

**To Reproduce**
Steps to reproduce the behavior:
1. Add new block containing RichText control (Paragraph, List, etc)
2. Write any text.
3. Select some text and make it bold (or italic, underline, whatever).
4. Move the cursor at the end of selection.
5. You will notice that the block toolbar no longer highlights applied formater and it hides after a brief time.
6. When you continue typing from the end of the selection, format will continue to be applied.
7. No move the cursor to the beginning of the selection. Actually one keypress before.
8. UI shows that format option is still selected and toolbar can be see.
9. When you start typing you don't see format applied but UI tells something else.

**Expected behavior**
Formats should be properly applied with the proper visual state of Block Toolbar controls.

**Screenshots**
![typing at the end of selection](https://user-images.githubusercontent.com/699132/47812009-7f1fb100-dd47-11e8-807a-e2735d6e9d05.gif)


**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Version: the latest

**Comment by iseulde** [comment]
This needs to be addressed in #11322. In other words, we need to make the rich text value boundary-aware.
