### ISSUE TITLE
Fatal error: Cannot declare class WP_Block_Parser_Block, because the name is already in use

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#11145]
`Fatal error: Cannot declare class WP_Block_Parser_Block, because the name is already in use in \wp-content\plugins\gutenberg\packages\block-serialization-default-parser\parser.php on line 10`

I get this on homepage when simply activating WordPress 5.0 beta 1 and Gutenberg 4.1.1 together. My functions.php is using `gutenberg_parse_blocks` and generating this.

**Comment by designsimply** [comment]
I just tested with 5.0-beta3-43865 by installing and activating Gutenberg 4.1.1 and I was able to edit posts with Gutenberg and all looks well for me on the home page on the font end. Are you able to try with beta3 to see if the problem is still happening for you there?

> My functions.php is using gutenberg_parse_blocks and generating this.

Is this for a custom theme you are building? If yes, are you able to include a more complete code example and would it also be possible to explain the end goal for what you are trying to do?

**Comment by manake** [comment]
The error is still there in `5.0-beta3-43865` and Gutenberg 4.1.1.

What completely eliminates the error is un-commenting this line `require_once dirname( __FILE__ ) . '/../packages/block-serialization-default-parser/parser.php';` in `/wp-content/plugins/gutenberg/lib/blocks.php` on line 86. Then the error is gone and everything works.

**Comment by manake** [comment]
Maybe `class_exists` instead of `require_once` could help.

I just have a function in functions.php:

`function myParseBlocks(){
	global $post;
	$blocks =  gutenberg_parse_blocks( $post->post_content );
}`

and calling this function on page.php causes this.

**Comment by uusijani** [comment]
My test blog is running WP 5.0-beta3-43867 with Gutenberg 4.3.0-alpha-0841246 (from [Daniel Bachhuber's nightly](https://danielbachhuber.com/2018/10/02/gutenberg-nightly-build/)), and the theme I'm using is [Cover2](https://wordpress.org/themes/cover2/) ([Github here](https://github.com/peiche/cover2)), which also appears to exhibit this in single post view.

I've narrowed it down to [this function](https://github.com/peiche/cover2/blob/f6a8229be7c52d4d52cc2d1cd1aa4baf849c8a65/inc/aesop.php#L36) ([called from header.php](https://github.com/peiche/cover2/blob/904584f8006a48048db18b945d3663c11d61f842/header.php#L31)), where the `gutenberg_parse_blocks()` call triggers the issue.

I'm not saying I'm 100 % sure it's Gutenberg and not the theme(s) at fault here, but I just thought I'd post this just in case it helps to find out either way.

**Comment by designsimply** [comment]
I tested this with WordPress 5.0-RC1-43946 and Gutenberg 4.5.1 by adding this:

```
function myParseBlocks(){
	global $post;
	$blocks =  gutenberg_parse_blocks( $post->post_content );
}
```

to the `functions.php` file for the Twenty Seventeen theme and then viewing the home page and I couldn't replicate the problem at this time.

I also tried installing and activating the Cover2 theme (version 1.4.1) and found that I could load the home page normally without any errors. 

@manake if you're still having trouble with the latest version of WP5.0-RC (or if I've done anything wrong in my testing steps above), can you please note the latest version you've tested with and re-open this issue?

**Comment by manake** [comment]
I can confirm that the issue is not resolved. I can't re-open the ticket.

Do this and the issue is gone:
1. Go to /wp-content/plugins/gutenberg/lib/blocks.php.
2. On line 71 in Gutenberg 4.6.1 add `//` before `require_once dirname( __FILE__ ) . '/../packages/block-serialization-default-parser/parser.php';`.
3. It's solved that way.

5.0-RC3-43968

**Comment by uusijani** [comment]
You can reproduce this even with Twenty Nineteen, by adding `<?php $blocks = gutenberg_parse_blocks( $post->post_content ); ?>` to header.php.

Replacing `gutenberg_parse_blocks()` calls with `parse_blocks()` seems to work around the issue (for me at least), and the issue here, if any, is apparently just one of confusion: [renaming the function broke backwards compatibility](https://github.com/WordPress/gutenberg/issues/12653), but since [`gutenberg_parse_blocks()` is still defined](https://github.com/WordPress/gutenberg/blob/2a66db0fc99a9fb1ba99f61e59e6a0b2a4a5f9ef/lib/blocks.php#L60), instead of a "Call to undefined function" you get this attempt to redefine `WP_Block_Parser` ([via inclusion of parser.php](https://github.com/WordPress/gutenberg/blob/2a66db0fc99a9fb1ba99f61e59e6a0b2a4a5f9ef/lib/blocks.php#L71)), resulting in the "name is already in use".

**Comment by manake** [comment]
Yes, I would keep this closed.

# Solution (for anyone looking for one):

### Have WordPress 5.0+ and rename `gutenberg_parse_blocks()` to `parse_blocks()`. Problem solved.
