### ISSUE TITLE
Consider renaming BlockMover uids prop to selectedUids

### ISSUE THREAD

**Issue by BE-Webdesign** [WordPress/gutenberg#1115]
I stumbled a bit the other day when the uids prop for the BlockMover was actually supposed to be a list of selected block uids vs. the entire list of block uids.  From looking things over I think that is the actual behavior: selectedUids.  I am not 100% sure either, so if someone could verify that it is taking a subset of the uids, I think we should change the name.

**Comment by youknowriad** [comment]
Actually, this is not always equal to the selected Uids because we have the possibility to move the hovered block as well (And we show two block movers in this case). 

Side note. A component shouldn't be aware of its surroundings, so even if we were using it only for selected uids, I'd prefer passing a generic `uids` prop. The meaning would be: the block mover is responsible for moving the `uids` provided.
