### ISSUE TITLE
Native button block modifier classes should have better GUI controls

### ISSUE THREAD

**Issue by cameronjonesweb** [WordPress/gutenberg#11174]
**Describe the bug**
There are a couple of modifier classes that the button block has that are included natively but are not exposed to the GUI in an ideal manner. 

**Expected behavior**
Outline:
- There should be a new setting to toggle whether the button has an outline or solid background
- When outline is selected, the background colour setting label should change to border colour
- Additionally, presently when a custom background colour is applied the button will always have a background even with the `.is-style-outline` class applied, however not with the preselected colour options. This should not be the case

Squared:
- There should be a new setting to toggle whether the button has rounded corners or not.
- Alternatively, perhaps the buttons should have a range setting (similar to the column number settings) to set the size of the border radius, ranging from 0 to the height of the button.

**Additional context**
- Gutenberg 4.1.1

*Update*
So apparently I didn't look hard enough. However I don't belive the current approach is sufficient. You can't combine squared and outline styles without using custom classes, and outline style and custom background colours conflict, so I believe the outlined expected behaviour is a far better approach

**Comment by jjchrisdiehl** [comment]
I do agree, the expected behavior would be that the outline would not inherit a background color, but instead would have `background: transparent;`. Take a look:

![image](https://user-images.githubusercontent.com/16580129/47620466-d2340280-dac0-11e8-896e-1d9f1bc1749e.png )

This only happens in the editor, not on the live preview:

![image](https://user-images.githubusercontent.com/16580129/47620508-1e7f4280-dac1-11e8-9222-f24fd5841184.png)

As you can see the styling is applied as expected on the live preview.

When you inspect the live preview button, you see this code:

```
.wp-block-button.is-style-outline .wp-block-button__link.has-vivid-red-background-color {
    border-color: #cf2e2e;
}
```

But, when you inspect the editor:

![image](https://user-images.githubusercontent.com/16580129/47620533-761dae00-dac1-11e8-9cb7-6d55507b8221.png)

You have styling overriding the the default styling.

----------------------
Web Browser
Chrome 69.0.3497.100

Browser Operating System
Operating System
Microsoft Windows (10) NT 4.0

WP Version
4.9.8

Gutenberg 4.1.1

**Comment by talldan** [comment]
This seems to have been resolved now. It's possible to use Outline and apply a separate border radius.

Border color inherits the text color. I'll close the issue, but let me know if I'm missing anything and I can reopen.
