### ISSUE TITLE
Taxonomy terms are gone in 4.2 rc-1

### ISSUE THREAD

**Issue by slimmilkduds** [WordPress/gutenberg#11335]
**Describe the bug**
For non admin users all taxonomies are now empty in the editor. It throws one (403) Forbidden error per taxonomy.

This is an issue with this specific version of GB, reverting back to 4.1.1 and everything is back to normal

**To Reproduce**
1. Open or create a new post
2. Try to expand the taxonomy tabs (I have only tried custom Taxonomies)
3. Nothing happens (except errors in console)

If these steps to reproduce doesn’t work I’ll add the console log tomorrow as I don’t have a computer available right now.

**Desktop (please complete the following information):**
 Chrome

**Additional context**
GB 4.2 rc-1

**Comment by danielbachhuber** [comment]
Hi @slimmilkduds,

Thanks for the report. I wasn't able to reproduce this particular issue.

First, I registered a custom taxonomy called `topic`:

```
add_action( 'init', function() {
	register_taxonomy( 'topic', array( 'post' ), array(
		'hierarchical'      => false,
		'public'            => true,
		'show_in_nav_menus' => true,
		'show_ui'           => true,
		'show_admin_column' => false,
		'query_var'         => true,
		'rewrite'           => true,
		'capabilities'      => array(
			'manage_terms'  => 'edit_posts',
			'edit_terms'    => 'edit_posts',
			'delete_terms'  => 'edit_posts',
			'assign_terms'  => 'edit_posts',
		),
		'labels'            => array(
			'name'                       => __( 'Topics', 'YOUR-TEXTDOMAIN' ),
			'singular_name'              => _x( 'Topic', 'taxonomy general name', 'YOUR-TEXTDOMAIN' ),
		),
		'show_in_rest'      => true,
		'rest_base'         => 'topic',
		'rest_controller_class' => 'WP_REST_Terms_Controller',
	) );
});
```

Next, I signed in as a user with the `author` role and was able to observe the taxonomy's Post Settings Panel:

![image](https://user-images.githubusercontent.com/36432/47821050-a3b26380-dd1c-11e8-99a2-1c39f7e5f68d.png)

Can you share:
1. The code you're using to register your custom taxonomy?
2. Any modifications you've made to your roles?
3. The contents of the Network response in your Chrome developer tools?

**Comment by danielbachhuber** [comment]
> Tested and confirmed for the Categories panel (not custom) using both the author role and the contributor role.

I can confirm with Categories and Contributor. Looking further.

**Comment by danielbachhuber** [comment]
The immediate problem is that this request URL has `context=edit`:

```
http://alittletestblog.com/wp-json/wp/v2/categories?per_page=100&orderby=name&order=asc&context=edit&_locale=user 
```

The request URL should have `context=view`, because authors and contributors don't have permission to edit terms. Tracking down where this was introduced.

**Comment by danielbachhuber** [comment]
I believe the problem originated with #10089, specifically the change to use `getEntityRecords( 'taxonomy', slug, DEFAULT_QUERY );`, which then inadvertently means the request URL uses `context=edit`.

**Comment by adamsilverstein** [comment]
Can the e2e tests be extended to run as multiple roles so we can catch these types of regressions?

**Comment by danielbachhuber** [comment]
> Can the e2e tests be extended to run as multiple roles so we can catch these types of regressions?

Yes. We could create a plugin that creates an `author` user on load and switches to it.

---

@youknowriad Just so it's stated, I think reverting #10089 is the wrong approach for this.

The data module will eventually need to handle `context=view` vs. `context=edit`. There are plenty of scenarios in the WordPress backend where a WordPress User only has read permission for an entity, and can't access the full shape of its `contex=edit` data. For instance, an Editor can assign authors to a Post but shouldn't be able to view their capabilities data. And, in this specific scenario, an Author should be able to assign Terms to a Post without editing them.

You might disagree with the underlying `context` abstraction but:

1. It's what we have.
2. It isn't going away or changing substantially.
3. It's is probably what you'd end up designing if you had to solve the problem originally.

To revert #10089 instead of solving for `context=view` vs. `context=edit` in the data module is to simply re-introduce the bugs that it fixes and kick the problems further down the road.

cc @aduth

**Comment by youknowriad** [comment]
> The data module will eventually need to handle context=view vs. context=edit.

As discussed in DM. I think the data module shouldn't have to think about context at all. It's not abstraction on the REST API, it's an abstraction to retrieve WordPress Data and the REST API is an implementation detail.

We can't end up with entities in the store having different shapes depending on how they were fetched.

> To revert #10089 instead of solving for context=view vs. context=edit in the data module is to simply re-introduce the bugs that it fixes and kick the problems further down the road.

What bugs we will be reintroducing? #10089 is supposed to be a refactoring. If it fixes a bug by inadvertance, we can still fix in the old implementation of the component.

**Comment by danielbachhuber** [comment]
> I think the data module shouldn't have to think about context at all. It's not abstraction on the REST API, it's an abstraction to retrieve WordPress Data and the REST API is an implementation detail.

Ok. Where should the distinction between `context=view` and `context=edit` live then? The editor _must_ be able to distinguish between the two, and handle both.

> What bugs we will be reintroducing?

Maybe I misunderstood the implementation. I thought it was the path to eventually solving #10873 #7266 #7565

**Comment by youknowriad** [comment]
> Ok. Where should the distinction between context=view and context=edit live then? The editor must be able to distinguish between the two, and handle both.

Why it must?

**Comment by youknowriad** [comment]
> But then you'd have two different shapes of data in the store?

No, because the shape won't change for the same user.

> Are you expecting that we'd change the implementation of context at this point in the release cycle?

I'm not. I already talked about it a long time and I know It's not going to change now. I do think `context=all` or something is not that impactful as it's just a new context but I'm more pragmatic than that and thinking of reverting the component to use `apiFetch` directly and call it a day.

**Comment by danielbachhuber** [comment]
> I'm more pragmatic than that and thinking of reverting the component to use `apiFetch` directly and call it a day.

How do we refresh the component then?

**Comment by youknowriad** [comment]
> How do we refresh the component then?

I don't know, a hook maybe (even if it's not my favorite option in term of extensibility). Why would you refresh it though?

**Comment by danielbachhuber** [comment]
> Why would you refresh it though?

Because of #7565 #7266?

**Comment by youknowriad** [comment]
For #7565  even hacking with the Data Module seems like the wrong way to deal with those issues, it probably deserves its own component (Sidebar API or other).

#7266 These kind of issues is exactly what the data module is supposed to fix but it also highlights something I was talking about, if we do sepparate `view` and `edit` requests we can't automatically refresh the entities as well because we'd need a request on the other context as well.

**Comment by danielbachhuber** [comment]
>  if we do sepparate `view` and `edit` requests we can't automatically refresh the entities as well because we'd need a request on the other context as well.

Good point.

**Comment by youknowriad** [comment]
I'll wait a little bit, it looks like an important discussion, so I'm fine waiting for other opinions on how to solve these issues. I can revert at anytime.

**Comment by danielbachhuber** [comment]
Per `#core-restapi` [conversation today](https://wordpress.slack.com/archives/C02RQC26G/p1541092000035900), @kadamwhite will create a PR that partially reverts the original PR.

**Comment by hughiemolloy** [comment]
I would just like to raise that I think the `context=edit` is still wrong. If you have permission to 'assign_terms' on the taxonomy you should not get a 403 when editing a post. The context should be used for the edited object not the entity record.
