### ISSUE TITLE
Different page presentation

### ISSUE THREAD

**Issue by Daniel199614** [WordPress/gutenberg#11366]
We have some problems / bugs after the update from Gutenberg 4.0 -> 4.1.1

Formatting of images are wrong.
The Images are in the editor in the middle, but on the finally Webside are on the left side.
Text are OK.

**Editor:**

![image](https://user-images.githubusercontent.com/37458558/47862171-cf088180-ddf4-11e8-974d-aeb3bb7e553e.png)

**Webside:**

![image](https://user-images.githubusercontent.com/37458558/47862114-ab453b80-ddf4-11e8-9876-43d205d0d777.png)

System information:
Windows 10 1803
Chrome 70.0.3538.77 / Edge 42.17134.1.0 / Internet Explorer 11.345.17134.0

**Comment by designsimply** [comment]
I tested with WordPress 4.9.8 and Gutenberg 4.2.0 using Firefox 63.0.1 on macOS 10.13.6 and centered images worked correctly for me both in the editor and when viewed on the front end. I used the Twenty Seventeen 1.7 theme in my test. Is it possible your theme is the source of the trouble? May I ask what theme you are using for testing or if you can link me to a live example from a site where I can see the problem happening?

![screen shot 2018-11-07 at 10 54 37 am](https://user-images.githubusercontent.com/1119271/48150387-c3490f00-e27b-11e8-904e-5a8d51fd2f60.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=15593&action=edit running WordPress 4.9.8 and Gutenberg 4.2.0 using Firefox 63.0.1 on macOS 10.13.6 using Firefox 63.0.1 on macOS 10.13.6.</sup>

![screen shot 2018-11-07 at 10 54 24 am](https://user-images.githubusercontent.com/1119271/48150384-bfb58800-e27b-11e8-9149-72ae4881155c.png)
<sup>Seen at http://alittletestblog.com/2018/11/07/image-centering-test/ running WordPress 4.9.8 and Gutenberg 4.2.0 using Firefox 63.0.1 on macOS 10.13.6 using Firefox 63.0.1 on macOS 10.13.6.</sup>

**Comment by Daniel199614** [comment]
Thanks for the answer.

Meantime I have testing other themes and the problem was random on other sides on the webside, who are edit with Gutenberg.
I also update to Gutenberg 4.2.0 without any change.

Theme: [Septera](https://de.wordpress.org/themes/septera/)


Below are links to two sides an the webside. On the first side all is OK.
On the second side the images are formatet in the middle, but are all images on the left side.

[Right](https://feuerwehr-herrnsdorf.de/fuehrung/feuerwehrfuehrung/)
[Wrong](https://feuerwehr-herrnsdorf.de/fuehrung/vereinsfuehrung/)

**Comment by designsimply** [comment]
I tested with Septera and can confirm it is a theme issue. I found that centering works as expected in Twenty Seventeen and not in Septera.

Centered image is not centered using the Septera theme:

![screen shot 2018-11-13 at 5 09 10 pm](https://user-images.githubusercontent.com/1119271/48451401-81cacf00-e767-11e8-81d0-0cb4b622b6e7.png)
<sup>Seen at http://alittletestblog.com/2018/11/14/image-alignment/ running WordPress 4.9.8 and Gutenberg 4.3 and the Septera 1.3.3 theme using Firefox 63.0.1 on macOS 10.13.6.</sup>

Centered image appears correctly in the Twenty Seventeen theme:

![screen shot 2018-11-13 at 5 09 37 pm](https://user-images.githubusercontent.com/1119271/48451412-8b543700-e767-11e8-9d9e-ff942a513407.png)
<sup>Seen at http://alittletestblog.com/2018/11/14/image-alignment/ running WordPress 4.9.8 and Gutenberg 4.3 and the Twenty Seventeen 1.7 theme using Firefox 63.0.1 on macOS 10.13.6.</sup>

The theme author may be able to solve this by changing `display: block;` to `display: table;` in this CSS rule in their `style.css` file:

```
.main .aligncenter, .main img.aligncenter {
	display: block;
	clear: both;
	margin-right: auto;
	margin-left: auto;
}
```

I recommend reporting the problem at https://wordpress.org/support/theme/septera since it is theme-specific.

To temporarily solve the problem on your own site, you can try adding the following line to your custom CSS as a temporary workaround:

`.main .aligncenter { display: table; }`

**Comment by Daniel199614** [comment]
@designsimply 
Thanks.
The Tipp works for the moment.

I will reporting the problem on the theme-specific support side later this day.
