### ISSUE TITLE
Selection.getRangeAt(). getRangeAt() issue on Safari

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#11457]
@youknowriad I'm suddenly getting error on safari regarding `const range = getSelection().getRangeAt( 0 );` . It says:

IndexSizeError: DOM Exception 1: Index or size was negative, or greater than the allowed value.

Seems like safari doesn't fully support it yet : https://developer.mozilla.org/en-US/docs/Web/API/Selection/getRangeAt .

Thanks!

-- copied from my comment here : https://github.com/WordPress/gutenberg/pull/4872 . Thanks!

**Comment by ocean90** [comment]
Thanks for the report! Which script is producing the error? I'm asking because #4872 did not add a `getSelection().getRangeAt( 0 )` line. Unlike [this](https://github.com/WordPress/gutenberg/blob/a38c816/packages/editor/src/components/rich-text/index.js#L230) and [this](https://github.com/WordPress/gutenberg/blob/e5b9987/packages/components/src/autocomplete/index.js#L142), the one mentioned in the pull request was checking for `selection.rangeCount` first. But that line actually doesn't exist anymore.

Other examples checking for `rangeCount` first:

* https://github.com/WordPress/gutenberg/blob/c05ede75a490b5c8b911ad43c6d882a5e61f0a22/packages/dom/src/dom.js#L165
* https://github.com/WordPress/gutenberg/blob/d95c7d61d8ca284394a5aa77e9f74f9b3aaea24e/packages/format-library/src/link/positioned-at-selection.js#L18

**Comment by phpbits** [comment]
@ocean90 how about adding the condition on all `getSelection().getRangeAt( 0 )`? Hoping this `const range = selection.rangeCount ? selection.getRangeAt( 0 ) : null;` should be added on both files that you've mentioned. Let me know your thoughts. Thanks!

**Comment by johngodley** [comment]
Is this fixed in #11209?

**Comment by phpbits** [comment]
@johngodley Thanks! That's the fixes I've added too and it's working fine :) Hoping it'll got merge soon. Thanks again!

**Comment by aduth** [comment]
Closing per confirmation at https://github.com/WordPress/gutenberg/issues/11457#issuecomment-436134113 .

Noting there were similar recent issues in Safari, also fixed in #15576 (expected for Gutenberg 5.7 / WordPress 5.2.1).
