### ISSUE TITLE
Improve the pullquote translators comments

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#11467]
These translators comments:

https://github.com/WordPress/gutenberg/blob/60e0b50a33f81cf0be90c8953862f39d7bdbbf3a/packages/block-library/src/pullquote/edit.js#L87-L95

```
/* translators: the text of the quotation */
placeholder={ __( 'Write quote…' ) }

/* translators: the individual or entity quoted */
placeholder={ __( 'Write citation…' ) }
```

describe what the placeholders are meant for. Instead, they should clarify these are the placeholders values for the quote and the citation.

**Comment by timelsass** [comment]
It looks like the quote component also had the same issue: 
https://github.com/WordPress/gutenberg/blob/60e0b50a33f81cf0be90c8953862f39d7bdbbf3a/packages/block-library/src/quote/index.js#L218

I opened #11494 when running through testing this change because it doesn't appear that translator comments are even included when they are referencing multiple lines.
