### ISSUE TITLE
Can't use the slash inserter in Japanese 

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#11479]
In #10961 we tried adding support for non-latin languages for the slash inserter. While the issue seems fixed in some languages (Arabic), it's not working as expected in Japanese

Related https://github.com/WordPress/gutenberg/pull/10961#issuecomment-435266404

**Steps to reproduce**

I see this is closed but I noticed that the issue isn't solved for Japanese. I don't have Windows machine at hand so am explaining this for Mac (Chrome 69.0.3497.100).

1. Open your computer's keyboard settings and add a Japanese keyboard (日本語). Once an additional keyboard is added, you can switch them using ctrl + space keys. If you have another app assigned to the shortcut, use the top bar icon near where your clock is.
2. Set your WordPress language to Japanese.
3. Start a new post.
4. Set your keyboard to **English** and type `/` in a blank paragraph block.
5. Switch to Japanese keyboard and type `gazou` -> hit space bar -> hit enter. You should see the letters `画像` after the `/`.

Result: I expected to see the image block appear in the search results but it did not.

A. At this point, you can move your cursor between the two letters (`画` and `像`) using arrow keys. If you hit `←` and `→` once each, you'll see the suggestion pop-up.

B. Also, if you delete the last letter and just leave `/画`, you'll see suggestions.

C. But just entering the first letter`画` by regular writing action (`ga` -> space bar -> enter) doesn't have the same result as B above.

![gutenberg-slash-insert](https://user-images.githubusercontent.com/34067/47893671-88249580-dea1-11e8-8700-5d0918b8f8bf.gif)

**Comment by mcsf** [comment]
I can use slash completion in Japanese as well. See screencast:

![japanese-slash-completion](https://user-images.githubusercontent.com/150562/47993628-d3c88080-e0e7-11e8-8f46-9cb509cb6adf.gif)

It's admittedly a little awkward:
- finding the actual slash character requires navigating down the input suggestions, at least when using an American physical keyboard;
- the IME popover and the block suggestions popover are present at the same time, and I need to press `Enter` to conclude the IME interaction and be able to move up and down the block suggestions.

But it works. @naokomc, for your issue report were you using the latest version of Gutenberg (4.1.1 as of today)?

I'll preemptively close this issue, but feel free to comment and reopen.

**Comment by naokomc** [comment]
Step 4 seems to be missed in others' test, but I don't think that itself matters.

The difference in my environment I noticed after seeing others' tests is that I have "Live Conversion" option turned off.
e.g. https://www.kuropixel.com/turn-off-japanese-live-conversion/

[Google IME](https://www.google.co.jp/ime/) in its default state also caused this issue but since I don't have date what percentage of Japanese users are not using the IME in OS's default setting, I can't say that this is a major issue. Will ask Windows users too.

**Comment by atachibana** [comment]
I tested it on Windows 10 Japanese edition with WordPress 5.0 Beta 3.
It works property with MS-IME and Google IME. `/画像` could find image bock. Thank you for the good work!

Just my thought:
But I want to propose to leave the function `/image` even in Japanese environment, because key combinations of Turn off Japanese -> `/` -> Turn on Japanese -> `画像` is too much for the shortcut...

**Comment by youknowriad** [comment]
@atachibana  Thanks for the tests

> But I want to propose to leave the function /image even in Japanese environment, 

Yes, this has been suggested here #11370
