### ISSUE TITLE
WP 5 beta: cursor jumps ahead of where it should be after pressing the spacebar

### ISSUE THREAD

**Issue by IovaMihai** [WordPress/gutenberg#11498]
**Describe the bug**
The video presents the issue much better than words can: https://www.dropbox.com/s/l1yfqwh9eoeu3c6/wordpress-5.0.mov?dl=0

**To Reproduce**
This was on a fresh WP 5 install. I have done an update since then to version 5.0-beta3-43865, but the issue still persists.

I had only one plugin active that added the two meta-boxes from the video. The cursor issue happens without any active plugins.

**Desktop (please complete the following information):**
MacBook Pro (Retina, 13-inch, Late 2013), macOS High Sierra 10.13.3
Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
No testing done on a mobile device.

**Comment by designsimply** [comment]
Noting that I am adding the `Needs Testing` label as a check to see if this is happening in the plugin. If it is not, we will want to move this issue to https://core.trac.wordpress.org/

Thank you for testing and for reporting the issue!

**Comment by dd32** [comment]
I was able to duplicate this with the TwentyNineteen theme, and as it turns out, it's because the font TwentyNineteen uses renders non-breaking spaces differently than normal spaces.

Thankfully, this is a known issue, and is being worked on over here: https://github.com/WordPress/twentynineteen/pull/463
