### ISSUE TITLE
Should "common blocks" comprise the most commonly-used blocks?

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#11515]
Right now, the blocks in the "common blocks" category don't actually correspond to the most commonly-used blocks, at least according to the data we currently have on hand. (See: https://codepen.io/sarahmonster/pen/bmzzyJ for data via Jetpack.)

The cuurrent list of common blocks (bold indicates a top ten block): 

- **paragraph**
- **heading**
- **list** 
- **quote**
- **image**
- cover
- **gallery**
- audio
- file
- video

We may want to consider amending this to include the top ten most commonly used blocks instead:
- paragraph
- heading
- image
- list
- code
- gallery
- table
- quote
- separator
- spacer 

The four abandoned blocks (audio, file, video, and cover) might work well in a "media" category instead.

After that html, youtube, and columns are most frequently used, but I'm not sure that I'd recommend putting them in the "common blocks" category.

**Comment by karmatosed** [comment]
This feels like it's hiding in 'question' when should be a design discussion so moving it to that.

**Comment by paaljoachim** [comment]
Another idea.
What if we instead of showing 9 blocks in the **Most used** area have 12 blocks (needs a capital U in used). These would overall be the most used blocks in the layout. One could automatically populate the 12 blocks and gradually the **Most used** blocks area will change as the user adds various blocks to the layout. This way Common Blocks can be merged into the Most used area. 

Common Blocks can be removed and the various blocks added to other block sections. I do believe there is also an issue for renaming and cleaning up where the various blocks should go. (I am just not able to locate it at the moment.)

@mapk @jasmussen

**Comment by jasmussen** [comment]
The block library and how blocks are shown does need a lot of work. #19836 was one attempt at making that happen, but perhaps it doesn't sufficiently refine the appearance of blocks themselves. 

But one driving force in that PR was to expand the footprint of the block library to make it possible to browse in a more comfortable interface. In general I almost never use the "recent blocks" to the point that I would consider removing that section entirely. Mostly though, I'd avoid giving the paragraph block any kind of prominence, as you should almost always create that using the Enter key.

**Comment by mapk** [comment]
There's a lot of work happening around the Block Library right now. I think it's best to close this in favor of the reorganization and relabeling of block categories which are soon to come.

**Re-naming block categories**
https://github.com/WordPress/gutenberg/pull/19279

**Redesigning the Block Inserter**
https://github.com/WordPress/gutenberg/issues/17335#issuecomment-589000529
