### ISSUE TITLE
Separate test utils functions into their own files

### ISSUE THREAD

**Issue by tofumatt** [WordPress/gutenberg#11535]
Right now we have a large, single file (https://github.com/WordPress/gutenberg/blob/master/test/e2e/support/utils.js) that houses all of our test utilities for writing E2E tests with Puppeteer. As we've increased our E2E tests (yay!), we've increased the size of that file (boo!).

Recently @notnownikki made a PR with some really handy mocking functions that could arguably live in their own file. We should probably start organising these test utils into their own files before that file becomes a 1,000 line monster.

**Comment by notnownikki** [comment]
Ah, good point! That PR is https://github.com/WordPress/gutenberg/pull/11250 btw :)

**Comment by gziolo** [comment]
It looks like we could add `utils` subfolder, rename `test/e2e/support/utils.js` to `test/e2e/support/utils/index.js` and extract all methods from this file, put in a few new files and only re-export them from index to ensure we don't have to touch existing files.

**Comment by vadimnicolai** [comment]
@gziolo please confirm if what I've started is what's expected and I can finish PR the same way.
And, please advise, because I am new to this project and not sure what's the optimal way of running E2E tests here. I have used `npm run test-e2e` (before changes have been made) and got this output
![image](https://user-images.githubusercontent.com/1477453/48291589-b4cb4500-e47f-11e8-9eb5-7d911abe803b.png)

**Comment by gziolo** [comment]
@vadimnicolai, it passed on Travis, so I assume everything going well so far 👍
