### ISSUE TITLE
cannot update latest version

### ISSUE THREAD

**Issue by paulgallie** [WordPress/gutenberg#11575]
the plugin says update to latest version buy this gives an error - see below:
Update Failed: Could not copy file. gutenberg/build/edit-post/index.js

**Comment by designsimply** [comment]
Could you provide a little more information? Are you running WordPress 4.9.8 and did you attempt to update from Gutenberg 4.1.1 to 4.2 by clicking the update button directly on the plugin listed in the WP Admin > Plugins page?

**Comment by paulgallie** [comment]
HI there,
Yes we are running wordpress 4.9.8 and attempting the update by clicking the update button on the plugin on installed Plugin page

**Comment by designsimply** [comment]
Thank you for confirming that. I tried that same test by installing version 4.1.1 from https://github.com/WordPress/gutenberg/releases/tag/v4.1.1 and then going to Plugins and clicking the "update now" link below the Gutenberg plugin and I did not see any error in my test. I would like to close this issue because I wasn't able to replicate it in testing and so I think it may have been an isolated incident, however, if you see the problem again please definitely reply back or create a new issue. I haven't seen this reported before but I would like to know if it ever comes up again. 

![screen shot 2018-11-13 at 6 49 13 pm](https://user-images.githubusercontent.com/1119271/48454739-ba71a500-e775-11e8-8334-4930b5d7b25b.png)

![screen shot 2018-11-13 at 6 49 21 pm](https://user-images.githubusercontent.com/1119271/48454738-ba71a500-e775-11e8-9f79-4214a0aa988e.png)

<sup>Tested with WordPress 4.9.8 and Gutenberg 4.1.1 updating to 4.3 using Firefox 63.0.1 on macOS 10.13.6</sup>

If you haven't already, please try completely deleting and then reinstalling and reactivating the Gutenberg plugin.
