### ISSUE TITLE
Table Block: add caption support

### ISSUE THREAD

**Issue by fienen** [WordPress/gutenberg#11589]
**Describe the bug**
When creating a table block, you have to manually edit the HTML if you want to include a caption on the table. A `<caption>` is allowed to be the first child of a `<table>` element for accessibility purposes as described in https://www.w3.org/WAI/tutorials/tables/caption-summary/ and https://developer.mozilla.org/en-US/docs/Web/HTML/Element/caption

**To Reproduce**
1. Create or edit a post
2. Insert a table block
3. Convert to HTML editing
4. Add a `<caption>` element just inside the `<table>`  element
5. Convert back to visual editing

**Expected behavior**
This should not produce an error, and should be treated as acceptable markup. Bonus points if the table block editor straight up supported captions, as well as thead/tfoot without having to manually editing the HTML of the table.

**Screenshots**
![table1](https://user-images.githubusercontent.com/784502/48140728-fc2eb700-e26e-11e8-9be4-7fba8f15080a.JPG)
![table2](https://user-images.githubusercontent.com/784502/48140734-fdf87a80-e26e-11e8-8e12-ec6c3f7e8f2d.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 70

**Additional context**
- Gutenberg 4.2.0

**Comment by ellatrix** [comment]
Right, there is currently no caption support.

**Comment by Rik44444** [comment]
this issue has been closed, but in my Wordpress version 5.5 i do not have caption support in the Table block, is that correct? Or have i missed it?

**Comment by michaelmcpeekbrenau** [comment]
One year later and the Tables block still doesn't support captions and doesn't use ARIA labels to connect figcaptions with tables, either.

**Comment by talldan** [comment]
Table blocks should support captions since WordPress 5.4:
<img width="609" alt="Screenshot 2021-08-30 at 11 13 05 am" src="https://user-images.githubusercontent.com/677833/131279961-63852973-641a-4d86-9772-c3c3d762dcf5.png">

@michaelmcpeek The implementation does use a `figcaption`, but screenreaders should still announce this.

An implementation using the table `<caption>` element was attempted initially, but unfortunately browsers/assistive technologies didn't seem to support a `contenteditable` caption element. That might have changed now, so it could be worth looking at again.

https://github.com/WordPress/gutenberg/issues/24205 discusses changing the caption implementation (and aria labels aren't the right way to connect a caption to a table).

**Comment by betagoo** [comment]
`figcaption` is not semantic. It's very big problem.

**Comment by Amberroseweeks** [comment]
The above solution @talldan is a `<figcaption>` not a semantic HTML table caption of `<caption>` which appear right after the initial `<table>` tag. This issue is not resolved and should remain open. Because of this issue, my web page is failing section 508 compliance because our tables do not have an accessible name tied to them through the caption tag.

**Comment by maikelRAOW** [comment]
Is there a solution for this yet?
