### ISSUE TITLE
HTML of dynamic blocks altered in the front-end

### ISSUE THREAD

**Issue by daext** [WordPress/gutenberg#11629]
With WordPress-5.0-Beta3 the content of dynamic blocks in the front-end is altered.

In my case in the HTML generated by a custom Gutenberg block unnecessary HTML paragraphs have been added.

Our custom Gutenberg blocks use the method explained [here](https://wordpress.org/gutenberg/handbook/blocks/creating-dynamic-blocks/) to generate the dynamic blocks in the front-end:

```
register_block_type( 'my-plugin/my-custom-block', array(
    'render_callback' => 'my_plugin_render_block_my-custom-block',
) );
```

This issue doesn't exists in the Gutenberg plugin but with WordPress-5.0-Beta3 is making our blocks unusable. (the JavaScript part is now broken because the DOM is altered)

**Comment by designsimply** [comment]
I'm adding the `Needs Testing` label here as a check on what you've said about the plugin and also noting that if the problem happens only in WP 5.0 beta that we will want to move the issue to https://core.trac.wordpress.org/

For reference, may I ask if you're using the WP 5.0 beta3 zip file downloaded directly from https://wordpress.org/news/2018/11/wordpress-5-0-beta-3/ or if you are using the bleeding edge nightlies via the WordPress Beta Tester plugin?

I can help test but would very much appreciate some direction! Testing question: since you've mentioned dynamic blocks, would it be a good test for me to try with something like the Latest Posts block (a dynamic block) or is your question more about your custom code and a specific use case and help request?

**Comment by daext** [comment]
I confirm you that I downloaded WP 5.0 beta3 from https://wordpress.org/news/2018/11/wordpress-5-0-beta-3/.

The plugin where this issue happens make use of the 'render_callback' to call a custom function that generates the HTML. This is a simplified example:

```
  //The JavaScript part  ------------------------------------------------------------
  save: function() {

    /**
     * This is a dynamic block and the rendering is performed with PHP:
     *
     * https://wordpress.org/gutenberg/handbook/blocks/creating-dynamic-blocks/
     */
    return null;

  },

//The PHP part ---------------------------------------------------------------
register_block_type( 'my-plugin/my-custom-block', array(
    'render_callback' => 'my_plugin_render_block_my-custom-block',
) );

function my_plugin_render_block_my-custom-block($attributes) {

    //Here the HTML is generated based on $attributes (received from the block) and data available on custom database tables but the resulting HTML is now altered with WP 5.0 beta3

}
```

It's a plugin that we sell through CodeCanyon and I'm available to send you privately the product with the exact instructions to simulate the issue. In case please use this email address info@daext.com

**Comment by youknowriad** [comment]
I remember something like that fixed a long time ago. I'm closing, let me know if you still experience this.
