### ISSUE TITLE
Using the mouse wheel when heading block activated "locks" me in (wp-5.0-beta)

### ISSUE THREAD

**Issue by websupporter** [WordPress/gutenberg#11647]
**Describe the bug**
In the 5.0 beta I have a post with a `h2` heading. I click on the `h2` heading and then I use the mouse wheel to scroll around in the text. Instead of going down in the text after a while it jumps back to the `h2` block.

I can't reproduce this issue with wp4.9.8 and the [gutenberg nightly build](https://builds.danielbachhuber.com/gutenberg-nightly.zip); but the error persist also with the nightly build on 5.0-beta

**To Reproduce**
1. Run current WordPress beta 5
2. Create a post with some content, and a h2 heading somewhere
3. Click on the h2 to activate the block
4. Try to scroll through your text

**Screenshots**
https://youtu.be/kr4MLb9vU84

**Desktop (please complete the following information):**
 - Ubuntu 14.04
 - Firefox
 - 63.0 (64-Bit)
- Default mouse with a mouse wheel

**Additional context**
- Version 4.3.0-alpha-4e9d9b3 [gutenberg nightly build](https://builds.danielbachhuber.com/gutenberg-nightly.zip)

**Comment by websupporter** [comment]
I can't reproduce it on Chrome though, seems Browser specific.

**Comment by websupporter** [comment]
Today, I tried to reproduce the bug with a clean WP5-beta installation. First I couldn't reproduce it, but when I switched to the TwentySeventeen theme it was back again, so it seems somehow to be tied to the theme.

https://youtu.be/RznPGx12vGM

I used the WordPress5 beta ZIP you can download here: https://wordpress.org/news/2018/11/wordpress-5-0-beta-3/
It persisted when I went to Dashboard > Updates with the version 5.0-beta3-43878

**Comment by designsimply** [comment]
If this problem is only happening with WP 5.0 beta 3, we will want to consider moving the issue to https://core.trac.wordpress.org/ though we can leave it open here for now to see if we can get an additional tester who has a mouse wheel who can help verify the issue by checking it with WP 4.9.8 + Gutenberg 4.3+ on Firefox using the following steps:

1. Create a post with some content, and a h2 heading somewhere.
1. Click on the h2 to activate the block.
1. Try to scroll through your text using a mouse wheel.

**Comment by websupporter** [comment]
I can't reproduce it in WP5 beta4 :tada: 

Thank you :heart:
