### ISSUE TITLE
Conflict with WPMUDEV - Defender pro

### ISSUE THREAD

**Issue by ggando14** [WordPress/gutenberg#11644]
There is a conflict with WPMUDEV - Defender Pro plugin, when both are activated, I can no edit or create posts, it keeps kicking blocking me and need to wait at least 5 minutes to regain access to the site. I've gone to all defender settings and can not find solution.

**Comment by mrxkon** [comment]
Hi @ggando14 !

I'm using Defender + Gutenberg myself but never experienced any issues or conflicts between them. I've been trying to replicate as well on my various setups but without any luck.

Have you verified that it's a conflict between these two i.e. by using the Classic Editor and not having the same issue? I'm asking as we didn't have any similar reports as well.

Also since I see that you're mentionng Pro you could always contact us via https://premium.wpmudev.org/hub/support/#get-support if you like so we can take a closer look and  resolve this.

**Comment by mrxkon** [comment]
@ocean90 , we've run tests again on our end ( at WPMU DEV ) without finding anything conflicting or causing issues between Defender + Gutenberg.

I'm not sure what the process for these Issues is exactly, but since we haven't found anything and there are no other reports either from our members or here do you think we could close this up ?
