### ISSUE TITLE
Uncaught (in promise) 

### ISSUE THREAD

**Issue by julianbianqui** [WordPress/gutenberg#11672]
Hi, I have this error "Uncaught (in promise)" every time I try to save a post, I am using the latest version of metabox io and also the latest version of advanced custom fields, there is a compatibility problem with these plugins?
I am tested with gutenberg 4.2.0 and wordpress 4.9.8.
 Best!

**Comment by designsimply** [comment]
I tested with WordPress 4.9.8, Gutenberg 4.3, Advanced Custom Fields 5.7.7, and Meta Box 4.15.7 using Firefox 63.0.1 on macOS 10.13.6 and I was able to both save and publish a post without any problems. Note: I added a field group to ACF including a text field and saved content to it and I also copied the sample code from https://docs.metabox.io/quick-start/ into my theme's `functions.php` file and filled out the basic form before saving and publishing successfully.

In your case, the error you're referencing may be due to something else or it may be that you've done something differently with the custom meta box code you've added. It's hard to say without more information. The error message "Uncaught (in promise)" may have a file or path listed next to it, can you check to see if you can find what that is in case it provides a helpful hint or possibly include a screenshot showing the full error message? If it does have something specific that points to a particular plugin, then I can help you get an issue filed in the right place. If the error is simply vague, then I would recommend temporarily turning off all other plugins except Gutenberg and clearing cache and testing saving a post again to see if you are able to save. If you can, you can turn the plugins back on one by one and repeat the test until you find which one is the source of the trouble.

**Comment by julianbianqui** [comment]
I was fixed it! Thanks @designsimply!

**Comment by designsimply** [comment]
🎉

**Comment by designsimply** [comment]
@julianbianqui I assume this was fixed by updating to the latest versions of ACF and Meta Box. Let me know if that's not correct though!
