### ISSUE TITLE
Don't enqueue CSS when post type is not Gutenberg enabled

### ISSUE THREAD

**Issue by jdevalk** [WordPress/gutenberg#11673]
**Describe the bug**
When a post type is not using Gutenberg yet, for instance because the site uses the Gutenberg Ramp plugin, we shouldn't enqueue `block-library/style.css` and `block-library/theme.css` on the frontend for that post type.

**To Reproduce**
1. Go to [https://joost.blog/about/](https://joost.blog/about/), this is a page. On this site, the classic editor is used for this post type.
2. View source, see that both of these CSS files are embedded anyway.

**Comment by Clorith** [comment]
What then if I have a non-Gutenberg post type that in turn pulls in content from other posts/pages that do Gutenberg (or even sidebars that somehow rely on it)?

I don't think there's much harm in blanket including the Gutenberg styles if Gutenberg is enabled, to avoid any such scenarios (with the exception where themes have dequeued them on their own, in which case they are responsible for things being proper).

Yes, it adds 1 or 2 resources to load, but hopefully our http/2 focus can be re-ignited post 5.0 and that will then just be a temporary tradeoff until those capable have it in their hands. (I don't know how we're looking on adoption of webservers that support it of course, so I can only speak in general terms).

**Comment by jdevalk** [comment]
Well, in the current state of those files, they can affect the look of a page without wanting to do so. The CSS isn't all namespaced, for instance, this:

```css
@keyframes fade-in{
    0%{
        opacity:0
    }
    to{
        opacity:1
    }
}
```

That could very easily conflict with existing CSS. If we want to allow people to "Ramp up" to Gutenberg using Gutenberg ramp, we should make sure we don't break their site design for them.

**Comment by Clorith** [comment]
That's a very valid point, perhaps we should be a bit more mindful here and actually have some form of wrapper class or similar on our styles.. At least this seems like the best approach in my opinion to not unexpectedly affect non-related elements, and it is what we tell themes and plugins to do, so abiding by it our selves as well makes perfect sense.

**Comment by jdevalk** [comment]
To be fair, as I mentioned in #11668 I don't think these styles should exist in that file. There's more there that isn't structural but rather meant for the editor. Everything else is namespaced with `wp-` but IMHO that's not specific enough.

**Comment by youknowriad** [comment]
Agreed with the issues mentioned here:

We have an `_animations.scss` file that is meant to be a "mixin" the issue is that CSS animtations can't be defined as mixins so they end up duplicated automatically in all stylesheets.

I suggest removing this file by doing something like:

 - If an animation is used only once in Gutenberg, define it in the stylesheet actually using it and give a very specific name
 - If an animation is used in multiple places, we can keep this generic animations file but not import it implicitely (like other variables and mixins files) and only import it explicitely when a stylesheet (package) need it. (In addition to making these animations names more specific).

**Comment by youknowriad** [comment]
(Deleted my comment as published on the wrong issue)
