### ISSUE TITLE
How to use `styled-components` in the front-end?

### ISSUE THREAD

**Issue by mahdiyazdani** [WordPress/gutenberg#11714]
Is there any way around to use the [styled-components](https://www.styled-components.com) within the Gutenberg’s save method?

As far as I can see this works perfectly fine in the back-end which is obviously because of the React and React-DOM that are accessible globally. However, this doesn't work in the front-end and extension is not able to inject the style tag before the closing head tag.

**Comment by roborourke** [comment]
@mahdiyazdani you'll need to load react on the front end too and use `ReactDOM.render()` on your blocks. For using `styled-components` I don't think there's a simpler way, especially if there's some dynamic use of props for changing styles. Server side rendering with WordPress is still quite hard to do and wouldn't give you the dynamic portion of styled components.

I don't think this is something Gutenberg can support in itself I'm afraid.

**Comment by mahdiyazdani** [comment]
@roborourke Thanks for sharing your input.

I don't think that loading the React or React-DOM in the front-end might be a good idea at all, in fact, I wish Gutenberg had a way around to handle this on its own.

**Comment by roborourke** [comment]
No worries. I totally agree it’s not ideal to load react if you don’t have
dynamic components on the front end. In that instance you’re better off not
using styled components at all and go for a sass loader or something that
creates a file you can enqueue.

I don’t believe it’s reasonable or likely for Gutenberg itself to try and
support styled-components output on save because it’s a separate project
that not everyone would use, plus it would adds to an already large
maintenance burden.

If anything was to happen to support SC it’d be via a plugin or special
webpack loader for example.

**Comment by designsimply** [comment]
Closing because the answer provided sounds valid. Thank you for the question @mahdiyazdani and for the input @roborourke!
