### ISSUE TITLE
Consider adding a way to "hover" all blocks.

### ISSUE THREAD

**Issue by BE-Webdesign** [WordPress/gutenberg#1171]
Not sure if this is already possible, but it would be nice to be able to toggle the hover state (visually) of every block. When using enter and typing you can make lots of empty blocks without realizing it and it can become hard to navigate through the content.

**Comment by jasmussen** [comment]
I think this is good speculation. I've been thinking about making the blocks more visible also, if nothing else then also to showcase where a text block starts and ends, so expectations are set right, as in perhaps showing a 1px outline even on hover. 

Another idea is briefly flashing the block boundaries whenever the page is loaded, or _some action is taken_. 

Otherwise I think we should generally take inspiration from desktop publishing apps like Indesign, where the outlines are generally only visible when selected or hovered.

**Comment by 00travelgirl00** [comment]
I think it would be good if an empty field would always be visible, also without a hover.

![empty_fields](https://user-images.githubusercontent.com/21318377/27285443-0dcabcbc-54fd-11e7-9cd5-241d9875a569.gif)


Also I'm not quite sure, if the little line on border-left is clear enough for everyone, also because the colour of the line is really light and not dark enough in my opinion. 

Just a little try how it would look like, if the empty fields have a border-left. I personally would prefer a box, because its easier to spot, where to click in. 

 
<img width="851" alt="bildschirmfoto 2017-06-19 um 14 34 32" src="https://user-images.githubusercontent.com/21318377/27285560-5acc0ade-54fd-11e7-945c-7087a0b8ab67.png">

I personally would prefer a box, because its easier to spot, where to click in. Even it could look a bit crowded. 

<img width="829" alt="bildschirmfoto 2017-06-19 um 14 44 45" src="https://user-images.githubusercontent.com/21318377/27285731-ed525278-54fd-11e7-8db6-641c6d5365e9.png">

**Comment by jasmussen** [comment]
Since we have a ⌘A shortcut that selects all blocks, and we have hover outlines that span the full block, I'm going to close this ticket for now. We can reopen if we feel the issue becomes pressing again.
