### ISSUE TITLE
Add call to action on classic block

### ISSUE THREAD

**Issue by bahiirwa** [WordPress/gutenberg#11718]
I'm always lost when I open my post for editing after installing Gutenberg for a new editing experience. The blob of text just stares at me even on hover. 

If the 3 vertical dots icon appeared to show that the block can be edited on hover (Convert to blocks).

Just like the other blocks if the classic block had a simple movement for user experience to show what it is (like the image block that has a blue note saying image)

**Comment by designsimply** [comment]
Adding some screenshots for reference. 

Here is what a post looks like for me when I create it using the classic editor and then open it using Gutenberg—it has a label at top left but it does not appear on hover and is not the same as other blocks which have a blue background and appear at top right:

![screen shot 2018-11-11 at 9 40 09 am](https://user-images.githubusercontent.com/1119271/48315659-4dec7f80-e596-11e8-9c96-157f77af002b.png)

Here is the same content after clicking on the classic block:

![screen shot 2018-11-11 at 9 40 19 am](https://user-images.githubusercontent.com/1119271/48315669-72e0f280-e596-11e8-9163-d25e79dde1d4.png)

Here is a comparison of the block label, which appears top right when hovering, as seen on the image block:

![screen shot 2018-11-11 at 9 41 56 am](https://user-images.githubusercontent.com/1119271/48315676-9310b180-e596-11e8-8284-b4450ae94cd9.png)

<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=15656&action=edit running WordPress 4.9.8 and Gutenberg 4.3.0-rc.1 using Firefox 63.0.1 on macOS 10.13.6 .</sup>

**Comment by sarahmonster** [comment]
It looks as though there is a hover state for the block, it's just hiding:

<img width="642" alt="Screenshot 2019-04-02 at 17 30 51" src="https://user-images.githubusercontent.com/376315/55420053-06c75100-556e-11e9-9396-bde9b3a1b82d.png">

Making the choices more explicit here would be a good call. I just got rather confused trying to find the "convert to blocks" option, which was a bit more separated from the actual content since I had the top toolbar mode enabled. If I got lost and confused, I suspect others might be too.

What about making the choice here more explicit, so it's clear the actions a user has available to them?

![Frame](https://user-images.githubusercontent.com/376315/55420479-0e3b2a00-556f-11e9-8c08-8dea8d8977e3.png)

**Comment by mapk** [comment]
@sarahmonster when I have the Classic Editor plugin "on", I don't seem to get an option for Gutenberg. And the same vice-versa. If I turn the Classic Editor plugin "off" then I get Gutenberg. Would your button "Edit in classic mode" turn the plugin "on"? Or am I missing something entirely here?

I'm curious why we can't just show the Classic block with the full menu (selected view above) when the user opens a classic editor post in Gutenberg. 

Why can't it default to this?

![Screen Shot 2019-04-05 at 4 53 35 PM](https://user-images.githubusercontent.com/617986/55661842-65393d00-57c3-11e9-9e3b-2b05eaef8979.png)

**Comment by designsimply** [comment]
I think Sarah's design, "Edit in classic mode" great simply open the classic block toolbar (not the plugin which is a separate thing). 

> I'm curious why we can't just show the Classic block with the full menu

The only reason that comes to mind might be performance related, for example if opening the classic block loads things that do not need to be loaded by default and saves time if they aren't. I know that performance has been a key area of focus.

**Comment by sarahmonster** [comment]
> Would your button "Edit in classic mode" turn the plugin "on"? Or am I missing something entirely here?

My understanding of this issue was that this intermediate state is seen by users who wrote a post using the pre-5.0 editor (the classic editor, in effect) but there may be more complexity here to consider.

If the post was authored using the Classic block, it should (and does) default to showing the Classic block with the full toolbar. But if the post were edited with the pre-5.0 editor, or with the Classic Editor plugin, and the user has since switched to using Gutenberg, it makes sense to provide a clear and easy path to converting to blocks (potentially with the option to undo) or to edit in the Classic block (referred to above as "Classic Mode" mostly because use of "block" is potentially confusing there when sitting next to a "Convert to blocks" option.)

**Comment by mapk** [comment]
I'd love to see an explicit call to action here. Right now, I have to click the block, then select the vertical dots icon to see the option to "Convert to blocks." And on top of that, once I click the block, the icons are all jacked up. I've reported that here: https://github.com/WordPress/gutenberg/issues/16525

**The path to convert this to blocks:**
![Screen Shot 2019-08-21 at 6 47 31 AM](https://user-images.githubusercontent.com/617986/63437743-f5c59200-c3df-11e9-9f40-3220974d20b6.png)


**I'm in favor of going with @sarahmonster's mockup:**

![55420479-0e3b2a00-556f-11e9-8c08-8dea8d8977e3](https://user-images.githubusercontent.com/617986/63437785-10980680-c3e0-11e9-827e-e0a9986b2deb.png)

**Comment by Mamaduka** [comment]
The Classic block in iframed editors now has a CTA button in the toolbar. Should we close this issue?

## Screenshot
![Image](https://github.com/user-attachments/assets/f30336b5-8b41-46a2-900d-59ce5046f98c)

**Comment by Mamaduka** [comment]
Closing the issue. The Classic block now has a prominent "Convert to blocks" CTA in the toolbar in iframed and non-iframed editors.
