### ISSUE TITLE
Blocks added where mouse was focused, instead the column

### ISSUE THREAD

**Issue by virgiliud** [WordPress/gutenberg#11720]
**Describe the bug**
When clicking the + sign to add a block in a column, the block is added where the mouse was focused. 

**To Reproduce**
1. Add a columns block.
2. Click anywhere outside of the column where you want to add a block. You can even click in another column.
3. Hover over and click the + sign in the column where you want to add a block. The block is added where the mouse was focused instead of the column where the + sign was clicked. 

**Expected behavior**
It expected to add the block in the column where the New Block button was clicked. 

**Desktop (please complete the following information):**
Chrome 70.0.3538

**Additional context**
Gutenberg Version 4.2.0

**Comment by designsimply** [comment]
I tested with WordPress 4.9.8 and Gutenberg 4.3 and I wasn't able to replicate the problem as described ([20s](https://cloudup.com/cxLDlExTWHP)). I also tried with 4.2 and noticed the cursor would land in the block below where I tried to add a new block ([28s](https://cloudup.com/c1LIjrbpVzS)) so I think this is solved in 4.3 but please let me know if you find otherwise!
