### ISSUE TITLE
"Updating Failed" or "Publishing Failed" on fresh installed blog

### ISSUE THREAD

**Issue by stockwerk5** [WordPress/gutenberg#11732]
**Describe the bug**
"Updating Failed" or "Publishing Failed" message constantly on top of the editor.

**To Reproduce**
Tried this on a fresh install of WordPress as well as deactivating all plugins on the site I'm experiencing this on.

1. Gutenberg installed and updated, create a new post.
2. Try to save the new post as a Draft or Publish it.

**Expected behavior**
I've expected the post to be saved and published without error.

**Screenshots**
<img width="1673" alt="screenshot 2018-11-11 um 14 27 15" src="https://user-images.githubusercontent.com/29687754/48313510-ecd8a200-e5bd-11e8-96ae-f6bd69587d43.png">

<img width="1834" alt="screenshot 2018-11-11 um 13 03 36" src="https://user-images.githubusercontent.com/29687754/48313500-d03c6a00-e5bd-11e8-8ff8-e1dd3bb57416.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.1
 - Browser Chrome 70.0.3538.77
 - WordPress 4.9.8 with Gutenberg Version 4.2.0

**Additional:**
I don't use Cloudflare which was mentioned in other topics.

**Comment by ocean90** [comment]
Do you have any plugins active? Can you see which `index.js` is throwing the error?

**Comment by stockwerk5** [comment]
It's `/wp-content/plugins/gutenberg/build/deprecated/index.js`

Theme is Contentberg with core plugins.

**Comment by designsimply** [comment]
I found Contentberg at https://themeforest.net/item/contentberg-blog-content-marketing-theme/22634637

@stockwerk5 can you please try the same testing steps after updating to the latest version of Gutenberg (4.6 at the time of this writing) and, if the problem is still happening with 4.6 for you, can you please also try switching to the default theme (Twenty Seventeen or Twenty Nineteen) in order to rule out a conflict with the theme in this case?

**Comment by stockwerk5** [comment]
I updated both: Gutenberg and theme to the latest November versions. Now it's fine. Thanks.
