### ISSUE TITLE
Content Structure: Reusable blocks that aren't in the page are counted

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#11744]
**Describe the bug**
The _Content Structure_ component mistakenly includes reusable blocks that aren't attached to the page in its _Blocks_ count.

**To Reproduce**
1. Create a new post
2. Insert a block
3. Convert it to a reusable block
5. Click _Content Structure_
6. It reports that there are 2 blocks

**Expected behavior**
_Content Structure_ should report that there is 1 block in the post.

**Screenshots**
<img width="941" alt="screen shot 2018-11-12 at 10 40 05" src="https://user-images.githubusercontent.com/612155/48319878-552f8e00-e667-11e8-9529-95c50545f2f3.png">

**Comment by bph** [comment]
I agree the Block count is whacky, but I think it's not entirely related to reusable blocks. There might be  something else going on. 
I recorded two videos. The screen is bit slow moving but I didn't want to edit video, to preserve the full experience.

1. In this video, you see me loading a post from the list of posts. Then immediately after the post fully loads, I look at the block count: 52. Also, note: 8 headings,  4 paragraphs, and 325 words.
2. Then I move a block upwards. The Block count is now 63. The block count increased, although I didn't add a block, just moved one. And notice the change in paragraphs? It displays now 6 paragraphs, instead of 4.
3. To double-check, I move another block, but the numbers don't change any more. 
4. Let's see what happens when I add another Twitter Embed.: The word count increases by 1 to 326, Heading stays the same, paragraphs increases by two, and Block count increases by 12 to 75 blocks. 

See for yourself: http://recordit.co/v7g07SUjqO

The second video was recorded right after the first one. Starting again with the list of posts. 
1. Beginning count: Words 326, Headings 8, Paragraph back to 4 Block count 53, one more than in the first video as we added a block in between. 
2. My intention is to removed the previously added tweet, but have a hard time to get the block toolbar to show. (Again be patient :-) Eventually, I succeed in removing it. And the immediate change in numbers: 326 words, 8 headings, Paragraph block increase by 2 and the block count by 10 (although, I just removed a block) 
3. I saved the post and from the list of posts I open it again. The count is back to the orginal numbers. Words 325, Headings 8, paragraph 4 and 52 blocks.

Here is the second video.  http://recordit.co/C03rtZhQF6

Additional information: 
Reusable blocks in total: 10 
Reusable blocks used in this post: 1 block 2 times.
