### ISSUE TITLE
Issue with nested blocks and change of editor width

### ISSUE THREAD

**Issue by florianbrinkmann** [WordPress/gutenberg#11759]
**Describe the bug**

After changing the editor width like described in the docs (https://wordpress.org/gutenberg/handbook/extensibility/theme-support/#changing-the-width-of-the-editor) and adding the stylesheet via `wp_enqueue_style`, also blocks that are used in `InnerBlocks` get this new width, so they overflow their parent blocks. The reason is the following generated rule:

```
.editor-styles-wrapper .wp-block { width: 1250px }
```

Where `1250px` is my custom width. If this rule would not be there, it would work fine.

**To Reproduce**
1. Create stylesheet to modify editor width (for example via `.wp-block { max-width: 1250px; }`
2. Enqueue it to the editor.
3. Use `add_theme_support( 'editor-styles' );`.

**Expected behavior**

Nested blocks should not be affected by those max width rule.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 65.0a1 (2018-11-11) (64-Bit)

**Additional context**
- Gutenberg 4.2.0.

**Comment by designsimply** [comment]
Tested and confirmed using WordPress 4.9.8 and Gutenberg 4.3 and Twenty Seventeen 1.7 using Firefox 63.0.1 on macOS 10.13.6 with the following steps:

Add these lines to `functions.php` in the theme:

```
add_theme_support( 'editor-styles' );
add_editor_style( 'editor-style.css' );
```

Add a `editor-style.css` file to the theme and add these lines to the `editor-style.css` file:

```
.wp-block { max-width: 1250px; }
h2 { color: red; }
```

I also tried with:

```
.wp-block { width: 1250px; }
h2 { color: green; }
```

Go to Posts > Add New and notice the width of the editor has not changed and `<h2>` headings are not red. In the past, I accidentally used `editor-styles.css` (plural) instead of `editor-style.css`, and I have double checked to make sure I have the correct file name referenced this time.

**Comment by designsimply** [comment]
I re-tested with WordPress 4.9.8 and Gutenberg 4.4 `f9ddd6882` and found that I was able to get the editor styles to work as expected as long as I took into account the other styles in the theme. For example, I was testing with Twenty Nineteen and that theme already uses styles such as `.wp-block { width: calc(6 * (100vw / 12 )); }` and when I added `.wp-block { max-width: 1250px; }` it didn't override the other more-specific already-existing rule. Because the `width` rule is more specific, I needed to take that into account and the following worked for my case:

```
.wp-block { 
	width: 900px;
	max-width: 900px; 
}
```

(This is to explain my own misunderstanding from earlier.)

Now, for the issue originally reported! I tested and confirmed that if I use editor styles to modify the editor content width then nested blocks are affected when they shouldn't be. You can see this happening for Twenty Nineteen without making any modifications since it already uses custom editor styles to modify content width:

![screen shot 2018-11-16 at 1 35 46 pm](https://user-images.githubusercontent.com/1119271/48646132-1ec67b80-e9a5-11e8-8d51-3a0ed18097a6.png)
<sup>Seen at http://localhost:8888/wp-admin/post.php?post=28&action=edit running WordPress 4.9.8 and Gutenberg 4.4 `f9ddd6882` using Firefox 63.0.1 on macOS 10.13.6.</sup>

@youknowriad is this something that should be fixed on the editor side or should themes such as Twenty Nineteen be expected to account for inner blocks such as `Columns` and  `Media & Text` when they update content width using custom editor styles?

**Comment by florianbrinkmann** [comment]
I found out that not only the nested blocks are affected by the generated `width: ` rule, but also all other blocks. Try to resize the viewport (make it narrower), and the blocks are not reposnive anymore (because of the (in my case) `.editor-styles-wrapper .wp-block { width: 1250px }`).

**Comment by youknowriad** [comment]
The documentation suggest that we should use `max-width` and not `width` and in my case it works great this way.

**Comment by youknowriad** [comment]
The `width` rule is not created dynamically anymore. We did do that in an old version of Gutenberg but it changed in the last two releases AFAIK. Checking.

**Comment by youknowriad** [comment]
yes, I'm not seeing where we generate this.

**Comment by florianbrinkmann** [comment]
Oops, you are right, my fault, sorry – had a width rule in another file 🤦‍♂️

**Comment by youknowriad** [comment]
no worries, glad it's resolved now.
