### ISSUE TITLE
Drop cap and Alignment both option not working properly

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/gutenberg#11756]
**Describe the bug**
Drop cap and text alignment both settings do not work in new editor.

**To Reproduce**
1. Write a sentence in Paragraph block
2. Click on drop cap toggle
3. Click on Align right

**Screenshots**

![error](https://user-images.githubusercontent.com/10103365/48345275-a195c080-e69d-11e8-98b4-dc23c1081dc1.gif)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version 69.0.3497.81

**Additional context**
- Gutenberg: latest from master
- WordPress: 5.0 beta 3

**Comment by mukeshpanchal27** [comment]
Above issue will fixed if we remove float left from below css code.

p.has-drop-cap:not(:focus):first-letter {
    **float: left;**
    font-size: 8.4em;
    line-height: .68;
    font-weight: 100;
    margin: .05em .1em 0 0;
    text-transform: uppercase;
    font-style: normal;
}

**Comment by Naerriel** [comment]
What is the expected behaviour of aligning right with drop cap?
If the lines of text have irregular left side then there will be white space between some of the lines and the drop cap letter.
Example: 
![export 1](https://user-images.githubusercontent.com/13454526/50777598-50204100-129c-11e9-982f-46b8fbbb7f48.png)

Personally I can't think of the reasons what for would someone use drop cap with align: right.
Maybe we'll turn drop cap off, when aligning right?

**Comment by Jackie6** [comment]
I agree with Naerriel's comment. I think the align right button should be disabled when the drop cap is enabled.

**Comment by rebeccaj1211** [comment]
I think it should look something like this (although this is center align)

![download](https://user-images.githubusercontent.com/10778156/55837863-929e2780-5af0-11e9-9bc9-a086799e51a4.png)

**Comment by gziolo** [comment]
@jasmussen - can you help to clarify how it should be implemented?

**Comment by jasmussen** [comment]
That is an EXCELLENT question. 

I looked up [the typographical behavior on Wikipedia](https://en.wikipedia.org/wiki/Initial#Types_of_initial), it's interesting reading. The term is "initial", which is a large first letter, and usually the three styles of intitials include the first letter just being big, one where the first letter sits in the left margin, and the style the block editor uses, the drop-cap, where a quarter of the text is indented to make space for the large first letter.

The first of these three, as Rebecca suggests, lends itself to working with right aligned text, whereas the two other styles do not, and are inherently tied to left-aligned or justified text (though to be clear, on RTL reading directions the dropcap should float on the right where the text starts).

Since the block editor currently embraces the drop-cap style, it seems like the correct thing to do here would be to _disable_, perhaps with a line of explanatory help-text below, the drop-cap button when the alignment is anything other than left (or right for RTL languages).

**Comment by rebeccaj1211** [comment]
Okay, I'll take a look into this!

**Comment by richtabor** [comment]
If the paragraph text is longer than one/two lines, then the issue doesn't occur, right? I personally don't think this is a big enough issue, as the current solution is to not use the feature, if it doesn't work for you. 

Aligned right:
<img width="709" alt="Screen Shot 2020-07-21 at 12 25 23 PM" src="https://user-images.githubusercontent.com/1813435/88080945-c1a5a480-cb4d-11ea-8e06-afdc661491c5.png">

**Comment by paaljoachim** [comment]
I see both PR's associated with this issue have gone stale.
@obenland @rebeccaj1211 

Joen @jasmussen 
Do you want to take a look at this issue as you are working on this PR?
https://github.com/WordPress/gutenberg/pull/28685

**Comment by rafaelgalani** [comment]
I can work on it... But how is it supposed to work? Should the drop cap option be disabled?

**Comment by jasmussen** [comment]
It could work like this. With unaligned text, you get the usual behavior:

<img width="1270" alt="left aligned" src="https://user-images.githubusercontent.com/1204802/110089321-428c7600-7d96-11eb-98a1-3bb1952eca15.png">

If you center or right align, you'd get this:

<img width="1270" alt="centered" src="https://user-images.githubusercontent.com/1204802/110089337-47e9c080-7d96-11eb-8b73-d94bd43e05ee.png">
<img width="1270" alt="rightaligned" src="https://user-images.githubusercontent.com/1204802/110089338-491aed80-7d96-11eb-8ef6-5657ea4a8b1e.png">

Note the help text, "Aligned text cannot have a dropcap". It could potentially use better verbiage, but I intentionally avoided using "Centered text" or "Right aligned text", as we want to handle RTL situations also. 

And on that note, dropcap in RTL looks a bit broken — but that could be because I'm using english text in an arabic context.

<img width="1270" alt="Screenshot 2021-03-05 at 09 35 53" src="https://user-images.githubusercontent.com/1204802/110089430-68197f80-7d96-11eb-9358-c5922ae8e932.png">

I would _imagine_, and be happily corrected, that for RTL text, the dropcap should only work in the default alignment, i.e. _right_, and be disabled for center/left alignments.

**Comment by rafaelgallani** [comment]
Sorry for taking so long to respond. 

>And on that note, dropcap in RTL looks a bit broken — but that could be because I'm using english text in an arabic context.

@jasmussen From what I found, that might not be the reason why it's broken: I think that the culprit might be twenty twenty-one theme, at least in my tests:

![image](https://user-images.githubusercontent.com/18705930/111912478-81822300-8a48-11eb-8653-e359f2546fa0.png)
All of the text is right-aligned (due to `style-rtl.css`, which converts `left` CSS directives to `right`). **EXCEPT** the drop cap. 

---

![image](https://user-images.githubusercontent.com/18705930/111912427-3cf68780-8a48-11eb-8bca-be1baa8574f8.png)
Since the twenty twenty-one theme is not within Gutenberg's context, its styling rules are not converted to RTL. Is the `!important` rule allowed in this specific case?

Besides that, the only necessary fix might be changing the drop cap help text and disabling the CSS rules when center/opposite alignment (left in RTL, right in LTR) is applied.

**Comment by jasmussen** [comment]
@rafaelgalani Thank you for the excellent investigative work! That does make it seem like a Twenty Twenty One bug.

My instinct is that we should not add !important to the block editor rules if we can avoid it. In this case, it's clearly a bug that is worth fixing directly in the Twenty Twenty One theme — it needs to simply remove most of those drop cap rules, and keep only the ones that override. I see the code here:

https://github.com/WordPress/twentytwentyone/blob/trunk/assets/css/ie-editor.css#L3220

Would you be willing to open a ticket for it? It would need to be done here: https://core.trac.wordpress.org/newticket?component=Bundled+Theme&summary=Twenty+Twenty-One

You can also search existing tickets here: https://core.trac.wordpress.org/search?q=twenty+twenty-one

Let me know, otherwise I'll open a ticket. Thanks again!

**Comment by rafaelgallani** [comment]
@jasmussen There was no open ticket related to this issue, so here's the one I created: https://core.trac.wordpress.org/ticket/52885.
I'll also open a PR adding the help text to the drop cap and removing it when using centered/opposite alignment.

**Comment by jasmussen** [comment]
Thank you that's perfect!

**Comment by carolinan** [comment]
Do we still want to remove the visual drop cap when the paragraph is aligned?
