### ISSUE TITLE
Adding gallery in Classic Block does nothing

### ISSUE THREAD

**Issue by completewebco** [WordPress/gutenberg#11847]
Describe the bug
Gallery is not inserted into Block Classic

To Reproduce

Install WordPress 4.9.8
Installed Gutenburg Plugin 4.3.0

Write a post, insert block classic, click on media icon, create a gallery und click on "insert gallery"
Nothing happens in classic block

Expected behavior
The gallery should be in block classic

Desktop (please complete the following information):

OS: Windows 10 64bit, recent version
Browser Chrome, recent version
Additional context

Getting the following console error when the gallery is added:

Uncaught TypeError: wp.shortcode is not a constructor
    at Object.shortcode (media-editor.min.js?ver=4.9.8:1)
    at Object.<anonymous> (media-editor.min.js?ver=4.9.8:1)
![screen shot 2018-11-14 at 5 35 28 am](https://user-images.githubusercontent.com/6548537/48477396-7ca16a80-e7cf-11e8-8546-da26658c1cff.png)
![screen shot 2018-11-14 at 5 25 46 am](https://user-images.githubusercontent.com/6548537/48477405-81661e80-e7cf-11e8-875e-c642d9bfc04a.png)

**Comment by designsimply** [comment]
I tested with WordPress 5.0.2 and no active plugins on Chrome 70.0.3538.110 on macOS 10.13.6 and was unable to replicate the problem. ([21s](https://cloudup.com/cGJyPrgnVtP))

Please update to the latest version of WordPress and uninstall the Gutenberg plugin (it's no longer needed unless you are working on code for the software or are beta testing) and temporarily deactivate all plugins and try again. If the problem is still happening, please re-open this issue and make a note of the updated versions you've tested and any other details you can think of which may be relevant.
