### ISSUE TITLE
Classic block toolbar gap on scroll

### ISSUE THREAD

**Issue by timelsass** [WordPress/gutenberg#11878]
**Describe the bug**
The classic editor's toolbar fixes position when scrolling, with a large gap in space after the editor top bar.

**To Reproduce**
1. Add a classic block to gutenberg editor in a new page/post with enough content to allow the screen to scroll.
2. Scroll down on page.

The result is that the toolbar fixes in position with a gap between the toolbar and the editor top bar.

**Expected behavior**
I believe this is intended to "stick" to the editor topbar when scrolling.  The gap looks to be about the same space as the editor top bar's height.

**Screenshots**
![tinymce-toolbar-gap](https://user-images.githubusercontent.com/11907254/48507115-09244b00-e819-11e8-9937-b167b0107246.png)

**Desktop (please complete the following information):**
- OS: Ubuntu 18.04.1 LTS
- chrome
- Version 69.0.3497.92 (Official Build) (64-bit)

**Additional context**
- Gutenberg v4.3.0
- Using 2019 theme

**Comment by designsimply** [comment]
I tested with WordPress 4.9.8 and Gutenberg 4.3 using Chrome 70.0.3538.77 on macOS 10.13.6 and couldn't see the gap above the classic editor block when scrolling:

![screen shot 2018-11-14 at 1 49 54 pm](https://user-images.githubusercontent.com/1119271/48511558-40dcc400-e814-11e8-807b-d7eec02ca377.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=15796&action=edit running WordPress 4.9.8 and Gutenberg 4.3 using Chrome 70.0.3538.77 on macOS 10.13.6.</sup>

Leaving the `Needs Testing` label for now and noting we should check from additional OSs because I used macOS and the original report was for Ubuntu.

**Comment by designsimply** [comment]
I tried again withChrome 70 on Windows 10 and included an image this time but still don't see a gap above the classic block toolbar when scrolling. ([screenshot](https://user-images.githubusercontent.com/1119271/48521927-d2a7f980-e833-11e8-8cd7-f737ee5e2ac9.png))

**Comment by ZebulanStanphill** [comment]
Unable to reproduce in WordPress 4.9.8 with the Twenty Seventeen theme using either Gutenberg `master` branch or Gutenberg 4.3.0. Tested on Antergos Linux using both Firefox Developer Edition 64.0b9 and Chromium 70.0.3538.102.

Notably, the original post mentions using "2019 theme", which I presume means Twenty Nineteen. It also doesn't specify the WordPress version. So this could be a 5.0-specific issue or an issue caused by the Twenty Nineteen theme. I have not tested with the WordPress 5.0 beta or Twenty Nineteen theme.

@timelsass Are you using WordPress 4.9.8 or the WordPress 5.0 beta? Are you using the Twenty Nineteen theme? Is everything on your site up-to-date?

**Comment by timelsass** [comment]
Yes @ZebulanStanphill, sorry about that - WordPress 4.9.8 running Twenty Nineteen theme.  @designsimply I just ran through testing on windows and mac.  After looking into it, it looks like this has been resolved pulling in changes from WordPress/twentynineteen@b2fa9c0dcc8d401a78e8005ef2d8d41622eb6df2 and WordPress/twentynineteen@8b6a5f861883e7566ac1a3032ef5585fb9228cc0  - I should have checked out other themes, my bad!  I'll close this ticket as it's not applicable for this repo - and a non-issue now.
