### ISSUE TITLE
Names and toolbar for alignwide and alignfull are confusing

### ISSUE THREAD

**Issue by joyously** [WordPress/gutenberg#11881]
**I think there is a design problem with GB classes `alignfull` and `alignwide`.**
These are not descriptive of what they are. They are width classes and I can never remember which is which. They have nothing to do with alignment. It is very confusing for a user to see the alignment and width mixture in the toolbar.

The problem is spreading, since themes will have to use these names and now #themereview is proposing adding a filtering tag to the repo called `align-wide`. 

The documentation will mention the names and have to explain them. I can see how this might be difficult to translate into other languages when it doesn't even make sense in English.

It would be easier to address before 5.0 than after.

**Comment by designsimply** [comment]
Maybe `fullwidth` and `widewidth` would be considered as alternate labels? 

Regarding putting them together in the toolbar, that makes sense to me because if something is full-width it doesn't need to also be left-aligned or right-aligned at the same time and so the choice makes sense to be one or the other and I can see them being grouped because of that (and I see this is a separate argument from them having 'align' in the naming).

Note: Typically, with regard to triage, may aim is to review and test without bias (as much unbias as possible!). In this case, I added some opinions above and would like to note they are mine only. I will also add the `Needs Design Feedback` label to try to get further perspective on the choices for the naming of the `alignfull` and `alignwide` as well as how they are grouped within the toolbar. Thanks for posting feedback!

**Comment by m-e-h** [comment]
I've gotten used to these but now that you mention it, I too struggled with the difference at first. 
fullwidth and widewidth make more sense to me.

**Comment by joyously** [comment]
Yeah, but which is which? Full and wide are the same to me. 
_AND_ there is no checking for image sizes, so you can insert an icon and make it stretch all across the screen.

**Comment by melchoyce** [comment]
Would `fullscreen` be better?

**Comment by joyously** [comment]
Yes! if that's what it is.

**Comment by joyously** [comment]
Although `fullscreen` has connotations of height and width. Perhaps screen-width or window-width. I'm not real sure what the other one is... column-width? content-width?  What is it supposed to mean?

**Comment by mapk** [comment]
It looks like, for the user, the two alignment options are labeled as `Full width` and `Wide width`. Is the main user interaction point the block toolbar? If so, it seems like they make sense in relation with their icons. If they still don't make sense here, a simple tooltip update with the appropriate text could happen.

![Screen Shot 2019-03-20 at 4 09 07 PM](https://user-images.githubusercontent.com/617986/54725172-5730be80-4b2b-11e9-976c-727a5b307ed0.png)
![Screen Shot 2019-03-20 at 4 09 14 PM](https://user-images.githubusercontent.com/617986/54725176-59931880-4b2b-11e9-8196-3988ec53ca5b.png)

I definitely understand the argument that they are not alignments, and maybe we can look into how to call them differently. 

But if this conversation is around how these terms are used in the code, especially for theme developers, then working this change in could get tricky.

**Comment by karmatosed** [comment]
As @mapk's comment shows the tooltips related to width, so, for now, let's close this as it can always be reopened and certainly has feedback.
