### ISSUE TITLE
using "/" to add block when you have more than 10 blocks matching the search word

### ISSUE THREAD

**Issue by slimmilkduds** [WordPress/gutenberg#11897]
We have 100s of reusable blocks, many which follow a similar naming convention. If you have more than 10 blocks that should be listed for a certain search word they don't appear in the list.

**To Reproduce**
1. Create 15 reusable blocks with the names "keyword 1", "keyword 2", "keyword 3", "keyword 4" etc
2. search for "keyword" using the / shortcut
3. only 10 of the 15 blocks are shown

**Request**
Not really sure, a scrollbar would be nice, or a "load more results". Something to at least suggest that you are not seeing everything that's actually available.

**Comment by draganescu** [comment]
I added a needs design label because for 100s of items I guess a scrollbar wouldn't help much and another interaction, well, needs design :)

**Comment by enriquesanchez** [comment]
For the design part, I wonder how much of an issue this still is now that we have a much taller block inserter, which has enough room to display more results.

But I agree, the search results should display all available items via scrolling or a "Show more" button.

**Comment by enriquesanchez** [comment]
>I wonder how much of an issue this still is now that we have a much taller block inserter, which has enough room to display more results

Correcting myself, because I understood this issue was happening in the main block inserter but the issue happens in the 'slash inserter'. I have created 20 reusable blocks all namespaced with "keyword" and I only see 10 results:

<img width="340" alt="Screen Shot 2020-04-28 at 12 04 53" src="https://user-images.githubusercontent.com/3276087/80516135-a2311e00-8948-11ea-8b22-83ab4ecc7a53.png">

The block inserter, for comparison:

![2020-04-28 12-00-53 2020-04-28 12_02_04](https://user-images.githubusercontent.com/3276087/80515793-246d1280-8948-11ea-8de8-94c2a2c624e5.gif)

----------

I think that allowing scroll would be the most obvious approach here, but I wonder if there are any historical reasons why we don't have it here. Perhaps @mapk or @karmatosed can chime in.

**Comment by enriquesanchez** [comment]
From https://github.com/WordPress/gutenberg/issues/21080#issuecomment-608365463:

>For quick inserter we have to be careful with how things expand when searching since it can take over the entire page. I can see listing a row of patterns there and an "browse all" link that just opens the sidebar panel for a better experience.

A "View more" link that takes you to the main inserter is also worth exploring.

**Comment by mapk** [comment]
The `/` inserter is really meant as a power feature for quickly adding blocks to the page. For this reason, any further UI involved with this interaction reduces its swiftness for adding blocks. I suggest we don't add more features to this feature. 😄 

Instead, if there are multiple blocks with similar names, maybe the efficiency is in how the users can name their blocks. Sometimes keeping features limited is part of the power they enable. 

In addition, now that the Inserter can be opened persistently, I feel this issue is less of a problem. I'm going to close this out for now.
