### ISSUE TITLE
Posts Page shows Classic Editor interface

### ISSUE THREAD

**Issue by pixolin** [WordPress/gutenberg#11982]
**Describe the bug**
Opening the Posts Page shows title and sidebar in Classic Editor style.

**To Reproduce**
1. Create a new page "Blog" and set it as posts page in Settings > Reading
2. Go to menu Pages 
3. Open posts page

**Expected behavior**
I expect the page to be displayed in the style of the new Gutenberg editor.
It is a confusing user experience, if the page looks like it was written in the Classic Editor. 

**Screenshots**
<img width="1027" alt="screenshot_362" src="https://user-images.githubusercontent.com/1968542/48627786-c21f8c80-e9b5-11e8-9c7f-b4bf716f15e7.png">

**Desktop:**
 - OS: MacOS 10.14.1
 - Browser Chrome, Firefox, Safari, … (latest versions)

**Additional context**
WordPress 5.0-beta5-43907

**Comment by swissspidy** [comment]
Core ticket: https://core.trac.wordpress.org/ticket/45263

**Comment by pixolin** [comment]
So… actually not a Gutenberg issue?
I close the issue then. Thank you Pascal.

**Comment by aduth** [comment]
Closing as fixed in core.

**Comment by creativecoder** [comment]
Note that this issue is not fixed in Core (though it is partly a Core issue). As things stand now, it's not even possible to add a filter to allow the posts page to be opened in the Gutenberg editor.

Here's the relevant Trac ticket that would add the ability to filter which editor is used for the posts page: https://core.trac.wordpress.org/ticket/45537

I'll re-open this issue, as it's relevant to full site editing (for example: edit.posts.page.mp4 from https://github.com/WordPress/gutenberg/issues/28341#issuecomment-801911429)

**Comment by creativecoder** [comment]
Note that this is resolved by the changes from https://core.trac.wordpress.org/ticket/45537, which are included in WP 5.8

**Comment by mtias** [comment]
Yes, sorry for the laconic close without context :)
