### ISSUE TITLE
Gutenberg editor not working after recent update

### ISSUE THREAD

**Issue by chandpasha1234** [WordPress/gutenberg#12036]
**Describe the bug**
When I click on creating new page/post or try to edit previous post it shows blank screen. If I deactivate plugin or open page/post with classic editor everything works fine. Clearing cache doest work.

![image](https://user-images.githubusercontent.com/44142514/48675001-0909af80-eb79-11e8-8803-ffc77544af42.png)
![image](https://user-images.githubusercontent.com/44142514/48675006-20489d00-eb79-11e8-8cb9-a78a0566b020.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Browser : Mozilla quantum, chrome

**Additional context**
Gutenberg 4.4.0

**Comment by designsimply** [comment]
Based on the first few errors listed in the screenshot (thank you for including that!!), I want to make a guess that it seems like it might be a problem with the update itself because if it really is a syntax error in the source code causing trouble then probably no one would be able to get the install (I _think_ this seems logical 🙂 but I am not 100% sure) and I know that several people have updated, including me so I know that 4.4 can work.

> SyntaxError: missing ) after argument list
> TypeError: wp-data is undefined

I also noticed:

> TypeError: AtD is not defined

AtD is After the Deadline. Do you have Jetpack installed and AtD (spelling and grammar) activated through Jetpack? If yes, may I ask the version? If that's the source of the trouble, I can help test that and it would be ace to confirm what you have in your setup.

May ask for a full list of your active plugins?

**Comment by chandpasha1234** [comment]
Sorry!
I added "defer parsing of javascript" to funtion.php which cause all this problem.
Now I removed it everything working fine.

**Comment by Soean** [comment]
Thanks, so I am closing this issue
