### ISSUE TITLE
events on html elements

### ISSUE THREAD

**Issue by g-thome** [WordPress/gutenberg#12039]
For some reason, I can't use react's synthetic events with my HTML elements. Only with Gutenberg components.
I had this code in my block, which was supposed to display an input text on my inspector column: 
`
<InspectorControls>
    <PanelBody>
        <PanelRow>
            <label>Timestamps</label>
        </PanelRow>
        <PanelRow>
            <input
                className="time-stamps"
                onChange={timeStamps => setAttributes({ timeStamps })}
                value={timeStamps}
            />
        </PanelRow>
    </PanelBody>
</InspectorControls>
`

It didn't work as I wanted because the onChange property wouldn't work so my text didn't update when I attempted to type in the field. I solved it by simply replacing my input with a PlainText. Problem is now I **need** to use an HTML audio element and I can't just replace it with something else.

This is my current code for my audio: 
```
export default class Audio extends Component {
    render() {
        const { attributes: { audioURL } } = this.props;

        this.log = () => {
            console.log('tick');
        }

        return (
            <audio id="audio_snippet" onTimeUpdate={this.log()} className="audio" controls>
                <source src={audioURL} type="audio/mpeg" />
            </audio >
        )
    }
}
```

As you can imagine, this.log() doesn't trigger because the onTimeUpdate doesn't work.

**Comment by aduth** [comment]
In your second example, you should be assigning the value of `onTimeUpdate` with the callback _function_, as otherwise you're passing the result of the function invocation.

`onTimeUpdate={ this.log }`

I wonder if your issue with `onChange` for the input element has more to do with the subtle differences between `onChange` and `onInput`. Could you try the latter?

There shouldn't be any reason why events wouldn't work as you'd expect on DOM elements as in any other React application.

https://reactjs.org/docs/handling-events.html

Pre-emptively closing as resolved, but we can plan to reopen if there's more to address here.
