### ISSUE TITLE
Wordpress Gutenberg

### ISSUE THREAD

**Issue by schusterjoh** [WordPress/gutenberg#12056]
If I want to publish a page which was created with Gutenberg it doesn't store the page. In the error-logfile I receife following message:
19.11.2018 11:51:50 ea-services.de [client 87.150.94.0] rdbm_handle_postscan_block: hostname=ea-services.de, client_ip='87.150.222.194', would captcha uri: '/index.php'
Working without Gutenberg it works fine
I'm using PHP 7.2.

**Comment by schusterjoh** [comment]
I Need help urgently

**Comment by catehstn** [comment]
Hi @schusterjoh - can you try some debugging steps so that we can try and isolate the problem?

What plugins do you have on this site? Can you try deactivating them and see if Gutenberg works, please?

**Comment by schusterjoh** [comment]
Yes, it works without Gutenberg

I just started the project and have no plugins installed.

As theme I use nextgen 18

Best regards

Hans

 

Von: catehstn <notifications@github.com> 
Gesendet: Montag, 19. November 2018 19:00
An: WordPress/gutenberg <gutenberg@noreply.github.com>
Cc: schusterjoh <schuster@sjconsulting.de>; Mention <mention@noreply.github.com>
Betreff: Re: [WordPress/gutenberg] Wordpress Gutenberg (#12056)

 

Hi @schusterjoh <https://github.com/schusterjoh>  - can you try some debugging steps so that we can try and isolate the problem?

What plugins do you have on this site? Can you try deactivating them and see if Gutenberg works, please?

**Comment by catehstn** [comment]
Can you please try with the 2019 theme?

**Comment by schusterjoh** [comment]
Hello,

I wanted to check the configuration of PHP 7.2

May you have a look to the attached document, if the configuration is ok.

Thank You

Johann

 

Von: catehstn <notifications@github.com> 
Gesendet: Montag, 19. November 2018 20:34
An: WordPress/gutenberg <gutenberg@noreply.github.com>
Cc: schusterjoh <schuster@sjconsulting.de>; Mention <mention@noreply.github.com>
Betreff: Re: [WordPress/gutenberg] Wordpress Gutenberg (#12056)

 

Can you please try with the 2019 theme?

**Comment by designsimply** [comment]
The attachment did not come through. I am not sure I would be able to tell what's going on from the PHP configuration, but what I can do is test with PHP 7.2 myself:

I installed WordPress 4.9.8 and Gutenberg 4.5.1 on a system using PHP 7.2.12 and found that I was able to create and publish posts using Gutenberg without any problems. 

I also tried searching the internet for more information about this part of the error you posted:

> `rdbm_handle_postscan_block`

But I couldn't find much. The only thing I could find was https://stackoverflow.com/questions/53069210/changes-in-wordpress-backend-result-in-downloads-of-php-files which describes a different problem where the php file is downloaded instead of displaying on screen when they try to create a new user or change site settings. This seems unrelated to the problem you described, and so I am not sure the error log message is related to the issue with publishing a page.

May I ask you to check on a few things?

First, can you open the console panel in your browser's development tools _before_ trying to publish a page and then watch what messages appear there after you try publishing? Messages that appear in that context may be more relevant in this case. I am not sure if helpful details will be there, but it's worth a check!

Next, because I haven't seen the `rdbm_handle_postscan_block` note before does not mean it's not relevant. Would it be possible for you to run another check where you try publishing a page and check to see if the error log from the server side shows that same error you saw before at the exact same time that you try publishing the post? This could help rule out that error appearing at another time which could mean it's irrelevant to the publishing problem.

I searched for https://wordpress.org/themes/search/nextgen+18/ and was unable to find it in the theme directory, so I think it may be a custom or paid theme. Where did you get the nextgen 18 theme?

To document what versions you are running, are you testing with WordPress 4.9.8 and Gutenberg 4.5.1?

**Comment by designsimply** [comment]
I am interested in helping to troubleshoot this with you. Please let me know if you're still having trouble publishing with Gutenberg.

**Comment by schusterjoh** [comment]
Hello,

I am working now with the German Version of Wordpress 5.0 with Divi Builder.

I have to build an Web-Site in English language.

My proplem is now, that several messages occurs in German Language and I can’t find a possibility to translate them into English. For instance when you are requested to give comments tob logs.

Wher can I translate this messages to English?

Thank you for your Help

Johann

**Comment by catehstn** [comment]
You can see how to change the language of your site here: https://www.hostpapa.in/knowledgebase/change-wordpress-language/

I'm closing this issue as it does not seem to be related to Gutenberg. I suggest you try the forums: https://wordpress.org/support/
