### ISSUE TITLE
Reusable blocks gone after update to 4.4.0

### ISSUE THREAD

**Issue by Powerball18** [WordPress/gutenberg#12062]
**Describe the bug**
After updating the gutenberg plugin the old reusable blocks don't show up in the autocompleter or the block menu. When you add a new one it will work as normal

**To Reproduce**
1. Add reusable blocks in old gutenberg version
2. Update gutenberg to 4.4.0
3. Check if reusable blocks are there

**Expected behavior**
All reusable blocks (old and new) are shown in the menu or autocompleter

**Comment by designsimply** [comment]
I tested creating a reusable block with Gutenberg 4.3 activated then updating from 4.3 to 4.5.1 and the reusable block was still there for my test. It's possible my testing steps weren't exactly the same as yours or that this issue is resolved in version 4.5.1. Here is a video to compare steps if needed: [39s](https://cloudup.com/cv6i_fL79jS).

Please try upgrading to the latest version which was just released today to check if the problem persists in your case. If you find I missed something in testing, please let me know and we can re-open.
