### ISSUE TITLE
Give feedback when pasted content is not allowed in a block.

### ISSUE THREAD

**Issue by Sjardo** [WordPress/gutenberg#12094]
**Is your feature request related to a problem? Please describe.**
When you paste a code-snippet into Gutenberg's paragraph block, I notice that it did not do anything. Checking the console for any error's or my part, but everything seemed to work fine! After asking around, this seemed to be intentionally. 

Yet, for a user to paste content (a code-snippet or anything else) that is not allowed in a certain block, should give feedback on the screen. Otherwise, users could think it's broken or did something wrong. This gives a bad user experience.

**Describe the solution you'd like**
The best UX, in this case, should be a notification with a clear message what is happening. If the content the user pastes is not valid for the block, give out a notification that it's not allowed. 

**Describe alternatives you've considered**
In my eyes the best solution would be to paste the content as text (rework any symbols to ASCII code if that's possible) and set out the warning that GB detected content that's probably better suited for the other block and give an option to switch to the other block.

**Comment by designsimply** [comment]
Thanks for testing and for posting a request. May I please ask that you reply with the code snippet you used so it is included here for reference?

I see why you are making this request, and I would also like to note that Gutenberg parses code such as the kind generated by word processors or other websites and modifies it to clean it up—in those cases, a notice like you are talking about is not needed or wanted—so there is a decision to be made. It is worth noting that Gutenberg favors the user experience where editing code is not required in order to use the editor and so a lot of notices about code would go against that. It is a choice made by the project.

You may already know about it, and I'm adding a quick note just in case: there is a Custom HTML block which was made for working with the kind of custom code which I think you are referring to.

**Comment by Sjardo** [comment]
Hi, thanks for your reply!

The code i tried to copy (from sublime text):
```<source media="(max-width: 480px)" srcset="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==" sizes="100%">```

I absolutely agree with all your statements, but one. If you expect to see a reaction from Gutenberg (after pasting, typing or anything else) and you do not get a visual response, users could think it's not working.

The post snippet should be placed in a custom HTML block or code-block, I'm aware of that. But when I accidentally try to paste it in a block (in this case, a paragraph), that does not work with the content I try to insert, I expect a notification or something like that with a message, for example:  "_The content you try to insert is not compatible with the block. Please try the other blocktype_".

I hope I could clarify my thoughts about the issue.

**Comment by designsimply** [comment]
> I absolutely agree with all your statements, but one. If you expect to see a reaction from Gutenberg (after pasting, typing or anything else) and you do not get a visual response, users could think it's not working.

I see your point. I think it's an intentional choice made by the developers in favor of not making a notification when pasted content is invalid or should be removed (such as the case I noted earlier where pasted content from word processors contains extraneous/unwanted code). Thanks for the discussion!

In reference to the example you provided, I looked up the `<source>` tag at https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source and found that it must be wrapped in the `<picture>`, `<audio>`, or `<video>` element.

I tested by copying and pasting the demo HTML from https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture into an empty block:

```
<picture>
    <source srcset="https://interactive-examples.mdn.mozilla.net/media/examples/surfer-240-200.jpg"
            media="(min-width: 800px)">
    <img src="https://interactive-examples.mdn.mozilla.net/media/examples/painted-hand-298-332.jpg" />
</picture>
```

and it was converted to: 

```
<figure class="wp-block-image"><img src="https://interactive-examples.mdn.mozilla.net/media/examples/painted-hand-298-332.jpg" alt=""/></figure>
```

Also, if I paste the same example without an `<img>` fallback:

```
<picture>
    <source srcset="https://interactive-examples.mdn.mozilla.net/media/examples/surfer-240-200.jpg"
            media="(min-width: 800px)">
</picture>
```

The pasted HTML does nothing—no warning is given and no image appears.

@iseulde is that the expected behavior when pasting a `<picture>` element containing `<source>` and `<img>` elements or just a `<source>` element or is this a separate bug compared to the request above?

**Comment by Sjardo** [comment]
To be sure you understand me, the code snippet was an example for this blogpost: https://sjardo.com/blog/disable-loading-images-on-mobile/. So I really don't want it to convert to anything else, then plain copy. (it's in there now, in a code-block). I just want a message that would have said the content I tried to copy (in this case, a code snippet) is not allowed in a paragraph. 

So the second example, where you get no warnings, is exactly the point I try to make. Just give a warning if Gutenberg can't do anything with the pasted copy. 

_(Sorry it took a while to clarify what I tried to explain, English is not my first language... )_

**Comment by ghost** [comment]
<img width="708" alt="Screenshot 2023-03-05 at 10 38 49 PM" src="https://user-images.githubusercontent.com/118618474/222987502-b2fc516e-4ad0-4708-9ca0-919b703037d0.png">

It seems this just gets escaped now, so I'll close this issue. As you've already mentioned we now also have the code block. If you feel like there's still something unresolved here, feel free to reopen the issue.
