### ISSUE TITLE
Classic editor 'more options' disappears at 220% zoom

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#12104]
Not sure how much of a problem this is, but if you zoom in the classic editor the 'more options' button disappears at a certain point. Here is 200%:

<img width="1259" alt="edit_post_ _wordpress_latest_ _wordpress" src="https://user-images.githubusercontent.com/1277682/48775709-c7d2e600-ecc5-11e8-903d-297f449b3cf2.png">

And it disappears at 220%:

<img width="1453" alt="edit_post_ _wordpress_latest_ _wordpress" src="https://user-images.githubusercontent.com/1277682/48775741-d6b99880-ecc5-11e8-923c-f88fc1498039.png">

The other buttons all wrap round properly as you zoom further

The more button also seems to be 1 pixel too far down vertically, and overlaps the border when you highlight it.

**To Reproduce**
1. Add a classic editor block
2. Zoom the browser window to 220%
3. Note the more options ellipsis menu disappears

**Desktop (please complete the following information):**
Mac+Chrome

**Comment by designsimply** [comment]
I tested using WordPress 4.9.8 and Gutenberg 4.4 with Firefox 63.0.1 on macOS 10.13.6 and found that the more menu moves from the top right of the block to below the block at 240% zoom.

![screen shot 2018-11-20 at 10 51 09 am](https://user-images.githubusercontent.com/1119271/48792800-6c4b2d00-ecb2-11e8-888c-c83594186bd0.png)
<sup>Seen at https://tan-otter.jurassic.ninja/wp-admin/post.php?post=19&action=edit running WordPress 4.9.8 and Gutenberg 4.4 using Firefox 63.0.1 on macOS 10.13.6.</sup>

I found the same for Chrome 70.0.3538.77 on macOS 10.13.6:

![screen shot 2018-11-20 at 10 54 07 am](https://user-images.githubusercontent.com/1119271/48792921-b6341300-ecb2-11e8-9a58-e84151eb2328.png)
<sup>Seen at https://tan-otter.jurassic.ninja/wp-admin/post.php?post=19&action=edit running WordPress 4.9.8 and Gutenberg 4.4 using Chrome 70.0.3538.77 on macOS 10.13.6.</sup>

This is the same behavior that we see on mobile (see background explanation at https://github.com/WordPress/gutenberg/issues/7256#issuecomment-435792345).

Perhaps it is still an accessibility issue due to how the placement of the button moves to below the block though?

**Comment by johngodley** [comment]
Ah yes, I was looking at a long block and didn't notice the menu was at the bottom!

**Comment by afercia** [comment]
Discussed during today's accessibility bug scrub. Usually, users who need a very high "zoom in" level use screen magnifier software. These tools shouldn't trigger the behavior that moves the More Options button to the bottom.

However, the real a11y issue here is that visual order doesn’t match the DOM order. Worth considering a good percentage of users with accessibility need use their mobile device connected to a keyboard: https://webaim.org/projects/screenreadersurvey7/#mobilekeyboard

Also, this issue seems already covered by #9739 ?

**Comment by sabernhardt** [comment]
Would it be a good idea to include "maximum-scale=2.0" in the viewport meta tag as a temporary fix, hoping that anyone who needs it larger than 200% uses a screen magnifier as well?

**Comment by anevins12** [comment]
We need content and functionality to work up to 400% and I don't recommend putting maximum scales on things - sounds like @afercia has found the underlying issue
