### ISSUE TITLE
2 bugs about content cut off with scrolling problems and korean order

### ISSUE THREAD

**Issue by MYIG** [WordPress/gutenberg#12110]
um... when I use gutenberg, I see it many many many times. I have to use F5.

![cap 2018-11-18 15-31-13-727](https://user-images.githubusercontent.com/44285360/48773795-c4fae400-ed0b-11e8-8594-16d1a337f1f7.png)
![cap 2018-11-18 15-31-55-000](https://user-images.githubusercontent.com/44285360/48773796-c4fae400-ed0b-11e8-893b-cd9ef6788396.png)

I don't know why... but it is a very common bug.

and... second bug. it is hard to explain because it is about Korean. My bad English skill... but it makes me angry many times too.

for example, 강 is made of ㄱ, ㅏ, ㅇ. so when I press backspace, it deleted 강 -> 가 -> ㅏ -> blank until I use spacebar.

![cap 2018-11-20 22-41-17-633](https://user-images.githubusercontent.com/44285360/48777359-b9141f80-ed15-11e8-8e8c-10de23cfd0e5.png)
when it is like that, 
![cap 2018-11-20 22-41-20-850](https://user-images.githubusercontent.com/44285360/48777369-bf0a0080-ed15-11e8-85c9-a84993cb8452.png)
it is no problem to use it.

but...
![cap 2018-11-20 22-42-58-902](https://user-images.githubusercontent.com/44285360/48777522-1b6d2000-ed16-11e8-8221-184bb5c3ec9d.png)
when letter is like that,
![cap 2018-11-20 22-41-24-651](https://user-images.githubusercontent.com/44285360/48777548-2b84ff80-ed16-11e8-9404-627efa71fa77.png)
it becomes like that... hmm...

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/44285360/48777838-05139400-ed17-11e8-8c3c-da6ceeb2c575.gif)
가나다라마바사 -> 가나다라마바 -> 가나다라마 -> 가나다라 .... it is normal but
가나다라마바사 -> 가나다라마바ㅅ -> 가나다라마ㅅ ->가나다라ㅅ it becomes that... please fix it.

**Comment by designsimply** [comment]
@MYIG may I please ask for you to move the 2nd bug to a new issue so that each one can be reviewed individually? Thank you!

For the issue you reported having to use F5, is it correct that the problem is the meta boxes sometimes do not appear until you refresh the page? 

I tried replicating the problem by installing the following two plugins which I saw meta boxes for in your 2nd screenshot:

1. https://wordpress.org/plugins/easy-social-share-buttons/
1. https://wordpress.org/plugins/seo-by-rank-math/

In my test, I was able to see the Rank Math SEO meta box appear normally. I tested using the Gutenberg Demo post with Chrome 70 on Windows 10 ([screenshot](https://user-images.githubusercontent.com/1119271/48794489-5b50ea80-ecb7-11e8-9626-26e26519797a.jpg)) and with Firefox 63 on macOS.

I noticed the editor area appears cut off in your first screenshot, including the scrollbar to the right. May I please also ask for you to list your OS, browser, WordPress, and Gutenberg plugin version numbers for reference?

I see that you have many plugins installed. It's possible this problem is due to a plugin conflict of some kind. The typical advice in this case would be to ask you to turn off all other plugins and switch to the default theme temporarily to see if the problem happens in that scenario. I understand that it may be a difficult request and I can offer a temporary test site by going to https://jurassic.ninja/create?nojetpack&gutenberg&shortlived (the site will last for one hour) which would be good for you to use as a test to see if the problem happens for you without the influence of other plugins possibly creating a conflict. Are either of those options something you can test from your side?

**Comment by MYIG** [comment]
@designsimply okay I will post againㅎㅎ second bug is veery important to me.

um... I feel not don't appear but deleted. it is like... 'it is not scrolled but there is nothing, but I can't scroll more so there is nothing.' of course, I can see that box normally, but it often appears.

Windows 10 1803,  chrome 70.0.3538.102, wordpress 4.9.8 and gutenberg 4.4. oh there is 4.5 now. I will tell you again there is a that bug again.

**Comment by designsimply** [comment]
Thank you! I will review #11956 separately and I would also like to move the discussion about scrolling problems and content cut off to #11185 which has more information from others reporting similar problems.
