### ISSUE TITLE
The "Block created" and "Block updated" messages shouldn't be persistent

### ISSUE THREAD

**Issue by johnbillion** [WordPress/gutenberg#12127]
**Describe the bug**

When creating a reusable block, the "Block created" confirmation message appears but remains persistent until the user actively dismisses it.

The same occurs when updating (for example, naming) a reusable block. The "Block updated" message is persistent until the user dismisses it.

This results in confirmation message stacking when saving the post. See screenshot.

**To Reproduce**
1. Create a new post.
2. Insert content into a block
3. Convert the block into a reusable block
4. Note the confirmation message, and note that it is persistent
5. Publish the post
6. Note the "Post published" message and the "Block created" message stack on top of each other

**Expected behavior**

Ideally the confirmation messages for reusable blocks would disappear after a timeout, or disappear at least when the post is published to avoid stacking.

**Screenshots**

<img width="557" alt="" src="https://user-images.githubusercontent.com/208434/48797191-caebc780-ed01-11e8-9255-50d1b81f62ca.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 70

**Additional context**
- Gutenberg version: WordPress 5.0 beta 5

**Comment by pmmueller** [comment]
Same with the message "Post updated" and "Page updated" after saving a post or page. It stays visible until you click on the x. There's a couple of annoying things due to that behavior: 

1. If the post or page is saved every now and again that message will be up there more or less permanently, which defeats its purpose really. 
2. A click in the title open the permalink - perfectly hidden behind that message. 

Ideally the messages would disappear after a timeout. 

![bildschirmfoto 2018-11-23 um 16 56 27](https://user-images.githubusercontent.com/1928205/48952202-a3833d80-ef41-11e8-959a-77aa99433d4f.png)

**Comment by KokkieH** [comment]
Another request for this from the [WordPress.com forums](https://en.forums.wordpress.com/topic/post-updated-notification/).
