### ISSUE TITLE
Find a more durable process for measuring the block editor width

### ISSUE THREAD

**Issue by antpb** [WordPress/gutenberg#12135]
@aduth mentioned in https://github.com/WordPress/gutenberg/pull/11973 a need for a more durable way to measure the block editor width. 

> I went with something like this in 87130e4, considering it a temporary solution, cached as much as is reasonable (cleared on window resize).

_Originally posted by @aduth in https://github.com/_render_node/MDExOlB1bGxSZXF1ZXN0MjMxNTEzMDI1/timeline/more_items_

There are some concerns with determining block editor width and the following review thread summarizes most of them: https://github.com/WordPress/gutenberg/pull/11973#discussion_r235048751

As work is finishing up in https://github.com/WordPress/gutenberg/pull/11973 this issue is getting created so we do not lose that action item of improving logic that determines block editor width.

**Comment by paaljoachim** [comment]
Should we close this issue, Anthony?

**Comment by ndiego** [comment]
This issue was reviewed in today's Editor Bug Scrub. Given that we can now define layout settings in theme.json that set content widths, I *think* this issue can be closed. Concerning images specifically, there are a number of other open issues, including [this recent one](https://github.com/WordPress/gutenberg/issues/46987). That said, feel free to reopen if I am misinterpreting this issue. Thanks!

**Comment by roborourke** [comment]
@ndiego bit of a blast from the past but, now that container queries are more widely supported, it's possible that if `.editor-styles-wrapper` was set as a container, and any `@media` queries were modified to `@container` queries (maybe in the `add_editor_style()` helper? Then all those visual discrepancies between front end and editor when various sidebars are open would be solved. This could remove the need to calculate the editor width altogether perhaps.
