### ISSUE TITLE
Gutenberg Issues

### ISSUE THREAD

**Issue by Dhiggins79** [WordPress/gutenberg#12146]
I will use this as running issues thread. I will update when new things happen and when things are fixed. I use Gutenberg in my website, a newspaper. Publish approx. 32 posts per day.  Version: 4.5.0(11/20/2018)
BTW, I love this plug-in. But it does have issues and I get that. That's why I'm adding what I see. I use lots of different formats daily.

**Issues:**

Tags- when adding tags they keep disappearing when pressing enter. I end up having to add tags from the "All Posts" page.
Tables aren't adjustable
Would be nice to have a section to add "authors", such as I publish press releases. I post them, but they are written by another entity. 
Adding images to left or right of text causes uneven lines and no way to fix.
A few updates ago, categories were set as most used first... then it switched to alphabetical order. Better as most used first.
Sometimes, not always when adding caption to uploaded image_( in the media upload AND within article)_ it doesn't show when inserting same image from media library into article.
Seems layout is getting squished. I used to be able to have more on each line. Such as Tables. They used to fit when copied and pasted, now they become squished and distorted.
Would be better if in scheduling calendar would be were above time. Just easier, personal opinion, don't know how anyone feels on that. 
On an earlier version you could have "most used" blocks/inserts/formats that would pop up on the side of the block. Now you have to into the whole thing and search. 
erasing blocks needs to be easier. Sometimes I get a random empty block. I can't just erase it. I have to type something in it and then go to "remove".

I will add screen shots as I come across things, I just stumbled on doing this tonight after I finished my work, but wanted to get my thoughts in here before I forgot. Thanks

****Desktop**** 
 - OS:Windows 10, current on all updates
 - Browser Chrome
 -Version 70.0.3538.102 (Official Build) (64-bit) 11/20/2108

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by designsimply** [comment]
The function of the GitHub repository is mainly to report bugs. We also try to keep issues isolated so that there is one bug report per issue. Your list has several things which still need troubleshooting or more information, some things which have explanations for why they are the way they are, and some which already have solutions. I would like to help you get all of those things sorted out. May I please ask you to move this request to the forums at https://wordpress.org/support/plugin/gutenberg and provide a link in a reply here? Would you please also make a note of your theme and list your active plugins when you create a new request in the forums?

Thank you so much for testing Gutenberg and posting about your experience! And thank you if we can pick up this conversation in the forums to start so that we can come back to the GitHub repository with more details and one report per issue that cannot already be explained via a forums thread.

**Comment by Dhiggins79** [comment]
Thanks and sorry for posting in the wrong area. I  will get it moved.

**Comment by GanJyothsna1977** [comment]
I am a student for WordPress and trying to develop my profile website. Until I had WordPress 4.9.8, Gutenberg was working and now after updating to 5.0.1, it has become unusable. As I searched the plugin, it says that the plugin does not work in 5.0.1 and tested till 4.9.9. How can I make it work?
This is the page below which I get as I try to edit the page
![image](https://user-images.githubusercontent.com/37164985/49984787-874a4d80-ff8f-11e8-929c-40101fdb8d7f.png)
