### ISSUE TITLE
"Disable the visual editor when writing" option shouldnt show code editor

### ISSUE THREAD

**Issue by Zodiac1978** [WordPress/gutenberg#12211]
**Describe the bug**
If someone has checked the option "Disable the visual editor when writing" in the profile Gutenberg is showing the code editor. 

Assuming an user who has checked the box is updating to WP 5.0 the user will see the code editor of a classic block. No option to convert to blocks and no notice why this is not showing blocks. I think this is bad NUX.

If a user is already using Gutenberg, this option will show the code editor for all the blocks. With all the comment markup to configure the blocks. Editing this is for professionals who know what they do. It is risky to break something here. 

**To Reproduce**
1. Update to Gutenberg 4.5.1
2. Check the box in your profile: "Disable the visual editor when writing"
3. Edit a post

**Expected behavior**
I would expect to see the classic block with the text/HTML mode instead of the visual editor and all Gutenberg blocks with their "Edit as HTML" option enabled (if available).

This is IMHO what the checkbox "Disable the visual editor when writing" is saying.  - Show me the markup and no visual representation of it.

**Additional context**
- Gutenberg 4.5.1

**Comment by ktmn** [comment]
Left me confused for a while. It should at least have a message indicating what's going on.

The option should only apply for the classic editor block. Which doesn't even have text mode afaik.
For example I wanted to edit an old table with custom classes (meaning I wouldn't want to use the table block) but there isn't even text mode in the classic editor block so I had to switch the whole Gutenberg to text mode.

**Comment by Zodiac1978** [comment]
After millions of downloads it seems to be just a problem for 4 people. I assumed this would be a bigger problem in the support forums. It obviously isn't.

https://wordpress.org/support/topic/pages-presenting-in-html-only/
https://wordpress.org/support/topic/why-force-us-to-use-a-text-editor/
https://wordpress.org/support/topic/visual-and-block-editor-are-gone/
https://wordpress.org/support/topic/gutenberg-not-working/

Now the release has happened and no one from the Gutenberg team followed my opinion about the expected behavior. So I am closing this thread myself.

**Comment by danekee** [comment]
Im glad to read it here. Im very dissapointed with similar issue.

Im using Guttenberg for quick nice looking style, but not for main posts, where Im using my own, build for years, **structure & functions**. Also I want use classic editor due to many Quictktags defined on my own and I didnt find a way to use quicktags in guttenberg. I want it to be working due to back compatibility with many older my posts created via classic code editor. And even for new one. Many of them is snippets for html. Maybe I will manage it with custom blocks if it would be possible. I need learn guttenberg more... But I have doubt of capability use all quicktags as custom blocks, because many of them is only partial html, predefined classess for quick inserting etc... thats what quicktags are goodfor. And they are irreplaceable... whole child theme is working working it what QT can done. And they are important for you to need not remember what you need to do with code in your own theme.  No discussing about QT. But with guttenberg they are unusable... 

Further when Im using classic editor plugin, Im facing issue you described here in this way:
Enable visual editor is the only way to get the guttenberg block works.
But cant in the edit classic editor(plugin) as a code, because there is old visual editor, probably forever not posible to switch to text editor next link. Its there but not reaction...
So editing old post or for make any post with my quicktags button edns with several setting to have to be done... 
**The main problem of guttenberg is bad back compatibility!** (I see it as label here now, so we understand each other I hope) Thats NUX (if I understand it as Negative User eXperience correctly)

**Comment by Zodiac1978** [comment]
NUX = New User eXperience
