### ISSUE TITLE
How are edit methods dissected when displaying the editor?

### ISSUE THREAD

**Issue by mrmadhat** [WordPress/gutenberg#12227]
When constructing a block the `edit` method might include components such as `InspectorControls` and `BlockControls` to add settings in the sidebar/block toolbar. I would like to know how these components make it into the sidebar and block settings when the editor loads.

I imagine when a block is selected the sidebar will somehow look at the construction of the component and if it finds an `InspectorControls` component it loads it. Potentially something to do with the active component being passed into the sidebar as a prop then mapping through the children of the prop?

Could someone explain what's happening or link me to a doc/article that explains it?

Thanks

**Comment by aduth** [comment]
A high-level overview can be found here:

https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/block-tutorial/block-controls-toolbars-and-inspector/#inspector

A more low-level / technical explanation is that it uses a combination of:

- [`Slot` and `Fill` components](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/slot-fill) to render elsewhere in the page (i.e. rather than in the blocks listing, show something in the sidebar).
- [React's Context feature](https://reactjs.org/docs/context.html) to transmit block selection information directly from the block renderer to the inspector controls element, to avoid a block developer needing to manage whether the component be rendered only when a block is selected.
   - See #5029
   - https://github.com/WordPress/gutenberg/blob/62f61631bef4b97be519773eb1b949a847dc493c/packages/editor/src/components/inspector-controls/index.js#L13
   - https://github.com/WordPress/gutenberg/blob/62f61631bef4b97be519773eb1b949a847dc493c/packages/editor/src/components/block-edit/context.js#L45-L61

**Comment by mrmadhat** [comment]
That's exactly what I was look for, thanks @aduth
