### ISSUE TITLE
Multiple Issues With Certain Posts

### ISSUE THREAD

**Issue by brazenvoid** [WordPress/gutenberg#12259]
**Describe the bug**
I have this post which is in a classic block:

![editor view](https://user-images.githubusercontent.com/8722533/48960633-fdaaef80-ef8f-11e8-85ca-ffd9c785df19.JPG)

The preview shows me this:

![preview](https://user-images.githubusercontent.com/8722533/48960643-1915fa80-ef90-11e8-8f14-467fd477d15d.JPG)

The live version is fine.

The other issue is that converting to blocks doesn't work. The controls experience a flicker and that's it. The console has the following errors:

![console](https://user-images.githubusercontent.com/8722533/48960697-c0932d00-ef90-11e8-8c54-ef89dfcb3c1d.JPG)

**To Reproduce**
I can perhaps give the tester access to the site. Or I can help testing it.

**Desktop**
 - OS: Windows 10
 - Browser: Firefox
 - Version: v63.0.3

**Additional context**
- I don't know, its a site on WP free plan, should be latest.

**Comment by designsimply** [comment]
I tested with WordPress 4.9.8 and Gutenberg 4.5.1 and the Twenty Seventeen theme and I don't see the same problem happening there. The description of the problem sounds to me like it _might_ be theme-specific. Consider changing themes (such as to Twenty Seventeen) temporarily and check to see if the same problem happens with a different theme. I also noticed your blog is hosted on WordPress.com and I suspect the issue is either related to the theme you're using or to that specific hosting environment, so you will want to report the issue to the WordPress.com support team directly. To do that, got to https://wordpress.com/ and log in. Then look for the `(?)` icon near the bottom right of your screen. You should see a "Contact us" option if you click on the `(?)`.

When you report the issue, you should include:

* A link to this GitHub issue (specifically the console errors are important to report).
* Note your current theme and mention whether you've tested any other themes and if the same problem happens for you in other themes.

Thank you for using Gutenberg and for reporting this issue.
