### ISSUE TITLE
Scheduling

### ISSUE THREAD

**Issue by runnyunder** [WordPress/gutenberg#12256]
When editing a post - add a check if a post is already published, so that it can not be then re-scheduled.

Already Published posts should not be able to be scheduled for a later date - or at least display a warning especially if a post has comments - the date for that comment, could be then shown to be 'earlier' than the 'original date/time' shown.

**Comment by sarahmonster** [comment]
I've tested this and it looks as though one can edit the publish date of a published post into the future, effectively un-publishing it. This feels rather like expected behaviour, but it could be worth showing a warning. That said, it's possible that suggested changes in #7602 will help reduce confusion here by clarifying when the post will be published better.

**Comment by karmatosed** [comment]
I think for now this should be closed. There is an unpublish link being added that helps a little. If this does still need iterating, we can always reopen.
