### ISSUE TITLE
Special characters NOT emojis

### ISSUE THREAD

**Issue by MaricaCB** [WordPress/gutenberg#12297]
**Is your feature request related to a problem? Please describe.**
I frequently need to insert special characters relating to statistics. Ex. x-bar, delta, alpha, beta, etc.

**Describe the solution you'd like**
The old omega special characters button in the format text menu

**Describe alternatives you've considered**
There are none that I am easily capable of doing.

**Comment by designsimply** [comment]
This was discussed in #1678 and ended with the character map being accessible in the Classic block and encouragement to implement in other areas as a plugin. I also added a note on that issue referencing your reason for the request so that all of the requests about the character map are consolidated in one issue.

**Comment by MaricaCB** [comment]
Thank you!
