### ISSUE TITLE
Clicking Wide or Full alignment makes the Image block jump

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#12292]
Tested with Twenty Nineteen because it supports "Wide" or "Full" alignments.

When clicking the "Wide" or "Full" alignment buttons in an Image block, the image "jumps" a bit down, even though there's no apparent reason for the extra space to exist. Here's a GIF:

![wide](https://user-images.githubusercontent.com/1682452/48983320-9b680100-f0ed-11e8-9f0d-48d77296f7ba.gif)

This seems to happen only on the Image block. Doesn't happen on other blocks that support wide and full alignment, e.g. Columns, Cover, Gallery.

As far as I can tell, the jump is caused by one single line of CSS: `position: relative` here:

https://github.com/WordPress/gutenberg/blob/b5a709fc63a11f042c53f67f80a2eaf50713e00a/packages/edit-post/src/components/visual-editor/style.scss#L32-L41

To my understanding, especially after https://github.com/WordPress/gutenberg/pull/7365, the toolbar should be completely pulled out from the layout flow. That's the reason why it normally uses `position: absolute`. 

However, with a wide or full alignment, it gets `position: relative;` so it still takes some space in the layout.

Pushing a PR to remove `position: relative;` would be trivial and in my testing it would fix the issue. However, I'm not sure if there are other reasons for `position: relative;`. /Cc @jasmussen

**Comment by jasmussen** [comment]
Thanks for a very solid ticket with even a suggested fix.

However that fix won't do it. When removing the position relative, this happens:

![sans-position-relative](https://user-images.githubusercontent.com/1204802/49005362-cd697980-f166-11e8-9a13-f8820b3e9a83.gif)

Due to the change we recently made to TwentyNineteen this wasn't easily discoverable, but as you ticketed yourself in https://github.com/WordPress/twentynineteen/issues/665 that behavior might need a revisit. Basically we need the block movers to be available also for fullwide images. 

I will see if I can find another fix.

**Comment by afercia** [comment]
Ah, I see, that's with Twenty Seventeen and the toolbar docked to the block left edge. Right.

**Comment by jasmussen** [comment]
Submitted fix in #12305.
