### ISSUE TITLE
Autosave continues to trigger for published posts when no changes applied

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#12318]
**Describe the bug**

I discovered that autosave triggers even when there were no changes applied only for the published post. It works perfectly fine for drafts.

**To Reproduce**
1. Create a post (it isn't related to demo post only), write some content and publish it.
2. Reopen your published post.
3. Open network tab in your browser's developer tools.
3. Change something in one of the blocks.
4. Observer autosave being triggered after your changes were autosaved.

**Expected behavior**
Autosave is triggered only once after content in the published post has changed.

**Screenshots**
![autosave-published-post](https://user-images.githubusercontent.com/699132/49020293-62349d00-f190-11e8-96c6-735ff5f7dde2.gif)

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Chrome
 - Version: 70

**Comment by aduth** [comment]
It's technically expected that the post remains "dirty" after an autosave occurs, because it is not a full save for a published post. So while we expect the user should be _prompted_ about unsaved changes (which occurs in the classic editor as well), the autosaves themselves should discontinue after the first.

**Comment by aduth** [comment]
This may require some new state to distinguish a post which is dirty _but for which a user has not made changes since the last save_, to be used in considering whether the `AutosaveMonitor` component should schedule an autosave. In other words, a post may be dirty (prompt on navigate) but not a candidate for autosave.

Reducer pseudo-code:

```js
function hasUnsavedUserEdits( state = false, action ) {
	switch ( action.type ) {
		case 'REQUEST_POST_UPDATE_SUCCESS':
			return false;

		case 'EDIT_POST':
		/* ... all other user edit actions as `case` */
			return true;
	}

	return state;
}
```

There's some conceptual overlap with the `getReferenceByDistinctEdits` selector, and it's not necessarily safe to assume that some actions are in-fact user-initiated, so there might be some alternative I'm overlooking here.
