### ISSUE TITLE
Is there a limit to the number of child elements rendered in SVG for block type icon?

### ISSUE THREAD

**Issue by willdelphia** [WordPress/gutenberg#12391]
I have been trying to create a block type with a custom SVG icon. No matter what I try only two of my three polygons are being rendered. Is this 2 limit something that was intentional? Is there a way to include an SVG icon with more than two child elements? 

Heres the code in question: 

```
   var icon= el("svg", { width: 20, height: 20, viewBox: '0 0 20 20'  },
        el(Fragment, 
            el("polygon", { points: "5.33 14.09 0 10.96 0 9.31 5.33 6.18 5.33 7.83 1.5 10.14 5.33 12.42 5.33 14.09"}),
            el("polygon", { points: "6.61 5.55 8.5 5.55 10.07 8.37 11.47 5.55 13.41 5.55 10.96 9.97 13.45 14.46 11.56 14.46 9.86 11.48 8.42 14.46 6.55 14.46 8.84 10.01 6.61 5.55"}),
            el("polygon", { points: "14.68 6.18 20 9.31 20 10.96 14.68 14.09 14.68 12.44 18.5 10.13 14.68 7.85 14.68 6.18"}),

        ));

```

**Comment by willdelphia** [comment]
I was able to get around this issue by converting my three shapes to a compound path in illustrator. Though I am still curious why my first attempt didn't work.

**Comment by designsimply** [comment]
I tried researching this and found the following note in #11640 which seems relevant:

> The documentation of "Managing block categories" was wrong as on the server we can not set SVG icons. The server would not be able to use our SVG component.
> This PR fixes the documentation and adds a new action that allows updating the icon on the front end in a simple way.

Please note that I am new to JavaScript! I looked at the example in the handbook for setting an SVG icon for the category and it looks a bit different compared to yours and I was wondering if you could have a look, since there's evidence it has been updated, to see if it's more helpful to you now?

https://wordpress.org/gutenberg/handbook/designers-developers/developers/filters/block-filters/#managing-block-categories

**Comment by aduth** [comment]
I was able to reproduce the original issue, but I narrowed down the root cause to be ambiguity on the second argument of `createElement`. In your example, the first polygon is misinterpreted as the props of the element and thus does not appear. When you explicitly provide `null` or an empty object as the second argument instead, all three polygons would appear.

https://jsbin.com/wowawen/1/edit?html,js,output
