### ISSUE TITLE
WP 5 Compatible check-mark / filter in plugin search

### ISSUE THREAD

**Issue by burnuser** [WordPress/gutenberg#12412]
**Is your feature request related to a problem? Please describe.**
With WP 5.0 a lot of Plugins stop working or don't work correctly. Finding Plugins in the WordPress Plugin repository with approved WP 5.0 compatibility would be very important for (re-) building a site without problems.

**Describe the solution you'd like**
Implement a check-mark / filter for Version compatibility (with listing of versions like 5.0, 5.1, 5.2, ...) in the search form of the plugin repository https://wordpress.org/plugins/
And if you change the search form, add range-filters for standard informations like "Last updated", "Active installations" and "Ratings" too please.

**Describe alternatives you've considered**
You can search regular and check compatibility afterwards, but with hundreds of search results according to common search terms this is a unnecessary hard and time consuming work!

**Comment by swissspidy** [comment]
Please note that there's already "Tested up to:" in the plugin repository.

Extending the search functionality in WordPress and on WordPress.org is not related to Gutenberg as the editor. That's why I'm closing this issue here.

For this we use the https://core.trac.wordpress.org/ (core) and https://meta.trac.wordpress.org/ (WordPress.org) issue trackers. There are already multiple tickets suggesting similar enhancements on these issue trackers.

NB in my personal experience the majority of plugins continue to work just fine with WordPress 5.0. Plus, there's already the "Tested up to" information for plugins that gives a hint at a plugin's compatibility.
