### ISSUE TITLE
Embedded URL works on classic editor but not using Embed block

### ISSUE THREAD

**Issue by woorise** [WordPress/gutenberg#12421]
I am trying the following URL in the Embed block on WordPress 5 RC1 and I get the error "Sorry, we could not embed that content." But at the same time it works fine on the front end.

https://woorise.com/wr/ps4-slim-10-games

The URL is a custom post type on a WordPress multisite installation. When I use the classic editor (or previous versions of WordPress) it works as expected.

I have installed the following plugin that uses the wp_embed_register_handler() function.
https://wordpress.org/plugins/woorise/

I have also checked the console and network tabs for errors but I don't get any.

**Comment by swissspidy** [comment]
Support for `wp_embed_register_handler()` was introduced in #6345, but it doesn't seem to (properly) work anymore with WordPress 5.0. I added a core ticket for it now: https://core.trac.wordpress.org/ticket/45447

In your specific case I don't really see why you use `wp_embed_register_handler()` though.

That function should be used for sites that do not support oEmbed. However, woorise.com runs on WordPress, which supports oEmbed out of the box. Including iframe resizing and everything.

It even still advertises oEmbed support. The problem is just that somehow your URLs aren't recognized:

```
https://woorise.com/wr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwoorise.com%2Fwr%2Fps4-slim-10-games
```

I'd recommend you to use the built-in WordPress oEmbed functionality to embed your giveaways. This way it will work not only in Gutenberg/WordPress, but any other website out there that supports oEmbed. Plus, nobody needs to install any plugin to embed your content.

**Comment by woorise** [comment]
@swissspidy Thank you for your suggestion. I tried to edit the embedded templates and load the required scripts (I am using a Gravity Form inside the embedded content) but I can't submit the form and I am also get the following error. Is my case something that can be done with WordPress so I can continue investigating?

SecurityError: Permission denied to access property "document" on cross-origin object
