### ISSUE TITLE
Limit formatting button appearance to a specific block

### ISSUE THREAD

**Issue by mahdiyazdani** [WordPress/gutenberg#12439]
I was wondering if there is a way to restrict the already registered (new) formatting button for a particular block?

Related: #11727

**Comment by designsimply** [comment]
_Restrict_ the formatting button? Can you give a more specific example of what your trying to do?

Aside: I did try checking the [Format API documentation](https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/format-api/) but didn't spot anything there about restricting or removing existing format buttons.

**Comment by seb86** [comment]
I too would like to remove a format option for my custom block. I would like to disable the **Inline Image** format but leave the rest alone. I only want text format options to be available for the Rich Text component. Is there a new settings variable that we have to pass like when we enable support for alignment?

Currently I have.
```
supports: {
		align: [ 'wide', 'full', 'center' ],
}
```
Do I or Could We append to this like so?
```
supports: {
		align: [ 'wide', 'full', 'center' ],
		format: [ 'code', 'strikethrough', 'uppercase' ],
}
```
P.S The uppercase would be CoBlocks format.

**Comment by aduth** [comment]
I'm not certain this is currently possible. The default format types are registered in the [`format-library` package](https://github.com/WordPress/gutenberg/tree/master/packages/format-library), using the [`registerFormatType` function](https://github.com/WordPress/gutenberg/tree/master/packages/rich-text#registerFormatType) from the [`rich-text` package](https://github.com/WordPress/gutenberg/tree/master/packages/rich-text). While it's not exposed on the public interface of the package, it is possible to unregister format types using the data module (`wp.data.dispatch( 'core/rich-text' ).removeFormatTypes`). However, since `rich-text` is not distinct per block type, if format types were removed, they would be removed from all block types.

**Comment by youknowriad** [comment]
cc @ellatrix in case you have more information here.

**Comment by ellatrix** [comment]
Do you mean for a block that you yourself are registering? Then yes, since #14542.

**Comment by patelshveta** [comment]
Is this possible to remove certain format type for core blocks like 'core/heading' but not for other core blocks in wordpress version 5.3?

**Comment by rleecrewmp** [comment]
For anyone stumbling upon this, it is possible to limit the [appearance of your custom format button](https://developer.wordpress.org/block-editor/how-to-guides/format-api/#step-4-show-the-button-only-for-specific-blocks-optional).
