### ISSUE TITLE
.mp4 video in Classic block isn't displayed correctly

### ISSUE THREAD

**Issue by JuliaArr** [WordPress/gutenberg#12454]
The height of the embed .mp4 video is cut.
Steps to reproduce the error:

1. Add new Classic Editor.
2. Add Media
3. Upload .mp4 file
4. See error: https://www.screencast.com/t/KBwkdwJSTwF - its height is 150px instead of needed 640px

![2018-11-29_1641](https://user-images.githubusercontent.com/1119271/49392039-82adab80-f6ea-11e8-919a-d9e26b4cc976.png)

I'm using Twenty Nineteen default WordPress theme.
WordPress development version 5.0-RC1-43946

**Comment by talldan** [comment]
This issue was discussed during a bug triage session on slack (requires signup or account to view the link):
https://wordpress.slack.com/archives/C02QB2JS7/p1565247029339000

Two of us could still reproduce the issue in the block editor. We also test in the classic editor, which doesn't seem to exhibit this behaviour, so this issue does seem to be in the right place.

**Comment by youknowriad** [comment]
It looks similar to #10806 Maybe a duplicate.

**Comment by afercia** [comment]
Note: this applies also to [audio and video playlists](https://github.com/WordPress/gutenberg/issues/16054#issue-453789628).

**Comment by paaljoachim** [comment]
Testing with WordPress 5.7 beta 3.
Twenty Twenty One.

I am wondering if this PR by @glendaviesnz 
https://github.com/WordPress/gutenberg/pull/23547 has taken care of the problem.

This is what I am seeing in the backend.
![Screen Shot 2021-02-21 at 18 17 05](https://user-images.githubusercontent.com/5323259/108632824-283aca00-7471-11eb-9d39-89a6cd01a86e.png)

I also check the code and it looks differently then the example you provided @JuliaArr 
I will go ahead and close this issue. If that is a mistake then please reopen.
