### ISSUE TITLE
Inactive Add-New Block

### ISSUE THREAD

**Issue by bright-guy** [WordPress/gutenberg#12488]
Blocks are not active. All blocks have been replaced by what appears to be a single block.

Please see attached screenshot for details.
<img width="1552" alt="screen shot 2018-11-30 at 5 22 51 pm" src="https://user-images.githubusercontent.com/5422510/49318297-00dd3880-f4c6-11e8-8981-bac81b550413.png">

**Comment by swissspidy** [comment]
You're just in the code editor, not the visual editor. You can switch back via the three dots in the top right corner:

<img width="297" alt="screenshot 2018-12-01 at 14 02 53" src="https://user-images.githubusercontent.com/841956/49328475-dba60400-f571-11e8-89e1-6ad6283d8ac0.png">

Also make sure the "Disable the visual editor when writing" box is **not** checked in your user profile, otherwise the code editor is the default.

**Comment by bright-guy** [comment]
Thank you. Thank you, so much. Your solution worked!
