### ISSUE TITLE
Add Gutenberg Editor for category description

### ISSUE THREAD

**Issue by Jabe64** [WordPress/gutenberg#12511]
As Gutenberg will be integrated for Posts & Pages, so should it be for Category Descriptions too.

I wanted to vote for such feature but didn't find anything about it…

**Comment by designsimply** [comment]
Gutenberg only covers the editor area in this first phase but will eventually expand to other areas. I believe one of the next areas to be considered will be menus, for example. Because work isn't being done on category editing yet and because scope is still being set for the next phase, I will close this issue and also place it in the Ideas project to be considered as a suggestion for a future enhancement.

Thank you for posting to ask about this!

**Comment by Jabe64** [comment]
You're welcome! Can't wait for phase 2! Thanks for adding this to suggestions.

**Comment by gmmedia** [comment]
I would love to see the Gutenberg editor in the category and tag description.

Any news about that?

**Comment by pwkip** [comment]
I mentioned this in slack: https://wordpress.slack.com/archives/C02QB2JS7/p1587993803341100
This issue will probably not be reopened because all templates, including category templates will eventually be made of blocks.

I'm not sure what this means for the description field, but I guess it will just become that: a description field. I assume we will be able to add more complex data-structures to categories trough the block editor.

**Comment by danyork** [comment]
I just want to chime in with the comments above to say that the lack of the ability to edit category pages (and tags) is one of the barriers holding us back from doing more with the block editor across our site. We use category archives pages extensively in the navigation and main design of our site. Currently have built them out using ACF with rows of text, images, etc. above the posts for the category (or tag). We've been doing more and more with the block editor and would like to use it on all of these category archive pages, too. (Versus rebuilding all the category archive pages as, say, regular "pages" with a category feed... and then doing redirections, etc.)

Per the comment above and the Slack discussion, I understand that eventually these archive pages will all be blocks... but I guess my question is - any thoughts on _when_ that might start to happen?

**Comment by MuhammedSwalihct** [comment]
Any update on this? Would be a cool feature to extend the ability to edit the category and tag pages with Gutenberg so that the webmasters could have a better archive than just a list of posts

**Comment by CreativeDive** [comment]
Please add a block included content area to the taxonomies, like your sidebar implementation. We can't wait :-) This is a must have for WordPress and to optimize taxonomy pages.

**Comment by Wohlfarth** [comment]
@designsimply I see you closed this issue some longer time ago and you mentioned to place it in the Ideas project for future enhancement. 

Is there any update on this feature? Is this issue being worked/discussed anywhere?

Using Gutenberg to edit categories/taxonomies seems an important feature to me.

Thank you for the kind feedback!

**Comment by LauGau** [comment]
I cannot wait neither !

**Comment by skorasaurus** [comment]
@Wohlfarth This is being tracked in https://github.com/WordPress/gutenberg/issues/17099

**Comment by blachawk** [comment]
Whats the latest on implementing this? Can't wait.

**Comment by skorasaurus** [comment]
> Whats the latest on implementing this? Can't wait.

@blachawk

It appears that Gutenberg developers aren't making this a priority and still needs to be designed from a technical standpoint.. :(

You can track its progress at https://github.com/WordPress/gutenberg/issues/17099 and subscribe to that issue to be notified of updates.
