### ISSUE TITLE
Blocks: Add cog to the side of block, as a shortcut to "advanced" inspector controls

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1251]
Mockup:

![screen shot 2017-06-19 at 10 41 56](https://user-images.githubusercontent.com/1204802/27276575-f13f2450-54db-11e7-8598-5f68985ca84f.png)

The cog there on the right will open the inspector when you click it. That is, if the sidebar is closed, it will open the sidebar. 

It should show up only when a block _has_ advanced inspector controls (see #1100). 

This button can also address an accessibility issue, see #1182. CC: @afercia

**Comment by afercia** [comment]
Interesting, yes this could help #1182. The tab order will be key, as the cog and delete button should be placed in the most logical order when tabbing. Of course, both buttons would need some aria-label to be properly labeled.

**Comment by aduth** [comment]
>The tab order will be key, as the cog and delete button should be placed in the most logical order when tabbing.

Do you have any thoughts on what the best tab order would be? It appears visually as though they would occur after the fields, but for consistency with the rest of the controls, I would think they should be part of the series with movers -> toolbar -> cog / delete.

**Comment by afercia** [comment]
Looking also at #130, yes I tend to think the cog and delete buttons should be part of the movers > toolbar, for consistency and also because it's "one place less" to look at. Not sure about the visual part. The mockup with the delete button within the toolbar makes the logical grouping match the visual grouping, see https://github.com/WordPress/gutenberg/issues/130#issuecomment-301434018 and I do like it, just my personal opinion.
On the other hand, separating the bin / trash can icon could maybe help avoiding unwanted destructive actions. Have you considered to ask users to confirm in some way (maybe using something more elegant than a JS confirm) the delete action? As @GaryJones noted on #130, when a block is gone... is gone, no chance of recovery.

**Comment by aduth** [comment]
>when a block is gone... is gone, no chance of recovery.

Not the intention, though undo / redo is admittedly very basic and incomplete at the moment (partially tracked at #627).

**Comment by afercia** [comment]
Good to know! 👍

**Comment by afercia** [comment]
See #1372 that is going to add a "cog" button, however that's used just to open the sidebar.

**Comment by mtias** [comment]
This is done.
