### ISSUE TITLE
Creating a clear difference between types of blocks

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#12515]
We need a clear distinction between various kinds of blocks:
The standard blocks used for the layout. (All the regular blocks we have today.)
Reusable Blocks <-> Global Blocks (we need to define each kind of block type)
Template Blocks
Inner Blocks

Creating a visual que for each kind of block.

**A standard paragraph block.** On hover shows the label (Paragraph). Label should also be clickable. A thin blue outline.

![screen shot 2018-12-02 at 11 26 33](https://user-images.githubusercontent.com/5323259/49338692-554afa00-f625-11e8-9117-f789bb44001c.png)

**Inner Blocks**
A standard column block. On Hover shows the label Column -> Paragraph. Clicking Column label should then select the parent Column. Clicking Paragraph label should select the child paragraph block.
A thin blue outline.

![screen shot 2018-12-02 at 11 29 31](https://user-images.githubusercontent.com/5323259/49338703-904d2d80-f625-11e8-935b-e793df1cb713.png)

New suggestion:
On Hover shows the inner selected block and the parent block, so the user gets an overview of the connection between inner and outer blocks.

I have added some transparency to the parent block. I have also added a thicker outline around the child/inner block to show that it is being hovered over.
The label word Column and the inner block Paragraph should become clickable.

![inner-block-gutenberg](https://user-images.githubusercontent.com/5323259/49338766-d3f46700-f626-11e8-96bf-f17bf64abb24.jpg)

---

 **Reusable block**

![screen shot 2018-12-02 at 11 44 57](https://user-images.githubusercontent.com/5323259/49338868-837e0900-f628-11e8-894b-9fc5cba8f19f.png)

Adding a dash of green to the outline as well as showing the two columns:

![reusable-block-gutenberg](https://user-images.githubusercontent.com/5323259/49338870-9ee91400-f628-11e8-89ac-416b5dceb0bb.jpg)

Keeping a consistency between the various kinds of blocks.
By seeing the parent and child block within.
By adding some color to each kind of block type.
Making all block labels clickable.
Click a parent block, reusable block etc etc and see the default settings for it in the right sidebar.

Ideas for Global Block Settings
https://github.com/WordPress/gutenberg/issues/1224

**Comment by paaljoachim** [comment]
Here is an issue filed on trac that is similar to what I mention: https://core.trac.wordpress.org/ticket/45575

It is important that all blocks should have a clear border to define the space they are in.

**Comment by mario-neuhold** [comment]
I like the idea of different colors / border styles! 
And I would suggest to make a toggle option to show these borders permanently via the options panel, just like "Top Toolbar". Not sure if default on/off would be better, since it kinda interfers with the visual expectation of the live result. Thinking of something like this:
![image](https://user-images.githubusercontent.com/29606929/51386386-7e1a4680-1b22-11e9-9802-226589506b1a.png)

**Comment by mapk** [comment]
I believe the inner blocks are being explored in https://github.com/WordPress/gutenberg/pull/14961 and https://github.com/WordPress/gutenberg/pull/15537. With these changes, a lot of confusion should be resolved. 

I'm also not too keen on differentiating based solely on color because there could be a11y issues there.

What I do like about this issue is the concept of making the block labels clickable as in a breadcrumb system. Although the labels have changed design since this issue was created. In addition, with the advent of a new Document Outline, this too may prove to be unnecessary. 

I'm going to close this since it's being solved in a variety of ways in other PRs right now. Thanks @paaljoachim for the suggestions.
