### ISSUE TITLE
Is there possible to add custom control or trigger button to each block settings ?

### ISSUE THREAD

**Issue by sahidhossen** [WordPress/gutenberg#12513]
If I want to add extra settings button or control to the each custom block then is it possible ? 

If not then is there any way to add a trigger element for each custom / core block and get the trigger callback function (example- click) for show some extra options?

**Comment by designsimply** [comment]
You can use `BlockControls` to add buttons to a block toolbar or `InspectorControls` to add settings to a block sidebar.

See https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/block-tutorial/block-controls-toolbars-and-inspector/ and https://wordpress.org/gutenberg/handbook/designers-developers/developers/filters/block-filters/#editor-blockedit for details and examples about that. 

If you still need help at that point, please post a brief description or example of a setting you're trying to add, include code example (or pseudo code example) if you have one, and post it either to https://wordpress.org/support/forum/wp-advanced/ or https://wordpress.stackexchange.com/ because those are the best places to ask for help with custom code questions. Thank you!

**Comment by mehov** [comment]
For those coming from Google

Since the https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/block-tutorial/block-controls-toolbars-and-inspector/ link is dead, here's a close alternative: https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/block-controls-toolbar-and-sidebar/
