### ISSUE TITLE
The typing is very sluggish/slow

### ISSUE THREAD

**Issue by slung** [WordPress/gutenberg#12560]
**Describe the bug**
Typing text is extremely sluggish, almost unusable. I wait for about 5 - 10 seconds after I type something for the text to appear on the screen.

**To Reproduce**
1. Type something
2. Wait several seconds for the text to appear

**Expected behavior**
The text should appear as I type

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome v70.0.3538.110

**Comment by designsimply** [comment]
Thank you for reporting this. Can you tell me a bit more about your content? If you click the (i) in the top toolbar, how many words and blocks does it report? Are you using a lot of media or embeds? 

I'm asking to try to get a better idea of the problem because typing is not sluggish in my own testing so far but I would like to try to replicate the same situation you're seeing. If possible (if it's okay with you to post the contents of one of the posts you're having trouble with), if you can go to More > Copy All Content and paste the result either into a code block here or into a `pastebin` and provide the link then I could use that as a test case.

**Comment by designsimply** [comment]
WordPress 5.0.2 has been released with several performance updates. Please update to WordPress 5.0.2 and if you're still seeing the same problem, please re-open this issue and include as much detail about the problem you can.
