### ISSUE TITLE
Top toolbar hides permalink popup of title field

### ISSUE THREAD

**Issue by florianbrinkmann** [WordPress/gutenberg#12623]
**Describe the bug**

If the »Top Toolbar« option is enabled, the permalink popus appears under the toolbar and is partly hidden. I use Firefox 65.0a1 (2018-12-03) (64-Bit) on Windows 10.

**To Reproduce**
1. Open a post with Gutenberg.
2. Enable the »Top Toolbar« option.
3. Click into the post title field.

**Expected behavior**

The permalink popup should appear above the toolbar.

**Screenshots**

![top-toolbar-issue](https://user-images.githubusercontent.com/2310924/49538231-3bcadc00-f8cb-11e8-8184-90c8f167348b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 65.0a1 (2018-12-03) (64-Bit)

**Additional context**
- Gutenberg bundled in WordPress RC3.

**Comment by designsimply** [comment]
Closing as won't fix for now because the permalink is accessible in the document settings sidebar and because permalink will be removed from the title in the the future. See https://github.com/WordPress/gutenberg/issues/11398#issuecomment-440486817

Thank you for the report and including a screenshot!

**Comment by florianbrinkmann** [comment]
Okay, didn’t found that issue, thanks for the info!

**Comment by designsimply** [comment]
It was a bit hidden!
