### ISSUE TITLE
Gutenberg slows down my internal site 4x & not compatible with YoastSEO. Detailed report - help appreciated 

### ISSUE THREAD

**Issue by marcusblogger** [WordPress/gutenberg#12627]
Ok I am really struggling to find a path forward with my Gutenberg issues the past week. So going to be very thorough with this write-up to try to get much needed assistance. 

First off, I am using most updated Wordpress 4.9.8. I am also working out of Google Chrome. I go into Health Check Troubleshoot mode and the following happens:

- With no plugins, my long 2k+ word posts open right away no problems
**- I activate Gutenberg and the load time 4x's.** Posts that opened in 2 seconds now takes 8+ seconds to load with lag as you edit a post.
- **I then download the SEO plugin that is on millions of sites: YoastSEO and the posts now take 30+ seconds to open, effectively making my dashboard unusable** with incredibly slow load times and lags. 
- I then also tried Gutenberg with just All in One SEO, and the load times are less than it is with YoastSEO. So to use Gutenberg, I would then have to make big move from Yoast to another plugin? 

I have been looking into this issue for a week now and have tried this many times - same issues persisting so this is not a fluke. 

**So now I have to use Classic Editor - BUT since I created my first 20+ posts with Gutenberg, my formatting is now all off.** Spacing is no longer the same with many blocks now crammed into long paragraphs. 
And now with Gutenberg disabled, my internal links throughout all my posts do not show the same Gutenberg preview of course and don't even work period.
So...since Gutenberg is currently unusable due to loading issues, I have to be all in on Classic Editor now and go through all my old posts and fix the spacing formatting, fix the links, and make them workable for users with that very different editor. 
And then once Wordpress forces me back to Gutenberg hopefully when issues are resolved, I assume I will have to go through every post and essentially reverse everything back so that formatting is now good with Gutenberg again.
I of course do not want to have to do this if it can be avoided.
So I am hoping there must be another issue to troubleshoot as otherwise Gutenberg is not usable for anybody with long/normal length posts. 
Are there imminent updates to fix these major issues? 

Another thing I am noticing (I am not technical) is I was directed to see if there was any javascript issues. 

So when I got to one of my posts that loads very slow with Gutenberg, **I see 395 issues as shown in screenshot. I then get rid of Gutenberg with Troubleshoot mode and there are no issues showing in the Tools - Developer - JavaScript Console**
![Uploading Screen Shot 2018-12-05 at 2.39.12 PM.png…]()

Could there be a fix somewhere here?

So to recap, I am in a tough spot and hoping my non-technical self is just missing a simple fix. If not I either have to ditch the Gutenberg editor which I really liked so that my dashboard is usable (currently load times make it unusable) and then go through all my content to fix the formatting issues and link issues etc. And then go through again once Gutenberg is usable to reformat everything back.

1.  **Can you confirm that Gutenberg is not compatible with YoastSEO and when that issue may be resolved given the importance?** If not, what could be the reason for uniquely causing me issues. 

2. Can you confirm Gutenberg currently slows post load speed dramatically (especially for long posts full of blocks) relative to default Wordpress editor? If so, expected update/fix release date? If not, what could be the reason for uniquely causing me issues

**Any insights would be surely greatly appreciated.** I would pay to hop on the phone with somebody to fix these issues at this point. Cheers.

**Comment by designsimply** [comment]
First, thank you for reporting this issue!

> So when I got to one of my posts that loads very slow with Gutenberg, I see 395 issues as shown in screenshot.

I'm quite interested in seeing that screenshot but it looks like it didn't get linked properly somehow. Can you try uploading it again in a new comment? To do that, go to https://github.com/WordPress/gutenberg/issues/12627 while logged in to GitHub and drag an image into a comment reply area.

<blockquote>So now I have to use Classic Editor - BUT since I created my first 20+ posts with Gutenberg, my formatting is now all off. Spacing is no longer the same with many blocks now crammed into long paragraphs.</blockquote>

Are these drafts or published posts? If they are published posts, is there some reason you need to go back and edit them or is that a thing you feel you need to do for all your posts when you switch editors? (Theoretically, you should absolutely not have to do that.)

<blockquote>And now with Gutenberg disabled, my internal links throughout all my posts do not show the same Gutenberg preview of course and don't even work period.</blockquote>

Links added from one post to another using Gutenberg should still work normally if you switch back to the classic editor. I just tested this by creating a post with links to other posts on the same site using Gutenberg then deactivating Gutenberg and opening the post again. In that case, all of my test links still worked normally. Could you tell me a little more about how exactly you create an internal link or show me an example? It's possible I didn't test correctly if I'm not thinking the same way you are about internal links.

<blockquote>Can you confirm that Gutenberg is not compatible with YoastSEO and when that issue may be resolved given the importance? If not, what could be the reason for uniquely causing me issues.</blockquote>

It should be! Yoast SEO has been on top of Gutenberg compatibility from the start and have been making updates along the way. Sometimes a bug will surface though, and this could be one of those times. I will do some additional testing, but in the mean time, may I ask if you happened to test with Yoast SEO without Gutenberg and how the load times were affected for you?

<blockquote>Can you confirm Gutenberg currently slows post load speed dramatically (especially for long posts full of blocks) relative to default Wordpress editor? If so, expected update/fix release date?</blockquote>

There is an open issue for this at #11782 which I see you commented on at https://github.com/WordPress/gutenberg/issues/11782#issuecomment-444655971 and that you also wrote a similar issue a few days ago at #12508. For this case, I think the best course of action will be to document in just one issue and then wait for a reply. Because of that, and for this case, I would like to close this issue and continue the discussion at #12508. I did ask some questions above though, and I want to note that you can still reply here even after this issue is closed or you can provide the answers at #12508.

I also will try to think of any additional information I can ask for in #12508 which might be able to move this issue forward for you.

Aside: I see that you mentioned you are using WordPress 4.9.8. I also wanted to note for reference that you said at https://github.com/WordPress/gutenberg/issues/12508#issuecomment-443556415 that you are using Gutenberg 4.6.1 (I am noting this because it's helpful to note the version number as we go for reports like this one).

**Comment by marcusblogger** [comment]
> First, thank you for reporting this issue!
> 
> > So when I got to one of my posts that loads very slow with Gutenberg, I see 395 issues as shown in screenshot.
> 
> I'm quite interested in seeing that screenshot but it looks like it didn't get linked properly somehow. Can you try uploading it again in a new comment? To do that, go to #12627 while logged in to GitHub and drag an image into a comment reply area.
> Repasting here: did it work this time?
![screen shot 2018-12-05 at 2 39 12 pm](https://user-images.githubusercontent.com/45521788/49564173-79cdfd00-f8d7-11e8-84f2-5ae36f067ae5.png)


> > So now I have to use Classic Editor - BUT since I created my first 20+ posts with Gutenberg, my formatting is now all off. Spacing is no longer the same with many blocks now crammed into long paragraphs.
> 
> Are these drafts or published posts? If they are published posts, is there some reason you need to go back and edit them or is that a thing you feel you need to do for all your posts when you switch editors? (Theoretically, you should absolutely not have to do that.)

>These are for published posts. Which I am going back into to edit and fix (this is a new site - not material traffic is generated yet, so I publish knowing I will go back and fix. But switching editors and just tweaking a few lines I noticed that the spacing is off throughout when I go to my site. 

> 
> > And now with Gutenberg disabled, my internal links throughout all my posts do not show the same Gutenberg preview of course and don't even work period.
> 
> Links added from one post to another using Gutenberg should still work normally if you switch back to the classic editor. I just tested this by creating a post with links to other posts on the same site using Gutenberg then deactivating Gutenberg and opening the post again. In that case, all of my test links still worked normally. Could you tell me a little more about how exactly you create an internal link or show me an example? It's possible I didn't test correctly if I'm not thinking the same way you are about internal links.


> I create internal links with the embed option on Gutenberg and paste in the URL. Now I go to my posts after switching from Gutenberg to Classic Editor and they do not hyperlink. Ex: see my post here https://nomadicsportsfan.com/staples-center-lakers-game-trip-ultimate-guide/ 
I link to my LA Coliseum post towards the beginning of the post and it just shows the URL with no ability to click. 


> > Can you confirm that Gutenberg is not compatible with YoastSEO and when that issue may be resolved given the importance? If not, what could be the reason for uniquely causing me issues.
> 
> It should be! Yoast SEO has been on top of Gutenberg compatibility from the start and have been making updates along the way. Sometimes a bug will surface though, and this could be one of those times. I will do some additional testing, but in the mean time, may I ask if you happened to test with Yoast SEO without Gutenberg and how the load times were affected for you?
> Yes, as detailed the load time for my LA Coliseum post was 8 seconds with just Gutenberg and then jumped to 30+ seconds with YoastSEO installed. Could there be an issue with how I configured settings (I followed detail guide to set it up so doubt that could be it)?
> > Can you confirm Gutenberg currently slows post load speed dramatically (especially for long posts full of blocks) relative to default Wordpress editor? If so, expected update/fix release date?
> 
> There is an open issue for this at #11782 which I see you commented on at [#11782 (comment)](https://github.com/WordPress/gutenberg/issues/11782#issuecomment-444655971) and that you also wrote a similar issue a few days ago at #12508. For this case, I think the best course of action will be to document in just one issue and then wait for a reply. Because of that, and for this case, I would like to close this issue and continue the discussion at #12508. I did ask some questions above though, and I want to note that you can still reply here even after this issue is closed or you can provide the answers at #12508.
> I am fine waiting if I had any insight on an eta for fixes. I need to decide whether to deal with some growing pains as it improves in near future which is fine or if this will continue to be work in progress project for the next year for example. 
> I also will try to think of any additional information I can ask for in #12508 which might be able to move this issue forward for you.
> Thanks for all your effort here. I will take this to that thread now as well. Thanks
> Aside: I see that you mentioned you are using WordPress 4.9.8. I also wanted to note for reference that you said at [#12508 (comment)](https://github.com/WordPress/gutenberg/issues/12508#issuecomment-443556415) that you are using Gutenberg 4.6.1 (I am noting this because it's helpful to note the version number as we go for reports like this one).
