### ISSUE TITLE
NUX: Consider making "close" button hide the current guide instead of disabling tips completely

### ISSUE THREAD

**Issue by TimothyBJacobs** [WordPress/gutenberg#12632]
Right now, as far as I can tell, there is only one guide in Gutenberg. However, when using the NUX package with multiple guides, it'd be more helpful if clicking the close button only dismissed that guide instead of completely disabling tips. 

Each guide can be associated with completely different parts of an application and the user saying "I know this, don't bother me" about one component of the application shouldn't be treated as, "I'm an expert on everything in this app, no need to tell me about it ever". This would particularly hold true when adding new features to an application that you want to show guides for.

**Comment by karmatosed** [comment]
In this case, it's not something I feel needs design feedback as much as needs a decision on the development level.

**Comment by sarahmonster** [comment]
This warrants design discussion because it changes the way that users will interact with tips. 

## The problem

Tips belong to a "guide". By default, Gutenberg ships with only one guide, but plugin developers can add their own guides. 

<img width="516" alt="screenshot 2019-02-25 17 42 48" src="https://user-images.githubusercontent.com/376315/53357155-1e833800-3925-11e9-9be2-a6015840fcea.png">

Tapping the "x" does the following:
- closes the current tip
- disables the "show tips" setting (no more tips will be shown)

As a result, closing out _one_ tip also disables all other tips, including tips that are added by third-party plugins. 

Basically, there are three possibilities for the "x" button:
1. Close the _current tip only_.
2. Close the current tip _and all other tips in this guide_.
3. Close the current tips _and all other tips_.

Gutenberg current uses #3, but this is suggesting to instead use #2. From a user experience point of view, that could be a bit confusing since there's no way of identifying what guide a tip is part of, and I've already selected a "disable all tips" option.

## Potential solutions

We'll want to be careful to ensure that a solution here follows these principles:
1. Tips are used to provide contextual, helpful information when users need them most.
2. As a user, I can dismiss tips easily and quickly if I never want to see them.

It's important that we balance these two user needs here in order to provide the best experience possible. We don't want people to be annoyed by tips always popping up when they're not helpful, but we also want to help users learn this new interface (including plugins!)

I'm thinking the most user-friendly approach might be to expose some more information to users, so they can better control what tips are shown. Here are a few ideas:

1. Tapping the "x" closes the current tip _only_. A different control would be used to dismiss _all_ tips.

<img width="493" alt="screenshot 2019-02-25 17 58 37" src="https://user-images.githubusercontent.com/376315/53358514-7f603f80-3928-11e9-976b-5785a4139aee.png">

2. Tapping "x" only disables tips in the current guide. Tips that are part of another guide will still appear. 

For this to work, we'd want to expose a title of the current guide, so that users can distinguish between the different tips without getting confused. We'd also want to change the tooltip text to read something like "Disable all tips in this guide" rather than "Disable all tips".

<img width="483" alt="screenshot 2019-02-25 18 10 45" src="https://user-images.githubusercontent.com/376315/53358604-b46c9200-3928-11e9-9cb9-8c43c17eebb0.png">


3. A combination of the above:

<img width="480" alt="screenshot 2019-02-25 17 59 24" src="https://user-images.githubusercontent.com/376315/53358532-8c7d2e80-3928-11e9-8785-cc53475393f8.png">

We could even go a step further and add finer-grained controls here:

<img width="465" alt="screenshot 2019-02-25 18 20 08" src="https://user-images.githubusercontent.com/376315/53359134-fe09ac80-3929-11e9-8bad-a49aabf52bd9.png">

This would allow users to select 1, 2, or 3, depending on their preferences, but I suspect it's presenting too many choices without enough payoff.

**Comment by karmatosed** [comment]
Adding back in design discussion label based on feedback,  thanks.

**Comment by mapk** [comment]
Excellent explorations Sarah! I'm gravitating toward Proposed Solution Number 2. I think closing _all tips in all guides_ is a bit extreme when, as a user, I'm really just trying to get out of this set of tips. At this point, I'm not even aware that there may be other guides that I might be more interested in. 

Closing all tips for all guides seems like more of a power user action. I can see this as a setting in the Options panel.

Number 2 works in simplicity. There's a `X` to simply close these tips (from this guide) or a link to continue through them. It's a good balance.

**Comment by enriquesanchez** [comment]
There's discussion on #16315 about redesigning Tips and a PR (#18041) already in the works.

**Comment by richtabor** [comment]
> There's discussion on #16315 about redesigning Tips and a PR (#18041) already in the works.

Also in that discussion, we reviewed how perhaps only sibling tips (those relative to a particular series of tips) should be closed. ([link](https://wordpress.slack.com/archives/C02S78ZAL/p1574184104163300))

**Comment by noisysocks** [comment]
Closing this out as tips have been removed in #18041 and `DotTip` has been deprecated in #18981.
