### ISSUE TITLE
Block picker stays visible after choosing inline-image

### ISSUE THREAD

**Issue by simison** [WordPress/gutenberg#12645]
Block picker stays visible after choosing inline-image block.

**To Reproduce**
1. Insert inline image block to a post
2. Observe how block picker stays over the media selector:
<img width="700" alt="image" src="https://user-images.githubusercontent.com/87168/49582840-eb9d5980-f95e-11e8-940c-d407d0467be8.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version 63

Latest Gutenberg `master`, WordPress 4.9, TwentyNineteen theme.

**Comment by jorgefilipecosta** [comment]
Hi, @simison thank you for reporting the issue, I'm not able to reproduce the issue. What plugins do you installed when the problem happens?

**Comment by kcalkmc** [comment]
Tested using Windows 7, WP 5.0 , Chrome and Firefox, multiple tests on each.
Unable to reproduce.

**Comment by designsimply** [comment]
This turned out to be a bit tricky. I tested using WordPress 5.0.2 and no active plugins and found that the block library modal overlaps the media modal if there is already at least one inline image present and if you use an inserter between or next to blocks and not the inserter in the top toolbar.

**Video:** [1m18s](https://cloudup.com/cA1NoO3MIa8)
<sup>Seen at https://testingallthetime.com/wp-admin/post.php?post=255&action=edit running WordPress 5.0.2 and no active plugins using Firefox 63.0.3 on macOS 10.13.6.</sup>

**Comment by ChemicalSailor** [comment]
I have this issue on a page with no other inline images. You have to use the block inserter between blocks or to the left of an empty block.

I tested on a new page with no other blocks and it works fine. On a new page with one of these blocks added the issue can be seen (not an exhaustive list but covers the most common)
- image
- video
- file
- gallery
- audio
- table
- latest posts
- archives
- categories
- embed

I didn't make any inputs to the blocks, this is 'as inserted'

Additionally, the bug can be seen when a combination of blocks are present, e.g pullquote and list, pullquote and html. I wasn't going to sit and test every possible combination.

**Comment by gziolo** [comment]
I don't think it is still an issue since `Inline Images` are no longer included in the Inserter. They were moved to the block toolbar.

![Screen Shot 2019-10-17 at 13 18 29](https://user-images.githubusercontent.com/699132/67004449-a13d4b00-f0e0-11e9-86ec-63d1a290e84d.png)

Thank you for the original report.
