### ISSUE TITLE
Multi-column layout: elements are shifted rightwards from the center

### ISSUE THREAD

**Issue by idea--list** [WordPress/gutenberg#12640]
**Describe the bug**
Multi-column layout shifted rightwards.

**To Reproduce**
1. You set up a multi-column layout and put text or images in the columns.
2. Update the page and check it in the front-end
3. Notice all the content inside the multi-column area shifted significantly to the right side

**Expected behavior**
The layout should be centered exactly

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser chrome v 70.0.3538.110
 

**Fix**
- Open the file gutenberg/build/block-library/style.css find the following part in it:
@media (min-width:600px){.wp-block-column:nth-child(odd){margin-right:32px}
	.wp-block-column:not(:first-child),.wp-block-column:nth-child(2n){margin-left:32px}
	.wp-block-column:not(:last-child){margin-right:32px}}

- To solve the display issue, add these lines to the styles.css of your active theme: 
@media (min-width:600px){.wp-block-column:nth-child(odd){margin-right:0px}
	.wp-block-column:not(:first-child),.wp-block-column:nth-child(2n){margin-left:0px}
	.wp-block-column:not(:last-child){margin-right:0px}}

After that the content is centered exactly just as expected

Should be addressed as fast as possible.

**Comment by m-e-h** [comment]
Thinking this is the same issue: https://github.com/WordPress/gutenberg/pull/12199

**Comment by designsimply** [comment]
I want to add a screenshot for clarity. I followed the steps provided and here is how a columns block with three columns in the editor and the front end from my test:

<img width="1280" alt="screen shot 2018-12-06 at 4 29 49 pm" src="https://user-images.githubusercontent.com/1119271/49618020-3aa1b980-f974-11e8-8313-f66b5e74a200.png">

<img width="1280" alt="screen shot 2018-12-06 at 4 29 59 pm" src="https://user-images.githubusercontent.com/1119271/49618018-3a092300-f974-11e8-9ed5-4f997f8ff073.png">

<sup>Tested with WordPress 5.0 and the Twenty Seventeen 1.8.</sup>

I'm not sure this illustrates the problem though, because I don't see a significant shift. Can you let me know if I'm not looking in the right place? Also, can you note the theme and theme version number you are testing with?

Note: when you said "set up a multi-column layout" I assumed you meant a columns block. I wasn't 100% sure that's what you meant though, so let me know if that's not right!

**Comment by designsimply** [comment]
My apologies. I think this is a better screenshot:

<img width="1280" alt="screen shot 2018-12-06 at 4 48 43 pm" src="https://user-images.githubusercontent.com/1119271/49618760-f2d06180-f976-11e8-9e3c-e01f25b509f2.png">
<sup>Tested with WordPress 5.0 and the Twenty Seventeen 1.8.</sup>

I still don't see it as a significant shift though, and so I still want to check in about that.

**Comment by idea--list** [comment]
Well if you try it on a REAL design then you get:
![image](https://user-images.githubusercontent.com/5784071/49628318-cacb1780-f9e3-11e8-9e5f-d5ed8376765d.png)

On a narrower screen it becomes even worse:
![image](https://user-images.githubusercontent.com/5784071/49628399-33b28f80-f9e4-11e8-84b4-9942096406eb.png)

After applying the proposed fix:
![image](https://user-images.githubusercontent.com/5784071/49628512-c5ba9800-f9e4-11e8-900b-4192a1e440dc.png)

![image](https://user-images.githubusercontent.com/5784071/49628487-9d329e00-f9e4-11e8-9b25-773ef42ddd76.png)

Hope you are convinced now as without the fix GB just ruins real world designs.
Please note that even m-e-h has reported the same issue.

**Comment by idea--list** [comment]
Hmm strange... i copied the full width screenshots first and then the narrower ones but system mixed them up.

**Comment by idea--list** [comment]
Oh my GOSH!!

Here is the next bug with a real design. I have a "Columns" block to which i added a custom CSS class (in which i set a background-image). Inside that "Columns" block i have some text, etc. Below that there is a section (actually a "Section" block from the Ultimate Addons for Gutenberg plugin as with GB in itself it is simply not possible to expand just the background-color to full width without also expanding the content which is another issue IMHO). To the above mentioned section i also added a CSS class wich defines a semitransparent background-color.

You can clearly see the next bug in the screenshot:
![image](https://user-images.githubusercontent.com/5784071/49662319-b9b5f100-fa4b-11e8-8bca-041ed51b8bcc.png)

Took me some time to figure it out, but the cause lies once again in gutenberg/build/block-library/style.css file:
.wp-block-column{flex:1;flex-basis:100%;**margin-bottom:1em**;min-width:0;overflow-wrap:break-word;word-break:break-word}

After adding .wp-block-column{margin-bottom:0em}; to the theme's css file the isssue is resolved, the bg-image does not overflow the semi-transparent bg-color.

For god's sake, please remove any padding or margin offsets from the .wp-block-column class that you hard-coded in GB's css file. It is a really bad idea and not easy to find the cause!

Also found another one i still did not mention:
.wp-block-text-columns .wp-block-column{**margin:0 16px**;padding:0}

**Comment by idea--list** [comment]
@designsimply 
You just can't be serious with that! I am developing a theme for a client on WPRig v1.4.
How do you think it would make me sense to change the theme?
I just stop wasting my time to debug this crappy editor. Bye.

**Comment by designsimply** [comment]
@idea--list apologies for not being more clear. I was noting that I was using the default theme and didn't realize at first that they had made an adjustment in the theme itself. 

Work is ongoing in https://github.com/WordPress/gutenberg/pull/12199 and I found the issue was also reported at https://github.com/WordPress/gutenberg/issues/13035 and I would like to close this issue in favor of that one.
