### ISSUE TITLE
Button style suggestion: (rounded|squared)x(outlined|filled)

### ISSUE THREAD

**Issue by cloudinstone** [WordPress/gutenberg#12699]
Now, the button block has 3 styles, `rounded`, `squared` and `outlined`. 

Shouldn’t it be `(rounded|squared)x(outlined|filled)` ?

**Comment by kcalkmc** [comment]
I tested with WP 5.0. Screen confirms what you describe. 
![wp-issue-12699](https://user-images.githubusercontent.com/9540372/49700381-99b23900-fbd5-11e8-870b-9758d8340751.png)

It would be great to get designer feedback on this.

**Comment by benhuson** [comment]
From a design perspective I find it odd that "rounded" and "squared" have both made it in as default styling options for the button block. Generally I would expect you would want a consistent button style across a site, so that should be the job of a theme or site wide customiser setting, rather than having to style each button block individually? I guess it's in there now though and will be staying? It just means themes will have to unregister one of the styles if they don't need it.

"Outlined" and "filled make sense as styling options to differentiate between an important primary and a secondary button.

**Comment by kjellr** [comment]
This ticket was discussed in [this week's Design chat](https://wordpress.slack.com/archives/C02S78ZAL/p1556036878246800). 

The general consensus was that yes, the current options are weird. 😄 

Historically, most themes (and websites in general) do not use both rounded and squared buttons. Removing one of those options would make a lot of sense here. Then, the options would be: 

- `Default` (Filled. Would be either rounded or squared, depending on the theme's preference)
- `Outlined` (Would be either rounded or squared, depending on the theme's preference)

If themes wanted to implement additional options, they could include them as custom block styles.

**Comment by enriquesanchez** [comment]
>Shouldn’t it be (rounded|squared)x(outlined|filled) ?

Wanted to plus one this idea. I recently came across this same problem where I wasn't able to both style a button squared and outlined and thought it was odd.

**Comment by youknowriad** [comment]
It looks like #16481 is trying to address the same issue. Let's consolidate there.
