### ISSUE TITLE
Bulk Convert From Classic To Block

### ISSUE THREAD

**Issue by AngoraSpace** [WordPress/gutenberg#12694]
Dear All 

I have about 600 more posts that I created on classic editor. I tried to convert one of them to block mode, the content is fine, except some of minor code and layout.

I want my current post and my future post has same code and layout. So, I need to bulk convert all of them from classic mode to block mode. Because it’s hard enough for me if I have to convert it one by one. How to fix it?

Regards

**Comment by designsimply** [comment]
You mentioned in your first paragraph that converted content is fine except some minor code and layout. May I first ask about those differences? I am trying to understand if converting old content is really necessary or if it's advisable to tell you that the old content should not need to be converted.

**Comment by GlennMartin1** [comment]
@angoraspace

There is not a bulk way to convert all pages/posts. 

My 100s off pages had tons of shortcodes to produce the layout I needed. Layout shortcodes (like, for columns) will never convert into Gutenberg columns. So, in my case, bulk convert would not have helped.

I manually rebuilt each page/post. That's not a small matter, but after months I'm 90% done. I'm almost ready to ditch my shortcode plugins. 

A bulk convert probably would not be smart (even if it would be a feature), because you would want to review each page after conversion one at a time, anyway.

**Comment by AngoraSpace** [comment]
The difference about my previous posts (that created on classic editor) with my future posts (that created on gutenberg) is about embed, short code, alignment, etc. 

If I don't convert my previous posts to gutenberg, then my future posts layout will be different with my previous posts. And that will take impact to my sharing button, related posts, etc, below my content.

**Comment by designsimply** [comment]
This is exactly the feedback I wanted to document:

<blockquote>If I don't convert my previous posts to gutenberg, then my future posts layout will be different with my previous posts. And that will take impact to my sharing button, related posts, etc, below my content.</blockquote>

I am going to close this issue because, as @GlennMartin1 has noted, a bulk "Convert to Blocks" option is not available. I will also add this issue to the Ideas project board in this repository for future consideration and it does help to have the reasons behind the request documented so thank you very much for the conversation!

I would also like to mention that including a specific example use case including screenshots and noting what theme you are using would be very good to document for future discussion. If that is something you'd like to submit, please do add a comment with the details.
