### ISSUE TITLE
Latest Posts block date change position when we add extra class.

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/gutenberg#12700]
**Describe the bug**
When anyone add an extra class in Additional CSS Class date position change in Latest Posts block.

- WordPress 5.0
- Twenty Nineteen 1.0

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a Latest Posts block.
2. Add an extra class in Additional CSS Class box
3. See error

**Expected behavior**
Do not change data position in editor.

**Screenshots**

![latest-post-issue](https://user-images.githubusercontent.com/10103365/49684732-b3804d00-fafd-11e8-9c01-26ec04191110.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04 LTS
 - Browser Google Chrome
 - Version 69.0.3497.81 (64-bit)

**Additional context**
- When we add an extra class that class also place in <time> tage class then needs to remove then it will fix above issue.

**Comment by swissspidy** [comment]
By default the class of the `<time>` element is `wp-block-latest-posts__post-date`. That's the class that's styled in the CSS.

However. if I add a custom class `foo`, the class will be `wp-block-latest-posts foo__post-date`. That's because the parent `<ul>` class is changed to `wp-block-latest-posts foo has-dates` and it's just copied for `<time>`.

I don't think the class of the `<time>` should be changed when adding a custom class, because the class is already added to the parent `<ul>`.
