### ISSUE TITLE
Option to add all toolbars of nested blocks to top of innerBlocks container

### ISSUE THREAD

**Issue by virgiliud** [WordPress/gutenberg#12779]
**Is your feature request related to a problem? Please describe.**
By all toolbars I mean one at a time depending which block is being edited. This feature will present a better user experience for blocks created with the innerBlocks component, and intended to feel as a single block.

**Describe the solution you'd like**
An option to show the toolbars of all nested blocks on top of the innerBlocks container. This will be a great solution for creating a single block feel by nesting blocks.
 
For example if building a testimonial block (with an image, heading, and paragraph) it makes sense to use core blocks in the innerBocks component rather than rewrite the code for images, headings, paragraphs, etc. This can be done but the toolbars appear in each nested block, overlapping content. By adding/toggling the toolbar of all nested blocks on top of the innerBlocks container you get the feel of a single block and looks cleaner.

Below is an example of a block I created using the innerBlocks component. It uses the core heading, paragraph, and button block. It would look better if the toolbar of any block I'm editing appears in the top of the parent block/innerBlocks component, rather than overlapping content and showing the same toolbar icons, in different positions.

![screen shot 2018-12-11 at 2 14 10 am](https://user-images.githubusercontent.com/3076742/49769843-86dd5880-fcea-11e8-8cd5-5701e12a0af6.png)

**Comment by kjellr** [comment]
> For example if building a testimonial block (with an image, heading, and paragraph) it makes sense to use core blocks in the innerBocks component rather than rewrite the code for images, headings, paragraphs, etc. This can be done but the toolbars appear in each nested block, overlapping content. By adding/toggling the toolbar of all nested blocks on top of the innerBlocks container you get the feel of a single block and looks cleaner.

The core of this issue seems to be the unclear relationship between parent and child blocks. As it stands now, parent blocks and child blocks seem pretty separate — the boundaries of each one are somewhat mysterious, and when you're working inside of a child block, you aren't really aware that you're inside of a parent block. By bringing the toolbars of nested block into the parent block, it sounds like you're trying to make the child block seem like it's part of a cohesive parent block.

There's some excellent exploration going on in https://github.com/WordPress/gutenberg/issues/9628 that I think goes about this solving this issue a different way:

Two things specifically: 

1. [Showing the structure of nested blocks](https://github.com/WordPress/gutenberg/issues/9628#issuecomment-468381291) when you have either a parent or child selected.
2. [Adding some temporary additional padding](
https://github.com/WordPress/gutenberg/issues/9628#issuecomment-456811415) when working on a parent/child block. This not only improves the ability to select other child blocks, but it also helps add a little extra space to prevent overlap of the toolbar + content, as you noted above.

Since the general issues here overlap with those in that ticket, I'm going to close this issue for now. Feel free to either chime in there with any ideas, or let me know if I misunderstood the issue you're trying to solve for above. 

Thank you!
