### ISSUE TITLE
Footnote Anchoring

### ISSUE THREAD

**Issue by mosesneelam** [WordPress/gutenberg#12784]
**Describe the bug**
In the classic editor, when copying a document that has footnotes from Microsoft word, it was simple to paste, as the classic editor would automatically anchor to the respective foot note (I.e., when clicking foot note 1, the page would automatically take you to foot note 1 and vice versa), In the Gutenberg tool, this does not happen automatically. Instead, you would have to go through each footnote individually and anchor it. Why is this? It makes it tedious when you have 100+ footnotes. It would be helpful if this was fixed.

**Comment by youknowriad** [comment]
Can you share an example document here? This would help us track and fix the issue. Thanks.

**Comment by mosesneelam** [comment]
I am unable to upload a document? An example of an article with footnotes on my website is the following: https://truthinmydays.com/is-the-byzantine-text-the-result-of-a-long-process-of-development-and-standardization-an-examination-of-klaus-wachtels-text-critical-model/#Footnotes

Thanks,
Please let me know if you need me to upload a document. If so, how would I go about doing it?

**Comment by youknowriad** [comment]
sorry for the late response, yes it would be good if you could upload the document somewhere. You can upload directly here in Github, otherwise, feel free to upload to any sharing service (example cloudup.com) and paste the link here.

**Comment by youknowriad** [comment]
Closing, let's reopen if we have more details on how to reproduce this.

**Comment by juanruitina** [comment]
Hi there, I'm having the very same issue. Here's the info I've collected.

**Describe the bug**
Whenever pasting a text with footnotes from a Word file (e.g. desktop Word on Windows) into the block editor, both the links to the footnotes and the footnotes themselves show up, but the links pointing to each other just don't work.

**To reproduce**
Paste text with footnotes from a Word document like this: [Test footnotes.docx](https://github.com/WordPress/gutenberg/files/5679013/Test.footnotes.docx) into the block editor.

**Expected behavior**
Links to footnotes and footnotes themselves should link to each other. This used to work with the old editor, and in fact it still works when pasting in a "classic block". I understand both are still TinyMCE.

By looking at the code, it seems that **neither the links to the footnotes nor the footnotes have the "name" attribute** that TinyMCE seems to use for making the anchor links work:

```html
<!-- wp:heading -->
<h2>Regular blocks</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>This test has a couple<a href="#_ftn1">[1]</a> of footnotes<a href="#_ftn2">[2]</a>.</p>
<!-- /wp:paragraph -->

<!-- wp:separator -->
<hr class="wp-block-separator"/>
<!-- /wp:separator -->

<!-- wp:paragraph -->
<p><a href="#_ftnref1">[1]</a> This is footnote 1.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><a href="#_ftnref2">[2]</a> This is footnote 2.</p>
<!-- /wp:paragraph -->

<!-- wp:heading -->
<h2>Classic block</h2>
<!-- /wp:heading -->

<p>This test has a couple<a href="#_ftn1" name="_ftnref1">[1]</a> of footnotes<a href="#_ftn2" name="_ftnref2">[2]</a>.</p>
<p><a href="#_ftnref1" name="_ftn1">[1]</a> This is footnote 1.</p>
<p><a href="#_ftnref2" name="_ftn2">[2]</a> This is footnote 2.</p>
```

![Footnotes capture](https://user-images.githubusercontent.com/1409729/101901786-dc86bd00-3bb1-11eb-98e8-c0ab708c5bf8.PNG)

**Editor version (please complete the following information):**
- WordPress version: 5.6 and 5.5.3, was an issue in previous versions as well
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 83

It's interesting how pasting footnotes *seems* to work at first, but then it doesn't. I understand this need might be a bit niche, but organisations like mine publish entries with dozens of footnotes regularly. We just migrated our website to WordPress and this makes adoption a bit more difficult. If someone could have a look, that would be much appreciated.
