### ISSUE TITLE
Not able to underline header block font

### ISSUE THREAD

**Issue by willstocks-tech** [WordPress/gutenberg#12814]
**Describe the bug**
I'm creating a post at the moment and I've put a H2 Heading Block in the post content. I can make it bold and italic, but when I try to underline:
a) There's no option against the block
b) cmd + u/ctrl + u doesn't do anything either

**To Reproduce**
1. Create a new Gutenberg post in WP 5.0
2. Add a H2 Heading block
3. Type in a heading... "This is a heading block" as an example
4. Apply bold + attempt to apply an underline to the font

**Expected behavior**
I expect to be able to apply the most basic of styles to my headers? I have **B**, _I_ and ~strikethrough~ as an option, why not underline?

**Screenshots**
To be captured!

**Desktop (please complete the following information):**
 - OS: MacOS + Windows 10
 - Browser: Chrome + Safari, Chrome

**Comment by swissspidy** [comment]
I suspect that this is because adding underlines is something that should be added by the theme as it's such a rarely used tool. From an accessibility perspective exposing such an formatting option would be very bad as it can be easily confused with an actual hyperlink.

So this is probably more plugin territory than anything else. Plugins like https://wordpress.org/plugins/advanced-rich-text-tools/ already add more things to the formatting toolbar, so one could add an underline button to that as well.

**Comment by willstocks-tech** [comment]
Ahh, OK no worries - I'll get a text-decoration: underline applied to my H2's as I always use it! 

I don't know I personally agree with: "From an accessibility perspective exposing such an formatting option would be very bad as it can be easily confused with an actual hyperlink." as I'm sure 99% of people are familiar with the underlined U for being underline and a chain/link icon for hyperlinks. It's the first time I've personally _not_ seen underline in a WYSIWYG editor but hey ho!

I'll tweak my theme a little :) - thanks @swissspidy

**Comment by swissspidy** [comment]
I was referring to confusion on the front end :-)

Closing now since this approach works for you.
