### ISSUE TITLE
Media & Text Block Not allowing edit image size

### ISSUE THREAD

**Issue by flexerd** [WordPress/gutenberg#12833]
**Describe the bug**
After adding the image block width cannot be changed; If attempt is made to drag image side width, it becomes 100% no further editing is available. Text side seems to overlap on drag-bar

**To Reproduce**
1. Add Media with Text Block
2. Add Image
3. Try to change width of image side

**Expected behavior**
Expecting to be able to change image width (Worked in Gutenberg 4.7

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Chrome
 - 71.0.3578.98

**Additional context**
Wordpress 5.0.1 Gutenberg 4.7 disabled
No Console JavaScript Errors

**Comment by designsimply** [comment]
Tested and confirmed with WordPress 5.0.1 with no active plugins using Chrome 70.0.3538.110 on macOS 10.13.6. @jorgefilipecosta, this appears to be a regression of #12600 but is only happening when the plugin is not in use. If you test with WP 5.0.1 + Gutenberg 4.7.0 it works normally.

![12833](https://user-images.githubusercontent.com/1119271/49947630-f00dc900-feae-11e8-849e-a5359cf5cb5d.gif)

**Comment by jorgefilipecosta** [comment]
This issue will get solved as soon as core ticket https://core.trac.wordpress.org/ticket/45442 is shipped (5.0.2 probably).

**Comment by paaljoachim** [comment]
NB! Bug on Ipad.
Image goes into full width on iPad with text below.

**Comment by designsimply** [comment]
> Image goes into full width on iPad in Safari with text below.

@paaljoachim I tested adding a Media & Text block with WordPress 5.0.3 and no active plugins from an iPad mini iOS 12.1.1 Safari and found that I was able to both insert an image into a Media & Text block at a normal size and also resize it by using the drag handles.

General triage notes: it seems like you have posted into this closed issue because you think there may have been a regression for the same case or that it was never working for older versions of iOS on iPads, however, because the issue was closed several weeks ago it is not the best place to report an issue unless you think it is minor and are just leaving a note for reference. It can be a tricky balance though to know whether to open a new issue or not! In this case, because the issue is old enough and because I have done a quick test with a modern version of iOS and did not find the bug so far in testing, if you think the problem is worth re-checking from older versions of iOS would you mind opening a new issue and please also make sure to include a quick list of steps for testing (you could copy from the issue above), your iOS/Safari versions (as you have noted here), and also your WordPress version and mention whether or not you are testing with the Gutenberg plugin active and it's version number if you are? Because you mentioned a CSS workaround, it may also be worth noting your theme and theme version number in case it is related. Thank you!
