### ISSUE TITLE
Yoast SEO not working after Gutenberg appear

### ISSUE THREAD

**Issue by akolatronic93** [WordPress/gutenberg#12851]
**Describe the bug**
After Gutenberg appeared, I am not getting any advising from the Yoast SEO plugin. Not getting information about prominent words, not getting information about related links. It looks like it isn't recgnizing text as such because it displays a message that says "The text contains 0 words" even after I insert several blocks. I am not getting any SEO score, even if the keywords are the same as the title of the post.

**Comment by designsimply** [comment]
Please update to the latest versions of WordPress and Yoast SEO (which are 5.0.2 and 9.3 at this time). 

If you are still having trouble after updating, please turn off all other plugins (if you have any) and try the test again. If the problem goes away, you will want to turn each plugin back on until you find the one with the conflict.

I found that there are a few similar past reports at Yoast SEO which both point to either a theme or plugin conflict:

* https://github.com/Yoast/wordpress-seo/issues/4508
* https://github.com/Yoast/wordpress-seo/issues/3875

If the problem is still happening with everything updated and Yoast SEO is the only active plugin, please report as much detail as you can about the problem to Yoast SEO at https://github.com/Yoast/wordpress-seo/issues/new/choose.

**Comment by eleavor** [comment]
I just deactivated all plugins, and still have a zero word count (ETC) for this post https://ncfhaexpert.com/front-page/closing-a-usda-home-loan-during-gov-shutdown/ 

updated to Genesis 2.8.0 and Wordpress 5.0.3 with Yoast 5.0 SEO Premium

**Comment by swissspidy** [comment]
@eleavor Is it still broken with all plugins deactivated? Have you reported this to Yoast SEO already?

**Comment by designsimply** [comment]
@eleavor if the problem is still happening with WP 5.0.3 and Yoast SEO is the only active plugin, please report as much detail as you can about the problem to Yoast SEO at https://github.com/Yoast/wordpress-seo/issues/new/choose. If at all possible, try temporarily switching from Genesis to a default theme such as Twenty Nineteen because knowing that would help confirm whether the problem in your case is definitely only associated with the Yoast SEO plugin.
