### ISSUE TITLE
Excerpts as they are seen in a post preview.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#1288]
A thought...

On a few of my sites I use a styled excerpt as part of the post preview on the front page.
I have added some code to add TinyMCE to the excerpts meta box so that I can make it a little nicer. Here is an example in Norwegian. The word Utdrag is the same as Excerpt.

![screen shot 2017-06-20 at 00 46 42](https://user-images.githubusercontent.com/5323259/27317067-0f4adec8-5552-11e7-88fb-76fe0245ff37.png)

When I go to the front page and look at the styling of the excerpt this is what I see:

![screen shot 2017-06-20 at 00 48 35](https://user-images.githubusercontent.com/5323259/27317082-37dd5258-5552-11e7-8ec5-14ed8722845f.png)

Having a simple way to style the contents of the excerpt box directly would be of help or else it would just show up as a block of text.

**Comment by mtias** [comment]
I think we'll want an excerpt block to exist.

**Comment by paaljoachim** [comment]
That is a very good idea!

**Comment by westonruter** [comment]
Would excerpt block be locked to the first position in the editor once it is inserted?

**Comment by mtias** [comment]
@westonruter most likely, yes, and it wouldn't get the "mover" controls.

**Comment by paulwilde** [comment]
Should it be something you add via the popup - It would make sense to limit to only be added once, and then disable it in the popup.

On that note, such a feature would be nice in general for the API so third-party plugins could introduce blocks that have a specific limit to the amount of times it can be added to the place.

**Comment by westonruter** [comment]
@mtias also I presume that the Excerpt's block contents should get stored in the `excerpt` field of the post (the `post_excerpt` DB field) as opposed to being inline in the `post_content`, right?

**Comment by mtias** [comment]
@westonruter yes, correct. I had an issue for similar handling of featured images too.

**Comment by Drivingralle** [comment]
I don't think that's a good idea to lock the excerpt or other "meta box" like fields in place on top of the editor.

As some of my projects are made so 50+ users can publish, it's already hard enough to teach the frontend and backend method to create and view content. 
Thinking about telling them that they should ignore the first few "locked" blocks, because they will not appear in the frontend in that place anyway just cause them and me headaches.
Having the excerpt metabox and other below the current wp-editor allows to teach something like: 
"And in this boxes all the other notes and related information need to be entered.". 

Not mixing the main blocks and other blocks (excerpt-block) in one column/interface-part is very important for people which can not abstract as well as we (techy) web people/devs. 

IMHO:
If Gutenbergs goal is to provide a better interface to edit visible content, maybe it should become an frontend editor. So the wp_content or sidebar can be replaced with there own Gutenberg instances. Plus an area (customizer like) that allows to edit "invisible" meta data.

**Comment by paaljoachim** [comment]
I think it is totally fine where it is located right now as part of the Document settings. But then we need a way to add various styling to it. It could actually behave like a block but inside the Document setting.

**Comment by paaljoachim** [comment]
Here is some semi styling of the excerpts box:
![gutenberg-semi-styling-excerpts](https://user-images.githubusercontent.com/5323259/29480972-f913fed2-847c-11e7-9c9d-5f06b5c967cd.jpg)

**Comment by mtias** [comment]
This is a good one for looking at after the editing phase is done.
