### ISSUE TITLE
Conversion to Classic Block needed for completing the formatting workflow

### ISSUE THREAD

**Issue by burnuser** [WordPress/gutenberg#12899]
Classic Editor (especially with plugins like TinyMCE Advanced) has much more inline-formatting options than Gutenberg. Knowing such need in advance, I can select Classic Block to solve it. But in most cases I have 2 formatting problems:
I.) I recognise the need of extended inline-formatting after filling the block with content or even later when reworking the site content.
II.) I have a existing- pre Gutenberg - site, with a lot of inline formatting which is than converted to blocks. Thankfully the most formatting is shown also in Gutenberg blocks. But ... can not be edited any longer.

I made some - working - tests with second case:

Formatting:
*) Font Family
*) Font Size
*) Text Color
*) Background Color
*) Subscript
*) Superscript
*) Special character
*) Nonbreaking Space

All convertible Standard-Blocks:
x) Paragraph
x) List
x) Quote
x) Heading
x) Verse
x) Preformatted

Test:
1. Used this formats in Classic block
2. Duplicate block
3. Converted Duplicate to blocks
4. Converted blocks to each other (all possible conversions)
5. Formatting works!
6. Deinstalled TinyMCE Advanced
7. All formats are unchanged, blocks are valid
8. Reinstalled TinyMCE Advanced
9. All special formats are editable (in Classic) again

The only not correct working (but with open tickets):
a) Nonbreaking space works, but is not encoded
https://github.com/WordPress/gutenberg/issues/3549
b) Justify does not work
https://github.com/WordPress/gutenberg/issues/8450

ToDo:
In the moment all listed blocks are convertible to Paragraph.
But an additional conversion of all blocks to Classic would resolve the above stated problems.
It would allow extended inline formatting of existing regular block content AND the editing of existing formatting in converted block content.
All fully standard compatible AND interchangeable (Classic convert to Blocks <=> Blocks convert to Classic), building a closed workflow for inline-formatting!

**Comment by swissspidy** [comment]
I personally don't think we should encourage people to use the classic block in such a way. Add the necessary labels to get some more feedback on this.

**Comment by azaozz** [comment]
Thinking that is a pretty nice way to "ease in" switching from Classic to Block editor. Unfortunately the Classic Block is not suitable for such use, it is actually not a block at all, just some "loose" HTML in between other blocks.

Also thinking it is okay for such functionality to be added by plugins. The above mentioned TinyMCE Advanced does something similar with its Classic Paragraph block :)

**Comment by bozzmedia** [comment]
I have run into a similar workflow issue where once you go forward using paragraph blocks on a lot of content, it becomes cumbersome to edit and may be best suited for the classic editor block. Is there any way to convert para blocks to classic editor? 

I think this is worth persuing long term because this encourages folks to use Gutenberg without worrying about making a decision to use blocks on a particular page if they can always revert the page back to classic editor.  As it is, having built a few sites now using Gutenberg, I am finding myself now moving back to using classic editor as a default for pages with a lot of text content and regretting using gutenberg on some pages. If I could switch between classic editor and blocks as part of my content workflow I would be more inclined to continue to experiment with Gutenberg for these pages.  My 2 cents.

**Comment by gziolo** [comment]
> I have run into a similar workflow issue where once you go forward using paragraph blocks on a lot of content, it becomes cumbersome to edit and may be best suited for the classic editor block. Is there any way to convert para blocks to classic editor?

This should be part of the [Classic Editor plugin](https://wordpress.org/plugins/classic-editor/) if ever implemented.

I'm closing this issue based on feedback from @swissspidy and @azaozz.

> (Was going to assign a "Close" label but it doesn't exist?? Should probably be added, it is pretty useful/works well on core trac.)

There is `Won't FIx` label as well.
