### ISSUE TITLE
I don't have up or down arrows to the left of the block. Therefore unable to move blocks around, how do I fix this problem?

### ISSUE THREAD

**Issue by TracyNewcomer** [WordPress/gutenberg#12993]
If you have a question you have a few places that you can ask this:

- Support Forums: https://wordpress.org/support/plugin/gutenberg
- Handbook: https://wordpress.org/gutenberg/handbook
- https://chat.wordpress.org #core-editor

If you are unable to ask in those places you can ask here, however you will get faster responses through those recommended places.

**Comment by swissspidy** [comment]
> I don't have up or down arrows to the left of the block. Therefore unable to move blocks around, how do I fix this problem?

Can you please post a screenshot?

**Comment by TracyNewcomer** [comment]
Hi,
Thank you so much for responding to my question. I tried reinstalling
WordPress 5.0 and that did help to solve this issue.
Thanks again
Tracy Bussing

**Comment by swissspidy** [comment]
Glad to hear you were able to resolve the issue!

**Comment by TracyNewcomer** [comment]
The issue is not resolved

**Comment by TracyNewcomer** [comment]
I still don't have up & down arrows, please don't close my case
Tracy

**Comment by swissspidy** [comment]
Can you elaborate?

You just wrote:

> I tried reinstalling WordPress 5.0 and that did help to solve this issue.

If you still don't have up & down arrows, can you please upload a screenshot here of what you currently see?

**Comment by TracyNewcomer** [comment]
I do not have an up & down arrow beside the box in order to move the box up
or down

**Comment by designsimply** [comment]
The block movers (up & down arrows near the top left of each block) will not appear if you are using the Spotlight mode. Can you check to see if you have that turned on by clicking the More menu (three dots) at the far right side of the top toolbar?

If you are using a very small screen size or have zoomed in your font settings a lot in your browser settings, the block movers may appear below the block instead of next to the block. If either of those cases apply to you, can you check for the arrows below the block?

**Comment by TracyNewcomer** [comment]
Thank you so much for your help, it worked!!
Tracy
