### ISSUE TITLE
Pasting a URL that does not advertise oEmbed support results in a broken embed

### ISSUE THREAD

**Issue by jeremyfelt** [WordPress/gutenberg#13003]
**Describe the bug**

When I paste a URL like https://core.trac.wordpress.org/changeset/44321, which does not support oEmbed and is not intended for use as embedded content, into a new paragraph block, I get an error showing "Sorry, we could not embed that content." and no obvious way to say "just show the URL, please".

**To Reproduce**
1. Create a new post
2. Paste https://core.trac.wordpress.org/changeset/44321 into the post content
3. See error

**Expected behavior**

If a pasted URL does not support oEmbed, I expect that just the URL text is used and that an oEmbed is not attempted.

If it's helpful for the error message to appear, I think it may be even more helpful to have another action available, such as a button for "add as text only" or something.

**Screenshots**

<img width="663" alt="screen shot 2018-12-18 at 6 38 11 pm" src="https://user-images.githubusercontent.com/286171/50195478-1ccd4080-02f4-11e9-9655-4eb5c213ded1.png">

**Desktop (please complete the following information):**
 - OS: OSX 10.12.6
 - Browser Chrome (latest)

**Additional context**

WordPress 5.0.1

**Comment by notnownikki** [comment]
Hi! Thanks for raising this issue, it's one that's bugged me for a long time too. Thankfully, this was fixed in https://github.com/WordPress/gutenberg/pull/12095 which adds options to convert the URL to a paragraph, or to try to embed again (just in case there were network errors). I'm not sure when that's due to be merged into core, but the fix is there in version 4.7 of the plugin.
