### ISSUE TITLE
Add Block: Page/New Page

### ISSUE THREAD

**Issue by grindstr** [WordPress/gutenberg#13047]
I’m setting up new web site with twenty nineteen and miss the possibility to add new page sections on front page, like the way you can add more page sections in the "Theme Options" within the Customizer of Twenty Seventeen. I was thinking that this same feature could fit perfectly as a block in Gutenberg Editor.  
I attached some clipboard image from Customizer of Twenty Seventeen theme, to show what i'm aiming at. Hope this could be taken into consideration:-)

regards
grindstr

![section-placeholders-customizer](https://user-images.githubusercontent.com/45949513/50300392-93994380-0484-11e9-964f-55bd23afe3ed.JPG)
![section-placeholders](https://user-images.githubusercontent.com/45949513/50300398-9ac05180-0484-11e9-9799-5c3714aea963.JPG)

**Comment by youknowriad** [comment]
Can't you just use a static page as home page and use the block inserter to add whatever sections you want to add there? Is this what you're trying to achieve?

**Comment by grindstr** [comment]
Yes, If this block inserter can add an existing page within my static home page, then it's what i'm looking for. But where can I find this block inserter? 
In case there is not such block, the block i'm trying to explain is simply a block that open up a list with all your existing pages. From this list you can select a page to add to your static home page, or whatever page you want to build up this way. You will be able to create a page containing several pages with different information. The same pages can be used on other places within your site, the main purpose is to be able to maintain information only one place. If you have knowlegde of the twenty seventeen theme feature, you will know what i'm aiming at. If this block already exist, please let me know where i can find it. Then all my effort trying to give ideas for such a block is wasted.

**Comment by youknowriad** [comment]
Did you try the reusable blocks feature?

So instead of creating separate pages, just create blocks, select them, click the block menu and choose "Create reusable block".

You'd be able to insert this same block in all the pages using the inserter.

**Comment by grindstr** [comment]
Yes, I have tried reusable block, but this is as far as I see only possible for single blocks. How to make a hole page reusable?

**Comment by grindstr** [comment]
I don't think you understand what i'm trying to achieve. Take a look at this web site: https://solnikgarden.com/ and scroll down the front page. You will see that this site is build up with sections of different pages. You can see a horisontal line of every section.

**Comment by grindstr** [comment]
What is the problem of making a block adding a page? Reusable block don't make it possible to maintain the information at one place, without changing the information everywhere you have used the reusable blocks. Its too cumbersome and will never be used. If there should be some flexibility of this block editor, why not expand the flexibility of this editor?

**Comment by grindstr** [comment]
For simpler starting point where you want to reuse some building block and make changes, I can see the point of using reusable block. But for hole pages, sorry, I can't see how this will be possible if you want to maintain the information of reused blocks if you want to do changes everywhere, especially hole pages. Please let me know what i'm missing here?

**Comment by youknowriad** [comment]
> Reusable block don't make it possible to maintain the information at one place, without changing the information everywhere you have used the reusable blocks.

That's exactly what reusable blocks, if you change it once, it updates everywhere.

> What is the problem of making a block adding a page?

There's no problem, the only thing is that we don't want to introduce the same feature twice.

**Comment by grindstr** [comment]
I still think you have missed the hole point. Who will make such effort of creating reusable blocks to hole existing pages? Why? Its's totally nonsense. This feature exist within some themes today, but you are only focusing on using existing solution within gutenberg editor that is out of context. I'm open to discuss solutions to the future gutenberg editor, but I have to say that i'm very disappointing if you represent a team of developing gutenberg blocks if this is the conclusion. It's better to say that you will not contribute to add this feature. I will never ever use reusable block to rebuild or reuse existing pages. I hope someone else can see this dialog and to comment on this.

**Comment by youknowriad** [comment]
I'm sorry you feel this way, it's totally possible that I missed the point, I'm still trying to understand though. I'll leave this issue open for others to weight in. No one has all the answers.

**Comment by mapk** [comment]
> I’m setting up new web site with twenty nineteen and miss the possibility to add new page sections on front page

Hey @grindstr! While I understand your familiarity with creating pages and using pages as the reusable content, I believe @youknowriad is pointing out that Gutenberg presents a different paradigm. 

Rather than using "pages", Gutenberg makes this possible with reusable blocks. Reusable blocks can be a combination of several blocks that provide the layout and content you desired – just like a page. You can also edit the reusable block and update the layout or content and it will update that reusable block everywhere it's used.

> Yes, If this block inserter can add an existing page within my static home page

If you're creating new content/layouts, Gutenberg reusable blocks works really well. If you're trying to add existing pages this way, reusable blocks don't work so well with that... unless those existing pages are all done in Gutenberg. Then you can open an existing page, select all the blocks and create one reusable block. 

Editing these reusable blocks is a bit difficult to find. Click the inserter icon and scroll to the bottom where you'll see the "Reusable" section. From here there is a link, "Manage all reusable blocks" – clicking that will take you to the page where you can edit all your reusable blocks – just like pages.

![screen shot 2018-12-31 at 10 54 08 am](https://user-images.githubusercontent.com/617986/50566096-6d786c80-0cea-11e9-9d3f-74b78563e310.png)

Using pages in Twenty Seventeen was a workaround limited by the structure of WordPress. The concept of using "pages" within pages is confusing for many. Now with Gutenberg, everything is a block, and blocks can be inserted anywhere (especially in the coming Phase 2).

I hope that helps clarify some things. I don't think Gutenberg will be creating any core blocks to insert pages into pages. BUT what's really cool is that someone else can build a custom block to do this!

**Comment by designsimply** [comment]
@grindstr have you tried reusable blocks per the suggestions here and it didn't work?

Have you seen the interface for editing reusable blocks at `/wp-admin/edit.php?post_type=wp_block`?

![screen shot 2019-01-25 at 5 08 20 pm](https://user-images.githubusercontent.com/1119271/51779321-d5408e00-20c3-11e9-90e5-7778f3135d5c.png)

**Comment by grindstr** [comment]
Hi @designsimply. 
Design simply is exactly what i'm aiming at. Design something that will make it easy for editors to use.  I have been using reusable block on three full (static) pages on my front page. But, the way it is implemented, makes it hard to edit and maintain. Specially if you are dealing with dynamically pages, where you need to use this "very hidden and restricted reusable editor", /wp-admin/edit.php?post_type=wp_block. I was trying to add new block, copy and paste between one reusable to create another reusable. This editor is terrible. 

Let me give you my design point of view on how I would have liked this to work. Maybe it's better to comment on that.
Instead of copying blocks and add it as "reusable", it would have been better to store these block as a "new page". There should be a setting within the pages editor to "hook" the page as "reusable". These pages "hooked" could very much show up in the list of "reusable block" as implemented today. But the main point of doing it this way is that you will be able to edit and maintain the pages using the regular editor. And you can remove this terrible restricted reusable editor hidden at /wp-admin/edit.php?post_type=wp_block. I have problem to see why it's build a separate editor for reusable blocks?

Another approach to make reusable block/pages, is to make a new block to add a page elsewhere. Hope someone one day will make a plugin like this, with some ability to switch on/off some features. It is as simple as it could be @designsimply :-)
I think then all the effort and time the Gutenberg project have spent on making the reusable block editor is totally waste. 

I'm aware that the Gutenberg project are restricted to work within some guidelines and mandate. So with that in mind, my feedback is now only to point out my design opinion of the reusable editor. 
I also know that there is a lot of work within this project and that the focus has to be on the most important functionality. 
I hope for some understanding about my opinion of this.

**Comment by paaljoachim** [comment]
Hey @grindstr 

Lets see if I understand this correctly.
You could like a way to insert a full page into an existing page.

It sounds like your talking about something similar to the template feature which is still in the ideas phase.

Here is a template test made by @jeremyfelt 
https://twitter.com/jeremyfelt/status/1075932152422756353

This could mean add a template page to the existing page one is building. Either to have it overwrite the content of the page it is being added to or to add it below the existing content of the page.

Here is a template issue: https://github.com/WordPress/gutenberg/issues/5537

**Comment by designsimply** [comment]
Thank you for posting your thoughts! I will say that at this point in time the reusable block editor is a fairly new feature and likely to go through future revisions and improvements but I am not sure when because iterating on the design and discoverability of reusable blocks is not a priority noted in the [Phase 2 Scope & Features](https://github.com/WordPress/gutenberg/issues/13113) document. 

> And you can remove this terrible restricted reusable editor hidden at /wp-admin/edit.php?post_type=wp_block. 

I was thinking about this and went back to something you said earlier:

> However, if you want to re-use whole dynamic pages, it will be difficult, or almost impossible to use "reusable blocks" editor. You then have to be able to change the page in the usual way under "Pages", and at the same time be able to verify and visualize the result before you publish. Using reusable block editing on whole pages is meaningless.

And also what you said about not wanting to change the information everywhere:

> Reusable block don't make it possible to maintain the information at one place, without changing the information everywhere you have used the reusable blocks.

And it almost seems like @paaljoachim might be exactly right and the Template API might be closer to what you are wishing for and we just didn't understand in the earlier descriptions! 

In case templates do look appealing to you, I will also add a link to a little bit of information about them from the Gutenberg handbook which you can check out if you are interested:
https://wordpress.org/gutenberg/handbook/designers-developers/developers/block-api/block-templates/

**Comment by grindstr** [comment]
Thanks @paaljoachim and @designsimply.  
The last statement was something I said before you told me how the reusable block did work and where I could find this "hidden" editor. So sorry for this statement. It is possible to maintain it everywhere but i still mean it's difficult to use, both for static or dynamic pages/blocks. 

What I'm looking for is to show a resume of my topics on my front page. The best would have been to show part of each page with a "read more" link before scrolling down to the next topic/page. But this should be settings the user can decide, also to be able to show/hide the page title. What I liked with twenty seventeen was the way you could build up your front page this way and also show part of your post/blog page, the same way as you selecting the main post page, but without the sidebar. I think this is possible for some paid versions of some themes, but when I first started to check out GB, my first thought was that this would fit perfectly as a special "add page" block, with the ability to hide/show title, read more and decide how many posts you like to show when adding the post page, and so on. 

Anyway, I will check out and look more into templates from the links you supplied. Could be this is what may solve my wishes. My head is still thinking this is a block issue, but I know to little about templates to say anything about this now:-). 

If there will be some possibility to test any first version of templates, I really like know about this and to be able to test it. 

Thanks for your comments and for trying to understand what i'm looking for.

**Comment by designsimply** [comment]
Because there isn't anything specific and actionable in this issue right now and because a recommendation was made to explore either reusable blocks or templates as preferred solutions right now, I would like to close this issue and note that the suggestion was acknowledged but that it isn't currently a planned update to make a page-within-a-page block.

Thanks for having the discussion and for your patience with everyone trying to understand the root issue!

**Comment by paaljoachim** [comment]
Hello again @grindstr 

It kinda sounds like your looking for a way to show blog post previews on any page.
I have been using this plugin: https://wordpress.org/plugins/post-type-archive-mapping/ (One can choose to show any category from posts or Custom Post Types.)
The next version of the Latest Post block is these days being worked on: https://github.com/WordPress/gutenberg/issues/1594

Have a great day!
