### ISSUE TITLE
ACF metaboxes not working

### ISSUE THREAD

**Issue by drmab** [WordPress/gutenberg#13046]
**Describe the bug**
When creating or editing a post, The ACF metaboxes appear, but cannot be opened. Clicking the arrow, or the title, does nothing.

**To Reproduce**
1. Create new post with ACF field groups
2. Click on the ACF metabox.

**Expected behaviour**
The accordion should open to reveal the fields.

**Desktop (please complete the following information):**
 - OS: Win7
 - Browser: Firefox
 - Version: 64
 - WP 5.0.2, Apache 2.4.23 - PHP 7.0.10 - MySQL 5.7.14

**Comment by designsimply** [comment]
I tested with WordPress 5.0.2 and Advanced Custom Fields 5.7.9 using Firefox 63.0.3 on macOS 10.13.6 and was unable to replicate.

1. Install and activate ACF.
1. Go to Custom Fields > Add New. 
1. Add a few custom fields and click Publish to create a Field Group.
1. Go to Posts > Add New.
1. Click the arrow to the right of the field group to open and close it.

Result: the toggle to opened and closed normally. ([24s](https://cloudup.com/cASiVYWXogm))

Some troubleshooting steps you can try next are:

Clear your browser cache or try from a different browser to rule out a local caching or browser issue.

Test with all other plugins temporarily deactivated and using the default theme to rule out a plugin conflict.

If you're still having trouble with ACF as the only active plugin when using WordPress 5.0.2, try checking the console in your browser's web developer tools for errors at the time you click the arrow the custom field group open and closed while editing a post. If there are any errors showing in the console, they could prove to be helpful for debugging.

Because I was unable to replicate the problem or find anything indicating it is related to Gutenberg, I am going to close this issue for now and recommend also asking in the help forums for ACF to find out if any other users of that plugin are experiencing the same problem. If  you spot something different in my testing compared to yours, let me know and we can re-visit. And we can also re-open if you have more information to add or if we find that others are experiencing the same problem even if I did not in testing so far.

**Comment by drmab** [comment]
Indeed, it was because of a plugin, namely WPML.

**Comment by drmab** [comment]
Just so you know, the latest update of WPML fixed the problem.
