### ISSUE TITLE
How to use 'react-slick' in save function?

### ISSUE THREAD

**Issue by prajaktagadhave** [WordPress/gutenberg#13055]
Hello,

I want to use `react-slick` component for one of my blocks. In edit function I am able to use `import Slider from "react-slick"` <Slider> component successfully.
That is in customizer everything works fine. But, if we placed <slider> Component inside save function it throws error - `uncaught (in promise) TypeError: Cannot call a class as a function at _classCallCheck (inner-slider.js`

Any idea about this?

**Comment by swissspidy** [comment]
It‘d be helpful uf you could share your code here.

**Comment by designsimply** [comment]
You probably need to extend your class as React.Component class.

I'm going to close his issue with that note and ask that if the suggestion doesn't help then please reply with a code example to re-open the issue!

**Comment by chrisvanpatten** [comment]
@prajaktagadhave I may have misunderstood, but I believe that the issue is that the React-Slick component may not serialise cleanly to HTML. If you want to use React-Slick on the front-end you would likely need to store the data in JSON or some other format, and then enqueue separate JS on the front-end that requires React and renders the component with the saved data.
