### ISSUE TITLE
Pressing Preview shows infinite "Generating Preview..."

### ISSUE THREAD

**Issue by trade-commander1** [WordPress/gutenberg#13071]
**Describe the bug**
My wordpress installation was automatically updated to WP 5.02.
When i now open the preview of a page, it stucks in "Generating Preview..."

**Comment by swissspidy** [comment]
That's usually a sign of a JavaScript error. It might very well be related to your other issue, #13072.

While the preview is stuck, please go back to the editor and open your browser's developers tools by pressing F12. Then, click on "Console" to see if there are any errors shown. If so, try to copy the error message and paste it here, or take a screenshot of it.

Also, try to disable all plugins and switch to a default theme like Twenty Nineteen to see if the issue still persists.

**Comment by trade-commander1** [comment]
Hello Sir,

thank you for answer.

„Also, try to disable all plugins and switch..“

 

really, this is recommendation ?

 

I better should not update or drop WordPress.

 

 

Von: Pascal Birchler [mailto:notifications@github.com] 
Gesendet: Samstag, 22. Dezember 2018 11:02
An: WordPress/gutenberg
Cc: trade-commander1; Author
Betreff: Re: [WordPress/gutenberg] Pressing Preview shows infinite "Generating Preview..." (#13071)

 

That's usually a sign of a JavaScript error. It might very well be related to your other issue, #13072 <https://github.com/WordPress/gutenberg/issues/13072> .

While the preview is stuck, please go back to the editor and open your browser's developers tools by pressing F12. Then, click on "Console" to see if there are any errors shown. If so, try to copy the error message and paste it here, or take a screenshot of it.

Also, try to disable all plugins and switch to a default theme like Twenty Nineteen to see if the issue still persists.

**Comment by swissspidy** [comment]
@trade-commander1 This is not a **recommendation**, these are suggestions to help you **debug** this problem so we can find the root cause. Two very different things.

**Comment by designsimply** [comment]
I have tried testing using WordPress 5.0.2 and the following steps:

1. Go to Pages.
1. Click on any published page.
1. Click the Preview button.
1. Note whether or not the preview works.
1. Go to Pages > Add New.
1. Add a title and some content.
1. Click the Preview button.
1. Note whether or not the preview works.

**Result:** the previews in my testing worked normally in all cases.

**Note:** this doesn't mean they necessarily should be working for you, but it does show that they have been tested and are working in a basic setup and that more information is needed to proceed with your issue report. It is possible there is a plugin or theme conflict and it would be helpful to narrow that down for testing purposes or to know any other relevant details you can think of.

Please test after temporarily switching to a default theme. If that doesn't help, please switch your theme back and and temporarily disable all plugins and test again—if the problem is still happening for you at that point, please re-open this issue and please add a comment noting if your testing steps match the ones I used and which version of WordPress you tested with and any other details you may have found which could be relevant to helping you solve this case. Thank you for participating here and for working to get additional details.
