### ISSUE TITLE
All Gutenberg paragraph fails to save Grammarly Edited text. 

### ISSUE THREAD

**Issue by quickfever-cdn** [WordPress/gutenberg#13083]
**Describe the bug**
When using Grammarly to correct spelling mistakes, the page doesn't seem to save it even when you save it. On reload, the edited text with Grammarly reverts back.
**To Reproduce**
1. Install Grammarly Chrome extension.
2. Make a new post, type few lines in a paragraph block. Fix errors with Grammarly. 
3. Save Draft, or Publish.
4. reload, page. Everything reverts back.

**Expected behavior**
It should save text, fixed by Grammarly.

**Desktop (please complete the following information):**
 - OS: Windows 10, 17763.195
 - Browser Chrome 71
 - GT version: Wordpress 5.0.2

**Additional context**
- Latest shipped with Wordpress 5.0.2

**Comment by cedial1** [comment]
This situation is far worse than described here by quickfever-cdn. I have completely lost my temper over losing man-days of work due to Grammarly's bugs messing up Gutenberg in an incredibly sneaky way. My outrage has led me to extensively document the HTML with which Grammarly is assaulting Gutenberg. 
[Gutenberg+Grammarly-The Perfect Storm.pdf](https://github.com/WordPress/gutenberg/files/2706478/Gutenberg%2BGrammarly-The.Perfect.Storm.pdf)
"

**Comment by youknowriad** [comment]
Unfortunately this isn't immediately actionable within Gutenberg, I suggest raising this issue to the Grammarly extension authors.

**Comment by desrosj** [comment]
Noting that [Trac-47432](https://core.trac.wordpress.org/ticket/47432) was closed as a duplicate of this issue.

**Comment by limeshparekh** [comment]
I also have the same problem. Unfortunately, Both of my fav platforms don't work with each other. SAD
