### ISSUE TITLE
Dock the Add Block top inserter area

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#13211]
**Is your feature request related to a problem? Please describe.**
To insert a block one has to click the Block Inserter -> scroll to find the correct block -> click the block. One can also do / then block name to find the block one needs to use.

**Describe the solution you'd like**
I am suggesting a dock the block similar to a Photoshop toolbar is docked.

![add-block-stick-toolbar](https://user-images.githubusercontent.com/5323259/50727983-8d14f800-1123-11e9-82ec-227f77aaa6f4.jpg)

Having an icon/words one can click to stick/dock the blocks area.

--

Dock the Blocks on the left side.
With labels.

![stick-the-block-open-labels](https://user-images.githubusercontent.com/5323259/50727955-0c55fc00-1123-11e9-9cd1-f23be1966370.jpg)

Without labels.

![stick-the-block-open](https://user-images.githubusercontent.com/5323259/50727947-f5170e80-1122-11e9-9615-ff4aa4407de1.jpg)

**Comment by ZebulanStanphill** [comment]
This reminds me of the way the widget library is shown on the `wp-admin` Widgets page and in the Customizer. Perhaps something like this could replace those in the future.

**Comment by designsimply** [comment]
Thank you very much for the suggestion. I found a similar feedback and design exploration of the block library from the past in #8951 and would like to reiterate the reply from that issue here as well to say the suggestion is appreciated and that we currently plan to stick with the current design.

I will also add some design feedback from my own perspective (which are my opinions):

* The icon-only version is not accessible.
* Make sure to consider mobile.
* The white arrow next to "Posts" in your designs make it look to me like the menu belongs to "Posts" which is a bit confusing.
* A design addition this different would be so great to explore first as a plugin first.

Please consider continuing to discuss the issue here after it is closed.

**Comment by paaljoachim** [comment]
Hello Sheri @designsimply 

Thanks for the feedback!

I made the wireframe as I jump between using Norwegian and English languages and the name of a block varies depending on language. Having an option to stick the blocks as an additional toolbar would be helpful for me while building the site, as I could just click the icon with the name under it to have it added to the layout. The option is to click the + sign browse through the block list.

It would likely not be used while on a mobile. 
We would then just skip icon only mode.

I will just leave the issue as it is. I just wanted to add the suggestion.
