### ISSUE TITLE
editor doesn't display current site pages

### ISSUE THREAD

**Issue by DavidMambopro** [WordPress/gutenberg#13234]
When my wordpress was updated to Ver. 5 and the Gutenberg editor become the default, I could not see any of my current site pages when logged into the wordpress backend admin??? I had no choice but to activate the old editor. What's the reason for this issue? Thanks.

**Comment by youknowriad** [comment]
It's one of two things:

 - a plugin (or more) incompatibility issue, try disabling your plugins one by one to find the problematic one.
 - a server configuration issue: Gutenberg requires the REST API to work properly and since it's the first feature using it, your installation might have a broken REST API setup for some reason.

I'm closing but let me know how it goes.
