### ISSUE TITLE
Many cmd+ and ctrl+ shortcuts not working in Gutenberg on MacOS

### ISSUE THREAD

**Issue by AdrienM76** [WordPress/gutenberg#13258]
**Describe the bug**
Many cmd+ and ctrl+ shortcuts are not working in Gutenberg.

**To Reproduce**
1. Go to editing a post in Gutenberg
2. Click on ⌤⌥H to bring up shortcuts
or
2.⇧⌘D to duplicate a block
or
any other block manipulation shortcut
3. nothing happens

Note, basic text manipulation such as ⌘B, ⌘I, ⌘K, ⌘X, ⌘C, ⌘V, ⌘A, all work fine. It seems this is limited to shortcuts employing ⌤ or ⌥(ctrl or option) or ⌘(cmd) with a modifier.

**Expected behavior**
All shortcuts work as intended.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.2
 - Browser: Firefox-dev
 - Version: 65.0b9

**Additional context**
- WP 5.0.2

**Comment by designsimply** [comment]
I tested with WordPress 5.0.2 using Firefox 64.0 on macOS 10.13.6 and keyboard shortcuts such as `^⌥H` and `⇧⌘D` worked in my tests.

![13258-7s](https://user-images.githubusercontent.com/1119271/50944951-cdd87e00-144f-11e9-8166-7dc574e22651.gif)

Any chance you'd be able to run the test again using the latest stable release of Firefox instead of the dev version?

Can you confirm you've tried a couple basic troubleshooting steps such as clearing browser cache and making sure there aren't any browser add-ons which could be causing trouble?

**Comment by AdrienM76** [comment]
Thank you for the prompt reply and my apologies for taking so long to get back to this.

It seems to be a problem with Firefox at least on MacOS. I tested with 60.4.0esr in Safe Mode and I still couldn't get either shortcut to work. (I didn't test any others) ctrl-opt-H produces a 'dot above' character instead of bringing up help (ctrl seems to be ignored as opt-H is the shortcut for typing that character with a U.S. input method) and shift-cmd-D does nothing at all.

However, both work in Safari.

**Comment by designsimply** [comment]
At first, I wanted to ask if you could update to Firefox 64 but then I researched what 'ESR' means and I found:

> Firefox Extended Support Release (ESR) is an official version of Firefox developed for large organizations like universities and businesses that need to set up and maintain Firefox on a large scale. Firefox ESR does not come with the latest features but it has the latest security and stability fixes.

<sup>Source: https://support.mozilla.org/en-US/kb/switch-to-firefox-extended-support-release-esr</sup>

Because the description of Firefox ESR mentions that it does not come with the latest features, it made me wonder if that specific version is the problem—I also wonder that because I myself tested with Firefox 64.0.2 on macOS 10.13.6 and found the keyboard shortcuts to be working in that version of Firefox. 

I will add this back to the `Needs Testing` label to ask for help either from people working on the project or from the community (or I may be able to circle back once my other tasks are done) to see if we can get another tester to help confirm whether or not keyboard shortcuts work for them when using Firefox ESR 60.4.0+.

Thanks for responding! It's no problem about the delay and it's good to know the extra details and that keyboard shortcuts do work for you when using Safari!

**Comment by AdrienM76** [comment]
I tested with the ESR because that's what I already had installed. There's also a fairly good chance users might stick with it as well, rather than always have the latest. The original report was involving 66beta both Nightly and -Dev editions. So even if 64 is special, this functionality is due to break shortly down the road anyway. Just for completeness, I'll test with 64.0.2 also and report back.

**Comment by youknowriad** [comment]
I can't reproduce this in the latest firefox versions. Firefox have been updated several times since.

**Comment by AdrienM76** [comment]
I can also confirm this is working in FF 69.02, but oddly is still not working in FF-Nightly 71.0a1(2019-10-08) or FF-dev (70.0b13). I hope this isn't a regression on Mozilla's part. While I understand more users might be using stock FF, I'd be surprised if the proportion of FF-dev users were insignificant.
