### ISSUE TITLE
Gallery Block: Gallery not being properly displayed/rendered in Edge

### ISSUE THREAD

**Issue by AtrumGeost** [WordPress/gutenberg#13270]
**Bug Description**
When opening a page with a galler of three columns in Edge it won't be properly displayed as in other browsers.

**To Reproduce**
1. Create a new page or post with a 3-column gallery
2. Open the published page or post in Edge

**Expected behavior**
To get the gallery displayed as in other browsers

**Screenshots**

https://bright-natterjack.jurassic.ninja/gallery-test/

Gallery in Edge:

![screen shot on 2019-01-09 at 15-03-20](https://user-images.githubusercontent.com/3696121/50925337-14ae7f80-1420-11e9-83c5-942a6ed2b809.png)

Gallery in Chrome:

![screen shot on 2019-01-09 at 15-06-18](https://user-images.githubusercontent.com/3696121/50925376-2db73080-1420-11e9-837b-be09e18da93a.png)

**Desktop:**
 - OS: Windows 10 for Edge and macOS for Chrome
 - Browser: Edge 18 Latest Version (using Browserstack) and Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Additional context**
- Tried with Jurassic Ninja running WordPress 5.0.3 and Twenty Nineteen theme
- Tried with WordPress.com and the Affinity theme

**Comment by designsimply** [comment]
Nice find! I tested and confirmed with WordPress 5.0.3 and no active plugins using Twenty Nineteen 1.2 that a 3 column gallery doesn't line up correctly in Edge 18 on Windows 10.

![bs_win10_edge_18 0 6](https://user-images.githubusercontent.com/1119271/50985228-0a908d80-14c1-11e9-9f2f-cf446d121175.jpg)

Interestingly, I found that it works properly _if_ the Gutenberg 4.8.0 plugin is activated:

![bs_win10_edge_18 0 7](https://user-images.githubusercontent.com/1119271/50985240-154b2280-14c1-11e9-9d6b-e904b3762cc8.jpg)

@jasmussen the main difference I spotted between the two screenshots above is that when the plugin is NOT installed Edge calculates an _ever-so-slightly_ different width as `calc(-10.6667px + 33.3333%)` served via `style.min.css` and when Gutenberg is deactivated then Edge calculates the width as `calc(-10.66px + 33.33%)` served via `style.css`. I noticed that changing `margin-right` to be even one pixel smaller, from `16px` to `15px`, solves the problem but I am not sure if that's too much of a bandaid kind of a fix. Ooo, I can PR it if that looks like a viable solution to you though!

Related PR: https://github.com/WordPress/gutenberg/pull/10027

Code ref: https://github.com/WordPress/gutenberg/blame/88a69507e0bba453fd0f239b4be1567c94953396/packages/block-library/src/gallery/style.scss#L102

btw, this all seems _incredibly_ sub-pixel rendering edge-case-y to me! I did find that different browsers round fractional pixels differently (https://cruft.io/posts/percentage-calculations-in-ie/) but the part about Edge rounding differently for minified CSS (more decimal places) vs unminified CSS is interesting and I am curious whether the difference in rounding happens because of the minification or if it's something coming from the plugin vs core. It's got to be because of the minifcation, right?

**Comment by coreyworrell** [comment]
This also happens in Firefox when fractional scaling is used (`layout.css.devPixelsPerPx` equals `1.25` for example).
