### ISSUE TITLE
Add Block: Next Page

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#1328]
WordPress allows splitting up posts into multiple pages by placing `<!--nextpage-->` into the content. Just like `<!--more-->` inserts a "Read more" tag (see #983). Gutenberg should also support this.

I'll look into both to see if I can easily create a PR for that. 🤞

**Comment by jasmussen** [comment]
See also "Read More" mockups, I susepect this block can look much the same 'cept for the label:

https://github.com/WordPress/gutenberg/issues/983#issuecomment-310593148

**Comment by dmsnell** [comment]
This is going to be a bit more difficult I suppose since we can have more than one. It makes sense as a block though and I think we can visualize it well in the editor. I would like to hold off on implementing it in the parser for now, however, until we figure out the more tag. The reason is that I think that many of the decisions we make for it will apply here.

**Comment by mtias** [comment]
It'd be nice to show this in the "table of contents" panel as well if used.

**Comment by karmatosed** [comment]
As the project moves towards merge proposal, we are moving issues that aren't needed for that to projects. This doesn't mean they won't get done, they totally can and that's why we're moving to projects. This allows us to focus on the issues that have to happen to Gutenberg.
