### ISSUE TITLE
Upgraded site has no default blocks

### ISSUE THREAD

**Issue by CoolDadTx** [WordPress/gutenberg#13299]
**Describe the bug**
I upgraded my WP site a while back. I've updated it since then and are now at 5.0.3. At the time I was using JetPack with Markdown support so the post editor allowed me to use markdown instead of HTML. JetPack now has a Markdown block available so I was going to switch to using the block inside the editor. However there are no blocks being shown as available. I create a new post and the option to add a block (the plus) is disabled.  I went to the block editor and it doesn't show any blocks being available, just the option to import from JSON or add a new block.

At this point I have the new editor but none of the default blocks are available so I can actually create content. Opening an older post is supposed to convert it to the "classic block" but all I see is the text. No blocks are shown as available.

At one point I had the classic editor plugin installed but not activated. Not sure what is going on but I would like to get the default blocks available in WP available.

**To Reproduce**
1. Go to add a new post.
2. The "add block" button is disabled when inside the body of the post.
3. Go to the block editor.
4. No blocks are listed as available. Only options are to import or add a new one.

**Expected behavior**
The default blocks that ship with WP should be available to use.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome, Edge, Firefox
 - Version 

**Smartphone (please complete the following information):**
n/a
**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by designsimply** [comment]
First, check to make sure the option at Users > Your Profile > Personal Options > "Disable the visual editor when writing" is unchecked. 

If the problem persists, when this has come up in the past, the root cause was that the web host was configured so that it was not passing headers through and that needs to happen in order for the blocks to work. Here is the solution for that issue from someone in the support forums:

> There's two methods for resolution that we've landed on:
> 
> 1. Change the CloudFront behaviors to pass on headers. This is detailed in [this post by user g3luka][1].
> 2. Add code to functions.php that will enable the `user_can_richedit` flag [as detailed in my post][2]. Many thanks to https://webhost.io/, our host, for coming up with this one.
> 
> [1]:https://wordpress.org/support/topic/block-editor-no-longer-working-only-shows-html/page/2/#post-11014978
> [2]:https://wordpress.org/support/topic/block-editor-no-longer-working-only-shows-html/page/3/#post-11032983

Source: https://github.com/WordPress/gutenberg/issues/12927#issuecomment-450880090

Sites hosted using AWS CloudFront are likely affected, and there could be other hosts with the same problem. If you're not sure how to check the configuration of your server to make sure it is passing headers through, please ask your web host for help as they should know the ins and outs of the setup you are using.

If you find that neither of the proposed solutions above is helpful, please reply here and ask to re-open the issue. Thank you!
