### ISSUE TITLE
Target Classic Editor Block with has_block

### ISSUE THREAD

**Issue by mrpritchett** [WordPress/gutenberg#13297]
I'm looking for a way to target classic editor block in order to conditionally run code for just the classic editor (in block form, we already have the classic editor without Gutenberg take care of).

We're looking to do something like `if ( ! has_blocks() || has_block( 'classic_editor' ) ) {`

I was told in Core-Editor channel to try `has_block( 'null' )` but that does not work.

**Comment by mrpritchett** [comment]
We're looking to do something like `if ( ! has_blocks() || has_block( 'classic_editor' ) ) {`

**Comment by mrpritchett** [comment]
I was told in Core-Editor channel to try `has_block( 'null' )` but that does not work.

**Comment by youknowriad** [comment]
This is a bit more complex that it seems because the classic block block don't produce block comments (as it's the fallback block) which means the regex used is not going to work regardless. 

We may want to introduce a special case for this block in these functions. 

That said, these functions are now maintained in Core, so it's better to open a trac ticket https://core.trac.wordpress.org
