### ISSUE TITLE
Improve or rethink the Reusable Block Indicator

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#13307]
The Reusable Block Indicator is a small component meant to visually expose the name of a reusable block:

<img width="897" alt="screenshot 2019-01-13 at 13 37 40" src="https://user-images.githubusercontent.com/1682452/51085433-58172f80-1739-11e9-88c2-7af65ed92b76.png">

When hovered, it displays a tooltip with the block type ("Reusable block:") and the saved name of the block:

<img width="890" alt="screenshot 2019-01-13 at 13 48 40" src="https://user-images.githubusercontent.com/1682452/51085460-00c58f00-173a-11e9-9973-9bddde2a02dd.png">

Although the Reusable Block Indicator appears only on hover, the saved name appears also when tabbing into the block, so let's say this is fine for keyboard users:

<img width="909" alt="screenshot 2019-01-13 at 13 51 05" src="https://user-images.githubusercontent.com/1682452/51085511-ab3db200-173a-11e9-8af1-861e85a26a13.png">

However, when hovering, the block "breadcrumb" appears too: the combined effect of two things appearing in the same spot doesn't look so nice and maybe could be improved:

<img width="343" alt="screenshot 2019-01-13 at 12 10 53" src="https://user-images.githubusercontent.com/1682452/51085543-623a2d80-173b-11e9-92a0-aa26ab05f6d0.png">

Worth also considering making information available only on hover it's pointless on touch devices and mobile. Overall, I'd propose to consider to make this information available elsewhere in the block.

**Comment by kjellr** [comment]
I wonder if we can just remove that indicator icon. These blocks already have a dotted border, which makes them distinct from standard blocks. 

<img width="794" alt="frame" src="https://user-images.githubusercontent.com/1202812/53024586-4d814180-342d-11e9-82e1-1d0a5bfc1e8c.png">

Either way, we should just rely on the standard block label on hover, and add the block's custom name into it: 

<img width="794" alt="frame-1" src="https://user-images.githubusercontent.com/1202812/53024600-5114c880-342d-11e9-8430-fda44471b7ec.png">

For greater clarity, we could also include a "Reusable Block" label before the name in the selected state: 

<img width="794" alt="frame" src="https://user-images.githubusercontent.com/1202812/53024742-a3ee8000-342d-11e9-8233-6e4ef27c2ba1.png">

**Comment by mapk** [comment]
This was talked about in the Design weekly triage meeting today. Let's drop the tip and just show the more detailed label similarly to how columns does it right now.

![Screen Shot 2019-04-16 at 9 10 18 AM](https://user-images.githubusercontent.com/617986/56226189-9ae1ef80-6027-11e9-843c-15a817204d1e.png)

I do like how @kjellr shows a colon `:` instead of an arrow in the example above because this isn't a nested column, but rather a name given to the reusable block.

**Comment by paaljoachim** [comment]
I like the @kjellr idea of adding Resuable Block: Example Name.
What if we just get that added?

**Comment by mapk** [comment]
This was raised again in [today's design triage](https://wordpress.slack.com/archives/C02S78ZAL/p1585672115117200).

I double checked and it looks like this isn't an issue anymore since the introduction of the new UI. There is no more indicator. For this reason, I'm going to close this issue.

![reusable](https://user-images.githubusercontent.com/617986/78051561-b6c2cc00-7332-11ea-86d9-fb2e225266a0.gif)
