### ISSUE TITLE
block encountered error, cannot be previewed

### ISSUE THREAD

**Issue by BlameDutchie** [WordPress/gutenberg#13304]
Posts with a jetpack Tiled Gallery.
Convert to Blocks.
Block with gallery shows the error.

Have an unconverted post with jetpack tiled gallery:
Goto editor toolbar.
Click the dots, select Convert to Blocks.
See error.

**Expected behavior**
Editor should show gallery.

**Screenshots**
![block_encount](https://user-images.githubusercontent.com/12746371/51084456-cbad4280-1721-11e9-9d29-5ee961dc35bc.jpeg)

**Desktop:**
 - OS: MacOS 10.13.6
 - Browser: Chrome, Safari, Firefox Devel, Opera
 - All most recent versions

**Additional context**
Wordpress 5.0.3, no classic editor plugin.

**Comment by talldan** [comment]
Hi @BlameDutchie. Thanks for reporting this, and apologies no one got back to you sooner.

Your issue was discussed during a bug triage session (slack link, needs signup/account):
https://wordpress.slack.com/archives/C02QB2JS7/p1565245504313100

It looks as though this has been resolved now. Just a note, jetpack issues can be reported here:
https://github.com/Automattic/jetpack/issues

There is a new related issue, the block now converts to a normal gallery, that's tracked here:
https://github.com/Automattic/jetpack/issues/12903
