### ISSUE TITLE
Gutenberg will not update when permalinks are changed from plain

### ISSUE THREAD

**Issue by suzupetal** [WordPress/gutenberg#13338]
this darn site is not very user friendly sorry for closing and now opening one...

When i attempt to change the permalinks to something other than "Plain", gutenberg will not update a page or post. I have gone down the list of ways to change them and each one gives me an error.

**Comment by designsimply** [comment]
Based on your description so far, it sounds like you may have a web server configuration that isn't compatible with the permalinks _and_ Gutenberg for some reason. Gutenberg utilizes the REST API whereas the old editor did not, so this may be a REST API problem surfaced by Gutenberg using the REST API.

It would help to know:

1. How are rewrites configured for your web server? See  https://github.com/WordPress/gutenberg/issues/12655#issuecomment-445816958 for a sample nginx rule.
* Exactly what errors do you see?
 * When you try to update a post, do you see any errors in the console panel inside your browser's web developer tools?
 * Are you able to find any related errors in your web server logs corresponding to similar timestamps when you see the problem happen in the editor?

> I have gone down the list of ways to change them and each one gives me an error.

What list? What are the errors?

Thanks for reporting this btw! And thank you for taking the time to work through the problem here as it will hopefully help others if we can work together to get to a solution for you and document it.

**Comment by youknowriad** [comment]
It looks like this has some good leads. Closing for now.
