### ISSUE TITLE
Wordpress 5.0.3 not show page template

### ISSUE THREAD

**Issue by Tungnpyoungworld** [WordPress/gutenberg#13355]

**Comment by youknowriad** [comment]
Can you provide more details? Everything is fine by default.

**Comment by brandonconn03** [comment]
I am experiencing the same issue on a site I admin. After the 5.0.3 update, the testimonials template and a custom 'staff' template are no longer showing.  

![dashboard](https://user-images.githubusercontent.com/18543006/52069219-4f519680-254c-11e9-8571-95c7160b5e38.PNG)

**Comment by youknowriad** [comment]
Were you able to find a solution here? or exact steps to reproduce?

**Comment by brandonconn03** [comment]
> Were you able to find a solution here? or exact steps to reproduce?

No, I have not been able to locate a solution.

**Comment by aduth** [comment]
@brandonconn03 Is the theme you're using publicly available so that a developer could try to reproduce the issue in their own environment? At the very least, could you share the first few lines of the template file (`page-testimonials.php`) which include the [page template comment](https://developer.wordpress.org/themes/template-files-section/page-template-files/#creating-custom-page-templates-for-global-use)?

For debugging context, the available templates are generated using the same mechanism as would have been done in the previous editor (`WP_Theme::get_page_templates( $post_id )`, [source](https://github.com/WordPress/wordpress-develop/blob/7bdef3d3ef7b4eca799ca43c2c456f29e6213a0d/src/wp-admin/edit-form-blocks.php#L150-L161)).

Could you try to see what happens when you enter the following snippet into your [browser's Developer Tools Console](https://developers.google.com/web/tools/chrome-devtools/console/), if you're able?

```
wp.data.select( 'core/editor' ).getEditorSettings().availableTemplates
```

**Comment by youknowriad** [comment]
I'm going to close as it doesn't seem like we can reproduce at the moment.

Let's reopen if we manage to get details about how to reproduce the issue.
