### ISSUE TITLE
How to add events in saved block

### ISSUE THREAD

**Issue by stevensullivan** [WordPress/gutenberg#13378]
I have this component

```
class CallToAction extends Component {
  handleChange() {
    console.log('changed');
  }

  render() {
    return (
      <input type="text" value={ this.props.cta } onChange={ this.handleChange }/>
    );
  }
}
```

When I include it in the edit: method of my block, the onChange fires and logs ‘changed’ as expected

When I include it in the save: method of my block, it does not work.

Why is this? Is there something special I have to do to make event handlers work?

**Comment by swissspidy** [comment]
The render callback just returns the HTML that is saved to the database and on displayed on the front end.

Your onChange callback won't fire on the front end because your `CallToAction` component is not loaded there.

If you need interactive components on the front end, you need to enqueue your JS (and its dependencies) there by hooking into `wp_enqueue_scripts` and using `wp_enqueue_script()`

**Comment by designsimply** [comment]
Closing this since an answer was provided and noting we can re-open if needed.

Also would love to check in with you @stevensullivan that you have the info you need to go forward with your work!
