### ISSUE TITLE
Hide a block from being previewed on the front end.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#13373]
We can easily add a hide block option to the ... (three dots block option) contextual drop down menu.

Use Case: One tests out different layouts to see how they look. Instead of deleting blocks one could just hide them from frontend view. One might also need to test out various text and instead of deleting one can hide the block or blocks from view. 
Thinking forward. 
Making the title into a block that can not be deleted, but it can be moved around the layout. It can also be hidden from being seen on the frontend.

Here is how I see it.

From this:
![screen shot 2019-01-19 at 18 22 42](https://user-images.githubusercontent.com/5323259/51430164-404b1a00-1c17-11e9-9846-079d5440a6fd.png)

![screen shot 2019-01-19 at 18 29 19](https://user-images.githubusercontent.com/5323259/51430211-2a8a2480-1c18-11e9-87e1-2b442ce5af46.png)

To this:
![gutenberg-hide-block-dropdown](https://user-images.githubusercontent.com/5323259/51430422-8efab300-1c1b-11e9-8de2-d07d5bb3ae22.jpg)

A hidden block seen in the backend in Gutenberg:
![gutenberg-hidden-block](https://user-images.githubusercontent.com/5323259/51430230-6b823900-1c18-11e9-989c-ebae8a8a259d.jpg)

This option could also easily hide the title block for being seen on the frontend. https://github.com/WordPress/gutenberg/issues/4573

@mapk @jasmussen @melchoyce @jwold

**Comment by kjellr** [comment]
Thanks for sharing, @paaljoachim. My initial reaction is that this seems to tackle a somewhat uncommon use case, and may not make sense to be included in core. It _would_ on the other hand, make a fantastic plugin.

A small purely visual note to add: If we did pursue this, we'd need to aovid dimming out unused blocks: this convention is already used in "Spotlight Mode", so this would conflict.

**Comment by paaljoachim** [comment]
I do agree with you Kjell. At present time it will probably fit better in a plugin then in core.

**Comment by brandbrilliance** [comment]
This is something we might need to add to the gutenberg core. When I search for this feature, I can't locate anything do with Front-End hide/show, since all the plugins are focussed on actually hiding the actual block from the Back-end user – which of course, is a completely different function. We don't want to hide the block from the client, we want to add the block to the layout, show the client how it will work and then "activate" the visibility on the Front-End, so they can quickly go-live. It would also be nice to show the block in preview mode somehow, but not on the front-end live page. This is helpful when building pages for clients and as they bring their content.

**Comment by paaljoachim** [comment]
Check out this discussion:
**Allow users to hide blocks based on various contexts**
https://github.com/WordPress/gutenberg/discussions/67661
