### ISSUE TITLE
Inline image in table, but no caption, no link

### ISSUE THREAD

**Issue by Gerard8** [WordPress/gutenberg#13382]
In the classic editor, I could insert html code for a table, then put images (with a caption) in the table, and attach a link to that image. With the Gutenberg editor, it is now easy to include a table, and I have found the way to include an image in a cell (inserting an inline image). However, sofar I have not found a way to attach a caption to such an inline image, nor is it possible to attach a link. Is there a solution for this problem?
Examples for comparison:
Classic editor:  https://gejoweb.wordpress.com/nostronica-3/
Gutenberg editor: https://gejoweb.wordpress.com/alt-nostronica/

**Comment by Gerard8** [comment]
Additionally: after a change of theme, the size of the images (all 200 x 150 pixels) are no longer the same. Initially, Initially, while creating the table with the inline images, I could 'create' room in the table cells through enserting some blank lines underneath the inline image, and then resize the image to its proper size. This 'trick' no longer works after the theme change. It appears, that I have to start from scratch. Would appreciate a better way to control the size of the inline images.

**Comment by Gerard8** [comment]
Addionally, could it be made possible to include a 'List' (bulleted) as an inline element?

**Comment by Gerard8** [comment]
Addionally, could it be made possible to include a 'List' (bulleted) as an inline element?

**Comment by Gerard8** [comment]
Addionally, could it be made possible to include a 'List' (bulleted) as an inline element?

**Comment by talldan** [comment]
#13154 is an open issue for adding lists to table cells.

I don't think the table block is likely to have full image support any time soon, so I'm removing the `[Block] Table` label from this issue. 

The examples above look like the table is being used to lay out other content, in this case displaying images in a grid. The table block's main use case is to support display of tabular data, and an arrangement of images doesn't fit that use case. 

There is still a chance that the inline image might support links and captions in the future, in which case it would work.

@Gerard8 If there were other options in the editor for the layout of images in a grid, would you consider using them instead of a table?

There are some options that currently exist that might be close to that goal:
- The gallery block can display images in a grid, but there's no way to add links from an image to an ad-hoc page.
- The columns block supports adding inner image block and links can be added to those images. Vertical alignment can be used to tidy things up. The columns don't support grid lines.
- There are third party blocks that support grid layouts in the plugin directory. They seem to be fairly similar to the columns block with one or two exceptions. Images and links can be added.

**Comment by Gerard8** [comment]
Thank you very much for your comments! I will certainly investigate the mentioned, currently existing options. In due course, I'll select the option that suits me best, i.e. that comes closest to the present (classical) possibilities

**Comment by ellatrix** [comment]
There's currently no intention to support captions for inline images. Let's close this in favour of #18768, the proposal there might make it possible to have an image block in a table.

**Comment by pattihis** [comment]
@talldan says:

> The table block's main use case is to support display of tabular data, and an arrangement of images doesn't fit that use case.

A fair usage example would be adding logos of clients/products/companies in a comparison table listing their data and a link would be needed to take the user to the item's single page. A similar example would be a Top10 ranking table where we would list eg. brand logos. Another usage would be icons, like a "View More" action icon in a data table that would need a link.

@ellatrix says:

> There's currently no intention to support captions for inline images

Yes but what about links? Links on inline images are definitely needed, as explained in the examples above. Hope this is re-considered, thanks.

**Comment by talldan** [comment]
> Yes but what about links? Links on inline images are definitely needed, as explained in the examples above. Hope this is re-considered, thanks.

@pattihis You can already link an inline image. Insert it first, select it, and then apply link formatting.
