### ISSUE TITLE
Get Block Attributes durning parse_query or other early hooks

### ISSUE THREAD

**Issue by Keith-Cancel** [WordPress/gutenberg#13433]
Is there a good way to read all saved block attributes during the parse_query? I can pass the queried_object post content to the WP_Block_Parser class, but it seems like the blocks are parsed later since the attributes are passed to the dynamic rendering callback.

The reason I ask as I searched around I see that a lot of the PHP api still seem to be in the works, and it seems wasteful to parse the post twice. So either I would like to pass off the what I parsed or trigger parsing so that I can both use the results and the block system can use it as well.

**Comment by swissspidy** [comment]
There's currently no way to prevent double-parsing like that. 

If you really need to parse blocks that early, manually use `do_blocks`.

**Comment by Keith-Cancel** [comment]
I ended for now using [parse_blocks](https://developer.wordpress.org/reference/functions/parse_blocks/) and recursive go through all options. Although, still strikes me wastefully having no way to avoid double parsing.

**Comment by designsimply** [comment]
Closing since it appears an answer was provided and a solution was also mentioned (even though it was also stated the solution may be wasteful because of double parsing).

We are working to [move help requests to support forums](https://github.com/WordPress/gutenberg/issues/new?template=Custom.md) in order to focus the work here in the repo on new development. Because of that, may I please ask that you post to https://wordpress.org/support/forum/wp-advanced/ or at https://wordpress.stackexchange.com/ to discuss this further if you'd like to explore other potential solutions that might be less wasteful? Thank you so much!

**Comment by Keith-Cancel** [comment]
Is there any plans to provide the pre-parsed array from the pare_blocks function look hook that can be called when parsing is initiated and if hook returns data use that instead?

**Comment by swissspidy** [comment]
@Keith-Cancel I'm not aware of any direct plans, but I'm sure some hooks and filters could be added. Feel free to create a ticket on https://core.trac.wordpress.org/ with your suggestion!
