### ISSUE TITLE
Documentation of components should include discussion of their counterparts from @wordpress/editor.

### ISSUE THREAD

**Issue by pbiron** [WordPress/gutenberg#13465]
**Is your feature request related to a problem? Please describe.**
For all components (from `@wordpress/components`) that have a counterpart in `@wordpress/editor`, their documentation should have a discussion of their counterpart, including when it is appropriate to use one or the other.

See the Slack discussion starting at https://wordpress.slack.com/archives/C02QB2JS7/p1548285638344400 for context.

Here is some background.

Based on [ServerSideRender ](https://wordpress.org/gutenberg/handbook/designers-developers/developers/components/server-side-render/) from the handbook, I created a dynamic block that imports the `ServerSideRender` component from `@wordpress/components`.  All was working fine for several months, both in the editor and on the front-end.

Recently, I modified the `render_callback` function for the block such that it needs the global `$post` variable to be set to the post containing the block in order to work properly.  And was shocked to find out it isn't set when the `block-renderer` endpoint is called by the editor (but it is set when called on the front-end).

So I asked in Slack whether something had changed.  @pento quickly diagnosed the problem: I need the JS side of the block to import `ServerSideComponent` from `@wordpress/editor` and **NOT** `@wordpress/components` (as described in the handbook (at the link above, and in the [Creating dynamic blocks](https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/block-tutorial/creating-dynamic-blocks/).

I had no idea that `ServerSideComponent` from `@wordpress/editor` even existed...because as far as I can tell, it is mentioned **nowhere** in the handbook.

**Describe the solution you'd like**

Various parts of the handbook should be updated to include discussions of when to use components from `@wordpress/components` and when to use their counterparts from `@wordpress/editor`.

In addition to `ServerSideRender`, @pento mentioned in Slack that:

> From a quick glance, `Autocomplete` and `ColorPalette` jump out, then I didn’t bother trying to compare the lists further.

**Comment by skorasaurus** [comment]
+1 this, I'm confused on this myself as I'm learning and struggling the differences between the two packages and when to look in one place over the other. 

(the editor package has been renamed to block-editor since issue was created) 

as of now, there are 3 components that have shared names in the block-editor package ([within a subfolder named components](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/)) and [the components](https://github.com/WordPress/gutenberg/tree/master/packages/components/) package:

Autocomplete - docs in block-editor package detail the difference. 

color-palette 

keyboard-shortcuts - also has its own separate package, @[wordpress/keyboard-shortcuts
](https://developer.wordpress.org/block-editor/packages/packages-keyboard-shortcuts/)

**Comment by pbiron** [comment]
@mburridge thank you for addressing this after all this time!  appreciate it
