### ISSUE TITLE
Bump PHP minimum to 5.6

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#13478]
Hi,
WordPress is bumping the PHP minimum to 5.6 in the next WP major version (5.2).
See: https://make.wordpress.org/core/2018/12/08/updating-the-minimum-php-version/

All new code we add to Gutenberg will be released in WordPress 5.2 or later. Does it make sense to add extra lines, to become compatible with PHP 5.2 or should ne bump the minimum for the plugin to 5.6?

Comment wich started this discussion: https://github.com/WordPress/gutenberg/pull/7966#discussion_r250465953

**Comment by aduth** [comment]
Related Slack conversation ([link requires registration](https://make.wordpress.org/chat/)):

https://wordpress.slack.com/archives/C02QB2JS7/p1548322703377100

**Comment by EldarAgalarov** [comment]
PHP 5.2 is too old. Just bump to 5.6 without any compatibility with 5.2.

**Comment by pento** [comment]
I'm inclined to leave it at PHP 5.2 for now.

PHP in the parser and block packages will need to stay as PHP 5.2, because those files are imported into core, and we may need to do a WordPress 5.1.x release that includes changes to them.

It doesn't matter so much for other PHP, but then you're looking at maintaining two different levels of PHP support, depending upon what file you're editing.

As much as I'm excited about dropping PHP 5.2, it won't hurt to maintain it for a few more months.

**Comment by Soean** [comment]
Thanks for your feedback. So let's wait 👍
