### ISSUE TITLE
Help using withSelect

### ISSUE THREAD

**Issue by mathishuettl** [WordPress/gutenberg#13475]
Hello,

I don't know how to use withSelect() what is it... a promise? And why do I have to pass a Object at the end? Is there a docu somwhere? and what does it exactly? With trial and error I could now query posts, but I struggle when I want to get a posts category. Can you help me please?

```
class TravelCategories extends Component {
	
	static getCategory ( categoryId ) {
		// how to get category title here?
	}
		
	render() {
            const { posts } = this.props;

            const hasPosts = Array.isArray(posts) &&  posts.length;

            if (!hasPosts) {
                return ()
            }
			
            return (
                <div>
					{ posts.map( ( post, index ) => (
						<div className="col-md-4">
							<h3>{ post.title.rendered }</h3>
							{ TravelCategories.getCategory( post.categories[0] ) }
						</div>
					) ) }
                </div>
            );
        }
}
edit: withSelect ( ( select, props ) => {
	const { getEntityRecords } = select("core");

	const postQuery = {
		postType: "reisen"
	};

	return {
		posts: getEntityRecords("postType", "reisen", { } )
	}
} ) (TravelCategories),
```

**Comment by swissspidy** [comment]
`withSelect` is a so-called **higher order component** (HOC). A HOC is a function that takes a component and returns a new, enhanced component. That's why you pass an object (your existing component) to it.

You can learn more about Higher Order Components here: https://wordpress.org/gutenberg/handbook/designers-developers/developers/components/higher-order/

https://wordpress.org/gutenberg/handbook/designers-developers/developers/packages/packages-data/ has an example specific for `withSelect`

**Comment by youknowriad** [comment]
Thanks for the reply @swissspidy
