### ISSUE TITLE
Why my facebook embed show in German (de_DE)

### ISSUE THREAD

**Issue by JustineBABY** [WordPress/gutenberg#13525]
Hello,

I'm new in Gutenberg, but i'm very happy for usign this official wordpress editor. But I have a question, about the Facebook embed show.

I think that all my WP site is configured to the English language, and when I embeded a facebook link in Gutenberg Embed Block, it show it in German (de_DE).

This is the code source from the Gutenberg facebook embed block:

```
<figure class="wp-block-embed-facebook wp-block-embed is-type-video is-provider-facebook"><div class="wp-block-embed__wrapper">
<div id="fb-root"></div><script>(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src='https://connect.facebook.net/de_DE/sdk.js#xfbml=1&version=v3.2';fjs.parentNode.insertBefore(js,fjs);}(document,'script','facebook-jssdk'));</script><div class="fb-video" data-href="https://www.facebook.com/OM/videos/2135948819801714/" data-width="1200"><blockquote cite="https://www.facebook.com/OM/videos/2135948819801714/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/OM/videos/2135948819801714/">Mercato &#8211; Balotelli</a><p>Level completed ✅ #OMnation</p>Gepostet von <a href="https://www.facebook.com/OM/">Olympique de Marseille</a> am Mittwoch, 23. Januar 2019</blockquote></div>
</div></figure>
```
Thank before for repply.

**Comment by Soean** [comment]
I don't think it's an Gutenberg/WordPress issue. The editor is not adding any language settings.
Maybe it because of your IP or facebook account? I can't test the issue because i am located in Germany.

cc @notnownikki Any idea here?

**Comment by notnownikki** [comment]
The embed block just sends the URL to FaceBook's oEmbed service, and displays whatever it gets back, Gutenberg doesn't add any locale or language information to it. The documentation on FaceBook oembed shows that it doesn't support language or locale parameters, so  think that FaceBook tries to detect what country the request is coming from and return the language based on that. If your web host is in Germany, FaceBook is going to see the request coming from Germany and return German content.

The URL that WordPress calls to get the embed response from FaceBook is `https://www.facebook.com/plugins/video/oembed.json/?maxwidth=600&maxheight=960&url=https%3A%2F%2Fwww.facebook.com%2FOM%2Fvideos%2F2135948819801714%2F&dnt=1&format=json` which returns `en_GB` content for me, probably because I'm in the UK.

**Comment by Soean** [comment]
Thank you for your explanation 👍
I am going to close this ticket, because there is nothing we can do about the language.

**Comment by JustineBABY** [comment]
I'm in France, my host is in Switzland, but I use the cloufrare. So my WP site ip is in USA by cloudflare and nothing to do with Germany. Why this facebook block show in german? Where does this script come from: 

`<div id="fb-root"></div><script>(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src='https://connect.facebook.net/de_DE/sdk.js#xfbml=1&version=v3.2';fjs.parentNode.insertBefore(js,fjs);}(document,'script','facebook-jssdk'));</script>`

Because, I only entered the link of the video in the Gutenberg facebook block. It's very strange?

Best.

**Comment by notnownikki** [comment]
That script comes directly from FaceBook. All WordPress does is ask FaceBook for the script needed to embed the video, and then WordPress outputs the script. WordPress does not change the language, and Facebook does not have any option to override or change the language, so this is an issue outside of WordPress.

**Comment by JustineBABY** [comment]
Thanks for repply.

I'm in France, my host is in Switzland, but I use the cloufrare. So my WP site ip is in USA by cloudflare and nothing to do with Germany. Why this facebook block show in german de_DE? Where does this script come from:

`<div id="fb-root"></div><script>(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src='https://connect.facebook.net/de_DE/sdk.js#xfbml=1&version=v3.2';fjs.parentNode.insertBefore(js,fjs);}(document,'script','facebook-jssdk'));</script>`

Best.

**Comment by JustineBABY** [comment]
Thanks for repply,

Now, I try this link: 

`https://www.facebook.com/plugins/video/oembed.json/?url=https://www.facebook.com/OM/videos/2135948819801714/`

It show: 

`{"author_name":"Olympique de Marseille","author_url":"https://www.facebook.com/OM/","provider_url":"https://www.facebook.com","provider_name":"Facebook","success":true,"height":500,"html":"\u003Cdiv id=\"fb-root\">\u003C/div>\n\u003Cscript>(function(d, s, id) {\n  var js, fjs = d.getElementsByTagName(s)[0];\n  if (d.getElementById(id)) return;\n  js = d.createElement(s); js.id = id;\n  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.2';\n  fjs.parentNode.insertBefore(js, fjs);\n}(document, 'script', 'facebook-jssdk'));\u003C/script>\u003Cdiv class=\"fb-video\" data-href=\"https://www.facebook.com/OM/videos/2135948819801714/\">\u003Cblockquote cite=\"https://www.facebook.com/OM/videos/2135948819801714/\" class=\"fb-xfbml-parse-ignore\">\u003Ca href=\"https://www.facebook.com/OM/videos/2135948819801714/\">Mercato - Balotelli\u003C/a>\u003Cp>Level completed \u2705 #OMnation\u003C/p>Posted by \u003Ca href=\"https://www.facebook.com/OM/\">Olympique de Marseille\u003C/a> on Wednesday, January 23, 2019\u003C/blockquote>\u003C/div>","type":"video","version":"1.0","url":"https://www.facebook.com/OM/videos/2135948819801714/","width":500}`

Which returns `us_US`

**Comment by notnownikki** [comment]
Yes, for me and my install of WordPress, it returns `en_GB`, and if I access it from my server in the US, it returns `us_US`. It could be an issue with Cloudflare, if they send out requests from servers worldwide, or if they cache requests and have cached one from Germany? Or it could be an issue with Facebook? We can't help with either of those things though, because all WordPress does it make the request and return whatever Facebook gives us.
