### ISSUE TITLE
ColorPalette not showing default colors

### ISSUE THREAD

**Issue by JustusL** [WordPress/gutenberg#13537]
I just tried using a ColorPalette for my Custom Block Plugin but instead of showing the default colors I have just been able to see the custom color wheel.

Implementation looks like this:
`const { ColorPalette } = wp.components`
`//...`
`<Fragment>`
    ` <InspectorControls>`
        `<PanelBody>`
            `<PanelRow>`
                `<label>My color:</label>`
                `<ColorPalette/>`
            `</PanelRow>`
        `</PanelBody>`
    `</InspectorControls>`
    `<div>`
`//...`
    `</div>`
`</Fragment>`

And I get this as an output:
![error](https://user-images.githubusercontent.com/34372092/51841083-10ce9880-230e-11e9-8b30-a6c6e742b68e.png)

I would be grateful for any kind of help :)

**Comment by jorgefilipecosta** [comment]
Hi @JustusL, In order to have editor defaults the plugins need to use wp.editor.ColorPalette instead of wp.components.ColorPalette. The wp.components is a low-level version that allows the component user to set its own defaults.
I'm closing the issue for now, if you have additional questions feel free to reopen.

**Comment by ETVO** [comment]
Hello, I am facing the exact same issue. I tried using `wp.editor.ColorPalette` and `wp.blockEditor.ColorPalette`, but the default value is still not being saved.
