### ISSUE TITLE
Cant get data on first invocation  on wp.data.select( 'core' )

### ISSUE THREAD

**Issue by snnsnn** [WordPress/gutenberg#13555]
Im an not sure if it is a bug or I am missing some settings but on chrome, `wp.data.select( 'core' )` methods returns null on first invocation but works as expected for subsequent invocations. Behavior is consistent for programmatic and browser console calls.

Blocks are working fine.

I'm running WordPress 5.0.3 with  twenty nineteen theme and without any plugins. Server runs on official wordpress container. 

Version 71.0.3578.98 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/16473630/51876163-b159a280-2378-11e9-889c-290ea5cbd5f7.png)

On firefox, first invocation returns error, subsequent ones returns null
Firefox 64.0 (64-bit) on Linux

![image](https://user-images.githubusercontent.com/16473630/51876308-3f358d80-2379-11e9-9b2f-2068e1c599bb.png)

**Comment by youknowriad** [comment]
The error in firefox needs to be investigated but otherwise, that's the expected behavior as these selectors trigger async requests, if you want to stay up to date with the value of a given selector, you need to "subscribe" (wp.data.subcribe) to the registry or use `withSelect` which takes care of this for you.

**Comment by youknowriad** [comment]
I just tried on Firefox, and it's working properly for me. Might be related to plugins or something else.

**Comment by snnsnn** [comment]
Ok. Thanks.
