### ISSUE TITLE
"Latest Posts" blocks need "pagination"/"Load more" feature

### ISSUE THREAD

**Issue by murshed** [WordPress/gutenberg#13584]
Need pagination feature or load more button on the "Latest Posts" blocks

<img src="https://i.imgur.com/49FvMDS.png"/>

**Comment by paaljoachim** [comment]
Hey @murshed 

Version 2 of the Latest Posts block is being worked on these days:
https://github.com/WordPress/gutenberg/issues/1594

**Comment by murshed** [comment]
Still not added on 5.1 (RC)
<img src="https://i.imgur.com/iMjP1hF.png"/>

**Comment by duyngha** [comment]
is there anyone have a temporary workaround for this?

**Comment by paaljoachim** [comment]
For the time being I would suggest to use the plugin Custom Post Blocks: https://wordpress.org/plugins/post-type-archive-mapping/
I use it on a bunch of sites as it offers a lot of really useful features.

**Comment by duyngha** [comment]
> For the time being I would suggest to use the plugin Custom Post Blocks: https://wordpress.org/plugins/post-type-archive-mapping/
> I use it on a bunch of sites as it offers a lot of really useful features.

Thanks @paaljoachim

I will give it a try

**Comment by duyngha** [comment]
> For the time being I would suggest to use the plugin Custom Post Blocks: https://wordpress.org/plugins/post-type-archive-mapping/
> I use it on a bunch of sites as it offers a lot of really useful features.

This plugin works exactly what I want. Thanks again for your suggestion @paaljoachim

**Comment by murshed** [comment]
been 1 year and no one takes care of this issue.

**Comment by paaljoachim** [comment]
Hey @murshed bring it up during the Core Editor chat tomorrow, and hopefully that will help. There is a need for a developer to create a PR and get this feature in.

**Comment by murshed** [comment]
Thanks so much, Paal Joachim Romdahl.

**Comment by eviolini** [comment]
This issue was discussed during the weekly [Core Editor meeting on 18 December, 2019](https://make.wordpress.org/core/2019/12/18/editor-chat-summary-wednesday-18-december-2019/). Two approaches were brought up as potential solutions — first as a setting option, the second as a stand-alone block that could be placed by the user and moveable. 
**As a setting option —**
From an experience perspective, most site editors may not recognize the need to include pagination as a page element. Including it as a setting removes friction for the end user simplifying the UX. The drawback as a setting is it doesn't allow the user to position or move the pagination element if desired.    
**As a stand-alone block —**
Pagination could be a block because it is a visual element that is needed for query blocks, posts blocks, archive templates, top level index templates with post lists. The functionality could be developed in such a way that if it is used stand-alone it would default to paginating the default post loop for the page, while other blocks might opt to use it by default (e.g. the latest posts block). The drawback as a standalone element is how is the the stand-along block configured in relation to the parent block.

**Comment by joyously** [comment]
I don't agree that this is a **need**. The block is for showing the _Latest_ posts, not **all** the posts. It should show the latest and that is it. No pagination or More link is needed.

**Comment by murshed** [comment]
> I don't agree that this is a **need**. The block is for showing the _Latest_ posts, not **all** the posts. It should show the latest and that is it. No pagination or More link is needed.

I appreciate your comment.

Already a plugin adding pagination feature.

![Getwid blocks](https://i.imgur.com/ZwVMPJE.png)

**Comment by paaljoachim** [comment]
This issue was brought up again in Todays Core Editor chat Slack channel during the Open Floor. 

Bottom line is this:

@youknowriad 
Mentioned: "this is related to the Query block question above. I believe this will be supported in the Query block. Maybe in the Latest post block but we should first figure out the Query block IMO."

@gziolo 
"what’s the difference between Query block and Latest Posts block in one sentence? :)"

@youknowriad
"Query block doesn’t have a fixed output based on attributes, it uses InnerBlocks to render each “post”. So you could combine PostTitle, PostContent, PostExcerpt... Post* blocks as a template for each “Post” entry in the Query block. It’s the WordPress loop as a block"

Check the Slack link for additional information.
(you need to be logged in to be able to read) https://wordpress.slack.com/archives/C02QB2JS7/p1582728608092200

**Comment by enriquesanchez** [comment]
This issue was discussed during today's [Gutenberg design triage meeting](https://wordpress.slack.com/archives/C02S78ZAL/p1583859644277600).

We agreed that the 'Latest posts' block is OK the way it is. The moment we add pagination to it it stops being "latest posts" and becomes "all posts".

Seeing that there are other options to accomplish this (plugin and query block), we'll be closing this issue for now.

**Comment by thpglobal** [comment]
Wow - do I disagree with your decision. People should have this functionality out of the box - everyone needs it - and who would think to search for a block named "query" when your are replacing the display-posts shortcode?

**Comment by raulcraveiro** [comment]
If this block won't have pagination, than we should have a all posts block or a pagination block. It's so weird that I need to use a plugin to add such a basic feature.

**Comment by tuiuiudev** [comment]
> This issue was discussed during today's [Gutenberg design triage meeting](https://wordpress.slack.com/archives/C02S78ZAL/p1583859644277600).
> 
> We agreed that the 'Latest posts' block is OK the way it is. The moment we add pagination to it it stops being "latest posts" and becomes "all posts".
> 
> Seeing that there are other options to accomplish this (plugin and query block), we'll be closing this issue for now.

Hi there @enriquesanchez,

I'm sorry to be rhetorical here, but it looks like this solution for load more posts and/or pagination would be great in the Gutenberg plugin.

It is weird to receive an answer like this: _Seeing that there are other options to accomplish this_ 

If that phrase made any sense, Gutenberg itself shouldn't have been created in the first place, as there are other options for accomplishing what it is here to accomplish.

And if a big issue is the initial goal for "latest posts", then let's pivot it and make it "all posts".

Let's avoid workarounds by installing more and more plugins.

Thank you for considering my request. I look forward to a positive response.

Kind regards

**Comment by joyously** [comment]
I don't normally agree with the team's decisions, but I do with this one. 
The Latest Posts block should show only the Latest. This comes from the Recent Posts widget. 
There is another block that allows full access to the query, which doesn't have a widget counterpart. Its counterpart is using a plugin or the main query of WP itself.
There is one topic that is very common on the forums, and that is "why is the pagination messed up?" 
The pagination functions use some global variables that go with the main query, so any plugins or theme that affect those can mess up the pagination.
