### ISSUE TITLE
Insert Link: consider adding the post type for pages and CPTs or the date for posts in suggested link search results

### ISSUE THREAD

**Issue by designsimply** [WordPress/gutenberg#13641]
Requested in #9660.
Mentioned at https://github.com/WordPress/gutenberg/issues/6392#issuecomment-419289220.

Consider adding the post type (e.g. Page, CPT name, or the date for posts) on the right for suggested links similar to how the classic editor does:

![screen shot 2017-07-29 at 17 39 06](https://user-images.githubusercontent.com/1682452/28746065-5593b8f8-7485-11e7-9cc7-ab9ce4993130.png)
<sup>Example screenshot from #2084 showing how post types are listed in link suggestions in the classic editor.</sup>

**Comment by chrisvanpatten** [comment]
I would love this - even better if there's a way to build it into the REST API search endpoint as a "Secondary Search Context" label (or something like that) which could be filtered so post types could provide their own helpful string, similar to how the built-in "Post" post-type shows a date instead of the post type name.

**Comment by edwinhamers** [comment]
+1 for me.. Sorry to open my own issue for it!

https://github.com/WordPress/gutenberg/issues/16534#issuecomment-510464477

**Comment by sarahmonster** [comment]
There are some mockups that relate to this on #8573.

**Comment by mtias** [comment]
This has been implemented. For reference:

![image](https://user-images.githubusercontent.com/548849/91657313-517d2d80-eac0-11ea-90a9-f9c3f991ab5d.png)
