### ISSUE TITLE
Image caption alignment in wrong position.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#13684]
**Describe the bug**
Default alignment for image. Add caption. It shows up in the wrong place.

**To Reproduce**
1. Add an image.
2. Add a caption.
3. See if it aligns correctly with the image or if is aligns with the white image block space area.
4. Also check the frontend.

**Expected behavior**
Video embed caption code is now finally aligning captions correctly. 
https://github.com/WordPress/gutenberg/issues/11441

**Screenshots**
Backend Gutenberg:
![screen shot 2019-02-05 at 23 15 10](https://user-images.githubusercontent.com/5323259/52312953-ed11ef00-29ac-11e9-8de9-e86152a53858.png)

Aligns to the white image block space and not the image.
![screen shot 2019-02-05 at 13 19 49](https://user-images.githubusercontent.com/5323259/52312961-f56a2a00-29ac-11e9-873e-7d4a7489ca20.png)

I wrote caption centered. For the caption is centered to the white image block space and not the image itself.
![screen shot 2019-02-05 at 13 20 08](https://user-images.githubusercontent.com/5323259/52312996-129ef880-29ad-11e9-9aae-6e69ef67c3b4.png)

Frontend
![screen shot 2019-02-05 at 13 20 22](https://user-images.githubusercontent.com/5323259/52313008-2b0f1300-29ad-11e9-8597-eefdce9ad0b0.png)

**Desktop (please complete the following information):**
 Mac OSX 10.13.6
Chrome
Gutenberg version 4.9.

@youknowriad

**Comment by draganescu** [comment]
Hi @paaljoachim I was able to reproduce this only when selecting "Image Size" from the inspector.

<img width="936" alt="screenshot 2019-02-18 at 17 59 53" src="https://user-images.githubusercontent.com/107534/52962936-30a22b00-33a7-11e9-86e3-4c966721c3f3.png">

If I resize using the handles the caption remains centered to the image:

<img width="577" alt="screenshot 2019-02-18 at 18 02 38" src="https://user-images.githubusercontent.com/107534/52963042-72cb6c80-33a7-11e9-9fcf-79a6bfe45ae0.png">

Is this how you did it, using the Inspector "Image Size" dropdown or manually resized the image?

Also, the yep, misalignment is visible on frontend too.

**Comment by paaljoachim** [comment]
Hey @draganescu 

I just checked. Image has default alignment and the image is in full size mode.

Backend:
![screen shot 2019-02-18 at 17 33 14](https://user-images.githubusercontent.com/5323259/52964853-b328eb80-33a3-11e9-9c97-6773080acc01.png)

Frontend:
![screen shot 2019-02-18 at 17 33 33](https://user-images.githubusercontent.com/5323259/52964865-bb812680-33a3-11e9-879c-8d062904e724.png)

When I select Wide Width alignment then it looks correct.
![screen shot 2019-02-18 at 17 34 49](https://user-images.githubusercontent.com/5323259/52964917-dd7aa900-33a3-11e9-9120-3942b56d3b95.png)

**Comment by draganescu** [comment]
Apparently this is as intended: when the image is smaller than the block's box, but not floated (default align):

- the image's figure element gets a div wrapper 
- the figure and the figcaption elements are displayed as table and table caption respectively

This only happens if the image is resized or floated (aka has any other float rather than the default).

Maybe @jasmussen could chime in with some advice as to why we don't display the figure as table by default and the figcaption as table-caption **by default**, but only when the wrapper is present:

```
	.alignleft,
	.alignright,
	.aligncenter,
	&.is-resized {
		display: table;

		// The figure is born with left and right margin.
		// We remove this by default, and then customize it for left, right, and center.
		margin-left: 0;
		margin-right: 0;

		> figcaption {
			display: table-caption;
			caption-side: bottom;
		}
	}
```

Both in the editor and the front end using the table display for the figure and the figcaption elements by default, aligned or not aligned, resized or not resized, seems to work ok, but I am unsure yet if it yields other problems.

**Comment by jasmussen** [comment]
Okay had to walk down memory lane to find the reasons for this. 

Turns out we tried it, and punted it. https://github.com/WordPress/gutenberg/pull/7721#issuecomment-413845441

The pertinent bit:

> In general we use a `display: table;` trick to get the caption to size itself according to the image. This works because of the unique rules of the table. However if an unfloated image follows a floated image, this means the unfloated image can size itself down to "fit in the available space", which is not what we want.

As I mention in the comment there, it is worth revisiting. But it may not be as simple as just applying the table property to the image block across the board. So for any PRs you make, please be sure to try a multitude of different image size & float configuations. Notably:

[small image, floated, with big caption]
[small image, not floated, with big caption]

And be sure to compare before and after.

**Comment by paaljoachim** [comment]
I retested this by using various image alignments and the caption is now aligning correctly in Gutenberg and on the frontend. I will go ahead and close this issue.

**Comment by paaljoachim** [comment]
Resizing the image directly using the handlebars automatically adjusts the caption area. Resizing the image using medium or thumbnail does not adjust the caption.
I will add a new issue for this specific bug.

**Comment by sparkbold** [comment]
experienced the same issue.
