### ISSUE TITLE
Adjust the wording of smugmug embeds

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#13691]
I just tested the Smugmug block embed for 5.0 RC-1 and noticed that the wording could be changed:

"Sorry, this embedded content cannot be previewed in the editor."
Change to:
"Embedded content cannot be previewed in the editor."
Or 
"Smugmug embedded content cannot be previewed in the editor."

As the word "sorry" feels out of place.

@jasmussen 
@brentswisher

**Comment by jasmussen** [comment]
Great ticket, thank you!

**Comment by michelleweber** [comment]
Agree, no need to apologize here! "Smugmug embeds can't be previewed in the editor." works.

(If they can be previewed in the normal preview pane, you might consider adding that detail -- it's always nice to give people a positive next step when they hit an error or something doesn't work as expected.)

**Comment by jasmussen** [comment]
Fast work Michelle! This ticket is ready for a PR!

**Comment by paaljoachim** [comment]
Hey Michelle @michelleweber 

"Smugmug embeds can't be previewed in the editor." 
to me it feels better to spell it out...
"Smugmug embeds cannot be previewed in the editor."

**Comment by michelleweber** [comment]
We often go with contractions because they sound more conversational, but if you feel strongly feel free to spell it out.

**Comment by paaljoachim** [comment]
As a foreigner I do believe I use cannot more then can't. Can't to me is more American then cannot.

**Comment by jasmussen** [comment]
"Cannot" sounds as formal as "father" is to "dad" to me personally. But you bring up a really interesting point, Paal: should we start to create the outlines of a "voice and tone" guideline for the handbook? It could more or less describe the tone of descriptions and titles, how they can provide guides to translators, how long a description should be, do's and don't examples?

CC: @chrisvanpatten because that enters documentation territory. What do you think?
