### ISSUE TITLE
Transform Column Block to Table Block

### ISSUE THREAD

**Issue by msdesign21** [WordPress/gutenberg#13707]
**Is your feature request related to a problem? Please describe.**
Today I learned that a table block is a thing. Up until this point I had been trying to use the Column block, cursing at why I couldn't add data in rows. I wonder how many other people have this same confusion? 

**Describe the solution you'd like**
Perhaps one way to help with table block discovery could be to add the Table block to the Transform menu when the column block is selected: 
![http://cld.wthms.co/qYh9yD+](http://cld.wthms.co/qYh9yD+)
Direct Link: http://cld.wthms.co/qYh9yD 

If anything, it would make it easier for those that might want to transform their column block to a table quicker to do so. 

**Describe alternatives you've considered**
I don't know if it would be a good idea or not, but another idea I considered in terms of improving table block discovery: when using the block inserter: typing "column" could also display the table block: 

![http://cld.wthms.co/rEV1LL+](http://cld.wthms.co/rEV1LL+)
Direct Link: http://cld.wthms.co/rEV1LL 

I could see it breaking the pattern of typing to search exact block names, but I could also see the argument that columns can be found in the table block. If this is better as a separate issue, let me know. 

cc @designsimply in case she's also noticed any usability issues confusing a column block for a table block.

**Comment by designsimply** [comment]
I <em>have</em> seen usability testing where people try to use tables for layout when a gallery or column block would be more appropriate.

🤔 since, as a rule, tables are for data and columns are for layout, I can see why you might want to have a transform, or block conversion, from one to the other for cases where someone didn't know that distinction and switching between them would make it easier for them. Adding a `Needs Decision` label to get a 2nd opinion.

**Comment by mapk** [comment]
> since, as a rule, tables are for data and columns are for layout,

This, to me, seems the reason why not to allow transformation between the two. I think at least not yet. Right now, tables don't accept much beyond plain text while columns do. The transformation between the two could be problematic. I think as we improve the table block, maybe we can then look at allowing transformation between the two. 

Let's close this for now because of these reasons. We can always open it later. If you think I've missed something with this decision, just let me know.
