### ISSUE TITLE
warning when creating new page "implode(): Invalid arguments "

### ISSUE THREAD

**Issue by jmyt8** [WordPress/gutenberg#13875]
**Describe the bug:**
Block editor (Gutenberg) returns warning when creating new page.
<b>Warning</b>:  implode(): Invalid arguments passed in <b>../wp-admin/edit-form-blocks.php</b> on line <b>251</b><br />

**To Reproduce:**
Go to > Pages > Add new

**Additional context:**
editing existing pages show no warning.
problem existed on a multisite (wp version 5.0.2) with 4 sites. warning shows up in two exising sites and any new site created.
all plugins deactivated.

**Comment by aduth** [comment]
Since this is an issue in a core file (`wp-admin/edit-form-blocks.php`), it should be reported to Trac instead. I've created a Trac ticket, including some possible debugging hints (if it sounds familiar why for your site there may not be a post or user known for the created post).

https://core.trac.wordpress.org/ticket/47013
