### ISSUE TITLE
warning in firefox, deprecation

### ISSUE THREAD

**Issue by glorious1** [WordPress/gutenberg#13902]
**Describe the bug**
In javascript console when editing page in Firefox and WordPress 5.0.3, 
the following appear:
onmozfullscreenchange is deprecated. components.min.js:12:81117
onmozfullscreenerror is deprecated. components.min.js:12:81117

**To Reproduce**
Edit a page in Firefox 65.0.1
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox 65 and Safari 
 
**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by m-e-h** [comment]
Just noticed this as well. 
Some info:
https://www.fxsitecompat.com/en-CA/docs/2018/fullscreen-api-has-been-unprefixed/
https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API/Guide

**Comment by skorasaurus** [comment]
Still applicable in Gutenberg 9.8 ; more info at https://bugzilla.mozilla.org/show_bug.cgi?id=1504946

**Comment by FoobarProtocol** [comment]
No, this is not completed. Never got fixed. Would be nice if the powers that be at Firefox could be a browser capable of getting past a simple Cloudflare captcha. Getting sent in the infinite loop every single fucking time (even with all extensions disabled) is a fucking hassle and makes the browser as undesirable as it can get. 

I understand you all are open source, but Jesus Christ. Apply for another grant if that's what you all have to do in order to allow people to just browse the fucking internet like normal people.
