### ISSUE TITLE
Extending core block core/image block validation fails

### ISSUE THREAD

**Issue by cuckopl** [WordPress/gutenberg#13999]
Hi ,

I am writing plugin for wordpress 5. And i have problem with block validation . 

Everything works fine . Untill i add aligment for image.

![image](https://user-images.githubusercontent.com/8525055/53163770-22ceee80-35cf-11e9-8999-e3ea5cfd76f5.png)

I am adding extra attributes like it is written in documentation. I am adding to core/image block 3 extra attributes.

```// Register/add the new attribute.
const addExtraAttribute = props => {
    if (props.name !== ImageBlockName) {
        return props;
    }
    const attributes = {
        ...props.attributes,

        smartframe_caption: {
            type: "string",
            attribute: "smartframe_caption",
            default: "",
            selector: "figure",
            source: "attribute",
        },
        smartframe_theme: {
            type: "string",
            attribute: "smartframe_theme",
            default: "",
            selector: "figure",
            source: "attribute",
        },
        use_smartframe: {
            type: "string",
            attribute: "use_smartframe",
            default: "no",
            selector: "figure",
            source: "attribute",
        }
    };

    return {...props, attributes};
};

addFilter(
    "blocks.registerBlockType",
    "core/extra-attribute",
    addExtraAttribute
);
```

Next i add  extra props. 

```
const addExtraData = (props, blockType, attributes) => {
    if (blockType.name !== ImageBlockName) {
        return props;
    }

    return {
        ...props,
        ...{
            "smartframe_caption": attributes.smartframe_caption,
            "smartframe_theme": attributes.smartframe_theme,
            "use_smartframe": attributes.use_smartframe,
        }
    }
};

addFilter(
    "blocks.getSaveContent.extraProps",
    "my-plugin/extra-attribute",
    addExtraData
);
```

After that there is this strange validation problem. I try to find some answers on git but there wasn't any similar problem. I am doing something wrong ? Or this is just bug ?

wordpress 5.0.3 
Chrome Version 71.0.3578.98 (Official Build) (64-bit)
os:  Sierra macOS 10.13.6 (17G4015)

**Comment by youknowriad** [comment]
Hi There! noting that extensing the "save" function of core blocks is not recommended because it might result with validation errors when you enable/disable your plugin for the pre-existing content.

Alos, This tracker is not used for support requests though. For general help requests, please post in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/. Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.
Thank you!
