### ISSUE TITLE
Block gets stuck in HTML mode after deleting block content

### ISSUE THREAD

**Issue by mboynes** [WordPress/gutenberg#14036]
Deleting the contents of a paragraph block while in "Edit in HTML" mode, then moving focus out of that block, can make it so that block cannot obviously be removed or converted back to visual mode.

**To Reproduce**

1. Enter content in an empty paragraph block
2. In the block options, "Edit as HTML"
3. Erase the content
4. Click away from the block

The block content is replaced by `<p></p>` and there's no longer an option to delete the block or to "Edit Visually".

Alternatively, deleting the text contents of the paragraph tag (e.g. in `<p>hello</p>`, delete "hello" leaving an empty paragraph tag) will surface the same bug.

**Expected behavior**
After clearing the block contents and clicking away from the block, I would expect to still be able to delete the block or to switch back to "Edit Visually".

**Screenshots**

![delete-contents-html-mode](https://user-images.githubusercontent.com/465154/53217131-e4fcb500-3624-11e9-90c7-10e2dce175fd.gif)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 72.0.3626.109
 - WordPress 5.0.3

**Comment by designsimply** [comment]
Tested and confirmed using WordPress 5.2-alpha-44767 that the block toolbar (including the option to "Edit Visually") disappears if you create a new block then switch to "Edit as HTML", delete all content, and unfocus the block.

Because deleting all content from a block while in HTML mode is likely rare, I'm recommending low priority status unless we find a reason otherwise. Would like to hear from others in comments here if more people run into this as a problem!

**Comment by Thelmachido** [comment]
I was able to reproduce this as shown below:

https://user-images.githubusercontent.com/41231764/182693552-f5b8a7b9-b004-484f-bd5a-656078e885a7.mov

Gutenberg 13.8.0

WordPress 6.0.1
