### ISSUE TITLE
Embed: always put focus on the required input field to enter an URL

### ISSUE THREAD

**Issue by slaFFik** [WordPress/gutenberg#1407]
It's an obvious improvement.

**Comment by youknowriad** [comment]
There are so much more "obvious improvements" that need to be done. We'd appreciate any PR improving the experience.

**Comment by slaFFik** [comment]
Sure, but that will require a ton of JS installations and other things, that are not my main focus.
I can provide only the user-oriented feedback for now. Hopefully, that's ok :)

**Comment by youknowriad** [comment]
Yes, it is appreciated, thanks for the feedback. I just wanted to make sure you understand that we have so many things to do and we couldn't have solved everything even if it's obvious.

**Comment by slaFFik** [comment]
Sure, I totally understand. Those is just my 2c :)

**Comment by mtias** [comment]
@afercia is this something that makes sense from an a12y point of view?

**Comment by afercia** [comment]
@mtias: controversial.

As a general rule: always prefer native focus order and avoid to move it programmatically as much as possible.

In limited cases, where it makes sense, focus can be moved programmatically, making sure no relevant UI controls get "skipped".

In case of very simple forms with a very specific task, focusing the first form field generally helps all users. Gutenberg is already focusing the paragraph, for example.

On the other hand, moving focus on the block container as it happens now for the embed blocks gives an immediate feedback about what the block is. When inserting an embed, focus goes to the container highlighted in red in the screenshot below:

![screen shot 2017-08-31 at 17 27 35](https://user-images.githubusercontent.com/1682452/29931921-01539954-8e73-11e7-947f-1ec803a604b2.png)

This way, assistive technologies can announce what the block is (because it has an aria-label):

![screen shot 2017-08-31 at 17 24 04](https://user-images.githubusercontent.com/1682452/29931950-16ee697e-8e73-11e7-9237-d63209f5da69.png)

So, I'd say it's not so "obvious" 🙂 

Following the same approach, when inserting an image or gallery we should then move focus to the "insert" button?

There's the danger to make the mover, formatting, cog and delete controls less discoverable. On the other hand, there is an inconsistency across blocks that should be improved.

I'd recommend to consider this issue holistically, checking all the different blocks and see how many have a main "task". Then try to set focus on the main control for all the blocks, that is also the image, gallery, etc. Then test also with assistive technologies, they hopefully should announce the b;;ock type even when moving focus inside the block.

The other controls discoverability issue would stand, but I guess asking users a certain level of exploration is acceptable. (note, this wouldn't happen is all the other controls were placed _after_ the block content).

**Comment by mtias** [comment]
Yes, I'd lean on not auto-focusing here.

**Comment by afercia** [comment]
Well... maybe consistency is more important. I'd say either always auto-focus or never.

**Comment by mtias** [comment]
The thing is that embeds have a single purpose—add url. Other blocks would have more fields, and it might not make sense to prioritize one above another.

**Comment by afercia** [comment]
@mtias there are some inconsistencies though. Quickly checking  some blocks, if I'm not wrong, Classic text, Code, Html, and Quote blocks don't have initial focus set on the editable field.
The Paragraph block does. I'm not sure I fully understand this different behavior.
That doesn't mean I'm recommending one of the twos, the best option should be tested and carefully pondered. It's just they're different.

**Comment by mkaz** [comment]
@mtias @afercia - I would vote for focusing in Text, Code, HTML, and Quote blocks where the main action is to keep going. I came across this writing a post and I wanted to enter a code example.

1. Type enter to get a new block

2. `/code` to switch block to code block and type enter

3 (a). The new code block appears but does not have my focus, and typing enter again creates a paragraph block below the code block.

3 (b). To type in the code block after creating it, I need to either use the mouse or it so happens I can use the arrow keys but this feels unintuitive since I do not see a cursor when block gets inserted, there is no indicator of what has focus.

**Comment by jasmussen** [comment]
Great discussion here, and good instinct for creating the ticket. 

In addition to the accessibility concerns voiced here, there's another use case that requires you to be able to focus _the block placeholder_ without being auto-focused on the textfield, and that involves selecting the block to delete it with the delete key. As such, although the instinct is right, I'm going to close this one for now.
