### ISSUE TITLE
Media in Video/Audio blocks no longer plays

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#14072]
**Describe the bug**
Audio or video files inserted into an Audio/Video block won't play.
If you insert a YouTube Embed block, you can click on the video to play it. Audio/Video blocks should act in the exact same way.

**To Reproduce**
1. Add Video Block
2. Upload and insert video into block
3. Try to click the play button to play the video

**Expected behavior**
You should be able to click on the Audio/Video block and play the file within the dashboard.

**Desktop (please complete the following information):**
 - OS: macOS 10.12.6
 - Browser: Firefox Quantum 65.0.1
 - WP: 5.1

**Comment by jorgefilipecosta** [comment]
Hi @maddisondesigns, thank you for reporting this issue. This behavior was an intentional decision, and the ability to use the blocks in the editor was removed.
I'm not sure about the reason for this decision, @jasmussen, @mapk do you have some thoughts on this?

**Comment by maddisondesigns** [comment]
This makes it inconsistent with the Embed blocks (which can be played), and its also a backwards step from the Classic Editor. If I add a video to my page using the Classic Editor, I'm able to play preview it. I should be able to do the same in the Block Editor.

**Comment by jasmussen** [comment]
I don't personally recall making the audio and video blocks unplayable intentionally, it seems like a bug to me.

What we did do, which was intentional, was make embeds require an additional click in order to be playable. The idea being that you can click a YouTube video to _select it_ (in case you want to make it wide or add a caption) without that click starting the video. A second click should always start the video playing.

There could be good reasons for locking the audio and video blocks from playback — I wasn't personally part of that conversation, so I'll defer to those involved in case it was intentional. 

But it slightly smells like a regression, and that the solution here is to ensure that audio, video, and embed blocks work the same — one click to select the block, another to start them playing.

**Comment by jasmussen** [comment]
Tagged "Embed" not because this is specifically related to _embeds_, but because the issue might be related.

**Comment by mapk** [comment]
Definitely a bug. I just tested myself and can't get an uploaded video in the Video block to play. I would expect that clicking the "PLay" button would play the video similarly to the Embed blocks.

**Comment by paaljoachim** [comment]
Tested with WordPress 5.7 beta 3.
Twenty Twenty One
Chrome

Adding a video to the video block I am not able to get the play button to work in the backend.

![Screen Shot 2021-02-21 at 18 38 50](https://user-images.githubusercontent.com/5323259/108633348-1149a700-7474-11eb-9435-f7ac2f4e24d8.png)

@ntsekouras Nik. Could you take a look at this?

**Comment by jorgefilipecosta** [comment]
Given that according to the discussion here it seems not being able to play videos on the backend is a bug I will work on a PR to fix this issue if no one else is already working on this issue.

**Comment by paaljoachim** [comment]
Hey Jorge @jorgefilipecosta 
Embedding a Youtube video can be played in the backend and for consistency it would also be helpful to be able to play an uploaded video the same way. Thank you for working on this!
