### ISSUE TITLE
Seperator block ends up full-width

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#14102]
Often the theme's `<hr>` styling will override any differentiation between wide and short separators, and both end up full-width.

Issue made from block audit #8970. Props @kjellr and @sarahmonster.

**Comment by jorgefilipecosta** [comment]
Hi @karmatosed, @kjellr, @sarahmonster,
What would be the ideal way to address this problem, should we increase the specificity of our styles to make sure they overwrite theme ones?

**Comment by sarahmonster** [comment]
Some examples of this in action:

Twenty seventeen:
<img width="424" alt="screenshot 2019-02-26 11 39 23" src="https://user-images.githubusercontent.com/376315/53410271-3907f080-39bb-11e9-8e42-f09bb148bf84.png">

Twenty sixteen:

<img width="568" alt="screenshot 2019-02-26 11 48 30" src="https://user-images.githubusercontent.com/376315/53410717-79b43980-39bc-11e9-9514-5814891e417a.png">

Twenty fifteen:
<img width="584" alt="screenshot 2019-02-26 11 49 36" src="https://user-images.githubusercontent.com/376315/53410821-c6981000-39bc-11e9-803d-d9edf95bb76f.png">

Atomic blocks:
<img width="751" alt="screenshot 2019-02-26 11 51 18" src="https://user-images.githubusercontent.com/376315/53410849-dca5d080-39bc-11e9-8d54-c57307d5ef14.png">

_s:
<img width="776" alt="screenshot 2019-02-26 11 51 55" src="https://user-images.githubusercontent.com/376315/53410865-eb8c8300-39bc-11e9-89c9-34f7a58b8ff1.png">


It looks as though we'd need to set a width attribute on the default `.wp-block-separator` element. Since the default separator doesn't have a specific class, you'd either need to use chained :not statements:

```
.wp-block-separator:not(.is-style-wide):not(.is-style-dots) {
    max-width: 100px;
}
```

...or add an additional class to the default `.wp-block-separator`, and apply the styling directly to that.

If the `:not` solution seems sensible (and like it wouldn't be likely to break anything), I can make a PR for this.

**Comment by webmandesign** [comment]
The issue was also discussed in #10569

**Comment by paaljoachim** [comment]
Is this issue still valid?

**Comment by paaljoachim** [comment]
I will go ahead and close this issue as it seems like this has been taken care of in various associated issues/PR's. If I am mistaken then please reopen the issue.
