### ISSUE TITLE
Rich Text: Non-selected inline boundaries wrongly highlighted

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#14120]
**Describe the bug**

When applying an inline format to a region of text, any other texts in the same paragraph with that same format appear as highlighted. I would only expect the selected text to be highlighted.

**To Reproduce**

1. Navigate to Posts > Add New
2. Insert a new paragraph block
3. Insert some text
4. Apply bold to a fragment of text
5. Apply bold to an _entirely separate_ fragment of text
6. Observe that both fragments of text are highlighted

**Expected behavior**

Only the text selected at step 5 should appear as highlighted when bold is applied.

**Screenshots**

![bolded](https://user-images.githubusercontent.com/1779930/53422121-df002e80-39ac-11e9-8a7b-2c40b36e73e0.gif)

**Desktop**

 - OS: macOS Mojave Version 10.14.3
 - Browser: Chrome Version 72.0.3626.119 (Official Build) (64-bit)

**Additional context**

Gutenberg master (e0adbe074), 5.1.0 latest release.

cc @iseulde

**Comment by iseulde** [comment]
This is a result of having the same reference at those indices after applying the format (and normalising formats). We should probably only normalise neighbouring formats only. This used to be the case before one of the list rewrites. I can look into this after #13948, when list formats are separated.

The highlighting of other boundaries will go away as soon as you move selection, because `create` uses a reference per DOM element.
