### ISSUE TITLE
Change verse block icon

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#14131]
The verse block icon is a pencil, could this be something more 'verse like'? This comes from the block audit #8336

**Comment by danicholls** [comment]
Quill is kind of classic for literature, and verse in particular. Alternatively, simple lines (like an unordered/ordered list but without the dots or numbers) of varying lengths (like long, short, medium).

**Comment by maddisondesigns** [comment]
Would be good to get the rest of those Embed icons changed while this is being done - #9124

**Comment by kjellr** [comment]
A quill of some sort might work. But I wonder if focusing on the functionality rather than the suggested intent here would better convey what this block does? The verse block basically just lets you type multiple lines into one block, and preserve the line formatting. 

To that end, I wonder if something showing multi-lined text would be more clear: 

![verse](https://user-images.githubusercontent.com/1202812/53664232-f867db80-3c35-11e9-8207-b422d7c594d7.png)

**Comment by karmatosed** [comment]
I like that @kjellr - let's change it!

**Comment by kjellr** [comment]
Closing since #14622 has been merged. Thanks, folks!
