### ISSUE TITLE
Change column/columns markup to replace Gutenberg Grid CSS

### ISSUE THREAD

**Issue by tomhrtly** [WordPress/gutenberg#14162]
As we are aware, Gutenberg adds a style sheet on the front end for it's grid system but if websites already include a grid system from a framework such as Bootstrap, Bulma etc., as developers, we should be able to change the class names for the markup on the front-end to replicate this.

To try and solve this, I de-registered the `wp-block-library` CSS file in `functions.php` but it's frustrating and time consuming to manually add the `row` class to columns and `col-12` to each column in the front-end through the "Additional CSS class" area in the block settings. 

It would be handy for developers to be able to change the CSS classes that get displayed on the front-end automatically so that the user does not have to keep adding the classes manually on each row or column. E,g, change `wp-block-columns` to `row` and `wp-block-column` to `col`.

**Comment by youknowriad** [comment]
You should be able to build a plugin that automatically adds these custom classNames as the columns block gets used.

**Comment by tomhrtly** [comment]
For the sake of simplicity and less HTML, I wish to remove the `wp-block-columns` class name and **replace** this with another class of my choosing, e.g. `row` if I'm using Bootstrap. If I'm not using the Gutenberg grid CSS, why should I be rendering the classes for it?

I believe there should be the ability for developers to change the existing class names that are rendered instead of keep adding the class names manually for the sake of cleaner markup and so that we don't have to manually add the class to the columns block every time.

**Comment by youknowriad** [comment]
If you extend the block and add `className: false`, to the support setting of the block, it should work. That said, this means, Gutenberg might show "invalid blocks" if you disable your plugin (implementing this behavior) because the markup will be different and Gutenberg might think that it's wrong. (needs testing)

**Comment by tomhrtly** [comment]
Is it possible to make these changes and test with the Block API? Also, so that our websites can be fully compatible with any CSS frameworks that may be used, it would be handy to change any of the HTML that gets render with each block.

I've noticed with some frameworks there are some small compatibility problems due to extra HTML nesting of core Gutenberg blocks.

This would be a very developer friendly feature for Gutenberg and we wouldn't have to think about our HTML code not being displayed correctly with the framework that is being used.

**Comment by aduth** [comment]
Another option to consider here is to invert how you're trying to customize the blocks, and instead use Bootstrap's SASS mixins to generate the styles for the default class names produced by the block editor.

https://getbootstrap.com/docs/4.1/layout/grid/#mixins

>Is it possible to make these changes and test with the Block API?

See: https://wordpress.org/gutenberg/handbook/designers-developers/developers/filters/block-filters/#filters

From Gutenberg's end, it ties into #7604 since, as noted at https://github.com/WordPress/gutenberg/issues/14162#issuecomment-470530864 , current options for extensibility can lead to unintended invalidations when your plugin becomes deactivated.

Lastly, an option can be to create your own variant of the columns block:

- https://github.com/WordPress/gutenberg/tree/master/packages/block-library/src/columns
- https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/inner-blocks

For the purpose of triage, I'd consider this closed on the basis of existing options to extend a block, given noted caveats on validation tracked at #7604.
