### ISSUE TITLE
Adding the style attribute using block filter

### ISSUE THREAD

**Issue by gregbia** [WordPress/gutenberg#14242]
I'm trying to add a style attribute in the block editor to a block's wrapper using a [block filter][1]:

    const addStyle = createHigherOrderComponent( ( BlockListBlock ) => {
        return ( props ) => {
            return <BlockListBlock { ...props } className="my-class" style="color: red" />;
        };
    }, 'addStyle' );
    
    wp.hooks.addFilter( 'editor.BlockListBlock', 'my-plugin/add-style', addStyle );

Only the `my-class` class name is added to the class attribute but no style attribute. Is it possible to add a style attribute as well? The documentation states:

> It receives the original BlockListBlock component and returns a new
> wrapped component.

but does not say you can add only class names. 

  [1]: https://wordpress.org/gutenberg/handbook/designers-developers/developers/filters/block-filters/#editor-blocklistblock

**Comment by youknowriad** [comment]
After some discussions in the Core JavaScript meetings, we're considering these filters as not the ideal API to extend the editor UI. We're not going to remove them, but the way they work is that you're only able to wrap the components or change their supported props and style is not a prop supported by this component.

**Comment by gregbia** [comment]
Thank you for the information! Will there be another API for extending blocks? I find these filters useful for making editor blocks look like the frontent (especially when using inner blocks), as in the editor, Gutenberg wraps blocks in more divs. For example I'm building a block for columns. I;m using innerblocks to add column by column in a columns block. In the editor I have to add classes to the block's `editor-block-list__block` wrapper in order to get the look on the front-end.

**Comment by tousignant-christopher** [comment]
I second this. Inner Blocks do not display as they would on the front end, and being able to use the filters to adjust the editor to better match the front end would be ideal. If we shouldn't be using the filters to achieve this, what should we use instead?

**Comment by Jamiewarb** [comment]
Hey there!

>we're considering these filters as not the ideal API to extend the editor UI

Any recent thoughts on this? It looks like this is still the way to be adjusting the editor UI

**Comment by tousignant-christopher** [comment]
@Jamiewarb The API has changed since I posted the last gist. With Gutenberg's API v.2, blockProps and InnerBlocksProps were introduced that will no longer wrap the block in needless wrappers. 

I created a couple of Gist to demo these funcs.

If you are creating a normal block that does not take in children block, check out:
[useBlockProps](https://gist.github.com/tousignant-christopher/ccf4ef7b5d8a87731bba6d0f82de5e18)

If you are creating a block that accepts children blocks, check out:
[useInnerBlocksProps](https://gist.github.com/tousignant-christopher/b2a0a17c10538194449c66e378c0adc7)

note that you need to declare API version 2 when you register the block. If you do not, the necessary functions will not be exposed to you. 

Also note, these gist are not complete examples, they are just to show how you would use blockProps and innerBlocksProps.

lmk if you need anything else.
