### ISSUE TITLE
Reusable Blocks looses focus if you want to add an inline block

### ISSUE THREAD

**Issue by vheinrich** [WordPress/gutenberg#14274]
**Describe the bug**
If we edit a reusable block and want to add a paragraph with an inline image, the paragraph block losses its focus. As a result of this the inline block option in the block inserter isnt visible.

**To Reproduce**
1. Build a reusable block with a inner block paragraph or just a paragraph block as a reusable block
2. Save the block as reusable block
3. Edit the reusable block and try to add an inline image to the paragraph
4. The paragraph Block looses its focus and an inline element cant be added.

**Expected behavior**
Not loosing of focus and ability to add a inline block.

**Screenshots**
Screencast: https://www.dropbox.com/s/zif9h1xrb89zx9k/gutenberg_reusableblock_inlineimage.mp4?dl=0

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3
 - Browser Safari 
 - Version 12.0.3

**Additional context**
- WP Version: 5.1.
- Theme: TwentyNineteen

**Comment by noisysocks** [comment]
I'm able to add inline images to reusable paragraph blocks in the latest development version of Gutenberg. This may have been inadvertently fixed by https://github.com/WordPress/gutenberg/pull/14233.

![inline-images](https://user-images.githubusercontent.com/612155/54248616-7a8ac500-4591-11e9-8fc1-7168228ebf2c.gif)
