### ISSUE TITLE
Media & Text: Turn "Stack on mobile" toggle on by default

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#14281]
IMO, this block should make this responsive by default, so we should enable the toggle by default.

**Comment by kjellr** [comment]
Agreed. This would align to the concept of "Smart defaults", and would be inline with the way the Columns and Gallery blocks behave.

**Comment by marekhrabe** [comment]
Do you think we should be concerned about the backwards compatibility here? 

Eg: if somebody used Media & Text previously and really wanted it to show as columns even on mobile, they had to do nothing as it was (and still is) the default behavior. If we just change the default now, all those people would get the "stacking" activated on all their blocks just with the update. 

I also think there might be a non-insignificant group of people who would appreciate stacking but didn't know about the option so they don't have it active. Automatic opt-in might be great for them.

Any idea how to approach this?

**Comment by kjellr** [comment]
I do think that's a concern, but on the other hand, I'm sure there will be a fair amount of users who didn't know that toggle existed, and will be pleased that their Media & Text blocks now work nicely on mobile after this change. This definitely feels like the best behavior for this block. 

If possible, it'd be awesome to only apply this to new blocks somehow, but if that's not an option then I think it's okay. I don't think it's necessarily a _breaking_ change, since it improves the way these will look in the vast majority of cases.

**Comment by AmirS** [comment]
Pull request at #14364
