### ISSUE TITLE
docgen: hoist constants using the `@constant` JSDoc tag

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#14292]
When generating docs for an API, constants could be grouped at the top of the API section. Suggested at https://github.com/WordPress/gutenberg/pull/14265#issuecomment-470076141

One way to implement this would be to group the symbols that are constants, as declared by the [`@constant` JSDoc tag](http://usejsdoc.org/tags-constant.html).

Note the related `@const` tag.

**Comment by aduth** [comment]
>When generating docs for an API, constants could be grouped at the top of the API section. Suggested at #14265 (comment)

Per my related comment at https://github.com/WordPress/gutenberg/pull/14266#issuecomment-470120844 , could it just be that the generated output is ordered by the order in which the symbol appears in the source?

**Comment by nosolosw** [comment]
@aduth We should create an issue for sorting! :) 

> I like the first idea here. Is there any challenge to this, or downside?

One good thing about using the export order to sort the API would be that we could group things together: like having `registerPlugin` just before `unregisterPlugin`. Or what [you mentioned](https://github.com/WordPress/gutenberg/pull/14266#issuecomment-470120844) about having the most used functions first. 

The downside is that it requires manual curation. I don't think we have now the amount of time required to curate _all_ the packages. And, even if we did, I don't think we could sustain it over time: being almost at [400 contributors](https://github.com/WordPress/gutenberg/graphs/contributors) means a high-potential for wildly different curations of things, but also changes made by contributors unaware of the _proper_ order.

Alphabetical takes that burden out of the table. But also a strong argument for it is that API docs are _reference_ documentation (like a dictionary, which is optimized for lookup). This is in contrast with _onboarding_ documentation (tutorials and such), where you present the most relevant things first.

Said that: I look forward to bringing more grouping abilities. This issue is just one possibility. The data module would be a good use case to explore: how can we group `selectors`, `action creators`, `HOCs`, etc. in the API docs without involving manual curation? I wish `jsdoc` had any way to define artifacts in one semantic level up, at the domain layer (I mean: from `@class`/`@function`/`@constant` to `@selector`/`@action`/etc).

**Comment by nosolosw** [comment]
> I wish jsdoc had any way to define artifacts in one semantic level up, at the domain layer (I mean: from `@class/@function/@constant` to `@selector/@action/etc.`).

Although [`@typedef`](http://usejsdoc.org/tags-typedef.html) could be something to explore, it's limited in that only serves to document the type of a parameter or the output. It's not about the _signature_ of the artifact (which is what defines a `selector`, `action creator`, etc).

**Comment by aduth** [comment]
> @aduth We should create an issue for sorting! :)

Sorry, did not mean to side-track, just seemed that sorting could supersede the need for specifically hoisting constants.

>But also a strong argument for it is that API docs are reference documentation (like a dictionary, which is optimized for lookup). This is in contrast with onboarding documentation (tutorials and such), where you present the most relevant things first.

I like this argument, and your follow-up point about groupings. I can't say I have any advice to offer. The idea sounds similar to something like PHPUnit's [`@group` annotation](https://phpunit.de/manual/6.5/en/appendixes.annotations.html#appendixes.annotations.group). Is there any specific problem we might face if we were to use a tag not strictly part of the JSDoc family?

**Comment by nosolosw** [comment]
One thing I had hopes in was the [`@kind` tag](http://usejsdoc.org/tags-kind.html). Tried to use it like `@kind selector`, but that makes the linter unhappy.

Bizarrely enough, what doesn't make the linter unhappy is to use our own tag `@gutenberg selector` :man_shrugging: `doctrine` also passes it through, so it's picked up by `docgen` and ends up in the JSON that it generates. We'll only need the formatters to use this in some way.

A different approach would be to use the [`@implements` tag](http://usejsdoc.org/tags-implements.html) such as `@implements {selector} an extra description`. I like this approach better. It fits with our purpose (describing domain's semantics) and it's spec/future-proof (at least any tool that claims JSDoc support should play nicely with this). Created https://github.com/WordPress/gutenberg/issues/14333

**Comment by oandregal** [comment]
I'm triagging issues we don't plan to tackle. We can reopen if it regains interest.
