### ISSUE TITLE
Improve scrolling performance

### ISSUE THREAD

**Issue by rozmy** [WordPress/gutenberg#14312]
I have hundreds of elements (blocks) that kills my browser. Is is possible to improve the scrolling performance? (Hide DOM elements outside my current viewport - something similar to [virtual scrollbar techniques](https://medium.com/walkme-engineering/showing-elements-to-infinity-and-beyond-a4f58f4b86d5))

**Comment by youknowriad** [comment]
Virtual scrollbar techniques was explored but abandoned because of two reasons:

 - It can't be made accessible
 - It only works if the height are known before rendering the elements which is not the case for blocks.

Which version are you using, with the last Gutenberg plugin version, the performance should be decent
