### ISSUE TITLE
wordpress.com CSS issue prevents scrolling

### ISSUE THREAD

**Issue by aristath** [WordPress/gutenberg#14324]
I've only encountered this issue on wordpress.com with the Gutenberg plugin installed so I assume it has something to do with that.

There's a scrollbar between the content and the sidebar, and that prevents scrolling. If I try to scroll while the cursor is in the content it doesn't scroll. The content only scrolls if I move my cursor to the sidebar.

Adding this CSS fixes the issue:
```css
.editor-writing-flow {
  overflow-y: hidden;
}
```
![screenshot_2019-03-07 edit page wplemon com wordpress](https://user-images.githubusercontent.com/588688/53981625-961e4780-411b-11e9-9e98-f23412a9603c.png)

Issue occurs on latest firefox, I haven't checked other browsers.

**Comment by aristath** [comment]
Update: Only happens on Firefox, on Chrome it's fine. I don't have a windows machine to check Edge or OSX to check Safari, I'm on linux.

**Comment by talldan** [comment]
Hi @aristath - it is intentional that there's a scrollbar for both the main content area and the sidebar:

![scrolling](https://user-images.githubusercontent.com/677833/54249625-3644f800-4584-11e9-83fb-7c385fcff042.gif)

I've tested in both WordPress.com and my gutenberg dev environment in Firefox and could see any issues that prevented scrolling.

If there is a bug you're experiencing and it's only happening in WordPress.com, I'd recommend creating a support request there - https://wordpress.com/help/contact.

I'll close the issue, but feel free to continue to comment, and if there is a bug we can reopen it.
