### ISSUE TITLE
Gallery Block: Think up responsive feature

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1433]
The gallery block has a slider to pick the amount of columns you see. This is a "one size fits all" slider, that defines the amount of columns across all screen sizes.

How can we make this more responsive friendly, so for example on mobile screens you have a single column, and on big monitors you have big 4 or 5?

One idea is to have two sliders:

- Max. columns (for big viewports) 
- Min. columns (for small viewports)

Then we'd figure out the responsive math to decide how many to show at multiple breakpoints in between.

A simpler option, perhaps, would be to have a slider for each breakpoint:

- Columns on desktop
- Columns on tablet
- Columns on mobile

Then we'd have exactly three breakpoints. 

Thoughts?

**Comment by paulwilde** [comment]
I'd honestly leave this up to the theme to decide (via CSS).

**Comment by jasmussen** [comment]
> I'd honestly leave this up to the theme to decide (via CSS).

I could give that a 👍

**Comment by karmatosed** [comment]
I am torn about leaving it up to the theme. I think some intelligent responsiveness out of the box would be better, over leaving it all up to the theme. I also am torn about having extra sliders to set this.

Can we have a default behaviour for responsive and let the theme take from there?

**Comment by folletto** [comment]
Thinking outside the box, a different suggestion.

What if instead of "columns" we specify the size of the thumbnail? This would work really well with an implementation using `flex` and would be a single setting across any screen size. The UI could have a setting for `min` and `max` width for the column, maybe even a `single value` and we calculate some variance in the background (well, we let `flex` do it).

Pros:

1. Implementation is a straight build on `flex`.
2. No lies: the number of columns is dependent on screen size, and we acknowledge it.
3. No dependency on the theme column width.

Cons:

1. Columns are an incredibly intuitive concept to grasp, if one is building only for desktop, that's all they need.

This might be a challenging suggestion exactly due to how intuitive "columns" are, as it's often what people want, yet... maybe the size is as intuitive, and we just haven't tried?

**Comment by jasmussen** [comment]
I like that line of thinking, Davide —  a simple "rule" to replace several more complex ones. However right now, if you insert 5 images in a 3 column gallery, you get this:

![screen shot 2017-07-03 at 13 46 45](https://user-images.githubusercontent.com/1204802/27791595-1c5000a4-5ff6-11e7-8822-879c4ef474bf.png)

In this case, the thumbnail size varies based on the _available space_. Which obviously we could revisit, but I think it's a quite nice implementation.

**Comment by folletto** [comment]
Yep, I think it's how flex handles it. We had a similar consideration (and following workaround) in working with the theme showcase. ;)

I think it's a good way to deal with the last line, and we shouldn't step away from it. We could just add a note that the last line will fill, regardless? And maybe in the future an option to _not_ allow it filling. ;)

**Comment by mtias** [comment]
Let's set a sensible default for mobile, like max 3 or 2 columns as a start.

**Comment by karmatosed** [comment]
My feelings are 2 for mobile is a good point.
