### ISSUE TITLE
Is it possible to add anchor to only specific part of block not whole block?

### ISSUE THREAD

**Issue by prajaktagadhave123** [WordPress/gutenberg#14372]
Hello,

Is it possible to add anchor support to specific part of block instead of whole block?

Refer this screenshot - https://monosnap.com/file/xCJUy092uamCdifVDsicKz66SGbrHI

Here, we want to add anchor to '**h2**' tag not for whole block?  Is this possible?

**Comment by marekhrabe** [comment]
I believe there is an "Advanced Heading" on your screenshot from https://wordpress.org/plugins/ultimate-addons-for-gutenberg/. You should file an issue with the author so they can add the functionality. It is up to each block how (and if) they implement a support for anchors.

The "Heading" block from core Gutenberg adds anchor directly to the `<Hx>` tag and it sounds like a good idea 3rd party block for headings to follow the same rule.

I'm closing the issue here, as it doesn't directly involve the core but rather a 3rd party plugin.
