### ISSUE TITLE
Gallery: add missing options to inspector

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#1448]
There are a few items we should preserve on the inspector, like linking to the attachment view of an image. Not sure how many of these we want to consider.

**Comment by jasmussen** [comment]
Also, we want to find a way to improve the cropping of thumbnails somehow. The current arbitrary height images isn't the most visually pleasing. Perhaps a soft-crop using `object-fit`.

**Comment by westonruter** [comment]
Whatever options are chosen, they should align with the Gallery widget that is now in development (and vice versa): https://github.com/xwp/wp-core-media-widgets/pull/120

**Comment by jasmussen** [comment]
For reference, these are the options in the current gallery:

![screen shot 2017-07-26 at 11 32 22](https://user-images.githubusercontent.com/1204802/28614452-3384dbe8-71f6-11e7-8af5-1eedb3c9f527.png)

By the way @mkaz it looks like in master, this button...

![screen shot 2017-07-26 at 11 33 45](https://user-images.githubusercontent.com/1204802/28614504-5e91f12c-71f6-11e7-8ab6-d7e7dcc9d8bc.png)

is broken ...

![screen shot 2017-07-26 at 11 33 57](https://user-images.githubusercontent.com/1204802/28614507-6490ede4-71f6-11e7-9e2c-b4aff30dfa76.png)

... but only on the demo content. Is that because it's demo content, or is there a deeper underlying issue?

**Comment by westonruter** [comment]
AFAIK, the edit button doesn't work in the demo gallery because the demo content doesn't refer to any attachments in the media library. The images are just hard-coded. So since there are no attachment IDs, there is nothing to find in the Edit Gallery frame. A way to fix this would be to construct the gallery dynamically out of a couple random images in the media library, but that would depend on there being images to begin with and also to hope they would look good in a gallery.

**Comment by mkaz** [comment]
As of right now the gallery modals require a fair amount of data to be stored, including the thumbnail images to display properly on edit. There is issue #1986 to address the but then will require an attachment id # for it to work properly, which I'm not sure will work with demo content since it probably can't be hard-coded

**Comment by jasmussen** [comment]
Since we know for a fact that the demo content will go away at some point, it doesn't seem worth it to jump through hoops to make sure it works perfectly in every situation. In fact you could argue that a "fix" would be to not show the gallery at all — perhaps we could show a placeholder instead?

**Comment by mtias** [comment]
> In fact you could argue that a "fix" would be to not show the gallery at all — perhaps we could show a placeholder instead?

I think being able to have galleries with media that is not in your library is still a good thing.

**Comment by jasmussen** [comment]
> I think being able to have galleries with media that is not in your library is still a good thing.

Ah, I missed that bit. Yeah absolutely.

**Comment by mtias** [comment]
That said, definitely not something to prioritize.

**Comment by mtias** [comment]
Let's close this one as we have issues for adding the "link to" option and the thumbnail size: https://github.com/WordPress/gutenberg/issues/1450
