### ISSUE TITLE
Inputs: Unify height

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#14505]
**Describe the bug**
Inputs in Gutenberg seems to use various heights, from 28px to 38px tall.

**Expected behavior**
All inputs (except for TextareaControl) should be the same height.

**Screenshots**

![image](https://user-images.githubusercontent.com/2846578/54563436-8d413780-499f-11e9-8539-86636ddf78eb.png)

![image](https://user-images.githubusercontent.com/2846578/54563465-9fbb7100-499f-11e9-985b-e8742eb64820.png)

![image](https://user-images.githubusercontent.com/2846578/54563567-e27d4900-499f-11e9-839b-3bf9a96344f9.png)

![image](https://user-images.githubusercontent.com/2846578/54563591-f2952880-499f-11e9-8f44-32636ad953fd.png)

Personally, I think all single-line inputs should be standardized to 38px.

**Comment by m-e-h** [comment]
Sort of related https://github.com/WordPress/gutenberg/pull/11555

**Comment by jasmussen** [comment]
Really noble goal, love it. I have a personal preference for 36px because it's base12, and therefore compatible with the 24px grid we're sort of hoping to roll out. But 38px works too. 

A question in Slack asked why there are so many separate styles, and why there are "mixins" for these as well. Here's a little context:

- Primarily, years of WordPress styles building up in a not-componentized way, means there is a fair bit of CSS bleed, styles that inherit where they shouldn’t. 
- The mixins are an attempt to provide unified styles, same as these, so when a change across components like these have to be made, it can be done in one place. For example we are trying to reduce the number of focus styles we have — for situations like panels receiving focus, we have the dotted line. For buttons, we have a border. By including the mixins in an array of different components that use these focus styles, we can change the focus style in one place and it will affect all components that use it. 

The best way to remove CSS bleed is to patch WordPress itself so all styles are properly scoped. In absence of that, we have to work within the boundaries of overriding CSS.

**Comment by mtias** [comment]
I think this should progress as things get standardized through the use of components. cc @ItsJonQ
