### ISSUE TITLE
Add ability to update multiple Blocks' attributes in Block Editor Data 

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#14511]
Essentially we need a way to update the attributes of multiple Blocks in a single go.

We currently have the [ability to do this for a single Block](https://wordpress.org/gutenberg/handbook/designers-developers/developers/data/data-core-block-editor/#updateblockattributes), but there are [use cases where it would be great to be able to do this for multiple Blocks](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/columns/edit.js#L113).

Also note this would need to be tested to see whether it creates a single undo history entry or whether it creates an individual history entry per attribute update. Ideally we'd need the ability to control this otherwise we get [this issue](https://github.com/WordPress/gutenberg/pull/13899#discussion_r263341084
).

Given the feedback [here](https://github.com/WordPress/gutenberg/pull/13899#discussion_r265309934) I'd be interested to hear from @aduth on this one as I believe he's currently working on Undo functionality.

**Comment by aduth** [comment]
From https://github.com/WordPress/gutenberg/pull/13899#discussion_r263356386:

>Is there a way to update an attribute without tracking it into history? What other options might we have?

There's one default limiter in place, which is that any consecutive updates to the same block attribute or same post property will be flattened into a single undo level:

https://github.com/WordPress/gutenberg/blob/c34d6b78e77cd4edbc2963003409151fb0939312/packages/block-editor/src/store/reducer.js#L158-L176

https://github.com/WordPress/gutenberg/blob/c34d6b78e77cd4edbc2963003409151fb0939312/packages/editor/src/store/reducer.js#L79-L94

Much of this is controlled by the `shouldOverwriteState` option of the custom `withHistory` higher-order reducer:

https://github.com/WordPress/gutenberg/blob/c34d6b78e77cd4edbc2963003409151fb0939312/packages/editor/src/utils/with-history/index.js#L29-L33

The recent block editor refactoring fragmented this a bit more, since it needs to "bubble up" whether a change should be considered as making its own undo level (note the first of the snippets above from the `block-editor` reducer). It does this by calling one of either `onChange` or `onInput` for persistent (undo-tracked) or non-persistent changes respectively:

https://github.com/WordPress/gutenberg/blob/c34d6b78e77cd4edbc2963003409151fb0939312/packages/block-editor/src/components/provider/index.js#L95-L99

To your end, then, it might be considered:

- Could the updates be applied in an order which triggers the default flattening (i.e. consecutive updates to the same attribute)?
- If not, is there some other way we could enhance `isUpdatingSameBlockAttribute` (or more likely `withPersistentBlockChange`) to programmatically account for a case like yours as considered to be persisted only at predefined intervals?
- At worst, could it be expressed as something akin to a database transaction wherein all operations which occur during the transaction would be counted as a single persistent change?

**Comment by mtias** [comment]
Take a look at how multi-select attribute changes for the same block type work if needed for inspiration.

**Comment by bfintal** [comment]
@mtias can you help point to the right direction? I see that `updateBlockAttributes` now accepts an array for the `clientIds`. But how about if you want to update multiple blocks that have different attributes at the same time? If you do things in one go, you might have the ability to have a single undo action to undo the multiple updates
