### ISSUE TITLE
The site is not working

### ISSUE THREAD

**Issue by nedalco1** [WordPress/gutenberg#14547]
After the new update
The site is not working
I use WordPress 5.1.1
Waiting for update

**Comment by nedalco1** [comment]
The site only works when the add-on is disabled

**Comment by youknowriad** [comment]
Hi there! which add on are you talking about?
Can we have more details on the failure?

**Comment by nedalco1** [comment]
When you update the add-on today
The site stopped working
Then I sent the technical support to the host
They told me the problem with this addition
Their words are true
When I've disabled the add-on
The site returned to work
See some of the conversation
https://a.top4top.net/p_1175h11hb1.jpg

**Comment by nedalco1** [comment]
Please I want a solution
My business is now parked

**Comment by youknowriad** [comment]
Can you share more details about the error, unfortunately, without these, there's no way for us to reproduce the error or know why you're having a failure.

**Comment by nedalco1** [comment]
The problem has been resolved
By going back to the previous version
Apparently there is a sufferer of the problem
https://wordpress.org/support/topic/site-down-due-to-gutenberg-update-in-wp/

**Comment by youknowriad** [comment]
Thanks for the link, we'll take a look.

**Comment by youknowriad** [comment]
It looks like there's a plugin called `envira-gallery` that is using a deprecated function in Gutenberg. This function is still supposed to work for two more versions though. @aduth thoughts?

**Comment by aduth** [comment]
The error appears to occur from this line in the now-deprecated `is_gutenberg_page`:

https://github.com/WordPress/gutenberg/blob/98a19b6ed32ff5dad4e2227e3d9e88efe71016a3/gutenberg.php#L92-L97

I've encountered issues before where `get_current_screen` was not a defined value, where the `require_once` in the preceding line is intended to ensure the function is available. 

Looking closer at its implementation however, it seems there may be cases (presumably in non-wp-admin contexts) where it would return `null`, thus prompting the error seen above.

https://github.com/WordPress/wordpress-develop/blob/49d8c2590c73c283576c9864cd69973f7f1421b8/src/wp-admin/includes/screen.php#L213-L230

From this, I'd consider the following action items:

- Within the plugin, any time we call `get_current_screen`, we should anticipate that it may return `null`. For the specific implementation of `is_gutenberg_page`, I'd suggest the following revision:

```php
$screen = get_current_screen();
return ! is_null( $screen ) && $screen->is_block_editor();
```

- For plugins generally, they should move away from the (now-deprecated) `is_gutenberg_page`. However, noting all of the above, while the recommendation would be to use `WP_Screen::is_block_editor`, the above two caveats should be noted that (a) `get_current_screen` may not be defined and (b) if defined, it may return `null`.

I could not verify this against `envira-gallery` since the plugin repository only contains a "lite" version. The lite version does not contain a reference to `is_gutenberg_page`, and in my limited testing works as expected without any errors.

cc @chrisakelley

**Comment by aduth** [comment]
Pull request at #14558.

**Comment by chrisakelley** [comment]
@aduth I just pushed an update to Envira Gallery Pro that should resolve it from our side.

**Comment by aduth** [comment]
Thanks for checking in @chrisakelley , and apologies for any trouble caused! I'd still like to see this solved on Gutenberg's end, even if the functions are slated for removal in a few versions' time.
