### ISSUE TITLE
No ability to indent

### ISSUE THREAD

**Issue by michaelswengel** [WordPress/gutenberg#14554]
**Is your feature request related to a problem? Please describe.**
In the old WP editor, we had the ability to indent paragraphs, list items, or whole sections of text at will. Gutenberg apparently provides no way to do this. This is a feature that I used very very frequently and need to have.

For example, items under an H3/H4 could be indented under an H2 if needed. One use case would be something like the following:

```
3 Reasons Gutenberg Needs Better Indentation Control

      Reason 1 Heading Here
      P: Reason 1 paragraph text here. This type of formatting wouldn't work as a typical list item.

      Reason 2 Heading Here
      P: Reason 2 paragraph text here.

      Reason 3 Heading Here
      P: Reason 3 paragraph text here.

Next major point of article.
```

This type of formatting makes posts far easier to follow visually and better organizes information. Hopefully this makes sense.

**Describe the solution you'd like**
I would like to see native indent/outdent abilities return in Gutenberg. This is the ideal (and honestly, only) solution.

**Describe alternatives you've considered**
Using a classic block or the classic editor is not a solution as these will be going away in the future. While this can be done to a limited extent via HTML, most people are not comfortable with HTML/CSS and should not be required to use it to do what was so easy to do in the old editor.

PLEASE bring native indenting to Gutenberg.

**Comment by vesaraiskila** [comment]
I wholeheartedly support adding the ability to indent paragraphs and other items. We, too, do that all the time. It is strange that this feature has been omitted from Gutenberg.

As the feature is not available, one has to use an HTML solution that invariable causes an error message, although the solution works after converting the block into HTML - see my bug report at

https://github.com/WordPress/gutenberg/issues/14672

**Comment by michaelswengel** [comment]
Agreed. PLEASE bring back the ability to indent paragraphs. This is a very important feature for many of us.

**Comment by aduth** [comment]
>Using a classic block [...] is not a solution as these will be going away in the future.

Can you elaborate on where this information comes from?

**Comment by michaelswengel** [comment]
@aduth , the classic editor is going away we are told. Is that wrong? 

Are you saying you plan to support the classic block indefinitely?

**Comment by aduth** [comment]
I'm not aware of plans to stop supporting the Classic block. It serves a different purpose from the Classic Editor plugin. The block exists largely to preserve the integrity of content produced prior to WordPress 5.0. The plugin serves to restore the pre-5.0 visual interface as users transition to the new editor.

To be clear, this says nothing of whether it may be subject to future iterations in its how it looks and behaves, but I expect it would continue to exist in one form or another.

**Comment by michaelswengel** [comment]
That's good news. However, having to use the classic block for something like this doesn't exactly lend itself to a seamless, enjoyable experience with Gutenberg, and it would be awesome if we can get it baked in. :)

**Comment by vesaraiskila** [comment]
I was advised earlier to use something like this in the HTML mode to achieve paragraph indentation:

`<p style="padding-left: 30px;">A paragraph to be indented</p>`

However, doing that invokes an error message, and after resolving it in a way that maintains the indentation, the block can only be edited in HTML mode, which is cumbersome.

So, an important feature has been omitted, and a solution around it has significant problems of its own.
I submitted a report about the latter at 
#14672

**Comment by noahkarp** [comment]
As a newbie to WP, I assumed that indenting text blocks would be an indispensable function. I took it for granted that moving to Gutenberg would preserve that functionality. 

I like Gutenberg so far, but this is a terrible limitation. On our site we indent text all the time for literary quotations etc, and not having a simple tool for doing this is perplexing.

PLEASE BRING BACK INDENT.

**Comment by bashoholic** [comment]
I just started using WP and like other have said you can edit as HTML, but it throws an error at you. In addition, that block will remain in HTML format only from that point on. I thought Gutenberg was suppose to bring about simplicity? 

In writing, starting a new paragraph should be indented, omitting such a basic writing concept is absurd.

**Comment by cvladan** [comment]
I'm stunned by the fact that indenting is not supported in Gutenberg...

**Comment by PaddyWhacks** [comment]
I agree - surely this should be part of the core functionality? Crazy that users have to edit HTML for a basic indent.

**Comment by phpbits** [comment]
@michaelswengel @PaddyWhacks I've added indent and outdent formats on [EditorsKit](https://wordpress.org/plugins/block-options/) plugin. I hope this could be a huge help. Indent will be available on the following blocks:

- Paragraph Block
- Heading Block
- List Block

Here's the preview on how the formats work. Thanks!

![Gutenberg indent formats](https://user-images.githubusercontent.com/3365507/74141664-51a40180-4c32-11ea-87f8-f55a8e3763cf.gif)

**Comment by michaelswengel** [comment]
Thanks Jeff. Sadly, this sort of plugin shouldn't be necessary. Hence 
our concerns here.

**Comment by wpericam** [comment]
I've worked on several sites recently where this was an issue (not being able to indent the first line of a paragraph). A plugin or CSS shouldn't be necessary for a paragraph block, as others have mentioned above, because this is a common formatting need for paragraphs. Also, not all users have access to these features (ie. CSS and plugins). 

Just wanted to add that I've run into this 3 or 4 times in the last month.

**Comment by jdoree** [comment]
Agreed that this should be a native feature. Its omission is shocking.

**Comment by ricjcs** [comment]
I also request this option and I even suggested it to Wordpress.com support

**Comment by LukaszJaro** [comment]
Yes, just noticed the tech writer I work with is using spaces to indent paragraphs: `<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; on and on..</p>`

**Comment by devisan** [comment]
...and now they've removed indent from the Classic Block. Why?

**Comment by paaljoachim** [comment]
I am using the Gutenberg plugin version 8.4.
At present time the easiest method is to add the Classic Block and use the Indent icon.
(The below is in Norwegian.)

<img width="869" alt="Screen Shot 2020-07-05 at 10 49 04" src="https://user-images.githubusercontent.com/5323259/86528991-484f5600-bead-11ea-81ca-9e8dca34b48d.png">

There are a lot of areas in Gutenberg core to focus on. This feature just has not yet been added to the Paragraph block.
When someone has the time to add the feature it will likely make its way into the drop down similar to what Jeffrey did for EditorsKit.

@ellatrix I am just pinging you here so that you get a heads up about this issue.

**Comment by devisan** [comment]
Like I said above, but you apparently didn't believe, the option has been removed recently. On all my sites. It was there a couple of months ago, but it's gone now. That's why I posted here. 
<img width="896" alt="Screen Shot 2020-07-05 at 11 10 36 AM" src="https://user-images.githubusercontent.com/12875318/86536816-3a4f0480-beb0-11ea-85b3-e11d338a42e1.png">

**Comment by paaljoachim** [comment]
Hey @devisan 

I worked with a client site yesterday and could not find indentation in the paragraph block in Gutenberg so I did some searching. I added the above comment to how I indented using the **classic block** directly in Gutenberg and that worked alright. It is not believing or not, but what I did to create a work around. Your toolbar looks different then the Classic Block toolbar in Gutenberg.

Example from a local site:
Using the theme Twenty Twenty.


Here is the toolbar with the Classic Editor plugin installed and activated. Indentation icons are seen in the second row.
![Screen Shot 2020-07-05 at 18 44 08](https://user-images.githubusercontent.com/5323259/86537469-8bcab400-beef-11ea-8d14-5596aa292435.png)


Here is the toolbar with the Gutenberg plugin 8.4 installed and activated. (Deactivated the Classic Editor plugin)
![Screen Shot 2020-07-05 at 18 41 56](https://user-images.githubusercontent.com/5323259/86537418-40180a80-beef-11ea-8f96-392d19c785eb.png)

It looks like you might be using the TinyMCE Advanced plugin. It should have a way to bring back indentation through a kind of settings page.

Anyhow this issue is about getting indentation into Gutenberg.

**Comment by automattic-ian** [comment]
Getting some user feedback to add an indent capability.

**Comment by PaddyWhacks** [comment]
> @michaelswengel @PaddyWhacks I've added indent and outdent formats on [EditorsKit](https://wordpress.org/plugins/block-options/) plugin. I hope this could be a huge help. Indent will be available on the following blocks:
> 
> * Paragraph Block
> * Heading Block
> * List Block
> 
> Here's the preview on how the formats work. Thanks!
> 
> ![Gutenberg indent formats](https://user-images.githubusercontent.com/3365507/74141664-51a40180-4c32-11ea-87f8-f55a8e3763cf.gif)

Wonderful, thanks Jeff. Still should be in the core functionality of Gutenberg, but awesome workaround until its added

**Comment by paaljoachim** [comment]
Heya Ian @automattic-ian 

It is awesome that you are looking into getting user feedback.
Looking at the existing "More rich text controls" drop down.

<img width="574" alt="Screen Shot 2020-07-28 at 11 11 37" src="https://user-images.githubusercontent.com/5323259/88644341-210e3200-d0c3-11ea-8355-31665e931562.png">

It would be nice to add increase and decrease indent into the drop down menu.

@ellatrix Ella, I am pinging you about this issue, as I think you might want to know about it.

**Comment by ellatrix** [comment]
Indenting a paragraph should not be added at the rich text level, but at the paragraph level, similar to alignment. You cannot control the paragraph element with rich text, only the contents. For indentation you need to add a class or style to the paragraph element.

**Comment by supernovia** [comment]
Noting another request for indentation:
https://wordpress.com/forums/topic/how-to-indent-using-block-editor/

For what it's worth I agree it should go in the paragraph styles block, although I have seen some folks ask for indentation to write poetry, when they don't want to change their font like the poetry block can.

**Comment by aristath** [comment]
Just a note here:
There is currently an undergoing effort to bring padding & margin controls to all blocks.
Once that is implemented this one will also be solved.

**Comment by supernovia** [comment]
> There is currently an undergoing effort to bring padding & margin controls to all blocks.
Once that is implemented this one will also be solved.

I'm not sure that would cover indentation of paragraphs if people want to indent those.

**Comment by garretthyder** [comment]
> Indenting a paragraph should not be added at the rich text level, but at the paragraph level, similar to alignment. You cannot control the paragraph element with rich text, only the contents. For indentation you need to add a class or style to the paragraph element.

From discussing in a scrub with @paaljoachim I wonder if we could instead add it to the alignment menu as indent/outdent;
<img width="349" alt="Screen Shot 2020-10-20 at 11 15 29 PM" src="https://user-images.githubusercontent.com/8726005/96680628-b881ca80-132a-11eb-8de4-6a9c5bbc73e7.png">
We could use icons you find in most word editors;
<img width="65" alt="Screen Shot 2020-10-20 at 11 16 21 PM" src="https://user-images.githubusercontent.com/8726005/96680644-c20b3280-132a-11eb-9d39-c1a9aeb6e89b.png">

**Comment by DavidRuaune** [comment]
garretthyder - "We could use icons you find in most word editors ..." would be great. That's what you used to have!

**Comment by garretthyder** [comment]
> garretthyder - "We could use icons you find in most word editors ..." would be great. That's what you used to have!

Ah right, thanks @DavidRuaune, I forgot there was already icons present for that in the Classic Editor so we have the dashicons we'd need.

**Comment by poojashetty18** [comment]
Got some user feedback to add an indent capability.

**Comment by paaljoachim** [comment]
It would be great to get a status update on this issue.
Thanks!

**Comment by jerrysarcastic** [comment]
Also requested in https://wordpress.com/forums/topic/paragraph-feature/

For the time being I gave the classic block option as a workaround, but is it not correct that we will be retiring this block eventually? I noted this in the description for the [classic editor plugin](https://wordpress.org/plugins/classic-editor/):

> Classic Editor is an official WordPress plugin, and will be fully supported and maintained until at least 2022, or as long as is necessary.

That does not make it sound like the classic editor will be around indefinitely (but will instead sunset at some point) so does it seems safest to assume that the classic block functionality may also be removed around the same time?

**Comment by ricjcs** [comment]
> That does not make it sound like the classic editor will be around indefinitely (but will instead sunset at some point) so does it seems safest to assume that the classic block functionality may also be removed around the same time?

The classic block will no longer be officially supported, but the classic block will not disappear, even because of the old posts.

In fact, the classic block is equivalent to not having a block. If you look at the code of a post that has some classic block, you will see that the html code appears without any block.

But indentation was something that should be part of the paragraph block, so that it was not necessary to insert the classic block just for that.

**Comment by paaljoachim** [comment]
Another way to handle this issue (for now at least) is this issue: 
Plain quote style (indent) #28524

**Comment by Sandstromer** [comment]
Could an indent option be added to _Text settings_ below the _Drop cap_ option, like so:

![paragraph-text-indent](https://user-images.githubusercontent.com/76742815/108624734-a92c9e00-743e-11eb-9ad3-6dfe484c5839.png)

The CSS could be included in the paragraph stylesheet, something like:
```
.has-indent {
    text-indent: 2em;
}
```

As the drop cap is visually applied to start of the paragraph, this would make it more consistent as the indent is also visually applied at the start of the paragraph.

**Comment by aristath** [comment]
Adding an indent option to paragraph blocks IMO would be wrong...
I can think of 2 scenarios where one would want to indent text:
1. If it's a quote
2. If ALL paragraphs are indented because that is what the design requires.

In the 1st case, a quote block should be used and not a paragraph block because the paragraph would be semantically incorrect.
In the 2nd case the theme should style all paragraph blocks.

If a site/theme does indeed want this as an option in paragraphs for whatever reason, then it should be added as a block-style and not an option:
```php
register_block_style(
    'core/paragraph',
    array(
        'name'         => 'indented',
        'label'        => esc_html__( 'Indented', 'my-theme' ),
        'inline_style' => 'p.is-style-indented { text-indent: 2em; }',
    )
);
```

**Comment by paaljoachim** [comment]
Thank you Ari!

Btw to indent the whole paragraph: https://ulyssesonline.com/2011/08/04/indent-entire-paragraph-using-css/
One can instead of adding text-indent use padding.

**Comment by mtias** [comment]
Closing this in favor of #28524.

**Comment by ricjcs** [comment]
In my opinion there are other reasons to use paragraph indentation besides quote (although it is probably the most used), such as an introduction, to highlight a paragraph, etc.

Also, the plain quote style in many themes continues with the theme style instead of just the indented paragraph, and it also doesn't make sense to use this option if it's not a quote.

For me, and in my opinion, the plain quote style does not completely replace the functionality of the Classic Block.

Is there a possibility that this topic will be reopened?

On Wp-calypso I noticed that a issue about this topic remains open: [Gutenberg: Add indents to paragraphs](https://github.com/Automattic/wp-calypso/issues/30051)
