### ISSUE TITLE
JavaScript Translation not loading >= 5.2.0 at ja.

### ISSUE THREAD

**Issue by torounit** [WordPress/gutenberg#14573]
**Describe the bug**
JavaScript Translation not loading >= 5.2.0 at ja. 
In 5.1.0 loading success load translation in js.

In the case of of it_IT, success load translation any version.

Translation file exist < 5.3.0 on it_IT.
But, In the case of ja, it exists only up to 5.0.0.

https://downloads.wordpress.org/translation/plugin/gutenberg/5.3.0/it_IT.zip
https://downloads.wordpress.org/translation/plugin/gutenberg/5.0.0/ja.zip

Require Translation json file Gutenberg 5.2.0 ?

**Comment by ocean90** [comment]
5.0.0 is the latest language pack version for Japanese as you can see on https://translate.wordpress.org/projects/wp-plugins/gutenberg/language-packs.

Newer language packs are not available because there are a few missing/not approved translations at https://translate.wordpress.org/projects/wp-plugins/gutenberg/dev/ja/default.
