### ISSUE TITLE
I don't have result when searching pro a term or phrase, who is in "Reusable Block"…

### ISSUE THREAD

**Issue by Nemzag** [WordPress/gutenberg#14595]
**Describe the bug**
I try to search articles, containing term's or phrase’s,
who are in reusable block,
I don't get any results !!!

**To Reproduce**
1. Go to Search Bar
2. Type a sentence, who is in a reusable block,
3. No results found !!!

**Expected behavior**
Results should be shown !!!

**Desktop (please complete the following information):**
 - OS: Windows 10
 - FireFox & Chrome
 - Both with last version.

**Comment by swissspidy** [comment]
Since reusable blocks are only referenced in the post content and not actually copied. That's why it is possible to update a reusable block once and have the changes reflected everywhere it is being used.

If you require 100% accurate search results, the best option is to use a dedicated search engine.

Related: #3739

**Comment by Nemzag** [comment]
I use an free WordPress.com site, I don't have any plug‑in,
and I don't want to use one, and to pay pro it…
Please in the future, find a solution…
Thank you.

**Comment by nerrad** [comment]
I'm going to close this in favor of the discussion happening in #3739.
