### ISSUE TITLE
Empty values not getting saved in the post_content

### ISSUE THREAD

**Issue by Balachandark** [WordPress/gutenberg#14629]
**Describe the bug**
I have created a new Heading block. For padding options, I have used the Range Control. I have provided 15 as the default value for it. I get the default value 15 in the editor. Whenever the value is changed the value gets updated to the post_content but when I reset the values to blank then the values are not updated to the post_content hence the default values are visible even if I save the block with empty values.

**Expected behavior**
I expected the empty values to be stored in the post_content so that I would be able to differentiate between the values that the user has provided and the default values.

**Video**
Please refer to this video - [https://cl.ly/d04a60bae966](https://cl.ly/d04a60bae966).

**Desktop (please complete the following information):**
 - OS: Windows 8
 - Browser: Chrome
 - Version 73.0.3683.86 (Official Build) (64-bit)

**Additional context**
- Gutenberg Version 5.3.0.

**Comment by swissspidy** [comment]
I don't see any bug here 🤔 

If your default value is 15 and the user changes the value to 14 and then back to 15, why should it matter for your application whether the value is now 15 or empty.

And when you click reset, the value is removed and your default should be applied.

**Comment by Balachandark** [comment]
The problem that I am having is that I want the default values to be applied when the block is added to the page i.e. 15, but when the user resets the values then I don't want the default values to be applied, but as the user has provided empty values so it should inherit its parents CSS.

**Comment by aduth** [comment]
There were some recent revisions to how the RangeControl (and specifically the reset behavior) is implemented (see #12952). It may be worth testing again in the latest version of the plugin to see if the expected behavior is present.

To the original request, however: It is intentional that if a value is reset to its default, it would not be assigned in the generated attributes of a block. It is done this way so that, for example, the default could be changed in the future and all existing content which do not have a specific value assigned would automatically begin using this new default.

**Comment by youknowriad** [comment]
Closing, let's reopen if needs more consideration.
