### ISSUE TITLE
New Block: Logos

### ISSUE THREAD

**Issue by frontdevde** [WordPress/gutenberg#14665]
**Is your feature request related to a problem? Please describe.**

I want to propose a new block, the "logos" block. The "logos" block is a list of logos that can be used to, e.g., display logos of customers, partners, sponsors, etc. and link out to them directly.

![logos-wireframe (1)](https://user-images.githubusercontent.com/1562646/55078848-078d4e00-5069-11e9-97f6-378bdd14b6bb.png)

**Describe the solution you'd like**

The initial functionality for this block should include:

- Ability to add a link to an external URL to each logo
- TBD...

Visually we'd want to ensure that:
- Logos aren't cropped and are centered on the cross-axis
- Logos have a maximum width, so they do not scale to full width
- When there are only a few logos, we’d like them to be centered

**Describe alternatives you've considered**

With the currently existing set of blocks, it is not possible to achieve a visually pleasing result with a good user experience. We tried a combination of Columns > Column > Image blocks for a similar looking section. The user experience of adding/removing logos, unfortunately, was far from intuitive. Similar issues arose when we tried to use the gallery block for this purpose. In addition, Gallery images crop by default and can't be linked to an external URL. When the crop option is “off” the images are placed on the cross-end line on the site. For logos, it’d make more sense if the logos are centered on the cross-axis. When the gallery has a small number of images, say 3, the CSS makes images to fill the space. This makes sense for a gallery, but not with logos because the logos become big. When there are only a few logos, we’d like them to be centered rather than to be left aligned.

**Comment by frontdevde** [comment]
Current status: I'm working with @thomaguillot to further define the functionality and figure out a good UX for the block options, etc.

**Comment by aduth** [comment]
Related Slack conversation ([link requires registration](https://make.wordpress.org/chat/)):

https://wordpress.slack.com/archives/C02QB2JS7/p1553698496980800

**Comment by paaljoachim** [comment]
Great initiative!

My initial response is mixed.
As it would be great to get this working with image blocks next to each other with aligning all of them to the left. Which would mean looking at various ways in how to improve the image block.

But I think that adding a logos block is a good idea as an user will likely look for specific blocks to do specific things. Such as adding logos to the bottom of a page. 

Personally I would prefer an image block that could do this in addition to a logos block.

There has been some talk of what belongs in core and not. Well there are lots of video embed blocks and it seems one can just paste an url from a lot of sites into the default paragraph block and have the video embed just show up instead of specifically selecting an embed block. So I am all for more variety of useful blocks.

**Comment by mrleemon** [comment]
Wouldn't make more sense to add the ability to link to external sites in the already present Gallery block?

**Comment by strarsis** [comment]
Very related: Add SVG image file support to WordPress core?
Currently I have to use a separate plugin for allowing SVG files.

**Comment by paaljoachim** [comment]
Related:
"Add an Icons block"
https://github.com/WordPress/gutenberg/issues/16484

**Comment by mtias** [comment]
It seems the icon block would cover most of this use case.
