### ISSUE TITLE
Group Block: add ability to alter padding values

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#14747]
The Section Block currently has padding added when a background color is set. It would be good to be able to adjust this setting regardless of whether there is a background color set.

**Describe the solution you'd like**
A UI to enable the adjusting of the Block inner padding. This should

* Allow pixel level adjustment of the Block padding
* Allow adjustment of the 4 values independently of each other or as a single value

**Potential Considerations**

* What should happen with different viewport sizes? For exmaple a large padding that looks great on large screens would look terrible on small screens. How do we handle this?

**Comment by youknowriad** [comment]
I think there's already an issue about this (related to responsive controls), this might be a duplicate.

**Comment by paaljoachim** [comment]
I would think that the Group block could go ahead as an example on how to add block specific padding/margin controls. Getting it in place so that down the line it could also be added to other blocks.

I am adding in some issues.

Block-specific responsive controls
#13363

Add padding and margin for blocks, and get rid of Spacer block.
https://github.com/WordPress/gutenberg/issues/11824

Add Block: Responsive
#6650

Support for Responsive Columns
#6048

**Comment by mtias** [comment]
I like starting with this block to see how specific controls might work.

**Comment by getdave** [comment]
@mtias I've started work on an implementation of this.

**Comment by mapk** [comment]
I'm removing the `Needs Design` label because it looks like the design work in happening in the PR.

**Comment by mtias** [comment]
@ItsJonQ could we look at enabling the padding control from _Cover_ here?
