### ISSUE TITLE
Merely selecting a block after load creates undo level

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#14766]
**To Reproduce**

1. Create a new post.
2. Create a new paragraph with some text.
3. Save the post.
4. Reload the page.
5. Select the paragraph block.
6. Observe that the undo button is not disabled any longer.

**Expected behavior**

I don't expect block selection to create undo levels.

**Additional context**

I see the following actions when I select a block:

```js
{type: "FETCH_REUSABLE_BLOCKS", id: undefined}
{type: "SELECT_BLOCK", initialPosition: null, clientId: "adb9ef30-61f7-45c3-b785-01fc5ca630e3"}
{type: "RECEIVE_REUSABLE_BLOCKS", results: Array(1)}
{type: "UPDATE_SETTINGS", settings: {…}}
{type: "RECEIVE_BLOCKS", blocks: Array(1)}
{type: "RESET_EDITOR_BLOCKS", blocks: Array(1), shouldCreateUndoLevel: false}
{type: "FETCH_REUSABLE_BLOCKS_SUCCESS", id: undefined}
```

So it looks like it has something to do with reusable blocks fetching? Cc @noisysocks @aduth.

**Comment by ellatrix** [comment]
The action that grabs my attention is `RESET_EDITOR_BLOCKS`. Why are blocks being reset after block selection? The user didn't do anything that should trigger a reset?

**Comment by aduth** [comment]
I'd need to spend some time investigating to understand, but on hunch I think it's related to one of either reusable blocks triggering `RECEIVE_BLOCKS`, or as part of the refactor of a separate block editor module and how it treats "persistent" changes.

https://github.com/WordPress/gutenberg/blob/495f54cadb6cf1aac4b531fa715e3afcf18729e7/packages/block-editor/src/store/reducer.js#L178-L240

Clicking on a paragraph triggers autocomplete to do the fetch for reusable blocks so that it can populate results in the slash command.

**Comment by aduth** [comment]
I seem to be observing that that this "dirties" the post as well, which was intended to be explicitly not the case with the implementation of #13088 . If confirmed, I'd suggest it be prioritized for a fix to be included with the WordPress 5.2 release. As a regression, it should be reasonable to expect and to implement a test as part of the `change-detection.test.js` suite.

**Comment by aduth** [comment]
There may be separate issues here between how the `RESET_EDITOR_BLOCKS` impacts undo history and how it impacts change detection.

For the original issue describing undo history, this may in-fact be the expected behavior, or at least there's a specific condition which forces that an undo history entry be created when history is currently empty, even if the action (`RESET_EDITOR_BLOCKS`) wouldn't otherwise create one.

https://github.com/WordPress/gutenberg/blob/bb3b77ae4521d8f6246b765eff1afe8345dd91cc/packages/editor/src/utils/with-history/index.js#L122-L129

...specifically the `! past.length` condition, introduced with #4956, including some discussion at https://github.com/WordPress/gutenberg/pull/4956#issuecomment-365733987 .

---

For change detection, it may be a matter of configuring `withChangeDetection` to either reset at or explicitly ignore the `RESET_EDITOR_BLOCKS` action:

https://github.com/WordPress/gutenberg/blob/bb3b77ae4521d8f6246b765eff1afe8345dd91cc/packages/editor/src/store/reducer.js#L144-L148

Looking at the implementation prior to [changes](https://github.com/WordPress/gutenberg/pull/13088/files#diff-d41c21a0efc38fef548f4181bbc539f3) in #13088, we seemed to include at least a few `ignoreTypes`:

https://github.com/WordPress/gutenberg/blob/4be0a36c703a45cdcac67807d30e2e4f26c92343/packages/editor/src/store/reducer.js#L411-L416

It's not immediately clear to me why these were dropped (cc @youknowriad ).

**Comment by aduth** [comment]
> ...specifically the `! past.length` condition, introduced with #4956, including some discussion at [#4956 (comment)](https://github.com/WordPress/gutenberg/pull/4956#issuecomment-365733987) .

As an action item, I might propose to consider whether the `! past.length` condition could be removed or, at the very least, updated to force the next action to behave as to merge ("overwrite") state. This latter approach doesn't resolve the issue that if, immediately after selecting the block, the user were to press Undo, the `RESET_EDITOR_BLOCKS` action would be inadvertently undone.

>Looking at the implementation prior to changes in #13088, we seemed to include at least a few ignoreTypes: _[...]_ It's not immediately clear to me why these were dropped

I will plan to explore a solution here, specifically seeking to restore the removed `ignoreTypes`.

**Comment by aduth** [comment]
One possible action which can incidentally serve as a solution: Rather than trigger to fetch reusable blocks immediately upon block selection, the fetch should only occur after some initial typing. This would help avoid the scenario where the fetch results are the first action dispatched to the editor store.

**Comment by aduth** [comment]
> > Looking at the implementation prior to changes in #13088, we seemed to include at least a few ignoreTypes: _[...]_ It's not immediately clear to me why these were dropped
> 
> I will plan to explore a solution here, specifically seeking to restore the removed `ignoreTypes`.

Spending more time looking at this, I understand now why `ignoreTypes` is no longer applied for this action type, since from the editor state, `REPLACE_EDITOR_BLOCKS` is the [sole way it tracks blocks](https://github.com/WordPress/gutenberg/blob/ed31b3a27be2faf6a60a52609e4e13c263989bfe/packages/editor/src/store/reducer.js#L149-L155) and changes in this value are necessarily tracked to support the unsaved changes prompt.

I'd wondered then if it would be worth tying this to the `shouldCreateUndoLevel` property of the action dispatched. While this is workable, it doesn't seem the appropriate solution given that the property corresponds to [`onInput` callbacks](https://github.com/WordPress/gutenberg/blob/ed31b3a27be2faf6a60a52609e4e13c263989bfe/packages/editor/src/components/provider/index.js#L200-L204) from `BlockEditorProvider`, something which seems a change worth considering (a branch with this proposal can be seen at [`fix/reset-editor-block-change-detection`](https://github.com/WordPress/gutenberg/compare/fix/reset-editor-block-change-detection)). 

Rather, it seems the issue is that we shouldn't expect `RESET_EDITOR_BLOCKS` to ever occur in `editor` as a result of the reusable blocks being received. The way this seems to be happening is that receiving the reusable blocks [triggers a `receiveBlocks` action](https://github.com/WordPress/gutenberg/blob/ed31b3a27be2faf6a60a52609e4e13c263989bfe/packages/editor/src/store/effects/reusable-blocks.js#L220-L222) in the `block-editor` module, where presumably this should be treated as effectively equivalent to a ["syncing incoming value" operation](https://github.com/WordPress/gutenberg/blob/ed31b3a27be2faf6a60a52609e4e13c263989bfe/packages/block-editor/src/components/provider/index.js#L84-L89) and not bubble back up to editor by its `onChange` or `onInput` (but it does).

**Comment by aduth** [comment]
While related, I've split off the problem of change detection to its own issue at #14910, which I've discovered to be affecting more flows than just the block selection (opening an inserter or editing a post containing a reusable block can also trigger the prompt).

**Comment by aduth** [comment]
One of #14915 and #14916 should resolve this; the latter being the more "durable" solution.
