### ISSUE TITLE
Add whitespace below the last block on the edit post screen

### ISSUE THREAD

**Issue by jeremyfelt** [WordPress/gutenberg#14852]
**Is your feature request related to a problem? Please describe.**

When writing a long blog post (OSX, Firefox 66.0.2, WP 5.1, Gutenberg 5.4.0), the focus of the writing area shifts as you write until the content is long enough to fill the screen. At that point the focus stays at the bottom of the browser window. I find my self wishing I could scroll the bottom line up closer to the middle of the screen instead. I'm on a laptop right now, but I have the same trouble on a large desktop monitor. It *seems* like Chrome handles it a bit better, but I haven't done extensive testing.

I've included a screenshot, though I'm not sure how helpful it really is. Imagine that this takes up the entire laptop screen and to see the bottom line of text, I'm almost staring at the keyboard. :)

<img width="788" alt="Screen Shot 2019-04-05 at 2 43 33 PM" src="https://user-images.githubusercontent.com/286171/55658111-5cd80680-57b1-11e9-9307-3f6a121f77f3.png">

**Describe the solution you'd like**

I'd like a good chunk of whitespace below the last block that I can use in combination with the browser scroll to move the text up the screen a bit while writing.

**Comment by jasmussen** [comment]
I hear you, and I personally have this particular fix VERY high on my wishlist, for all the reasons you've mentioned.

We actually tracked this under the term "Typewriter linebreak behavior" way back in #353. At one point @ellatrix even had the feature working, but I think there were some performance issues that made us turn it off again, I can't recall.

The challenge here is that we can't actually just add padding to the bottom — or rather, we can, but as you keep typing, the scrollbar won't leverage it. You'll still keep typing right until the text is at the bottom of the screen, before the browser starts scrolling again. We have to write some clever JS in order for the scrollbar to stay in sync with where the caret is, and keep some whitespace below where you write.

---

As I wrote all of that, I realized that I was describing the utopian solution. But perhaps you just wanted some extra padding at the bottom to _manually_ scroll, is that the case? Because I can PR that up relatively quickly.

**Comment by draganescu** [comment]
Hi @jasmussen Riad just closed two issues in favor of this one. In your comment you said:

> But perhaps you just wanted some extra padding at the bottom to manually scroll, is that the case? Because I can PR that up relatively quickly.

Yes! That is exactly what I want, not some fancy typewriter mode, just the ability to scroll once in a while and lift the bottom of the post higher on the screen.

Not sure if @jeremyfelt or @Studio384 need more, but I for one would be very happy with the simplest implementation :)

**Comment by jasmussen** [comment]
Yep. Let's go with that.

The simplest solution is to add just some whitespace at the bottom. It would require you to scroll yourself, no typewriter effect for now.

See also this comment by @talldan, though: https://github.com/WordPress/gutenberg/issues/14942#issuecomment-482494101 -- we'll want the extra space to be clickable to set focus in the text just like when you click the whitespace below an empty appender currently. In fact the first might be as simple as setting a min-height on the click redirector.

**Comment by jeremyfelt** [comment]
> The simplest solution is to add just some whitespace at the bottom. It would require you to scroll yourself, no typewriter effect for now.

👍 I think this would be great!

**Comment by draganescu** [comment]
@jasmussen ok if I take a stab at this or did you already begin?

**Comment by jasmussen** [comment]
Feel free! But ping me any time if you need a hand.

**Comment by draganescu** [comment]
@jasmussen @jeremyfelt here is a PR #15165 with the smallest possible change that already feels awesome! :)

**Comment by mtias** [comment]
I'd love to make this happen and work on typewriter / consistent line focus as well. One thing we need to consider is that as the editor looks more and more like the front-end, the writing experience can start to suffer — it would be harder to fake the spacing at the bottom if you want to faithfully represent the front-end. However, I think we'd always have a need for a writing / distraction free mode that focuses just on text.

**Comment by draganescu** [comment]
@mtias this doesn't look like it is needed anymore owed to the new typewriter experience, which is now a default, hence I will close it.

**Comment by sparkbold** [comment]
This is a good idea but should it be hidden when there is a meta box below? Now there is a big gap between the editor and the meta box area.
