### ISSUE TITLE
Text input in Dropdown on toolbar hides toolbar when you type.

### ISSUE THREAD

**Issue by kadencewp** [WordPress/gutenberg#14890]
**Describe the bug**
When I add a text input into a dropdown or popover in the block controls toolbar as soon as you try to type into the toolbar it's hidden. I assume this has to do with the toolbar hiding when you type into the context like in a paragraph block. I'm wondering if there is any way to prevent this while typing in the toolbar.

**To reproduce**
1. Create a dropdown in the block controls of a block.
2. Inside that dropdown add a text control component
3. Try typing into the text control component.
4. It disappears along with the toolbar and nothing is ever typed.

*Note that if the toolbar is set to "top toolbar" in the editor settings this doesn't happen. It's only when in context (which I assume is the majority of users).

**Expected behavior**
I am hoping there is a way to type in the toolbar, my use case for this is a search input.

Thanks for anyone that might be able to point me to a workaround.

**Comment by kadencethemes** [comment]
ok, I found it: 
https://github.com/WordPress/gutenberg/blob/7964f381e07e06b2ac13698fd1465a4d0c16da1b/packages/block-editor/src/components/observe-typing/index.js#L148

Apparently, within a dropdown of the toolbar, I needed to add "block-editor-block-toolbar" class to get the observe-typing to correctly ignore the typing in that popover.

I am going to leave this open for now until I get some feedback because my workaround still seems like a hack and perhaps there should be a better solution.

Ben

**Comment by FerrielMelarpis** [comment]
@kadencewp Have you tried stopping the keyPress and keyDown event propagation? 
That did the work for me.

**Comment by akaufman3** [comment]
Also experienced this issue when trying to put a `TextControl` field into the `Popover`. Adding the class mentioned above on a div inside of the `Popover` that wrapped all the contents, resolved the issue for me as well. It looks like the state of the popover in my case was being triggered on the `onChange` `setState` in my TextControl - essentially closing the Popover. From what I heard from @chrisvanpatten, the writing flow sees the click in the TextControl as entry into the writing flow experience and attempts to hide the Block Tool Bar.

**Comment by chrisvanpatten** [comment]
I am definitely encountering this problem but it seems to depend a lot on the exact placement of the text input, and also (seemingly) only impacts the block if you are subscribing to a store which would cause re-renders (effectively resetting the popover's state).

The fix of adding a className does work, but absolutely feels like a hack, especially since you subsequently need to unset those styles.

**Comment by chrisvanpatten** [comment]
Fixed by #21421.
