### ISSUE TITLE
Undo: typing something after fresh post load cannot be undone

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#14950]
**Describe the bug**

**To reproduce**

1. Load a post, e.g. the demo content.
2. Type something in a paragraph block, e.g. "test".
3. Try to undo it with the button.
4. The button becomes disabled, but the post content remains unchanged.

**Expected behavior**

I expect the post content to be restored as it was when loaded.

**Screenshots**

![undo](https://user-images.githubusercontent.com/4710635/56038651-b9e43700-5d32-11e9-8e45-739915db8d77.gif)

**Comment by ellatrix** [comment]
Not sure if this is a regression, but I'm pretty sure this worked correctly before.

**Comment by aduth** [comment]
I reproduced in `master` and also in Gutenberg 5.4.0 , but it appears as though it had been working correctly in WordPress 5.1.x .

From some initial debugging, it appears related to the block editor module in #13088, specifically around how it keeps the blocks value in sync between the two stores `editor` and `block-editor`. When pressing Undo, the state is updated to the expected values in `editor` store, but it's never synced back to `block-editor`.

In testing, when pressing Undo it appears to get stuck in the **first** of the condition steps of:

https://github.com/WordPress/gutenberg/blob/0d26bba43c76617a8b6c3031bea93344ae9116a9/packages/block-editor/src/components/provider/index.js#L38-L43

Meaning:

- The new blocks value is never reflected in the block editor (`resetBlocks` is not called)
- `this.isSyncingOutcomingValue` is being unset later than we expect
   - My expectation is that it should be unset _immediately_ after calling `onChange` or `onInput`, not after the multi-second delay it took me before pressing the Undo button. This implies that it's waiting until some _next_ state change before taking effect.

**Comment by aduth** [comment]
The issue also occurs only if multiple inputs occur within the paragraph, not just a single keypress, which would seem to indicate it could be related to [undo history state merging](https://github.com/WordPress/gutenberg/blob/0d26bba43c76617a8b6c3031bea93344ae9116a9/packages/editor/src/store/reducer.js#L96-L116).

**Comment by aduth** [comment]
I further suspect it is related to the delayed explicit creation of an undo level from RichText, where this is considered _in addition to_ an actual change in blocks value when syncing the value from block editor.

https://github.com/WordPress/gutenberg/blob/0d26bba43c76617a8b6c3031bea93344ae9116a9/packages/block-editor/src/components/provider/index.js#L97-L111

Since `this.isSyncingOutcomingValue` could potentially be set without the blocks value actually changing, it means that the logic for unsetting it in `componentDidUpdate` will likely not be run immediately since there is no change in props value.

A simple solution here may be to only set `this.isSyncingOutcomingValue = true;` if the blocks value changes, since the purpose of the value is in avoiding to `resetBlocks` when it occurs as a result of a change from the block editor.

I'll give it a try.
