### ISSUE TITLE
Changelog missing for Gutenberg 5.5.0

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#15023]
**Describe the bug**
Changelog content is missing for 5.5.0: https://wordpress.org/plugins/gutenberg/#developers

**To reproduce**
1. Go to https://wordpress.org/plugins/gutenberg/#developers
2. Notice the missing changelog content for
    ````
    Changelog
    For 5.5.0.
    ````
    further below on that page.

**Expected behavior**
Changelog content, at least bugfix should be mentioned.

**Comment by talldan** [comment]
Thanks for pointing this out @starsis. I did the release, and I did update the changelog, but there might have been some formatting issues that prevented it from being parsed. Looking at the change, I think it's due to the formatting in the headers of each section:

https://plugins.trac.wordpress.org/changeset/2069867/gutenberg/trunk/readme.txt

**Comment by talldan** [comment]
I've updated that, the changelog is now present. Closing this, thanks again for making the issue.

https://wordpress.org/plugins/gutenberg/#developers
