### ISSUE TITLE
Apply Gutenberg Style to Posts in Frontend

### ISSUE THREAD

**Issue by joaosrico** [WordPress/gutenberg#15218]
Hello Everyone.

I'm new in this, but i've try to search on google, ask friends, and nothing came out.

All I want is to have the look of a blog post created with Gutenberg but on my frontend post.

I've tried to edit CSS from function.php.
I've tried to change the theme style.
I've tried to search for Gutenberg style to apply on single.php.

I still can't get it done.

How do I get the same lettering, same spacing size, same paragraph size, everything that I see in Gutenberg editor, in my post on the blog after publishing it?

If there is a thread about this, please give me the link, because i've searched for hours, using the keywords on the title of this post. and I still can't find a way..

Thank you so much for your help!

**Comment by neverin772** [comment]
I would also to add to this with the following: - 

1. How do you add core styles from gutenberg blocks to the frontend (@joaosrico).
2. How do you override these styles of each _core_ gutenberg block.

**Comment by youknowriad** [comment]
Hi There!

A quick note that this issue tracker is not used for help requests. For general help requests, please post in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/.

Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.

For your particular request, I may want to consider using a theme that provides editor styles for Gutenberg in order to show the same thing in both the editor and the frontend.

Thank you for your understanding!
