### ISSUE TITLE
Shrinkable navigation sidebar

### ISSUE THREAD

**Issue by jwold** [WordPress/gutenberg#1522]
The more I play with Gutenberg, the more it feels like a fullscreen immersive experience would be ideal. However, the current editor has that and I rarely use it since it feels like a lot of trouble to go in and out of fullscreen (it takes a click and about a second wait to open/close it).

What if we had 3 stages to the left navigation sidebar?

1. As is, full size
2. Partially collapsed (like how it shows on tablet view)
3. Fully hidden

In order to drag between these states there would be a button that appears on hover to pull the sidebar left or right. Kind of like how Things 3 does it: https://v.usetapes.com/mi3p2NxN3Z

Here's how I envision the different states:

![sidebar states](https://user-images.githubusercontent.com/3411173/27612077-ace0b520-5b49-11e7-8ce9-bb6969ff583c.png)

**Comment by brentjett** [comment]
That's a cool idea. Any reason not to do the same for the settings sidebar on the right as well? Bitbucket's latest UI update has a nice fluid implementation of sidebar resize that's worth looking at. 

![f013ssuvjv](https://user-images.githubusercontent.com/1790660/27613161-a49731d0-5b5f-11e7-98c5-0ffd06eabe6b.gif)

**Comment by jwold** [comment]
@brentjett I like the Bitbucket example!

Also, shrinking the right column the same way makes a lot of sense. We could still have the button to toggle it, but I like being able to drag it.

**Comment by jasmussen** [comment]
I agree quite a bit with the premise of this ticket, and I think there are many interesting ways to address it, including the ones suggested.

However I also think we should draw a line between what's a "Gutenberg" feature, and what's a WordPress core feature. Since this is about the navigation interface, I would posit that it should be a benefit that would be worth bringing to all of WordPress, not just the editing interface. As such I would recommend opening this ticket "upstream", so to speak ;)

Perhaps it can be positioned as an idea for how to improve the "collapse menu" interface that currently does something in this vein. I would remind, though, that no matter then specific implementation, there should probably be an explicit button action for each navigation size. 

I would personally star this ticket, as the current collapse/fold/autofold interface feels pretty complicated for what should be simple. It's also not as responsive as it could be.

**Comment by jwold** [comment]
Great suggestion @jasmussen. I've created a new Trac ticket to continue this discussion: https://core.trac.wordpress.org/ticket/41249

**Comment by jasmussen** [comment]
Awesome! I'm going to close this one then. Thanks!
