### ISSUE TITLE
"Resolve block" modal: make the columns have the same content space

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#15235]
The main purpose of the "Resolve block" modal is to provide users with a visual representation of the changs before and after the conversion that is going to happen.

Lines of code in this representation should make easy the task to visually scan lines of code and spot the differences. However, as the two columns have a different available space for their content, that's not that easy. For example, see the screenshot below:

<img width="870" alt="Screenshot 2019-04-28 at 17 15 37" src="https://user-images.githubusercontent.com/1682452/56866508-5e74a300-69da-11e9-9218-87bf99e725e0.png">

Ideally, the lines of code should have the same length in both columns.

**Comment by joybhallaa** [comment]
Can I work on this?

**Comment by afercia** [comment]
@joybhallaa sure you can!

**Comment by joybhallaa** [comment]
Sorry, I will not be able to work on this.

**Comment by foysalremon** [comment]
I think, to looks better and to get the same space for content on both column the first one should have a 15px padding on its right and the second one should have 14px instead of 15px on left because of a 1px border. 

But I need to be sure about it if there is no chance of css conflict on related element. Maybe some design feedback.

**Comment by talldan** [comment]
Fixed by #15581
