### ISSUE TITLE
Improve pasting paragraphs of text

### ISSUE THREAD

**Issue by jwold** [WordPress/gutenberg#1524]
When you paste in multiple paragraphs of text it would be great if the text block could remember the paragraph breaks. 

**What's happening right now:**

- Paste multiple paragraphs into text block
- All paragraphs are bunched together and any line breaks are removed

**Ideal state**

- Paste multiple paragraphs into text block
- All paragraphs are separated by a line break and kept in one text block

**Note:** One other way would be that pasting multiple paragraphs creates multiple text blocks, but I **don't think** that's ideal. It's easy to break a paragraph out anyway by pressing enter twice. 

Annotation:

![annotation](https://user-images.githubusercontent.com/3411173/27617511-a3b46998-5b6b-11e7-9c2c-b9586e5c4cfd.png)

**Comment by youknowriad** [comment]
Seems like a duplicate to #1442 and the work being done in #1331. Closing, feel free to reopen if there's any subtility I missed.

Also, It would be great if you can check for existing issues and PRs before opening issues. It'd help triage work.

**Comment by jwold** [comment]
@youknowriad, thanks for the help triaging this and the other ticket! I'll be more diligent about checking tickets. 

@iseulde and @jasmussen I read through #1331 and am still not sure if this feature is covered. 

If I paste in multiple paragraphs of text from another source will the #1331 PR create line breaks between each or bunch them up?

**Comment by youknowriad** [comment]
@jwold The idea is that pasting will convert the text to blocks, so multiple paragraphs of text will create multiple text blocks which is the right thing to do IMO.

**Comment by jwold** [comment]
Had a discussion on Core-Editor about this. I'm personally ok either way with creating multiple text blocks or keeping it in one text block but adding paragraph breaks. The argument for keeping in one text block is you're adding context for where you're pasting text. 

Example:

I start writing an article and add some text and an image, I then paste in a few paragraphs of text into one text block, add some more, etc. If I need to break out the text into multiple text blocks again it's really easy to just press enter twice on each one.

**Comment by youknowriad** [comment]
Note that the text block doesn't support multiple paragraphs, it's just `br`. We already explored a multi-paragraph text block before but we decided to leave this for the classic block only.

**Comment by jasmussen** [comment]
> Note that the text block doesn't support multiple paragraphs, it's just br. We already explored a multi-paragraph text block before but we decided to leave this for the classic block only.

That's the thing though, you can actually force paragraphs in there, which you shouldn't be able to:

![jun-28-2017 16-17-18](https://user-images.githubusercontent.com/1204802/27641831-4ce04cc4-5c1d-11e7-815a-a26fc3750e6a.gif)

This is a textexpander in action. But pasting multiple paragraphs in a single block does the same. 

I agree that ideally pasting multiple paragraphs like this would create multiple paragraph blocks. But I'd also be _okay_ with collapsing the `p`s into `br`s, since _typographically_ those are still paragraphs, they are just zero margin paragraphs. But yes, the former would be ideal. 

Alternately, if we detect you pasting multiple paragraphs, or textexpanding, we could convert it to "classic text".

**Comment by iseulde** [comment]
There's a PR for this waiting, which converts it all to text blocks...
