### ISSUE TITLE
Keyboard focus is not managed when dialogs close

### ISSUE THREAD

**Issue by karlgroves** [WordPress/gutenberg#15321]
Keyboard focus is not managed when dialogs close

-   **Severity:** Medium
-   **Affected Populations:**
    -   Blind
    -   Low-Vision
    -   Motor Impaired
    -   Cognitively Impaired
-   **Platform(s):**
    -   All / Universal
-   **Components affected:**
    -   Tools and Options

#### Issue description

When the "Keyboard Shortcuts" and "Options" dialogs are dismissed,
the keyboard focus is reset to the top of the page. This may be
confusing or inconvenient for users, who would expect the focus to
return to the last element they were focused on.

Keyboard and screen reader users rely on predictable and consistent
focus control to navigate the page. When this is absent, users may find
it much more difficult or impossible to navigate using the keyboard.

#### Remediation Guidance

Ideally, use JavaScript to continually track the keyboard focus
position, so that when dialogs are opened via shortcut keys, the focus
can be returned to the previously-focused element when they close.

If that's not practical, then closing these dialogs should set focus on
the "Tools and Options" button.

#### Relevant standards

-   [2.1.1 Keyboard
    (Level A)](https://www.w3.org/TR/WCAG20/#keyboard-operation-keyboard-operable)

**Note:** This issue may be a duplicate with other existing accessibility-related bugs in this project. This issue comes from the Gutenberg accessibility audit, performed by [Tenon](https://www.tenon.io) and funded by [WP Campus](https://wpcampus.org/). This issue is GUT-53 in Tenon's report

**Comment by melchoyce** [comment]
Screenshot from full report:
 
![image](https://user-images.githubusercontent.com/2846578/57184294-7a5ec580-6e6e-11e9-9060-1d2e3f99cd43.png)

**Comment by afercia** [comment]
In these cases focus should always be moved back to the "invoking context", ie. the button that toggled the modal. When invoking modals from buttons in the "More" menu, this was impossible because the More menu then closed, thus the invoking button disappeared.

As far as I can tell, this has been mitigated with the introduction of the `onFocusLoss` option in #14444. Now, focus is moved back to the "Tools and Options" button it that was the invoking context.

Notable exception: the datepicker popup, see #15329.

Worth investigating other edge cases of focus loss.

**Comment by gziolo** [comment]
It was fixed in #16964.
