### ISSUE TITLE
Add Block option is disable after update to latest wordpress version

### ISSUE THREAD

**Issue by sidd2211** [WordPress/gutenberg#15363]
Hello

I have updated to latest wordpress version, and trying to use Gutenberg editor , but i have some issue with it. i cant access the add block option as its disable and having follow error in console -

Uncaught (in promise) TypeError: Failed to fetch : https://lumen5.com/learn/wp-includes/js/dist/data.min.js?ver=4.2.1

please help me with this. Screen Shot attached .

<img src="https://lumen5.com/learn/wp-content/uploads/2019/04/gutenberg_error.png" />

Thanks

**Comment by swissspidy** [comment]
Hi there

Looks like at least one error is caused by your Anti-Malware plugin that you have installed.

Please try deactivating this plugin, and all other plugins for that matter, to see if this error still occurs.

Next, ensure that the checkbox "Disable the visual editor when writing" in your user profile is **not** checked.

After that, go to the editor again, click on the three dots in the top right corner, and select "Visual Editor"

**Comment by sidd2211** [comment]
Hello Swissspidy,

Thanks for the reply, i tried both the solution you mentioned above, but still no luck for me. However in addition , the add block is working with pages, but not with the post. i am not sure what is causing this.

further help appreciated .

Thanks
Sid

**Comment by sidd2211** [comment]
Anybody can help me with this ??

**Comment by youknowriad** [comment]
Sorry you're having trouble with this unfortunately we can't help here. You'll have to figure out what's blocking the JavaScript files from being loaded properly.

If you're still looking for help, please post in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/.

Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.

Thank you!
