### ISSUE TITLE
Insert from URL missing when adding an image

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#1536]
This functionality is missing, whilst it may just not be implemented yet, it would be great to at least track that it doesn't get missed out.

**Comment by karmatosed** [comment]
A user also brought this up themselves testing:

"Is it not possible to get an image via an url? If so, I could not find a way to do it."

**Comment by westonruter** [comment]
Yeah, there probably needs to be a URL input field that appears in the placeholder, so somewhat of a combination of the current Image placeholder and the Embed placeholder:

![image](https://user-images.githubusercontent.com/134745/27991204-091e81a4-6424-11e7-805b-bd921ee5a51f.png)

But, with that in place, should a user be able to say, replace an image inserted via URL to then be an image from the media library? And vice versa, should an image added from the media library be able to be replaced with an external image URL without having to replace the entire block? We can do this in the Image widget since the media modal has the two tabs for selecting from the media library and selecting via URL:

![image](https://user-images.githubusercontent.com/134745/27991212-488d28fe-6424-11e7-9128-c8d8bef3a32f.png)

**Comment by imath** [comment]
Hi,

I've been thinking about this lately. And i'm wondering if creating a specific `core/media-url` would be a better idea for Gutenberg. Because some users might also need to add external urls for Video and Audio.

Into the classic editor, It's possible to paste an external url to an image of course, but it's also possible to paste an external url to a video or an audio file. Once pasted, the image tag, video tag or audio tag are output into this editor.

So here's what came to my mind about it:

1. The new `core/media-url` could show an url input and output the image/video/audio tags according to the file extension on form submit.
2. The "Transform into:" button of this new block could show the `core/image` if it's an external image, the `core/audio` if it's an external audio, etc..
3. If "Transform into:" is clicked the external media could be `media_handle_sideload()`-ed and added to the WP Media Library.
4. As the contributor role shouldn't be able to `upload_files` (#3672) this new block could be used instead of the blocks needing the `upload_files` capability.
5. It would avoid editing the `core/image`, `core/audio`, `core/video` blocks to add a similar code to let them deal with external urls.

**Comment by talldan** [comment]
My thoughts are that this should become part of the Image Block. I think that's where the user would naturally expect to find this.

The audio/video blocks already seems to have this, so it should be possible to make it consistent. 

I think there are two main changes.
1) Change the placeholder for the image block so that it's consistent with audio/video:
![screen shot 2018-08-13 at 5 56 19 pm](https://user-images.githubusercontent.com/677833/44025424-b0265b54-9f22-11e8-9393-7a60564564f5.png)

2) Change what happens when the edit button is pressed on the toolbar (this could behave in exactly the same way as the media block, display the placeholder again.)
![screen shot 2018-08-13 at 5 57 15 pm](https://user-images.githubusercontent.com/677833/44025400-9fc7d940-9f22-11e8-8e2f-a81e0b706531.png)

I think the most difficult question is whether these changes carry over to the Gallery Block (and if so, how?). That should probably be a separate issue.

@karmatosed what are your thoughts?

**Comment by imath** [comment]
FYI in the last patch of https://github.com/WordPress/gutenberg/pull/4155 I’ve added url inputs to images

imath.
https://imathi.eu



imath.
https://imathi.eu

**Comment by talldan** [comment]
@imath Oh no, I'd just about finished working on a branch that also adds the change when I saw your comment!

When do you think you'll get a chance to address the feedback on your PR? I'm more than happy to help out if you need some assistance with it and don't have the time to look at it.

If its something you can't look at I can also work on separating out the URL input change into a separate PR.

A few options available, let me know what you think.

**Comment by imath** [comment]
Hi @talldan

I’m feeling really bad I haven’t found the time to update the PR, sorry about it. I think the input URL for media blocks or even the File block is very linked to the upload_files capability : it’s a way to let the contributor role use and edit the media blocks. So I think progress should be made on #4155 to solve #1536. That being said the fact I can’t find time to work on it shouldn’t block progresses on #4155. So I’m more than happy if you can bring your help on it or even take it over. I’m afraid I’ll need one more week before I can begin working on it.

**Comment by imath** [comment]
@talldan If it can help, I just invited you on my fork so that you can have push access on it. The branch for #4155 is `add/blocks-capability`

**Comment by talldan** [comment]
@imath Thanks for that, I'm very happy to take a look at #4155 to see whether I can progress it. Will start on that tomorrow.

**Comment by talldan** [comment]
@imath - I've been working on it for a bit now, but I just can't forsee #4155 being merged. It's too difficult to review because of the way comments are hidden by github. 

I propose splitting it up into the following parts:
1. Make it so that external URLs can be used on image blocks
2. Roll out MediaUploadCheck, but perhaps make is inactive so the UI appears the same as it is now.
☝️ I think those changes should be not too difficult to get reviewed and merged. MediaUploadCheck touches quite a few places, so it'd be good to get it into the codebase.

3. Redux handling of upload permissions and preloading of OPTIONS request. Make the MediaUploadCheck active.
☝️ This bit requires more critique during review and possibly exploration of alternative ways of tackling the problem. I'm not sure that will happen on the #4155 PR as the feedback just gets lost.

I'll make sure you're credited for all your hard work on all three parts. Let me know what you think.

**Comment by imath** [comment]
@talldan the only downside of it is precisely the UI will keep on being buggy for the contributor role. I wonder if it doesn't impact the Super Admin role on multisite btw... #4155 is 8 months old and it's being punted to later at almost each realease.

New blocks were added like the inline image & the file one. IMHO, this doesn't seem to be the right priority to me. I would expect to first fix the capability issue, then add new media blocks...

That being said. I understand your point of view, and i'm fine with your plan. At least, the contributor role will be able to add an image once he got stuck by the buggy UI with the media library 😉

**Comment by imath** [comment]
Oh I forgot the most important @talldan : thank you so much for the progresses you’ve made on #4155 💪👍

**Comment by talldan** [comment]
@imath - I've decided to combine 2 & 3 from my message. I just couldn't forsee them being merged separately. It would be too hard to validate that everything works correctly.

New PR is here - https://github.com/WordPress/gutenberg/pull/9301. Lets hope we get some good traction on this now.

**Comment by imath** [comment]
Awesome work @talldan thanks a lot 🤞

**Comment by karmatosed** [comment]
Just removing design for now as we're iterating in the PR.
