### ISSUE TITLE
Would be nice if ColorPalette onChange handler would return selected color object

### ISSUE THREAD

**Issue by ranostaj** [WordPress/gutenberg#15559]
### Description

I have a problem to easily get selected color name/value from ColorPalette Component
To get the actual selected color name I have to do some workaround.

The `onChange` handler receives as an argument selected color (string) (the color attribute from a color object). 
Instead, I'd expect to be provided the whole selected color object from the colors array

### Example

Block attributes: 

```JSON
"attributes": {
  "color": {
      "type": "string",
      "default" : "bg-white"
   }
}
```
...somewhere in Component:

```JavaScript
import  {ColorPalette} from '@wordpress/editor';
...
.....
const {color} = props.attributes;
const colors = [ 
	{  name: 'Yellow', value: 'bg-yellow', color: '#FFCE00' }, 
	{  name: 'Gray', value: 'bg-gray-thin', color: '#f4f4f4' }, 
	{  name: 'White', value: 'bg-white', color: '#FFFFFF' }, 
];
<ColorPalette 
    disableCustomColors
    value={getColorValue(color)} 
    colors={colors} 
    onChange={setBackgroundColor} />
 
```
### Problem

Now my onChange handler has the following logic:

```JavaScript
const setBackgroundColor = (selectedColor) => {
       // find specific color object based on the value provided by onChange handler
      const color = colors.find(c => selectedColor === c.color)
      // then set the named value in this e.g. "bg-yellow" wich i need to pass to the component
      props.setAttributes({color:color.value})
}

```

Also in order to retrieve and pass correct value into ColorPalette Component I need to to following logic:

```JavaScript
const getColorValue = (color) => colors.find(c => color === c.value).color;

```

### Expected behaviour

I'd like to have the whole color object passed into onChange handler:

``````JavaScript

// the selected color should be a selected array item -  object e.g.
// "{  name: 'yellow', value: 'bg-yellow', color: '#FFCE00'}" 

const setBackgroundColor = (color) => props.setAttributes({color:color.value})
```

**Comment by swissspidy** [comment]
> Now my onChange handler has the following logic:
> Also in order to retrieve and pass correct value into ColorPalette Component I need to to following logic:

`getColorObjectByColorValue` and `getColorObjectByAttributeValues` do this for you.

> I'd like to have the whole color object passed into onChange handler:

What if someone chooses a custom color? `color.value` will not exist there.

----

Changing the type of variable returned by `onChange` sounds like a breaking change to me. IMO `ColorPalette` should continue to be low level enough so that returning the color value is enough.

**Comment by AlchemyUnited** [comment]
@ranostaj - full disclosure - I did not read your request in detail (it's been a long day) but maybe this will utility will help?

Note: I'm creating my own array of colors (in PHP) and passing those to the blocks via the server-side localize script function. 

Note #2 - I'm actively  working  on upping my JS game, so please forgive anything n00b-ish. Of course if you have  any recommendation please  let me know. 

```
colorObject = function colorObject(colors, color, prop, undef = '') {

    var colorObj = getColorObjectByColorValue(colors, color)

    if (typeof colorObj === 'undefined') {
        // remove the # from the color so, worst case you'd still get a valid classname
        if (color) {
            return color.slice(1);
        }
        return undef;
    }

    switch (prop) {
        case 'color':
            if (colorObj.color) {
                return colorObj.color
            }
            return '';

        case 'name':
            if (colorObj.name) {
                return colorObj.name
            }
            return '';
        case 'slug':
            if (colorObj.slug) {
                return colorObj.slug
            }
            return ''

        default:
            return ''
    }
}
```

**Comment by AlchemyUnited** [comment]
@swissspidy said "What if someone chooses a custom color? color.value will not exist there."

Yes. But why can't the behavior be different if custom  colors are off? And in that case, why not be able to define what property is the saved for value? Wouldn't that not break anything in the wild, but also allow a better tool going forward? 

p.s. The fact that colors are being inlined so often should -imho - be a massive concern. Else there are going to be  a lot of surprised (read: pissed off) users in the future when they find out their content is locked into  a color pallet they are no longer interested in. Just me?

**Comment by ranostaj** [comment]
@swissspidy I just wanted to point out that it is kinda unexpected design. When I am passing an array of objects as colors prop I'd expect the provided onChange value is selected object, instead, I got a color string. 

So then I need to to some logic which I described in example. 

I see your point and understand that changing returned onChange value would be breaking change, so why do not return as a second argument selected object?  `onChange(color, object)`

**Comment by AlchemyUnited** [comment]
@ranostaj  - I hear ya. But there's a work around. By the time you get done fighting this fight _and_ it's gets coded, accepted, merged, etc. it could be what? A  couple months? If you're lucky. Are you willing to wait that long? (Probably not.) 

I agree with.  But the fact that it is how it is tells me I don't have enough hours in the day to try to rationalize with those who made such  decisions. No need to fight. Just pick up my toys and move on. But maybe that's just me.

**Comment by ranostaj** [comment]
@AlchemyUnited, Of course, I'm not going to wait until this will be included in the release - I have my own workaround. The intention here was to just point out some thoughts with some hope it might be discussed and hopefully implemented. 

Anyway, I keep my stuff going on so no worries about this delaying my work :)
Thank's for contribution.

**Comment by gziolo** [comment]
@jorgefilipecosta, you are the best person to answer this question about changing the public API of `ColorPalette` component.

**Comment by jorgefilipecosta** [comment]
Hi, all thank you for bringing this issue and discussing it.
There is HOC named `withColors` that is used by core blocks and can be used on custom blocks. The HOC handle the receiving and setting of color related properties.
That's the reason the onChange does not pass the color object -- the auxiliar HOC abstracts everything. (that and because of back-compatibility with code that was created in a time where color was just a string with the color code).

In the case provided given that we have a color attribute, that stores the color slug, if we wrap the edit component with `withColors( 'color' )( CustomBlockEditComponent );`, a color property will be passed with the color object containing the properties color, name slug, etc. So to get the color code one needs to do color.color, to get the name one can use `color.name`. To set the color, a property `setColor` is also passed to the edit component; this function receives the color code and can be directly passed to the ColorPalette component.

More information about the withColors HOC can be read on https://github.com/WordPress/gutenberg//blob/359858da0675943d8a759a0a7c03e7b3846536f5/packages/block-editor/src/components/colors/with-colors.js (the HOC contains code comments).

If your block needs to use a specific set of colors instead of using the theme provided ones, a call to createCustomColorsHOC is needed, the table block uses this mechanism https://github.com/WordPress/gutenberg//blob/0d60f1bb51391ac12243ff573253733c07479686/packages/block-library/src/table/edit.js.

I hope you find this information helpful. I'm going to close the issue for now, but if any additional information/discussion is required feel free to comment, and we can reopen it.
