### ISSUE TITLE
HTML Obfuscation is removed when a page is saved

### ISSUE THREAD

**Issue by frogdesk** [WordPress/gutenberg#15550]
**Describe the bug**
HTML blocks are modifying the code put into them unexpectedly.

**To reproduce**
1. Go to https://www.albionresearch.com/misc/obfuscator.php or another email obfuscator and pick up an obfuscated verison of an email address, or use this obfuscation of test@gmail.com:
`<a href='m&#97;ilt&#111;&#58;t%65&#115;t%&#52;0g&#109;ail&#46;c%6F&#37;6D'>te&#115;t&#64;gmail&#46;com</a>`
2. Create a new HTML block
3. Paste the obfuscated email code.
4. Save the page.
5. Refresh the page.
6. See that most or all of the obfuscated characters have been replaced by non-obfuscated characters.

**Comment by talldan** [comment]
Hi @frogdesk, this issue was discussed during today's triage meeting on slack (signup required):
https://wordpress.slack.com/archives/C02QB2JS7/p1560407162484500

It looks like this has always been the behaviour in WordPress, in testing, the classic editor also has the same behaviour.

Also worth mentioning that the Custom HTML block does do some validation and santization to ensure safe and correct values are output, so it might be this that's causing the deobfuscation.

Unfortunately, I don't think that's something that will be solved because it relates to safety and because the behaviour was always present, so I'll close this issue as wontfix. 

Please feel free to comment, and if it turns out there is something to fix the issue can always be reopened.
