### ISSUE TITLE
Update button doesn't work reliably

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#15577]
**Describe the bug**
The update button doesn't reliably become enabled after making edits.

After making some edits to a Classic Block, the Update button is still disabled and I'm not able to save, and clicking on the button does nothing. I then make a few more edits and the Update button still remains disabled, but I'm able to click on it and save my changes.

It's not reliably detecting block changes, and also not changing state even after detecting changes.

Video: https://cl.ly/fcfbd14e2196

**To reproduce**
1. Add Classic Block
2. Save & Publish page
3. Edit Classic Block and see if Update button becomes available.

**Expected behavior**
As soon as I make a change to a block, no matter how small, the update button should become enabled and I should be able to click it to save my changes.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3
 - Browser: Firefox Quantum 66.0.5
 - Version: WP 5.2

**Comment by nerrad** [comment]
Thanks for your report and the screen capture video (very helpful).  From the screenshot and my own testing it looks like new content in the classic block is not captured until clicking outside of the classic block.  

I've also waited for autosave to kick in while keeping focus on the classic block and it looks like it never kicks in.

A couple workarounds for now are:

-  make sure you switch focus outside of the classic block after editing content to ensure it is picked up by autosave (or to manually do update).
- (depending on use-case) convert the classic block to block content and changes in content will get picked up with regular blocks.

**Comment by rilwis** [comment]
@nerrad 

Is there any way to tells the editor that a block has changed programmatically? I have a similar problem, but with a custom dynamic block, that the publish button is not active when the block attributes change.

**Comment by youknowriad** [comment]
Also, it seems #13424 is related.

**Comment by gchtr** [comment]
I found a similar bug where I have a post with 3 empty paragraphs saved in the post content. When I remove all blocks, the update button is blocked. I can only save when there’s at least one block. The bug is not related to empty paragraphs. It happens with any type of block.

![gutenberg-update-button-bug](https://user-images.githubusercontent.com/2084481/63917797-b2040580-ca3b-11e9-86c1-a5063fc67b72.gif)

**Comment by talldan** [comment]
@gchtr I think there the editor won't save an empty post. When there are more than one empty blocks they get added as empty `<p>` tags so the editor will save.

**Comment by gchtr** [comment]
@talldan Yes, I can’t save an empty post. And that’s exactly what I think should be possible. I can’t delete all content in a post and save it. The empty blocks are just an example, I know they save as empty `<p>` tags. It could be any block instead of empty paragraphs, though. Is it intended that a post always needs to have content? Or should it follow the logic that when I change anything, I can save a post?

Currently, I have a use case where I have a post that has custom fields below the post content. Blocks are optional for additional content. But I’m having a really hard time saving the post when I don’t add any blocks. (And yes, I know that custom fields will eventually have to be converted to blocks).

**Comment by talldan** [comment]
@gchtr Yep, if I remember correctly there's specifically some code that prevents a save if the title, content and excerpt are empty. I'd recommend creating a separate issue if that's something that needs to be improved as it's highly unlikely someone will notice the comment here.

**Comment by gchtr** [comment]
@talldan Thanks, I found it in https://github.com/WordPress/gutenberg/pull/5018. I’ll open a separate issue.
