### ISSUE TITLE
Error message "This block has encountered an error and cannot be previewed" after adding page title

### ISSUE THREAD

**Issue by gbassoc** [WordPress/gutenberg#15586]
Since I upgraded to WordPress 5.2 the issues described below has started to happen
I created a new page, keyed the page title and press return, that resulted in the error message "This block has encountered an error and cannot be previewed" before I had even selected a block to use, i was not trying to preview anything at this point.
(see image gutenberg-editor-issue-1)
![gutenberg-editor-issue-1](https://user-images.githubusercontent.com/10323770/57575867-e92db700-744a-11e9-969d-63f260f28c84.png)
I am unable to delete the block with the message " This block has encountered an error and cannot be previewed"

also note the meassage saying "Move paragraph block ......." 

If I use an existing page with existing blocks created in an earlier version of WP those blocks are much wider, but when I add new blocks those blocks are about 1/4 the width of the older blocks
(see image gutenberg-editor-issue-2)

 ![gutenberg-editor-issue-2](https://user-images.githubusercontent.com/10323770/57575924-4413de00-744c-11e9-9c52-6ff29a6fcc72.png)

note the error message "This block has encountered an error and cannot be previewed" is not presented on an existing page with existing blocks".
You will also notice the style of the buttons in the block search popup window have also changed.

I have carried out the usual troubleshooting actions, i.e. disabling all the plugins and using the default theme but those actions did not resolve the issue with Gutenberg editor.

**Comment by gbassoc** [comment]
my browser is Chrome 74.0.3729.131 on Windows 10.
I had to restore the website to WP 51.1.

**Comment by nerrad** [comment]
> I created a new page, keyed the page title and press return, that resulted in the error message "This block has encountered an error and cannot be previewed" before I had even selected a block to use, i was not trying to preview anything at this point.
(see image gutenberg-editor-issue-1)

I'm a bit confused by your report because the `gutenberg-editor-issue-1` screenshot has more than just page title in it.  Also, just to be clear, wheh you say "I created a new page"  do you explicitly mean a new WordPress page (as in the page post-type) or do you mean a new WordPress post (as in the post post-type).

Following the below steps with WordPress 5.2 (no Gutenberg plugin active) I'm unable to reproduce the first issue:

### New page
1. Click "Add New Page"
2. Add a title and press return.

### New post

1. Click "Add New post"
2. Add a title and press return.

Following the below steps with an existing page or post in WordPress 5.2 (no Gutenberg plugin active), I'm unable to reproduce the second issue.

### Existing page/post

1. Edit an existing page/post with previous blocks


Since you've stated that you tried deactivating all plugins and switched to a default theme, the only other thing I could suggest you trying is to clear your browser cache in case there's some javascript and/or css cached somehow.

Also if you have any browser extensions enabled, you might want to try the site with all extensions off to see if there's an extension you are using that is interfering with site behaviour.

**Comment by gbassoc** [comment]
I am not using a Gutenberg plugin just the Gutenberg editor in core.
What to see in the image gutenberg-editor-issue-1 is a result of three steps carried out
1. I click New Page -  Ok so far
2. I add a title and press return, this is when I start to get the error massage described
3. I selected the HTML block and added some code to it 

I have reverted to 5.1.1 on this particular website. I will see if I can replicate this site to test and perform and upgrade to 5.2 to recreate the issues

**Comment by drjagan** [comment]
I had the same problem.
The 'PDF Embedder' plugin (by Dan Lester) caused the issue.
Deactivating the plugin resolved the problem. 
Hope this helps.

**Comment by Wnfdiary** [comment]
I have the same problem, when i try to add link. I tested on another theme with all plugins and it works normal. So the problem is with the theme - lets blog theme by themegoods . I got this error after I installed WordPress 5.2.2. The same error i got with spacer block. However if I change to the code editor and than back to visual editor, the block comes back. I have tried both Chrome and IE.

Thank you

**Comment by youknowriad** [comment]
A lot of work have been done to address similar issues. I'm going to close now but if you're able to reproduce this with the last release of the plugin or WordPress 5.3 beta, please do reopen the issue with exact steps to reproduce. Thanks.
