### ISSUE TITLE
"START_OF_SELECTED_AREA" character appears after undo

### ISSUE THREAD

**Issue by hypest** [WordPress/gutenberg#15619]
**Describe the bug**
Undoing a paragraph merge leaves behind a copy of the `START_OF_SELECTED_AREA` (0x0086) char.

**To reproduce**
1. Start off with this html:
```<!-- wp:paragraph -->
<p>Word</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Press</p>
<!-- /wp:paragraph -->
```
2. Merge the “Press” block to the one above it
3. Undo
4. Inspect the html via the browser dev tools and verify that the special char is there before the `Press` word in the second block

**Expected behavior**
No copies of the special char should be left in the text/markup.

**Screenshots**
![Screenshot 2019-05-14 at 11 09 31](https://user-images.githubusercontent.com/1032913/57681765-058f4680-7639-11e9-89f2-b6555883deae.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4
 - Browser Firefox 66.0.5
 - Version on hash eea04cf20

**Comment by aduth** [comment]
It was mentioned that this may have been fixed by #15599 . Needs additional testing or confirmation from @ellatrix .

An underlying cause is the mutation of the original block object in the logic of `block-editor`'s `effects.js`, which has the negative impact of unintentionally mangling Undo history.

There is some direct mutation which still occurs in this file, which is concerning to me:

https://github.com/WordPress/gutenberg/blob/34d24ed9d98f738c682c20b500634d85319cd33c/packages/block-editor/src/store/effects.js#L102

https://github.com/WordPress/gutenberg/blob/34d24ed9d98f738c682c20b500634d85319cd33c/packages/block-editor/src/store/effects.js#L137

**Comment by ellatrix** [comment]
@aduth Yes, it was a bit more challenging to not mutate. I just wanted to add a line in the other PR so it's fixed.

**Comment by ellatrix** [comment]
This is fixed.
