### ISSUE TITLE
the ESLint @wordpress/react-no-unsafe-timeout shouldn't guard against using setTimeout in react hooks

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#15622]
Related https://github.com/WordPress/gutenberg/pull/15594/files#r283707207

This ESlint rule's behavior is specific to the React component class. Now that we support react hooks its behavior should be expanded to allow setTimeouts inside hooks.

cc @aduth

**Comment by aduth** [comment]
In the referenced example:

```js
useEffect( () => {
	const timeoutHandle = setTimeout( () => {
		onRemove();
	}, NOTICE_TIMEOUT );

	return () => clearTimeout( timeoutHandle );
}, [] );
```

This shouldn't be flagged by the rule anyways, since it's meant to exempt anything which is assigned to a variable, on the assumption that assigning `setTimeout` to a variable is an indicator that a matching `clearTimeout` exists, which it clearly does in the example above.

https://github.com/WordPress/gutenberg/blob/13a6b263d6dcc765152bf894533f9a0debcd0ca9/packages/eslint-plugin/rules/react-no-unsafe-timeout.js#L71-L78

There may well be a bug here if this is not working correctly, but it doesn't seem like it would be something specific to the usage of hooks.
