### ISSUE TITLE
Improvement to the Image Edit Block Placeholder

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#15637]
Currently the when the user goes to swap out the image in an image block with another image, the Image Edit placeholder comes up. 

![edit-image](https://user-images.githubusercontent.com/617986/57727869-66be1680-7647-11e9-80d9-85e4dde32582.png)

This works great, but I think the design can be refined a bit more.

1. "Edit Image" doesn't quite make sense here. The user can't really edit that image (ie. crop, resize, etc.). Maybe we say "Replace Image"?
2. The thumbnail might benefit from some improvements as well. Whether it floats left, or becomes smaller, etc.
3. Should the three buttons be stacked, or aligned in the same row?
4. Is the "Cancel" link the best solution here? Maybe take a look at a "X" in the corner? Or creating a way to just keep the image by clicking it, or something.

Just some thoughts for minor improvements.

**Comment by talldan** [comment]
I've worked on this a bit in the past (though it has been iterated on since). It definitely presented some challenges!

> Should the three buttons be stacked, or aligned in the same row?

When thinking about this it's definitely worth considering how it looks when the 'Insert from URL' button has been clicked:
![Screen Shot 2019-05-16 at 11 02 25 am](https://user-images.githubusercontent.com/677833/57823537-7e71d800-77ca-11e9-951e-17644d6b448a.png)

I originally put the button on its own to make sure it feels balanced with the popover in the middle when it's opened (and to make sure it doesn't overlap anything else). I definitely understand it looks unusual with the button on its own, but thought I'd share why the original decision was made.

Having said that, I'm still not completely convinced the popover for entering the URL is the right pattern, either. 

Look forward to seeing options for tidying it up 😄

**Comment by enriquesanchez** [comment]
I was comparing this to how we handle basically the same operation on the media & text block and found some differences:

<img width="875" alt="Screen Shot 2019-07-25 at 4 29 37 PM" src="https://user-images.githubusercontent.com/3276087/61910194-8b612500-aef9-11e9-9a43-6ea930289f00.png">

- On the media & text block, we use a pencil icon to represent the same action (Edit media vs. Edit image).
- On the media & text block, clicking the "edit media" icon takes you straight to the "Select or Upload Media" modal.
- We also don't present the option to "Insert from URL" in this case. Any reason why we do that?

I wonder if we can bring some consistency to these two blocks. Is there any reason why "media" is treated as a different typo of upload?

cc. @mapk @talldan

**Comment by enriquesanchez** [comment]
I just came across https://github.com/WordPress/gutenberg/issues/14795 and https://github.com/WordPress/gutenberg/pull/15517 and looks like this flow is being implemented on other blocks, including media & text.

**Comment by mapk** [comment]
It appears there is other work happening here https://github.com/WordPress/gutenberg/issues/11952 in regards to replacing an image which will most likely be carried over to the blocks that use images, so let's close this one out.
