### ISSUE TITLE
Add the possibility to completly remove Gutenberg from Wordpress and replace it with the normal editor

### ISSUE THREAD

**Issue by blackdevil72** [WordPress/gutenberg#15678]
Hello,

It would be great for us user if Gutenberg Editor could be completely removed from the system and not bloat our installation for no reasons. None of the websites I manage and people who use then have a use for it and its more an annoyance than anything else. It take space and is never used and never will be.

The best thing would be to add the possibility to choose on the installation process wich editor you want to install (or both). Then in the admin panel let to possibility to remove one or the other, if both are installed let the possibility to user to choose wich one they want to use.

Thank you for your consideration.

**Comment by GlennMartin1** [comment]
There was strong negative feedback on the early beta versions, and arguably the 5.0 release was premature.

But WordPress 5.2 (and especially recent versions of Gutenberg plugin) have brought a much higher level of maturity to the editor, and the public reception is now largely positive.

The block editor is here to stay. Almost 50% of WordPress users are running 5.0 and higher.

Migration is easy, especially since non-block pages/posts remain unchanged in a Classic block. No need to update any of your pages - it's an almost seamless transition. 

And if you don't like it, install the Classic Editor plugin. But better, allow yourself to rediscover Gutenberg on the newest plugin version. Chances are you'll love it.

**Comment by swissspidy** [comment]
One of the core [philosophies](https://wordpress.org/about/philosophy/) of WordPress is **decisions, not options**. There's no point in giving users such an option upon installation. That just creates unnecessary bloat and maintenance burden for all the contributors. The new editor is here to stay, and the UX improvements it brought to WordPress have been very well received overall.

As mentioned, you can use the Classic Editor plugin if you cannot or don't want to use the new block editor.
