### ISSUE TITLE
Add support for native lazy loading images

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#15753]
In chrome 75, the blink team has added support for native lazy loading images. More information can be found [here](https://addyosmani.com/blog/lazy-loading/). 

Adding native lazy loading images is as simple as adding an attribute of `loading`.  

Core blocks such as image and gallery should support this lazy loading. 

There is already a [trac ticket](https://core.trac.wordpress.org/ticket/44427) for this to tackle this on the PHP side.

**Comment by pcfreak30** [comment]
While I like this idea, I think it should be pointed out that we should not re-invent the wheel with a lazyload library. One that I have seen google link to (forgot where) and as a link on pagespeed I think, is https://github.com/aFarkas/lazysizes.

They also have an IntersectionObserver version at https://github.com/aFarkas/lazysizes/blob/gh-pages/src/lazysizes-intersection.js which uses no scroll timers. The code uses no jquery and also makes changes with requestAnimationFrame with a simplistic queue system for performance vs setTimeout. Among it is a folder with like 20 plugins, thus can be used for custom ones.

Thanks.

*cross-post from https://core.trac.wordpress.org/ticket/44427 due to the relevancy*

**Comment by vanaf1979** [comment]
i worked on this one, but the galary-block gives me a error when i build. See  https://github.com/WordPress/gutenberg/issues/16078

**Comment by wolffe** [comment]
We shouldn't reinvent the wheel, we just need to add (or allow adding) a `loading="lazy"` parameter.

**Comment by noisysocks** [comment]
https://core.trac.wordpress.org/changeset/47554 implements the `loading` attribute for all images in `the_content` which includes block editor images. This will ship as part of WP 5.5.

**Comment by shadtek** [comment]
It looks like `loading="lazy"` is not being added to images.

**Comment by renatonascalves** [comment]
@shadtek Are you uploading images or inserting images from a link?

**Comment by shadtek** [comment]
> @shadtek Are you uploading images or inserting images from a link?

Uploading and choosing from media library. Wordpress version 5.6
