### ISSUE TITLE
Gutenberg reports an HTML block as wrong (again)

### ISSUE THREAD

**Issue by locksoft** [WordPress/gutenberg#15794]
This is a issue I had in the earlier versions of Gutenberg. Then, luckly, it was solved.
Today it appeared again.

I've this structure:

```
<!-- wp:html -->
<!-- comment -->
<div class="tab_row">
<div class="tab_date">text</div>
<div class="tab_dot top"></div>
<div class="tab_content">
<div class="tab_title">text</div>
<!-- /wp:html -->

<!-- wp:paragraph -->
<p>Text</p>
<!-- /wp:paragraph -->

<!-- wp:html -->
</div>
</div>
<!-- /wp:html -->
```

And so on. It's a table-like structure. The first and last blocks are custom html. Everything works correctly but, if I save the article, when I open it again those blocks are reported as wrong. I can correct them (having Gutenberg closing open "div") or convert in custom html (leaving them as they are).

I don't know if something was changed in the last update but I'd like if Gutenberg would accept my html code without trying to "repair" or think it's wrong. :)

Is this a known issue?

Thanks

**Comment by locksoft** [comment]
Update: after installing the 5.8.0 version, bug is still there.

https://i.postimg.cc/26xHWp96/Schermata-2019-05-30-alle-16-11-26.png

**Comment by talldan** [comment]
Hi @locksoft. I understand this issue is old, so it might not be relevant to you, but thought I'd reply. Also, apologies a reply took so long.

The issue you're having here is that the HTML in your first block has unclosed tags and the last block has closing tags without opening tags. Each block is assessed individually for the validity of its HTML, so those blocks would be considered invalid.

I think the core thing here is that each block is intended to be a correct standalone unit. If you were to move or duplicate the first or last block with this markup it'd result in invalid HTML within the post, which is something that the editor tries to guard against.

There also isn't currently a way of nesting other blocks within custom HTML, that would have to be built as a custom block. There's an example here for building that kind of block:
https://developer.wordpress.org/block-editor/tutorials/block-tutorial/nested-blocks-inner-blocks/

Alternatively the whole content you're trying to define would be within a single HTML block:
```html
<!-- wp:html -->
<!-- comment -->
<div class="tab_row">
<div class="tab_date">text</div>
<div class="tab_dot top"></div>
<div class="tab_content">
<div class="tab_title">text</div>
<p>Text</p>
</div>
</div>
<!-- /wp:html -->
```

**Comment by jordesign** [comment]
As there's been no further movement here - and a workaround is proposed, I'm going to close the issue.
