### ISSUE TITLE
Blocks are disappearing when clicking on right side column/ left side column

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#15817]
This was previously reported in trac:

https://core.trac.wordpress.org/ticket/47213

"Steps to follow :
-> Open Editor.
->Add column block/ Image with content block.
-> Clicking on the right side column.
->After that clicking on the "add block" option.
-> Blocks not fount displayed in the popup.
Please find below attched video :
https://www.screencast.com/t/0ObyatkwF"

**Comment by karmatosed** [comment]
This was originally reported in trac and looping in the poster of that issue here, @nayana96249.

**Comment by nerrad** [comment]
There's been some work on the columns block since this was reported so the latest master is a bit different.  However it's clear there still remains an issue as demonstrated by this screencast:

![example](https://cl.ly/3d9baa778bd2/Screen%20Recording%202019-05-26%20at%2010.25%20AM.gif)

Two things to note in this screencast:

1. Inserting a column block only has blocks available via the inner block selector in the columns (not via the main block selector in the top menu) - which appears to be similar to the original report.
2. It's not clear how to delete the columns.  The only way I was able to delete was to click the next block area after the column and then hit backspace twice.

**Comment by nayana96249** [comment]
Hello @nerrad ,

As of now, I can see If I am clicking on second column then I can add other blocks using "+" icon in the column section.

Thanks

**Comment by nerrad** [comment]
Thanks for reporting back @nayana96249 !  I'm going to go ahead and close this issue then.
