### ISSUE TITLE
KSES: Update CSS properties considered safe for all users.

### ISSUE THREAD

**Issue by marybaum** [WordPress/gutenberg#15819]
## Description
Apart from some minor updates to account for the block editor, the KSES list of allowed CSS properties for authors and contributors has not been updated for quite some time.
Most significantly, not all safe Grid and Flexbox attributes are supported. Several other new features of CSS are missing too.
## Reference 
https://developer.mozilla.org/en-US/docs/Web/CSS/Reference
## Tasks
Add explicit support for new properties that shorthand attributes already support implicitly
Define what safe means in this context: Browser support? A11y considerations?

**Comment by nerrad** [comment]
I think this is something that should be requested via a [core trac ticket](https://core.trac.wordpress.org/).  As far as I can tell, kses allowed tags are not filtered in Gutenberg anymore.  The additional support would be added via the `safecss_filter_attr` function.

In the meantime, for plugin/theme projects, additional filter support can be added via the `safe_style_css` filter.

If proven otherwise, please do re-open this issue!
