### ISSUE TITLE
On clicking on Full screen toggle button table width is exceeding the editor width.

### ISSUE THREAD

**Issue by nayana96249** [WordPress/gutenberg#15849]
Steps to follow :

Block Issue: Table block 

1. Open editor.
2. Add Table block.
3. On clicking on Full-screen toggle button table width is exceeding the editor width.
4. It should not exceed the editor.

https://www.screencast.com/t/SJiRBgjR

**Comment by nerrad** [comment]
As far as I can tell, this is intentional.  That is what the purpose of "full-width" is.  I'll leave this for others to weigh in though.

**Comment by melchoyce** [comment]
It is intentional, in that it matches how the other full-width blocks work, but I think it could benefit from a little bit of padding in the editor, maybe just when the block is selected?

![image](https://user-images.githubusercontent.com/2846578/58650876-d2f27880-82dd-11e9-88e6-af3b72d6cc96.png)

Makes me wonder if maybe full-width media blocks and full-width text blocks should have slightly different rules.

**Comment by kjellr** [comment]
In general, I do agree that text-based blocks with no background should likely have a tiny bit of additional padding there. The columns block also pushes interior text-based blocks right up to the edge at the moment, but I'm fairly sure that's a mistake, as it also creates a horizontal scroll too (See https://github.com/WordPress/gutenberg/issues/15192). It didn't always behave that way. 

In the case of the table block, I wouldn't mind adding a tiny bit of margin around it — aesthetically it'd make the block seem much more intentional.

**Comment by talldan** [comment]
It looks like the behavior is still the same today, with the table sitting flush with the edges of the editor. Re-labelling as an enhancement given there's a good amount of design feedback around adding margin when the block is full-width.

**Comment by talldan** [comment]
Re-testing this, and it seems to be resolved now.
