### ISSUE TITLE
is-shallow-equal: invalid for objects with undefined values

### ISSUE THREAD

**Issue by matthewvalentine** [WordPress/gutenberg#15905]
**Describe the bug**
isShallowEqualObjects produces invalid results when the keys of the two objects are different, but any keys missing in the second have the value `undefined` in the first.

There is no specific user-visible issue related to this that I'm aware of, I just happened to look at the code. Although it's possible some subtle issue might exist now or in the future.

**To reproduce**
Run `isShallowEqualObjects({a: undefined}, {b: 5})`, and you'll get `true`.

**Expected behavior**
Should return `false`.

**Comment by pento** [comment]
Nice find, thanks @matthewvalentine!

This issue is caused by this loop:

https://github.com/WordPress/gutenberg/blob/0719922928f9c7e8764e80d1ecf648b1ed43d711/packages/is-shallow-equal/objects.js#L29-L36

In your example it compares `a[a]` (which has been set as `undefined`) with `b[a]` (which hasn't been defined), incorrectly concluding that these two `undefined` results mean the same thing. 🙂

I think there are two potential solutions for this:

- Before the loop, compare `aKeys` and `bKeys`, to see if they're the same.
- Inside the loop, check if `key` is in `bKeys`.

I suspect there will be other issues if `b` contains any items set to `undefined`, which makes me lean towards the first option, though performance will be a potential problem to be aware of.

**Comment by aduth** [comment]
Noting that this code is extremely performance-sensitive (it [determines rerendering](https://github.com/WordPress/gutenberg/blob/0719922928f9c7e8764e80d1ecf648b1ed43d711/packages/data/src/components/use-select/index.js#L132) of almost every every element in the application), so array searches or other iterations should be avoided / consolidated as much is possible.

One thought, based on the equality by virtue of the implicit `undefined` of the other object, is to include an `Object#hasOwnProperty` check on the other object when comparing, to assure that it's actually present (since its presence would contribute to `keys` and thereby allowing the keys length comparison earlier in the function to bypass if it was explicitly defined).
