### ISSUE TITLE
Component `help` fields don't allow HTML.

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#15904]
**Is your feature request related to a problem? Please describe.**

Components like `TextControl`, `RangeControl`, etc have a `help` field that shows instructions to the user. It's often necessary to use HTML within that kind of field, in order to use links, paragraphs, etc.

For example, a `TextControl` that asks users to enter an API key. The user may need to sign up for a 3rd party account with the API service, go through multiple screens to configure and retrieve the credentials, etc. All of that requires more explanation than can fit into a single sentence. It's best to link directly to the service's comprehensive documentation instead.

**Describe the solution you'd like**

Allow the value of the field to contain HTML.

**Comment by draganescu** [comment]
I wonder if there is any reason to "restrict" what the help text shows?

**Comment by talldan** [comment]
I think this is possible and has been for a while:
```jsx
help={ <>Some text <a href="example">Link</a></> }
```

The anchor link field is a good example (implemented here - https://github.com/WordPress/gutenberg/pull/16142), that has a link as part of the help text:
<img width="262" alt="Screenshot 2021-07-21 at 12 18 14 pm" src="https://user-images.githubusercontent.com/677833/126430330-80d579d2-a398-4e02-b473-e1a878eb4f0f.png">

HTML in a string wouldn't be accepted because that would potentially be a security vulnerability if the source of the text was outside of the control of the frontend code.
