### ISSUE TITLE
ROW element

### ISSUE THREAD

**Issue by leodluz** [WordPress/gutenberg#15926]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/22651765/58657175-16f07800-82f4-11e9-9c32-4f7387f0a18d.png)
**Describe the solution you'd like**
A row element, which is so common in bootstrap, would solve my problem. 

**Describe alternatives you've considered**
Or maybe remove the lock for 1 column in the 'columns' element.
![image](https://user-images.githubusercontent.com/22651765/58657330-6c2c8980-82f4-11e9-8906-296ce2f756ca.png)

**A clear and concise description of what you want to happen.**
Avoid problems with clear: left and content alignment.

**Comment by roguewdesign** [comment]
Hi leodluz,

Have you considered using the Group block?

You could place your Columns within a Group which would wrap them in a div element. In addition, you could create a custom ROW CSS class for the Group.

`.my-custom-row {
         overflow: hidden;
         clear: both;
}`

Something like that.

**Comment by leodluz** [comment]
There are no group block!

![image](https://user-images.githubusercontent.com/22651765/58672552-dc033a00-831d-11e9-8aa2-77047701244e.png)

**Comment by roguewdesign** [comment]
It may not be released yet, but if you install the Gutenberg Editor plugin, you should see it:

https://en-ca.wordpress.org/plugins/gutenberg/

**Comment by talldan** [comment]
Adding a link to the forum thread here:
https://wordpress.org/support/topic/container-block/

It's mentioned there that since https://github.com/WordPress/gutenberg/pull/15210 was merged, the group block now renders with an inner div and it's not possible to add the `row` classname to the inner `div`.

It might be nice to allow users to specify a classname on the inner div through the block inspector (block sidebar). Although this is also using the group block for something it wasn't intended to be used for. There are Bootstrap block plugins available, which might be a better option.
