### ISSUE TITLE
Inserter: Cannot read property 'focus' of null/undefined

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#1606]
On lates master, I get 2 JS errors in the console while tabbing through the inserter items. To reproduce, for example:
- open the inserter
- click on the last tab (Embed)
- click on the Search field
- press Tab on your keyboard

On the first Tab presses I get::
`Uncaught TypeError: Cannot read property 'focus' of null`
after a few Tab presses I get:
`Uncaught TypeError: Cannot read property 'focus' of undefined`

Same happens also on the first/second Tabs in a slightly different way. Same when using arrow navigation (press right/arrow keys instead of Tab).

Also, the new "tabs" added at the bottom can't be navigated using the keyboard.

Maybe related: #1582

**Comment by afercia** [comment]
![screen shot 2017-06-30 at 15 37 35](https://user-images.githubusercontent.com/1682452/27738318-517a9dd6-5dab-11e7-9a41-554f60cb9cfb.png)

**Comment by swissspidy** [comment]
Just ran into this as well:

```
TypeError: undefined is not an object (evaluating 'this.nodes[refName].focus')
```

The logic flaw is inside [`InserterMenu.focusNext`](https://github.com/WordPress/gutenberg/blob/b34ea0210ab37bb7b51058e7f608708632643aee/editor/inserter/menu.js#L138-L151).

When you're on the "Recent" tab, the `findNext()` call will not only search inside "Recent", but all the blocks visible in "All".

So when I see this (with focus on "Cover Image"):

<img width="295" alt="screen shot 2017-07-02 at 19 39 12" src="https://user-images.githubusercontent.com/841956/27772230-3bc0a80a-5f5e-11e7-87ba-155df9c3b992.png">

And when I hit tab, it looks for "Pullquote", which theoretically is next in line:

<img width="245" alt="screen shot 2017-07-02 at 19 39 26" src="https://user-images.githubusercontent.com/841956/27772240-58c3b19a-5f5e-11e7-9411-3d6c68fb27bd.png">

Of course, that doesn't work.

The same happens when you're already focused on the last element in the list in the "All" tab. It then looks for embed blocks in the list.

**Proposed solution:**

When the last element is reached, focus should go to the tabs.

Even better: Use arrow keys instead of tabs to navigate the blocks. This way you can jump from search to tabs by simply pressing tab twice.

Perhaps this would get solved by #1596. See also: #1588.

**Comment by afercia** [comment]
> Even better: Use arrow keys instead of tabs to navigate the blocks. This way you can jump from search to tabs by simply pressing tab twice.

ideally, this should happen inside the category groups with `role="menu"`. This way, the Tab key would navigate from the search to each menu and then to the tabs.
Navigation within each menu should be arrows-only (as the ARIA spec recommends).
Side note: this is also how keyboard interaction works in the macOS emoji inserter:

<img width="306" alt="macos emoji inserter keyboard" src="https://user-images.githubusercontent.com/1682452/27772543-f80599c0-5f64-11e7-8aa4-28c36040d96d.png">

**Comment by youknowriad** [comment]
No errors for me. It's probably fixed elsewhere.

**Comment by afercia** [comment]
Yeah, cannot reproduce.
