### ISSUE TITLE
Classic Block has broken block switcher

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#16137]
**Describe the bug**
The Classic Block seems to have picked up a block switcher, perhaps after the group block was merged?

**To reproduce**
1. Fire up the latest version of master (5.9.0-rc.1)
2. Add a Classic Block to your editor
3. See the block switcher in the top right corner when the block is selected

**Expected behavior**
There is no block switcher, it should look like this:

![image](https://user-images.githubusercontent.com/2846578/59392630-2a0c3a80-8d2d-11e9-8e72-d161253ecbea.png)

**Screenshots**

![classic-block](https://user-images.githubusercontent.com/2846578/59392505-c08c2c00-8d2c-11e9-8ceb-11168c790f5d.gif)

**Comment by youknowriad** [comment]
This is a very annoying bug could we try to fix it? Maybe we could just disable the block switcher (group transform) from the classic block. cc @getdave

**Comment by donmhico** [comment]
Hello @youknowriad @melchoyce 

I would like to try and give this a fix, however I have a question as I want to understand more. Is there any reason why we want to disable block switcher (group transform) icon in Classic Block Editor? Is this because other than "Group" there's no other transform option?

**Comment by talldan** [comment]
I've updated the styling in https://github.com/WordPress/gutenberg/pull/17323, but I didn't really consider that it should have no transform 🤔
