### ISSUE TITLE
Make 'H' bigger

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#16139]
The 'H' on heading block in block library has padding issues compared to others.

![image](https://user-images.githubusercontent.com/253067/59394007-e87e8e00-8d32-11e9-934e-0ae050a86a87.png)

**Comment by Soean** [comment]
Dashicons (Like the heading "H") are 20x20 px, all others are 24x24 px, not sure why this was added: https://github.com/WordPress/gutenberg/blob/3c0b12be9090975421cdaa68dc03e15c4913721f/packages/components/src/icon/index.js

**Comment by karmatosed** [comment]
I think this doesn't need design as it can be changed to fix this. Please add back in the label if that is the case.

**Comment by sarahmonster** [comment]
For reference, this is part of the issue:

<img width="285" alt="Screenshot 2019-07-04 at 13 48 59" src="https://user-images.githubusercontent.com/376315/60802745-88cca480-a171-11e9-9495-18aff8c566aa.png">
<img width="166" alt="Screenshot 2019-07-04 at 13 49 31" src="https://user-images.githubusercontent.com/376315/60802746-89653b00-a171-11e9-9d91-8cc5faa6e17c.png">

Here's what it looks like "sized up" to 24px:
<img width="737" alt="Screenshot 2019-07-08 at 11 20 22" src="https://user-images.githubusercontent.com/376315/60803169-8585e880-a172-11e9-964a-748573f2990d.png">

Definitely better, but still feels a wee bit out of place due to the heavy lines. To fit better with the other icons used, it feels as though it should be outlined.

Here are a few potential approaches to solving the problem:

1. Change the H icon in Dashicons itself to use less padding inside the box. This may cause inconsistency with the Dashicon set, and requires hunting down the icon in Trac. (The icon doesn't appear in the Dashicons Github repo or in the Dashicons website, oddly enough.)
2. Use a custom icon, designed to the Material grid, for the Heading block. This creates a wee bit more overhead, but does allow us to tweak the icon a bit further so it better aligns with the styling we're using for other block library icons. (For instance, we could adjust the width of the lines or use an outline style.)
3. Use 24x24 for Dashicons. This is the easiest approach here in many ways, but it leads to unintended side effects for those Dashicons that don't have as much padding inside the box:

<img width="741" alt="Screenshot 2019-07-08 at 11 21 15" src="https://user-images.githubusercontent.com/376315/60803239-abab8880-a172-11e9-8fdc-6d633270ae8c.png">

In the above screenshot, RSS, Search, and Tag all use Dashicons, all of which have significantly less padding inside the box, in spite of being heavier:

<img width="258" alt="Screenshot 2019-07-08 at 11 25 14" src="https://user-images.githubusercontent.com/376315/60803464-2a082a80-a173-11e9-980a-769ef25363d3.png">


Of these options, I suspect 2 (using a custom icon) is probably our best bet in terms of maintaining consistency across icons here, but I'd appreciate additional feedback if there's a better approach!

**Comment by mtias** [comment]
Closing per work on #20284
