### ISSUE TITLE
Instagram Block: Ability to embed a profile

### ISSUE THREAD

**Issue by mdrockwell** [WordPress/gutenberg#16183]
**Problem**
The Instagram block does not make it clear that it only accepts links to individual Instagram photos or videos, but would be fantastic if it also accepted Instagram profile links.

**Solution**
Allow inserting a URL for an Instagram profile in the embed block, that would display the Instagram profile photo and bio when published.

**Alternatives**
When published, the Instagram block with a profile URL could also potentially display the most recent photos from that profile.

**Comment by senadir** [comment]
Embedding instagram account is not straightforward as embedding images & videos.
embedding a single media is as easy as putting the url in a simple code, but embedding profiles require creating an Instagram Client application, client secret & token, building an API call to the instagram to fetch the information of **your account**, so you can't embed other people content.

so this feels out of the scope of the native embed model since it builds on OEmbed and therefor should be done in a separate plugin.

**Comment by youknowriad** [comment]
I think @senadir's reply is solid. In order to do this, instagram needs to provide us with an OEmbed provider for profiles.
