### ISSUE TITLE
dateI18n returns not affected by `gmt` parameter

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#16218]
**Describe the bug**

The return value of `dateI18n()` is identical when the `gmt` parameter is set to true and when it's set to false, even though the site's timezone is _not_ GMT.

**To reproduce**

1. Set WP timezone to something different than your browser's timezone. In this example, my browser timezone is `America/Vancouver`, and WP is set to `America/New_York`.
1. Execute this:

```js
console.log(
	wp.date.__experimentalGetSettings().timezone.offset, "\n",
	new Date().getTimezoneOffset() / -60,                "\n",
	dateI18n( 'Y-m-d h:ia', 1560855600 * 1000, true ),   "\n",
	dateI18n( 'Y-m-d h:ia', 1560855600 * 1000, false )
);
```

Expected:

```
-4 
 -7 
 2019-06-18 11:00am 
 2019-06-18 07:00am
```

Actual:

```
-4 
 -7 
 2019-06-18 04:00am 
 2019-06-18 04:00am
```

There are three things wrong here; they could be interrelated, or distinct bugs.

1. The results of `dateI18n()` should be different when `gmt` is `true` than when it's `false`, but they're identical.
1. The value when `gmt` is `true` should be `11:00am` (GMT), not `04:00am` (Vancouver).
2. The value when `gmt` is `false` should be `07:00am` (New York), not `04:00am` (Vancouver). 

Possibly related: https://github.com/WordPress/gutenberg/issues/15221

**Environment:**
 - WP 5.2.3-alpha-45550
 - Firefox 68.0b10 (64-bit)

**Comment by davilera** [comment]
Also, I don't know what's the difference between `date` and `dateI18n`... can anyone please explain?

**Comment by Rarst** [comment]
Oh, it's even more messy than that. `$gmt` argument _does_ apply, but only _if_ timestamp is not provided. So it works for retrieving _current_ time from it, but not _given_ time. It's pretty insane, but we are keeping it because of backwards compatibility.

`wp_date()` is 5.3+ replacement that is sane, `date_i18n()` is now wrapper around it (preserving its twisted behaviors for BC).

> what's the difference between date and dateI18n

`date()` is a PHP function that does date formatting and works with Unix timestamps.

`date_i18n()` is a WordPress function that does date formatting, date localization, and works with WP timestamps (summed with time zone offset and incompatible with Unix timestamps).

**Comment by vcanales** [comment]
Fixed in https://github.com/WordPress/gutenberg/pull/18982
