### ISSUE TITLE
Repeater component

### ISSUE THREAD

**Issue by BenjaminZekavica** [WordPress/gutenberg#16269]
Hallo :) I have one wish feature. Innerblock are fine but I love it, if its possible to create repeater fields same ACF. 

**Look here:**[ https://www.advancedcustomfields.com/resources/repeater/ ]( https://www.advancedcustomfields.com/resources/repeater/ )

I create one component same there, but its difficult to change order and so on.. 
[Gutenberg Idea](https://github.com/BenjaminZekavica/WordPress-Gutenberg-Repeater)

I think for developers that component will be great.

**Comment by draganescu** [comment]
Howdy @BenjaminZekavica ! This looks like a good idea, however I wonder what is the usecases you had in mind? I also used a repeater field, but as a _user_ not as a developer :)

For example there is a post block in development and a query block as well. Combined a LatestPosts block will probably be implemented using both.

Since a block author has acces to implementing code directly, and a user cannot connect a block to data directly (visually) what is the place where a repeater would work in Gutenberg?
