### ISSUE TITLE
Manual to use import React Components (plugins)

### ISSUE THREAD

**Issue by BenjaminZekavica** [WordPress/gutenberg#16270]
React is really great and has a big community with much packages, but I would like to integrate come packages, but in Gutenberg nothing works... 

I hope soon as possible it will be documented.

**Comment by swissspidy** [comment]
It would really help if you could explain what exactly you are trying to do and where you currently face some issues. Please share some code that you're struggling with.

You can totally use all the features of React and other React components in your plugin code. There aren't really many Gutenberg-specific things that you might need to consider. Gutenberg also offers lots of helpful packages like `@wordpress/scripts` to make developing for the block editor easier.

**Comment by BenjaminZekavica** [comment]
Thank you :) But I think if you wont to load scripts (same jQuery Plugins) can I set it into register scripts function or ? 

What you can recommend? 
I will use that [Github Repo](https://github.com/SortableJS/react-sortablejs )

Must I use that ?? Its important to use import React from react or? 

```
import React from 'react';
import Sortable from 'react-sortablejs';
```

**Comment by youknowriad** [comment]
You can use any React library just avoid `import React from 'react';`  and use `wp.element` instead of `react`. We have tools like the scripts package and there are several scaffolding tools to make this easy for you.

Also please note that for general help requests, we use the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/.

Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. 

You may also ask for technical support at https://wordpress.stackexchange.com/.

Thank you!
