### ISSUE TITLE
publish base scss used by `components` as an npm package

### ISSUE THREAD

**Issue by haszari** [WordPress/gutenberg#16274]
**Is your feature request related to a problem? Please describe.**
I'd like to use `@wordpress/components` to implement a user interface, and I'd like to customise colours. For example, I'd like a standard button, but pink instead of blue :)

To achieve this, I can depend on `@wordpress/components`, reference the source stylesheet (`@wordpress-components/button/style.scss`), and use PostCSS to specify default colors.

This stylesheet depends on various "globals" set up in `assets/stylesheets`.

**Describe the solution you'd like**
Publish a package containing the base / global scss variables/mixins etc defined `assets/stylesheets`. 

**Describe alternatives you've considered**
There are definitely alternatives here. I've considered pasting these files into my own repo and updating manually, or refactoring the component styles so they don't depend on anything. Another approach would be to include the global styles within the `components` package.

The crux of this is how to expose a themeable control from `wp-components`. I'm assuming that it's ok for me to use `@wordpress-components/button/style.scss` directly – there are probably alternative ways to allow components to be themed or colorschemed :)

**Comment by noisysocks** [comment]
This issue came up in [a #core-editor triage meeting](https://wordpress.slack.com/archives/C02QB2JS7/p1562825646367000).

https://github.com/WordPress/gutenberg/issues/16347 is a good proposed solution to this problem. If implemented, this would let third parties import the built CSS from `@wordpress/components` and customise colours etc. using CSS variables. 

Let's move discussion over into https://github.com/WordPress/gutenberg/issues/16347. I'll close this one out for now.

**Comment by psealock** [comment]
@haszari, I just came across this and we have a temporary solution you might be interested in. It involves manually copying over a few Gutenberg SCSS variables and running the postcss process to theme components like buttons. I'll go into more detail if you'd like.
