### ISSUE TITLE
Set Column width based on the layout selected.

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#16302]
**Describe the bug**
Column width is still empty and displaying bordered warning.

**To reproduce**
1. Insert Column block and select a column

**Expected behavior**
Width should be set based on the selected column layout.

**Screenshots**
<img width="274" alt="Screen Shot 2019-06-26 at 9 30 55 PM" src="https://user-images.githubusercontent.com/3365507/60184032-ebf93580-9859-11e9-9622-0bef81c76017.png">

**Comment by aduth** [comment]
It is intended that there not be an explicit assigned value for the width, when choosing a template for one of the equal column widths, since the default behavior of the columns block is to distribute widths evenly. This was a later change in #16129 (https://github.com/WordPress/gutenberg/pull/16129#discussion_r294243851).

I'm not able to reproduce the issue with the warning border. Were there other steps before this was shown? An incompatibility with a theme or plugin?

**Comment by phpbits** [comment]
> An incompatibility with a theme or plugin?

Oh yeah! Just checked and the CSS is coming from Block Lab. My bad. Thanks!
