### ISSUE TITLE
Publish flow: change wording of publish button contextually

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#16308]
As part of the broader changes suggested to the publishing flow in https://github.com/WordPress/gutenberg/issues/7602#issuecomment-497816705, I'd like to recommend changing the wording on the publish button itself, depending on the post's scheduled status:

# Scheduled for a future date: 
Schedule post

# Posting immediately: 
Publish now
Publish

# Scheduled to publish on a date in the past: 
Publish retroactively

**Comment by kristastevens** [comment]
Hello @sarahmonster  -- clear and concise! 👍 says I. Thanks for the ping!

**Comment by sarahmonster** [comment]
@kristastevens You're way faster than I am—I was still busy editing my accidentally-posted suggestion above! (Computers are hard.)

Here's what these suggestions would like in context of the new proposed publishing flow:

Past:
![Publish in past](https://user-images.githubusercontent.com/376315/60198088-b98b1080-9838-11e9-8c51-afce59941fa6.png)

Present:
![Publish now](https://user-images.githubusercontent.com/376315/60198089-b98b1080-9838-11e9-9357-71b7e71095f5.png)

Future:
![Schedule publish](https://user-images.githubusercontent.com/376315/60198090-b98b1080-9838-11e9-8175-18b52f72669e.png)

Given that there's been some confusion around when a post will actually publish, the primary aim here is to make it _extremely clear_ when the post will actually publish using the various settings available.

See also: #16127

**Comment by kristastevens** [comment]
Hi @sarahmonster -- ha! Your timing was perfect. I was just about to start another project when your ping came in. I have some thoughts -- here there are: 

Since the date/timing of publication seems most important, what if we were to re-arrange the order of the messaging here: 

CASE: RETROACTIVE 

Ready to publish? 
Double-check your settings, then use the button to **retroactively** publish your post. 

Publish on
[retroactive date]
Your post will be published now and back-dated to **[date].**

Who can see my post?
Your post will be visible to **anyone who visits your website**.

Button text: Publish retroactively

----

CASE: PRESENT 

Ready to publish? 
Double-check your settings, then use the button to publish your post. 

Publish on
[today's date]
Your post will be published **right now**. 

Who can see my post?
Your post will be visible to **anyone who visits your website**.

Button text: Publish now

----

CASE: FUTURE 

Ready to publish? 
Double-check your settings, then use the button to schedule your post. 

Schedule for 
[date]
Your post will be published **in X days**. 

Who can see my post?
Your post will be visible to **anyone who visits your website**.

Button text: Schedule post

**Comment by afercia** [comment]
@sarahmonster thanks for your explorations and for focusing on potential accessibility issues related to the label change.

Generally, changing a control name "on the fly" can be problematic for users with accessibility needs. When a control's name changes _unexpectedly_, some users may not be able to understand what happened. For example: users explore content, find a "xyz" control, then something happens, and.. oh no! Where's "xyz" now? It disappeared. There's now a "zyx" control and users may be confused.

In this specific case, I'd tend to think the change from "Publish" to "Schedule" is OK because:
- it happens after an explicit user action
- it's what already happens in the classic editor and many users are used to it

I'm a bit more wary about "Publish retroactively" but just because the string is a bit too long, forces users to think at what it means, and it's difficult to translate in some languages. I'd like to propose to explore a shorter and simpler text.

**Comment by karmatosed** [comment]
I really like the idea of this following through the story of the post, particularly if it can balance accessibility. That said I wonder if we need to context it by saying 'post', could it just say Publish, Schedule? I also wonder about retroactively as a term here.

**Comment by chrisvanpatten** [comment]
I agree on "Publish retroactively" being a bit of a mouthful… it seems to suggest some kind of magical time travel 😅

For that specific case, I think just "Publish" is reasonable because the effect is that the post will be immediately available. Yes it will be set to a date in the past, but the result is still that the post is online for everyone _now_ — not available in the past.

**Comment by sarahmonster** [comment]
Okay, let's try these labels out in tandem with the copy changes being suggested in #16127:

![Pre-publish panel button label](https://user-images.githubusercontent.com/376315/61047640-d8aca500-a3d7-11e9-89d7-2cc73582dbf7.png)

I agree that "Publish retroactively" is a bit of a wordy way of putting it. My biggest concern is that we need a way to make it very clearly that the post will be published _immediately_, so as to avoid situations like the one in #13230. Perhaps the best solution would be to use "Publish now" for both past and present behaviours, since that's the effective result here? Or perhaps the new clarifications introduced here are sufficient to clarify user understanding of when and how a post will publish when back-dated (purposefully or otherwise).

What does everyone think?

**Comment by karmatosed** [comment]
This has been discussed in the weekly design triage meetings and now is being closed to consider iterating later. The focus right now is on other areas which will likely see this area improved in maybe a different direction.
