### ISSUE TITLE
Make block content available to PHP callbacks

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#1631]
`do_blocks()` extracts blocks from the post content and calls the block's render function to generate the dynamic output.

The callback receives the block's attributes as an argument, but not its content.

The Latest Posts block doesn't need the content, but I can imagine some other dynamic blocks would.

**Comment by felixarntz** [comment]
@swissspidy While I generally don't like to mix up fixes between multiple issues in one PR, I think it makes sense in this case here, since it integrates with the changes being made regarding block type classes. Therefore I added this functionality (also useful in case that no `render` argument has been provided) in the above commit / PR.

**Comment by youknowriad** [comment]
fixed in #1340
