### ISSUE TITLE
Inconsistent use of colours in Parapgraph block

### ISSUE THREAD

**Issue by zakalwe2016** [WordPress/gutenberg#16313]
**Describe the bug**
Inline styles are used to set colour of text and background for selected text in a paragraph but setting these for the block results in classes. This seems inconsistent.

**To reproduce**
1. Create a Paragraph Block
2. Enter some text
3. Select a background colour from "Colour Settings" (Not "Text Colour")
4. Select a text colour from "Colour Settings" (Not "Text Colour")

**Expected behavior**
Expect that colours are set inline as per selected text.

**Screenshots**
![image](https://user-images.githubusercontent.com/18077285/60203005-a92c6300-9843-11e9-8b55-cec1ae09c814.png)

Results in 

    <p class="has-text-color has-background has-very-light-gray-color has-vivid-red-background-color">
        <span style="background-color:#cf2e2e" class="tadv-background-color">Some text…</span>
    </p>
Classes generated `has-background`, `has-very-light-gray-color` and `has-vivid-red-background-color` instead of inline styles.

For a project I am working on, I have disabled the Gutenberg styles so I would need to add these to my CSS. It would be better IMO if these were output inline as other colours are.

**Comment by zakalwe2016** [comment]
This is also apparent in the Cover block:

```
<div class="wp-block-cover has-vivid-red-background-color has-background-dim" style="background-image:url(http://dev.culbonefinance.co.uk/wp-content/uploads/2019/06/slider.jpg);background-position:71.28712871287128% 45.23809523809524%">
    <div class="wp-block-cover__inner-container">
        <p style="text-align:center" class="has-large-font-size">Some text here</p>
        <p>Lorem Ipsum dolor site amet…</p>
    </div>
</div>
```

**Comment by markhowellsmead** [comment]
Additional technical explanation. This problem applies to every element and every block in which the colour or background colour can be editorially selected from the colour palette.

When choosing a colour from the palette in the editor, a `style` attribute is applied to the element containing a fixed RGB value. However, the saved HTML for the site contains a class name (e.g. `has-primary-color`), not a fixed RGB value.

The saved HTML is the correct approach: it allows a Theme developer to modify the colour value of `.has-primary-color` in the CSS file at any time.

Taking the example of primary being red (#ff000). The Theme developer's CSS includes `.has-primary-color {color: #ff0000;}`. If the CSS is later changed to `.has-primary-color {color: #0000ff;}`, the website is changed to blue, but the elements which were editorially marked as #ff0000 are still #ff0000 in the editor.

**Comment by markhowellsmead** [comment]
For a more in-depth use-case involving the Customizer and CSS variables, I've written a blog post at https://permanenttourist.ch/2020/04/combining-the-wordpress-customizer-and-gutenberg-editor-colour-palettes/. (Skip to https://permanenttourist.ch/2020/04/combining-the-wordpress-customizer-and-gutenberg-editor-colour-palettes/#unsolvableproblem for the relevant details.)

**Comment by talldan** [comment]
> Inline styles are used to set colour of text and background for selected text in a paragraph but setting these for the block results in classes. This seems inconsistent.

@zakalwe2016 Apologies for the delay in a response. When this issue was created, it wasn't actually possible to set colors on portions of selected text in the block editor, so I imagine this inconsistency was coming from a plugin you were using.

Currently, class names are used where possible if styles are provided by a theme. That means that when switching between themes, if the new theme has a color named the same, that color selection transfers. 

This seems to be consistent within the post content for block colors and the recently introduced text color feature.

I noticed that in the editor itself the block uses both class names and inline styles, but I can't see this would cause any issues since the colors are provided and defined by the theme anyway.

I'll close the issue as the original issue seems to be related to the plugin usage mentioned.

**Comment by markhowellsmead** [comment]
@talldan This problem is still current for me. I have no plugins installed.

**Comment by markhowellsmead** [comment]
Update: WordPress 5.4 appears to apply the class name in the saved HTML and the editor, but also applies the colour in duplication as a `style` attribute in the editor. With the current state of Gutenberg, I can't see a way of implementing the solution of customisable site-wide colours using the Customizer. I'm hoping that the site editing features which are currently in development will allow for this; for now I'll see whether I can solve the issue using a Child Theme.

**Comment by talldan** [comment]
@markhowellsmead That seems to be a different issue to the one the user reported, which is about color applied through formatting (provided by a plugin):
> Inline styles are used to set colour of text and background for selected text in a paragraph

The code snippet provided in the description demonstrates this:
```
<span style="background-color:#cf2e2e" class="tadv-background-color">Some text…</span>
```
The span above is formatting that applies color. It's unrelated to the paragraph block itself. When this issue was created the paragraph block didn't have this functionality so that's why I've closed the issue.

It's not uncommon for users to misinterpret functionality provided by a separate plugin as something that the core editor has provided.

Your issue seems separate, so I'd recommend making a new issue. However, I don't think it's a problem, the inline styles in the editor are applied when the editor loads. Those colors are supplied by the theme, so if the colors are adjust by the theme, the editor will also change the inline styles.

**Comment by markhowellsmead** [comment]
Thanks for the comprehensive answer. I'll find a different solution until the full site editing tech. has been developed further.
