### ISSUE TITLE
Icon color overrided

### ISSUE THREAD

**Issue by maximebj** [WordPress/gutenberg#16349]
Hi everyone

I have this issue: 

![capture 2019-06-28 à 14 31 27](https://user-images.githubusercontent.com/1785489/60342373-98016480-99b1-11e9-831f-bbdbad6ebf7a.jpg)

The result should be: 

![capture 2019-06-28 à 14 31 34](https://user-images.githubusercontent.com/1785489/60342389-9fc10900-99b1-11e9-9442-475b273a1164.jpg)

(and the icon is not centered)

It seems than it comes from this CSS:

`
.components-button.block-editor-block-switcher__no-switcher-icon:disabled .block-editor-block-icon.has-colors {
    color: #555d66!important;
}`

My Icon declaration: 

`icon: { background: '#874476', foreground: "#fff", src: 'warning' },`

Are you aware of this bug? Thanks!

**Comment by jorgefilipecosta** [comment]
I was able to verify this issue in the last version of WordPress, in the master branch, the problem is not happening now because we have the group transform available for all the blocks if we disable the group block the problem starts happening again. Thank you for reporting this issue @maximebj I think it is an unknown bug.

**Comment by maximebj** [comment]
Glad I can help (at my level) :)

**Comment by jorgefilipecosta** [comment]
It seems the color change is intentional to make the user aware that the icon is in a disabled state. The problem is that the background color is not being changed, which may cause the icon to look wrong or even totally unreadable; PR https://github.com/WordPress/gutenberg/pull/16390 fixes this problem.
