### ISSUE TITLE
Default Quote & Pullquote editor styles use extremely high "backwards" CSS specificity

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#16488]
**Describe the bug**
The default selector for setting `.wp-block-quote` styles in `editor-blocks.css` is:

```css
.wp-block-quote:not(.is-large):not(.is-style-large)
```

This means that the selector has the specificity of 3 classes which seems quite high for a default block. It is also logically very strange and goes against CSS orthodoxy that the _default_ value essentially blacklists the core style variations for the block. The default should have the lowest specificity!

The same issue then continues with the `cite` styles:

```css
.wp-block-quote:not(.is-large):not(.is-style-large) .wp-block-quote__citation
```

The same thing (but slightly better) impacts the pullquote block:

```css
.wp-block-pullquote:not(.is-style-solid-color)
```

**Expected behavior**
When providing my own block editor styles, I would expect to write them more or less like this:

```css
.editor-styles-wrapper .wp-block-quote {}

.editor-styles-wrapper .wp-block-quote.is-large,
.editor-styles-wrapper .wp-block-quote.is-style-large {}
```

This is the minimum specificity allowed by the editor style convention that includes the `.editor-styles-wrapper`.

Because of the higher specificity, it's extremely hard to write automated styles that work on both the front and back end where the structural markup is different.

I would hope to be able to do something like this:

`_blocks.scss`:
```css
.wp-block-quote {}
```

`block-styles.scss`:
```sass
.editor-styles-wrapper { @import blocks; }
```

My current workaround is to use the repeating class "hack", but this can have a cascading effect of increasing the specificity of many other selectors:

```css
.wp-block-quote.wp-block-quote.wp-block-quote.wp-block-quote /* specificity = 4 classes */
```

**Additional context**
WordPress 5.2.2

**Comment by DouglasMilnes** [comment]
I have just been having similar problems finding `.wp-block-pullquote:not(.is-style-solid-color)`, having discovered I can do with custom block styles. Trying to ensure that my CSS addresses the style for the block chosen and only the block chosen has been horrible. And at that, I'm not going halfway to stop people doing something daft (like put a pullquote inside a blockquote, which I'd like to style as just a paragraph).

Selectors I stumbled across lately:
```
    .wp-block-pullquote:not(.is-style-solid-color) 
    .wp-block-cover-image .wp-block-subhead:not(.has-text-color)
    .wp-block-social-links:not(.is-style-logos-only) .wp-social-link
```

I know that sometimes this is inevitable and I'm glad I don't have to deal with `.wp-block-table.is-style-stripes.has-subtle-pale-pink-background-color tbody tr:nth-child(odd)` but the CSS we have to deal with should be as clean and specific as possible.

Even worse is that I found I had to drop in far too many `!important` imperatives because my child theme stylesheet is being overridden by later Wordpress standard styling. Maybe that's another issue..

**Comment by ellatrix** [comment]
Cc @aaronrobertshaw @talldan maybe this should also be fixed with :where

**Comment by mrwweb** [comment]
It would help to have someone else confirm, but I think this issue may have been resolved in the past few versions, at least when using `theme.json` for styling.

**Comment by aaronrobertshaw** [comment]
Thanks for the ping @ellatrix and re-testing this @mrwweb 👍 

I've looked into this one and I cannot replicate any issues either. @mrwweb is correct that the issues noted here have been resolved at various points since the issue was created.

---

#### Quote

The quote block selectors were fixed via https://github.com/WordPress/gutenberg/pull/47969. The `large` block style is deprecated so the styles since #47969 have been kept for backwards compatibility purposes.

#### Pullquote

The `is-style-solid-color` block style for the pullquote block has been deprecated for a while now. The selectors for its styles have been left untouched as well. 

The specific selector mentioned here, `.wp-block-pullquote:not(.is-style-solid-color)`, was removed when the solid color block style was deprecated in #39413 .

#### Subheading Block

For `.wp-block-cover-image .wp-block-subhead:not(.has-text-color)`, it turns out the subheading block was never stabilized in core and was later removed in https://github.com/WordPress/gutenberg/pull/29627. This selector was removed at the same time.

#### Social Links

The Social Links block had its styles updated recently to ensure compatibility with the new `0-1-0` capping of global styles specificity. See https://github.com/WordPress/gutenberg/pull/63049.

The updates in https://github.com/WordPress/gutenberg/pull/63049 combined with the recent reduction of global styles specificity across the board should help alleviate the original problem this issue relates to i.e. the high specificity of core styles.


---

I'd vote to close this issue as resolved. What do you all think?

**Comment by mrwweb** [comment]
Sounds right to me! Closing.
