### ISSUE TITLE
Simplify Button Block Styles

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#16481]
We should revise the style variations we are offering for the button block as we have created a matrix of outline/fill rounded/squared that is not the most elegant or usable. ("How can I get a squared and outlined button?")

I'd suggest removing the square/round pairs from the style selection and turning that into a border radius setting instead. That'd allow us to keep just two style variations (fill / outline).

**Comment by truchot** [comment]
I agree with @mtias! 

If default button is already styled (by theme most overtime) with no radius the squared style is useless.

**Comment by benoitchantre** [comment]
Great idea.

Is it really necessary to add a border radius setting?
I think it is better for consistency if the style radius comes from CSS.

**Comment by mapk** [comment]
Would the `border-radius` setting be per block? I ask because changing the `border-radius` of buttons is probably something that makes more sense in the global settings arena which we don't really have yet.

Maybe getting this setting into the Button block is a good version 1. I'd love to see this expand into a global setting in the future as those are explored more.

**Comment by mtias** [comment]
> I ask because changing the border-radius of buttons is probably something that makes more sense in the global settings arena which we don't really have yet.

This is a good point, but also applies to style variations in general. We've discussed allowing setting certain attributes as defaults for any new block, and some of that is covered in https://github.com/WordPress/gutenberg/issues/7551

**Comment by klihelp** [comment]
+1
