### ISSUE TITLE
Gutenberg - Transition [Transform] Bug on Reordering 

### ISSUE THREAD

**Issue by BenjaminZekavica** [WordPress/gutenberg#16519]
I open now a Issue Ticket because more in some Themes the new transition animation it doesn't work fine in the latest version of Gutenberg. 

You have to change the Transform CSS. More details here: 
https://github.com/WordPress/gutenberg/pull/16065#issuecomment-510158699 

For example the new Twenty Nineteen Theme: https://github.com/WordPress/gutenberg/pull/16065#issuecomment-509231071

**Comment by ellatrix** [comment]
This is caused by `translate3d(0px, 0px, 0px)` after #16065. To reproduce, look at the full sized image or embed block in the demo content.

<img width="452" alt="Screenshot 2019-07-08 at 15 43 42" src="https://user-images.githubusercontent.com/4710635/60815113-3dc58800-a197-11e9-9497-ede1ec4c6777.png">
