### ISSUE TITLE
Provide a way to identify the source of a block

### ISSUE THREAD

**Issue by Otto42** [WordPress/gutenberg#16521]
With the prevalence of new blocks and possibly the start of a new block directory, it seems like more and more it is possible for users to be using a block without knowing where it came from.

Example:

https://www.reddit.com/r/Wordpress/comments/cb58se/why_is_my_gutenberg_table_of_contents_non/

TL;DR: User asked about a table of contents block, when asked what plugin added it, they thought it was a default block. 

Blocks need to have some way to identify themselves and where they come from to the end-user. Simple "branding" isn't going to be enough, this should be built into the structure of the block system and exposed somewhere as a standard item.

**Comment by TimothyBJacobs** [comment]
💯 I see this at our local meetup as well.

**Comment by marekhrabe** [comment]
I have noticed the Plugin directory started to list block in the detail view by their name (`prefix/block` format). See for example https://wordpress.org/plugins/atomic-blocks/#blocks. 

It might be good to show this block name somewhere in the UI of Gutenberg. What about the sidebar with block settings? Would that be too prominent? 

<img width="280" alt="Screenshot 2019-07-31 at 17 22 46" src="https://user-images.githubusercontent.com/156676/62256854-d5de1800-b3b7-11e9-90e8-ee0f2814352a.png">

I guess the block name was always considered something that users don't directly see but with those being slowly exposed in other places and the issue with identifying blocks, this might become important.

**Comment by marekhrabe** [comment]
The Block Manager could be another good place where this would make sense and won't be on eyes all the time.

<img width="200" alt="Screenshot 2019-07-31 at 17 30 28" src="https://user-images.githubusercontent.com/156676/62257206-3c176a80-b3b9-11e9-95d2-bd6c5c20cf7d.png">

**Comment by mtias** [comment]
If we instrument collections (#16866), it could be surfaced next to the block name / description in the sidebar.

**Comment by richtabor** [comment]
We chatted about this in today's design meeting ([Slack](https://wordpress.slack.com/archives/C02S78ZAL/p1580835949156900)). Adding the source under the title in the Settings Sidebar seems logical, though two notes: 

1. Perhaps we could employ a more natural label "from CoBlocks". 

2. Do core blocks need this, or only third party blocks?

**Comment by StevenDufresne** [comment]
> Perhaps we could employ a more natural label "from CoBlocks".

This makes the most sense to me since the block type is a technical detail and not expected to be surfaced this visibly. 

Riffing on this idea.... I believe, as the block directory evolves and more third party blocks are used, users will want access to more meta information about the block than just its author. Based on the current bock directory flow, it isn't apparent where I can go to learn more about the block (at least until some of the new block directory `wp-admin` views are implemented). Moreover, as blocks become more complex, space in the `BlockInspector` will be very valuable (Some conversations are already happening in the[ plugin guidelines](https://github.com/WordPress/wporg-plugin-guidelines/pull/68)).

**Potential Solutions**
1. Could we make the block title a link?
2. Add the natural label as @richtabor suggests and link to details.

_*Note: I'm making the assumption that all plugins will have a details view._

These links could open up a new page with the block details open?

![Settings](https://d.pr/i/g5l5rP.png)


This would help make sure that the editor and the block inspector are focused on fulfilling its first mission, building.... and delegating secondary tasks elsewhere.

**Comment by annezazu** [comment]
So much has changed in the five years since this was opened (!!!). I'm going to close this out as a result in favor of a more recent issue that matches current designs on the same topic: https://github.com/WordPress/gutenberg/issues/64532
