### ISSUE TITLE
Isuue with editor.BlockListBlock filter after v6.1

### ISSUE THREAD

**Issue by amyriounis** [WordPress/gutenberg#16540]
The issue is present when the `style` prop is modified using the `editor.BlockListBlock` filter.

Let's suppose I need to add some custom styles to a block's wrapper element (only `core/image` for the example). Currently I'm using something similar to that:

```javascript
const { createHigherOrderComponent } = wp.compose;

const withStyles = createHigherOrderComponent( ( BlockListBlock ) => {
	return ( props ) => {
		if ( props.block.name !== 'core/image' ) {
			return <BlockListBlock { ...props } />;
		}

		let wrapperProps = props.wrapperProps;
		wrapperProps = {
			...wrapperProps,
			style: {
				...( wrapperProps && { ...wrapperProps.style } ),
				marginBottom: '30px',
			},
		};
		return <BlockListBlock { ...props } wrapperProps={ wrapperProps } />;
	};
}, 'withStyles' );

wp.hooks.addFilter( 'editor.BlockListBlock', `my-plugin/core-image-blb-with-styles`, withStyles );
```
This approach seems to collide with the changes introduced in #16065.

**To reproduce**
1. Use the snippet above. 
2. Add two image blocks and a heading.
3. Remove the first image block.

You should get something like this:
![Screen record from 2019-07-11 17 39 19](https://user-images.githubusercontent.com/9055437/61060415-28ed2c80-a403-11e9-9564-759451d41cd4.gif)

**Comment by jrtashjian** [comment]
We're seeing the same issue while debugging an issue submitted to CoBlocks with an almost identical code snippet: https://github.com/godaddy/coblocks/issues/668

I took some time to debug this today and here are my findings:

When inspecting a block with the React Developer Tools, the `style` prop of the wrapper includes the new transform styles required for the new motion stuff. When I add a filter to add new styles and inspect the block with the React Developer Tools, the `style` prop only includes my new styles (no transform styles). I expect them to be merged.

When debugging the filter `editor.BlockListBlock`, the `wrapperProps` are always undefined so it is impossible to properly merge new values using `Object.assign` onto existing values. If they are always undefined I would expect it's because my filter is being applied first and the next filters should properly handle merging as well. However, only my `style` props exist.

I think the issues might be around this bit of code but have not debugged further: https://github.com/WordPress/gutenberg/blob/3279e116b9486099a681282a7aae050c96f563c6/packages/block-editor/src/components/block-list/block.js#L410-L417

**Comment by amyriounis** [comment]
@jrtashjian Haven't properly debugged this but just by looking at the code I can tell that if `blockWrapperProps` contains a  `style` prop it will override the style attribute used for the animation here:

https://github.com/WordPress/gutenberg/blob/3279e116b9486099a681282a7aae050c96f563c6/packages/block-editor/src/components/block-list/block.js#L469-L470

A simple merge would probably solve this issue. I don't think there is a way around it from a developer's standpoint (besides not using the style prop) as you don't have access to both variables when using the `editor.BlockListBlock` filter. I ended up disabling the animations through CSS to have everything working until this gets resolved.

**Comment by jrtashjian** [comment]
Good catch! I’m going to look more into this later today to try and get a patch submitted.
