### ISSUE TITLE
Widgets: Missing the block appender button from the Block Areas

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#16601]
In the new widgets screen in wp-admin we're missing the block appender button from the Block Areas. Can we get it added?

**Current:**

![Screen Shot 2019-07-15 at 2 16 42 PM](https://user-images.githubusercontent.com/617986/61249959-5be93600-a70b-11e9-9ecc-af1fd0d97908.png)

**Proposed:**

![Screen Shot 2019-07-15 at 2 20 31 PM](https://user-images.githubusercontent.com/617986/61250115-c0a49080-a70b-11e9-9984-08af4d4967ec.png)

**Comment by karmatosed** [comment]
I wonder if we also need the title and description over just having a block appender? It's worth seeing I think as otherwise almost reads like a post/page writing.

**Comment by jorgefilipecosta** [comment]
Hi @mapk, and @karmatosed thank you for identifying and discussing this issue.
It seems the block appender is not appearing because the styles required for it to work are part of the edit-post module.
PR https://github.com/WordPress/gutenberg/pull/16943 fixes this problem and the default block appender starts appearing. It solves the issue by providing the same appender as the normal post editor.
If for this scenario having a custom appender is a must, I guess we can follow up by allowing the block editor module to be more customizable, similar to what we allow now for inner blocks.

**Comment by jorgefilipecosta** [comment]
Fixed in: https://github.com/WordPress/gutenberg/pull/16971
