### ISSUE TITLE
useSelect doesn't return the updated value if it is not an object.

### ISSUE THREAD

**Issue by alvaro0555** [WordPress/gutenberg#16612]
**Describe the bug**
Following the documentation of [useSelect hook](https://github.com/WordPress/gutenberg/tree/master/packages/data#useSelect) to return a value from the store (custom or core) the updated value is only returned if the callback returns an object.

**To reproduce**
Try the following **isolated**. Notice that in the third example `getSelectedBlock()` is being returned as is. 

Doesn't update
`const is_typing = useSelect(select => select("core/block-editor").isTyping());`

Updates correctly
`const is_typing = useSelect(select => ({ value: select("core/block-editor").isTyping() }));`

Updates correctly
`const selected = useSelect(select => select("core/block-editor").getSelectedBlock());`

**Version:**
 - WordPress: 5.2.2
 - Gutenberg 6.1.1

**Comment by youknowriad** [comment]
cc @nerrad @epiqueras

**Comment by nerrad** [comment]
Ya, `useSelect` is doing a `isShallowEqualObjects` comparison: https://github.com/WordPress/gutenberg/blob/a894b3520598eceb91ddd8bb0299024b4f970afa/packages/data/src/components/use-select/index.js#L132-L134

So the question then is:

- do we update documentation so that its clear the `mapSelect` callback should return an object OR
- do we modify `useSelect` so that it will do shallow compares of arrays and primitive types as well?

I think the latter would be useful.

**Comment by epiqueras** [comment]
I'd go with the latter as well. We should have a shallow comparison helper that handles all data types.

**Comment by nerrad** [comment]
I probably will find some time to do that this week.
