### ISSUE TITLE
Open page in new tab option

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#16636]
Implement the option to open any menu item in a new tab and add the option to the inspector.

**Comment by sarahmonster** [comment]
I'd actually love for us _not_ to include this at all as an option. It's a poor user experience and it's bad for accessibility, since it highjacks the native user experience and takes control away from the user.

I can open any link in a new tab if I want, but I can't force a link that's set to open in a new tab to open in the same tab.

From the [W3](https://www.w3.org/TR/WCAG20-TECHS/G200.html): 

> In general, it is better not to open new windows and tabs since they can be disorienting for people, especially people who have difficulty perceiving visual content. However there are some situations where it is preferable from an accessibility perspective to open a new window or tab. Here are two such situations:

> Opening a page containing context-sensitive information, such as help instructions, or an alternate means of completing a form, such as a calendar-based date picker, will significantly disrupt a multi-step workflow, such as filling in and submitting a form, if the page is opened in the same window or tab.

> The user is logged into a secured area of a site, and following a link to a page outside of the secured area would terminate the user's logon. In this case opening external links in an external window allows the user to access such references while keeping their login active in the original window.

The first case here seems extraordinarily unlikely, whilst the second case is probably rare enough that it's okay not to design explicitly for it. 

If we think it's valuable to offer this functionality in spite of the concerns about accessibility and usability, we should probably include a warning to let users know this isn't an advised practise (similar to the colour contrast warning) and use an indication to let users know that the link will open in a new window.

**Comment by grahamarmfield** [comment]
I agree with @sarahmonster

**Comment by noisysocks** [comment]
Closing this. https://github.com/WordPress/gutenberg/issues/17539 tracks enhancements to the Menu item block.
