### ISSUE TITLE
quotation marks or inverted commas not working as expected 

### ISSUE THREAD

**Issue by arvindsinghu** [WordPress/gutenberg#1663]
i was using the plugin for testing and i thought to write new post and found that the quotation marks or inverted commas are not working as expected . 

like i selected the text on which i want quotation marks or inverted commas but the quotation marks or inverted commas where selected for whole post  .

let me explain you by my post example.

![2017-07-03](https://user-images.githubusercontent.com/25670904/27792510-a973060e-6017-11e7-8edf-18a9cbe59ac9.png)

1 : i thought to add quotation marks or inverted commas "Niantic Inc., creator of Pokemon Go, will release a rare Pikachu" line . i selected quotation marks or inverted commas , and when i saw the preview than it was showing the quotation marks or inverted commas for whole .

**Comment by karmatosed** [comment]
Hmm this is interesting, I'm trying to work out what is going on and I think it could be due to the theme over Gutenberg. Lets pick this apart a bit. Can you try using Twenty Seventeen for example? Do you get the same issue? If you do, can you please provide exact step by step instructions and I'll try and replicate.

**Comment by arvindsinghu** [comment]
Hello ,
I found this error while adding tuition Mark or inverted commas while
typing the post :)


Thank you

~Arvind Singh

**Comment by karmatosed** [comment]
I am unable to get this to have an issue on the latest version, so closing for now. We can always reopen.
