### ISSUE TITLE
ResizableBox example does not resize

### ISSUE THREAD

**Issue by snnsnn** [WordPress/gutenberg#16652]
**Describe the bug**
The ResizableBox example in README.md does not resize and cursor never changes to resize syle.

Here is the code I used:

```
import * as React from 'react';
import { ResizableBox } from '@wordpress/components';

const Edit = (props: any) => {
  const {
    attributes: { height, width },
    setAttributes,
    toggleSelection,
  } = props;

  return (
    <ResizableBox
      size={{
        height,
        width,
      }}
      style={{
        backgroundColor: 'orange',
      }}
      minHeight="50"
      minWidth="50"
      enable={{
        top: false,
        right: true,
        bottom: true,
        left: false,
        topRight: false,
        bottomRight: true,
        bottomLeft: false,
        topLeft: false,
      }}
      onResizeStop={(event, direction, elt, delta) => {
        setAttributes({
          height: parseInt(height + delta.height, 10),
          width: parseInt(width + delta.width, 10),
        });
        toggleSelection(true);
      }}
      onResizeStart={() => {
        toggleSelection(false);
      }}
    >Some text</ResizableBox>
  );
};

export default Edit;
```

But when I use original module instead of exported one, it works as expected:

```
import { Resizable as ResizableBox } from 're-resizable';
```

Here is what ResizableBox from components renders onto page:
```
<div data-block="a4765993-8e9b-4331-bc85-78ed55288e4f"><div class="components-resizable-box__container" style="position: relative; user-select: auto; background-color: orange; width: 100px; height: 100px; box-sizing: border-box;">Some text<span><div class="components-resizable-box__handle components-resizable-box__side-handle components-resizable-box__handle-right" style="position: absolute; user-select: none; cursor: col-resize;"></div><div class="components-resizable-box__handle components-resizable-box__side-handle components-resizable-box__handle-bottom" style="position: absolute; user-select: none; cursor: row-resize;"></div><div class="components-resizable-box__handle components-resizable-box__corner-handle components-resizable-box__handle-bottom components-resizable-box__handle-right" style="position: absolute; user-select: none; cursor: se-resize;"></div></span></div><div class="__resizable_base__" style="width: 100%; height: 100%; position: absolute; transform: scale(0, 0); left: 0px; flex: 0 1 0%;"></div></div>
```

Here what original Resizable component from 're-resizable' module renders onto page:
```
<div data-block="f51637e3-cc3f-492a-8eb5-c456ea316893"><div style="position: relative; user-select: auto; background-color: orange; width: 100px; height: 100px; box-sizing: border-box;">Some text<span><div class="" style="position: absolute; user-select: none; width: 10px; height: 100%; top: 0px; right: -5px; cursor: col-resize;"></div><div class="" style="position: absolute; user-select: none; width: 100%; height: 10px; bottom: -5px; left: 0px; cursor: row-resize;"></div><div class="" style="position: absolute; user-select: none; width: 20px; height: 20px; right: -10px; bottom: -10px; cursor: se-resize;"></div></span></div><div class="__resizable_base__" style="width: 100%; height: 100%; position: absolute; transform: scale(0, 0); left: 0px; flex: 0 1 0%;"></div></div>
```
Note: Gutenberg Handbook also uses same example.

**Comment by derweili** [comment]
I can confirm this bug.
Original re-resizable component works well.

**Comment by derweili** [comment]
I testet the component again an found out that the `ResizableBlox` is indeed working.

The reason why it seems not not to work is because the handles (used for resizing) are hidden by default. 

https://github.com/WordPress/gutenberg/blob/bd76217166e0d75793ca20b63ad5d4c89119b321/packages/components/src/resizable-box/style.scss#L3-L7

This makes sense because the handles should only be visible when the Block is selected.
Unfortunately there is not documentation about this behavior.

To show the handles you need to add following css to your block:
```
.components-resizable-box__handle {
	display: block;
}
```

Thats the way how the core-blocks solve it:
Media-Text block
https://github.com/WordPress/gutenberg/blob/672599a74c5a373cfba7c83a0616e7d9e3af8023/packages/block-library/src/media-text/editor.scss#L53-L69
Image block
https://github.com/WordPress/gutenberg/blob/7964f381e07e06b2ac13698fd1465a4d0c16da1b/packages/block-library/src/image/editor.scss#L33-L36

There should be definitely be a documentation about this.

To improve the usage of the Component, I would recommend to add an "official" way to show/hide the handles, instead of a bunch of individual solutions.

This could be done by adding an new attribute "showHandles" to the `ResizableBox` which shows/hides those handles.
This attributes accepts a boolean value and should be false by default to ensure backwards compatibility

**Comment by ItsJonQ** [comment]
@snnsnn Oof! That's a bummer. 

> This could be done by adding an new attribute "showHandles" to the ResizableBox which shows/hides those handles.

@derweili That's a great suggestion! I create a PR to help resolve this :)

https://github.com/WordPress/gutenberg/pull/18097
