### ISSUE TITLE
Post Transition Status actions not working in Gutenberg

### ISSUE THREAD

**Issue by tomhrtly** [WordPress/gutenberg#16706]
**Describe the bug**

As a contributor, when adding a custom function using `add_action()` into the `draft_to_pending` post status transition, if I add `wp_die()` into my custom function, a Gutenberg error will appear saying "Updating failed" but the post will still be set to "Pending Review".

**To reproduce**
1. Add the following code to your `functions.php` file:

```
function my_custom_function() {
    wp_die();
}
add_action('draft_to_pending', 'my_custom_function');
```

2. Create a new post, save it as a draft and then submit the post to be reviewed.
3. See the "Updating failed" error message.
4. Go to the post listing page and see the post status has been changed from "Draft" to "Pending Review".

**Expected behavior**
The post status should not have changed to "Pending Review" but stayed on "Draft".

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 75

Gutenberg version: 6.1.1

**Comment by derweili** [comment]
The hook `draft_to_pending` is called after the post was updated.
You can't prevent the post-transition with the `draft_to_pending` hook because it already happend at this point.

Because you abort php execution, Gutenberg receives an invalid response from the REST-API.
Gutenberg can't know why the response is invalid and if the post was updated or not.

Maybe the error message should be changed to something like 
*"An error occured. Updating the post update may not have worked."*


I'm not sure what your original intention is but I think you need another hook to get the result you want:

- You can use the `map_meta_cap` filter to dynamically grant or deny the user permission to update a post.
- You can als use the `wp_insert_post_data` filter to manipulate the post data before a it is inserted into the database.

**Comment by tomhrtly** [comment]
@derweili Thanks for the clarification, I was under the impression that the `draft_to_pending` hook occurred before the transition.

For my project, I'm simply passing conditionals inside the function that is hooked into `draft_to_pending`. So if the conditionals fail, the post transition is still happening when I don't want it to.

On a separate note, is it possible to change the error that is displayed in Gutenberg from "Updating failed" to a different paragraph?

**Comment by derweili** [comment]
> For my project, I'm simply passing conditionals inside the function that is hooked into draft_to_pending. So if the conditionals fail, the post transition is still happening when I don't want it to.

Maybe you can use the [`rest_pre_insert_{$this->post_type}`](https://developer.wordpress.org/reference/hooks/rest_pre_insert_this-post_type/) filter instead.


> On a separate note, is it possible to change the error that is displayed in Gutenberg from "Updating failed" to a different paragraph?

Not I don't think so. 

Its hardcoded  and I don't think there is a filter available for that, but I'm not 100% sure.

**Comment by derweili** [comment]
> For my project, I'm simply passing conditionals inside the function that is hooked into draft_to_pending. So if the conditionals fail, the post transition is still happening when I don't want it to.

Maybe you can use the `rest_pre_insert_{$this->post_type}` filter instead.


> On a separate note, is it possible to change the error that is displayed in Gutenberg from "Updating failed" to a different paragraph?

Not I don't think so. 

Its hardcoded  and I don't think there is a filter available for that, but I'm not 100% sure.

**Comment by tomhrtly** [comment]
@derweili Will take a look at that filter, thanks for your help!
