### ISSUE TITLE
Allow user to change block editor width

### ISSUE THREAD

**Issue by jankimoradiya-multidots** [WordPress/gutenberg#16747]
**Is your feature request related to a problem? Please describe.**
- In the block-based editor, the editor width is small. when users are creating pages/posts using it the page editor looks very congested to add blocks to create pages and editor is not showing good compare to the front side of the page.

**Describe the solution you'd like**
- We can add the feature to change editor width in by default WordPress/Gutenberg rather than theme option. This feature will change only the editor width of the pages/posts not frontside.

- I have implemented this type of feature by creating as plugin and I am using that.

- Please see below video for "Gutenberg Editor Width Change".
https://drive.google.com/file/d/1plNQKGuC-rZ_vymwYiwAiKaOAayl3M8X/view

**Describe alternatives you've considered**
- I have seen that currently, the user/theme developer can add the setting to change the editor width in the theme setting by using [theme-support](https://developer.wordpress.org/block-editor/developers/themes/theme-support/#changing-the-width-of-the-editor). but when the non-technical user use the block-based editor to create pages/posts and their theme( which users are using) haven't this type of setting to change editor width.

- So, I thought we can add this type of features in by default WordPress/Gutenberg. 

Please share feedback for the same. Any thoughts are most welcomes....!!!

Thanks in Advance...

**Comment by swissspidy** [comment]
The editor width is directly influenced by how the content is presented on the front end. It would be very odd to have a wide editor area but a narrow presentation on the actual website. That's why it's the theme's responsibility to adjust the editor width accordingly. Perhaps you can elaborate on why that's not enough?

**Comment by jankimoradiya-multidots** [comment]
Thank you @swissspidy for the feedback.

I thought that if the non-technical users are using WordPress to create their site and they have used themes which haven't option to change editor width at that time they feel odd while creating pages in the narrow editor.

It is good for me to allow the user to change block editor width by theme but I have thought it maybe we can it in default WordPress. then users haven't need to add it in their themes or no need to use any extra plugin for change editor width.

Thanks

**Comment by youknowriad** [comment]
I think if there's a UI to change the editor width, it should also affect the frontend at the same time. That's not possible at the moment because themes are hand-written in php code, so there's no way to consistently apply that to the frontend.

The best tradeoff, for now, is to keep it as a theme responsibility.

Thanks for your understanding.
