### ISSUE TITLE
Make only styling you can do available

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#1677]
The strikethrough is only available on highlighted text, this actually makes a lot of sense. However, you see it as an option even when not highlighting. Perhaps thls does not make as much sense?

![strike](https://user-images.githubusercontent.com/253067/27804540-5e39d4be-6027-11e7-9a1d-44c4f8ecb07f.gif)

**Comment by kevinwhoffman** [comment]
The current strikethrough behavior seems in line with bold and italic, in that a click toggles the behavior on and off. Some users may prefer to toggle it on before they begin typing, rather than typing, then highlighting, then clicking strikethrough. I think it's best to keep it consistent with the bold and italic controls as it is now.

**Comment by karmatosed** [comment]
As a flow we've improved things and so closing this right now.
