### ISSUE TITLE
Column Bock Does Not Save Pasted Text

### ISSUE THREAD

**Issue by dschiera95** [WordPress/gutenberg#16798]
**Describe the bug**
When I copy and paste text into a Paragraph block inside of a Column block and save, the text does not actually save, and the text is gone when you reload the edit page.

**To reproduce**
1. Add a new page
2. Add a Column block
3. Add a paragraph block to a Column of the Column block
4. Copy and paste some text into the Paragraph block
5. Publish the page
6. View the page. Copied text is not there
7. Go back to editor. Copied text is no longer there either.

**Expected behavior**
Text that is copied and pasted into a Paragraph block inside a Column block should be saved to the page when the page is published.

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - Browser: Chrome
 - Version: 75.0.3770.142

**Additional context**
- Gutenberg Version: 6.1.1
- WordPress Version: 5.2.2

**Comment by tmdesigned** [comment]
I was able to reproduce this on Gutenberg 6.1.1. 

However, I am unable to reproduce it on 6.2 beta or on the default version shipped with WordPress. It seems to only be present on the 6.1 beta.

I believe it is the same as Issue #16645 which is fixed by #16717 

Since the bug was only recently introduced, you could temporarily downgrade from the beta or upgrade to the 6.2 beta version.

**Comment by dschiera95** [comment]
@tmdesigned, Thanks! I verified that the bug is fixed in 6.2.0-rc.1.
