### ISSUE TITLE
blocks.getBlockDefaultClassName filter is not applied to heading, paragraph and image blocks.

### ISSUE THREAD

**Issue by hatsumatsu** [WordPress/gutenberg#16884]
**Describe the bug**
The filter `blocks.getBlockDefaultClassName` does not alter the class attribute of heading, paragraph and image block.

**To reproduce**
1. Add the filter as decribed [in the docs](https://developer.wordpress.org/block-editor/developers/filters/block-filters/#blocks-getblockdefaultclassname)
`````
function addBlockCustomClassName( className ) {
    return 'wp-block ' + className;
}

// Adding the filter
wp.hooks.addFilter(
    'blocks.getBlockDefaultClassName',
    'my-plugin/add-block-custom-class-name',
    addBlockCustomClassName
);
`````
2. Class attribute of blocks like columns, group etc. is altered correctly but paragraph, heading and image blocks are untouched.

**Expected behavior**
All block should be affected by the filter.

**Comment by youknowriad** [comment]
That's not a bug, these blocks opt-out of the default className.

**Comment by hatsumatsu** [comment]
@youknowriad okay, but why? In the editor these are treated as and called `blocks`. Shouldn't it be possible to target all blocks in CSS via a generic class?

Coming from https://github.com/WordPress/gutenberg/issues/6639 it seems that both workarounds to easily target all blocks via one CSS selector don't work.

**Comment by youknowriad** [comment]
> okay, but why? In the editor these are treated as and called blocks

Because they are blocks, a block is not necessary something with a given class. A block can even be multiple DOM elements without any wrapper. A block doesn't map to a DOM element, it's just an entity that wrappes a fragment of content and allows you to edit it visually.

In the case of paragraphs, headings and images we decided to opt-out of these classNames because these blocks are too common and we don't want to pollute the post-content with these. 

I hope that answers your questions.

**Comment by hatsumatsu** [comment]
Okay, thanks for clarifying. Guess the expectations of what the desired markup looks like differ based on different frontend workflows. I was just hoping for a clean BEM-like code style...
