### ISSUE TITLE
Top toolbar items unnecessarily buried on large screens

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#16889]
### Problem

Some items in the top toolbar are hidden behind a dropdown menu, even when there is plenty of space to show them:

<img width="2046" alt="Screen Shot 2019-08-02 at 8 01 59 AM" src="https://user-images.githubusercontent.com/484068/62379466-df709880-b4fb-11e9-87a6-777c1ca1fb9c.png">

This makes them harder to discover, and means that mouse users have to do an extra click every time they want to use those buttons.

Was that an intentional design decision to avoid overwhelming the user, or does the toolbar not adapt just because that feature wasn't part of the MVP?

### Proposed Solution

When there's space for it, all of the toolbar's items should be shown. When there isn't, they should be automatically moved to dropdown menu, like they are today.

**Comment by karmatosed** [comment]
My concern here is moving interaction elements because of screen size. I totally get on larger screens there is the space, but I don't think that means we should surface everything. I'd love for opinions here on if those icons are important enough to show on top level or belong in secondary under a drop down. For me, they are secondary enough for drop down.

**Comment by kjellr** [comment]
I agree with @karmatosed on this one. In this particular case, the items in the dropdown aren't necessarily there only because they don't fit, but because they're less important used than the Bold/Italic/Link buttons. As another example, we also recently [made the decision](https://github.com/WordPress/gutenberg/pull/16557) to hide all alignment toolbar items behind a dropdown for other reasons too. 

For what it's worth though, it does look like Google auto-expands as the screen gets bigger: 

![docs](https://user-images.githubusercontent.com/1202812/62487559-2d053380-b790-11e9-99cb-8f945c326cc5.gif)

**Comment by mapk** [comment]
The example provided shows the Top Toolbar option enabled. In that particular case, one might have room to allow more icons to be surfaced. When moving these icons into dropdowns, I did not consider the Top Toolbar option. It might be worth revisiting this.

The best thing to help this move forward would be to list which icons/actions are the ones to be surfaced or develop a rule of some kind like "When there is room, begin from the left and expand each dropdown until there is no more room." I'm just throwing out ideas here.

**Comment by kjellr** [comment]
> The example provided shows the Top Toolbar option enabled.

That's true. This could be something that's only available in that mode.

**Comment by drw158** [comment]
Expanding to show more icons on bigger viewports seems like a good idea to me, as long as it's not a justification to add additional icons/buttons. (i.e. "There's room for more buttons here, so why don't we add x feature to the top toolbar?")

**Comment by davidshq** [comment]
I understand not showing all the formatting buttons due to importance, but it would be nice to be able to surface some buttons if the user desired. e.g., someone may find x button something they use frequently, having to click on a dropdown every time (assuming no keyboard shortcut, or user is not aware of shortcut) gets tedious.

**Comment by mapk** [comment]
> e.g., someone may find x button something they use frequently, having to click on a dropdown every time (assuming no keyboard shortcut, or user is not aware of shortcut) gets tedious.

I understand the concern here. It's a good point. But I'd rather make purposeful decisions and limit the options presented to a user. I believe we did this well here and suggest we keep the it this way right now, but consider showing them in the Top Toolbar.
