### ISSUE TITLE
Stylesheets added with add_editor_style() are not loaded on the new widget screen.

### ISSUE THREAD

**Issue by oxyc** [WordPress/gutenberg#16968]
**Describe the bug**

Stylesheets added with `add_editor_style()` are not loaded on the new widget screen thus user applied styling isn't taken into account.

**To reproduce**

1. Add a stylesheet using `add_editor_style()`
2. Open up the new widget screen
3. Notice that the blocks are not getting user defined styles applied.

**Expected behavior**

I expect that the styles I've defined for the editor will apply for blocks within widgets as this will be the rendered frontend with most setups.

**Comment by oxyc** [comment]
I looked at a fix by simply adding the styles to blockEditorSettings in `lib/widgets-page.php` like [`edit-form-blocks.php`](https://github.com/WordPress/WordPress/blob/5.2.2/wp-admin/edit-form-blocks.php#L184:L203) does but apparently the settings get filtered out before getting to https://github.com/WordPress/gutenberg/blob/b4c7054da14d2b4660a96d95998702fe599f316b/packages/editor/src/components/provider/index.js#L119

How will this work when there are multiple editor instances though?

**Comment by youknowriad** [comment]
That's on purpose. This is still an experimental area but the thinking is that themes might have sidebards and widgets areas style requirements that are different from the "content" (which is currently loaded in the editor).

So it might now make sense to load the editor styles without any change in the widgets screen.

**Comment by oxyc** [comment]
Right, currently it feels broken when any user defined block styles are available to choose but not actually styled–some styles can be quite major too. Using Advanced Custom Fields I've even swapped out the php template of the block depending on which style is selected.

I understand this is a work in progress so I'm justing giving my point of view.

**Comment by BenceSzalai** [comment]
It is still a rather odd thing considering that there's a dedicated `add_editor_style()` function, for which widget editor was apparently purposefully excluded, but there's no `add_widget_editor_style()` or similar call.

Or since I'd consider both to be an "editor" maybe a second optional argument, that defines where to load it, e.g.
```php
function add_editor_style( $stylesheet = 'editor-style.css', $where = 'content' /* or 'widgets' */ ) { /* ... */ }
```

What I mean by this it is strange that someone was thinking about it, decided the styling needs can be different for the two areas (valid), so handle the content editor and the widget editor separately (sure), but actually not add a way to style the widget editor (why?).

Also I know it's possible to simply use `'admin_enqueue_scripts'` to load styles for the widget editor. Except that the `add_editor_style()` function either loads the editor style in an `iframe` preventing style leeks from the editor to the admin UI or it preprocesses the whole stylesheet and narrows the scope of each selector to under `.editor-styles-wrapper`.

Now if we want to use the same stylesheet in the widget area, we need to handle the scope narrowing ourselves...

UPDATE: Meanwhile I've figured that calling `add_editor_style()` on an earlier hook, like `amin_init` will load the styles in the widget editor.
Right now the only reason the styles are not loaded into the widget editor is that in `wp-admin/widgets-form-blocks.php` the editor config is generated before (line 26: `$editor_settings = get_block_editor_settings(`) the `enqueue_block_editor_assets` action (line 65).

So to work that around one can do e.g.:
```php
add_action('admin_init', 'cb_enqueue_widget_editor_styles');
function cb_enqueue_widget_editor_styles() {
	if ( $GLOBALS['pagenow'] === 'widgets.php' ) {
		add_editor_style('path/to/widget_editor_style.css');
	}
}
```
