### ISSUE TITLE
When using :frst-letter style, the cursor gets moved behind the first character

### ISSUE THREAD

**Issue by ddryo** [WordPress/gutenberg#16995]
![bug](https://user-images.githubusercontent.com/31400297/62818751-84d3de00-bb86-11e9-8aef-6362cc7e6b77.gif)

**Comment by nerrad** [comment]
Hi there @ddryo,

Thanks for posting your issue here in the Gutenberg Repository.

While your screenshot may help illustrate what it happening, there's still not really enough detail here to take any action.

Can you please clarify:

- Does this happen in every browser?
- Please spell out the exact steps one would take to reproduce this.
- Is this happening with Gutenberg plugin active?  If so, what version?
- What version of WordPress are you using?
- Do you have any plugins or themes active that interact with Gutenberg?

**Comment by ellatrix** [comment]
`:frist-letter` + `contenteditable` is buggy across different browsers. Unfortunately, there's not much we can do. Gutenberg also has drop caps for paragraphs, but we had to disable them when editing the paragraph.
