### ISSUE TITLE
Inserter: Remove double borders from blocks that have child blocks

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#17068]
In the block Inserter, parent blocks that have child blocks are identified by a double border.

![Jetpack form block with children](https://user-images.githubusercontent.com/617986/63178571-2cc22f00-bfff-11e9-8bae-6412f8650912.png)

I don't believe this is necessary to communicate to the user. In fact, I'd argue this causes more confusion than help. 

After discussions with @jasmussen, @melchoyce, @sarahmonster, and a few others, we believed removing the double borders was the better way forward.

**Comment by ZebulanStanphill** [comment]
Yeah, the double borders almost makes it look like the listing is for a collection of block types, rather than a single block type. It's also weird that blocks like Columns don't use this double border. Indeed, the fact that a block uses child blocks is an implementation detail rather than something that the user needs to know about when choosing a block to insert.

**Comment by jasmussen** [comment]
For historical context, we added this border to indicate that it is a child block that can only be surfaced in the block library, if you already have its parent block focused. However aside from not being clear from the design itself, in practice this also hasn't been necessary.
