### ISSUE TITLE
Add Slot/Fill in BlockSwitcher

### ISSUE THREAD

**Issue by HardeepAsrani** [WordPress/gutenberg#17114]
It'd be great to have a slot/fill here so we could extend blocks in more ways. My particular use case here is to add our custom Block Styles component, that we use as our Block Styles are more than just CSS class change. Apart from that, I can see it being used for more things so make this part available for others to use?

If yes then I can try to do it as see how Slot/Fill work.

What do you think?

<img width="538" alt="Screen Shot 2019-08-21 at 1 57 16 am" src="https://user-images.githubusercontent.com/2649903/63381855-2b09ba00-c3b7-11e9-919c-127b598b7b59.png">

**Comment by draganescu** [comment]
cc @youknowriad how do we make decisions on where to place new slots for plugins?

**Comment by youknowriad** [comment]
Thanks for the suggestion here.

Unfortunately I disagree here because I don't think we should be thinking extension points based on "placement/position" of things. These break too often and would prevent us from iterating the UI without breaking changes.

I'd encourage you to try to think in terms of use-cases, what would you use this slot/fill for and if we find a pattern in the use-cases, we can add a semantic API that can adapt to any UI.

Thanks.
