### ISSUE TITLE
DatePicker styling issue (Gutenberg 6.3)

### ISSUE THREAD

**Issue by simonhammes** [WordPress/gutenberg#17129]
**Describe the bug**
The DatePicker component seems to have a styling issue in Gutenberg 6.3: the weekdays are somehow wrapped into a second line, which leads to the first row of days being **unselectable**. In the default Gutenberg version rolled out with WordPress 5.2.2, this did not happen.

**Code**
``` jsx
<DatePicker
    currentDate={ props.attributes.date }
    onChange={ date => props.setAttributes( { date: date } ) }
/>
```

**Screenshots**
![Screenshot_2019-08-21 Edit Page ‹ Mein Blog — WordPress(1)](https://user-images.githubusercontent.com/10352679/63453108-3527c900-c448-11e9-8b9a-1023fa9b303c.png)

**Desktop**
 - OS: Windows
 - Browser Firefox 68 and Chrome 76

**Comment by talldan** [comment]
@simonhammes Just to double-check, is this an issue you've noticed while implementing `DatePicker` component?

Looking at the `DatePicker` in the Status & Visibility panel in the sidebar in Gutenberg it seems fine.

**Comment by simonhammes** [comment]
> @simonhammes Just to double-check, is this an issue you've noticed while implementing `DatePicker` component?

Yes

**Comment by sarahmonster** [comment]
Sounds like this is an issue primarily related to the `@wordpress/components` _UI component_ itself, rather than the save component. (If `[Component] Saving` means what I assume it does here.)

It's likely that there's some additional code used to wrap the Datepicker as used in the editor that prevents this issue from showing up in Gutenberg itself. We should see about shifting that code to the component itself, so that the component is more portable and usable by third-party applications.

**Comment by simonhammes** [comment]
I did some more research on this issue and it seems like I have figured out one aspect of the problem:

When the datepicker is used outside of the sidebar/InspectorControls, the `ul .DayPicker_weekHeader_ul` element inherits the padding property from the `.editor-styles-wrapper ul` class. This overwrites the padding rules set in the `.DayPicker_weekHeader_ul` class. Disabling the inheritance in Chrome DevTools solves at least part of the problem: the styling seems fine, but the days themselves are still not all clickable.

**Comment by sarahmonster** [comment]
@simonhammes would you be interested in submitting a PR with your solution? We can help review and test it! 😄

**Comment by simonhammes** [comment]
@sarahmonster Unfortunately, I don't have a local setup ready to submit pull requests. I'm sorry :/
Maybe someone else can chime in and see if my suggested approach fixes the issue completely.

**Comment by sarahmonster** [comment]
No worries! If you'd be interested in contributing, instructions for how to get started are here: https://github.com/WordPress/gutenberg/blob/master/docs/contributors/getting-started.md 

There are also lots of people in [Slack](https://make.wordpress.org/chat/) who can help if you have any issues getting up and running. 

In the meantime, I'll add a "needs dev" label here, but I'm keeping the "needs testing" label as well, since it would be helpful to confirm this issue appears with all implementations of the component outside of the Gutenberg editor.

**Comment by glendaviesnz** [comment]
I have added a potential fix for this at https://github.com/WordPress/gutenberg/pull/18856
