### ISSUE TITLE
Cannot set an ID to blocks

### ISSUE THREAD

**Issue by Tropicalista** [WordPress/gutenberg#17224]
**Describe the bug**
In some cases is useful to add an ID to an element. This is impossible on gutenberg.
Some blocks doesn't have the possibility to edit html, others give the "unexpected or invalid content" if I try to add an id.

**To reproduce**
1. Create a paragraph block
2. Edit as html
3. Add id="cta"
4. See error unexpected or invalid content

**Expected behavior**
html id should be an option if I want to use an advanced editor.
Adding an id option in block panel advanced settings should be considered

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome

**Smartphone (please complete the following information):**
 - Version 76.0.3809.132

**Comment by talldan** [comment]
Hi @Tropicalista Thanks for creating the issue.

> html id should be an option if I want to use an advanced editor.

Do you mind providing some more information on why you need an id for this instead of a class name?

Both the Group Block (a new block available in the plugin and due to be released in WP 5.3) and the Heading Block support adding ids via the 'Anchor' setting in the Advanced section. The Group block can be used to wrap any other block(s), so that might solve your issue.

I would mention that this feature is really for adding links to sections of posts.

**Comment by Tropicalista** [comment]
The use case is to create a scroll down to section menu. 

I wasn't aware the group block have this feature. So this solves my problem. 

Thanks

**Comment by nickasd** [comment]
This still is an issue today. I need to set the ID of a link so that I can change its text from JavaScript. Setting both `id` or `onclick` cause an "unexpected or invalid content" error.

**Comment by Tropicalista** [comment]
Nowaday I think you can set this using [WP_HTML_Tag_Processor](https://developer.wordpress.org/reference/classes/wp_html_tag_processor/).

**Comment by nickasd** [comment]
I'm not sure how I'd have to use that. Isn't that all PHP code? I was hoping I could change the ID from within the Wordpress page editor, without having to write my own plugin. Perhaps I'd have to use a raw HTML block for this?
