### ISSUE TITLE
Hover state of Top Toolbar buttons do not match

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#17337]
**Describe the bug**
The hover state of the Top Toolbar items do not match between the "Options" button on the far right, and the 5 buttons on the far left.

**To reproduce**
1. Hover over the "Block navigation" button in the Top Toolbar.
2. Observe the hover state.
3. Hover over the "More tools and options" button in the Top Toolbar.
4. Observe that its hover state is different.

**Expected behavior**
I expected the hover state of the "More tools and options" button to match that of the other buttons on the left side.

**Screenshots**

**Block navigation button** (hovered)

![Screen Shot 2019-09-04 at 4 27 21 PM](https://user-images.githubusercontent.com/617986/64300361-505b0400-cf31-11e9-9565-f2033e69b4e4.png)

**More tools and options button** (hovered)

![Screen Shot 2019-09-04 at 4 27 06 PM](https://user-images.githubusercontent.com/617986/64300379-5fda4d00-cf31-11e9-95c2-dc66f9845eb4.png)

**Desktop (please complete the following information):**
 - OSX
 - Firefox 68.0.2
 - Gutenberg 6.4

**Comment by Seniru** [comment]
Seems no problems with the mobile phones

**Comment by sarahmonster** [comment]
💯 to normalising these hover patterns throughout the interface. There are actually a number of different hover styles that happen across the top toolbar:

![2019-09-16 17 36 05](https://user-images.githubusercontent.com/376315/64976201-a07a8480-d8a8-11e9-9a6a-867dc667c267.gif)

From left to right, I'm seeing:
1. Soft border + slight depth created by a box-shadow:
![2019-09-16 17 39 58](https://user-images.githubusercontent.com/376315/64976481-4af2a780-d8a9-11e9-9f2f-eb53799139f3.gif)

2. Slide up/down to a different icon entirely:
![2019-09-16 17 40 12](https://user-images.githubusercontent.com/376315/64976488-4f1ec500-d8a9-11e9-8b1d-c55dbcbd7520.gif)
This interaction seems to be limited to the transform menu alone—it would be interesting to test whether this interaction provides valuable information for users, since it's a rather aggressive animation.

3. Hard border, no shadow:
![2019-09-16 17 40 28](https://user-images.githubusercontent.com/376315/64976496-5514a600-d8a9-11e9-9eac-75a6361487d2.gif)


Interestingly, we also seem to use different patterns for selected hovers. In some cases, they'll use the hard border:
![2019-09-16 17 42 43](https://user-images.githubusercontent.com/376315/64976562-783f5580-d8a9-11e9-82c2-b71a284bc5b4.gif)


But other selected items won't change at all to indicate a hover state:
![2019-09-16 17 40 48](https://user-images.githubusercontent.com/376315/64976529-6a89d000-d8a9-11e9-9bed-29c0076c7341.gif)

Switching to a single, unified hover state for these interactions seems like it would be an easy win in terms of reducing some code inefficiencies and creating a more consistent and understandable user interface.

**Comment by Seniru** [comment]
@sarahmonster the effect with the settings, preview and publish button are OK  (as they are for entirely  a different  purpose). But I agree with you with the other parts
