### ISSUE TITLE
Bug: Open link in new tab removed when saving draft

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#17334]
**Describe the bug**
As I was adjusting the Core Editor meeting notes in Gutenberg in WP Core. I noticed after adjusting between 20-30 links to open in a new tab that saving a draft and then previewing and then going back to check the links again at the open in new tab has disappeared.

Here is what I experienced:
![Open-link-new-tab-gone](https://user-images.githubusercontent.com/5323259/64285833-a2654f00-cf5c-11e9-8478-59b7a03e35c5.gif)

**To reproduce**
1. Login to WP org and locate my core editor meeting draft.
2. Add some links that opens in a new tab. 
3. Click Save Draft a couple of times.
4. Go back and check the links.
5. See if the links have removed open in new tab.

**Expected behavior**
I am expecting open in new tab to remain after I have selected it.

Btw
Another issue.
Add a link then open drop down to open in tab. See the link disappear.
As one has to add a link then click enter to create the link. Then open the link drop down to open link in new tab.

**Comment by talldan** [comment]
Confirmed. I think the link does still open in a new tab, but the option doesn't appear toggled correctly.

In my testing, saving the post wasn't even required. As soon as you click off of the link and then click back onto it to check the setting the option is toggled off.

**Comment by aduth** [comment]
@talldan When you reproduce this, are you first clicking the Edit (pencil) button in the link dialog before toggling the option? As I explored at https://github.com/WordPress/gutenberg/issues/19365#issuecomment-574817370 (similar/duplicate issue), this may have been an intentional decision that the toggle change only take effect when "Apply" is clicked in the dialog.

But based on the screencast in the original report, I see that this reset is happening even without pressing that Edit button.

@paaljoachim To try to narrow down whether this might be an issue with Make/Core blogs (or the version of Gutenberg it is running), can you confirm whether you are able to reproduce this on any other sites?

**Comment by paaljoachim** [comment]
**Retesting.**
Create a new post.
Add a link. Make it open in a new tab.
Save draft.
Preview.
Go back to edit.
Recheck to see if the open in a new tab is still active.

The opne in new tab is still active. As it was earlier not.
@aduth Andrew I believe we can close this issue as it has now been taken care of.

**Comment by aduth** [comment]
Thanks for re-testing @paaljoachim ! Let's close this, but I'll keep open #19365 as a tracker for the user experience difficulty surrounding differences in how the toggle behaves when clicking the "Edit" button in the link dialog.
