### ISSUE TITLE
Trouble using the @wordpress/media-utils package 

### ISSUE THREAD

**Issue by metalandcoffee** [WordPress/gutenberg#17347]
I checked out the support forums and concluded that this is still the best place to get help since I don't think many people are trying to use the `@wordpress/media-utils` package in the context I'd like to.

I created a custom settings page in the WordPress admin and I'd like to utilize this package to render a button to select media from the WordPress Media library. Here is how my code looks like. 

```
import React from 'react';
import ReactDOM from 'react-dom';
import { MediaUpload } from '@wordpress/media-utils';



const element = ( <MediaUpload /> );

ReactDOM.render(
  element,
  document.getElementById('my-button')
);

```

The code is super simple at this point because I'm just trying to take baby steps. But I see the following error in the browser console.

![image](https://user-images.githubusercontent.com/20868511/64345414-52b76f80-cfbe-11e9-9d04-105e227e7105.png)

I'm not sure how to get passed this error. Also, if you can offer some guidance on what I'm trying to achieve, that'd be great!

**Comment by talldan** [comment]
@metalandcoffee It looks like you're on the right track.

When using a `MediaUpload` component there are two props that are required, `onSelect` and `render`. `onSelect` handles what happens when some media is selected and `render` is used to render the button that opens the media upload dialog:

```
<MediaUpload
  onSelect={ ( media ) => { // do something with the media in this function } }
  render={ ( { open } ) => (
    // render a button that opens the media upload dialog
    <Button
      label={ __( 'Edit file' ) }
      onClick={ open }
      icon="edit"
    />
  ) }
/>
```

Those props are documented in this file:
https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/media-upload/README.md#props

Hopefully that solves the issue.
