### ISSUE TITLE
Handle unrecognized blocks without modifying their markup

### ISSUE THREAD

**Issue by nylen** [WordPress/gutenberg#1735]
While developing a demo plugin for #1619 and renaming blocks as their desired implementation becomes more clear, the user experience of blocks that are no longer recognized is quite bad.  They are turned into `core/freeform` blocks on saving, without any indication of what is going on.

We need to find a way to show in the UI that an "unrecognized" block was detected, and avoid modifying it.

**Comment by iseulde** [comment]
See also #1394, which also helps avoiding modifications and adding classes.

**Comment by dmsnell** [comment]
Also see #1175 for some additional context to this problem. That issue wasn't intended on turning into a discussion about using `post_content` but rather as a way to address the lifecycle of the post before, during, and after edit sessions.

The fact that we forget about the document structure when we save could be seen as a positive and negative at the same time I think. The worst bit is what you point out: we are way to jumpy on turning things into `freeform` blocks.

Instead of this behavior I would love to "preserve the broken structure" and give the author the choice _when the author decides to edit it_. That means, for the sake of rendering the post in the editor we can treat it as if it were a freeform block and maybe even indicate that it's broken (some kind of graying? a warning indicator?).

Once we enter into that block to edit it we can present the choice: "We had a problem determining how this block should be edited…(a) maybe there is a plugin missing to handle the `pizza/margherita` block - [open the repository]…(b) the recorded format differs from our expectations - [manually fix and see examples]… (c) an unknown problem occurred when reading it - [undo to latest known working state]… (d) go ahead and edit and lose the rich information encoded in the block - [edit at own risk as freeform]"

the problem extends beyond block type but also to attributes. for example, if we leave out the quotes on the JSON attributes then the whole set of attributes will be wiped out.

**Comment by aduth** [comment]
Some effort toward this goal at #1929

**Comment by nylen** [comment]
The same mechanism as #1929 can work here, but it's not working yet.  To verify, create a post with this content:

```html
<!-- wp:core/not-implemented-yet /-->

<!-- wp:core/not-implemented-yet -->
abc
<!-- /wp:core/not-implemented-yet -->
```

Edit it in Gutenberg, and see that the empty block is removed and the other one changes to a `freeform` block:

```html
<!-- wp:core/freeform -->
abc
<!-- /wp:core/freeform -->
```

(This also happens without the post being marked as dirty, which seems less than ideal but may be a separate issue.)

**Comment by mtias** [comment]
Related #2126.
