### ISSUE TITLE
Cover Block: video doesn't start on iOS

### ISSUE THREAD

**Issue by benoitchantre** [WordPress/gutenberg#17479]
**Describe the bug**
When you add a cover block containing a video, the video doesn't start on iOS.

**Expected behavior**
The video should start.

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 12.4.1
 - Browser: Safari

**Additional context**
- Gutenberg 6.5

**Solution**
Add the `playsinline=""` attribute to the video tag.

**Comment by JanZimmer** [comment]
+1

**Comment by marcuswisecaesar** [comment]
+1 

2504115-zen

**Comment by separatelyunited** [comment]
+1 to this.

I found that the video didn't play on Google Chrome on iOs (using xs & 8+) on Safari or Google Chrome. On Android (using Samsung Note 9), the video started on Chrome and then froze; with Microsoft Edge the blurry video image didn't even load only a placeholder box.

I expected that if the auto-play video isn't supported or doesn't start on mobile browsers that the video thumbnail would be what shows (similar to when autoplay is disabled on mobile for other video blocks). Or that a static image could be chosen as a fall back similar to how the Media header for Twentyseventeen is set up.


Missing video on Edge:
![Screenshot_20200113-233337_Edge](https://user-images.githubusercontent.com/30807174/72538045-c60d9f80-3842-11ea-97af-929c9630b707.jpg)

Video started then froze on Chrome using Android:
![Screenshot_20200113-233623_Chrome](https://user-images.githubusercontent.com/30807174/72538307-416f5100-3843-11ea-8c96-6a845239a1f5.jpg)

Not started at all on iOs:
![IMG_8374](https://user-images.githubusercontent.com/30807174/72538471-85faec80-3843-11ea-9f9a-03038bf1d11d.PNG)

**Comment by khristiansnyder** [comment]
+1
Encountered this issue today as well.

**Comment by eamcgill90** [comment]
Reported here: 19496236-hc

**Comment by benchilcote** [comment]
I found this to be a suitable workaround:
https://wordpress.org/plugins/advanced-backgrounds/

**Comment by pburke** [comment]
Workaround for anyone looking:

```php
/**
 * Filter Cover block output to add "playsinline" attribute on videos
 */
add_filter('render_block', function ($block_content, $block) {
    if ('core/cover' !== $block['blockName']) {
        return $block_content;
    }

    return str_replace('autoplay muted loop', 'autoplay muted loop playsinline', $block_content);
}, 10, 2);
```

**Comment by openfist** [comment]
reporting this issue as well
#2819740-zen

**Comment by donalirl** [comment]
I came across this too. Video backgrounds do not have full mobile browser support. It would be helpful to at least be able to set a fallback image for when the video doesn't play, as per #18962

**Comment by jasmussen** [comment]
[Mobile Safari has a few heuristics built in](https://webkit.org/blog/6784/new-video-policies-for-ios/) for when it allows autoplay on mobile, for example it blocks playback if the device is in "low power mode".

The heuristics for allowing mobile autoplay are also outlined there:

- `<video>` elements will be allowed to autoplay without a user gesture if their source media contains no audio tracks.
- `<video muted>` elements will also be allowed to autoplay without a user gesture.
- `<video autoplay>` elements will only begin playing when visible on-screen such as when they are scrolled into the viewport, made visible through CSS, and inserted into the DOM.
- `<video autoplay>` elements will pause if they become non-visible, such as by being scrolled out of the viewport.

The document also notes the behavior of `playsinline`:

> On iPhone, `<video playsinline>` elements will now be allowed to play inline, and will not automatically enter fullscreen mode when playback begins.
> `<video>` elements without playsinline attributes will continue to require fullscreen mode for playback on iPhone.
> When exiting fullscreen with a pinch gesture, `<video>` elements without playsinline will continue to play inline.

So it seems like `playsinline` is necessary because otherwise the video will require fullscreen to be played, and that happens only if you tap the video. We already add `muted`. So the following markup should work:

```
<video autoplay muted playsinline>
  <source src="video.mp4" type="video/mp4" />
</video>
```
