### ISSUE TITLE
Block style preview is too small to notice differences

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#17620]
### Problem

If I create a custom block style for the paragraph block, and it changes the font color from black to grey, italicizes the text, changes the size by a few points, or other moderate visual changes, it's nearly impossible to tell that from the preview, because it's so tiny.

<img width="290" alt="Screen Shot 2019-09-26 at 1 16 03 PM" src="https://user-images.githubusercontent.com/484068/65721881-d285a680-e05f-11e9-8bd0-430e16a3d12a.png">

A similar problem may occur with other blocks, but so far Paragraph is the one I've noticed it with.

### Proposed Solution

The preview could be zoomed-in, maybe?

**Comment by GlennMartin1** [comment]
Related: https://github.com/WordPress/gutenberg/issues/17608

**Comment by mapk** [comment]
As noted in the other issue from @karmatosed: 

> I thought there was an issue for this and if there is one please close this (I wasn't able to find it). The style thumbnails for the separators are incredibly subtle, so much I couldn't see them.
![65684882-9a2e9a00-e058-11e9-9470-05a70d907ae4](https://user-images.githubusercontent.com/617986/66415602-cf1fe280-e9b0-11e9-919d-306ee7eba7f9.png)

**Comment by richtabor** [comment]
We discussed this today in the [Gutenberg Triage Meeting](https://wordpress.slack.com/archives/C02S78ZAL/p1570552965193000) (Slack link) and the idea of having a way for blocks to opt-out of the scaling of style variation previews came up. 

The current scaling system works well with larger content, but for other blocks such as this, it doesn’t work. In CoBlocks we've actually overridden the style variation scaling on certain blocks so that they would be more visible. 

It'd be interesting to explore adding this capability (perhaps within `supports` of the block registration) to opt out of the scaling functionality.

**Comment by iandunn** [comment]
It looks like this can also be impacted by the theme. I have a custom block that looks normal in TwentyTwenty, but very small in TwentyFifteen.

**Comment by jordesign** [comment]
Closing this issue as the way previews of style variations for blocks is now handled differently.
