### ISSUE TITLE
Definition for rule '@wordpress/no-unused-vars-before-return' was not found

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#17635]
**Describe the bug**
Extending eslint with `plugin:@wordpress/eslint-plugin/react` results in lint error:
````
Definition for rule '@wordpress/no-unused-vars-before-return' was not found  @wordpress/no-unused-vars-before-return
````

**To reproduce**
1. Extend `.eslintrc.js`:
```js
  'extends': [
    'plugin:@wordpress/eslint-plugin/react',
    'eslint:recommended'
  ],
````
2. Run eslint.

**Expected behavior**
All rule definitions are found and lint runs correctly.

**Related**
https://developer.wordpress.org/block-editor/packages/packages-eslint-plugin/#rulesets

**Comment by aduth** [comment]
There was a missing reference to the plugin itself, so it could not resolve the rule.

A fix is proposed at #18457 

In the meantime, I believe a workaround could be to include your own explicit reference to the WordPress ESLint plugin, so that the custom rules are made available for referencing.

In your `.eslintrc.js`:

```
plugins: [ '@wordpress' ],
```
