### ISSUE TITLE
Block disapear when clicking on a link (anchor, <a>) with no href 

### ISSUE THREAD

**Issue by nicpelletier** [WordPress/gutenberg#17657]
**Describe the bug**
In Gutenberg 6.5.
Shows this error in the console :
react-dom.min.b694e242.js:103 TypeError: Cannot read property 'trim' of undefined

**To reproduce**
1. Copy text from a source where there is a <a> tag with no href
or
create a link with no href when editing a block in HTML mode
2. In visual mode, click on the link or drag over it (like when you want to select text containing a anchor with no href). 
3. Oups, block is gone!

**Expected behavior**
The pop-up to enter the adress should show up empty

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 77

Thank you!

**Comment by glendaviesnz** [comment]
Have tested this and it is easy to replicate on latest master using the steps outlined above.

The problem is that https://github.com/WordPress/gutenberg/blob/master/packages/url/src/index.js#L362 doesn't check for a null value being passed in. 

It would probably make sense to check here that url is defined before running .trim, but none of the other methods in this file check the params so maybe it is a deliberate decision to leave checking to the callers. Also, changing this method would require updating the related index.d.ts to allow undefined or false as an optional return type ... so the quicker/easier fix of checking at the caller end is the following PR - https://github.com/WordPress/gutenberg/pull/17928
