### ISSUE TITLE
How do I use the block.registerBlockType filter on a block I made?

### ISSUE THREAD

**Issue by Alexius08** [WordPress/gutenberg#17670]
All sample code I could find so far of the various block filters within the documentation use the core blocks, but I want to make them work on blocks I made. So, I made a block named "test/testblock", and I also made the following filter:

````
wp.hooks.addFilter(
	'blocks.registerBlockType',
	'test/test-block-filter',
	(settings, name) => {
		console.log(`block name: ${name}`);
		return settings;
	}
);
````

Every time I load the editor, I see a list on the console that includes blocks from core and core-embed but not the block I made. Although I can still insert test/testblock into posts, I can't use the filter on it since it can't be detected at all (although filters using editor.BlockEdit works fine with it). I've declared the block in Javascript using registerBlockType, so I have no idea of what other declarations or anything else I have to do to be able to use the filter on it.

**Comment by swissspidy** [comment]
Please note that for general help requests, posting in the support forum at https://wordpress.org/support/forum/how-to-and-troubleshooting/ is usually preferred.

Technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/. You may also ask for technical support at https://wordpress.stackexchange.com/.

The reason is that GitHub is the place where development happens, and these other resources are much better for getting help as they are tailored for that purpose.

----

That being said, it looks like you are calling this filter too late. It needs to run _before_ you register your custom blocks.

So you'd need to do something like this:

```js
wp.hooks.addFilter(
	'blocks.registerBlockType',
	'test/test-block-filter',
	(settings, name) => {
		console.log(`block name: ${name}`);
		return settings;
	}
);

wp.blocks.registerBlockType(...)
```
