### ISSUE TITLE
Image Block: Option to disable the caption

### ISSUE THREAD

**Issue by CreativeDive** [WordPress/gutenberg#17678]
Hey, when I use the image block, the caption is always visible. What can I do to conditionally disable the caption?

**Comment by talldan** [comment]
@CreativeDive The caption should only be visible if it has text content. When it's empty there shouldn't be a caption element for the block.

Could you provide some more information on what you're seeing and what you expect to happen?

**Comment by CreativeDive** [comment]
@talldan I can see, we can manually delete the caption text content for the image block. I think this solves that. We can close this issue :-)

**Comment by talldan** [comment]
Awesome, I'll close it 👍

**Comment by sproutient** [comment]
Sometime, I just want to insert just image, I don't want users to see the caption option while inserting the block, so something like 
[ 'core/image', { caption:false } ] would be nice. (when using in template for inner blocks).

**Comment by davidfregoli** [comment]
+1 for @sproutient, blocks need more options in order to make streamlined and non confusing templates for users

**Comment by FriendlyWP** [comment]
+1 @talldan Since captions are associated with the image in the Media Library, there should be a way to show/hide them in different contexts when they're inserted via the block editor. For instance on a site I'm working on now there are images in an image gallery where captions are shown (correctly) but if editors insert those same images elsewhere and *don't* want captions to show, the only option is to delete the caption itself, which also deletes it from the gallery.

**Comment by talldan** [comment]
> Sometime, I just want to insert just image, I don't want users to see the caption option while inserting the block, so something like
[ 'core/image', { caption:false } ] would be nice. (when using in template for inner blocks).

@sproutient @davidfregoli  I'd recommend submitting a new issue for this. The issue here is closed as the reporter's problem was solved and so your comments won't be very visible.

----

> For instance on a site I'm working on now there are images in an image gallery where captions are shown (correctly) but if editors insert those same images elsewhere and don't want captions to show, the only option is to delete the caption itself, which also deletes it from the gallery.

@FriendlyWP Would you be able to provide some more detail, as I don't quite follow. What you describe should only happen if you're using a reusable block. Changes to one gallery block shouldn't affect another (unless you're using a plugin that does this).

I just tested and it's possible to delete the caption text from a block, but the 'default' caption text in the media library remains and other blocks aren't affected.

**Comment by newoceans** [comment]
Edit: forget about my comment below. I removed the captions by clicking on the 'Media Library' link of the gallery; hence I removed them from the media that is: the images. Just discovered I better double click on the caption itself and remove it. This way it gets removed from the images in the gallery, but not the images in the library. But might be confusing for other users too...

---

Regarding @FriendlyWP comment: I prefer to manage image captions (as well as alt texts and descriptions) through the media library. When I insert a gallery with a few images, every image gets the caption at the front end. When deleting the individual captions, they disappear from the gallery but also from the image attributes in the media library.

Looking for a way to manage captions through the library, but turn them on/off separately when using the image on a page.
