### ISSUE TITLE
With Gutenberg 6.6, the pinned plugins menu icons are not scaled properly

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#17719]
Try installing the dropit plugin. In previous versions the icon was showing properly, it Gutenberg 6.6, the icons are not scaled down to the button height.

<img width="632" alt="Capture d’écran 2019-10-02 à 3 55 45 PM" src="https://user-images.githubusercontent.com/272444/66055406-68707400-e52d-11e9-8320-6ffdb87dd86a.png">

Probably due to the buttons refactoring cc @jasmussen @talldan

**Comment by youknowriad** [comment]
Same in the more menu 
<img width="273" alt="Capture d’écran 2019-10-02 à 3 59 51 PM" src="https://user-images.githubusercontent.com/272444/66055603-b4231d80-e52d-11e9-8487-ce2d76cbfa0a.png">

**Comment by youknowriad** [comment]
So I noticed this as soon as I updated my blog to 6.6 and I'm pretty sure I didn't touch dropit in the meantime, I can debug deeper later though.

**Comment by youknowriad** [comment]
I suspect buttons were flex aligned which also affects the size of their children and it's not the case anymore.

**Comment by jasmussen** [comment]
Oh I know what it is now.

On 5.2 without plugin, the markup is this:

```
<span class="dropit-sidebar-icon is-small color-giphy"><svg width="115px" height="159px" viewBox="0 0 115 159"> ... </svg></span>
```

On 5.2 with plugin 6.6 enabled, the markup is this:

```
<span class="dropit-sidebar-icon is-24 color-giphy"><svg width="115px" height="159px" viewBox="0 0 115 159"> ... </svg></span>
```

So at some point, `is-small` became replaced by `is-24`.

**Comment by etoledom** [comment]
@youknowriad - I've been checking this out following the changes on https://github.com/WordPress/gutenberg/pull/17228.

Previous to this change:
https://github.com/WordPress/gutenberg/blob/eb3a82f4354ea18c349b92279d798fdbfa00f8e2/packages/components/src/icon-button/index.js#L58
We were passing down a `Dashicon` if icon was a string, or the icon object directly otherwise.
`{ isString( icon ) ? <Dashicon icon={ icon } ariaPressed={ ariaPressed } /> : icon }`

Now we are always passing the icon (objec or string) to the Icon component, and `Icon` has a default size value of 24.

Probably if we keep this logic and just change Dashicon with Icon, it will work as before:
`{ isString( icon ) ? <Icon icon={ icon } />  : icon }`

A fast test on web and mobile seems to work.
What do you think?

cc @Tug

**Comment by youknowriad** [comment]
I'm not certain that's the issue here. Since that plugin icon is always rendered with ` Icon` anyway (before and after). The icon there is an element not a string.

**Comment by gziolo** [comment]
There is a different margin when the pinned icon is toggled:
![Screen Shot 2019-10-03 at 14 56 10](https://user-images.githubusercontent.com/699132/66128344-f90e8900-e5ed-11e9-8171-6f09d17c8fbf.png)
![Screen Shot 2019-10-03 at 14 56 16](https://user-images.githubusercontent.com/699132/66128345-f90e8900-e5ed-11e9-8849-872dd8ce0e4e.png)

**Comment by etoledom** [comment]
> I'm not certain that's the issue here. Since that plugin icon is always rendered with ` Icon` anyway (before and after). The icon there is an element not a string.

This change do solve the issue with the buttons though. I don't see other possibly change on https://github.com/WordPress/gutenberg/pull/17228 that could have triggered this problem

```javascript
-    <Icon icon={ icon } />
+    { isString( icon ) ? <Icon icon={ icon } />  : icon }
```

Maybe it could at least give some lights?

![Screen Shot 2019-10-03 at 2 56 07 PM](https://user-images.githubusercontent.com/9772967/66128515-3e32bb00-e5ee-11e9-9020-1e64dbea30a6.png)

**Comment by youknowriad** [comment]
ohhh, actually you're right @etoledom let's just restore the "if" then
