### ISSUE TITLE
Adding add_theme_support() disable-custom-colors causing problems

### ISSUE THREAD

**Issue by AlchemyUnited** [WordPress/gutenberg#17715]
**Describe the bug**
I was working with the pullquote block (and have NOT tested this with other blocks - yet). I also added my own editor-color-palette, in case that matters

**To reproduce**
1. Add a pullquote and make it solid
2. Pick a Main color. 
3. Save post / page and view on frontend.
4. Now use add_theme_support()  to disable-custom-colors 
5. Go back to the same post / page and edit the same pullquote
6. Change the main color. 
7. Save and view on frontend. 

For me **both** main classes were in the <figure> tag. That is the original main color (class) was not removed. 

Once I had the dual main colors / classes I also tried using Clear trying to move both / all, and that didn't work either. Not that I expected it to since more than one is not what's expected. 

Note: I was originally using the Classic Editor and then switched over to Gutenberg. Not sure if this matters but someone else I know mentioned they had previous using from from Classic to GB. Probably a none issue. 

Note: there might be something more to the reproduce pattern, I'll update if I find out otherwise. I'm definitely getting the bug. I could be mis-noticing the pattern that creates it. 

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Version  Latest

**Additional context**
- WordPress 5.2.3

**Comment by premitheme** [comment]
I can confirm this issue. It happens when the editor hangs while saving and the "Update" button shows "Updating..." forever...
![Screen Shot 2019-11-22 at 2 29 23 PM](https://user-images.githubusercontent.com/3824596/69428652-6f03b680-0d3a-11ea-8100-c09fbd20e7a1.png)

and after you refresh the page the editor shows this message ...
![Screen Shot 2019-11-22 at 2 29 38 PM](https://user-images.githubusercontent.com/3824596/69426702-804ac400-0d36-11ea-9916-84cb88efad0b.png)

After this happens, the classes of the block don't update correctly especially the ones related to the background color. Whatever background color I try to set, there is a background color class leftover from the previous setting before the hang happened. Therefore, the block never gets the right style since there are two different background color classes applied at the same time. In addition to that `has-background` class is still applied even if I switched to default Pullquote style which has no background (and when I switch again to solid I have 2 `has-background` classes) ...
![Screen Shot 2019-11-22 at 2 15 20 PM](https://user-images.githubusercontent.com/3824596/69426995-31515e80-0d37-11ea-920c-09a1f9f62861.png)

I realized that `has-background` and `has-<whatevercolor>-background-color` classes are now applied to the "Additional classes" input in the Advanced settings panel, which is not the expected behavior. The only way to get rid of this conflict is to manually remove the classes to reset the block to its default state. Then everything works fine again.

It's important to mention that this happens either with a custom color palette or the default color palette.

I'm not sure if this issue happens to any block with background color capability or just the Pullquote block, but my self I faced this with the Pullquote block with solid style.

**To reproduce**
Steps to reproduce the behavior:

* Add a Pullquote and make it solid
* Pick a Main color.
* Save post/page and view on the frontend.
* Repeat "pick a color/save" until you get the editor saving hang.
* refresh the page (click "Reload" if the browser prompted).
* Pick a Main color.
* Save post/page and view on the frontend.
* The background color will never update the block has two BG color classes at the same time.

**Desktop**
* OS: macOS 10.14.6
* Browser Chrome 78.0.3904.97

**Additional context**
* WordPress 5.3

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting. Are you able to reproduce this after you have installed and activated the newest version of Gutenberg that is available through [the Gutenberg plugin](https://wordpress.org/plugins/gutenberg/)?

**Comment by kathrynwp** [comment]
I’m going to go ahead and close out this issue, since there hasn’t been any activity on it in several years.

If anyone feels it should still be looked at, please add a comment and I can take another look. Thanks!
