### ISSUE TITLE
Image inside a column creates unusable dialog box

### ISSUE THREAD

**Issue by EricDu** [WordPress/gutenberg#17721]
Adding an image inside a column in the Gutenberg playground (with the default Align Center) results in a really skinny, unusable box.
![Screen Shot 2019-10-02 at 12 35 19 PM](https://user-images.githubusercontent.com/3483810/66063511-7dd7a500-e511-11e9-958f-61d63cf0fdda.png)

**Comment by youknowriad** [comment]
<img width="1390" alt="Capture d’écran 2020-02-27 à 2 34 36 PM" src="https://user-images.githubusercontent.com/272444/75451496-f29ff580-5970-11ea-8644-95bf4934aa55.png">

In very narrow columns, it can probably still happen but generally speaking this is fixed with the new responsive placeholder designs.
