### ISSUE TITLE
Columns block missing classes

### ISSUE THREAD

**Issue by zkingdesign** [WordPress/gutenberg#17765]
**Describe the bug**
I'm having issues when adding in new column blocks. While before the html looked like this : 
`<div class="wp-block-columns has-3-columns">`

now the front-end is only outputting:
`<div class="wp-block-columns">`

Why is this happening?

**Additional context**
- Gutenberg 6.6

**Comment by youknowriad** [comment]
Hi there and thanks for opening the issue.

This is an intended change though. The idea is that right now the columns can have different widths so relying on the number of columns (that className) to style them might not be a great idea.

We wrote this post that goes through all the theme related changes for WordPress 5.3 https://make.wordpress.org/core/2019/09/27/block-editor-theme-related-updates-in-wordpress-5-3/ 

Thanks.

**Comment by swinggraphics** [comment]
The correct solution to this is to add a class like `has-custom-column-widths` rather than removing the extremely helpful and important classes. Every single workaround runs into the same problem with custom column widths, all of which would be solved by `class="wp-block-columns has-3-columns has-custom-column-widths"`. 😢 This is an issue on literally every site I work on that uses the block editor.
