### ISSUE TITLE
"Open New Tab" toggle on links not getting saved

### ISSUE THREAD

**Issue by mlaetitia** [WordPress/gutenberg#17770]
**Describe the bug**

Since Gutenberg 6.6 (at least) setting a link to "open in a new tab" doesn't "stick". This to say - doesn't get saved

**To reproduce**
1. From a post/page editor, create a paragraph block
2. Add a link
3. Set the link to open in a new tab
4. Click anywhere else
5. Click the link -> settings , the “open in a new tab” will be toggled off

**Expected behavior**

The chosen setting would stay set :)

**Screenshots**

![see screen shot](https://cld.wthms.co/gD6Mzq+)

https://cld.wthms.co/gD6Mzq

**Desktop (please complete the following information):**
 - OS: iOS 
 - Browser Safari, Chrome

**Additional context**
-Tested in a self hosted environment + WordPress.com (simple and business plan).

**Comment by youknowriad** [comment]
cc @ellatrix maybe you have an idea here.

**Comment by glendaviesnz** [comment]
I appears that this might be because opensInNewWindow state is not toggled in InlineLinkUI if the activeAttributes.url and activeAttributes.target props both change - in this case only the url change is reflected in the component state due to getDerivedStateFromProps returning before the opensInNewWindow check is hit

Potential fix for this at https://github.com/WordPress/gutenberg/pull/17794
