### ISSUE TITLE
add indication of sources for citations as translator comments

### ISSUE THREAD

**Issue by pixelverbieger** [WordPress/gutenberg#17810]
**Description**

Working on the translations for 5.3 we (German polyglots) found some difficult passages to translate.

What we (meanwhile) learned that these passages are

    a quote by Matt Mullenweg
    a three line poem by some Japanese poet
    a movie shooting script (Citizen Kane)
    an excerpt of Don Quixote 

It took quite a while for us to figure that out.
(And we're still unsure how to translate these passages appropriately.)

**Problem**

Quotes like Matt's must be translated differently than those of a classic like Don Quixote. (For a classic there might exist "standard" translations which should be used then.)
… and some things like this three line poem just could be replaced by any other (German) three-liner.

The same applies to book or film titles. In some languages, these may differ from the original title.

**Solution**

For future releases I wish there were indication of sources for such citations -> written as translator comments.

===========================
(originally posted on https://core.trac.wordpress.org/ticket/48238 , @ocean90 asked me to create a ticket for this here at GitHub -> done :) )

**Comment by La-Geek** [comment]
I second this. However, knowing the source of such quotations does not mean that we can translate them meaningfully.

As an alternative / suggestion: Either adopt the original quotation in English or use your own national citations.

**Comment by Soean** [comment]
Thanks for the ticket. Same for the verse example. 

**Source**: _A Musical Instrument_ by _Elizabeth Barrett Browning_

https://github.com/WordPress/gutenberg/blob/465c45ea78d0ca8844c376c6b3711c740f8aa83d/packages/block-library/src/verse/index.js#L26-L31

**Comment by tobifjellner** [comment]
If possible, keep a poem in ONE string (it's fully OK to use some kind of placeholder for BR-tags, if you can't allow the tags to be included in the string itself. (Just add a translator not about what's expected). If you break up a haiku into three separate strings, then any attempt to translate it piece by will just become weird. (There is not guarantee that the translator will work on these sub-strings in a logical order).
Also: In some of these cases, rather than translating, we may be talking about localizing/adapting...
Depending on how these sample texts are used, it may turn out better to use a totally different sample text in some locale versions.

**Comment by SergeyBiryukov** [comment]
> If possible, keep a poem in ONE string (it's fully OK to use some kind of placeholder for BR-tags, if you can't allow the tags to be included in the string itself. (Just add a translator note about what's expected).

Just wanted to second that request, this should really be a single string. A placeholder for the `<br>` tags should not be necessary, just passing the string through a `nl2br()`-like function would suffice.

**Comment by aduth** [comment]
This has been corrected for the verse block (#18365) and the code block (#18964).

Can someone clarify if there is a remaining action item here? Or can this issue be closed?

**Comment by tobifjellner** [comment]
Remaining things needed:
1. The line value: `'<p>' + Object(external_this_wp_i18n_["__"])('One of the hardest things to do in technology is disrupt yourself.') + '</p>',` should have a translators comment.
the Citation string "Matt Mullenweg" should be made translatable, since some locales may need to transcribe his name to a different script.

2. The strings in `content: Object(external_this_wp_i18n_["__"])('EXT. XANADU - FAINT DAWN - 1940 (MINIATURE)') + '\n' + Object(external_this_wp_i18n_["__"])('Window, very small in the distance, illuminated.') + '\n' + Object(external_this_wp_i18n_["__"])('All around this is an almost totally black screen. Now, as the camera moves slowly towards the window which is almost a postage stamp in the frame, other forms appear;')` need to be combined, and get a translators comment, which mentions what this is and if it would be OK to replace with something else.

3. A translators comment is needed for `caption: Object(external_this_wp_i18n_["__"])('Mont Blanc appears—still, snowy, and serene.')`

**Comment by aduth** [comment]
Possibly related: #19006 (I'm not too sure whether minification affects core Gutenberg strings extraction the same as it does the plugin)

**Comment by mcsf** [comment]
Replying to https://github.com/WordPress/gutenberg/issues/17810#issuecomment-563013409:

@tobifjellner: I've opened #19048 and would welcome a review. For this to be useful in GlotPress it's still contingent on #19006, but perhaps now the present issue has fulfilled its purpose and can be closed?
