### ISSUE TITLE
Theme support: Consider auto-generating stylesheets for theme's color palettes, font-sizes and gradients

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#17860]
Right now if themes want to provide their own color palette, their own custom font sizes or gradients, they need to provide the stylesheets to apply these to the editor and the frontend.

That stylesheet is always the same though: classNames based on the color names or font size names... and applying the color or the size. 

**Proposal**

To simplify this for theme authors and avoid duplication, consider automatically generating that stylesheet and loading it where appropriate (frontend and editor).

cc @jorgefilipecosta

**Comment by JJJ** [comment]
Can you more clearly define what the problem is you’re proposing a solution for?

Themes _do_ provide style sheets, and there is currently some duplication between editor and theme-side stylings. But also these files shouldn’t be modified directly, so Gutenberg shouldn’t be writing to them.

I’m fuzzy on what simpler means here, what duplication is being removed, and which style sheet is being generated where to help whom.

Are you suggesting that editor styles be derived from theme-side styles? For example, loading the style.css into PHP and parsing it to then automatically regenerate editor styles on the fly?

The issue of class names including colors in them notwithstanding, wouldn’t this introduce a bunch more problems when it comes to versioning these generated style sheets against different versions of Gutenberg/WordPress, and whatever plugins or themes may have added their own theme support for various functionalities?

Are the style sheets that get generated intended for human consumption and interaction? Are you envisioning people taking these generated style sheets and modifying their results?

Are all style sheets really **always** the same?

**Comment by youknowriad** [comment]
After discussions in #18028 Let's postpone this until we find a better approach. The caching issues are real and performance in the frontend is important.
