### ISSUE TITLE
Gutenberg doesn't wrap text

### ISSUE THREAD

**Issue by mchat05** [WordPress/gutenberg#17865]
<img width="847" alt="Screen Shot 2019-10-09 at 10 33 48 AM" src="https://user-images.githubusercontent.com/10283503/66491355-96e7d500-ea80-11e9-9a2c-303d7e868d0d.png">
I have made an image block and had it float right, but the paragraphs below it won't wrap...this leaves a BIG space to the left until the next paragraph block. Please advise: https://curesearch.org/Immunotherapy-in-Children

**Comment by paaljoachim** [comment]
Hi

I added two paragraphs with text. Then added an image. Then added another paragraph with text.
I then changed the alignment of the image to the right. This is what it looks like in the environment I tested in:

![Screen Shot 2020-12-17 at 21 32 11](https://user-images.githubusercontent.com/5323259/102540462-5daceb00-40af-11eb-9361-8be049591086.png)

--------
-
-
-
---------

![Wrap-text-around-image](https://user-images.githubusercontent.com/5323259/102540285-1888b900-40af-11eb-81a5-da62287f47c8.gif)

Local dev site.
Chrome
WordPress 5.6
Theme: Twenty Twenty
Gutenberg plugin 9.5.2


I believe this issue is fixed. If not then let us know and it can be reopened.
Thanks!
