### ISSUE TITLE
Alt shortcuts broken for Internet Explorer 11 and Edge

### ISSUE THREAD

**Issue by rgembalik** [WordPress/gutenberg#17870]
While typing I tend to use AltGr + A to type the Polish ą character. The letter is being inserted but after that, the entire page content is being selected. The same happens in Edge and on IE 11 (but Chrome works ok). Once it happens I cannot type ą letter anymore. 

What's more, I noticed that the CTRL + A shortcut itself works only once. After being used once to select text within a text block it stops being handled by Gutenberg and the next time I press CTRL + A, it simply selects the text on the entire editor.

When it happens it doesn't show any errors in the console (neither during initialization, after editor page is loaded).

I tested it both on Wordpress 5.2.3 and 5.2.2. Switching Language to English with English keyboard layout didn't fix the CTRL+A problem.

- Browsers: IE11 and Edge
- Functionality: Shortcuts CTRL + A and ability to type Polish character ą with ALT GR + A
- System Language: Polish
- Keyboard Layout: Polish (Programmers)

**Comment by KarolNet** [comment]
Hi, are any work being carried out in this area?
I have the same problem :(

**Comment by aduth** [comment]
Can you confirm if this is still an issue in the latest version of WordPress (5.3.x) or the Gutenberg plugin?

I'm having trouble reproducing this, though it's unclear to me if it's because I am using a virtual keyboard instead of a physical one.

Debugging notes for future reference:

- `primary+a` is [registered in `KeyboardShortcutsRegister`](https://github.com/WordPress/gutenberg/blob/3ab37270ac91bec58ac6e137fd1d7d26b7f1b15d/packages/block-editor/src/components/keyboard-shortcuts/index.js#L193-L203)
- The behaviors described in the original report seem to indicate that the "Select All" behavior is being triggered
- `primary+a` should evaluate to `Ctrl+A`, and shouldn't trigger in response to AltGr+A
- Consider also issues in implementation of;
   - [`keycodes.rawShortcut`](https://github.com/WordPress/gutenberg/blob/3ab37270ac91bec58ac6e137fd1d7d26b7f1b15d/packages/keycodes/src/index.js#L137)
   - Upstream [Mousetrap](https://github.com/ccampbell/mousetrap) library

**Comment by rgembalik** [comment]
@aduth Unfortunately, the issue persists on WP 5.3.2. I prepared a test case, which presents some of that behaviour, although it's not always selecting the entire text (I think it still tries to). Please, consider the following test cases. Although I didn't keep the flow the same, they are all beginning with me doing roughly the same thing:
1. Pressing `a` three times, which should result in `aaa`
2. then key down on `Alt GR` (right alt which is equivalent of `LCtrl + LAlt` ) and pressing `a` again three times, which should result in `ąąą` in polish, so I should have `aaaąąą`
3. then I am lifting `Alt GR` and repeating the 1. and 2.
4. after that I am messing with keys a bit
All the above were recorded for chrome, edge and ie (uploaded in that order). The actual result on IE and edge is, that there is only a single letter `ą` and no further `Alt GR + a` presses results in giving me that.
![chrome](https://user-images.githubusercontent.com/2618837/76115018-a5aec580-5fe7-11ea-8a3d-cda349d6b2f5.gif)
![edge](https://user-images.githubusercontent.com/2618837/76115025-aa737980-5fe7-11ea-8918-d24f6ab71334.gif)
![ie11](https://user-images.githubusercontent.com/2618837/76115031-acd5d380-5fe7-11ea-8b51-d96f1b0d5c11.gif)

I believe this might be connected with also system language and/or browser language preferences and not only with the keyboard layout itself.

One of my colleagues reported that this might be connected with the following area of the code:
https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/writing-flow/index.js#L455
and the method implementation:
https://github.com/WordPress/gutenberg/blob/master/packages/keycodes/src/index.js#L230

Unfortunately, I haven't had time to confirm the above claim, so consider it a "raw" hint :)

**Comment by aduth** [comment]
Those code references look like solid leads to me. One specific thing I note about the `isKeyboardEvent` function is that it's not checking modifiers _exclusively_, so it could be passing for `Ctrl` + `Alt` when we really only want it to be firing for `Ctrl` _and no other modifiers_.

**Comment by aduth** [comment]
I started looking at this on Friday, and while the changes necessary to consider modifiers exclusively is rather straight-forward, I'm running into some conflicting reporting from the unit tests.

With the changes:

```diff
diff --git a/packages/keycodes/src/index.js b/packages/keycodes/src/index.js
index 998200bd2..df0170df7 100644
--- a/packages/keycodes/src/index.js
+++ b/packages/keycodes/src/index.js
@@ -12,7 +12,7 @@
 /**
  * External dependencies
  */
-import { get, mapValues, includes, capitalize } from 'lodash';
+import { get, mapValues, includes, capitalize, xor } from 'lodash';
 
 /**
  * WordPress dependencies
@@ -219,6 +219,12 @@ export const shortcutAriaLabel = mapValues( modifiers, ( modifier ) => {
 	};
 } );
 
+function getEventModifiers( event ) {
+	return [ ALT, CTRL, COMMAND, SHIFT ].filter(
+		( key ) => event[ `${ key }Key` ]
+	);
+}
+
 /**
  * An object that contains functions to check if a keyboard event matches a
  * predefined shortcut combination.
@@ -230,8 +236,9 @@ export const shortcutAriaLabel = mapValues( modifiers, ( modifier ) => {
 export const isKeyboardEvent = mapValues( modifiers, ( getModifiers ) => {
 	return ( event, character, _isApple = isAppleOS ) => {
 		const mods = getModifiers( _isApple );
+		const eventMods = getEventModifiers( event );
 
-		if ( ! mods.every( ( key ) => event[ `${ key }Key` ] ) ) {
+		if ( ! xor( mods, eventMods ).length ) {
 			return false;
 		}
```

Tests fail because there are a few tests which apply additional modifiers (in this case, `altKey`):

https://github.com/WordPress/gutenberg/blob/c82094d8389b1756f05d4079ba98e4ee25961502/packages/keycodes/src/test/index.js#L501-L514

But looking closer at the tests, the test implementation seems incorrect, since that's within the bucket of `access` tests:

https://github.com/WordPress/gutenberg/blob/c82094d8389b1756f05d4079ba98e4ee25961502/packages/keycodes/src/test/index.js#L485

So I would expect this line:

https://github.com/WordPress/gutenberg/blob/c82094d8389b1756f05d4079ba98e4ee25961502/packages/keycodes/src/test/index.js#L505

**Comment by aduth** [comment]
I started looking at this on Friday, and while the changes necessary to consider modifiers exclusively is rather straight-forward, I'm running into some conflicting reporting from the unit tests.

With the changes:

```diff
diff --git a/packages/keycodes/src/index.js b/packages/keycodes/src/index.js
index 998200bd2..df0170df7 100644
--- a/packages/keycodes/src/index.js
+++ b/packages/keycodes/src/index.js
@@ -12,7 +12,7 @@
 /**
  * External dependencies
  */
-import { get, mapValues, includes, capitalize } from 'lodash';
+import { get, mapValues, includes, capitalize, xor } from 'lodash';
 
 /**
  * WordPress dependencies
@@ -219,6 +219,12 @@ export const shortcutAriaLabel = mapValues( modifiers, ( modifier ) => {
 	};
 } );
 
+function getEventModifiers( event ) {
+	return [ ALT, CTRL, COMMAND, SHIFT ].filter(
+		( key ) => event[ `${ key }Key` ]
+	);
+}
+
 /**
  * An object that contains functions to check if a keyboard event matches a
  * predefined shortcut combination.
@@ -230,8 +236,9 @@ export const shortcutAriaLabel = mapValues( modifiers, ( modifier ) => {
 export const isKeyboardEvent = mapValues( modifiers, ( getModifiers ) => {
 	return ( event, character, _isApple = isAppleOS ) => {
 		const mods = getModifiers( _isApple );
+		const eventMods = getEventModifiers( event );
 
-		if ( ! mods.every( ( key ) => event[ `${ key }Key` ] ) ) {
+		if ( ! xor( mods, eventMods ).length ) {
 			return false;
 		}
```

Tests fail because there are a few tests which apply additional modifiers (in this case, `altKey`):

https://github.com/WordPress/gutenberg/blob/c82094d8389b1756f05d4079ba98e4ee25961502/packages/keycodes/src/test/index.js#L501-L514

But looking closer at the tests, the test implementation seems incorrect, since that's within the bucket of `access` tests:

https://github.com/WordPress/gutenberg/blob/c82094d8389b1756f05d4079ba98e4ee25961502/packages/keycodes/src/test/index.js#L485

So I would expect this line:

https://github.com/WordPress/gutenberg/blob/c82094d8389b1756f05d4079ba98e4ee25961502/packages/keycodes/src/test/index.js#L505

...should be:

```js
isKeyboardEvent.access( event, undefined, isAppleOSTrue )
```

The problem is: Making that change, even without any changes to `keycodes/src/index.js`, will _also_ fail tests, which leads me to think there's other issues with this implementation already in `master`.

(cc @ellatrix in case any of this rings bells)

**Comment by rgembalik** [comment]
@aduth While the reasoning seems valid to me (bear in mind I have no idea how the keyboard events are working in Guttenberg) it doesn't explain one key difference: why would that behave differently in chrome and in edge/ie11? Just to reiterate: the chrome implementation is valid, it works as expected. If there were some implementational issues on the level of matched modifiers, wouldn't that be the issue everywhere?

**Comment by aduth** [comment]
@rgembalik It's a good question. Maybe the modifier properties are reported differently based on the browser?

One way to test could be to use W3C's Keyboard Event Viewer tool to compare the differences of these key combinations under different browsers:

https://w3c.github.io/uievents/tools/key-event-viewer.html

**Comment by rgembalik** [comment]
Here's how it looks on my chrome and edge (ie11 won't work with key event viewer). I hope print screen is ok, as I have no viable option of exporting it. Bear in mind that both cases have the same keyboard state (num-lock enabled, capslock disabled, scroll-lock disabled).
**chrome:**
![image](https://user-images.githubusercontent.com/2618837/76227835-307a0500-6220-11ea-973f-58611496d71a.png)
**edge:**
![image](https://user-images.githubusercontent.com/2618837/76227876-3ff94e00-6220-11ea-9417-a776de9e7366.png)

**Comment by rgembalik** [comment]
@aduth ⏫  I both cases I typed the first 6 characters of the test sequence from above: `aaaąąą`.

**Comment by aduth** [comment]
Thanks for that. Yeah, definitely see some differences there, notably that Edge (and not Chrome) reports [`altKey: true`](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/altKey) when using <kbd>AltGr</kbd>.

**Comment by aduth** [comment]
I opened #20733 as an improvement to comparing expected modifiers from a keyboard event. I think the issue of browser-specific inconsistencies might warrant some separate logic to normalize the event, but I still sense that #20733 may fix the issue as reported in the initial comment (with <kbd>AltGr</kbd><kbd>a</kbd> triggering "Select All"), since I believe the reason it is triggering the unexpected behavior in Edge is because Ctrl+Alt+A (as seen in https://github.com/WordPress/gutenberg/issues/17870#issuecomment-596590032) would match `wp.keycodes.isKeyboardEvent.primary( event, 'a' )` without the changes in #20733.
