### ISSUE TITLE
Button block with gradient background fails to validate on multisite

### ISSUE THREAD

**Issue by mmtr** [WordPress/gutenberg#17938]
**Describe the bug**
Button blocks set with a gradient background are considered invalid blocks by the editor when loaded on a multisite WordPress install, due to the KSES filters registered on those environments.

<img width="811" alt="Screen Shot 2019-10-14 at 18 14 44" src="https://user-images.githubusercontent.com/1233880/66766497-85526300-eeae-11e9-9994-0c2594a5da02.png">

```
Content generated by `save` function:

<div class="wp-block-button"><a class="wp-block-button__link has-background" style="background:linear-gradient(135deg, rgba(6, 147, 227, 1) 0%, rgb(155, 81, 224) 100%)">test21</a></div>

Content retrieved from post body:

<div class="wp-block-button"><a class="wp-block-button__link has-background" style="background:linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%);">test21</a></div>
```

The only difference between the content generated by the `save` function and the one retrieved from DB are the missing whitespaces on the `style` attribute.

Those whitespaces are removed by the [`wp_kses_hair` function](https://core.trac.wordpress.org/browser/tags/5.2.3/src/wp-includes/kses.php?marks=1223#L1223) which is executed by the [KSES filters triggered when saving the post](https://core.trac.wordpress.org/browser/tags/5.2.3/src/wp-includes/kses.php?marks=1989#L1977). These filters are only registered [when a user doesn't have the `unfiltered_html` capability](https://core.trac.wordpress.org/browser/tags/5.2.3/src/wp-includes/kses.php?marks=2033#L2029) (which is the case for [multisite regular admins](https://core.trac.wordpress.org/browser/tags/5.2.3/src/wp-includes/capabilities.php?marks=401,402#L397)).

**To reproduce**
1. Run Gutenberg master on a multisite install, or test with a user not having the `unfiltered_html` capability.
1. Add a new post.
1. Insert a button block.
1. Set a gradient background on the button.
1. Save or publish the post.
1. Reload the editor.
1. Note how the button block is marked as invalid.

**Expected behavior**
The button should remain valid.

**Comment by jorgefilipecosta** [comment]
Hi @mmtr,
Thank you for reporting this issue.
I submitted a PR to fix the spacing problem: 
But we have another problem, for contributor rules our inline style is totally removed.
This happens because WP core has logic to only accept style rules with () inside for url(...):
https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/kses.php#L2264-L2271

It seems we can not have a simple temporary workaround in the plugin because although we can use safe_style_css to add new accepted style properties there is no filter to remove this logic from being applied.
I will try to submit a fix in WP core, to address the contributor problem.

**Comment by mmtr** [comment]
Thanks @jorgefilipecosta!

**Comment by jorgefilipecosta** [comment]
Closing this issue as the core patch was merged, the problem should be fixed on the next WordPress release.
