### ISSUE TITLE
Feature: Editorial comments/notes

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#17949]
I had started work on comments (or notes if you like) on text or blocks inside the editor. I soon realised that this might require some design input. One big influence is, of course, Google Docs. I like the way the comments are always visible, but we might not have the space for that with the sidebar (inspector). Alternatively, the list of comments could be displayed in a list in the sidebar, and kind of move next to the marked text when it is clicked on (the comment or the text). The downside of this is that the comment list wouldn’t be always visible.

**Comment by karmatosed** [comment]
This is really exciting! There might be some previous explorations to use from the Comment API work: https://github.com/WordPress/gutenberg/issues/3026. 

Topbar and in sidebar: https://github.com/WordPress/gutenberg/issues/3026#issuecomment-396182181

![41223822-273fdace-6d6b-11e8-81d2-d57c3199f517](https://user-images.githubusercontent.com/253067/66833415-b89afd80-ef53-11e9-95fe-922f520c407c.png)

![41223816-23933be6-6d6b-11e8-9375-b1d90ee720a7](https://user-images.githubusercontent.com/253067/66833422-bd5fb180-ef53-11e9-878e-17c4887b047b.png)

![41223826-29242250-6d6b-11e8-83f6-4ddb96c60637](https://user-images.githubusercontent.com/253067/66833424-be90de80-ef53-11e9-949b-ccf18ac0acf1.png)

Outside: https://github.com/WordPress/gutenberg/issues/3026#issuecomment-473322570

<img width="780" alt="54441071-3daf0180-473c-11e9-8780-4a6017625d94" src="https://user-images.githubusercontent.com/253067/66833485-d1a3ae80-ef53-11e9-8313-8d5d5b3e2e03.png">

<img width="814" alt="54441043-2b34c800-473c-11e9-919d-056b5058af08" src="https://user-images.githubusercontent.com/253067/66833489-d4060880-ef53-11e9-9ae2-945f60c34e5c.png">

Kudos to @hedgefield and @uxkai for explorations.

**Comment by mapk** [comment]
Here's an idea spurred from the concepts above. I'm making use of the sidebar because we have it. I'm also suggesting we use "Comment" as a mode in the new mode selector for Edit and Select. It might fit nicely there.

Selecting the "Comment" mode swaps out the sidebar with comments and shows all the highlighted comment areas on the page. 

Clicking through each highlighted part shows new comments in the sidebar.

[Link to prototype](https://www.figma.com/proto/RjSpDESe2Edb0FFIzbA3n7/Multi-user-Editing?node-id=2%3A1910&viewport=1087%2C417%2C0.25&scaling=min-zoom)

![comment 2019-12-26 20_42_29](https://user-images.githubusercontent.com/617986/71501618-695d2d00-2820-11ea-9bb3-97ceac003926.gif)

**Comment by karmatosed** [comment]
I would like to bring us back to a few points to decide on before we go through with any design here. Just as a bit of consideration as there are some assumptions in the prototype (which are fine if we agree):

- Is the new place to interact with anything that is an interaction going to be the mode drop down?
- Is commenting a mode?
- Is adding a 3rd use to the sidebar a good route forward?

Now, I have a few thoughts relating to this myself. I personally don't see commenting as a mode so would argue against putting it in same buckets as the others. You can edit and comment for example. I don't see a precedent for mixed modes yet (we might be establishing one).

If I think of the use case of commenting for example in Google docs, I do so 'on the fly' and I don't have to switch modes to do that. This is why I think some earlier explorations around this might be good to follow.

https://user-images.githubusercontent.com/253067/66833422-bd5fb180-ef53-11e9-878e-17c4887b047b.png

I think though bringing back to my first points, we need to have some clear IA on the modes and rules around that before jumping into this being the design direction. 

One consideration is I think without indicating it's the 3rd sidebar and just laying it over, that's quite a jarring experience. Of course, if commenting is to be a separate mode that might be acceptable, but what if I am in that mode and have sidebar turned off or on a smaller screen?

**Comment by jasmussen** [comment]
Great thread, great ticket, great feature. I'm so excited someone is working on this. My instinct for this is also that a sidebar is a good place for this. 

The old editor, "Editorially", was so lovely in this respect. I don't have good screenshots, all I could find was this:

![78edaa1682dc2e381bd24ee7ffb0f791_3](https://user-images.githubusercontent.com/1204802/71819897-b0071e80-308d-11ea-8c0e-3fea6b3d2c3a.png)

But in this one, it looks like commenting was indeed a "mode" that was invoked by activating the sidebar. I don't necessarily think it _needs_ to be a mode in the block editor, but it _could_ be, and the tools dropdown _could_ be a good place for it. This is equivalent to Figma where clicking the comment bubble changes into a mode where a single click adds a comment. 

I will say, though, that if we do make it a tool, like Figma, we should sleep in this idea for a while, think about it long and hard, and only do it if we feel it's SUPER right. We definitely don't want the tools dropdown to become a kitchen-sink :)

**Comment by mapk** [comment]
>  I personally don't see commenting as a mode so would argue against putting it in same buckets as the others. 

If the term "mode" is difficult, which I totally understand, we call these "tools" in the actual popover in Gutenberg. In which case, the _Comment tool_ would be active when selected. I imagine it's similar to how Figma does it.

![Screen Shot 2020-01-06 at 11 29 37 AM](https://user-images.githubusercontent.com/617986/71843300-63fdaf00-3078-11ea-931f-d54572af92a3.png)

Figma's sidebar also switches over to a commenting system.

![Screen Shot 2020-01-06 at 11 40 17 AM](https://user-images.githubusercontent.com/617986/71843744-67456a80-3079-11ea-8285-2000e96b7484.png)


My concepts are just thoughts being shared. I totally dig how Google Docs does it and would choose that first, but based on the original issue, I was under the impression that wasn't going to work so well for us here.

**Comment by karmatosed** [comment]
Just swapping out labels to encourage those iterations.

**Comment by jasmussen** [comment]
> If the term "mode" is difficult, which I totally understand, we call these "tools" in the actual popover in Gutenberg. In which case, the Comment tool would be active when selected. I imagine it's similar to how Figma does it.

To be clear, I'm cautiously agreeing with you that the Figma tool/mode combination might just be right here! The only reason I'm cautious is to suggest, and to echo Tammie, that this is something worth sketching/figma-prototyping out in somewhat high detail so that we can build up the confidence I feel should be necessary to add the tool!

**Comment by hedgefield** [comment]
Great to see some action on this concept again. I've been short on time for more explorations, so thanks a bunch @mapk for jumping in with a new prototype. The modes dropdown feels like a natural place to put the commenting sidebar toggle that I had in my old mockups, it didn't exist back then or I would have probably come to the same conclusion :)

That said, I agree with the point that leaving a comment should be a no-brainer anytime anywhere action. But I don't think these have to be mutually exclusive.

I think the act of _commenting_ can be integrated into the writing and editing mode easily. It could appear when you highlight a sentence or a block, open a popover to type into and that's it. This is similar to what Notion does in the screenshot that Tammie posted above.

_Taking action on comments_ then could use a dedicated sidebar that shows all the comments and replies in their entirety and you can go through and respond. This also wouldn't have to exclude editing, as to edit text you don't really need the sidebar. This means you can comment and continue working without the burden of a separate mode, and only summon all comments when necessary. And I'd vote for making that possible from every comment indicator in the document, instead of explictly having to go to a mode dropdown.

I hope this makes sense to anybody outside of my head too! I've made a quick sketch to support the idea visually. Thoughts?

<img src="https://user-images.githubusercontent.com/6073772/71969930-eec0e400-3207-11ea-922f-b3821fcdb6db.png" width="256" /> <img src="https://user-images.githubusercontent.com/6073772/71969931-ef597a80-3207-11ea-9469-e6398646bbba.png" width="256" />
<img src="https://user-images.githubusercontent.com/6073772/71969933-ef597a80-3207-11ea-82ba-68a1278a95aa.png" width="256" /> <img src="https://user-images.githubusercontent.com/6073772/71969935-eff21100-3207-11ea-9dbb-6191e84bf39d.png" width="256" />

**Comment by mapk** [comment]
Hey @hedgefield! Glad to see you coming back to this. 😄 

> But I don't think these have to be mutually exclusive.

I agree here! The combination that you presented works quite well together.

> This also wouldn't have to exclude editing, as to edit text you don't really need the sidebar. This means you can comment and continue working without the burden of a separate mode, and only summon all comments when necessary.

Good points! 👍  I didn't dig into that experience in detail quite yet, so I'm stoked that you did. Allowing a way to just add a comment from the "Edit" mode feels intuitive and bringing some sort of way to do that close to the content is the way to go.

**Comment by karmatosed** [comment]
This is great @hedgefield, good to see more exploring around this. I wonder what other than a sidebar could be used? I know there were some explorations right back in phase one we went through that I think took it interestingly out of there.

**Comment by paaljoachim** [comment]
What I found interesting in Gutenberg 7.7 was the placement of the Block Patterns in the sidebar. Even though they later will be added to the Block Inserter screen. The concept of turning on something that shows up in the sidebar was very interesting.

![Screen Shot 2020-03-17 at 23 17 46](https://user-images.githubusercontent.com/5323259/76907279-1eded000-68a6-11ea-923f-27aebc61287c.png)

Advantage
It does not add any icons to the top toolbar.
It is a little more hidden away. Does not create visual clutter.
Uses the sidebar settings (it seems on top of settings) to create notes.

**Comment by mtias** [comment]
Closing as this is superseded by #59445.
