### ISSUE TITLE
`@wordpress/scripts` lint:js includes comment 

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#17966]
**Describe the bug**
Running lint:js includes warning for comments `warning  The type 'Component' is undefined` :

```
/**
 * Override the default edit UI to include a new block inspector control for
 * assigning the custom class name, if block supports custom class name.
 *
 * @param {Function|Component} BlockEdit Original component.
 *
 * @return {string} Wrapped component.
 */
```

Happening `"@wordpress/scripts": "^5.1.0"`

**Comment by gziolo** [comment]
It's all good. It doesn't break the flow as it's a warning. You should either declare the type `Component` or use `Object` instead.

**Comment by gziolo** [comment]
@dsifford – do you know how this could be resolved in Gutenberg and for folks who consume npm packages? Can we somehow provide those basic types and make them available for reuse?

**Comment by dsifford** [comment]
> Can we somehow provide those basic types and make them available for reuse?

Yes. This is precisely the reason why the lint warning is happening; because they are not yet provided.

Assuming the `Component` being warned about here is just a React `Component`, the way to fix this particular error would be to import `Component` from the React type definitions using a [jsdoc import typedef statement](http://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html#import-types). Once it's imported in that file, the linter will be aware of it and the warning will go away.

So, for example...

```js
/**
 * @typedef {import('react').Component} Component
 */
```

**Comment by gziolo** [comment]
It was added as a breaking change in v5.0.0 so everything is correct. 

See also: https://github.com/WordPress/gutenberg/blob/master/packages/eslint-plugin/CHANGELOG.md#300-2019-08-29
