### ISSUE TITLE
Popover positioning is unexpected

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#17978]
**Describe the bug**
When I specify a popup position, the popup doesn't always show where I expect it to

**To reproduce**
1. Check out this PR: https://github.com/WordPress/gutenberg/pull/17977
2. Add a link to some text
3. Enter some text in the URLInput field to open the list of pages
4. Notice that the popover doesn't appear at the bottom left of the URLInput

**Expected behavior**
I expected the popover to appear at the bottom left of the URLInput

**Screenshots**
<img width="858" alt="Screenshot 2019-10-16 at 18 17 25" src="https://user-images.githubusercontent.com/275961/66942548-3ee13d80-f041-11e9-9d5b-976570345101.png">

**Comment by scruffian** [comment]
@noisysocks, I think the code introduced in #6631 is the root of the issue here. There are some things I don't understand in this code:

- Why does the left alignment depend on the chosenYAxis? https://github.com/WordPress/gutenberg/blob/master/packages/components/src/popover/utils.js#L37
- Why do we need to change the left alignment based on the width of the element? (https://github.com/WordPress/gutenberg/blob/master/packages/components/src/popover/utils.js#L40) If the element is going to be left aligned then it can overlap to the right for quite a while before its going to hit the edge of the window. Would it be better to check if the left alignment plus the width is greater than the window?

I'll probably have more questions once I've investigated some more.

**Comment by noisysocks** [comment]
> Why does the left alignment depend on the chosenYAxis?

If you choose `yAxis = 'middle'` then the popover must appear to the left or to the right of the anchor point, otherwise it will obscure the anchor point. The horizontal direction (left or right) is chosen based on how much horizontal screen real estate there is so that none of the popover appears off-screen.

> Why do we need to change the left alignment based on the width of the element? 

This is to prevent the popover appearing off-screen. For example, if you choose `xAxis = 'right'` and the anchor point is so near to the right of the screen that some of the popover would appear off-screen, then `xAxis` is overridden to be `'left'`.

**Comment by scruffian** [comment]
@noisysocks - thanks for the reply!

> If you choose yAxis = 'middle' then the popover must appear to the left or to the right of the anchor point, otherwise it will obscure the anchor point. The horizontal direction (left or right) is chosen based on how much horizontal screen real estate there is so that none of the popover appears off-screen.

This makes sense for this case, but if I have not chosen `middle`, the left alignment defaults to the midpoint, might not be what I have selected.

> This is to prevent the popover appearing off-screen. For example, if you choose xAxis = 'right' and the anchor point is so near to the right of the screen that some of the popover would appear off-screen, then xAxis is overridden to be 'left'.

I get this for the `right` case, but for the `left` case the logic we have seems flawed - shouldn't we be looking at the browser width in this case?

**Comment by noisysocks** [comment]
> This makes sense for this case, but if I have not chosen middle, the left alignment defaults to the midpoint, might not be what I have selected.

The idea is that the axes you specify via `position=""` are where you would _prefer_ the popover to appear. It might not be possible, in which case your preference will be totally ignored. 

For example, `"top left"` will switch to `"bottom right"` if the anchor point is too near to the top left of the screen. `"middle left"` will switch to `"bottom right"` if the anchor point is too near to the top left of the screen.

> I get this for the right case, but for the left case the logic we have seems flawed - shouldn't we be looking at the browser width in this case?

It's been a long while since I've looked into this code so I can't say off the top of my head whether there's a flaw there. It is of course possible that there are bugs 🙂 — would you like to do some investigating and report back?

**Comment by scruffian** [comment]
@noisysocks the PR linked in the description illustrates one of the bugs, which is caused by the lines I pointed out! If you can confirm that this is indeed a bug I'll be happy to work on a fix, but I just wanted to make sure it really was a bug first!

**Comment by noisysocks** [comment]
I took a look at your PR and I don't think there's a bug there.

I think the confusion here is thinking that `"bottom left"` means 'position the popover to the bottom left of the _container_', when in fact it means 'position the popover to the bottom left of the _anchor point_'. The anchor point is the centre of the container. 

Referring to your example, `position="bottom left"` instructs the Popover to position itself to the bottom left of the _anchor point_, shown in pink:

<img width="681" alt="Popover bottom left" src="https://user-images.githubusercontent.com/612155/67170754-8e3bbb00-f3ff-11e9-83da-16acd3b0f7e4.png">

Similarly, `position="bottom right"` instructs the Popover to position itself to the bottom right of the _anchor point_:

<img width="696" alt="Popover bottom right" src="https://user-images.githubusercontent.com/612155/67170763-94ca3280-f3ff-11e9-81f8-c61d936b23a0.png">

(The edge doesn't align perfectly because of a `margin-left: -24px` on `. components-popover__content` which is there to account for the popover arrow which is hidden in this case.)

Popovers in Gutenberg work this way because Gutenberg generally uses popovers for dropdown that point to a specific point on the screen:

<img width="409" alt="Screen Shot 2019-10-21 at 12 45 06" src="https://user-images.githubusercontent.com/612155/67170995-af50db80-f400-11e9-979c-bed096173aad.png">
<img width="289" alt="Screen Shot 2019-10-21 at 12 45 16" src="https://user-images.githubusercontent.com/612155/67170996-b11a9f00-f400-11e9-8e49-679a4885b424.png">
<img width="400" alt="Screen Shot 2019-10-21 at 12 45 31" src="https://user-images.githubusercontent.com/612155/67170997-b24bcc00-f400-11e9-9546-88eb85729810.png">

Does that make sense? Could we help clarify this by e.g. updating the docs?

**Comment by scruffian** [comment]
Ah ok now I get it, thanks. Glad I didn't spend too long trying to "fix" it!

How is the anchor point defined?

**Comment by aduth** [comment]
Unless I've misinterpreted the discussion, it doesn't appear there's a bug or other actionable item to be resolved here.

>How is the anchor point defined?

One can be provided custom using the `anchorRect` prop. But by default, the Popover will [render an (effectively empty) `span` element](https://github.com/WordPress/gutenberg/blob/b39e9d9c3f9336a1fd297b332e7eff4626b3efee/packages/components/src/popover/index.js#L502-L504) at the original DOM location, and this is used as the basis for positioning the popover.
