### ISSUE TITLE
TimePicker is12hour format is reversed

### ISSUE THREAD

**Issue by JHeimbach** [WordPress/gutenberg#17970]
**Describe the bug**
The order of inputs for a Timepicker is reversed. 
In the documentation is described that the dateformat is assumed to be mm-dd-yyyy if is12Hour is true, currently the order is switched on `is12Hour`.

**To reproduce**
 1. Insert Timepicker component in Block
 2. set is12Hour to true

or
here is the responsible function https://github.com/WordPress/gutenberg/blob/master/packages/components/src/date-time/time.js#L243-L247

**Expected behavior**
```
is12Hour == true => MM-DD-YYYY
is12Hour == false => DD-MM-YYYY
```

**Screenshots**
![block editor](https://user-images.githubusercontent.com/1742040/66917000-c2d4fe80-f01c-11e9-82fa-37a7267761d5.png)
![code snippet](https://user-images.githubusercontent.com/1742040/66917023-d1bbb100-f01c-11e9-9b32-72d9bd2fd742.png)

**Desktop (please complete the following information):**
 - OS: all
 - Browser all
 - Version all

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser: all
 - Version: all

**Additional context**
- Tested in: WordPress 5.2.4

**Comment by JHeimbach** [comment]
If you want I can open a PR with the necessary changes

**Comment by talldan** [comment]
Thanks for reporting @JHeimbach, sorry it took so long to verify this! We discussed this in a triage session in slack (https://wordpress.slack.com/archives/C02QB2JS7/p1625548800325600).

The problem is quite easy to spot in the storybook:
https://wordpress.github.io/gutenberg/?path=/story/components-timepicker--default

Definitely open to contributions for this if you're still interested, though I realise your comment was almost two years ago.

DateTimePicker also seems to have the same problem, but I think it probably uses the same component.

It might be an option to use a separate more clearly named prop to indicate the order of the fields.

**Comment by sabernhardt** [comment]
Related tickets on Trac: [52501](https://core.trac.wordpress.org/ticket/52501) and [52664](https://core.trac.wordpress.org/ticket/52664)

**Comment by milkcask** [comment]
There appears to be a dated assumption that go against i18n best practices. I'm going to add a new prop for date format preference and break that assumption.
