### ISSUE TITLE
Get the current attributes from the Block mockup?

### ISSUE THREAD

**Issue by bilouStrike** [WordPress/gutenberg#18024]
Hi, I need to use the current attributes of selected block, i found this selector getBlock in the Namespace: core/block-editor, that say : "Returns a block given its client ID. This is a parsed copy of the block,containing its blockName, clientId, and current attributes state." 
but it give me my default attributes definition.
I need just the attributes that saving in the block mockup.

**Comment by talldan** [comment]
@bilouStrike It looks like you can use `getSelectedBlock` (https://developer.wordpress.org/block-editor/data/data-core-block-editor/#getSelectedBlock) for that purpose.

Just a note, this github repo is devoted to the development of the block editor rather than help requests. For future help requests please go to either the wordpress.org forums or the WordPress stack exchange. Thanks.
