### ISSUE TITLE
404 error url in the Readme

### ISSUE THREAD

**Issue by paolosax** [WordPress/gutenberg#18056]
**Describe the bug**
You can check how this component is implemented for the edit post page using wp.media module in "edit-post". -> the link is not available

**Comment by henryholtgeerts** [comment]
I have tracked down the working link [here](https://github.com/WordPress/gutenberg/tree/master/packages/edit-post/src/hooks/components/index.js). 

The bug was caused by an extra 'media-upload' in the URL.

I made the necessary changes and have created PR [#18277](https://github.com/WordPress/gutenberg/pull/18277) accordingly!
