### ISSUE TITLE
Widgets: Define widget screen admin locations for extension via SlotFill 

### ISSUE THREAD

**Issue by ryanwelcher** [WordPress/gutenberg#18068]
The current implementation of the Widgets screen has no exposed SlotFill locations for developers to leverage.

The existing widgets.php page has two actions that can be leveraged to add additional items to the page:

 `widgets_admin_page`: appears below the title of the page.

![widget-admin-page](https://user-images.githubusercontent.com/1259027/67318335-5bfe8c00-f4d9-11e9-85f1-c215ab021f14.png)

`sidebar_admin_page`: appears above the footer:

![sidebar-admin-page](https://user-images.githubusercontent.com/1259027/67318264-45583500-f4d9-11e9-8acf-4fd6966940e7.png)

I propose that we start by introducing a SlotFill equivalent for each of these actions on the new widget screen:
1. PluginPreWidgetAreas: appears before the Widget areas are rendered
2. PluginPostWidgetAreas: appears after the Widget areas are rendered
![widgetScreenSlots](https://user-images.githubusercontent.com/1259027/67318354-615bd680-f4d9-11e9-8833-2dc3cc9fe1ab.png)

**Comment by ryanwelcher** [comment]
I would also like to propose a new location here:
![widgetAreasPanel](https://user-images.githubusercontent.com/1259027/94025673-c45b8a80-fd86-11ea-8802-0b7010446928.png)

**Comment by noisysocks** [comment]
`PluginPreWidgetAreas` and `PluginPostWidgetAreas` is difficult because that entire part of the screen (the grey area) is a block editor. I think instead let's make it so that plugins can insert blocks at the first and last position using `wp.data.dispatch( 'core/block-editor' ).insertBlock( ... )`.

`PluginWidgetAreasPanel` sounds good to me.
