### ISSUE TITLE
button text color

### ISSUE THREAD

**Issue by NasKadir123** [WordPress/gutenberg#18168]
**Describe the bug**
Hi! I added my color palette by theme_support.
Everything is working, except button text color.
In backend it shows fine, but in frontend my text color is always white,
Because you have:
`.wp-block-button__link:active, .wp-block-button__link:focus, .wp-block-button__link:hover, .wp-block-button__link:visited {
color: inherit; }`
I can't understand why it crosses out my class style for text color.

**Screenshots**
Here I have in my backend:
![Снимок экрана 2019-10-29 в 20 06 37](https://user-images.githubusercontent.com/49153601/67774833-3d276900-fa88-11e9-9d3d-f25c048edee7.png)
Here it is in frontend:
![Снимок экрана 2019-10-29 в 20 12 09](https://user-images.githubusercontent.com/49153601/67774971-78c23300-fa88-11e9-867d-2025e651d7d4.png)

**Desktop (please complete the following information):**
 - IOS
 - Chrome
 - Version 78.0.3904.70

**Additional context**
- Wordpress Version 5.2.4

**Comment by jorgefilipecosta** [comment]
Hi @NasKadir123,
It seems the styles set an inherited color for focus, hover and visited. In this case, the visited style is overwriting your styles when the button was previously visited.
If you don't want the visited styles to apply, you may solve this problem by increasing the specificity of your styles e.g: instead of ".has-dark-greyish-background" use ":root .has-dark-greyish-background" as the selector.

I hope you find this information useful. If you would like additional discussion on this issue, feel free to leave a comment.
