### ISSUE TITLE
Radio buttons broken layout within the meta boxes area

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#18181]
**Describe the bug**
Also reported on Trac as it affects WordPress 5.3 RC 3, see https://core.trac.wordpress.org/ticket/48466

A very recent CSS change in Gutenberg that was merged yesterday in core breaks the radio buttons used by plugins within the editor meta boxes area. Specifically the newly added margin: -3px -4px; makes the radio buttons "blue dot" completely misplaced:

<img width="378" alt="Screenshot 2019-10-30 at 12 15 12" src="https://user-images.githubusercontent.com/1682452/67855497-d307d600-fb12-11e9-99f5-d81d5850b90a.png">

See https://github.com/WordPress/gutenberg/pull/18108/files#diff-0ad88efa3865f313f57c422957d02b2fR99-R101

Removing these negative margins fixes the issue. I'm not sure they are really necessary, as removing them doesn't seem to change anything else. Also, to my understanding #18108 was meant to fix issues within the sidebar, so I'm not sure why it's targeting the meta boxes area.

To reproduce, use Advanced Custom Fields and add a group with a radio button and a checkbox. Or directly edit the HTML in your browser dev tools and add a radio button and a checkbox somewhere within the meta boxes area .postbox.

<img width="533" alt="Screenshot 2019-10-30 at 12 52 21" src="https://user-images.githubusercontent.com/1682452/67856239-5b3aab00-fb14-11e9-8c86-31cfda9b8865.png">

**Comment by afercia** [comment]
@youknowriad reminded me plugins and themes can add meta boxes into the default sidebar. See for example the "Astra" theme mentioned in the related issue #18053. Screenshot:

<img width="322" alt="Screenshot 2019-10-30 at 13 13 49" src="https://user-images.githubusercontent.com/1682452/67857602-82df4280-fb17-11e9-9087-f0c71442177c.png">


However, the new CSS should _not_ target the meta boxes area below the post.

**Comment by jasmussen** [comment]
Changed the CSS to not target the meta boxes area below the post.

![Screenshot 2019-10-30 at 13 42 32](https://user-images.githubusercontent.com/1204802/67859649-6bef1f00-fb1c-11e9-9145-7ca44b25c5a4.png)

I noticed that radio buttons have regressed:

![Screenshot 2019-10-30 at 13 51 04](https://user-images.githubusercontent.com/1204802/67859700-89bc8400-fb1c-11e9-9c90-19e27c6f46c8.png)

I have not slipstreamed a fix in this one as it's an unrelated issue. But the issue is that the radios used to be sized in pixels, now they're sized in rems. In pixels they were 16x16, which made the math to position the dot correct. Now they compute to 15x15px, smaller hit area and obviously non-centered dot. 

Is this tracked or is someone working on this?

**Comment by afercia** [comment]
I'm not seeing changes to the the visibility radio buttons. Any special way to reproduce that? Browser? 

> In pixels they were 16x16 ... Now they compute to 15x15px,

`1 rem` still computes to 16 pixels. Are you sure the misalignment is not because of some other reasons e.g. a plugin that alters the CSS?

**Comment by jasmussen** [comment]
Excellent instinct. It's caused by Astra theme, it seems.

**Comment by jasmussen** [comment]
I do agree it is unfortunate that themes can affect the UI as such. The lack of an iframe is causing this. Shadow DOM is an option, rewriting such rules using the built in editor style rewriter is another, but even then themes can enqueue styles globally so we can't fully prevent it. 

There is some discussion in https://github.com/WordPress/gutenberg/issues/10178#issuecomment-539462094 on how to proceed to protect UI from editor styles.
