### ISSUE TITLE
Translation references at translate.wordpress.org

### ISSUE THREAD

**Issue by mobby2561** [WordPress/gutenberg#18184]
Is there a way to change the plugin references to a different source which is human readable?
Many of the strings are really hard to spot, so I hope that this could help a little bit.

I've seen different source for the Twenty Twenty theme which is pointing to it's GitHub, so maybe giving translators the wp/trung branch as an reference might be the solution.

Thank you in advance.

**Comment by swissspidy** [comment]
Twenty Twenty is a bit special because development currently happens on GitHub and not on WordPress.org SVN.

The Gutenberg plugin is also special because the source files are here, but the WordPress.org translation platform only scans the final plugin that is uploaded to the plugin directory, which unfortunately means the references are not really human readable.

If you have an idea on how to change this, I suggest opening a ticket on https://meta.trac.wordpress.org/ to adjust the translation platform, as there's nothing that can be done on the Gutenberg side to change this
