### ISSUE TITLE
"No matching template found"

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#18209]
**Describe the bug**
After updating to latest Gutenberg plugin version the frontend is displaying "No matching template found"

**To reproduce**
1. Update the Gutenberg plugin
2. Go to any post

**Expected behavior**
Should display the post

**Screenshots**
<img width="1211" alt="Screen Shot 2019-10-31 at 7 08 39 PM" src="https://user-images.githubusercontent.com/3365507/67942124-19902a00-fc12-11e9-9f46-321189f1ee4d.png">

**Comment by aristath** [comment]
In your plugin options there's checkboxes to enable/disable experiments.
I'm guessing you have enabled the templates experiment.
You can simply disable it, this experiment is under heavy development.
If you do want to test it, there's a new menu under Appearance on your dashboard where you can create templates. Templates should be named `index`, `page` etc. There's currently no blocks for `content`, `post-title` etc, these are still being worked on (that's why it's still an experiment).

**Comment by phpbits** [comment]
@aristath I totally understand the there are `experiments` but those were checked before the plugin was updated and working fine. Are there reasons why there is no checker if there are templates or not to prevent this error? Thanks!

**Comment by aristath** [comment]
More work is being done and released with each update of the plugin.
Previously there was not enough work done in this feature so it wasn't doing anything. Now that there's been more progress, it does.
It's not an error. It's an experiment. These should not be enabled on live sites

**Comment by phpbits** [comment]
@aristath I see. Thanks a lot!

**Comment by youknowriad** [comment]
Closing as addressed. The replies from @aristath are valid.

**Comment by lordspace** [comment]
@aristath  how do you disable templates experiments? where can I find this in the settings?
