### ISSUE TITLE
Navigation Block: Enter key shouldn't add line break in menu item

### ISSUE THREAD

**Issue by mcsf** [WordPress/gutenberg#18208]
**Describe the issue**
This is both a bug report and an enhancement request.

1. When the caret is inside a menu item, I had expected that pressing <kbd>Enter</kbd> would:
  * Add a new menu item in the same level as the item I was editing.
  * **or** at the very least add a subitem whose parent is the item I was editing.
2. In any case, defaulting to breaking the line feels like experiencing an unhandled case.

**To reproduce**
1. Start a new post.
1. Add a Navigation block.
1. Add the first menu item, input some text
1. Press <kbd>Enter</kbd>

**Observed**
We remain in the same menu item, but now this item's text contains a line break.

**Expected behavior**
That's up to us to decide.

**Comment by mcsf** [comment]
Added to the _Navigation block_ project for visibility, but please move it out or close if deemed unimportant.

**Comment by karmatosed** [comment]
For now, going to mark this as needs design feedback. It certainly does need thinking but not sure a design needs creating yet.

**Comment by mapk** [comment]
I experienced this over here: https://github.com/WordPress/gutenberg/issues/18353#issuecomment-569372668 and it felt really odd. I expected different results when hitting `Enter` similar to @mcsf.

**Comment by karmatosed** [comment]
Removing design feedback label as I think we have it.

**Comment by mapk** [comment]
I'm still experiencing this. Can we get some development on it? 

![nav](https://user-images.githubusercontent.com/617986/76132158-560bd200-5fc6-11ea-9838-601115610304.gif)

**Comment by talldan** [comment]
@mcsf @mapk Would be good to clarify the desired behaviour so that we can see if it fits into the current behaviour that RichText supports (onReplace, onSplit, onDelete etc). 

I think there are two options:
- Hitting Enter when the caret is in the middle of a range of text does nothing. Hitting enter when the caret is at the start or end of the range adds a new nav link before or after.
- The RichText behaves much like the paragraph block. Hitting Enter when the caret is in the middle of a range splits the nav link into two links and Delete merges them back together

I think the first option seems reasonable, but it might require some modifications to how RichText handles `onSplit` or possibly something related to the `multiline` prop, which I always found a little confusingly named.

The second option seems unusual in this context, I don't really see a use case for splitting a link in two. The closest block to this one seems like the Buttons block, which is also basically a set of links. Does it seem like this behavior should also exist there?

**Comment by noisysocks** [comment]
What do you think @karmatosed?

**Comment by karmatosed** [comment]
> Hitting Enter when the caret is in the middle of a range of text does nothing. Hitting enter when the caret is at the start or end of the range adds a new nav link before or after.

This one I 'think' feels right. I'm wondering if we are limiting a user case for having it work just like a paragraph? That's my only concern with limiting.
