### ISSUE TITLE
Heading block "encountered an error" since 6.8.0

### ISSUE THREAD

**Issue by niaccurshi** [WordPress/gutenberg#18232]
**Describe the bug**
Upon installing the 6.8.0 plugin update, all of my heading blocks returned the "This block has encountered an error and cannot be previewed." error in the editor.

**To reproduce**
1. Have a site where the headings exist in the editor, with extra classes defined (unsure if it is relevant but all of my headings do have extra classes defined)
2. Upgrade the plugin to 6.8.0
3. Check the heading block and see the error returned

**Expected behavior**
Normal heading block display

**Comment by niaccurshi** [comment]
The same happens when adding a new heading block, the following error is created

![image](https://user-images.githubusercontent.com/1426885/68019900-e347be80-fc94-11e9-82c3-524d6f1a939e.png)

**Comment by turansadri** [comment]
I had this in my theme setup (removes the colour palette) and noticed it now breaks the headings after 6.8.0 update.

add_theme_support( 'editor-color-palette' );

However it's easily fixed by giving an empty array instead of nothing.

add_theme_support( 'editor-color-palette', array() );

Hope this helps.

**Comment by niaccurshi** [comment]
Thanks this also resolved my issue, would be good to see an empty array applied as default to stop other themes crashing this way!

**Comment by m-alzam** [comment]
Confirmed with a child theme.
