### ISSUE TITLE
urls in content block are saved with escaped characters - breaks search&replace

### ISSUE THREAD

**Issue by despecial** [WordPress/gutenberg#18267]
Case:
Enter a link in the editor and save it. In the database the link is saved as `https:\/\/www.google.com`

Problem:
If you want to move the site and replace all links, these stored values will be ignored because they don't match the normal pattern `https://www...`.

Reported also at the wp-cli git:
https://github.com/wp-cli/wp-cli/issues/5293

Why are these links escaped?

**Comment by ehti** [comment]
Hi @despecial,

We tried to reproduce this in editor triage today, but couldn't. Links in content (including inline links) are saved in database without being escaped.

Can you share some more details - what kind of links are you referring to? And can you try it on a fresh WordPress install without extra plugins and the default theme?

Thanks

**Comment by despecial** [comment]
Hello @ehti I will repost what I already posted at the wp-cli repo.
Concerning your question: any links in Gutenberg blocks

Currently we pull the database from a production page to develop environment.
After import we run this commmand to update to local urls
`wp search-replace production_url local_url`

The problem seems to be the way Gutenberg stores values.
URLs are escaped and become:
`https:\/\/www.domain.com`

So I ask myself: should wp cli run twice or use two wp search-replace commands?
```
wp search-replace https://www.production_url https://local_url
wp search-replace https:\/\/www.production_url https:\/\/local_url
```

**Comment by skorasaurus** [comment]
I ran into this problem today (where a URL wasn't updated after I ran wp search-replace) and investigated: 

Even after running: 
`wp search-replace 'https://nameofmysite.com' 'https://nameofmytestingsite.test' --recurse-objects --skip-columns=guid --skip-tables=wp_users`

Also running `wp search-replace https://nameofmysite.com https://nameofmytestingsite.test --recurse-objects --skip-columns=guid --skip-tables=wp_users` produced the same results below. 

I found that all of the pages that still contained `https://nameofmysite.com` (the url that I wanted to be replaced) had invalid html inside of its `post_content` (e.g. missing closing` </li></p> `and `</a>` tags); 
Some of the pages were last updated using TinyMCE (before Gutenberg); there was one page written in Gutenberg but the invalid html (which I wrote) were inside HTML blocks. Notably, when I went to update the page in Gutenberg 9.5.1, I was prompted to recover the HTML blocks, something that I hadn't received before when I had edited that page in Gutenberg (it had been a couple months and a couple releases of the Gutenberg plugin since I last edited that page. 

I'm closing this issue. If you're able to reproduce this using content that is produced in Gutenberg (besides writing invalid HTML in the HTML block; please share the exact steps (what block); and see if this problem still occurs in other themes like TwentyTwenty or TwentyNineteen.

**Comment by despecial** [comment]
Why are you closing this when we already confirmed WHAT is causing the problem.
The escaped // signs that are ignored by the replace command.

I dont understand why you speak about reproducing this and you still dont mention if your "recovering of the HTML blocks" changed the urls correctly.

This is just wrong and a total different problem what you are talking about.

**Comment by skorasaurus** [comment]
Sorry, I should have be more clear: fixing the HTML errors did fix the problem for me and yes, my issue had a different cause than yours. 

That said, 
I have not seen any instances where Gutenberg stores urls in its block content like you shared `https:\/\/www.google.com`  

Others have reported it at https://github.com/wp-cli/wp-cli/issues/5293 but neither they nor you have reported how Gutenberg specifically creates those urls. 

If you provide more information like what block you are using; whether this still happens when you have deactivated all plugins on the site;

**Comment by Mamaduka** [comment]
Hi,

This came up during the recent Editor bug scrub. A few of us attending tested the issue but couldn't reproduce it.

Considering the issue has been inactive, I will close it for now.

Here's my tests content:

```html
<!-- wp:paragraph -->
<p>Testing <a href="https://example.com">URLs</a> for example content.</p>
<!-- /wp:paragraph -->

<!-- wp:social-links -->
<ul class="wp-block-social-links"><!-- wp:social-link {"url":"https://example.com/","service":"wordpress"} /--></ul>
<!-- /wp:social-links -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"className":"is-style-fill"} -->
<div class="wp-block-button is-style-fill"><a class="wp-block-button__link wp-element-button" href="https://example.com">Example</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->
```

After adding the post, I could successfully run - `wp search-replace https://example.com https://example.org`
