### ISSUE TITLE
NavigationMenuItem: Close dropdown once option selected.

### ISSUE THREAD

**Issue by retrofox** [WordPress/gutenberg#18309]
There's no way to close the dropdown once options are selected except for clicking outside or pressing Esc. Perhaps a close button would be useful?

**Comment by tellthemachines** [comment]
@retrofox I'm not sure if this issue refers to the link selection dropdown (because we previously discussed the same issue happening with the colour palette dropdown) but it's certainly happening there, so I'm attaching a screenshot of it for clarity:

<img width="401" alt="Screen Shot 2019-11-13 at 11 08 52 am" src="https://user-images.githubusercontent.com/8096000/68723235-1e8aab80-060c-11ea-9016-3ec66d6d27df.png">

Feel free to edit this or add more info if you were referring to another dropdown!

**Comment by karmatosed** [comment]
I explored this a bit, my concern though is we are getting to that situation of 2 things close together even we stagger this:

![closing](https://user-images.githubusercontent.com/253067/70463049-05aed200-1ab4-11ea-9df2-b3f562e46e80.png)

**Comment by shaunandrews** [comment]
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/191598/70470441-02f2b380-1a99-11ea-95f5-0728c28a0c42.png">

We could try moving the "Change" button down to its own line. Also shown on the right is an idea of making the popover narrower when the Link Title and URL are shorter — but grow as needed.

**Comment by karmatosed** [comment]
@shaunandrews that seems like a reasonable middle ground, going to remove design feedback label and let's go with that for now.

**Comment by getdave** [comment]
I agree we need this, but (personal opinion alert!) the visuals look a lot less elegant to me now that the `Change` button isn't on the right hand side.

Without the `X` icon breaking outside the boundaries of the popover (which I assume would be outside design style guide) I don't see any other option however. 

Also noting that Google docs _doesn't_ have a close button so just confidence checking that we definitely need to do this...

**Comment by WunderBart** [comment]
> There's no way to close the dropdown once options are selected except for clicking outside or pressing Esc

Regarding closing it via `ESC` - it actually doesn't work in the following scenario:

1. Click `Add Navigation Link`,
2. Define a URL and press enter,
3. The popup should remain open showing the created link details but will go out of focus (?) and won't be closable by `ESC`,
4. Press `TAB` to bring one of popup's elements to focus and then `ESC` to close the popup.

Does that sound like something that could be addressed within this issue? Happy to create another issue otherwise.

**Comment by shaunandrews** [comment]
Seems like #19481 could be related.

**Comment by tellthemachines** [comment]
Is this still needed now that the dropdown closes itself on link selection?

**Comment by draganescu** [comment]
Hi @tellthemachines from my testing this does not feel like a need anymore. I will close this but pinging @shaunandrews for second opinion.
