### ISSUE TITLE
Adding sub items to menu is confusing visually with all the + icons

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#18333]
If you add a few sub-items you get this visual:

![nav-subconfuse](https://user-images.githubusercontent.com/253067/68317164-93ad2c80-00b2-11ea-9e66-a7afc3482b62.png)

I would suggest that seeing just one is better and this isn't a great experience for people, beyond the background not letting me see the '+' any way that well.

**Comment by mapk** [comment]
Ooooh. Those trailing `+` icons are all over the place! Definitely needs help. 

![Screen Shot 2019-11-06 at 4 09 55 PM](https://user-images.githubusercontent.com/617986/68348848-07016f00-00b0-11ea-9895-ab86ca12f0ac.png)

Can we drop those `+` icons completely since we have a block toolbar icon that adds more submenu items?

![Screen Shot 2019-11-06 at 4 11 32 PM](https://user-images.githubusercontent.com/617986/68348867-1da7c600-00b0-11ea-8865-d762120dc7da.png)

**Comment by mapk** [comment]
We could probably drop them from the sidebar too!

![Screen Shot 2019-11-06 at 4 12 36 PM](https://user-images.githubusercontent.com/617986/68348941-53e54580-00b0-11ea-80f6-bf6ab2b92fbe.png)

**Comment by mtias** [comment]
The plus is a trailing inserter when a sub-menu already exists. It should show only for the currently selected level.

**Comment by obenland** [comment]
Work on #18310 should help alleviate some of this pain

**Comment by draganescu** [comment]
It feels as if this is a bug. I think I can remember that at some point all sub items behaved like the main items, and you could (like @mtias describes) only see the appender for the currently selected level.

**Comment by draganescu** [comment]
Yes, I found in git history that there was an issue with the registration of allowed blocks which prompted @talldan to hide menu items with css instead, but that leaves "on" all those appenders.

I added this #19598 small PR to hide appenders for other navigation levels. Not sure if this is  the best approach but if it is, it will help when we implement those flyout ideas in #18310.

**Comment by obenland** [comment]
@draganescu Was this fixed by #19598?

**Comment by talldan** [comment]
Yep, I think this is fixed by #19598.
