### ISSUE TITLE
Clicking into menu item shows border

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#18331]
Right now you see a border around the menu item when you click into it:

![image](https://user-images.githubusercontent.com/253067/68316842-0a95f580-00b2-11ea-8f7c-f8027906890b.png)

I would suggest having nothing is better?

**Comment by mapk** [comment]
I'm a little lost here, so bear with me...

**If you're talking about the light grey border around the input field**... that's necessary because it indicates an input field, but at the same time it's so light I can barely see it. My suggestion in this case is to keep the border around the input field and darken it for accessibility.

**However, if you're talking about the dotted border**... that's actually the parent block's border and not the border of the individual item. It's hard to discern between the two because you've selected the first menu item. Clicking one of the others shows this relationship a bit better. 

Ultimately either case can use some design improvements.

**Comment by draganescu** [comment]
I am not sure if we need to treat the menu item as an input and add a border to it, because being a Rich Text you'd expect it to simply be editable text, not an input as there is no form to submit. I would remove the border altogether.

**Comment by karmatosed** [comment]
I also feel it shouldn't be treated as input as we don't do this to typing area.

**Comment by mtias** [comment]
The text is a Rich Text attribute, same as the text of a Button block, so shouldn't have any border unless it's part of the front-end design as well. The menu item as a whole should have a focus state (like when you press Escape).

**Comment by retrofox** [comment]
> The text is a Rich Text attribute, same as the text of a Button block, so shouldn't have any border unless it's part of the front-end design as well.

Good to know, thanks. It was introduced by me 🤦‍♂ btw it has been already fixed, already on master.
