### ISSUE TITLE
Navigation block: Hover state for first item is lost

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#18354]
**Describe the bug**
When hovering over Nav items, I see a grey left border appear. This is good because it indicates that there's an interaction that can happen. But when I hover over the first item in the Nav block, I don't see any left border. This is probably b/c it's tied in with the left border of the block, but I'm left without a visual hover state.

**To reproduce**
1. Add Navigation block.
2. Add items to the block.
3. Hover over each item.
4. Observe that the first item in the block doesn't have a matching hover state.

**Expected behavior**
I expect the hover state to work on the first nav item as well. I get that it's probably just hidden by the left border of the block, but maybe this can be improved so it's consistent?

**Screenshots**

![nav-hover 2019-11-06 15_44_46](https://user-images.githubusercontent.com/617986/68347975-79bd1b00-00ad-11ea-96b4-165342d8c1fd.gif)

**Desktop (please complete the following information):**
 - OS Catalina
 - Firefox 70.0.1
 - Gutenberg 6.8

**Comment by karmatosed** [comment]
Noting this only happens if you have selected the block, for example, if you haven't selected you see:

![image](https://user-images.githubusercontent.com/253067/69960806-5184d880-1502-11ea-9e0b-9201d2d01262.png)

I would say it could be something to move right by a few pixels to indication, but that then has impacts for CSS if we bring back backgrounds. Feels like a discussion point over needing design right now.

**Comment by mapk** [comment]
I just tested this again and it looks to be resolved when we removed the hover state for all blocks.

![nav-hover 2019-12-17 09_51_08](https://user-images.githubusercontent.com/617986/71021254-cd5e5380-20b2-11ea-889a-1cafc20f9b06.gif)
