### ISSUE TITLE
REST API endpoint for Menu Post Types

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#18373]
Currently there is no way to access Menu `Post` data via the REST API.

This will be required for the enhanced version of the Block placeholder for new Nav Menu Block where you need the option to select from an existing WP Menu. See [here](https://github.com/WordPress/gutenberg/issues/18307) for more context.

**Describe the solution you'd like**
A custom API endpoint in Gutenberg which provides access to data about Menu Post Types.

**Describe alternatives you've considered**
Asking WP Core to add an endpoint seems unlikely.

**Comment by TimothyBJacobs** [comment]
@getdave The REST API team has been working on menu endpoints in [WP-API/menus-endpoints](https://github.com/WP-API/menus-endpoints). Read endpoints are pretty solid. Writes are more a work in progress. 

cc @spacedmonkey.

**Comment by getdave** [comment]
Thanks @TimothyBJacobs!

@kadamwhite @TimothyBJacobs! Would it be possible for you to raise this in the next REST API chat in Slack? 

I'd be interested to learn:

* How likely it is this will be added to Core REST API?
* What indicative timelines are available (if any).
* Whether we've considered adding the endpoint to Gutenberg first as a testing ground?

If possible it would be great if you could update this Issue with the status? I would do this myself but I can't easily attend the 18:00 UTC meeting time.

Very much appreciated.

**Comment by spacedmonkey** [comment]
Hi @getdave 

I am also work on the REST API team and I worked on the feature plugin [WP-API/menus-endpoints](https://github.com/WP-API/menus-endpoints). We have working on / discussing this plugin over 6 months in the REST API core chats in slack. This api was written as a plugin, so that other could test it and once ready, it could become a core patch and end up in WP core. 

What would really help is if you can install the plugin and play around with it. We need to answer these questions. 

Is the data in a workable format for requirements?
Are all required fields in the API?
Do you just need to get data out of the menus or to also create menus ( the plugin does both )?

Once have confirmed this and a need for this API in core, we can start adding polish and unit tests and get it merged in :D

**Comment by draganescu** [comment]
@spacedmonkey what is the exact status of the plugin in terms of available data? Are all the endpoints in the plugin's readme file available or is it work in progress?

**Comment by getdave** [comment]
I'm intending on installing the Plugin and developing the necessary Gutenberg functionality using the new endpoints it provides. Should be a good test.

**Comment by spacedmonkey** [comment]
Is there any chance you could test on this [branch](https://github.com/spacedmonkey/wp-api-menus-widgets-endpoints/tree/feature/validation). I just remember there a couple of notice error on the current master branch. I will work to get this merged ASAP. 

As for the state of the API, we have full CRUD for menus, menu items and menu locations. 
There are 2 PRs outstanding from me 
[Add menu location assignment](https://github.com/WP-API/menus-endpoints/pull/34)  ( used by themes but not useful for this use case). 
[Validation](https://github.com/WP-API/menus-endpoints/pull/31) - Which fixes a number of known issues and make sure types are correct.

Once these are merged and we have feedback from the community / gutenberg team, we can lock down the format of the API. From there, it is a matter of final tweaks, comments and unit tests added. Then we can port the plugin to a core patch. 

Your feedback and input is massively valuable here. If you have issue, do feel free to create issues on the [repo](https://github.com/WP-API/menus-endpoints).

**Comment by getdave** [comment]
I've started testing against this yesterday with [a PR to allow Nav Block item creation from existing Menus](https://github.com/WordPress/gutenberg/pull/18869).

Initially, I found it odd that the `/menus` endpoint did provide info about the Menu items. 

Overall however, it worked 🎉 

Will continue iterating on my PR to further stress test.

**Comment by spacedmonkey** [comment]
@getdave Now that [Validation](https://github.com/WP-API/menus-endpoints/pull/31) is merged, can you use [master](https://github.com/WP-API/menus-endpoints/tree/master) on [WP-API/menus-endpoints](https://github.com/WP-API/menus-endpoints).

Let me know if you need anymore support.

**Comment by draganescu** [comment]
Hey everyone!

Now that the master branch of the` WP-API/menus-endpoints` feature plugin contains what is needed for the navigation block to be developed further, I believe that all the problems, issues and suggestions should be tracked in the [WP-API/menus-endpoints](WP-API/menus-endpoints) repository, until core has them integrated, and [Trac](https://make.wordpress.org/core/components/rest-api/) afterwards.

In light of the above I will close this issue in order to avoid duplicate issues in different repositories.

Thank you 🌮
