### ISSUE TITLE
Social links: Inconsistent clicking behavior 

### ISSUE THREAD

**Issue by mmtr** [WordPress/gutenberg#18370]
**Describe the bug**
When clicking on a social link logo, its position determines the behavior:
- If the logo is to the left of the mover, the address input shows up.
- If the logo is to the right of the mover, the address input doesn't show up.

![Nov-07-2019 13-52-26](https://user-images.githubusercontent.com/1233880/68390592-e693ec00-0165-11ea-88fa-90f81b009772.gif)

**To reproduce**
1. Insert a Social Links block.
1. Click on a logo placed to the right of the mover.
1. Notice how the logo is focused/selected and the address input doesn't show up.
1. Click on a logo placed to the left of the mover.
1. Notice how the logo is focused/selected and the address input shows up.

**Expected behavior**
The address input should be always displayed.

**Comment by jasmussen** [comment]
Good ticket. I would imagine efforts to merge the mover control with the toolbar as imagined in #18667 will help address this.

**Comment by draganescu** [comment]
Thank you @mmtr !

<img width="672" alt="Screenshot 2020-01-09 at 17 58 16" src="https://user-images.githubusercontent.com/107534/72082923-a38efa00-3309-11ea-91fc-b239310715b0.png">

Currently in the master branch the social icons have movers placed in the toolbar and so that solves this issue. Will close.
