### ISSUE TITLE
Navigation Menu: Optionally use arrow for dropdowns.

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#18396]
It'd be nice to allow users to choose whether they want to show an arrow next to navigation items that have a dropdown. Probably off by default.

![image](https://user-images.githubusercontent.com/548849/68474144-f6263a00-0224-11ea-9725-731ee897f845.png)

**Comment by draganescu** [comment]
Should this arrow be customisable by a theme?

**Comment by karmatosed** [comment]
Potentially I can see this as a setting shows on the parent to sub nav link, for example:

<img width="1305" alt="subnavstyles" src="https://user-images.githubusercontent.com/253067/70461104-cd0cf980-1aaf-11ea-8830-66eb5ff0b64a.png">

I am torn though because this also could fit under a style variation.

**Comment by mtias** [comment]
A setting makes more sense to me because a style variation would end up as a complicated matrix: light / with arrow; light / with no arrow; dark / with arrow; dark / with no arrow.

**Comment by karmatosed** [comment]
@mtias sounds reasonable, it could get murky and that was part of reason I was torn. I think maybe then this at least opens it up for other subnav settings or for plugin hooks.

**Comment by WunderBart** [comment]
@mtias @karmatosed I'd suggest a bit different placement and naming of the setting, something like this:

<img src="https://user-images.githubusercontent.com/1451471/72276434-2b3d7700-3630-11ea-947b-d112ee9f5af3.png" width="240">

How does that look?

**Comment by mtias** [comment]
Yes, correct. It should be a setting of the navigation block, not the navigation link.

**Comment by ZebulanStanphill** [comment]
Seeing as that the chevron is a mere stylistic thing, I agree with @mtias that it should be a style variation (or just left to the theme entirely) rather than a dedicated block option.

**Comment by ZebulanStanphill** [comment]
#19601 has been merged, but I'm still not convinced that adding a whole new inspector setting and addition HTML markup was necessary. Are we sure that this could not have been accomplished with CSS `::after` pseudo-element styles and the block styles API?

**Comment by retrofox** [comment]
HI @ZebulanStanphill, thanks for your feedback. We've merged #19601 in order to fix https://github.com/WordPress/gutenberg/issues/18396

> I'm still not convinced that adding a whole new inspector setting ...

It has been discussed, for instance...

[> A setting makes more sense to me because a style variation would end up as a complicated matrix: light / with arrow; light / with no arrow; dark / with arrow; dark / with no arrow.](https://github.com/WordPress/gutenberg/issues/18396#issuecomment-563604230)

> and addition HTML markup was necessary

if you mean to adding an SVG icon, it's similar to the previous one. [It was discussed in the PR, too.](https://github.com/WordPress/gutenberg/pull/19601#discussion_r367894133)

However, we are going to keep working on the new design for sub-menus, and it's closely related to this implementation. Here there is the (draft now) PR https://github.com/WordPress/gutenberg/pull/19681

**Comment by retrofox** [comment]
Sorry, maybe I wasn't clear enough about my previous comment. Just in case, what I attempted to say is feedback is more than welcome, @ZebulanStanphill, in #19681 in order to keep polishing the implementation.
