### ISSUE TITLE
i18n: Include Tannin onMissingKey in i18n public API

### ISSUE THREAD

**Issue by tpaksu** [WordPress/gutenberg#18392]
Is it planned to open `Tannin.options.onMissingKey` method to outside world like `wp.i18n.options.onMissingKey` or something? It would be nice for developers who want to debug their gutenberg translation related stuff, or gutenberg core translators.

**Comment by aduth** [comment]
For context, `onMissingKey` was implemented in Tannin largely to serve the purpose of compatibility with Jed in the offering of a [`@tannin/compat`](https://www.npmjs.com/package/@tannin/compat) package. At the time, I wasn't aware of how this might be used, outside the one example offered in [Jed's documentation](https://messageformat.github.io/Jed/) of "Do something with the missing key e.g. send key to web service".

For what was discussed in #5168, I think there may be some opportunity to consider it in use as a means to substitute a value in place of what would otherwise [return the singular and plural string as defaults](https://github.com/aduth/tannin/blob/e189cff824dff9f8868e5d3d66469bbbfba737d4/packages/tannin/index.js#L215-L217).

I don't have strong reluctance against offering something here in `@wordpress/i18n`, but I'm curious how you might imagine it to be implemented.

If for the majority use-case it's for the purpose of providing fallback strings, I wonder if we could design the API around that.

For example, would something like a third argument `fallbackDomain` on `setLocaleData` be an option? Or a boolean value to defer to the default domain, something like `fallbackToDefault` as the third argument of `setLocaleData`? Or, in a similar suggestion to https://github.com/WordPress/gutenberg/issues/5168#issuecomment-551902476, if we had a way to get locale data back out, could you do something like...:

```js
wp.i18n.setLocaleData( lodash.assign(
  {},
  wp.i18n.getLocaleData( 'default' ),
  myDomainLocaleData
);
```

To me, the last of these ideas would be the least worrisome to commit to, since it seems reasonable to have a "getter" complement to `setLocaleData`.

**Comment by tpaksu** [comment]
There are some cases which `onMissingKey` callback can be useful that came to my mind:

1. One developer can log the missing translations for the custom block and fix them before releasing.

```javascript
wp.i18n.options.onMissingKey = function(singular, domain){
    console.log("Translation missing for", singular, domain);
    return singular;
};
```

2. One can use a different localization package than `wp.i18n` and `Tannin` duo, for example another global array that contains the translations, and return that via `onMissingKey` to the system. But this may need the required modification on the `Tannin.prototype.dcnpgettext` function.

```javascript
var translations = {   
   "my untranslated text": "my translated text",
];

wp.i18n.options.onMissingKey = function(singular, domain){
    return translations[singular];
};
```

3. One can check if a - must have - translated string exists on the `i18n.data` array to check if the domain data is loaded, and if not exists, load the required domain data with setLocaleData before anything goes wrong.

```javascript
wp.i18n.options.onMissingKey = function(singular, domain){
    if(this.i18n.data[domain] === undefined){
        // some logic to load the textdomain,
        // but should be aware of possible infinite loop 
        return wp.i18n.__(singular, domain);
    }
};
```

4. To use a fallback parent domain when a translation isn't found on a child domain, For example, you have a slider block and it's sub-block, slide. And you decided to separate the translation domains because you want to handle them in different git repositories. (Just ignore the slider and slide blocks, they may be some better blocks to give as an example), You may have *slide number* translations in both domains, or you just want to include it in the *slider* domain, and use it inside the *slide* block etc. instead of using *slider-domain* in *slide* package, you can do something like this:

```javascript
wp.i18n.options.onMissingKey = function(singular, domain){
    if(domain == "slide-domain"){
        return wp.i18n.__(singular, 'slider-domain');
    }
};
```

So as you see, just giving the fallback domain would not suffice for any case except the last one. It would save you from further problems because you will give the users a very useful entrance point to put their hacks on and continue their life without another pull request on your translation package, of course, IMHO.
