### ISSUE TITLE
Navigation block item breaks on mobile

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#18401]
**Describe the bug**
When inserting or editing a navigation item on mobile, the toolbar of the menu item breaks on multiple lines.

**Expected behavior**
It should stick to the bottom of the navigation menu block instead of being anchored to the navigation menu item.

**Screenshots**

<img width="310" alt="Screenshot 2019-11-08 at 15 30 56" src="https://user-images.githubusercontent.com/107534/68480809-59709600-023e-11ea-8063-80bc25b102d7.png">

**Smartphone (please complete the following information):**
 - Device: IPhone Simulator

**Comment by getdave** [comment]
> It should stick to the bottom of the navigation menu block instead of being anchored to the navigation menu item.

@draganescu This relates to 

https://github.com/WordPress/gutenberg/pull/18336#issuecomment-551880816

@mtias is there any precedent for this behaviour for nested Blocks' toolbars?

**Comment by karmatosed** [comment]
@shaunandrews looping you in for this as my feelings are we might have to simplify things or at least look at stopping overlaps.

![68602276-f41ae000-049d-11ea-8387-10759e581d09](https://user-images.githubusercontent.com/253067/68606022-6f33c480-04a5-11ea-8d4f-4cd462a1b11f.png)

![68602240-e6fdf100-049d-11ea-9112-2ec2ddda9bd4](https://user-images.githubusercontent.com/253067/68606027-70fd8800-04a5-11ea-9b0d-4ab118d7e69d.png)

![68602206-d64d7b00-049d-11ea-98cc-0c7d90af497b](https://user-images.githubusercontent.com/253067/68606032-72c74b80-04a5-11ea-8b4a-3bf78c1497ca.png)

![68602182-cdf54000-049d-11ea-853d-f1a26e33627f](https://user-images.githubusercontent.com/253067/68606037-7529a580-04a5-11ea-92e9-1f802bdc3630.png)

**Comment by shaunandrews** [comment]
At the _very least_ the Link UI needs to better adjust on mobile screens—perhaps a modal overlay, instead of the positional popover.

In the screenshots above, it seems like some of the spacing and positioning of the toolbar is just plain broken. This doesn't appear to be a problem specific to the Navigation block (though it is definitely impacted) and is more related to nested blocks in general — the toolbar tries to respect the nested paddings/margins.

Instead, I think the toolbar should always be positioned to the left edge of small viewports and likely full-width.

**Comment by frontdevde** [comment]
I just had a brief look at the issue and what seems to happen is the following:

On other blocks, we make use of absolute positioning for the toolbar to appear below the block. That works well for the main toolbar of this block as well but breaks down for the toolbar on the individual items:

![mobile-subnav-current](https://user-images.githubusercontent.com/1562646/68869063-dd23fa00-06f8-11ea-8e5a-bf26975d9822.gif)

That is because for the individual items there are now a few different elements in between that set position relative. We could reset those to the initial state on mobile. That would somewhat work but it breaks down the moment the user would click the button to toggle the item position. The issue there is that the transform creates a new stacking context. So the item changes position during the animation and then jumps to full width the moment the animation stops:


![mobile-stacking-context-issue](https://user-images.githubusercontent.com/1562646/68869968-596b0d00-06fa-11ea-82e9-0d13eaba4a62.gif)

With this in mind, what would probably be the most straightforward solution, for now, is to make each of the menu items full width. This way each block stretches over the full width and the toolbar can just be positioned at the bottom of the menu item just as with any other block.

**Comment by draganescu** [comment]
> make each of the menu items full width on mobile.

Interesting exploration @frontdevde, thank you! I believe this idea above is a good approach since usually navigation at mobile phone breakpoints is indeed stacked.

**Comment by frontdevde** [comment]
We're working on the mobile toolbar over in https://github.com/WordPress/gutenberg/pull/18686. This is what the navigation block looks like on mobile with the current state of that PR.

![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/1562646/69712562-5a8d3880-1103-11ea-9128-91ec013a3ee1.gif)

So if we can land the changes we're attempting to make to the mobile toolbar in general, this should also fix the UX issues we're seeing with the navigation block submenu toolbars.

**Comment by frontdevde** [comment]
Fixed by #18686
