### ISSUE TITLE
Registering an attribute with "integer" or "number" results in problems.

### ISSUE THREAD

**Issue by mintplugins** [WordPress/gutenberg#18406]
**Describe the bug**
When creating a custom block and registering attributes, if you set the "type" to be `integer` or `number`, while the value does save in the wp_posts table, the `props` in the block's `edit` method never get the saved value. 

If you switch the `type` to be `string`, it works properly, with the `edit` method having the saved value.

**To reproduce**
1. Create a custom block and use this to register your attributes:
```
attributes: {
	posts_per_page: {
		type: 'integer',
		default: 10,
	}
},
```
2. Update the value of that attribute using something like this:
`props.setAttributes({posts_per_page: 20})`
3. Click on "Update" and refresh the page.
5. Check your database's wp_posts table for this post, and notice that the value saved in the post_content column is `20`.
4. Back on the Gutenberg editor, notice the value still comes through as `10`, and not `20`.
5. Note that the same thing happens if you attempt to use `number` instead of `integer`.

To get it working you can change "integer" to "string" when registering your attributes, like this:
```
attributes: {
	posts_per_page: {
		type: 'string',
		default: 10,
	}
},
```

**Expected behavior**
I expect the props in Gutenberg to consistently use the saved value regardless of the attribute's defined type.

**Screenshots**
<img width="858" alt="Screen Shot 2019-11-08 at 9 50 22 AM" src="https://user-images.githubusercontent.com/1638128/68485656-aee07f00-020d-11ea-8fe7-e681432ea73a.png">
<img width="288" alt="Screen Shot 2019-11-08 at 9 49 30 AM" src="https://user-images.githubusercontent.com/1638128/68485661-b142d900-020d-11ea-8c78-dae6de8bfa07.png">
<img width="294" alt="Screen Shot 2019-11-08 at 9 52 44 AM" src="https://user-images.githubusercontent.com/1638128/68485668-b3a53300-020d-11ea-9642-ea8d2d9659a4.png">

My guess at the reason here is likely because `wpdb` always returns a string, and Gutenberg is getting a string from the database. Gutenberg likely then checks to make sure the value is an `integer`, which fails, and thus it returns nothing, causing the default value of `10` to be used.

Note that the docs state you can use `integer` or `number` here:
https://developer.wordpress.org/block-editor/developers/block-api/block-attributes/

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser Chrome Version 78.0.3904.87 (Official Build) (64-bit)

**Additional context**
- Gutenberg Version: 6.8.0

**Comment by Christian-Roth** [comment]
Ran into the same problem. But it works for me when using type: 'int'

**Comment by talldan** [comment]
@Christian-Roth 'int' isn't a valid attribute type. What's likely happening when you use 'int' is that the editor falls back to using a string attribute.

@mintplugins Thanks for reaching out. I don't think this can be an issue given there are lots of core blocks that have number attributes, and they'd all be broken (they're not :smile:). An example is the Spacer block, which is very similar to your example. It has a default of height attribute of 100, when I changed its height, the new value is saved successfully as a number. When reloading the post, the spacer still had the updated numeric value:
![Screen Shot 2019-12-16 at 11 52 19 am](https://user-images.githubusercontent.com/677833/70877966-8e6cc700-1ffa-11ea-8de9-284dec9cf5f8.png)

There are a coupe of extra criteria that I'm aware of when using number attributes, though, it might be one of these that's causing the issue:
- There's no type conversion when saving an attribute, so if your attribute is declared as a `number` but its JavaScript type is a `string`, the value won't be saved. The types should be converted prior to being stored:
```js
setAttributes( { myValue: parseInt( updatedValue, 10 ) } );
```
- Be careful when sourcing attributes from html. The issue here is that a value like this on an html tag is a string:
![Screen Shot 2019-12-16 at 11 58 17 am](https://user-images.githubusercontent.com/677833/70878182-67fb5b80-1ffb-11ea-8480-83d499ffa435.png)
Because of the lack of type conversion you can really only use strings when working with html attributes.

**Comment by mintplugins** [comment]
@talldan Converting the type using `parseInt` prior to saving fixed it! Thanks for the explanation.
