### ISSUE TITLE
Disable publishing if document outline or contrast warnings found

### ISSUE THREAD

**Issue by LukaszJaro** [WordPress/gutenberg#18408]
Is there something being worked on that would prevent a end-user from publishing their content if accessibility/outline issues are detected? Or maybe bring it to their attention?

https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/document-outline/index.js

**Comment by tellthemachines** [comment]
Hi @LukaszJaro, thanks for raising this. We have some discussion about this issue [here](https://github.com/WordPress/gutenberg/issues/10581) and a [pull request to address it](https://github.com/WordPress/gutenberg/pull/14889) that needs some follow up. 

I'm closing this issue as a duplicate; please feel free to comment or otherwise participate in the ones I linked to above!
