### ISSUE TITLE
Default input box of ColorPicker not showing on changing alpha value

### ISSUE THREAD

**Issue by WPCurt** [WordPress/gutenberg#18427]
I am following method as suggested in below URL.

https://developer.wordpress.org/block-editor/components/color-picker/

To get better understanding of issue please see this gif.

Unless I change the alpha value there is no problem but after changing the alpha value the inputbox disappears

Please watch this video
[Video link](https://www.screenpresso.com/=1nn8f)

**Comment by ddryo** [comment]
If you change the alpha value of rgba back to 1, the default input box will appear.

![output](https://user-images.githubusercontent.com/31400297/68825188-96280b80-06dc-11ea-9faf-744ea33e1181.gif)

**Comment by jatind93** [comment]
@ddryo 

Thank's for your reply.

But i wan't input box without resetting alpha value.
Is it possible?

**Comment by tellthemachines** [comment]
@WPCurt when the alpha value is set to less than 1, the input for the hexadecimal value disappears because the hexadecimal format doesn't support transparency. So, if you need to use custom alpha values, you're restricted to the `rgba` or `hsla` input options. I hope that answers your question!

Closing as this is the correct behaviour for this component; feel free to reopen if I've missed anything.
