### ISSUE TITLE
Why do the custom HTML block have embed as its keyword?

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#18535]
**Describe the bug**
The custom HTML block ( core/html ) has a keyword of `embed`.
That doesn't make much sense.

**To reproduce**
n/a

**Expected behavior**
Remove the keyword, so it's consistent with other formatting blocks. 

**Screenshots**
![image](https://user-images.githubusercontent.com/2474435/68904214-580b0600-0735-11ea-8aa7-a7b5916c561b.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by mcsf** [comment]
This was added in #2518, 2½ years ago. The context is that this would help discovery of the HTML block in case one has a non-WordPress-supported embed: #2505.

In my experience this doesn't get in the way of finding actual embed blocks via `/` autocompletion, nor via the main Inserter — where block categories are very evident.

I'll close this issue, but feel free to comment if you feel strongly otherwise.
