### ISSUE TITLE
Navigation block: Remove experimental flags

### ISSUE THREAD

**Issue by obenland** [WordPress/gutenberg#18550]
Once #18549 is merged, let's go ahead and remove the `__experimental` flags from the link and navigation components.

**Comment by getdave** [comment]
Some additional context here that could be lost due to the number of Issues and discussions in Core Slack.

The Nav Block has now reached a point where it is usable and stable. There are certainly still improvements to be made but these can be iterated upon. 

The aim now is to promote the Block to a first-class Block citizen. This means merging the Block in a _non_-experimental form.

The Nav Block GH board's "Blocking" column shows the tasks remaining to achieve this. Ideally, we'd want to avoid adding tasks here without speaking with @mtias first.

Once these tasks have been completed we will liaise with @mtias and @youknowriad to see if it's possible to do an early point release of Gutenberg for this Block.
