### ISSUE TITLE
Navigation Block: needs alignment controls

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#18557]
Should support left / center / right for how to lay out the items. It should probably expose a few more flex options within the inspector controls (space between and such).

**Comment by getdave** [comment]
Looking at this one as urgent priority now.

**Comment by getdave** [comment]
Question: are there any existing precendents for having align `wide`/`full` but also `full-left` `full-right`...etc?

I ask because my adding the default alignment attributes as per... 

```js
supports: {
		align: [ 'wide', 'full', 'left', 'center', 'right' ],
}
```

...doesn't afford that level of control. Instead you have to choose one alignment of:

* left
* right
* center
* full
* wide

There is no way to have a nav that is full width and aligned right for example. See below for a (somewhat) illustrative example:

![Screen Capture on 2019-12-03 at 15-16-17](https://user-images.githubusercontent.com/444434/70063722-2ec8f180-15e0-11ea-8ffa-194d7796fecb.gif)

**Comment by ZebulanStanphill** [comment]
Notably, the "align left" and "align right" options are usually interpreted by themes as "float left" and "float right", which is not really appropriate in this use case.

**Comment by getdave** [comment]
Thanks for that @ZebulanStanphill. I didn't full understand that.

I can imagine however, users wanting control over the hoz alignment of items within the Nav Block as a whole. I certainly would! Do you agree?

Therefore do I need to add a custom control for this? What say you @karmatosed?

**Comment by karmatosed** [comment]
I would expect it to depending on the theme have full/wide as that is aa theme setting. I do think left and right alignment is needed for navigation.

**Comment by ZebulanStanphill** [comment]
It would be pretty similar to the text alignment controls on the Paragraph (and some other text-related) blocks, but it might be implemented using flex alignment styles (`align-items`, `justify-content`, etc.) for the Navigation Menu rather than `text-align`.

**Comment by getdave** [comment]
Thanks! So we should: 

* Leave align `wide` and `full` in the `supports` config
* Add custom controls for "item alignment" a bit like `core/paragraph`

I'll add something and you can see what you think, unless anyone would prefer to mockup something first?

**Comment by karmatosed** [comment]
@getdave that sounds like a great path forward to me, don't think it needs mocking.

**Comment by getdave** [comment]
@mtias There is a working PR for this now. As you raised this issue I thought you might like to know.

**Comment by mtias** [comment]
Yes, should definitely use a separate text alignment tool for this, not mixed with wide / full-width.
