### ISSUE TITLE
Text alignment: add 'justify'

### ISSUE THREAD

**Issue by Siguardius** [WordPress/gutenberg#18555]
Hi,
It's been a long time since Gutenberg was incorporated into WordPress and one thing still didn't change. Block editor is missing an option to justify text.

Could you add this option just below left, right and center align?

**Comment by wpfangirl** [comment]
Justified text was removed from WordPress in version 4.7 for accessibility reasons. Because it's difficult to do hyphenation well on the web, justified text often leaves large gaps between words, making it difficult for people with dyslexia (and all the rest of us, really) to read. There are probably some block plugins that add the feature back in, but I wouldn't expect it to return to core anytime soon. Have a look at [this article](http://mediaaccess.org.au/accessibledocumentservice/2015/08/text-justification-is-a-key-accessibility-issue-in-documents/) for some more details.

**Comment by phpbits** [comment]
@Siguardius You can use [EditorsKit](https://wordpress.org/plugins/block-options/) to add Justify alignment and other missing text formats. I hope this helps. Thanks!

**Comment by youknowriad** [comment]
Closing as answered :)
