### ISSUE TITLE
Standardize the buttons :active style across color schemes

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#18577]
The UI buttons have a different `:active` style depending on the active color scheme.

With the default color scheme the only visible changes _while pressing a button_ are:
- a barely noticeable button text change (this could be simplified)
- a border color change:

<img width="828" alt="Screenshot 2019-11-18 at 16 29 54" src="https://user-images.githubusercontent.com/1682452/69066276-4b322f00-0a21-11ea-9d5c-43032004f060.png">

Instead, when an alternate color scheme is activated, the buttons get also the `box-shadow` intended for the focus style. Seems to me this happens because the style for the alternate color scheme doesn't reset the box-shadow to `none` as expected:

<img width="821" alt="Screenshot 2019-11-18 at 16 30 24" src="https://user-images.githubusercontent.com/1682452/69066364-761c8300-0a21-11ea-8e56-0c88fa331a54.png">

In the screenshot above the active color scheme is "Midnight" and I wouldn't expect to see the button border get bigger. I'd expect just a border color change.

Or maybe the opposite :) I'd say the `:active` style should be consistent across the variou color schemes, whatever it is.

It would be great to clarify what the intended style is and make the necessary adjustments, as this is also needed for the buttons in core that need to be fixed for WordPress 5.3.1. See https://core.trac.wordpress.org/ticket/48598

/Cc @jasmussen @karmatosed @melchoyce

**Comment by jasmussen** [comment]
Now that 5.3 is out, it is so lovely to see increasing consistency in the focus styles for buttons and input fields.

It did come together a little fast, especially towards the end. Notably the secondary button style did not, perhaps, receive as much love as it deserved. From your screenshots, for example, the Midnight theme styles them red, which suggests danger, something best reserved for a Trash button. While that can be fixed in the non-default Midnight color scheme, it does feel like this is a problem that is best solved with additional polish to the secondary button. And this would affect how the active-style is designed, because I agree, that should be consistent as well.

@davewhitley designed a secondary button style which in my estimation solves the issue at hand:

<img width="579" alt="Screenshot 2019-11-20 at 09 28 23" src="https://user-images.githubusercontent.com/1204802/69221750-4c29a480-0b78-11ea-8622-6fc734b1e7f9.png">

- Contrasty
- Clearly secondary
- Not affected by admin scheme styles
- Works well with the new unified focus style
- Is conducive to a consistent new active-style. 
- It does not look like an input field because it has the same gray material the old buttons have.

This active style could simply be identical to the one for primary buttons.

**Comment by afercia** [comment]
@jasmussen thanks for your feedback. It's becoming a little hard to coordinate issues between the Gutenberg repo and the WordPress Trac. It requires some effort to keep track of the different conversations going on in two different places. Just noting it because we should probably strive to keep issues and tickets focused on their very specific scope instead of making them broader with consequent overlap between Trac and GitHub.

I'd tend to think the color schemes being applied to the secondary buttons is something that should be discussed by the core design team, as it was implemented after their feedback. It also impacts the whole admin so Trac appears to be the most proper place. See this Trac ticket starting from @melchoyce comment: https://core.trac.wordpress.org/ticket/48585#comment:5

> it has the same gray material the old buttons have

Yep, I'd agree the old grey background appears to work better and it's basically the same thing I proposed on https://core.trac.wordpress.org/ticket/48452#comment:17

However, this issue is specifically about the box-shadow that appears _while_ clicking buttons when a color scheme is activated.

The default color scheme resets the box-shadow for the buttons `:active` style so no additional "outline" appears when clicking the secondary buttons:

https://github.com/WordPress/wordpress-develop/blob/54e2c8ccb0ddd54778115df815e07f6a28b1a5c5/src/wp-includes/css/buttons.css#L149-L155

Instead, the alternate color schemes don't reset the box-shadow. This can be fixed for core but then it should be fixed also in Gutenberg.

**Comment by jasmussen** [comment]
Happy to have this being discussed on Trac and in #design and everywhere appropriate, completely agree. But am I not in the core design team?

I also agree it's important to keep the tickets focused. However in this case I'm suggesting that the _design_ of the button is the best way to solve the issue at hand. Anything else, I feel, optimizes towards something that is best fixed at the source.

**Comment by afercia** [comment]
Everybody is in the design team 🙂I just wanted to note it should be a group discussion on core.

**Comment by jasmussen** [comment]
Absolutely! 👌

**Comment by mapk** [comment]
I'm not sure if this is still an issue. I've added a "needs testing" label.

**Comment by enriquesanchez** [comment]
Here's the same image placeholder from the initial comment in the most version 7.9.0-rc.1 of the Gutenberg plugin, using the Midnight color scheme ('Insert from URL' is being hovered):

<img width="627" alt="Screen Shot 2020-04-14 at 11 46 50" src="https://user-images.githubusercontent.com/3276087/79253011-2a42fe00-7e48-11ea-91c5-1d3b93b59297.png">

**Comment by jasmussen** [comment]
I believe this has been fixed. 

Default:

![default](https://user-images.githubusercontent.com/1204802/79307481-45b91200-7ef7-11ea-811a-8b919e59d5e9.gif)

Midnight:

![midnight](https://user-images.githubusercontent.com/1204802/79307488-4782d580-7ef7-11ea-9dfe-f16383988b6e.gif)

The color schemes should be revisited entirely, but that feels separate.
