### ISSUE TITLE
Conform to standard rich text editor / word processor behavior

### ISSUE THREAD

**Issue by mor10** [WordPress/gutenberg#1858]
## Issue Overview
When writing content in a word processor, certain behaviors are standard and expected. These need to be emulated in Gutenberg to avoid confusion from users who write and edit content in WordPress. A non-exhaustive list is provided below.

## Expected Behavior
- A single press of the Return key produces a new paragraph (block).
- Pressing Shift+Return produces a line break.
- Pressing Return twice breaks you out of a list (ordered or unordered)

## Current Behavior
- A single press of the Return key produces a line break.
- Pressing Shift+Return produces a new paragraph (block).
- Pressing Return twice creates a new paragraph (block).
- Pressing Return twice in a list creates two empty list items.

## Possible Solution
These behaviors are either opposite of or outside of standard expected behavior from a rich content editor, and also run counter to how the current content editor in WordPress works. 

When writing and editing content, Gutenberg should behave like a standard word processor or rich content editor. Creating non-standard output causes the end-user to experience frustration and the perception that something is either wrong or the feature they are looking for does not exist.

**Comment by swissspidy** [comment]
> Pressing Return twice breaks you out of a list (ordered or unordered)

See #1482.

**Comment by mor10** [comment]
Excellent. Then focus of this ticket can be shifted to line/paragraph breaks.

**Comment by mtias** [comment]
Thanks for the feedback. See https://github.com/WordPress/gutenberg/pull/1078 for the initial switch to single line breaks on enter. This is something we wanted to test early on to see how it feels next to the notion of a block per paragraph—specially to those not familiar with the nuisances of line breaks, paragraph breaks, and the shift+enter behaviour.

Word processors are not extremely clear—in terms of visual perception—in how they handle line breaks. See example from Pages:

![image](https://user-images.githubusercontent.com/548849/28219718-3d5c5818-68bd-11e7-97d8-f6f48d1e8518.png)

Both elements look the same to the user given default styles, yet one is a paragraph break and the other is a line break.

This often leads to users doing multiple paragraph breaks when they are not needed. At the same time, the usual expected behaviour above is counter intuitive with how the web handles default paragraph styles (with margins) compared to traditional book layouts or even email clients that generally do a single visual break on enter.

**Comment by mor10** [comment]
I'm confused: right now it looks like hitting Return while inside a block produces a LinkedIn break, as in `<br>`. Is this incorrect? If a single press of Return produces a new paragraph `<p></p>` element, this is not visually clear. 

To clarify: When writing content in an editor, a single press of the Return key should produce a new paragraph element while Shift+Return should produce a line break tag. This is expected behavior. How that relates to blocks is a separate conversation. I'm talking about the HTML output.

**Comment by mor10** [comment]
This issue looks to have been resolved in #1989.

**Comment by karmatosed** [comment]
As this issue has been resolved, closing - if it's not please let me know and we can reopen.
