### ISSUE TITLE
Not able to remove scroll in HTML-block

### ISSUE THREAD

**Issue by ghost** [WordPress/gutenberg#18640]
I updated to WordPress 5.3 several days ago and I see to my horror that the HTML-block has now scroll-function around it in the Gutenberg-editor. How do I remove this scroll-function? This function means that I lose overview over the code – I have to scroll down inside the code-box to see the whole code. Is this a permanent feature that is not possible to remove? I must say WordPress is less and less friendly for those who like to make their own code.

**Comment by youknowriad** [comment]
Hi There! yes, it's a permanent feature because most users have multiple blocks used and the HTML block in the middle of more visual blocks. It's not a pleasant experience when you have all the blob of code shown in the middle of the rest;

That said, it should be possible to tweak the block by loading some CSS in the editor (through your editor styles, or a custom plugin loading a stylesheet in the editor).
