### ISSUE TITLE
Solution for migrating content from classic editor to Gutenberg

### ISSUE THREAD

**Issue by michaelH91** [WordPress/gutenberg#18645]
**Problem**
There is currently no easy way to migrate content (posts and pages) from the classic editor to Gutenberg (which actually works). Unfortunately, this does not make it easier to adapt the block editor for everyone who is still using the classic editor.
In my opinion, the lack of having such an option is a big obstacle for people getting familiar easily with the new editor.

**Approach and possible solution**
I think it would be great to have a button called “Export blog posts (from classic editor)” or something like that at /wp-admin/edit.php.

Process:
a) If you click on it, a separate view in the backend opens. It contains an option for the admin to select either some or all (1-n) blog posts to export. This file then contains the content of the selected blog posts done with the classic editor including all meta data such as title, date published, author, etc.
b) Afterwards, I imagine to have another button at /wp-admin/edit.php named “Import blog posts (for the block editor)” which makes it possible to import the same file again and the magic (migration process from classic to block) happens in the background.

**Alternatives**
Without the need of an export: Just have a button for blog posts saying “Migrate content from classic to block editor”.
The same for wp-admin/edit.php?post_type=page.
Lastly, instead of putting that into core, it might be a good idea to have a separate plugin for that process.

**Comment by paaljoachim** [comment]
Hey @michaelH91 Michael

I apologize that we overlooked your issue.

Being able to export classic editor posts with title, date published, author etc. Seems like a very good plugin idea.
Perhaps some plugins that do export/import will add this feature.

I am thinking that we can close this issue for now. As it sounds more like an idea for a plugin than something that will be added to Gutenberg plugin.

Have a great day!

**Comment by paaljoachim** [comment]
I posted about this issue on a Facebook WordPress Gutenberg Community.
https://www.facebook.com/groups/gutenberghub/permalink/2882182835347553/

One reply went like this:
Is the issue that you want to convert more than one block at a time?
If so there is the Bulk Block Converter (https://wordpress.org/plugins/bulk-block-converter/) which uses Gutenberg's transformation engine. It works fine for smaller sites, as you need to keep the browser open during the transformation. Gutenberg's transform has a few issues, but overall it's solid.

Another option is Bulk Convert to Blocks (https://bulkconverttoblocks.com/). Full disclosure: I've written this plugin. It's a ground up rewrite of conversion code that I've used on several large client projects.
The difference between this plugin and the one mentioned above is in the philosophy:
1. Gutenberg's conversion can be lossy, whereas this plugin will try and maintain as much as possible. I prefer to keep HTML and not transform to blocks, rather than lose content in the process.
2. There is no support for third party plugins in Gutenberg, like transforming their shortcodes into their blocks (Jetpack, WP Forms, WooCommerce,...). This plugin could do that easily with an extension.
3. The conversion is PHP based, so developers could implement their own converters. Or use actions and filters. This is different from Gutenberg, which is entirely JavaScript based.
4. This is made for true bulk conversion. With WP CLI, you can convert thousands of posts with no issues.
It's still early, as I'm in the process or ironing out a couple of issues. But the plugin is close to having feature parity with Gutenberg's converter.
There's a lot of potential here. But I'm unsure about how many people find such a plugin useful. Maybe it's a niche tool? Or not? Let me know.
Because if enough people are interested, I will invest more time in making the plugin more feature rich, and useful for more people.

**Comment by paaljoachim** [comment]
For more information see the WPTavern article by Justin: 
https://wptavern.com/ask-the-bartender-how-to-bulk-convert-classic-wordpress-posts-to-blocks

**Comment by rafaucau** [comment]
> https://bulkconverttoblocks.com/

@paaljoachim The link to your plugin is not working. Is the project abandoned?

**Comment by paaljoachim** [comment]
Hey @rafaucau 
I have no idea..... (Not my plugin though. I just linked to it.)

**Comment by scrobbleme** [comment]
[Convert to Blocks](https://wordpress.org/plugins/convert-to-blocks/) has a WP CLI command for bulk conversion.
This basically opens an editor, does its "magic" and opens the next post.

We have a project with > 8000 "classic" posts, we need to bulk convert. 
There really is the need for such a tool.

**Comment by mtias** [comment]
It's better to use plugins for bulk updating, but we have this planned for core: #64129
