### ISSUE TITLE
Button Component isDestructive not showing red text-based style as indicated

### ISSUE THREAD

**Issue by SpencerCloud** [WordPress/gutenberg#18674]
Creating a Button using the WP component and specifying isDestructive to "true" doesn't change the style to the expected red outline and red text as indicated in the [documentation](https://developer.wordpress.org/block-editor/components/button/).

`el(
    Button,
    {
        isDestructive: true,
    },
    'Delete Slide',
),`

The above code yields the following HTML:

`<button type="button" class="components-button is-destructive">Delete Slide</button>`

Even though is-destructive is a class in the HTML, it looks like text.

**Comment by devdivdev** [comment]
@SpencerCloud 
Looking at the style file, it only makes the text red when the button is a link, not sure if this is how it was intended.
`&.is-link.is-destructive {
		color: $alert-red;
	}`
Because applying the _is-destructive_ to a button will makes it look a little bit weird. 
![Screenshot_1](https://user-images.githubusercontent.com/19231421/69466305-f88ba680-0d83-11ea-9387-16b7d673a135.png)

**Comment by enriquesanchez** [comment]
There are design guidelines for the different button types in the [WordPress Components library](https://www.figma.com/file/ZtN5xslEVYgzU7Dd5CxgGZwq/WordPress-Components?node-id=5208%3A742) ([link requires Figma access](https://make.wordpress.org/design/handbook/workflows/figma-access/)).

These are the styles for destructive buttons:

<img width="1157" alt="Screen Shot 2020-03-17 at 11 58 53" src="https://user-images.githubusercontent.com/3276087/76886842-f378c880-6846-11ea-85fd-fc6a891f52e2.png">
