### ISSUE TITLE
Changing navigation link doesn't update the label

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#18695]
**Describe the bug**
When changing the link of a navigation menu item to a post or page the label of the link does not update to the one of the selected post or page.

**To reproduce**
1. Make a post
2. Add an empty navigation menu
3. Add a navigation item by searching for a page
4. Observe the label
5. Click on edit link button and then on change
6. Search for a different page
7. Select it
8. Observe the label: bug.

**Expected behavior**
The new selected page or post should be reflected by a new label.

**Screenshots**
![menu-label-not-updating](https://user-images.githubusercontent.com/107534/69438786-5d2c0e80-0d4e-11ea-9c05-4a202c05c3f6.gif)

**Comment by retrofox** [comment]
Although I think you're right, I'm not 100% sure that this behavior wasn't to desired. AFAIK, the link label is populated from the page title [only if it is not defined](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/navigation-link/edit.js#L68). Guessing it was the intended behavior in order to keep the previous label, that btw may be defined explicitly b the user.

**Comment by melchoyce** [comment]
My first instinct is “that’s a bug.” If I’d manually changed the label, I’d see maybe keeping it.
But if I add and then replace without manually editing the label, I expect it to totally replace the previous menu item.

**Comment by karmatosed** [comment]
I also feel like this is a bug when experiencing it so it might be worth fixing as a result.
