### ISSUE TITLE
Richtext component tabs the user out of field after one keystroke

### ISSUE THREAD

**Issue by martinowren** [WordPress/gutenberg#18702]
**Describe the bug**
Richtext component tabs the user out of field after one keystroke
Video of the bug can be found here: https://youtu.be/yIH3-tsyiDI

Gist code: https://gist.github.com/martinowren/b6c8993d9b72e9b61d605b3832690811

**To reproduce**
1. Add the block
2. Click on 'Legg til partner'
3. Click on the richtext component and try to do multple keystrokes

**Expected behavior**
The user should be able to write coninusly 

**Desktop (please complete the following information):**
 - OS: Windows WSL ubuntu
 - Browsers: all major browsers

**Comment by talldan** [comment]
@martinowren Thanks for getting in touch. This looks like a bug with your code rather than RichText. I realise you may have solved this in the meantime, but I'll explain anyway.

The crux of the issue is that you have the `PartnerCard` component declared in the body of the `edit` function. Everytime `edit` runs, the `PartnerCard` component is redeclared as a new component. This means that React cannot reconcile that component, and so it's replacing it in the DOM every time, and that's causing the caret to lose its position.

The fix I came up with was to extract `PartnerCard` outside of the `edit` function. That means you can't access some of the edit state through a closure, so a bit of refactoring was needed ... in the end my `PartnerCard` looked a bit like this:
```
const Partnercard = ( props ) => {
	const { onChange, value } = props;

	return (
		<div className={ 'flex-children' }>
			<div className={ 'partnercard' }>
				<div className={ 'aligner' }>
					<RichText
						className={ 'heading' }
						tagName="p"
						placeholder="Navn på partner."
						value={ value }
						onChange={ onChange }
					/>
					<img className={ 'partner-logo' } src={ 'https://russemerket.no/wp-content/uploads/2019/06/russemerketlogo.png' } alt={ 'alt-text' }></img>
				</div>
			</div>
		</div>
	);
};
```

and is used like this:
```
{ partnerObj.map( ( partner, index ) => {
	return (
		<Partnercard
			key={ index }
			value={ partnerObj[ index ].caption }
			onChange={ ( newVal ) => {
				setAttributes( {
					partnerObj: [
						...partnerObj.slice( 0, index ),
						{
							index,
							caption: newVal,
						},
						...partnerObj.slice( index + 1 ),
					],
				} );
			} }
		/>
	);
} ) }
```

One other change I made was to use the `tagName` prop on the `RichText` component and replace the surrounding `<p>` tag. That was because `RichText` outputs a `div` by default, and it's invalid to nest a `div` in a `p`.

Hope that helps.
