### ISSUE TITLE
SelectControl: value as object

### ISSUE THREAD

**Issue by mahnunchik** [WordPress/gutenberg#18706]
**Is your feature request related to a problem? Please describe.**

Allow to have value as object, not only as primitive types.

Object is converted to `[object Object]` for now.

**Comment by talldan** [comment]
@mahnunchik It looks like `SelectControl` is just a thin wrapper around the native `select` element, so that's why it doesn't support objects—the value is passed straight through to the `select` and that's what doesn't handle objects.

I think your best option would be to create your own component based on `SelectControl` that handles converting those objects to values.

I'll close this issue as I can't see any reason this shouldn't be possible.
