### ISSUE TITLE
Styles that are wrapped with editor styles wrapper are not cached

### ISSUE THREAD

**Issue by jorgefilipecosta** [WordPress/gutenberg#18741]
The mechanism we have to wrap styles with editor styles wrapper is to pass a string with the content of the stylesheet via editor settings and then Gutenberg changes this string before adding it to the dom as a style element.
This solution has a problem, the styles are not cached by the browser, the string with the styles is passed every time the editor loads.
These styles include styles implemented by the theme and can have a considerable size.
I think we should enqueue these styles normally so they are cached by the browser. On settings, we should pass identifiers of the stylesheets that should be rewritten (e.g: the path) on Gutenberg we should dynamically change the stylesheets to wrap them.

**Comment by nosolosw** [comment]
I was thinking about this and found this issue and the corresponding PR https://github.com/WordPress/gutenberg/pull/18763

It looks like this is a dead-end because we can't rely on finding the stylesheet due to some hosts dequeuing the defaults and then concatenating different stylesheets together to server them through CDNs. Is that correct? If we can't rely on the existence of stylesheets, is there any other alternative to pass it through the editor settings? I can't think of any, so perhaps we can close this?

**Comment by jorgefilipecosta** [comment]
Yes, let's close the issue.
