### ISSUE TITLE
Notices: Editor notice margins appear conflicted with theme background color

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#18762]
**Describe the bug**

If a theme defines an editor background color, the existence of a notice in the editor will create an undesirable gap of white.

![image](https://user-images.githubusercontent.com/1779930/69651172-afff1200-103d-11ea-98f5-6f740a7bd988.png)

**To reproduce**

1. Activate a theme which has an editor background color (e.g. TwentyTwenty)
2. Navigate to Posts > Add New
3. Open your browser's [Developer Tools Console](https://developers.google.com/web/tools/chrome-devtools/open), then add the script:
   - `wp.data.dispatch( 'core/notices' ).createInfoNotice( 'Hello World!' )`

**Expected behavior**

Any space between notices and the editable content should be seamless (inherit background color).

**Desktop (please complete the following information):**

 - OS: macOS Catalina 10.15.1 (19B88)
 - Browser: Chrome Version 78.0.3904.108 

**Additional context**

Originally observed at https://github.com/WordPress/gutenberg/pull/18732#issuecomment-558703398

My first intuition was to remove the margin from the last notice in the set. However, there are two issues with this:

- The margin should be preserved between the last notice of the "pinned" collection, and the first notice of the "dismissible" collection
- I would expect that even the intentional margins between notices should have the theme background color show through.

Possible solutions:

- Remove the margins altogether (use borders instead to create seams between notices?)
- Move notice rendering into `.editor-styles-wrapper` element (the element which receives the theme styling)

**Comment by richtabor** [comment]
Yup, it's from a margin-bottom of `5px` added by the `.components-notice` styling indeed. With multiple notices involved, here's what we have now:

<img width="1164" alt="Screen Shot 2019-11-26 at 12 59 36 PM" src="https://user-images.githubusercontent.com/1813435/69659677-b3e66080-104c-11ea-9fd8-89ba8a3a847a.png">

If we move the notices into the `.editor-styles-wrapper` element as is, they'd overlap the `.editor-post-title` element, causing a conflict there. Perhaps a border, or inset box-shadow, could be a simpler implementation.

<img width="1163" alt="Screen Shot 2019-11-26 at 1 00 14 PM" src="https://user-images.githubusercontent.com/1813435/69659758-df694b00-104c-11ea-8561-60f2c33c021d.png">
<img width="1164" alt="Screen Shot 2019-11-26 at 1 04 07 PM" src="https://user-images.githubusercontent.com/1813435/69659924-3cfd9780-104d-11ea-9659-3b0c432fbab7.png">

**Comment by richtabor** [comment]
Here's with setting`.components-notice` margin to `0` and adding `border-bottom: 1px solid rgba(0, 0, 0, 0.15)` to the notice (including the first one, which makes the notice feel part of the UI a bit more). I chose that border-bottom color to match the `.edit-post-header` border with transparency, so that it does that clash with notice colors. 

<img width="1218" alt="Screen Shot 2019-11-26 at 1 09 23 PM" src="https://user-images.githubusercontent.com/1813435/69660298-fbb9b780-104d-11ea-9592-046aa8ee01d4.png">

### And here's the same, but with two notices:
<img width="1217" alt="Screen Shot 2019-11-26 at 1 11 55 PM" src="https://user-images.githubusercontent.com/1813435/69660442-56531380-104e-11ea-8503-c6024ede0f09.png">

### Info notices:
<img width="1218" alt="Screen Shot 2019-11-26 at 1 12 21 PM" src="https://user-images.githubusercontent.com/1813435/69660479-6b2fa700-104e-11ea-9e9d-6194e1eace8b.png">

### Error notices:
<img width="1218" alt="Screen Shot 2019-11-26 at 1 12 59 PM" src="https://user-images.githubusercontent.com/1813435/69660506-7d114a00-104e-11ea-97a3-82c251290609.png">

**Comment by aduth** [comment]
@richtabor I'll of course defer to your judgment (and any other designers who might weigh in), but from my perspective, your proposed border seems nicer to me even than the original design was going for with the margins. There's a nice consistency with borders used elsewhere in the UI (with that in mind, should it be the exact color of other borders, if not already?).

Seems to me like a nice way to fix the issue 👍

**Comment by richtabor** [comment]
>  ...but from my perspective, your proposed border seems nicer to me even than the original design was going for with the margins. 

100%, totally agree.

> There's a nice consistency with borders used elsewhere in the UI (with that in mind, should it be the exact color of other borders, if not already?).

Yea, we can try - it's worth exploring. There may be a bit of clash with a gray border against the notices (as they hold a background color), which is why I went transparent. For reference, the `0 0 0 1px rgba(0, 0, 0, 0.2)` I mocked here is also used within the `ColorPaletteControl` component, as those button elements have background colors as well. 

<img width="267" alt="Screen Shot 2019-11-26 at 1 39 46 PM" src="https://user-images.githubusercontent.com/1813435/69662360-37ef1700-1052-11ea-846e-38b75c897423.png">

**Comment by aduth** [comment]
> There may be a bit of clash with a gray border against the notices (as they hold a background color), which is why I went transparent.

Huh, I clearly needed to brush up on my understanding of how borders and backgrounds interact ([CodePen](https://codepen.io/aduth/pen/povorda)), since I was under the impression it wouldn't matter if the border was _outside_ of the content/background area. But yes, I can see now why a semi-transparent black would likely clash less than a static gray border.

**Comment by aduth** [comment]
>For reference, the `0 0 0 1px rgba(0, 0, 0, 0.2)` I mocked here [...]

Can you clarify, since your [first comment](https://github.com/WordPress/gutenberg/issues/18762#issuecomment-558751676) mentioned using a `border-bottom`, but the syntax you mention here now (and in use by `ColorPaletteControl`) is a `box-shadow`; should we be using a border or box shadow?

**Comment by richtabor** [comment]
> > For reference, the `0 0 0 1px rgba(0, 0, 0, 0.2)` I mocked here [...]
> 
> Can you clarify, since your [first comment](https://github.com/WordPress/gutenberg/issues/18762#issuecomment-558751676) mentioned using a `border-bottom`, but the syntax you mention here now (and in use by `ColorPaletteControl`) is a `box-shadow`; should we be using a border or box shadow? I would imagine a border should be sufficient?

Oh sorry about that! I was referring to the `rgba` value being the same. A `border-bottom` would work great here.

For clarification:
1. The screenshot below is using a `border-bottom` the same value as the `edit-post-header`:
<img width="484" alt="Screen Shot 2019-12-02 at 2 08 35 PM" src="https://user-images.githubusercontent.com/1813435/69987361-60bd5380-150d-11ea-9c7c-7f8758515317.png">

2. While this screenshot is using a `border-bottom: 0 0 0 1px rgba(0, 0, 0, 0.125)` (which adds more contrast between elements and fits in better with the contrast from the `edit-post-header` border-bottom. I'd say this works much better.
<img width="496" alt="Screen Shot 2019-12-02 at 2 09 02 PM" src="https://user-images.githubusercontent.com/1813435/69987356-5a2edc00-150d-11ea-8373-842d7666ede7.png">

**Comment by aduth** [comment]
Thanks for clarifying. In #18871, I went with `border-bottom`. I used `0.2` as the alpha though. That's different from what you're suggesting in your latest comment, but per your comment about "the `rgba` value being the same", the color palette and friends use `0.2` as well, not `0.125`.

**Comment by richtabor** [comment]
> ...the color palette and friends use `0.2` as well, not `0.125`.

Yea, I was playing around with the `rgba` to see if I could get the contrast visually similar to what the `.editor-post-header` provides. Both work fine. 👩‍🎨
