### ISSUE TITLE
Allow a "duplicate and detach" to use reusable blocks as templates

### ISSUE THREAD

**Issue by Julianoe** [WordPress/gutenberg#18814]
**Is your feature request related to a problem? Please describe.**
I have a group of blocks added into the reusable blocks.
I want to change one of the instances of the reusable blocks, so it becomes different from the other ones.

If i do “remove from reusable blocks” this deletes this instance but also the reusable blocks from all my website, and I don’t seem to be able to copy-paste the content of a reusable block. What happens then????

The reusable block is an extremely complex and large group of blocks… but if i want to do a variation of it i’m forced to redo it all by hand??? I think there could be a better way for this use case.

I should add that this use case appeared to me when i prepared reusable group of blocks for a non developer user so that they could use the reusable blocks as "templates".

**Describe the solution you'd like**
I briefly exchanged on the subject with @karmatosed [here](https://wordpress.org/support/topic/how-to-edit-reusable-blocks/#post-12147032). We think a good solution to that would be to allow the possibility to **duplicate and detach** so that a reusable group of blocks can then be used as a separate one from the source.

I hope this issue is clear enough. Otherwise i'm willing to explain furthermore. Let me know.

**Comment by talldan** [comment]
Hi @Julianoe. Yep, what you describe seems like a pretty common workflow, and it seems like there's already been some thought around this kind of functionality in issue #8403.

The main way to achieve what you're describing at the moment is to use the 'Convert to Regular Block(s)' option, make changes, and then create a reusable block again so that you have two variations.
![Screen Shot 2020-01-24 at 2 35 13 pm](https://user-images.githubusercontent.com/677833/73049239-e37fe080-3eb6-11ea-9daf-67313c65c478.png)

I'll close this in favour of #8403 as that already has quite a bit of suggestion.
