### ISSUE TITLE
Link interface unification using one in navigation block

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#18833]
There is a new link interface being used for navigation:

![image](https://user-images.githubusercontent.com/253067/69887105-2f5e4100-12dd-11ea-938c-5e9210dd6e84.png)

Whilst the #17557 was closed this only brought it into navigation. I would like to see it replacing the one also used anywhere else. Unfortunately, right now we have 2 ways to add links so let's fix that.

**Comment by noisysocks** [comment]
> Unfortunately, right now we have 2 ways to add links so let's fix that.

We have four by my count! 😀 Soon to be five if https://github.com/WordPress/gutenberg/pull/18139 is merged.

Paragraph block:

<img width="311" alt="Screen Shot 2019-12-05 at 16 39 56" src="https://user-images.githubusercontent.com/612155/70250674-8e5d0380-177e-11ea-965b-bac3c2772973.png">

Image block:

<img width="318" alt="Screen Shot 2019-12-05 at 16 40 29" src="https://user-images.githubusercontent.com/612155/70250675-8e5d0380-177e-11ea-9d53-b8ab4376e55f.png">

Navigation block:

<img width="381" alt="Screen Shot 2019-12-05 at 16 41 04" src="https://user-images.githubusercontent.com/612155/70250676-8ef59a00-177e-11ea-921e-9f668192c717.png">

Button block:

<img width="236" alt="Screen Shot 2019-12-05 at 16 42 05" src="https://user-images.githubusercontent.com/612155/70250678-8ef59a00-177e-11ea-8d0f-e65a4e4d6db4.png">

**Comment by phpbits** [comment]
Do you have any link for the documentation on how to extend the new interface? Thanks!

**Comment by noisysocks** [comment]
@phpbits:

There is a little documentation on the `LinkControl` component (which is what the Navigation block uses) here:

https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/link-control/README.md

**Comment by noisysocks** [comment]
Just thinking through what might be involved here:

- Need to update the built-in `link` format (`format-library/src/link/index.js`) to use `LinkControl`.
- Need to update the Image block to use `LinkControl`.
- Potentially should also update the Button block to use `LinkControl`.
- Potentially should deprecate the old components (`URLInput`, `URLPopover`, etc.)

There's no need to do everything at once. We can start small and iterate.

`LinkControl` will also need to be updated to support more than just checkbox settings so that the Image block can show the _Link Rel_ and _Link CSS Class_ settings. For this I would suggest replacing the `currentSettings` prop with an API designed around composition, e.g:

```js
<LinkControl currentLink={ ... } onLinkChange={ ... }>
	<LinkControl.ToggleSetting title="Open in new tab" onToggle={ ... } />
	<LinkControl.TextSetting title="Link rel" value="" onToggle={ ... } />
	<LinkControl.TextSetting title="Link CSS class" value="" onToggle={ ... } />
</LinkControl>
```

**Comment by karmatosed** [comment]
Closing this one as making individual issues for each area that needs this.

**Comment by phpbits** [comment]
@noisysocks Any updates on how we can add extra controls on the Link popover? Planning to add extra 'trash' icon at the bottom to remove link. Thanks!

<img width="381" alt="Screen Shot 2020-05-31 at 11 33 08 PM" src="https://user-images.githubusercontent.com/3365507/83356215-17a06c00-a397-11ea-99ff-dca9f9bce9a6.png">
