### ISSUE TITLE
Table Block: Toggling Header/Footer rows results in lost data

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#18919]
When working with a table block, I found that toggling the Header/Footer sections can lead to a loss of input data. To reproduce, try this:

1. Add a table block to your document.
2. Turn _on_ the Header section from the block sidebar.
3. Add text to any Header section cell.
4. Turn _off_ the Header section from the block sidebar.
5. Turn _on_ the Header section from the block sidebar.

After toggling the Header, I'd expect the text added to the Header cell to be retained. Instead, the text is removed and all cells are no empty.

![table header toggle](https://user-images.githubusercontent.com/191598/70169483-e3bee500-1698-11ea-9875-aab100fdf740.gif)

**Comment by talldan** [comment]
> After toggling the Header, I'd expect the text added to the Header cell to be retained. Instead, the text is removed and all cells are no empty.

Thanks for creating the issue. For some background, this was discussed pretty extensively in the initial PR and the decision was that is wasn't needed since undo/redo work for restoring the data:
https://github.com/WordPress/gutenberg/pull/15409#issuecomment-490180676

Given that, I'm going to add the `Needs decision` label. Perhaps it'd be something you could raise as a point in one of the design meetings, @shaunandrews?

**Comment by ntsekouras** [comment]
Hey @talldan and @shaunandrews! Had you discussed this back then in a design meeting or somewhere else?

Since there is an alternative with `undo` and there were no other references about this since then, should we close this issue and the respective PR?

**Comment by shaunandrews** [comment]
I'd still consider this an issue, but I might be alone. I'll close it myself as it doesn't seem like there's much to do here.
