### ISSUE TITLE
Using the up arrow key to navigate to parent blocks no longer works properly

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#18928]
## The issue
Pressing the up arrow key while your selection is on the first child block of another block should navigate to the parent block. At some point this behavior seems to have been broken and no longer works properly in `master`. This was working properly in Gutenberg 7.0.0.

I suspect this issue may be related to #18780 and #18881.

## How to reproduce
1. Create a new post.
2. Insert a Group block.
3. Insert any block inside the Group block.
4. Press the up arrow key. Notice that you don't navigate to the Group block.
5. Press the up arrow key again. Notice that you navigate to the post title, skipping the Group block entirely.

## Environment
- WordPress 5.4-alpha-46814
- Gutenberg `master` as of https://github.com/WordPress/gutenberg/commit/49dac29050c054056746cd861c0d2c2e2146d68a
- Using Dissenter browser 0.70 (based on Chromium 78)

**Comment by ellatrix** [comment]
Whatever fixes it should add an e2e test.

**Comment by aduth** [comment]
Appears to have been introduced by #18379

**Comment by aduth** [comment]
Fix proposed at #19135.

> Whatever fixes it should add an e2e test.

As noted in the description of #19135, we do have an end-to-end test which attempts to verify this behavior ([source](https://github.com/WordPress/gutenberg/blob/112816a3c7cf05614460547d500c259c1eb6568a/packages/e2e-tests/specs/editor/various/writing-flow.test.js#L18-L88)). However, because it relied on the DOM as the source of truth, and because the active element in the DOM _was_ correct (despite it showing the wrong block's toolbar), the tests would pass. In #19135, I've updated the test to assert against both the DOM and the block editor state.
