### ISSUE TITLE
Social Block: Update alignment controls

### ISSUE THREAD

**Issue by obenland** [WordPress/gutenberg#18951]
#18909 added ~alignment~ justification settings to the Navigation block. Let's update the Social Links block with those same settings.

Currently those settings are a little buggy, losing the border around the block and adding some margin.

![2019-12-02 20 52 47](https://user-images.githubusercontent.com/1398304/70267085-92732c00-1752-11ea-8bca-77caeb8761da.gif)

**Comment by mtias** [comment]
_Buttons_ should also probably use this alignment control group: https://github.com/WordPress/gutenberg/pull/17352

**Comment by getdave** [comment]
In which case do you think we should extract a `BlockJustificationToolbar` for all these use cases?

**Comment by ZebulanStanphill** [comment]
Just to be clear, the lack of block border is (kinda) intentional. The so-called `alignleft` and `alignright` options are really float left and float right options (at least in most themes, anyway; some themes like Twenty Twenty pull the content into a separate column outside of the flow of the rest of the post content). Rendering the block border and controls around floated blocks is complicated, so the compromise that was made was to just not render the border.

**Comment by ZebulanStanphill** [comment]
Personally, I think the block align toolbar is poorly named, since only the `aligncenter` option is an actual alignment. `alignleft` and `alignright` are floats and `alignwide` and `alignfull` are almost like "anti-floats".

**Comment by getdave** [comment]
I'm working on a PR for this. Will push up shortly.

**Comment by jasmussen** [comment]
Coming back to this one, I believe this issue has been fixed:

![align and justify](https://user-images.githubusercontent.com/1204802/110371343-236b3e00-804d-11eb-848f-a744205fc224.gif)

So closing as such, but please reopen if this was in error!

**Comment by gwwar** [comment]
@jasmussen closing this one for you :D

**Comment by jasmussen** [comment]
Thank you :)
