### ISSUE TITLE
Sidebar double scrollbar

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#1899]
In some operating systems, scrollbars aren't "overlaid" on the screen but they do take space. This happens also on Windows 10, where _all_ browsers display a double scrollbar when the scrollbar height exceed the viewport height. That's likely going to happen when opening the categories panel for example (since there are usually lots of categories) and also on small screens.

Worth noting the double scrollbar is there also on macOS, you just can't see it most of the times. Just resize your browser window to make it smaller and open some panels in the sidebar.

![scrollbars](https://user-images.githubusercontent.com/1682452/28209616-8df303e6-6893-11e7-890d-5bbb9f5c35b6.jpg)

Maybe worth considering alternative solutions to `overflow: auto;`.

**Comment by jasmussen** [comment]
Also this:

![screen shot 2017-07-28 at 09 15 29](https://user-images.githubusercontent.com/1204802/28706596-541baafa-7375-11e7-80a7-4bb69074f9b1.png)

Another solution is to _double down_ on `overflow: auto;`, so that the `html` element doesn't scroll, but indeed the main editable field scrolls instead. This could also help solve issues with `position: fixed;`, as well as scroll bleed (see #656), which is extra annoying on mobile. 

The reason we didn't approach it this way from the start, is that in past versions of iOS, scrolling anything but the HTML element had really weird quirks. But this seems to have been fixed in recent versions of mobile Safari. CC: @mtias — what do you think?

**Comment by afercia** [comment]
Update: in Firefox and Edge on Windows, 1366x768 display I can see now 3 scrollbars:

![screenshot 27](https://user-images.githubusercontent.com/1682452/28942127-7c5a740e-789a-11e7-8480-331a4e1ada61.png)

**Comment by jasmussen** [comment]
I've _occasionally_ seen a double scrollbar even in Safari. That is, it feels like some of the negative margin on the `component-panel` combined with an overflow somewhere might cause an extra scrollbar that shouldn't be there. So I think if we fix that one, we should be back down to two.
