### ISSUE TITLE
Iterate on social block placeholder

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19020]
Currently, the starting point of social links is a lot visually:

![image](https://user-images.githubusercontent.com/253067/70458140-65ec4680-1aa9-11ea-8212-7469a25b2796.png)

Considering what the other placeholders have, it might be nice to reduce the options and have a starting step. Here, for example, are the columns and navigation ones:

![image](https://user-images.githubusercontent.com/253067/70458189-7ef4f780-1aa9-11ea-8f2b-296b69f68abf.png)

**Comment by jasmussen** [comment]
Thanks for the ticket. I would definitely welcome help improving this block.

Currently I personally believe the setup state a.k.a. "placeholder" is the biggest issue, and rightly what this ticket should probably focus on.

One design principle that may be worth remembering here is to move closer to what you'll see on the front-end. The gray blob placeholder has no indication what the end result will look like. Imagine a page template that features a gray blob Social Links placeholder towards the end — users will likely mistake it for an Image. 

It works better for the Image block and other literally big-footprint blocks, because the gray blob is a callback to desktop publishing placeholders, where you'd draw a big square with a cross in it to indicate to the layouter that _this spot should be filled by an image yay big_. 

Social links, when properly configured, will look like colored candy-beans in a row, which is very unlike the gray blob. **This is what has informed the current setup state for Social Links**: 6 blocks pre-inserted, one of them configured. 

As we explore improving this, I would recommend looking at the Coblocks block called Social Profiles. I would call it the gold standard for a social links block setup state:

![coblocks](https://user-images.githubusercontent.com/1204802/70507911-a1305900-1b2d-11ea-9e89-b664a65864de.gif)

Some notes on that:

- Coblocks does not use child blocks, so it’s only got 8 links and they are hardcoded and can’t be rearranged, and it can’t be made plugin extensible
- Social Links uses child blocks, which means blocks can be rearranged, deleted, preinserted, preconfigured, and extended by plugins (once #17278 and #17277 are addressed).
- It also means that all the clunky UI from child blocks encumber the block: what has focus? How do I delete the block? Those movers are clunky (also #18370). What does the left border indicate?

We know that child blocks will be used in many many more places, for example the Quote block or the Gallery block, where paragraphs and images inside would benefit from being direct manipulation and easy to rearrange with separate consistent mover controls.

So it's worth noting that iterating the child block UI, will benefit every block that uses child blocks, including blocks very similar to this one, such as the Navigation block and the Buttons (plural) block. 

- Selecting parent blocks is still being improved, most recently with edit/select tools.
- #18370 aims to explore better focus rectangles to clearly indicate what actually has focus, and not necessarily paint borders around the child block just because the child block is being edited.
- A detached toolbar can be more contextual and out of the way of the block being edited.
- Mover controls being absorbed by the toolbar can lighten the UI in such a small space.
Most importantly, any positive change to child blocks benefits every block already using it, including Navigation Block.

**Comment by mapk** [comment]
I took a look at a few reasons why our Social Links block doesn't present the best initial set up state and came up with some ideas.

### 1. Initial State 
When adding the block to the page, we drop the user right into a nested block which isn't how the CoBlocks version works. This may be the cause to some confusion.

**Core Social Links block (initial state)**

![Screen Shot 2019-12-26 at 1 02 25 PM](https://user-images.githubusercontent.com/617986/71490579-4743ba80-27e0-11ea-8a9a-a7284a1287bb.png)

**CoBlocks Social Profiles block (initial state)**

![Screen Shot 2019-12-26 at 1 01 32 PM](https://user-images.githubusercontent.com/617986/71490594-5c204e00-27e0-11ea-9cc3-49b2739e66f0.png)

**Possible solution**
If we just showed the parent block instead, this is what you'd see as soon as the block is added:

![Screen Shot 2019-12-26 at 1 02 33 PM](https://user-images.githubusercontent.com/617986/71490641-b15c5f80-27e0-11ea-9f50-72526333af1f.png)


----

### 2. Too many options?
At the getgo the Social Links blocks offers 6 options right away. This might be a bit much for an average user.

**Current  setup state**

![Screen Shot 2019-12-26 at 1 02 25 PM](https://user-images.githubusercontent.com/617986/71490652-c9cc7a00-27e0-11ea-9758-f869ddb066af.png)

**Possible solution**

![social-3 2019-12-26 13_00_31](https://user-images.githubusercontent.com/617986/71490668-dd77e080-27e0-11ea-8bce-1fbe8e1f98f5.gif)

----

### 3. The thick left-border
This left-border is obviously too much in the context of nested blocks and feels quite awkward.

**Current left-border**

![Screen Shot 2019-12-26 at 1 11 14 PM](https://user-images.githubusercontent.com/617986/71490722-3b0c2d00-27e1-11ea-86c0-15f784cc63ff.png)

**Possible solution: Remove left-border for nested blocks.**

![social 2019-12-26 12_47_12](https://user-images.githubusercontent.com/617986/71490737-4eb79380-27e1-11ea-85dc-5ea9af8e62e8.gif)

**Comment by jasmussen** [comment]
One of the challenges that both this social links block, and indeed the Buttons block has, is to better indicate what has focus. The thick left border does not indicate focus or even "the block is selected", it simply means _something inside this block has focus_. This is part of what #18667 hopes to address — better indicating what has focus, and reducing non-focus borders to not mistake them for focus.

**Comment by karmatosed** [comment]
I am going to ask perhaps a question that seems obvious but, do we need to have buttons showing by default? Why can't the placeholder just be to select one?

**Comment by jasmussen** [comment]
> Why can't the placeholder just be to select one social link? I used this over the break and found having multiple ones loaded by default was a lot to experience.

To be sure I'm understanding you right — instead of inserting a social links block that is "pre-populated", just insert an empty one so you can use the Add button to add your own, one by one. 

We actually did explore this when building, and it's a bit awkward:

![social links](https://user-images.githubusercontent.com/1204802/71819625-bc3eac00-308c-11ea-82ed-4937a3f4a5bb.gif)

Consider the use of this block inside a page or post template, which is likely where it will be used the most, as this is kind of a "set it and forget it" block. In this case, the block would be completely empty and invisible.

By being pre-populated with a few popular networks by default, on the other hand, as soon as you select the block you know what it's about. And similar to the Coblocks version, if you don't fill out any of the pre-populated ones they won't show up in the published version.

I recognize this isn't ideal either, as one can feel the need to remove those empty pre-inserted ones — even if they don't show up when published, the fact the the blocks are there feels wrong! This is the problem [Coblocks solved by not using child blocks](https://github.com/WordPress/gutenberg/issues/19020#issuecomment-563920296).

**Comment by karmatosed** [comment]
Thanks for showing that, yes it is a bit stark to have the +.

Could we just have one them over a row of them? Maybe best guess Twitter or fallback on WordPress? The problem I myself felt it was a lot to remove everything I didn't want when using this.

**Comment by jasmussen** [comment]
Reducing it to just the WordPress one preinserted could work. It could be interpreted as a fun callback to the "blogroll" which came with the .org link preinserted :)

**Comment by paaljoachim** [comment]
Testing the Social Media Block.

Adding the Social Media Block adds the various social icons seen here.
<img width="465" alt="Screen Shot 2020-01-13 at 02 06 10" src="https://user-images.githubusercontent.com/5323259/72228720-7a8c9480-35a9-11ea-80c1-05cba0a0a4fc.png">

The first thing I want to do is click the ones I do not plan on using, and press backspace/delete key to get rid of the icons I do not need. But they do not go away. As they just remain as ghosts. The one Social icon that I do use Facebook shows stronger then the ghosts I want to remove and send to the light.

<img width="714" alt="Screen Shot 2020-01-13 at 02 10 44" src="https://user-images.githubusercontent.com/5323259/72228781-f25abf00-35a9-11ea-9591-4daa048dced3.png">

Deselecting the block I see the Facebook icon.
<img width="483" alt="Screen Shot 2020-01-13 at 02 09 52" src="https://user-images.githubusercontent.com/5323259/72228811-48c7fd80-35aa-11ea-8140-3e751e26ee49.png">

Checking the frontend I see this:
<img width="715" alt="Screen Shot 2020-01-13 at 02 13 54" src="https://user-images.githubusercontent.com/5323259/72228820-61381800-35aa-11ea-8206-91c39d0ccd3c.png">
(Which likely means that the Gridd theme from @aristath has yet to add a frontend CSS for the social Media icons. I thought that Gutenberg would automatically add the frontend styles in addition to the backend styles.)

**Comment by jasmussen** [comment]
> The first thing I want to do is click the ones I do not plan on using, and press backspace/delete key to get rid of the icons I do not need. But they do not go away

This is a great thought, and it is a _foundational_ issue to fix. Not just for this block, but for the Butttons block as well, and indeed any other block with child blocks.

I believe that the solution is to more clearly indicate what has focus, and we are trying to do that with #19344. Right now it looks like the social icon has focus, when in fact the URL bar has focus.

**Comment by maddisondesigns** [comment]
Just wondering why the WordPress icon is added by default to this block? It's supposed to be a "Social Links" block. While there may be a small number of people who want to link to their dot org profiles, the majority of users aren't going to want a WordPress icon and you're just forcing them to have to remove it every single time. If you're going to have some default icons, then they should be Twitter, Facebook, Instagram, LinkedIn & YouTube. They're the most common social platforms used by the majority of people.

Also, the Block Editor is supposed to show the blocks as they appear on the front-end, but these icons are styled differently in the editor and on the front-end. In particular, when hovering over the icons.

In the Block Editor:
![Social-Links-Block-Editor](https://user-images.githubusercontent.com/2078245/75966511-96b01080-5f1e-11ea-8105-9390a1272258.gif)

On the front-end:
![Social-Links-Front-end](https://user-images.githubusercontent.com/2078245/75966427-754f2480-5f1e-11ea-9da1-aa67fd20e1b8.gif)

**Comment by mapk** [comment]
There's been some significant updates with G2. Here's what the intitial state of this block looks like now.

![Screen Shot 2020-03-06 at 12 43 38 PM](https://user-images.githubusercontent.com/617986/76121422-77f65c00-5fa8-11ea-8c79-6b7ed8dd9fd5.png)

It still has lots to improve on. But seeing as this issue is primarily around the placeholder or initial setup screen, let's just consider that.

1. The blue border indicates that I've got the WordPress icon selected, but the icon in the toolbar is the block's icon. This is a bit confusing.
2. I wonder if it would help to show the unused icons in black and white, and the used icons in color rather than just fading out the unused ones?

Here's how this block currently works, just FYI.

![social](https://user-images.githubusercontent.com/617986/76121663-09fe6480-5fa9-11ea-8bd9-cd5d5fc62bd3.gif)

**Comment by mkaz** [comment]
Going back to @karmatosed idea above. I think exploring removing the placeholders all together might be worth exploring since having them is confusing users also. There was another recent report about removing the default WordPress icon being an extra step and not as easy.

What if there was a placeholder item not as actually icons but a filler with instructions it click to add, something close to the idea of the Image Placeholder? @mtias has same placeholder ideas in this issue that feel related: https://github.com/WordPress/gutenberg/issues/19256

**Comment by mtias** [comment]
The only thing I would change is that once you have any icon set, selecting the block should not show placeholders anymore, just the + if you want to add more. The initial state with a row of icons seems a much better experience than just an empty block. I also find the WordPress one a bit weird as the primary / default item.

**Comment by mrwweb** [comment]
Just want to echo what others are saying. Having used this block a number of times in the last few days:

- As @maddisondesigns mentions, having the WP icon default first and prefilled is really annoying. I have had to delete it every time I use this block.
- The placeholders are very unwieldy. When placed in a narrow column, they exceed the column width and the later placeholders become unclickable.
- It feels really weird that I can delete a placeholder icon block that doesn't really exist. As @mtias suggests, the very first change I'd make is to remove all placeholders once a first icon is set.
- Because of all the placeholders and the lack of drag-and-drop, moving an icon from the end of the row to first in the list is very inconvenient.
- I'd much prefer a single placeholder icon. Thinking about the way the buttons block works, when I insert social icons, could focus immediately be put into the first placeholder position with all the options expanded for me to select the first icon?

**Comment by mrleemon** [comment]
Personally, I find the social icon placeholders in the social block very confusing. Do all these icons get added by default? Do I have to delete the ones I don't plan to use?
