### ISSUE TITLE
Columns block: Manually setting column width doesn't persist

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#19112]
**Describe the bug**
When manually setting a column width,  and then setting another column width, the first column width changes and doesn't keep the value already set.

**To reproduce**
1. Add a Columns block with 3 columns.
2. Manually set the first column width to `5`.
3. Skip to the 3rd column and manually set that column to`5`.
4. Observe that the first column grew in width by itself and didn't keep the manually set value.

**Expected behavior**
I expect the columns to keep whatever manual width I set.

**Screenshots**

![cols 2019-12-12 16_15_27](https://user-images.githubusercontent.com/617986/70759272-b3abbd80-1cfa-11ea-9bab-86f363547ce0.gif)

**Desktop (please complete the following information):**
 - OSX Catalina
 - Chrome 78.0.3
 - Gutenberg 7.1

**Comment by joshm33333** [comment]
This problem is even worse in 7.1
I used to be able to use ctrl-v, and go back and forth between 2 columns pasting over and over as they slowly got closer and closer to the desired widths
Now, for some reason, I can't paste into the number field, and setting custom widths has become impossible. I find myself inserting custom CSS as a workaround

**Comment by aduth** [comment]
I believe this may be a duplicate of #16370 . @mapk, can you confirm?

**Comment by mapk** [comment]
Yep, thanks @aduth, it's the same. I'll close this one out.
