### ISSUE TITLE
Gutenberg Reusable Blocks Boilerplate!

### ISSUE THREAD

**Issue by ahmadawais** [WordPress/gutenberg#1911]
Hey, folks!
📦 I have released a [Gutenberg Boilerplate](https://github.com/ahmadawais/Gutenberg-Boilerplate). 
Its goal is to be an easy to understand and heavily documented️ WordPress Gutenberg Boilerplate plugin!

👀 I am looking for reviewers and contributors willing to help continue building on and improving this boilerplate! You're more than welcomed to reach out via [Twitter](https://twitter.com/mrahmadawais/) or [Email me](http://ahmda.ws/cntctaa)!

🙌 I am hoping to get the community started with building Gutenberg blocks. That way they'll have a much better idea of what is being done here, and probably get more people involved with the project!

📃 I have written an extensive post about it, in the post I have also share my thoughts on the Gutenberg Editor, the dependency hell, license paradox, and stuff than you can [read here](https://ahmda.ws/GutenbergBoilerplate). 

🌟 I'd like to thank Matias Ventura, James Nylen, Riad Benguella, Andrew Duthie, Joen, and other contributors and the docs for the help. 

### Links
- [Gutenberg Boilerplate](https://github.com/ahmadawais/Gutenberg-Boilerplate) GitHub Repo. 
- Introduction to [Gutenberg Boilerplate](https://ahmda.ws/GutenbergBoilerplate) and other stuff. 
- Looking for contributors/reviewers — reach out via [Twitter](https://twitter.com/mrahmadawais/) or [Email me](http://ahmda.ws/cntctaa)!

**Comment by jasonbahl** [comment]
@ahmadawais great work! Really cool project and proof of concept that I think will help drive adoption of Gutenberg.

Some concerns I have about _everything_ being registered in JS.

We have the REST API in core and projects like WPGraphQL that allows for remote access of data from WordPress, including non-content data such as filed settings and attributes, etc. if there is no server side content block registration, there's no real way for REST or WPGraphQL to expose data outside of WP. 

Is there a proper server side block registration API that you chose not to use in your examples for some reason?

In my head, there would be a TON of value in having blocks be registered statically on the server and have JS components be hydrated with the server-side static definitions rather than having all the block attributes be registered solely on the client making that data only useful in the context of the Gutenberg editor when that's not the only use for it. 

For example if I were building a native app, I'd love to take advantage of existing blocks that I've registered statically for Gutenberg. If the blocks were registered server-side, I could access info about the blocks (icon, name, placeholder, other settings and attributes) remotely via REST or GraphQL and use those same definitions to build a native UI. Or even hypothetically Calypso could take advantage of static server-defined blocks and load them into their UI...

Anyway, good work and curious to see where this stuff goes.

**Comment by ahmadawais** [comment]
>@ahmadawais great work! Really cool project and proof of concept that I think will help drive adoption of Gutenberg.

That's very kind of you to say! 💯 And that's what I expect to happen!


>Some concerns I have about everything being registered in JS.
We have the REST API in core and projects like WPGraphQL that allows for remote access of data from WordPress, including non-content data such as filed settings and attributes, etc. if there is no server side content block registration, there's no real way for REST or WPGraphQL to expose data outside of WP.
Is there a proper server side block registration API that you chose not to use in your examples for some reason?

I think it's been worked at! There's a PHP wrapper being built. @mtias  can tell you more about it.

>In my head, there would be a TON of value in having blocks be registered statically on the server and have JS components be hydrated with the server-side static definitions rather than having all the block attributes be registered solely on the client making that data only useful in the context of the Gutenberg editor when that's not the only use for it.
For example if I were building a native app, I'd love to take advantage of existing blocks that I've registered statically for Gutenberg. If the blocks were registered server-side, I could access info about the blocks (icon, name, placeholder, other settings and attributes) remotely via REST or GraphQL and use those same definitions to build a native UI. Or even hypothetically Calypso could take advantage of static server-defined blocks and load them into their UI...

I agree with that! I am sure there will be a JS to PHP API Extension here. I read it in the repo! Haven't looked into it at the moment!

>Anyway, good work and curious to see where this stuff goes.

🎩💯

**Comment by karmatosed** [comment]
Thank you for creating this, as this isn't an exact issue or something to develop I am going to close up this ticket. However, it's awesome this is being done.

**Comment by ahmadawais** [comment]
Sure thing! :)

**Comment by nylen** [comment]
@ahmadawais this project is based on the [examples](https://github.com/nylen/gutenberg-examples) we started building, and linked to from the [developer documentation site](http://gutenberg-devdoc.surge.sh/blocks/).

I think you've done a very nice job of documenting and improving the project.  However, there is no attribution of this original source anywhere on the GitHub repo.

We plan to continue developing the examples repo and the documentation that goes along with it, including a prominent link from the main page of the Gutenberg project.  I expect that this examples repo will live at https://github.com/WordPress/gutenberg-examples soon.

This would be something that would benefit the WP community more if we unified these two projects under https://github.com/WordPress and continued developing there, as well as improving the documentation to add prominent links to the project.

Please let me know if this is something you'd be interested in collaborating on.  Otherwise, please add an attribution link back to the original project.

**Comment by ahmadawais** [comment]
🙌 @nylen first of all thank-you for the documentation help. It paved the way towards building this boilerplate. 

>@ahmadawais this project is based on the examples we started building and linked to from the developer documentation site. I think you've done a very nice job of documenting and improving the project. However, there is no attribution of this original source anywhere on the GitHub repo. ... 

🍒 Actually, it did help a lot but I wrote all of the code manually (except for certain files like .babelrc, package.json, etc.) — I took help from a repo with a name like `gutenberg-boilerplate-esnext` or something — I had downloaded a zip — I think you removed it and changed it to the examples repo? The documentation and code mostly came out of the Gutenberg's repo itself (the docs and the docblocks, etc.) otherwise, I wrote it myself with whatever I could fathom.

👀 I am glad that you liked it. About attribution, well I did attribute it in [my article](https://i.imgur.com/49SkdDf.png), at [WPTavern's article](https://i.imgur.com/gziTw5n.png), [in this issue](https://i.imgur.com/VUfT2uF.png), and now in the [boilerplate's readme](https://i.imgur.com/9Q8QDu3.png) as well. The examples repo felt like a work-in-progress — so, I didn't go around linking to it. I hope it's cleared out now. 

>We plan to continue developing the examples repo and the documentation that goes along with it, including a prominent link from the main page of the Gutenberg project. I expect that this examples repo will live at https://github.com/WordPress/gutenberg-examples soon.

🌟 That's actually pretty interesting. I am sure this will be a new thing since there are no example implementations in [there](https://github.com/WordPress?utf8=%E2%9C%93&q=example&type=&language=). And definitely a step in the right direction. 👍


>This would be something that would benefit the WP community more if we unified these two projects under https://github.com/WordPress and continued developing there, as well as improving the documentation to add prominent links to the project. Please let me know if this is something you'd be interested in collaborating on. 

🎯 I couldn't agree more! I'd be up for collaborating on this project — for sure! About unifying the two repos — I have a few questions there... mind jumping on a Slack chat to discuss that? I am `mrahmadawais` on the make WP slack. Let's discuss how we can move forward with it :)

Looking forward!
