### ISSUE TITLE
do_blocks doesn't render blocks correctly

### ISSUE THREAD

**Issue by juanRabaa** [WordPress/gutenberg#19114]
**Describe the bug**
The same gutenber content that printed inside the loop with `the_content` looks fine, is broken if being printed using `do_blocks($post->post_content);`

For example, the `core-embed/youtube` instead of rendering the iframe of the youtube video, only shows the video url. 

Blocks that uses a php `render_callback` function renders correctly, so its seems related to js. I guess `do_block` doesn't work with non dynamic blocks. Is there another function I'm missing?

**To reproduce**
1. Create a post with gutenberg blocks
2. Render the content using `do_blocks($post->post_content);`

**Expected behavior**
Blocks should render exactly like they do when using `the_content`

**Screenshots**
![do_blocks bug](https://user-images.githubusercontent.com/28640722/70770316-a23ed180-1d4b-11ea-9ff8-4296cc007cf9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 78.0.3904.108]

**Additional context**
- Wordpress Version: 5.2.5
- Gutenberg Version: The one that comes with that wordpress

**Comment by juanRabaa** [comment]
I've just realise that applying `the_content` filter to the HTML string from `do_blocks` fixes the dynamic blocks.

`apply_filters( 'the_content', do_blocks($post->post_content) );`

The problem with this is that wordpress automaticly adds `<p>` to the blocks content when applying the filter, which brakes some layouts. I don't get why, being that `the_content()` doesn't seems to be doing this.

A quick fix would be to `remove_filter('the_content', 'wpautop')`, but I'm not sure if I'm messing with something else doing this

**Comment by juanRabaa** [comment]
I ended up going for something like this

```
add_filter( 'render_block', function ( $block_content, $block ) {
    if(!RB_Gutenberg_Module::is_dynamic($block['blockName']))
        remove_filter( 'the_content', 'wpautop' );
    return $block_content;
}, 10, 2 );
```
If the block is dynamic, I remove the `wpautop` filter that adds the `<p>` to the markup.

I don't think this is the best way to do it, but it is the best I could come up with in such little time.

**Comment by talldan** [comment]
@juanRabaa I'm not fully versed on the issue, but I did some digging and it looks like there's some handling of this in the do_blocks function:
https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/blocks.php#L540-L545

It disables `wpautop` when blocks are present, but makes sure they're restored later using `_restore_wpautop_hook`, which is implemented in the same file:
https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/blocks.php#L550-L568

It looks like `the_content` filter needs a priority to make this implicit behaviour work correctly, so that might be where you were running into issues.

**Comment by johnstonphilip** [comment]
I am replicating this as well. When running block content through `do_blocks`, youtube videos do not get passed through oembed, but just return the URL. If I wrap in the_content filter, the oembed code for the video exists as expected.

**Comment by johnstonphilip** [comment]
I believe this happens because oembed only is hooked to `the_content` filter, but not anywhere in `do_blocks`:

See:
https://github.com/WordPress/WordPress/blob/270f2011f8ec7265c3f4ddce39c77ef5b496ed1c/wp-includes/class-wp-embed.php#L39

So if you are running `do_blocks` outside of `the_content` filter running, your oembeds will not get rendered properly.

**Comment by johnstonphilip** [comment]
This fix is to do this:

```
// Handle embeds.
global $wp_embed;
$rendered_content = $wp_embed->autoembed( do_blocks( $content ) );
```

**Comment by juanRabaa** [comment]
> I believe this happens because oembed only is hooked to `the_content` filter, but not anywhere in `do_blocks`:
> 
> See:
> https://github.com/WordPress/WordPress/blob/270f2011f8ec7265c3f4ddce39c77ef5b496ed1c/wp-includes/class-wp-embed.php#L39
> 
> So if you are running `do_blocks` outside of `the_content` filter running, your oembeds will not get rendered properly.

I haven't come back to this issue in a while. I did experiment it in a project a month ago, but i got it fixed.

If as you say this is happening because you are running `do_blocks` outside `the_content` filter, why not do `apply_filter("the_content", do_blocks())`?

**Comment by edmundcwm** [comment]
@johnstonphilip's solution works well! Thanks for that.

And if you need to also support the processing of the `[embed]` shortcode then you might want to do the following:

```php
// Handle embeds.
global $wp_embed, $post;
$rendered_content = $wp_embed->run_shortcode( $post->post_content );
$rendered_content = $wp_embed->autoembed( $rendered_content );
$rendered_content = do_blocks( $rendered_content );
```

In fact this is what Core does (in [block-template.php](https://github.com/WordPress/WordPress/blob/master/wp-includes/block-template.php#L238) and [block.php](https://github.com/WordPress/WordPress/blob/master/wp-includes/blocks/block.php#L45)) when it uses `do_blocks()` outside of the `the_content` filter.

@juanRabaa using `apply_filters( 'the_content', do_blocks( $content ) )`does work but I feel it's better to be explicit about processing the embeds by using the `run_shortcode` and `autoembed` methods. Because somewhere else in the codebase someone might be running `add_filter( 'the_content', 'callback_that_filters_content_but_fails_to_process_embeds' )` with a priority higher than `8` (which is what Core is using to [process embeds](https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-embed.php#L33-L41)); this opens up the risk of embeds breaking again.

**Comment by mikeybinns** [comment]
Just to add, I had success by applying the content filters inside do_blocks, like this:
```php
do_blocks( apply_filters( 'the_content', $my_block_comment_as_string ) );
```
The embed correctly processed and there were no added p tags like when I just used the `the_content` hook.
But it didn't work the other way around:
```php
// DIDN'T WORK, added p tags
apply_filters( 'the_content', do_blocks( $my_block_comment_as_string ) );
```
