### ISSUE TITLE
Revisions missing for reusable blocks

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#19149]
**Describe the bug**
The reusable blocks don't have any revisions, but these are important as the reusable block content is of course not included in page/post revisions.

**To reproduce**
1. Insert new block
2. Give that block some example content.
3. Make that block a reusable block.
4. Save the page.
5. Make changes to that reusable block that had been placed on that page.
6. Update that reusable block.
7. Go to Gutenberg reusable block list (still hard to find, you can go there by going to the Reusable blocks section in block menu of inserter and then use the link 'Manage all reusable blocks').
8. Notice that there are no revisions in block tab (like in document tab for posts that support revisions or pages).

**Expected behavior**
Revisions being available for reusable blocks.

**Comment by andymagill** [comment]
+1 for this. Without revisions this is more a copying feature than re-usable.

**Comment by donalirl** [comment]
I would also like to see this feature introduced 👍

**Comment by MattBergerWP** [comment]
+1 to this. 

Our team uses Resusable Blocks to complete forms of content with standard sections of text to fill out. However new users often forget to "convert to regular block" and end up replacing all the placeholder copy with their specific content, and then publish. This makes the block unusable for the next person as they see the information left by the previous user.

It would be great to be able to roll back a block to a previous version so that it could be easily reverted to its original state.

**Comment by AtrumGeost** [comment]
It would be great to have this. Especially for when you edit a reusable block by mistake

**Comment by mtias** [comment]
Revisions will be enabled for 5.8 https://core.trac.wordpress.org/ticket/53072
