### ISSUE TITLE
Cannot Dismiss Welcome Modal in IE11

### ISSUE THREAD

**Issue by gwwar** [WordPress/gutenberg#19140]
**Describe the bug**
The new welcome modal doesn't appear to be dismissible when clicking on the `x`, or background overlay in IE11

![dismiss](https://user-images.githubusercontent.com/1270189/70835860-4445d480-1db3-11ea-9332-1f561b1e47c1.gif)

**To reproduce**
1. Make sure the NUX welcome will display for a user.  `wp.data.dispatch( 'core/nux' ).enableTips()`
2. When viewing in IE 11 try to click on the `x` or background overlay

**Expected behavior**
Modal dismisses

**Additional context**
- Tested on master (b2ef0f550b5e0fc549742f3dfbef2bea89155169) using BrowserStack (Windows 10 / IE11)

**Comment by tellthemachines** [comment]
Can confirm this is happening on Windows 10 / IE 11. Button is not clickable on hover, but can be tabbed to with the keyboard. The culprit is the `margin-top: -56px` set on `components-guide_container` which causes the container to overlay the button so that it becomes unclickable.

Closing on click outside is broken for all modals on IE, so must be an issue with the Modal component, or possibly `withFocusOutside`.

**Comment by aduth** [comment]
I'll plan to take a look at this today, if nobody's claimed it yet.

**Comment by aduth** [comment]
Fixes proposed at #19201
