### ISSUE TITLE
Full screen doesn't show on smaller screens by default

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19176]
There is a lot going on before you even get to the editor on mobile web.

![image](https://user-images.githubusercontent.com/253067/70922617-4eb7d680-201e-11ea-95bf-5a7a8f8e92d0.png)

What if some elements of the fullscreen were brought in?

<img width="463" alt="mobile" src="https://user-images.githubusercontent.com/253067/70922917-d4d41d00-201e-11ea-8dab-1df417b009e7.png">

**Comment by MichaelArestad** [comment]
I've been thinking about the `Fullscreen Mode` editor option lately. I wonder if there is a reason it is an option instead of the default. This ties directly in. Even on a large screen, the admin interface is not only competing for attention, but is taking up valuable space.

In this scenario especially, I see no great reason why it wouldn't default to full screen on tablets and phones.

**Comment by karmatosed** [comment]
Now that fullscreen is activated by default, this is an issue only on smaller screens. It would be great to fix so that fullscreen goes across all sizes.

**Comment by jordesign** [comment]
As of WP 6.3 this is _better_ - but there is still a lot going on.

<img width="394" alt="Screenshot 2023-08-16 at 2 32 42 pm" src="https://github.com/WordPress/gutenberg/assets/1842363/09e3166a-f7b2-4c23-9bb0-f2156563a563">

**Comment by karmatosed** [comment]
This has been iterated so for me I am going to close this.
