### ISSUE TITLE
Block toolbar should move to by block

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19185]
On a mobile device, it would be nice to move the block to the top and connect with the toolbar when interacting. There is a movement to connect back, however, there is still a disconnected space. For example here, I am interacting with the image block.

![2019-12-16 21 42 13](https://user-images.githubusercontent.com/253067/70945406-06fc7380-204d-11ea-8c96-72cd28207448.gif)

**Comment by melchoyce** [comment]
Seems like something a stronger active block indication could help with?

**Comment by jasmussen** [comment]
Is this tested in the iOS simulator? It's hard to tell without the soft-keyboard showing. If it's from the simulator, here's how to toggle it:

<img width="654" alt="Screenshot 2019-12-17 at 09 47 23" src="https://user-images.githubusercontent.com/1204802/70979692-5032de80-20b2-11ea-96c4-c7fe16776eda.png">

I ask because the way Mobile Safari handles the soft keyboard and viewport scrolling is notoriously bad, and as a result is unfortunately the lowest common denominator we have to design for. 

> Seems like something a stronger active block indication could help with?

I disagree specifically on the term "active block indication", though I would agree making it much more clear what actually has _focus_ is very very important. It may sound like a subtle distinction but I think it matters:

- If you click in text, what matters is that the **text caret** — where you clicked to type — is immediately identifiable, and where your eye expects it to be. Given that caret is often gray, I doubt additional borders will help here. 
- If you click an image, it's very important that the image itself has a distinctly visible **focus style**, so you know what you're editing. 

You should always know exactly what you're editing, and making sure it's in expected view is important.

**Comment by melchoyce** [comment]
Sorry, "active block indication" was kind of a brain fart, I couldn't remember what to call it.

**Comment by karmatosed** [comment]
@jasmussen it wasn't but that might be what forces this.

**Comment by mtias** [comment]
Floating toolbars can be a lot trickier on mobile. The native apps have controls docked, but on the bottom, which is generally the most intuitive place since that's where the keyboard exists. We don't have good browser APIs on mobile to handle that positioning, though, so until that changes I don't think there's much to do here.
