### ISSUE TITLE
The appender in the group block is missing icon

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#19246]
**Describe the bug**
While testing #19135 I noticed that the group block in Firefox 71 is missing the plus Icon (Chrome displays properly)

**To reproduce**
1. Use Firefox latest
2. Create a post
3. Add a group block
4. See bug

**Expected behavior**
The appender to have the plus icon

**Screenshots**

<img width="662" alt="Screenshot 2019-12-19 at 17 48 15" src="https://user-images.githubusercontent.com/107534/71188213-3992b000-2289-11ea-894b-dd49e38f48df.png">

**Desktop (please complete the following information):**
 - OS: osx
 - Browser Firefox
 - Version 71

**Smartphone (please complete the following information):**

**Comment by glendaviesnz** [comment]
Seems to be related to the `.block-editor-button-block-appender` styles.

If `flex-direction: column` is disabled it fixes it:
<img width="708" alt="column" src="https://user-images.githubusercontent.com/3629020/71226522-f5fb7d00-2340-11ea-8e7f-3ac57d434516.png">

but this breaks the alignment in chrome

removing the padding also fixes it, and doesn't break the alignment in chrome:

<img width="699" alt="padding" src="https://user-images.githubusercontent.com/3629020/71226565-20e5d100-2341-11ea-9d1f-34e5b2eb99f2.png">

Ran out of time to work out exactly what the issue is, or what the best fix is sorry.

**Comment by bartczyz** [comment]
Howdy @draganescu!

I noticed this issue on MacOS 10.14.6 / Safari 13.0.4 as well.

IMO the problem is with the height of the element. Since the container doesn't have a `height` set it's being squashed by the padding.

Adding `height: 100%` fixes the problem for me.

I will open a PR later today. 👍
