### ISSUE TITLE
init hook not called for dynamic block render callbacks

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#19324]
**Describe the bug**
The `init` hook is not called when a dynamic block is rendered on server-side.

**To reproduce**
For this example I use WooCommerce product block and override the rendering:
1.
```php
function woo_block_product_grid_item_html($html, $block_attr, $_product) {
    return 'Test!';
}

add_filter( 'woocommerce_blocks_product_grid_item_html', __NAMESPACE__ . '\\woo_block_product_grid_item_html', 10, 3);
````
In the theme I also add an `init` hook handler:
```php
add_action('init', function() {
  echo 'Hook called!';
});
````
2. The hook is not called when the block is rendered dynamically.
This is an issue when relying on the `init` hook.
E.g. for removing the product thumbnail one can remove the default thumbnail function:
```php
remove_action( 'woocommerce_before_shop_loop_item_title', 'woocommerce_template_loop_product_thumbnail', 90 );
````
But this doesn't work for dynamically rendered block callback, even when the `init` hook is used.

**Expected behavior**
`init` hook is called.
`remove_action` and other methods aren't invoked when used in theme for dynamically rendered blocks.

**Additional context**
Related: https://github.com/WordPress/gutenberg/issues/13634

**Comment by talldan** [comment]
Hi @strarsis, sorry for a delay in response on this issue. Is this still a problem you're experiencing?

The issue was discussed in a core-editor triage session (here's a link to the conversation on slack - https://wordpress.slack.com/archives/C02QB2JS7/p1594100394102000).

There was some confusion over what the intention is with the use of `init`. My understanding is that `init` is called once on load rather than when a dynamic block renders. Let me know if I'm misunderstanding here.
