### ISSUE TITLE
Automatic switch media button in toolbar when using the MediaPlaceholder Component

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#19336]
**Is your feature request related to a problem? Please describe.**
Almost every time media items are used in a block you need a way to edit them after you first insert them. This can be done how ever the developer likes though. But wouldn't it make it a better user experience if all of them worked the same way? And also if you only need to change it in one place instead of in every single block that uses it. Like it had to be done here: #16200 

**Describe the solution you'd like**
Automatically adding a replace media interface to the block toolbar when using the `MediaPlaceholder` component. Either having it turned on by default but being able to disable it or needing to enable it yourself via a prop.

**Comment by youknowriad** [comment]
Interesting proposal. Did you see this @draganescu could be interesting to see how feasible is that and whether it's a good addition or not.

**Comment by draganescu** [comment]
Hi @fabiankaegy this sounds very nice, I'll check this out and see how it works as a feature of the MediaPlaceholder component.

**Comment by draganescu** [comment]
My initial thoughts are that having `MediaReplaceFlow` added to a block's toolbar by `MediaPlaceholder` is going to be complicated by the fact that `MediaPlaceholder` is unmounted everytime the "edit" state is done, which will remove `MediaReplaceFlow` as well.

The placeholder is thought (both functionally and visually) as an either/or component, it will not fit well with making it deliver options to block's which use it.

One other option to achieve a similar result (which I've explored with `MediaReplaceFlow` initially) is to possibly have a HoC `MediaContainer` that offers both `MediaReplaceFlow` and `MediaPlaceholder`. We need a HoC because any component ofering both has to render both in the scope of `BlockControls` for the replace flow and outside that, in the scope of the implementing block's container, for the placeholder.

**Comment by youknowriad** [comment]
Good thoughts,  based on this, I feel like having to include the two components is probably a simpler way to go, so let's close this issue for now. Thanks for looking.
