### ISSUE TITLE
Reduce padding on block menus so hover doesn't have gaps

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19349]
I was building a block and found this visual hover state really was a bit annoying:

![image](https://user-images.githubusercontent.com/253067/71528866-d97bb980-28d9-11ea-9079-1c1054894939.png)

By reducing or increasing hover to cover the entire whitespace, it could feel better.

**Comment by mapk** [comment]
I agree. AND it looks like the hover state has rounded corners. I don't think these are necessary in this instance because they're difficult to discern and because the hover state extends to the edges, they look like a mistake.

**Comment by akkspros** [comment]
i agree to reducing or increasing hover to cover the entire whitespace

**Comment by ibdz** [comment]
I suggest increasing the left & right padding of components-menu-group to have the same padding as top & bottom.
![Screen Recording 2020-02-27 at 03 16 53](https://user-images.githubusercontent.com/426383/75384081-1a12a600-5910-11ea-81b7-c94c5caa1321.gif)

This approach will lead and get along with the new toolbar interface G2 “Advancing the Block Interface”.
![Screen Shot 2020-02-27 at 03 13 27](https://user-images.githubusercontent.com/426383/75384410-a3c27380-5910-11ea-865d-bfb24deaf265.png)

**Comment by karmatosed** [comment]
@ibdz I think that's a great step. I will remove the design feedback label, but let's loop in @jasmussen to find out where this sits with the interface iterations.

**Comment by jasmussen** [comment]
Some good thoughts here, and they have perhaps been slightly ahead of the ideas that were explored in #18667. In that vein, the menu now looks like this:

![menu](https://user-images.githubusercontent.com/1204802/75756438-f2b54200-5d30-11ea-81d3-e2d03862331d.gif)

Note the differentiation between focus and hover — hover is not strictly necessary to have, which is why we've gone with a minimalist text color change, whereas the focus one is important. 

I wonder if that addresses the feedback?

**Comment by mapk** [comment]
Looks like G2 has resolved this. Thanks!
