### ISSUE TITLE
Is it the right way for showing post format based meta box?

### ISSUE THREAD

**Issue by nriddhi** [WordPress/gutenberg#19356]
I have enqueued post-format.js with 'admin_enqueue_scripts', but getting error in console. Is it the right way for hiding and showing metabox from this Gutenberg editor?

I am getting error, 

> Uncaught ReferenceError: wp is not defined

**Post-format.js**
```
(function ($) {
    "use strict";
   wp.data.subscribe(() => {
       var postFormat = wp.data.select('core/editor').getEditedPostAttribute('format');
       $('#appmyil-section-video01, #appmyil-section-audio01, #appmyil-section-image01').hide();

       if( postFormat == 'image' ) {
         $('#appmyil-section-image01').fadeIn();
       };
       if( postFormat == 'video' ) {
         $('#appmyil-section-video01').fadeIn();
       };
       if( postFormat == 'audio' ) {
         $('#appmyil-section-audio01').fadeIn();
       };
   });
})(jQuery);
```

**Comment by youknowriad** [comment]
Hi There!  when you use WordPress JS APIs like so, make sure to define your dependencies for your script.  Based on the code above I can see that this script depends on both `wp-data` (wp.data) and `wp-editor` ('core/editor').

Other than that, you should make sure to run your callback only when `postFormat` changes (save  the previous value), otherwise it will run too often.
