### ISSUE TITLE
Error: 'This response is no valid JSON response" during media upload in gutenberg editor on mobile devices

### ISSUE THREAD

**Issue by Florianoli** [WordPress/gutenberg#19368]
Hi there,
Sometimes during uploading media in a post, I get the following error: 'This response is no valid JSON response. " 

By the way, my WordPress installation and plugins are up-to-date. The issue occurs mainly on mobile devices.

Thanks for your help!

**Comment by youknowriad** [comment]
Unfortunately, we can't know what happens as this message is too generic and can happen for multiple issues.

Ideally, you should try to check your server logs. If it's happening during media uploads, I suspect it's because of php memory limit issues on your server.

Which version of WordPress are you using?

**Comment by youknowriad** [comment]
Closing as stale
