### ISSUE TITLE
Block HTML editor, should have a modal under to show result preview directly.

### ISSUE THREAD

**Issue by Nemzag** [WordPress/gutenberg#19380]
**Is your feature request related to a problem? Please describe.**
Yes and not,
the problem is that we don't see the graphic result directly.

**Describe the solution you'd like**
A window or modal under code to see the graphic preview directly.
Who will show the section were we are vorgwing,
in 9 or 15 line’s. To not exceed the size of the page.

**Comment by youknowriad** [comment]
Would you mind sharing a mockup or something? I'm having trouble understanding your proposal. Thanks.

**Comment by Nemzag** [comment]
Ok, will make it,
but what you mean by mockup ? A wire‑frame ?
How do you say that in French ?
I don't comprehend, actually what is a « mockup ».

**Comment by youknowriad** [comment]
une maquette :), un wireframe, comme tu veux, juste pour avoid une idée.

**Comment by Nemzag** [comment]
Ok je le fais.

**Comment by Nemzag** [comment]
Hi & peace,

I made the mockup.

Now we have this :

<img src="https://mangzedi.files.wordpress.com/2020/01/now01.png">

And this :
<img src="https://mangzedi.files.wordpress.com/2020/01/now02.png">

I would like like this :
<img src="https://mangzedi.files.wordpress.com/2020/01/future3.png">

With line edited in middle (height) in preview, and as a modal (upon the next block)… Or else. If you have better idea.

**Comment by Nemzag** [comment]
Or even keep HTML & Preview button, to see only one of them,
but third button "both" possible.

**Comment by yamhochi** [comment]
Hey @Nemzag would you mind re-uploading your screenshots? They seem to be broken :(

**Comment by Nemzag** [comment]
Hi,
it is not broken, but the blog was put by me in private mode, I will make it public soon.
To correct this.

**Comment by Nemzag** [comment]
@yamhochi 
Hi, I corrected the bug.
Tʰang 当谠 帑 you pro advertising me and also pro your ħêlph.
Ħave a lõng & ħappy life [leif]…

**Comment by mapk** [comment]
This is a good consideration to bring up. Thanks for this idea!

However, I personally prefer the simplicity of either the HTML or the Preview as it is now. I understand that you don't see the preview while writing the HTML, but I don't understand why that's necessarily a problem. Showing both together could take up a lot of space in the Editor.

Right now the block expands as more HTML is written. This would cause the Preview to drop further down the page. I like keeping this compact and using a Preview toggle instead.

**Comment by paaljoachim** [comment]
Hi @Nemzag 

Let's say that the main point of having a preview seen below the HTML area would be to see the automatic changes as one adds the HTML. At present I am not sure if it is possible to have a live preview as one types in the HTML. 
Today as one clicks the Preview button one also says to the code I am ready to see the preview, and the preview is seen.

I agree with @mapk 
Switching between Preview <-> HTML in a toggle feels like the best method. It keeps the preview in the same space the HTML is located in. Removing the toggle the HTML and the preview will take up a lot more space.

Another method would be to use an online HTML creation service to create the HTML and see the preview at the same time, and when one has finished bring the HTML into Gutenberg. 

Sorry to say it but I do believe this issue is a no go, @Nemzag.
I am removing the "Needs Design Feedback" label as @mapk and myself both left a similar comment.

**Comment by jordesign** [comment]
Given there has been no further discussion - and the convention of toggling between HTML and preview is now well established, I'm going to close this issue.
