### ISSUE TITLE
Tiled mosaic upload problem

### ISSUE THREAD

**Issue by rickmgithub** [WordPress/gutenberg#19411]
**Describe the bug**
When you try to drag in an image into the browser to add an image, it doesn't upload it but goes replaces WordPres.com in the browser tab with the image

**To reproduce**
- Create a post
- Drag an image into the post to create an image block
- Convert the image block to a "tiled mosaic" block
- Drag image into the block 

**Expected behavior**
The image to appear in the gallery rather than to be redirected to show the image

**Desktop (please complete the following information):**
I repeated the problem myself on 
Chrome Version 79.0.3945.88 (Official Build) (64-bit)
MacOS

**Comment by talldan** [comment]
Hi @rickmgithub, the tiled mosaic block isn't part of the core gutenberg block collection, this is probably a feature of WordPress.com or a plugin that's bundled in WordPress.com by default.

Because of that, it's not possible for us to address the issue here. I'd recommend reaching out to WordPress.com support—https://en.support.wordpress.com/
