### ISSUE TITLE
Longer author names overlap on drop down

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19414]
This was on latest build using Chrome. If the author has a longer name you get overlap:

![author-overlap-dropdown](https://user-images.githubusercontent.com/253067/71815501-93f88280-3077-11ea-96ec-b2a478ba2a09.png)

**Comment by tellthemachines** [comment]
Hi @karmatosed , I'm not sure where this component is located in the UI, could you please add some more detail/steps to reproduce? Thanks ❤️

**Comment by karmatosed** [comment]
@tellthemachines sure, you go to documents > settings and if have multiple authors it's there.

**Comment by tellthemachines** [comment]
OK this is an interesting one, and seems to be the same problem that's occurring in #19415. I can't reproduce it in my local dev environment, but can definitely see it in a production website with the latest version of the Gutenberg plugin activated. If I deactivate the plugin, it doesn't happen.

The problem is with stylesheet ordering. In the plugin, the `edit-post` package stylesheet is loaded after core styles, so override the default styling we have in place for selects in core. In core itself, the stylesheets are bundled in the correct order, so we don't get the issue. In gutenberg dev, the stylesheets also load in the correct order, which is why I can't reproduce this in my local environment 😅

**Comment by karmatosed** [comment]
Oh that's interesting, thanks for some serious sleuthing there @tellthemachines!
