### ISSUE TITLE
Improve inline image sizing

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19426]
Currently, the inline image width looks like this:

![image](https://user-images.githubusercontent.com/253067/71817800-fc972d80-307e-11ea-9017-9e4c976475b7.png)

It would be great to iterate this a little to tidy up the input and maybe bring in image sizes over have an up/down select.

**Comment by mapk** [comment]
Would it be helpful to allow the `vertical-align: [options]` for this? Like if I wanted to set `vertical-align: middle` on the image so that the text would be centered on it.

So instead of this:

![Screen Shot 2020-01-07 at 10 09 20 AM](https://user-images.githubusercontent.com/617986/71917827-d97b8500-3135-11ea-9bcc-a92e9f2b8746.png)

I can make it look like this:

![Screen Shot 2020-01-07 at 10 09 34 AM](https://user-images.githubusercontent.com/617986/71917839-dda7a280-3135-11ea-86a1-8e47b32796a0.png)

**Comment by karmatosed** [comment]
This could do with some design of the flow at least, so let's get that label here.

**Comment by mapk** [comment]
Here's a go at how the controls might work. I left out the "Return" icon figuring they could work similarly to the new Design Tools for the Image block. 

![inline-image](https://user-images.githubusercontent.com/617986/87730488-cb5d8f80-c77c-11ea-834a-31dc799d777b.png)

**Comment by melchoyce** [comment]
It might make more sense to refactor inline images to be child blocks, so they can have their own toolbar for settings. That would help eliminate this one-off UI and make the block's behavior more consistent.

**Comment by jordesign** [comment]
I'm going to close this issue as it seems well covered in these more recent ones:

* https://github.com/WordPress/gutenberg/issues/28813
* https://github.com/WordPress/gutenberg/issues/38184
