### ISSUE TITLE
I am have encountered an issue.

### ISSUE THREAD

**Issue by clarelawes32** [WordPress/gutenberg#19441]
I opened up Gutenburg editor on my Wordpress website and the section of the editor where you actually write your post and such has been reduced to a tiny little box that is completely unusable. It's not even an inch in height. I need to how to fix this. I'm hoping someone will see this and be able to help, but honestly not expecting much.

**Comment by karmatosed** [comment]
Oh no @clarelawes32 that sounds not great for you. In order to work out if this is an issue with the editor, would you perhaps be able to give me a few more details? 

- What version of WordPress are you using for example, ideally what version of Gutenberg would be very helpful to know. 
- Are you using a custom theme? 
- If you are using a custom theme are you able to try Twenty Twenty for example?

Along with the above, if you could link a screenshot or gif/video that would help in working this out.

**Comment by clarelawes32** [comment]
I'm happy to provide any info I can to help resolve this.

- I'm using Wordpress version 5.3.2
- I am using them Reblog
- I have added a screenshot of the problem
![Screenshot (2)](https://user-images.githubusercontent.com/59581663/71850489-a2539800-3091-11ea-96e1-219dabc4c237.png)

Thank you for your help!

**Comment by 0aveRyan** [comment]
@clarelawes32 I believe this is probably because that `Yoast SEO` panel is open (which is their legacy panel). 

If you click the triangle on the same line as `Yoast SEO` are you able to see the full editor again? Most if not all of Yoast's functionality is now accessible via a Gutenberg Plugin, which you can toggle from the Main Menu (three vertical dots in the upper right of the screen) and will show in the right sidebar inspector. If you still need that legacy panel, you may need to open and close it using that triangle indicator as-needed. If this doesn't solve your issue, please reply!

**Comment by clarelawes32** [comment]
@0aveRyan Thank you!! Problem solved!

**Comment by 0aveRyan** [comment]
@clarelawes32 glad we could sort that out! going to close this for now
