### ISSUE TITLE
Move "Welcome Guide" link to Options modal dialog

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#19443]
**Is your feature request related to a problem? Please describe.**
Let's move the "Welcome Guide" link to the Options modal dialog. It feels like a good place under the "Inserter help panel" item in the "General" section. Based on https://github.com/WordPress/gutenberg/issues/19409, we're exploring ways to eliminate the two instances of "Tools" sections in the interface, and clearing out this section may help.

I realize this would make the Welcome Guide a checkbox instead of just a button that triggered it. I believe it can still work similarly though. Clicking the Welcome Guide "on" could trigger it to open right after closing the Options dialog. And closing the Welcome Guide would check the option to "off" in the Options dialog.

**Describe the solution you'd like**

![Screen Shot 2020-01-06 at 12 24 07 PM](https://user-images.githubusercontent.com/617986/71848084-6addef00-3083-11ea-96fa-d4d53b492b64.png)

Does this sound reasonable?

**Comment by karmatosed** [comment]
I think this makes sense. I would argue for moving all options to the bottom but that's another issue. I also think it opening after one modal closes makes sense.

**Comment by napolitano** [comment]
Please don't take it too badly if I post a few thoughts about the "Welcome Guide" in the following, free of the liver. But after searching half of the internet in vain for a useful solution to permanently disable this feature, I'm a bit annoyed - because this Welcome Guide has hindered me several times in the last days.

So here are some thoughts from the point of view of a Wordpress user (of course purely subjective without claiming to be valid for all or the majority of users):

    The "Welcome Guide" has very little value from the user's point of view. It is not very helpful for new users and superfluous for experienced users
    The "Welcome Guide" - when displayed - hinders the use of Wordpress and forces an interaction
    The "Welcome Guide" is displayed without being asked - for example, there is no query during installation whether such functionality is desired
    There is currently no way to turn it off permanently - for example via wp-config or the menu option "Settings

Personally, I find the Welcome Guide very annoying and in my personal opinion it is not helpful to promote the editor "Gutenberg" in a positive way - at least not in its current form.

My advice to all involved would be - even before any redesigns & Co. are discussed - to make this "feature" safely disableable for the time being. Ideally via a graphical switch on the "Settings" page - or at least via a configuration option in wp-config.php to allow experienced users to turn it off.

This also gives you time to think about the feature as a whole. The Welcome Guide in its current form brings almost nothing to new users - a guided tour with context bubbles that show where to find features and what to use them for would certainly be more beneficial for this target group - and a query "Do you already have experience with the Gutenberg Editor?" during the installation, in order to activate such a tour, would be great.

**Comment by annezazu** [comment]
While looking at the plans for the welcome guide in the site editor, I stumbled back on this issue and wanted to follow up. It seems like this is covering two items: adding the welcome guide link to the Options modal (now called Preferences) and the ability to toggle off the welcome guide. For turning this off in general across a wide scale, I wanted to flag this previous GitHub discussion where a plugin solution is shared: https://github.com/WordPress/gutenberg/issues/19512#issuecomment-572304859 In terms of having this built into core, in the future, this won't need to be a setting when this issue is resolved around how these settings are stored: https://github.com/WordPress/gutenberg/issues/15105 As a result, having something to turn this feature on/off won't make sense and will only act as a bandaid until then. 

All of this is to give context on why I'm closing this issue out but I welcome having it reopened if it seems advantageous to do so or I misunderstood the wider context of this issue 🙌🏼
