### ISSUE TITLE
 force the editor to reload or re-render server-side blocks on Tax change

### ISSUE THREAD

**Issue by pbearne** [WordPress/gutenberg#19486]
Hi Guys

in the weeds again :-)

I am using a custom Taxonomy along with a CPT to create some custom pages

I have a couple of custom blocks that rely on the taxonomy set on the page to drive the content they show

So I need a way to force blocks to re-render when Taxonomy changes ( I have already converted the Tax to a select and have an on-change action wired up)

Can I trigger a block by name or do I need to reload the whole page
I may need to trigger a page save to make sure the Taxonomy is set

what is the recommended way to do this?

Thanks

**Comment by mcsf** [comment]
Hi there!

This is an interesting question to raise. By nature, a block is meant to be a unit of content described only by its attributes and serialised content. However, this assumption quickly breaks whenever we are dealing with dynamic blocks, and this bleeds into the editor when we use `ServerSideRender`.

Ideally, we would be able to express all of the dependencies of a block. In your example, the post's tags (or other taxonomy) would be one such dependency. The closest supported mechanism we have so far is [_post meta attributes_](https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/block-api/block-attributes.md#meta). It might or might not make sense to support the equivalent for taxonomies or post attributes in general, e.g.:

```js
attributes: {
	tags: {
		type: 'string',
		source: 'post',
		attribute: 'tags'
	},
},
```

That way, any change to the post's tags would be treated as an attribute change for your block, thus triggering a re-render.

The last months have seen a lot of improvements in the framework around so-called _core entities_, so we might be closer to achieving this. Looping in @epiqueras and @youknowriad in case they have better recommendations.

* * *

In the meantime, you could cheat with some custom code. There are two things to do:
1. forcing a block to be re-rendered
2. knowing when to re-render it

`ServerSideRender` doesn't expose any way to trigger re-renders. The only way is to change the attributes of the block. So you can either add a dummy attribute to your block type, in which case you can trigger a re-render by updating that dummy attribute to some new value. Otherwise, if you'd like to avoid compromising the block type, you could _replace_ a block with an identical one:

```js
wp.data.dispatch( 'core/block-editor' ).replaceBlock(
  originalBlock.clientId,
  wp.blocks.cloneBlock( originalBlock )
);
```

If you have several blocks in a single post which may care about the post's tags, you could use a blunt instrument in the form of `resetBlocks`. Use with caution:

```js
wp.data.dispatch( 'core/block-editor' ).resetBlocks(
  wp.data.select( 'core/block-editor' ).getBlocks().map( wp.blocks.cloneBlock )
);
```

2. To subscribe to tags edits:

```js
{
	let previous = wp.data.select( 'core/editor' ).getEditedPostAttribute( 'tags' );
	let unsubscribe = wp.data.subscribe( () => {
		const tags = wp.data.select( 'core/editor' ).getEditedPostAttribute( 'tags' );
		if ( tags !== previous ) {
			previous = tags;
			wp.data.dispatch( 'core/block-editor' ).resetBlocks(
				wp.data.select( 'core/block-editor' ).getBlocks().map(
					wp.blocks.cloneBlock
				)
			);
		}
	} )
}
```

**Comment by epiqueras** [comment]
We are moving away from post meta attributes or any custom source attribute because it breaks the pureness of block rendering and makes validation require a specific state.

In this case, you just need the block to rerender when tags change right? You can use `withSelect` or `useSelect` to subscribe to the value without doing anything with it and that will do what you want:

```js
wp.data.useSelect( select => select( 'core/editor' ).getEditedPostAttribute( 'tags' ) );
```

Or even better, to also support nested post contexts (in a template/site editor for example):

```js
wp.coreData.useEntityProp( 'postType', postType, 'tags' );
```

That will subscribe to the nearest parent post.

**Comment by mcsf** [comment]
> You can use withSelect or useSelect to subscribe to the value without doing anything with it and that will do what you want:

That's true, I didn't think that this might be a block type that would itself be edited by OP; `useSelect` is much better. Thanks.

Closing the issue as solved.

**Comment by pbearne** [comment]
To help others I have put my working code on gist https://gist.github.com/pbearne/2009f8cf8fc5416dd6f2bd4d821a94f6

**Comment by mcsf** [comment]
Thanks for following up!
