### ISSUE TITLE
Heading/Text block: editor toolbar "color" control

### ISSUE THREAD

**Issue by lkraav** [WordPress/gutenberg#1955]
It should be possible to colorize a part of any text via the editor toolbar.

Lower priority, but perhaps also useful: API to define specific colors for user selection in the color picker - such as a selection of preset brand CVI colors.

**Comment by iseulde** [comment]
I realise this is quite a popular feature, colouring text and custom CSS, but I'm never sure if we should continue supporting this in Gutenberg (plugin territory).

An alternative is to let the theme register basic colour variables, so that they all change when you switch themes. They could also be overwritten by the user, for a specific theme, but fall back to the default when switching. Cc @hugobaeta @melchoyce.

See also: https://core.trac.wordpress.org/ticket/27159.

In any case, we should really do it right this time, if we add it. :)

**Comment by lkraav** [comment]
> I realise this is quite a popular feature, colouring text and custom CSS, but I'm never sure if we should continue supporting this in Gutenberg (plugin territory). An alternative is to let the theme register basic colour variables, so that they all change when you switch themes. 

Plugins for everything is fine with me, but are regular folk really going to be happy to discover "Can't highlight a couple of words out of this headline"? This is a basic technique for helping notice important stuff during scroll-through skimming.

**Comment by hugobaeta** [comment]
@lkraav 
> This is a basic technique for helping readers notice important stuff during scroll-through skimming.

I'd argue there are more semantic ways to markup something important in a text, namely `strong` (bold) and `em` for emphasis (italics). Colors have always been, in my opinion, a potentially dangerous tool to give a normal user. Especially because of how it's implemented, writing those values inline directly in the database. It creates scenarios where the text is set in a specific way that might look bad and create accessibility issues with a change of theme. 

@iseulde I strongly believe Gutenberg is the clean slate we've longed for years, to guarantee the best, future-proof, accessible semantic experience out of the box. Everything else is plugin territory. 

The theme-defined styles might be a great tool for theme designers and developers to use, beyond of this specific issue.

**Comment by karmatosed** [comment]
The paragraph tool not have coloring and I think for now that's enough. Let's close this and consider it a plugin for Gutenberg or something to consider as v2 of the editor.
