### ISSUE TITLE
Adding text before a hyperlink is added inside the link

### ISSUE THREAD

**Issue by joshm33333** [WordPress/gutenberg#19588]
I don't believe this is standard behavior for a text editor. Create a hyperlink in a paragraph, put the cursor directly before the first letter, start typing. The new characters are added to the hyperlink.

EDIT: It seems to have something to do with the way the cursor position is determined. If you click anywhere within 10 pixels or so of the left of the first letter, the cursor jumps to the beggining of the hyperlink. In the attached image, I'm trying to click between the elipses, but the cursor always moves to just before the 'R'.
<img width="162" alt="samp" src="https://user-images.githubusercontent.com/37098565/72232531-aa2ea300-358f-11ea-8dac-72366103b1cf.png">

This is especially problematic if the hyperlink is the first item in a paragraph, and you want to add more text before it. You must either remove the hyperlink, add the text, then add the hyperlink again, or, type the text somewhere else, then copy and paste it to the desired location.

I've noticed many of these minor text editing symptoms. Please advise, should I create a new issue for every one? Or should I compile a list and create one issue for all of them?

Windows 10
Edge BETA
Gutenberg 7.1

**Comment by youknowriad** [comment]
Gutenberg (and the classic editor) use what we call "format boundaries". This means each format (bold, italic, link...) has two caret positions at the beginning and at the end of the format and since these two positions are not visually separated, a click there will choose one over the other.  In that case, it chose the one inside the format and not outside it but you can easily navigate in and out of the format using the arrow keys in the keyboard.  So try clicking "left arrow" when the caret is at the beginning of the link to move out of the link and start typing. 

You'll notice that if you're inside a format (link, bold...), the text is highlighted a little bit.

I hope this fixes your issue.
