### ISSUE TITLE
Color Picker saturation overlay is offset until saturation picker moves

### ISSUE THREAD

**Issue by jeryj** [WordPress/gutenberg#19610]
**Describe the bug**
When the color picker is first rendered (before moving the saturation picker), the saturation background is offset to the left.

**To reproduce**
1. Go to the editor
2. Add a navigation block
3. Edit the text color of the navigation
4. Click the "custom color" link/button
5. See the offset saturation (the right 8px or so will be a solid, bright color)
6. Move the saturation picker and the saturation will snap into the correct spot

**Expected behavior**
The light/dark saturation background should span the entire background instead of being offset.

**Screenshots**
<img width="288" alt="Screen Shot 2020-01-13 at 4 19 32 PM" src="https://user-images.githubusercontent.com/967608/72297470-9f245300-3621-11ea-92af-48b1e4145291.png">
<img width="527" alt="Screen Shot 2020-01-13 at 4 22 19 PM" src="https://user-images.githubusercontent.com/967608/72297471-9fbce980-3621-11ea-8e2e-3bde4c7a7bd5.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version 79.0.3945.88

**Additional context**
Gutenberg 7.2.0

**Comment by Addison-Stavlo** [comment]
This is a very interesting issue.  I have been poking at this for a while now and although I see what is happening, none of the css tricks that I think would solve it seem to do so.  I just can't seem to get rid of that offset when the pointer starts on the right end of the saturation box without messing up the pointer's behavior across the other edges of the box.

The best fix I can come up with currently is changing it so that the bar on the right ends up being white instead of the base color.
![Screen Shot 2020-01-15 at 12 19 52 PM](https://user-images.githubusercontent.com/28742426/72455950-b8e4a800-3791-11ea-8d80-a9a651e5be52.png)
All other behavior is identical, its just that bar on the right is now white instead of colored.  It does seem like a step forward in that it looks a little less broken, but it still looks broken to me.  I wonder if this partial fix is even worth opening a PR for? 

I think a better fix is possible, but at this point im thinking it may take a much more complicated approach than just changing a CSS rule as done above.

**Comment by jeryj** [comment]
I hadn't noticed that it only happens when the button for the saturation selector is on the edge. Thanks for pointing that out!

I poked around as well with that and also hit a dead end. It's so strange that it wants to "make room" for the button on the right when it renders, but doesn't care after you move it around. 

The white background _does_ look better, but I wonder if the pure background color (like the original bug) is preferable since it shows you the base color you're working with.

This is a weird one for sure. I'm really curious what the fix would end up being.

**Comment by Addison-Stavlo** [comment]
I wish there was some CSS rule to make this work correctly (maybe there is, but I just can't find it), but I did find a simple way to fix this with javascript.  The PR listed above does that. 😄
