### ISSUE TITLE
Buttons block: aligning broken

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#19616]
None of the alignment buttons of the buttons block work.

**Comment by tijosh** [comment]
The alignment works, but you have to select the parent `Buttons` block rather than the `Button` itself:

![Screenshot](https://d.pr/i/xnbOq0+)

Then, you can select the desired alignment: 

![Screenshot](https://d.pr/i/Sm9rvK+)

![Screenshot](https://d.pr/i/yULL7J+)

Less than ideal—it would be good if choosing the individual button's alignment also set the parent container's alignment.

**Comment by ellatrix** [comment]
Sounds like the individual buttons should not have any alignment buttons then.

**Comment by strarsis** [comment]
Well, the buttons block contains button blocks, hence it acts as a container of button blocks.
What if a designer makes a more fancy buttons block, e.g. one that aligns all its button blocks into a ring? What if some of these button blocks should be aligned to the right and some to the center, etc.?
Just removing the individual alignment options from a single button block inside a buttons block would also take some possibilities away from the theme designer. What about just hiding that option or making it possible to be enabled by the theme?
