### ISSUE TITLE
Nav Block: Editing a link should show search results

### ISSUE THREAD

**Issue by apeatling** [WordPress/gutenberg#19647]
**Describe the bug**
When I edit a navigation link I only see the search term in the box, I don't see any search results so I can select something different. Only when I edit the search term do I see search results.

See this gif for an example:

![2020-01-14 12 02 02](https://user-images.githubusercontent.com/1464705/72378281-ec5a0080-36c5-11ea-803f-2ac25f3bc52a.gif)

**To reproduce**
1. Select a navigation link in the navigation block
2. Select the "Link" menu
3. Click the "Edit" button on the popup
4. See the link inserter with the link text in the search box, but no results
5. Edit the link text in the search box to see results

**Expected behavior**
I should see search results as soon as I hit the "Edit" button. I might have selected the wrong page or post and want to choose a different result.

**Comment by getdave** [comment]
May require changes to `LinkControl` and/or (the underlying) `URLInput`.

**Comment by getdave** [comment]
This will be tricky because triggering of fetching search results is controlled by the inner mechanics of the underlying `URLInput` component. There is no way to programmatically trigger this fetching. It is triggered by:

1. `onChange` in the `<input />`
2. When there is no value (to show initialSuggestions).

I was thinking we might be able to just try always triggering `updateSuggestions` on each `componentDidUpdate` but _only_ if 

1. `this.isUpdatingSuggestions` is not set 
2. `<input />` has a value with length which is no empty whitespace.

We'd need to be careful though cos then we'd need to avoid calling [`updateSuggestions` in the `this.onChange` method.](https://github.com/WordPress/gutenberg/blob/dcb08f311b3e1e68108ea1a02fb71765731a8cf9/packages/block-editor/src/components/url-input/index.js#L172).

Would need careful unit and manual testing to avoid infinite loops.

**Comment by getdave** [comment]
Also worth noting that this implementation may all change due to this discussion https://github.com/WordPress/gutenberg/issues/18061. However, that looks someway down the road.

**Comment by WunderBart** [comment]
> It is triggered by: 1. onChange in the <input />

If the seach is triggered `onChange`, could it also be triggered (and handled by the same handler) `onFocus`?

Somewhere between [these lines](https://github.com/WordPress/gutenberg/blob/dcb08f311b3e1e68108ea1a02fb71765731a8cf9/packages/block-editor/src/components/url-input/index.js#L348), like this:

```javascript
<input
  ...
  onChange={ this.onChange }
  onFocus={ this.onChange }
/>
```

@getdave @jeryj

**Comment by jeryj** [comment]
@WunderBart That does seem to work fine in my testing. It maybe feels a little hacky to call the `onChange` with the `onFocus`, but it works surprisingly well for a one line change on a complicated component! Nice idea!

**Comment by jeryj** [comment]
I think there's going to be more to do than simply triggering a search, as it searches for the URL and not the linked label/page if it's internal. This means, if you hit enter, it disconnects it from the internal page and considers it a plain link.

It seems this issue will take more than just triggering the suggestions based on the URL.

![clicking url link changes the label](https://user-images.githubusercontent.com/967608/73018905-1e671300-3de8-11ea-98c5-95452432360f.gif)

**Comment by getdave** [comment]
This is also causing a problem for me in https://github.com/WordPress/gutenberg/pull/19775, as when an error is shown when Page Creation fails we need to reshow the search results and the Create button. 

![Screen Capture on 2020-01-24 at 11-27-09](https://user-images.githubusercontent.com/444434/73065891-8e36d580-3e9c-11ea-9657-3a61ae0eebce.gif)

**Comment by getdave** [comment]
@jeryj @WunderBart I have found a way around this on my PR. It's a bit of a hack though so we might need to see what the Core team think. Effectively what I'm doing is forcing the input to detect a new change. I'm doing this by [resetting it to an empty string and then immediately setting it back again to the original value](https://github.com/WordPress/gutenberg/pull/19775/commits/e5bcb32ea271f160f260277241912230f0d17c56#diff-106913d5079b57c6032c0775292d8d9dR146).

This works!
