### ISSUE TITLE
Gutenberg playground and undo history for standalone editor

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#19663]
I'm posting this more as a question/conversation.

I've been experimenting with using Gutenberg as a standalone editor, outside of WordPress. The [Gutenberg playground](https://github.com/WordPress/gutenberg/blob/7f12830ca3c302e4fee8a49de1121376db8696d6/storybook/stories/playground/index.js) has been very useful for this, and it's great that it's possible to extract the editor side of Gutenberg from WordPress.

However, some of what I would consider 'core editor' functionality does seem to be tied to the WordPress side of Gutenberg, and not directly available from a playground style setup.

For example, the undo/redo history is (I think) tied to the concept of a post, and post entities. If you use the Gutenberg playground you will see that undo/redo is not available:

https://wordpress.github.io/gutenberg/?path=/story/playground-block-editor--default

Naively trying to bind the keyboard shortcuts and issuing the appropriate undo/redo actions has no effect - the underlying data is not there.

For my experiments the only way I was able to get undo history was to introduce `<EditorProvider>` instead of `<BlockEditorProvider>`. This then required a bunch of WordPress specific stuff, along with using the Redux data stores instead of local state, and the creation of a pseudo post entity to keep everything happy.

I appreciate that the playground is just a playground, and I know that the focus of Gutenberg has been to create an editor for WordPress.

Is it possible to add undo history to the Gutenberg playground without either re-implementing it yourself, or introducing posts? If not, should undo history be made available in a more agnostic way? It seems a fundamental part of an editor experience.

**Comment by youknowriad** [comment]
Hi There!

The playground is one possible implementation but it seems like it could be easy to implement your own undo, by storing the different versions of `onChange` calls in an array or something like that. If you're using Redux to store your blocks, there's already a bunch of Redux middlewares that would allow you to do this very easily.

In Gutenberg it doesn't make sense to implement Undo/Redo at the block editor level because we need undo/redo for the whole screen and not just the block content.

I hope this helps.
