### ISSUE TITLE
Block Placeholder: Notices

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#19671]
**Describe the bug**
Notices look off in the new block placeholder:
<img width="477" alt="Screenshot 2020-01-15 at 14 42 06" src="https://user-images.githubusercontent.com/275961/72442970-66ad8200-37a5-11ea-83ab-9fdcb0d09eff.png">

**To reproduce**
1. Add a block that uses notices in the placeholder
2. Make an error happen
4. The padding around the notice looks wrong

**Expected behavior**
In the old design Notices looked fine in this contect

**Screenshots**
<img width="477" alt="Screenshot 2020-01-15 at 14 42 06" src="https://user-images.githubusercontent.com/275961/72442970-66ad8200-37a5-11ea-83ab-9fdcb0d09eff.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome

**Additional context**
- Please add the version of Gutenberg you are using in the description: Lateset

**Comment by epiqueras** [comment]
What is another block where this happens?

This seems to be specific to this Calendly block which is not part of Core.

**Comment by p-jackson** [comment]
> What is another block where this happens?

This also affects the File block, which shows a notice when the file isn't permitted.

<img width="661" alt="image" src="https://user-images.githubusercontent.com/1500769/73724163-9beb3580-478f-11ea-9b54-c52a4abe27c3.png">

Looks like this issue was introduced in #18745. Previously `<Placeholder>` content was centred, and there are custom margins being applied to `<NoticeList>`s inside `<Placeholder>`s as if this were still the case.

**Comment by epiqueras** [comment]
cc @jasmussen was this intended?

**Comment by jasmussen** [comment]
> was this intended?

Hi! No, this was not intended. If you have bandwidth to address this feel free to, otherwise I can look at it next week.

**Comment by epiqueras** [comment]
Done

**Comment by scruffian** [comment]
This is being tracked by https://github.com/WordPress/gutenberg/pull/20024

**Comment by epiqueras** [comment]
That's an **unmerged** PR. This is the issue.

**Comment by scruffian** [comment]
Oh whoops, sorry :)
