### ISSUE TITLE
LinkControl - remove URL protocol from Entity (only!) search results

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#19670]
Could the URL protocol be dropped?

_Originally posted by @mtias in https://github.com/WordPress/gutenberg/issues/19513#issuecomment-573070658_

This refers to removing `https://` (or similar) on all Entity (eg: `Post/Page`) search results. This does _not_ apply to direct entries.

So `https://www.mywebsite.com/?p=1234` would be displayed as `www.mywebsite.com/?p=1234` with the `https://` removed.

**Comment by aduth** [comment]
My initial reaction here is that we should want to be consistent with how these links are presented, either always showing or always omitting the protocol, since a disparity could lead to additional code maintenance overhead and user confusion.

I guess the idea is that:

- The protocol isn't very nice to see
- For the current site, it's likely assumed to be "known" already and thus a redundant detail
- It's important (?) to show the protocol for all other URLs, since a user could want to distinguish

Is the last of these necessarily true though? As a user, is this an important detail for me in choosing amongst a set of suggestions related to my search query? Are there other options for me to get that detail if it was important to me, preferably in a context which is most appropriate (i.e. could I see it in the "View" mode of the link, or at worst I'd still have the option when editing the link again?)

As one point of reference, Google's new redesign doesn't bother to make any distinction of the protocol in the search results. In the following screenshot, the two links are HTTPS and HTTP respectively:

![image](https://user-images.githubusercontent.com/1779930/73491195-0cebb100-437c-11ea-9be1-3a621bc6f058.png)

Then again, Google's redesign has been widely panned, especially in regards to their presentation of links (though from my readings, moreso on how it obscures the _path_), so it might not be the best example from which to draw conclusions.

**Comment by draganescu** [comment]
I added an alternative PR to @sainthkh 's to remove the display of the protocol. This combined with #21050 which deprecated the use of URL for internal links when rendering, raises how and when should we store the URL in the navigation block? 

- All the time for consistency?
- Only for external URLs?
- For internal links, should we store it without protocol but with the protocol omit format, e.g. `//localhost/category/post-name` so that the browser can use the current protocol?
