### ISSUE TITLE
Nav Block: Aligning items right does not provide any default edge padding

### ISSUE THREAD

**Issue by apeatling** [WordPress/gutenberg#19688]
⚠️ **IMPORTANT**
Let's wait until #19681 ships before to work on this, since it will introduce many changes in the styles organization.

-----------------

**Describe the bug**
Using the navigation block and aligning items right doesn not provide any default edge padding so the items hit right up against the edge of the container. There is some default spacing when aligning left on the left edge.

<img width="1054" alt="Screen Shot 2020-01-15 at 3 10 50 PM" src="https://user-images.githubusercontent.com/1464705/72479500-76c76080-37a9-11ea-9dce-d229206806b1.png">

**To reproduce**
1. Add a navigation block with some items
2. Use the "justify items right" option
3. View the nav block in the front end

**Expected behavior**
There should be some default padding to stop it hitting against the edge of the container.

**Comment by apeatling** [comment]
The same actually applies to items aligned left.

**Comment by obenland** [comment]
Let's double-check padding in all three alignments and make sure center-aligned doesn't get off center by residual paddings.

**Comment by retrofox** [comment]
It was already fixed in https://github.com/WordPress/gutenberg/pull/19681

Tested with `maywood`

**no alignment**
![image](https://user-images.githubusercontent.com/77539/73696995-598ffe80-4692-11ea-8102-f6c7128ea833.png)

**wide**
![image](https://user-images.githubusercontent.com/77539/73697010-6876b100-4692-11ea-9327-83a8c9db3d06.png)

**full**
![image](https://user-images.githubusercontent.com/77539/73697032-74627300-4692-11ea-91da-c2ceb2df3ae7.png)


Just in case, it applies the padding as default here:
<img width="990" alt="Screen Shot 2020-02-03 at 2 36 18 PM" src="https://user-images.githubusercontent.com/77539/73697133-b12e6a00-4692-11ea-9bc8-0085f094a48e.png">
