### ISSUE TITLE
Paragraph block: Selecting text from end to beginning will also select the block

### ISSUE THREAD

**Issue by AtrumGeost** [WordPress/gutenberg#19702]
**Describe the bug**
If you select a text you want to delete from end to beginning, the block is also selected and thus deleted.

**To reproduce**

0. Install and activate the Gutenberg plugin
1. Open the editor
2. Add a couple of paragraphs
3. Select the first sentence on the paragraph  from end to beginning
4. Hit the backspace key

**Expected behavior**
For the first sentence to be deleted. 

**What happened instead**
The whole block was deleted.

**Screenshots**

![Screen Capture on 2020-01-16 at 07-19-17](https://user-images.githubusercontent.com/3696121/72527161-20ecca00-3836-11ea-816f-cb462affe5e4.gif)

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.2 (19C57)
 - Browser Chrome Version 79.0.3945.117 (Official Build) (64-bit)

**Additional context**
- I was able to replicate this behavior on WordPress.com
- On WordPress.org you can only replicate it if you have the Gutenberg plugin (Version 7.2.0) active

**Comment by youknowriad** [comment]
This seems like a regression. Any idea what might have caused it @ellatrix

**Comment by ellatrix** [comment]
Interesting. @AtrumGeost did this ever work for you?

I see that, when you select from end to start, the focussed element end up being the block element instead of the rich text element. If this is a regression, it must be caused by the new multi selection behaviour. When you leave a bock, the rich text element will be disabled and multi selection will be enabled. If you stop outside the rich text element, the element will be enabled again, but it won't receive focus. I'm not sure if this worked before either though, because we didn't have any logic in place to refocus the anchor element.

I'll look for a fix.

**Comment by AtrumGeost** [comment]
Hi @ellatrix ! This was reported by a user. It works normally with the Gutenberg "core" version:

![Screen Capture on 2020-01-17 at 08-56-22](https://user-images.githubusercontent.com/3696121/72617646-6deca100-3907-11ea-8eb8-72a8c70d5439.gif)

You can only replicate the issue while having the Gutenberg plugin active
