### ISSUE TITLE
Consider to find a solid way to avoid events conflicts with nested components

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#1973]
DOM events (especially keyboard events since a single keypress has many different events that fire) when used on multiple and _nested_ components may lead to unexpected behaviors. For example, while working on the DropDown menu currently used in the table block:

<img width="754" alt="screen shot 2017-07-21 at 15 20 40" src="https://user-images.githubusercontent.com/1682452/28467285-af2e934e-6e2f-11e7-87d4-56b7c6875688.png">

at first, I couldn't realize why pressing Escape when the menu is open closed the menu and also made the whole toolbar disappear. Turns out the `VisualEditorBlock` component [is using a few events](https://github.com/WordPress/gutenberg/blob/252937b8ea6159879963b65639900c35f7d235b3/editor/modes/visual-editor/block.js#L349-L354) including keydown and keyup.

At the same time, the menu is using keydown and it's correctly preventing its propagation. However, when pressing _and releasing_ Escape, that's also a `keyup` event that propagates to the block, making the toolbar disappear.

With nested components, this kind of behaviors might happen in other scenarios too, leading to unexpected behaviors and time spent in debugging.

There are solutions, but not so ideal because ideally any component should be "isolated" and work outside of the box without having the need to have some knowledge about other components.

See also https://wordpress.slack.com/archives/C02QB2JS7/p1500643535380467.

Trying to find a solid high-level solution for the future would be great.

**Comment by afercia** [comment]
I understand this issue is too generic. I’d rather consider to mention this as a best practice in the documentation for plugin authors.

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1520531993000020)._

**Comment by noisysocks** [comment]
I've definitely noticed that bugs due to a missing `event.stopPropagation()` keep popping up.

It would be nice to have a generic solution to this. I don't think we can use portals because having a component render outside of its parent's DOM will break styling in a lot of cases.

Maybe a component that stops its children from propagating key and form events would suffice?

```js
function stopEventPropagation( event ) {
	event.stopPropagation();
}

function EventBoundary( { children } ) {
	return (
		<div
			// Key events
			onKeyDown={ stopEventPropagation }
			onKeyPress={ stopEventPropagation }
			onKeyUp={ stopEventPropagation }

			// Form events
			onChange={ stopEventPropagation }
			onInput={ stopEventPropagation }
			onInvalid={ stopEventPropagation }
			onSubmit={ stopEventPropagation }
		>
			{ children }
		</div>
	);
}

// Usage:

<EventBoundary>
    <input type="text" placeholder="Go ahead, press arrow keys in me" />
</EventBoundary>
```

Alternatively, we could try to make `<ObserveTyping>` smarter in some cases. For example, we might not trigger `startTyping()` if the event target is nested within a `<Toolbar>` or `<InspectorControl>`.

I recall @aduth worked on something to do with ignoring descendent events which might also help here.

**Comment by designsimply** [comment]
> I couldn't realize why pressing Escape when the menu is open closed the menu and also made the whole toolbar disappear.

I tested just now with Firefox 61.0.1 on macOS 10.13.6 and found that the escape key correctly closes toolbar dropdown without closing the toolbar. ([24s](https://cloudup.com/cpKQOgOWA6r))

> With nested components, this kind of behaviors might happen in other scenarios too, leading to unexpected behaviors and time spent in debugging.

@afercia I also tested a table block nested inside a columns block and didn't see the problem there either. I am going to close this issue because it seems resolved based on my testing today. Please do let me know if you can think of additional scenarios to test and I'll re-open. 🙂

**Comment by afercia** [comment]
@designsimply agree. It's my opinion that we'll see more errors like these ones though. At the very least there should be a recommendation to always stop events propagation. This should be clearly explained in the documentation. As noted above, a built-in solution would be nice.
