### ISSUE TITLE
Sticky Posts and visibility options are missing meaningful errors

### ISSUE THREAD

**Issue by spencerberry** [WordPress/gutenberg#19746]
**Describe the bug**
Marking a post as "stick to top of the blog" requires the post to also be public.

If you set it to Password protected, there is a generic error when you try to update or publish:

> Updating failed. An unknown error occurred.
> Publishing failed. An unknown error occurred.

This error is unhelpful.

It is also very easy to lose your work if you set these two options and then make changes to the post. Nothing will be saved as long as sticky and a password protected visibility is set.

**Expected behavior**
I would expect to not be allowed to set this combination in the first place, if the design intent is to not allow it.

A state where your post will not update or save changes is a state that should be avoided entirely, in my opinion.

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.2 Catalina 
 - Browser Chrome Version 79.0.3945.117 (Official Build) (64-bit)
- Tested on both WordPress.com Premium and Gutenberg 7.2.0 plugin.

**Comment by jorgefilipecosta** [comment]
Hi @spencerberry, I repeated the test and it seems in the last version of Gutenberg I'm getting a meaningful error "Publishing failed. A post can not be sticky and have a password.". I'm closing the issue for now if in your tests you are still getting non-meaningful errors please leave a comment and I will debug the issue further.

**Comment by assad-ebrahim-uk** [comment]
This raises the design intent question.  Is there any reason why we cannot have a sticky and password protected post?

Use case:  I run a research program where the participants publish (publicly) when ready, but otherwise use password protection to publish them internally (not public).  We have a top level research program page which is internal (password protected) and would like it to be sticky so it appears first in the main page.
