### ISSUE TITLE
Additional CSS Class(es) not working on Navigation Block

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#19858]
**Describe the bug**
Adding **Additional CSS Class(es)** on Navigation block isn't reflecting on the editor and only added on the frontend. While on the Navigation link, adding custom classes were not applied on both editor and frontend. Thanks!

**Comment by pagelab** [comment]
I was able to reproduce this using Gutenberg version 7.3.0.

**Comment by roo2** [comment]
I had a look at fixing this, there are two issues:
1) The Navigation Block's *Additional CSS Class(es)* are not rendered in the editor.
** The addisional CSS Classes are rendered on the live page correctly [x]
** This one is very easy to fix but I think the impact is very low since custom CSS is not applied in the editor anyway
2) `Navigation Link` components do not have their *Additional CSS Class` applied at all
** this is much more involved to fix, I looked into `packages/block-library/src/navigation/index.php` but it looks like the `Navigation Link`'s Additional css class is currently passed in to this function.

For people coming from google, a workaround would be to style the Navigation Link's using e.g. nth child selectors.

**Comment by draganescu** [comment]
Hi @phpbits can you take a look at #20076 and let me know if it solves this as expected?

**Comment by phpbits** [comment]
@draganescu Tested and seems to be working fine. Custom classnames are being added. Thanks!
