### ISSUE TITLE
Latest Posts: changing number of posts doesn't refresh

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#1991]
This is a regression. Changing number of posts doesn't update the block until you save and reload the post.

**Comment by westonruter** [comment]
Taking a look…

**Comment by mtias** [comment]
Looks like `postToShowCurrent === postToShowNext` is returning `true`.

**Comment by westonruter** [comment]
The regression was introduced as part of #1889. /cc @aduth

**Comment by aduth** [comment]
I'm not able to reproduce. Can we be more specific with steps, or what of #1889 caused the regression?

**Comment by westonruter** [comment]
@aduth I used Git bisect to find the commit that caused the problem. It was among the commits in #1889. Specifically, a0584931ecbeb09ecfefeac7cd0e07d6471386c4 first made it so that that number field couldn't be changed at all, and then the following commit 0f6a5915f824e457d0478a8b790cf34af647621e allowed the field to be modified again, but then the changes to the field didn't cause any changes to be reflected in the component. At the previous commit 012c0ee387a89e83dadebc468f51d37d890e6797, the first commit in the PR, the posts shown field is editable and its changes are reflected in the block.

**Comment by mtias** [comment]
It is fixed after https://github.com/WordPress/gutenberg/pull/1995
