### ISSUE TITLE
Preview fails to display meta data on pages/posts in Gutenberg and Unyson custom theme

### ISSUE THREAD

**Issue by john-ampwebdesign** [WordPress/gutenberg#19933]
I am working on a custom theme that includes custom meta items that can be changed on a page or a post. Much like ACF fields in request [16006](https://github.com/WordPress/gutenberg/issues/16006) and [12617](https://github.com/WordPress/gutenberg/issues/12617) but in this case the user can change a hero image, sidebar content and more right from the editor page. Currently using WordPress 5.3.2. Removed all plugins except Unyson which is needed for the custom theme. 
Issue steps: 

1. Create new page
2. Add H2 header and content with Lorem Ipsum
3. Click preview - preview renders okay
4. Change content - preview renders okay
5. Add new sidebar content via theme's custom meta block
6. click preview and only see step 4 content
7. Allow to autosave, click preview and I see content and custom sidebar content
8. Change sidebar content
9. click preview and sidebar content does not change
10. Publish (or update page), view page or click preview can see all content changes

I have tried the code that was posted by Btoko4 into the functions.php file and nothing changes. 

Like others, if I change to WP 2020 theme, the preview works as expected as the meta values are only present on the new theme so this doesn't help in bug solving.

Unyson plugin is the most recent and they replied that it isn't something the plugin is doing wrong.

The task I have, like others, is to capture/save the meta block data and present it in the preview.

I have followed the other help requests related to this but so far none of their fixes have helped.

Any help or further direction is appreciated.

**Comment by defunctl** [comment]
I believe this is because WordPress is deleting the revision, returning 0 on every odd preview because it can't detect that anything has changed in the post, even if it's added to `_wp_post_revision_fields()`: https://github.com/WordPress/WordPress/blob/037a73675722c40557f9507717c9548fdd031d0d/wp-admin/includes/post.php#L1837

Give this mu plugin a go (place it in wp-content/mu-plugins, make the directory if it doesn't exist) and see if helps: https://gist.github.com/defunctl/ecae2d6cdb78762aa8e8e043a6161d23

It forces WordPress to create an autosave after core has deleted the autosave before the preview is loaded. 

Can't promise it'll work, but any problems just delete the file you created.

Just thought I'd share as this seems to be an ongoing issue and hopefully it helps someone.

**Comment by talldan** [comment]
@john-ampwebdesign Thanks for reporting. This is a known issue and tracked on #16006. I'll close this one as a duplicate.
