### ISSUE TITLE
Block Editor: ⨁ icon and Block toolbar are missing in Microsoft Edge 18

### ISSUE THREAD

**Issue by chriskmnds** [WordPress/gutenberg#19979]
**Describe the bug**
It has been reported [here](https://github.com/Automattic/wp-calypso/issues/39072) (props @zdenys) that Microsoft Edge 18 users are not able to see the block inserter button ⨁ when hovering over blocks, or the block toolbar when clicking on them.

We confirmed briefly that this is not a wp-calypso or WPCOM specific issue. It happens on local WP installs running Gutenberg 7.3.0 (may happen in previous versions too). 

**To reproduce**

1. Starting at URL: Any Post/Page with some Blocks added
2. Hover over spots in between various Blocks
3. Select any Block

**Expected behavior**

- See the ⨁ icon appearing to add a Block in that spot
- See the Block's toolbar above it when any Block is clicked (selected)

**Screenshots**

Link: https://d.pr/i/lgdogS

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge 18

**Additional context**
Refer to https://github.com/Automattic/wp-calypso/issues/39072 for more reports of the incident from WPCOM users.

**Comment by chaitanyamsv** [comment]
A user reported in 18438062-hc

**Comment by aduth** [comment]
My understanding is the issue may be caused by the introduction of `window.DOMRect` in a few places in code:

https://github.com/WordPress/gutenberg/blob/c6b019b6f7bc46847e45d9f664c749540a1fb9b6/packages/block-editor/src/components/block-list/insertion-point.js#L121

https://github.com/WordPress/gutenberg/blob/c6b019b6f7bc46847e45d9f664c749540a1fb9b6/packages/components/src/popover/index.js#L81

https://github.com/WordPress/gutenberg/blob/c6b019b6f7bc46847e45d9f664c749540a1fb9b6/packages/components/src/popover/index.js#L316

Internet Explorer and Edge do not support this feature:

https://developer.mozilla.org/en-US/docs/Web/API/DOMRect#Browser_compatibility

A solution is to include a polyfill. #19823 can be used as prior art, with an equivalent upstream Core patch at [Trac#49360](https://core.trac.wordpress.org/ticket/49360) as reference for when this code makes its way to WordPress.

The `polyfill-library` we have used for `Node#contains` and `URL` does appear to have a polyfill for `DOMRect` as well, which is fortunate and the obvious choice:

https://github.com/Financial-Times/polyfill-library/tree/master/polyfills/DOMRect

cc @ellatrix
