### ISSUE TITLE
@wordpress/env: Allow configuration of `wp-config.php` constants in `.wp-env.json`

### ISSUE THREAD

**Issue by WraithKenny** [WordPress/gutenberg#19972]
**Is your feature request related to a problem? Please describe.**
It'd be useful to be able to add `wp-config.php` constants to the Env config.

**Describe the solution you'd like**
`wp-env.json` should support something like:
```
{
  "themes": [
    "../path/to/theme/dir"
  ],
  "plugins": [
    "../path/to/plugin/dir"
  ],
  "config-extra": {
    "SAVEQUERIES": "true",
    "JETPACK_DEV_DEBUG": "true",
  }
}
```
These values should be passed into the `docker-compose.yml` under `WORDPRESS_CONFIG_EXTRA`

**Describe alternatives you've considered**
The alternative is using my own `docker-compose.yml`

**Comment by epiqueras** [comment]
cc @noisysocks

**Comment by noisysocks** [comment]
Yep, let's do it.

Some notes regarding implementation:

- It must be possible to configure the [WordPress debug constants](https://wordpress.org/support/article/debugging-in-wordpress/), namely: `WP_DEBUG`, `WP_DEBUG_LOG`, `WP_DEBUG_DISPLAY`, and `SCRIPT_DEBUG`. `WP_DEBUG` and `SCRIPT_DEBUG` should be enabled by default.

- Constants should be configurable using `.wp-env.json` only and not e.g. using an environment variable. This is because WordPress constants are generally a _per project_ setting. See https://github.com/WordPress/gutenberg/pull/20158#issuecomment-585521944. Also, using JSON for this means that we can avoid issues where e.g. a constant must be `true` instead of `"true"`.

- The local `wp-config.php` file, if it exists, should be updated when `wp-env start` is ran so as to ensure that the config in `wp-config.php` matches the config specified in `.wp-env.json`. Only the constants specified in `.wp-env.json` should be modified: that is, any other code that is in `wp-config.php` should not be touched. To do this we will need to roll our own `wp-config.php` generation using [`wp config create`](https://developer.wordpress.org/cli/commands/config/create/) and [`wp config set`](https://developer.wordpress.org/cli/commands/config/set/). Right now we are relying on the `wordpress` Docker image to generate the `wp-config.php` but this is not flexible enough to handle updates to arbitrary constants—it can only update database constants.

- Because `wp-env` is a tool specifically for WordPress and _config_ in WordPress parlance has a very specific meaning, I think we can get away with using `"config"` as the key in `.wp-env.json`.

  ```json
  {
  	"themes": [
  		"../path/to/theme/dir"
  	],
  	"plugins": [
  		"../path/to/plugin/dir"
  	],
  	"config": {
  		"WP_DEBUG": true,
  		"SCRIPT_DEBUG": true,
  		"SAVEQUERIES": true,
  		"JETPACK_DEV_DEBUG": true
  	}
  }
  ```

**Comment by epiqueras** [comment]
>Only the constants specified in .wp-env.json should be modified: that is, any other code that is in wp-config.php should not be touched.

Why is that necessary?

**Comment by noisysocks** [comment]
If you're using a local install (e.g. `"core": "~/path/to/wordpress-develop/build"`) you may prefer to add code or constants to the `wp-config.php` manually. `wp-env` shouldn't blow those changes away if it can help it. At any rate, `wp config set` handles this correctly so we get it for free.

**Comment by epiqueras** [comment]
What about the same constants being already defined in `wp-config.php`, should we overwrite them?

I guess we should.

**Comment by noisysocks** [comment]
Yes, I think so.
