### ISSUE TITLE
Image Replace - Open Media Library - Media Library does not open with the current image selected

### ISSUE THREAD

**Issue by gsallman** [WordPress/gutenberg#20040]
**Describe the bug**
When wanting to edit the caption/description/title associated with an image in the media library, you cannot do so easily from within a post because the only way to edit that data is to click on Replace which does not select the image when you arrive in the Media Library. In previous versions, the image was selected in the Media Library.

**To reproduce**
1. Go to a post written a long time ago, on a site with several thousand images.
2. Click on replace for the image
3. Now find the image whose details you wanted to edit -- It's  almost impossible 

**Expected behavior**
When clicking Replace -> Open Media Library; the current image should be selected. This was the previous behavior of this function before the 'Replace' button was introduced.

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Firefox
 - Version: latest/irrelevant.

**Additional context**
- Gutenberg 7.3.0

**Comment by Ringish** [comment]
@gsallman I made a quick fix for this [here](https://github.com/Ringish/gutenberg/commit/9f5c96384f74b041aae7bd1db17b0c4e46691ada) with the expected behaviour.

<img width="556" alt="Skärmavbild 2020-02-06 kl  15 09 06" src="https://user-images.githubusercontent.com/3396172/73944368-bc7fd080-48f2-11ea-922f-c484b4fd4e3d.png">
<img width="1438" alt="Skärmavbild 2020-02-06 kl  15 09 15" src="https://user-images.githubusercontent.com/3396172/73944389-c4d80b80-48f2-11ea-9ccc-04b120a8ac45.png">

**Comment by gsallman** [comment]
Looking good. I'll keep an eye out for it in the next update.

**Comment by talldan** [comment]
cc: @draganescu.
