### ISSUE TITLE
Add Block: Cover Video

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#2007]
Like Cover Image, but for videos. Similar to Header Videos.

Was chatting with @jasmussen about whether this should be an option in Cover Image, or a new block. We determined it would be good as its own block since the settings would likely be different (like aspect ratio), and you'd have the added benefit of it showing up when you search "video."

**Comment by karmatosed** [comment]
I like this idea, I also think it would be popular. Anyone up for doing a mock?

**Comment by karmatosed** [comment]
As the project moves towards merge proposal, we are moving issues that aren't needed for that to projects. This doesn't mean they won't get done, they totally can and that's why we're moving to projects. This allows us to focus on the issues that have to happen to Gutenberg. I am closing this but it will live in projects.

**Comment by karmatosed** [comment]
As the project moves towards merge proposal, we are moving issues that aren't needed for that to projects. This doesn't mean they won't get done, they totally can and that's why we're moving to projects. This allows us to focus on the issues that have to happen to Gutenberg. I am closing this but it will live in projects.
