### ISSUE TITLE
Error When Saving with Fraktur Characters Included

### ISSUE THREAD

**Issue by dstark** [WordPress/gutenberg#20199]
Gutenberg in WordPress 5.3.2 gives the following error when you attempt to save a post that includes Fraktur characters: "Updating failed. Error message: Could not update post in the database"

For instance, inserting Fraktur P (𝔓, equivalent to HTML entity &Pfr;) in a post raises the error and does not allow the post to save. If you instead try to insert the character by editing the HTML and including &Pfr;, the HTML is automatically converted into the equivalent Unicode character, which then again doesn't allow the post to save.

Seemingly the only work around is to insert an HTML code block, and there include &Pfr; or one of the equivalent HTML designations for Fraktur P. Using an HTML block rather than a paragraph block doesn't automatically convert the designation for the HTML entity into the equivalent Unicode character. So in this workaround, the post can then be saved.

It would be helpful, however, if Fraktur P or any other Unicode characters could be inserted and saved directly within paragraph blocks without needing to go through the HTML editing process.

Thank you so much!

**Comment by youknowriad** [comment]
Hi There!

I'm not able to reproduce the issue with the last Gutenberg version. Did you try with the plugin to see if it's fixed there?

Thanks.

**Comment by dstark** [comment]
Hmmm ... that's interesting. With the Gutenberg plugin enabled (v7.5.0), I get the same error, which I've included in the attached screenshot.
![image](https://user-images.githubusercontent.com/205528/74541805-ec892e00-4f07-11ea-9f50-4853054bb764.png)

**Comment by youknowriad** [comment]
I know other persons had similar issues with special chars. I wonder if it's something related to how the database is setup.

**Comment by dstark** [comment]
Hmmm ... interesting. I haven't done anything custom there that I know of. It will be interesting to see if others chime in.

**Comment by karmatosed** [comment]
@dstark just checking if this is still an issue as not seeing any other reports.

**Comment by dstark** [comment]
Thanks for checking in. Yes, the issue does persist unchanged from what I described above. The error still comes up if I insert a Fraktur character directly. But I can (most times) work around this by creating an HTML block and using the HTML code equivalent (e.g., &#120083; for 𝔓). Occasionally, Gutenberg is a bit overly helpful and converts this HTML into the Fraktur character (which then causes the error in saving the post). But I'm usually able to save things okay with the HTML equivalents.

If I can provide anything further, please feel free to ask.

**Comment by talldan** [comment]
I couldn't reproduce the issue, the post saves fine when I tested. It may have been resolved, but if it still happens I'm fairly certain this wouldn't a Gutenberg issue, but either a REST API or database issue

@dstark If you're still experiencing this, it'd be good to verify that the payload sent from the block editor to the REST API is correct. Here's some fairly detailed steps if you're unfamiliar:

1. Create a new post
2. Insert the 𝔓 character
3. Open the developer tools
4. Switch to the network tab
5. Click the clear button
6. Save the post
7. In the network tab a new request should show up in the table, click it
8. Find the request payload and confirm that the 𝔓 character was properly sent

When I checked, this is what I see:
<img width="522" alt="Screenshot 2021-07-21 at 2 50 07 pm" src="https://user-images.githubusercontent.com/677833/126444701-d96d7dd2-09e6-463a-83e2-c1e72fb028f9.png">

Gutenberg seems to be sending the character correctly to the REST API.

So I think the issue lies either with something happening server side, or as hinted could be a database issue.

Another option is that it could be an inconsistency between browsers, so if you do see the wrong data being sent in the network request, it'd be great to know what browser you're using.

**Comment by ndiego** [comment]
This issue was reviewed in today's Editor Bug Scrub. We have been unable to replicate using the latest versions of Gutenberg and WordPress. Therefore, I am going to close this issue. If anyone can replicate it in the future, please feel free to reopen this issue with additional information.
