### ISSUE TITLE
InnerBlocks with template returning a block count of zero

### ISSUE THREAD

**Issue by buhlahkay** [WordPress/gutenberg#20243]
I’m trying to create a block with an InnerBlocks template. Since the block has a template, the block should start with at least 1 child. If the child count ever reaches 0, then I want to remove this block, since it would be empty.

The issue that I’m running into is that the value of “blockCount” is 0 for a split second when the block is first created, so it’s removing itself before it’s created. Is this expected behavior with getBlockCount, or is there a way to wait for the template to populate the InnerBlocks before I check the block count?

Tried StackOverflow and WordPress support forums already, but haven't gotten a response.

Here is my edit function for reference.

```
edit: props => {
  const { setAttributes } = props
  const { className } = props.attributes
  const { removeBlock } = useDispatch('core/block-editor')
  const { blockCount } = useSelect(select => ({
    blockCount: select('core/block-editor').getBlockCount(props.clientId)
  }))
  if (blockCount === 0) {
    removeBlock(props.clientId)
  }
  return (
    <div className={ className }>
      <InnerBlocks
        allowedBlocks={ ['my/block'] }
        template={ [['my/block']] }
        templateLock={ false }
        renderAppender={ false }
      />
    </div>
  )
}
```

**Comment by talldan** [comment]
@buhlahkay my understanding is that the inner blocks are created from the template by `synchronizeBlocksWithTemplate` when the `InnerBlocks` component mounts:
https://github.com/WordPress/gutenberg/blob/3d3c3e1e4539cd5884234d3d7375e290efde2749/packages/block-editor/src/components/inner-blocks/index.js#L41-L66

Because the parent block is already in the block editor store prior to its `InnerBlocks` mounting, it'll initially have that blockCount of 0.

I don't think there's a way to tell whether `InnerBlocks` has mounted and created its templated from the store. You may have to use a local ref to track when the initial blocks were created and then removed, e.g.:

```jsx
edit: props => {
  const { setAttributes } = props
  const { className } = props.attributes
  const { removeBlock } = useDispatch('core/block-editor')
  const { blockCount } = useSelect(select => ({
    blockCount: select('core/block-editor').getBlockCount(props.clientId)
  }))
  const previousBlockCount = useRef( blockCount );
  useEffect( () => {
     if ( previousBlockCount.current > 0 && blockCount === 0 ) {
      removeBlock( props.clientId );
    }
    previousBlockCount.current = blockCount;
  }, [ blockCount, props.clientId ] );

  return (
    <div className={ className }>
      <InnerBlocks
        allowedBlocks={ ['my/block'] }
        template={ [['my/block']] }
        templateLock={ false }
        renderAppender={ false }
      />
    </div>
  )
}
```

I haven't tested that code, but something like this should theoretically work. I followed the FAQ example here for using a ref to store the previous state:
https://reactjs.org/docs/hooks-faq.html#how-to-get-the-previous-props-or-state

I'll close the issue for now, but do reply to let me know how you get on. Would also be great if you could update those Stack Exchange and forum topics with the answer if this works.

**Comment by buhlahkay** [comment]
@talldan Thanks this is exactly what I was looking for. And it forced me to learn more about hooks! Will update the other posts with your answer.
