### ISSUE TITLE
Nav Block "Create" option sometimes requires scroll 

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#20272]
**Describe the bug**

Originally raised by @aduth in https://github.com/WordPress/gutenberg/pull/19775#pullrequestreview-359127802.

> Minor design note: I barely noticed there was even an option for creating a page here, and that's despite the fact that I have scrollbars shown to be always visible, which I find that most macOS users don't (but should!).

![image](https://user-images.githubusercontent.com/1779930/74557750-d773c580-4f2e-11ea-9a56-47ebe3cb0a8c.png)

Note that the "Create Page" search suggestion is hidden in the search results and you need to scroll to see it.

**To reproduce**
TODO

**Expected behavior**
You should always be able to see the "Create" option.

**Desktop (please complete the following information):**
All viewports.

**Smartphone (please complete the following information):**
All platforms.

**Comment by jasmussen** [comment]
We could sort it at the top?

**Comment by getdave** [comment]
Does this even still occur? The original report is very old.

**Comment by jasmussen** [comment]
It does, but it's mitigated by the menu not showing all types at once. If you have a lot of pages that start with the same two letters, the "Create" would be out of sight:

<img width="575" alt="Screenshot 2021-02-01 at 10 57 07" src="https://user-images.githubusercontent.com/1204802/106443028-5170c780-647c-11eb-87f1-eb015433d604.png">

However because it's mitigated, and because the "Create page" arguably _should_ be at the end, I'm tempted to close it.

**Comment by jasmussen** [comment]
I'm going to close this one for the time being, and encourage anyone to reopen it if it surfaces as a problem!
