### ISSUE TITLE
Unclear CSS in block editor

### ISSUE THREAD

**Issue by chris985** [WordPress/gutenberg#20396]
Why is there a global rule being set on our sites? This should NOT be something gutenberg is doing. Breaks mobile-responsive websites by making them unable to scroll on mobile. Is this a joke? Disabling gutenberg of course fixes the problem and removes the CSS being added.

```
html {
	position: fixed;
	width: 100%;
}
```
/wp-content/plugins/gutenberg/build/block-editor/style.css?ver=1581705661:1

**Comment by Soean** [comment]
This style should only be loaded in the editor, not on the frontend. This code comment explains why it was added:
```
// On Mobile devices, swiping the HTML element should not scroll.
// By making it fixed, we prevent that.
```
https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/editor-skeleton/style.scss#L1-L5

**Comment by swissspidy** [comment]
Certainly not a "joke".

If this stylesheet is loaded on your website's frontend, I recommend checking your theme and active plugins to find the culprit. It's not something Gutenberg is doing.

**Comment by talldan** [comment]
That has also been inadvertently fixed by this change:
https://github.com/WordPress/gutenberg/pull/20245/files#diff-4d8551b27a54fe4f0a0a70e0df53ae98R3

It shouldn't be an issue in 7.6. But as others have mentioned it seems like a theme or plugin is loading the editor's styles for your website, which shouldn't be happening.
