### ISSUE TITLE
No padding between YouTube video and List block...

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#20414]
**Describe the bug**
There is no padding between a YouTube video block and a List block.

**To reproduce**
- Insert a List block.
- Insert a YouTube video.
- Left-justify (wrap) the YouTube video.
- Note there is no padding between the List numbers/bullets.

This same result is seen with or without Gutenberg activated.

**Expected behavior**
There should be padding around the YouTube video.

**Screenshots**
![75084379-b6dadb00-54ed-11ea-9bb4-65799d1c051e](https://user-images.githubusercontent.com/30901407/75158478-316d4b80-56e4-11ea-865b-0272fd320ae1.jpg)

**Additional context**
- This was first reported in the Storefront repo at https://github.com/woocommerce/storefront/issues/1271. That issue was closed there because this was found to be an issue in the native Twenty-_________ WordPress themes, and so this should be fixed in Gutenberg.

**Comment by youknowriad** [comment]
Hi there!

Thanks for the issue.

I don't really think this is a bug though. The floated element does add a margin but since the list is using "list-style-position: outside" (the default for lists) it creates the overlap. 

There's no way for a list block to know that it's next to a floated element, so for me this should be closed as "won't fix"

**Comment by GlennMartin1** [comment]
I understand what you're saying; but I think you'd agree it's kinda unsightly, and I don't think Gutenberg should settle for this.

Perhaps it should be reconsidered if Lists should be using a negative margin.

Regardless of how this is addressed, I think it's reasonable and obvious that it should not remain as-is.

**Comment by youknowriad** [comment]
> Perhaps it should be reconsidered if Lists should be using a negative margin.

Whether the List block should be using inside or outside bullets is a theme decision that is applied using editor styles. I understand why themes would prefer outside bullets though. In the most generic usage (no floats on the right), it looks better in text-based content.

Potentially, this could be fixed with a style variation from the theme.

I still think there's nothing to be done in Gutenberg here.
