### ISSUE TITLE
Improve widescreen experience

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#2045]
From: https://wordpress.org/support/topic/dreadful-awful-unusable/

> Responsiveness has been totally ignored. I use a wide screen monitor. The current editor used the full-screen width. The new one uses a very narrow editing column in the centre of the screen and presents me with blank areas to both sides. Of the available screen width that the editing space could fill, Gutenberg uses 30.8% That’s less than a third of what’s available. tinyMCE uses 100%
> 
> Meanwhile the “Insert” link (pretty important when you’re editing) is placed miles away in the top right corner, out of my focal point, beyond my peripheral vision.

Maybe we could consider a max-width on the content area on wide screens. Worth playing around with a couple different ideas to improve this experience.

**Comment by brentjett** [comment]
It also might be worth considering how far away the settings sidebar can be from a block and if a user will notice the settings panel change when selecting a block to work on. If they click the gear icon but don't realize the panel loaded on the right because they are on a very large monitor, that would obviously be a problem. There are quite a few 4k, 5k (on my desk, for example) and ultra-wide displays running around now.

I disagree on the "TinyMCE uses 100%" as a positive thing though. Line length should be managed for readability and any theme that would actually display it's body content the full width of the browser on the frontend was likely not written in the current decade. The editor should maintain a sensible max width for the content area, but 608px might be a little narrow.

**Comment by karmatosed** [comment]
https://github.com/WordPress/gutenberg/issues/1887 has some prior conversation around this. I think it could be good to make sure we get one thread. Hoping it is ok as closing this one and moving conversation there.

**Comment by melchoyce** [comment]
Good catch!
