### ISSUE TITLE
Incorporate "Add New Page" Flow into "Add Template"

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#20473]
The "Add Template" flow should also somehow incorporate the new "Add Page" from the URL popover.

**Comment by MichaelArestad** [comment]
CC @mapk since you were working on these flows.

**Comment by mapk** [comment]
Thinking this through... I imagine a user story that works like this:

_As a user, I just created a new template, tested it out with some existing content, and now I want to create a new page based on this template._ 

The first place I'd imagine seeing an option for this is in the Content dropdown in the top toolbar. I don't think this would exist under the Template dropdown because I'm just using the template to create a new page. But maybe it can? Anyways, here's a go at where I think this would work.

![Screen Shot 2020-04-17 at 11 16 16 AM](https://user-images.githubusercontent.com/617986/79601193-48ee0280-809d-11ea-80fe-ffdf0d820a54.png)

If it does feel better as part of the template menu options, we can include it like so...

![Screen Shot 2020-04-17 at 11 21 24 AM](https://user-images.githubusercontent.com/617986/79601442-a71ae580-809d-11ea-8799-c751b4dd764c.png)

**Comment by karmatosed** [comment]
I wonder if you need to see 'from template' as copy, or just creating a new page makes sense?

For me, there is a presumption of knowing what a template is in this phrase:

> As a user, I just created a new template, tested it out with some existing content, and now I want to create a new page based on this template.

I would say people don't know often and don't even have to know that it's even a template.

**Comment by shaunandrews** [comment]
I'm confused. Is this about adding a new template, or adding a new page?

Adding a new page from the Content dropdown could work, but I'd expect it to then act similar to the Link UI previously mentioned:

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/191598/80012808-e0879280-849b-11ea-88d4-7aaa7051f6ad.png">

But again, I'm not sure if thats the problem this issue aims to resolve.

**Comment by MichaelArestad** [comment]
From what I understand, this is about being able to create a new page at the same time as creating a new template.

**Comment by paaljoachim** [comment]
Is this issue still valid?

**Comment by paaljoachim** [comment]
I am closing this issue for now.
Please reopen if I am mistaken.
@jameskoster and @mapk
