### ISSUE TITLE
Gutenberg Table Block_User not able to change table display design using drop down selecting option

### ISSUE THREAD

**Issue by mohitdadhich10** [WordPress/gutenberg#20497]
Table Block drop down option change or select Table style layout is not working.

Steps :
1) Select Table block.
2) Select style option.
3) Change style using option available in Default Style drop down .
4) Table style will not get change. 

![image](https://user-images.githubusercontent.com/50702885/75436872-431c5080-597b-11ea-9c0e-197826c7cb23.png)
)

**Comment by jorgefilipecosta** [comment]
Hi @mohitdadhich10 thank you for reporting this issue.


The Default Style dropdown does not change the style of the currently selected block. It makes all the other table blocks inserted after have a "Default Style".
In order to change the style of the currently selected block you can click on the preview of the style e.g: the area above "Stripes".
