### ISSUE TITLE
DOMException: "The operation is insecure." react-dom.min.b694e242.js:103:487

### ISSUE THREAD

**Issue by jeremyfelt** [WordPress/gutenberg#20525]
**Describe the bug**
* When I try to edit a draft post, published post, or add a new post, I see only an error: "The editor has encountered an unexpected error."
* If I look at the console, I see: `DOMException: "The operation is insecure." react-dom.min.b694e242.js:103:487`
* If I "Attempt Recovery", I get a blank white screen where the editor should be and no messaging.
* If I disable the Gutenberg (7.6.0) plugin, I can edit the post just fine.

I tried disabling all other plugins and the issue remains.

Here's the results of "Copy Error": https://gist.github.com/jeremyfelt/911e9ac8ac2701efa6aff982b7d96387

**To reproduce**
1. Attempt to edit a post
2. See error

**Expected behavior**
The editor should appear.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser Firefox 73.0.1 (Same in latest Chrome)

**Comment by jeremyfelt** [comment]
I do use a different subdomain for `wp-content/`, though that hasn't caused any trouble in the past with the plugin (that I'm aware of).

**Comment by jorgefilipecosta** [comment]
Hi @jeremyfelt is this error also happening on wp/trunk /WordPress 5.4 without the Gutenberg plugin?

**Comment by aduth** [comment]
I've not seen this sort of error before, but from some initial debugging ([[1]](https://stackoverflow.com/questions/35042340/firefox-securityerror-the-operation-is-insecure) [[2]](https://stackoverflow.com/questions/49539306/firefox-service-worker-securityerror-domexception-the-operation-is-insecure/49547221#49547221)), I see some trend of relationship to browser security settings.

@jeremyfelt Can you clarify if you have any specific, non-default settings related to security settings in your browser (related to cookies, browser storage, etc)?

**Comment by aduth** [comment]
Does it start to work again if you try to download older versions of the Gutenberg plugin?

Substitute version in URL: https://downloads.wordpress.org/plugin/gutenberg.7.6.0.zip

Hypothesis: I notice that you are serving plugin assets from a separate domain, where perhaps default browser security is rejecting operation on basis of [Same-Origin Policy](https://en.wikipedia.org/wiki/Same-origin_policy), or SameSite cookies ([becoming more strict in browsers recently](https://www.jardinesoftware.net/2019/10/28/samesite-by-default-in-2020/)).

**Comment by galloppinggryphon** [comment]
I also experienced the DOMException error in Gutenberg 7.6. For me, the problem was accompanied by this error:

`The resource from “https://example.com/wp/wp-content/themes/theme/css/theme-settings.css?ver=1.0” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).`

I had moved this file and forgot to update the URL (wp_enqueue_style()) in functions.php, making Firefox scream bloody murder. Once I corrected the reference, the error disappeared and the editor loaded normally. 

I use the following rules in .htaccess and disabling them also prevented the error:
```
<IfModule mod_headers.c>
  Header set X-XSS-Protection "1; mode=block"
  Header always append X-Frame-Options SAMEORIGIN
  Header set X-Content-Type-Options nosniff
</IfModule>
```

Hope this can be of help.

Perhaps I can suggest a more helpful error message for this circumstance? Or maybe the set of problems that can trigger the same error is too large. I don't know how React knows that the operation is insecure, but more helpful console feedback from React would be a place to start -- if it knows which file it has problems with, it should tell...

**Comment by mcsf** [comment]
> Perhaps I can suggest a more helpful error message for this circumstance? Or maybe the set of problems that can trigger the same error is too large. I don't know how React knows that the operation is insecure, but more helpful console feedback from React would be a place to start -- if it knows which file it has problems with, it should tell...

The thing is that the error comes directly from the browser. See [DOMException](https://developer.mozilla.org/en-US/docs/Web/API/DOMException).

**Comment by aduth** [comment]
I'm curious where the network request is originating that is triggering the error is coming from, especially considering the timing. There's some history of ["transforming" CSS from stylesheets](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/utils/transform-styles), but I don't believe these files are loaded in the browser ([source](https://github.com/WordPress/wordpress-develop/blob/94516bbb3f66b132466967111556f47df6a49f62/src/wp-admin/edit-form-blocks.php#L188-L207)). Not sure if it might be one of the newer experimental features (block directory, full-site editing, etc).

@galloppinggryphon I would be curious if you might have the ability to test this against [WordPress 5.4.0 RC](https://wordpress.org/news/2020/03/wordpress-5-4-release-candidate/), to see whether the problem is present there as well.

@jeremyfelt Do the circumstances described in https://github.com/WordPress/gutenberg/issues/20525#issuecomment-597218976 ring familiar to your setup? Does the issue occur across themes? Are there any errors in the console like the one shown in that comment?

**Comment by jeremyfelt** [comment]
Thanks @aduth and all for looking at this. I haven't had a chance to really troubleshoot past that initial error. I don't think my situation involved a mime type mismatch. I'm fairly confident it's an issue with the different content domain, as none of my other sites had an issue, so I'll poke at that at some point.

All that said - everything works again after the upgrade to Gutenberg 7.7.0. Which could mean that either something changed in my browser in the last 12 days while I had 7.6.0 deactivated OR that 7.7.0 fixed something.

I'd be okay to close this out as an annoyance, though I'll definitely keep an eye on things to see if I can trigger it again.

**Comment by aduth** [comment]
Let's close this out for now as resolved, and reopen if it surfaces again.
