### ISSUE TITLE
Please, give back the "preview" button!

### ISSUE THREAD

**Issue by locksoft** [WordPress/gutenberg#20564]
I installed the 0.7.6 version of Gutenberg and, while it finally solves the scrolling on mobile devices, it makes so difficult to have a preview. I see a "desktop" voice I've no idea what it does, as I see the normal editor. "Tablet" and "mobile" only give a gray background with an empty textarea in the middle. Open externally works, but it's two clicks every time.

For the moment I'm reverting back to 0.7.4,

**Comment by NewJenk** [comment]
The standalone preview button that opens a preview in a new tab (current WP behaviour) definitely needs to come back. Or, a filter needs to be added to allow sites to easily revert to the status quo.

Although I can see what is trying to be accomplished with the dropdown, there are an infinite amount of reasons why the edit screen may not replicate the front-end, and in these cases the preview button works just fine.

**Comment by mapk** [comment]
So it appears that this issue isn't about a missing Preview button, because it's definitely still there. It's just that it requires two clicks when trying to quickly preview your post. I get that. Thank you for raising this.

What we're trying to improve is the ability for people to preview how their content will look in various screen sizes. This is a new feature in WordPress, so will likely take some getting used to.

I'm going to close this issue for now in support of the new screen size preview ability.
