### ISSUE TITLE
Block API: Explore how block variations could be embedded in other places

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#20584]
## Description

Follow-up for #16283.

Some ideas were previously shared by @kjellr in https://github.com/WordPress/gutenberg/issues/16283#issuecomment-508132004:

> In many cases, it'll make sense to include these options in the setup state. Beyond that, they'll likely also need to live in either the Block Switcher menu, or in the Sidebar: 
> 
> _Layout Options in the Sidebar:_ 
> <img width="958" alt="03" src="https://user-images.githubusercontent.com/1202812/60599264-2a23b700-9d7c-11e9-858a-f5482b799d37.png">
> 
> _Layout Options in the Block Switcher:_ 
> <img width="958" alt="Frame 2 1" src="https://user-images.githubusercontent.com/1202812/60599265-2a23b700-9d7c-11e9-8b07-18f8cd4655c0.png">

**Comment by ocean90** [comment]
It would be nice to have at least one of the options since it doesn't seem to be possible to use `transforms` to switch to another variation due to the same block name.

**Comment by paaljoachim** [comment]
It seems this issue is very much associated:
https://github.com/WordPress/gutenberg/issues/20583

---

It seems like we need a new Layout Panel.


Levels:
Select a Block through the inserter panel or the '/'
The Block has different layouts. Think columns has the initial startup select a layout approach. The same layouts should always be available in a Layouts panel in the sidebar for various Blocks.
A block has Styles. It would be good to create a clear differentiation of layout options and style options. 

A figma example with the Columns Block:
![Variation panel](https://user-images.githubusercontent.com/5323259/84371237-9ee0b180-abd9-11ea-9ada-529ff3f205d6.jpg)

![2 Sidebar - Open Layout panel](https://user-images.githubusercontent.com/5323259/84371352-cd5e8c80-abd9-11ea-8496-f9be855ccd90.jpg)

Mini prototype.
https://www.figma.com/proto/HcOy92XlgMNtUjH5KF2Os0/New-Sidebar-Layout-Panel?node-id=2%3A0&scaling=min-zoom

**Comment by ntsekouras** [comment]
This shouldn't be coupled with `styles and layout` in mind because there are blocks that just change attributes and nothing else visually, like the `embed` block.

Related issue: https://github.com/WordPress/gutenberg/issues/25231

**Comment by gziolo** [comment]
I think we can close it in favor of #25231 that is covering exactly the same topic.
