### ISSUE TITLE
Design of 'Set featured image' button now strays from core

### ISSUE THREAD

**Issue by garretthyder** [WordPress/gutenberg#20616]
**Describe the bug**
In WP 5.4RC1 I found the 'Set featured image' button to be a larger rectangle than in 5.3.2 which strays away from the design of other similar buttons in core such as the Background Image or Select Site Icon buttons.

**To reproduce**
1. Install WP 5.4RC1
2. Create a Post/Page
3. Expand the Featured Image accordion
4. See the larger 'Set featured image' button

**Expected behavior**
The button shouldn't have changed as it was previously matching the core design for such buttons.

**Screenshots**
![Screen Shot 2020-03-03 at 2 13 39 PM](https://user-images.githubusercontent.com/8726005/75827763-3a52c280-5d5f-11ea-893a-27f46e434a9a.png)
*New Size

![Screen Shot 2020-03-03 at 2 50 56 PM](https://user-images.githubusercontent.com/8726005/75827785-42126700-5d5f-11ea-804b-4b6a02fb96cd.png)
*Original Size

![Screen Shot 2020-03-03 at 2 57 35 PM](https://user-images.githubusercontent.com/8726005/75827833-57879100-5d5f-11ea-9548-de2f52f84620.png)
*Other WP Core button

**Desktop (please complete the following information):**
 - Device:  MacOS 10.15.3
 - Browser: Chrome Version 80.0.3987.122
 - Version: 5.4RC1

**Comment by jorgefilipecosta** [comment]
Hi @mapk, is the new bigger design of the button something expected or we should consider this size a bug (and fix it before 5.4 is released)?

**Comment by mapk** [comment]
I believe this may be a bug. Dropping it back down to the smaller size sounds right.

I currently see:

![Screen Shot 2020-04-13 at 7 31 26 PM](https://user-images.githubusercontent.com/617986/79179851-62512f00-7dbd-11ea-83d2-68fd2a5d58cd.png)

**Comment by johnwatkins0** [comment]
Hi, @mapk. It looks like this button was given a 90px min height as part of #17486 to accommodate drag and drop for the featured image panel. While the user is dragging a file, the panel gets this overlay that is ~90px high:

<img width="298" alt="Screen Shot 2020-05-03 at 3 49 57 PM" src="https://user-images.githubusercontent.com/9020968/80925533-1ce9a700-8d56-11ea-9d5d-1d628adcc595.png">

### Options

1. Don't change anything; keep it as is with the tall button.
2. Make the button smaller with whitespace above and/or below, maybe like this: 

<img width="308" alt="Screen Shot 2020-05-03 at 3 33 45 PM" src="https://user-images.githubusercontent.com/9020968/80925545-3db1fc80-8d56-11ea-92d0-fbaeb2a44767.png">

The drag and drop UI state will fill the whitespace; see my first screenshot just above.

3. Make the button smaller without the whitespace, and expand the panel while the user is dragging and dropping. (I feel this is a bad option because having UI shifting mid-drag doesn't seem like a good idea.)
4. Adjust the style of the dropzone component. This is probably not a could option because the component is used in so many places. We could apply custom styles only for the featured image panel, though.

Let me know what you think. Self-assigning this issue because I have a branch in progress.

**Comment by mapk** [comment]
@johnwatkins0 I'd like both the button and the draggable area to match in size. If the reason it was made larger was for a larger draggable area (good investigation there BTW) than I'm fine leaving it at the larger size. 

I'm really not sure where else in Core this sort of button exists. The block editor is core now, so it seems to have replaced itself?

**Comment by garretthyder** [comment]
Agreed, thank you for the sleuthing @johnwatkins0, I'm also casual to close if the change was to improve the ability to get a file into the draggable area. And if that becomes a core standard we can look into other places within core where the image select button exists and update it to support drag-drop-upload. For example the Image Widget and the Customizer Background Image.

**Comment by johnwatkins0** [comment]
👍 Sounds good. Unassigning myself as it sounds like nothing needs to be done for now.

**Comment by garretthyder** [comment]
Let's close this out then, @mapk feel free to reopen if there's anything further to pursue. I'll take a look at instances in core and see if it makes sense to make them support the drag-drop stuff.
