### ISSUE TITLE
Gutenberg 7.6 does not load on MS Edge 44

### ISSUE THREAD

**Issue by mmtr** [WordPress/gutenberg#20652]
**Describe the bug**
Accessing the block editor when using Gutenberg 7.6 on MS Edge 18 results in a blocking error that prevents users from editing or creating post and pages.

<img width="740" alt="Screen Shot 2020-03-05 at 12 12 47" src="https://user-images.githubusercontent.com/1233880/75978513-f5ee3080-5ede-11ea-9c99-96f3ea8e5c88.png">

The issue seems to be specific to Gutenberg 7.6 and MS Edge 18, since it is not present when using either MS Edge 80 or Gutenberg 7.5

**To reproduce**
1. On MS Edge 18, go to wordpress.org/gutenberg
1. See error.

Alternative steps:
1. Install and activate Gutenberg 7.6.
1. On MS Edge 18, start a new post.
1. See error.

**Expected behavior**
The editor should load successfully. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: MS Edge
 - Version: 18

**Comment by Soean** [comment]
MS Edge 18 is very old and we don't support this browser anymore, or do you mean 81?

**Comment by gwwar** [comment]
From what I've read in https://make.wordpress.org/core/handbook/best-practices/browser-support/ Edge 18 still has more than 1% usage. So theoretically we should be supporting this one.

**Comment by aduth** [comment]
I can reproduce an issue on WordPress.org/gutenberg , but not when running the plugin directly.

Or at least, I assume that this is running Edge 18.x :

![image](https://user-images.githubusercontent.com/1779930/76015866-db6d8480-5ee9-11ea-905a-62fa14cf5726.png)

**Comment by aduth** [comment]
I'm not sure why I wasn't able to reproduce earlier, but I can do so now.

Debugging was quite difficult, but after some process of elimination, I think it is caused by this rule:

https://github.com/WordPress/gutenberg/blob/8a94254b6adac030f5a6ffd8e718972e1f19f48e/packages/block-library/src/gallery/style.scss#L108-L113

Commenting this line is enough to make the difference in whether the editor loads or not in Edge 18.x.

What's confusing to me, however, is that this style has existed for quite some time, originally introduced in #13326, then most recently updated in #19344. These recent updates haven't yet been published in any plugin release, so I wouldn't expect that to be the source of any regression.

@jasmussen As author of #13326, I'm not sure if this might ring any bells with you? Could we imagine some alternative solution to the original issue which doesn't require this specific formulation of `@supports` in the stylesheet?

It's still confusing me to me that this would only recently have become an issue. 🤔

**Comment by aduth** [comment]
In some further testing, it does not appear to crash when using WordPress trunk (5.5-alpha-47431), which I would expect to be the equivalent of WordPress 5.4-RC1, and thus not affecting the upcoming WordPress 5.4 release. It would be good if someone else could confirm this.

**Comment by gwwar** [comment]
@aduth is there a download link for the 5.4 RC1? I was having trouble finding it.

**Comment by gwwar** [comment]
@aduth I think 5.4-RC1 should be okay with Edge 18

<img width="1184" alt="Screen Shot 2020-03-05 at 4 24 23 PM" src="https://user-images.githubusercontent.com/1270189/76038347-3c9f5300-5efe-11ea-932b-438b4da48f65.png">
<img width="1190" alt="Screen Shot 2020-03-05 at 4 27 22 PM" src="https://user-images.githubusercontent.com/1270189/76038385-550f6d80-5efe-11ea-91fc-f6629c81a310.png">

**Comment by talldan** [comment]
It looks like the browser version is v44 (but EdgeHTML v18) in those screenshots, so I've changed the title to match.

**Comment by jasmussen** [comment]
> @jasmussen As author of #13326, I'm not sure if this might ring any bells with you? Could we imagine some alternative solution to the original issue which doesn't require this specific formulation of @supports in the stylesheet?

😩 

Oh, the IE tax. 

Given that Microsoft has released a Chromium based edge, and is not only actively rolling pushing it out to Windows machines running classic Edge, but _replacing_ the classic Edge too (updating the shortcuts to point the the new edge and disabling the classic Edge), I would say that the immediate next step is to remove any Edge related CSS code, especially if it's causing these issues. 

The original gallery margin issue that it fixed is not only Classic-Edge specific, but it's not fundamentally a breaking issue, and given classic Edge is actively being deprecated, it seems time to relieve ourself of that hack.

**Comment by aduth** [comment]
The changes proposed at #20690 appear to resolve the crash, removing the Edge-specific styles while still retaining the original fix intended with #13326.
