### ISSUE TITLE
Excerpt in a latest-posts-block vs. blog page

### ISSUE THREAD

**Issue by mmwb** [WordPress/gutenberg#20702]
Get the impression that an **excerpt** in a latest-posts-block is different from an **excerpt** of a post on a blog page. I'm asking because shortcode tags (both begin and end tag) are removed/stripped from an excerpt of a post as used on a blog page, even including the text in between! 

Make a post and add within the first 55 words an internal link, italic text, bold text and a shortcode with a begin and end tag.

Editor:
<img width="761" alt="Schermafbeelding 2020-03-07 om 21 13 55" src="https://user-images.githubusercontent.com/46068706/76151749-a1061200-60b8-11ea-9bf5-5551422149c3.png">

Excerpt of this post on blog page in frontend looks like this:
<img width="685" alt="ScrPrt excerpt twentytwenty 2020-03-06" src="https://user-images.githubusercontent.com/46068706/76151703-fd1c6680-60b7-11ea-8b3f-996cde7321b6.png">
Link and styles are gone - as expected . The shortcodes are removed, but also the content in between (not the desired outcome).

In a latest-posts-block the excerpt looks different. More like the full content:

<img width="636" alt="ScrPrt Full Text twentytwenty 2020-03-06" src="https://user-images.githubusercontent.com/46068706/76151715-276e2400-60b8-11ea-86de-758f6af5f93b.png">

where only style attributes are stripped, but not html and shortcode tags.

The shortcodes in this example are created by 2 wiki lookup plugins. 

Is stripping of the tags ( [wiki] & [/wiki] ) including the content in between caused by the plugin or by WP/Gutenberg to your knowing?
Thanks in advance for your advise.

Using WP 5.3.2 on PHP 7.4.3. on shared hosting with LiteSpeed WebServer
MacOS 10.15.3 with Safari 13.0.5 & Firefox 73.0.1 & Chrome 76.0.3809.100 as client

**Comment by jorgefilipecosta** [comment]
Hi @mmwb thank you for reporting this issue.

@draganescu wasn't this issue fixed with the merge of https://github.com/WordPress/gutenberg/pull/20432? The block is just using what the rest API provides right?

**Comment by skorasaurus** [comment]
The stripping of html links and text formatting within excerpts is expected behavior in WordPress. 

When I make a post, 
Make a post and add within the first 55 words an internal link, italic text, bold text, as you stated, the 


The latest-posts block uses [get_the_excerpt](https://github.com/WordPress/WordPress/blob/cc17fee0895374cfb0d1857e4e686dc69fc1f2f7/wp-includes/blocks/latest-posts.php#L108). 
get_the_excerpt will first check if there's a manually created excerpt (in $post->post_excerpt). 

Then, [wp_trim_excerpt](https://github.com/WordPress/WordPress/blob/dacd7a55ea918c54f71d9691a29023b48c4ae779/wp-includes/default-filters.php#L185) is called, and [strips out the shortcodes](https://core.trac.wordpress.org/browser/tags/5.3/src/wp-includes/formatting.php#L3781). 

More explanation is available at [the_excerpt](https://developer.wordpress.org/reference/functions/the_excerpt/#more-information) page. 
This behavior is pretty standard for WordPress themes as far as I know.

**Comment by mmwb** [comment]
Do you notice the differences in the (same) excerpts above?

**Comment by mmwb** [comment]
Happens in themes like TwentyTwenty, Blocksy, Asta and WeaverXtreme

**Comment by mmwb** [comment]
Aha, as far as I can see now this happens with WP 5.3. But not if Gutenberg 7.7.1 is used.

In that case my issue is scaled back to the question why enclosing HTML-tags get stripped in a  different way than enclosing shortcode tags.

**Comment by jorgefilipecosta** [comment]
I think with the changes applied by @draganescu the problems with excerpts in the latests posts block should be fixed on WordPress 5.4. If there is still a problem in the lastest RC feel free to leave a comment so we can debug the issue further.

Thank you for reporting and sharing insights @mmwb, @skorasaurus.
