### ISSUE TITLE
Full / wide alignment for visually fully aligned block which content is still width-constrained

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#20708]
For many themes I encountered a common pattern for page sections:
The section itself extends to the full page width, but the content is still constrained to the usual max-width of the other content.
In Gutenberg, `full` aligned blocks extend to the full width of the page, but its content is also not constrained.
One way to still implement this in Gutenberg but keep the option to fully extend a group using `full` alignment would be to use the `wide` alignment.
`wide` aligned groups would have to extend to full width as `full` does, but still constraint their inner content wrapper.
Is this the right approach for Gutenberg? I would have to copy some styles for `full` alignment and apply them to `wide` alignment, too, the editor has to be "tamed" a bit.

**Comment by tellthemachines** [comment]
Hi there! As of #29335, it is now possible for a theme to provide settings to constrain the width of all blocks inside a group block. In order to do so, you have to add a `theme.json` file to your theme, and you can find info on how to configure it [here](https://make.wordpress.org/core/2021/06/29/on-layout-and-content-width-in-wordpress-5-8/).
