### ISSUE TITLE
Ability to get (and set) site options from wp_options table using useSelect()

### ISSUE THREAD

**Issue by philbuchanan** [WordPress/gutenberg#20731]
**Is your feature request related to a problem? Please describe.**
Specifically, I'm looking to add a feature to my Gutenberg block that allows a user to set and restore options for the block type globally (i.e. across multiple posts). A user can make some changes to the default block settings (attributes) then save and have them applied automatically the next time they insert a new block of that type. My initial thinking was to save the defaults into the `wp_options` table. 

This is, of course, just one example of why I'd like to be able to access global site settings within my block. Generally I'm looking for a way to retrieve site options within a Gutenberg block of plugin.

**Describe the solution you'd like**
Ideally I can use `useSelect()`:

```js
const myOption = useSelect( (select) => {
    return select( 'core' ).getOption( 'my_option_name' )
} );
```

Or another hook similar to the [proposed method for retrieving post meta](https://make.wordpress.org/core/2020/03/02/general-block-editor-api-updates/):

```js
const [meta, setMeta] = useEntityProp('postType', 'post', 'meta')
```

Perhaps there is already a solution to this, and I just can't find how to do it in the documentation.

**Describe alternatives you've considered**
My current solution is to add a custom API endpoint for my plugin and to use `wp.apiFetch` to get and set the option. This adds a lot of overhead to the block code and requires me to manually manage the state of the defaults and current settings.

**Comment by mtias** [comment]
See how it's used in the site title block: https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/site-title/edit/index.js#L17

And how it's declared in entities: https://github.com/WordPress/gutenberg/blob/master/packages/core-data/src/entities.js#L20-L25

**Comment by philbuchanan** [comment]
@mtias Is there some documentation around how to declare my own entities?

**Comment by Mamaduka** [comment]
@mtias this feature will be available for WP 5.4 or higher, right?

**Comment by Mamaduka** [comment]
I was playing around with `useEntityProp` and settings entity. Unfortunately, changes aren't persisted in the database.

Tested with WP 5.4-RC2 and Gutenberg 7.7.0.

Imaginary map block:
```js
/**
 * WordPress dependencies
 */
import { useEntityProp } from '@wordpress/core-data';
import { useState } from '@wordpress/element';
import { Button, Placeholder, TextControl } from '@wordpress/components';

export default function QuestMapEdit() {
    const [ value, onChange ] = useState( '' );
    const [ apiKey, setApiKey ] = useEntityProp( 'root', 'site', 'quest_map_api_key' );

    return (
        <>
            { apiKey ? (
                <p>Your API Key: { apiKey }</p>
            ) : (
                <Placeholder instructions="Quest Map API">
                    <TextControl
                        value={ value }
                        className="components-placeholder__input"
                        placeholder="Enter Quest Map API Key..."
                        onChange={ onChange }
                    />
                    <Button
                        isPrimary
                        onClick={ () => setApiKey( value ) }
                    >
                        { 'Save Key' }
                    </Button>
                </Placeholder>
            ) }
        </>
    );
}
```

```php
/**
 * Register API Key settings.
 *
 * @return void
 */
function register_settings() {
	register_setting(
		'quest_map',
		'quest_map_api_key',
		[
			'type'              => 'string',
			'show_in_rest'      => true,
			'sanitize_callback' => 'sanitize_text_field',
		]
	);
}
add_action( 'rest_api_init', __NAMESPACE__ . '\\register_settings' );
add_action( 'admin_init', __NAMESPACE__ . '\\register_settings' );
```

**Comment by mcsf** [comment]
> I was playing around with `useEntityProp` and settings entity. Unfortunately, changes aren't persisted in the database.

Hi, @Mamaduka. Indeed, any changes to entities need to be explicitly saved, just how you would expect to save content blocks after changing their attributes.

Right now, you can do this explicitly using the [saveEditedEntityRecord](https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/data/data-core.md#saveEditedEntityRecord) action. Using Matías's [example with site title](https://github.com/WordPress/gutenberg/issues/20731#issuecomment-596585647), you would call:

```js
wp.data.dispatch('core').saveEditedEntityRecord( 'root', 'site' );
```

In the future, in order to accommodate full-site editing, the block editor will provide better tools to let users know which entities in the editor have unsaved changes (e.g. the post itself, the site entity that bears the site title setting, the templates parts such as the header).

Some of this is already usable if you enable the full-site editing experiment in the Gutenberg settings and then open the experimental editor at **Gutenberg > Site Editor (beta)**. Here, the logic around saving is taking into account the multitude of possible entities being edited; check out the source for [`SaveButton`](https://github.com/WordPress/gutenberg/blob/ae44d9099d895dcf1078e255ece4fcb0301646bb/packages/edit-site/src/components/save-button/index.js#L41-L51) and [`EntitiesSavedStates`](https://github.com/WordPress/gutenberg/blob/ae44d9099d895dcf1078e255ece4fcb0301646bb/packages/editor/src/components/entities-saved-states/index.js#L70-L85).

As an illustration, notice how the special Save Design button in the Site Editor is aware that I made edits to the Site entity when I set the setting `foo` (that I registered for the sake of the experiment):

![save-entities-button](https://user-images.githubusercontent.com/150562/76646978-d21c9180-6553-11ea-82fd-940d0cfb4301.gif)

**Comment by ndiego** [comment]
Hi @mtias is there a trick to using `useEntityProp` outside of the editor? Retrieving settings in the editor (i.e. in a block) works like a charm. However, I have built a custom settings page that leverages the editor components. Using `useEntityProp` returns undefined when it was working perfectly in the editor. After going through the docs, it looks like it must be a context issue, but it sort of looks like `useEntityProp` sets its own context. Any guidance would be greatly appreciated!!

**Comment by mcsf** [comment]
You probably need to set up the context with `BlockEditorProvider` ([source](https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/provider/README.md)).

This can be used in tandem with `useEntityBlockEditor` (see [example](https://github.com/WordPress/gutenberg/blob/9699f4f013e19fe8b96661eaf6344f2f8037f383/packages/edit-site/src/components/block-editor/index.js#L50)), depending on your use case.

**Comment by talldan** [comment]
It looks like all the questions have been answered for this issue, so I'll close it. Feel free to keep the conversation going.

**Comment by ndiego** [comment]
I just discovered an issue where the following example returns a rest error "rest_forbidden" if the user is not an Admin. Does anyone know a way around this? I am using a custom option to control some functionality in my blocks, and I need to retrieve this setting at all user levels.

`const [ demoSetting, setDemoSetting ] = useEntityProp( 'root', 'site', 'demo_setting' );`

**Comment by evrpress** [comment]
@ndiego do you have a solution for this? You must have the `manage_options` capability to use the `/settings` endpoint.

I currently use `wp_add_inline_script` to add a global variable with the settings.

**Comment by ndiego** [comment]
@evrpress yeah I am using `wp_add_inline_script` as well. Not ideal, but it works 🤷‍♂️

**Comment by mediaformat** [comment]
I'm working with `saveEditedEntityRecord`, but unless a schema is defined in `register_setting()` it results in a 400 Bad request. I'm working with dynamic data, so would like to find a way around this, or another method of setting wp_options.
