### ISSUE TITLE
Social Icon Block Colours

### ISSUE THREAD

**Issue by icc365** [WordPress/gutenberg#20751]
**Describe the bug**
Incorrect colours for the block social icon backgrounds as they relate to each social platform. I'm currently testing WordPress 5.4 RC1.

**Expected behavior**
Recommend either using a single colour, otherwise if the idea is to match the colours to the social networks, best to use their actual colours.

**Example**
Facebook colour in the block uses this HEX colour: `#1977f2` 
The official colour for Facebook is: `#3b5998`

**Additional context**
- Using and testing the WordPress 5.4 RC1 version.

**Comment by jasmussen** [comment]
The colors for the facebook logo are taken from this document: https://en.facebookbrand.com/facebookapp/

Although the document mentions the term "app", it does show clear usage guidelines for how to use the brand colors, which appear to be correctly used by the block, if those guidelines are indeed the right ones.

I'm happy to submit a pull request to update the colors, but we have to find an official Facebook resource that suggests the color we're using is wrong first, otherwise we are not actually following official guidelines.

**Comment by icc365** [comment]
Thanks for the follow-up. Actually, it's many of the icon backgrounds that don't match the official colours, not just facebook. Although, I see facebook has changed their branding. From what I can tell, their blue is now `#1778F2`

The best thing to do if the colours are to get updated is to go to the official social sites and get their branded colour values. This might help too: https://www.lockedownseo.com/social-media-colors/

**Comment by jasmussen** [comment]
I could swear I did exactly that! But I'll take another look 👍👍
