### ISSUE TITLE
(Firefox) "Open Document Settings" region visible after closing sidebar

### ISSUE THREAD

**Issue by mcsf** [WordPress/gutenberg#20759]
## Steps to reproduce

1. Open the sidebar with either Document or Block settings selected.
1. Close it using the X sign to the right from the _Document_ and _Block_ tabs.
**Observed:** the little _Open document settings_ region is visible.

Note that the same doesn’t happen when closing the sidebar by clicking on the cog icon

## Screencast

<img src="https://user-images.githubusercontent.com/150562/76307383-a33abd00-62c0-11ea-936b-d999d460fe87.gif" alt="firefox-toggle-sidebar" width="400">

## Environment

Firefox 74 (stable), macOS Catalina.

**Comment by jorgefilipecosta** [comment]
This problem is happening on WordPress 5.4 and was not happening on WordPress 5.3.

**Comment by aduth** [comment]
Initial debugging:

- Only happens in Firefox in macOS, not Windows
- Most definitely in some way related to [this behavior quirk of button clicking and focus](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Clicking_and_focus)
- At the point that "X" is clicked, focus remains in the sidebar, which is why the "Open Document Settings" is still shown ([source](https://github.com/WordPress/gutenberg/blob/d4f159a3da0738aa045e9969dba2c6c13a7f6a8d/packages/edit-post/src/components/layout/style.scss#L85-L91))
- Yes, you heard right. Focus remains in the sidebar, despite the sidebar not being visible. The element still exists. I guess this is intentional ([source](https://github.com/WordPress/gutenberg/blob/d4f159a3da0738aa045e9969dba2c6c13a7f6a8d/packages/edit-post/src/components/layout/index.js#L129))? 
- Normally we rely on [this logic](https://github.com/WordPress/gutenberg/blob/d4f159a3da0738aa045e9969dba2c6c13a7f6a8d/packages/edit-post/src/components/sidebar/index.js#L33-L41) to forcibly move focus to the "Settings" button in the heading toolbar after clicking "X"

As a result, I sense it's something about the button not emitting events we're expecting, or at least in a way that `withFocusReturn` is not able to pick up on. In previous versions, I expect that the sidebar was not being rendered if closed, so focus would be "lost" by virtue of the fact that the element was removed from the DOM. Based on timing, I'd imagine this might be related to refactoring in #18044 (cc @youknowriad).
