### ISSUE TITLE
Add a way to control letter spacing

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#20796]
I've been having fun with making themes and block patterns lately, but I'd like to have finer control over letter-spacing to express visual varieties and to achieve opinionated styling around type.

It'd be great to allow increasing/decreasing letter spacing.

**Example of decreasing:**
![Pattern 35](https://user-images.githubusercontent.com/908665/76437665-cabd8280-63b1-11ea-8db2-69b1a550cd2b.png)

**Example of increasing:**
![Pattern 16](https://user-images.githubusercontent.com/908665/76437710-de68e900-63b1-11ea-9e1d-c855d52452e5.png)

**Comment by aristath** [comment]
Personal opinion:
Letter-spacing, word-spacing and line-height are things that don't concern the majority of people. You'd never use it when writing a post, you'd never use it when creating a normal page. You'd use these options only when creating a one-off page with specific styling for a very specific purpose.

The "Choices, not Options" philosophy is in place so that we always keep in mind that we should not over-complicate things.
Having a couple dozen of options is cool because we can do whatever we want, but at the same time it also slows down the daily stuff like writing a blog post by introducing visual (and code) noise to the mix.

**Comment by alaczek** [comment]
I agree it will be tricky to nail the balance and not over-complicate the simple tasks like writing a post with design options that might be used once, if at all. On the other hand letter spacing is a  pretty basic tool from design point of view, and it enables designers to create nicer layouts and patterns, that will benefit users. 

I guess what I'm suggesting considering where letter spacing setting would make the biggest impact, and implement it there. For example, I think this would come in really handy in FSE, in header/footer design for things like site title and navigation blocks.

**Comment by ianstewart** [comment]
> Letter-spacing, word-spacing and line-height are things that don't concern the majority of people. You'd never use it when writing a post, you'd never use it when creating a normal page. You'd use these options only when creating a one-off page with specific styling for a very specific purpose.

Pattern creation and Template/Template-Part editing in the Site Editor — and even block-based theme creation in the Site Editor? — are both those sort of one-off tasks where this support could be valuable. I agree that most people would likely never use this from a creation standpoint. But when selecting from and then editing future block patterns or template-things this could be welcome.

**Comment by ntsekouras** [comment]
Closing this one as it seems to have been resolved by https://github.com/WordPress/gutenberg/pull/31118.
