### ISSUE TITLE
Add quick uppercase option

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#20801]
It'd be great if there is an uppercase option for text so the user can change text to uppercase quickly without actually typing it in uppercase.

![Pattern 38](https://user-images.githubusercontent.com/908665/76449496-18db8180-63c4-11ea-9af9-96f7b2a284f4.png)

**Comment by aduth** [comment]
Do you imagine this would be an option to control the _styling_ of the text (i.e. [`text-transform`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform)), or transforming _the content itself_? Not sure if the latter might have any impact on zero or more of: Ability to copy text meaningfully, ability to translate, accessibility, HTML semantics (SEO, etc).

**Comment by aduth** [comment]
> Not sure if [transforming the content] might have any impact on zero or more of: Ability to copy text meaningfully, ability to translate, accessibility, HTML semantics (SEO, etc).

By coincidence, I just stumbled upon this related conversation:

https://core.trac.wordpress.org/ticket/48412

From @afercia :

>I'd like to propose to remove all of them: all caps should be avoided for better readability and because screen readers may pronounce all caps words as abbreviations.

**Comment by iamtakashi** [comment]
> Do you imagine this would be an option to control the styling of the text (i.e. text-transform), or transforming the content itself?

I imagined an option that controls the styling of the text.

**Comment by phpbits** [comment]
@iamtakashi You could use [EditorsKit](https://wordpress.org/plugins/block-options/) plugin which adds Uppercase Text Transforms and other formats. I hope this could help. Thanks!

**Comment by iamtakashi** [comment]
@phpbits Thanks! 

I've also seen this option in other plugins too. That suggests it's a popular feature, and it's worth considering adding it to Gutenberg as well.

**Comment by afercia** [comment]
A while ago there was an interesting conversation on Slack #accessibility about uppercase text and its impact on assistive technologies: https://wordpress.slack.com/archives/C02RP4X03/p1573228360336200 (requires registration)

Real case from another project:

"ADD SITE" (styled with text-transform)
was being read out as "ei dee dee site" 🙂 

Apart from accessibility concerns, uppercase text does have a meaning, whether it's "more important"., "shouting", or anything else. Meaning should be separate from presentation and not rely on CSS. It might also have impact on SEO, as some text styled as uppercase is perceived as lowercase by search engines.

Users already have the ability to type uppercase text, if they want to do so.

Worth also considering that copy/paste operations appear to behave differently across browsers. For example, copying and pasting some lowercase text transformed with `text-transform: uppercase`:
- Chrome: the pasted text is uppercase
- Firefox: the pasted text is lowercase

**Comment by mtias** [comment]
Also somewhat related: https://github.com/WordPress/gutenberg/issues/20442

**Comment by mtias** [comment]
This is good context. I think it's super important as we expand the customization tools to ensure the outcome is the most semantic representation possible — and that we keep improving upon it. Is it clear if the limitations of `text-transform` are structural or implementation details of how browsers are interpreting it?

**Comment by karmatosed** [comment]
I can see both sides here regarding adding uppercase. I can see how it's a nice option for people, I can also see how it makes longer text, over one sentence harder to read. In this case, I would probably advise a few options:

- Limit to headings and cover blocks.
- Add a warning similar to contrast if we do add to all text blocks.

**Comment by lancewillett** [comment]
On WordPress.com sites we employ a tool in the formatting bar to quickly change text to uppercase:

<img width="689" alt="Screen Shot 2020-04-04 at 12 39 52" src="https://user-images.githubusercontent.com/66797/78460183-8604ce80-7673-11ea-8092-a18dc05d7df4.png">

<img width="749" alt="Screen Shot 2020-04-04 at 12 39 43" src="https://user-images.githubusercontent.com/66797/78460182-84d3a180-7673-11ea-831d-a3995371fca3.png">

I'm not 100% sure, but I believe it loads from the CoBlocks plugin.

**Comment by afercia** [comment]
Seems .com uses CSS though: `<span class="uppercase">text</span>`

which bring us to the previous point: 
> uppercase text does have a meaning, whether it's "more important"., "shouting", or anything else. Meaning should be separate from presentation and not rely on CSS. It might also have impact on SEO ...

**Comment by richtabor** [comment]
> I'm not 100% sure, but I believe it loads from the CoBlocks plugin.

Yup, it is.

**Comment by ianstewart** [comment]
> Is it clear if the limitations of text-transform are structural or implementation details of how browsers are interpreting it?
— mtias

> Real case from another project:
> "ADD SITE" (styled with text-transform)
> was being read out as "ei dee dee site" 🙂
— afercia

For follow-up, I'm curious if there are ways to avoid that. Does that always happen with every reader, in every case of text-transform? Are there cases where it doesn't? (I'm curious about the mechanics of that.)

> It might also have impact on SEO, as some text styled as uppercase might be perceived as lowercase by search engines.
— aferica

I am definitely not an SEO expert. It would be get a teensy bit of research here. My quick looking around suggests that it is not a concern.

Fwiw, I can think of a somewhat SEO-related case where using text-transform would be preferable for this block. My site-title block.

It seems relatively common to have a site-title styled in all uppercase in some sort of header treatment. That text is special since it's drawn from the database. If I wanted to re-purpose that text again in the footer of my site but lowercase — would I have to not use a site-title block in order to have it styled differently there if it wasn't using CSS?

I can see this being important for themes.

But the SEO thing: If I wanted my site-title to appear in uppercase and couldn't use styles that could potentially affect how it appears in search results since it's also re-purposed in the title element? Without text-transform styles users could be creating titles like "IAN'S BLOG" for visual reasons and wondering why people searching for it always saw, relatively un-professional or hokey in this context, uppercase in search results.

That's partly why I wondered if there were any technical ways to resolve the display issue to also address a11y needs, especially, for screen readers.

**Comment by iamtakashi** [comment]
It's not uncommon to display post titles and meta (category, date, etc.) in all uppercase too. It'd be a real pain if the users need to type all uppercase all the time.

![Screenshot 2020-09-21 at 11 29 22](https://user-images.githubusercontent.com/908665/93757292-64d27300-fbfe-11ea-9ce4-c8657a849de6.jpg)

**Comment by paaljoachim** [comment]
I believe that @ItsJonQ Jon is working on improving the typography controls used in the sidebar for various blocks that have a focus on text. Transform I believe might be one of the controls.

**Comment by ianstewart** [comment]
Related issue https://github.com/WordPress/gutenberg/issues/28106

**Comment by skorasaurus** [comment]
related https://github.com/WordPress/gutenberg/issues/22163

**Comment by ramonjd** [comment]
👋 Since https://github.com/WordPress/gutenberg/pull/34064 most core text blocks have support for text transforms:

![Nov-09-2021 11-44-52](https://user-images.githubusercontent.com/6458278/140841146-211d7618-bfef-494e-a260-56d783889946.gif)

Post Title styles can also be targeted in the Site Editor since https://github.com/WordPress/gutenberg/pull/31623

<img width="289" alt="Screen Shot 2021-11-09 at 11 56 02 am" src="https://user-images.githubusercontent.com/6458278/140842030-dbdbafb3-b257-46b8-8c52-3584cc3acd27.png">

What do folks think? Are these merged typography supports PRs sufficient to close this issue?

**Comment by ramonjd** [comment]
Closing this issue as I think the tools required to achieve the desired effects are there. Feel free to reopen if this isn't the case. Thank you!

**Comment by dashkevych** [comment]
I've tested this feature using **WordPress 5.9-alpha-5219**2, and it looks like the options adds `style="text-transform:uppercase"` to the element to change text to uppercase.

Is it possible to use CSS class instead of inline styling for the letter case?

Maybe something similar that we have right now for the **text alignment**: `has-text-align-left`, `has-text-align-center`, `has-text-align-right`

**Comment by ramonjd** [comment]
> Is it possible to use CSS class instead of inline styling for the letter case?

👋 

Many of the block supports add inline styles to a block's container element, for example, padding, margin and other typography settings. 

One advantage is that inline styles provide high specificity, which is great since user-defined values will override any theme defaults, which, I believe, is the intention.

Is there a specific reason for using a CSS class in this instance?

**Comment by dashkevych** [comment]
> One advantage is that inline styles provide high specificity, which is great since user-defined values will override any theme defaults, which, I believe, is the intention.

Thank you very much for explanation 🙏 It makes sense now.

**Comment by peXed** [comment]
@ramonjd 

I apologize for bringing up an old issue, but I am currently experiencing a problem with the inline styles that have been added. We would like to utilize a class instead, because the uppercase text requires a different letter-spacing in our design. Is there a way to achieve this?

**Comment by richtabor** [comment]
> Is there a way to achieve this?

You can now also add tracking/letter-spacing to blocks: 

<img width="902" alt="CleanShot 2023-01-25 at 13 43 29" src="https://user-images.githubusercontent.com/1813435/214654444-15ee5f32-d221-49f1-b0c9-cb4bc1f8e7f6.png">

**Comment by peXed** [comment]
> > Is there a way to achieve this?
> 
> You can now also add tracking/letter-spacing to blocks:
> 

Thank you for you reply. Unfortunatly, that is not what we need. Because of the font we are using, we always want to have a fixed letter spacing value for font that is all uppercase.
Always setting the letter spacing by hand will cause  a lot of errors.

**Comment by richtabor** [comment]
You can leverage theme.json `styles.blocks` settings to add letterSpacing to specific blocks — or `styles.typography` to apply it across the whole site. 

Here's how I did it with the `core/navigation` blocks, but you can do the same with `elements.headings` to target all headings:

<img width="417" alt="CleanShot 2023-02-10 at 10 09 21" src="https://user-images.githubusercontent.com/1813435/218125889-fbf1057a-1990-4884-8eb1-4a4ed287e4b5.png">

Or you can skip theme.json and do it right within Global Styles > Blocks > Heading > Typography, which would apply that spacing globally across all heading blocks.  

<img width="429" alt="CleanShot 2023-02-10 at 10 11 03" src="https://user-images.githubusercontent.com/1813435/218126350-8a76c432-4470-47a4-885f-781750d303ec.png">
