### ISSUE TITLE
Navigation block appender hard to see when have black background

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#20815]
If you select a black background you can make the appender very hard to see. I would suggest a border perhaps on the appender would solve this? cc @jasmussen for some input as this is since the recent interface iterations.

![image](https://user-images.githubusercontent.com/253067/76463402-39630600-63db-11ea-8fe9-e61b60f0d0b0.png)

Here is what it looks like with different background:

![image](https://user-images.githubusercontent.com/253067/76463345-189ab080-63db-11ea-8017-c00cad418e8c.png)

**Comment by mtias** [comment]
It seems that it's still alright given the + has enough contrast?

**Comment by jasmussen** [comment]
The usual way to handle contrast issues like this is to ensure that at any time, two colors are used. This is why there's a 1px white inner border on the primary button when focused. 

In this case, I'm also leaning towards Matías assessment that this button _has_ two colors, and therefore does serve its purpose. Might be worth sleeping on this one and seeing if it resurfaces as a consistent issue, and then tackle when we're sure it's a problem. Good ticket otherwise!

**Comment by karmatosed** [comment]
Ok happy to close it, there feels like a loss visually to me but happy to sleep on it and close for now.
