### ISSUE TITLE
Block Patterns: Coverblock is missing a CSS class

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#20825]
When adding the gradient coverblock via the Block Patterns in 7.7.0
the `has-background-gradient` CSS class is missing from the wrapping div on the front.

The class is added correctly in the editor.

This means that the block does not look the same on the front and in the editor and that the default `opacity: 0.5;` of the dim is much more difficult to remove.

**To reproduce**
1. Add the coverblock from the Block Patterns.
2. Save
3. View the front
4. See the default 0.5 opacity dim cover the block.

-If I manually add a new cover block with the same gradient, or if I change the gradient of the existing block, then the class is added on the front.

**Expected behavior**
I expect the class to be added, so that block on the front looks identical to the block in the editor.

**Desktop (please complete the following information):**
 - OS:  Win10
 - Browser: Chrome Version 80.0.3987.132

**Additional context**
- Please add the version of Gutenberg you are using in the description.
Version 7.7.0

WordPress Version 5.3.2

**Comment by youknowriad** [comment]
I looked deeper here and it seems it's not a patterns issue but the Cover image doesn't add the `has-background-gradient` className if a palette gradient is used, it's only added when custom gradients are used.

I believe that's probably consistent about how colors work (right @jorgefilipecosta), so it's intended.

that said, there's still a patterns bug, the pattern shouldn't be using aa "Palette" gradient because depending on the theme, the chosen gradient class might not be present.

So the action item here would be to update the pattern to use a custom gradient.

**Comment by mtias** [comment]
It's using the class instead of a custom gradient on purpose to see what sort of issues we run into.
