### ISSUE TITLE
Add a way to add inline text background color

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#20835]
It'd be nice to be able to add an inline text background color to any text. I've seen it's being called "highlight", but I'm not sure the proper name :)

**Example:**
![Pattern 37](https://user-images.githubusercontent.com/908665/76530573-d2416200-646b-11ea-8589-49fb244d66f4.jpg)

The text can be multi-lined, and a little detail that makes this nicer is to have side paddings so that the background doesn't get cut off immediately at where the text begins/ends. [An old CSS Tricks that talks about this](https://css-tricks.com/multi-line-padded-text/).

Previously: https://github.com/WordPress/gutenberg/pull/16014

**Comment by paaljoachim** [comment]
Associated with
"Bring colors by the block for some blocks"
https://github.com/WordPress/gutenberg/issues/20197

**Comment by dingo-d** [comment]
It would also be cool to add the gradient to the highlighted text in the `RichText` component. Currently, only the color can be added, either via inline `color:` style on `has-inline-color` span element or by referencing the color name registered in the global colors.

Since the inline color already uses a span to format it, and in order to apply the gradient to the text we'd need to add it as a background with background-clip, this shouldn't be that hard to implement.

**Comment by ArabCrew786** [comment]
# This is a Test, Test Color [Red](#)

**Comment by ArabCrew786** [comment]
<h1>This is a Test, Test of Color <span style="color:red">Red</span></h1>

**Comment by ArabCrew786** [comment]
![image](https://github.com/WordPress/gutenberg/assets/136216042/4110084b-c65c-4b22-bf51-ef43c1a360f8)
It does not work lol Wtf
please help how do i color a sentence

**Comment by ArabCrew786** [comment]
![image search api](https://user-images.githubusercontent.com/110724391/184472398-c590b47c-e1f2-41f8-87e6-2a1f68e8850d.png)[(Youtube)](https://www.youtube.com/watch?v=3HIr0imLgxM)
