### ISSUE TITLE
Global styles: resetting

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#20868]
This is pulling out some actions hidden in prototypes to have a discussion about where and how resetting of the global styles applied should happen. In the latest mocks resetting has 2 options:

- Undo the last action, redo the last action.
- Reset all global styles applied.

This shows when the global styles sidebar is activated.

<img width="1260" alt="reset-01" src="https://user-images.githubusercontent.com/253067/76618238-feb6b600-651f-11ea-8dd1-c10fc209a014.png">

By also applying and individual style to that block you over-rule any global styles, so in a way that resets also.

Here you see those called out more:

<img width="1260" alt="rest-02" src="https://user-images.githubusercontent.com/253067/76618259-0bd3a500-6520-11ea-9e40-f3323f7d121b.png">

However, it's worth discussing around a few points:

- Is this enough resetting?
- Does there need to be resetting of each block type?
- Should there be a resetting option outside of global styles itself?
- Should there be a message when you click 'reset'?
- Is 'reset' the right copy or should it be 'reset all', something else?

**Comment by MichaelArestad** [comment]
> Is this enough resetting?

To start, yes.

> Does there need to be resetting of each block type?

I think that's the next logical step. I think it could be explored on it its own because it might not necessarily need to be a "reset" button. It could just show you what the original settings were somehow.

> Should there be a resetting option outside of global styles itself?

Two scenarios that could be useful:
1. Block type resets
2. Full theme/template resets (but that feels a bit extreme)

> Should there be a message when you click 'reset'?

No. There is no message when you "Undo." 

> Is 'reset' the right copy or should it be 'reset all', something else?

This is a good question. Just some brainstorming here: "Restore default styles" is a bit more explicit, but is lengthy. I don't see this as a blocker as we can iterate on the verbiage.

**Comment by mapk** [comment]
> Is this enough resetting?

I believe so too! An undo AND a high-level reset link work IMO.

> Does there need to be resetting of each block type?

I like this idea and hadn't thought of it yet. Good call. Maybe it's like an "un-syncing" from the global styles which causes the block to return to the default setting (or theme setting).

> Should there be a resetting option outside of global styles itself?

Resetting global styles defaults back to the the theme's styles, correct? That seems sufficient to me. But resetting global styles shouldn't affect any individual block styling done. So if the user wanted to reset that, would it be block-per-block?

> Should there be a message when you click 'reset'?

This is where I might disagree with @MichaelArestad. An undo doesn't need a msg because it's incremental over the last several changes. But a global reset could reset things that were done days ago, right? Maybe in that case, there should be some messaging around it.

> Is 'reset' the right copy or should it be 'reset all', something else?

Maybe "Reset global styles"?

**Comment by MichaelArestad** [comment]
> But a global reset could reset things that were done days ago, right? Maybe in that case, there should be some messaging around it.

Possibly. Especially if you can't "Undo" the reset action.

**Comment by karmatosed** [comment]
Whilst I can see having a message could be needed, I would rather see what the flow feels like and add messaging, over bring in without knowing it's needed fully. I think everyone is majority in agreement, so let's move this into development for now as we can refine from there.

**Comment by mtias** [comment]
I think "resetting" should be within the global styles panel and there has to be more context around the action "Reset to theme default styles".
