### ISSUE TITLE
Consider the icon for global styles

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#20873]
With the recent icon work, I wanted to open up the discussion here about what icon should be used for the global styles at least in its first version. The current version is:

<img width="325" alt="Frame 5" src="https://user-images.githubusercontent.com/253067/76621917-5b1dd380-6528-11ea-9268-aca8b19135d8.png">

I personally, think this could be ok for a v1, but I feel it could be much better. Does anyone have some ideas here? I admit I am a little stuck on seeing beyond this right now, hence asking.

**Comment by pagelab** [comment]
The customizer [is represented](https://developer.wordpress.org/resource/dashicons/#admin-customizer) in the Dashicons icon font as a brush. 

So, maybe giving it a spin with another graphic element would do?

<img width="198" alt="Captura de Tela 2020-03-14 às 19 52 17" src="https://user-images.githubusercontent.com/1451087/76691768-555de600-662d-11ea-9169-2c9d2e98751a.png">

Or perhaps you could play with this crayons/settings idea:

<img width="163" alt="Captura de Tela 2020-03-14 às 19 52 27" src="https://user-images.githubusercontent.com/1451087/76691779-5f7fe480-662d-11ea-99cd-95ba0eea537a.png">

Another concept considering the dichotomy between global and local: a block inside a bigger block (a site), that also connects to the idea of a color wheel:

<img width="186" alt="Captura de Tela 2020-03-14 às 20 01 07" src="https://user-images.githubusercontent.com/1451087/76691893-8854a980-662e-11ea-9791-c93067bc51c6.png">

<img width="175" alt="Screen-Shot-2020-03-14-20-05-34" src="https://user-images.githubusercontent.com/1451087/76691967-26487400-662f-11ea-9427-d687e82cafa2.png">

Here's a sketch file with those ideas, feel free to use it:
[global-styles-ideas.sketch.zip](https://github.com/WordPress/gutenberg/files/4333500/global-styles-ideas.sketch.zip)

**Comment by pablohoneyhoney** [comment]
Adding to the conversation here. In the spirit of homogeneity, there's one icon for _color_ in [the new library](https://www.figma.com/file/fnyj380i05vGzuuH60frLQ/G2-Design?node-id=1970%3A0) that could work well:

<img width="396" alt="icon-globalstyles" src="https://user-images.githubusercontent.com/25516611/77347981-0b50c080-6d0f-11ea-96a2-9cd07ceda253.png">

In case we want to break out color and font properties, just did one for font:

<img width="396" alt="block-font" src="https://user-images.githubusercontent.com/25516611/77346620-ebb89880-6d0c-11ea-8583-4711bc443163.png">

**Comment by karmatosed** [comment]
Thanks for those ideas @pagelab and @pablohoneyhoney. I do like the crayons, but that probably when small will look a bit more like equalizers. My instinct is for the droplet as I can see it working nicely in this case.

**Comment by shaunandrews** [comment]
I think the droplet works well for color (and that's how we currently use it) specifically because its inner shape represents the selected color. I'm not the droplet works for Global Styles as there will be multiple control controls. Also, having the same icon for color and global styles would confuse me.

Maybe some combination of the droplet and the font icon could work?

Random ideas: 

- paintbrush
- palette
- blueprint
- fan deck (You know, those Pantone color reference thingies...)
- pencil + brush

**Comment by MichaelArestad** [comment]
The palette has worked well enough for the Customize sidebar item in wp-admin. This seems like a good application for it that might be familiar enough to understand. It's just a bit complex as far as shapes go.

**Comment by enriquesanchez** [comment]
I also think the palette could work well. It's already commonly seen as a styling tool.

And I'm also leaning towards the pencil + brush. Having these two tools together makes me think I can edit and style.

**Comment by pagelab** [comment]
More concepts for inspiration:

![more-concepts](https://user-images.githubusercontent.com/1451087/77699723-a953bd80-6f91-11ea-9cb2-d8a8e852bbb9.png)

**Comment by nosolosw** [comment]
https://github.com/WordPress/gutenberg/pull/24250 just landed and came with the [typography icon](https://github.com/WordPress/gutenberg/blob/master/packages/icons/src/library/typography.js). I wanted to ping folks about this, in case we can close this issue or want to update the icon.

**Comment by shaunandrews** [comment]
The typography icon is likely fine for now, but I do think a more representative icon is needed at some point down the road.

**Comment by noahshrader** [comment]
![global-styles](https://user-images.githubusercontent.com/3665539/94720868-00f92a00-0323-11eb-9eed-d3c5baf434eb.png)

Took a quick pass at this.

For some of the early explorations, I had been using a color palette icon (moreso to just have something there) in a style consistent with those found in the block editor. While I love the consistency with the Customizer, and the icon being a relatively common indicator of style/color, it's really just that: _color_.

The above concept combines two elements that I think best represent the scope of global styles: _styling elements_ (paintbrush) and _measuring elements_(ruler) - both globally recognized. I agree with earlier sentiment here of keeping the shape as simple as possible, without obscuring (though really, once discovered, isn't overly critical).

Just a thought; not tied to it.

**Comment by MichaelArestad** [comment]
@noahshrader I like the direction. How does it look in context?

**Comment by pablohoneyhoney** [comment]
To pick this up, sharing here an icon that's cleaner, contextually more balanced, and more encompassing of all the capabilities and intricacies of GS. It also plays along with other new icons and evolving language. 

<img width="336" alt="global styles" src="https://user-images.githubusercontent.com/25516611/109843984-accbdc00-7c19-11eb-8d39-07d58d92538e.png">

<img width="326" alt="Screen Shot 2021-03-03 at 12 13 46 PM" src="https://user-images.githubusercontent.com/25516611/109844479-2cf24180-7c1a-11eb-8ab2-c0d24393278a.png">

Other explorations here too, some of which could perhaps land themselves in more specific functions if needed. 

<img width="445" alt="Screen Shot 2021-03-03 at 12 19 34 PM" src="https://user-images.githubusercontent.com/25516611/109845052-bace2c80-7c1a-11eb-9b61-a80172e3ca1d.png">

**Comment by estelaris** [comment]
The design team reviewed today and we think that more iterations are needed. We feel like most of the icons presented make reference to color

**Comment by paaljoachim** [comment]
Here is a link to the discussion: https://wordpress.slack.com/archives/C02S78ZAL/p1615306694219300

**Comment by kjellr** [comment]
> To pick this up, sharing here an icon that's cleaner, contextually more balanced, and more encompassing of all the capabilities and intricacies of GS. It also plays along with other new icons and evolving language.
> 
> ![](https://user-images.githubusercontent.com/25516611/109843984-accbdc00-7c19-11eb-8d39-07d58d92538e.png)

My main hesitation with this version is its similarity to [the standard "contrast" icon](https://www.google.com/search?tbm=isch&sxsrf=ALeKk01oy6Le6nGpNQXQYGuhQFb-HMNAgA%3A1615312604924&source=hp&biw=1299&bih=839&ei=3LZHYMPONa6q5NoP-_a-wA4&q=contrast+icon&oq=contrast+icon&gs_lcp=CgNpbWcQAzIECCMQJzICCAAyAggAMgYIABAFEB4yBggAEAUQHjIGCAAQBRAeMgYIABAFEB4yBggAEAUQHjIGCAAQCBAeMgYIABAIEB46CAgAELEDEIMBOgUIABCxA1DFFlirHmDZH2gAcAB4AIABWYgBgAaSAQIxM5gBAKABAaoBC2d3cy13aXotaW1n&sclient=img&ved=0ahUKEwjDrI-w5KPvAhUuFVkFHXu7D-gQ4dUDCAY&uact=5). I could get used to it, but I'm not sure I'd know what that meant the first time I saw it in context. 

I do think some of the more artistic icons (brush, ruler, etc) are a clearer metaphor, though since Global Styles covers so many different options, some sort of abstract icon might be our best bet here.

**Comment by pagelab** [comment]
>  Some sort of abstract icon might be our best bet here.

I imagine that a totally abstract icon, not based on the task at hand in any way, will require a high dose of good faith from the user to understand it, which is not ideal in this case.

It's definitely possible to learn the meaning over time, of course, but just like pretty much all other icons in use today ([Gutenberg icon library](https://www.figma.com/file/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library?node-id=8%3A13) or [Dashicons font](https://developer.wordpress.org/resource/dashicons/)) adopt some form of figurative representation,  I would argue that the same is needed here to make this new feature a little more obvious and to arouse more interest in it at the same time – like it was done for the Share and REST API Icons, which are “almost” abstract.

<img width="107" alt="main-share-icon" src="https://user-images.githubusercontent.com/1451087/133324009-16987064-bd54-4f29-9264-2d23520db950.png">

<img width="124" alt="rest-api-icon" src="https://user-images.githubusercontent.com/1451087/133323686-095bfb4e-588a-4441-9933-a0251f721d78.png">

**Comment by ghost** [comment]
Please, reconsider the chosen icon.

Problem:
When "light/dark mode" is an icon instead of a toggle, websites and applications choose this icon to indicate "light/dark mode".

Settings regarding "design, appearance and styles" commonly are represented on projects by a brush icon or a color palette.

Even though this new feature, Global Styles, has a larger scope than what WordPress used to offer, I don't see the benefit in choosing an abstract icon to convey the idea.

Global Styles is not a new system disconnected from styles and themes, indeed is an improvement to the current themes system. If we were to consider the strength of WordPress' past and present, we would perceive that on the dashboard, indeed a brush icon has been developed for years in people's memory as an association with appearance, themes, styles, personalization. Therefore, the icon that would be most comprehensible in people's memory regarding the new Customizer remains a brush. I say new and better Customizer, because this is how common people manifest what they understand about Global Styles. Departing from a pencil brush to yin-yang, moon, or water drop, I have not tested yet with public, but from past experience I assure you people are going to find this new icon unrelated and confusing.

Proposed solution:
It would be desirable to honor the current dashboard icon regarding Themes, a pencil brush, bring it into Gutenberg in order to maintain the subjectivity regarding Themes permeating WordPress project, and hold a referendum with the public outside the developers' scope regarding the experimentation and initiatives here.

**Comment by ZebulanStanphill** [comment]
I don't see how a half-moon shape has anything to do with styles. Like the previous comment pointed out, it looks like a dark-mode toggle icon. A brush makes far more sense for something related to "styles", and the icon is already used by WordPress so there's familiarity with it.
