### ISSUE TITLE
Add block: lock Page/Post for all non-Admins Roles

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#2090]
I personaly needed it on almost all my websites. Would not go in the detail, can just say Contact Page, CF7 and Google Maps embed code. (I know I could call all of it in template with PHP code directly. But....) Or some other Pages with shortcodes (now blocks) that may not change under any circumstances. Or say bbBpress Page serving as template, etc....

What I would ask, and would never dare normaly, but now when you make Gutenberg I can do it.

- Add new block visible in Inserter only to admins, and not any of the other Roles.
- When this block is inserted in the Page (or Post), Page is locked for all roles under Admin, Not even Title would be possible to edit. View permission can stay, but Edit is away.

**Comment by StaggerLeee** [comment]
I do it allways with custom snippet in own functions.php. Array of Page IDs, and they are gone for all except Admins from Page listing.

Still, one block like that would be nice to have.

**Comment by annaephox** [comment]
Interesting idea @StaggerLeee ! We have been chatting about this too, but envisioned that the lock-down could happen at the block-level (possibly in addition to the page level). The idea would be that a developer/agency could create page templates, and lock down certain blocks so that their clients/content creators would not "spoil" the page layout, for example

<img width="1081" alt="screen shot 2017-07-31 at 4 21 18 pm" src="https://user-images.githubusercontent.com/25762760/28765116-605df306-760c-11e7-8bca-f7dda2fa24b3.png">

@jasmussen : what are your thoughts/does this align with Gutenberg priorities?

(cc @EphoxJames)

**Comment by jasmussen** [comment]
I like this, especially for templates. 

On one hand I like the crosses on the borders because they make it visual that the block is locked, even just looking at the silhuette. On the other hand, it adds visual weight. Perhaps we should look at "graying" a bit, if at all possible, maybe adding a lock icon in a corner. 

I would suggest it's great to explore this concept further, but probably not necessarily build it quite yet. It seems like something we definitely want to do down the road, but that probably the pieces in place currently should solidify and receive polish first. But good to think about, as there are a lot of unknowns. For example, what if you insert a new block below the locked block, and move it up — can you?

**Comment by StaggerLeee** [comment]
Just give each block same background-color, to differentiate them from editable ones.
Or some 1-3 pixels border in different color. And mouseover, hover popover "Block cannot be edited", or similar.
Dont forget Title and Slug. If User (say Editor) can change them, everything else is pointless.

**Comment by youknowriad** [comment]
Templates and templates locking is shipped now and you can switch the template lock level based on the logged-in user. 

see https://wordpress.org/gutenberg/handbook/templates/

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1518714794000004)._
