### ISSUE TITLE
wp-env requires node v11, not mentioned anywhere

### ISSUE THREAD

**Issue by slaFFik** [WordPress/gutenberg#20923]
**Describe the bug**
To avoid situations like in #20661 it might be a good idea to notify somehow somewhere about the package requirements.

**To reproduce**
1. Make sure you have Node v10 LTS installed
2. Install `wp-env` (no errors)
3. try to run `wp-env start` - you will get an error (see #20661)

**Expected behavior**
1. Include the requirements in package.json file of the package (via [`engines`](https://docs.npmjs.com/files/package.json#engines))
1. Include the check during the installation

Related discussion: https://github.com/WordPress/gutenberg/issues/20661#issuecomment-599485768

**Comment by noahtallen** [comment]
Coincidentally, this will be resolved in https://github.com/WordPress/gutenberg/pull/21229 because we won't use flatMap any more. So v10 will work correctly.

The Gutenberg repo uses lts as the minimum node version in general (visible in `.nvmrc`), which is currently v12. I wonder if there is a way to extend that locally. 🤔 We definitely need to at least show a warning when running wp-env commands if the node version is incompatible. The only reason I wouldn't think to use engines at first is that we'd have to continuously update it to the most recent LTS versions, so we'd likely get behind on that
