### ISSUE TITLE
Embeds: Support additional parameters in YouTube embed URLs.

### ISSUE THREAD

**Issue by kwight** [WordPress/gutenberg#21002]
The YouTube block will properly handle an embed video, of the format `https://www.youtube.com/embed/:id`. Their embed API allows for [additional parameters](https://developers.google.com/youtube/player_parameters), but adding any of these parameters will break Gutenberg's handling of the URL.

![2020-03-18 13 45 40](https://user-images.githubusercontent.com/349751/77006386-9a309800-691f-11ea-8f03-ea828c1f6c06.gif)

Support for these params could be very helpful – in particular the `rel` param, allowing suggested videos at the end of playing to be from the video's own account.

**Comment by Soean** [comment]
Hey @kwight , thanks for opening this issue, we already have an open issue about the youtube parameters, see #9678.
So I will close this one.

**Comment by Soean** [comment]
I am reopening the issue. Even though we don't support the parameters yet, the video should work.

**Comment by bobeaston** [comment]
Another vote in favor.  I too use rel=0 to keep visitors on my site (seeing my own videos rather than others as "recommended vids.")
Currently, I use override code in functions.php to ensure the parm gets attached.  Would be better to have it included as valid.

**Comment by bobeaston** [comment]
In the meantime, there's [a solution](// https://wpforthewin.com/remove-related-videos-wp-gutenberg-embed-blocks/) that can be added to functions.php.

**Comment by talldan** [comment]
This might need to be a trac ticket (oEmbed handling code is in WP Core).

Some prior tickets where this was discussed:
- https://core.trac.wordpress.org/ticket/32353
- https://core.trac.wordpress.org/ticket/33072

**Comment by bobeaston** [comment]
THANKS talldan!  I had not chased down those trac tickets.  Thanks for bringing them up.

From the gist of those tickets, and swisspidy's  comments in particular, it will do little good to argue for the change in WP Core. swisspidy argues that adding parameter selection/passing to WP Core's oEmbed code, if done for this one YouTube parm, would have to be done for lots of other parms and providers too.  I've browsed that code and understand his reluctance.

I have not yet chased the code for the Gutenberg YouTube block.  If it simply passes the provided url to the oEmbed code, I guess this request will die.  

If not, since the block is isolated to YouTube, maybe there's an opportunity to fix it here without having to worry about all the other video providers?

Meanwhile, I'm sticking with a very simple post-embed fix:
```
<?php  /// discard this line ///
// Add &rel=0 to Gutenberg YouTube Blocks
function ree_youtube_player( $block_content, $block ) {
  if( "core-embed/youtube" === $block['blockName'] ) {
    $block_content = str_replace( '?feature=oembed', '?feature=oembed&rel=0', $block_content );
  }
  return $block_content;
}
add_filter( 'render_block', 'ree_youtube_player', 10, 3);
```

**Comment by jordesign** [comment]
Looking at the Trac tickets listed above - this is a Won'tfix as part of core - as it would mean we need to start setting up ways to handle all attributes from all oEmbed providers. it is recommended to look into plugin options instead. Accordingly, I'll be closing this issue.
