### ISSUE TITLE
Global styles: link color setting

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#21032]
A common thing to change outside a theme is a link color. When you set that, there is a need to also set hover and active colors. I began exploring what this could look like and a tabbed interface could be an option:

![image](https://user-images.githubusercontent.com/253067/77117571-31821200-6a2a-11ea-9338-83f72f212c69.png)

In the context of a larger screen that would look like this:

<img width="1260" alt="all" src="https://user-images.githubusercontent.com/253067/77117598-3f379780-6a2a-11ea-87b3-3d2d2314318f.png">

**Comment by karmatosed** [comment]
To go further, the colors should show by default the theme specified ones. You can then click each and replace with a custom color. There is a reset option to clear all. 

If there aren't any theme set colors it should have defaults. My recommendation would be the blue wee use for links,  black, white and a grey.

<img width="689" alt="colors" src="https://user-images.githubusercontent.com/253067/77210752-a6704d00-6af9-11ea-9a40-76c1ee458309.png">

Default suggestions:

<img width="223" alt="Frame 10" src="https://user-images.githubusercontent.com/253067/77211336-99ecf400-6afb-11ea-8c4d-0368356c526f.png">

**Comment by carolinan** [comment]
What about the visited links?

**Comment by karmatosed** [comment]
@carolinan do you think they should have a custom colour or default to a variation (darker/lighter) from another?

**Comment by aristath** [comment]
I don't think I've seen a different color used for visited in many, many years!

**Comment by carolinan** [comment]
When reviewing themes it is most notable when the author sets a default color for _all_ link statuses, then adds color options for links and _forgets to apply the color to the visited links._

It might be just fine to apply the "link color" also to the visited link status. But if the visited link is left defaulting to the theme color, all sort of things can happen like white text over white background. 

If we look at themes in the theme directory (via wpdirectory.net) , a:active has a larger number than a:visited. 
a:active 28294
a:visited 25167

I don't think it is common to add a different color to a:active either, it is usually the same color as hover.  That has a bigger impact on buttons with a much larger click area.

The accessibility benefit if the visited link has a different color than the standard link is likely very small because there would need to also be a text decoration change.

**Comment by GrimLink** [comment]
@carolinan I don't think the visited pseudo state helps anyone.
It would be better to drop this style from the link styles and other blocks like the button.

In most CSS stacks/frameworks it is not styled anymore.
So I am surprised it is in the Gutenberg blocks, and then also we have the matter of the privacy points around the visited pseudo state.

So to simplify stuff, it would be better to drop the styles for this.

**Comment by mtias** [comment]
Link color is supported as an element now, and other states are being covered by #27075 and #38277.
