### ISSUE TITLE
React Warning with v16.13: Cannot update a component while rendering a different component, bad setState() call 

### ISSUE THREAD

**Issue by ocean90** [WordPress/gutenberg#21049]
**Describe the bug**
[React 16.13.0](https://github.com/facebook/react/releases/tag/v16.13.0) introduced a warning for when a function component is updated during another component's render phase (https://github.com/facebook/react/pull/17099). In [version 16.13.1](https://github.com/facebook/react/releases/tag/v16.13.1) the warning was adjusted to be more specific (https://github.com/facebook/react/pull/18330).

The warning looks like this:

> index.js:1 Warning: Cannot update a component (`Foo`) while rendering a different component (`Bar`). To locate the bad setState() call inside `Bar`, follow the stack trace as described in https://fb.me/setstate-in-render

Such a warning is currently triggered when using the `useSelect()` hook from the `@wordpress/data` package in a React app with v16.13.x.
In my app I have three components which all retrieve the data from the store through the `useSelect()` hook which now each log such a warning.

The warning seems to get triggered by [onStoreChange](https://github.com/WordPress/gutenberg/blob/f0e36362104e9be9e655ce8cfa9e5c6b45913602/packages/data/src/components/use-select/index.js#L140).

**To reproduce**
I was able to get the warning with Gutenberg as well.

1. Go to `gutenberg_register_vendor_scripts()` and add the following lines:
   ```php
	$react_suffix = ( SCRIPT_DEBUG ? '.development' : '.production' ) . $suffix;
	gutenberg_register_vendor_script(
		$scripts,
		'react',
		'https://unpkg.com/react@16.13.1/umd/react' . $react_suffix . '.js',
		array( 'wp-polyfill' )
	);
	gutenberg_register_vendor_script(
		$scripts,
		'react-dom',
		'https://unpkg.com/react-dom@16.13.1/umd/react-dom' . $react_suffix . '.js',
		array( 'react' )
	);
	```
2. In package.json bump the version of react and react-dom to 16.13.1
3. Run `npm i` and `npm run dev`
4. Create a new post
5. Open browser console
5. Insert an image block
6. Upload an image and wait until it's inserted
7. See error message in browser console

<details>
<summary>Error Message</summary>

```
Warning: Cannot update a component (`Unknown`) while rendering a different component (`Unknown`). To locate the bad setState() call inside `Unknown`, follow the stack trace as described in https://fb.me/setstate-in-render
    in Unknown (created by WithSelect(WithViewportMatch((ImageEdit))))
    in WithSelect(WithViewportMatch((ImageEdit))) (created by WithDispatch(WithSelect(WithViewportMatch((ImageEdit)))))
    in WithDispatch(WithSelect(WithViewportMatch((ImageEdit)))) (created by Edit)
    in Edit (created by WithToolbarControls(Edit))
    in WithToolbarControls(Edit) (created by WithInspectorControl(WithToolbarControls(Edit)))
    in WithInspectorControl(WithToolbarControls(Edit)) (created by WithInspectorControl(WithInspectorControl(WithToolbarControls(Edit))))
    in WithInspectorControl(WithInspectorControl(WithToolbarControls(Edit)))
    in Unknown (created by WithDispatch(Component))
    in WithDispatch(Component)
    in Unknown (created by WithMultipleValidation(WithInspectorControl(WithInspectorControl(WithToolbarControls(Edit)))))
    in WithMultipleValidation(WithInspectorControl(WithInspectorControl(WithToolbarControls(Edit)))) (created by WithFilters(Edit))
    in WithFilters(Edit) (created by BlockEdit)
    in BlockEdit (created by BlockListBlock)
    in BlockCrashBoundary (created by BlockListBlock)
    in BlockListBlock (created by (BlockListBlock))
    in (BlockListBlock) (created by WithFilters(BlockListBlock))
    in WithFilters(BlockListBlock) (created by IfCondition(WithFilters(BlockListBlock)))
    in IfCondition(WithFilters(BlockListBlock)) (created by WithDispatch(IfCondition(WithFilters(BlockListBlock))))
    in WithDispatch(IfCondition(WithFilters(BlockListBlock)))
    in Unknown (created by WithSelect(WithDispatch(IfCondition(WithFilters(BlockListBlock)))))
    in WithSelect(WithDispatch(IfCondition(WithFilters(BlockListBlock))))
    in Unknown (created by Pure(WithViewportMatch(WithSelect(WithDispatch(IfCondition(WithFilters(BlockListBlock)))))))
    in Pure(WithViewportMatch(WithSelect(WithDispatch(IfCondition(WithFilters(BlockListBlock)))))) (created by ForwardRef(BlockList))
    in div (created by ForwardRef(RootContainer))
    in div (created by InsertionPoint)
    in InsertionPoint (created by ForwardRef(RootContainer))
    in ForwardRef(RootContainer) (created by ForwardRef(BlockList))
    in ForwardRef(BlockList) (created by ForwardRef)
    in ForwardRef (created by VisualEditor)
    in div (created by CopyHandler)
    in CopyHandler (created by WithDispatch(CopyHandler))
    in WithDispatch(CopyHandler) (created by VisualEditor)
    in div (created by ObserveTyping)
    in ObserveTyping (created by WithSafeTimeout(ObserveTyping))
    in WithSafeTimeout(ObserveTyping) (created by VisualEditor)
    in div (created by WritingFlow)
    in div (created by WritingFlow)
    in WritingFlow (created by VisualEditor)
    in div (created by CopyHandler)
    in CopyHandler (created by WithDispatch(CopyHandler))
    in WithDispatch(CopyHandler) (created by VisualEditor)
    in div (created by Typewriter)
    in Typewriter
    in Unknown (created by WithSelect(Typewriter))
    in WithSelect(Typewriter) (created by VisualEditor)
    in div (created by BlockSelectionClearer)
    in BlockSelectionClearer (created by WithDispatch(BlockSelectionClearer))
    in WithDispatch(BlockSelectionClearer)
    in Unknown (created by WithSelect(WithDispatch(BlockSelectionClearer)))
    in WithSelect(WithDispatch(BlockSelectionClearer)) (created by VisualEditor)
    in VisualEditor (created by Layout)
    in div (created by EditorSkeleton)
    in div (created by EditorSkeleton)
    in div (created by EditorSkeleton)
    in EditorSkeleton (created by NavigateRegions(EditorSkeleton))
    in div (created by NavigateRegions(EditorSkeleton))
    in NavigateRegions(EditorSkeleton) (created by Layout)
    in div (created by FocusReturnProvider)
    in FocusReturnProvider (created by Layout)
    in Layout (created by Editor)
    in ErrorBoundary (created by Editor)
    in BlockEditorProvider (created by WithDispatch(BlockEditorProvider))
    in WithDispatch(BlockEditorProvider)
    in Unknown (created by Context.Consumer)
    in WithRegistryProvider(WithDispatch(BlockEditorProvider)) (created by EditorProvider)
    in EntityProvider (created by EditorProvider)
    in EntityProvider (created by EditorProvider)
    in EditorProvider (created by WithDispatch(EditorProvider))
    in WithDispatch(EditorProvider)
    in Unknown (created by WithSelect(WithDispatch(EditorProvider)))
    in WithSelect(WithDispatch(EditorProvider))
    in Unknown (created by Context.Consumer)
    in WithRegistryProvider(WithSelect(WithDispatch(EditorProvider))) (created by Editor)
    in div (created by DropZoneProvider)
    in DropZoneProvider (created by Editor)
    in SlotFillProvider (created by SlotFillProvider)
    in SlotFillProvider (created by Editor)
    in StrictMode (created by Editor)
    in Editor (created by WithDispatch(Editor))
    in WithDispatch(Editor)
    in Unknown (created by WithSelect(WithDispatch(Editor)))
    in WithSelect(WithDispatch(Editor))
```
</details>

<details>
<summary>Error Stack</summary>

```
r	@	react_devtools_backend.js:6
printWarning	@	react-dom.82e849f1.js:82
error	@	react-dom.82e849f1.js:54
warnAboutRenderPhaseUpdatesInDEV	@	react-dom.82e849f1.js:23376
scheduleUpdateOnFiber	@	react-dom.82e849f1.js:21300
dispatchAction	@	react-dom.82e849f1.js:15795
onStoreChange	@	index.js:156
(anonymous)	@	index.js:172
(anonymous)	@	registry.js:54
globalListener	@	registry.js:54
(anonymous)	@	index.js:93
dispatch	@	redux.js:221
(anonymous)	@	index.js:24
(anonymous)	@	promise-middleware.js:20
(anonymous)	@	resolvers-cache-middleware.js:52
_callee$	@	index.js:257
tryCatch	@	wp-polyfill.js?ver=7.4.4:6496
invoke	@	wp-polyfill.js?ver=7.4.4:6722
prototype.<computed>	@	wp-polyfill.js?ver=7.4.4:6548
asyncGeneratorStep	@	asyncToGenerator.js:3
_next	@	asyncToGenerator.js:25
(anonymous)	@	asyncToGenerator.js:32
(anonymous)	@	asyncToGenerator.js:21
_fulfillSelector	@	index.js:236
fulfillSelector	@	index.js:236
selectorResolver	@	index.js:271
(anonymous)	@	edit.js:727
mapSelect	@	index.js:55
useSelect	@	index.js:104
(anonymous)	@	index.js:56
renderWithHooks	@	react-dom.82e849f1.js:14938
updateFunctionComponent	@	react-dom.82e849f1.js:17169
beginWork	@	react-dom.82e849f1.js:18745
beginWork$1	@	react-dom.82e849f1.js:23314
performUnitOfWork	@	react-dom.82e849f1.js:22289
workLoopSync	@	react-dom.82e849f1.js:22265
performSyncWorkOnRoot	@	react-dom.82e849f1.js:21891
(anonymous)	@	react-dom.82e849f1.js:11224
unstable_runWithPriority	@	react.af754d50.js:2685
runWithPriority$1	@	react-dom.82e849f1.js:11174
flushSyncCallbackQueueImpl	@	react-dom.82e849f1.js:11219
flushSyncCallbackQueue	@	react-dom.82e849f1.js:11207
scheduleUpdateOnFiber	@	react-dom.82e849f1.js:21334
dispatchAction	@	react-dom.82e849f1.js:15795
onStoreChange	@	index.js:156
(anonymous)	@	index.js:172
(anonymous)	@	registry.js:54
globalListener	@	registry.js:54
(anonymous)	@	index.js:93
dispatch	@	redux.js:221
(anonymous)	@	index.js:24
(anonymous)	@	promise-middleware.js:20
(anonymous)	@	resolvers-cache-middleware.js:52
dispatch	@	redux.js:563
(anonymous)	@	runtime.js:63
(anonymous)	@	create.js:37
(anonymous)	@	runtime.js:39
(anonymous)	@	create.js:47
next	@	create.js:46
(anonymous)	@	create.js:38
(anonymous)	@	runtime.js:39
(anonymous)	@	create.js:47
next	@	create.js:46
(anonymous)	@	create.js:38
(anonymous)	@	runtime.js:39
(anonymous)	@	create.js:47
next	@	create.js:46
(anonymous)	@	create.js:38
iterate	@	create.js:51
runtime	@	create.js:73
(anonymous)	@	runtime.js:59
(anonymous)	@	runtime.js:58
(anonymous)	@	index.js:27
(anonymous)	@	promise-middleware.js:20
(anonymous)	@	resolvers-cache-middleware.js:52
(anonymous)	@	index.js:207
(anonymous)	@	index.js:138
(anonymous)	@	runtime.js:34
(anonymous)	@	create.js:47
next	@	create.js:46
(anonymous)	@	create.js:38
(anonymous)	@	runtime.js:39
(anonymous)	@	create.js:47
next	@	create.js:46
(anonymous)	@	create.js:38
(anonymous)	@	runtime.js:39
(anonymous)	@	create.js:47
next	@	create.js:46
(anonymous)	@	create.js:38
(anonymous)	@	runtime.js:39
(anonymous)	@	create.js:47
next	@	create.js:46
(anonymous)	@	create.js:38
iterate	@	create.js:51
runtime	@	create.js:73
(anonymous)	@	runtime.js:59
(anonymous)	@	runtime.js:58
(anonymous)	@	index.js:27
(anonymous)	@	promise-middleware.js:20
(anonymous)	@	resolvers-cache-middleware.js:52
(anonymous)	@	refx.js:32
(anonymous)	@	index.js:207
(anonymous)	@	use-dispatch-with-map.js:68
(anonymous)	@	index.js:142
(anonymous)	@	registry.js:54
globalListener	@	registry.js:54
(anonymous)	@	index.js:93
dispatch	@	redux.js:221
(anonymous)	@	index.js:24
(anonymous)	@	promise-middleware.js:20
(anonymous)	@	resolvers-cache-middleware.js:52
(anonymous)	@	index.js:15
(anonymous)	@	refx.js:32
(anonymous)	@	index.js:207
setAttributes	@	block.js:300
(anonymous)	@	use-dispatch-with-map.js:68
onSelectImage	@	edit.js:221
setMedia	@	index.js:132
setAndUpdateFiles	@	upload-media.js:83
_callee$	@	upload-media.js:190
tryCatch	@	wp-polyfill.js?ver=7.4.4:6496
invoke	@	wp-polyfill.js?ver=7.4.4:6722
prototype.<computed>	@	wp-polyfill.js?ver=7.4.4:6548
asyncGeneratorStep	@	asyncToGenerator.js:3
_next	@	asyncToGenerator.js:25
Promise.then (async)		
asyncGeneratorStep	@	asyncToGenerator.js:13
_next	@	asyncToGenerator.js:25
(anonymous)	@	asyncToGenerator.js:32
(anonymous)	@	asyncToGenerator.js:21
_uploadMedia	@	index.js?ver=43ddf24…192103306bc7f1:1373
uploadMedia	@	upload-media.js:67
(anonymous)	@	index.js:37
onFilesUpload	@	index.js:134
onUpload	@	index.js:108
callCallback	@	react-dom.82e849f1.js:182
invokeGuardedCallbackDev	@	react-dom.82e849f1.js:231
invokeGuardedCallback	@	react-dom.82e849f1.js:286
invokeGuardedCallbackAndCatchFirstError	@	react-dom.82e849f1.js:300
executeDispatch	@	react-dom.82e849f1.js:383
executeDispatchesInOrder	@	react-dom.82e849f1.js:408
executeDispatchesAndRelease	@	react-dom.82e849f1.js:3401
executeDispatchesAndReleaseTopLevel	@	react-dom.82e849f1.js:3410
forEachAccumulated	@	react-dom.82e849f1.js:3382
runEventsInBatch	@	react-dom.82e849f1.js:3427
runExtractedPluginEventsInBatch	@	react-dom.82e849f1.js:3637
handleTopLevel	@	react-dom.82e849f1.js:3681
batchedEventUpdates$1	@	react-dom.82e849f1.js:22006
batchedEventUpdates	@	react-dom.82e849f1.js:792
dispatchEventForLegacyPluginEventSystem	@	react-dom.82e849f1.js:3691
attemptToDispatchEvent	@	react-dom.82e849f1.js:4390
dispatchEvent	@	react-dom.82e849f1.js:4312
unstable_runWithPriority	@	react.af754d50.js:2685
runWithPriority$1	@	react-dom.82e849f1.js:11174
discreteUpdates$1	@	react-dom.82e849f1.js:22022
discreteUpdates	@	react-dom.82e849f1.js:803
dispatchDiscreteEvent	@	react-dom.82e849f1.js:4291
```

</details>

**Expected behavior**
No warning should be triggered.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 80

**Additional context**
* https://github.com/facebook/react/issues/18178#issuecomment-595846312

**Comment by ocean90** [comment]
@nerrad Any thoughts on this warning in `useSelect()`? Is it a valid issue?

**Comment by nerrad** [comment]
Thanks for documenting this @ocean90.  I followed the steps to swap in React v16.13.  I also see the warning when I just _select_ an existing image block.

**Comment by nerrad** [comment]
I spent a bit of time trying to debug this, but I'm a bit stumped. It looks like the `forceRender` call in `onStoreChange` is what triggers this warning. The stack reveals it is when `onStoreChange` is triggered from the subscription callback registered to the store. There _may_ be a race condition happening here in that when the `forceRender` is called, the component it is invoked within is already re-rendering because of some other state change.

The one thing I _was_ able to verify, is that if I change [this code](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/image/edit.js#L733) so that `getMedia( id )` is not called, there is no warning when I select the image after initial editor load. Since this selector is triggering a resolution state, this is what triggers the subscriber call when the image is resolved.

I also discovered that if I _wait a few seconds_ before selecting the image on initial editor load, there is no warning when I select the image.  So that gives further credence to the race condition theory here.  I'm suspecting this timeline:

- Editor with image block loads.
- Image component is rendered and `getMedia( id )` triggers a resolution for the component.
- If the image block is selected _before_ the resolution is complete, then it is being re-rendered _before_ the resolution has completed. Resolution completes, and this triggers a subscriber call, which triggers a re-render of the component, which triggers the react warning.
- If the resolver resolves and the image block is re-rendered _before_ selecting it, then no warning occurs.

**Comment by nerrad** [comment]
cc @aduth and @youknowriad might need your input on this as well. If the above timeline is correct, this could be problematic when we bump the React version to React 16.3+

**Comment by youknowriad** [comment]
Created this PR https://github.com/WordPress/gutenberg/pull/21289 to allow us to investigate this better.

**Comment by youknowriad** [comment]
Can we reproduce this issue elsewhere? I mean the image block is a big one, it would be good if we find ways to reproduce this in a more contained environment.

**Comment by youknowriad** [comment]
Seems like this is a related PR on a similar library https://github.com/dai-shi/react-tracked/pull/42/files

**Comment by youknowriad** [comment]
Digging a little bit, it seems the `getMedia` is called during the "rendering" time (not inside a useEffect), this causes resolvers to run sync, these resolvers may or may not update the redux state, when they do update, it triggers a "subscribe" to all listeners. these listeners will trigger `onStoreChange` on child components.

I found that wrapping `onStoreChange` in `setTimeout` to make it async solves the issue. Maybe it's the right fix here but doing so surfaces other issues (Slot/Fill) where we try to call `setState` on unmounted components (merging two paragraphs).

I wonder where this rabbit hole leads :P

**Comment by ocean90** [comment]
> Can we reproduce this issue elsewhere?

You mean in Gutenberg or a React app which just uses the `@wordpress/data` package? If for the latter, I can try to create a reduced version of my use case.

**Comment by Fanaticys** [comment]
It reproduces when I write:
`
const handleToggleChange = () =>
       setChecked(state => {
       newState = !state;
       onChange(newState);
       return newState;
    });
`
And this change fixes the problem:
`
const handleToggleChange = () => {
  setChecked(!checked);
  props.onChange(!checked);
}
`

**Comment by epiqueras** [comment]
Oooh, I've been keeping an eye on this one.

It's something that came up as React is getting stricter and stricter in preparation for Concurrent Mode (CM).

Another thing that we will need to take care of later is [tearing](https://stackoverflow.com/questions/54891675/what-is-tearing-in-the-context-of-the-react-redux). This is when state changes while a render is interrupted and the continuation of the render uses different values. It's even harder to get right for `useTransition` or updates that are triggered from events triggered while rendering.

Third-party library authors are going crazy in trying to get their implementations to work:
https://github.com/dai-shi/lets-compare-global-state-with-react-hooks#comparison-table
https://github.com/dai-shi/will-this-react-global-state-work-in-concurrent-mode#results

The React team published an external [`useSubscription`](https://github.com/facebook/react/tree/master/packages/use-subscription) hook to help. However, it can still cause tearing when components are first subscribing, so they then built an internal [`useMutableSource`](https://github.com/reactjs/rfcs/blob/master/text/0147-use-mutable-source.md) which leverages internals to avoid tearing in all cases and supports subscribing to specific slices of state.

There are still competing RFCs, though, e.g., there are talks on having Context support selectors so that it can replace all of these performance hacks. That would circumvent tearing because as long as updates are not triggered in renders, React makes sure that a paused render continues with cached context values.

Jumping to any one of these solutions would be premature and send us down a costly rabbit hole.

This specific issue is flaring up because of selectors synchronously triggering resolvers, which in turn synchronously trigger store subscriptions. I think that it makes a lot of sense for resolvers to trigger asynchronously. I pushed that to #21289, and the warning is gone.

I still think we should hold off on upgrading React until they stabilize a proper API for this, and we can refactor `@wordpress/data` to use it.

**Comment by mayanktiwaridotcom** [comment]
I faced something similar when I tried to bind onClick on Parent component loop instead of passing method as prop to lift up state.
so for example:
```
 this.props.contactList.map((value, index) => {
                        return (
                            <ChatListRow key={value.id} contact={value} active={this.props.activeChat} onClick={this.markSelected}/>
                        )
                    })
```

I solved it by:
`
//parent component
this.props.contactList.map((value, index) => {
                        return (
                            <ChatListRow key={value.id} contact={value} active={this.props.activeChat} markSelectedhandler={this.markSelected}/>
                        )
                    })
//in child component
<div
            className={`media p-1 d-flex align-items-center ${(props.active === props.contact.userId) ? 'bg-dark text-light' : ''}`}
            onClick={() => props.markSelectedhandler(props.contact.userId)}>
`
Posting this here just in case someone else faces this issue, I get that context is different(wordpress in current thread) but error message is exactly same so if any one comes across this while googling they may find this helpful.

**Comment by romelgomez** [comment]
I have similar error, different project, an workaround that I finded is call setState into a setTimeout function

```
setTimeout(() => {
  setState(newState);
})
```

**error:** 

```
index.js:1 Warning: Cannot update a component (`Orders`) while rendering a different component (`Unknown`). To locate the bad setState() call inside `Unknown`, follow the stack trace as described in https://fb.me/setstate-in-render
```

ref: https://github.com/facebook/react/issues/18178#issuecomment-602327720

**Comment by cristhianLaurente** [comment]
@mayanktiwaridotcom estuve probando con tu ejemplo pero lo que hace no es renderizar el componente sino hasta darle el onClick.
en mi caso quiero que se renderize junto con el otro componente y ahi es donde vota el error, pude solucionarlo con el setTimeout pero no creo que sea eficiente, al leer  a los demás.

seguire investigando sobre este error.

**Comment by mo-taufiq** [comment]
**test**
### jsakljfkla
_fajkf_
`lklklsaf`
> ksjflksaj
[jskfjs](url)
@kafjkaj
- [ ] fkasf
#ksajfjks

**Comment by ssminspiration** [comment]
I had also met this errors when using useReducer hook in a component, I deliver the dispatch function to the child component, then I called the dispatch to change the status of ancestor's,then the erros occured. I am confused and don't how to fix the errors.

**Comment by youknowriad** [comment]
So I've been battling with this and e2e test issues and I have a better understand understanding of the problems we have:

In WordPress Data, running selectors does this now (pseudo code)

```js
resolveSelector(args) {
  if ( resolverHasBeenAlreadyTriggeredForArgs(args) ) {
     return;
  }
  
  markSelectorAsTriggeredForArgs(args);
  runResolverForArgs(args)
}

runSelector( args ) {
  resolveSelector( args );
  return getSelectorValue( args );
}
```

Notice that above both `markSelectorAsTriggeredForArgs` and `runResolverForArgs` trigger changes on the global state which means components get rerendered (while we're already rendering them aka calling selectors).

A naive fix is to:

```js
resolveSelector(args) {
  if ( resolverHasBeenAlreadyTriggeredForArgs(args) ) {
     return;
  }
  
  delay( () => {
    markSelectorAsTriggeredForArgs(args);
    runResolverForArgs(args)
  } );
}
```

so now the resolution is delayed and the React warning is gone but there's another issue here. It is possible that resolvers get called multiple times unnecessarily. This happens because when `resolveSelector` is  called the first time, the flag to mark the resolver as already triggered is only updated inside the "delay" which means potentially, the resolver runs multiple times (and we have this in our end2end tests).

So for me, the solution requires making the "resolution state" independent from the "rendering state" in order to be able to do this without triggering warnings

```js
resolveSelector(args) {
  if ( resolverHasBeenAlreadyTriggeredForArgs(args) ) {
     return;
  }
  // This is synchronous now.
  markSelectorAsTriggeredForArgs(args);
  
  delay( () => {
    runResolverForArgs(args)
  } );
}
```

But there's another issue, several components rely on these resolution selectors to show spinners etc... which makes me think, maybe we need "two resolutions states", one internal to the registry and one to be used in components so we'd end up with something like:

```js
resolveSelector(args) {
  if ( resolverHasBeenAlreadyTriggeredForArgs(args) ) {
     return;
  }
  // This is synchronous now.
  markSelectorAsTriggeredForArgs(args);
  
  delay( () => {
    markSelectorAsTriggeredForArgsInState(args);
    runResolverForArgs(args)
  } );
}
```

Anyway, this is starting to get complex and I appreciate toughts and ideas here. cc @nerrad @epiqueras

**Comment by epiqueras** [comment]
Yeah, that's basically what I said above:

>This specific issue is flaring up because of selectors synchronously triggering resolvers, which in turn synchronously trigger store subscriptions. I think that it makes a lot of sense for resolvers to trigger asynchronously. I pushed that to #21289, and the warning is gone.

**Comment by youknowriad** [comment]
But it's not as easy as making the resolvers async, the hasStarted thing need to be sync.

**Comment by epiqueras** [comment]
I did that too.

**Comment by youknowriad** [comment]
@epiqueras where can I see that? In the PR, it was all wrapped in setTimetout including the "startResolution" call.

**Comment by epiqueras** [comment]
https://github.com/WordPress/gutenberg/pull/21289/commits/de352f714e456851e502d4523afc9a38292afd37

**Comment by epiqueras** [comment]
There's a local variable that updates synchronously to avoid duplicate calls.

**Comment by youknowriad** [comment]
But that local variable doesn't depend on "args" which means it's going to create issues where potential resolvers won't run at all?

**Comment by epiqueras** [comment]
Yes, I guess it needs to be a map that uses args.
