### ISSUE TITLE
"Update Design" checkboxes don't render properly in site editing

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#21168]
Are not loading relevant styles for when they are toggled.

![image](https://user-images.githubusercontent.com/548849/77640788-43e4da00-6f5b-11ea-9037-685d06d68424.png)

**Comment by skorasaurus** [comment]
Here's a very detailed report of this written by @JustinyAhin
Describe the bug
In Site Editor (beta) page, after editing the site, and clicking on the "Update Design" button, it is impossible to check on of the checkboxes of templates or templates parts in order to save the changes made.

To reproduce
Steps to reproduce the behavior:
On a fresh WordPress install,

    Install and activate the Gutenberg Plugin
    Go to Gutenberg > Experiments, and enable "Full site editing" and "Full site editing demo templates" option.
    Go to Gutenberg > Site Editor (beta) and made some changes to the site in the block editor.
    Click on "Update Design" button and try to check one of the checkboxes.

Expected behavior
We should be able to select one of the checkboxes (Template: Front Page and Template Part: Header) to save them.

Screencast
https://res.cloudinary.com/segbedji/video/upload/v1585841865/Gutenberg/Site_Editor_beta_Gutenberg_WordPress_-_Firefox_Developer_Edition_02_04_2020_16_30_28_v4whxh.mp4

Desktop

    OS: Windows 10 Professional 1803
    Browser: Firefox Developer Edition
    Version: 75.0b11

Additional context

    WordPress 5.4
    Gutenberg 7.8.1

**Comment by mtias** [comment]
@skorasaurus this was fixed in #21159, so it'll be part of the next release.
