### ISSUE TITLE
Arrow navigation broken in Firefox

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#2124]
To reproduce, create e.g. two paragraphs in Firefox and try to use the arrow keys to move the caret from one to another. Normally this should work. In Firefox it does not. The selection API probably behaves a bit different there, though I'm pretty sure it used to work.

**Comment by iseulde** [comment]
Related: #2222. Also related: pressing arrow twice in empty editable. Looking for an alternative solution that may give a better experience too.

**Comment by tg-ephox** [comment]
@iseulde are you also looking at #2222? I plan to look at this next if not.
Also @EphoxJames is working on #2392 will this issue overlap with that?

**Comment by tg-ephox** [comment]
@iseulde part of the problem with this issue is around links. When you left or right arrow through the TinyMCE editor, as it gets to a link the cursor position stays the same when it changes the style to display the link.  That causes this code to assume the beginning or end of the block has been reached: https://github.com/WordPress/gutenberg/blob/595efd81005645e5622c5e0628a221081f6cbaf0/editor/modes/visual-editor/block.js#L294

A different approach to handling this would be required though.  Maybe a custom event or a callback prop on the block to say when the end of editor has been reached?

**Comment by iseulde** [comment]
@tg-ephox Yeah I know. There's PRs such as #2431.

**Comment by iseulde** [comment]
I should have linked to the issues.

**Comment by youknowriad** [comment]
should be fixed by #2424
