### ISSUE TITLE
Block Styles: edit() calls for each style which slow the rendering of block

### ISSUE THREAD

**Issue by maheshwaghmare** [WordPress/gutenberg#21265]
I have search about this issue before creating this one but not found something related issue.

If someone found it then don't hesitate to close this one.

Okay, I have created a sample Gutenberg blog with 5 styles.

**Test 1: Adding Block First Time into the Editor**

When I add block first time into the Block editor then it call the `edit()` function 6 times.

Here, First call is initial call and remaining 5 calls are due to block styles.

**Test 2: Change style from Inspector**

If I change the style from inspector then it again call 6 times.

Please check the [testing video](https://www.dropbox.com/s/xdrd47pstuynd4g/bFXRV8vtYa.mp4?dl=0)

**Code Snippet**

```js
/**
 * BLOCK: Test
 *
 * Registering a basic block with Gutenberg.
 * Simple block, renders and saves the same content without any interactivity.
 */

const { __ } = wp.i18n;
const { registerBlockType } = wp.blocks;

registerBlockType( 'cgb/test', {
	title: __( 'Test' ),
	icon: 'shield',
	category: 'common',

	// Register block styles.
	styles: [
	    {
	        name: 'test-style-1',
	        label: __( 'Style 1' ),
	        isDefault: true
	    },
	    {
	        name: 'test-style-2',
	        label: __( 'Style 2' ),
	    },
	    {
	        name: 'test-style-3',
	        label: __( 'Style 3' )
	    },
	    {
	        name: 'test-style-4',
	        label: __( 'Style 4' )
	    },
	    {
	        name: 'test-style-5',
	        label: __( 'Style 5' )
	    }
	],

	edit: ( props ) => {
		const { className } = props;

		console.log( className );

		return (
			<div>Hello World</div>
		);
	},

	save: ( props ) => {
		return (
			<div>Hello World</div>
		);
	},
} );
```

I have try some other tests and found that:

1) If I add 10 styles then it call 10 times.
2) If I add `<RichText>` component type something then for each keyup event the `edit()` function calls 10 times due to 10 styles.

See [another testing video](https://www.dropbox.com/s/82c63ec6zn5g3r3/dWmPa8pCj5.mp4?dl=0) which demonstrate how the edit function call multiple times while typing into the `<RichText>` component.

**Expected behavior**
It should be call at once when we click on any style.

**Screenshots**
[Testing Video](https://www.dropbox.com/s/xdrd47pstuynd4g/bFXRV8vtYa.mp4?dl=0)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Chrome Version 80.0.3987.149 (Official Build) (64-bit)]
 - Version [Gutenberg Version 7.8.1]

**Comment by youknowriad** [comment]
Hi There! 

It is true that `edit` function is called for each style variation but that's also expected, since that's what allows to render the preview of the style.

We do need to work on the rendering performance of the editor in general but we can't stop calling "edit" on block previews.

I'm thinking we should close this preview issue though.

**Comment by vicolaspetru** [comment]
I have the same issue, and I think if I have set `example` attributes for style preview,  then in this case the block `edit()` doesn't need to be re-rendered for each style variation because the values in preview doesn't change! You have to initialize only once and then skip the render from style variation.

Is it possible to do what I wrote above or how can we fix this at the moment? Because I have a block with multiple `ChildComponent` and when I try to typing something in `RichText` component, the block freezes for a few seconds and this makes a very bad efficiency for users 😔

**Comment by noisysocks** [comment]
Closing per https://github.com/WordPress/gutenberg/issues/21265#issuecomment-607171354. Let's focus on https://github.com/WordPress/gutenberg/issues/24210 which identified a potentially related performance issue.
