### ISSUE TITLE
Block API: Choose a Block-Style for a Block Variation

### ISSUE THREAD

**Issue by goaround** [WordPress/gutenberg#21292]
**Is your feature request related to a problem? Please describe.**
I would like to choose a different style for my variations. With the current API the that is not possible.

**Describe the solution you'd like**
A parameter like `style: 'fancy'` would be awesome: https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/block-api/block-registration.md#variations-optional

**Comment by gziolo** [comment]
You can do it by setting explicitly className attribute to the class name that the given style uses in the produced content. I’m aware that it isn’t the best way to achieve it so I agree that we should find a better way. I think  your proposal sounds reasonable. We properly should use the name styleVariation to distinguish it from the style you define on the server for the block.

**Comment by gziolo** [comment]
@mcsf or @youknowriad any thoughts on this proposal?

**Comment by youknowriad** [comment]
Personally, I feel using the className is a very reasonable way of doing this.

**Comment by mcsf** [comment]
I think using className is acceptable too, mainly for two reasons:
* Style variations are already an arguably low-level API, since they are just a wrapper for custom classes. For something more robust, proper Variations may be a better choice.
* With the planned work in Global Styles, I'd rather not overload the term (and property name) `style`, since that may soon come to mean much more than just custom classes.

**Comment by goaround** [comment]
@gziolo the `className` attribute works for me. Thanks for pointing it out to me. Properly it would be good to add this to the documentation?

**Comment by gziolo** [comment]
I opened #21927 where I added an example. I hope it will help other folks 👍
