### ISSUE TITLE
Revise toolbar items for Nav block on Navigation Menu page

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#21310]
**Description**
#19170 created an experimental page for using the nav block to created existing WordPress menus.

In the context of this page, the Nav Block's toolbar contains several items that are irrelevant:
- Alignment
- Block Navigator
- Colors
- An empty Block More Menu

<img width="490" alt="Screenshot 2020-04-01 at 2 59 17 pm" src="https://user-images.githubusercontent.com/677833/78108234-8f9af600-7429-11ea-9116-49667a5c6c7b.png">

**Comment by marceloaof** [comment]
Are there talks about bringing the entire nav-menus.php structure to inside Gutenberg editors, extending it with APIs to plugins from there?
Threads about removing or limiting features in WP, at this point, normally reveal problems about Gutenberg scope that I believe is part of the case here: see, the current scenario allows the Menus page to handle menus that are going to be used, if not in plugins, also inside Gutenberg editor and full-site-editing. That approach wasn't feasible when Gutenberg was Classic Editor. The current approach isn't the best anymore, because now there is exactly that, more: the possibility for the user to also edit its colors, alignments of menu items... Isn't it better handling menus as a single interface than to spread its features, dividing the process into navmenu page, templates, many pages..? If I proposed to create an "Images.php" page to set its height, width, border-radius before being inserted an image on editor or plugins, and spare these settings from happening there on Gutenberg, everyone would notice how unconvenient this Idea is. The same applies here... how much easier for devs to maintain the code and better for users if the entire nav-menus.php features were inside the editor, maybe on the Block sidebar, or as a popup.

I believe these toolbar items are not irrelevant in nav-menus.php, even on the current scenario, because we can set them as global definitions of sort for nav-menus from there.
But I would be okay if you remove them...

**Comment by adamziel** [comment]
Related: https://github.com/WordPress/gutenberg/pull/22792

**Comment by draganescu** [comment]
#23021 closed this
