### ISSUE TITLE
Facebook embed block does not embed profile page.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#21437]
**Describe the bug**
I tested out the Facebook Embed block.

![Screen Shot 2020-04-06 at 23 14 50](https://user-images.githubusercontent.com/5323259/78605754-6ed50500-785c-11ea-8eef-cc6fcd5e51e6.png)

Added my own page, and received the below message.

![Screen Shot 2020-04-06 at 23 10 14](https://user-images.githubusercontent.com/5323259/78605797-7e544e00-785c-11ea-8b38-437a1da3d168.png)

**Expected behavior**
I expected to be able to embed something from my own Facebook page.

Test. Using.
Twenty Twenty theme.
Gutenberg plugin 7.8.1.
Desktop Server. Local site using Chrome.

**Comment by JoshuaGoode** [comment]
@paaljoachim Currently, Facebook embeds in WordPress core do not support profiles so this is expected behavior

Here's a list of what the embed shortcode and block currently support: https://wordpress.org/support/article/embeds/#okay-so-what-sites-can-i-embed-from

To review, that's the following:

> post, activity, photo, video, media, question, note

You can embed any of those items using the shortcode or block but not your profile.

An example of a post link that you can embed would be `https://www.facebook.com/WordPress/posts/10157988246567911`

**Comment by paaljoachim** [comment]
Thanks for the feedback @JoshuaGoode 

It seems the option here is to either close this issue or open a trac issue to extend the Facebook Embed to include profiles. Or perhaps this would be something to get fixed in Gutenberg?

**Comment by talldan** [comment]
I think this would be a core ticket @paaljoachim. Worth searching trac to see if there's already something created.
