### ISSUE TITLE
Improve Block Navigation Menu

### ISSUE THREAD

**Issue by BinaryMoon** [WordPress/gutenberg#21452]
I think the block navigation could be a really handy tool but currently I find it hard to use. On long pages there's no way to differentiate different sections.

What I would like to suggest is changing the text that appears in the dropdown - mostly the headings, but possibly for other blocks as well. 

Changing the _heading_ text so it's the actual text from the heading would add waypoints making it clearer where you will end up. You could also use _Image_ or _Gallery_ captions.

The text could be cropped so it still fits on one line. It just has to give an indication of the content, it doesn't have to be the full content.

Here's an image showing what I mean:

![Block Navigator](https://user-images.githubusercontent.com/1004130/78657738-2439a400-78c1-11ea-829a-e7adde5f45fd.png)

**Comment by richtabor** [comment]
Second this; great idea 💪

**Comment by pablohoneyhoney** [comment]
Nice! Very relevant thought as we keep evolving each one of the pieces. Being more specific and contextual would help parse the content and navigate to it.

**Comment by karmatosed** [comment]
Love this, it's a great iteration. I adore the block navigator interface, so any opportunity to make that more useful for me should be taken. Thanks for this suggestion @BinaryMoon. Let's move this right into needs dev, as for me it's a great iteration.

**Comment by johnwatkins0** [comment]
It looks like #19664 is making related updates.

**Comment by BinaryMoon** [comment]
Not sure it does. That ticket seems to be about the navigation block, not the block navigation. Unless I misunderstood/ missed something?

**Comment by johnwatkins0** [comment]
Sorry, I should've gone into detail. I was looking into working on this earlier, but then I saw #19664 (which touches both the navigation block and block navigation). In the current `master` branch there's an `__experimentalLabel` block option that gets passed into block navigation to render the text that shows. It actually works beautifully for what's needed here -- e.g., displaying the first 30 characters of heading text instead of "Heading" -- but #19664 removes `__experimentalLabel` and introduces a new way in to customized text in the navigator. So I think it's probably worth waiting for that PR to land before working on this.

**Comment by BinaryMoon** [comment]
Ah ha - got you. Thanks for explaining :)

**Comment by jordesign** [comment]
As there's been no further discussion on this, and the List view has matured significantly since 2020 - I'm going to close this issue.

If there _are_ further UX suggestions - please open a new issue with screenshots relevant to the current state.
