### ISSUE TITLE
Block Transforms: Refine visuals

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#21478]
This is what the block transform looks like currently:

<img width="837" alt="Screenshot 2020-04-08 at 11 12 54" src="https://user-images.githubusercontent.com/1204802/78766768-f9675280-7989-11ea-890f-9e4bbe8d4287.png">

This is what it's mocked up to be as part of #18667:

<img src="https://user-images.githubusercontent.com/548849/69342494-f8988300-0c6b-11ea-8c53-ddae75cc76d1.png">

Let's explore how to get them closer.

- [ ] Dark border & zero elevation prop for the popover
- [ ] More consistent colors and typography
- [ ] Better spacing and sizing of icons inside

Here's an additional sketch for transforms:

<img width="1272" alt="Screenshot 2020-04-08 at 11 15 31" src="https://user-images.githubusercontent.com/1204802/78766993-4fd49100-798a-11ea-93ba-3ba6df9f58b5.png">

**Comment by karmatosed** [comment]
I love the reduction here to a simple drop-down. Whilst the block library is useful, I don't believe it's something to be used as a pattern anywhere there is a block interaction, so removing it here to offer an easier to read list is an improvement.

I do have a little ponder about the disconnection of the menus, particularly on the 3rd level, that feels awfully far. I think though this could be because I am not experiencing this, so getting into a PR makes sense to feel what the interaction is like.

**Comment by mapk** [comment]
Creating a list instead of grid view of these for the Transform tool feels like a great improvement. Most everything coming from the block toolbar is a list already, so this fits well. 👍

**Comment by jasmussen** [comment]
This is improved:

<img width="610" alt="Screenshot 2020-10-23 at 10 28 30" src="https://user-images.githubusercontent.com/1204802/96975251-833bcf00-151a-11eb-81c4-c1b2d975335e.png">

It's not perfect, but we can open initial actionable items if need be.
