### ISSUE TITLE
Button Update Doesn't Make Centering and Moving of Block Obvious/Intuitive

### ISSUE THREAD

**Issue by NewYorkerLaura** [WordPress/gutenberg#21509]
Hi All,

I love Gutenberg! I create content in it every day for upwards of 30 unique sites.

The button update:

LOVE that I can do side-by-side

HATE that it's not UX friendly in terms of innate functionality being obvious and present (moving up and down/centering) when you click the plus button. See  [short video]([url](https://trainingvideoslaura.s3.amazonaws.com/zoom_0.mp4)) of me replicating multiple frustrated clients who asked for help this week and ME (been using WordPress since 2006) who took three days to figure out what was going on!

https://trainingvideoslaura.s3.amazonaws.com/zoom_0.mp4

**Comment by 0aveRyan** [comment]
I've reviewed the video above and will try to summarize the report so it can be actionable.

With the **Buttons Block** added in #17352, **Block Alignments** and the **Block Mover** are now in the parent block and the experience to users is those options have disappeared or grayed-out. 

For users accustomed to inserting `Button Blocks` (singular), it's extremely easy to miss that the single button is an inner block in a `Buttons Block` (plural) and wonder where those controls went -- this is a notable large UX departure for regular users of the legacy Button Block. There are only two visual cues that communicate this departure that are easy to miss: 

1) the `s` in Buttons upon insertion 
2) the block breadcrumbs in the bottom toolbar.

**I realize this parent-and-inner block relationship is a design problem that's been iterated on a few times and is by no means a simple problem.** That said, with full-site editing on the horizon with many nested relationships, I think it's worth revisiting the problem to see what else can be done to communicate hierarchies to users for Buttons/Button, Columns/Column and some of the other blocks with UX challenge.

None of these are the one magic solution, but a few ideas that aren't block borders...

### Emphasize selection relationship in Block Breadcrumbs
<img width="240" alt="Screen Shot 2020-04-09 at 6 18 16 PM" src="https://user-images.githubusercontent.com/9565066/78954108-eb9bf500-7a8f-11ea-9308-ed82c804d032.png">

### Use Block Sidebar to emphasize relationship (low-fidelity mocks)
<img width="282" alt="Screen Shot 2020-04-09 at 6 25 15 PM" src="https://user-images.githubusercontent.com/9565066/78954184-24d46500-7a90-11ea-9210-994f4cb095c1.png">

<img width="282" alt="Screen Shot 2020-04-09 at 5 58 18 PM" src="https://user-images.githubusercontent.com/9565066/78954189-2bfb7300-7a90-11ea-80f8-e4b09181dc43.png">

### Add "Select Parent Block" to Block Menu on Inner Blocks (or some other way on the toolbar)
<img width="534" alt="Screen Shot 2020-04-09 at 6 09 28 PM" src="https://user-images.githubusercontent.com/9565066/78954226-49304180-7a90-11ea-9c6d-997317336fb6.png">

### Provide inverse plus icon treatment for inner blocks so plus icons in inner blocks are more clearly distinct (unmocked below, but perhaps outline instead of fill treatment)
<img width="654" alt="Screen Shot 2020-04-09 at 6 15 07 PM" src="https://user-images.githubusercontent.com/9565066/78954326-a7f5bb00-7a90-11ea-886e-2dde3cd3bbcc.png">

### Highlight Block Navigation whenever Inner Blocks are Selected
<img width="254" alt="Screen Shot 2020-04-09 at 6 36 06 PM" src="https://user-images.githubusercontent.com/9565066/78954448-1b97c800-7a91-11ea-9661-ee339529a588.png">

**Comment by paaljoachim** [comment]
@NewYorkerLaura We do not have access to the video. Could you make it so we can access it again?

@0aveRyan Thanks for the feedback! 
This is something we need to look closer at.

**Comment by NewYorkerLaura** [comment]
Looks like the video got deleted when I was doing some cleanup in my AWS buckets. Here's a new link https://trainingvideoslaura.s3.amazonaws.com/button+issue.mp4

**Comment by paaljoachim** [comment]
Hey Laura. Can you also edit your initial post with the correct link? That would be helpful. Thanks.

**Comment by paaljoachim** [comment]
Changes have happened since this issue was created. An example is that we now have a parent icon show up to the left of the Block toolbar when there are inner blocks present. This is what it now looks like for the Buttons block.

![Screen Shot 2021-04-06 at 18 46 23](https://user-images.githubusercontent.com/5323259/113748255-8dd4d400-9708-11eb-91a3-bd0c0987cc4d.png)

Clicking the left icon brings one up to the parent - Buttons block.

https://user-images.githubusercontent.com/5323259/113748504-dc826e00-9708-11eb-888c-ed4e2dd3de60.mp4

I do believe that the various issues might have been taken care of. I will go ahead and close this issue. I can always reopen if I made a mistake. But any additional actionable item could perhaps be made into a new issue. Thanks.
