### ISSUE TITLE
Media File link configuration option does not work for external images

### ISSUE THREAD

**Issue by tharglet** [WordPress/gutenberg#21518]
**Describe the bug**
When I add a external image in an image block, the "Media File" button does not work when trying to make it into a link

**To reproduce**
1. Create a new post in Wordpress 5.4
2. Insert an image block
3. Click "Insert from URL"
4. Insert a valid URL for an image (e.g. one on Imgur)
5. Click the "Insert link" button
6. Click "Media File"

**Expected behavior**
The image becomes a link to the media file inserted in step 4. Instead, nothing happens

**Desktop (please complete the following information):**
 - OS: Windwos 10
 - Browser Chrome
 - Version 80.0.3987.163

**Additional context**
- Please add the version of Gutenberg you are using in the description.
Unsure of how to find this. Using WP5.4 with no editor plugins.

Images inserted from upload or the gallery**Describe the bug**
When I add a external image in an image block, the "Media File" button does not work when trying to make it into a link

**To reproduce**
1. Create a new post in Wordpress 5.4
2. Insert an image block
3. Click "Insert from URL"
4. Insert a valid URL for an image (e.g. one on Imgur)
5. Click the "Insert link" button
6. Click "Media File"

**Expected behavior**
The image becomes a link to the media file inserted in step 4. Instead, nothing happens

**Desktop (please complete the following information):**
 - OS: Windwos 10
 - Browser Chrome
 - Version 80.0.3987.163

**Additional context**
- Please add the version of Gutenberg you are using in the description.
Unsure of how to find this. Using WP5.4 with no editor plugins.

The Media File button works correctly with images inserted from the gallery or as an upload.

**Comment by johngodley** [comment]
Confirmed that trying to set the link on an externally hosted image to either 'media page' or 'attachment page' doesn't set the link or close the popup. Tested in master.

![image](https://user-images.githubusercontent.com/1277682/79339313-9abd4e00-7f20-11ea-8a86-c69c572cca0d.png)

The problem seems to be caused by this code:

https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/image/edit.js#L376

The URL for externally hosted images is stored in `url`, not `href`.

Additionally I don't think it makes sense to have the attachment page as an option.

**Comment by kirilzh** [comment]
I see that this bug only exists when adding an image from URL. Uploading a local file works as expected.
