### ISSUE TITLE
Rename "gutenberg" link to "edit in gutenberg" or ·edit in new editor"

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#2159]
We have a link under posts in the table list view that just says "Gutenberg" and links to edit a post in gutenberg. We should clarify the action with a verb: "Edit in ..." which could be "in Gutenberg" or "in new editor" if we want to avoid the code name.

(mentioned by @helen)

**Comment by karmatosed** [comment]
I would say where we can phasing out the codename is good. This feels like a good step towards that.

**Comment by nylen** [comment]
"Edit in Block Editor"

**Comment by helen** [comment]
At this moment I think it'd be best if the link was descriptive about the intention of the new editor rather than a description of it, if that makes sense. So "new editor", "experimental editor", "beta editor" or something like that rather than "block editor". Longer strings are harder to fit in some places but I think it's worth providing more guidance to get the best possible testing and feedback.

**Comment by westonruter** [comment]
See also PR #1797

**Comment by aduth** [comment]
This is largely satisfied by #1797. We should start thinking about how Gutenberg becomes the default editor, but this should be created as a separate issue.
