### ISSUE TITLE
eslint-config 5.0.0: Error: Failed to load plugin '@wordpress/eslint-plugin' declared in '.eslintrc.js': Cannot find module '../utils'

### ISSUE THREAD

**Issue by curtisbelt** [WordPress/gutenberg#21610]
**Describe the bug**

When running eslint, an error occurs:

```
Error: Failed to load plugin '@wordpress/eslint-plugin' declared in '.eslintrc.js': Cannot find module '../utils'
```

Submitted PR: https://github.com/WordPress/gutenberg/pull/21609

**Comment by aduth** [comment]
Introduced by: #20574

Last week, I started a local branch to add type-checking to this package, and one of the first things I did (based on discussion from https://github.com/WordPress/gutenberg/pull/18942#issuecomment-601772189) was to move these files into a `lib/` directory. I think this convention in packages could help to avoid these sorts of errors in the future, since if the entry within `files` was simply `lib`, it could support the addition of new folders without additional changes necessary.

**Comment by gziolo** [comment]
The new version `5.0.1` of the package with the bug fix is out on npm.
