### ISSUE TITLE
In the new Navigation screen LinkControl does not show suggestions 

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#21620]
**Describe the bug**
Here is a screen recording:

![no-suggest](https://user-images.githubusercontent.com/107534/79365791-c6a5f700-7f53-11ea-9f70-abee5d1f8fff.gif)

**Expected behavior**
I expected the same behavior that the block has in posts:

![with-suggest](https://user-images.githubusercontent.com/107534/79365785-c4439d00-7f53-11ea-98f9-59697435c752.gif)

**Comment by getdave** [comment]
It's probably that you're missing the `@wordpress/editor` package which is where the data comes from to populate that list

https://github.com/WordPress/gutenberg/blob/cc0fddac19834c9e1674cb496e2301802ec32de0/packages/editor/src/components/provider/index.js#L32-L47

**Comment by talldan** [comment]
I think this is due to the endpoint for fetching the suggestions being part of the editor settings:
https://github.com/WordPress/gutenberg/blob/c6fb7f9247abcf95e282b9f8ef652a47558a838a/packages/block-editor/src/components/url-input/index.js#L528-L532

It's possibly not specified as part of the settings in the navigation menu page?

**Comment by adamziel** [comment]
I proposed a solution in https://github.com/WordPress/gutenberg/pull/21873
