### ISSUE TITLE
Consider what revisions could look like

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2165]
Revisions currently still uses the same interface as the existing editor. Whilst out of scope for v1, I think it's worth having as an issue for design ideas on this. What could be done to improve revisions and make them work better inside Gutenberg? Has anyone got some ideas/designs for this?

**Comment by jwold** [comment]
A couple of questions:

1. Do we know what value the current revision interface offers? I was just playing with it some more and realized that I've never used the "compare any two revisions" option. 
2. In looking at Medium.com, their revision history is incredibly simple. Click a button, see a dropdown, choose the revision you want to restore. When you're on that revision you can cancel or restore that revision. I find that incredibly useful for many use cases. 

--

So bottom line, the revision history option we have in WordPress today is great. It gets the job done and allows for tons of flexibility. Do we need all that though? 

Also, the current interface doesn't really "show" me what I'm looking at, it just displays html text and code. Not super helpful. Medium on the other hand takes me to a frontend view of that revision (which helps since the editing experience and frontend look are the same) and asks if I want to keep or reject it.

**Comment by karmatosed** [comment]
As the project has grown, we are just focusing on the flow and making revisions fit. I'm going to close this as whilst revisions does need attention, it's not within the spec of Gutenberg.
