### ISSUE TITLE
Consider select state with background color change on toolbars

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#21814]
The current implementation of select state on inner toolbars, for example with bold styling, is to have a background color:

![image](https://user-images.githubusercontent.com/253067/80084226-81cf2100-854e-11ea-9c24-fa714717ae65.png)

I think bringing this also into the block top toolbar makes sense:

<img width="806" alt="1" src="https://user-images.githubusercontent.com/253067/80084269-8e537980-854e-11ea-877b-cd4725eb9e05.png">

This was a point in discussion with @jasmussen in #21727 and I said there I'd create this issue. I'd be keen to discuss if this makes sense for people as a toolbar selected state, no matter where the toolbar is within the block.

**Comment by jasmussen** [comment]
Thanks for the ticket. Let me just be sure I understand things right because there may be nuance I missed.

There's a toggled state, and there's a "dropdown is open" state. In the case of the line tools with bold and italic, you select something, make it bold, and so long as the caret is in bold text, you see the bold button _toggled_ -- which is dark and inverted.

In the example you show the alignments is highlighted/toggled -- was it meant to indicate that this menu is also "open"? Because if yes, then I'd ambiguate between those two. See the following:

<img width="1233" alt="Screenshot 2020-04-23 at 12 33 59" src="https://user-images.githubusercontent.com/1204802/80089816-c793e580-855e-11ea-9805-4779a492e534.png">

In this case, the Wide alignment is chosen for the cover block, and is correctly shown as toggled (dark, inverted). The dropdown is also shown as _opened_, which at the moment is indicated with a blue icon color. This color change is a little subtle, so the thought I had was whether there were different treatments to showing this menu as being open. 

One option is to not change the blue color at all and just rely on what has focus and geographic spacing to indicate where you are. But I'd avoid mixing in the dark/inverted "toggled" state with "dropdown is open" state.

**Comment by karmatosed** [comment]
> One option is to not change the blue color at all and just rely on what has focus and geographic spacing to indicate where you are. But I'd avoid mixing in the dark/inverted "toggled" state with "dropdown is open" state.

I sort of was thinking of the 'something is set' being an indicator. A balance might yes then be to not change the blue color and rely on focus. I feel that clears up some confusion.

**Comment by mapk** [comment]
I'm still trying to understand the various design decisions in G2, so I'm glad this was surfaced. Thanks for the discussion. It looks like it was intentional, and appears to work well in multiple places, so I'll close this one out.
