### ISSUE TITLE
I can't add any blocks to my posts

### ISSUE THREAD

**Issue by muhammedaltin** [WordPress/gutenberg#21865]
Hey there,

Even I use latest version of Gutenberg, I can't add any blocks.  Any advice please?

Here is the ss:
https://prnt.sc/s57nth

thank

**Comment by karmatosed** [comment]
Hi there, that sounds like a not great experience for you let's see how we can dive into what the issue is. It looks like you might be using a custom plugin or theme. My only thought initially is that might be causing some issues. As there are no other reports of this using a default theme like Twenty Twenty, would you be able to try that as a starting point?

**Comment by karmatosed** [comment]
As there is no more information, for now closing this. It can always be reopened once more details are provided.
