### ISSUE TITLE
Docs: Cannot update meta field value in the updated metabox tutorial.

### ISSUE THREAD

**Issue by atachibana** [WordPress/gutenberg#21901]
**Describe the bug**
In #21155, @jorgefilipecosta updated the metabox tutorial so that it will use `useEntityProp` instead of attributes. Certainly, the tutorial runs successfully and set new meta value as 'myguten_meta_block_field', but we can't update the value once it is saved.

**To reproduce**
1. $ npm init @wordpress/block meta-box
2. $ cd meta-box
3. Insert the contents of `myguten-meta-block.php` in [Step 2](https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/tutorials/metabox/meta-block-2-register-meta.md).
4. Replace the contents of `src/index.js` by ESNext contents in [Step 3](https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/tutorials/metabox/meta-block-3-add.md)
5. $ npm runs start
6. Create New Post
7. Insert Meta Block from common blorks
8. Type 'Hello' and Publish
9. Modify it 'Hello 2' and Update. Still field is 'Hello 2'
10. Reload browser. You'll see 'Hello'.

**Expected behavior**
Modified value should be saved and displayed.

**Editor version (please complete the following information):**
- WordPress version: 5.4
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Tested both. 5.4 block editor and Gutenberg Plugin 7.9.1
- If the Gutenberg plugin is installed, which version is it? 7.9.1

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Version 81.0.4044.113

**Comment by jorgefilipecosta** [comment]
Hi @atachibana,

 I followed the steps described and I was not able to reproduce the issue. The meta value updates as expected and the new value appears after each reload:
![Apr-30-2020 18-32-22](https://user-images.githubusercontent.com/11271197/80741158-19b1a980-8b11-11ea-91ac-f1e2ecb25fc9.gif)
Do you have any plugin or theme installed that may interact with the editor/meta values and impact this behavior?

**Comment by atachibana** [comment]
@jorgefilipecosta 
Sorry for your time and effort. I refreshed my environment and above issue was disappeared, though I should keep old environment to investigate deeply what caused above issue...
I close this issue. I'm very sorry.

**Comment by atachibana** [comment]
@jorgefilipecosta
I think I found the root cause. My old environment was @wordpress/scripts 8.0.1, and now it is 9.0.0.

**Comment by jorgefilipecosta** [comment]
Hi @atachibana thank you for confirming the issue was fixed 👍

**Comment by ecolink** [comment]
I have a similar problem，The same problem was encountered after refreshing the browser twice ! :{

**Steps to reproduce the behavior:**

1. $ npm init @wordpress/block meta-box
2. $ cd meta-box
3. Insert the contents of myguten-meta-block.php in Step 2.
4. Replace the contents of src/index.js by ESNext contents in Step 3
5. $ npm runs start
6. Create New Post
7. Insert Meta Block from common blorks
8. Type 'Hello' and Publish
9. Modify it 'Hello 2' and Update. Still field is 'Hello 2'
10. Reload browser. You'll see 'Hello 2'.
11. **Reload the browser again , Modify it 'Hello 22' and Update.Still field is 'Hello 22' . But , Reload the browser again,You'll see 'Hello 2'.**

**Expected behavior**
Modified value should be saved and displayed.

Editor version (please complete the following information):

WordPress version: 5.4.2
wp-script: 12.0.0

OS: iOS
Browser chrome
Version 81.0.4044.113
