### ISSUE TITLE
__getExperimentalSettings timezone offset may be a string or integer

### ISSUE THREAD

**Issue by jeremyfelt** [WordPress/gutenberg#21977]
**Describe the bug**

The value provided by `wp.date.__getExperimentalSettings.timezone.offset` differs in type depending on the site's timezone setting.

* A timezone of `America/Los_Angeles` set through General Settings in the WordPress admin results in an integer offset value of `-7` (currently in DST).
* A timezone of `UTC-7` results in a string offset value of `"-7"`.
* A timezone of `UTC` results in an integer offset value of `0`.
* A timezone of `UTC+0` results in a string offset value of `"0"`.

If this data is passed directly to something like `moment().utcOffset()`, [which expects either an integer or a string](https://momentjscom.readthedocs.io/en/latest/moment/03-manipulating/09-utc-offset/) formatted like `"-07:00"`, then the returned object will not contain the expected offset information.

Any of these values can be passed through `Number()` or converted to minutes via `* 60`, which moment also understands, so I could see how this isn't necessarily a **bug** bug, but having this documented here may help someone else who started questioning the world a bit. :)

**Expected behavior**
In a perfect world, `wp.date.__getExperimentalSettings.timezone.offset` would always be an integer. In a more perfect world, computers would never think we mean "-7" when we type -7. 😀

_Edited March 25, 2021: I'm not sure how `__getExperimentalOffset()` got into my head, but this should all be `__getExperimentalSettings().timezone.offset`. I've edited the title and description to clarify._

**Comment by davilera** [comment]
I can confirm this issue and, as pointed out by @jeremyfelt, the value provided by `wp.date.__getExperimentalOffset.timezone.offset` should always be a number.

Tests in [`packages/date`](https://github.com/WordPress/gutenberg/blob/%40wordpress/date%403.9.0/packages/date/src/test/index.js) pass because the timezone is never a string (I know because I wrote them). I didn't realize that sometimes WordPress returned that as a string, so I failed to capture that behavior...

There's two options to fix this one:

1. Either we tweak [`setSettings`](https://github.com/WordPress/gutenberg/blob/%40wordpress/date%403.9.0/packages/date/src/index.js#L91) to make sure the this number is not a string (notice it doesn't have to be an integer; it can be a float such as `1.5`).
2. Or we [fix WordPress core](https://github.com/WordPress/WordPress/blob/5.4.1/wp-includes/script-loader.php#L356) itself so that it initializes this value correctly.

I personally think WordPress should always provide a consistent value (namely, a number and not a string). But, regardless of that, should we also add a safe guard in `wp.date`?

**Comment by ryelle** [comment]
I just ran into this when trying to figure out why a site shows different times when using "Vancouver" vs "UTC-7". I've pushed a PR that converts the offset to a number before using it in `buildMoment` https://github.com/WordPress/gutenberg/pull/25684 — it seemed safer to make the conversion at this point, in case other plugins are filtering that value, or the library is used outside of WordPress.

**Comment by ciampo** [comment]
cc @noisysocks as he's made some changes in #43005 related to this issue

**Comment by noisysocks** [comment]
In #43005 I updated the types to reflect reality, but agree it should always be a number.

> * Either we tweak [`setSettings`](https://github.com/WordPress/gutenberg/blob/%40wordpress/date%403.9.0/packages/date/src/index.js#L91) to make sure the this number is not a string (notice it doesn't have to be an integer; it can be a float such as `1.5`).
> * Or we [fix WordPress core](https://github.com/WordPress/WordPress/blob/5.4.1/wp-includes/script-loader.php#L356) itself so that it initializes this value correctly.

Doing both sounds good to me 🙂

**Comment by ciampo** [comment]
> Doing both sounds good to me 🙂

Sounds good to me too!

Has anyone involved in this conversation got any capacity to work on this? It looks like some work had already been started in https://github.com/WordPress/gutenberg/pull/25684 (which got approved, but never merged)

**Comment by noisysocks** [comment]
I fixed the call to `setSettings()` in Core in https://core.trac.wordpress.org/ticket/56459.

**Comment by Mamaduka** [comment]
@noisysocks, does this mean we can close #25684?

**Comment by noisysocks** [comment]
I think https://github.com/WordPress/gutenberg/pull/25684 addresses the first option in https://github.com/WordPress/gutenberg/issues/21977#issuecomment-639541141.

**Comment by jeremyfelt** [comment]
> * A timezone of America/Los_Angeles set through General Settings in the WordPress admin results in an integer offset value of -7 (currently in DST).
> * A timezone of UTC-7 results in a string offset value of "-7".
> * A timezone of UTC results in an integer offset value of 0.
> * A timezone of UTC+0 results in a string offset value of "0".

I've tested all of these with `wp.date.__experimentalGetSettings().timezone.offset` and (since 6.1) `wp.date.getSettings().timezone.offset` and everything looks good. Thanks!
