### ISSUE TITLE
Warning: Modified Externally & Locked! 

### ISSUE THREAD

**Issue by WPDevHQ** [WordPress/gutenberg#2197]
Not sure if this has been reported here yet - cross ref: https://wordpress.org/support/topic/block-content-warning-message/
![gutenberg gutenberg nore wordpress](https://user-images.githubusercontent.com/16872407/28934354-88b67f8a-7878-11e7-99d8-c404386e0171.png)

**Comment by nylen** [comment]
@WPDevHQ can you share the content of this post (the contents of the `Text` view?)

There should be more information about this warning in the browser console.  This is an area of the code that we are actively working on; right now it is set to be very aggressive about preserving content rather than potentially overwriting changes.

**Comment by WPDevHQ** [comment]
Sure, here's the raw data: https://gist.githubusercontent.com/WPDevHQ/8e98134e0cdd0bbcf982d63d2b302369/raw/0a89bd4bedb644f7c0b7b6777d5ac32953002662/gutenberg-locked-warning.md

Not seeing much in the console other than errors in parsing and Unknown pseudo classes

**Comment by nylen** [comment]
Thanks for the report.  We will look into it.

**Comment by mtias** [comment]
This should be much improved now.

**Comment by nonsalant** [comment]
I appear to be getting the same thing whenever I add an "Additional CSS Class" to a block (and then save and reopen via Gutenberg link).

For example:
```
<!-- wp:core/separator -->
<hr class="wp-block-separator separator-bottom" />
<!-- /wp:core/separator -->
```
Appears in the Visual editor as externally modified.

**Comment by Kuckovic** [comment]
I get this error whenever I add 2 images in the same block.
I have a "large-img" and "small-img" in my custommade block - when I save, it's all fine. But when I refresh - the "small-img" url has been replaces with the "large-img" - so that I have a duplicate.

And I get the error: "This block appears to have been modified externally. Overwrite the external changes or Convert to Classic Text to keep your changes."

It's ONLY my images!
All the text-fields are fine...

Frustrating!

**Comment by leo-ji** [comment]
I've been experiencing this issue as well, except for me it's paragraph blocks that always reopen as modified externally.

I've narrowed this down to <p> tags — I think Gutenberg uses <p> tags as part of the block validation process before the tags are stripped out by something else.

**Comment by mtias** [comment]
@leo-ji yes, the paragraphs is a known issue that happens whenever `removep` occurs on blocks through opening a post in the classic editor. We are working on a fix for it.

**Comment by ombion** [comment]
I want to love Gutenberg. This warning function forces me to do something I don't want to - convert to Block or Edit as HTML. Provide a Cancel option and let me go back to where I was - the original block I have. This is annoying. Remember, you don't want to make assumption and forces user to do thing a certain way.

**Comment by mtias** [comment]
The new version coming out next week should have improvements on this area!

**Comment by ombion** [comment]
I've updated the plugin with its latest release for my WP installation, and I'm still getting this same annoying warning message multiple times in multiple places. This has gotta be a bug because the same message also happens on those blocks where the code was not modified externally as the message warns. 
![error message](https://user-images.githubusercontent.com/8562849/42565298-e74b6d66-84b7-11e8-90ff-41335ea13cd9.png)

**Comment by aduth** [comment]
Hi @ombion , can you provide some information:

- The minimal repeatable steps necessary to produce a warning message.
- The full contents of your console log ([instructions for Chrome](https://developers.google.com/web/tools/chrome-devtools/console/#opening_the_console)
- A list of other plugins currently activated for your site

**Comment by ombion** [comment]
Aduth, I'd love to help. That request will take some time to provide you the proper info. I'm on a super tight deadline at the moment, so I'd have to get back to this later.

In the meanwhile, one thing I notice, and this may help. On some of the blocks when I apply CSS class to the optional Advanced > Additional CSS Class box, those tend to act up. The script somehow detects this as "externally" modified, and theoretically it is not because the modification is done according to what the system allows.
