### ISSUE TITLE
Button markup change?

### ISSUE THREAD

**Issue by davouid** [WordPress/gutenberg#21996]
**Describe the bug**
it seems that there was a back and forth with the button markup
**from:** 
```
<div class="wp-block-buttons aligncenter">
<div class="wp-block-button">
<a class="wp-block-button__link " href="#">
XXXXX</a>
</div>
</div>
```
**to:**
```
<div class="wp-block-buttons aligncenter">
<a class="wp-block-button wp-block-button__link " href="#">
Visiter les lieux
</a>
</div>
```
**And back:**
```
<div class="wp-block-buttons aligncenter">
<div class="wp-block-button">
<a class="wp-block-button__link " href="#">
XXXXX</a>
</div>
```
</div>

Is it only me?
Will it change again?

**Comment by davouid** [comment]
I have my answer #21923

**Comment by talldan** [comment]
In case you're wondering why I reopened and closed again, the issue was appearing in 'open' filter searches in github 🤔 
<img width="419" alt="Screenshot 2020-05-08 at 11 30 03 am" src="https://user-images.githubusercontent.com/677833/81367290-5ee06780-911f-11ea-975b-8481760f7690.png">

Seems to be solved after re-closing it.
