### ISSUE TITLE
"Latest Posts" block Featured Image setting, percentage size buttons cannot be indivdually selected

### ISSUE THREAD

**Issue by roo2** [WordPress/gutenberg#22009]
**Describe the bug**
Percentage sizes don't work in the Latest Posts block's featured image settings

**To reproduce**
* Add a **Latest Posts** block
* In the block settings for the Latest Posts block, enable **Display featured image**
    * the "Image dimensions" Section will appear
    * Buttons to set percentage sizes will appear `25% | 50% | 75% | 100%` 
* In the *Image Dimensions* section, select one of the percentage sizes e.g. `25%`

**Expected behavior**
The 25% button is selected and the image is resized to 25% (of the available screen width or original image size?)

**Actual behavior**
All of the percentage size buttons are selected and the images disapear

**Screenshots**
<img width="243" alt="Screen Shot 2020-05-01 at 8 58 20 AM" src="https://user-images.githubusercontent.com/22446385/80768436-c03b9000-8b8d-11ea-8f1e-8435702a97ee.png">

**Editor version (please complete the following information):**
- seen on wordpress.com with gutenberg plugin version 7.7.1 and 8.0.0

**Desktop (please complete the following information):**
 - OS: macos
 - Browser: saw this in Firefox and Chrome

**Comment by annezazu** [comment]
@roo2 Thanks for reporting this! I tried to replicate this on a test site with Gutenberg 8.0.0 and WordPress 5.4 with no additional plugins installed using the TwentyTwenty theme. I wasn't able to! Here's a video I took  demonstrating what I tried to make sure we're on the same page:

https://cloudup.com/c99lbkJAMxE

I'm going to close this out for now since I'm unable to replicate this with the latest version of both Gutenberg and WordPress without any additional plugins. On your end, I'd recommend ruling out a plugin or theme conflict. If you find this is still an issue, feel free to re-open so we can explore this more.
