### ISSUE TITLE
Feature Request: Please add an option to uncheck the Welcome Guide (Tips) and Pop ups (Inserter help Panel)

### ISSUE THREAD

**Issue by La-Geek** [WordPress/gutenberg#22067]
In WordPress 5.4 resp. Gutenberg 8.0 the options to uncheck "Tips" and "Inserter Help Panel are not available anymore. Okay, instead of the Tips there is now the "Welcome Guide" and the "Inserter Help Panel" are now Pop ups. But please add a checkbox for each one. It is enough to see this guide once. But it pops up often and this flackering in the inserter is annoying.

**To reproduce**
Gutenberg 8.0 = Navigate -> "More tools & options -> Options

**Expected behavior**
There should be the checkbox "Tips", resp. "Welcome Guide"  and "Inserer help panel", resp. Pop ups.

Or do you have at least a code snippet for the functions.php to disable it? Thanks in advance.

**Screenshots**

### **WordPress 5.3.2:**
![options_tips](https://user-images.githubusercontent.com/1585416/80912070-b3a86a80-8d3a-11ea-922e-ce1a9aea0a8a.jpg)

### **WordPress 5.4.1:**
![wp_5_4_1__options_inserter_help_panle](https://user-images.githubusercontent.com/1585416/80912214-b192db80-8d3b-11ea-9a23-3522001e7245.jpg)

### **Gutenberg 8.0:**
![gutenberg_8_missing_inserter_help_panel](https://user-images.githubusercontent.com/1585416/80912186-860ff100-8d3b-11ea-9111-d4fac9a29342.jpg)

**Comment by talldan** [comment]
The issue is that the Welcome Guide appears before the user has a chance to access the settings menu, so by the time they've made a choice here the guide has already been dismissed.

The settings menu preferences are also cleared whenever the user clears browser storage, so this wouldn't solve the issue.

It's recognized that using browser storage isn't ideal, so an improvement is proposed on issue #15105 to store the settings in the database. The same would apply when dismissing the Welcome Guide—that this has been dismissed would be stored permanently so in effect you would never see the guide again.

**Comment by La-Geek** [comment]
@talldan 
thank you very much for your help. Since #15105 plus the ticket:
https://github.com/WordPress/gutenberg/issues/22053 exist, this ticket here is outdated and could be closed.
