### ISSUE TITLE
@wordpress/env not working

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#22074]
**Describe the bug**
<img width="565" alt="Screen Shot 2020-05-04 at 8 05 29 PM" src="https://user-images.githubusercontent.com/3365507/80963967-9bbc0e00-8e42-11ea-9c5f-2d1ae1246001.png">

**To reproduce**
1. Run `wp-env start`

**Comment by kirilzh** [comment]
@phpbits  Did you try the suggested actions "re-compiling or re-installing the module (using `npm rebuild` or `npm install`)?

**Comment by phpbits** [comment]
Yeah, did both and I even remove node_modules folder but still having the same error.

**Comment by talldan** [comment]
@phpbits As the error mentions this unfortunately happens if installing using one version of node and then trying to execute a command using another version. It's the `nodegit` dependency that causes this.

> I even remove node_modules folder but still having the same error.

It looks like you're using a global version of `@wordpress/env` (based on the path to node_modules in the screenshot), not sure if you were deleting the folder local to the project. You'd probably have to use `npm uninstall -g @wordpress/env` and then reinstall. 

Or you could switch to the node version used to install originally the package.
