### ISSUE TITLE
gallery shortcode size attribute not honored in Gutenberg Blocks

### ISSUE THREAD

**Issue by ratzrattillo** [WordPress/gutenberg#22070]
When creating a blogpost and using the gallery shortcode with size attributes, the image always gets displayed in the same size.
e.g.: `[gallery ids="123" size="medium"]` results in the same image size when using `[gallery ids="123" size="large"]` or `[gallery ids="123" size="full"]`. The original image size is is e.g. 2000x2000px.

This issue only seems to arise in Gutenerg Blogposts, not on other pages.

**Comment by noisysocks** [comment]
When I test this locally with `size="medium"` and `size="large"` the `sizes` attribute in the HTML is set correctly.

It's possible that the images are _appearing_ the same size because the gallery block by default in Twenty Twenty resizes its columns to be 33.3% of the post width. You can disable this with `columns="0"` in the shortcode.
