### ISSUE TITLE
Use hooks or bind decorator fo context binding in components

### ISSUE THREAD

**Issue by dingo-d** [WordPress/gutenberg#22098]
**Is your feature request related to a problem? Please describe.**

While browsing the media-text component source code I've noticed that all the [methods in the constructor](https://github.com/WordPress/gutenberg/blob/7ecf7a17a2d705dc45db92f5ed5d3d51b56c1863/packages/block-library/src/media-text/edit.js#L63-L69) are using the 

```js
this.methodName = this.methodName.bind(this)
```

pattern, for context binding. This is a common practice in React that people are thought early on (well not just in React, but it applies to regular JS).

I'm sure it's done like this for all components (haven't checked). And while it works and all, it is kinda ruining the readability.

**Describe the solution you'd like**

There are two ways this can be solved:

1. Use React hooks - using `useEffect` could make things more readable. This does require extra effort in rewriting every component using hooks where necessary (I assume there's a lot to rewrite).

2. Use bind decorator from the [decko](https://github.com/developit/decko) package.

With it, any method that needs context provided would get `@bind` in front of it.

I'm more inclined in the second option, as it:

- Removes extra boilerplatey code, and adds simple `@bind` decorator where needed
- Makes code more readable

I would love to hear thoughts about this.

**Comment by youknowriad** [comment]
Hi there! thanks for the suggestions.

Noting that Gutenberg only uses valid JS code + JSX, so decorators are excluded. I believe @aduth is working on PRs to clarify the guidelines.

For the binding, I think your first proposal here is our preferred option. that said, we don't refactor existing components just for the sake of refactoring them because it's just a waste of time. We do refactor to use hooks in general when we need to touch these components for several reasons. Ideally, at some point, we should get rid of the "Component" class usage entirely.

If you'd like more thoughts on this, you should consider bringing this to the #core-js weekly chats.

**Comment by dingo-d** [comment]
> Noting that Gutenberg only uses valid JS code + JSX, so decorators are excluded.

Not sure what's the reasoning behind this, but I'll be looking forward to the guidelines 👍 

Yeah, refactoring for the sake of refactoring makes little sense. That's the WordPress core way as well if I'm not mistaken.

Yeah, since hooks are in the React core, makes sense to use them ofc 👍 

Thanks for the quick answer!

**Comment by youknowriad** [comment]
> Not sure what's the reasoning behind this, but I'll be looking forward to the guidelines

I believe the reasoning is the following: we don't want to use something that can get removed later. There are some examples out there like Object.observe for instance.

**Comment by aduth** [comment]
Proposed documentation for language feature support commitment: #22030

Proposed documentation to encourage function components (no class components): #22090
