### ISSUE TITLE
Icon spacing consistency in the Top Toolbar

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#22110]
**Describe the bug**
The ellipses icon is too close to the settings icon in the top toolbar.

**Expected behavior**
I expected more spacing between the actual click areas of each icon, not just between the icons themselves. Otherwise we end up with something like this:

![Screen Shot 2020-05-05 at 8 19 03 AM](https://user-images.githubusercontent.com/617986/81083354-53840680-8ea9-11ea-8b45-062102cd6efb.png)

On the left side of the top toolbar, this seems to be accounted for already and looks much better.

![Screen Shot 2020-05-05 at 8 21 25 AM](https://user-images.githubusercontent.com/617986/81083509-875f2c00-8ea9-11ea-9ffc-6f0244b5a04d.png)

I get that there's some logic going on because when the settings sidebar is hidden, the cog icon is inactive and doesn't show a background. In which case, this appears just like the left side where the icons' click areas all butt up against each other. However, this still feels very awkward when one of the icons can be activated and show a background color.

cc @jasmussen for your insight here.

**Comment by jasmussen** [comment]
I would suggest that's actually intentional, because the vertical ellipsis is an optically smaller-footprint icon than most of the others, so when none of the icons are focused or toggled, the balance feels right:

<img width="282" alt="Screenshot 2020-05-06 at 08 54 54" src="https://user-images.githubusercontent.com/1204802/81145787-49303e00-8f77-11ea-8d8d-bb4a51bc57f8.png">

One way to address that is to make the button actually smaller, and then add spacing:

<img width="325" alt="Screenshot 2020-05-06 at 08 57 43" src="https://user-images.githubusercontent.com/1204802/81145978-b2b04c80-8f77-11ea-90dc-12fcacc4581c.png">

But that doesn't seem to come with any tangible benefits, it's just a smaller clickable area. 

#21870 talks a bit more about improving the grid spacing in the top toolbar, perhaps we can revisit aspects of the more menu in that ticket?

**Comment by mapk** [comment]
I figured there's some reasoning here. 😄 I can close this to resume discussion in #21870. Thanks!
