### ISSUE TITLE
Opt-in usage tracking notice improvements

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#2215]
Looking a bit into the [recently added](https://github.com/WordPress/gutenberg/pull/2140) usage tracking notice, noticed a few things:

<img width="582" alt="firefox" src="https://user-images.githubusercontent.com/1682452/28962813-3306f256-7907-11e7-97d5-c2f05eded0c3.png">

There are two "dismiss" buttons:

![screen shot 2017-08-04 at 11 11 47](https://user-images.githubusercontent.com/1682452/28962820-3dd3632c-7907-11e7-9706-6692af7da9ad.png)

this is because of the combined effect of the component and the WordPress `makeNoticesDismissible()` (which runs on document ready). Since this notice appears on page load, `makeNoticesDismissible()` adds its own dismiss button.

Reducing the strings to translate is always a good thing. See `Dismiss this notice` vs. `Dismiss this notice.` (period at the end).

The order of the elements in the notice could be improved. Currently, the Yes and No button are placed before the text. Screen reader users will hear, in this order:
Yes
No
Can Gutenberg collect data ...
Dismiss this notice
(Dismiss this notice.)

Also from a logical perspective, I'd say available answers should go after the question.

All text is wrapped in `<div>`s. It would be nice to use slightly more semantic elements for text. The WordPress notices use paragraphs.

The italic text uses a `font-size: 90%;` which translates to a computed value of `11.7px`. This is definitely too small. I'd also propose to use values that translate to a computed value without rounding.

Minor: the rendering is different across browsers. I'd propose no action on this, just something to be aware of:

Chrome:

![chrome](https://user-images.githubusercontent.com/1682452/28963222-ac1af89e-7908-11e7-881b-b2536ad78a64.png)

Firefox: 

<img width="582" alt="firefox" src="https://user-images.githubusercontent.com/1682452/28962813-3306f256-7907-11e7-97d5-c2f05eded0c3.png">

this ie because bold text is rendered differently.

**Comment by nylen** [comment]
> There are two "dismiss" buttons

Their behavior is slightly different.  The "No" button makes a decision that will cause the notice to go away; the "dismiss" button does not.

This probably isn't necessary though; fixed in #2217.

> The order of the elements in the notice could be improved

Fixed in #2217.

> The italic text ... is definitely too small.

If this text needs to get bigger, then it should probably not be shown by default because then this notice is taking up too much space.  I tried to move it behind a `Popover` in #2217 but it got a bit complicated and there are a few more things to be done still.

Another option would be a modal dialog, but we don't have a component for this yet.
