### ISSUE TITLE
I noticed that you added SubScript & SuperScript in toolbar, can you add UpperCase, LowerCase, Capitalize.

### ISSUE THREAD

**Issue by Nemzag** [WordPress/gutenberg#22163]
**Is your feature request related to a problem? Please describe.**
Sometime I would like to change case easily and rapidly,
instead than switching between apps and making long copy paste, change, copy paste.
(because since a recent change in editor, in a blockquote block, we can't paste many para‑graph because it break and split the blockquote in two parts, so we need to copy paste one line by one.)

**Describe the solution you'd like**
Add these three icons in tool‑bar in "Pole rich text controls".

**Comment by Nemzag** [comment]
May be you can add <abbr> also.
Good bye.

**Comment by ramonjd** [comment]
👋 Since https://github.com/WordPress/gutenberg/pull/34064 most core text blocks have support for text transforms:

![Nov-09-2021 11-44-52](https://user-images.githubusercontent.com/6458278/140841146-211d7618-bfef-494e-a260-56d783889946.gif)

The options aren't in the toolbar, but in the editor sidebar control panel.

Do you think it's a reasonable compromise or should we keep this issue open to discuss UX proposals?

**Comment by richtabor** [comment]
> The options aren't in the toolbar, but in the editor sidebar control panel.

That's right. It's not planned to incorporate the typography stack into the toolbar — I'll close this. Thanks!
