### ISSUE TITLE
Only Use Own Block Editor Styles

### ISSUE THREAD

**Issue by 1sd15** [WordPress/gutenberg#22162]
**Is your feature request related to a problem? Please describe.**
I've always been frustrated with the Gutenberg CSS in the backend as it's selectors are generic and affect the blocks I'm bringing in. An example of this is the selector for 'img' in 'block-container'. This alters the images in the blocks I bring in and thus makes is annoyingly difficult to keep the front-end-css look and feel on the backend.

**Describe the solution you'd like**
Ideally the issue of using generic selectors is solved via the means for setting their alterations to 'img' (for example) to a class that is applied to their default blocks. However, as this is probably a difficult and long fix, so I understand the lack to do it. If I could completely stop loading the Gutenberg Styles and instead add my own block styles, even if it means adding in the 'add block' buttons are everything myself, I would prefer that.

**Describe alternatives you've considered**
I have tried overriding the styles but it's tedious and wiping a CSS selector can prove difficult due to when the styles come into the backend and are loaded.

**Comment by talldan** [comment]
@1sd15 Thanks for the feedback. Usually I've found it's helpful for tickets to be specific and actionable and then they're more likely to be picked up. Often more general tickets are very hard to put into action.

The example you pointed to of `img` is helpful, maybe you'd be able link to the style in the codebase or share a screenshot of the rule in the browser dev tools so that it's easier to investigate.

**Comment by devinmaeztri** [comment]
Hi! I'm closing this issue as the author @1sd15 hasn't responded in 2+ weeks. It can be reopened when needed. Thanks!
