### ISSUE TITLE
Documentation on the ClassicEdit component

### ISSUE THREAD

**Issue by chvillanuevap** [WordPress/gutenberg#22206]
Hi there!

I'm trying to include the classic editor (TinyMCE) in a custom block. I have setup my entire block, but I'm missing the most important piece. I have no idea how to import the ClassicEdit component into my file. There is no documentation about the component in the WordPress Handbook, and unlike RichText or any other component, it does not live in either wp.editor or wp.components. I did a search on the handbook documentation, and there is not a single mention of this component. Is it not mentioned because we are not supposed to use it? 

I've tried:
```
import { ClassicEdit } from '@wordpress/block-library';
const { ClassicEdit } = wp.editor;
const { ClassicEdit } = wp.components;
```
and I keep getting the error in the console:
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```
I wanted to request for some documentation on this component, or for the component to be added to the developer handbook.

Thanks!

**Comment by chrisvanpatten** [comment]
Hi @chvillanuevap —

The component is not actually exported from the block library for public use. That's why you can't find any documentation for it: it's not supposed to be used by third parties. It powers the "Classic" block and is tailored to that purpose.

That said, I previously implemented a `WysiwygControl` which is heavily inspired by the classic block. You are welcome to [copy the code from my repo](https://github.com/TomodomoCo/wp-wysiwyg-control) as a starting point for your own work.

As this is not strictly a Gutenberg issue (since the ClassicEdit component it not intended to be used) I'm going to close this. Thanks for writing in!
