### ISSUE TITLE
Header toolbar: last two buttons have no margin between them

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#22219]
<img width="304" alt="Screenshot 2020-05-08 at 12 55 42" src="https://user-images.githubusercontent.com/4710635/81399600-8c331280-912b-11ea-871a-cdf7eb8685e0.png">

Cc @jasmussen

**Comment by jasmussen** [comment]
Interestingly, @mapk recently reported the exact same issue in #22110, and my response here is going to be the same — the icons are optically sized, and will feel imbalanced if a margin is added there. One thing we can do is [make the button less wide](https://github.com/WordPress/gutenberg/issues/22110#issuecomment-624476659), but that just makes for a smaller hit area.

More than that, I hope we can revisit some of these things, including the toggled button size, in #21870, that might prove a better solution to it.

**Comment by ellatrix** [comment]
Ok, makes sense :)

**Comment by mapk** [comment]
I think we can fix this! It's obviously awkward, so I think we can work a solution here. Interestingly enough we might be able to add more space there similar to the other side.

![Screen Shot 2020-05-08 at 5 08 20 PM](https://user-images.githubusercontent.com/617986/81458307-97e40080-914e-11ea-8c21-de3b41f0baa1.png)

And just make the ellipses horizontal instead of vertical. That may do it.
