### ISSUE TITLE
Patterns thumbnail throws validation error

### ISSUE THREAD

**Issue by nicpelletier** [WordPress/gutenberg#22276]
Hi,

I have a filter that automatically ads ids to groups and headers to build a custom in page nav. It conflicts with the patterns that contains a group (probably headers too) like "Hero Two Columns" because of validations errors. I can't see the patterns previews and if add the block anyway, i have a error saying that the block contains invalid stuff instead of showing the block in the editor.

If this is not considered a Gutenberg bug, can you suggest a way to achieve what i need to do? It's been working fine for over a year now. I just updated from version 7.5.1. I guest there was no patterns in this version. I'm using Gutenberg 8 and WordPress 5.4.1 now.

Here is my code. Sorry for the french comments, but you should get what it does :

`
function ajoutAttributs( props, type, attributes ) {
	if ( type.name === 'core/group' || type.name === 'core/heading' ) {
		// Pour les blocs Gutenberg natifs de titre et de groupe (utilisés pour onglets de type de procédure), si un id (ancre) n'a pas été ajouté par l'édimeste, ajoute un id automatiquement. Ce dernier est composé du type de bloc et d'un nombre aléatoire de 1 à 100000. Les id sont utiles à la navigation (ancres) et à l'accessibilité (ARIA).
		let nom = '';
		if ( props.id ) {
			nom = props.id;
		} else {
			const nomComplet = type.name;
			const noms = nomComplet.split( '/' );
			nom = noms[ noms.length - 1 ];
			const nombre = Math.floor( Math.random() * 100000 );
			nom += '-' + nombre;
			props = lodash.assign( props, { id: nom } );
		}
		// Ajoute l'attribut ARIA role aux onglets (groupe avec la classe "type-procedure").
		if ( type.name === 'core/group' && attributes.className ) {
			if ( attributes.className.includes( 'type-procedure' ) ) {
				props = lodash.assign( props, { role: 'tabpanel', 'aria-labelledby': 'btn-' + nom } );
			}
		}
	}
	return props;
}

wp.hooks.addFilter(
	'blocks.getSaveContent.extraProps',
	'aide-brio/ajout-id',
	ajoutAttributs
);
`

[Here is the console error i get when i click the patterns thumbnail.](https://gist.github.com/nicpelletier/d0f3f10cb36ba234b28b15c20ca49465)

Thank you!

**Comment by annezazu** [comment]
Hey @nicpelletier! Thanks for jumping in here. This repository is focused on the development work for Gutenberg including reporting bugs, feature requests, etc. As a result, the best place to get help with the customization you're trying to do is in the forum below:

https://wordpress.org/support/forum/wp-advanced/

Please share your request there!

**Comment by nicpelletier** [comment]
Hi @annezazu ! Thank you for your suggestion. Can we just give this a second look or a second opinion, because i really think that if this is not a bug, there is at least a problem with the doc. We have the same validation problem with the patterns if we use the exemple code that is in the blocks.getSaveContent.extraProps filter official documentation: 
https://developer.wordpress.org/block-editor/developers/filters/block-filters/#blocks-getsavecontent-extraprops

**Comment by annezazu** [comment]
Sure thing! @mkaz might you be able to chime in here and take a look? :)

**Comment by mkaz** [comment]
Hi @nicpelletier - I tested it out and it does work as described, but I think I also uncovered the same problem you ran into.  You can see my test on this branch here: https://github.com/mkaz/test-block/tree/test/extra-props

The issue is if you are adding a filter to an existing block — in my example, I added a background color to the default heading block — then when the editor loads existing content (previous to the filter existing) then what is saved does not match what the editor expects and you get a validation error.

You can see this if you:

1. create a post with a heading block and ave it
2. use my example plugin 
3. load the post in the editor, it will invalidate the heading block

However, if you create a new post with the plugin enabled, add a heading, save it, and then go back to editing the heading will be fine. Because the new post saved while using the plugin, will save the extra prop, and thus will not invalidate.

I'll investigate some more, it seems like that invalidation shouldn't occur, otherwise the function will not be that useful, since it would invalidate any existing content, which I don't think is the intent.

**Comment by mkaz** [comment]
I created a new ticket with the specifics I'm seeing, let me know if that doesn't cover what you are describing or if there is more to it. Thanks for raising the issue.
