### ISSUE TITLE
Enable the block movers in List View and add e2e tests

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#22287]
## Description

https://github.com/WordPress/gutenberg/pull/18014 introduced block movers for the block navigation. Currently they're enabled in the Navigation Block, so that they can be tested and any issues ironed out, but at some point could be introduced in the general purpose block navigation in the editor.

This should be a simple task, but as part of that, it'd be prudent to also include e2e tests for the feature.

I've labelled this as `Blocked`, which can be removed when we're comfortable enabling the feature.

**Comment by SchneiderSam** [comment]
Oh yes! So useful!!!

**Comment by richtabor** [comment]
I noticed we have a [showBlockMovers prop](https://github.com/WordPress/gutenberg/blob/d858c0683137ee05732790940777424010484449/packages/block-editor/src/components/list-view/index.js#L72) in the `ListViewComponent`. 

Has this been considered for the List view lately? cc. @WordPress/gutenberg-design 

<img width="350" alt="CleanShot 2023-04-12 at 12 33 37" src="https://user-images.githubusercontent.com/1813435/231523710-cd298c99-e232-4113-9824-3f5e5417876f.png">

**Comment by jasmussen** [comment]
They always felt a bit fiddly to me due to their small hit area, which is tricky to fix. If I'm using a mouse to move things around, drag and drop in the list view feels superior. Which, to be clear isn't a knock on the movers: in many times the explicit up/down action can be more precise, whereas drag and drop can be imprecise. But combined with the separate discussions on the list view becoming hard to navigate in deep nesting contexts, I'd love to get a bit further with improving those pieces first.

**Comment by richtabor** [comment]
> in many times the explicit up/down action can be more precise, whereas drag and drop can be imprecise. 

Yes, exactly. I've found my flow is to select a block in List view, see which block/group is selected within the content area, then drag it around there in the canvas. 

Perhaps if drag and drop were improved, and group naming in List View https://github.com/WordPress/gutenberg/pull/42605 happens, that would add enough confidence to not look for better precision placement controls.
