### ISSUE TITLE
Large Quote style should not be set to italic in the core

### ISSUE THREAD

**Issue by danieldudzic** [WordPress/gutenberg#22305]
<img width="1768" alt="Banners_and_Alerts_i_Edit_Post_‹_This_is_a_site_title_super_long_—_WordPress" src="https://user-images.githubusercontent.com/905781/81749669-5932ab00-94ac-11ea-9050-ee6710a08209.png">

Currently, the core styles the Large Quote style with: `font-style: italic`

This renders "Italic" setting unusable.

![IDioP6zbVW](https://user-images.githubusercontent.com/905781/81751596-05c25c00-94b0-11ea-898b-c29f2fc1f3e6.gif)

The Twenty Twenty theme actually overrides it with  `font-style: normal` "fixing" the issue.

In my opinion, in an ideal world, the theme should decide, whether to have the italic setting pre-selected for (Large) Quotes.

**Comment by joyously** [comment]
This same thing can be said of a lot of the core block styles. The opinionated parts of the styles belong in theme.scss instead of style.scss, so that the theme can opt out. 
But I've actually made this same exact complaint of styling quotes as italic in many theme reviews. The blockquote element is for quoting a reference, and it can contain HTML markup like bold and italic and links, so using colors or italic or bold for the styling means the choices of author are limited.

Unfortunately, testing this shows that there is another problem with the inline tools. You can't nest bold inside of bold or italic inside of italic. Themes should be styling for extra bold and different kinds of emphasis. For instance, in my theme I have
`em em, em i, i em, i i, cite em, cite i { text-transform: uppercase; }`

**Comment by skorasaurus** [comment]
Thanks for reporting; the 'large quote' style has been removed and the quote is not italicized in either style now provided by Gutenberg.
