### ISSUE TITLE
Add custom fields in image settings sidebar

### ISSUE THREAD

**Issue by gedraamanda** [WordPress/gutenberg#22330]
I want to add a credit field in the image settings. At the moment, the field appears when we place an image:

![ex](https://user-images.githubusercontent.com/47435955/81849461-eddced80-952c-11ea-8f52-67ab162174ed.jpg)

And every time I need to edit the field I have to remove the image and put it back. 
I think the solution is to put the field in image block settings (admin sidebar) or turn back the popup edition.

Wordpress have a solution for this?

**Comment by karmatosed** [comment]
Hi @gedraamanda this looks like you'd be wanting to extend the media panel. For that, I would point you to the developer documentation for WordPress over Gutenberg specifically, https://developer.wordpress.org/. As this isn't an issue with the editor lets close this up for now.

**Comment by altendorfme** [comment]
That was not a very nice way to help.

Not all of us are React developers, and adding an extension to the media panel is anything but simple, the only documentation closest to this issue was from @liip on your blog (https://www.liip.ch/en/blog/how -to-extend-existing-gutenberg-blocks-in-wordpress).

Before Gutenberg we worked with mandatory fields at ACF, which is really practical!

Adding credits to images is really important, there are laws in several countries that require us to put this information, the developers of Gutenberg could have thought of that.
