### ISSUE TITLE
Documentation: Technical documentation areas for improvement

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#2236]
Aside from being out-of-date, through conversations and code observations I've noticed some areas of technical documentation which are lacking. Noting them here for my own reference. This is an incomplete and working list. Feel free to add your own.

- How and where is a block saved?
- What are [comment|sourced] attributes?
- When would I want to use a comment attribute instead of a sourced value?
- How do I represent a new / placeholder / empty block?
- How do attributes change?
- What are props?
- Which props are passed to [edit|save]?
- Up-to-date API reference

Topics which are covered but could do for some elaboration:

- Why are there two functions `edit` and `save`?

**Comment by karmatosed** [comment]
As the project moves towards a full vision, we are moving issues that aren't needed for that to projects. This doesn't mean they won't get done, they totally can and that's why we're moving to projects. This allows us to focus on the issues that have to happen to Gutenberg. I am closing this but it will live in projects.
