### ISSUE TITLE
Transform to block from post meta

### ISSUE THREAD

**Issue by dingo-d** [WordPress/gutenberg#22378]
**Is your feature request related to a problem? Please describe.**

A lot of sites, in the past, used to use ACF as a 'page builder'. You'd create set of 'components' and you could build a page using that. All the content would be stored in the post meta, as that's what ACF does.

Cut to present day where we have GB with blocks, and the ability to transform blocks from one type to another, and [some other types](https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/block-api/block-transforms.md). But no post meta transforms.

**Describe the solution you'd like**

This presents a problem because there is no way to have a concise way to transform post meta fields, or group of them, into a single GB block.

You're basically stuck manually transferring everything. And if you have a huge site built that way, you're most likely doomed to never ever move it to the new editor.

This is something that people who work in agencies see most of the time, and why many of them are not willing to move to GB (one of the reason). Doing everything manually takes time, and in most cases the ROI for the client is minimal.

It would be great to have that kind of transform. And it would be great to be able to use that on existing posts/pages/CPTs.

**Comment by dingo-d** [comment]
Any info about this?

**Comment by tellthemachines** [comment]
To be clear, is the request for a mechanism to transform custom fields like ACF fields into core blocks? This would not be straightfoward because ACF can have many different formats, some of them not compatible with existing core blocks (inputs for example) and transforms need to know exactly what they're transforming from and to, in order to make sure the block contents get preserved correctly. 

It's a hard problem to solve because ACF style template building and Gutenberg blocks are very different mental models: blocks are made to be as close as possible to front end presentation, whereas the mapping between ACF fields and the front end is very much up to individual theme authors.

**Comment by dingo-d** [comment]
Well, all ACF fields are stored in the post-meta fields. And currently, the transformation types are:

```block
enter
files
prefix
raw
shortcode
```

So there is no easy way to specify you want to transform meta fields to a block.

If you could map the meta fields to block attributes, the problem of transforming ACF 'builders' to blocks would be easier I think.

**Comment by tellthemachines** [comment]
> So there is no easy way to specify you want to transform meta fields to a block.

Core transforms only apply to content that's typed or pasted into the editor: text, code, files or shortcodes. Potentially, if the meta fields had any expression in the output HTML (e.g. as data attributes), you could write a raw transform that would turn them into block attributes. 

But the block you'd be transforming _to_ would have to be a custom block, which would have to be registered with the attributes that correspond to the ACF custom fields, so that part at least would still be manual.

**Comment by dingo-d** [comment]
The problem (the way I remember it when I was thinking about it back in 2020 when I wrote this issue) is that you don't have meta fields exposed so that you can use the data from them to transform the meta field to a block.

Say you have a 'card' component made out of ACF fields: image, headline, paragraph, and link. If you'd have the meta fields available during the transform, you could create a custom transformation rule that will just convert those fields into corresponding core (or custom) blocks (optionally wrapping them in a group). Or even creating a custom block.

So the manual part is implied, the problem is the lack of a way to fetch that data directly in the transform function in JS (to my knowledge).

I hope I'm being a bit clearer about the intentions and limitations, I didn't really think about this in a long time (almost 3 years to the day 😅).

**Comment by tellthemachines** [comment]
> So the manual part is implied, the problem is the lack of a way to fetch that data directly in the transform function in JS (to my knowledge).

Oh, I see. I haven't actually tried this, but you should be able to use `wp.data.select( 'core/editor' ).getEditedPostAttribute( 'meta' )` within the transform function to get the post meta.

**Comment by dingo-d** [comment]
Will test this out, thanks 👍🏼

**Comment by priethor** [comment]
Thanks for reporting, @dingo-d. Let's close this issue, as it still needs more info to be actionable. Please feel free to reopen it again if there is more information. 🙏
