### ISSUE TITLE
Using blocks.getSaveContent.extraProps invalidates for existing content

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#22386]
**Describe the bug**

When using the filter `blocks.getSaveContent.extraProps` and adding an extra prop to a block causes invalidation errors for any existing blocks for that type.

I created a minimal test plugin to demonstrate, you can see on this branch: 
https://github.com/mkaz/test-block/tree/test/extra-props

In my example, I add a background color to the default heading block, when the editor loads existing content saved prior to the plugin, then when it is loaded the the extra prop added you get a validation error.

**Steps to reproduce:**

1. Create a post with a heading block and save it
2. Download and activate [the example plugin](https://github.com/mkaz/test-block/tree/test/extra-props), or create your own JS file using the filter.
3. Load the existing post in the editor, and the heading block will have a validation error.

**Expected behavior**

It seems like the goal of the filter `blocks.getSaveContent.extraProps` is to allow people to add extra props to core (or other) blocks without causing any invalidations, so it should work with existing content loaded into the editor.

Related: #22276 

As reported in #22276 it was related to patterns and that the bug was new when using Gutenberg 8, so unknown if something changed with some newer updates.

**Comment by youknowriad** [comment]
That's not a bug for me, that's expected behavior and one of the reasons we recommend render_block server-side instead of using this filter.

**Comment by mkaz** [comment]
Ok, I can update the docs to reflect that, the existing Note: is around using in Developer Tools, and does not mention the issue with existing content.

https://developer.wordpress.org/block-editor/developers/filters/block-filters/#blocks-getsavecontent-extraprops

**Comment by nicpelletier** [comment]
@mkaz, @youknowriad, thanks for the help and the note in the doc, but there's more to it. In your test plugin, if we change "heading" at line 7 of test.js to "paragraph", "group" or any core block used in the default patterns, you will have a validation error in the tumbnail. See : 
https://github.com/nicpelletier/issues-reporting/blob/master/pattern-error1.png

If you add the pattern to your page, you will have the error in the main editor. See : 
https://github.com/nicpelletier/issues-reporting/blob/master/pattern-error2.png

Maybe the blocks.getSaveContent.extraProps filter should be deprecated because chances are that if it's used, it makes the patterns unusable.

Thank you,

**Comment by youknowriad** [comment]
`blocks.getSaveContent.extraProps` is actually useful for Core itself. Maybe we could soft-deprecate it and have an unstable one only used by Core at some point.
