### ISSUE TITLE
WritingFlow in navigation mode doesn't scroll the page

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#22420]
**Describe the bug**

When the editor is switched to "navigation mode", the WritingFlow component is supposed to make the Tab and Down / Up arrow keys navigate from block to block.

Actually, the blocks are selected but the page doesn't scroll. In a page with long content, this defeats the whole purpose of WritingFlow as the selected block doesn't ever come into view.

**To reproduce**
- edit a post with some long content
- click on the title
- use the Tab or Down arrow keys to move to the first block after the title
- press Escape to switch to "navigation mode"
- keep pressing the Tab or Down arrow keys to navigate the blocks
- observe the page doesn't scroll
- observe the Sidebar: the content changes and shows the selected blocks type and settings, which is correct and proves the blocks are actually selected
- however the page doesn't scroll so keyboard users can't really see which block is selected

Note that in this context, the term "selected" refers to the Gutenberg block selection mechanism, not the DOM selection methods.

Animated GIF to better illustrate:

![writing flow navigation mode](https://user-images.githubusercontent.com/1682452/82221876-da60c680-9920-11ea-9e8d-c45473a1a9cd.gif)

In the scenario above, I wonder how this block navigation mechanism is of any help for sighted keyboard users.

**Expected behavior**
The page to scroll and the "selected" block to be into the screen view.

**Browsers details**
- note: I can see some scrolling only with Safari stable 13.1
- no page scroll with Safari technology preview Release 106 (Safari 13.2, WebKit 15610.1.12.2)
- no page scroll with macOS Chrome 81
- no page scroll with macOS Firefox 76.0.1

**Editor version (please complete the following information):**
- WordPress version: 5.4 and trunk
- can reproduce on the WP 5.4 block editor, the trunk block editor, and the plugin Version 8.1.0 

**Additional context**
Code responsible for this behavior:

https://github.com/WordPress/gutenberg/blob/c327f19aaa873452e35d6fbc169e6acac11247e0/packages/block-editor/src/components/writing-flow/index.js#L379-L410

**Comment by aduth** [comment]
Is there something of the "code responsible" (e.g. `event.preventDefault`) you're expecting would be preventing the scroll behavior from taking place?

I observe that outside navigation mode, there's a "scroll into view" behavior in caret selection placement of `placeCaretAtVerticalEdge` ([source](https://github.com/WordPress/gutenberg/blob/c327f19aaa873452e35d6fbc169e6acac11247e0/packages/dom/src/dom.js#L421)). If I recall, a custom implementation was used for multi-selection ([`MultiSelectScrollIntoView`](https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/multi-select-scroll-into-view/index.js)), likely at least in part because "multi-selection" is largely an emulated selection.

Unsure if it's a case where something like this is necessary for navigation mode, or if the default focus behavior could be expected to bring the focused block into view.

**Comment by afercia** [comment]
I tried to comment out `event.preventDefault()` as first thing, and didn't notice changes in the behavior.

FYI: just created another issue which highlights more WritingFlow buggy behaviors that happen only with Firefox, see https://github.com/WordPress/gutenberg/issues/22424

The fact it works (sort of) in Safari 13.1 and there are additional broken behaviors in Firefox potentially highlights some non-standard method used to move focus or maybe an issue related to timings or who-knows-what that makes the actual behavior very inconsistent across browsers.

**Comment by tellthemachines** [comment]
I tested this in Chrome and Safari on macOS and Chrome and Firefox on Windows 11 and it's working well now. Closing this issue; feel free to reopen if it reoccurs.
