### ISSUE TITLE
Show toolbar in starting point of nav-menus screen

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#22468]
Currently, if you've created a menu and come to the screen, you get the following showing:

![image](https://user-images.githubusercontent.com/253067/82354600-ecae3380-99f8-11ea-91ed-eed3d3df25b5.png)

I would suggest if we can showing the toolbar would make for a better visual experience. It then is easier to see it's a block.

**Comment by noisysocks** [comment]
We can make it so that the leftmost block is selected by default. One issue with this, though, is if that leftmost item has subitems then things look a bit confronting.

![localhost_8888_wp-admin_admin php_page=gutenberg-navigation(Laptop with MDPI screen)](https://user-images.githubusercontent.com/612155/82784073-253f8880-9ea3-11ea-9432-f49c334b8bc9.png)

I wonder if it's possible to show a greyed out toolbar when there is no block selected?

**Comment by draganescu** [comment]
We should select the Navigation block itself once it's built and the toolbar will show.

**Comment by adamziel** [comment]
https://github.com/WordPress/gutenberg/pull/22737 aims to solve this one

**Comment by karmatosed** [comment]
@adamziel I still see the following though:

![image](https://user-images.githubusercontent.com/253067/83264043-71e2d680-a1b7-11ea-9f49-d8be2938cac1.png)

Am I missing something here as I would have expected to not still see the blank screen.

**Comment by draganescu** [comment]
In my testing this was closed by #22737
