### ISSUE TITLE
Class "is-without-arrow" is added to all Toolbars instead of just the ones without arrows.

### ISSUE THREAD

**Issue by ggedde** [WordPress/gutenberg#22474]
When editing a block the class "is-without-arrow" is added to all toolbars. Instead it should only be added to the ones that don't include arrows.  Like when you only have one block. Currently is showing on all.

Running WordPress Version 5.4.1
Using default Gutenberg
MacOs 10.14.6
Chrome 81.0.4044.138

**Comment by talldan** [comment]
@ggedde I'm not sure what you mean when you say:
> Instead it should only be added to the ones that don't include arrows. Like when you only have one block.

The `is-without-arrow` class refers to the little triangle that appears on popovers or tooltips. Like this one you see in github's UI:
<img width="51" alt="Screenshot 2020-05-22 at 4 33 42 pm" src="https://user-images.githubusercontent.com/677833/82648289-0eeac000-9c4a-11ea-909f-f6f09cf12dc3.png">

The toolbar is implemented as a popover. 

As far as I know, all the 'arrows' were all removed from the editor in the recent redesign, so that explains why `is-without-arrow` is ubiquitous.

**Comment by talldan** [comment]
Ah, I think I see what you mean now. You're referring to the Block Movers.

As mentioned above, `is-without-arrow` refers to something different, so I'll close the issue.

**Comment by ggedde** [comment]
@talldan Thanks, I guess I just didn't know what that meant.  I will open a separate request as I need a way with css to know if the popup toolbar does not contain movers.
