### ISSUE TITLE
Bouncing navigation is distracting when short link or longer link moves to next line

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#22472]
This is a bit hard to explain, so I have a gif!

![2020-05-19 18 51 17](https://user-images.githubusercontent.com/253067/82360847-e40e2b00-9a01-11ea-8067-2f67a9a663ed.gif)

As you can see as you add a link, if there is limited space it wraps. This makes sense, however on being smaller there is a weird experience of it popping back up. I am not sure what could resolve this apart from my suggestion of it not wrapping. It certainly feels like there should be more spacing around the '+' also.

**Comment by MichaelArestad** [comment]
I don't think the behavior should change as far as wrapping goes because it's not altogether different than a long word wrapping when writing a paragraph. That said, we could explore horizontal scrolling when overflowing instead of wrapping.

**Comment by ZebulanStanphill** [comment]
>That said, we could explore horizontal scrolling when overflowing instead of wrapping.

I disagree. On the front-end, the menu links wrap, so they should do the same in the editor.

I don't really see this as a bug in the first place. Maybe it's a little jarring to have it move up/down like that, but it has to move because wrapping links mid-text would be a weird experience for a Navigation menu, and having them overflow using a scroll bar would be a really bad Navigation experience... especially for desktop where horizontal scrolling is more difficult.

**Comment by MichaelArestad** [comment]
> I disagree. On the front-end, the menu links wrap, so they should do the same in the editor.
Very true.

**Comment by shaunandrews** [comment]
I don't see this as a bug; Its expected behavior.
