### ISSUE TITLE
Accessing attributes in a dynamic block

### ISSUE THREAD

**Issue by echoloco** [WordPress/gutenberg#22480]
Hello, I am not sure if this is a bug or a misunderstanding on my part on how blocks work. I am trying to create a dynamic block and I am unable to determine the way to grab the Javascript attribute information on the PHP side.

My current index.js:

```
import edit from "./edit";

import { registerBlockType } from "@wordpress/blocks";
import { __ } from "@wordpress/i18n";

const attributes = {
    max_links: {
        type: "number",
        default: 7
    },
    links: {
        type: "array",
        default: [],
        source: "query",
        selector: "a",
        query: {
            text: {
                source: "html"
            },
            link: {
                source: "attribute",
                attribute: "href"
            }
        }
    }
};

registerBlockType("myblocks/quicklinks", {
    title: __("Quick Links", "myblocks"),
    description: __("Quick Links Block", "myblocks"),
    icon: "list-view",
    category: "my-category",
    keywords: [__("links", "myblocks")],
    attributes,
    edit
});

```

Current plugin.php:

```
function my_register() {
  register_block_type('quicklinks', array(
        'render_callback' => 'my_blocks_render_quicklinks_block',
        'attributes' => array(
            'max_links' => array(
                'type' => 'number',
                'default' => 7
            ),
            'links' => array(
                'type' => 'array',
                'default' => [],
                'source' => 'query',
                'selector' => 'a',
                'query' => array(
                    'text' => array(
                        'source' => 'html'
                    ),
                    'link' => array(
                        'source' => 'attribute',
                        'attribute' => 'href'
                    )
                )
            )
        )
    ));
}

add_action('init', 'my_register');

function my_blocks_render_quicklinks_block( $attributes, $content ) {
    var_dump($attributes);
    var_dump($content);
}

```

When I run the code the value of `$attributes['max_links']` is properly set to 7 but the value of `$attributes['links']` is an empty array.

My best guess is that my variable declaration in PHP is not matching the Javascript side but I cannot find any examples that define the source of the attribute as a query. Is there a way to get the query from the PHP side? Can I get the same information from the HTML as can be done in the Javascript side? Do I need to save the attributes from the Javascript side to something such as Redux and then pull them on the PHP side somehow? Are there any examples I can use to implement this?

Thanks

**Comment by talldan** [comment]
@echoloco I think the issue is that you can't source attributes from markup (using the `query`, or `html`/`attribute` source options) for dynamic blocks because they don't save any HTML, their markup is generated by the server side render_callback function when a post loads.

To demonstrate, the dynamic Latest Posts block looks like this in the code editor:
```
<!-- wp:latest-posts {"displayPostDate":true,"displayFeaturedImage":true} /-->
```
There's no HTML content, all the attributes are saved and sourced from the block delimiter HTML comment.

For a static block, like Table (which used the query attribute source), because it saves HTML in the post content, attributes like the values in the cells can then be sourced from the HTML that gets saved:
```
<!-- wp:table -->
<figure class="wp-block-table"><table><tbody><tr><td>1</td><td>2</td></tr><tr><td>3</td><td>4</td></tr></tbody></table></figure>
<!-- /wp:table -->
```

So I think your options are to switch to a static block, or simplify your block's attributes:
```
'links' => array(
                'type' => 'array',
                'default' => [],
)
```

You can also add an 'items' option to the attribute definition to define the expected shape of the data, though unfortunately it doesn't seem to be documented.
