### ISSUE TITLE
Wrap button if long single line of text and depending on screen sizes

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#2249]
## Issue Overview
Button goes outside of wrapper container

## Steps to Reproduce (for bugs)
Type/Paste some long sentence inside button block.

- Chrome
- Vivaldi

## Current Behavior
Button goes outside of container and cover Trash icon. If button text is in several rows it will hide the other icon too.

![](https://s1.postimg.org/hepgtecun/2017-08-06_164727.jpg)

**Comment by karmatosed** [comment]
I'm in 2 minds if this is a bug. Why? Well because you are asking it to have one long line of text. The alternative is it would either:

- Lie over the trashcan icon
- Auto wrap to the size of the screen

Now the later would be something the button would do on the actual front also. I think there's a case for having that be a behaviour of the button.

**Comment by StaggerLeee** [comment]
Hi @karmatosed, 
it is only for you as info. There is 95% probability I will disable this block on all websites. As many others too.

Unrelated to all this, or it is. As Gutenberg now is very huge and new beast I urge you to reconsider making one new Settings Page only for Gutenberg. And open for Role based Gutenberg.

I can tell you how will it be in the future. No web design company would dare put anything they did in its Portfolio. Pictures there can be very different from how website looks. Users/Owners have to much influence of whole feeling, layout and design on website.

It will be very time demanding job to limit them to what they can/may and cannot do with Gutenberg.

**Comment by jahvi** [comment]
I wanted to give this one a go with #2502 let me know what you think
