### ISSUE TITLE
Clicking the page background should hide open sub menus

### ISSUE THREAD

**Issue by manmotive** [WordPress/gutenberg#22626]
**Describe the bug**
Sub menus cannot be closed by clicking on the page background

**To reproduce**
1. Go to the new Navigation page
2. Click on a menu item with a sub menu so that the sub menu appears
3. Attempt to hide the sub menu by clicking 'off' the item (anywhere in the page background)
4. Notice the sub menu remains visible (it is only possible to hide the sub menu by selecting another block that does not have a sub menu)

**Expected behavior**
Any open sub menus should be closed when the page background is clicked

**Editor version (please complete the following information):**
- WordPress version: latest
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? plugin
- If the Gutenberg plugin is installed, which version is it?  8.2

**Comment by talldan** [comment]
I'm not sure if this is intentional! @adamziel I think you may have worked on this?

**Comment by tory-brown** [comment]
@manmotive is this issue still open to work on?

**Comment by manmotive** [comment]
I've just checked with the latest version and yes the sub menus are still tricky to close.

**Comment by talldan** [comment]
So just to run through how it works at the moment - if a link with a submenu is selected or one of the links in a submenu is selected, that submenu will appear open.

The issue seems to be that clicking the empty part of the navigation editor doesn't deselect the selected block. This could be something for us to add.

In the post editor when clicking the empty area, the document is selected and any selected block is deselected. I wonder if something similar should happen here, perhaps the main nav block should become selected as that sort of represents the document.

@shaunandrews what do you think?
