### ISSUE TITLE
Draggable Component Not Working

### ISSUE THREAD

**Issue by henzlym** [WordPress/gutenberg#22636]
I am trying to extend a plugin created to be able to drag and drop listed post from on position to another using the Draggable component but it seems not possible. I have had some success using the jQuery UI dependency to achieve the feature but it would be nice to use core Gutenberg components.

**Comment by talldan** [comment]
@henzlym There doesn't seem to be any information on what's not working in this issue, and so there's not a lot to go on. 

Draggable is used in several places in the editor and does seem to be working, so it'd be good to understand what the problem is.

There's an example in the storybook for this component that might help you with implementation:
https://wordpress.github.io/gutenberg/?path=/story/components-draggable--default

One thing to note is that it doesn't look like the component handles the drop behaviour, instead the element that the draggable is dropped on needs to handle that. There's a `DropZone` component, but that doesn't yet seem to have a storybook example for me to link to.

**Comment by talldan** [comment]
Closing the issue as there hasn't been a response.
