### ISSUE TITLE
PHP notice in the site editor

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#22800]
**Describe the bug**
With 8.2.0 and later, this notice is showing in the site editor
`Notice: Undefined index: front-page in /var/www/html/wp-content/plugins/gutenberg/lib/edit-site-page.php on line 162`

https://github.com/WordPress/gutenberg/blob/master/lib/edit-site-page.php#L162

**To reproduce**
1. Install Gutenberg
2. Enable full site editing
3. Enable a theme that has support for full site editing. 
https://github.com/WordPress/theme-experiments
4. Open the site editor.
5. See PHP notice

**Expected behavior**
I expect experimental features to change often, but not be broken in the plugin releases. :)

Editor version (please complete the following information):
WordPress version: 5.4.1
Gutenberg:  8.2.0,  8.2.1

PHP version: 7.3.13

Desktop (please complete the following information):
Windows 10
Chrome version: 83.0.4103.61

**Comment by youknowriad** [comment]
Maybe related to this  https://github.com/WordPress/gutenberg/pull/21980/files#r435217075

cc  @epiqueras @noahtallen @ockham

**Comment by epiqueras** [comment]
You need to have at least an `index.html` block template to fall back to for this to work.

**Comment by ockham** [comment]
My bad! I'll work on a fix tomorrow.

**Comment by carolinan** [comment]
Requiring and index.html makes sense considering the template hierarchy, but the error shows when front-page.html is missing, not when index.html is missing.

**Comment by ockham** [comment]
To repro this:
- There shouldn't be any `wp_template` CPTs (neither published nor `auto-draft`s) from previous Site Editor runs. (It's best to start with a fresh install.)
- Furthermore, the "Full Site Editing Demo Templates" checkbox in `/wp-admin/admin.php?page=gutenberg-experiments` _must not be ticked_.

**Comment by epiqueras** [comment]
>but the notice shows when front-page.html is missing, not when index.html is missing.

Yes, there is a bug there.

>Furthermore, the "Full Site Editing Demo Templates" checkbox in /wp-admin/admin.php?page=gutenberg-experiments must not be ticked.

Doesn't that mean there isn't an `index.html` template? Or are you using a theme that provides one? If that's the case, then the error is in how theme provided files are being looked up. It should be easy to debug that.

**Comment by ockham** [comment]
> > but the notice shows when front-page.html is missing, not when index.html is missing.
> 
> Yes, there is a bug there.

Right, this is one part of the problem. I think I'm setting the wrong key here: https://github.com/WordPress/gutenberg/blob/710373b254fbcd15d524afdeb31da0d93c4defd4/lib/edit-site-page.php#L158

This will use the name of the template that was _found_, not the name of the key that was looked for. So if we're looking up `front-page`, but don't find any template, and [thus fall](https://github.com/WordPress/gutenberg/blob/710373b254fbcd15d524afdeb31da0d93c4defd4/lib/template-loader.php#L226) back to `index`, the template will be stored under the `index` key, rather than the front-end one.

I think the fix for this is to use the template we were looking for as key:

```diff
diff --git a/lib/edit-site-page.php b/lib/edit-site-page.php
index 817c3ef9cb..0dcaf92d6a 100644
--- a/lib/edit-site-page.php
+++ b/lib/edit-site-page.php
@@ -155,7 +155,7 @@ function gutenberg_edit_site_init( $hook ) {
 
                $current_template = gutenberg_find_template_post_and_parts( $template_type );
                if ( isset( $current_template ) ) {
-                       $template_ids[ $current_template['template_post']->post_name ] = $current_template['template_post']->ID;
+                       $template_ids[ $template_type ] = $current_template['template_post']->ID;
                        $template_part_ids = $template_part_ids + $current_template['template_part_ids'];
                }
        }
```

This should make the error go away when there's no `front-page.html`, but an `index.html` -- e.g. for [Twenty Twenty Blocks](https://github.com/WordPress/theme-experiments/tree/10e858358faca115a1ce4395e6e7edecdfe8c4c1/twentytwenty-blocks) :crossed_fingers: 

> > Furthermore, the "Full Site Editing Demo Templates" checkbox in /wp-admin/admin.php?page=gutenberg-experiments must not be ticked.
> 
> Doesn't that mean there isn't an `index.html` template? Or are you using a theme that provides one? If that's the case, then the error is in how theme provided files are being looked up. It should be easy to debug that.

The theme I was testing this with was Twenty Twenty (i.e. not the 'Blocks' version), so no `index.html`. I'm still getting the error about the missing `front-page` index with themes that don't come with block template, this will need separate fixing. I left a related note [here](https://github.com/WordPress/gutenberg/pull/22893#discussion_r436181505).

**Comment by epiqueras** [comment]
That fix makes sense. Let's ship it.

**Comment by ockham** [comment]
> That fix makes sense. Let's ship it.

Working on a PR that also addresses [this problem](https://github.com/WordPress/gutenberg/pull/22893#discussion_r436188403).
