### ISSUE TITLE
Extra spaces generated in figure HTML on some browsers creates revision diff spam

### ISSUE THREAD

**Issue by SeanDS** [WordPress/gutenberg#22886]
**Describe the bug**
Different browsers appear to save figure HTML with or without extra spaces before the closing `>` tag. This creates useless diff lines in the post revision admin screen:

![image](https://user-images.githubusercontent.com/5225190/83734310-573cb180-a63e-11ea-926d-8ebed448bb8c.png)

**To reproduce**
1. Create a post with a figure and caption in Opera.
2. Edit the post in Firefox, changing something else but not the figure.
3. Observe the revision created for the changes contains the above diff.

**Expected behavior**
Gutenberg should normalise whitespace across browsers to avoid generating diff lines like this that only add to the noise when looking at changes across revisions.

If Gutenberg cannot control the generated HTML, e.g. due to React or the DOM, then perhaps WordPress itself should do this normalisation.

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Default.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox 78.0a1

**Comment by andrewserong** [comment]
I'm just going through a few old issues to close out ones that might no longer be applicable. A lot has changed in the block editor since mid-2020, and retesting this one, it appears that I can't reproduce the issue:

* In Opera browser version 98.0.4759.39 (arm64) I created a post with an Image block, a caption, and a separate paragraph
* Over in Firefox 112.0.2 I opened that post and made a change to the paragraph in the post, and then saved the post.

In the revisions view, I see that the diff is correctly just the change to the paragraph block:

![image](https://github.com/WordPress/gutenberg/assets/14988353/aaf69df5-1146-4380-a0ba-17aa390d6bdb)

I'll close out this issue now, but feel free to re-open if the issue is still occurring.

**Comment by SeanDS** [comment]
Thanks @andrewserong I'll comment back here if I notice this issue again in the future.
