### ISSUE TITLE
TinyMCE Single with React

### ISSUE THREAD

**Issue by annaephox** [WordPress/gutenberg#229]
In addition to the [TinyMCE-per-block](https://wordpress.github.io/gutenberg/tinymce-per-block/) (prototype 2) vs [TinyMCE-single](https://wordpress.github.io/gutenberg/tinymce-single/) (prototype 3) tradeoffs, another significant difference is the use of React (prototype 2) vs direct DOM manipulation (prototype 3) for the UI

Implement a branch of TinyMCE-single (prototype 3) using React
Include alternate UI from #215 

This will let us compare
1. TinyMCE-per-block + React   vs.  TinyMCE-single + React
2. Direct DOM UI  vs.  React UI

![demo-ephox](https://cloud.githubusercontent.com/assets/25762760/23784843/24e59d28-05b0-11e7-9a94-3cd9816c4609.gif)

**Comment by intronic** [comment]
I definitely found it quicker and easier to prototype different alternative UI options using React.

**Comment by prototypo** [comment]
This seems like the best of both worlds: React plus a single TinyMCE.

**Comment by prototypo** [comment]
Anna has added a video of the (still nascent) prototype in action in [#215](https://github.com/WordPress/gutenberg/issues/215)

**Comment by jasmussen** [comment]
CC: @dmsnell because I know he's voiced some thoughts on using React in WordPress.

> Anna has added a video of the (still nascent) prototype in action in #215

@prototypo Where does this prototype live?

In order to minimize duplicate work it would be nice for development of any prototypes to happen in the open, especially as currently we are planning only two technical prototypes that are already underway, both adhering to the UI baseline. In general, prototyping work in this phase should ideally either be part of those two technical prototypes, or be separate UI-only prototypes (GIFs, mockups, fiddles, Marvel click-through's) to explore various solutions to tickets labelled Design.

**Comment by dmsnell** [comment]
> voiced some thoughts on using React in WordPress

some muddled concerns that probably aren't that big a deal at this point. if we wrap something in React we could likely just as easily wrap it in a Web Component or some other _completely free_ system that certain businesses and organizations wouldn't shy away from

**Comment by intronic** [comment]
I take the point about React. In the above description; 

   s/React/some-virtual-dom-based-declarative-model/g

And the argument stands. React is already being used in prototype #2 so we thought to try it to compare & contrast vs the direct-mutation model, given the prototype nature.

There are other completely free alternatives that are along the same lines, some even fairy drop-in replacements at the api level.

**Comment by intronic** [comment]
Hi @jasmussen,

It is in the open, but just not easily discoverable for some reason. It seems our accounts maybe aren't associated with the project or something; we dont come up in  at-mentions for instance. 

Maurizio ([mimo84](https://github.com/mimo84/gutenberg)) & I ([intronic](https://github.com/intronic/gutenberg)) forked from the Ephox gutenberg fork (just a few days ago) since at this stage we are still learning the gutenberg code & goals. 

Its very exploratory right now as we are figuring out how the two prototypes are being put together. Once we have something concrete sorted we'll set up a PR. Its just that we're not there yet.

Cheers,
M

**Comment by prototypo** [comment]
@jasmussen The prototype is being worked in a fork of gutenberg at [https://github.com/ephox/gutenberg](https://github.com/ephox/gutenberg). But @intronic is right about org permissions; we'll have a look at that on Monday our time. Sorry for the trouble.

Please expect a PR soonest, probably early next week.

**Comment by jasmussen** [comment]
@intronic @prototypo I wasn't aware you didn't already have commit access or other privileges here, we can get those for you easily. You should've just asked.

**Comment by intronic** [comment]
@jasmussen @prototypo  - on my part, honestly, my first goal was to get my head around all the moving parts in gutenberg. 

There are a lot of parts, moving very fast. We'll catch up & integrate ourselves v. soon  :)

**Comment by aduth** [comment]
>And the argument stands. React is already being used in prototype 2 so we thought to try it to compare & contrast vs the direct-mutation model, given the prototype nature.

Not that it makes much difference to the discussion, but worth clarifying that it's [an abstraction of React](https://github.com/WordPress/gutenberg/blob/ad0a60c44df92d78a38834d2576e8efe4ab839e6/tinymce-per-block/src/blocks/heading-block/form.js#L4) (had even [previously not used `react` proper](https://github.com/WordPress/gutenberg/commit/01f2c86dcd24a7a23b0fd16e2d5f93bd3266c821#diff-dbd47a1a29f1ee343ad0536f8f97f6a8)), for the point of considering whether it makes sense to have flexibility in swapping the underlying implementation; for example, perhaps one of the [`hyperscript`](https://github.com/hyperhype/hyperscript) sort which is mostly compatible in its APIs but not virtualized.

**Comment by jasmussen** [comment]
Merged in the prototype. Let's take the learnings we got from that prototype and either keep them in mind as we work on existing tickets, or open new ones if there were particularly valuable take-aways not yet ticketed.
