### ISSUE TITLE
new Image Block Bug

### ISSUE THREAD

**Issue by RickorDD** [WordPress/gutenberg#22979]
I found Mathias and Matt's presentation on the new image block very good. Do you already have a ticket for this bug?

![Git](https://user-images.githubusercontent.com/6922544/83965291-e3efa580-a8b2-11ea-9270-93121b6fec20.png)

**Comment by paaljoachim** [comment]
Hey @RickorDD 

I have not seen that bug before.
We need to know which browser and a lot more.
Please go through and answer these steps which are listed when filling out a bug report.

**Describe the bug**
A clear and concise description of what the bug is.

**To reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"]
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by RickorDD** [comment]
New Issue

https://github.com/WordPress/gutenberg/issues/22984
