### ISSUE TITLE
The classic block doesn't work on the Site Editor Page

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#23086]
<img width="661" alt="Capture d’écran 2020-06-11 à 11 15 30 AM" src="https://user-images.githubusercontent.com/272444/84373805-fe888e00-abd4-11ea-9ef5-e736f29143e2.png">

TinyMCE might not be loaded properly.

**Comment by mtias** [comment]
It might make sense to disable it there for now.

**Comment by youknowriad** [comment]
@mtias Not sure we can, I only noticed this because I had an existing page using it and I tried to load that page in the site editor.

**Comment by itsjusteileen** [comment]
From a documentation perspective @youknowriad, would we say that the classic block would or would not be expected to work in FSE.

**Comment by zaguiini** [comment]
So wouldn't it be better to hide the block instead of displaying it on the list? It's still a problem...

**Comment by Mamaduka** [comment]
I'm removing this issue from WP 5.9 project board since RC1 was released last night.

Let's try and land a fix for this in a minor release.

**Comment by Addison-Stavlo** [comment]
👋  I see this is on the 5.9.x todo list, sounds like we need to revisit and reprioritize?

**Comment by annezazu** [comment]
Tested this with 14.1 RC1 and an error occurs. Adding to 6.1 board. I think we should remove this from usage in the Site Editor until there's a fix or a more well thought out solution cc @michalczaplinski @ockham as a heads up.

**Comment by talldan** [comment]
A possible option might be making a new 'freeform' block. I would envisage it having a preview of the contents and a 'Convert to blocks' button that's visible when selected. The trade off would be that the block probably wouldn't be editable, but it would at least be better than an error.

For some history, the widget editors tried using the html block as the freeform block instead of the classic block, but there were a couple of issues. The first being that the block delimiter isn't rendered for a freeform block, so plugins are unable to extend the html block attributes in the widget editors. The second issue is that autop runs on freeform content, so any html blocks get unwanted `<p>` tags. There was a fix for this in the widget editors - https://github.com/WordPress/gutenberg/pull/42623, but it may be better to use a separate new block.

**Comment by ockham** [comment]
Assigning to @michalczaplinski -- Michal will look into disabling the block in the Site Editor 🙂

**Comment by michalczaplinski** [comment]
I've opened https://github.com/WordPress/gutenberg/pull/44554 to hide the block when in the Site Editor but I ran out of time to fix it completely today (more details in the PR).

**Comment by michalczaplinski** [comment]
The Classic block is now hidden from the inserter in the Site Editor: https://github.com/WordPress/gutenberg/pull/44554
