### ISSUE TITLE
Should styles/padding sidebar panels be available for placeholders?

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#23122]
We don't show block settings for blocks that utilize placeholders (Image & Cover for example).

Should we also not show the block's Styles panel, and incoming Spacing panel? 

The Styles and Spacing panels do not perform any action at that point; only when the placeholder's requirement is fulfilled. 

**Screenshots**
<img width="1308" alt="Screen Shot 2020-06-12 at 3 07 50 PM" src="https://user-images.githubusercontent.com/1813435/84537855-8eeecd80-acbe-11ea-8418-ba3f83753b62.png">
<img width="1205" alt="Screen Shot 2020-06-12 at 3 09 17 PM" src="https://user-images.githubusercontent.com/1813435/84538005-d5442c80-acbe-11ea-9875-a5d60354e8a2.png">

**Comment by enriquesanchez** [comment]
Agreed these settings should not be available while the block is in its placeholder state.

**Comment by getsource** [comment]
It looks like a decision was made here not to fix this issue, because the behavior is dependent on user workflows, and individual Blocks:
https://github.com/WordPress/gutenberg/pull/33823#issuecomment-892443035
https://github.com/WordPress/gutenberg/pull/33823#issuecomment-900913909

Should this issue be closed based on that?
