### ISSUE TITLE
Add method to remove image/revert to placeholder state

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#23125]
The core Gallery block (and a few third party image-related blocks) have a method to easily remove an image. In the spirit of consistency, let's consider adding the same delete/remove action that the Gallery block has, to the Image block. 

This would also resolve the issue that the word "Replace" may be too long of a label to include in the toolbar when translated. We could remove the "Replace" and the popover entirely. When clicking on the "X" the block could revert to the placeholder state, which is a familiar experience. 

**Describe the solution you'd like**
<img width="674" alt="image" src="https://user-images.githubusercontent.com/1813435/84547705-1265ea00-acd2-11ea-877d-46ba77f2930d.png">

Here's a screenshot of the Gallery block: 
<img width="1327" alt="gallery" src="https://user-images.githubusercontent.com/1813435/84548026-c10a2a80-acd2-11ea-8799-719dc60d8980.png">

**Comment by mapk** [comment]
Chatted about this in the [Design Triage today in Slack](https://wordpress.slack.com/archives/C02S78ZAL/p1597767841420200).

While the `x` obviously removes the image from the Gallery block, it doesn't remove the Gallery block itself. It may be confusing for the user to click the `x` to remove the image, but still see a placeholder for the Image block. Or do we remove the Image block completely when they click `x`?

I would assume the user isn't thinking in terms of a block while editing this content. So when clicking the `x` they may be expecting the image to be removed from the content of their document.

IMO, I think it's best to keep the "Replace" because it's clear what's happening, and not pursue this. I'll close this for now, but if you want to reopen, please feel free to.
