### ISSUE TITLE
Remove the SEO settings block from the nav block

### ISSUE THREAD

**Issue by jdevalk** [WordPress/gutenberg#23153]
**Describe the bug**
I was testing the Nav block and saw the SEO settings block:

<img width="285" alt="Screenshot 2020-06-15 at 11 33 22" src="https://user-images.githubusercontent.com/487629/84642058-3ad12c80-aefc-11ea-9a0a-ee91144f00c3.png">

I think it's problematic to add this to core. The wording is already wrong (as this is a hint and not a "rule", like `robots.txt` is) and it links to a Codex page that is outdated. 

We've seen over the past few months that different SEO plugins chose to word these options differently, because of a difference of opinion in how this should work and also a difference in how they perceive their audience. 

Also, the _large_ majority of WordPress users should _not_ use this toggle, like, ever. Which makes it risky to add this.

I strongly feel therefor that this should be plugin territory and should _not_ be dealt with in core. If we do decide to ship this in core, the wording should be changed, the linked-to page should be updated and it should still become filterable.

**To reproduce**
1. Open a post
2. Insert a Navigation block
3. Add a link and select it
4. See the SEO settings block in the block sidebar

**Expected behavior**
Don't have a default SEO settings block, allow plugins to filter and add a block like this themselves.

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? 8.3

**Comment by aristath** [comment]
Worth noting here: `nofollow` may be used for SEO purposes, but traditionally is also accompanied by `noopener noreferrer` which are mostly security & privacy-related
We could remove the "SEO" section - as we should, but not the setting itself... Perhaps changing it to include the other 2 properties as well - and tweaking the description would be preferable?

**Comment by jdevalk** [comment]
Couple of remarks:

* I don't think these things have anything to do with each other, `noopener` is added to plenty of links in WordPress without user interaction.
* `noreferrer` was only added to `noopener` because for a while, Firefox didn't support `noopener`, you shouldn't use that anymore, it breaks referrer analytics.

**Comment by aristath** [comment]
Didn't know that, thanks!

**Comment by noisysocks** [comment]
I dug into why this attribute was added and found https://github.com/WordPress/gutenberg/issues/13690#issuecomment-460986534.

We need to support setting the `rel` attribute in some capacity so that we maintain backwards compatibility with the existing `nav-menus.php` screen which, when you enable it in Screen Options, lets you set the `rel` attribute using a text field.

<img width="429" alt="Screen Shot 2020-07-07 at 11 25 22" src="https://user-images.githubusercontent.com/612155/86687900-f6dbce00-c048-11ea-9f71-d170ee603a79.png">

It's also worth noting that the Buttons block supports setting the `rel` attribute using a text field.

<img width="287" alt="Screen Shot 2020-07-07 at 11 57 42" src="https://user-images.githubusercontent.com/612155/86688122-28ed3000-c049-11ea-8940-a6530b81a85a.png">

---

Instead of removing the _SEO settings_ panel, let's replace it with the same _Link settings_ panel that the Buttons block has.

**Comment by adamziel** [comment]
Great idea! See the updated version of https://github.com/WordPress/gutenberg/pull/23682

<img width="408" alt="Zrzut ekranu 2020-07-7 o 16 45 06" src="https://user-images.githubusercontent.com/205419/86798608-40d8aa00-c071-11ea-9f45-2a0f537c1688.png">
