### ISSUE TITLE
Navigation block: Add a way to control spacing

### ISSUE THREAD

**Issue by alaczek** [WordPress/gutenberg#23294]
Site headers and footers often require tight control over spacing (typically a combination of padding, margin, and line-height) to achieve the desired look. Ideally, we'd have some way of controlling both vertical and horizontal spacing.

**Vertical Spacing**
Vertical spacing comes into play in many popular header design patterns, where navigation is displayed on the same line as site title and /or tagline:

![image](https://user-images.githubusercontent.com/4550351/85089426-f8725d00-b225-11ea-83d2-c23f04e611c3.png)

![image](https://user-images.githubusercontent.com/4550351/85089577-53a44f80-b226-11ea-96d8-967fe7b3c982.png)

![image](https://user-images.githubusercontent.com/4550351/85089634-79c9ef80-b226-11ea-92fd-f12031917666.png)

**Horizontal spacing**
Control over spacing between nav menu items is an important aspect of a site header design. It would enable us to create designs like these (hat tip to @iamtakashi for these):

![image](https://user-images.githubusercontent.com/4550351/85089745-bdbcf480-b226-11ea-8615-bc2ec4e52555.png)

![image](https://user-images.githubusercontent.com/4550351/85089961-4dfb3980-b227-11ea-8d34-44323fa337b7.png)

![image](https://user-images.githubusercontent.com/4550351/85090011-6c613500-b227-11ea-9325-5a0c8d6162ea.png)

**Comment by draganescu** [comment]
This issue has been discussed on Slack in the weekly Navigation Sync meeting. The resolution was `Needs Design` because it's a matter of how the overall editor experience is in relation to controls for padding and margins for blocks. 

Recently, the cover block has had padding controls (spacing) added. Should we reuse that for the navigation block?

**Comment by apeatling** [comment]
> Recently, the cover block has had padding controls (spacing) added. Should we reuse that for the navigation block?

I think the same controls should be used. Ideally all padding and margin controls are universal.

**Comment by draganescu** [comment]
Howdy @shaunandrews, I will remove this from the Navigation project as it is not a requirement of the editor.

**Comment by jasmussen** [comment]
You can now use space-between to control horizontal spacing:

<img width="1219" alt="Screenshot 2021-01-26 at 09 38 12" src="https://user-images.githubusercontent.com/1204802/105820748-3dc7eb80-5fba-11eb-8de5-e4dd7ba06900.png">

Would adding a line-height control, perhaps both to navigation and site logo / site title blocks help accomplish the vertical spacing issue?

**Comment by priethor** [comment]
Adding the line-height control would definitely help achieve many design patterns like the ones listed in the opening post in a more friendly way than adding vertical spacer controls before and after the navigation block. I think it's something worth adding.

**Comment by shaunandrews** [comment]
With the new space-between option, and the incoming updates to the spacer block (https://github.com/WordPress/gutenberg/pull/29133) I think we're pretty close to resolving this issue.

**Comment by jasmussen** [comment]
Since #29133 is merged, I'm closing this one. Please reopen, or open a new issue, if an aspect was missing.

<img width="702" alt="Screenshot 2021-03-15 at 12 40 29" src="https://user-images.githubusercontent.com/1204802/111148269-b5ae9d00-858b-11eb-817f-a1d02fdf5cf1.png">

<img width="869" alt="Screenshot 2021-03-15 at 12 40 54" src="https://user-images.githubusercontent.com/1204802/111148272-b6dfca00-858b-11eb-924a-193f4f090211.png">
