### ISSUE TITLE
Spacer/Interval block weird markup bug

### ISSUE THREAD

**Issue by aryabchenko** [WordPress/gutenberg#23334]
**Describe the bug**
While using spacer block I have much bigger space right before the block itself. The block has correct height as per html code, but all browsers (Chrome, Opera at least) shows big white space before (from 200 to 900 px in height)

**To reproduce**
I have no correct steps, the only two things I found:
1. Page should include  at least one interval/spacer block
2. This block should be somewhere in the top. I managed to get correct markup with interval block in the bottom of page.

**Expected behavior**
It should work the same as in editor

**Screenshots**
Unfortunately didn't took, but it looks like much bigger interval block and I see no extra code : one block ends then the next starts but a huge white space between in real browser.

**Editor version (please complete the following information):**
5.4.2 and 5.3.x are affected.
5.0.x and 5.2.7 are NOT affected.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser Chromium based, Opera
 - Version latest

**Smartphone (please complete the following information):**
hadn't checked

**Additional context**
I downgraded my site back to 5.2.7, so I cannot find more details or test smth, I cannot upgrade it back and break all the pages again. If you can reproduce - it would be awesome, if not - just close it.

**Comment by annezazu** [comment]
@aryabchenko thanks for reaching out about this! I just tried to replicate this using WordPress 5.5  RC and Gutenberg 8.6.1 but wasn't able to do so. I then tried to replicate with WordPress 5.4.2 but wasn't able to do so. Here's a video for context: https://cloudup.com/c70l8589U4y

If you're able to replicate, please share! Otherwise, I'm going to close this out for now since I can't replicate.
