### ISSUE TITLE
Add most used blocks dial buttons directly on empty editor page

### ISSUE THREAD

**Issue by alexvornoffice** [WordPress/gutenberg#23420]
**Is your feature request related to a problem? Please describe.**
When you want to add something, you need to press: + then select a block
Why not make it easier and have allready most used blocks buttons on the editor? 
"Save a click!"

**Describe the solution you'd like**
A have attached an image showing the solution.

**Describe alternatives you've considered**
text

![gutenberg_add_new_block](https://user-images.githubusercontent.com/1689187/85552536-c13beb80-b62b-11ea-9aa1-8dddbee9b8ef.png)

**Comment by paaljoachim** [comment]
Hi @alexvornoffice 

Thank you for the suggestion! It is appreciated!
One of the goals for the backend Gutenberg layout screen is to keep it as close as possible to what one would see on the frontend. So when no blocks are selected in the backend one gets a kind of preview directly in the backend screen of what it looks like on the frontend.

Adding 9 block icons such as you mention in your suggestion could create a bigger difference from backend to frontend. There would be extra visuals creating a kind of disturbance of what the layout looks like. There is a less visual disturbance with just clicking enter and seeing the "Start writing....." text.

I will also ping in @mapk Mark to also give some quick feedback.

**Comment by mapk** [comment]
Thanks for the ping, @paaljoachim. We actually used to show the last 3 block icons or something similar next to the inline inserter. We opted to remove them because the icons provided more distraction. There is a desire to allow the Inserter to be open at all times. This issue in particular talks about it. https://github.com/WordPress/gutenberg/issues/26223

I believe that would be a great solution that would also address this issue. Let's close this one in favor of the other.
