### ISSUE TITLE
I find a error and JSON error

### ISSUE THREAD

**Issue by MYIG** [WordPress/gutenberg#23473]
![gutenberg json error and](https://user-images.githubusercontent.com/44285360/85743649-2f250780-b73f-11ea-9763-4eef181d53d1.jpg)
![gutenberg json error and 2](https://user-images.githubusercontent.com/44285360/85743660-30eecb00-b73f-11ea-957d-15b918c499c6.jpg)

There is a error 'the response is not a valid JSON response'. I searched google and its solution is using classic error... I can't publish my post now. Please fix it...

And I can see the error. You may see that my top bar in that picture is shorter than normal top bar..

**Comment by annezazu** [comment]
@MYIG Thanks for reaching out here! Of note, this repository is dedicated to building gutenberg and not for support requests. Your best bet is to head to the [support forums to get help](https://wordpress.org/support/). Be sure to include information like Gutenberg version (if applicable), WordPress version, any plugins installed and active, etc. Closing this out for now but you're welcome to re-open if you believe this issue is related to core Gutenberg development.
