### ISSUE TITLE
Qs about Block Directory

### ISSUE THREAD

**Issue by nickhamze** [WordPress/gutenberg#23527]
How is the search suppose to work? I wanted to try it out so I tried searching for one of my own plugins, Lazy Lists, that as far as I know is in the [block directory](https://wordpress.org/plugins/browse/block/). 

First I search for the exact block name, I know no one will do that but I wanted to make sure it turned up. When I do that I just see this:
<img width="352" alt="Screen Shot 2020-06-26 at 4 32 41 PM" src="https://user-images.githubusercontent.com/158918/85902886-ad7abb80-b7ca-11ea-8c29-de2dad62c178.png">

Not only was I surprised that I didn't see my block I was also surprised that it just said "No blocks found in your Library". Did it even search the block directory? From that message it's hard to tell. Then I try one of the tags "list" and I see this:
<img width="350" alt="Screen Shot 2020-06-26 at 4 34 54 PM" src="https://user-images.githubusercontent.com/158918/85903066-119d7f80-b7cb-11ea-9821-1b4fc1741a87.png">

Which finds a core blocks but there is still no indication that you tried to search the block directory and didn't find anything. 

It's a bit confusing to me. I didn't even know that searching would help me find blocks elsewhere as there is no indication that a block directory even exists. Currently (in WP 5.4) that search only searches for blocks you already have installed. I never search so I'd never have discovered the block directory in its current form. I feel like some indication is necessary to let people know that the directory exists and you need to type a search term in if you want to find more blocks.

**Comment by talldan** [comment]
@nickhamze Thanks for your feedback.

It looks like Lazy Lists enhances the core List block rather than providing a separate custom block, so I don't think it could be considered a block in the block directory and the search probably wouldn't work because of that. 

My understanding is that the block directory search is initiated when no currently installed or core blocks match the search term. The feature isn't present in WP 5.4, but will be in WP 5.5 and is also available in the Gutenberg plugin.

@StevenDufresne or @ryelle would be able to double-check my understanding.

I tried some of the other blocks from the link you provided and the search worked.

> I feel like some indication is necessary to let people know that the directory exists and you need to type a search term in if you want to find more blocks.

That's good feedback. The feature is under active development, so gathering feedback from user testing will be useful.

**Comment by StevenDufresne** [comment]
@nickhamze Hi!

@talldan is correct in that the block directory expects blocks to register a custom block. Blocks that do not, are currently being filtered out at the API level. 

The implementation is based on the [block directory guidelines](https://github.com/WordPress/wporg-plugin-guidelines/pull/68/files). If you have any feedback on the guidelines, please join the conversation in that pull request.

In terms the discoverability of blocks, I have brought up the same concern in https://github.com/WordPress/gutenberg/issues/22149#issuecomment-627794527. I expect to cycle back and get more movement here soon.

**Comment by nickhamze** [comment]
@StevenDufresne and @talldan Oh, I misunderstood. I thought that the content on the block directory could be found [here](https://wordpress.org/plugins/browse/block/) and since lazy list was present there it should have shown up in search.

**Comment by talldan** [comment]
No worries @nickhamze, hopefully that answers any questions you have. 

I'll close the issue now.
