### ISSUE TITLE
Edit with Elementor button no longer visible

### ISSUE THREAD

**Issue by gvmweb12** [WordPress/gutenberg#23645]
**Describe the bug**

hi, when gutenberg plugin activated elementor page builder is no longrer available from add new page or new post .
block editor only is available from edit page. ( usually you have option to edit page with elementor) 
but this option disapears whn glutenberg plugin is activated.
**To reproduce**
1. Go to '...'install elementor ( free version is doable)
2. Click on '....'check add new page edit  options ( see elementor button)
3. Scroll down to '....'install glutenberg plugin and activate
4. See error... open add new page....elementor option no longer available, only block editor.

**Expected behavior**

expect to have a choice of which editor to use.

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Does the website has Gutenberg plugin installed, ##### problem with plugin only#######
or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"]
- If the Gutenberg plugin is installed, which version is it? ###latest 8.40
elementor latest
Elementor v2.9.13
Elementor Pro v2.10.3
( all are new insatalls on a demo test site )
**Desktop (please complete the following information):**
 - OS: [e.g. win10
 - Browser chrome, 
 -  Version 83.0.4103.116

**Smartphone (please complete the following information):**

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by talldan** [comment]
@gvmweb12 I'd recommend reaching out to elementor devs as this may be something that can be fixed on their side.

As far as I know, there's not an official API that's used to add the 'Edit with Elementor' button, so not sure what can be done on the Gutenberg side.

**Comment by gvmweb12** [comment]
Hi,
No problems,
I expect page builders will be a thing of the past soon anyway..
With Gutenberg and addon plugins like uag and stackable etc...
Like this direction, will make things do much easier and lighter with less
plugins.
Keep up the good work

Cheers
Stuart

**Comment by f-lungov** [comment]
@talldan it looks like the button disappeared after a Gutenberg update, not Elementor's. Isn't it worth a look to find out what change caused it?

**Comment by talldan** [comment]
Hey @f-lungov, I did have a look. 

As mentioned above, from what I can tell there's no official API to add a button to this part of the editor. 

Elementor would probably be attaching it to the corresponding DOM element in the toolbar, which when it was working was the element with the class `edit-post-header-toolbar`. In the latest versions of Gutenberg, this element is still there, so it's unclear to me why this would have stopped working. There are no errors in the console, so no clue to me what might be going wrong.

One of the Elementor developers would probably have a better idea of how this works on their side, which is why I recommended reaching out to them..

**Comment by talldan** [comment]
I did some more digging and discovered that this is related to recent changes to improve the accessibility for the editor toolbar.

The block editor toolbar has some code that detects whether the toolbar is built using only accessible components:
https://github.com/WordPress/gutenberg/blob/818d0458c3fa8845694e57247ed06d135a581a31/packages/block-editor/src/components/navigable-toolbar/index.js#L86

This code is updated by a DOM MutationObserver. It works like this:
1. When the DOM for toolbar is modified, this code check whether the toolbar is built using only accessible components.
2. If it's built using only accessible components, `isAccessibleToolbar` is set to `true`, otherwise it's set to `false`.
3. When this value changes from `true` to `false` or vice versa, the DOM for the toolbar is replaced (the toolbar is dynamically switched from an accessible one to a legacy one).

When Elementor attaches its button to the toolbar it triggers this code, `isAccessibleToolbar` changes from `true` to `false`, and the DOM for the toolbar gets replaced, resulting in the Elementor button no longer being present.

**Comment by f-lungov** [comment]
Hi @talldan , thanks for your investigating!

I have contacted their support and had no response yet. It looks like they have been getting a lot of tickets, hopefully they will have time to make changes on their end before this Gutenberg change is merged into core. For now I have just deactivated Gutenberg, but this solution will only work for so long until I (and millions of people) have to choose between Elementor and WP 5.5.

**Comment by f-lungov** [comment]
Just one more thing. The button we are talking about is very bold and hard to miss. It may be worth checking out why your code is flagging it non-accessible. It looks to me like a false positive, and it may be happening with components from other plugins too.

**Comment by mcsf** [comment]
> The button we are talking about is very bold and hard to miss.
> It may be worth checking out why your code is flagging it non-accessible. It looks to me like a false positive, and it may be happening with components from other plugins too.

Visibility is a factor for accessibility, but in this case — and often — the concern is the focusability or "tabbability" of the elements. Indeed, the criterion in use is:

https://github.com/WordPress/gutenberg/blob/b87d66640b5e87bfd460166da57c2347f09d9afc/packages/block-editor/src/components/navigable-toolbar/index.js#L25-L28

where `elements` is the found tabbable elements attached to the toolbar. So the characteristic (whether an element inside the toolbar is a proper and accessible _toolbar item_ is — currently and experimentally — self-reported.

**Comment by f-lungov** [comment]
@mcsf I see, it makes sense. Hopefully the element will be tabbable before WP 5.5.

**Comment by paaljoachim** [comment]
Is this issue still valid @f-lungov and @gvmweb12 ?

I assume by now that Elementor has fixed this issue.

**Comment by f-lungov** [comment]
@paaljoachim , yes they fixed it before WP 5.5.

**Comment by paaljoachim** [comment]
I will then go ahead and close this issue.
