### ISSUE TITLE
Misleading More text after saving an empty text

### ISSUE THREAD

**Issue by ntsekouras** [WordPress/gutenberg#23780]
**Describe the bug**
With the current behaviour of `More` block, if we change the text to an empty string and update, we will save an `undefined` value. This leads into taking the default value of `More` block that is `Continue Reading`.

So if we refresh the page later will show the JS default value: `Read more` but actually doesn't have a value.

**To reproduce**
1. Go to a post and add a `More` block
2. Empty the `More` text and update
3. Refresh the page and watch that `Read more` is shown
4. View the post's category page in front end and watch that `Continue Reading` is shown

**Expected behavior**
A user shouldn't be able to save an empty text for `More` block. On focusing out the input, it should change to the default JS value `Read more`.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/16275880/86889331-3ddac980-c104-11ea-91b2-b895aad518dd.png)
When we save.

![Screenshot(2)](https://user-images.githubusercontent.com/16275880/86889319-3adfd900-c104-11ea-8b46-cc893d743908.png)
After reloading the post

![Screenshot(1)](https://user-images.githubusercontent.com/16275880/86889327-3ca99c80-c104-11ea-9e91-fe9c48047592.png)
What is shown in front-end

**Comment by mcsf** [comment]
> Steps to reproduce the behavior:
> 
> 1. Go to a post and add a `More` block
> 2. **Empty the `More` text and update**
> 3. Refresh the page and watch that `Read more` is shown 
> 4. View the post's category page in front end and watch that `Continue Reading` is shown

As a user, what did you expect to happen in the editor once you emptied the text input? And in the front end?

**Comment by mcsf** [comment]
The More block was added fairly early on in the development of Gutenberg and it sought to mimic the functionality provided with TinyMCE. This explains why it's such a simple block and why its editor view is so detached from the front-end result.

It's also a block that doesn't tend to receive a lot of attention, and so it has remained like this for a long time.

More importantly, until Phase 2, Gutenberg has only concerned itself with the `post_content`. Thus, it made sense to render More as a very discreet line, because the rendered post will have no visual cue at all.

However, as we move into full-site editing (FSE) territory, it will probably be good to revisit More in such a way that it can behave differently depending on the editing content:

* When editing a single post (like today), More should merely appear as a dashed line (like today).
* In FSE, when editing a page that has a list of posts (e.g. an archive view), the More blocks corresponding to each post should be rendered faithfully (i.e. an actual button matching the theme).
* The same situation applies when using the [Query block ](https://github.com/WordPress/gutenberg/pull/22199): it should be possible to render faithful More blocks among the blocks nested in Query.

Ideally, the FSE work with More in mind would make it easier to determine what the server-side `$more_link_text` will be in the case of an absent `customText` value for the More block. And then we won't have to hack the value of `customText` as initially attempted in #23758. :)

**Comment by ntsekouras** [comment]
>As a user, what did you expect to happen in the editor once you emptied the text input? And in the front end?

Probably be empty both at admin and front-end.

**Comment by ntsekouras** [comment]
I'm closing this issue as it seems FSE development/evolution is a better place to revisit, maybe reinvent, as described by @mcsf  above.
