### ISSUE TITLE
Adding custom attribute to freeform (classic) block

### ISSUE THREAD

**Issue by Elkex** [WordPress/gutenberg#23865]
I created a custom attribute that will append a margin class to every Gutenberg custom & core block through a SelectControl field with several options in the sidebar. This works perfectly for most blocks, but not for the **freeform block**.

The property appears in the sidebar when the freeform block was chosen, but it is not possible to save the value of this attribute when I save the page & reload the editor in the browser.

The values does appear on the frontend once the block is being rendered, but if we then choose to change the size of the margin, it sort of puts a second wrapper around this block and appends both margin classes.

The value is being appended through a filter and the "createHigherOrderComponent".

Does anyone know a solution to this problem on how we can save this custom attribute?

![Screenshot 2020-07-10 at 12 58 35](https://user-images.githubusercontent.com/17483344/87147560-1bd07b00-c2ad-11ea-8166-167cad28cc8f.png)

**Comment by talldan** [comment]
@Elkex Thanks for reaching out. This is due to the way the classic/freeform block is designed.

Other blocks serialize their attributes to an HTML comment. The comment serves the purpose of marking the block boundary as well as a place to store attribute values:
```html
<!-- wp:heading {"fontSize":"large","style":{"typography":{"lineHeight":"2"}}} -->
<h2 class="has-large-font-size" style="line-height:2">test</h2>
<!-- /wp:heading -->
```

But the freeform block is designed to handle any other content in a post that doesn't have these comments. Often that's content created in other editors like the classic editor. As such, it doesn't have the HTML comment boundaries and can't save attributes.

As this block is designed to be a fallback or a way to handle legacy content, I don't think that's something that will change in future.

Hopefully that answers the question, but let me know if not.
