### ISSUE TITLE
Image block: Resized image with no defined alignment appears centered in the editor instead of left-aligned (WP 5.5 beta2)

### ISSUE THREAD

**Issue by dianeco** [WordPress/gutenberg#23986]
**Steps to reproduce**

1. Inside the editor, add an image.
2. Resize it to a smaller size using the resize handles.
3. Observe that the image appears centered instead of left-aligned while it appears left-aligned on the front-end.

![resize-image-align](https://user-images.githubusercontent.com/44895380/87647425-a4d52f80-c74f-11ea-934d-32b588317a07.gif)

Tested using WordPress 5.5 beta 2 and WP 5.4.2 + Gutenberg 8.5.1.
Tried with Twenty Twenty & Twenty Seventeen.

**Comment by pagelab** [comment]
I can reproduce this on version 5.5-beta2-48491 with the default editor styles applied.

**Comment by annezazu** [comment]
Replicated with Gutenberg 8.6.1.

**Comment by merapi** [comment]
@tellthemachines @annezazu The resized image should be centered in the output/FE, correct? (not left-aligned in the editor).

**Comment by annezazu** [comment]
Right now, seems like the solution is either: 
1. When resizing an image, have it default to whatever the alignment is set to (this means defaulting to the left).
2. If it is naturally centered, make sure it's reflected on the front end.

Not quite sure what's intended here! Might need to bring in some designers.

**Comment by tellthemachines** [comment]
My understanding of the issue (which I was also able to reproduce) is that an image with no set alignment (defaulting to left-aligned) shouldn't change alignment when resized (it should stay left, in editor and front-end). Instead, what happens is the image suddenly appears center-aligned after resizing.

**Comment by merapi** [comment]
> (this means defaulting to the left)
> (defaulting to left-aligned)

@annezazu @tellthemachines 

I think it's center by default (looking at the icon)?

Newly inserted image:
![image](https://user-images.githubusercontent.com/21036224/96274949-6874d200-0fd1-11eb-8cb7-af08d8ae2bea.png)

After resizing + left-aligned at the bottom:
![image](https://user-images.githubusercontent.com/21036224/96274708-2186dc80-0fd1-11eb-96f3-078c24e3f51d.png)

**Comment by tellthemachines** [comment]
> I think it's center by default (looking at the icon)?

That's the bug! It should be left-aligned by default after resizing. That's how it worked before 5.5.

**Comment by merapi** [comment]
Checked on 5.4, now I get it.
So just to sum up: we have this 6th option of alignment ("undefined" - when no option is selected, that aligns to the left of the text content and it's different than the left alignment from the options) that confusingly shows the center alignment icon when it's active. Don't we want to fix it? by either adding another alignment option (that will be active from the start) or making one of the current options a default one? (not the "undefined" one)

**Comment by talldan** [comment]
I've put together a fix - #26376.

Did some debugging, it isn't related to the alignment options. All the blocks that have alignments have that align center icon by default, but it doesn't mean that the actual alignment is center. Table and cover are other examples.

This is more of a CSS issue. The image block's wrapping `figure` tag, is styled as `display: table;` (a hack to make the caption center properly). `display: table` makes the wrapper collapse to the content size when the contents are smaller, rather than take up the full-width like it would if it were `display: block`.

At the same time all blocks have a `margin: auto` applied to their wrappers, which has the unwanted side-effect of centering the image:
https://github.com/WordPress/gutenberg/blob/55bf7ec3b7c032df68437b4605673c13fdf2c6cf/packages/block-editor/src/components/block-list/style.scss#L305-L309
