### ISSUE TITLE
[Navigation Block] Add introductory text to adding a new menu item

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#24007]
**Describe the bug**

Currently, when adding a new item to the menu, there's no prompt or introductory text to help nudge the user along. With work being done to expand the number of types of blocks that can be added to the Navigation Block, there should likely be some sort of explanation. Otherwise, it feels a bit like something is broken.

**To reproduce**
1. Open the editor
2. Add the navigation block
3. Select the + to add a new item. 

**Screenshots**

Here's a video of me talking through this issue (and others): https://cloudup.com/c1ChZfDf5ut

Navigation:
<img width="812" alt="Screen Shot 2020-07-16 at 1 48 08 PM" src="https://user-images.githubusercontent.com/26996883/87716076-27b3b580-c763-11ea-97dc-3dd0aa0b5483.png">

General block:
<img width="403" alt="Screen Shot 2020-07-16 at 1 51 52 PM" src="https://user-images.githubusercontent.com/26996883/87716079-297d7900-c763-11ea-92a7-a991cd7e6f6f.png">

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? 8.5.1

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 83.0.4103.116

**Comment by noahshrader** [comment]
Good catch!

1. I think your suggestion with adding a title to this makes sense to give context to the choices.
2. We should remove the "Browse All" button as there are only two options and opening the left sidebar is unnecessary as all options are show in the quick library.
3. From a dev standpoint, we should take another look at how we're styling elements within the library containers so that it degrades well (the removal of the search box completely collapses the top padding, as shown in your screenshots)

Attached is a super quick example of the added section heading:
![Navigation Options](https://user-images.githubusercontent.com/3665539/88938083-f05d0280-d252-11ea-8912-1c212ea1d463.png)

**Comment by MichaelArestad** [comment]
> Currently, when adding a new item to the menu, there's no prompt or introductory text to help nudge the user along. With work being done to expand the number of types of blocks that can be added to the Navigation Block, there should likely be some sort of explanation. Otherwise, it feels a bit like something is broken.

@annezazu is what Noah proposed what you are expecting or were you proposing something more like a walkthrough or popover with more information?

**Comment by annezazu** [comment]
Ah apologies. I reacted with a heart but should have used my words ;) I dig what Noah proposed as a minimalist way to lightly introduce this interaction. I wonder if even just saying "Options" is enough in case this kind of situation happens again where a limited set of blocks can be used in the interface. It could help create some nice consistency rather than having unique headers. 

Minor note: I definitely think Link should be listed before Search as adding repeated links seems far more likely than a bunch of search boxes.

**Comment by MichaelArestad** [comment]
In that case. I think Noah's mock works. Let's run with that.

**Comment by annezazu** [comment]
Sounds good to me!

**Comment by mtias** [comment]
It feels like the text could even expand a bit more instead of just being a heading. In any case, this seems like a good thing to support in the inserter API (a description? a tip? a heading?) that can be optionally added when blocks are restricted (i.e. when `allowedBlocks` is present). cc @youknowriad @pablohoneyhoney

**Comment by annezazu** [comment]
Noting the current experience as of Gutenberg 10.1.1 and WordPress 5.7: 
<img width="563" alt="Screen Shot 2021-03-15 at 6 35 04 PM" src="https://user-images.githubusercontent.com/26996883/111238692-2fab4a00-85bd-11eb-83d6-38e070073d34.png">

**Comment by annezazu** [comment]
Pulling in feedback from the [third call for testing for the FSE program](https://make.wordpress.org/test/2021/03/09/fse-program-testing-call-3-create-a-fun-custom-404-page/#comment-1416) from @paaljoachim:

> Adding a navigation. I added an existing menu but it contained only one link. Clicking to the right of the black square with a + in it I expect to be able to add a text link. But I have to click the black square. I am not able to select Posts or Pages. (That is probably because I have to click the Browse all button.) The Inserter add block panel shows up. With very limited options. Design and Widgets areas. I go back to the Navigation. Click to add a link. There I can add a post or page.

Helpful to think about the above context when/if this is addressed :)

**Comment by annezazu** [comment]
This feedback came up once more in the [sixth round of testing for the FSE Outreach Program](https://make.wordpress.org/test/2021/05/12/fse-program-testing-call-6-stick-the-landing-pages/): 

>Confusing: adding the pages to Navigation. I wouldn’t have known I needed to use the Page Link block if you hadn’t instructed me to do so.

I've even caught myself clicking + and then starting to type a page title forgetting to first select the Page Link block. This might just be something to adjust to but a visual prompt would go a long way.

**Comment by jasmussen** [comment]
I'm seeing this at the moment:

<img width="685" alt="Screenshot 2021-07-08 at 11 15 27" src="https://user-images.githubusercontent.com/1204802/124896552-d8067380-dfdd-11eb-8aed-969af99cc1ed.png">

What, if anything, does that mean for the original ticket as reported?

**Comment by mtias** [comment]
@jasmussen what I have in mind is some help text whenever you open the inserter in a restricted area that says "These are the blocks available to insert within the {ParentBlockName} block".

**Comment by jasmussen** [comment]
> whenever you open the inserter in a restricted area that says "These are the blocks available to insert within the {ParentBlockName} block".

That seems like it could be a quick win, and potentially benefit other limited nesting containers such as Social Links.

@vcanales @mkaz any thoughts on the level of effort this would take to build? Seems simple enough.

**Comment by mkaz** [comment]
@jasmussen @mtias Are you looking for something like this?

<img src="https://user-images.githubusercontent.com/45363/132586393-2c0af244-7686-4db8-bb1e-4a4f851a8343.png"
alt="QuickInserter for Navigation Block" width="536"/>

Do you want to be able to customize the message per parent block, or do you think a standard message and then just switch out the name of the block it applies to?

The implementation might be slightly different depending, I'm still digging in to how we might pass the property down into the QuickInserter, so much of it is abstracted within InnerBlocks it is not quite as easy as I hoped.

**Comment by paaljoachim** [comment]
A perspective....
With the latest mockup I get the impression that it is only the 6 blocks one can insert into the navigation. A user might not even know (understand) that they can click Browse all to access additional blocks that can be inserted into the navigation.
The text takes about as much space as another row of blocks would do. Btw merging the Navigation editor and the Navigation block into how various aspects are handled with help the learning curve for users. As adding a Nav block would have similarities into how working with the Nav editor becomes.

**Comment by jasmussen** [comment]
The quick inserter definitely needs iteration as far as both curation of the default 6, but also how you explore additional ones. But even without that, the "Browse all" at the bottom means it isn't a dead end, so I think it could still be a quick win:

<div align="center">
<img width="510" alt="Basic" src="https://user-images.githubusercontent.com/1204802/132810637-99edda45-16c6-40b1-a025-9f6b2c7ec632.png">
</div>

This could be a fine small step to solve this ticket, so long as it isn't the end of the road.

And we do want to improve the quick inserter. It is arguably the most used interface, and right now the frecency inside means that some blocks get more prominence than they deserve simply because you don't discover others to bump them down the list. So just to explore the idea, here's what it would look like if we added a custom scrollbar:

<div align="center">
<img width="510" alt="W  custom scrollbar" src="https://user-images.githubusercontent.com/1204802/132810829-dad62dae-bafa-4850-a3a0-c2e3c20a4c47.png">
</div>

_Note it would have to be custom so it doesn't fade out on Mac or mobile systems, or the point is lost._

Another option is to add paging dots:

<div align="center">
<img width="510" alt="W  pager dots" src="https://user-images.githubusercontent.com/1204802/132810918-226c8fb5-365d-4253-97e2-676de5da4a63.png">
</div>

That 3rd option would be the same as the current "Browse all" button.

**Comment by paaljoachim** [comment]
For the first option adding text it needs to be clear that those are the top 6 block options that can be used for the Navigation bar (+ editor).

The second option I did not even initially see the scrollbar until I read the text. I believe that scrollbars can easily be overlooked.

The third option uses the wide Browse all in a more practical way. 

Brain storming. The Browse all is a big button which gives a hint that says if you do not see what you are looking for in the 6 blocks above you will need to click the Browse all and see all the blocks even those not related to Navigation. 
Keeping the user inside the quick inserter will help focus on the current task at hand. Adding a block to a Navigation.

Some explorations.
![Quick-Inserter-ver1](https://user-images.githubusercontent.com/5323259/132818899-138a86d3-80cc-4282-a735-a9b4772e607d.jpg)

Adds the arrow/chevron we are used to from opening and closing the sidebar settings panels.


![Quick-Inserter-ver2](https://user-images.githubusercontent.com/5323259/132820843-bd34f242-2cc7-4d44-8ced-b8ddcf0ae420.jpg)
Adds dots in the side of the Browse all bar.


![Quick-Inserter-ver3](https://user-images.githubusercontent.com/5323259/132820918-fbf3f382-e7ea-4697-98a1-898efe85f679.jpg)

Adds dots to the top center area giving a hint that this is just one of three block areas one can click through. It gives clarity showing that there are more than 6 quick inserter blocks available.

**Comment by annezazu** [comment]
This experience has been iterated upon SO MUCH since I opened this issue thanks to the work around a lighter experience: https://github.com/WordPress/gutenberg/issues/34041

Here's a current view:

<img width="810" alt="Screen Shot 2022-02-06 at 7 10 37 PM" src="https://user-images.githubusercontent.com/26996883/152718584-82be7863-280d-469d-a0dc-fe6b081c6459.png">

I'm going to close this out as a result as I don't think this feedback applies anymore :)
