### ISSUE TITLE
Navigation: Allow Spacer Block

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#24028]
Allowing the Spacer block as an inner block of Navigation would let people create visual groupings of links. Something like this:

<img width="649" alt="image" src="https://user-images.githubusercontent.com/191598/87831838-96237100-c852-11ea-90f8-86a8c991b1e3.png">

A horizontal option for the Spacer block could be useful in horizontal navigations, too:

<img width="789" alt="image" src="https://user-images.githubusercontent.com/191598/87832020-fca88f00-c852-11ea-8a86-f1a6805cba83.png">

**Comment by draganescu** [comment]
This issue is currently blocked by the following aspects:

- currently the spacer block only handles vertical spacing
- adding horizontal spacing to the spacer block raises issues with fixed horizontal element sizes and responsiveness

There are also the related issues #23293 and #23294 which could eventually solve this better.

**Comment by noisysocks** [comment]
I think let's drop this for WP 5.6.

**Comment by draganescu** [comment]
I would love to have the spacer included in the list of supported blocks in building complex navigation, but it is not a requirement for the editor so I will remove this  from the Navigation project.
