### ISSUE TITLE
Social icons are not clickable in 2-colons block

### ISSUE THREAD

**Issue by Arskrigitsioniets** [WordPress/gutenberg#24026]
**Describe the bug**
The problem is if a have 2-columns block, where one of the columns is bigger than another one (one of the core templates of Gutenberg), social icons from block "social icons" which go over the column are not clickable, so I can't add a link to them anyway.

**To reproduce**
1. Go to creating a new page
2. Create a 2-columns block, where the left column is smaller than the right
3. Try to add Social Icons block with 10 social icons in the left column
4. Discover that you can't click the last icons.

**Screenshots**
https://i.imgur.com/TI74yuO.jpg

**Editor version (please complete the following information):**
- WordPress version: 5.3.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Default

**Comment by mapk** [comment]
Yep, I was able to recreate this. We should probably have the social icons stack in narrow width containers similarly to how the Navigation block works.

**Recreated problem**
![social](https://user-images.githubusercontent.com/617986/88240492-26d7c380-cc3c-11ea-8b74-0199316c0d1d.gif)


**Current**
![Current](https://user-images.githubusercontent.com/617986/88240913-7965af80-cc3d-11ea-98d1-6b4e71c1707a.png)

**Proposed**
![Proposed](https://user-images.githubusercontent.com/617986/88240917-7d91cd00-cc3d-11ea-9f3a-607517b72e89.png)

**Comment by noahshrader** [comment]
I agree with @mapk's suggestion. It follows suit with the navigation block, conforms to the space of the column and of course, improves usability and visual balance.

Also, would like to not see the block toolbar jumping around as you hover on different icons, which you can see in the GIF under the "Recreated problem" section above. Personally, it should keep a consistent distance at the top of the social icons block.

I also noticed that on smaller resolutions/widths, the icons get improperly resized:

<img width="1436" alt="Screen Shot 2020-07-28 at 9 25 06 AM" src="https://user-images.githubusercontent.com/3665539/88671429-49dafb00-d0b4-11ea-9293-feef92a69191.png">

**Comment by noahshrader** [comment]
Quickly looking into the sizing of those social buttons, it seems like if you applied _height_ and _width_ to the `<a>`, it helps resolve that issue. Going to create a new GitHub issue for this.

**Comment by mapk** [comment]
>Also, would like to not see the block toolbar jumping around going from the first icon in the list to others, which you can see in the GIF under the "Recreated problem" section above. Personally, it should keep a consistent distance at the top of the social icons block.

@noahshrader the reason that toolbar jumps is because it's the toolbar for each individual social link block, so it moves to the particular social entity you're interacting with. If you click on the Social Links bock (the block that contains them all) the toolbar resides where it's expected to be.

Also, good find 👍  on that other problem with resizing.

**Comment by noahshrader** [comment]
@mapk Edited my prior post. What I'm referring to are the slight bumps that happen when hovering over icons (because the hover states affect position of the toolbar). To reproduce:

1. Click the first icon in the list
2. Hover the second icon
3. Hover over the first icon

Curious if it would be cleaner for that toolbar to be unaffected by the hover states of the icons and maintain a consistent Y position.

**Comment by mapk** [comment]
Ah yes! Excellent. Thank you. 😄

**Comment by cpapazoglou** [comment]
It seems that all points are addressed there
https://github.com/WordPress/gutenberg/pull/25334
