### ISSUE TITLE
YouTube embeds breaking/"spinning forever" and erroring out eventually

### ISSUE THREAD

**Issue by MattDemers** [WordPress/gutenberg#24035]
I've been having some trouble lately with Gutenberg and YouTube embeds.

Simply pasting in YouTube links will result in a long "spinning" animation, then eventually an error out. Other times, this error will take much shorter time to show up.

![firefox_cXml6kX41W](https://user-images.githubusercontent.com/7098804/87866536-06b0b780-c951-11ea-8eab-0c6688a9f5dc.png)

This shows up when I've used an /embed/ link, or any variation of the YouTube links for the block.

However, this problem seemed to have fixed itself a couple days ago, but has now returned. It seems to be independent of any channel, privacy status or length of video. I'm currently using a child theme of TwentyTwenty with minimal modifications. I am also hosted on Dreamhost with latest PHP, SSL on my domain, etc.

**Things I've tried**:

* Reinstalling Wordpress, both from the in-dashboard dialog, and through FTP (keeping WP-content)
* Changing themes, and using "vanilla" TwentyTwenty
* Deleting custom CSS rules (such as the "Additional CSS" in the "Customize" menu
* Installing/uninstalling the Gutenberg plugin (it isn't installed)
* Deactivating all my plugins

None of these have fixed my problem. When I've installed Wordpress locally, and the problem is not present there. I'm currently thinking it's my hosting (I'm not sure if this is viable?) or something wrong with my configuration, database, etc.

In the past I've had another error related to this but with a different output: instead of just not embedding, it used to output a large white square with the URL printed underneath, or just the URL itself.

There's [actually an example of an embed working on my site](https://mattdemers.com/creator-focused-crypto-dipping-my-toes-into-brave/) but it seems to be very janky; I honestly don't know how it works.

**Comment by bph** [comment]
@MattDemers Looking at the URL of the YouTube video is you are using the service own embed URL but not the normal YouTube link. 
https://www.youtube.com/watch?v=xmQh5jRVRNM
The URL used for the YouTube block needs to be of the format /watch?v=[youtubeid]

For your example,  use the links from the browser URL 
https://www.youtube.com/watch?v=E2UTc2lTjww

![Screen Shot 2020-07-19 at 1 50 01 AM](https://user-images.githubusercontent.com/39980/87868273-33b99600-c962-11ea-904b-cd0e880777b8.png)

A video of embedding a YouTube video: https://recordit.co/eIQyqKzFGd

Please refer also to the [documentation page for YouTube Embed block ](https://wordpress.org/support/article/youtube-embed/)

**Comment by MattDemers** [comment]
@bph Thanks for the response. As I mentioned in the original post, I've tried the watch, embed, shortlink, and most variations of YouTube link.

Unfortunately the issue is still present. However since posting my initial topic it now goes _immediately_ to the error, and doesn't spin for as long.

![image](https://user-images.githubusercontent.com/7098804/87868471-e3433800-c963-11ea-8190-f3bf258347b8.png)

**Comment by bph** [comment]
Had to make sure. Sorry if my infor felt redundant.
As the embed for YouTube videos in general works, your experience could be routed in a plugin conflict. 

Have you ever used the  troubleshooting mode of the [Health Check & Troubleshooting plugin](https://wordpress.org/plugins/health-check/)? It allows you to - just for an administrator to disable all plugins & revert to a default theme. A normal visitor will.see.your site unchanged. Then you can see if the error still occurs. If it does, then there is then we need to dig deeper. If it doesn't you can activate one plugin at a time to see which one conflict with the embed feature. 

BTW, these kind of support is better suited for the general [support forums](https://wordpress.org/support/forum/how-to-and-troubleshooting/), where more support volunteers are helping WordPress users. Can you start a new topic there with the next findings? If you then post the link to topic  here,  I'll meet you there.and we can close the issue here.

**Comment by MattDemers** [comment]
Apologies.

The thing is, the embeds work now, without any changes that I've made. I suspect this is something to ask my hosting about, because it's not like I've tweaked anything on my end to magically make it work.

Thanks for your time.

**Comment by bph** [comment]
You are welcome. No worries. @MattDemers
