### ISSUE TITLE
Avoid CSS conflicts with other projects

### ISSUE THREAD

**Issue by Kwadz** [WordPress/gutenberg#24031]
Gutenberg is more and more used by other open-source projects. But it's difficult to integrate it, for example about the CSS conflicts.

To make it more easily adoptable and widely used by other projects, what do you think about prefixing all the CSS classes?
Any other idea is welcome.

I'd like to put some effort to make its adoption easier.

**Comment by tellthemachines** [comment]
Hi @Kwadz , thanks for opening this issue! Could you share some more about what kind of CSS conflicts you're running into? Are they on the editor interface itself, or on the output content?

**Comment by Kwadz** [comment]
I'm using it with Drupal, via the [Drupal Gutenberg](https://www.drupal.org/project/gutenberg) module. It's not on the Gutenberg editor interface itself but on the rest of the CMS. There is a related [issue in Drupal.org](https://www.drupal.org/project/gutenberg/issues/3142400). That said, may be we could simply encapsulate Gutenberg in an iframe to avoid conflicts with any external CSS 🤔

**Comment by tellthemachines** [comment]
Hmm, from what I understand of that Drupal issue you link to, it seems the problem is with theme styles overriding the editor module styles. In that case there's not much we can do on the Gutenberg side, as potentially any theme CSS that's generic enough (say a rule targeting all `<ul>`s) could interfere with the editor styling. 

I'm not familiar with the inner workings of Drupal, but encapsulating the editor in an iframe sounds worth exploring!

**Comment by Kwadz** [comment]
Thanks for your feedback.
