### ISSUE TITLE
No way to unregister delete or backspace keys as shortcuts for removing a block.

### ISSUE THREAD

**Issue by bfintal** [WordPress/gutenberg#24097]
Performing this:

```js
wp.data.dispatch( 'core/keyboard-shortcuts' ).unregisterShortcut( 'core/block-editor/remove' )
```

Should stop the `delete` key from deleting a block, although it doesn't.

Doing this after an `unregisterShortcut` shows the shortcut as removed, but it still works.

```js
wp.data.select( 'core/keyboard-shortcuts' ).getShortcutRepresentation( 'core/block-editor/remove' )
```

**Comment by talldan** [comment]
Hey @bfintal. The `core/block-editor/remove` shortcut is the one in the block settings menu, ctrl+opt+z on a mac:
<img width="272" alt="Screenshot 2020-07-22 at 12 42 07 pm" src="https://user-images.githubusercontent.com/677833/88135130-e74bb000-cc18-11ea-8b8f-edb8be041cc3.png">

The idea of this shortcut is that it can remove a text-based block where `delete` or `backspace` would only remove text within the block.

I tested `unregisterShortcut` and it seemed to work ok for that shortcut. 

I don't think there's a way to disable `delete` probably because it's part of the writing flow in the editor rather than being registered as a specific shortcut.

I did notice there's `core/block-editor/delete-multi-selection` and that works for disabling delete or backspace for block multi selections, so things do seem a little inconsistent in that respect.

I'll label as a bug and re-title the issue to match the problem.

**Comment by kathrynwp** [comment]
@talldan Hi! As there hasn't been any movement on this issue in two years, I've marked it as stale. Let me know if you think it should be kept open. Thanks!

**Comment by talldan** [comment]
Hmm, I don't have much of an opinion on it. I haven't seen any other requests for this, so it's probably ok to close.

What do you think, @bfintal?

**Comment by Thelmachido** [comment]
Since this was marked as stale 24 days ago and there hasn't been activity since then I will close this issue for now, please feel free to re-open if you want to circle back on this @bfintal
