### ISSUE TITLE
[Feat] Create a new classic menu block

### ISSUE THREAD

**Issue by ashiishme** [WordPress/gutenberg#24113]
**Is your feature request related to a problem? Please describe.**
This is a new request to make the menu items & blocks management separate & easier in navigation block.

**Describe the solution you'd like**

Current proposed solution based on the @draganescu thoughts: 

A classic menu block in navigation block ( child ) that would remove the tie between the navigation block and classic menu-items in the navigation screen.
The idea is to delegate all management of block <-> walker <-> db items to another block, not to navigation.

**Describe alternatives you've considered**
Not yet. Please propose your ideas in comment.

[check the discussion about this feature in slack.](https://wordpress.slack.com/archives/C02RQBWTW/p1595403449073100)

**Comment by noisysocks** [comment]
I could see this living alongside the Pages block (https://github.com/WordPress/gutenberg/issues/23689) so that, after inserting a (empty) Navigation block, the user has a choice to:

1. Insert a Link and start the menu from scratch; or
1. Insert a Pages block which populates the navigation with all the site's pages; or
1. Insert a Menu block which populates the navigation with an existing site's menu.

See https://github.com/WordPress/gutenberg/issues/23207.

**Comment by noisysocks** [comment]
Closing this for now as it doesn't fit in with the planned approached outlined in https://github.com/WordPress/gutenberg/issues/24364. We can re-open if things change.
