### ISSUE TITLE
Create Popver Descriptions for Each Block in the Insert Menu

### ISSUE THREAD

**Issue by cedon** [WordPress/gutenberg#2411]
Some of the blocks available for insertion, more specifically `Cover Text` and `Verse` really have no context as to what these blocks are, what they do, how a user might utilize them, etc. While these are the only two that, in my mind, are not self-explanatory, future blocks might have a similar issue.

For further reference see #1559 Comment [322124393](https://github.com/WordPress/gutenberg/issues/1559#issuecomment-322124393)

**Comment by jasmussen** [comment]
Thanks for opening this ticket. Since the discussion we had back in August, a fair amount of things have changed both with regards to the block in question, and the design of the inserter. We even have a "Slash" command now. As such, for now, I'm going to close this ticket as no longer an issue. 

Closing doesn't mean it can't be reopened again if the issue reappears or proves still relevant. Thanks again for the report.
