### ISSUE TITLE
Publish/Update/Preview Stripping out <br /> Elements inside Paragraphs

### ISSUE THREAD

**Issue by cedon** [WordPress/gutenberg#2414]
## Issue Overview
Line Break elements being stripped from paragraphs on preview/publish. 

## Steps to Reproduce (for bugs)
Press Shift+Enter to insert `<br />` multiple times.

![image](https://user-images.githubusercontent.com/12448364/29289866-2c740bd8-810c-11e7-95c8-def2ad1ef813.png)

which results in the following code in the text editor view:
```
<!-- wp:core/paragraph -->
<p>This post demonstrates the Verse block...<br/><br/><br/><br/>which is really just a &lt;pre&gt; element....</p>
<!-- /wp:core/paragraph -->
```

## Expected Behavior
I expect to see the phrase `This post demonstrates the Verse block...`, four blank lines, and then the phrase `which is really just a &lt;pre&gt; element....` all wrapped in a `<p>` element.

## Current Behavior
The code above generates the following:

![image](https://user-images.githubusercontent.com/12448364/29290540-6dead9d2-810e-11e7-92e7-d539b527fe10.png)
```
<p>This post demonstrates the Verse block&#8230;</p>
<p>which is really just a &lt;pre&gt; element&#8230;.</p>
```

If there is no text after the `<br />` element, then only
```
<p>This post demonstrates the Verse block&#8230;</p>
```

When I go back into the editor for the post, visually I see four line breaks and the text editor still has the HTML code showing four line breaks. So now there is a disparity between how the editor is showing my my text will look and the code that's going to be used, and what is actually presented to the browser when the post is previewed/published.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by karmatosed** [comment]
I think the issue here is how the text is being handled by the theme. For example, here is what is showing without any styling:

![2017-08-15 at 16 09](https://user-images.githubusercontent.com/253067/29322099-41b196dc-81d4-11e7-89cf-4f613ff4e320.png)

This is what I see using Twenty Seventeen:

![2017-08-15 at 16 16](https://user-images.githubusercontent.com/253067/29322328-10f93d14-81d5-11e7-87b0-fb4d40d4c0fa.png)

I'm not sure what theme you are using but as you can see I can added blank lines in both.

**Comment by cedon** [comment]
I was using 2017 too.
