### ISSUE TITLE
New icons for Post blocks

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#24175]
We currently have several Post blocks that do not have custom icons created for them. I'm beginning this process and submitting a few icons for review to be used for these Post blocks and to be added to the Figma library. I've designed these to maintain the common post blocks icon structure with the two lines below.

The Post blocks that do not have custom icons include:

- Post Featured Image
- Post Comments Form
- Post Comments Count
- Post Comments

![Screen Shot 2020-07-23 at 3 38 22 PM](https://user-images.githubusercontent.com/617986/88345318-9318fc80-ccfa-11ea-97fc-f659586cb503.png)

[Figma file](https://www.figma.com/file/FBsbFeGh4eK5LxZ7owZEoL/icons?node-id=0%3A1)

cc @pablohoneyhoney @jasmussen @noahshrader

**Comment by shaunandrews** [comment]
- I wonder if the featured image could just use the regular image icon, maybe with a star or something?
- I don't recognize the shapes in the comments-form icon; It reads more like an unordered list. I'm not sure how to visually represent a form, but a simple rounded-rect might suggest an input.
- The "2" in the comment count icon isn't coming off as a number; It just looks like a squiggled line. Maybe just a dot or pill shape to mimic an unread count?
- I think the post comments icon could just be the regular comment icon? Maybe with an extra line to suggest there are more than one.

Here's a couple quick ideas:

<img width="229" alt="image" src="https://user-images.githubusercontent.com/191598/88404948-95339780-cd9c-11ea-97a6-4e7f49a1c9bd.png">

**Comment by mapk** [comment]
I like those explorations, @shaunandrews and it seems like we can venture out of the double line icon pattern because both the Post Tags block and the Post Date block use regular icons. Is that the case, @pablohoneyhoney, or is this set of icons strongly encouraged to follow the double line pattern for Post blocks?

**Comment by mapk** [comment]
After some discussion, I was encouraged to drop the double line pattern for the Post blocks icons due to the image not communicating very clearly. I've taken @shaunandrews' suggestions above and have iterated further.

![Screen Shot 2020-07-29 at 2 44 28 PM](https://user-images.githubusercontent.com/617986/88856958-4629a000-d1aa-11ea-90d4-2bf27dc46dfe.png)

Some notes regarding the iteration:

- I've dropped the double lines.
- The "post comments" related icons are unified using an additional line signifying there's more than one comment. (inspired from Shaun's above)
- The bookmark element is utilized in other blocks like the Cover and Heading blocks.
- I flipped the mountains in the featured image icon so they don't interfere with the bookmark element.

**Comment by pablohoneyhoney** [comment]
The last iterations tend to be more evident about the meaning, but they are a bit crowded. Is there a chance we can reduce further and see them in context? That might help to understand better the complexity or clarity needed.

**Comment by mapk** [comment]
The comments-related icons do feel a little crowded. I was balancing the unification of the comment-related icons with that. However, the featured image icon, and the post comments icon work well IMO. Here's how they look in context with their block.

![In-blocks](https://user-images.githubusercontent.com/617986/88944837-162ddb80-d242-11ea-97e1-65332a92ef96.png)

Here's an iteration to lessen the crowded appearance. I've pulled the smaller icon out of the comment shape and revised them a bit.

![Screen Shot 2020-07-30 at 9 43 25 AM](https://user-images.githubusercontent.com/617986/88950188-22696700-d249-11ea-90a0-555010c4b75e.png)

**Comment by mapk** [comment]
A few more iterations keeping the comment icon, but dropping the added line indicating multiple comments.

![Screen Shot 2020-07-30 at 11 31 56 AM](https://user-images.githubusercontent.com/617986/88960451-5d26cb80-d258-11ea-9699-8ca6e7880680.png)

**Comment by jasmussen** [comment]
There's a great deal of complexity in a very small space, and none of them read very well to me. It's an open question whether they need to be perfectly representative given they are somewhat rarely used page builder blocks. But if we can't well represent the topic in the icon, at least the icons should not add further complexity to the visual appearance.

There's some rhythm in the initial offering of the _icon and then lines of text_ that feels like it makes the blocks group together, which they do given they all relate to post meta templates. But I wonder if instead of lines of text, we could use the bubble comment icon as the denominator, rhythm creator, and then add iconography for each aspect of the topic in a similar layout.

Topic wise, Shaun's versions feel like they approach something that better resembles forms, featured images. The non-stacked comment icon also feels sufficient.

**Comment by mapk** [comment]
>There's some rhythm in the initial offering of the icon and then lines of text that feels like it makes the blocks group together, which they do given they all relate to post meta templates. But I wonder if instead of lines of text, we could use the bubble comment icon as the denominator, rhythm creator, and then add iconography for each aspect of the topic in a similar layout.

Yep, this was my sentiment as well and why I chose that direction in [my last set of iterations](https://github.com/WordPress/gutenberg/issues/24175#issuecomment-666586627).

**Post Featured Image icon**
I'm still partial to the bookmark in the image icon for the Post Featured Image icon because the alignment of the shapes work nicely at the icon level. And the image icon doesn't get smaller which causes difficulty interpreting what it is. But I'm open to using a star if that's a strong preference.

![Screen Shot 2020-08-03 at 11 15 52 AM](https://user-images.githubusercontent.com/617986/89213928-b9e8f580-d57a-11ea-93fa-2a0e65cfa8bf.png)

**Post Comments Form icon**
As for the Post Comments Form icon, I incorporated Shaun's example above and moved it into the toolbar for context.

![Screen Shot 2020-08-03 at 11 03 29 AM](https://user-images.githubusercontent.com/617986/89213434-ed775000-d579-11ea-8318-5e310d7641fe.png)

It doesn't communicate "form" to me. I'm not sure what to make of a rectangle inside of a comment bubble. But again, I can be convinced otherwise. :) I did attempt another iteration that uses the comment bubble and also displays a minimal form inside rather than what could have been interpreted as a bulleted list.

![Screen Shot 2020-08-03 at 11 21 27 AM](https://user-images.githubusercontent.com/617986/89214386-95d9e400-d57b-11ea-93f5-8a7a3980f712.png)

**Post Comments Count icon**
The more difficult of these, IMO, is the Post Comments Count icon. How does one communicate comment counts visually at a small scale? Do we use a dot which is more popularly recognized as a notification? (and maybe this is okay) Or do we try for more meaning as in the scratches commonly used for counting? But this adds complexity. Or, as I tried earlier, maybe we show a number? 
Each of these when placed inside the comment bubble increases complexity, but retains uniformity. Breaking out of the comment bubble can help here. With those few extra pixels, do we attempt to communicate _comment counts_ or should we just focus on _counts_?

While I agree the scratches icon was leaning toward too much complexity, I've since simplified it. It represents "count" quite well, and inside the comment bubble, it unifies with _comment count_.

![Screen Shot 2020-08-03 at 11 41 23 AM](https://user-images.githubusercontent.com/617986/89216002-7c866700-d57e-11ea-8f58-246f5a60791c.png)

But alas... it can also be interpreted as stitching... Ugh. 😄

**Comment by jasmussen** [comment]
> But I'm open to using a star if that's a strong preference.

My reluctance is mostly that the square with a mountain and a bookmark looks like a mix between Cover and Image, while also being complex. 

For all of the icons, the biggest issue I perceive is that it's very hard to find a metaphor that accurately represents the subject matter as just an icon. And in the absense of us finding those, I don't think we should add visual complexity. There is more than just the icon to denote a block type, and in that light it feels more important that these icons not only look different from each other, but given they are all template related, perhaps look grouped together.

In that vein, going back to the initial instinct of "small basic icon plus group indicator below". The first version had lines of text below, but is there a way to denote template better than text? Perhaps a stylized puzzle piece?

I.e. featured image: small image plus puzzle piece.

Comment form: comment plus puzzle piece.

Comment count: count plus puzzle piece.

**Comment by mapk** [comment]
I tried out the puzzle concept, @jasmussen. It gets pretty tight when dropping below 10px for the puzzle piece to work as an icon addition. But I wanted to share these and get your feedback. 😄 

### Post icons

![post-icons](https://user-images.githubusercontent.com/617986/90167815-0f7a8a80-dd51-11ea-8962-9355e0c163de.png)

### Post Comments Count
As I mentioned above, figuring out the best icon to represent "count" is difficult. For the ones above, I used an icon representing an abacus. But with concern about complexity, I tried a few variations with just numbers and settled on the number 1 as best representing a "count".

![post-comments-count](https://user-images.githubusercontent.com/617986/90168111-8152d400-dd51-11ea-8b21-112dee13e8b1.png)

### The puzzle piece addition
The puzzle piece is tricky at that size. While initially, I built it with smaller appendages, I iterated to add 0.5px larger appendages for more definition. You can see the difference (maybe?) below.

![puzzle](https://user-images.githubusercontent.com/617986/90168291-bced9e00-dd51-11ea-80f7-0f35623e63a6.png)

**Comment by jasmussen** [comment]
I think that can work. But I miss the stacked silhouette you started with way at the top. Here's a riff:

<img width="470" alt="Screenshot 2020-08-14 at 09 56 49" src="https://user-images.githubusercontent.com/1204802/90227337-aeb48600-de14-11ea-90a3-be56b308ae5d.png">

The puzzle piece is slightly fuzzy, but the layout and repeatable pattern / "belonging" these share feels valuable. Is it worth trying out? As an alternative, it could be worth trying to miniaturize the generic "Block"/LEGO brick icon and use in place of the puzzle piece:

<img width="435" alt="Screenshot 2020-08-14 at 10 11 41" src="https://user-images.githubusercontent.com/1204802/90228513-a3625a00-de16-11ea-964a-4f206acb99ec.png">

SVGs:

Featured Image
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M11.2 16.8H10v-1.3c0-.3-.2-.5-.5-.5h-5c-.3 0-.5.2-.5.5v5c0 .3.2.5.5.5h1.6L6 19.8c0-.6.4-1 1-1s1 .4 1 1L7.9 21h1.6c.3 0 .5-.2.5-.5v-1.3l1.2.1c.7 0 1.2-.6 1.2-1.2.1-.8-.5-1.3-1.2-1.3zM13 3H5c-.6 0-1 .4-1 1v8c0 .6.4 1 1 1h8c.6 0 1-.4 1-1V4c0-.6-.4-1-1-1zm-.5 8.5h-7v-.9l1.8-1.3 1.3.8c.3.2.7.2.9-.1L11 8.6l1.5 1.4v1.5zm0-3.5l-1-1c-.3-.3-.8-.3-1 0L8.9 8.6l-1.2-.8c-.3-.2-.6-.2-.8 0l-1.3 1V4.5h7V8z"/></svg>
```

Post Comments:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M11.2 16.8H10v-1.3c0-.3-.2-.5-.5-.5h-5c-.3 0-.5.2-.5.5v5c0 .3.2.5.5.5h1.6L6 19.8c0-.6.4-1 1-1s1 .4 1 1L7.9 21h1.6c.3 0 .5-.2.5-.5v-1.3l1.2.1c.7 0 1.2-.6 1.2-1.2.1-.8-.5-1.3-1.2-1.3zM13 3H5c-.6 0-1 .4-1 1v8.4c0 .3.2.7.5.8.1 0 .2.1.3.1.2 0 .4-.1.6-.2l1.9-1.9H13c.6 0 1-.4 1-1V4c0-.6-.4-1-1-1zm-.5 6.6H6.7l-1.2 1.2V4.5h7v5.1z"/></svg>
```

Comments Form:

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M11.2 16.8H10v-1.3c0-.3-.2-.5-.5-.5h-5c-.3 0-.5.2-.5.5v5c0 .3.2.5.5.5h1.6L6 19.8c0-.6.4-1 1-1s1 .4 1 1L7.9 21h1.6c.3 0 .5-.2.5-.5v-1.3l1.2.1c.7 0 1.2-.6 1.2-1.2.1-.8-.5-1.3-1.2-1.3zM4.5 9s.1 0 0 0l1.4-1.4h4.6c.3 0 .5-.2.5-.5V3.5c0-.3-.2-.5-.5-.5h-6c-.3 0-.5.2-.5.5v5.3c0 .3.4.4.5.2zm10-.5h-6c-.3 0-.5.2-.5.5v3.6c0 .3.2.5.5.5h4.6l1.4 1.3c.2.2.5.1.5-.2V9c0-.3-.2-.5-.5-.5z" fill="#1e1e1e"/></svg>
```

Comment Count:

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M11.2 16.8H10v-1.3c0-.3-.2-.5-.5-.5h-5c-.3 0-.5.2-.5.5v5c0 .3.2.5.5.5h1.6L6 19.8c0-.6.4-1 1-1s1 .4 1 1L7.9 21h1.6c.3 0 .5-.2.5-.5v-1.3l1.2.1c.7 0 1.2-.6 1.2-1.2.1-.8-.5-1.3-1.2-1.3zM13 3H5c-.6 0-1 .4-1 1v8.4c0 .3.2.7.5.8.1 0 .2.1.3.1.2 0 .4-.1.6-.2l1.9-1.9H13c.6 0 1-.4 1-1V4c0-.6-.4-1-1-1zm-2.2 6.6H7l1.6-2.2c.3-.4.5-.7.6-.9.1-.2.2-.4.2-.5 0-.2-.1-.3-.1-.4-.2-.1-.3-.1-.5-.1s-.4 0-.6.1c-.2.1-.4.3-.6.4l-.2.3L7.2 5l.1-.1c.3-.2.5-.3.8-.4.3-.1.6-.1.9-.1.3 0 .6.1.9.2.2.1.4.3.6.5.1.2.2.5.2.7 0 .3-.1.6-.2.9-.2.3-.4.7-.8 1.2l-.4.6h1.6v1.1z" fill="#1e1e1e"/></svg>
```

[Figma](https://www.figma.com/file/fnyj380i05vGzuuH60frLQ/G2-Design?node-id=1178%3A0)

**Comment by mariohamann** [comment]
Many nice icons! I especially like the different "counting icons". :) Thank you for sharing the Figma-files.

Here are a few ideas I would like to add ([Figma](https://www.figma.com/file/mqo2NTIfvugd6VZot2plhP/block-post-comments?node-id=0%3A1)):

## Template Icons

It's certainly a good idea to mark "template blocks" differently.  The "stacked" design makes it a bit difficult to see the icons above them. So I find the insertion of the puzzle icon into the icon more coherent. I just wonder if an additional icon is scalable enough for all future blocks? I have looked for more neutral solutions.

- With variant 1 there are too many lines in the same thickness. But for me it gives a sense of "template". :)
- An inverted variant makes the "special" nature of the template blocks very clear, but could also be very heavy if there are many of them.
- More discreet is the third variant, which simply uses a line as marking element. Maybe that is enough?

![Screen Shot 2020-08-14 at 13 21 56](https://user-images.githubusercontent.com/26542182/90244640-72dbe980-de31-11ea-9b1d-cb53965d9050.jpg)


## Post Comments
In general I find it very useful if all comment related blocks share a speech bubble as a common icon, because in my opinion they belong together very much.

### Count
Since the block at the end is a variable number, I wonder if setting it to a "1" is ideal. So I like the tally sheet (with 5 lines) much better! Maybe it could also be useful to set an asterisk in the sense of a variable parameter?
![Screen Shot 2020-08-14 at 13 22 07](https://user-images.githubusercontent.com/26542182/90244645-766f7080-de31-11ea-8784-87ac3e519548.jpg)


### Comments
I find the icon that displays stacked comments very useful and as far as I remember it also fits well e.g. to block groups. As another suggestion, the underlying comment could also be displayed as another stylized speech bubble.

![Screen Shot 2020-08-14 at 13 22 01](https://user-images.githubusercontent.com/26542182/90244671-82f3c900-de31-11ea-8f42-87c8537c48d0.jpg)

### Form
I have two thoughts on this:

1. in WhatsApp etc., messages from yourself are marked with a speech bubble pointing to the right. Since the person commenting also takes this active role, mirroring the speech bubble might be a good idea.
2. I like the presentation of the form already. The idea with the 3 points came to me spontaneously and I just wanted to add it, but I don't really think it is better. :)

![Screen Shot 2020-08-14 at 13 22 04](https://user-images.githubusercontent.com/26542182/90244665-7f604200-de31-11ea-8a61-424fceb0369e.jpg)

**Comment by jasmussen** [comment]
Good thoughts, Mario! I think there are two aspects to consider, one is the need for the icons in this thread, and the other is the larger thought of a special treatment for "template icons".

It seems the puzzle piece idea did not catch on, perhaps it was simply too much complexity as alluded to, or maybe it's all just blocks and no treatment necessarily. Here's another round to address the 4 specific icons here:

<img width="511" alt="Screenshot 2020-08-17 at 11 13 47" src="https://user-images.githubusercontent.com/1204802/90380443-58498080-e07c-11ea-91d8-df5f73d95655.png">

These try to capture some of the simplicity of the very first offering, but are not beholden to any "template part pattern".  SVGs. Featured image:

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M19 3H5c-.6 0-1 .4-1 1v7c0 .5.4 1 1 1h14c.5 0 1-.4 1-1V4c0-.6-.4-1-1-1zM5.5 10.5v-.4l1.8-1.3 1.3.8c.3.2.7.2.9-.1L11 8.1l2.4 2.4H5.5zm13 0h-2.9l-4-4c-.3-.3-.8-.3-1.1 0L8.9 8l-1.2-.8c-.3-.2-.6-.2-.9 0l-1.3 1V4.5h13v6zM4 20h9v-1.5H4V20zm0-4h16v-1.5H4V16z"/></svg>
```

Post comments.
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M13 8H4v1.5h9V8zM4 4v1.5h16V4H4zm9 8H5c-.6 0-1 .4-1 1v8.3c0 .3.2.7.6.8.1.1.2.1.3.1.2 0 .5-.1.6-.3l1.8-1.8H13c.6 0 1-.4 1-1V13c0-.6-.4-1-1-1zm-.5 6.6H6.7l-1.2 1.2v-6.3h7v5.1z"/></svg>
```

Comment count:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M13 8H4v1.5h9V8zM4 4v1.5h16V4H4zm9 8H5c-.6 0-1 .4-1 1v8.3c0 .3.2.7.6.8.1.1.2.1.3.1.2 0 .5-.1.6-.3l1.8-1.8H13c.6 0 1-.4 1-1V13c0-.6-.4-1-1-1zm-2.2 6.6H7l1.6-2.2c.3-.4.5-.7.6-.9.1-.2.2-.4.2-.5 0-.2-.1-.3-.1-.4-.1-.1-.2-.1-.4-.1s-.4 0-.6.1c-.3.1-.5.3-.7.4l-.2.2-.2-1.2.1-.1c.3-.2.5-.3.8-.4.3-.1.6-.1.9-.1.3 0 .6.1.9.2.2.1.4.3.6.5.1.2.2.5.2.7 0 .3-.1.6-.2.9-.1.3-.4.7-.7 1.1l-.5.6h1.6v1.2z"/></svg>
```

Post comments:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M14 10.1V4c0-.6-.4-1-1-1H5c-.6 0-1 .4-1 1v8.3c0 .3.2.7.6.8.1.1.2.1.3.1.2 0 .5-.1.6-.3l1.8-1.8H13c.6 0 1-.4 1-1zm-1.5-.5H6.7l-1.2 1.2V4.5h7v5.1zM19 12h-8c-.6 0-1 .4-1 1v6.1c0 .6.4 1 1 1h5.7l1.8 1.8c.1.2.4.3.6.3.1 0 .2 0 .3-.1.4-.1.6-.5.6-.8V13c0-.6-.4-1-1-1zm-.5 7.8l-1.2-1.2h-5.8v-5.1h7v6.3z"/></svg>
```

I'd love for us to be able to wrap this one. The icons don't need to be perfect because we can always update them again, but more importantly we shouldn't feel blocked on the icon pipeline.

**Comment by mapk** [comment]
@jasmussen I like the featured image icon! Good call on extending it across.

Moving the lines above the comment icons helps to visually identify the comments as being _below_ the post. 👍 

I'll get a PR going here and make sure the Figma icons get updated as well.
