### ISSUE TITLE
HTML content gets executed as reusable block

### ISSUE THREAD

**Issue by MatzeKitt** [WordPress/gutenberg#24283]
**Describe the bug**
If you create an HTML block, the content is displayed as text. As soon as you store it as reusable block, however it’s getting executed.

**To reproduce**
1. Add a new HTML block
2. Add the following content to the HTML block: `<script>console.log( 'Hit' );</script>`
3. Store this block as reusable block
4. Watch the `hit` in the browser console

**Expected behavior**
Even as reusable block the HTML should not be executed in the backend.

**Editor version (please complete the following information):**
- WordPress version: 5.5-RC1-48687
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Yes
- If the Gutenberg plugin is installed, which version is it? 8.6.1

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - Browser: Safari
 - Version: 13.1.2 (15609.3.5.1.3)

**Comment by getdave** [comment]
Thanks for reporting this @KittMedia.

I've replicated this as you describe. I also note that the `console.log` is executed when the block is _previewed_ in the Block Inserter when you hover over the block.

However, I'm not 100% sure whether this is a bug or a feature. The HTML block is intended to allow you to enter/execute arbitrary HTML code which presumably includes `<script>` tags. Indeed the reason this might exist is that a 3rd party might _legitimately_ ask you to add a `<script>` to a page and you'd need to be able to do that with Gutenberg.

Is there a specific use case here that concerns you? 

I note you say 

> should not be executed in the backend.

The HTML block allows you to preview the HTML you have entered within the editor. Therefore if we are allowing HTML which includes `<script>` then a `console.log` will be executed when you first insert the reusable version of the block because the default view is "Preview" for that block. Is your concern that the `<script>` will be executed on reusable block insertion? 

Look forward to hearing your thoughts.

**Comment by KittMedia** [comment]
The script tag was just an example. If you enter custom HTML in a regular block, you always get this block as text. However, as reusable block, the HTML gets executed as long as you don’t edit the block. At least for me and my colleagues, this is confusing since the same block behaves differently as regular block and as reusable block.

I understand that it can make sense to have the HTML executed from a WYSIWYG view, but from a usability standpoint it’s hard for me to understand. At least since it may be that you use e. g. shortcodes inside your HTML (I use it for a custom picture/img element as placeholder), which could lead to errors (404 in my case since the shortcode doesn’t get executed in the img tag and thus the source to the file is not found).

I hope that makes it more clear why I have this concern. 🙂

**Comment by getdave** [comment]
@KittMedia Thanks for replying. Just so I can fully understand do you think you might be able to provide another example using real content explaining how it works with the regular HTML block and how it doesn't work once that same block is converted to a reusable block?

Apologies if this seems obvious but I feel like I'm missing a key piece of context here. Any help would be much appreciated.

**Comment by KittMedia** [comment]
No problem, I’m glad that you ask when anything is not clear to you.

A real example would be this code.
```
<!-- wp:group {"align":"full","className":"header-image"} -->
<div class="wp-block-group alignfull header-image"><div class="wp-block-group__inner-container"><!-- wp:html -->
<picture>
	<source media="(min-width: 1024px)" srcset="/wp-content/uploads/sites/11/2020/07/header-[location part=uri].jpg">
	<source srcset="/wp-content/uploads/sites/11/2020/07/header-[location part=uri]-mobile.jpg">
	<img src="/wp-content/uploads/sites/11/2020/07/header-[location part=uri].jpg" alt=""> 
</picture>
<!-- /wp:html --></div></div>
<!-- /wp:group -->
```
That’s the whole content of the reusable block, which is used on multiple pages. Via shortcode `[location part=uri]` the location name (e. g. `new-york`) gets output so that we can use a single reusable block to update the images of all locations at once. If however you display this block in your backend you get a 404 request for this file since the shortcode gets only executed in the frontend and thus the file `header-[location part=uri].jpg` doesn’t exist.

If you have additional questions, feel free to ask. And you don’t need to apologise for it. 🙂

**Comment by jordesign** [comment]
I'm no longer seeing this take place in WP 6.3 with the reusable blocks replaced by un/synced patterns so I'll close this issue.

Happy for it to be reopened after further testing if I've misunderstood or incorrectly tested.
