### ISSUE TITLE
HTML block content gets transformed into entities

### ISSUE THREAD

**Issue by MatzeKitt** [WordPress/gutenberg#24282]
**Update**: this bug is not isolated to reusable blocks. It happens when creating a `core/html` block when it contains these characters as the HTML entities `&amp;`, `&lt;` and `&gt;`.

--------

**Describe the bug**
If you create an HTML block with the content `3 < 4` and ~store it as reusable block~ save it, and then reload the page, the `<` becomes `&lt;`.

Background: I need to use this HTML block to add some JavaScript. If parts of this JavaScript gets changed by encoding to HTML entities, it just doesn’t work on the one hand and can result in a total crash of Gutenberg on the other hand.

**To reproduce**
1. Add a new HTML block
2. Add this content: `3 < 4`
3. Store the block as reusable block

**Expected behavior**
The block is stored as reusable with the raw content added.

**Editor version (please complete the following information):**
- WordPress version: 5.5-RC1-48687
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Yes
- If the Gutenberg plugin is installed, which version is it? 8.6.1

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - Browser: Safari
 - Version: 13.1.2 (15609.3.5.1.3)

**Comment by getdave** [comment]
I tested this and can confirm the Issue is occurring as described. I also noted the following block validation issue n the browser console:

```
Block validation: Block validation failed for `core/html`...

Content generated by `save` function:

3 &lt; 4

Content retrieved from post body:

3 < 4
```

This notes a mismatch between what is being saved (encoded entities) and what is in the post body (string of raw HTML).

I can see the block's `save` passes the block content through `<RawHTML>`

https://github.com/WordPress/gutenberg/blob/5e77f46d2955749057e423001643a67daff54cc3/packages/block-library/src/html/save.js#L6-L8

...which is a wrapper around React's `dangerouslySetInnerHTML ` prop

https://github.com/WordPress/gutenberg/blob/5e77f46d2955749057e423001643a67daff54cc3/packages/element/src/raw-html.js#L20-L27

**Comment by getdave** [comment]
@KittMedia Do you have an example of the JavaScript you need to include that is not working. A reduced test-case form for testing would be fine.

**Comment by KittMedia** [comment]
Of course:

```
function conditionalMemberFields() {
	var membershipRadios = document.querySelectorAll( '[name="membership"]' );
	var membershipConditionals = document.querySelectorAll( '.conditional-membernumber' );
	
	if ( ! membershipRadios.length || ! membershipConditionals.length ) {
		return;
	}
	
	for ( var i = 0; i < membershipRadios.length; i++ ) {
		membershipRadios[ i ].addEventListener( 'change', function( event ) {
			for ( var n = 0; n < membershipConditionals.length; n++ ) {
				if ( event.currentTarget.value === 'Ja' ) {
					membershipConditionals[ n ].classList.remove( 'conditional-membernumber' );
				}
				else {
					membershipConditionals[ n ].classList.add( 'conditional-membernumber' );
				}
			}
		} );
	}
}
```

**Comment by KokkieH** [comment]
This doesn't happen only when saving the block as a reusable block. I can also replicate with these steps:

1. Add the content to a HTML block
2. Save draft
3. Exit the editor
4. Re-open the post for editing.

On reopening, the block displays the HTML entity rather than the character.

Reported by a WordPress.com user in https://wordpress.com/forums/topic/editing-posts-with-markdown-markup/

**Comment by getdave** [comment]
> Of course:
> 
> ```
> function conditionalMemberFields() {
> 	var membershipRadios = document.querySelectorAll( '[name="membership"]' );
> 	var membershipConditionals = document.querySelectorAll( '.conditional-membernumber' );
> 	
> 	if ( ! membershipRadios.length || ! membershipConditionals.length ) {
> 		return;
> 	}
> 	
> 	for ( var i = 0; i < membershipRadios.length; i++ ) {
> 		membershipRadios[ i ].addEventListener( 'change', function( event ) {
> 			for ( var n = 0; n < membershipConditionals.length; n++ ) {
> 				if ( event.currentTarget.value === 'Ja' ) {
> 					membershipConditionals[ n ].classList.remove( 'conditional-membernumber' );
> 				}
> 				else {
> 					membershipConditionals[ n ].classList.add( 'conditional-membernumber' );
> 				}
> 			}
> 		} );
> 	}
> }
> ```

Just to confirm if you try this out by adding a HTML block then pasting in the content above you'll get a browser console log warning that block validation failed because `save` function and `post body` don't match. This is because `<` is converted to `&lt;` for serialization but doesn't seem to be deserialized back to `<` for use in the editor.

```diff
function conditionalMemberFields() {
	var membershipRadios = document.querySelectorAll( '[name="membership"]' );
	var membershipConditionals = document.querySelectorAll( '.conditional-membernumber' );
	
	if ( ! membershipRadios.length || ! membershipConditionals.length ) {
		return;
	}
	
-	for ( var i = 0; i < membershipRadios.length; i++ ) {
+	for ( var i = 0; i &lt; membershipRadios.length; i++ ) {
		membershipRadios[ i ].addEventListener( 'change', function( event ) {
-			for ( var n = 0; n &lt; membershipConditionals.length; n++ ) {
+			for ( var n = 0; n < membershipConditionals.length; n++ ) {
				if ( event.currentTarget.value === 'Ja' ) {
					membershipConditionals[ n ].classList.remove( 'conditional-membernumber' );
				}
				else {
					membershipConditionals[ n ].classList.add( 'conditional-membernumber' );
				}
			}
		} );
	}
}
```

**Comment by joehoyle** [comment]
For anyone that might want a not-pretty workaround, when you need to do a JS less-than comparison in a HTML block: `Math.sign( a - b ) === -1` can be a substitute. I told you it wasn't pretty! h/t @rmccue

**Comment by ftoppi** [comment]
Hello, the issue is still in present 5.8.1 . It also happens with square brackets.

**Comment by getdave** [comment]
Confirmed. Issue still present.

**Comment by getdave** [comment]
@MatzeKitt With the merge of https://github.com/WordPress/gutenberg/pull/27268 this should now be fixed. Gutenberg 14.8 will be released soon so you should be able to test it using the Gutenberg Plugin by next week.
