### ISSUE TITLE
babel-plugin-makepot misses a lot of strings.

### ISSUE THREAD

**Issue by manzoorwanijk** [WordPress/gutenberg#24347]
**Describe the bug**
Even after so many tweaks, `@wordpress/babel-plugin-makepot` fails to extract all the strings

**To reproduce**
I have created a minimal ejected [CRA based demo](https://github.com/manzoorwanijk/wp-make-pot-demo)
1. Clone the [repo](https://github.com/manzoorwanijk/wp-make-pot-demo)
2. Run `yarn build` to create a production build
3. Check `/src/languages/custom.js.pot`

**Expected behavior**
The file should contain an entry for all the 3 strings:
- `"This is a header."`
- `"Edit %s and save to reload."`
-  `"Learn React"`

**Actual behavior**
It misses some strings.

**Version info:**
- `"@wordpress/i18n": "^3.14.0",`
- `"@wordpress/babel-plugin-makepot": "^3.7.0"`

**NOTE**
It sometimes works the first time you run `yarn build`, but fails on subsequent builds.

**Also**
Before someone here suggests to use WP-CLI makepot, it does not support Typescript.

**Comment by aduth** [comment]
Can you try with your Babel configuration set to cache?

At this line, `true` instead of `false`:

https://github.com/manzoorwanijk/wp-make-pot-demo/blob/26b226ad5d3aebf915407f29f84df440c4314b16/babel.config.js#L2

I suspect what might be happening is that the plugin holds string data in memory for all files which have been scanned already, and so each time it writes the `.pot` file, it will combine any new strings with existing strings.

If caching is disabled, the data is lost between files, so only the last file scanned will have its strings included in the output.

I think the plugin should probably handle this better. Admittedly, Babel is not well-suited for this sort of multi-file parsing that the plugin needs to do.

A more durable solution might try to merge using data _from the output file as it exists_, rather than what it knows to be data in memory from previous transformed files.

**Comment by manzoorwanijk** [comment]
> Can you try with your Babel configuration set to cache? At this line, true instead of false.

I already tried that, doesn't work.

**Comment by manzoorwanijk** [comment]
After some debugging, I noticed that
- the `exit` function [here](https://github.com/WordPress/gutenberg/blob/b084ecdc230e9d2d65c04e9acbb46a1e540045aa/packages/babel-plugin-makepot/src/index.js#L311) in `babel-plugin-makepot`  is not even called after `babel-loader` caches modules.
- if I set `cacheDirectory` to `false` [here](https://github.com/manzoorwanijk/wp-make-pot-demo/blob/master/config/webpack.config.js#L389), it works as expected.

**Comment by jordesign** [comment]
Hey @manzoorwanijk  - I'm working through older issues and wanted to check if you're still seeing this issue in place?

**Comment by manzoorwanijk** [comment]
I do not use this anymore. So, I have no idea if the issue still persists.

**Comment by jordesign** [comment]
Thanks @manzoorwanijk. As there's been no further reports in 3 years I'll close this for now.

If it does arise again - we can re-open this issue.
