### ISSUE TITLE
Attributes get overwritten in `registerBlockType` on wp-admin page editor reload

### ISSUE THREAD

**Issue by ahwitz** [WordPress/gutenberg#24345]
**Describe the bug**
I've somehow managed to build a custom block that commits attributes correctly to the database, but on reloading the wp-admin page editor, overwrites and changes the attributes.

**To reproduce**
1. Using this component definition: https://gist.github.com/ahwitz/3fd11746fd49becdfd516467d3a0e29d
2. Add values to `icon` (`fa-facebook`), `label` (`Facebook`), and `url` (`facebook.com`) fields.
3. Console correctly outputs `edit {icon: "fa-facebook", url: "facebook.com", label: "Facebook"}`.
3. Click on "Update." Console correctly outputs `save {icon: "fa-facebook", url: "facebook.com", label: "Facebook"}`
4. View component on the public side of the website, and everything renders correctly as:
```html
<div class="wp-block-rilm-org-rilm-readmore rilm-readmore">
  <span class="rilm-readmore-icon fa fa-facebook"></span>
  <span class="rilm-readmore-text">Read more:</span>
  <a class="rilm-readmore-url" href="facebook.com">Facebook</a>
</div>
```
5. Re-open page/post with component in the admin interface. Console outputs:
```
save {icon: "", label: undefined, url: "Facebook"}
save {icon: "", url: "Facebook"}
```
...and a "Block validation failed" error gets thrown because `save()` does not render the same way.

**Expected behavior**
The HTML committed to the database and displayed on the public site should re-render identically in the admin interface.

**Screenshots**
n/a but can provide if necessary.

**Editor version (please complete the following information):**
- WordPress version: **5.4.2**
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? **Default.**
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**
 - OS: **Mac desktop.**
 - Browser **Chrome.**
 - Version [e.g. 22] **84**.

**Additional context**
Definitely a LARGE chance at user error, but I've been digging around and searching for some kind of lead on this and have found nothing, and even very little documentation as to what the built-in Block API components are supposed to do. Was stuck with no output on any fields when trying to use raw HTML (no React components) in the `save()` output, but got something to happen now; the fact that it's actually swapping and deleting attribute values seems like it could be a bug, so I wanted to report that as/before I asked for help.

Let me know if any additional information is necessary!

**Comment by talldan** [comment]
@ahwitz The problem seems to be your attribute declaration:
```js
    attributes: {
        icon: {
            type: 'string',
            source: 'text',
            selector: '.rilm-readmore-icon'
        },
        label: {
            type: 'string',
            source: 'text',
            selector: '.rilm-readmore-label'
        },
        url: {
            type: 'string',
            source: 'text',
            selector: '.rilm-readmore-url'
        }
    },
```
This definition is important as it instructs the parser on how to retrieve the values for your attributes from the post content (e.g. the html produced by your `save` function.

The following things are incorrect:
- For the `icon` attribute, the text of the element with the classname `.rilm-readmore-icon` will be used, but your save function shows there is no text for this element:
```jsx
                <RichText.Content
                    tagName="span"
                    className={"rilm-readmore-icon fa " + attributes.icon}/>
```
- For the `url` attribute, the text of the element with the classname `.rilm-readmore-url` will be used, but your save function shows that the `href` attribute is where this value is saved:
```jsx
                <RichText.Content
                    tagName="a"
                    className="rilm-readmore-url"
                    href={attributes.url}
                    value={attributes.label}/>
```

Fixes:
- It's not possible to retrieve the `icon` attribute from a classname, so the best option would be to remove the `source`, and `selector` properties in that attribute declaration
- For `url`, `source` should be changed to `'attribute'` and a new `'attribute': 'href'` property should be used.

There's more info on block attribute definitions here (the handbook page is being fixed at the moment):
https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/block-api/block-attributes.md

**Comment by ahwitz** [comment]
Dan - thanks for the help. Could not find that page for the life of me - is that what the "Block Attributes documentation" link on https://developer.wordpress.org/block-editor/developers/block-api/block-attributes/ is supposed to point to?
