### ISSUE TITLE
dependency-extraction-webpack-plugin breaks when using optimizations.runtimeChunk = 'single'

### ISSUE THREAD

**Issue by stefanfisk** [WordPress/gutenberg#24352]
**Describe the bug**

`@wordpress/dependency-extraction-webpack-plugin` breaks in two ways when using `optimizations.runtimeChunk = 'single'`.

1. The asset files are named based on the runtime chunk's name, i.e. `runtime.asset.php`.
2. All asset files are added to the runtime chunk.

The first issue results in only the last entrypoint's asset being saved (as it overwrites the previous ones').

The second issue makes it impossible to correlate an asset file with its entrypoint.

**To reproduce**

I've created an example project here: https://github.com/stefanfisk/wordpress-dependency-extraction-webpack-plugin-runtimechunk-single-bug

**Expected behavior**

The asset files should be named according to the entrypoint names, and only be added to the entrypoint chunks.

Preferably it should be possible to configure the asset file names. For example it would be nice if using hashes in `output.filename` did not result in the asset filename containing a hash.

**Plugin version:**

- `@wordpress/dependency-extraction-webpack-plugin` 2.8.0
- `webpack` 4.44.1

**Comment by stefanfisk** [comment]
I've got a quick and dirty fix going here: https://github.com/stefanfisk/gutenberg/tree/fix/24352-dependency-extraction-runtimechunk-single

Since I don't quite grok the internals of Webpack It's probably broken in ways I cannot fathom, so I'm refraining from opening a PR for now.

**Comment by gziolo** [comment]
@sirreal, any chances you could have a look at this issue?

**Comment by sirreal** [comment]
@stefanfisk if you have a working change would you like to open a PR? It would be nice to have something to start from.

I don't have much bandwidth to dedicate to this myself, but I'll support with guidance and reviews as much as possible.

**Comment by slightlyfaulty** [comment]
Actually, this breaks when _any_ entrypoints share a runtime, e.g. when using [`dependOn`](https://webpack.js.org/configuration/entry-context/#dependencies). Because `runtimeChunk` is used to determine the output filename instead of `entrypointChunk`, the output filenames clash and get overridden.

I've tested @stefanfisk's [PR](https://github.com/WordPress/gutenberg/pull/26214) and it works great. Would be amazing if we could finally get it merged.

Maybe it's just me, but I don't see how efficient code-splitting has _ever_ been possible while this issue exists??

**Comment by gziolo** [comment]
> I've tested @stefanfisk's [PR](https://github.com/WordPress/gutenberg/pull/26214) and it works great. Would be amazing if we could finally get it merged.

Thank you for the reminder and for testing the patch proposed. Let's see what we can do to move it forward 👍🏻
