### ISSUE TITLE
Automate block documentation based on block.json data

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#24422]
There's a fair bit of automated documentation we generate based on code at the moment: [packages](https://developer.wordpress.org/block-editor/packages/), [data](https://developer.wordpress.org/block-editor/data/), [components](https://developer.wordpress.org/block-editor/components/), etc.

With more blocks supporting the `block.json` specification and more features being ported to it, it is a high-quality source from which we can extract a lot of information easily:

- block name
- block category
- block attributes
- [style attributes](https://github.com/WordPress/gutenberg/issues/22700)

For a start, one thing we could do would be to create a new top-level section called "Block Reference" that would list them all with their main data.

**Comment by nosolosw** [comment]
cc @mkaz @annezazu

**Comment by nosolosw** [comment]
https://github.com/WordPress/gutenberg/pull/24421 could have benefited from having an automated tool for this as well.

**Comment by JustinyAhin** [comment]
Hi @nosolosw @mkaz @gziolo 

I'd like to tackle this issue.

But I have a couple of questions/things I need to know.

I guess right now, there is no documentation that is generated based on JSON?

Also, from [this conversation](https://github.com/WordPress/gutenberg/issues/6190#issuecomment-495603517), I'm seeing that espree (https://github.com/eslint/espree) could be a good tool for doing such automation. Where could I start using it? I've been looking at its documentation and was a bit lost about whether or not it takes files as entry instead of JSON code directly.

If you know uses cases of that and can point me to them, that would be awesome.

Thanks :)

**Comment by nosolosw** [comment]
Nice!

I'm not aware of anything we generate from JSON that goes into the block editor handbook. I'm not sure either what use cases were I thinking back then but there doesn't seem to be a need for `espree` in this case ― processing a JSON from a node script should be enough. We have a few in https://github.com/WordPress/gutenberg/tree/master/bin/api-docs in case that gives you a place to start poking around.

Have you looked at [this other comment](https://github.com/WordPress/gutenberg/issues/6190#issuecomment-683401874) below? Looking at ways to integrate https://github.com/WordPress/gutenberg/issues/24152 into the block editor handbook would be cool.

**Comment by nosolosw** [comment]
I've used a script I've pushed to the `[add/block-json-extractor](https://github.com/WordPress/gutenberg/tree/add/block-json-extractor)` branch to list the block supports in a way that's useful to prepare the dev notes.

Hopefully, that could be taken forward to embed that info in some part of the block editor handbook.

**Comment by nosolosw** [comment]
In this space, there's also [this project](https://youknowriad.github.io/blockbook/) by Riad that would be great to integrate into the block editor handbook.

**Comment by mkaz** [comment]
Closed in #36183
