### ISSUE TITLE
music.youtube embedding abilities

### ISSUE THREAD

**Issue by tanjoymor** [WordPress/gutenberg#24475]
Currently, the YouTube embed block doesn't support the new `music.youtube` subdomain.

Would like to see this capability added please.

**Comment by aristath** [comment]
Does `music.youtube` even support embeds? I couldn't find anything, and when you try to share a song there's no embed option there either

**Comment by tanjoymor** [comment]
I'm not sure either, though it seems maybe not? Very limited information, all I could find was: https://support.google.com/youtubemusic/answer/9716522?hl=en and nothing about embedding.

**Comment by aristath** [comment]
Doesn't look like it's possible right now.
However, if/when YouTube Music supports oEmbed, it will work out of the box simply by pasting the URL in the editor :wink:

**Comment by ntsekouras** [comment]
> However, if/when YouTube Music supports oEmbed, it will work out of the box simply by pasting the URL in the editor

Actually it won't be supported out of the box due to the `RegExp` pattern here: https://github.com/WordPress/gutenberg/blob/48ff9a111c979455c47013f2ea1991270b9be10a/packages/block-library/src/embed/variations.js#L52

But it would be a small fix :)

I'll close this for now since it's not supported yet by `music.youtube`. - Thanks both for looking into this!
