### ISSUE TITLE
Mobile and Tablet preview not working with Undescores Theme

### ISSUE THREAD

**Issue by askel45** [WordPress/gutenberg#24585]
**Describe the bug**
I use the Underscores theme for my blog and the preview does not work with it for mobile and tablet. Instead, it shrinks into a small white box with a grey background.
1. Tablet preview https://prnt.sc/tzzikv
2. Mobile preview https://prnt.sc/tzzj8a
Is it because the theme is not built to support the block editor yet?

**Comment by talldan** [comment]
@askel45 Do you have metaboxes enabled at the moment?

There was a recent issue (https://github.com/WordPress/gutenberg/issues/23404) fixed by this change - https://github.com/WordPress/gutenberg/pull/24478. It sounds very similar.

The fix will be in Gutenberg plugin v8.8.0 (released on Wednesday) and WordPress v5.5.1.

**Comment by askel45** [comment]
@talldan yes I do (added by some plugins).

**Comment by talldan** [comment]
Thanks for confirming. I'll close this issue as fixed by #24478. 🎉
