### ISSUE TITLE
Navigation: Improve how non-link blocks appear in old `nav-menus.php` screen

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#24639]
If a user activates a theme that has `add_theme_support( 'block-nav-menus' )`, adds a non-link block to their Navigation, and then opens the old Menus screen (`nav-menus.php`), they will see the block they added as a Block menu item like so:

<img width="445" alt="Screen Shot 2020-08-19 at 11 09 42" src="https://user-images.githubusercontent.com/612155/90580660-c2912b00-e20c-11ea-94e1-935fd1be60cd.png">

There's a few improvements we could make here:

- Prevent user from being able to nest menu items underneath a Block menu item, since in most cases this requires changing the HTML in the Block menu item.

- If the theme does not have `add_theme_support( 'block-nav-menus' )`, properly indicate that the menu item will not display on the frontend.

See https://github.com/WordPress/gutenberg/pull/24503#discussion_r470446388.

**Comment by noisysocks** [comment]
> If the theme does not have add_theme_support( 'block-nav-menus' ), properly indicate that the menu item will not display on the frontend.

We'll need a simple design for this.

**Comment by Thelmachido** [comment]
Closing this issue due to the Navigation Editor project being moved to [an inactive status on the feature projects page](https://href.li/?https://make.wordpress.org/core/features/) in coordination with the project leads. If this work is picked back up, issues can be revisited and reopened as needed.

The work will continue on the navigation block.
