### ISSUE TITLE
Navigation: Improve how invalid non-link blocks appear in Navigation screen

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#24640]
If a user activates a theme that has `add_theme_support( 'block-nav-menus' )`, adds a non-link block to their Navigation, then switches away to a theme that _doesn't_ support `block-nav-menus`, they will still see the block they added in the Navigation screen like so:

<img width="961" alt="Screen Shot 2020-08-19 at 11 19 43" src="https://user-images.githubusercontent.com/612155/90581152-e3a64b80-e20d-11ea-94a4-4440c8dd64b7.png">

In this state, it is not possible to add additional non-link blocks. The previously added non-link block remains there so that no user data is lot as a result of changing theme.

Because the theme does not support `block-nav-menus`, this non-link block will **not** display in the site's frontend. The user must delete the block and potentially replace it with a regular link.

We should indicate to the user that the block is invalid and won't display in the site's frontend. The user should either change theme or delete/replace the block.

**Comment by shaunandrews** [comment]
Would it make sense to not show these blocks? Or to somehow collect them into an "Unsupported Blocks" section?

**Comment by draganescu** [comment]
Yes it would make sense as the blocks will not be rendered on the front end anyway. But maybe instead of hiding, mark them like #23573 suggests?

**Comment by Thelmachido** [comment]
Closing this issue due to the Navigation Editor project being moved to [an inactive status on the feature projects page](https://href.li/?https://make.wordpress.org/core/features/) in coordination with the project leads. If this work is picked back up, issues can be revisited and reopened as needed.

**Comment by Thelmachido** [comment]
Closing this issue due to the Navigation Editor project being moved to [an inactive status on the feature projects page](https://href.li/?https://make.wordpress.org/core/features/) in coordination with the project leads. If this work is picked back up, issues can be revisited and reopened as needed.
