### ISSUE TITLE
register embed Blocks failed after update

### ISSUE THREAD

**Issue by silvanarnet** [WordPress/gutenberg#24678]
I've updated WP Core from 5.4 to 5.5 and Gutenberg to 8.8.0. In the release Notes I saw that the embed block now is a single block with block variations. After the update i got some js errors, saying that these blocks aren't registered.

I am using the ghostkit plugin along with some others and a custom theme.

![image](https://user-images.githubusercontent.com/42134096/90732434-604b2f80-e2cb-11ea-8be6-325bb668ca0f.png)

**Comment by getsource** [comment]
Hi @silvanarnet!

I'm sorry it has taken so long for a reply on this issue.
It was discused during [a triage session today](https://wordpress.slack.com/archives/C02QB2JS7/p1612244321470000).

In testing markup from a block before the merge mentioned in the report, it was automatically migrated to the replacement single embed block.

Are you still experiencing this issue? If so, could you please provide some example markup for blocks that aren't getting migrated, so that it can be tested further?

Thanks so much!

**Comment by chaion07** [comment]
This came up once again in our [recent triage session](https://wordpress.slack.com/archives/C02QB2JS7/p1619500819320000). Seeing no response, (referring to @getsource comment) we feel it is okay to close this.

> 
> In testing markup from a block before the merge mentioned in the report, it was automatically migrated to the replacement single embed block.
> 
> Are you still experiencing this issue? If so, could you please provide some example markup for blocks that aren't getting migrated, so that it can be tested further?
>

Thank you!
