### ISSUE TITLE
Help Developers Transition to React & Gutenberg

### ISSUE THREAD

**Issue by VR51** [WordPress/gutenberg#2468]
Reading the discussions surrounding Gutenberg it looks like Gutenberg will break a lot of plugins, many themes and will ruin post editor customisations made by both developers and code tinkerers. End users and developers will be forced to use and work with Gutenberg so WordPress has the responsibility to own the problems Gutenberg will create.

I assume WordPress Core will do its best to minimise site breakage but we do know sites and hearts will break when Gutenberg hits. It is too big a change with the past to not anticipate breakage.

Some ways WordPress might consider to help developers adapt to Gutenberg, to motivate developers to upgrade their plugins to work with Gutenberg, and to help site owners who are not developers but whom tinker occasionally with code to transition to Gutenberg would be for Automatic/WordPress to,

- Offer grants to developers of non commercial plugins where those plugins are complex or widely used
- Provide comprehensive React training to all interested parties by text chat, video sessions and easy to read documentation
- Offer to takeover development of old plugins where the developer has no wish to adapt the plugin to Gutenberg or where the developer has left the WP world
- Offer to directly assist plugin developers to rewrite their plugin code to work with Gutenberg

I don't doubt that WordPress will provide assistance to developers and end users. WordPress is friendly like that. But that assistance needs to be more than a few documents and many self promoting videos about the benefits of Gutenberg and React.

A new ecosphere of plugins and themes will arrive to replace non Gutenberg compatible plugins but it is unfair for WordPress to tell developers that their feelings, investment in WordPress and time spent with WordPress don't count where Gutenberg is concerned: it's happening, get used to it.

That last statement might seem melodramatic but I can see people walking away from WordPress unless WordPress goes out of its way to smooth the migration to Gutenberg.

This is a conversation that needs to begin now rather than be left until a few months before Gutenberg goes live.

**Comment by epakrat** [comment]
https://wptavern.com/facebook-isnt-budging-on-reacts-bsd-patents-license

Perhaps the Gutenberg team needs to consider a transition of their own before asking others to invest themselves in a framework that may ultimately dropped from Gutenberg later and not used in core?

**Comment by StaggerLeee** [comment]
I did not know Jetpack is using React.

**Comment by justintadlock** [comment]
I think this topic is worth discussing, particularly with the merge proposal set for December.  We're talking just a few months away.

The current documentation on building with Gutenberg is the equivalent of a "Hello World" program.  I know we're in "build mode" right now.  However, there should be a balance between building things and documenting them as we go along.

This is the missing component between many of the devs who are pushing back against Gutenberg and the team.  Teach us how to build things with it.  Gain developer trust.

I have dozens of plugins that Gutenberg will directly impact.  As a single developer, this is going to take months, perhaps over a year, to update everything.  I'd like to get started doing that sooner rather than later.

**Comment by karmatosed** [comment]
Whilst I understand the intention of this issue, it's not something that needs an issue right now. Education and transition is something we an all work on as a community.
