### ISSUE TITLE
Block Inserter, between blocks, no longer shows all blocks

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#24744]
**Describe the bug**
Why does the Block Inserter between each block no longer show all blocks? Why is it showing these 6 blocks? They're **not** the Most Used blocks. I have **never** used the RSS block even once so why is it showing?

Why am I forced to open the Block Inserter panel when I click the **Browse all** option?

<img width="1043" alt="screenshot_83" src="https://user-images.githubusercontent.com/2078245/90974495-0ec2cf00-e56f-11ea-96e2-7cfd8bc4656a.png">

Not only am I forced to open the Block Inserter panel, by doing so, you close the Settings Sidebar on me, forcing me to have to reopen that again as well, after I insert the new block.

Vid: https://share.getcloudapp.com/jkuZ4bYR

You're making it harder and harder, and more time consuming, to edit content with each release! Not to mention, how many extra clicks I now need to make to open and reopen panels because you close them on me, or because you don't show me all the blocks I want to see.

**To reproduce**
1. Edit page
2. Hover cursor between blocks to show Add Block icon

**Expected behavior**
Can no longer scroll through all blocks when trying to use block inserter between blocks

**Editor version (please complete the following information):**
-WordPress version: [5.5]
-Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [default]
-If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

Desktop (please complete the following information):
-OS: macOS Catalina 10.15.6
- Browser: Firefox 79.0

**Comment by gigatyrant** [comment]
I agree.

Is it possible to display more blocks, or all blocks with a scroll as before?

This adds unnecessary steps for many themes that do not use the options in the left column.

**Comment by tellthemachines** [comment]
Thanks for the feedback @maddisondesigns ! You can find some context on the quick inserter changes in #22789. 

> Why is it showing these 6 blocks? They're not the Most Used blocks. I have never used the RSS block even once so why is it showing?

Block usage data is stored in the browser, so if you delete your local storage, or switch to another browser, those preferences will be lost. That's my best guess as to what is happening there, but it's odd that the RSS block should be there as by default, if there are no user preferences, they should appear in the [order they are registered](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/index.js#L124).

Regarding the Settings sidebar closing when the inserter panel opens, that one has generated a lot of discussion - see #22525 and #23968 - and it's not super clear what the ideal behaviour should be 😅

**Comment by maddisondesigns** [comment]
@tellthemachines I can't see any explanation within #22789 as to why the Quick Inserter was changed to its current iteration. Like most of the UI changes you've performed in the past couple of years, this simply makes the Block Editor more cumbersome and harder to use, and forces me to make more clicks.

My browser history rarely gets deleted. The "Most used" blocks within both the Quick Inserter and the Block Inserter have never accurately displayed the actual most used blocks. I've raised this issue multiple times across multiple github issues. There's obviously an issue somewhere as it just doesn't work properly. It's never worked properly, from day one.

The answer to the issue of the closing Settings Sidebar seems pretty obvious to me. If Gutenberg closes a panel that I have open, just so you can display some other panel, then it's Gutenberg's responsibility to re-open that panel when the other one is closed. This seems like common sense. Don't close my panels and then force me to have to re-open them all the time! @folletto mentions the exact same thing in [this comment](https://github.com/WordPress/gutenberg/issues/23968#issuecomment-658932816).

> For me the rule is simple: if it was open, reopen.

**Comment by annezazu** [comment]
>The answer to the issue of the closing Settings Sidebar seems pretty obvious to me. If Gutenberg closes a panel that I have open, just so you can display some other panel, then it's Gutenberg's responsibility to re-open that panel when the other one is closed.

Looping back on this issue as I stumbled across a duplicate today and tested again with WP 6.6.2 only to find that the settings sidebar will remain open if you use the "browse all" option now:

https://github.com/user-attachments/assets/8f48448f-1092-4288-9bf3-1eadbe53ea66

The quick inserter has also evolved to, at times, prioritize patterns rather than blocks: https://github.com/WordPress/gutenberg/issues/36697 For example, when you're at the root of a template. 

In terms of why the quick inserter was changed to begin with, it has to do with information density from what I can gather in this original issue:  https://github.com/WordPress/gutenberg/issues/21080

It was meant to be highly contextual and prioritizing the ability to search to find what you need. When I use playground aka a super fresh site without any history, it shows the most commonly used blocks:

![Screenshot 2024-09-05 at 7 54 48 PM](https://github.com/user-attachments/assets/5f89a664-3f73-41ec-b047-2c1f71cb7f3e)

As a result, I'm going to close this out but I encourage new issues to be opened to keep refining the experience. I'll be doing the same as I'm finding it's really hard to initiate the quick inserter recently!
