### ISSUE TITLE
Text inputs inside cover block has white text on white background when not in focus

### ISSUE THREAD

**Issue by vaakash** [WordPress/gutenberg#24741]
If any text input is placed under "cover block" (in block editor), the input text is white (not exactly white but a very light grey) when not in focus. It gets back normal text color when input is focussed.

For example, Add "shortcode" block inside "cover block" and the text is white when not in focus.

**To reproduce**
1. Open block editor
2. Insert the "cover block"
3. Insert a "shortcode block" inside the "cover block"
4. The text of the input text element is white when not in focus.

**Expected behavior**
The input text should not be white when not in focus.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/299561/90973635-909c0380-e541-11ea-815d-84aca11e440d.PNG)
![Capture2](https://user-images.githubusercontent.com/299561/90973636-9265c700-e541-11ea-8b70-7dbe95276499.PNG)

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.4.2]
- It is the "default" block editor.

**Desktop**
 - Browser [chrome]

**Comment by talldan** [comment]
I wasn't able to reproduce this, but I tested using WordPress 5.5, and I have a feeling it might have been fixed since:
<img width="569" alt="Screenshot 2020-08-28 at 4 41 15 pm" src="https://user-images.githubusercontent.com/677833/91540403-540b4600-e94d-11ea-8b0e-c179564e6c20.png">

 @vaakash do you have an environment where you might be able to test using WordPress 5.5?

**Comment by vaakash** [comment]
@talldan I just upgraded to v5.5 and I see the issue is fixed. Thanks for your time in checking this !
