### ISSUE TITLE
Buttons Block: Add font-size controls

### ISSUE THREAD

**Issue by alaczek** [WordPress/gutenberg#24776]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to control button size (both font-size and padding).

**Describe the solution you'd like**
This could be done by:
* having separate padding and font-size settings
* combining both in one setting. I quite like how this is done in Atomic Blocks plugin:

![Ns2VVDIhyP](https://user-images.githubusercontent.com/4550351/91363860-e96ce400-e840-11ea-8e8a-bef561d2f298.gif)

Separate settings would give us more control while the combined approach makes for a simpler UI.

**Comment by paaljoachim** [comment]
I believe that the Buttons block could also have Typography controls.
I added the issue for it here: https://github.com/WordPress/gutenberg/issues/29112

Margin/padding would be inside a Dimensions panel mentioned in your issue here: https://github.com/WordPress/gutenberg/issues/29098

I believe we can close this issue. What do you think @alaczek ?

**Comment by alaczek** [comment]
Yep, I think so!
