### ISSUE TITLE
 Multi select paragraph block formatting

### ISSUE THREAD

**Issue by joweber123** [WordPress/gutenberg#24777]
At the moment, when multiple paragraph blocks are selected, text formatting options disappear.

![Screen Shot on 2020-08-25 at 13:40:16](https://user-images.githubusercontent.com/24914028/91123731-87916a80-e6d8-11ea-9f36-a4dc26fa09e3.png)

It would be nice if those text formatting options were retained if a user would, for example, like to make multiple blocks **bold.**

![Screen Shot on 2020-08-25 at 13:37:49](https://user-images.githubusercontent.com/24914028/91123574-2e293b80-e6d8-11ea-9fe1-1a2f8d3f9924.png)

It looks like a lot of progress has been made on this already with the following merge - https://github.com/WordPress/gutenberg/pull/22470 but I do not see this other issue being addressed in any other feature requests currently.

**Comment by youknowriad** [comment]
Hi There! these are "format controls" that applies to text selections while multi-block selection is not "text selection", the whole blocks are selected.  Unfortunately, this won't be supported unless we also support text selection across blocks. It's a topic that was discussed several times in the past but because of the complexity and the difficulty to support that in a generic way, it's probably not going to be pursued in the near feature.

I think we should just close this issue for that reason.

**Comment by joweber123** [comment]
OK.  As long as this is something on the radar of developers feel free to close the issue.  I do think this would be much appreciated by users if it could be implemented in the future.  Thank you for the detailed explanation.

**Comment by youknowriad** [comment]
To be completely clear What I'm trying to say that it's not something we'll be able to implement in the future unless at some point the block-editor supports cross ablock selection which is probably not going to happen IMO (at least not in the near future).
 
This is unfortunate, but in all software designs there are tradeoffs, and one of the important tradeoffs made for Gutenberg (allowing simple third-party blocks API and separate content editables per block) make this very hard.
