### ISSUE TITLE
Featured Image Block: Add image from block

### ISSUE THREAD

**Issue by manwithpowers** [WordPress/gutenberg#24813]
Right now the Featured Image can't be selected or edited directly from the block itself.
I understand why the Featured Image is chosen from the sidebar as it's something general to the entire post, but nonetheless I find it very counter-intuitive that you can't ALSO select an image directly from the Featured Image block. Most of the non-technical people working on sites I'm developing don't understand why the Featured Image needs to be added in the sidebar but then actually added to the page separately, it just becomes another thing I have to train them on. It's a small thing but worthy of consideration IMO.

I think it would make a lot of sense (and be more intuitive to laypeople, ie most of the folks I'm working with), if the Featured Image block behaved similar to a standard image block, with the ability to select/re-select/edit an image right in the block.

Alternatively, perhaps the image can be selected from the block sidebar editor, when the Featured Image block is selected?

To be clear, I'm not suggesting removing the Featured Image from the post sidebar, I'm suggesting that the ability to select/edit the Featured Image _also_ be possible directly in the block.

**Comment by mtias** [comment]
Absolutely! That's the path we are in — the _featured image_ block is currently a "work in progress" block. It should definitely allow setting and unsetting the featured image from the block itself. There's also been some discussions about converting any existing image in a post to a featured image block, so that you can easily turn an existing image into the featured one from the post itself.

**Comment by manwithpowers** [comment]
Excellent to hear, thanks very much for the response.

**Comment by mtias** [comment]
Thank you for sharing your thoughts
