### ISSUE TITLE
Expanded instructions for disabling Block Directory

### ISSUE THREAD

**Issue by MarcinKilarski** [WordPress/gutenberg#24830]
Could we add to instructions both examples of how to disable the Block Directory from a plugin and a theme? Otherwise, people might not know that they should use a different hook than 'plugins_loaded' when disabling the Block Directory from a theme. Thank you.

From a plugin:
/**
* Disable Block Directory
*/
add_action('plugins_loaded', 'myplugin_disable_block_directory');
function myplugin_disable_block_directory()
{
   remove_action( 'enqueue_block_editor_assets', 'wp_enqueue_editor_block_directory_assets' );
   remove_action( 'enqueue_block_editor_assets', 'gutenberg_enqueue_block_editor_assets_block_directory' );
};

From a theme:
/**
* Disable Block Directory
*/
add_action('admin_init', 'mytheme_disable_block_directory');
function mytheme_disable_block_directory()
{
   remove_action( 'enqueue_block_editor_assets', 'wp_enqueue_editor_block_directory_assets' );
   remove_action( 'enqueue_block_editor_assets', 'gutenberg_enqueue_block_editor_assets_block_directory' );
};

**Comment by JustinyAhin** [comment]
Hi @MarcinKilarski 
Thanks for opening the issue.

There is already some documentation about how to disable the block directory through plugin here https://developer.wordpress.org/block-editor/developers/filters/editor-filters/#block-directory.

It has been added in this PR https://github.com/WordPress/gutenberg/pull/24357.

IMO, it makes more sense to disable this feature in a plugin (MU Plugin) rather than directly in the theme.

**Comment by JustinyAhin** [comment]
I am going to close this issue.
Feel free to open a new one if needed :).
