### ISSUE TITLE
FSE: Fall back to Top level PHP theme templates when no FSE templates are available

### ISSUE THREAD

**Issue by tomjn** [WordPress/gutenberg#24834]
Currently template posts are used, falling back to block template files in the theme.

However, if neither exist, then no template is available. This also means that using full site editing requires a complete site rebuild.

In order to provide a fallback and migration path for non-block based themes, PHP templates should be added as a fallback for top level templates. This would mean files such as `home.php`, `single.php`, `archive.php`, etc would be loaded if no FSE equivalent is available. This does not apply to template partials however, e.g. `get_template_part( 'foo', 'bar' );` would work the same as it always has in a PHP template, and no new functionality would be added to FSE block templates.

This also means that sites can convert their themes one template at a time, or conduct partial migrations without rebuilding an entire site from scratch.

Related to #24803

**Comment by aristath** [comment]
I was thinking a bit about this one... The issue is that we need to check if a block-template exists _before_ we hijack the query-template filter.
So I did a quick test by replacing the `gutenberg_add_template_loader_filters` function with this one:

```php
function gutenberg_add_template_loader_filters() {
	foreach ( get_template_types() as $template_type ) {
		if ( 'embed' === $template_type ) { // Skip 'embed' for now because it is not a regular template type.
			continue;
		}

		$type = preg_replace( '|[^a-z0-9-]+|', '', str_replace( '-', '', $template_type ) );

		$template_override = gutenberg_override_query_template(
			'',
			str_replace( '-', '', $template_type ) . '_template',
			apply_filters( "{$type}_template_hierarchy", array( "{$type}.php" ) )
		);
		if ( $template_override ) {
			add_filter( str_replace( '-', '', $template_type ) . '_template', 'gutenberg_override_query_template', 20, 3 );
		}
	}
}
```

The above code works, so it should be possible to achieve what we want here by tweaking the logic of the above proof-of-concept to optimize it... We just need to discuss a bit and figure out where we want to hook and how to handle the conditional loading of FSE templates.

**Comment by aristath** [comment]
This was done in https://github.com/WordPress/gutenberg/pull/29026 and further refined in https://github.com/WordPress/gutenberg/pull/31604
