### ISSUE TITLE
Getting White Screen After Updating Gutenberg!?

### ISSUE THREAD

**Issue by undertaker001** [WordPress/gutenberg#25033]
**Describe the bug**
After updating to latest gutenberg version. I am unable to edit post. Keep Getting White Screen..
**To reproduce**
1. Go to 'Posts'
2. Click on 'Edit post'
3. Nothing, just white screen.
4. Tried 3 different browsers, same issue. 

**Expected behavior**
It should open edit post page.

**Screenshots**
![white screen](https://user-images.githubusercontent.com/70372403/92084137-61f31800-ede0-11ea-8a69-b647e6b7622f.jpg)
![white screen12](https://user-images.githubusercontent.com/70372403/92091517-4bea5500-edea-11ea-9e1b-c8a971d0d247.jpg)

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.5.1]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? ["Gutenberg plugin"]
- If the Gutenberg plugin is installed, which version is it? [8.9.0]

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Edge]
 - Version [86]

**Comment by regevbr** [comment]
Same here - had to rollback to 8.8.0

**Comment by undertaker001** [comment]
> Same here - had to rollback to 8.8.0

Yeah... rolling back fixed the issue...

**Comment by aristath** [comment]
I'm afraid I was unable to replicate this one... It could be a conflict of some sort, could you all 

Which version of WordPress are you using?
Did you try switching to the default twentytwenty theme?
Did you try disabling all 3rd-party plugins?

**Comment by regevbr** [comment]
Sadly I didn't have the time to do it and looked for a quick fix. Maybe my issue is the non default plugin Travelera

#### Editor version:
WordPress version: 5.5.1
Gutenberg plugin 8.9.0
Theme: Travelera

#### Desktop (please complete the following information):
OS: Ubuntu 18
Browser Chrome
Version 85

**Comment by undertaker001** [comment]
> I'm afraid I was unable to replicate this one... It could be a conflict of some sort, could you all
> 
> Which version of WordPress are you using?
> Did you try switching to the default twentytwenty theme?
> Did you try disabling all 3rd-party plugins?

Already shared everything (if you care to put some time and read the actual post). Check the attached screenshots too. 
Theme is not the issue.
If its a conflict then again it's gutenberg fault. You keep breaking functionality in each update (other plugins dev can't keep up with the bugs of gutenberg). And we users can't do that testing thing every time (Literally, each update has some weird issue everytime and also thanks for breaking up the classic editor in new WP 5.0 update, forcing users to use gutenberg), if some other thing messed up by disabling plugins then you again going to blame us. -_- You devs should understand by now what is the problem. already given you console error report yet you still unable to figure out the problem. That is some next level bug fixing i would say. And please this time come up with better excuse than saying "we do it for free blah blah blah".

**Comment by aristath** [comment]
> Already shared everything (if you care to put some time and read the actual post). Check the attached screenshots too

As I already mentioned, I am unable to replicate the issue.
I am testing on Ubuntu, with Firefox, on a clean WP installation, using the default theme and no 3rd-party plugins installed.
On its own Gutenberg doesn't throw any errors. Which leads me to believe this is due to a conflict with a 3rd-party plugin. But there are thousands of plugins out there, so it's impossible for us to just guess which one causes the issue.

> If its a conflict then again it's gutenberg fault.

Perhaps you're right. It could be Gutenberg's fault, or it could be the 3rd-party's fault, or it could also be no one's fault. The fact that something went wrong doesn't necessarily mean that someone did something wrong.
That's why I asked if you disabled 3rd-party plugins... It is one of the easiest methods to identify where the issue lies. If we can understand that Gutenberg + plugin X causes an issue, then we can investigate, replicate, and find a solution.
But without any extra information I'm sorry to say no developer will ever start testing thousands of plugins both premium and free to find the one that causes an issue when combined with Gutenberg.

We're willing to help, but we can't do much unless we know _how_ things break.
If all 3 people in this issue for example report that they all use plugin X, then we know that's the common denominator and we can work with that. If the problem is not limited to a compatibility with a single plugin but spans multiple plugins, then we need to investigate what they have in common and how they affect Gutenberg, what throws the error.
But without any extra info, we can't do any of that. There's nothing for us to actually test.

> And we users can't do that testing thing every time

Gutenberg by its nature is a feature/experimental plugin. That is its role, it brings in the form of a plugin things that have been tested and have been deemed ready for production - but not ready for stable WordPress Core yet. The purpose of installing Gutenberg is to test the next, upcoming features...

If you want to help us figure out what the issue is and how to fix it so that the next person has a better experience, we'd greatly appreciate it. That's why we're here, to get things ready in the Gutenberg plugin and ultimately ship them in WordPress Core :+1:

**Comment by regevbr** [comment]
@aristath here is a list of my installed plugins:
- Accelerated Mobile Pages
- Elementor
- Envato Market	
- GA Google Analytics
- Gutenberg
- Increase Maximum Upload File Size
- Lazy Load - Optimize Images
- LiteSpeed Cache
- Mashshare Share Buttons
- MC4WP: Mailchimp for WordPress
- Meta Box
- One Click Demo Import
- Polylang
- Redux
- Shield
- SSL Insecure Content Fixer
- Sucuri Security - Auditing, Malware Scanner and Hardening
- Travelera Elementor Addons
- Travelera Share Buttons
- UpdraftPlus - Backup/Restore
- WooCommerce
- WP Mail SMTP
- Yoast SEO

And as mentioned before I use the Travelera theme with Wordpress 5.5.1

**Comment by aristath** [comment]
Thank you @regevbr :+1: 

I was able to replicate now by doing the following:
* Enabled the Yoast SEO plugin
* Created a new post, added a title **and a featured image**
* Saved the post, reloaded the page and got the blank screen.

I removed the needs-testing and needs-more-info tags, and marked this one as a bug

**Comment by regevbr** [comment]
Yes I think that the error I saw in the console was related to a picture that its URL was set on an undefined variable. Great work!

**Comment by regevbr** [comment]
@aristath thanks so much for the swift response! I can confirm that 8.9.1 solved the issue
