### ISSUE TITLE
Disable download button in audio block

### ISSUE THREAD

**Issue by AiratHalitov** [WordPress/gutenberg#25121]
**Is your feature request related to a problem? Please describe.**
Not all audio is allowed to download. The user needs to be given the option to hide the Download button.

![image](https://user-images.githubusercontent.com/4050715/92410177-ba1d7780-f15c-11ea-8f08-1a441f48859b.png)

**Describe the solution you'd like**
Add ability to disable Download button in audio block settings. 
**Before:**
![image](https://user-images.githubusercontent.com/4050715/92410254-f81a9b80-f15c-11ea-9fa3-c71b501dc39f.png)
**After:**
![image](https://user-images.githubusercontent.com/4050715/92410422-72e3b680-f15d-11ea-8992-516a5589f897.png)

Gutenberg 8.9.2
WordPress 5.5.1

**Comment by ntsekouras** [comment]
By testing in Chrome (greater than version 58), Safari and Firefox, I could see that `download` is shown only in Chrome's `audio` element's implementation. I haven't looked deep enough but since Gutenberg `audio` block is implemented with `audio` HTML element, this seems to be internal implementation per browser(engine).

Since Chrome is widely used, there could be an addition of this option with a note, but would be irrelevant for other browsers..
I tested it quickly and can be achieved with `controlsList` attribute ([ref here](https://developers.google.com/web/updates/2017/03/chrome-58-media-updates#controlslist)).

Would it make sense to include this option though with the above concerns? I'd like some more opinions on this.

-cc @mcsf @youknowriad 

I've also created a quick draft PR for any testing purposes if it will be decided to be implemented. (https://github.com/WordPress/gutenberg/pull/25191)

**Comment by aristath** [comment]
Considering `controlsList` is only available in Chrome and its derivatives, I don't think this would make sense to add at this point in time... If [browser support](https://caniuse.com/mdn-api_htmlmediaelement_controlslist) improves to include Firefox & Safari then at least that would cover the majority of users.

**Comment by mcsf** [comment]
I second @aristath's opinion.

> Since Chrome is widely used, there could be an addition of this option with a note, but would be irrelevant for other browsers..
> I tested it quickly and can be achieved with `controlsList` attribute ([ref here](https://developers.google.com/web/updates/2017/03/chrome-58-media-updates#controlslist)).
> 
> Would it make sense to include this option though with the above concerns? I'd like some more opinions on this.

This feature is likely to introduce confusion for users, and we'd providing a very poor contract if site owners believe their content is "safe" behind a no-download directive that only one browser honours (not to mention that files can easily be downloaded regardless of that button, but that's a different topic).

Ethically or symbolically, I also think it would do everyone good if WordPress and Gutenberg don't blindly follow Chrome's latest implementations, _especially_ when they are experimental, [as is the case with `controlsList`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/controlsList).

I suggest closing this issue and revisiting if and when this interface becomes widely supported.

**Comment by ntsekouras** [comment]
>This feature is likely to introduce confusion for users

Thank you for reporting this @AiratHalitov, but based on the research, support and all the above reasons I will close this issue and we can revisit it in the future.
