### ISSUE TITLE
The image from the site logo block can not be removed from the customizer

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#25173]
**Describe the bug**
If a full site editing theme has theme support for the custom logo, 
the same image is used in the block and in the customizer option.
It is possible to replace the image using the customizer option, and this is reflected in the block.

But if the logo is removed in the customizer option, this setting is being reset -removing the image does not work. 
There are no error messages but once you refresh the page, the image from the block is present again.

**To reproduce**
1. Enable full site editing.
2. Enable a theme with support for full site editing and `add_theme_support( 'custom-logo' );`
3. Add a site logo block in the editor.
4. Go to the customizer and remove the logo and publish the changes.
5. Refresh the page to see the image return to the setting.

**Expected behavior**
Either remove the image from the block, leaving an empty block in the editor, 
show an error message, or disable the remove logo feature.

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Gutenberg: Version 8.9.3

**Desktop (please complete the following information):**
 - PC windows 10
- Chrome Version 85.0.4183.83

**Comment by ockham** [comment]
cc/ @pablinos @scruffian since I believe this reflects the Core unit test errors that we've discussed internally (and that I've mentioned [here](https://github.com/WordPress/gutenberg/issues/26418#issuecomment-724037229)).

**Comment by ockham** [comment]
Sharing my internal comment:

> I'll recap key findings from @bartkalisz @scruffian @pablinos @jeherve (thanks all!):
> 
> The `test_get_custom_logo` and `test_has_current_logo` tests are current failing; more precisely, it's the final assertion after `$this->_remove_custom_logo()`, shown here for `test_get_custom_logo`:
> 
> ```
> /**
>  * @group custom_logo
>  *
>  * @since 4.5.0
>  */
> function test_get_custom_logo() {
> 	$this->assertEmpty( get_custom_logo() );
> 	$this->_set_custom_logo();
> 	$custom_logo = get_custom_logo();
> 	$this->assertNotEmpty( $custom_logo );
> 	$this->assertInternalType( 'string', $custom_logo );
> 	$this->_remove_custom_logo();
> 	$this->assertEmpty( get_custom_logo() );
> }
> ```
> 
> The reason is that if the custom logo is removed, Gutenberg kicks in and adds the site logo, as per https://github.com/WordPress/gutenberg/blob/d8188cdd45f93d9c0b3223ba59b87c815e0b4390/packages/block-library/src/site-logo/index.php#L57-L68
> 
> That last filter is added to the `theme_mod_custom_logo` hook by the `site-block` registration function: https://github.com/WordPress/gutenberg/blob/d8188cdd45f93d9c0b3223ba59b87c815e0b4390/packages/block-library/src/site-logo/index.php#L42-L55
> 
> Note that the function above also contains logic to sync the site logo with the theme modified logo. We believe that this is what causes the last assertion to fail, after the custom logo is removed (but persisted in that option).
> 
> The latter block is registered unconditionally for GB 9.3 as per the following change, while previously it was only registered if the FSE experiment was enabled: https://github.com/WordPress/gutenberg/commit/d8188cdd45f93d9c0b3223ba59b87c815e0b4390#diff-92dc6950bcaf54290625664019ea23b023cb3f156de19586612c8d3e3cf52adcL46

**Comment by noisysocks** [comment]
Removing this from the 5.7 Must Haves board as it relates to full site editing which isn't shipping in 5.7.

**Comment by creativecoder** [comment]
It looks like this issue is resolved by https://github.com/WordPress/gutenberg/pull/30427

**Comment by ockham** [comment]
> It looks like this issue is resolved by #30427

Yeah, it appears that #30427, plus the fact that the Customizer is now disabled for FSE themes, have resolved this issue.

**Comment by creativecoder** [comment]
> plus the fact that the Customizer is now disabled for FSE themes, have resolved this issue.

@ockham Can you say more about how disabling the Customizer for FSE themes affects this issue with the Site Logo block?

With the potential adding of the Site Logo block to WP 5.8, for use without the site editor and while the Customizer is available, will there be any problems?

I looked at how it's working now and it seems okay:

- If you update the logo through the Customizer, that setting updates the theme option and copies it to the `sitelogo` option.
- If you remove the logo from the Customizer, it deletes the theme option and the `sitelogo` option.
- If you update the logo in the Site Logo block, that updates the `sitelogo` option, which will override any theme logo option that's set (and thus show the new `sitelogo` in the Customizer)
- If you remove the logo from the Site Logo block (not currently possible), the Customizer will revert to the theme option for the logo, if there is one.
- When you switch themes, if there's a `sitelogo` set, you'll see that as the logo in the Customizer and Site Logo block (because it overrides the theme option). Otherwise you'll see the theme option logo for the new theme in the Customizer, if there is one set, and nothing in the Site Logo block.

**Comment by pablinos** [comment]
> If you remove the logo from the Site Logo block (not currently possible)

Isn't that the problem this issue was concerned with, that the logo would keep getting reassigned to the Customizer version?

If it's not possible does that mean it's not fixed?

**Comment by ockham** [comment]
> > plus the fact that the Customizer is now disabled for FSE themes, have resolved this issue.
> 
> @ockham Can you say more about how disabling the Customizer for FSE themes affects this issue with the Site Logo block?

Sorry for the late reply, I only saw this now. The fact that the customizer is disabled for FSE themes is relevant in that it makes it impossible to delete the custom logo from there -- see the repro instructions in the original issue description. If that's no longer possible, the site block becomes the only way to change the site logo.

> With the potential adding of the Site Logo block to WP 5.8, for use without the site editor and while the Customizer is available, will there be any problems?

Seems like 😅  -- see #32229, #32229, and @pablinos' [comment below](https://github.com/WordPress/gutenberg/issues/25173#issuecomment-853547094).

---

It's been a while since I looked into this, and my memory isn't super fresh on this one. I collected some information in a previous PR (https://github.com/WordPress/gutenberg/pull/26895) -- maybe that can provide some more insight, in case that things are still broken?

cc/ @fullofcaffeine @david-binda since y'all were having problems with the site logo block on WP.com.

**Comment by ockham** [comment]
One thing I'd recommend at this point -- since the Site Logo has seen so much back and forth -- would be some solid unit test coverage to define the desired behavior. I think it's partly covered by unit tests in `wordpress-develop` already, so it might be a matter of "just" running those tests with GB enabled.

**Comment by pablinos** [comment]
@grantmkin I found some notes I made about this issue when we went through it together in December! I think we decided the main part of the solution is for the behaviour to change based on the type of theme that is active, or being activated.

- Traditional themes should display the `custom_logo` option
- Block themes should display the `sitelogo` option
- On theme activation, the option should be copied to the other option based on the theme type.
- As the option is changed, the syncing should happen one way, again based on the theme type.

But, as @ockham says, things have moved on considerably since then. With the customizer being disabled for FSE, I don't know if this is still an issue, and it seems from your testing, that it does behave as expected. My only question is whether not being able to remove the logo is an example of the functionality being missing or broken.

Adding some tests would be great too, but as this relies on different themes being activated and the options being accessed via the Customizer and the block, it could be a little hard to isolate. If there are tests already, that would be great.

**Comment by creativecoder** [comment]
> I found some notes I made about this issue when we went through it together in December! ...

Thanks @pablinos, I mentioned this to you last week, but adding here as well for anyone following the issue. Because the Site Logo block will now be available in the post/template editor in WP 5.8, it no longer makes sense to divide how the logo works based on theme type. You'll be able to use the Site Logo block and access the custom logo settings in the Customizer with "non FSE" themes.
