### ISSUE TITLE
Widget screen: Add Drag & Drop of widgets between collapsed widget areas

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#25243]
It looks like drag & drop is not at the moment working.

It would be helpful to be able to drag and drop widget/blocks between one widget area and another.

Example from the old Widget Screen:

![Drag-drop-old-Widget-Screen](https://user-images.githubusercontent.com/5323259/92925734-39e86200-f43b-11ea-8f9d-98ce8ff47a74.gif)

**Comment by youknowriad** [comment]
Drag and drop between widget areas is already available. The issue now is that the areas need to be opened.

**Comment by manooweb** [comment]
> Drag and drop between widget areas is already available. The issue now is that the areas need to be opened.

Do you mean, because the second widget area isn't opened we can't drag and drop form one to the other ?

What I noticed

1. when a widget area is opened and not empty I can move a widget from another widget area 👍
2. when a widget area is closed I can't move a widget from another widget area. It needs to be opened automatically as in the legacy widget page to be able to drop the widget.
3. when a widget area is empty, it is always closed, so we can't move a widget from another widget area to an empty widget area. See the second point

**Comment by paaljoachim** [comment]
I believe we can go ahead and close this issue. As the PR for dragging & dropping widgets between widget areas have been merged.
