### ISSUE TITLE
Scheduled Post time has mismatched between time shown and hint

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#25256]
**Describe the bug**

When displaying the time in the calendar, a hint was added in #23400 so the user would know what timezone the post was being schedule in. 

The issue is it now appears that the time being selected is the user's time and not the server time.

**To reproduce**
1. Set the site time to a different timezone, this example site set to EDT
2. Create a new post and schedule the post time
3. Notice the hint shown is EDT, but the time picked is in PDT

**Expected behavior**

The time shown should match the hint of what time zone it is being set to.

**Screenshots**

![date-time](https://user-images.githubusercontent.com/45363/92948662-91240d80-f40e-11ea-953a-900c41e4ae92.gif)

Related trac ticket: https://core.trac.wordpress.org/ticket/50624

**Comment by vcanales** [comment]
Another thought that comes to mind: the real base of the problem is that the site is providing the frontend with an already formatted time, which makes it harder to manipulate, as the new variable of 'timezone' is introduced. It would perhaps be best if the system reported all times as UTC. 

If we take a look at the [tests on `@wordpress/dates`](https://github.com/WordPress/gutenberg/blob/master/packages/date/src/test/index.js#L76) for instance, they all rely on UTC times being provided—ie. they're all suffixed with `Z`.

**Comment by vcanales** [comment]
This turned out to be a deeper issue that it seems, in my opinion.

When handling dates on the frontend, the multiple possible sources of truth must be kept in mind in order to avoid inconsistencies with the “actual” dates. The WordPress entity’s “date” and “date_gmt” attributes should be considered the source of truth when handling WordPress entities.

### The happy path.

The user’s Browser timezone is UTC-3. The user sets the site’s time to UTC-3 as well. The user creates a post; the following timestamps are set in the corresponding attributes. date is the site’s local time, date_gmt its UTC(GMT/Zulu Time) equivalent.

| date | date_gmt |
|---|------|
| 2020-09-23T17:18:00 | 2020-09-23T20:18:00|

Gutenberg’s dateI18n function is called, in order to display the post’s formatted date on the editor—the `date` parameter is used

```js
> dateI18n('F j, Y g:i a', '2020-09-23T17:18:00')
< September 23, 2020 17:18 pm
```

This scenario is well tested, and it works correctly!

### The not so happy path

The user’s Browser timezone is still UTC-3, but they’ve set the site’s time to UTC-5. At 5:18pm UTC-5, the user creates a post; the following timestamps are set:

| date | date_gmt |
|---|------|
| 2020-09-23T17:18:00 | 2020-09-22T22:18:00|

The formatting function is called to display the post’s formatted date:

```js
> dateI18n('F j, Y g:i a', '2020-09-23T17:18:00')
< September 23, 2020 3:18 pm
```

Here we can see that 3:18pm is neither UTC-5 nor -3 for the actual UTC time of
`2020-09-22T22:18:00`, but rather UTC-7. The formatting function is transforming the given time to UTC—ie. 20:18pm—based on the Browser Settings , and then setting the timezone. `20:18-05:00 = 15:18 or 3:18pm`.

Same would happen if we used `date_gmt` instead, which is actually being used in the ‘latest posts’ and ‘latest comments’ blocks, but is not apparent on first sight as those blocks are only displaying the date but not the time. This creates problems anyway because day changes would be offset by whatever difference in times there is.

A combination of `date_gmt` + the `gmt` parameter on the `dateI18n` function doesn’t work either, because the timestamp is _ambiguous_ ie. doesn’t have timezone information. Moment’s .utc() method, which is invoked when the third parameter on dateI18n is set to `true`, and in turn calling `gmdateI18n`, _transforms_ the given date to UTC in this case, again applying the Browsers timezone to it.


### Possible Solutions

1. Adding a timezone or a Zulu Time suffix to the `date_gmt` timestamp renders the correct result:

```javascript
> dateI18n( 'F j, Y g:i a', '2020-09-23T22:18:00Z' )
< September 23, 2020 5:18 pm
```

I think this would be ideally done in the _backend_.

2. Patching it on the frontend, every time the function is called. It would mean using `moment` to let `dateI18n` know that the date is actually a UTC date...

```javascript
const dateGMT = "2020-09-23T22:18:00";
const actualGMTDate = moment( dateGMT ).utc( true );

> dateI18n( actualGMTDate );
< September 23, 2020 5:18 pm

...or similarly doing the same when we save the data to the store.
    
```

3. Changing the API by always assuming that the date is GMT when using `gmdateI18n`

ie. changing the API to

```javascript
export function gmdateI18n( dateFormat, dateValue = new Date() ) {
/**
 * The only change in the next line, where the`true` parameter
 * is added to the `utc()` function.
 */
	const dateMoment = momentLib( dateValue ).utc( true ); 
	dateMoment.locale( settings.l10n.locale );
	return format( dateFormat, dateMoment );
}
```

This breaks the tests, so I'm hesistant on this being the best solution. The entire library is tested using timestamps that include the `Z` suffix.

### Conclusion/Questions

Adding the `Z` suffix to the dates that WordPress provides to the editor requires next to no changes on the frontend, other than using the `gmt` parameter on `dateI18n`. The impact on the backed is unknown at this time. 

This issue is affecting every usage of  the `dateI18n` function that relies on the date provided by either the `date` or `date_gmt` parameter of the Post Entity, or any other _ambiguous_ timestamp. Currently, besides the scheduler, that's also the following blocks:

- https://github.com/WordPress/gutenberg/blob/aa0abb915e843e2d636d4242aa249e504284abbc/packages/block-library/src/post-comment-date/edit.js
- https://github.com/WordPress/gutenberg/blob/aa0abb915e843e2d636d4242aa249e504284abbc/packages/block-library/src/post-date/edit.js
- https://github.com/WordPress/gutenberg/blob/9cb1acfc7d396465ec1bff2af63ef0df3bb7677e/packages/block-library/src/latest-posts/edit.js

Please let me know your thoughts. I'm particularly interested on the perspective of the non-Gutenberg side of this issue, as I haven't filled the knowledge gap there. 

cc. @mkaz

**Comment by mkaz** [comment]
Good work digging in and figuring out the scenarios.

I think I'm with you on the first solution — adding the `Z` would be explicitly setting what I think is assumed that the date is UTC. Also, we should be able to check the incoming date does not have any time zone indicator and only set it if it is missing.

This would be a good one to bring up in the Core JS Meeting, usually there is time in the meeting to bring up items, but might be good to add ahead to the [meeting's rolling agenda](https://docs.google.com/document/d/1Y2Q1iZ89M88NA3iq0TyLzWn9wy6Zxob-wX3tJ4ivHPc/edit?usp=sharing) to give people a chance to prep.

**Comment by vcanales** [comment]
[I brought this up on the meeting](https://wordpress.slack.com/archives/C5UNMSU4R/p1600784168028500), and as suggested, I'd like to bring this to the attention of @aduth and @davilera—I don't have permissions to add you as reviewers, hence the ping :)

**Comment by tellthemachines** [comment]
Is this a duplicate of #25003?

**Comment by vcanales** [comment]
> Is this a duplicate of #25003?

Yes, it’s the same problem.

**Comment by david-szabo97** [comment]
This seems to be fixed by now. Not sure which commit though. Probably it's fixed by migrating from moment to date-fns. @mkaz Can you confirm? Thanks!

**Comment by mkaz** [comment]
Yep, fixed in https://github.com/WordPress/gutenberg/pull/25782
