### ISSUE TITLE
.tiff files cause error on refresh

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2535]
To reproduce:

- Click image block
- Add a .tiff file
- Nothing shows
- Refresh
- This shows:

![2017-08-25 at 12 29](https://user-images.githubusercontent.com/253067/29712321-21f7af42-8991-11e7-809d-279ac4447f7a.png)

**Comment by aduth** [comment]
[`Uncaught TypeError: Cannot convert undefined or null to object`](https://github.com/WordPress/gutenberg/blob/fdb11586be4bae9e4e71a1e4550cdd92d307655b/blocks/library/image/block.js#L98)

The issue is that we expect the media item to return a `media_details.sizes` object on the API return value:

https://github.com/WordPress/gutenberg/blob/fdb11586be4bae9e4e71a1e4550cdd92d307655b/blocks/library/image/block.js#L81-L85

In the case of a TIFF image, the `media_details` property is an empty object, so `availableSizes` state is assigned as `undefined`.

**Comment by karmatosed** [comment]
@aduth can we do something to catch this for .tiff?
