### ISSUE TITLE
Should the Post Content block be editable?

### ISSUE THREAD

**Issue by ntsekouras** [WordPress/gutenberg#25394]
Currently the `Post Content` block when inserted is editable and a user can edit the content and save the changes to the respective post. This feels a bit weird and might confuse a user about what flows should follow.

While it can be convenient for some to use this, it might be better to have the post content `locked` and have a single clear flow on where to edit a post's content.

Related to the ongoing work on FSE the Milestone:5 about Query block. #24762.

**Comment by youknowriad** [comment]
THe block itself should be editable (in FSE templates for instance) but maybe it can require a two steps edition (select, click edit...) in the context of the "Query" block. This needs some design thoughts.

**Comment by mtias** [comment]
Let's start by locking editing. I'd like to get FSE into a state where _display_ is working well before opening up edit of content too much.

**Comment by karmatosed** [comment]
For now, I am going to remove 'needs design' as if it's going to not have the 2 steps I think that makes sense to remove. It can be added back in.

**Comment by bobbingwide** [comment]
No. In my opinion the Post content should not be directly editable. 
The block editor is confusing enough already. It's very difficult to understand the context. 
There's hardly any visual feedback with regards to block nesting.
In order to know where a block is in the inner block hierarchy you have to use 
- the Outline toolicon and/or 
- the block icon's parent block and/or 
- the breadcrumbs links - which aren't in my field of view most of the time. 

For an example of how things can go wrong see https://github.com/bobbingwide/fizzie/issues/43#issuecomment-732441294

**Comment by annezazu** [comment]
Noting that the same "click to edit" flow might be useful to consider here https://github.com/WordPress/gutenberg/issues/29337

**Comment by ntsekouras** [comment]
Closing in favor of https://github.com/WordPress/gutenberg/issues/32317 which explores the flow for 'locking' the Post blocks.
