### ISSUE TITLE
Cover Image block has no control to make full width

### ISSUE THREAD

**Issue by davidsword** [WordPress/gutenberg#2542]
No UI option in Cover Image block to make full width.

1. insert block > cover image
2. no format option to align 'full', only left/center/right, 
3. no Inspector setting, only Fixed, Dim, and class.

gb 0.9.0, safari 10.1, macos 10.12.6

I think i remember it being there a few months ago. If I go from Visual to > Text, I'm able to make it fullwidth by changing the the wp:core/cover-image object from `"align":"center"` to `"align":"full"`

**Comment by youknowriad** [comment]
Yes, all themes do not support the full/wide widths by default, because they require special CSS in the theme's stylesheets. Thus, we made it opt-in. More details on enabling this feature here http://gutenberg-devdoc.surge.sh/reference/theme-support/

I'm closing, feel free to reopen if it doesn't answer your question.
