### ISSUE TITLE
When wordpress upgrade to nosql mysql 8?

### ISSUE THREAD

**Issue by nabi009** [WordPress/gutenberg#25438]
Wordpress cover 37% of web, with plugins sites go heavy and nosql is best in performance and now a days all hosting platform support MySQL 8 if it upgrade it will be great.

**Comment by aristath** [comment]
Hello @nabi009 
This repository is for the WordPress editor, not WordPress itself. WordPress requests can be submitted on https://wordpress.org/support/forum/requests-and-feedback/
As far as I know there are no issue with any MySQL versions so I don't see why you can't use v8
The only restrictions are in the [requirements page](https://wordpress.org/about/requirements/):

> MySQL version 5.6 or greater OR MariaDB version 10.1 or greater. 

I'll go ahead and close this ticket since it is not about the Gutenberg (editor) project.

**Comment by nabi009** [comment]
Thanks
