### ISSUE TITLE
Delete menu option shows no visible indication that deletion is in progress on navigation screen

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#25435]
**Describe the bug**
Clicking 'Delete Menu' doesn't result in any visual indication that the deletion is in progress. In my case the delete request took a few seconds to complete (I was on a slow internet connection when testing this). During that time it feels like the page has frozen and something has gone wrong momentarily until eventually the deletion happens.

**To reproduce**
1. If you're on a fast internet connection, use browser dev tools to throttle the connection.
2. Open the navigation screen
3. Selected a menu you wish to delete
4. Using the block settings (cog) menu click the delete menu option
5. Observe that nothing happens until the menu is deleted

**Expected behavior**
There are a few options:
- The delete button shows a progress indication
- A loading spinner or snackbar is shown
- The menu is deleted optimistically by the client while the request to the server is still in progress.

**Comment by shaunandrews** [comment]
I think we can do a few things to improve this:

- Use a "busy" button when deleting.
- Dim all interactive elements on the screen while the deletion is happening.
- Show a snackbar after deleting; I don't think these support actions, but having some way to undo could be nice.
- Rather than drop them back onto another menu, lets give users the option to choose which menu to edit, or to create a new menu.

![Delete Menu Flow](https://user-images.githubusercontent.com/191598/107565801-11af8b80-6bb2-11eb-825a-636dad2ac61f.gif)
