### ISSUE TITLE
Read More Button 

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#25450]
It'd be nice if a "read more" link could be styled like a button.

![Screenshot 2020-09-18 at 14 14 35](https://user-images.githubusercontent.com/908665/93601592-52b3c300-f9b9-11ea-8ab6-f53919bc32bf.jpg)

It might be neat to extend Buttons block to allow it to link to the permalink (if it's in a Query Loop block?) rather than adding all the controls to the read more link in the post excerpt block?

**Comment by supernovia** [comment]
I know this issue is more about buttons than alignment, but since it's regarding the design of the read more link, will it be possible anymore for a "read more" link or button to be inline with the previous paragraph, as it used to be? 

A user was asking here:
https://wordpress.com/forums/topic/problems-with-new-editor-classic-content-shifted-andn-more-tag-at-wrong-pos/

Their previous posts have the more link inline like this:
<img width="614" alt="Screen Shot 2021-03-12 at 4 07 31 PM" src="https://user-images.githubusercontent.com/3476361/111007892-1a2fe900-834d-11eb-948e-804201d0e731.png">

They are concerned about changes to formatting as they switch to Blocks.

**Comment by kjellr** [comment]
Just wanted to echo this request. It would come in handy for Query block patterns. For example: 

<img width="797" alt="Screenshot 2021-04-26 at 17 02 22" src="https://user-images.githubusercontent.com/1202812/116106780-6a0a0b80-a680-11eb-976b-f509e9bc156e.png">

**Comment by antonyjsmith** [comment]
Second this, being able to add a button to link to a post kind of feels like the most bog standard of requirements for MVP with this block.

I had high hopes for the query block in 5.8 but so far it's effectively unusable for me in the current state. Due to this issue and #27620
