### ISSUE TITLE
Center aligned image isn't centered in 0.90 (either in editor or on front of site)

### ISSUE THREAD

**Issue by wpfangirl** [WordPress/gutenberg#2548]
## Issue Overview
I inserted an image and selected center align, but the image didn't center either in the editor or in the post previw.

## Steps to Reproduce (for bugs)

1. Add an image block.
2. Click the button to center-align it.
3.
4.

## Expected Behavior
The image should center, the same way it right-aligns and left-aligns (that is, the whole block resizes to fit the image, and centers).

## Current Behavior
The block stays full-width, though the image resizes. The image shows inline inline even though the `aligncenter` class is added to the figure.
![image-not-centering](https://user-images.githubusercontent.com/14795150/29753616-fb7a97c2-8b29-11e7-8581-8901db44b347.png)

**Comment by aduth** [comment]
This is potentially theme-dependant, caused by the alignment class `aligncenter` being applied to the `figure` wrapping the `img`, not the `img` itself:

https://github.com/WordPress/gutenberg/blob/5cc934f11d5ac28efed70d657fddda7d4c5cd759/blocks/library/image/index.js#L99-L104

The recommended styles for `.aligncenter` perform centering by `auto` left-and-right margins:

https://codex.wordpress.org/CSS#WordPress_Generated_Classes

In the case of a `figure`, this will not work because as a [block-level element](https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements), it already occupies the full width of its container:

![Figure full width center](https://user-images.githubusercontent.com/1779930/29790431-d480fd1c-8c07-11e7-9563-3e7f17f65ac5.png)

When applied to the image though, since the image assigns its own `width`, it will center itself within:

![Image cneter](https://user-images.githubusercontent.com/1779930/29790524-2e4f1d60-8c08-11e7-988a-10668114508b.png)

Possible solutions:

- Avoid using the default `aligncenter` (and other align) class and instead assign custom classes with styles prescribed by the image block
- Assign `aligncenter` (and other align) to the `img` element
   - This may have repercussions on alignment of a caption, if applicable

**Comment by wpfangirl** [comment]
Okay, that applies to the way it looks on the front of the site, but not, one presumes, to the way it looks in the editor. Also, the alignleft and alignright work on the front of the site (if you resize the image), but not the aligncenter. Yet presumably these classes are being applied to the figure rather than the image in all cases.

**Comment by aduth** [comment]
>Okay, that applies to the way it looks on the front of the site, but not, one presumes, to the way it looks in the editor.

The reason it's not aligned in the editor is because there appears to be nothing operating on the center align style. There are styles to handle the left/right (float) and wide/full (escape bounds) cases, but not center:

https://github.com/WordPress/gutenberg/blob/e3bedc0f52731cebb9277ec6146f7551672ab7e1/blocks/library/image/index.js#L85-L90

>Also, the alignleft and alignright work on the front of the site (if you resize the image), but not the aligncenter. Yet presumably these classes are being applied to the figure rather than the image in all cases.

Yes, but left and right alignments use `float`, not the `margin`s of `auto` like with center alignment. The floated figure will assume the width of the image.

This doesn't seem predictable though:

>You should always set a width on floated items [...] If no width is set, the results can be unpredictable. Theoretically, a floated element with an undefined width should shrink to the widest element within it. This could be a word, a sentence or even a single character - and results can vary from browser to browser.

http://css.maxdesign.com.au/floatutorial/introduction.htm

**Comment by youknowriad** [comment]
With recent changes, this seems to work as intended in the editor. In the frontend it depends on the theme styles.

**Comment by aduth** [comment]
Fixed by #4801
