### ISSUE TITLE
Consider adding <b> and <i> tags next to <strong> and <em>

### ISSUE THREAD

**Issue by smeedijzer-internet** [WordPress/gutenberg#25581]
**Is your feature request related to a problem? Please describe.**
There are valid cases where a `<b>` or `<i>` are used semantically as per the HTML5 specification. (https://www.w3.org/International/questions/qa-b-and-i-tags). But only `<strong>` and `<em>` are available. In many cases I want to add bold or italic text without adding extra importance or emphasis.

**Describe the solution you'd like**
Consider adding `<b>` and `<i>` tags next to `<strong>` and `<em>`. 

**Describe alternatives you've considered**
None

**Comment by mapk** [comment]
Those particular HTML tags are rare. My suggestion is to make the change using the Code Editor instead of relying on a UI element for this.

![bold](https://user-images.githubusercontent.com/617986/94091730-d6145080-fdcd-11ea-8efa-5c35319d8343.gif)

**Comment by Y0hy0h** [comment]
I want to do the same thing to make the markup more accessible, since we use bold to visually emphasize. I can't tell my other authors to edit the code, as they are non-technical.

I haven't yet grasped if there is a way of building a Gutenberg plugin that could, for example, process the output of the paragraph block and replace all `<strong>` with `<b>`? If you could point to me to what I can read to figure that out, that would be really helpful. :)
