### ISSUE TITLE
Reduce clicks for "Select Image" and "Preview" by defaulting to previous choice

### ISSUE THREAD

**Issue by ddegner** [WordPress/gutenberg#25662]
**Is your feature request related to a problem? Please describe.**
In the Gutenberg editor "Select Image" (in an image block) and "Preview" both have dropdown option boxes that require two clicks each time they are selected.  But users usually chose the same option every time.  For example most users store their images either in Media Library, Google Images, or Pixma but not two of them.
<img width="288" alt="Screen Shot 2020-09-26 at 21 00 33" src="https://user-images.githubusercontent.com/29661332/94353339-1f6ad700-003e-11eb-87a4-437896e3f300.png">
<img width="312" alt="Screen Shot 2020-09-26 at 20 59 57" src="https://user-images.githubusercontent.com/29661332/94353341-20036d80-003e-11eb-9ecf-8d7814c0d5cc.png">

**Describe the solution you'd like**
It would greatly reduce the number of clicks if "Select Image" and "Preview" defaulted to the previously chosen option and had a carrot beside that could be clicked to expand and show the alternative options if required.
<img width="30" alt="Screen Shot 2020-09-26 at 21 00 53" src="https://user-images.githubusercontent.com/29661332/94353346-2c87c600-003e-11eb-9ead-598f40de6cf2.png">

**Describe alternatives you've considered**
Also a settings page option to default "Select Image" to one of the options could solve the problem but would require more settings.

**Comment by joedolson** [comment]
The image selection interface shown here is not something currently in core. I can't speak definitively to what was available in 2020, when this issue was raised, but certainly at this point it's not a core issue.

There may be room to improve the View menu (no longer called 'Preview'), but practically speaking I don't think this is the solution.

The view toggle is not a tool that displays different previews; it switches the canvas editing view between desktop, tablet, and mobile. Opening a preview in a new tab is the only option that's actually a preview, and doesn't really require multiple uses, since you can open it once and refresh as you go. 

Given that, I think this issue can be closed.
