### ISSUE TITLE
Document Settings (Full site editing): Document title is misaligned when there is a scrollbar 

### ISSUE THREAD

**Issue by jeyip** [WordPress/gutenberg#25716]
## Describe the bug
If we have a scrollbar in the content then the document title is a little bit off. Since the editor's content container's width is smaller by a few pixels because of the scrollbar.

## To reproduce
1. Set up the site editor locally
2. Ensure that, in your computer settings, the scrollbar for browser windows is permanently displayed ([How to do so in mac](https://osxdaily.com/2011/08/03/show-scroll-bars-mac-os-x-lion/))
2. Navigate to the site editor
3. Note how the document title is centered with content
4. Click on the settings icon in the top right-hand corner of the site editor
5. Note how the document title is now slightly misaligned

## Expected behavior
The document title should be centered with block editor content with or without a sidebar present.

### Without scrollbar
![image](https://user-images.githubusercontent.com/2256104/94249112-b725d380-ff1f-11ea-8a5c-0fcff842597b.png)

### With scrollbar
![image](https://user-images.githubusercontent.com/2256104/94249149-c442c280-ff1f-11ea-9d12-be2b5883d547.png)

**Comment by noahtallen** [comment]
I don't think we need to fix this. Happy for folks to open it if we need to. My reasoning is that:

1. The primary reason this interaction is strange is that when clicking a template part, the height of the DOM increases with the block inserter. Therefore, a scrollbar can start showing up when none was there before.
2. The scrollbar only applies to the content area, and the top bar is ordered and centered with respect to itself. Since the scrollbar does not apply to that, I'm not sure we should be adjusting anything based on that.
