### ISSUE TITLE
Being able to add to inactive widgets feels unexpected

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#25747]
I found I was able to add to inactive widgets. This felt a little confusing to me as a flow, perhaps this is something to discuss over a bug and might be a workflow mindset. I did feel that inactive would 'park' or hold my widgets I wasn't using, so I wasn't sure about adding to that. 

![image](https://user-images.githubusercontent.com/253067/94717810-bab6c180-0348-11eb-9c66-5083d244650d.png)

My expected behaviour, in this case, would be for inactive to just have widgets not used in, not to also have a way to add.

**Comment by noisysocks** [comment]
Yeah I agree. We could set a template lock on the inactive widget area which means users can't insert any blocks to it.

What do you think, @mapk?

**Comment by mapk** [comment]
One user flow that was brought to my attention during research was that people use the inactive widget area to "prepare" widgets before going live, or move widgets into during seasonal transitions while keeping the settings.

**The first** is solved now because we don't actually go live until the "update" button is clicked. So while it's not necessarily an issue anymore, I'm hesitant to disrupt common user flows that people are comfortable with.

**The second** issue is something we'd still need to allow. People should be able to move a widget from an active area into the inactive widget area manually. An example of this is using a widget to promote something during summer months and then deactivate it during winter months, but keeping all the settings.

I recommend we keep the flow as is.

**Comment by noisysocks** [comment]
That makes sense.
