### ISSUE TITLE
Jump positions unexpected within widget editor when clicking edit

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#25745]
I was exploring the new interface for widgets and saw the 'edit' actions. This was interesting to me as I initially expected it to 'edit' or open. I did notice the screen move a little, but because I had a larger widget area as you can see in this gif, it was a little disjointed.

![2020-09-30 17 37 52](https://user-images.githubusercontent.com/253067/94714335-ea16ff80-0343-11eb-91b5-30227a7294aa.gif)

My recommendations would be:

- Review if 'edit' is the right term for this here. Perhaps 'goto' or 'interact'? It certainly had me expecting to edit inline.
- Offset the jump point on the screen to maybe jump a little below the object. This would avoid the issue of having to scan to the bottom of the page.
- Potentially consider animations to draw focus to the interaction point.

There is also a further bug when the edit action has to jump up to the top, as shown in gif included. It doesn't quite get there.

**Comment by mapk** [comment]
I'm not sure how much of this can be implemented for WP 5.6. The designs I've shared in the past show the Widget Area in the tabs, when a widget area is selected.

![Inline inserter 1](https://user-images.githubusercontent.com/617986/95351684-5a5adf00-0876-11eb-998b-37036bef9678.png)


If nothing is selected, I'm fine with a revised description of the screen. Let's stick with "Widget Areas" terminology since that is what we're going with elsewhere. I'd also remove the links in the sidebar too.

![Inline inserter 3](https://user-images.githubusercontent.com/617986/95351820-73fc2680-0876-11eb-9c91-55c4b1b82b44.png)

I remember sharing this info back here: https://github.com/WordPress/gutenberg/issues/24838
