### ISSUE TITLE
Large font sizes break the appearance of the preset sizes dropdown

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#25862]
**Describe the bug**

If a theme provides very large font sizes as presets, it breaks the appearance of the preset size dropdown. 

**To reproduce**
1. Use a theme that provides a large font size (96, for example).  
2. Use the preset sizes dropdown.
3. Notice the overflow.

**Expected behavior**

Font size representations there should be capped to a size that prevents them from overflowing their container. 

**Screenshots**

![Screen Shot 2020-10-06 at 10 04 54 AM](https://user-images.githubusercontent.com/1202812/95212375-a09f3800-07bb-11eb-843d-4f68b13b6d86.png)

Gutenberg 9.1.0
Discovered while building the [Twenty Twenty One Theme](https://github.com/WordPress/twentytwentyone).

**Comment by aristath** [comment]
Ideally I'd say they shouldn't even have a preview... a simple drop down with the labels would work fine and won't break if the font sizes are not defined in pixels (I actually came across this while building an FSE theme).
Everything breaks if the font-size is something like a calc() containing a css var

**Comment by kjellr** [comment]
A couple quick ideas: 

At the very least, we can set overflow-y to hidden on these fields. That'll improve the appearance somewhat: 

![Screen Shot 2020-10-06 at 11 45 53 AM](https://user-images.githubusercontent.com/1202812/95225178-7f454880-07c9-11eb-9914-0ccd116b402a.png)

When we set the inline value, instead of setting the value directly, we could use something like `min(32px, [actual value])`. to ensure that even if the value is huge, it'll max out at a reasonable size: 

![Screen Shot 2020-10-06 at 11 52 08 AM](https://user-images.githubusercontent.com/1202812/95225943-625d4500-07ca-11eb-99f4-06550cb84a9e.png)

**Comment by aristath** [comment]
The reason I'm suggesting that the dropdown should not offer a preview of font-sizes is because using sizes like these will cause an error: https://github.com/aristath/q/blob/1c6b6c99e1d386c1cec49b8e2407aa4b25fefef6/experimental-theme.json#L31-L52

The above JSON file is a perfectly valid scenario and should be taken into account, not everyone will use pixels - especially if they want to implement something like a consistent typography-scale and/or responsive/adaptive typography sizes.

![Screenshot from 2020-10-07 08-11-03](https://user-images.githubusercontent.com/588688/95290126-321eb080-0875-11eb-9e70-3129f01e88a8.png)
