### ISSUE TITLE
Widget Editor: Can't drag a block to an empty widget area

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#25911]
### Problem
I can't drag and drop a block/widget to the bottom of another widget area. Nor can I drop a block/widget into an empty area.

**Dragging to bottom**

![drag-to-bottom](https://user-images.githubusercontent.com/617986/95353866-a018a700-0878-11eb-980d-ef14b17f100b.gif)

**Dragging to an empty area**

![drag-to-empty](https://user-images.githubusercontent.com/617986/95353884-a6a71e80-0878-11eb-9c22-09c6ac66be2c.gif)

**Comment by talldan** [comment]
I can't reproduce the issue with dragging to the bottom, but indeed it doesn't seem to be possible to drop in an empty area.

**Comment by talldan** [comment]
The problem for empty areas is that the drop zone area is effectively 0px high because the appender isn't shown, so there's no target for dragging blocks. This could be fairly simple fix for widget areas of adding a min height to the block list layout component.

There may also be the same issue in other editors/blocks.
