### ISSUE TITLE
There is no "really wide" button in the demo

### ISSUE THREAD

**Issue by withinboredom** [WordPress/gutenberg#2594]
Version: 1.0

## Issue Overview

Trying out the demo, I was unable to find the "really wide" button

<img width="873" alt="screen shot 2017-08-29 at 2 58 23 pm" src="https://user-images.githubusercontent.com/1883296/29838936-a4de1806-8cca-11e7-8af6-c2645503f945.png">

## Steps to Reproduce (for bugs)

1. Go to demo page
2. Scroll to image that says to make really wide
3. Cannot locate anything that indicates really wide

Chrome, latest production (60)

## Expected Behavior

Some way to make an image really wide

## Current Behavior

Unable to make an image really wide

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by youknowriad** [comment]
Yes, all themes do not support the full/wide widths by default, because they require special CSS in the theme's stylesheets. Thus, we made it opt-in. More details on enabling this feature here http://gutenberg-devdoc.surge.sh/reference/theme-support/

There's currently this theme showcasing all Gutenberg features including wide alignments https://github.com/WordPress/gutenberg-theme

I'm closing, feel free to reopen if it doesn't answer your question.

**Comment by withinboredom** [comment]
Thanks, I'll open a different bug then ;)
