### ISSUE TITLE
List block - tab to indent/outdent list items

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#25947]
**Is your feature request related to a problem? Please describe.**
When editing a list block it would be nice if hitting the `TAB` key would indent the current bullet point. This is common to most other text editing applications. Simialrly, `SHIFT + TAB` should outdent the list item.

**Describe the solution you'd like**
* `TAB` key should indent the current list item.
* `SHIFT + TAB` should outdent the list item.

**Describe alternatives you've considered**
We'd need to check this didn't cause any accessibility issues as tab is used by keyboard users to navigate.

**Comment by beaulebens** [comment]
I believe the reason this _doesn't_ happen is because there are accessibility considerations (and thus the label), so as a minor refinement, one way we could accomplish this is to _only_ indent/outdent if tab/shift-tab is pressed when the caret is at the beginning of a list item.

That's how Google Docs also works, since it acts as a bit more of an intentional signal that you're trying to adjust positioning vs add a tab within the content of the list item (or tab out to some other control element).

**Comment by alexstine** [comment]
A dedicated shortcut may be the best way to go here. Tab in blocks is generally used to go to block options while Shift+Tab is used to focus the block toolbar. This gets complicated if we start making exceptions to the rule for certain blocks. Since Tab/Shift+Tab already have globally defined functions, a dedicated shortcut for this may be good.

Just my thoughts...

Thanks.

**Comment by zackkrida** [comment]
Hello, I've also encountered this issue but was made aware of several shortcuts:

Indent: `cmd+m` Outdent: `cmd+shift+m`

and, a 'hidden' shortcut when on the first character of a new list item:

Indent: `space` Outdent: `backspace`

I would also expect the tab behavior, but I'm thinking what Gutenberg does may be the best approach. For reference, here's what happens in **Notion**:


https://user-images.githubusercontent.com/6351754/115410324-8a3d5480-a1c0-11eb-8438-6c690d98f0a1.mp4

**Comment by getdave** [comment]
It looks like not using TAB is an intentional design and a11y decision. Thanks for all the input and rationale here.
