### ISSUE TITLE
Class the block based widgets editor as "admin" for is_admin

### ISSUE THREAD

**Issue by mattyrob** [WordPress/gutenberg#25945]
**Describe the bug**
In testing the Widgets page migration to Block Editor code I am getting a mainly grey screen, this is because the REST API endpoint URL is being encoded somewhere.

**To reproduce**
1. Local install of development WordPress code
2. Gutenberg release code installed and activated (this issue is confirmed with Gutenberg 9.0, 9.1 and 9.1.1)
3. Visit Themes > Widgets page
4. See console log error `http://localhost/dev/index.php?rest_route=%2F__experimental%2Fsidebars&context=edit&_locale=user`
5. Not the presence of escaped slashes (%2F)

**Expected behavior**
No URL errors and no are screen

**Screenshots**
<img width="1929" alt="Screenshot 2020-10-08 at 08 55 22" src="https://user-images.githubusercontent.com/1280733/95430711-0b7b7b00-0944-11eb-9c4e-a42adbc3da3f.png">

**Editor version (please complete the following information):**
- WordPress version: 5.6-alpha-49099
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin (issue is confirmed with Gutenberg 9.0, 9.1 and 9.1.1)

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browser Safari
 - Version 14.0
- Same issues persists local with Chrome 86.0.4240.75 and Firefox 81.0.1

**Comment by mattyrob** [comment]
I have narrowed this issue to a plugin that creates a widget. Within the code is a function that is called to display some additional widget settings. This function is conditionally loaded if `is_admin()` is true to reduce code loading overhead.

It seems the new Widget page is either not classed as an admin page or there is a race condition such that the function is not available at the time of rendering.

I imagine there may well be other widgets out there that call code that is conditionally available in admin areas only.

**Comment by adamziel** [comment]
@mattyrob thank you for reporting! Would you mind sharing which plugin did you narrow it down to?

**Comment by mattyrob** [comment]
@adamziel Sure, the issue arises with the Subscribe2 plugin and the main widget (the counter widget works fine).

https://wordpress.org/plugins/subscribe2/

Commenting line 174 of the widget class code (`subscribe2/classes/calss-s2-form-widget.php`) fixes the Widget screen but breaks the functionality of the widget.

**Comment by draganescu** [comment]
From https://github.com/WordPress/gutenberg/issues/28538#issuecomment-773679136 by @noisysocks 👍 

I can confirm that enqueue_block_editor_assets is not being called in the widgets screen, navigation screen, and in the site editor.

Whether it should be called in these screens is an interesting question. I think it probably makes sense for there to be a generic enqueue_block_editor_assets action which is called on all four screens and then a more specific enqueue_block_editor_assets-$screen action which can be used to target one screen but not the others.

But I know that we already have a few related actions and filters e.g. enqueue_block_assets, should_load_block_editor_scripts_and_styles, and admin_enqueue_scripts. I think the first step here should be to do a little audit, straighten out how these actions and filters are related, document them, and then evaluate what's missing. This could get really complicated if we add a new action without first getting out house in order.

**Comment by talldan** [comment]
Related to the above comment, https://github.com/WordPress/gutenberg/pull/30076 added `enqueue_block_editor_assets` in the standalone widgets page. I don't know if this fixes the issue.

**Comment by noisysocks** [comment]
I can confirm that `enqueue_block_editor_assets` now fires in the Widgets screen.

Unfortunately this does not fix the Subscribe2 widget though. The error that this widget is having is because `S2_Form_Widget::form()` relies on PHP code is only included when `is_admin()` returns true. `is_admin()` is not true in REST API requests such as the one that is made to display a Legacy Widget block.

This issue has come up a few times in a few different contexts:

- https://github.com/WordPress/gutenberg/issues/16731
- https://core.trac.wordpress.org/ticket/47394
- https://core.trac.wordpress.org/ticket/25104

There's unfortunately no real fix that Core can implement. It would be wrong to make it so that `is_admin()` returns true in this case because REST API requests are, indeed, not WP Admin requests. Also the call to `is_admin()` happens when the plugin is loaded and not when the REST API request is handled.

The plugin needs to be updated so that the code needed by `S2_Form_Widget::form` is included whenever `S2_Form_Widget::form()` is called and not just when `is_admin()` is true.
