### ISSUE TITLE
Adjust borders on block-level controls in the Toolbar

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#25983]
The semantic groupings we have in the toolbar — meta, block level, inline — should also have a visual representation with the borders. Right now separate block level controls have different representations, including cases like Navigation where every single one has borders.

Here's a before and suggested after:

<img width="515" alt="Block toolbar groupings" src="https://user-images.githubusercontent.com/1204802/110668888-17f25100-81cc-11eb-9b24-88cc84f5b342.png">

**Comment by karmatosed** [comment]
I took a little look at this and my current thinking is how far could we reduce the use of borders which would result in having much clearer groupings.

Here is what just some look like currently to context.

<img width="703" alt="example" src="https://user-images.githubusercontent.com/253067/100445753-88ee7c80-30a5-11eb-9c3d-9ffea7aa269a.png">

<img width="546" alt="example2" src="https://user-images.githubusercontent.com/253067/100445755-89871300-30a5-11eb-92a2-eadbcb2f7a00.png">

## Grouping
As mentioned, the groupings naturally fall into the following. I would like to check my thinking on meta referring to document controls (moving within space), but this is what I think summarises a potential reduction here:

<img width="598" alt="Frame 1" src="https://user-images.githubusercontent.com/253067/100448313-fb615b80-30a9-11eb-982e-332029e992ff.png">

In this case, if controls fell into that group, there would be no border.

<img width="550" alt="navigation" src="https://user-images.githubusercontent.com/253067/100448286-f56b7a80-30a9-11eb-9123-536c0b025bb0.png">

The outlayer here is the options section, which might be acceptable as additional information appended to the toolbar.

There will need to be some working out of each case, but having a more robust pattern I feel is a great starting point here.

**Comment by jasmussen** [comment]
Great ticket. I've taken Tammies work above, and built upon it and expanded with some "before/after" ones, which I will take the liberty of updating the main ticket with.

_Note that this is about toolbar groupings in the design sense. There are some underlying tech issues that need to be addressed in order to make this happen to solve this PR._

As already proposed by Matías and Tammie, I've embraced these 4 section descriptors:

- **Meta** refers to actions on the block itself — its type, style, position.
- **Block level** refers to the HTML parlance where block level relates to the whole block. Actions here apply to the whole block, such as alignments, or in case of blocks with nesting, actions that affect all blocks inside.
- **Inline level** similarly refers mostly to in-text transformations such as bold or italic on a text selection. This grouping can also be **Other**, for actions that don't fall into any of the other groups.
- **More** is the overflow menu.

Mockup:

<img width="515" alt="Block toolbar groupings" src="https://user-images.githubusercontent.com/1204802/103628073-c369f580-4f3e-11eb-8a95-9f3aa9307634.png">

In the above mockup, the Paragraph already has correct groupings. Image and Navigation need a little work.

Related issues:

- [Full height button in Cover](https://github.com/WordPress/gutenberg/issues/27496)
- [Allow width controls on every block](https://github.com/WordPress/gutenberg/issues/25973)
- [Design improvements to Image block toolbar](https://github.com/WordPress/gutenberg/issues/26411)
- [Block Toolbar/Movers: Revisit groupings and align to a grid](https://github.com/WordPress/gutenberg/issues/24898) (can largely be closed in favor of this one)

**Comment by hedgefield** [comment]
This is really great, makes the grouping so much clearer 👍

**Comment by mtias** [comment]
Closing this as done.
