### ISSUE TITLE
Enter in iOS Safari hides keyboard

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#2601]
This breaks the writing flow. I have to re-focus the area to be able to type further.

**Comment by iseulde** [comment]
Also have to click twice in a block to be able to get a caret and keyboard. May be related.

**Comment by iseulde** [comment]
Also noticed that in OSX Safari the toolbar seems to pop up twice in a short time when you focus an Editable. May be related to.

Haven't figured out what is causing this yet :/

**Comment by iseulde** [comment]
Interestingly it works fine on a new post... Only when I load the demo, type a bit, and press enter, focus is lost.

**Comment by tg-ephox** [comment]
Investigating the toolbar popping up twice in some instances on Safari.  Doesn't happen every time and removing the `CSSTransitionGroup` in `BlockToolbar` makes it not visible but maybe this is just because it happens a lot faster... Although maybe this isn't worth looking at considering https://github.com/WordPress/gutenberg/pull/2998 ? Will look into the iOS issue tomorrow.

**Comment by iseulde** [comment]
This is still an issue. Fix in #4775.

**Comment by iseulde** [comment]
Fixed in #5769.
