### ISSUE TITLE
Non breaking space not interpreted

### ISSUE THREAD

**Issue by sebastienserre** [WordPress/gutenberg#26014]
**Describe the bug**
In french we're using non breaking space between words and double punctuation ie :!?; to avoid this kind of things:
![nbsp](https://user-images.githubusercontent.com/3902621/95711317-ccf70080-0c62-11eb-86c4-3cdb225be647.png)

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? "default"

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu Linux 20.04.1
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 81

**Comment by audrasjb** [comment]
Hi,
FWIW, I tested the issue and I can't reproduce on Chrome. It looks like specific to Firefox.

**Comment by fr-laurentn** [comment]
Related to https://github.com/WordPress/gutenberg/issues/18523

**Comment by fr-laurentn** [comment]
Could be also related to : https://core.trac.wordpress.org/ticket/48464

**Comment by noisysocks** [comment]
On Mac this is possible because there's a system level shortcut (<kbd>Opt</kbd>+<kbd>Space</kbd>) for inserting non breaking spaces. On Windows and Linux this shortcut needs to be added to the block editor. https://github.com/WordPress/gutenberg/issues/18523 is the issue which tracks this enhancement.
