### ISSUE TITLE
"Theme Styles" option doesn't support theme styles enqueued via enqueue_block_editor_assets

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#26037]
### Problem
I noticed an awesome "Theme Styles" writing option in the "Preferences" section now. This is looking promising! However, checking it on/off doesn't seem to do anything. At least not in relation to the Twenty Twenty theme. Just checking in here to see if this is a theme problem, or an Editor problem. 

### Expectation
I expected that checking "off" the "Theme Styles" option would remove any theme styles from the Editor. But I still saw the theme styled buttons, background, quotes, etc.

**Example**

![theme-styles](https://user-images.githubusercontent.com/617986/95783596-06416780-0c87-11eb-95ec-e0fe00197ece.gif)

cc @karmatosed. I'm not entirely sure about this one, so please close if it's theme related and not editor related.

**Comment by karmatosed** [comment]
This is super interesting as yes I can confirm it doesn't work in that theme but works in Twenty Nineteen!

![2020-10-15 11 40 47](https://user-images.githubusercontent.com/253067/96112975-5b75b700-0edb-11eb-84dd-f5ddc53d55a9.gif)

It would seem therefore to be theme-specific, although I am not totally sure about that. It's not a new option and I would probably lean to recommending a ticket be created in trac, which I am happy to if needed. I would like to get some dev feedback on if that's case though so let's get some labels on this.

**Comment by karmatosed** [comment]
This was discussed during the core editor chat and does come down to the theme. This means that a trac ticket for the theme will be the best approach and I'll create that, whilst closing this.

**Comment by joyously** [comment]
But perhaps the text of the editor option should be changed so that it does not imply that it works for every theme.

**Comment by kjellr** [comment]
As per my comments in [the Trac issue](https://core.trac.wordpress.org/ticket/51554), the issue here is that the "Theme Styles" feature in Gutenberg doesn't account for stylesheets that have been enqueued via `enqueue_block_editor_assets`.

This is something that can be fixed in Twenty Twenty, but that's just one theme, and there will be others who enqueue stylesheets this way (For example, Twenty Nineteen uses that method to enqueue custom colors css if someone's modified colors in the Customizer). So Gutenberg should account for this, either by checking for and dequeueing those stylesheets, or by hiding/disabling the "Theme Styles" checkbox when themes enqueue stylesheets this way.

I'll re-open this issue for discussion around that idea.

**Comment by youknowriad** [comment]
It's not possible to know what styles enqueued in `enqueue_block_editor_assets` are theme or not. So I think instead themes should be using the default way to provide styles instead (add_editor_styles, theme.json...).
