### ISSUE TITLE
Add pattern search to the slash inserter 

### ISSUE THREAD

**Issue by bradhogan** [WordPress/gutenberg#26116]
**Is your feature request related to a problem? Please describe.**
Right now, you can search patterns in the main inserter; however, you can only use the quick forward slash inserter to search for existing blocks. 

**Describe the solution you'd like**
Would love to see the quick search (forward slash inserter) include the option to search the keywords for patterns (including custom patterns).

Thank you!

<img width="757" alt="Screen Shot 2020-10-14 at 9 46 55 AM" src="https://user-images.githubusercontent.com/1781226/96020020-46792500-0e02-11eb-9aba-6dfbcbd6e663.png">

**Comment by karmatosed** [comment]
@bradley2083 thanks for creating this issue. It's certainly an interesting idea and I took sometime to explore. The problem to solve, if I am correct, is how to add block patterns as easily within the flow as blocks. This does make sense, but there is a fundamental differences between blocks and patterns that perhaps suggests a different avenue to explore.

- Patterns don't have icons to denote them: this means the listing would be different to blocks.
- Patterns are by their nature visual: it really helps to see, to browse these before applying them.

Whilst, the first point could lead to exploring what this interface looked like with them adapted. The second point for seems to lend to a need to think of any 'quick route to adding' to also expose them visually. They are different content and I think there's a strong argument for needing to see a pattern before adding, even when an advanced users of this '/' command.

## Proposed solution
I started thinking of a way to bring maybe you quicker to the visual interace of patterns. What about adding a shortcut and once clicked the patterns section of the library would open?

<img width="506" alt="Frame 5" src="https://user-images.githubusercontent.com/253067/100274752-e3c58e00-2f56-11eb-9372-dca9141b4ced.png">

As '/' is considered an advanced function, there could be similar thinking here that advanced users would know and learn the keyboard shortcuts as they create content.

This solution does break the flow of creating, you move away from the area you are working. The future holds exploring different options with block patterns, for example maybe even a modal that displays them. (#26905) This could then become what opens on this shortcut. That would avoid taking from the flow of creating.

## Feedback
I realise that my solution is proposing something different, but due to the nature of patterns I think it's worth considering if it makes sense or not to add them to the '/' command. I'd love to open that discussion and hopefully my suggeston begins exploring being able to more rapidly get to patterns. I absolutely agree quickly accessing them is a great step, it's just how that could happen.

**Comment by webmaster-cob** [comment]
@karmatosed - I understand the desire to preview a pattern before inserting it. However, reusable blocks are discoverable through the / key inline option and they can be just as complex as patterns. We set up our reusable blocks with a common prefix to differentiate them between standard blocks. It works really well for us. We're looking forward to patterns being easier to manage so we can use them to replace reusable blocks in most cases. 
<img width="255" alt="2021-03-02 16_56_45-Add New Page ‹ City of Bellingham — WordPress and 13 more pages - Work - Microso" src="https://user-images.githubusercontent.com/26336976/109735875-4f338300-7b78-11eb-8c9e-232bb5c41ec1.png">

**Comment by shaunandrews** [comment]
I've briefly played with adding patterns to the `/` inserter:

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/191598/117488118-04e4ce80-af3a-11eb-875b-ea641f6b19e0.png">

Considering that pattern names often include block names, I think it might be difficult to navigate with a keyboard.

--

Alternatively, I think it might interesting to try a _new_ `;` inserter for specifically adding patterns:

<img width="423" alt="image" src="https://user-images.githubusercontent.com/191598/117488213-22199d00-af3a-11eb-92b1-9bb19c1e6d38.png">

I'm not sure how this would be introduced to users, as I expect it would be incredibly hard to discover.

**Comment by ghost** [comment]
We don't think a preview needs to be provided for patterns with the "/" inline inserter option. If you want a preview, you can use the "Add Block" or "Toggle Block Inserter" option. The "/" is meant to be a quick shortcut from our experience.

**Comment by annezazu** [comment]
This came up on a hallway hangout today with the FSE Outreach Program, especially as patterns are being prioritized in the quick inserter now. Consider this a renewed +1 :)

**Comment by richtabor** [comment]
>  as I expect it would be incredibly hard to discover.

Agreed.

**Comment by mtias** [comment]
The best way to introduce this is likely going to be the wp:pattern block, I don't think individual patterns should intermix with the slash inserter results otherwise.

**Comment by carolinan** [comment]
Are we expecting the / command to list both user-created and other patterns?

**Comment by richtabor** [comment]
> Are we expecting the / command to list both user-created and other patterns?

No. The inserter doesn't provide a well enough interface for deciding accurately what to choose. User-created patterns are fine, as they're something you've named yourself, but otherwise it'll be tough to distill whats what.

**Comment by carolinan** [comment]
Then isn't this issue solved? What is left to do?

**Comment by annezazu** [comment]
Good point. Let's close this out in favor of https://github.com/WordPress/gutenberg/issues/51921. Right now, with synced patterns being introduced, this can be a more productive way forward to connect this feedback with the current interface.
