### ISSUE TITLE
registerBlockVariation innerBlocks duplicate class attribute and classes

### ISSUE THREAD

**Issue by LukaszJaro** [WordPress/gutenberg#26165]
**Describe the bug**
When creating a block variation using innerBlocks, the class attribute and classes are duplicated. You can see the duplication in the html when you view page source.

**To reproduce**

1. Create block:
```
wp.blocks.registerBlockVariation(
		'core/group',
		{
		  name: 'pricing-table',
		  title: 'Pricing table',
		  icon: 'tag',
		  attributes: {
			className: 'pricing-table',
		  },
		  innerBlocks: [
			["core/heading",{align:"centre",className:"is-style-callout mb-0",content:"<strong>Pricing Table Title</strong>","level":2}],
			["core/table",{hasFixedLayout:false,caption:"",head:[],body:[{cells:[{content:'Fee..<br><span class="has-inline-color has-muted-text-color">Sub-fee with muted text colour...</span>',"tag":"td"},{content:"$<br>$",tag:"td"}]},{cells:[{content:"Fee 2..",tag:"td"},{content:"$",tag:"td"}]},{cells:[{content:"Total",tag:"td"},{content:"$",tag:"td"}]}],foot:[],className:"is-style-regular"}],
		  ],
		},
	  );
```
2. Insert block and publish page
3. View page source: `<h2 class="has-text-align-centre is-style-callout mb-0" class="has-text-align-centre is-style-callout mb-0">`

**Expected behavior**
No class attribute duplication when inserting block variation.

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Not using Gutenberg plugin

**Desktop (please complete the following information):**
Windows 10, all browsers impacted

**Comment by talldan** [comment]
Thanks for reporting @LukaszJaro. Unfortunately, I haven't been able to reproduce this. Here's the resulting HTML when I used the provided code snippet:
<img width="477" alt="Screenshot 2020-10-16 at 10 52 40 am" src="https://user-images.githubusercontent.com/677833/96207512-fcc54180-0f9d-11eb-94b3-b0b6b58d97f6.png">

It may be that it's already been fixed in the plugin. I notice you're using WordPress 5.4.2, which will be quite a few versions behind in Gutenberg terms.

**Comment by LukaszJaro** [comment]
Thanks for testing @talldan !

Next time I do maintenance on the site I will update WP and that will probably fix it.

Thanks,
