### ISSUE TITLE
[Widgets Screen] Twitter Block doesn't display embed on front end

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#26180]
**Describe the bug**

When embedding a twitter block in the widgets screen, the embed shows up properly in Appearance > Widgets but doesn't render when viewed on the front end of the site.

**To reproduce**
1. Create a new test site.
2. Install Gutenberg and activate.
3. Go to Appearance > Widgets.
4. Add a twitter block and embed a tweet.
5. View on the front end of the site. 

**Expected behavior**

I expect the twitter embed to work on the front end.

**Screenshots**

Front end of site:
<img width="574" alt="Screen Shot 2020-10-15 at 5 51 24 PM" src="https://user-images.githubusercontent.com/26996883/96197434-4d418e00-0f0f-11eb-9185-36bfa6bde342.png">

Appearance > Widgets Screen:

<img width="1251" alt="Screen Shot 2020-10-15 at 5 51 36 PM" src="https://user-images.githubusercontent.com/26996883/96197437-4e72bb00-0f0f-11eb-8347-0de67f0d5e43.png">

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg Plugin
- If the Gutenberg plugin is installed, which version is it? 9.1.1 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 86.0.4240.75

**Comment by fabiankaegy** [comment]
This issue probably relates to #26104

**Comment by talldan** [comment]
Looks like it might be all embeds as well from my limited testing

**Comment by talldan** [comment]
Did some further investigation. The class `WP_Embed` is responsible for processing embeds on the frontend.

Currently it runs on `the_content` (post content) and `widget_text_content` (text widgets), but not on other types of widget:
https://github.com/WordPress/wordpress-develop/blob/86fc3af215a61f042804e3feb57627976d2bb54d/src/wp-includes/class-wp-embed.php#L32-L40

I think we'd want it to also run for all block based widgets. I've made a trac ticket to cover this - https://core.trac.wordpress.org/ticket/51566

Lets keep this issue open so that it doesn't get missed.
