### ISSUE TITLE
Widgets Screen: Provide 'Manage with Live Preview'

### ISSUE THREAD

**Issue by garretthyder** [WordPress/gutenberg#26244]
**Is your feature request related to a problem? Please describe.**
With the Legacy Widget editor there was the 'Manage with Live Preview' which would take you to the Customizer > Widgets screen.
<img width="294" alt="Screen Shot 2020-10-16 at 5 26 15 PM" src="https://user-images.githubusercontent.com/8726005/96331288-0340d100-1011-11eb-9b38-56f784035d04.png">

**Describe the solution you'd like**
This screen still exists so we should provide the same link.

One concern is you can't really edit block widgets from the Live Preview it takes you back to the widgets screen.

**Comment by shaunandrews** [comment]
I'm not sure we need this button in the new screen. Its unclear to me what the purpose of it is, and what workflows it helps to enable.

**Comment by draganescu** [comment]
The purpose of the button originally was to be a shortcut and a highlight for the fact that the customizer offers real time preview of editing widgets. In our new editor the problem remains, as saving the editor produces effects immediately. But, we do have a preview ability now right in the stand alone editor, so the problem is ... halved?

Maybe instead of a manage with live preview button we could soup up that old thought of having a general preview button that switches all widgets into preview mode? But even so, it's nowhere near what the customizer offers with things previewing in context as you edit.

Also, the work that is going on to add blocks support to the customizer is another reason to keep this legacy button, for new users who land on this editor but don't know yet that in the customizer you have a better "live" preview, not just a preview.
