### ISSUE TITLE
How to enable global undo functionality?

### ISSUE THREAD

**Issue by capJavert** [WordPress/gutenberg#26271]
Hello,

I was looking and I can not find example of enabling global `undo` functionality to my Gutenberg editor instance. I am using standalone setup outside of wordpress (like one in storybook example).

Can someone point me in direction or answer is this even possible outside of full wordpress integration?

Tnx!

**Comment by talldan** [comment]
@capJavert How you implement it really depends on how you provide state to your editor. It's not a built-in part of the block-editor package.

In the editors in WordPress the functionality is provided by the `core/data` package's entity system, so if you're using that to manage your state it should be pretty straightforward. An example is the undo button in the site editor:
https://github.com/WordPress/gutenberg/blob/master/packages/edit-site/src/components/header/undo-redo/undo.js

And the redo button is pretty similar:
https://github.com/WordPress/gutenberg/blob/master/packages/edit-site/src/components/header/undo-redo/redo.js

**Comment by capJavert** [comment]
@talldan could you provide basic example to use `core/data` as replacement for (from [here](https://github.com/WordPress/gutenberg/blob/trunk/storybook/stories/playground/index.js)): 

```js
const [ blocks, updateBlocks ] = useState( [] );
```

I was looking through code and docs but could not find an example implementation. Is that even possible?

**Comment by talldan** [comment]
@capJavert `core/data` is specifically built for WordPress, so to be able to provide advice I'd need to know whether you're building something for WordPress. This is the list of WordPress data types supported by the `core/data` entity system:
https://github.com/WordPress/gutenberg/blob/1f55df53a0ec469c7abd7cbdb65568b08d84f906/packages/core-data/src/entities.js#L21-L128.

The system was really built with full site editing in mind, where a user may make edits to various bits of WordPress data (e.g. a post, a site title) all within the same editing session, so a user will need to be able to undo, redo, load, save those types of data. Generally these are tied to REST API endpoints. There is a specific `useEntityBlockEditor` react hook to build an editor around a single type of data, but also blocks and other types of UI can make edits to different entities (via something like `useEntityProp` and they'll be recorded as part of the same undo stack.

If you're building something that doesn't fit into that system then you would probably want to roll your own state management. So for example, you could use popular libraries like redux and redux-undo (https://github.com/omnidan/redux-undo) to implement the undo/redo functionality. You'd hook into the `onChange` and/or `onInput` handlers here:
https://github.com/WordPress/gutenberg/blob/1f55df53a0ec469c7abd7cbdb65568b08d84f906/storybook/stories/playground/index.js#L35-L36, so that whenever a change is made it's added to the undo stack, and then if an undo is triggered the value should reflect the 'undone' state:
https://github.com/WordPress/gutenberg/blob/1f55df53a0ec469c7abd7cbdb65568b08d84f906/storybook/stories/playground/index.js#L34

**Comment by capJavert** [comment]
@talldan thanks for clarification, yes, we are implementing a standalone editor (outside of wordpress). I will checkout the `useEntityBlockEditor` hook.

We were having trouble because by default Gutenberg overrides all `CTRL+Z` or `CMD+Z` shortcuts with `event => event.preventDefault()` so we had to patch that out to even get it to work and then implemented undo into our own state management (this part of codebase https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/rich-text/use-remove-browser-shortcuts.js). Any inside into that?

I though that by using wordpress state and data we could avoid patching gutenberg codebase and just use wordpress actions.
