### ISSUE TITLE
Nav Menu Block is Confusing

### ISSUE THREAD

**Issue by DaisyOlsen** [WordPress/gutenberg#26299]
**Is your feature request related to a problem? Please describe.**
Feedback posted by @helen in Widget Screen [Call for Testing Comments](https://make.wordpress.org/core/2020/09/30/call-for-testing-the-widgets-screen-in-gutenberg-9-1/#comment-40089)
The nav menu block is kind of confusing – adding/removing items is pretty slick but removing them later is kind of scary because it’s not clear whether you’re deleting one item as a block or the entire menu as a block (it’s the former). Maybe some highlighting would help here. It’s also a little strange in the customizer because it shows the contents of the nav menu as links that actually work instead of no-op-ing.

**Comment by jasmussen** [comment]
I agree quite a bit with the thoughts outlined, and would most of the concerns will be addressed once all issues linked from #27593 land. Are there any thoughts from this call for testing that are best opened as individual issues and added to the tracking issue?

**Comment by DaisyOlsen** [comment]
I think anything that needed to be opened as an individual issue from the pre 5.6 Call for testing of the Widgets screen were opened at that time. I worked with product design to identify which comments needed to be captured as issues. I don't know if any should be added to the tracking issue or not. @priethor any thoughts on this?

**Comment by priethor** [comment]
Thanks for the flag. I pretty much agree with both the feedback and with Joen, many of the raised concerns are due to the block still being a WIP.

Another thought that comes to mind related to the feedback (though not directly addressed in it) is how the navigation block _can_ work similarly to how reusable blocks do when you use a named menu created through the Navigation screen, so changes done to the navigation block affect all instances of that menu like with reusable blocks or other FSE blocks (site title, site logo), but if the menu is not named it acts like a normal, independent block.

However, after doing a quick search, as far as I understand this will be solved with PR #29012

**Comment by annezazu** [comment]
I'm going to close this out since there doesn't appear to be anything actionable at this point remaining. Feel free to reopen if that's not the case!
