### ISSUE TITLE
RadioControl: Focus styles need attention in Firefox

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/gutenberg#26293]
**Describe the bug**
I'm not sure what the intention for the focus styles are ([the CSS rules for them are here](https://github.com/WordPress/gutenberg/blob/f8e10e05f6b6e98a34b1e901badcb155c196227d/packages/base-styles/_mixins.scss#L375)) but they look completely different in Chrome and Firefox (and especially bad in Firefox):

<img width="816" alt="Captura de Tela 2020-10-19 às 11 39 14" src="https://user-images.githubusercontent.com/24264157/96497705-ee766000-11ff-11eb-8a2e-0b658edf120a.png">
<img width="880" alt="Captura de Tela 2020-10-19 às 11 39 01" src="https://user-images.githubusercontent.com/24264157/96497721-f2a27d80-11ff-11eb-8734-c27da231a28f.png">

**To reproduce**
Visit https://wordpress.github.io/gutenberg/?path=/story/components-radiocontrol--default in **Chrome and Firefox on macOS** and observe the differences in default styles as well as focused styles (by tabbing into the control).

**Expected behavior**
Styles should be the same across browsers or at the very least there shouldn't be the triple halo in Firefox.

**Additional context**
Found while working on CSS-in-JS conversion of the `RadioControl`

**Comment by skorasaurus** [comment]
Hi @saramarcondes 

In Firefox 85:
![Selection_037](https://user-images.githubusercontent.com/955351/106911661-647bd580-66d0-11eb-826e-3092ef6ad966.jpg)

And in Chrome: 
![Selection_038](https://user-images.githubusercontent.com/955351/106911647-6180e500-66d0-11eb-907e-7911f812b717.jpg)

Deferring to you whether this should now be closed.

**Comment by saramarcondes** [comment]
@skorasaurus I wonder if this is OS specific as I still see the issue. Screenshot from today:

<img width="193" alt="Captura de Tela 2021-02-04 às 08 39 16" src="https://user-images.githubusercontent.com/24264157/106925023-896a4b80-66c4-11eb-8257-1f935afcaa60.png">

**Comment by skorasaurus** [comment]
> @skorasaurus I wonder if this is OS specific as I still see the issue. Screenshot from today:
> 
> <img alt="Captura de Tela 2021-02-04 às 08 39 16" width="193" src="https://user-images.githubusercontent.com/24264157/106925023-896a4b80-66c4-11eb-8257-1f935afcaa60.png">

Very well could be; I'm on Ubuntu. You?

**Comment by saramarcondes** [comment]
I'm on macOS, I'll update the issue description to be more sepcific.

**Comment by carolinan** [comment]
Firefox 88.0.1 on PC, Windows 10:
![Radio control has a blue border with a small border radius](https://user-images.githubusercontent.com/7422055/117763073-7cf91000-b22a-11eb-8be1-118750ab2141.png)

**Comment by talldan** [comment]
This was issue was discussed in a triage session in slack (https://wordpress.slack.com/archives/C02QB2JS7/p1620710555026800).

Everyone could reproduce the inconsistent focus style in one form or another when comparing Firefox to Chrome (or chrome-alikes).

What seemed more serious is that Safari currently shows no focus style (https://wordpress.slack.com/archives/C02QB2JS7/p1620710989036300).

**Comment by t-hamano** [comment]
It has been some time since this problem was reported, so I was testing again.
In my environment, it is expressed as follows:

| State | Chrome | FireFox |
| ---- | ---- | ---- |
| Default | ![chrome_default](https://user-images.githubusercontent.com/54422211/206195613-055c67df-9f66-4f54-b3c2-ff68319ebf8e.png) | ![firefox_default](https://user-images.githubusercontent.com/54422211/206195926-c353f613-3a59-4c5d-9175-6c870c0db93a.png) |
| Focus | ![chrome_focus](https://user-images.githubusercontent.com/54422211/206195961-a8d333ef-0ba0-471c-a015-6bc035f92e31.png) | ![firefox_focus](https://user-images.githubusercontent.com/54422211/206195983-0abe7b6f-fce7-4767-ad76-196db66bd83e.png) |

- OS: Windows 11
- Chrome: version 108.0.5359.95)
- FireFox: version: 107.0

My feeling is that there are differences in appearance based on each browser's specifications, but they appear to be acceptable. I would be glad if someone could confirm the display, especially on Mac OS and Linux.
