### ISSUE TITLE
Add possibility to suppress rest_autosave_no_changes error

### ISSUE THREAD

**Issue by leurdo** [WordPress/gutenberg#26315]
**Is your feature request related to a problem? Please describe.**
I am building a block with server side rendering and inner blocks. This block gives possibility of editing post of another post type. So, nothing from this block is saving to its attributes except id of post from another post type. Everything is saving to another post type from state.

But when inner blocks are changed, autosave throws 400 error (nothing to save). Yes, we have really nothing to save, but this is normal.

**Describe the solution you'd like**
I would like to have possibility to suppress rest_autosave_no_changes error with hook or something. Or make it just a warning, not error.

**Describe alternatives you've considered**
Or please offer another solution of this problem.

**Comment by tellthemachines** [comment]
Changing the post autosaving behaviour might produce unexpected results, but a possible workaround would be to generate something saveable by modifying a block attribute on every change, or every few changes - incrementing a number, for instance. Would that work?

**Comment by tellthemachines** [comment]
Actually, thinking better of this, there's already a way to do this in core blocks. For an example, check the implementation of [reusable blocks](https://github.com/WordPress/gutenberg/tree/try/group-variation-placeholder/packages/reusable-blocks), where the contents of a block are saved to a post type. A similar behaviour exists in the [Navigation block](https://github.com/WordPress/gutenberg/tree/try/group-variation-placeholder/packages/block-library/src/navigation) too.

I'm going to close this issue because it's been inactive for a long time and the question should be answered now 😅 but feel free to reopen if that's not the case!
