### ISSUE TITLE
Design improvements to the Link UI

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#26351]
The link UI could use some design tweaks to bring it line with the evolution of the interface:

![image](https://user-images.githubusercontent.com/548849/96708949-43e67480-139a-11eb-8dde-f5820173936d.png)

- Update the "return" icon.
- Update the circular + to the now standard black [+].
- Revise the lines: should they be darker? Should they be equal in length?
- The "create new page" flow only happens after search has finished. Should it be shown sooner or does it risk too much in terms of possible conflicts? I think it should be shown immediately.

Suggestion for icon:

![image](https://user-images.githubusercontent.com/548849/96709454-fddde080-139a-11eb-8667-a88a53605cf4.png)

**Comment by karmatosed** [comment]
In tackling this problem I think it would be a good idea to split this into iterations that bring inline with current styling and then start to consider later going beyond the existing experience. As a result the first exploration I've done focuses on iteration, specifically around these points:

- Update the "return| icon.
- Update the "+" circular visual.
- Iterate the spacing and lines.

> The "create new page" flow only happens after search has finished. Should it be shown sooner or does it risk too much in terms of possible conflicts? I think it should be shown immediately.

I tend to agree with you @mtias that as soon as we can show this, it should be shown. I would love to know other's feelings here and what the possible conflicts could be. I came to this decision based on having to wait for the option is a hitch in the experience flow that's avoidable if it's shown immediately.

## Iteration

### Icon
I did explore whether the return icon existed @mtias, this might be myself not finding it so please let me know if that's the case. However, I created something approximate to your suggestion that I think could work:

<img width="396" alt="icon-return" src="https://user-images.githubusercontent.com/253067/97320351-9970c480-1865-11eb-8ea1-bbb8e59a7675.png">

I'm interested in opinions if this aligns when seen in explorations to come.

## Smaller iterations
There are 2 'stages' to this I have explored, searching and results. First, searching:

<img width="360" alt="i1_ smalliterations no suggestion" src="https://user-images.githubusercontent.com/253067/97339466-887e7e00-187a-11eb-89ea-02193e41e175.png">

Here the following changes to the search results:

<img width="360" alt="i1_ small suggestion" src="https://user-images.githubusercontent.com/253067/97339495-903e2280-187a-11eb-8afe-a5ab5b499089.png">

A summary of points that have changed would be:

- New icon
- Aligning the + styling
- Removing one of the lines: this brings the same relating content together

### Futher exploring
Taking the idea of reducing the horizontal lines, some further explorations lead me to the following:

<img width="360" alt="i1_ smalliterations no suggestion2" src="https://user-images.githubusercontent.com/253067/97339540-9fbd6b80-187a-11eb-91a3-75c1c4df2d0f.png">

<img width="360" alt="What if 3" src="https://user-images.githubusercontent.com/253067/97338711-9b448300-1879-11eb-9531-9321a40c72fb.png">

What the above explores and raises is perhaps what the intent should be to the grouping. Perhaps there is merit in grouping by actions, for example creating and opening in a new tab. I would love some discussion around this but do feel this goes beyond the iterations that can start happening.

## Looking beyond
Whilst the above explorations do all focus on the existing interface, I think in working through this there is some more work to be done around this interface. Where possible, the link interface should be as similar as possible and trusted in what it will be. I do however think focusing feedback on these explorations begins that and gets some experience gains in earlier.

## Feedback
I am looking specifically for feedback on:

- Is the icon aligned with existing work?
- Is there anything missing from these explorations?
- Is there anything should be iterated on in these explorations?

## Next steps
Once I have some feedback, the goal will be to iterate or get a PR as soon as possible for this. There is some good 'low hanging' fruit experience wise to catch here which is always a great.

**Comment by karmatosed** [comment]
I worked on a little PR of some of the changes here, specifically the removal of border and also adjusting some padding:

![image](https://user-images.githubusercontent.com/253067/97491751-7c69ed80-195a-11eb-95b3-fddeac08fddc.png)

**Comment by mtias** [comment]
@karmatosed added the icon to the figma, it's in the "explored" group:

![image](https://user-images.githubusercontent.com/548849/97574337-5cced580-19eb-11eb-94ac-19cd00d5d1bd.png)

**Comment by karmatosed** [comment]
@mtias thanks, that's great!

**Comment by karmatosed** [comment]
Updating here some more work that has gone on in the PR, this includes extra changes like label styling, spacing and some general tidying.

![2020-10-29 21 54 25](https://user-images.githubusercontent.com/253067/97636787-8b6f9f00-1a31-11eb-91c7-d10f9d52a679.gif)

**Comment by karmatosed** [comment]
There has been quite a bit of work done around this and next is to get some development assistance around this.

## Current
After a little back and forth in a PR, visual updates are now in. All the new icons and some additional iterations are in place. This is what currently it looks like:

![2020-11-11 20 29 09](https://user-images.githubusercontent.com/253067/98861520-50239600-245d-11eb-8c0f-e98c24b8bb0c.gif)

## What is next?
The missing piece is around the way 'create' works. I would advise this should as said by @mtias be shown as soon as possible. 

> The "create new page" flow only happens after search has finished. Should it be shown sooner or does it risk too much in terms of possible conflicts? I think it should be shown immediately.

As noted by @shaunandrews in #26317, then taking this to other areas for the link interface would be needed.

**Comment by skorasaurus** [comment]
ref https://github.com/WordPress/gutenberg/issues/24099

**Comment by getdave** [comment]
@jasmussen Do you think we can safely close this one out? I seems we can but I would appreciate a second opinion.

**Comment by jasmussen** [comment]
A vast amount of stuff has happened to the Link UI since this ticket:
![link ui](https://user-images.githubusercontent.com/1204802/141740479-bf2cd72e-91bb-4e85-b4a0-c92581bd9b31.gif)

Enough that in most cases it makes most sense to close out this ticket, and if need be, open new specific ones. In the case of this issue, one remaining task is the "Create new" item mentioned here:

> The "create new page" flow only happens after search has finished. Should it be shown sooner or does it risk too much in terms of possible conflicts? I think it should be shown immediately.

That still appears to be the case:
![create new](https://user-images.githubusercontent.com/1204802/141740656-4424f5d2-5070-45e6-b157-12d3ff54b88a.gif)

I wonder if a quick fix is to just literally show the "Create new page" immediately, as soon as you start typing, so you don't have to wait for the search to complete?

---

Related, I think there are some design improvements we can make and track separately. One of the challenges we have is that the weight of items is pushing down the "Create new page" button: 

<img width="431" alt="Screenshot 2021-11-15 at 08 46 28" src="https://user-images.githubusercontent.com/1204802/141742096-9facd452-a852-4858-827c-49aea0188f93.png">

Could we reduce each item to one line? In this example, the word "Pocahontas" hasn't been used on the site at all:

<img width="380" alt="URL dialogs" src="https://user-images.githubusercontent.com/1204802/141743801-58cdc319-834b-474a-adb4-36230b7f9603.png">

But if there was a page called "Pocahontas", it would show up first:

<img width="380" alt="URL dialogs" src="https://user-images.githubusercontent.com/1204802/141744170-c366333b-0d4f-4133-adb6-01275094c4b1.png">

In this case, the word "about" shows up in quite a few places:

<img width="380" alt="URL dialogs" src="https://user-images.githubusercontent.com/1204802/141743918-a063226a-c436-4201-9b27-89f7d8e58729.png">

Let me know what you think and I can create a new ticket tracking future design improvements.

**Comment by shaunandrews** [comment]
I'd love to see a more thorough and wholistic design for the Link UI that covers all the scenarios and use-cases across the editor, it's blocks, and perhaps wp-admin. I'm all for small tweaks in various separate issues/PRs to incrementally improve the existing UI, but I'm still lacking a general end-goal or direction.

For instance, it seems there are now icons for different post-types, but I'm not sure these are placed correctly (Should they be on the right? Maybe they should be smaller?) or if they're added visual weight is necessarily worth it. Or, is dropping the URL/permalink actually helpful, or harmful?

I think the mockups you posted above are a good starting point; They reduce some of the spacing, line-heights, and overall size of the UI. Maybe some more iteration there will help provide a solid map towards where smaller tweaks and issues should go.

**Comment by getdave** [comment]
Thanks for this review 🙇 Given that all but one of the concerns have been addressed I'd personally I'd like to see a new Issue tracking  new improvements.

> I wonder if a quick fix is to just literally show the "Create new page" immediately, as soon as you start typing, so you don't have to wait for the search to complete?

Let me look into this one.

> Could we reduce each item to one line? In this example, the word "Pocahontas" hasn't been used on the site at all:

I know that we can't easily do this because doing so makes it very hard to discern the different between certain results. We intentionally wrap longer items to ensure the user has full access to the information about the search suggestion.

We addressed this in https://github.com/WordPress/gutenberg/pull/33753 in response to user feedback in https://github.com/WordPress/gutenberg/issues/33586.

> ...the weight of items is pushing down the "Create new page" button:

I wonder whether making a dedicate UI button for this function would be better than tacking on a "Create" option as we do currently? The question of reducing the number (quantity) or size (visually) of the results has been suggested a few times in various places but it always ends up with us loosing to much information that the user cares about in the results.

> I'd love to see a more thorough and wholistic design for the Link UI that covers all the scenarios and use-cases across the editor, it's blocks, and perhaps wp-admin.

I'd be happy to see this and work with a designer to iterate on it.

**Comment by karmatosed** [comment]
> Thanks for this review 🙇 Given that all but one of the concerns have been addressed I'd personally I'd like to see a new Issue tracking new improvements.

+1

**Comment by jasmussen** [comment]
Coming back to this one, here are the freshest mockups showing URL dialogs filtered across a slew of contexts:

<img width="1740" alt="URL dialogs i2" src="https://user-images.githubusercontent.com/1204802/197507918-c21bf038-f6ba-4f21-bb95-2b55bac23f44.png">

And the search options:

<img width="1220" alt="Searching i2" src="https://user-images.githubusercontent.com/1204802/197546715-46d2f12f-44d4-493b-93fe-acd1526dd9f1.png">

Are they appropriate to update this issue? Or is it best to create a separate issue?

**Comment by richtabor** [comment]
I'm closing this issue as quite a bit has adapted since, and we have https://github.com/WordPress/gutenberg/issues/50891 moving forward that focuses on a holistic UI/X refresh of LinkControl.
