### ISSUE TITLE
Rethink how the template part work and persist its properties

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#26392]
The template part as written today supports a number of properties:

 - `tagName` to  choose the wrapper tag: header, footer,  section, div...
 - some styling attributes: color...

The idea was that template parts should have similar configuration options as the group block to be able to use them properly for headers, footers, sidebars...

The problem though is  that these properties are saved as regular block attributes in the comment something like:

```
<-- wp:template-part { "tagName": "footer", "postId":10  }  /--> 
```

which means they are not saved on the template part itself but on the "caller" or "template" making use of the template part. It means these semantics do not persist across the usage of the same template part, and this kind of defeats their purpose.

**Potential solution**

 - Make the template part block work like an empty wrapper  (like a reusable block) without any customization properties
 - On the UI level, when creating new template parts... encourage the addition of a group block at the root level of all template parts.

cc @noahtallen @vindl @mtias

**Comment by mtias** [comment]
I think conceptually it makes sense to attach properties to the template part, but perhaps there's a way to make the Group be a controlled block (always the first element) even if its properties can be set from the template part UI (they are saved instead in the Group). Would that make sense?

**Comment by noahtallen** [comment]
I do think the challenge with nested group blocks is just that navigating nested blocks is not an ideal experience (in my opinion), so I personally prefer to avoid requiring it for common use cases. (_Especially_ because the nested block inserters cause the UI to jump around) 

> It means these semantics do not persist across the usage of the same template part, and this kind of defeats their purpose.

One of the arguments from @Addison-Stavlo when we discussed this last was that it might be more practical to have the attributes be specific to the entity than to all template parts. Copying my comment from a different issue:

> I'm on board with just leaving it as block attributes at the template level. The two things that persuaded me:
> - It's a lot easier to put a group block inside a template part and have it apply to all template parts than it is to put a group block outside of every template part.
> - None of the possible solutions to the problem seem to work in a clean way with nice API. On the one hand, we would be trying to directly block attributes into post meta of a different post, which would be pretty non-standard, and on the other hand, we would be trying to merge two template part block attributes with each other.

(from https://github.com/WordPress/gutenberg/issues/22034#issuecomment-685166740)

I do like the idea of allowing those attributes to be global, but I'm just not sure how to make that happen, since the template part _block_ itself is not ever global by itself

> but perhaps there's a way to make the Group be a controlled block

would this mean that the group block is basically "transparent" in the block editor?

**Comment by Addison-Stavlo** [comment]
>  and this kind of defeats their purpose.

I don't think it entirely defeats their purpose.  It gives settings that can be applied specifically on that template.  Thus the same template part could be used on multiple templates with minor style differences (color variations, etc.).  I discussed an example of how this might look in practice here: https://github.com/WordPress/gutenberg/issues/22034#issuecomment-683170709.  Styles from inner blocks (such as a group block wrapping the content inside the template part) can still be used to apply these settings across all template parts.  In the case of the template part block we are just giving styles to the block that wraps the entity, in which case it makes sense that they would not persist to another block wrapping that entity elsewhere.

**Comment by youknowriad** [comment]
The ship has sailed here. I'm closing for now.
