### ISSUE TITLE
Preset size dropdown includes empty li when only custom font sizes are enabled

### ISSUE THREAD

**Issue by alexdelgado** [WordPress/gutenberg#26489]
Currently you can add a list of font sizes via `editor-font-sizes` or disable them completely with `disable-custom-font-sizes`. 

If you just want to enable custom sizes you can set `add_theme_support( 'editor-font-sizes', array( '' ) )`. However, the "Preset Size" dropdown displays with an empty line item.

<img width="270" alt="Screen Shot 2020-10-26 at 9 17 17 PM" src="https://user-images.githubusercontent.com/5625356/97248846-a2638680-17d0-11eb-9806-3ae399c17a17.png">

I think the expected behavior should be that the dropdown doesn't show or at least doesn't have an empty line item.

**Comment by talldan** [comment]
Looks broken to me even when supplying the sizes from the docs:
```php
	add_theme_support( 'editor-font-sizes', array(
		array(
			'name' => __( 'Small', 'themeLangDomain' ),
			'size' => 12,
			'slug' => 'small'
		),
		array(
			'name' => __( 'Regular', 'themeLangDomain' ),
			'size' => 16,
			'slug' => 'regular'
		),
		array(
			'name' => __( 'Large', 'themeLangDomain' ),
			'size' => 36,
			'slug' => 'large'
		),
		array(
			'name' => __( 'Huge', 'themeLangDomain' ),
			'size' => 50,
			'slug' => 'huge'
		)
	) );
```

<img width="145" alt="Screenshot 2020-10-30 at 4 15 48 pm" src="https://user-images.githubusercontent.com/677833/97676277-5ca60700-1acb-11eb-905e-aaea47db077d.png">

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting.  I think this has been solved because the interface is no longer a dropdown;  as indicated in the screenshot. 

if no custom font-sizes are enabled.
![image](https://user-images.githubusercontent.com/955351/152059289-ca40dafc-c60a-4df6-a171-15f3126445be.png)

when custom font-sizes are enabled
![image](https://user-images.githubusercontent.com/955351/152059442-c816c55a-b641-447f-8790-b5ea40cae032.png)


Please reopen if you still have this issue. 

Tested using wordpress 5.9, w/o gutenberg activated.
