### ISSUE TITLE
Query: Number of pages settings are too restrictive

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#26550]
### Problem
Currently, the "Number of pages" control requires the user to set the exact number of pages they want to include in the query.

![Screen Shot 2020-10-28 at 11 47 24 AM](https://user-images.githubusercontent.com/617986/97483106-473aac80-1914-11eb-9c3b-330d3ee425ca.png)

This is a problem because many times the user might want to include _all_ posts that match their settings and may not know the exact number they need to type as the page count.

### Solution
I realize that the Pagination block should be one the user can add, duplicate, and move around (hopefully from within the Query block). But the setting should be a simple toggle to turn on or off pagination, not an input field. Maybe in the block itself, a user can adjust whether or not they want "All" pages or limit this by a particular number.

Can we try something like this?

![pagination](https://user-images.githubusercontent.com/617986/97486567-db0e7780-1918-11eb-8dc9-8c10082cbfaa.gif)

I also imagine the Pagination block would provide the same options as other blocks such as "Duplicate" allowing more than one Pagination block and moving it to above or below the list.

![Screen Shot 2020-10-28 at 12 35 06 PM](https://user-images.githubusercontent.com/617986/97487504-2c6b3680-191a-11eb-8069-0a1812c525b8.png)

cc @ntsekouras @mariohamann

**Comment by mariohamann** [comment]
- I wasn't aware of the concept of "Number of pages". In my opinion, this option doesn't make sense. Is this option still available? In the loooong discussion in https://github.com/WordPress/gutenberg/issues/25198#issue-697086719 it seemed to be abandoned very early? (Is this option available in REST?)
- I totally second the idea that the pagination block should be inside the Query Block – I think that makes things easier in technical terms.
- I like the interaction to add a pagination Block and I like the concept of adding more than one pagination block. Instead of a Boolean: What do you think about an "Add button"? I think in that case we could add a pagination block per default (Currently it would feel strange to have pagination active per default, but in FSE it would be quite useful.)

![Screen Recording 2020-10-28 at 21 45 56](https://user-images.githubusercontent.com/26542182/97494802-1cc60f00-1967-11eb-8332-3373e2bb6377.gif)

## Further thoughts
- Will pagination be available outside of FSE? That wouldn't work, would it?
- To show the Top 10 of posts, users would select "10 posts per page" and "No pagination". Quick thought concerning the labels: Might it the label "posts per page" irritate if there is only one page?

**Comment by mapk** [comment]
Thanks, @mariohamann!

>I like the interaction to add a pagination Block and I like the concept of adding more than one pagination block. Instead of a Boolean: What do you think about an "Add button"?

I believe the Inserter (panel and/or inline) would solve this. Here's a screenshot of how it is right now.

![Screen Shot 2020-10-29 at 11 13 54 AM](https://user-images.githubusercontent.com/617986/97616752-318fba80-19da-11eb-82b6-de0b9318bb5c.png)

The initial idea behind the toggle in the toolbar was about turning pagination on... not so much around adding pagination, although it did that as well. :)

I did receive some feedback today from @jameskoster and @MichaelArestad about including the Pagination block in the Query block by default. And if the user doesn't want it, they can just delete that block. Here's how that might work.

![pagination](https://user-images.githubusercontent.com/617986/97621047-9699df00-19df-11eb-8840-36fb28f943f4.gif)

**Comment by MichaelArestad** [comment]
Could we remove the number of pages setting? This seems like information that should be passed to the pagination block somehow without a user needing to specify.

**Comment by jameskoster** [comment]
Isn't the Number of pages setting is entirely redundant? 

I'd have thought it would be calculated automatically – `total number of posts returned by query / number of posts displayed per page = number of pages`

**Comment by mapk** [comment]
@ntsekouras can we get to this point where the Pagination block is added by default to the Query block? And then if we can revise the dropdown to look more like this:

- Eliminate the "number of pages" option.
- Add helper text to the "offset" option along with a more thorough label.

![Screen Shot 2020-11-03 at 10 33 48 AM](https://user-images.githubusercontent.com/617986/98026613-409eb000-1dc0-11eb-80ea-17c85c1b29cc.png)

**Comment by skorasaurus** [comment]
was requested by a user at https://github.com/WordPress/gutenberg/issues/22226 ;

**Comment by ntsekouras** [comment]
Closing this as `Number of pages` is handled with `Query Pagination` block (https://github.com/WordPress/gutenberg/pull/28125)
