### ISSUE TITLE
Add block 'badges' to communicate at-a-glance information

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#26632]
In https://github.com/WordPress/gutenberg/pull/26594 a need arose for a stylised "beta" token that would be applied to the Site Editor menu item in the wp-admin navigation. 

This affordance may also be useful on a per-block level in the Site Editor as it becomes more prominent over time, to remind folks that many features are still a work in progress.

<img width="1415" alt="Screenshot 2020-11-02 at 13 31 24" src="https://user-images.githubusercontent.com/846565/97873601-c878b180-1d0f-11eb-88dc-83b190ecdf35.png"> 

We can apply a similar style treatment to the Site Editor link in the wp-admin navigation for consistency, if there is perceived value in doing so:

<img width="220" alt="Screenshot 2020-11-02 at 13 42 10" src="https://user-images.githubusercontent.com/846565/97874656-3a052f80-1d11-11eb-9f81-7c1f33e26019.png">

---

Taking one step back, this feature may also be handy in the future for communicating other at-a-glance block information such as newness, secondary grouping (e.g. to indicate which blocks were added by a specific plugin), or whether an upgrade is required (for blocks with premium features).

<img width="849" alt="Screenshot 2020-11-02 at 13 40 02" src="https://user-images.githubusercontent.com/846565/97874474-eeeb1c80-1d10-11eb-9cb5-cd0a07ec6b66.png">

**Comment by priethor** [comment]
Block badges came as feedback during the Go/No-go demo on April 14th with the goal of marking block themes as "Lab" blocks, denoting they are stable (not beta) and can be used, but the user experience might not be polished yet.

**Comment by hedgefield** [comment]
This looks excellent and will indeed be very useful. I'd maybe bold the label text as the white on black is kinda hard to read at a small size. Otherwise I say go for it!

Small aside, I don't know if "Lab" is really going to be a word that means anything to the average user out of context like that. But I agree "Beta" or "Experimental" might make it sound too unstable. Perhaps something in the vein of "Early access", "Rough" or "Basic".

**Comment by priethor** [comment]
I think "Early access" is the option that best conveys the message.

**Comment by youknowriad** [comment]
This didn't make the 5.8 cut, I'm removing it from the board. also cc @mtias in case you have thoughts about this, I know that we decided against such an API previously.

**Comment by mtias** [comment]
Yes, I worry about making it an API because it can get out of control without a clear indication of what we want to signal — are badge terms related to a specific taxonomy? Can they be used for anything? Would people use them as tags? Can you have many? Can they be extended? Can you remove existing ones? I'd expect we would also receive requests for colors, or icons, or making them actionable (act as a button), etc, if we are not clear about purpose and boundaries.
