### ISSUE TITLE
TikTok Embed: The play button is unclickable on Chrome

### ISSUE THREAD

**Issue by jonnyruzek** [WordPress/gutenberg#26635]
Step to Replicate

- Create new post or page.
- Select Tiktok embed block to add a tiktok video.
- Publish the page.

Expected:

You should be able to click on the play button to play the video.

Actual:

The button is unclickable when checking on Chrome. Browser details: https://www.whatismybrowser.com/ Chrome 86 on macOS (Catalina). The user who reported this issue was checking it on Edge.

It works fine on Safari and Firefox though.

**Comment by tellthemachines** [comment]
I'm unable to reproduce this on Chrome 86/macOS Catalina, with either WP 5.5.3 or 5.6-beta4. @jonnyruzek which version of WP/Gutenberg plugin are you using? 

My Chrome browser just updated today so it could also have been an issue on their side.

**Comment by jonnyruzek** [comment]
I can't reproduce this now on macOS 11.0.1 / Chrome 86 either. 

Using Gutenberg 9.3 on WordPress.com. Closing this for now.

**Comment by WinserverSupport** [comment]
Its June 5, 2021 and I am able to repeat this problem.  I created an example link, https://home.winserver.com/public/tiktok.  I tried it on Current Chrome on two different PC's (Windows 7 and Windows 10).   Going to try my iPhone now...  Works...     On Windows 7 & 10, I opened the Chrome Debug window and I see Policy Permission errors which is what lead me to [https://github.com/w3c/webappsec-permissions-policy/blob/main/features.md#sensor-features](https://github.com/w3c/webappsec-permissions-policy/blob/main/features.md#sensor-features) and then here.   Since I am typing on my Windows 10 machine, I will display an snapshot of the errors I see:

![image](https://user-images.githubusercontent.com/64587872/120893868-5e94f300-c5e3-11eb-85fa-57cbefbf41d3.png)
