### ISSUE TITLE
Button block not generating the proper HTML for the link to work

### ISSUE THREAD

**Issue by nomad411** [WordPress/gutenberg#26697]
**Describe the bug**
When using the button block in a post, and adding a link, the link is not clickable when viewing the page on the frontend.

**Editor version (please complete the following information):**
- WordPress version: 5.5.3
- "default" block editor

I tested with WP only, using TwentyTwenty.

The generated tag looks like this: 

`<a class="wp-block-button__link" target="_blank" rel="https://yahoo.com/ noopener noreferrer">Press Me!!!</a>`

**Comment by skorasaurus** [comment]
Hi @nomad411 

This has tripped up my co-workers several times. 

You can insert the destination link by using the block's toolbar as indicated [in this WordPress guide](https://wordpress.com/support/wordpress-editor/blocks/buttons-block/#linking-a-button) instead of the side panel. 

In this context, the `rel` values aren't supposed to be URLs but [for SEO and content marketing](https://support.google.com/webmasters/answer/96569?hl=en) .

**Comment by nomad411** [comment]
Ahhh Grr! 

Thanks a bunch.
