### ISSUE TITLE
MS Edge and Polish letter "ą"

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#26710]
From https://core.trac.wordpress.org/ticket/45872.

---

Hi team,

I use MS Edge on daily basis and have noticed that only in that browser (Chrome, Firefox, IE are OK) i cannot type Polish letter "ą" when editing post. To type special Polish letters right ALT key is used with that letter, so in this case RAlt+A. Unfortunately this key combination selects all text (all blocks) in the editor - just like Ctrl+A - instead of typing "ą". All other special letters like "ę, ś, ć, ł, ó, ż, ź etc. are OK.

I am using the latest WP and plugins are updated to the latest versions. Occured also in troubleshooting mode of the Health Check & Troubleshooting plugin.

Please advise.
Thank you,
Michal

**Comment by getsource** [comment]
Hi, and for those following, sorry that this has taken so long for a response since the initial report.

This issue was mentioned in a [triage session today](https://wordpress.slack.com/archives/C02QB2JS7/p1617083005046000).

I tested by setting my keyboard in Windows 10 to the Polish one, and was able to enter `ą` key with RAlt+a into Edge 89.0.774.63, using the most recent Core trunk nightly.

I'm wondering if this was fixed in Edge since the initial report, perhaps with the move to Chromium.

Since it seems to be working at this point, I'm going to close this issue for now.
However, if you are still having the problem -- apologies, and please do feel free to comment and reopen!
