### ISSUE TITLE
wp-env does not automatically activate the first theme in .wp-env.json

### ISSUE THREAD

**Issue by ecgan** [WordPress/gutenberg#26766]
**Describe the bug**

According to https://www.npmjs.com/package/@wordpress/env#wp-envjson, the "themes" field is:

> A list of themes to install in the environment. **The first theme in the list will be activated.**

In my WooCommerce project, I have the following `.wp-env.json`: 

```json
{
	"core": null,
	"plugins": [ 
		"https://downloads.wordpress.org/plugin/woocommerce.latest-stable.zip",
		"." 
	],
	"themes": [
		"https://downloads.wordpress.org/theme/storefront.latest-stable.zip"
	]
}
```

The Storefront theme is installed but not activated automatically.

**To reproduce**

1. In a plugin project, create a `.wp-env.json` with the above data.
2. Make sure `composer install`, `npm install` and `npm run build` is already run.
3. Run `npm run wp-env start`. This should download and activate the plugins and theme.
4. Open up a browser and go to http://localhost:8888/wp-admin/themes.php. 

![Screenshot on 2020-11-06 at 18-22-18](https://user-images.githubusercontent.com/417342/98355443-174e8000-205d-11eb-9577-a74dcc8ca54e.png)

**Expected behavior**

The storefront theme should be installed and activated.

**Actual behavior** 

The storefront theme is installed, but the active theme is Twenty Twenty.

**Comment by noahtallen** [comment]
@ecgan Thanks for the report! We deliberately removed this functionality, but I guess the docs did not get updated.

The reasoning for removing this behavior is this use case:
1. You run `wp-env start`. A particular theme is activated.
2. Since you have several mapped themes, you activate one of them for testing.
3. You run `wp-env start` again. Your active theme is switched back to the one in the config file.

This is unexpected behavior -- most folks would expect the theme they activate to remain activated in the database, but this was not the case.

**Comment by ecgan** [comment]
@noahtallen , this is just an idea off the top of my head, is it possible to make wp-env activate the theme on first run? i.e.:

1. Run `wp-env start` for the first time. It will auto-download docker, install plugins and themes, and activate the first theme.
2. Run `wp-env start` for the subsequent times. Since the things are already installed and setup, no need to activate anything.
3. Run `wp-env destroy` to delete everything.
4. Run `wp-env start`, which is treated like being run for the first time - auto-download docker, install plugins and themes, and activate the first theme.

I see themes similar to plugins. When I have a plugin defined in `.wp-env.json`, it is auto-installed and activated. I can manually deactivate the plugin in wp-admin. When I run `wp-env stop` and `wp-env start`, the plugin stays deactivated. Can this be applied to themes as well?

**Comment by noahtallen** [comment]
I think that behavior is possible, but I do think plugins work a bit different from that. (If you run `wp-env stop` and then `wp-env start --update`, the code tells the plugin to activate again.)

I think it's possible to implement anyways.

That said, you can also just activate the theme via CLI: `wp-env run cli "wp theme activate twenty-twenty"`. What's your particular use case?

**Comment by ecgan** [comment]
@noahtallen , 

> That said, you can also just activate the theme via CLI: wp-env run cli "wp theme activate twenty-twenty". What's your particular use case?

I was thinking it would be tedious to manually switch to a theme after I run `wp-env destroy` and `wp-env start`, but I can put the CLI command into an initialization script. That slipped my mind. Thank you for the good idea! 🙂

**Comment by nielslange** [comment]
I just run into the same problem and found out that `wp-env run cli "wp theme activate twenty-twenty"` only changed the theme within the WordPress development site. To change the theme within the WordPress test site, I ran the command `wp-env run tests-cli "wp theme activate storefront"`. I thought it's worth sharing in case someone else is facing this problem.

**Comment by firxworx** [comment]
Note for those who stumble here in the future. If using `pnpm` with `wp-env` installed via the inclusion of `@wordpress/env` in your `package.json` dependencies, you may get an error if you try to use commands with the quoting noted in the above examples in this thread.

Example error:
 "OCI runtime exec failed: exec failed: unable to start container process"

The issue is that docker sees the whole string vs. command and arguments. The following is an example that will work for you to use wp-cli (assuming wp-env is up and running):

```bash
pnpm wp-env run cli wp theme activate twenty-twenty
```

**Comment by andrewfleming** [comment]
The WP-CLI command to activate a theme can be added to the [lifecycleScripts](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-env/#node-lifecycle-script) object, avoiding a separate initialisation script.

```
{
	"core": null,
	"phpVersion": "8.2",
	"plugins": [
		".",
		"https://downloads.wordpress.org/plugin/query-monitor.3.16.4.zip"
	],
	"themes": ["https://downloads.wordpress.org/theme/storefront.latest-stable.zip"],
	"lifecycleScripts": {
		"afterStart": "wp-env run cli wp theme activate storefront"
	}
}
```
