### ISSUE TITLE
Display Block Vendor

### ISSUE THREAD

**Issue by tomjn** [WordPress/gutenberg#26848]
**Is your feature request related to a problem? Please describe.**

Blocks should display their vendor/where they came from somehow, I'd suggest in the block inspector at the top:

<img width="300" alt="Screenshot 2020-11-10 at 12 06 33" src="https://user-images.githubusercontent.com/58855/98672122-32ffa200-234d-11eb-8bc1-29a779ed803e.png">

Ideally, via a `vendor` option when registering a block.

_As for why..._

I was trying to help a user recently who was asking a question about a container block, and swore blind that it came from Gutenberg and had no plugins, despite there being no such block in WP core. The block was named `Container` and had no clues as to where it came from.

I eventually tracked it down to either Atomic Blocks or Genesis Blocks, but the user insisted they were using no plugins and the default theme. Perhaps they'd used the block directory? Either way the user became hostile when presented with direct evidence it was not a core block. This would have been trivial to avoid if the block had provided a vendor name and it had been displayed somewhere in the interface.

**Comment by mapk** [comment]
How about something like this?

![Block Author 1](https://user-images.githubusercontent.com/617986/98751460-06f81700-2375-11eb-95bb-51361add4aa4.png)

**Comment by carlomanf** [comment]
With respect, I think the real problem is your customer service skills. Anyone knows the way to solve this is to deactivate plugins one by one (not to mention refrain from calling users hostile.)

Plugins have never been expected to differentiate their UI additions from those of core. The software is GPL, meaning that core + plugins together become one piece of software. Furthermore, many applications are white-labeled and rely on being able to fully wipe the branding of WP and that of plugins.

Maybe there could be a settings screen visible to only admins that tracks registered blocks to their respective plugins, but it shouldn't inject advertising into the editor nor should it inflict an API change on plugin developers.

**Comment by tomjn** [comment]
> How about something like this?

👍  This looks good to me, simple, straight forward, understated.

**Comment by skorasaurus** [comment]
Hi @tomjn ; while triaging, I found another issue - https://github.com/WordPress/gutenberg/issues/16521 that requests what you're looking for, specifically when it was triaged - https://github.com/WordPress/gutenberg/issues/16521#issuecomment-582021004 Please subscribe to that issue and follow it for progress.
