### ISSUE TITLE
A Nicer Home for the Docs

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#2686]
Gutenberg docs currently live in the following url http://gutenberg-devdoc.surge.sh/

We need to find them a nicer home.

**Comment by dmccan** [comment]
Thanks for putting this together.  The external style sheets are blocked by Privacy Badger. This is what that page looks like in Chrome: https://cl.ly/073a1n2F1H1z

**Comment by ahmadawais** [comment]
@mtias How about a separate Git Repo for docs which get hosted on GitHub pages and is CNAMED from WP.org or something?

**Comment by youknowriad** [comment]
@ahmadawais we could do the same without splitting the docs from the repo. I think code should live alongside the docs (keeps in sync, and we can use the code in the docs)

**Comment by ahmadawais** [comment]
Yes, you're right.

**Comment by karmatosed** [comment]
As the project moves towards a full vision, we are moving issues that aren't needed for that to projects. This doesn't mean they won't get done, they totally can and that's why we're moving to projects. This allows us to focus on the issues that have to happen to Gutenberg. I am closing this but it will live in projects.
