### ISSUE TITLE
Gallery block doesn't align left visually

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#2690]
This may be something we decide to have themes tackle, if we do then we need to document this.

I was testing a reported issue where galleries were merging into blocks. I wasn't able to replicate this, however I did notice there is a large difference between the visual of an aligned gallery block when it's in the editor and theme. I suggest we look to at least do something so themes can handle this better.

For example the editor:

![2017-09-07 at 09 37](https://user-images.githubusercontent.com/253067/30154167-f638051c-93b0-11e7-9f3f-e1072c6272c7.png)

Twenty Seventeen:

![2017-09-07 at 09 43](https://user-images.githubusercontent.com/253067/30154194-05dbcb7a-93b1-11e7-88c1-c0e2151c936c.png)

**Comment by gonzomir** [comment]
There are two proiblems with aligning the gallery block to the left:

1. Twenty Seventeen sets the `display: inline;` for `.alignleft` class, which overwrites the value, set by the Gutenberg CSS for the gallery. That's why the pictures are stacked in one column.

2. The gallery container element doesn't have any width set, so it can grow and take all the space, and so the next block doesn't flow around it.

You can work around these problems if you add the following CSS in the customizer:

```
.wp-block-gallery.alignleft {
  display: flex;
  max-width: 48%;
  max-width: calc(50% - .75em);
}
```

**Comment by jorgefilipecosta** [comment]
Hi @karmatosed, a PR that fixes this specific issue was merged so I think this issue may be closed.

**Comment by karmatosed** [comment]
Yes, thanks.
