### ISSUE TITLE
Gutenberg stuck in Code View (on missing nickname)

### ISSUE THREAD

**Issue by worldoptimizer** [WordPress/gutenberg#26943]
**Describe the bug**
The entire block editor default to code view with no way to enable block editing if the NICKNAME of a user is not set.

**To reproduce**
Add a user without nickname (in my case I added a user through the database after a migration/restore)
You can't use the Gutenberg editor. 

**Expected behavior**
There should be some check or fallback or notice in such a case.

**Editor version (please complete the following information):**
WP Version 5.5.3

**Desktop (please complete the following information):**
Not relevant

**Smartphone (please complete the following information):**
Not relevant

**Additional context**
https://wordpress.org/support/topic/block-editor-no-longer-working-only-shows-html/page/5/

**Comment by talldan** [comment]
> Add a user without nickname (in my case I added a user through the database after a migration/restore)

@worldoptimizer Seems a bit random, not sure why that would happen. Though nickname is a required field, so I imagine most users won't have this problem.

If the same thing happens in the classic editor, it might be something to report upstream in WordPress core (https://core.trac.wordpress.org/), as it wouldn't be caused by any of the code in this codebase.

**Comment by alexmustin** [comment]
FWIW as a developer looking for shortcuts to save time, it's very easy to setup a new WP Admin user inside of phpMyAdmin and entirely skip the Nickname field.

Please don't require this field to be used for anything crucial to site development.

**Comment by lydiaroberts** [comment]
Agree with @alexmustin. I just ran into this because I had to get into a WP site by creating a user via phpMyAdmin. Fortunately this thread came up quickly in a Google result and I was able to resolve. 

Just to add some more detail, the issue wasn't just that Gutenberg defaults to Code View, but the entire _option_ to toggle between Visual and Code View is gone from the menu, so it's not possible to toggle at all (it is truly stuck in Code View).

**Comment by talldan** [comment]
Gutenberg uses the `user_can_richedit` function from WordPress core to determine whether the visual editor is available:
https://developer.wordpress.org/reference/functions/user_can_richedit/

That's pretty basic, it seems to just check if an older browser is used. Nothing related to nicknames (it does check for a user id, but that's unrelated).

As this option can be modified by plugins, I'd recommend disabling any active plugins to see if that makes a difference.

Because this is a WordPress core issue it should be reported in core trac (a separate bug tracker). There was an issue here, but it seems it couldn't be reproduced - https://core.trac.wordpress.org/ticket/45996.
