### ISSUE TITLE
Post comments form placeholder state

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#26999]
The current placeholder for post comments is a little lacking:

![image](https://user-images.githubusercontent.com/253067/99253202-448ef100-2808-11eb-8a76-0099b0b6d53f.png)

## Problem
This block doesn't require any interactions and the output is on the front of the site. As a result, this is what shows.

## Solution
My suggestion is to show what will be output, however I understand this could feel editable as a result. In #26865  I have been exploring styling here and potentially that could be used here. Rather than having the white placeholder background that leads to interaction, perhaps a simple border and showing content works?

<img width="947" alt="2" src="https://user-images.githubusercontent.com/253067/99253824-5329d800-2809-11eb-9c6e-ba84a07e08e9.png">

My own suggestion would be to consider not even having the border, but I'm open to feedback there.

<img width="947" alt="2" src="https://user-images.githubusercontent.com/253067/99253995-9421ec80-2809-11eb-92be-9f2b60aaa737.png">

## Feedback
It would be great to get feedback on this. Is there a default way of treating blocks like this for placeholders that could be used for this one perhaps?

**Comment by jameskoster** [comment]
+1 to just displaying the form. Related: https://github.com/WordPress/gutenberg/issues/26856

**Comment by karmatosed** [comment]
Ah great, @jameskoster do you think this one should be closed to focus on that issue? Happy to do that if that one is scooping them all up.

**Comment by jameskoster** [comment]
No I think we can leave this open. I suspect that #26856 may be split up any way.

**Comment by karmatosed** [comment]
Looks like the feedback here is to display the form, so goign to move this to needs dev with that recommendation and to also not show a border.

**Comment by ockham** [comment]
We're going to try to implement a basic placeholder state as mocked up here for WP 6.0 (since we need it for #40256, among other things). See [this comment](https://github.com/WordPress/gutenberg/pull/40256#issuecomment-1099514136) for background.

**Comment by paaljoachim** [comment]
Updating the current reply comment box. I made a user named user.
From the Twenty Twenty Two theme.

### Logged in user: 
![Screenshot 2022-04-14 at 22 10 47](https://user-images.githubusercontent.com/5323259/163468127-df1e7acc-9bb0-4c08-bd3a-f8fe7d1989e8.jpg)

### Not logged in user:
![Screenshot 2022-04-14 at 22 11 40](https://user-images.githubusercontent.com/5323259/163468242-4f680934-9a6e-48e4-93d0-11030d15bc06.jpg)

### We could perhaps do something like this (simplifying even further):
-- As a version 1 iteration.
![Leave-a-Reply-comment-box](https://user-images.githubusercontent.com/5323259/163468471-768ca71e-7d10-4184-b77c-de5d0097d58a.jpg)

------

### Fully modifying the Post Comments block with inner blocks it contains.
-- As a version 2 iteration.

Circling back to the not logged in user information. So that we can customize the various fields of the Post Comments block.

"Leave a Reply" text. --> We might want to change/remove the heading to another text or another heading type.
Your email address will not be published. Required fields are marked * ---> We might want to change/remove this text.
Comment * ----> We might want to change Comment text and * to something else.
Name ---> Change text.
Email ---> Change text.
Website ---> Change text, or remove.
-checkbox- Save my name, email, and website in this browser for the next time I comment. ---> Change text or remove.

This means we will need to use the full not logged in user information as a parent block with inner blocks that can be modified.
