### ISSUE TITLE
Gutenberg whitescreens if you register a block with a syntax error

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/gutenberg#2701]
## Issue Overview
If you register a block with a syntax error, the entire editor doesn't appear and in Chrome, the page loader keeps spinning and spinning, eating more and more CPU. 

## Steps to Reproduce (for bugs)
1.  Forget your commas
2. Lose your editor

## Expected Behavior
The block doesn't register, but the editor is still usable.

**Comment by youknowriad** [comment]
these two problems might be unrelated, we discovered some infinite loops problems and hopefully fixed with #2688 

can you try with master?
what's the block shape you're trying to register?

**Comment by aaronjorbin** [comment]
@youknowriad I just pulled and it is in fact completely fixed. Thanks.  

FWIW, I discovered this by having the object that was passed as the second argument to `blocks.registerBlockType` have a missing comma. 

Think it might be worth having a test to make sure Gutenberg still renders ok even if there is a syntax error in a plugin?

**Comment by mtias** [comment]
The block boundary error handling should be covering this. cc @aduth

**Comment by aduth** [comment]
The block boundary error handling accounts for errors which occur while rendering the block (its `edit` implementation):

https://github.com/WordPress/gutenberg/blob/a116256c1b3b623d645a17f900946cb1dee4ae3f/editor/modes/visual-editor/block.js#L383-L411

Further error handling for `save` implementation is handled in the serializer:

https://github.com/WordPress/gutenberg/blob/a116256c1b3b623d645a17f900946cb1dee4ae3f/blocks/api/serializer.js#L156-L163

Global application _rendering_ error handling is proposed in #3208

It's important to differentiate render errors from general runtime errors. Block boundaries aren't capturing the sorts of issues described in the original comment because it doesn't occur as part of the render (we can't render a block if we don't know that it's registered, and it's the registration itself causing the error).

Currently we assume a plugin will register its block type immediately on its own script load; it is not my expectation that a plugin loading a script with a syntax error should crash the application, and in my testing it does not. It _does_ crash the application if the block is implemented within Gutenberg itself, because the syntax error causes a failed build through Webpack / Babel.
