### ISSUE TITLE
Image disappears when trying to crop

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#27145]
**Describe the bug**
While testing #27105 I found that when trying to crop an aligned image the image would disappear.

**To reproduce**
- in a new post
- add an image
- set its alignment to right
- select the image
- press crop in the toolbar
- notice the bug

**Expected behavior**
The image should not disappear.

**Screenshots**

![align-crop](https://user-images.githubusercontent.com/107534/99809260-b2aa1f80-2b4a-11eb-8da4-960d1d72b149.gif)

**Comment by stokesman** [comment]
I can confirm what I believe is the same bug except the image isn't disappearing but instead it shrinking drastically.
<details>
<summary>Screen recording of the issue on center aligned images</summary>
<img src="https://user-images.githubusercontent.com/9000376/100474201-f34af100-3094-11eb-8382-b4ae1e04e99e.gif"/>
</details>

It does also happen on left or right aligned images.

While trying to figure this out, I gave reverting 1fbe105 a try and that worked to resolve this. Because #26376 was backported to WP 5.6 I'm pinging @tellthemachines and @talldan to see if they can test if this issue is occurring there. If it is, then please proceed to testing if #27320 is a proper fix🤞

**Comment by tellthemachines** [comment]
I can reproduce this issue in 5.5.3. Given that it's not a 5.6 regression, it's not eligible to be included during RC stage.

**Comment by draganescu** [comment]
@stokesman I added an alternative PR  #27687 that does not change the CSS but instead uses clientWidth as the width of the cropper when 100% means zero px. I am unsure if this is a better fix, but it seems to be making a sort of defensive implementation in case more CSS results in 100% being zero px in the future.

**Comment by stokesman** [comment]
Nice one Andrei, I'd taken a quick look toward that approach but didn't quickly find where to implement it. Seems the better way to me.

**Comment by draganescu** [comment]
@stokesman I merged #27687 let's see if anything new pops up. I think #27320 can be closed?

**Comment by stokesman** [comment]
Thanks for the reminder Andrei
