### ISSUE TITLE
Improve Link Entry

### ISSUE THREAD

**Issue by annaephox** [WordPress/gutenberg#2715]
Dialog style input fields open in layers in Gutenberg right now, resulting in visual clutter. Examples of this issue are raised in #2628 and #2204 

For example, when we **insert a Button Block**, we see this:
![wordpress - layering 001](https://user-images.githubusercontent.com/25762760/30259758-7838564a-9706-11e7-94fc-abd0c30024be.jpeg)

Breaking this down, there are 4 elements competing for our attention (numbers 1-4). These elements have a hierarchy in terms of their priority: for example, if the user has inserted a Button Block, they would be most interested in adding a URL and Label for the button first, before tackling alignment, block settings or adding new blocks. Out of the four elements, the link insert has the highest priority:

![wordpress - layering 002](https://user-images.githubusercontent.com/25762760/30259827-dc7a27f0-9706-11e7-9cca-0210770ab9c5.jpeg)

We can improve the design to facilitate this.

**Proposed solution: Serialised dialog**
Last year, we developed and user tested a "serialised dialog", which has now been rolled into TinyMCE mobile ([wireframes here](https://invis.io/E7DF1AB62#/252659977_IMG_9737)). In this example, the main toolbar is replaced with a serialised version of the "dialog". The fields in the dialog are ordered by priority, allowing the user to complete the action at any time (without necessarily scrolling through all the input fields). 

We could apply this same concept to input fields/dialogs in Gutenberg: i.e. **when a selection is made that needs extra input (e.g. link), the main block toolbar is replaced by a serialised dialog**. For the button block, this would look something like this

![wordpress - layering 003](https://user-images.githubusercontent.com/25762760/30259943-a2eba7ec-9707-11e7-9eaf-e6198c955ff2.jpeg)

Thoughts? Improvements?

/cc @karmatosed @melchoyce @mtias

**Comment by tg-ephox** [comment]
@karmatosed @melchoyce @mtias this is about 90% complete, just need to tweak some styles really...  Thoughts?

![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/30682649/30628759-b321056a-9e1b-11e7-8bbb-d8edccba07b4.gif)

**Comment by mtias** [comment]
@annaephox @tg-ephox I like the direction, but can you look at the link implementation for the image block? It already does the "display in toolbar" and it should be aligned design wise.

**Comment by karmatosed** [comment]
I also agree that unifying the design would be good. It's not something we want varying.

**Comment by annaephox** [comment]
Yes, agreed 
@tg-ephox has been working on making all of the link insert experiences consistent, so button, regular text block, image, hero image, etc
We'll add some videos in here shortly - the fixes are all in #2779

**Comment by annaephox** [comment]
Changes made in #2779 shown below (thanks @tg-ephox): we focussed on making the link insert experience consistent across all the blocks @melchoyce @karmatosed would be great to get your eyes over this quickly and see if it looks OK. Thx

**Video showing link dialog animating into position over the toolbar**

![button-link](https://user-images.githubusercontent.com/25762760/31374094-ea36796c-addf-11e7-9e44-93727b769bee.gif)


**Block by block** 

![wordpress-links issue 2715 001](https://user-images.githubusercontent.com/25762760/31373818-d786c5de-adde-11e7-98fb-2efe953d6fb8.jpeg)
![wordpress-links issue 2715 002](https://user-images.githubusercontent.com/25762760/31373819-d7b99f54-adde-11e7-8c67-00183f669133.jpeg)
![wordpress-links issue 2715 003](https://user-images.githubusercontent.com/25762760/31373820-d7ed2b44-adde-11e7-8e7f-9b0196bceedd.jpeg)
![wordpress-links issue 2715 004](https://user-images.githubusercontent.com/25762760/31373823-d821a6a8-adde-11e7-9189-23e006243ce1.jpeg)

**Comment by karmatosed** [comment]
Seeing this as a prototype there are a few issues that strike me. The flow feels super weird after a certain point. There's a lot of points likely to confuse users. I think it's a combination of things. The merging hasn't quite gone as hoped of the existing link we have in and these iterations. However, that happens sometimes and we have to iterate, sometimes taking a step back from what is produced.

Let's walk through the flow and I'll discuss as I go.

![1](https://user-images.githubusercontent.com/253067/31409868-3d893120-ae05-11e7-975d-aa92d0a1aae3.png)

This first bit feels natural. It works. It makes sense having a limited UI at this point.

![2](https://user-images.githubusercontent.com/253067/31409875-455f02f8-ae05-11e7-936c-3f0a37f56b94.png)

We seem to be missing validation at this point, which was a good thing to have. The loader is really badly positioned also.

At this point the visual becomes confused and the flow feels disjointed and confusing.

![3](https://user-images.githubusercontent.com/253067/31409955-8557d2f4-ae05-11e7-862f-a81182c17ab0.png)

Here is where we have a mystery meat danger going on. I don't know why but the toggle worked a whole lot better outside of this implementation.

![4](https://user-images.githubusercontent.com/253067/31409998-a0dc8542-ae05-11e7-9f2c-c9d37246899b.png)

The arrow here enforced the lost feeling. The hover saying submit is weird and then seeing the arrow.. I feel very confused here.

It's a bit weird because whilst cluttered.. this feels better:

![5](https://user-images.githubusercontent.com/253067/31411203-c7596336-ae08-11e7-88e8-71237409ad4b.png)

I think we can work through this though, so let's do that.

I feel user testing both versions would be good to see what different feedback we get. However, I think there are some iterations needed before we get there.

**Comment by annaephox** [comment]
Hey @karmatosed : the code for the above has been written (#2779), so perhaps we can merge and then user test?
I agree with you that some of the fields (e.g. open in new window, and the last one with the tick) are awkward. We left these fields exactly as they are per current link entry dialogs, so as not too change up too much at once
Can I suggest that we first see whether this general approach sticks, and then refine the fields and chrome on the link entry element?

**Comment by karmatosed** [comment]
@annaephox I am not happy merging in it's current state, no.

**Comment by annaephox** [comment]
@karmatosed : no problem
Can we get some guidance as to what you would like to see changed?

**Comment by mtias** [comment]
Thanks for the iterations here. With the UI changes in the last couple releases, plus https://github.com/WordPress/gutenberg/issues/3283 I think this issues can be considered resolved.
