### ISSUE TITLE
Grey gap at bottom of screen when scrolling

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#27157]
Currently when you scroll the following is seen - using Firefox:

![2020-11-20 15 12 40](https://user-images.githubusercontent.com/253067/99817150-796eb100-2b44-11eb-92c6-5c5ede3ae9ef.gif)

This looks like it's not happening until the following [PR](https://github.com/WordPress/gutenberg/pull/26944). 

The solution is to not have the gap, I will investigate this in a PR, but posting as it's existing issue and initially didn't fix by doing a simple revert on my install so creating this issue for deeper investigation.

Props @jasmussen for noting this.

**Comment by tellthemachines** [comment]
I don't think this was caused by #26944, because that one was backported to 5.6 and this issue isn't happening on 5.6 RC1. 

I supect the culprit to be #27035, particularly [this line](https://github.com/WordPress/gutenberg/blob/master/packages/edit-post/src/components/visual-editor/style.scss#L31) that applies `height: 100%` to `block-editor-writing-flow__click-redirect` (if the height is applied only to `editor-styles-wrapper` the issue disappears).

**Comment by jasmussen** [comment]
Created a fix in #27187.

**Comment by karmatosed** [comment]
Ah @tellthemachines the backporting makes sense why I was having issue tracking this down, thank you so much for context there.
