### ISSUE TITLE
Place holder icons disappear in a dark theme for Social Links

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#27176]
**Describe the bug**
Using the Social Links block on a dark background makes the placeholder icons disappear in the background. It's hard to figure out what one needs to do. 

1. User Twenty-Twenty-one as theme
2. set background color to a dark color. I used #303030
3. Add a new post
4. Use Social Link block

**Expected behavior**
I expected the placeholder icons to display in clear colors 

**Screenshots**
![Screen Shot 2020-11-21 at 11 01 39 AM](https://user-images.githubusercontent.com/39980/99888806-68de3980-2c1d-11eb-8dd5-65b23a1868f0.png)

**Editor version (please complete the following information):**
- WordPress version: WordPress 5.6-RC1-49667
- Gutenberg [Nightly](https://gutenbergtimes.com/need-a-zip-from-master/#nightly) Version 9.4.1.202011121 

**Desktop (please complete the following information):**
 - OS: 10.15.7
 - Browser Chrome
 - Version: Version 86.0.4240.198

**Comment by jasmussen** [comment]
Good ticket, thank you.

The placeholder icons are there to indicate that you have an empty social links block that you should consider filling out. When that block is then selected, we fade those placeholders out to make it clear you have to click the plus to get going.

In a previous version, the placeholder was more opaque, and this actually caused confusion, with people thinking they could click those blobs, rather than the plus to add. So we intentionally made it very light.

However it's barely visible, I can see that. I tried my hand with #28838 to improve things. 

But if that doesn't improve things, we might want to remove the placeholder entirely on select. What do you think?
