### ISSUE TITLE
Retain text color when pasting from one block to another.

### ISSUE THREAD

**Issue by jerrysarcastic** [WordPress/gutenberg#27212]
**Describe the bug**
When copying/pasting text from one block to another, most formatting (bold, italic, etc) is retained but any custom color setting the text has is lost.

**To reproduce**
1. Open Gutenberg editor and add sample text.  Format the text to give it a custom color
2. Copy that text and paste it into the same block or a new block
3. Text loses it's color formatting as it is pasted in (other formatting is retained)

**Expected behavior**
Expected color formatting to be retained since it it is formatted in Gutenberg already.

**Screenshots**
![Markup 2020-11-23 at 10 54 24](https://user-images.githubusercontent.com/1967448/100014339-50cffc80-2d7a-11eb-8824-7e8e21345202.png)

Also a video showing the issue here:  https://d.pr/v/jibHwB

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.5.3]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Issue is can be replicated both with and without the Gutenberg plugin installed

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.4
 - Browser Chrome
 - Version Version 86.0.4240.198 (Official Build) (x86_64)

**Comment by ellatrix** [comment]
> When copying/pasting text **from one block to another**, most formatting (bold, italic, etc) is retained but any custom color setting the text has is lost.

This has been fixed by #27967.

**Comment by k-boikov** [comment]
Hi, I think that fix/improvement has suffered a regression in https://github.com/WordPress/gutenberg/pull/30197 
Tested the way the original author reported and in 10.2 it works (it preserves the colors) but that introduced the bug copying multiple blocks copies only the first one. That is fine after updating to 10.3.2 (copying multiple blocks works as expected) but the colors are no longer preserved as introduced in 10.2. Updating to 11.2.1 does not change anything (colors are still not preserved).
WordPress version 5.7.2

Edit: the bug is actually only reproducible on Linux, it has never worked there. Upon further debugging I found out that clipboardData.getData( 'rich-text' ) was always empty. I tried to set it as 'application/json', but that arrives empty on paste too. 
Ubuntu 20.04.2 LTS
Chrome 91.0.4472.77
