### ISSUE TITLE
Use pptr-testing-library in e2e tests

### ISSUE THREAD

**Issue by kevin940726** [WordPress/gutenberg#27260]
**Is your feature request related to a problem? Please describe.**
As already mentioned in #7974. We have quite a few tests using selectors of class names. For instance, a test in `adding-blocks`:

https://github.com/WordPress/gutenberg/blob/5c530b2a9de44381c9add6ad23967fcd36042bc7/packages/e2e-tests/specs/editor/various/adding-blocks.test.js#L122-L128

As summarized by @gziolo there at https://github.com/WordPress/gutenberg/issues/7974#issuecomment-485870717, we should be using selectors that simulate the way users use the app. While `aria-label` selectors are considered okay, class names selectors certainly are not. It's even being pointed out in our [doc](https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/backward-compatibility/README.md#class-names-and-dom-updates) that class names shouldn't be considered public APIs.

**Describe the solution you'd like**
Use [`pptr-testing-library`](https://github.com/testing-library/pptr-testing-library) in our e2e tests.

It should look something like this:

```js
import { getDocument, queries } from 'pptr-testing-library';

const { getByRole } = queries;

it( 'test', async () => {
	const document = await getDocument( page );

	const searchBox = await getByRole( document, 'searchbox', {
		name: 'Search for a block',
	} );
} );
```

**Pros**
- By enforcing to use only accessible selectors, we are now more confident that our app is accessible to screen readers.
- The queries are a lot like the ones we've been using in RTL already, so the learning curve should be relatively low.

We could also go a step further and consider wrapping `pptr-testing-library` in `e2e-test-utils` package and expose utilities/queries from there. We could potentially get less boilerplate and provide more functionality to our specific use cases.

```js
import { screen } from '@wordpress/e2e-test-utils';

it( 'test', async () => {
	// Shortcut to `queries.getByRole.bind( null, await getDocument( page ) )`
	const searchBox = await screen.getByRole( 'searchbox', {
		name: 'Search for a block',
	} );

	// We can even inject our own custom matchers that map to `@testing-library/jest-dom`
	await expect( searchBox ).toHaveFocus();
} );
```

**Describe alternatives you've considered**
Leave it as is. There aren't many problems in the past anyway.

However, I think it's still useful for new tests to follow the best practices.

**Comment by gziolo** [comment]
> By enforcing to use only accessible selectors, we are now more confident that our app is accessible to screen readers.

It's more complex than that but it surely is very important to maximize the chances that code is accessible in as many ways as possible.

Once you get familiar with `pptr-testing-library` then it seems very useful. We already have quite a few utils that hide all the implementation detail but obviously, there is room for improvement. I'm personally not familiar `pptr-testing-library`. In theory, it should be fine to have it as it most likely uses a similar API to `react-testing-library`. In practice, it's often a different group of people who writes both unit and e2e tests so it might turn out that contributors will end up using what Puppeteer API offers. I'm not against this proposal, if people feel strongly about having it, we can enable it. I only hope that it's actively maintained because we had many issues with `enzyme` in the past because it was always behind React updates. In effect, we were forced several times to rewrite a big number of unit tests to make them work when React was adding new APIs. Eventually, we discourage the usage of `enzyme`.

**Comment by kevin940726** [comment]
@gziolo 

> It's more complex than that but it surely is very important to maximize the chances that code is accessible in as many ways as possible.

Sure, that's why I use _more_ there instead of fully confident 😉 .

> I only hope that it's actively maintained because we had many issues with enzyme in the past because it was always behind React updates.

Judging from the source code of `pptr-testing-library`, seems like what it does is simply injecting the `dom-testing-library` source code into puppeteer's `page`. Since that `dom-testing-library` is a framework-agnostic library, I think we don't have to worry about outdated issues too much. Other parts are just using the public APIs of puppeteer, so it should be actively maintained too. Even if it did become outdated, we can always contribute to it. Given that it's not a huge library like `enzyme`, I believe the maintanence effort (if any) should be minimal.

**Comment by mcsf** [comment]
I'd like to comment on this premise:

> While `aria-label` selectors are considered okay, class names selectors certainly are not. It's even being pointed out in our [doc](https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/backward-compatibility/README.md#class-names-and-dom-updates) that class names shouldn't be considered public APIs.

Indeed, classes are a private interface, and labels are better targets than classes. But I don't see this as a reason to completely dismiss classes as a viable target in E2E tests, _if no better alternatives are present_. I say this because all tests are run for every pull request in the project, which gives us some confidence that PR authors will patch failing tests if they depend on changing classes.

Going back to the general issue, though, I think we already have the necessary tools to target page elements as detailed by Robert in https://github.com/WordPress/gutenberg/issues/7974#issuecomment-525984222. It might be more fruitful to work on encouraging or enforcing this practice through linting.

I don't feel very strongly about this topic, although my personal inclination is that the change is unnecessary. Also, the parent issue was closed not too long ago.

**Comment by kevin940726** [comment]
>  I don't see this as a reason to completely dismiss classes as a viable target in E2E tests, if no better alternatives are present.

**Comment by noisysocks** [comment]
I'm not very familiar with `pptr-testing-library` or `@testing-library/dom`, but, at a glance, it looks like this might solve one big gripe that I have with our use of Puppeteer which is that it makes it too easy to write an unstable E2E test that fails when a selector is missing.

That is, I keep thinking that we really ought to **always** use `waitForSelector` or `waitForXPath` when we select an element. This is because so many of our test failures are because an element isn't yet on the screen. The most common one I see is that it takes one frame for a popover to appear. It costs barely anything to wait for a selector—we should just always do it.

Again, I haven't looked into `pptr-testing-library`, but it looks like this gripe of mine would be addressed if we encourage using the `find*` methods.

**Comment by talldan** [comment]
> That is, I keep thinking that we really ought to always use waitForSelector or waitForXPath when we select an element. This is because so many of our test failures are because an element isn't yet on the screen. The most common one I see is that it takes one frame for a popover to appear. It costs barely anything to wait for a selector—we should just always do it.

Absolutely! I think writing more assertions in tests would be nice too. A frustration I have with puppeteer is that it often carries on when an action fails (like it misses a click on an element), so I think asserting that an action has a consequence more regularly would lead to more understandable failures in tests.

When it comes to `ppter-testing-library` it definitely looks compelling. At the same time I think it'd be good to look at some of the tests to see why we're using class name selectors, because I don't really have a clear understanding. Maybe because it's easier? Or maybe to avoid ambiguity? Or to select elements that don't have visible text?

I think we could at least take inspiration from it. In hindsight, looking at our e2e-test-utils, I think we could consider taking more advantage of puppeteer's `elementHandles`. Functions should probably return or take elementHandles:

An example is that we have utilities like:
```js
await clickButton( text );
```

But perhaps (and synonymous with how pptr-testing-library works) we should be doing:
```js
const button = await getButton( text );
await button.click();
```

Because then you can do something else with the `elementHandle`, like:
```js
const isButtonDisabled = await isDisabled( button );
expect( isButtonDisabled ).toBe( false );
```

Or you can use the elementHandle as the parent for another element query (which pptr-testing-library does as well).

**Comment by kevin940726** [comment]
I can go ahead and create a draft PR to convert some of our tests to use `pptr-testing-library` (maybe `adding-blocks`? Some other better ideas?), so that it's easier to see the before & after.

**Comment by kevin940726** [comment]
Now that we're using Playwright and its built-in [role selectors](https://playwright.dev/docs/selectors#role-selector), I think this can now be closed.
