### ISSUE TITLE
is-hovered css class application quirks

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#27296]
Whilst working on https://github.com/WordPress/gutenberg/pull/27271 I noticed a couple of strange instances where the `is-hovered` class it not correctly applied. The first one is block placeholders, please observe:

![hovered](https://user-images.githubusercontent.com/846565/100343557-69891e00-2fd7-11eb-8b1b-89d8326c0098.gif)

I added a red outline to highlight the elements that seem to block the class being added. Interestingly, hovering the elements _inside_ those elements does _not_ seem to block the class being added.

A similar thing happens with link blocks in the navigation block:

![hovered-2](https://user-images.githubusercontent.com/846565/100349002-af49e480-2fdf-11eb-8288-11b11270d28d.gif)

cc @jasmussen

**Comment by jasmussen** [comment]
Excellent GIF usage. Definitely helpful for debugging.

**Comment by jeyip** [comment]
After doing some digging:

- `useBlockProps` implements the `useIsHovered` hook [here](https://github.com/WordPress/gutenberg/blob/b17dbfc935522f7c3c7f2bc0e6b2e991cdb0b687/packages/block-editor/src/components/block-list/use-block-props/index.js#L126) and [here](https://github.com/WordPress/gutenberg/blob/b17dbfc935522f7c3c7f2bc0e6b2e991cdb0b687/packages/block-editor/src/components/block-list/use-block-props/index.js#L106)
- `useIsHovered` [adds event listeners](https://github.com/WordPress/gutenberg/blob/b17dbfc935522f7c3c7f2bc0e6b2e991cdb0b687/packages/block-editor/src/components/block-list/use-block-props/use-is-hovered.js#L48-L54) that fire on `mouseover` and `mouseout`
-  the issue we're seeing can be characterized [by this blurb:](https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseleave_event)

<img width="1058" alt="Screen Shot 2021-02-03 at 6 09 11 PM" src="https://user-images.githubusercontent.com/5414230/106834820-f3dea580-664a-11eb-8782-132595895a1b.png">

Using the navigation link as an example, when we hover over text, even though it's clearly a child of the navigation link `<li>` tag, `mouseout` is still triggered. This is because, even though the pointer is still within the `<li>` tag, has is now "out", `mouseout` behavior dictates that it should still be fired when entering a descendant.
