### ISSUE TITLE
The 'Use theme styles' toggle only works inconsistently

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#27318]
**Describe the bug**
The 'Use theme styles' toggle no longer seems to work. Unchecking it has no effect.

**To reproduce**
1. Using a theme with editor styles, open the editor, optionally add some content
2. In Preferences > Settings toggle the 'Use theme styles' option and close the panel
3. Theme styles are still shown
4. Toggle it again
5. Theme style are still shown

**Expected behavior**
When unchecking the option, theme styles are not shown. Rechecking it shows the styles again.

**Editor version (please complete the following information):**
- WordPress 5.6 RC1
- Gutenberg 9.4.1

**Comment by talldan** [comment]
This seems inconsistent, it just started working again. 🤷‍♂️

**Comment by noisysocks** [comment]
When I first tested this I was able to reproduce the issue but then I refreshed the page and now everything works. Might have something to do with migrating the setting?

**Comment by talldan** [comment]
I haven't experienced this for a while. Will close, but can always reopen if the issue returns.

**Comment by fschtn** [comment]
I have this exact problem right now.. Any updates? Still "fixed"?

**Comment by ayyilmaz** [comment]
The problem has continue. I use Herald Theme and When I go to editor I cant use nicely because it makes font size smaller than normal. It effects paragraphs. Itry to change font size of `.editor-styles-wrapper` class from customizing section but it does not effect. It creates new css command like this: 

```
html :where(.editor-styles-wrapper) p {
    font-size: revert;
    line-height: revert;
    margin: revert;
}
```

Problem has been continuing and I think issue should not be closed.
