### ISSUE TITLE
Global Styles: Add a way to set defaults for all styles

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#27338]
If I declare support for a global style in a block I'd also like to be able to set a default value for that block. For example I could set default values for padding in the block attributes like this:

```
		"spacing": {
			"type": "object",
			"default": {
				"padding": {
					"type": "number",
					"default": 10
				}
			}
		},
```

I think this is already supported by some properties but either this one doesn't work, or I'm doing it wrong!

**Comment by scruffian** [comment]
This is achievable now, the syntax is like this: 

`"style": { "default": { "spacing": { "padding": { "default": 10 } } } }`

It might be good to document this

**Comment by scruffian** [comment]
There also seem to be two bugs with this:
1. If you set a default value it's not reflected in the block - is it expected that this is set in CSS?
2. If you reset the control it wipes the value rather than going back to the default.

**Comment by nosolosw** [comment]
I think I may benefit from some more context on the specifics you're working with! Is this something you do with `theme.json` (presumably not because I don't know how you'd do it), or are you working with a block and so trying to create its block.json ([block supports docs](https://developer.wordpress.org/block-editor/developers/block-api/block-supports/), in case they're helpful)? If it is the latter, you can add defaults (there's an example about padding in the docs).

**Comment by scruffian** [comment]
Ah yes, that's what I'm doing. Sorry I hadn't seen the docs. I think the bugs I mentioned above are still relevant though.

**Comment by nosolosw** [comment]
@scruffian I found https://github.com/WordPress/gutenberg/pull/27341 which I believe is what prompted you to file this issue?

I left a few comments there, but, essentially instead of `default` you need to use `top`, `right`, `bottom`, `left` ― see the documentation for [padding](https://developer.wordpress.org/block-editor/developers/block-api/block-supports/#spacing). As per the control, I believe it works as designed (remove any style value).

**Comment by gziolo** [comment]
Would be it fine to define this default value inside `supports` rather than passing `true`? It’d more convenient for developers.

**Comment by scruffian** [comment]
Closing in favour of https://github.com/WordPress/gutenberg/issues/27796
