### ISSUE TITLE
Expose breakpoint-values.js from @wordpress/components to be used in CSS-in-JS

### ISSUE THREAD

**Issue by ecgan** [WordPress/gutenberg#27340]
**Is your feature request related to a problem? Please describe.**

I would like to use CSS-in-JS libraries (e.g. [Emotion library](https://emotion.sh/docs/introduction)) and would like to use the breakpoint values in my project.

https://github.com/WordPress/gutenberg/blob/33d036649918092329ec9a481764897e0c9a44a9/packages/components/src/utils/breakpoint-values.js#L1-L10

**Describe the solution you'd like**

Expose it so that I can use it from @wordpress/components npm package.

**Describe alternatives you've considered**

Currently I have to copy and paste the values into my project, which is not ideal.

**Comment by jordesign** [comment]
Hey @ecgan  - just looking back through some older issues and wanted to see if this is still a relevant enahancement request for you?

**Comment by ecgan** [comment]
Hi @jordesign , currently the things I'm working on are not related or dependent on this enhancement request. Do you know if this issue has been fixed, i.e. is there a way for plugin developers to access those breakpoint values?

**Comment by jordesign** [comment]
I'm not aware of changes there specifically - but in regard to this issue being related to CSS in JS libraries - there is likely much that has changed in the ~3 years since the original report.

I'll close this for now - and if it proves to be an issue in the future, a new issue can be opened with updated details.
