### ISSUE TITLE
Flow for editing the styles of a specific block type

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#27393]
In the global styles context, it should be possible to go from block to editing that block's global styles properties. Maybe a first start could be adding an action to the ellipsis menu "Edit Global Styles":

![image](https://user-images.githubusercontent.com/548849/100729672-599f7e80-33c9-11eb-81dc-96fa85bf7ec0.png)

**Comment by jorgefilipecosta** [comment]
An additional possibility discussed in a conversation with @mtias was a design tool/ block global styles select tool

The tool can be a top-level button on the toolbar, when we press the button we activate a block select mode. When we click on a block we automatically open the global styles panel for that block.

This tool is implemented in addition to the system referred to on this issue.

**Comment by jasmussen** [comment]
This seems related to "push styles to global", and it would be good to consolidate. A use case, I'm writing a post on my brand new blog and using a Quote block for the first time, and realizing it looks poor. I might want to style it locally there, then push it to global. While this is possible with "push to global", it can be refined with a modal before/after preview. It can perhaps take inspiration from how you update components in Figma.

**Comment by jameskoster** [comment]
Since it's possible to apply a block styles globally now we might consider this issue complete. 

But that flow could use some improvements. For example:

* Displaying a before/after preview & diff, either in a modal or the multi-entity save panel. 
* The shortcut suggested in the OP could open the global styles panel with the style book focussed on the selected block
* Consider granularity of pushable changes in the local context. Currently you can only push _all_ local changes, there might be an argument for a more selective experience.

**Comment by annezazu** [comment]
Closing this out considering the above discussion and the fact that "Apply globally" is an option under advanced. For improving this, let's open up individual issues going forward like so https://github.com/WordPress/gutenberg/issues/57740 and potentially consolidate with an iteration issue if we want to see something ship in a future release.
