### ISSUE TITLE
Regression: Metaboxes and sidebar are partially hidden by .interface-interface-skeleton__footer element

### ISSUE THREAD

**Issue by sabernhardt** [WordPress/gutenberg#27456]
**Original report by elliotcondon**
https://core.trac.wordpress.org/ticket/51920

**Describe the bug**
When editing a post that contains metaboxes, the element `div.interface-interface-skeleton__footer` is absolutely positioned over the top of the metabox area and the sidebar.

**To reproduce**
Steps to notice overlap of content section with metaboxes:
1. Have or install/activate an SEO plugin or another kind that adds metaboxes at the bottom of the content area.
2. Use a laptop/desktop size screen at 100% zoom.
3. Scroll to the bottom of the content area.

Steps to notice overlap of content section with sidebar:
1. Show Document panel.
2. If scrollbar does not appear, expand sections until it does.
3. Scroll to the bottom of the sidebar.

**Expected behavior**
Footer would not overlap other elements.

**Screenshots**
Both metaboxes and sidebar overlapped by footer on laptop screen:
![metaboxes and sidebar covered by footer](https://user-images.githubusercontent.com/17100257/100978909-a76ed080-3508-11eb-8bc6-7c6caf8414bf.png)

Metaboxes covered at the bottom of a larger screen:
![larger screenshot](https://core.trac.wordpress.org/raw-attachment/ticket/51920/Screen%20Shot%202020-12-01%20at%201.30.59%20pm.png)

**Editor version:**
- WordPress version: 5.6-RC2-49734, without the Gutenberg plugin

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox 83

**Comment by sabernhardt** [comment]
The footer was switched from fixed positioning to absolute in PR #26944, but switching that back to fixed does not seem to help.

**Comment by sabernhardt** [comment]
I think I'm done fixing the title and first comment on this report now. (:facepalm:)

**Comment by sabernhardt** [comment]
For comparison, this is how it was in WordPress 5.5.3:

![footer is below metaboxes and sidebar](https://user-images.githubusercontent.com/17100257/100981911-0a626680-350d-11eb-9630-d0f643262ffe.png)

**Comment by elliotcondon** [comment]
Update: Looks like this issue is not only scoped to metaboxes. The `.interface-interface-skeleton__footer` element will also interfere with the block editor sidebar.

![Screenshot_2020-12-04 Edit Post ‹ WordPress 5 6 — WordPress](https://user-images.githubusercontent.com/2296425/101120628-06823180-363e-11eb-95bb-c4669aad3e74.png)

**Comment by talldan** [comment]
This was fixed by https://github.com/WordPress/gutenberg/pull/26432 in the plugin, but was merged too late for 5.6 and was missed for backporting during beta/RC.

As mentioned on the trac ticket, the best option now seems to be to get this into 5.6.1 whenever that may be—I've labelled the PR as such.

Closing this issue given it's fixed, but I'll comment on the trac ticket that a backport is needed for that PR as well.
