### ISSUE TITLE
Improve the Global Styles Sidebar Design

### ISSUE THREAD

**Issue by jorgefilipecosta** [WordPress/gutenberg#27473]
As an improvement to the current global styles sidebar, @mtias suggested a good possibility would be implementing the following prototype, given that it is better than what we have now implemented in the repository:
https://g2-components.xyz/iframe.html?id=examples-wip-globalstylessidebar--default&viewMode=story#
![image](https://user-images.githubusercontent.com/11271197/101058752-636de100-3585-11eb-9bf1-f7b9a6eb2db7.png)

So let us prioritize implementing this design.

This design can, of course, be iterated on.

The implementation of this design involves enhancing our components/bring some components/concepts from the G2 repository.

cc: @jasmussen,@jameskoster, @kellychoffman, @shaunandrews @youknowriad, @nosolosw, @ItsJonQ, @aristath, @mcsf

Related: https://github.com/WordPress/gutenberg/issues/27331

**Comment by jasmussen** [comment]
> This design can, of course, be iterated on.

Important emphasis, we probably will. I think we need a better subheading style. But this is a big improvement over what's there, so blaze a trail!

**Comment by aristath** [comment]
I like that it cleans up and organizes things, but it reminds me a lot of the customizer :thinking: 
I'm adding the accessibility tag here because AFAIR there are a lot of issues with that pattern and the a11y team has mentioned repeatedly that it should not be done. CC @joedolson @enriquesanchez 

I agree we should find a way to organize things visually, but this time if possible I'd like us to take a11y into account from the beginning :smiley:

**Comment by jameskoster** [comment]
The pattern was discussed fairly recently in #accessibility. Quoting @sarahricker:

> Correct, I think we should let the team proposing that proof out their proposal, rather than dismiss it outright. It will be a challenge for sure, but there are probably a few other ways to augment the design that might help us reach a middle ground. 

> I’m  also seeing a lot of content around the web re: making accessible side bars and slide out navs: https://knowbility.org/blog/2020/accessible-slide-menus/ I think those things should be reviewed and considered, as this is a very modern design element that many apps are moving to.

https://wordpress.slack.com/archives/C02RP4X03/p1602258922112800

**Comment by aristath** [comment]
Thank you @jameskoster :heart:

**Comment by mariohamann** [comment]
As far as I understand, this should switch between the different heading-styles?

![image](https://user-images.githubusercontent.com/26542182/101159858-5bb64700-362e-11eb-9d11-c571bc3ba19a.jpeg)

In my opinion, this would definetely need a more Tab-like-Style or should be wrapped in accordions, too.

![Screen Recording 2020-12-04 at 12 49 34](https://user-images.githubusercontent.com/26542182/101160459-59a0b800-362f-11eb-8dd5-f390c67276c5.gif)

**Comment by mtias** [comment]
The contents of the panels (Colors, Typography, Spacing) are not that important for this issue, which focuses more on the grouping and presentation of global and per-block styles. For the components and rendering of the individual tools, see #27331.

**Comment by joedolson** [comment]
Can you tell me how I would find the global styles sidebar to make a comparison between the two? I'm not sure what this is, exactly.

**Comment by ItsJonQ** [comment]
For context, the current Global Styles design looks like this:

<img width="1375" alt="Screen Shot 2020-12-08 at 5 29 05 PM" src="https://user-images.githubusercontent.com/2322354/101549001-e5417e00-397a-11eb-801c-23d2ae66925f.png">
<img width="1379" alt="Screen Shot 2020-12-08 at 5 28 56 PM" src="https://user-images.githubusercontent.com/2322354/101549002-e5da1480-397a-11eb-8b8e-dabccde7e5f9.png">
<img width="1377" alt="Screen Shot 2020-12-08 at 5 28 51 PM" src="https://user-images.githubusercontent.com/2322354/101549003-e5da1480-397a-11eb-9972-5d6b0f826f06.png">

Here's a quick video screencast showing the experience:
https://d.pr/v/MJ12zo

(Loaded with the [Q theme](https://wordpress.org/themes/q/) by @aristath )

---

### Instructions for viewing Global Styles

* Make sure you're on the latest `master`
* Load a FSE enabled theme
* In my case, I downloaded and activated the [Q theme](https://wordpress.org/themes/q/)
* On the left nav in WP Admin, there should be a new item labeled "Site Editor"
* Click "Site Editor", which takes you to the Site Editor, where you'll see global styles on the right

**Comment by jorgefilipecosta** [comment]
Hi @alexstine,
Thank you for entering this conversation and raising important questions.


Regarding https://g2-components.xyz/iframe.html?id=examples-wip-globalstylessidebar--default&viewMode=story, the link is for a storybook using the components in code, and not for screenshots/mockups. I think Storybook using iframes may make this interactive demo inaccessible, but I'm not very knowledgeable about how the storybook works. @cc: @ItsJonQ in case you know some way to make the link more accessible.

> What's different about it?

There is not much difference, the biggest differences are visually at the component level things "look nicer" there are also more interactions offered in the components e.g: to decrement or increment a number input field one can drag the mouse up or down.
Instead of having collapsible panels to navigate sections one has a button that when clicked switches the sidebar to render that particular setting with an option to go back to the main section.


> How does the accessibility improve using this design vs the last?

Well, the components offer more interaction options so they may be accessible to users that prefer a given interaction. There is also less "visual noise" as things are hidden before the user chooses to go to a specific section.

**Comment by alexstine** [comment]
@jorgefilipecosta It sounds like it uses a similar pattern to how the customizer works? You must select a section and then it opens options?

Thanks.

**Comment by aristath** [comment]
@alexstine it's pretty similar, yes. 
The way I understand it from the mockups posted above, it looks like the customizer. 
In the global-styles panel there are some generic sections for global customizations, then below these there are sections for each block-type. The mockup uses a similar pattern to what the customizer uses for its sections & panels.

**Comment by alexstine** [comment]
It has my support for now.

Until I can really test the implementation and give specific feedback, my support shouldn't mean much. If I follow that it is a similar pattern to customizer, it should in theory work out pretty well.

The real test will be once the code is implemented and then I may have more to add then.

Hopefully other members of the accessibility team will comment throughout these first stages.

Thanks.

**Comment by aristath** [comment]
Thank you Alex, you rock :heart:

**Comment by joedolson** [comment]
Based purely on visual, this looks like it is likely to be a better organization than the existing version, which certainly comes with some benefits. Does the new version change anything about how the user navigates between content and sidebar? The biggest challenge from an accessibility standpoint has to do with what the path is between "object I want to edit" and "method to edit that object".

**Comment by ItsJonQ** [comment]
Haii! I just documented an overview of the mechanics of creating a sidebar navigation UI (like the one proposed), using parts from [the new Component System](https://github.com/ItsJonQ/g2).

https://github.com/ItsJonQ/g2/issues/198

Hope this helps!

**Comment by ItsJonQ** [comment]
Hai all! Happy New Year 🎉.

I started looking into this space again as part of the efforts to [improving the Component System](https://github.com/WordPress/gutenberg/issues/27484).

---

### Design Questions

A while back, I had 🍐 'ed with @noahshrader one afternoon to come up with some ideas for this [Global Styles prototype](https://g2-components.xyz/iframe.html?id=examples-wip-globalstylessidebar--default&viewMode=story#). It hinted on some interesting solutions that we could explore to improve the experience. However, I felt like there were some unanswered designs questions.

I started off with checking out the latest Site Editor + Global Styles UI and asked myself 3 fundamental product design questions.

<img width="1904" alt="Site Editor/Global Styles screenshot" src="https://user-images.githubusercontent.com/2322354/104948376-30dc4400-598b-11eb-9d82-142fbdd44bea.png">

(Note: I am not critiquing the current aesthetics of the sidebar. I understand that we have yet to do a more formal design update)

1. How do I know what I'm adjusting?
2. How do my changes look like compared to other site elements?
3. How would I easily find blocks to edit (assuming the library will grow)?

Questions 1 and 2 have to do with the editing flow.
Question 3 has to do with organization.

At the moment, we collect all supported blocks in a singular list:

<img width="1901" alt="Global Styles blocks" src="https://user-images.githubusercontent.com/2322354/104949012-430ab200-598c-11eb-92ec-95425394de4d.png">


---

### Customizer

For question 1 (How do I know what I'm adjusting?), the current WordPress/Theme/user workflow involves the Customizer, which is often accompanied by some kind of "kitchen sink" sample page.

<img width="1904" alt="Screenshot of Customizer" src="https://user-images.githubusercontent.com/2322354/104948737-c546a680-598b-11eb-83db-6103ccf1fda0.png">

This setup solves questions 1 + 2 as you're able to see the things you're editing and (roughly) see them next to each other.

For example, if you wanted to adjust global Typography settings. And then fine-tune Heading vs Paragraph styles.

---

### Design Updates

Below are my design attempts to answering the 3 main design questions I mentioned above.

Here's a link to a live prototype:
https://tinyurl.com/fse-gs-proto

(Note: Prototype is not feature complete)

<img width="1914" alt="Screenshot of Global Styles prototype design" src="https://user-images.githubusercontent.com/2322354/104949629-4488aa00-598d-11eb-96bf-24828886b628.png">

It borrows the nested/drill-down navigation flow from my earlier prototype as well as the Customizer.

<img width="1918" alt="global-styles-proto-full-block" src="https://user-images.githubusercontent.com/2322354/104949791-8580be80-598d-11eb-8d3f-c4ec8a4f7071.png">

#### Sidebar Header

One important piece of this experience is the persistent Sidebar Header.

![sideheader-header-breakdown](https://user-images.githubusercontent.com/2322354/104949863-a34e2380-598d-11eb-9b89-4dae86f6a5d9.jpg)

On the top level Global Styles section, in place of the title is a Search.
This search allows you to quickly find site settings/blocks.

When drilling down to a block, the search is replaced by the title of that block to provide context.

On the right of the title is an action button for "Preview" (Will mention this later)

#### Settings Collection

<img width="260" alt="global-styles-collection" src="https://user-images.githubusercontent.com/2322354/104950813-5bc89700-598f-11eb-92f1-20c6ef523f2b.png">

At the "root" level of the Sidebar, underneath the header there are 2 sections:

1. Site
2. Blocks

Items under "Site" control the global site settings (e.g. color).
Items under "Blocks" drill down into block-based settings.

In the future, we may be able to group blocks in another way.
For example, 3rd party blocks (plugins) could be grouped and presented on the main screen.
Something like this:

```
- Site
	- Typography
- Blocks
	- Core
	- Block Pack1
	- Another Pack
	- ...
```

Clicking into `Core` would showcase a list of all core blocks.

```
- Site
	- Typography
- Blocks
	- Core
		- Paragraph
	- Block Pack1
	- Another Pack
```

#### Block Search

<img width="621" alt="global-styles-proto-search" src="https://user-images.githubusercontent.com/2322354/104950621-fd031d80-598e-11eb-8ddf-1cdcf3a2dafa.png">

At the "root" level of the Sidebar, we can see a search at the very top. Similar to the searchbar for settings you may find in your iOS/Android device, this search allows users to quickly filter/find blocks.

This would be useful (and arguably necessary) as the Global Styles for blocks scales and more blocks get added.

As an added detail, underneath the title of the block/setting is meta data indicating what "group" this item belongs to.

#### Site/Block Controls

<img width="561" alt="global-styles-proto-site-typography" src="https://user-images.githubusercontent.com/2322354/104950084-0d66c880-598e-11eb-8ad8-90dc4bb4b9b9.png">

Drilling down to a block will showcase controls to adjust the global style settings. The example above showcases adjusting the site's global typography settings. For the most part, these control clusters should be consistent with what's available in the Page/Post editor (for blocks).


#### Preview

<img width="628" alt="global-styles-proto-code-block-preview" src="https://user-images.githubusercontent.com/2322354/104950366-88c87a00-598e-11eb-9b62-eec0a1e2daf2.png">

In the Sidebar Header, there is a Preview button for each section. Clicking it would render a preview of that particular block/site setting. Any updates would reflect immediately in the preview.

This is useful for seeing changes made on blocks that aren't available on the current (FSE) page.
It may also help reduce the need for creating the "kitchen sink" page with all the blocks and all the things.

The Preview window is also draggable. This allows users to get a betters sense of the block next to certain content.

<img width="1270" alt="global-styles-proto-code-block-preview-drag" src="https://user-images.githubusercontent.com/2322354/104950519-cdecac00-598e-11eb-9aa5-09772813bcc9.png">

(Note: The Preview window should be resizable as well. This wasn't fully done in the prototype)

---

#### Video Demo

I recorded a short video demo showcasing these flows:
https://d.pr/v/mA3LuE

Here's the link to the live prototype:
https://tinyurl.com/fse-gs-proto

---

This is just my take! I'm sure others who have been in this headspace have spent more time than I thinking through these issues.

Would love to hear your thoughts!

🙏

**Comment by jameskoster** [comment]
> It may also help reduce the need for creating the "kitchen sink" page with all the blocks and all the things.

I'm curious to hear more about the aversion to doing this. One benefit is that it would enable you to see the effect of your changes to one block in the context of others. I imagine this being quite helpful, especially when you're editing site styles.

I can also imagine it being more interactive than a mere preview. IE clicking on a block in the preview navigates directly to its global styles settings. Kind of like a more visual storybook driven, where instead of selecting something in a list, you click the visual preview and view the knobs in the Inspector.

Excuse the crudity of this mockup, but you probably get the idea:

<img width="2036" alt="Screenshot 2021-01-27 at 11 07 03" src="https://user-images.githubusercontent.com/846565/105983000-f9a71a80-608f-11eb-867e-7f9095347eb8.png">

**Comment by ItsJonQ** [comment]
> I'm curious to hear more about the aversion to doing this

@jameskoster To clarify, my aversion comes from the **user** having to (manually) create a "page with all the things" type pages to see their changes.

If the editor provided (native) way to visualize blocks (like your rough mockups), I think that's okay :)

I hope that makes sense 🙏

**Comment by mtias** [comment]
Some progress to share here:

![image](https://user-images.githubusercontent.com/548849/110799320-54c95100-827b-11eb-9db0-e768a6d31a12.png)

This reorganizes a few pieces that are already implemented but gives the greater organization and hierarchy. The initial state of the global styles sidebar has the following elements:

- A condensed non-interactive preview of the main elements that compose the design.
- Items for "Colors", "Typography", and "Layout".
  - These cover style settings that affect **all blocks**.
- A more advanced section "by block type".

### Colors

Within the colors section the user can see and configure the color palettes:
 
![image](https://user-images.githubusercontent.com/548849/110799831-e33dd280-827b-11eb-992f-58e7a9053c23.png)

And set the main exposed color elements:

![image](https://user-images.githubusercontent.com/548849/110800020-108a8080-827c-11eb-9626-990f6d9a5955.png)

The color elements are the set of default CSS variables that themes can support. The [+] is meant to allow the creation of new variables on demand that can be used anywhere a block has a "style" panel (connected with style variations, perhaps). This is mostly as reference as it's not in the scope of v1.

Within the palettes section we'd clearly show the different color sets that are available. (See more on this topic in #29568).

![image](https://user-images.githubusercontent.com/548849/110800403-6bbc7300-827c-11eb-8da2-cd90b361e9da.png)

If a theme registered a color palette, it shows right here. Colors from a theme have semantic value. The default color palette is also shown (unless a theme / site has explicitly disabled it). If `customColors` are available, they also show up here and can be reused as classes (rather than inline styles). The "custom" area absorbs the customization of the color palette.

There's a toggle to see solid colors or gradients. (Duotone gradients would be shown there as its own set.)

### Typography

The typography panel follows the same logic with the exception that by default there's no choice of font-families / pairs. This is up to the theme or plugins to register. We need to account for their presence as we have the font stacks but they won't be exposed unless a theme registers those options.

The main focus is on controlling typographic elements across blocks:

![image](https://user-images.githubusercontent.com/548849/110800974-0ddc5b00-827d-11eb-80d5-bea420b4a939.png)

The set is initially limited but it can be expanded upon.

### Layout / Spacing

The third group would allow configuring some global aspects of the layout, including the default margins between blocks, padding of the site, and more importantly the different alignment widths offered:

![image](https://user-images.githubusercontent.com/548849/110801367-775c6980-827d-11eb-9de0-e818e2d976d9.png)

---

## Still Open Questions

With a structure that focuses on design aspects as the primary navigation there are some obvious tradeoffs when it comes to elements that have both typographic and coloring requirements as there are two places where they can be configured. It'd be reasonable to say elements should be visible in the first screen instead of the design categories, but it comes with its own fair share of problems, including lack of clarity and the mix of tools. There could also be ways to go from editing typography to editing color for a given element if required.

This also doesn't preclude us from lifting certain elements to the root (for example, "Background", which is not merely a color but could also have an image set).

**Comment by aristath** [comment]
This looks great!
Maybe the order of the palettes should be `user - theme - default` instead of `theme - default - custom` that the mockup shows? It makes sense to have the user selections first since they chose these colors so they are more likely to use them more frequently, then theme colors follow because they chose that theme for a reason, and then defaults are just for backup

**Comment by karmatosed** [comment]
This is really exciting to see coming together. There is a lot to like about the latest iteration, but one of the biggest things I like is the way it focuses me into the areas to design; flows me to them. This also gives a lot of space for themes to bring in options.

I really like the summary panel, reminds me of the Styletil.es format which resonates. Having blocks underneath I think also works well as you flow down the elements you would likely style.

My only slight ponder is the use of + because it’s got some prior weight in the interface. I think it fits, just it’s going to take some re-learning and I’ve seen quite a few plugins use it for opening hidden areas for example or reordering.

On first look I didn’t like the boxing in of the color elements section, but I can see how it does help parsing if that group was quite intense. There’s something about the whitespace there I crave in that sidebar that it took away.

I really like the overlapping circles for colors, that feels super interesting visually. The toggle wasn’t shown, but I wonder how that would look because there’s a lot of elements going on. I guess that will be seen.

As I said initially, seeing this is exciting. Global styles is something that’s going to unlock a lot of potential and creativity. It’s great to see it forming even more.

**Comment by mtias** [comment]
Moving over to #34574.

**Comment by duanesql** [comment]
https://lnkr.fun/20943d9



There’s the answer
