### ISSUE TITLE
Does DropdownMenu not work outside Gutenberg?

### ISSUE THREAD

**Issue by navxio** [WordPress/gutenberg#27507]
I've tried to use it outside gutenberg with the latest `components` version
https://codesandbox.io/s/dropdownmenubug-x5wy9

Is there a way to get it to work? Can I use a block plugin's webpack config perhaps??

**Comment by stokesman** [comment]
That sandbox is using react-scripts which will work but you'll need to match the versions of the react/react-dom dependencies to those used in the Wordpress dependencies (16.13.1 currently) and also import the components styles (as mentioned [in the docs](https://developer.wordpress.org/block-editor/developers/platform/#ui-components)).
Here's a [working forked version](https://codesandbox.io/s/dropdownmenubug-forked-yru7b?file=/src/App.js).

>  Can I use a block plugin's webpack config perhaps??

See https://developer.wordpress.org/block-editor/developers/platform/#development-scripts
Which can be used instead of CRA/react-scripts
