### ISSUE TITLE
Heading block: the font size drop-down options gets overlap with each other 

### ISSUE THREAD

**Issue by kmadhak** [WordPress/gutenberg#27606]
Describe the bug
in Heading block the font size drop-down options gets overlap with each other 

Steps to reproduce the behaviour:

1. Go to 'Editor'
2. Add new page
3. Click on 'add block'
4. Select the block 'Heading'
5. Enter text as Heading
6. View the options of 'font size' drop down
7. See error

Expected behaviour
Options of drop-down should not get overlap with other

Screenshots
https://prnt.sc/vywy1n

Video
for more detail please view the attached video
https://www.loom.com/share/c18f7e3fc98c4771972d5c460ece0cb3

Editor version:
WordPress version: 5.6

Desktop:
OS: Windows
Browser chrome
Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by talldan** [comment]
@kmadhak This was fixed in the Gutenberg plugin (https://github.com/WordPress/gutenberg/pull/26705) but unfortunately the fix didn't end up in WordPress 5.6. I've labelled it now for WordPress 5.6.1 whenever that may be.

Thanks for testing, I'll close this issue given the fix has already been made.
