### ISSUE TITLE
Featured Image block: Allow free-form resizing

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#27620]
## What problem does this address?

When working with in the Query block's grid view, it would be great to allow for themes to set a consistent height/crop for all of the Featured images within. 

Example use case, where each image is cropped to a square: 

![](https://user-images.githubusercontent.com/1202812/101647418-b375f900-3a06-11eb-9b6a-9ea8a9b6c221.png)

The current lack of dimension controls on the featured image block means individual image aspect ratios are unchanged, causing a bit of a jumpy layout:

<p align="center">
<img width="300" alt="Screenshot 2021-05-03 at 11 28 55" src="https://user-images.githubusercontent.com/1204802/116861118-e3ff3f00-ac02-11eb-9b49-dce08cc6d02c.png">
</p>

## What is your proposed solution?

If we enable dimension controls and allow [object-fit](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) properties to be configured (defaulting to `cover`), we can enable some much more coherent and nice layouts. Shown here with some custom border radii applied as well:

<p align="center">
<img width="300" alt="Screenshot 2021-05-03 at 11 13 35" src="https://user-images.githubusercontent.com/1204802/116861278-258fea00-ac03-11eb-8860-b0a3542e01f2.png">
</p>

Here's what the featured image inspector controls could look like:

<img width="1440" alt="Featured Image" src="https://user-images.githubusercontent.com/1204802/116861641-b5ce2f00-ac03-11eb-8f47-cbe922909199.png">

_This was previously explored in #27545_

**Comment by ntsekouras** [comment]
This is related: https://github.com/WordPress/gutenberg/issues/24660. There are design explorations as well.

**Comment by ianstewart** [comment]
Additional example where automatic cropping as an option would be valuable:

![image](https://user-images.githubusercontent.com/545779/106058479-e9566600-60b6-11eb-9ea7-b22aa214e154.png)

**Comment by annezazu** [comment]
To make sure feedback isn't lost from this [recent WP Tavern post](https://wptavern.com/fse-outreach-round-2-building-a-custom-homepage-with-gutenbergs-site-editor), I'm sharing here as it's relevant to the discussion above:

> There is no way to set the size of the image output by the Post Featured Image block. The only way to get a uniform size at the moment is to pre-crop the images before uploading them to WordPress. There is no reason this should not essentially be a variation of the Image block. The only thing featured images need that is different is the option to link to the post.

This was identified as a current pain point in the FSE experience.

**Comment by jasmussen** [comment]
I took the liberty of tweaking the title and content of this ticket a little bit, with some mockup work from the now-closed #31418.

**Comment by leph83** [comment]
I would add another Setting with a slider where you can adjust the ratio. 
And if you add this feature, it would be nice, if you can choose which part of the image should always be visible. 
Like the control in the cover block.

**Comment by paaljoachim** [comment]
The controls suggested by @kjellr Kjell seems like a good first iteration/version.

![Screen Shot 2021-05-04 at 18 32 59](https://user-images.githubusercontent.com/5323259/117037850-417cb400-ad07-11eb-8276-78669979eecf.png)

I do have one question. Will the "contain" option in a way crop very tall images? So that all images look nice at the height and width suggested?

---

We do also have the possibility to use the Focal point picker having a more finetuned selection as @leph83 touches upon.

---

For a more advanced version we have @shaunandrews Shaun's mockups here: https://github.com/WordPress/gutenberg/issues/24660#issuecomment-700255041
These are more complex. Mockup of controls for the Cover and Group blocks.

**Comment by leph83** [comment]
@paaljoachim I'm not a huge fan of fixed pixel sizes. It's not responsive.

**Comment by jasmussen** [comment]
The blue px indicator is meant to be a unit selection dropdown, so you could choose other units, such as %, vw, vh, em, rem, etc.

**Comment by leph83** [comment]
> The blue px indicator is meant to be a unit selection dropdown, so you could choose other units, such as %, vw, vh, em, rem, etc.

So if I have 3 Columns with a picture inside of each, that I wanted to make square I could set the properties to 100% height and 100% Width to achieve that? That would work for me. 

I don't see the possibility to choose the object position in your design, when I chose cover as my scaling option. That would be nice to have.

**Comment by jasmussen** [comment]
> So if I have 3 Columns with a picture inside of each, that I wanted to make square I could set the properties to 100% height and 100% Width to achieve that? That would work for me.

Well, if those 3 columns were part of a query, then setting the dimensions of one of the featured images to square would do it for all of them, yes.

I'd agree it would be nice to also have the focal point picker for the featured image block, but I'd think it would be a nice followup to do. Also keep in mind that themes could do it in the manually as well.

**Comment by leph83** [comment]
Oh I missed the part, where it's a query. This feature would also be amazing for the Gallery Block and the Image Block itself too

**Comment by ntsekouras** [comment]
In order to use `object-fit` here we need to have set a `width` and a `height/min-height`. Should we have some defaults like `width: 100%` and `height/min-height: 200px` for example? Can we communicate this better by showing/hiding `scale` controls depending the existence of `width` and `height` values?

--edit: Maybe having only a `height` control makes more sense? Do we have use cases that we would want to restrict featured image's width, especially when the block has another wrapper outside the `img` element (currently a `p`)? 

Any thoughts?

**Comment by jasmussen** [comment]
> In order to use object-fit here we need to have set a width and a height/min-height. 

Excellent point. Without them they aren't that useful. One option: only show the image scaling properties if a width and height have been set:

<img width="1440" alt="no dimensions" src="https://user-images.githubusercontent.com/1204802/117266278-5ff0c580-ae55-11eb-811f-f43e3c0d2c41.png">

<img width="1440" alt="dimensions" src="https://user-images.githubusercontent.com/1204802/117266326-6e3ee180-ae55-11eb-9f8a-d2b5fee447fb.png">

**Comment by carolinan** [comment]
Could the featured image be a variant of the image block, just with a different source?
The image block has more features and is tested, yet, trying to import controls from it to the featured image block or the custom logo has proven to be very difficult.

**Comment by ntsekouras** [comment]
>Could the featured image be a variant of the image block, just with a different source?

I recently made some exploration for making it a block variation of `Cover` but it needs way more explorations as the flows become difficult to reason with. I'm not sure about the `source` attribute since this is a dynamic value and haven't worked with this handling before..

I believe landing at least a basic handling for now like the above would be okay for now and gives value, in order to make it to 5.8. I'll have a PR soon for this and we can test how it feels.

**Comment by justintadlock** [comment]
> To make sure feedback isn't lost from this [recent WP Tavern post](https://wptavern.com/fse-outreach-round-2-building-a-custom-homepage-with-gutenbergs-site-editor), I'm sharing here as it's relevant to the discussion above:
> 
> > There is no way to set the size of the image output by the Post Featured Image block. The only way to get a uniform size at the moment is to pre-crop the images before uploading them to WordPress. There is no reason this should not essentially be a variation of the Image block. The only thing featured images need that is different is the option to link to the post.
> 
> This was identified as a current pain point in the FSE experience.

I wanted to add some clarification to this since it was added to a ticket about Dimensions.  While related, I was specifically referring to the **Image Size** control (e.g., full, thumbnail, medium, large, custom-theme-size, etc.) and not width/height controls.  These are the sizes created via `set_post_thumbnail_size()` and `add_image_size()`.

This ticket seems to be moving toward a path for dimension and scaling controls, which is great, but I don't want this feature to get lost if it's out of scope for this ticket.  I can open a separate ticket if needed.

**Comment by jasmussen** [comment]
Thank you for the reminder, Justin. Here I included the thumbnail size picker:

<img width="1440" alt="Featured Image i3" src="https://user-images.githubusercontent.com/1204802/120147692-56a21100-c1e7-11eb-8885-4afea2a523e7.png">

**Comment by melchoyce** [comment]
Instead of having to specify an exact width and height by default, it might be nice to explore the ratio picker the image block uses:

![image](https://user-images.githubusercontent.com/2846578/125703032-5e2e5f09-69f5-405b-acaf-e1bad708d7f5.png)

**Comment by antonyjsmith** [comment]
Just to weight in here to provide some end user perspective.

Rolling out a new block which is aimed at replacing blocks like 'Latest Posts' before reaching feature parity is a major pain in the ass as you keep having to relearn stuff, hit brick walls and end up at GitHub, which lets be honest, isn't somewhere your average Joe is going to want to start digging around to find out why they can't change the image size in a significant new feature.

By way of example there are now two blocks to create a grid of posts and one handles featured images better than the other provided it's a post I want to use and not a CPT or Page, if that's the case then I'll have to hard crop them all.  This is incredibly frustrating, a waste of time, confusing and tough to explain to an end user.

I just find it a lot of wasted effort to have all this discussion around a completely different implementation when the featured image control works perfectly well in the 'Latest Posts' block and is familiar to a user since it's basically the same as an image block.

Having to relearn an approach with a replacement block and discover limitations, inconsistencies of feature sets to what on the surface appear the same components and lack of feature parity for existing approaches with replacement blocks is a consistent blight on the Gutenberg project.

**Comment by justintadlock** [comment]
Should this ticket be closed by #31634?

I was under the impression that an Image Size control was a part of this, which is why I didn't open another ticket (it would also partially cover @antonyjsmith's concerns).  I don't think this is in the PR.

**Comment by ntsekouras** [comment]
The issue was closed automatically from the PR and addressed the initial proposed enhancements. There are more to come to this block (Featured Image) and we have [this issue](https://github.com/WordPress/gutenberg/issues/32332) for consolidating the 'posts list' blocks. 

I created a new issue for the image controls here: https://github.com/WordPress/gutenberg/issues/33789
