### ISSUE TITLE
Media and Text block renders undesired top border around the image

### ISSUE THREAD

**Issue by remyjimjim** [WordPress/gutenberg#27625]
**Describe the bug**
The Media and Text block of the "Block" editor renders an undesired top border around the image.

**To reproduce**
1. Add a new page
2. Add a "Media and Text" block to the page
3. Upload an image via the "Upload" button, my image was 8k and 400x400 png
4. Resize the image via the grabber dot
5. Click on the "Content" pane and enter the text that goes next to the image
6. Click the "Publish" button to save your work.
7. Confirm that you want to publish as either private or public.  I've tested both.
8. View page.  You'll likely see the image on the left of the text with a dotted border above the image.  

**Expected behavior**
You should see the image on the left of the text without a border above the image.

**Screenshots**
![image](https://user-images.githubusercontent.com/5574148/101678333-a8c16100-3a12-11eb-9707-2144d4bb00bf.png)

**Editor version (please complete the following information):**
- WordPress version: 5.4.4
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default
- If the Gutenberg plugin is installed, which version is it? Not installed

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: firefox 83.0, chrome 87.0.4280.88 (Official Build) (64-bit) , opera 72.0.3815.400
 - Version [e.g. 22] see above

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by talldan** [comment]
@remyjimjim Thanks for reaching out. I couldn't reproduce this using a very similar 400x400 png with a transparent background:
<img width="710" alt="Screenshot 2020-12-10 at 11 28 31 am" src="https://user-images.githubusercontent.com/677833/101717805-f43f4200-3ada-11eb-8ad9-df0e22fddd70.png">

I tried a number of different bundled themes, and also tested both WordPress 5.4.4 and WordPress 5.6, but still didn't get the border.

I think this is most likely to be caused by either your theme or a plugin, most likely the theme.
