### ISSUE TITLE
Categories: number of posts in the editor do not count descendant categories

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#27642]
The categories block has an option that allows users to show the number of posts within a category. Categories can be hierarchical, and when they are, the number of posts of a category includes the number of posts of its descendants.

Example: 

- Having the following hierarchical categories: "sports" > "martial arts" > "aikido". 
- Add the "sports" category to 1 post, add the "martial arts" category to 1 post, and add the "aikido" category to 1 post.
- Create a post that includes the category block showing the post count and publish it.

The expected result is that the number of posts listed in each category is:

- 3 for "sports"
- 2 for "martial arts"
- 1 for "aikido"

In the front-end & in the post list screen (`wp-admin/edit.php`) the numbers are correct. However, in the editor, the numbers are 1 for each category.

**Comment by settenop** [comment]
As of my understanding (but I'm a noob, just started digging around the code) the count is returned by the REST API, the values should be from the WP_REST_Terms_Controller::get_items method, the problem is that get_items would actually discard the "pad_counts" parameter needed in order to fix this bug.

If I'm right a possible solution could be:
1. Add "pad_counts" to $parameter_mappings in  WP_REST_Terms_Controller::get_items (https://github.com/WordPress/WordPress/blob/3ed22735d3834b74e0706322fb2a52f032e695e9/wp-includes/rest-api/endpoints/class-wp-rest-terms-controller.php#L182-L192).
2. Register "pad_counts" in WP_REST_Terms_Controller::get_collection_params (https://github.com/WordPress/WordPress/blob/3ed22735d3834b74e0706322fb2a52f032e695e9/wp-includes/rest-api/endpoints/class-wp-rest-terms-controller.php#L999)
3. Add "pad_counts" with true as value to the categories block query https://github.com/WordPress/gutenberg/blob/8d5fd89f573e00601b189b1a2f87d5bc7b862349/packages/block-library/src/categories/edit.js#L30

Should we ask if it's ok to add the "pad_counts" parameter to the REST API or I'm missing something?

**Comment by kathrynwp** [comment]
I can replicate this, but I'm not actually sure whether this qualifies as a bug or not. If it is, it doesn't seem to be specific to Gutenberg, because when I go to the Posts > Categories area, I see that the Sports, Martial Arts, and Aikido categories each show 1 post, as you can see here in this example:

![Categories_‹_Self-hosted_Test_—_WordPress](https://user-images.githubusercontent.com/7662449/183698227-b3f3e905-36dc-456a-b41e-84c25653425b.jpg)

@talldan I'd appreciate your input, thanks!

**Comment by talldan** [comment]
From @settenop's comment it sounds like it could be a core REST API issue, though it's something I'm familiar with. I couldn't find any associated core trac tickets.

@spacedmonkey - would you be able to confirm if this is something that requires a trac ticket, or is it a case of Gutenberg doing it wrong?

**Comment by jordesign** [comment]
As we've had no further input on this issue in about a year - I'm going to close it out. @spacedmonkey  please feel free to reopen if it is still an issue - along with any further details of if it should be handled in Trac, or is Gutenberg specific.
