### ISSUE TITLE
Text overlap while typing in visual editor

### ISSUE THREAD

**Issue by Rajiv-A** [WordPress/gutenberg#27816]
Hi

Kindly refer to the attached screen shot, where the text gets overlapped after typing the text and press Enter key.

Is this a bug?
![Wordpress post error](https://user-images.githubusercontent.com/76216517/102632345-f9545f00-4174-11eb-85ec-b8a5adf73977.jpg)

**Comment by annezazu** [comment]
@Rajiv-A thanks for reaching out! This definitely looks like a bug but it might be due to other plugins you have installed on your site. Can you confirm this bug while you're using WordPress 5.6 and the latest version of Gutenberg (9.6.2) if you have Gutenberg installed? I ask because I wasn't able to replicate this using solely WordPress 5.6 and Gutenberg 9.6.2!
