### ISSUE TITLE
Saving a Short Code Gives a JSon Error

### ISSUE THREAD

**Issue by honestjohn1** [WordPress/gutenberg#27815]
When I try to save a short code I get a Json error in the blocks editor, it works perfectly with the classic editor. Looking at previous posts, it seems this issue has been reported over and over again for the last 2 years which surprises me rather! See the screen short below:

![2020-12-18](https://user-images.githubusercontent.com/76218218/102631876-32290f80-4146-11eb-9d4a-65b5e1a144b0.png)

Any suggestions?

**Comment by annezazu** [comment]
@honestjohn1 thanks for reaching out to report this although I'm bummed you're having trouble. For starters, can you confirm that you are using WordPress 5.6 and the latest version of Gutenberg (if you have it installed)? Finally, are you able to replicate this if your other plugins are disabled? Looking through some support forums related to this issue, it seems permalinks might also play a role: https://wordpress.org/support/topic/error-updating-failed-error-message-the-response-is-not-a-valid-json-response/ Thanks in advance for the additional information as it's necessary for us to properly identify the cause here.
