### ISSUE TITLE
Add rich text to the site title block

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#27830]
**Is your feature request related to a problem? Please describe.**

The site title block is in many ways a heading block, but it does not have the same controls.

I would like to be able to edit it as HTML, to split the text into two lines, and I would like to be able to use the inline color tool to 
have two different text colors.

The buttons are not even in the same position and the font weight for the heading level is different. I think it would be good to make them consistent:

![site-title-comparison](https://user-images.githubusercontent.com/7422055/102688011-095f5380-41f4-11eb-8c2f-6aeea5e6c36c.png)

**Comment by mtias** [comment]
This came up a few times before (used to be rich text) and the main issue is inline html is not allowed to be saved on the title, so block level transforms are the only ones available.

**Comment by carolinan** [comment]
So the solution would be to allow saving of HTML but remove it before output inside a title _attribute_?

**Comment by mtias** [comment]
Since the site title attribute can be used in multiple ways in WordPress and allowing encoded html would be a breaking change we'd need to figure out a different way to save formatting while leaving the option in plain text. This could get tricky, since if we separate formatting from the raw data we could run into sync issues. At that point probably the easiest is to keep the data in html and sync on edit to the site option if you want to user inline formatting.

**Comment by glendaviesnz** [comment]
@carolinan  - text format options have been added in https://github.com/WordPress/gutenberg/pull/31734, it seems that currently this is the only option for adding additional formatting options to this block given the inability to support rich text, but will let you decide if you want this ticket to remain open for further exploration of rich text support.
