### ISSUE TITLE
Multiple toolbars in Tablet & Mobile preview in FSE

### ISSUE THREAD

**Issue by hawkmusician** [WordPress/gutenberg#27841]
**Describe the bug**
Multiple toolbars appear in tablet & mobile preview mode when selecting a block. One appears in the header (by default in tablet & mobile mode) and another on the block itself (as default in Desktop mode).

**To reproduce**
1. Go to site editor
2. Add 2 blocks
3. Go to tablet or mobile preview mode
4. Select second block, see error with toolbar appearing in both header and editor.

**Screenshots**

![multipletoolbars](https://user-images.githubusercontent.com/23136551/102761698-8961f680-4377-11eb-906b-a7b403224a1c.PNG)

**Editor version (please complete the following information):**
- WordPress version: 5.6
- Gutenberg plugin installed 9.6 RC

**Comment by annezazu** [comment]
@hawkmusician it looks like you're using additional plugins outside of just Gutenberg in this case. Can you deactivate the other plugins installed on your site and test once more? On my end, I wasn't able to replicate this duplicating issue but I was able to find an issue with the toolbar not loading properly:

https://user-images.githubusercontent.com/26996883/103309778-420ce300-49d3-11eb-8db9-0757b18cce6e.mov

I reported this here for now: https://github.com/WordPress/gutenberg/issues/27920

**Comment by hawkmusician** [comment]
Hi @annezazu. Thanks for taking a look at this.

Here's a video that I hope will explain better. All other plugins were deactivated. 

https://user-images.githubusercontent.com/23136551/103337993-41308b80-4a7d-11eb-86d0-8e565105e9f4.mp4

**Comment by annezazu** [comment]
@hawkmusician  thanks for this video!! Can you send me a screenshot of what settings you have enabled for both the post/page editor and the site editor? Here's an example:

<img width="289" alt="Screen Shot 2021-01-04 at 12 21 22 PM" src="https://user-images.githubusercontent.com/26996883/103571009-5d6e6700-4e87-11eb-8425-db41109f62d7.png">

I ask because it seems like with the post/page editor you likely have the Top Toolbar view enabled which is why you don't see the toolbar over the individual blocks.
