### ISSUE TITLE
Alpha support for ColorPalette custom color

### ISSUE THREAD

**Issue by amir2mi** [WordPress/gutenberg#27960]
Hi is there any option for adding alpha support to ColorPalette custom color, color picker?
This component is quite practical and saves developers from working and wasting time with ColorPicker. 
But the limitation for this component is just alpha support and I searched for it but did not find anything related.

![colorpalette](https://s16.picofile.com/file/8419851000/Annotation_2021_01_02_193720.jpg)

**Comment by mupic** [comment]
This is a very necessary change that I personally keep waiting for about a year now and it is very strange that it was not supported from the very beginning.

**Comment by amir2mi** [comment]
@mupic Probably forgotten. As I tried the color picker of experimental gradient picker supports this feature.

**Comment by skorasaurus** [comment]
Hi, I believe this can be closed because alpha support is included by default in the color picker. 

Your pull request is still applicable as far as I know. 

Please reopen if I missed understood. 

![image](https://user-images.githubusercontent.com/955351/213812051-4a07404f-8a19-4e43-860c-14c6dae582ee.png)
