### ISSUE TITLE
Invalid date format response updating very old post date

### ISSUE THREAD

**Issue by bondweb** [WordPress/gutenberg#27975]
Hi there,

I got this response 

{
  "code": "rest_invalid_param",
  "message": "Parametro(i) non valido(i): date",
  "data": {
    "status": 400,
    "params": {
      "date": "Data non valida. "
    }
  }
}

when I try to update in Gutenberg the date of a post published before 1901/12/14  This issue happens only in a wp stage site installed on windows IIS 10 hosted on microsoft azure. The same if I try to create a new post dated before 1901/12/14.

If I use the quick edit I haven't the issue and all works fine. It's evident that the issue happens only when the client works with the WP REST API.

How can I fix it? Thanks guys :-)

**Comment by talldan** [comment]
@bondweb It looks like this is a limitation on 32-bit systems, some more background in this ticket -https://core.trac.wordpress.org/ticket/25347

> The valid range of a timestamp is typically from Fri, 13 Dec 1901
 20:45:54 UTC to Tue, 19 Jan 2038 03:14:07 UTC. (These are the dates
 that correspond to the minimum and maximum values for a 32-bit
 signed integer.)
 
So I don't think there is a way for you to fix this without switching your server. Worth checking the WordPress forums though to see if anyone else has encountered this (https://wordpress.org/support/forums/).
 
I'm not sure whether WordPress core could handle those past dates differently in the same way future dates were fixed on that linked ticket. If you'd like to report it as a bug I'd recommend using trac (https://core.trac.wordpress.org/newticket), as the code that handles the date validation is in WordPress core rather than the Gutenberg plugin.
