### ISSUE TITLE
get_block_categories(WP_Post $post) ... get_all_block_categories()? 

### ISSUE THREAD

**Issue by douara** [WordPress/gutenberg#28009]
I am trying to list all blocks registered ( Core blocks & Custom ones registered by plugins ) under their respective categories in a custom admin page.

Categories are set for blocks using the dispatch method `wp.blocks.setCategories`, like in [this example](https://github.com/WordPress/gutenberg/blob/c597dd7fd3e06bfdf4737b5e101b28bf3a3e517f/lib/edit-site-page.php#L156
)

Some plugins register their block categories only for specific post types, and the function `get_block_categories(WP_Post $post)` return the block categories only for the current post type, it won't return them if we were in custom admin page for instance. 

**Describe the solution you'd like**
some way to get the list of all registered block categories 
define a new function `get_all_block_categories` that doesn't take any  parameters and returns all blocks categories registered for all post types

**Comment by johngodley** [comment]
The `get_block_categories` function can be supplied with an editor context instead of a post:

```php
get_block_categories( new WP_Block_Editor_Context() );
```

This means you don't need to supply a post. However, it requires blocks to use the `block_categories_all` filter instead of the deprecated `block_categories` filter.

As shown in the example here, it's possible the category will only be added if a specific post type is supplied:

https://github.com/WordPress/gutenberg/blob/f3797c37b2f0b5d3ee52282bb3cd5563db8e9b8a/docs/reference-guides/filters/block-filters.md#managing-block-categories

With this in mind I'm not sure there is an easy way of achieving a 'get all' function that would work with existing blocks as well as future blocks - everything is set up to expect a post.

Given your custom requirements it may be easier to iterate over all the post types, and call `get_block_categories` for each, merging together and removing duplicates.

**Comment by OArnarsson** [comment]
@DOUARA were you able to find a good way to achieve this?

**Comment by abder** [comment]
@oandregal 
I do think that is the only way:

> Given your custom requirements it may be easier to iterate over all the post types, and call get_block_categories for each, merging together and removing duplicates.

**Comment by tellthemachines** [comment]
@douara if your question is answered can we close this issue now?

**Comment by abder** [comment]
> @douara if your question is answered can we close this issue now?

Yes, Thanks!
