### ISSUE TITLE
Improve searching for blocks with similar names in the slash inserter

### ISSUE THREAD

**Issue by SJNBham** [WordPress/gutenberg#28051]
When using the forward-slash method to insert a new block, you can type in characters to search for available blocks. If a block name has a space in it, users are unable to search for that block using a space. For example, searching the following list of blocks using "/PRE B" doesn't provide any results:

PRE Block 1
PRE Block 2
PRE Block 3
PRE Block 4

Whereas searching the above list using "/PRE" returns all of them up. 

We have a bunch of reusable blocks with text similar to the above list to make it easier for our content editors to see which are custom for our agency vs. standard blocks. However, this also applies to standard blocks like "Media & Text" and "Page Break".

It would be great if spaces were allowed in the search for reusable blocks while using the inline forward-slash insertion option.

**Comment by talldan** [comment]
Thanks for the suggestion. Another or additional suggestion is to use a fuzzy search so that typing 'PRE2' matches 'PRE Block 2', that will lead to faster matching compared to having to type the exact block name.

A good example is that there are the Latest Comments and Latest Posts blocks, and it'd be easier to get the right result if you could just type something approximate like 'lposts' and have the most relevant block with those characters in its name appear at the top.

**Comment by mtias** [comment]
This should have been addressed with #29939.
