### ISSUE TITLE
wp-env: file permissions issues with rewrites and uploads

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#28201]
## Description

It seems like it's not possible to use pretty permalinks with wp-env and/or upload files; at least ffor the tests container.

## Step-by-step reproduction instructions

1. Try to upload file
2. Receive issues about year-based upload folder not being writeable
3. Try to enable pretty permalinks on the tests container, for example via `npm run wp-env run tests-cli "wp rewrite structure '/%postname%'"`
4. Try to access container via pretty permalinks, get Apache error message instead of seeing WP

## WordPress information
- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: 
- Operating system: 
- Browser:

**Comment by imgerson** [comment]
I think there are permission issues when the WordPress version is specified using the `core` field @swissspidy. I found this working on the e2e tests for the Sucuri WordPress plugin https://github.com/imgerson/sucuri-wordpress-plugin/actions/runs/587185507

**Comment by swissspidy** [comment]
Interesting finding, thanks for sharing! That will make debugging hopefully a tad easier.

**Comment by noahtallen** [comment]
I'm guessing that rewriting the URL format is related to the [line in the documentation](https://developer.wordpress.org/cli/commands/rewrite/structure/) which says "To regenerate a .htaccess file with WP-CLI, you’ll need to add the mod_rewrite module to your WP-CLI config." it could also be due to the wp-cli being a separate service from the one which serves requests.

Re: image uploads. I'm currently able to upload images to both the dev and tests image in the editor and in the media library using the .wp-env.json in this repo. Could you share yours? I wonder if a difference there is causing the problem.

**Comment by noahtallen** [comment]
#30053 also fixed some permissions issues, so it'd be worth re-testing file upload. (The URL format is still broken though.)

**Comment by andrewmumblebee** [comment]
I'm also experiencing this issue

It works fine with v4.0.4 but after updating my global version of @wordpress/env to 5.10.0 none of my API testing is working as .htaccess is not writeable.

When the docker container is spun up, the whole of the WordPress folder has my user as the owner, rather than using www-data as the owner for the folders. 

It looks like the `chown www-data:www-data wp-content wp-content/plugins wp-content/themes` that was removed in https://github.com/WordPress/gutenberg/pull/30053 was needed, stuff like the `mu-plugins` folder is not writeable without this.

I'm not using a custom "core" in wp-env.json, just a couple of mappings. Also tested this out on a seperate folder without a wp-env.json file, so it would use the base setup and it still can't write to .htaccess in the container as the owner is my user rather than www-data.

So even simple APIs such as /wp-json/wp/v2/posts don't work atm with wp-env for me.

**Comment by noahtallen** [comment]
This should be solved by #49962. You'll be able to see the change it when developing Gutenberg directly (since `npx wp-env` or `npm run wp-env` execute the source code directly in this repo). The fix should be available in about 10 days on npm. You may need to destroy the environment first so that it can be re-created with the correct permissions. Of course, if you still experience issues, drop a comment!
