### ISSUE TITLE
WP 5.6 getCurrentPostType and others not working anymore

### ISSUE THREAD

**Issue by Elkex** [WordPress/gutenberg#28225]
Hello!

After updating to WordPress 5.6, we noticed that getting the getCurrentPostType, getCurrentPostId,... API functions are not working anymore.

```
wp.domReady( () => {
	const postType = select( 'core/editor' ).getCurrentPostType();
});
```

I cannot seem to find an alternative or updated version of this hook.

Anyone an idea?

Thanks in advance!

**Comment by ntsekouras** [comment]
Hey @Elkex 👋 - thanks for reporting this!

Actually the API works fine. The problem lies in `wp.domReady`.

I'll close this one in favor of:https://github.com/WordPress/gutenberg/issues/25330, that has a bit more context.

**Comment by nickpish** [comment]
Would someone be able to provide a full, working example of how to use `getCurrentPostType()`? I've read through all the linked threads relating to this issue, and I'm still not able to get `wp.data.select( 'core/editor' ).getCurrentPostType()` to return anything other than `null`. I'm trying to get the current post type to allow for conditionally unregistering blocks and modifying settings, using a script enqueued via `enqueue_block_editor_assets`. I've tried adding numerous dependencies, and nothing seems to work. This thread comes up high in Google searches for "getCurrentPostType not working" so I'd imagine others might find an example of a working solution helpful as well- thanks!

**Comment by MarkMarzeottiDI** [comment]
@nickpish Came across this today and pieced together an answer to the question as I had it as well. As mentioned above `wp.data.select( 'core/editor' ).getCurrentPostType() ` does not seem to be available at `wp.domReady`. The solution is described in issue [#25330](https://github.com/WordPress/gutenberg/issues/25330) by user [markhowellsmead](https://github.com/markhowellsmead). I was able to use [subscribe](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-data/#subscribe) to wait until the post type becomes available, do what I need to with that info, then unsubscribe. My code where I am removing a taxonomy panel if the user is editing a 'location' post looks like this:

```
const getPostType = () => wp.data.select('core/editor').getCurrentPostType();
let postType = null;

const unsubscribe = wp.data.subscribe(() => {
	const newPostType = getPostType();
	if (newPostType !== postType) {
		unsubscribe();
		postType = newPostType;
		if ('location' === postType) {
			wp.data
				.dispatch('core/edit-post')
				.removeEditorPanel('taxonomy-panel-associated_location');
		}
	}
});
```

I'm not certain this is the most efficient way, but since `wp.domReady` was being fired before all the data was available, this is working to run the code as soon as it becomes available.

**Comment by nickpish** [comment]
Thank you, @MarkMarzeottiDI - I will give this a shot!

**Comment by jranby** [comment]
> [@nickpish](https://github.com/nickpish) Came across this today and pieced together an answer to the question as I had it as well. As mentioned above `wp.data.select( 'core/editor' ).getCurrentPostType() ` does not seem to be available at `wp.domReady`. The solution is described in issue [#25330](https://github.com/WordPress/gutenberg/issues/25330) by user [markhowellsmead](https://github.com/markhowellsmead). I was able to use [subscribe](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-data/#subscribe) to wait until the post type becomes available, do what I need to with that info, then unsubscribe. My code where I am removing a taxonomy panel if the user is editing a 'location' post looks like this:
> 
> ```
> const getPostType = () => wp.data.select('core/editor').getCurrentPostType();
> let postType = null;
> 
> const unsubscribe = wp.data.subscribe(() => {
> 	const newPostType = getPostType();
> 	if (newPostType !== postType) {
> 		unsubscribe();
> 		postType = newPostType;
> 		if ('location' === postType) {
> 			wp.data
> 				.dispatch('core/edit-post')
> 				.removeEditorPanel('taxonomy-panel-associated_location');
> 		}
> 	}
> });
> ```
> 
> I'm not certain this is the most efficient way, but since `wp.domReady` was being fired before all the data was available, this is working to run the code as soon as it becomes available.

Super useful, thanks
