### ISSUE TITLE
Use Gutenberg as default editor

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#2824]
Related: #2159

As Gutenberg stabilizes, we should begin to develop a strategy by which it will take the place of the current post editor. As it stands, the Gutenberg editor is relegated to a separate admin sidebar menu section and surfaced through secondary actions in the posts list screens. Now also as of #1797, when generating an edit link for a post, it will default to the Gutenberg editor if the post contains block content.

**Task:** Change Add New for all posts admin menus and admin bar to direct to the Gutenberg editor, not as a separate submenu screen, but integrated into the default post editing workflow.

**Open questions:**

- Would we / how would we continue to expose the classic post editor, both during the lifetime of the feature plugin and as a final solution in a core merge?

**Comment by azaozz** [comment]
I've looked at this a bit: best would be to add another filter to post.php that will allow replacement of all of the editor UI. I'll try to make a patch :)

**Comment by maddisondesigns** [comment]
Why is this being made the default editor when clicking _Add New_? I can understand it defaulting for Posts/Pages that have been edited in Gutenberg, but it shouldn't be the default for ALL new Posts, at least not yet, and not until it's significantly closer to being implemented in core.

How do I go about creating a new post using the traditional TinyMCE Editor? The whole reason Gutenberg is currently in a plugin is so that you can use the existing core features, while trying out the new features. I currently have this running on a site where I do a lot of testing of other core functionality, and now by defaulting the editing experience to Gutenberg you're forcing me to have to constantly deactivate and reactivate the plugin when I want to switch between what I'm testing. This is a really annoying decision!

**Comment by azaozz** [comment]
> Why is this being made the default editor...

Because it is going to be the default WordPress editor :)

> How do I go about creating a new post using the traditional TinyMCE Editor?

There is https://wordpress.org/plugins/classic-editor/ that's going to be released later today. It is meant fur exactly these user cases, even after Gutenberg gets merged in core.

**Comment by pento** [comment]
I don't think the plugin is the right solution here - while Gutenberg is a plugin, at least, people are much more likely to need to switch back to the classic editor due to something not working quite right.

Similar to how we have the "Classic Editor" link in the post list table, I think there's value in having a button that performs the "New Post in Classic Editor" function.

**Comment by afercia** [comment]
> I don't think the plugin is the right solution here - while Gutenberg is a plugin, at least, people are much more likely to need to switch back to the classic editor due to something not working quite right.

I couldn't agree more. Also pointed out during yesterday editor chat that IMHO is a bit too early to make Gutenberg the default editor, especially for the "Add New" link. I still need to be able to create new posts in the classic editor.

Also, what about Custom Post Types? Not all CPTs fill fit with Gutenberg, I guess many need the old `post.php` and `post-new.php` pages.

**Comment by afercia** [comment]
I'd also like to add a change like this should have been discussed in a Trac ticket for visibility 🙂

**Comment by pento** [comment]
> Also pointed out during yesterday editor chat that IMHO is a bit too early to make Gutenberg the default editor, especially for the "Add New" link.

Nah, it's time to live on the edge.

> Also, what about Custom Post Types? 

CPTs that don't have use the editor or don't set `show_in_rest` go to the classic editor, everything else goes to Gutenberg. We can expand those conditions if there are other groups of CPTs that don't play nicely with Gutenberg.

> I'd also like to add a change like this should have been discussed in a Trac ticket for visibility

Not so much, splitting discussion about Gutenberg functionality between Trac and GitHub is a recipe for masses of missed conversations.

**Comment by aduth** [comment]
>CPTs that don't have use the editor or don't set `show_in_rest` go to the classic editor, everything else goes to Gutenberg. We can expand those conditions if there are other groups of CPTs that don't play nicely with Gutenberg.

I couldn't find an associated issue for this, so created #3066.

**Comment by aduth** [comment]
From development perspective, I'd like to be able to switch back and refer to the classic editor for parity comparisons. As long as this is available in one form or another ([even via another plugin](https://github.com/WordPress/gutenberg/issues/2824#issuecomment-337850506)), this is not a concern for me, so long as I'm not forced to do an plugin activation dance any time I'd want to make these references.

**Comment by afercia** [comment]
>> I'd also like to add a change like this should have been discussed in a Trac ticket for visibility

> Not so much, splitting discussion about Gutenberg functionality between Trac and GitHub is a recipe for masses of missed conversations.

I don't see the change to default editor as a "Gutenberg functionality" 🙂 it is something that impacts WordPress and its whole ecosystem and as such should be discussed on Trac.

**Comment by azaozz** [comment]
> I don't think the plugin is the right solution here - while Gutenberg is a plugin, at least, people are much more likely to need to switch back to the classic editor due to something not working quite right.

Exactly, being a "in progress" plugin means it can be disabled if the user doesn't feel like testing it or has other issues :)

> Similar to how we have the "Classic Editor" link in the post list table, I think there's value in having a button that performs the "New Post in Classic Editor" function.

Right. It is a functionality in the Classic Editor plugin too. It can also be tested/refined while Gutenberg is a plugin.

**Comment by azaozz** [comment]
> Also pointed out during yesterday editor chat that IMHO is a bit too early to make Gutenberg the default editor, especially for the "Add New" link.

Why? The Gutenberg plugin is like any other plugin that enhances or replaces the editor. Very similar to the plugin that replaces TinyMCE with CKEditor, https://wordpress.org/plugins/ckeditor-for-wordpress. It's not like we are forcing anybody to use it :)

**Comment by afercia** [comment]
> It's not like we are forcing anybody to use it

You're forcing me on trunk :) not in my day to day work I'm forced to continuously switch it on and off.

**Comment by buzztone** [comment]
I'm not concerned with making Gutenberg the default editor if I install & activate the Gutenberg plugin. I do believe the plugin is now at a suitable place for me to do that.

However I'm still a little confused about how I can get back quickly to using the Classic Editor. I suspect I just need to deactivate the Gutenberg plugin. Is there already some documentation available that can explain this & reassure other slightly confused Gutenberg users?

**Comment by aduth** [comment]
As of #3070 there's now a dropdown menu on the posts list to choose an editor from which to author the post.

![dropdown classic editor](https://user-images.githubusercontent.com/1779930/31794563-babf4ad4-b4f0-11e7-8909-5396379ef161.png)

Hovering a post in the post list and choosing "Classic Editor" will direct you to editing that post in the classic editor.

![hover classic editor](https://user-images.githubusercontent.com/1779930/31794552-b38908d6-b4f0-11e7-9003-3095d1e0da92.png)

**Comment by buzztone** [comment]
@aduth _confusion evaporates and reassurance arrives_

Could be worth adding this explanation to 1.5 release notice.

**Comment by cedon** [comment]
In following up with this, is there a function/etc. that CPT plugin developers can use to force that switch? For example, I am writing a very field heavy CPT plugin that Gutenberg just isn't suitable for as far as I can see.

So rather than forcing my users to use that drop-down each time, is there a way that my plugin could do something like:

`wp_set_editor( 'classic' );`

So that when they add a new post of this CPT, they will automatically get the classic editor.

**Comment by youknowriad** [comment]
@cedon Short answer yes.

With templates and blocks saving to custom fields. We think Gutenberg is suited for field heavy CPTs. The tooling around this is not there yet. 

That said, you can declare that your metaboxes are not compatible with Gutenberg which should redirect automatically to the classic editor. Details here https://wordpress.org/gutenberg/handbook/reference/meta-box/#testing-converting-and-maintaining-existing-meta-boxes

**Comment by cedon** [comment]
My CPT basically looks like a health questionnaire you'd get at the doctor's office though. That's where my concern is. If I saw something in Gutenberg that could do it and that I could reference, I'd gladly update the plugin since it's at the state where I am now starting to construct metaboxes and such.

I do think that something should be added outside of `add_meta_box()` though. Either an explicit function like my hypothetical `wp_set_editor()` or an optional parameter for `register_post_type()` that could be part of the `$args` array often used.

**Comment by ambrix** [comment]
Last Wordpress update install Gutenberg, so I can’t use tinyMCE anymore. How I can switch to my plugin tinyMCE Advanced? Thx
