### ISSUE TITLE
Reusable blocks: changes in a draft post not possible

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#28295]
I'm not sure I fully understand how reusable blocks are supposed to work, but something seems to have changed recently (#27887 maybe?) and it's now possible to modify a reusable block from inside the editor.

If I'm working on a draft post the only way to save changes to a reusable block is by publishing.

Steps:
- Start a new post, type a few paragraphs, and then select and convert to a reusable block
![image](https://user-images.githubusercontent.com/1277682/104938922-a9e99480-59a7-11eb-9527-605cd3e1309a.png)
- Save this as a draft
- Make changes to the reusable block (it's not obvious you're editing a reusable block - there's no indicator). Note that the publish button now has a mysterious blue dot on it. I'm not sure what means. Also note that the 'save draft' is not highlighted - I can't save my changes
![image](https://user-images.githubusercontent.com/1277682/104939050-d4d3e880-59a7-11eb-9555-98c9d85858a6.png)
- Make some changes outside the reusable block. Note that I can now save my changes so I save as draft
![image](https://user-images.githubusercontent.com/1277682/104939111-ea491280-59a7-11eb-84a5-eab6b6c7e3a7.png)
- The blue dot is still present! I don't want to publish, so I reload the page (ignoring the 'Changes that you made may not be saved' - I've just saved it)
- My changes in the reusable block have been lost

I suspect the blue dot indicates that it needs to save the reusable block, but it's a fairly vague indicator. It would seem more natural that changes in the reusable blocks are reflected in the `save draft` indicator just like all changes.

Gutenberg 9.7.3

**Comment by youknowriad** [comment]
Reusable blocks are global which means "save draft" is not a good action for them because you can be editing a published reusable block already inside a draft post. That's why for now they are tied to the "publish/update" flow. 

I understand that it's not always easy to understand and improvements here are definitely needed but It is a very difficult UX challenge.

**Comment by johngodley** [comment]
Sure, I didn't mean for this to come across as critical, and I appreciate the difficulty involved.

What I described above is certainly me intentionally doing the wrong thing, and wanting to track that.

Would including reusable blocks in the save draft flow be an option? I don't know what the consequences of doing that are, but it seems reasonable that if you're editing a global object the data gets saved even in a draft.

**Comment by youknowriad** [comment]
I didn't read this as critical, I was just trying to add some context :) 

> Would including reusable blocks in the save draft flow be an option?

That would be difficult:

 - Right now, you can't really use a "draft" reusable block in a post. That's not something we ever supported.
 - If you create a new post, use an existing reusable block inside it, tweak the reusable block content.; What do you expect of the "save draft" action? you can't really save the reusable block changes as draft, it's a published one that might already be used in other posts, you can't update the published reusable block either because the intent of the post author is to "save draft".

The truth I personally don't know the solutions here and would love some creative design thinking :)

**Comment by annezazu** [comment]
As a heads up, this was brought up [in a trac issue here ](https://core.trac.wordpress.org/ticket/52767) around the 5.7 release as a point of confusion. I also want to note that this relates to a wider discussion around multi-entity saving happening here https://github.com/WordPress/gutenberg/issues/29577 I agree this is going to require some creative design thinking especially with an FSE future!

**Comment by kimclow** [comment]
Just noting that this issue popped up this past week for us while working on some new pages. 

If I have a reusable block on a draft page - any changes I make in WP Admin don't save after the block has been made reusable. 
**There is a workaround: if you navigate to the Manage Reusable block on the Blocks drop-down, then the changes save. But they do not save while working on the actual page.** 

I believe it's linked to the "Save Draft" button not actually saving the edits within a reusable block. If you watch my screen recording, the page isn't "Saveable" after editing the block. And this aligns with the discussion above. 

To replicate: 
1. Start a post or page and add a few blocks
2. Make these blocks reusable 
3. Do not publish this page or post, but save it as a draft. 
4. Start a new post or page, and insert the reusable block you have just created 
5. Make an edit to the block 
6. Save draft 
7. Preview either of the two draft pages you've included the reusable block on; neither of them will show the updated block. They will show the original block from step 2. 

Here's a screen recording: https://d.pr/v/QXsAPc 
 
WordPress current version: 6.2
Theme: Meraki however this issue is also happening on [Jetpack.com](http://jetpack.com/) which uses a custom theme. 
Browser: Version 112.0.5615.137 (Official Build) (arm64) 

Device: MacBook Pro (16-inch, 2021) 
Running: Monterey 12.6.1

**Comment by youknowriad** [comment]
It seems the flow has changed a bit with two important changes that I believe make the experience better than what it used to be:

 1- You have to click "edit original" to actually go into a separate focus mode to edit the pattern. This makes it clear that you have to "save" the pattern before returning to the post.
 2- If you didn't save the pattern change and you return to the post, you can save as "draft" but the main button says "save" and asks you to save the pattern changes.

So I think the behavior is decent. I'm closing the issue for now.
