### ISSUE TITLE
Site Editor: Template Part slugs do not match the title

### ISSUE THREAD

**Issue by mattwiebe** [WordPress/gutenberg#28302]
## Description

When creating a new Template Part in the Site Editor, the generated slug is always `template-part`, followed by increasing numbers, `-2`, `-3`, etc, no matter the title given. 

This is a problem because choosing "Select Existing" when 

## Step-by-step reproduction instructions

1. Open Site Editor
2. Add a Template Part block
3. Choose "New template part"
4. Give your template part a name (where it says "Untitled Template Part")
5. Press the blue "Update Design" button in the upper right
6. Navigate to `wp-admin/edit.php?post_type=template_part`
7. See that all of the slugs are `template-part(-n)`

## Expected behaviour
Slugs are generated from the title.

## Actual behaviour
Slugs are all `template-part(-n)`

<img width="412" alt="image" src="https://user-images.githubusercontent.com/195089/104957520-ef03cb80-5993-11eb-9261-3e2d98d85730.png">

## WordPress information
- WordPress version: 5.6
- Gutenberg version: 9.8.0-rc.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: Desktop
- Operating system: macOS 11.1
- Browser: Chrome 87.0.4280.141

**Comment by david-szabo97** [comment]
Looks like we are using a fix slug 🤔 

https://github.com/WordPress/gutenberg/blob/3458607659e7eaefa0de93f7c36702f6b6afce6b/packages/block-library/src/template-part/edit/placeholder/index.js#L28

**Comment by Addison-Stavlo** [comment]
> we never had slugs based on the title I guess.

Previously the slug and titled were both created with "Untitled Template Part" / `untitled-template-part`, and whenever the title was updated the slug would be updated as well.  Now that the theme+slug combo is required to be unique the slug is no longer updated along with the title.  This allows users to rename them easily without the unique restriction.  However, it also makes it so we need to be careful about always showing title instead of slug in the editor UI.

**Comment by Addison-Stavlo** [comment]
Closing with #28330 - feel free to re-open if there is still an issue.
