### ISSUE TITLE
Query Block: not rendering on front-end of site in page content

### ISSUE THREAD

**Issue by ianstewart** [WordPress/gutenberg#28334]
The query block appears to fail to render on the front-end of a site in page content as seen in the screenshot below, with the query block in page content on the left, and the published front-end result on the right.

![image](https://user-images.githubusercontent.com/545779/105094520-0319fc80-5a6a-11eb-92db-6b79e68e58a6.png)

- WordPress 5.6
- Gutenberg 9.7.4
- Theme: TT1 Blocks (also tested with "Q" theme)

**Comment by ntsekouras** [comment]
Hey @ianstewart - The problem here lies to the `inherit query from URL` option that defaults to `true` and therefore in a page/post context doesn't work as expected because the $wp_query is about the single page.

Can you try setting the above mentioned option to false, so as to close this issue?

I know this is confusing and easy to miss and I've made some explorations on detecting the FSE and page/post context, but needs more thinking and work on context detection..

**Comment by gziolo** [comment]
There is also this question of whether the query detected from the URL should only trigger filtering when it's one of the pages that display a list of posts. In the case of the single page type, it could use all possible posts by default — just an idea to explore. Finding sensible defaults is very important here.

I would like to hear thoughts from more people building FSE themes: @scruffian, @aristath, @carolinan.

**Comment by MaggieCabrera** [comment]
> There is also this question of whether the query detected from the URL should only trigger filtering when it's one of the pages that display a list of posts. In the case of the single page type, it could use all possible posts by default — just an idea to explore. Finding sensible defaults is very important here.

I agree with that perception, it would be what I expected as a theme developer

**Comment by scruffian** [comment]
This caught me out too. I think that when "inherit query from URL" is turned on, the other options should be disabled. I also wonder if it should move to the block toolbar, so that its more obvious...

**Comment by aristath** [comment]
The problem here is the empty `post_type` argument in the query. Since it's empty, `get_posts()` defaults to `post` and so it doesn't work for pages. 
For the sake of an example, I created an FSE theme with nothing but an `index.html` template in it. In that template I added a query block and nothing else. On the frontend: It worked for archives showing multiple posts. It worked for single posts by showing that single post. But on pages it was empty because it was a different post-type.

Currently debugging this to see if there's an easy way to define the post-type :+1:

**Comment by aristath** [comment]
PR in https://github.com/WordPress/gutenberg/pull/28351

**Comment by aristath** [comment]
> There is also this question of whether the query detected from the URL should only trigger filtering when it's one of the pages that display a list of posts. In the case of the single page type, it could use all possible posts by default — just an idea to explore. Finding sensible defaults is very important here.

I'd expect the exact opposite... If I add a query block and set it to inherit the global query, then I expect it to inherit the global query. When viewing a single post, the global query contains that single post/page, so that's what I'd expect it to show by default.
Just like in a classic theme I could add an `index.php` file with a loop and have it work properly everywhere, showing the content for whatever page I'm on - regardless of whether it's an archive or a page, post etc.

**Comment by gziolo** [comment]
> Just like in a classic theme I could add an `index.php` file with a loop and have it work properly everywhere, showing the content for whatever page I'm on - regardless of whether it's an archive or a page, post etc.

Thank you for sharing this use case. I'm perfectly fine with preserving the same behavior as long as it's predictable and works correctly. That makes this issue a bug then.
