### ISSUE TITLE
When an empty legacy widget is added the widget area can't be saved

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#28561]
## Steps to reproduce:

- have the current master of Gutenberg
- have a default WordPress install with no extra plugins
- go to Appearance -> Widgets
- at the end of a widget area add a legacy widget block
  - the legacy widget block should say there are no available widgets
- save the page
- see the error

## Screenshots

https://user-images.githubusercontent.com/107534/106173222-60b1f580-619c-11eb-98e9-2e95a2f28553.mp4

**Comment by tellthemachines** [comment]
This looks like the same error as #31249

**Comment by noisysocks** [comment]
We can fix this the same way we did in the Customzier by converting the Legacy Widget block to a `block` widget when it is empty.

https://github.com/WordPress/gutenberg/blob/cc2e0782b53e55ae3c4c3ae81b5ec3e47ddbc1a5/packages/customize-widgets/src/components/sidebar-block-editor/use-sidebar-block-editor.js#L17-L21

While we're at it, we should move `blockToWidget` and `widgetToBlock` to `@wordpress/widgets` so that we're not defining the same functions in both `edit-widgets` and `customize-widgets`.

**Comment by noisysocks** [comment]
> While we're at it, we should move `blockToWidget` and `widgetToBlock` to `@wordpress/widgets` so that we're not defining the same functions in both `edit-widgets` and `customize-widgets`.

Hm, can't really do this as they're different implementations. In `@wordpress/customize-widgets` we are mapping from blocks ↔ how widgets are represented in the Customizer. In `@wordpress/edit-widgets` we are mapping form blocks ↔ how widgets are represented in the REST API. They aren't the same unfortunately.
