### ISSUE TITLE
Gallery Block: Edit/remove buttons cover move image buttons

### ISSUE THREAD

**Issue by Copons** [WordPress/gutenberg#28600]
## Description

If the gallery has many (actual number depends on the images size/ratio) columns, the edit/remove buttons cover the move image buttons.

Originally reported in https://github.com/Automattic/wp-calypso/issues/49282

## Step-by-step reproduction instructions

- Edit a post and enter a Gallery block.
- Choose (or upload) around 6-7 images (again, number depends on the chosen images), and insert the gallery in the post content.
- Adjust the block to display the maximum amount of columns allowed.
- Click on one of the images.

## Expected behaviour

To be able to click on the move image buttons.

## Actual behaviour

The edit/remove buttons cover the move image buttons.

## Screenshots or screen recording (optional)

| Three Columns (working) | Four Columns (broken) |
| - | - |
| <img width="631" alt="Screenshot 2021-01-29 at 16 16 53" src="https://user-images.githubusercontent.com/2070010/106300157-05d8d680-624e-11eb-8e6a-3990d342a749.png"> | <img width="630" alt="Screenshot 2021-01-29 at 16 17 09" src="https://user-images.githubusercontent.com/2070010/106300170-096c5d80-624e-11eb-83f6-7125e30579a0.png"> |

## WordPress information
- WordPress version: 5.6
- Gutenberg version: 9.8
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: MacOS 10.15.7 and 11.1
- Browser: Chrome 87.0 and 88.0

**Comment by mtias** [comment]
The best way to fix this will be this refactor https://github.com/WordPress/gutenberg/pull/25940

**Comment by glendaviesnz** [comment]
@Copons the Gallery refactor has been merged. It is still behind an experimental flag until mid September due to some mobile app compat issues, but if you enable the gallery experimental flag and add a new gallery this issues is resolved:

![move](https://user-images.githubusercontent.com/3629020/131267808-b6aa2486-932b-4676-9c0d-8a39024152ef.gif)

The old gallery format is still supported, ie. any existing galleries will still display in the editor in the old format, but there will be an option to migrate them some time in the near future, so probably not worth spending an time resolving this issue for the old format ... so are you happy to close this issue now?

**Comment by mtias** [comment]
Yes, we can close this now.
