### ISSUE TITLE
Buttons Block: Extra vertical space between buttons in the Editor

### ISSUE THREAD

**Issue by alaczek** [WordPress/gutenberg#28647]
## Description
I noticed that when I insert Buttons block and set the buttons to 100% width, there's large vertical spacing between the buttons, to accommodate the block appender. This causes the editor view to be different than the preview. This behaviour is also different than if no width is set on the buttons - in that case no extra appenders appear between the buttons. This might be the intended behavior, but I found those differences confusing.

## Step-by-step reproduction instructions
1. Create a new post or a page.
2. Add Buttons block with three to four buttons inside.
3. Set each button to 100% width, so that each button sits on a separate line.
4. Note that large vertical space between the buttons. If you hover over that space, a block appender will appear.
5. Preview the site. Note that the spacing between the buttons is much smaller.
6. Go back to the editor. De-select the width setting for each button, so that they all appear on the same line. Note the narrow spacing between buttons, and no appender when hovering over the spaces.
7. Preview the site and note that the spacing between the buttons in the editor and in the preview are the same.

## Expected behaviour
I didn't expect the extra vertical space in the editor when the button width is set to 100%. 

## Actual behaviour
I expected the spacing between the buttons to be the same in the preview and in the editor. I realize this will depend on the theme as well, but before this can be tackled in the theme, the issue of extra appenders needs to be hashed out.

## Screenshots or screen recording (optional)
Editor view - large vertical spacing between buttons:
![image](https://user-images.githubusercontent.com/4550351/106548496-34fb8a80-6563-11eb-8cca-6f408d11786a.png)

Preview - much smaller vertical spacing:
![image](https://user-images.githubusercontent.com/4550351/106548543-4ba1e180-6563-11eb-8553-975d88384f03.png)

Here's a short video: https://www.loom.com/share/0f138caac58147a6ab0dc9564e950c9f

## WordPress information
- WordPress version: 5.6.0
- Gutenberg version: 9.8.3
- Are all plugins except Gutenberg deactivated? Yes (Jetpack)
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes (TT1)

## Device information
- Device: Desktop
- Operating system: macOS 10.15.7
- Browser: Chrome 87.0

**Comment by paaljoachim** [comment]
Thank you for creating the issue @alaczek !
I am also seeing this using Twenty Twenty One, Gutenberg plugin 10, and WordPress 5.7 beta 3.

Backend Twenty Twenty One:
![Screen Shot 2021-02-18 at 13 09 24](https://user-images.githubusercontent.com/5323259/108355101-ac2f5080-71ea-11eb-8925-1052f448607e.png)

Frontend:
![Screen Shot 2021-02-18 at 13 09 39](https://user-images.githubusercontent.com/5323259/108355131-b3565e80-71ea-11eb-88dd-38e3f75122d3.png)



@tellthemachines @carolinan @mkaz

**Comment by paaljoachim** [comment]
I did an inspect element on the backend and noticed this.

![Screen Shot 2021-02-25 at 22 28 40](https://user-images.githubusercontent.com/5323259/109220118-d4095000-77b8-11eb-9aad-b2ea51ab6d40.png)

```
.editor-styles-wrapper [data-block] {
    margin-top: var(--global--spacing-vertical);
    margin-bottom: var(--global--spacing-vertical);
}
```

These margins should be collapsed making the backend look closer to the frontend.

Commenting out the above margins.

![Screen Shot 2021-02-25 at 22 30 55](https://user-images.githubusercontent.com/5323259/109220393-29456180-77b9-11eb-9930-5b8b5c1a3d0f.png)

**Comment by ryelle** [comment]
It turns out this is also the case with the default block-library styles (ex, Twenty Fifteen) - margins don't collapse between buttons in the editor, so each space between buttons has 2x margin, meanwhile on the frontend the margin is only applied to the bottom.

<img width="832" alt="Screen Shot 2021-02-25 at 7 04 37 PM" src="https://user-images.githubusercontent.com/541093/109235769-50da0100-779c-11eb-9bc4-922e44280860.png">

<img width="687" alt="Screen Shot 2021-02-25 at 7 24 07 PM" src="https://user-images.githubusercontent.com/541093/109237160-0b6b0300-779f-11eb-9e62-eacc71ba3320.png">

Could the margin top [set here](https://github.com/WordPress/gutenberg/blob/a0ec0232a06b2dd20ac033bf04ff56496cb948a6/packages/block-library/src/buttons/editor.scss#L13) be removed or set to 0, maybe? Twenty Twenty & Twenty Twenty-One will still need to update too, since they set their own margins.

**Comment by jasmussen** [comment]
Is this issue fixed by the new block spacing (gap) control?

<img width="1392" alt="Screenshot 2022-09-30 at 13 41 59" src="https://user-images.githubusercontent.com/1204802/193262228-77280b1d-1110-4e50-802f-f5140c6bb4ab.png">

**Comment by paaljoachim** [comment]
Testing using 
Twenty Twenty Two.
WordPress 6.0.2
Gutenberg plugin 14.2

Testing instructions from original post
1- Create a new post or a page.
2- Add Buttons block with three to four buttons inside.
3- Set each button to 100% width, so that each button sits on a separate line.
4- Note that large vertical space between the buttons. If you hover over that space, a block appender will appear.

Getting the appender on hover in between the buttons is kind of tricky. It looks like I need to have the parent Buttons block selected for the appender on hover to show up.

![Screenshot 2022-10-06 at 11 06 17](https://user-images.githubusercontent.com/5323259/194272691-0f79a60c-25bd-4f5a-9ac5-df7a812f4b48.jpg)






5- Preview the site. Note that the spacing between the buttons is much smaller.

I see an identical spacing on the frontend.
![Screenshot 2022-10-06 at 10 53 44](https://user-images.githubusercontent.com/5323259/194268001-d489862d-4ef5-4e8e-add1-c58a7ee22d2b.jpg)

6- Go back to the editor. De-select the width setting for each button, so that they all appear on the same line. Note the narrow spacing between buttons, and no appender when hovering over the spaces.

### I am not able to get the appender on hover to be seen. Or it might just be difficult to get to show.

No appender on hover between the buttons.
![Screenshot 2022-10-06 at 11 01 36](https://user-images.githubusercontent.com/5323259/194270665-808033f8-2cf8-4eb0-a2e3-d067ff5b0ad9.jpg)


8- Preview the site and note that the spacing between the buttons in the editor and in the preview are the same.

Yes. I see the same identical buttons on the backend and frontend.

**Comment by paaljoachim** [comment]
From what I am seeing the appender in between the buttons is having a hard time showing up and could be fixed.
We should close this issue and open a new issue in relation to getting a more stable appender in place which will easier show up between the buttons.

**Comment by jasmussen** [comment]
Getting the appender to show between buttons in small-gap situations feels like a separate issue to being able to controlling the gap, right?

**Comment by paaljoachim** [comment]
Yes. Here is the new issue for the in between appender: https://github.com/WordPress/gutenberg/issues/44728

Closing this issue.
