### ISSUE TITLE
Handbook: RadioControl example screenshot does not show RadioControl

### ISSUE THREAD

**Issue by benlk** [WordPress/gutenberg#28763]
## Description
The RadioControl documentation at https://developer.wordpress.org/block-editor/components/radio-control/ shows the following example screenshot:

![](https://make.wordpress.org/design/files/2018/11/radio-usage-do.png)

This is not a RadioControl; it's something custom: https://github.com/WordPress/gutenberg/blob/004a32ec09d5b789be694d85725fe49cca385f08/packages/editor/src/components/post-visibility/index.js#L94-L124

The key difference that led me to notice and file this bug is that the image shows labels with a header text followed by a description. While this is doable by passing HTML into the label property of each option, it's not behavior that is described on the page, and the example code shown results in something that looks different.

## Step-by-step reproduction instructions

1. Visit https://developer.wordpress.org/block-editor/components/radio-control/

## Expected behaviour
The RadioControl docs should use a RadioControl as an example.

## Actual behaviour
The RadioControl docs screenshot a component that is not a RadioControl.

**Comment by dhruvkb** [comment]
@benlk while I agree with your point that the screenshots are not using the `RadioControl` component, I believe the purpose of the screenshot is not to show a visually accurate `RadioControl` component but to illustrate when the component should be used instead of checkboxes. 

I think they serve this purpose very well. The screenshot at the very top of the article depicts how the `RadioControl` component looks.

**Comment by benlk** [comment]
The reason I filed this bug was because I was trying to reproduce the screenshot's "labels with a header text followed by a description" behavior with a `RadioControl`. The documentation implies that it is possible: the post-visibility control screenshots are used in the documentation for an example of when to use a `RadioControl`, and they show a component with radio buttons and the more-complex labels. It seems like a logical inference that this is a `RadioControl`, and that everything in that screenshot can be achieved with a `RadioControl`. But it's not possible to do with a `RadioControl`, and I lost two hours trying to figure out how to get a `RadioControl` to do the thing which is shown in the `RadioControl` docs.

If there are actual `RadioControl` examples in Gutenberg or in core WordPress, then they would be better than this screenshot which displays behavior that is not available in `RadioControl`.

**Comment by lmartins** [comment]
It does illustrate how the component should be used, but it also sends people on wild goose chases to understand what they are missing in order to have help information next to each option. Having the docs giving a more accurate representation of how the component seems like a good idea.

**Comment by ryanwelcher** [comment]
@krokodok is going to have a look at getting these updated.

**Comment by krokodok** [comment]
Here are two new screenshots that hopefully cause less confusion. The code for the RadioControl is directly taken from the Example section on the handbook page. The CheckboxControls are built to look similar, to make clear the important difference at first sight:

![radio-usage-do](https://user-images.githubusercontent.com/10128264/228872949-ae66ec0d-f9c9-4579-83df-c6e489b9a55d.png)
![radio-usage-dont](https://user-images.githubusercontent.com/10128264/228872964-02c91d98-3714-45ae-a47f-9b6ef8c51314.png)

**Comment by krokodok** [comment]
Could somebody update these please in the manual since I don't have the needed rights for that?

**Comment by mirka** [comment]
@krokodok Would you like to submit a PR for this? [This](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/radio-control/README.md) is the markdown file in question, and you can use the GitHub file links (`https://user-images.githubusercontent.com/`~) to the images you uploaded here already. Those GitHub files aren't easily removed once uploaded, so we can consider them sufficiently stable.

**Comment by krokodok** [comment]
Adding these two updated screenshots here, because I don't know how to host them otherwise on GitHub. 😅 PR is coming ASAP!

**Comment by krokodok** [comment]
Adding these two updated screenshots here, because I don't know how to host them otherwise on GitHub. 😅 PR is coming ASAP!
![dont](https://github.com/WordPress/gutenberg/assets/10128264/141de08b-f616-48d6-a329-56d5c1d3ea6e)
![do](https://github.com/WordPress/gutenberg/assets/10128264/9700dab5-9809-4152-82d6-08157a433b4e)

**Comment by krokodok** [comment]
@mirka Thank you for pushing me in the right direction to solve this. I created a draft PR here: https://github.com/WordPress/gutenberg/pull/60024

The PR is a draft because I created new screenshots, but can't "host" them anymore inside a GitHub comment as previously. So I would really appreciate it if someone with access to make.wordpress.org could host the files on there. The situation is explained in detail in the draft PR.
