### ISSUE TITLE
Wp-block-image: Breaks natural CSS flow on floating alignment properties

### ISSUE THREAD

**Issue by Intervik** [WordPress/gutenberg#28820]
## What problem does this address?
wp-block-image has no markup as a parent to floating image such as alignleft. Top level elements should NEVER break the CSS flow. `<div><figure class="alignleft"></figure></div>` is wrong. Properties like `alignleft + p { margin-top: } or alignleft ~ h2 { clear: both; } `etc etc not working.

## What is your proposed solution?
Add classname to top level element such as has-float or attribute data-align=left or whatever. Or better, keep figure element as top level element.

**Comment by tellthemachines** [comment]
Ideally the `figure` should be the top-level element.

**Comment by AtrumGeost** [comment]
I got this same issue. Noticed that when the Image Block is centered the <figure> tag is gone:

![Screen Shot on 2021-05-06 at 11-17-01](https://user-images.githubusercontent.com/3696121/117331826-be6d7200-ae5c-11eb-98f8-0cb728fbc8e9.png)

On the screenshot, you'll notice the second and third image don't have the <figure> element because they are aligned to the center.

**Comment by andrewstaffell** [comment]
This is basically the same issue as #33385.

**Comment by tellthemachines** [comment]
Closing as this has now been fixed, as per discussion in #33385.
