### ISSUE TITLE
Overview of experimental settings? Opening up additional settings.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#28987]
@jasmussen Joen's issue here got me thinking: https://github.com/WordPress/gutenberg/issues/28963 that we should go through the various experimental settings there themes need to opt-in to use them.

Adding an opt-in makes it harder to discover. As theme creators will need to continually discover which settings they need to opt-in to.

Let's look through the experimental settings and see which we would like open up for a wider usage. Thanks.

**Comment by chthonic-ds** [comment]
As a theme creator I'd prefer opt-out to become the default approach. When new features are opt-in I don't need to continually discover which settings I need to opt out of.

**Comment by carolinan** [comment]
As a theme author, I would much rather discover new features in a dev note or blog post than suddenly having it enabled in my themes without me knowing it.

**Comment by chthonic-ds** [comment]
I also prefer opt-in to be the default approach and to be alerted in a dev note. I write and manage a lot of one-off custom themes and, in the age of the block editor, it's an ongoing battle to keep the editor view tightly coupled to what is useful for each theme.

**Comment by paaljoachim** [comment]
We also need a Block Editor doc for experimental settings, so anyone can check the doc to see which settings are experimental. Then select which setting to add to a theme. 
@annezazu @mkaz

**Comment by jasmussen** [comment]
I'm not sure it's productive to discuss in the abstract the approach to opt in or opt out, because there's no context to help make a decision.

#28963 on the other hand is specific to the Cover block, and more precisely, the unit control. I would think it valid for themes to want to opt out/in to allowing cover block resizing, but since you can already use VW units by using the fullscreen button, it feels more like a bug that you can't use the unit selector unless a theme opts in.

**Comment by paaljoachim** [comment]
I will go ahead and close this issue. If someone feels it is constructive to reopen let me know and I will open the issue again.
