### ISSUE TITLE
What tools can be used?

### ISSUE THREAD

**Issue by BE-Webdesign** [WordPress/gutenberg#29]
Hi!

I was curious if there were any tooling limitations surrounding this project.  I would like to be able to use es6 stuff, but wasn't sure if adding a build process, etc. was what this repository was all about.  If a node.js build process, is not permitted, or if there is a future build process in mind, it would be nice to know what can be used or what potentially lies ahead.  On top of build tools ( or lack thereof ), what unit testing stuff can be used?

No worries if this is not on the agenda at this time, but I would like to help out and having a bit of direction on what tools you like to use can help guide my contributions.  For now I will do non es6, but it could get ugly 😄 

Thank you!

**Comment by mtias** [comment]
Thanks for joining!

We had to revert a spread operator before due to browser support: https://github.com/WordPress/gutenberg/commit/08fe7d501c3c13410d81ad59ad597710257b6a0a

We can bring some building process if we really feel constrained, though the main goal for the UI prototype is just to have an interactive mockup to serve as the basis for the real thing later on. So consider [the code in blocks.js](https://github.com/WordPress/gutenberg/blob/master/blocks.js) to be throwaway. We should start adding more technical prototypes soon and we should definitely polish that more as we move along.

**Comment by mtias** [comment]
@BE-Webdesign as we put our attention on more technical prototypes we'll have build processes and the ability to use ES6, etc.
