### ISSUE TITLE
Run the build-plugin workflow for pull requests labelled as Drafts

### ISSUE THREAD

**Issue by skorasaurus** [WordPress/gutenberg#29088]
## What problem does this address?

The Github workflow that [Builds a pull request as a zip file](https://github.com/WordPress/gutenberg/pull/26746) is awesome addition to the troubleshooting process and has saved time for me and others already.
It creates a ZIP of the gutenberg plugin, already built, so you can just unzip that file into your plugins directory and use that PR in an environment without having to setup git or do repetitive actions (fetching, pulling, building, etc) 

However, that Github action/workflow does not run for pull requests that are labelled as drafts. 

## What is your proposed solution?

If it's possible to also run the workflow for draft PRs that would be cool; I do not know what kind of overhead this adds or if it's even possible. 
[The github workflow ](https://github.com/WordPress/gutenberg/blob/master/.github/workflows/build-plugin-zip.yml) doesn't specify anything that I can see about omitting drafts. 

If there's no known reason why this was turned off (please respond here if you know why it was turned off for drafts), I'll try to look into this more at https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

**Comment by ockham** [comment]
Hey @skorasaurus :wave: 

Are you sure that all draft PRs are affected by this? I have a few [PRs](https://github.com/WordPress/gutenberg/pulls/ockham) in draft state, and the workflow seems to be running for them.

It is true that there are draft PRs for which the workflow _isn't_ run, such as https://github.com/WordPress/gutenberg/pull/28891 (as of this writing) -- but note that most other workflows aren't run for that one either. I think that that happens if the PR's branch needs a rebase. The problem with draft PRs is that GitHub doesn't add its usual "needs a rebase" banner at the bottom of the PR -- making the problem harder to spot.

**Comment by skorasaurus** [comment]
Thanks for the explanation, https://github.com/WordPress/gutenberg/pull/28891 was the specific one that I had in mind when I wrote this issue :D 

I thought I found one more PR that this occurred with; but now I can't find it... 

I guess then I can close this since this is mostly resolved; but if you want to reopen to find (with certainty) out why some do not; you can.
