### ISSUE TITLE
Improve responsiveness of the navigation screen

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#29100]
Since the [design iteration of the navigation screen](https://github.com/WordPress/gutenberg/pull/28675) was merged, there hasn't be much discussion of how these changes should work responsively.

There most notable issue is that the sidebar squishes content:
<img width="391" alt="Screenshot 2021-02-18 at 1 07 00 pm" src="https://user-images.githubusercontent.com/677833/108308255-6d999600-71ea-11eb-9b72-cb8021b11c8a.png">

So potentially there needs to be a way to let users open and close the sidebar on mobile breakpoints, and it should float rather than being inline.

**Comment by draganescu** [comment]
Related #28875

**Comment by talldan** [comment]
This should be improved quite a bit by #30013.

**Comment by javierarce** [comment]
Another responsive-related issue here: [Navigation screen: snackbar component overflows in mobile #31182](https://github.com/WordPress/gutenberg/issues/31182)

**Comment by javierarce** [comment]
Another issue for the responsive view: [Navigation Screen: add padding around the canvas in mobile view #31543](https://github.com/WordPress/gutenberg/issues/31543)

**Comment by kathrynwp** [comment]
Closing this issue due to the Navigation Screen project being moved to [an inactive status on the feature projects page](https://make.wordpress.org/core/features/) in coordination with the project leads. (The developer documentation in the initial post are no longer accessible)

If this work is picked back up, issues can be revisited and reopened as needed. Thanks for pitching in on this early feature so the wider WordPress project could benefit from the lessons learned!
