### ISSUE TITLE
Auto save wipes undo levels

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#2915]
## Issue Overview
When auto saving finishes, undo levels are gone.

## Steps to Reproduce (for bugs)
Open the demo content. Make an edit and select another block so the change is updated in the state. Wait for auto save. When it finishes, the undo and redo buttons are disabled (the levels are gone).

## Expected Behavior
Auto save should not affect undo levels.

**Comment by iseulde** [comment]
See:
https://github.com/WordPress/gutenberg/blob/v1.3.0/editor/effects.js#L65
https://github.com/WordPress/gutenberg/blob/v1.3.0/editor/reducer.js#L237
https://github.com/WordPress/gutenberg/blob/v1.3.0/editor/utils/undoable-reducer.js#L54

@aduth Any idea why we would need to reset these levels at all?

**Comment by aduth** [comment]
The reset was implemented prior to autosave, so if I recall correctly, the thought was that since saving was a very intentional action, it would make sense for undo history to reset to that time as the "clean slate" point.

There may also have been a consideration to avoid excessive memory usage by keeping around a very long history of state. An original implementation of the undoable reducer had included a "max history length" feature around this worry, but was later dropped as premature optimization.

In all, I think it's probably a good idea (and even a simplification) to drop the undo resets.
