### ISSUE TITLE
Undo level present on load

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#2916]
## Issue Overview
When the editor finished loading, an undo level is already present, even though there's nothing to undo yet.

**Comment by aduth** [comment]
Related to https://github.com/WordPress/gutenberg/issues/2915#issuecomment-334943404, this is partly related to the reason for reset actions, which is that since undo history is tracked for any action causing a change in the undoable reducer value, we need to make sure that initialization actions occurring on page load are not reflected as changed through Undo, either by avoiding changes in state, or assigning the clean state point via an action ("RESET_POST").
