### ISSUE TITLE
Site Editor: template part border disappears when hovering over nested blocks

### ISSUE THREAD

**Issue by vindl** [WordPress/gutenberg#29258]
Whenever we hover over a template part a helpful border appears to help delineate that area from the rest of the page. However it's only shown when hovering over empty spaces within template part. As soon as you hover over one of the nested blocks this border disappears.

Correct me if I'm wrong but I don't think this is the expected behavior. The border should disappear only after nested block is selected.

**Comment by Addison-Stavlo** [comment]
cc @jameskoster - Is this expected or do you think there should always be a border around the template part as well when a child is hovered (both child and parent template part having the hover border triggered at the same time)?

**Comment by jeyip** [comment]
The behavior was implemented intentionally.

“The desired effect in the Site Editor is that only the block being hovered has an outline.” (from this [comment](https://href.li/?https://github.com/WordPress/gutenberg/pull/28715#issuecomment-773192877))

In other words, we designed the hover state in such a way that we only expect one block to be outlined at any given time. There’s good news though! If we prefer it, I’m fairly confident that we could quickly modify template part block behavior so that it shows borders, even when nested blocks are hovered.

**Comment by jameskoster** [comment]
+1 what @jeyip said. When more than one hover-outline is visible at once things gets very visually noisy, and clarity around which block will be selected on click is reduced.

**Comment by vindl** [comment]
cc @simison since we were involved in a similar discussion recently and your expectation was that both blocks should be outlined.

**Comment by Addison-Stavlo** [comment]
> and clarity around which block will be selected on click is reduced.

Perhaps a different border style (lighter, thinner, etc.) may serve a purpose for the parent template part in this circumstance?

Alternatively IIRC there are some explorations around requiring the user to select the template part to be able to edit its content, I would assume that would also serve as a separate potential solution for this same ux concern of "how do i know this hovered thing with a border does/doesn't belong to a template part". 🤔

**Comment by jameskoster** [comment]
The hover interaction discussed here is supposed to provide unmistakable clarity in regards to which block will be selected on click. If we start outlining multiple blocks on hover the waters are muddied. What is the benefit there? If it is to understand the relationship between parent / child block, I would argue that the fact we outline the parent of the _selected_ block is adequate.

As we're learning in #28637, getting these outlines right is going to be an exercise in finesse. "Less is more" seems to be a sensible approach to begin with.

> Alternatively IIRC there are some explorations around requiring the user to select the template part to be able to edit its content

Personally I think this could be the way to go, but it still needs some exploration. I intend to look into an 'mvp' for reusable blocks very soon. If we feel that works well then we can cross-pollinate the pattern to template parts and bypass this issue altogether :D

**Comment by simison** [comment]
Yeah, I agree with @jameskoster on this specifically:

> When more than one hover-outline is visible at once things gets very visually noisy, and clarity around which block will be selected on click is reduced.

There are two things being mixed up here:
- "I know what block I will choose when I click on point at the screen"
- "I know which template part the block I'm hovering belongs to"

Since the _only_ visual cue for the template part currently is the hover border, I wrote my comment about hover-borders. But if you just fix that by showing both identical-looking hover borders simultaneously, the need for knowing what I click becomes a problem as Jay says.

> Alternatively IIRC there are some explorations around requiring the user to select the template part to be able to edit its content

Yep, I think something along those lines could solve it. Other ones being different visual cues used for indicating template areas on hover, for example, opacity changes for other templates, different-looking borders, background color changes, etc.

Another very related problem I had was that "just hovering past text, on empty area" doesn't work for choosing the template behind the blocks, because many of the blocks contain empty "invisible" areas:

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/87168/108992200-b6959280-76a1-11eb-80d8-731750bcf7ca.png">

Yet another related problem is that on smaller screens template part can take the whole page and thus relying on borders isn't reliable:

<img width="1265" alt="image" src="https://user-images.githubusercontent.com/87168/108993790-b39ba180-76a3-11eb-8f82-bca2a5177a8c.png">

**Comment by creativecoder** [comment]
> Alternatively IIRC there are some explorations around requiring the user to select the template part to be able to edit its content

Just noting that this is nearly what we have now, when in select mode.

![template-editing-select-mode](https://user-images.githubusercontent.com/1699996/109067260-e483d280-76b3-11eb-8946-dcd495a3eaa5.gif)

**Comment by mtias** [comment]
I think this can be closed now
