### ISSUE TITLE
Components: NumberControl up/down buttons not working correctly

### ISSUE THREAD

**Issue by jeyip** [WordPress/gutenberg#29271]
## Description

When selecting the columns block in Gutenberg (in the Firefox or Safari), the arrow buttons in the block inspector to add or remove additional columns is broken

## Step-by-step reproduction instructions

1. Navigate to the post editor or site editor
2. Add a columns block
3. Open the block inspector
4. Verify that the arrow buttons does not adjust the number of columns as expected

## Expected behaviour

- Clicking on the "up" arrow will add an additional column to the columns block
- Clicking down on the "down" arrow will remove a column from the columns block

## Actual behaviour

The arrow buttons are unresponsive or don't function at as expected

### Firefox
![2021-02-23 14 00 25](https://user-images.githubusercontent.com/5414230/108914588-6dc9d500-75e0-11eb-9cc8-37d7560e88c1.gif)

### Safari
![2021-02-23 14 07 34](https://user-images.githubusercontent.com/5414230/108914989-11b38080-75e1-11eb-932c-0b20a8bc8b60.gif)

## WordPress information
- WordPress version: 
- Gutenberg version: `master`
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 blocks

## Device information
- Device: Desktop
- Operating system: Mac Big Sur
- Browser: Firefox latest

**Comment by tellthemachines** [comment]
I can reproduce these behaviours on both Firefox and Safari. It happens on all components using `NumberControl`; to verify test [its story](https://wordpress.github.io/gutenberg/?path=/story/components-numbercontrol--default) on the affected browsers. Seems to be working as expected on Chrome.

**Comment by jeyip** [comment]
I started investigating this.

Relevant files:

- `packages/components/src/number-control/index.js`
- `packages/components/src/input-control/index.js`
- `packages/components/src/input-control/input-field.js`

**Comment by stokesman** [comment]
bf9f9e572138ab28814c1b113a6d9b5fbbfaea8c removed a bit of logic to ensures the focus of the input in case it's not. Firefox needs that since it doesn't focus the input if just the spinner arrows are hit and the input (in components based on `InputControl`) must have the focus or else it updates only via props.

I made #29305 which fixes this for Firefox. The issue with Safari seems different and appears to be that the drag-to-adjust feature is not working. Maybe it was something to do with the updated react-use-gesture from #28280. I've not figured that out yet and have to take a break from this for now.
