### ISSUE TITLE
Template part: Remove transform options

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#29296]
As surfaced in #29249, the block transform options on the Template Part block do not work.

That said, it doesn't seem sensible to allow Template Parts to be transformed in this manner at all. So rather than fix this, I vote that we remove it altogether.

**Comment by carolinan** [comment]
A conversation related to this took place on Slack (An account is needed to view it)
https://wordpress.slack.com/archives/C02QB2JS7/p1617179378083600

**Comment by Mamaduka** [comment]
@ntsekouras, now that we have some logic specific to Reusable blocks and Template Parts, would it make sense to update `hasPossibleBlockTransformations` and add a check for the latter?

https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-switcher/index.js#L91-L93

P.S. I remember you looked into ways to disable wildcard transformations for blocks, but I don't remember the results.

**Comment by ntsekouras** [comment]
Ideally we should augment the transforms API to handle things like excluding and better handling of the wildcard. Having said that, since we already have some specific logic there about template parts, I think it would be okay to have a stop gap solution with a good comment that this should be handled by the transforms API.
