### ISSUE TITLE
German translation of "reset" needs too much space

### ISSUE THREAD

**Issue by Azragh** [WordPress/gutenberg#29373]
## Description
The German translation of the reset button "zurücksetzen" in the font sizes takes a few pixels too much space, which leads to a vertical scroll bar.

I would either use the German word "standard", "leeren" (which means "to empty"), or simply leave it at "reset" - the term appears frequently in German and should therefore be understood by all users.

## Screenshots
![image](https://user-images.githubusercontent.com/15014142/109298945-9cd88480-7834-11eb-9388-7f769b8e951a.png)

**Comment by Soean** [comment]
Hey @Azragh, thanks for reporting. We already have an open issue about this bug, see #28612. So I close this one.

Just changing the translation don't solve the problem, because there is also an option for custom font size, so the problem will appear again. And I think there are also other languages with the same problem.
