### ISSUE TITLE
Navigation Page Link - Searches posts instead of pages

### ISSUE THREAD

**Issue by Addison-Stavlo** [WordPress/gutenberg#29396]
May be this is the cause of https://github.com/WordPress/gutenberg/issues/29395 as well.

When using  the navigation "Page Link" feature to search for pages, the results given seem to be for posts instead.

Here is the starting suggestion before any input (Suggests my post "hello world" instead of my page "sample page"):
![Screen Shot 2021-02-26 at 8 02 32 PM](https://user-images.githubusercontent.com/28742426/109370378-01fc9c00-786e-11eb-8aa6-db01026e5e52.png)

When searching for my page, it finds no results even if published:
![Screen Shot 2021-02-26 at 8 02 46 PM](https://user-images.githubusercontent.com/28742426/109370387-12147b80-786e-11eb-9cf2-587570b96639.png)

**Comment by paaljoachim** [comment]
It sounds like a bug to me....

**Comment by Psmith-Ukridge** [comment]
I'm just getting started working with blocks in a serious way - started using Hensen theme and had this same problem - only posts come up when you try to add new pages to the navigation. I'm used to the menus option in wordpress - that really threw me and I wasted a lot of time thinking I was doing something wrong.

**Comment by kjellr** [comment]
Running `trunk`, I do see pages returned in the post/page editor, but I do not see them returned in the Site Editor. 


(Also, this may be somehow related to https://github.com/WordPress/gutenberg/issues/29984)

**Comment by gwwar** [comment]
Looks like this one probably happened since site editor was created:

Basically we have multiple implementations of `fetchLinkSuggestions` and they're getting out of sync.

Post-Editor:

https://github.com/WordPress/gutenberg/blob/f15a9f29fa8d4fbc2c7baa67ac5de9c9f80bdb2f/packages/editor/src/components/provider/use-block-editor-settings.js#L42-L106

Site Editor:

https://github.com/WordPress/gutenberg/blob/f15a9f29fa8d4fbc2c7baa67ac5de9c9f80bdb2f/packages/edit-site/src/index.js#L21-L45

Navigation Editor:

https://github.com/WordPress/gutenberg/blob/f15a9f29fa8d4fbc2c7baa67ac5de9c9f80bdb2f/packages/edit-navigation/src/utils/fetch-link-suggestions.js#L31-L101
