### ISSUE TITLE
Contextual block toolbar: Move below the block when bumping against the top edge

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#29464]
## What problem does this address?

Mostly in the site editor, if you select a block close to the top of the screen, it bumps against the screen edge and gets pushed downwards, covering content:

<img width="1270" alt="Screenshot 2021-03-02 at 09 04 09" src="https://user-images.githubusercontent.com/1204802/109617318-884b0380-7b36-11eb-88e7-8e7b31e63693.png">

## What is your proposed solution?

In those cases, show the block toolbar below the block:

<img width="1270" alt="Screenshot 2021-03-02 at 09 04 57" src="https://user-images.githubusercontent.com/1204802/109617345-926d0200-7b36-11eb-82ad-aaa01db99b65.png">

We might need an additional heuristic, that still shows the toolbar above the block if the block is taller than, say, 300px.

**Comment by annezazu** [comment]
Noting here that this same problem occurs in template editing mode (not sure how much code is shared between the site editor and template editing mode). Edited to add a quick video:


https://user-images.githubusercontent.com/26996883/119399318-f87ca780-bc95-11eb-8d71-6678f71e3b46.mov

**Comment by ellatrix** [comment]
I think the same dark padding as the template editor would be a nice solution.

**Comment by kjellr** [comment]
Noting that this will be a frequent issue for header template parts, since they'll often be the first block included on the page. Currently, the block toolbar completely hides the arrows in the patterns carousel for that block's placeholder: 

![119679526-6e0b8380-be0e-11eb-94e8-9a46a5e9b95a](https://user-images.githubusercontent.com/1202812/119680807-816b1e80-be0f-11eb-82dd-6b2ecd46b3e4.gif)

**Comment by jasmussen** [comment]
🔥
