### ISSUE TITLE
Site editor: Selecting block does not switch to the block tab

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#29620]
## Description

In the post editor, when you select a block, the block tab is selected to show contextual controls:

![post editor](https://user-images.githubusercontent.com/1204802/110309441-a1095c80-8001-11eb-8ae2-d17f10e20253.gif)

This is not the case in the site editor:

![block tab](https://user-images.githubusercontent.com/1204802/110309455-a666a700-8001-11eb-985f-d00be329ee5f.gif)

## Step-by-step reproduction instructions

Install a block-based theme (https://github.com/WordPress/theme-experiments) and go to the site editor. Click a block, and note the block tab is not selected.

## Expected behaviour

The block tab should automatically be selected to show contextual controls for a block, when the block is selected.

**Comment by carolinan** [comment]
Confirmed.

**Comment by critterverse** [comment]
I noticed this when completing the most recent [FSE call for testing](https://make.wordpress.org/test/2021/03/09/fse-program-testing-call-3-create-a-fun-custom-404-page/). Just wanted to note that this may involve the extra step of a forced toggle between the two righthand sidebars as well if the Global Styles sidebar is already open:

https://user-images.githubusercontent.com/77359364/112077076-0f960080-8b52-11eb-811d-a019ef6d1bc9.mov

**Comment by jasmussen** [comment]
> Just wanted to note that this may involve the extra step of a forced toggle between the two righthand sidebars as well if the Global Styles sidebar is already open:

I would think that it's okay that selecting a block while viewing global styles doesn't toggle the block toolbar. That might be disruptive. 

There might also be an opportunity to make the global styles panel contextual in a similar way, so when you select a paragraph, the paragraph block type panel is toggled in the global styles panel.

**Comment by critterverse** [comment]
>I would think that it's okay that selecting a block while viewing global styles doesn't toggle the block toolbar. That might be disruptive.

Thanks for weighing in @jasmussen! I agree on this being potentially disruptive 😬 The reason why I'm calling attention to it is because there were a few instances when using the Column block that I came to a standstill over the secondary controls not being visible. This is especially confusing when using _Transform to_, which doesn't include the intermediate step of a placeholder block that allows for adjusting the number of Columns:

https://user-images.githubusercontent.com/77359364/112161677-bf568700-8bc1-11eb-946f-424e4ac764c9.mov

It could very well be that this is an argument for revisiting the division between primary & secondary controls for the Column block as much as anything else!

>There might also be an opportunity to make the global styles panel contextual in a similar way, so when you select a paragraph, the paragraph block type panel is toggled in the global styles panel.

+1 I can see this going a long way to improve the usability of block-specific Global Styles (especially if existing issues surrounding the division between primary/secondary block controls are resolved at an individual block level).
