### ISSUE TITLE
Button Padding not calculating

### ISSUE THREAD

**Issue by pbking** [WordPress/gutenberg#29675]
## Description
When evaluating button styling padding calculations appear to be breaking in some situations.

## Step-by-step reproduction instructions
Add a button to a page.  (Ensure that it is NOT styled as an 'outline button')
When running locally (using wp-env) the padding of the button is the size that is expected.
![image](https://user-images.githubusercontent.com/146530/110487308-74198000-80bb-11eb-9e9e-9ee00afc9912.png)
I see that the "padding" for this button is set to `padding:calc(.667em + 2px) calc(1.333em + 2px);` which I believe was done this way to ensure that 'regular' and 'outline' buttons are ultimately the same size.

Next I re-created the same site (using pressable) and note that the button padding is NOT rendering correctly.  (This can also be seen in [theamdemo.wordpress.com](https://theamdemo.wordpress.com/2019/06/25/gutenberg-button/?theme=pub/mayland-blocks).)
![image](https://user-images.githubusercontent.com/146530/110487616-c064c000-80bb-11eb-83f4-6f9d80250b74.png)
I note that the padding value is set in this scenario to `padding:calc(.667em+2px) calc(1.333em+2px);` which is exactly the same as the other instance with the space removed from around the +, however the value is noted as an "invalid property value".  Reintroducing the spaces manually addressed the padding errors.

## Expected behaviour
The padding of the buttons should be expressed in such a way that will work in every scenario.

## Actual behaviour
The padding styles of buttons are expressed in a way that breaks when content is optimized (spaces removed).

## WordPress information
- WordPress version: 5.6.2
- Gutenberg version: 10.1.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No

**Comment by scruffian** [comment]
This change was introduced in https://github.com/WordPress/gutenberg/pull/29208

**Comment by ockham** [comment]
From a quick (!) glance, this could be similar to #28497.
(It's possible that we need to tweak the normalization done in #28501 in order to make sure that expressions like this are treated as invalid.)

**Comment by ockham** [comment]
I agree that this seems to be WP.com (and Pressable) specific (rather than being a bug in Gutenberg itself) -- probably due to a CSS minifier violating the CSS spec by removing spaces around operands in a `calc()` expression.

I'll thus close this issue. To keep track of it for WP.com, please file an issue in the https://github.com/Automattic/wp-calypso repo instead. (Furthermore, from internal Slack discussions, it seems like WP.com teams are already aware and looking into this issue.)

**Comment by ockham** [comment]
Seems I was mistaken: looks like this was also reported [here](https://github.com/WordPress/gutenberg/pull/28358#discussion_r589402550), and fixed by https://github.com/WordPress/gutenberg/pull/29554 (and minification was later removed altogether by https://github.com/WordPress/gutenberg/pull/29624).
