### ISSUE TITLE
Design changes to template parts does not prompt saving the template part

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#29758]
## Description

When I change the design of a template part in the site editor and select the update design button,
I am only asked if I want to save the template, not the template part.

_This means that if I change the background color of a template part inside the site editor, the color change is not saved._

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. Activate a full site editing theme that has template parts
2. In the site editor, select a template part and change its colors.
3. Update design. See that only the template is listed under "Select the changes you want to save"
5.  Make a change to the blocks inside the template part, like adding a new paragraph.
6. Update design. See that both the template and template part are listed under "Select the changes you want to save".

## Expected behaviour

I expected to be able to save design changes.

## Actual behaviour

Design changes to template parts does not prompt saving the template part.

## WordPress information
- WordPress version: 5.7.
- Gutenberg version:  current trunk (https://github.com/WordPress/gutenberg/commit/5d99e6ce5a334987dbf4f0117333781ee1956656)
- Are all plugins except Gutenberg deactivated? yes
- Are you using a default theme (e.g. Twenty Twenty-One)?  TT1 Blocks,  Armando

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome Version 89.0.4389.82

**Comment by stacimc** [comment]
The experience is a bit confusing. I'm able to confirm that if you only make design changes to a template part, you are not prompted to save the template part -- but the design changes _are_ persisted when you do save the template.

In fact it seems that design changes to template parts are only persisted when saving the template, and non-design changes are only persisted when saving the template part. This leads to some non-intuitive scenarios:

1. Select the header template part and make a design change (change its background color) and a change to its blocks (add a new paragraph).
2. Click 'Save' and see that both the template and the template part are listed under "Select the changes you want to save".
3. Uncheck the template part and **_only_** save the template.
4. View the site on the frontend; the design change (new background color) is reflected, but the block change (new paragraph) is not.
5. Go back to the site editor and select the header template part again. Make another design change (change text color) and a change to its blocks (add a new paragraph again).
6. Click 'Save' and see both the template and template part listed.
7. This time uncheck the template, and **_only_** save the template part.
8. View the site on the frontend; the block change (new paragraph) is visible, but the design change (new text color) _is not reflected_, even though you saved the template part.

It looks like this separation is intentional, but it does feel confusing from a user perspective. I would expect to be prompted to save the template part for either block or design changes, and for both types of change to only take effect when the template part is explicitly saved.

**Comment by carolinan** [comment]
Related: https://github.com/WordPress/gutenberg/issues/30732
