### ISSUE TITLE
Persistent List View: Show the entire content of Query blocks

### ISSUE THREAD

**Issue by Copons** [WordPress/gutenberg#29784]
_This issue is about the Persistent List View experiment (#28637), currently only available in the Site Editor._

The Persistent List View is supposed to display all the blocks of the current content.
This doesn't happen for the Query block, which only shows the last item of the loop (e.g. the most recent post).

If we select a block contained in one of the "other" items of the loop, the Query branch in the list view will update, and the content of the selected loop item will replace the most recent's one.

We might want to show the content of the entire Query loop, instead of just one item (either the selected one, or the most recent).

**Comment by ntsekouras** [comment]
`Query` works in a way where only one item is `editable` by selecting it (defaults to first item) and the others are just previews which aims to a more understandable UI. Every item in the loop contains the same blocks with each other and are identical in terms of content(blocks - not referring to dynamic blocks which result to different content).

I can see this creating a lot of confusion (and unnecessary complexity IMO) especially when `movers` are implemented, as the order of the items depends on the actual `query` which comes from `context`. Another thing could be when we have set the Query number of posts to something big which will overwhelm the list view.

Of course it has more technical challenges, but would like to hear what do you think would be the value of showing all the posts somehow?

**Comment by Copons** [comment]
> `Query` works in a way where only one item is `editable` by selecting it (defaults to first item) and the others are just previews which aims to a more understandable UI. Every item in the loop contains the same blocks with each other and are identical in terms of content(blocks - not referring to dynamic blocks which result to different content).
> 
> I can see this creating a lot of confusion (and unnecessary complexity IMO) especially when `movers` are implemented, as the order of the items depends on the actual `query` which comes from `context`. Another thing could be when we have set the Query number of posts to something big which will overwhelm the list view.
> 
> Of course it has more technical challenges, but would like to hear what do you think would be the value of showing all the posts somehow?

@ntsekouras 🤔 AFAICS items in the loop are _not_ identical though: (at least?) the Post Content block is always different!
_(Unless you were talking about Post Content, when you mentioned dynamic blocks 😄 )_

I'm not familiar at all with how the Query block works, so I won't presume to know a solution or even an idea for this issue.
My concern is only relevant for the Persistent List View which, supposedly, should outline the exact same blocks contained in the canvas.

On the other hand, the issue with movers would make total sense, thanks for pointing it out.
I guess this might need some design thought, because it's really a super tricky one — althought I'd consider it minor at this point, so IMHO there's no rush.

**Comment by ntsekouras** [comment]
>@ntsekouras 🤔 AFAICS items in the loop are not identical though: (at least?) the Post Content block is always different!
(Unless you were talking about Post Content, when you mentioned dynamic blocks 😄 )

Exactly. I'm talking about the blocks used and Post Content is one them but is dynamic.

>althought I'd consider it minor at this point, so IMHO there's no rush.

Agreed :)

**Comment by jameskoster** [comment]
> My concern is only relevant for the Persistent List View which, supposedly, should outline the exact same blocks contained in the canvas.

If we instead say that list view should outline the exact same blocks contained in the **_document_** then it is ok to only display the Post Content block without its children, since those children belong to a _different_ document.

With regards to showing each post as a dedicated item in list view, something like:

<img width="396" alt="Screenshot 2021-06-04 at 15 16 58" src="https://user-images.githubusercontent.com/846565/120815657-ef1df580-c547-11eb-8746-5dc80e445322.png">

I agree with Nik that this could lead to some very confusing interactions. Since each post is based on a template, what would it look like if I try to drag the Featured Image block? Do they all move in tandem?

Also – if I move the Post Title block in one post, and see it move for all the other posts, I don't think I would understand why that is happening since everything _appears_ to be separate.

I suspect there are probably solutions to all of these wrinkles, but when you put them all together I wonder if the UX becomes overwhelming. The better solution (at least in the short term) may be improving the names and descriptions for Query / Query Loop (https://github.com/WordPress/gutenberg/pull/32283).

**Comment by priethor** [comment]
As stated above, this could be quite confusing, especially as we are heading in a different direction trying to ease interactions with Query block and its variations in the List View, like the one proposed in  #32268

Let's close this for now and revisit this kind of interaction further down the line :+1:
