### ISSUE TITLE
When editing the page_for_posts page the canvas should match the front end

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#29821]
Setting a static home page unlocks an affordance to specify a separate page to display the post archive:

<img width="482" alt="Screenshot 2021-03-12 at 13 20 07" src="https://user-images.githubusercontent.com/846565/110947520-2d848980-8338-11eb-9b22-dc5f9e561fe8.png">

When presented in the editor the content of this page does not reflect what you see on the frontend. Indeed any changes you make are essentially ignored until you unset this page as the `page_for_posts`.

Here's an example of a perfectly reasonable user flow which behaves in a very unexpected way:

https://user-images.githubusercontent.com/846565/110946015-4ee47600-8336-11eb-9e59-6a189e689a7a.mp4

I appreciate this isn't really a bug – WordPress has always handled this the same way. But with all the blocks we've built for the Site Editor there's potential for us to do better in this specific instance. To kick off discussion, one idea would be for this page to display a single Query block, which cannot be removed. Perhaps some of the attributes are locked as well. Pattern transforms (https://github.com/WordPress/gutenberg/issues/28736) could be possible.

It's worth acknowledging that this issue is not restricted to the page for posts. There are other templates in the site editor that should 'lock down' specific blocks. I think that is a slightly different issue though, and worth discussing elsewhere (https://github.com/WordPress/gutenberg/issues/27848#issuecomment-797494456).

Edit: This is somewhat related to https://github.com/WordPress/gutenberg/issues/28341

**Comment by jameskoster** [comment]
I don't know that this necessarily needs design.

Essentially if I open the page assigned to `page_for_posts` in the editor, I should see the relevant query block from the `home` template if it exists, or the `index` template if it doesn't. Those blocks should of course be locked, and inherit attributes like `posts_per_page` from the site settings.

**Comment by jameskoster** [comment]
This issue is especially pertinent now that it is possible to directly move from editing a page to editing a template:

https://user-images.githubusercontent.com/846565/117279241-6aad5980-ae59-11eb-9c4d-67bdbf49b895.mp4

Edit: Re-adding the needs design label. This needs some consideration to account for both classic and block themes.

**Comment by jameskoster** [comment]
It's actually possible to "break" the functionality currently by assigning the "wrong" template. Using a general page template would result in the posts page no longer displaying posts.

Initial thought: Since the template for this page resolves automatically, It should not be possible to _change_ the template in the UI. Creating a new template should be possible once – this action spawns the `home` template (hopefully with a better name 😅).

Edit: After a chat with @youknowriad, it probably makes most sense to simply hide the template panel for this page for 5.8. This mimics how the classic editor treats this page.

**Comment by creativecoder** [comment]
Here's an experiment that allows editing the Posts page template (and any other page template) when editing a page: https://github.com/WordPress/gutenberg/pull/32022

**Comment by jameskoster** [comment]
It would be nice to revisit this now that the site editor is live. 

One option might be to redirect folks to the Site Editor and open the `home` or `index` template when they edit this "page". This would solve the awkward experience where content added to the page never actually appears on the frontend.

Another option would be to open the template editor that exists in the post editor.

**Comment by paaljoachim** [comment]
What if clicking the posts page be it the front page or a designated posts page would show the Query Loop block in place with a kind of default block structure in place? This way one still have access to only the Posts Page outside the site editor. 

Going from currently this:
![Screenshot 2022-02-08 at 14 14 03](https://user-images.githubusercontent.com/5323259/152994239-31178c8c-8521-45e0-be1b-978d0313f08c.jpg)

To

Something like this:
![Screenshot 2022-02-08 at 14 15 10](https://user-images.githubusercontent.com/5323259/152994378-761a8985-e05e-4d4c-a2af-b17cd62ab343.jpg)

**Comment by jameskoster** [comment]
Yup, that is another option. But it's tricky for a few reasons:

* We'd need to hide most options on the Query block since they would be inherited from the URL and other global settings (posts per page etc)
* The Query Template would need to be synced with the underlying template
* The UI must be clarify that changes to this Query could affect other pages
* We'd need to prohibit the addition of blocks outside the Query – that is template editing territory
* Should folks be able to edit the posts returned by the Query?

All of this might result in too much of a detachment from the expected page editing experience.

**Comment by paaljoachim** [comment]
@aurooba made this associated issue: 
[FSE] When static front page/posts page is set, disable the page editor, redirect to Site Editor 
https://github.com/WordPress/gutenberg/issues/38389

Also sharing the Core Editor Slack conversation that is also happening:
https://wordpress.slack.com/archives/C02QB2JS7/p1644323569973349

**Comment by aurooba** [comment]
I'm going to go ahead and close #38389 and add my thoughts here because it makes a bit more sense to keep it all in an issue:

-----------------------

This is a confusion I encountered myself – despite understanding the WordPress Template Hierarchy extremely well – and have watched others encounter too. It stems from being able to do things one way before and having the paradigm change in FSE. 

When you set a `page` as the `static front page` in a block theme, you should be editing the `Front Page` template in the Site Editor rather than in the Page Editor. However, _because_ you can still add things to the _Page_ you set as the `Front Page`, it's easy to get confused and starting working on the page there.

When a `Page` is set as the `Posts page`, there is a little notice in the snackbar letting you know you are editing the `Posts` page.
<img width="520" alt="Screen Shot 2022-01-31 at 2 29 47 PM" src="https://user-images.githubusercontent.com/6925260/151876200-8bdc08b1-a45a-443e-a78b-88305a013d1b.png">
This is better, but still not enough, because the phrasing leads you to believe that you are making _actual edits_ to the `Posts` page, when in fact, edits here will do nothing, because you should be editing the `Home` template in the Site Editor (the fact that it's called the `Home` page, directly coming from the Template Hierarchy is super problematic and I'll leave that for another issue I'll inevitably make).

### Here's what I'm thinking
When a `Front Page` is set, the Block Editor should be disabled and have a button to take you to the Site Editor, the same goes for the `Posts` page. Or better yet, let's make it automatic! Clicking `Edit` on the page set as the `Front Page` or the `Posts` page could automatically redirect you to the appropriate template in the Site Editor.

**Comment by carlomanf** [comment]
I think redirecting to the site editor makes sense. Maybe the code from #36294 could be re-purposed for this.

**Comment by jameskoster** [comment]
Noting that this experience still feels buggy. On the backend, the preview frame and edit experience still show something completely different to what you see on the frontend. 

## Backend
<img width="1511" alt="Screenshot 2024-03-20 at 11 49 31" src="https://github.com/WordPress/gutenberg/assets/846565/ac45f059-c5c2-4dc3-adb6-98b8cf30ad42">

<img width="1513" alt="Screenshot 2024-03-20 at 11 49 44" src="https://github.com/WordPress/gutenberg/assets/846565/51e2b796-ce86-4e62-b446-147bbb30689f">

## Frontend
<img width="1511" alt="Screenshot 2024-03-20 at 11 49 55" src="https://github.com/WordPress/gutenberg/assets/846565/48e6917b-c06c-45b2-bc6a-b464184e1a6d">

**Comment by ellatrix** [comment]
This doesn't seem like a regression, so punting

**Comment by jameskoster** [comment]
I'd appreciate more testing, but this may be fixed now.

| Backend | Frontend |
| --- | --- |
| <img width="1404" alt="Screenshot 2024-07-19 at 12 45 03" src="https://github.com/user-attachments/assets/07eb4d98-3736-4801-8d7a-cfa6b934ee1e"> | <img width="1403" alt="Screenshot 2024-07-19 at 12 45 15" src="https://github.com/user-attachments/assets/240dca6c-73e6-408a-9e9a-16cd29f30f53"> |

Note that the correct template is referenced in the Inspector, compared with the screenshots [above](https://github.com/WordPress/gutenberg/issues/29821#issuecomment-2009388431).

Tentatively closing, but let's re-open if there reports to the contrary.
