### ISSUE TITLE
Popover position improvement idea

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#29868]
Alternative to the idea proposed in #21275.

The popover position API is very clunky and it tries to satisfy a lot of different positioning needs.

What if we provide a base rectangle and allow popovers to be positioned from there, purely in CSS? Why reinvent the wheel and maintain or introduce a positioning API if CSS provides a great one?

How could this be done?

Instead of positioning a popover immediately at the target position, we position the **wrapper** popover div element exactly over the anchor element so that it has the same dimensions and positions (base rectangle).

<img width="366" alt="Screenshot 2021-03-15 at 13 15 08" src="https://user-images.githubusercontent.com/4710635/111145012-7a629d00-8590-11eb-9da5-c078ff8b47db.png">

^= Imagine a the popover div overlays the anchor div.

From there, the popover **content** div can take any relative position it wants through the CSS positioning API. You can even stretch it as an overlay (imagine a block overlay through a popover).

That's pretty much it. :)

Of course we can map the existing position API with CSS, and we can provide better JS shortcuts if we want. The point is for it to be powered by CSS under the hood and allow all the flexibility of CSS.

Cc @youknowriad.

**Comment by youknowriad** [comment]
I think a good position API would be good, I think in the ideal world, we'd compose UI components without writing any bit of CSS. That said, the current position API is definitely bad and also, this doesn't prevent us from actually basing the implementation of the Popover component the way you suggest above. (I'd also like a prop to not do anything aside cover the anchor) :P 

Also cc @sarayourfriend @ItsJonQ since they integrated a new Popover component on the code base that needs to be brought in sync with the current one as well.

**Comment by ellatrix** [comment]
Right, it doesn't prevent us from making an API in JS that is powered by CSS under the hood. We can still use props as shortcuts.

**Comment by youknowriad** [comment]
I feel like there has been a lot of iterations on the Popover since this issue was opened. We have the "placement" prop and we use floating ui under the hood. I think we're in a better position now. I'm closing but let me know if you think otherwise.
