### ISSUE TITLE
WordPress 5.7 cannot create new reusable block or change an exisiting one

### ISSUE THREAD

**Issue by siggorr** [WordPress/gutenberg#29885]
## Description
From Wordpress V5.7 it is for me not possible to create a new, or change a existing reusable block from "manage all blocks" editor. The buttons for saving and publishing are there, but are not working.

Tried with healt check, all plugins deactivated and a standard theme (twenty-twenty), issue still there
tried to clear cache / opcache / browser cache, but no improvenments.

Downgrading to WP 5.6.2 solved the issue
Attached the Firefox Console log
[Error LOG.TXT](https://github.com/WordPress/gutenberg/files/6146823/Error.LOG.TXT)

## Step-by-step reproduction instructions
1. Go to  'manage all reusable block '
2. Click on  'create new '
3. make a block
4. click save or publish
5. the buttons are there, but not working

## Expected behaviour
to be possible to create new or change an exisiting reusable block

## Actual behaviour
buttons for saving / publishing seems not to be working

## WordPress information
- WordPress version: 5.7
- Gutenberg version: integrated in WP 5.7
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes (not by default but tried with twenty-twenty

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome 88.0.4324.190, Firefox 86.0

**Comment by paaljoachim** [comment]
Hi @siggorr 

Testing with
WordPress 5.7.
Gutenberg plugin: 10.1.1 (I also deactivated the Gutenberg plugin so no plugins were active.)
Twenty Twenty One and Twenty Twenty themes.
Chrome and Firefox.

Made a new page. (saved draft)
Went to the Inserter Add block panel. Clicked Reusable and then "Manage Reusable blocks"
Entered the Reusable blocks screen.
Clicked "Add New"
Added a title and some contents (a heading and an image) to the new Reusable block.
Clicked Publish. Reusable block published.

Twenty Twenty One
![Screen Shot 2021-03-16 at 18 03 36](https://user-images.githubusercontent.com/5323259/111350026-f983ce00-8681-11eb-917b-fd13392dbe40.png)

Twenty Twenty
![Screen Shot 2021-03-16 at 18 05 24](https://user-images.githubusercontent.com/5323259/111350273-3b147900-8682-11eb-9d47-fb79b00cecf9.png)

I noticed no problem.

**Comment by nblenkhorn** [comment]
I'm also having this issue. All of my reusable blocks no longer function. 

I also get stuck in a loop where I can't remove an added reusable block. It says it's removed, but previewing still shows the block after saving. Save and returning to posts list prompts for: leave page | stay on page. If you stay, you still can't remove the block, if you leave and then come back in to edit the block is still there. It's so frustrating!

If I try creating a new html block it just inserts the code from the reusable block so I end up with multiple blocks that I can't edit or remove.

**Comment by talldan** [comment]
I also couldn't reproduce the issue in a clean WordPress install. 

@nblenkhorn Would you be able to share what steps we can take to reproduce your issue?

**Comment by siggorr** [comment]
@talldan 
@paaljoachim 

It doesn't seems to be a global problem. I also tested on the second site (on the same server, with the same server settings, same PHP Version and PHP extensions) and it works perfekt. But it is an issue of WP 5.7 / new Gutenberg version, because simple downgrading to the WP 5.6.2 Version solves the problem. But this is not a long term solution, for sure, just a work around.

I tried all simple solutions, from deactivating all plugins and using a standard twenty-twenty theme (with health check), clearing cache, opcache and browser caches. Noting helps.

Although, I have to say, the problems started actually with WP 5.6. I noticed then, that the editing and saving of reusable blocks are way much slower then before. Sometimes takes about a minute to save them, sometimes happens immediately. Also it is not possible anymore to change reusable block to normal and vice versa (I am using a German localization, so I am not sure what are exactly names of those options in English). But I never saw this as a huge issue, it is just annoying, because a work around is possible. But with WP 5.7 it is for me not possible anymore to edit my blocks and make new - so it is a huge issue for me.

Maybe important to mention, I have a lot of reusable blocks (about 3700), because this is the way how I build my content - over reusable blocks.

And just to prove it, that there are issues with WP 5.7 block editor. By making new reusable block (with just headline and simple text), I am getting a lot of recursions errors in the Firefox console. This doesn't happens with WP 5.6.2 block editor. 

[Error LOG.TXT](https://github.com/WordPress/gutenberg/files/6154404/Error.LOG.TXT)

**Comment by nblenkhorn** [comment]
I have several sites using the same theme/plugin stack on different servers and they all seem to have the same issue. I have narrowed it down to Custom HTML and Shortcode blocks. I was previously seeing some weirdness with these types of reusable blocks, but once I inserted them, "convert to block" seemed to fix the issue. If I didn't convert them they wouldn't show up on the front-end, only the back end.

**Comment by nblenkhorn** [comment]
[wp-env.txt](https://github.com/WordPress/gutenberg/files/6158265/wp-env.txt)

**Comment by AtrumGeost** [comment]
I was working with a customer today who ran into this same issue (has 1600 reusable blocks) with the latest version of WP and Gutenberg (running on WordPress.com). However, in this case, the issue is not happening only on the latest version of WordPress. Here's a link to the WordPress.com forums where the issue was initially reported:

https://wordpress.com/forums/topic/cant-edit-any%e2%80%91pole-any-article-or-new-after-%c2%b130sec/#post-3605322

**Comment by drewwats** [comment]
Having the same issue. Some blocks don't show up, some are showing the wrong block. Block editor is now useless.

**Comment by small-fork** [comment]
I am unsure if I should be adding this here or on core trac (I found the link to this thread there).

I've also found my reusable blocks are no longer in the "directory" if trying to add a new block. (I used to be able to search by the reusable block names). And I'm unable to make new ones, among other issues with their behavior, all as of the change to 5.7. Here is a breakdown of what I'm seeing:

**On the Reusable Blocks "List" page (/wp-admin/edit.php?post_type=wp_block)**
* My reusable blocks are still showing in the "list" page (/wp-admin/edit.php?post_type=wp_block), and I am able to go into their edit screen and see their content. 
* While I can access the "Edit" screen of a reusable block if going to the List of them, the "Update" button results in no action, thus making it impossible to actually edit existing blocks.
* While I can click the "Add New" button on the list page (new block edit screen opens  to /wp-admin/post-new.php?post_type=wp_block), when clicking "publish", it does the publish confirmation ask, then I click "Publish" again and it goes back to the first "Publish" button, never actually allowing me to publish the block


**Within a post or page**
* Reusable blocks do not come up in the block search and there is no "Reusable" tab in the block sidebar (Should be "Blocks" "Patterns" "Reusable") Screenshot: http://snpy.in/RMQBcp
* Existing reusable blocks already within content still seem to be displaying the reusable block's content and have something of a "ghost frame" of what should be the frame for editing them within the post they're embedded within, however the option is not present. Screenshot: http://snpy.in/H1JtpQ
* If I switch to code editor view, I can see the HTML for the block, and it seems (at least from one test), that I can add an existing reusable block to a post if I flip to the Code Editor view and paste in the HTML (though cannot make new reusables). Example of the HTML:

`<!-- wp:block {"ref":20311} /-->`
* I am unable to save new reusable blocks from within a post or page. Clicking the "Add to Reusable blocks" results in nothing happening.

Thank you!

**Comment by saemideluxe** [comment]
I encountered the same issue. I found out that any echo-ing inside a shortcode function will create that problem. Not sure why exactly, is it a security feature of wordpress or does something break? Well, anyway, echoing should not be necessary inside shortcode functions. So in most cases this should be easily fixable by correctly implementing the shortcut function (aka removing all echos or, like in my case, calling ```astra_the_post_title``` with ```$echo=false```).

**Comment by obladon25** [comment]
I encountered the same issue.

The problem is related to the timeout somehow. We receive an API response from the `/wp-json/wp/v2/blocks/4528?context=edit&_locale=user`
but the content in `.block-editor-block-list__layout` remains unchanged.
When I do CTRL + SHIFT + R no HTML is added to `.block-editor-block-list__ayout` for any reusable block. When I load the page with CTRL + R, then some blocks appear, some do not.

Classes:
`block-editor-inner-blocks -> .block-library-block__reusable-block-container -> 
.block-editor-block-list__layout`

<img width="1201" alt="Screenshot 2021-09-10 at 12 00 52" src="https://user-images.githubusercontent.com/4404634/132858244-582aa4ae-9cbf-4b83-96e3-04f8ed489a09.png">


<img width="1214" alt="Screenshot 2021-09-10 at 12 01 17" src="https://user-images.githubusercontent.com/4404634/132858284-4236da62-13af-41ec-81a3-5d0c37dd6244.png">


Because no HTML is added from the reusable block in `.block-editor-block-list__layout` , when saving the post, an update is made to the reusable block without content, and we lose the content on all pages (where this block is used). After I add the old content in the block (in the reusable blocks section `/wp-admin/edit.php?post_type=wp_block` ), the content is displayed on the frontend.

<img width="1338" alt="Screenshot 2021-09-10 at 12 26 15" src="https://user-images.githubusercontent.com/4404634/132858330-53ba99d6-6432-488f-894a-f1701f25aa48.png">


Is it possible to check this?


**Update:**

I think this may be related to the fact that some changes are being made in the DOM. Some blocks are displayed, but some show only "+", and  the displayed blocks are different at each refresh.

Loading:

<img width="839" alt="Screenshot 2021-09-10 at 15 06 24" src="https://user-images.githubusercontent.com/4404634/132858414-a8c51c07-6b26-4a1e-9149-3922f5e634cc.png">


Loaded:

<img width="1186" alt="Screenshot 2021-09-10 at 15 07 44" src="https://user-images.githubusercontent.com/4404634/132858439-b37a6c7a-74d7-41dc-9f44-752e8bb6116e.png">



*The same issue may be due to JS errors from other plugins (which have not been updated).

**Comment by paaljoachim** [comment]
I am wondering if this Trac ticket might be associated:
https://core.trac.wordpress.org/ticket/52790

**Comment by Yodapp** [comment]
I'm also having issues with reusable blocks. I've tried a clean install with no plugin and the default thene as well as GeneratePress (only the theme). Almost everytime I try to use a reusable block it freezes the web browser. It works fine to save a reusable block, but once trying to add it, the block isn't showing or if it's showing the browser tab hangs the moment I hover over the block.

I've tried this in Chrome, MS Edge, on both Mac and Windows 10 (both updated) and I've made sure that the cache was empty, did a hard reload etc etc. (I work as a web dev so I'm used to test things like this)

For me it started with either 5.8 or 5.8.1. The only thing in common is that I've only tested using chromium browsers.

@paaljoachim After reading the link you provided I also think it's related.

**Comment by kathrynwp** [comment]
I'm going to go ahead and close this out, given the last two comments on the related Trac ticket linked above. If anyone is still experiencing issues with Reusable blocks, please follow the steps laid out by Jonathan here:

https://core.trac.wordpress.org/ticket/52790#comment:72
