### ISSUE TITLE
Leaving a boundary such as a `<code>` tag can move you to the next block

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/gutenberg#2993]
Gutenberg Version: 1.4

## Issue Overview
If a paragraph block has a `<code>` boundary as the last item, and there is a paragraph block after it, pressing the right arrow moves you to the next block. I would expect to 

## Steps to Reproduce (for bugs)

1. Create two paragraph blocks
2. In the first block, create a code tag using `\`word\`` 
3. Reenter the code boundary
4. press the right arrow key

## Expected Behavior

I expect to stay in the block that I am currently writing in

## Current Behavior

I move to the next block.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by jeffpaul** [comment]
_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #core-editor by jeffpaul. [View the logs](https://wordpress.slack.com/archives/C02QB2JS7/p1521737430000003)._

**Comment by jasmussen** [comment]
I would agree with @SuperGeniusZeb that this ticket and #1246 seem to touch on the same, which is still an issue:

![boundary](https://user-images.githubusercontent.com/1204802/38660585-09dbc7f2-3e2e-11e8-83ae-7bdea99fad5a.gif)

Just in order to keep things moving, I'm going to close the previous one in favor of this one as this seems more descriptive, though noting appreciation and gratitude to @buzztone for opening the original issue.

**Comment by jasmussen** [comment]
That's a good point.

**Comment by jasmussen** [comment]
Good point, @SuperGeniusZeb, thank you. 

Although this ticket was technically first, that other ticket has since then been added to the merge proposal milestone. And so I'm closing this one. Apologies for the mess, but in cleaning this repo we can at times be a bit heavy handed. The issue will be fixed.
