### ISSUE TITLE
Broken padding in Search block's button

### ISSUE THREAD

**Issue by fullofcaffeine** [WordPress/gutenberg#29952]
## Description

The `Search` block's button's padding is broken. Tested with `v10.2.0` (latest version at the time I'm writing this). See screenshot s below (tested with TwentyTwentyOne and Blank Canvas themes).

## Step-by-step reproduction instructions

1. Install `v10.2.0` in your WordPress instance;
2. Switch to the Blank Canvas theme;
2. Create a new post or page;
3. Insert a `Search` block;
4. Observe how there's way too much padding at the bottom (or not enough at the other sides) making the button look odd and the text not centered.

## Expected behaviour

The button should look well and balanced and not have the odd padding at the bottom.

## Actual behaviour

There's way too much padding at the bottom (or not enough at the other sides) making the button look odd and the text not centered.

#### Twenty Twenty One theme:
<img width="850" alt="Screenshot 2021-03-11 at 10 48 47" src="https://user-images.githubusercontent.com/87168/110761343-4e75ad80-8258-11eb-8b2f-22da8f54aa48.png">

#### Blank canvas theme:
<img width="174" alt="Screenshot 2021-03-11 at 10 17 13" src="https://user-images.githubusercontent.com/87168/110761368-559cbb80-8258-11eb-8dd6-03a2d29e593e.png">

## WordPress information
- WordPress version: 5.8-alpha-50538.
- Gutenberg version: v10.2.0.
- Are all plugins except Gutenberg deactivated? Yes.
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, but also tested with the Blank Canvas theme.

## Device information
- Device: Desktop.
- Operating system: Ubuntu Linux 18.04.
- Browser: Firefox Quantum 87.0b9 (64-bit).

**Comment by simison** [comment]
Checked in Gutenberg 10.5 and TwentyTwentyOne, still happens:

<img width="692" alt="image" src="https://user-images.githubusercontent.com/87168/119540593-437de400-bd96-11eb-8b01-f89e4a0b5051.png">

Blank Canvas:

<img width="694" alt="Screenshot 2021-05-25 at 20 43 49" src="https://user-images.githubusercontent.com/87168/119544029-0156a180-bd9a-11eb-97c4-71bf8d667062.png">

I think this can also be theme-specific since it didn't happen with Alves theme:

<img width="844" alt="Screenshot 2021-05-25 at 20 43 56" src="https://user-images.githubusercontent.com/87168/119543994-f56adf80-bd99-11eb-843a-b29708cf6e59.png">

Perhaps the block needs to be a bit more defensive about its styles?
