### ISSUE TITLE
Gallery refactor: undo  doesn't work with keyboard to remove a gallery with images

### ISSUE THREAD

**Issue by glendaviesnz** [WordPress/gutenberg#30001]
## Description
If a gallery is created by dragging and dropping images CMD-Z or Delete key do not work to remove the block. Also of parent gallery is selected the delete key can't be used to delete it as it can with other container blocks. Probably related to https://github.com/WordPress/gutenberg/issues/29998

## Step-by-step reproduction instructions
Check out [gallery refactor PR](https://github.com/WordPress/gutenberg/pull/25940) and turn on refactored gallery experiment
Drag and drop images to create a gallery block. CMD-Z to undo, nothing happens
Select the parent Gallery block and hit Delete key - nothing happens

**Comment by kathrynwp** [comment]
Hi @glendaviesnz I'm just checking to see whether this issue is still applicable and valid now that the refactored gallery is in core.

I only been able to replicate intermittently, but not only with drag-and-dropped gallery images, also with images selected from the Media Library... so I'm not 100% sure I'm testing correctly. Let me know what you think!

WordPress 6.0.1
Gutenberg 13.8.1 active or inactive
No other plugins active
Twenty Twenty-Two 1.2

**Comment by glendaviesnz** [comment]
Let's close this one for now.
