### ISSUE TITLE
Advanced settings in blocks

### ISSUE THREAD

**Issue by ahartvanyi** [WordPress/gutenberg#3002]
Hi,

I'd like to ask if is it possible to add Additional CSS Class input field under Advanced block settings, to specified block elements like Paragraph or List?
Also can I register a new, custom advanced block setting for specified blocks?

If so, could you please share a solution?

Many thanks,

**Comment by youknowriad** [comment]
Hi! Unfortunately, this is not possible right now. (Because support for the custom className is also used to declare support for the generated className cc @aduth ). But this is something we'll look at.

**Comment by lkraav** [comment]
@ahartvanyi your question is partly unclear, with multiple questions chained into sentences. Use numbered lists so people can answer each item with clarity. It's not possible to tell right now whether @youknowriad replied to both parts or not.

My version of the question is: is it possible to filter and/or augment core blocks with additional properties and alter their final rendering output?

Forking each core block into a custom plugin with some added customizations has significant maintenance overhead.

**Comment by youknowriad** [comment]
yep sorry my answer was not clear enough, I was answering this

> I'd like to ask if is it possible to add Additional CSS Class input field under Advanced block settings, to specified block elements like Paragraph or List?

Other blocks do have a support for an additional CSS class while the paragraph/list don't.

> Also can I register a new, custom advanced block setting for specified blocks?

This is tracked here https://github.com/WordPress/gutenberg/issues/2474

**Comment by lumberman** [comment]
Unfortunately no progress on any extendability. It's very confusing as WP developers have high hopes for Gutenberg, but **there is no door for us get in**.

Gutenberg looks like Apple AppStore with a strict set of rules and limitations. As a developer, you can play in your tiny "sandbox" and don't even think to adjust/modify any standard features.

I know guys are very busy building most important features now, but **extendability (filters/hooks) is one of the main features of WordPress**. Otherwise, all the people would use WordPress.com or Calypso.

**Comment by klihelp** [comment]
yes for filters

**Comment by mtias** [comment]
@lumberman an overview of all the planned extensibility points are in: https://github.com/WordPress/gutenberg/issues/3330

We also welcome contributors to get started on these, specially if they have use cases they want accomplished.

**Comment by mtias** [comment]
Closing as https://github.com/WordPress/gutenberg/pull/3318 and https://github.com/WordPress/gutenberg/pull/3493
