### ISSUE TITLE
Navigation Block: Make it clearer how to delete a Link Block without a link

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#30116]
## What problem does this address?

Currently, if you add a link block to the navigation block but don't add a link, it results in a pretty confusing experience if you want to then delete the same link block. This is likely to be a common interaction for users though as they look to build out menus (trying out adding items, removing them, changing their minds mid adding a block, etc). The current experience gave the impression that one couldn't delete the block without adding a link first in order to get rid of the link UI:

>When adding a Link block you cannot remove it without clicking on Add a link – I’d like to select the block without having to bring up the Link UI.

In the video, I obviously know it's possible to delete the link block but this seems to be a point of confusion if you aren't as familiar and could easily come up if someone adds a link but then changes their mind. 

https://user-images.githubusercontent.com/26996883/112062985-566e0100-8b26-11eb-9f7e-31124f1e23aa.mov

This came up as part of feedback for the [third call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2021/03/09/fse-program-testing-call-3-create-a-fun-custom-404-page/#comment-1430). 

## What is your proposed solution?

While it makes sense to nudge a user to add a link in this context, there also needs to be a way to easily select the block without immediately throwing the user into the link UI controls as that seems to make it harder to feel one can then delete the block outright. This might mean a "double click" interaction, for example. I trust design here!

**Comment by jasmussen** [comment]
Great ticket, valid feedback, thank you. As noted on another ticket, it's tricky because it is key to the menu item placeholder that it opens immediately on click/close, and that if you press Escape, the URL dialog closes and the block is selected so you can delete it.

I don't think either of the following are good solutions, but sharing in case they inspire better ideas:

- Clicking the button selects it, you have to click an Edit icon next to it to add a link. 
- Clicking the button selects it, you have to press the URL button in the toolbar to add a link.
- There's a close button on the URL dialog.

**Comment by getdave** [comment]
@annezazu @jasmussen Recent improvements to the Nav block (6.5?) mean that it's now _much_ harder to end up with an empty link. Indeed we actively optimise to avoid this scenario.

https://github.com/user-attachments/assets/fbff10cb-7f67-49a2-8158-5de5714e0c76


Do you think this warrants this Issue being closed out?

**Comment by annezazu** [comment]
Yes, I do! Let's close it.
