### ISSUE TITLE
Navigation Block: Improve flow for deleting submenu items

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#30115]
## What problem does this address?

>Adding nested Link blocks in submenus left me in a situation where I was unable to remove the nested submenus because there is no way to delete using List View and the block toolbars for the nested link blocks don’t have any “delete” UI. I had to add a link before I could delete them – https://d.pr/i/75gd0G/zwqvFdfoe8

Currently, if you select the option to add a submenu item but, if you want to immediately remove it, it's not quite clear how to do so to the point that it seems one must add a link in order to then delete the block. The video below shows the experience (note that it's on purpose that I'm breezing through it so I don't end up with a long, confusing video): 

https://user-images.githubusercontent.com/26996883/112061786-a1871480-8b24-11eb-8ff3-a94b9a1cf14a.mov

Here's a video showing the confusion a bit more for effect:

https://user-images.githubusercontent.com/26996883/112062416-8a94f200-8b25-11eb-827d-25c2875c25ca.mov

This came up as part of the [third round of testing for the FSE Outreach Program. 
](https://make.wordpress.org/test/2021/03/09/fse-program-testing-call-3-create-a-fun-custom-404-page/#comment-1430)

## What is your proposed solution?

Right now, the "Add a Link" prompt is so prominent that it's not clear you're actually able to still select the block and use the same deletion pathways as before. I will leave it to design to come up with a clearer pathway here!

**Comment by jasmussen** [comment]
One tricky challenge here is that the menu item placeholder is meant to immediately open the URL dialog when clicked/invoked. You should be able to press Escape, which then selects the block, so you can press Delete to delete it. A better design for submenus with a bit more space is likely going to help provide some clarity on what's going on here, that's certainly something on my list regardless of whether it helps or not.

However in the second video, the menu closes immediately upon opening the link dialog. That's a completely broken experience. I also cannot reproduce it, so it's very likely that it has been fixed by https://github.com/WordPress/gutenberg/pull/29869 which is scheduled for Gutenberg 10.3.

**Comment by annezazu** [comment]
I think you are right about the latter video being fixed by that PR! In that case, I only saw that happen when I had two layers of submenus and tried to link the second submenu item.

**Comment by jasmussen** [comment]
To connect the dots, if we solve https://github.com/WordPress/gutenberg/issues/30116#issuecomment-804662996, this one should be solved also.

**Comment by tellthemachines** [comment]
With the introduction of the Submenu block, this flow has changed a bit: the URL popup no longer appears immediately when clicking "Add submenu". On the other hand, a submenu won't disappear any more if we remove all of its links; it just shows an inserter. 

(The quickest way I can think of to immediately revert an added submenu is cmd+z, or ctrl+z on Windows.)

With these changes in mind, is this still an issue? And if so, does the Submenu block alter anything about our possible solutions here?

**Comment by jasmussen** [comment]
The block has indeed evolved quite a bit, and the submenu block makes the experience feel less fragile or prone to error. Combined with improvements to simple menu item building, and simplified page link setup states, it's a good time to reevaluate both this ticket and in extension #30116. For the conversation, here's a GIF showing the current flow for adding submenu items, how to link them up, and how to delete them:

![deleting submenu items](https://user-images.githubusercontent.com/1204802/136912534-c7135af5-04be-4afe-9b8a-84071acce1c2.gif)

To explain the GIF:

1. Click a menu item to select it, then click the "Add submenu" button in the block toolbar. This adds a submenu, but an empty one.
2. Now click a plus inside the submenu to add a page link. This immediately opens the URL dialog popover, letting you choose or search for a page to link to.
3. To delete an item, select it, and delete it using the ellipsis menu, the shortcut key, or by entering select mode and pressing "Delete".

What is shown as challenging in the initial video is that when the menu item in a setup state (as denoted by the blue underline) it will immediately open the URL dialog to let you wire up the button. In other words, when clicking the block, focus is set not on the block itself, but on the URL input field, making the common "Delete" button not work as it does when selecting an Image for example. But in fact the ellipsis menu is still both available and functioning as intended:

![deleting items](https://user-images.githubusercontent.com/1204802/136913710-28d4f2d4-7865-4611-9181-208898c198b2.gif)

That makes the process of deleting items similar to that of deleting social icons, and even to an extent deleting paragraphs or buttons, since those both set focus on input fields as well:

![deleting buttons](https://user-images.githubusercontent.com/1204802/136914088-3f90bae7-96ee-40ec-b135-74f04695e49d.gif)

When this ticket was initially opened, the flow of creating submenus and the behavior and visual appearance of menu item placeholders (it used to look like a button), was genuinely fiddly and it definitely felt worth addressing. However revisiting this after the last many months of improvements, it's not feeling as problematic as it used to. In light of that, it might be worth revisiting this test and seeing if it's still an issue.

And if it is, it might be worth evolving this one into a new ticket focused on exploring simpler deletion of any block that sets focus on something other than the block itself, (which includes menu items, social icons, paragraphs, or buttons).

**Comment by jasmussen** [comment]
One thought: at the moment the Navigation block employs a "absorb toolbar" feature which always anchors the block toolbar to the navigation container, even that of child blocks. It could be interesting to unset that for the _navigation_ block, and instead apply that to _submenu blocks_. That would let the block toolbar align with the submenu block, rather than the navigation block, potentially feeling more contextual.

**Comment by annezazu** [comment]
Based on the updates outlined above (thank you!), I agree that this can be closed for now. I can re-open if additional feedback comes in about the new experience through the outreach program. 

> And if it is, it might be worth evolving this one into a new ticket focused on exploring simpler deletion of any block that sets focus on something other than the block itself, (which includes menu items, social icons, paragraphs, or buttons).

+1 to having a larger issue.
