### ISSUE TITLE
#wpbody-content is going down way below the viewport if a scrollbar appears

### ISSUE THREAD

**Issue by oglekler** [WordPress/gutenberg#30137]
Gutenberg > Navigation (beta)

While resizing a window if the body starting to have a scrollbar the whole #wpbody-content is going down way below the viewport:

Video: https://disk.yandex.ru/i/nrrWoLBNCzuTQg

_Environment:_
WordPress 5.7
Gutenberg version 10.2.1
experimental Full Site Editing theme

**Comment by talldan** [comment]
Hi @OlaIola. Thanks for reporting this—There have been a few changes over the last few days that have hopefully fixed this.

The structure of the layout of the page changed in https://github.com/WordPress/gutenberg/pull/30013, FSE themes should be working properly since https://github.com/WordPress/gutenberg/pull/30076, and https://github.com/WordPress/gutenberg/pull/29926 hides the notices at the top of the page. These fixes should all be in 10.3.

When testing with those recent changes I do still see the extra scrollbar on the right for the main editor area. I'd expect that to be next to the area it scrolls, so that seems like something that can definitely be fixed.

I couldn't see the other issues, but it'd be good to do some extra testing on 10.3 to verify that.

**Comment by getdave** [comment]
Hi @OlaIola. Were you able to find any time to re-test this? It looks like perhaps it will have been fixed but I'd love to confirm. Much appreciated.

**Comment by javierarce** [comment]
In case it helps, I haven't been able to reproduce this bug.

**Comment by carolinan** [comment]
I have not been able to reproduce this with 5.7.1 using current trunk or 10.6 Rc1 of Gutenberg.

**Comment by talldan** [comment]
Lets close for now, we can always reopen if this reappears.
