### ISSUE TITLE
Navigation Block: Editing the label of block causes Add Link prompt to appear incorrectly

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#30163]
## Description

If you add a Link Block to the navigation block, add a link, and then try to edit the label/text the "Add link" prompt shows up despite a link already being added. This makes it seem as though by deleting the label, you have also removed the link.  cc @jasmussen since you're working on this!

## Step-by-step reproduction instructions

1. Add a navigation block
2. Add a link block
3. Add a link 
4. Edit the text of the link you added and fully remove the text.
5. See "Add link" but confirm the link is already still added. 

## Expected behaviour

I expect the "Add link" prompt to say "Add text" or "Add label" since a link is already in place. 

## Actual behaviour

The "Add link" prompt shows up. 

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/26996883/112237252-e6d04280-8c07-11eb-9354-5bc323f4ea38.mov

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.2.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

## Device information
- Device: Desktop
- Operating system: MacOS 
- Browser: Chrome 88

**Comment by jasmussen** [comment]
It seems clear that blocks like Button, Social Link and Menu Item are all types of blocks that aren't very useful unless they have both a label(/icon) and a URL, and that anything we do to optimize for how it currently works is likely going to be less effective. That's also a bit of what we're discussing in https://github.com/WordPress/gutenberg/issues/28440#issuecomment-804771123, and I think I'll try reopening a version of that.

**Comment by annezazu** [comment]
Just noting that 5.9 still has the same behavior:

https://user-images.githubusercontent.com/26996883/152741811-f0997046-2559-4c31-bdd3-4f269a681819.mov

**Comment by kathrynwp** [comment]
Still able to replicate this with:

WordPress 6.0.2
Gutenberg 14.2.0 active or inactive
No other plugins active
Twenty Twenty-Two 1.2

@jasmussen with the Navigation Block being a focus in 6.1, would you perhaps have a moment to revisit this issue? Thanks!

**Comment by jasmussen** [comment]
Thanks for the ping. Coming back to this one, it seems like the solutions suggested in [my previous comment](https://github.com/WordPress/gutenberg/issues/30163#issuecomment-805537147) haven't made much progress. So the simplest solution in that light might be to treat this as a bug: _why isn't the content of the navigation item reset when backspacing the entire label_?

That does appear to work for plain rich text links:

![what happens when I make a link](https://user-images.githubusercontent.com/1204802/193771875-efc65312-b60c-43b0-ac5d-e4cfc9ada8a1.gif)

I wonder why a navigation item would be any different. CC: @draganescu if you have any insights?

**Comment by draganescu** [comment]
I think the navigation link is different from the inline link because the inline link is visibly removed from the text, while in the navigation block only the label is removed. If we remove the link when we delete all the label text, editing the label from scratch will become impossible.

I think the solution here is to manage the placeholder depending on the navigation link having an URL or not. No URL > add a link, has URL > add a  label.
