### ISSUE TITLE
@wordpress/scripts 14.0.1 incorrect creation of css source maps

### ISSUE THREAD

**Issue by Lovor01** [WordPress/gutenberg#30289]
After updating to 14.0.1 version of @wordpress/scripts, css source maps are incorrectly generated for setup of multiple blocks in one plugin (tested on two machines, both in firefox and chrome browsers)

Source map for style-index, blocks front-end is generated only for last compiled block (I am using setup with more blocks in separate directories, all imported from common index.js in the root. Each block has its own style.css file for each block). In previous versions, source maps were generated correctly.

**Comment by gziolo** [comment]
Hey, thank you for the report. Is your repository public so we could check the setup, or at least it would be great to have some more details on how the project is exactly structured, does it use the default webpack config, etc.?

**Comment by Lovor01** [comment]
> 
> 
> Hey, thank you for the report. Is your repository public so we could check the setup, or at least it would be great to have some more details on how the project is exactly structured, does it use the default webpack config, etc.?

No, it is not public, perhaps I could share some key files which reveal structure of imports. I tested also version 14.1.1-next.5c9849e156.0, but nothing changed, source maps are still not 'aggregating' files.

**Comment by gziolo** [comment]
> No, it is not public, perhaps I could share some key files which reveal structure of imports. I tested also version 14.1.1-next.5c9849e156.0, but nothing changed, source maps are still not 'aggregating' files.

It can be a simplified project that reproduces the issue. What was the previous version you were using that worked fine?

**Comment by getsource** [comment]
Hi @Lovor01!
Thanks again for the report.

This issue was discussed in a [triage session today](https://wordpress.slack.com/archives/C02QB2JS7/p1625547926313600). Thanks again for the 

It looks like as was mentioned by @gziolo, more information is necessary for further testing.

Specifically, it'd be helpful to have a simplified / sample project where the issue is able to be reproduced, and the version that worked as expected for you, for comparison.

I'm going to swap out "Needs Testing" for "Needs More Info" for status, since it is going to be difficult to reproduce without this.

**Comment by gziolo** [comment]
We are in the process of upgrading webpack to the next major version v5 in #33818. It might improve the way soruce maps are handled.
