### ISSUE TITLE
Parent block delayed re-render after inner block move in Safari

### ISSUE THREAD

**Issue by tlovett1** [WordPress/gutenberg#30299]
## Description

I've encountered an issue in Safari when inner blocks are moved.  Although the inner blocks move correctly, the parent block sometimes receives the updated inner blocks with their new ordering after a few second delay. This does not happen in Chrome.

This could be related to #30249

## Step-by-step reproduction instructions

I've created a proof of concept block to reproduce the problem:

Code: https://gist.github.com/tlovett1/2c49074bc4ed6931e914bb2bd1bf92d1

## Screenshots or screen recording (optional)

Video showing the problem: 

https://user-images.githubusercontent.com/1844351/112659737-0dba8e80-8e2b-11eb-933c-b3bb4057c0e2.mov

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.2.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Operating system: macOS 10.15.7

**Comment by gziolo** [comment]
Thanks for the report with the very detailed reproduction 👍🏻

It looks similar to https://github.com/WordPress/gutenberg/issues/28166 that seems to be fixed in https://github.com/WordPress/gutenberg/pull/29892 by @ellatrix. We would need to re-test with the Gutenberg 10.3-rc1 and see if it's still valid.

I see another similar report related to nested blocks and Safari in https://github.com/WordPress/gutenberg/issues/19454.

Another one: #29678.

**Comment by Mamaduka** [comment]
I was able to reproduce the issue with Gutenberg 10.3.2 and Safari 14.0.3.

Unfortunately, I'm not 100% sure what the next steps of debugging should be.

**Comment by Mamaduka** [comment]
Same as #30249 and should be fixed by #30995
