### ISSUE TITLE
Reusable blocks: enable usage in Site Editor

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#30308]
## What problem does this address?

This came up as [part of the third FSE call for testing](https://make.wordpress.org/test/2021/03/09/fse-program-testing-call-3-create-a-fun-custom-404-page/#comment-1451). Essentially, while you can create and search for a reusable block when in the Post Editor, you're unable to do so in the Site Editor. 

https://user-images.githubusercontent.com/26996883/112701031-1d4ecd00-8e55-11eb-89c5-e33ed8b74626.mov

## What is your proposed solution?

If this is intentional to help avoid users making bad decisions, feel free to close! For now, my proposed solution is to allow reusable blocks to be integrated into the site editor experience as it might be jarring to suddenly be without the option to utilize reusable blocks.

**Comment by priethor** [comment]
Thanks for following up on this, @annezazu!

I'm not sure the solution is to enable reusable blocks in the site editor but to better let users understand the difference between them. To me, what causes confusion is not being able to add reusable blocks in the site editor, but being able to add template parts in both the site editor and the post/page one.

Otherwise, I would directly think template parts are the equivalent of reusable blocks on a site level, but being able to add both in the post editor creates some overlap that makes me question which of them I should create in each case.

**Comment by annezazu** [comment]
Makes sense! This feels similar to this current experience with the navigation block where only so many blocks are available to be used but the UI doesn't make that clear (it just feels broken): https://github.com/WordPress/gutenberg/issues/30159 

Let's wait to hear from someone who might have more information on whether this is a decision or a missing feature. I can update the issue appropriately from there (either keep it as enable or update to say make the UI clearer).

**Comment by DaisyOlsen** [comment]
My initial reaction to this was pretty dramatic but I'll dust off my site-creator hat for a moment. The power of a reusable block lies in its central management and automatic propagation. Create it once, use it multiple places, modify it in one place with changes reflected instantly, everywhere.

If the solution, as @priethor suggests is to use template parts in a post or page what is the point of having reusable blocks at all other than the obvious answer of backward compatibility? Does this effectively remove their usefulness?

IMO there should be one preferred way to create centrally managed content that can be used in multiple places on a site at will. Right now that is Reusable blocks, if there is a shift to using template parts to fill this need(I'm not necessarily opposed to this) as a better solution the long term then that should be clearly communicated so that site builders can adjust to that way of thinking.

Ending here with a rhetorical question - Are FSE template parts effectively reusable blocks 2.0?

**Comment by priethor** [comment]
It seems the expected behavior should be the opposite as right now:
- Template parts should be available only in template editors (#30668).
- Reusable blocks should be available in both the post editor and template editors (#30669).

I suggest we close this as a discussion issue in favor of those 2 separate issues.

**Comment by gziolo** [comment]
We discussed the same issue on WordPress Slack in #core-editor channel (link requires registration at https://make.wordpress.org/char):

https://wordpress.slack.com/archives/C02QB2JS7/p1618837744030100

I second what @priethor said:

> It seems the expected behavior should be the opposite as right now:
> 
> - Template parts should be available only in template editors (#30668).
> - Reusable blocks should be available in both the post editor and template editors (#30669).

**Comment by annezazu** [comment]
Closing this out based on the above in that case!
