### ISSUE TITLE
Add className and Id to the InnerBlocks component

### ISSUE THREAD

**Issue by Lovor01** [WordPress/gutenberg#30317]
Currently, it is not possible to add class or id as props to InnerBlocks.
I propose adding `className` and `id` props on component, so InnerBlocks container could be easier styled.

**Comment by Lovor01** [comment]
After further thinking, I think they are not necessary after all. They would only apply to editor and you can uniquely style the block with combination of provided classes

**Comment by Netyson** [comment]
Hi, I head the same problem, than I found your issue and was like “why does this not work”. And I started to deep dive into this issue because I needed it to work specially if you work with grid or flexbox layout and you want it to work on the editor to.

So here another solution if is not possible to do it with the given classes and css styles.

One downside of `<InnerBlocks /> `  is that in the editor this creates additional DOM nodes that wrap the markup of the inner blocks.
Since WordPress 5.9 we have the option to use useInnerBlocksProps, this allows us to customize the markup. See: https://make.wordpress.org/core/2021/12/28/take-more-control-over-inner-block-areas-as-a-block-developer/

In Addiotn to that I found https://wordpress.stackexchange.com/questions/390696/innerblocks-breaks-flexbox-and-css-grid-styles & https://wp-gb.com/innerblocks/ that described the issue in more detail and with some example.

With there help i manged to do it like this:

            var blockProps = useBlockProps({ className: 'a-members-grid', style: { gridTemplateColumns: howManyRows,} });
    
            var innerBlocksProps = useInnerBlocksProps(
                blockProps,
                { 
                    allowedBlocks: [ 'arteeo/team-single' ],
                    template: [ ['arteeo/team-single'], ],
                    renderAppender: InnerBlocks.ButtonBlockAppender ,
                    orientation:"horizontal",
                    templateInsertUpdatesSelection: true,
                },

            );

                return [

                    el( "div",{ className: "wp-block-team-grid",  },
                        el( 'section', innerBlocksProps, ),                             
                    )

                ]
