### ISSUE TITLE
Can't continue typing in Firefox after starting an unordered list with the * conversion

### ISSUE THREAD

**Issue by helen** [WordPress/gutenberg#3033]
When I start an unordered list using the `*` formatting shortcut in Firefox, it converts into a list item but I cannot continue typing unless I click where the cursor is. Arrows keys sort of work, although the results are a bit unexpected in general. The stuck typing problem does not appear to affect Chrome (nor the odd arrow navigation, which should probably be a separate issue).

**Comment by ephox-mogran** [comment]
This looks like an obscure cursor position issue in Firefox.

Essentially, the problem is that there is no valid cursor position for typing because the `li` that is created is completely empty (or just has an empty text node). Therefore, Firefox can't position a typing cursor.

This doesn't seem to happen every time, though, because Firefox looks like it tries to insert `br` tags into empty content editable lists in some situations when they are added to the DOM. This gives a valid cursor position. I've experimented with this in the following fiddle (https://jsfiddle.net/h2opp1vL/2/), though it's not quite as deterministic as I would have liked.

The fix is just to make the transform for a core/list block have a br inside the first li item it creates on Firefox. Chrome doesn't need the `br` for a valid cursor position, which is why it doesn't have the same issue. However, it's probably a good idea to put one in there on every browser. Modern browsers (I believe IE11+) tend to replace any `br` tag they see in an empty `li` as soon as the user starts typing.

**Comment by ephox-mogran** [comment]
Any fix that we do here is probably going to be a stop-gap. It should be handled inside tinymce.

**Comment by ephox-mogran** [comment]
A fix to add a cursor position to an empty editable list is in code review in the TinyMCE development team. I'll let you know when it is available.

**Comment by ephox-mogran** [comment]
This has been fixed as of TinyMCE 4.7.2.

**Comment by mcsf** [comment]
Closed via #3388.

**Comment by earnjam** [comment]
Issue does not occur in v4.1.0

**Comment by earnjam** [comment]
Seems to be resolved now in `master` and 5.0 beta 5. 

Not sure when it got fixed exactly. Wish we could get some kind of e2e test on this to prevent it from coming back again.

**Comment by mcsf** [comment]
> Wish we could get some kind of e2e test on this to prevent it from coming back again.

I do too, the problem is targeting browser-specific issues with e2e tests.

**Comment by mrwweb** [comment]
> Seems to be resolved now in master and 5.0 beta 5.

Yup. Not seeing it in FF 63, WP 5-beta5, Win 10.
