### ISSUE TITLE
Implement undo/redo in the widgets customizer

### ISSUE THREAD

**Issue by kevin940726** [WordPress/gutenberg#30400]
Implement undo/redo as shown in https://github.com/WordPress/gutenberg/issues/27343#issuecomment-765644623.

https://user-images.githubusercontent.com/191598/105537781-6d2bdf00-5cc0-11eb-99fb-85af854c0a94.mp4

**Comment by noisysocks** [comment]
Not sure that we should prioritise this. In my mind it wouldn't make sense to add undo/redo to _only_ the Widgets section of the Customizer. I'd instead expect undo/redo to work throughout the Customizer.

I'd prefer that we punt this out of the v1 product that we launch and implement it properly throughout the Customizer some time in the future.

cc. @shaunandrews

**Comment by critterverse** [comment]
Just wanted to chime in to say that I think we should try to include the undo/redo feature in v1 if possible, since these actions are primary functionality that many people rely on in the editor. I worry that the user experience will suffer/be confusing without being able to do this!

Agree that it would be nice to have this functionality across the whole Customizer but it does seem especially important for the launch of the Widgets screen.

**Comment by noisysocks** [comment]
@kevin940726: Any ideas on how to implement this?

Unlike the Widgets screen, we aren't using `core-data` entities which means we don't get undo/redo "for free".

Ideally the undo tree would be stored close to the source of truth is which is the `wp.customize` changeset.

**Comment by kevin940726** [comment]
I'm thinking maybe we should do this in `useSidebarBlockEditor` and store the tree in React though. React should make it easier to implement this feature, and some logics could probably be reused from `core-data`.

**Comment by celloexpressions** [comment]
There is some history of exploring undo/redo in the customizer globally. It would be best to implement this functionality throughout the customizer so that widgets inherit that functionality, instead of only building it out for widgets. I also think adding block editing in the customizer greatly increases the need for undo/redo. 

There are two types of undo/redo: step-by-step during editing and batched revisions. Step-by-step seems like the first priority, and batched revisions would be a great future enhancement (also with a goal to bring that feature to site/template editing in the future).

This is the core ticket for granular undo/redo (note it was originally for a global "reset" button that I still wouldn't support). It includes designs and proposed technical implementation details from a few years ago: https://core.trac.wordpress.org/ticket/21666

This is the core ticket for batched revision management. The underlying technical framework (customize changesets) is already in place (same as the draft and publish features). We "just" need to develop UI to browse revisions. This feature could have a huge usability upside relative to development effort given the amount of backend work already in place. It would likely be straightforward to show a given revision in the customize preview in addition to diff-style changesets.
 https://core.trac.wordpress.org/ticket/31089

**Comment by noisysocks** [comment]
Thanks for the links @celloexpressions.

> Step-by-step seems like the first priority, and batched revisions would be a great future enhancement (also with a goal to bring that feature to site/template editing in the future).

Agreed.

**Comment by kevin940726** [comment]
#30654 just got merged, which should pave the way for the step-by-step undo/redo feature. The core functionality is already there, we just need to implement the UI and improve the performance if needed.
