### ISSUE TITLE
Add unit support to the spacer block (plus unit steps adjustment)

### ISSUE THREAD

**Issue by Jugibur** [WordPress/gutenberg#30437]
## What problem does this address?
I always use em/rems to define sizes.
This has the well-known advantage that all sizes can be defined centrally per breakpoint. This way the spacing grows proportionally to the base font size.
Unfortunately, the spacer block only allows the fixed height in the form of a pixel specification. 
So it would be great if you could select the unit in the spacer block.

## What is your proposed solution?
In addition to the selection of the unit, however, it would be very important in my eyes to be able to specify the sizes of the individual steps in functions.php, which could be set with the slider.
Example: For the unit "em" a step size of ".25em" would be very pragmatic.

These step sizes could then be used in general when using this unit, e.g. for column sizes.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/22956 . Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue. Please reopen if your issue is different than the one mentioned in the issue.
