### ISSUE TITLE
Allow Group blocks to transform into Cover blocks

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#30445]
It's currently possible to transform a Cover block into a group block, but not the other way around. It would be great to add that option in. 

Transform options for Cover Block|Transform options for Group Block
---|---
![Screen Shot 2021-04-01 at 8 11 40 AM](https://user-images.githubusercontent.com/1202812/113292110-0b8c8000-92c2-11eb-96e7-345715d9a550.png)|![Screen Shot 2021-04-01 at 8 12 01 AM](https://user-images.githubusercontent.com/1202812/113292238-3b3b8800-92c2-11eb-9242-cd9920c6a4a2.png)

**Comment by Soean** [comment]
You can't transform a Cover block into a Group block, only wrap a group block around the Cover block (This is possible for every block). You can use `ungroup` to remove the group around the block.

<img width="441" alt="Bildschirmfoto 2021-04-12 um 21 36 07" src="https://user-images.githubusercontent.com/695201/114451075-1c4cc800-9bd7-11eb-984e-a985d9ddeb84.png">

If we add the ungroup option to the transfer dropdown, we should build for all blocks, not just for the cover block.

**Comment by ntsekouras** [comment]
I personally can't find much value in this transform, as `Cover` block needs user input to initialize and we'll have to make arbitrary choices about them. This can confuse users I think. Maybe by having extra checks for having an Image block in group's InnerBlocks and use that as the Cover's background 🤔  ?

Even that would need more changes since the `isMatch` from `transforms API` would need to be extended to provide the `innerBlocks` as well and not only the attributes.

Reference: https://developer.wordpress.org/block-editor/reference-guides/block-api/block-transforms/#block

**Comment by getsource** [comment]
I'm not sure if it's better for me to reply here or in the PR.

It's worth noting that this does not require user input if there is an existing background of some sort, but I hear you.
I'm mostly thinking it might be easier for a user to take this path, if they started out with a group, and decided to move to a cover block. Could also only allow the transform when that's the case, but that blocks users from migrating a group when they intend to add an image to the background.

I thought about adding something to migrate an image from `innerBlocks`, but I also wonder if that would be confusing, since it'd be difficult to know which image to pick, and could generate user surprise. I suppose with the previews, it would show the user what would happen, though. I can try to put together a path of some sort to do that, if folks think it'd be helpful.

**Comment by kjellr** [comment]
Perhaps we only make this available for Group Blocks that have a solid color background set? Then there's a clear 1:1 cover block equivalent to transition to. (Once https://github.com/WordPress/gutenberg/issues/14744 is resolved, there should be more possibilities here too).

**Comment by ntsekouras** [comment]
>It's worth noting that this does not require user input if there is an existing background of some sort

>Perhaps we only make this available for Group Blocks that have a solid color background set?

Handling `Group` blocks that have background/gradient should work well with the current API `isMatch`. Agreed.

Also I'm not aware if we can extract the theme's main background color programmatically to set as `background` to `Cover` if not one is set..

**Comment by kjellr** [comment]
> Also I'm not aware if we can extract the theme's main background color programmatically to set as background to Cover if not one is set..

Yeah, I'm not sure that we can. Though it might get easier to do that if the theme's defined a background via theme.json.

**Comment by getsource** [comment]
Updated the PR to only offer transformation to cover when a background color or gradient is available in the Group block.
