### ISSUE TITLE
experimental-theme.json: Workarounds for using REM values?

### ISSUE THREAD

**Issue by andersnoren** [WordPress/gutenberg#30491]
This is less of a feature request than a feature... question. When using REM values in CSS, the `html` element is frequently set to `font-size: 62.5%` to make 1rem equal 10 pixels. See [this article](https://snook.ca/archives/html_and_css/font-size-with-rem) for details.

In experimental-theme.json, my understanding is that you set the base font size of the document this way (copied from TT1 Blocks, with other properties removed):

```
{
	"styles": {
		"root": {
			"typography": {
				"fontSize": "var(--wp--preset--font-size--normal)",
			}
		}
	}
}
```

This applies the `var(--wp--preset--font-size--normal)` variable to the `font-size` property of `.editor-styles-wrapper` in the editor, and to the `html` element on the front-end. Applying it to the `html` element on the front-end means that the 1rem = 10 pixels approach can't be used, since the font size property of the `html` element is already occupied by the font size set in experimental-theme.json. Setting the `body` element to `font-size: 62.5%` will result in 1rem = 62.5% of the font size value defined in experimental-theme.json.

My question is whether there is a good workaround for this. Is it possible to use experimental-theme.json to apply a font size to the body element on the front-end and the `.editor-styles-wrapper` in the editor, for example? I understand why the `:root` is used to hold the CSS variables, but base styles for the document as a whole (font sizes, line heights, colors, font families, etc.) are usually applied to the body element.

**Comment by aristath** [comment]
The `font-size: 62.5%` was a great workaround to allow calculating rem values based on a 10-pixel base font-size, but since in Gutenberg users can tweak the root font-size via global-styles, I'm not sure it fits in the vision of what the web should be...
Doing `font-size: 2.4rem` to define a `24px` font-size might make sense from a math/calculations perspective, but it doesn't make a lot of sense if we consider that the default root font-size is `16px`... I mean why change the root font-size to `10px` and then calculate everything based on that, when we can simply define `24px` as `1.5rem`? 🤔 

I believe it would be best if we build pixel-agnostic themes instead of pixel-specific... As for a workaround, the only thing I can think of would be to define a `--rem` css-variable in theme.json, and then use that in styles.
So something like this maybe? (assuming `--wp--preset--font-size--normal` is `16px` here)
```json
{
	"settings": {
		"defaults": {
			"custom": {
				"typo": {
					"rem": "calc(var(--wp--preset--font-size--normal) / 1.6)"
				}
			}
		}
	}
}
```

Then in a stylesheet the theme could have something like this:
```css
body {
  --rem: var(--wp--custom--typo--rem); /* Just making the var-name shorter)
}

h1 {
  font-size: calc(2.4 * var(--rem));
}
```
but that might be overkill...

**Comment by andersnoren** [comment]
Yeah, the 62.5% workaround has always been more developer driven (round numbers, jay!) than user driven. I still think using the HTML element for the root font size will have detrimental effects though, and effectively mean that you won’t be able to use the REM unit instead of pixels in themes with Global Styles, regardless of whether you use the 62.5% font size approach or not.

For example, let’s say that the theme is using REM values throughout, in combination with a `[root][typography][fontSize]` value of 20 pixels. So if the theme developer wants a group padding of 32 pixels, he/she sets it to `1.6rem`.

However, the user running the theme decides that a font size of 20 pixels is too small, so he/she bumps it to 24 pixels in the Global Styles to make the base text larger. When the user visits the site, the user discovers that the change has not only increased the font size, but all margin/padding/borders/transforms on the site, making the site as a whole 20 percent larger. Effectively, on a site styled with REM units instead of pixels, the user won’t be able to change the root font size without also changing the dimensions of pretty much all other elements on their site.

For new FSE themes, we could simply say that REM units shouldn’t be used, but any REM-based themes that want to add Global Styles support after the fact would be forced to change all of their units from REM to pixels. That’s a pretty big obstacle.

It seems to me like this could all be avoided pretty easily by moving the `[styles][root]` properties on the front-end from the html element to the body element.

**Comment by aristath** [comment]
> Effectively, on a site styled with REM units instead of pixels, the user won’t be able to change the root font size without also changing the dimensions of pretty much all other elements on their site.

That's not necessarily a bad thing though... Personally, I consider it a plus!
My content-width is always expressed in `em` values to make sure that the content is readable at all screen sizes... so usually I have something like `max-width: 52em` for the content, with `1em` padding on the side.
If the user changes the font-size, then I want the content-width to also change accordingly, and the padding will need to change proportionately to reman a bit balanced.
It's not a bad thing, it's just a different way of looking at things. The `32px` padding makes sense if my font-size is 16px, but does it make sense if I set my font-size to 32? Or should it also adapt? Is the fact that an rem-based theme adapts a bad thing? `rem` is relative, so why should it _not_ adapt to the user-selected font-size? 🤔

**Comment by andersnoren** [comment]
It won't just effect the content area though, but all sections of the site: The header, footer, contact forms, the WooCommerce store, the size of the logo, the target size of the navigation button... A user looking to tweak the body font size of their site likely won't expect layout changes as a result, and won't be able to make changes to the body font size without affecting the layout if the site is running a REM based theme with Global Styles support.

My main point is that while we can and should have discussions about which approach works better, WordPress shouldn't force theme authors into one approach when it very easily can allow for multiple :) Which brings me back to this:

> It seems to me like this could all be avoided pretty easily by moving the [styles][root] properties on the front-end from the html element to the body element.

**Comment by aristath** [comment]
> My main point is that while we can and should have discussions about which approach works better, WordPress shouldn't force theme authors into one approach when it very easily can allow for multiple :)

Agreed.

I think the main difference here is the way we perceive "root" in global-styles?
When I change the root font-size in global styles, I expect it to change the font-size for the site, not just the content, because "root" to me is the site. So yes, it will also change the font-size for headers, footers etc. If I want something to not be related to that, then I just use px or some other unit which is not related to the root font-size. Since users can use em, rem etc values when editing things in their global styles, they will probably expect the rem values they enter for padding etc to be relevant to the value they used for their root font-size.
If the root font-size is decoupled from the root element and instead it's on the body, then how will it behave as a root font-size in rem values that users enter in global styles? 🤔

**Comment by andersnoren** [comment]
> When I change the root font-size in global styles, I expect it to change the font-size for the site, not just the content, because "root" to me is the site.

Completely agreed. The unintentional changes come into play when the REM unit is used not just to set font sizes, but for all other properties as well (padding, margin, transform, border, width, height, etc). When a logo is set to a maximum height of 10rems, and the HTML font size is reduced by 20 percent to reduce the base font size of the site, the max height of the logo will also be reduced by 20 percent.

> Since users can use em, rem etc values when editing things in their global styles, they will probably expect the rem values they enter for padding etc to be relevant to the value they used for their root font-size.

I didn't know Global Styles would support different units - when I add a unit suffix to any "Custom" font size field in Global Styles, the "Update Design" button gets disabled. Is this something that's coming down the road, or can the theme enable it in experimental-theme.json?

> If the root font-size is decoupled from the root element and instead it's on the body, then how will it behave as a root font-size in rem values that users enter in global styles? 🤔

Theme authors could still opt-in to this behavior by setting the font size of `html` to the variable they've set `[root][typography][fontSize]` to. With the current structure, theme authors can't opt out of it.

**Comment by aristath** [comment]
Yes, font-sizes will support custom units too!
I was under the impression that part was already working but I checked again and can see it's not right now... I'll need to investigate 👍 
There's also the ability to have custom paddings in some blocks (like cover, group, template-part and others), that part can be enabled using `spacing` in theme.json: https://github.com/WordPress/gutenberg/blob/7b96d882cbfd775c2ece472cb11010006700fad0/docs/how-to-guides/themes/theme-json.md#settings

**Comment by kjellr** [comment]
It sounds like this one can probably be closed out for now, given that global styles supports multiple units. @aristath / @andersnoren does that sound right?

**Comment by andersnoren** [comment]
@kjellr This issue is more about the `root:typography:fontSize` being applied to the html element, preventing the use of the `html { font-size: 62.5% }` [structure](https://snook.ca/archives/html_and_css/font-size-with-rem) (which sets 1rem = 10 pixels). It means that any developers that currently use the 1rem = 10 pixels structure in their CSS will need to switch to pixel values instead when they build block themes. 

I don't mind it, but people used to the 1rem = 10 pixels approach in their CSS will probably grumble a bit about it not being possible in themes using global styles with a base font size.

**Comment by carolinan** [comment]
They are applied to the `<body`>, not `<html>`, did I misunderstand something?

**Comment by adamwoodnz** [comment]
Closing following triage policy

**Comment by fclaussen** [comment]
My problem is similar to this. I have a site that uses a third-party supplied set of CSS files for existing components like buttons, tabs, etc... They are setting font-size to 10px or 62.5%.

We've integrated everything so that the blocks look good in the editor. I had to enqueue an additional css in the editor side to change the html font-size to 10px in order for the proportions to fit their styleguide. It all works.

Fast forward to now where there's a new request that would make sense to do using FSE so the goal is to transition some of their parts like header/footer to FSE. Then I noticed that when the theme is FSE it adds an iframe. In that Iframe I cannot update the html tag to be 10px which blocks me from moving forward with what I wanted to do.
