### ISSUE TITLE
Custom post types without `show_in_rest` cannot load editor

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#3066]
Previously: https://github.com/WordPress/gutenberg/issues/1342#issuecomment-319920850

This has been known and I assumed there was an issue, but a major blocking issue to relying on the REST API for building a post editor is that a custom post type must explicitly opt in to being available through the REST API, and therefore Gutenberg cannot load correctly otherwise.

Options for moving forward:

- Load classic editor for these post types
- Eliminate dependency on core REST API
- Revise REST API permissions to allow access to non-whitelisted post types in administrative contexts
   - See https://github.com/WordPress/gutenberg/issues/1342#issuecomment-319920850

**Comment by joehoyle** [comment]
I created https://core.trac.wordpress.org/ticket/42785 to get some progress on better defaults for content included in the REST API. This doesn't quite address all the cases here such as "private" post types, which I think we can also push ahead.

**Comment by danielbachhuber** [comment]
_Cross-posting from the Trac ticket_.

I'm unconvinced that `show_in_rest` should become opt-out instead of opt-in.

Given custom post types probably have custom editor UI (metaboxes and otherwise), it seems unlikely that Gutenberg will be a drop-in replacement for the existing UI. Also, I'm concerned we'd unintentionally expose data we don't mean to expose.

Lastly, such a significant change *certainly* shouldn't be in a minor release.

For the purposes of Gutenberg, loading the Classic Editor for post types with `show_in_rest=false` seems sufficient to me.

**Comment by dd32** [comment]
> I'm unconvinced that `show_in_rest` should become opt-out instead of opt-in.
> 
> Given custom post types probably have custom editor UI (metaboxes and otherwise), it seems unlikely that Gutenberg will be a drop-in replacement for the existing UI. Also, I'm concerned we'd unintentionally expose data we don't mean to expose.
> [snip]
> For the purposes of Gutenberg, loading the Classic Editor for post types with `show_in_rest=false` seems sufficient to me.

I personally agree with the above reasoning, it seems that falling back to the Classic Editor for post_types not supporting `show_in_rest` is the most compatible and perhaps expected behaviour here.

That means that this has been fixed by 5390ea2c98b76905abe0bab5b8eaeed0a3576aa0 & #3146

**Comment by dd32** [comment]
Going to close this in preference for https://core.trac.wordpress.org/ticket/42785 - Gutenberg acts correctly here, when/if cores defaults change those post_types will pick up Gutenberg if the other conditions are met.
