### ISSUE TITLE
InnerBlocks: Create a clickable label or component to add additional context to an inserter

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#30688]
## What problem does this address?

In #29851 we want to add some additional context to the inserter button for the social links. Using the selected state, and the placeholder prop, we can add the "Add link" text, however we want this text to truly be a label for the inserter so when clicked it will have the same action.

![](https://user-images.githubusercontent.com/1204802/111133059-60b65b00-857a-11eb-9c04-f3f180218449.gif)

## What is your proposed solution?

My initial thought is to add an `InserterLabel` prop that can get passed down and then rendered alongside the button, however I'm open to alternate solutions. Should it be a component to allow additional customization?

**Comment by stokesman** [comment]
I got curious about this, gave it try, and applied it in the Social Icons block #30848. I'm not eager to see it land because if the main concern is the placeholder state of that block, I think there is probably a better way to improve it.

>Should it be a component to allow additional customization?

I think that would be getting too close to redundancy with `renderAppender`.

**Comment by mkaz** [comment]
This is no longer relevant as the inserter and InnerBlocks have been refactored and modified various times for Navigation block, this can be achieved in new wyas.
