### ISSUE TITLE
Discussion: What should take over for the Theme Editor?

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#30695]
In this issue: 
https://github.com/WordPress/gutenberg/issues/29630
@jameskoster is exploring new drop down links within the Appearance menu that is related to Full Site Editing.

![Appearance-themes-screen](https://user-images.githubusercontent.com/5323259/114247465-6e061000-9995-11eb-8032-37c45de42ec7.jpg)

One of the links that is being removed is the Theme Editor the area where one can go directly to the various files to modify example the functions.php file to add in code snippets etc, style.css and other files within the themes area.

What should take over so that we can easily go in and make adjustments directly in the files?

**Comment by celloexpressions** [comment]
Is there a reason that the theme code editor wouldn't work with the new FSE features? The Additional CSS feature in the customizer was envisioned as a potential long-term replacement for the theme code editor. If there is consensus around deprecating the theme file editor, that could be a potential replacement. See [the original feature proposal for more information](https://make.wordpress.org/core/2016/10/11/feature-proposal-better-theme-customizations-via-custom-css-with-live-previews/).

**Comment by carolinan** [comment]
This menu item is still needed and should not be removed.
Adding new CSS only is not the equivalent to editing theme files.

There are theme files that are not related to templates or CSS like a functions.php file that is needed to include other functional files like:
register block patterns
register block styles, enqueue CSS for the block styles -_Block style CSS can not be created using theme.json because of the wp-custom naming convention_
enqueue JS

There will also be a period where this is needed until global styles are completed  -for example to enqueue remote fonts -
and until there is a code editor mode in the site editor.

**Comment by jameskoster** [comment]
Since Templates, Styles, Header, Footer etc can each be considered aspects of theme editing, might it be worth changing the label on this menu item? I worry that the "Theme Editor" link might inadvertently lure newer users to an unnecessarily advanced (and potentially dangerous) UI rather than the newer (user-friendlier) alternatives.

Perhaps something like Appearance > Advanced, or Appearance > Code Editor would better describe how this feature sits along side the other site editing functions?

**Comment by bkjproductions** [comment]
The existing code/theme editor is one of those things that usually I have to disable for clients anyway. I would wonder why have it at all, now that the block editor seems to require more serious programming skills (if you're going to mess around in PHP/JS/React) and allowing the novice to willy-nilly change code might encourage sloppy coding.

**Comment by annezazu** [comment]
Noting that it's now called the Theme File Editor and, for block themes, we simply show "Themes" and "Editor".

![Screenshot 2023-10-27 at 8 37 34 AM](https://github.com/WordPress/gutenberg/assets/26996883/8c52914d-3be9-472c-8d54-50cc02972726)

I think this issue can be closed out as I'm not sure how relevant it is today. Happy to reopen of course if I'm missing something or if we can get some fresh thoughts :)

**Comment by paaljoachim** [comment]
Wow nice! Thank you for sharing Anne! I have not thought about this aspect of WordPress for quite a while.
