### ISSUE TITLE
[FSE] Clarify what is being reverted when clearing template customizations

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#30773]
## What problem does this address?

When reverting a template to the theme default, the initial expectation is that _everything_ you're looking at will reset when, in truth, only parts will. Here's a quick video showing this:

https://user-images.githubusercontent.com/26996883/114453474-cbb57a80-9b96-11eb-9b9f-cf309bd8fd4d.mov

Because it's not clear what's a template vs a template part, this makes for a somewhat confusing experience and came up during recent user testing. 

## What is your proposed solution?

Perhaps having a block outline of what will be reverted? Or showing what will change using the List View to confirm reverting? I'm not quite sure as this seems like a design problem that falls in line with other related issues around distinguishing types of content. 

cc @jameskoster for thoughts here (no rush). Feel free to close out if this is already being worked on!

**Comment by jameskoster** [comment]
This is a little bit tricky because we need to account for situations where the template parts are customised, but the parent template is not.

I think the clearest way to achieve this would be to list the template parts in the template details popover and provide a revert link there.

We actually have an issue for listing the parts [here](https://github.com/WordPress/gutenberg/issues/29147).

It doesn't feel like a big leap to provide a revert action (and others) via ellipsis menu:

<img width="607" alt="Screenshot 2021-04-13 at 10 20 11" src="https://user-images.githubusercontent.com/846565/114529495-e8f35300-9c41-11eb-8bab-169559fa2820.png">

We can potentially re-use this interface in other areas where template parts are listed (List View).

Edit: Adding blocked label (#29147).

**Comment by annezazu** [comment]
Wow! Excellent thinking.

**Comment by annezazu** [comment]
Noting that this can be closed when this is merged: https://github.com/WordPress/gutenberg/pull/41765 cc @ntsekouras  for awareness
