### ISSUE TITLE
Improve flow for previewing unsaved pages/posts

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#3087]
## Issue Overview

If you load the demo content and press Preview before the content has saved, you get an empty new tab on the URL `about:blank`, which sits there for a few seconds, and then it redirects you to the preview.

What happens in the background is that as soon as you press preview, we actually do save the content, but we also open the browser tab where the preview will eventually load.

The wait period is a bit jarring, though:

![preview](https://user-images.githubusercontent.com/1204802/31822991-e45f5ca2-b5aa-11e7-95fb-cc8e667ea691.gif)

It would be nice if instead of loading `about:blank`, we could load something else, an intermediate page that says "Preparing your preview" or something. Doesn't have to be complex, can be a completely white page with the text centered.

**Comment by aduth** [comment]
A bit of technical context:

Popup windows can only be opened in response to user interaction. Therefore, we must open the popup as soon as the user clicks Preview, otherwise we won't be permitted to do so later (can't perform the save in the editor first before showing).

The process is:

1. User clicks Preview
2. Popup window is opened to blank page
3. Post is saved
4. After post finishes saving, blank page is redirected to preview

While we could direct the user to another page, since there'd be a load time associated with this, another option might be to write directly to the blank page with our intermediate messaging.

Demo: https://codepen.io/aduth/pen/jGJaYX

**Comment by jack-lewin** [comment]
I've [started work on this](https://github.com/WordPress/gutenberg/compare/master...jack-lewin:preview-popup-loader), will try and make a PR tomorrow.

**Comment by aduth** [comment]
Considering this as closed by #3157
