### ISSUE TITLE
API for adding a -top- Toolbar Button

### ISSUE THREAD

**Issue by mostl33** [WordPress/gutenberg#30901]
Hi there,

is there an API to add a Button to the Top-Toolbar? I can't find anything (just unanswered posts):

![image](https://user-images.githubusercontent.com/73604048/115005034-bcd90b80-9ea7-11eb-80a0-4d0cd8cfd410.png)

Thanks in advance & thanks for this _great_ project -!-
mostl33

**Comment by gziolo** [comment]
> Thanks in advance & thanks for this great project -!-

❤️ 

> is there an API to add a Button to the Top-Toolbar? I can't find anything (just unanswered posts):

It isn't possible at the moment with the extension points that exist in the editor. It was discussed many times but it never happened mostly because the primary way to include an item in the toolbar is through the More Menu on the right side and the concept of pinned items. The reasoning always was to improve the current way of extending the UI before opening more places in the editor for extensibility.

<img width="305" alt="Screen Shot 2021-04-19 at 15 46 06" src="https://user-images.githubusercontent.com/699132/115246753-76ddab00-a126-11eb-8f08-f86f3661dddc.png">

**Comment by TomasHurtz** [comment]
Hello 

I too would like to know how best to add top toolbar button in Gutenberg page / post editor.

![Edit-page - top-toolbar-WordPress](https://user-images.githubusercontent.com/17046561/169166820-584da664-0372-4292-b81f-df1f39941a72.jpg)


[Here is a useful example](https://stackoverflow.com/questions/62105561/adding-button-to-header-of-gutenberg-editor-in-wordpress-through-plugin) I have not tried yet - but it seems there are few resources on this matter.

For example, if one wishes to replace the "W" logo at the top left of the editor, with a drop down instead...

**Comment by gziolo** [comment]
This issue https://github.com/WordPress/gutenberg/issues/16988 from @ryanwelcher looks like a very similar proposal. There is also a broader discussion in https://github.com/WordPress/gutenberg/discussions/37448 about making the editor’s interface more extensible.

**Comment by ryanwelcher** [comment]
@TomasHurtz there is an existing SlotFill for that location that you can use to modify the W logo. See - https://developer.wordpress.org/block-editor/reference-guides/slotfills/main-dashboard-button/ Just keep in mind they are marked as `__experimental` and may change in the future.

If there is interest, I'd love to pick up that old issue/PR and see where we can take :)

**Comment by jordesign** [comment]
With https://github.com/WordPress/gutenberg/issues/16988 looking very similar - I'll close this in favour of that issue.
