### ISSUE TITLE
Page Template: Not able to cancel save of page template.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#31043]
I am going through the process of creating an user interface for the new page template feature.
One thing that bugs me over and over is that I am not able to cancel the save of a template/reusable block etc etc.

It should be as simple as unchecking an option to not save it. Having it automatically revert back to nothing or to the last save.

Here is the Page template save process at the moment. It starts out inside the Page template area.

https://user-images.githubusercontent.com/5323259/115561409-d28a6e80-a2b5-11eb-8210-edb8b6be1453.mp4

Possible solution:
Uncheck options to move onward to publish.

**Comment by paaljoachim** [comment]
A simple solution would be to uncheck what one does not want to save.
An example. Discarding to save a page template would bring one back to the Pages screen with use of the default page template. As discarding to save a page template would also delete the page template one initially created but decided later on not to save.


https://user-images.githubusercontent.com/5323259/115725313-0763f780-a382-11eb-9e74-bcfa31ced237.mp4

**Comment by jameskoster** [comment]
I _think_ we can potentially close this one since https://github.com/WordPress/gutenberg/pull/30793 is merged :) In the video below I demonstrate editing a post and a template in the same session, but only saving the changes to the post:

https://user-images.githubusercontent.com/846565/115752433-ffac4f00-a391-11eb-8c30-86e0186137ea.mp4

To discard the template changes you simply exit the editor.

It may be worth exploring a dedicated "Discard" action that could be applied to any entity in the multi-entity save flow, maybe  something like:

<img width="312" alt="Screenshot 2021-04-22 at 17 46 08" src="https://user-images.githubusercontent.com/846565/115753078-adb7f900-a392-11eb-8a17-6a2a276e3581.png">

But really that's not doing much different to just un-checking the checkbox.

**Comment by paaljoachim** [comment]
That is the best Discard suggestion I have seen. Discard text link seen beside each item that is to be saved.
Simple and straight forward approach. This can also be used for Reusable blocks. @critterverse 
https://github.com/WordPress/gutenberg/issues/29871

(Users might uncheck first and then click the Discard link.)

One more thing Discarding also needs to result having the Publish dot removed, as it needs to know that specific items will not be saved and are discarded.

**Comment by annezazu** [comment]
Going to go ahead and close this out considering this seems to be covered in the issue Jay mentioned above. Further, this issue relates to what's described here as the changes should be disregarded when switching between modes: https://github.com/WordPress/gutenberg/issues/27896 Love seeing the creativity here in how to tackle this thorny problem!
