### ISSUE TITLE
Page Template: Change button word "Apply" to "Save"

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#31091]
In an issue @jameskoster suggested we make a change to a button that said "Design" (in FSE) to "Save".
I am suggesting we stick to the word "Save".

Current:
![Page-template-apply](https://user-images.githubusercontent.com/5323259/115722679-84da3880-a37f-11eb-83f6-cc13e8a57850.jpg)

New:
![Page-template-Save](https://user-images.githubusercontent.com/5323259/115722705-8ad01980-a37f-11eb-8bfd-9b6116e39baa.jpg)

https://user-images.githubusercontent.com/5323259/115724139-f797e380-a380-11eb-95c4-3c6d263033b7.mp4

**Comment by jameskoster** [comment]
Since https://github.com/WordPress/gutenberg/pull/30793 the save flow between post and template editors has been unified, so we may be able to close this issue?

One thing we might explore is the label on the primary button in the post editor top bar now that these save flows have been connected. In the Site Editor we use a single "Save" button which works quite well. In the post/template editor(s) we have "Publish", "Update", and "Schedule" buttons, based on the status of the post. 

Because it is now possible to edit all kinds of independent entities (reusable blocks, templates, template parts, site properties like title / tagline / logo, and so on) in the midst of editing a post, labels like "Schedule" lose some contextual value. In the worst case this particular label is confusing – "Can I schedule a change to my _Site Title_?". 

Some ideas relating to this have already been discussed in https://github.com/WordPress/gutenberg/issues/30800, so perhaps we should continue the conversation there?

**Comment by paaljoachim** [comment]
I will go ahead and close this issue. Let's as you say continue the conversation in #30800 .
