### ISSUE TITLE
Query Block: Change "Inherit query from URL" language 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#31113]
## What problem does this address?

[This came up as part of the fifth call for testing](https://make.wordpress.org/test/2021/04/14/fse-program-testing-call-5-query-quest/#comment-1501) for the FSE Outreach program from @getdave and from a member of the Japanese WordPress community:

>Inherit query from URL – this wording needs to be made less technical. Perhaps just “Use default query items for this page”.

>I thought that if difficult to understand the language, such as "inherited a query from URL".

>It is hard to understand the words, Query, Global Query.

## What is your proposed solution?

Here are some ideas:

- Dave suggested “Use default query items for this page”. 
- Use default options
- Use default settings
- Use default query

**Comment by Sandstromer** [comment]
My personal opinion would be for the Query Block to default initially to the "Inherit query from URL" state like it does now but there would be no mention of inheriting the query or using default query.
So, instead of deselecting this, the user would select an option something like "Customize the query" to change the query arguments.

Doing this the other way round feels more natural to me, and possibly easier for a non-dev user to understand?

**Comment by aristath** [comment]
Some background here:
Instead of a switch the initial PR had a checkbox to "customize the query". The checkbox was then replaced by a switch, and in the switch it made more sense to change the label to reflect what it does.
The Query block was always considered a developer tool and AFAIK the plan was to allow user interaction with it via variations without actually exposing the query block itself. With that in mind, the language of the switch was more developer-oriented than what users would expect.

Using the term "default" would make sense, and if we do plan to expose the block to end-users, then yes, we need to change the label.

**Comment by priethor** [comment]
It's worth noting that this came up during the [WP 5.8 FSE Go/No-go demo](https://make.wordpress.org/core/2021/04/15/full-site-editing-go-no-go-april-14-2021/) as well.

**Comment by ntsekouras** [comment]
Resolved here: https://github.com/WordPress/gutenberg/pull/32694
