### ISSUE TITLE
Post Title: deleting the block crashes the parent group block

### ISSUE THREAD

**Issue by vindl** [WordPress/gutenberg#31115]
Steps to reproduce:

1. Open the Site Editor on a test site that has TT1 Blocks theme active.
2. Open the page template from the browsing sidebar.
3. Select the Post Title block and press `delete`.
4. Notice that the containing group block crashes and display "This block has encountered an error and cannot be previewed." error message.

Before:
<img width="1788" alt="Screen Shot 2021-04-23 at 3 09 42 AM" src="https://user-images.githubusercontent.com/1182160/115803563-715fb980-a3e1-11eb-9c47-cec175b29a57.png">

After:
<img width="1786" alt="Screen Shot 2021-04-23 at 3 10 05 AM" src="https://user-images.githubusercontent.com/1182160/115803571-73c21380-a3e1-11eb-9519-2028c6ff3359.png">

**Comment by JustinyAhin** [comment]
I've tried to reproduce this, but I can not.

When I press `delete` on the post title, it rather deletes the characters in the title.

My setup:
WordPress 5.8-alpha-50761
Gutenberg  10.5.3 only activated
TT1 blocks

macOS 11.1
Firefox Developer Edition 89.0b6 


https://user-images.githubusercontent.com/33403964/116860191-199f2a80-abf9-11eb-86c1-81cdd2e0fa04.mp4

**Comment by devfle** [comment]
I can confirm it. Steps to reproduce:

1. Add group block to your site
2. Insert a random block inside it e.g. shortcode
3. Save / publish the page and reload it
4. select the block inside the group block
5. press backspace and delete it.

The group block crashes an the console fires some exceptions e.g. "Uncaught Error: An error occurred while running 'mapSelect': Cannot read property 'title' of undefined"

**Comment by JustinyAhin** [comment]
> I can confirm it. Steps to reproduce:
> 
>     1. Add group block to your site
> 
>     2. Insert a random block inside it e.g. shortcode
> 
>     3. Save / publish the page and reload it
> 
>     4. select the block inside the group block
> 
>     5. press backspace and delete it.
> 
> 
> The group block crashes an the console fires some exceptions e.g. "Uncaught Error: An error occurred while running 'mapSelect': Cannot read property 'title' of undefined"

I'll give a look again. I've likely not reproduced correctly

**Comment by bbertucc** [comment]
I found this same issue when deleting a block in the footer while using Site Editor. The block was the only block in the footer. When deleting it, this popped up..
<img width="481" alt="Screen Shot 2021-05-04 at 3 43 58 PM" src="https://user-images.githubusercontent.com/46652/117067479-afb57c80-acef-11eb-9ece-aa74739a763b.png">

**Comment by david-szabo97** [comment]
**UPDATE**: After some extensive investigation, it looks like this problem occurs in any container blocks.

Error is happening in `useBlockProps`, at different points usually. But mostly it happens at 

https://github.com/WordPress/gutenberg/blob/6d977df25ba32cec009380c436ccffb26e0d8562/packages/block-editor/src/components/block-list/use-block-props/index.js#L96

The block is still being rendered after it's deleted. The `useSelect` on line 72 is called because the store state changes so it runs again and crashes the block because the block state doesn't exist anymore in the store state.

I couldn't figure out why but using the "Remove block" option from the dropdown doesn't cause any crashes. So it's tied to the backspace keyboard shortcut in some way 🤔 

Investigating further....

**Comment by leutrimhusaj** [comment]
I think after merge of #32088 this could be closed.
