### ISSUE TITLE
Search Block: Add icon-only option

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#31128]
## What problem does this address?

The search block comes with a number of easily configurable defaults:

![search](https://user-images.githubusercontent.com/1204802/115863906-6daa5200-a436-11eb-8cd8-79d9c8d7515e.gif)

Including:

- It's resizable
- Label can be toggled
- Button can be an icon button
- Button can be toggled off, shown outside, or shown inside

One nice addition would be the ability to show only the icon.

## What is your proposed solution?

Add an option to show just the search button:

<img width="674" alt="Screenshot 2021-04-23 at 13 21 25" src="https://user-images.githubusercontent.com/1204802/115864195-d7c2f700-a436-11eb-9698-07cf72f8a345.png">

On focus the input field would then expand to allow search.

**Comment by carolinan** [comment]
This setting was once removed, so is there anything that can be reused from the code that was removed?

**Comment by carolinan** [comment]
This might be obvious but the expanded input field also needs to be more visible than in the image above 😄 

Displaying the input field on focus is not a good option, what if the person is trying to navigate past the search icon instead of opening it. It should only expand on explicit user action like pressing the button.

**Comment by karmatosed** [comment]
Oh my this little feature has a lot of options.

> One nice addition would be the ability to show only the icon.

I think this is going to be very popular and useful, however I think that finding a balance in how it happens is important.

@carolinan when you say this:

> It should only expand on explicit user action like pressing the button.

Do you mean when clicking the icon? I can see that sort of working where you click the icon and it expands but the issue is clicking is also meant to 'perform the search' so there's a bit of 'double duty' going on for the interaction.

**Comment by carolinan** [comment]
So there needs to be two buttons, one to open the "modal" that displays the input field, and one to submit.
This would also be true if the input field was opened on focus.

**Comment by talldan** [comment]
Just noting for anyone looking to pick this up that there was a PR for this - #31719, and it might be a good starting point for anyone looking to contribute.

**Comment by kathrynwp** [comment]
A request to have an icon-only search option came in via the forums:

https://wordpress.org/support/topic/search-block-options/

This would be a great enhancement.
