### ISSUE TITLE
Presets used in patterns: register them as user presets?

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#31124]
One issue we have with patterns is that presets (colors, font sizes, font-families) they may want to use (as classes) may or may not be available depending on which theme is active ― presets are registered by the theme itself and different themes register different presets. What end ups happening in most cases is that patterns use inline styles to make sure they work.

I was thinking about this in the context of https://github.com/WordPress/gutenberg/issues/29568 which aims to introduce three color palettes: core, theme, and user. If we look at patterns as blocks and styles that users could have added by themselves, how a user would have added colors that aren't available in the theme? By adding them to the user palette.

So, as a follow-up work from https://github.com/WordPress/gutenberg/issues/29568 and it relation to the pattern directory as well, would it make sense that:

- patterns can register the preset colors they use in the user color palette?
- extend the concept of core/theme/user to other presets such as font-size and font-family?

cc @mtias @kjellr @carolinan @jasmussen @aristath

**Comment by jasmussen** [comment]
Yes, this is a good one. It's adjacent to switching themes as well, and I encountered it in #30831 where the navigation block could not rely only on `has-background` to be sure that a background color was present, because `has-red-background` might have been present in one theme but not the next.

I think @pbking, @MaggieCabrera and @scruffian might have encountered related challenges and have ideas as well.

Ultimately though, I think we can get pretty far by just having a few consistently available palettes always be there.

**Comment by MaggieCabrera** [comment]
What happens if a pattern registers a preset that conflicts with one from the theme? Like a pattern would define red/primary differently than the theme would? 

I like the idea of always having a default presets for things like font size and family that will always exist regardless of the theme

**Comment by kjellr** [comment]
In many cases, users will want to change colors immediately after they add a pattern. So if we do add a feature like this, I think we should be sure to automatically remove any unused pattern preset colors. Otherwise I imagine you'll just get a big buildup over time of colors that you're not using. 

But as folks have mentioned above, I think that having a single consistent palette will go a long way to helping us. I suggest we try that out and then see if an idea like this still seems useful.

**Comment by carolinan** [comment]
Presets would be a good start but I hope custom styles will also be considered (issue linked above), as well as how to handle images in patterns.

**Comment by oandregal** [comment]
Going to close this one. Thus far, there's no plan to do this and we just shipped in WordPress 5.8 the ability to use core colors in addition to theme ones.
