### ISSUE TITLE
Legacy  widget should not be "previewable" in the customizer

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#31139]
It makes no sense to preview a legacy widget when using the `LegacyWidget` block in the Customizer since there is a better and full page preview on the screen.

<img width="1215" alt="legacy-preview-customzier" src="https://user-images.githubusercontent.com/107534/115869743-ffba5680-a446-11eb-85b0-4310c3d59194.png">

In the screenshot above the previews don't even match (and they probably won't no matter what we do).

Can we remove the preview based on the editor that uses the `LegacyWidget` block?

**Comment by noisysocks** [comment]
@critterverse: What do you think?

**Comment by critterverse** [comment]
It would be kind of a shame to lose to the preview for legacy widgets that have one, if only because they feel more Gutenberg-like than the legacy widgets without a preview. Checked a few different themes and it looks like the previews already match pretty closely in most instances — the thing that seems the most inconsistent between the sidebar and preview area is the styling for titles. Would it be possible to make the title match more closely?

(Twenty Twenty-One also adds bullet points into the sidebar preview in a lot of cases but that seems to only happen with that theme...)

If not, maybe we should consider defaulting to the behavior for legacy widgets with no preview.

**Comment by draganescu** [comment]
Yea, considering some widgets have immense setup forms and tiny previews, ditching the preview would make the sidebar unusable. I will close this idea, that while it makes "sense" it would make things more rational but much harder to use.

My proposal, let's not change anything. \o/
