### ISSUE TITLE
Support extending all widget  editing forms (like Jetpack visibility settings)

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#31181]
## Description
This potentially affects  other widgets that use the action controls of their form for supplementary  features. We strip that when getting the widget form and hence lose them. In this case, Jetpack has an option called "Enable widget visibility controls to display widgets only on particular posts or pages", available in Jetpack > Settings > Writing > Widgets.

## Step-by-step reproduction instructions
0. Install Gutenberg trunk and Jetpack
1. Configure Jetpack in Jetpack > Settings > Writing > Widgets. to have  "Enable widget visibility controls to display widgets only on particular posts or pages" set to on.
2. Go to Appearance > Widgets
3. Add any widget provided by Jetpack
4. Save
5. Go to the classic Appearance > Widgets editor by editing the URL to: [yoursite]/wp-admin/widgets.php
6. Notice the added widget has a visibility button
7. Go to Appearance > Widgets
8. Notice the widget does not have a visibility button

## Expected behaviour
The visibility button should appear.

## Actual behaviour
The visibility button should not appear.

## Screenshots or screen recording (optional)

<img width="1143" alt="visibility-not-showing" src="https://user-images.githubusercontent.com/107534/116051695-89edff00-a681-11eb-84c6-5d4123eb037e.png">

<img width="1116" alt="visibility-showing" src="https://user-images.githubusercontent.com/107534/116051702-8b1f2c00-a681-11eb-8213-d64e4f9a7989.png">

**Comment by noisysocks** [comment]
What filter/hook is used to add this button? It might be possible to invoke it in the REST API endpoint which renders the widget form control.

**Comment by noisysocks** [comment]
I'm having trouble testing this. When I install Jetpack locally I can't browse to Jetpack → Settings as there are errors. Perhaps Jetpack isn't working with 5.8-alpha.

If I can get the hook name that Jetpack is using then I can investigate adding support for it in the REST API.

**Comment by jeherve** [comment]
> When I install Jetpack locally I can't browse to Jetpack → Settings as there are errors. Perhaps Jetpack isn't working with 5.8-alpha.

Jetpack does work with WP 5.8-alpha & Gutenberg 10.7.1. What errors do you see when you navigate to Jetpack > Settings? Are you running the latest version of the plugin?

> If I can get the hook name that Jetpack is using then I can investigate adding support for it in the REST API.

The Jetpack feature mentioned in this issue is named Widget Visibility. It lives here:
https://github.com/Automattic/jetpack/blob/9f7ce71e3df8428484264aa49fc2ba7d8a11f13b/projects/plugins/jetpack/modules/widget-visibility/widget-conditions.php

As you'll see there, it hooks into the widget form using `in_widget_form`:
https://developer.wordpress.org/reference/hooks/in_widget_form/

Hopefully that clarifies things a bit!

**Comment by webzunft** [comment]
I may have the same issue with the [Fixed Widget plugin](https://wordpress.org/plugins/q2w3-fixed-widget/). It also uses `in_widget_form` to extend the widget form. The option is visible in the legacy view, but nowhere to be found for new blocks edit to a sidebar.

![Bildschirmfoto 2021-06-03 um 15 40 31](https://user-images.githubusercontent.com/2728720/120654489-098d9b80-c482-11eb-87fa-3549804f72c7.png)

I am happy to open a new ticket if this is a different issue, though.

**Comment by noisysocks** [comment]
> Jetpack does work with WP 5.8-alpha & Gutenberg 10.7.1. What errors do you see when you navigate to Jetpack > Settings? Are you running the latest version of the plugin?

It works for me now. Not sure what happened 🙂

> The Jetpack feature mentioned in this issue is named Widget Visibility. It lives here:
Automattic/jetpack@9f7ce71/projects/plugins/jetpack/modules/widget-visibility/widget-conditions.php

Thanks for pointing me here. It looks like Jetpack is only hooking into `in_widget_form` when `is_admin()` is true. `is_admin()` will return false in REST API requests like the one which the Legacy Widget block uses to obtain the form markup.

Sadly, this is a perennial issue. We've seen it in a few places e.g. in Core-47394 and Core-25104. There's not much we can do on the WordPress side of things as it would be a lie to fake `is_admin()` when the request is literally not for a WP Admin page.

I think in this case Jetpack will have to move the `add_action` out of that `if ( is_admin() )`. When I do that in my local copy of Jetpack it seems to work, albeit the styles and scripts are broken. Probably the CSS selectors are targeting the old page's markup.

<img width="1252" alt="Screen Shot 2021-06-10 at 14 12 41" src="https://user-images.githubusercontent.com/612155/121464376-1f0d4300-c9f7-11eb-9453-8f50ce178e98.png">

> I may have the same issue with the Fixed Widget plugin. It also uses in_widget_form to extend the widget form. The option is visible in the legacy view, but nowhere to be found for new blocks edit to a sidebar.

`in_widget_form` is only called inside the `<form>` of a Legacy Widget block. It will not be called inside a non-legacy block and it doesn't really make much sense to do so as non-legacy blocks are rendered using React and do not have a `<form>`.

I'm not sure of a good alternative in this case. Fixed Widget could add a new checkbox control to the block inspector which appears for every block, but then there's not currently a nice way to have that setting saved so that Fixed Widget can do something with it on the frontend. We may need to add a new API for that. Would you mind opening a new issue to discuss?

---

So, closing this issue as there's unfortunately no action we can take. Let me know if something is not clear or if there's something we can do to make this easier and I can re-open.

**Comment by jeherve** [comment]
> I think in this case Jetpack will have to move the add_action out of that if ( is_admin() ). When I do that in my local copy of Jetpack it seems to work, albeit the styles and scripts are broken. Probably the CSS selectors are targeting the old page's markup.

We'll take care of that. Thanks for taking a closer look!
