### ISSUE TITLE
theme customizer color control makes everything dissapear

### ISSUE THREAD

**Issue by TBAIKamine** [WordPress/gutenberg#31273]
adding a customizer control of invalid type returns to default type of text:
```
$wp_customizer->add_control('setting_id',array(
 'type' => 'abcdef'
))
```
the above code will work just fine, but the one below will crush down the customizer making everything dissapear:
```
$wp_customizer->add_control('setting_id',array(
 'type' => 'color'
))
```
now I know there is a workaround and a color type can be added differently using custom controls. but that's not the point
also it's sad that such simple control can't be simply added the usual way.
especially that the [official handbook ](https://developer.wordpress.org/themes/customize-api/customizer-objects/#controls)says you can use ANY html type attribute for inputs.
which is WRONG.

**Comment by aristath** [comment]
Hello @TBAIKamine,
I don't think this is the right place for this question... This is a repository for the WordPress editor, and has nothing to do with the customizer.
I would advise you to ask this question in https://wordpress.org/support/ instead.

To answer your question though, if you want a color control, WordPress already includes one (see https://developer.wordpress.org/themes/customize-api/customizer-objects/#core-custom-controls).
I suspect that by defining `'type' => 'color'`, WP tries to use the custom control and can't because it's not what it expects to see (though I'd have to check the code to be sure). So if you absolutely need to use an HTML color input instead of WP's default color control, you could try using an input and define the `input_attrs` for it. I haven't tested it, but there's a chance it might get you the result you need.
