### ISSUE TITLE
Patterns: Create a pattern in a similar way to how we create a Reusable block.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#31298]
## What problem does this address?

At current there is no user interface to create a pattern. Let's change that.

## What is your proposed solution?

Similar to how we add blocks to become a Reusable block it would be helpful to add blocks to become Pattern blocks.

![Patterns-Add-to-Pattern-blocks](https://user-images.githubusercontent.com/5323259/116463835-7a320e80-a86b-11eb-9977-e26f3778cb81.jpg)

**Comment by mtias** [comment]
We used to allow this briefly and removed it because it's confusing. Even in that dialogue it's not clear to me when I should choose one option over the other. A project to allow user editable patterns could be worthwhile but it needs a much broader scope and proposal, as it'd be a subtype of `wp_block`.

**Comment by paaljoachim** [comment]
I am wondering if we should do something like this:

**Add to Reusable blocks**
Add a global connected block

**Add to Pattern blocks**
Add an independent pattern block.

As it gives a short explanation of what each is. It would use the current method, and it can be an easy way to choose to use a global connected block or an independent block. It would give a quick access to creating both types of blocks directly in Gutenberg.

**Comment by paaljoachim** [comment]
@mtias 

I am thinking something similar to this:
![Add-to-Reusable-Pattern-blocks](https://user-images.githubusercontent.com/5323259/116779779-aa023180-aa78-11eb-9ee7-8b00de91ddc1.jpg)

A one liner that Reusable blocks are still connected with the original block.
That Pattern blocks are disconnected from original block.

@kjellr @melchoyce 


Associated:
Patterns: Manage Patterns similar to Reusable blocks. 
https://github.com/WordPress/gutenberg/issues/31367

Reusable blocks: Convert a Reusable block to a pattern. 
https://github.com/WordPress/gutenberg/issues/31296

**Comment by mtias** [comment]
Could be, or perhaps we need to use a modal where we can offer more context on what each option allows. In any case it needs a more in depth look to all the implications.

**Comment by paaljoachim** [comment]
I reopened the issue as it would be helpful to save blocks to a Pattern block.

**Comment by JosVelasco** [comment]
Perhaps make the option only available from the FSE editor. Something like an advanced option.

**Comment by JosVelasco** [comment]
There is already a plugin that converts reusable blocks to patterns and it works good. Reusable Blocks Extended: https://wordpress.org/plugins/reusable-blocks-extended/

Since there is a concern about generating confusion in the posts editor we could polish this plugin. Instead of "convert to reusable block" we could add the option "save as pattern" making a copy of the reusable block and listing it in /wp-admin/edit.php?post_type=wp_block

There could be a filter at the top of the list, please see my attachment. 

![reusable-block-pattern](https://user-images.githubusercontent.com/13054571/120074971-013df680-c065-11eb-805c-5b78b2de1ad2.png)

**Comment by paaljoachim** [comment]
Hi @JosVelasco 

That is a very good idea!

Adding the option to the Reusable blocks manage screen as you are showing is one good way of handling it.
As it would keep it out of the Gutenberg layout area for now and instead we just give the option in the manage screen.

One thing that comes to mind. To create a pattern one would first need to save it as a Reusable block and then -> convert/save it as a pattern. I do look forward to having a method to click multiple blocks and then save these as a Reusable block or as a Pattern directly through the ellipsis /3 dot drop down.

**Comment by mtias** [comment]
Also related: #32682. There's a proposed flow there for creating patterns as part of a design library.

**Comment by ecations** [comment]
This would indeed be very helpful. The way we create reusable blocks is really easy and intuitive. But I only need to reuse the structures (and not the content) so I'm looking at block patterns. And it seems to be a lot more involved to create those compared to reusable blocks.

**Comment by mtias** [comment]
This is done now!

**Comment by ecations** [comment]
That's great news! Where can we find more info about this feature?

**Comment by paaljoachim** [comment]
Hi @ecations 

Here is a PR which shows how it will work:
https://github.com/WordPress/gutenberg/pull/51144
