### ISSUE TITLE
Gutenberg does not change "_edit_last" post meta

### ISSUE THREAD

**Issue by amir2mi** [WordPress/gutenberg#31501]
I discovered a bug while I was trying to show **a post, the last modification author name**.
Generally, WordPress uses `_edit_last` post meta to save the last modification author ID.

The problem is Gutenberg does not set or change this post meta and when a post is published by Gutenberg then modified WP functions like [`get_the_modified_author()`](https://developer.wordpress.org/reference/functions/get_the_modified_author/), [`the_modified_author()`](https://developer.wordpress.org/reference/functions/the_modified_author/), will return null.

Steps to reproduce:
1- Create a post with Gutenberg.
2- `the_modified_author()` will return null.
3- Switch to Classic editor and save again.
4- Now `the_modified_author()` gives the user name who saved with Classic editor.

If a post was not modified it must show the user name who published the post, so it should be set for the first time during the post saving process and this does no happen.

[It was also mentioned while I was searching through issues in 2018](https://github.com/WordPress/gutenberg/issues/12903#issuecomment-447891872)

**Comment by peterwilsoncc** [comment]
Hi @amir2mi and thank you for the report.

This ticket was [discussed in a triage session](https://wordpress.slack.com/archives/C02QB2JS7/p1627970053073400) a short time ago.

It was decided that this was better filed under the WordPress Core ticketing system as the bug is likely with either the API Gutenberg uses or elsewhere in Core. There is an existing ticket reporting the issue you can find at https://core.trac.wordpress.org/ticket/50255.

I'm going to close this ticket off now. It's a perfectly valid issue but administratively it's handled elsewhere.

Thanks.
