### ISSUE TITLE
Unexpected behavior: wp_enqueue_scripts is firing in the block editor if the Gutenberg plugin is active

### ISSUE THREAD

**Issue by CreativeDive** [WordPress/gutenberg#31536]
Hello together,

I ran into a strange issue with the Gutenberg plugin activated:

```
if ( ! function_exists( 'frontend_example_function' ) ) :

	function frontend_example_function()	{

		wp_enqueue_style( ... );
		wp_enqueue_script( ... );

		my_function_is_doing_frontend_things();
		
	}

endif;

add_action( 'wp_enqueue_scripts', 'frontend_example_function' );
```

You can see with the upper function, I enqueue frontend assets and do additional things in this action with an additional function like: `my_function_is_doing_frontend_things();`

The "`wp_enqueue_scripts`" action is a frontend action only.

But I have detected, that my function `my_function_is_doing_frontend_things();` is also firing if I load the backend block editor.

I have searched for the reason for this unexpected behavior and I just couldn't figure out why this was happening.

Until I have deactivated the "Gutenberg" plugin.

After deactivating the "Gutenberg" plugin everything works fine as expected. My frontend function `my_function_is_doing_frontend_things();` included in the "`wp_enqueue_scripts`" action is no longer executed if I load the backend block editor.

I suspect this is a bug and something is not working properly. Can you confirm and reproduce this issue?

**Comment by CreativeDive** [comment]
Tested with WP 5.7.1 and Gutenberg plugin 10.5.4

**Comment by vdwijngaert** [comment]
Did this happen before the 10.5 update? 

Would you mind doing a 

```php
debug_print_backtrace();
die();
```
In your function to get a backtrace?

**Comment by CreativeDive** [comment]
@vdwijngaert I've downloaded the Gutenberg 10.4.1 Release and it works as expected. "`wp_enqueue_scripts`" is not firing in the block editor.

The backtrace is outputting nothing in the backend block editor, because it's included in the "`wp_enqueue_scripts`" action. A frontend action can't output something in the backend, right?

But why my included function fires in the block editor if the Gutenberg plugin is activated?

**Comment by CreativeDive** [comment]
@vdwijngaert an easy use case for testing, create a function to create a file, like:

```
function my_function() {
file_put_contents( $file_path, $file_data );
}
```

Then call this function inside the "wp_enqueue_scripts" action. Go to the backend and open the block editor. You can see, this file is created if you visit the block editor. But that shouldn't happen in this case.

**Comment by CreativeDive** [comment]
@vdwijngaert tested, since the 10.5.0. Release, this error occurs.

**Comment by vdwijngaert** [comment]
Hey @CreativeDive, no worries, I can reproduce it and I traced it back to where it happens. At first glance it seems expected behavior, but taking a look.

**Comment by vdwijngaert** [comment]
Okay, the changes that cause this behavior are done here: https://github.com/WordPress/gutenberg/pull/30438/commits/40b15b5dd41bec229dd5f57e15dd4280b0ecfece. @youknowriad, maybe you can take a look? Looks like you've worked on that part.

Here's what I got: 

The code I referred to is where logic was added for determining the template in use for the entity that's currently being edited. As far as I can tell, this currently happens by means of the `_wp-find-template` query var. The `gutenberg_override_query_template` function takes care of this by hooking into the `*_template` filter, and returns the template that's in use well before the `wp_enqueue_scripts` is reached. 

Only, it looks like in some cases we never get to the point where the "No matching template found" error message should be returned. The check for the query var only happens when the index template is reached at the end, so we never reach that point on pages with a non-fse page template like `front-page` in my case.

**Comment by CreativeDive** [comment]
@vdwijngaert Thank you for quickly investigating this issue. Very nice response time :-)

**Comment by CreativeDive** [comment]
@youknowriad I think a Must Have Fix for WordPress 5.8

**Comment by jorgefilipecosta** [comment]
Hi @CreativeDive, @vdwijngaert,
I tried to replicate this issue and did not manage to replicate it.

I used the following test code:
```
function frontend_example_function() {
	file_put_contents( 'debug.txt', 'testdata' );
}

add_action( 'wp_enqueue_scripts', 'frontend_example_function' );
```

When loading the post editor and the site editor nothing was written to the file. When opening the frontend the file was changed as expected.

Are you still able to replicate this issue in the Gutenberg trunk?

**Comment by CreativeDive** [comment]
@jorgefilipecosta I don't know why you can't replicate this issue. This is happening since Gutenberg 10.5. and with the latest plugin version too. @vdwijngaert was able to replicate this issue. I think he can advise you, because he found the cause of it
 :-)

**Comment by CreativeDive** [comment]
@jorgefilipecosta , @vdwijngaert I can confirm this issue is still there with Gutenberg 10.6.

**Comment by kathrynwp** [comment]
@CreativeDive @vdwijngaert As this issue has been open for a while, I'm circling back to see if it's still occurring for either of you. If so, please indicate your WordPress version, and whether the issue happens with or without the latest version of Gutenberg (14.0.2), with no other plugins active. Thank you!

**Comment by CreativeDive** [comment]
@kathrynwp I don't think this auto-reply goes down well with the issue creators. Many users have bothered to report bugs, often checked on the surface or not even verified after months/years. And now many of these issues get a response like this. I think if anyone here should be testing these bugs, it's WordPress developers.

**Comment by kathrynwp** [comment]
@CreativeDive  Thanks for your feedback and your patience, as it’s obvious that you’ve been waiting a long time for a response. For context, this isn’t an auto-response. It’s an effort to ensure that the currently open issues are still relevant to the project, so that those remain open have a greater chance of being addressed. When looking through the issue, it appeared that you were keen to help test and report back whether the issue was still valid so, to me, it made sense to check with you once more! This is a common practice, especially when an issue couldn’t be replicated previously. Thanks for being so helpful up to this point. It really helps the project to have folks participate in this way when they can, especially for intermittent or hard-to-replicate issues.

@jorgefilipecosta @vdwijngaert mind testing this once more to see if you are able to replicate with 14.0.2?

**Comment by ndiego** [comment]
This issue was reviewed in today's Editor Bug Scrub. I was able to replicate the situation using the code provided [here](https://github.com/WordPress/gutenberg/issues/31536#issuecomment-839173810). However, per the [discussion](https://wordpress.slack.com/archives/C02QB2JS7/p1666706971801329) during the bug scrub, the fact that admin requests can trigger  `wp_enqueue_scripts` shouldn’t inherently be an issue. Are you able to provide some additional details about what issues this implementation is causing?

**Comment by CreativeDive** [comment]
From my understanding, a frontend `wp_enqueue_scripts` action should not perform any operations in the backend context.

Frontend: `wp_enqueue_scripts`
Backend: `admin_enqueue_scripts`

In my opinion it's a performance issue. In my case, I performed file operations that affect the frontend only. Therefore, it is not desirable that this is also done in the backend.

**Comment by ndiego** [comment]
> In my opinion it's a performance issue. In my case, I performed file operations that affect the frontend only. Therefore, it is not desirable that this is also done in the backend.

Thanks for the follow-up @CreativeDive. @Mamaduka any thoughts on this?

**Comment by Mamaduka** [comment]
Thanks for providing more details, @CreativeDive.

> From my understanding, a frontend wp_enqueue_scripts action should not perform any operations in the backend context.

The action itself isn't called in WP admin, but when the block theme is active, the editor makes a GET request to the site to get the correct template for the post or page. It is the cause of the `wp_enqueue_scripts` action call.

The remote requests from admin pages triggering the actions on the front shouldn't be an issue, IMO.

You can use the following snipped to avoid performing file operations for the requests initiated by the editor.

```php
// Skip the requests from the block editor.
if ( isset( $_GET['_wp-find-template'] ) ) {
  return;
}
```

**Comment by CreativeDive** [comment]
@Mamaduka thanks for providing this solution. I will close this issue.
