### ISSUE TITLE
Aligning image blocks make resizing impossible

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#31657]
**Steps to reproduce**

 - Insert an image block and pick an image
 - Notice that the resize handles are visible (you can resize the image)
 - Center or left align it.
 - The resize handles disappear and you can't get them back even if you restore the "no alignments" option.

**Comment by vdwijngaert** [comment]
Hmm. Had to switch to tt1 (non-blocks) to get the usual alignment options (other than wide and full), but looks like it still works over here. Is this in trunk? 

In wide & full alignment, it looks like resizing gets [disabled by design](https://github.com/WordPress/gutenberg/blob/ee8b5a39b0189af153d205c3b493fa4e1e862ada/packages/block-library/src/image/image.js#L132-L139), but that's probably unrelated.

**Comment by youknowriad** [comment]
> Hmm. Had to switch to tt1 (non-blocks) to get the usual alignment options (other than wide and full), but looks like it still works over here. Is this in trunk?

This is related to #30568 (not necessarily a bug)

**Comment by ellatrix** [comment]
Is this for a specific theme? I can't reproduce.

<img width="834" alt="Screenshot 2021-05-19 at 17 58 51" src="https://user-images.githubusercontent.com/4710635/118835671-e08ad980-b8cb-11eb-977d-e82c2e7c7658.png">

**Comment by youknowriad** [comment]
I can't reproduce anymore 🤷
