### ISSUE TITLE
Template Editing mode hindered by plugin's meta boxes 

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/gutenberg#31789]
## Description
When a plugin such as Yoast SEO is activated and you enter Template Editing mode the 
meta boxes that normally appear below the content get pride of place and scroll into view. 

## Step-by-step reproduction instructions
1. Activate Yoast SEO
2. Edit a page
3. From the Settings pane Template panel choose Edit.
4. The Template editor opens 
5. But the meta boxes loom into view.

## Expected behaviour
I think the meta boxes should be hidden when editing the template.

## Actual behaviour
The meta boxes are a bit in your face.
They can be minimised, but it has to be done each time.

## Screenshots or screen recording (optional)
![image](https://user-images.githubusercontent.com/2474435/118121720-cb084200-b3e9-11eb-9988-2c900504897c.png)

## WordPress information
- WordPress version:  5.7.1
- Gutenberg version: 10.6.0
- Are all plugins except Gutenberg deactivated? No. Needed Yoast SEO and another plugin to display the meta boxes.
- Are you using a default theme (e.g. Twenty Twenty-One)? No. I'm using `thisis`.

## Device information
- Device:  Desktop
- Operating system: Windows 
- Browser: Chrome

**Comment by carlomanf** [comment]
I can't reproduce this with the core meta box for custom fields. It might be a problem with Yoast SEO?

**Comment by carolinan** [comment]
I tested with Yoast SEO deactivated and by activating a theme that has meta boxes ([Aaron](https://wordpress.org/themes/aaron/)).

With Gutenberg trunk or 10.6.0 active, I am seeing the black background color around the meta box both in the post editor and template editing editing mode.
I am also seeing the scroll in the template editing mode, and there is not much space to edit content.

![metabox covers template editing mode](https://user-images.githubusercontent.com/7422055/118256886-44696880-b4ae-11eb-9032-9975d4d7129f.png)

**Comment by carlomanf** [comment]
> I can't reproduce this with the core meta box for custom fields. It might be a problem with Yoast SEO?

I was still on version 10.5.4 when I couldn't reproduce it before. After updating to version 10.6, I'm now able to reproduce it with the core meta box for custom fields. Therefore, it's definitely a new regression introduced by version 10.6.

Can I also just say that the new black padding is extremely ugly, and shrinking the physical size of the canvas seems like a very strange way to communicate the increased editing scope in template mode. I think there needs to be a rethink of how to remind the user they are in template mode. Perhaps an informational strap at the top, similar to the ones for autosaves and updating failed, rather than extra padding?

**Comment by carlomanf** [comment]
> Perhaps an informational strap at the top, similar to the ones for autosaves and updating failed, rather than extra padding?

This is a mock-up of what I'm thinking. It would obey the user's admin color scheme and eliminate the need for the extra black padding.

![Screen Shot 2021-05-15 at 7 45 22 pm](https://user-images.githubusercontent.com/6543827/118356056-c9d84000-b5b6-11eb-948d-9092be657fb6.png)

**Comment by youknowriad** [comment]
Let's try to remove the meta boxes from the template mode.

**Comment by carlomanf** [comment]
I'd rather they not be removed altogether, as they can still be useful in template mode. This was not a problem in version 10.5, where they were just collapsed as normal.

**Comment by youknowriad** [comment]
I think it doesn't make sense to keep them as most of them contain "post related things" and the "sidebar ones" are removed, so it makes sense to be consistent and remove the "content ones" as well.

**Comment by carlomanf** [comment]
I agree to err on the side of consistency, although I'm not convinced the sidebar ones should be removed either, because the new sidebar that replaces them is practically empty. If there were some template-related tools to take their place, I think there'd be a stronger case for removing them. It will also be interesting to see whether any/many users report that they prefer the template mode to the standard mode for editing the post itself.
