### ISSUE TITLE
Navigation Editor: Handling saving for multiple menus

### ISSUE THREAD

**Issue by Mamaduka** [WordPress/gutenberg#31813]
## What problem does this address?
Step 3 from #30322.

Currently, you can save one menu at a time.

## What is your proposed solution?
A. Allow users to save multiple menus, like multi-entity saving of Reusable Blocks in post editor or Template Parts in the site editor.
B. Add warning dialog with confirmation when switching menus or creating a new one, and there are unsaved changes.

**Comment by getdave** [comment]
Noting here for the purpose of prioritisation that multi-saving of menus is not currently supported by the existing Navigation screen either. You must `Save` before you switch to editing another menu else your changes are lost.

**Comment by spacedmonkey** [comment]
It is worth nothing, that there are menu and menu items, which are stored differently here. Do you mean saving multiple menu items at the same time. It is worth noting that menu items [already](https://github.com/WordPress/gutenberg/blob/trunk/lib/class-wp-rest-menu-items-controller.php#L47) supports batched rest api requests. Menus do not currently support saving multiple menus in batch requests, but we could enable this functionality.

**Comment by Thelmachido** [comment]
Closing this issue due to the Navigation Screen project being moved to [an inactive status on the feature projects page](https://href.li/?https://make.wordpress.org/core/features/) in coordination with the project leads.

 If this work is picked back up, issues can be revisited and reopened as needed. Thanks for testing this early feature and giving feedback so the wider WordPress project could benefit from the lessons learned!
