### ISSUE TITLE
Make tab and shift-tab change ordered/unordered list level

### ISSUE THREAD

**Issue by andfinally** [WordPress/gutenberg#31885]
## What problem does this address?

Whenever I'm creating a bulleted list, I instinctively tap the tab key or shift/tab combination to change the indent level of the list item, and I'm always frustrated when I rediscover for the umpteenth time that Gutenberg doesn't support it. It's an almost universal convention, used in MS Word, VSCode, [tinyMCE](https://codepen.io/tinymce/live/QWNpjbg) and many other editors. The current shortcuts – space and backspace – feel idiosyncratic.

The way they work is also not very convenient, because your cursor needs to be positioned at the start of the list item, otherwise they do what space and backspace normally do. You can't type or paste the list item content in and then change the indent – you have to go searching for the start of the line first.

## What is your proposed solution?

When a bullet list or numbered list is selected in the editor, or the cursor is anywhere in a list item, make tab increase the list item indent level and shift-tab decrease it.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting. The tab and shift/tab combination because TAB is used as a keyboard shortcut to navigate to other parts of the block editor; there's discussion about this at https://github.com/WordPress/gutenberg/issues/8356 and https://github.com/WordPress/gutenberg/issues/7051

Secondly, you can go to the beginning of a line by using the keyboard shortcut Ctrl and the left arrow key.

**Comment by andfinally** [comment]
Hm, I see! Thanks @skorasaurus, sorry about the duplicate.
