### ISSUE TITLE
Navigation Responsive 'frontend.js' missing for view

### ISSUE THREAD

**Issue by pbking** [WordPress/gutenberg#31909]
## Description
Attempting to leverage [this recent change](https://github.com/WordPress/gutenberg/pull/30047) I was unable to open the responsive menu due to a javascript error (missing resource).

## Step-by-step reproduction instructions
Add a menu block to a page and populate it with at least one menu item.
Select 'Enable Responsive Menu' from the Navigation Block Editor Panel
Save the Page and load it in the view.
Reduce the screen width until the mobile navigation menu is shown.
Click the mobile navigation menu.
  Note that it does not open.
  Note the error presented in the console regarding the missing frontend.js
```
GET http://localhost:4759/wp-content/plugins/gutenberg/build/block-library/blocks/navigation/frontend.js?ver=5.7.2 net::ERR_ABORTED 404 (Not Found)
```
Note that the frontend.js file present in `/packages/block-library/src/navigation` is absent from the build location.

I built (and rebuilt, and cleaned and rebuilt) Gutenberg many times.  Manually copying the file into the expected location produced errors (import not being something that can be leveraged in that situation it seems).

## Expected behaviour
The frontend.js file should be transpiled and available.

## WordPress information
- WordPress version: latest (wp-env)
- Gutenberg version: trunk
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No

**Comment by pbking** [comment]
+ @vcanales as the author

**Comment by vcanales** [comment]
Hi @pbking ! Thanks for reporting this — I've created https://github.com/WordPress/gutenberg/pull/31917 in order to address it.  I'd appreciate it if you could test again using that branch.

The issue is caused by outputting the wrong destination for the Navigation block's `frontend.js` file when creating the production build — this issue does not exist when running a development build, which might help understand why we didn't catch it before.
