### ISSUE TITLE
Docs: Indicate that the third parameter of @wordpress/core-data userCan is needed for some actions

### ISSUE THREAD

**Issue by juanRabaa** [WordPress/gutenberg#31918]
When using the function `userCan` from **@wordpress/core-data**, it will always return `false` for any object type (`resourse`) when passing the actions `delete` or `update`, when not passing the third parameter (`id`).

I wanted to check if a user (admin) had the ability to delete any `post` doing `wp.data.select( 'core' ).canUser( 'delete', 'posts' );`. I wasted quite some time trying to figure out why it would always return `false`.  This is because `canUser` needs the third parameter (`id`) to be passed for these cases.

We should indicate this in the documentation.

**Comment by talldan** [comment]
@juanRabaa This sounds like a bug in the REST API.

The `canUser` function works by making an `OPTIONS` request to the endpoint in question and checking the `allow` header in the response. I can see that even though I'm an admin, the allow header only has `GET` and `POST`.

When an id is specified the function instead calls `GET` due to a previous REST API bug. The `GET` request seems to return the right thing in the allow header, so that's why it's working when you add an id.

I've created a ticket for the upstream issue and will close this - https://core.trac.wordpress.org/ticket/53223.

**Comment by TimothyBJacobs** [comment]
@juanRabaa There is no blanket way to do check to see if a user can delete any post. Whenever the actual delete happens, WordPress checks that they can delete that specific post. If you want to check that they have a specific capability, you could do that thru the `wp/v2/users/me` endpoint, but again keep in mind that just because they have the `delete_posts` capability for instance, it won't be accurate.

**Comment by juanRabaa** [comment]
> @juanRabaa This sounds like a bug in the REST API.
> 
> The `canUser` function works by making an `OPTIONS` request to the endpoint in question and checking the `allow` header in the response. I can see that even though I'm an admin, the allow header only has `GET` and `POST`.
> 
> When an id is specified the function instead calls `GET` due to a previous REST API bug. The `GET` request seems to return the right thing in the allow header, so that's why it's working when you add an id.
> 
> I've created a ticket for the upstream issue and will close this - https://core.trac.wordpress.org/ticket/53223.


Im not sure if it is a bug though. I think it needs an ID because a user can have the capability to delete some posts, but not others. And as @TimothyBJacobs stated, checking against a capability isn't always accurate.

This is why I marked this as a documentation suggestion. If the ID is needed, then we should marked it as required. Also, when doing a check for `userCan("delete","posts")`, a warning should be thrown to let the developer know that an ID is needed.

**Comment by TimothyBJacobs** [comment]
So it's a bit more complex than that. The `userCan` function is just an abstraction over the `Allow` header. So while the third parameter may be required for some actions like `DELETE`, it isn't for others. But that info itself is contextual on the resource. For instance, you could have a collection endpoint that has a `DELETE` method, like the Application Passwords collection.
