### ISSUE TITLE
Legacy widgets are not visible on the widget screen until clicked

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#31935]
## Description

If I place widgets and then activate Gutenberg, the legacy widgets are not visible in the widget areas until I click on the widget
(I don't mean clicking on the widget area to expand a closed widget area, but clicking inside it).

## Step-by-step reproduction instructions

1. Activate a theme with widget areas.
2. Place widgets.
3. Activate Gutenberg.
4. Go to the widget screen, see that the widget areas look empty.

## Expected behaviour

I expect the widgets to be visible.

## Actual behaviour

The legacy widget is not visible in the widget area until I click on the widget.

## Screenshots or screen recording (optional)

![legacy-widgets](https://user-images.githubusercontent.com/7422055/118645222-f1a9ec80-b7de-11eb-82a0-0234e82f1662.gif)

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: Tested with current trunk and 10.6.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Tested with both Twenty Twenty and Aaron.

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome Version 90.0.4430.212

**Comment by annezazu** [comment]
I also ran into this along with very strange spacing issues likely as a result of this bug. If that's a separate issue, happy to open a new one. I'm using WordPress 5.7.2, Gutenberg 10.6.1, and the Twenty Twenty theme:

https://user-images.githubusercontent.com/26996883/118689834-a682e000-b7c4-11eb-9bb6-5afd7940ee9b.mov

Will open a bug around the coloring and text color of the "Add a block" since that seems to be due to some CSS bleeding.

**Comment by tellthemachines** [comment]
I'm running into this issue only in the second of two available widget areas. Using TwentyTwenty theme, three legacy widgets added into each area, the first area displays fine in the new editor, but in the second none of the widgets are visible until focused.

**Comment by helen** [comment]
Adding a data point - I experienced this yesterday in a newly activated Twenty Sixteen after using a block-based theme, with what I believe were just the default widgets in the inactive area and no other widgets/blocks shown (search, recent posts, recent comments, archives, categories, meta).

GB: running from Git trunk, rev b6e3e1c8c43f8f36e80b7352054cb9c46a136112
Core: running from trunk/src, SVN r50984 - https://github.com/WordPress/wordpress-develop/commit/187c7fc7252a53b5f355a31a8cb3deadf985f4c7
Screencast: https://youtu.be/JzBMyy1MCKo

**Comment by talldan** [comment]
I've looked into this and the cause is fairly straightforward. There's some logic for dynamically updating the height of the widget preview iframe when its content loads, but in collapsed widget areas that height is always calculated as `0` (because the widget area is collapsed and all the content in the widget area has no height).

It doesn't recalculate when the widget area is expanded, so the block looks empty.

Coming up with a fix shouldn't be too difficult. Just a matter of looking for the right solution.

**Comment by a4jp-com** [comment]
I've got this problem in WordPress 6.6.1.

**Comment by carolinan** [comment]
@a4jp-com I am not able to reproduce it, can you add any more information?

I did the following:
Activated Twenty Twenty-One
Added the "Meta" legacy widget to the footer widget area. Saved.
Activated Gutenberg (trunk)
Returned to the widget screen
-All widgets are visible, both blocks and legacy.
