### ISSUE TITLE
Escape key in customize widgets editor exits back to main customizer menu

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#31972]
## Description
As the title says, escape key in customize widgets editor exits back to main customizer menu, which overrides some other uses for escape:
- Navigation/Select mode
- Using escape to close dropdowns (block settings, editor more menu)

## Step-by-step reproduction instructions
1. Open the customize widgets editor
2. Select a block

## Expected behaviour
Navigation mode is entered

## Actual behaviour
The editor is closed and the page navigates back to the main customizer menu

**Comment by critterverse** [comment]
We also have #31730 but can close that in favor of removing the "back" functionality altogether, let me know!

(We should take a look at the back functionality for `Enter` as well — this currently takes you back a step when you first open the Customizer editor before selecting anything, otherwise seems to be disabled)

**Comment by talldan** [comment]
Cool, I missed that one. I'll close this in favour of #31730 and mention about popovers there.
