### ISSUE TITLE
Investigate unstable navigation test.

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#32033]
This test has been skipped in #32031 because it's too unstable and has been failing too often in trunk.

cc @Mamaduka

**Comment by Mamaduka** [comment]
Thanks, @youknowriad

I will have a look and try to fix it.

**Comment by Mamaduka** [comment]
@getdave I was wondering maybe I should update `assertIsDirty` and check against `__experimentalGetDirtyEntityRecords` instead of dialog.

Not sure if this is the cause of the issue, but response mocking sometimes fails during page reload.

https://github.com/WordPress/gutenberg/blob/b65583def3168fb481b2a776f892f2a38b10a616/packages/e2e-tests/specs/experiments/navigation-editor.test.js#L536-L554

**Comment by Mamaduka** [comment]
It looks like this was caused by missing `await` for `assertIsDirty` async function 🤦

**Comment by youknowriad** [comment]
nice catch @Mamaduka what about the other skipped tests in the same file? Do we have a similar error there?

**Comment by Mamaduka** [comment]
I'm still trying to reproduce those locally.

**Comment by Mamaduka** [comment]
Reopening since tests still fail from time to time. I've created a new PR to explore more permanent solution #32122.

**Comment by Mamaduka** [comment]
I'm closing the issue since Navigation Editor is no longer in development.
