### ISSUE TITLE
Jetpack / Markdown text removed by Gutenberg

### ISSUE THREAD

**Issue by robsmithiii** [WordPress/gutenberg#3207]
## Issue Overview

If I add text when the Jetpack / Markdown integration is enabled on my site, after publishing the post, Gutenberg warns that the post has been externally modified. Any of the choices I make causes me to lose the original markdown text.
## Steps to Reproduce (for bugs)

1. Enable Jetpack plugin and enable markdown within settings.
2. Create a post containing Markdown, at which point Jetpack will render the text correctly.
3. Attempt to edit the post again, and a warning dialog concerning external modifications appears.
4. Original markdown data is lost.

## Expected Behavior

I would like to see the original markdown retain an re-rendered each time (the current behavior in the class editor).

## Current Behavior

Markdown data is lost.

## Possible Solution

Perhaps the ability to add a Markdown blocktype that wouldn't require the Jetpack plugin to be enabled...

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by mkaz** [comment]
Related to #2817

**Comment by mkaz** [comment]
@robsmithiii Today's release of Gutenberg (version 1.6) should include the fix for your bug, or at least solve the issue of content being removed. 

The fix does not implement a markdown content block as suggested, the goal of Gutenberg is as a visual editor, so not sure if a markdown block makes sense, maybe as a plugin. 

Gutenberg does support converting markdown to blocks if you paste it, which is great if you compose posts in markdown and copy and paste them over.
