### ISSUE TITLE
Gallery block: automatically migrate v1 blocks to v2 on edit

### ISSUE THREAD

**Issue by glendaviesnz** [WordPress/gutenberg#32075]
At some point in the future we will want to automatically migrate the v1 block content to v2 format on edit and remove the v1 edit and save code.

Some work was done previously on setting up the deprecations for this, but the code was removed when the decision was made to continue supporting the v1 format. This removed code can be found at https://gist.github.com/glendaviesnz/b295c625e4dfe59c678ae396f5c361d5 or at the original commit https://github.com/WordPress/gutenberg/blob/0ff156a277ae6cb7589ca016addb80f8a6a628de/packages/block-library/src/gallery/deprecated.js

Also, the changes needed to the underlying fixtures, etc. can be found at https://github.com/WordPress/gutenberg/pull/28481. This will likely be outdated by the time it is reimplemented, but may provide information on what is required in order to update fixtures to new version of the block.

**Comment by celloexpressions** [comment]
In using version numbers for galleries, please remember that the "classic" editor has its own gallery shortcode (pre-block) that also comes with a different set of markup. Themes and plugins need to handle all three versions of markup (although some v2 content will transform to v3 with migration proposed here). This issue is essentially about migrating from v2 to v3, while v1 retains the classic markup unless users manually "convert to blocks" with classic blocks in the editor.

It's still possible to add v1 galleries inside of classic blocks, and sites have years of older content in this format. Will the "convert to blocks" approach for v1 galleries still be manual? And will it convert directly to v3?

**Comment by glendaviesnz** [comment]
> Will the "convert to blocks" approach for v1 galleries still be manual? And will it convert directly to v3?

Yes, correct. classic gallery short codes will remain as they are unless a user decides to use the `Convert to blocks` option, at which point, with the auto migrations in place the gallery short codes will go directly from v1 -> v3:
![classic-convert](https://user-images.githubusercontent.com/3629020/138773904-5632a905-6b21-4807-8061-19871524c3cd.gif)
