### ISSUE TITLE
Improve sidebar settings after entering Template Editing Mode

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#32073]
## What problem does this address?

When one opens up the template editor from the post editor, the focus causes the sidebar settings on display to be a dead end.  This feedback comes from the [sixth round of testing from the FSE Outreach Program](https://make.wordpress.org/test/2021/05/12/fse-program-testing-call-6-stick-the-landing-pages/): 

>The “Template” tab in the sidebar is mostly useless. I’m sure there’s more we could do here to educate and relevant functionality we could expose.

<img width="393" alt="image-23" src="https://user-images.githubusercontent.com/26996883/119076518-f245ad00-b9af-11eb-91d4-6e680cf10c96.png">

## What is your proposed solution?

I imagine there are a few ways forward:

- Share a description in that sidebar setting
- Change the focus so it lands on the first block in the template
- Something I'm not thinking of 😅

**Comment by jameskoster** [comment]
Since we now display the template details in the top bar, I'm not sure we really need this tab at all?

<img width="421" alt="Screenshot 2021-06-01 at 15 32 21" src="https://user-images.githubusercontent.com/846565/120341219-9bfd3600-c2ee-11eb-8757-173a82418e97.png">

Displaying the name and description makes sense, but we should probably do it there rather than the sidebar. I opened https://github.com/WordPress/gutenberg/issues/32362 to explore this some more.

https://github.com/WordPress/gutenberg/issues/29147 is related, but we can probably put this in the top bar as well.

---

Another option would be to make the sidebar an educational area that explains in more detail what templates are, with links to documentation etc.

**Comment by annezazu** [comment]
Agreed on removing it if that's included in the template details. In that case, I imagine it would make more sense to have this open on the top most block (site title)? However, I do like the idea of links to documentation!

**Comment by annezazu** [comment]
More feedback from this experience of landing in template editing mode from @synora:

> What part of the template we’re editing is evident to us because we’re testing but what about the user? There’s no indication of where exactly they are. I was expecting some sort of highlighted area or even label to let me know where I was, but there was nothing.

**Comment by jameskoster** [comment]
> There’s no indication of where exactly they are

In the Site Editor, template parts are highlighted in the top bar:

<img width="920" alt="Screenshot 2021-06-03 at 09 54 36" src="https://user-images.githubusercontent.com/846565/120617109-b8fe4a00-c451-11eb-9dba-9500c6a0fa13.png">

We should probably do something similar in the template editor once template parts are a feature there. The sidebar isn't the best place for this information since it is often collapsed.

**Comment by youknowriad** [comment]
With all the iterations on the Document bar the sidebar of the template editor, I think this issue is not relevant anymore.
