### ISSUE TITLE
10.6.2 causes severe issue with inboundnow Emails

### ISSUE THREAD

**Issue by netflowauditor** [WordPress/gutenberg#32130]
Gutenberg update to 10.6.2 breaks the inboundnow Emails. After updating all emails preview and are sent with the websiute framework instead of the default email template. After deactivating Gutenberg it all works again.

**Comment by talldan** [comment]
@netflowauditor Thanks for reaching out. This isn't really enough information for any developer to be able to follow-up on your report (which is why we include a template for you to fill out).

Please could you fill out all the required information.

A few additional questions:
- What is inboundnow? Is it a plugin? I don't see it in the WordPress plugin directory. If this is a paid plugin, it'll be very difficult for developers here to offer support, I'd suggest reaching out to the plugin developers (they may also be able to reach out to Gutenberg developers with more specific information if this is a regression in the Gutenberg codebase).
- You mention "emails preview and are sent with the websiute framework", what's the website framework?

**Comment by netflowauditor** [comment]
inboundnow is a gpl contact management system for WordPress available on Github.

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/62791190/119408492-78366080-bcee-11eb-8106-dc928a9e1422.png">

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/62791190/119408508-82f0f580-bcee-11eb-8dd2-6ee2b5defbab.png">

We upgraded to 10.6.2 on 19 May 2021. Prior to the Gutenberg upgrade our email automation app was working harmoniously with Gutenberg.

**Comment by talldan** [comment]
> inboundnow is a gpl contact management system for WordPress available on Github.

Can provide some links to the plugin?

> We upgraded to 10.6.2 on 19 May 2021. Prior to the Gutenberg upgrade our email automation app was working harmoniously with Gutenberg.

Do you recall which version you were using previously?

Please also fill out the bug report template as requested, particularly the steps to reproduce. At the moment there's very little information for any Gutenberg contributor to act on.

It's also definitely worth reaching out to the inboundnow developers. It may have been an issue triggered by a version bump in Gutenberg, but it doesn't always mean the problem was caused by this plugin. It could be that inboundnow are using an API incorrectly, or relying on an experimental API that has been changed. Inboundnow developers may also be able to assist with debugging.

**Comment by talldan** [comment]
Looks like this was solved by inboundnow (https://github.com/inboundnow/inbound-pro/issues/205).
