### ISSUE TITLE
Paragraph Block: focus on inline text color panel stays too long

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#32246]
## Description

The inline text color panel to customize text colors pops back up after setting an inline color when you select an additional item of text to edit. 

## Step-by-step reproduction instructions

1. Add a paragraph block.
2. Add some text. 
3. Set a custom in line color for one of the words and, after doing so, click to highlight another word. Notice the inline color panel pops up. 

## Expected behaviour

The inline color panel would not reappear.

## Actual behaviour

The inline color panel remains. 

## Screenshots or screen recording (optional)

Here's a roughly 1 min long video of me going back and forth showing the behavior in various situations. A few times it doesn't occur and I'm not quite sure why (is it related to adding in line color to an already bolded text item?): 

https://user-images.githubusercontent.com/26996883/119710357-7e762b00-be1b-11eb-81d6-9cb20dbbed4d.mov

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.7.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

## Device information
- Device: Desktop
- Operating system: MacOS Big Sur 11.4
- Browser: Chrome Version 89.0.4389.128

**Comment by stacimc** [comment]
I can confirm this happens when selecting an inline text color for text that already has some other inline style — bold in your example, but it also happens if the text is in italics/superscript/etc.

I noticed that when other inline styles are _not_ present, the color panel does not immediately close once a color is selected. It only closes when the user clicks outside/blurs the element somehow. This fires the `onClose` handler, which [toggles off the `isAddingColor` state](https://github.com/WordPress/gutenberg/blob/8fbc4d617f6d85da7f5496e8d49e869c7ecca011/packages/format-library/src/text-color/index.js#L84) used to display the panel.

It looks like what’s happening is that in the case when other inline styles are present, the color panel erroneously closes as soon as a color is selected, without actually firing the `onClose` handler — meaning the `isAddingColor` state isn’t turned off, so if you click anywhere inside the paragraph the panel still thinks it ought to be displayed.

Unfortunately I haven't been able to figure out why the panel is closing when other inline styles are present.

**Comment by annezazu** [comment]
I can no longer replicate this with 5.9 and GB 12.5.3 :D Going to close this out as a result.
