### ISSUE TITLE
Feature request: Ability to select template editing as the default editor mode

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#32385]
## What problem does this address?

I would like to be able to choose if I want content editing or template editing to be the default when I open the block editor.

**Comment by aristath** [comment]
Could you please elaborate? 
Why should this option be available?
The block editor is for editing _content_. The template editor is for editing _templates_. So the workflow is to write the content, and then if needed, edit the template. Sure, the content can be edited in the template-editor and you can even build an entire site using blank pages and custom templates, but the fact that it's possible doesn't mean it's recommended...
Making the template editor the default would mean that instead of creating a _page_, you'd actually be creating a _template_. But a template can't be displayed on its own,it needs to be attached to a post/page.
I'm a bit confused by the scenario here...

**Comment by carolinan** [comment]
Just like some people will prefer dark mode, some prefer full screen or to work with keyboard shortcuts -some users may prefer to always see the full web page.

It is not only about creating new items, but also about existing content. 
For new items, it would create a post or page that uses the default template. It would not create a new template until the "new" link was selected in the template section.
