### ISSUE TITLE
Toolbar overflows viewport on small right aligned images

### ISSUE THREAD

**Issue by Azragh** [WordPress/gutenberg#32402]
## Description
Toolbar overflows viewport on small right aligned images. Not much more to say here.

## Step-by-step reproduction instructions
Create an image block, choose alignright and resize it to 150px or so. In Twenty Twenty-One you maybe have to resize the browser a little bit to see this behaviour.

## Screenshots
![image](https://user-images.githubusercontent.com/15014142/120494753-5f980b80-c3bc-11eb-83f0-36d4d4bf4960.png)

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.7.1

Only Gutenberg active with Twenty Twenty-One

## Device information
- Device: Desktop
- Operating system: Windows
- Browser: Chrome

**Comment by inaikem** [comment]
Replicated while scrubbing a related bug elsewhere. Please note that the issue is present in many, if not all instances where the toolbar appears over an element towards the right of the main editor window.

This example shows a toolbar appearing over an image block in the right-most column of a column block:

![Tooblar hidden](https://user-images.githubusercontent.com/66711744/126127743-cf7d5890-ff6e-4a95-ad9b-7f70887c3544.png)

**Comment by talldan** [comment]
This was flagged on the [forums](https://wordpress.org/support/topic/is-this-expected-behaviour-for-the-popover-in-gutenberg/), and when testing it definitely seems to happen, especially in a right-hand column:
<img width="277" alt="Screenshot 2021-07-21 at 5 41 48 pm" src="https://user-images.githubusercontent.com/677833/126468306-914d1ecd-e45b-4f11-99a8-da578e0b79a1.png">

Feels like a possible regression and a definite usability issue. Raising the priority.

**Comment by antonyjsmith** [comment]
Thanks @talldan. To clarify, this has been around for some time, it's not emerged with 5.8. I'd just wearily come to accept it, however it's getting increasingly worse as the popover continues to grow.

**Comment by youknowriad** [comment]
I do recall that we fixed this in the past with some popover shifting behavior, it might have regressed cc @ellatrix
