### ISSUE TITLE
Pasting into a List block creates another list

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#3241]
Pasting some list items into a list should gracefully integrate instead of creating a new block.

**Comment by iseulde** [comment]
This is an interesting problem. What we get back from the raw handler is a new list. Since it is not inline content, editable will split the block and insert the new block in between, which causes the multiple lists. How should this be solved? Maybe some extra logic in the block registration to merge them back, if we detect the pasting of a block type in the same block type?

**Comment by iseulde** [comment]
To me this seems like a problem that will resolve itself once we have nested blocks.

**Comment by iseulde** [comment]
The only thing I can think of right now is make an exception in the editable paste logic: if we're in a list editable and the pasted block is just a list, create a string and let TinyMCE handle paste further.

```js
if ( this.props.multiline === 'li' && content.length === 1 && content[ 0 ].name === 'core/list' ) {
	event.content = renderToString( content[ 0 ].attributes.values );
}
```

**Comment by jorgefilipecosta** [comment]
With the merge of https://github.com/WordPress/gutenberg/pull/3949, this issue should be fixed.
