### ISSUE TITLE
Extra scroll space at bottom of Customizer menu screen when “Show scroll bars: Always” is turned on (MacOS)

### ISSUE THREAD

**Issue by critterverse** [WordPress/gutenberg#32437]
Tested on macOS Big Sur Version 11.4 on Chrome, Firefox, and Safari with the OS preference for “Show scroll bars: Always” turned on.

I noticed a bug where there is a lot of extra space at the bottom of the sidebar content area on the Customizer menu screen. The bug only appears when you have visible scoll bars enabled, and visit a section of the Customizer that _does_ have long scrolling content like the Widgets editor. When you return the Customizer menu screen, the scroll bar remains even though the items are not going past the fold on the page:

https://user-images.githubusercontent.com/77359364/120666233-6d03d300-c45a-11eb-9405-9b52e9df7d69.mov

**Comment by critterverse** [comment]
Closing this and re-opening as a trac ticket!

**Comment by stokesman** [comment]
I can't imagine this is unique to macOS but I haven't tested on other platforms. I'm also pretty sure it's due to the widgets editor and thus should meet the criteria for inclusion in 5.8, so I've added it to the project.

I'd ended up creating an issue for this too before I saw this one and I'm pasting in the screen recording I made since it's show the scrollbars appearing/disappearing depending on the widgets editors screen.

https://user-images.githubusercontent.com/9000376/121068560-49ee6180-c781-11eb-97ff-f82b8a77797c.mp4

Should be a straightforward fix I think but I've no familiarity with what API the Customizer provides to hook into panel switching.
