### ISSUE TITLE
InnerBlocks' `allowedBlocks`whitelist not respected due to `parent` field of another block's `block.json`.

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#32436]
## Description

The `<InnerBlocks>` API enables a developer to provide a whitelist of `allowedBlocks` which should determine which blocks are allowed to be inserted as child blocks.

A good example of this is [the `core/navigation` block which defines an `ALLOWED_LIST` as a constant](https://github.com/WordPress/gutenberg/blob/6da0390f864c68dc69494d50d586e8c0d841835e/packages/block-library/src/navigation/edit.js#L87).

However, currently on `trunk` if a child block defines a `parent` in its `block.json` then it will _always_ be available as an "allowed block type" even if the _parent_ block has excluded it from the allowed blocks.

The reason for this appears to be the `canInsertBlockTypeUnmemozied` selector

https://github.com/WordPress/gutenberg/blob/6da0390f864c68dc69494d50d586e8c0d841835e/packages/block-editor/src/store/selectors.js#L1324-L1353

Essentially the current logic allows a block to be available if _either_:

1. The parent has allowed it via `<InnerBlock>`'s  `allowedBlocks`.
2. The block itself has defined the parent block in the `parent` field of its `block.json`.

As a result, even if `#1` is false, if `#2` is true then the block will be made available despite the fact that the parent's block list settings explicitly defined that it should _not_ be available.

For an example see the `core/navigation-link` block which [defines `core/navigation` as a `parent` block in its `block.json`](https://github.com/WordPress/gutenberg/blob/6da0390f864c68dc69494d50d586e8c0d841835e/packages/block-library/src/navigation-link/block.json#L7).

## Steps to reproduce

You can test the problem for yourself. 

* **Make sure you are on `trunk`.**
* Go to the `core/navigation` block's `edit.js` and replace

https://github.com/WordPress/gutenberg/blob/6da0390f864c68dc69494d50d586e8c0d841835e/packages/block-library/src/navigation/edit.js#L32-L39

with

```js
const ALLOWED_BLOCKS = [
	// 'core/navigation-link',
	'core/search',
	// 'core/social-links',
	// 'core/page-list',
	'core/spacer',
	// 'core/home-link',
];
```

This should mean that _only_ spacer and search blocks are allowed as child blocks of Navigation.

* Build the Plugin - `npm run dev`.
* Now insert a navigation block.
* Try adding items via the block inserter.
* You should lots of blocks available rather than the expected whitelist you defined earlier.

## Expected behaviour
If a given block A defines a set of `allowedBlocks` and passes that to `<InnerBlocks>` then only those blocks should be available as "allowed blocks" even if another block B defines block A as a `parent` in `block.json`.

## Actual behaviour
If a block defines another block as a `parent` via `block.json` then it will always be available even if the other block excludes it from the `allowedBlocks` list of `<InnerBlocks>`.

## Screenshots or screen recording (optional)

<img width="2087" alt="Screen Shot 2021-06-03 at 17 15 18" src="https://user-images.githubusercontent.com/444434/120677722-4c09a500-c48f-11eb-9029-e5f298a1c181.png">

## WordPress information
- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: 
- Operating system: 
- Browser:

**Comment by getdave** [comment]
@talldan Might you have 5mins to verify this? It would be much appreciated. I suspect this is the core reason why we are using block filters to manually force the available blocks for the Nav Editor.

**Comment by draganescu** [comment]
In my understanding, the gist of the above is that allowed blocks should have more strength than parent. 

I 100% think you're right to expect so as well, since:

- a block specifying its allowed parent is a matter of block availability
- a block specifying a list of allowed blocks is a matter of functionality

If a parent specification overrides the allowed blocks specification it has high chances to crash the parent. If the allowed blocks overrides the parent nothing breaks (if the only available parent of block x does not allow block x, nothing breaks, it's a small bug).

**Comment by getdave** [comment]
> In my understanding, the gist of the above is that allowed blocks should have more strength than parent.

I believe you are correct 👍 

> Returns the list of allowed inserter blocks for inner blocks children

Also `__experimentalGetAllowedBlocks` actually appears to be specifically focused on what is allowed in the _inserter_. 

Indeed it specifically tests for

```js
hasBlockSupport( blockType, 'inserter', true ) ) 
```

In which case I think we should rename the method as I took it to mean "tell me which blocks are allowed to be inserted into the editor _in general_".

**Comment by draganescu** [comment]
What is the difference between blocks allowed in the inserter and blocks allowed to be inserted in a block? I think I get the answer but we may need to spell it out. Do we need hidden blocks? If so, what is the difference between hidden and not allowed?

**Comment by talldan** [comment]
It's worth considering how plugins might work. A block might have a setting for `allowedBlocks`. A plugin has no way of modifying that. If a plugin wants to add a new supported inner block type to the navigation block, the only option is the `parent` property.

So I think the current behaviour is correct. Making `allowedBlocks` have precedence would severely limit what plugins can do.

It's been mentioned before that `parent` is a bit limited. Once it's set, the block can't be used globally, which is what Page List, Spacer, Social Links and Search all require, so they're in the allowed blocks list because they can't use `parent`. Blocks that have a limited context (button in buttons, social link in social links) should probably all only use `parent` for consistency.

> Also __experimentalGetAllowedBlocks actually appears to be specifically focused on what is allowed in the inserter.

Yeah, I've mentioned before this could be renamed and stabilised, but it slips my mind now what a good name would be - https://github.com/WordPress/gutenberg/issues/25786#issuecomment-703391425 (cc @draganescu).

**Comment by getdave** [comment]
> A block might have a setting for allowedBlocks. A plugin has no way of modifying that. If a plugin wants to add a new supported inner block type to the navigation block, the only option is the parent property.

> So I think the current behaviour is correct. Making allowedBlocks have precedence would severely limit what plugins can do.

I'm thinking this might be just a limitation of the block supports API (ie: it's not filterable)? It feels like we're allowing `parents` to take precedent purely in order to allow Plugins to modify where a block appears. To me as a developer if I set a whitelist of `allowedBlocks` on my `InnerBlocks` I'd expect that to be honoured. I certainly wouldn't expect this to be overridden because of another prop that seems (at least initially and without a lot of debugging) unrelated.

Should we instead look at if/how we can make the Block Supports API more extensible for Plugin developers? Indeed I see some overlap here with `theme.json`. As a theme author, I might want to limit what blocks can be added to the `core/navigation` block and I should be able to do that via `theme.json`.

**Comment by talldan** [comment]
> To me as a developer if I set a whitelist of allowedBlocks on my InnerBlocks I'd expect that to be honoured.

I'm not sure, it seems a bit of an existential question—if `parent` is set shouldn't that also be honoured? I think of `parent` as the equivalent of a `from` transform, where a block developer shouldn't have to modify other blocks to specify a transform, they should be able to make it work from a single block specification. In the same way, if a third part developer wants to make a block for use only in the nav block, they shouldn't need to modify the nav block. So `parent` could be considered as adding to `allowedBlocks` rather than conflicting with it.

It might also be difficult to change the order of precedence now, because it'd be a breaking change.

----

> Should we instead look at if/how we can make the Block Supports API more extensible for Plugin developers?

There have been some past issues about extending `allowedBlocks`, along with some other ideas, definitely would be good to explore that further:
- https://github.com/WordPress/gutenberg/issues/14515
- https://github.com/WordPress/gutenberg/issues/15682
- https://github.com/WordPress/gutenberg/issues/24596

Possibly a few duplicate issues, and worth searching for others that I didn't catch.

**Comment by getdave** [comment]
This isn't a question I can answer at this point so closing for now.

**Comment by mikeybinns** [comment]
I know this is a really old ticket, but I have just run into the same issue, so I'll chime in with my use case.

I've made a custom navigation block. It has effectively a 3 tier block structure. Top level blocks are "Navigation" (collapses into mobile style menu) and "Nav list group" (a static list of links like you'd find in a footer). Inside those blocks is a "Nav list" (the actual list element of the nav) block, and inside that child blocks "submenu" and "menu link".

I wanted to block "submenu" from being allowed in the nav list if it's a child of the "Nav list group" block, but keep it available if it's a child of the "Navigation" block.

I agree with what's mentioned above, I think it's expected that allowedBlocks would take precedence because of conditional situations like this, however I also think @talldan is correct about it being a breaking change and therefore difficult to implement.

As a workaround for my specific situation, I was able to overcome it by setting the "Navigation" block as an ancestor for submenu alongside the parent for "nav list", which removes it from the list under "Nav list group".
