### ISSUE TITLE
UnitControl: Consumers should only have to specify allowed units & defaults

### ISSUE THREAD

**Issue by aaronrobertshaw** [WordPress/gutenberg#32478]
## What problem does this address?
As the UnitControl is used more frequently, consumers are having to resupply the entire CSS units config when needing a subset of the default units. This creates a couple of issues:

- string translation: redefining the units creates the same multiple entries for folk to translate
- maintainability: all consumers need to be changed when a label needs to be changed

Discussion: https://github.com/WordPress/gutenberg/pull/31483#discussion_r645685944

## What is your proposed solution?

Update the UnitControl to only ask for allowed units and their defaults. This would leave common values/labels etc in the one place.

**Comment by aristath** [comment]
This was already done in https://github.com/WordPress/gutenberg/pull/31822

I see since then a few more CSS_UNITS were added for border-radius and letter-spacing, so PR https://github.com/WordPress/gutenberg/pull/32482 replaces these.

We use the `useCustomUnits` function to get an array of properly formatted units - and that also allows us to inherit values from theme.json and provide default values for each unit:

```js
const units = useCustomUnits( {
	availableUnits: useSetting( 'spacing.units' ) || [
		'px',
		'em',
		'rem',
		'vw',
		'vh',
	],
	defaultValues: { px: '430', em: '20', rem: '20', vw: '20', vh: '50' },
} );
```

**Comment by aaronrobertshaw** [comment]
Thanks @aristath, the PR with changes to the border support took some time to go through the usual process and land. It's great to see this has already been addressed. I'll update the comments on the original PR.
