### ISSUE TITLE
Scripts: Stop using shebangs to prevent issues with Windows environments

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#32504]
## What problem does this address?

Related issue: #32258.

Related comment in https://github.com/WordPress/gutenberg/pull/31279#discussion_r642307708 by @mcsf:

> As much as I love [shebangs](https://en.wikipedia.org/wiki/Shebang_(Unix)), AFAIK they just don't work well or at all with Windows. This just emerged in #32329. I'm wondering if we should/could forbid it with our linter — wdyt?

On Windows when running a script that uses shebangs you will encounter the following error message:

```
'.' is not recognized as an internal or external command,
operable program or batch file.
```

## What is your proposed solution?

Related comment by @mcsf in https://github.com/WordPress/gutenberg/pull/31279#discussion_r646462148:

> The alternative would be to just not have any shebang, meaning that scripts would just have code:
> 
> ```js
> 1. /**
> 2.  * External dependencies
> 3.  */
> 4. const builder = ...;
> ```
> 
> This would make it impossible for anyone in a UNIX system to invoke `./index.js` (they would have to explicitly call the interpreter with `node index.js`), thus eliminating the possibility of merging something that would break in Windows.

The task is to find all scripts that use shebang like:

https://github.com/WordPress/gutenberg/blob/8bc24948c580ae37d3dbe8fde08bb248c4e61e83/bin/plugin/cli.js#L1

and check if they work correctly with Windows. Some might work like:

https://github.com/WordPress/gutenberg/blob/8bc24948c580ae37d3dbe8fde08bb248c4e61e83/packages/create-block/index.js#L1

because they are linked in the `bin` folder in `node_modules`:

https://github.com/WordPress/gutenberg/blob/8bc24948c580ae37d3dbe8fde08bb248c4e61e83/packages/create-block/package.json#L30-L32

@mcsf, how do we decide? 😄

**Comment by mcsf** [comment]
Hm, I wasn't aware of the special treatment of scripts linked via the `bin` property in `package.json`. The [docs](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#bin) even stress:

> Please make sure that your file(s) referenced in bin starts with `#!/usr/bin/env node`, otherwise the scripts are started without the node executable!

Which leads me to think that Node must do some special dance in Windows runtimes in order to handle these well.

In that case, I withdraw my recommendation to remove shebangs. I think trying to discern good shebangs from bad ones will be difficult, and with little payoff. If any other reports from Windows users come our way, we'll patch those issues _ad hoc_.

If you agree, you can close this issue. In that case, I'm sorry to have wasted your time with this, @gziolo. :)

**Comment by gziolo** [comment]
Interesting learning about the recommendation for `package.json` setup related to scripts linked via `bin` 👍🏻
