### ISSUE TITLE
Latest Posts and Latest Comments blocks don't look great when editor styles are disabled

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#32718]
## Description

With "Use theme styles" turned off, the Latest Posts and Latest Comments blocks don't look great.

## Step-by-step reproduction instructions

1. Go to Posts → Add New.
2. Go to Preferences → Appearance and turn off "Use theme styles".
3. Insert a Latest Posts and Latest Comments block.
4. Select the Latest Comments block and turn off "Display avatar", "Display date", and "Display excerpt".

## Expected behaviour

I would expect both blocks to appear as regular unstyled unordered lists, like so.

<img width="1252" alt="Screen Shot 2021-06-16 at 14 01 32" src="https://user-images.githubusercontent.com/612155/122155976-612cfd80-ceab-11eb-8c03-e2ee22d61c9f.png">

## Actual behaviour

They don't look like lists.

<img width="1252" alt="Screen Shot 2021-06-16 at 13 59 58" src="https://user-images.githubusercontent.com/612155/122156022-7b66db80-ceab-11eb-95f2-b8277a7168d5.png">

**Comment by draganescu** [comment]
There is a long standing problem with styling the list item in the Customizer: it is missing its bullets:

<img width="1442" alt="Screen Shot 2021-06-17 at 09 13 58" src="https://user-images.githubusercontent.com/107534/122341836-976e8980-cf4c-11eb-86b1-fc350f4bc281.png">

**Comment by kevin940726** [comment]
It seems to be explicitly added in #14627. Not sure about the design decisions there though 🤔, maybe @getdave has some thoughts?

**Comment by getdave** [comment]
Gosh that was a long time ago. My brain seems to suggest we removed it because when you add the Latest Posts Block to the main content you didn't want bullet points for each entry in the list, especially if you had the full excerpt and content turned on.

That said it does seem like perhaps that should have been behind a guard to only happen if there is except and content being shown in the list.

I'd suggest perhaps the block shouldn't provide these styles and instead should have an option "show bullet points" which determines whether or not we add/remove the bullets.

**Comment by getdave** [comment]
I've spun up https://github.com/WordPress/gutenberg/pull/32806 as a PoC to see if we want to take this approach.

**Comment by noisysocks** [comment]
Closing as fixed by https://github.com/WordPress/gutenberg/pull/32983.
