### ISSUE TITLE
Reusable block: Making it easier to understand that one is removing the Reusable block from a page.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#32748]
The problem: It is not clear that one is removing a Reusable block or removing the inner content. As it will say Remove block at any level one is on.

Reported here:
https://core.trac.wordpress.org/ticket/53434

From my understanding of the above report the user is wondering how to delete a Reusable block from a page without it affecting all other instances used of the Reusable block.

----

Here is a screenshot I shared in the above Trac Ticket:
![Remove-Reusable-block-top-container](https://user-images.githubusercontent.com/5323259/122280036-09ad8280-cee9-11eb-800b-bd5dcdc4e283.jpg)

As the Reusable block is selected the words "Remove block" could instead say "Remove Reusable block (instance)" 
(or something similar).
![Remove-Reusable-block-instance](https://user-images.githubusercontent.com/5323259/122280667-b982f000-cee9-11eb-8ded-291aab89362b.jpg)

What is important with the above suggestion is that the words "Remove block" is replaced to clearly show that one is removing the instance of the Reusable block.

@jasmussen @critterverse

**Comment by critterverse** [comment]
>I'm in a situation where I need to delete a reusable block on one page without losing it on all the other pages that it appears on.

Since this is the current behavior, it seems like this user is mostly unclear about when the parent Reusable block is actually selected — I think your advice there will help a lot, @paaljoachim! It also helps that the "remove block" action as it works currently is non-destructive, not the reverse 😅

There has been some exploration in https://github.com/WordPress/gutenberg/issues/30357 about how to introduce options that are traditionally seen as "document-level" settings into the Inspector block-level settings for Reusable blocks. This would include things like Revisions and "Move to trash" (which usually appears in the Status & Visibility panel for other document types). I think these additions could go a long way towards helping differentiate a global delete that's associated with the post type and a local delete that's associated with the current page. It would be great to also include a little one-liner explanation in the sidebar to explain that the "Move to trash" option there is a global one.

**Comment by jasmussen** [comment]
This is one of the reasons why I believe the "clickthrough" interface is a good interface here. By clickthrough I mean a colored overlay that indicates when you click this block, you click the parent first: the reusab le block itself. Meaning if you need to remove it, you just press Delete, just like if you select an image and it's focused.

**Comment by Xilonz** [comment]
> This is one of the reasons why I believe the "clickthrough" interface is a good interface here. By clickthrough I mean a colored overlay that indicates when you click this block, you click the parent first: the reusab le block itself. Meaning if you need to remove it, you just press Delete, just like if you select an image and it's focused.

This is a snippet I just created that simulates the "click first on reusable block, then on the contents". Wouldn't be too hard to add a ::before element that does the colored overlay. 
```
.wp-block.is-reusable:not(.is-selected):not(.has-child-selected) .block-library-block__reusable-block-container * {
    pointer-events: none;
}
```

**Comment by jordesign** [comment]
Although the terminology is different - this issue still seems relevent. Perhaps the wording at the pattern level could be changed to 'Remove Pattern' instead of 'Delete'? This seems an easy win - what do you think @jasmussen 

<img width="708" alt="Screenshot 2023-10-30 at 5 33 43 pm" src="https://github.com/WordPress/gutenberg/assets/1842363/40ce08c7-32ec-45dd-adac-93676b9fd748">

**Comment by jasmussen** [comment]
Ultimately whether you select a pattern, synced or not, everything is blocks, and so the term should be the same. And it is indeed "Delete" now:

![Screenshot 2023-10-30 at 07 44 26](https://github.com/WordPress/gutenberg/assets/1204802/36836152-2b25-424e-b8a8-bbfc498c2c38)

**Comment by jordesign** [comment]
That being the case - do you think we can close this issue as wontfix? As the first click now _does_ select the pattern as a whole?

**Comment by jasmussen** [comment]
Sure.
