### ISSUE TITLE
API to define a default template for the template mode

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#32752]
WordPress 5.8 will introduce a template mode in the post editor https://make.wordpress.org/core/2021/06/14/introducing-the-template-editor-in-wordpress-5-8/ 

That mode allows users to create block templates and assign them to posts and pages. A default starting template is used to repopulate newly created templates.

Ideally, themes should be able to define the content of the initial template. Let's try to provide an API to do so. This API should be able to scale to FSE themes as well.

The simplest solution might be to add a settings to the `block_editor_settings_all` filter as this can be provided in php and made translatable easily. 

An alternative would be a file in the theme (convention) but since we don't want to add block-templates to themes yet, it seems premature for this option.

cc @TimothyBJacobs @aristath

**Comment by aristath** [comment]
Using the `block_editor_settings_all` filter would make sense... 
The 1st thought that came to mind was introduce a `block-template-default.html` file, but the filter sounds more versatile, and it can still be used with a file using something like
```php
add_filter( 'block_editor_settings_all', function( $settings ) {
    $settings['block_template'] = file_get_contents( get_theme_file_path( 'block-template-default.html' ) );
    return $settings;
});
```
so using the filter does not exclude using a file... it makes sense to do something like that since it leaves the door open for other future implementations

**Comment by youknowriad** [comment]
yes, that make sense maybe it should be named more something like `default_block_template`?

**Comment by aristath** [comment]
> maybe it should be named more something like `default_block_template`?

Yes, that would make sense. Or even `default_block_template_content` if we want to be more verbose/accurate :+1:
