### ISSUE TITLE
"This block contains unexpected or invalid content" => although same content / plus replacing tag

### ISSUE THREAD

**Issue by Jugibur** [WordPress/gutenberg#32916]
## Description
Gutenberg shows the message "This block contains unexpected or invalid content" right after saving the post (and reload) without changing the content of this block.
It is a "core/heading" block **h3** and after try to resolve the block by Gutenberg it changes it to **h2**.

This issue maybe encountered, because I'm adding the default block class name the "core/heading" and some blocks (for better styling).

## Step-by-step reproduction instructions
Please use the code below to add a default class name with JS to some blocks and have create a custom post type with a base template.
I've tested it in theme 'Twenty Twenty-One'.

## Expected behaviour
There shouldn't be a message because nothing changed, it was a "fresh" heading block.
Plus: After resolving this by Gutenberg the h-tag shouldn't changed!

## Actual behaviour
After creating a new post I checked the HTML-Code, it is in my example:
`<h3 class="wp-block-heading">Headline Example</h3>`
So it's exactly what I wanted.

I just select the headline – but changed no content and no style. 
Then, after saving and reloading my post, the message "This block contains unexpected or invalid content" appears and after resolving it by Gutenberg the HTML-Code changes to:
`<h2 class="wp-block-heading">Headline Example</h2>`

## Code snippet (optional)
Please copy this to the function.php of 'Twenty Twenty-One' or a base theme:

```php
register_post_type('post_test', array(
	'labels' => array(
		'name' => 'Post Test',
	),
	'public' => true,
	'show_in_rest' => true, 
	'template' => array(
		array( 'core/heading', array( 
			'level' => '3',
			'content' => 'Headline Example',
			'className' => 'wp-block-heading'
		) ),
	)
));
```

To add the default class name to some blocks, I'm using this code and insert it to 'Twenty Twenty-One' under assets/js/editor.js
```js
function addBlockClassName(settings, name) {
	
	if (
		(name !== 'core/list')
		&& (name !== 'core/heading')
		&& (name !== 'core/button')
	) {
        return settings;
    }
    return lodash.assign( {}, settings, {
        supports: lodash.assign( {}, settings.supports, {
            className: true
        } ),
    } );
}
wp.hooks.addFilter(
    'blocks.registerBlockType',
    'dab/add-block-classname',
	addBlockClassName
);
```

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.8.2 
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: macOS 10.14.6
- Browser: Firefox 89.0.1

**Comment by getdave** [comment]
I'm not 100% but I suspect this is because you'd be better off adding the `wp-block-heading` via a JS filter

https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters/#blocks-getblockdefaultclassname

That way you wouldn't need to modify the className when you define the template.

Also on the topic of templates you might like [this article I wrote on creating templates using block content copied from the editor](https://aheadcreative.co.uk/articles/setting-default-wordpress-editor-block-templates-via-php-from-block-grammar/).

**Comment by talldan** [comment]
@Jugibur Thanks for reaching out. Sorry some time passed before you got an answer to this. You might have already solved it.

It looks like the issue is with your CPT template. There are two separate issues.
- 'level' should be defined as a number, but you have it as a string. This makes the type checking fail, and is why you see the heading revert to level 2.
- `className` isn't needed because it's added in the saved content by your JavaScript filter.

Changing the template to this makes it work correctly:
```php
register_post_type('post_test', array(
	'labels' => array(
		'name' => 'Post Test',
	),
	'public' => true,
	'show_in_rest' => true, 
	'template' => array(
		array( 'core/heading', array( 
			'level' => 3,
			'content' => 'Headline Example',
		) ),
	)
));
```
