### ISSUE TITLE
Adding Format Button to the Toolbar

### ISSUE THREAD

**Issue by TeamDNK** [WordPress/gutenberg#32943]
## Description
Registering a format button with a [whitelisted](https://github.com/WordPress/gutenberg/blob/3da717b8d0ac7d7821fc6d0475695ccf3ae2829f/packages/block-editor/src/components/rich-text/format-toolbar/index.js#L23) name allows for filling the ToolbarControls slot. Is this intended and could this be used to insert a format that would be heavily used on a specific post type?

## Step-by-step reproduction instructions
1. Register format
2. For the format name property, use 'text-color'

## Screenshots or screen recording (optional)
![image](https://user-images.githubusercontent.com/64434855/123171584-ddd25580-d430-11eb-866d-c4c060793e81.png)

## Code snippet (optional)
```
<RichTextToolbarButton
  title="Tooltip"
  name={ "text-color" }
  icon={ icon }
  ...
/>
```

## WordPress information
- WordPress version: 5.7.2

**Comment by tellthemachines** [comment]
Interesting loophole 😄 I don't believe it is intended. A deliberate API would allow an optional prop to be passed to `RichTextToolbarButton` specifying if the button should appear in the toolbar or not, and its usage would be documented.

With the above in mind, I'd recommend not using it because it's not guaranteed to continue working indefinitely; any changes to the internal logic of the component could break that accidental feature.

**Comment by tellthemachines** [comment]
I'm going to go ahead and close this issue; feel free to open a new one if you have any further questions!
