### ISSUE TITLE
Widgets Editor: Third party blocks reported as registered with an invalid category

### ISSUE THREAD

**Issue by dreamwhisper** [WordPress/gutenberg#32993]
## Description
Third party blocks reported as registered with an invalid category on widget screens.

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. Activate a third party plugin such as Genesis Blocks.
2. Go to the widgets screen or the customizer.
3. View the console and note `The block "genesis-blocks/gb-someblock" is registered with an invalid category "genesis-blocks".`

## Expected behaviour

No message about an invalid category in the console.

## Actual behaviour
See Screenshots.

## Screenshots or screen recording (optional)
<img width="728" alt="Screen Shot 2021-06-25 at 9 43 45 AM" src="https://user-images.githubusercontent.com/1271053/123435319-7389f400-d59b-11eb-89d2-115f0bec45d2.png">

<img width="673" alt="Screen Shot 2021-06-25 at 9 51 29 AM" src="https://user-images.githubusercontent.com/1271053/123435328-75ec4e00-d59b-11eb-8a4b-9ee1aa0791b4.png">

<img width="741" alt="Screen Shot 2021-06-25 at 9 56 10 AM" src="https://user-images.githubusercontent.com/1271053/123435471-99af9400-d59b-11eb-9e7b-513fd9c54392.png">

## WordPress information
- WordPress version: 5.8-beta3-51230
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: Mac
- Operating system: 10.15.x
- Browser: Chrome

**Comment by talldan** [comment]
Thanks for reporting this. This is expected.

Unfortunately the `block_categories` filter couldn't really be made to work with non-post screens (since the filter receives a post object, which the widget editor doesn't have), it will be deprecated in WordPress 5.8, though it will still continue to work as expected in the post editor. 

There's a new `block_categories_all` filter that will solve the issue, and plugins should update to use that.

There's some background here - https://core.trac.wordpress.org/ticket/52920. A dev note will also be published about the changes.
