### ISSUE TITLE
Manually using backticks does not render inline code

### ISSUE THREAD

**Issue by eduardozulian** [WordPress/gutenberg#33004]
## Description

It appears that using single \`backticks\` for inline code is not working since version 10.7.0. Instead of the actual code rendered, \`code\` will appear.

## Step-by-step reproduction instructions
1. Start a new post/page
2. Start a paragraph 
3. Add one backtick, type something, add another backtick, and hit space. Example: \`code\`

## Expected behaviour
To see something like:

This is `code`

From my tests, this worked until [version 10.6.2](https://github.com/WordPress/gutenberg/releases/tag/v10.6.2)

## Actual behaviour
The code does not render:

<img width="228" alt="Captura de Tela 2021-06-25 às 20 01 39" src="https://user-images.githubusercontent.com/1136160/123492563-3a2fa380-d5f0-11eb-8740-5788d4b4ab71.png">

For now, the only solution is to manually select the text, use the toolbar dropdown, and choose "Inline code".

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/1136160/123493032-a232b980-d5f1-11eb-8bcc-4a2b45ba84bd.mp4

## WordPress information
- WordPress version: 5.7.2.
- Gutenberg version: Any after version 10.6.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Macbook Pro
- Operating system: MacOS Bug Sur 11.4
- Browser:  Chrome 91.0.4472.114

**Comment by talldan** [comment]
I tested and couldn't reproduced any issues.

I tested 5.7.2 and 5.8 beta with the Gutenberg plugin disabled, and 5.8 with the latest Gutenberg trunk checked out. (Mac OS / Brave)

Is this a freshly setup site, @eduardozulian?

**Comment by eduardozulian** [comment]
@talldan I tried with two separate installs, one of them being fresh, both with WP 5.7.2.

As soon as I activate the Gutenberg, I experience the same as presented in the above video.

Thanks for checking!

**Comment by skorasaurus** [comment]
Sorry, I too tested, and the code is displayed as intended; no issues found. 

https://user-images.githubusercontent.com/955351/123690561-83ffd000-d822-11eb-91e2-c841387f2f58.mp4

I'm using 10.9.1, wordpress 5.7.2 on a vanilla wordpress install with both twentytwenty and twentytwenyone themes. Used chrome Version 91.0.4472.114 (Official Build) (64-bit) on ubuntu

**Comment by talldan** [comment]
Hmm, I'm confused about what's happening then. I'm wondering if it could be related to keyboard layout—perhaps the backtick is a slightly different character code on some keyboard layouts. The block editor checks for `0x60`.

What keyboard layout do you use @eduardozulian?

**Comment by mcsf** [comment]
Per a private exchange on Slack, it seems likely that this issue affects keyboard layouts in which backticks are produced using [key composition](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/isComposing).

For instance, on my Portuguese (pt-pt) keyboard layout, a backtick is produced using the chord <kbd>shift + ´</kbd>, followed by <kbd>space</kbd>. This is because the initial chord produces a [grave accent](https://en.wikipedia.org/wiki/Grave_accent) <kbd>\`</kbd> but waits for the next key to decide how to compose the characters. For instance, the chord <kbd>shift + ´</kbd> followed by <kbd>a</kbd> produces <kbd>à</kbd>. A backtick is just a grave accent on its own, hence the use of <kbd>space</kbd>. This feature in keyboards is also known as a [dead key](https://en.wikipedia.org/wiki/Dead_key).

I assume that @eduardozulian is using either a Brazilian Portuguese (pt-br) or even a version of the US layout with international keys that also features dead keys.

> From my tests, this worked until version 10.6.2

This is some precise bisecting, thank you! To be clear, is 10.6.2 the last good version, or the first bad one?

**Comment by mcsf** [comment]
> This is some precise bisecting, thank you! To be clear, is 10.6.2 the last good version, or the first bad one?

I just tested this myself: 10.6.2 is the last good version, and 10.7.0 the first bad one.

Edit: this means that it's a regression in the current Release Candidate for WordPress 5.8.

**Comment by mcsf** [comment]
A Git bisection revealed https://github.com/WordPress/gutenberg/pull/31752 as the origin.

**Comment by eduardozulian** [comment]
@mcsf you got it! I'm currently using the US English Layout as shown in the following image:

<img src="https://cdn.shopify.com/s/files/1/0810/3669/files/us-english-mac-keyboard-layout-keyshorts_1024x1024.png?79"/>

And I don't think it's needed anymore but yeah, I can confirm that the latest good version was indeed 10.6.2.

Thanks for checking this further, Miguel, and also thank you both @talldan and @skorasaurus here. Sorry for the delay in my replies!

**Comment by ellatrix** [comment]
I still can't reproduce the issue for a US keyboard. I have the same keyboard, using macOS Big Sur and Chrome. 🤔
What I _can_ reproduce is the dead key issue, but that doesn't apply to a US keyboard.
Looking to fix the other issues now.
