### ISSUE TITLE
CTRL + K or CDM + K on a phrase starting with # creates an internal link

### ISSUE THREAD

**Issue by wpgaurav** [WordPress/gutenberg#33009]
## Description
Say I have written a paragraph that has
`Mahatma was ranked #12 in the list of the most powerful leaders`.

If I select **#12 in the list of the most powerful leaders** and hit CTRL K, it creates an internal link to `#12-in-the-list-of-the-most-powerful-leaders`.

Is that intentional? Even if that's I cannot find a real-life use-case of this.

WP: 5.7.2
Gutenberg: 10.9.0
Chrome 91 on Windows

**Comment by talldan** [comment]
I don't think it's intentional, thanks for reporting it. Luckily it's fixed by #32663, which has just been merged and will be in the next version of the plugin.

With that, the link will only be automatically created if the text is a valid anchor or URL link (e.g. highlighting '#my-heading' would automatically create a link to `#my-heading`).
