### ISSUE TITLE
Block Transforms From option missing on core-embed/youtube block

### ISSUE THREAD

**Issue by thetwopct** [WordPress/gutenberg#33059]
## Description

When creating a block and using the transforms API, converting from the `core-embed/youtube` block doesn't display an option to convert the YouTube embed block to the new block.

## Step-by-step reproduction instructions

In your custom block JS file:

```
		transforms: {
			from: [
				{
					type: 'block',
					blocks: [ 'core-embed/youtube', 'core/paragraph' ],
					transform: ( { content } ) => {
						return createBlock( 'lf/my-other-block', {
							myVariable: content.url,
						} );
					},
				},
			],
		},
```

## Expected behaviour

The block transform option is expected to show on the YouTube block, but it doesn't. 
The block transform option does show on the Paragraph, so the Transforms API and code I use is working.

## Actual behaviour

The new block transform option is missing from the YouTube embed block.

![2021-06-29-141352@2x](https://user-images.githubusercontent.com/10615884/123753619-419ec780-d8e4-11eb-9789-82e1376164f5.jpg)

The block transform option does show on the Paragraph block (as per my Transforms code), so the Transforms API and code I use is working.

![2021-06-29-142708@2x](https://user-images.githubusercontent.com/10615884/123755467-1d43ea80-d8e6-11eb-8068-bf553a0172af.jpg)

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: Not installed / core.
- Are all plugins except Gutenberg deactivated? All plugins deactivated except custom blocks
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: Mac
- Operating system: MacOS
- Browser: Safari

**Comment by talldan** [comment]
Hi @thetwopct. I think the problem is there isn't a block called `core-embed/youtube`. The block is called `core/embed`, and it has a block variation of 'youtube'.

Your best option would be to write your transform against the `core/embed` block, and use an `isMatch` function on your transform, and check the block's `providerNameSlug` attribute is `'youtube'`. (docs - https://developer.wordpress.org/block-editor/reference-guides/block-api/block-transforms/#block)

The might mean having two separate `from` transforms as the `isMatch` wouldn't work for the paragraph block you've also specified.

Some other reference info ... here's the embed block's type info - https://github.com/WordPress/gutenberg/blob/a125447b6383e0a186e3614fdd886c61f2651a1c/packages/block-library/src/embed/block.json#L3

The block variation is defined here - https://github.com/WordPress/gutenberg/blob/a125447b6383e0a186e3614fdd886c61f2651a1c/packages/block-library/src/embed/variations.js#L46-L57

**Comment by thetwopct** [comment]
Thanks @talldan, makes sense, seems the `core-embed/block` [was the old way to target them](https://github.com/WordPress/gutenberg/blob/a7e2895829c16ecd77a5ba22d84f1dee1cfb0977/packages/blocks/src/api/parser.js#L437).

**Comment by talldan** [comment]
Ah right, I didn't realise the old block name was prefixed `core-embed` like that. 👍
