### ISSUE TITLE
Update button remains disable even after making changes in reusable block

### ISSUE THREAD

**Issue by thisissandip** [WordPress/gutenberg#33072]
## Description
Even after making changes to the reusable block, the update button remains disabled.

## Step-by-step reproduction instructions
1. Add a reusable block
2. Edit the reusable block
3. Check the update button

## Expected behaviour
Update button should be highlighted/enabled like the image below to let the user know there are changes to be saved.

![image](https://user-images.githubusercontent.com/69596988/123832105-9fea9b00-d922-11eb-92e2-9b95ee565a53.png)

## Actual behaviour
Update button is disabled

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/69596988/123831308-d247c880-d921-11eb-832c-e2c515c90faa.mov

**Comment by Mamaduka** [comment]
This can be related to the changes in #32889.

/cc @ockham

**Comment by ockham** [comment]
Aww, crap 😕  Sorry about this, I'll work on a fix tomorrow 👍

**Comment by ockham** [comment]
Note to self, we should definitely add some test coverage. Probably at the [unit test level](https://github.com/WordPress/gutenberg/blob/012461b161b915496ad4aef3b5fd0727abedf583/packages/editor/src/components/post-publish-button/test/index.js), but maybe also to the [reusable blocks e2e tests](https://github.com/WordPress/gutenberg/blob/012461b161b915496ad4aef3b5fd0727abedf583/packages/e2e-tests/specs/editor/various/reusable-blocks.test.js).

**Comment by ockham** [comment]
Okay, I dug a bit into this.

I checked all of the predicates that go into `isButtonDisabled`: https://github.com/WordPress/gutenberg/blob/d3fb83c4d7097b31b28184e3a9cd18f6e5667724/packages/editor/src/components/post-publish-button/index.js#L108-L113

Turns out that none of them are a reliable indicator for when we're saving non-post entities. Thus, we cannot at the same time have the button enabled when there are changes to a non-post entity (such as a reusable block), _and_ disable it while we're saving a non-post entity (such as the Site Title block).

I'll revert https://github.com/WordPress/gutenberg/pull/32889 for now, in order to restore the behavior for reusable blocks. A more complete solution will require an `isSavingNonPostEntity` selector.

**Comment by ockham** [comment]
Noting that `packages/e2e-tests/specs/editor/various/reusable-blocks.test.js` [didn't fail](https://github.com/WordPress/gutenberg/runs/2904176499) for https://github.com/WordPress/gutenberg/pull/32889, so we should make sure to add test coverage for this regression. I'll give that a quick spin.

**Comment by ockham** [comment]
> Noting that `packages/e2e-tests/specs/editor/various/reusable-blocks.test.js` [didn't fail](https://github.com/WordPress/gutenberg/runs/2904176499) for #32889, so we should make sure to add test coverage for this regression. I'll give that a quick spin.

https://github.com/WordPress/gutenberg/pull/33151
