### ISSUE TITLE
Forward slash inserter doesn't work in the widgets editor

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#33099]
When using the forward slash inserter in the new Widgets editor nothing happens.

### To reproduce

1. Use the latest WordPress 5.9 RC
2. Go to Appearance > Widgets
3. Add a paragraph block
4. Type "/"
5. Observe nothing happens

### Screenshots

https://user-images.githubusercontent.com/107534/123967606-25238d80-d9bf-11eb-98ce-5d33933a6a75.mp4

### Expected behavior

The slash inserter should behave like the one in the post editor, triggering the quick insert popover menu.

**Comment by tellthemachines** [comment]
I can only reproduce this when starting from an empty widget area and typing consecutive paragraphs. Interestingly enough, as soon as I hover over the widget area, causing the in-between inserter to appear, the autocomplete box shows up.

**Comment by tellthemachines** [comment]
So this is happening because at the point the popover menu tries to render, the list of valid blocks for insertion is empty, because `templateLock` is set to `all` (the filter is returning false [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/store/selectors.js#L1332)). I don't know why that's the case though, as we're setting templateLock to false in the [widget area inner block props](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-widgets/src/blocks/widget-area/edit/inner-blocks.js#L36). 

To make things worse, it doesn't happen every single time. It _only_ happens when adding blocks to an empty widget area, but maybe one time out of ten it works as expected 😖
