### ISSUE TITLE
Snackbar notices appear behind block inserter.

### ISSUE THREAD

**Issue by Addison-Stavlo** [WordPress/gutenberg#33114]
Running current `trunk` branch of gutenberg, i am noticing that snackbar notices appear behind the block inserter sidebar.

To Repro:
* Open the block inserter
* Insert a block pattern
* Notice the notices are hidden underneath the inserter sidebar

![Screen Shot 2021-06-30 at 3 48 29 PM](https://user-images.githubusercontent.com/28742426/124022732-35396e00-d9bb-11eb-8554-79c04b4a3643.png)

This seems to happen in both the post and site editors.

**Comment by Mamaduka** [comment]
I was able to reproduce the issue.

Code to trigger snackbar for testing from Console:
```js
wp.data.dispatch('core/notices').createSuccessNotice( 'Snackbar should be visible when block inserter is open', { type: 'snackbar' } );
```

**Comment by Mamaduka** [comment]
I did a little more research, and it looks like the issue is with stacking context.

The `components-snackbar-list` element's `z-index: 10000` only has effect inside its parent element - `interface-interface-skeleton__content`. Parent's sibling elements will treat it with same z-index as its parent. Which in our case is 20 and `interface-interface-skeleton__secondary-sidebar` has `z-index: 90`.

The easiest solution will be to move the `components-snackbar-list` outside the content element.

Example in Codepen: https://codepen.io/Mamaduka/pen/jOmPvmo

**Comment by youknowriad** [comment]
@Mamaduka can we try that in a PR. What are the implications of moving the snack list out?

**Comment by Mamaduka** [comment]
@youknowriad, I did a quick test, and if I move `<EditorNotices />` outside of the `<InterfaceSkeleton>` content, it breaks how other notices are displayed.

**Comment by youknowriad** [comment]
@Mamaduka maybe we should separate snackbars and regular notices into two components.

**Comment by Mamaduka** [comment]
I'm going in that direction now. I will have PR ready soon.

**Comment by Mamaduka** [comment]
PR is ready for review.
