### ISSUE TITLE
Social Icons: TikTok logo invisible when in "Logo only" style and on a black background

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#33168]
## Description
When the social icons are inside a black group block and "Logos only" is selected, the TikTok block is not visible:

Default:
<img width="871" alt="Screenshot 2021-07-02 at 14 18 06" src="https://user-images.githubusercontent.com/275961/124280522-b2422000-db40-11eb-899a-53832986c2d1.png">

Logos only:
<img width="871" alt="Screenshot 2021-07-02 at 14 18 16" src="https://user-images.githubusercontent.com/275961/124280531-b5d5a700-db40-11eb-8bed-b55fcf4c429e.png">

## Step-by-step reproduction instructions
- Add a group block
- Set the background to black
- Add a social icons block
- Add a tiktok block
- Switch the social icons block to be Logos only

## Expected behaviour
I'm not sure how to fix this - maybe the block can detect the color of the parent?

**Comment by jasmussen** [comment]
This is an interesting one, thanks for filing it! Here it is with a white background:

![logos](https://user-images.githubusercontent.com/1204802/124433532-2532dd00-dd73-11eb-8943-ec05a158a2e8.gif)

I'm not sure there's really a solution to it that doesn't have us adding a drop shadow or stroke to every single logo-only icon, and I'm not sure we want that. The thing is, every logo is susceptible to bleeding into the background, if the background happens to be adjacent. Here's a black background, changing to a Facebook blue, to a WordPress blue:

![black](https://user-images.githubusercontent.com/1204802/124433796-6f1bc300-dd73-11eb-9c2f-b3225764a83e.gif)

From what I know about the contrast checking tool, we can't really use it here, as it can't be aware of what the logo color is, nor which background (theme or group or cover) to check against. For that reason, I feel like any solutions we explore they should probably be around the block UI itself; generic ways to surface contrast issues.

Otherwise I'm tempted to suggest this one is the prerogative and responsibility of the user, to ensure contrast, just like how we don't do anything special for black text on a black background:

![text](https://user-images.githubusercontent.com/1204802/124434616-624b9f00-dd74-11eb-98ff-0bf46b3a939e.gif)

**Comment by scruffian** [comment]
Thanks @jasmussen, I agree with your conclusion! Let's close...
