### ISSUE TITLE
Reusable blocks gets deleted when not completely loaded

### ISSUE THREAD

**Issue by tisaneetjardin** [WordPress/gutenberg#33234]
## Description
In the editor, if the reusable blocks are not completely loaded and we save the page/article, the system will ask if we want to save the reusable blocks. To our deepest dismay, we realized that if you click on yes, the reusable blocks get wiped out and there is no way to bring them back, since they have no history.

Wordpress editor should not propose to update the reusable blocks if they are not completely loaded. Or maybe you should at least provide a history for them so that we can always go back to a previous version...

## Step-by-step reproduction instructions
1- Load an article with a couple of reusable blocks
2- Before reusable blocks are completely loaded, click on update the page
3- Accept to update reusable blocks

## Expected behaviour
the blocks that are not completly loaded should not be able to be overwritten

## Actual behaviour
The reusableblock got wiped out

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: I don't know
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme No (using Astra)

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome

**Comment by fwazeter** [comment]
Three of us tried to replicate this during triage, [link to slack conversation here](https://wordpress.slack.com/archives/C02QB2JS7/p1630387400103600). Unfortunately, none of us could replicate.

It does however, appear that there was a fix in WordPress 5.8 to address this kind of issue, here's a link to the [Trac #53072](https://core.trac.wordpress.org/ticket/53072).

It would be great if we could get a specific reusable block example we can use to attempt to duplicate the issue otherwise.

**Comment by devinmaeztri** [comment]
Hi! I'm closing this issue as the author @tisaneetjardin hasn't responded in 2+ weeks. It can be reopened when needed. Thanks!
