### ISSUE TITLE
[List view panel] - Multiselection & Group/Ungroup

### ISSUE THREAD

**Issue by webexpr-dhenriet** [WordPress/gutenberg#33251]
It would be really useful to be able to move blocks with multiselection, drag & drop, and to group/ungroup blocks  from the list view panel.

- Be able to move blocks by drag and drop outside other blocks
- Be able to multiselect and group/ungroup from the list view panel
- Be able to multiselect blocks and move that selection  from the list view panel

![Screenshot_4](https://user-images.githubusercontent.com/62699215/124734209-2e5baf80-df15-11eb-83e6-299b02efbd42.png)

**Comment by mtias** [comment]
Thanks for the feedback! Check out https://github.com/WordPress/gutenberg/issues/29733 which is tracking a lot of these improvements.

**Comment by talldan** [comment]
Thanks for creating the issue @webexpr-dhenriet.

A lot of these suggestions are already tracked in other issues:
- https://github.com/WordPress/gutenberg/issues/29736
- https://github.com/WordPress/gutenberg/issues/29733

I don't think multi-selection or group/ungroup is tracked though, so it might be worth re-writing this issue to focus on that. What do you think?

> Inside the list view panel, on block hover display the class if there is one

This seems like a very niche thing, I'm not sure most users would expect to see a classname. There have been requests to display anchors, which has now been implemented.

**Comment by webexpr-dhenriet** [comment]
@mtias https://github.com/mtias thanks
@talldan https://github.com/talldan I have rewritten the issue only for Multiselection & Group/Ungroup

**Comment by steveangstrom** [comment]
I agree on the importance of List View multi-select.
With the editor separating every paragraph into a block and my clients like to write large tracts its very difficult for them to move a section of text.  
**You will see in the below image -** the client wishes to move the block of paragraphs and two of the headings into the column. 
Currently this is an arduous task, impeded by the anonymity of the P blocks.

**RE; the "hover to view" suggestion**  it might be better if hovering over the element showed the first X characters of the content.  So in the case of a Paragraph block it might show "Lorem Ipsem dol..."    (rather than showing the classname) 

The optimal identifier solution for me would be : to double click / right click  the item in List view, and "rename" it.   In this case I am trying to locate the Paragraph block which is a Poem, and the two surrounding which carry the credits and place these in the column.  As you can see - it's difficult.   I'd prefer to be able to name a paragraph "poem" so I can find it when I move it.

**Accessibility**: Dragging list items with the current system often places them in the wrong order as I have dexterity issues and mouse-drag accuracy is very difficult for me. The drop zone appears to be tiny!  

![multi-select-requirements-in-list-view-sidebar--001](https://user-images.githubusercontent.com/8482649/129229671-c8b7ba06-9ecf-4c29-80c7-e1926a452508.jpg)

**Comment by andrewserong** [comment]
I'll close out this issue now as multiselection was introduced back in https://github.com/WordPress/gutenberg/pull/38314.
