### ISSUE TITLE
Plugin releases - document process for minor releases

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#33277]
## What problem does this address?

A few folks (including @noisysocks) have pointed out that the release docs don't have much info on releasing minor versions of the Gutenberg Plugin. 

## What is your proposed solution?

Document the process in the release docs.

I think perhaps @ockham can give us the basics of the process and then we can use the existing knowledge to flesh out the docs.

**Comment by ockham** [comment]
👋  So basically, the process is no different from stable releases -- i.e. in the "Run workflow" control, you specify `stable`. 

![image](https://user-images.githubusercontent.com/96308/124898424-78a96300-dfdf-11eb-9bb0-e3bb8a4bdb40.png)

The workflow is smart enough to do one of the following:
- If the previous release was an RC (e.g. `x.y.0-rc.1`), release the corresponding stable version (`x.y.0`).
- If the previous version was stable (`x.y.z`), release a point release, with `z` incremented (`x.y.(z+1)`).

**Comment by ockham** [comment]
Furthermore, it's possible to release a point release (`x.y.z`) for a stable version (`x.y.z`) as long as the next stable minor release (`x.(y+1).0`) hasn't been published, by selecting the corresponding branch (`release/x.y`) from the 'Use workflow from' dropdown.

E.g. let's say the latest stable version is `10.8.2`, and we've already published `10.9.0-rc.1`. We can release `10.8.3` by selecting the `release/10.8` branch, and specifying `stable` in the text input field.

(As soon as `10.9.0` is released, this is no longer possible. The reason is that it would require significant changes to how we upload plugin versions to the WP.org plugin SVN repo).

**Comment by noisysocks** [comment]
Neat! So I think let's just copy more or less ☝️ that into the handbook page.

https://developer.wordpress.org/block-editor/contributors/code/release/
