### ISSUE TITLE
Navigation screen: blocks can't be dragged into submenus

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#33272]
## Description

It's not possible to drag a link into a submenu, because submenus close unless their parent or one of their children is in focus, and dragging a link over the submenu parent doesn't cause the submenu to open.

It's also not possible to move links into or out of submenus with the keyboard, as reported in #33271.

## WordPress information
- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: 
- Operating system: 
- Browser:

**Comment by Thelmachido** [comment]
Closing this issue due to the Navigation Screen project being moved to [an inactive status on the feature projects page](https://href.li/?https://make.wordpress.org/core/features/) in coordination with the project leads. 

If this work is picked back up, issues can be revisited and reopened as needed.

Thanks for testing this early feature and giving feedback so the wider WordPress project could benefit from the lessons learned!
