### ISSUE TITLE
Post Excerpt Block: Add the ability to style "Read more" independently

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#33288]
Today, the read more link generally inherits the style settings of the entire excerpt. Since it's a link, you can adjust the  color by using the experimental link color feature, and since it's inline text, you can use options like Bold, Italic, etc. 

The alignment cannot be adjusted independently, and neither can the font size. 

I expected the read more text to be a standard, separate child block that would have its own set of controls. Adopting this implementation would allow for a wider range of design options. (Maybe even the ability to change the link into a button?)

## GIF of current state:

![read-more](https://user-images.githubusercontent.com/1202812/124920327-36732800-dfc5-11eb-9dd6-830fb44f1a63.gif)

**Comment by scruffian** [comment]
In addition to this, it would be useful to be able to add an arrow (like →) to the link...

**Comment by getdave** [comment]
[Related](https://wordpress.org/support/topic/placing-the-read-more-link-outside-the-excerpt-block/#post-14944094) - should we not have a separate block for this?

**Comment by annezazu** [comment]
This came up as part of the [tenth call for testing for the FSE Outreach program](https://make.wordpress.org/test/2021/09/29/fse-program-testing-call-10-pattern-party/#comment-2099) and the solution explored here I believe will address the root issue of the current experience being unclear that you can customize this part of the Post Excerpt block:

> Post Excerpt – there’s a section to ‘add “read more” link text‘ (which I’m not sure what it means?) that if you click on, it doesn’t show the blinking “|” which signifies that you can add text to it (although it does work and you can add text). If you click directly right after it, it’ll then show the blinking “|” and that acts as more of a sign that you can modify and add text. It might be a bit confusing for some users from a visual cue standpoint

Happy to open a separate issue but, to me, this helps provide more context for why it's important to have the ability to style this aspect separately.

**Comment by critterverse** [comment]
Would love to have this functionality! Here's a look at how this might work with a new Read More block that acts as a child to the Post Excerpt block.

Post Excerpt block — before:

<img width="1200" alt="post-excerpt-before" src="https://user-images.githubusercontent.com/77359364/139681891-c08f5316-84fd-4a86-b3e0-d5c0cd951858.png">

Post Excerpt block — after, with new Read More child block:

![read-more](https://user-images.githubusercontent.com/77359364/139705492-86085ac6-e4b3-4bd4-a95e-46527fd5a785.gif)

Here's how it would look from the List view. The parent/child relationship could work similarly to the Buttons/Button block where the child never exists independently of the parent:

![read-more-list-view](https://user-images.githubusercontent.com/77359364/139713678-4c7661db-0a1d-459b-a8a8-1bd19dc81b1d.gif)

Notes:

- Currently, there's an option to include the "Read more" link on the same line as the excerpt text or on a new line. This option doesn't seem to make as much sense with a separate block
- Instead, there could be an option for the Read More block to have a text link or button-style link. These options could be available in the block settings Style panel 
- When a button Style is selected, two additional panels could be added to the sidebar ("Border" and "Width settings") 
- Otherwise, the toolbar and block settings could be the same for the Read More block as the parent Post Excerpt block
- There is an existing “More” block (for use within Content only) so there may be some confusion between this and the Read More block. The existing More block feels like legacy functionality that will probably soon be handled by the [Post Excerpt block settings](https://github.com/WordPress/gutenberg/issues/34757) — I wonder if this block could be hidden entirely for block themes?
- TBD: icon for Read More block

Thoughts?
