### ISSUE TITLE
components: Add baseline validation to NumberControl

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/gutenberg#33291]
## What problem does this address?
It's currently possible to input invalid values into the `NumberControl`: https://github.com/WordPress/gutenberg/pull/33285

To prevent this, you currently have to manage that in the `onChange` you pass. But we should be able to introspect into the `min` and `max` values _at minimum_ to create a generic validation function which prevents invalid values from being entered.

## What is your proposed solution?
Using the `min` and `max` props, verify that the input value is between those numbers, inclusive of both (to match the HTML API).

**Comment by stokesman** [comment]
To pick up from https://github.com/WordPress/gutenberg/pull/33285#issuecomment-877169112:

>https://github.com/WordPress/gutenberg/blob/ad0cc77c85a16a45b33a1d3855a15a0207beb34e/packages/components/src/input-control/input-field.js#L92-L109

>Notice how it calls `handleOnCommit` which in turn "commits" the value, causing the NumberControl's reducer to kick in and do the clamping. But it only does this when `isPressEnterToChange` is true, which is counter intuitive to me. Perhaps that's where the bug is?

I know I've wondered about this very same thing. I suppose that `handleOnCommit` didn't seem necessary when `isPressEnterToChange` is `false`, because the value would have already propagated. It probably wouldn't hurt to always call 'handleOnCommit' from blur events. Yet doing so may not be enough to prevent an issue like #33270 because, as I understand it, that happens as soon as the value propagates. If so, it means the component would have to validate on input and omit propagation for any out-of-range values.

**Comment by michalczaplinski** [comment]
I wonder if we should also make it more explicit that the value that is passed to the `onChange` callback is a string rather than a number?

It's quite easy to forget that you should use `parseInt` to parse the value that is passed to the `onChange` callback because otherwise you might inadvertently change the value from number to string. I've noticed this in a couple places in the Query Loop block:

https://github.com/WordPress/gutenberg/blob/bbaeea2056c96af931170da1665d5d98c79b4b8d/packages/block-library/src/query/edit/query-toolbar.js#L64-L75

https://github.com/WordPress/gutenberg/blob/bbaeea2056c96af931170da1665d5d98c79b4b8d/packages/block-library/src/query/edit/query-toolbar.js#L88-L97

https://github.com/WordPress/gutenberg/blob/bbaeea2056c96af931170da1665d5d98c79b4b8d/packages/block-library/src/query/edit/query-toolbar.js#L115-L120

Loom video to explain in a bit more detail: https://www.loom.com/share/c7cf93b582fa4350b8562242adfa9133

--- 

One suggested solution could be to pass values as **both** string and number to the `onChange` callback. This is what [Chakra UI](https://chakra-ui.com/docs/form/number-input#numberinput-props) is doing for example: 

<img width="500" alt="Screen Shot 2021-09-29 at 12 16 10" src="https://user-images.githubusercontent.com/5417266/135317431-61ecbe29-23cb-4056-86de-dff26ed1a631.png">

**Comment by ciampo** [comment]
Opened a tentative fix for this in #39186

> I wonder if we should also make it more explicit that the value that is passed to the onChange callback is a string rather than a number?

Re. this suggestion, I made a note and I'm going to consider it when I'll resume the work on refactoring `NumberControl` to TypeScript (https://github.com/WordPress/gutenberg/pull/38753)
