### ISSUE TITLE
Prevent plugins from using `core/` namespace

### ISSUE THREAD

**Issue by nylen** [WordPress/gutenberg#333]
How can we prevent plugins from using the `core/` namespace, as in `core/my-block-name`, while still allowing blocks to be registered this way by the editor itself?

**Comment by BE-Webdesign** [comment]
There are a couple ways to do it.  I think allowing it is fine though.  One option is in `registerBlock` to throw an error if `core/` namespace is detected.  Then you could manually assign the core objects to `wp.blocks`.  Another probably better option is to introduce an array of approved core block slugs.  When registering check whether the slug contains `core/` and from there check if it is contained in the approved core blocks array.  Then have the same registering logic that is already in place do its thing.

**Comment by TimothyBJacobs** [comment]
Maybe reopen #336. A registry, if I'm understanding what you meant @BE-Webdesign, would allow for the namespaces to be enforced instead of being bypassable by accessing the global variable directly.

A method could be added like `freezeNamespace( string namespace )`. Which would prevent additional blocks from being added to that namespace. That would protect core, but would help plugin authors to alleviate the same thing. WooCommerce might not want people using the `wc` namespace for instance.

**Comment by BE-Webdesign** [comment]
TimothyBJacobs that could be another application of changes made by #336.  But it is not totally necessary at this point to implement something like that.

**Comment by mtias** [comment]
Going to close this for now as there's no trivial implementation and it's low priority.
