### ISSUE TITLE
Creating a universal "Terms" or "Taxonomy Terms" block to replace the "Categories" block

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#33302]
## What problem does this address?
In Gutenberg we have the Categories block. It is simple and effective at what it does. But what if a user wanted to display Tags or the terms of another taxonomy in a similar way? At present, they would need to build a custom block. 

We also have the Post Terms block that supports variations. Out of the box, the block include variations for both Categories and Tags. But as a developer, you can very easily register a variation for a custom taxonomy. I believe this approach is also needed for the Categories block.

## What is your proposed solution?
I am purposing that a new universal block be built. Something like "Terms" or "Taxonomy Terms" that resembles the current Category block pretty much exactly, but support variations. Out of the box it would include a variation for categories, and then developers could register their own variations as needed. 

I am basically trying to gauge interest in this approach. I am happy to take a stab at building the block. But I don't want to pursue this if the greater community does not feel this is warranted 😉

**Comment by celloexpressions** [comment]
Agreed that there should be a generic post terms block. All terms registered with `show_ui` (or alternatively, `show_in_nav_menus`) should automatically expose a corresponding term list block variation. And presumably `show_in_rest` would also need to be defined as `true`, since that is required for custom taxonomy UI to show up on post types that support the block editor (by the way, I cannot find this stated in the documentation currently).

A generic post terms block and/or automatic term block variants for custom taxonomies will make block templates much more practical to use with custom post types. This is essential and necessary for CPT plugins to adopt the block editor. It allows them to focus on designing block patterns showcasing their functionality, rather than wasting time creating their own blocks to represent terms. 

Users can in turn implement and customize these patterns, allowing unprecedented cross-theme compatibility for custom post types with block based themes. This feature is a critical "building block" in the gradual adoption of block-based themes from a plugin's perspective.

**Comment by Julianoe** [comment]
This would be a great addition. I've had the issue with all my recent complex sites. Not having a universal taxonomy terms is painful for project that use the full versatility of Wordpress. And doing variations like you share [on your blog](https://nickdiego.com/displaying-custom-taxonomies-in-the-full-site-editor/) @ndiego does not work anymore, I can't manage to find how to make a variation of the Categories block anymore :-1:

**Comment by MikeB8s** [comment]
I agree that this would be a great addition.

I am able to make a block variation of the **core/post-terms** block (in version 5.9) for a custom taxonomy, giving it a title, description, icon, and **attributes: ( term: 'myTaxonomy' },** .  This provides similar functionality to the Post Categories block, but I have noticed a couple of quirks.

The title, description, and icon are correctly reflected  in the block selector.  However, once the block is selected,:
1. The Block Toolbar displays a default icon (not the one given for the block variation).
2. The Settings Sidebar Block tab displays the default icon, and displays 'Post Terms' for both the title and description.

**Comment by sophiegyo** [comment]
It'd be really nifty if something like this could be implemented if it could cover taxonomies in general (e.g. tags)! I ended up testing the Jetpack plugin's "portfolio" function and even WooCommerce products in a couple of Query Loops in a few different themes before being sure it was due to the category and tag blocks not accounting for custom post types.

**Comment by skorasaurus** [comment]
I'm working with term meta and terms for the first time in several years (or ever?) and came across this issue while reviewing what capabilities exist in Gutenberg in order to find a **block that would display all terms that exist for a particular taxonomy across an entire website**. 

Even after some research about the current state of such a block; I was a bit confused and found this issue which heavily overlaps with https://github.com/WordPress/gutenberg/issues/49094 (This message is also cross-posted in #49094). 

I include some notes in case anyone else has the same issue or is trying to triage this issue: 

**Categories block** - lists all terms that exist for the taxonomy 'category' across an entire website. 
In the block inserter and list view, the block is called 'Categories List' 
Block markup: `<!-- wp:categories /--> `
Only can select the 'category' taxonomy 

**Post Terms block** - lists the terms that are assigned for a taxonomy (selected in the attribute field) on a particular post or page 
In the block inserter and list view; these blocks are named "Categories" or "tags" 
`<!-- wp:post-terms {"term":"category"} /-->`  or 
`<!-- wp:post-terms {"term":"post_tag"} /--> `

If you register a custom taxonomy, a block variation for the post terms block is registered.
It appears in the block inserter and list view as "Name of your taxonomy(s)"

**Tag cloud** - lists all of the terms that exist for the taxonomy "post_tag" across an entire website. 
in the block inserter and list view, the block is called 'Tag Cloud'; displays it in a cloud like format.  
Only can select the taxonomies 'category' and 'post_tag'
  or  
 
There are a couple existing PRs https://github.com/WordPress/gutenberg/pull/58033 & https://github.com/WordPress/gutenberg/pull/26555 that modifies the categories block to select any taxonomy and displays all of that taxonomy's terms  on the website.

Going forward in the long-term: I think a new flexible block(s) would probably be appropriate as Tom described at https://github.com/WordPress/gutenberg/issues/49094#issue-1625439496

There is a separate block under development - https://github.com/mattyza/terms-list-block but I haven't examined it.

**Comment by ms-studio** [comment]
Just one observation: the "Tag Cloud" block, while defaulting to post_tag, actually supports the selection of other custom taxonomies, via a dropdown menu. 

However, the same is not true for the "Categories list" block. The difference in behavior between those two blocks doesn't seem very logical. If it's possible with default blocks to display taxonomy words as a cloud, why can't we show them as a plain list?
