### ISSUE TITLE
Top toolbar not immediately noticeable 

### ISSUE THREAD

**Issue by msdesign21** [WordPress/gutenberg#3334]
## Issue Overview

I'd like more tests from the community on this to be sure, but based on 2 tests using 1.6 it was very difficult for users to figure out how to adjust alignment, as they did not immediately see the top toolbar. 

The test asked the participant to recreate this page with Gutenberg: https://drive.google.com/file/d/0B4BHP7ZnNw32RWJRa2diODFXVGs/view

Here's the video from test 1: http://cld.wthms.co/bJVmXP
Here's the video from test 2: http://cld.wthms.co/GSYyNl

Both took minutes of clicking around and searching before they could find it. 

## Expected Behavior

- Most times they were trying to search the settings for something that would help them with alignment. Went back to this multiple times clicking on various blocks to see what they got. 
- They also tried searching in the block options for formatting. 
- Once you've inserted an image, as was asked in this test, your eye is already half way down the page making it even more difficult for new users to find. 

## Current Behavior

You'll notice the first time a new user lands on the page their eye will naturally do a scan from the top down, but when you are on the Title, the top formatting bar is blank. 

It's also placed in what I like to call the "WordPress blind zone" (you'll notice the persistent Stripe alert in the video that I can't get to go away) :P - I believe we've trained WP users to ignore this space for years due to the misuse/abuse of alert messages. 

## Possible Solution

I'd want more tests for this to be conclusive, but there's a few options we could also try to test. 
Color, padding on the page in general, appearing when you are on the title but maybe greyed out? Or a color/animation of some sort? A NUX guided tour may seem like the obvious answer, but I don't want that to be a crutch for UX that could maybe be improved. 

Again, would need many more tests. Would love volunteers to help with this, you can use t[he same test](https://drive.google.com/file/d/0B4BHP7ZnNw32RWJRa2diODFXVGs/view) mentioned above. The image can be found [here](http://images.indianexpress.com/2015/06/einstein-759.jpg) or any image can work. 

## Todos
- [ ] Test with at least 5 more new users (any volunteers?) 
- [ ] Documentation

**Comment by wpalchemist** [comment]
I can confirm that this is very confusing.  Yesterday I spent several frustrating minutes trying to figure out how to center some text, and finally found it at the very top of the page.  It is really counter-intuitive to have all of the formatting buttons above the page title - we're all used to the title being at the very top of the page, and everything interactive being below the title.

**Comment by StaggerLeee** [comment]
Maybe it is not point asking people who follow Gutenberg news and discussion to do test ( Github ),
People following all this know where all buttons are, and where they can find what they need.

I personally like it more as it was before, did not find it very distracting. 

Somehow I imagined Gutenberg blocks in distant future as wrappers for everything. Buttons, toolbar, even settings toolbar if third party developer decide this way.
For instance I imagined "shortcode" block to keep everything inside this block, be it select dropdown, modal popup box, all settings and formatting there.

Then if they plan to make Gutenberg full-blooded template editor position of toolbar inside blocks is better than top of the page.

**Comment by CalebWoodbridge** [comment]
+1 on finding this confusing. I just installed the Gutenberg plugin for testing for the first time on the development version of one of my clients' sites, and as I started to play around with the blocks, I spent a while trying to work out where the setting was to change alignment.

I expected I might see it alongside or above the block itself, and then tried looking under the block settings menu. I didn't expect it in the top toolbar, because I thought that would relate to document-level settings rather than block-level settings.

**Comment by hedgefield** [comment]
We did see this come up a few times in our user test, that people hardly used the top bar aside from the publish button. But that could be due to there not being many things up there that you need on a regular basis while writing/editing. You could argue that having these essential block controls up there would help put more attention on it. It's not that different from any other editor, it's more that we're not used to it in a WordPress context. A good tutorialization here would help a lot I think.
