### ISSUE TITLE
Widget Area does not display when Gutenberg is Activated

### ISSUE THREAD

**Issue by linuxstarter** [WordPress/gutenberg#33360]
## Description

When I Activate Gutenberg, the display area of the Widgets does not show anything.

## Step-by-step reproduction instructions

1. Install and Activate Gutenberg
2. Go to Appearance > Widgets

## Expected behaviour

Expect to see my available Widgets

## Actual behaviour

I see a blank screen in the Widgets area. This happens also when I user the Customizer.

## Screenshots or screen recording (optional)

[https://drops.cyberfilebox.com/Kou48Nkg]

## Code snippet (optional)
`Uncaught TypeError: Object(...)(...).getWidgetTypes is not a function`
- this is with 26 plugins activated 

`[12-Jul-2021 05:41:14 UTC] PHP Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'WCFMmp_Frontend' not found in /home/winasweepstakes/www/www/wp-includes/class-wp-hook.php on line 292`

## WordPress information

WordPress 5.7.2
Gutenberg 11.0.0
Are all plugins except Gutenberg deactivated? "Yes" (but, I have some errors below when I didn't deactivate all plugins). Nonetheless, the issue occurs even when I do a clean install of WordPress.
Are you using a default theme: No, but, the issue did occur with a clean install of WordPress as well and the theme was Twenty-One
- also note that this issue does not occur with the same theme I was using (Rehub) and over 40 plugins activated and the same setup.

## Device information
- Device: "Desktop"
- Operating system:  "Windows 10"
- Browser: "Chrome 91.0.4472.124 (Official Build) (64-bit)

**Comment by SeanRWDougall** [comment]
Is this issue being assigned/addressed please? With the Plugin deactivated, my Site displays full width and sidebar disappears. Thank you.

**Comment by getsource** [comment]
Hi @linuxstarter! Thanks for the report, and sorry it's taken a while to reply.

This was talked about in [a triage session](https://wordpress.slack.com/archives/C02QB2JS7/p1631596214433900).

It was noted that a lot has changed with the Widgets screen since this issue was created.

The blank screen is not reproducible for me with an install with no plugins (except for Gutenberg) activated and Twenty Twenty-One, as mentioned in this issue.

As this feature is now in WordPress core (released in 5.8) -- does it work for you there?
If it does, does it still stop working when the plugin is activated?

If it's still causing problems, folks present did a search to see if they could find the plugin referenced in the error message, and it looks like the code referenced is in"WCFM Marketplace". It might be worthwhile to see if that plugin, and any others you use, might have updates for WordPress 5.8 that address this issue.

**Comment by devinmaeztri** [comment]
Hi! I'm closing this issue as the author @linuxstarter hasn't responded in 2+ weeks. It can be reopened when needed. Thanks!
