### ISSUE TITLE
Documentation: using CSS to style the wp-embed

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#33529]
## What problem does this address?

An Auto wp-embed currently looks like this:

![Auto-embed-WordPress](https://user-images.githubusercontent.com/5323259/126069374-bd56ff78-765d-478a-b6e3-c8cbcc3abc2d.jpg)

## What is your proposed solution?

It would be nice to add some documentation on how to style the wp-embed through CSS.
I tried styling the 

p.wp-embed-heading {
    margin: 0 0 15px;
    font-weight: 600;
    font-size: 22px;
    line-height: 1.3;
}

and 

.wp-embed-footer {
 }

with adding a background color but was not able to get it to show the adjustments. Even when I used the !important tag.

@mkaz @ntsekouras

**Comment by mkaz** [comment]
🤔 The embed content does not come from the block editor but from core WordPress. The editor will see an embed, call out to the source to get the markup and then include that markup in the page. The code in WordPress that generates the markup is [here at embed-content.php](https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/theme-compat/embed-content.php).

I'm not sure where we would include this CSS documentation, themes? Also, I'm not sure what level of docs we should include for specifying classnames, it is a common task to use a browser developer tools to discover. In a sense it is self documenting since anyone can inspect and get the classname and create whatever CSS rules the need.

**Comment by mtias** [comment]
This is isn't related to the editor or gutenberg tools. Ways in which WP embeds could be improved could make sense in core. For example, I could see some of the color values inheriting from theme.json in the context of a WordPress site.
