### ISSUE TITLE
Improve visibilty of global styles when you are using it in site editor

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#33539]
Global styles are amazing, but what isn't amazing is not knowing you are in global styles, changing the style and having the entire site change. It's very easy to either stay in global styles or not realise you are, because currently there is not much visual notice of the different states.

![image](https://user-images.githubusercontent.com/253067/126143362-8611b5c9-8589-4e82-ac74-b67b7b6bd46d.png)

Not in global styles:

![image](https://user-images.githubusercontent.com/253067/126143435-cdc5bf68-448f-4a19-ad10-f5f758437d0e.png)

## What is your proposed solution?
I know there are panel iterations being planned so perhaps this falls in those but a few suggestions:

- A more obvious panel state: from a header change to the background color.
- Even better than a panel state would be a top bar state change or more obvious indicator I am in that editing form still when applying things. I might close the panel, do something, save and not remember.

The biggest problem right now is the burden of remembering is on the user and as this is already a mentally taxing experience, it would be great to reduce that burden.

**Comment by richtabor** [comment]
> I know there are panel iterations being planned

Do you know of relevant issues/PRs?

**Comment by karmatosed** [comment]
@richtabor there is https://github.com/WordPress/gutenberg/issues/27473#issuecomment-796773866

**Comment by youknowriad** [comment]
Looks like the design of the sidebar has changed a lot since this issue was opened. We also have a welcome guide to help the user understand things properly.

That said, I think the main confusion point will be fixed with this issue https://github.com/WordPress/gutenberg/issues/66376 when we move the sidebar to a global level in the site editor.

I'm closing this issue now but let me know if you feel otherwise.
