### ISSUE TITLE
Search isn't styled in the site editor menu

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#33538]
Currently the search background defaults to the browser default, which looks out of place in the styling of the menu.

![image](https://user-images.githubusercontent.com/253067/126141958-87d4f935-f0fd-40c7-83f5-7103289f7213.png)

## Step-by-step reproduction instructions
To see this simply go to the site editor, open the menu and click the search icon. I saw this in Firefox, so perhaps it is styled in other browsers but I didn't explore beyond.

## Expected behaviour
If such strong styling is being brought in it should reflect across all interface elements and include their states.

## Actual behaviour
It isn't styled so doesn't fit the rest of the menu.

Noting as a bug, because for me this is a design bug.

**Comment by javierarce** [comment]
I've been trying to find a Figma file with the original design for that field, and I've found some ideas [in this file](https://www.figma.com/file/5guogx5ebxfqJgUQNj5hta/Core-Navigation?node-id=149%3A1007).

<img width="347" alt="Screenshot 2021-07-26 at 17 06 21" src="https://user-images.githubusercontent.com/4933/127012438-bee0cbff-e14d-46ae-90a8-b2f7cfccc9a5.png">

On that page, the input field background changes to white when the user selects it, but since the field is focused right after the search is revealed and the color combination is AAA compliant, I think we could go for a darker version. 

![image](https://user-images.githubusercontent.com/4933/127125535-fcc7c490-9277-4442-b8fd-3ac17912401f.png)

**Comment by javierarce** [comment]
Besides the background color, the style of the search field is different from the one used to search blocks and patterns. So +1 to update its design. 

![image](https://user-images.githubusercontent.com/4933/127020326-77fb9243-0c1d-4754-a500-ede5df048153.png)

**Comment by zaguiini** [comment]
Hi @javierarce,

Is this the final design? Is it ready to be worked on?

**Comment by javierarce** [comment]
Yes, go for it @zaguiini

**Comment by zaguiini** [comment]
#36011 is ready for review. Please take a look, @javierarce!
