### ISSUE TITLE
Editor: straight quotes don't filter to curly quotes on publish as expected

### ISSUE THREAD

**Issue by lancewillett** [WordPress/gutenberg#3353]
## Issue Overview
An amazing feature of the WordPress editing experience is you can enter "dumb" quotes, aka straight quotes or primes — and when the post is filtered for view with `wp_texturize` they automagically turn into curly quotes  for proper typography.

## Steps to Reproduce (for bugs)
1. Make a new post with Gutenberg, I tested with v 1.6.1 and WP trunk (latest Safari on macOS)
2. Publish and view the resulting post in the front-end

## Expected Behavior
I expected ' to turn into ’ and " to turn into ”.

## Current Behavior
Instead, the quotes stayed the same (straight primes).

## Possible Solution
I'm not sure, but it could have to do with Gutenberg post content not being filtered properly through the built-in WP texturize functions.

## Screenshots

Gutenberg editor view
<img width="834" alt="screen shot 2017-11-06 at 09 58 41" src="https://user-images.githubusercontent.com/66797/32453459-7d67154e-c2d9-11e7-87f9-721863d45ba3.png">

After publishing on the front-end
<img width="577" alt="screen shot 2017-11-06 at 09 59 02" src="https://user-images.githubusercontent.com/66797/32453464-7f3eaf76-c2d9-11e7-93a3-ea7fd4dbda13.png">

## Related Issues and/or PRs
Noticed this when debugging punctuation weirdness on https://ma.tt/2017/11/new-backpack-aer-fit-pack/

**Comment by aduth** [comment]
This appears to be another issue of React's default string sanitization for block serialization working against us, since the WordPress texturize step is not expecting these to be represented as entities.

A couple ideas:

- Expand the [entities which `wptexturize` replaces](https://github.com/WordPress/wordpress-develop/blob/c6326694380722ccbdd78e21a2bd0d079383291c/src/wp-includes/formatting.php#L10-L313) to include these values
- Reimplement our own `save` serialization which skips the sanitization

Related issues with serialization:

- https://github.com/WordPress/gutenberg/issues/3806#issuecomment-350740527
- #2463
- #421
- https://github.com/WordPress/gutenberg/pull/2349#issuecomment-321585871
- #3048

**Comment by lancewillett** [comment]
Re-testing after fixes with fd08045

Looks good! Texturize in the front-end output works as expected. Chrome latest on macOS, Gutenberg 2.6.0 and WP 4.9.5.

Editor:
<img width="878" alt="screen shot 2018-04-09 at 09 54 11" src="https://user-images.githubusercontent.com/66797/38511176-223f20cc-3bdc-11e8-956e-132383259f2e.png">

Front-end output:
<img width="866" alt="screen shot 2018-04-09 at 09 54 03" src="https://user-images.githubusercontent.com/66797/38511175-2221e3f4-3bdc-11e8-8984-a3e7c36c4e12.png">
