### ISSUE TITLE
Improve visibility of adding a template in site editor

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#33537]
The site editor has the ability to add template, which is great if you can find it. There is a visibility issue as it is both hidden in the menu information architecture and also behind a '+' which besides the search doesn't read like add a template:

![image](https://user-images.githubusercontent.com/253067/126141491-6a202736-77a3-45ff-8e37-3c436a4270b5.png)

As far as a proposed solution goes, I think being able to add is so important literally using the words 'add template' or 'edit template' just as is done in the other editor makes sense. There is a disconnect that needs levelling between the two editors and each has different usability plus and minus points, merging those together would be great to bring them together.

**Comment by youknowriad** [comment]
The design changes a lot since this issue was opened, we can now add templates in two places, the sidebar and the template list screen with a big blue button. Is this issue considered resolved?

<img width="1062" alt="Screenshot 2023-02-24 at 2 01 01 PM" src="https://user-images.githubusercontent.com/272444/221185045-009e8359-6628-463d-9327-7eb9b4cba5a1.png">

**Comment by annezazu** [comment]
Going to close this out as I agree the design has evolved and there's now a more prominent option in the manage all template flow.
