### ISSUE TITLE
Broken loop in WP_Theme_JSON_Resolver

### ISSUE THREAD

**Issue by schlessera** [WordPress/gutenberg#33552]
The loop in `WP_Theme_JSON_Resolver` to extract translatable paths is broken, as it contains an immediate and unconditional `return`. This causes the loop to immediately exit again after the first iteration, thus never actually looping.

https://github.com/WordPress/gutenberg/blob/f76d127ae9ffdbab74bb0cf1e885566b789aa5c8/lib/class-wp-theme-json-resolver-gutenberg.php#L129-L137

This means that the extraction only works where there's only a single item in the array of translatable strings per section (i.e. the `'name'` field).

The suggested code would be:
```php
	foreach ( $partial_child as $key => $context ) { 
		$result[] = array(
			'path'    => $current_path, 
			'key'     => $key, 
			'context' => $context, 
		);
	);
	return $result;
 }
```

**Comment by swissspidy** [comment]
cc @gziolo @nosolosw

**Comment by gziolo** [comment]
Yes, good catch. It’s an obvious bug from https://github.com/WordPress/gutenberg/pull/28246 that I didn’t catch only because we had only one field used for all translatable paths :sweat_smile:
We need a test that uses a custom schema and requires several fields to be translated, a good example would be in the i18n schema for `block.json`:
https://github.com/WordPress/gutenberg/blob/d361e91268ded0031aab4f346165dd9b5607b205/packages/blocks/src/api/i18n-block.json#L10-L16

At some point, we could also unify the logic that applies translations based on i18n schemas.
I recently proposed https://github.com/WordPress/wordpress-develop/blob/92a8fda178379f7366054f26580ae756da0dcbda/src/wp-includes/blocks.php#L219-L247 that could work for both, but it doesn’t cover the case with `*` that `theme.json` has.

**Comment by gziolo** [comment]
It was also backported to WordPress core: https://github.com/WordPress/wordpress-develop/commit/3f83b507435ec0c110ee89aadfa623af80275639.
