### ISSUE TITLE
Short blocks have very small hover area.

### ISSUE THREAD

**Issue by markjaquith** [WordPress/gutenberg#3355]
Single-line paragraphs (and probably other short blocks) have a **very** small hover area. For a paragraph, it is literally limited to the line-height of the text. The padding around the item doesn't count. This makes working with one-line paragraphs rather frustrating.

![twitchy-single-line-paragraph](https://user-images.githubusercontent.com/353790/32459323-3ea94b50-c2fd-11e7-8c89-301726e00e76.gif)

**Comment by aduth** [comment]
Part of the issue here is that the "Between Inserter" creates a padded buffer zone when it activates, and for short paragraphs it is easy to accidentally move between buffer zones of the before and after inserters when trying to access the text itself.

See Implementation Notes of #3008 for demonstration.

It could be that this buffer zone needs to be adjusted, either globally or based on block height; the latter may resolve these specific cases, but also introduces an inconsistent experience.

**Comment by youknowriad** [comment]
> It could be that this buffer zone needs to be adjusted, either globally or based on block height; the latter may resolve these specific cases, but also introduces an inconsistent experience

I wonder if there's a way to do this:

 - Keep the buffer as is
 - Hovering the buffer shows the inserter
 - Clicking the buffer, clicks on the block

**Comment by aduth** [comment]
I could see that working well, but would be a challenge to implement. The obvious solution would be to apply `pointer-events: none;` to the buffer area (to allow the natural cursor, e.g. text to take effect), but of course this means that the mouse events would not fire consistently (to hide).
