### ISSUE TITLE
Remove bottom margin from image block

### ISSUE THREAD

**Issue by TheRadicalDreamer** [WordPress/gutenberg#33564]
## What problem does this address?

When adding an image block if i don't set any reference text on the bottom of the image, it should not create a bottom margin.

So in this way i can stack images without to use CSS to remove that margin.

## What is your proposed solution?

It will be better that if images does not have a reference text, it should not create a margin on the block.

The figure tag has this maring as you can see.
![image](https://user-images.githubusercontent.com/11801254/126251650-199064ca-d631-470e-bf88-5ac305484e6c.png)

**Comment by getdave** [comment]
Hi @avagp. I tried this out and I can see the issue but I think this is a difficult one to solve in a way that meets everyone's needs.

To me if you're adding a succession of images it might be best to use the Gallery block. Now the issue with that is that the Gallery block also applies margin by default - even in single column mode.

I know there's currently [a major refactor of the Gallery block underway so perhaps you could comment on the PR](https://github.com/WordPress/gutenberg/pull/25940) and ask for the feature set to include the ability to disable spacing between images? @glendaviesnz is working on that one and so he might have some insight.


That way you could add your individual image blocks, select them and then convert to Gallery via the transform menu.

Other than I'm not sure it is possible to write a CSS selector that will target Image blocks that are next to other Image blocks. You can target the next sibling but that still leaves a space on the original Image block. We also cannot add a blanket rule to remove the margin from all Image blocks because in general writing flow having a default bottom margin is actually pretty useful.

If you have an idea for how this could be solved then we could look into exploring this.

**Comment by ntsekouras** [comment]
This could probably be more fine tuned with a theme that supports `spacing.customMargin` and enable the support flag in `Image` as well...

--cc @nosolosw

**Comment by TheRadicalDreamer** [comment]
Totally/

What i am doing is that i use container blocks from the Stackable plugin to
control that margin on every block.
[image: image.png]

I believe that this little addition can help you a lot with custom layouts.

I almost only use gutenberg blocks, but this margin is driving me nuts :/

**Comment by EdithAllison** [comment]
I second the need to remove the bottom margin. If Gutenberg adds in a margin, I'd like to see the layout panel enabled so I can over-ride it. The wider issue I see here is that Gutenberg IMO should not make design decisions for me, but give me the tools to make my own. Presets / defaults are great for "just add it" use case; but the option to over-ride should be there.

**Comment by jordesign** [comment]
Closing this as control over margins for images (and gaps between blocks) can now be handled with Global Styles.
