### ISSUE TITLE
Gallery block: Empty caption element smaller on iOS than Android

### ISSUE THREAD

**Issue by fluiddot** [WordPress/gutenberg#33600]
## Description

I noticed that on iOS the caption element when is empty it's smaller compared to the Android version (see attached screenshots), making the caption selection more difficult to users.

## Step-by-step reproduction instructions

1. Add a Gallery block
2. Add some images to the gallery
3. Tap on one image
4. Observe that the caption element is hard to tap

## Expected behaviour

The caption element should be easy to tap on both platforms.

## Actual behaviour

The caption element is harder to tap on iOS than on Android.

## Screenshots or screen recording (optional)

iOS|Android
--|--
<img src=https://user-images.githubusercontent.com/14905380/126505971-7211b5cb-0612-4f8c-92cb-9103683ca3e7.jpeg>|<img src=https://user-images.githubusercontent.com/14905380/126506155-f2715fdc-28a3-4c73-aac5-56630fae656c.jpg width=828>

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: iPhone 11
- Operating system: iOS 14.2
- WordPress app version: `develop`

**Comment by mchowning** [comment]
:wave: @mkevins ! Do you have any thoughts on this issue?

**Comment by mkevins** [comment]
>  @mkevins ! Do you have any thoughts on this issue?

Hi @mchowning :wave: :smile:

I have a feeling this may have to do with the line height of the underlying native component, but I also remember that there were some tricky situations for handling the semi-transparent overlay and the border of the selected image. I believe there could be a platform variation resulting from the way these issues were overcome.

Since the refactored gallery format work has landed (with nested image blocks), and this current format will eventually be deprecated, I agree with the low priority on this one. The new format does not have a transparent overlay for the image captions, as they are displayed below the image in the same way they are for the image block.

**Comment by geriux** [comment]
Closing this issue since the new format of the Gallery is available (which uses Inner blocks) and older formats are migrated to the new one.
