### ISSUE TITLE
What happened to FontSizePicker?

### ISSUE THREAD

**Issue by NasKadir123** [WordPress/gutenberg#33636]
## Description
After update to WordPress 5.8 version FontSizePicker doesn't take number as type of value. Can you provide correct change log about it? Right now the value described as number | string which is not true. Or am I missing something?

## Step-by-step reproduction instructions
Create any custom block with attribute fontSize as a 'number' and check how FontSizePicker works.

## Actual behaviour
The problem has appeared because of new options of new values for font size such as em and rem. I think it's so incompetent to change FontSizePicker with any additional option to remove this font size units. So right now the number value is incorrect and it kills everything that was created before.

## WordPress information
- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: 
- Operating system: 
- Browser:

**Comment by getdave** [comment]
Can I confirm you are referring to `<FontSizePicker>` from `@wordpress/components`? If so then it doesn't appear to take an attribute called `fontSize`. There is an prop called `value` which accepts a unitless value such as `16` as well as a value with units such as `16px`.

You can see from the code how this is handled:

https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/font-size-picker/index.js

If that doesn't solve your query please could you provide a code example of your specific use case along with a set of steps to replicate the issue. We can then investigate further.

> So right now the number value is incorrect and it kills everything that was created before.

I'm particularly concerned about this so I'd like to verify this issue one way or another.

> I think it's so incompetent to change FontSizePicker with any additional option to remove this font size units

I understand your frustration but let's remember that folks work really hard on these items. Let's work constructively to fix them.

I appreciate your help and cooperation. Look forward to hearing back.

**Comment by NasKadir123** [comment]
@getdave Sorry for my roughness, I didn't want to insult anyone.
Let me try to show you an example where I'm using withFontSizes and getFontSizeClass HOCs https://github.com/NasKadir123/textBlock.
This block is working in previous versions, but not in the new one. When you change Font Size in FontSizePicker for example to "large" it works, but if you insert number inside Custom input, for example "24" it will throw the error. It has the same effect even if you don't want to use HOCs and will just have a value attribute with type number.
I will be glad to provide more information just let me know if you interested.
Thanks in advance!

**Comment by getdave** [comment]
@NasKadir123 Thanks for coming back here with more information.

I installed your block on my test site and the `FontSizePicker` is working correctly with no console errors.


https://user-images.githubusercontent.com/444434/126780044-f86c51fb-494e-4f48-86df-498a15128d82.mov

Bear in mind this test site is a fresh install of WordPress 5.8 with the latest Gutenberg Plugin installed. 

If you continue to experience an error I would recommend trying out your Plugin on a fresh install to see if it happens there. If not then I'd recommend trying to debug why it happens on your current site - probably by deactivating all Plugins and making sure everything is up to date.

As I'm not 99% sure there is no issue with the FontSizePicker I'm going to close this one out but if you can verify this bug is happening on a clean install then please feel free to reopen with the additional information.

Many thanks.

**Comment by NasKadir123** [comment]
@getdave OMG, I forgot to say that after changes of custom font size Update (in your case Publish) the page and refresh it.
