### ISSUE TITLE
Block manager hides blocks

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#33670]
## Description
In the block manager I can see there are hidden blocks but I can see no way of unhiding them.

## Step-by-step reproduction instructions
1. On WordPress 5.8
2. Install the Lalita theme (not sure if this causes anything)
3. Edit a post
4. Go to the top right corner and click the dotted menu
5. From that menu choose block manager
6. Observe if bug is present: all blocks are enabled but block manager reports some hidden blocks

## Expected behaviour
If blocks are hidden I should be able to unhide them.

## Actual behaviour
Some blocks are reported hidden but can't be found.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/107534/126861472-4749619d-f73a-46b8-ac9c-6d47e9c6bd9f.mp4

## WordPress information
- WordPress version: 5.8
- Gutenberg version: -
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? No

**Comment by Mamaduka** [comment]
I'm not able to reproduce the issue on clean installation. I tested with Lalita and TT1 themes.

Do you have any other blocks plugins active on installation?

**Comment by talldan** [comment]
To reproduce:
1. Add a plugin that has a block collection
2. Uncheck the visibility for the blocks from the plugin
3. Disable/uninstall the plugin

The problem is that the hidden block names are persisted in local storage, but not displayed in the list or removed from the hidden count once the plugin is no longer active.

**Comment by ryelle** [comment]
I hit this problem today (which complicated this issue https://github.com/WordPress/gutenberg/issues/38500), I had two hidden blocks that I couldn't unhide, because I had removed the source plugin.

I don't know if there's any reason to persist the list when a plugin is inactive, it could be useful to hide specific blocks that a user (or client) might install (though maybe a "disallowed list" filter would be better for this kind of thing, it's come up before: #33954 #38472). So perhaps the `hiddenBlockTypes` list should check against currently-active blocks?
