### ISSUE TITLE
Site Editor, Components, and Iframes - Style issues with components using emotion and Iframes.

### ISSUE THREAD

**Issue by Addison-Stavlo** [WordPress/gutenberg#33735]
## Description

In the Site Editor, certain components (such as Modals and Popovers) when applied from the editor canvas frame render without including necessary styles for other child components.

The few component's that have stuck out as having missing styles in this circumstance (the 'Disabled' component and the various 'Flex' components) all seem to use emotion / css-in-JS as their style delivery mechanism.

### Example 1
One example is in the Selection dropdown for the Template Part block.  When it is rendered from the Template Part Block's placeholder in the editor canvas frame, the preview (that is wrapped in a `<Disabled>` component) is not disabled as expected and is interactable with the mouse:

<img src="https://user-images.githubusercontent.com/28742426/127380623-ca0f26d4-6cb8-4caf-b72a-067d0b305483.png" width="300px" />

![Screen Shot 2021-07-28 at 2 33 01 PM](https://user-images.githubusercontent.com/28742426/127380628-9b18c97d-1d89-44b0-b4fb-1d1701e40d0b.png)

Notice how the cursor is able to interact with blocks in the preview.

However, when this dropdown component is accessed through the "Replace" button in the block toolbar the `<Disabled>` components disabling styles work as expected:

<img src="https://user-images.githubusercontent.com/28742426/127380872-2557df61-0803-4176-80e5-3b80da8be204.png" width="300px" />

Note - As an aside from the issue with the disabled component, in both versions the previews are unable to inherit the site's background color.  In the post editor everything works as expected, this preview is disabled from interaction and inherit the editors background colors:

<img src="https://user-images.githubusercontent.com/28742426/127381289-3a1600e0-0907-4889-9f6c-c1f6a1793d9c.png" width="300px" />

### Example 2

For example, take a Modal that contains a pair of buttons nested in flex components similar to:
```
<Modal>
    <Flex justify="flex-end">
        <FlexItem>
            <Button> Cancel </Button>
        </FlexItem>
        <FlexItem>
            <Button> Create </Button>
        </FlexItem>
    </Flex>
</Modal>
```
Also, consider that this modal is triggered by a block on the canvas (ex- the Template Part's placeholder flow for creation [explored here](https://github.com/WordPress/gutenberg/pull/33703)).

We would expect these Flex components and styles to render the buttons as flex items at the end of a flex group.  In the post editor, this appears as expected:

![Screen Shot 2021-07-28 at 2 31 47 PM](https://user-images.githubusercontent.com/28742426/127382487-f6e8d68e-d245-4345-ac06-1e9390dcfde0.png)

However, when this is rendered in the Site Editor the Flex components do not have their associated styles:

![Screen Shot 2021-07-28 at 2 31 04 PM](https://user-images.githubusercontent.com/28742426/127382868-fe3d0e7e-663d-4f79-9e87-56e8bb95f265.png)

Consider for a second if we replaced the parent `<Modal>` with a `<Placeholder>` component, the Flex components do receive their expected style:

<img src="https://user-images.githubusercontent.com/28742426/127383601-512d9871-0e6b-40c1-bfcc-d7ad1f0ef952.png" width="300px" />

So it seems like this happens when emotion styled components are rendered in other components that are outside the parent frame. 🤔  

Similar to example 1, if this Modal is based outside of the editing canvas and rendered from the editor itself (such as the similar 'Convert to template part' modal that is found through the block toolbar's ellipsis menu), these styles are included as expected:

<img src="https://user-images.githubusercontent.com/28742426/127384154-1d1a137f-f31b-480d-93fb-d64bea4f52b5.png" width="300px" />

**Comment by jasmussen** [comment]
Worth crosslinking this with #30503, which mentions a `StyleFrame` component to address this issue.

**Comment by ryelle** [comment]
I'm running into this trying to create a modal component for the Pattern Directory editor.

I've made [a demo plugin](https://gist.github.com/ryelle/247871127e6744f8e16caac0b0c01706) to reproduce the issue. It seems like the emotion styles in the modal content are not being picked up. The components are given a unique prefix ID (cache key), but no styles are registered to that UUID key. It must have something to do with the iframe use, though, because the "Modal test" block in my demo plugin works fine on the post editor, but breaks on the site editor.

I used the `Grid` and `Spinner` components to test.

| Post Editor | Site Editor |
|------------|-----------|
<img width="971" alt="edit-post" src="https://user-images.githubusercontent.com/541093/140411035-e9c28bdc-c163-4e60-9411-a470f1897a20.png"> | <img width="390" alt="edit-site" src="https://user-images.githubusercontent.com/541093/140411045-c4ec2ac4-5b22-4dfa-be14-90f37abfe887.png"> |

Unfortunately, I'm out of my depth on how these emotion styles are generated - how does emotion know which component styles to load, and why might it skip modal content but only on an iframed editor?
