### ISSUE TITLE
Unable to set margin on headers using theme.json

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#33795]
I seem to be able to set padding but setting the margin has no effect on header blocks. This is interesting to me as I would have thought I could do both. It doesn't seem to be something lurking in the theme I am using as that's super minimal, however, I would be curious to know if others have experienced this?

**Comment by tellthemachines** [comment]
Hi @karmatosed , by "header" do you mean a Header template part, or a Heading block? If the latter, I believe this is a bug, as the styles from theme.json have very low specificity (just an `h2` in the front end, and an `.editor-styles-wrapper h2` in the editor) and they are being overridden by more specific layout styles, e.g. `body .is-layout-constrained > *`.

I'm going to go ahead and mark this as a bug, because we definitely should be able to set margins for Heading blocks in theme.json 😅

**Comment by tellthemachines** [comment]
Closing since #47858 has now been merged.
