### ISSUE TITLE
.wp-site-blocks template HTML wrapper should be filterable

### ISSUE THREAD

**Issue by jeremyfelt** [WordPress/gutenberg#33798]
## What problem does this address?

`get_the_block_template_html()` in WordPress and `gutenberg_get_the_template_html()` in Gutenberg build the template HTML for the current page view and then wrap it in `<div class="wp-site-blocks">` immediately before returning. This is a decision made in the original implementation, #17626.

## What is your proposed solution?

It should be possible for a theme and the user to have as much control over the markup as possible. This wrapper may work as a default for many themes, but is not strictly necessary.

I would propose adding a filter here, maybe like so:

```
$original_content = $content;
$content = '<div class="wp-site-blocks">' . $content . '</div>';
$content = apply_filters( 'gutenberg_get_the_template_html', $content, $original_content );
```

It could also be more complex and filter both whether the content should be wrapped and then what the wrapping class is.

This would have an impact on how the [automatic skip-link JS](https://github.com/WordPress/gutenberg/blob/79cfaf9e5aff7b1ad0924ec61d6dc8a99cff665d/lib/full-site-editing/templates.php#L256-L258) is generated, though that can easily be replaced by a theme via the `wp_footer` action.

**Comment by ngdangtu-vn** [comment]
Thanks, I really need this fix. Do you know why we still don't it? Is there anything I can do?

**Comment by carolinan** [comment]
`wp-site-blocks` is used for the output of alignments, margin, block gap, and the root padding from theme.json.

**Comment by fabiankaegy** [comment]
I'm currently into an issue which would also require the ability to filter the markup of templates before they are rendered. 

I have a custom rich text format which stores some data as data-attributes. This rich text format should pull in dynamic data and for regular posts and pages we can accomplish this using the `HTML_Tag_Processor` and a filter on `the_content` filter. However this doesn't work for the templates. 

(My case it kind of related to this issue here: https://github.com/WordPress/gutenberg/issues/18490 )

**Comment by jeremyfelt** [comment]
I think this ship probably sailed 2 years ago. 😅

FWIW, I'd be okay closing this request.
