### ISSUE TITLE
Info/Information Notice Styling is absent

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#33853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried deactivating all plugins except Gutenberg?

- [X] I have tested with all plugins deactivated.

### Have you tried replicating the bug using a default theme e.g. Twenty Twenty?

- [X] I have tested with a default theme.

### Description

Per the Notice component documentation in the Block Editor developer's handbook (https://developer.wordpress.org/block-editor/reference-guides/components/notice/), 'info' should be a supported notice type alongside 'warning', 'error', and 'success'.

It should have a light blue background, but there doesn't appear to actually be any styling for this.

'error', 'success', 'warning' all work as expected and result in the appropriately colored notices. Using 'info' just gives you a white background.

Analyzing load-styles.php shows that the following all style rules that set background colors:
.components-notice.is-error
.components-notice.is-warning
.components-notice.is-success

but there is no rule for 
.components-notice.is-info

### Step-by-step reproduction instructions

Generate a notice of type 'info'

### Expected Behavior

A notice appears with a light blue background

### Current Behavior

A notice appears with a white background

### Code snippet (optional)

 wp.data.dispatch( 'core/notices' ).createNotice(
        'info', // Can be one of: success, info, warning, error. 
        'This is a sample info notice.', // Text string to display.
        {
            isDismissible: true, // Whether the user can dismiss the notice
        }
    );

### WordPress Information

5.8

### Gutenberg Information

not installed

### What browsers are you seeing the problem on?

Chrome

### Device Information

Desktop

### Operating System Information

Windows 10

**Comment by talldan** [comment]
Well spotted. Looks like it was something that was never added. This is the PR that added the original styles - https://github.com/WordPress/gutenberg/pull/8856

Here's a screenshot of an info notice. It looks ok, the blue border on the left is from the admin theme color. Maybe info notices should always be a blue instead of being admin theme dependent:
<img width="623" alt="Screenshot 2021-08-04 at 2 10 40 pm" src="https://user-images.githubusercontent.com/677833/128130781-890079f4-b651-4c42-bcf2-545d67caadd5.png">

The docs have this:
<img width="598" alt="Screenshot 2021-08-04 at 2 11 37 pm" src="https://user-images.githubusercontent.com/677833/128130832-7cb5e0b1-2639-450b-b621-b9cb8064a086.png">

**Comment by MadtownLems** [comment]
My suggestion is to get the code sync'd up with the documents. I think there's a lot of merit to an Informational notice (we're obviously trying to use one), and the white background notice is incredibly easy to gloss over without realizing it's there at all.

**Comment by jordesign** [comment]
Closing this issue as it will be addressed in https://github.com/WordPress/gutenberg/issues/34901
