### ISSUE TITLE
Moving the cursor before deleting text within the Image Alt Text fields results in incorrect cursor placement on Android

### ISSUE THREAD

**Issue by dcalhoun** [WordPress/gutenberg#33857]
## Description
When deleting characters _after moving the cursor_ within the Image Alt Text field, the cursor is placed in the incorrect location. Rather than cursor placed after the first preceding character, it is placed after the second preceding character. This appears to only occur on Android, and does not occur on iOS. 

## Step-by-step reproduction instructions
1. Launch the editor.
2. Insert and Image block.
3. Tap the settings cog button to open the block settings.
4. Tap the Alt Text field.
5. Enter text into the field. 
6. Move the cursor to a different location in the text. 
7. Press the delete/backspace key. 

## Expected behaviour
The character before the cursor is removed. The cursor is placed after the character one place before the deleted character. 

## Actual behaviour
The character before the cursor is removed. The cursor is placed after the character two places before the deleted character. 

## Screenshots or screen recording (optional)
https://user-images.githubusercontent.com/438664/128053613-8667814c-a547-4d02-a614-4be57c60dfe9.mp4

## WordPress information
- WordPress version: WordPress.com
- Gutenberg version: 11.10
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Samsung Galaxy S20
- Operating system: Android 11
- WordPress app version: 17.7 (GB Mobile 1.56.0)

**Comment by hypest** [comment]
👋 @dcalhoun, can you also try to check when has this perhaps begun to happen? That will help assess it's importance, thanks!

**Comment by dcalhoun** [comment]
@hypest WPAndroid 17.7 (GB Mobile 1.56.0) is the oldest version I am able to reproduce this issue. I have updated the issue description with this information.

**Comment by SiobhyB** [comment]
I found an open issue in the React Native repository, https://github.com/facebook/react-native/issues/30503, that lines up with the behaviour described here:

> If using a Samsung keyboard many of the characters typed will be duplicated. Try moving the cursor to the middle of the sentence typed and try deleting some characters ans you will notice the cursor jumping back and deleting more than one character at a time. This last issue is also seen when using Google keyboard.

That issue was introduced in React Native 0.63.0. As GB Mobile 1.56.0 included the upgrade to React Native 0.64.0, it'd make sense that it was that version where this issue began presenting itself. 

I'm currently working on resolving a different (but relevant) error (described at https://github.com/WordPress/gutenberg/pull/33057#pullrequestreview-725305368) that I believe will also resolve this issue (and [possibly this one](https://github.com/WordPress/gutenberg/issues/33856)). I'll therefore assigned myself to both for now. :)

**Comment by SiobhyB** [comment]
Closing, as this was fixed in wordpress-mobile/gutenberg-mobile#3818.
