### ISSUE TITLE
Block Styles: Show style preview when hovered or focused

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/gutenberg#33933]
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/191598/128535732-ff1c5e90-a806-45f2-9e64-358445b9a579.png">

Block Styles appear in both the block's toolbar and in the editor's sidebar. Currently, styles are shown with both a rendered preview and a name. The previews are a little too small to be helpful, but also add to the overall height of the sidebar accordion. Here's how it look when a plugin adds just a few styles to the Button block:

<img width="281" alt="image" src="https://user-images.githubusercontent.com/191598/128535937-417cba5c-a2bc-4626-bdc6-148be4569c86.png">

The overall height of the accordion in the screenshot above is about 570px. It ends up pushing down more important controls like Typography and Color.

Lets move the previews so they only appear when the style is hovered or has keyboard focus. This reduces the overall footprint, and also puts more emphasis on the style's name.

![Style Previews on Hover](https://user-images.githubusercontent.com/191598/128536449-60406a8b-d36f-4fce-8d51-596bccba9477.gif)

**Comment by fwazeter** [comment]
I like the way this feels - it appears more functional while also feeling a bit more modern when handling the preview.

**Comment by richtabor** [comment]
I agree. This makes styles still be featured - but take up a lot less space in the sidebar.

**Comment by ramonjd** [comment]
I tried this out using a Popover. I had to rely on a [Popover SlotFill at the outer, Post Editor level](https://github.com/WordPress/gutenberg/blob/release/11.4/packages/edit-post/src/components/layout/index.js#L281) since the sidebar hides any overflow.

![Screen Capture on 2021-09-01 at 11-08-21](https://user-images.githubusercontent.com/6458278/131595881-1005c6d0-fed4-46a3-801d-e533e10a2df3.gif)

On mouseover, rendering the preview is not entirely reliable as you can see from the screen capture above.

Often there's not enough time for the preview container to calculate the correct height, something it does on the fly. My guess the Popover animation and the bevy of nested iframes don't help much.

Still, this happens _sometimes_ in the block inserter previews as well.

Also, for mobile (and if the popovers prove too unruly/inaccessible) I thought maybe we could reduce the preview to the currently selected (no previews)

![styes-mobile-batman](https://user-images.githubusercontent.com/6458278/131598558-4a7a11a8-8347-4663-9820-ea236bb126dc.jpg)

Also were there any preferences for the Default Style dropdown? 

Thanks!

**Comment by mtias** [comment]
One thing that stands out in terms of componetry — because this is a design pattern we don't have anywhere else — is that it looks fairly aligned with the new proposal for font pair selection in global styles:

![image](https://user-images.githubusercontent.com/548849/132498795-eebbccd5-273a-4095-9457-d314f60f85b1.png)

It might be good to be explicit about aligning there in terms of component semantics.

**Comment by mtias** [comment]
@shaunandrews have you thought about the "default style" dropdown and how it'd fit? It's even more pronounced now with the smaller footprint of the style selectors and seems off. Might make sense to think of a panel ellipsis menu to handle reset and setting a new default instead, like "set current option as default".

**Comment by apeatling** [comment]
Worked on in https://github.com/WordPress/gutenberg/pull/34522

**Comment by shaunandrews** [comment]
Using the more menu could help with resetting and changing the default style:

<img width="599" alt="image" src="https://user-images.githubusercontent.com/191598/140092375-6ef67ef7-ff45-4a95-be32-0e2334381848.png">
