### ISSUE TITLE
Add all pages option doesn't work in Navigation screen

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#33999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried deactivating all plugins except Gutenberg?

- [X] I have tested with all plugins deactivated.

### Have you tried replicating the bug using a default theme e.g. Twenty Twenty?

- [X] I have tested with a default theme.

### Description

Can't create menu using "add all pages" option.

### Step-by-step reproduction instructions

1. Navigation screen, create new menu
2. choose "add all pages"
3. set a location for the menu
4. save
5. go to front end and verify menu doesn't display

### Expected Behavior

Expected menu to show on front end.

### Current Behavior

Menu doesn't show on front end.

**Comment by talldan** [comment]
So basically the Page List block isn't supposed to be supported by default (unless the theme opts in to supporting more block types), since it's not backwards compatible with how classic menu items work. It already can't be added via an appender.

I think this issue is a bit bigger than just the nav screen too. In other editors it's possible for the Page List block to be unregistered, but because this feature is hard coded into the nav block's placeholder, Page Lists can still be added.
