### ISSUE TITLE
High specificity breaks two column layout between mobile and large viewports

### ISSUE THREAD

**Issue by scheinercc** [WordPress/gutenberg#33996]
https://github.com/WordPress/gutenberg/blob/1eaad3cbad327e9fad5d8eef93c46aa773b7080b/packages/block-library/src/columns/style.scss#L46

Here I set the width of the image container on the left to `100px`
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/817856/128979942-1e34f6e2-c6de-4545-b647-3acc0dfe1a47.png">

Once I hit the above linked break point the `100px` gets overwritten by `50% - 1em` which does not work at all:
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/817856/128980124-2687de68-e77e-4e9f-87ce-d2677ed91bc9.png">

I get why `!important` is used here, but it makes it impossible to counter this in a sustainable way.

**Comment by stacimc** [comment]
Thanks for reporting this, @scheinercc. To give you some context, this behavior at mid-range viewports is currently necessary in order to [avoid issues with column wrapping](https://github.com/WordPress/gutenberg/pull/20597#issuecomment-595974441) -- but adding the ability to customize column widths at different viewports is being very actively discussed.

You can check out this existing issue: #13363, where column behavior in particular is discussed. There's also #19909 along the same lines.

I'm going to close this issue as a duplicate, as it appears the linked issues cover this specific well.
