### ISSUE TITLE
Improve block inserter

### ISSUE THREAD

**Issue by brickbones** [WordPress/gutenberg#34]
If more options are available, changing the width of the _**.insert-block__menu**_ feels like a better experience.

![wp-c](https://cloud.githubusercontent.com/assets/8192076/22792550/26600d20-eebb-11e6-8eb7-478208bee6b5.gif)

**Comment by jasmussen** [comment]
Interesting idea, thanks for sharing a mockup also 🌟 

The design is definitely in need of further love. The most recent mockup looks like this:

![insert](https://cloud.githubusercontent.com/assets/1204802/22820175/f2bcc574-ef75-11e6-8f18-9dce621d841f.png)

Maybe it does need to be bigger, I know @melchoyce has some thoughts on this as well. Probably prudent to keep in mind though: there are _many_ (once all is said and done it's likely there will be 50+ outside of plugins alone), so we can't possibly show them all (which is why there are emoji-like tabs in that mockup). The balance we need to find is between showing a big friendly insert dialog that's keyboard accessible (type `/` on a new line to invoke it, then type to search or use arrow keys + enter to insert), and not overwhelming people with choice.

**Comment by brickbones** [comment]
Here is my idea a little bit more elaborated. I will include the emoji-like tabs and darker icons.

![c-3](https://cloud.githubusercontent.com/assets/8192076/22826653/7fcf348e-ef61-11e6-8c3d-c865f961f074.gif)

**Comment by karmatosed** [comment]
I really like the idea this takes up more space. I feel the current implementation is a little small. I understand wanting it to be minimal and I'm not totally sold on it being full width either. I think exploring different sizes would be great. We probably also increase accessibility for users as we make larger.

**Comment by jasmussen** [comment]
This inserter will likely undergo iterations as well, hence this ticket is valuable. I know that both @melchoyce and @folletto have thoughts on how to improve this.

**Comment by brickbones** [comment]
Playing with different positions and sizes.
![option-1](https://cloud.githubusercontent.com/assets/8192076/23143884/eab579ec-f791-11e6-8ff4-dedc428da0af.jpg)
![option-2](https://cloud.githubusercontent.com/assets/8192076/23143887/eabee158-f791-11e6-8709-96442b1b0cf7.jpg)
![option-3](https://cloud.githubusercontent.com/assets/8192076/23143885/eab940ae-f791-11e6-8221-fd3b9d2c890c.jpg)
![option-4](https://cloud.githubusercontent.com/assets/8192076/23143886/eabb5f06-f791-11e6-8cc9-021c0e9b0d09.jpg)

**Comment by folletto** [comment]
> This inserter will likely undergo iterations as well, hence this ticket is valuable. I know that both melchoyce and folletto have thoughts on how to improve this.

I've a couple of hypothesis, but more in general I'd try to explore a set like:

1. Plus on the page: plus at the end (as is in the current prototype)
2. Plus on the page: plus on the side, always present regardless of which line one is on
3. Plus on the page: plus appearing on a blank line
4. Plus in a fixed part of the screen: top bar
5. Plus in a fixed part of the screen: inspector / sidebar
6. Plus in a fixed part of the screen: floating palette in a fixed position (the page scrolls but the palette doesn't).

I lean more toward 4-5-6 because:

* Would unclutter the page, moving it further away from text and giving more focus.
* An insertion point is already present: the cursor. Solving the problem of "how to add in the middle".
* Would open the possibility of options that don't cover text on wider screens.

**Comment by jasmussen** [comment]
Took the liberty of renaming the ticket to be the canonical "inserter improvements" ticket.

**Comment by jasmussen** [comment]
Please see also #323, as that will be the task ticket for the inserter.
