### ISSUE TITLE
Replace Post Formats with Proper Schema Markup

### ISSUE THREAD

**Issue by deborah86** [WordPress/gutenberg#34080]
## What problem does this address?

It is frustrating to not be able to add proper schema types to pages and posts. Schema is beneficial for SEO. 

Gutenberg has the Post Format types but these do not integrate with schema types. These are also only available on posts and not pages. As WordPress moves closer to FSE, this feature will become more obsolete.

## What is your proposed solution?

The solution is to add schema options in the Page Settings of the block editor by replacing Post Format types with proper schema markup. This will allow users to select the proper schema type and settings for the page or post.

Resources to consider:

- [Organization of Schemas](https://schema.org/docs/schemas.html)
- [Post Formats](https://wordpress.org/support/article/post-formats/)

**Comment by swissspidy** [comment]
Since post formats is a WordPress core feature and you essentially suggest adding full-blown schema support to WordPress core, this might be a better feature request for WordPress Trac.

In my opinion, schema markup is ever-changing and quite complicated with different relations between entities etc. Adding support for that in core is simply not feasible and thus is best kept in plugin territory.
