### ISSUE TITLE
Setting typography.customFontSize: false in theme.json doesn't remove font size classes and variables

### ISSUE THREAD

**Issue by philbuchanan** [WordPress/gutenberg#34120]
### Description

I'm using the `theme.json` file to disable a number of font settings for the theme. Specifically there is an issue with custom font sizes:

```json
{
	"version": 1,
	"settings": {
		"typography": {
			"customFontSize": false,
			"fontSizes": []
		}
	}
}
```

Setting both of those properties _does not_ actually remove the classnames (e.g. `.has-large-font-size` or variables (e.g. `var(--wp--preset--font-size--large)`).

The challenge this introduces is that the `core/cover` block's default template uses `<p class="has-large-font-size">…</p>`. Since the UI was disabled in `theme.json`, there is no way in the editor to remove this setting (with the exception of using the code editor which I don't think is a valid solution). Further, because the `.has-large-font-size` class uses `!important` it is also very difficult to override the style in my theme. I can use `!important` myself, but if I have custom paragraph styles applies, I'll need even more specific selectors. 

I would expect that if I disable custom font sizes entirely, it should not define the classnames or variables at all or, at the very least, not apply them to existing blocks.

### Step-by-step reproduction instructions

1. Disable custom font sizes using `theme.json`.
2. Add a `core/cover` block.
3. Note the `has-large-font-size` class applied with no way to remove it.

### Environment info

WordPress 5.8
Not using the Gutenberg plugin (although I have tested and the issue remains with the plugin enabled).

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

**Comment by andrewserong** [comment]
Thanks for reporting this @philbuchanan, for the particular blocks affected, was it just the Cover block you noticed the issue with? It sounds like for a short-term fix, we might be able to check the `customFontSize` setting in the Cover block before setting the innerblocks template, and then set the `fontSize` attribute only if the setting hasn't been disabled.

**Comment by philbuchanan** [comment]
@andrewserong I only noticed this with the Cover block.

**Comment by ramonjd** [comment]
The [Cover block defines an innerBlocks template](https://github.com/WordPress/gutenberg/blob/c5a842aab91b53c646cf9f45c387e4ce225b887b/packages/block-library/src/cover/edit.js#L77), explicitly setting the `fontSize` attribute to `'large'`.

```
const INNER_BLOCKS_TEMPLATE = [
	[
		'core/paragraph',
		{
			align: 'center',
			fontSize: 'large',
			placeholder: __( 'Write title…' ),
		},
	],
];
```

The block support hook detects the existing `fontSize` attribute and adds the class automagically.

It looks as though we generate the className `has-large-font-size` in the [fontSize hook](https://github.com/WordPress/gutenberg/blob/a7e2895829c16ecd77a5ba22d84f1dee1cfb0977/packages/block-editor/src/hooks/font-size.js#L73), specifically in the `blocks.registerBlockType` and `blocks.getSaveContent.extraProps` filters at the bottom of that file.

Before running `addSaveProps`, which adds the className, we check if the block has support for the feature. It appears that it only takes the settings in `paragraph/block.json` into account, and not any overriding theme.json rules.

At first glance it sounds sensible to filter out such attributes if support for that attribute has been turned off. That might however affect existing blocks that have applied font size or any other block support style, and still have the corresponding attributes.

I don't have sufficient general knowledge of theme.json to know if my thinking is right on this though. 🤔 

I can think of a few options:

Remove `fontSize: 'large',` from the innerBlock template in `cover/edit.js` and let the user decide whether they want large font sizes (or otherwise) in the Cover block. 

In my view this would be the easiest option: we don't dictate how a paragraph appears in the cover block.

Maybe not ideal from a design perspective, since the default text will be smaller. 

We could on the other hand replace the innerBlocks with a heading. 

<img width="670" alt="Screen Shot 2021-09-21 at 3 35 14 pm" src="https://user-images.githubusercontent.com/6458278/134116699-20bbba2f-0bfd-42a9-8404-305a91fd998b.png">

That might have semantic implications, that is, if we declare an `h2` it might not fit in the semantic flow of HTML document elements.

**Comment by ramonjd** [comment]
> we might be able to check the customFontSize setting in the Cover block before setting the innerblocks template, and then set the fontSize attribute only if the setting hasn't been disabled.

The the customFontSize setting applies to the paragraph block so maybe we could do this in the [fontSize](https://github.com/WordPress/gutenberg/blob/a7e2895829c16ecd77a5ba22d84f1dee1cfb0977/packages/block-editor/src/hooks/font-size.js) hook, which is where the props are extended according to any activated block support rules. 

This assumes that:
1. It's a good idea
2. We can dive into the settings (via [useSettings](https://github.com/WordPress/gutenberg/blob/bf060dbdc6d4aa40736a6559455a373e4850e0d0/packages/block-editor/src/components/use-setting/index.js) hook?) at filter runtime.

**Comment by andrewserong** [comment]
Thanks for digging into this one @ramonjd!

Instead of manipulating the fontSize hook, I was wondering if we could do something like having two separate `INNER_BLOCKS_TEMPLATE` constants in `cover/edit.js` and switch the one we're passing in to `useInnerBlocksProps` based on the result of `useSetting( 'typography.customFontSize' );`?

So, perhaps something along the lines of `template: hasCustomFontSize ? INNER_BLOCKS_TEMPLATE : INNER_BLOCKS_TEMPLATE_WITHOUT_FONT_SIZE` around [this line](https://github.com/wordpress/gutenberg/blob/trunk/packages/block-library/src/cover/edit.js#L611-L611)?

Or, move the INNER_BLOCKS_TEMPLATE constant to be defined within the `edit.js` function, possibly inside a `useMemo` and return the template with or without the `fontSize` attribute, based on the custom font size setting?

**Comment by ramonjd** [comment]
> Instead of manipulating the fontSize hook, I was wondering if we could do something like having two separate INNER_BLOCKS_TEMPLATE constants in cover/edit.js and switch the one we're passing in to useInnerBlocksProps based on the result of useSetting( 'typography.customFontSize' );?

Ah yes, I didn't think of this. Brilliant, thank you. I was fixated on the individual block's support, rather than the theme when considering an in-block approach. I'll try this out!

_Edit_: it ended up being the `fontSizes` array that we needed to check.
