### ISSUE TITLE
Add applyFilters to the Query Block query.

### ISSUE THREAD

**Issue by TobyOsborne** [WordPress/gutenberg#34201]
## What problem does this address?
Currently, there doesn't seem to be a way to modify the Query Block query (for the preview in the block editor).

For example, I'd like to create a custom attribute that modifies the query to show different items.

On the frontend this is easily done through pre_get_posts, but I'm having a hard time reflecting it in the block editors preview.

## What is your proposed solution?
Add an`applyFilters` somewhere that provides access to the Query block attributes, and allows modifying the query variable set in the post-template block (around line [89](https://github.com/WordPress/gutenberg/blob/b2b35ba7b89b7d62dffec9db4cbd34edb6533414/packages/block-library/src/post-template/edit.js#L89))

**Comment by ntsekouras** [comment]
Thanks for the issue @TobyOsborne !

I believe this issue is resolved by a set of PRs(ex [1](https://github.com/WordPress/gutenberg/pull/43590), [2](https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/extending-the-query-loop-block/)).

You can read more about [extending Query Loop block](https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/extending-the-query-loop-block/) and if feel free to reopen the issue if you need something different.
