### ISSUE TITLE
Nav items of fixed "type" retain ability to enter a custom URL.

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#34224]
## What problem does this address?

On the current screen if I add a "Page" item it remains as a "Page" item which is always locked to the URL represented by that Page entity. In the new editor the UI affords the ability to edit the URL to be anything. Therefore I can create an item with a specific type, but then update the URL to be something else entirely. This becomes very confusing.

## What is your proposed solution?
Consider disabling ability to enter custom URLs when nav item is of a specific type (ie: Page, Post...etc). Alternatively make system "intelligent" enough to convert the nav item to "custom" if/when the user enters a custom URL.

## Screenshots

https://user-images.githubusercontent.com/444434/130430175-79adedc0-6435-43c9-a3c7-355bf8e50d8c.mov

**Comment by getsource** [comment]
In case it's relevant (I think it is, as far as auto-switching?), during testing of #34072, I noticed that if the link is manually edited to a different post ID that exists, but without using autocomplete, that doesn't update the ID attribute.

**Comment by Thelmachido** [comment]
Closing this issue due to the project being moved to [an inactive status on the feature projects page](https://href.li/?https://make.wordpress.org/core/features/) in coordination with the project leads. If this work is picked back up, issues can be revisited and reopened as needed.

Thanks for testing this early feature and giving feedback so the wider WordPress project could benefit from the lessons learned!
