### ISSUE TITLE
Add ability to create a new navigaition menu with a single click

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#34227]
## What problem does this address?

The existing Navigation screen has a means to create a new menu from a single click. The new screen is a two step process of finding the "hidden" button in the dropdown and then clicking.

## What is your proposed solution?

Add a button to the top toolbar saying "Create new Menu".

### Existing
<img width="1116" alt="Screen Shot 2021-08-23 at 11 43 51" src="https://user-images.githubusercontent.com/444434/130435080-e8c37ede-c2fa-419c-b94b-e161101c04c3.png">

### New
<img width="1117" alt="Screen Shot 2021-08-23 at 11 44 23" src="https://user-images.githubusercontent.com/444434/130435082-387ef32d-646e-4bdb-9b70-f2913e5ea136.png">

**Comment by javierarce** [comment]
+1 to adding a button in the top bar https://github.com/WordPress/gutenberg/issues/31241

![image](https://user-images.githubusercontent.com/4933/130582549-f8b586ff-7428-40f2-9342-f17f19da9f0d.png)

**Comment by draganescu** [comment]
@javierarce if we add the inserter the plus icon is gonna show up twice in the toolbar, once for the inserter sidebar and once for the create menu button. Can we just try text?

**Comment by javierarce** [comment]
Yeah, we'll need to do that, good point… I'll update the designs.

**Comment by javierarce** [comment]
Here is the updated design for the top bar: https://github.com/WordPress/gutenberg/issues/31241#issuecomment-915871085

**Comment by Thelmachido** [comment]
Closing this issue due to the Navigation Screen project being moved to [an inactive status on the feature projects page](https://href.li/?https://make.wordpress.org/core/features/) in coordination with the project leads. If this work is picked back up, issues can be revisited and reopened as needed. 

Thanks for testing this early feature and giving feedback so the wider WordPress project could benefit from the lessons learned!
