### ISSUE TITLE
Improve UX for nesting navigation items via drag / drop

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#34234]
## What problem does this address?
The existing Navigation screen allows you to drag items horizontally in order to nest them. This isnt supported by the new screen even in the "List view" (which is accessible via the Nav block toolbar itself).

## What is your proposed solution?
Either implement a similar drag to indent UX or a new control in the block toolbar to allow items to be nested (a bit like how you can nest bullet lists in MS-Word or Google docs). 

## Screenshot
https://user-images.githubusercontent.com/444434/130451241-ce62d151-b4b9-41a8-bcd0-7b1eca4e7204.mp4

**Comment by getdave** [comment]
FYI the List View part of this puzzle looks like it may be addressed by https://github.com/WordPress/gutenberg/pull/34022.

**Comment by Thelmachido** [comment]
Closing this issue due to the project being moved to [an inactive status on the feature projects page](https://href.li/?https://make.wordpress.org/core/features/) in coordination with the project leads. 

If this work is picked back up, issues can be revisited and reopened as needed. Thanks for testing this early feature and giving feedback so the wider WordPress project could benefit from the lessons learned!
