### ISSUE TITLE
Ability to ascertain nav item "type" without having to select each Nav item

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#34233]
## What problem does this address?
On the new Navigation screen unless you click on an individual nav item (and you have the sidebar open) it's not possible to tell at a glance what the "type" (eg: Post, Page, Category...etc) of a given nav item is. 

The existing Nav screen as indicators next to each item.

## What is your proposed solution?

Add some kind of indicator inline without having to click on each item to see the "type".

### Existing Navigation screen

You can see the "types" at a glance:

<img width="728" alt="Screen Shot 2021-08-23 at 13 54 13" src="https://user-images.githubusercontent.com/444434/130450818-2e85d4e6-3820-4f01-a70c-c11a227bea7a.png">

### New block based Navigation screen

No types without clicking on each item:

<img width="1121" alt="Screen Shot 2021-08-23 at 13 55 07" src="https://user-images.githubusercontent.com/444434/130450812-12d05fd5-5fd0-4031-8781-a2a9e0d56a1a.png">

**Comment by Thelmachido** [comment]
Closing this issue due to the Navigation Screen project being moved to [an inactive status on the feature projects page](https://href.li/?https://make.wordpress.org/core/features/) in coordination with the project leads. If this work is picked back up, issues can be revisited and reopened as needed. 

Thanks for testing this early feature and giving feedback so the wider WordPress project could benefit from the lessons learned!
