### ISSUE TITLE
Ability to bulk select non (immediately) adjacent sibling Nav items

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#34232]
## What problem does this address?
The existing Navigation screen allows for selecting multiple nav items that are not immediate siblings and removing them in one go. The new screen only allows this for immediate siblings but does not work if you have to select items that are not next to each other.

## What is your proposed solution?
Update block selection mechanic to allow for selecting multiple items that are not immediate children by holding CMD or Ctrl and clicking.

## Screenshot

https://user-images.githubusercontent.com/444434/130450157-9ecec405-ae99-442f-9306-d68def9e096b.mp4

**Comment by talldan** [comment]
Related https://github.com/WordPress/gutenberg/issues/2320, https://github.com/WordPress/gutenberg/issues/16797

**Comment by getdave** [comment]
I've pinged the contributors on https://github.com/WordPress/gutenberg/pull/16811 to see if there were good reasons why this approach was abandoned and also to see if we can restore the branch and continue to build on the approach there.

**Comment by Thelmachido** [comment]
Closing this issue due to the Navigation Screen project being moved to [an inactive status on the feature projects page](https://href.li/?https://make.wordpress.org/core/features/) in coordination with the project leads. 

If this work is picked back up, issues can be revisited and reopened as needed. Thanks for testing this early feature and giving feedback so the wider WordPress project could benefit from the lessons learned!
