### ISSUE TITLE
Border radius not working for the button block

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#34240]
### Description

When a theme provides a border-radius via `theme.json` the styles are not enqueued. Comes from https://github.com/WordPress/gutenberg/pull/34180#issuecomment-903625767

### Step-by-step reproduction instructions

- Add this to the empty theme:
```json
	"styles": {
		"blocks": {
			"core/button": {
				"border": {
					"radius": "0",
					"color": "red",
					"style": "solid",
					"width": "6px"
				}
			}
		}		
	}
```

- Create a new post that contains a button.
- The expected result is that both in editor and front doesn't have rounded borders.

### Screenshots, screen recording, code snippet

Editor | Frontend
--- | ---
<img width="861" alt="Screenshot 2021-08-23 at 11 54 27" src="https://user-images.githubusercontent.com/3593343/130428290-073e588d-72ab-4028-a476-b0e874074a1f.png"> | <img width="945" alt="Screenshot 2021-08-23 at 11 54 23" src="https://user-images.githubusercontent.com/3593343/130428292-fbeef4d7-800f-478c-a673-8752a339cd78.png">

### Environment info

This happens in `trunk` with the latest WordPress.

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

**Comment by oandregal** [comment]
cc @aaronrobertshaw @ramonjd

**Comment by aaronrobertshaw** [comment]
Initially, I thought this was related to the issue where block support styles that are applied after skipping serialization couldn't target the correct element.

Turns out the generation of styles from the theme.json filtered out `empty()` values which caught `"0"` as well. 

A PR to fix this is now available: https://github.com/WordPress/gutenberg/pull/34251
