### ISSUE TITLE
Navigation editor: Menu switcher doesn't show after deleting a menu

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#34255]
### Description

The change implemented in https://github.com/WordPress/gutenberg/pull/29201 seems to have regressed.

### Step-by-step reproduction instructions

1. Visit the navigation editor
2. Make sure you have at least three menus, if not create some menus
3. Delete one

Expected: the menu switcher is shown
Actual: another menu is shown

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

**Comment by Mamaduka** [comment]
Thanks for catching this, @talldan.

I might have introduced this regression with #31320. I will have a look at a possible fix tomorrow.

**Comment by javierarce** [comment]
👋 Is this issue still relevant?

**Comment by Thelmachido** [comment]
Closing this issue due to the project being moved to [an inactive status on the feature projects page](https://href.li/?https://make.wordpress.org/core/features/) in coordination with the project leads.

 If this work is picked back up, issues can be revisited and reopened as needed. Thanks for testing this early feature and giving feedback so the wider WordPress project could benefit from the lessons learned!
