### ISSUE TITLE
Make it easier to add new items in between existing Nav Item blocks within the Nav Editor

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#34268]
## What problem does this address?

In the new Nav Editor screen it's really difficult to add items in between existing items.  This is because the inserter is only about 1 pixel and so it's _really_ hard to select it.

Try adding some nav items and then hovering in between the items to see if you can get the quick inserter to show up.

## What is your proposed solution?

- [ ] Improve the interaction so  there is a bigger target area to trigger the inserter.
- [ ] Add the "global" inserter to the top bar of the editor screen as per other Editors.

**Comment by getdave** [comment]
cc @rolf-yoast as you flagged this to me.

**Comment by Thelmachido** [comment]
Closing this issue due to the project being moved to [an inactive status on the feature projects page](https://href.li/?https://make.wordpress.org/core/features/) in coordination with the project leads. If this work is picked back up, issues can be revisited and reopened as needed. 

Thanks for testing this early feature and giving feedback so the wider WordPress project could benefit from the lessons learned!
