### ISSUE TITLE
Search Block “Optional placeholder” text takes on nav block underline

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#34275]
### Description

When assigning the underline styling to the overall navigation block, the "optional placeholder" text adopts the underline likely due to some CSS bleeding. 

### Step-by-step reproduction instructions

1. Add a navigation block to the site editor.
2. Add a search block.
3. Select the overall navigation block and, in the sidebar settings, select the underline option.
4. Notice that the  "optional placeholder" text shows underlined text. 

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/130706973-ee971919-aab6-4bbe-b4b9-b4dfaad446ec.mov

### Environment info

- WordPress 5.8
- Gutenberg 11.3
- Desktop with MacOS

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

**Comment by jasmussen** [comment]
Good ticket. I have a "fix" in https://github.com/WordPress/gutenberg/pull/34379 that we might not want to merge. Another option is to simply remove text decoration support from the navigation block entirely!

**Comment by jasmussen** [comment]
After exploring the fix in #34379, conversation in the comments suggested that underline due to its unique nature on a technical level needs to be individually applied to each menu item, lest it will be inherited all the way down the stack.

Whether that also means we move the underline control to each menu item, or whether we can/should provide a nav-block global toggle is up for conversation. But it means this one needs a different fix.

**Comment by annezazu** [comment]
Noting that text decoration has been removed from the navigation block and is not in 5.9 (was looping back on the state of things): https://github.com/WordPress/gutenberg/pull/37963 Going to leave this open until the above draft PR is merged/work continues to address this.
