### ISSUE TITLE
The last sibling inserter is redundant

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#3433]
The last sibling inserter is redundant, as it is immediately followed by the bottom inserter. I'd propose to remove it or find a way to not reveal it.

It's redundant visually and also for keyboard users and screen reader users:
- keyboard users will have to tab through to contiguous controls that do the same thing
- screen reader users will hear "Insert block" twice when tabbing away from the last block

![screen shot 2017-11-10 at 17 34 11](https://user-images.githubusercontent.com/1682452/32668620-5f29a25a-c63e-11e7-930d-10933748e36f.png)

**Comment by mtias** [comment]
Also related: https://github.com/WordPress/gutenberg/issues/3078

**Comment by jasmussen** [comment]
I'm very keen on #3078, and I think it'll do a lot for the writing flow.

The key idea of that ticket is that we have the toolbar inserter, we have the slash inserter, and when you make a linebreak between two blocks and insert a block, it gets inserted where your caret is. Point being — although this is a block editor, we are mimicking patterns that are seen in normal textarea editors. 

The sibling inserter is an experiment to improve the flow for inserting between blocks, without having to click enter first. I think the idea is sound, even if we need to polish it a bit further. However if we do remove the trailing inserter in #3078 — which I think we should absolutely try sooner rather than later — perhaps we should postpone removing the last sibling inserter, or at least tackle that as part of improvements to that component itself.

**Comment by jasmussen** [comment]
Closing as the last sibling inserter is no longer present.
