### ISSUE TITLE
Remove the icon and word Navigation from the Nav block select option line.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#34365]
## What problem does this address?

Selecting a Nav - horizontal.

![Screen Shot 2021-08-28 at 09 35 40](https://user-images.githubusercontent.com/5323259/131210413-ade65efc-099b-4e66-af82-4c7288396e1c.jpg)
The icon and word Navigation is on the same line as to where one adds a selection. It crowds the options.

Selecting a Nav - vertical.

![Screen Shot 2021-08-28 at 09 40 04](https://user-images.githubusercontent.com/5323259/131210546-c5c7b9d5-e017-403a-a1fa-0cf70b72a89f.jpg)

## What is your proposed solution?
This:
![Adjusting-Navigation-select-area](https://user-images.githubusercontent.com/5323259/131210461-6278ce11-08b5-4409-acb0-da744490308a.jpg)

and

this:
![Adjusting-Navigation-select-area-vertical](https://user-images.githubusercontent.com/5323259/131210619-41306119-bff0-45a4-9bbb-e929c17c514d.jpg)

One only shows the options we need to choose from. No distraction with the icon and Navigation text.

**Comment by jasmussen** [comment]
Yep, placeholders are difficult, in part due to the space they take up. I do think that we need both a holistic rethink of the visual appearance of appenders (not just looking at a single block but looking across). But also that we need to use these more sparingly — a separate issue.

I did explore some designs on this topic a while back. I'm not completely in love with them so paused it, but sharing here in case it inspires others:

<img width="940" alt="Generic placeholder" src="https://user-images.githubusercontent.com/1204802/131304588-aee38329-c516-4363-ba11-6def2b385e4f.png">

<img width="740" alt="Setup states   appenders" src="https://user-images.githubusercontent.com/1204802/131304596-767fd752-784e-4449-b037-ae6e21387a3d.png">

<img width="1460" alt="Setup states   appenders 2" src="https://user-images.githubusercontent.com/1204802/131304603-f2f7df97-a538-4397-b07f-b5046756d6e2.png">

Note in the above how in group, column, and navigation blocks you have to select them first to surface the options. So there are two states. That is especially useful in case of the group block where it allows you to select the group block itself, in case you'd like to delete it. In the case of the navigation block, it helps it pass the squint test, since its resting state has an icon indicator.

**Comment by annezazu** [comment]
A lot has changed since this issue was opened! Here's the current state with WordPress 5.9 and Gutenberg 12.5.3 showing how the placeholder adjusts based on amount of space given to the block both in terms of the full block name and default options to choose from:
<img width="816" alt="Screen Shot 2022-02-06 at 11 39 25 PM" src="https://user-images.githubusercontent.com/26996883/152745318-00b461e2-28b5-4efd-9848-dafbae7349c1.png">
<img width="421" alt="Screen Shot 2022-02-06 at 11 39 39 PM" src="https://user-images.githubusercontent.com/26996883/152745322-1a2c9f92-1e75-4a5d-b978-46e8aa0265f7.png">

As a result, I'm going to close this issue out as I think it's been well addressed in the last 6 months. Feel free to re-open if there's something I missed!
