### ISSUE TITLE
Gutenberg enhanced code editor request

### ISSUE THREAD

**Issue by Theo789595** [WordPress/gutenberg#34367]
So as you know Gutenberg has 3 available options for editing:

1. Visual block editor
2. Edit as HTML option for blocks
3. Code Editor (ctrl+shift+alt+m)

**Issue:**
Other than the block editor needing a lot of work to go... the code editors need work to be done too.
When editing as html and especially when using code editor it is unacceptable to just have a plain, raw space with 0 functionality to code in.

**Request:**
**Highlighting** and **autocomplete** and any other improvements for **code editing** inside the editor.

**Comment by mtias** [comment]
Thanks for the feedback. See #17017 #10423 and #5614 that cover improvements to the code editor.

**Comment by palmsout** [comment]
Is it me or has the code editor been removed altogether? I no longer have the option to change to code editor mode while in the site editor. I looked through the release changelog, and I didn't see anything about this. What could be causing this if this was not an intentional change? Sorry if this is comment is not in the right place. Let me know if I could start a new issue (if this is a novel bug or something, which I can't imagine it could be).

**Comment by palmsout** [comment]
Sorry, I wasn't specific enough before. I can still see the code editor option for posts, etc. But I can no longer see it when I'm editing a template. I'm sure I used to be able to! @mtias

**Comment by carlomanf** [comment]
@palmsout the code editor has disappeared because of changes that were made with #35990. I left a comment over there because I noticed that revisions had disappeared as well. Both are features that I use from time to time and should be reinstated.

**Comment by jameskoster** [comment]
Yes the code editor was never made a part of the template editor. I'm unaware of the context there, so it may be worth opening a new ticket to discuss this.

**Comment by danger89** [comment]
Maybe see also Monaco editor: https://github.com/microsoft/monaco-editor
