### ISSUE TITLE
Heading Block: Add option to adjust spacing below

### ISSUE THREAD

**Issue by supernovia** [WordPress/gutenberg#34392]
## What problem does this address?
With blocks as widgets, users have to add a heading block if they want to keep their widget titles. But depending on the theme, that may result in a heading that has a big space underneath it that can currently only be solved with CSS:
<img width="1457" alt="Screen Shot 2021-08-30 at 11 24 31 AM" src="https://user-images.githubusercontent.com/3476361/131380708-084dfc4a-d40c-4a21-8e00-bbf218b5e473.png">

## What is your proposed solution?
Offer an option for adjusting the margins. Obviously this isn't nice looking in Preview, but maybe something like this. 
<img width="343" alt="Screen Shot 2021-08-30 at 11 22 23 AM" src="https://user-images.githubusercontent.com/3476361/131380816-5a0c82cd-6d32-43c6-9c4c-70f0a353fa70.png">

**Comment by bph** [comment]
Is the heading block getting padding/margin support?

**Comment by supernovia** [comment]
> Is the heading block getting padding/margin support?

I hope it will! It'd resolve this widget title issue people are seeing.

**Comment by colorful-tones** [comment]
I believe this may have been resolved recently with [Add spacing controls to all heading blocks #35772](https://github.com/WordPress/gutenberg/pull/35772), but could probably use testing and verification.

**Comment by ntsekouras** [comment]
@colorful-tones is right and there was a discussion and decision to include only the `margin` support: https://github.com/WordPress/gutenberg/pull/35772#issuecomment-947377980.

In order to see this control though you [need to enable](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/hooks/margin.js#L76) it in your theme(https://wordpress.slack.com/archives/C02QB2JS7/p1635329909091600).

**Comment by ndiego** [comment]
The Heading block now supports margin, so I am going to close this issue. I also just [opened a PR](https://github.com/WordPress/gutenberg/pull/43454) to add padding support.
