### ISSUE TITLE
Allow disabling `text` and `background` color via `theme.json`

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#34414]
The new UI for the global styles sidebar is going to expose text and background as elements the user can modify. Themes should be able to enable/disable them as they do with the link color. Both at the global and per-block levels.

![image (1)](https://user-images.githubusercontent.com/583546/131493291-9bf0d634-d26c-4067-b14a-e00a514be266.png)

We don't need a specific key for gradients so far. They can already be disabled in isolation by the themes by doing:

```json
settings.color.gradients: [],
settings.color.customGradient: false
```

that only affect the gradients.

**Comment by mtias** [comment]
Palette + custom color, and gradient + custom gradient are pairs of settings that affect the _content_ of color and gradient tools. Access to disabling specific elements (text, background) would be great. We need to contemplate if we need to support custom palettes for these areas, because that might change the signature a bit. Perhaps in that case we need to lean and replicate the `styles.elements` object and also do a `settings.elements` where you could specify a custom palette for an element or disable it entirely, or only support gradients, etc.

**Comment by oandregal** [comment]
Ah, nice. Yeah, it may be cool to have different palettes per element. I'd think it could work as you suggested. So far, with the elements we have (link and headings) and the way they are exposed in the UI, the rest of the settings wouldn't be used anywhere, though.

Regarding background & text. I was wondering what would you think of having a new element called "body"/"default"/"general" in the UI that groups the settings & styles contained at the global level in the `theme.json` (the ones that don't match any block or element and are serialized to the `body` HTML element). It creates some dissonance for me to mix things in that UI panel. Elements or blocks -for example, the link element or the group block- can have any style property (text color, background color, gradient color) while text or background mean a very thing (the text color or body & the background color of the body, respectively).

Anyway, independently of how we show them in the UI, I'd think we still go ahead with https://github.com/WordPress/gutenberg/pull/34420 as adding the ability to disabling text & background independently matches what we do for the other style properties (`color.link`, `border.style`, `typography.fontWeight`, etc).
