### ISSUE TITLE
Add support for custom taxonomies in navigation editor

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#34442]
## What problem does this address?

Follow up from https://github.com/WordPress/gutenberg/issues/34440. 

The current menu screen, allows for custom taxonomies terms to be added to menu. See screenshot from current editor.

<img width="302" alt="Screenshot 2021-09-01 at 10 36 15" src="https://user-images.githubusercontent.com/237508/131649203-79c3a8de-86e4-4804-ab57-08e72900a342.png">

However these custom taxonomies are not reflected in navigation editor.

<img width="436" alt="Screenshot 2021-09-01 at 10 31 30" src="https://user-images.githubusercontent.com/237508/131648151-b7709cad-5a2d-4dda-92f8-9c3a6493bd79.png">

## What is your proposed solution?

Add support for custom taxonomies in navigation editor

**Comment by kathrynwp** [comment]
Closing this issue due to the Navigation Screen project being moved to [an inactive status on the feature projects page](https://make.wordpress.org/core/features/) in coordination with the project leads. (The developer documentation in the initial post are no longer accessible)

If this work is picked back up, issues can be revisited and reopened as needed. Thanks for pitching in on this early feature so the wider WordPress project could benefit from the lessons learned!
