### ISSUE TITLE
Navigation editor should respect `show_in_nav_menus` 

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#34443]
## What problem does this address?

When registering custom [post types](https://developer.wordpress.org/reference/functions/register_post_type/) or [taxonomies](https://developer.wordpress.org/reference/functions/register_taxonomy/), there is a param called  `show_in_nav_menus`. This param is designed to control what CPT / taxonomies are shown in menu screen. Developers can also use `register_taxonomy_args` or `register_post_type_args` to change built in types to be hidden / shown in nav menus. 

It worth noting that this data is in the taxonomy REST API endpoint [already](https://github.com/WordPress/wordpress-develop/blob/afb38a6eb6a02f949b12ae381438d0b7c7bbef0e/src/wp-includes/rest-api/endpoints/class-wp-rest-taxonomies-controller.php#L255). However, this `show_in_nav_menus` data is not returned Post types endpoint. So this data will have be added. 

Related: https://github.com/WordPress/gutenberg/issues/34442 https://github.com/WordPress/gutenberg/issues/34440

## What is your proposed solution?

Navigation editor should respect show_in_nav_menus

**Comment by spacedmonkey** [comment]
CC @TimothyBJacobs as we will need to add new fields to the post types endpoint.

**Comment by spacedmonkey** [comment]
Created a core patch https://github.com/WordPress/wordpress-develop/pull/1650

**Comment by spacedmonkey** [comment]
It is worth noting that a `show_in_nav_menus` should be true, but `show_in_rest` could be false. Not sure yet how we handle this. Thoughts @TimothyBJacobs ?

**Comment by TimothyBJacobs** [comment]
I think probably a separate issue for that @spacedmonkey.

**Comment by kathrynwp** [comment]
Closing this issue due to the Navigation Screen project being moved to [an inactive status on the feature projects page](https://make.wordpress.org/core/features/) in coordination with the project leads. (The developer documentation in the initial post are no longer accessible)

If this work is picked back up, issues can be revisited and reopened as needed. Thanks for pitching in on this early feature so the wider WordPress project could benefit from the lessons learned!
