### ISSUE TITLE
Navigation block: Home link option causes spacing issues

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#34470]
### Description

When adding the Home link option to the navigation block, the next item added causes spacing issues. This is likely related to https://github.com/WordPress/gutenberg/pull/33021. This was found as part of the [ninth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2021/08/11/fse-program-testing-call-9-handling-highered-headers/#comment-1922)

### Step-by-step reproduction instructions

1. Add a navigation block.
2. Add in the Home Link option.
3. Add a custom link or an additional item and notice the spacing collapses. 

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/131723325-303478ae-edcf-46e1-ab12-e8a517bf5385.mov

### Environment info

- WordPress 5.8
- Gutenberg 11.4
- TT1 Blocks
- Desktop MacOS

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

**Comment by annezazu** [comment]
cc @jasmussen

**Comment by jasmussen** [comment]
Thanks for the issue. I can't reproduce in trunk:

![tt1](https://user-images.githubusercontent.com/1204802/131797184-9b141774-7acf-4059-8c26-d330f4c17e05.gif)

Furthermore, I'm almost certain that this issue has been fixed by #33918 and #33918, which together closed #33048. The motivation is best explained in [this comment](https://github.com/WordPress/gutenberg/pull/32677#issuecomment-861284806), but boiled down to each navigation item having its own navigation margin and padding styles, causing the exact issue described here.

Are you able to test using trunk?

**Comment by annezazu** [comment]
Thanks as always for your lovely follow up. Confirmed that I can't replicate with trunk! Strange considering the PRs listed merged are shown for 11.4 (which I can replicate with). Closing this out either way.
