### ISSUE TITLE
"ReferenceError: CSS is not defined" when testing with wp-scripts test-unit-js

### ISSUE THREAD

**Issue by ryelle** [WordPress/gutenberg#34476]
### Description

When running a test with the default `test-unit-js` command provided by `@wordpress/scripts`, I'm getting this failure: `ReferenceError: CSS is not defined`

I can track it back to this line:

https://github.com/WordPress/gutenberg/blob/4623cf1e90db7373b63acd750380ee6ea0e60bac/packages/components/src/ui/utils/space.ts#L33

I can fix it by adding a local `jest.config.js` to define an empty CSS global, but I think this should be handled in the provided jest config.

### Step-by-step reproduction instructions

I created a very simple demo using `create-block`, you can see it here: https://gist.github.com/ryelle/221233ba154225475300649dc485f3e0 -- I made no changes to the default code, just stripped it down a bit and added a test.

Run `npm test` and you'll see the error.

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

**Comment by gziolo** [comment]
@ciampo or @sarayourfriend, any thoughts on how we can resolve this issue in unit tests?

> I can fix it by adding a local jest.config.js to define an empty CSS global, but I think this should be handled in the provided jest config.

Should we use a fallback in the code when `CSS` is not defined?

**Comment by ciampo** [comment]
> Should we use a fallback in the code when CSS is not defined?

We can change the code to something like `CSS?.supports?.( ... )`, although that won't prevent an error if in the future another call to `CSS.supports` will be added to the codebase.

In addition to that, in order to prevent similar errors in the future, I would also consider adding the `CSS` global to the Jest configuration.

**Comment by gziolo** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/CSS/supports – it exists only on the web so it's similar to other usages of API that are present only in the browser. In other places, we add check to ensure that this code will run with Node.js, example:

https://github.com/WordPress/gutenberg/blob/ca67d603637950bc08291ed9208a3f2d2e3e67c2/packages/compose/src/hooks/use-media-query/index.js#L17-L18

**Comment by ciampo** [comment]
I've done some further investigation and also found out this related ticket — jsdom/jsdom#2026

I've also opened #34572 which adds a check to make sure that `CSS.supports` is only called in a browser environment, as discussed.

Should we also consider editing the Jest config and add `CSS` as a global, in order to prevent a similar issue from happening in the future?

**Comment by gziolo** [comment]
> Should we also consider editing the Jest config and add CSS as a global, in order to prevent a similar issue from happening in the future?

With #34572, is that still necessary? I think it's a good thing as it helps us to catch some potential bugs with non-browser envs.

**Comment by ciampo** [comment]
Good point. Let's leave the config untouched, then.
