### ISSUE TITLE
Dropdown menus are now very narrow

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#34518]
### Description

This week I've spotted that dropdown menus have become very narrow. This feels like a very recent regression.

In some cases the UI is not functional, in other cases it's not making use of the available space as well as it could be.

### Step-by-step reproduction instructions

1. Add an image block
2. Resize the screen to a small size
3. Click the Insert From URL button

Expected: the dropdown has adequate space to type in a URL
Actual: the dropdown is very narrow

1. Add a navigation block
2. Select the  'Add existing Menu' button.

Expected: the dropdown is a reasonable width
Actual: The dropdown is very narrow

There are other cases too, and this will probably have affected users of the components package, so I think the root issue with dropdowns.

### Screenshots, screen recording, code snippet

<img width="435" alt="Screenshot 2021-09-03 at 11 02 42 am" src="https://user-images.githubusercontent.com/677833/131946558-9ff1c8e7-76bf-46c9-9f3b-420a307acd6c.png">

<img width="177" alt="Screenshot 2021-09-03 at 11 29 02 am" src="https://user-images.githubusercontent.com/677833/131946569-f78113dc-c8fc-46cb-99a1-510967c85d88.png">

### Environment info

Gutenberg version: Latest `trunk` at the time of writing.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by youknowriad** [comment]
cc @jasmussen

**Comment by jasmussen** [comment]
This is almost certainly a result of #33995, which removed a min-width that every popover was born with. The reasoning is this: the popover should be agnostic to its content, and be able to accommodate both wide content:

<img width="326" alt="Screenshot 2021-09-03 at 09 43 59" src="https://user-images.githubusercontent.com/1204802/131969408-0b7f16ad-15a8-48f8-b129-8d021bbfa628.png">

... but also content that is intentionally thin, like the vertical headings level indicator:

<img width="477" alt="Screenshot 2021-09-03 at 09 44 15" src="https://user-images.githubusercontent.com/1204802/131969449-2c287276-770b-4e36-9ff8-9d4b03b13927.png">

The second part of the reasoning is that it's up to each menu item individually to ensure that it has a reasonable width. Since the popover is now as wide as the smallest item inside, this can be done either using `white-space: nowrap;` on items inside, or by applying an appropriate min-width.

Sorry I missed this one, and thank you for the ticket. I'll prepare a patch in a moment, but short of restoring the basic min-width and overriding it in case of the vertical heading, would you agree the above reasoning makes for a good principle?

**Comment by jasmussen** [comment]
Got a fix in #34532, which reapplies a min-width to the _menu item component_, which means most text menus should now not collapse beyond a basic minimum.

**Comment by talldan** [comment]
@jasmussen The logic sounds good. My feeling is this should be considered a breaking change for the components package, so the changelog would need to be updated to say this.

**Comment by jasmussen** [comment]
Good point. I'll put together a changelog update in a little bit. Do you think it needs a dev note as well?

**Comment by talldan** [comment]
Not sure, it's probably ok just as a note in the package changelog. I think in terms of WordPress core it's probably very very minor, but to users of the package (given the package's remit) it's something they should have more control over when updating.

**Comment by jasmussen** [comment]
Updated the changelog in https://github.com/WordPress/gutenberg/pull/34532/files#r701802151, let me know if that looks right.
