### ISSUE TITLE
A Query Block is inserted when Inserting a Posts List Block

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#34556]
### Description

When you insert a _Posts List Block_, it actually inserts a _Query Loop Block_ instead.

<img width="1440" alt="screenshot_146" src="https://user-images.githubusercontent.com/2078245/132118366-e8c2ff1d-98e1-482a-b874-54f0c82ba603.png">

If this block is simply a customised version of the _Query Loop Block_, then you need to tell users this. Inserting a completely different block to what the user selected is confusing. If this is what it's supposed to do, then at the very minimum, don't show "Query Loop" in the Settings Sidebar for the block title.

There is zero documentation when I tried to google to find out anything about this block so I have absolutely no idea whether this is doing what it's supposed to be doing, or not. Either way, it's incredibly confusing. There isn't even any indication in the Help Panel in the Block inserter, that this block is simply a customised Query Loop block.

<img width="1052" alt="screenshot_148" src="https://user-images.githubusercontent.com/2078245/132118713-3c733b4a-639b-45ee-ae3c-61361e45b574.png">

Having multiple blocks that perform identical functions is really poor usability and confusing.

### Step-by-step reproduction instructions

1. Insert Posts List Block
2. Look at Settings Sidebar to see that it's inserted a Query Loop Block instead

### Environment info

WP5.8 (No Gutenberg plugin. Core only)
TwentyTwenty
MacOS Big Sur 11.5.2
Firefox 91.0.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by maddisondesigns** [comment]
Also, why does it exclude Sticky Posts, and why is there no option to include them? If this Block is supposed to be used within a theme template when FSE becomes available, then why would I want to exclude Sticky Posts?

**Comment by ntsekouras** [comment]
👋 @maddisondesigns - thanks for creating the ticket.

`Posts List` is indeed a  `Query Loop's block variation` and that's why it's shown in the inserter. This behavior is the same for every variation with `inserter` scope (or nothing as `inserter` is the default) like `Youtube` which is just a block variation of `Embed` block.

`Query Loop` is a quite new block with many enhancements planned for the future and I was wondering why seeing the `Query Loop` there was a problem? Besides the confusion that you describe, what was your use case, goal or expectation, that  couldn't be achieved. Any more specific feedback would be really helpful.

>If this is what it's supposed to do, then at the very minimum, don't show "Query Loop" in the Settings Sidebar for the block title.

Regarding the above, there is a calculation (through `isActive` prop in block variations API) if a block matches a block variation. In complex blocks like the `Query Loop` is quite hard to properly match the block and there are discussions/plans to use some variations which are configured for some basic needs, like the above. `Posts List` is a `Query Loop` configured to show `posts` and exclude `sticky` posts, which is a quite common use case for a site.

**Comment by maddisondesigns** [comment]
@ntsekouras Thanks for explaining that. My main concern is that it's confusing for users when you select one block (Posts List) and it inserts a completely different block (Query Loop).

I can understand why it's done and having a pre-configured block makes sense to make it easier for users, but the way it's done at the moment, makes it confusing.

You mention that other blocks currently work in same way, for example, a _YouTube_ block is just a block variation of the _Embed_ block. That may be so, but as far as your average user is concerned, the _YouTube_ block is just another completely different block. When you insert a _YouTube_ block, it actually shows "YouTube" in the Settings Sidebar. The user can see that the block they inserted is the one that was indeed added. This doesn't happen with the _Posts List_ block. When you insert a _Posts List_ block, the Settings Sidebar tells you that you've inserted a _Query Loop_ block instead. The same goes for the _List View_ button in the top Block Editor Toolbar (at the top of the page). If I'm searching through that to find the _Posts List_ block that I just inserted earlier, I'm not going to find it because it's listed as a _Query Loop_ block instead. As an end user, it's confusing when you think you're inserting one thing, and it ends up inserting something else.

<img width="1920" alt="screenshot_749" src="https://user-images.githubusercontent.com/2078245/133872956-2fbfa2dc-85ac-4bae-b5fd-b13eca346886.png">

It either needs to say _Posts List_ in the Settings Side (and the List View), or it needs to be made clearer that what you're actually inserting is a (customised) _Query Loop_ block instead.

**Comment by ntsekouras** [comment]
>It either needs to say Posts List in the Settings Side (and the List View), or it needs to be made clearer that what you're actually inserting is a (customised) Query Loop block instead.

Makes sense @maddisondesigns ! I understand the issue here and is not an easy one to solve well. 

Noting that there are already some discussions about this and the road map for `Posts List` and in general the handling of `Query Loop` and its block variations.

So I'll close this one in favor of the existing: https://github.com/WordPress/gutenberg/issues/32268. Check it out and follow that one, for continuing the discussions in one place.

Thanks!
