### ISSUE TITLE
The Global Styles Interface

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#34574]
_In collaboration with @pablohoneyhoney. Not finalized._

Previously #27473.

This issue covers the broad design aspects of global styles, the upcoming user interface for `theme.json`. For the broader implementation roadmap check #20331. The global styles interface aims to allow managing design aspects of a site globally and across blocks. The current interface merged in the plugin is merely a tentative placeholder.

### Iconography

Global styles will be a crucial component for the set of design tools and deserves a more iconic representation. In the future, there will be flows built into the system allowing you to move from _local_ styles to _global_ — like making customizations to a button block and opting to apply them globally changes across all buttons of that type. To support these flows from within the local scope a recognizable symbol can help guide the different flows as the functionality spreads across more places.

- [x] Closes: #20873

![image](https://user-images.githubusercontent.com/548849/132193095-e2113fc5-706e-4482-bdfe-43165048f3b2.png)

The initial placement of the tool continues to be in the editor header for the site editing or template editing contexts. As part of the broader explorations on information architecture for the site editing features, direct access is also a possibility.

![image](https://user-images.githubusercontent.com/548849/132192975-44ecc38b-ad97-48a3-bcd4-9a7f9470d756.png)

### Structure

Currently the target are four main components to the interface plus a preview:

- Colors.
- Typography.
- Layout.
- Blocks.

Together they represent the formal structure of `theme.json`. This is designed to allow growing in the future as needs arise, either in core or through extensions. Navigating through sections currently is intended to work as a drill-down pattern to provide more breathing room for the tools and additional focus.

**Small previews.** One challenge the design aims to solve is the problem of not necessarily seeing what you are affecting because changes are applied far and wide on the site and those elements may not be visible at all times in the larger canvas preview. For example, if you are customizing duotone filters globally but don't have an image in the current view, the user may not be seeing the entirety of what they are affecting. To address this, each panel is structured around a top level abstracted **preview**. This is meant to capture the spirit of customizations while also providing instant feedback and hierarchy.

![image](https://user-images.githubusercontent.com/548849/132187344-df9cd402-bd47-4273-a7d3-26e6341d9add.png)

Down the road, the capabilities of global styles could expand to provide a more in depth styleguide that can expand across blocks and patterns. While not an immediate priority, it is considered in various issues, including #32682.

- [ ] Consider all meta-functions of global styles. This footer menu is not an immediate priority but it would provide access to a variety of functions that are not formally spec'd yet.

![image](https://user-images.githubusercontent.com/548849/132194453-fe2bbaed-7544-4906-bf57-34de9dcb8259.png)

- Styleguide.
- Revisions.
- Reset all.
- Export / import.
- Theme / Pattern browsing.
- etc.

#### Palettes

![image](https://user-images.githubusercontent.com/548849/132201379-c9caecab-31e7-4073-ab4c-9e15a5e8b9f4.png)

The color section encapsulates the ability to visualize and manage color palettes as well as customizing color elements across the site. Currently, there's a single set of color palettes that can be provided at one time, but this is meant to change with the overview at #29568.

- [x] Closes #28416.

Following up, multiple sets of palettes would be a possibility, including light / dark splits. The access point for managing color palettes is the following one:

![image](https://user-images.githubusercontent.com/548849/132196153-a4225392-ed4e-4caf-92aa-4ff069ad862f.png)

It lists some initial colors for recognizability and the overall number of colors available. Palettes are split between **theme** (more semantic), **default** (spectrum based), and **custom** (colors registered by the user).

![image](https://user-images.githubusercontent.com/548849/132188024-1536a6c4-14f2-4f20-89c3-5e4d03de5c2f.png)

There are a bunch of granular combinations that need to be supported, since the **default** palette ought to be replaceable or disabled entirely. Custom colors could also be disabled globally, which means this panel could look like this depending on configuration:

![image](https://user-images.githubusercontent.com/548849/132195463-6b715304-e5d9-4df2-9bed-a6339eaa66bb.png)

If available, editing a color palette would work as follows:

![image](https://user-images.githubusercontent.com/548849/132195678-3d714933-8c69-4f4b-8df8-bd817d8338fa.png)

Palettes include both solid colors as well as gradients. The gradient tools still need to be finalized:

![image](https://user-images.githubusercontent.com/548849/132201706-f333be95-dff7-4912-b435-15f171944b2c.png)

#### Elements & Filters

More general descriptions of elements is to be included in the main tracking issues, but this gives a good overview of what aspects are represented. Most importantly, background, text, links, etc, are represented here as elements. (Elements can resolve to CSS variables sometimes.)

![image](https://user-images.githubusercontent.com/548849/132196892-0ba0d8df-d5ed-44bc-b387-bb83e429bfba.png)

- [ ] A category of "filters" is split and would allow configuring things like duotone across a site when it should apply beyond individual blocks (like Image, Media & Text, and Featured Image, for example, but not a Gallery). This is a good example of an in-depth feature that needs to connect a block-agnostic context with block specific settings, hence the navigation.
- [x] Filters, such as duotone, need configurable defaults. They are equivalent to a new color palette.

Right now core only supports duotone, and infrastructure work is being done to connect it with `theme.json`.

- [x] #33642. 
- [ ] #34122.

One major challenge also comes in how multiple color states can be represented and accessed as is the case of links. This needs further research to narrow down a UX flow that makes sense while not being overbearing.

![image](https://user-images.githubusercontent.com/548849/132202773-33c86d08-8b6d-4169-ad9e-eda6e7726f32.png)

#### Tool

Accessing an element brings into focus the main color tools with an emphasis towards selecting a color from existing palettes. The preview element is used as an anchor point and to provide immediate feedback on interactions. The color picker is a fundamental component of this interface.

- [x] Tracking: #34284.

In the global styles context, the picker opens as a _flyout_ menu:

![image](https://user-images.githubusercontent.com/548849/132191321-33ab5148-d85b-49d1-9cef-d4cbd0ede685.png)

#### Fonts

Managing fonts as site assets still needs a more formal proposal but broadly speaking the design would incorporate a recognizable small preview. This is the corollary to the palette management interface. These sets would be extensible and configurable, ranging from a single default set (current state) to multiple choices.

![image](https://user-images.githubusercontent.com/548849/132197992-7b6b72e7-181e-4a0e-919b-bf24383f2589.png)

With support for additional pairings and browsing the UI would evolve to accommodate it. There's a larger surface of issues to work through and figure out when it comes to themes switching and the ability to combine sets from different themes or styles.

![image](https://user-images.githubusercontent.com/548849/132197832-82bc6ead-5eeb-4bea-b26c-cbffe3d05b98.png)

An interface for selecting font families is still upcoming as there are quite a few details to get right, including communicating potential performance impact of multiple fonts.

- [ ] Finalize UI for selecting and managing fonts.

#### Elements

Elements naturally operate in the same way as the colors panel does.

- [x] The main difference if the `GroupItem` contains a small preview of the specific typography attributes applied.

![image](https://user-images.githubusercontent.com/548849/132198372-2a31e45c-4e40-4acd-aae1-291528195b0f.png)

This is updated live to reflect current choices.

#### Tool

![image](https://user-images.githubusercontent.com/548849/132199312-a3610d4e-3b27-48b2-9e45-843090c9f830.png)

The concrete tools for typography are the same to the one used in blocks and reflect the settings of theme.json. A breakdown of that in more detail:

- [ ] Tracking: #34345
- [x] The extra addition is a preview area that draws from the preview elements used throughout global styles.

### Layout

The last group gathers tools around layout and spacing. In the context of global styles this is reduced to site container attributes. There are several issues tracking progress and improvements on the various layout related tools.

![image](https://user-images.githubusercontent.com/548849/132192696-f75d4932-35cc-4781-a46e-ff629956b5a3.png)

- [ ] #29506.
- [ ] #33687.
- [ ] #28356 and #34558.

### Blocks

The "by block" section is an interface to the more granular `theme.json` that affects individual blocks across a site. This allows controlling the default settings and style attributes of blocks and renders in a similar way to the block inspector toolbar.

![image](https://user-images.githubusercontent.com/548849/132199614-ffe9b262-8e3e-4e47-a9d6-1a7926537672.png)

- [x] Include design of inner panel.

It needs to be clear what blocks might have customizations.

**Comment by youknowriad** [comment]
Just wanted to update quickly here on the progress:

 - The sidebar has a new icon now.
 - We also introduced the navigation system in #34885 it's using the old Navigation components but we're considering switching to new simpler components that offer more UI flexibility in #34904

**Comment by youknowriad** [comment]
The global styles preview has just been added in #34991

**Comment by Clorith** [comment]
I'm honestly not sure if this is the right ticket for thoughts on the concept of a `theme.json` administrative interface, but I'll throw it in, please feel free to point me elsewhere if there is a better location.

The concept of an interface here in the first place feels counter-intuitive to WordPress' philosophy I feel ("Decisions, not Options"), we are now potentially throwing a **lot** of options at users, and they are things the user probably should not be changing in the first place.

The concept of a hardcoded configuration file in the theme is that the theme has made the decisions for the user, the theme authors know what limitations to impose, and which choices the user should reasonably make, this is all part of the themes identity, and by giving users without that familiarity the power to overwrite that within core with a set of button clicks, especially when a lot of the implications of changes here may not be apparent to the average user, I worry this will be a bad experience both to the user, but also theme developers who put time and effort into those decisions.

This is in contrast to how the customizer currently works, to make a comparison I know has been made elsewhere before. In the customizer, the theme has made a conscious decision on what the user should be able to modify, and how, where as here the themes entire set of decisions are exposed to the end user.

I did see the mention of creating some kind of generic previews, but I don't feel those give a realistic representation of what the user is changing in the same way as for example the customizer where you see your actual content would (the exception being if the Site Editor element you're looking at happens 

I should make it clear though, as a power user, I absolutely LOVE the idea of this interface (and I really like how it's shaping up by looking at this tickets planned ideas), but this really feels like it would be a prime area for someone to make a standalone plugin for those who want that granular control to override what others have defined, because as a built in feature it introduces a lot of what I will call "potentially dangerous" options (for example the current implementation, which I know is a bit of a placeholder, has no relationship to content, so I can safely now make my text and background clash contrast-wise without the warnings I'd get in the normal block editor, and this change would now be globally acknowledged as the default value, and I would only see the individual warnings inside the block editor it self if I chose to look at the color options for the text I write).

**Comment by annezazu** [comment]
@Clorith I wanted to chime in to share some thoughts as I've heard some of this feedback a ton with my work with the FSE Outreach Program. Hopefully it helps give wider context and others can continue to chime in as needed. This is not meant to stop the conversation but to continue it.

>we are now potentially throwing a lot of options at users, and they are things the user probably should not be changing in the first place.
&
>by giving users without that familiarity the power to overwrite that within core with a set of button clicks, especially when a lot of the implications of changes here may not be apparent to the average user, I worry this will be a bad experience both to the user, but also theme developers who put time and effort into those decisions.

Right now, this work is intentionally being done in a way that "illustrates the maximum amount of customization options — the ability to lock down templates, capabilities, design tools, etc, is still a prime focus to account for the different needs of different sites" (From the [Status Check: Site Editing and Customization](https://make.wordpress.org/core/2020/12/10/status-check-site-editing-and-customization/) post). 

>This is in contrast to how the customizer currently works, to make a comparison I know has been made elsewhere before. In the customizer, the theme has made a conscious decision on what the user should be able to modify, and how, where as here the themes entire set of decisions are exposed to the end user.

This will still be the case with theme.json as options are being added to disable options. For example, you could disable the option for users to add Custom Font sizes with a simple line to theme.json: 
```

{
    "version": 1,
    "settings": {
        "typography": {
            "customFontSize": false,
}
```

These options to disable and "lock down" various pieces will continue to be built into theme.json so theme authors can still do that curation or, conversely, purposefully have things be wildly customizable by users. 

Of course, as you mentioned, I imagine there will always be room for plugins to play a role in locking down the interface for folks or, conversely, opening up options more to create a more tailored experience based on the site's needs. For example, perhaps the site administrator wants to use a theme where they can customize every little detail but they want the option to lock those options down for other users on the site.

**Comment by youknowriad** [comment]
Quick update on the progress above: We've just separate the color palette panel to its own screen in #35109, we've designed the Menu Item as suggested in the issue above, the palette's design itself is still unchanged though.

**Comment by youknowriad** [comment]
Small update here: The site padding has been added in #35241

**Comment by Clorith** [comment]
Thanks for the extended explanation @annezazu, appreciate it!

So does this mean that the ability to disable customization with `false` entries is already implemented? Looking at the current documentation this isn't quite clear on a global level, but on a per-block level it is, which may be why I did not notice this feature at first. Perhaps we should expand the `theme.json` documentation to have a section for disabling global customization options, would that make sense?

Has any thought been put into what happens when core introduces new global styles down the road, which themes have not opted out of, since they didn't know of them at the time of creation? Would it make sense to introduce a `settings.globalStyles.disabled` type entry where a `true` value opts the theme out of the global styles editor altogether, thus fully locking down the creators choices and that's that (unless the site users chooses to install a plugin, of course)?

**Comment by oandregal** [comment]
> Would it make sense to introduce a `settings.globalStyles.disabled` type entry where a true value opts the theme out of the global styles editor

:wave: The existing settings affect the UI panels of the block sidebar & the global sidebar. This is, if you do `settings.color.custom: false` the user should not be able to add custom colors in an UI panel (whether block or global). See the [docs](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#settings) for the full set of settings available at the moment.

If I understand correctly, the purpose of something along the lines of `disabled` would be to prevent the global sidebar in the site editor from being available. In my view, it makes more sense to control the availability of the site editor and the global styles sidebar via WordPress capabilities, like the we do in the Customizer (`customize` capability).

**Comment by youknowriad** [comment]
Status update here: The color panels for background, link and text have been extracted to separate views per the design above in https://github.com/WordPress/gutenberg/pull/35400

**Comment by Clorith** [comment]
> If I understand correctly, the purpose of something along the lines of `disabled` would be to prevent the global sidebar in the site editor from being available. In my view, it makes more sense to control the availability of the site editor and the global styles sidebar via WordPress capabilities, like the we do in the Customizer (`customize` capability).

That was my intended approach, yes, that it would then be controllable by `theme.json`, and not capabilities, capabilities are already a complex system as is (I'm not opposed to this, just airing some thoughts), and tieing it into capabilities means a theme ideally shouldn't be modifying these things, hopefully, they can, but it's always better when functionality is handled by plugins, whole other conversation I know :) 

I did have a look at the docs, and declaring for each available customizable option that you want to disable it is an option _now_, but what about when the available options change in the future, if I as a theme creator wanted to lock down everything, my theme could then be "future proofed", instead of needing to be on top of any new customization changes with every release (and even every plugin update in case someone is using the plugin).

But I still wonder what thought was put into a theme having the capability of declare that "I've made all these choices for the foreseeable future", as I still feel that's something the theme should be able to declare, if someone wants to make a _child_ theme, that removes this lock, that's a whole other story (speaking of, how would this work with child themes?)

**Comment by oandregal** [comment]
> how would this work with child themes?

Child themes with `theme.json` work fine and there's more work incoming. Details at https://github.com/WordPress/gutenberg/issues/25612

**Comment by sdwire** [comment]
I see a comment "The gradient tool still needs to be finalized."

That's encouraging. I'm not seeing if/where a design discussion is happening. Is there a page for discussing the gradient tool?

One thing I'd really like to see in the gradient tool is to let me select colors from among the solids in the color palette. If l then change the value of a color in the palette of solids, I'd like to see the gradients that use that color automatically updated to reflect that change.

I can't see that this idea has been discussed, and I'm not sure where to plant the idea. Any pointers?

**Comment by oandregal** [comment]
> This allows controlling the default settings and style attributes of blocks and renders in a similar way to the block inspector toolbar.

Just wanted to unwrap this comment. I understand this means that the block list could be organized by block categories instead of being a flat list?

**Comment by paaljoachim** [comment]
As the customizer is hidden from full site editing themes it would be very helpful to add a custom CSS area to the Global Styles panel. There is an issue for it here: 
**Global Styles: an input for custom CSS**
https://github.com/WordPress/gutenberg/issues/30142

**Comment by mtias** [comment]
Closing this as most of the UI is implemented. Splitting a new tracking issue just for typography at #38534.
