### ISSUE TITLE
schema for "/__experimental/menu-items" errors

### ISSUE THREAD

**Issue by MohammedFaragallah** [WordPress/gutenberg#34628]
I'm not sure any if these cases are intentional but,

https://github.com/WordPress/gutenberg/blob/dd5fd6b2466d33177d46dcdc0733abd0217e044a/lib/class-wp-rest-menu-items-controller.php#L1067-L1070

this endpoint return array of numbers for `menus` not a number

https://github.com/WordPress/gutenberg/blob/dd5fd6b2466d33177d46dcdc0733abd0217e044a/lib/class-wp-rest-menu-items-controller.php#L1046-L1051

also `_invalid` is missing not null or any falsy value

**Comment by talldan** [comment]
cc @spacedmonkey

**Comment by spacedmonkey** [comment]
Hello @MohammedFaragallah  I am developer of this endpoint. 

Let me explain these schema issues.

https://github.com/WordPress/gutenberg/blob/dd5fd6b2466d33177d46dcdc0733abd0217e044a/lib/class-wp-rest-menu-items-controller.php#L1067-L1070

This is not a mistake. A menu item can not be assigned to multiple menus. So I highjacked the schema, so that you only assign it to one endpoint. 

https://github.com/WordPress/gutenberg/blob/dd5fd6b2466d33177d46dcdc0733abd0217e044a/lib/class-wp-rest-menu-items-controller.php#L1046-L1051

I will look into this

**Comment by MohammedFaragallah** [comment]
@spacedmonkey thank you for your fast response

> This is not a mistake. A menu item can not be assigned to multiple menus. So I highjacked the schema so that you only assign it to one endpoint.

 maybe add `maxItems` to match the endpoint array response/or change the response to a number

 ```php
if ( 'nav_menu' === $taxonomy->name ) { 
 	$schema['properties'][ $base ]['maxItems'] = 1; 
 } 
```

**Comment by spacedmonkey** [comment]
> maybe add maxItems to match the endpoint array response/or change the response to a number

I don't like this idea, personally. Thoughts @TimothyBJacobs ?

**Comment by MohammedFaragallah** [comment]
@spacedmonkey  just a question does the schema represent the response?

I'm asking because I'm generating typescript definitions from it to make the response typesafe

it's working fine even with third-party plugins

**Comment by spacedmonkey** [comment]
@MohammedFaragallah I have pushed a couple of fixes. The schema should match up now. Can you checkout trunk and see if fixes your issues.
