### ISSUE TITLE
Navigation block: Add link color support

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#34648]
## What problem does this address?
Themes need a way to control the colors of links inside the navigation block. Ideally sub nav items have separate controls too. It would be really good to be able to control the colors of the reponsive menu too.

## What is your proposed solution?
We should add support for link color to the block.

**Comment by carolinan** [comment]
Related to this is that the site title block in the navigation block has a link color option, but the option doesn't work.

**Comment by ockham** [comment]
> Related to this is that the site title block in the navigation block has a link color option, but the option doesn't work.

I had a brief look into this. The reason is the following selector that includes the Navigation block class name twice, thus increasing specificity over the (elements-based) link color selector:

![image](https://user-images.githubusercontent.com/96308/137140589-543c92c6-9963-4b7b-ae2a-56cc3a2ceb72.png)

@getdave thankfully pointed me to the relevant code and comment: https://github.com/WordPress/gutenberg/blob/bccecb53099c6d372dfe1c1a5762a0409d1af23a/packages/block-library/src/navigation/style.scss#L43-L46

@jasmussen added that the specificity balance between themes and global styles is delicate. So we probably shouldn't simply remove the duplicate class name, since it'll likely break other things 😬 

Not sure how to proceed, but wanted to document these findings for posterity.

**Comment by jasmussen** [comment]
The inheritance, as I recall, is there to inherit colors set on the navigation block itself. I'll poke around a bit when I have a moment, see what we can do.

**Comment by jasmussen** [comment]
I think #35725 fixes this one, and per @ockham's suggestion, it simply removes the extra specificity, which is always good to remove. The only gotcha is that I recall that specificity as being _necessary_, but I don't recall why, other than it being related to how colors were output by global styles at the time. But hopefully there are no ill side effects and this one gets addressed in the process.
