### ISSUE TITLE
Patterns using VH units or fixed background vertically expanding their previews endlessly

### ISSUE THREAD

**Issue by Robertght** [WordPress/gutenberg#34729]
### Description

This is a replica of this issue: https://github.com/Automattic/wp-calypso/issues/56077

### Steps to Reproduce

1. Start by opening a page to edit
2. Click the blue plus sign to open the blocks & pattern search sidebar
3. Go to Patterns → Headers (in the Patterns drop down)
4. Start scrolling. The second pattern, "Large header with text and a button" does not load correctly and breaks the entire pattern selection box. 

I tested this on Chrome and did not see the same error/issue. 

In Safari, I also got an error that "This webpage is using significant memory. Closing it may improve the responsiveness of your Mac." 

I'm currently running Safari Version 14.1.2 (16611.3.10.1.6) on macOS Big Sur, version 11.5.2. 16" 2019 MacBook Pro. 

Video of the error: 

https://user-images.githubusercontent.com/30205248/132394213-f4588668-003c-4fea-9aec-0a6e2806f971.mov

### Operating System

macOS

### OS Version

11.5.2

### Browser

Safari

### Browser Version(s)

14.1.2

### Is this specific to applied theme? If so, what is the theme name?

I tested using Blank Canvas and also Bradford. Issue happened on both themes. 

### Available Workarounds

You can use a different web browser - I was able to select a header pattern in Chrome. 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jasmussen** [comment]
Thank you for the ticket. I can reproduce this in `trunk`. The issue is with the "Large header with text and a button" pattern under "Headers". 

The pattern in question uses both the cover block's fixed-position property and the has a height of `100vh`. This is the element that expands:

```
<div class="block-editor-block-preview__content components-disabled css-idxg31-StyledWrapper e1ac3xxk0" style="transform: scale(0.250833); height: 10028.1px;"><iframe aria-hidden="true" tabindex="-1" title="Editor canvas" style="position: absolute; width: 1200px; pointer-events: none; height: 39979px;"></iframe></div>
```

![bug](https://user-images.githubusercontent.com/1204802/133428044-db032ddc-9f9d-4526-8c43-a5b0eefadb5c.gif)

It appears to be the iframe auto-resize function that keeps firing, possibly because `100vh` keeps increasing as the iframe grows taller, causing a loop.

**Comment by Robertght** [comment]
@jasmussen It looks like there are other browsers and OS's(& versions) affected by this: https://github.com/Automattic/wp-calypso/issues/56182

**Comment by jasmussen** [comment]
I took the liberty of updating the title a bit.

**Comment by zdenys** [comment]
I was able to reproduce it with the Coming Soon patterns too.

https://user-images.githubusercontent.com/39308239/134360172-ee1253df-fc08-40ef-b535-53a49390f00c.mp4

**Comment by yansern** [comment]
**Investigation note:**
1. `100vh` units causes the resize observer to go into a firing loop.
2. The component tree looks like this `BlockPatternsList > BlockPattern > BlockPreview > AutoHeightBlockPreview`.
3. The file to look at is `packages/block-editor/src/components/block-preview/auto.js`.
4. Quick fix: As there is no DOM event that could determine when a page is fully rendered, I think the quickest way is to just have a hard limit on how many times ResizeObserver listener can be triggered.

**Comment by gwwar** [comment]
I saw this with Skatepark too. BlockPreview already has a viewportWidth prop. Can we provide a similar default for viewportHeight? Patterns that use vh should probably explicitly set this when registering the pattern. In addition to this we can set a max height (so we don't get silly results).

https://user-images.githubusercontent.com/1270189/137536800-3e9057b1-d43b-4d83-9e6a-b9bdee20601c.mp4

**Comment by alshakero** [comment]
I'm working on this and I think I've find a good solution. I'll send a PR shortly.

**Comment by alshakero** [comment]
PR ready https://github.com/WordPress/gutenberg/pull/35841

**Comment by kjellr** [comment]
Just a heads up that I've temporarily removed `Header area with hatched pattern` from the list of featured patterns, so that this doesn't happen whenever folks scroll down the "Featured" list.

**Comment by hngdny** [comment]
It seems that we still have recent reports of this happening: https://wp.me/pd4QKa-oI#comment-231

`Firefox 95 on Ubuntu 18.04 and also on a different computer with Chrome 96 and Chromium 90 on Ubuntu 16.04`

Tested on the following themes: Twenty Twenty, Alves, and Business Identity (retired)

**Comment by ndiego** [comment]
I wanted to circle back on this issue as it's a pretty important one, especially as patterns become a more integral part of the building experience.

I have been unable to diagnose the root cause, but I did want to highlight an incredibly easy way to reproduce this using native block controls.

1. Make sure you have the latest version of Gutenberg active.
2. Create a Columns block with two columns.
2. In the right column, add a Cover block, set a background image/color and apply the "Toggle full height" setting.
3. In the left column add some text.
4. Register a pattern with this block code. 
5. Preview the pattern in the Inserter. 

![vh-issue](https://user-images.githubusercontent.com/4832319/150136075-d63bdfbe-148a-440b-aaa2-99615243c657.gif)

What strange is while I am able to reproduce this in the latest version of Gutenberg, this issue does not appear to exist In WordPress 5.9 RC3! The same pattern in RC3 without Gutenberg active looks like this:

![image](https://user-images.githubusercontent.com/4832319/150137506-e703f44a-a13f-4ca3-931d-bba8a96758b7.png)

Very curious 🤔

**Comment by richtabor** [comment]
I've been able to replicate this, but only with vh units set to `100`. If I set a pattern to `99vh` it seems to be working fine.. probably 😅

**Comment by courtneyr-dev** [comment]
I have reproduced this issue as well when activating Gutenberg 12.5.x. I found it especially noticeable in Twenty Twenty One theme, and less apparent in Twenty Twenty Two. 

https://user-images.githubusercontent.com/5519705/150691541-60021696-2df9-4933-8433-81966a4f6719.mp4

Mac Monterey, Chrome Version 97.0.4692.71, running site in LocalWP, 5.9RC3

**Comment by noisysocks** [comment]
Can the folks here who are able to reliably reproduce the issue please go and test whether https://github.com/WordPress/gutenberg/pull/35841 fixes it?

**Comment by ixkaito** [comment]
I share my video from [WordPress Core's Trac](https://core.trac.wordpress.org/ticket/54885). This bug exists with all bundled themes except Twenty Twenty-Two.

https://user-images.githubusercontent.com/5457539/150724011-807bd9be-ef3a-4b8c-bcc0-b35f618dd076.mp4

#35841 seems to provide a minimum fix. Blocks still expand vertically but stop at the aspect ratio 1:1. 

https://user-images.githubusercontent.com/5457539/150724904-8ec2880d-8f6c-4852-aba5-de13ba05a54e.mp4

WordPress: trunk, 5.9-RC3
OS: macOS
Browsers: Chrome, Firefox

**Comment by ixkaito** [comment]
I noticed that this bug occurs with non-block themes. The bug is caused by the vertical margin applied to previews of `100vh` blocks. The vertical margin is set in the following file.

https://github.com/WordPress/gutenberg/blob/2484854b37ab5c138dab87743d1fc8f833074cd8/packages/edit-post/src/classic.scss#L28-L29

**Comment by hellofromtonya** [comment]
Hello all 👋  PR #38175 has been merged and will be backported to Core to include in 5.9 RC4 and final release. Thank you everyone for contributing!
