### ISSUE TITLE
Iterate menu creation screen to add content

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#34778]
This is based on the latest trunk for this experimental feature, so I am aware that this might be a work in progress. Still, I think there are several areas where things could perhaps be improved and avoid confusing interaction patterns. I am going to create separate issues for these not to confuse them. The first of these is having 2 links (or more) on one screen.

<img width="1271" alt="original01" src="https://user-images.githubusercontent.com/253067/133079714-950ce2b7-f559-4fe0-b8e1-fcabbf180102.png">

This above interface can get even more complicated when you have existing menus:

![2021-09-13 at 13 02](https://user-images.githubusercontent.com/253067/133080047-6863ee91-eee6-477c-bb17-f8bfa96a3c59.png)

Whilst, I don't think having a drop-down is the ultimate solution, and I think there's room for further exploring, I think it's better than having links in this case. Here is my starting idea for discussion:

<img width="1271" alt="iterare02" src="https://user-images.githubusercontent.com/253067/133080142-504c1da5-4435-4903-ba14-cbda49ab78d0.png">

I am also aware that what I am proposing isn't new and builds on previous work around this interface; I'd love input, though if there is a direction planned, I do not see for these screens I found. I know with existing menus we need a two-step process if have drop-downs for example.

**Comment by javierarce** [comment]
Thanks for this review, @karmatosed! 

There was a short conversation around that screen in this (already closed) [pull request](https://github.com/WordPress/gutenberg/pull/34568#issuecomment-913515320), so this issue is great to bring out some ideas from there.

In my opinion, we should get rid of this state and instead show an empty menu. That will simplify the process of creating navigations (but to explain what this screen is about to new users, we'll need to implement a Welcome Guide)

My motivation to remove that screen is that it won't really be needed when we add [bulk insertion](https://github.com/WordPress/gutenberg/issues/31667). Once we have that feature in place, the option to "Add all pages" will be less valuable. 

Regarding the last option (Copy existing menu), @Mamaduka mentioned that:

> If the current goal is to achieve parity with the "old" navigation screen, I think we can remove the "Copy existing menu" option. It doesn't exist on the current screen.

I agree and I also think that a "duplicate menu" option that was always available will be more helpful for users.

**Comment by karmatosed** [comment]
> In my opinion, we should get rid of this state and instead show an empty menu. That will simplify the process of creating navigations (but to explain what this screen is about to new users, we'll need to implement a Welcome Guide)

I think I'd need to see that idea of using the welcome guide instead, but I'm super curious about it. I certainly think this screen isn't the best.

> My motivation to remove that screen is that it won't really be needed when we add bulk insertion. Once we have that feature in place, the option to "Add all pages" will be less valuable.

Whilst I understand that, it is an expected pattern in WordPress, I think we could find people therefore assuming it would be there to add all. That doesn't mean it has to be on this screen, though - I can't recall if there was an easy 'select all' on the bulk adding because perhaps that solves this.

What do you think we could do to iterate what we have now and bridge the experience to get to the idea?

**Comment by javierarce** [comment]
> I can't recall if there was an easy 'select all' on the bulk adding because perhaps that solves this.

I added a "Remove selected" from my designs instead of a "Select all" because the new interface could allow selecting items from different types, and with the layout, I proposed there wasn't much space for a "Select all" option. That said, I could rethink that part of my design.

> What do you think we could do to iterate what we have now and bridge the experience to get to the idea?

I think the steps could be:

- Design and implement a Welcome Guide
- Design and implement a "Duplicate menu" option
- Release the [Bulk inserter](https://github.com/WordPress/gutenberg/issues/31667)
- Remove the menu creation screen

**Comment by karmatosed** [comment]
> I proposed there wasn't much space for a "Select all" option. That said, I could rethink that part of my design.

I slightly want to see what that could look like but I'm concerned if you are about limited space. I come back to it's an expected path for some users, which is why I would love to not remove it totally.

**Comment by kathrynwp** [comment]
Closing this issue due to the Navigation Screen project being moved to [an inactive status on the feature projects page](https://make.wordpress.org/core/features/) in coordination with the project leads. (The developer documentation in the initial post are no longer accessible)

If this work is picked back up, issues can be revisited and reopened as needed. Thanks for pitching in on this early feature so the wider WordPress project could benefit from the lessons learned!
