### ISSUE TITLE
Core Data: The "cacheKey" improvements

### ISSUE THREAD

**Issue by Mamaduka** [WordPress/gutenberg#34771]
### Sort `_fields` and `include` keys values

Both keys are normalized using the `getNormalizedCommaSeparable` function, but they aren't sorted. It results in having a different cache key if the order of values is changed, and triggering a new REST API request, even though we're requesting the same data.

Example:
```js
// Do the initial request.
wp.data.select('core').getEntityRecords('taxonomy', 'post_tag', { _fields: 'id,name' });

// This triggers another request, but can use previously cached values.
wp.data.select('core').getEntityRecords('taxonomy', 'post_tag', { _fields: 'name,id' });
```

### Update "hashing" method

Currently, we're using `addQueryArgs` to generate the query cache key "hash." While this method works just fine, it produces extra characters when encoding commas and ampersands.

I looked at few popular query libraries, and most of them are using `JSON.stringify()` to create a query cache key. So maybe we should also adopt this method.

* [React Query example.](https://github.com/tannerlinsley/react-query/blob/21f7b89e916852129e996b0141abcc2e1af554d4/src/core/utils.ts#L293-L312)
* [React Toolkit Query example.](https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/src/query/defaultSerializeQueryArgs.ts#L5-L20)

/cc @adamziel , @youknowriad, @jsnajdr

**Comment by jsnajdr** [comment]
`JSON.stringify` is not going to help with `_fields: 'name,id'`. The `'name,id'` value is a string, and no generic library can understand its internal structure and the fact that the order doesn't matter for `_fields`. I can imagine a very similar `_sort: 'name,id'` option where the order matters a lot.

We'll have to treat `_fields` specially to fix this.

**Comment by Mamaduka** [comment]
Thanks for the feedback, @jsnajdr.

We're already converting comma-separated values into an array and then back to string for the `stableKey.` So we can sort them after array conversion.

See: https://github.com/WordPress/gutenberg/blob/1d93095ce8f2dc72e024cf58f93d6824438f7313/packages/core-data/src/queried-data/get-query-parts.js#L74-L83

I only mentioned `JSON.stringify` as an alternative to the current cache key generator.

```
// Example cache key using `addQueryArgs`
?include=0%2C1%2C2%2C3%2C4&_fields=id%2Cname

vs

// Same key using `JSON.stringify`
{"include":"0,1,2,3,4","_fields":"id,name"}
```

**Comment by adamziel** [comment]
There are two levels to consider here

Level 1 is `@wordpress/data` resolution cache. It is entity-agnostic and uses the serialize resolver arguments as keys:

https://github.com/WordPress/gutenberg/blob/fb3d84b4a8245cc25b5978eddf95e4a3ff8d7477/packages/data/src/redux-store/metadata/utils.ts#L48-L59

I don't think it should know about the core-data-specific selectors, so we're left with layer 2: The `getEntityRecord` resolver in `@wordpress/core-data`:

https://github.com/WordPress/gutenberg/blob/fb3d84b4a8245cc25b5978eddf95e4a3ff8d7477/packages/core-data/src/resolvers.js#L132-L134

It would have to compile the full query in https://github.com/WordPress/gutenberg/blob/fb3d84b4a8245cc25b5978eddf95e4a3ff8d7477/packages/core-data/src/resolvers.js#L161-L164 and e.g. always sort the `_fields` query arg so that this fragment returns before the HTTP request:

https://github.com/WordPress/gutenberg/blob/fb3d84b4a8245cc25b5978eddf95e4a3ff8d7477/packages/core-data/src/resolvers.js#L97-L105

The same would be needed in `getEntityRecords`, only it is more complex there because there is no code path to short-circuit if there's a cache hit:

https://github.com/WordPress/gutenberg/blob/fb3d84b4a8245cc25b5978eddf95e4a3ff8d7477/packages/core-data/src/resolvers.js#L161-L166

**Comment by Mamaduka** [comment]
Thanks for the feedback, @adamziel.

I agree that "Level 1" doesn't need to know about the `core-data` specifics, but I would also expect any two selectors with the same arguments to return the same results.

@jsnajdr did some work to improve this (#38914, #38945).

**Comment by adamziel** [comment]
> I would also expect any two selectors with the same arguments to return the same results.

I assume you meant "two selector calls", not "two selectors"? I guess it's a matter of how we define _the same arguments_. It would surely be nice if a selector could say "this is a string" and "this is an http query". Perhaps if it made its own resolution cache key? I'm thinking of something like `getEntityRecords.resolutionCacheKey = function(kind, name, query) { }`

**Comment by Mamaduka** [comment]
Closing this issue as it doesn't seem to be a priority at the moment.
