### ISSUE TITLE
Bogus undo and unsaved changes state

### ISSUE THREAD

**Issue by Mamaduka** [WordPress/gutenberg#34802]
## Problem
When you open the Navigation Editor or reload the page after saving (CMD + R), the page is displayed if you have unsaved changes. It also shows the active "Undo" button, which does nothing.

## Screencast

https://user-images.githubusercontent.com/240569/133230675-08fb9bfc-e3e4-4d79-b2c9-c7bccc54f243.mp4

**Comment by Mamaduka** [comment]
I think this "side effect" causes the issue. If I comment out the `setAttribute`, there's no more unsaved state.

https://github.com/WordPress/gutenberg/blob/639a603bb47b5e2d6f8b3126225e3db0b1941480/packages/block-library/src/navigation-link/edit.js#L366-L373

Is it possible for `__unstableMarkNextChangeAsNotPersistent` not to work in context of Navigation Screen?

/cc @talldan.

**Comment by talldan** [comment]
You're right, it doesn't seem to be working in the navigation editor. I'm not sure why that would be though. Looking into it.

An option might just be to get rid of `isTopLevelLink`. I'm not sure why it should be needed, I think it should be possible to determine using a CSS selector whether something is a top level link. Using an attribute for this isn't great.

**Comment by Mamaduka** [comment]
I'm not sure about `isTopLevelLink.` Based on #31149, we need that attribute to have different color options for submenus.

Side note: If we end up keeping `isTopLevelLink`, we should wrap `setAttributes` in if condition and only set it for actual top links.

**Comment by talldan** [comment]
So there are a couple of differences between the post editor and the nav editor in terms of this issue:

### 1. Block is loaded differently
In the post editor `isTopLevelLink` is saved as an attribute so when loading a post this value is restored. `setAttributes( { isTopLevelLink } )` has no effect because the attribute already has the correct value. Contrast this to the navigation editor, blocks are converted to menu items when saving, `isTopLevelLink` isn't saved anywhere. When loading the block always has an `undefined` value, so now `setAttributes( { isTopLevelLink } )` actually does trigger a change. It could be possible to set a correct value for `isTopLevelLink` in our `menuItemToBlock` code, perhaps `true` when the parent is `0`, or `false` otherwise. 

### 2. Nav editor behaves slightly differently to the post editor in adding things to the undo stack.
The reducer that adds things to the undo stack works slightly differently in the post editor. There, changes to blocks are considered 'transient' edits, and the edit is flattened onto the previous item:
https://github.com/WordPress/gutenberg/blob/79be73821a236c4aee3216d98de301b025d206af/packages/core-data/src/reducer.js#L448-L464

This is defined in the entities definition, like this one for widgets:
https://github.com/WordPress/gutenberg/blob/79be73821a236c4aee3216d98de301b025d206af/packages/core-data/src/entities.js#L71-L79

I don't think the nav editor has a definition for its 'stub' navigation post entity, so maybe it needs one and to define block edits as transient.

**Comment by Mamaduka** [comment]
Thanks for the detailed explanation.

The Widget editor also uses an in-memory post entity but does have the same issue.

**Comment by talldan** [comment]
Just testing the widget editor, it does indeed have the same issue. Preventing the nav block from serialising `isTopLevelLink` (by deleting the attribute declaration) makes it become apparent.

I've put together a fix in #34839, but it introduces another issue. (edit: now fixed)
