### ISSUE TITLE
Add support for custom post type archive in navigation editor

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#34858]
## What problem does this address?

As of [#16075](https://core.trac.wordpress.org/ticket/16075), it has been possible to add custom post type archives into menus. The new navigation screen should also support this. 

<img width="753" alt="Screenshot 2021-09-15 at 21 48 58" src="https://user-images.githubusercontent.com/237508/133507376-a0fb84c0-6696-42dd-95aa-bf417351b5eb.png">

Related:  https://github.com/WordPress/gutenberg/issues/34440

**Comment by kathrynwp** [comment]
Closing this issue due to the Navigation Screen project being moved to [an inactive status on the feature projects page](https://make.wordpress.org/core/features/) in coordination with the project leads. (The developer documentation in the initial post are no longer accessible)

If this work is picked back up, issues can be revisited and reopened as needed. Thanks for pitching in on this early feature so the wider WordPress project could benefit from the lessons learned!
