### ISSUE TITLE
Add preference panel to navigation screen

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#34859]
## What problem does this address?

The current navigation screen, as screen options, that look like this. 

<img width="1616" alt="Screenshot 2021-09-15 at 21 53 46" src="https://user-images.githubusercontent.com/237508/133510132-f602316a-ea49-41fe-a061-1552b4438142.png">

This allows users to hide / show elements of the navigation screen. The new navigation screen should have this functionality as well. The post editor has a preference dialog, that could map to this functionality pretty well. 

<img width="811" alt="Screenshot 2021-09-15 at 21 58 56" src="https://user-images.githubusercontent.com/237508/133511947-add709d9-a758-4038-9dbc-81d0e4279039.png">

**Comment by talldan** [comment]
The editor will definitely need some preferences at some point for things like 'Top toolbar'.

I'm not sure all the options from the current menu editor screen to be replicated. The block editor already uses the inspector sidebar for secondary block settings and I don't think those things need to be enabled or disabled. It's more of a problem in the current menu screen where they take up precious screen space.

The checkboxes for post types / taxonomies are a little similar to the concept of the block manager (given the way those are currently exposed as variations of the link block), so that might be an interesting one to explore.

**Comment by spacedmonkey** [comment]
> It's more of a problem in the current menu screen where they take up precious screen space.

To give some context here, when I used to work on client sites, I used to go through any site and hide lots of the options the client would not use or and would find confusing. Hide sections is not only able screen space, it is a way to stream line the editor, to not confuse users. I flag this, as I can't have only been person to do this. 

There also just needs to be a way to hide and show sections. We may also want to allow users to allow hide / show what blocks can be used. See the block visibility section in the current editor. 

<img width="773" alt="Screenshot 2021-09-20 at 10 04 48" src="https://user-images.githubusercontent.com/237508/133978838-a0b9dda8-3fcd-4e32-9107-3dc99aedd72a.png">

**Comment by kathrynwp** [comment]
Closing this issue due to the Navigation Screen project being moved to [an inactive status on the feature projects page](https://make.wordpress.org/core/features/) in coordination with the project leads. (The developer documentation in the initial post are no longer accessible)

If this work is picked back up, issues can be revisited and reopened as needed. Thanks for pitching in on this early feature so the wider WordPress project could benefit from the lessons learned!
