### ISSUE TITLE
Consider moving the new menu link in screen

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#34933]
This is based on the latest implementation so I am aware that things might change. @javierarce please correct me if I am presuming or missing some context of something already planned.

The biggest issue for me right now is the positioning of the 'new menu'. It feels wrong if you compare it to other topbars.

<img width="1242" alt="01" src="https://user-images.githubusercontent.com/253067/133830863-aa157d18-9fc7-473e-9cc8-9a9a76a12c68.png">

That area is has a fairly predictable flow that includes publishing, which creating a new menu to me doesn't fall into.

<img width="1519" alt="02" src="https://user-images.githubusercontent.com/253067/133830920-2d47a3f2-af98-4eba-8fcf-a0545c1217f1.png">

Whilst I am aware they are different sections, if the idea is to unite them a little with interfaces, it seems confusing to place them there.

I would propose a variation of perhaps moving to the side as tools are placed there. This is just an idea and certainly needs iteration:

<img width="1410" alt="3" src="https://user-images.githubusercontent.com/253067/133831030-3ae94b96-2126-4136-9249-37fa552e8272.png">

I am not sure if the fact it's text is the problem, but we probably will be hiding it too much under an icon - it might be worth exploring though. I am also aware that 'create' will be in the drop-down, so over time we can know if a surface level 'new menu' is needed, but I suspect it will be.

**Comment by kathrynwp** [comment]
Closing this issue due to the Navigation Screen project being moved to [an inactive status on the feature projects page](https://make.wordpress.org/core/features/) in coordination with the project leads. (The developer documentation in the initial post are no longer accessible)

If this work is picked back up, issues can be revisited and reopened as needed. Thanks for pitching in on this early feature so the wider WordPress project could benefit from the lessons learned!
