### ISSUE TITLE
Text formatting mode lost after backspace is used

### ISSUE THREAD

**Issue by guarani** [WordPress/gutenberg#34938]
## Description
If the user has formatting ON (e.g. bold) and types text, then deletes a portion of it, the formatting is turned OFF as soon as the backspace key is tapped.

## Step-by-step reproduction instructions
1. In a paragraph block, turn on bold
2. Type some text, notice that the text will be bold as expected
3. Delete the last character(s)
4. Again type text, notice that the new text is not bolded (unexpected)

## Expected behaviour

I expect that deleting text should not reset formatting (bold, italics, strikethrough, etc). On Gutenberg web and the Gutenberg Android demo app, deleting does not reset formatting.

## Actual behaviour
Tapping backspace resets formatting to its default state of regular text weight, emphasis, etc.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/1898325/133846305-3d82797b-a1c6-4510-9756-2f9e8a014355.mov

## Device information
- Device: iPhone 12
- Operating system: 14.5
- Gutenberg demo app for latest commit on `trunk`: fcc32eeee7901472279b609a7d35b18c963388e8

## Additional info

First reported in https://github.com/wordpress-mobile/gutenberg-mobile/issues/757#issuecomment-717629028

**Comment by hypest** [comment]
Possibly also related: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2055

**Comment by fluiddot** [comment]
> **Step-by-step reproduction instructions**
>  3. Delete the last character(s), notice that the bold format button is now in its OFF state (unexpected)

@guarani Not sure if it refers to the bold format button located in the toolbar, if so, I noticed in the video and testing locally that the button is in its enabled state after pressing backspace, is this step accurate?

<img width="308" alt="Screenshot 2021-11-26 at 18 19 05" src="https://user-images.githubusercontent.com/14905380/143614459-0faa32e4-a791-4260-8ac7-880ffe152549.png">

**Comment by guarani** [comment]
You're right @fluiddot, I've now fixed that step above (not sure why I had that in there originally).

**Comment by fluiddot** [comment]
After checking both web and native version behaviors related to the calculation of the active format ([reference](https://github.com/WordPress/gutenberg/blob/d3b1327465cd9fa00489a3578d3c42bc6a597ede/packages/rich-text/src/component/index.native.js#L612)), looks like there are some differences but I couldn't find yet the culprit of this issue. I'll keep exploring the web version ([reference](https://github.com/WordPress/gutenberg/blob/trunk/packages/rich-text/src/component/use-format-boundaries.js)) in case there are any potential cases we might be missing in the native version hence, we should incorporate.

**Comment by fluiddot** [comment]
Upon further investigations, I found that the issue is unrelated to what I stated in the previous comment but Aztec which automatically recalculates the active text format when pressing the backspace key (i.e. deleting backward), as shown in the following example on an empty paragraph:

**1. Enable bold format (note the font attribute attribute `font-weight: bold`)**
```
activeFormats props passed from RichText to Aztec: [ { type: 'core/bold' } ]
Aztec typing attributes = {
    NSColor = ...
    NSFont = "<UICTFont: 0x7fa9f93dd6d0> font-family: \"Noto Serif\"; font-weight: bold; font-style: normal; font-size: 16.00pt";
    NSParagraphStyle = ...
}
```


**2. Type `123`**
```
Aztec typing attributes = {
    NSColor = ...
    NSFont = "<UICTFont: 0x7fa9f93dd6d0> font-family: \"Noto Serif\"; font-weight: bold; font-style: normal; font-size: 16.00pt";
    NSParagraphStyle = ...
}
activeFormats props passed from RichText to Aztec: [ { type: 'core/bold' } ]
Aztec typing attributes = {
    NSColor = ...
    NSFont = "<UICTFont: 0x7fa9f93dd6d0> font-family: \"Noto Serif\"; font-weight: bold; font-style: normal; font-size: 16.00pt";
    NSParagraphStyle = ...
}
activeFormats props passed from RichText to Aztec: [ { type: 'core/bold' } ]
Aztec typing attributes = {
    NSColor = ...
    NSFont = "<UICTFont: 0x7fa9f93dd6d0> font-family: \"Noto Serif\"; font-weight: bold; font-style: normal; font-size: 16.00pt";
    NSParagraphStyle = ...
}
```

**3. Press the backspace key (note the font attribute change to `font-style: normal`)**
```
Aztec typing attributes = {
    NSColor = ...
    NSFont = "<UICTFont: 0x7fa9a93abad0> font-family: \"Noto Serif\"; font-weight: normal; font-style: normal; font-size: 16.00pt";
    NSParagraphStyle = ...
}
activeFormats props passed from RichText to Aztec: [ { type: 'core/bold' } ]

```

This explains the behavior described in the issue, the bold format button is active because it's controlled by the RichtText component, however, the active format in Aztec is different. This change is produced when handling the event produced by pressing the backspace button ([reference](https://github.com/wordpress-mobile/AztecEditor-iOS/blob/969b90f3b14a55b3b07e8434ad2ee247f8a6adf4/Aztec/Classes/TextKit/TextView.swift#L723-L743)) which calls the `recalculateTypingAttributes ` function and sets a different format disabling bold ([reference](https://github.com/wordpress-mobile/AztecEditor-iOS/blob/969b90f3b14a55b3b07e8434ad2ee247f8a6adf4/Aztec/Classes/TextKit/TextView.swift#L1337-L1364)). The recalculation logic basically sets the typing attributes by retrieving the attributes of the text located at the current position, since the caret is placed at the end of the text in the example (specifically after text `12`), Aztec determines that there's no text format to apply and sets the font style to normal.

A potential workaround for this would be to prevent that Aztec from executing the typing attributes recalculation, and let the RichText component be in full control of the active format. I applied this solution in the following PRs:
- **Aztec-iOS PR:** https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1346
- **Gutenberg PR:** https://github.com/WordPress/gutenberg/pull/37676

<hr>

Something I noticed is that on Android this issue can't be reproduced, although it also produces a mismatching on the active format between Aztec and the format toolbar on a different case.

https://user-images.githubusercontent.com/14905380/147822852-cbf4d02d-2453-4edd-ba1f-2ed5164354ac.mp4

For this case, I opened another PR with a similar change, although for this case, the selected styles (i.e. the active format) were being modified by Aztec on text changes.

- **Aztec-Android PR:** https://github.com/wordpress-mobile/AztecEditor-Android/pull/949
- **Gutenberg PR:** https://github.com/WordPress/gutenberg/pull/37676

**Comment by guarani** [comment]
> You're right @fluiddot, I've now fixed that step above (not sure why I had that in there originally).

Oops, seems like I didn't delete this earlier, fixed now.
