### ISSUE TITLE
Use block icons on the Global Styles "Block Types" interface

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#34942]
## What problem does this address?
We leverage block icons everywhere, but in the current Global Styles "Block Types" panel, we're not.

<img width="744" alt="Screen Shot 2021-09-19 at 7 14 27 PM" src="https://user-images.githubusercontent.com/1813435/133946006-16467689-0afd-4b48-8a1d-25be4b90599a.png">

## What is your proposed solution?
Consider adding the block icons to the left of the labels for each block. 
<img width="738" alt="Screen Shot 2021-09-19 at 7 15 11 PM" src="https://user-images.githubusercontent.com/1813435/133946020-679d7ba2-6b98-406e-9926-5da6628d9c56.png">

**Comment by karmatosed** [comment]
+1 to use these if we are showing the blocks we should also show block icons. However, I also ponder if this screen is having some work done on it as part of the new sidebar work so @jasmussen I wonder if you have some context there?

**Comment by jasmussen** [comment]
I've been watching along the sidelines of #34574 how the inspector layout has been evolving since the initial version that landed as part of #18667. One of the things emerging so far appears to be the ItemGroup panel, which could for example [group a stack of color swatches together](https://github.com/WordPress/gutenberg/issues/33820#issuecomment-915081540), as well as the ability for the interface to slide as you drill down into an item. In absence of a good mockup exploring it, I'm not sure that ItemGroup would be a good interface for styling by block type, or whether we might want something that was closer along the lines of the list view from the slash command or the transform dialog. In all cases, icons probably do make sense there, and is definitely worth exploring in mockup form.

**Comment by karmatosed** [comment]
The sidebar is having some iterations but potentially right now using what is in main here is a rapid mock:

![2021-10-02 at 00 40](https://user-images.githubusercontent.com/253067/135696240-2c349a2c-b04b-4fbc-bfee-c13c8cc74ec3.png)

**Comment by mtias** [comment]
This was completed a little while ago.
