### ISSUE TITLE
Hide theme locations for menu if none available

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#34961]
Not all themes have theme locations for menus. However, the location menu area in the sidebar seems to show even if there aren't any available.

![2021-09-20 at 13 37](https://user-images.githubusercontent.com/253067/134003524-8150208d-1acd-4b82-a10e-d9f2bd7bd983.png)

I would recommend either showing a notice saying this is due to the theme - it just says 'none available' or just don't show unless the theme has them. It's a little confusing having them there if can't use them.

**Comment by kathrynwp** [comment]
Closing this issue due to the Navigation Screen project being moved to [an inactive status on the feature projects page](https://make.wordpress.org/core/features/) in coordination with the project leads. (The developer documentation in the initial post are no longer accessible)

If this work is picked back up, issues can be revisited and reopened as needed. Thanks for pitching in on this early feature so the wider WordPress project could benefit from the lessons learned!
