### ISSUE TITLE
Pass filter value when clicking Browse All in Nav Editor screen

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#34987]
Let's port over change from https://github.com/WordPress/gutenberg/pull/34912 which allows the search value to be passed over to the inserter when "Browse All" is triggered. THis saves the user from having to re-type their search query.

**Comment by getdave** [comment]
Add to the [Tracking Issue](https://github.com/WordPress/gutenberg/issues/29102) under `Normal`.

**Comment by kathrynwp** [comment]
Closing this issue due to the Navigation Screen project being moved to [an inactive status on the feature projects page](https://make.wordpress.org/core/features/) in coordination with the project leads. (The developer documentation in the initial post are no longer accessible)

If this work is picked back up, issues can be revisited and reopened as needed. Thanks for pitching in on this early feature so the wider WordPress project could benefit from the lessons learned!
