### ISSUE TITLE
Improve navigation screen loading state

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#34995]
## What problem does this address?
When loading menus with lots many menu items it, there is no loading state and there is indication to the user that something is happening. See video below. We should indicate to the user that the menu is loading. 

https://user-images.githubusercontent.com/237508/134154079-222d03ef-3899-4b9b-9030-135eed089b23.mov

**Comment by karmatosed** [comment]
This is a great usability gain if we add more than the tiny little loading circle. I have this feeling I've seen the skeleton placeholders in FSE places. If that is possible I would suggest bringing those in here. Just a gentle placing of that would be enough to give an indication of something incoming.

I have seen the following when no content in navigation, so adapting that for loader makes sense to me:

![2021-09-21 at 13 38](https://user-images.githubusercontent.com/253067/134171884-b5b71e9b-44c2-4358-bc72-466b8019f768.png)

https://github.com/WordPress/gutenberg/issues/22072 has some content on how this could be implemented.

**Comment by javierarce** [comment]
Linking to this other issue https://github.com/WordPress/gutenberg/issues/35503 since it's important we implement a common/similar solution.

**Comment by kathrynwp** [comment]
Closing this issue due to the Navigation Screen project being moved to [an inactive status on the feature projects page](https://make.wordpress.org/core/features/) in coordination with the project leads. (The developer documentation in the initial post are no longer accessible)

If this work is picked back up, issues can be revisited and reopened as needed. Thanks for pitching in on this early feature so the wider WordPress project could benefit from the lessons learned!
