### ISSUE TITLE
Lots of calls to menu item REST API after saving menu. 

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#34999]
### Description

Follow up ticket from https://github.com/WordPress/gutenberg/pull/34541 and this [comment](https://github.com/WordPress/gutenberg/pull/34541#issuecomment-922555964). 

When after saving a menu with lots of menu items ( say 500 ), the navigation editor, makes a REST API request, for every single menu item updated. This results in over 500 REST API calls. Sadly, this may take down site with a hardware firewall or limited memory. 

### Step-by-step reproduction instructions

1. Create menu with new navigation screen
2. Create many menu items. 
3. Save menu. 

See screen recording.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/237508/134155900-c809852c-465b-495e-8b3d-228f6774e925.mov

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kathrynwp** [comment]
Closing this issue due to the Navigation Screen project being moved to [an inactive status on the feature projects page](https://make.wordpress.org/core/features/) in coordination with the project leads. (The developer documentation in the initial post are no longer accessible)

If this work is picked back up, issues can be revisited and reopened as needed. Thanks for pitching in on this early feature so the wider WordPress project could benefit from the lessons learned!
