### ISSUE TITLE
Indicate to users when menus are saving

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#35003]
## What problem does this address?
Unlike to other editors in WordPress, saving menus / menus items can require multiple REST API requests. This means that saving can take some time. The save button should have some kind of indication that menu is being saved. 

## What is your proposed solution?
The save button should be disabled and wording should changed to "Saving". 

https://user-images.githubusercontent.com/237508/134161017-45ee45b1-6ffc-4956-9460-ee25c80c2b1d.mov

**Comment by karmatosed** [comment]
I 'think' there is a saving state for buttons we can use. We could for example use the same style as the saved button on publish. In that case, it has diagonal stripes and disables until publishing is done. This I would expect to work the same at least.

![2021-09-21 13 49 09](https://user-images.githubusercontent.com/253067/134173308-f41e1def-a5e8-4e4f-a69b-a13f24e14271.gif)

**Comment by spacedmonkey** [comment]
I like that! We should implement that.

**Comment by kathrynwp** [comment]
Closing this issue due to the Navigation Screen project being moved to [an inactive status on the feature projects page](https://make.wordpress.org/core/features/) in coordination with the project leads. (The developer documentation in the initial post are no longer accessible)

If this work is picked back up, issues can be revisited and reopened as needed. Thanks for pitching in on this early feature so the wider WordPress project could benefit from the lessons learned!
