### ISSUE TITLE
Information icon doesn't use the conventional icon

### ISSUE THREAD

**Issue by benoitchantre** [WordPress/gutenberg#3506]
## Issue Overview
![actual-information-icon](https://user-images.githubusercontent.com/1521015/32862345-1acf6cac-ca58-11e7-9f72-742d1a4ef725.png)

The icon actually used to trigger the information popover is not really in line with a [conventional information icon](https://thenounproject.com/search/?q=information&i=1388253).

It is also the same as the page icon from the menu but a with a slightly different meaning.

Gutenberg version 1.7

## Possible Solution
- use a conventional icon ("i" inside a circle)
![conventional-information-icon](https://user-images.githubusercontent.com/1521015/32862123-505ec7b0-ca57-11e7-81a7-48216ac1d0a7.png)

- use an icon to represent the content, maybe with a small information icon added
![content-icon](https://user-images.githubusercontent.com/1521015/32862263-dbf7ccd6-ca57-11e7-93a4-17d709077dec.png)

- eventually rename _Information_ to _Content structure_

**Comment by hedgefield** [comment]
I did not find this new icon fitting either. To me it says "pages" or "layers" or "overview". The info icon was better at this - it does give meta information about your post after all.

**Comment by benoitchantre** [comment]
Related PR: #3478

**Comment by jasmussen** [comment]
Although I support all the thinking that has gone into moving this icon to the top toolbar — it certainly is the right place for it — I'm personally not a super fan of having the icon sit where it is currently. (Also I agree it should be an (i) in a ring, which is why I just merged in such an icon). 

The question we have to ask ourselves is: do we need to see the word count so often that it deserves permanent top left placement? If yes, then we're good. If no, then perhaps we can look at showing this icon when _no block is selected_, and hide it by the formatting toolbar when a block is selected. 

Another option is to put the word count feature into the ellipsis menu — then it becomes a two-click operation.

Yet another option is to show the word count in the publish dropdown, however that's a _learnable_ feature, not very _discoverable_. 

For performance reasons, it would not be wise to show a live wordcount as you are typing. 

What other options could there be?

**Comment by mtias** [comment]
"Content structure" seems sensible as tooltip.

**Comment by benoitchantre** [comment]
> Do we need to see the word count so often that it deserves permanent top left placement?

I don't think it is that important to have that button top left placement. In most editing softwares, the button to get informations about the content is not located next to the primary buttons. It's not a tool, it's a button to display information.

I think it would be better to move this in the right side of the screen.

> What other options could there be?

- keep it as an icon, but move it before the preview button
- remove the icon and popover, display these infos in a _Content structure_ panel that could be the first panel

> For performance reasons, it would not be wise to show a live wordcount as you are typing.

Maybe It could be updated only when you stop typing after a reasonable delay.

**Comment by StaggerLeee** [comment]
Believe me nobody will use it and click on it, only by mistake.
It will just sit there as dead duck. Nice addition, but hide it properly and remove from default view..
