### ISSUE TITLE
Buttons for superscript and subscript

### ISSUE THREAD

**Issue by benoitchantre** [WordPress/gutenberg#3507]
## Issue Overview
Content editors don't have an easy way to use superscript and subscript.

Gutenberg version 1.7

## Possible Solution
As this type of formatting is applied only to a few letters, these buttons could be displayed only when the user selected some text.

**Comment by iseulde** [comment]
This is plugin territory. We also didn't have these buttons in the old editor.

**Comment by piettt** [comment]
Hello,

but it'll be a great thing to add it in gutenberg.

Regard.

**Comment by iseulde** [comment]
You can now use [this plugin](https://wordpress.org/plugins/advanced-rich-text-tools/) to add the buttons.

**Comment by benoitchantre** [comment]
Thank you at lot for this plugin @iseulde. I wanted to look at the source of your `index.js`, but it's a minified version. Could you add the unminified version? As noted in the WordPress Plugin Handbook, _code must be (mostly) human readable_.

**Comment by Swagatam1975** [comment]
> You can now use [this plugin](https://wordpress.org/plugins/advanced-rich-text-tools/) to add the buttons.

It just stopped working in the wordpress 5.2.

**Comment by Swagatam1975** [comment]
Gutenberg is supposed to be super advanced, but sadly we can't even work with subscripts which is one of the most basic features a text editor can have.

**Comment by corentin-gautier** [comment]
> This is plugin territory. We also didn't have these buttons in the old editor.

Strongly disagree with this, and the fact that it wasn't there before should not be taken into account. As it has been said before this is a very basic feature, so I think it should be a part of the core. Please reconsider adding this @benoitchantre ?

**Comment by Hochiss** [comment]
several buttons, incl. sub-/super-script, find& replace, insert media..., cannot be displayed using block editor at Gutenberg:
![weird buttons ](https://user-images.githubusercontent.com/36304198/70707920-a5997500-1cd9-11ea-9676-6cde66f9402d.png)

Is that a bug or setting issue, pls. help

**Comment by kkm000** [comment]
I'm sorry for speaking my heart out, guys, but there is about a light year distance between the promise of Gutenberg and all that blogging about how great and revolutionary it is, and this reply, which essentially reads _UI usability is none of our business._

## No. It is!

Please step off this narcissistic mirror, yes, Gutenberg is great in its foundation, but it's not the Best Humanity Achievement Ever. From the usability standpoint, it's probably somewhere in the lower third of all different Web editors I ever used. Any time I'll choose the most simplistic Google Docs over it. Web version of Microsoft Word beats it with a poke of its left pinkie. It really has an amazing potential, but please, I beg you, please one day stop marveling this God's handiwork, and **make it freaking useful to others**.

I'm a darn good software engineer. I've been one for 30 years. I opened the Codex and implemented one rich box extension. Guys, it was a disaster. One version, the symbols are in the SVG font, and next minor point they are constants in code. To hell with the icons. I was never able to add a keyboard shortcut to it. And if you'd tell me I'm just another idiot that does not know how to add a shortcut to a plugin extending your amazing editor, I will totally agree with you: almost everyone is an idiot in this sense, no argument here. It's a matter of definition the word “idiot.” I'm not in a bad company, after all.

I've read a lot of deeply philosophical writing on the foundational principles of the the block editor (and, let me reiterate, _I really think it's a great idea!_). But I've never seen a single damn piece of writing on the UX. Not. A. Single. One.

So, it looks like there is an abyss between how you perceive the new editor (because of its internal consistency and extensibility and beautiful internal machinery design based on the delicate and refined philosophy, and  how we the users see this half-baked, barely usable editor lacking most features any semi-decent editor written by a freshman as his coursework would have. And I think I understand why this abyss will be never mended: either the whole user community suddenly decides they do not need sub- and superscripts (very unlikely), and another... well, you see the point. Or don't. I don't care. 

I'm not positing a false dichotomy here. A piece of software is either useful enough to be used, or is being flung out of the window.

Look at Adobe Photoshop. It's not simple. It has an oh so steep learning curve. They say that anything can be done in it, and anything that can be done, can be done in more than one way. And they also say that if you use your mouse instead of finger-knotting keyboard chords, you are out of business. It's not only the artistry and experience that matters. It's how quick the user can do it.

“It's a plugin business”??? Bwa-ha-ha-ha!!! _Have you ever looked t wordperss.org?_ Do it please. If you recommend others to do that, do it too. Just once, but please look there. I hope that will be a sobering experience. There are over 9000 plugins that add sub- and superscripts to your blocks. Unfortunately, 8999 of them are either borked or brain-dead, and at least 1000 will mangle your setup to the point of restoring a backup. I have neither infinite lifetime nor infinite budget to try them freaking all!. Writing in plain HTML is quicker that with your wretched editor. Not simpler. Not more comfortable. Not beautiful, no, it's ugly. _Quicker._ You either care about the usability and your users, or... I should better stop, my limit of strong lexis is deep in red for today.  

The sad thing, and it's really, really sad, is that you, the Gutenberg team, managed to come up with really a great idea how to refurbish the 20-year old software to math the modern Web world, and then completely trashed its implementation, as if an idea itself is worthy more that the implementation. Sorry, it's not. An abstract idea is worth nothing, when it comes to anything “applied,” (as opposed to “pure”°, including software. You contributed so many first days of your remaining lives to implementing a half-cooked software based on it. And I'm really, really sorry. It seemed to have a great potential : (

Psssst. Steam pressure down, more time lost, now back to the battle with your Gutenberg.

**Comment by Wingo5315** [comment]
Since this was first proposed (and then closed) there has been a drop-down section added for features that aren't mainstream (used by 90% of users) but are still useful - such as inline images, inline code, etc.

I see no reason as to why we can't put this feature into core - we already have a working prototype (@ellatrix 's plugin) - and we already have similar features like inline images/code.

**Comment by ellatrix** [comment]
I agree

**Comment by ellatrix** [comment]
I agree

**Comment by ellatrix** [comment]
@kkm000 Posting comments like that doesn't help.

**Comment by kkm000** [comment]
@ellatrix, I do not understand what do you mean by “like that.”

To recapture, you told your users to, summarizing it simple, get lost and deal with usability issues by seeking a fix from a third party. I tried to convince you that implementation and usability of your product do matter, and significantly more so than a beautiful design or a deep philosophy under it. I read your message as a vague disagreement, but I do not understand with what points exactly are you disagreeing.

If by “like that” you mean that you disagree with the message wholesale, then the disagreement lies in basic tenets, and communication wanting a foundation is impossible. Otherwise, please clarify your point.

**Comment by ellatrix** [comment]
> To recapture, you told your users to, summarizing it simple, get lost and deal with usability issues by seeking a fix from a third party.

That's not summarising it simple. You completely rephrase what I said. I didn't tell anyone to get lost, I didn't tell anyone to deal with usability issues.

> I tried to convince you that implementation and usability of your product do matter, and significantly more so than a beautiful design or a deep philosophy under it. 

I don't get convinced with a list of remarks built on

> Please step off this narcissistic mirror [...]

etc. 

I think you know what I mean. 🙂 It's not nice.

**Comment by piettt** [comment]
I totally agree with @Wingo5315. I don't understand why it is not already in Gutenberg core.
We must use this plugin or this one [https://fr.wordpress.org/plugins/tinymce-advanced/](https://fr.wordpress.org/plugins/tinymce-advanced/)
And there is no "no breaking space"
I understand why some people continue with the classic editor !! For other people we must add it with a copy-paste.
Regard.

**Comment by piettt** [comment]
@kkm000 
you said " There are over 9000 plugins that add sub- and superscripts to your blocks" seriously what king of drug do you take ? ;-)  And yours posts are not very cool. Please stop to write here. Thank.

**Comment by mcsf** [comment]
@piettt, can I ask you to moderate your [comment](https://github.com/WordPress/gutenberg/issues/3507#issuecomment-619042056) where it suggests drug consumption? Thanks.

**Comment by mcsf** [comment]
@kkm000 — first off, I’ll be as factual and direct as I can. Your comment:

* amounts to venting in the lengthiest way you could;
* draws generalisations that border on the defamatory;
* is condescending and insulting;
* stems from the assumption that other parties involved, in particular @ellatrix, act in bad faith;
* posits where it should instead inquire. If you haven’t seen any writing on UX, then ask about it. There are plenty of resources;
* constructs a “us vs. them” relationship;
* claims, all the while, to hold the one truth and that the opinions behind it are unanimous;
* goes beyond insulting some direct contributors to Gutenberg and targets everyone (“brain-dead”?) who makes the Plugin Directory what it is;
* is not actionable.

We all have a right to feel frustrated about things.

We also all understand that not only mistakes happen, but errors in communication happen too. If two partners under a single roof get their wires crossed, what about a project made up of hundreds or thousands of contributors that stretch out not only through space but also through time and through our regional and personal backgrounds? It should be acknowledged as a miracle that we can collaborate.

We have a right to be frustrated. But we don’t have a right to take it out on the next person, especially when we don’t know the whole story. We all have the duty to construct, not destroy.

In addition:

* no one has made claims to a grandiose humanitarian achievement, nor to have finalised a vision;
* many have never taken the lack of super- and subscript support to conclude that the block editor is an utter failure;
* the initial conversation in this issue is 18 months old, and a lot of context can and has changed since then;
* @ellatrix made a quality plugin herself to address the issue in question, as she pointed out; she was true to her assessment in 2018 that plugins would do users a better service and built one, and I agree that this was a good assessment at the time;
* today, there is room for revision, which she has acknowledged.

Have you considered how hurtful your comment may have been for the person directly concerned? @ellatrix was graceful enough to merely point out that it wasn’t a helpful comment. Please reply in kind and consider the damage it may have done. When confronted, please don’t pretend that your comment was an honest argument (“I tried to convince you that […]”) when it was, in essence, an attack.

Comments can hurt, and, because contributors take feedback seriously, they can also consume an incredible amount of time. Please be considerate and constructive.

**Comment by piettt** [comment]
> 
> 
> @piettt, can I ask you to moderate your [comment](https://github.com/WordPress/gutenberg/issues/3507#issuecomment-619042056) where it suggests drug consumption? Thanks.

Yes, sorry about that.
