### ISSUE TITLE
Prompt users will lose changes by switching menus

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#35100]
## What problem does this address?

In the navigation screen, when user makes change to a menu can change the menu using the menu switcher. When switching menus, the changes you have already made to the first menu are lost. 

https://user-images.githubusercontent.com/237508/134580136-a1e89165-b858-4c96-824e-abc4507a96db.mov

## What is your proposed solution?

When there are unsaved changed in the post editor and user tries to navigate away, there shown this message. Maybe we do something similar in the navigation editor.

<img width="286" alt="Screenshot 2021-09-23 at 21 26 47" src="https://user-images.githubusercontent.com/237508/134579115-da219f58-5eff-4099-ac11-5bb6b480082d.png">

**Comment by getdave** [comment]
The pattern in the Site Editor is for the changes to be preserved and then when you hit "Save" it shows you which templates you've edited (including ones you are not currently viewing). You can then pick which ones to save - defaulting to all of them.

We could do the same with Menus. Default to preserving changes and then asking the user which ones they want to save.

**Comment by Mamaduka** [comment]
Here is the issue for multi-entity saving enhancement #31813.

**Comment by kathrynwp** [comment]
Closing this issue due to the Navigation Screen project being moved to [an inactive status on the feature projects page](https://make.wordpress.org/core/features/) in coordination with the project leads. (The developer documentation in the initial post are no longer accessible)

If this work is picked back up, issues can be revisited and reopened as needed. Thanks for pitching in on this early feature so the wider WordPress project could benefit from the lessons learned!
