### ISSUE TITLE
Adding all pages in Navigation screen doesn't add child pages

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#35103]
### Description

When creating a menu in the Navigation screen by clicking "Add all pages", child pages do not get added to the menu.

### Step-by-step reproduction instructions

1. Make sure you have at least one page that is a child of another page.
2. Create a new menu in the Navigation screen, and click "Add all pages".
3.  Verify that the child page(s) weren't added to the menu.

### Environment info

Gutenberg trunk, all browsers etc.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kathrynwp** [comment]
Closing this issue due to the Navigation Screen project being moved to [an inactive status on the feature projects page](https://make.wordpress.org/core/features/) in coordination with the project leads. (The developer documentation in the initial post are no longer accessible)

If this work is picked back up, issues can be revisited and reopened as needed. Thanks for pitching in on this early feature so the wider WordPress project could benefit from the lessons learned!
