### ISSUE TITLE
Block Gap css variable is loaded in the editor for some classic themes

### ISSUE THREAD

**Issue by stacimc** [WordPress/gutenberg#35197]
### Description

Related: #34452

The generated CSS variable for the [block gap spacing config](https://github.com/WordPress/gutenberg/blob/fdf905725852ec5f3064828c968f03e8f62312f6/lib/theme.json#L244) is being added to the stylesheet for some classic themes, only in the editor.

<img width="264" alt="Screen Shot 2021-09-28 at 3 47 36 PM" src="https://user-images.githubusercontent.com/63313398/135175995-9a6dcf59-db03-42cd-ae7a-f9fa32306b56.png">

The styling rules that pick it up and utilize it for layout spacing are _not_ generated, but the existence of the global `--wp--style--block-gap` variable at all causes backwards compatibility issues for blocks that opt into the Gap block support or otherwise make use of the variable in their CSS. For example, this kind of styling rule anticipates that `--wp--style--block-gap` will be undefined in classic themes, allowing fallback to a default value:

```
margin-left: var(--wp--style--block-gap, 2em);
```

Instead, the global 24px gap is picked up in the editor, and the fallback value is picked up on the frontend.

Themes where I can reproduce the bug: Twenty Twenty One, Seedlet
Themes where I cannot reproduce: Twenty Twenty, Maywood

### Step-by-step reproduction instructions

1. Activate the Twenty Twenty One or Seedlet theme
2. In a new post, insert a Columns block with 33/33/33 split.
3. Inspect the center Column in the editor. You should see that `--wp--style--block-gap` is defined and is being picked up by this column's styles (so the left margin is 24px)
4. View the post on the frontend and inspect the center Column again. You should see that the same style rule is applied, but `--wp--style--block-gap` is no longer defined, so the fallback `2em` is used for the margin.

### Screenshots, screen recording, code snippet

Styles in the editor:
<img width="800" alt="Screen Shot 2021-09-27 at 4 06 58 PM" src="https://user-images.githubusercontent.com/63313398/135176849-4182b986-a9a6-4310-b093-4fcece4c35f5.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by stacimc** [comment]
This isn't terribly noticeable with the Columns block, because it only results in a slightly smaller gap between columns on the frontend versus the editor. I noticed this when trying to add the Gap block support to the Buttons block #34546, where it is much more apparent with rules like this:

```
// 0.5em is the current column-gap, kept for backwards-compatibility.
column-gap: var(--wp--style--block-gap, 0.5em)
```

On themes with the issue, in the editor the column-gap between buttons more than doubles in size, which can easily cause buttons to overflow to the next row and appear significantly different from the frontend.

**Comment by andrewserong** [comment]
Thanks for writing this up @stacimc! I think the culprit here is that the `block_styles` styles get rendered when a theme opts in to the experimental link color via `add_theme_support( 'experimental-link-color' );`. It looks like [TwentyTwentyOne does that here](https://github.com/wordpress/wordpress-develop/blob/ecad6ae28cf0b9755945d1d6a09e807a43fba6a2/src/wp-content/themes/twentytwentyone/functions.php#L333-L333) and [Seedlet does it here](https://github.com/Automattic/themes/blob/78fc9b086139198a18e76a01a0569aa0ca1cf64a/seedlet/functions.php#L257-L257). [Here's the conditional](https://github.com/wordpress/gutenberg/blob/trunk/lib/global-styles.php#L146-L146) where `global-styles.php` causes the block styles to be loaded.

I wonder if a solution might be for us to see if we can guard generating the blockGap variable behind a check for the presence of the `settings.spacing.blockGap` setting? Possibly by extending `get_block_classes` to also accept the settings nodes, and then do the check in get_block_classes before calling `compute_style_properties`? Or, extend `compute_style_properties` to check settings, too?

**Comment by andrewserong** [comment]
I've put together a PR looking at one particular way to try to handle it in https://github.com/WordPress/gutenberg/pull/35209. Very happy for feedback on whether it looks viable!
