### ISSUE TITLE
Navigation Editor: Unexpected behavior when reloading menu with placeholders

### ISSUE THREAD

**Issue by gwwar** [WordPress/gutenberg#35271]
### Description

If we create a menu with placeholder links, save, then reload the menu we'll see some inconsistencies:

- Tag, Category and Custom placeholders look correct
- Post and Page placeholders render as items like `#474 (no title)` (the menu id created)
- Submenu placeholders disappear

We do show a validation error on save, so I was also surprised to see that the menu serialized. (Overall it probably is friendlier to allow saving, but we may want to make the warning a bit clearer).

<img width="675" alt="CleanShot 2021-09-30 at 11 41 36@2x" src="https://user-images.githubusercontent.com/1270189/135512511-de6c0b09-2127-4eb9-a872-a70ebdcd6e0c.png">

| Placeholders after reload | Published view |
|-----|-----|
| <img width="706" alt="CleanShot 2021-10-05 at 10 46 41@2x" src="https://user-images.githubusercontent.com/1270189/136075909-9e21a6d2-3fb6-448a-a30b-27461467aa37.png"> | <img width="503" alt="CleanShot 2021-10-05 at 10 46 46@2x" src="https://user-images.githubusercontent.com/1270189/136075941-129350e0-b0f4-49d3-b2a3-c795e7c2209d.png"> |

### Step-by-step reproduction instructions

1. Visit the Gutenberg experiments page `/wp-admin/admin.php?page=gutenberg-experiments` and enable the Navigation Screen
2. Visit `/wp-admin/admin.php?page=gutenberg-navigation` and create a new menu
3. Open the global inserter (Blue plus button in top left)
4. Add all block types from the inserter
5. Save
6. Reload the page
Expected: menu doesn't save OR placeholders appear as they did before
Actual: See video/image

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1270189/135513300-4ecbaa76-b236-478f-8663-80f9c519bee1.mp4

### Environment info

Gutenberg trunk (d78bbc84ecb844245d1751ac36e21dbda92fef57)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by gwwar** [comment]
So looking at the endpoint code, I think it's reasonable to enforce a url/title for a custom link, say (we're linking directly to WordPress.org). I think the problem we're running into here, is that **we also assign the "custom" type for empty  placeholder links** that we haven't decided to pick anything for yet. (Kind/Type isn't specified yet either). This is exacerbated by recent behavior changes to allow direct links in the inserter too in https://github.com/WordPress/gutenberg/pull/34899. If we save these empty placeholders, they will be visible in the published view.

In the spirit of aiming for a lighter navigation block experience https://github.com/WordPress/gutenberg/issues/34041, what do folks think about changing the direct insert links from custom links to Post Type in the navigation editor. (Alternatively we could try to serialize non-specified placeholders as page placeholders but that may be confusing.)

https://github.com/WordPress/gutenberg/blob/1f75f8f6f500a20df5b9d6e317b4d72dd5af4ede/lib/class-wp-rest-menu-items-controller.php#L415

| explicit custom link | attributes set |
|-----|-----|
| <img width="515" alt="CleanShot 2021-10-05 at 11 16 36@2x" src="https://user-images.githubusercontent.com/1270189/136080284-807d1967-7afa-4554-9719-cf15adbe824d.png"> | <img width="984" alt="CleanShot 2021-10-05 at 11 16 59@2x" src="https://user-images.githubusercontent.com/1270189/136080515-0658dc34-115f-42c2-b556-c24e73ab3e95.png"> |

https://user-images.githubusercontent.com/1270189/136081476-6b3be124-2851-4f94-81a4-bd532484fd60.mp4

**Comment by tellthemachines** [comment]
> In the spirit of aiming for a lighter navigation block experience #34041, what do folks think about changing the direct insert links from custom links to Post Type in the navigation editor. (Alternatively we could try to serialize non-specified placeholders as page placeholders but that may be confusing.)

Given these blocks are now inserted directly, I don't think we should restrict them to a type such as Post or Page, because that won't allow users to search for other types (if we restrict to Post users won't be able to search for pages, if we restrict to Page they won't be able to search for categories, etc.); the default was set to custom link to allow maximum flexibility.

I'm not sure exactly what's happening, but I'd expect the missing text we're setting [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/navigation-link/edit.js#L524) to be respected for all cases, not just taxonomies. 

Fwiw my testing shows post and page types a bit different from yours after reload: instead of `#474 (no title)` I'm just seeing "Untitled". But if I assign the menu a location, the menu items will display as "Untitled" on the front end, and a link is generated using the menu item number as if it were a post id, e.g. `http://localhost:8888/?p=474`.

Another interesting thing I'm noticing is that, when an empty custom link or submenu is present, post, page and taxonomy type links are multiplied on reload if we press "Save" multiple times. So, if I insert one custom link, one page and one category, and press "Save" three times, on reload I see three pages and three categories. Not sure if this is related at all 😕

**Comment by gwwar** [comment]
I'm pretty flexible with what folks decide to go with, provided that the behavior is consistent. 👍  I think these cases might be a little easier to debug if there's a code-view equivalent in the navigation editor that shows the menu item serialization, but otherwise it should be doable by observing the API requests. 

> So, if I insert one custom link, one page and one category, and press "Save" three times, on reload I see three pages and three categories. Not sure if this is related at all

Sounds like a similar category issue. It's mostly likely due to to logic here:

https://github.com/WordPress/gutenberg/blob/c8148c289d364ea18fa883fec877e5451d9d91cb/packages/edit-navigation/src/store/actions.js#L196-L204

I'm guessing that we send the same batch request 3 times. This can probably be avoided with optimistic updating on the client (where we assume the save worked, and only modify state otherwise if we see an error response).

**Comment by Mamaduka** [comment]
Closing the issue since the editor is no longer maintained and has been removed from the project.
