### ISSUE TITLE
Widget Block theme editor styles ignored

### ISSUE THREAD

**Issue by antonyjsmith** [WordPress/gutenberg#35320]
### Description

I'm using add_editor_style to enqueue some custom styling to the block editor, I cannot target elements to apply styling, font's seem to be respected - I'm unsure how or why - but specific stying for bocks which works fine in the post editor is not reflected in the widget editor.

Most annoying of all I cannot seem to change the main widget container max-width.

### Step-by-step reproduction instructions

add_editor_style and add_theme_support, add a style sheet and some styles. e.g

```
.wp-block[data-type="core/widget-area"] {
	max-width: 1200px !important;
}
```

Has no effect

### Environment info

Wordpress 5.8, without Gutenberg Beta plugin
All browsers i.e Vivaldi, Firefox, Safari, Chrome
Desktop OS X Catalina

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by antonyjsmith** [comment]
Does anyone know if this is a bug or not? I've not come across anything even referring to styling this page, I'm pretty sure I've done a comprehensive search, there isn't a reference in the block editor handbook and neither have I seen any example in different themes.

Really don't know what to do and these undocumented, seeming incomplete changes pushed to core are really starting to wear me down!

**Comment by noisysocks** [comment]
Hi @antonyjsmith! The CSS you shared looks right to me. I think what probably is the issue is that you're using `add_editor_style` which will automatically prefix all your CSS rules with `.editor-styles-wrapper` so that the CSS will only affect elements that are _within_ the widget area. This is because editor styles are supposed to style content that appears on the frontend and the widget area containers do not appear on the frontend.

Try using a regular CSS style enqueue by hooking into `admin_print_styles` and calling `wp_enqueue_style`.

https://developer.wordpress.org/reference/functions/wp_enqueue_style/

**Comment by antonyjsmith** [comment]
Thanks for the feedback, I've not tested so unsure if it works since we decided to abandoned Wordpress as the CMS for the project anyway!
