### ISSUE TITLE
Embedding mobile Twitter URLs results in embed failure

### ISSUE THREAD

**Issue by dcalhoun** [WordPress/gutenberg#35357]
## Description
When embedding a Twitter URL in the block editor, a preview is not successfully rendered if the URL used is a _mobile variant_, i.e. https://mobile.twitter.com. A variant of this unexpected behavior happens in both the native mobile and web editors. 

## Step-by-step reproduction instructions
1. Open the block inserter. 
2. Insert a Twitter Embed block. 
3. Paste a _mobile_ Twitter URL, e.g. https://mobile.twitter.com/rauchg/status/807626710350839808
4. Dismiss the block settings bottom sheet. (Native Mobile editor only)

## Expected behaviour
The Embed block displays a preview of the tweet. 

## Actual behaviour
The Embed block does not display a preview of the tweet, but instead:

- Web editor: converts to Paragraph block containing the URL text. 
- Native editor: displays "Unable to embed media." 

## Screenshots or screen recording (optional)

| Native Mobile | Web |
| - | - |
| ![Native mobile block editor displays a successful and failed embed for the same Tweet for traditional and mobile URLs respectively](https://user-images.githubusercontent.com/438664/136038236-5c422b9c-971a-4206-be9f-b815d37d3edb.PNG) | ![Web block editor displays a successful and failed embed for the same Tweet for traditional and mobile URLs respectively](https://user-images.githubusercontent.com/438664/136039145-896be90f-3954-4a3d-8137-b38409cbcc19.png)

## WordPress information
- WordPress version: WordPress.com
- Gutenberg version: v11.6.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: iPhone SE
- Operating system: iOS 15.0
- WordPress app version: 18.4

**Comment by fluiddot** [comment]
I think this is caused because the `oembed` endpoint doesn't include the word `mobile` in the regex patterns for Twitter URLs (example: `#https?://(www\.)?twitter\.com/`):

**Regex patterns for Twitter URLs:**
https://github.com/WordPress/wordpress-develop/blob/f2d146d3f1ebd5661af2efd3099b0c988df538c8/src/wp-includes/class-wp-oembed.php#L67-L72

**Comment by hypest** [comment]
👋 @dcalhoun , I tried the mobile URL https://mobile.twitter.com/rauchg/status/807626710350839808 on https://wordpress.org/gutenberg/ and WPCOM's Simple site Gutenberg editor and it failed to produce in both cases. Gives me a `Sorry, this content could not be embedded.` on .org's Gutenberg, and immediately falls back to paragraph block on (see video below). My WPCOM site is on the Intergalactic2 theme.

https://user-images.githubusercontent.com/1032913/136518888-58055ca1-f780-496a-b233-0d47d809173c.mov

I think I'd categorize this as an "enhancement" ticket, if it ends up being theme related 🤔

**Comment by fluiddot** [comment]
> I think I'd categorize this as an "enhancement" ticket, if it ends up being theme related 🤔

Not sure if this is a theme-related issue, looks like on WP.com sites the embed failures are treated differently than from self-hosted sites, but in both cases, the embedding operation fails.

**Comment by dcalhoun** [comment]
> [...] it failed to produce in both cases. Gives me a `Sorry, this content could not be embedded.` on .org's Gutenberg, and immediately falls back to paragraph block on (see video below).

@hypest unless I am misunderstanding, I believe you described the same behavior I attempted to capture for the web editor. It seems my ticket description just needs to be updated to be more clear. I do not perceive this to be theme related, as we have now reproduced it with multiple themes. 

- Web editor: converts to Paragraph block. 
- Native editor: displays "Unable to embed media."

**Comment by hypest** [comment]
🤦‍♂️ I think you're right David! When I saw the "web" screenshot (https://user-images.githubusercontent.com/438664/136039145-896be90f-3954-4a3d-8137-b38409cbcc19.png) I seem to only focus on the succeedding preview, interpreting it as "ah, the web is able to produce a preview". Sorry for not paying good attention to the description.

About the issue per se, if the expected behavior is to indeed support the mobile URL variant, then it starts to look like a backend issue (as Carlos mentioned about the oembed endpoint). Then again, it looks like the mobile and web Gutenberg (on .org) handles this quite gracefully by displaying an error message. For the .org side of things, this doesn't feel like an issue for mobile and at best, it's an enhancement ticker, right?

For the WPCOM side, that indeed is a mismatch of bahavior from the mobile app but perhaps the better place for such a ticket is gutenberg-mobile's repo, not the Gutenberg repo. WDYT about moving this there, or splitting it into an enhancement ticket here (to add support for the mobile URLs) and a "misalignment" ticket in gutenberg-mobile?

**Comment by dcalhoun** [comment]
> About the issue per se, if the expected behavior is to indeed support the mobile URL variant, then it starts to look like a backend issue (as Carlos mentioned about the oembed endpoint). 

@hypest agreed. 

> Then again, it looks like the mobile and web Gutenberg (on .org) handles this quite gracefully by displaying an error message. For the .org side of things, this doesn't feel like an issue for mobile and at best, it's an enhancement ticker, right?
>
> For the WPCOM side, that indeed is a mismatch of bahavior from the mobile app but perhaps the better place for such a ticket is gutenberg-mobile's repo, not the Gutenberg repo. 

I would agree there are now two issues from unmet expectations: 

1. Mobile Twitter URLs are valid embeds. 
2. Invalid embeds should have similar outcomes in both the web and native mobile editors. 

> WDYT about moving this there, or splitting it into an enhancement ticket here (to add support for the mobile URLs) and a "misalignment" ticket in gutenberg-mobile?

Rephrasing this issue to be a feature request for mobile Twitter URL support sounds good to me. 👍🏻 

In regards to a new bug issue for the mobile editor, I might argue that the mobile experience is better as it partially explains why the embed does not appear, whereas the web editor automatically converts the embed to a paragraph block. If you agree, then the bug issue would be for the web and presumably should reside in this repo. WDYT? 

| Native Mobile | Self-Hosted Web | .com Web |
| - | - | - |
| ![Native mobile editor provides error message and convert option](https://user-images.githubusercontent.com/438664/136857426-2a46885a-8dca-4ad8-886a-9e70e35e3152.jpeg) | ![Self-hosted editor provides error message and convert option](https://user-images.githubusercontent.com/438664/136857445-12f54964-71e5-4f40-b55c-099addbc8983.png) | ![.com web editor auto-converts invalid embed to paragraph text](https://user-images.githubusercontent.com/438664/136857792-8d395e5e-b4c4-401b-bd9e-bad75040fd74.png) |

**Comment by hypest** [comment]
> In regards to a new bug issue for the mobile editor, I might argue that the mobile experience is better as it partially explains why the embed does not appear, whereas the web editor automatically converts the embed to a paragraph block. If you agree, then the bug issue would be for the web and presumably should reside in this repo. WDYT?

Ah, I see your point, and thanks for the annotated screenshots! I don't have the full context about the WPCOM's flow and since this touches more on the design side of things, @iamthomasbishop can you help with this? Looks like there's a misalignment between WPCOM's and the mobile app in how they handle the mobile-URL variant. Can you find the right place to host this discussion? Thanks!

**Comment by kyleaparker** [comment]
> since this touches more on the design side of things, @iamthomasbishop can you help with this? Looks like there's a misalignment between WPCOM's and the mobile app in how they handle the mobile-URL variant. Can you find the right place to host this discussion?

I agree that the way native mobile and self-hosted are handling this is a better user experience. I could try to start a discussion or alternatively could we open an issue somewhere to propose including the same error handling on .com web? It may just be an oversight, or there may already be discussion/issues about this.

**Comment by pablohoneyhoney** [comment]
Neat conversation into these details! 

I’m not sure if there are current discussions about this in particular but we had comments on how placeholders (for clarity: the empty block state) need to evolve.

I’ve reproduced the embed issue above and it works similarly in a hosted and self-hosted environment, at least for me. This is something it’s been explored in P2 as well, since we need to provide more natural ways to embed external links and content.

This is what I see in hosted:

![hosted](https://user-images.githubusercontent.com/25516611/138202896-81fb4d0e-a586-4c68-811b-c6871ff48fa8.gif)

And self-hosted:

![self-hosted](https://user-images.githubusercontent.com/25516611/138202920-feeb16e8-51b0-4dcb-950a-b566dc207615.gif)

Functionally, there are two ways to embed: simply paste a link, or add an embed block to drop the link in. So they could already have distinct ways of highlighting a possible issue. Currently both cases surface the block placeholder and display an almost invisible notice. It’s kind of abrupt to pop the placeholder when I try to simply paste a link (first case). Provided this is something fairly simple from a user standpoint, the actions (4!) in the placeholder error state are abusive and create an unnecessary cognitive load.
Furthermore, I think the placeholder itself needs love and the notice needs to be more noticeable, no pun intended 😄  And the text and elements can be reduced heavily.

More granularly:

- If I paste a link it could simply paste the link, and if richer signals are available (from a video, a tweet, etc.), then do display that added content, providing awareness to the user (in context of the block) that you can turn that off to become a simple link (similarly to how Slack does it by closing the unfurl keeping the plain link).

- If I add an embed block and then paste an URL, the result state of that placeholder should vary from the resting state. We’d need to reduce greatly the placeholder UI to focus on the validation of what’s happening. There’s some beauty to the simplicity of the state in the app version, even though the flow to edit the URL is too obscure (see image below). Or mimic the behavior of the first case, whereas even from the embed block we return a plain link when the unfurl can’t happen. In this case a simple snackbar noticing what just happened could be enough.

![image](https://user-images.githubusercontent.com/25516611/138202984-0c94ef36-5558-4247-9527-4fc0d4c648fd.png)

**Comment by kyleaparker** [comment]
> I’ve reproduced the embed issue above and it works similarly in a hosted and self-hosted environment, at least for me. This is something it’s been explored in P2 as well, since we need to provide more natural ways to embed external links and content.

I'm not seeing the embed error on self hosted, for me it's auto converting to a plain text paragraph. Could this be a bug, or was it an intentional design decision? 

> Furthermore, I think the placeholder itself needs love and the notice needs to be more noticeable, no pun intended 😄 And the text and elements can be reduced heavily.

💯 this state could be drastically simplified. Is this something that's currently in the works?

**Comment by hypest** [comment]
👋 @kyleaparker and @dcalhoun ! Just checking in about the discussions progress around this ticket. Have we reached some consensus perhaps?

**Comment by kyleaparker** [comment]
>  Mobile Twitter URLs are valid embeds.
  
Agreed with this and ideally we can find a way for mobile Twitter embeds to work.
 
> Invalid embeds should have similar outcomes in both the web and native mobile editors.

I'm sure continued improvements could be made, but what we currently have on mobile feels like it sets the right expectations.

**Comment by dcalhoun** [comment]
After reviewing this thread again and discussing with @kyleaparker, I am closing this issue in favor of three new issues that address the topics that arose within this original issue:

* [Support embedding Mobile Twitter URLs](https://core.trac.wordpress.org/ticket/54414#ticket)
* https://github.com/WordPress/gutenberg/issues/36377
* https://github.com/Automattic/wp-calypso/issues/57916

My hope is that by splitting the issues, the relevant teams can discuss/plan/prioritize the work as they deem appropriate. However, please feel free to re-open this issue if needed.
