### ISSUE TITLE
Delete at the beginning of newly created quote deletes the quote, not the first charater.

### ISSUE THREAD

**Issue by tomalec** [WordPress/gutenberg#35388]
### Description

I convert a paragraph of text (pasted markdown, or just any text) to a quote block, by adding `> ` at the beginning. Then once the block is converted, I continue expecting the block would behave as if it has been before, and I placed the caret at the beginning. So I press <kbd>del</kbd> I'd expect the first character after the caret to be removed.

Then unexpectedly the quote block is converted back to a paragraph. This is the action I'd expect on undo or backspace. <kbd>del</kbd> deletes what's after not before the caret.

In Notion and other rich text editors, it behaves as I'd expect.

### Step-by-step reproduction instructions

1. Open the editor, like https://wordpress.org/gutenberg/
2. Move caret to the beginning of a paragraph.
3. Type `> `.
4. Once the block is converted press press <kbd>del</kbd>.
5. Continue typing.the 

### Screenshots, screen recording, code snippet

![Screen-cast of the broken behavior in Gutenberg](https://user-images.githubusercontent.com/17435/136159828-3adca55f-fb32-4961-ac37-51e9ef2035cb.gif)
![Screen-cast of the correct behavior in Notion](https://user-images.githubusercontent.com/17435/136160999-e804846a-f644-4b87-891b-6fc138c25856.gif)

### Environment info

- WordPress 5.9
- Chrome, Firefox
- Ubuntu 20.04

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ellatrix** [comment]
You're right, `Delete` shouldn't undo it.

**Comment by mhkuu** [comment]
I found that this is a more generic issue with transforms through prefixes, as I can also reproduce it with creating a list block by prepending `* ` or `- `. I tracked it down to `packages/block-editor/src/components/rich-text/use-undo-automatic-change.js` where we allow the automatic change to be undone on pressing the delete, backspace, and escape button. I'll create a PR to remove the `DELETE` key from the guard so that only backspace and escape triggers the undo 👍
