### ISSUE TITLE
RSS Block and Let's encrypt

### ISSUE THREAD

**Issue by Arskrigitsioniets** [WordPress/gutenberg#35484]
As I suspect, due to a [worldwide known problem](https://www.securityweek.com/expired-lets-encrypt-root-certificate-causes-problems-many-companies) with Let's Encrypt SSL, which occurred on 30th September, I have a problem with RSS block and my RSS feed from my site using this SSL.

My RSS Feed is: https://forum.strategycon.ru/index.php?action=.xml;sa=recent;limit=10
When I try to put it in RSS Block in Gutenberg, I get the following error:
**WP HTTP Error: cURL error 60: SSL certificate problem: certificate has expired**

While my site itself works fine and there's no problem with SSL. I think,

I think Gutenberg RSS block should be updated to work despite this Let's Encrypt situation if the problem is actually connected with it (a test is needed).

**Comment by skorasaurus** [comment]
From brief research, this appears to be an issue with WordPress Core, ref: https://core.trac.wordpress.org/changeset/51883/
and https://core.trac.wordpress.org/ticket/50828 https://core.trac.wordpress.org/ticket/54207

I'm closing for now because this is being tracked in WordPress Core and any fixes to this would be implemented not in Gutenberg but WordPress core.
