### ISSUE TITLE
Pressing enter after auto-inserting a period in a Quote inserts an invisible new line on Android

### ISSUE THREAD

**Issue by dcalhoun** [WordPress/gutenberg#35573]
## Description
When adding text to a new Quote block, if a period is auto-inserted by pressing two spaces at the end of a word, then pressing <kbd>Enter</kbd> does not display a new line. Pressing <kbd>Enter</kbd> a second time splits the block, as expected, but the aforementioned new line is still not visible. 

If at this point, one presses <kbd>Delete</kbd>, the currently focused Paragraph block is correctly merged into the Quote block. _The missing new line then becomes visible_ in the Quote block. 

This issue occurs in the latest WPAndroid 18.4-rc-2 release. I did not narrow down the specific point the bug was introduced, however it does occur in WPAndroid 17.0 and does _not_ occur in WPAndroid 15.0. This issue also does not occur on iOS. 

## Step-by-step reproduction instructions
1. Launch the block editor. 
2. Insert a Quote block.
3. Type text followed by two spaces so that a period is auto-inserted, e.g. `A great statement. `
4. Press <kbd>Enter</kbd>.

## Expected behaviour
A _visible_ new line is inserted into the Quote block. 

## Actual behaviour
An _invisible_ new line is inserted into the Quote block. 

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/438664/137132658-be66e801-6d7a-4c91-9bec-92c83149de16.mp4

## WordPress information
- WordPress version: WordPress.com
- Gutenberg version: 11.6.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Samsung Galaxy S20
- Operating system: Android 11
- WordPress app version: WPAndroid 17.0

**Comment by hypest** [comment]
I can't seem to be able to reproduce on WPAndroid 18.2-rc-3 (on Pixel 2XL, Android 11, Gboard 10.9.05.387080390-release-arm64-v8a). I also tried v17.0 and the latest beta at the time of writing (v18.4-rc-2) and cannot reproduce.

I wonder, since v17.0 is a bit old at this point @dcalhoun , can you also give 18.4-rc-2 a try?

Also, I noticed in the video that you seem to have needed to tap `Enter` twice actually, right? Maybe what you experience is not a "block shouldn't have split" issue but rather, "Enter should have added a newline and it doesn't". The second `Enter` seems to kinda have done it's job OK, which is to "split on an empty line". Feels like the internal state of the block doesn't match the rendered state somehow. WDYT?

**Comment by dcalhoun** [comment]
> I wonder, since v17.0 is a bit old at this point @dcalhoun , can you also give 18.4-rc-2 a try?

Sorry for the confusion. This issue does happen on the latest beta release, I was merely attempting to reference the _oldest_ point where I found the behavior occurring. I will update the description for improved clarity. 

> Also, I noticed in the video that you seem to have needed to tap `Enter` twice actually, right? Maybe what you experience is not a "block shouldn't have split" issue but rather, "Enter should have added a newline and it doesn't". The second `Enter` seems to kinda have done it's job OK, which is to "split on an empty line". Feels like the internal state of the block doesn't match the rendered state somehow. WDYT?

You are 100% correct. Your proposed description is much more accurate. Thank you for the consideration and thought you put into this explanation. I will update the description to be more accurate.

**Comment by fluiddot** [comment]
I couldn't reproduce the period auto-inserting until realizing that it's required to enable the typing option "Double tap space bar to add period" in the keyboard configuration 😅, I'd like to share it here in case it helps.

<img src=https://user-images.githubusercontent.com/14905380/143613512-428dc2fc-4014-4f90-8eb2-aba623e263fa.jpg width=300>

**Comment by fluiddot** [comment]
I ran some investigations of the issue, and I spotted that this is caused by a condition on Aztec that prevents updating the internal text value due to receiving an event count lower than expected:

https://github.com/WordPress/gutenberg/blob/628e956b1eadcfb82dc36bf21e418ae436ae4ac9/packages/react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecManager.java#L220

When pressing enter after auto-inserting a period, the `eventCount` value passed is lower hence, the condition is not fulfilled and the `setTextfromJS` function is not called which updates the internal value. This means that the new line (`<p></p>`) is not created, as the issue description states:

<img width="751" alt="Screenshot 2021-11-26 at 19 30 40" src="https://user-images.githubusercontent.com/14905380/143619932-4f126aa5-1adb-4d68-b23b-c448957e5bde.png">

However, when pressing enter in any other case, the `eventCount` is higher in the order of one hundred:

<img width="753" alt="Screenshot 2021-11-26 at 19 34 26" src="https://user-images.githubusercontent.com/14905380/143620150-2f3da721-795f-483b-929f-ef05cd177e01.png">

I was surprised by the huge difference in the count, so I checked the `RichText` component and noticed that the function `manipulateEventCounterToForceNativeToRefresh` might actually increase by one hundred the event count, matching the previously described case.

https://github.com/WordPress/gutenberg/blob/80112e467d7ff6e537d7229e1aae559a518c2a92/packages/rich-text/src/component/index.native.js#L701

I traced the call when pressing enter, to understand what's the difference between both cases (auto-inserting period vs regular case), and I identified that it's triggered from the following line for the regular case:

https://github.com/WordPress/gutenberg/blob/80112e467d7ff6e537d7229e1aae559a518c2a92/packages/rich-text/src/component/index.native.js#L745

**For future reference, we should check what conditions from the following code are different between both mentioned cases, in order to find the culprit of the event count discrepancy:**

https://github.com/WordPress/gutenberg/blob/80112e467d7ff6e537d7229e1aae559a518c2a92/packages/rich-text/src/component/index.native.js#L731-L734

**Comment by mtias** [comment]
Is this still relevant with the new shape of quotes?

**Comment by dcalhoun** [comment]
> Is this still relevant with the new shape of quotes?

Great call out. Thank you! 

I am unable to reproduce this issue in WordPress mobile app 20.4-rc-1, presumably due to the new usage of inner blocks within the Quote block. Closing this as resolved, but feel free to reopen if someone believes we still need this issue.
