### ISSUE TITLE
Transforming quote with citation to paragraph should create two paragraphs

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#3559]
If you have a quote with a citation, and transform this to paragraph, you get a paragraph of the quote, and an empty blockquote with just the citation:

![quote transformation](https://user-images.githubusercontent.com/1204802/33011325-f7c5c344-cddd-11e7-8624-6088f53da3e8.gif)

Would it be nicer if this transformed into two paragraphs instead?

The inverse should not be true though — selecting two paragraphs and transforming into a quote should have a quote with two paragraphs and no citation.

**Comment by youknowriad** [comment]
What about a quote with multiple paragraph and a citation? Should it be three paragraphs or a paragraph and a quote? I suppose three paragraphs for consistency with the proposed behavior here.

**Comment by jasmussen** [comment]
> What about a quote with multiple paragraph and a citation? 

I lump it in with transforming to and from a list. 5 paragraphs turn to 5 list items in one direction, and back to 5 paragraphs the other direction.

For the quote, 3 paragraphs turn to a blockquote with 3 paragraphs. If you add a citation and transform back, I think it makes more sense to get 4 paragraphs than 3 paragraphs and an empty quote with a citation.

Is it technically really tricky?

**Comment by youknowriad** [comment]
> https://github.com/WordPress/gutenberg/pull/3519

No it's not (not until we use nested blocks :P)

**Comment by jasmussen** [comment]
> No it's not (not until we use nested blocks :P)

;) No nesting!

**Comment by jorgefilipecosta** [comment]
Thank you for your report @jasmussen this should be fixed with the merge of https://github.com/WordPress/gutenberg/pull/3802.

**Comment by jasmussen** [comment]
Hooray! Thank you.

**Comment by HJMeyer** [comment]
Sorry, but exactly this behaviour was the first stumbling stone I experienced when I tested Gutenberg for the first time today. I tried to transform the quote + citation of Matt Mullenweg, 2017 to a paragraph, and then to transform it back. First step: I click on icon ‘paragraph’: the quote and the citation become to two separate paragraphs. Then I click on the icon for ‘quote’: I get two quotes, each with empty citation field. 
This is not what I expected when I read: “the structure of the quote is protected even if you select, modify, or remove the source. It’s always easy to add it back.“ This promise is not met, because the structure is gone. This is not intuitive. If it is possible to make two blocks from one, it must be possible to merge to blocks to one.
It would be easy if you added an icon for transforming a paragraph to a citation (working only if the previous block is a quote).
