### ISSUE TITLE
Custom Font Size: add tooltip to button

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#35699]
The slider icon to show more in typography is very confusing because it doesn't have a tooltip and also isn't that clear as far as iconography goes to what it means.

![2021-10-15 22 45 23](https://user-images.githubusercontent.com/253067/137556945-7ab6420d-95b6-4da2-82c6-c4ca459ef06d.gif)

Once you find it, then you understand however the initial discovery is really hard to work out.

As a side note, having so many things hiding behind icons is making the interface really harder to use each time that happens so we perhaps want to reduce not increase where doing this.

**Comment by mtias** [comment]
Adding a tooltip would be a good quick improvement.

**Comment by cbravobernal** [comment]
I will happy to take this with @bangank36 on WCEU2022 contributor day!!!

**Comment by cbravobernal** [comment]
Hi there!

I cannot reproduce the issue, as the size editor tool was updated after this Issue was created. 

The tooltip seems to be there!

<img width="1320" alt="Screenshot 2022-06-02 at 10 51 08" src="https://user-images.githubusercontent.com/37012961/171604464-6bbc9149-0b95-4713-9e50-c2c232acd743.png">
.
