### ISSUE TITLE
Editor styles are applied inconsistently for themes that do not support theme.json

### ISSUE THREAD

**Issue by chad1008** [WordPress/gutenberg#35730]
### Description

If a theme does not support theme.json, editor styles are not applied on some themes, and text is rendered in the browser's default font.

This appears to have been introduced in #35424, when the check for `WP_Theme_JSON_Resolver_Gutenberg::theme_has_support()` was removed.

In testing a few different themes, it does appear there are theme-specific variables at play as well, and not simply whether or not the theme supports theme.json. How and when the theme declares its editor styles may be a factor (ie  `add_editor_style()` vs `wp_enqueue_style(`) and/or `init` vs `enqueue_block_editor_assets` for example)

### Step-by-step reproduction instructions

1. Activate a theme such as [Nucleare](https://wordpress.org/themes/nucleare/), which happens to be impacted
2. With Gutenberg v11.7 active, create a new post. Note the browser default font
3. Close the editor, and roll back to Gutenberg v11.6.
4. Create another new post, and note that the theme's editor styles are applied.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by oandregal** [comment]
Hey, thanks for reporting. 

I can indeed confirm that removing [this check](https://github.com/WordPress/gutenberg/pull/35424/files#r724332466) has caused this bug. I'm a bit puzzled as to why, though.

My best hypothesis at the moment is that removing this check has surfaced at an existing bug that was dormant. I checked and, for the Nucleare theme, if the `$settings['styles']` is empty after [this code](https://github.com/WordPress/gutenberg/pull/35424/files#diff-0b8e98dead5542e95159bd3c482158111d3f16637e7eef9af13373358fa42ded) runs, everything works as expected. However, after https://github.com/WordPress/gutenberg/pull/35424 there are no themes with empty `$settings['styles']` because we always add the core presets for all. So I guess that change is affecting other parts of the codebase. I'm still trying to understand where/why/how.

**Comment by oandregal** [comment]
mmm, I think I've got a lead. At https://github.com/WordPress/gutenberg/pull/34439 (Gutenberg 11.5) we added some styles for themes that didn't add any editor styles. Nucleare is one of such themes. However, by doing https://github.com/WordPress/gutenberg/pull/35424 all the themes provide _some_ styles: at least there are the core presets.

I'm exploring a potential fix at https://github.com/WordPress/gutenberg/pull/35736

**Comment by oandregal** [comment]
Created a second PR at https://github.com/WordPress/gutenberg/pull/35737 I think this is a better approach, but would like to hear people's thoughts.

**Comment by Sifrqitt** [comment]
As soon as I upgraded the Gutenburg plugin to the latest 11.7.1 , from the previous version 11.6.0, the fonts displayed in the editor no longer match my theme fonts, they seem to have reverted to some default fonts (see attached picture). I don't like it at all because I like my theme fonts, so I will be reverting to the previous version of Gutenburg, until this is fixed.

Using latest Wordpress version 5.8.1
![Capture2](https://user-images.githubusercontent.com/41350452/138362978-22c6edf0-c9c5-475d-9109-7dd0dbe9264b.PNG)
