### ISSUE TITLE
[Quote, Pullquote Blocks] Allow theme.json customizations of the citation fields

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#35735]
Currently, `theme.json` does not let you style the citation field for the Quote and Pullquote blocks.

It should be possible to (for example), set a font size for the main quote, and set a specific font size for the citation as well.  Or to use different fonts for each. Here's some pseudocode for example: 

```
"core/pullquote": {
	"typography": {
		"fontFamily": "var(--wp--preset--font-family--source-serif-pro)",
		"fontSize": "var(--wp--preset--font-size--huge)",
		"fontWeight": "300"
	},
	"citation": {
		"typography": {
			"fontFamily": "var(--wp--preset--font-family--system)",
			"fontSize": "var(--wp--preset--font-size--small)",
			"fontStyle": "italic"
		}
	}
}
```

Here's an example of what we'd like to achieve for the pullquote block in Twenty Twenty-Two, but cannot at the moment: 

<img width="732" alt="Screen Shot 2021-10-18 at 10 57 03 AM" src="https://user-images.githubusercontent.com/1202812/137756348-27077d4b-88ce-4eff-b35b-53bc966bf93a.png">

The main issue in that specific case is that I cannot use one font for the quote, and another font for the citation.

**Comment by ZebulanStanphill** [comment]
It's worth noting that there have been plans to convert the Quote (and presumably also the Pullquote) to use nested blocks (#15486), and one of the things that would likely change alongside that is the markup of the blocks, in order to match the latest WHATWG spec. See https://github.com/WordPress/gutenberg/pull/25892/files#r589615279. Not sure if that has any effect on this issue, but I figured I'd bring it up in case it did,

**Comment by carolinan** [comment]
@scruffian 👋 Do you think `citation` / cite  should be added to _elements_?

**Comment by scruffian** [comment]
Yes I do. Would you like to create a PR for it? :)

**Comment by carolinan** [comment]
Yes I can try, there should be enough reference in the other elements changes.

**Comment by scruffian** [comment]
This was closed by https://github.com/WordPress/gutenberg/pull/43543
