### ISSUE TITLE
Bug Shortcode

### ISSUE THREAD

**Issue by RickorDD** [WordPress/gutenberg#3576]
i have a Plugin with a Shortcode. 

<img width="459" alt="bildschirmfoto 2017-11-20 um 17 37 26" src="https://user-images.githubusercontent.com/6922544/33029673-88b29108-ce19-11e7-8deb-3e13acc6255c.png">

when i call 

**echo "Hello Shortcode";**
**print "Hello Shortcode";**

then shows a error
<img width="336" alt="bildschirmfoto 2017-11-20 um 16 18 36" src="https://user-images.githubusercontent.com/6922544/33025625-c7cc319c-ce0e-11e7-9f48-198705284ca0.png">

but call

**return null;**

then shows ok
<img width="298" alt="bildschirmfoto 2017-11-20 um 17 41 46" src="https://user-images.githubusercontent.com/6922544/33029897-1dbc8f4c-ce1a-11e7-929b-1b968cfaee12.png">

**Comment by Soean** [comment]
"Note that the function called by the shortcode should never produce output of any kind. Shortcode functions should return the text that is to be used to replace the shortcode. Producing the output directly will lead to unexpected results. This is similar to the way filter functions should behave, in that they should not produce expected side effects from the call, since you cannot control when and where they are called from." https://codex.wordpress.org/Function_Reference/add_shortcode

**Comment by RickorDD** [comment]
ok, this new code running fine.

<img width="473" alt="bildschirmfoto 2017-11-20 um 18 56 21" src="https://user-images.githubusercontent.com/6922544/33033438-aa01e088-ce24-11e7-9577-e505e5896f5f.png">

**Comment by shadyshrif** [comment]
what about using WP function that already prints?

For example:
wp_list_categories

this is my code

`function my_list_categories_shortcode() {
    wp_list_categories(); 
}

add_shortcode( 'cat_list', 'my_list_categories_shortcode' );`
