### ISSUE TITLE
Cover block - Default overlay opacity is set to 100

### ISSUE THREAD

**Issue by geriux** [WordPress/gutenberg#35766]
## Description
The default overlay opacity is set to 100 which covers any image/video that's added as a background. This is a regression from this [PR](https://github.com/WordPress/gutenberg/pull/35065).

## Step-by-step reproduction instructions
- Open the mobile editor
- Add a Cover block
- Add an image
- Once it finishes uploading, you can see the overlay is covering the image.

## Expected behaviour
The media should be visible when it's added to the block. The overlay should have a default value of `50`

## Actual behaviour
The media is covered by the overlay which has a default value of `100`

## Screenshots or screen recording (optional)
https://user-images.githubusercontent.com/4885740/137935312-6d37f1a9-5eb7-4861-8309-e34a749b1a86.mp4

## Device information
- Device: Redmi Note 8T OS 11

**Comment by glendaviesnz** [comment]
@geriux Because of the need to allow an opacity setting on the background color when there is no image, as added [here](https://github.com/WordPress/gutenberg/pull/35065), I think it might be confusing to users to set the default dimRatio to 50 as then the background color will have a default 0.5 opacity so users might wonder why they selected black but it shows more as a grey, etc.

It would be possible though to switch the dimRatio to 50 if an image is added and it is currently set to 100 as [in this PR](https://github.com/WordPress/gutenberg/pull/35789). Do you think that would work as a solution for the mobile app as well?

**Comment by geriux** [comment]
> @geriux Because of the need to allow an opacity setting on the background color when there is no image, as added [here](https://github.com/WordPress/gutenberg/pull/35065), I think it might be confusing to users to set the default dimRatio to 50 as then the background color will have a default 0.5 opacity so users might wonder why they selected black but it shows more as a grey, etc.
> 
> It would be possible though to switch the dimRatio to 50 if an image is added and it is currently set to 100 as [in this PR](https://github.com/WordPress/gutenberg/pull/35789). Do you think that would work as a solution for the mobile app as well?

Hey @glendaviesnz 👋  thank you for working on a fix so quickly! This works for mobile with the extra change from this [PR](https://github.com/WordPress/gutenberg/pull/35792#pullrequestreview-784157848) 🎉
