### ISSUE TITLE
Placeholder options not aligned in columns

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#35812]
### Description

When adding an image into a column of a Columns block the place holder adopts to the size of the column. The placement of screen elements is a bit hap hazardous. As you can see from the screenshot, 

- the title of the block is left aligned, 
- the **"Upload"** button is centered, 
- the **Media library** link is left aligned again and 
- the button **Insert from URL** is centered again. 

### Step-by-step reproduction instructions

- Create a post
- Add a columns block with three columns
- Try to add an image to one of the columns. 

### Screenshots, screen recording, code snippet

<img width="404" alt="Screen Shot 2021-10-20 at 2 14 50 PM" src="https://user-images.githubusercontent.com/39980/138148861-481e6ca3-fed0-43ce-919b-0639ad4f479f.png">

### Environment info

- WordPress 5.9-alpha-51919
- Gutenberg nightly (before 11.8 RC) v Version 11.9.0.202110120
- OS 10.15.7
- Chrome Version 94.0.4606.81 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jasmussen** [comment]
Thanks for the ticket! Do you have additional steps to reproduce? I can't seem to myself:
<img width="741" alt="Screenshot 2021-11-03 at 10 13 36" src="https://user-images.githubusercontent.com/1204802/140034482-6d51bf2b-5fe9-43e0-95b2-f0eaca3c2eb1.png">

Also, if you are able to test https://github.com/WordPress/gutenberg/pull/33494 (perhaps using gutenberg.run), can you see if that solves the issue? I suspect that a theme or a plugin you are using, is applying a text alignment which bleeds into the placeholder.

**Comment by bph** [comment]
@jasmussen hmm you might be right about the theme influencing the alignment. It's odd that I don't mention the theme in the issue. I'll double check it again and will also test the PR and see if that'll fix it. It will take a few days though.

**Comment by jasmussen** [comment]
Don't worry able it, I think there's potentially an easy bug fix. Happy to help.

**Comment by bph** [comment]
So I was able to reproduce the issue using Twenty-Twenty-one Theme 

<img width="485" alt="Screen Shot 2021-11-10 at 1 46 23 PM" src="https://user-images.githubusercontent.com/39980/141174482-d51b6350-758a-403f-812c-fd2c8f7968e7.png">

Here is a video to: https://recordit.co/STdY3r8Lr7
In TT1 the items on the image placeholder are all aligned well. 

<img width="771" alt="Screen Shot 2021-11-10 at 1 52 19 PM" src="https://user-images.githubusercontent.com/39980/141175453-191d2464-7cb7-4738-8180-abb344992b73.png">

Should we close the issue here and open a trac ticket for twenty-twenty-one?

**Comment by bph** [comment]
Oh and there was no difference in this behavior, when using the plugin build from PR #33494

**Comment by bph** [comment]
The last test was with 11.9 RC 4, and I still see the same issue in Twenty-twenty-one. :-)

**Comment by jasmussen** [comment]
Thank you for the additional information, I was able to reproduce, though I wasn't able to get your "staircase columns block" effect, that seems like an additional bug! 
<img width="772" alt="Screenshot 2021-11-11 at 08 11 35" src="https://user-images.githubusercontent.com/1204802/141254367-5b336dc7-10c5-4db6-b528-339dc0acac86.png">

As it turns out, TwentyTwentyOne has this rule:

```
.wp-block-image > div {
	text-align: center;
}
```

that's part of its editor style, and it's what centers the first and 3rd buttons, as shown in this GIF:
![bug](https://user-images.githubusercontent.com/1204802/141254468-38e6b3df-6267-4883-bc57-406fcf43236b.gif)

I have pretty high confidence that #33494 will fix this, but there's a good chance that won't land for 5.9. Furthermore I do think this is something to fix in the theme, as it seems like a somewhat offhand rule whose side effects maybe weren't clear when it was written. Thank you!

Edit: Oh and if you have the bandwidth to create the ticket, I would appreciate that, you can use the GIF if you like.

**Comment by bph** [comment]
Created [Trac Ticket ](https://core.trac.wordpress.org/ticket/54427) for Twenty-Twenty-One Theme and close this issue here.
