### ISSUE TITLE
Ensure the Customizer is available for plugins or theme options when using a FSE theme

### ISSUE THREAD

**Issue by Clorith** [WordPress/gutenberg#35874]
### Description

When using a theme that declares support for Full Site Editing (uses `theme.json`), the _Customize_ options are hidden (you can still access the Customizer directly with a link).

This would require plugins or themes that wish to continue using options to implement their own links, creating multiple entry-points to a core feature, and potential user confusion/frustration.

### Step-by-step reproduction instructions

1. Verify that Twenty Twenty-One is your active theme
2. Install the WooCommerce plugin (uses the Customizer to set up their display options)

The Customizer link is where it usually sits by default, under the Appearance menu item.

3. Switch to the TT1-Blocks theme

The Customizer link is now gone from where it used to be, but replaced with a custom link added by WooCommerce, which takes you to its own area in the Customizer.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by celloexpressions** [comment]
As I elaborated on #30496, there isn't feature parity for core customizer features yet, so it's premature to hide the customizer for block themes regardless of plugins or themes adding options to the customizer. Doing so also breaks core features. Any conditional logic to hide the customizer should be removed for now (for 5.9).

I would also point out that the current conditionals only hide some of the customize links. The theme switching process uses the customizer for live preview regardless of a the theme's configuration, in both wp-admin and through the customizer. The dashboard also features a prominent button to customizer your site that remains visible for block themes. It seems like the current logic was intended to be more of a temporary experiment.

**Comment by noisysocks** [comment]
Looking through #30496, I don't see anything underneath "Customizer-Only Features" that is critical for WP 5.9 given you can switch to a non-block theme and the majority of users will do just that. We do not need to strive for feature parity because block themes are not replacing classic themes. Also worth noting is that the site editor and block themes are labeled "Beta".

The one issue that does stand out to me in #30496 as required for WP 5.9 is this one that we're in right now. This is because Twenty Twenty-two will be the default theme and plugins will appear broken or we will have duplicate Appearance → Customize entries if we do not address the issue.

Showing a link to the Customizer only when a plugin needs it (#35877) is my preferred solution but if need be I'm happy to pivot to always showing a link to the Customizer. We can make this pivot during the 5.9 beta period if required.
