### ISSUE TITLE
Update top-level README for Block Editor Handbook 

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#35905]
## What problem does this address?

[The current top-level page for the Block Editor Handbook](https://developer.wordpress.org/block-editor/) is geared towards the post editor being the primary Gutenberg tool, with the upcoming release of WP 5.9 the Block Editor Handbook covers many topics beyond just the post editor.

## What is your proposed solution?

I'm open to suggestions on what to include. There are a lot of topics covered in the handbook, from building blocks to global styles, and block themes. 

A couple of suggestions for the page, but welcome your thoughts:

- Update the lead image - The current image was used to highlight sections in the post editor, it is not really feasible to try to cover all the topics the handbook now covers. So, we probably want something more aspirational, open to suggestions.

- Review and organize the content - The main focus of the handbook previously was on creating blocks, but with WP 5.9 there are block themes, settings, styles, and templates that will need prominence. How best do we guide the developers?

**Comment by annezazu** [comment]
Thanks for kicking this off! Whew, great call out to get this page updated. Keen to help as I can. I agree with both of your suggestions. 

> How best do we guide the developers?

This might be overkill but I imagine almost three sections with rough categories (this is off the top of my head and not meant to be fully comprehensive): 

Beginner:
- Help with testing. 
- Build your own custom block patterns (can link to workshop). 

Intermediate: 
- Contribute to the codebase with good first issues.
- Create custom block variations
- Create custom block styles

Advanced:
- Contribute to the codebase outside of good first issues.
- Build a block theme. 
- Adopt pieces of FSE for your theme. 
- Create a custom block. 

In general, it feels important to move away from creating a custom block as the sole way to develop with Gutenberg or create things for clients, especially since custom blocks aren't always the best solution or the only.

**Comment by jasmussen** [comment]
I have a bit on my plate these days, but commenting here to offer support with a fresh screenshot at some point. If you can let me know when the time draws nearer I'll see if I can add something.

**Comment by ryanwelcher** [comment]
This will be addressed with https://github.com/WordPress/gutenberg/issues/35905

**Comment by skorasaurus** [comment]
formally closing per https://github.com/WordPress/gutenberg/pull/49643#issuecomment-1506947161
