### ISSUE TITLE
Paragraph placeholder in InnerBlocks is set to opacity 0

### ISSUE THREAD

**Issue by virgiliud** [WordPress/gutenberg#35928]
### Description

When generating an InnerBlock with a template in the editor, the placeholder of a paragraph that's immediately after another paragraph is set to opacity 0. Please see screenshot. 

### Step-by-step reproduction instructions

1. Create an InnerBlock with the following allowed blocks and template:

```
const ALLOWED_BLOCKS = [ 'core/image', 'core/paragraph', 'core/list', 'core/group', 'core/heading', 'core/button' ];

const TEMPLATE = [
  [ 'core/heading', { placeholder: 'Price Title' } ],
  [ 'core/paragraph', { fontSize: 'large', placeholder: '$49/mo' } ],
  [ 'core/paragraph', { placeholder: 'Price Subtitle' } ],
  [ 'core/list', { placeholder: 'Feature list' } ],
  [ 'core/button' ]
];
```

2. Generate the InnerBlock in the edit() function with the following settings:
```
<InnerBlocks
      allowedBlocks={ ALLOWED_BLOCKS }
       template={ TEMPLATE }
       renderAppender={ InnerBlocks.ButtonBlockAppender }
/>
```

3. In the editor, the paragraph block with the placeholder "Price Subtitle" will have 0 opacity.

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/3076742/138730633-6bf62162-68ee-4676-a949-50cf390bc642.png)

### Environment info

WP version 5.8.1, using the stable Gutenberg version (not the plugin with experimental features)
Tested in multiple themes

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
That is an odd error; I am able to reproduce this on trunk last build from 2021-11-18.

**Comment by skorasaurus** [comment]
That is an odd error; I am able to reproduce this on Gutenberg trunk last built on 2021-11-18; 

Investigating this more; the cause is [this CSS in the paragraph bloc](https://github.com/WordPress/gutenberg/blame/3da717b8d0ac7d7821fc6d0475695ccf3ae2829f/packages/block-library/src/paragraph/editor.scss). 

@jasmussen - could you shed some light for this decision?

**Comment by jasmussen** [comment]
Sure! It was added in #28275 to fix #13599. That is, if you create 10 empty paragraphs in a row, there's little value in seeing `Type / to choose a block` repeated ten times. 

A very ugly hack we can't ship would be to do this:

```
.block-editor-block-list__block[data-empty="true"] + .block-editor-block-list__block[data-empty="true"] {
	[data-rich-text-placeholder="Type / to choose a block"] {
		opacity: 0;
	}
}
```
<img width="813" alt="Screenshot 2021-11-23 at 09 24 55" src="https://user-images.githubusercontent.com/1204802/142990959-f6495ba7-8b8e-4061-9d86-7b8a8db44b76.png">

Should we add an additional `data-custom-placeholder` attribute that just ensures full opacity?

**Comment by ndiego** [comment]
I just encountered this issue on a project I am working on. @jasmussen I like the idea of `data-custom-placeholder` attribute that can easily be targeted with CSS.

**Comment by afercia** [comment]
I've been pinged on the associated PR and discovered this issue. Learned something new as I was unaware of this behavior.

I'm not sure the original change from #28275 / #13599 is a good choice in the first place. In my opinion, that introduced an accessibility and usability issue. The point is that the Editor is an editing interface. _It should show what is editable_. Instead, by hiding the default placeholder for the subsequent paragraph blocks, there's no visual indication of the editable fields.

No border, no shape, no placeholder text, nothing. Seems to me that deliberately hiding the editable parts of an interface is less than ideal. Consider the screenshot below, where:

- A Row block contains 3 empty paragraphs, horizontally stacked.
- After the Row, there are 6 empty paragraphs, vertically stacked.

<img width="1513" alt="no visible editable fields" src="https://user-images.githubusercontent.com/1682452/181001873-48e238d7-1ba2-49a2-98ee-b7403272441f.png">

As a user, I can't really _see_ where the editable paragraphs are, with the exception of the first ones. 

It's not even clear where I'm supposed to click to target the editable empty paragraphs. Hovering with the mouse doesn't help.

Basically, the interface is lying to users because there's really no visual presentation of the editable parts.

I'd like to stress that this is an editing context. While I understand the desire to make the editor a visual preview that is as close as possible to the front end, I'm not sure this is the right direction to take. 

Overall, I'd like to propose to reconsider the original change and just revert it.

Minor, but interesting annoyance: when entering text or emptying the paragraphs, the placeholder visually 'moves' to the right / left and down / up. Basically, the placeholder appears and disappears based on the associated CSS rule that hides all subsequent placeholders (except the first one). The resulting visual effect is pretty confusing. I doubt users will actually understand why the placeholder appears and disappears. See animated GIF:

![placeholder-moves](https://user-images.githubusercontent.com/1682452/181006359-58e26b16-5243-4630-b346-26b8ed92abb9.gif)
