### ISSUE TITLE
Cover Block min height unit "vh" missing / only "vw" selectable

### ISSUE THREAD

**Issue by dennisheiden** [WordPress/gutenberg#36035]
### Description

I have noticed that you cannot select "vh" as unit for the min-height block setting of cover blocks, only "vh" (besides px etc.)

![image](https://user-images.githubusercontent.com/25924499/139244184-6c1ae634-79e8-4453-9dc7-ebda0485448c.png)
![image](https://user-images.githubusercontent.com/25924499/139244256-1a90e621-581f-431f-862f-30e035eb558d.png)

### Step-by-step reproduction instructions

- Editor view
- Insert Cover Block
- Select unit list for min height

### Environment info

WordPress 5.8.1
Gutenberg Version 11.8.0 (Plugin)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kkalvaa** [comment]
I came here looking for the same issue, I also find this to be very annoying. It doesn't make sense to set height based on view width rather than view height. I curently have an ussue where I need to set a cover to 60% of the view height, which would be very easy with **60vh**, but completely impossible with **vw** in a responsive setting as I can never know the exact dimensions of the user's viewport.

**Comment by fwazeter** [comment]
This looks very much like the theme.JSON file in the theme you're in does not have VH enabled as an enabled unit in the spacing-> unit section. 

Which theme are you using? I've been in and out of adjusting cover blocks in latest Gutenberg all day with VH in my own themes and a few test themes.

Check the theme.JSON file for:

```

  "settings": {
       "spacing": {
            "units": [ "px", "em", "rem", "vh", "vw" ]
        }
}

```

If a unit isn't listed in the spacing/units array, when other units have been specified, then it won't typically show, likewise any valid spacing unit will show if it's listed - for instance, I'll often add ch.

**Comment by dennisheiden** [comment]
Oh! I see. Have tested this again with Twenty Twenty-One, and there is a vh option:

![image](https://user-images.githubusercontent.com/25924499/140040345-b776fc68-c961-4749-a428-f528bd521207.png)

Going to check this again in the client project, sorry for asking, is there any source on theme.jsons or a boilerplate available? (I will search myself, but I think asking might shorten my search.)

**Comment by dennisheiden** [comment]
Ok, it's not a Gutenberg issue.

The theme doesn't need to have theme.json (Twenty-One has none, I think). The theme needs support for custom units:

`add_theme_support( 'custom-units' );`

Thanks @fwazeter for the hint to the right direction!

**Comment by fwazeter** [comment]
> Ok, it's not a Gutenberg issue.
> 
> The theme doesn't need to have theme.json (Twenty-One has none, I think). The theme needs support for custom units:
> 
> `add_theme_support( 'custom-units' );`
> 
> Thanks @fwazeter for the hint to the right direction!

Glad I could help! 

You are correct - you can certainly just add the proper theme supports directly, theme.json (although for all the great things it can do right now, it makes you wish it could do more, so it gets weird) just serves as an API to make a lot of that easier. Vanilla TwentyTwentyOne doesn't have it, but the alternate for FSE/Full Site Editing, TT1Blocks uses it and pretty much any major FSE theme will use them going forward. 

For what it's worth - you can add a theme.json file to any theme that's 5.8 compatible if you want (although there may be some conflicts depending on the theme) - not sure how much theme development you're doing, but worth taking for a spin since more and more functionality is being built into it. 

If there's any weird quirkinesses with settings like that that you run into, and in case you didn't see this page, this is the official [WordPress docs for the theme.json](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#backward-compatibility-with-add_theme_support) file and covers all the extra add_theme_supports.

**Comment by dennisheiden** [comment]
Yeah, I'm looking forward to implement theme.json and stuff to our theme for the next bigger update.
