### ISSUE TITLE
Disable `show_in_rest` for template CPTs

### ISSUE THREAD

**Issue by TimothyBJacobs** [WordPress/gutenberg#36095]
The templates CPTs are currently marked as `show_in_rest` and has a custom controller specified. The templates controller, however, does not follow the patterns for CPT controllers. Most importantly, the route URLs are completely different.

Before the CPTs get merged, we should make sure to turn off that `show_in_rest` and instead register the routes manually on `rest_api_init`.

https://github.com/WordPress/gutenberg/blob/e015b5f1d4308af87648c9c7b33e011b0b6aab97/lib/full-site-editing/templates.php#L46

https://github.com/WordPress/gutenberg/blob/be48e651c5c94333fabea93be7c5273085b89564/lib/full-site-editing/template-parts.php#L46

**Comment by noisysocks** [comment]
cc. @ockham @youknowriad who I believe are working on merging this endpoint.

**Comment by youknowriad** [comment]
If I'm not wrong, that endpoint has been merged already in 5.8, so this would be a breaking change. For instance instead of `getEntityRecord( 'postTypes', 'wp_template' )` we'll be using `getEntityRecord( 'root', 'template' )`. I think that's solvable in Gutenberg by having some kind of "alias" behavior for entities to ensure backward compatibility but I'm not sure that it's the only breaking change, is there other impacts on the backend potentially?

**Comment by TimothyBJacobs** [comment]
Ack, I should of caught this before 5.8 merge then. Thanks for clarifying @youknowriad. I agree this would be a BC break, and I think probably not worth making the change then.
