### ISSUE TITLE
Load post types / taxonomies that support `show_in_nav_menus` via the REST API

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/gutenberg#36110]
## What problem does this address?

Current data of what post types and taxonomies support nav menus is loaded in PHP.

https://github.com/WordPress/gutenberg/blob/8709795d43cfbed9a2d35d65e0a2696b867fb75c/packages/block-library/src/navigation-link/index.php#L316-L318

However, this data is avalible in the REST API. 

<img width="454" alt="Screenshot 2021-11-01 at 11 05 40" src="https://user-images.githubusercontent.com/237508/139662447-b46e48ea-dbd7-4c33-9537-c8e4fd60c9d6.png">
<img width="520" alt="Screenshot 2021-11-01 at 11 06 11" src="https://user-images.githubusercontent.com/237508/139662464-2c8ce344-f30b-42bf-890b-f0cff4993073.png">

This data could be loaded via the REST API. In many cases, types and taxonomies endpoints are already loaded on the page. 

https://github.com/WordPress/gutenberg/blob/ff6cfe0c0a631f37ca9e1e6cbc66aefdf7536b82/lib/full-site-editing/edit-site-page.php#L111-L112

**Comment by kathrynwp** [comment]
Closing this issue due to the Navigation Screen project being moved to [an inactive status on the feature projects page](https://make.wordpress.org/core/features/) in coordination with the project leads. (The developer documentation in the initial post are no longer accessible)

If this work is picked back up, issues can be revisited and reopened as needed. Thanks for pitching in on this early feature so the wider WordPress project could benefit from the lessons learned!
