### ISSUE TITLE
__experimentalBlockAlignmentMatrixControl : the positions of the dots should not change when RTL

### ISSUE THREAD

**Issue by shadigaafar** [WordPress/gutenberg#36237]
### Description

I tested it on RTL, and it says about the point that is "top left": "top right", even when console log the values, they are the in the opposite direction of dots:

though if you test it in cover block... the content aligns perfectly in the appropriate location as the dots... but i think that because who ever developed the cover block has used flex and flex direction change on RTL... but that is not the solution. cause now the tooltip text is different from the actual dot's location. so, I guess the direction of the dots should stay in one way for RTL and LTR... 

### Step-by-step reproduction instructions

1. console log the values  generated on change of  __experimentalBlockAlignmentMatrixControl component.
2.  go to the block editor and test your block... 
3. see what has been generate when you change alignment
4. flip html direction to RTL by changing to any RTL language.
5. see if the values u get corresponds with UI dot's location.

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/74800166/140446221-3315b158-5edf-4ec9-8464-77b70dcf27ec.png)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by shadigaafar** [comment]
The propose solution:
This problem should not be fixed by CSS, cos it will break any blocks already using it, and it will mean that each time this component is used, must do custom RTL for the positions... so, the best solution is to modify the generated values by `__experimentalBlockAlignmentMatrixControl` based on RTL or LTR...  and the tooltip text.

**Comment by shadigaafar** [comment]
The proposed solution:
This problem should not be fixed by CSS, cos it will break any blocks already using it, and it will mean that each time this component is used, must do custom RTL for the positions... so, the best solution is to modify the generated values by `__experimentalBlockAlignmentMatrixControl` based on RTL or LTR... and the tooltip text.

**Comment by shadigaafar** [comment]
changing the label text for RTL is enough for fixing this problem.

**Comment by t-hamano** [comment]
~~I tested this issue using the language direction switcher and [RTL Tester](https://wordpress.org/plugins/rtl-tester/) on Storybook and was indeed able to reproduce it.~~

*Note: In my environment, `isRTL` function did not respond correctly when I changed to the RTL via RTL Tester.
Therefore, it may be necessary to actually change the WordPress site language and try it on the cover block instead of following the steps below.* 

## LTR language on Storybook

![ltr](https://user-images.githubusercontent.com/54422211/183915113-aa1919d3-ee98-4953-8d47-8df53baad7f9.png)

## RTL language on Storybook

![rtl](https://user-images.githubusercontent.com/54422211/183915130-96d2ed83-204f-4858-b9cd-880ce99dfa17.png)

## RTL language in cover block

![cover](https://user-images.githubusercontent.com/54422211/183915407-897e6c0e-c5ef-49f6-ab08-91590f6152eb.png)

I think that to reverse the left and right display labels when in RTL language is the solution.

**Comment by t-hamano** [comment]
@shadigaafar 
Thank you for submitting the issue.
I have submitted #43126 to resolve this issue.
