### ISSUE TITLE
When click on Editor (beta), styles panel is open

### ISSUE THREAD

**Issue by kellychoffman** [WordPress/gutenberg#36270]
- When you click on Appearance > Editor (beta), you are brought to the site editor with styles open. 
- When you click on Appearance > Styles, you are also brought to the site editor with styles panel open. 

[Now that we have two distinct paths](https://github.com/WordPress/gutenberg/pull/36194), one to Editor, one to Styles, we should differentiate the two a bit more. (Before we did not have a Styles nav item, so the decision was made to have the styles menu open when you enter the Editor)

Should we close the styles panel when you click on Appearance > Editor (beta)? It could really focus things. The welcome guide will also inform users they can click on the icon in the top bar to open Styles menu.

**Comment by jameskoster** [comment]
For the record, I think this is going to be a bit confusing regardless. Mostly because both links send you to editor views where the primary focus (IE the canvas) is identical. I would prefer the Styles link took you to a unique view, but we can get to that later. For now I agree that making sure the styles panel is closed when Editor beta is clicked would be a good first step.

**Comment by carolinan** [comment]
The styles menu item was removed, can this be closed?

**Comment by jameskoster** [comment]
Yes I think so.
