### ISSUE TITLE
Gutenberg 11.9: Not possible to filter the global style settings anymore

### ISSUE THREAD

**Issue by briceduclos** [WordPress/gutenberg#36330]
### Description

Before Gutenberg 11.9, it was possible to filter the block editor settings using this solution https://github.com/WordPress/gutenberg/issues/27504#issuecomment-858761483 posted by @oandregal.

Testing Gutenberg 11.9 RC-3, this solution doesn't work anymore. So, how can we filter the editor settings?

Thanks

### Step-by-step reproduction instructions

Use the filter below to modify the editor settings:
`add_filter( 'block_editor_settings_all', 'custom_global_styles_settings', PHP_INT_MAX  );`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @briceduclos

We tested this during the Core Editor [Triage session today](https://wordpress.slack.com/archives/C02QB2JS7/p1636434928059200), and the `block_editor_settings_all` filter works expected.

The issue might be with individual settings. Can you share the example code you're using to filter those settings?

Thanks

**Comment by oandregal** [comment]
Hi Brice, by any chance, are you filtering some of the [theme settings](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#backward-compatibility-with-add_theme_support) we retrofit into theme.json? These are `custom-line-height`, `custom-spacing`, `custom-units`, `disable-custom-colors`, `disable-custom-font-sizes`, `disable-custom-gradients`, `editor-color-palette`, `editor-font-sizes`, `editor-gradient-presets`, `experimental-link-color`.

If you want to filter one of those settings from the theme the recommended way is to use `after_theme_setup` instead of the block settings filter. There was a bug in how we retrofit these settings in WordPress 5.8 that we've fixed https://github.com/WordPress/gutenberg/pull/36054 for WordPress 5.9.

If you are filtering any other setting, would your specific use case?

**Comment by briceduclos** [comment]
Thanks for your replies. I'm using the following code:

```
function custom_global_styles_settings( $settings ) {

    if ( isset( $settings['__experimentalGlobalStylesBaseConfig'] ) ) {
        $settings['__experimentalGlobalStylesBaseConfig']['settings']['layout']['contentSize'] = '800px';
    }
    
    if ( isset( $settings['__experimentalFeatures'] ) ) {
        $settings['__experimentalFeatures']['layout']['contentSize'] = '800px';
    }   
    
    return $settings;
}
add_filter( 'block_editor_settings_all', 'custom_global_styles_settings', PHP_INT_MAX  );
```

I've just realized it still works in the page/post editor, but it doesn't work in the site editor (Appearance > Editor).

**Comment by briceduclos** [comment]
Hi @Mamaduka, @oandregal,

I've found out that Gutenberg 11.9 doesn't use `$settings['__experimentalGlobalStylesBaseConfig']` anymore. Is there a solution?

Thanks.

**Comment by oandregal** [comment]
Hey @briceduclos the code above still works for filtering `__experimentalFeatures`. 

`__experimentalGlobalStylesBaseConfig` has been removed in favor of the rest API endpoint introduced at https://github.com/WordPress/gutenberg/pull/35985 The REST API already has a few filters in place, so it should be doable. I don't remember which one would be appropriate off the top of my head. I can try to investigate and post an example here after the betas are in a good place. Please, be welcome to share if you do it before.

It's also worth noting that most of these settings/data flows are experimental until the API is fully matured and changes are expected. The names of the settings communicate that.

**Comment by Thelmachido** [comment]
Hi @briceduclos it looks like @oandregal gave more information about the issue you were having and how to resolve that. 

I believe it is safe to mark this as resolved, if the suggested Rest API isn't working as expected please feel free to open the issue.
