### ISSUE TITLE
stylelint-config: Conflict with stylelint@14.1.0

### ISSUE THREAD

**Issue by Luehrsen** [WordPress/gutenberg#36514]
Stylelint 14.0 was released about a month ago and the official vscode stylelint plugin swiftly deprecated the 13.x branch. See https://github.com/stylelint/vscode-stylelint. 

When using @wordpress/stylelint-config with stylelint 14.1.0 npm install cannot resolve dependencies, as @wordpress/stylelint-config requires a peerDependency of "^13.7.0", which excludes the 14.x branch.

https://github.com/WordPress/gutenberg/blob/39f883e503f05aac223fe9d9d03a49d6279192a4/packages/stylelint-config/package.json#L39

After quickly scanning the code I don't see a reason why the peerDependency cannot be ">=13.7.0" for now.

I will submit a PR to implement this.

**Comment by WraithKenny** [comment]
This isn't fixed. 

https://github.com/WordPress/gutenberg/blob/trunk/packages/stylelint-config/package.json

Stylelint 14 needs more than just a peer update. The dependencies in stylelint-config are all out of date, and not compatible with 14.

`stylelint-scss` has to be at ^4 https://github.com/stylelint-scss/stylelint-scss/blob/HEAD/CHANGELOG.md
`stylelint-config-recommened` must be ^6 https://github.com/stylelint/stylelint-config-recommended/blob/main/CHANGELOG.md
`stylelint-config-recommened-scss` must be ^5 https://github.com/stylelint-scss/stylelint-config-recommended-scss/blob/master/CHANGELOG.md

As it is, every scss file checked with this package is reporting a false positive and otherwise not working. 

Also, the peer dependency for 13 should just be removed; there's no point to keeping it.

**Comment by WraithKenny** [comment]
Additionally, `stylelint-config-recommened-scss` @^5 has moved `stylelint-scss` from `peerDependencies` to `dependencies` so that can be removed from this package.json too.

```
	"dependencies": {
		"stylelint-config-recommended": "^3.0.0",
		"stylelint-config-recommended-scss": "^4.2.0",
		"stylelint-scss": "^3.17.2"
	},
	"peerDependencies": {
		"stylelint": "^13.7.0 || ^14"
	},
```
should become
```
	"dependencies": {
		"stylelint-config-recommended": "^6",
		"stylelint-config-recommended-scss": "^5"
	},
	"peerDependencies": {
		"stylelint": "^14"
	},
```
