### ISSUE TITLE
Navigation Block: align block toolbar closer to currently selected nested block

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#36538]
## What problem does this address?

Seems a regression happened at some point as the block toolbar now doesn't align with the currently block being edited. Here's a quick video to demonstrate:

https://user-images.githubusercontent.com/26996883/142045018-9041960b-11e6-4d09-b88c-583a519bffd0.mov

## What is your proposed solution?

Have the toolbar align with the current nested block being edited within the nav block. cc @talldan

**Comment by talldan** [comment]
Thanks for the ping. Unfortunately, I don't know much about this, and can't recall how it works. I did do a search around the codebase and looked back through recent PRs, but can't locate anything relevant. Was it a setting in the block.json or the inner blocks? Also not sure if it was a setting on the parent or child block.

I think @getdave implemented the feature initially where the child block's toolbar is pinned to the parent, so Dave might be able to provide some info about how it works. I'm not sure which PR disabled that on the nav block, whether is was also something Dave worked on or someone else.

**Comment by jasmussen** [comment]
This used to be intentional behavior: docking to the parent block toolbar was important back when every block had a border around it, lest it became very noisy very quickly. The API created for it remains useful, I imagine, for a slew of blocks and use cases, so I appreciate that it was made.

Without the borders, though, there's definitely a disconnect in placement of the block toolbar. I think it might still be theoretically useful for submenu items to have their toolbar docked to the parent item. 

However in the name of improving things in the near term, and exploring further, it seems worth it to disable the feature for the navigation block for now.

**Comment by talldan** [comment]
Ok, looked a bit more and found the change - https://github.com/WordPress/gutenberg/pull/34615

It seems like the change only affected the block when it's vertical. When horizontal the toolbar is still anchored to the parent.

So it isn't a regression, and I think we are now in feature freeze, but it is a small change so perhaps ok. I leave it up to the release lead.

**Comment by getdave** [comment]
Ah yeh but what happens when you're in nested submenus? That's why the feature was created. If the toolbar follows the nested block then the UX is horrible.

If this gets changed then we should at least make it only for the top level.

Personally I think we're too close to a release to change this.

Yes I also implemented the PR which made the "pin to parent" feature only apply in horizontal mode and not in vertical mode.

**Comment by mtias** [comment]
Yes, this is more of a decision that's been pending for some time — the change is just changing a flag. Let's see what comes up in testing and we can make a call.
