### ISSUE TITLE
Add Welcome Guide to Styles More Menu

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#36544]
## What problem does this address?

With the introduction of the Welcome Guide for the site editor https://github.com/WordPress/gutenberg/issues/32844, it would be great to have a way to trigger it once more.  

<img width="298" alt="Screen Shot 2021-11-16 at 2 35 16 PM" src="https://user-images.githubusercontent.com/26996883/142053646-510e7541-e335-4486-a6e8-f1105ec184ba.png">

## What is your proposed solution?

Add it as an option here:

<img width="288" alt="Screen Shot 2021-11-16 at 2 39 43 PM" src="https://user-images.githubusercontent.com/26996883/142054181-1f695d8e-96db-4684-81c4-ca7301a8df58.png">

**Comment by shaunandrews** [comment]
Seems like it should go in the top toolbar "..." menu instead, like the Welcome Guide is for the post editor:

<img width="436" alt="image" src="https://user-images.githubusercontent.com/191598/142054576-f689d8a7-34bc-4f11-b66c-ca2ffbc068b0.png">

We're getting a little carried away with all these different "..." menus. Worth noting the one you suggested is only visible if the Styles sidebar is open.

**Comment by annezazu** [comment]
AFAIK https://github.com/WordPress/gutenberg/issues/32844 handles having it in the usual spot!

**Comment by Mamaduka** [comment]
I think the "Styles" ellipsis button has a different purpose, similar to Dimensions one. Welcome Guide might be a little out of place there.

@talldan also pointed out a few issues with the current spit Welcome Guide solution - https://github.com/WordPress/gutenberg/pull/36172#discussion_r750077181. I would love to hear more feedback on this one as well 🙇

**Comment by mtias** [comment]
The main "welcome guide" is for the site editor, not for styles. It seems styles invoke its own when it's opened for the first time, so it makes sense to reinitialize that it's there.

**Comment by Mamaduka** [comment]
Another question: Do we want only to invoke Styles' welcome guide when a user visits Editor via "Appearance > Styles"?

P.S. I'll do a follow-up PR tomorrow.

**Comment by shaunandrews** [comment]
> The main "welcome guide" is for the site editor, not for styles.

I doubt this separation is obvious or makes sense to anyone outside of the people on this thread. The only way to see the styles is to use the site editor. 🤷

**Comment by mtias** [comment]
@shaunandrews can you clarify what would open when clicking "welcome guide" in your suggestion? Because there's already a welcome guide attached to the site editor.

**Comment by shaunandrews** [comment]
Its not clear to me what the distinction is between the two guides. Right now, when I click "Appearance -> Editor" and "Appearance -> Styles" I see the "Welcome to Styles" guide. It seems the only way to trigger the Site Editor guide is to close the styles sidebar. Its really finicky and the logic is not at all obvious. Here's the how I first encountered both guides:

1. I went to the "Appearance -> Styles" and I immediately saw the styles welcome guide, since (for whatever reason) my styles sidebar was open.
2. I kept the sidebar open, and made a few changes.
3. A few minutes later I closed the style sidebar and was immediately shown the site editor welcome guide. This was very confusing, since I wasn't aware what I did to trigger it, and it was so similar to the style guide that I thought it was a bug.

Maybe it should be a single welcome guide that covers both the site editor and styles sidebar? This seems like the best solution considering that the editor welcome guide is a single screen, which mentions styles.

<img width="398" alt="image" src="https://user-images.githubusercontent.com/191598/142250008-3f95a37d-94fa-4638-8774-4842dd8a89db.png">

Or, if we're sure we want two, maybe we label them something more descriptive in the menu, and figure out a better way to trigger them when first experiencing the site editor.

<img width="305" alt="image" src="https://user-images.githubusercontent.com/191598/142250101-98dcf521-83fa-452f-9e51-3c39bc595a64.png">

**Comment by javierarce** [comment]
I like the idea of having two entry points for each guide since it's confusing that the same button triggers a different one depending on whether the styles are toggled or not.

Having just one guide could work, but there's a significant imbalance on the content right now: an inner functionality of the site editor (styles) presents more information than the general guide. So if we wanted to merge those guides, we'd probably need to address that.

In any case, those solutions won't scale well as soon as we want to add more slides or guides. So I think at some point, we'll need to rethink how we present this information to the users (in my mind, the ideal solution could be having a general guide organized by sections for each feature).

**Comment by Mamaduka** [comment]
Do we have the final design/specs for this issue? I can start working on follow-up PR.

**Comment by Mamaduka** [comment]
Hi, everyone

I just wanted to check in again, if we have the final design for this issue.

Side note: The separate "Styles" entry point was removed recently - https://github.com/WordPress/gutenberg/pull/36637.

**Comment by shaunandrews** [comment]
> I just wanted to check in again, if we have the final design for this issue.

I guess the original proposal of adding it to the Styles sidebar "..." menu is still the best solution.


![](https://user-images.githubusercontent.com/26996883/142054181-1f695d8e-96db-4684-81c4-ca7301a8df58.png)

**Comment by mtias** [comment]
@noisysocks this is a nice to have for 5.9, can be easily punted

**Comment by Mamaduka** [comment]
@mtias, I've got to push another update for Welcome Guide and will try to include this as well.
