### ISSUE TITLE
New user experience with TT2

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#36578]
The first time experience of loading a new installation of WP trunk with TT2 is not great. The welcome message encourages the user to go to a screen that has been removed from the main navigation (customizer) and doesn't mention anything relevant about blocks, styles, and patterns.

![Screenshot 2021-11-16 at 11 21 50](https://user-images.githubusercontent.com/548849/142249324-ebaede68-5e0f-42df-ae4c-539d856c0531.png)

This is a huge wasted opportunity to establish the main concepts (blocks, patterns, styles), set the right expectations, and link to the relevant places. Let's plan for something more relevant here.

---

Similar about the main "customize" action on the theme browser. There's been mentions on how people could differentiate between themes built fully with blocks from others, and this is one aspect that can help with it. Instead of "Customize" the action could read "Editor" or whatever seems most appropriate.

![image](https://user-images.githubusercontent.com/548849/142249870-0da6bfbf-c31f-4e2f-a7a6-c7ff416712f3.png)

In the future, alternate styles would need to be a core component of this experience.

---

TT2 index template (used on a vanilla install) looks underwhelming in the context of the expectation the TT2 screenshot sets. We should build a home.html template to use for the index of the blog or similar.

<img width="1792" alt="Screenshot 2021-11-16 at 10 32 33" src="https://user-images.githubusercontent.com/548849/142250703-f4c63cca-4975-4071-b741-4b262261c763.png">

Tracked in https://github.com/WordPress/twentytwentytwo/pull/243

**Comment by connah99** [comment]
I think we should be wary of changing the welcome banner too much, as it serves a good general purpose. By having a few, more relevant, links it should still serve as a good introduction. 
If a what's new section was added, it would give an introduction to new features, and allow a short explanation of what they do. Otherwise, I don't think just adding a few extra links would do much to help an ordinary user, given how much 5.9 introduces. 
God knows I'm not a designer, but I've done a quick mock-up on Figma, sans Dashicons. 

![Desktop - 1](https://user-images.githubusercontent.com/91231626/142279604-9974eb8d-cc6f-4bc0-bd80-32a47db43aec.png)

**Comment by noisysocks** [comment]
Closing this in favour of:

- https://core.trac.wordpress.org/ticket/54460 for changing the Customize link and Welcome Box
- https://github.com/WordPress/twentytwentytwo/pull/243 for updating TT2 to have a better first experience

**Comment by jameskoster** [comment]
Trac ticket for the welcome banner: https://core.trac.wordpress.org/ticket/54489
