### ISSUE TITLE
Not able to edit post title some time

### ISSUE THREAD

**Issue by ghost** [WordPress/gutenberg#36614]
### Description

Not able to Edit post Title, It is happening some times only.

### Step-by-step reproduction instructions

Steps : Create a new post - Add post title - add font family, size, colour - save it - try to change post title

### Screenshots, screen recording, code snippet

Video : https://www.screencast.com/t/wGaa6Z2lFbMe

### Environment info

- WP version : 5.8.2
- Gutenberg : 11.9.1
- Theme - TT1 blocks 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Hi @sudip-d! From what I gather based on your video, you are trying to edit the Post Title Block. I wasn't sure at first so added the needs testing label :D  Right now, this is purposefully the case -- one cannot edit the text itself of the Post Title block but can edit the appearance. This is because it will edit the actual post title and this isn't necessary obvious to users. Here's the original context: https://github.com/WordPress/gutenberg/pull/32505

I'm going to close this out as a result but let me know if you believe this should be re-opened.
