### ISSUE TITLE
Unable to see Separator Color while selected

### ISSUE THREAD

**Issue by beatricekulcsar** [WordPress/gutenberg#36730]
### Description

While the separator is selected you cannot see the separator color you choose in the side bar.

### Step-by-step reproduction instructions

1. select the separator
2. click on the settings side bar
3. change color of separator

### Screenshots, screen recording, code snippet

<img width="866" alt="Bildschirmfoto 2021-11-22 um 12 51 35" src="https://user-images.githubusercontent.com/71608597/142857106-f3c480e8-447d-4f45-9543-bb48f77c03e5.png">

### Environment info

WordPress Version 5.8.2
Gutenberg Version 11.9.1
Active Theme: TT1 Blocks (tt1-blocks), Version 0.4.7

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
Thanks for reporting @beatricekulcsar. I am no longer able to replicate in WordPress 6.2 RC2. Therefore, it looks like this bug was fixed sometime in the last year or so. If you continue to experience issues, please feel free to reopen this issue. Thanks! 

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/4832319/226634755-643fae59-0b56-4fae-a69f-12a6cdd6e44f.png">
