### ISSUE TITLE
Docs - Clarify behavior of useOnce argument

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#3695]
The `block-api.md` document makes the following statement for the `useOnce` argument:

> Whether a block can only be used once per post.

To a Gutenberg extender, it would be helpful to know how this argument affects the behavior of the block within the editor — what does it actually do?

**Comment by youknowriad** [comment]
Maybe we should not document this property. It's only useful for the "more" block where you can only insert this block once in a post.

**Comment by benhuson** [comment]
Could it not be useful for plugins that may want to add a block that is used just once?

Consider a block where the data may be saved as post meta where you would only want one instance per post. For example, a subtitle block - this would differ from just a normal heading in that it would be saved as post meta so that it could be pulled an displayed separately on post archives etc.

**Comment by youknowriad** [comment]
@benhuson That's a good point 👍 

Anyone wants to PR this?

**Comment by jaswrks** [comment]
I PR'd it, docs enhanced here: https://github.com/WordPress/gutenberg/pull/4473

**Comment by adamsilverstein** [comment]
Fixed in https://github.com/WordPress/gutenberg/pull/4473
