### ISSUE TITLE
3 gutenberg_-functions called in wp-trunk (blocks/navigation.php)

### ISSUE THREAD

**Issue by kebbet** [WordPress/gutenberg#36962]
### Description

 There are three instances in the navigation block where gutenberg_-functions are called. They should be replaced with their correct function name, and be fixed upstream. Introduced in https://core.trac.wordpress.org/changeset/52069.

File: `/src/wp-includes/blocks/navigation.php`
L176: `gutenberg_get_menu_items_at_location`
L181: `gutenberg_sort_menu_items_by_parent_id`
L182: `gutenberg_parse_blocks_from_menu_items`

A ticket for the same issue has been created in the WordPress trac system. https://core.trac.wordpress.org/ticket/54532

### Step-by-step reproduction instructions

The functions seems to exist in trunk but under other names, such as `_wp_get_`*

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by noisysocks** [comment]
These functions were recently removed from Core (https://github.com/WordPress/wordpress-develop/commit/a9e66f4bcb8a857c78ac29f7de30f8f9f3d129c5) but remain in the plugin (https://github.com/WordPress/gutenberg/blob/trunk/lib/navigation.php). 

Are they still being used by the Navigation block? If not, we can simply remove this code.

Otherwise, I'm not sure what to do. Ordinarily we would gate functionality that needs to exist in the plugin but not in Core behind the `GUTENBERG_PHASE` variable. But that doesn't work in PHP. Perhaps we have to implement something analogous to `GUTENBERG_PHASE` for block PHP.

What do you think @talldan?

**Comment by tellthemachines** [comment]
#36604 removes those functions from Gutenberg. It's approved, but has been sitting there for a few days and has a bunch of conflicts. From the convo there was uncertainty about whether this should go into 5.9, but given it removes functionality that shouldn't be in core, backporting it would fix the issue here.

**Comment by talldan** [comment]
These were already removed for the navigation block in the plugin in https://github.com/WordPress/gutenberg/pull/36336. `lib/navigation.php` isn't the block's PHP. That's in the block-library package.

**Comment by tellthemachines** [comment]
@talldan those functions are still in the latest trunk, e.g. [here](https://github.com/WordPress/gutenberg/blob/trunk/lib/navigation.php#L353)

**Comment by talldan** [comment]
Ok, @noisysocks has corrected me, and it's not so much that the functions exist, but that they are called.

**Comment by talldan** [comment]
> @talldan those functions are still in the latest trunk, e.g. here

Yeah, but they shouldn't be deleted, they're in use in the plugin. Functions in that file will be renamed when copied to trunk.

The issue is that the block's php file is copied automatically and so the call site of those functions is wrong.

**Comment by talldan** [comment]
So for some more background, these functions are for the `__unstableLocations` feature in the nav block, it's used to render a classic menu on the front end of a user's site. It's a plugin only feature that still needs some work.

They were also used by navigation area block, but the navigation area feature has been or will be removed.

So I think the quandry is how do we handle unstable code given the block php is automatically copied across to core.

Now that they're only used by the navigation block I think the following could be possible.
- Move the functions back into the block's php file and rename them with a `_block_core_navigation` prefix
- Define a constant like `IS_GUTENBERG_PLUGIN` in the gutenberg plugin
- Wrap the functions in an if statement that checks `defined( IS_GUTENBERG_PLUGIN )`
- Also gate where the functions are called using the same check.

**Comment by noisysocks** [comment]
> Move the functions back into the block's php file 

This bit isn't strictly necessary. Gating the part of `navigation/index.php` which calls these functions makes sense though.

**Comment by talldan** [comment]
> This bit isn't strictly necessary. Gating the part of navigation/index.php which calls these functions makes sense though.

True, I'd just prefer to have the function references be correct so that they can be traced to the callsite.
