### ISSUE TITLE
Template panel displays 404 as the selected template for drafts

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#36986]
### Description

When you activate a theme with support for template editing and create a new post or page,
the Template panel in the block editor shows that the 404 page is current template.
Once published, the current template is displayed as page or post respectively.

### Step-by-step reproduction instructions

1. Install 5.9-alpha-52272
2. Activate a theme with support for template editing, for example Twenty Twenty-Two
3. Create a new post or page and view the Template section.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/7422055/143997051-9b317047-5f22-4bd5-8151-65c56ecb31f3.mp4

### Environment info

WordPress 5.9-alpha-52272 via the beta tester plugin.
Gutenberg is not active.
Windows 10, Chrome.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by noisysocks** [comment]
Related: https://github.com/WordPress/gutenberg/issues/33940

I looked into this and the bug only exists in Core and not when the Gutenberg plugin is activated. The problem is that the AJAX request being made to `?p=26&_wp-find-template=true` is 404ing. You can confirm this in DevTools by opening the post editor.

I see code in Core which is supposed to handle the `_wp-find-template` query param but it doesn't look like `locate_block_template` is hooked into `wp_loaded` or anything like that.

https://github.com/WordPress/wordpress-develop/blob/5fa8d73b1b22ff72f06ae53c07cf2887a4f4b60a/src/wp-includes/block-template.php#L61

I suspect something was missed while backporting the block theme infrastructure in https://core.trac.wordpress.org/ticket/54335 cc. @ockham 

I'll move this issue to Trac since that's where the fix needs to land.

**Comment by noisysocks** [comment]
Let's move to https://core.trac.wordpress.org/ticket/54553.

**Comment by carolinan** [comment]
@noisysocks thank you!
