### ISSUE TITLE
Accessing the scrollTop of scrollContainer (`.interface-interface-skeleton__content`) is throwing in BlockStyles

### ISSUE THREAD

**Issue by alshakero** [WordPress/gutenberg#36999]
### Description

The `BlockStyles` component does some calculation to figure the right position of the `BlockStylesPreviewPanelFill`. It uses the `scrollTop` of `scrollContainer (.interface-interface-skeleton__content)`, which can be null at times, thus throwing an error.

The bug was likely introduced in https://github.com/WordPress/gutenberg/pull/34522. I don't fully understand the changes in #34522, but this tiny change in [this line](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-styles/index.js#L63) might be sufficient to resolve the issue:

```diff
- setContainerScrollTop( scrollContainer.scrollTop + 16 );
+ setContainerScrollTop( scrollContainer?.scrollTop ?? 0 + 16 );
```

### Step-by-step reproduction instructions

See https://github.com/Automattic/wp-calypso/issues/56922#issuecomment-981143542.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

cc @ramonjd

**Comment by tellisbethel** [comment]
I have a user running into the error: `TypeError: Cannot read properties of null (reading 'scrollTop')`. This happens when they try adding anything to their sidebar widget on their [Tojours theme](https://wordpress.com/theme/toujours/).

I was going to add their case to the following report, but the highlighted comment led me here: 
https://github.com/Automattic/wp-calypso/issues/56922#issuecomment-982587438

Let me know if more info, like the full error message, is necessary, or if I'm posting in the wrong place! :)

**Comment by ramonjd** [comment]
Thanks for the report everyone. I'll look into this.
