### ISSUE TITLE
Heading text is added to HTML anchor

### ISSUE THREAD

**Issue by tomektomczuk** [WordPress/gutenberg#37040]
### Description

Whatever you type to the heading this text is automaticly added to HTML anchor

### Step-by-step reproduction instructions

1. Add Heading block
2. Type any text
3. Open Advance setting the text is automatically added to the anchor

### Screenshots, screen recording, code snippet

<img width="1767" alt="Screenshot 2021-12-01 at 17 15 37" src="https://user-images.githubusercontent.com/40096666/144271292-d1ed8d1d-4d0e-436d-b8c3-0e89265e3a30.png">

### Environment info

WordPress 5.8.2
Gutenberg 12.0.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Hi, 
This is an intentional feature that was introduced in https://github.com/WordPress/gutenberg/pull/30825#issuecomment-959051708 

There is no way to disable the feature at this time but this was reported at https://github.com/WordPress/gutenberg/issues/36365 where you can follow its progress and share your experience with it.
