### ISSUE TITLE
Make it easier to select other templates

### ISSUE THREAD

**Issue by akirk** [WordPress/gutenberg#37251]
## What problem does this address?
Right now, if you want to choose another header template, you need to know that you need to select the header inside the Gutenberg editor and click "Replace":

![Screenshot 2021-12-09 at 12 17 05](https://user-images.githubusercontent.com/203408/145386837-c71fc257-ebec-4d54-9c55-f9170407271e.png)

## What is your proposed solution?
Think about adding the ability to choose the header template in other places. This is where I tried before I found the "Replace":

![Screenshot 2021-12-09 at 12 36 02](https://user-images.githubusercontent.com/203408/145389616-11259e5d-94a5-4a37-bd5d-a1e2c52a97ab.png)

![Screenshot 2021-12-09 at 12 36 31](https://user-images.githubusercontent.com/203408/145389680-9aa24990-85d7-4bd9-adfd-c2618bd8fa13.png)

![Screenshot 2021-12-09 at 12 37 50](https://user-images.githubusercontent.com/203408/145389743-dafb7f14-1da9-47f4-b792-4898b410e88d.png)

Also the word "Replace" works only in the context of the editor when you compare it to how you change an existing image in an image block. But I'd propose to use something like "Select template" instead.

**Comment by karmatosed** [comment]
This is interesting because for me going to the header itself was natural to click replace. I went there first.

![2022-01-07 at 18 54](https://user-images.githubusercontent.com/253067/148592958-599a4282-55c2-4e28-9c5e-ae869a258b8b.png)

I think I have concerns about 'replace' showing over the list view to get a little complex, but again that might be because I feel the replace flow matches other cases we have like the media flow.

![2022-01-07 at 18 56](https://user-images.githubusercontent.com/253067/148593127-791cfbee-df37-4322-ada2-4d703ebcf563.png)

**Comment by youknowriad** [comment]
![Image](https://github.com/user-attachments/assets/c7d045e1-357b-4b5a-a75f-540e6e9f3f17)

We know show alternative designs on the sidebar when you select the header. If you think it's not enough or have other ideas please consider opening an issue with some concrete action items;
