### ISSUE TITLE
Provide a get_site_editor_url() function so plugins can link to the site editor

### ISSUE THREAD

**Issue by Aljullu** [WordPress/gutenberg#37277]
### Description

The Site Editor URL changes depending on the environment. On WP 5.9 it's `site-editor.php`, while on WP 5.8 + GB it's `themes.php?page=gutenberg-edit-site`. Currently, if a plugin wants to link to the Site Editor or to a specific template or template part, they need to check the version of WP to be able to generate the correct URL.

It would be ideal if WP had a function that returned the correct URL (something like `get_site_editor_url()`), simplifying the life for plugin devs and making their code less likely to break in the case of future changes.

### Real life use-case

In WooCommerce we are creating the Mini Cart block, which includes a link in the editor sidebar to edit the template part associated with it. Currently, we would have to check the WP version in order to generate a link that works in WP 5.8 + GB and WP 5.9 ([see PR](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5348)).

### Step-by-step reproduction instructions

-

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by gigitux** [comment]
I started to work on this issue. I have more details to share with you.
I noticed that the URL is `site-editor.php` only when GB is disabled and WP version is 5.9.
From what I understand FSE will merge in `core`, but maybe GB will start to diverge from WP 5.9. So in the end I think that we should redirect to `themes.php?page=gutenberg-edit-site` if GB is enabled and to `site-editor.php` otherwise.

I would really like that this is as handled automatically by the core or maybe by the plugin (I don’t know if plugins can intercept endpoint and do redirect).
So the developers will point to the user always to `site-editor.php`, but the system will intercept the request and will redirect the user to the right endpoint.

@Mamaduka @kevin940726

**Comment by noisysocks** [comment]
When the Gutenberg plugin is updated to require WP 5.9 at minimum we will remove `themes.php?page=gutenberg-edit-site` and the URL will always be `site-editor.php`. I therefore don't think adding `get_site_editor_url()` is very valuable. 

I'd recommend just switching based on the version.

```php
global $wp_version;
if ( version_compare( $wp_version, '5.9', '<' ) ) {
	$url = admin_url( 'themes.php?page=gutenberg-edit-site' );
} else {
	$url = admin_url( 'site-editor.php' );
}
```

**Comment by dinhtungdu** [comment]
@noisysocks It makes sense to me. Thanks for the suggestion. @Aljullu I think this issue can be closed.
