### ISSUE TITLE
Site Editor: Template Part gets emptied on undo

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#37361]
This is a strange one. Take a look at the video below:

https://user-images.githubusercontent.com/846565/145984278-585920fc-aa1f-447a-8973-6ed155cd7d40.mp4

The Group block in my template has a padding value applied by my theme. If I reset the padding via design tools and then undo that action, my template parts are mysteriously emptied of all blocks.

**Comment by jameskoster** [comment]
_Possibly_ related to https://github.com/WordPress/gutenberg/issues/36937?

**Comment by Mamaduka** [comment]
I think this is a regression after #37283.

**Comment by Mamaduka** [comment]
The same happens with Reusable blocks and I'm also able to reproduce this by running following code in console:

```js
const blocks = wp.data.select('core/block-editor').getBlocks();
wp.data.dispatch('core/block-editor').resetBlocks(blocks);
```

I think the `tree[ 'controlled||' + clientId ]` is lost when running `RESET_BLOCKS` action.

**Comment by youknowriad** [comment]
> I think the tree[ 'controlled||' + clientId ] is lost when running RESET_BLOCKS action.

In my thinking that should have been fine because "resetting" means the controlled blocks should bring back their content again from "core" store. I guess it doesn't work though because these controlled blocks are not "remounting" in this case.

So yeah, I guess we have two options:

 - Try to compare the incoming list of blocks with the blocks already in state (and retain all the controlled blocks keys that are still in the incoming list but also retain all the blocks that are inside them => the logic might not be that easy, we could restore the previous logic but it was a bit naive and we'd be restoring the other fixed issue)
 - Try to see if there's a way to notify the "controlled blocks" that they should prefer the "external value" over the "internal" after a "RESET"

**Comment by Mamaduka** [comment]
@youknowriad, I started working on suggested options (or tried) but soon realized that I wouldn't be able to come up with the fix in time for the last beta.

**Comment by youknowriad** [comment]
I'll try to find some time to take a look as well, I wonder if we should revert in the meantime?

**Comment by Mamaduka** [comment]
> I wonder if we should revert in the meantime?

Let's revert for now. This issue will affect more users. The previous one only affects the Site Editor in specific conditions.
