### ISSUE TITLE
Template Editor toolbar dropdown broken

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#37427]
### Description

When editing a template via the template editing mode in the post editor, the dropdown in the toolbar appears to be broken.

### Step-by-step reproduction instructions

1. Use a block theme or theme supporting template editing mode
2. Head to a post or page
3. Under Templates in sidebar > Edit
4. Try to click the dropdown in the toolbar.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/146278794-9e1090d8-0a39-4cf7-91c6-e3e288d43c75.mov

<img width="388" alt="Screen Shot 2021-12-15 at 6 06 43 PM" src="https://user-images.githubusercontent.com/26996883/146278807-37b02bfa-637e-49ed-937c-20997b3793c6.png">
<img width="410" alt="Screen Shot 2021-12-15 at 6 07 57 PM" src="https://user-images.githubusercontent.com/26996883/146278874-f15137de-fca5-4c4c-a674-ddf767370225.png">

### Environment info

- WordPress 5.9 beta 3
- No GB
- TT2 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment]
It looks like part of the issue here is that if a template has a template file then the drop down is supposed to display the template description:

<img width="369" alt="Screen Shot 2021-12-16 at 3 59 48 PM" src="https://user-images.githubusercontent.com/3629020/146300662-eb67324a-15a8-4a55-afa5-b7563afcb182.png">

... but some templates don't have a description:

<img width="255" alt="Screen Shot 2021-12-16 at 4 00 35 PM" src="https://user-images.githubusercontent.com/3629020/146300731-eee86ac9-383e-402b-9f02-dbcf3ee03343.png">

There seem to be two ways that we could fix this if `template.has_theme_file && template.description === ''`:

1. Just display the template title with no dropdown
2. Display the dropdown with a generic fallback message

Option 1. seems like a good option as there doesn't seem to be any need to show the dropdown if no description, but I haven't worked on this area at all so there may be something I am overlooking.

**Comment by Mamaduka** [comment]
I think I know the reason for the regression. I will push the fix for the issue shortly.
