### ISSUE TITLE
Wrong usage of `_n()` in WP 5.9 beta 3 translatable strings

### ISSUE THREAD

**Issue by audrasjb** [WordPress/gutenberg#37471]
### Description

_This issue is copy pasted from https://core.trac.wordpress.org/ticket/54638.
Thanks @tobifjellner for the report._

---

The new code for WordPress contains three instances where the "Template Part"/"Template Parts" string pair is used.
However, this is usage of _n() is incorrect.

If you want to handle just the singular and plural terms, then this should be handled in the code (if 1 == n then ...) and not by using _n()
Alternatively, if these strings are used together with the relevant number, then a placeholder for the count variable should be present in the string (i.e. printf)
Three references (to the current as-built package)
https://build.trac.wordpress.org/browser/trunk/wp-includes/js/dist/editor.js?marks=5220#L5220
const entityLabel = name === 'wp_template_part' ? Object(external_wp_i18n__n?)('Template Part', 'Template Parts', list.length) : entity.label; Set description based on type of entity.

https://build.trac.wordpress.org/browser/trunk/wp-includes/js/dist/block-library.js?marks=38830#L38830
https://build.trac.wordpress.org/browser/trunk/wp-includes/js/dist/editor.js?marks=5220#L5220

### Step-by-step reproduction instructions

https://github.com/WordPress/gutenberg/blob/5604b2323e57f0125ad8fb8dc5423c067978b128/packages/editor/src/components/entities-saved-states/entity-type-list.js#L52-L55

### Environment info

- WordPress 5.9 beta 3
- Gutenberg not installed

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ocean90** [comment]
The same applies to https://github.com/WordPress/gutenberg/blob/5604b2323e57f0125ad8fb8dc5423c067978b128/packages/editor/src/components/entities-saved-states/entity-type-list.js#L19-L37.

**Comment by aristath** [comment]
Before making any changes to this behavior, please keep in mind that not all languages have the same concept of singular/plural as English. For example, there are languages where the plural for 2 is different than the plural for 3 and so on.

**Comment by Mamaduka** [comment]
I'm removing this issue from WP 5.9 project board since RC1 was released yesterday.

Let's try and land a fix for this in a minor release.

**Comment by Mamaduka** [comment]
Maybe we can drop the label and description variations altogether. Instead, use singular form for labels and plural for descriptions. All other labels are in this form, making it consistent.

@ockham, what do you think?

**Comment by ockham** [comment]
Hey @Mamaduka, thanks for the ping!

@aristath [Your point](https://github.com/WordPress/gutenberg/issues/37471#issuecomment-997676136) about differentiating between plural forms is very valid and the reason why I used `_n()` in the first place. However, since we're dealing with "indefinite" plurals here (without a number), we might not have to worry about those. (E.g. I think pretty much all languages have a unique translation of `These changes` or `these templates`, where it's unknown if it's 2, 3, or x.) So we can probably use the `if ( 1 === n ) { ... } else { ... }` logic here.

That said, I was a bit surprised here since I believed that `_n()` was the right way of providing singular/plural versions of a string, even if it didn't include the number itself. I don't see that documented in the [docs](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-i18n/#n) for the JS version of `_n()` -- is that something we need to add? I'd also be curious to learn why this is discouraged 🙂 

@Mamaduka That could be an alternative; however, IIRC, I added the different versions for singular and plural in response to a designer's feedback that suggested doing so in order to make the copy correspond better to the number of changes (i.e. checkboxes) the user sees:

![image](https://user-images.githubusercontent.com/96308/162976829-ff4576e5-7d77-4861-b2e4-e0c09e9e4944.png)

**Comment by Mamaduka** [comment]
Thanks for the feedback, @ockham.

I think `( 1 === n )` is a simple enough change for this case so that we can go with it. I will follow up with PR later today or tomorrow morning.

Re `_n` usage, I was only able to find this comment explaining the issue - https://developer.wordpress.org/reference/functions/_n/#comment-2397.
