### ISSUE TITLE
Auto-select the alphabetical choice in forward-slash inserter command

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#37532]
The forward-slash inserter command right now for 'ima' shows this:

![2021-12-20 at 17 22](https://user-images.githubusercontent.com/253067/146807263-2cd96023-7702-4fd8-8a1c-304b54923301.png)

I would have expected 'Image' to be the one selected and added first. This has caught me a number of times when in flow by adding Imgur not Image. Not only can we likely assume someone wants Image block more, it also feels like it wasn't applying any alphabetical or obvious (to me) listing.

I'm curious what others think.

**Comment by Mamaduka** [comment]
Hi, @karmatosed

I can see the "Image" block correctly selected when I try `ima`, but I get the same results as you with `img`.

![CleanShot 2021-12-30 at 16 00 54](https://user-images.githubusercontent.com/240569/147750278-e234414a-d131-4bfb-bb87-9e34883f6432.png)

**Comment by annezazu** [comment]
With WordPress 5.9, I see the following for /ima:

<img width="361" alt="Screen Shot 2022-02-06 at 7 30 01 PM" src="https://user-images.githubusercontent.com/26996883/152720093-bc62ee92-9aff-4a57-8ec5-245c9c8de202.png">

However, if I try /img, I then see the reversed results:

<img width="344" alt="Screen Shot 2022-02-06 at 7 30 05 PM" src="https://user-images.githubusercontent.com/26996883/152720124-d86400da-3715-446c-a7d4-c2a276be8562.png">

This feels like an easy win and was noted as feedback as part of the [FSE Outreach Program's All Things Media exploration](https://make.wordpress.org/test/2022/02/02/fse-program-exploration-all-things-media/#comment-2303):

>Using / and img always also adds Imgur embed option. Which I have never heard of and do not plan to use. It would be nice to not so easily show embeds that are not much used.

**Comment by paaljoachim** [comment]
Thank you for opening the issue Tammie!

I would prefer not to see Imgur every time I write /img as Imgur is not a service I plan on using or have heard of. Having a way to make less used embeds just a little more hidden would be helpful. This could for instance mean that writing / Img only Image will show up but writing Imgu will show Imgur embed service.

Here is an associated issue:
Show inserter block variations in the block manager and allow them to be toggled
https://github.com/WordPress/gutenberg/issues/27708

I know Nik @ntsekouras has earlier worked on this. I believe also @jasmussen Joen has some thoughts on it as well.

**Comment by ntsekouras** [comment]
👋 This is expected. The thing is that we use a generic algorithm for `ranking` them [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/inserter/search-items.js#L142) and IMO this works well. It prioritizes the results based on the searched term and if we would sort them alphabetically, the results would be less relevant.

The above case happens because the `img` is part of the block variation's title(`imgur`) and I can't think of any adjustment that could be generic and work well in all scenarios.

On the other hand though this feels like an important but very specific request and we could handle this on it's own. A specific approach for this would be [here](https://github.com/WordPress/gutenberg/pull/38589), where I change the title of `Imgur` variation to `Embed Imgur`.

**Comment by karmatosed** [comment]
Thank you everyone. Today if you still type 'img' you get the img embed. I think as no action has happened and that PR is now out of date, I am ok closing this. If someone wants to create a quality of life PR that's awesome but as it works as expected that is ok for me.
