### ISSUE TITLE
Gaps in current global styles

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#37550]
This is a tracking issue to highlight the next big steps we can tackle to implement the original vision of the global styles (merge default, theme, and user styles) to improve both the developer experience and the performance.

Absorb the two big missing style pieces via the `theme.json` algorithm:

- Block styles: https://github.com/WordPress/gutenberg/issues/33977
- Style variations: https://github.com/WordPress/gutenberg/issues/33232

Performance:

- Do not output block styles for blocks that aren't used on the page: https://github.com/WordPress/gutenberg/issues/31642
- Track performance https://github.com/WordPress/gutenberg/issues/34329

**Comment by conatus** [comment]
Hello there!

Thanks for your work on all this.

### The Feature - Control UI for individual blocks

I've been tracking the movement of a specific use-case: controlling the visibility of UI controls in the Block Editor using `theme.json`. 

For example: a theme editor wants people to be able to remove elements in the UI of the button block controls, e.g. size. 

This is so they can restrict how much a user can do in order to keep the general aesthetic of the website on track and prevent the user from being overwhelmed by choices when modifying a block.

### How did we get here

Here is a path for all this:
- This feature was brought up on https://github.com/WordPress/gutenberg/issues/20588
- This issue was consolidated in favour of #20331 and #28163
- #28163 contains the bulk of the discussion of this feature
- The feature was mentioned in the issue description, but not in the thread beneath.
- The issue #28163 was closed out and consolidated in favour of #20331. It wasn't brought up on #28163 again.
- #20331 was  closed out in favour of this issue, which doesn't quite include this feature which was discussed initially at #20588

### My Questions

Recognise that there is a lot going on :)

Bit conscious it feels like this feature, which there is some desire from the community for some time doesn't have an issue tracking it that is visible to engineers on your side working on it.

My questions are:
- Is there some issue tracking this feature I have missed?
- If not, can we create one?
- If this isn't planned for any time soon, then where would we be able to track this?

Do let me know if this is the wrong place to comment.

Thanks so much!

**Comment by oandregal** [comment]
Hi @conatus If I understand correctly, the question is whether there's an issue for tracking modifications to theme.json? We had an overview task in the past to plan the work ahead. Now, they're created as the needs evolve to control more of the UI and involve changes to UI, theme.json, etc.

There's also [reference docs](https://developer.wordpress.org/block-editor/reference-guides/theme-json-reference/) for the different versions of theme.json and we should improve the [example documentation](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/) soon as well.

If you have anything specific in mind that is not implemented yet, would you create a new issue if there isn't one?

**Comment by conatus** [comment]
Hi @oandregal 

Thanks for your help! I will take a look at those links, but to clarify this isn't about tracking modifications to the theme.json.

What this is about is: there is some control of the Block UI on an individual block we want to not show to the user. 

For example, we want to remove the ability for them to control alignment on button blocks. This is so we keep the design consistent and to restrict the number of options a user has to consider.

The closest issue I can find around this issue is #27295. I haven't read it yet, but can see you wrote it, so hopefully can point me in the right direction.

#33891 also concerns the feature I am thinking of, though doesn't to have been responded to by someone on the team.

**Comment by oandregal** [comment]
> For example, we want to remove the ability for them to control alignment on button blocks.

Hi @conatus I don't think this is something that can be disabled via `theme.json` at the moment. If there isn't already one, you could create an issue with this specific need. Specific issues are easier to navigate than general ones.

**Comment by conatus** [comment]
Hey @oandregal 

Rather than create a new issue, should we considate conversation over at https://github.com/WordPress/gutenberg/issues/33891? 

There is a lot of conversation on this feature across GitHub, including by yourself - for example https://github.com/WordPress/gutenberg/issues/27295 - though you are suggesting this is not the same thing.

**Comment by conatus** [comment]
This seems to be exactly what is needed. 

https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#settings-for-the-block-editor

"Settings for the block editor...What customization options should be made available or hidden from the user."

Does this make sense?
