### ISSUE TITLE
Next Comments Block: Link showing on the last page when selecting a custom "items per page" setting.

### ISSUE THREAD

**Issue by cbravobernal** [WordPress/gutenberg#37560]
## What problem does this address?

The error is available near the end of the video:

https://user-images.githubusercontent.com/699132/146942214-7cae3c4f-4d76-4d12-8a2e-ab382248edb6.mov

When selecting a custom setting for items per page, the `Next Comments` links show up even when we are on the last page.
Similar to #37553 

## What is your proposed solution?

We will check why is happening after we land #37297 and create a PR accordingly.

**Comment by gziolo** [comment]
It looks like there is the only one case where the link to Older and Newer Comments are wrongly displayed is with these settings:

<img width="865" alt="Screenshot 2022-02-17 at 10 55 42" src="https://user-images.githubusercontent.com/699132/154451312-97948f98-d15f-4bc4-aa77-f5ca8f4c4a46.png">

There should be Older Comments rather than Newer Comments link:

<img width="706" alt="Screenshot 2022-02-17 at 10 55 35" src="https://user-images.githubusercontent.com/699132/154451303-0fd7f55e-5d23-4b5a-876f-f57b5941d98d.png">

**Comment by SantosGuillamot** [comment]
There is another related use case where the pagination is not working properly.

When the option "Last page displayed by default" is enabled, and you go to the penultimate page, the "Next Comments" link is pointing to `#comments`, which is wrong.

I've been running some tests (I will create a PR later) and it seems this is caused by the [get_comments_pagenum_link function](https://developer.wordpress.org/reference/functions/get_comments_pagenum_link/), used by these blocks. It is adding this conditional `if ( 'newest' === get_option( 'default_comments_page' ) && $pagenum = $max_page )` and, when that happens, it doesn't create the link properly. Removing that check seems to solve this issue.

## Steps to reproduce
1 -  Enable the "Last page displayed by default" setting.
<img width="865" alt="Screenshot 2022-02-17 at 10 55 42" src="https://user-images.githubusercontent.com/699132/154451312-97948f98-d15f-4bc4-aa77-f5ca8f4c4a46.png">
2 - Go to a post with comments pagination and go to the penultime page.
3 - You can check that the "Next Comments" link is pointing to `#comments` instead of the proper page.
<img width="841" alt="Screenshot 2022-03-04 at 18 49 34" src="https://user-images.githubusercontent.com/34552881/156815597-9f747767-3a35-484c-8dad-66239e1f5574.png">

**Comment by hellofromtonya** [comment]
Issue: block's settings do not override global settings

I can reproduce ✔️ 

# Test Report

## Env
 - OS: macOS Big Sur
 - Localhost: wp-env
 - Browsers: Edge, Firefox, Chrome, and Safari
 - Theme: TT2
   
## Setup and Testing Steps
 - Go to Settings > Discussion and set these settings:
    - Check `Break comments into pages`
    - `2` top level comments per page
    - `first` page displayed by default
    - `older` comments at the top of each page
![Screen Shot 2022-03-09 at 3 55 37 PM](https://user-images.githubusercontent.com/7284611/157543304-c66b11dd-8437-43f6-a5e9-8cc059ae963b.png)
- Go to Posts > Add New to create a new post
- Add in the Comments Query Loop block with these settings
    - Order by: Newest to oldest
    - Default page: Newest
    - Items per Page: 3
       
![Screen Shot 2022-03-09 at 3 55 30 PM](https://user-images.githubusercontent.com/7284611/157543339-8c098ef2-ce8e-46e4-924e-113af489a602.png)
 
   - Publish the post
   - View on the front end
- Add 10 comments (not replies)
- Refresh the page
- Click on `2` in the Comments Query Loop block's pagination
- Hover over the `Older Comments` link and notice its URL
- Click on the `Older Comments` link. **Expected behavior**: it should go to page 1.
     
## Results

When on `cpage=2`, the `Older Comments` link's URL does not have a `cpage` query var. 
When clicking it goes to the last page of the comments.

![WrongOlderCommentsLInkURL](https://user-images.githubusercontent.com/7284611/157543985-740cdf20-d49a-4900-a4ff-e08d94aadc62.gif)

Values:
- `cpage`'s value is correct without having to set it via `set_query_var()`.
- `get_option( 'default_comments_page' )` is set to `oldest`

### Call stack

- `gutenberg_render_block_core_comments_pagination_previous()` calls `get_previous_comments_link()`
- `get_previous_comments_link()` 
    - gets the `cpage` query var value (which is `2`) and subtracts 1 from it, i.e. to point to the previous page
    - calls `get_comments_pagenum_link()` passing a `1` to it as the previous page number
- `get_comments_pagenum_link()` [See the code here](https://github.com/WordPress/wordpress-develop/blob/6b224e3ac043009663be61c6646841c0fe45bf0a/src/wp-includes/link-template.php#L2955-L2969).)
   - grabs the page's URL
   - checks the first conditional which fails as `get_option( 'default_comments_page' )` is `oldest` not `newest`
   - checks if the previous page number is > 1 => it's not so it skips this conditional check too

## Thinking here

It's not due to `cpage` as that is being set correctly. Rather, it's because `get_comments_pagenum_link()` is not aware of the block's local settings but rather is using the global settings.

## What about classic themes like TT0 and TT1?

TT1 and TT0 are using `paginate_comments_links()` which calls `paginate_links()` where the next ("newer") and previous ("older") links do always have the `cpage` query var in the URL.

![classiccomments](https://user-images.githubusercontent.com/7284611/157553725-9c6b2e75-6493-4e6b-ac05-3ab937f8f3e9.gif)

## Next steps

- [ ] Investigate why the pagination code is different in `paginate_links()`.
- [ ] Explore making `get_comments_pagenum_link()` block local settings aware.

**Comment by ironprogrammer** [comment]
In response to @hellofromtonya:

> Investigate why the pagination code is different in `paginate_links()`.

TT0 and TT1 utilize `paginate_links()` to generate ALL comment navigation links, including prev/next AND the numeric pagination. This is enabled by setting `$args['prev_next'] = true`. "Previous" links generated by this function always include the comments page slug, e.g. `comment-page-1` ([code reference](https://github.com/WordPress/wordpress-develop/blob/8a64e9fef9c9eae3a36862bd4de1d7b430d89498/src/wp-includes/general-template.php#L4284-L4304)). This matches the test result's "Older Comments" link that was [reported above](#issuecomment-1066689344).

For comparison, TT2 utilizes `paginate_links()` ONLY for the pagination links (i.e. `$args['prev_next'] = false`), and uses `get_previous_comments_link()` and `get_next_comments_link()` to generate prev/next links. The "previous" link generated in this case specifically omits the comments page slug when the default comments page is "first" and the previous page's index is `1` ([code reference](https://github.com/WordPress/wordpress-develop/blob/8a64e9fef9c9eae3a36862bd4de1d7b430d89498/src/wp-includes/link-template.php#L2955-L2971)).
