### ISSUE TITLE
Hovering on Padding/Margin control creates undo level

### ISSUE THREAD

**Issue by Mamaduka** [WordPress/gutenberg#37606]
When I hover over on Padding or Marging control, it creates "undo level" in the editor.

I can see `EDIT_ENTITY_RECORD` in Redux logs, triggered by `onChangeShowVisualizer.`

## How to reproduce
1. Add a Group block to a post.
2. Open the "Dimensions" panel and hove over padding control.
3. New "undo level" is created.

Tested with TT2, Gutenberg trunk, and WP 5.9-beta4.

## Screencast
https://user-images.githubusercontent.com/240569/147198719-c3746612-4116-41b9-a59c-dfb3387159f8.mp4

**Comment by aaronrobertshaw** [comment]
Thanks for the ping @Mamaduka.

I think this might be a duplicate of https://github.com/WordPress/gutenberg/issues/36418.

There are some open PRs relating to this problem already. 
- https://github.com/WordPress/gutenberg/pull/33560
- https://github.com/WordPress/gutenberg/pull/36587

As you note, this issue is due to the box control visualizers storing its data within the block attributes. Rather than duplicate or fork the discussion, I'd suggest we close this issue and continue it on https://github.com/WordPress/gutenberg/issues/36418 or the PR most likely to proceed (https://github.com/WordPress/gutenberg/pull/33560).

**Comment by Mamaduka** [comment]
Thank you, @aaronrobertshaw. The #33560 looks like a good candidate.
