### ISSUE TITLE
Navigation Editor: ability to disable via filter

### ISSUE THREAD

**Issue by superbmario** [WordPress/gutenberg#37640]
Much like the filters to disable the new Widgets editor, will there be a filter to disable the new Navigations editor?

Currently for widgets:

```
// Disables the block editor from managing widgets in the Gutenberg plugin.
add_filter( 'gutenberg_use_widgets_block_editor', '__return_false' );
// Disables the block editor from managing widgets.
add_filter( 'use_widgets_block_editor', '__return_false' );
```

For Navigation I assume the following? Building on the comments at https://github.com/WordPress/gutenberg/issues/24683#issuecomment-903755241

```
// Disables the block editor from managing navigations in the Gutenberg plugin.
add_filter( 'gutenberg_use_navigation_block_editor', '__return_false' );
// Disables the block editor from managing navigations.
add_filter( 'use_navigation_block_editor', '__return_false' );
```

**Comment by superbmario** [comment]
After trying WP 5.9 RC3, I can see that the 'Appearance > Menus' page is not changed to Gutenberg like the 'Appearance >Widgets' page was. So if I understand correctly, a filter to disable that from happening will not be required. Therefore this issue could be closed if so.

**Comment by kathrynwp** [comment]
Closing this issue due to the Navigation Screen project being moved to [an inactive status on the feature projects page](https://make.wordpress.org/core/features/) in coordination with the project leads. (The developer documentation in the initial post are no longer accessible)

If this work is picked back up, issues can be revisited and reopened as needed. Thanks for pitching in on this early feature so the wider WordPress project could benefit from the lessons learned!
