### ISSUE TITLE
Give categories a full gutenberg editor

### ISSUE THREAD

**Issue by gingerling** [WordPress/gutenberg#37746]
## What problem does this address?

In my store, the top two pages people arrive at from google are categories. It's super frustrating that I can't fully edit these pages, both for customer information and SEO, I would love to be able to edit each category with the full gutenberg experience. I could made beautiful pages with links to key products, blogs, with images and information. Google, myself and most importantly my customers would be happy. It would work great with the new templates system too!

## What is your proposed solution?

When you click edit on the category, you don't get the basic text editor

![Screenshot from 2022-01-06 10-56-57](https://user-images.githubusercontent.com/2853040/148379269-5fd2aa42-e66d-4676-aa5a-d7f09b26dc0c.png)

![Screenshot from 2022-01-06 10-57-13](https://user-images.githubusercontent.com/2853040/148379489-7e40a59e-fe55-4eac-96c2-41764f6f675b.png)

You get a full editor.

The blocks you add create the content that goes at the top of category page. It will probably be a few hundred words as normal BUT you can have really engaging info like key products, blogs, quotes, buttons... videos... images!

![Screenshot from 2022-01-06 11-04-01](https://user-images.githubusercontent.com/2853040/148379690-49e7f783-1355-4e01-b4bf-25ef69488f33.png)

Then, when you're done and publish it - the category archives show below that.

![Screenshot from 2022-01-06 11-06-49](https://user-images.githubusercontent.com/2853040/148379387-359a4212-f48c-4bc0-a8dc-ad043379ff98.png)

It seems like the templates system is trying to achieve this in a way, for example woocommerce blocks have done this:

![Screenshot from 2022-01-06 11-24-07](https://user-images.githubusercontent.com/2853040/148380045-ca91f113-0fe0-46ab-98d1-2c8e348ba9b4.png)

However I don't think WordPress should end up with people creating a new template for each category page. It seems simpler from a user perspective just to allow full editing of archive pages to begin with. 

Of course this still works brilliantly with templates - category pages might be treated more like a landing page, for example - stripping out some design elements to focus the user. That's what the template would do.

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting and all of the detailed pictures and clear use case :) 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/17099. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue. 

Please reopen if I'm misunderstanding and you're looking for something different than in #17099

**Comment by jamiemarsland** [comment]
Hi, just to jump in here - we have a plugin that lets you customize a block theme woocommerce category pages - https://www.pootlepress.com/storefront-blocks/ We updated it last month so it works with block themes and fse - there's an explanation here https://youtu.be/V0uWuXXOjr4.

**Comment by WesCook** [comment]
A native solution would definitely be appreciated.  I tried the Storefront Blocks plugin as mentioned in an above comment, as part of their Blocks bundle, and it was one of the worst WordPress experiences I've had in years.  It was full of bugs, barely worked with classic themes, and after a year of no updates they forced a paid renewal without any notice.  Support didn't respond once to any requests.  It's not a good option here.

Regardless, the plugin's solution was to simply map a category to a regular page with a redirect.  It doesn't actually add the Gutenberg editor to the categories themselves.  That's not a good approach because it introduces 301s into regular navigation, and requires two URLs to maintain.

A real upgrade to category pages is needed.  I understand there's some issues in how the data is currently stored in the backend, but modifying the schema should be possible.  Categories are an important part of many website's designs - especially on eCommerce sites where they tie together different products.

More than just enabling Gutenberg, I would also expect category pages to work in contexts like query loops to pull in all relevant posts/products.  Certainly [WooCommerce Blocks](https://woocommerce.com/document/woocommerce-blocks/) could make use of that functionality as well.

It would also be useful if the standard loop could be disabled so that custom loops could be used instead.  While it's possible this could be detected heuristically (eg. is a query loop in use?), I think an actual checkbox would be more explicit and easier to reason about.

If the question is, "Why even use a category page at that point"?  It's because it's more semantic, better organized in the backend, the slugs will be accurate to your site's hierarchy, and 301s won't be required during navigation (these are bad for SEO, and can drop information like query strings on click).
