### ISSUE TITLE
Not all dashicons can be specified for `icon` in block.json

### ISSUE THREAD

**Issue by csalzano** [WordPress/gutenberg#37761]
### Description

The documentation for block.json says a dashicons slug can be provided in the `icon` property.

> An icon property should be specified to make it easier to identify a block. These can be any of WordPress’ Dashicons (slug serving also as a fallback in non-js contexts).

https://developer.wordpress.org/block-editor/reference-guides/block-api/block-metadata/#icon

This is not true. I can't get `network`, `community`, or `quote` to appear, for example. No icon shows for the block when specifying some dashicons. I do not know why some are not working.

### Step-by-step reproduction instructions

1. Create a block with a block.json file
2. Provide the string "network" in the `icon` property
3. Use the block

### Screenshots, screen recording, code snippet

![Screen Shot 2022-01-06 at 2 39 20 PM](https://user-images.githubusercontent.com/938411/148441353-3c38fce8-7ad7-44e6-b202-89aba653566e.png)

### Environment info

WP 5.8.2
Gutenberg plugin 12.3.0
I cannot deactivate all other plugins because the block I'm building when I discovered this issue is in a plugin.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by csalzano** [comment]
@karmatosed how can I provide the testing needed? Would a link to a repo with a broken icon be sufficient?

**Comment by karmatosed** [comment]
@csalzano that would help but also someone needs to test this along with you.

**Comment by t-hamano** [comment]
Hi, @csalzano

Perhaps you are missing some string that you are specifying.

For example, if it is `network`, you can specify **`admin-network`** and it will be displayed correctly.

![capture](https://user-images.githubusercontent.com/54422211/153589551-c637bd69-de1d-41c0-914e-394114dc1ec4.png)
https://developer.wordpress.org/resource/dashicons/#admin-network

The point is to specify `admin-network`, not `dashicons-admin-network`, because the `dashicons-` prefix is given automatically.

Please give it a try.

**Comment by csalzano** [comment]
Yes, that's it. Thanks & sorry for the trouble.
