### ISSUE TITLE
Navigation Editor: Deleting an existing menu causes a maximum depth exceeded error

### ISSUE THREAD

**Issue by chad1008** [WordPress/gutenberg#37794]
### Description

With the beta Navigation Editor enabled, if a menu already exists when the editor is loading, attempting to delete it will crash the editor. The UI will display a generic `The navigation editor has encountered an unexpected error.` with an `Attempt Recovery` button.

In the error console, a `Maximum depth exceeded` React error is displayed (screenshot below)

### Step-by-step reproduction instructions

1. Go to Gutenberg > Experiments and ensure Beta Navigation Editor is activated
2. Open the Navigation editor and create at least one menu
3. Navigate away from the navigation editor, to any other wp-admin page
4. Return to Gutenberg > Navigation (beta)
5. When the panel opens a menu is selected by default. Click the **Delete Menu** button
6. The button will display its 'busy' animation for a moment, and then the error occurs
7. Refresh the Navigation editor. When the page loads, you'll see the menu has been deleted, despite the error that was displayed

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/13856531/148608668-6013f489-e352-42aa-b05e-8e8e61a5f325.png)

### Environment info

WP 5.8.3, GB 12.3.0, Twenty Twenty-One

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kathrynwp** [comment]
Closing this issue due to the Navigation Screen project being moved to [an inactive status on the feature projects page](https://make.wordpress.org/core/features/) in coordination with the project leads. (The developer documentation in the initial post are no longer accessible)

If this work is picked back up, issues can be revisited and reopened as needed. Thanks for pitching in on this early feature so the wider WordPress project could benefit from the lessons learned!
