### ISSUE TITLE
Site editor pattern inserter only displays two categories

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#37814]
### Description

When I open the site editor, toggle the inserter, and select the patterns tab, it only shows two categories:
buttons and query.

If I go to the block editor, including the template editor, the same tab shows: featured, buttons, columns, gallery, headers, text, query.

### Step-by-step reproduction instructions

1. Open the site editor
2. toggle the inserter
3. select the patterns tab

### Screenshots, screen recording, code snippet
Site editor:
![pattern tab in site editor with two categories](https://user-images.githubusercontent.com/7422055/148725556-5b1f1455-b61f-46f3-97ca-55bcf79c493b.png)

### Environment info

WordPress 5.9-RC1-52542
With and without Gutenberg version 12.3.0
Multiple themes (emptytheme)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kafleg** [comment]
![image](https://user-images.githubusercontent.com/13062231/148730912-88f8d0b1-2512-4f23-ad4d-a9e5c08b71dc.png)

RC1 without Gutenberg

**Comment by carolinan** [comment]
Which of these categories are registered by the theme?
Did you try with a theme that does not register patterns/pattern categories?
And are the same categories displaying in all 3 editors?

**Comment by kafleg** [comment]
Categories registered by Twenty Twenty-Two theme. 

1. Featured
2. Footers
3. Headers
4. Query
5. Pages

Categories showing when the theme activated without the registered block categories:
1. Buttons
2. Query 

Missing categories(The below categories should be shown when the theme without patterns categories)
1. Text
2. Gallery 
3. Columns

Issues created by @carolinan is valid. Need to check properly.

Thank you

**Comment by kafleg** [comment]
When checking from the posts > add new > patterns < there are categories displayed with the theme without patterns categories registered.

![image](https://user-images.githubusercontent.com/13062231/148732183-294bf025-118b-4e7c-87e3-d69b6975f545.png)

**Comment by noisysocks** [comment]
I can repro this using `emptytheme` **without** the Gutenberg plugin activated but cannot reproduce this **with** the Gutenberg plugin activated. Perhaps there's a missing backport.

**Comment by noisysocks** [comment]
The problem is that remote patterns are loaded when the `current_screen` hook is called.

https://github.com/WordPress/wordpress-develop/blob/7f2ddd0ae6f128d4292d7cbd20d9e359bb176609/src/wp-includes/default-filters.php#L335

Before proceeding, this hook checks that `$current_screen→is_block_editor` is true.

https://github.com/WordPress/wordpress-develop/blob/7f2ddd0ae6f128d4292d7cbd20d9e359bb176609/src/wp-includes/block-patterns.php#L55-L57

But `is_block_editor` is not set to true until **after** the `current_screen` hook is called.

https://github.com/WordPress/wordpress-develop/blob/7f2ddd0ae6f128d4292d7cbd20d9e359bb176609/src/wp-admin/admin.php#L212

https://github.com/WordPress/wordpress-develop/blob/7f2ddd0ae6f128d4292d7cbd20d9e359bb176609/src/wp-admin/site-editor.php#L32

The inserter hides the categories as they are empty.

Unfortunately there is no suitable hook that fires in between the call to `$current_screen→is_block_editor( true )` and the call to `WP_Block_Patterns_Registry::get_instance()->get_all_registered()`.

Perhaps we should call `_load_remote_block_patterns` and `_load_remote_featured_patterns` directly instead of using a hook? What do you think @hellofromtonya?

At any rate, I'll turn this into a Trac ticket since that is where the fix needs to happen.

**Comment by noisysocks** [comment]
Moved to https://core.trac.wordpress.org/ticket/54806.

**Comment by carolinan** [comment]
This issue has resurfaced for me but only when Gutenberg 12.4.1 or Gutenberg [current trunk](https://github.com/WordPress/gutenberg/commit/8df93444e581111882c18c7ae343997579b71a66) is active.
With WordPress 5.9 alone, the remaining categories and patterns are loading.

**Comment by carolinan** [comment]
Retested with Gutenberg 12.9, I believe this has been solved.
