### ISSUE TITLE
Up-arrow in Component Toolbar Navigation takes you to top of page.

### ISSUE THREAD

**Issue by jdelia** [WordPress/gutenberg#3783]
## Issue Overview
Up-arrow in Component Toolbar Navigation takes you to top of page unexpectedly.

## Steps to Reproduce (for bugs)

1. Using the component toolbar navigation left and right arrow keys 
2. Pressing the up-arrow key takes you to the top of the page unexpectedly. 
3. User will loose their place.

Chrome 62.0

## Expected Behavior
Not sure what the expected behavior should be - but I did not expect to be taken to the top of the page. 

## Screenshots / Video
https://cl.ly/431N362x1E3F

**Comment by ephox-mogran** [comment]
I can replicate this. It is due to the arrow keys not being handled. The NavigableMenu needs to return 0 for the offset. However, looking into this, I've found a few other issues with the link dialog. I'm going to see if I can get some cypress tests up and running so that we don't keep hitting these regressions.

This particular bug can be caught by a unit test, though. We'll just need to make sure that the up event isn't propagating past the NavigableMenu when orientation is set to horizontal.
