### ISSUE TITLE
Load `theme.json` CSS before `add_editor_style()` CSS

### ISSUE THREAD

**Issue by andrewstaffell** [WordPress/gutenberg#37839]
### Description

In the editor the rules from `theme.json` are being inlined after those from `add_editor_style()`. This makes it difficult for a block style to override a default at the same level of specificity. As far as I can see you have to artificially increase the specificity, which makes it less flexible. 

### Step-by-step reproduction instructions

Here's a simple example. 

I have a "No gap under" block style for groups so that several colour-background groups can be placed flush against each other, ie. overriding the default bottom margin. 

### theme.json
```
{
	"$schema": "https://schemas.wp.org/trunk/theme.json",
	"version": 2,
	"settings": {
	"styles": {
		"blocks": {
			"core/group": {
				"spacing": {
					"margin": {
						"bottom": "2rem"
					}
				}
			}
		}
	}
}
```

### Block style definition
```
registerBlockStyle('core/group', {
	name: 'no-gap-under',
	label: 'No gap under',
});
```

### add_editor_style() definition
```
.is-style-no-gap-under {
	margin-bottom: 0;
}
```

### Result
The block style is ineffectual in the editor: because the `theme.json` rules are inlined after the editor styles, the block style (which should function as an override) doesn't work, and is overridden by the default instead. (It works fine in the front-end because the block styles are easily loaded after the inlined `theme.json` styles.)

<img width="507" alt="Screenshot 2022-01-10 at 14 28 08" src="https://user-images.githubusercontent.com/696154/148834724-6cce4d29-f605-4be0-b3fb-c001912ebfc9.png">

The element being inspected here is:
```
<div class="block-editor-block-list__block wp-container-0 is-selected wp-block-group is-style-no-gap-under block-editor-block-list__layout">
```

The first and last rules would ideally be in the opposite order, allowing easy overriding without having to add extra class or tag names to the rule to force it. I've tested just inverting the two corresponding `<style>` declarations by dragging them into the opposite order in Chrome Dev Tools, and putting the `add_editor_style()` rules below the `theme.json` rules instantly fixes the problem.

### Environment info

WP 5.8.3
Gutenberg 12.3.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by oandregal** [comment]
Hey Andrew, thanks for bringing this up.

We could fix this in the plugin and I've prepared a PR to do so at https://github.com/WordPress/gutenberg/pull/37885

However, this needs to be fixed in WordPress core directly as well. I've also prepared a PR for WordPress core at https://github.com/WordPress/wordpress-develop/pull/2139 I'd think this is not a good time to land that PR in WordPress, as it can have unexpected side-effects. I'd think it's best to land it after the WordPress 5.9 cycle is closed so we have time to test.

While looking into this I've noticed a couple of things that would prevent this from working, but are separate endeavors:

- We sometimes load the global stylesheet in the footer while the theme styles stay in the header, see https://github.com/WordPress/gutenberg/issues/37589#issuecomment-1009858402 for details. That means in theme styles won't override global ones if they have the same specificity.
- Registering the block style using the `inline_style` property  (`register_block_style( 'block', array( ..., 'inline_style' => 'STYLES GO HERE' } ) )` is problemating on its own:
  - does not wrap the inline styles with the `editor-styles-wrapper` class in the editor
  - loads the styles in the front before the global stylesheet

**Comment by andrewstaffell** [comment]
Thanks for swift response and PRs @oandregal. 

In case it's relevant to know, I do have `add_filter('should_load_separate_core_block_assets', '__return_true');` in this theme. I'm not sure if it would behave differently without that, but I guess the change still makes sense either way. 

And yes to waiting for 6.0 to test fully!
