### ISSUE TITLE
Quick Inserter not visible at bottom of Site Editor

### ISSUE THREAD

**Issue by audrasjb** [WordPress/gutenberg#37891]
### Description

**Note: this is a copy paste from a Trac ticket.**

> While clicking in the new Theme Editor to add a new block at the bottom of the Editor, the Editor cannot be scroll further to see the whole widget and also it isn't appearing in the way to see it whole as well.

See the original Trac ticket for further details and screenshots: https://core.trac.wordpress.org/ticket/54750

### Step-by-step reproduction instructions

See the original Trac ticket for further details and screenshots: https://core.trac.wordpress.org/ticket/54750

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
I can't replicate with 5.9 
<img width="1364" alt="Screen Shot 2022-01-11 at 3 37 33 PM" src="https://user-images.githubusercontent.com/26996883/149038208-8b7a5325-f6ce-426d-bfe3-731d7a521b8c.png">
RC2:

<img width="1377" alt="Screen Shot 2022-01-11 at 3 37 08 PM" src="https://user-images.githubusercontent.com/26996883/149038205-3005633f-ffae-4df1-9c5d-4945eff1f8e5.png">

Going to try flagging for folks in core-test to see if others can.

**Comment by carolinan** [comment]
I was not able to reproduce this.
Custom theme, Windows 10, Chrome, Firefox, Edge, Opera.

**Comment by JustinyAhin** [comment]
I was able to reproduce the issue, but it looks like it happens in very specific conditions.

## Environment
- OS: macOS BigSur 12.0
- Browser: Firefox Developer Edition 96.0b10 
- WordPress 5.9-RC2
- Plugins: WordPress Beta Tester
- Theme: TT2


## Steps to reproduce
This is still not very clear. Here is what I did though:
- In the theme editor, create a blank page template
- Create empty paragraph blocks until reaching the bottom of the viewport
- Add a Row block at the bottom of the page and add a button inside the block
- Now try to click on the + icon to add another block (see recording https://cln.sh/EmcIuW )


I haven't been able to reproduce it with another blocks' combination other than Row + Buttons. Also, it only happens when the page is fully scrolled down.

**Comment by piotrbak** [comment]
I'm able to reproduce this issue. 
### Environment
-TT2 theme, Windows 10, Chrome, 1920x1080, 5.9-RC2-52567 WP

### To reproduce, in my case:
1. Go to the Single Post editor (using TT2)
2. Scroll to the bottom
3. Add a new block, let's say Cover
4. Try to add a new block inside the group that contains comment block
5. See the error

It also happens when the page is fully scrolled down.

Screencast:
https://drive.google.com/file/d/1RvRJdJzfvEgNs9BisUTX3fRZPe3u4-k1/view?usp=sharing

**Comment by annezazu** [comment]
Thank you all for testing and following up. Huge help. Re-labeling this and adding to must-haves to be safe.

**Comment by talldan** [comment]
It's pretty hard to reproduce. I found it easiest in Firefox (couldn't reproduce at all in Brave) using the in-between blocks inserter.

**Comment by youknowriad** [comment]
I can't reproduce this in either browser. There has been iterations on the popover components, so it's probably solved.
