### ISSUE TITLE
Reusable Blocks: Add ability to delete a Reusable Block

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#3792]
The user should be able to delete a Reusable Block that they've created. 

Technically, this can be accomplished by:

- Implementing the `delete_item` and `delete_item_permissions_check` methods in `WP_REST_Reusable_Blocks_Controller`
- Adding a `DELETE_REUSABLE_BLOCK` effect, which calls `new wp.api.models.ReusableBlocks( { id } ).destroy()`
- Dispatching `DELETE_REUSABLE_BLOCK` when the user confirms their intent to delete the block

Some discussion about how the UI for this should work is required. Some ideas:

1. Add an `X` icon to each Reusable Block in the Inserter. Clicking it would show an alert which confirms whether or not the user is OK with deleting the block. On confirmation, the block is deleted and a 'Reusable block deleted' notice is shown.
2. Add a 'Delete Reusable Block' button to the Block Inspector. This is shown when a Reusable Block is selected. Clicking it would show an alert which confirms whether or not the user is OK with deleting the block. On confirmation, the block is deleted and a 'Reusable block deleted' notice is shown.

cc. @jasmussen @mtias

**Comment by jasmussen** [comment]
I know @karmatosed has some thoughts on this.

My instincts go along this route: have a new section dedicated to re-usable blocks that lives in the ellipsis menu. This ellipsis menu item could take you to a completely separate "screen takeover" section, that lists all your reusable blocks with options to delete either. This could also provide a more relaxed interface for renaming or even editing the blocks, as I'm sure future enhancements are likely to require some real estate.

Here are mockups for configuring "Publicize" as an extensibility pattern, something similar could be used here:

![ellipsis](https://user-images.githubusercontent.com/1204802/33540398-3042b964-d8cb-11e7-8bc0-286caaab6e49.png)

![publicize](https://user-images.githubusercontent.com/1204802/33540401-3213e420-d8cb-11e7-8791-b9e52aff8b52.png)

The chief downside with the above is that it's a lot of new work.

An alternative, for now, would be to simply add the "delete block" item to the block ellipsis menu:

![block ellipsis](https://user-images.githubusercontent.com/1204802/33540433-5de24100-d8cb-11e7-8f1e-c03a180e7dd1.png)

**Comment by mtias** [comment]
@jasmussen wouldn't it be alright to add a trash button to this mode?

![image](https://user-images.githubusercontent.com/548849/33719204-c495f94e-db3e-11e7-9f7d-d84158c8397a.png)

I agree with having a view for managing all the reusable blocks down the line. Another thinking is how to categorize them. I'd love for this to be less user involved. Say if you have 20 reusable blocks of type x, that we automatically group them under a category in the "saved" blocks panel in the inserter. If you have a mix of types and only 5 blocks, it's ok to just let them mix.

The other thing is allowing the original icon to persist instead of forcing the icon to be the same.

**Comment by jasmussen** [comment]
All of those ideas sound good to me, provided we can

- prompt on delete to make sure the just knows the action not only deletes the saved block source, but (presumably?) detaches all used instances from the block
- the separate page for all the blocks been be revisited some time in the future

Given how important this feature feels, I suspect it'll be important to have a nice big screen section to manage these from a central location.

**Comment by westonruter** [comment]
> Given how important this feature feels, I suspect it'll be important to have a nice big screen section to manage these from a central location.

Indeed. The next generation of the Widgets admin screen.

**Comment by Lewiscowles1986** [comment]
Just an idea, could the front-end remove the block if it's been removed, not render if the block doesn't exist, and then just add an admin ui to wherever you're storing blocks?

I have a plugin that delivers the same concept as re-usable blocks. I've maintained it since 2015, and it has a visual editor integration using oEmbed. It does add some non-visual content in the case a block is not present (for debugging). But as it's implemented via CPT you get the benefit of powerful content and a deleted folder (users have to be really determined to ensure it's really deleted).

**Comment by afercia** [comment]
To my understanding, it is also possible that some reusable blocks will be "orphaned", meaning saved in the database but not currently used anywhere. That's when they're "detached" but the `wp_block` post still exists in the database, right?

If so, a dedicated UI to manage reusable blocks separately does make even more sense, as it would be the only place in the UI where they can be managed.

**Comment by amandablum** [comment]
I am also experiencing this issue, but want to give some more context to the issue. As an admin/user, not a developer, I expect reusable blocks to be one of the primary ways we give clients templates in a usable way (I know we can create blocks but the average admin isn't going to do that,.) 
We want to consider the admin vs user usability of these blocks. Putting the delete button on an ACTUAL block in a post signals to me that I am merely deleting THAT block, not the reusable block, and I expect clients to misunderstand the use of the delete button and delete a reusable block they need, just not on that page. The only place I expect I would understand the totality of the block deletion is either in the menu from which we select blocks, or in the Gutenberg admin menu (I don't know if that's expected to live on). 
Second, to delete a reusable block via the above methods means I first have to insert the block into a post/page, unless I misunderstand the flow above. As an admin, I'm noticing the blocks that need deletion (mostly because they were accidentally created) in the "add a block" menu.Its counter-intuitive to insert that bad block, and then delete it and expect it to disappear from the add a block menu.

**Comment by ryancwalsh** [comment]
I'm confused. This issue is marked as "closed", but I can't find (by poking around in WordPress or by searching the internet for docs) any way to edit or delete a reusable block. 

Can someone tell me where/how to do that, even if it means logging into the server via SSH and editing files? I don't know where to look. Thanks.

**Comment by ryancwalsh** [comment]
Well, I just found "Remove from Reusable Blocks", which I swear wasn't there yesterday. Maybe when I updated Gutenberg today that feature became available, or maybe I'd just never seen it. So that answers the question about deletion. And the editing seems to work but with a delay (e.g. if you have 2 custom blocks in the same post and go to edit one). Okay. **Sorry for the distraction. No real problem here.**
