### ISSUE TITLE
Doesn't work without wp-components dependency

### ISSUE THREAD

**Issue by MehbubRashid** [WordPress/gutenberg#38000]
### Description

I am testing it outside of gutenberg (in site frontend). Nothing works if I don't add wp-components as dependency while enqueueing the bundled script.

If I add wp-components as dependency, everything works fine even if I don't have @wordpress/components package installed in my node_modules folder. 

So, why it is written to `npm install @wordpress/components --save` [here](https://github.com/WordPress/gutenberg/tree/trunk/packages/components) ? It is not needed! even if we do it, we still have to add wp-components as dependency. 

### Step-by-step reproduction instructions

1. Use a hook (wp_head) to print something on the site "<div id='react-app'></div>"
2. in that react-app id, load react
3. Enqueue the bundled javascript file
4. npm install @wordpress/components --save
5. Try to use the button component, It won't work.
6. Add wp-components as the dependency, it will work
7. Uninstall the @wordpress/components package
8. It still works.

### Environment info

- WordPress Version: 5.8
- Gutenberg: Not installed. (Testing in site frontend)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by swissspidy** [comment]
Can you show the code you are using? I suppose you are directly accessing stuff from the window.wp.components global.

The idea behind installing the WP packages is that you get all the type information and IDE autocompletion during locally when importing the components from the package.
Then, wp-scripts will automatically turn these imports into usage of the window.wp.components global and exclude the package from your bundle and add the wp-components script as a dependency, because WP loads the script separately for you.
If you don‘t need these benefits and want to access thise globals directly, that‘s fine too. You don‘t have to use it.

Also keep in mind that the readme mentions installing also for those using the packages outside a WP context.

I recommend checking the Gutenberg handbook for more information about wp-scripts and the like.
