### ISSUE TITLE
Duplicated settings in inspector controls on Comments Query Loop block

### ISSUE THREAD

**Issue by cbravobernal** [WordPress/gutenberg#38080]
### Description

When I add a Comments Query Loop, if we set more than 2 items per page. Most of the sidebars options of all inner elements appear `n` times, being `n` equal to `items per page -1`.

### Step-by-step reproduction instructions

1. Go to a page or a post with comments, you need to have at least 3 comments.
2. Use the toolbar option to change the comments per page.
3. Click on any inner block of the Comment Template and check sidebar for duplicated settings.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/37012961/150172814-a2c82ca9-8792-4b8d-ac2f-1671ba7a2272.mov

### Environment info

- WordPress version 5.9-beta3-52380
- Gutenberg version "trunk"

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by gziolo** [comment]
I reported it also in a comment here: https://github.com/WordPress/gutenberg/issues/37154#issuecomment-998728016. I think it's related to the issue with rendering either a loop of the same blocks, or it's coming from the nested blocks. Anyway, we need to improve how we render the Comment Template block and its inner blocks. I think @michalczaplinski is looking into it already. We should find out whether #37154 and this one are separate issues.

**Comment by michalczaplinski** [comment]
Strangely enough the same issue was mentioned by @andrewserong in https://github.com/WordPress/gutenberg/pull/38263#pullrequestreview-868581596 

Seems like the problem of having duplicate sidebar controls also came up before in Post Template block https://github.com/WordPress/gutenberg/pull/37519#issuecomment-1000013791

**Comment by SantosGuillamot** [comment]
@michalczaplinski I've realised that, in the editor, if you click in any of the inner blocks of the Comment Template, it jumps to the latest comment. I made a quick video to show it:

https://www.loom.com/share/ac22dbcb0d25492888df959a3445dc86

Not sure if it is related to this issue, but as both happen only in the editor I thought they could be triaged at the same time. Please let me know if you think it makes sense to open a new one.

**Comment by gziolo** [comment]
@michalczaplinski and @c4rl0sbr4v0, if you need some help we can pair to work on this one next week. It's a very tricky one and there are several issues with how it works today. We tested a few different scenarios yesterday with @SantosGuillamot and it was very difficult to achieve simple goals like wrapping inner blocks with a Group block or use multiselection, etc.

**Comment by michalczaplinski** [comment]
> @michalczaplinski I've realised that, in the editor, if you click in any of the inner blocks of the Comment Template, it jumps to the latest comment. I made a quick video to show it:

Yup, this is a [known issue](https://github.com/WordPress/gutenberg/pull/38263#issuecomment-1033184348) 🙂 These are the 3 the bugs that I'm quite sure are related to the problem of "duplicate settings" that is described in the current issue:

- If a top-level comment has replies and is clicked on, its innermost reply is being selected instead.
- If a comment has multiple replies and a user selects one of the inner blocks of that comment (e.g. the Comment Date) then this same Comment Date block flickers across all the comments.
- In order to select one of the inner blocks of the Comment Template, it is necessary to click twice. That is, clicking on a block within another instance selects the parent template block instead. This issue is mentioned here (I’d say it’s not essential, but it is a quite annoying) _This one is probably related but I'm not 100% sure_

--- 

@gziolo That would be great! I have in fact spent a couple of hours trying to come up with a solution yesterday and I haven't made great progress so far :/ It seems to be tricker than I thought. I **think** it's somehow related to the fact that we are are nesting inner blocks several times (because replies can have replies that can have replies, etc.)

**Comment by michalczaplinski** [comment]
Status update:

This issue has been blocked by two additional issues:
- https://github.com/WordPress/gutenberg/pull/39415
  - Comments Query Loop was not showing up in the inserter because of a bug introduced in #39180
  - It's already fixed.
- https://github.com/WordPress/gutenberg/issues/39443
  - The inner blocks of the Comment Template cannot be selected which makes it impossible to test the current issue of duplicate settings is Inspector Controls.
  - This issue was introduced in #38187
