### ISSUE TITLE
Multiple navigation menus are being created

### ISSUE THREAD

**Issue by lumpysimon** [WordPress/gutenberg#38157]
### Description

I'm running 5.9-RC3 with Twenty Twenty Two theme. Gutenberg plugin is *not* installed.

Multiple navigation menus are being created even though I have not added any, when I go between the new site editor and the manage menus screen.

### Step-by-step reproduction instructions

* Click 'Edit site' in the admin toolbar.
* Click on the header navigation menu block.
* Click 'Select menu'.
* Click 'Manage menus'.
* There is one menu listed, called 'Header navigation'.
* Do nothing on this screen, then navigate to 'Appearance' > 'Editor'.
* Click on the header navigation menu block.
* Click 'Select menu'.
* There are now two navigation menus showing ('Header navigation' and 'Header navigation 2').
* Repeat the above steps, each time a new navigation menu is created.

At no point during this process have I clicked 'Add new' on the menus page, clicked any 'Publish' buttons, etc.

### Screenshots, screen recording, code snippet

<img width="1330" alt="Screenshot 2022-01-22 at 13 15 37" src="https://user-images.githubusercontent.com/625372/150639956-d4f818de-a67f-42c1-861a-8385a4f1332a.png">

### Environment info

WordPress 5.9-RC3
Twenty Twenty Two theme
Gutenberg *not* installed
MacOS 12.1
PHP 7.4 (site is running locally using Valet)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Thanks for reporting this. To explain what's happening:
1. The theme provides some initial menu content
2. When selecting the navigation block with this content, a Navigation Menu is created
3. At the point, the changes to the template and the new menu need to be saved to avoid duplicates

The duplicates should only happen if when exiting the site editor the warning about unsaved changes is ignored.

I agree it is confusing, and something that should be improved.

I did mention the problem with duplicate menus in my feedback on the PR - https://github.com/WordPress/gutenberg/pull/36024#issuecomment-953531985 - but this is the direction others wanted to take.

Perhaps the best option is if the block could check whether another menu with the same content already exists before creating a new one. Maybe menus created this way could have some kind of flag (e.g. `wasInitialThemeContent: true`), and then before creating a new menu, the block can check any menus with this type to see if they have the same original content.

**Comment by getdave** [comment]
> When selecting the navigation block with this content, a Navigation Menu is created

Why do we have to save _immediately_ if there have been no changes? Why is there even a "dirty" state? 

Is there a way we can adjust the flow so that we only save a new menu if there have been changes?

**Comment by talldan** [comment]
> Is there a way we can adjust the flow so that we only save a new menu if there have been changes?

It would be good to try. Saving is asynchronous, so it would have to be pretty seamless and not interupt the user's editing. 

It still only mitigates the issue though, the user can choose not to save changes in the site editor (which avoids assigning the `ref` in the nav block), and they would still get another menu when they next go to edit (because there's no `ref` assigned). Granted it does reduce the problem as users are less likely to edit compared to selecting the block.

**Comment by talldan** [comment]
I've outlined a couple of options for solving or improving this in https://github.com/WordPress/gutenberg/issues/39489.

**Comment by getdave** [comment]
IN https://github.com/WordPress/gutenberg/pull/39883 weve now updated things so that Nav blocks that:

- are provided by a Theme template
- are inserted via a Pattern
- are created manually via Code View

...will only be converted to a Navigation Menu entity _if_ the user modifies the original blocks.

So if your Theme includes a Nav block it won't get saved as a Navigation Menu until you click on it _and_ make some changes to the menu items. At that point it saves.

This should avoid so many menus being created because no longer does focusing the Nav block cause a Nav Menu to be created.

**Comment by jordesign** [comment]
With https://github.com/WordPress/gutenberg/pull/39883 closed - and no further reports of this kind - I'm going to close this issue as well.
