### ISSUE TITLE
forced paragraph tags when the HTML block is used as a widget.

### ISSUE THREAD

**Issue by arinoch** [WordPress/gutenberg#38229]
### Description

Tags are added at the beginning and end of HTML code when those tags are not required. I expect instead that the custom HTML I entered will remain unaltered.

### Step-by-step reproduction instructions

1. Enter the widget area, either through Appearance > widgets or through the customizer.

2. Add a custom HTML block with any HTML code, preferably code that doesn't require \<p> and \</p> tags (the code I was testing was surrounded by \<center> and \</center> tags).

3. Save your changes, and back out of that screen--return, for example, to the dashboard.

4. Revisit that screen, either in the customizer or in Appearance > Widgets, the editor will add \<p> and \</p> tags.

### Environment info

Has been tested on WordPress 5.8.3, with and without the gutenberg plugin and with several default themes (Twenty Twenty-One, Twenty Twenty), as well as the Hever theme available for download from Automattic.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/33832. Feel free to [add your reaction](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments) and follow its progress in the issue.

Please reopen and comment with additional details if your issue is not the same as the one specified above.
