### ISSUE TITLE
Enhanced functionality for table block

### ISSUE THREAD

**Issue by ghost** [WordPress/gutenberg#38248]
## What problem does this address?
Limitations in using table block in the post. We updated our WordPress site to 5.9. However, we observed that there are no changes or enhancements in the table block added to the Post/custom post. The table block provided in WordPress is very very basic. 

## What is your proposed solution?

We need the following features specifically for the table block:

* Custom / draggable column width, independent for each column
* Merging and splitting of rows and columns 
* Enabling Tab key for moving from one cell to another
* Bulleted / ordered list inside a table cell
* Image block inside a table cell

**Comment by jacobdubail** [comment]
I would add 

- ability to move/drag rows up/down, ability to re-order rows/column simply.

**Comment by talldan** [comment]
@quickdraft Thanks for mentioning all these improvements. Generally it's good to create individual issues for enhancements. It becomes very hard for other users to search for something like adjustable column width when things are grouped together like this. Because of this I'm going to close the issue.

There's already what we call a 'tracking issue' for all the Table Block issues, which offers an overview of other requests from users - https://github.com/WordPress/gutenberg/issues/32400.

Some of the things you mentioned are already listed there, I can see issues already for lists and merging cells.

> Image block inside a table cell

This is something that has been requested before, but there aren't plans to support other blocks within cells at the moment. You can currently use the inline image option to add images:
![Screen Shot 2022-01-27 at 12 12 05 pm](https://user-images.githubusercontent.com/677833/151290606-b50aaa8c-16f1-4117-acc8-a60e394a1528.png)

> Enabling Tab key for moving from one cell to another

The tab key is currently reserved for moving from a block to the sidebar. Arrow keys are the easiest way to navigate around a table at the moment.

> Custom / draggable column width, independent for each column

I don't see an issue for this. It'd be good to make one, as this would be a nice feature! I've added it to the list on #32400 and also mentioned your ideas in a comment there.
