### ISSUE TITLE
Colorpicker onChange event doesn't fire

### ISSUE THREAD

**Issue by MehbubRashid** [WordPress/gutenberg#38290]
### Description

If we bind any event in the onChange property of colorpicker component, the function doesn't fire.

### Step-by-step reproduction instructions

1.) Use the color picker component
2) Bind a function in onChange property
2) The function doesn't fire

### Environment info

- WordPress Version: 5.8
- Not using gutenberg (testing in site frontend)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
@MehbubRashid what happens if you use 5.9? I'm curious to know your current experience with the latest release :)

**Comment by MehbubRashid** [comment]
Hi @annezazu , It's working in 5.9

**Comment by t-hamano** [comment]
@MehbubRashid 

`onChangeComplete` has been deprecated, and `onChange` is now recommended instead.

Therefore, WordPress 5.8 does not support `onChange` and will not fire because the old `onChangeComplete` is still in effect.

Please see: https://make.wordpress.org/core/2022/01/04/miscellaneous-block-editor-changes-in-wordpress-5-9/#colorpicker.

**Comment by annezazu** [comment]
Thanks for connecting the dots @t-hamano :) Closing this out.
