### ISSUE TITLE
Author select section on the post edit pages is gone.

### ISSUE THREAD

**Issue by ghost** [WordPress/gutenberg#38298]
### Description

After the last update, the "author select" area that exists on the post editing page and that allows us to select other authors as the author of the post to be published, disappeared. It just doesn't show up anymore.

### Step-by-step reproduction instructions

1. Go to post edit page
2. Try to select other author for the specific post

### Screenshots, screen recording, code snippet

Before last update:

![present](https://user-images.githubusercontent.com/18150957/151425621-242802fa-583c-4d0c-bfc4-9e4d29841aa1.jpg)

After last update:

![not present](https://user-images.githubusercontent.com/18150957/151425577-bedb66f8-8acf-422e-bf34-ae171fd9234c.jpg)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
Hi @TgDsGooD, thanks for reporting. The Author selection field was not removed in 5.9, but it does take a sec to fetch the current users. So when you first load the page, the field is not be visible. Once the authors have been fetched, it will appear. This is the same functionality as in previous versions as far as I am aware.

Can you check to see if there are any console errors? If so, would you be able to share them here?

**Comment by ghost** [comment]
I waited more than 5 minutes and the field does not appear. Here's a print for you to see!

My domain I painted black so it doesn't show up.

![console-error](https://user-images.githubusercontent.com/18150957/151432243-4c047336-b059-4866-ad6a-ec426edf73cf.jpg)

![console2](https://user-images.githubusercontent.com/18150957/151432291-3e7d40df-850d-4785-9ad5-710c99fc658b.jpg)

**Comment by ndiego** [comment]
Thanks for the followup. Yeah, the multiple server 404 errors point to a larger issue here. My guess is these issues are preventing WordPress from being able to successfully fetch the authors. It looks like the errors might be related to a plugin or your specific theme? Very hard to tell, but perhaps whatever is loading `betube-admin.css`?  

While not a solution, I hope the above was a bit helpful. I am going to close out this issue since the Author selection field was not removed in WordPress 5.9 and this issue seems related to other external factors. If you need additional help resolving this further, please check out the [support forum here](https://wordpress.org/support/forum/how-to-and-troubleshooting/).
