### ISSUE TITLE
Problem with widgets in WordPress 5.9

### ISSUE THREAD

**Issue by mateo3235** [WordPress/gutenberg#38443]
### Description

Hello. After updating wordpress to version 5.9, the widgets that I had on the website declared with the class Timetable extends WP_Widget stopped showing. Has anyone had a similar problem? I have the widget block editor turned off.

### Step-by-step reproduction instructions

1. Install Wordpress 5.9

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Hey there! This repo is generally for issues impacting the main block editor and now site editor. As a result, I recommend opening an issue in Trac since that covers the other interfaces within WordPress, including widgets:. Here's where you can search for issues: https://core.trac.wordpress.org/ Here's where you can open one: https://core.trac.wordpress.org/newticket
