### ISSUE TITLE
we need opposite of allowed_block_types_all filter

### ISSUE THREAD

**Issue by kubiqsk** [WordPress/gutenberg#38472]
it will be very helpful if we would have `disallowed_block_types_all` or `disabled_block_types_all` filter similar (opposite) to `allowed_block_types_all`

currently when you use `allowed_block_types_all` you will receive first argument `$allowed_block_types` as `TRUE` boolean value, so there is nothing to filter… but the real problem is that when you use this filter, then you will automatically **disable all potential future blocks** that can appear after updates.

`disallowed_block_types_all` would allow you to just disable some specific blocks without having this (negative) impact on other blocks

**Comment by aristath** [comment]
Hey there @kubiqsk!

You don't need an "opposite" filter, the existing filter can be used. The value can either be a `boolean`, or an array as documented on https://github.com/WordPress/gutenberg/blob/b72113b2b047ad1dd7c950f7cd9893db9e6518a6/docs/reference-guides/filters/block-filters.md#allowed_block_types_all
You can also see this in the filter's inline comments: https://github.com/WordPress/wordpress-develop/blob/42b4e39c6d16e9969c790b16ece04fe533d0d597/src/wp-includes/block-editor.php#L122-L123

I hope that helps!

I'll go ahead and close this issue since it's possible to use the existing filter to enable/disable blocks 👍

**Comment by kubiqsk** [comment]
@aristath yes, i know about this, but as I wrote - once you will specify some allowed blocks array, then all future, potential blocks that can appear with update or installing new plugin will be automatically disabled and THAT'S the problem I'm talking about

**Comment by aristath** [comment]
Hmmm I see what you mean.
Would something like this work?
```php
add_filter( 'allowed_block_types_all', function( $allowed_block_types, $block_editor_context ) {
	$blocks = WP_Block_Type_Registry::get_instance()->get_all_registered();
	// Blocks to remove.
	$disallowed_blocks = [
		'core/group',
		'core/columns',
	];
	foreach ( $disallowed_blocks as $block ) {
		unset( $blocks[ $block ] );
	}
	return array_keys( $blocks );
}, 10, 2 );
```

**Comment by kubiqsk** [comment]
Hm, interesting, I'm using `get_all_registered()` in my plugin but few weeks ago I wasn't able to get blocks created with ACF here.
I had to use `acf_get_block_types()` and merge arrays or process them separately, but now I can see it actually returns everything including ACF blocks.
So can I rely on this PHP function `get_all_registered()` that it will return really all registered blocks?
There are many different block creators plugins or additional Gutenberg blocks in many plugins...
But yes, thank you, if this will really work with all the blocks, then it's really not needed

**Comment by kubiqsk** [comment]
Oh no, sorry, it was actually JS `wp.blocks.getBlockTypes()` where the ACF blocks are missing... 
Then you're right! It can be definitely used that way
Thank you very much for your time
