### ISSUE TITLE
Latest posts block's read more link gets rendered as plain text in frontend 

### ISSUE THREAD

**Issue by Azragh** [WordPress/gutenberg#38515]
### Description

Just noticed that with the newest version of the plugin the read more link isn't a link anymore.

### Step-by-step reproduction instructions

Add a latest posts block, set content to excerpt and grid view.

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/15014142/152506835-71e22f06-c900-4228-9263-f572b442cfe6.png)

![image](https://user-images.githubusercontent.com/15014142/152506772-245c8090-6f73-4080-9465-3d7467f9cabe.png)

### Environment info

Newest WP and Gutenberg Plugin, theme twentytwentyone, no other stuff active.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by getdave** [comment]
I have a fix incoming...

**Comment by Andrew-Starr** [comment]
@getdave will the fix also fix https://github.com/WordPress/gutenberg/issues/38489 as I think they are both post content being wrongly escaped?

**Comment by andrewstaffell** [comment]
@getdave I have an analogous problem with the Post Title block since the late escaping changes in 12.5. We were using the standard `the_title` filter to add some custom formatting to post titles on the front end, and it broke in 12.5:

<img width="379" alt="Screenshot 2022-02-02 at 17 51 08" src="https://user-images.githubusercontent.com/696154/152652185-01e30a0f-ba67-4065-9d95-104f89872880.png">

Without necessarily reverting the escaping, is there any way the title could still be filtered later than the escaping? (Might be useful in other contexts too?)

**Comment by getdave** [comment]
Ok let me fix this. I'll do a full audit of all those escaping PRs now as well.
