### ISSUE TITLE
Heading: Uncaught TypeError when pressing Enter

### ISSUE THREAD

**Issue by mcsf** [WordPress/gutenberg#3867]
## Issue Overview
When pressing Enter in a Heading block, either at the end of the editable field or anywhere before that, an uncaught TypeError is thrown, though seemingly no user-facing breakage occurs.

## Steps to Reproduce (for bugs)
0. Open the browser console.
1. Start a post.
2. Type `## This is a heading`, which should convert to a H2-level Heading.
3. Press Enter to start a Paragraph below.

## Expected Behavior
Nothing should happen aside from a new Paragraph appearing and the cursor (and focus) moving to it.

## Current Behavior
On the top of the expected behavior, a logged TypeError appears in the console.

## Possible Solution
A quick glance at the stack trace and some reading of `blocks/editable/index.js` make me wonder if this is caused by an interaction in/with TinyMCE. Perhaps @ephox-mogran knows.

## Screenshots / Video
<img width="367" alt="screen shot 2017-12-08 at 11 33 00" src="https://user-images.githubusercontent.com/150562/33764275-ab48ab9e-dc0b-11e7-92bf-a19fd3d73efe.png">

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by ephox-mogran** [comment]
The problem is that the enter key handling is firing on an editor that has just been removed from the dom. If you include a `stopImmediatePropagation` in the `onKeyDown` code in `editable/index.js`, it doesn't happen.

```
} else {
				event.preventDefault();
                                // This line is added.
				event.stopImmediatePropagation();

				if ( event.shiftKey || ! this.props.onSplit ) {
					this.editor.execCommand( 'InsertLineBreak', false, event );
				} else {
					this.splitContent();
				}
			}
```

Note, you may only want to add it if you aren't pressing Shift because you really only want to add it when you are recreating the editors. E.g.

```
} else {
				event.preventDefault();
				if ( event.shiftKey || ! this.props.onSplit ) {
					this.editor.execCommand( 'InsertLineBreak', false, event );
				} else {
                                       // This line is added.
	           		       event.stopImmediatePropagation();

					this.splitContent();
				}
			}
```

This should stop the caret handling that happens `onKeyDown` which is causing this problem. It is trying to read the range of an editor no longer in the DOM.

**Comment by mcsf** [comment]
Thanks for the comment, @ephox-mogran. I've opened a fix.
