### ISSUE TITLE
Blocks: Floated button block takes more space when it gets focus

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#3869]
## Issue Overview

Floated button block takes more space when it gets focus. This causes the following block to display differently depending on the focus of the button.

## Steps to Reproduce (for bugs)
1. Add a new button.
2. Make it floated to left.
3. Add another block.
4. Click on the button block and observe how 2nd block changes.

Browser: Chrome
System: macOS

## Expected Behavior

Floated button block has always the same width.

## Current Behavior
Issues around the floated button, because it’s born with a min-width so it looks weird.

## Screenshots / Video

![screen shot 2017-11-30 at 10 11 37](https://user-images.githubusercontent.com/699132/33769267-caa5ad0c-dc29-11e7-83dd-c26f49714292.png)
![screen shot 2017-11-30 at 10 12 51](https://user-images.githubusercontent.com/699132/33769268-cabf69cc-dc29-11e7-88f9-af568db54642.png)

/cc @jasmussen

**Comment by jasmussen** [comment]
After thinking about this, I think _maybe this is okay_. 

For the time being it is intentional that an unselected block is a preview, and a selected block can show extended configuration controls, in this case an input field for the URL. Many other blocks are likely to do similar things, and so long as the preview looks accurate when the block is unselected perhaps that's okay.

However I also can't quite perceive all the ways this can go wrong. We might indeed need some tweaks to how floats are handled, in case they break more deeply than the above. 

As such, I would suggest we keep this issue open, but on the backburner.

**Comment by jasmussen** [comment]
While the recent improvement to floats hasn't _fixed_ this issue, it has nonetheless made the experience much less jarring and more predictable:

![float-block-preview-changes](https://user-images.githubusercontent.com/1204802/36589321-33066c18-188b-11e8-9d6b-0fd1317e751a.gif)

Clicks on buttons do what you expect them to, and although it's perhaps not ideal that things shift around a lot when you select them, it is a design principle that a _selected block_ can show additional controls, in this case a URL bar.

As such, I'm going to close this for now, we can then revisit if need be. One solution would be to redesign the URL bar of the button.

**Comment by gziolo** [comment]
Much better, thanks 👍
