### ISSUE TITLE
Blocks: Broken layout when multiple floated blocks in succession

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#3870]
## Steps to Reproduce (for bugs)
1. Add an image block.
2. Make it aligned to left.
3. Add a button block.
4. Make it aligned to left.
5. Add another block.

Browser: Chrome
System: macOS

## Expected Behavior

Blocks are properly aligned.

## Current Behavior

Broken layout when multiple floated blocks in succession.

## Screenshots / Video
![screen shot 2017-11-30 at 10 09 05](https://user-images.githubusercontent.com/699132/33769462-9a403ae6-dc2a-11e7-8b18-0e2e7efdc190.png)

![screen shot 2017-12-08 at 15 18 24](https://user-images.githubusercontent.com/699132/33769605-15d2d858-dc2b-11e7-8da1-3a3a02e12bfa.png)

/cc @jasmussen

**Comment by jasmussen** [comment]
Great ticket.

Yes, this seems to have happened because we have no max-width on the main container, and so we have emulated the floats using left margins instead.

We can "hack our way through this" by using `.alignleft + .alignleft` to remove the left margin, or we can rethink not having a max-width on the main container.

It's been suggested a number of times that iframing the editor is not feasible (#2420). But if we were able to do that, at least it would simplify the math used to calculate the widths of `wide` and `full-wide` images. Right now that math is made complex by the plethora of responsive calculations we have to make in order to accommodate multiple widths of the left and right sidebars at responsive breakpoints.

A while back Matías had a version where wide and fullwide images were sized using JavaScript. Not the most ideal thing, but perhaps it's time to revisit that? 

CC: @youknowriad @aduth @mtias

**Comment by youknowriad** [comment]
> A while back Matías had a version where wide and fullwide images were sized using JavaScript. Not the most ideal thing, but perhaps it's time to revisit that?

I also think we should revisit using a fixed width for the content container and use JavaScript to compute the wide and full-wide widths.

**Comment by jasmussen** [comment]
This issue seems to have been almost completely fixed by the recent floats refactor, yay!

![multiple floats](https://user-images.githubusercontent.com/1204802/36585580-be63ebda-187e-11e8-9df4-b07b1967dd46.gif)

As is apparent from the GIF above, the remaining issue is with the block toolbar, which there simply isn't room for in a nice way, as that toolbar also respects the floats. 

I'm going to look into that, there may be an easy fix.

**Comment by gziolo** [comment]
Awesome work, one fix to close them all 🗡
