### ISSUE TITLE
We need a Section block

### ISSUE THREAD

**Issue by field2** [WordPress/gutenberg#38710]
## What problem does this address?

A section on a page is a common pattern, but there's currently no block to address it. The cover block comes close, but it isn't semantically the same thing; a cover is typically at the top of the page and serves as an intro or banner for the rest of the content. And while blocks can be grouped, the group doesn't have the controls (width, background color/img, etc.) that the cover block has. Furthermore, a section block would be marked up properly using the section html tag.

## What is your proposed solution?

Create a new "section" block with controls for width, height, background-essentially the same as for wp-block-cover, but more targeted for inline/flexible positioning within the block order on the page.

**Comment by aurooba** [comment]
Hallo @field2, all of this is currently possible with the group block in 5.9! :)

<img width="284" alt="Screen Shot 2022-02-10 at 9 28 21 AM" src="https://user-images.githubusercontent.com/6925260/153451842-5304a7af-4b57-472d-aabb-20cfbb67dfa3.png">

It's a matter of making sure they are active and supported by your theme. For example, with the `Twenty Twenty Two` theme activated, I can see all the following options available for the Group Block, which is..everything you noted. :)

**Comment by field2** [comment]
Oh wow, I didn't think to switch themes to see that. Thanks for posting the screenshot!
I guess I'll have to enable those settings somehow in my custom theme. I'm not having much luck googling; any suggestions? 
[edit] OK, I see where I can change the html element, but not some of the others:
<img width="288" alt="image" src="https://user-images.githubusercontent.com/1656980/153473818-a76bb17a-4eeb-426e-afb7-cbe56c3e7904.png">

**Comment by aurooba** [comment]
@field2 You'll find this function helpful: https://developer.wordpress.org/reference/hooks/block_editor_settings_all/

It covers all the Block Editor settings, and you can enable the ones you'd like in general. I'm not sure if there is a way to enable them on a block-by-block basis through this function, but hopefully this will get you the features you're looking for! I should also mention this is highly theme dependent, so you should get in touch with the theme author (if you are using a theme by someone else), otherwise, I'd recommend looking into [`theme.json` support](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/) for your theme.

If this is helpful, please feel free to close this issue! :)

**Comment by paaljoachim** [comment]
I happen to come across this issue.
From quickly browsing through it seems that this issue can be closed, so I will go ahead and do so. 
It can of course be reopened if need be.
