### ISSUE TITLE
Seperater block styles option is not visible proper

### ISSUE THREAD

**Issue by NidhiDhandhukiya** [WordPress/gutenberg#38736]
### Description

when you choose separator block and use it in the inspector control options we have style option as you see in the attached screenshot that styles of it should not visible  proper.
<img width="1440" alt="Screenshot 2022-02-11 at 3 39 26 PM" src="https://user-images.githubusercontent.com/75485120/153574103-a3f080e1-6ac1-4d56-a62c-4e3de9e33862.png">

I attached the another screenshot which is from table block border styles can we use that same structure so it would be nice for anyone to apply a style and it is visible proper.

<img width="1440" alt="Screenshot 2022-02-11 at 3 42 12 PM" src="https://user-images.githubusercontent.com/75485120/153574129-78aa5d7c-69b6-4500-aff0-9baee11de509.png">

### Step-by-step reproduction instructions

1. Go to seperator block.
2. in right side inspector control styles is not loking proper.

### Environment info

-wordpress version 5.9

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by t-hamano** [comment]
I think it is because the style preview area is so small that the dots are displayed too small to be visible.
You can see that the dots are indeed there If you zoom in on the browser.

It is very difficult to see in WordPress 5.9, but the preview area is expanded and becomes slightly easier to see if you enable the gutenberg plugin.

### WordPress 5.9 ( gutenberg plugin disabled )

![off](https://user-images.githubusercontent.com/54422211/153699373-b6617df1-f2a6-495a-a292-a120a3f355ca.png)

### WordPress 5.9 ( gutenberg plugin enabled )

![on](https://user-images.githubusercontent.com/54422211/153699369-ab00c818-a683-4535-a761-896c5c1b43f3.png)

I'm sure there are other edge cases like this, so I think it's better to accept it as correct preview area behavior instead of dealing with it individually.

Does anyone have any good ideas on how to solve this problem?

**Comment by 61pixels** [comment]
This is also an issue with other blocks too, not just separator blocks. It also happens with button blocks and others. A fresh 5.9 install with Twenty Twenty Two and add a button and look at the style previews. The button is cut in half vertically. I've been trying to debug my custom previews for days since upgrading to 5.9 and am at a loss, which is why I spun up a fresh install to see if it was my theme or core, and have had others confirm it as well. Everything looked fine before updating to 5.9

**Comment by Thelmachido** [comment]
At the moment he separator block's styles are shown from what is below. The styles are clearly added to buttons i.e Default, Wideline, and Dots. Clicking on each button gives you the style you want.

https://user-images.githubusercontent.com/41231764/190100836-5560141a-a100-4099-940d-80163ac29782.mov

I think this is pretty clear, I will close this issue for now 

WordPress 6.0.2

Gutenberg 14.0.3

Theme Twenty Twenty Two

**Comment by t-hamano** [comment]
This issue targets the block style preview, not the inserted block. However, as shown below, the latest Gutenberg seems to have improved the situation.

![separator_default](https://user-images.githubusercontent.com/54422211/190116370-d06333c6-d773-43e1-9732-4a6392ea98da.png)
![separator_wide](https://user-images.githubusercontent.com/54422211/190116381-0ae11929-e021-40d3-8f07-0113cee083f4.png)
![separator_dots](https://user-images.githubusercontent.com/54422211/190116396-0fa41143-db17-42d4-9b25-6ee67d6a3b3a.png)
![button_fill](https://user-images.githubusercontent.com/54422211/190116410-905da57b-feab-406e-8d13-f09c138fc51c.png)
![button_outline](https://user-images.githubusercontent.com/54422211/190116420-0c3bd0da-ed71-4be4-960c-90669d0a8acc.png)
