### ISSUE TITLE
Improve duotone popover experience to keep popover open

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#38797]
## What problem does this address?

In the latest FSE Outreach Program's [All Things Media exploration](https://make.wordpress.org/test/2022/02/02/fse-program-exploration-all-things-media/#comment-2324) the following feedback was shared:

>When working with Duotone, applying the first filter takes back the user to the editor which makes it more troublesome to modify the style, while when applying the following filters the settings control still visible on the frontend so the user can preview the style before coming to the conclusion. It’ll be better if the settings control stays visible when applying the very first effect.

Here's a video of the current experience: 

https://user-images.githubusercontent.com/26996883/153988338-1c82c861-f606-409f-bfa5-551b0e5a21d5.mov

## What is your proposed solution?

Keep the pop over open throughout rather than having it go away after first applying a filter. 

Just in case it's related, here's a prior issue https://github.com/WordPress/gutenberg/issues/29746#issuecomment-845629902

**Comment by richtabor** [comment]
Not sure if it's related, but we do have a bit of interface jump when applying a filter. 

https://user-images.githubusercontent.com/1813435/213613177-3be6a7cf-25f4-4b5e-9a75-5edcf9611a17.mp4

**Comment by jeryj** [comment]
Unintentionally fixed by https://github.com/WordPress/gutenberg/pull/48401.

[These lines](https://github.com/WordPress/gutenberg/pull/48401/files#diff-6f22f0774376559bfc44d97f35641a183d05a599de2c6749ee26ce766b1e5657L278-L280) were causing the popover to close when there were no duotone styles. It's unclear to me why it was closing after the first selection, but I have confirmed the `return <BlockListBlock { ...props } />;` line was causing this behavior.
