### ISSUE TITLE
 Problem with Yoast panel after WP 5.9 upgrade.

### ISSUE THREAD

**Issue by darkonelson** [WordPress/gutenberg#38813]
### Description

I need you support because I have some problems with Yoast panel after WP 5.9 upgrade.

### Step-by-step reproduction instructions

The problem is not in the functionality of the program but in Yoast panel in block editor.
When I open visual block editor all is well. But when I switch on mobile or tablet preview and come back in desktop preview Yoast panel (usually on the end of the page) comes on top of the block editor and cover edited blocks. Covered blocks loose colour. Only way to prevent this is to reload the page.

I switch off all plugins and replace theme with WP default but problem persist.
I really need to solve that because I cant  use a visual block editor on this way.
regards
Nelson

### Screenshots, screen recording, code snippet

![After switch back to desktop preview -yoas panel are under the block editor and now blocks loose colours](https://user-images.githubusercontent.com/87546406/154033025-678e119d-7744-4bf6-b3ab-0b99db05657f.jpg)

### Environment info

WP5.9,
Astra Pro theme
 UAG blocks
 Yoast Pro 
 Sucury security
Windows10 with Chrome browser

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by fwazeter** [comment]
It's never fun when a plugin does odd behavior after a core update.

Likely whatever code Yaost used to connect to the editor and display their panel had a subtle change and Yaost hasn't adjusted to meet the change yet - this feedback would be much more beneficial to give to Yaost directly, because then they could make the changes they need to make to have it display properly. 

I'm not familiar with their processes directly, but I'm certain either their website or plugin page has a way to contact them and submit this kind of feedback.

**Comment by darkonelson** [comment]
Well after all upgrades I have some problems.Before contacting anyone I try
to determine in which theme or plugin the problem is.
When I switched from Astra to twenty twenty and switch off all plugins
problem persist with diference-Yoast panel is closed now.
I contacted Yoast and gave them credentials. After two logins they said
that cannot reproduce same problem???
Now the question at all is whether and when it will be resolved. If it was
something else everything would be o.k.
 But this prevents me from using the block editor and publishing new
materials.
Thank you for your help
Nelson

**Comment by fwazeter** [comment]
Yeah, definitely sounds pretty frustrating. It's just that no one contributing to WordPress that doesn't happen to be part of Yaost's team has no way of actually doing anything about it, since it's just happening with Yaost (a fully independent company from  WP), it's something going on there with them. 

It'd be the same thing as if you downloaded a plugin of mine, an update could happen, it could cause everything to go wonky for you, and no one here could help you with it unless it was me, as much as we might want to (cause you know, it sucks to say "hey, not our problem it's THAT person over there!"). 

~~Doesn't look like they have a public github repository to submit similar feedback in an issue tracker so I don't even have a good direction I could point you in.~~ Comment below found it! for some reason, my search couldn't pull it up.

**Comment by darkonelson** [comment]
Thank you for your help.
I really appreciate that.
Nelson

**Comment by Luehrsen** [comment]
> Doesn't look like they have a public github repository to submit similar feedback in an issue tracker, so I don't even have a good direction I could point you in.

The public GitHub Repository for Yoast SEO is here: 

https://github.com/Yoast/wordpress-seo

**Comment by andreaslindahl** [comment]
I'm getting the same behaviour, both with Yoast and Advanced Custom Fields plugins. So unclear if the error is on their side or on the Wordpress side?

**Comment by carolinan** [comment]
Hi, thank you for reporting this.
This issue is actually a duplicate, and it has been reported multiple times. I have been trying to locate the problem and resolve it without being able to.

Any input and continued troubleshooting would be much appreciated, and can be added to the original issue:
https://github.com/WordPress/gutenberg/issues/38062

I can confirm it does not only affect Yoast SEO.

**Comment by darkonelson** [comment]
There are no errors in the console, only warnings.
![Warnings in console](https://user-images.githubusercontent.com/87546406/154540694-277c8b70-3b4b-44e5-adc4-feaab9994bf3.jpg)
