### ISSUE TITLE
On some screen resolutions heights, FSE's color styles custom gradients color picker positioning prevents changing the color's settings

### ISSUE THREAD

**Issue by nekohayo** [WordPress/gutenberg#38834]
### Description

Gutenberg's FSE miscalculates the position of its chained gradients+colors popup widgets need to be, resulting in the impossibility of setting exact color parameters.

See the attached screencast, particularly the 2nd part when I get to the gradients' colors.

### Step-by-step reproduction instructions

1. Size your browser window to be on a 1080px-high display with some space lost to toolbars and taskbars above/below etc., so let's say 700-800px usable height for the FSE
2. Create a custom gradient in the colors styles sidebar
3. Try to pick one of the colors of the gradients
4. Try to set the numeric values defining that color

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/479401/154163584-84f9488d-a3f4-434f-aa17-8f09d7c607b0.mp4

### Environment info

- Wordpress 5.9 with its built-in Gutenberg
- Firefox on Linux

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Thelmachido** [comment]
Hi, @nekohayo I cannot reproduce this, if you try to add a custom gradient color now the pop-up window gives you the option to scroll up and down to add the color codes you want as shown in the video below:

https://user-images.githubusercontent.com/41231764/190621160-516e584d-fa2b-4fba-bb6f-a5162a3110a9.mov

This might have been fixed in the recent updates, I am going to close this issue for now but feel free to check and add more information. 

WordPress 6.0.1
Gutenberg 14.1.0
Twenty Twenty Two theme
