### ISSUE TITLE
Query block and sticky posts issue

### ISSUE THREAD

**Issue by KristofferBroberg** [WordPress/gutenberg#38895]
### Description

Query block set to display only sticky posts work as expected in the editor but not on the frontend.

On the front end, sticky posts either doesn't show or standard posts are shown if there aren't any posts marked as sticky. 

### Step-by-step reproduction instructions

1. Make sure at least on post is set to sticky
2. Add a query loop in the block editor.
3. Set the Sticky post setting to "only"
4. Confirm that posts are displaying in the editor.
5. Save and view the front. 

### Environment info

Wordpress 5.9
Tested with and without latest Gutenberg plugin activated.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by KristofferBroberg** [comment]
Same as  #35322 ?

**Comment by skorasaurus** [comment]
Hi @KristofferBroberg ; this is the same as https://github.com/WordPress/gutenberg/issues/35322 ; so I'll close the issue and you can follow the progress and share any additional thoughts in that thread. We like each issue to be unique to keep things orderly and be able to determine how many people are affected by an issue.

**Comment by ntsekouras** [comment]
👋 @KristofferBroberg 

In your issue you're talking about a `Query Loop` that `inherits the query` from template or for the custom queries? Because I just opened a PR for custom queries [here](https://github.com/WordPress/gutenberg/pull/38909), but in `inherit` queries have other nuances and I'm thinking of hiding the control in that case to avoid confusion, as it needs investigation to be handled properly.

**Comment by KristofferBroberg** [comment]
Hey @ntsekouras!

I don't have access to the computer I "develop" my theme on right now, but I'm pretty sure the problem was there both ways...inherit and custom. Either way, #38909 looks promising and should solve it for me at least!
