### ISSUE TITLE
Block inline styles does not present in correct block

### ISSUE THREAD

**Issue by randhirexpresstech** [WordPress/gutenberg#38905]
### Description

Either block inline styles does not present in correct block or correct inline block styles not loading or extra inline block styles loading in twentytwentytwo theme
Here is an example of button block which is a child block of buttons block. Styles related to button block written in buttons block and does not load in some FSE themes which do no use `add_filter( 'should_load_separate_core_block_assets', '__return_false' );
`. 
Please check [screencast-block-inline-styles-not-present-in-correct-block](https://app.usebubbles.com/mfSPrmUPowhPgqUkeEQpSq/block-inline-styles-not-present-in-correct-block) 

[Block button css works after adding buttons block ](https://app.usebubbles.com/uhEgN4kugRA1CE7MNna4Gx/block-button-css-works-after-adding-buttons-block)

### Step-by-step reproduction instructions

1. Activate Twenty Twenty-Two theme
2. Install woocommerce plugin and setup a store 
2. go to woocommerce > Get ready to start selling > Personalize my store > create home page 
3. Visit homepage and inspect first "Go shopping" button on cover. check the CSS style ".wp-block-button.aligncenter". you will find css related to wp-block-button under **wp-block-buttons-inline-css** instead of **wp-block-button-inline-css** 
4.  You will not find **wp-block-buttons** in entire HTML page except its only inline css which is loading even if we do not use its block.
5. Activate any other FSE theme which doesn't use `add_filter( 'should_load_separate_core_block_assets', '__return_false' ); ` example- Bricksy, Gutena
6. Check homepage, you will see "Go shopping" button no more centre aligned because **wp-block-buttons-inline-css** is not loading there. 
7. Edit homepage and add a buttons block anywhere in the page. Check homepage, you will see "Go shopping" button aligncenter css will work OR Go to tools > theme file editor > click on functions.php file 
8. add  `add_filter( 'should_load_separate_core_block_assets', '__return_false' );`  in functions.php file and click update file 
9. Check homepage, you will see "Go shopping" button aligncenter css will work

### Screenshots, screen recording, code snippet

Please check [screencast-block-inline-styles-not-present-in-correct-block](https://app.usebubbles.com/mfSPrmUPowhPgqUkeEQpSq/block-inline-styles-not-present-in-correct-block) 

[Block button css works after adding buttons block ](https://app.usebubbles.com/uhEgN4kugRA1CE7MNna4Gx/block-button-css-works-after-adding-buttons-block)

### Environment info

WordPress Version 5.9
WooCommerce Version 6.2.0
Twenty Twenty-TwoVersion: 1.0
BricksyVersion: 1.1.9
GutenaVersion: 1.0.3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
This issue was reviewed in today's Editor Bug Scrub. Thank you for sharing. In the latest versions of WordPress and Gutenberg, it is not possible to place a Button bock on the page without being contained within a Buttons block. That said, what you described regarding inline styles is the correct implementation. 

Inline block styles are only loaded when the block exists on the page. It looks like custom styles for the Button block were added to the stylesheet for the Buttons block. In the screenshare, somehow, there is a Button block not contained in a Buttons block. Therefore since there is no Buttons block on the page, the inline styles for the Button block are not rendered. From what I can tell, everything is working correctly here.

Perhaps WooCommerce includes a block pattern with a solitary Button block. If this is the case, the best solution is to swap out the button with a Buttons block. 

In light of this investigation, I am going to close this issue. But feel free to reopen as needed.
