### ISSUE TITLE
Block template resolution isn't  working on Windows

### ISSUE THREAD

**Issue by Mamaduka** [WordPress/gutenberg#39024]
Originally reported on Twitter by @gmazzap. Thank you, Giuseppe.

> They _recursively_ check the theme's "template/" folder to find HTML templates, but they don't normalize found paths.
So templates inside "template/" subfolders are not found on Windows.

https://twitter.com/gmazzap/status/1496037481069916160

**Comment by gmazzap** [comment]
Thank you @Mamaduka 

First, sorry for the obvious typo in the tweet (it's `templates/`)

## How to reproduce

In a vanilla WP 5.9 installtion, add the following to the twentytwentytwo `functions.php`:

```php
add_action(
    'theme_page_templates',
    function ($templates): array {
        return array_merge(['my-folder/my-template.php' => 'My Custom Template'], $templates);
    }
);
```

Then edit/create a page in WP, and select the "My Custom Template" template.

Now, in the twentytwentytwo `templates/` folder, create the `my-folder/` folder, and add a `my-template.html` template. 
(Maybe you can copy and rename `page.html`).

In the template editor you now see the "My Custom Template" template. Change something so you can recognize when it is used.

Go back to the edit screen of the page that has assigned the template and preview it.

If you are on Windows, the template will _not_ be used.

## Debugging

The issue happens in the `gutenberg_get_block_templates` / `get_block_templates` function.

On Windows, here: https://github.com/WordPress/gutenberg/blob/7628871fb78b85f5f2adac10a80ad7dda7246b4a/lib/compat/wordpress-5.9/block-template-utils.php#L705 `$should_include` is `false`, because `$fits_slug_query` is false.

And that because here https://github.com/WordPress/gutenberg/blob/7628871fb78b85f5f2adac10a80ad7dda7246b4a/lib/compat/wordpress-5.9/block-template-utils.php#L702  `$query['slug__in']` will contain the array item `my-folder/my-template`, but `$template_file['slug']` is `my-folder\my-template`.

So the cause is that `$template_file['slug']` has Windows directory separator. And that's because `_get_block_templates_paths` does not normalize the path here: https://github.com/WordPress/gutenberg/blob/7628871fb78b85f5f2adac10a80ad7dda7246b4a/lib/compat/wordpress-5.9/block-template-utils.php#L230

## Notes

More generally, in the whole Gutenberg code I see there a mix of hardcoding `/` as separator with using `DIRECTORY_SEPARATOR`. I think a better approach would be to make sure that anywhere there a path, that is normalized.

**Comment by Mamaduka** [comment]
I've not seen any other reports regarding this issue, and the mentioned files have been moved to the core repo.

I'll close the issue.
