### ISSUE TITLE
Dropping a block into an empty Group/Column block from the List view

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#39065]
## What problem does this address?
In an effort to explore how we can continue to improve the List view experience, I found that it's not currently possible to drag another block into an _empty_ Group, or Column, block from the List view. 

## What is your proposed solution?
Perhaps empty Group and Column blocks should be treated differently within the List view, where when dragged above, a visual cue indicates we can drop a block into the "empty" one — and on release, the block is added inside the Group/Column block.

#### Design 
We currently have the thin line that indicates where a block should be dropped. We should consider either extending that border around the designated drop-zone, or alternatively setting the background of the drop-zone to the selected state (accent-color).

#### Attempting to drop a block into an empty Group block (current)
https://user-images.githubusercontent.com/1813435/155578647-82556408-c2d7-4187-ad45-9b770eb9c81b.mp4

Note that I've intentionally omitted the Columns block (without a variation assigned). I'd consider that block a different animal, as we'd have to think through what should happen variant wise (like perhaps it sets the 50/50 variant, or 100).

**Comment by richtabor** [comment]
As an aside, we also need a drop indicator for when you're dropping a block into a closed Group/Columns block. It's possible today to do that, but there's no visual indicating it so. Adding this here as it's related design wise.

**Comment by talldan** [comment]
@richtabor It is a little hard to find, but if you drag to the bottom-right of a column or group you can nest a block and the drop indicator should shift to show the nested position.

**Comment by annezazu** [comment]
Noting that I found this as part of trying to determine another issue for the sixteenth FSE Outreach Program call for testing:

https://user-images.githubusercontent.com/26996883/185984138-0a254341-de72-4add-b1b4-76a600b15ca5.mov

This definitely feels very buggy and strange, especially considering you can generally drag/drop using the mover tools.

**Comment by talldan** [comment]
@annezazu As mentioned above, you need to drag to the right side of a block to nest under it.

The reason it works this way is that List View needs a way to determine if you want to drop the block after the column or inside the column. I think the particular situation is confusing, because a user can't drop an imagine after a column. But it makes more sense with other blocks like empty groups.

I don't think this is a bug, the feature is working as intended, but it could absolutely do with some improvement.

Perhaps it's clearer if there's a red drop indicator showing that an image can't be a sibling of a column.

**Comment by annezazu** [comment]
Ah apologies. I thought you were simply describing a workaround rather than an intended functionality. I'll list it as an enhancement. I'd be curious what @WordPress/gutenberg-design might do here.

**Comment by jasmussen** [comment]
It's very clear the drag and drop experience in list view is not great, and the suggestion to highlight the container when dragging on top of it seems like it could work, especially if it's easy to implement.

My mind goes back to #34022, though, which implemented a vastly superior dragging experience:

https://user-images.githubusercontent.com/1270189/135886976-4a905428-918a-419f-9bc5-e9e0fd5518ad.mp4

In this experience, the reactivity makes it clearer which nesting level you're about to drop an item on. There could still be "drop on top of container" added to this one, but even as is, it would likely be an improvement. Performance was a concern at a time, but [the implementation of windowing](https://github.com/WordPress/gutenberg/pull/34022#issuecomment-932600813) seemed to solve that. It would be neat if someone could revisit that PR, see if it can be resurfaced and brought home.

**Comment by talldan** [comment]
> It's very clear the drag and drop experience in list view is not great, and the suggestion to highlight the container when dragging on top of it seems like it could work, especially if it's easy to implement.

It seems like it would require a lot of precision from a user, as we'd essentially be packing in three drop zones vertically per row. (if that makes sense). A row is only 36px, so that means 12px high drop zones.

https://github.com/WordPress/gutenberg/pull/34022 worked a bit better, I think because of the way it allows a clearer visualization of where the block is being dropped to. It still essentially used a similar mechanic of dragging left and right to nest, but felt more natural because you could see where the block would end up.

It'd be good to find a way to land it in bitesized chunks. It's a lot to rebase and review, and also I'm unfamiliar with framer-motion, so have no idea what much of it is doing 😄

**Comment by richtabor** [comment]
This is now resolved ✅
