### ISSUE TITLE
Bug: cannot exit template editing mode in Site editor

### ISSUE THREAD

**Issue by creativecoder** [WordPress/gutenberg#39149]
### Description

Back button disappears from the isolated template part editing in the Site editor, leaving no way to get back to the main editing interface.

### Step-by-step reproduction instructions

- Open the Site editor, select a template part, and open that template part in the isolated editor
- Open the list view and click on one of the blocks in the list
- The "Back" link disappears.

### Screenshots, screen recording, code snippet

![template-back-button-disappears](https://user-images.githubusercontent.com/1699996/156281387-51154b8e-e62c-4e83-b65a-532e659b376a.gif)

### Environment info

- WP 5.9.1
- Gutenberg 12.7.0-rc.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
I think the issue is that the items in List View are links, and when clicked they result in new location state that doesn't have the `fromTemplateId` property used here:
https://github.com/WordPress/gutenberg/blob/827d099c6a342ef38bcee9e86d4ef5058952c01c/packages/edit-site/src/components/block-editor/back-button.js#L17-L21

I notice if you use the browser back button to effectively undo, then the editor's back button appears again.

@kevin940726 wondering if you have any thoughts on the best way to solve this?

**Comment by annezazu** [comment]
Noting that I just ran into this today and can replicate.

**Comment by kevin940726** [comment]
Interesting, I didn't know that the items in List View are links.

Is it possible to override the links in List View to carry on the state? Or maybe we should do that globally when the route change is resulted from a hash change 🤔. Not sure if any of these is possible though, will need to play with it and see how it goes.

**Comment by talldan** [comment]
> Interesting, I didn't know that the items in List View are links.

They weren't originally, they were changed to links at some point. I don't know if that was a good idea or a bad idea 😄 .

It is a bit inconsistent now, because the breadcrumbs at the bottom aren't links.

> Is it possible to override the links in List View to carry on the state?

I don't think so. I would also be concerned that plugins might introduce links elsewhere in the UI that do something like this, so I don't think links will ever be completely under our control.

If there's a way to handle this globally, that might be good.

**Comment by annezazu** [comment]
Adding this to the 6.0 board as this feels critical to fix and was confirmed once more as part of the twelfth call for testing [with the FSE Outreach Program:](https://make.wordpress.org/test/2022/02/23/fse-program-testing-call-12-hyping-headers/#comment-2378)

>I did not have a “Back” per the directions “When done, select “Back” to return to your homepage template…”

**Comment by ntsekouras** [comment]
This seems to have been resolved by @alexstine here: https://github.com/WordPress/gutenberg/pull/37934/files#r816489682

**Comment by creativecoder** [comment]
Confirming this seems to be fixed for me.
