### ISSUE TITLE
@wordpress/edit-navigation is not available on npm

### ISSUE THREAD

**Issue by Heliozoa** [WordPress/gutenberg#39246]
### Description

Hi,
thanks for your work on gutenberg.
I was trying to use the [@wordpress/edit-navigation](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-edit-navigation/) package in a project that already depends on some `@wordpress` packages, but [I wasn't able to find it on npm](https://www.npmjs.com/search?q=%40wordpress%2Fedit-navigation). I assume this is because the package is marked as private in the package.json:
https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-navigation/package.json#L4
The [package docs](https://developer.wordpress.org/block-editor/reference-guides/packages/#using-the-packages-via-npm) make it sound like it should be published, so I decided to make an issue. Alternatively, if it is meant to be private, I think the docs could be clarified.
Thanks for any help!

### Step-by-step reproduction instructions

1. Run `npm install @wordpress/edit-navigation`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Hi @Heliozoa - thanks for reaching out about this. The edit-navigation package is still highly experimental at the moment, so that's the main reason for it not being published.

There's still a lot of change that will probably happen to this package, so it's impossible for the maintainers to guarantee a stable public API.

I think the best thing would be to make this clearer by adding a note explaining this at the start of the README file.

**Comment by kathrynwp** [comment]
Closing this issue due to the Navigation Screen project being moved to [an inactive status on the feature projects page](https://make.wordpress.org/core/features/) in coordination with the project leads. (The developer documentation in the initial post are no longer accessible)

If this work is picked back up, issues can be revisited and reopened as needed. Thanks for pitching in on this early feature so the wider WordPress project could benefit from the lessons learned!

**Comment by seanvarnham** [comment]
Can I just ask, why does WordPress release docs on their website for unpublished packages ([@wordpress/edit-navigation](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-edit-navigation/)), yet many functions in some existing packages aren't even acknowledged in the docs...?

**Comment by kathrynwp** [comment]
@seanvarnham Good question! I'm guessing that since documentation efforts (as with development) are all volunteer-driven, not all features are documented evenly. If you see something undocumented or unacknowledged, please feel free to report it here: https://github.com/WordPress/Documentation-Issue-Tracker/ Thanks!
