### ISSUE TITLE
Provide a pathway to migrate widgets to block themes

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#39270]
## What problem does this address?

Currently, when switching from a classic theme to a block theme, widgets created in the classic theme aren't migrated over. 

## What is your proposed solution?

I could have sworn this was previously discussed, whether on a hallway hangout or in a core editor meeting, but I can't find any related issues so I decided to open this one up since this recently came up as a point of feedback. Since widgets "live" in the spaces that template parts fill, it makes the most sense for migration to happen in the form of generating template parts during migration:

- User has widgets in a classic theme.
- User switches to a block theme. 
- Widget areas are converted to an equivalent template part with blocks (header, sidebar, etc). Anything already a block can remain as such and anything else could be converted to a legacy widget block thanks to the work done with the block widget editor. 

If the user didn't want to use this, they could just ignore or delete the template part. If they switched back to a classic theme, it should preserve backwards compatibility. I don't know enough about the technical underpinnings here either way but wanted to get this documented regardless as it feels like a key area of refinement ahead of more folks adopting block themes in due time.

**Comment by mtias** [comment]
So I think you should be able to import an existing widget area content into a template part. We should probably place this in the block inspector for a template part as an "import", "use existing widget area" or "transform" action:

<img width="569" alt="image" src="https://user-images.githubusercontent.com/548849/175947529-edcff110-aeae-4fcb-a5bf-1900b7fe79ef.png">

Considering widget areas can already have block content, this should be a fairly seamless transition. Once it's possible to use and edit template parts on non-block themes (#37943), this flow should be even more transparent.

**Comment by noisysocks** [comment]
> I could have sworn this was previously discussed

It might have been privately with me! 😅 Let me copy and paste some notes that I wrote in July 2021 about this subject:


<h2 id="using-cpts">Using CPTs</h2>



<ul><li>Hook into <code>after_theme_switch</code>. When we detect that user is moving from a classic theme to a block theme, or from a block theme to a classic theme, perform a migration.</li><li>Migrating from a classic theme to a block theme: Grab all of the widget areas in the classic theme (<code>sidebar-1</code>, <code>footer-1</code>, etc.), create a template part with the same ID for each widget area, run <code><a href="https://github.com/WordPress/gutenberg/blob/6160b5d54d98ab5e57808f65e45781c8b19e10ba/packages/edit-widgets/src/store/transformers.js#L7" rel="nofollow ugc">widgetToBlock</a></code> on each widget to create template part HTML.</li><li>Migrating from a block theme to a classic theme: Grab all of the widget areas in the classic theme, find any template part with matching ID, run <a href="https://github.com/WordPress/gutenberg/blob/6160b5d54d98ab5e57808f65e45781c8b19e10ba/packages/edit-widgets/src/store/transformers.js#L37" rel="nofollow ugc"><code>blockToWidget</code></a> on each block to create widgets.</li><li>Block widgets are turned directly into the block that's stored in it. Legacy widgets are turned into a <code>core/legacy-widget</code> block.</li><li>The site editor can include legacy widget scripts if it detects the use of a <code>core/legacy-widget</code> block.</li><li>In a classic theme, you do not see the site editor. In a block theme, you do not see Appearance → Widgets.</li></ul>



<h3 id="pros">Pros</h3>



<ul><li>Minimal changes required for the site editor.</li><li>The site editor only has to know about template parts, which it already supports. (It's a "clean slate".)</li><li>Migration, while finicky, is easy to write unit tests for.</li></ul>



<h3 id="cons">Cons</h3>



<ul><li>Running migration scripts on theme switch can be finicky. Need to ensure we create backups of data. Need to ensure we handle edge cases such as ID conflicts.</li><li>Block themes will not have any notion of a "widget area". Plugins which add functionality to widget areas will no longer work.</li></ul>



<h2 id="using-widget-areas">Using widget areas</h2>



<ul><li>Provide a Widget Area block in the site editor.</li><li>In the frontend, the Widget Area block renders a single widget area by calling <code>dynamic_sidebar()</code>.</li><li>In the editor, the Widget Area block renders an <code>InnerBlocks</code>.</li><li>The Widget Area block uses <code>EntityProvider</code> to save changes to a <code>sidebar</code> entity via the <code>/wp/v2/widgets</code> API added in 5.8.</li><li>The Widgets screen can be refactored to use this Widget Area block as well as the multi-entity saving system. (This also fixes <a href="https://github.com/WordPress/gutenberg/issues/32952" rel="nofollow ugc">#32952</a>.)</li><li>Legacy widgets continue to work via the <code>core/legacy-widget</code> block.</li><li>Block themes can support the Widgets editor at Appearance → Widgets if we want.</li></ul>



<h3 id="pros">Pros</h3>



<ul><li>Can have the standalone Widgets editor in block themes if we want. It's arguably a nicer interface than the standalone template editor.</li><li>"Widget areas" continue to exist meaning plugins which use them and add functionality to them can continue to work.</li><li>No finicky migration.</li></ul>



<h3 id="cons">Cons</h3>



<ul><li>Requires block theme authors to have to know about widget areas <strong>and</strong> template parts, even though both concepts are very similar (identical?).</li><li><code>dynamic_sidebar()</code> and its ilk are a mess :) No "clean slate" for block themes.</li></ul>



<hr class="wp-block-separator has-css-opacity"/>



<p>I lean towards the first approach because I feel it fits nicely with block themes and the site editor being a "fresh start" for WordPress that serves as a foundation for the next 15 years of growth. In the year 2030, do we want to be explaining to developers what a "widget" is? :) </p>



<p>But, this is all hypothetical. I think we should build a prototype of both approaches and see what happens.</p>

**Comment by noisysocks** [comment]
> We should probably place this in the block inspector for a template part as an "import", "use existing widget area" or "transform" action:

I like this idea of doing the migration on request as opposed to automatically on theme switch. It's more intentional—less surprises. Also, it caters for users who wish to ditch their existing widget areas and start fresh.

**Comment by carlomanf** [comment]
@noisysocks There are a few issues I see with the "Using CPTs" proposal:

- The migration will not run if the `after_theme_switch` hook doesn't fire for some reason (e.g. if the theme is switched using phpmyadmin)
- Currently, there is still no way to retrieve template parts from inactive block themes (see #31397) so the widget areas would only become available to block themes that are activated immediately in the wake of a classic theme, but not to block themes activated in the wake of another block theme, which seems silly.

I think @mtias suggestion of importing widget areas on request is far more preferable, and I believe it also mirrors the ability to import menus to the navigation block.

That said, the lack of a solution to #31397 could still cause confusion for users about why it's easier to import a "legacy" widget area than to import an inactive template part. No equivalent problem exists for the navigation block because navigations are not tied to themes.

#31971 still looks like a workable first step to solving #31397 but was closed due to the PHP code being moved from the experimental plugin into core.

**Comment by noisysocks** [comment]
Yeah, good call on https://github.com/WordPress/gutenberg/issues/31397. I think it's another missing piece of the theme switching puzzle.

What makes sense to me right now is that both widget areas and template parts to stick around in the database after switching theme and for us to provide:

- For block themes, UI to import an old widget areas into a template part.
- For classic themes, UI to edit template parts in WP Admin and the ability to programatically render a template part (e.g. by calling `render_template_part()`).

**Comment by mtias** [comment]
@noisysocks the function for the last part already exists — themes can use `block_template_part( $part )` already in PHP. It's just lacking a UI to edit them.

**Comment by mtias** [comment]
I'm bumping the priority of this for visibility.

**Comment by Mamaduka** [comment]
I just pushed my current progress for this feature #45509.
