### ISSUE TITLE
BaseControl help text not screen reader accessible

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#39271]
### Description

The BaseControl component accepts a `help` prop, that renders as an additional description for the control. That description is wrapped in a `p` tag, but it is not linked to the control in any way, so screen readers ignore it.

One way to fix this is adding `aria-describedby` to the control itself, pointing to the `id` of the description.

### Step-by-step reproduction instructions

1. In the post editor, click the top right hand side "Options" button, and then click the last button on the dropdown, "Preferences". This should open a modal dialog with three tabs of editor preferences.
2. Under General > Publishing, there is a toggle with the label Include pre-publish checklist" and help text: "Review settings, such as visibility and tags."
3. Using a screen reader, focus this control. Note the label is read out but the help text is ignored.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Smit2808** [comment]
Hi @tellthemachines 

Can you tell me your environment? because I am not able to reproduce the issue. It's working fine in my system.

And the control field also has the aria-describedby attribute with the value pointing id of help text "p" tag.

My environment:
-> Mac OS
-> Browser chrome
-> Wp fresh installed site wp v5.9.1
-> No external plugin or theme installed
-> Using Gutenberg trunk repo.

**Comment by tellthemachines** [comment]
Oh weird, I can no longer reproduce it on trunk either. Fwiw I was working on #39176 and testing on Safari/VoiceOver, and the description wasn't being read out.

I'll close this for now.
