### ISSUE TITLE
Links are invisible on the mobile.

### ISSUE THREAD

**Issue by HILAYTRIVEDI** [WordPress/gutenberg#39335]
## Description
In the twenty twenty-two when I am opening the hamburger menu in the customizer the links take the same color as the background of the mobile menu due to which it appears to be invisible.

## Step-by-step reproduction instructions

1. Activate theTwenty Twenty-Two theme
2. Add some pages to your site(if not).
3. Go to the customizer.
4. In the customizer, you will see your pages listed in the navigation. Click on the preview > mobile.
5. You will see that all the links disappear as they have the same color as the background.

## Expected behavior
The link's color should be different and darker according to the background by default.

## Actual behavior
The links and background have the same color.

## Screenshots or screen recording (optional)

https://www.loom.com/share/d3717fcb5ab74549bc014dfd11dad176

## WordPress information
- WordPress version: 5.9.1
- Gutenberg version: 12.8.0
- Are all plugins except Gutenberg deactivated? "Yes"
- Are you using a default theme (e.g. Twenty Twenty-One)? "Yes"

## Device information
- Device: Laptop
- Operating system: macOS

**Comment by hypest** [comment]
Thanks for opening this ticket! I will remove the `Mobile App - i.e. Android or iOS` as that label is only used for issues that happen in/due the mobile _apps_.

**Comment by HILAYTRIVEDI** [comment]
#39635 This PR will fix the issue.

**Comment by ndiego** [comment]
This is actually a theme design "issue" in Twenty Twenty-Two. Everything is technically working, but the Header template part has set the Link color to White, which causes them to "disappear" in the mobile overlay. This can be easily fixed by setting the text overlay color on the Navigation block, see the screenshot below. Since this is theme related, I am going to close this out. 

![image](https://user-images.githubusercontent.com/4832319/186182728-a01e51d2-c74e-4c00-9947-6f0680ec4d69.png)
