### ISSUE TITLE
FSE: Discrepancy between back and frontend if changing content width in templates

### ISSUE THREAD

**Issue by onetrev** [WordPress/gutenberg#39527]
### Description

I've noticed that if you change a Group Block's width in a page template, the changes work on the frontend but are not reflected in the backend. Instead, the backend continues to rely on the theme.json setting for `contentSize`. 

Here's a screenshot from my editing the Group Block for the content area of the Page Template. I've changed the width to 980px.

![Screenshot 2022-03-17 141323](https://user-images.githubusercontent.com/597601/158732072-e507abca-8c23-4571-b26e-f3f8ef087686.jpg)

But you can see when editing a page in the WP admin, it's using the theme's (Videomaker in this case) contentSize value.

![Screenshot 2022-03-17 141754](https://user-images.githubusercontent.com/597601/158732173-0f9c33f0-a6be-4117-a412-f604cec99ab2.jpg)

The good news is that in the end, attachment below, the proper width is applied on the frontend, but shouldn't the WP admin be able to use this value as well?

![Screenshot 2022-03-17 142118](https://user-images.githubusercontent.com/597601/158732284-367624b4-295c-4ae0-a655-7e17b8c870a3.jpg)

### Step-by-step reproduction instructions

1. Alter Group Block wrapper in Site Editor template to be a different value from the theme's default value.
2. Add content to a page in WP admin that uses the above template.
3. Check width in admin vs width output on the front end.

### Environment info

- WordPress 5.9 (no Gutenberg plugin)
- Theme: Videomaker

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
Yes, this is an issue that has existed for some time. Layout settings in Templates are not actually reflected in the Page Editor. This is a larger issue due to the fact that the Page Editor is not really "aware" of the template that has been applied to a post/page and is beyond the scope of 6.0 at this point. Therefore, I am going to remove it from the [6.0 Project Board](https://github.com/orgs/WordPress/projects/27/views/1), but it would be a good one to revisit for future versions of Gutenberg and 6.1.

**Comment by onetrev** [comment]
Pretty sure with the iframed editor this isn't an issue any more. Not from my testing, so closing this out.
