### ISSUE TITLE
List v2: Add a different icon for List Item

### ISSUE THREAD

**Issue by ntsekouras** [WordPress/gutenberg#39628]
## What problem does this address?
Currently the experimental new `List` and `List Item` blocks share the same icons. We should have different icons to differentiate them easier.
<img width="597" alt="Screenshot 2022-03-22 at 9 36 37 AM" src="https://user-images.githubusercontent.com/16275880/159430697-bf9df5d1-8663-4daa-97a8-7c2d94efd980.png">

--cc @jasmussen

**Comment by jasmussen** [comment]
For now and as we're still exploring, could we use these two icons depending on whether the parent container is set as ordered or unordered?

<img width="259" alt="Screenshot 2022-03-22 at 09 08 37" src="https://user-images.githubusercontent.com/1204802/159435726-14062fa9-633a-4c16-a208-1c4b0102387f.png">

**Comment by ntsekouras** [comment]
>For now and as we're still exploring, could we use these two icons depending on whether the parent container is set as ordered or unordered?

I don't think that's possible right now. While this is similar to block variations we don't have a way to know the parent's attributes in the places we need to show the icon. 

It's not urgent issue for sure though 😄

**Comment by jasmussen** [comment]
A thought:

Since a list item can only ever be used inside an ordered or unordered list, could we actually not show any icon in that toolbar? I would expect main list transformations (transforming to a ToDo list, for example), to happen on the parent list block, and there wouldn't ever be any transformations on list items. Like so:

<img width="849" alt="Screenshot 2022-03-23 at 09 23 53" src="https://user-images.githubusercontent.com/1204802/159655103-bf5b3818-1eb1-45ce-8848-c8c93fa1df6d.png">

This would make it an exception to the rule for block toolbars, but with a clear heuristic: ol/li and ul/li are inevitably tied together. Definition lists (dl/dt/dd) would would fall in under the same heuristic.

🤔

**Comment by jasmussen** [comment]
Alright, let's try this one, the second one:

<img width="732" alt="Screenshot 2022-03-31 at 09 26 14" src="https://user-images.githubusercontent.com/1204802/161000921-145ac505-9bb3-43f3-a52b-6fa09b30b08d.png">

SVG:

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" style="enable-background:new 0 0 24 24" xml:space="preserve"><path d="M12 11v1.5h8V11h-8zm-6-1c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z" style="fill:#1e1e1e"/></svg>
```
