### ISSUE TITLE
Remove the `inherit` option from the Comments Query Loop and Comment Template

### ISSUE THREAD

**Issue by michalczaplinski** [WordPress/gutenberg#39648]
## What problem does this address?
https://github.com/WordPress/gutenberg/pull/39227  either introduces breaking changes to existing comment pagination functions, OR introduces Gutenberg-dedicated functions that are reliant on how core comments utilize pagination URLs.

But there are underlying challenges brought on when pagination between core comments and comment blocks are out of sync. Both share the same URL, but have to indicate differing indexes of pagination.

## What is your proposed solution?
Remove the following options from the Comments Query Loop and Comment Template blocks:
- `perPage`
- `order`
- `defaultPage` 
- `inherit` 

Additionally, we should ALWAYS inherit the related settings from the core Discussion settings.

**Comment by gziolo** [comment]
I see that the block works now only when the `$post` object is set on the page.

https://github.com/WordPress/gutenberg/blob/ec2ac147e3e06c64f79d08b3ebc6ff770c263dbf/packages/block-library/src/comment-template/index.php#L56-L59

Otherwise, it renders nothing.

Maybe the user-facing name of the block should also change to better align with what is capable of doing. It's a Post Comments List with all the options removed. If you look at the PHP implementation of the `WP_Comment_Query` class, you can see that it supports a long list of params for the query which makes it very flexible and it definitely can work in all different scenarios:

https://developer.wordpress.org/reference/classes/wp_comment_query/

**Comment by luisherranz** [comment]
Do you mean dropping the word "Query" from the "Comments Query Loop" name in the block [title](https://github.com/WordPress/gutenberg/blob/ec2ac147e3e06c64f79d08b3ebc6ff770c263dbf/packages/block-library/src/comments-query-loop/block.json#L5)?

**Comment by gziolo** [comment]
> Do you mean dropping the word "Query" from the "Comments Query Loop" name in the block [title](https://github.com/WordPress/gutenberg/blob/ec2ac147e3e06c64f79d08b3ebc6ff770c263dbf/packages/block-library/src/comments-query-loop/block.json#L5)?

Maybe. I'm mostly confused at the moment what's the current plan for the block. It's much simpler than all the initial explorations and has limited application. Still, it's a great replacement for the existing Post Comments block that shipped in WordPress 5.9. Well, it also makes me realize that at the moment we have two similar blocks 😄

**Comment by luisherranz** [comment]
> It's much simpler than all the initial explorations and has limited application

It is, but I guess it's better to make it public without those options in 6.0 and then evaluate the current issues with the non-inherited options than wait until all the problems are solved, don't you think?
