### ISSUE TITLE
wp-block-navigation do not support "current-menu-ancestor current-menu-parent " for parent items when the sub item is active ?

### ISSUE THREAD

**Issue by hoangvs** [WordPress/gutenberg#39663]
### Description

Hello Everybody,

I have a problem with wp-block-navigation when I use Twenty Twenty-Two theme. It's not assign "
current-menu-ancestor current-menu-parent" to parent menu like old wp_nav_menus system. So It's hard to me detect current parent menu .

I wish someone can help me on this .

**Comment by illycz** [comment]
This is essential!

**Comment by illycz** [comment]
I'm using classic menu for now. But support for current parent is really essential...

**Comment by Marc-pi** [comment]
@gziolo any chance to have this shipped in with upcoming 6.0/6.1 ? i know features are freezon on beta cycles but :
* **Such regression fix is indeed a quick win addition ... and make the core navigation block more usable / finalized on real projects, other wise we need menu extensions or custom code...
* Would permit to hightlight parent entry when child is active, so that common non dev user can easily add dedicated css decoration rules.

BTW The customizer is still there - but hidden - so we can make quickly small adjustements without to have to create a child theme. I hope you'll add back a way for us to customize css rules directly within the editor,

**Comment by aristath** [comment]
PR: https://github.com/WordPress/gutenberg/pull/40778 👍

**Comment by annezazu** [comment]
cc @getdave in case you might have insight here!
