### ISSUE TITLE
No content visible when a plugin containing a block is activated

### ISSUE THREAD

**Issue by donnapep** [WordPress/gutenberg#3978]
## Issue Overview
No content is visible for a page, post, or custom post type when a plugin containing a block is activated.

## Steps to Reproduce (for bugs)
1. Download the `add/module-block` branch of the [Sensei plugin](https://github.com/Automattic/sensei/tree/add/module-block).
2. Do an `npm run build` before copying the plugin folder to a site and activating it.
3. In the admin, go to a page, post or CPT that you know has some content.
4. Notice that no content is visible in the editor, but that there are console errors that appear unrelated to Sensei:
![gutenberg-console-error](https://user-images.githubusercontent.com/1190420/33949123-b2c508b0-dff6-11e7-97cd-bb7c944613dc.jpg)
5. Switch to Code Editor view to confirm there is content:
![code-editor](https://user-images.githubusercontent.com/1190420/33949128-b8d11154-dff6-11e7-975d-16ca384ab5bb.jpg)
6. Switch back to Visual Editor and the following error appears:
![visual-editor-error](https://user-images.githubusercontent.com/1190420/33949102-9d8d9048-dff6-11e7-9c7a-c00d5bb0a339.jpg)

Chrome 62.0.3202.94 on MacOS 10.12.6 and WordPress 4.9.1, Gutenberg 1.9.1. No other active plugins.

## Expected Behavior
I would expect to see content in the editor for a page, post or CPT.

## Current Behavior
There is no content in the editor for a page, post or CPT.

## Possible Solution
The problem does not appear to be with the block that's implemented in Sensei, as the console error references the `_pluck` function, which I'm not using. Let me know if there's any further info that would aid with debugging though.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by danielbachhuber** [comment]
Hi @donnapep,

Thanks for the detailed report. Based on what you've shared, it appears TinyMCE views has an undeclared dependency on the [Underscore](http://underscorejs.org/) library. Because this dependency isn't met, you're experiencing a JavaScript error which causes the rest of Gutenberg to fail.

I tried #4647 locally but that didn't seem to fix it.

**Comment by danielbachhuber** [comment]
Oh, here's another clue. There's a newer version of Underscore? scoped to `window._`:

![image](https://user-images.githubusercontent.com/36432/35302057-1c3df598-0042-11e8-9c20-d19d9f852785.png)

WordPress bundles 1.8.3:

![image](https://user-images.githubusercontent.com/36432/35302104-3e284366-0042-11e8-9801-a2ddb76582ea.png)

It looks like 1.8.3 is the official version, so some dependency you've added has included a global `_`.

**Comment by nerrad** [comment]
I just encountered this too.  I have a plugin that is declaring the built-in WordPress underscore library as a dependency and thus `_.` gets scoped globally.  That is conflicting with lodash which is a dependency of Gutenberg.

**Comment by nerrad** [comment]
So if I do the same thing as you did @danielbachhuber in a _working_ gutenberg instance, I get the same values.  From the `_.VERSION` value I'm guessing that its actually lodash that is scoped as the `._` global.

**Comment by nerrad** [comment]
K figured it out and putting here for anybody else who stumbles on this problem.  The issue was that in the plugin I created for custom gutenberg blocks, I was using lodash in the build.  If one does not just import the specific things needed from lodash, the `_` lodash global method name gets used and that conflicts with underscore in WP.  The easiest way to avoid this is to simply include `babel-plugin-lodash` in your build config (or even easier just include  `@wordpress/babel-preset-default` with your build.

**Comment by schoidev** [comment]
Or put this on your webpack configuration.
```
  externals: {
    lodash: 'lodash',
  },
```
