### ISSUE TITLE
Customizing Block Latest Posts in Editor

### ISSUE THREAD

**Issue by hagege** [WordPress/gutenberg#39825]
In the list of blocks that can be customized when editing the templates, it would be useful if the "Latest Posts" block is also offered. Please have a look at the GIF file
![issue_missing_latest_posts](https://user-images.githubusercontent.com/27292550/160475915-43a80e96-f863-4e8a-a335-45d8adab7eae.gif)

**Comment by annezazu** [comment]
I can replicate this and am not quite sure why it's not listed with Global Styles. Hoping someone else might have some insight :)

**Comment by kathrynwp** [comment]
I'm still able to replicate this with WordPress 6.0.2 (no plugins active) but with Gutenberg 14.1.1 active, the Latest Posts block does show up in the list of blocks:

![Editor__beta__‹_Self-hosted_Test_—_WordPress](https://user-images.githubusercontent.com/7662449/192600755-0af11e5b-08e8-4c8e-95a1-ccd660e53532.jpg)

Closing this out as this should be fixed in core shortly.
