### ISSUE TITLE
Consider adding the ability to replace template parts in template part focus mode

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#39864]
## What problem does this address?

This came up as part of the [twelfth FSE Outreach Program call for testing:](https://make.wordpress.org/test/2022/02/23/fse-program-testing-call-12-hyping-headers/#comment-2377)

>Specifically, I really LOVE the new “Replace” button to choose between an existing template or a Pattern. But I wish I could “Replace” with a Pattern even in focus mode. If I came to this screen to really work on my header, why would I have less options here than I have when looking at the full site?

Here's a quick visual showing how you can replace when in the Site Editor but that option goes away when in focus mode:

https://user-images.githubusercontent.com/26996883/160695386-c424e48f-6e06-499b-b4c7-04471b0f994c.mov

## What is your proposed solution?

I know previously work was done to limit the overall template part settings displayed in focus mode to reduce confusion (https://github.com/WordPress/gutenberg/issues/30732, https://github.com/WordPress/gutenberg/pull/36571) but I wonder if there's a way to bring just the option to Replace the template part will work nicely without opening the can of worms of further customization.

This feels related to this work of showing patterns as section too, specifically around offering more ways to cycle through patterns: https://github.com/WordPress/gutenberg/issues/39281  cc @jameskoster

**Comment by jameskoster** [comment]
This is good feedback, thanks for the mention!

I think we need to tread a little carefully so that we don't conflate the purpose of each view/mode. The regular editor view is optimised for editing the blocks within a template, so it is reasonable that you're able to entirely replace things like headers and footers with relative ease. 

> If I came to this screen to really work on my header

This is the key point I think. The purpose of focus mode (imo) is to concentrate on the blocks within complex units like headers. It's more about fine-tuning than entirely replacing. There is certainly work to be done to refine those heuristics, and I think you're right that 39281 will help a lot there.

All that said, there are probably certain conditions in which focus mode could prioritise surfacing patterns. For example if you create a new header from scratch, or delete all the blocks within the header you're editing.

**Comment by annezazu** [comment]
Going to close this out in favor of this new issue that would address this (and has a clear design): https://github.com/WordPress/gutenberg/issues/44582
