### ISSUE TITLE
Caption before table

### ISSUE THREAD

**Issue by ssimo3lsuhsc** [WordPress/gutenberg#39909]
## What problem does this address?

It is currently impossible to position a caption above a table and **enforce that screen readers will read the caption before the table.** I have tried using headings, but the data that has the same importance as the table in my hierarchy of information is a simple date, and it doesn't really make sense to include a heading at that point.

**Comment by ssimo3lsuhsc** [comment]
Yes, this problem still exists on Gutenberg core.
There is a plugin which can handle before-table captions:
https://wordpress.org/plugins/flexible-table-block/

I will use it as my plugin whenever I want to create WordPress tables until it is no longer being actively developed.

**Comment by ndiego** [comment]
This issue came up in today's Editor Bug Scrub. There is another similar issue with additional information and a [linked PR](https://github.com/WordPress/gutenberg/pull/41980) with a potential fix. Therefore, I am going to close this issue in favor of [Improve table caption accessibility #41502](https://github.com/WordPress/gutenberg/issues/41502). Feel free to add any additional comments there.
