### ISSUE TITLE
Site editor - Duplicated name colors when adding/deleting in custom palette

### ISSUE THREAD

**Issue by geriux** [WordPress/gutenberg#39945]
### Description

While creating a custom color palette in the site editor, there's a case where deleting the first colors would cause a bug where new colors created will keep the previous name causing duplicates. 

Then when using these colors that have the same name there's a bug where the color you select is not the one you see.

### Step-by-step reproduction instructions

1. Go to the site editor
2. Create a new custom color palette
3. Add 3 custom colors
4. Delete the first one or the second one
5. Add a new color (notice that it will have the same name as the previous one)
6. Try to use your new palette and see that selecting the colors that have the same name causes an issue where you can't see the color you're actually selecting.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/4885740/161040523-0190bc90-7ac7-477f-9602-fbf3e22a9f05.mov

### Environment info

- Gutenberg version `12.8.0`
- Browser: Chrome ` 98.0.4758`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by javierarce** [comment]
> While creating a custom color palette in the site editor, there's a case where deleting the first colors would cause a bug where new colors created will keep the previous name causing duplicates.

I imagine that this happens because we generate the name of the new color by adding one  the number of rows. 

A good solution that avoids repeating the name of the color, no matter how they are arranged on the list, would be to do something like Figma does with pages: sort all the pages that are labeled "Page X" (where X is a number), and then create a new page with the subsequent number. 

https://user-images.githubusercontent.com/4933/161078136-cc27953d-83bc-46fe-bc17-8e74de2ce071.mov

**Comment by ramonjd** [comment]
I threw up something over at https://github.com/WordPress/gutenberg/pull/40837

It tries to replicate Photoshop's layout behaviour:

![2022-05-05 12 10 41](https://user-images.githubusercontent.com/6458278/166866539-88633c79-148d-4e88-a78e-c83c4ea435a2.gif)
