### ISSUE TITLE
Uppercase attributes in the default block "Table"  become lowercase

### ISSUE THREAD

**Issue by taraskhvyl** [WordPress/gutenberg#39979]
### Description

When I try to insert svg icon in the editor mode into the cell of default table, attributes with uppercase letters become lowercased. For example, `viewBox`  -> `viewbox`. Because of this, the icon is not displayed in the visual editor.

### Step-by-step reproduction instructions

1. As we have real Gutenberg editor here https://wordpress.org/gutenberg/ , we can use it for this issue.
2. Insert default Gutenberg table with any number rows and cols.
3. Select this table and click `Edit as HTML`.
4. Insert any icon with `viewBox` attribute between `td` tags.
5. After that click `Edit visually` in the table settings.
6. We can see, that icon is absent, because `viewBox` attribute became `viewbox` in the devtools.

### Environment info

On the local env I'm using:

- Wordpress 5.9.2
- Gutenberg 12.8.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
Hi @taraskhvyl, thank you for submitting an issue! I did some digging/testing and unfortunately, this is expected behavior. The Table block uses the [RichText](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/rich-text) component. The component does not natively support SVG markup at this time and as a result, the component is not parsing the markup correctly. Given the nature of SVGs, it is unlikely that the RichText component will ever support them. While not a great workaround, my best recommendation would be to use the HTML block.

**Comment by taraskhvyl** [comment]
@ndiego Thank you for your response!
