### ISSUE TITLE
Heading block inside cover block misses the alignment options

### ISSUE THREAD

**Issue by landwire** [WordPress/gutenberg#39992]
### Description

This is what's missing:
![iScreen Shoter - 2022-04-02 11:22:40 373](https://user-images.githubusercontent.com/1001202/161376896-baa40a8c-2a3d-46f7-811f-f1517a85f7dc.jpg)

I would expect this:
![iScreen Shoter - 2022-04-02 11:24:46 082](https://user-images.githubusercontent.com/1001202/161376894-12868589-2fcd-4963-b558-55242a79d1cb.jpg)

Produces very long headline on wide screens.
![iScreen Shoter - 2022-04-02 11:26:45 746](https://user-images.githubusercontent.com/1001202/161376892-e5a21062-e06a-475b-bf26-a54d963e8501.jpg)

**Additionally as far as I can tell settings.supports.align on the heading block is set to true, which I assume should be false if this for some reason intended behaviour.**

### Step-by-step reproduction instructions

1. Create cover
2. Add heading block inside
3. Alignment is missing

### Environment info

Latest Wordpress
Latest Gutenberg

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
Hi @landwire, this is expected behavior, but I agree that it's confusing. The Cover block does not support block layout (wide, full) on inner blocks, and therefore the Heading block does not have these settings when placed inside of a Cover block. 

That said, if you place a Heading block inside of a Group block, and configure the layout settings (see the screenshot below), the Heading block will then have the expected settings. Currently, the Cover block does not have these layout settings, but I anticipate it will at some point in the future. 

![image](https://user-images.githubusercontent.com/4832319/161450700-46a20bb5-03bb-4dac-8f55-1f0edb673dd7.png)

So a workaround is to create your Cover block, and set the alignment on the Cover block as you would like. I assume you want it full width. Then in the Cover block add a Group block and enable "Inherit default layout" on the Group. Inside the Group add your Header block and you will now have the alignment settings you are looking for. 🙌

Since there is a workaround, and this, unfortunately, is expected behavior at this point, I am going to close out this ticket. Please let me know if I can be of further assistance.

**Comment by landwire** [comment]
Hi @ndiego,
thanks for taking the time to explain the workaround. I have three questions however:

1. Can we make sure that "settings.supports.align" is set to false in situations when a heading block (or any block really) that would normally support align is restricted in that way. Then I can show alternative block settings based on that check.

2. Is there a way to make sure whenever a cover block is used, that it always has a group block inside and a paragraph block inside that group block initially? Basically like block templates on a per block basis?

3. How can I set the "Inherit default layout" to true by default for each group block?

Thanks!
