### ISSUE TITLE
LetterSpacingControl: Add min/max limit to avoid letters overlapping and extra space

### ISSUE THREAD

**Issue by amustaque97** [WordPress/gutenberg#39993]
### Description

While reviewing #39642, I found an issue there is no limit for letter spacing. If negative input is supplied letters overlap and mess the UI. There should be some min and max limit to control this weird behaviour.

As part of the investigation I found we need to make changes here: 
https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/letter-spacing-control/index.js#L37

### Step-by-step reproduction instructions

1. Create a new post or page.
2. Add `site-title` block and write some text.
3. Change letter spacing to some negative value.
4. Save and publish.
5. Open same post and see letters overlapping.

### Screenshots, screen recording, code snippet

<img width="1616" alt="Screenshot 2022-04-02 at 4 30 41 PM" src="https://user-images.githubusercontent.com/21127788/161380201-0351c233-9076-4c74-9a24-ffbf87bd87ef.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Andrew-Starr** [comment]
Not sure there should be any min or max limits imposed. Let the user decide what is best for them in each particular case.

Change the font size to a custom value something like 90px and the -12px letter spacing does not look so weird.

**Comment by amustaque97** [comment]
> Not sure there should be any min or max limits imposed. Let the user decide what is best for them in each particular case.
> 
> Change the font size to a custom value something like 90px and the -12px letter spacing does not look so weird.

This is how it looks with the above mentioned font size and letter space and if we go beyond this, things start looking ugly. Will take suggestion from others to see what we can do best.
<img width="1369" alt="image" src="https://user-images.githubusercontent.com/21127788/161381671-14dbbe40-4b4a-43d3-bb54-e7a39ab39093.png">

**Comment by marceloaof** [comment]
Things start looking ugly just in one perspective, since we have seen bolder, beautiful designs that go more negative than -12 or wider than dozens (fashion font families).
And this is only english... different language alphabets in the west and east which contain different letters, commonly their words are stretched differently.
We also consider animations with CSS in which the starting letter-spacing is considered beyond limits and returns to zero when scrolling the page. Other use-cases: overlapping paragraph blocks, and just a subtle letter-spacing difference between them.

"Not sure there should be any min or max limits imposed. Let the user decide what is best for them in each particular case."

**Comment by amustaque97** [comment]
Make sense 💯 . Thank you for your input @Andrew-Starr  and @marceloaof . Closing this issue because of comment of the above comments.

**Let the user decide what is best for them in each particular case.**
