### ISSUE TITLE
Rename "VisualEditorBlock" to just "VisualBlock"

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#400]
`VisualBlock` seems like a clearer representation.

**Comment by aduth** [comment]
We should consider whether there's any need for conventions binding component names to the class names, as the [currently prescribed CSS guidelines](https://github.com/WordPress/gutenberg/blob/master/docs/coding-guidelines.md#css) require that this component have the class name `editor-visual-editor__block` (at least in its present directory placement).

**Comment by jasmussen** [comment]
Seems like this change should either happen soonish if it needs to.

**Comment by aduth** [comment]
I'm inclined to close this, only because per guideline conventions, the class name of the element _must_ be `editor-visual-editor__block` anyways. Unless we're content with:

```js
const VisualBlock = () => <div className="editor-visual-editor__block" />;
```

Which maybe we are. Otherwise, we could consider revising the guidelines to one more accommodating but similarly consistent, but this seems separate from the issue here.
