### ISSUE TITLE
Fallback content for query loop block when there are no posts.

### ISSUE THREAD

**Issue by AdsonCicilioti** [WordPress/gutenberg#40014]
## What problem does this address?

The user does not see anything if there is no content in the query loop, especially in a template for the search page in FSE.
A bad UX. Which forces us to create a template in PHP and evidence that FSE is not yet mature.

### See, found posts:
![image](https://user-images.githubusercontent.com/6278398/161510099-4220da51-4f9f-4bb8-b69c-06cfc77fdaf6.png)

### When there are no posts:
![image](https://user-images.githubusercontent.com/6278398/161510270-ba78dbb7-563d-4157-a444-00a20faf5567.png)

## What is your proposed solution?

I'm not sure, but we need a way to configure fallback content for this situation.

**Comment by carolinan** [comment]
Hi!
In Gutenberg version 12.9.0 there is a new block that you can place inside the Query loop, called "no results".
The blocks that you place inside this container are shown when there are no results to show. You can place any blocks inside it.

**Comment by ndiego** [comment]
Hi @AdsonCicilioti, I just tested and confirmed @carolinan's recommendation above. The No Results block was added in 12.9, here is the relevant PR: #38806. Note that this block will only be an option when you are adding a block directly to the Query Loop block. If you try and add the block to the Post Template block, it will not show up as an option. The setup you want looks like this:

![image](https://user-images.githubusercontent.com/4832319/161528528-b262e1a1-fbb1-4d9e-8cc6-6502c9985d0a.png)

Since there is a solution, I am going to close out this ticket, but please let me know if you have any additional questions!

**Comment by AdsonCicilioti** [comment]
Yes it's true! Thank you very much @carolinan  and @ndiego !

One more thing, could there be any hint in the documentation indicating the use of these related blocks.
![image](https://user-images.githubusercontent.com/6278398/161626210-11b88270-e099-47bf-8547-3ee9a97d09cb.png)
