### ISSUE TITLE
Fix this column bug right now please?

### ISSUE THREAD

**Issue by MYIG** [WordPress/gutenberg#40030]
### Description

I have been using Gutenberg for a long time, but it is the first time to me...
my column is so strange... what happened????

### Step-by-step reproduction instructions

I am just using columns to restrict my editor width. Because there is no certain feature about it in Gutenberg and Wordpress... if I am knowing about code much, it may not need to do it... Anyway, it works well but the column suddenly becomes horizontally...

### Screenshots, screen recording, code snippet

![normal column](https://user-images.githubusercontent.com/44285360/161568834-bf6bf1d4-f202-47d4-8984-933dabdbb357.jpg)

it is normal

![column bug](https://user-images.githubusercontent.com/44285360/161568857-e3d8cedc-95bc-449b-8851-584ed730d26c.jpg)

it is bug... what happened?

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by bph** [comment]
Hi @MYIG, 
Thank you for reporting! It seems like a bug, indeed. 
Could you please help us to research this bug: 

- What are good steps to reproduce your experience. 
- What are the language and environment settings? 
- What browser are you using? What version? 
- Are you using the Gutenberg plugin? 
- Which WordPress version is installed?

**Comment by MYIG** [comment]
It appears suddenly. I don't know why really.
When I am writing a post, it doesn't happen. It happens when I try to edit my post.
I tested by health check plugin, and I find it doesn't appear when I deactivate Gutenberg.

I am writing Korean but it appears the post translated by WPML. So I think it is not about the language.
I am using Vivaldi Browser mainly. I don't check it in other web browsers.
My Wordpress version is latest.

The amazing thing is it doesn't appear in all column blocks. Some block has that bug...

**Comment by ramonjd** [comment]
> I am writing Korean but it appears the post translated by WPML
>  Anyway, it works well but the column suddenly becomes horizontally

I've tried to replicate this using only the Gutenberg plugin and can't.

I wonder if WPML is adding, or failing to add, [writing-mode CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode) to the document. 

Writing mode determines how text flows and can be vertical or horizontal.

We recently [updated Gutenberg's layout styles](https://github.com/WordPress/gutenberg/pull/38816) so that block top and bottom margins would work if the writing mode changed, but it shouldn't at all affect the direction of text flow.

If possible, it would be great see if WPML are adding any special styles to Korean or other languages that may be writting vertically.

Like Chrome, you can do this in Vivaldi https://help.vivaldi.com/desktop/tools/developer-tools/#:~:text=Open%20a%20web%20page%20or,quickly%20open%20the%20Developer%20Tools.

Have a look at the columns block and the individual blocks within:

<img width="1475" alt="Screen Shot 2022-04-06 at 11 57 14 am" src="https://user-images.githubusercontent.com/6458278/161880636-13401414-3fea-4460-b2ab-14ca284126ac.png">

**Comment by MYIG** [comment]
You can't say easily. I said it doesn't appear when I write it first. And not every column has those bug. It appeared when I edited my post after publishing it first...

But I will test it again only without wpml then...

=> I tested it. I think is bug about my plugin oxygen... if I use both oxygen and Gutenberg, that bug appears... not WPML. hmm sorry about it.

**Comment by ramonjd** [comment]
> I tested it. I think is bug about my plugin oxygen... if I use both oxygen and Gutenberg, that bug appears... not WPML. hmm sorry about it.

Thanks for testing!

I'll close for now given that you've tested with oxygen plugin. 

If the problem persists with Gutenberg only, feel free to reopen the issue.
