### ISSUE TITLE
Improve placeholder for Post Content block

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#40074]
## What problem does this address?

The current placeholder for the Post Content block leaves a lot to be desired both in terms of the overall display and in terms of the space it takes up.  

<img width="1133" alt="Screen Shot 2022-04-05 at 7 26 40 PM" src="https://user-images.githubusercontent.com/26996883/161883523-d50c25e0-70a7-4cc6-ba83-e54988c40840.png">

## What is your proposed solution?

It should give the _impression_  of content to serve as guidance. It's important that it doesn’t look like real content though as this would cause great confusion. As this is being considered, it would be wise to also explore adding additional style options and to ensure that whatever is chosen matches well with the ability to do things like change font size (aka you can see changes reflected) https://github.com/WordPress/gutenberg/issues/35118

**Comment by carolinan** [comment]
What if we displayed the default "Hello world" post with a dashed border around it?

**Comment by carolinan** [comment]
Related:
https://github.com/WordPress/gutenberg/issues/37883

**Comment by mtias** [comment]
I'd avoid any cosmetic effects that can mislead users into thinking they are actual styles. Reusing the hello world content could work as a start.

We should probably also do something similar for the excerpt.

**Comment by carolinan** [comment]
On second thought, I don't think we should use the Hello World content because it encourages users to edit or remove the block 😊 

>Welcome to WordPress. This is your first post. Edit or delete it, then start writing!

Perhaps something like:

This is a placeholder for your content. When you view your website, the block displays the content of the post or page that you have assigned.


Or to give the impression of longer content:

This is a placeholder for your content. When you view your website, the block displays the content of the post or page that you have assigned.

Welcome to WordPress. In the WordPress editor, each paragraph, image, or video is presented as a distinct “block” of content.
Each block comes with its own set of controls for changing things like color, width, and alignment.
These will show and hide automatically when you have a block selected. Experience the flexibility that blocks bring, whether you are building your first site, or write code for a living. Start writing!

**Comment by kristastevens** [comment]
Hi @carolinan, thanks for the ping!

I do prefer the slightly longer version here because it's the perfect place for additional context in helping educate the user at a critical point in the creation process. I really like the line at the end that infuses the user with possibility: "Experience the flexibility that blocks bring, whether you are building your first site, or write code for a living. Start writing!" I made just a few suggestions below, including a slight trim and a little reordering. 

> Welcome to WordPress! 

> This is a placeholder for your content. 

> In the WordPress editor, each paragraph, image, or video is presented as a distinct “block” of content. When you view your website, the block displays the content of the post or page that you have assigned.

> Each block has controls for changing things like color, width, and alignment. These controls will show and hide automatically when you have a block selected. 

> Experience the flexibility that blocks bring, whether you are building your first site, or write code for a living. Start writing!

**Comment by carolinan** [comment]
@kristastevens  Thank you

> When you view your website, the block displays the content of the post or page that you have assigned.

I meant this as an explanation to why the text in this block is different depending on where you view the block. 🤔 

Maybe if we replace "the block" with "this block".

----


Welcome to WordPress!

This is a placeholder for your content.

In the WordPress editor, each paragraph, image, or video is presented as a distinct “block” of content. When you view your website, this block displays the content of the post or page that you have assigned.

Each block has controls for changing things like color, width, and alignment. These controls will show and hide automatically when you have a block selected.

Experience the flexibility that blocks bring, whether you are building your first site, or write code for a living. Start writing!

**Comment by kristastevens** [comment]
Makes perfect sense, @carolinan — _this_ looks good to me!
