### ISSUE TITLE
Custom rich text format type should be highlighted when active, but it isn't

### ISSUE THREAD

**Issue by davilera** [WordPress/gutenberg#40138]
### Description

Custom format types from the Rich Text package are not working properly. When a format is applied, it should be highlighted in the toolbar menu (and it sometimes isn't). Moreover, when it's not highlighted (and it should), it's not possible to remove the format (and it should).

### Step-by-step reproduction instructions

Register the following format type in the browser's JS console:

```js
wp.richText.registerFormatType( 'test/bold', {
  title: 'Bold Test',
  tagName: 'b',
  className: null,
  edit: ( { isActive, value, onChange } ) => wp.element.createElement(
    wp.blockEditor.RichTextToolbarButton,
    {
       icon: 'editor-bold',
       isActive,
       title: "Aaa Bold",
       onClick: () => onChange( wp.richText.toggleFormat( value, { type: 'test/bold' } ) ),
    },
    null
  ),
});
```

It should now be available under the "More block tools" menu:

<img width="468" alt="Screenshot 2022-04-07 at 12 01 34" src="https://user-images.githubusercontent.com/12100954/162174611-f766c679-371b-43a1-bf6d-c2da29b4927f.png">
 
If you apply this new format, the "More block tools" menu should be highlighted when the cursor is on a piece of text that uses said format. This works as expected at first:

<img width="468" alt="Screenshot 2022-04-07 at 12 03 52" src="https://user-images.githubusercontent.com/12100954/162175045-d7d0333a-30d5-4aab-b235-87dbf06f7cd6.png">

### Issue 1

Unfortunately, it doesn't after saving the post, refreshing the editor, and repeating the process:

<img width="468" alt="Screenshot 2022-04-07 at 12 04 43" src="https://user-images.githubusercontent.com/12100954/162175200-85011409-9f1c-4c40-b4ba-c908864d076f.png">

Apparently, entering and exiting the "Code Editor" seems to fix the issue... until, of course, Gutenberg is reloaded.

### Issue 2

I've also noticed that built-in format types are properly highlighted in the UI, both in the "More block tools" and the format type itself in the dropdown menu (in this case, the "Superscript" format):

<img width="511" alt="Screenshot 2022-04-07 at 12 12 39" src="https://user-images.githubusercontent.com/12100954/162176612-985d64be-5525-4324-8fd8-6c75c16edc8a.png">

but our custom format type isn't. When it works, it does so partially (as in, the "More block tools" is indeed highlighted, but the menu item itself isn't):

<img width="511" alt="Screenshot 2022-04-07 at 12 14 35" src="https://user-images.githubusercontent.com/12100954/162176951-52d89a1b-f95b-46ad-a5c1-caa8270363a6.png">

### Environment info

- WordPress 5.9.3
- With and without Gutenberg 12.9.0
- No other plugins
- Twenty Twenty-One 1.5
- Firefox and Chrome on both Windows and Linux

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by flmuel** [comment]
same here...

**Comment by t-hamano** [comment]
The `icon` prop of `RichTextToolbarButton` component can accept svg elements, dashicon names, etc.
For example, in the core format type, the button includes the icon as SVG since the icon is specified from the `@wordpress/icons` package:

```html
<button type="button" aria-checked="true" role="menuitemcheckbox" class="components-button components-dropdown-menu__menu-item is-active has-text has-icon">
  <svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false"> 
    <path d="..."></path>
  </svg>
  Inline code
</button>
```

The style as a drop-down icon and the active format style are then applied, as shown below.

![svg](https://user-images.githubusercontent.com/54422211/186378204-7e69df50-98ef-4bea-b4fe-c2242b94ecab.png)

On the other hand, if a dash icon name is specified, the button includes `span` tag with the class name as shown below:

```html
<button type="button" role="menuitem" class="components-button components-dropdown-menu__menu-item is-active has-text has-icon">
  <span class="dashicon dashicons dashicons-editor-bold"></span>
  Aaa Bold
</button>
```

There is no style applied to this span tag, so the active state is not shown and there is a text misalignment as reported in #29376:

![dashicon](https://user-images.githubusercontent.com/54422211/186378756-30cc6996-4201-45a2-b8e1-78d9c7994a30.png)

We can solve this problem by using SVG icons instead of Dashicon, but fundamentally, I think we should apply the same style to dashicon.
