### ISSUE TITLE
Get template path or name from pattern

### ISSUE THREAD

**Issue by illycz** [WordPress/gutenberg#40141]
### Description

How to get page template from registered pattern in block theme?

### Step-by-step reproduction instructions

1. I have template in template folder, which is selected for specific page.
2. I have pattern registered within `register_block_pattern()`.
3. `get_page_template()` return `...wp-includes/template-canvas.php`

Also get post ID is not possible inside pattern.

Thanks for any suggestions

### Environment info

WP 5.9.3
Gutenberg 12.9.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
Hi @illycz, to confirm, you are trying to get a specific page template from within a block pattern as well as the post id from within a block pattern. Is that correct?

**Comment by illycz** [comment]
Yes, I have header with light/dark logo so I make header as pattern where I can have a php logic.
But actually I don't know how to get template from this pattern.
I know that I can have two template parts for specific templates, but for switching only logo it looks unnecessarily complicated.

Thanks

**Comment by ndiego** [comment]
This issue was reviewed in today's Editor Bug Scrub. Patterns are intended to only include block markup. Any PHP should be for simple things like translating strings or providing direct paths to assets, like images, used within blocks included in the pattern. In theory, you could use PHP to swap out a logo, but there is no direct way to detect the template the pattern is in. Your use case is a bit more advanced than what Patterns were designed for. They are really just a wrapper for a predesigned collection of blocks. 

The easiest solution, as you indicated, is to have different template parts for each header you want to display. Alternatively, building this logo-switching functionality directly into a custom block would give you the most flexibility. While I know this is not the answer you were looking for, but hopefully it provides a bit more context to the issue.

**Comment by illycz** [comment]
Understand. Thanks
