### ISSUE TITLE
`appearanceTools`: make it work for all visual tools + remove block settings from core

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#40194]
In WordPress 5.9 we added a new setting `appearanceTools`, with the goal of controlling a number of visual tools at once.

This issue summarizes a few things we've heard about this behavior, to gather more thoughts and see if it's time to expand it.

## 1. It doesn't controll _all_ the visual tools

We didn't make it control [all](https://github.com/WordPress/gutenberg/pull/36246) the visual tools at the time. For context, these is the current status: the visual settings/tools that can be controlled via `theme.json`, their default values, and whether or not they're controlled via `appearanceTools`:

Visual setting/tool | Default | Controlled by appearanceTools
--- | --- | ---
border.color | `false` | 🟢
border.radius | `false` | 🟢
border.style | `false` | 🟢
border.width | `false` | 🟢
color.background | `true` | 🔴
color.custom | `true` | 🔴
customDuotone | `true` | 🔴
customGradients | `true` | 🔴
defaultDuotone | `true` | 🔴
defaultGradients | `true` | 🔴
defaultPalette | `true` | 🔴
color.link | `false` | 🟢
color.text | `true` | 🔴
spacing.blockGap | `null` | 🟢
spacing.margin | `false` | 🟢
spacing.padding | `false` | 🟢
typography.customFontSize | `true` | 🔴
typography.dropCap | `true` | 🔴
typography.fontStyle | `true` | 🔴
typography.fontWeight | `true` | 🔴
typography.letterSpacing | `true` | 🔴
typography.lineHeight | `false` | 🟢
typography.textDecoration | `true` | 🔴
typography.textTransform | `true` | 🔴

**What would happen if we made `appearanceTools` to control all the visual settings?**

- For those themes that want a "catch-all" mechanism to disable any UI, this would be ideal.
- For those that want to enable everything, this would be ideal.
- For those that want a fine-grainer control, they still could.

Note that expanding the visual tools affected by `appearanceTools` won't have any visual impact to users: the settings themes have would still be honored.

## 2. There're some block settings that aren't controlled by the global `appearanceTools` setting

Global settings work this way: they cascade from global to block. Example, if core defines a global `appearanceSetting: false` all the blocks inherit that behavior, unless they set something else explicitely.

We take advantage of this today for [some blocks](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/theme.json#L225) (button and pullquote) that had **pre-existing behaviour that we maintained for themes without `theme.json` support** when we introduced `appearanceTools`:

```json
{
  "settings": {
    "blocks": {
      "core/button": {
        "border": {
	  "radius": true
        }
      },
      "core/pullquote": {
        "border": {
          "color": true,
          "radius": true,
          "style": true,
          "width": true
        }
      }
    }
  }
}
```

This is one of the advantages of the system: those block are inheriting _all_ the settings from the global, except the ones they want to override. If a theme wouldn't want this behaviour they can do something else by provide a different value for the setting or just use `appearanceTools` at the block level:

```json
{
  "settings": {
    "blocks": {
      "core/button": { "appearanceTools": false },
      "core/pullquote": { "appearanceTools": false }
    }
  }
}
```

**What would happen if we removed these block settings and let the global setting control them?**

- If a theme has `appearanceTools: true` at the global level the user won't see any change (the tools will be enabled anyway by the cascade).
- If a theme doesn't use `appearanceTools` but had any this settings enabled at the global level (border.color, border.radius, border.style, border.width) the user won't see a change for the settings that were enabled.
- For any other theme, the button and pullquote won't show the border controls they had before.

The trade-off of removing the pre-existing button & pullquote settings is that themes without `theme.json` will see a behavior change the can't control unless their theme start using `theme.json`. [Edit](https://github.com/WordPress/gutenberg/issues/40194#issuecomment-1094702545): _we could add a specific fallback for these kind of themes for button & pullquote to maintain the existing behavior._

**Comment by mtias** [comment]
Another perspective here can be to allow themes / sites to disable the wp-includes version of theme.json entirely.

**Comment by oandregal** [comment]
> What would happen if we removed these block settings and let the global setting control them?
> For any other theme, the button and pullquote won't show the border controls they had before.

For themes without `theme.json` we could add a fallback [here](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/class-wp-theme-json-resolver-6-0.php#L101) for button and pullquote to maintain the existing behavior. So, for the majority of themes, there won't be any change.

**Comment by kraftner** [comment]
> > What would happen if we removed these block settings and let the global setting control them?
> > For any other theme, the button and pullquote won't show the border controls they had before.
> 
> For themes without `theme.json` we could add a fallback [here](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/class-wp-theme-json-resolver-6-0.php#L101) for button and pullquote to maintain the existing behavior. So, for the majority of themes, there won't be any change.

I think this would be the preferable approach since it would be problematic to only be able to control this in legacy themes by starting to use `theme.json` since that again will trigger some other unwanted side-effects like #33385.

**Comment by kraftner** [comment]
> Another perspective here can be to allow themes / sites to disable the wp-includes version of theme.json entirely.

I think this sounds attractive. Would this then also remove all the other settings like colors, gradients, font sizes, spacing units,…?

When I read `appearanceTools` I think of really absolutely everything that affects the appearance in any way, returning the block editor again to an actual *content* editor with no way to individually affect anything that goes beyond text and media.

So for example also removing any way to alter font size, including the defaults, by setting font sizes to an empty array.

---

Sidenote: The list of affected items above is missing `defaultDuotone`, maybe due to https://github.com/WordPress/wordpress-develop/commit/b5ad284a93821db78380610e7da77a9d99200e9d#diff-0a35f8ff88e18fde4294ab337d101751ba8777ff270dabb7d25d31627ff015f9R16

**Comment by oandregal** [comment]
> Sidenote: The list of affected items above is missing defaultDuotone, maybe due to https://github.com/WordPress/wordpress-develop/commit/b5ad284a93821db78380610e7da77a9d99200e9d#diff-0a35f8ff88e18fde4294ab337d101751ba8777ff270dabb7d25d31627ff015f9R16

Added `defaultDuotone` to the list.

**Comment by mtias** [comment]
That's how `appearanceTools = false` should work, but if there's a more granular addition that enables back some tools, those would supersede. Since WordPress ships with a default set, to achieve a completely blank slate on which all appearance tools are disabled there'd be a need for not loading the bundled theme.json at all. It might a case to supply that setting in wp-config.

**Comment by kraftner** [comment]
Since this is something that is urgently needed for a certain group of users, but admittedly not relevant for a standard user, I am not sure if adding a wp-config constant isn't a bit to prominent as well as limited since it will probably only allow a boolean switch.

What about having a filter to load another `theme.json` as the default set?

Maybe here ([here in core](https://github.com/WordPress/WordPress/blob/90cbd98c6bb448f56178fec68f57ab74d9e5bdf8/wp-includes/class-wp-theme-json-resolver.php#L137))

https://github.com/WordPress/gutenberg/blob/f3459925a7da90ec96ad46f6eef8e01d8d632978/lib/compat/wordpress-6.0/class-wp-theme-json-resolver-6-0.php#L48

This would also enable having something like a custom default for an organization that can be bundled into a plugin and then be reused independently from the actual theme used.

**Comment by mtias** [comment]
A filter that can also return `null` for the included theme.json could make sense.

**Comment by oandregal** [comment]
There's +2 years without progress on this ticket but there's a bunch of activity around block controls everywhere else. This ticket no longer seems relevant, so I'm closing it.
