### ISSUE TITLE
Block Gap gets flushed out for Group Block in Global Styles

### ISSUE THREAD

**Issue by ramizmanked** [WordPress/gutenberg#40206]
### Description

Value passed to Block Gap control flushing out for Group Block in Global styles on Save.

### Step-by-step reproduction instructions

1. Backend > Appearance > Editor.
2. Click on 'Styles' icon next to 'settings' on top right corner.
3. Go to 'Blocks'.
4. Select 'Group' block.
5. Select 'Layout'.
6. Try changing 'Block spacing' value.
7. Save.

### Screenshots, screen recording, code snippet

https://vimeo.com/697832273/694b8efd50

### Environment info

- **WordPress:** 5.9.3
- **Google Chrome:** 100.0.4896.75
- **System Configuration:** Mac with Apple Silicon running on macOs Monterey 12.3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
Hi @ramizmanked, thanks for reporting. I just tested this in WordPress 6.2 RC2 and was not able to replicate the issue. Setting block gap in Global Styles correctly applies the spacing globally, so I am guessing something was fixed in the last few months. If you continue to experience issues, please feel free to reopen this issue. Thanks!
