### ISSUE TITLE
Split block tools between "settings" and "appearance"

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#40204]
We've discussed this as far back as 5.0, but it was not yet the right time to explore. Now that we have tools more clearly delineated, it's a good time to start looking at how we can split the block inspector between settings and appearance — appearance would generally be all the common block tools registered through supports, and setting would generally be block specific tools. The earliest mockups we had used a tabbed interface for this. There are some other considerations to discuss, including attribute types and UI slots for registering controls. We should assume by default `<InspectorControls>` are of role "settings".

Mockup:

<img width="1600" alt="Tabbed inspector" src="https://user-images.githubusercontent.com/1204802/192754943-c98cf06f-8dad-4e7b-9663-6c5bd4b0c594.png">

See also: #42257, which could benefit from this.

**Comment by jasmussen** [comment]
Here are a couple of options:
<img width="1000" alt="options" src="https://user-images.githubusercontent.com/1204802/162750005-d7abd08a-064c-41eb-be0e-83bad660e94c.png">

In both of these, the tab style has been massaged, and "Settings" and "Appearance" are sub-tabs of the Block inspector. 

The right variant gives a little more prominence to the block description, and makes it a "card" — that helps anchor the settings below:
<img width="1600" alt="settings" src="https://user-images.githubusercontent.com/1204802/162750410-ff866873-5a77-4b53-84a5-3f3d0cd6feeb.png">

**Comment by jameskoster** [comment]
This looks like a great starting point to me, but there's something about the nested tabs that feel a bit awkward. Maybe it's just because the settings/appearance tabs seem 'heavier' than the post/block ones, and that's throwing the hierarchy off a bit?

Some more 'out there' ideas that are probably terrible, but I share just in case they inspire anything better:

### Settings only
Could we say the inspector only handles settings, and put access to the appearance panels in the toolbar?

<img width="1438" alt="Screenshot 2022-04-13 at 11 05 13" src="https://user-images.githubusercontent.com/846565/163155159-af5cc6aa-95ee-455d-9fb9-75dc528100c8.png">

This would reduce reliance on the Inspector which could be good, but the appearance panels would need to be movable which complicates things.

### Drilldowns
Remove the post/block tabs and utilise the drilldown pattern from global styles.

![inspector](https://user-images.githubusercontent.com/846565/163158267-b6dc21b4-5124-471c-8c4e-ed16717e7127.gif)

We might do the same thing in the block inspector – emphasise appearance options and put settings in a drilldown.

Figma prototype [here](https://www.figma.com/proto/eGoqmWIztNBcib1ukrFwki/Random-explorations?page-id=0%3A1&node-id=2%3A505&viewport=376%2C48%2C1.66&scaling=scale-down&starting-point-node-id=2%3A505).

### Split document / block settings into different UI regions
In the site editor, template details are accessed in the top bar, we might do the same thing in the post editor freeing up the Inspector to concentrate solely on blocks.

<img width="1595" alt="Screenshot 2022-04-13 at 11 32 31" src="https://user-images.githubusercontent.com/846565/163159636-4749a43b-c22c-4ec2-b63b-2f1a2844b2d1.png">

**Comment by ZebulanStanphill** [comment]
In my opinion, it has always felt inconsistent and confusing that all plugin sidebars are separate in the top toolbar, but the document settings and block inspector share a sidebar. So I'm all for splitting the document and block sidebars, though I'm not sure where to place the former.

Perhaps just have two buttons instead of the current single cog next to the Publish button? Or maybe the middle of the top toolbar is the place to put it after all (as seen in the prior comment's mockup); my main concern with that design is how it is not clear that the post title in the toolbar is the point to access the settings. I know there's been some accessibility concerns about various buttons lacking descriptive labels.

Back to the main point of this issue, I totally agree that we should split design options from more block-specific settings. Divi Builder does this, and it really helps with organizing the very large number of options in its modules.

**Comment by jameskoster** [comment]
> Or maybe the middle of the top toolbar is the place to put it after all

On balance I think this could be the way to go. There's a lot of context in https://github.com/WordPress/gutenberg/issues/27093, but in short:

* Displaying the title on the canvas can be confusing (it cannot be styled, doesn't always appear in the same location – or at all – on the frontend).
* We already do something similar for templates in the site editor / template editor.
* It's fairly common to see the filename top-center in edit apps, e.g. TextEdit:

<img width="698" alt="Screenshot 2022-05-10 at 10 36 27" src="https://user-images.githubusercontent.com/846565/167598500-e9fd8500-a5aa-4d70-a62b-65fec20e6c3e.png">

Plus it means we can eliminate the awkward nested tab situation that could arise when we close this issue.

Also related: https://github.com/WordPress/gutenberg/issues/39082

**Comment by shaunandrews** [comment]
Rather than having multiple, nested tabs, or a complex drill-down, perhaps a segmented control would work better:

<img width="775" alt="image" src="https://user-images.githubusercontent.com/191598/167650749-b9c31a4e-50bc-4ba6-b249-0b66d7a0dd55.png">

**Comment by jameskoster** [comment]
Yup that could work too. The only slight drawback is that we use the SegmentedControl elsewhere as a selection tool:

<img width="301" alt="Screenshot 2022-05-10 at 15 24 34" src="https://user-images.githubusercontent.com/846565/167651997-d76d9558-3d55-40ae-89c5-2f5ff940b9cd.png">

**Comment by SaxonF** [comment]
Tabs feel like the right pattern here but agree nesting looks weird. What about converting post/block tabs into breadcrumbs to better show the parent->child relationship, with "post" being the top level "block".

Could also play with typography treatment and input stroke colour to try and reduce competing elements.

![image](https://user-images.githubusercontent.com/1072756/167750314-13338915-5653-4286-9388-65bb3d99f7db.png)

Dark mode
![image](https://user-images.githubusercontent.com/1072756/167768444-9fa3e0a6-cb5e-4840-aaf1-4a4fadc37623.png)

**Comment by jameskoster** [comment]
At a glance the breadcrumb pattern looks great, but I worry about the scalability. In the template editing context you'll mostly be seeing `Template / ... / Selected block` which reduces the value quite a bit. 

I do appreciate how much lighter the interface appears when you reduce the stroke on active tabs, and use icons instead of full labels.

**Comment by SaxonF** [comment]
I don't like this as I don't think its visible enough but worth dropping here in case it inspires other approaches

![image](https://user-images.githubusercontent.com/1072756/167838041-5bc39c6c-029d-4f38-b4b3-29908f9670b3.png)

**Comment by jasmussen** [comment]
For folks subscribed to this ticket, I added a mockup to the main issue with a baseline tab interface that we can build. Whether that needs to evolve into a segmented control or otherwise, this can be explored separately.

**Comment by aaronrobertshaw** [comment]
Thanks for adding the mockup.

I'd like to take this one on, as it touches on some areas I've had a little experience in Gutenberg. Namely, block supports and our `InspectorControls` slots. Happy to collab with others as well 🙂

**Comment by mtias** [comment]
I think this might take a few iterations to get right, so we should consider enabling it as a feature flag until we square all the dependencies (UI, block API, extensibility, etc).

**Comment by mtias** [comment]
@jameskoster @SaxonF can we try a design that includes the three tabs (list, settings, styles) but uses the icons?

**Comment by jameskoster** [comment]
Purely using our existing components:

<img width="382" alt="Screenshot 2022-10-12 at 14 24 09" src="https://user-images.githubusercontent.com/846565/195354534-10d7c89a-71c0-441a-b4b1-248dcea3eaef.png">

There's some tension between the block icon and the tabs, which would be solved by simply removing it. 

<img width="347" alt="Screenshot 2022-10-12 at 14 28 16" src="https://user-images.githubusercontent.com/846565/195355419-26f6d4ed-31af-428d-8036-47659507fef8.png">

The icon to use for settings is also a bit contentious. The one above is used for "custom" elsewhere so doesn't feel like a perfect fit. The cog feels more natural, but obviously we use that to toggle the Inspector itself so it might be a bit awkward.

**Comment by mtias** [comment]
I think we should try using the panel icon instead of the top level cog, and use the cog for the settings tab.

<img width="820" alt="image" src="https://user-images.githubusercontent.com/548849/195368723-e1e062f1-3340-4dcf-88ed-47654c962fbb.png">

**Comment by jameskoster** [comment]
Yup, that could work.

<img width="363" alt="Screenshot 2022-10-12 at 17 25 28" src="https://user-images.githubusercontent.com/846565/195397299-4bb68569-be68-4138-8608-b098f2dfff86.png">

**Comment by jasmussen** [comment]
Perhaps nitpick territory — should the sidebar icon be flipped horizontally?

**Comment by jameskoster** [comment]
Yup, we should probably have both versions of the icon so the button can flip based on locale (rtl/ltr).

There may be other applications where we need the inverse as well such as https://github.com/WordPress/gutenberg/issues/28745.

**Comment by aaronrobertshaw** [comment]
Can someone point me in the direction of the [panel icon](https://github.com/WordPress/gutenberg/issues/40204#issuecomment-1276264434) via a figma link or supply the SVG etc so I might add it to the icons package?

**Comment by jasmussen** [comment]
Sure, here's drawer-right:

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" style="enable-background:new 0 0 24 24" xml:space="preserve"><path d="M18 4H6c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm-4 14.5H6c-.3 0-.5-.2-.5-.5V6c0-.3.2-.5.5-.5h8v13zm4.5-.5c0 .3-.2.5-.5.5h-2.5v-13H18c.3 0 .5.2.5.5v12z" style="fill-rule:evenodd;clip-rule:evenodd;fill:#1e1e1e"/></svg>
```

drawer-left:

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" style="enable-background:new 0 0 24 24" xml:space="preserve"><path d="M18 4H6c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zM8.5 18.5H6c-.3 0-.5-.2-.5-.5V6c0-.3.2-.5.5-.5h2.5v13zm10-.5c0 .3-.2.5-.5.5h-8v-13h8c.3 0 .5.2.5.5v12z" style="fill-rule:evenodd;clip-rule:evenodd;fill:#1e1e1e"/></svg>
```
<img width="132" alt="Screenshot 2022-10-14 at 09 56 25" src="https://user-images.githubusercontent.com/1204802/195793610-2687d945-1b51-443a-a9cd-f917ab26c134.png">

**Comment by jameskoster** [comment]
Remember to remove the `fill:#1e1e1e` part 😁

**Comment by aaronrobertshaw** [comment]
Proof of concept PR is up in https://github.com/WordPress/gutenberg/pull/45005.
