### ISSUE TITLE
[Block] Transform from Post Comments block (depricated) -> Comments Query Loop block

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#40223]
## What problem does this address?

It would be helpful to make it easier to transform between between Post Comments block <-> Comments Query Loop block.

## What is your proposed solution?

Add the transform here:
![Screenshot 2022-04-11 at 13 21 45](https://user-images.githubusercontent.com/5323259/162729591-7c629b96-8902-454e-8325-a77be0c9b083.jpg)

**Comment by ockham** [comment]
Hey @paaljoachim, we've considered adding a transform from Post Comments to Comments Query Loop. However, since it would be somewhat complex to implement, we didn't want to make it a blocker that would prevent us from including the new Comments blocks with WP 6.0. Instead, we've opted to deprecate the Post Comments block for now (also hiding it from the inserter).

Furthermore, there's a bit of precedent of blocks like these co-existing, without necessarily adding a transform: IIUC, we still provide the "Latest Posts" block and haven't yet added a transform to transform it into a Posts Query Loop. (Not saying that it's ideal, just that there's precedent.)

I think that we're still considering adding a transform from Post Comments to Comments Query Loop in the long run (but not in time for WP 6.0). I'll defer to @SantosGuillamot who might have a more definitive answer 😄

**Comment by paaljoachim** [comment]
Thanks for the comment @ockham Bernie!

**Comment by ockham** [comment]
We've now merged (#41807) the legacy Post Comments block into the new Comments block (formerly known as Comments Query Loop). This includes a button to transform the "legacy" version of the block (i.e. Post Comments) into the new version (Comments).

This is pretty similar in spirit to what this issue was requesting, so I think we can close it 🙂

**Comment by paaljoachim** [comment]
Great! Thank you!
