### ISSUE TITLE
Categories block limits preview to 10 categories

### ISSUE THREAD

**Issue by bradyvercher** [WordPress/gutenberg#4022]
## Issue Overview

On a site with 68 categories, only 10 show up in the Categories block preview in the editor.

## Steps to Reproduce (for bugs)

1. Add more than 10 categories and make sure they're assigned to posts.
2. Insert a Categories block

## Expected Behavior

I expected the preview to match the output on the frontend, where all the categories are displayed.

### Editor Preview
<img width="702" alt="screen shot 2017-12-14 at 4 36 51 pm" src="https://user-images.githubusercontent.com/1302030/34021151-1b6bfdc8-e0ed-11e7-8ce1-3da659c9d688.png">

### Frontend View
<img width="248" alt="screen shot 2017-12-14 at 4 37 13 pm" src="https://user-images.githubusercontent.com/1302030/34021154-2067fab6-e0ed-11e7-9a7a-00b4c45ff11b.png">

### Categories Request
<img width="785" alt="screen shot 2017-12-14 at 4 39 55 pm" src="https://user-images.githubusercontent.com/1302030/34021245-88b6fe78-e0ed-11e7-86b4-38063823c41a.png">

**Comment by noisysocks** [comment]
We can't list _all_ categories in the editor since [the API has a hard limit of 100](https://developer.wordpress.org/rest-api/using-the-rest-api/pagination/#pagination-parameters).

I think setting a higher limit (e.g. 50) and having the UI indicate that not all categories are being shown (e.g. by fading out) would be a good compromise between being fully WYSIWYG and performant.

**Comment by danielbachhuber** [comment]
Related #4623, #4632, #4622

**Comment by westonruter** [comment]
One alternative would be to use the`ServerSideRender` proposed in #780.
