### ISSUE TITLE
Additional CSS class field appears above block-specific controls in Category block Inspector

### ISSUE THREAD

**Issue by bradyvercher** [WordPress/gutenberg#4023]
## Issue Overview

When inserting a Categories block, the "Additional CSS Class" field appears above the block-specific controls in the Inspector. After deselecting the block and reselecting it, the field renders below the other block controls.

## Steps to Reproduce (for bugs)

1. Insert a Categories block
2. View the order of the controls in the Inspector

## Expected Behavior

I expected the "Additional CSS Class" field to appear at the bottom of the Inspector like it does in other blocks.

## Screenshots / Video

<img width="281" alt="screen shot 2017-12-14 at 4 45 03 pm" src="https://user-images.githubusercontent.com/1302030/34021418-a1cd5bc2-e0ee-11e7-8c1c-e0af083b00be.png">

**Comment by Soean** [comment]
@bradyvercher I can't reproduce the bug anymore, can you re-test with the latest master?

**Comment by bradyvercher** [comment]
Yep, I just tested again in Chrome, Safari, and Firefox and it still occurs for me.

**Comment by mtias** [comment]
I was able to replicate briefly, though it becomes fixed after some interactions (like selecting other blocks) and then doesn't reoccur. @aduth maybe it rings a bell for you since you improved how the slot for inspector controls handled ordering.

**Comment by aduth** [comment]
I'm fairly certain this has to do with `key` reconciliation with slotted content.

https://reactjs.org/docs/lists-and-keys.html#keys

In other words, we expect a particular mount order to reflect the intended display order of sidebar items, but in some unknown cases the elements become reconciled and the display order shifts.

I can fairly reliably reproduce this, but only when:

- Inserting a Categories block from a new post
- Starting on the "Document" sidebar tab and then shifting to "Block" only after the Categories block is inserted

We might need some more robust mechanism for defining the expected order of items within a slot.

There's certainly some precedent to draw from (page `menu_order`, [hooks `priority`](https://developer.wordpress.org/reference/functions/add_filter/), [menu page `$position`](https://developer.wordpress.org/reference/functions/add_menu_page/)).

**Comment by jorgefilipecosta** [comment]
It looks like the bug happens because we are not showing inspector controls to change configs while loading the categories from the rest API. The PR solves this problem https://github.com/WordPress/gutenberg/pull/4266 and makes this block more in line with other blocks e.g: latest posts.
As when loading we don't show inspector controls the class input is the only input being added and is added in the first position. We then load categories and add the other inputs. Given that the class input is already there other inputs are added below it. If we change to other block and come back everything is redrawn and is in the right position.
I think this happens only when adding a new post because for other inserts of the category block our withAPIData HoC returns the request it already has "cached".
