### ISSUE TITLE
Image block image size option is not working properly in large and full width.

### ISSUE THREAD

**Issue by NidhiDhandhukiya74** [WordPress/gutenberg#40353]
### Description

When we choose image block and when we update that image size from large to full width it is not showing any effect ,in image dimention tab we can able to do changes in width and hight value but we can not able to see any changes in actual image width and hight.

### Step-by-step reproduction instructions

1. Update to WordPress 6.0 Beta 1 and Activate Gutenberg 13.0.0, Twenty Twenty two theme.
2. Appearance > Editor (beta)
3. Select Image block.
4. choose any image and then change it size to medium.
5. The image looks little small now change image size to large.
6. The image looks little bigger now choose the full size option in to the image size.
7. It will not make any differences if we are changing it into the full size from large and if we again make it large then also no changes should be reflected.
Note:- the change in to the width and hight we can able to see into the image dimension width and hight input box but it is not reflected onto the image.

### Screenshots, screen recording, code snippet

I have attached video recording link for better understanding.
https://www.loom.com/share/d6f49435856a4b3d882aa8ef213796d2

### Environment info

WordPress 6.0 Beta 1, Gutenberg 13.0.0 and Twenty Twenty two theme.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
Hi @NidhiDhandhukiya74, thank you for opening this issue. The image size control allows you to change the image source dimensions. The reason why there is no visual difference between "Large" and "Full Size", is because the Image block itself is constrained by the content width of the page. Both the "Large" and "Full Size" sizes are larger than the content width, so they appear the same. Hopefully, that makes sense, please let me know if I can provide any further assistance.

**Comment by NidhiDhandhukiya74** [comment]
Hello @ndiego ,
Thanks for the answer and thanks for clarifying my problem.
