### ISSUE TITLE
Post Excerpt Block: settings duplicated when selecting between different post excerpts in a Query Loop

### ISSUE THREAD

**Issue by NidhiDhandhukiya74** [WordPress/gutenberg#40358]
### Description

In Query Loop block when you choose post excerpt and if you have multiple post so in different post when you click on that post excerpt it will add multiple settings in inspector control.

### Step-by-step reproduction instructions

1. Select Query Loop block.
2. Click on the button start blank.
3. Choose  **Title, Date, & Excerpt**
4. now from query loop choose post expert of any one post.
5. Then choose post expert from another post.
6. So each and every click will add a new setting in inspector control (Right side in settings of that block)
7. and amongst that all setting only one is working other is not useful.

### Screenshots, screen recording, code snippet

https://www.loom.com/share/34f6469686e0405cb13301e2819349b7

### Environment info

WordPress 6.0 Beta 1, Gutenberg 13.0.0 and Twenty Twenty two theme.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
I am able to replicate this. I believe we need to tackle for 6.0 and have added it to the board.

**Comment by annezazu** [comment]
Updated the title to make this a bit clearer and have included a screenshot below of how the settings duplicate/double when selecting between post excerpt options:

<img width="1425" alt="Screen Shot 2022-04-18 at 4 29 47 PM" src="https://user-images.githubusercontent.com/26996883/163892721-22721548-3e55-4a8e-ae0a-845479479c59.png">

**Comment by aaronrobertshaw** [comment]
I've done some digging into this. 

To reliably replicate the bug, I needed to not only select the Post Excerpt but also click into the "read more" link within it, then select a new Post Excerpt. I believe this is where recent partial block selection updates might be causing a problem.

Git bisect appears to indicate the bug was introduced via [#38892](https://github.com/WordPress/gutenberg/pull/38892). 

<details>
<summary><strong>Demo - Before #38892</strong></summary>

Commit: 5a71300729

https://user-images.githubusercontent.com/60436221/163950925-5aeef37e-ff0e-4b95-9a36-117bfc153d43.mp4
</details>


<details>
<summary><strong>Demo - After #38892</strong></summary>

Commit: 721e3c4d3c

https://user-images.githubusercontent.com/60436221/163950893-7296b9cd-87b0-4191-85cd-101c53781d1b.mp4
</details>

There were similar issues hit when attempting to add a click handler for switching between selected blocks when clicking on a block preview in [#37519](https://github.com/WordPress/gutenberg/pull/37519). 

@ellatrix would you have any insights or thoughts on this issue? 🙏 

I'm out of time today but will try and pick this up again in the next couple of days.

**Comment by annezazu** [comment]
@mcsf tagging you in since I know Ella is out for a bit :)
