### ISSUE TITLE
[Fonts API] Allow enqueueing of font face with a chosen weight within range

### ISSUE THREAD

**Issue by zaguiini** [WordPress/gutenberg#40367]
## What problem does this address?

Since weights can be a range, it would make sense for any weight within the range of the registered font face to be enqueued.

For example:

```php
wp_register_webfont(
	array(
		'font-family'  => 'Source Serif Pro',
		'font-style'   => 'normal',
		'font-stretch' => 'normal',
		'font-weight'  => '200 900',
		'src'          => get_theme_file_uri( '/assets/fonts/SourceSerif4Variable-Roman.ttf.woff2' ),
	)
);
```

Font weight range from 200 to 900 gets registered. But right now, if you try passing a font weight within this range, you get an error:

```
The "Source Serif Pro:400:normal" font face is not registered.
```

## What is your proposed solution?

Passing a font weight within the range (200 to 900) should enqueue that registered face.

In `theme.json`:

```json
"fontFamilies": [
	{
		"fontFamily": "Source Serif Pro",
		"name": "Source Serif Pro",
		"slug": "source-serif-pro",
		"fontFaces": [
			{
				"fontFamily": "Source Serif Pro",
				"fontWeight": "400",
				"fontStyle": "normal"
			}
		]
	}
]
```

**Comment by hellofromtonya** [comment]
Update:

This issue is no longer valid for the Fonts API once the Font Library is merged.

Why?

As shared in Ongoing Roadmap update https://github.com/WordPress/gutenberg/issues/41479#issuecomment-1597915077, the Fonts API will no publicly expose the means to "register" or "enqueue" fonts. The [Font Library](https://github.com/WordPress/gutenberg/pull/50927) and [font management](https://github.com/WordPress/gutenberg/issues/45271) will handle the user workflow.

The Fonts API will get / pull the font variations from Theme JSON merged data that need their `@font-face` generated and printed.

Thank you everyone for your contributions!
