### ISSUE TITLE
settings.color.duotone = null does not validate against theme.json schema

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#40383]
### Description

After reviewing a number of issues including #31764, #33295, #35931, and #38299, I believe that the following two `theme.json` values are required to fully disable the custom duotone feature:

1. `settings.color.duotone`: `null` removes the SVG filters output in the body field. Setting this property to an empty array (`[]`) does not work.
2. `settings.color.customDuotone`: removes the UI toolbar control in combination with the first change

However, when I try to validate my `theme.json`, there is an error for `settings.color.duotone`: `null`:

> None is not a type of 'array'

Prior to WordPress 5.9.3, the null value also seemed to cause a PHP error, but I believe [that has been resolved](https://core.trac.wordpress.org/ticket/55241).

So first: **Is this the correct way to fully disable duotone support with `theme.json`**.

If so:

1. The schema needs to be updated to allow `null` for `settings.color.duotone` -OR- using `[]` as the value for that setting should prevent the SVG filters from being output
2. The official way to remove duotone should be documented

### Step-by-step reproduction instructions

Validate the following `theme.json` file:

```json
{
	"$schema": "https://schemas.wp.org/trunk/theme.json",
	"version": 2,
	"settings": {
		"color": {
			"duotone": null,
			"customDuotone": false
		}
	}
}
```

### Environment info

WordPress 5.9.3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by Humanify-nl** [comment]
I have encountered the same problem.

The output of SVG duotones in head also is affected by this. Passing an empty array to disable duotone will still generate them. Null generates error. 

I had to resort to using the php function to remove these.
`remove_action( 'wp_body_open', 'wp_global_styles_render_svg_filters' );`

**Comment by ajlende** [comment]
> Is this the correct way to fully disable duotone support with theme.json.

This is the correct way to disable duotone filters

```jsonc
// theme.json
{
	"settings": {
		"color": {
			// This clears the duotone palette for the theme
			"duotone": [],
			// This removes the default duotone filters from the UI
			"defaultDuotone": false,
			// This disables the ability to set a custom duotone filter
			"customDuotone": false
		}
	}
}
```

Using all three options for `colors` and `gradients` in the same way will disable those features, respectively.

Even after all of that, there will still be the SVGs for the default filters output at the beginning of the `body`. Default colors, gradients, filters, etc. are always output to support block patterns which may use these default swatches. If you aren't worried about that, you can disable just the SVG generation by removing some filters.

```php
// Removes generation from core
remove_action( 'wp_body_open', 'wp_global_styles_render_svg_filters' );
// Removes generation from the gutenberg plugin
remove_action( 'wp_body_open', 'gutenberg_global_styles_render_svg_filters' );
```

Finally, `null` is an invalid option for `duotone`, `colors` and `gradients`, so the theme.json schema is correct. If setting `duotone` to `null` was disabling something more, it is unintended behavior and may change in the future.

Hopefully that clarifies things. Keep an eye on https://github.com/WordPress/gutenberg/issues/38299 for changes to the SVG generation for default filters. I'd like a better solution for block patterns rather than always including all of the defaults, and that issue is where updates on that problem will be posted.

**Comment by mrwweb** [comment]
Thanks for this very good answer, @ajlende. I can confirm that even in WP 6.1, the `null` behavior still works, but I can switch to the PHP filter from now on. Appreciate you providing the reasoning behind that as well.
