### ISSUE TITLE
Cutting and pasting the title text results in full-screen overlay

### ISSUE THREAD

**Issue by noahtallen** [WordPress/gutenberg#40395]
### Description

When cutting (cmd/ctrl-x) text out of the Title area, and then pasting (cmd/ctx-v) that same text back in, a full-screen overlay is shown with the pasted text highlighted in the top-left.

### Step-by-step reproduction instructions

1. On current Gutenberg trunk, go to http://localhost:8888/wp-admin/post.php
2. Type some text into the title
3. Select some text, and use `cmd-x` (or `ctrl-x`) to cut the selection.
4. Move your cursor elsewhere in the title
5. Use `cmd-v` (or `ctrl-v`) to paste back into the title.
6. Observe the issue

### Screenshots, screen recording, code snippet

When the selection disappears, it's because I used `cmd-x` to cut it. `cmd-v` then triggers the bug.

https://user-images.githubusercontent.com/6265975/163632526-de3e3938-f5e3-4302-b38e-a2824a31199e.mov

### Environment info

- Current Gutenberg trunk in wp-env
- Firefox 99
- macOS 12.3.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I was only able reproduce the issue in Firefox.

**Comment by NidhiDhandhukiya74** [comment]
Hello @noahtallen yes i was also able to reproduce this issue in Firefox,
And noticed one another thing that in firefox when you cut and paste in title it will add one another div for that paste text between our actual content that's why this issue is happen.
In chrome the stucture remains same when we cut and paste the text in title so that's why this issue is only happen in firefox.

**Comment by Mamaduka** [comment]
I can no longer reproduce the issue running the current Gutenberg plugin trunk and 14.0.

I believe it was fixed via #42321.
