### ISSUE TITLE
Suggested improvements to reusable block flow

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#4041]
It's worth noting that these mocks do not include #3810 and the potential name change as that is still being worked through.

Currently the flow of reusable blocks is this:

![resuaable1](https://user-images.githubusercontent.com/253067/34050280-3fc3aa02-e1b2-11e7-8ac8-0872020f86ea.png)

I want to suggest we change a few things to give this as the flow:

![reusable2](https://user-images.githubusercontent.com/253067/34050308-50088fc2-e1b2-11e7-9a9a-100db07e8492.png)

The biggest change is that 'Edit | Detached' are no longer together. We give an option to detach anyway and by moving everything to the ellipsis we can have a new section. Here you can delete and detach. This helps avoid misclicking with 2 very different actions being beside each other.

I also changed 'Edit' to say what it does. This is a little improvement on clarity. We could reduce the text there to say 'Edit name', I am open to suggestion there.

The 'save / cancel' being beside each other I'm still not totally sold on, but it's a trap pattern we have in WordPress and for now leaving that.

As this includes the deletion, it ties in with #3792 also.

**Comment by afercia** [comment]
> I also changed 'Edit' to say what it does.

While I'm all for control labels that are as explicit as possible, seems to me the Edit button makes the whole block editable, not only its name. Currently, to edit the content of a reusable block users have to click Edit.

One more thing: maybe the first "Delete" should be "Remove"?

![34050308-50088fc2-e1b2-11e7-9a9a-100db07e8492](https://user-images.githubusercontent.com/1682452/34105677-925a164e-e3f5-11e7-9193-cc6d186d6e96.png)

This is visible also in the current menu, where "Delete" doesn't really delete the reusable block: it just removes it from the post and the saved `wp_block` post type is still saved in the database.

**Comment by jasmussen** [comment]
Intellectually I like moving "Detach" to the ellipsis menu, not only because it's a _slightly "destructive" action_, but because then there's more room for a label. But I'm also not over the moon convinced that it's a good change. The toolbar that pops out at the bottom seems like a great place to surface actions that are contextual to the reusable block, and another way to make the detach action less destructive would be to make a JavaScript confirm dialog, which could also in descriptive text describe what detaching really means.

Adding Delete Reusable Block to the ellipsis menu, I kind of feel the same about. It's good to put it in the advanced settings because it's destructive. But at the same time it feels like we are optimizing for the current interface, where I think we should presume that there is a separate "Manage Reusable Blocks" page somewhere in the future, for example under the Presentation menu item?

But all that said, this feedback isn't helping what we have _today_, and I completely acknowledge that _a future interface_ can easily become a resting pillow for not doing anything. As such, I do think adding the delete in the ellipsis menu is a good change for now, especially if combined with a JavaScript prompt. Though I'd echo Andrea's feedback, if we use the delete phrase for the reusable block, we should use "Remove" for the block thing.

**Comment by noisysocks** [comment]
Thanks @karmatosed! I'll implement this as part of https://github.com/WordPress/gutenberg/pull/4031.
