### ISSUE TITLE
Modifying Tags 

### ISSUE THREAD

**Issue by Khaos22** [WordPress/gutenberg#40492]
## What problem does this address?
When I make a post on my blog there is a tag section where I add tags to the post. Below that section there is a section called most used tags. 

## What is your proposed solution? 
I would like to modify the most used tags or create something like a bulk tags used often. So I don't have to type every tags each time.

**Comment by talldan** [comment]
@Khaos22 Would you be able to update the description and add as much information as possible (including screenshots).

It's a little difficult to read at the moment.

**Comment by Khaos22** [comment]
![image](https://user-images.githubusercontent.com/104107010/164454862-1396e831-4e9e-4e33-aa91-8ce60651309d.png)

I have attached a screenshot of the most used tags box. It is right below the add new tag box.

**Comment by talldan** [comment]
@Khaos22 Could you edit the original description to improve it. At the moment all the text is in the headers.

It could also do with more information, like how a user gets to the Most Used tags UI that you're describing.

Here's a guide that will help you understand how to use markdown formatting in github issues - https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax.

**Comment by Khaos22** [comment]
I updated that post.

**Comment by Khaos22** [comment]
I'm not understanding what else I can do to better explain it. I sent screenshots and change the wording.

**Comment by adamwoodnz** [comment]
Thanks @Khaos22 I can see the most used tags list on posts I create. You can click each of the most used tags to add them to your post so that you don't have to type them. I believe that's the main reason to have them displayed there, and should be pretty fast.

As for bulk applying tags the easiest way might be to have a string saved somewhere with all your tags comma separated ready to paste into the box, eg. `queeniesblog, queenies blog, tmz, blogger`. You can also bulk edit posts to add a tag list like this to many posts at a time.

If you want something smarter than that maybe there is a community plugin for managing tags but I haven't been able to find anything like that. You might also try posting in the [forums](https://wordpress.org/support/welcome/) for further help from the community.

**Comment by Khaos22** [comment]
Is there anyway I can change any of the most used tags?

**Comment by adamwoodnz** [comment]
No, they are dynamic by design. Sounds like you want a 'favorite tags' list.

**Comment by Khaos22** [comment]
Is there a way to get a favorite tags list?

**Comment by adamwoodnz** [comment]
Not out of the box, it would need a plugin.

**Comment by Khaos22** [comment]
Ok thank you
