### ISSUE TITLE
All blocks files loading every time that a block is previewed

### ISSUE THREAD

**Issue by larodiel** [WordPress/gutenberg#40525]
### Description

I've started to use gutenberg, but after insert a few blocks on it it gets really slow.
When I was digging to discover what was happening I found out that all **css files are requested every time that we click on a block** and it slowdown the editor a lot.
I've tried to find a solution but I couldn't as its request are made by the react on wp core.

### Step-by-step reproduction instructions

1. Go to the block editor
2. add a few blocks
3. it gets really slow ever time that a block is clicked because we need to wait the request get ready.

### TL;TD
Gutenberg loads all CSS files again once clicked on a block, making a lot of extra request to the server causing slowing down.

### Screenshots, screen recording, code snippet

 ![Network files requests](https://larods.com.br/screenshots/styles-files-requests.png)

### Environment info

- WP 5.9.3
- [Brave Version 1.37.116 Chromium: 100.0.4896.127 (Official Build) (x86_64)](https://brave.com/latest/)
- Desktop (Mac)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by colorful-tones** [comment]
I tested and was able to replicate this with the following scenario:
- OS: macOS Monteray 12.3.1
- Hardware: MacBook Pro 2020 / Processor: 1.7 GHz Quad-Core Intel Core i7
- Brave Version 1.37.116 Chromium: 100.0.4896.127 (Official Build) (x86_64)
- WordPress 5.9.3, TwentyTwentyTwo 1.1

Every time I added a core block the stylesheets were called again. This did not have perceivable impact on the editor's performance, and merely additional overhead in calling stylesheet each time.

<img width="1680" alt="Screen Shot 2022-04-26 at 11 06 53 AM" src="https://user-images.githubusercontent.com/405912/165333008-90d39d2c-1d15-4718-8adc-b54ac06616c6.png">

**Comment by ndiego** [comment]
I am able to confirm as well in both Chrome and Brave. See the video below. While likely the expected behavior, is this ideal? I am sure this is due to the block previews that are rendering. It is worthwhile to note that this also happens in WordPress 5.9.3.

https://user-images.githubusercontent.com/4832319/165421588-fdf1f526-5f4b-4576-9aee-a4182b88bdb0.mp4

**Comment by Mamaduka** [comment]
Thanks for testing.

@ndiego, I think we should update the issue title/description. The bug is caused by block previews and not by the Inserter.

**Comment by ndiego** [comment]
This is an issue that needs technical feedback and perhaps a reworking of how block previews are managed. At this point in the release process for 6.0, I do not believe we will be able to get a reliable fix implemented in time for 6.0. I am going to remove it from the 6.0 Project Board, but this issue should still be picked up for future versions of Gutenberg and perhaps even a Core minor release. Thanks again for reporting @larodiel!

**Comment by ellatrix** [comment]
Yes, this is caused by the displaying the preview, not by adding the block. The preview loads a separate iframe, which loads the assets, but these assets are normally cached by the browser, unless you "Disable Cache" in the developer tools. So this is nothing to worry about, it shouldn't slow down your site or the editor! :) Even if the the assets are somehow not cached, it's not blocking interaction so it should be fine.

<img width="995" alt="image" src="https://github.com/WordPress/gutenberg/assets/4710635/c7cbbcb9-1d8d-41d7-b873-165542567ee2">
