### ISSUE TITLE
Disable the dropdown for "default style" in block style panel when new styles are registered 

### ISSUE THREAD

**Issue by EdithAllison** [WordPress/gutenberg#40537]
## What problem does this address?
I don't want auhors to be able to set a style default. The default should be set in the code for the site; and authors should only be able to over-ride on a per block basis. This is to protect the site design and to avoid accidental changing of defaults by inexperienced users. 

### Description of my use case 

I've registered two custom block styles via register_block_style() one of which is set as default. But I'm still seeing a "default style" dropdown in the style panel. I'm unsure how this actually works (is this the default per page, per user or gobal) but in any case I want to remove it as I don't want authors on the site to be able to set a new default but I can't see any info how to do this. 

<img width="303" alt="block_styles" src="https://user-images.githubusercontent.com/19706428/164675837-2c977d67-8822-45bc-ac65-1c8990f8ee82.png">

```
        register_block_style(
		'core/heading',
		array(
			'name'         => 'source-serif-pro',
			'label'        => __( 'Source Serif Pro', 'storefront' ),
			'style_handle' => 'gutenberg',
		)
	);
	register_block_style(
		'core/heading',
		array(
			'name'         => 'lato',
			'label'        => __( 'Lato', 'storefront' ),
			'is_default'   => true,
			'style_handle' => 'gutenberg',
		)
	);
```

My concern is that an author will change the default and then other authors won't notice & start using it which could wreck the design of the site.

**Comment by ndiego** [comment]
Hi @EdithAllison, this functionality appears to have been removed in the latest version of Gutenberg and is also removed in WordPress 6.0 Beta 2. So when WordPress 6.0 comes out officially in May, users will not longer be able to set a default style, which should resolve this issue for you. If you want to test out the new block styles UI, you can activate the Gutenberg plugin on your site. 

Since this issue will be resolved in 6.0, and is currently resolved in the Gutenberg plugin, I am going to close this out. Please let me know if I can provide further assistance.
