### ISSUE TITLE
Block styles affect the message inside the Warning component

### ISSUE THREAD

**Issue by luisherranz** [WordPress/gutenberg#40536]
### Description

I expect that UI warning messages (created using the `<Warning>` component) are not affected by the block styles (Block Supports and Global Styles).

### Step-by-step reproduction instructions

1. Add a block that contains a warning. For example, the current version of Post Comments: `<!-- wp:post-comments /-->`
2. Change the typography of the block.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/3305402/164646485-9e3224de-a57e-44fa-b6b0-8ede5239d47b.mov

### Environment info

- WordPress 5.9, Gutenberg 13 RC1, TwentyTwentyTwo
- Chrome 100
- macOS 12.3.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ockham** [comment]
We now have two alternative PRs to fix this issue:

1. @DAreRodz' PR (#40847) tackles the problem at the level of the individual styles that can be modified from the Block Inspector. Folks have voiced the concern that if additional style options are added, we’ll also have to add overrides for those (i.e. requiring maintenance).
2. @michalczaplinski's draft PR (#40868) uses the Shadow DOM to encapsulate that Warning component’s styling; the big question here if GB folks will be open to introduce that for that purpose. Also, it increases the PR surface, which might make it less likely to get backported for 6.0

I just had another idea (and will likely add a third PR to the mix):

Both this issue and #40826 originate from the fact that the Warning is displayed ["inside"](https://github.com/WordPress/gutenberg/blob/b53edba02f2fa4bf08988b0bdf3db7faad44126d/packages/block-library/src/post-comments/edit.js#L105) of the block.

But there’s precedent for Warnings that are displayed outside (such as Invalid Block markup), and they don’t suffer from those issues. So I'd like to try that; I think there's hook for that.

**Comment by michalczaplinski** [comment]
I've investigated a little bit and here's the summary of my findings (this is in addition to what Bernie mentions [above](https://github.com/WordPress/gutenberg/issues/40536#issuecomment-1119516263))

1. The third approach that Bernie tried in https://github.com/WordPress/gutenberg/pull/40898 I think would also suffer from the problem of style leaking if there is another parent block (e.g. Group) that can change styling via Block Supports

   https://user-images.githubusercontent.com/5417266/167230402-789a6095-949b-4fb4-ab9c-abfc886a9127.mp4

2. Shadow DOM isolates and encapsulates the CSS is not the whole story and there are some exceptions that affect us. [This](https://open-wc.org/guides/knowledge/styling/styles-piercing-shadow-dom/) is a good overview of which properties pierce through the Shadow DOM and which ones don't. TL;DR:

   - ["inheritable"](https://gist.github.com/dcneiner/1137601) properties pierce through the shadow DOM
   - CSS custom properties also pierce through the Shadow DOM
   
3. Because of the above, in https://github.com/WordPress/gutenberg/pull/40868, I've realized that I'd need to add `all: initial` to the shadow host in order to achieve true encapsulation of styles. This same technique is also mentioned in the [article](https://open-wc.org/guides/knowledge/styling/styles-piercing-shadow-dom) (same as linked above). 

   However, this approach has a drawback which is that the any styles that are used in the [reset.css](https://github.com/WordPress/gutenberg/blob/942e40d919d8466a01761b65252df12bfaf33ef8/packages/block-library/src/reset.scss#L1) are not going to be applied. 
   
   In the light of that, I think it might be best to only set `initial` on the [inheritable](https://gist.github.com/dcneiner/1137601) properties.

4. Finally, I've tried an approach without using custom elements or Shadow DOM. Just adding a `<div style={ { display: 'contents', all: 'initial' } }>` that wraps the `<Warning/>` component, seems to isolate the styles just as well! So, I think the way to go would be to set only the aforementioned inheritable properties to `initial` on that wrapping `<div>`.

**Comment by DAreRodz** [comment]
I re-read [Using Shadow DOM](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM#:~:text=You%20can%20affect,for%20handy%20encapsulation.) and, AFAIU, using a shadow tree doesn't prevent global styles from being applied inside _in any way_. What it does is the opposite. CSS styles defined inside the shadow tree are encapsulated there and ignored outside.

That's certainly handy, but not in this case. 😅 

I guess the best approach is using [`all: initial`](https://developer.mozilla.org/en-US/docs/Web/CSS/all), as @michalczaplinski shared in the comment above. I think that's the way of preventing style inheritance in CSS.

**Comment by luisherranz** [comment]
> using a shadow tree doesn't prevent global styles from being applied inside in any way

It's true that it doesn't prevent inheritance, but it prevents targeting its elements from the outside, though. 

Look at how this `p` rule doesn't affect the paragraph inside the Shadow DOM.

```css
p {
  color: blue;
}
```

https://codepen.io/luisherranz/pen/OJQNVVG

---

I didn't know `all: initial` could be used in the Light DOM. I think you're right; that's probably the best option here 🙂👍️

**Comment by DAreRodz** [comment]
Thanks for your example, @luisherranz; pretty useful. 💯  I have to say that I don't know how styles are inherited yet, TBH. It looks like some rules are inherited, some others not?

If you, for example, add `color: red;` to the `.my-element` class, you will see that the paragraph inside the shadow tree turns red. 😅 

![Screenshot 2022-05-09 at 14 31 18](https://user-images.githubusercontent.com/6917969/167410541-297b9883-09b2-4f48-abf8-26d1d2ac15d5.png)

**Comment by ockham** [comment]
> The third approach that Bernie tried in https://github.com/WordPress/gutenberg/pull/40898 I think would also suffer from the problem of style leaking if there is another parent block (e.g. Group) that can change styling via Block Supports.

Good catch, thanks @michalczaplinski!

This _could_ be considered a more generic issue (it might affect existing GB warnings, such as the "Invalid block content" one), but I agree that it kind of gets in the way of #40898 being an exhaustive fix that we can merge in the short term 😬 

Edit: Yep, looks like it affects existing warnings. This is a Group with letter-case set to all-uppercase, containing one unsupported block:

![image](https://user-images.githubusercontent.com/96308/167435884-d326890c-aaec-473a-8257-c52a51ba2711.png)

**Comment by michalczaplinski** [comment]
>  It looks like some rules are inherited, some others not?

Exactly. [Some rules](https://gist.github.com/dcneiner/1137601) are inherited and others not. As you pointed out, the Shadow DOM prevents the styles _inside of it_ from leaking out, but the inherited styles still affect the content inside of the Shadow DOM.

> but it prevents targeting its elements from the outside, though.

That's also true! If we **only** use `all: initial` without the Shadow DOM, then technically some parent component could do something silly like `div { background: red; }` and mess with the styles of the `<Warning />`. But I think this is a minor concern.

**Comment by michalczaplinski** [comment]
I have dug a little deeper still and updated https://github.com/WordPress/gutenberg/pull/40868 with the approach of using just `all: initial`.

There are some caveats that I have documented there.

**Comment by luisherranz** [comment]
> If we only use all: initial without the Shadow DOM, then technically some parent component could do something silly like div { background: red; } and mess with the styles of the <Warning />. But I think this is a minor concern.

That's also true, although not what I had in mind when I made that comment 😄 

There are a lot of tiny details with these APIs, so I've made a [video to explain what I meant](https://www.loom.com/share/d686ac7c73fe473d9450657c8d50ffed).

But I think the current solution is great as it is, @michalczaplinski! 

EDIT: Now that I read your comment again, I'm not sure anymore if what you meant was what I meant already, or what you meant was that the shadow root can also be styled from the outside and conflict with the `all: initial` rule 😄🙏

**Comment by michalczaplinski** [comment]
yes, I'm sorry, I think I typed out my previous response too quickly! 😅 

What I meant is what you mentioned in the video! That when you use the light DOM, it can still be styled from the outside, even if you add the `inital: all`. But that's not a big issue in practice because probably nobody is going to target the specific classes that are applied in the Warning component nor would they usually write styles targeting all `p` :

```css
/* Don't think anyone's gonna write something like that outside of the Warning component */
.block-editor-warning__message {
  text-transform: uppercase;
}

/* And if you add styles like that in your site, you probably have a bigger 
   problem or you know what you're doing :)  */
p { 
  text-transform: uppercase;
}
```
