### ISSUE TITLE
Improve Colour Picker Copy and Pasting UX

### ISSUE THREAD

**Issue by Nyiriland** [WordPress/gutenberg#40692]
## What problem does this address?

**Better UX for pasting/copying colours within the colour picker. Below is a Figma mockup.**

![image](https://user-images.githubusercontent.com/3835008/165783922-94c0399f-c1b9-4d07-ba52-066d5f8e286f.png)

## What is your proposed solution?
**See above screenshot.** Essentially:

- Colour picker opens with "detailed inputs" mode already active
- "Show detailed inputs" toggle (now unnecessary) is replaced with a button to copy colour value
- In future iterations, could potentially condense colour value input fields to a single row to reduce vertical space.

**Comment by iwasthesword** [comment]
I agree with this. As a standard UX when clicking I expect it to be editable/selected so I can choose to either copy or paste it.

**Comment by mghenciu** [comment]
+1 for an UI/UX rework here.

Developers Tools from Chrome use a similar popup - and the (first) UX flow is to edit the HEX value, not copy:
![image](https://user-images.githubusercontent.com/52494172/170050373-16e65a25-8a81-49ae-8964-a94cf64f4dc6.png)

___
To be more empathic , I tried using the flow using only the WP context (meaning that I tried copying a gradient from a Section to another). **And here is another pain point - # char handling**. 

- So I went to a section, selected the color 
- clicked on the HEX to copy it
![image](https://user-images.githubusercontent.com/52494172/170052614-4243c25b-6690-4af4-8b86-1c125d3075f7.png)
- HEX was copied with **Number sign** #2873FF
- I went to another Section to paste the copied HEX
- and when I paste it, **it doesn't works because it should be without the** **#**
![image](https://user-images.githubusercontent.com/52494172/170053216-652694e1-9f96-42ef-851f-a6d82aa7eeaf.png)

 
___ 
For the second paint point, a potential solution would be to make it like in Figma & Chrome Dev Tools - if a user would paste #7B61FF or 7B61FF, those will both work.

**Comment by stokesman** [comment]
Nicely detailed suggestions @Nyiriland. The main issue here should now be resolved by https://github.com/WordPress/gutenberg/pull/41222. The issue noted by @mghenciu should be resolved by https://github.com/WordPress/gutenberg/pull/41223.

It looks like this issue could be closed. The unaddressed suggestion is:
>In future iterations, could potentially condense colour value input fields to a single row to reduce vertical space.

There may be another open issue to which the suggestion could be appended.

**Comment by annezazu** [comment]
For context, with WordPress 6.2, the current view looks like this:

<img width="291" alt="Screen Shot 2023-04-28 at 3 47 47 PM" src="https://user-images.githubusercontent.com/26996883/235165547-2be1d6db-43a7-4fbc-b3a1-d201362c3983.png">

As a result, and based on the above comment from @stokesman, I'm going to close this issue out!
