### ISSUE TITLE
Navigation: New menus are locked by default

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#40822]
To reproduce:

* Enable the Navigation experiment in Gutenberg settings
* Open "Navigation (beta)"
* Enter a name to create the menu
* Notice that you cannot immediately edit the menu because it is locked.

Video:

https://user-images.githubusercontent.com/846565/166704921-fa9e273e-4a19-41c3-ae11-007b2e4c820f.mp4

Edit: Possibly related, but even when unlocked I cannot add all pages or start empty:

https://user-images.githubusercontent.com/846565/166705345-abe29e46-a5ce-4d3f-b408-e6054ab08327.mp4

**Comment by Mamaduka** [comment]
Hi, @jameskoster

This is probably related to #40263. The editor uses template lock for main navigation block, so the lock status is inherited.

Second is known bug, but since screen development is on hold for now, I don't think it's priority to fix the issue.

**Comment by getdave** [comment]
> The editor uses template lock for main navigation block

Oh! Since when?

**Comment by Mamaduka** [comment]
I'm not sure when this change was introduced, but it's there :)

https://github.com/WordPress/gutenberg/blob/ad2a96baac3351a0cc00d4113b2b60bcca03bbdb/packages/edit-navigation/src/components/layout/index.js#L125-L128

**Comment by talldan** [comment]
> Enable the Navigation experiment in Gutenberg settings

There are quite a few issues with the navigation editor because of changes to the block. Maybe it's worth removing this setting and ensuring the editor isn't enabled for anyone (the code for the editor can stay, but perhaps the project is considered 'mothballed').

I don't think there's any active effort to solve the issues and my concern is that it's confusing or might break things for users.

> I'm not sure when this change was introduced, but it's there :)

I think from the very start. The navigation block isn't removable since that's the main (only) way users can build menus.

The nav block's inner blocks are unlocked here:
https://github.com/WordPress/gutenberg/blob/6f11e0b8dd377f3eb85faf0c182fa053bf7bdaaf/packages/block-library/src/navigation/edit/inner-blocks.js#L134-L137

I don't think the inability to edit the block is caused by template lock, but more likely other bugs. 

There were more recently some discussions about not using a navigation block at all, which would solve this particular issue—it'd be more like a BlockEditorProvider that has the same configuration as the nav block (allowed blocks etc).

**Comment by kathrynwp** [comment]
Closing this issue due to the Navigation Screen project being moved to [an inactive status on the feature projects page](https://make.wordpress.org/core/features/) in coordination with the project leads. (The developer documentation in the initial post are no longer accessible)

If this work is picked back up, issues can be revisited and reopened as needed. Thanks for pitching in on this early feature so the wider WordPress project could benefit from the lessons learned!
