### ISSUE TITLE
Double gutenberg_ prefix given to some PHP functions during the build

### ISSUE THREAD

**Issue by adamziel** [WordPress/gutenberg#40938]
## Description

Add the following code to `packages/block-library/blocks/navigation.php` and run the build:

```php
function block_core_navigation_get_post_ids( ) {
}

function block_core_navigation_get_post_ids_from_block( ) {
}
```

It gets bundled in `build/block-library/blocks/navigation.php` as:

```php
function gutenberg_block_core_navigation_get_post_ids( ) {
}

function gutenberg_gutenberg_block_core_navigation_get_post_ids_from_block( ) {
}
```

This is caused by the following webpack transform:

https://github.com/WordPress/gutenberg/blob/7c9286a1158a6a97d231d38430ce2f585e877cd7/tools/webpack/blocks.js#L122-L169

In short:

1. The transform finds function `block_core_navigation_get_post_ids`
2. It performs a naive str_replace to `gutenberg_block_core_navigation_get_post_ids`
3. In the process, `block_core_navigation_get_post_ids_from_block` also gets affected
4. Then, the transform acts on the `block_core_navigation_get_post_ids_from_block` separately

And we end up with a double prefix.

Initially seen in https://github.com/WordPress/gutenberg/pull/40752#issuecomment-1121127913

Related: https://github.com/WordPress/gutenberg/pull/40657

cc @spacedmonkey @gziolo @youknowriad @ellatrix @noisysocks @getdave

**Comment by adamziel** [comment]
I initially thought of replacing `function $name` to `function gutenberg_$name` instead of `$name` to `gutenberg_$name`, but that would not handle cases like `$post_ids = array_map( 'block_core_navigation_get_post_ids_from_block', iterator_to_array( $inner_blocks ) );`.

The only other solution I can think if is checking each match for the presence of `gutenberg_` prefix right before replacing. Otherwise, we'd need a PHP parser.

**Comment by noisysocks** [comment]
Lol nice. Could we use a negative lookahead? Haven't tested it but something like this.

```
/^\s*function (?!gutenberg_)([^\(]+)/gm
```

**Comment by adamziel** [comment]
@noisysocks that would work, we'd just have to stop precomputing all the matches first:

```js
Array.from(
	content.matchAll(
		/^\s*function ([^\(]+)/gm
	)
)
	.reduce( ( result, [ , functionName ] ) => {
		// Prepend the Gutenberg prefix
	}, content )
```

And start matching and replacing in batches of one:

```js
while ( true ) {
	const match = content.match(
		/^\s*function (?!gutenberg_)([^\(]+)/gm
	);
	if ( ! match ) break;
	// Prepend the Gutenberg prefix
}

```

**Comment by ockham** [comment]
Also happening to [`block_core_navigation_insert_hooked_blocks_into_rest_response`](https://github.com/WordPress/gutenberg/blob/6ebbb8b2c2724bbc293650ed82b723bcc02ed8ec/packages/block-library/src/navigation/index.php#L1596) (because it fully includes another function name, [`block_core_navigation_insert_hooked_blocks`](https://github.com/WordPress/gutenberg/blob/6ebbb8b2c2724bbc293650ed82b723bcc02ed8ec/packages/block-library/src/navigation/index.php#L1464)).

**Comment by ockham** [comment]
> @noisysocks that would work, we'd just have to stop precomputing all the matches first [...] [a]nd start matching and replacing in batches of one: [...]

Alternatively, we might be able to keep the batch processing if we made sure we're only replacing full function names, i.e. tweak this part so that `functionName` needs to be followed by a non-alphanum, non-underscore: https://github.com/WordPress/gutenberg/blob/6c47fe212da8957972f867295a1727de9f1fb0a2/tools/webpack/blocks.js#L190-L193

Finally, a quick-and-dirty fix might be to remove `gutenberg_` before adding `gutenberg_` 😬

```diff
diff --git a/tools/webpack/blocks.js b/tools/webpack/blocks.js
index 080ee2e0124..329510e9fba 100644
--- a/tools/webpack/blocks.js
+++ b/tools/webpack/blocks.js
@@ -194,7 +194,7 @@ module.exports = [
 													( match ) =>
 														prefix +
 														match.replace(
-															/^wp_/,
+															/^(wp_|gutenberg_)/,
 															''
 														)
 												);
```

**Comment by adamziel** [comment]
Moving the rewriting to PHP and using the built-in tokenizer would make this much easier.
