### ISSUE TITLE
Color reset trigger is missing in 6.0-RC1

### ISSUE THREAD

**Issue by imnavanath** [WordPress/gutenberg#40960]
### Description

In editor the color picker don't have "Reset" trigger in the version of 6.0-RC1.
Core trac - https://core.trac.wordpress.org/ticket/55707
Screenshot - https://share.bsf.io/2Nuz4q0o

- Issue reproducible in - 6.0-RC1
- With theme - 2022

### Step-by-step reproduction instructions

Check editor any color picker in WP-6.0-RC1

### Screenshots, screen recording, code snippet

https://share.bsf.io/2Nuz4q0o

### Environment info

WordPress version: 6.0-RC1
Browser used: Chrome
System info: Windows with 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment]
I was able to replicate this. It is because `clearable` is [set to false here](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/colors-gradients/dropdown.js#L138), which I think was a deliberate design decision to remove reset/clear buttons when there was also a reset option in the ToolsPanel dropdown. I can't find an issue that explicitly states this though.

It would be easy to toggle this back on, but I think we should get some design input before doing so.

**Comment by aaronrobertshaw** [comment]
One of the goals of the `ToolsPanel` design was to reduce the proliferation of reset and clear buttons as more controls were added to the inspector controls sidebar. I believe this was part of https://github.com/WordPress/gutenberg/issues/27331 though I'm a little short on time and haven't been able to dig too far into it to locate the exact comment or sub-issue that might have explicitly stated that intent.

When the color panel was switched to use the `ToolsPanel`, the [clearable flag was set to false](https://github.com/WordPress/gutenberg/pull/34027/files#diff-ad1d53efac56f53733486d999e58f29074e50b74b692ce5f5fd78b4c3163781cR32) for the block support color controls then.

**Comment by ndiego** [comment]
Yes, this was a deliberate design change. Note that you can reset colors using the dropdown. See the gif below.  

Since this change is intentional in 6.0+ I am going to close this issue, be please let me know if there are any further questions or concerns.

![color-reset](https://user-images.githubusercontent.com/4832319/168590329-9f747667-04c8-4e50-8db3-e539faf79737.gif)
