### ISSUE TITLE
Style variations preview is cut off

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#41177]
### Description

When using 6.0 RC 3, the style variations preview is now cut off. If I use GB 13.2.2, it shows up correctly so something must have changed recently. cc @ndiego as a heads up & @glendaviesnz since you chimed in on another similar issue @gziolo as co-core editor tech lead. 

Here's another similar issue about the preview where you can see how this should appear https://github.com/WordPress/gutenberg/issues/40699

### Step-by-step reproduction instructions

1. Open the Appearance > editor
2. Open styles
3. Select "browse variations"
4. Notice problem

### Screenshots, screen recording, code snippet

What it looks like: 
<img width="285" alt="Screen Shot 2022-05-19 at 6 16 44 PM" src="https://user-images.githubusercontent.com/26996883/169429358-5f05587a-7373-4d30-b1ff-ee9e460a28d7.png">

What it should look like:
![165822972-5c946f50-edad-48fc-b3d8-cb9e23bc7771](https://user-images.githubusercontent.com/26996883/169429483-77bec2f5-b472-4886-a089-6c8d3c9ed459.gif)

### Environment info

- WordPress 6.0 RC 3
- No GB
- TT2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by getdave** [comment]
I remember https://github.com/WordPress/gutenberg/pull/40842 was adjusting things to do with iframes and styles.

**Comment by Mamaduka** [comment]
I think I was able to track down the problem. It's similar to the issue with the Pattern previews in WP 5.9.

When the `SCRIPT_DEBUG` is set to `false` and Gutenberg plugin isn't active, some styles are leaking into the iframes. In this case, [`min-width` is set for the `body`](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-admin/css/common.css#L3766-L3769).

The main problem with this bug is that it's tough to test with Gutenberg active.

I will try to create a POC patch.

## Screenshot
![CleanShot 2022-05-20 at 14 56 57](https://user-images.githubusercontent.com/240569/169514072-cc885af2-21ea-47c1-9c5e-a4a3ee291aa5.png)

**Comment by ndiego** [comment]
I can confirm. Looks like a lot more styles are being applied to the `<body>` tag in RC3, and one of them is `min-width: 240px`.

**RC3 only**
![image](https://user-images.githubusercontent.com/4832319/169514006-25bef6cd-9e19-4c5f-bc4a-642a1a323d65.png)

**RC3 with Gutenberg 13.2.2**
![image](https://user-images.githubusercontent.com/4832319/169513785-083d6d1e-6a64-4385-a1f2-07e0a76c38da.png)

These styles look to be [applied straight](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-admin/css/common.css#L3766-L3769) to all `<body>` tags in the editor. 

We could fix this with something like the following. It is not very elegant but would be the quickest solution that could then be iterated on post-release.

```
body.editor-styles-wrapper {
    min-width: 0;
}
```

**Comment by ndiego** [comment]
@Mamaduka I just confirmed that adding the following to common.min.css does fix the problem. Not a great solution, but one nonetheless 🤷‍♂️

```
@media screen and (max-width: 782px) {
    body.editor-styles-wrapper {
        min-width: 0;
    }
}
```

**Comment by Mamaduka** [comment]
@ndiego, this is what I was thinking:

_packages/edit-site/src/components/global-styles/preview.js_

```
<EditorStyles
	styles={ [
		...styles,
		{
			css: 'body{min-width: 0;}',
			isGlobalStyles: true,
		},
	] }
/>
```

@youknowriad, any preferences on we should add `min-width:0`?

**Comment by ndiego** [comment]
Yeah, that is a bit more elegant that my hack 🙌

**Comment by youknowriad** [comment]
I'm fine adding the min width to the iframe styles but let's ensure that it's added before the styles that come from the theme (themes can potentially override this right?)

Also it's probably something that should only be added in the iframe, and not for all usage of EditorStyles

**Comment by youknowriad** [comment]
The suggested fix above applies to the previews only, I assume these styles can leak to the main iframe too right? Don't we have any issues there?

**Comment by Mamaduka** [comment]
Most of the other iframes are larger than 240px. The better fix would be to avoid leaking these styles in iframes, but I'm not sure how :(

**Comment by youknowriad** [comment]
Yes, let's just add it to the iframe component with a comment now. I don't think we can easily avoid the leaks without removing the compact CSS thing which we can't do.

The other thing would be to figure out to split styles into two calls instead of one in Core depending on whether they're theme styles or core styles.

**Comment by annezazu** [comment]
Thank you all for jumping in and resolving this so quickly.
