### ISSUE TITLE
Add ability to use "Page creation Patterns" for custom post types

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#41304]
## What problem does this address?

This would be a follow up from #38787. It is now possible to mark patterns as full page patterns by setting `blockTypes` to `array( 'core/post-content' )`. Currently this feature is limited to the Page post type however. 

## What is your proposed solution?

It would be great to also add support for custom post types to use the page creation patterns.

It would also be great to have a way to determine which patterns should get shown for which Post type. If I imagine a "Product" custom post type it would be super useful to only show various product-specific patterns that already use product CPT specific blocks in it.

At the same moment, it would be really valuable to have some programmatic way to opt-in or out of the modal altogether for certain post types.

**Comment by Humanify-nl** [comment]
Great idea.

I think the reasoning why this isnt here for full page patterns in CPT's may be this:

Custom post types usually have a specific layout. We can already [prefill post types with blocks](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-templates/#custom-post-types) when registering a post type with the 'template' array. 

It would be amazing if we could refer to an existing pattern file here (from /patterns dir in theme). If we could add an array with two or more templates? We could auto fill the 'page creation modal' with a choice between two variations of the CPT template.


#### Proposed method of refering to template instead of block markup:
```
function myplugin_register_book_post_type() {
    $args = array(
        'public' => true,
        'label'  => 'Books',
        'show_in_rest' => true,
        'template' => 'post-book-pattern', // ( a php file which exists inside /patterns in theme)
        ),
    );
    register_post_type( 'book', $args );
}
add_action( 'init', 'myplugin_register_book_post_type' );
```

#### Proposed method with multiple pattern files.
```
function myplugin_register_book_post_type() {
    $args = array(
        'public' => true,
        'label'  => 'Books',
        'show_in_rest' => true,
        'template' => [ 'post-book-pattern', 'post-book-pattern-two' ]  // it is now an array, so page creation modal is triggered.
        ),
    );
    register_post_type( 'book', $args );
}
add_action( 'init', 'myplugin_register_book_post_type' );
```

##### Additionally:
A more abstract issue coupled with this is:

_What is the difference between a 'template' and 'page-creation-pattern', in the eyes of a client / non-dev user?_

These two concepts become a bit entangled and the more I think about this, the less it makes sense to make a distinction between a template and a full-page-pattern.

**Comment by jorgefilipecosta** [comment]
Thank you all for the discussion that happened. I proposed an implementation for this issue at https://github.com/WordPress/gutenberg/pull/41791.

**Comment by mtias** [comment]
I see this is the same proposal as https://github.com/WordPress/gutenberg/issues/41398. @jorgefilipecosta take a look at the API I propose there, I think it's clearer.
