### ISSUE TITLE
Query Loop Block doesn't respond to the function is_paged() 

### ISSUE THREAD

**Issue by Rale379** [WordPress/gutenberg#41409]
Hello,

The function `is_paged()` doesn't work.

It works fine on a Woo Shop page, for example, but not on a Blog Archive page built with the Query Loop block.

Above the posts grid, there is a section that I would like to only show on the first page.

On paginated pages, the section should no load.

I tested `!is_paged()` with a simple code snippet. 

But, I will be using the plugin [Block Logic – Full Gutenberg Block Display Control](https://wordpress.org/plugins/block-logic/) to add the logic.

Got any ideas for a workaround?

**Comment by justintadlock** [comment]
@Rale379 - Can you share the code that you're trying for more context?

**Comment by Rale379** [comment]
@justintadlock - Thank you for the response.

It works properly on the default Woo Shop page, but on a Gutenberg Archive, all pages show the HTML from the `!is_paged()` condition.
```
add_action('wp_head', 'paginated_condition_43987');
function paginated_condition_43987() {
	
	if( !is_paged() ){
		
		echo'<h1>This is the first page</h1>';
	}
	
	if( is_paged() ){
		
		echo'<h1>This is a paginated page</h1>';
	}
}
```

**Comment by Rale379** [comment]
To add more info...

The category archive works properly with the `is_paged()` function.

And that's probably because it uses the default Archive template.

On a custom page, that I want to use as the blog archive, I am not able to select the default Archive template.

I can only select custom templates.

And a page with a custom archive template does not work with the `is_paged()` function.

If I go to the WP Customizer and set my posts page to be Blog, the `is_paged()` function works.

But, then it's using a template that I don't have access to and can't edit with Gutenberg.

**Comment by Rale379** [comment]
The problem is probably in the URL structure.

The Category page is using the default Archive template and works well
site.com/category/news/page/2/

The Blog page is using a custom archive template and doesn't respect the `is_paged` condition
site.com/blog/?query-14-page=2

**Comment by justintadlock** [comment]
I see what you're referring to now.  `is_paged()` has never worked for custom query URLs like that in WordPress (even before Query Loop).

And, there's really no good way to universally check that because the query ID could change  (`?query-14-page` might be something entirely different for another query).

For this specific query, you could check like this:


```php
if ( isset( $_GET['query-14-page'] ) && 1 < intval( $_GET['query-14-page'] ) ) {
	// Do something
}
```

But, this should definitely be addressed.  

I'm not sure `is_paged()` is the right function or whether we need a new function.  Historically, it has only ever worked where the global query is paged.  It's possible there might be back-compat concerns.  

I have added the "WP Core Bug" label here in case we end up making a decision to change how `is_paged()` works in core.  We can remove that if the best course is to create a new conditional function or method of handling this.

**Comment by Rale379** [comment]
Dammit, I already hand-coded most of the archive page...  :)
Wasn't expecting a solution, at least not this quickly.

Thank you for the code. I will be using it
