### ISSUE TITLE
Add Image block, Initial state on popup incorrect.

### ISSUE THREAD

**Issue by richardmorrison** [WordPress/gutenberg#41473]
### Description

Using the Image Block in Gutenberg, when selecting the Media Library option, the pop up starts on the Upload tab, not the Media Library tab. And also stays on the selected option, when closing and re-opening the pop up.

<img width="324" alt="Screen Shot 2022-06-01 at 12 39 01 PM" src="https://user-images.githubusercontent.com/61720320/171305568-b24582d2-34b2-4f17-97b4-ced849a54d85.png">

### Step-by-step reproduction instructions

1. Create new post.
2. Add Image block.
3. Select Media Library to find image.
<img width="673" alt="Screen Shot 2022-06-01 at 12 40 00 PM" src="https://user-images.githubusercontent.com/61720320/171305646-1ed7a148-c193-440e-a5a1-72ef45030461.png">
4. Pop up dialog shows the Upload Files tab first.
<img width="346" alt="Screen Shot 2022-06-01 at 12 41 03 PM" src="https://user-images.githubusercontent.com/61720320/171305724-f982da3c-9da1-4e6c-89b5-353dfdfe62de.png">
5. If Media Library tab is selected, on closing the pop up modal, on reopening, it stays on Media Library.. though the same happens if Upload Files tab is selected. Eg: It stays on selected state.
 

### Screenshots, screen recording, code snippet

![gutenberg-image-upload-bug](https://user-images.githubusercontent.com/61720320/171306486-8b2642ca-a5dc-4f61-8ed4-9e0251bc77d9.gif)

### Environment info

WordPress 6.0 without Gutenberg plugin.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kathrynwp** [comment]
Hi @richardmorrison – thanks for the report!

I was not able to replicate this issue with WordPress 6.0, either with or without the Gutenberg plugin active (v. 13.3.0).

Here's a screencast:

https://user-images.githubusercontent.com/7662449/171446685-cd793982-3b2f-4614-a614-5f51a6c17159.mov

Are you experiencing this only this one specific site, or on other sites running WP 6.0 as well?

**Comment by glendaviesnz** [comment]
@kathrynwp I was able to replicate this on WP 6.0 with latest GB trunk, but it only happens if you select the `Upload` tab in the media library modal and exit, an then click `Media library` again, eg. it remembers your last open tab:

https://user-images.githubusercontent.com/3629020/172769766-e01b7e0c-a5cf-447d-a28f-aae6bdd6eb82.mp4

I guess it could sometimes make sense to remember the last open tab of the media dialog, but it is a little confusing in this context as you have `Upload` and `Media Library` buttons and you click `Media Library` and end up on an `Upload` tab, and you don't necessarily make the connection that it was the tab you were last on last time you used the media library, and if you wanted to `Upload` first up you would probably use the upload button on the placeholder.

**Comment by carolinan** [comment]
I am seeing the same result as Glen.

**Comment by akasunil** [comment]
Have fixed this issue in PR [41678](https://github.com/WordPress/gutenberg/pull/41678). Thanks
