### ISSUE TITLE
Query Loop Block Filter Expansion

### ISSUE THREAD

**Issue by Zaeo** [WordPress/gutenberg#41797]
## What problem does this address?

Currently, the logic behind the Query loop filter with multiple categories is OR. This is the only option and limits the use of filters to get more specific hub pages for larger sites. This functionality has been in plugin-based implementations of query loops for years. I don't use tags at all, and going back and modifying hundreds of posts to add them for more specific filtering is way more work than it's worth.

Keyword filtering doesn't work either, as I mention games in my other categories as an interlinking strategy, so they show up in the query.

For example, I do Reviews of Games, Software, and Hardware. Well, I have a reviews category, a Games category, a Software Category, and a Hardware Category. I want to be able to filter Reviews + Games, Reviews + Software, and so on.

## What is your proposed solution?

Implement a dropdown selector in the block filter to change the filter logic for categories and tags to dictate how multiple categories are handled.

AND / OR / EXCLUDE being the three options. I'd even be happy with just AND / OR logic.

**Comment by kathrynwp** [comment]
Hi there @Zaeo, thanks for submitting this issue! I found an overarching issue that dives into related enhancements to Query Loop block filtering:

https://github.com/WordPress/gutenberg/issues/30706

Since your suggestion here relates closely to the existing issue, I'm going to close out this one. In order to consolidate the feedback, please chime in on the existing ticket to add your thoughts. Thanks!
