### ISSUE TITLE
Figure out media integration.

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#418]
In the not distant future we need to start integrating this. Related https://github.com/WordPress/gutenberg/issues/310

@westonruter you may have thoughts on this as part of the media widgets work.

**Comment by westonruter** [comment]
The different media widget types should provide good examples for how to invoke the media library, passing in a state, and getting a mutated state back out for use in blocks.

One thing we just came up against in the realm of embeds is the fact that currently the `parse-embed` admin-ajax request requires a `post_ID` for context. This request is used to preview an embed in the media modal frame and also (currently) when the media is shown in the TinyMCE editor. The `post_ID` is required I believe because WordPress currently caches external oEmbed responses in postmeta. 

There has been some discussion about enhancing the `embed` REST API endpoints in core to support the `proxy` use case, as opposed to just getting an embed for a post/page. See https://wordpress.slack.com/archives/C02RQC26G/p1492038272597233

**Comment by jasmussen** [comment]
Some relevant discussion in https://github.com/WordPress/gutenberg/issues/454#issuecomment-297357691

**Comment by westonruter** [comment]
Note that media manager is no longer dependent on having a post for context to fetch oEmbed data. It now makes use of the new oEmbed proxy endpoint in the core REST API.
