### ISSUE TITLE
It takes more than 20 seconds to paste not-so-large HTML document.

### ISSUE THREAD

**Issue by kohheepeace** [WordPress/gutenberg#41826]
### Description

Copy-pasting a **not-so-large** HTML document takes more than **20 seconds**.

[**A same issue has already been reported**](https://github.com/WordPress/gutenberg/issues/14079#issuecomment-1156516305
), but I have created a new issue to **isolate the problem**.

### Step-by-step reproduction instructions

1. Create new wordpress site by Flywheel Local (wordpress version is 6.0)
2. Install gutenberg plugin and activate it. (gutenberg version is 13.4.0)
3. Goto https://docusaurus.io/docs and copy the document
4. Create new post and paste the copied HTML document

### Screenshots, screen recording, code snippet

The following gif is when copy-and-pasting https://docusaurus.io/docs content.

![2022-06-21 09 54 06](https://user-images.githubusercontent.com/29557494/174695427-20c86d38-e056-4cf6-be75-a182832aea99.gif)

### Environment info

- Wordpress version: 6.0
- Gutenberg version: 13.4.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
@aristath wonder if you have any insights here based on some of the performance work you've done!

**Comment by annezazu** [comment]
I just replicated this on the Make Network (Make Core specifically). I'll try to flag this up in #core-editor to see if anyone can take a look.

**Comment by ntsekouras** [comment]
The problem is in this [line/function](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/rich-text/use-paste-handler.js#L92)(`removeWindowsFragments`). You can test by commenting it out. This function was introduced [here](https://github.com/WordPress/gutenberg/pull/33607) and passing the `html` string by two consecutive `replace` functions is quite expensive. 

Also it's a great time to [write a test for this](https://github.com/WordPress/gutenberg/issues/34235).

In the snippet provided in the PR do we need to also remove the `html and body` tags? Does someone know? --cc @getdave 

```
<html>
 <body>
   <!--StartFragment-->
   Copied text here
   <!--EndFragment-->
 </body>
</html>
```
IMO if we don't find a workaround quickly enough, it would be good to revert that PR, as this affects paste in every OS and is taking a really long time..

**Comment by mcsf** [comment]
> The problem is in this [line/function](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/rich-text/use-paste-handler.js#L92)(`removeWindowsFragments`). You can test by commenting it out.

Nice sleuthing! 🌟 

> This function was introduced [here](https://github.com/WordPress/gutenberg/pull/33607) and passing the `html` string by two consecutive `replace` functions is quite expensive.

This surprised me, so I looked at the function, thinking that `replace` by itself shouldn't be **that** expensive. What follows are just my immediate reactions, and I haven't confirmed any of this with code. This is the body of the function:

```js
const startReg = /.*<!--StartFragment-->/s;
const endReg = /<!--EndFragment-->.*/s;
return html.replace( startReg, '' ).replace( endReg, '' );
```

What stands out here are the `.*` patterns combined with the [`s` flag](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/dotAll) of the regular expressions. I can expect this to cause the RegExp engine to start eating loads of memory as it consumes the matches, and maybe even to backtrack if there are multiple of these `(Start|End)Fragment` marks.

Since the goal of the function is to remove the marks as well as any preceding/following whitespace, I would rewrite it as:

```js
const startStr = '<!--StartFragment-->';
const startIdx = html.indexOf( startStr );
if ( startIdx > -1 ) html = html.substring( startIdx + startStr.length );

// Possible optimisation: only run this second block if there was a match for `startStr`.
const endStr = '<!--EndFragment-->';
const endIdx = html.indexOf( endStr );
if ( endIdx > -1 ) html = html.substring( 0, endIdx );
```

**Comment by mtias** [comment]
Agreed on reverting if there is no quick fix. Also, the suggested test looks like it's just for pasting on Windows, but we should have performance tests for pasting larger chunks of content in general given this regression slipped through.

**Comment by Mamaduka** [comment]
I think this is a good candidate for 6.0.1.

cc @adamziel
