### ISSUE TITLE
image linking issue wordpress 6.0

### ISSUE THREAD

**Issue by helpmeurgent** [WordPress/gutenberg#41994]
### Description

after upgrading to WordPress 6.0, i notice that if i copied image from external source linking, its actually uploading on my server

but before in WordPress 5.9 or all older version its was works perfectly if i copy a image from external source, pasted image also linked external source not uploaded my hosting storage

how can i stop it?

### Step-by-step reproduction instructions

video: https://youtu.be/dBK6LSx-p4s

### Screenshots, screen recording, code snippet

video: https://youtu.be/dBK6LSx-p4s

### Environment info

video: https://youtu.be/dBK6LSx-p4s

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
@mcsf, I think this is related to the recent fixes in #38992.

**Comment by helpmeurgent** [comment]
both are different things, it's not same, its happened every WordPress 6.0 version, i have tested multiple sites

**Comment by mcsf** [comment]
Hi, @helpmeurgent. 

>  if i copied image from external source linking, its actually uploading on my server

This is the intended behaviour. As @Mamaduka points out, up until 5.9.x there was a bug causing the editor to insert an external image when the user pasted an actual image attachments.

It should be understood that there is no one-size-fits-all behaviour, but, according to #38992 and other reports, the most expected outcome when pasting image attachments is to upload them to the site's media library.

> how can i stop it?

* Copy the URL of the image instead of the image itself
* Add a new Image block and click "Insert from URL"
* Paste the copied URL and confirm

https://user-images.githubusercontent.com/150562/177132911-504a0e4d-e7d2-40be-b578-e9d805dd6a55.mp4

* * *

That said, your screen recording did highlight a particular UI bug: 

<img width="476" alt="blog bug" src="https://user-images.githubusercontent.com/150562/177133242-24ef2f61-d59d-43ec-922d-94ece493e115.png">

The real URL is something like `https://my-domain/my-site/wp-content/uploads/.../my-image.jpg`, instead of `blob:<external-URL>`. This is a minor bug that I'll fix right away, but it doesn't affect the actual post content.

**Comment by helpmeurgent** [comment]
but I want to like before external image should attach like WordPress 5.9. i have an images website now i copy all image link one by one and put links paste image URL it takes huge time, currently I'm using my site WordPress 5.9 for this issue not updated to WordPress latest version

**Comment by helpmeurgent** [comment]
anyone here to help?

**Comment by ndiego** [comment]
This issue was reviewed in today's Editor Bug Scrub. While I know the current implementation is not what you are looking for @helpmeurgent, everything is working as intended per the [comments above](https://github.com/WordPress/gutenberg/issues/41994#issuecomment-1173627889). There are no plans to change this functionality. Therefore I am going to close this issue.
