### ISSUE TITLE
Fix ComboboxControl outputting duplicate IDs with FormTokenField

### ISSUE THREAD

**Issue by alexstine** [WordPress/gutenberg#42112]
### Description

The ComboboxControl component uses the FormTokenField component to render the author combo box when the number of users is equal to or greater than 25. Once this happens, the IDs are duplicated because useInstanceId hook thinks FormTokenField and ComboboxControl components are different. This is caused I believe because of a custom focus management component wrapped around the ComboboxControl output components. I would expect the IDs to not be duplicated as this is severely impacting accessibility.

### Step-by-step reproduction instructions

1. Ensure your site has at least 25 users that have the ability to be marked as an author. I believe user roles (author, editor, and administrator) will suffice.
2. Open a post.
3. Notice how author and tags have duplicated IDs.

### Environment info

Latest Gutenberg (trunk).

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by alexstine** [comment]
@ciampo @Mamaduka I moved this over here from this PR: https://github.com/WordPress/gutenberg/pull/42060.

I think I finally figured out what was going on but I really do not have time at this point to come up with a fix. Seems like instead of checking the exact object, we should allow a lazy match on something like this. Can one of you find someone to work on this? 💯 

Thanks!

**Comment by ciampo** [comment]
I looked into this as well, and I managed to reproduce the bug.

> The ComboboxControl component uses the FormTokenField component to render the author combo box when the number of users is equal to or greater than 25.

A more exact version of this description is:

The [`PostAuthor` component](https://github.com/WordPress/gutenberg/blob/1af7e35ab9b2714ea923b463bda6bb41591c6418/packages/editor/src/components/post-author/index.js) (in the `@wordpress/editor` package) displays a `SelectControl` or a `ComboboxControl` component depending on the number of users (the combobox is shown if there are at least 25 eligible authors to choose from).

---

After my investigation, I don't think that the issue is caused by neither the custom focus management mentioned above, or by the `useInstanceId` hook (at least, for how it's intended to work).

**I believe that the bug is caused by the fact that `ComboboxControl` [internally uses the `TokenInput` component](https://github.com/WordPress/gutenberg/blob/24acf9979c6acee76c09587dab79d37087623837/packages/components/src/combobox-control/index.js#L234-L251)** imported from the `FormTokenField` component.
The `TokenInput` component receives a prop called `instanceId`, [which is appended to a constant string prefix to create the final `id` for the underlying `input` element](https://github.com/WordPress/gutenberg/blob/ef6c5e99b6d6fa18fc0dbdefb8475a8a35ae5c72/packages/components/src/form-token-field/token-input.tsx#L45).

The bug reported in this issue can be reproduced when both a `ComboboxControl` and a `FormTokenField` component are rendered in the same page. Since they are 2 different components, they _can_ be assigned the same `instanceId` (i.e there can be a `ComboboxControl#1` and a `FormTokenInput#1`). But the fact that internally they use the same `TokenInput` component, makes it so that the resulting markup contains duplicated IDs (since both components are rendering `TokenInput` components with `instanceId = 1`).

The fix should be relatively simple, since [the `useInstanceId` hook accepts a `prefix` as the second argument](https://github.com/WordPress/gutenberg/blob/a3fa82c3ec0a57f2f09d438a36d2ae86ff805b03/packages/compose/src/hooks/use-instance-id/index.js). I will open a PR soon.


Edit: opened https://github.com/WordPress/gutenberg/pull/42134 with a tentative fix.
