### ISSUE TITLE
Consider not auto-publishing new templates

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#42130]
Currently, when you create a new template in the site editor it is published immediately, but there is no feedback to confirm this except for the disabled Save button which isn't particularly clear :)

https://user-images.githubusercontent.com/846565/177194690-4f7a2758-f99f-4ff3-8113-93734670ff8a.mp4

This may be something to address in the mean time, but more importantly let's discuss whether templates should be published instantly like this, or require an additional user action.

A strong argument _against_ auto-publishing is that the user may not understand the frontend of their site is affected immediately after creating the template. In the example video above I may leisurely go about creating my `tag` template over an extended period of time without realising that tag archives on the frontend could be broken until I'm done.

cc @WordPress/gutenberg-design

**Comment by scruffian** [comment]
Yeah this makes sense to me, as you say a simple change like this can easily break your site.

**Comment by draganescu** [comment]
So the only change to make is to not publish. Should a draft still be automatically saved?

**Comment by jameskoster** [comment]
No I don't think that'd be the only change, we'd need to contemplate the publish flow, and consider drafts like you mentioned.

But I think auto-publish is still worth discussing. It's awkward at the moment because:

1. You don't _know_ the template is auto-published.
2. New templates start blank.

But the former could easily be fixed, and the latter will be largely addressed by https://github.com/WordPress/gutenberg/pull/42007.

**Comment by paaljoachim** [comment]
Brain storming...
I create a template but still have adjustments I need to make to it. So upon creating a template I get the option to save as draft or to publish. I as it as a draft work on the template and then publish it.

I create a template and it is automatically published. As templates can be made and also get more advanced. Auto publishing a template can break "something" on the site, as I have not yet done whatever remains for the template to work as it should.

What about some kind of logic that does something like....
I make a template and something is required for me to do to make it work correctly. I get a message telling me that I still need to do so and so for the template to work correctly. This implies that there are specific steps one has to do for creating a specific template. As these steps are not finished yet as a user I would need to know how to finish the remaining steps so that I get the template to work.

That could of course mean that there is somekind of publish panel for specific templates giving me the information I need to get the template correctly setup and published.

**Comment by jameskoster** [comment]
Now that new templates are not created blank, the chance of breakages is significantly reduced making this less of an issue.

Still, it would be nice if there was some visual feedback to confirm that templates are published immediately after creation. We can probably look into that separately.
