### ISSUE TITLE
Autocompleter lets you insert multiple More blocks

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#4225]
![more-bug](https://user-images.githubusercontent.com/612155/34473892-53ef0bf2-efcc-11e7-92f8-997007a06ca7.gif)

#### Steps to reproduce
1. Create a new post
2. Insert a More block using the /slash shortcut.
3. Insert another More block using the /slash shortcut.

#### Expected result
Step (3) should be impossible as only one More is allowed in a post.

#### Actual result
[More, More, More!](https://www.youtube.com/watch?v=hVZKJt4WzxM&feature=youtu.be&t=51)

#### Root cause
Autocompleter doesn't respect the `useOnce` property.

**Comment by bobbingwide** [comment]
In the classic world it is quite valid to have the more tag multiple times in a post:
- posts which support multiple languages 
- posts with shortcodes that check the viewers capability. 
- and possibly even paged pages

When implementing this fix the implementer should to take backward compatibility into consideration.

**Comment by mcsf** [comment]
Thanks for providing that perspective, @bobbingwide. Such an example, however, really pushes the editor's ability to accommodate for the disparate uses of shortcodes and tags. This is probably one of those scenarios where the most viable option is to use the Classic block. Otherwise, Gutenberg will treat the shortcodes markings as individual shortcodes, or actually not detect them at all, since these (`[:en]`) start with a colon, which is currently not part of the pattern Gutenberg looks for:

https://github.com/WordPress/gutenberg/blob/4cf813540030640d99e4c53a86da49ddba6387f9/blocks/library/shortcode/index.js#L35-L43

Interestingly, upon testing this, the fact that those shortcodes start with a colon means that, when pasting, Gutenberg resorts to the Classic block on its own, thus preserving the legacy content:

Without `:` support | With `:` support
--|--
<img width="787" alt="screen shot 2018-02-09 at 12 24 22" src="https://user-images.githubusercontent.com/150562/36027737-5d25f8ee-0d94-11e8-9941-ea04b2c0c143.png"> | <img width="755" alt="screen shot 2018-02-09 at 12 25 01" src="https://user-images.githubusercontent.com/150562/36027742-6340d2a8-0d94-11e8-990c-61b64ea3ea53.png">

* * *

My takeaway is that we will never be able to anticipate all the possible ways in which shortcodes are used to structure special content. It it manageable to look at content within regular opening and closing tags:

```
[en]
Hello
[/en]
[fr]
Bonjour
[/fr]
```

but that's the extent of what we can infer.

**Comment by bobbingwide** [comment]
Note: I have just created a prototype test case which demonstrates that it's quite possible to create and display paginated content with multiple excerpts being correctly extracted.

```
Page 1 excerpt
<!--more more-->
Page 1 content
<!--nextpage-->
Page 2 excerpt
<!--more again-->
Page 2 content
<!--nextpage-->
Page 3 excerpt
<!--more third-->
Page 3 content
```

Whilst WordPress core doesn't cater for multiple extracts they can be achieved using very little code.
```
add_filter( "get_the_excerpt", array( $this, "paginated_excerpt" ), 10, 2 );
	
function paginated_excerpt( $excerpt, $post ) {
  global $more;
  $saved = $more;
  $more = false;
  $excerpt = get_the_content();
  $more = $saved;
 return $excerpt;
}
```

**Comment by mcsf** [comment]
Correct, though I'm not concerned about the server-side aspect, where I expect things to work the same way. I'm concerned about the editor, namely recognizing what is what.

**Comment by bobbingwide** [comment]
So long as it's clearly documented what the differences are between old and new.

**Comment by mtias** [comment]
We show this if you add more than one now:

![image](https://user-images.githubusercontent.com/548849/39752254-27c0ef58-52bb-11e8-8648-08430af55d23.png)

**Comment by ocean90** [comment]
While the notice is nice, we shouldn't allow adding multiple `useOnce` blocks via autocompleter at first place.

See also #3968.

**Comment by noisysocks** [comment]
Noting that https://github.com/WordPress/gutenberg/pull/6067 should fix this because it makes the autocompleter use `getInserterItems` which takes into account `useOnce`.
