### ISSUE TITLE
Add support for adding templates and template parts for plugins

### ISSUE THREAD

**Issue by costasovo** [WordPress/gutenberg#42362]
## What problem does this address?
Currently, templates are defined within the theme (source theme) and can be edited in the site editor (source custom). There are some use cases where plugins could also use the possibility to add a template. WooCommerce blocks plugin already adds templates for Product Catalog page, Product Page, etc. At MailPoet, we are considering using templates and templates parts for email templates.
[WooCommerce Blocks developers documented how they added the templates](https://github.com/woocommerce/woocommerce-blocks/blob/a5d7c19451e78ef8b2467ddef06e3dc2e0184021/docs/internal-developers/templates/block-template-controller.md). As you can see from the docs, adding a template is currently cumbersome.

## What is your proposed solution?
This could be solved by adding an API for registering a template. I don't know the internals in detail, so I struggle with proposing the solution.

I was thinking about a function like:
```php
/**
 * @param WP_Block_Template
 */
function register_block_template( WP_Block_Template $template ) {}
```
or maybe just 
```php
function register_block_template( array $args ) {}
```
The `$args` would cover [parameters for defining the block template](https://github.com/woocommerce/woocommerce-blocks/blob/a5d7c19451e78ef8b2467ddef06e3dc2e0184021/src/Utils/BlockTemplateUtils.php#L223-L234).

It could be used for both templates and template_parts.

**Comment by gigitux** [comment]
It isn't easy for a plugin to register a custom block template. I created a POC (I used `@wordpress/create-block` for the boilerplate), to show it: https://github.com/gigitux/poc-register-template-plugin/blob/main/poc-register-template-plugin.php.


Also, this is a production class that handles Block Templates for WooCommerce Blocks:

https://github.com/woocommerce/woocommerce-blocks/blob/2b79d3e87dffd5b38d5910ebcf39057e267d190d/src/BlockTemplatesController.php

As you can see, it is complex registering and handles custom block templates for a plugin.

Also, the current POC is bugged because it doesn't load the custom block template from the database after the user saves a new version of the template.

Following my exploration, it is necessary using three filters to register a block template:

- pre_get_block_template
- pre_get_block_file_template
- get_block_templates

Also, it is necessary to write custom logic to read the directory where the templates are placed and parse the filename to get the template's name.


It would be great to have a better way/specific API to register block templates.

**Comment by fabiankaegy** [comment]
I think this ticket may be a duplicate of #41401 

I'm going to leave it open for now since it already has some valuable context here but want to make both sides aware of one another :)

**Comment by Aljullu** [comment]
Just a heads-up that I left a comment with an API proposal in https://github.com/WordPress/gutenberg/issues/41401#issuecomment-2085542661.

> I think this ticket may be a duplicate of https://github.com/WordPress/gutenberg/issues/41401

+1 to closing this issue as duplicate of https://github.com/WordPress/gutenberg/issues/41401, given that the other one is older.

**Comment by fabiankaegy** [comment]
Closing to keep https://github.com/WordPress/gutenberg/issues/41401 as the main source of truth
