### ISSUE TITLE
Change Status and Visibility

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#4242]
From @ElectricFeet in testing:

> "Status and Visibility" also contains other page/post properties, such as the date and draft review status. So the title "Status and Visibility" doesn't describe the contents.

> Suggestion: Change this to "Page properties" (or "Post properties"/"Product properties" etc., depending on what you're editing).

I don't personally think Page/Post properties makes sense. However we could have Properties as an option. I think we can find a better word though.

**Comment by jasmussen** [comment]
No strong opinion here, the point seems kinda valid. Though not strongly so — the date and draft review status are both, well, statuses and the date is going to play a role in the posts visibility. So part of me leans towards this being a non-issue. But I also wouldn't object to a solid alternative.

Though if I recall correctly there are some challenges in including the post type in a translation. So perhaps just "Properties" instead of "Page properties", if that's the term we go with?

**Comment by karmatosed** [comment]
For now lets close this as we can always iterate and it does align more with core right now as is.
