### ISSUE TITLE
Social icons links need option open a new window

### ISSUE THREAD

**Issue by lwangdu** [WordPress/gutenberg#42506]
### Description

There is no way you can create social icons links option "open a new window". If someone could fix issue that would be great.
Thank you.

### Step-by-step reproduction instructions

Add social icon and add link. there is no option for open a new window.

### Environment info

 WP 6.0.1 and Gutenberg 13.6.0. 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
**'Open in new tab'** option has been introduced in many core blocks:

- `core/avatar`
- `core/button`
- `core/comment-author-name`
- `core/comment-edit-link`
- `core/file`
- `core/gallery`
- `core/image`
- `core/post-author-name`
- `core/post-title`
- `core/read-more`
- `core/site-logo`
- `core/site-title`

Since social icon links are supposed to be external links, so this suggestion makes a lot of sense.

**Comment by t-hamano** [comment]
@lwangdu
Sorry, I didn't do enough research, but Social Links Block already has the capability.

#25468

We can set a batch of link openings, is this what you are looking for?

**Comment by lwangdu** [comment]
@t-hamano Thanks for checking with me. I see in order get option 'open new window'. you have to select whole social area. If you click on individual social icon, there is no way you can check the option on or off. Thank you for your help!
