### ISSUE TITLE
Use of Unsafe Javascript preventing usage of secure Content Security Policy (CSP)

### ISSUE THREAD

**Issue by jornfranke** [WordPress/gutenberg#42513]
### Description

The wider context is written in: https://core.trac.wordpress.org/ticket/50997

The block editor uses in several places unsafe Javascript (amongst others the Function object) that prevents usage of secure CSP without allowing unsafe code. Some examples (might not be all):
Gutenberg is using turbo-combine-reducers (a not maintained package since 4 years): https://github.com/aduth/turbo-combine-reducers/blob/master/index.js#L25

Which has the issue. 

Another one is directly in Gutenberg: https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/utils/parse-css-unit-to-px.js#L27

There might be more places where unsafe code occurs. See also here for the description of unsafe code: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_eval_expressions

Note: The Function operator is very similar to eval and a prime source of XSS attacks. Thus it should be removed from the code and it should be possible to enable safe Content Security Policies without unsafe eval.

A similar issue was described in https://github.com/WordPress/gutenberg/issues/20395, but this is now a more detailed description.

### Step-by-step reproduction instructions

See https://core.trac.wordpress.org/ticket/50997

### Screenshots, screen recording, code snippet

See https://core.trac.wordpress.org/ticket/50997

### Environment info

Wordpress 5.x and 6.x confirmed, possibly all versions having the block editor.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
> Gutenberg is using turbo-combine-reducers (a not maintained package since 4 years): https://github.com/aduth/turbo-combine-reducers/blob/master/index.js#L25

The maintainer of this one is a former contributor to Gutenberg (one of the top contributors), so there's probably some scope to change this package or move to a different solution.

> Another one is directly in Gutenberg: https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/utils/parse-css-unit-to-px.js#L27

I think this is used on the React Native project. It doesn't seem used by the web version of the block editor. It was introduced in https://github.com/WordPress/gutenberg/pull/34186. Unfortunately it seems to be exported from the `@wordpress/block-editor` npm package as a public API, plugins can use it (try `wp.blockEditor.getPxFromCssUnit` in the console), so it seems like it'll still need to be fixed.

**Comment by gziolo** [comment]
> The block editor uses in several places unsafe Javascript (amongst others the Function object) that prevents usage of secure CSP without allowing unsafe code. 

> > Gutenberg is using turbo-combine-reducers (a not maintained package since 4 years): https://github.com/aduth/turbo-combine-reducers/blob/master/index.js#L25
>
> The maintainer of this one is a former contributor to Gutenberg (one of the top contributors), so there's probably some scope to change this package or move to a different solution.

It was a design decision to use the Function object in `turbo-combine-reducers` to achieve 82x improved performance over what Redux offered at that time. We should evaluate alternatives and ensure that it doesn't impact the performance of the editor.

Aside: I don't think that this library needed any updates in the last 4 years as it does a single thing that was extremely optimised.

**Comment by jornfranke** [comment]
I understand the motivation and the decision that was made years ago was probably valid at this time, but many enterprises nowadays want to enforce more strict CSP, which is also justified. One can look at different things  - is this library in any case needed, for what is it used in Gutenberg? Do you still have the code that it replaced due to higher performance?

**Comment by gziolo** [comment]
>  Do you still have the code that it replaced due to higher performance?

Sure, it's `combineReducers` from `redux`. (https://redux.js.org/api/combinereducers)

**Comment by jornfranke** [comment]
Maybe this will help: https://github.com/reduxjs/redux/blob/master/docs/usage/structuring-reducers/BeyondCombineReducers.md
Also it seems that the code was also rewritten - not sure if this improves performance nowadays, but might be worth a try: https://github.com/reduxjs/redux/blob/master/src/combineReducers.ts#L125

**Comment by mcsf** [comment]
I understand why browsers would flag this as unsafe code, though I'm not worried about `turbo-combine-reducers`.

Personally, I'm more concerned with occurrences like [parse-css-unit-to-px.js#L27](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/utils/parse-css-unit-to-px.js#L27), where the attack surface is larger and we should be more conservative in the input.

Now, the case of `turbo-combine-reducers` is more contained, and the library underpins all state changes in Gutenberg. It doesn't handle free-flowing data or user input; instead, it receives the application's own reducer structure. Even then, the only attack vector I can think of would be maliciously crafted object keys, e.g.

```js
combineReducers( {
  'some " weird {} ; key': function() {},
} )
```

Mitigating that should be simple enough: validating the `keys` right upon initialisation of `combineReducers` and throwing an error if any key looks strange.

> Maybe this will help: https://github.com/reduxjs/redux/blob/master/docs/usage/structuring-reducers/BeyondCombineReducers.md

I read that document, and we are using `combineReducers` as intended.

> Also it seems that the code was also rewritten - not sure if this improves performance nowadays, but might be worth a try

I doubt that any performance gains there would be a match for Andrew's 82x improvement, but I agree that we should nevertheless do a new comparison.

**Comment by jornfranke** [comment]
I understand that it might be more complex. I am skeptical about validation - first we will never find all possible strange keys (cf. for instance WAF rules for Log4shell - it is up to now impossible to find one that covers all cases of Log4Shell and also security experts say it is impossible). I think also validation rules will significantly hamper performance itself with little benefit related to security int his case. Then, if combinedReducer has the application's own reducer structure then I believe there is a very good chance that it contains free-flowing user input and there is the risk that further of such input might be accidentally introduced in the future in some other parts of the application by a developer not aware or forgetting about this or by a plugin. 

Nevertheless, even if we currently think the attack surface is low for combinedReducer - it will not work with a strict CSP activated (especially unsafe-eval is one of the first from my experience enterprise would want to activate), which is a blocker for more and more enterprises in the future. 

We need to find a good way to replace it which is not blocked by a CSP - they set the CSP for a good reason.

Btw. the Vega Visualisation Grammar had originally also Function objects and they thought having an own CSP compliant parser would hamper performance or not cover all cases, but in the end it was not really problematic.
One could here also have a default option UNSAFE_EVAL = true that needs to be activated to used combinedReducer with Function and UNSAFE_EVAL = false for the replacement (which may be slower). UNSAFE_EVAL = FALSE should be then default in a future minor version.

**Comment by aduth** [comment]
While a performance hit would be undesirable, I'd also lean generally toward reverting back to the default Redux `combineReducers`, since I think a standard Content Security Policy configuration should at least be supported by Gutenberg, and any use of arbitrary code evaluation should be avoided if a reasonable alternative exists.

It's been a while since I've been involved in this project, but is there a straightforward way to test to see what that performance impact might be? The existing benchmarks are quite old, so I wouldn't be surprised if browser optimizations have changed the landscape. And since `turbo-combine-reducers` was designed to be a drop-in replacement, it shouldn't require much effort to adjust the implementation to use `redux` instead.

**Comment by mcsf** [comment]
(Oh hey, @aduth!)

Btw, this seems like something to be on @tyxla and @jsnajdr's radar.

> I'd also lean generally toward reverting back to the default Redux `combineReducers`, since I think a standard Content Security Policy configuration should at least be supported by Gutenberg, and any use of arbitrary code evaluation should be avoided if a reasonable alternative exists.

Right, this is hard to refute. It would be interesting to not just run an updated benchmark against Redux's implementation, but to (re-)profile Gutenberg's state update cascade to assess the real cost of `combineReducers` amidst the cascade. Depending on those two metrics, we could either entirely switch to Redux's implementation, or — if the performance penalty is too important — make the CSP-ready alternative an option for site admins.

**Comment by jornfranke** [comment]
Can you link already an issue/pullrequest by them on this topic? Thanks!

**Comment by tyxla** [comment]
We haven't had the chance to make progress on this one yet. I think @flootr might also be interested in taking a look.

**Comment by BowFarmer** [comment]
I may be running into the same issue on the admin pages. I created a mu-plugin that adds a robust CSP to the front facing pages of my Wordpress site. Using the 'template_redirect' and 'rocket_buffer' hooks (because I use WP Rocket), I am able to scan the generated html, create hashes for all inline scripts, and make a script-src CSP specifying these allowed hashes. The CSP blocks any other inline scripts from running.
I'm now trying the same on the admin side, and the only remaining problem I have that makes me use 'unsafe-eval' on the admin side CSP, is a new function call inside /wp-includes/js/dist/data.min.js. It is also inside /wp-includes/js/dist/data.js. I'm told that this is a Gutenberg issue and that block editing will not work without /wp-includes/js/dist/data.min.js.
This issue seems to have been pointed out several years ago and is still not fixed. I find it puzzling that no one seems to be taking this seriously.

**Comment by BowFarmer** [comment]
Since this is an issue affecting the block-editor, a CSP safe version, even if it is slower, would be fine with me. I prefer security over speed. What I don't comprehend is why this security hole is still around years after it was pointed out. I find people complaining about it three years ago.

**Comment by tyxla** [comment]
We're still interested in getting this one addressed. I know @jsnajdr was interested in taking a look at it.

**Comment by tyxla** [comment]
@jsnajdr started working on a potential solution in #54606.

**Comment by jornfranke** [comment]
I still see in Wordpress 6.4.2 that unsafe Javascript is used. Does it not include this Gutenberg release?

**Comment by tyxla** [comment]
> I still see in Wordpress 6.4.2 that unsafe Javascript is used. Does it not include this Gutenberg release?

Unfortunately, WordPress 6.4 includes Gutenberg 16.2 to 16.7 and the fix didn't make it into the release as it was part of Gutenberg 16.8 and we didn't specifically cherry-pick it into the release. It will be part of the next major WordPress release though.

**Comment by jornfranke** [comment]
Confirmed, it is in Wordpress 6.5 and I can now define a CSP without unsafe-eval. Great work - Thanks a lot!

**Comment by BowFarmer** [comment]
Great! Now I can finish my admin side CSP.

**Comment by jornfranke** [comment]
I wrote also a small overview on how one can do this: https://jornfranke.codeberg.page/technology-tutorials/wordpress-csp/

**Comment by BowFarmer** [comment]
Hi Jörn,

Thank you for the link. It is informative and helpful.

On Apr 14, 2024, at 11:05, Jörn Franke ***@***.***> wrote:
I wrote also a small overview on how one can do this: https://jornfranke.codeberg.page/technology-tutorials/wordpress-csp/

So what I do is look at the final html before WordPress sends it back. I look for all inline scripts and calculate hashes for them and add those hashes to my CSP.

On the front end my CSP ends up looking like this with all the allowed script hashes:

base-uri 'self' p8x8w4j8.rocketcdn.me challenges.cloudflare.com checkout.clover.com ;
object-src 'none’;
script-src 'self' p8x8w4j8.rocketcdn.me challenges.cloudflare.com checkout.clover.com data: 'sha256-77WmSGVq6PlE+/dOVkQSZGQWCrUBl6KIyLWH507dV1o=' 'sha256-M1etSTsLTYyio9eWYa4749eeV1vBu8wcRrvhuWcZKC4=' 'sha256-7y9/KNsyJQGWriyCQmEaf3FZwqU52r1AuCBxscB1YcY=' 'sha256-hmgfyXY6AzlJeRWqm+bMvB3XPWFuPrZX1muhIi+gtSc=' 'sha256-MTQk+ZugiSyMOmP4Z9xCUFM5CCHjf5UIyrv7RIN82oE=' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=' 'sha256-izUawXlqNDdXMuZkhAs2IbHXjUXDLoCHQNwTl6PzKkg=' 'sha256-JifyozaSM89dFYWoPUZeY3Sz3S/t5J/0HY1rFsIxq68=' 'sha256-1X+hmeDCSiqR5517YUrA2tiViPVS+yZYRp3WkC1g3vk=' 'sha256-A8P10y0WSvNDEFERE8AOaLoSXb/km+njslYccDvOCok=' 'sha256-eHL/Izx7K/qWL0kdBXXnHwsLSHvGOJn/THLHydUZdog=' 'sha256-C7CIpwSS5m3mXZcXJPPh/8geedELe6rTiB841eQdFZ4=‘;
style-src 'self' p8x8w4j8.rocketcdn.me challenges.cloudflare.com checkout.clover.com 'unsafe-inline’;

However on the admin side, I discovered there are several scripts that some pages include which call functions like ‘new Function()’ which browsers block if I don’t include ‘unsafe-eval’ in my script CSP.

Browsers will display a message like: "Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Securit…"

So on the admin side, when I am looking at the final html, I check to see if block-templates/index.js (WooCommerce issue), underscore.min.js, and handlebars.min.jis are included as those scripts will not run without ‘unsave-eval’. So many of my admin pages do not need ‘unsafe-eval’ and some do.

At one point I was creating nonces for all inline scripts, but I switched to using hashes because with nonces I had to change the final html and write nonces into each inline script. With hashes I just need to calculate them. Browsers will calculate hashes for inline scripts they see and check if those hashes are in the CSP.

This is how I make those hashes:

function make_csp_hashes( string $page_html, string $extra_script_rules ) {

	$uris = ' p8x8w4j8.rocketcdn.me challenges.cloudflare.com checkout.clover.com ';

	// Create a hash from the content of each <script></script> and put a list of allowed hashes
	// into the CSP.

	$hashes_a = array(); // array of hashes for inline scripts.

	$page_html = preg_replace_callback(
		'#<script.*?>(.*?)<\/script>#s',
		function ( $matches ) use ( &$hashes_a ) {
			$script_content = $matches[1]; // Extract the content between the script tags.
			// phpcs:ignore
			$hash       = base64_encode( hash( 'sha256', $script_content, true ) ); // Compute the SHA-256 hash and encode it in Base64.
			$hashes_a[] = "'sha256-" . $hash . "'"; // Add the hash to the list with the 'sha256-' prefix.
			return $matches[0]; // Return the original script tag unmodified.
		},
		$page_html
	);

	// Now $hashes_a contains the hashes for the inline scripts, and can be included in the CSP header.

	// Reduce the array so that each hash only appears once.
	$hashes_a = array_unique( $hashes_a );

	// Make a string with a list from hashes.
	$header     = '';
	$hashes_csp = array_reduce(
		$hashes_a,
		function ( $header, $hash ) {
			return "{$header} {$hash}"; // Note the space between the quotes to separate the hashes.
		},
		''
	);

	// Set our CSP header.
	header( sprintf( "Content-Security-Policy: base-uri 'self' %1s;object-src 'none';script-src 'self' %2s %3s %4s;style-src 'self' %5s 'unsafe-inline';", $uris, $uris, $extra_script_rules, $hashes_csp, $uris ) );
}

When creating the CSP for the admin side, I also check for these things and include the result of $extra_script_rules in the CSP:

if (false !== strpos($page_html, 'block-templates/index.js') || false !== strpos($page_html, 'underscore.min.js') || false !== strpos($page_html, 'handlebars.min.js')) { $extra_script_rules .= " 'unsafe-eval' "; }

Since the CSP is created dynamically for every page, if some plugin changes and modifies an inline script, the CSP that gets created will work for the new or modified script.

What was very difficult to figure out is how to capture the final html before WordPress sends it out. I use WP-Rocket and after days of trying to get it to work, I contacted them and they told me that I had to hook into their filter ‘rocket_buffer’. If I hooked into that filter I would see the final html for pages they optimize.

Depending on what optimization plugin sites use, the process to see the final html before it is returned will be different.

add_filter(
	'rocket_buffer',
	/**
	* Callback function to modify output before it is sent to the browser.
	*
	* @param  string $page_html The output to be modified.
	*
	* @return string The modified output.
	*/
	function ( $page_html ) {

		make_csp_hashes( $page_html, 'data: ' );

		// Debugging header.
		header( 'X-CSP-set-by: rocket_buffer;' );

		return $page_html;
	},
	100
);

There are frontend pages WP-Rocket does not handle, so I hook into ’template_redirect’ to handle those pages.

For the admin side, I hook into ‘admin_init’ to capture the final output before it is sent out.

add_action(
	'admin_init',
	/**
	* Callback function to modify output before it is sent to the browser.
	*
	* @param  void
	*
	* @return string The modified output.
	*/
	function () {

		if ( ! is_admin() ) {
			return;  // Exit the function if not on an admin page.....
		}

		global $wp;

		$requested_url = $wp->request;

		header( 'X-CSP-set-by: admin_init;' );

		ob_start(
			/**
			* Callback function to modify output before it is sent to the browser.
			*
			* @param  string $output The output to be modified.
			*
			* @return string The modified output.
			*/
			function ( $output ) {

				global $wp;

				$output_length = strval( strlen( $output ) );

				make_admin_csp_hashes( $output, '' );

				return $output;
			}
		);
	},
	PHP_INT_MAX
);

I’ve had the dynamic CSP generator for my frontend pages for a year now and it works great. I am stil testing the CSP generator for the admin side. It is working well now that I figured out which scripts need ‘unsafe-eval’ and which ones do not.

Daniel

**Comment by jornfranke** [comment]
Thanks, with Wordpress 6.5 there should be no page anymore needing unsafe-eval and it can be deactivated.

**Comment by BowFarmer** [comment]
Thank you.
