### ISSUE TITLE
Button element causing errors in Editor since Gutenberg 13.7.x

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#42649]
### Description

Since upgrading to Gutenberg 13.7.x, errors are now being thrown in both the post Editor and the Site Editor. Screenshot below. 

The button element code I have been using for testing is:

```
		...
		"elements": {
			"button": {
				"spacing": {
					"padding": {
						"top": "0.8em",
						"right": "1.2em",
						"bottom": "0.8em",
						"left": "1.2em"
					}
				}
			},
			...
```

### Step-by-step reproduction instructions

1. Use Twenty Twenty-Two or similar block theme. 
2. Add the code above in theme.json
3. Open the post Editor and see the error (need debug on of course)

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/4832319/180576105-6e25d332-11fa-4e2d-8c37-9b3123d072ef.png)

### Environment info

- WordPress 6.0.1
- Gutenberg 13.7.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
@scruffian and @getdave, pinging you both on this since I believe you have been working on the button element.

**Comment by getdave** [comment]
I believe @scruffian is now looking into this.

**Comment by scruffian** [comment]
This is a tricky one. The problem comes from core not correctly checking that a key exists before trying to access it. I have proposed a fix for this in core here: https://github.com/WordPress/wordpress-develop/pull/3026, but this probably won't get into a release any sooner than 6.1, and in 6.1 we'll have the newer version of the Theme_JSON which already avoids this by iterating over the elements array specified in the class.

An alternative approach is to override the functions that core calls to use the Gutenberg versions, but one of these is `get_block_editor_settings` which is called from `edit-form-blocks.php` and I can't find a good way to override that...

**Comment by ndiego** [comment]
@scruffian the strange thing is that these errors do not display in Gutenberg 13.6, only in 13.7. Since the button element worked in 13.6, this led me to believe something changed in 13.7 that's causing this. That's just a guess though 🤷‍♂️

**Comment by hz-tyfoon** [comment]
Hey @scruffian, 
I've checked your PR https://github.com/WordPress/wordpress-develop/pull/3026
Looks like the PR contains another error. I've added some comments there. please check. 🙂

**Comment by hz-tyfoon** [comment]
hey @ndiego ,

I've checked this with gutenebrg 13.6 & U're right. There's no php notice with 13.6
But, looks to me the issue was with 13.6 because, with that version the `get_style_nodes()` function wasn't picking up the contents of the `theme.json` file which it should.

But in the latest gutenebrg release, the `get_style_nodes()` function is picking them up properly & that's why the php error notice was shown.

**Comment by scruffian** [comment]
Since this has a core patch now I'm not sure there's much more we can do here, so I'm going to close this.
