### ISSUE TITLE
Fluid typography in theme.json loads just the default size in the site editor

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#42680]
### Description

When you use the fluid typography API recently introduced in Gutenberg, the min and max settings are ignored in the editor and it just loads the default value.

### Step-by-step reproduction instructions

1. Add a new fluid font size in your fontSizes array (`settings.typography.fontSizes`) in `theme.json` and save.
```json
  {
      "size": "1.3rem",
      "fluid": {
          "min": "1.3rem",
          "max": "2.5rem"
      },
      "slug": "default-title",
      "name": "Default Title"
  }
```
3. Set the fonstSize for a block in your theme.json (`styles.blocks`).
```json
"core/post-navigation-link": {
      "typography": {
          "fontSize": "var(--wp--preset--font-size--default-title)"
      }
  }
```
3. Open the editor and add a block to a template and save.
4. Save and navigate the frontend. The block should have a fluid font size.
5. Reload the editor and verify that the font size of the block is NOT fluid.

### Screenshots, screen recording, code snippet

Frontend:
![image](https://user-images.githubusercontent.com/1310626/180830315-a14f0135-8ea0-4513-9348-8efdb081b3b7.png)

Editor:
![image](https://user-images.githubusercontent.com/1310626/180830737-eba597ce-fbe4-4a92-9b69-054fccb74732.png)

### Environment info

- Wordpress 6
- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by pagelab** [comment]
Did you add `"fluid": true,` to `settings.typography`? I can reproduce this issue only if it is removed.

**Comment by matiasbenedetto** [comment]
> Did you add "fluid": true, to settings.typography? I can reproduce this issue only if it is removed.


Hi @pagelab, thanks for testing. Please try using the template editor as suggested in the step-by-step reproduction instructions.

This seems to be working fine on the post editor but failing on the template editor (Appearance -> Editor from the WP sidebar menu).

**Comment by pagelab** [comment]
I see. I confirm, it's not working in the template editor, just in the regular post editor.

**Comment by ramonjd** [comment]
Thanks for registering this bug. 

It appears to be an existing bug, unrelated to the fluid typography changes, whereby the font size presets are printed twice to the page:

1. In a style tag in the document's head (`global-styles-css-custom-properties-inline-css`). The presets are printed _before_ any processing takes place.
2. And again, at the bottom of the page, in `wp.editSite.initializeEditor`, where the processing has taken place and the clamp values are visible.

The former, at least in the template/site editor, are taking precedence over the latter.

It looks like it's a bug with any preset that defines its value via a [value_func](https://github.com/WordPress/gutenberg/blob/83d17c898e3cb1c7738cba0adaa643557794ca7f/lib/compat/wordpress-6.1/class-wp-theme-json-6-1.php#L1054). So duotone is exhibiting the same behaviour.

The fluid typography changes do highlight the need for this to be addressed. I'll take a look and see if I can hunt down the cause.

_Edit_: Oh, it looks like we also need a [JS version](https://github.com/WordPress/gutenberg/blob/87cdeb311dda6c54ec207a4567a414598342f5e6/packages/edit-site/src/components/global-styles/utils.js#L61) of the fluid font size algorithm **for the site editor only** (because it's in an iframe)
