### ISSUE TITLE
Provide a way for a pattern to be directly swapped for a different pattern

### ISSUE THREAD

**Issue by Andrew-Starr** [WordPress/gutenberg#42771]
## What problem does this address?

While recently showing someone how to insert a pattern into a page, they turned to me with the question "can I change this pattern for another pattern?"

As it is now, this would require removing all of the blocks that make up the previously added pattern, and then adding the other pattern.

Once a pattern has been added, this collection of individual blocks loses its "patternness", and so directly swapping it for another is not possible.

## What is your proposed solution?

Perhaps the Group block could have an additional attribute that would let us define a custom pattern area, perhaps in the Advanced section similar to how we can write HTML anchor.

Patterns with the same area attribute on the group container could then be swappable in the editor. This part I'm not sure exactly how it would work. Maybe a control in the Group block toolbar that would let us preview and select a different pattern that has the same defined area attribute.

**Comment by mtias** [comment]
Thanks for the suggestion! Closing as duplicate since this is captured in these two issues:

- #39281
- #27575

It's an important part of the patterns roadmap — transforming patterns into other patterns, having collections / variations of patterns for an area like we do for headers, footers, queries.
