### ISSUE TITLE
[Pattern Inserter] Make category selection and explorer sticky at top of sidebar container.

### ISSUE THREAD

**Issue by BE-Webdesign** [WordPress/gutenberg#42833]
## What problem does this address?
When lists of patterns are long. As you scroll down a list the ability to switch category or open the pattern explorer gets tucked away at the top of the sidebar. If it was sticky, one could easily scroll through patterns and then change category, or open the explorer. Below is a video illustrating the issue:

https://user-images.githubusercontent.com/16389612/181989319-15d78739-05d5-49f1-afb5-fa1c1d94e026.mp4

## What is your proposed solution?
Add some `position: sticky` CSS magic, so the dropdown and button are at the top of the list always.

**Comment by ndiego** [comment]
Hi @BE-Webdesign, this issue came up today in the Editor Bug Scrub. Thank you for your feature request. Due to the recent changes coming in WordPress 6.2 that redesigned the patterns panel, this request, while a great one, is no longer relevant. Therefore, I am going to go ahead and close this issue. Thanks!
