### ISSUE TITLE
Copy and Export a Post

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#4284]
One drawback of composing all content via blocks is that the ability of copying and moving a full post can become a bit harder. We support Cmd+A and Cmd+C if you are not focused on a block.  I think we can, in addition, offer some clear tools for this in the ellipsis menu while at the same time exposing keyboard shortcuts for quick copy-all.

![image](https://user-images.githubusercontent.com/548849/34565308-9ec160c8-f15a-11e7-8692-c7e5c5e1677b.png)

Furthermore, we could consider having a "Export as..." menu there for quickly generating a plain text file, or an HTML doc for the post, etc.

**Comment by karmatosed** [comment]
I like this as an idea. I can imagine this could be good for things like sharing blocks too.

**Comment by iseulde** [comment]
@jasmussen and I also discussed making cmd+a work to select all content. If a block is selected without any input fields, it would select all content as it does now. If the focus is inside an input field, it would first select all content in that field, and a second time would select all blocks.

**Comment by iseulde** [comment]
This is still a good shortcut in addition of course.

**Comment by mcsf** [comment]
Technically, how would the copying itself happen? Per the latest _Clipboard API and events_ W3C [draft](https://w3c.github.io/clipboard-apis/#clipboard-event-interfaces), a pure Web-events-based operation isn't expected in the future:

> Note: Synthetic clipboard events will not actually modify the clipboard or the document. In other words, while the script above will fire a paste event, the data will not be pasted into the document.

Out in the wild, buttons that need to be clicked in order to copy data (e.g. copying a repository's URL from its GitHub page) are a common sight. Historically, these would require hacks, one way or another: a common solution was to [use Flash](https://github.com/zeroclipboard/zeroclipboard/). 🙈 

Enter `document.execCommand` and its `copy` command. This seems to be the _de facto_ standard invocation to write to the clipboard. Its notable characteristic is that it doesn't accept arbitrary data (_à la_ `clipboardData.setData`) and instead relies on document selection. Uses on the Web include the practice of creating a `textarea` on the fly, injecting text into it, selecting the element, triggering the `copy` command, then destroying the element. This is a possibility, along with simply relying on Gutenberg's own block selection abilities. For its simplicity, I explored the latter in [branch `update/copy-from-ellipsis`](https://github.com/WordPress/gutenberg/compare/update/copy-from-ellipsis?expand=1); it works in Firefox and Chrome, but not in Safari.

Are there other methods we should be thinking of for this?

**Comment by mtias** [comment]
> Uses on the Web include the practice of creating a textarea on the fly, injecting text into it, selecting the element, triggering the copy command, then destroying the element.

The textarea is already at hand for the "text" mode of the editor. (See also https://github.com/WordPress/gutenberg/tree/master/components/clipboard-button )

**Comment by mcsf** [comment]
> (See also https://github.com/WordPress/gutenberg/tree/master/components/clipboard-button )

TIL. I’m constantly surprised by this codebase.

**Comment by jasmussen** [comment]
@iseulde 

> @jasmussen and I also discussed making cmd+a work to select all content. If a block is selected without any input fields, it would select all content as it does now. If the focus is inside an input field, it would first select all content in that field, and a second time would select all blocks.

YES! I was thinking about this, and was sure we'd discussed this. But I can't find a ticket. 

I've also been thinking that it might be cool to have different behavior for multiple consecutive ⌘A's. Like ⌘A inside a paragraph selects all text in that paragraph, ⌘A again selects this paragraph at the block level, ⌘A again selects all blocks.

**Comment by mcsf** [comment]
→ Copying aspect implemented in #4323

**Comment by mtias** [comment]
Closing as done. I'll open one for "Export...".
