### ISSUE TITLE
Webfonts Performance: Add a filterable threshold to limit the number of enqueued fonts

### ISSUE THREAD

**Issue by hellofromtonya** [WordPress/gutenberg#42871]
Part of https://github.com/WordPress/gutenberg/issues/41479.

## Problem Statement

The enqueue process is unlimited, meaning an unlimited number of fonts could be enqueued.

Imagine a site uses a plugin that enqueues 50, 100, or more web fonts. What would happen to the website? It would negatively impact the user's experience and site's metrics and rankings.

What is the maximum number of font files to fetch from the web server before a web page's loading slows down too much to negatively impact users and site metrics and rankings? How many font files are too many? 3, 5, 10, 50?

## Scope

- [ ] Determine if Core should limit the number of enqueued fonts. Is it its job to have a threshold? Or is that the responsibility of extenders and site owners?

If there's consensus for Core to have a filterable threshold, then:

- [ ] Determine a maximum number of enqueued fonts. For example, this number could be set high but at the point where most websites would negatively be impacted by too many fonts.

- [ ] Determine how to alert users when there are too many.

**Comment by jonoalderson** [comment]
A few considerations...

- A reasonable theme might have 2 or 3 fonts; something for headings, something for body content, +1 (e.g., a brand typeset or icon font; though the latter are decreasing in popularity and usage).
- A font might reasonably use 2 or 3 files; a couple of weights, and a specific heavy/italic treatment.
- A site with international content (or complex language) might split out the glyphs for language subsets; resulting in 5-6 resources per font.

That makes setting a sensible limit difficult, as the above would already need to account for 3*3*6 (50+) files.

However...
- Not all _enqueued_ fonts are _loaded_ (and browsers are generally smart enough to only request the font file if/when a visible element is styled with it). There's _very little_ overhead in over-enqueueing, as long as stuff isn't used on the page.
- Browsers are getting better at synthesizing 'inbetween' weights and styles; so there's less need to enqueue multiple similar weights (and sometimes, no need to enqueue italic fonts at all).

In the wild, it's usually problematic when a page loads more than ~3 font files. But we're missing the mechanics to understand what's _used_, rather than what's _enqueued_?

In which case, this might not be achievable at this stage :(

**Comment by aristath** [comment]
> Imagine a site uses a plugin that enqueues 50, 100, or more web fonts. What would happen to the website? It would negatively impact the user's experience and site's metrics and rankings.

If a plugin enqueues that many webfonts, then it's an extremely bad plugin (or theme).
It would be the same if a plugin enqueued 100 JS or CSS files, and we don't limit those for good reason. A plugin is allowed to load 200 scripts and 500 stylesheets. It's not illegal to do so, but it's just a bad implementation and these slowly die out. Let nature take its course... 😅 

I agree with @jonoalderson above... I don't think we should limit them. It would be difficult if not impossible to determine which font-families to load and which ones not to. If we attempt to make it "too smart" there's a higher risk of doing the wrong thing in Core.

**Comment by colorful-tones** [comment]
> Not all enqueued fonts are loaded (and browsers are generally smart enough to only request the font file if/when a visible element is styled with it). There's very little overhead in over-enqueueing, as long as stuff isn't used on the page.

💯 

A common misconception is that `@font-face` is what triggers a font to be downloaded. However, it is not until the font is used that it actually called, e.g. `h1, h2, h3, h4, h5, h6 { font-family: "Open Sans"; }`

> Let nature take its course...

💯

**Comment by simison** [comment]
Are there plans to improve UX to warn users about performance impact of using too many fonts at the site? Seems like education might avoid the need for backend filtering entirely.

Theme utilizing dozens of fonts on the other hand should probably be screened out from the Theme repository in first place.

**Comment by aristath** [comment]
> Are there plans to improve UX to warn users about performance impact of using too many fonts at the site? Seems like education might avoid the need for backend filtering entirely.

Fonts are just another asset - just like css files or JS scripts.
WP doesn't limit the number of assets loaded or warn when a plugin or theme loads too many of those files, so I don't think we should do that for font assets. 

I agree that loading 10 fonts would be a bad thing, but IMO if a theme/plugin does something like that, then it's probably a poorly designed product and these tend to not last long.

**Comment by hellofromtonya** [comment]
I'm closing this issue.

Why? As @aristath mentioned, the decision of how many fonts is not for the Fonts API to decide. WordPress doesn't throttle the number of css or script assets. 

And with the coming [font management](https://github.com/WordPress/gutenberg/issues/45271) and user workflows through the [Font Library](https://github.com/WordPress/gutenberg/pull/50927), users are in control of what global fonts they want to "activate" on their site.

I agree this is not an issue to be solved in the Fonts API.

Thank you everyone for contributing!
