### ISSUE TITLE
Template names for specific entities can get confusing when the entity is renamed

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#42894]
This came up in https://github.com/WordPress/gutenberg/pull/42165.

When you create a template for a specific entity, its name is used to define the template name. For example if you create a template for your post 'Hello World!' the template will be named 'Post: Hello World!'.

If you change the title of that post, the template name is not updated to match. This can make identifying templates difficult over time.

Let's discuss ways we can make the names for these templates dynamic, so that they update in lock-step with the source entity.

cc @jorgefilipecosta @ntsekouras

**Comment by mcsf** [comment]
Could this become a blocker for 6.1 if not addressed? @mtias @priethor

**Comment by jorgefilipecosta** [comment]
I think the simple fix would be not to store hard-coded names on the template name and description and instead leave them empty. If they are empty, the rest endpoint would dynamically compute names and descriptions based on the entities being referenced.
I think ideally, this would be addressed before 6.1 otherwise, on 6.1 we are going to store names and then even if we fix we still have confusing names for things already stored.

**Comment by priethor** [comment]
> I think ideally, this would be addressed before 6.1 otherwise

Agreed, I don't think it's a blocker, but it would definitely be terrific to address it before 6.1

**Comment by jameskoster** [comment]
Yeah it would be nice to eliminate any backwards compatibility headaches if we can 🙏

**Comment by jorgefilipecosta** [comment]
PR to fix this issue available at https://github.com/WordPress/gutenberg/pull/43862.
