### ISSUE TITLE
Site Editor: Root padding support in theme.json and no colors

### ISSUE THREAD

**Issue by Gierand** [WordPress/gutenberg#42913]
### Description

Adding support for root padding in theme.json causes no color rendering in the Site Editor.

### Step-by-step reproduction instructions

Depending on the setting in `useRootPaddingAwareAlignments` in theme.json, follow the video demonstration below.

### Screenshots, screen recording, code snippet

**Before:**
```
"settings": {
   "useRootPaddingAwareAlignments": false
}
```
![before](https://user-images.githubusercontent.com/1615208/182562815-ca60c0b7-9d2a-4fa3-81b3-7cb6877b8f08.gif)

**After:**

```
"settings": {
   "useRootPaddingAwareAlignments": true
}
```

![after](https://user-images.githubusercontent.com/1615208/182562842-a0733ef9-41bf-4984-ab33-259779a6792e.gif)

### Environment info

WordPress version: **6.0.1** and **6.1-alpha-53810**
Gutenberg version: **13.9.20220731**

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by tellthemachines** [comment]
Thanks for reporting this @Gierand !

I can reproduce the issue on trunk with Empty Theme. Looks like it's caused by [the early return](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-site/src/components/global-styles/use-global-styles-output.js#L257) after root padding variables are set.

It only happens in the editor though, not on the front end. Looking into a fix now.

**Comment by spencerfinnell** [comment]
Thanks for the quick fix. In case anyone else is searching as a result of a similar consequence, it was also affecting typography options like `fontWeight` and `lineHeight`. Confirmed fix on `trunk`.
