### ISSUE TITLE
Navigation block: Handle invalid ref IDs

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#42928]
## What problem does this address?
If a navigation block uses a ref ID, and the associated navigation CPT is deleted, the block won't be able to display the previously valid navigation CPT.

## What is your proposed solution?
In this case the block should behave in the way as an empty block would, falling back to another navigation CPT if one is available, or Page List if there are no navigation CPTs.

We should ensure the same behaviour exists in both the editor and the frontend.

**Comment by draganescu** [comment]
I think this is solved by #42735 because that PR adds this behavior:

- If a navigation block uses a block menu with ref X,
- and the associated navigation CPT is deleted, 
- makinf X point to nothing
- the block will display a message that the menu is deleted
- and invite the user to create a new one
