### ISSUE TITLE
useRootPaddingAwareAlignments does not work with padding that uses a single value

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#42978]
### Description

If I enable `appearanceTools` and `useRootPaddingAwareAlignments` and a root padding using a single value,
then the CSS for the global padding does not work because `--wp--style--root--padding-*` is empty.

### Step-by-step reproduction instructions

Add the following to theme.json:

```
{
	"version": 2,
	"settings": {
		"appearanceTools": true,
		"useRootPaddingAwareAlignments": true,
		"layout": {
			"contentSize": "840px",
			"wideSize": "1100px"
		}
	},
	"styles": {
		"spacing": {
			"padding": "100px"
		}
	}
}
```

Add a group block with layout enabled and with a full width image in either editor.
Save and view the front.
Confirm that the style `.has-global-padding > .alignfull ` is present, but the image is not full width.

Now change the padding to:

```
"styles": {
		"spacing": {
			"padding": {
				"top": "100px",
				"right": "100px",
				"bottom": "100px",
				"left": "100px"
			}
		}
	}

```
And confirm that the padding works correctly on the front, because now `--wp--style--root--padding-*` has the correct value.

### Environment info

WordPress 6.0.1
Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by tellthemachines** [comment]
I'm afraid that's the expected behaviour 😅 . If we support the shorthand value, we have to also provide support for scenarios like `padding: 10px 20px 15px`, and, at least for the initial implementation, we decided to skip that as the logic to support those values properly was getting very complicated. 

Other global styles settings don't really support them well either. We have #40132 to track that and work out a solution for all those scenarios. In the meantime, we just have to specify all the values individually 😞

**Comment by carolinan** [comment]
My expectation is then that it is documented better ;)

**Comment by tellthemachines** [comment]
Yes, it should be documented! I'm not sure whereabouts we should mention it though - given this is behaviour isn't in core yet. There will definitely be a dev note for the upcoming release, and then I guess it can go in the handbook together with the rest of the theme.json stuff?

**Comment by carolinan** [comment]
If we want new features to be tested before they are in core -which is one of the reasons why they are in Gutenberg first, they need to be documented before they are are in core.

**Comment by tellthemachines** [comment]
Yeah, that makes sense.

So this is an interesting one. It turns out that the [theme.json docs](https://developer.wordpress.org/block-editor/reference-guides/theme-json-reference/theme-json-living/#spacing-2) already specify that the general padding under styles should be an object with top, right, bottom, left properties. So officially we _shouldn't_ be using a string whether we have `useRootPaddingAwareAlignments` enabled or not. The fact that the string actually works if it contains only a single value was likely an accident 😭 

I guess we can add a note under the `useRootPaddingAwareAlignments` section (which I'll add shortly) saying that if this option is enabled, padding _has_ to be an object.

**Comment by tellthemachines** [comment]
Ok I've made  #43463 to address the documentation gap.
