### ISSUE TITLE
Cannot delete embeds with backspace

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#4299]
## Issue Overview
Unlike other blocks, I cannot delete any embed blocks with the backspace/delete key.

## Steps to Reproduce (for bugs)
1. Insert and select an embed block.
2. Press backspace.
3. Nothing happens.

## Expected Behavior
Block should be deleted.

## Current Behavior
Block is still there.
## Todos
- [ ] Tests
- [ ] Documentation

**Comment by aduth** [comment]
Related: #4011

It is probably the case that the iframe for the embed is "eating" the keyboard event, since it has the focus.

**Comment by karmatosed** [comment]
As reported in #6950 this is something impacts maybe beyond embed blocks and would be good to get the ability to delete.

**Comment by aduth** [comment]
FWIW there is handling for Backspace/Delete keys in `BlockListBlock` to delete the current block:

https://github.com/WordPress/gutenberg/blob/8e7682bed8dfec8430ed40eb434f66cf70217827/editor/components/block-list/block.js#L362-L372

It is, however, scoped to keypresses which occur directly on the focusable block wrapper, not any inputs within. This is important, of course, since a user pressing backspace to delete a bit of text in a block's input shouldn't trigger the block to delete itself. In the case of #6950, I have a counter-argument: If I insert a URL then hold backspace to delete the entered text, should the block eventually delete itself? Or would this be unexpected behavior when my intention is simply to reset the input to an empty value?

What are the blocks which fail these expectations? Can we enumerate them?

To the original issue, I think we ought to close this as a combination of "works as intended" and "won't (can't) fix".

"Works as intended" as in, when I insert an embed link and immediately press backspace, the block _is_ deleted:

1. Navigate to Posts > Add New
2. Click the "Write your story" prompt
3. Paste: https://twitter.com/i/moments/880688233641848832
4. Press Backspace
5. Note that the block is deleted

"Won't fix" as in, I'll make the claim that, due to [same-origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy), it is impossible to implement detection of a Backspace key event which occurs within an embed iframe, which is what I assume is meant by "select" in the original comment (i.e. clicking _within_ the frame). Happy to be proven wrong here.

With that in mind, I suggest we close the issue, and reopen if a proof-of-concept for iframe support can be demonstrated or we want to repurpose for other specific failing blocks.
