### ISSUE TITLE
Sketch file is missing fonts

### ISSUE THREAD

**Issue by field2** [WordPress/gutenberg#430]
When the sketch file is opened, I'm alerted that there are a bunch of missing fonts:
![missing_fonts](https://cloud.githubusercontent.com/assets/1656980/25064409/7c49a63a-21c7-11e7-9d6f-5eb7fd3e7380.jpg)

I installed some from google and apple, installed dashicons.ttf, but still getting missing font errors. Is there a repo of the fonts somewhere?

**Comment by jasmussen** [comment]
The SF UI fonts we can't legally provide links to, as getting them requires you being a registered Apple developer. This is ironic since the fonts are technically already installed on a Mac, but in a hidden place. So the bottom line is, unless you have those, we can't really do anything I'm afraid.

Are there any of the other fonts that are missing?

**Comment by field2** [comment]
Aha, ok. The other ones can be downloaded from google fonts, except for Merriweather (the version I download and install from Google fonts doesn't get the thumbs up from sketch for some reason) and dashicons (I had to get an older version; the one at the latest repo doesn't work)

**Comment by jasmussen** [comment]
There's a bug in Sketch where every font used is presumed needed, even if it isn't actually used anymore. The file should only actually need Noto and SF. I know the warning is annoying.

**Comment by jasmussen** [comment]
Closing this for now. It's still searchable in the repo and can serve answers to others looking.
