### ISSUE TITLE
Sub navigation font color doesn't work when background has color Gutenberg 13.8.1

### ISSUE THREAD

**Issue by lwangdu** [WordPress/gutenberg#43031]
### Description

After I updated Gutenberg 13.7.3 to 13.8.1 sub navigation font color doesn't work when background has color.

### Step-by-step reproduction instructions

Go to front page or site editor.
Click on sub navigation
I can't see font color but it works with Gutenberg 13.7.3. Please see the screen short
![Gutenberg 13 7 3](https://user-images.githubusercontent.com/24829573/183099151-d40a1f8c-a7d5-49b8-a4af-d7e5b78cbc8b.png)
![Gutenberg 13 8 1](https://user-images.githubusercontent.com/24829573/183099194-310541d8-8585-4cb9-b7ea-61881341ff94.png)
s

### Environment info

- WP 6.1, Gutenberg version 13.8.1 Theme TT2
- Browser chrome
- Mac book pro

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by getdave** [comment]
This seemed unusual to me so I took a look. To me this is expected behaviour. The Navigation text color is set to white and that is "inherited" by the submenus. As the submenu dropdown colour is white you cannot see the text.

However there is a control that allows you to change the submenu text color to something else.

Perhaps in older versions of the WordPress the inheritance wasn't working and then we corrected that. This is probably why this seemed like a bug.

https://github.com/user-attachments/assets/02faaaae-5ed5-4bd0-8912-fe1e1c0cd200
