### ISSUE TITLE
"Hide Advanced Settings" option does nothing

### ISSUE THREAD

**Issue by WPprodigy** [WordPress/gutenberg#4310]
## Issue Overview

If you click on the ellipses/more options at the block level for an image, there is a "Show Advanced Options" setting. Once clicked, the block-level settings will be toggled on in the sidebar.

If you go back and click "Hide Advanced Settings" though, nothing happens.

I also noticed some odd behavior with the button keeping it's active background color for no reason.

## Steps to Reproduce
Quick Screencast: http://cld.wthms.co/73sV3n

**Comment by afercia** [comment]
Seems to happen for any block, for example also paragraphs? This used to work and when clicking on "Hide Advanced Settings" the whole sidebar should close. See #3982

**Comment by WPprodigy** [comment]
Believe this can be closed, thanks to https://github.com/WordPress/gutenberg/pull/4332.

**Comment by WPprodigy** [comment]
Just tested, it is mostly fixed. However, it is still possible to replicate the option having an unnecessary background color after using it: http://cld.wthms.co/jfCBxX

**Comment by jorgefilipecosta** [comment]
> Ah, so the NavigableContainer component is causing it to focus the first button for accessibility reasons. Still strange though.

Either it auto-focusing the first is a bug, or there is a bug that occurs when opening the ellipses menu while the component isn't currently selected (because then the auto-focus doesn't occur).


Hi @WPprodigy thank you for your tests. It looks like the focus of the first does not occur when the block isn't currently selected because re-renders are triggered. And that is a different bug from the original one. I close this issue and create for that this one.
