### ISSUE TITLE
Inline images & text in a list can't be placed at top level

### ISSUE THREAD

**Issue by XVII** [WordPress/gutenberg#43106]
### Description

When trying to un-indent an inline image, it takes the entire dot point back from the second level. It's not possible to get the inline image to sit at the same level as "second paragraph"

This also applies to text -- i.e. if I wanted a paragraph below the second level dot points, but before "third item".

### Step-by-step reproduction instructions

See image for example list block structure.
Attempt to un-indent an inline image or text to top level (part of second item)

- first item
first paragraph
- second item
second paragraph
  - second level, first item
  - image
- third item
third paragraph

### Screenshots, screen recording, code snippet

![2022-08-10_14-01-28](https://user-images.githubusercontent.com/446329/183810167-97f31085-1716-4006-ab43-0a8ca048a625.gif)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
> When trying to un-indent an inline image, it takes the entire dot point back from the second level. It's not possible to get the inline image to sit at the same level as "second paragraph"

@ShadowXVII Isn't that because you've added another bullet point after the second paragraph? 

The image is part of that 'second level, first item' bullet point, just as 'second paragraph' is part of the 'second item' bullet point. If you want to unindent the image it'd have to have its own bullet point.

I don't think this is unusual, this is how lists work in my experience. For example, the exact same thing happens in Google Docs.

**Comment by XVII** [comment]
@talldan fair enough. I think my frustrations lie with how fiddly it is is more so the issue. Ugh even that bloody width box! :)

Let's close this and I'll reconsider my feedback.
