### ISSUE TITLE
[List Block V2] Text color inconsistencies in dark mode

### ISSUE THREAD

**Issue by hassaanelgarem** [WordPress/gutenberg#43146]
## Description
While in dark mode, the bullet/number is not white causing them to not be visible. And changing the indentation of an inner list block causes the text color to change.

## Step-by-step reproduction instructions

1. Enable List Block V2
2. Open editor in the WordPress app
3. Add a new list block
4. Create the following list:
    - One
    - Two
        - Three
    - Four
5. Switch to dark mode
6. Observe that the bullets are not visible in dark mode
7. Select the (Two/Three) block
8. Tap on the indent button
9. Observe that the text color changes

## Expected behaviour
Bullet points should always be visible, and text color should not change.

## Actual behavior
Bullet points are not visible in dark mode. And text color changes when indentation changes

## Screenshots or screen recording (optional)
<details><summary>First Issue Recording</summary>

https://user-images.githubusercontent.com/25306722/184133449-efe9b43e-191d-49c6-b2f6-7b5061967079.mp4

</details>
<details><summary>Second Issue Recording</summary>

https://user-images.githubusercontent.com/25306722/184133476-858cb443-864a-4ca6-97fb-1fe7f7385198.mp4

</details>

## WordPress information
- WordPress version: 6.0.1
- Gutenberg version:  13.8.1
- Are all plugins except Gutenberg deactivated? Only Jetpack is enabled
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Samsung Galaxy S22
- Operating system: Android 12
- WordPress app version: 20.5-rc-1 (1259)

**Comment by geriux** [comment]
Hey @derekblank 👋 could you take a look at this issue?

This is only affecting standard themes, for block-based themes it works correctly as we use the theme's colors and not the default light/dark ones.

We missed adding a default color for dark mode 😅 

Thanks!

**Comment by derekblank** [comment]
@geriux I took a look at this one, and I can definitely replicate it. I think you might have a better idea about what's really going on, though. 

When switching to dark mode, the black color for the list item comes from [list-item/styles.native.scss](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/list-item/style.native.scss#L27), which itself is being set in list-style-type.native.js:
https://github.com/WordPress/gutenberg/blob/0c2ce6d672d3491b54a5fa93c86212ad34ace58e/packages/block-library/src/list-item/list-style-type.native.js#L112-L115

When I log out the values of `style?.baseColors?.color?.text` (or even just the entire `style` object), it is always `undefined`, which is why it is defaulting to the black list item color.  Any ideas on why `style` might be undefined here, or the better way to set the default color to match the text color? 

Edit: I should mention that `style` is only undefined in list-style-type for standard themes (or when using the Gutenberg Mobile Demo app). As mentioned above, it works fine in block themes.

**Comment by geriux** [comment]
Thanks for taking a look!

>When switching to dark mode, the black color for the list item comes from [list-item/styles.native.scss](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/list-item/style.native.scss#L27), which itself is being set in list-style-type.native.js:

Yeah this is the issue, we need to have a `.wp-block-list-item__list-item--default--dark` for the default text's color for dark mode.

>When I log out the values of style?.baseColors?.color?.text (or even just the entire style object), it is always undefined, which is why it is defaulting to the black list item color. Any ideas on why style might be undefined here, or the better way to set the default color to match the text color?

This is `undefined` for standard themes, for block-based themes we are able to fetch the theme's colors through the block editor settings endpoint, when we have this data we pass it through a `style` prop to each block.

When the user has a block-based theme enabled we overwrite the default colors we have for the background of the editor, and text colors. So we won't have any issues with light/dark mode changes. For standard themes we do need to have both `light` and `dark` colors, in this case we missed adding the `dark` color variant for the new List V2 😅

**Comment by geriux** [comment]
Fixed with https://github.com/WordPress/gutenberg/pull/43244
