### ISSUE TITLE
Group Block gives no visual indication of HTML Element selected  

### ISSUE THREAD

**Issue by AlchemyUnited** [WordPress/gutenberg#43158]
### Description

When using the Group Block, there's nothing in the UI to quickly and easily understand which HTML Element type (e.g., div, section, article, etc.) is select from the Advance section (in the right sidebar) of the Block settings. 

- The List View gives no indication of the HTML Element Type

- And best I can tell, the block itself (i.e., markup) in the editor doesn't have anything (a data attribute?) for the HTML Element. That is, it's not even possible to - for example - add some admin CSS that adds a border to the group, and that border color maps to the HTML Element, <section> = red, <div> = blue, and so on.  

The only alternative seems to be to click on each group block. open the Advance tab (on the right) and see what HTML Element is selected. That's a lot of work for something like this. 

As user experience go, this feels like a Bug more than a missing feature.  

### Step-by-step reproduction instructions

Add a Group block. 

Pick the Element Type. 

Move to another block

Try to figure out the Element Type for the Group block(s). 

### Environment info

- I'm on the latest version of WP, *not* using the GB plugin. 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by andrewserong** [comment]
Thanks for opening this issue @AlchemyUnited! There's an existing discussion exploring this issue in https://github.com/wordpress/gutenberg/issues/42610 and a semi-related PR that's looking at improving the naming of blocks like the Group block in the List View: https://github.com/WordPress/gutenberg/pull/42605

I'll close this issue out as a duplicate, since it's already being discussed in #42610. But I think the idea of exposing the selected tag in the list view is a good one.

In terms of being able to target the particular block via admin CSS, in the block editor, the selected HTML element is used, so you could potentially use, for example, `article.wp-block-group` to target a Group block that uses the `article` element if you needed to.

**Comment by AlchemyUnited** [comment]
@andrewserong  - Hey. Thanks. Sorry I didn't see that other issue. I did look :) But apparently not enough :(

As for CSS and admin. Oh. I see. I was looking for a CSS class for the type along with .wp-block-group. I didn't notice that the actual element in the admin reflects the one selected for the group. Oops. Sorry. Thanks for pointing that out. I think it can help :)

**Comment by andrewserong** [comment]
> Sorry I didn't see that other issue. I did look :) But apparently not enough :(

No need to apologise, I miss existing issues _all_ the time. Thank you for taking the time to write up the issue! 🙂
