### ISSUE TITLE
Popover: rework props around shift, filp and resize behavior

### ISSUE THREAD

**Issue by ciampo** [WordPress/gutenberg#43191]
## What

Tracked in #42770

Currently, `Popover` exposes two props for tweaking its behavior when intersecting with the viewport's boundaries:

- `__unstableForcePosition`
- `__unstableShift`

However, it feels like these props don't offer the correct abstraction and actually limit the flexibility of the component.

## Proposed next steps

We could look at removing `__unstableForcePosition` and replacing it with separate `resize` and `flip` props, in order to be more aligned with `floating-ui`'s middleware options.

Bonus: we should also look at https://ariakit.org/examples/popover, and try to make a potential refactor of the component to `ariakit` as simple as possible

**Comment by talldan** [comment]
It turns out I didn't need this to fix the issue with legacy widgets (#43297).

But I can still push a PR that refactors this.

**Comment by talldan** [comment]
> Bonus: we should also look at https://ariakit.org/examples/popover, and try to make a potential refactor of the component to ariakit as simple as possible

Nearly forgot, I looked at how ariakit's popover works.

It seems like that uses a `fitViewport` prop, which I guess is roughly the same as `resize` (though I don't know if 'viewport' is correct, but maybe that's just a nitpick):
- https://github.com/ariakit/ariakit/blob/main/packages/ariakit/src/popover/popover-state.ts#L480-L487

And there's a `flip` prop:
- https://github.com/ariakit/ariakit/blob/ece71049c13908c58a638c3f069375b7f9311ad6/packages/ariakit/src/popover/popover-state.ts#L445-L463

So that may be another reason to still change the props.

**Comment by ciampo** [comment]
Thank you for the exploration!

> But I can still push a PR that refactors this.

That would be great!

**Comment by ciampo** [comment]
Reopening as the `shift` prop is still marked as `__unstable` — we should:

- add a new `shift` prop with the same default value of `__unstableShift`
- add a deprecation notice to `__unstableShift`

@talldan , would you be able to work on this? It should be a quick one.

**Comment by ciampo** [comment]
https://github.com/WordPress/gutenberg/pull/43845
