### ISSUE TITLE
Hamburger-style (overlay) menu items do not work when contains internal #anchor links

### ISSUE THREAD

**Issue by gOuTM** [WordPress/gutenberg#43205]
### Description

Hamburger-style (overlay) menu items do not work when contains internal #anchor links.  Everything works if overlay menu setting set to Off. But it is crucial for mobile view.

### Step-by-step reproduction instructions

1) Open editor to maintain corresponding navigation menu – for me that site editor, because my navigation is in the header of the site.
2) Add menu items that lead to an internal anchors. #submissionform — or whatever.
3) Set overlay menu option to "mobile". 
4) Now open the site from the mobile (I've checked both android and ios) and tap menu button.
5) Tap on the navigation item that contains an anchor link.
6) Close the menu.
7) Congratulations, you're on the same place where you were when you opened the site.

### Environment info

Wordpress 6.0.1, Guttenberg plugin installed but deactivated.
Twenty Twenty-Two theme, last available version

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

I believe this issue was fixed in #39625.
However, as noted in [this comment](https://github.com/WordPress/gutenberg/pull/39625#issuecomment-1161754913), this fix will be reflected in WordPress 6.1.
Alternatively, if you activate Gutenberg plugin 13.2 or higher, you can confirm that this issue has been resolved.

I would like to close this issue, but please re-open it if you have any problems 👍
