### ISSUE TITLE
[Create Block]: Add ability to pass a slug for the block name

### ISSUE THREAD

**Issue by ryanwelcher** [WordPress/gutenberg#43235]
## What problem does this address?
Currently, when scaffolding a block with the `@wordpress/create-block` package, we can pass a `slug` to define the name of the plugin, which is also used as the name of the block. This was brought up in https://github.com/WordPress/gutenberg/pull/41642#issuecomment-1213448794

```bash
npx @wordpress/create-block my-awesome-plugin
```

The command above would generate a plugin called 'my-awesome-plugin` with a block of the same name. There are many times that the name of the plugin will be different than the block.

## What is your proposed solution?
Introduce a new CLI parameter called `--block-name` to allow the command to function as follows:

```bash
npx @wordpress/create-block my-awesome-plugin --block-name custom-block
```

**Comment by ryanwelcher** [comment]
Now that https://github.com/WordPress/gutenberg/pull/41642 is merged, this parameter could be used to pass a series of names to allow scaffolding of multiple blocks at once
```bash
npx @wordpress/create-block --no-plugin --block-name custom-block-one,custom-block-two
```

**Comment by dgwyer** [comment]
> Now that https://github.com/WordPress/gutenberg/pull/41642 is merged, this parameter could be used to pass a series of names to allow scaffolding of multiple blocks at once

100% yes! I'm currently doing exactly this in a custom script I created. But I'd love to see it added as part of the `@wordpress/create-block` core script.

e.g. To create multiple blocks:

```
npx create-wp-block todo-list -b block1 block2 block3
```

https://github.com/dgwyer/create-wp-block

**Comment by gziolo** [comment]
I’m all in for adding support for multiple blocks. It might be quite challenging to achieve in the quick mode because there are a few CLI args that should differ between blocks:

https://github.com/WordPress/gutenberg/blob/a3c753d28ddb0972311e2da0136277626bdf832e/packages/create-block/lib/index.js#L40L50

`namespace` is the only CLI argument that we want to share and maybe `category` but `slug`, `title`, and `short-desc` should definitely differ between blocks and even often with the plugin.

**Comment by ryanwelcher** [comment]
Now that `--target-dir` is available for create-block, it's possible to define the directory separate from the block.

For example, 'npx @wordpress/create-block my-block --target-dir ./src/block-one --no-plugin` would scaffold a new block called `my-block` inside the`src/block-one` directory.

I think this makes this issue moot. I'm going to close this but happy to discuss it if anyone disagrees.

**Comment by michakrapp** [comment]
Still an issue, if you want to have the right command as script in your package.json, to create more blocks inside your existing plugin.
Because the `--target-dir` does not add the slug as folder when `--no-plugin`.

**Update**: I understand that the parameter was added to have a different folder name from the slug, but the ability for a subfolder from the slug would be cool.

Folder structure:
```
mu-plugins/
        my-blocks/
                blocks/                                // can be src if have to
                        block-one/
                                block.json
                        block-two/
                                block.json

```

If i wanted to create another block in that structure, I want to use my saved command like `yarn create-block block-three`
```
"create-block": "npx @wordpress/create-block@latest --target-dir blocks --no-plugin --category my-blocks --namespace my-blocks",
```

So without `--target-dir` it will create a folder in the plugin root `my-blocks/block-three` with the files in it.

If I add the subfolder path in the saved command like `--target-dir blocks` it will scaffold the files directly inside `my-blocks/blocks`.

So our other devs have to use it like
`yarn create-block block-three --target-dir blocks/block-three`
