### ISSUE TITLE
Changing number of Latests Posts rapidly leads to some numbers being defunct 

### ISSUE THREAD

**Issue by mboynes** [WordPress/gutenberg#4328]
## Issue Overview

This is best demonstrated through a video:

![latest-posts-cache](https://user-images.githubusercontent.com/465154/34615362-9f0bcb2e-f202-11e7-9a9e-2bd59642c130.gif)

When changing the number of posts in the Latest Posts block, some numbers appear to get cached using the results of other numbers. Therefore, for example, "7" may only show 2 posts, and there's no way to get it to actually request and show 7 without reloading the page. This appears to be a combination of API request races and caching.

This is on Chrome/Mac using the latest build of `master`. It _sort of_ happens on 1.9.1 -- though 1.9.1 appears to make a new API request with every change, so even though you may be on "4" but showing 2 posts, if you change to another number and back to 4, you might then get 4 posts.

This occurs in both list and column view, though it should be noted that #4276 currently prevents one from attempting this in column view.

## Steps to Reproduce (for bugs)

1. Insert a Latest Posts block
2. Change the number of posts at a moderate pace
3. When on master (currently d1df878), you might encounter a number that shows the wrong number of posts. When on 1.9.1, when you stop changing the number, as the API requests complete the displayed number of posts may jump around and eventually land on a number that's not what you're expecting.

Because there is a race condition involved, the results are sporadic. Sometimes when you try it, everything may work as advertised.

## Expected Behavior

The number of posts selected matches the number of posts displayed (as long as that many posts exist, of course).

## Current Behavior

The number of posts selected doesn't always match the number displayed.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by jorgefilipecosta** [comment]
Hi @mboynes thank you for your bug report 👍 
I was able to replicate this problem. It is very simple to replicate using the keyboard to change the number of posts. And it looks like we have the problem in the caching mechanism used by withAPIData.
<img width="697" alt="screen shot 2018-01-05 at 18 50 20" src="https://user-images.githubusercontent.com/11271197/34624549-a6457e6c-f24d-11e7-927d-0951bb712702.png">
<img width="1289" alt="screen shot 2018-01-05 at 19 01 46" src="https://user-images.githubusercontent.com/11271197/34624550-a6644090-f24d-11e7-8809-4d4d77eb5cc9.png">

The cache may save the body result of another request while the headers get always correctly saved in the cache (possible to see by link rel next). It looks like it is not a server/network problem because using the network inspector it looks like the correct body arrived.
cc: @aduth

**Comment by aduth** [comment]
Strange. I'm guessing it's not correctly tracking the received response to the originating request, and therefore caching the incorrect response in some cases. I'll plan to take a look.

**Comment by jorgefilipecosta** [comment]
Hi @aduth, I found a fix for this problem. Everything was right in withAPIData :) Sorry for my wrong analysis! The problem was that latest posts block was using a splice operation (instead of a slice one) on the data array passed to it, mutating the array. The array in the cache is the same array was the one passed as a prop so our cache got corrupted.
