### ISSUE TITLE
Duotone filter also applies to border on Image block

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#43295]
### Description

If an image block has a border and a duotone filter applied, the filter also alters the border color. This happens because both duotone and border styles are applied to the `img` element.

One possible solution would be to add the border styles to the figure instead, and to make sure the image doesn't break out of any border radius we could add `position: relative; z-index: -1` to it.

Edit: in the above scenario, the caption would appear inside the border. To fix that, we could absolutely position the `figcaption` and add some bottom margin to the `figure`. Caveats:
* This assumes spacing between blocks always uses the top margin, which it does in block themes via layout support. In classic themes it doesn't seem to be possible to add borders to images, so it may not be an issue.
* Adding margin only to a `figure ` that contains a `figcaption` might require support for [:has()](https://caniuse.com/css-has) to get better.

### Step-by-step reproduction instructions

1. Create an image block;
2. Add a border; 
3. Add a duotone filter.
4. Verify that the border color is changed by the duotone filter.

### Screenshots, screen recording, code snippet

Expected:

<img width="419" alt="Screen Shot 2022-08-17 at 3 07 47 pm" src="https://user-images.githubusercontent.com/8096000/185039448-bdf2d56f-4da1-4680-ba10-c5ea15ec4a7e.png">

Actual:

<img width="427" alt="Screen Shot 2022-08-17 at 3 07 22 pm" src="https://user-images.githubusercontent.com/8096000/185039442-11ea9e2d-b256-4814-8ba6-bd898b45d1d6.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jasmussen** [comment]
Whether expected or intentional or not, I'm afraid there isn't anything we can do here. So long as the border gets applied directly to the `img` tag, it will affect any borders or otherwise. The alternative would have to involve a wrapping container to set the border on that, which would likely reach a point of complexity to come with its own set of downsides. 

An alternative approach would be to provide some useful helptext in context of the design or border tools, which is output when a duotone filter is applied, explaining that the border is included in what gets filtered.

**Comment by mtias** [comment]
I think this is an ok tradeoff right now and not worth complicating the implementation further.
