### ISSUE TITLE
Discussion: Should Theme Export include plugin provided templates

### ISSUE THREAD

**Issue by DaisyOlsen** [WordPress/gutenberg#43448]
I've discovered that when a plugin that provides templates that are compatible with a block theme (SenseiLMS, WooCommerce, LifterLMS confirmed) are present and a theme is exported from site editor the plugin provided templates are included in the downloaded theme.

I'd like to encourage a discussion regarding whether or not all plugin provided templates should be included in the export or only those that have been modified in the site editor.

My reason for bringing this up relates to the possibility that there could be a risk of templates becoming invalid or increase confusion if a theme is created and subsequently installed on a site when no actual modifications have been made to those plugin provided templates.

**Comment by mburridge** [comment]
> I'd like to encourage a discussion regarding whether or not all plugin provided templates should be included in the export or only those that have been modified in the site editor.

My feeling is that if even a single plugin-provided template has been modified, then all templates provided by that plugin should be supplied in the export. So for example, if the single product template from WooCommerce is edited then presumably the theme is meant to support WooCommerce so all WooCommerce template files, e.g. basket page, checkout page, etc..., should be included in the export even if those ones haven't been changed.

**Comment by carlomanf** [comment]
My instinct is not only that it should be the plugin's responsibility to answer this question for its own case, but that it would be mostly futile for core to "mandate" it one way or another, since it probably would not be too hard for the plugin to "spoof" its templates as coming from the theme and thus get around the "mandate." There is currently not one official way for plugins to provide templates and each plugin may do it in a different way.

**Comment by juanmaguitar** [comment]
@DaisyOlsen Maybe we should convert this issue into a discussion? How could we move forward with this discussion?
