### ISSUE TITLE
Can blocks be made with other JS frameworks?

### ISSUE THREAD

**Issue by justanotherco** [WordPress/gutenberg#4344]
Is it possible (or will it ever be possible) to easily make blocks with other JS frameworks, such as Vue?

**Comment by youknowriad** [comment]
Did you try tools like this https://github.com/akxcv/vuera it should be easy enough.

**Comment by justanotherco** [comment]
That looks interesting, but is that the only way to create block with other JS frameworks? Will Gutenberg officially not support anything other than React?

**Comment by youknowriad** [comment]
@justanotherco That just my opinion and not an official Gutenberg or WordPress opinion. So, take it as is:

If we were to build an official support for another framework, we would build wrappers like `vuera` above. And since these wrappers already exist and are probably better maintained and developed than any custom wrapper we could offer, we should encourage their usage instead.

**Comment by martinszeltins** [comment]
I am also looking for a Vue.js support for creating blocks. It seems very unfair to be limited to only React. Vuera isn't perfect and there are some edge cases.
