### ISSUE TITLE
"Browse styles" in the global style sidebar does not always show

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#43554]
### Description

When a theme has theme.json style variations:
Normally I have to wait 15 seconds before the "browse styles" option is visible in the global styles sidebar. This feels too long.
But sometimes, it does not show up at all, and I have to refresh the site editor and wait again.

Tested in different themes, including Twenty Twenty-Three.

### Step-by-step reproduction instructions

I am not sure how to reproduce this consistently. I am using:
Mac
Chrome version 104.0.5112.101
Local by flywheel nginx, PHP 8.0.0, mySQL 8.0.16.
WordPress 6.0.1.
Gutenberg current trunk, no other plugins
Twenty Twenty-Three

A "classic" menu from the theme test data is used in the themes header navigation block.

1. Activate the theme
2. Open the Site editor
3. Open the global styles sidebar
4. Wait...

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
I haven't been able to reproduce the issue with it not appearing, but it doesn't seem ideal that it loads in asynchronously. It's probably also not great for accessibility, because there's a chance that a user may tab past it, not realising the button isn't present yet in the UI.

If it can't be loaded synchronously it should probably at least have a loading indicator and be focusable.

**Comment by colorful-tones** [comment]
I have noticed the lag in loading, and it is certainly long enough that it warrants attention. However, I have not experienced it not loading altogether.

**Comment by carolinan** [comment]
I have not experienced this in a long time, closing.
