### ISSUE TITLE
ViewScript in block.json does not work for dynamic blocks

### ISSUE THREAD

**Issue by Lovor01** [WordPress/gutenberg#43727]
### Description

Please see bug description on this [Trac ticket](https://core.trac.wordpress.org/ticket/56470)

Thanks!

### Step-by-step reproduction instructions

1. Create dynamic block
2. create javascript script and set viewScript in block.json to that script
3. script is not enqueued!

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by gziolo** [comment]
Thank you for opening the issue and linking the Track ticket. This should be addressed directly in WordPress core so let's continue the discussion there.

The short answer is, I agree it's confusing because it doesn't work like that for `script`. The best way to move forward is to allow customizations for assets in `block.json` as explained in [Trac#54018](https://core.trac.wordpress.org/ticket/54018#comment:5) and align the default behavior with `script`. This way, block authors could still opt in to defer to `render_callback` when the script should get enqueued.
