### ISSUE TITLE
Handbook: Add a way to ensure correct code markers are used

### ISSUE THREAD

**Issue by kdevnel** [WordPress/gutenberg#43758]
## What problem does this address?

I recently created a PR (#43185) to fix an issue on the Handbook, where there was a missing `{% end %}` marker.  It looks like this situation is quite easy to get into since there doesn't appear to be an easy way to ensure the correct opening and closing markers are used.

This content is processed and compiled after the changes are merged so you only see the result afterwards.

## What is your proposed solution?

I wonder if there is a way this _could_ be checked. Perhaps even an automated test of some kind that if an opening tag is used, there is a corresponding closing tag. 

Alternatively, if there are any tools available to the Handbook maintainers that they use to help with this, I couldn't find any documentation so it would be great to document this somewhere!

**Comment by ndiego** [comment]
This issue was reviewed in today's Block Editor Handbook Docs Scrub. We are working on improving the documentation around writing and reviewing docs PRs. Ideally, a technical solution would be great, and the limitations around previewing PRs make things more challenging, but better docs and a more thorough review process should alleviate these issues. Therefore, I am going to close this out, but if any contributor wants to explore building an automated solution, please don't hesitate to do so!
