### ISSUE TITLE
Project scaffolded by @wordpress/create-block does not enforce WordPress Coding Standards

### ISSUE THREAD

**Issue by mburridge** [WordPress/gutenberg#44095]
## What problem does this address?
The project scaffolded by `@wordpress/create-block` is consistent with the [WordPress Coding Standards](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/), but it doesn't enforce them in subsequent development.

If you deviate from the WordPress Coding Standards the linter will adapt, e.g. if you put double quotes around a string in a `.js` file in a newly scaffolded project and then save the file the linter will put double quotes around all the strings.

## What is your proposed solution?
I think simply adding:

`"prettier": "@wordpress/prettier-config"`

to the `package.json` file generated in the project will enforce the WordPress Coding Standards when a file in the project is saved.

**Comment by gziolo** [comment]
The issue is more nuanced and tracked in https://github.com/WordPress/gutenberg/issues/21872. One of the motivations of the [proposal to change WordPress Coding Standards for JavaScript](https://make.wordpress.org/core/2022/01/05/proposal-changes-to-javascript-coding-standards-for-full-prettier-compatibility/) was the ability to use the original Prettier that would resolve this issue. Unfortunately, this attempt failed because of the lack of consensus from WordPress core committers. The alternative approach to convenience Prettier's maintainers to add exception for the WordPress project https://github.com/prettier/prettier/issues/13107 has also stalled.

**Comment by gziolo** [comment]
I tested it again with Node v22.7.0 and npm 10.9.0. I scaffolded the block with `npx @wordpress/create-block@latest` to test it. It installed `@wordpress/scripts` v30.7.0.

I can't reproduce it anymore, so it must have been fixed upstream in the npm client.
