### ISSUE TITLE
Update spacing in exploded padding control

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#44121]
Part of https://github.com/WordPress/gutenberg/issues/43412

The current spacing is poor because the range is equidistant from the label before and after, which can make it hard to understand which control and which label are related:

<img width="262" alt="Screenshot 2022-09-13 at 13 06 02" src="https://user-images.githubusercontent.com/846565/189896577-f34d9ccb-e192-4006-b6f4-acfb250d5996.png">

It would be good to update the spacing so that there's a larger gap between the control and the subsequent label. 

<img width="448" alt="Screenshot 2022-09-13 at 13 06 39" src="https://user-images.githubusercontent.com/846565/189896951-d9e70b26-a050-4dee-bcab-9954c78237bc.png">

Considering https://github.com/WordPress/gutenberg/issues/41973 it would also be good to increase the height of the input itself to 40px instead of the current 30px.

**Comment by glendaviesnz** [comment]
@jameskoster I have a [PR for this here](https://github.com/WordPress/gutenberg/pull/44141). It was hard to get the exact dimensions you specified due to the way the range control is absolute positioned, but let me know what you think and let me know if you think it needs further px adjustments.

I also added a slight indent when in unlinked mode which I think really helps to indicate which dimension setting the controls relate to, particularly if you have margin and padding settings.
