### ISSUE TITLE
Change the word 'block' in settings

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#4415]
A little history. We have right now: Document and Block. In a recent issue #4319 a lot of good discussion happened that the word format wasn't right. As such, we need to revert for today and then consider what would be.

![2018-01-11 at 20 04](https://user-images.githubusercontent.com/253067/34844853-b971dd2a-f70a-11e7-90b1-b5cd165e5158.png)

It's important to note that an end user won't know what 'Block' means. One idea that @mtias has suggested, could we just say the name of the block being interacted. Now, consistency wise this could seem odd but it also could add some context to the 'global (document) and the specific'.

This is a good topic to discuss so please add in your insights. Try and think what other words than block would work in this case. What do other applications use in this instance?

**Comment by amandablum** [comment]
The more I think about this, the more I go to the whole concept of widgets and how we've managed them for so long. Widgets is literally the most generic term ever. I've taught people what widgets are over 8 or 9 years, in which their functionality and purpose has grown and shifted, but they were always able to pick it up. Widgets had a utility. But the correlation here is pretty close. My point is... there is a parent term to describe them: widgets. Within them, a slew of KINDS of widgets, and we never confused them. And since our users are so used to how widgets work, we can use that as a template for how to make blocks work and how they will understand them.  We can improve on that process.... inserting a widget is clunky, but its also what our users know. 

Point being, we still need to call them something and I argue, heartily, that word needs to be a noun. In other words, we need to call them something that describes their purpose, not their action.

**Comment by greatislander** [comment]
Element?

**Comment by carlhancock** [comment]
I still think "Block" is the best thing to call it.  It's what everyone has been calling it during Gutenberg development.  It is what tutorials have already been written and published about Gutenberg have been calling it.  It's what people are already actively creating resources for Gutenberg are calling it such as Zac Gordon's Gutenberg development course.

It's a simple name that users won't have a hard time picking up.

"Add the Gravity Forms Block to your page."

"Add the WooCommerce Product Block to your page."

The fact that users don't know what "Blocks" are shouldn't be a deterrent.  Just because they don't know what it is they will learn very very quickly because plugins and themes are going to be bringing them blocks at a rapid clip once Gutenberg is released.

**Comment by greatislander** [comment]
I still think Block is best. It’s been used throughout all the writing, tutorials,  code samples etc. over the course of Gutenberg’s development. It’s also used in [other platforms](https://support.squarespace.com/hc/en-us/articles/206543757-What-are-blocks-).

**Comment by karmatosed** [comment]
It's worth noting just because we are changing the settings name we are not changing the notion of blocks. This is about an experience description not changing the concept. It's important to not leap from this issue to assume we're removing the word block entirely.

**Comment by carlhancock** [comment]
@karmatosed Why the desire to change the name in the sidebar? If the name isn't being changed for Blocks themselves doesn't it make sense for the sidebar navigation tab for the Block settings to also say Blocks?  You edit either the Document settings or the Block settings.  

@travislopes created another issue on this naming inconsistency and went into detail (as did I in my reply) as to why "Format" is not a good name for the Block Settings.  You can see that in more detail here: https://github.com/WordPress/gutenberg/issues/4390

Block settings may or may not have anything to do with "Format" which has design/UI connotations.  Settings for a block may have nothing to do with design/UI.  The example in #4390 outlines this.

The #4390 ticket also recommends making these labels be pluggable so that they could be customized by plugins and custom code.  WordPress is used for all kinds of things and the UI labels for things like this need to be customizable.  If someone is building a hosted web site solution for a niche market with WordPress they may want to call Blocks something entirely different.  

If these things can be manipulated via code that won't be an issue.  Right now things such as the label for the settings cog icon when selecting a block are hardcoded.  They need to be flexible and able to be manipulated.  This kind of flexibility is heavily used by people that build custom solutions and web apps on top of WordPress.

**Comment by techmagick** [comment]
+1 for staying with current Block naming. Users will figure out very quickly what it means.

**Comment by leahkoerper** [comment]
+1 to all the points made above for sticking with the name Block. As @carlhancock said, users are going to quickly learn the term- particularly from using the inserter. If we change it in the sidebar, it's only going to be _more_ confusing for users. Additionally, even the shapes of the current UI suggest the word block- they are literally big rectangles that stack :)

**Comment by karmatosed** [comment]
Closing as this one seems set right now.
