### ISSUE TITLE
Site Logo: Block styles not reflected in the editor.

### ISSUE THREAD

**Issue by alaczek** [WordPress/gutenberg#44177]
### Description

The Site Logo block offers two styles: Default and Rounded. When selecting the Rounded option, neither the placeholder wireframe nor the logo image becomes rounded in the editor. It is rounded in the preview though. I expected the Site Logo block image/placeholder to become rounded both in the editor and preview after selecting the Rounded block style.

### Step-by-step reproduction instructions

1. Open up the Editor via Appearance > Editor.
2. Edit the Site Logo block in the header - select the Rounded option in the block styles.
3. Note the Site Logo placeholder is still square.
4. Add a logo image. The logo image is square as well.
5. Save and preview the site. The site logo in the preview is rounded, as expected.

### Screenshots, screen recording, code snippet

![Q8rUCwM7Yo](https://user-images.githubusercontent.com/4550351/190305152-88fab0f6-a3c3-4b7a-ad53-2023166459ab.gif)

### Environment info

- WordPress 6.0.2, Gutenberg plugin 14.0.3
- Theme: Twenty Twenty Two 1.2
- Browser: Chrome 105.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
It does look rounded in the editor for me:
![Screen Shot 2022-09-15 at 12 48 29 pm](https://user-images.githubusercontent.com/677833/190316949-ea8f7cc9-80a5-4d9d-a1d6-d619895176be.png)
![Screen Shot 2022-09-15 at 12 47 21 pm](https://user-images.githubusercontent.com/677833/190316968-260591f4-96a0-4e28-aef1-433f8661c42c.png)

(as well as on the frontend.)

It looks like it was fixed by a PR here - https://github.com/WordPress/gutenberg/pull/43762, so the fix will be in Gutenberg 14.1. Thanks for reporting this though.
