### ISSUE TITLE
Post Featured Image: Border radius option not working when custom height and width set

### ISSUE THREAD

**Issue by dashkevych** [WordPress/gutenberg#44172]
### Description

Setting custom border radius for Featured Image block inside Query block, when custom height and width are set, works only in the Editor, but not on the actual website.

### Step-by-step reproduction instructions

1. Make sure post has set featured image.
2. Create new page with Query block in it.
3. Select Post Featured Image block.
4. Set custom width and height in Dimensions section (sidebar).
5. Set custom border radius in Dimensions section (sidebar).
6. Publish page.

### Screenshots, screen recording, code snippet

<img width="1387" alt="back-end-example" src="https://user-images.githubusercontent.com/3655965/190269265-f225bc9c-c561-4370-a7af-1a43d4d242fa.png">
<img width="938" alt="front-end-example" src="https://user-images.githubusercontent.com/3655965/190269275-66f81a32-e6be-441c-9c6c-82615465c379.png">

### Environment info

- WordPres: 6.1-alpha-54149
- Gutenberg: 14.0.3 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Can confirm the issue. Thanks for reporting this.

**Comment by aaronrobertshaw** [comment]
I believe this is the same issue as https://github.com/WordPress/gutenberg/issues/44194 which has been fixed via https://github.com/WordPress/gutenberg/pull/44213. 

Following the test instructions as per this issue, I couldn't replicate the issue since the fix landed, so I'll close this one. 

Thanks for reporting it @dashkevych 👍 

<details>
<summary>Demo video of latest test</summary>


https://user-images.githubusercontent.com/60436221/191176214-f034dc60-c1a0-4411-8bcf-0589da09df83.mp4



</details>

**Comment by talldan** [comment]
@aaronrobertshaw There was also a similar report in https://github.com/WordPress/gutenberg/issues/44262 about the cover block.

**Comment by aaronrobertshaw** [comment]
Thanks, I've replied on https://github.com/WordPress/gutenberg/issues/44262 as the Cover block doesn't actually have border support yet.
