### ISSUE TITLE
Move document information and outline to list view panel

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#44193]
Consolidating list view / navigator, document stats, and document outline has surfaced a few times in the past. I'm proposing we revisit this and redesign the document stats a little bit. With the addition of "time to read" the current grid design is becoming harder to quickly parse:

- Display them as a list and smaller font size at the top or bottom of list panel.
- Add a tab interface to switch between all blocks and outline when headings are in place.

Mockup:

<img width="1600" alt="integrated-list-view" src="https://user-images.githubusercontent.com/1204802/192787452-280bab60-3fde-4f8c-84b8-157594b03962.png">

* List view and Outline tabs at the top
* Outline tab only available if the document has heading blocks
* Outline stats fixed at the bottom, shown on both tabs

Related #41330

Some questions to resolve in implementation: does the document stats take up valuable list view space? If yes, we can [collapse the information into a single row](https://github.com/WordPress/gutenberg/issues/44193#issuecomment-1252189792).

---

Issue updated Sep. 30.

**Comment by jasmussen** [comment]
Here's a first draft that puts the desired information into the panel:

<img width="1600" alt="Options" src="https://user-images.githubusercontent.com/1204802/191233592-78b6e073-f58b-433c-80e6-d641881f922b.png">

There's something about the balance and structure that isn't quite working, but sharing it here for thoughts, in case @WordPress/gutenberg-design has some ideas. [Here's a Figma file](https://www.figma.com/file/vmHxwa8WhiyiP9poe2om9J/Inspector-Panels?node-id=13392%3A35312) to poke at if inspiration strikes.

**Comment by jameskoster** [comment]
Aren't we giving too much prominence to the overview by placing it at the top of the panel? I would imagine the other features of list view are used more frequently...

An alternative that places the details at the bottom of list view:

<img width="340" alt="Screenshot 2022-09-20 at 12 02 17" src="https://user-images.githubusercontent.com/846565/191241469-c9f29381-adcb-4d61-92c2-9d590db5381a.png">

**Comment by jasmussen** [comment]
Whether at the top or the bottom, I quite like that gray/compressed style 👌 

If we _do_ put it at the bottom (need to still chew on it), then the top List View header can be replaced entirely by the tabbar, with the X on the right.

**Comment by mtias** [comment]
I can see it at the bottom, but the single line won't work in most languages. Can we try the split two column at the bottom?

**Comment by paaljoachim** [comment]
Looking at the screen today.

![Screenshot 2022-09-20 at 13 17 08](https://user-images.githubusercontent.com/5323259/191244838-c1fa174c-945f-4070-a102-06a16c998dfe.jpg)

List view - Canvas/document view
Bottom Breadcrumbs. (Which I have often found very helpful.)

---

A few explorations
![List-view-and-details](https://user-images.githubusercontent.com/5323259/191246356-c92fb293-af08-4cfd-9c9c-d25c12e6294b.jpg)

---

![List view and details 2](https://user-images.githubusercontent.com/5323259/191247609-978de2f4-2b33-412d-affd-206486cd9560.jpg)

---

![List view and details 3](https://user-images.githubusercontent.com/5323259/191247641-13a1185e-fa76-4142-9650-b9b627832484.jpg)

**Comment by jameskoster** [comment]
There is also https://github.com/WordPress/gutenberg/issues/36696 to think about. I'm not sure if that's something we still want to pursue?

<img width="368" alt="Screenshot 2022-09-20 at 13 40 40" src="https://user-images.githubusercontent.com/846565/191260011-2dea3dcc-ea62-4401-a3a8-627831c0458b.png">

**Comment by jasmussen** [comment]
This is getting close, I like that ☝️. If we right-align the character/word counts, does that put them too far from the label?

<img width="404" alt="Screenshot 2022-09-20 at 14 44 33" src="https://user-images.githubusercontent.com/1204802/191260977-0416bc31-d34d-48d4-9541-103f76512d73.png">

I like that it acts as a framing device for the main grid of the panel.

**Comment by mtias** [comment]
I don't know that the number of blocks makes a ton of sense in the header. Can we bring it to the list below? Also, it seems these stats should be contextual to what you are doing — editing content or designing. When designing none of those three seem that useful, but blocks, template parts, etc, might be relevant.

**Comment by jameskoster** [comment]
> does that put them too far from the label

I find it harder to trace personally, but it's not too bad as there are only 3 rows. If there were more it could become problematic.

> Also, it seems these stats should be contextual to what you are doing

I think the stats should only be present in the post editor list view (side note, we should ensure they're hidden in the template editor – currently they are not). We can figure out which stats (if any) to display in the site editor separately.

**Comment by jasmussen** [comment]
Just to follow up on this one, here's an idea of making the panel tabbed-only, which woudl put the counts solely in the outline tab:
<img width="1440" alt="Overview" src="https://user-images.githubusercontent.com/1204802/191454076-cb4c95aa-3a48-4388-a709-e349ddc9ce6e.png">

This could still be combined with showing the information at the bottom of both tabs, as an anchor:

<img width="1440" alt="Overview 2" src="https://user-images.githubusercontent.com/1204802/191454255-9fc71ee0-1463-405b-9d17-c92624b17752.png">

**Comment by jameskoster** [comment]
I quite like the idea of only displaying the stats in the Outline tab. It does mean we'd need to design an 'empty' state for that tab though, for cases where a post/page contains no headings. 

Another option could be to add a user preference which toggles the display of the stats. I don't know how many people use them but I suspect it's relatively small. This way, if the toggle is off and the post contains no headings then we can just hide the Outline tab altogether.

**Comment by jasmussen** [comment]
> It does mean we'd need to design an 'empty' state for that tab though, for cases where a post/page contains no headings.

Would it be crazy to just not have the tab if empty?

**Comment by jameskoster** [comment]
> Would it be crazy to just not have the tab if empty?

Then how would you see the stats?

**Comment by jasmussen** [comment]
Right, that would only work if the stats was a fixed anchor at the bottom of either tab.

**Comment by jasmussen** [comment]
Should we zero in on this one for starters? 

<img width="1600" alt="integrated-list-view" src="https://user-images.githubusercontent.com/1204802/192787452-280bab60-3fde-4f8c-84b8-157594b03962.png">

That is:

* List view and Outline tabs at the top
* Outline tab only available if the document has heading blocks
* Outline stats fixed at the bottom, shown on both tabs

**Comment by ALJ** [comment]
All the mockups above look polished and wonderful, but I disagree with shrinking the usable area of the List view (if that's what's happening).

@jasmussen in your latest List view mockups, is it the intention to have the statistics _always visible_ fixed to the bottom, with the List view items scrolling "behind" it? Another way of asking is: where are the statistics if the List view is so tall as to require scrolling?

I ask because multiple clients have told me List view is one of their favorite features of the block editor as it makes complex/nested block structures clearly visible to them. They want room in the List view to see as much as possible, and  expand multiple levels. It would be a disservice to them to make the List view smaller.

**Comment by jasmussen** [comment]
> is it the intention to have the statistics always visible fixed to the bottom, with the List view items scrolling "behind" it? Another way of asking is: where are the statistics if the List view is so tall as to require scrolling?

Good points, I love the list view too. I think we have options here. My initial instict would be for list view items to scroll behind it, since the footprint of the stats isn't that big especially at desktop breakpoints. But we can also _flex_, so that it is fixed at the bottom until list view items push it downwards. That might make those stats less findable on a large document, though. Another option is to query the viewport height and adjust the behavior accordingly. Yet another option is to minimize the footprint even further: personally I don't find the "Time to read" all that useful in the _editor_ context (I'd rather have that as a block to output for my blog readers!). Potentially we could reduce character and word count into a single row.

In any case, I like to think that these issues will become immediately apparent in a PR that implements this, allowing us to choose among the paths forward. 

I'll update this ticket with that context, and hopefully we can thread the needle.

**Comment by jasmussen** [comment]
This ticket has been updated and should be ready for a dev to pick up!

**Comment by ALJ** [comment]
> ... we can also flex, so that it is fixed at the bottom until list view items push it downwards. That might make those stats less findable on a large document, though...

RIght, that might annoy authors who rely on easy access to the character/word counts.

List view and Statistics are _both_ useful but probably for different kinds of authors or at different times. Assembling a nested page of layout blocks is a different task than writing narrative text to fit a word-count limit. Combining the tools into one pane, or making either more difficult to find/use, might be a tricky balance. Regardless of the direction taken, I'm sure the design will be an improvement over the current state and can be more easily tailored in a PR 😄

**Comment by alexstine** [comment]
Something else everyone needs to think about. I have no problem with combining the list view and these statistics, one could argue that putting the information in a more centralized location actually exposes it more and that is not a bad thing. My problem specifically deals with a context issue. We can no longer call this the "List View" sidebar because it contains more than the list view. For the purpose of accessibility and the tool tip that you get when hovering the button in the toolbar, what should it now be called? "List View" is no longer true. Maybe it should be changed to "Document Structure"?

I probably should have brought this up before now but better late than never.

It is likely something no one else really thought about either because the visible "List View" wrapped in a bold/strong tag was removed in the linked PR. Out of sight, out of mind. However, for accessibility, there are still `aria-label` with "List View" and a button with "Close List View Sidebar".

Thoughts?

Thanks.

**Comment by jasmussen** [comment]
That's a good point, thank you.

> Maybe it should be changed to "Document Structure"?

Sounds good to me. The tabs would still indicate either sub-section.

**Comment by alexstine** [comment]
@jorgefilipecosta Do you have time to do some label replacing and probably modify some E2E tests for the new name?

**Comment by colorful-tones** [comment]
I hate to get caught in semantics, and may I suggest: "Document Overview"? It seems a bit more descriptive of the context _and_ easier to grok.

Great catch on the `aria-label` and for raising this issue @alexstine

**Comment by alexstine** [comment]
That still seems fair to me. Describes the purpose clearly.

**Comment by annezazu** [comment]
@jorgefilipecosta can you confirm you'll follow up on the above? Trying to manage an update for Phase 2 and am trying to ensure this can fully be considered marked as done :)

**Comment by jorgefilipecosta** [comment]
Hi @alexstine, than you for catching the missing label change. @colorful-tones thank you for suggesting a new label.
@annezazu there is a follow-up PR fixing this at https://github.com/WordPress/gutenberg/pull/45524.
