### ISSUE TITLE
Improve organization of templates to reflect importance/hierarchy

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#44302]
## What problem does this address?

Right now, when you're looking at the template list, there's no sense of what's important and the templates feel a bit scattered, especially after you add new ones that appear at the top: 

<img width="1035" alt="image (24)" src="https://user-images.githubusercontent.com/26996883/191299711-78ae79a3-c223-4aa6-acec-16c15183c851.png">

It feels odd that you have to scroll and read each template to find what you are most likely to need.

## What is your proposed solution?

Consider adding a level of organization to the templates to help better reflect importance and relevance of specific templates. For example, the template powering the homepage likely should be listed higher than a random new category template. 

cc @WordPress/gutenberg-design for thoughts here!

**Comment by jasmussen** [comment]
I like to think there's an opportunity for a thumbnail view [in the not too distant future](https://github.com/WordPress/gutenberg/issues/36667#issuecomment-1228468407). But in the mean time, should we categorize? Maybe a main category holding home, index, archive, then an expanded category for category, 404, single, page, tag, etc, and finally a category for custom-made templates?

**Comment by paaljoachim** [comment]
Ordering the template page into categories could be helpful.

**Comment by jameskoster** [comment]
There's some discussion in https://github.com/WordPress/gutenberg/issues/42325#issuecomment-1206455419 which might be relevant here.

**Comment by annezazu** [comment]
This came up in the [nineteenth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2022/12/14/fse-program-testing-call-19-running-through-refinements/#comment-2830):

>But why does the order of the templates change? Home template is not always the first template.

**Comment by jameskoster** [comment]
It's difficult to order the _entire_ list of templates because 'important' is somewhat subjective based on the current task and existing templates. We could create an ordering function that sorts based on the existence of templates hierarchically (e.g. Index is only important when Home doesn't exist). But a simpler approach might be additional sorting levels in the UI... so instead of just having a single list of templates they're arranged into categories. Quick mockup:

<img width="393" alt="Screenshot 2023-01-05 at 11 02 35" src="https://user-images.githubusercontent.com/846565/210765464-6f3795ea-60e7-4861-a331-01627b6e1989.png">

This could theoretically make the template addition process simpler too. For example if you want to add a blog to your site you just click + and select 'Blog', rather than having to manually create Category, Tag, Author, Single Post, one by one.

**Comment by jasmussen** [comment]
I wonder if subheadings could work in that context? While the waterfall structure affords endless drilldowns, I wonder if it isn't nice to have more immediate access?

**Comment by jameskoster** [comment]
I'd say it's worth a try. We'd probably need to make the subheadings sticky to aid orientation within extra long lists.

**Comment by annezazu** [comment]
Noting that the current chaotic ordering remains confusing as I test 6.2 beta 2. For example, here's a screenshot of browse mode where you can see some custom templates alongside the ones built into TT3:

<img width="357" alt="Screen Shot 2023-02-15 at 9 50 07 AM" src="https://user-images.githubusercontent.com/26996883/219111816-93ba8aff-cbfd-4568-a436-6696612e9c5f.png">

In this case, I have to scroll down and find "home" to edit my homepage template. Is this something we can improve for 6.2? I think it will be a huge quality of life improvement cc @richtabor as design lead.

**Comment by jameskoster** [comment]
My preference here would be to add some subheadings to group templates contextually, something like:

<img width="380" alt="Templates" src="https://user-images.githubusercontent.com/846565/219344616-229a2ac4-6049-4459-95f7-66f3e03a0601.png">

Grouping by post type (and custom) will scale well when plugins are added (you can imagine a 'Products' section when you install WooCommerce). I acknowledge things like 404 aren't technically `page`s, but I suspect that's how most people think about them. 

It's a bit down the road, but we could use such grouping to create a UI for adding custom post types too. For example there may be a 'Add testimonials section' button somewhere which would automatically create `archive-testimonials` and `single-testimonials` (and place them in a new Testimonials template section) in one click.

If we add grouping to the list (contextual or otherwise) then I think the ordering may be less of an issue. That's not to say we shouldn't figure something out there, more that it can probably by worked out separately.

**Comment by jordesign** [comment]
I really like this idea of grouping with sub-headings (without the need to drill down)

**Comment by SaxonF** [comment]
Groupings look good. In future we may need to figure out how this overlaps with the idea of showing certain templates alongside pages, but not something to think about now.

**Comment by jameskoster** [comment]
In terms of ordering within the sections, perhaps alphabetical would be okay to start, with the caveat that 404 should always be at the bottom :)

**Comment by mtias** [comment]
Groupings seems nice to explore, but I agree at least stopping the seemingly random shifts that occur when using "recently edited". A hard-coded list based on A/Z but optimized (don't lead with 404) seems like a good start. Custom templates should probably be still separate, it can get confusing otherwise.

**Comment by jameskoster** [comment]
With https://github.com/WordPress/gutenberg/pull/48473 merged this is at least partially solved. 

@annezazu do you think that's adequate to close this issue, or should we aim for the grouping as well?

**Comment by mtias** [comment]
I'd like to continue exploring the "Pages / Blog / Custom" groupings further, but probably best to do a specific issue about that.

**Comment by jameskoster** [comment]
I opened https://github.com/WordPress/gutenberg/issues/48651 as a follow-up. 

I'll close this one, but feel free to re-open if I am too eager in doing so.
