### ISSUE TITLE
TS2305: Module @wordpress/... has no exported member __experimental...

### ISSUE THREAD

**Issue by seothemes** [WordPress/gutenberg#44345]
## What problem does this address?

TypeScript is throwing an error because experimental features are not exported by `@types/wordpress__...` packages. Are there any plans to support experimental feature types, or should we not use them?

`TS2305: Module '"@wordpress/components"' has no exported member '__experimentalNumberControl'.`

<img width="763" alt="screenshot of typescript error" src="https://user-images.githubusercontent.com/24793388/191664444-1995842d-40a4-47e2-9a92-f54b6128471e.png">

## What is your proposed solution?

Ideally, experimental features would also be added to the types packages.

Can be suppressed with `// @ts-ignore`

**Comment by mirka** [comment]
Good question! The fact that NumberControl isn't included in `@types/wordpress__components` is not intentional, as far as I know. I think you could even submit it to the [DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/wordpress__components) if you wanted to. I don't think anybody is actively making sure that the WP packages types on DefinitelyTyped are up to date, and so they're always quite unreliable.

The reliance on DefinitelyTyped is just a stopgap until we get to a point where we can officially ship the type data with the Components package itself. We're actively working towards that goal (#35744), and we're getting closer. Basically we need to finish typing every component left in this [exclude list](https://github.com/WordPress/gutenberg/blob/569241a3e1b7d0cc0567fccb92b1b57eb1b5b9c5/packages/components/tsconfig.json#L43-L77).

Whether or not you _should_ use experimental components is a different matter — you're free to use it as long as you understand that there are no guarantees around breaking changes 🙂

**Comment by seothemes** [comment]
@mirka thank you, that's helpful. I will have a go at submitting it to the DefinitelyTyped repo and helping with the exclude list if I can figure out how to submit PRs to Gutenberg.

Over time I have found them to be pretty good - or not that hard to fix when there are breaking changes. Simple ones like the number control I can't see changing too much.

**Comment by mirka** [comment]
The action item here is basically #35744, so I'll close this issue in favor of that one.
