### ISSUE TITLE
Scrolling down the list of patterns scrolls the editor instead

### ISSUE THREAD

**Issue by javierarce** [WordPress/gutenberg#44379]
### Description

Scrolling down the list of patterns after the last loaded pattern will scroll the editor instead.

Edited: Testing this again, I can also reproduce the bug scrolling down outside the sidebar (for example, scrolling down the content of a post or page)

Here's a video showcasing the problem:

https://user-images.githubusercontent.com/4933/191792770-072da5bf-ca57-4b8e-8bbf-5fbb37f4b68f.mov

I found this bug both on Chrome and Safari. Firefox doesn't seem to be affected.

### Step-by-step reproduction instructions

1. Go to the editor.
2. Click the plus icon of the Inserter
3. Visit the Patterns tab
4. Scroll down the list

### Environment info

- WordPress 6.0.2
- Gutenberg 14.2.0-rc.1 
- Chrome and Safari on macOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by javierarce** [comment]
Testing this again, I can also reproduce the bug scrolling down outside the sidebar (for example, scrolling down the content of a post or page)

**Comment by ntsekouras** [comment]
This is very weird issue, mostly because I can reproduce in most pattern categories, but not for `Buttons`, using 2022 theme. I tried adding `overflow:hidden` to `.edit-post-editor__inserter-panel`(and to the site editor one) and it seems to work, but...

I then tried the [new design for patterns](https://github.com/WordPress/gutenberg/pull/44028) and my above css wasn't working properly. On the other hand in the new PR I rendered twice the categories to make it more than the viewport height and couldn't scroll more than it.. --cc @youknowriad @jasmussen

**Comment by jasmussen** [comment]
Tricky indeed! At a glance it looks like this is because overflow is `auto` on `.interface-interface-skeleton__body`, whereas if it was `hidden` on that, and instead `auto` on `.block-editor-writing-flow`, it seems like it would address the issue. 

However there's likely more going on. For example why can I scroll the block tab just fine, just not the patterns one? Curious indeed.

**Comment by youknowriad** [comment]
The pattern inserter has been redesigned. I'm not able to reproduce this issue personally.
