### ISSUE TITLE
List no longer splits paragraph with line breaks into list items

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#4438]
## Issue Overview

The transformation around the list block now seem to be inconsistent.

* Selecting a single paragraph block and transforming it into a list results in a list with one item (even if there are line breaks in the paragraph). It used to turn each now line into a list item.
* Selecting multiple paragraphs and turning it into a list creates a list item out of every paragraph. Seems logical. Turning it back works correctly.
* Creating a list with the pattern `*`, `-`, `1.` or `1)` + `SPACE` creates a list item out of every new line in the paragraph. Turning the list back into a paragraph results in a paragraph for every list item. This seems broken.

@mtias Are we now done with creating list items form lines in a paragraph? It seems we need to choose between one or the other? Or do you see an alternative?

**Comment by youknowriad** [comment]
This is an intended behavior since the introduction of the ability to select multiple paragraph blocks to transform them into a list. This was changed to make this transformation work consistently in both directions.

I'd argue aht we should change the third point here to create a single list item. And consistently consider `<p>` equivalent to `<li>` and consider `<br>` as formatting.

**Comment by iseulde** [comment]
Okay, then we can get rid of the whole BR logic in the list block... I thought there was a specific request to have BR also turn into list items though (single block selection).
