### ISSUE TITLE
Make it easy to copy (and paste) block styles

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#44418]
It would be nice if there was a way to copy styles for a block, and 'paste' them onto another. Currently the only way to do this is to duplicate the entire block which is not always convenient, or to manually copy the tools/settings one-by-one which is extremely tedious for heavily styled blocks. 

Related to https://github.com/WordPress/gutenberg/issues/44417 and #38267, and this issue contains designs based on https://github.com/WordPress/gutenberg/issues/44361.

Surfacing copy and paste styles in a context menu provides the full block context, and manages prominence. If possible, using nested menus option would be the clearest path forward, to further manage prominence. 

<img width="905" alt="Nested menus" src="https://user-images.githubusercontent.com/1204802/201296979-451ec38c-6db7-4d53-97ae-c6c6a45acc75.png">

A smaller option would be to accept a longer ellipsis menu:

<img width="905" alt="Just menus" src="https://user-images.githubusercontent.com/1204802/201296994-d77be2f6-a34b-4386-bda1-4cb84a109459.png">

---

Issue updated Oct 11.

**Comment by mtias** [comment]
Also related to #38267.

I see this tool operating at the level of the "appearance" / "settings", exposed like we have "Duplicate" for the entire block in the ellipsis menu.

**Comment by javierarce** [comment]
Here are two ideas for the copy and paste interface:

1. Obvious solution: we list the new options under the Copy block element:

![image](https://user-images.githubusercontent.com/4933/196230961-37d1d733-34c5-48d1-bc9c-00639a06d879.png)

We could also group the copy and paste options

![image](https://user-images.githubusercontent.com/4933/196237317-6b526615-599e-431a-9cf0-c36b56e6445c.png)

I've explored other designs that include an option to paste blocks, but it would require users to give the browser access to the clipboard, and I imagine this is the reason we don't already offer this.

[Figma file](https://www.figma.com/file/WNTUdJBimu1tqHJBRlYAfm/Copy-and-paste-block-styles?node-id=0%3A1)

**Comment by talldan** [comment]
The other option that came to my mind is something that works a bit like 'Paint format' does in a spreadsheet, where you can copy from one block and click/select the other block to apply.

**Comment by jameskoster** [comment]
I wonder if we could group all the copy/paste actions into a single flyout?

That might be useful in the future if we decide to allow block _settings_ to be copy/pasted independently as well. 

```
Copy/Paste >
    Copy Block
    Copy Styles
    Copy Settings
    ---
    Paste Block
    Paste Styles
    Paste Settings
```

**Comment by javierarce** [comment]
That was more or less the first thing I tried, but then I noticed we don't give the option to paste blocks (because of privacy concerns, I suppose).

![image](https://user-images.githubusercontent.com/4933/196394955-ae5553c6-7d07-48e6-af60-88acee9b3641.png)

But now that I think of it again, a possible workaround to avoid asking for clipboard permissions could be to store the copied block in the Local Storage too, as I imagine we will need to do with Styles and Settings.


[Figma file](https://www.figma.com/file/WNTUdJBimu1tqHJBRlYAfm/Copy-and-paste-block-styles?node-id=0%3A1)

**Comment by jameskoster** [comment]
Good points. Perhaps your second design would be a good place to start. Should there be keyboard shortcuts for these actions?

**Comment by kevin940726** [comment]
> a possible workaround to avoid asking for clipboard permissions could be to store the copied block in the Local Storage to

One thing to consider is that this workaround won't work for data copied from other tabs. For instance, copying from the patterns directory in wordpress.org cannot be pasted on a WordPress instance. We would need to handle that gracefully to reduce inconsistency.

**Comment by kevin940726** [comment]
Maybe we can learn from Google Sheets and only provide a single "copy" action but provide several "special paste" actions.

![image](https://user-images.githubusercontent.com/7753001/198945936-a6290a12-a3c9-4b4b-8f7d-3a0c65c8478b.png)

This works by copying the whole block along with the styles into the clipboard, and deciding which part to paste depending on user intentions (both, block only, styles only).

Note the "Paste block" action is still available in the top-level settings. This is to make it clear that it should be the most used action and avoid confusion.

A bonus benefit of this approach is that we can allow pasting styles from different contexts, either from a new browser tab or from a completely different app. Imagine being able to paste only the styles from `wp.org/patterns` for instance.

**Comment by jameskoster** [comment]
Thinking about this a little more, I'm not sure 'Paste block' is an action we want to add to this menu just yet.

This makes me lean towards @javierarce's [original design](https://github.com/WordPress/gutenberg/issues/44418#issuecomment-1281171238) with the three actions

* Copy block
* Copy styles
* Paste styles

The styles action could be grouped under a flyout in the future, but it's not essential to begin with.

**Comment by kevin940726** [comment]
I still don't think "copy styles" should be an individual action. Styles only make sense in a WordPress environment, there's nothing to be pasted in other applications. It might create some confusion around it. Instead, we should handle the paste events on our side to support both blocks and styles. This gives us more control over how the internals should be implemented too.

"Paste block" is quite awkward 😅. Since we're in the settings dropdown of an existing block, pasting blocks might actually mean _replacing_ it.

I wonder if the wording of "Paste styles" can be refined too. Maybe something like "Paste and apply styles only" makes more sense. But I think this is trivial.

**Comment by kevin940726** [comment]
I opened a draft PR https://github.com/WordPress/gutenberg/pull/45477 for adding "paste styles" to the block settings. There are a lot of unanswered questions, but I figured a working branch would better explain the details. Please try it out and share any feedback here or there!

**Comment by javierarce** [comment]
> I still don't think "copy styles" should be an individual action.

I'm not completely sure about this decision. I think not having explicitly complementary actions is confusing. We can be smart about it and implement it in the way you mention, but in the end users will need to copy a block in order to paste a style.

**Comment by kevin940726** [comment]
> I think not having explicitly complementary actions is confusing. We can be smart about it and implement it in the way you mention, but in the end users will need to copy a block in order to paste a style.

That's a fair point! Apple's Numbers has a separate "Copy Style" action, while Google's Sheets and Microsoft's Excel have only one "Copy" action but multiple "special" pasting actions. It's hard to decide which one is better for UX without data.

However, while trying Numbers' approach, I found the interactions quite interesting. It seems like "Copy" and "Copy style" belong to different "types" of clipboards. Data copied from the "Copy" action cannot use "Paste style" to paste to somewhere; Styles copied from the "Copy style" action cannot use "Paste" to paste to somewhere either. I think it's possible because the clipboard API is less restricted at the OS level. I don't think we can do the same in the browsers though, `clipboard.readText()` can only access the latest copied data from the clipboard.

Another thing that might be worth mentioning is that blocks (and styles) don't only exist in a WordPress instance, they can exist anywhere on the web too. A good example is [wp.org/patterns](https://wp.org/patterns), one can copy patterns from there and paste the styles somewhere in their editor. I think it might be confusing for the users when they can't find the "Copy style" button there. They might just think that it's impossible to copy the styles of the blocks there.

In addition, I'm not sure if it's a good idea to add two buttons with the exact same behaviors ("Copy" and "Copy style").

**Comment by jasmussen** [comment]
Noting that #44361 was just updated with mockups that include style copy/paste actions. Should we merge the issues, or would you like me to extract the copy pieces for this one?

**Comment by priethor** [comment]
I think it's better to keep them separated so that we can more clearly divide and parallelize the development work.

**Comment by jasmussen** [comment]
I went ahead and updated the issue! Since it already has a dev assigned, it's mostly a formality.
