### ISSUE TITLE
Gutenberg for Emails?

### ISSUE THREAD

**Issue by bhubbard** [WordPress/gutenberg#44421]
Gutenberg has made great strides in WordPress. One thing that is lacking in WordPress Core is an email editor tool. There are hooks developers can use to modify the templates, but many go toward plugins to customize emails generated by WordPress for the ease-of-use as a user. Additionally, plugin developers like WooCommerce will build entire toolsets to create/manage email templates. 

### Could Gutenberg be used to edit emails? 

The **HTML/CSS** output for blocks would probably need to be different due to the way these are handled in emails today. How to handle **HTML** vs **plain/text** versions of an email? I would love to see if this could be explored, and maybe lead way to some kind of "email" mode for Gutenberg. Once it's established that emails can be created in Gutenberg with decent compatibility with email clients, maybe WordPress Core can begin to use it by offering an admin UI to modify default emails generated by WordPress, in addition to other plugins using it for their own emails.

**Comment by annezazu** [comment]
Hey @bhubbard! Apologies for the delay here. Check out this plugin that does exactly what you're describing: https://newsletterglue.com/ 

For now, I'm going to close this out as it's firmly in plugin territory rather than something Core will take on (will take on allowing the possibility to extend the editor for this exact reason of course!).
