### ISSUE TITLE
Site logo does not scale above certain point

### ISSUE THREAD

**Issue by andowt** [WordPress/gutenberg#44624]
### Description

When changing the size of the site logo I expect that the image should grow or shrink to fill the selection box

Shrinking works as expected however the image stops growing at a certain point (possibly actual px size of image)

However rendered website does display correctly

### Step-by-step reproduction instructions

Activate twenty twenty two theme
Add site logo to header
Grow and Shrink

### Screenshots, screen recording, code snippet

![scaling](https://user-images.githubusercontent.com/90341234/193343712-0c8ebef8-2afc-47c3-bc5c-ed6fbfec73e1.gif)

### Environment info

Wordpress 6.0.2
Build in editor and gutenberg plugin
Tested on both firefox and chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ghost** [comment]
This issue still occurs. Would like to add to this that it happens regardless of what theme you use.

The problem seems to me that the width is only being set on the resizable box, but not on the image itself. If I download the source code, add an inline style to the image and set the size, it does scale along. Same happens when I add `width: 100%` to the image in the Browser Dev Tools, although then I also have to add it to the anchor wrapped around it.

**Comment by ghost** [comment]
On closer inspection, if you turn the toggle `Link image to home` to off, the image scales up again. So it seems to have something to do with the width on solely the anchor wrapping the image.

**Comment by annezazu** [comment]
I was unable to replicate this in 6.3 RC3, regardless of whether the `Link image to home` setting was on or off. Closing out as a result but, if I'm mistaken or there's something missing, please just comment again and I'll follow up to reopen and investigate.
