### ISSUE TITLE
Reusable Blocks Fallback

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#4468]
One interesting thing about reusable blocks is that they turn generally static content dynamic. This is great for reusability, but it also changes the nature of the content since it now naturally needs server computation — which means post raw context would lack the content that was there before (RSS, email, etc).

Outside of looking at these mechanisms one by one to include this generation, the other options is one that Gutenberg has prepared for from the start, which is mixing dynamic and static content. Instead of returning `null` on the save function of reusable blocks, we can return the HTML as a fallback copy. As with any fallback, the issue is that it might stop reflecting truth if the reusable block is edited in another post context. But this fallback content is only used as a snapshot since rendering the post through `the_content` will always reflect the latest status.

```html
<!-- wp:block {"ref": 123} -->
<p>The original block's HTML content, which is sourced dynamically when rendering the post in dynamic contexts.</p>
<!-- /wp:block -->
```

Yet another alternative — which is what I generally suggest for dynamic blocks that want to set some fallback content — is to think of the dynamic content in terms of canonical resources. The "latest posts from category x" block can save a `See: example.com/category/x` link in the HTML for the cases where latest posts cannot be generated.

```html
<!-- wp:latest-posts {"category":"x"} -->
<p>See <a href="http://example.com/category/x">example.com/category/x</a>.</p>
<!-- /wp:latest-posts -->
```

What would an ideal markup for a reusable block with the above context? Maybe it is a link to the post itself. Maybe the user can configure it (though this seems too heavy).

Thoughts?

**Comment by noisysocks** [comment]
> Outside of looking at these mechanisms one by one to include this generation 

Where exactly do we display a post's raw content without calling `the_content`/`render_callback`? 

> As with any fallback, the issue is that it might stop reflecting truth if the reusable block is edited in another post context

One can imagine scenarios where this would be mildly disastrous:

1. Annie creates a scheduled post with a reusable block containing her store's opening hours
2. Later, she goes to the Contact page, inserts that reusable block, and edits it to changes the hours
3. When the scheduled post is published, subscribers get an email with the wrong store opening hours!

Another edge-case to consider: what happens when a reusable block is deleted? Should all posts and pages that use that reusable block render the fallback content instead? (Currently, they render `null`.)

**Comment by ChemicalSailor** [comment]
I have a potentially related issue: I'm working on a plugin that creates a dynamic block (saves null) and just for fun I went and deactivated the plugin. On the frontend it doesn't get rendered, which is expected, but in the editor it falls back to an empty classic block which is not a good UX. Definitely don't want to be deleting the block out of the content, but some kind of fallback content to notify the user would be useful.

**Comment by dmsnell** [comment]
Dropping my thoughts here since I've been concerned about reusable blocks in the same way.

It seems like the general idea of a reusable block needs some behavior toggles to give authors choice in what they publish.

With one toggle we select whether we want to provide the static fallback render.
![screen shot 2018-09-24 at 9 57 02 am](https://user-images.githubusercontent.com/5431237/45956333-39512980-bfe0-11e8-89ee-da1a1d696fe0.png)

With another toggle we select if we want the reusable block to be "hybrid dynamic static" with a link to the canonical resource.

![screen shot 2018-09-24 at 9 59 37 am](https://user-images.githubusercontent.com/5431237/45956467-951bb280-bfe0-11e8-8f3a-3068646d4096.png)

![screen shot 2018-09-24 at 9 59 41 am](https://user-images.githubusercontent.com/5431237/45956476-977e0c80-bfe0-11e8-9822-76689ce828f3.png)

Whether or not the out-of-sync data _should_ show is something I believe will be determined on a case-by-case basis. I'd rather an old logo appear than no logo, for instance. Having options in the block inspector would give me the choice.

What format would the canonical link take? Don't know, but there's some sense that the block would be some encapsulated bit of the page. We could annotate it in some way with a standard link format, even if it were akin to a figure caption.

**Comment by mtias** [comment]
I am going to close this as I think things are fine for now. An overhaul of "search" in general in a world of blocks is something that would be a nice project to do in the future.
