### ISSUE TITLE
Showing global style's title on inspector

### ISSUE THREAD

**Issue by Olein-jp** [WordPress/gutenberg#44730]
## What problem does this address?
Now we are going to change global style, we can see style's panel which show color stylying.
But if we make looks like similer global style, we'll not easy to choice which is our favorite, which is before one.

## What is your proposed solution?
I think better to show global style's title which we set in global style's json, not only a bit coloring information.
It's easy to choice completely different style like light or dark. But not many like this.

![9a8e3b0c-9af9-45a0-ba6a-a56e2023ce2d](https://user-images.githubusercontent.com/28924629/194283751-76197c55-6aec-4761-88cb-47c6357c0a65.png)

**Comment by jasmussen** [comment]
The style cards are intentionally designed to show the visuals first, and the title on hover and focus. This works well for TT3:

<img width="269" alt="Screenshot 2022-10-10 at 11 27 22" src="https://user-images.githubusercontent.com/1204802/194835941-389ef180-15d5-4974-bc0e-8db7014b8cb5.png">

In showing the same basic shape, in my opinion, those style cards provide a clear indication that they are changing the style of the current theme, which can be useful since you can also change themes.

I recognize that there are cases where two style variations may look very similar. I like to think that there are some opportunities here for iterating the current style card.

**Comment by Olein-jp** [comment]
> and the title on hover and focus. This works well for TT3

Is this working on TT3? I couldn't reproduce on my local TT3 on 6.1 beta 3 like [this](https://github.com/WordPress/twentytwentythree/pull/269#pullrequestreview-1135302225).

Showing theme color with shape is so beautiful I think, so I understood your opinion.

**Comment by jordesign** [comment]
I'm seeing this working correctly (showing the style title on hover) in 6.2.2. I also see it working correctly in the Site Browser view in 6.3 RC3.

I'll close this issue for now - but feel free to re-open if I've missed something.
