### ISSUE TITLE
Template Part: Replace flow for footer in TT3 shows very small preview

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#44844]
### Description

When replacing a footer template part using TT3, I noticed the template preview was basically nonexistent, making it both hard to see and hard to select. 

Of note, the current header & footer patterns aren't visible right now and that's been reported here: https://github.com/WordPress/gutenberg/issues/44843

### Step-by-step reproduction instructions

1. Use 6.1 beta 3.
2. Activate TT3. 
3. Head to Appearance > Site Editor.
4. Create a new footer. Save it.
5. Select the footer > Select the three dot menu > select "replace".
6. Notice the default TT3 footer is very tiny and hard to select/see. 

### Screenshots, screen recording, code snippet

<img width="1494" alt="Screen Shot 2022-10-10 at 7 27 28 PM" src="https://user-images.githubusercontent.com/26996883/194966961-1297ad90-3280-4c80-a88f-d6b700514763.png">

### Environment info

- WP 6.1-beta3-54428
- No GB
- TT3
- Chrome 106.0.5249.61

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
It looks like the Footer in TT3 only has a pattern block within it:
```html
<!-- wp:pattern {"slug":"twentytwentythree/footer-default"} /-->
```

So I think the problem is around showing patterns within pattern previews, which I remember there was another bug report for.

This is the one - https://github.com/WordPress/gutenberg/issues/39732. The linked PR does fix it when I tested ([Try nested patterns previews with block editor setting](https://github.com/WordPress/gutenberg/pull/44784#top)), so I think this can be considered a duplicate.

**Comment by annezazu** [comment]
Sweet! I trust your read there and will close this out.
