### ISSUE TITLE
Screen re-jiggers after tapping the + menu on Android

### ISSUE THREAD

**Issue by designsimply** [WordPress/gutenberg#45]
Steps to reproduce:

1. Go to https://wordpress.github.io/gutenberg/ using an Android device.
1. Tap on the heading content block at the top.
1. Scroll down and tap the (+) icon at the bottom left.

<strong>Result:</strong> a disorienting screen re-jigger happens. (<a href="https://cloudup.com/croVHGjQkVn">24s</a>)

Aside: this might be a "normal" Android thing? (I've recently switched from iOS to Android.)

Tested with Chrome on a Pixel with Android 7.1.1.

**Comment by jasmussen** [comment]
Can't find the ticket for whatever reason, but @mtias suggested showing the insertion dialog _above_ the plus instead of _below_. It could look like this:

![insert](https://cloud.githubusercontent.com/assets/1204802/22820886/f4ecd80e-ef78-11e6-9836-20bbda4ec311.png)

That might alleviate some of the scroll issues.

**Comment by jasmussen** [comment]
Closing and redirecting to #44, as the place to discuss mobile specific UI.
