### ISSUE TITLE
Link popup is misplaced if editor is not focussed

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#45009]
### Description

If the editor itself isn't focussed then the link popup UI appears in an incorrect position.

![image](https://user-images.githubusercontent.com/1277682/196125903-fab447e1-56c6-4ce5-a734-8a8d0e950095.png)

### Step-by-step reproduction instructions

1. Start a new post and enable top toolbar mode
2. Click into the first paragraph to show the formatting tools
3. Click out of the paragraph to remove focus (i.e. open block settings, click into a text field)
4. Click the link button in the top toolbar formatting tools
7. Note the popup appears in the top left corner

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1277682/196129050-e6980fcc-210c-4ca7-83fb-9f29c4959513.mp4

### Environment info

- WordPress 6.0.2
- Gutenberg 14.3.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by getdave** [comment]
I was able to replicate this. I've learnt that the `range` value is different when you're cursor is within the block in the canvas vs when you are focused in an input in the inspector controls.

https://github.com/WordPress/gutenberg/blob/f6f7afe873febc29643e0f05cc0b835ed79dc48a/packages/rich-text/src/component/use-anchor.js#L48

The bounding rectangle (which is important for positioning) is therefore different because it is called on the `range`

https://github.com/WordPress/gutenberg/blob/f6f7afe873febc29643e0f05cc0b835ed79dc48a/packages/rich-text/src/component/use-anchor.js#L53-L55

This is why the positioning is off. We need to correct this...somehow.
