### ISSUE TITLE
Localized patterns are loaded twice in the inserter

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#45013]
### Description

When using a localized WordPress, the pattern inserter shows both localized patterns and unlocalized (english).

### Step-by-step reproduction instructions

- Use a localized WordPress version. For example, set WordPress to Spanish.
- Add a new post and open the pattern inserter.
- Open the modal.
- Navigate the "Featured"/"Destacados" until you see the "Medios y texto con imagen a la izquierda"/"Media and text with image on the left" pattern.

My expectation is that if a pattern is localized, the unlocalized version (English) should not be present. What happens is that both of them are displayed. See the top-left pattern (localized) and the bottom right pattern (unlocalized) in this image:

![image](https://user-images.githubusercontent.com/583546/196145501-2eeca432-5b7d-48ec-a9be-25e6be3ed7a9.png)

### Environment info

- WordPress 6.1 RC1.
- TwentyTwentyTwo.
- Gutenberg 14.3.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ockham** [comment]
I can repro this in WP 6.1 RC3, Twenty Twenty, no Gutenberg, language set to Deutsch:

![Bildschirmfoto 2022-10-26 um 12 14 21](https://user-images.githubusercontent.com/96308/198000927-5d549cdc-3e5b-4dde-8b64-36ebf9e1ee10.png)

**Comment by Mamaduka** [comment]
I think this is a Pattern Directory issue. When requesting remote patterns with non-English locale, it returns both localized and non-localized patterns.

The patterns returned from the directory have no unique slug, so we generate them using titles. Since titles are localized, the `$is_registered` check fails to prevent duplicates.

I've used the following URLs for testing:

```
// Core patterns
http://api.wordpress.org/patterns/1.0/?locale=es_ES&wp-version=6.1&pattern-keywords=11

// Featured patterns
http://api.wordpress.org/patterns/1.0/?locale=es_ES&wp-version=6.1&pattern-categories=26
```

Cc @ryelle

**Comment by ryelle** [comment]
This is a pattern directory issue, and there's an issue here about it: https://github.com/WordPress/pattern-directory/issues/314

> The patterns returned from the directory have no unique slug, so we generate them using titles.

Patterns in the directory do have unique slugs, they're just not returned via the API (I don't think that was entirely intentional). However, it probably wouldn't help, because the slugs are also unique between patterns, for example `three-columns-of-text` and `three-columns-of-text-es_es`.

**Comment by Mamaduka** [comment]
Thank you, @ryelle!

I will close this issue and remove it from WP 6.1.1 project board.
