### ISSUE TITLE
ESLint errors on missing JSDocs on React component methods

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#4504]
## Issue Overview

Currently ESLint errors if there are no JSDocs on modified React component methods. IMHO, I don't think methods such as `render` and `keyDown` all need JSDocs. Additionally there have been tons of missing JSDoc warnings for a while, which is kind of frustrating to go through during development.

## Screenshots / Video

<img width="679" alt="screen shot 2018-01-16 at 09 46 03" src="https://user-images.githubusercontent.com/4710635/34979931-1f15af1c-faa3-11e7-94c7-cb6afc3156e2.png">

<img width="294" alt="screen shot 2018-01-16 at 09 46 38" src="https://user-images.githubusercontent.com/4710635/34979938-233316de-faa3-11e7-831f-a2d3cae70422.png">

**Comment by Soean** [comment]
Related to #4245

**Comment by pento** [comment]
I've been thinking about this a bit, and I'm inclined to agree that JSDocs shouldn't be required for re-implemented component methods.

These docs have little value for parsing out of the project, as the methods are never exported - appropriate inline comments in each method are far more valuable. Much of the content in JSDocs for these methods (`render()`, in particular), should be in the component docs.

At any rate, the current `eslint` output is super spammy, and makes searching for actual problems impossible - that needs to go.

@atimmer, @ntwb: If WordPress `eslint` plugin can be configured to not throw warnings on re-implemented component methods, please do that. Otherwise, #4245 needs to be reverted.
