### ISSUE TITLE
Zoomed out view: selection area on mover tool is slightly off

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#45088]
### Description

When using the experimental zoomed out view, the focus of the movers is just slightly off. cc @youknow

### Step-by-step reproduction instructions

1. Turn on the zoomed out view in Gutenberg > Experiments.
2. Head to Appearance > Editor.
3. Turn on Zoomed out view.
4. Notice when you select the movers, that the selection area is a bit off. 

### Screenshots, screen recording, code snippet

Zoomed out view:

<img width="221" alt="Screen Shot 2022-10-18 at 4 41 54 PM" src="https://user-images.githubusercontent.com/26996883/196565074-43e1f9aa-bbf2-4fe2-b533-d0419fddca9a.png">

Normal mover tools:

<img width="173" alt="Screen Shot 2022-10-18 at 4 43 01 PM" src="https://user-images.githubusercontent.com/26996883/196565171-d30f7219-b7d4-40f2-b279-db29bde50e02.png">

### Environment info

- WP 6.1 RC2
- GB 14.3.1
- TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by noisysocks** [comment]
I think you meant to cc. @youknowriad :)

**Comment by annezazu** [comment]
Hah! Yes. Thank you.

**Comment by youknowriad** [comment]
How do you "select" a block mover. I'm finding it hard to focus.

**Comment by annezazu** [comment]
In this case, I was using tab to move around it or just hovering over top of it to have that show.

**Comment by t-hamano** [comment]
I came from [the comments on this PR](https://github.com/WordPress/gutenberg/pull/44241#issuecomment-1305195062).

I don't think this issue is a regression of #44241. Reverting #44241 does not seem to correct the problem.

![focus](https://user-images.githubusercontent.com/54422211/200842907-b4b1cfff-247d-44fc-9f65-1dc7f2c918c6.png)

Then the size of the block mover button is different in the normal editor and in the zoomed out view. It is **36px** wide in the normal editor and **48px** wide in the zoomed out view.

I think that the override of the button width and focus outline might be reduced by unifying the width to 36px. If this direction is appropriate, I would like to try to fix it.

Button width is 36px:

![normal-editor](https://user-images.githubusercontent.com/54422211/200846055-2a29f944-812c-4ae1-ac09-62e1ef166d6a.png)

Button width is 48px:

![zoomed-view](https://user-images.githubusercontent.com/54422211/200846073-634b3a01-b3f1-4d72-bcc6-958997af4bc5.png)
