### ISSUE TITLE
Improve the Posts Page edit experience

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#45099]
The posts page is unique in the sense that it will always resolve to display a specific template (either Home or Index). This is detailed in the template popover:

<img width="349" alt="Screenshot 2022-10-19 at 09 36 58" src="https://user-images.githubusercontent.com/846565/196640568-f8b10e85-927e-4fff-b4af-c857e03fee63.png">

But otherwise the edit experience feels like any other page. You can add blocks and so on, but they will never actually appear on the frontend because the Query Loop block in the Home or Index template will only display posts. You can add a parent page, a Feature Image, manage discussion options... but none of this will have any affect on the display. All of this combines to create a rather confusing experience.

One option to explore would be linking to the Site Editor to edit the relevant template, but there are likely others to explore.

**Comment by fabio-blanco** [comment]
Oh my God!!... Two days trying to figure out how to create a posts page!
Indeed @jameskoster you're right, that's a terrible experience!!

It turns out that all I needed was to create a blank page with any template and set it as the "posts page"!

If the the content of the page is irrelevant why to force the user to choose a blog page? It could just use the default home.html or index.html and just let the user choose the page slug.

If the user is able to choose the page to use as a blog page then please allow the user to edit the page template.

That's a really bad usability experience for any one that wants to use a static page as a starting page and also have a blog page!!

**Comment by jameskoster** [comment]
> why to force the user to choose a blog page?

If I recall correctly it works this way because some classic (PHP) themes would provide template compositions with multiple queries which enable the Posts Page to display the content of that page _in addition_ to the latest posts. This doesn't exist in block themes which is why the experience is so awkward, but we do still need to support classic themes.

**Comment by emdashftw** [comment]
I was extremely confused because of that dialog on how to setup the "Posts page" in such a way that I could use different templates and not just the `home.html` template.

Since it says that the template cannot be changed. I thought that the only way to use different custom templates would then be to unset the posts page (`--select--` option) in the "Your hompage displays" section, and then go to a page "Quick Edit" > "Template" to set my custom template (with query block markup). But if you do that, the Query Block just don't populate the posts lists... I guess, it should be without context or something like that.

I have only understood how it's done when I installed the TT4 theme, and analyzed how the theme implements the different pages (portfolio / business / blogging). So I went to the "Blog Home" template, and then I saw this:

![image](https://github.com/WordPress/gutenberg/assets/679512/94dc1a31-51e3-426e-9435-4f656ea7309a)

I was completely ignoring that it was possible to replace "the content" of the template from there.

I think that is easy to visually miss that menu option or to forget about that it even exist. Maybe the option shouldn't be so hidden in the menu, and be in the sidebar below the description.

I think I would delete the highlighted message in yellow "The posts page template cannot be changed". That is the confusing part. And I would do something like that:

![image](https://github.com/WordPress/gutenberg/assets/679512/934535ef-3ad2-4f56-97f3-ab8d554f62f5)

So you can pick, what template to replace.

![image](https://github.com/WordPress/gutenberg/assets/679512/bac9918d-2a84-47d7-9aed-27d8d2ac27fa)

I don't know if this could be done. But It's what would make most sense to me.

I also think that this page `https://wordpress.org/documentation/article/template-editor/` should illustrate/highlight that you can replace "the content" of the template from there (using Template Types). And that it should explain the difference between editing a template, and replacing "the content" of a template.

**Comment by jameskoster** [comment]
> So I went to the "Blog Home" template, and then I saw this

That affordance only appears if the active theme supplies patterns associated with the template, but it might be worth including some in core too. I agree it could be more prominent, and that's what https://github.com/WordPress/gutenberg/issues/44582 aims to achieve. 

We might reuse that design when editing pages that intrinsically resolve to specific templates like Front Page and Home. To connect a dot, I suggested this [here](https://github.com/WordPress/gutenberg/issues/52335#issuecomment-1774804430) as well cc @richtabor.

**Comment by jameskoster** [comment]
I guess this is mostly a duplicate of https://github.com/WordPress/gutenberg/issues/29821
