### ISSUE TITLE
Revision Compare: show diff between custom template and theme template

### ISSUE THREAD

**Issue by georgeh** [WordPress/gutenberg#45290]
## What problem does this address?
When viewing the history of a template or template part in the revision compare screen, the oldest revision is empty and listed as "Removed":

![image](https://user-images.githubusercontent.com/128240/197844905-24fb949c-be41-4db2-a2a9-60af6d7388d7.png)

## What is your proposed solution?

When comparing templates or template parts, the oldest version should be the theme-supplied version on the filesystem. Also, choosing to restore that version should do the same as the "Clear customizations" action when browsing templates and template parts.

**Comment by carlomanf** [comment]
The template and template part post types are registered with `$args['show_ui'] = false` so I'm honestly surprised that this screen is available at all. Not saying that there shouldn't be a way to edit revisions for these post types, but if I registered a post type with `$args['show_ui'] = false` then I would expect access to all editing screens including this one to be barred.

**Comment by carlomanf** [comment]
Further to the above, I would argue the output on this particular screen is correct. The reason is it's a generic interface that is intended to work with conventional post types. Templates and template parts are not conventional post types, and it should be expected that their unconventional implementation might cause unexpected effects with the generic editing screens, such as the one reported here. Hence they are registered with `$args['show_ui'] = false` and why this screen should not be available for these post types or for any that are registered with `$args['show_ui'] = false`.

Diluting a generic interface to accommodate a special case with a particular post type does not seem like the right approach and will just cause issue after issue, similar to the historical use of auto-drafts to represent file-based templates.

**Comment by annezazu** [comment]
Noting that this matches the discussion here: https://github.com/WordPress/gutenberg/issues/50675 Closing out as a result of what's found there. Happy to reopen if I'm missing something!
