### ISSUE TITLE
Writing flow: cannot keyboard delete paragraphs with preceding Columns/Group

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#45436]
### Description

When the `backspace` key is pressed in an empty paragraph block or heading block, the block is deleted and the focus is shifted to the previous block. I think this is the expected behavior.

However, in WordPress 6.1(with or without Gutenberg ) if the block is preceded by a group or column, the block is not deleted, but wrapped in the previous block.

I think this is a bug, not an expected change.

### Step-by-step reproduction instructions

See screencast.

## WordPress 6.0

https://user-images.githubusercontent.com/54422211/199179430-ec05ee9e-69eb-4b8a-91c6-31d170f88ea5.mp4

## WordPress 6.1

https://user-images.githubusercontent.com/54422211/199179440-768f2713-6f94-470f-8ae9-ad926e51a74c.mp4

### Environment info

- OS: Windows 11
- WordPress version: WordPress 6.1-RC6
- Gutenberg Version: 14.4.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by stacimc** [comment]
I tested and was able to reproduce this with:
* WordPress 6.0.3
* Gutenberg 14.4.0
* TT1 blocks
No other plugins active.

**Comment by carolinan** [comment]
I am able to reproduce this with 6.1 but not 5.9.5.

I believe this trac issue is a duplicate: [core trac 57010](https://core.trac.wordpress.org/ticket/57010).

>  I use the group block a lot on my sites as a kind of wrapper for all the site content. I have noticed since 6.1, when you delete the top element in the group using the delete key, the whole group gets removed. I made a video.
[https://www.loom.com/share/275f988018b24145b7065d9f00e5c3cb](https://www.loom.com/share/275f988018b24145b7065d9f00e5c3cb)
I only hit delete on my keyboard enough times to remove the headers letters but when you remove the last letter the group block goes too.

**Comment by priethor** [comment]
Is there any update on this issue, @vcanales ?

**Comment by vcanales** [comment]
@priethor, I haven't been able to crack this one yet; it's a bit of a head-scratcher since it involves going deep into parts of Gutenberg state management that I haven't explored yet. I might need to tap into some other minds on this. I'm wondering, though, where it would be best to bring it up. I'll raise the issue in the Making WordPress Slack before the next meeting, but I'd appreciate any other suggestions.

**Comment by priethor** [comment]
Thanks for the update, @vcanales! Maybe @ellatrix can help here, as she's more familiar with the writing flow.

**Comment by ellatrix** [comment]
The problem here is that, when we try to merge two blocks, we attempt to convert the selected block to the block we're trying to merge into, and then merge its inner blocks. For example, when you merge a paragraph or heading into a quote, we convert the paragraph or heading to a quote, and then merge those two quotes.

Now in the case of Columns this is interesting: we convert the paragraph to a Columns block (which is possible since there's a transform), and then we merge these two Columns blocks together. It's a bit strange but not totally weird. The reason why it looks broken is each Column block having a width attribute, and those are not correct after merging. E.g. 50/50 becomes 50/50/100.

Now there's several solutions here:

* Fix the widths, and  allow backspace from a previous to create an additional column. This is weird though, although another backspace would remove the extra column. Jarring experience though.
* Remove the paragraph => Columns transform (which creates a single Column with a paragraph). I'm not sure how useful this transform is. I think it's a bit weird.
* Add an API so an exception can be made.

**Comment by ellatrix** [comment]
Does anyone have any opinions?
