### ISSUE TITLE
Pattern Inserter: consideration to always show each pattern title

### ISSUE THREAD

**Issue by samiff** [WordPress/gutenberg#45595]
## What problem does this address?

In #44028 it looks like the pattern item title was visually hidden:

https://github.com/WordPress/gutenberg/blob/25aa4b41d46d8a8ab9650e79d787a9d09f0dceb3/packages/block-editor/src/components/inserter/style.scss#L314-L316

While that may work well for patterns with a lot of visual variation between them, I'm finding it a step back for patterns that are less visually striking. Here is an example where a third-party plugin has registered a pattern category with different form patterns:

![Screenshot 2022-11-07 at 3 42 12 PM](https://user-images.githubusercontent.com/15803018/200431928-a369d76f-69b3-4254-aeec-42e19c9bee2f.png)

It's difficult to make sense of which form pattern to add. I do note that the above screenshot is for a desktop screen resolution. The individual pattern titles are visible from a mobile resolution as seen here:

![Screenshot 2022-11-07 at 3 41 53 PM](https://user-images.githubusercontent.com/15803018/200432179-831cdff0-d07c-4797-a640-b04ace59be17.png)

And here is an example for the "Footers" pattern category:

![Screenshot 2022-11-07 at 4 00 28 PM](https://user-images.githubusercontent.com/15803018/200433589-c640d3dc-7508-4c0e-8c9a-a8e64417fe70.png)

That seems very confusing to me especially if I had not used patterns much before. Do I just click & undo until I find what I need? Versus the UX with titles:

![Screenshot 2022-11-07 at 4 03 25 PM](https://user-images.githubusercontent.com/15803018/200433975-8f22978c-a50c-4dc5-bca4-7639c61079a2.png)

## What is your proposed solution?

For each pattern's title to remain visible on all screen resolutions, for example:

![Screenshot 2022-11-07 at 3 49 58 PM](https://user-images.githubusercontent.com/15803018/200432049-43e10734-a9b8-4bc3-9e5b-1e1d3d132a1c.png)

CC: @annezazu via https://github.com/WordPress/gutenberg/issues/41379#issuecomment-1306229482

**Comment by annezazu** [comment]
Thank you! Tagged away and noting for @jameskoster.

**Comment by jameskoster** [comment]
Aside from some less common instances I don't think the pattern titles are adding much value in this view. Ideally choosing a pattern should be a visual affair, and the noisy text disrupts that quite a bit. Not to mention the fact that they reduce the number of patterns visible in the column at any one time which also feels like a negative.

Trying to read between the lines, it seems like the biggest issue here is that the previews aren't large enough for you to delineate the difference between some patterns. The contact forms is a good example. Observing the issue through that lens might yield different potential solutions? 

Perhaps it should be possible to increase the width of the patterns column? Or maybe we should flip the widths of the inserter/pattern columns... it's a little strange that the latter is smaller than the former. Another option would be to offer a shortcut to browse the patterns in the explorer.

I'm sure there are many other options to consider, but ideally we avoid the text labels simply because they aren't useful most of the time.

**Comment by samiff** [comment]
> Ideally choosing a pattern should be a visual affair, and the noisy text disrupts that quite a bit.

This seems to be a heavily guiding statement, and I wonder how it aligns with information currently found in the [handbook](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-patterns/)?

> Block Patterns are predefined block layouts, available from the patterns tab of the block inserter.
> 
> The properties available for block patterns are:
> `title` (required): A human-readable title for the pattern.
> `description` (optional): A visually hidden text used to describe the pattern in the inserter. A description is optional but it is strongly encouraged when the title does not fully describe what the pattern does. The description will help users discover the pattern while searching.

Viewed more abstractly, Patterns are just groups of blocks. While these groupings of blocks _could_ be highly visual, that is not a certainty especially as more third-party developers leverage the feature.

> it seems like the biggest issue here is that the previews aren't large enough for you to delineate the difference between some patterns

Again, this seems to assume that a pattern's visual representation alone would provide understanding of what the pattern provides. The "Explore all patterns" button does currently provide larger pattern previews with titles. Here is an example of that window _with titles removed_ for the "Query" pattern category:

![Screenshot 2022-11-08 at 10 55 57 AM](https://user-images.githubusercontent.com/15803018/200639955-2fb36e7b-4b19-422f-a94c-507379589c3c.png)

That does not inspire confidence in selecting a pattern to me. And currently the process of adding a pattern, not liking it, and wanting to remove it can be tedious (there is no quick undo feature).

**Comment by carolinan** [comment]
I agree with @samiff here, having the title visible helps me select the correct pattern for the "job".
I personally do not find the title noisy.

**Comment by jasmussen** [comment]
I think we should definitely show both borders and titles in the pattern modal, and it's part of [this design that also connects it to the pattern directory](https://github.com/WordPress/gutenberg/issues/44611). However for the sidebar inserter, the balance isn't as clear to me. It is always the case with design that if everything is loud, nothing is loud, which is why I empathise with the intent to minimize distractions across the board. As far as solutions go, are there options other than permanently listing out all pattern titles? Such as show them on hover/focus? Perhaps show them only for [site building patterns](#44501)?

**Comment by samiff** [comment]
> I empathise with the intent to minimize distractions across the board.

In my opinion, a pattern's title is _critical_ information that should always be displayed. A pattern preview (even at larger sizes) does not always fully encapsulate what a pattern provides to a user. Hopefully that has been illustrated by some of the examples (core included) shared here.

> Such as show them on hover/focus?

This would be an interesting compromise, though my personal vote would be to always display the title.

**Comment by jameskoster** [comment]
Dare I suggest a switch in the Patterns panel to toggle title visibility?

**Comment by jasmussen** [comment]
Such would be the "Show labels" option, right? Perhaps that could show them always, otherwise they'd appear on hover/focus. Not sure.

**Comment by jameskoster** [comment]
I was thinking more literal:

If the switch is on then titles appear beneath the patterns, like they do in the Explorer. If it's off then they're hidden entirely.

Positioned differently, but you get the idea:

<img width="650" alt="Screenshot 2022-11-10 at 12 41 36" src="https://user-images.githubusercontent.com/846565/201094286-a9d2c84d-30a9-4d83-af7d-f0a294f21fc1.png">

**Comment by johngodley** [comment]
A +1 to viewing titles - they are important, particularly if it's hard to tell what a pattern is visually (or to see what the difference between similar patterns is).

As an alternative suggestion maybe a pattern could supply it's own preview layout?

#28135

This means a mostly text-based or abstract pattern, where a direct preview doesn't really add any value (it will always be too small), could decide to use an alternative and more visually relevant representation.

**Comment by jasmussen** [comment]
I don't think we should have a toggle for titles — I think we need to decide on always, hover/focus, or otherwise.

**Comment by digitalwaveride** [comment]
Also +1 for titles.
We are currently working on forms and would see many patterns that differentiate themselves not (just) visually but especially by the functionality of the input blocks. Even if users could identify labels on input fields, it takes a lot of effort to understand the topic of the form.

**Comment by javierarce** [comment]
The recently implemented Media tab shows titles on hover/focus and it seems a good compromise to me: you get a compact column that just shows the content, but you can get extra information if you want.
