### ISSUE TITLE
Fix Nav block anchor link closing

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#45608]
> If this was the fix recently included in 6.1, it does not cover the common case of a link like `/#anchor` or `/some-page/#anchor`. It only works if the `href` exactly starts with `#`. So if you are on `/some-page/` and you click the `/some-page/#anchor` link, it will scroll down to the anchor, but the modal will remain open.
> 
> My current fix:
> 
> ```js
> import MicroModal from 'micromodal'
> 
> // Fix navigation block
> const links = document.querySelectorAll('.wp-block-navigation-item__content')
> 
> for (const link of links) {
>     const modal = link.closest('.wp-block-navigation__responsive-container')
>     const id = modal?.id || ''
> 
>     if (id && link.href.indexOf('#') !== -1 && link.pathname === location.pathname) {
>         link.addEventListener('click', () => {
>             if (modal.classList.contains('has-modal-open')) {
>                 MicroModal.close(id)
>             }
>         })
>     }
> }
> ```

@draganescu I looks like we'll need a bug fix PR for this.

_Originally posted by @getdave in https://github.com/WordPress/gutenberg/issues/39625#issuecomment-1307585747_

**Comment by coreyworrell** [comment]
Just a note for the simple fix mentioned above, it may be good to check that the `link.hostname` matches as well to prevent a link like `https://other-website.com/blog/#anchor` from being included while on `https://my-website.com/blog/`. 

Then again, closing the modal when clicking an external link probably doesn't pose any issues either.. Honestly since submenus are triggered by buttons (afaik), the modal should probably close after clicking any link. Unless that is just undesirable to see the menu close before the browser navigates to the next page.

**Comment by getdave** [comment]
@coreyworrell Thanks very much for the feedback and observations. That's really helpful.

I wonder, would you consider submitting a PR to fix this feature? I'm not sure whether it would be your first PR on this repo but I would be more than happy to help you through the process if that's of interest.

What do you think? All contributors received props on the Gutenberg Plugin releases and ultimately in WP Core.

**Comment by coreyworrell** [comment]
@getdave sure, just created a pull request #45829
