### ISSUE TITLE
Gallery block: Invalid JSON response error when try to upload images 

### ISSUE THREAD

**Issue by gyurmey2** [WordPress/gutenberg#45714]
### Description

I can attach images from media library but not via the direct upload in editor. Initially images seem to upload alright and a preview is shown on the gallery. A few seconds later an error message is displayed on the Gallery block: `The response is not a valid JSON response`.

### Step-by-step reproduction instructions

1. Add a gallery block.
2. Select all images from [WeTransfer](https://we.tl/t-ZknJZ9VqzJ) and try upload them.

### Screenshots, screen recording, code snippet

![wp](https://user-images.githubusercontent.com/113413673/201227943-b83d8077-ec14-42ee-b0cb-f5daa98c9011.png)
![cpu](https://user-images.githubusercontent.com/113413673/201228759-d3c3ccb6-23f6-488b-82e3-34f60db00d3f.png)

### Environment info

WordPress: 6.1
Theme: TT3
Without any plugins installed.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
This issue was reviewed during today's Editor Bug Scrub. Unfortunately, we have been unable to replicate the issue. Can you provide more details about the images you are attempting to upload, such as the size? We are not able to access the WeTranser link.

**Comment by gyurmey2** [comment]
The link to WeTransfer has expired ([new one here](https://we.tl/t-ipQDG0Ek7K)). Thanks!

**Comment by gyurmey2** [comment]
@ndiego, @t-hamano, the [problem still exists](https://dewranglers-naku.instawp.xyz/sample-page/).

[Auto login](https://eiacgcg.r.af.d.sendibt2.com/tr/cl/DVfB7aMpPtBZv0ZQrsN2kE5UfXbnn4kHh0K0QPZio_BA2h43dPG0DGLJp8JGmg25gEY6dM8EcEO3U0aEN4rsWsSLBdjXwW3osHqMpCAXEdhniH1a-7xHSJyI01oGvn-pbdbUXsHOvv4_qXQ21oSwd_59-CGu8C1Uv2ekPZCpAlo45Ba2cNieRIrFVNvbbEHg9Dn8n24Ihznc9piSxKCXnizjDKFtmzCIb77r58Ed6tiVFWpHo2QmULlUIFBhHwdk1zYWuL7knvqSfUtlr-QJwQERs2tiXD0-Tp4LRE0iFpJfqTnMJqUhdo3F757uC2PzO9xS1LuENnbGbbORSAL0sOGoesTGIYybzb0P9qqPy3w) + [Images to download.](https://we.tl/t-NovU9Nbo8N)

**Comment by t-hamano** [comment]
@gyurmey2

Thank you for providing the environment.
I was able to reproduce it.

The error appears to be caused by the server returning a 408 error, causing the `apiFech` to time out. Perhaps if you upload a few pictures at a time, you will not encounter any errors.

I think this error is server dependent, but one way to improve it might be to show the error code in the snack bar.

![408](https://user-images.githubusercontent.com/54422211/211811985-f4183d44-0a76-44d6-bbdd-c999c49206cc.png)

![fetch](https://user-images.githubusercontent.com/54422211/211812084-99755411-e5d8-4695-b939-dc545aad9888.png)

**Comment by gyurmey2** [comment]
@t-hamano, thank you for checking it out and it looks like you're right.

Btw, you would check [this issue](https://github.com/WordPress/gutenberg/issues/46876)? [Same WP install](https://app.instawp.io/wordpress-auto-login?site=$2y$10$PzPOWPWEbD8O9BTsEQnjFeg8a4lv7IJC5p4eLPtfQbRdsjRFQW3LK).

**Comment by ndiego** [comment]
This issue was reviewed in today's Editor Bug Scrub. Based on the [comment above](https://github.com/WordPress/gutenberg/issues/45714#issuecomment-1378709806), this appears to be server related. Therefore, I am going to close this issue. But if I am misinterpreting this issue, let me know, and I will reopen it. Thanks!

**Comment by gyurmey2** [comment]
Thanks! The problem occurs on servers with the maximum allowable memory limit of 1GB, which is a large part of servers around the world. [Test done a moment ago on InstaWP](https://deposit-elohistic-dbe99d.instawp.xyz/sample-page/).
