### ISSUE TITLE
Padding on paragraph not behaving as expected

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#45750]
![padding](https://user-images.githubusercontent.com/846565/201636598-4e9c9ab0-4550-4524-bed8-5700d04b9181.gif)

My expectation is that the overall footprint of the Paragraph would remain the same, with the text being "squished" based on the padding value. As you can see in the gif above the Paragraph footprint grows to accommodate the padding. 

I acknowledge that my expectation is likely biased, and perhaps we need to support both `content-box` and `border-box` values. Keen to hear thoughts from others on this. Is the behavior demonstrated above what you would expect? 

cc @WordPress/gutenberg-design

**Comment by jasmussen** [comment]
Well, this is the box model challenge, right? While I personally would prefer that the text gets squished inwards (border-box), honesly I'd be fine if:

* The box model is the same in editor and frontend, so the result is the same
* The padding control and visualization is accurate to said box model

The alternative to the above would be to default to border-box across all blocks, editor and frontend. We used to do this just for the editor, but removed that because it didn't match the frontend. I don't personally have a strong aversion to such a default happening, just clarifying.

**Comment by jameskoster** [comment]
Yes it is all down to the `box-sizing` value.

> The box model is the same in editor and frontend, so the result is the same
> The padding control and visualization is accurate to said box model

This is the case currently, so perhaps this isn't an issue at all. I don't really know why, but I was surprised to see this behavior :)

**Comment by jasmussen** [comment]
Yeah and I think it's valid: the un-intuitiveness of the default box model definitely has a long history in general web-design. So I guess it's mainly whether we change the default in the editor, or put the onus on theme develoeprs to do so.
