### ISSUE TITLE
Ability to convert existing shortcodes to blocks

### ISSUE THREAD

**Issue by billerickson** [WordPress/gutenberg#4576]
## Issue Overview
If a plugin currently uses a shortcode in the post content field for including its functionality, and the plugin is updated to also implement this functionality as a Gutenberg block, can there be a method for the existing shortcodes to automatically become blocks when a user is editing the page in Gutenberg?

For example, let's say I have a form plugin that generates a form in the content area when `[form id="1"]` is added. I update this plugin to add Gutenberg support, so now there is a "Form" block that lets users select which form them want and renders a representation of that form in the Gutenberg editor. 

When my user updates to WordPress 5.0 and Gutenberg is used, (currently) the old shortcodes will remain in paragraph text. The user doesn't see the nice, new representation of that functionality as a Form block.

**Comment by youknowriad** [comment]
Hi!

The shortcode will not be automatically updated but you can defined a "shortcode" transformation to allow transforming the shortcode on paste or when the user clicks explicitely on "Convert to blocks" (for old content in the classic block).

You can see an example here https://github.com/WordPress/gutenberg/blob/master/blocks/library/image/index.js#L99-L145

This is not documented yet because the transform API is yet to be stabilized.

Good luck with your custom block 👍

**Comment by danielbachhuber** [comment]
> This is not documented yet because the transform API is yet to be stabilized.

@youknowriad Is there an existing issue to make sure the documentation is created when the API is stabilized?

**Comment by youknowriad** [comment]
@danielbachhuber not that I'm aware of, fine to open ane one.

**Comment by mtias** [comment]
Example of how it'll work on paste: https://cloudup.com/cccPqbEyXUv
