### ISSUE TITLE
Block add browser extension blocks - wp block social links 

### ISSUE THREAD

**Issue by linwoodlana** [WordPress/gutenberg#45783]
### Description

I think that would be good to acknowledge that Social links block -  get blocked when using browser extension “Adblock Plus”. Social icons/links do not show in frontend and in backend block can't be added!
I did not test with other ad blockers, so I don't know if it only happens with  “Adblock Plus”.

### Step-by-step reproduction instructions

1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
Thanks for reporting. We have tested this in today's Editor Bug Scrub, and have been unable to replicate with a fresh install of Adblock or uBlock Origin. That said, since this issue does not originate in Gutenberg itself and there is no real action we can take, and users can change their allowlists in the ad blocker settings, I am going to close this out.
