### ISSUE TITLE
Stack Block: Add space between option

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#45868]
It's not yet possible to make a design in the editor like this by distributing elements at the top and the bottom of a space.

![Pattern 8](https://user-images.githubusercontent.com/908665/202549709-f06ce7a8-f5f0-49d1-b9e2-3e16fe3c030e.jpg)

We already have a space between option in the row block, but it's missing for the Stack block.

| Row | Stack |
| ----------- | ----------- |
| ![Screenshot 2022-11-16 at 10 16 16](https://user-images.githubusercontent.com/908665/202550308-ddc75af2-2895-4cf7-b01e-78fb0e8ddce8.jpg) | ![Screenshot 2022-11-16 at 10 15 31](https://user-images.githubusercontent.com/908665/202549888-6e86e269-ab35-423a-bd43-be3e83251caf.jpg) |

It'd be great if we could add the option to Stack block.

**Comment by richtabor** [comment]
Agreed, I think this could be cool.

**Comment by andrewserong** [comment]
+1 Great idea! There's a related issue for adding in vertical alignment options for stack / vertical orientations of flex layouts here: https://github.com/WordPress/gutenberg/issues/35849. I've added this to the tracking issue in https://github.com/WordPress/gutenberg/issues/44720

**Comment by tellthemachines** [comment]
It's fairly straightforward to add this control, but what we should bear in mind is that it won't work unless the Stack has a fixed height. (This is why we didn't add it in the first place, also because we only implemented the Min-height control very recently). Could we work around that by add a warning of some sort when this option is selected?
