### ISSUE TITLE
6.1.1 block editor removes ids?

### ISSUE THREAD

**Issue by pietschker** [WordPress/gutenberg#45920]
### Description

I used the block editor function to create block ids heavily (in the extended section of the tool sidebar, creates HTML id, as in `<p id="…" …>`).  this function is missing in the 6.1.1 block editor. When I save a page with such ids, the ids vanish.
WP 6.1.1, biuilt-in block editor, theme is Kaira Overlay.

### Step-by-step reproduction instructions

Take a page that has ids, added with the corresponding 5.x block editor function.
Open it in the 6.1.1 block editor, make some random changes, save.
ids are gone.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by akasunil** [comment]
Hello @pietschker,
Can you send some more info with screenshots for better understanding of the issue you are facing ?

**Comment by pietschker** [comment]
Contrary to 5.x, the List block does not have the „HTML anchor“ input field anymore („Extended“ now only shows „additional CSS classes"):



All id anchors in List blocks are gone (I had added them via the List block’s „HTML anchor“ function in 5.9.x). When I add them again to the <ul> element im HTML edit view (in 6.1), ithey stay.
The List block has also lost most of its other settings it used to have, like list style. In fact, „Extended“ is the only setting left.

Most other block elements (paragraph, for example) seem to have kept the HTML anchor function.

Viele Grüße,
Lutz

**Comment by talldan** [comment]
@pietschker The list block should still have HTML anchor support.

What might be confusing is that the List Block now supports inner blocks. When you first add a List Block, your focus is immediately upon the 'List Item' block and not the 'List' Block itself.

You can see this in the breadcrumbs at the bottom of the block editor:
![Screen Shot 2022-11-21 at 5 43 02 pm](https://user-images.githubusercontent.com/677833/203017906-9b1af5cc-8070-4b35-ba84-318df8fb7c67.png)

If you select 'List' from that UI (or other good ways are using the 'Select parent block' button on the toolbar, or using List View), then you should be able to edit the HTML Anchor again.

**Comment by pietschker** [comment]
Ah, I see. Thanks for the heads-up! It does not explain why the existing anchors vanished, but it does not matter for me any more - they are gone anyway (and repaired, by no).

Kind regards,
Lutz

**Comment by t-hamano** [comment]
I think it may be related to #45987. When updating to 6.1.1, many attributes in the list block appear to be truncated. It might be good to test this issue again after #46000 is merged to resolve #45987.

**Comment by pietschker** [comment]
Yes, I believe this could be the same bug. Good to know where it is located so I can check the relevant posts and pages. Thanks for the update! OK for me to close or merge my request.

Kind regards,
Lutz

**Comment by t-hamano** [comment]
I have confirmed that this problem is resolved in the latest Gutenberg. Leave the confirmation steps here and close the issue.

---

### Insert a list block in WordPress 6.0.X

- In the latest gutenberg repository, put the following in `.wp-env.override.json`:

```json
{
	"core": "WordPress/WordPress#6.0.3"
}
```

- run `npm run wp-env start -- --update`
- Confirm that the WordPress version is 6.0.3.
- Deactivate the Gutenberg plugin.
- Insert a list block and register an anchor.
- Save the post and reload the browser. Confirm that the anchor in the listing block is retained.

### Update to WordPress 6.1.1 (Reproduction of the problem)

Update `.wp-env.override.json` with the following code:

```json
{
	"core": "WordPress/WordPress#6.1.1"
}
```

- run `npm run wp-env start -- --update`
- Confirm that the WordPress version is 6.1.1.
- Deactivate Gutenberg plugin.
- Open the post.
- Confirm that the anchor has disappeared from the list block. (Don't save the post.)

### Confirm that this has been fixed in the latest Gutenberg

- Activate the Gutenberg plugin.
- Confirm that the anchor is retained in the listing block.
