### ISSUE TITLE
Extensibility: Make it possible to add "Open in a new window", "nofollow" and other link options

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#4597]
## Issue Overview
The "Open in new window" link option was removed in #4583. For plugin authors it should be possible to add this function with a plugin.
This also can be useful for a "nofollow" option, see #4499

**Comment by StaggerLeee** [comment]
It should stay (open in new tab), at least as simple functions filter.
There are cases when needed. "Friends, Links, Portfolio" pages/templates.

Stupid to link to some donor/friend/sponsor and be navigated away from your website, just because of this courtesy link.

**Comment by paaljoachim** [comment]
Hmm Open in a new window should stay as a option in the UI without having to add some extra code for it.
If it clutters the link interface then perhaps have the block setting change to reflect the selection of a link box. As additional options could then be shown in the Link setting.

**Comment by iseulde** [comment]
We could create a slot in the inspector that has formatting props from `Editable` and can then be filled by a plugin. So when you select a link for example, you'd see extra options in the block inspector.

In some cases it may be more interesting to filter the links with a `the_content` filter, based on the URL, template, etc.

**Comment by paaljoachim** [comment]
Thanks Ella.

**Comment by dmccan** [comment]
Please consider adding the "Open in a new tab" option to the Gutenberg link interface. It is widely used. It is just a checkbox. It is common to use it on all external links.

**Comment by iseulde** [comment]
Even though I wouldn’t recommend doing this, there are plugins that will
automatically add this attribute to external links. Might be easier than
adding it manually for every link? Regardless, there’s a PR somewhere that
adds the UI.

**Comment by dmccan** [comment]
It's an option of the current (classic) editor ... so it is not new behavior and apparently a normal enough option. It would be more convenient to have the checkbox near the URL entry box. I'm glad there is a PR.  I'm not in a position to merge the pull request. Can you please do so?

**Comment by karmatosed** [comment]
Closing as with latest version we're adding back in open in a new window.

**Comment by juicerocket** [comment]
Please add the nofollow option in the same format as the new window option. It's also important because Google and the FTC both require "nofollow" for any paid-for link (like blogs use, for influencer marketing). It's way too difficult to add that now, with Gutenberg. It should be a toggle option like the new window option.

**Comment by Natuurlijklinda** [comment]
The nofollow option is indeed very important! I hope it will be an option soon, since the Ultimate Nofollow plugin is not working with the new layout... The rest of the new layout works very nice (uptill now), so I actually want to use. But I need the nofollow option. :) As said above, it would be nice if it's the same as the "open in new window" toggle or something like that.

**Comment by designsimply** [comment]
Noting that a new issue was created requesting the ability to add `nofollow` for links at #13542.

**Comment by StaggerLeee** [comment]
Is than "noopener" added automatically ?

**Comment by designsimply** [comment]
@StaggerLeee I found an explanation about "noopener" at https://support.performancefoundry.com/article/186-noopener-noreferrer-on-my-links.
