### ISSUE TITLE
Filtering 'code/list' by 'allowed_block_types_all', can't add list items.( only first line can)

### ISSUE THREAD

**Issue by ryota-mukeikaku** [WordPress/gutenberg#46047]
### Description

Can't create new list item( list block can create), with these code.
`
add_filter('allowed_block_types_all', function () {
    return['core/list'];
});
`

### Step-by-step reproduction instructions

Add these code on functions.php.
`
add_filter('allowed_block_types_all', function () {
    return['core/list'];
});
`

Go to /wp-admin/post.php.

Add core/list block on editor.

You can write on first list item, but you won't add new line( list item).

### Environment info

wp ver 6.1.1
mac os
google chrome

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
@ryota-mukeikaku How about if you try:
```js
add_filter('allowed_block_types_all', function () { return['core/list', 'core/list-item]; });
```

**Comment by DAreRodz** [comment]
Hey @ryota-mukeikaku, the filter you are using ([`allowed_block_types_all`](https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters/#allowed_block_types_all)), filters _all_ the block types you can use in the editor. The reason you can't add new List Item blocks is because you only allowed List blocks.

The code that @talldan shared should work in your case. 🙂

**Comment by DAreRodz** [comment]
You can take a look at this related issue: https://github.com/WordPress/gutenberg/issues/45583. Closing this one.
