### ISSUE TITLE
Navigation: Move the "add submenu" item and add an icon

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#46072]
## What problem does this address?
The "add a submenu" item in the navigation link block is hard to find.

## What is your proposed solution?
In the navigation link block, the “add submenu item” should be at the top of the ellipsis menu options with a divider below. We should also use the submenu icon to reinforce the connection.

**Comment by Humanify-nl** [comment]
Added to this; when the site has a black background color, the plus signs are black too. Making it even harder.

**Comment by getdave** [comment]
> Added to this; when the site has a black background color, the plus signs are black too. Making it even harder.

@Humanify-nl I think that's the appender in the block canvas though right? This issue pertains to the experimental offcanvas editor for the Navigation block.

If I got that wrong feel free to provide a screenshot 🙇

**Comment by Humanify-nl** [comment]
@getdave I believe you are correct sir. It is the little plus inside the submenu I am referring to.

**Comment by draganescu** [comment]
I am either not looking at this correctly or customizing the more menu for one case seems very difficult. That menu is meant to hold:

- generic options
- available for all blocks
- registered once

... and this shows in the API:

- items added via plugins are added _after_ default options
- there is no way for a block to decide to opt out of these options
- there is no way to decide which is 1st or 2nd

I am unsure how to approach this for the off canvas navigation editor component, as even if it is open to implement some workarounds, I can't see them (again, I may be looking at this the wrong way).

**Do we really need the normal block more menu? Can't we build our own for this case?**

If I were to build a smaller options menu for the experiment, some things would be more discoverable for the experiment validation. Deciding to use this special more menu could be a prop of the ListView, so that won't block a future merge of the off canvas navigation editor into the ListView.

**Comment by draganescu** [comment]
I will explore the idea of building a custom menu for the navigation block. This menu will be passed via prop and displayed instead of the normal one.
