### ISSUE TITLE
Custom Fields Block

### ISSUE THREAD

**Issue by kaffeeringe** [WordPress/gutenberg#46082]
## What problem does this address?
I use a custom fields as a "kicker" or "subtitle" or whatever you call that small headline above the real headline. I hardcoded that into my old style theme. But I can't display that in Gutenberg themes like twenty-twentythree.

## What is your proposed solution?
A block with a dropdown of all available custom fields and layout-options like the headline-block.

**Comment by masteradhoc** [comment]
@kaffeeringe thanks for the feature request. pretty much came around the same when trying FSE.

Also reached out to @polevaultweb from ACF-Team in order to see if ACF itself has something planned for this - as its our go to solution for custom fields. as i just saw your issue though i add some context also here.

We need to have some kind of an option for these two usecases (maybe you have more?)


### **UseCase 1**
You want to display a simple information you set maybe in a ACF Options Page

**Idea**: A simple block solution to choose a custom field to display. Prepared for FSE Template & Template Parts

**Possible Workaround**: use the shortcode field output see https://www.advancedcustomfields.com/resources/shortcode/ or ofc develop a custom acf block to display this. Though second option if you have to do that for a lot of fields bit much work for whats needed.


### **UseCase 2**
You want to display a information you attached in a post / page / taxonomy,..

**Idea**: A more advanced block solution to choose a custom field to display that works especially also with query loop.

**Possible Workaround**: i only see a custom acf block option here.



**Liveexample of a possible solution.**

1) See: https://wpstackable.com/blog/stackable-integrates-with-acf/
Currently i think only available with the full stackable pro plugin and not seperately. others as kadence etc. seem to offer similar stuff.

2) will go with this option or now: https://wordpress.org/plugins/display-a-meta-field-as-block
simple clean block thats focused on soley this :)


something like this natively would be a gamechanger.

**Comment by t-hamano** [comment]
[The Block Bindings API](https://make.wordpress.org/core/2024/03/06/new-feature-the-block-bindings-api/) has been released in WordPress6.5. Currently, you have to write code, but you could bind any custom field to a Paragraph block or Heading block, for example.

Therefore, I think that a block dedicated to custom fields is no longer necessary.

**Comment by SantosGuillamot** [comment]
As @t-hamano shared, you should be able to bind any custom field to a paragraph, heading, image, or button. With plans to support other core blocks in the future. Does that cover your use cases? Or is there something missing? Should we close this issue?

**Comment by kaffeeringe** [comment]
That sounds like a great solution!Am 27.06.24, 14:16 schrieb Mario Santos ***@***.***>:

   
  As @t-hamano shared, you should be able to bind any custom field to a paragraph, heading, image, or button. With plans to support other core blocks in the future. Does that cover your use cases? Or is there something missing? Should we close this issue?

**Comment by skorasaurus** [comment]
given the response from @kaffeeringe ; closing this issue =)
