### ISSUE TITLE
If the newline characters are different, the markdown notation cannot be pasted in the desired way.

### ISSUE THREAD

**Issue by tenman** [WordPress/gutenberg#46098]
### Description

If the line feed code is different, the markdown notation cannot be parsed. 　
CR/LF parsed into preformatted block, LF parsed as markdown

### Step-by-step reproduction instructions

Server gutenberg/changelog.txt download and copy paste your post ( LF )

```
== Changelog ==

= 14.6.1 =

## Changelog

### Fixes

#### Global Styles
- Fix the `upgrader_process_complete` hook for `wp_theme_has_theme_json`. ([45881](https://github.com/WordPress/gutenberg/pull/45881))
- Update `wp_theme_has_theme_json` to use `WP_Object_Cache`. ([45543](https://github.com/WordPress/gutenberg/pull/45543))

### Bug Fixes
- Ta Processor: Prevent bugs from pre-PHP8 strspn/strcspn behavior. ([45822](https://github.com/WordPress/gutenberg/pull/45822))

## Contributors

The following contributors merged PRs in this release:

@oandregal @dmsnell
```

https://github.com/WordPress/gutenberg/blob/trunk/changelog.txt (CR/LF)
View raw Click

Copy the same range as the markdown above and paste it into your post

Thank you.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

According to the thing you reported, do you mean that the line feed code is different in the downloaded file and in the file displayed as RAW data on the web?

I expect that when RAW text on the web is pasted into an editor, it is converted to a preformatted block because the RAW data is enclosed in `pre` tags:

![pre_raw](https://user-images.githubusercontent.com/54422211/204309136-38b7b199-6cd4-4eeb-bbd3-42db79f13463.png)

If there is anything I have misunderstood or missed, please let me know.

**Comment by tenman** [comment]
Please see example
https://www.tenman.info/wp3/emulsion/en/2022/11/29/markdown-example/

**Comment by t-hamano** [comment]
It would be good to explain this issue in English so that many people can check it out. I still don't understand what your problem is, but at least it appears to paste into the block editor as expected, regardless of the difference in line break codes.

https://user-images.githubusercontent.com/54422211/204417586-4b850074-9307-4f8d-afac-79f11a74e36e.mp4

**Comment by tenman** [comment]
I have confirmed that the issue you submitted does not occur in Gutenberg 14.6.1.

Thank you t-hamano.
