### ISSUE TITLE
Post Excerpt: Add align text options

### ISSUE THREAD

**Issue by beafialho** [WordPress/gutenberg#46126]
## What problem does this address?

This has been a pain point in a few designs I tried to accomplish. Currently, it's not possible to align the post excerpt text to the middle, only to the left.

## What is your proposed solution?

We should have the option to align post excerpt to the center like we do in paragraph blocks.

https://user-images.githubusercontent.com/65220155/204316591-e1492b2a-9a25-4797-bbf8-913d8505f3e5.mp4

**Comment by t-hamano** [comment]
I think this is a bug.

The excerpt block has a text-align option, but outside of the post context, the toolbar and sidebar options are not visible due to [the early return](https://github.com/WordPress/gutenberg/blob/d005420847de17be0b3111203782834c2dc85e0c/packages/block-library/src/post-excerpt/edit.js#L59-L74).

On the other hand, Post title, Post Date, Post Author, etc. have text-align options that work outside of the post context.

![post-excerpt](https://user-images.githubusercontent.com/54422211/204509115-6238fdc9-e631-4a68-bd6a-4bc03780b5cb.png)

**Comment by t-hamano** [comment]
I have found similar problems reported in #44324.  It also appears that @carolinan has submitted #45003 to resolve these issues.

**Comment by t-hamano** [comment]
I would like to close this issue as a duplicate.

**Comment by beafialho** [comment]
Thank you!
