### ISSUE TITLE
Improve empty menu state in Nav Offcanvas

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#46202]
If you create a new menu from scratch then the current "empty" state for the menu isn't very clear about what you shoudl do next. It also looks a little...untidy.

<img width="394" alt="Screen Shot 2022-11-30 at 12 59 56" src="https://user-images.githubusercontent.com/444434/204803019-30de31a9-a289-4d05-a70b-252c54c4a3d2.png">

Would appreciate some design guidance on how we can improve this. Maybe @SaxonF?

**Comment by getdave** [comment]
This one is waiting on Design.

**Comment by SaxonF** [comment]
![image](https://user-images.githubusercontent.com/1072756/206389318-0a51d0fb-0269-4022-aa65-54e90db0f578.png)

This is from a previous discussion so not sure if it's still suitable. It might be ok to use "Add menu item" as a label rather than the plus, even if its just for the first menu item (blank state).
