### ISSUE TITLE
Checking of block type names is incorrect when passing a Path

### ISSUE THREAD

**Issue by jihaisse** [WordPress/gutenberg#46208]
### Description

Using `register_block_type( __DIR__ . '/build/my-block' );` with a Path containing uppercase in it, method `WP_Block_Type_Registry::register` throw an error : 

> Block type names must not contain uppercase characters.

### Expected Behavior

Get non-confusing feedback.

### Current Behavior

Feedback is not about the namespace of the block, but about the Path

### Step-by-step reproduction instructions

1. Call `WP_Block_Type_Registry::register( '/home/wordpress/testSite/wp-content/my-plugin/build/my-block' )`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
@jihaisse 
Thank you for the report.
I have tested the following and could not reproduce it.

- Create a local environment that includes the lower camel case directory in its path
- `cd D:\_local\lowerCamelCaseDir\app\public\wp-content\plugins`
- `npx @wordpress/create-block gutenpride`

And that error is caused by the fact that the block name contains uppercase letters such as:

```json
{
  "apiVersion": 2,
  "name": "creAte-block/Gutenpride",
}
```

 But you mean that the block name is all lowercase, right?

**Comment by jihaisse** [comment]
Thanks for your time.

After upgrading to wordpress 6.1.1 this behavior disappeared. 

I close this issue.
