### ISSUE TITLE
Inserter search behavior - fuzzy? keywords?

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#464]
In order to decide whether additional functionality should be added to the blocks API, I'd like to nail down the expected behavior of the inserter search field.

Taking the Image block as an example:

- If I type "ima", should it appear?
  - Title search, already implemented
- If I type "common", should it appear?
  - Search by category
- If I type "imge", should it appear?
  - Fuzzy search
- If I type "picture", should it appear?
  - Keyword search

**Comment by jasmussen** [comment]
The pattern we're mimicking is that of chat apps, for example Slack:

![slash commands](https://cloud.githubusercontent.com/assets/1204802/25231499/5c7aed18-25d8-11e7-8058-6ed13c2fa4fc.gif)

In this case, the slash actually indicates the succeeding text is the search query.

In the prototypes, the slash was simply a shortcut to invoke the inserter —  neither the `/` nor the succeeding search text was actually literally output on the new line. But the end result was the same, you could type /, type image, press enter, and have an image block. Though I have a preference for fully embracing the commandline and showing the literal text, the other approach is fine too.

I don't think fuzzy text search is strictly necessary at this point. It could be a nice improvement in the future.

You made a good point in chat:

> “Not found” is easy enough. I’m fine without a mockup if you want to tinker with my styling judgment directly in the PR

I think "Not found" would be a good thing to show regardless of the literal typing out or the shortcut approach, so long as dismissing it (escape key or clicking outside) is easy.

**Comment by inhll** [comment]
This is a great point to bring up @aduth! I agree with @jasmussen that the simple title search is a great starting point, with fuzzy search being the logical extension. Keyword can also be helpful but may also add to the clutter and people will kinda wonder why "ph" is returning results for a bunch of different seemingly random results.

Category search adds a lot of complexity in my experience, as it's confusing for people to see a whole category of item without the category children, and even more confusing with category children since that adds a lot of additional clutter. The available block and category types in WP are simpler than what I was working on, but this could still be an issue and visual scanning should be a sufficient "category search" for the moment, and perhaps the long run.

**Comment by jasmussen** [comment]
Closing as "settled". Feel free to reopen if this was in error.
