### ISSUE TITLE
Query Loop block: Split settings awkwardness with "Create a new post for this feed" prompt

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#46472]
### Description

When using the split settings https://github.com/WordPress/gutenberg/issues/40204 options under Gutenberg > Experiments, if you add a Query Loop block, the settings tab runs into some awkward layouts with the "Create a new post for this feed" prompt. cc @aaronrobertshaw @gutenberg

### Step-by-step reproduction instructions

1. Enable split settings under Gutenberg > Experiments.
2. Open the site editor.
3. Add a query loop block. 
4. Go to the "settings" tab and notice awkwardness in spacing.

### Screenshots, screen recording, code snippet

<img width="290" alt="Screen Shot 2022-12-12 at 10 21 12 AM" src="https://user-images.githubusercontent.com/26996883/207123919-e85e129c-940c-4ea8-99d3-4cbda3eee3c9.png">

### Environment info

- WP 6.1.1
- GB 14.7
- TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aaronrobertshaw** [comment]
Thanks for writing up this issue @annezazu 👍 

I've explored a couple of approaches to addressing this already. The first ( https://github.com/WordPress/gutenberg/pull/45437 ) was the addition of a new slot above the sidebar tabs so we could move the link. This PR was abandoned primarily due to concerns around blocks potentially abusing it to push their controls to more prominent positions than they merit.

The second approach ( https://github.com/WordPress/gutenberg/pull/46147 ), that should be landing soon, is to remove the color controls from the Query block so that it will be a "settings only" block. The result will be that the Query block doesn't show tabs and the create new post link will appear in its usual position.

**Comment by annezazu** [comment]
Fantastic! Thank you for the context and for already doing work to resolve it!
