### ISSUE TITLE
Changes to page/post title block in site editor not reflected in editor

### ISSUE THREAD

**Issue by simonwammerfors** [WordPress/gutenberg#46534]
### Description

Changes made to the title block in a page template in the site editor (like centering the text and making the block wide width) shows in the site editor and on the front end, but does not carry over to the editor. When editing a page in the editor the title is left-aligned and not wide width.

### Step-by-step reproduction instructions

1. Activate Twenty Twenty-Three.
2. Edit the page template and make the title block centered and wide width.
3. Edit a singular page in the editor.
4. The title is left-aligned and not wide width.

### Screenshots, screen recording, code snippet

![Skärmavbild 2022-12-14 kl  13 19 25](https://user-images.githubusercontent.com/88452801/207593903-0d0c9e4d-c1cc-4b1a-a314-00bcf6e8d25f.png)
Site Editor

![Skärmavbild 2022-12-14 kl  13 19 55](https://user-images.githubusercontent.com/88452801/207593889-0a96b889-6b83-422a-96cf-7d61f8be89af.png)
Editor

### Environment info

- WordPress 6.1.1
- Gutenberg 14.7.2
- Safari 16.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by ndiego** [comment]
Thanks for posting this issue. We reviewed it during today's Editor Bug Scrub. This issue has really always existed. The styling on post/page title is not an accurate reflection of the template that the page/post is using. To reduce this confusion, there are a number PRs that are exploring other ways of surfacing the post/page title in the Editor. Here is [one example](https://github.com/WordPress/gutenberg/pull/46135). 

Since this is not actually a bug, I am going to close the issue. But hopefully, we will soon have a better way to handle post/page titles in the Editor that better reflects the layout of the template.
