### ISSUE TITLE
Gallery: dimension options not available for many themes

### ISSUE THREAD

**Issue by ricjcs** [WordPress/gutenberg#46545]
### Description

Dimension options, which include block spacing, among others, do not appear in the block gallery settings in several themes, such as "Twenty Seventeen". I think this happens in themes (but not all) that are not prepared for full site editor.

In the source code if I manually put the block spacing like this:  `<!-- wp:gallery {"linkTo":"none","style":{"spacing":{"blockGap":{"top":"5px","left":"5px"}}}} -->`, works perfectly fine in the theme. So these options are not incompatible with the theme, so I think they should appear in the settings.

### Step-by-step reproduction instructions

1. Install the Twenty Seventeen Theme
2. Add or edit a post
3. Add a gallery block with some images
4. Check that the dimension options do not appear in the gallery block settings

### Screenshots, screen recording, code snippet

**Gallery block settings in the Twenty Seventeen theme:**
![Captura de ecrã 2022-12-14 135755](https://user-images.githubusercontent.com/11923491/207631103-416ed66e-aebb-4c21-b648-5759d7e5d583.jpg)

**Gallery block settings in the Twenty Twenty-Three theme:**
![Captura de ecrã 2022-12-14 140106](https://user-images.githubusercontent.com/11923491/207631167-200292de-64d2-4167-aa00-f233222c5b32.jpg)

### Environment info

- Wordpress 6.1.1 without Gutenberg
- Wordpress 6.1.1 with Gutenberg 14.7.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by kathrynwp** [comment]
Hi @ricjcs  – Good question! I don't think Twenty Seventeen has been retrofitted to declare support for all the new block settings, and I'm not sure whether it's planned to go back that far, since it's a five year-old theme. 

@carolinan – would you know? And if you think it's a good idea, should a ticket be created over in https://core.trac.wordpress.org with the Bundled Theme component? Thanks!

**Comment by ricjcs** [comment]
Thanks for the reply @kathrynwp 

The theme I indicated was just an example, as there are several that present this situation. The problem can only be solved by updating the theme? Wouldn't a correction in Gutenberg solve it?

The problem only happens in the settings that don't show the options. If the parameters such as spacing are manually edited in the source code, the block appears correctly in the editor and when viewing the website.

**Comment by kathrynwp** [comment]
> The problem can only be solved by updating the theme? Wouldn't a correction in Gutenberg solve it?

Another excellent question! I don't _think_ it's possible to handle this only on the Gutenberg side; I think classic themes (non-block themes like Twenty Seventeen) need to explicitly declare support for some of the newer block settings, but I'm sure Carolina will be able to confirm that.

**Comment by glendaviesnz** [comment]
Thanks for the questions about this @ricjcs. There are a number of block settings that are only available to block-based themes because there is no way to guarantee that those features will work out of the box with classic themes. Also, many of these settings are used to edit styles that were traditionally the responsibility of classic themes and site owners may not necessarily want content editors to suddenly have access to these  - and without a `theme.json` file there is no way to selectively disable them.

Classic themes can add a theme.json file without opting into the whole blocks-based approach and iteratively add support for controls as needed tough. That way, the theme developers/users can test and make sure everything works correctly before they offer explicit support.

**Comment by ricjcs** [comment]
Thanks @glendaviesnz

So would it be possible to add a theme.json to one of these themes, so that the dimension/spacing settings become available in the gallery? Would you know what code to put or where to find this information?

**Comment by glendaviesnz** [comment]
@ricjcs, I just tested with TwentySeventeen and adding a `theme.json` file with the following content to the top level of the theme directory made the block spacing option appear in the gallery block:

```json
{
	"$schema": "https://schemas.wp.org/trunk/theme.json",
	"version": 2,
	"settings": {
		"appearanceTools": true
	}
}
```

**Comment by ricjcs** [comment]
Thank you very much @glendaviesnz. It worked with another theme. The content in the editor was all on the left without margin. I added the following code:

```
"layout": {
       "contentSize": "900px"
}
```
Looks like everything is ok! Thanks! 😄

**Comment by kathrynwp** [comment]
Thanks for chiming in and testing, @glendaviesnz!

I'll go ahead and close this out.
