### ISSUE TITLE
Post date block: to display post date and modified date side by side.

### ISSUE THREAD

**Issue by iidastudio** [WordPress/gutenberg#46645]
I want to display the post date and modified date side by side.
To do this, I need the option of not displaying the modified date on the front if it has never been modified.
I think we also need to add a class to distinguish each of them.

**Comment by carolinan** [comment]
Do we also need to add a prefix to the block, similar to the post term block?
So that we can easily add "Published (current block text here)" and "Modified (current block text here)"

**Comment by carolinan** [comment]
If there is consensus to change the behavior of the modified date, this PR should solve it https://github.com/WordPress/gutenberg/pull/46839
But we need to decide what we consider a modification, because if we create a post, and spend say half an hour writing the content, WordPress will save a modified date: I assume it is common to not publish the post immediately.
