### ISSUE TITLE
blank pages on WP 6.0.3 with plugin 14.8.1

### ISSUE THREAD

**Issue by wimdecorte** [WordPress/gutenberg#46802]
The last update to 14.8.1 running on WP 6.0.3, Simplelin theme - made all pages render blank.  No error in the browser, just an empty body element

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/5022743/209717960-fc7ae45d-ebdf-4c17-8934-016bea28cc46.png">

In the WP Admin backend most pages also do not show up in the list anymore.  The count of pages is still accurate but only a few pages show in the list.
Disabling the plugin brings the website and the backend back.

**Comment by t-hamano** [comment]
Thanks for the report.
It may not be the same error as yours, but I did indeed get a critical error with WordPress 6.0.X.

```
Fatal error: Uncaught Error: Call to undefined function wp_get_typography_font_size_value()
```

![fatal_error](https://user-images.githubusercontent.com/54422211/209753864-b01fbe1e-f577-4a29-9d5d-596c4e38aa6e.png)

I replaced `wp_get_typography_font_size_value` with `gutenberg_get_typography_font_size_value` in the Gutenberg plugin, and the error no longer seems to occur.

Probably because `wp_get_typography_font_size_value` is [available from WordPress 6.1](https://github.com/WordPress/wordpress-develop/blob/ac9573bd67a225e51fb7b698b4d507e6ae396f83/src/wp-includes/block-supports/typography.php#L449-L468).

@ockham 
Replaced by #44876 with a wp_prefixed function, but considering that the Gutenberg plugin now supports WordPress6.0, should we prefix it back?

**Comment by Mamaduka** [comment]
@t-hamano, I believe we only need to replace the method is a single place. See #46806.

**Comment by t-hamano** [comment]
@Mamaduka 
I understand now, thanks 👍
