### ISSUE TITLE
`@wordpress/components`: add `type="button"` to vanilla `<button />` elements

### ISSUE THREAD

**Issue by ciampo** [WordPress/gutenberg#46814]
## Update 9 Jan 2023

As [agreed](https://github.com/WordPress/gutenberg/issues/46814#issuecomment-1372216151), we should add `type="button` to all vanilla `<button />` elements in the `@wordpress/components` package.

## Original issue description:

In https://github.com/Automattic/isolated-block-editor/issues/197 it is flagged that the `button` element rendered by the `Button` component doesn't always have `type="button"`, which leads to forms being submitted involontarily.

By having a quick look at the code, it looks like the `type="button"` attribute should be always assigned by default to all rendered `buttons` (in fact, it's not assigned only when `Button` renders an anchor tag, which seems correct):

https://github.com/WordPress/gutenberg/blob/1645fb2292ce2064b6a74f09be1069b794106cca/packages/components/src/button/index.js#L116-L123

We should investigate better the issue reported in https://github.com/Automattic/isolated-block-editor/issues/197 and understand why the `Button` component is not behaving as expected.

**Comment by mirka** [comment]
Ok, so it looks like we can assume that this only happens in places where we're using a raw `<button>` instead of the `Button` component 😅 The example given in the original issue ("changing the font size of a paragraph") seems to confirm this, as FontSizePicker has a ToggleGroupControl which uses raw `button`s under the hood.

A quick scan of the codebase surfaces only one instance in the wp-components package, and just a few more in `block-library` and `edit-site`.

**Comment by ciampo** [comment]
Do you think we can just add `type="button"` to those raw `<button />`s ? After all they were never meant to be form submit buttons

**Comment by mirka** [comment]
I think so, yes.

**Comment by Pitboz** [comment]
Happy to give this a go. 😄

**Comment by Pitboz** [comment]
Hey @mirka . I've been taking a closer look here and I wanted to confirm with you the following changes before committing them. 😄 

Based on the issue description, should I add the `type="button"` attribute to the `<button />` elements in the following files?

- https://github.com/WordPress/gutenberg/blob/d921d2a34d52383f78a970fa1d8a76a1b9f361c1/packages/components/src/tooltip/stories/index.js#L75-L83
- https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/page-list-item/edit.js
- https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-site/src/components/block-editor/resize-handle.js

**Comment by mirka** [comment]
> Based on the issue description, should I add the `type="button"` attribute to the `<button />` elements in the following files?

@Pitboz Good question! I'd say no to the three files you listed. And don't worry if there are other places you're unsure about — we'll review it in the PR 🙂

**Comment by Pitboz** [comment]
Hey @mirka . Really sorry for dropping this for so long. I'd like to work and complete this, however, I feel like I'm a bit lost. 😅 Is there an example or any guidance you can share with me? I can also drop this and someone else can take over and I will follow the changes because I don't want to take up too much of your time.

**Comment by ciampo** [comment]
Hey @Pitboz , don't worry. @mirka will be away until early December, but I will make sure that someone can take this over and bring it to the finish line.

**Comment by andrewhayward** [comment]
@ciampo can you clarify if the scope of this ticket is limited to [`@wordpress/components`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components)? @mirka's [comment above](https://github.com/WordPress/gutenberg/issues/46814#issuecomment-1370368760) also references [`block-library`](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-library) and [`edit-site`](https://github.com/WordPress/gutenberg/tree/trunk/packages/edit-site), so it's not entirely clear what's expected.

**Comment by ciampo** [comment]
Thank you for asking — let's go with what Lena proposed.

**Comment by andrewhayward** [comment]
[Searching for `<button`](https://github.com/search?q=repo%3AWordPress%2Fgutenberg+path%3A%2Fpackages%5C%2F%28components%7Cblock-library%7Cedit-site%29%5C%2F%2F+-path%3A*%2F__snapshots__%2F*+-path%3A*%2Ftest%2F*+-path%3A*%2Fstories%2F*+-path%3A*%2Ftypes.ts+-path%3A*.map+-path%3A*.d.ts+-path%3A*.php+-path%3A*.md+%2F%28%3F-i%29%3Cbutton%2F&type=code) in `@wordpress/components`, `@wordpress/block-library` and `@wordpress/edit-site` yields results across 9 files (plus a false-positive `/stories/` hit).

We can ignore the following, because they're not actually in code:
https://github.com/WordPress/gutenberg/blob/f04f5c5ee7875bd858d35891565f1b7f736c772f/packages/edit-site/src/components/site-hub/index.js#L72
https://github.com/WordPress/gutenberg/blob/f04f5c5ee7875bd858d35891565f1b7f736c772f/packages/block-library/src/navigation/edit/deleted-navigation-warning.js#L14

Which leaves us with the following, six of which will require work...

## packages/block-library/src/page-list-item/edit.js

> [!IMPORTANT]
> This is missing a `type`, so will need fixing.

https://github.com/WordPress/gutenberg/blob/f04f5c5ee7875bd858d35891565f1b7f736c772f/packages/block-library/src/page-list-item/edit.js#L66-L71

> [!IMPORTANT]
> This is missing a `type`, so will need fixing.

https://github.com/WordPress/gutenberg/blob/f04f5c5ee7875bd858d35891565f1b7f736c772f/packages/block-library/src/page-list-item/edit.js#L90-L95

## packages/block-library/src/search/edit.js

> [!NOTE]
> This has a `type`, so is fine.

https://github.com/WordPress/gutenberg/blob/f04f5c5ee7875bd858d35891565f1b7f736c772f/packages/block-library/src/search/edit.js#L336-L349


## packages/components/src/button/index.tsx

> [!NOTE]
> [`buttonProps` is defined above](https://github.com/WordPress/gutenberg/blob/f04f5c5ee7875bd858d35891565f1b7f736c772f/packages/components/src/button/index.tsx#L165-L174) to have a `type`, so this is fine.

https://github.com/WordPress/gutenberg/blob/f04f5c5ee7875bd858d35891565f1b7f736c772f/packages/components/src/button/index.tsx#L243-L249


## packages/components/src/color-palette/index.tsx

> [!IMPORTANT]
> This is missing a `type`, and while `onToggle` might deal with the problem, it should be fixed regardless.

https://github.com/WordPress/gutenberg/blob/f04f5c5ee7875bd858d35891565f1b7f736c772f/packages/components/src/color-palette/index.tsx#L292-L302


## packages/components/src/toggle-group-control/toggle-group-control-option-base/component.tsx

> [!NOTE]
> This has a `type`, so is fine.

https://github.com/WordPress/gutenberg/blob/f04f5c5ee7875bd858d35891565f1b7f736c772f/packages/components/src/toggle-group-control/toggle-group-control-option-base/component.tsx#L133-L141

> [!IMPORTANT]
> This is missing a `type`, and `commonProps` does not explicitly include one either, so it should be fixed. It should be included before `commonProps` though, as that _does_ include consumer-provided `props`, which could contain a `type`.

https://github.com/WordPress/gutenberg/blob/f04f5c5ee7875bd858d35891565f1b7f736c772f/packages/components/src/toggle-group-control/toggle-group-control-option-base/component.tsx#L145-L152


## packages/edit-site/src/components/block-editor/resize-handle.js

> [!IMPORTANT]
> This is missing a `type`, so will need fixing.

https://github.com/WordPress/gutenberg/blob/f04f5c5ee7875bd858d35891565f1b7f736c772f/packages/edit-site/src/components/block-editor/resize-handle.js#L33-L38


## packages/edit-site/src/components/page-patterns/grid-item.js

> [!IMPORTANT]
> This is missing a `type`, so will need fixing. Note that it should be included before `props` to allow for a consumer override.

https://github.com/WordPress/gutenberg/blob/f04f5c5ee7875bd858d35891565f1b7f736c772f/packages/edit-site/src/components/page-patterns/grid-item.js#L172-L204

**Comment by ciampo** [comment]
Sounds like a good plan!
