### ISSUE TITLE
SEO problem: Vimeo URLs getting extra parameters h, dnt and app_id

### ISSUE THREAD

**Issue by galbaras** [WordPress/gutenberg#46825]
### Description

When embedding a video using the Vimeo block, e.g. https://player.vimeo.com/video/783178335, the URL appearing on the front end of the site has extra parameters, e.g. `?h=d0386dac7a&amp;dnt=1&amp;app_id=122963`.

This looks the same to a user, but Google Search Console is reporting the page as being inconsistent with Rank Math Pro's Video Schema markup, which is generated from the URL saved for the block. 

### Step-by-step reproduction instructions

1. Add a Vimeo block with the plain video URL
2. Examine the URL at the front end of the site

### Environment info

WP 6.1.1
Rank Math SEO 1.0.104.1
Rank Math SEO Pro 3.0.26.1
Theme: Genesis 3.4.0 child (no relevant custom code)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by ndiego** [comment]
Hi @galbaras. Thank you for reporting. This issue came up in today's Editor Bug Scrub, and we were able to replicate and see additional "stuff" being added to the end of the URL once embedded. Unfortunately, Gutenberg has no real control over this as it's added by Vimeo's embed provider. In talking to other developers, there are likely ways to circumvent this, but it would never be stable/reliable enough for Core. Solving the issue will likely need to be done on the Rank Math side. Given this, I am going to close this issue.
