### ISSUE TITLE
ToggleControl: Missing gap if label too long

### ISSUE THREAD

**Issue by MatzeKitt** [WordPress/gutenberg#47072]
### Description

If you have a rather long label (which we do in translating some default strings to German), the gap between the toggle and the label is getting removed as soon as the label is longer than the available space.

### Step-by-step reproduction instructions

1. Add a ToggleControl.
2. Set the label of the ToggleControl to "Die inneren Blöcke verwenden die Breite des Inhalts" (which is the German translation for "Inner blocks use content width").

### Screenshots, screen recording, code snippet

<img width="279" alt="toggle-control-missing-gap" src="https://user-images.githubusercontent.com/1018979/211830995-b3872130-e94c-4b23-8670-51d571c92680.png">

### Environment info

– WordPress 6.1.1, no Gutenberg plugin
– macOS 13.1 with Safari 16.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by La-Geek** [comment]
Verified in WordPress 6.1.1, no Gutenberg plugin
Windows 10 (recent version) with Chrome browser

Add (for example) the block group to get the toggle element in the sidebar.

https://user-images.githubusercontent.com/1585416/211834392-cfccdd82-1742-4198-a5de-1ff19dd28de8.mp4

**Comment by richtabor** [comment]
I confirmed this is happening in WordPress 6.1.1, but is fixed in the Gutenberg plugin. 

It'll land this March, in [WordPress 6.2](https://make.wordpress.org/core/2022/12/27/wordpress-6-2-planning-schedule-proposal/). 

Screenshot (with Gutenberg):

<img width="648" alt="CleanShot 2023-01-11 at 16 35 50@2x" src="https://user-images.githubusercontent.com/1813435/211922859-fdf1a548-d458-4320-969d-ed4f425b48cc.png">
