### ISSUE TITLE
 Restrict gutenberg block next post & previous post to same category

### ISSUE THREAD

**Issue by adventureum** [WordPress/gutenberg#47090]
## What problem does this address?

I am using gutenberg default blocks **[next post], [previous post]** in the template.

but,

In gutenberg editor, 

It don’t have the parameters to set to **restrict post navigation to the same category**. 

## What is your proposed solution?

I think many wordpress users need this feature to restrict **[next post], [previous post]** navigation to **the same category**.

So, I suggest to add this feature. 

Do you agree？ friends?

Thanks very much.

**Comment by justintadlock** [comment]
@laoyingzhige Thanks for filing this ticket.  Your original [support thread](https://wordpress.org/support/topic/how-to-restrict-block-next-post-previous-post-to-same-category/?view=all) was on my list.  Nice to see it already here.  :) 

For more context, both the `previous_post_link()` and `next_post_link()` PHP functions allow for several category/taxonomy-related options that their block equivalents do not currently have:

```php
function previous_post_link(
	$format = '&laquo; %link',
	$link = '%title',
	$in_same_term = false,
	$excluded_terms = '',
	$taxonomy = 'category'
)
```

Since both of the blocks are just wrappers for the PHP function, it should be relatively straightforward to transfer the `$in_same_term` and `$taxonomy` parameters to block settings.  This is also a somewhat common request based on my own experience in the past.

Function reference:

- https://developer.wordpress.org/reference/functions/previous_post_link/
- https://developer.wordpress.org/reference/functions/next_post_link/

**Comment by masteradhoc** [comment]
+1 @carolinan nice work! when will this be added to gutenberg? :)
