### ISSUE TITLE
List block not working

### ISSUE THREAD

**Issue by ghost** [WordPress/gutenberg#47185]
### Description

When creating a new list block you can add an item but when you try to create another item by using enter it won't add a new item but stay on the current line. Using tab and shift tab to indent or unindent an item also no longer works as it will continue going through the z-index elements in the editor instead of nesting the item further in or outwards.

### Step-by-step reproduction instructions

1. Add a list block
2. Add an item to the list and try to use enter to add another item
3. Add another item using the + symbol
4. Use shift or shift tab to indent or unindent an item
5. Use the indent or unindent button in the toolbar

### Environment info

- WordPress 6.1.1 with a custom theme
- Brave/Chrome browser
- Tested on Windows 10 and MacOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by zvolanek** [comment]
@lorenzotenhagen If you use filter allowed_block_types_all or similar, you must add core/list-item

**Comment by ndiego** [comment]
Hi @lorenzotenhagen, this issue came up in today's Editor Bug Scrub. I was unable to replicate the issue with using enter/return to add a new list item. Pressing enter/return reliably added new list items for me in 6.1.1 and the latest version of Gutenberg. I tested with Chrome and Safari. Are you able to provide any additional reproduction steps?

That said, I could confirm that shlft/tab does not indent list items. I went back to 5.9, and the old List block functions the same way. Therefore, it does not appear to be a regression, rather this functionality may never have existed (even though it would be great to have).

**Comment by lecklin** [comment]
Ran into the same issue today and it was solved by what @zvolanek mentioned.

I use `allowed_block_types_all` in my custom theme to filter what blocks can be used and the `core/list-item` block was missing. This resulted in the list block allowing only the single default list item. Allowing the block returned full functionality with list items.

This was a recent change introduced in WP 6.1 and [not really directly mentioned](https://wordpress.org/support/wordpress-version/version-6-1/#compose-richer-lists-and-quotes-with-inner-blocks) in the release post, field guide or release notes. So it was easy to miss and recent enough to fly under the radar until now.

I suspect the (shift+)tab outdent/indent doesn't work due to a11y considerations (switching block focus) and probably never has. This was/is a feature in the classic editor.
With Gutenberg you can however use space and backspace for list item indent/outdent respectively. Tested this now post-fix and they work fine, but just remember they require the caret/cursor to be at the start of the list item content.

**Comment by ghost** [comment]
> Ran into the same issue today and it was solved by what @zvolanek mentioned.
> 
> I use `allowed_block_types_all` in my custom theme to filter what blocks can be used and the `core/list-item` block was missing. This resulted in the list block allowing only the single default list item. Allowing the block returned full functionality with list items.
> 
> This was a recent change introduced in WP 6.1 and [not really directly mentioned](https://wordpress.org/support/wordpress-version/version-6-1/#compose-richer-lists-and-quotes-with-inner-blocks) in the release post, field guide or release notes. So it was easy to miss and recent enough to fly under the radar until now.
> 
> I suspect the (shift+)tab outdent/indent doesn't work due to a11y considerations (switching block focus) and probably never has. This was/is a feature in the classic editor. With Gutenberg you can however use space and backspace for list item indent/outdent respectively. Tested this now post-fix and they work fine, but just remember they require the caret/cursor to be at the start of the list item content.

Thanks to everyone who replied, I got everything working again!

**Comment by KSym04** [comment]
> @lorenzotenhagen If you use filter allowed_block_types_all or similar, you must add core/list-item

This works, thanks!
