### ISSUE TITLE
Consider adding reusableBlock to the supports block configuration

### ISSUE THREAD

**Issue by fastlinemedia** [WordPress/gutenberg#4722]
## Issue Overview
My apologies if this is already doable but I didn't see it in the documentation. I don't feel like converting a block I'm working on to a reusable block makes sense. 

Would it possible to get `reusableBlock` added to the `supports` block configuration so we can disable saving as a reusable block for our blocks? 

This block also has `useOnce` set to `true`, so maybe another solution would be to remove converting to a reusable block for `useOnce` blocks.

**Comment by gziolo** [comment]
@mtias, technically it is an easy task. The question is if we should add this? I don’t see reasons to not do it.

**Comment by gziolo** [comment]
Pinging also @noisysocks as he implemented most of the logic for the reusable block.

**Comment by noisysocks** [comment]
Sounds reasonable and easy to do. Nesting such an attribute under `supports` eases my one concern which is that this change would increase the surface area of the block registration API.

> This block also has useOnce set to true, so maybe another solution would be to remove converting to a reusable block for useOnce blocks.

I don't think we could do this since one might desire a block that should only appear once in a post but that a user can re-use throughout several posts, e.g. a 'post header' block, a 'google analytics block', etc.

**Comment by fastlinemedia** [comment]
Thanks! Getting `useOnce` under `supports` sounds good to me.

**Comment by mtias** [comment]
Sounds fine to me. Can go with `reusable: false` default to `true`

**Comment by noisysocks** [comment]
That's a really good point, @mtias.

@aduth: How does `useOnce` work when nested within a container block?

@fastlinemedia: Could you please describe your use case for this functionality in a little more detail? What block are you building? Why does it not make sense for one to make it reusable?

**Comment by fastlinemedia** [comment]
@mtias @noisysocks thanks for the follow up on this!

I'm not quite following the example for why it wouldn't make sense to make a block non-reusable but I don't think it's a huge issue for what I'm trying to do if that's the case.

I've been working on a block for switching between Gutenberg and Beaver Builder. So far, this is what we have...

https://www.dropbox.com/s/nc0pnn70ry07g8v/beaver-builder-block.mov?dl=0

I don't really think it makes sense for that block to be reusable (definitely should be useOnce though), however, I don't think it's going to hurt anything if it is turned into a reusable block.

I'll go ahead and close this one out. Thanks again!

**Comment by mtias** [comment]
@fastlinemedia thank you for the discussion! I think honoring `useOnce` here would make sense. My point was that, since we have nested block support, you could imagine a user adding a Columns block on which they insert your non-reusable block, and making the column group reusable — which effectively means your non-reusable block is being reused. Does that make more sense?

**Comment by fastlinemedia** [comment]
@mtias no problem and thanks for explaining it further! That makes perfect sense.

**Comment by noisysocks** [comment]
@fastlinemedia: FYI, this came up again in https://github.com/WordPress/gutenberg/issues/5941 and there's now an open PR which adds the functionality you requested: https://github.com/WordPress/gutenberg/pull/5970

**Comment by fastlinemedia** [comment]
@noisysocks thanks for the heads up! :)
