### ISSUE TITLE
Add aspect ratio support to Post Featured Image block

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#47274]
## What problem does this address?

Related to https://github.com/WordPress/gutenberg/issues/38990, but it's easier to implement this as a first-pass on the Post Featured Image block. The Image block is more difficult, as we have to account for cropping via the Image block's existing crop aspect ratio tool. 

## What is your proposed solution?

Let's add support for the upcoming aspect ratio theme.json presets (#47271)  to the Post Featured Image block. 

<img width="810" alt="post-featured-image" src="https://user-images.githubusercontent.com/1813435/213401214-b31f48ab-a95c-447f-8afc-d6796e691859.png">

I put the width and height controls below the aspect ratio, as the aspect ratio affects the height (which is calculated based on the aspect ratio and width). I also have them inverted for consistency with the current image size controls in the Image block; in today's Post Featured Image block, height is first.

**Comment by Thelmachido** [comment]
I would agree that this option would make the visual presentation of content better. 

At the moment, the `Post Featured Image` block when added to a template will render width as per block settings e.g `Wide width`, `Full width`, etc which is great. However, the rendered height of the image depends on the size of the image. 

This affects the display of content because post-featured images are being displayed at different heights. This seems to be a bit buggy, the expected behavior would be for all posts to display the same height regardless of the image size folks upload. 

I provided the CSS below for the site to display a fixed height.

```
.wp-block-post-featured-image img {
    height: 500px;
    object-fit: cover;   
}
```

+1 this issue because of this [forum thread](https://wordpress.org/support/topic/howe-to-crop-featured-image/#post-16400278) folks wanting to know how to crop the featured image.

**Comment by richtabor** [comment]
I'm cool with closing this, as https://github.com/WordPress/gutenberg/pull/47854 added the initial functionality, with follow ups outlined in https://github.com/WordPress/gutenberg/issues/47963
