### ISSUE TITLE
List items that have a link disappear.

### ISSUE THREAD

**Issue by Korben00** [WordPress/gutenberg#47346]
### Description

When I create a list block and put links on some of these items, they disappear.

### Step-by-step reproduction instructions

1/ Create a list block
2/ Put elements with links in this list
3/ Save the article
4/ Refresh Gutemberg
5/ The linked items have disappeared (back side and front side)

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/775494/214000109-7de61b2d-9076-49b0-9269-8496e6c5d5a6.mp4

### Environment info

- Wordpress 6.1.1 (generic Gutemberg included with this version)
- All browsers
- tested on macOS
- No activated plugin during the test

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
Thanks for reporting the issue. I haven't been able to reproduce the problem, though I tested using latest WordPress `trunk` and latest Gutenberg `trunk`.

**Comment by ndiego** [comment]
This issue was reviewed in today's Editor Bug Scrub. We have been unable to replicate using the latest versions of Gutenberg and WordPress. We also tested with only 6.1.1, and all list items with links were displayed correctly. @Korben00 
 would you be able to provide any additional information about your setup or retest this issue? Thanks!

**Comment by priethor** [comment]
Closing the issue as it has been stale for a while, and there is no way to reproduce it. Please feel free to reopen if the issue persists and there is more info; thanks!
