### ISSUE TITLE
6.0.3 -> 6.1.1 broke custom Image Block border radius

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#47422]
### Description

We recently upgraded from WP 6.0.3 to 6.1.1. After doing so, we noticed that many of our Image Blocks with custom border radii set were failing to appear rounded until someone went in and edited the page/post.  I believe I tracked it down to the following CSS discrepancy between core CSS included in the versions:

The file in question:
/wp-includes/css/dist/block-library/style.css

On 6.0.3, it includes:
.wp-block-image:not(.is-style-rounded) > a,
.wp-block-image:not(.is-style-rounded) img {
  border-radius: inherit;
}

But this does not exist in 6.1.1's version.

Manually adding back the missing CSS appears to fix our custom border radii.

For reference, we are using a Classic Theme with a theme.json file

### Step-by-step reproduction instructions

1. Have a classic theme using theme.json on 6.0.3
2. Set a custom border radius on an Image Block.
3. Upgrade to 6.1.1
4. See that the image corners are no longer rounded

### Environment info

WordPress 6.1.1, no Gutenberg plugin

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
In WordPress 6.1, the border support was increased to include color and width and not only radius, so the CSS needed to be updated.

> until someone went in and edited the page/post.

I believe this is the case for any kind of block deprecation and that there is currently no way around it.
After updating the block markup, do you still need to add the extra CSS?.

**Comment by MadtownLems** [comment]
Testing again from a scratch install of 6.0.3 using the Twenty Twenty-Two Theme

6.0.3:
![2023-01-26 09_18_15-Image Test Page – 6 0 Backtesting](https://user-images.githubusercontent.com/945157/214875242-882d2899-0dcd-4fa9-9b90-a34a2457451f.png)

After updating to 6.1.1:
![2023-01-26 09_20_47-Image Test Page – 6 0 Backtesting](https://user-images.githubusercontent.com/945157/214875326-f1abba5f-6c19-4fc4-bdf5-dcdb25529fe8.png)

Note that the custom radii are now missing. (The images that do still have round corners were done with the Round image style)

When you go to Edit the Page.... the backend shows them rounded. The front still does not, until we actually save the page. Note that we can't even save the page until we make a change, so I need to make an arbitrary change, then save, and THEN it shows my custom radii on the front-end.

It's great that the editor helps get the markup in line with what will work, but this feels completely unreasonable from a backwards compatibility standpoint. There's no way site owners should be expected to manually visit, edit, and save every single post in order to have their previously rounded corners stay rounded, using core functionality (that isn't experimental).

**Comment by t-hamano** [comment]
As far as I can tell, if you apply a custom radius to an image block, the markup saved will be different as follows:

### WordPress 6.0.X

```html
<figure class="wp-block-image size-large is-style-default" style="border-radius:50px">
	<img src="https://live.staticflickr.com/103/309542801_46cdb9b259_b.jpg">
</figure>
```

### wordPress 6.1.X

```
<figure class="wp-block-image size-large has-custom-border is-style-default">
	<img src="https://live.staticflickr.com/103/309542801_46cdb9b259_b.jpg" style="border-radius:50px">
</figure>
```

Comparing the two, WordPress 6.1.X differs in the following ways:

- The `figure` element has the `has-custom-border` class
- `border-radius` style is applied to `img` element instead of `figure` element

Of course, these changes are automatically migrated when you open a post that contains that block, but the markup will remain the same as before unless you save that post.

@aaronrobertshaw I think this kind of problem has occurred in other blocks in the past, but if you know how it has been handled, please let us know 🙏

**Comment by aaronrobertshaw** [comment]
Thanks for the ping! 👍 

I've put together a fix for this in https://github.com/WordPress/gutenberg/pull/47766.

It proposes to add a style specifically targeting deprecated image blocks that have the custom border radius as an inline style on the outer `figure` element. That style will restore the border-radius inheritance.

While testing, I also found another bug with theme.json radii overriding custom radii when cropping an image in the editor. That could also be fixed with a small styling tweak.
