### ISSUE TITLE
[Style Book] Hide blocks that are not available in the inserter 

### ISSUE THREAD

**Issue by gigitux** [WordPress/gutenberg#47440]
## What problem does this address?

In WC Blocks, we have a block (Product Search) that is now deprecated. We don’t show it anymore in the inserter. For folks that have it in the editor, we render a notice to “upgrade” the block (the upgrade will convert the block to a Search block variation).
Attached is an image showing how the block is rendered on the Stylebook.

![image](https://user-images.githubusercontent.com/4463174/214799616-8337ecae-5f25-44e1-b464-2d955ce46747.png)

## What is your proposed solution?

A good solution is to have the possibility to hide the block on Style Book.

**Comment by t-hamano** [comment]
Hi @gigitux,

I just created draft #47461 to solve this problem, but then I remembered that with the [current logic](https://github.com/WordPress/gutenberg/blob/360e5a418d5d28250b2fe7e38e741afb3e4145ce/packages/edit-site/src/components/style-book/index.js#L75), removing the `example` prop from the block with `supports.inserter` set to `false` would produce the expected result.

If `supports.inserter` is `false`, then theoretically the example should not be needed since the preview is not displayed.

@noisysocks

Shouldn't the blocks with `support.inserter` set to false be shown in the stylebook? Or should we follow the current logic and remove the `example` property for blocks we don't want to display?

**Comment by gigitux** [comment]
> I just created draft https://github.com/WordPress/gutenberg/pull/47461 to solve this problem, but then I remembered that with the [current logic](https://github.com/WordPress/gutenberg/blob/360e5a418d5d28250b2fe7e38e741afb3e4145ce/packages/edit-site/src/components/style-book/index.js#L75), removing the example prop from the block with supports.inserter set to false would produce the expected result.

Oh right! Good point! Thanks a lot for pointing me in the right direction!

**Comment by noisysocks** [comment]
We don't have any blocks like this in Core but it's _technically_ possible that a block author might want a block that's hidden from the inserter (`inserter: false`) but still appears in the Style Book (has an `example`). For example maybe it's a block that is intended to be accessed via a block transform.

Can WC Blocks simply remove `example` from the deprecated Product Search block?

**Comment by t-hamano** [comment]
@noisysocks 
Thank you for the advice!

> Can WC Blocks simply remove example from the deprecated Product Search block?

Yes, that method would be the simplest.

Personally, I consider blocks that are hidden from the inserter to be those that have been deprecated or don't need to show a preview. Therefore, I have submitted #47461 to not display blocks hidden from the inserter and would be happy to check if this makes sense.

**Comment by gigitux** [comment]
> Yes, that method would be the simplest.

I proceeded to remove the example from the block: https://github.com/woocommerce/woocommerce-blocks/pull/8315 https://github.com/woocommerce/woocommerce-blocks/pull/8309

It is a good solution! I'm okay with this approach. I could close the issue. What do you think?

**Comment by noisysocks** [comment]
Awesome glad to hear.

We can keep this open. Maybe https://github.com/WordPress/gutenberg/pull/47461 is a good idea. I can't decide 😀
