### ISSUE TITLE
Reusable Blocks: Allow overwriting parts of it

### ISSUE THREAD

**Issue by crstnio** [WordPress/gutenberg#4748]
I couldn't find a related issue.

Creating a reusable block disables the settings in "Block" sidebar. They appear only while editing the reusable block itself.

This could be improved. The paragraph block for example. It has multiple settings like background and text color. These could be edited on an instance basis like inheritance in Gantry 5.

Example:

<img src="https://user-images.githubusercontent.com/34842497/35553927-21c17cee-059a-11e8-90d4-36de15c021a5.png" width="400">

Every single setting of the inherited block could be overwritten. But not only that.

It would be great and more important to adjust the block content, but maintain the global block settings. This saves us from creating dozens of reusable blocks with almost the same settings, but altered content.

I hope my intention is clear: Let us "inherit" reusable block settings and content on a single basis.

**Comment by karmatosed** [comment]
I personally feel reusable blocks as a concept because it's a 'copy' of a block you have setup, makes sense to not allow individual changes like you are suggesting. The path to a reusable block is usually this:

- Add a block
- Style it, do adjustments to make it as you want
- Make reusable

You are simply making a copy to use. In this sense not having everything else makes sense.

**Comment by crstnio** [comment]
Of course, but imagine the following:

1. You have a block named quote. This block has settings for text color and background color.
2. Now you want multiple minor versions of these quotes on multiple pages.

With current reusable blocks:

3. You create reusable blocks for each and every custom quote block – sometimes with altered background and color, some other with custom quote contents.

With inheritance:

3. You create **one** reusable block and inherit it's content and settings as needed.

Would you update dozens of reusable blocks around hundreds of blog posts that only have different contents but all need a new background? That would downgrade the use of reusable blocks. Instead it would be more useful to have only one reusable block with inherited content and change the background **once**.

**Comment by jasmussen** [comment]
This does seem like a valid use case, and if implemented right could enhance reusable blocks a fair bit. As such, it seems like a nice optimization.

However we have a fair amount of tasks ahead of us for Gutenberg, including improving the flow for editing an already shared block (wherein you can configure block settings across all shared blocks). There will also be a Gutenberg customization focus this year, and it seems like enhancing shared blocks (previously called reusable blocks) is very likely. 

As such, I would either close this ticket and revisit when the Gutenberg Customization focus kicks off, or tag this ticket "Customization" and put the priority as low for now. I say this with the greatest respect for the concept, which I agree is valid, and if a volunteer were to create a pull request for this, I'd definitely thumb it up.

**Comment by appscaptain** [comment]
+100 for this feature request.

I'm happy to see I'm not the only person missing this feature. It limits the usage of reuseable blocks greatly.

Oftentimes you setup up reuseable sections based on reuseable blocks and need to customize them a lot or slightly for each page while keeping the structure/layout. The quote example is a great usecase. I have this problem throughout many sections of my website.

Since reuseable block don't support this, you end up making a bunch of copies of the same black with slightly different content (which is unmanageable), or more likely, you simply don't use reuseable blocks.

Could be nice if the styling and structure was reuseable but that you could override the content itself or part of the basic styling. Like:
• Text
• Images
• Background colors

There could be a reset button to reset these overrides. Similar to how Sketchapp has overrides - https://www.sketch.com/docs/symbols/overrides/.

**Comment by jamieschmid** [comment]
Any details on why this was closed, or is it just because the opener's account was deleted?
I have a use case for this currently, and can see a lot of applications for this feature. I'd like to start the conversation back up, should I create a new issue?

My use case is this:
We have multiple CTA's on the site, which often have common title and body copy, but the link button needs to be unique for tracking and email capture reasons. Currently trying to work out a solution using nested blocks, but it's getting complex. The ability to set overrides for some or all of a shared block would be phenomenal and make this task much easier.
