### ISSUE TITLE
[Page List] Locking and customization UI updates

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/gutenberg#47506]
There are a couple of issues with the Page list block within the Navigation Block list view as it stands today regarding the icons and interactions related to them:

<img width="348" alt="Screenshot 2023-01-27 at 16 08 49" src="https://user-images.githubusercontent.com/3593343/215127873-f599b4b8-1919-42b1-9782-8235bf1c7c0d.png">

- The lock icons

Currently all page list elements have a lock icon. This is very busy, making the inspector list view quite cramped. @mtias  suggested the solution of template locking the Page List using `contentOnly` and only showing the lock icon in the page list parent block. The problem is that this mode right now hides all children in the list view and only offers a flattened list of content blocks on the inspector. 

<img width="1321" alt="Screenshot 2023-01-27 at 16 11 05" src="https://user-images.githubusercontent.com/3593343/215127926-e1c12693-aefc-418f-8c98-bbab0b6cb60b.png">

- The edit icons

Currently only the Page list parent has an edit icon and that's our way to access the "Customize" button that turns the page list into a list of links. If we were to use `contentOnly` for this block, we could consider triggering the transformation into links when someone tries to edit the content of the page list, but we'd have to consider how that interaction would happen.

<img width="295" alt="Screenshot 2023-01-27 at 16 34 30" src="https://user-images.githubusercontent.com/3593343/215128003-1b217012-7977-44c0-a796-baae683526c6.png"> | <img width="282" alt="Screenshot 2023-01-27 at 16 46 56" src="https://user-images.githubusercontent.com/3593343/215128094-aa6663d3-91f6-422b-bdba-68f849a2259f.png">

**Comment by richtabor** [comment]
Here's an issue I wrote up for the lock icons specifically: https://github.com/WordPress/gutenberg/issues/47268

**Comment by MaggieCabrera** [comment]
I was discussing this further with @scruffian and I think what makes sense here is:

- Remove the lock: all from the children of the page list and instead make the page list be contentOnly instead
- Stop hiding the children from contentOnly locked blocks from the list view
- Have a different way of visually expressing that the block and children are in contentOnly mode.

**Comment by MaggieCabrera** [comment]
> I was discussing this further with @scruffian and I think what makes sense here is:
> 
>     * Remove the lock: all from the children of the page list and instead make the page list be contentOnly instead
> 
>     * Stop hiding the children from contentOnly locked blocks from the list view
> 
>     * Have a different way of visually expressing that the block and children are in contentOnly mode.

I'd like to get a heads up on this before getting too deep into the code, besides I need design direction for the last bit @mtias @richtabor @jasmussen @SaxonF

**Comment by SaxonF** [comment]
> we could consider triggering the transformation into links when someone tries to edit the content of the page list, but we'd have to consider how that interaction would happen

This was originally the intention and I think its captured [here](https://github.com/WordPress/gutenberg/issues/47064).

> Have a different way of visually expressing that the block and children are in contentOnly mode.

This is a tricky one... I'm inclined to just leave it visually as is (no lock) for now and work towards being able to convert a page list item into a custom link which then of course would convert the parent page list block. This fits in with the above pattern of being able to transition from a page list to a list of custom links seamlessly.

**Comment by jasmussen** [comment]
The mini locks are noisy, so it makes sense to me to show it on the parent.

**Comment by MaggieCabrera** [comment]
> The mini locks are noisy, so it makes sense to me to show it on the parent.

yeah, what @richtabor is suggesting in https://github.com/WordPress/gutenberg/issues/47268 but right now, only the children are actually locked, not the parent. I was thinking how to do this and I wonder if a CSS solution would be best to at least hide the icons from the children? We would have to introduce multiple exceptions for this block to hide the locks for the children and show them for the parent

**Comment by scruffian** [comment]
> We would have to introduce multiple exceptions for this block to hide the locks for the children and show them for the parent

I think it would be better if we can avoid this.

**Comment by scruffian** [comment]
On further consideration, I don't think `contentOnly` is model here - Blocks that are `contentOnly` locked allow users to edit the content, but not the structure of the blocks. In the Page List, all child blocks are completely locked - they cannot be removed, or moved, or edited in any way. This is the same situation as when a block and all it's children are locked, a bit like this:

<img width="511" alt="Screenshot 2023-02-02 at 10 09 56" src="https://user-images.githubusercontent.com/275961/216295931-9341ce2d-6553-4b09-b567-459a13966556.png">

<img width="348" alt="Screenshot 2023-02-02 at 10 09 49" src="https://user-images.githubusercontent.com/275961/216295948-2229fe1b-d1e9-4fbd-8105-417f0d5fe2d0.png">

The navigation block also has an "edit" lock:
<img width="499" alt="Screenshot 2023-02-02 at 10 14 40" src="https://user-images.githubusercontent.com/275961/216296986-31319164-dd6a-4198-816d-9c0faf731ffb.png">

The problem with this is also that it prevents the items showing in the list view.

I think we need to look at this situation holistically, rather than doing something specific for the Page List blocks.

One option is to create a new type of lock - "child" lock? This would allow a block to lock all its children, but the block itself would remain editable. This is probably useful for other blocks, not just the Page List. The behaviour would be something like this:

1. When locking a block users have the option to apply the lock to:
- that block only
- that block and all it's children
- the children only
2. The third would apply the selected locks to all the children of the block but the block itself would remain unlocked
3. The block with locked children would absorb the lock icons for all the children, perhaps with a slightly different visual display (multiple locked icons?) to make it clear that the lock is applied to the children
4. The block would continue to display all the children even though they are locked but they would be visually disabled (maybe a slight grey color?)

To be honest this solution seems quite complex, and I'm not sure that's any better than the current situation with the stacked icons on the Page List block.

**Comment by scruffian** [comment]
I think we can close this based on the work done in https://github.com/WordPress/gutenberg/pull/48723
