### ISSUE TITLE
Block API: BlockGap with support for only one direction doesn't work correctly

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#47518]
### Description

The `supports.spacing.blockGap` property allows you to specify the direction of support. When only one direction was supported, the following problems occurred:

- Tooltip does not show values
- Slide pointer cannot be moved in custom input.
- In custom input, input of values is not reflected.

These problems don't occur when unidirectional support is applied in `margin` and `padding` properties.

### Step-by-step reproduction instructions

Use the following markup to insert a Social Links Block that supports vertical and horizontal gaps:

```html
<!-- wp:social-links {"showLabels":true} -->
<ul class="wp-block-social-links has-visible-labels"><!-- wp:social-link {"url":"#","service":"wordpress"} /-->
<!-- wp:social-link {"url":"#","service":"fivehundredpx"} /-->
<!-- wp:social-link {"url":"#","service":"amazon"} /-->
<!-- wp:social-link {"url":"#","service":"facebook"} /-->
<!-- wp:social-link {"url":"#","service":"instagram"} /-->
<!-- wp:social-link {"url":"#","service":"twitter"} /--></ul>
<!-- /wp:social-links -->
```

change the following:

```diff
diff --git a/packages/block-library/src/social-links/block.json b/packages/block-library/src/social-links/block.json
index a7707cf195..c5c23acf94 100644
--- a/packages/block-library/src/social-links/block.json
+++ b/packages/block-library/src/social-links/block.json
@@ -66,7 +66,7 @@
                        }
                },
                "spacing": {
-                       "blockGap": [ "horizontal", "vertical" ],
+                       "blockGap": [ "horizontal" ],
                        "margin": true,
                        "padding": true,
                        "units": [ "px", "em", "rem", "vh", "vw" ],
```

confirm that the problems listed at the beginning of this section are reproduced.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/54422211/215243102-a2144e16-3a30-49bb-9189-7ebbdeee020a.mp4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by andrewserong** [comment]
Thanks for opening up this issue @t-hamano! What's the use case for only specifying a gap in one direction? I'd be keen to understand this better before attempting to allow support for a single direction, as the blockGap output would need to be altered a bit in order to support it.

By design the `blockGap` output was written without handling the case for a single direction gap, so personally I'd view this as more of an enhancement request than a bug. From memory, the thinking behind the implementation of axial / split horizontal and vertical gap was something along these lines:

* For flex layouts the gap is output using the `gap` property shorthand, and the current implementation of axial support means that the layout output doesn't have to be aware of other individual properties, and can instead concatenate the value, so split values are `gap: 1em 2em` rather than having to output separate `row-gap` and `column-gap` properties.
* Gap works a little differently than margin or padding, in that here we tend to expect default values that are non-zero. So if someone goes to set a gap value for a particular direction, in most cases there will need to be a value set for the other direction, too. If the user wants the opposing direction to be set to `0`, they can do that with axial gap controls, but is there a case where a block developer wants to prevent the user from doing that?
* In most cases we could think of, using `blockGap: true` would be preferable to setting only a particular side — a distinction between block spacing and margin/padding is that for the latter, setting to `true` allows the user to set different values for each side, however with block gap, that's not the case. The `blockGap: true` state is already pretty close to a single direction.
* For blocks that want to provide an explicit value for one direction, they can still ship their own override for that direction by providing their own `row-gap` or `column-gap` rule, and the UI for the simple `blockGap: true` should still work for the opposing side.

Thanks for digging in here, and apologies if I'm missing some details on what's expected! CC: @tellthemachines since this relates to the flex layout work.

**Comment by t-hamano** [comment]
Thanks for the detailed description, @andrewserong!

Also, thank you for your comments on related issues and PRs:

- #47523
- #47501

I would like to write here my reasons for raising these issues as I think this issue is appropriate in discussing them.

I started these issues/PRs because of a question about this property that was [posted](https://wordpress.slack.com/archives/C02QB2JS7/p1674827340737559) in the `#core-editor` channel on slack.

I began by examining what values the `blockGap` property supports. I simply thought that if `blockGap` supports arrays, it could be possible to store only one of the values. And for the unsupported direction, I expected the default gap value to be applied. However, the gap control didn't work correctly and I unintentionally determined this behavior to be a bug. I was not aware that in [the document](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-supports/#spacing) indicated in [this comment](https://github.com/WordPress/gutenberg/pull/47523#issuecomment-1407854304) it states that it does not support single direction 😅

As a practical matter, there are not many cases where a developer wants to prevent a gap in one direction from being changed.

I'm wondering if gap support at the block level is currently expected to be used by developers. If so, then I think the explanation in the current document is sufficient (I simply missed it 🙂). If not, I suggest removing that description from the documentation and not adding it to the schema that I am attempting to do with #47501. In other words, I believe that the documentation and schema should be consistent.

**Comment by andrewserong** [comment]
Thanks for laying out your thinking here, Aki! It's very helpful to know that at first glance it looks like a bug, it definitely flags that things can be improved. It's pretty tricky with features that are still undoing development, like layout and gap, to figure out the right level of documentation and how support should work in the editor. Here's some potential ideas for a path forward:

* What if we borrow some of the logic from dimensions supports so that we hide the gap controls if the sides value isn't allowed (e.g. if it only has one direction rather than both)? There is an existing [useIsDimensionsSupportValid](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/hooks/dimensions.js#L335) hook that checks if the sides are correct (used by margin and padding) that hides those controls and generates a console warning if the values are incorrect. Perhaps we could create a variant of that hook for the gap controls?
* I agree with your thinking that the documentation and schema should be consistent... now that we're discussing this in greater detail, I think I lean toward documenting more things rather than leaving them undocumented. What about adding a `description` property to the `blockGap` object in your schema PR (https://github.com/WordPress/gutenberg/pull/47501) flagging that blockGap depends on the experimental layout support? Also, does the schema format allow us to specify that both vertical/horizontal must be listed or none? If so, then I think these two tasks (hide controls and warn if sides are incorrect + land the schema change with the description field) might help us address the original issue raised.

Thanks again for digging in deeply here, I think it's very much worth it to improve how all this works, particularly as it'd be great to proceed with stabilising / clarifying these features where we can 🙂

**Comment by t-hamano** [comment]
Thank you for your advice, @andrewserong!

> I think these two tasks (hide controls and warn if sides are incorrect + land the schema change with the description field) might help us address the original issue raised.

I see, I think those approaches make sense. I would like to update the two PRs currently submitted, each for the appropriate purpose 👍

**Comment by andrewserong** [comment]
> I would like to update the two PRs currently submitted, each for the appropriate purpose 👍

Sounds great. Thank you for your continued work on this! Happy to help review once they're ready for another look 🙂
