### ISSUE TITLE
"Manage Menus" link in template editor

### ISSUE THREAD

**Issue by sebastienserre** [WordPress/gutenberg#47560]
### Description

In the template/template part editor, there's a link "Manage menus" which is pointing on a `wp_navigation`custom post type list (/wp-admin/edit.php?post_type=wp_navigation).
In this link there's no action we can do and surely not manage any menu as we can't add content in it.

I think, this link should be removed

![2023-01-30_15-15](https://user-images.githubusercontent.com/3902621/215510130-773a5db1-23cd-49e0-9cbe-8292c7c1d4b1.jpg)

### Step-by-step reproduction instructions

1. Go to Appearence > Editor
2. Click on a navigation block.

### Environment info

- WordPress 6.1.1
- Not tested with Gutenberg plugin (only Core editor)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No
- Not tested with Gutenberg plugin (only Core editor)

**Comment by carlomanf** [comment]
I'm aware of an issue with this link that I haven't seen reported anywhere yet, but I can't tell whether this is the same issue because you don't provide much information. The reproduction instructions don't really address the issue, they just tell how to locate a navigation block. Similarly, the screenshot doesn't show anything meaningful other than the existence of the link.

What happens when you click on the link, and what do you mean by "there's no action we can do and surely not manage any menu as we can't add content in it?"

**Comment by sebastienserre** [comment]
Hello,

Here's a video showing there's a link which go to a Custom Post Type list of content and when we edit one of the post (which are navigation menu) we can't do anything...
I don't think adding a link which doesn't allow to do anything is needed
https://www.loom.com/share/7c6498dc4c88406091ed5fb3c7863171

**Comment by carlomanf** [comment]
Thanks for the video. It seems to be loading the classic editor for some reason. I don't know whether it's intentional, but if so, it looks like you can still delete and rename them?

The bug that I had noticed is a different one. The link loads an "access denied" message if the current user is lacking the `edit_posts` capability, [despite the post type registration](https://github.com/WordPress/wordpress-develop/blob/6.1/src/wp-includes/post.php#L514) actually declaring `edit_theme_options` as its capability.

**Comment by sebastienserre** [comment]
My message is just "the navigation menu we're seeing is not needed and I think we can remove it"

**Comment by noisysocks** [comment]
I couldn't reproduce this. The screen is clunky and we probably should be linking somewhere better but it _does_ work for me.
