### ISSUE TITLE
Browse Mode: Consider adding a pointer for how to get back to dashboard 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#47583]
## What problem does this address?

Repeated feedback has come in around the FSE Outreach Program and other sources around how to get back to the dashboard while using browse mode. While adding a "dashboard" link is being considered to be brought back, it's also worth considering whether we should add a pointer if this interaction remains without an explicit dashboard link, similar to what's being explored here: https://github.com/WordPress/gutenberg/issues/47410 

Note that this will depend on how https://github.com/WordPress/gutenberg/issues/36667 progresses for 6.2.

## What is your proposed solution?

Add a pointer that explains how to get back to the dashboard. Quick copy idea:

>Trying to return to your dashboard? Just click on your site icon above. 

cc @WordPress/gutenberg-design for feedback and @youknowriad as a heads up.

**Comment by davewhitley** [comment]
I had the same problem. I tried to figure out how to exit this screen and it took a long time to figure out. Here is the part that confused me:

<img width="520" alt="Screen Shot 2023-02-02 at 2 12 52 PM" src="https://user-images.githubusercontent.com/618551/216439840-4d46be07-63d2-492f-9571-da7de87cae5c.png">

It didn't occur to me that the logo might exit or navigate away from this screen. A few reasons for that:
- There's no arrow, icon, or text label that indicates that it might be a button or provide navigation.
- It appeared obvious to me that the logo was part of the card that it's inside (by "card" I mean the dark black rectangle that sits on top of the dark sidebar). Because of that, if I clicked the logo or anywhere in the "Edit" card, I assumed it would take me to some sort of edit screen (probably the WP editor).
- The "Home" and "Templates" text is so close to the logo that I thought they were related.
- Another design (I believe the previous design?) had an arrow with the text "Dashboard". Remembering this design, I thought that perhaps the ability to go back to the Dashboard had been removed.

<img width="682" alt="Screen Shot 2023-02-02 at 2 10 52 PM" src="https://user-images.githubusercontent.com/618551/216441797-8d654c1b-8ce7-47be-b9f1-b10832483253.png">


In this case, I don't think a tooltip is enough, because of the close association of the logo and the Edit button (they are in the same container). People will always associate the two and assume they do the same thing if clicked.

There is also this design that has been standard for a while:

<img width="476" alt="Screen Shot 2023-02-02 at 2 12 20 PM" src="https://user-images.githubusercontent.com/618551/216442732-73b73417-0a7c-4deb-8a0f-c5ffc86751e3.png">

Maybe not ideal, but at least it has a hover tooltip, and I have learned what it does. It has no association with any UI around it, so I learned that it must do something unique (and there's no confusion about its relationship with the surrounding UI). It's a completely isolated element. Because of this previous 

### Ideas for solutions

- Detach the logo from its container that also contains the Edit button. This could include putting the logo outside of the card, or putting it on its own row (not on the same row as the Edit button).
- Putting a back arrow or cross next to the logo.
- Tooltip will certainly help, but I'd like to see additional steps taken

Thanks for logging this issue!

**Comment by ndiego** [comment]
I agree that some additional action should be taken here. Not sure what the best implementation would be, but I foresee confusion, especially since the "beta" label is being removed from the Site Editor. Over the next few months, we will see an influx of new users who may have never experienced the Site Editor before.

**Comment by jameskoster** [comment]
Given the intention is to [add more panels](https://github.com/WordPress/gutenberg/pull/47777), and for this navigation paradigm to (potentially) [scale up to wp-admin](https://make.wordpress.org/design/2022/06/13/thinking-through-the-wordpress-admin-experience/) in the future, adding a Back arrow at the Design level seems the simplest thing to try:


https://user-images.githubusercontent.com/846565/217835285-e0ae607f-948d-4c9b-87e8-035666e6648e.mp4

**Comment by paaljoachim** [comment]
I really like the clarity of having the < (back arrow) and the tool tip that says "Dashboard".
Which @glendaviesnz made in this now merged PR:
https://github.com/WordPress/gutenberg/pull/47950

![Screenshot 2023-02-15 at 07 16 43](https://user-images.githubusercontent.com/5323259/219025192-e72173cd-aa9d-4591-a1ff-0de3985abce5.jpg)
