### ISSUE TITLE
DateTimePicker Displays an Incorrect Calendar if the user's timezone is vastly different from the WordPress one.

### ISSUE THREAD

**Issue by cadwell** [WordPress/gutenberg#47698]
### Description

When the user's timezone is significantly different than the timezone that WordPress is configured with, the DateTimePicker component displays incorrectly. The first day of the month that is being displayed is the last day of the previous month. This causes some days within the month to disappear.  

Similar issue to https://github.com/WordPress/gutenberg/issues/29306 however this targets the month's display.

### Step-by-step reproduction instructions

1. Change your local machine's timezone to somewhere in England. 
2. Set WordPress's timezone setting to Los Angeles.
3. Edit or Add a new post.
4. Open the DateTimePicker component by trying to schedule a post.

### Screenshots, screen recording, code snippet

<img width="270" alt="image" src="https://user-images.githubusercontent.com/167076/216365896-0949ce76-fe3e-4306-adec-f51da2ce2d2f.png">

### Environment info

- WordPress Version 6.1.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by chiltonreaktiv** [comment]
@cadwell I have experienced this issue as well. I was able to reproduce this bug.

**Comment by wojtekn** [comment]
Possible fix: https://github.com/WordPress/gutenberg/pull/47879

**Comment by singhpaul** [comment]
Issue was not resolved by #47879 or there has been a regression because we're able to replicate reliably with the steps outlined by @cadwell above. 

The following screenshot was taken at UTC Feb 2, 2024 @ 2:04 AM. WP and server are both set to New York TZ and the local machine to London TZ. Jan 31 is displayed erroneously, Feb 29 is missing and the current month is mislabeled as January.

![Screenshot 2024-02-02 at 2 05 15 AM](https://github.com/WordPress/gutenberg/assets/7103245/3915bebb-b7c4-4279-af99-b6d97ff4dbd4)

This also has functional implications because the date display offset yields the peculiar behavior that clicking on a date in the calendar updates the form input field date to the *next* date. So clicking on Feb 7 updates the form input field to Feb 8, as seen here:

![Screenshot 2024-02-02 at 2 14 10 AM](https://github.com/WordPress/gutenberg/assets/7103245/22515a48-584f-47e5-bedf-5470d213cc4b)

As @cadwell mentioned, issue seems related to #29306.
