### ISSUE TITLE
Gutenberg 2.1.0 not support add gallery

### ISSUE THREAD

**Issue by Imranaliweb** [WordPress/gutenberg#4771]
Gutenberg 2.1.0 not support add gallery style like: Tiles, Squares, Circle

**Comment by youknowriad** [comment]
Hi, thanks for opening this issue, I think these styles should be probably built as plugins (custom blocks). A masonry layout is explored in this PR though https://github.com/WordPress/gutenberg/pull/4734 

@jasmussen I'm leaning towards closing this issue as Plugin territory.

**Comment by jasmussen** [comment]
Due to the nature of how masonry layouts are best built, I have come around to agreeing that the stock gallery should be vanilla. As such I've closed my other PR.

However, Gutenberg comes with a feature that makes it easy for you to use a masonry layout with your gallery today. Here's a tutorial.

Step 1: add the class name "custom-gallery" to your Gutenberg gallery block:

<img width="279" alt="screen shot 2018-01-31 at 10 13 10" src="https://user-images.githubusercontent.com/1204802/35614456-78c4b99a-066f-11e8-8200-7ab91dfbf45b.png">

Step 2: paste the following into your WordPress theme stylesheet, style.css:

```

ul.custom-gallery {
	column-count: 1;
	column-gap: 0;
	padding: 0;
	display: block;
}
@media (min-width: 600px) {
	ul.custom-gallery {
		column-count: 2;
	}
}
@media (min-width: 960px) {
	ul.custom-gallery {
		column-count: 3;
	}
}
@media (min-width: 1440px) {
	ul.custom-gallery {
		column-count: 4;
	}
}
ul.custom-gallery .blocks-gallery-item {
	display: block;
	width: auto;
	margin: 0;
}
ul.custom-gallery .blocks-gallery-item figure {
	height: auto;
}
```

Your gallery will now look like http://moc.co/projects/

**Comment by Imranaliweb** [comment]
Hi joen, 
it does not work like jetpack gallery and it will not be able to add it easily.

**Comment by jasmussen** [comment]
> it does not work like jetpack gallery and it will not be able to add it easily.

I'm confident Jetpack will update the tiled gallery feature to work with Gutenberg soon enough.
