### ISSUE TITLE
Allow enabling and disabling Layout at block level in theme.json

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#47807]
## What problem does this address?

Currently it's not possible to enable or disable the Layout block support for specific blocks in theme.json.

## What is your proposed solution?

Implement support for enabling and disabling layout from theme.json settings, e.g.:

```
"blocks": {
			"core/group": {
				"__experimentalLayout": false
			}
		}
```

**Comment by andrewserong** [comment]
Thanks for writing this one up! It might be good to combine this with stabilising the layout support at the same time, so that the `theme.json` file doesn't need to use the `__experimental` prefix.

Also, another thought: would setting `layout` to `false` disable only the UI, or also the style output for the layout? Taken a step further, if `core/group` was set to `layout: false`, would that mean that Row and Stack variations would no longer appear in the inserter, and no layout classnames would be added to the rendered block?

**Comment by tellthemachines** [comment]
> Taken a step further, if core/group was set to layout: false, would that mean that Row and Stack variations would no longer appear in the inserter, and no layout classnames would be added to the rendered block?

Without actually testing this, I _think_ that the variations would still appear. Should they? I'm not sure. Also not sure regarding the classnames, I think we'll have to experiment and see what works best! Feedback from extenders would also be welcome.

**Comment by andrewserong** [comment]
> I think we'll have to experiment and see what works best! Feedback from extenders would also be welcome.

Sounds good! It'll be fascinating see what the right level of switching things off is for folks 👍
