### ISSUE TITLE
Use Gutenberg on a real website

### ISSUE THREAD

**Issue by cyrildc** [WordPress/gutenberg#4784]
Can I use Gutenberg on a client website? If not, when do you think it will be ready approximately?

**Comment by jasmussen** [comment]
I use it on my website: http://moc.co, and it's working well for me. I would recommend that you take it for a spin on your own site, and see how it feels. While some features are still missing, we are working hard to get them there, and are very close. I'd say the plugin is definitely stable, though, even if a few things are missing. The bigger issue is plugin support, which is one of the remaining missing pieces, likely to trickle in in the next few months. Hope that helps.

**Comment by laras126** [comment]
Check out Human Made's website and [their write up about it](https://humanmade.com/2018/01/22/gutenberg-on-humanmade-com/). I am currently building a website (a pro bono project for a non-profit) with a few custom blocks that should be launched in a month or so. 

Along the lines of what @jasmussen said: As someone from a background of custom fields-based sites with ACF, it has been very challenging to adapt to the block building tech stack and mindset. If you have the time to put into learning or are already very savvy with JS, then 100% go for it! Otherwise, I would give it a few more months for more support resources (like [create-guten-block](https://github.com/ahmadawais/create-guten-block) – which is amazing) to emerge.

**Comment by karmatosed** [comment]
As you have some responses, let's close this up as it's not an issue as much as a question about implementation.

**Comment by GlennMartin1** [comment]
Ignorant question - I apologize:

So, if I install Gutenberg on my site, convert the pages & posts to blocks, etc.... what happens when WP 5.0 is released? 

Will I simply disable/uninstall the plugin, and it's all set?

**Comment by laras126** [comment]
@GlennMartin1 That's a good question! I can't speak to this 100%, but I imagine the process would be something like that if not easier (e.g. the plugin automatically detected and deactivated when 5.0 is installed). I'd suggest posting this question on issue #4087 for more visibility!

**Comment by jasmussen** [comment]
Good question, and yes, the plugin will automatically be deactivated if it is active when you upgrade to 5.0. CC: @pento

**Comment by pento** [comment]
Yah, the plugin will be automatically deactivated when you upgrade to 5.0.
