### ISSUE TITLE
Post Featured Image Aspect Ratio: Link width and height controls

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#47963]
## What problem does this address?
Since we merged https://github.com/WordPress/gutenberg/pull/47854, the width and height controls work independently of the aspect ratio control and it's not clear how they interact.

Here's a suggestion from @richtabor:

I'm thinking that if an aspect ratio is assigned, then the height/width should adhere to that ratio (regardless of which is changed). For example, if you set the aspect ratio to 16:10, then set a width of 1600px, the height should be auto-set to 1000px. And if you change the height to 800px, then the width would auto-set to 1280 (maintaining the 16:10 aspect ratio).  

We could also leverage the existing link/unlink control to show that the values are linked together (and provide a way to unlink the height/width). If unlinked, then the aspect ratio value should no longer represent the chosen ratio, but rather "Freeform" (or another term if we prefer). 

https://user-images.githubusercontent.com/1813435/217947215-60ee90b4-59e3-4d70-a742-4d3438ece9eb.mp4

**Comment by jasmussen** [comment]
I like it. 

* There's something about the 3 oddly sized cover/contain/fill that feel uneven, and honestly, "Fill" doesn't feel that compelling to me, I can't think of when I'd actually use this. 
* The link/unlink makes sense but I don't love how its placement breaks the otherwise fairly strict 2 column grid that we're aiming for (see also #46734). 

I took a quick stab at a remix:

<img width="364" alt="Frame 1" src="https://user-images.githubusercontent.com/1204802/218137975-ff770a9d-7953-4c5b-9fa6-85e82f9c541e.png">

It's essentially the same mockup, but the width/height becomes a single control rather than two separate ones, so it can have a single label and the link/unlink on the right. This is the same pattern the Font size control uses with the "settings" icon on the right.

It omits the "Fill" option, leaving the two scaling options to breathe. There's a question whether a segmented control is still appropriate when there are only two options, the alternative could be a toggle. But I like how it affords good help-text. What do you think?

**Comment by richtabor** [comment]
> What do you think?

Love it. 

> There's a question whether a segmented control is still appropriate when there are only two options, the alternative could be a toggle.

I think in this case it does track better than a toggle would, especially with the more technical nature of the attribute and the amount of help text. 

Should it be Width & Height, or Height & Width? 

The current control in the core/post-featured-image block is Height/Width, whereas the core/image block is Width/Height.

**Comment by jasmussen** [comment]
I picked width and height to match the sequence of the fields, but no strong opinion.  Can also pair it with onfocus tooltips a la the exploded border control if need be. Also yes, it'd be nice to revisit the featured image control and harmonize 👍 👍

Nice work!

**Comment by scruffian** [comment]
Width and height is the correct order according to the rules of ablaut reduplication.

**Comment by amjadr360** [comment]
> I'm thinking that if an aspect ratio is assigned, then the height/width should adhere to that ratio (regardless of which is changed). For example, if you set the aspect ratio to 16:10, then set a width of 1600px, the height should be auto-set to 1000px. And if you change the height to 800px, then the width would auto-set to 1280 (maintaining the 16:10 aspect ratio).

With this behavior, users will face unwanted width and height image size issues.  Such as, if the user sets the image size as 2000px and wants to set the image aspect ratio to 16:10, it will result in the image size of 1600px, but the user wants 2000px size image. 

I think the aspect ratio should not affect the width/height of the image.

**Comment by richtabor** [comment]
I don't think we need this anymore, with the current implementation of using "Auto". 

<img width="364" alt="Frame 1" src="https://github.com/WordPress/gutenberg/assets/1813435/c99686a9-2c80-4c14-8280-678358875e7d">
