### ISSUE TITLE
Compatibility issue with php 7.4.1 version

### ISSUE THREAD

**Issue by Anjali29dots** [WordPress/gutenberg#48092]
### Description

When we try to activate the plugin, we get this warning.
https://share.cleanshot.com/ccn9Pr1r3CnX98bs1gLS

### Step-by-step reproduction instructions

1. Go to Upload Plugin - WordPress 6.2 Beta 2
2. Go to upload with PHP version downgrade than 8.0.

### Screenshots, screen recording, code snippet

https://share.cleanshot.com/ccn9Pr1r3CnX98bs1gLS

### Environment info

WordPress 6.2 Beta 2
PHP Version: 7.4.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Hi @Anjali29dots,

Thanks for the report.

In your screenshot you can see the following error message: 

```
An unexpected error occurred. Something may be wrong with WordPress.org or this server&#8217;s configuration.
```

This error simply means it tries to connect with the server but could not. In that case, the issue might be listed with your hosting provider or internet connectivity. Therefore, it should not be affected by specific plug-ins or PHP versions.

**Comment by kathrynwp** [comment]
Since this looks to be an issue with your specific WordPress installation, I'm going ahead and closing this out. Since this doesn't appear to be specific to the Gutenberg plugin, please feel free to post in the [Fixing WordPress forum](https://wordpress.org/support/forum/how-to-and-troubleshooting/?view=all) if you need further help.
