### ISSUE TITLE
Query Loop "Create a new post" display error with split tabs

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#48213]
### Description

The new split tabs (between Styles and Settings) is interfering with the existing "Create a new post for this feed" control. Now it sits under the tabs, but is not affected by the tabs. 

There's not really a great place for it. We should either add it to the Layout (not amazing, but keeps the control present) or remove it. 

### Step-by-step reproduction instructions

1. Add a Query Loop block
2. See error in the block inspector

### Screenshots, screen recording, code snippet

<img width="671" alt="CleanShot 2023-02-17 at 10 50 50" src="https://user-images.githubusercontent.com/1813435/219701282-99fd7985-e2f5-4eb8-8c23-6ab333e20c58.png">

### Environment info

- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
@richtabor I believe this was fixed in https://github.com/WordPress/gutenberg/pull/46147 with the removal of color support for the Query block. I do not see a Styles panel in Gutenberg Trunk or Beta 2. When you have a chance, can you confirm? Thanks!

![Image](https://user-images.githubusercontent.com/4832319/220108347-6da05256-ff8d-40fe-bcc8-9993e287da3b.png)

**Comment by richtabor** [comment]
Ah, I'm wondering too if https://github.com/WordPress/gutenberg/pull/48117 led to the Styles tab added back. That PR was merged too — I don't see the tabs here anymore.
