### ISSUE TITLE
Remove "Areas" from template details dropdown

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#48487]
Now that we have List view and improved focus states for the template parts, it's a bit redundant having areas listed here as well. Let's remove these. 

<img width="792" alt="CleanShot 2023-02-24 at 17 59 32" src="https://user-images.githubusercontent.com/1813435/221584133-0c4eff82-3357-4aff-af3f-22cafb272213.png">

**Comment by hanneslsm** [comment]
I like this, but since this makes the "clear customizations" even more prominent (it's now basically the only thing you can do in the dropdown), I'd like to point to one issue, that would add a confirmation modal before clearing the customizations. https://github.com/WordPress/gutenberg/issues/39124

**Comment by mtias** [comment]
Indeed — the collapsed list view now does a better job of presenting the main sections of a template, whether template part based or not. This menu is now rather confusing, particularly given it focuses on the first area it finds by default, so it adds an outline on the canvas.

@HannesDev with revisions for templates exposed, a confirmation seems less necessary (you can restore your changes), but it might still be nice to show and can be a way to tell people that they have revisions (if enabled).
