### ISSUE TITLE
Command palette: Add contextual shortcuts when editing a template

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#48481]
<img width="512" alt="Editing Template" src="https://github.com/WordPress/gutenberg/assets/846565/7825f390-b23e-45b0-a654-fb897364202b">

- [ ] Update document title to open command palette (https://github.com/WordPress/gutenberg/pull/50369)
- [x] Add contextual delete/reset action to command palette (https://github.com/WordPress/gutenberg/pull/50543).
- [ ] Display recently edited templates as shortcuts.
- [ ] Display shortcut to manage templates.

**Comment by jameskoster** [comment]
To connect a dot, adding the 'Recent templates' section here can be a small first step that guides users to this area as a navigational tool for moving around in the site editor. In the future this might graduate to a more elaborate device as described in https://github.com/WordPress/gutenberg/issues/44461#issuecomment-1424412421

**Comment by SaxonF** [comment]
I assume this a potential solution for the issue of "[Quick template switching is still not quite there.](https://github.com/WordPress/gutenberg/issues/48443)". 

Since we are also looking template vs content editing, it might be worth exploring alternative options for quick template switching. e.g. in page inspector. We also have onboarding flows for creating [pages and templates](https://github.com/WordPress/gutenberg/issues/41060) which would be nice to align around.

**Comment by jameskoster** [comment]
Hm, I think those are different things?

Template switching in the context of this issue is about quickly navigating from editing one template to another.

Template switching in the page inspector is about switching which template is applied to that page.

**Comment by SaxonF** [comment]
> Template switching in the context of this issue is about quickly navigating from editing one template to another.

My bad! Can we just lean on [command center](https://github.com/WordPress/gutenberg/pull/49330) for any "in editor" document switching? The templates list in sidebar is otherwise the go-to place for switching/previewing templates. I'm just trying to find opportunities to simplify, and the template details popover feels unnecessary at this point.

**Comment by jameskoster** [comment]
> Can we just lean on https://github.com/WordPress/gutenberg/pull/49330 for any "in editor" document switching?

If we make it more discoverable (IE clicking the template title), then yes I think that makes sense.

**Comment by mtias** [comment]
Where are we on this given the new command palette and header design?

**Comment by jameskoster** [comment]
The command palette should supplant the current popover. I'll update the OP.

**Comment by jameskoster** [comment]
I guess this is tracked by https://github.com/WordPress/gutenberg/issues/50407. I'll close.
