### ISSUE TITLE
No visual indication of switch to default template in the post editor

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#48577]
### Description

When using the template switcher in the post editor sidebar to switch from a custom template back to the default one, there is a brief flash of layout reflow but apart from that no visual indication that the change was successful. Neither the template name in the sidebar or the layout actually changes.

### Step-by-step reproduction instructions

1. In a block theme with more than one post (single) template, create a post and set it to use a non-default template.
2. Save and reload the page.
3. Try switching the template back to the default.

### Screenshots, screen recording, code snippet

![template-switch-to-default](https://user-images.githubusercontent.com/8096000/221753923-3109a655-7532-49f0-94d8-c1aaf9e4f3e9.gif)

### Environment info

I noticed this happening on the latest Gutenberg trunk, but it's also reproducible on WP 6.1.1 with no plugins enabled so it's not a regression from the last release.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
Hmm, I see something different in 6.2 Beta 4 with Gutenberg tunk and without Gutenberg. 

https://user-images.githubusercontent.com/4832319/222250130-9cb2f2e0-1bd9-42eb-b4a5-7ae70d20bd5d.mov

**Comment by tellthemachines** [comment]
@ndiego this issue _only_ occurs when switching from a custom template to the default one, and you have to reload the page in between changes. So if your page is already set to a custom template and you go in and switch it to default, you should be able to reproduce the issue on both Core and Gutenberg.

**Comment by ndiego** [comment]
Ah I see, thanks for the clarification. I can now confirm as well.

**Comment by ndiego** [comment]
I moved to the 6.2 Board. It would be great to get a fix in place, but if we run out of time, I am comfortable punting given the issue has existed in 6.1.

**Comment by talldan** [comment]
Did some debugging of this. It looks like when selecting a default template the post editor falls back to using the `__experimentalGetTemplateForLink` selector:
https://github.com/WordPress/gutenberg/blob/ee4a3ad99a191dabcc175ba8dd60344be1bc46d9/packages/core-data/src/selectors.ts#L1155-L1177

It fetches the template for the post from the server. But the change back to the default template that the user just made hasn't been saved yet. The server is outdated, so the post switches back to showing the previous selection. Wow, this is a horrible bug.

The easiest fix might be to save the post as soon as the template is switched from the dropdown so that server is up to date. 

There might be other options, but I'm not too familiar with the code.

**Comment by Mamaduka** [comment]
This is an old issue and probably a duplicate of #41449. There were a few attempts to fix it, but nothing straightforward to include this late in the cycle.

@ndiego, let's punt this for the next minor or major release.

**Comment by Mamaduka** [comment]
As I mentioned in my previous comment, this is an old issue and a possible duplicate of #41449. Since it's not introduced in 6.2, I'll punt it for the next major release.

**Comment by bph** [comment]
This seems to have been punted quite often. It's now on the project board for 6.5

**Comment by annezazu** [comment]
As part of the[ work to unify post and site editor experiences](https://github.com/WordPress/gutenberg/issues/52632), I wanted to retest this experience with 6.4.2 and GB 17.4.1. I can still replicate this when switching from a custom template back to default: 

https://github.com/WordPress/gutenberg/assets/26996883/a0642186-fd34-47f8-9746-ffc66d5d619e

cc @youknowriad for consideration since this now impacts both page and site editor experiences. Going to put this as to do in 6.5 for now.
