### ISSUE TITLE
Template Revisions: Revisions button not showing until after making non-paragraph edits.

### ISSUE THREAD

**Issue by jordesign** [WordPress/gutenberg#48610]
### Description

Testing revisions in both Templates and Template parts on a fresh install - it seems revisions aren't initialised by simple text edits (and saves) adding paragraphs. 

The revisions button only appear after making a more involved edit (and save) like adding an image.

### Step-by-step reproduction instructions

1. Start a fresh WordPress install with Gutenberg 15.2 installed and active.
2. Open the Site Editor and open a template or template part to edit.
3. Add a paragraph with text to the template and save the changes.

You can check for template revisions immediately, or after closing and re-opening the Site Editor. But none will appear.

4. Edit the template again and make a different change, like adding an image, and saving the changes.

After this edit - revisions will start showing.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1842363/222038912-1bd0dae0-c232-4d36-97e6-0c3cb7b96dc6.mp4

### Environment info

WP 6.1.1 and GB 15.2.2
No other installed plugins
Theme: TwentyTwentyThree

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
@draganescu can you look into this perhaps? :)

**Comment by draganescu** [comment]
Interestingly 2 revisions appear. I will investigate when I catch some empty slot :)

**Comment by Mamaduka** [comment]
@draganescu, we're not shipping the revisions button in 6.2, correct?

**Comment by draganescu** [comment]
We are not because it's having a bigger problem in core - the links in the revisions screen are broken because template and template part post types don't have an url for editing them by definition.

**Comment by draganescu** [comment]
Yes, the problem here is that the templates and template parts are not in the database and the 1st time they're edited they're basically added to the database, along with their edit. This shows up as two revisions, one with an empty post and one with the post having all the content (including the 1st edit).

Starting only with the 2nd edit, which will result in 3 available revisions, will we see actual diffs.

Here is a video demonstrating:


https://user-images.githubusercontent.com/107534/225954617-eeefff85-3ff2-41c0-adc3-68c0f20de748.mp4

**Comment by draganescu** [comment]
I will close this to continue tracking the bug in #49164. Thank you @jordesign 🙏🏻
