### ISSUE TITLE
"wp-scripts build" doesn't copy reneder callback php file from src to build folder if "render" property set in block.json metadata

### ISSUE THREAD

**Issue by realthemes** [WordPress/gutenberg#48696]
### Description

I'm developing my custom block plugin using create-block script, when the turn came to render callback file I set "render" metadata in block.json file like it say in documentation: "render": "file:./render.php", I also place file render.php in block folder but when I try to compile plugin whith `npm run build` command, the render.php file doesn't copied to /build/my-block/ folder, actually rest of plugin are compiling normally the only problem is copying. Currently I forced to use special command to force copy PHP files to build folder

### Step-by-step reproduction instructions

1. create block plugin with create-block
2. set "render": "file:./render.php" metadata in block.json
3. compile whith "npm run build" 
4. there no render.php file in build folder

### Environment info

Wordpress 6.1.1, built-in Gutenberg, custom theme
Google Chrome
Windows 11

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by torounit** [comment]
Try `$ wp-scripts build --webpack-copy-php`.

**Comment by realthemes** [comment]
Thanks for the tip, yes I forced to use  --webpack-copy-php  command to
copy PHP, it works perfectly but in Wordpress documentation it is say that
PHP must be copied with default commands wp-script build if "render" field
specified

пт, 3 мар. 2023 г. в 08:39, Hiroshi Urabe ***@***.***>:

**Comment by gziolo** [comment]
@realthemes, thank you for the report. What version of `@wordpress/scripts` do you have installed? https://github.com/WordPress/gutenberg/pull/43917 added support for automatic copying of the file defined in the `render` field of `block.json`.  As far as I can tell, the version should be greater than `24.0.0`.

I see that you noted that you use Windows, so maybe there is something wrong with how paths are handled. @t-hamano, would be so kind to verify that?

**Comment by realthemes** [comment]
@gziolo here is the version - "@wordpress/scripts": "^25.4.0", sorry I was need to say that I make my plugin from single block to multiple block plugin, currently I have `src` folder and inside it nested my blocks folders, but I'm pretty sure that there no problem, beqause: 1. my plugin are compiling and all blocks are working, 2. If I use `$ wp-scripts build --webpack-copy-php` command then PHP file are copied correctly.

**Comment by gziolo** [comment]
As long as the PHP file's path is relative to `block.json`, then it should pick it up. I assume it is because you didn't report issues with JS and CSS.

**Comment by t-hamano** [comment]
I didn't know until now that if the path to `render.php` is defined in `block.json`, it is automatically copied 😅 I mistakenly thought that we needed to specify the `--webpack-copy-php` option in order to copy the PHP file containing `render.php`.

Indeed, on Windows OS, it appears that the PHP file paths defined in `block.json` are not being copied. Below are the test results. I would like to explore the cause of the problem.

### On Windows11

#### Build a single dynamic block

- ❌ `wp-scripts build`: `render.php` file is NOT copied to the `build` directory
- ✅ `wp-scripts build --webpack-copy-php`: `render.php` file and other PHP files are copied to the `build` directory

#### Build multiple blocks

- ❌ `wp-scripts build`: `render.php` file is NOT copied to the `build/{block}` directory
- ✅ `wp-scripts build --webpack-copy-php`: `render.php` file and other PHP files are copied to the `build/{block}` directory

### On WSL2 (Ubuntu)

#### Build a single dynamic block

- ✅ `wp-scripts build`: `render.php` file is copied to the `build` directory
- ✅ `wp-scripts build --webpack-copy-php`: `render.php` file and other PHP files are copied to the `build` directory

#### Build multiple dynamic blocks

- ✅ `wp-scripts build`: `render.php` file is copied to the `build/{block}` directory
- ✅ `wp-scripts build --webpack-copy-php`: `render.php` file and other PHP files are copied to the `build/{block}` directory
