### ISSUE TITLE
Custom Page Template Not Showing Correct Selection in Page Editor

### ISSUE THREAD

**Issue by krackajackfoo** [WordPress/gutenberg#48783]
Wordpress V 6.1.1

I manually created and uploaded a custom page template called Serenity to my child theme. The template works correctly, no issues there at all. However, I noticed that when I go in to edit a page and apply that page template, the page template selector doesn't display "Serenity" after it's been selected, it continues to display as "Default Page Template", even though the Serenity template is applied and is active.

When you are in the Pages screen of Wordpress admin, and you select QuickEdit on a page that has the Serenity template applied, the correct template displays properly here.

So essentially, my custom page template isn't being listed as active inside the page editor, but it is in the quickedit screen. 

![Serenity Code](https://user-images.githubusercontent.com/39440299/223121142-a8100dad-3ea4-4dd1-85d1-3436360d4ed7.jpg)
![4ac0503a-7698-4bbd-a73b-f4a1a2bd7d97](https://user-images.githubusercontent.com/39440299/223121137-eabd4401-ae4d-42c8-ad26-e5cd3895ae99.jpg)
![96ad10da-1693-4837-bb1b-b2047502d34f](https://user-images.githubusercontent.com/39440299/223121140-41c4d341-ba39-4dd4-bfb7-e8302a1999d2.jpg)
![Serenity Quickedit](https://user-images.githubusercontent.com/39440299/223121134-b8fe9ba2-66e1-4d90-80e6-f43d970a36de.jpg)

**Comment by kathrynwp** [comment]
Hey there, and welcome to GitHub! Thanks for all the screenshots and replication steps.

I was able to replicate this issue **intermittently** with a child theme of Twenty-Twenty.

### Specs:

- WordPress 6.1.1
- No active plugins
- Theme: Twenty Twenty child -
- [twentytwenty-child.zip](https://github.com/WordPress/gutenberg/files/10913560/twentytwenty-child.zip)
 
### Steps to replicate

1. Create a child theme of a classic theme 
2. Add a custom page template to the child theme (try the zip attached above or create your own)
3. Install and activate child theme
4. Go to Pages and create a page, or edit an existing page
5. In the Page Settings' Template area, select the custom page template from the child theme

### Result:

The template still says "Default template"

### Expected:

The displayed template name should match the name of my custom template

### Intermittent

When I went to repeat the test to make a screen recording, this bug did **not** occur again, and the template name appeared correct.

Screencast showing the correct behaviour:

https://user-images.githubusercontent.com/7662449/223541031-ad3317d2-a795-4963-8758-1803ac8c4b72.mov

**Comment by kathrynwp** [comment]
@krackajackfoo I found this issue which could possibly provide a clue:

https://github.com/WordPress/gutenberg/issues/47428

Could you please confirm whether either your parent theme or child theme contain a` theme.json` file? Your screenshot doesn't show one in your child theme, but it's possible you added one afterwards. I also downloaded Kadence [from here](https://wordpress.org/themes/kadence/) and don't immediately spot one, but would appreciate you double-checking both folders on your end. Thanks!

I originally had a `theme.json` file in my Twenty Twenty child theme, but later removed it, so that could account for my intermittent own intermittent test results.

**Comment by krackajackfoo** [comment]
Negative. No `theme.json` file in parent or child theme. There is a `package.json` file in the parent theme folder, but it doesn't appear to be pertinent to this issue.

**Comment by Mamaduka** [comment]
This is probably a duplicate of #41449.

**Comment by Mamaduka** [comment]
This issue was reviewed in today's Editor Bug Scrub. We have been unable to replicate using the latest versions of Gutenberg (15.7) and WordPress (6.2). Therefore, I am going to close this issue. If anyone can replicate it in the future, please feel free to reopen this issue with additional information.
