### ISSUE TITLE
Site Editor sidebar: unable to scroll, Save button hidden

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#48796]
When there are a long list of items in the sidebar the save button gets pushed off the viewport entirely, and it's not possible to scroll the contents to view it:

https://user-images.githubusercontent.com/846565/223163111-5e1e47f1-ba66-4de3-a388-ae1bf163ec4e.mp4

cc @youknowriad

**Comment by carolinan** [comment]
I can reproduce this if Gutenberg trunk is active, but not with only 6.2-beta4-55469. (chrome, macos)

**Comment by t-hamano** [comment]
I expect this is due to the removal of the `overflow:hidden;` in #48399.
https://github.com/WordPress/gutenberg/pull/48399/files#diff-b948436daf4637baf6bada5f65931d841feed7039369fba4176b1afb23d497f4L56

This PR has been backported to WordPress 6.2 and I believe this issue needs to be fixed. However, simply reverting to this CSS seems a bit unnatural. The reason is that the description panel added by #48739 scrolls at the same time.

https://user-images.githubusercontent.com/54422211/223365500-f219e14f-40d2-47a3-8bfe-40795f78d820.mp4

**Comment by youknowriad** [comment]
I've got a fix coming

**Comment by ntsekouras** [comment]
Fixed here: https://github.com/WordPress/gutenberg/pull/48822
