### ISSUE TITLE
Block validation failed for `core/group`

### ISSUE THREAD

**Issue by SabathMedia** [WordPress/gutenberg#48911]
### Description

I get this message for every page (event for empty/new pages):
`Block validation failed for 'core/group'.`

### Step-by-step reproduction instructions

1. Create an empty page.

### Screenshots, screen recording, code snippet

<pre>
Content generated by &#x60;save&#x60; function:

&#x3C;div class=&#x22;wp-block-group alignfull has-background-color has-white-color has-black-background-color has-text-color has-background has-link-color&#x22; style=&#x22;margin-top:0;margin-bottom:0;padding-top:var(--wp--preset--spacing--60);padding-right:var(--wp--preset--spacing--40);padding-bottom:var(--wp--preset--spacing--60);padding-left:var(--wp--preset--spacing--40)&#x22;&#x3E;&#x3C;/div&#x3E;

Content retrieved from post body:

&#x3C;div class=&#x22;wp-block-group alignfull has-background-color has-white-color has-black-background-color has-text-color has-background has-link-color&#x22; style=&#x22;min-height:40vh;margin-top:0;margin-bottom:0;padding-top:var(--wp--preset--spacing--60);padding-right:var(--wp--preset--spacing--40);padding-bottom:var(--wp--preset--spacing--60);padding-left:var(--wp--preset--spacing--40)&#x22;&#x3E;

&#x3C;/div&#x3E;
</pre>

### Environment info

WordPress 6.1.1 (Fresh installation, no plugins, default theme).
Gutenberg
PHP 8.0
MySQL 8.0.16

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by gocemitevski** [comment]
I'm getting the same error under `wp-env` for all existing and new pages. This appears to be a problem in `https://c0.wp.com/c/6.1.1/wp-includes/js/dist/blocks.min.js` line 10.

**Comment by jmaleman** [comment]
The same here! But I don't have installed Gutenberg plugin. When I install Gutenberg this error disappear. 😑

**Comment by metropoliscreative** [comment]
I am also getting these block validation errors for the 'core/group' block on multiple sites with all plugins disabled, not using the Gutenberg plugin. I'm pretty sure this started within the last 24 hours.

**Comment by kylegilman** [comment]
This has been driving me crazy! I'm developing a custom block and I thought I had done something really serious. I created a new, clean site and tested in Chrome & Edge on Windows, and on Safari on Mac. I got the same errors in the console. I also believe it started in the last 24 hours, but I can't figure out what could have changed. 
WordPress 6.2-beta5 does not have the error.

**Comment by t-hamano** [comment]
I have identified the cause of the problem. I was able to reproduce this issue with a new WordPress 6.1.1 installation.

The problem is that some block patterns retrieved from the remote block pattern directory do not match the block support supported by WordPress 6.1.X.

- https://wordpress.org/patterns/pattern/footer-with-background-color-and-three-columns/
- https://wordpress.org/patterns/pattern/centered-footer/
- https://wordpress.org/patterns/pattern/centered-footer-with-social-links/

As you can see in the error message, those patterns contain group blocks with the `min-height` style applied. `min-height` block support will be supported starting with WordPress 6.2, as described in [this post](https://make.wordpress.org/core/2023/03/06/minimum-height-dimensions-block-support/).

Therefore, if you add the following code, the error message should not appear.

```php
add_filter( 'should_load_remote_block_patterns', '__return_false' );
```

However, as noted in [this comment](https://github.com/WordPress/gutenberg/issues/45179#issuecomment-1298771641), patterns tagged with numbers above the current WordPress version should not be included in the response.

@ryelle 
If you know anything about this issue, please let us know 🙏

**Comment by SabathMedia** [comment]
My quick fix was to remove `"dimensions":{"minHeight":"40vh"}}` and `style="min-height:40vh"` from the `wp_options` table. The `options_name` is  `_site_transient_wp_remote_block_patterns_##########`.

**Comment by ndiego** [comment]
Since this issue does not appear to be related specifically to 6.2, I am removing it from the [project board](https://github.com/orgs/WordPress/projects/63). But please let me know if I am interpreting the issue.

**Comment by ryelle** [comment]
Those three patterns were set as "6.1+", so they would load in 6.1. Since it sounds like they should be 6.2+, I've updated the meta on each. They should not be loaded on 6.1.x sites anymore.

**Comment by t-hamano** [comment]
@ryelle 
Thank you for your response! I have confirmed that the console error no longer appears in WordPress 6.1.1.
