### ISSUE TITLE
Inserter: I should be able to drag an image from Media or Openverse into an Image block

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#48919]
The following demo video shows opening the inserter, inserting a gallery pattern from the patterns tab, then adding images from Media and Openverse tabs into the pattern:

https://user-images.githubusercontent.com/1204802/223682458-3cc2e200-b054-4c14-bba6-49729602e48b.mov

The issue here is that when I drag an image from the Media or Openverse tabs into the pattern, I expect to be able to drag these _on_ to existing Image blocks and replace their contents. At the moment, I can only insert _after_.

When I drag an image from my desktop into an image block, I can drop it onto the image:

![drag and drop from desktop](https://user-images.githubusercontent.com/1204802/223682975-1f615e3b-6e4a-400e-87b9-f32c9c2e131a.gif)

Same behavior should be possible from the inserter.

**Comment by annezazu** [comment]
Adding for consideration for 6.2.1!

**Comment by kevin940726** [comment]
This is an interesting one. Upon dragging from the inserter, the openverse media will be converted to corresponding blocks. In this case, an image will be converted to an image block, so we're not dragging the image but the image block.

We can try solving this by allowing image blocks to be dropped on another image block, and replacing the image content within it. I'm not sure if this is the desirable solution and what problem would surface though.

Another solution is instead of converting images to image blocks, we just drag images instead. I think this could probably break a lot of other things though, and we could lose some information in between (alt text and title for instance).

I'll continue to try things locally, but if anyone has better ideas, please share! ❤️

**Comment by ntsekouras** [comment]
@kevin940726 I have opened a [draft PR](https://github.com/WordPress/gutenberg/pull/49297) exploring some things and could use some input.

**Comment by kevin940726** [comment]
@ntsekouras Nice idea! I've thought of something like that before but gave up on jumping into that rabbit hole 😅 . Perhaps I should pick it up again 🤔 .

The HTML5 DnD API actually supports setting multiple different types of data. Furthermore, it's actually [preferred](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/Recommended_drag_types#dragging_images) to set multiple fallback data types. Perhaps we can solve this by setting both `wp-blocks` and `text/html`, then let the drop handlers decide which data types to receive.

**Comment by Mamaduka** [comment]
I chatted with @ntsekouras, and this feels more like an enhancement request than a bug. So I'm going to punt the request for the next major release.

**Comment by jasmussen** [comment]
I respectfully disagree that it's an enhancement vs. a bug, I consider it in fact pretty crucial. As far as it being punted to the next major release, however, I do respect that. The ship is out to sea! 

_But if a tugboat were able to catch up, I wouldn't object!_

**Comment by ntsekouras** [comment]
I'm refreshing my [PR](https://github.com/WordPress/gutenberg/pull/49297) and will try to land this for `6.2.1`.
