### ISSUE TITLE
Way to convert theme.json to theme.css in Gutenberg Editor

### ISSUE THREAD

**Issue by salahtobok** [WordPress/gutenberg#49007]
**Hi guys** 
I'm salahtobok , I'm interested in developing a Blog websites using both using Headless approach which provided by Wordpress ( Rest Api ) & SPA Technologies ( ex : Angular  ) ;
So my request is the following ; if you can give me an idea to convert theme.json to theme.css, because that is so important for me when I start coding a ( blog post page ) using angular while I can't use theme.json directly to style ( post content component )  which its data was generated by Gutenberg Editor .

**Note :** in the previous version of Gutenberg Editor I easily was able to to code ( blog post page ) because the styles of Gutenberg Editor style-editor.css was originally generated with ( twentytwentyone theme ), but now with the new feature of theme.json , everything has changed, see the picture below  .

![WhatsApp Image 2023-03-11 at 9 58 29 AM](https://user-images.githubusercontent.com/13577406/224475883-1c8a4ded-d0fd-44a9-8cba-7d9b54be0eee.jpeg)

Thank you in advance .

**Comment by tellthemachines** [comment]
Interesting question! With theme.json things are a little more complex than they used to be, because now the CSS styles are generated dynamically from multiple sources: base core styles, theme styles and user configured styles (that can be set in the global styles interface in the site editor).

I guess it would be possible to [extend the REST API](https://developer.wordpress.org/rest-api/extending-the-rest-api/) to create an endpoint for global styles CSS that could then be used in a SPA front end. 

If you're happy to use PHP, the `wp_get_global_stylesheet` function will output the merged core, theme and user styles in CSS format.

I hope this helps!
