### ISSUE TITLE
Allow WordPress globals and WP Query in block patterns

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#49006]
## What problem does this address?

Block patterns can be added as a PHP file and be built using some PHP.
But some of the most common WordPress functions used in both plugins and themes are unavailable, and its not as useful as it could be.
I can even see that creating patterns could replace the need for building custom blocks in some cases, if we had access to WP query.

If I understand correctly, it is because they are registered on init.
Can they be registered later?
https://github.com/WordPress/wordpress-develop/blob/6.1/src/wp-includes/block-patterns.php#L337

**Comment by fabiankaegy** [comment]
Question on this though 🤔 If patterns had more access and could use queries. Wouldn't that actually cause a lot of confusion for users since they might think the data in the pattern actually is dynamic when in fact it is only dynamic up until the point where the pattern is inserted and then it has no connection to the actual query and instead just renders a plain string (for example)

**Comment by huubl** [comment]
Changing the hook to 'wp' seems to work:

```
remove_action( 'init', 'gutenberg_register_theme_block_patterns');
add_action( 'wp', 'gutenberg_register_theme_block_patterns' );
```

**Comment by iandunn** [comment]
This is also a problem when a block theme defines a pattern and calls it from a page template, and then that pattern calls a function defined in the theme's `functions.php`. That file hasn't been loaded yet, so it'll trigger a fatal error. Could it be moved to `after_setup_theme` instead of `wp`?

If not, then maybe the logic in `gutenberg_register_theme_block_patterns()` can be split into two functions? The first could run at `init` and use `file_get_contents()` to populate `$pattern_data` based on the file headers, and then register the pattern. The second could run at `after_setup_theme` and include the file and store the content. I'm not sure if that would work, it's just a rough idea.

**Comment by iandunn** [comment]
Er, nevermind, `init` is later than `after_setup_theme`. I was seeing the fatal on `wp-admin/upgrade.php?step=1`, not the front end. So, it may be somewhat related to this issue, but probably not directly.

**Comment by carolinan** [comment]
I consider this solved with the block bindings.
