### ISSUE TITLE
Author dropdown on Edit Post page does not show all authors

### ISSUE THREAD

**Issue by johnnychrome** [WordPress/gutenberg#49015]
### Description

On sites with a large number of authors, the Author drop-down on the Edit Post page does not show a complete list of all authors on the site when the Gutenberg editor is enabled.

I have a site with about 160 authors. With Gutenberg is enabled, the dropdown shows a fraction of this count.

I have tried disabling all plugins and deleting the cache on a staging site: no change.

What DOES fix, is disabling Gutenberg. The classic editor dropdown shows all authors, as I would expect.

This bug has been present for a long time, but I just finally got around to trying to troubleshoot (WP 6.1.1) to make sure it wasn't a custom function I'd set up or a plugin creating the issue. Still could be, but seems isolated to Gutenberg.

### Step-by-step reproduction instructions

1. Edit a post on a site with a large number of authors, with Gutenberg enabled
2. Look at the Authors dropdown
3. Notice that there are only a limited listed shown
4. Back out to the main Posts page
5. Click the Quick Edit link
6. Look at the Authors dropdown and notice that it shows all authors

### Screenshots, screen recording, code snippet

Gutenberg, only a fraction of users in list:

<img width="1280" alt="Gutegberg" src="https://user-images.githubusercontent.com/127689690/224566985-d0402bbf-4b74-4389-8952-ff3e86b3b26c.png">

Classic, look at all those users!

<img width="1280" alt="Classic" src="https://user-images.githubusercontent.com/127689690/224567014-05460eb8-83b8-4c8e-91b3-0c85500edd43.png">

Apologies if this is a duplicate. I HAVE searched for similar issues in the repo per instructions below, but I'm new to Github so my searching skills might not be the best...

### Environment info

- Wordpress 6.1.1
- Safari, Firefox

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Hi, @johnnychrome

The dropdown should display 50 users at a time. In addition, you can search for an author by typing the name in a field.

Is the search feature not working for you?


## Screencast

https://user-images.githubusercontent.com/240569/225290380-f95fc046-4642-4012-acae-e29de4178e72.mp4

**Comment by johnnychrome** [comment]
> Hi, @johnnychrome
> 
> The dropdown should display 50 users at a time. In addition, you can search for an author by typing the name in a field.
> 
> Is the search feature not working for you?
> 
> ## Screencast

@Mamaduka: Appreciate your reply. I tested, and the search feature does _does_ work for me. Slapping my head here, I had not tested the search field to see if it would find users above and beyond those shown in the immediately visible drop down list.

**Comment by Mamaduka** [comment]
@johnnychrome, I'm happy it helped.

There are many user experience gems in the Editor, and it's hard to remember all of them.

**Comment by jamesnclud** [comment]
Dang, how did you get the search to work? I have the same exact issue on multiple sites. Confirmed it's not a plugin or theme code messing with some author-related filter, seems like the rest api just won't go beyond 51 results. Using the search field will only search the 51 results, but there are over 600 users on the site that should be listed/searched as well.

**Comment by Mamaduka** [comment]
Hi, @jamesnclud

The search results are limited to 51 users. Usually, that's enough to search users by name. Can you share more details about your issue?

Fetching all users/authors will affect editor performance on large sites.

**Comment by jamesnclud** [comment]
Hi @Mamaduka thanks for responding.

Well there are 154 users on this site, so if the author field is limited to 51 users then we're missing about 2/3 of the full list. We found a workaround for now to use the Quick Edit feature on the admin listing page, that still uses a <select> field with all of the authors as options. A bit unwieldy but hey at least it works.

To test it more I set up a basic WP site locally and used Fakerpress (https://wordpress.org/plugins/fakerpress/) to generate 500 users. I see the same issue, where that author field will fetch the first 51 users and no more. The search feature kinda works, but it only searches through those initial 51 results. It won't query all of the users.

I agree fetching all of the users at once would be ridiculous and it would definitely affect editor performance. The author field seems like a good use-case for querying the next set of authors when you scroll to the bottom of the list. Heck I thought it was already supposed to do that but I guess not. Or just allowing it to search all users, but that seems to be how it works for other people, just not me or my organization.

It's a tough problem to troubleshoot too because there are no console errors in the browser, and there are no errors in the server's error log.

_(EDIT: sorry for the giant paragraph here, this text editor does not like where I added new lines I guess.)_

**Comment by Mamaduka** [comment]
Sorry for the late reply, @jamesnclud!

Below is a screencast of my test search — 200 authors on a site generated via WP CLI. You can see that the component fetches authors not listed initially.

When searching for a user, do you see any errors/warnings in a DevTools console?

## Screencast

https://github.com/WordPress/gutenberg/assets/240569/c1079bae-2a28-4a70-91a9-d5d2dc9ec4b3

**Comment by lanceolenik** [comment]
We have this problem as well. It seems odd that the authors list under Quick Edit doesn't affect performance, but putting it in the main editor does.

In our situation, the search _does_ return authors who aren't in the initial drop-down, but again, this seems like a strange issue to not fix. Or at least create a setting that allows admins to choose how many authors to show or even choosing specific authors for the list that are more commonly used instead of the first 50 alphabetically.

**Comment by Soben** [comment]
Noting that we're encountering this issue as well. We have ~20 users with the name `Lauren` but only 10 shows up in the results when searching for 'Lauren' ... We entered the last name of a Lauren who doesn't show up in the results, and they don't show up for their own last name.

Users were added programmatically via Import plugin.

**Comment by Soben** [comment]
In my case, the user had incomplete user settings. They were missing the `wp_user_level` meta key, so they did not have correct roles associated with them.
