### ISSUE TITLE
Blank state for post content block

### ISSUE THREAD

**Issue by SaxonF** [WordPress/gutenberg#49086]
## What problem does this address?
With more emphasis being put on content within the site editor its becoming increasingly important to highlight the boundaries between template and page/post content. 

When editing an empty page via the site editor the `Post Content` block is essentially invisible until you select it in the layers panel. This puts the user at risk of adding content to their template rather than their page.

https://user-images.githubusercontent.com/1072756/225223425-6c0ac5b0-71ac-4ee7-b286-8a1b983b8123.mp4

## What is your proposed solution?
The post block should always show a prompt via an empty paragraph block. If post block is empty we can also include a quick link that opens up the patterns inserter. Eventually this link can tie into whatever is designed for [the new page flow](https://github.com/WordPress/gutenberg/issues/48456).

https://github.com/WordPress/gutenberg/assets/1072756/32076043-a406-4c1c-a15e-a60c7d8fd495

cc @WordPress/gutenberg-design

**Comment by paaljoachim** [comment]
Brainstorming...
Should the Post Content block just be an empty block to where one can not do anything with it?
As the post content in itself should be edited directly in the page.

Then again...
Let's say that I have a specific pattern/full page template I want to use for all my pages. So that when I enter a page that I see the pattern in place added through the page template. 

Case study.
It could be something like this old Spiritual Film club movie archive I used ages ago for each movie screening.
Here is one example.: https://spirituellfilm.no/filmer/190511-the-dreamseller/
Having a CPT named movies. Going to the CPT movie page template adding in a specific full page template/pattern into the Post Content block. With the structure in place I would then just go and create a new page and fill in the content inside the pattern. Keeping a consistent look for each movie that is added.

So that would make option 1. As I do not right now see the purpose of adding a paragraph block to it....

In relation to the description.
As making changes here can have unwanted effects because a person is not sure what this block does.
Making a change here will add the content to all your pages or posts.

A question comes up. Will adding content here replace all of the content in all the pages/posts? Or will it in a way add to the existing content?

**Comment by jasmussen** [comment]
@SaxonF is this partially addressed by #49980?

**Comment by SaxonF** [comment]
@jasmussen That works helps as it introduces another way to select the post content block but the core problem still remains. When a page/post has no content, the post content block is invisible / cant be selected under certain conditions.

**Comment by jameskoster** [comment]
> The post block should always show a prompt via an empty paragraph block

This seems like a reasonable place to start. It makes it much more obvious where to begin adding content:

<img width="1054" alt="Screenshot 2023-05-12 at 10 27 22" src="https://github.com/WordPress/gutenberg/assets/846565/851f20c9-9dc5-4f8f-98ae-7a3927a82cc5">

The prompt to select a pattern would be good to include, but I'm not 100% convinced about the design for that in the OP, mostly because it might be tricky to get the on-canvas appearance right. If it uses the admin-theme-color, we might run into contrast issues. If it uses the theme's link color, well, it looks like an actual link rather than part of the UI. 

Given the pattern prompt should appear automatically when _creating_ the page, maybe we don't need this secondary affordance? I don't think it would hurt to tackle that part in a follow-up?

**Comment by jasmussen** [comment]
> This seems like a reasonable place to start. 
> Given the pattern prompt should appear automatically when creating the page, maybe we don't need this secondary affordance? I don't think it would hurt to tackle that part in a follow-up?

I'd echo this.

**Comment by paaljoachim** [comment]
As editing a template <-> page/post comes closer and closer to each other. It seems like template parts are just patterns which are synced. If one for instance clicks a header or footer while editing a page/post initially it can be locked. With a message that this is a synced pattern (reusable block). To edit would mean adjusting all instances of where these are used. Click to continue to edit or click cancel. I know something like this has been discussed elsewhere.

Having the standard prompt "Type / to choose a block" which is seen in a page/post gives a hint and keeps the association to the regular page/post one can add blocks to.
