### ISSUE TITLE
Site Editor: Unnecessary commas in text of excerpt block of posts only in preview

### ISSUE THREAD

**Issue by miminari** [WordPress/gutenberg#49121]
### Description

When I convert WordPress to Japanese and open the site editor, I get unnecessary commas in the text of the excerpt block of a post. This phenomenon has been observed only on the site editor. I tried changing to several other languages(簡体中文, Espanol etc.), but this occurred only in Japanese.

### Step-by-step reproduction instructions

1. Activate Block Theme.
2. Change site language "日本語"
3. Go to "Site Editor".

### Screenshots, screen recording, code snippet

![スクリーンショット 2023-03-16 9 37 25](https://user-images.githubusercontent.com/487207/225479509-945e5b8e-8a3a-42a2-a7d1-78f1db132012.png)

### Environment info

- WordPress 6.1.1 and 6.2
- Gutenberg 15.3.1
- Mac OS 12.5.1
- Google Chrome 111.0.5563.64

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by miminari** [comment]
And, this maybe same issue, in the frontend, it seems that Japanese post couldn`t excerpt correctly ( the texts are too long ). This phenomenon also occurred on English mode. 
![スクリーンショット 2023-03-16 10 07 21](https://user-images.githubusercontent.com/487207/225484080-b183eb6a-73a2-4e54-b087-ae77c096311e.png)

**Comment by t-hamano** [comment]
@miminari 
Thanks for the report.

I think #49123 will solve this problem.

> And, this maybe same issue, in the frontend, it seems that Japanese post couldn`t excerpt correctly ( the texts are too long ). This phenomenon also occurred on English mode.

This problem is caused by the fact that the word count rules change depending on the site language.

If the site language is English, the text divided by a space is considered a single word. Therefore, if the target text is in a language where it is desirable to count according to that rule, the word count will work as expected. However, for languages such as Japanese, where one character should be counted as one word, this rule will not work correctly.

If you change the language of your site to Japanese, the Japanese excerpts will be trimmed to the expected length. Instead, the English excerpts will not work as expected because they are counted character by character.

Ideally, the language of the given text should be parsed and counting rules applied according to that language, but I think that is a separate issue to be discussed.

**Comment by miminari** [comment]
@t-hamano Thanks for the super-fast PR!

 I've figured out my misunderstanding.
And, It is too tough for me (maybe everyone) to get into the matter of the word count rule 🤪

If there is a site that needs to handle multilingual articles at the same time, I think it would be safe to use CSS on the theme or plugin side 😉
