### ISSUE TITLE
Image block placeholder not showing border or radius 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#49144]
### Description

The placeholder for the image block no longer reflects border or radius changes. 

### Step-by-step reproduction instructions

1. Add an image block.
2. Open block settings and change border and/or radius.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/225711625-5704b945-ae57-4c45-bc89-eec4bbf61021.mov

### Environment info

WP 6.2 RC2 with and without GB 15.3.1 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
This bug was [introduced in 6.1](https://github.com/WordPress/gutenberg/pull/31366), not in 6.2. Technically, this should not be fixed during 6.2's RC cycle.

**Comment by aaronrobertshaw** [comment]
> The placeholder for the image block no longer reflects border or radius changes.

Digging into this issue, it appears more a gap rather than a bug per se. The Post Featured Image block has its borders applied to the placeholder but this wasn't the case for the Image block.

I've updated the Image block in https://github.com/WordPress/gutenberg/pull/49569 so it will apply any borders to its placeholder content but only when the block isn't selected.
