### ISSUE TITLE
Move global styles to main menu

### ISSUE THREAD

**Issue by huubl** [WordPress/gutenberg#49187]
## What problem does this address?
I think there are too many buttons, options, tabs etc in the right sidebar. It feels a bit cluttered.

## What is your proposed solution?
Move Global Styles to "main menu" of the site editor:

![site-editor-global-styles](https://user-images.githubusercontent.com/50170696/226208798-df8ab067-bdb0-4046-bbb2-ab164a5963d1.png)

When Global Styles is clicked: show the Style Book as preview to configure the styles (with the option to switch to a page as preview), something like:

![site-editor-global-styles-2](https://user-images.githubusercontent.com/50170696/226209836-48bf9b89-6a38-4fc2-b144-7ebbe0f64a04.png)

**Comment by jasmussen** [comment]
Since this issue, a new "Styles" item has been added:
<img width="1392" alt="Screenshot 2023-07-24 at 14 46 00" src="https://github.com/WordPress/gutenberg/assets/1204802/ddb9447b-88e1-4ffc-89ba-2327c6b1097d">

When you have no style variations, that item takes you directly to global styles. When you do have style variations, you can click the Edit icon to go there:

<img width="1392" alt="Screenshot 2023-07-24 at 14 46 05" src="https://github.com/WordPress/gutenberg/assets/1204802/54b69993-fa8d-4918-887f-c451371b1fdc">

I expect this to expand further, perhaps even entirely absorb the global styles sidebar, so it will evolve closer to what is suggested as time goes on. I'll still close this one as fixed for now. Let me know if that was in error, we can always reopen.
