### ISSUE TITLE
Converting a Columns block into a reusable block fails

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#4923]
### Steps

* Create a Columns block.
* Add some blocks to the columns.
* Convert to reusable block.

### Result

![image](https://user-images.githubusercontent.com/548849/35917997-7f6d52d8-0c10-11e8-8550-84bc3771e4bc.png)

**Comment by mcsf** [comment]
While a proper fix (#5010) is readied, #5044 disables conversion of Columns blocks (v2.2).

**Comment by aduth** [comment]
Noting that I started work on an [alternative approach](https://github.com/WordPress/gutenberg/tree/fix/reusable-blocks-pointers) which includes a total refactor of reusable blocks to behave as pointers to original blocks. The main issue is that since reusable blocks load after-the-fact, there needs to be reconciliation in blocks state to (a) receive those blocks and (b) not mark the post as dirty. This is tricky, and I'm considering whether it could be sensible to share the reducer logic itself between normal blocks and reusable blocks, but still track reusable blocks in a separate part of state (e.g. a reducer creator).

**Comment by aduth** [comment]
Closed by #5228
