### ISSUE TITLE
Cover block: consolidate settings into one panel and remove Settings

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#49241]
### Description

With the addition of split settings https://github.com/WordPress/gutenberg/issues/40204 followed by the work to consolidate the settings when there's only an Advanced section https://github.com/WordPress/gutenberg/issues/47463, the Cover block shouldn't show split options. Right now, it does. Adding to 6.2 board since this was introduced in this release cycle.

### Step-by-step reproduction instructions

1. Add a cover block.
2. Notice that the settings are split but the settings tab only shows advanced section. 

### Screenshots, screen recording, code snippet

<img width="1244" alt="Screen Shot 2023-03-21 at 10 35 33 AM" src="https://user-images.githubusercontent.com/26996883/226694817-ed45eca2-dc45-44ef-aaf6-2ed251bd2c54.png">

### Environment info

- WP 6.2 RC2
- No GB

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
@ndiego correctly noted that this is because when you add an image settings, the advanced sections is that used:

<img width="1282" alt="Screen Shot 2023-03-21 at 10 46 42 AM" src="https://user-images.githubusercontent.com/26996883/226697064-45d9a1ac-54ba-4928-99d6-22fcc8954fba.png">

I wonder if there's a way to grey out these options? Unclear but leaving open for now! @jasmussen in case you have more thoughts here.

**Comment by richtabor** [comment]
There are now layout controls under the block's settings tab in trunk (https://github.com/WordPress/gutenberg/pull/45326). There's no real feedback with them available as a placeholder state though (don't think it warrants adding/removing tabs based on placeholder state). 
 
<img width="1231" alt="CleanShot 2023-03-21 at 17 16 10" src="https://user-images.githubusercontent.com/1813435/226742676-8a3cdadb-3318-4487-855a-7fc0f9440ded.png">

When its supported.

**Comment by jasmussen** [comment]
Thanks for creating the issue, and for all the detailed followup. I initially reproduced this on 6.1 + the latest (as of a couple of days ago) Gutenberg plugin.

It was a bit of a quick observation, I will note — but my immediate instinct was: _something's not working, because the tabs inspector tabs are only supposed to show if there are settings panels in addition to the Advanced panel_.

With these followup notes, however, it's clear that cover has both layout, and when an image is used, "Image settings" (which on a small detail note we could just call "Image", perhaps even "Background").

Just confirming:
<img width="1392" alt="Screenshot 2023-03-22 at 08 47 43" src="https://user-images.githubusercontent.com/1204802/226835356-de1e2f08-27ac-4467-b420-a0cd70d14324.png">

<img width="1392" alt="Screenshot 2023-03-22 at 08 48 26" src="https://user-images.githubusercontent.com/1204802/226835365-920856d5-f0cf-4258-baea-5ba1cbbe75d2.png">

In that light, I'd happy to close this one, as the plugin experience should be correct again next release.

**Comment by annezazu** [comment]
What you show above seems to be correct. While the initial issue is what will ship with 6.2, this ensures iteration in the future via the plugin. Closing out!
