### ISSUE TITLE
List Block CSS changes padding of navigation with backgrounds

### ISSUE THREAD

**Issue by Trekky12** [WordPress/gutenberg#49445]
### Description

The list-block includes global CSS for ul and ol with background which includes unwanted padding to the navigation bar:

```
<style id='wp-block-list-inline-css'>
ol,ul{box-sizing:border-box}ol.has-background,ul.has-background{padding:1.25em 2.375em}
</style>
```

### Step-by-step reproduction instructions

1. Create FSE theme
2. Include navigation block and set a background color
3. Include a submenu with some items
4. Create a post with a list
5. See the wrong padding in the navigation (especially on submenus)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Trekky12** [comment]
Since the "Needs More Info" label is added I will add some screenshots:

Article without list, submenu has zero padding as defined:
![grafik](https://user-images.githubusercontent.com/3930110/228753339-3b841a4f-a970-4e79-a1c0-239972df3cdd.png)

Article with list, submenu has wrong padding:
![grafik](https://user-images.githubusercontent.com/3930110/228753402-94eb31cf-aa6b-4777-a1f2-aab03bfd4929.png)

**Comment by Trekky12** [comment]
I've already added more information..

**Comment by cuemarie** [comment]
During my testing of the issue reported here: https://github.com/Automattic/wp-calypso/issues/75908 I was able to replicate in my self-hosted site as well:

![Screen Capture on 2023-04-18 at 17-02-38](https://user-images.githubusercontent.com/27249804/232930355-1b412cd9-7a2f-4bcf-9065-64060c0d5c2b.gif)

As @Trekky12 identified, the problem seems to stem from the submenu with a background color picking up CSS padding rules intended for the List block:

![Screen Capture on 2023-04-18 at 17-03-55](https://user-images.githubusercontent.com/27249804/232930436-afe83008-16c2-4b8e-a26f-9eb9471f6346.gif)

Site Details:
- WordPress v6.2
- Gutenberg v15.5.1
- No other active plugins
- Theme: Twenty Twenty Three
- Firefox 112.0.1

**Comment by cuemarie** [comment]
Related: 

- https://github.com/WordPress/gutenberg/issues/50342

**Comment by cuemarie** [comment]
Created a more generalized report here: 

- https://github.com/WordPress/gutenberg/issues/50486

**Comment by Thelmachido** [comment]
This bug was also reported here: https://wordpress.org/support/topic/navigation-submenu-left-padding-introduced

**Comment by jordesign** [comment]
I'll close this issue in favour of the duplicate/larger issue mentioned above.
https://github.com/WordPress/gutenberg/issues/50486
