### ISSUE TITLE
Cannot read shortcode block text on themes with white text

### ISSUE THREAD

**Issue by tomjn** [WordPress/gutenberg#49482]
### Description

The shortcode block has a textbox with a white background.

On themes with white body text, the textbox has white text on a white background, which is unreadable:

### Step-by-step reproduction instructions

1. Activate a theme with a dark colour palette and white text
2. Try to type in a shortcode blocks input

### Screenshots, screen recording, code snippet

<img width="725" alt="Screenshot 2023-03-30 at 15 24 29" src="https://user-images.githubusercontent.com/58855/228868055-9f27efe0-a048-4c5b-80d1-83ef9adea029.png">

### Environment info

 - WP 6.2
 - Chrome
 - MacOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

I could not reproduce it with Twenty Twenty Three. The Shortcode block overrides the theme text color with black:

![placeholder](https://user-images.githubusercontent.com/54422211/229264080-fff7f28e-4ed5-40ec-9ba9-37277000f4f8.png)

--- 

And since the textarea inherits its color, the text should also appear in black:

![plain-text](https://user-images.githubusercontent.com/54422211/229264110-6d1a4f4b-9e62-4851-bcd6-a6483e5e7622.png)

---

From your screenshot, it appears that the style of this block is different from the default. Have you defined any CSS on the theme side that would override the text color of this block?

**Comment by tomjn** [comment]
Yes, there are styles that set basic inputs, but these should not be influencing block editor chrome, much in the same way that headings in placeholder components don't look like headings in the block list. i've raised a number of issues over the years and have been told to raise a bug if this happens in the past
