### ISSUE TITLE
[Block] Table - Border width 0 does not remove cell borders in Gutenberg 15.4

### ISSUE THREAD

**Issue by cuemarie** [WordPress/gutenberg#49594]
### Description

The border of the table block keeps showing even when the border settings is set to 0 PX.

### Step-by-step reproduction instructions

1. Insert a Table block in a post
2. Set the border value to zero PX under the Block Settings
3. Preview/view the post

### Screenshots, screen recording, code snippet

**Setup**

![Markup on 2023-04-04 at 15:35:02](https://user-images.githubusercontent.com/27249804/229939600-1a7050e0-37d6-4da4-bc22-d465bbcc84bd.png)

**Results**

![Markup on 2023-04-04 at 15:33:51](https://user-images.githubusercontent.com/27249804/229939644-859c6638-4fae-401e-9744-80f3c9e9e9ec.png)

---

By comparison, if I deactivate Gutenberg 15.4, the borders are hidden when set to 0px:
![Markup on 2023-04-04 at 15:48:51](https://user-images.githubusercontent.com/27249804/229939696-945aa912-7394-4c32-ad78-df6612cf7614.png)

![Markup on 2023-04-04 at 15:49:17](https://user-images.githubusercontent.com/27249804/229939704-60fbe4cf-7b92-48fd-99e5-6a708a21cb65.png)

### Environment info

- Originally reported here: https://github.com/Automattic/wp-calypso/issues/75198
- WordPress v6.2
- Gutenberg v15.4.0
- Theme: Twenty Twenty-Three

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
I can reproduce the issue.

The root cause seems to be that border is now serializing on all blocks in this format (when sides are linked):
```json
"border":{"top":{"style":"solid","width":"44px"},"right":{"style":"solid","width":"44px"},"bottom":{"style":"solid","width":"44px"},"left":{"style":"solid","width":"44px"}}
```

Usually it would be in this simpler format:
```json
"border":{"style":"solid","width":"44px"}
```

The first format causes the table block to apply the `has-individual-borders` classname, which makes only the `<table>` element show the applied border.

It usually does this to support the mode where you can apply different borders sizes to different sides (you'll also notice you can't remove border in this mode, with or without the Gutenberg plugin active):
![Screen Shot 2023-04-05 at 1 20 58 pm](https://user-images.githubusercontent.com/677833/229987964-8992beb0-d907-4163-a687-abfcfe64344a.png)

But now it does it all the time.

**Comment by aaronrobertshaw** [comment]
https://github.com/WordPress/gutenberg/pull/49603 addresses being able to remove borders using a simple zero-width border. There are some other trickier edge cases to deal with when it comes to separate borders per side. I'm currently working through those in a follow-up to https://github.com/WordPress/gutenberg/pull/49603.
