### ISSUE TITLE
Provide a way to check for specific block align support using hasBlockSupport()

### ISSUE THREAD

**Issue by CreativeDive** [WordPress/gutenberg#49633]
### Description

Hey,

I've noticed there is no way to check if a block type supports a specific block align like `left, right, center, wide, full`.

I would expect hasBlockSupport() should work like this:

`hasBlockSupport( blockName, 'align', 'wide' );`

or

`hasBlockSupport( blockName, 'align', ['wide','full'] );`

But it dosen't work. Is there an other way how I can check this? The only thing I can do is to check if the block type supports align at all:

`hasBlockSupport( blockName, 'align', false );`

### Step-by-step reproduction instructions

1. Start the browser console.
2. Enter `wp.blocks.hasBlockSupport( 'core/paragraph', 'align', 'wide' )`
3. The result is true, but it should be false.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by CreativeDive** [comment]
A possible workaround could be:

```javascript
const blockAlignSupport = getBlockSupport( blockName, 'align', false );       

if( blockAlignSupport ) {
    if( blockAlignSupport.includes( 'wide' ) ) {
        // ... wide is supported
    }
}
```

But in my opinion the hasBlockSupport() function is incomplete, because I can't check a supports feature array and value.

**Comment by t-hamano** [comment]
I think `hasBlockSupport()` selector checks if it defines that support and returns a boolean value.

> 1. Enter wp.blocks.hasBlockSupport( 'core/paragraph', 'align', 'wide' )
> 2. The result is true, but it should be false.

The third argument, `defaultSupports`, is the default boolean value if that support is not defined. Since the paragraph block does not define `align` in the `supports` property, and `'wide'` is a truthy value, so it would return true.

Personally, I think if you want to check if a particular value is included, you can use `getBlockSupport()` as you described.

**Comment by CreativeDive** [comment]
I don't think it's an ideal solution, nor is it intuitive. But it's too late to make changes to the `hasBlockSupport()` function. Therefore I close the issue.
