### ISSUE TITLE
Switching from text to heading preserves alignment

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#497]
I'm not sure if this is intended as the heading block does not currently have an alignment property. There is no way to change the alignment once it's a heading.

Similarly, formatting is preserved, which makes me wonder what should happen to it if the new block does not support formatting. Or should all text fields _always_ support formatting?

**Comment by joyously** [comment]
Do you mean text alignment? Or float?
Both should be options on headings.

**Comment by iseulde** [comment]
Text alignment. I'm unsure why headings should be allowed to float?

**Comment by joyously** [comment]
Oh yes, they should. I've used that on a site, so they can be in an excerpt next to the featured image.
Or just in the post itself next to an image. You can't know what the user might want to do, so don't restrict it.

**Comment by iseulde** [comment]
@joyously At the moment you can't float a heading with the visual editor in core, so I'm not sure why we should start adding it here. Aligning, on the other hand, is something else.

**Comment by joyously** [comment]
> At the moment you can't float a heading with the visual editor in core, so I'm not sure why we should start adding it here. Aligning, on the other hand, is something else.

Well, at the moment, the visual editor in core does not do gallery blocks or hero image blocks, etc. either, so should we not add them? One of the things the current editor is missing is the handling of float alignment for all blocks that are not images.

**Comment by jasmussen** [comment]
Good thoughts here. 

I think there's definitely a space for floated text blocks. If not for a version 2 of the editor, then at the very least for the customization focus later in the year. Probably good to start conservatively, though, because we can always add these features later if it becomes clear that we're missing them in a more layout strong editor.

To answer this specific tickets question, excellent observation Ella. I see two solutions:

1. add text-align controls to the heading
2. strip the text align in the conversion to a heading

I personally lean towards the latter being the most obvious, as converting a right-aligned paragraph to a heading seems like an edgecase where the dataloss is acceptable.

**Comment by jasmussen** [comment]
This seems to work in a fairly predictable way for me in master. 

As such, I'm closing this in favor of #751
