### ISSUE TITLE
Filter for modification of component panel or other way how to modify them

### ISSUE THREAD

**Issue by tkapler** [WordPress/gutenberg#49743]
## What problem does this address?
I want to change slightly content of excerpt component panel (i want to add a counter). It works by simply adding a script to the post.php page. But when I then click e.g. to editor, than the right panel switch from Post to Block and when I go back to Post panel, it is whole reinitialised so again without my changes. The same if i just minimise the panel with the up arrow and then maximise it again.

## What is your proposed solution?
It would be great, if there would be some filter/action or javascript event, so that i could add my scripts to any block, so it would start anytime that block is initialised. I have tried to search for it in documentation or source code (or trying to find any plugin that would do something with existing panels), but i wasn't able to find anything useful.

**Comment by t-hamano** [comment]
Hi @tkapler

The block editor is rendered in React. So if you add an element directly with JavaScript, it will disappear because it will be re-rendered when you switch panels.

Gutenberg provides [SlotFills](https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/slotfills/README.md), a mechanism to inject items in multiple locations, so if you want to add content to the Post panel, you can use the [PluginPostStatusInfo](https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/slotfills/plugin-post-status-info.md) slot. For example, if you run the following code in the browser console, the content will appear in the Post panel and should not disappear when you switch tabs.

```javascript
const el = wp.element.createElement;
const { registerPlugin } = wp.plugins;
const { PluginPostStatusInfo } = wp.editPost;

registerPlugin( 'my-plugin', {
	render: () => {
		return el(
			PluginPostStatusInfo,
			{},
			el(
				'p',
				{},
				'My Custom Post Information'
			)
		);
	},
} );
```

![Slot](https://user-images.githubusercontent.com/54422211/232229899-91e3fc7b-929a-4865-a3cf-cd1b4131ec16.png)


Using these mechanisms requires knowledge of JavaScript, React, etc., but we encourage you to give it a try.

**Comment by t-hamano** [comment]
@tkapler 

I would like to close this issue as I think it is not about a bug/enhancement, but a question about implementation using React.

If you have technical questions, you may want to post them in [the Q & A category of Discussions](https://github.com/WordPress/gutenberg/discussions/categories/q-a). If you want more specific use cases for the `PluginPostStatusInfo` I mentioned, you may also find [the WPdirectory search results](https://wpdirectory.net/search/01H0SPTSY2Y7XGPTVB3JGN9HHR) useful.
