### ISSUE TITLE
Top Toolbar not visible until selected when on mobile

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#49772]
### Description

Passing on a report from @nomad-skateboarding-dev where the top toolbar doesn't appear with WP 6.2 until clicked when on mobile web. I couldn't replicate this just by making my screen size smaller. As you noted in slack "this is constant".

### Step-by-step reproduction instructions

1. Open the Site Editor
2. Navigate to Templates or Template parts
3. Add a front page template
4. Notice that when you begin adding blocks to the template, the top toolbar is empty until selected.

### Screenshots, screen recording, code snippet

You can also watch him talk through[ this problem starting here](https://youtu.be/d2MHIUdZsL4?t=1096) or watch the recording below that I took of his video:

https://user-images.githubusercontent.com/26996883/231541742-312d43fc-9247-4757-acbc-4da03e426697.mov

### Environment info

- WP 6.2
- TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by nomad-skateboarding-dev** [comment]
Thank you sincerely @annezazu 🙏

**Comment by nomad-skateboarding-dev** [comment]
Thank you sincerely @annezazu 🙏

**Comment by colorful-tones** [comment]
I believe the complexity of this issue and possibly the testing instructions may have changed since WP 6.3 was released with the new Site Editor experience. 

> Step-by-step reproduction instructions
> 1. Open the Site Editor
> 2. Navigate to Templates or Template parts
> 3. Add a front page template
> 4. Notice that when you begin adding blocks to the template, the top toolbar is empty until selected.

Oddly these steps lead to a different bug on mobile. If you follow step #1 and #2 in the new Site Editor the + icon to 'Add New Template' is gone. So, continuing to step `3. Add a front page template` is impossible. I've logged an issue for that: https://github.com/WordPress/gutenberg/issues/53927

**Comment by colorful-tones** [comment]
I'm still unclear as to the steps to recreate this. I already covered one scenario to create a new Template, which led to an additional bug report (as noted in my previous comment above). 

Users are able to create a new template within the Editor (non-Site-Editor) by opening the sidebar (right-hand) and clicking on the Template name and clicking the + icon. 

We might need some more details to focus the bug here.

<img width="300" alt="Screenshot 2023-08-24 at 2 55 26 PM" src="https://github.com/WordPress/gutenberg/assets/405912/c2a94fe9-4f01-4e3b-97de-1d2c3af5479e">

**Comment by annezazu** [comment]
Going to close this out - let's reopen if folks can replicate.
