### ISSUE TITLE
Wordpress buttons block - font selection

### ISSUE THREAD

**Issue by mhbManchester** [WordPress/gutenberg#49869]
I've used the buttons block a few times and while it is useful it seems strange that it doesn't have a way of selecting a different font.  I wasted a a while trying to add CSS to change the font, without success, and many end users wouldn't event thy to do that.
Could this feature be added, as it would add greatly to the block's usability?

**Comment by richtabor** [comment]
If you're using a block theme, you should have support for it. Here's with the default theme, Twenty Twenty Three:

https://user-images.githubusercontent.com/1813435/232624718-a5572613-5ba8-4114-9437-2a07710b4cce.mp4

**Comment by mhbManchester** [comment]
Not on "Twenty twenty-one" (we are using a bespoke child theme of that) which is meant to be a block theme too.
![Screenshot at 2023-04-18 09-45-25](https://user-images.githubusercontent.com/84074458/232724498-aa7d501f-a043-44da-b26c-0cd345d4e5df.png)

**Comment by t-hamano** [comment]
In order to use the Font Family dropdown in the Typography panel, you need to define a variation of it in the `settings.typography.fontFamilies` property of `theme.json`. Currently, however, there is no way to define that variation in a classic theme that does not have a `theme.json`, such as Twenty Twenty One. I believe that is why that dropdown does not appear.

**Comment by richtabor** [comment]
Yes, my example is from Twenty Twenty Three.

**Comment by t-hamano** [comment]
Hi @mhbManchester,

As I mentioned in [this comment](https://github.com/WordPress/gutenberg/issues/49869#issuecomment-1514533652), I believe the font selection not showing up is due to a setting in `theme.json` and not a Gutenberg issue. I would like to close this issue, but if you have any questions, please feel free to re-open it at any time.
