### ISSUE TITLE
Custom Field: Loads Continuously when submitted.

### ISSUE THREAD

**Issue by SavPhill** [WordPress/gutenberg#49995]
## Description

https://wordpress.org/gutenberg/

On the Gutenberg site, the Custom Field toggle button in Preferences > Panels continuously reloads when    the Enable & Reload button is clicked.

There appears to be an Uncaught TypeError as shown in the screen pic below.

## Actual behaviour

The button loads continuously.
## Screenshots or screen recording (optional)

![image](https://user-images.githubusercontent.com/38789408/233699440-3adf37dd-070f-4897-a67a-7275fe6becc6.png)

## WordPress information
- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: 
- Operating system: 
- WordPress app version:

**Comment by dcalhoun** [comment]
Hey @SavPhill. 👋🏻 Thank you for the report. 

This issue does not appear related to the WordPress native mobile apps, so I removed the "Mobile App - i.e. Android or iOS" label. I imagine it was added if the "Bug report (Mobile)" [issue template](https://github.com/WordPress/gutenberg/issues/new/choose) was mistakenly used instead of "Bug report." 

In the future, if you are willing to fill out all the template details, that will help expedite the process of debugging reported issues. 🙇🏻 

It appears the meta box included in Gutenberg was removed in https://github.com/WordPress/gutenberg/pull/13449. So, the reported issue may be specific to the site environment or core WordPress version. Are you able to recreate this issue with specific versions of WordPress?

**Comment by SavPhill** [comment]
@dcalhoun Thank you for updating the correct labels. I believe I added the label by mistake by using the wrong template as suggested.

I can confirm I have tested in other local and live environments and the issue is not found, so I agree that it presents to be related to the environment.

**Comment by dcalhoun** [comment]
> I can confirm I have tested in other local and live environments and the issue is not found, so I agree that it presents to be related to the environment.

Thanks for confirming. If it is an environment issue, this report may be better suited in [Meta Trac](https://meta.trac.wordpress.org/newticket) or [WordPress/wporg-gutenberg](https://github.com/WordPress/wporg-gutenberg/issues). If a new issue is opened there, it may make sense to close this issue.

**Comment by SavPhill** [comment]
Closed as to new issue opened at wporg-gutenberg:

https://github.com/WordPress/wporg-gutenberg/issues/58
