### ISSUE TITLE
Update the add template menu

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#50134]
In the run up to the 6.2 release template descriptions were made more verbose given the available real estate in the new detail panels:

<img width="397" alt="Screenshot 2023-04-27 at 13 46 48" src="https://user-images.githubusercontent.com/846565/234866045-a94bddd5-9c5a-44c2-b1b3-0099ded225f0.png">

Consequently the add template menu became extremely long and unwieldy. As a short-term solution the descriptions were removed from the menu items and placed in a tooltip:

<img width="391" alt="Screenshot 2023-04-27 at 13 48 02" src="https://user-images.githubusercontent.com/846565/234866312-c2cce10f-e57a-4eb0-85b5-e134895c39b0.png">

But this is not an ideal solution. It would be good to explore alternative options.

**Comment by jameskoster** [comment]
Given the creation of many templates invokes a modal where where you choose the scope for that template, it might be good to embrace the modal UI for the entire flow:

<img width="1448" alt="Screenshot 2023-04-27 at 14 06 08" src="https://user-images.githubusercontent.com/846565/234870828-33b39f37-5ba5-4d0b-8a23-3612294d560c.png">


cc @WordPress/gutenberg-design

**Comment by jasmussen** [comment]
I think this looks good, and works better than the tooltips. The nice and big buttons make the creation act feel as substantial as it should be.

How do you feel about those borders? Do you think it could potentially work with the gray borders, but no borders and blue background on hover? Mainly we have to consider the 1.5px focus style. From the 3 steps in that modal it would also be nice to unify the style, e.g. the last one suddenly omits borders where the two first steps have them.

One last thing, I wonder if there's a way to have the modal keep the same size across all three steps, so it doesn't have to resize that much and make you lose your place. 

Nice work!

**Comment by jameskoster** [comment]
If we got rid of the borders we'd need to tweak the padding to get the alignment right, but that shouldn't be a problem. It would be nice to remove them to be consistent with other buttons like blocks in the Inserter.

Fixed dimensions for each step would be nice I agree! It's a bit tricky to balance given the contrast in grid contents, but something like this could work:

<img width="1594" alt="Screenshot 2023-04-27 at 15 14 16" src="https://user-images.githubusercontent.com/846565/234890143-f5db92cc-ff6d-4b93-9f9f-0288e56a8673.png">

I removed the icons too. They're not canonical and given our plans for the document title not all that helpful either ([more context](https://github.com/WordPress/gutenberg/pull/48052#issuecomment-1516099394)).

**Comment by jasmussen** [comment]
I actually meant remove the borders on hover, but keep the gray ones on resting state, and 1.5 blue on focus.

**Comment by jameskoster** [comment]
I kind of like removing them, to be consistent with Inserter buttons, etc.

**Comment by jasmussen** [comment]
It's mostly that "All Pages" big button in the center, which is just kind of hanging there in space. Besides with the gray borders, they'd still be consistent with the light-weight style variation buttons.

**Comment by paaljoachim** [comment]
The thing with the second image is that one clicks the + sign and associated modal/drop down which is connected with the same location is seen. If a modal can become a kind of hybrid drop down meaning one clicks somewhere and the modal shows up connected to the same location on the screen then that would be helpful.

I would in a sense call the following modals located in the same area one clicked to activate these.
These give a sense of connectedness/association with the initial click to open something. It reminds the user where the drop down was initially triggered.

![Screenshot 2023-04-30 at 18 46 11](https://user-images.githubusercontent.com/5323259/235365471-193c6987-0b2d-4077-b1ac-ab13badbe5c4.jpg)

![Click opens drop down](https://user-images.githubusercontent.com/5323259/235366048-98a4d5c8-7927-41ef-9651-7d395909b98f.jpg)


![Screenshot 2023-04-30 at 18 45 48](https://user-images.githubusercontent.com/5323259/235365466-af8de6e4-56b0-4d58-89a8-b7eb787ac4a1.jpg)

So let's work on connecting trigger with trigger result. Having a closeness where that is possible. As it strengthens the association of trigger and trigger result.

**Comment by jawomg** [comment]
#50089

**Comment by jawomg** [comment]
> The thing with the second image is that one clicks the + sign and associated modal/drop down which is connected with the same location is seen. If a modal can become a kind of hybrid drop down meaning one clicks somewhere and the modal shows up connected to the same location on the screen then that would be helpful.
> 
> I would in a sense call the following modals located in the same area one clicked to activate these. These give a sense of connectedness/association with the initial click to open something. It reminds the user where the drop down was initially triggered.
> 
> ![Screenshot 2023-04-30 at 18 46 11](https://user-images.githubusercontent.com/5323259/235365471-193c6987-0b2d-4077-b1ac-ab13badbe5c4.jpg)
> 
> ![Click opens drop down](https://user-images.githubusercontent.com/5323259/235366048-98a4d5c8-7927-41ef-9651-7d395909b98f.jpg)
> 
> ![Screenshot 2023-04-30 at 18 45 48](https://user-images.githubusercontent.com/5323259/235365466-af8de6e4-56b0-4d58-89a8-b7eb787ac4a1.jpg)
> 
> So let's work on connecting trigger with trigger result. Having a closeness where that is possible. As it strengthens the association of trigger and trigger result.

**Comment by tomxygen** [comment]
I was experimenting with the full site editor and stumbled upon an issue that doesn't make sense to me.
Let's say I have a blog where I publish two types of posts: book reviews and movie reviews. The two types of reviews are quite similar in their structure but require slightly different templates.
While experimenting with the site editor, the first thing I did was go to the site editor, then to templates, and clicked on "Single: Item post". I made the desired changes, saved it, and then did it again for the other type of review.
After that, I created a new review and noticed that I couldn't assign the review to the new templates I had created. It took me a while to figure out that I shouldn't choose "Single: Item post", but instead had to choose the Custom template, rename it, and then style it as desired.

It is not clear that when you select "Single: Item post", then select "for a specific item", then you can't extend that template to other posts later. I think it should be made more explicit.
Instead, it's clear that, when selecting "for all items" it applies to all the posts.

In my opinion, the best scenario would be to change the behavior of the "for a specific item" that allows to create a template that can be applied to other posts as well, when creating the new post. 
Otherwise the "for a specific one" should be explicitly stated that it won't be possible to apply to other items in the future.

Also it is not clear that "custom template" is the best option to create a template that can be applied to specific items.
Furthermore, when creating a custom template, I have to build the custom article (for example) from scratch, instead of having it already pre-made like with "Single: Item post".

And also, having the "duplicate" option to easily duplicate custom templates would be great when I need to create custom templates that have few differences from one another.

As an experienced WordPress user, it took me a while to figure this out because it is very counterintuitive.

**Comment by jameskoster** [comment]
> It's mostly that "All Pages" big button in the center, which is just kind of hanging there in space. 

Did you try the [PR](https://github.com/WordPress/gutenberg/pull/50143)?

In a single screenshot I agree this looks a bit off, but in practise I don't find it too bad. The big hover interactions the button footprint pretty clear. 

Perhaps there's another way to lay out these buttons? Stack instead of Row? 🤔 

@tomxygen that's good feedback, thanks. Perhaps when you create a new template for Single item: Post we should present three options:

1. For all posts
2. For a specific post
3. To be used by any post ad hoc (with better wording of course).

It's probably worth opening a new issue describing this problem if you have the time.

**Comment by jasmussen** [comment]
> In a single screenshot I agree this looks a bit off, but in practise I don't find it too bad. The big hover interactions the button footprint pretty clear.

I did try it, and it's a big improvement. I'm not opposed to shipping. But even with the big hover, this one sits in the air:

<img width="560" alt="Screenshot 2023-05-02 at 13 22 30" src="https://user-images.githubusercontent.com/1204802/235652961-2817a9ec-d9a4-474c-8795-63b493e1f994.png">

It's a bit easier with this list, but even there it isn't clear why the text of the items don't line up with the text above:

<img width="559" alt="Screenshot 2023-05-02 at 13 22 16" src="https://user-images.githubusercontent.com/1204802/235653032-6328e3fd-ef94-4c2a-a405-10e30288a4fb.png">

I thin I'm still leaning towards a decorative light gray border, even if that border is gone on hover.

**Comment by jameskoster** [comment]
Hah, I'm keen to avoid the borders if we can, they add noise that I don't really think we need. I do acknowledge the 'hanging' point though. Perhaps stacking them and tweaking the alignment would help. I'll try it in the PR.

**Comment by tomxygen** [comment]
> Perhaps when you create a new template for Single item: Post we should present three options:
> 
> 1. For all posts
> 2. For a specific post
> 3. To be used by any post ad hoc (with better wording of course).

@jameskoster That's a great idea and in my opinion it completely fixes the issue I'm trying to bring up.
However, the 2nd and 3rd options could be unified into a single one that says "For specific items". 
I've designed a simple mockup on Figma to unify the 2nd and 3rd options, and it compares current design and my new design.
My mockup is based on the Page template, however, currently in the site editor, when selecting the page template, it's not possible to select all pages or a specific page. It's automatically set for specific page.
I'm not entirely sure that unifying 2nd and 3rd is the right way, because it may be confusing and people may not realize that you can assign that template to a new page/article you're creating.

<img width="876" alt="Screenshot 2023-05-02 at 3 20 37 PM" src="https://user-images.githubusercontent.com/47855768/235678634-9c50a13c-f5c7-4be7-bf8e-2d1a29c96264.png">
<img width="824" alt="Screenshot 2023-05-02 at 2 49 30 PM" src="https://user-images.githubusercontent.com/47855768/235678693-8010f3be-2b01-49d9-9d9c-fe7d9a1b459d.png">

> It's probably worth opening a new issue describing this problem if you have the time.

I will open asap. Let me know what you think about this mockup first.
If it could work, I'll add it to the issue.

**Comment by jameskoster** [comment]
@tomxygen Looking at those screenshots I'm missing a way to create a `page-$slug` template. But I acknowledge it might be worth prioritising `$custom` templates instead. Let's discuss in a dedicated issue.

**Comment by SaxonF** [comment]
> it isn't clear why the text of the items don't line up with the text above

@jameskoster @jasmussen this also relates to the editor sidebar discussion and other places we use an item group menu.

It's pretty common to apply negative margin to menu items so text/content aligns with hover overlapping. 
 
https://user-images.githubusercontent.com/1072756/235823707-fdab4add-26e3-478b-bc43-b116af69177b.mp4

We already do this with focus states on some dropdown menus

<img width="345" alt="image" src="https://user-images.githubusercontent.com/1072756/235823582-8edb233f-9010-47fe-b6f3-e7d38557b874.png">

Re the add template. I still think there is an opportunity to create an experience which reduces the reliance on template descriptions, which without knowledge of the template hierarchy are still quite complex. e.g. `The Front Page template takes precedence over Home`. Can we just pick the right template for people depending on what they need? It might also make more sense if we will be pushing the idea of treating certain templates more like pages.

**Comment by jameskoster** [comment]
> I still think there is an opportunity to create an experience which reduces the reliance on template descriptions, which without knowledge of the template hierarchy are still quite complex

I agree. This is just a short term patch to address the tooltip issue.

**Comment by jasmussen** [comment]
Yep, we need the short term bandaid while still wrapping up the long term.

**Comment by jameskoster** [comment]
Part of this was addressed in https://github.com/WordPress/gutenberg/pull/50143. 

Replacing the popover menu with a modal remains to be done:

<img width="716" alt="Screenshot 2023-05-03 at 15 05 36" src="https://user-images.githubusercontent.com/846565/235939875-761aafe7-15d6-4ff9-9a5f-a7c6eaee2711.png">
