### ISSUE TITLE
Twenty Nineteen : The font colour of category lists in the product category lists block is not working in the backend or frontend.

### ISSUE THREAD

**Issue by aezazs-multidots** [WordPress/gutenberg#50249]
### Description

Add a product category list block to any post or page and change the colour of the category list text, and after that, the colour is not reflecting in the front-end and backend side.

### Step-by-step reproduction instructions

1. Activate Twenty Nineteen theme
2. Add a product category lists block to any post or page
3. Change the colour of category lists text

### Screenshots, screen recording, code snippet

Issue Video Link => https://share.cleanshot.com/4NkTQnYZZ4HT2mVQ8tGF

### Environment info

Wordpress Version: 6.2-beta3
Gutenberg: Version 15.2.0
Browser: Safari Version 16.2 (18614.3.7.1.5)
Device: MacBook Air (Ventura 13.1)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi, the color option is for plain text only, not for link color. 
Unfortunately link color options are not supported in classic themes.

There is an older issue for re-adding link colors to classic themes here: [41857](https://github.com/WordPress/gutenberg/issues/41857)
Because this problem is already reported, I will close this issue as a duplicate.
