### ISSUE TITLE
Twenty Twenty : The size of the headings is not changing in the product title block

### ISSUE THREAD

**Issue by aezazs-multidots** [WordPress/gutenberg#50245]
### Description

When the Twenty Twenty theme is active, we add the product title block to any post or page. And when we change the heading level of that title in the backend side, there is no change in the size from h1 to h5 headings. On selecting h6 heading level, the font becomes capital and the size of the font increases.

### Step-by-step reproduction instructions

1. Activate Twenty Twenty theme
2. Add a product title block to any post or page
3. Now change the heading level of that title

### Screenshots, screen recording, code snippet

Issue Video Link => https://share.cleanshot.com/xFPjWxzKdcbmHqzvK2jP

### Environment info

Wordpress Version: 6.2
Browser: Google Chrome Version 112.0.5615.137
Device: MacBook Air (Ventura 13.3)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by NidhiDhandhukiya** [comment]
I can able to reproduce this issue.
The reason behind this issue is there is no specific css written for h1 to h6 in Twenty Twenty theme.
Because of that we can't able to see any difference whenever any heading level is changed.

If we want to resolve this issue we need to add the css according to heading level same as Other theme like Twenty Twenty one.

**Comment by talldan** [comment]
@aezazs-multidots The product title block isn't part of Gutenberg, it's probably from a plugin? I'd recommend reaching out to the plugin developer.
