### ISSUE TITLE
[Block] Latest Posts - Excerpt Read More link replaced with unlinked bracketed elipsis on live site

### ISSUE THREAD

**Issue by cuemarie** [WordPress/gutenberg#50492]
### Description

With any FSE theme active, the **Latest Posts** block displays an unlinked `[...]` in place of the Excerpt "Read More" link on the live site.

### Step-by-step reproduction instructions

1. Activate an FSE theme such as TT3
2. In a page or post, add the **Latest Posts** block
3. Enable Post Content > Excerpts, reduce the number of characters enough to see "Read More" links appear in the editor.
4. Save and view site

The Live site shows `[...]` wherever the editor showed "Read More", and the link is removed.

### Screenshots, screen recording, code snippet

**Editor**

![Markup on 2023-05-09 at 16:03:42](https://github.com/WordPress/gutenberg/assets/27249804/6b8bd166-3b11-4185-8b64-0611ab300eca)

**Live Site**

![Markup on 2023-05-09 at 16:04:09](https://github.com/WordPress/gutenberg/assets/27249804/7a451fa0-6277-4ef2-bb7b-f65c4ebde002)

### Environment info

- WordPress 6.2
- Gutenberg 15.7.1
- Replicated on themes: Twenty Twenty Three, Twenty Twenty Two, Blank Canvas, Skatepark

Originally reported here: https://github.com/Automattic/wp-calypso/issues/76739

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ramonjd** [comment]
I'd class this as a bug as I'd expect the read more links to match.

I naively tried this code in the [latest-posts/index.php](https://github.com/WordPress/gutenberg/blob/4c1c15d99f218eda8fc66c17f3e2f91230576942/packages/block-library/src/latest-posts/index.php) and it works pretty well. 

```php
	$filter_latest_posts_excerpt_more = function( $more ) use ( $attributes ) {
		$use_excerpt = 'excerpt' === $attributes['displayPostContentRadio'];
		return $use_excerpt ? '<a href="' . esc_url( get_permalink() ) . '" rel="noopener noreferrer">' . __( 'Read more', 'gutenberg' ) . '</a>' : $more;
	};
```

I think we'd need to make sure there some explicit instruction from the latest block post since some themes might use `excerpt_more` filter to handle the `more` link displayed after a trimmed excerpt.

`'excerpt' === $attributes['displayPostContentRadio']` should be enough.

Possibly related: 
- https://github.com/WordPress/gutenberg/pull/22372

**Comment by annezazu** [comment]
I can replicate with GB 15.9.

**Comment by ramonjd** [comment]
Could folks test this PR out to see if it's a good approach?
- https://github.com/WordPress/gutenberg/pull/51190
