### ISSUE TITLE
Backspace does not delete quote, preformatted, verse... (inconsistent behaviour)

### ISSUE THREAD

**Issue by notnownikki** [WordPress/gutenberg#5057]
## Steps to Reproduce (for bugs)
1. Type a few paragraphs
2. Hold backspace, you can delete the content and blocks, cursor goes up the document
3. Insert two paragraphs, a preformatted block, then two paragraphs, type some content in each
4. Put the cursor in the bottom paragraph, hold backspace. It will stop at the preformatted block.

## Expected Behavior

Backspace behaviour should be consistent across these text blocks

**Comment by jasmussen** [comment]
Also relevant, https://github.com/WordPress/gutenberg/issues/3558

**Comment by designsimply** [comment]
Tested and confirmed that pressing backspace (or delete) from a paragraph block into a preformatted block lands the cursor at the beginning instead of the end of the content as expected and also gets stuck (e.g. cannot backspace from a preformatted block into a paragraph block).

<strong>Video:</strong> [51s](https://cloudup.com/c60_a6EOxqK)

![screen shot 2018-07-09 at mon jul 9 4 33 28 pm](https://user-images.githubusercontent.com/1119271/42479477-49dec9c8-8396-11e8-9b7d-113784a2bfc0.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=13891&action=edit running WordPress 4.9.7 and Gutenberg 3.2.0 using Firefox 61.0.1 on macOS 10.13.5.</sup>
