### ISSUE TITLE
Pasting inside of Paragraph Block breaks attributes

### ISSUE THREAD

**Issue by davidsword** [WordPress/gutenberg#5059]
Safari 11, wp 4.9.4, gb 2.1.0, gutenberg theme. Happens when no other plugins active.

Pasting (normal and `shift+opt+cmd+v` sanitized pastes too) inside of the Paragraph block after things like align:full and background color have been set, break the align/bg attributes.

1. Add Paragraph block
2. Set align to full width
3. Set bg to light gray
4. Leave the block, to another, then return
5. Paste in text 

I've had it not happen on a clean page when it's the only block. In my testing, when there's more than one block it always happens.

![a](https://user-images.githubusercontent.com/1996370/36223129-474dc384-1178-11e8-96db-603d86443059.gif)
 
And another on a clean page:

![take2](https://user-images.githubusercontent.com/1996370/36224226-d2f6b0a0-117b-11e8-910b-6bf4be45e9d9.gif)

**Comment by iseulde** [comment]
I think the solution here is the same as #6132.

**Comment by designsimply** [comment]
I tried testing without the step to set the block alignment (because I don't see it any more), and I wasn't able to reproduce the problem.

**Video:** [39s](https://cloudup.com/c2S69Q0WgkJ)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14031&action=edit running WordPress 4.9.7 and Gutenberg 3.3.0 using Firefox 61.0.1 on macOS 10.13.6.</sup>

@davidsword if you're still having trouble with this, could you reply and let me know what versions you're using now and also which theme you're testing with?
