### ISSUE TITLE
Quote block: Top padding added when selecting

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#50614]
### Description

When the quote block is selected, a top padding is added which makes it jump.

### Step-by-step reproduction instructions

1. Select the quote block

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/17861443/add792f0-5f3c-47ed-9658-59e0019ce61c

### Environment info

- WP 6.2
- GB 15.7.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
I am able to replicate it. I am going to add it to the [UX & Polish](https://github.com/orgs/WordPress/projects/96/views/2) project for consideration. 
![quote-select-padding](https://github.com/WordPress/gutenberg/assets/4832319/db3ab571-68fc-4e8c-aa22-9f5c985fc1c8)

**Comment by cbirdsong** [comment]
This may be able to be improved with [`overflow: clip` and/or `overflow-clip-margin`](https://kilianvalkhof.com/2022/css-html/do-you-know-about-overflow-clip/). Browser support is currently a mixed bag on those, but if it's an easy fix with those and a more complicated fix otherwise then it might be an acceptable tradeoff?

**Comment by t-hamano** [comment]
The problem stems from the fact that `overflow:hidden` is applied when multiple blocks are selected. And this problem seems to have been resolved in #50215.

I would like to close this issue, but if the issue remains, you are welcome to reopen it at any time.
