### ISSUE TITLE
Template and Template part revision history shows empty state

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#50675]
Using Gutenberg 15.8.0 RC1 and trying to test revision history, I noticed that what shows as revision history seems incorrect for a few reasons:
- The first revision shown lists the entire content of the template, without changes as "added" with the "removed" section blank. This matches this issue: https://github.com/WordPress/gutenberg/issues/49164
- The second revision is entirely empty, showing nothing on either screen.

https://github.com/WordPress/gutenberg/assets/26996883/92283c7a-66cf-45ae-a509-0ccf6bb9e3f5

The same thing happens with template parts. cc @ramonjd can you dive in here? Something seems very off.

**Comment by annezazu** [comment]
Noting that the further I go in making revisions, the more it seems to work and show revisions properly but these initial experiences are rough.

**Comment by ramonjd** [comment]
I'm not sure what's going on here 🤔 

cc @draganescu in case there was any movement on [Template and Template part revision history shows empty state](https://github.com/WordPress/gutenberg/issues/50675), particularly [this comment](https://github.com/WordPress/gutenberg/issues/49164#issuecomment-1513180864)

When I get a chance this week I'll have a look around 👍

**Comment by talldan** [comment]
> the first revision shown lists the entire content of the template, without changes as "added" with the "removed" section blank.

When the template part first exists it does so as a file provided by the theme that can have no revision history attached to it.

When a user makes a first modification of a template part, a template part post is created and effectively takes over responsibility from the file. I think that first revision is the contents of the file being copied into the post.

I'm not sure what the second one is.

I think this is what Andrei mentioned in the comment as well.

**Comment by ramonjd** [comment]
As @talldan already noted, the first time you edit a template a new `wp_template` custom post type entry is created in the database. This is not classed as a revision post type.


```mysql
mysql> select ID, post_title, post_parent, post_type from wp_posts where post_type = "wp_template" union select ID, post_title, post_parent, post_type from wp_posts where post_parent in (select ID from wp_posts where post_type = "wp_template");

+----+------------+-------------+-------------+

| ID | post_title | post_parent | post_type   |

+----+------------+-------------+-------------+

| 18 | Home       |           0 | wp_template |

+----+------------+-------------+-------------+

1 row in set (0.00 sec)
```

Making another change, we create the first official "revision"

```mysql
mysql> select ID, post_title, post_parent, post_type from wp_posts where post_type = "wp_template" union select ID, post_title, post_parent, post_type from wp_posts where post_parent in (select ID from wp_posts where post_type = "wp_template");

+----+------------+-------------+-------------+

| ID | post_title | post_parent | post_type   |

+----+------------+-------------+-------------+

| 18 | Home       |           0 | wp_template |

| 20 | Home       |          18 | revision    |

+----+------------+-------------+-------------+

2 rows in set (0.00 sec)
```

So I think we can only show the revisions where there are more than 2 (here there is only one), since the revisions API only returns revisions post types (and not the original wp_template).

This solves the issue of the mysterious second page I believe because the revisions UI must have at least two revisions to compare.

I have a PR that does exactly that and appears to mitigate the bad experience

- https://github.com/WordPress/gutenberg/pull/50762

Now all this seems a tad incongruent since, in the user's mind, I guess the first change is most likely considered to be a revision, with the original theme version the "initial state".

For reasons mentioned, the way templates are created in the database don't allow us to compare the theme's initial state.

As for the first blank page, I'm also seeing this on regular posts as well. 


https://github.com/WordPress/gutenberg/assets/6458278/f676f907-90a8-4ffa-8b4e-66d7648de664

**Comment by annezazu** [comment]
Thanks so much for the deep dive, Ramon. TIL! While not ideal, I think it makes sense to delay until there are two revisions to compare to prevent confusion.
