### ISSUE TITLE
Block pattern setup toolbar is wrongly aligned

### ISSUE THREAD

**Issue by Tropicalista** [WordPress/gutenberg#50683]
### Description

BlockPatternSetup is showing misaligned toolbar at bottom.

 This is due to wrong aboslute positioning and it make impossible to switch between carousel and grid mode.

### Step-by-step reproduction instructions

1. Download and install Formello or create a modal that use BlockPatternSetup component
2. Show modal and check toolbar at bottom

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi, can you add complete testing instructions? It is not clear what "Formello" is, or what exactly about the component that is incorrect. Perhaps include some screenshots of the alignment?

**Comment by carolinan** [comment]
I see that you have already been asked to add more instructions in the PR, that is fine too of course.

**Comment by jordesign** [comment]
The linked PR (https://github.com/WordPress/gutenberg/pull/50684) indicates that this is a behaviour seen in a third-party plugin which references an old experimental function (`__experimentalBlockPatternSetup`) which is no longer in use elsewhere.

The PR has also stalled for 2 months since that point.

As such - I'll close this issue - but that PR can continue if needed.
