### ISSUE TITLE
Navigation on Browse Mode: Remove existing editing functionality 

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#50698]
As part of https://github.com/WordPress/gutenberg/issues/50396, the first step is to remove some of the existing functionality from the Navigation List View in Browse Mode, specifically:

- [x] Remove the link control popup for custom links and unset links.
- [x] Remove add submenu option.
- [x] Move the behaviour that selects a page to the ellipsis menu

**Comment by getdave** [comment]
Working on this now

**Comment by getdave** [comment]
I have a PR in https://github.com/WordPress/gutenberg/pull/50788 which removes the main edit pieces.

> Move the behaviour that selects a page to the ellipsis menu

This part is not clear to me. If understand that if you click on a menu item it will currently go to a preview of that page in the Browse Mode. I understand we want to remove that functionality but if we do then what happens if you select a Nav item? Nothing? The issue is that it still needs to be selectable to allow for drag & drop so this feels unusual.

**Comment by jasmussen** [comment]
Just catching up here. I understand that we may be removing the “click to navigate to page” action from the navigation items. For context, initial efforts had the Navigation section act as both content access and basic menu management. With the recent addition of the Pages section, this is less necessary, and if we remove the drilldown from these items we also simplify some of the back button behavior.

I still think there can be value in the drilldowns in the navigation section, especially as each drilldown detail increases in value (such as clicking the blog, then changing posts per page), but it is also fine to omit this behavior if it simplifies the process going forward. We can always revisit.

**Comment by scruffian** [comment]
PR to move the navigate action to the ellipsis menu here: https://github.com/WordPress/gutenberg/pull/50843

**Comment by scruffian** [comment]
This has been done.
