### ISSUE TITLE
Chrome crashes after opening a category with hundreds of patterns from the pattern inserter.

### ISSUE THREAD

**Issue by miksansegundo** [WordPress/gutenberg#50695]
### Description

Chrome crashes after opening a category with 323 patterns from the pattern inserter.

The issue seems to happen because the component `<BlockPatternList>` loads [all patterns](https://github.com/WordPress/gutenberg/blob/2452a92dce0e2db2b8b58be3089e7c31e4f74b45/packages/block-editor/src/components/block-patterns-list/index.js#L138) in the background.

A solution could be loading only the pattern in the view using the hook `useInView` from [react-intersection-observer](https://www.npmjs.com/package/react-intersection-observer).

### Step-by-step reproduction instructions

1. Register hundreds of patterns in a category
2. Open the editor's pattern inserter
3. Click on the category with hundreds of patterns
4. Wait for a few minutes until Chrome crashes

### Screenshots, screen recording, code snippet

<video src="https://github.com/Automattic/wp-calypso/assets/1881481/24ca7db1-cd84-4644-8e3b-bc26dac33ab4.mp4" />

### Environment info

- Gutenberg v15.7.1, WordPress 6.2, Storia theme
- Chrome 
- Desktop MacBook Pro with macOS 13.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by kevin940726** [comment]
c.c. @youknowriad This is similar to the topic we briefly discussed. `useAsyncList` might not be sufficient after all?

**Comment by youknowriad** [comment]
Do we know the reason for this crash? useAsyncList is for performance issues (not blocking the page), this might be something else memory... some pattern is doing wrong things?

**Comment by kevin940726** [comment]
I think it's a combination of multiple issues: performance and memory leaks (https://github.com/WordPress/gutenberg/issues/53382). I haven't identified most of them yet but I found something interesting.

IIRC, chrome devtools by default enable the "Disable cache" check in the network tab, which causes the same requests not to be cached when the devtools is open. Each `<BlockPreview>` loads the same set of stylesheets and scripts and iframes share the same request pool with the main frame. This causes the experience to degrade significantly when loading many patterns when the devtools is open.

One solution to that is to fetch the stylesheets once and cache and share them via [constructable stylesheets](https://web.dev/constructable-stylesheets/). This technique also increases performance for other iframes.

Another possible enhancement is to replace iframes with shadow doms entirely for block previews, since iframes have more overhead than shadow doms. However, this has many edge cases that need to be considered separately.

**Comment by aaronrobertshaw** [comment]
Quick update. A PR [fixing iframe memory leaks](https://github.com/WordPress/gutenberg/pull/53406) has already been merged and a second PR [adding pagination to the patterns](https://github.com/WordPress/gutenberg/pull/54007) in the inserter should land soon. Combined, these should address the crash and performance issues reported here.

**Comment by glendaviesnz** [comment]
This should have been resolved by https://github.com/WordPress/gutenberg/pull/54007 - please reopen if you still experience this issue on Gutenberg 16.7 or WP 6.4.
