### ISSUE TITLE
Pattern & Media List Items: Use consistent admin focus style

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#50757]
Let's update the focus state style applied to Inserter list items, so that it is in line with what we employ throughout the experience. 

### Current
<img width="350" alt="current" src="https://github.com/WordPress/gutenberg/assets/1813435/40778398-37ba-431a-873f-008b3e17e4a4">

### Expected
<img width="350" alt="expected" src="https://github.com/WordPress/gutenberg/assets/1813435/f1ecaf9d-68b2-44c9-938a-cca2d245366a">

**Comment by richtabor** [comment]
Could very well be related: 

<img width="279" alt="CleanShot 2023-05-18 at 14 58 41" src="https://github.com/WordPress/gutenberg/assets/1813435/7c72382c-0749-49fe-ba3c-45f3b02f973f">

**Comment by mikachan** [comment]
I believe this should be fixed with https://github.com/WordPress/gutenberg/pull/50819. Please re-open if not!

**Comment by juanfra** [comment]
From what I see in #50819 we're adding changes to the hover state of the icon. I believe those changes are not fixing what was initially reported in this issue, which concerns the focus style.

By inspecting the elements, I see that the styles for the image under "current" is using the border property for the focus style whereas we use an inset box-shadow in other places. It'll likely be fixed by adjusting the focus style for the "item group" component.

**Comment by mikachan** [comment]
Good spot, @juanfra. I've opened another PR to address this:  https://github.com/WordPress/gutenberg/pull/51576

**Comment by juanfra** [comment]
Thanks for working on this, Sarah 😄
