### ISSUE TITLE
[Block] Template Part: 'Replace' option missing from List View > Options menu if block not selected

### ISSUE THREAD

**Issue by cuemarie** [WordPress/gutenberg#50928]
### Description

In List View, you can select the `...` "Options for Group" menu of any block without selecting that block.  When you do this for a Template Part, the "Replace" option is missing, and instead "Create Reusable Block" is shown in it's place.

### Step-by-step reproduction instructions

1. Activate Twenty Twenty Three or another FSE theme
2. Open the editor and edit a template containing a template part
3. Open List View
4. Without selecting a template part, hover over it to find the `...` menu and select that
5. Look for "Replace XYZ" between _Detach blocks from template part_ and _Move to_ - you should see "Create Reusable Block" there
6. Next, select the template part, and open that menu again - now you'll see "Replace XYZ"

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/27249804/5cb3ce67-8e8d-4bf7-8bfe-52d894c4951d

### Environment info

- WordPress 6.2.2 
- Gutenberg v15.8.1
- Theme: Twenty Twenty-Three v1.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
@andrewserong might this be something you can work on as part of List View improvements?

**Comment by andrewserong** [comment]
Oh, thanks for the ping, Anne! I think we've run into similar issues previously, I'll look into it 🙂

**Comment by andrewserong** [comment]
After a little more digging, I think this one might not be all that simple to change, as the logic currently exists in the `TemplatePartEdit` component as part of the block itself, so I believe the `Replace <BlockTitle />` option only gets rendered when the block is selected. Also, the `TemplatePartSelectionModal` is rendered as part of the block itself, so it all appears to be quite tied into the block code, as opposed to the list view itself.

I might just ping @talldan in case Dan has any further insights, since we were looking at things related to this a while back.

From my perspective, the effort to impact of this bug appears to not be a very good balance to prioritise it right now, as there are still quite a few other easier to implement UX improvements to do for the list view and other areas.

Let me know if you think it's higher priority to have it fixed for 6.3, though.

**Comment by annezazu** [comment]
I agree with your read there. Thanks for digging in.
