### ISSUE TITLE
Empty Post Content in Pages doesn't always contain initial template

### ISSUE THREAD

**Issue by tellthemachines** [WordPress/gutenberg#50984]
### Description

#50623 added a template with a single Paragraph to Post Content block so that the block is always visible (via the paragraph's placeholder prompt) when opening an empty page in the site editor. This works fine if the site is set to display a static page as the homepage, but if homepage is set to display latest posts, the template only displays for the first page loaded in the site editor.

### Step-by-step reproduction instructions

1. Make sure site is set to display latest posts in homepage (under Reading settings);
2. Create a couple of pages, at least one of which should have no content;
3. Go to site editor > Pages
4. Click on the page without content first, check that the paragraph placeholder inside it is visible;
5. Go back to Pages view and reload;
6. Now click on another page first, and then go back and click on the empty page;
7. Verify that placeholder is not visible this time around.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by youknowriad** [comment]
This is what I've found so far: there's something wrong in the state but I can't tell yet where the original thing that creates this issue is:

At some point in the lifecycle of the block-editor "reducer" we end up with a block that:
 - has no children in "state.blocks.order[id]" 
 - has children in "state.blocks.tree['controlled||' + id].innerBlocks"

The second one is supposed to be a denormalization, so there's something wrong in the reducer at some point but I can't pinpoint. Some action is clearning the former without clearing the latter which end up with a wrong value returned by `getBlocks( id )`.

**Comment by youknowriad** [comment]
I can't reproduce this anymore.
