### ISSUE TITLE
Top toolbar: Refine the icons on the right

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#51006]
A few recent changes happened to the top toolbar:

* A new device icon indicator in the preview dropdown
* Moving the "Switch to draft" button into the inspector for published posts
* Showing the "Saved" state indicator also for published posts. 
* A new "View post" icon button

The buttons are a mix of colors and styles, and could use a little cleaning up:

<img width="652" alt="Toolbar buttons, before" src="https://github.com/WordPress/gutenberg/assets/1204802/e0259fa7-22a3-4d00-b00c-714137470998">

Here's a design iteration that accounts for both post editor and site editors:

| Before  | After |
| ------------- | ------------- |
| <img width="652" alt="Toolbar buttons, before" src="https://github.com/WordPress/gutenberg/assets/1204802/766fb3b7-3f32-4674-9d5f-f02fbf6b6304"> | <img width="652" alt="Toolbar buttons, after" src="https://github.com/WordPress/gutenberg/assets/1204802/e905d966-faa4-40f7-9e08-67f0d37c1d9d"> |

Main changes:

* Same color for all icon buttons
* Leveraging an icon-button for the device preview button
* Can show the "View post" always, just link to the preview before publishing.

---

Post updated Jun 6.

**Comment by jasmussen** [comment]
CC: @WordPress/gutenberg-design

**Comment by jameskoster** [comment]
Nice, this area is long over-due some tidy up!

A couple of notes, none of which need to hold up progression here:

> Leveraging an icon-button for the device preview button

Looks good, but without the "Preview" label the "Preview in a new tab" begins to feel a little out of place. I wonder if that action can move to the command palette down the road.

> Same color for all icon buttons

Makes sense. It's a shame the "Save draft" button will still be blue, but that element probably warrants a dedicated exploration. 

Finally: might it be good to consider re-positioning the save button as a part of this work? It feels very oddly placed here:

<img width="547" alt="Screenshot 2023-05-26 at 14 39 28" src="https://github.com/WordPress/gutenberg/assets/846565/b7a78089-2134-4fea-b9d8-82917dec6e23">

**Comment by jasmussen** [comment]
> Looks good, but without the "Preview" label the "Preview in a new tab" begins to feel a little out of place. I wonder if that action can move to the command palette down the road.

Could we just always show the "View post" button, and have it act as preview if unpublished?

> Makes sense. It's a shame the "Save draft" button will still be blue, but that element probably warrants a dedicated exploration.

> Finally: might it be good to consider re-positioning the save button as a part of this work? It feels very oddly placed here:

Controversial thought: what if it was all the way on the right? I'd keep that separate, but hey, could work?

**Comment by richtabor** [comment]
> Controversial thought: what if it was all the way on the right? I'd keep that separate, but hey, could work?

Perhaps. Maybe just the vertical ellipsis is on the right?

**Comment by jasmussen** [comment]
With always "view post" button, and save/publish on the right:

<img width="1472" alt="Top toolbar with save on the right" src="https://github.com/WordPress/gutenberg/assets/1204802/7a3fad03-c88c-45fa-a351-d5ff534330ef">

**Comment by jameskoster** [comment]
> Could we just always show the "View post" button, and have it act as preview if unpublished?

Yep, I think that could work for the post editor. We'll need to add the equivalent button to the Site Editor, perhaps as a part of https://github.com/WordPress/gutenberg/issues/50378?

**Comment by jasmussen** [comment]
Tentatively updated the post and added the dev label.

**Comment by jameskoster** [comment]
Are the proposed changes for the post editor, site editor, or both? 

The Site Editor may require a little more thought as the draft concept doesn't really exist there yet.

**Comment by jasmussen** [comment]
It was actually both site editor and post editor, but I forgot to include the site editor, and perhaps I should omit the document title as that's just distracting from the rest. Here's a clearer comparison:

| Before  | After |
| ------------- | ------------- |
| <img width="652" alt="Toolbar buttons, before" src="https://github.com/WordPress/gutenberg/assets/1204802/766fb3b7-3f32-4674-9d5f-f02fbf6b6304"> | <img width="652" alt="Toolbar buttons, after" src="https://github.com/WordPress/gutenberg/assets/1204802/e905d966-faa4-40f7-9e08-67f0d37c1d9d"> |

**Comment by jameskoster** [comment]
Bingo!

**Comment by juanfra** [comment]
I was taking a look at this one, and I have a doubt.

> Leveraging an icon-button for the device preview button

^ Does it mean that we want to remove the dropdown for the preview/view?

**Comment by jasmussen** [comment]
No, that would still drop down and show the devices plus labels, the dropdown would just be opened by an icon button.

But maybe the "Preview in new tab" option was extracted into the "View post" button instead, making the dropdown devices-only.

**Comment by juanfra** [comment]
Perfect, thanks for the clarification :)

**Comment by juanfra** [comment]
I had some time to work on this today, and I found a small constraint with moving the "Preview in new tab" to the "View" button.

While in the draft post-editing context it _could_ make sense to have something like that (because eventually, the behavior of the two buttons would be the same), when a post/page is already published, the value of the "preview" is to view how the changes (not saved) could look. Whereas the "view" always opens the public content (what's saved). So we would have two functionalities competing in one button.

https://github.com/WordPress/gutenberg/assets/252415/287da0d1-ffb4-483d-895b-5f8761153dfa

I'm unsure if it is an ideal UX to have a button behaving differently in two contexts. Plus, having the "View" button previewing can be confusing as well (It'll be next to a "Preview" dropdown). And, as these two would be competing, we would have to decide on which one to leave out. As a user, I would expect to be able to still preview changes without saving.

What I would propose is to:

- Have the "View" button disabled (or could also be hidden, as it is now) when in draft-context.
- Enabling the "View" button once the post/page is published.
- Keep the "Preview in new tab" under the preview dropdown, so that we keep the functionality available.

https://github.com/WordPress/gutenberg/assets/252415/c92c27c2-1432-4fcf-bb81-65c070657cdb

The other thing I was thinking is if, in favor of consistency, we could think of having a "View site" button in the site editor. That could maybe be a different discussion (could be contextual when editing pages, or just general to view the site).

**Comment by jasmussen** [comment]
> when a post/page is already published, the value of the "preview" is to view how the changes (not saved) could look. Whereas the "view" always opens the public content (what's saved). So we would have two functionalities competing in one button.

That's a great clarification. Yes indeed. To me that actually suggests keeping the existing trunk behavior, which is have the preview in new tab continue to exist in the dropdown, and then add a new "View site" button once published. 

Can we try that as a starting point? 

Another option which I wouldn't start with, is to keep the view post button and have it be a preview until published, then a view link, but _also_ keep the "preview in new tab" button in the dropdown. Not quite as elegant, but a potential plan B.
