### ISSUE TITLE
Block tooltip when dragging media into the canvas

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#51010]
When a user drags a media item into the canvas or a gallery block, the tooltips says "1 block". When there is only one block, we should just say the block type. In this case, it should say "Image" with the image block icon.

https://github.com/WordPress/gutenberg/assets/548849/2afe05db-0be1-48e7-a957-4eddfb571a3e

Side note, it's weird that we do multiline for this single string of text. It would fit perfectly fine in a single line.

**Comment by juanfra** [comment]
I've been looking at this one, and apparently, the draggable chip is not receiving the block title or icon.

I see that, [it either displays the icon or the label](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-draggable/draggable-chip.js#L26). The two lines are only showing when it's a two-word string, because of the current CSS wrapping properties, we could adjust that to have the width set to `max-content`.

For all other draggable items, we're just showing the block icon, so I think that in favor of consistency, we _could maybe_ only show the block icon, and keep the text for "Pattern" (or other cases where the block title or icon are not received).

I'm putting something together that will also fix it for the "Videos" section or any other type of block we use in the inserter draggable; it looks like this:

https://github.com/WordPress/gutenberg/assets/252415/62f492fc-4825-4ad5-aea0-1f2157b7ea66

**Comment by mtias** [comment]
@juanfra looks good, thanks for looking into it!
