### ISSUE TITLE
Experiment: Add zoom and animation toggle for image lightbox

### ISSUE THREAD

**Issue by artemiomorales** [WordPress/gutenberg#51055]
## What problem does this address?

*This builds on the image lightbox experiment using the Interactivity API, introduced in #50373, and is related to #49972 and #50029.*

Some users prefer the effect of a zoom animation for the lightbox over a fade animation. Ideally, users would be able to select the animation they prefer.

## What is your proposed solution?

Add support for a zoom animation to the lightbox, as well as a toggle for the behaviors UI, allowing users to select their preference when the lightbox is enabled for a particular block.

Initial explorations by @SantosGuillamot in the videos below and in [this branch](https://github.com/artemiomorales/gutenberg/tree/experiment/add-zoom-animation).

These explorations are originally from a [comment](https://github.com/WordPress/gutenberg/pull/50373#issuecomment-1554455731) in the initial PR.

### Desktop

https://github.com/WordPress/gutenberg/assets/5360536/f20f7b21-35ef-41d1-834d-b311a4a9e75b

### Mobile

https://github.com/WordPress/gutenberg/assets/5360536/03948141-1a9d-46a2-8c5b-235f1be4ba41

### Explanation

https://github.com/WordPress/gutenberg/assets/5360536/e1481d6c-675e-4f9d-9ce4-2f42cebb892f

**Comment by pablohoneyhoney** [comment]
I don't think we need the close X icon on the top right. `Esc` or click outside closes it. The only caveat is tab Esc leaves the image selected with a ring (in Medium). 

I wonder, based on the videos, if the transition can be sped up a bit more.

**Comment by pablohoneyhoney** [comment]
I also wonder if you all considered a very slight zoom on hover so it'd anticipate the behavior.

**Comment by artemiomorales** [comment]
@pablohoneyhoney Thanks for the ideas! Here are some thoughts:

> I wonder, based on the videos, if the transition can be sped up a bit more.
> I also wonder if you all considered a very slight zoom on hover so it'd anticipate the behavior.

These sound worth exploring — will give these a shot.

> I don't think we need the close X icon on the top right. 

For this one, we recently received [accessibility feedback](https://github.com/WordPress/gutenberg/issues/51126#issuecomment-1573820375) on the close button and that it is important to have it:

>Back when I was visually impaired and not totally blind, I always used close buttons on popups. That was before I had to learn every keyboard shortcut under the sun and clicking outside was always tricky due to magnification programs I used such as ZoomText. There is no reason to not have a visible close button. Why design in this project is so against it is totally beyond me but sometimes there is a reason the basics are the basics.

Will keep all of this in mind as this feature gets implemented.

**Comment by pablohoneyhoney** [comment]
It’s not a popup or a dialog with functionality though, you can literally hit the keyboard anywhere and it should "close", no shortcut needed.

I quoted "close" because it's not even an opening behavior  (which puts you in a new context with further actions), but a slight zooming behavior (same context, not critical for understanding any further text or functional information about the object itself), it’s not “closing” anything. 

In that vein, maybe “lightbox” (traditionally understood as a state hosting further actions like thumbnails, image info, carousel…) is not a clear name for this behavior anyways, I feel it has been misunderstood.

**Comment by andrewhayward** [comment]
It would be great if we could [predicate this on `prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia), so that we can respect any explicit ([and often important](https://www.a11yproject.com/posts/understanding-vestibular-disorders/)) choices made by end users.

Essentially, give content authors a choice as to whether they want a `fade` or `zoom` effect, but allow content consumers to override that. After all, "ideally users would be able to select the animation they prefer"!
