### ISSUE TITLE
Pattern Nesting Linked

### ISSUE THREAD

**Issue by mike-henderson** [WordPress/gutenberg#51108]
### Description

When nesting patterns with `wp:pattern` multiple instances of the same pattern are content linked. Also multiple formatting buttons are present depending on block (Align, Bold, Link, etc...).

The nested pattern should not be linked and a user should be able to edit the content independently. 

This is especially useful for creating design systems to keep the pattern directory dry.

### Step-by-step reproduction instructions

1. Install default WordPress
2. Create `card.php` in pattern directory
3. Create`card-group.php` in pattern directory
4. Create new page
5. Add *Card Group* pattern
6. Try to edit Heading Block
7. Observe Heading is linked in all instances of "card", multiple formatting buttons are present.

### Screenshots, screen recording, code snippet

Pattern code for card and card-group to be placed in pattern directory.
https://gist.github.com/mike-henderson/86c37d63399ca94f000de22f6fcb4301

<img width="1337" alt="Screenshot 2023-05-30 at 1 35 40 PM" src="https://github.com/WordPress/gutenberg/assets/78349/0e1a0297-6b7d-4878-9e19-8d5e64527a2c">

### Environment info

- WordPress 6.2.2
- Twenty Twenty-Three
- Gutenberg not installed

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
@mike-henderson Thanks for reporting. This was previously reported and should be fixed in the Gutenberg plugin (in the upcoming version 15.9) - https://github.com/WordPress/gutenberg/pull/50629. The fix will make its way across to WordPress 6.3 when that's released.

I'll close the issue, but if you can still reproduce as of Gutenberg 15.9 feel free to drop a comment here or make a new issue.
