### ISSUE TITLE
Apply text color selection to link color

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#51147]
The "Link" color control is not surfaced within a block's Colors (as it's not common use case). 

To improve discoverability, and improve the experience of coloring text _and_ links—a common scenario— it would be nice if a selected text color was also applied to the link color (thus rendering the "Link" control too). 

So when you change the text color, and the link color matches the exact value, the link color should adapt as well. If I've removed the link color, or changed it, then those changes should remain. 

### Visual 

<img width="375" alt="CleanShot 2023-05-31 at 23 25 27" src="https://github.com/WordPress/gutenberg/assets/1813435/d96a2750-9e33-461a-ab5a-2986f69fa68e">

**Comment by bph** [comment]
This totally necessary! I discovered that it doesn't when [testing footnotes and I changed the paragrph color](https://github.com/WordPress/gutenberg/issues/51895). I closed the issue because it's right now by design to not change the link color when text color is changed, and it would have been a duplicated of this issue. I hope we can make it a priority to implement @richtabor suggestion, if not for 6.3 but for 6.4
