### ISSUE TITLE
Query Pagination: Remove unwanted bottom margins from links

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#51299]
### Description

It's minor, but I remove it in every theme I work on. The bottom margins `0.5em` on the block's links seem unnecessary, creating misalignment. Can we remove them?

![Screenshot 2023-06-07 at 15 57 22](https://github.com/WordPress/gutenberg/assets/908665/3d6d9339-2fa6-4d9d-a808-099b3b9b600d)

![Screenshot 2023-06-07 at 15 57 34](https://github.com/WordPress/gutenberg/assets/908665/be8cc23b-3446-4cf8-8f35-270ca97d62e7)

![Screenshot 2023-06-07 at 15 57 40](https://github.com/WordPress/gutenberg/assets/908665/8fa6ec2d-06ae-4e15-8ca9-936a772ad94d)

### Step-by-step reproduction instructions

1. Go to Editor
2. Add a query pagination block
3. See the bottom margin added to the elements in the block.

### Environment info

- WP 6.2.2
- Gutenberg trunk
- Chrome, Mac

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by aurooba** [comment]
Good note, @iamtakashi! I believe the margin is there to deal with the scenario where those different elements are get really close to one another. Perhaps instead of an arbitrary `0.5em`, we could take advantage of the `blockGap` property instead? 🤔

**Comment by iamtakashi** [comment]
@aurooba Thanks for sharing your thought.

Whatever comes after the pagination block already has the top margin equivalent to the `blockGap`. But because of the unwanted bottom margin, the gap is bigger than how it should be. (Notice the gap between the orange(top margin on the image block) and the link in the pagination block.)

![Screenshot 2023-06-07 at 17 10 41](https://github.com/WordPress/gutenberg/assets/908665/6f6f8d58-1d9f-421d-b6da-5df74214831d)

It feels safe to remove the bottom margin though I wonder if anyone knows the intention.

**Comment by aurooba** [comment]
Ah yes, I see what you're saying. For some reason I thought that the `blockGap` wasn't set to apply on the inner pagination blocks, but upon looking at it again, I can see that it is. I agree with you, the bottom margin can likely be removed from the inner pagination blocks. 

Since `blockGap` didn't always exist, it's possible that the this margin was added before and then just got missed when `blockGap` was introduced.

For those folks who have `blockGap` disabled, do you think it would be a reasonable assumption that there would be no margin at all or in those cases should this margin still exist?

**Comment by iamtakashi** [comment]
> Since blockGap didn't always exist, it's possible that the this margin was added before and then just got missed when blockGap was introduced.

That's what I guess too.

> For those folks who have blockGap disabled, do you think it would be a reasonable assumption that there would be no margin at all or in those cases should this margin still exist?

That's a good question. Unlike a `p` or `figure` elements, it doesn't have margins from the user agent stylesheet, and it could bump to other blocks in some cases when the `blockGap` is disabled.

If Global Styles allows controlling the margins for the block, it'd be easier to remove it. Would that be a better solution?

**Comment by iamtakashi** [comment]
The bottom margins are still there, and it's getting harder to get rid of it. See the screenshot; they are not vertically in the middle.

![CleanShot 2024-05-29 at 16 23 45@2x](https://github.com/WordPress/gutenberg/assets/908665/a4844fbe-052e-4e26-b6ca-c7ab0f20a3db)

There is no margin control for the block in Global Styles.

I can't get rid of it in the theme.json. For example, this doesn't work.
```
"core/query-pagination-previous": {
	"spacing": {
		"margin": {
			"bottom": "0"
		}
	}
}
```

Adding a custom CSS doesn't work either.
![CleanShot 2024-05-29 at 17 12 05@2x](https://github.com/WordPress/gutenberg/assets/908665/121d630c-5617-4d05-a606-7726b988a49c)

![CleanShot 2024-05-29 at 17 08 45@2x](https://github.com/WordPress/gutenberg/assets/908665/af43f5b0-e046-4e05-a4f0-1f761f526c37)

I don't know why the blocks need the bottom margin. Can we just remove it from the previous page, the page numbers, and the next page blocks?

**Comment by tellthemachines** [comment]
Those `.5em` margins are coming from the [block library styles](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/query-pagination/style.scss#L3) and they're way too specific. I'm not sure what "blocks default margin" the comment is referring to or it it's still an issue, but would be worth reducing the specificity of those rules in any case.

**Comment by t-hamano** [comment]
Because the Query Pagination block is flex, the `0.5em` gap will be applied even if the theme doesn't support `blockGap`. Therefore, even if we delete the margins, there will always be `0.5em` of space between blocks within the Query Pagination block.

I simply removed all of these margins ([here](https://github.com/WordPress/gutenberg/blob/ffcf1ce5bd31ded7995e5c3698726b1c60f512e3/packages/block-library/src/query-pagination/style.scss#L3-L15) and [here](https://github.com/WordPress/gutenberg/blob/ffcf1ce5bd31ded7995e5c3698726b1c60f512e3/packages/block-library/src/query-pagination/editor.scss#L17-L34)) and tested it with a theme that doesn't support `blockGap`, and there didn't seem to be any problems:

![362581265-89091e8c-7477-493c-8f20-37b275eae971](https://github.com/user-attachments/assets/df26bd85-cb7f-4ef5-9781-8a5624c6b13f)

**Comment by tjcafferkey** [comment]
I have a draft PR for this here https://github.com/WordPress/gutenberg/pull/64874 but there remains a specificity issue which I've commented [here](https://github.com/WordPress/gutenberg/pull/64874#issuecomment-2317102436) if anyone's any suggestions.
