### ISSUE TITLE
Site Editor → Page Details: Link 'Last modified' detail to revisions

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#51343]
Follow-up to https://github.com/WordPress/gutenberg/issues/50390.

Here's the Page details panel in the site editor:

<img width="280" alt="Screenshot 2023-06-08 at 14 27 59" src="https://github.com/WordPress/gutenberg/assets/846565/76967de1-392a-4a24-8c98-a61d13fe4558">

The 'Last modified' detail could be more useful if it linked to revisions, as it does in the Styles panel:

<img width="684" alt="Screenshot 2023-06-08 at 14 31 34" src="https://github.com/WordPress/gutenberg/assets/846565/92ee13de-49a9-48f0-af52-bb9882e68f48">

The revisions page in wp-admin includes a "Go to editor" link:

<img width="397" alt="Screenshot 2023-06-08 at 14 32 44" src="https://github.com/WordPress/gutenberg/assets/846565/e5cd61d5-5633-4737-95fc-9bf9af94879b">

Ideally that link can be updated to conditionally return you to the correct view.

- [x] Update "Last modified" detail in Page panel to link to revisions
- [ ] Update "Go to editor" link on Revisions page so that it returns you to the site editor

**Comment by ndiego** [comment]
@jameskoster is this safe to punt to 6.4, or is this being actively worked on? Just trying to tidy up the 6.3 Board 😅

**Comment by jameskoster** [comment]
Fine to punt 👍

**Comment by jameskoster** [comment]
@ramonjd Thanks for adding the revisions link but I don't think we can quite close this issue yet as the second part ("Update 'Go to editor' link on Revisions page so that it returns you to the site editor") is not implemented.

**Comment by ramonjd** [comment]
> Thanks for adding the revisions link but I don't think we can quite close this issue yet as the second part ("Update 'Go to editor' link on Revisions page so that it returns you to the site editor") is not implemented

No worries. The issue was probably auto-closed by the PR merged. 

I thought the link would be best left for another PR as it will involve some PHP changes, and potential Core patches.

**Comment by ramonjd** [comment]
> I thought the link would be best left for another PR as it will involve some PHP changes, and potential Core patches.

I've been investigating this, and am a bit unsure how to proceed. So I'll post my thoughts first 😄 

The return to post links on the revisions page is generated from a template, unique to each post type object.

Currently, [admin/revision.php](https://github.com/ramonjd/wordpress-develop/blob/trunk/src/wp-admin/revision.php#L110) builds the link by calling [get_edit_post_link()](https://github.com/ramonjd/wordpress-develop/blob/trunk/src/wp-includes/link-template.php#L1453), which uses the link template from [page_object->_edit_link](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/post.php#L56).

For most post types, including pages and posts, the `_edit_link_` template looks something like this: `post.php?post=%d`.

`get_edit_post_link()` replaces the placeholder `%d` with the correct post id to build the edit post link.

Now we want to that template to vary depending on the origin of the referring URL. That means, if we're coming from the Site Editor, the return template should be something similar to what the [wp_template post object uses](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/post.php#L336), which is `site-editor.php?postType=%s&postId=%d&canvas=edit`.

I see a few challenges: 

1. the revisions page does not know where the revision is coming from, that is Post Editor vs Site Editor, but we could use some sort of`$_GET` query param on `revisions.php` to solve that. E.g., let's call it `editor`: `revision.php?revision=150&editor=site`
2. Whether we grab the query param on the revision page and pass it to `get_edit_post_link` (thereby changing the function signature), or modify `get_edit_post_link` to do the lot internally, we'd still have to build the link accordingly to some pattern. 
3. Where would we store that pattern? `_edit_link_` is taken. Maybe a new property on the post object? `_edit_site_link` or something. 

I'm not sure if any of this is a good idea. 🤷🏻 

In the plugin it can be done I think without great fuss using the [get_edit_post_link filter](https://developer.wordpress.org/reference/functions/get_edit_post_link/). With it we can return whatever we want. 

```php
function gutenberg_update_get_edit_post_link_page_from_site_editor( $link, $post_id ) {
	$post = get_post( $post_id );

	if ( 'page' === $post->post_type && 'revision' === get_current_screen()->base && isset( $_GET['editor'] ) ) {
		if ( 'site' === sanitize_text_field( $_GET['editor'] ) ) {
			$post_edit_link = 'site-editor.php?' . build_query(
					array(
						'postType' => '%s',
						'postId'   => '%s',
						'canvas'   => 'edit',
					)
				);
			return admin_url( sprintf( $post_edit_link, $post->post_type, $post_id ) );;
		}
	}

	return $link;
}
add_filter( 'get_edit_post_link', 'gutenberg_update_get_edit_post_link_page_from_site_editor', 10, 2 );
```

We would just have to come up with migration approach for Core. 

cc @draganescu if he has time since he worked on https://core.trac.wordpress.org/ticket/57709

**Comment by jameskoster** [comment]
@ramonjd possibly a dumb idea, but could the 'Go to editor' link behave like the browser back button when there is an internal referrer?

**Comment by ramonjd** [comment]
> but could the 'Go to editor' link behave like the browser back button when there is an internal referrer?

Very good question! That crossed my mind, but we'd also want to be able to build the link from wherever we are (and from wherever we've come). 

`get_edit_post_link()`, the function that builds these links, is used in a bunch of places and I think the main purpose is to specifically fetch the edit link, regardless of the referrer.

**Comment by jameskoster** [comment]
I suppose we can close this after all since it's a core issue. Feel free to re-open if you prefer.

**Comment by ramonjd** [comment]
> I suppose we can close this after all since it's a core issue. Feel free to re-open if you prefer.

Thanks! I'll make a note to create a trac issue. Hopefully folks will contribute some interesting suggestions as to how we can build this into core.

**Comment by ramonjd** [comment]
Trac ticket: https://core.trac.wordpress.org/ticket/59419
