### ISSUE TITLE
Dimension control: Spacing sizes should be displayed as slider instead of dropdown

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#51618]
## What problem does this address?
Gutenberg 16 introduces the new dimension controls, which in theory are good. 

However, what was a slider has changed to a dropdown.
For my theme I have defined purposely defined 8 spacing sizes, because in 15.9 this was the magic number to still have a slider, instead of the dropdown. Slides are much better and a faster way to select spacing sizes. 16.0 seem to have changed this number to 7, which I disapprove.

**GB 15.9 - Sliders:**
<img width="270" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/ca035dc8-0731-4303-b6ed-bb41b03dbf4c">

**GB 16.0 Dropdowns:**
<img width="278" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/454d0dae-a593-4849-9064-721ede049f8f">

Ironically, the heading block still uses sliders in 16.0 - which proves that having enough space for a slider is not an issue:
<img width="274" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/8d64bba4-cde4-4605-9ee4-e06c21ce070e">

## What is your proposed solution?
There is no value in changing the default number from spacing size from 7 to 8. So, please change it back :)

**Comment by aaronrobertshaw** [comment]
Thank you for taking the time to create this issue @hanneslsm 👍 

To my knowledge, there haven't been any changes as to when the spacing control displays as a select dropdown vs the segmented range control.

The magic number was 8 sizes if you included the `0` size that gets added by default, otherwise the magic number really was 7 custom sizing preset values.

The [original PR](https://github.com/WordPress/gutenberg/pull/42173) that added the spacing sizes control also indicates this with its testing instructions to check that setting the `spacingScale.steps` value to `> 7` results in the select list.

> In core or theme theme.json increase settings.spacing.spacingScale.steps to a value > 7 and check that segmented range is replaced with a select list

In that PR's code changes you can see where the [complete spacing sizes list is collected](https://github.com/WordPress/gutenberg/pull/42173/files#diff-17de057c2ae9a23adfffa3d8436dcfb1502bfa1e2412ffa61cadc662d202477fR28-R31) (including the zero value option) and where the [check for displaying the range control](https://github.com/WordPress/gutenberg/pull/42173/files#diff-66f5b15872a5b66944a30e88368f768aaca229d035a45884336c09de3f5c08d3R44) or not occurs.

After the [recent revamp](https://github.com/WordPress/gutenberg/pull/50660) of that spacing control in 16.0, you can find that same [collection of size options](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/spacing-sizes-control/hooks/use-spacing-sizes.js#L12-L15) and [check to display the range control](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/spacing-sizes-control/input-controls/spacing-input-control.js#L60) here in the latest code on trunk.

Testing 16.0 works as advertised for me. It displays 7 custom spacing presets as the range control and adding an extra one triggers the custom select list.

Given the point at which this spacing control switches from a range control to a select list hasn't changed, I think we should close this issue. If you face any further problems, it would be great if you could submit another issue along with your theme.json config for spacing. 

Thank you again for the detailed issue! 🙇

**Comment by hanneslsm** [comment]
@aaronrobertshaw  Wow, this is what I call an answer! 
I'll dig into the code, the links you provided are very helpful. Thank you so much!
