### ISSUE TITLE
Main inserter opens and closes immediately when Link popover is open

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#51646]
### Description

When a Link popover is open, clicking the + button in the editor top bar opens the Main inserter but the inserter closes immediately and unexpectedly. While users can always click the + button again, I'm not sure the sudden appearing and disappearing of the inserter is the best user experience.

Animated GIF to better illustrate:

![opens-closes](https://github.com/WordPress/gutenberg/assets/1682452/0b36b6a0-d0cf-4491-acaf-2c668f91c783)

I've been able to reproduce this behavior all the way back til WordPress 5.5. In WordPress 5.4 the inserter stays open. Although I guess many things have changed in the meantime, I'm going to mark this as a regression.

### Step-by-step reproduction instructions

- Go to the post editor.
- Select some text in a Paragraph block.
- Press Cmd (or Control on Windows) + K, to open the Link popover.
- Keep the Link popover open.
- Click the + button in the top bar to open the main inserter.
- Observe the inserter opens and suddenly closes.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
This is due to focus handler conflict. When the Link format popover is closed, using <kbd>Esc</kbd> or `focus-outside`, it will return focus to the selected text value. The Inerter popover interprets this as `focus-outside` and closes itself.

I've two possible solutions and would appreciate your expertise in picking the correct one.

1. Only return focus to the selected text value when the Popover is closed using the <kbd>Esc</kbd> key.
2. Don't return focus to the selected text value via Popover.onClose callback at all.

**Comment by afercia** [comment]
@Mamaduka thanks for your feedback. I think option 1 would be best. We should make sure that focus is returned to the selected text at least when using the keyboard.
