### ISSUE TITLE
Block appender requires a second click to open when the main Inserter is visible

### ISSUE THREAD

**Issue by Mamaduka** [WordPress/gutenberg#51678]
Extracted from "Allowed Blocks Setting on InnerBlocks" e2e tests. See #51677.

Block appender and in-between inserter require a second click to open when the main Inserter (in the sidebar) is visible. I expect the main inserter to be closed and the canvas appender to open.

## Reproduction steps.
* Open a post or page.
* Click on the empty paragraph block.
* Confirm that the canvas appender is visible.
* Open the main block inserter from the top toolbar.
* Click on the canvas appender.

## Screencast

https://github.com/WordPress/gutenberg/assets/240569/5b9f50c6-6498-4a0f-b255-31ca7cc4105b

**Comment by t-hamano** [comment]
I have confirmed that all blocks with click events also have this problem.

My guess is that this problem is caused by the following:

- The click event is fired when the mouse button is actually _released_.
- When the main inserter panel is open, simply _press_ the mouse key outside of that panel to close it
- The disappearance of the main panel shifts the position of the clicked element to the left in the block editor.
- Release the mouse key.
- The mouse cursor is no longer over the clicked element, so no click event occurs.

Therefore, after pressing the mouse cursor outside of the main inserter panel, holding down the mouse key and moving the cursor over the clicked element, and releasing the mouse key, the original click event will be triggered.

https://github.com/WordPress/gutenberg/assets/54422211/e3910f70-a3de-4554-b7ce-309473c75c94

**Comment by skorasaurus** [comment]
possibly related to https://github.com/WordPress/gutenberg/issues/35575

**Comment by Mamaduka** [comment]
I can no longer reproduce this issue on the trunk.

## Screenshot

https://github.com/user-attachments/assets/359b78d0-1a65-419f-83d5-5cbe1d8147ce
