### ISSUE TITLE
Top Toolbar: Refine icons and handle document title

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#51711]
When the top toolbar option is selected and you select a block, the document title in the site editor awkwardly overlaid. It should be hidden when a block is selected:

<img width="1472" alt="Responsive scheme" src="https://github.com/WordPress/gutenberg/assets/1204802/511ce6a7-941e-456f-9aa2-96beb515106b">

Note also that in this mode to enable the extra space necessary, the mockups here hide the Tools selector. 

Additionally, the expand/collapse icons have been updated to double-chevrons, where we can use these:

<img width="443" alt="Screenshot 2023-06-23 at 12 45 48" src="https://github.com/WordPress/gutenberg/assets/1204802/01149a48-3809-4449-8472-07cd16bbf123">

---

<details><summary>Initial issue</summary>

## What problem does this address?
With the changes in https://github.com/WordPress/gutenberg/issues/40450, the top toolbar can now become very large, to the point where it overlaps the command center:

<img width="1057" alt="Screenshot 2023-06-20 at 16 55 30" src="https://github.com/WordPress/gutenberg/assets/275961/a9b15664-e009-47d7-8f57-e61e9e80d91c">

## What is your proposed solution?
One option worth exploring is having items moving into/out of the ellipsis menu in the toolbar, as more/less space is available. This would require nested toolbars:

<img width="1054" alt="Screenshot 2023-06-20 at 17 00 08" src="https://github.com/WordPress/gutenberg/assets/275961/0c98f1cd-a201-4813-bc26-8e6051a5bcb3">

</details>

**Comment by jasmussen** [comment]
I would call this a bug. When the top toolbar option is selected and you select a block, the document title in the site editor is not meant to be visible. While collapsing tools can be a feature to explore separately, the immediate issue to fix is to address so that the document title is hidden when a block is selected in top toolbar mode. Here's a grid of the correct behavior:

<img width="1472" alt="Responsive scheme" src="https://github.com/WordPress/gutenberg/assets/1204802/511ce6a7-941e-456f-9aa2-96beb515106b">

Note also that we can hide the tool selector in top toolbar mode. 

Note the two updated icons, double chevron left:

```
<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" style="enable-background:new 0 0 24 24" viewBox="0 0 24 24"><path d="m12.6 7-1.1-1L6 12l5.5 6 1.1-1L8 12l4.6-5zm4 0-1.1-1-5.5 6 5.5 6 1.1-1-4.6-5 4.6-5z" style="fill-rule:evenodd;clip-rule:evenodd;fill:#1e1e1e"/></svg>
```


double chevron right:

```
<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" style="enable-background:new 0 0 24 24" viewBox="0 0 24 24"><path d="m12.5 6-1.1 1 4.5 5-4.5 5 1.1 1 5.5-6-5.5-6zm-4 0L7.4 7l4.5 5-4.5 5 1.1 1 5.5-6-5.5-6z" style="fill-rule:evenodd;clip-rule:evenodd;fill:#1e1e1e"/></svg>
```

**Comment by jasmussen** [comment]
Oh, it looks like we might already have some icons we can use here:

<img width="443" alt="Screenshot 2023-06-23 at 12 45 48" src="https://github.com/WordPress/gutenberg/assets/1204802/01149a48-3809-4449-8472-07cd16bbf123">

**Comment by annezazu** [comment]
Adding this to the triage board of 6.3 for consideration.
