### ISSUE TITLE
Convert to blocks adds unordered and ordered list

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#5172]
After converting a really long [post](http://nosolosoftware.com/essays/gestion-de-proyectos-de-software-libre/) (here's the [source](https://github.com/WordPress/gutenberg/files/1527889/post.html.txt) in case you want to replicate), some of the lists included both UL and OL tags.

## Before

![lists3-before](https://user-images.githubusercontent.com/583546/36472924-6fe1cbb2-16f3-11e8-9095-f4b6d35df9d9.png)

## After

![lists3-after](https://user-images.githubusercontent.com/583546/36472936-75621ae2-16f3-11e8-9a82-5c92e275e314.png)

FWIW, the majority worked flawlessly, it's only a couple that didn't work. The source contains really bad formatted HTML originally, so it's a wonder that Gutenberg can work with this at all. I'm just leaving it here in case it's useful as an extreme real-world use case for parsing.

Feel free to close it.

**Comment by nosolosw** [comment]
@aduth this is the follow-up issue that I mentioned at https://github.com/WordPress/gutenberg/issues/3799

**Comment by designsimply** [comment]
I tested this by copying the source of the http://nosolosoftware.com/essays/gestion-de-proyectos-de-software-libre/ post ([gist](https://gist.github.com/designsimply/0d560a078f622d7981ef1f728abd28ca)) and pasted it into the Gutenberg editor and found the following:

After pressing cmd+v to paste, I saw the following warning in Firefox:
> A web page is slowing down your browser. What would you like to do? [Stop It] [Wait]

![screen shot 2018-07-03 at tue jul 3 4 57 54 pm](https://user-images.githubusercontent.com/1119271/42248514-294ae762-7ee3-11e8-8b85-d58fc9ce48bb.png)

Leading space caused the first block to be code instead of paragraph:

![screen shot 2018-07-03 at tue jul 3 5 02 38 pm](https://user-images.githubusercontent.com/1119271/42248522-3a7f9f0a-7ee3-11e8-8ff8-614f9d526471.png)

Lists that appeared to be bullets became numbered—this may make sense given that the unordered list was nested inside an ordered list (but it's worth noting that the browser appears to parse the HTML differently).

![screen shot 2018-07-03 at tue jul 3 5 18 32 pm](https://user-images.githubusercontent.com/1119271/42248912-6651a9f0-7ee5-11e8-9b2c-00f418f08c0d.png)

A list with several nested ordered lists became a mix of numbered and bulleted.

![screen shot 2018-07-03 at tue jul 3 5 21 15 pm](https://user-images.githubusercontent.com/1119271/42248955-9db5417c-7ee5-11e8-9672-962ec0c8183c.png)

Successive lists with one item each only retain the first list item.

![screen shot 2018-07-03 at tue jul 3 6 20 38 pm](https://user-images.githubusercontent.com/1119271/42250906-8216446e-7ef1-11e8-83b0-ff66752c0114.png)

<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=13869&action=edit running WordPress 4.9.6 and Gutenberg 3.1.1 using Firefox 61.0 on macOS 10.13.5.</sup>

**Comment by designsimply** [comment]
> Successive lists with one item each only retain the first list item.

Moved to https://github.com/WordPress/gutenberg/issues/7702.

**Comment by designsimply** [comment]
Closing this issue because the source HTML from the original issue is not valid (as mentioned) and because the original issue says "feel free to close." 🙂

Sample HTML from the post:

```
<ol>
<ol>
<ol>
<ol>
<ul>
<li><a title="http://www.gnu.org/licenses/licenses.html" href="http://www.gnu.org/licenses/licenses.html" rel="nofollow">Licencias de software libre</a>, Free Software Foundation</li>
<li><a title="http://www.opensource.org/licenses" href="http://www.opensource.org/licenses" rel="nofollow">Licencias de software libre</a>, Open Source Initiative</li>
<li><a title="http://law.bepress.com/expresso/eps/773/" href="http://law.bepress.com/expresso/eps/773/" rel="nofollow">Copyright and Open Source Software Licensing</a>, de Sau Sheong Chang</li>
<li><a title="http://itmanagement.earthweb.com/osrc/article.php/12068_3803101_1/Bruce-Perens-How-Many-Open-Source-Licenses-Do-You-Need.htm" href="http://itmanagement.earthweb.com/osrc/article.php/12068_3803101_1/Bruce-Perens-How-Many-Open-Source-Licenses-Do-You-Need.htm" rel="nofollow">How many Open Source licenses do you need?</a>, Bruce Perens</li>
<li><a title="http://www.sanchez-crespo.com/archivo/software-libre/EstudioGPLv3.pdf/view" href="http://www.sanchez-crespo.com/archivo/software-libre/EstudioGPLv3.pdf/view" rel="nofollow">Estudio sobre la licencia GPL v3 y otras licencias open source</a>, Sánchez Crespo abogados y consultores</li>
</ul>
</ol>
</ol>
</ol>
</ol>
```

Note: Element ol not allowed as child of element ol in this context
