### ISSUE TITLE
Load font assets dynamically in the editor's iframe when the global settings are modified

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#51764]
### Description

If you update the theme JSON data modified client side using `useGlobalSettings` hook in the editor's Iframe without reloading the page, the font presets are loaded on the editor's iframe correctly, but the assets linked in the font presets are not. If I reload the page, the assets added client side are loaded as expected. /

I think the font assets should be automatically loaded if you update the settings.

### Step-by-step reproduction instructions

1. add font families to `typography.fontFamilies` global settings using the `useGlobalSettings` hook.
2. Observe that the new font families assets are not loaded in the editor iframe. 
3. Reload the page and observe that now the font assets are loaded  in the iframe.

### Environment info

- Gutenberg trunk
- WordPress  6.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ellatrix** [comment]
How is it done currently for other globals styles? Cc @oandregal

**Comment by ellatrix** [comment]
What exactly are these assets?

**Comment by oandregal** [comment]
@matiasbenedetto What I hear is that the font face definition provided via global styles is not updated upon client changes. This is, the `wp-fonts-local` stylesheet is not updated and only contains the old definitions:

![image](https://github.com/WordPress/gutenberg/assets/583546/bbc88a62-7cf7-4013-b3fe-9701cd64a41c)

Is this what you mean?

I don't have much context about how font assets are loaded in the editors, though I searched around and this is what I learned: by searching for `wp-fonts-local` ID I only found this [PHP code](https://github.com/WordPress/gutenberg/blob/53f44224d404c48be29cdcefdcbedbbedfa3d9cd/lib/experimental/fonts/class-wp-font-face.php#L222). This code is responsible for creating the stylesheet with the font faces declared via `theme.json`. However, I could not find anything similar for the client. That's what you need: the same code, in the client, so that the font face declarations work like any other style dependent on theme.json data: they are [updated upon changes in the theme.json data](https://github.com/WordPress/gutenberg/blob/53f44224d404c48be29cdcefdcbedbbedfa3d9cd/packages/edit-site/src/components/global-styles-renderer/index.js#L38) store in the client settings. Is this helpful?

**Comment by ellatrix** [comment]
See also #52767, and #52888 for another proposal.

**Comment by vcanales** [comment]
A work-around sort of proposal, that gets the font files loaded in the iframe at the same time that they're loaded into the parent container: https://github.com/WordPress/gutenberg/pull/54334

**Comment by mikachan** [comment]
Closing this as fixed by https://github.com/WordPress/gutenberg/pull/54334.
