### ISSUE TITLE
Extended Settings appears at the top of the mobile sidebar

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#5177]
When opening the sidebar on mobile, the Extended Settings wrapper appears at the top, blocking the close button and essentially forcing you to do a refresh to close the sidebar.

Gutenberg master 3f43e32, chrome on iOS and OSX.

<img width="385" alt="screen shot 2018-02-21 at 14 33 35" src="https://user-images.githubusercontent.com/6073772/36482635-431be9d4-1714-11e8-96c0-6f09b0d9089f.png">

**Comment by timnolte** [comment]
Just experienced this on mobile web editing today. This issue actually is experienced when in Portrait editing mode vs Landscape. When I turned my phone to rotate the screen to Landscape then navigation properly showed up in order to close the Extended Settings.

Portrait
----
![screenshot_20180311-171450](https://user-images.githubusercontent.com/4312062/37263203-67446c4c-257d-11e8-8cd4-34e2cfa97d78.png)

Landscape
----
![screenshot_20180311-171455](https://user-images.githubusercontent.com/4312062/37263202-6730f91e-257d-11e8-9de9-bdc7b79a5506.png)

**Comment by youknowriad** [comment]
There has been some iterations on this. Is this still an issue?

**Comment by timnolte** [comment]
@youknowriad I believe this issue is resolved. I've been using the mobile web interface recently and it was working in portrait mode. Thanks!
