### ISSUE TITLE
Page List: Change the Edit modal text

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#51789]
## What problem does this address?
The text for the modal when you try to edit the items in a page list block looks like this:

<img width="560" alt="Screenshot 2023-06-22 at 12 12 05" src="https://github.com/WordPress/gutenberg/assets/275961/f608a5dd-7418-4e83-b588-aecdab66dc87">

There are several problems with this:
- We shouldn't use the word "Menu"
- It doesn't make as much sense when a page list block is also part of a navigation block with other items.

I suggest we change it to:

> Edit these blocks
>These blocks are automatically kept in sync with pages on your site. Would you like to unsync them so you can edit them independently?

**Comment by richtabor** [comment]
> Edit these blocks

I don't know that most folks would equate menu items as blocks like we do. I think I like the idea of "unsyncing" instead of editing even. What about:

#### Edit page list
This page list is synced with the published pages on your site. Unsync the page list to add, delete, or reorder pages yourself.

Cancel / Unsync
