### ISSUE TITLE
Consider removing "Settings" and "Styles" from the Site Editor More Menu

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#51861]
Was resolving https://github.com/WordPress/gutenberg/issues/51859 when I noticed an inconsistency between the post and site editors. There is not a Plugins > Settings control within the post editor menu; so do we need one in the Site Editor? If not, do we need the "Styles" control as well? 

Both the Styles and Settings sidebars can be invoked from the editor header; seems a bit redundant to have these controls in both places. 

<img width="277" alt="CleanShot 2023-06-23 at 12 21 50" src="https://github.com/WordPress/gutenberg/assets/1813435/59893646-e4e3-4a40-ab98-333036989fdf">

**Comment by jasmussen** [comment]
Great question, there's some arcane lore context to this one so let me dive in. 

The answer is, _there is_ a plugins menu in the post editor, but only for sidebar plugins. Shown here, the Jetpack plugin:

![plugins](https://github.com/WordPress/gutenberg/assets/1204802/a5b7baf8-dfb1-4979-a9d1-598b05ca1259)

The menu item exists because you can _un-pin_ the sidebar plugin, but still get it back. In principle it should exist and behave the same in the site editor, i.e. it should exist when you have a sidebar plugin installed, such as CBT. 

However your issue surfaces a couple of inconsistencies. For one, CBT can't be unpinned. To me that suggests the pinning feature is optional, it shouldn't be optional, and every sidebar plugins should have a star here in the header:

<img width="443" alt="Screenshot 2023-06-26 at 09 10 44" src="https://github.com/WordPress/gutenberg/assets/1204802/3b566399-0265-4237-aae2-00e0ae7b3ac0">

<img width="349" alt="Screenshot 2023-06-26 at 09 10 50" src="https://github.com/WordPress/gutenberg/assets/1204802/6b786dab-028a-4d31-b2ae-62d4f3416d27">

Secondly, it seems the plugins section exists even when you _don't_ have any plugins installed. That doesn't seem useful. I wonder if it's because global styles is considered a sidebar?

**Comment by richtabor** [comment]
> I wonder if it's because global styles is considered a sidebar?

I think that's it exactly. And you shouldn't be able to unpin it anyhow. 

> For one, CBT can't be unpinned. 

CBT should emulate the unpin/pin functionality.

In short, Plugins should only be available if there are indeed plugins (like CBT) plugging into the UI. Settings and Styles are core features, not plugins that should be unpinnable.

**Comment by jasmussen** [comment]
> CBT should emulate the unpin/pin functionality.

Just to clarify, I think we need for this functionality to not be optional for plugins, so it should exist on the core side.

> In short, Plugins should only be available if there are indeed plugins (like CBT) plugging into the UI. Settings and Styles are core features, not plugins that should be unpinnable.

Right: any plugin that registers a plugin sidebar should be unpinnable and re-pinnable through an entry in the plugins menu, and it should happen automatically.

**Comment by youknowriad** [comment]
Given the discussion here and the linked PR. It seems we want to keep the "styles" menu in the site editor, so I'm closing this issue.
