### ISSUE TITLE
Hide parent selector when descendent of a disabled block is selected

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#51878]
It would be really nice (either here or in a follow-up) to also hide the parent selector when direct descendants of Post Content are selected. It doesn't really serve any meaningful purpose in this context:

<img width="147" alt="Screenshot 2023-06-22 at 10 05 14" src="https://github.com/WordPress/gutenberg/assets/846565/e3735bae-1bf5-40fc-a61f-b53c72558428">

_Originally posted by @jameskoster in https://github.com/WordPress/gutenberg/pull/51780#pullrequestreview-1492739202_

**Comment by noisysocks** [comment]
Something I realised while writing E2E tests is that if we do this we're removing one of the accessible ways to select the Post Content block. I think the only remaining way would be via the breadcrumbs. How much do you dislike this button, @jameskoster? 😀

**Comment by jameskoster** [comment]
> Something I realised while writing E2E tests is that if we do this we're removing one of the accessible ways to select the Post Content block.

The motivation for this change is the same as https://github.com/WordPress/gutenberg/pull/51780. With that in mind, I'm not sure there's an accessibility issue here? When you're editing a page, there's basically no value in selecting the Post Content block because you can't do anything with it, and the parent selector feels like a distraction. 

That said, I don't think it's a huge deal. Though nice to fix, if it's going to cause headaches perhaps it's something we circle back to later?
