### ISSUE TITLE
Pattern block: "Manage Patterns" to open the Library > Custom patterns

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#51944]
If supported, instead of navigating to `/wp-admin/edit.php?post_type=wp_block`, it would be nice if this control opened the new Library within `/wp-admin/site-editor.php?path=%2Flibrary`. 

Perhaps "Open Library"? 

<img width="1581" alt="CleanShot 2023-06-26 at 17 05 21" src="https://github.com/WordPress/gutenberg/assets/1813435/a434a908-a4eb-41dc-84a1-14adc0b1985a">

<img width="429" alt="CleanShot 2023-06-26 at 17 07 45" src="https://github.com/WordPress/gutenberg/assets/1813435/eac7a66f-dbea-41ea-adbd-f97b6c4f23b5">

**Comment by jasmussen** [comment]
I could go with either "Manage patterns" or "Open library", though would be good to check the capitalization. It should be sentence case but I think there are some cases around proper nouns.

**Comment by richtabor** [comment]
> I could go with either "Manage patterns" or "Open library", 

Let's roll with "Open library".

**Comment by aaronrobertshaw** [comment]
Just noting here that we're likely renaming "Library" to "Patterns", so perhaps we stick with "Manage patterns" after all. (https://github.com/WordPress/gutenberg/issues/52042)

**Comment by richtabor** [comment]
Works for me; we just need to fix the capitalization then (alongside the change in path).

**Comment by carlomanf** [comment]
This issue reminds me of https://core.trac.wordpress.org/ticket/54908, which got fixed by removing the `edit.php` screen altogether for templates and template parts. Perhaps the same treatment could be considered for reusable blocks now. While reusable blocks have long been available through `edit.php` and removing it would upset some users, it should also be noted that the screen does not include "unsynced" patterns and would cause some associated confusion. A similar issue was reported with #35994 and abandoned because it was too hard to fix.

**Comment by aaronrobertshaw** [comment]
I have an alternate solution up in https://github.com/WordPress/gutenberg/pull/52403 which will allow us to conditionally direct users to where most appropriate for the time being.

We can explore the removal of the `edit.php` screen if desired after 6.3. That would afford us some additional time to communicate well to the users that might be negatively impacted by the change.
