### ISSUE TITLE
Slideshow galleries

### ISSUE THREAD

**Issue by MrWonka** [WordPress/gutenberg#5197]
Loving the progress so far, however I wish I could make slideshow photo galleries, as I like to categorize my photos so people can see all the photos if they want, or just specific ones.

**Comment by Soean** [comment]
Hey @MrWonka,
thanks for your idea. We already have a ticket for a slideshow block, see #1958
It is closed for now, because it is not on the Roadmap for 5.0, but maybe later. 
You can give feedback in that ticket and add ideas.

Themes also can extend the gallery block to open a lightbox and start a slideshow.

**Comment by strarsis** [comment]
https://github.com/WordPress/gutenberg/issues/6608
