### ISSUE TITLE
Normalize template parts and pattern icons in "new" dropdown

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#52043]
The current dropdown in the patterns library is the following:

<img width="477" alt="image" src="https://github.com/WordPress/gutenberg/assets/548849/079e05ff-7544-4309-a911-f3be4a9f25ac">

This is a bit misleading since the "header" icon is not the default template part one, and the folder icon is used for pattern categories, not individual patterns. We should instead use these two, which further strengthens the relationship:

<img width="240" alt="image" src="https://github.com/WordPress/gutenberg/assets/548849/e333369a-208a-4d20-858a-238e970dfe47">

**Comment by jameskoster** [comment]
If we rename Library as Patterns (https://github.com/WordPress/gutenberg/issues/52042), do these need to be separate actions?

There may be scope to combine them in a single "Create pattern" modal:

<img width="568" alt="Screenshot 2023-06-28 at 15 37 32" src="https://github.com/WordPress/gutenberg/assets/846565/b14ece04-f8a3-41a1-bf93-04801ab55980">

If a pattern is added to the header category and marked as synced then a template part is created.

This modal could be reused in the editor, where instead of separate "Create template part" and "Create pattern" actions in the block toolbar we could just have a single "Create pattern":

<img width="333" alt="Screenshot 2023-06-28 at 15 40 33" src="https://github.com/WordPress/gutenberg/assets/846565/423bf1bb-52fc-467c-b2ce-4946ad2a9b32">

**Comment by bgardner** [comment]
@jameskoster I note in your screenshot that there is a "Category" drop down menu. Thought it’s not in 16.1, I suspect that is on its way? And if so, will it only include a list of core categories? Or will there be an option for custom categories to be created?

**Comment by mtias** [comment]
@jameskoster not ready to combine, the icon change is trivial during beta. The other is a whole new UX flow.

**Comment by talldan** [comment]
> I note in your screenshot that there is a "Category" drop down menu. Thought it’s not in 16.1, I suspect that is on its way? And if so, will it only include a list of core categories? 

@bgardner It's still being explored. In an earlier iteration there was an option to categorize user created patterns, but there were some bugs and technical issues that meant it wasn't included in the beta. I'm not sure it'll make 6.3, but I hope it'll be something that's added in a future Gutenberg plugin release and 6.4.

> Or will there be an option for custom categories to be created?

I think it'll be technically possibile. I'd let one of the design contributors answer about the user experience side. I guess there would need to be some thought about how it will scale. I know some users have many reusable blocks (and so patterns). It seems like it would be a useful organizational tool for those users.

**Comment by mtias** [comment]
Categories won't be in for 6.3. We should incorporate that into phase 3 as part of the broader workflow work, including possibly adding categories for media library as well.

**Comment by talldan** [comment]
Fixed by https://github.com/WordPress/gutenberg/pull/52108
