### ISSUE TITLE
Footnotes Block: unable to insert footnote on Paragraph inside Quote Block

### ISSUE THREAD

**Issue by liviopv** [WordPress/gutenberg#52084]
### Description

Unlike on other blocks with nested blocks (Cover, Media & Test), Footnotes are not working properly on the Quote Block. The link in the highlighted piece of text will be added, but the editor will not jump correctly to the Footnote Block

### Step-by-step reproduction instructions

1. Add the Quote Block to a post or page
2. Add a Paragraph inside the quote 
3. Add a Footnote to the Paragraph
4. The superscript link will be added to the highlighted text, but the screen will not just to the Footnote Block correctly, allowing to add the footnote

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/14153300/d2722f21-6b81-4295-be47-bd90fc9b49be

### Environment info

WordPress 6.2.2, Gutenberg 16.1 running on Local
Chrome 114, MacOS 13.0.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
I am able to confirm as well. cc @ellatrix

**Comment by ellatrix** [comment]
The problem here is that these blocks use `InnerBlocks.Content`. So turns out footnotes is not compatible with `InnerBlock.Content` because it’s wrapped in a function component. It _is_ compatible with `useInnerBlocksProps.save`, because that just returns the blocks without a wrapper component. 🤔 Not sure how we can make this work, other than just deprecating `InnerBlock.Content`...
