### ISSUE TITLE
Parts assigned to their own area do not appear in the site editor library.

### ISSUE THREAD

**Issue by inc2734** [WordPress/gutenberg#52101]
### Description

Areas added with filter hooks do not appear in the site editor library. Template parts assigned to that area do not appear in the list even if they are created.

### Code to add an area

```
function my_default_wp_template_part_areas( $default_area_definitions ) {
	return array_merge(
		$default_area_definitions,
		array(
			array(
				'area'        => 'my-area',
				'label'       => 'My Area',
				'icon'        => 'layout',
				'description' => '',
			),
		)
	);
}
add_filter( 'default_wp_template_part_areas', 'my_default_wp_template_part_areas' );
```

### Step-by-step reproduction instructions

- Add new area with the `default_wp_template_part_areas` filter hook.
- Create a template part assigned to that area.
- When we go to the library, we will see a list of template part areas, but not the unique area we added.
- The number of template parts assigned to uncategorize is increasing, but they are not shown in the preview.
- The same problem occurs whether template parts are created in the site editor or added to the parts directory.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/1094306/2eb8a872-486f-40e4-b3fe-b0af0fe07e37

### Environment info

- WordPress 6.3 beta2
- Twenty Twenty-ThreeVersion: 1.1
- Gutenberg 16.1.0 Enable/Disable

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by bd-viget** [comment]
I may need to open a new issue for this, however after this has been added, I'm wondering why can't the template part just display under its own custom section, rather than having them all in `General`?

<img width="347" alt="Screenshot 2023-10-25 at 4 34 23 PM" src="https://github.com/WordPress/gutenberg/assets/122309362/e81a334f-5b7e-4427-8714-d1dacb3c333c">

If I use the `default_wp_template_part_areas` filter to defined my own custom area, this should reflect in the FSE UI next to General, Header, and Footer.

And a side question, are our only options for icons `layout`, `header`, and `footer`? Is there no support for custom icons or passing an SVG value?

**Comment by bd-viget** [comment]
Another issue here is the value passed for `area_tag` is not honored. Using the following as an example:

```php
function my_default_wp_template_part_areas( $default_area_definitions ) {
	return array_merge(
		$default_area_definitions,
		array(
			array(
				'area'        => 'my-area',
				'label'       => 'My Area',
				'icon'        => 'layout',
				'description' => '',
				'area_tag'    => 'nav',
			),
		)
	);
}
add_filter( 'default_wp_template_part_areas', 'my_default_wp_template_part_areas' );
```

In my use case, I'm using `render_block_core_template_part` and the tag used in the output is `<div>`
