### ISSUE TITLE
Table block alignment issue.

### ISSUE THREAD

**Issue by viralsampat-multidots** [WordPress/gutenberg#52156]
### Description

Hello Team,

I was working with the table block and found one alignment issue. Here, I have prepared its video and attached it.

For a better understanding, please see my attachment.

**[Table block alignment issue: ](https://share.cleanshot.com/WG0gwfDH1sL81SMG0j3J)**

Thanks,

### Step-by-step reproduction instructions

1. Choose table block
2. Add its row/column data
3. Then, change its alignment from the horizontal toolbar setting.
4. Then view the page.

### Screenshots, screen recording, code snippet

![CleanShot 2023-06-30 at 11 57 50@2x](https://github.com/WordPress/gutenberg/assets/53076293/54b9a1c1-c99f-4e42-b9a5-594aa4c79279)
![CleanShot 2023-06-30 at 11 58 14@2x](https://github.com/WordPress/gutenberg/assets/53076293/6150cb3c-a79a-47a8-964f-c478820331be)

### Environment info

- WordPress version:6.2.2, Gutenberg 16.1.0, Theme active: Twenty Twenty-Three, Twenty Twenty
- Browser: Google chrome, Version 114.0.5735.198 (Official Build) (arm64)
- Device: MacBook Air M1
- OS: macOS 13.4.1 (22F82)

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi
Thank you for reporting the issue.
Just noting that this happens with other blocks too, like the image block.
There is no perfect solution for this, because the necessary CSS changes would affect the layout of existing websites.

There is some historical context and discussions on this:
https://github.com/WordPress/gutenberg/issues/4127

As a user, the recommended way to work around this is to place the table block inside a group block, or a column.

**Comment by jordesign** [comment]
Thanks for the context @carolinan - agreed this is a known behaviour that effects man blocks.

That being the case I'm going to close this issue for now.
