### ISSUE TITLE
Site Logo: Add aspect-ratio tool for custom image dimensions

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#52169]
[The aspect ratio control for custom image dimension](https://github.com/WordPress/gutenberg/issues/38990) has been very helpful. 

Can we have that for the Site Logo block too? It could be useful for some themes that are designed with a specific logo size and an aspect ratio in mind.

**Comment by richtabor** [comment]
I struggle with identifying when a site logo should have an aspect ratio assigned to it. The only instance I can think of is for when your avatar is your site logo. Otherwise, I don't think users would expect to replace a logo with their own and have it conform to a different aspect ratio.

Images work better, because there can be some soft-cropping, but logos can't.

**Comment by draganescu** [comment]
Yes, despite jumping quickly and trying to add the feature (see `try/site-logo-ar`), I second @richtabor 's problem above. Usual users will have a logo that is what it is - a photo, a drawing, some clipart. The profesional designer will have multiple variants of the logo. So setting a constraint in a pattern for the site logo in terms of aspect ratio does not look useful.

Maybe in terms of suggestion? Like, this aspect ration would look best.

**Comment by iamtakashi** [comment]
Thank you both for the feedback. Yes, @richtabor, I had the [Hey theme](https://heythemedemo.wordpress.com/?demo) in mind when I made this request. It's probably too niche.

**Comment by scruffian** [comment]
I think we should close this one as it doesn't seem like a good idea for the reasons above.
