### ISSUE TITLE
Image Block: Rename 'lightbox' feature to something more user friendly

### ISSUE THREAD

**Issue by artemiomorales** [WordPress/gutenberg#52183]
## What problem does this address?

The image 'lightbox', as currently named, may be unintuitive and jargony. We should consider renaming the lightbox to something more user friendly.

## What is your proposed solution?

I don't myself have many ideas for the moment, but perhaps something with 'expand' or 'enlarge' could work.

I'm also happy to go with 'lightbox,' but I understand there were varying opinions around this so thought I would open an issue to discuss.

**Comment by dmsnell** [comment]
"Lightbox" has going for it a long history of specific semantic use. While it risks being _jargony_, that is also balanced by being recognizable and less ambiguous.

**Comment by luisherranz** [comment]
I prefer 'expand' or 'enlarge'. I would actually go one step further and make it even more explicit by calling it 'Expand on click' (or 'Enlarge on click') in the UI select, so people reading it for the first time have a better idea of what this does.

**Comment by artemiomorales** [comment]
From a development perspective, I like that "lightbox" is concise and, from my perspective as a dev, pretty explanatory, at least code-wise, so perhaps leaving that in the code is for the best.

@luisherranz Do you mean that we could just change the label to 'Enlarge on click' but leave the actual value in the dropdown as `lightbox`, and continue using 'lightbox' throughout the scripts and styles? If so, I think that would be easiest and the best in terms of usability for both users and developers.

**Comment by dmsnell** [comment]
Keep in mind too that "lightbox" is not a term that come from software, but the software effect was built to mimic the effect of using a light box on some object. I only note this because the discussion sounds like a developer-vs-user conversation but the term itself comes more from the marketing and user end than it does from the software end.

**Comment by justintadlock** [comment]
As far as I know, the best data we have on this is the 10+ years of [lightbox plugins](https://wordpress.org/plugins/search/lightbox/) in the plugin directory, and pretty much most of them use "lightbox" in the title or description. There's a lot of history there, and I'd lean toward following what looks to already be working.

With that in mind, I do like something like "Expand on click" when I start thinking about new users who are unfamiliar with the lightbox concept.

**Comment by luisherranz** [comment]
> change the label to 'Enlarge on click' but leave the actual value in the dropdown as lightbox, and continue using 'lightbox' throughout the scripts and styles

No, that would be confusing for people that see `lightbox` in the `theme.json` and then it's trying to locate that behavior in the UI or vice versa.

In my opinion, the only thing that would be ok would be to call it `expand` and then use `Expand on click` on the label. `Lightbox on click` doesn't make much sense because lightbox is not an action.

**Comment by SantosGuillamot** [comment]
My two cents: It may be because I am not used to these functionalities, but I wasn't aware of what "lightbox" meant before working on this project. In that sense, "Expand on click" seems clearer to me.

I was wondering, is the "lightbox" term universal? Do non-English speaking users (not developers) understand the term "Lightbox"? Do you think "lightbox" will need to be translated into different languages? You might have more context than me, that's why I'm asking 🙂

**Comment by hanneslsm** [comment]
I'm strongly voting for keeping it as lightbox.
As @justintadlock we're using it since more then 10 years, it's the de facto name for this kind of functionality. ([2005 actually, the functionality even has a wikipedia articles in multiple languages](https://en.wikipedia.org/wiki/Lightbox_(JavaScript)), Google shows more than 111 million result when searching for "lightbox web").
We not have to change everything - save icons also still are floppy disks.

From a UX stand point I do not like "expand on click" for the following reasons:
1. It's focused on the visual effect. What if I want to have the expansion only very subtle - if at all? Is 10% already a "expansion" that is for all users notable to justify this as a name?
2. It's too limiting. Lightboxes can be expanded to show thumbnails and other information also. Will the name change, when these features will be implemented (like "show more")?
3. It focuses to much on the behavior and this can be confusing. If it's called "expand on click" does this mean, that it will also work when tapping?

**Comment by artemiomorales** [comment]
Hi @pablohoneyhoney, do you by chance have any thoughts on this? This based on [a suggestion](https://github.com/WordPress/gutenberg/issues/51055#issuecomment-1578360826) you made that perhaps 'lightbox' wasn't a good indicator of the functionality a while back.

**Comment by Poliuk** [comment]
My vote goes for keeping the lightbox naming, mainly because it's a widely adopted term in web development and, as Justin pointed out, especially in WordPress where we have 10+ years of plugins naming this same functionality as "lightbox".

**Comment by richtabor** [comment]
> "Lightbox" has going for it a long history of specific semantic use. While it risks being jargony, that is also balanced by being recognizable and less ambiguous.

Agreed. Lightbox is likely the most familiar/understood convention for this behavior.

**Comment by artemiomorales** [comment]
Given all of the input so far, it seems like "lightbox" is a solid choice for moving forward. Will go ahead and close this. Thanks everyone! 🙏

**Comment by dmsnell** [comment]
![lightbox](https://github.com/WordPress/gutenberg/assets/5431237/e2b83b55-162b-4d1d-be85-e126a7cf9688)

**Comment by Poliuk** [comment]
We've been discussing how to surface this new setting in the site editor, and we've come to the conclusion that we don't need to use the "Lightbox" label in the settings panel.
The official name of the feature will still be "Lightbox".

For more context see [this comment](https://github.com/WordPress/gutenberg/issues/53403#issuecomment-1697251463).
