### ISSUE TITLE
Navigation Burger menu > opened > close button inconsistencies (depending the log in status)

### ISSUE THREAD

**Issue by Marc-pi** [WordPress/gutenberg#52233]
### Description

The Burger Menu (navigation block), on mobile, displays wrongly the close cross (see screenshot below)
When user is log out, the cross is too close from the top of the screen.
It deals with admin bar not present for anonymous users (not log in)

The issue is there for months, and brings novice WP user to think that Gutenberg is not production ready.
The only way to fix this is to add custom csss.

@getdave if you can have a look, it is an issue that impacts all FSE sites, thus critical :-)
@ndiego  to be added IMHO for 6.3 next beta/RC , since it has a daily impact on 100% of FSE websites running purely Gutenberg

### Step-by-step reproduction instructions

1. Set a navigation menu with basic page entries
2. Play on mobile with it : open the burger and observe the UI
3. You can see the position of the icone is not consistent, depending on the log in statuts

### Screenshots, screen recording, code snippet

With admin bar active (login)
![image](https://github.com/WordPress/gutenberg/assets/919332/b20a8e7e-9a66-4cbe-b60c-beb45610a67d)

With no admin bar active (logout)
![image](https://github.com/WordPress/gutenberg/assets/919332/d194597a-5968-40a4-a4ff-0269af897285)

### Environment info

WP 6.2.2
Woo Blocks 10.5.0
TT2/TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by MaggieCabrera** [comment]
Right now this is working as intended, but probably what is intended is not what you are expecting, so it can prove confusing. The mobile overlay is setting padding-top to be the value of what's your [vertical root padding in theme.json](https://github.com/WordPress/gutenberg/blob/79dbfc57a0f3918a299f5856f69561f695ff8896/packages/block-library/src/navigation/style.scss#L509). If you set up a padding to the header template part, the overlay doesn't know, and doesn't have a way to match it. Instead of setting the padding on the containers surrounding the nav block, try setting the global padding values instead.

**Comment by MaggieCabrera** [comment]
I was just testing this with a theme that has a header that has a different background color than the rest of the content and applying the global padding doesn't work for those kinds of themes, and they would be affected by this problem. We should think of a way to avoid applying padding 0 when that is what was selected for the theme...

**Comment by MaggieCabrera** [comment]
@jasmussen I wonder if you have thoughts on this, since you fixed https://github.com/WordPress/gutenberg/pull/43576 introducing these variables.

**Comment by jasmussen** [comment]
Yes indeed, the adminbar is throwing this for a wrench, and the impact it's having on theme design work in general is definitely something to consider for any potential design iterations for the adminbar in the future.

When I worked on this last, and to keep the code simpler without too many position-gotchas (logged in, logged in mobile, not logged in), I intentionally ignored the adminbar, recognizing that it causes a shift but at least that shift is only for the editors/owners of the site.

Code quality is my main concern here, given the 3 cases that need to be handled in the top-positioning math of the overlay. But if a PR gets built that handles those cases in a nice enough way that doesn't feel like technical debt piling up, then I would think that could thread the needle and get a green light.

**Comment by MaggieCabrera** [comment]
> Yes indeed, the adminbar is throwing this for a wrench, and the impact it's having on theme design work in general is definitely something to consider for any potential design iterations for the adminbar in the future.
> 
> When I worked on this last, and to keep the code simpler without too many position-gotchas (logged in, logged in mobile, not logged in), I intentionally ignored the adminbar, recognizing that it causes a shift but at least that shift is only for the editors/owners of the site.
> 
> Code quality is my main concern here, given the 3 cases that need to be handled in the top-positioning math of the overlay. But if a PR gets built that handles those cases in a nice enough way that doesn't feel like technical debt piling up, then I would think that could thread the needle and get a green light.

No, it's not the admin bar that is a problem here, if you check the screenshots on the issue, the one that is broken is the one without an admin bar (has no extra margin to push it down). This only happens in cases where the theme declares the global padding-top for the site to be 0, so `padding-top: var(--wp--style--root--padding-top, 2rem);` resolves to 0. And we can't expect all themes to declare a non-zero value for the global padding because of the cases where the header needs to be a different color than the background of the site.

I don't see a clear solution here, we could revert to using 2rem but that would cause misalignments for sites that do use the padding-top. I wish we could apply it conditionally so we ignore zero values but I don't think there's a way for us to do that

**Comment by jasmussen** [comment]
Oh that's a doozy, thank you for the clarification!

So to make sure I get this right, when you're logged in, `var(--wp--style--root--padding-top, 2rem);` resolves to `2rem`, and when you're logged out, it resolves to `0`, is that right? I feel like I'm still missing a reason why this diverges.

**Comment by MaggieCabrera** [comment]
> Oh that's a doozy, thank you for the clarification!
> 
> So to make sure I get this right, when you're logged in, `var(--wp--style--root--padding-top, 2rem);` resolves to `2rem`, and when you're logged out, it resolves to `0`, is that right? I feel like I'm still missing a reason why this diverges.

No, it always resolves to 0, but when logged in there's an extra margin applied to compensate for the admin bar. If your site has padding-top applied instead of adding a wrapper to the header for the spacing, it will work nicely both logged-in or out. It fails if the global padding is 0 and you are using other means to separate the nav block from the top of the viewport (which are never considered by the overlay menu). The problem was never about the admin bar.

**Comment by jasmussen** [comment]
Tricky. I'll try and reproduce when I have a moment and see if I get any ideas!

**Comment by Marc-pi** [comment]
yep, detected on TT2/TT3 themes, the only ones i use as base to build my themes

**Comment by jasmussen** [comment]
Oh I see it!

<img width="1392" alt="Screenshot 2023-08-16 at 11 08 35" src="https://github.com/WordPress/gutenberg/assets/1204802/014b2f4d-cd98-483b-aced-8087f254eed4">

<img width="1392" alt="Screenshot 2023-08-16 at 11 09 09" src="https://github.com/WordPress/gutenberg/assets/1204802/9f5bce86-2a39-4e9c-9fe7-046e09b67326">

What would be the downside to simply removing this rule then?

```
.has-modal-open .admin-bar .is-menu-open .wp-block-navigation__responsive-dialog {
    margin-top: 46px;
}
```

? 

Or, can we be smarter about that rule?

**Comment by MaggieCabrera** [comment]
> Oh I see it!
> <img alt="Screenshot 2023-08-16 at 11 08 35" width="1392" src="https://user-images.githubusercontent.com/1204802/260960100-014b2f4d-cd98-483b-aced-8087f254eed4.png"> <img alt="Screenshot 2023-08-16 at 11 09 09" width="1392" src="https://user-images.githubusercontent.com/1204802/260960112-9f5bce86-2a39-4e9c-9fe7-046e09b67326.png">
> 
> What would be the downside to simply removing this rule then?
> 
> ```
> .has-modal-open .admin-bar .is-menu-open .wp-block-navigation__responsive-dialog {
>     margin-top: 46px;
> }
> ```
> 
> ?
> 
> Or, can we be smarter about that rule?

then we will get the bad result while logged in. Check TT3 logged out, you'll see the issue there.

**Comment by jasmussen** [comment]
Yes, the menu shifts, but at least that'll be for logged in people rather than the majority of visitors. 

But are there other ways we can address this? Can we change the `top` value of the modal while logged in, instead of add margin?

**Comment by MaggieCabrera** [comment]
> Yes, the menu shifts, but at least that'll be for logged in people rather than the majority of visitors.
> 
> But are there other ways we can address this? Can we change the `top` value of the modal while logged in, instead of add margin?

Yeah, we could use top instead of margin, definitely, but I don't think this is what's causing our issue here.

I'm sorry, I was wrong, TT3 doesn't have this issue, because it does set a proper global padding top. The one theme that I know for sure has this issue is [Blue note](https://wordpress.org/themes/blue-note/), which sets it to 0:

(logged out)
![Screen Capture on 2023-08-16 at 11-21-11](https://github.com/WordPress/gutenberg/assets/3593343/e5619bfb-ada3-4f51-b203-72e98a2dbddb)

**Comment by jasmussen** [comment]
Thanks for the GIF, that's helpful.

To me, that suggests two paths forward:

* We use `min()` as yet another wrapper around the variable, so as to provide a minimum top value so it doesn't bump against the edge. Edit: actually clamp or max might be needed here, mainly just to pick the largest value.
* We hustle on shipping #43852, so that the overlay can be edited separately, and customized in theme.json separately

Potentially the two can be combined.

The current hack is just that, a hack: the idea being that _if you design your website just-so, then things will line up_. But with a zero top-padding, as you note, it breaks apart.

**Comment by MaggieCabrera** [comment]
> Thanks for the GIF, that's helpful.
> 
> To me, that suggests two paths forward:
> 
>     * We use `min()` as yet another wrapper around the variable, so as to provide a minimum top value so it doesn't bump against the edge. Edit: actually clamp or max might be needed here, mainly just to pick the largest value.
> 
>     * We hustle on shipping [Reference the Navigation overlay as template part. #43852](https://github.com/WordPress/gutenberg/issues/43852), so that the overlay can be edited separately, and customized in theme.json separately
> 
> 
> Potentially the two can be combined.
> 
> The current hack is just that, a hack: the idea being that _if you design your website just-so, then things will line up_. But with a zero top-padding, as you note, it breaks apart.

I knew you'd find a solution, why didn't I think of `min()`??? Sorry it took a while for me to explain the issue clearly. I think the template part issue is going to take a while and I suspect this will affect TT4 as well, so I'll whip up a PR with a fix and then we can revisit when we have the overlay and probably remove all this hackiness.

**Comment by jasmussen** [comment]
Just to surface my sneaky edit, it may need _max_ instead of _min_, I always conflate the two. But in either case, make sure that either there's always a minimum value, which max may be able to by always picking the larger of two.

**Comment by MaggieCabrera** [comment]
> Just to surface my sneaky edit, it may need _max_ instead of _min_, I always conflate the two. But in either case, make sure that either there's always a minimum value, which max may be able to by always picking the larger of two.

So the minimum value is 2rem, and the max is the global padding top if it's bigger than 2rem.

**Comment by jasmussen** [comment]
Sounds right to me, and happy to test.
