### ISSUE TITLE
Text editor toolbar appears unnecessarily

### ISSUE THREAD

**Issue by vikmartin** [WordPress/gutenberg#52242]
### Description

When editing text in the block editor, the toolbar appears whenever you move the mouse rather than when you highlight text to change it

### Step-by-step reproduction instructions

1. Add new post
2. enter text in a paragraph block
3. move mouse

### Environment info

WordPress version: 6.2.2 Using Oxygen Builder
Happens on desktop - both Windows and Mac OS
Chrome and Firefox browsers

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
Hi @vikmartin  - you're correct about this behaviour - I find that happens in my testing.

My understanding is that the behaviour is correct and by design - as it allows you to apply styling (like bold/italic etc) to text _you're about to write_.

For example I might type a few words - then move my mouse to hit the 'bold' style, then keep typing in bold font, before clicking the 'bold' style off again.

**Comment by jordesign** [comment]
Given this is the expected behaviour - I'm going to close this issue. But please feel free to open it again if you feel there is more to discuss.
