### ISSUE TITLE
Focus mode: Lots of unrelated whitespace. 

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#52429]
<img width="1359" alt="Screenshot 2023-07-07 at 16 01 42" src="https://github.com/WordPress/gutenberg/assets/846565/38717b71-cd04-4752-8505-328920e08f4f">

The blue container in the screenshot above encompasses the entirety of the pattern. The whitespace above / below is caused by a couple of things:

1. Padding on the `body` applied in global styles
2. The appended inserter

These combine to somewhat taint the edit experience, as you're never 100% certain whether this whitespace is part of the pattern or not. It makes the overall experience feel a little buggy.

We can probably remove the body padding – it's not really relevant here as a pattern is never going to be viewed in isolation on the frontend.

For the inserter, perhaps we can try hiding it when the pattern is not empty?

**Comment by Ren2049** [comment]
If it's the TT3 theme then the padding is part of the global styles layout of the theme. I've started a new site with TT3 from scratch today and had to remove the padding  it from the global layout as well, same for the global block spacing which also doesn't belong there.

I guess they did it globally because it worked with their overall design style which is kind of exotic with that high amount of whitespace. For future default themes it might be a good idea to build the default theme with end user modifciation in mind which will be pattern based of course.

There are some good nuggets in this default Webflow design system everybody there is using which could be adapted for WP, basically as a general guideline for how themes should be build: https://finsweet.com/client-first/docs

**Comment by jameskoster** [comment]
The issue here is that it doesn't really make sense for the global padding to be visible when editing a template part in isolation.

**Comment by Mamaduka** [comment]
Is this the same issue as #51937?

**Comment by jameskoster** [comment]
Yes it is, thank you.
