### ISSUE TITLE
Site Editor: Inconsistent Delete button design in the dropdown

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#52510]
## What problem does this address?

In the Site Editor, we can rename, duplicate, and delete, primarily from the dropdown menu that appears by clicking on the ellipsis button. In this context, I feel that the UI is not unified about the **Delete** button.

- Should the Delete button be displayed in default or red?
- Do we need a border over the Delete button?

### Navigation Sidebar

![navigation](https://github.com/WordPress/gutenberg/assets/54422211/ad3ab315-0c14-41ad-8cea-101ef3279cee)

### Page Sidebar

![page](https://github.com/WordPress/gutenberg/assets/54422211/22f23086-1690-48ea-85df-4944bfdda2a4)

### Template Sidebar

![template_sidebar](https://github.com/WordPress/gutenberg/assets/54422211/886313ac-3666-4652-a73d-a216266e6671)

### All Templates

![template_list](https://github.com/WordPress/gutenberg/assets/54422211/29d7ac46-6763-4b06-9711-b0b476283956)

### All Template Parts

![template_part_list](https://github.com/WordPress/gutenberg/assets/54422211/8482f313-1580-430a-9026-68143154fda0)

### Patterns > My Patterns

![my_patterns](https://github.com/WordPress/gutenberg/assets/54422211/47cd4f92-af12-4b82-84a7-f51df2aae4b8)

## What is your proposed solution?

My feeling is that the following rules should apply:

- Red button (`is-tertiary`, `is-destructive`)
- No need for a top border.

**Comment by Mamaduka** [comment]
I think @afercia has some thoughts regarding using red color for destructive buttons.

**Comment by afercia** [comment]
Good catch @t-hamano ! Thanks for the ping @Mamaduka 

Historically, classic WordPress has always used red for destructive actions, together with an 'Are You Sure?' (AYS) dialog. I'd keep this pattern because users are familiar with it.

From an accessibility perspective, color alone wouldn't be sufficient if this was an icon button with no visible text. Since there is text and there is a confirmation dialog, I'd say this pattern is OK for a11y.

Aside:
While investigating this issue, I noticed something new. Looks like this is not the only inconsistency in the navigator screens. Spot the difference in the screenshot below :)  (I will create a separate issue)

<img width="750" alt="Screenshot 2023-07-13 at 09 17 34" src="https://github.com/WordPress/gutenberg/assets/1682452/30eeb409-80c0-4bc8-ae1a-2d1c1fbccdf7">
