### ISSUE TITLE
Buttons have mismatched heights

### ISSUE THREAD

**Issue by joecsmalley** [WordPress/gutenberg#52533]
### Description

I built a page with 4 inline buttons on top. The text on two of them drops down to a second line so the buttons are of different heights. There used to be the option to adjust that but I don't see it any longer, or potentially it's been removed. It could be just me but I created a vanilla wordpress site with just gutenberg and still had the same issue. I can't imagine I'm the only one who thinks buttons all with matching heights is visually appealing. Any help would be apprieciated.

### Step-by-step reproduction instructions

Create New Page > Create 4 buttons that display inline > Now how do you make them uniform?

### Screenshots, screen recording, code snippet

![Screen Shot 2023-07-11 at 3 35 10 PM](https://github.com/WordPress/gutenberg/assets/9999325/2c7a59ea-9ebb-465a-8480-195de187e394)

### Environment info

Wordpress Version 6.2.2
Twenty Twenty Three Theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ethanclevenger91** [comment]
To clarify this issue -

1. New WP install. TT3 theme. No Gutenberg plugin installed.
2. New post
3. Add button group
4. Create a few buttons
5. Disable wrapping at the button-group level
6. Ensure at least one button has enough content to overflow to a second line, and at least one other button does not
7. On the button group, set "Change vertical alignment" to "Stretch to fill"
8. See buttons do not, in fact, stretch to fill.

Can be seen [here](https://memberpresstest.kinsta.cloud/?p=10)

**Comment by ethanclevenger91** [comment]
To ensure this gets eyes, the tag should probably be updated to `[Type] Bug`. @jordesign is that something you're able to update?

**Comment by jordesign** [comment]
Thanks for the additional testing @ethanclevenger91  - I've labeled this one as an enhancement - as the behaviour being reported is as expected (rather than a bug).

Introduce an option/control for managing/evening the height of blocks is a good suggestion - but would be considered an enhancement of the existing functionality.

**Comment by jennydupuy** [comment]
In WP 6.5, this option still doesn't work for buttons, whereas it does for columns or rows.

**Comment by ethanclevenger91** [comment]
@jordesign I wouldn't really call this an enhancement. There's an alignment setting, and as @jennydupuy mentioned, it does what you would expect for columns and rows. It doesn't behave as expected for buttons. I would call this a bug, not an enhancement.

**Comment by t-hamano** [comment]
I tested this problem using Playground.

### WP 6.1.5

https://playground.wordpress.net/?wp=6.1

The "Stretch to fill" option does not exist in either Buttons or Button blocks.

![image](https://github.com/WordPress/gutenberg/assets/54422211/4d9f5d93-b3cf-4925-a6f0-f9a19dc91d9c)

### WP 6.2.4

https://playground.wordpress.net/?wp=6.2

![image](https://github.com/WordPress/gutenberg/assets/54422211/dfa70b6c-ea84-4880-8805-8adfe46de309)

A "Stretch to fill" option exists. Applying this option will align all buttons to the top.

### WP 6.3.3, WP6.4.4, WP 6.5 RC4 and latest Gutenberg

https://playground.wordpress.net/?wp=6.3
https://playground.wordpress.net/?wp=6.4
https://playground.wordpress.net/?wp=beta

Applying this option will align all buttons to the top.

So I guess this option hasn't been working properly since it was first introduced in WP6.2. Therefore, I'm marking this issue as a bug.
