### ISSUE TITLE
Add actions for saving / publishing a post.

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#526]
We need to hook up the actions for saving and updating a post at the bare minimum. It'd be good to touch base with API focus group.

**Comment by nylen** [comment]
I can take this one.

This is a thought for later rather than an immediate concern, but when we implement post scheduling / reverting to unscheduled, we will run into https://core.trac.wordpress.org/ticket/39953.

There will likely be more issues along the way, but we can tackle those as they come up, using the plugin to test out our proposed solutions.
