### ISSUE TITLE
Columns block blockGap not working properly on front end

### ISSUE THREAD

**Issue by bgardner** [WordPress/gutenberg#52616]
### Description

When using the blockGap (Block Spacing) setting in the Columns block, unexpected results occur. Typically when horizontal and vertical units are set, the property (`gap` in this case) outputs two values. It appears that whichever setting is given last (in order), that’s the one used in the CSS output.

### Step-by-step reproduction instructions

1. Go to page editor, add Columns block.
2. Add content to each column.
3. Set horizontal and vertical Block Spacing to separate values.
4. Publish page and see on front end that spacing is not being honored per the setting.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/486261/5827bde1-a576-44dc-bd3f-bdd2422de02e

### Environment info

WordPress 6.3 Beta 4
Gutenberg plugin not active
No other plugins active

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by richtabor** [comment]
I'm pretty sure the vertical blockGap is for when the columns are stacked vertically (mobile). It's a bit odd that there's no feedback when applying it, and also that the setting is enabled even if the columns are set to not stack on mobile though.

**Comment by bgardner** [comment]
When horizontal and vertical gaps are applied, there should be two output values such as:

`gap: var(--wp--preset--spacing--60) var(--wp--preset--spacing--80);`

But  it appears the output is only the last one selected such as:

`gap: var(--wp--preset--spacing--30);`

**Comment by bgardner** [comment]
Which means if you set the vertical gap last, it gets applied to both horizontal and vertical since there is only one value.

**Comment by Ren2049** [comment]
I wish I'd reach the stage (or maybe not lol) where I can play with the columns block. Currently I'm failing to design a properly aligned header. It seems like the internal CSS in JS system has problems that make all this a bug hunting whackamole.

**Comment by justintadlock** [comment]
I can confirm this scenario. A single `gap` property is added instead of both.

For me, this only happens when using spacing presets. If I select custom sizes and units, the gap is output correctly. @bgardner - Can you also confirm this?

**Comment by bgardner** [comment]
@justintadlock Yes, I can confirm this is true.

**Comment by BrennanButler** [comment]
I have been working on a fix for this in the hopes of committing my first contribution to the project.

Firstly, I'm getting some strange behavior when setting the block gap on the columns block. Preset spacing values are being transformed into css clamp values but only for either the vertical or horizontal spacing but never both. 

When the function gutenberg_render_layout_support_flag is executed, the block object passed contains a spacing attribute that has been transformed into the fluid css clamp value. This means the preg_match [here](https://github.com/WordPress/gutenberg/blob/trunk/lib/block-supports/layout.php#L654) skips the gap value due to it containing "unsupported characters".

In order to address the block gap issue we will need to modify the regular expression so that values such as clamp(1.8rem, 1.8rem + ... , 3rem) can be used. Removing "\(" from the expression fixes the block gap issue and I am happy to create a PR if everyone is happy with this for the fix?

**Comment by bgardner** [comment]
It would be great if we could get this fixed, as it’s a big issue affecting a block that is likely often used.

**Comment by bgardner** [comment]
I am closing this issue, as I believe this is fixed in WordPress 6.3-RC1 (with and without Gutenberg 16.3.0-rc.1 plugin active).

Tested the blockGap in Columns and all appears good.
