### ISSUE TITLE
Footnotes: can't add footnotes to nested blocks

### ISSUE THREAD

**Issue by ramonjd** [WordPress/gutenberg#52628]
### Description

I can't seem to add footnotes to any text blocks that are nested inside, say, a Group block.

### Step-by-step reproduction instructions

1. Insert a Group block
2. Then add a paragraph or heading inside
3. Add a footnote to the new text block
4. Observe that the * symbol appears and no footnote is generated

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/6458278/0a712647-729d-4f6e-b97f-2db613010c8e

### Environment info

- WP 6.3 Beta 4
- GB Trunk
- Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
I can confirm, @ellatrix any ideas?

![Image](https://github.com/WordPress/gutenberg/assets/4832319/be553b22-a980-4728-9f38-c2d969d74ade)

**Comment by andrewserong** [comment]
From a little digging, I _think_ this issue might have been introduced in https://github.com/WordPress/gutenberg/pull/52241 as it appears to only recurse into nested blocks that use `InnerBlocks.Content` (the Group block doesn't). We could try tweaking the logic slightly so that it always looks at the `innerBlocks` array instead? I might give that a try so that we have something to play with / test and see if that helps resolve the issue.

**Comment by andrewserong** [comment]
This turned out to be a little tricky as we can't always iterate over `innerBlocks` _after_ processing elements for a particular block, in case the inner blocks are meant to come before the elements of the block. An example of this is the Quote block, where the citation appears after the inner blocks.

I've put up a tentative PR over in https://github.com/WordPress/gutenberg/pull/52676 that seeks to fix it by looking for `RawHTML` as the flag to loop over inner blocks, as `useInnerBlocksProps` outputs inner blocks markup within a `RawHTML` component. It's an imperfect fix as there could conceivably be blocks that intentionally use both `useInnerBlocksProps` _and_ `RawHTML`, but so far, I _think_ the results are better than what we have on trunk. I've pinged a few folks for review on that PR. I'm very happy to throw it out if there are better ideas for how to fix it!
