### ISSUE TITLE
Can't create new navigation bar

### ISSUE THREAD

**Issue by MSR2012** [WordPress/gutenberg#52658]
### Description

I am trying to add navigation bar on footer template after adding navigation bar on header. Whenever I click plus icon and click navigation, it always add navigation block from header. It's not letting me to add new navigation. Most troublesome part is that if I change menu in one navigation, it changes in all.

### Step-by-step reproduction instructions

1. Go to template edit page.
2. Create a navigation on header template.
3. Then try to create another navigation on footer template.
4. Try editing menu name in footer template and observe header template navigation.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi!
When you add the second block in the footer, it automatically selects the _most recently created menu_ on your site.
This is intentional, not a bug.
To select another menu for the second navigation block, open the sidebar, and click on the three dot menu called "Navigation".
Select a menu from the options, or create a new menu:

<img width="282" alt="Navigation block menu tab with list of available menus." src="https://github.com/WordPress/gutenberg/assets/7422055/ba36627f-aee2-49a3-961e-719c1e7ff2dd">

**Comment by MSR2012** [comment]
Thanks, I was able to start new navigation.
