### ISSUE TITLE
post metaboxes cause always active post Publish/Update button

### ISSUE THREAD

**Issue by m-e-h** [WordPress/gutenberg#5272]
## Issue Overview

The `disabled` attribute doesn't get added to the post-publish-button when post metaboxes are present.

## Steps to Reproduce (for bugs)

1. Activate a plugin that uses post metaboxes.
2. Open a post that's been saved. Or save a new post.
3. The Update button is ready to update before any changes have been made.

Current versions of Chrome and Firefox on Ubuntu.

## Expected Behavior

The button should have the `disabled` attribute until a change is made.

## Current Behavior

No disabled att.

## Screenshots / Video

![updatebtn](https://user-images.githubusercontent.com/3585901/36698606-489b56a8-1b18-11e8-8ec4-1822ea888d1a.gif)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by youknowriad** [comment]
This is not a bug, this is the intended behavior. 

The fact is that there's no technical way to know that meta boxes are "dirty" or not because of the way people used to write them. 

 - When you first load the post with metaboxes, some meta boxes are already initialized with content to be saved and thus the link should be active
 - If the meta box form fields are updated programmatically, there's no way to detect that the value of the meta boxes actually changed. There's no `onChange` event, a `mutationObserver` doesn't trigger.

For these particular reasons and to avoid unsaved content, if you have meta boxes the link is never disabled, which is also similar to the current editor's behavior.
