### ISSUE TITLE
`hasMetaBoxes` selector returns `true` even when user has disabled all metaboxes from displaying 

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#52724]
### Description

The selector `wp.data.select('core/edit-post').hasMetaBoxes()` returns `true` even after a user has disabled all metaboxes from displaying via the display settings.

This issue is currently preventing the block editor from getting displayed in an iframe even when the metaboxes aren't actually displayed. 

### Step-by-step reproduction instructions

1. Enable a plugin that loads a traditional metabox such as Yoast SEO
2. Open the editor and disable all the metabox panels in the Settings -> Panels menu
3. Open the browser console and run the `wp.data.select('core/edit-post'). hasMetaBoxes()` selector
4. See that it still returns true.

### Environment info

- WordPress 6.3 Beta 4
- no gutenberg plugin
- emptytheme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by youknowriad** [comment]
Yes, I don't think `hasMetaBoxes` mean `hasVisibleMetaboxes` in this case. It's more about the meta boxes that are sent from the server. That said, even if we had `hasVisibleMetaboxes`, I'm not sure that it would have been the right selector for the iframed editor because adding and removing the iframe when the value changes on the fly is a bit risky. (Re-rendering everything...)

**Comment by fabiankaegy** [comment]
Thanks for that explanation. Closing this for now then 👍
