### ISSUE TITLE
Template Browser: Inconsistent use of 'eg.' in Template Descriptions

### ISSUE THREAD

**Issue by jordesign** [WordPress/gutenberg#52755]
### Description

In the descriptions of Templates it looks like `eg.` is used inconsistently. I see examples of:

* `eg.`
* `eg,`
* `eg.,`

I first spotted this on the 'All Archive' template which includes this text: ` This template will serve as a fallback when more specific templates (e.g., Category or Tag) cannot be found.`

<img width="352" alt="Screenshot 2023-07-19 at 8 50 45 pm" src="https://github.com/WordPress/gutenberg/assets/1842363/f26a95ec-b81b-4fbc-8533-1e4104586dba">

On reviewing the definitions (I could find) in the plugin at  there appeared to be more variations for other templates.

### Step-by-step reproduction instructions

Open the Site Editor > Templates and click through the Templates to see their details displayed.

### Environment info

WP 6.3RC1
No Plugins
TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
I agree this needs to be standardized, but given the string freeze, I think we need to punt this from 6.3. @annezazu @bph @firoz2456 can you confirm?

**Comment by annezazu** [comment]
This is tricky and [relates to a current convo in the release leads channel](https://wordpress.slack.com/archives/C051Z1SKBDZ/p1689743578125149?thread_ts=1689742659.269499&cid=C051Z1SKBDZ). TLDR: there is a string freeze but this relates to an existing string that the polyglots have, rather than providing a new thing to translate. I don't see this as creating additional work for translators based on that conversation so I could see this being a quick update as a result to handle. @tellthemachines  since you helped with that last situation!

**Comment by tellthemachines** [comment]
I'm not sure, because (if I understand correctly) we'd be making actual changes to strings instead of replacing them with existing ones. Does that mean the strings will be marked for translation instead of "fuzzy" as @azaozz mentions in that convo? Even if it's just that tiny change, if it means a translator has to go through and manually check what changed in each string then we should leave this one out.

**Comment by annezazu** [comment]
Flagged in the release leads and polyglots to get more info!

**Comment by tobifjellner** [comment]
String freezes are a bit less critical than before, since we now will create language packs even if a locale didn't reach exactly 100%. So if this gets fixed at least 2 weeks before release, then we'll be able to handle the changes.
This kind of small change will for a previously translated string typically create a "fuzzy": the string is not translated, but the translation platform generates an automatic suggestion with the previous translation. (And in this case, most translations won't actually change...)

Still: For reference, it would be good if you could drop a link to the commit/diff in Polyglots channel when this happens.

**Comment by tellthemachines** [comment]
Thanks for explaining @tobifjellner ! I guess we're good to make this change for RC2 then. Now do we have any volunteers to do a PR? 😄

**Comment by jordesign** [comment]
I'm willing to give it a shot - seeing as I reported it.

**Comment by ramonjd** [comment]
> I'm willing to give it a shot - seeing as I reported it.

Happy to help. Just ping if you need anything.

**Comment by jordesign** [comment]
OK fingers crossed - https://github.com/WordPress/gutenberg/pull/52848 will help with this.
