### ISSUE TITLE
Pattern inserter: filter by source

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#53033]
When there are multiple sources (for instance; the active theme and core) it can be desirable to view patterns from one source or the other rather than all of them jumbled together. 

In the future it may also be useful to offer users access to patterns bundled with installed-but-inactive themes.

A filtering mechanism in the pattern inserter could enable both of these features. A rough mockup:

<img width="312" alt="Screenshot 2023-07-27 at 14 37 22" src="https://github.com/WordPress/gutenberg/assets/846565/62bcf1c4-8f8d-423e-a5c3-a676362701fa">

Perhaps there alternative solutions? Let's discuss.

**Comment by hanneslsm** [comment]
In my theme I heavily [put focus on intrinsic design. ](https://github.com/hanneslsm/ProLooksUI/blob/0496206d487275d9813f48ce5c4217c2af914983/theme.json#L340C9-L340C42). That would mean that when using a pattern, all corresponding variables must also be loaded - spacing, colors, font-sizes, globally and for specific blocks that are used within. Additionally, fonts? I'm not sure of how much this will affect the performance, but I could imagine that we'd run into situations where people start having 10+ themes installed, only to use some of their patters.

**Comment by beafialho** [comment]
Thanks for bringing this up! I think seeing the patterns from a certain theme all together would be really useful. Some users may install themes because they bundle certain patterns they found useful, and from that point of view it seems expectable to see them there clearly and right away.

I find the mockup you shared adds a layer of complexity to the average user. There's no other mention to the active theme's patterns other than when we click that button. Could there be an option where we see the active themes' patterns in the list without these being categories? I think this would make the experience of installing and using a theme clearer.

<img width="418" alt="Captura de ecrã 2023-07-27, às 15 16 09" src="https://github.com/WordPress/gutenberg/assets/65220155/5d72e7a0-31ee-44f8-8d62-5bac1054cc33">

I'm curious what does "My patterns" contain? Is it a category or a filter?

**Comment by jameskoster** [comment]
@hanneslsm without getting too far into the weeds, I think that speaks to a need for standardised variable naming scheme. https://github.com/WordPress/gutenberg/issues/49279 seems relevant in terms of colors.

> Could there be an option where we see the active themes' patterns in the list **without these being categories**?

My concern with this approach is that you lose categorisation which seems like a pretty big trade-off. If a theme bundles hundreds of patterns, it seems likely you'd still want the ability to browse by category? There may also be scalability issues considering that plugins can add patterns too. You risk ending up with a mixture of categories and theme / plugin names which might be detrimental to the browsing experience.

**Comment by jameskoster** [comment]
This is now possible 🎉
