### ISSUE TITLE
LinkControl: "Cancel" does not close the popover entirely

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#53060]
I expected the cancel to close the link popover completely; not revert to the interstitial link preview. If I'm cancelling any edits to a link; I don't think I'd want to see the preview state — but rather close the popover and cancel the edit flow. 

https://github.com/WordPress/gutenberg/assets/1813435/f1dcf3dc-3448-4fcc-982a-e91393b3eacd

Related: https://github.com/WordPress/gutenberg/issues/50892

@getdave thoughts?

**Comment by getdave** [comment]
It's tricky because cancel doesn't mean "close" it means "stop whatever I was doing an go back without persisting anything". "Go back" in this context means back to the preview.

However there is an argument that it could/should close the UI entirely. Perhaps this is one to trial in a PR and see how it feels?

Also note there is no way for keyboard users to close the UI at all. This has been highlighted by a11y team members several times and so this lends weight to the `Cancel = Close` idea. Alternatively we could come up with standardised UI to close the popover but that's been rejected in the past for various reasons.

**Comment by richtabor** [comment]
> Perhaps this is one to trial in a PR and see how it feels?

I think it's worth a shot. 

> Also note there is no way for keyboard users to close the UI at all. 

Nice win. 
>  Alternatively we could come up with standardised UI to close the popover but that's been rejected in the past for various reasons.

We're settling on `Cancel` / `Action`, where the cancel action does close the popover/modal. 

<img width="179" alt="CleanShot 2023-07-27 at 20 50 25" src="https://github.com/WordPress/gutenberg/assets/1813435/ce5247c9-21d2-444d-a514-43935fd3acbe">
<img width="202" alt="CleanShot 2023-07-27 at 20 50 04" src="https://github.com/WordPress/gutenberg/assets/1813435/591f45ff-dc3f-49ba-a0af-857980d56875">

**Comment by richtabor** [comment]
Closing. It's fine as is.
