### ISSUE TITLE
Cannot add link to Template part if it contains a Navigation block.

### ISSUE THREAD

**Issue by jordesign** [WordPress/gutenberg#53086]
### Description

When editing a Template Part that contains a Navigation block - I'm unable to add a link to other text (in a paragraph or heading etc) within the Template Part.

I found I was still able to add links to text within Template parts that do _not_ contain a navigation block.

### Step-by-step reproduction instructions

1. Open the Site Editor > Patterns
2. Open a Template Part that contains navigation block.
3. Insert some text in a paragraph or heading
4. Select text and try and add a link

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/1842363/cacb07e0-08f0-4bba-844d-316994eb7fb8

### Environment info

WP6.3 RC3
No plugins
TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by tellthemachines** [comment]
I can reproduce this in 6.3 RC2 and Gutenberg trunk and can confirm it's a regression from 6.2.2.

**Comment by draganescu** [comment]
Did a bisect and found the problem appeared after #52899 
Also to add context to this issue:

- the problem only happens if a link is added to an existing text in the template part
- if one paragraph is added linking works for all exisiting text

**Comment by Mamaduka** [comment]
Odd, I'm seeing a different behavior. I couldn't open the link control when I added a new paragraph.

I can also reproduce the issue without the Gutenberg plugin. The #52899 hasn't been cherry-picked for RCs.

**Comment by getdave** [comment]
> The #52899 hasn't been cherry-picked for RCs.

That's cos it didn't have the label.

**Comment by Mamaduka** [comment]
What I mean is that I don't think #52899 is a cause of the bug. You can test WP 6.3 RC2 without a plugin and reproduce the issue.

**Comment by draganescu** [comment]
The cause is not the code in that PR. The cause is that the PR makes the navigation rendering work and when it works we have a double slot available for link UI and it does not know where to render. 

The best bet is to try and simplify how the navigation is rendered in the site editor sidebar.

**Comment by Mamaduka** [comment]
My `bisect` run points to this commit fca4289; you can check out the commit before c64bee4539, and the feature works.

**Comment by getdave** [comment]
I believe the Issue is that we have x2 `<BlockTools>` instances in the React Tree. 

https://github.com/WordPress/gutenberg/blob/27b117bbcd76191b620fc1a19d9132430a905df8/packages/edit-site/src/components/sidebar-navigation-screen-navigation-menus/navigation-menu-content.js#L109-L111

https://github.com/WordPress/gutenberg/blob/27b117bbcd76191b620fc1a19d9132430a905df8/packages/edit-site/src/components/block-editor/site-editor-canvas.js#L110

The former is then being rendered into by default by the rich text LinkControl:

https://github.com/WordPress/gutenberg/blob/27b117bbcd76191b620fc1a19d9132430a905df8/packages/format-library/src/link/inline.js#L253-L262

You can verify this by removing the following 3 lines of code completely:

https://github.com/WordPress/gutenberg/blob/27b117bbcd76191b620fc1a19d9132430a905df8/packages/edit-site/src/components/sidebar-navigation-screen-navigation-menus/navigation-menu-content.js#L109-L111

The problem is now the Navigation won't render in the sidebar because `<BlockList>` is gone.

However if you reinstate just the `<BlockList>` the Navigation still won't render. Why? Because inside of `<BlockList>` we end up rendering conditionally based on `<BlockListBackCompat>`:

https://github.com/WordPress/gutenberg/blob/27b117bbcd76191b620fc1a19d9132430a905df8/packages/block-editor/src/components/block-list/index.js#L130-L134

That in turn renders conditionally based on `<InsertionPoint>`:

https://github.com/WordPress/gutenberg/blob/27b117bbcd76191b620fc1a19d9132430a905df8/packages/block-editor/src/components/block-tools/back-compat.js#L30-L33

...and finally `InsertionPoint` ends up returning `null` based on this check:

https://github.com/WordPress/gutenberg/blob/27b117bbcd76191b620fc1a19d9132430a905df8/packages/block-editor/src/components/block-tools/insertion-point.js#L219-L226

This is because there is no `rootClientId` on the `blockInsertionPoint` object returning from the `getBlockInsertionPoint` selector.

If we can decouple that then we should be ok to render `<BlockList>` without the `<BlockTools>` wrapper which will solve our issue 🤞 

`getBlockCount( blockInsertionPoint?.rootClientId ) === 0` as a proxy for "block list is empty" is the issue.

**Comment by getdave** [comment]
This PR https://github.com/WordPress/gutenberg/pull/53115 "fixes" the Issue at the cost removing the `BlockToolsBackCompat` component which was scheduled to be removed in 6.3 anyway

https://github.com/WordPress/gutenberg/blob/429f83474feec55767a98b7d497e2c0e2de38ad0/packages/block-editor/src/components/block-tools/back-compat.js#L23-L27

It just removes `<BlockTool>` and because we've removed `BlockToolsBackCompat` the content renders. More detail above.
