### ISSUE TITLE
The in-between inserter doesn't appear when the last child block is selected

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/gutenberg#53315]
### Description

Coming from https://github.com/WordPress/gutenberg/issues/47200#issuecomment-1664652058 

The inserter does appear in Galleries, even when an image is selected. However, it does not appear when the last image is selected.

### Step-by-step reproduction instructions

1. Create a galley
2. Insert images
3. Select the last image
4. The inserter does not show up on the left and top of the images

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/17861443/f761ee20-fe97-4a5c-82cb-d75b2add2209

### Environment info

- WP 6.3-RC3-56344
- GB 16.3

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Thanks for opening this! Looks like a straight forward dev task to dive into. Added to the Polish board :)

**Comment by hanneslsm** [comment]
We must consider what happens if there is only one image in the gallery. Probably nothing, but if we find a solution it could fix https://github.com/WordPress/gutenberg/issues/50021

**Comment by Mamaduka** [comment]
I believe this issue isn't limited to the Gallery block; I can reproduce the same bug with Buttons and Columns.

As far as I can tell, `useInBetweenInserter` returns early due to this condition:

https://github.com/WordPress/gutenberg/blob/02dc8864c632d0127072993cb10006d6c002d84b/packages/block-editor/src/components/block-list/use-in-between-inserter.js#L132-L136

cc @ellatrix, @talldan

## Steps to reproduce
1. Open a post or page.
2. Insert Buttons or Column blocks with at least three inner blocks.
3. Select the last block.
4. Try enabling in-between inserter. See the screencast.

## Screencast

https://github.com/WordPress/gutenberg/assets/240569/96298207-ebf6-40eb-9fa5-f4cadcf78e4e

**Comment by talldan** [comment]
> I believe this issue isn't limited to the Gallery block; I can reproduce the same bug with Buttons and Columns.

> As far as I can tell, useInBetweenInserter returns early due to this condition:

Good find, that stops the in-between inserter from showing under the toolbar in vertical block lists, but it wouldn't be an issue for horizontal block lists. There could be some kind of additional logic added to that if statement.
