### ISSUE TITLE
Style Book: Integrate patterns

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#53437]
While styling globally you can observe your changes applied to the current document, or the full catalog of individual blocks by opening the Style Book. A missing piece here is a high level view of how global style edits affect patterns. 

In this issue lets explore how Style Book might be expanded to include patterns as well as blocks.

**Comment by carolinan** [comment]
Perhaps the most used user created patterns could be added to a new Patterns tab.

**Comment by richtabor** [comment]
I'm not thinking patterns and style book should be conflated. 

Both are already complex individually, and with https://github.com/WordPress/gutenberg/pull/65619 these would exist at the same level of the site editor navigation hierarchy, which is likely to be an easier (and more familiar) way to review patterns, rather than integrate them into style book.

**Comment by richtabor** [comment]
Closing this as non-planned currently. Perhaps we'll pick it up one day.
