### ISSUE TITLE
Style Revisions: return to Site Browser when style revisions were entered from that location.

### ISSUE THREAD

**Issue by jordesign** [WordPress/gutenberg#53616]
## What problem does this address?

When entering the Style Revisions from the Site Browser, and then closing them again, I expect to be returned to the Site Browser. Instead I find myself in the Index/Blog template in editing mode.

https://github.com/WordPress/gutenberg/assets/1842363/ecf9d194-93dd-47f1-a94b-e460a878f5f3

## What is your proposed solution?

Is there a way to remember the entry point to Style Revisions and return to that state when closing/accepting revisions?

**Comment by annezazu** [comment]
Hmm I'm torn about this as I could see it causing more confusion than clarity, particularly since this wouldn't happen any other time you explicitly click into the edit view (which is what's happening when you click on style revisions). It's not a good interaction to start going down since we're doing a lot to differentiate the two, offering a high level setup with Site View and a more detailed/robust setup with Edit View. Curious for @WordPress/gutenberg-design's thoughts.

**Comment by jasmussen** [comment]
I go both ways on that one, the flow as suggested is definitely not ideal.

But I also think it touches on a larger issue with how Global Styles are currently taking you into the edit view, wheras arguably you could stay in site view the whole time. If that were to happen (@jameskoster I think there was an issue where you mocked this up) this issue would be addressed as part of that.

**Comment by jameskoster** [comment]
Agreed. I see this as part of the 'Interface' improvements on the Global Styles roadmap (https://github.com/WordPress/gutenberg/issues/41232).

**Comment by jordesign** [comment]
If that's tracked elsewhere - then I'm happy with that. 😄 Happy for this to be closed and handled as part of the broader Global Styles work.
