### ISSUE TITLE
Crash when trying to type something in commands after editing blocks

### ISSUE THREAD

**Issue by okmttdhr** [WordPress/gutenberg#53863]
### Description

The Site Editor crashes when trying to type something in commands after editing blocks. You'll see the black screen. See the instructions below.

### Step-by-step reproduction instructions

1. Go to the Site Editor
2. Edit some blocks, such as changing the text, adding a block, and moving a block
3. Open commands 
<img width="1358" alt="Screen Shot 2023-08-22 at 13 46 49" src="https://github.com/WordPress/gutenberg/assets/5287479/6ac53c56-e52a-4fae-89ee-12afe7f3da2b">

4. Start tying and see the crash
[![Image from Gyazo](https://i.gyazo.com/65223a0e3459e61f6a38cde170840387.gif)](https://gyazo.com/65223a0e3459e61f6a38cde170840387)

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/5287479/3826ae6e-2d16-40bd-9dbb-62bd4ad37cc9

### Environment info

- Gutenberg v16.5.0-rc.1
- WordPress 6.3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### Related 

- https://github.com/WordPress/gutenberg/issues/53633

**Comment by ntsekouras** [comment]
👋 I can't reproduce.. Can you share a bit more info on the reproduction steps or share a small video? Thanks!

**Comment by okmttdhr** [comment]
Hi, @ntsekouras! I included the video in the description and note that this only happens on v16.5.0-rc.1. 
I am aware that _sometimes_ the crash does not happen, and not sure what the cause is exactly.

**Comment by liviopv** [comment]
I ran into this and ended up creating a duplicate in #53898

What I found:

- It's present in 16.5 stable, so it's out in the wild now.
- Only happens if the Command Palette is triggered when a block is selected. Triggering it without selecting any block works.
- Only happens in the Site Editor, the Post/Page Editor is fine
- The console logs:

```
Uncaught TypeError: Cannot read properties of null (reading 'toString')
    at index.js:261:14
    at Array.map (<anonymous>)
    at AI (index.js:249:4)
    at un (command-menu.js:36:39)
    at St (react-dom.min.js?ver=18:1:47627)
    at $s (react-dom.min.js?ver=18:1:120574)
    at Sl (react-dom.min.js?ver=18:1:88649)
    at kl (react-dom.min.js?ver=18:1:88577)
    at bl (react-dom.min.js?ver=18:1:88440)
    at sl (react-dom.min.js?ver=18:1:85264)
```


https://github.com/WordPress/gutenberg/assets/14153300/c2b1e403-9a7f-4b36-b8e9-fc10fc61b498

**Comment by jordesign** [comment]
Tested and confirmed in WP6.3 and GB16.5

**Comment by liviopv** [comment]
~Only happens in the Site Editor, the Post/Page Editor is fine~

I tested again and I was able to reproduce it in the Post Editor as well:


https://github.com/WordPress/gutenberg/assets/14153300/cd920b06-d5ad-4d88-a45b-ba9d2290bf68

```
TypeError: Cannot read properties of null (reading 'toString')
    at http://localivio.local/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=af7c44e3d3ac232a7bfc:145:63
    at Array.map (<anonymous>)
    at AI (http://localivio.local/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=af7c44e3d3ac232a7bfc:143:1361)
    at un (http://localivio.local/wp-content/plugins/gutenberg/build/commands/index.min.js?ver=837a8c80dd33e3db66e1:1:42581)
    at St (http://localivio.local/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:47627)
    at $s (http://localivio.local/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:120574)
    at Sl (http://localivio.local/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:88649)
    at kl (http://localivio.local/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:88577)
    at bl (http://localivio.local/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:88440)
    at sl (http://localivio.local/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:85264)

```

**Comment by draganescu** [comment]
I can repro with the latest releases but I can't repro on Gutenberg trunk. The error clearly comes from the block commands hook but unclear as to why so far.

**Comment by draganescu** [comment]
I cannot reproduce this w/ trunk no matter what I do. The code that seems to trigger the error 

https://github.com/WordPress/gutenberg/pull/52509/files#diff-a768f5465e6bc9bcf20a278d4bc127f719d2d3c2d6f2eb633c71cf787167a853R258

seems all right since it's never supposed to be null or undefined being in a map on an array with hardcoded values.

**Comment by annezazu** [comment]
FYI to @tellthemachines and @ramonjd for 6.3.2 possible inclusion!

**Comment by t-hamano** [comment]
Interesting, I found the cause. This problem can be reproduced by _building_ the latest trunk 😅

This is probably due to the fact that the callback value of the array is compressed by the build and the `callback.name` cannot be retrieved correctly at the point mentioned by @draganescu.

https://github.com/WordPress/gutenberg/blob/2aa67f6d8d6eb2175266403707e8f0e970f0a8ee/packages/block-editor/src/components/use-block-commands/index.js#L250-L252

![callback](https://github.com/WordPress/gutenberg/assets/54422211/f9e36f20-46ee-42a5-a759-7609ede40452)

Furthermore, since command labels are generated by the `replace` method, there will be localization problems.

Either way, #52509, to which this issue relates, is part of Gutenberg 16.5 and does not ship with WordPress 6.3, so I think it can be excluded from the 6.3.x editor task.
