### ISSUE TITLE
Allow /h2 /h3 ... for the creation of the proper header block

### ISSUE THREAD

**Issue by tkapler** [WordPress/gutenberg#53963]
## What problem does this address?
I often need to make header with other level then default H2. But it takes too much steps and or even switching from keyboard to mouse to do it.

## What is your proposed solution?
Simply allow /h1-/h6 shortcuts, that would directly create header with proper level.

**Comment by Mamaduka** [comment]
You should already be able to do that. Try typing `/h3` and then hit the <kbd>Enter</kbd>. See #26597.

**Comment by spencerfinnell** [comment]
Perhaps @tkapler was referring to a flow that more similarly mirrors how embeds are handled. If you type `/reddit` you get actual confirmation that it is a real block because the variation of the Embed block shows up in the suggestions: 

<img width="391" alt="Screenshot 2023-08-26 at 4 11 52 PM" src="https://github.com/WordPress/gutenberg/assets/491124/13d2bec2-fcec-455f-a19d-37dcd9819f26">

Showing the different heading levels in the suggestions would give users confidence that there actually _is_ a shortcut direct to a heading level instead of having the user _guess_ that pressing enter will use the variation.

Normal behavior of pressing enter when there are no block suggestions is to just go to a new paragraph, because supposedly you are "just typing" at that point. If you happen to be typing `/h3` and pressing Enter you get a different experience.

![Screen Capture on 2023-08-26 at 16-15-28](https://github.com/WordPress/gutenberg/assets/491124/071170a9-e71c-41f9-a4cc-bafa5aee31fc)

I certainly think the existing behavior is fine to keep but it makes a lot of sense to me to show the suggestions prior to pressing Enter as well.

**Comment by spencerfinnell** [comment]
I believe discussion can be continued in the original: https://github.com/WordPress/gutenberg/issues/32472

**Comment by tkapler** [comment]
> You should already be able to do that. Try typing `/h3` and then hit the Enter. See #26597.

what? i have never noticed that. It does not show any indication that it will do anything. You can mark it as closed then, but i believe it should be shown somehow, at least keep showing "header".
