### ISSUE TITLE
Remove "justify" option from List block

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#540]
Core has removed this item from the formatting bar.

**Comment by iseulde** [comment]
Shouldn't alignment be removed entirely from this one?

**Comment by mtias** [comment]
We were talking with @jasmussen that it may make sense to retain the left/right/center. But I'm not sure. What are your reasons for removing all of them?

**Comment by iseulde** [comment]
Aligning a list block feels odd, but maybe that's just me. :) Have no strong opinion.

**Comment by mtias** [comment]
@jasmussen @annaephox any thoughts on this?

**Comment by jasmussen** [comment]
In general I lean towards _starting out opinionated and minimalist_, and adding back as needed. I'm also leaning towards alignments, especially center alignment, not making any sense for lists. There's a use case for RTL languages that you brought up Matías, but I think we might want to mimic what the editor does currently. There's also #138. All of this leads me to lean towards wanting to remove alignments. 

However I'm not rigid on this.

**Comment by mtias** [comment]
Let's start with no alignment then.

**Comment by joyously** [comment]
If the alignment is for float, not text, it makes sense to apply it to the block itself, not the list items. Someone might want to float each list item to make a menu, but that's more advanced.

For text alignments, I can see people using it for the whole block, but I really don't like centered lists and don't want to encourage their use. They could use individual lines instead of a list and get the same thing(maybe, if the line-height was cooperative). The same for text aligning the list items (each one different or something).

**Comment by jasmussen** [comment]
> If the alignment is for float, not text, it makes sense to apply it to the block itself, not the list items. Someone might want to float each list item to make a menu, but that's more advanced.

Yep, I'm thinking of this as a feature to build later in the year for the customization focus. #427

**Comment by jasmussen** [comment]
Not seeing in master, so closing!
