### ISSUE TITLE
Inline rules in common.css overrule the sibling rules for adjacent blocks

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/gutenberg#54010]
### Description

In the Post Content, each block which follows another block is assigned a `margin-block-start` rule via `:where(body .is-layout-constrained) > *`. However, rules in common.css (like the following example) override this rule.

```
.wp-block-image {
    margin: 0 0 1em;
}
```

…also…

```
:where(figure) {
    margin: 0 0 1em;
}
```

<img width="780" alt="Screenshot 2023-08-29 at 09 50 15" src="https://github.com/WordPress/gutenberg/assets/1571592/40c0cf0e-f7b3-4a8d-aeb0-b19173645d47">

### Step-by-step reproduction instructions

See the screenshot above.

### Environment info

WordPress 6.3, any theme. Brave Browser on OSX.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report, but I could not reproduce it.

I think layout styles via global inline styles are output after `common.css`. Since both have zero Specificity, the later layout style should take precedence.

Does this issue reproduce in the default theme?

![image](https://github.com/WordPress/gutenberg/assets/54422211/b3e128ff-5e13-4982-8fdc-117955b879f5)

**Comment by markhowellsmead** [comment]
It doesn't, no. The custom theme doesn't load any custom CSS though.
I've been able to track down the problem to an explicit declaration `add_theme_support('wp-block-styles');` in the theme. These rules appear to be too strong, so I've removed them, as they break the block editor rules.
