### ISSUE TITLE
Quick pattern inserter doesn't include synced patterns or template parts

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#54180]
When editing a template in the Site Editor, if the quick inserter is invoked from the document root it will display patterns:

<img width="446" alt="Screenshot 2023-09-05 at 10 02 40" src="https://github.com/WordPress/gutenberg/assets/846565/e7b173e8-b5ee-43da-aa1a-09f3cb8b48dc">

However this only seems to include _unsynced_ patterns. It's not possible to view synced patterns or template parts here – even when searching – which seems like an oversight.

**Comment by glendaviesnz** [comment]
This appears to be fixed by the work being done to merge the inserter pattern tabs. On https://github.com/WordPress/gutenberg/pull/54007 I see the following:
<img width="783" alt="Screenshot 2023-09-07 at 4 06 56 PM" src="https://github.com/WordPress/gutenberg/assets/3629020/94ef6945-e047-4a46-9ef3-f9d9ad5224bd">

We should retest this once the pattern category PRs are merged.

**Comment by glendaviesnz** [comment]
@jameskoster I have retested on trunk and this issue is now fixed.
