### ISSUE TITLE
Backtick -> code replacement fires inconsistently.

### ISSUE THREAD

**Issue by rmccue** [WordPress/gutenberg#5454]
(Using Gutenberg 2.1.0.)

## Issue Overview
When typing, using backticks doesn't consistently replace the text between them with backticks.

## Steps to Reproduce (for bugs)
Unfortunately, I can't reproduce this consistently, as I can't tell exactly what conditions it occurs under. However, roughly:
1. Type into a paragraph block in Gutenberg.
2. Type a backtick character (`)
3. Type some text to convert to code
4. Type another backtick character.

(Using Firefox 59b on macOS 10.12.)

## Expected Behaviour
The text should always be converted to `<code>`

## Current Behaviour
The text is inconsistently converted to `<code>`; it works sometimes, but not others.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by rmccue** [comment]
This also occurs in the middle of the line. My current workaround is to backspace-delete the backtick and retype it, and repeat that until it finally works.

**Comment by mtias** [comment]
There's this issue as well: https://github.com/WordPress/gutenberg/issues/4642

**Comment by designsimply** [comment]
I have not yet experienced backtick-to-code conversion firing inconsistently when testing with a US keyboard layout on macOS 10.13.5. However, I did test with a Swiss German keyboard layout at https://github.com/WordPress/gutenberg/issues/4642#issuecomment-400391670 and found some inconsistencies there. 

@rmccue, I see you were using Firefox 59b on macOS 10.12 when you tested before. Are you still experiencing the problem where backtick-to-code conversion fails sometimes? May I ask what keyboard layout you are using? 

🤔 I want to say the content of the backticks shouldn't matter, but do you think that could be a factor. If yes, and if you happen to think of it, could you post some sample content here next time the problem happens? I could use that to help test!

**Comment by Digiover** [comment]
@youknowriad Thanks. I didn't think issue #8579 is a duplicate. I specifically read through this one, and the steps to reproduce are different as is the current behavior. I can reproduce my issue 100%.

Here's my info, screenshots are in #8579 

### Steps to reproduce

- Type text in a paragraph block
- add the far right backtick first
- add the most left backtick second
- See that there is no HTML `<code>...</code>` markup

### Expected behavior
I would expect HTML-code markup being added to the block.

#### Desktop (please complete the following information):
OS: Fedora release 28 (Twenty Eight)
Browser Chromium
Version 67.0.3396.79 Fedora Project - and Mozilla Firefox for Fedora 61.0.1 (64-bit)

#### Additional context
WordPress version 5.0-alpha-43555, and 4.9.8
Gutenberg version 3.4.0

**Comment by mtias** [comment]
Folding into #5454.

**Comment by rmccue** [comment]
@mtias This *is* #5454, was this rolled into another issue?

**Comment by mtias** [comment]
I'm silly, meant #4642. Hoping after RichText refactor this could be done simpler and solve all the issues together.
