### ISSUE TITLE
Details Block - add controls for spacing

### ISSUE THREAD

**Issue by DanSoschin** [WordPress/gutenberg#54552]
## What problem does this address?
When working with multiple details blocks in succession, it would be nice to have a control for manipulating the spacing (north and south) before and after each details block.

## What is your proposed solution?
Improves someone's ability to manipulate layouts in the editor without having to modify CSS, styles, or custom blocks. Provides a "low code" option for styling this block.

**Comment by hanneslsm** [comment]
This can be done with margins.
You might have to enable the view first.
<img width="293" alt="image" src="https://github.com/WordPress/gutenberg/assets/17861443/56076f4a-01a4-4d58-b60c-5c402ab1413a">
Is this what you were looking for?

**Comment by DanSoschin** [comment]
Is it possible that the Dimension controls are not yet merged/shipped into the P2 blogs? For example, when editing this post: https://make.wordpress.org/project/2023/09/15/wordcamp-us-2023-qa/ >> I do not see those controls.

![Screenshot 2023-09-18 at 8 29 46 AM](https://github.com/WordPress/gutenberg/assets/53192304/e32b7997-c3eb-4cb7-8ae3-01d7dd1ac859)

I only see controls for COLORS and TYPOGRAPHY.

**Comment by felipevelzani** [comment]
@DanSoschin I took a look at the subsite https://make.wordpress.org/project/, and I see it is using version 16.6.0 of Gutenberg. I believe the reason for the issue is that the P2 theme "WordPress.org Breathe" might need to add support to these features on Gutenberg — you might want to check this on #meta, but I don't think this will be simple to do as it is using a classic theme.
