### ISSUE TITLE
Details block: copy and paste not working in summary

### ISSUE THREAD

**Issue by DanSoschin** [WordPress/gutenberg#54550]
## What problem does this address?
Despite trying multiple methods, I cannot paste content into the "visible" portion of the details block. I **can** paste content into the hidden portion.

## What is your proposed solution?
Improves efficiency of the editing experience, especially when working with multiple documents or transposing content from something like a Google doc, etc.

**Comment by richtabor** [comment]
I could replicate this; video for reference:

https://github.com/WordPress/gutenberg/assets/1813435/c2e79bb9-3216-4c94-8c2b-43d2b8bdf062

**Comment by t-hamano** [comment]
This issue is probably related to #53422 and fixed in #54301. On my Windows machine, I couldn't reproduce this problem in Chrome or Firefox.

I would like you to test whether this problem is resolved with the latest trunk on MacOS.

https://github.com/WordPress/gutenberg/assets/54422211/8c7dfe97-32a5-4425-b4df-9c70cae880d9

**Comment by t-hamano** [comment]
Hi @DanSoschin, Is it possible to confirm if this problem is still occurring? If #54301 resolves this issue, then this issue should not reappear in WP6.4 since #54301 is included in WP6.4.

**Comment by DanSoschin** [comment]
Looks good! Tested quickly on a hosted WordPress.com 6.4.1 site, and I can copy/paste as expected.

**Comment by DanSoschin** [comment]
Closing out.
