### ISSUE TITLE
Aside for pullquotes rather than blockquote

### ISSUE THREAD

**Issue by ShinichiNishikawa** [WordPress/gutenberg#5457]
## Issue Overview
Currently, the pull quote block is marked up as `<blockquote>`. I suggest to change it to `<aside>`.

[HTML 5.2 W3C recommendation 4.3.5. The aside element](https://www.w3.org/TR/html52/sections.html#the-aside-element) states as below.

> The element can be used for typographical effects like pull quotes ...

## Steps to Reproduce (for bugs)
1. Create a pull quote block in the editor.
2. See what you get.

Gutenberg Plugin version: 2.3.0

**Comment by SuperGeniusZeb** [comment]
@karmatosed A pullquote is not part of the main content, so it makes perfect sense to use an `<aside>`. There is even an example in the spec that shows it being used this way:

```html
<p>He later joined a large company, continuing on the same work.
<q>I love my job. People ask me what I do for fun when I’m not at
work. But I’m paid to do my hobby, so I never know what to
answer. Some people wonder what they would do if they didn’t have to
work... but I know what I would do, because I was unemployed for a
year, and I filled that time doing exactly what I do now.</q></p>

<aside>
  <q> People ask me what I do for fun when I’m not at work. But I’m
  paid to do my hobby, so I never know what to answer. </q>
</aside>

<p>Of course his work — or should that be hobby? —      isn’t his only passion. He also enjoys other pleasures.</p>
```

Here a `<q>` tag is nested in the `<aside>`, but I would suggest using a nested `<blockquote>` instead, since you can have multiple paragraphs in the Pullquote block.

**Comment by mtias** [comment]
We are using `figure` now for pullquotes.
