### ISSUE TITLE
Pattern inserter: iterate on current experience with categories

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#54620]
I'm not following this recent changes to the pattern inserter (related https://github.com/WordPress/gutenberg/issues/53164). This doesn't quite feel like a step forward as-is. A few questions: 

1. Is the "All pattern types" select a filtering mechanism? I can't tell if patterns are available based on this select, other than the categories changing when selecting the "My patterns" option. 
---
2. What is "All categories"? It competes for comprehension with "All pattern types". Is that all "My Patterns", or only synced patterns, or both? I think they're all synced patterns, as they're using the `synced` purple, but otherwise there is no other connection. 

Edit: I think it may contain _every_ pattern on the site? Not sure how useful this really is; I don't think we need it. 

<img width="649" alt="CleanShot 2023-09-19 at 15 24 12" src="https://github.com/WordPress/gutenberg/assets/1813435/3df38333-66f2-4a1c-9d1c-8573a551a903">

---

5. Why do curated patterns from the pattern directory render, when "Theme patterns" is selected. I would expect that the results would be limited to patterns bundled in the theme. 

<img width="647" alt="CleanShot 2023-09-19 at 15 26 19" src="https://github.com/WordPress/gutenberg/assets/1813435/d5ada219-e0c2-462b-822e-ea453b9bc746">

---

6. Are these in the process of syncing? Also, why not use the same ToggleGroup that is leveraged in Site Editor > Patterns? 

<img width="646" alt="CleanShot 2023-09-19 at 15 27 43" src="https://github.com/WordPress/gutenberg/assets/1813435/042ddcf9-3557-438b-8df4-b9e2149cf448">
<img width="313" alt="CleanShot 2023-09-19 at 15 28 33" src="https://github.com/WordPress/gutenberg/assets/1813435/da7080bd-34b5-44f1-946a-247c1a407662">

---

7. I don't think we need to bring up prominence on the pattern explorer too much yet, especially while it's not an ideal experience. 

<img width="349" alt="CleanShot 2023-09-19 at 15 21 49" src="https://github.com/WordPress/gutenberg/assets/1813435/2827ee9a-5281-41b1-82c0-67515e3d8b29">

8. We need another design pass on the pagination and items count (count should probably be moved up towards the top). 

<img width="295" alt="CleanShot 2023-09-19 at 15 32 54" src="https://github.com/WordPress/gutenberg/assets/1813435/d8e40a57-c077-40b9-b9ad-74de5bd0fe5d">

**Comment by annezazu** [comment]
cc @SaxonF and @jameskoster

**Comment by glendaviesnz** [comment]
> This doesn't quite feel like a step forward as-is

Thanks for the feedback @richtabor. Despite some rough edges on the UI/UX it feels like a big step forward to me as prior to this change there was no way for users to categorise their own patterns and to filter their patterns by these categories - many users had thousands of patterns with no way to group/browse them other than title. Now they can assign multiple categories to each pattern for easier management and discovery in the inserter patterns tab - previously they were all just listed under `My patterns`. Also prior to this change there was a confusing separation between the Patterns tab where a user's `unsycned` patterns were listed, and the Synced patterns tab where all their `synced` patterns were listed, now there is just a single Patterns tab where all can be found regardless of source or sync type. And the final big step forward was the addition of paging for the listing of patterns. Prior to this change every pattern in a given category was displayed at once in the pattern preview tab which had massive performance implications, especially for those users that had thousands of patterns for whom the inserter patterns tab was unusable.

However, this was definitely a `first cut`, and with the significant underlying changes needed to implement the above improvements we had to deprioritise some of the UI/UX work in order to ensure that the most important parts of the new user patterns category functionality was merged in time for the 6.4 beta - with the view that the UI/UX would then be iterated on, and your comments are a useful starting point for that iteration work. Some of the previous design discussions/decisions [can be found here](https://github.com/WordPress/gutenberg/pull/54007). I will wait to hear what @SaxonF and @jameskoster think about the best next steps. 

 > why not use the same ToggleGroup that is leveraged in Site Editor > Patterns?

This was explored, but that toggle group control is currently not responsive so doesn't work in that narrow panel, especially with longer language strings. We didn't have time to refactor that control so a select list was used instead.

**Comment by SaxonF** [comment]
We are working off a branch [here](https://github.com/WordPress/gutenberg/pull/54681)

**Comment by estelaris** [comment]
De-emphasise pattern filters in inserter #54681 has been merged and it addresses the concerns on this PR

**Comment by richtabor** [comment]
> De-emphasise pattern filters in inserter https://github.com/WordPress/gutenberg/pull/54681 has been merged and it addresses the concerns on this PR

Some of them yes, but I can open up individual issues for these as follow-ups:

> We need another design pass on the pagination and items count (count should probably be moved up towards the top).

> I don't think we need to bring up prominence on the pattern explorer too much yet, especially while it's not an ideal experience.
