### ISSUE TITLE
Allow file uploads using drag and drop & add placeholder

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#5462]
WordPress supports a number of image, audio and video filetypes. We have media placeholders for each of those, and you can drag and drop them to upload.

WordPress also supports a number of filetypes that aren't media, such as pdf, doc, and others. See full list here: https://codex.wordpress.org/Uploading_Files

You should be allowed to upload and insert these files using drag and drop from the desktop. For example if you drag and drop `Schedule.pdf` into the editor, you should get a file block, like this:

![file block](https://user-images.githubusercontent.com/1204802/37092872-ae5ebea2-220d-11e8-8178-3bbddd25e195.png)

From that, you could copy the link and paste it over text if you like, to create a normal link:

![file link](https://user-images.githubusercontent.com/1204802/37086482-fa116748-21f7-11e8-91e7-4a94cf3dc5d0.png)

There would also be a placeholder block for files:

![files placeholder](https://user-images.githubusercontent.com/1204802/37086512-059b877e-21f8-11e8-9cc3-ac3c830971d1.png)

**Comment by mrjarbenne** [comment]
Glad this is on the radar. The lack of a "Files" block resulted a few moments of unsuccessfully attempting to insert a file. At first I thought perhaps the "Images" block might play double-duty as a general media upload, but it doesn't allow alternate formats. I eventually opened the Media Library in a separate window to upload a PDF, copied the URL, and then added it as a hyperlink back in the post. This was very cumbersome. If there is an alternate way to do this currently, it wasn't obvious.

**Comment by jasmussen** [comment]
That approach sounds great, thank you @mirka!

**Comment by nb** [comment]
@mirka, the plan looks good. The idea of allowing the user to upload anything and then let them transform the block into a specific one is especially powerful.

If the user specifics a URL, will we download the file or link to it/embed using the external URL?

Do you think we can somehow communicate with Gutenberg that are the allowed filetypes to avoid errors after upload (I would have to upload a 2GB log file to be rejected)? Can we do it? Are there any downsides?

**Comment by mirka** [comment]
I‘m thinking of making the text link part a normal link, and the download button an HTML5 download link. The `download` attribute will be ignored in IE, iOS Safari, and for cross-origin links. In those cases they will just act as a normal links, but I think it’s a good balance between code simplicity and convenience.

![artboard](https://user-images.githubusercontent.com/555336/39871563-3f7bf7e6-54a0-11e8-91c4-d9d37a418308.png)

@nb:

> If the user specifics a URL, will we download the file or link to it/embed using the external URL?

For now I‘m not going to sideload specified URLs, to keep the behavior consistent with audio/video blocks. This means that:

- File blocks with external audio/video URLs will be transformable into audio/video embed blocks, because the current implementation of those blocks accept external URLs as sources (without sideloading).
- File blocks with external image URLs will *not* be transformable into image blocks, because images for image blocks need to be uploaded to the Media Library (at least in the current implementation).

> Do you think we can somehow communicate with Gutenberg that are the allowed filetypes to avoid errors after upload (I would have to upload a 2GB log file to be rejected)? Can we do it? Are there any downsides?

Good point. I looked into this and found that a pre-check and error-messaging enhancement is in the works (#4203). I think we could add a mime type check in there using [get_allowed_mime_types()](https://developer.wordpress.org/reference/functions/get_allowed_mime_types/). I’ll post a separate issue for that.

As for downsides... I feel like it would be much easier for everyone if the REST API in Core could handle it better, like check the headers for Content-Type and Content-Length first and return an error without waiting for the binary transfer to complete. But I guess life is [not that easy](https://stackoverflow.com/questions/31970645/how-to-check-post-request-headers-before-receiving-and-parsing-request-body)!
