### ISSUE TITLE
Consider not having each template be a tab stop when in the Site Editor > Template view.

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#54630]
As part of the [Hallway Hangout on improving accessibility in the Site Editor](https://make.wordpress.org/test/2023/09/14/hallway-hangout-lets-chat-about-improving-accessibility-in-the-site-editor/), @alexstine noted that it might be advantageous to not have each be an individual tab stop. You can hear this discussed [briefly starting at 24:08](https://youtu.be/6N3Au-7jLoE?si=zQ9cx1wtsb3Qi0oU&t=1448). I'm not sure what advantageous there are to the current approach but opening up this issue to get more feedback :)

**Comment by joedolson** [comment]
I think it would be very helpful if the Templates navigation worked as a `tabpanel`. Right now, you have to tab through each template, then select it. At that point, the context changes and focus is placed on the 'Back' button. 

With tabpanel navigation, the entire navigation would be a single tab stop - which makes it much faster to bypass, and there would no longer be a need for the back button, since the template list would stay in place when a template is selected.

**Comment by joedolson** [comment]
Following discussion in an accessibility bug scrub, the templates navigation is not really appropriate for a tabpanel. A tabpanel needs to consist of only two components: the list of tabs, and the content they relate to. However, each template button actually needs to lead to a subselection of template parts and a view of the content related to the template. This makes a tabpanel an inappropriate interface for this tool.
