### ISSUE TITLE
Heading block: vertical orientation missing

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#54673]
Despite support for writingMode being added to the Heading block for 16.7 RC1 https://github.com/WordPress/gutenberg/pull/54351, I'm unable to find it when using 16.7 RC1:

<img width="287" alt="Screen Shot 2023-09-20 at 12 18 29 PM" src="https://github.com/WordPress/gutenberg/assets/26996883/3b74a5e3-baf2-4440-bde4-fd67060dba15">

Opening an issue here to figure out why that might be the case.

**Comment by annezazu** [comment]
cc @carolinan

**Comment by carolinan** [comment]
I can't reproduce this in Gutenberg trunk.
First I want to make sure that the active theme supports writingMode? Because is is opt-in, disabled by default.
if you are using Twenty Twenty-Four, it is enabled.


## Testing Instructions
Activate a block theme.
The writing mode setting is disabled by default; set it to true in theme.json settings > typography > writingMode:

```
	"settings": {
		"typography": {
			"writingMode": true
		}
	}
```

Create a new post or page, and add a heading block.
Enable the vertical text orientation option in the typography panel.
Save and view the front.
Confirm that the text is now vertical in the editor and the front.

Use the block toolbar and set the text alignment to right (ltr) or left (rtl).
Confirm that the text is now "upside down": the first letter in the heading is at the bottom.

**Comment by annezazu** [comment]
Ah! This is completely my mistake. I wasn't using TT4 :) Closing out.
