### ISSUE TITLE
Fonts: saving happens in the background

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#54698]
When saving fonts and trying to replicate this bug https://github.com/WordPress/gutenberg/issues/54568, I noticed that saving happens in the background, making the update button confusing. It's not clear that the save is occurring at all. Using WP 6.3.1 and GB 16.7RC1 with TT3. 

https://github.com/WordPress/gutenberg/assets/26996883/88f48014-4c67-4028-a908-d2ffb4edb99a

_Apologies if this is a duplicate - I swear I wrote about this somewhere already but couldn't find the issue! It could have been on a PR._

**Comment by t-hamano** [comment]
This issue also seems to be discussed in #54601. #54601 is registered as [a Stage 2 tracking issue](https://github.com/WordPress/gutenberg/issues/53307).

This issue seems to be registered as [a Stage 3 tracking issue](https://github.com/WordPress/gutenberg/issues/53926), but it may be a good idea to close this issue and assign #54601 to the appropriate stage.

**Comment by annezazu** [comment]
Closing now. I'm not sure how I missed your issue :D I did a search before opening to no avail. I am surprised to see this as part of stage 3.
