### ISSUE TITLE
Quote alternative style

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#547]
Let's do a stronger, more opinionated design variation for the style 2 to see how it feels. We should also consider dropping the multiple style control and creating a separate block for it. (This occupies the role of `quote-format` that WordPress currently has.)

Example:

![image](https://cloud.githubusercontent.com/assets/548849/25528625/07cef596-2c1f-11e7-8b58-70691683855d.png)

**Comment by joyously** [comment]
Please remember that `blockquote` is just an extended quotation of an external source. It can have all sorts of different HTML, not just `p` tags, which means that centering is a bad idea. Centering is so difficult to read that it should not be encouraged by the editor.

**Comment by jasmussen** [comment]
Absolutely, this issue would be for a separate block that's meant to be decorative. It would not be the standard quote.

**Comment by jasmussen** [comment]
The following design is for a separate pullquote block. This allowed me to add a "background image" option to the toolbar. The gray color is form the dimming overlay that will dim the background image if applied. Or just stand on its own as a solid color. The specific design might need to be polished a bit in implementation as we see various quotes applied to it, but the ingredients —  a bold quote and a citation field — are there. 

Placeholder:

![pullquote placeholder](https://cloud.githubusercontent.com/assets/1204802/25576212/8560406a-2e5d-11e7-924e-8ec4361f162f.png)

Filled out:

![pullquote](https://cloud.githubusercontent.com/assets/1204802/25576218/8b4ad576-2e5d-11e7-99d6-738205ac2243.png)

Selected:

![pullquote selected](https://cloud.githubusercontent.com/assets/1204802/25576222/8eda2c6e-2e5d-11e7-9b5f-3c859eab7420.png)

Because this assumes a separate block, I experimentally removed the alignment controls, so this block is always full-width. But that fact is not gospel, but rather a subject to discuss: does a separate pullquote block intended to replace the quote post format need alignments?

Here's a mockup that assumes it's the same quote block, but in "Style 2":

![pullquote style 2](https://cloud.githubusercontent.com/assets/1204802/25576322/3a6c288e-2e5e-11e7-9a1c-0e80777f1127.png)

**Comment by karmatosed** [comment]
We should be cautious of capitalisation due to those that have reading complications. Can we be opinionated whilst in normal case? Its not a good thing we are changing this to uppercase.

**Comment by mtias** [comment]
Definitely.

**Comment by rileybrook** [comment]
> Does a separate pullquote block intended to replace the quote post format need alignments?

Providing the same alignment options as the regular image block could provide more visual design options within a post, and a more creative user experience.

**Comment by jasmussen** [comment]
Here are new mockups, based on discussion here. 

1. Placeholder:

![pullquote placeholder](https://cloud.githubusercontent.com/assets/1204802/25659210/08e48a2c-3007-11e7-81df-5567accac474.png)

2. Neutral

![pullquote neutral](https://cloud.githubusercontent.com/assets/1204802/25659219/100c9402-3007-11e7-9f9b-c8fc35afe137.png)

3. Selected

![pullquote selected](https://cloud.githubusercontent.com/assets/1204802/25659230/1542e16a-3007-11e7-8526-1ebb3dca4bec.png)

Simple. No background. No caps. Big bold text that's centered. Same-as-image alignments. Only one style, which the theme will provide. CC: @mkaz

**Comment by karmatosed** [comment]
@jasmussen awesome, that works really well I think.

**Comment by jasmussen** [comment]
Since this is merged, I'm closing as fixed!
