### ISSUE TITLE
Font library: add support for detailed error messaging in API and UI

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/gutenberg#54777]
### Description

The current implementation of API doesn't return detailed error when a font upload fails. Because of this reason, it is not possible to show appropriate error message in the UI.

Return detailed error messages from the API.

### Step-by-step reproduction instructions

Try uploading a `.otf` file, and observe that API doesn't return any relevant error message or type.

### Environment info

- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by properlypurple** [comment]
I was able to reproduce this on WP 6.4-alpha-56670, with Gutenberg 16.7.0-rc.1. The screenshot below shows a toast saying `Error inserting fonts`, but it's in the layer below the fonts modal, and is not very visible.

![Screenshot from 2023-09-25 16-19-13](https://github.com/WordPress/gutenberg/assets/40858144/7bec59f3-4529-498c-8793-e376914f3612)

**Comment by madhusudhand** [comment]
@jasmussen can you suggest error messaging designs and message copy for the following scenarios.

1. All selected files uploaded successfully. (It shows `Upload successful` message and no designs required)
2. All uploads might have failed.
3. Only part of the uploads are failed (for the following reasons)

Failure reasons:

* Unsupported file extensions (ex: .txt, .svg)
* Invalid mime type (ex: a text file is given .ttf file extension, but mime isn't a font)
* User missing permissions to upload
* No write access on WP server
* Selected list of fonts are duplicated of already installed fonts
* Could be due to some bug/exception in the code.

**Comment by jasmussen** [comment]
Sure. For the time being, I would keep these as [notices](https://wordpress.github.io/gutenberg/?path=/docs/components-notice--docs), right below the gray upload box. I would keep them all at the yellow warning level, unless it's an upload successful, then it can be green. As noted elsewhere, in the future we should redirect to the uploaded font in the Library tab instead of showing the green notice.

Please note that many of these messages are also to be found in the `packages/media-utils/src/utils/upload-media.js` file and others. In general all these messages should be the same, regardless of whether it's for fonts or images. If you know of other places where error messages live, and that place has copy that can work for you better than my suggestions here, please use those instead. Use the below suggestions only if the precise use case isn't shown. CC: @Mamaduka in case he has insights here.

Failure copy suggestions:

> All selected files uploaded successfully. (It shows Upload successful message and no designs required)

"Upload successful".

> All uploads might have failed.

"Upload failed".

> Unsupported file extensions (ex: .txt, .svg)

"Sorry, you are not allowed to upload this file type." 

> Invalid mime type (ex: a text file is given .ttf file extension, but mime isn't a font)

"Sorry, you are not allowed to upload this file type." 

> **User** missing permissions to upload

"Sorry, you do not have permission to upload."

> No write access on WP server

"Sorry, WordPress does not have permission to upload."

> Selected list of fonts are duplicated of already installed fonts

Question, do we simply omit the duplicated fonts and upload any variants that are missing?

In that case, "Upload successful." — no reason to call this out, IMO.

> Could be due to some bug/exception in the code.

"Upload failed."

**Comment by Mamaduka** [comment]
I believe beside media upload util the remaining failure/validation errors are from server. Generally the [`_wp_handle_upload`](https://developer.wordpress.org/reference/functions/_wp_handle_upload/) method handles media uploads in core.

**Comment by annezazu** [comment]
Pulling [this feedback from the FSE Outreach Program](https://make.wordpress.org/test/2023/09/18/fse-program-testing-call-26-final-touches/#comment-3177) as these concerns are coming up there:

>I tried to upload a .zip on purpose but got no errors. It may be nice to have or suggest allowed font formats and a confirmation notification when one gets uploaded.

[Another piece of feedback](https://make.wordpress.org/test/2023/09/18/fse-program-testing-call-26-final-touches/#comment-3178) on this note from the same call for testing:

>Went to fonts.google.com and downloaded Fuggles.zip. It looks like I have to unzip the folder and then upload the Fuggles-Regular.ttf font file.

Proper error messaging would go along way, perhaps along with an "allowed file type" note.

**Comment by jasmussen** [comment]
I want to direct attention back to [the initial mockups](https://github.com/WordPress/gutenberg/issues/45271), which currently look like this:

<img width="1440" alt="Overview" src="https://github.com/WordPress/gutenberg/assets/1204802/7c801994-a4e6-4a96-91eb-5787c4ae74f7">

Note here the message below the Upload dropzone that says:

> Uploaded fonts will appear up in your library and can be used in your theme after that. Formats .ttf, .woff, and .woff2 are supported.

I believe the separate upload tab is still being developed in a separate PR, so I'm sharing this mostly as a note to remember to go back to the mockups, a lot of detail is captured there.

That said, I wouldn't mind if it were possible to include the extension information in the upload notice as well. So potentially something like:

> Sorry, you are not allowed to upload this file type. Formats `.ttf`, `.woff`, and `.woff2` are supported.

**Comment by hanneslsm** [comment]
> Failure copy suggestions:
>> All selected files uploaded successfully. (It shows Upload successful message and no designs required)
> "Upload successful".

I find the messages too nondescriptive.
This post has excellent examples for better error messages: https://www.thegiggal.com/ux-writing-error-messages/
It'd be wonderful if we could at least include some of the points: 
> What happened, Reassurance, What happened and why, Help fix it, Give a way out.
![image](https://github.com/WordPress/gutenberg/assets/17861443/a994e218-3b9b-4c0a-9a84-fdf11228423e)

**Comment by hanneslsm** [comment]
Also noting that in the current implementation the error messages disappear automatically after a few secs. This shouldn't happen.

**Comment by creativecoder** [comment]
I think error messages have been generally improved since the REST API updates and refactor in Jan. Can we close this one?

**Comment by madhusudhand** [comment]
Error messaging improved in latest releases and closing this as it is no longer applicable.
