### ISSUE TITLE
Font Library: indicate an error is occurring when connecting to google fails

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#54798]
In trying to connect to google using WP 6.3.1 and GB 16.7 RC2, I am seeing 500 errors in the console and the Google fonts connection endlessly loading:

<img width="1507" alt="Screenshot 2023-09-25 at 9 57 00 AM" src="https://github.com/WordPress/gutenberg/assets/26996883/674e5d55-4e26-4c5e-8f94-6e03ee19f6ab">

In this case, nothing in the interface is indicating to me that an error has occurred (and I'm not quite sure what is even going on). At the least, we should reflect an error has happened in the interface.

**Comment by matiasbenedetto** [comment]
The problem was this: Gutenberg 16.7 RC2 uses a URL for font collections that was removed temporally. I restored the test URL because this change to a permanent wporg CDN URL (https://github.com/WordPress/gutenberg/pull/54795) didn't make it to 16.7 RC2. It should work as expected now that the provisory URL is again online. 

~~I'm closing this ticket; please re-open it if the list still doesn't show.~~

**Comment by matiasbenedetto** [comment]
Apart from the particular error, I agree with you that we would need to display an error message in the frontend if the backend failed to load the font collection data.

Thanks for reporting this :)
