### ISSUE TITLE
Improve documentation for deprecated wp.editor.RichText.Content

### ISSUE THREAD

**Issue by 0xTanzim** [WordPress/gutenberg#54815]
### Description

The documentation for the wp.editor.RichText component should be updated to reflect that it is deprecated and should be replaced with wp.blockEditor.RichText.

Steps to reproduce:

Go to the WordPress documentation page for the wp.editor.RichText component.
Scroll down to the section titled "Usage".
Note that the documentation says to use const { RichText } = wp.editor;.
Expected behavior:

The documentation should say to use const { RichText } = wp.blockEditor; instead.

Actual behavior:

The documentation says to use const { RichText } = wp.editor;.

### Step-by-step reproduction instructions

gutenberg/packages/block-editor/src/components/rich-text

Go to the WordPress documentation page for the wp.editor.RichText component.  
Scroll down to the section titled "Usage".
Note that the documentation says to use const { RichText } = wp.editor;.

### Screenshots, screen recording, code snippet

![issue2](https://github.com/WordPress/gutenberg/assets/60542516/97459791-e3be-40e9-959a-9c7c66cc6349)

### Environment info

I have been using a late version of WordPress. 6.3
I use the chrome browser. Desktop. Windows 11Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by waviaei** [comment]
> gutenberg/packages/block-editor/src/components/rich-text
> 
> Go to the WordPress documentation page for the wp.editor.RichText component.
> Scroll down to the section titled "Usage".
> Note that the documentation says to use const { RichText } = wp.editor;.

Checking at the document https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/rich-text/README.md

I could no longer find the section "Usage", and the usage example which uses `const { RichText } = wp.editor;.`

Looking at the log, this has been fixed in #55841 on Nov 3, after this issue was created.
https://github.com/WordPress/gutenberg/commit/24bf989b08220d25d9244ced45a221fe3b2dd2a8#diff-c7f1fa97855ed23061eacc8c8fe0771c34d049f5ced0fbc10f2eb4aa43c23643

Then, vanilla JS example has been removed all together at #56121 

So I think we can mark this issue as resolved and close it!

**Comment by t-hamano** [comment]
@TanzimHossain2 Thanks for the report.

As mentioned in the previous comment, I would like to close this problem because there is no longer a string called `const { RichText } = wp.editor;`.
