### ISSUE TITLE
Tracking issue: 6.4 Featurettes 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#54810]
**Due date: Nov 7**

As part of efforts for the 6.4 release and related assets, this is a tracking issue to cover the work needed for the 6.4 featurettes. Pulling from the highlight grid work being tracked here https://github.com/WordPress/gutenberg/issues/54808, these are short and sweet videos focused in depth on one feature rather than an entire release video. Here's an example from the last release looking at a [reimagined Site Editor experience](https://twitter.com/WordPress/status/1643324170976067586). They should ideally be 30s to 60s, square in format so they work for reels and social media, and focus on no more than one feature, unless there's a feature set that might work well to show 1-3 items quickly. Let's use this issue to collaborate and share progress.

**Comment by jasmussen** [comment]
For these featurettes, and so that they work across social media and potentially the microsite, I spent a little time using [Screen Studio](https://www.screen.studio) to try and put together a concept for how these could look, here:

https://github.com/WordPress/gutenberg/assets/1204802/9a8adf80-d0d2-412c-8b1a-32b66a7ea428

* The videos are high resolution, and can be subsequently optimized with ffmpeg when we're happy with them.
* The videos are square, but feature some zooming for clarity on particular aspects of a feature. This works well for social media, and for reels, but can also work embedded on a website
* The browser inside is recorded in a 4:3 aspect ratio.

Note that the video content shown here is meant as an example, I'd like to take a stab with a new script that puts a bit less emphasis on the footnote block support, and perhaps more on the group background support. 

But as a format for the collection of featurettes in this round, I think this can work.

**Comment by jasmussen** [comment]
Here's a new version of the Design Tools featurette. Barring any feedback, content-wise I think this one is done, since it captures all the new stuff from Group backgrounds over footnote support and aspect ratio for placeholders.

https://github.com/WordPress/gutenberg/assets/1204802/3e2e1f64-f23b-4c0e-b07b-1a8f236da2d7

I'll move on to writing flow next.

**Comment by jasmussen** [comment]
Here's a tentative featurette for Writing Flow. Give or take any feedback, I think this one is pretty solid too.

https://github.com/WordPress/gutenberg/assets/1204802/de6f3131-950b-481b-afd6-05fd1787065a

**Comment by richtabor** [comment]
Perhaps reducing the speed of zoom will keep it smooth/less jumpy.

**Comment by jasmussen** [comment]
Ah, good notes! I will take a pass at that for both.

**Comment by rmartinezduque** [comment]
They look great, @jasmussen! I agree with Rich on making the zoom a bit smoother if possible. In the second video (writing flow), particularly at the 0:20 mark, I also noticed the pause feels a bit longer than usual (not sure if this is on purpose). As for the last improvement highlighted (the ability to merge consecutive lists), I wonder if there would be a way to make it more obvious. I was not sure whether to look at List View or the lists themselves in the content, and struggled a bit to quickly realize that they had been merged.

**Comment by annezazu** [comment]
Looks solid to me for writing improvements. The only thing that might be fun to sneak in is the [Link Control: Add “Open in new tab” control into the link preview](https://github.com/WordPress/gutenberg/pull/53566), making it easier to turn on and off that option. It's a big part of writing flow experiences and I know has gotten a fair amount of feedback in the last release cycle.

**Comment by jasmussen** [comment]
Good feedback all around. I managed to find the zoom speed and set it as slow as I could, and that works well enough. I also recorded again, to include the "open in new tab" feature — I actually meant to include that yesterday but forgot, so that's on me!

https://github.com/WordPress/gutenberg/assets/1204802/ef4e5440-7fb0-4359-bf96-83cf79516209

Here's slightly more edited, and zoom-slowed version of the design tools as well:

https://github.com/WordPress/gutenberg/assets/1204802/3b7a008d-933d-4162-a826-ae59a3d4a335

I'm uploading this one, plus the Screen Studio source file, as well as a zoom-updated version of the Design Tools featurette to the Google Drive as well, in a new "Featurettes" subfolder.

**Comment by annezazu** [comment]
@jasmussen this is very minor and I nearly missed it had I not tested but the duplicating blocks shortcut is _new_ for use within List View! You're demo-ing it outside of List View which is a slight difference (and which was already available at least in testing 6.3.1). If we don't want to show that as it might be perceived as too minor (I still think it's rad), you could demo this: https://github.com/WordPress/gutenberg/pull/48708#top

**Comment by jasmussen** [comment]
Good catch, here's a new one:

https://github.com/WordPress/gutenberg/assets/1204802/ced98126-4d53-4994-bdce-9f725b1c9544

**Comment by annezazu** [comment]
Quick note that the Font Library has been punted from 6.4 and is now slated for 6.5. Please remove this from the list of featurettes to complete.

**Comment by jasmussen** [comment]
Here's a new one for TT4:

https://github.com/WordPress/gutenberg/assets/1204802/6795de50-b8dd-470d-a4eb-c83d00b21e9d

@jameskoster is looking at a Workflow Upgrades.

I'll see if I can demo Lightbox primarily from the front-end perspective. Anything else you'd like to see?

In addition to this, next I'll add title and outro cards to these.

**Comment by annezazu** [comment]
Thank you for yet another update! The zoom feels a bit off in the TT4 one at times. In particular, some notes:
- Slow down the jump up at 8 seconds. It's sudden and stands out compared to the rest of the video.
- Zooming in at 10-11 seconds feels a bit off and you miss the lightbox (I am guessing that's what's going on). 
- 24 seconds, I'd zoom in on the category link rather than zooming in on the category title after and stay zoomed out through 28 seconds to see the full category page before zooming in again when you click at 29 seconds.
- I'm not sure why we're zoomed in at 33 seconds, especially when we get into the architecture photo. It makes it hard to see. 
- At the very end, I might just zoom all the way into "Designed with WordPress".

As for another possible video, I think it would be advantageous to have one around the number of patterns in TT4, using a few, and swapping out templates. I think the swapping templates piece in particular is a big part of this theme and it's wise to demo.

**Comment by jameskoster** [comment]
Here's an initial take on the workflow featurette:

https://github.com/WordPress/gutenberg/assets/846565/95676336-1a10-4bac-8c73-b89d915f7126

Included:

* Command palette enhancements (contextual block commands).
* Creating patterns with categorisation.
* Renaming Group blocks.
* Image thumbnails in list view.

**Comment by jasmussen** [comment]
Nice, thanks for doing that Jay! Looks good, I think the quality is perhaps a bit low, we'll just need to remember to export at a high fidelity for the final one. Which, by the way, can you put it in [this Gdrive folder](https://drive.google.com/drive/u/1/folders/1XSdBobPn4M3b4HVRCba7dI9z3zlLtMzO)? Please include the `.screenstudio` file, I'd like to try and tinker with a few things!

Some specific feedback: not sure why we're seeing the "Move" cursor at the beginning. Perhaps start with the cursor outside the browser, and then move in?

In general I find it useful to do primarily manual zooms, that way I can move the focus point to either corner of the recording, so the clearance is uniform, e.g. above and to the left, or bottom and to the left:

![Screenshot 2023-10-17 at 13 49 05](https://github.com/WordPress/gutenberg/assets/1204802/32e52a79-3de7-46f0-a039-1f91133ee17e)

At the 9s mark, it's unclear what you are selecting, it all looks black. It could be due to compression artifacts. But the scripted part is pretty good, selecting something, then invoking the command palette to "insert before". Perhaps it can be a lighter background and have some content inside? Perhaps you can select a spacer? In any case, something to make it clearer what is being selected. And it's nice to see the ⌘K shortcut! 👍 👍

I wonder if instead of pasting something in, you could search for a pattern, or open a pattern to insert? Otherwise you could paste in the existing pattern that was [created for the demo site](https://tt4business.mystagingwebsite.com/about/):

![Screenshot 2023-10-17 at 13 53 17](https://github.com/WordPress/gutenberg/assets/1204802/800e1995-d1e6-423d-9f60-246e9a6999d3)

In any case, that would feel a bit more at home than the safari pictures.

The zooms around 20s in could benefit from either no zoom, or a manual zoom so it doesn't move horizontally into the modal.

At the 29s mark, it would be nice to perfectly sync the zoom out to the click, so that the zoomout starts at the same time as the click.

The subsequent navigate to a different page could maybe work fine without the zoom — at that point it's might flow naturally, suggesting the command palette can be second nature as part of the flow.

Similar notes on the zooms around the 52s mark, I find the less things can move, the better, so a manual zoom here might be good. 

Subsequently around the 1:03 mark, showcasing those gallery thumbnails is nice, and might be good to zoom way in on.

At the 1.08 mark, for some reason the command palette flickers quite a lot, not quite sure what happened there. I.e. whatever the cause should be fixed in the software, but if the bug is present we might need to record something else, or polish this in the editor with a little editing magic. I.e. you might want to open the command palette, pause, _not move the cursor_, type out the full thing, pause, and then cut out all the flickering in the in-between. 

I'd also just press Enter on the Project Overview item, rather than click it.

It would be good to end on a punchline of sorts. Perhaps that's zooming in on the final pattern, and perhaps panning there with a glide: 

![Screenshot 2023-10-17 at 14 01 29](https://github.com/WordPress/gutenberg/assets/1204802/e026ecdd-80eb-4d85-93f8-410b7e5b42f7)

Nice work. I'm happy to help with the screen studio edits btw.

**Comment by jasmussen** [comment]
Good notes, Anne! I'll take a stab at some edits now.

> As for another possible video, I think it would be advantageous to have one around the number of patterns in TT4, using a few, and swapping out templates. I think the swapping templates piece in particular is a big part of this theme and it's wise to demo.

I wonder if that can actually be part of the workflow updates? Otherwise I'll see if I can put something together. I know that @beafialho also recorded a slew of smaller TT4 videos we might want to include in the mix here.

**Comment by jasmussen** [comment]
How about this one Anne?

https://github.com/WordPress/gutenberg/assets/1204802/d838dd25-4e4c-45ac-8eb2-c786fc95764c

I feel like I can tinker endlessly with these and trim and adjust the pacing here and there, but I want to start adding title and outro cards to these and have that pipeline up and running so we have something. I'm also running into limitations of Screen Studio, it only has basic editing, so I can't cut to a zoomed in version easily, all zooms except the first and last ones will be eased in both directions. Nevertheless, let me know your thoughts on this one, and I'll see what I can do.

**Comment by jasmussen** [comment]
Based on Jay's content and script, and [my own notes here](https://github.com/WordPress/gutenberg/issues/54810#issuecomment-1766275397), I took a stab at recording a version of the Workflow featurette here:

https://github.com/WordPress/gutenberg/assets/1204802/583f53db-018b-47a5-9811-fb5d91dcb764

I think the script is pretty solid, and it was quick to record, so it was mainly about adjusting the "Team" pattern a bit, and tuning the screen studio transitions. Let me know what you think, Jay and Anne!

**Comment by beafialho** [comment]
> I know that @beafialho also recorded a slew of smaller TT4 videos we might want to include in the mix here.

Sharing my TT4 videos here:

https://github.com/WordPress/gutenberg/assets/65220155/63c34071-83d3-42dd-bbd8-1aa68a393831

https://github.com/WordPress/gutenberg/assets/65220155/89b1a34d-194c-476b-abf4-c24bfd0df474

https://github.com/WordPress/gutenberg/assets/65220155/a582711d-0494-4b34-9136-609107199df5

https://github.com/WordPress/gutenberg/assets/65220155/61f71856-ee48-41bd-b629-d332f20864fd

**Comment by jasmussen** [comment]
Took a stab at adding intro/outro cards to these, and have "final" versions to share of the four featurettes. Design tools:

https://github.com/WordPress/gutenberg/assets/1204802/a9051497-4ca8-4e11-9374-d2ea3953477e

TT4:

https://github.com/WordPress/gutenberg/assets/1204802/5daaa95f-7087-4005-8c40-bf0403eb43d6

Writing Flow:

https://github.com/WordPress/gutenberg/assets/1204802/06d715aa-a432-4812-acd0-96b5992c3996

Workflow upgrades:

https://github.com/WordPress/gutenberg/assets/1204802/f54dcf8e-87d9-4023-9669-50e4e78f0131

I'd love your "final" feedback on this. 

I had on my ToDo to record a lightbox one as well, but given some recent flux on this I'm holding off on doing this for now.

**Comment by rmartinezduque** [comment]
Thank you for this update, @jasmussen! These look beautiful!

For the title of the intro cards, I suggest keeping some consistency. That is, if we want to include titles, it would be good to have them in all the featurettes. Some ideas for titles if needed:
  - Get creative with more design tools
  - Meet Twenty Twenty-Four
  - Enjoy new writing improvements
  - Work smoothly with upgraded tools
  
 cc @annezazu to ensure this feels aligned.

A few more notes:
- The "Built by WordPress" tagline may be a bit confusing; I'd suggest "Built with WordPress" instead.
- It would be great to include a call to action or a URL for more information in the outro card, like `wordpress.org/6-4/` to point folks to the microsite. Since `wordpress.org/6-3/` redirects to the 6.3 microsite, I assume the suggested URL could work for 6.4 as well.
- The outro card of the workflow upgrades video seems darker than the rest.

**Comment by annezazu** [comment]
>cc @annezazu to ensure this feels aligned.

These sound good and have enough alignment with the About page. 

For the videos, I have a few items of feedback.

Design tools: 
- the background image feels a bit lackluster in that it isn't distinguished much from a cover block. [This is way too long of a video](https://drive.google.com/file/d/1uMBVp8CiCpZ3o7RYFetr6EkJQ7eKKyJ_/view) but shows a bit more depth and more group block specific features perhaps. 

TT4: 
- the jump at 20-21s to a new page feels odd/rushed without a transition or click 
- the pause at 25-26s feels too long.

Writing Flow:
- the keyboard shortcut isn't visible when duplicating in list view at 25-26 seconds.

Workflow upgrades: 
- the initial command visible when you pull up command palette is a bit odd in between 10-11s + again at 35s ("edit template: wp custom...").
- the jump to the pattern modal at 20-21 seconds could be refined. 
- might want to end the video by showing the details view of the team pattern rather than going all the way through the save (doesn't add much).

_Hit enter too soon!_

**Comment by jameskoster** [comment]
Nice work @jasmussen, massive improvement :) I've made an i2 for the workflow vid and added to GDrive:


https://github.com/WordPress/gutenberg/assets/846565/255367af-7c7c-4da5-b2c3-6cbf419719c0

Obviously it doesn't have the intro, hopefully that's easy to add that?

Edit: I'm not sure why the quality is still poor, I'm exporting at 1080p, 50fps, for social media 🤔

> the initial command visible when you pull up command palette is a bit odd in between 10-11s + again at 35s ("edit template: wp custom...").

The visibility of this command is accurate, so I don't think we should hide it. I sped up those sections a bit though – it was particularly glaring at the 35s mark.

I also omitted the first couple of steps where the page details are navigated to. I find the sped-up animation a little jarring and I don't think that section really adds anything.

**Comment by jasmussen** [comment]
> the background image feels a bit lackluster in that it isn't distinguished much from a cover block. [This is way too long of a video](https://drive.google.com/file/d/1uMBVp8CiCpZ3o7RYFetr6EkJQ7eKKyJ_/view) but shows a bit more depth and more group block specific features perhaps.

In very soft pushback I want to suggest that the group block background _is_ very equivalent to the Cover block, the latter may just be a slightly quicker way to accomplish the same. So I intentionally didn't dwell that much on it, especially since we're still lacking a fair bit as far as tiling, scaling tools, etc. 

That said in full transparency this soft pushback is also because re-recording just that part of the video is slightly non-trivial. I'll put it on my list and see if I can stitch this in, _after_ I do the other changes 😅 

> the initial command visible when you pull up command palette is a bit odd in between 10-11s + again at 35s ("edit template: wp custom...").

Also somewhat tricky to fix, and (note to self) in general showing _suggested actions_ by default in the command palette is something we need to be smarter about. Showing just one, already selected, adds undue prominence.

Good notes in general, I'll dive in.

**Comment by jasmussen** [comment]
Oh I see Jay already addressed some of those notes in his i2, fantastic! 

> Obviously it doesn't have the intro, hopefully that's easy to add that?

It is, now that I have the hang of it, yes!

> Edit: I'm not sure why the quality is still poor, I'm exporting at 1080p, 50fps, for social media 🤔

For the final pass I'm re-exporting them in 4K, and then After Effects will do the final compression, that'll likely help. That said, good note, I hadn't noted the FPS counter, and I'll be sure to sync that up with the FPS I have set in AE, they should b e the same.

**Comment by jasmussen** [comment]
> It would be great to include a call to action or a URL for more information in the outro card, like wordpress.org/6-4/ to point folks to the microsite. Since wordpress.org/6-3/ redirects to the 6.3 microsite, I assume the suggested URL could work for 6.4 as well.

I'm a little reluctant to include the URL in the video itself, for a few reasons:

* The URL might change, although unlikely, but if that were to happen it would instantly make the video obsolete. We can make URL redirects, but even then I personally find it clunky having to remember and then type in a short-URL, I'd much rather tap or click an actual link.
* Since these videos are primarily meant for social media, presumably we'll attach an actual link in the prose that goes with it. 

What do you think?

**Comment by jasmussen** [comment]
Thanks for all the great feedback. I regret that I can't always respond in full depth to every detail but rest assured that I'm still on this, and still ready to respond to feedback. Hopefully with each iteration we'll get a little bit closer. 

Design tools i4:

https://github.com/WordPress/gutenberg/assets/1204802/2025ca4c-2283-4202-9447-70227630230e


TT4 i2:

https://github.com/WordPress/gutenberg/assets/1204802/5d4c1841-a8c2-47f3-8263-6eae16bcb33c


Writing Flow i2:

https://github.com/WordPress/gutenberg/assets/1204802/f517bfa2-c876-40b0-9f46-d7f08e35557b


Workflow Upgrades i3:

https://github.com/WordPress/gutenberg/assets/1204802/e9936d1b-ed24-4025-b87b-f99ab24e8668

**Comment by annezazu** [comment]
Ship it! Looks much smoother. Thank you for the continued iterations.

**Comment by jameskoster** [comment]
Agree these are looking good! A couple of tiny points:

* Design tools: The first few seconds where you navigate into a page doesn't add a lot, and the zoom kind of suggests its part of the showcase. Wondering if we could skip straight to the Editor and save a few seconds? Alternatively; remove the zoom and speed that section up – similar to the other featurettes.
* Writing flow: at 48s it's not super obvious that the Lists get combined, or how that is initiated.

**Comment by jasmussen** [comment]
Good feedback both. I did some small tweaks (trimmed the design tools intro, and rested a bit longer at 48s in writing flow) and will send them by a friend to help get some of the title card easings just right, will post back when I have something.

**Comment by jasmussen** [comment]
Here are what I would call the final featurettes:

https://github.com/WordPress/gutenberg/assets/1204802/49c85e39-5f9c-44ca-bf17-77f81ae66945

https://github.com/WordPress/gutenberg/assets/1204802/608e4865-2328-4ee8-a436-f2e55d3565c1

https://github.com/WordPress/gutenberg/assets/1204802/ff8dbb25-7f15-4224-9c68-c360e52c1a2b

https://github.com/WordPress/gutenberg/assets/1204802/c16d9fa4-ca15-4386-bcd3-2803ef011919

Thank you to Adam Wiltgen for finessing timings!

**Comment by richtabor** [comment]
Very nice!

**Comment by rmartinezduque** [comment]
@jasmussen, is there any folder with the 6.4 featurettes or should I download them directly from GitHub?

**Comment by jasmussen** [comment]
I've sent you a link to higher res versions, so you have something to choose from!

**Comment by annezazu** [comment]
Closing this as complete. Excellent work all!
