### ISSUE TITLE
Navigation Block: No blockGap unless you specify

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/gutenberg#54891]
### Description

The elements in the Navigation block don't seem to have blockGap anymore.

Although a custom blockGap works as expected, it shouldn't be necessary.

If I deactivate Gutenberg (trunk) the gaps come back.

### Step-by-step reproduction instructions

1. Open the site editor.
2. Use a Navigation block to build a navigation
3. See the links in the block appear back-to-back without any gap.

### Screenshots, screen recording, code snippet

| Without Gutenberg plugin | With Gutenberg plugin |
| ----------- | ----------- |
| ![localhost local_wp-admin_site-editor php (3)](https://github.com/WordPress/gutenberg/assets/908665/39381021-c980-4647-844d-4d019e1d7ac1) | ![localhost local_wp-admin_site-editor php_canvas=edit](https://github.com/WordPress/gutenberg/assets/908665/f0e45fa6-fdb5-4c6b-b7b3-b5ad162af0f4) |

### Environment info

WP 6.3.1
Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by bgardner** [comment]
Can confirm this is happening. Worth noting that (for me) this is only a Site Editor issue, and not a front end issue. See video.

https://github.com/WordPress/gutenberg/assets/486261/13f0a6af-6eb4-42a7-af92-1a51af716fb7

**Comment by bgardner** [comment]
I am experiencing the issue with WP 6.4 Beta1, with or without Gutenberg active.

**Comment by glendaviesnz** [comment]
It looks like this is a side-effect of https://github.com/WordPress/gutenberg/pull/46752

There was a [similar issue here](https://github.com/WordPress/gutenberg/issues/54943), and have tried the [fix PR](https://github.com/WordPress/gutenberg/pull/54981) for that, but it doesn't resolve this issue.

It looks like [some of the global styles layout selectors](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/global-styles/use-global-styles-output.js#L511) break if not prepended with the editor styles wrapper class, but this may have just been masking an issue with the way the flex classes are applied on the nav block so we will look for a fix at the nav block level rather than adding back `.editor-styles-wrapper` to this style outputs.
