### ISSUE TITLE
Format Library: Explore a fundamental solution regarding highlight popover jumping

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#54909]
Issue #49286 where popovers jump when applying inline highlighting to text has been fixed in #54736.

However, I am filing this issue in order to find a more fundamental solution.

> Maybe we could start by disabling caching completely and seeing what happens?
> _Comment from @ciampo_

**Comment by ciampo** [comment]
A few ideas:

- let's disable the caching altogether, it may help to get to the root of the problem
- I have a feeling that the main issue is that, when switching from "no highlight" to "highlight", the popover anchor may be removed from the DOM (or somewhat altered). In that case, a few possible solutions (at a high-level):
  - [current solution] caching the previous anchor position — that means that, even if the DOM element changes/is removed, we're going to continue using the previous anchor's position. It is a bit hacky, but it works
  - update the popover anchor to point to the most up-to-date element (that would require us to look into how highlighting is implemented, and somehow grab a reference to the correct DOM element)
  - tweak the highlight functionality so that DOM elements are not added/removed (this may be harder)


Let me know how the exploration goes!

**Comment by t-hamano** [comment]
This issue may have already been addressed by #58900. It looks like the cache has been cleared as well.

Can we close this issue?

**Comment by ciampo** [comment]
That's great to hear! Let's double-check by asking directly @jeryj , who implemented the fix you mentioned :)

**Comment by jeryj** [comment]
Yup! The fix in https://github.com/WordPress/gutenberg/pull/58900 should have addressed this.
