### ISSUE TITLE
Font Library: font name changes weight depending on which variants are active

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#54915]
In trying to replicate this issue https://github.com/WordPress/gutenberg/issues/54568, I noticed that the font name in the Typography section changes weight depending on which variants are active. In the video below, watch the weight of "Inclusive sans" in the Typography section (it changes from a more normal weighting to thin to bold by th end):

https://github.com/WordPress/gutenberg/assets/26996883/19eb653a-e7fb-4f11-a7ba-c7a1486b6110

To replicate, add a font that has a number of variants and deactivate different ones to see the font name change weight.

**Comment by ironprogrammer** [comment]
This behavior seems correct to me. The Typography sidebar only displays _active_ fonts/variants. E.g. if I have only enabled italics variants, I'd like that to be reflected here.

From the page load/resource perspective, when variants are deactivated, they are no longer enqueued. In order to display e.g. the "Regular" weight for each font would potentially require enqueuing non-active variants, and could behave inconsistently, say if a user has only uploaded an italics variant.

Testing this locally with only the _italic_ variant of Inclusive Sans active (cleared cache and checking enqueues in `#wp-fonts-local`), Safari overrides italics and weight, but falls back to a serif font. Chrome ignores the overrides completely.

_Figure 1: Safari - override italic face's font-style._
<img width="524" alt="Safari override font-style" src="https://github.com/WordPress/gutenberg/assets/824344/3509a186-a864-4b5e-8fcd-8122036ba1e5">

_Figure 2: Chrome - override italic face's font-style._
<img width="514" alt="Chrome override font-style" src="https://github.com/WordPress/gutenberg/assets/824344/403ff77b-b435-428f-900a-3e43dcb9ea11">

There might be other ways to normalize the listed font's styling if this behavior is desired.

**Comment by annezazu** [comment]
Hmm interesting! I found it to be a bit random in my testing but I can see what you’re saying. I’ll close this out.
