### ISSUE TITLE
Lightbox: connect with overall linking behavior to ensure proper UX

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#54916]
Right now, if you enable lightbox for an image and then add a link, the lightbox behavior is disabled, breaking user expectations. We need to clarify this experience as right now these behaviors are interconnected but that isn't clear. 

"Expand on click" should be designed and optimized for as something that you enable once, globally, and then optionally override on a per-image or gallery basis. In following this approach, it would make sense to move the toggle from the inspector and into the URL toolbar. In doing so, it becomes more intuitively clear that "Expand on click" is _mutually exclusive_ from linking to an attachment page, or a media file.

<img width="2720" alt="Lightbox for images, i4" src="https://github.com/WordPress/gutenberg/assets/1813435/e276c4bb-e3dd-420f-89c7-42a83602dc12">

This design also leverages concepts outlined for the Link Control in #50891. 

Separately, for when applying lightbox through a singular action across images in a gallery, the same dropdown that is currently used for linking to attachment or media files would be used:

<img width="557" alt="Lightbox for galleries, longer term" src="https://github.com/WordPress/gutenberg/assets/1204802/c7cc04ec-8d2a-4d5f-b235-68d19c6582e5">

See also: #56587 for conversations on the expand behavior as applied in galleries.

---

Issue updated Dec 22.

<details><summary>Previous version of the issue</summary>

Right now, if you enable lightbox for an image and then add a link, the lightbox behavior is disabled, breaking user expectations. We need to clarify this experience as right now these behaviors are interconnected but that isn't clear. Here's an example where you can enable lightbox and add a link but that then silently breaks lightbox behavior: 

https://github.com/WordPress/gutenberg/assets/26996883/c623b16f-2951-4737-b238-528afd0e369c

@jasmussen can you look into mapping this out? It seems like if you have lightbox enabled, we should disable the ability to add a link or consider a way to group these settings together since they interrelate. 

_Feel free to edit the title of this issue as it's a bit rough._

</details>

**Comment by jasmussen** [comment]
Good issue, thanks for the ping. To consider lightbox as something you might enable by default, and then _toggle off_ on a per-image basis, it would make sense to move the toggle from the inspector and into the URL toolbar. In doing so, it becomes more intuitively clear that the lightbox behavior is mutually exclusive from linking to an attachment page, or a media file. To that end, here's a mockup that does this:

<img width="2720" alt="Lightbox C2" src="https://github.com/WordPress/gutenberg/assets/1204802/af53cc15-2a65-445d-9f24-24032fea9ca7">

* It removes the toggle from the inspector, and adds it to the URL dropdown.
* In this flow, it's shown as enabled by default, but regardless, "Lightbox" becomes an option in the dropdown, next to attachment page and media file.
* When lightbox is enabled, whether by default or manually, the link dialog shows a toggle with help text.

Another option that is in the same vein of treating the lightbox just as the "attachment link" token, is to have the same existing UI, but add help text at the bottom:

<img width="2720" alt="Lightbox C3" src="https://github.com/WordPress/gutenberg/assets/1204802/8cc0e48c-c3c0-45d7-8498-d6ebd1952c6c">

Note that these mockups are visually slightly different from what's shipping, insofar as the border of the dropdown is black (as it should be when opened from the block toolbar). But those changes are not crucial to have in place in order to fix this bug, they are simply acknowledging that the current gray border is a _separate bug also worth fixing_. 

I'd also be open to suggestions on the verbiage, for the help text we can be as verbose as we need to be. Though to note, in trunk it's currently "Expand on Click", and that should be "Expand on click".

**Comment by richtabor** [comment]
I like the direction, though it feels like the lightbox functionality is a bit hidden behind the "Link" control, if it's not enabled by default.

**Comment by getdave** [comment]
Nice mockups 👍 

Just to add that `Expand on click` really isn't a search suggestion here where as both of `Media file` and `Attachment page` are.

IMHO expand on click could be a link _setting_ rather than something you select when choose from a list of link search suggestions.

**Comment by jasmussen** [comment]
> I like the direction, though it feels like the lightbox functionality is a bit hidden behind the "Link" control, if it's not enabled by default.

Lightbox in general is not something I, personally, think is worth optimizing for when it's _not_ enabled by default, so to that end I think it's okay in the _local_ situation. That said, it does need to be obvious, globally, how to set the default. I wonder if the inspector toggle can exist after all? Perhaps it's non-default in the local situation, and visible by default in the global? [Mockup here](https://www.figma.com/file/46qRP607dtqHGEosEaWWhY/6.4-Design?type=design&node-id=1098%3A55184&mode=design&t=dKlnR5vj72eTIkXc-1) if you want to tinker.

**Comment by annezazu** [comment]
Just to be safe, noticed this in the Gallery block settings. I'm assuming in these mockups this would be removed and only available in the Toolbar but wanted to make sure!

<img width="293" alt="Screenshot 2023-10-02 at 10 35 31 AM" src="https://github.com/WordPress/gutenberg/assets/26996883/6a370b1a-44e6-457c-b630-398c93c2ed9d">
<img width="288" alt="Screenshot 2023-10-02 at 10 35 21 AM" src="https://github.com/WordPress/gutenberg/assets/26996883/1b461a49-0881-457b-a6d9-1d514064186e">

**Comment by jasmussen** [comment]
Good callout. Since _a gallery_ cannot be singularly linked, that dropdown control is a blanket control that applies to all images inside. So ideally, "Expand on click" should be an option in that dropdown, shown by default if applied:

<img width="557" alt="Lightbox for galleries, at minimum" src="https://github.com/WordPress/gutenberg/assets/1204802/79d41a8a-55bd-4337-9cf9-eb3da0712858">

Longer term that could be enhanced with icon and help text:

<img width="557" alt="Lightbox for galleries, longer term" src="https://github.com/WordPress/gutenberg/assets/1204802/c7cc04ec-8d2a-4d5f-b235-68d19c6582e5">

**Comment by artemiomorales** [comment]
@annezazu @jasmussen Thanks for bringing this up and for the designs!

It's unfortunate we didn't catch this during the [latest issue exploring the lightbox UI](https://github.com/WordPress/gutenberg/issues/53403), as @michalczaplinski and I invested a lot of time into getting that UI to work. I haven't worked with the toolbar yet and the inclusion of the gallery UI logic is giving me pause.

I estimate that implementing the approach above would likely take at least 2 weeks, accounting for discovery in the code, implementation, covering edge cases, and rounds of code reviews, bringing us to October 17th, which is the date for the first 6.4 release candidate. It might also introduce unforeseen bugs, and we already have various other bugs that need to be addressed, documented in the [lightbox tracking issue](https://github.com/WordPress/gutenberg/issues/51132). 

We previously had [another implementation](https://github.com/WordPress/gutenberg/pull/51180) wherein we simply disabled the UI for the lightbox in the block settings — part of the [original design recommendation](https://github.com/WordPress/gutenberg/pull/49621#issuecomment-1508200045) for the lightbox — and, by contrast, that would likely only take us a couple of days to get merged:

![242666356-a223d775-affb-47b9-a21f-b5534d9472f7](https://github.com/WordPress/gutenberg/assets/5360536/041f70cf-683a-4b34-acf4-b5707618c8cd)

So we have two options:

1. If we're alright with prolonging lightbox fixes into the release candidate window from October 17th — October 30th, then I can begin removing the old UI and replacing it with the design proposed in this issue. If we can get additional developers helping with the other lightbox bugs, that would be ideal, as my gut check tells me that we'd otherwise start cutting uncomfortably close to final 6.4 deadline.

2. If we treat this issue as an enhancement rather than a bug, we can opt for the simpler disabling of the UI for now, deal with all of the bugs, then begin exploring this implementation afterward, giving a seemingly more appropriate amount of time for exploration, review, and covering edge cases.

My recommendation is the second approach. I'm not sure what the process is for handling unresolved bugs in the release candidate phase, but my inclination is to merge something simpler and get all bugs covered as soon as possible, rather than get close to the 6.4 finish line and risk additional crunch time, or perhaps punting of the lightbox altogether.

Am happy to hear other thoughts 🙏 Let me know what you think!

**Comment by annezazu** [comment]
Thanks so much for talking this through and providing different options. After checking with @priethor and @jasmussen, let's proceed with option 2 for now and plan to iterate for 6.5. I do want to make clear though that the link UI is the eventual best location here, whether it's a cross icon to detach an image, or a toggle to disable the lightbox. 

If you need any additional design help/guidance for option 2, please just say the word so we can move quickly for 6.4 ❤️

**Comment by richtabor** [comment]
> Since a gallery cannot be singularly linked, that dropdown control is a blanket control that applies to all images inside. So ideally, "Expand on click" should be an option in that dropdown, shown by default if applied:

Alternatively, we can use the same toolbar control as proposed for the image block on the gallery, omitting the inspector "Link to" control on the gallery block.

**Comment by richtabor** [comment]
> Another option that is in the same vein of treating the lightbox just as the "attachment link" token, is to have the same existing UI, but add help text at the bottom:

@jasmussen I lean in this direction, leveraging the proposed link UI in https://github.com/WordPress/gutenberg/issues/50891. 

What do you think of leveraging the component's description/help text instead. And using the "Unlink" icon for unlinking/removing the behavior, closely resembling the UI when a link is applied anywhere else as well. 

<img width="2720" alt="Lightbox for images, i4" src="https://github.com/WordPress/gutenberg/assets/1813435/e276c4bb-e3dd-420f-89c7-42a83602dc12">

**Comment by jasmussen** [comment]
That one looks great to me, feel free to update the issue! Nice one Rich.

**Comment by artemiomorales** [comment]
> Let's proceed with option 2 for now and plan to iterate for 6.5. I do want to make clear though that the link UI is the eventual best location here, whether it's a cross icon to detach an image, or a toggle to disable the lightbox.
>
>If you need any additional design help/guidance for option 2, please just say the word so we can move quickly for 6.4 ❤️

Perfect, thanks! I should have this UI fixed by the end of the beta period.

**Comment by richtabor** [comment]
> That one looks great to me, feel free to update the issue! Nice one Rich.

I created a follow-up to this issue that details the move https://github.com/WordPress/gutenberg/issues/55020.

**Comment by getdave** [comment]
@artemiomorales Please let me know if you go ahead with attempting to implement what Rich has in https://github.com/WordPress/gutenberg/issues/55020.

I've worked a lot with `LinkControl` and related components and we can work together to find the best implementation.

One thing to consider is that we should try and avoid augmenting the API of `LinkControl` where possible 🙏

**Comment by artemiomorales** [comment]
I opened a PR to do the simple fix: https://github.com/WordPress/gutenberg/pull/55141

**Comment by annezazu** [comment]
Just bringing in feedback [from this YouTube video ](https://youtu.be/aU1O1Nd7oDg?si=d2ixcm2GyrdFwagY&t=175)around how cumbersome it is to set the expand on click option for each individual image in a Gallery. This touches on comments further up where we need to think about these [settings within a Gallery block too. ](https://github.com/WordPress/gutenberg/issues/54916#issuecomment-1743585362) Happy to open a separate issue or just track this in this issue as part of this broader work.

**Comment by jasmussen** [comment]
The solution to that, IMO, is to lean into lightbox being something you set _on_ by default, and then toggle _off_ on a per-image basis, as somewhat [touched upon here](https://github.com/WordPress/gutenberg/issues/54916#issuecomment-1740641571) and part of the motivation for the URL dialog design.

**Comment by jasmussen** [comment]
For folks subscribed, I've updated this issue with a summary of the conversation, and the agreed upon mockups put into the body of the original issue, so it's hopefully easier to understand the next step. I've also gone ahead and hidden the conversation that was resolved (you can still expand the comments if you like) for clarity.

**Comment by annezazu** [comment]
Closing this since this has landed https://github.com/WordPress/gutenberg/pull/57608
