### ISSUE TITLE
Components: `Modal` Height Controls

### ISSUE THREAD

**Issue by chad1008** [WordPress/gutenberg#55062]
We recently implemented some preset sizes for `Modal` via the `size` prop: `small`, `medium`, `large`, and `fill`. (`fill` is analogous to and will eventually replace the `isFullScreen` prop)

See https://github.com/WordPress/gutenberg/pull/54471 for more, but the goal of this change was to make it easier for consumers to specify a width for their modals without having to resort to excessive style overrides.

An example of where this can be helpful is the font library modal in the site editor, [where a temporary workaround is currently in place](https://github.com/WordPress/gutenberg/pull/54518/files).

This is an interesting case, because while our new prop was primarily focused on widths (to avoid things like paragraph tags wouldn't push the modal to full viewport width), the font library also has _height_ needs. Right now it's using `isFullScreen`, which creates a modal that is... you guessed it... full screen, with an a small buffer on each side. Font library is then explicitly limiting the width to `65vw`. That means `isFullScreen` is really only in place to make the modal taller than it would be based on content alone.

The new `size = "large"` option would be a good fit here, giving a workable width on medium and large devices but allowing a full screen mobile experience. Except for the height issue. The problem is that the different tabs contained within this particular `Modal` are all different heights. That means switching tabs creates an unsightly jumping effect when `size: large` is applied:

https://github.com/WordPress/gutenberg/assets/13856531/b6464b3a-6944-43ab-94d4-e5961a1e31b9

Having a consistent height that can be specified by the consumer would be helpful here. It can be accomplished with CSS, but would it be preferable for `Modal` provide a built-in solution?

Possible ideas:
-  a new prop for height, maybe something like `isFullHeight` that would have the sam height effect of `isFullScreen`, but not impact width at all.
- apply a height value to our existing presets. Maybe just have `large` fill the screen vertically, maybe set specific min-heights for each?

Curious what others think from a component/design perspective. cc @ciampo @brookewp @andrewhayward @WordPress/gutenberg-design

**Comment by ciampo** [comment]
I guess we could at most set some proportionate min-height based on the width, but I'd be quite conservative with it

**Comment by jasmussen** [comment]
How about trying an `aspect-ratio`?

**Comment by ciampo** [comment]
`aspect-ratio` seems to work — it sets a min-height, but it grows as the container grows. I put together a quick [demo](https://codesandbox.io/s/flamboyant-lehmann-d458f9?file=/index.html), you can add / remove text to see the how it would behave

It wouldn't work if we wanted to impose a fixed height (although I'm not sure it would be a good approach)

**Comment by jasmussen** [comment]
`aspect-ratio` should respect a max-height, though, and it might be good to have one. It can be a very tall max-height, such as `calc(100svh - 4rem)`, something in that vein, but we wouldn't want it to grow taller than the screen.

**Comment by jameskoster** [comment]
Aspect ratio with a max-height could work as an option, but I think the default behavior should remain otherwise shorter modals become unnecessarily tall:

<img width="507" alt="Screenshot 2023-10-05 at 12 39 56" src="https://github.com/WordPress/gutenberg/assets/846565/cf841b0d-c0e7-4efa-9625-b2fd4b20ad5d">

Still, this particular issue seems to be fairly contextual, based on the inclusion of sub-navigation where each page affects the overall height. I wonder if a more comprehensive solution would be to build this feature into the Modal. It would avoid potential misuse of an aspect ratio option and promote consistent navigation patterns within modals.

**Comment by andrewhayward** [comment]
Respecting a desired height with `aspect-ratio` is definitely doable with a liberal application of `overflow: auto;`, but I'm not totally sure how that would work either!

```css
... {
  ...

  width: 200px/400px/600px/800px;
  aspect-ratio: 2/1;

  min-width: 33dvw;
  max-width: calc(100dvw - 2rem);
  min-height: 300px;
  max-height: calc(100dvh - 2rem);
}
```
<p align=center>
<img width="49%" alt="A box nominally 200px by 100px, but restricted to 229px by 300px." src="https://github.com/WordPress/gutenberg/assets/159848/7dd7c9f2-b373-4358-87cf-49ac0a882695">
<img width="49%" alt="A box nominally 400px by 200px, but restricted to 400px by 300px." src="https://github.com/WordPress/gutenberg/assets/159848/1a050ace-fc56-406d-af59-882d81b4e00a">
<img width="49%" alt="A box nominally 600px by 300px, and rendered as such." src="https://github.com/WordPress/gutenberg/assets/159848/65a14b92-1ed8-4b5c-84cc-be5b1646de1e">
<img width="49%" alt="A box nominally 800px by 400px, but restricted to 662px by 331px." src="https://github.com/WordPress/gutenberg/assets/159848/d76a5362-26e3-44bc-a4f3-23833839bbfa">
</p>

**Comment by ciampo** [comment]
> I wonder if a more comprehensive solution would be to build this feature into the Modal.

@jameskoster what do you refer to when you mention "this solution" ?

I think that this conversation is already about potentially adding a preferred aspect ratio to the existing size presets.

I'd also caution us against adding too many specific styles to a generic component like `Modal`.

**Comment by jameskoster** [comment]
@ciampo never mind, my point was that you'd only need the modal height to be fixed when there's a sub-navigation (like the fonts example in the OP, or the Preferences modal in the editor). But thinking about it some more there are other legitimate uses cases, like searching within a modal. 

If the aspect-ratio idea doesn't work out, another option could be to try the command palette approach. There the modal height still 'hugs' its contents, but since it's a fixed distance from the top of the viewport (rather than centrally aligned) it works okay.

**Comment by richtabor** [comment]
What if instead the top of the modal was positioned consistently, regardless of content height? Instead of an absolute center.

**Comment by chad1008** [comment]
`aspect-ratio` feels really promising, but it does look like it might require moving `Modal` away from using `display: flex`.

Based on some testing I've done just now, when `flex` is involved, the `aspect-ratio` is more strictly enforced, and the height of the element no longer expands with the content.

When combined with the `Modal` content's `overflow:auto`, `aspect-ratio` effectively becomes a fixed height that automatically makes the content scrollable. Here's a slight modification of @ciampo's previous example to [demonstrate](https://codesandbox.io/s/zealous-firefly-gppyr9?file=/index.html).

I can certainly look into removing `flexbox` from `Modal` to make room for `aspect-ratio`, unless that's a non-starter for anyone.

If that doesn't sound like a good path, maybe we apply a fixed hight to just one of the presets? Maybe `large` should always be full height (ie the `calc(100% - 80px)` we apply for `size: fill`/`isFullScreen`? That or a separate prop to make any modal full screen height?

**Comment by ciampo** [comment]
I think I'm losing track of exactly what issue are trying to solve here.

Looking at the initial example at the top of this issue, to me it looks okay that the consumer of `Modal` needs to set a specific height on the component for this specific use case.

I get the convenience of offering some preset sizes, and why we may also want to add height to those presets. But we can not expect to cover all use cases of `Modal` — which is why we allow folks to set a classname on it, and customize it.

**Comment by chad1008** [comment]
> I think I'm losing track of exactly what issue are trying to solve here.

My only concern was that in cases where the height of the `Modal` contents changes, like with internal tabs/navigation, the size of the modal can bounce around in an unsightly way.

If we think that's something we'd prefer to let consumers manage directly via CSS, that works for me, but I wanted to raise the question once I saw it.

**Comment by richtabor** [comment]
> My only concern was that in cases where the height of the Modal contents changes, like with internal tabs/navigation, the size of the modal can bounce around in an unsightly way.

Why I was thinking of a solution that maintains the origin positioning, regardless of height change.

**Comment by ciampo** [comment]
Got it, thank you both!

I guess one solution wouldn't prevent the other?

- We could work on a prop which toggles the origin positioning (as suggested by @richtabor )
- Separately, we could investigate adding some form of height constraint (as discussed by @chad1008 )

One thing I'm going to say is that we're about to start working on a new version of the `Modal` component, powered by a third party library (likely `ariakit`) instead of our current custom first-party implementation. I think it may be smart to punt any of the changes discussed in this issue so that we can apply them directly to the new version of the component?

**Comment by chad1008** [comment]
Cool. I can plan on tackling it that way, and in the meantime just leave the font-library hight fixed as it is today 👍 

Thanks everyone!!
