### ISSUE TITLE
Cover Block: Heading color option appears in 6.4 RC

### ISSUE THREAD

**Issue by cbirdsong** [WordPress/gutenberg#55653]
In 6.4 RC 2 the cover block has a heading color option:

![Wordpress block sidebar showing text, heading and overlay color options](https://github.com/WordPress/gutenberg/assets/1672206/661400f1-af88-4a7a-9f42-e259eab4fd64)

I tested this on both a hybrid/traditional theme and a FSE theme and it appears on both. It can be removed by adding `"heading": false` inside the color key in theme.json, but the schema thinks this is invalid.

Is all this intentional? I can't find any mention of it in the 6.4 field guide.

**Comment by t-hamano** [comment]
This feature seems to have been added in #49131. However, it looks like the theme.json schema is not updated.

**Comment by cbirdsong** [comment]
I don't see it in any other block, including the ones mentioned in the PR?

**Comment by t-hamano** [comment]
Since `__experimentalDefaultControls` is defined in blocks other than the cover block, it is not displayed by default. The cover block does not have `__experimentalDefaultControls` property, so all color support will be displayed by default. Please click on the ellipsis button.

![heading](https://github.com/WordPress/gutenberg/assets/54422211/5e983a42-43d2-4329-8150-334a06645500)

**Comment by t-hamano** [comment]
I submitted #55675 to update the schema of `block.json` and #55674 to update the schema of `theme.json`.

**Comment by annezazu** [comment]
I'm going to close this out unless anything remains unresolved! Doing a sweep for 6.4. Happy to reopen.
