### ISSUE TITLE
Term Description (core/term-description) is broken in 6.4-RC2

### ISSUE THREAD

**Issue by danieldudzic** [WordPress/gutenberg#55665]
### Description

With 6.4-RC2 the `core/term-description` block is not registered.  

<hr />
It seems that #51053 was made in order to hide the Term Description block from the post editor (and just have it available in the template editor).  

For context, this change breaks the Term Description block used in our patterns in WooCommerce Blocks: https://github.com/woocommerce/woocommerce-blocks/issues/11300

If this change is not reverted, 6.4 will cause breakage for users currently using those patterns but not having Gutenberg active.

<hr />

Trac ticket: https://core.trac.wordpress.org/ticket/59755

### Step-by-step reproduction instructions

1.  With a block theme, open `Appearance > Editor`.
2.  Open `Templates > All Archives`.
3.  Try to add the Term Description block. Notice that it's missing from the Inserter.

### Screenshots, screen recording, code snippet

6.3.2 - working correctly  

*   Editor: [​https://cloudup.com/cFcrg4DDyPY](https://cloudup.com/cFcrg4DDyPY)
*   Inserter: [​https://cloudup.com/cG1\_EShVyHH](https://cloudup.com/cG1_EShVyHH)
*   Front end: [​https://cloudup.com/carnkP-W2W6](https://cloudup.com/carnkP-W2W6)

6.4-RC2 - broken  

*   Editor: [​https://cloudup.com/cKfLlO3vAb4](https://cloudup.com/cKfLlO3vAb4)
*   Inserter: [​https://cloudup.com/cVFZb3A8uvy](https://cloudup.com/cVFZb3A8uvy)
*   Front end: [​https://cloudup.com/cJa31wewZZD](https://cloudup.com/cJa31wewZZD)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by hellofromtonya** [comment]
[As noted in the Trac ticket](https://core.trac.wordpress.org/ticket/59755#comment:9):

* The block changed to experimental in WP 6.3.0, but continued to render in WP Core without the Gutenberg plugin activated.
* This regression is a BC break as it rendered before 6.4, but no longer does in the backend or frontend.
* What changed in 6.4?
* What the change intentional?

**Comment by hellofromtonya** [comment]
With 6.4 final in a little over a week, pinging some folks @carolinan @aristath @ockham and 6.4 editor leads @SiobhyB @mikachan @karmatosed  @annezazu @bph

**Comment by SiobhyB** [comment]
👋 folks, I'll work on a PR for this shortly and request a review from everyone Tonya just @-mentioned. Thanks so much for pinpointing where the regression was introduced @danieldudzic!

**Comment by SiobhyB** [comment]
I spent a bit of time attempting to figure out a way to restore the block so that it wasn't available in the post/page editor, but opted to simply revert the regression in https://github.com/WordPress/gutenberg/pull/55669. My thinking behind this is as follows:

* We're _extremely_ tight on time, given we're late into Friday and the hope is to have 6.4 finalised on Monday.
* The original bug (https://github.com/WordPress/gutenberg/issues/38552) wasn't a new regression and had been available in core for over a year. There isn't an urgency to include a fix for it in 6.4 and we can address it separately.

I'll go ahead to request reviews from the folks mentioned in this issue.

**Comment by SiobhyB** [comment]
Addressed in https://github.com/WordPress/gutenberg/pull/55669 and re-opened the original bug in https://github.com/WordPress/gutenberg/issues/38552.

**Comment by carolinan** [comment]
I don't mind the revert for solving it short term.
But I don't feel like we have tracked down the real underlying issue?

The description of the problem in the WooCommerce repository shows that what is being edited is a **template**, which means the user is **not** attempting to add this block in the block editor*/ post editor.

**Comment by SiobhyB** [comment]
> But I don't feel like we have tracked down the real underlying issue?

I think you're right, we chose the quickest route towards avoiding the breaking change in time for the 6.4 release. For the future, it would be ideal to investigate a fix for the original problem described at https://github.com/WordPress/gutenberg/issues/38552 and explore ways to limit the block to the template editor. Or, is there another aspect to this that I'm missing?

> The description of the problem in the WooCommerce repository shows that what is being edited is a template, which means the user is not attempting to add this block in the block editor*/ post editor.

Indeed, an inability to access the block via the template editor was the problem. Reverting the changes in https://github.com/WordPress/gutenberg/pull/51053 resolved the problem, so it's now possible to access the block via the template editor again. I think we're all in agreement that, ideally, the block should _not_ be available from the post/page editor.
