### ISSUE TITLE
Tagging all functions in the wp-includes/blocks/ directory with @since tags

### ISSUE THREAD

**Issue by kebbet** [WordPress/gutenberg#55777]
### Description

While preparing for WP 6.4 RC3 a discussion was brought up about filters and functions missing a `@since` tag in the directory `wp-includes/blocks`. This ticket is for a general discussion on the topic.

Highlights from the slack-discussion 
`I think they should still have an @since when the come over to WordPress but I don't think this needs to interrupt or stop RC prep` by @aaronjorbin 

`Following up on the discussion: Very few of the functions in that directory have @since annotations. Thinking if they should be there, then would be worth adding them to all of the functions for consistency.` @hellofromtonya 

Pinging @mukeshpanchal27 who also expressed opinions.

For me as a novice developer I think the `@since` tags are helpful for tracking origins and how long things have been in core. And I think missing since-tags are breaking the docblock standard in core. But thats maybe an incorrect asumption of me.

### Step-by-step reproduction instructions

.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by gziolo** [comment]
All these files get automatically copied from `@wordpress/block-library/src/*/index.php` in WordPress core and the live in `packages` folder in this repository.

I think we briefly discussed it with @anton-vlasenko in the past, that as a follow-up we should consider adding CI check that enforces that `@since` is always provided for all declared functions in these files.
