### ISSUE TITLE
Query Loop block: Page next to current one (mid_size control) is not visible

### ISSUE THREAD

**Issue by tatasha2004** [WordPress/gutenberg#55794]
### Description

Query Loop block: Page next to current one (mid_size control) is not visible

### Step-by-step reproduction instructions

1. Install and activate WP 6.4 - Beta2 (Theme Twenty Twenty-Four)
2. Add Query Loop block and ensure that Query Page Numbers block is displayed
3. Check block settings

**Actual result:** 'Page next to current one' (mid_size control) is not visible https://monosnap.com/file/IBycGB5epadw3MtIekCERQTwweY4pa
**Expected result:** 'Page next to current one' should be visible.
Related to https://github.com/WordPress/gutenberg/pull/51216.

### Screenshots, screen recording, code snippet

![image](https://github.com/WordPress/gutenberg/assets/30239355/1bb539b4-42a2-471a-ad6c-7f64ef24bfe2)

### Environment info

 WP 6.4 - Beta2 (Theme Twenty Twenty-Four)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

The control corresponding to mid_size exists not in the Pagination block, but in the Page Numbers block _inside_ that block. Unlike the screencast in #51216, the configuration label is "Number of Links".

I think this is the expected behavior, so I would like to close this issue, but if you have any questions, please feel free to comment.

![page-numbers](https://github.com/WordPress/gutenberg/assets/54422211/536515fe-66f5-46c9-b6b5-55b37149fced)
