### ISSUE TITLE
Theme.json registered patterns missing in the Site Editor patterns view

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#55819]
TT4 [adds two patterns via theme.json](https://github.com/WordPress/twentytwentyfour/blob/trunk/theme.json#L4-L7), which are available within the Inserter, but omitted from the Site Editor > Patterns view. I'd expect that the theme's patterns should each be listed in the Site Editor > Patterns view. 

In the first screenshot, the 'clients-section' pattern is missing, but in the inserter, you can see it properly.

![CleanShot 2023-11-02 at 12 20 47](https://github.com/WordPress/gutenberg/assets/1813435/ec41c32e-28aa-4f2c-a60f-438c7de4bbc2)

![CleanShot 2023-11-02 at 12 45 22](https://github.com/WordPress/gutenberg/assets/1813435/cd02b22e-8f28-4c0d-a5a8-21d925937715)

Related to https://github.com/WordPress/gutenberg/issues/55109

**Comment by glendaviesnz** [comment]
I see the clients pattern in the site editor on trunk:

<img width="1463" alt="Screenshot 2023-11-03 at 4 44 04 PM" src="https://github.com/WordPress/gutenberg/assets/3629020/20b865dc-44d2-4eb0-b2e3-68a230afb3bd">

I wonder what is different on your setup @richtabor ?

**Comment by t-hamano** [comment]
I tested it on the latest WordPress trunk and Gutenberg trunk, and I'm also seeing the same thing as @richtabor , but I think this is due to the difference in the specifications of the inserter and pattern page.

- Inserter: Displays all themes and plugins, user patterns, and **patterns from the pattern directory**
- Site editor patterns page: themes and plugins, user patterns

If you compare the number of patterns belonging to each category on the inserter and the pattern page, you will notice that the numbers are different.

Patterns defined in the patterns property of TT4's theme.json are categorized in the patterns directory in the inserter.

`three-columns-of-services`

![three-columns-of-services](https://github.com/WordPress/gutenberg/assets/54422211/7f688469-d983-4b67-b0d2-2e04a10a3603)

`clients-section`

![clients-section](https://github.com/WordPress/gutenberg/assets/54422211/e631fd08-2476-4e78-b85e-e9d0f369315e)

I don't know why @glendaviesnz can't reproduce this problem, but if the specification is that the pattern defined in the `pattern` property of theme.json is classified as a pattern directory source, I think this is the intended behavior.

**Comment by glendaviesnz** [comment]
I did a fresh install of TT4 on a site and was then seeing the same thing. @aaronrobertshaw can you remember the reasoning for not including these theme patterns in the site editor?

If we decide that we want these `theme.json` specified patterns to appear in the site editor [this PR](https://github.com/WordPress/gutenberg/pull/55877) makes this change.

**Comment by aaronrobertshaw** [comment]
> @aaronrobertshaw can you remember the reasoning for not including these theme patterns in the site editor?

My recollection was that no pattern directory patterns were to be included in the Site Editor patterns page. If I follow the examples correctly, the TT4 patterns in question are remote patterns from the pattern directory and so given previous decisions omitted from the patterns page.

There was a [plan](https://github.com/WordPress/gutenberg/issues/50028#issuecomment-1569510845) to eventually allow remote patterns to be linked to from the Site Editor's Patterns page allowing users to copy those patterns to their local user-created patterns to manage further like those provided via files in a theme.

> If we decide that we want these theme.json specified patterns to appear in the site editor https://github.com/WordPress/gutenberg/pull/55877 makes this change.

I also have a vague recollection of there being some issues with nested remote patterns so it might be more involved than simply deleting the `pattern-directory/theme` source from the core patterns list.
