### ISSUE TITLE
shortcode_atts acting differently for Gutenberg than classic editor

### ISSUE THREAD

**Issue by mintplugins** [WordPress/gutenberg#5597]
## Issue Overview
Using version 2.3.0 of Gutenburg, if you enter a shortcode on the page with an attribute in quotes, the quotes are incorrectly part of the value after running it through the [shortcode_atts](https://codex.wordpress.org/Function_Reference/shortcode_atts) function. 

## Steps to Reproduce

1. Put this example code in a child theme's functions.php file:
```
function my_custom_shortcode( $atts ) {

	$vars = shortcode_atts( array('my_custom_att' => NULL), $atts );

	print_r( $vars['my_custom_att'] );
	die();
}
add_shortcode( 'my_custom_shortcode', 'my_custom_shortcode' );
```

2. Put this shortcode onto a Gutenburg page:
```
[my_custom_shortcode my_custom_att="test"]
```
<img width="660" alt="screen shot 2018-03-13 at 7 09 39 pm" src="https://user-images.githubusercontent.com/1638128/37374566-1acba03a-26f2-11e8-9d02-051e0a12ef72.png">

3. View the page. If you see the word `test` wrapped in quotation marks, that is the bug. It should not be in quotation marks. 

<img width="68" alt="screen shot 2018-03-13 at 7 08 45 pm" src="https://user-images.githubusercontent.com/1638128/37374549-02508778-26f2-11e8-8df8-201a9f81da31.png">

4. Repeat this exact shortcode in a classic editor, and the output will be without quotes.
<img width="52" alt="screen shot 2018-03-13 at 7 10 21 pm" src="https://user-images.githubusercontent.com/1638128/37374586-35070ba6-26f2-11e8-85f9-98781acfc98b.png">

## Expected Behavior
The output should not have quotes around it, the same way it works with the classic editor. 

## Current Behavior
The output incorrectly has quotes around it.

**Comment by mintplugins** [comment]
Just to clarify, version 2.4.0 was released this morning and this is still happening.

**Comment by danielbachhuber** [comment]
Thanks again for the detailed report with useful reproduction steps, @mintplugins.

I tested this against `master` (soon to be 3.1) today and was unable to reproduce the issue:

<img width="822" alt="image" src="https://user-images.githubusercontent.com/36432/41535770-68c2f27c-72b8-11e8-9ec4-f4aab8469b99.png">

<img width="744" alt="image" src="https://user-images.githubusercontent.com/36432/41535790-75c0fd02-72b8-11e8-8cef-8d3c04b050a9.png">

I'm not sure what the fix was, but it seems like this issue was addressed at some point in the last couple of months. Please let me know if you don't think this is the case.
