### ISSUE TITLE
ToolsPaneltem: Stale `hasValue` when value is reset by different means

### ISSUE THREAD

**Issue by Mamaduka** [WordPress/gutenberg#55976]
ToolsPaneltem: Stale `hasValue` when value is reset by different means

While working on #55973, I noticed that when you reset the image from `MediaReplaceFlow`, the tools panel still shows the reset option.

I can reproduce it on the trunk, so it's probably a different issue with the tools panel.

_Originally posted in https://github.com/WordPress/gutenberg/issues/55973#issuecomment-1802312078_

## Screencast

https://github.com/WordPress/gutenberg/assets/240569/e7ebdecd-297e-478b-a995-9108e41806af

**Comment by Mamaduka** [comment]
@andrewserong, let's move our ToolsPanel convo here.

In the screencast at 0:03, you will see that both tools panel options are active after resetting the image via `MediaReplaceFlow`. I would expect those to be disabled and non-actionable.

**Comment by andrewserong** [comment]
Thanks for raising this separately! I imagine it's probably an issue with the `ToolsPanel` as I can reproduce a similar kind of issue with typography in global styles. As an example, if we go to change the appearance and set a value, then set it back to default, the panel still thinks there's a value:

https://github.com/WordPress/gutenberg/assets/14988353/3e677490-577f-4591-a825-8c1260c62d17

Similarly, in the block editor, if we go to set a custom font size, and then clear out the value so that it matches the default state, the `ToolsPanel` still thinks there's a value there:

https://github.com/WordPress/gutenberg/assets/14988353/740e834c-5b52-42f9-ae8f-c2e166f80cb1

So it feels like perhaps in the `ToolsPanel` there's possibly some stale logic in checking for `hasValue`, as you mention.

**Comment by stokesman** [comment]
I believe this has been resolved by #60621. I tested a couple of the demonstrated cases in this issue and cannot reproduce them.

**Comment by Mamaduka** [comment]
Thanks for testing, @stokesman! I can also confirm that the reported bug is gone.

I'll close the issue.
