### ISSUE TITLE
"Headless TinyMCE"

### ISSUE THREAD

**Issue by androb** [WordPress/gutenberg#560]
This has been asked for, need to understand the requirement more.

**Comment by jasmussen** [comment]
Thanks Andrew. @iseulde can you help clarify what this could entail? Thanks.

**Comment by iseulde** [comment]
A "headless" version of TinyMCE would be the current version but without any UI, plugin loader, and stuff like that. Just a package that fixes bad browser manipulation in `contentEditable`, maybe with some tools/API to make it easier to use. Ideally it's also in npm and doesn't create global variables.

**Comment by aduth** [comment]
Related: https://wordpress.slack.com/archives/C02QB2JS7/p1487185410004370

**Comment by androb** [comment]
This was added in TinyMCE 4.7. Setting the theme to false will cause TinyMCE to be headless.

**Comment by dsifford** [comment]
@androb Would you be able to point us to an example of this API? I'm trying to run headless using Jest/jsdom and there are tons of errors being thrown by the core tinymce library because of all of the DOM APIs that it needs.

I tried stubbing `window.matchMedia` and that worked, but then an error was being thrown for tinymce's `util.toAbsPath` because the base URI is not defined.

CC: @spocke 

Thanks in advance.

**Comment by spocke** [comment]
What we mean by headless is that it has no ui similar to headless browsers like phantomjs. JSDom is a js implementation of the dom that is very limited so so only parts of a complex editor like tiny would be able to support that and we don’t have that on our roadmap. Tiny and all it’s tests works in a headless browser you can run our tests command line using grunt for example. So if you could run your tests though phantomjs it should work fine.

**Comment by dsifford** [comment]
I see. Thanks for the clarification.
