### ISSUE TITLE
"css"-Property in per block-based theme.json doesn't work anymore

### ISSUE THREAD

**Issue by Maufeat** [WordPress/gutenberg#56003]
### Description

The CSS Property in the theme.json doesn't work since the newest update.

For example this was working before:
```
...
  "styles": {
    "css": "{} html,body{display:none;}
    "blocks": {
      "core/navigation": {
        "css": "{} .wp-block-navigation-item__content:hover{color: black;}"
      },
    }
  },
...
```

### Step-by-step reproduction instructions

1) Roll back to the Gutenberg Version in WP 6.3.x
2) Update a Block CSS-Property in theme.json
3) Update to WP 6.4 and watch it not applying those properties

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Maufeat** [comment]
I found the issue here after tracking it down. The code has been edited to not allow non-nested code.

My example above:

```
"css": "{} .wp-block-navigation-item__content:hover{color: black;}"
```

needs to be changed to:

```
"css": "{ & .wp-block-navigation-item__content:hover{color: black;} } "
```

can be closed, if this is intended behaviour.

**Comment by t-hamano** [comment]
Hi @Maufeat,

```
"css": "{} .wp-block-navigation-item__content:hover{color: black;}"
```

I'm not sure why this code is working in WP6.3.x, but if you want to target child elements of a block, you need use `&`.

You can check various code examples in the following articles on the Developer Blog.

[Per-block CSS with theme.json – WordPress Developer Blog](https://developer.wordpress.org/news/2023/04/per-block-css-with-theme-json/)

I think this is the expected behavior, so I'd like to close this issue, but feel free to comment if you have any problems.
