### ISSUE TITLE
[WP 6.4.1] images can't be corrected selected as Gutenberg block after linking to media

### ISSUE THREAD

**Issue by Dzhami-Jame-ALI** [WordPress/gutenberg#56017]
### Description

Images can't be corrected selected as Gutenberg block after linking to media. This appears after wp 6.4. 

### Step-by-step reproduction instructions

1. Create an image in Gutenberg editor
2. Click the image: currently the image can be selected as a Gutenberg block, and blue selection border appears. 
3. Link the image to its media file
4. Click the image again: currently the image cannot be selected as a Gutenberg block, and blue selection border disappears (need to press Up Arrow key to restore it). 

### Environment info

New installed WP 6.4.1 in docker, without any other plugins or themes
Chrome
macOS Sonoma

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
Hi @Dzhami-Jame-ALI  - I'm having trouble recreating this issue. Are you able to share a screencast of it happening to have a better idea of what is going on?

**Comment by Dzhami-Jame-ALI** [comment]
Hi @jordesign - I am posting the screen recording here: 

https://github.com/WordPress/gutenberg/assets/26970006/6547beee-e98c-4ce1-804d-e1cc1f8464bc

**Comment by t-hamano** [comment]
Thanks for the report. I was able to replicate it.

Indeed, the image block is not selected correctly. When I select an image, the blue outline does not appear. The block is not inserted when I press the Enter key. I cannot delete the block even if I press the Delete key.

I think this issue is related to #55470. Because it appears to be [disabling the click](https://github.com/WordPress/gutenberg/pull/55470/files#diff-a14b61c874095649b236b78413e805b4541277b24eb71ce350a17d9f2b6396b1R86-R89).

#55470 was shipped in WP6.4, so this issue should occur in WP6.4 and later. I think this is an issue that should be resolved in a minor release, so I'll add it to the " WordPress 6.4 Editor Tasks" board.
