### ISSUE TITLE
Gutenberg is gone for CPTs when the "editor" option is missing from the "supports" argument

### ISSUE THREAD

**Issue by kmgalanakis** [WordPress/gutenberg#5603]
When creating a CPT, in order to enable Gutenberg for it we need to set `show_in_rest` to true.

Unfortunately, even though `show_in_rest` is set to true, the editor UI reverts back to the classic editor when the `editor` option is omitted from the `supports` CPT argument.

To test this use the simple code below:

```
function create_posttype() {
 
    register_post_type( 'movies',
    // CPT Options
        array(
            'labels' => array(
                'name' => __( 'Movies' ),
                'singular_name' => __( 'Movie' )
            ),
            'public' => true,
            'has_archive' => true,
            'rewrite' => array('slug' => 'movies'),
			'show_in_rest' => true,
			'supports'  => array( 'title' )
        )
    );
}
add_action( 'init', 'create_posttype' );
```

I know that it actually makes complete sense but imagine having only custom fields for a CPT. This will confuse users to see the classic editor.

Also, what would happen when GB is merged into the core?

**Comment by mtias** [comment]
This was intentional as gutenberg is an editing optimized view while the majority of the feedback we got was that post types that didn't require the visual editor should continue to work as they do now in wp-admin.

Going to close but thanks for the point of feedback as it might become relevant for the 5.0 roadmap.
