### ISSUE TITLE
Error when previewing before updating post

### ISSUE THREAD

**Issue by boemedia** [WordPress/gutenberg#5634]
## Issue Overview
When you add content and try to preview the post, the preview screen keeps pending. After closing and trying to update the post after attempting to preview, you get an error.

## Steps to Reproduce (for bugs)

1. Add content to post
2. Hit preview button
3. Return to post
4. Try to update post

Tested in Firefox 59.0 (64-bits) on a Macbook pro, with Astra theme installed.

## Expected Behavior

I expected the post to auto-save when hitting preview.

## Current Behavior

The preview is not working and initially, there's no error message. On returning to the editor, it's unclear what to do. Trying to save at this stage, gives an unexpected error.

## Possible Solution

Make the post autosave before preview or if it can't auto save, it should give a warning message to manually save before previewing.

## Screenshots / Video

See this video: https://cl.ly/2s0q0M0X3i02

**Comment by aduth** [comment]
Thanks for the report.

The published post preview is known to not be implemented yet, tracked separately at #2544

The crash is certainly a nasty one. From debugging, this appears to impact Firefox specifically, after previewing a post, closing the preview window, then continuing to save the post. This should be fixed in #5645.
