### ISSUE TITLE
Prefix all HTML classes with `wp-` or `g7g-`

### ISSUE THREAD

**Issue by peterwilsoncc** [WordPress/gutenberg#5647]
This is intended to be more specific than #793 (prefix everything).

## Issue Overview

There are a number of HTML classes used in Gutenberg with a high risk of collisions, `components-popover` being one, prefixing HTML classes will reduce this risk. 

This will break back-compat, it would be dandy to get this in before going in to core. 

## Expected Behavior

Gutenburg's CSS and HTML ought not clash with existing themes.

## Possible Solution

Prefixing HTML classes.

## Related Issues and/or PRs

#793

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by youknowriad** [comment]
For me `g7g-` is not a good choice since Gutenberg is just a code name and the components introduced here are global components that can be used in any part of WordPress and even outside WordPress.

Now `wp-` I'm not certain how this will avoid collisions, I expect this to be a prefix that can be already used. Also our current guidelines follow something similar to bem `module-name-component__subselector`. This doesn't mean that we can't have collisions but IMO the risk is small.

I haven't seen reports of conflicting classNames yet.

Not saying we shouldn't do it but maybe not that important. Thoughts @mtias @aduth

**Comment by aduth** [comment]
Yes, part of the naming structure for class names was intentionally prefixing to avoid conflicts, albeit more internal conflicts than those with other plugins. I could imagine _some_ being prone to conflicts, like the example in the original comment. Adding `wp-` could help, though it's certainly making some of these classes very verbose, e.g. `wp-edit-post-meta-boxes-area__container`

**Comment by peterwilsoncc** [comment]
For clarity, I am more concerned about HTML classes output on the front end and than within the WP dashboard (I'd expect plugins to prefix their classes for the dash).

I do agree something like `wp-module-name-component__sub-selector` becomes very verbose but it's the nature of BEM.

I'll put together a PR starting wtih the state classes `(has|is|with)` as a POC.

**Comment by aduth** [comment]
It's not likely something such as `Popover` would be used on the front-end. As I understand it, those components are primarily meant for building the administrative dashboard.

The modifier classes: Well, ideally they're modifier in the sense that even in a general usage outside WordPress, they'd modify _something_, and not be styled independently.

**Comment by mtias** [comment]
Front-end classes should already be prefixed, generally under `wp-block...`. If there are some that aren't, for elements we expect front-end visualization, let's open individual issues to discuss. Popover is not meant to be rendered on the front-end for most cases.
