### ISSUE TITLE
Expose revisions in Template and Template Part List and change icon for reverting

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#56603]
## What problem does this address?

Right now, we surface "clear customizations" as an action folks can take when viewing the template and template part list. In chatting with some folks who work regularly with customers using the Site Editor, they noted that having revisions surfaced there would go a long way to prevent users from accidentally clearing out their customizations and instead offering them an option they are more likely to use/benefit from (looking through revisions). Current view:

![Screenshot 2023-11-28 at 8 54 29 AM](https://github.com/WordPress/gutenberg/assets/26996883/f9a3f56e-128f-475e-8d68-7654ebc8d6b2)

Experimental view with data views work (currently if you just click on the button, it automatically reverts which feels precarious):

![Screenshot 2023-11-28 at 8 56 33 AM](https://github.com/WordPress/gutenberg/assets/26996883/d278dd06-cbb4-4ccc-a96f-23b70c5202b4)

Similar to this: https://github.com/WordPress/gutenberg/issues/52221 
Relates to Data Views work: https://github.com/WordPress/gutenberg/issues/55083

## What is your proposed solution?

Surface revisions in the template and template part lists and/or address this feedback to allow to save a revision when clearing customization per this issue https://github.com/WordPress/gutenberg/issues/52221  cc @WordPress/gutenberg-design  as we think about Data Views work.

- [x] Provide access to revisions for templates and template parts
- [ ] Add confirmation modal for clearing customizations

**Comment by jameskoster** [comment]
Totally. It's already there for pages in the new data view, so it makes sense to align.

<img width="253" alt="Screenshot 2023-11-28 at 19 29 05" src="https://github.com/WordPress/gutenberg/assets/846565/6e8e37f6-9bd8-4115-8a27-ef58308dfd7b">

**Comment by annezazu** [comment]
Fantastic! Let's keep this open to ensure it happens. Also, apologies for uploading the same screenshot twice. Updated the original issue to include the correct new view.

**Comment by annezazu** [comment]
Looping back on this -- here's what the experience is like with 6.5 RC3:

https://github.com/WordPress/gutenberg/assets/26996883/bc40c105-9985-498d-9903-ad3f96ffe64e

As data views work continues, I think two changes would go a long way: change revert icon so it doesn't match the revision icon & surface revisions over destructive actions for templates. Compared to posts or pages, I have a hard time imagining we want destructive actions surfaced so much over information like number of revisions. Just my two cents but, even if it remains there, we need to change the icon.

**Comment by kathrynwp** [comment]
It's fantastic that revisions are coming to the template editor!

Ran into a couple of things while testing ahead of a workshop that I wanted to provide feedback on:

100% agree with @annezazu that having same icon now used for “reset template” and “view template revisions” – is confusing – and risky. For example, someone could easily click on the "reset" icon thinking it will lead to revisions, and as a result, lose all their template customizations – with no way to get them back. 

Also completely agree with @annezazu that a user should be able to manage revision history from the "Manage All Templates" area.

The three dots next to the templates in table (list) view doesn’t seem to do anything anymore. IMO the three dots menu should have the same functionality, whether you're in grid or table view. It's currently very confusing that the three-dots menu allows deletion or reset from grid view, but does nothing at all from table view. 

I also think you should be able to access the options to view revisions, reset/clear customizations, or delete each template from both table/grid views, as applicable. These are three key pieces of functionality, and I think all should be accessible from the Manage All Templates overview, in either layout view.

Finally, I think the terminology for clearing customizations should be consistent across the board. Either "Clear customizations" or "Reset" – but not both (the current scenario), which can be confusing, unintuitive, and again, result in unintentional user actions.

![templates-gh2](https://github.com/WordPress/gutenberg/assets/7662449/f3ace868-929d-4a98-9c18-6011f214ddf9)

![templates-gh1](https://github.com/WordPress/gutenberg/assets/7662449/92ce7e6d-535b-4888-baeb-23fde3521447)

<img width="1099" alt="Blog_Home_‹_Template_‹_Food_Connection_‹_Editor_—_WordPress" src="https://github.com/WordPress/gutenberg/assets/7662449/4c405adf-8dab-40fe-9c8c-69736b0165c9">

Tested with:

WP 6.4.3
GB 17.9.0

**Comment by ntsekouras** [comment]
👋 it seems the revisions action in templates is implemented for a while, but I agree we need to change the icon asap(cc @jameskoster ). Probably we also need to add a modal like we did in sidebar card to confirm, which indicates more the 'destructive' result.

@kathrynwp regarding the Data Views actions you mention are there in the ellipsis menu, but only if they are available. For example if a template has revisions then the action is shown. Additionally there are discussions of removing the ellipsis if no actions are available.

Finally you mention that in the actions are different when changing layouts. That's not the case since the actions are common per list. So if you have noticed something like that it sounds like a bug and we should address it. Can you retest and confirm that the actions are there? Thanks!

**Comment by jasmussen** [comment]
A modal confirm will help. Should the revert option also be in the ellipsis menu, as Kathryn alludes to? That would allow the action to have more context, and have its footprint match its consequences.

**Comment by jameskoster** [comment]
We've gone back-and-forth a bit on whether destructive actions should be given prominence or not :) 

I lean towards them not being surfaced as quick-actions, and https://github.com/WordPress/gutenberg/pull/59551 seeks to achieve this for _pages_. If merged I intend to follow-up with a similar PR for templates. Like Joen says that would solve the icon issue as the action would move to the ellipsis.

**Comment by jameskoster** [comment]
@ntsekouras Looking at the code it seems the revisions action is included for templates:

https://github.com/WordPress/gutenberg/blob/e04cf9ce4f06469c051bb2d4bf093e279cac50e8/packages/edit-site/src/components/page-templates-template-parts/index.js#L413

But for one reason or another it doesn't seem to be working. 

Edit: It seems to work for template parts, but not templates 🤔

**Comment by jameskoster** [comment]
#59551 is merged 🎉 

I opened https://github.com/WordPress/gutenberg/pull/60075 to move the destructive actions in the templates data view as well.

**Comment by kathrynwp** [comment]
Hi @ntsekouras - thanks for looking at this!

> regarding the Data Views actions you mention are there in the ellipsis menu, but only if they are available. For example if a template has revisions then the action is shown.

> Finally you mention that in the actions are different when changing layouts. That's not the case since the actions are common per list. So if you have noticed something like that it sounds like a bug and we should address it. Can you retest and confirm that the actions are there? Thanks!

I've recorded a screencast to try to help clarify what I'm seeing. Thank you!

https://github.com/WordPress/gutenberg/assets/7662449/673cb4d7-9934-440a-9706-79d5c6c58db5

After recording the video I tried making some more changes to a different template (404) and then the ellipsis finally became active in Table view. Not sure why it didn't when I made edits to the Category template...

**Comment by kathrynwp** [comment]
Ran into a situation where you can clearly see here that I made template edits 3 minutes ago... and yet the revisions icon is not active, it's unclickable. There's also still no way to know whether this icon meant is for viewing revisions or resetting the template, as there's no popover/tooltip.

<img width="1509" alt="All_Archives_‹_Template_‹_Food_Connection_‹_Editor_—_WordPress" src="https://github.com/WordPress/gutenberg/assets/7662449/59ea7729-62a4-46f2-b1ec-8fbea27af171">

**Comment by ntsekouras** [comment]
Thanks for the video @kathrynwp and really appreciate the time it took you to make it!

You can only reset theme provided templates, although I get that this can be confusing. We have no current mechanism to track('reset') a template that users create, because they just start empty. The reason why you see some content when creating a new template is just a suggestion from WP, but that doesn't change the fact that the initial content is empty technically.

Regarding the ellipsis menu behaving differently between table and grid view, is that the grid view uses a compact representation of actions and combines all of them in the ellipsis menu. Table view utilizes an API that separates primary actions(with icons outside the menu) and then also combines all of them in the ellipsis menu.

>Ran into a situation where you can clearly see here that I made template edits 3 minutes ago... and yet the revisions icon is not active, it's unclickable. There's also still no way to know whether this icon meant is for viewing revisions or resetting the template, as there's no popover/tooltip.

Regarding the reset `icon` in Data Views, it has already been removed and the reset action has been denoted to secondary, so it's only available through the ellipsis menu. Additionally soon enough I'll open a PR that adds a confirm dialog to clear customizations.

Regarding the `revisions` inactive icons it's because there is only one revision(the initial creation of the template actually with no content). The icon becomes active when perform any additional change and same goes why in that case you don't see the `view revisions` action in Data Views.


I hope all these clarify some things and I'd love if you still find something confusing to let me know.

**Comment by jameskoster** [comment]
@ntsekouras I don't think we can close this yet. The revisions link for templates doesn't appear for me in data views. Strangely it does work for template parts 🤔 


https://github.com/WordPress/gutenberg/assets/846565/5afb11a7-5df3-4734-a3fe-6f53441e4ccd

**Comment by ntsekouras** [comment]
>@ntsekouras I don't think we can close this yet. The revisions link for templates doesn't appear for me in data views. Strangely it does work for template parts 🤔

Hm.. It seems we are using different logic between the sidebar footer and the template actions, both in Data Views and sidebar card actions(ellipsis menu). Yeah, let's keep open to consolidate this last part.

To be clear the difference is that in navigation sidebar we show even the first revision that is from empty content to some content and cannot be restored. So the question becomes if we should disable the revisions link in sidebar navigation if we have only one revision(the initial one) or the other way around and don't check this in data views..
