### ISSUE TITLE
Issue with Preview button

### ISSUE THREAD

**Issue by stefanos82** [WordPress/gutenberg#5688]
This issue is different from #5686 I have previously reported.

I switched to Astra theme by Brainstorm Force that works with Gutenberg and after I finished editing, I did not push "Update", but rather tried to previewed my changes.

As soon as I pressed it, I got stuck in this message:

![image](https://user-images.githubusercontent.com/1777466/37572206-5c860d0e-2b10-11e8-835e-54d5b37e57d5.png)

**Comment by karmatosed** [comment]
This is not something I can replicate in the default theme. I suspect as a result unfortunately this is the theme you are using, so let's try and dig a little more. Do you get this when you just view with the default theme, for example Twenty Seventeen? If you do, what plugins are you using? Maybe we can narrow it down to one of those.

**Comment by stefanos82** [comment]
For plugins I only use `Gutenberg` and `WordPress Importer`.

With `Twenty Seventeen` works as expected, but not with Astra.

**Comment by karmatosed** [comment]
@stefanos82 in this case I think there is something with the theme not Gutenberg. Would you mind reporting this in the theme support forums? https://wordpress.org/support/theme/astra. I think that's probably the best way forward at this point. If you can also in reporting maybe see if you get any console errors, that should help them diagnose more.

Should you not get a response or need to come back, please just update this issue and we can reopen. I am closing for now though, but that's something we can come back to.

**Comment by pphutthavong** [comment]
Hi. We're using stock WordPress, on the twentyseventeen theme on a fresh install and we are getting the same issue. There are no console errors and no network traffic.

**Comment by myleshyson** [comment]
The same thing is happening to me. I can't preview anything until I publish it first...which defeats the purpose. I get the same "Please Wait. Generating Preview..." Message

**Comment by swissspidy** [comment]
I'm experiencing the same issue from time to time and it's really annoying.

It seems like it happens when making some changes but not saving them before clicking on the Preview button. No autosave is happening then I guess.

Also, there's a JS error in the console when performing that action as well:

<img width="644" alt="screen shot 2018-06-19 at 12 28 39" src="https://user-images.githubusercontent.com/841956/41592310-72726f00-73bc-11e8-83bf-15de691a7137.png">

`REQUEST_META_BOX_UPDATES` is from the Redux store in Gutenberg.

`post.min.js` is from Polylang, so I'll see if disabling that plugin resolves the issue.

However, I would still argue for re-opening this issue.

**Comment by designsimply** [comment]
Looping back to note that I just tested with Astra 1.4.8 and WordPress 4.9.8 and Gutenberg 3.5.0 and previews worked as expected. Also wanted to note that if previews are not still not working for you, check to see if the steps noted at https://github.com/WordPress/gutenberg/issues/7852#issuecomment-413049850 trigger the problem for you (that issue is specifically related to previews and autosaves).
