### ISSUE TITLE
Pattern categories referenced as tags in site editor post taxonomies panel

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#57076]
Looks like #57049 has led to the pattern categories UI to suggest these are "tags", though they are categories. Perhaps this panel should be updated to use the existing categories UI anyhow; instead of the FormFieldToken, which is used for tags on posts. 

As an aside, I think it'd be fine to just have "Categories" as the panel title, as we do the same on the post editor (and the UI already suggests this is a custom post type via the tab). 

cc @youknowriad

![CleanShot 2023-12-14 at 13 08 01](https://github.com/WordPress/gutenberg/assets/1813435/d90b0632-a8b3-4383-9629-c8bc066e27fb)
![CleanShot 2023-12-14 at 13 07 20](https://github.com/WordPress/gutenberg/assets/1813435/40fab8ba-ac9c-4d37-b3ee-ebf5781a3e6a)

**Comment by youknowriad** [comment]
That's actually they seem to be using the `post_tag` taxonomy and not some other taxonomy.

**Comment by youknowriad** [comment]
We can probably hard code a label if we detect that it's the "wp_block" post type but I think this was wrong from the start, they should just have been named "tags" if they used the "post_tag" taxonomy.

**Comment by richtabor** [comment]
Yea, or just used categories properly. 😬

What do you think is the best way forward?

**Comment by youknowriad** [comment]
I think it can't be categories properly because that taxonomy is hierarchical, and here it's just "tags" actually but we want it to have "categories" as label. The ideal would have been a dedicated taxonomy or embracing the "tags" labels everywhere.  If it's too late for the latter, I think our path forward is to just hard code a specific "add new tag" label for this particular post type.

**Comment by youknowriad** [comment]
I'll take a deeper look tomorrow though :) and I'll have a better answer.

**Comment by youknowriad** [comment]
My bad here, it turns out, we're doing things correctly with a dedicated taxonomy. The problem is that the labels were not all defined and there's an automatic fallback to tags labels.

**Comment by glendaviesnz** [comment]
> Perhaps this panel should be updated to use the existing categories UI anyhow; instead of the FormFieldToken, which is used for tags on posts.

Just to confirm the thinking here. As Riad has mentioned we did not use WP categories here as they are hierarchical and we needed a flat taxonomy to match with the existing pattern categories which are also flat. The naming of `categories` instead of `tags` was also chosen to match with the existing pattern categories as the alternative of renaming the existing .org and theme categorisation to `tags` did not seem like the right approach.

Thanks for adding the extra labels.
