### ISSUE TITLE
SelectControl: Suffix wraps too aggressively

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#57217]
<img width="130" alt="Screenshot 2023-12-19 at 13 06 39" src="https://github.com/WordPress/gutenberg/assets/846565/e38ac6bb-9d3e-4b09-a842-6e57ac58d18f">

Even when the suffix is relatively short (see screenshot above) it wraps unnecessarily.

**Comment by mirka** [comment]
The padding is intended to be added by using the `InputControlPrefixWrapper`/`InputControlSuffixWrapper` utility component, as noted in the [descriptions](https://wordpress.github.io/gutenberg/?path=/docs/components-selectcontrol--docs) for the `prefix`/`suffix` props.

The chevron icon disappearing is also intentional, as it is a way to override the chevron, not only add more elements to it. (The chevron can be added back by the consumer if desired.)

Could we maybe see an example of a design that cannot be achieved with the current API design? A lot of things should be possible with the appropriate CSS. The click through behavior is also possible with the same approach currently used for the default chevron, if you refer to the styles used in this [wrapper component](https://github.com/WordPress/gutenberg/blob/5b7f662fc5f3886fb91c9d6827fbbb67a304eee9/packages/components/src/select-control/chevron-down.tsx#L17).

**Comment by jameskoster** [comment]
Apologies, I totally missed `InputControlPrefixWrapper`/`InputControlSuffixWrapper`.

The suffix wrapping still seems to be an issue though.

> The chevron icon disappearing is also intentional

Perhaps there is additional context that I am missing, but I don't understand why the presence of a suffix should result in the omission of the chevron, that seems quite unrelated? My expectation is that a suffix would be additional to the chevron, and that removing the chevron would be a separate prop. Though I'm not sure that should really be possible... to me the chevron is a defining visual element in the design of any SelectControl – I don't think I've seen it removed like this in any other design system.

In terms of design this is what I had in mind:

<img width="880" alt="Screenshot 2024-01-04 at 10 24 12" src="https://github.com/WordPress/gutenberg/assets/846565/4bad9408-80f7-46b7-b1a6-194409fd18d2">

If this is achievable then great! But I'm not entirely convinced that the chevron should be removed as a default experience when using this component with a suffix.

**Comment by mirka** [comment]
> Perhaps there is additional context that I am missing, but I don't understand why the presence of a suffix should result in the omission of the chevron, that seems quite unrelated?

I get where you're coming from. What we're aiming for is a simple API that is predictable across similar components (e.g. InputControl and SelectControl both have this `prefix`/`suffix` API), and is generic enough to cover all use cases without needing to add more props every time a new use case is found. In this case, the single `suffix` prop entirely replacing the default chevron suffix serves a lot more use cases than not, like if you want your custom suffix to come after the chevron, or if you want to use a different chevron icon or color. And frankly, adding a suffix to a Select is pretty niche so we don't have enough established patterns to assume what "most" people would need.

> In terms of design this is what I had in mind

There are a couple of paths we can take depending on the exact requirements.

- If you need the width of the Select to dynamically adjust to the entire length of the text, we probably want to make a new custom "Pagination Select" component, or use CustomSelectControl for more design flexibility. (With a standard SelectControl, you'd need to set a fixed width on the suffix if you also want click through. This is a limitation when using standard `<select>` elements.)
- If you don't need the prefix/suffix text to be in a lighter color, we could just make it part of the `<option>` text when currently selected. This is probably the easiest compromise.

**Comment by jameskoster** [comment]
At the primitive level I feel this approach errs a little too much on the side of flexibility versus consistency in design. For me a trailing chevron is fundamental to any select control – it's a universal indication of the behavior a user can expect on interaction. I appreciate that opinion verges into subjectivity though, and I now better understand the implementation, so thank you for explaining ❤️

> If you don't need the prefix/suffix text to be in a lighter color, we could just make it part of the <option> text when currently selected. This is probably the easiest compromise.

If this doesn't cause i18n issues it could be the way to go 👍

**Comment by jameskoster** [comment]
Updating this issue to concentrate on the suffix wrapping. I'll open issues for other design details.

**Comment by mirka** [comment]
This can be controlled by the consumer if they set a `width` on the suffix, for example `width: max-content` in this case. Does that work for you?

I don't think we are ready to change any defaults at this point, since the suffix construct is generic and un-opinionated by design, and we don't have enough use cases of the suffix pattern to dictate what the "majority" of use cases would want. Though, we might consider a more ergonomic API for this setting if it comes up a lot.

**Comment by jameskoster** [comment]
After some more digging, the wrapping only seems to occur if the suffix (or prefix) includes a space. That seems unexpected to me, but it can be fixed locally by adding `white-space: nowrap;`. If that's not a good candidate for addition then I guess we can close this issue :)
