### ISSUE TITLE
Footnote: Wrong link when adding more than 9 footnotes

### ISSUE THREAD

**Issue by renancarvalho** [WordPress/gutenberg#57321]
### Description

When adding more than 9 footnotes, the hyperlink generated by the footnotes is not including the second digit of the number bigger than 9. For instance, when having 10 footnotes, only the number 1 gets hyperlinked and 0 is not clickable.

## Step-by-step reproduction instructions

Add more than 10 paragraphs in the editor
Go one by one adding footnotes
After the 9th one, the hyperlink is wrongly created.

For instance, in this example only number 6 is clickable
<img width="388" alt="image" src="https://github.com/WordPress/gutenberg/assets/2653810/10d496ff-c917-4287-9404-096258aa288a">

### Screenshots, screen recording, code snippet

<img width="388" alt="image" src="https://github.com/WordPress/gutenberg/assets/2653810/163a75f4-b591-4731-b162-11e66e12433e">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by t-hamano** [comment]
Thanks for the report.

Do you know in which WordPress/Gutenberg version and in which browser this problem occurs?

I was unable to reproduce it in the following environment.

- OS: Windows 11
- WordPress: 6.4.2
- Gutenberg: 17.3.0 (Can't reproduce even if disabled)
- Browser: Chrome 120.0.6099.130, Firefox 121.0
- Theme: Twenty Twenty-Four

![footnotes](https://github.com/WordPress/gutenberg/assets/54422211/33e63e32-8aff-4d0b-84ae-7f31b0610b38)

**Comment by jp-imagines** [comment]
I was working with someone who experienced this on their site, and I was able to replicate the same behavior on a test site of my own. Both sites hosted at WordPress.com, WordPress version 6.4.2, Gutenberg 17.2.4. Replicated on Mac (Sonoma 14.1.2) in Firefox 121.0 and Chrome 120.0.6099.199. Replicated on the [Bitacora theme](https://wordpress.org/themes/bitacora/) and [Storefront](https://wordpress.org/themes/storefront/), as well as Twenty Twenty-Four.

The HTML output shows the `<a>` tag only on the first digit of any two-digit footnote number: 
![footnote](https://github.com/WordPress/gutenberg/assets/5630717/f46dfea2-973e-4b2a-9d44-730aabcaca9c)

Edited to add: The person I assisted noticed that older content (from 2020-2021) which was updated to use footnotes **don't** experience this issue; only newer content on their site (2022 and later) is affected. I was able to replicate this as well: after editing a post on my test site from 2021 (adding 5 paragraphs of lorem ispum content and adding 10 footnotes at random), the tenth footnote is linked properly instead of having just the `1` linked.

**Comment by t-hamano** [comment]
I tested it again and was able to reproduce it. Another thing I noticed is that an asterisk appears immediately after applying the footnote. Select that block again and the asterisk will be converted to actual numbers.


https://github.com/WordPress/gutenberg/assets/54422211/c4098cf4-ff96-4d53-a7c1-95340a46491e

**Comment by t-hamano** [comment]
I used `git bisect` to identify the PR where this problem occurred.

- #54505

By investigating the changes in this PR, we may be able to identify the cause.
