### ISSUE TITLE
Style Book: Add item to represent global Typography and Color settings

### ISSUE THREAD

**Issue by creativecoder** [WordPress/gutenberg#57323]
## What problem does this address?

In observing users interacting with Style Book this week, most immediately started clicking blocks on the canvas and then editing the block styles in the sidebar--this works really well for navigating Global Styles settings!

However, this meant that they missing seeing the top level global typography and color settings.

## What is your proposed solution?

Represent the global typography and color settings somewhere on the canvas, so clicking there navigates directly to those settings.

**Comment by ramonjd** [comment]
I like this idea. 👍🏻 

Since the examples are all blocks, maybe we could have a dedicated global or "site-wide" tab. Ignore the design, but just illustrating the point 😄 

<img width="651" alt="Screenshot 2023-12-22 at 12 23 42 pm" src="https://github.com/WordPress/gutenberg/assets/6458278/dee2dbd3-5bd6-4635-8b29-49341d474337">


I'm also wondering about the examples for the page and how explicit we'd need to be about where go, e.g., would "background color" need a distinct hotspot or would clicking anywhere on the background take us to the background color panel?

What about layout?

I'm sure we could come up with some fun examples. Just stuff to think about. 

Also, we could discuss with @noisysocks when he's back.

**Comment by ramonjd** [comment]
A "color" tab is being proposed over at:

- https://github.com/WordPress/gutenberg/issues/53431

It wouldn't be so much of a stretch to add a Typography, or some generic tab to house this stuff.

**Comment by richtabor** [comment]
A "Text" category already exists, but we should add font size presets to it, as suggested in #53431. I'm going to close this as a duplicate to #53431, as that encapsulates this idea. 

![Image](https://github.com/user-attachments/assets/36049534-cdde-4aa3-83af-03744be9117a)
