### ISSUE TITLE
add_theme_support('editor-gradient-presets', [ ]) notice / warning

### ISSUE THREAD

**Issue by langhenet** [WordPress/gutenberg#57344]
### Description

The add_theme_support feature to disable the editor gradients is not working properly.

If you implement it (`add_theme_support('editor-gradient-presets', [ ]);`) it gives a notice (warning in php 8.1) :

`Trying to access array offset on value of type bool`

### Step-by-step reproduction instructions

1. Add `add_theme_support('editor-gradient-presets', [ ]);` to the functions.php of your theme
2. Edit or add a page / post
3. check error log to see the notice / warning)

### Environment info

- Wordpress 6.4.2
- Gutenberg is not installed as a plugin

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

I tested with TT1 and fTT4 themes, but could not see any error messages. What theme are you testing with?

**Comment by t-hamano** [comment]
I tried testing again with WP6.5-RC1, but I still can't reproduce it. If I specify an empty array, no error message will be displayed and the gradient preset will not be displayed as expected.

I would like to close this issue, but if the issue is still not resolved, please feel free to comment.

![image](https://github.com/WordPress/gutenberg/assets/54422211/6f972a1c-79d4-487f-a2db-bfad94b9c282)
