### ISSUE TITLE
File Block: PDF preview not working on Classic Themes

### ISSUE THREAD

**Issue by liviopv** [WordPress/gutenberg#57419]
### Description

Unlike Block Themes, Classic Themes are not displaying previews for PDF when using the File Block.

related issues:
- https://github.com/WordPress/gutenberg/issues/46382
- https://github.com/WordPress/gutenberg/issues/15097
- https://github.com/WordPress/gutenberg/issues/34825

### Step-by-step reproduction instructions

1. Install a classic theme
2. Add a File Block with a PDF
3. Make sure "Show inline embed" is selected
4. Open the page

### Screenshots, screen recording, code snippet

Twenty Sixteen, Editor
![CleanShot 2023-12-28 at 11 18 51@2x](https://github.com/WordPress/gutenberg/assets/14153300/852f0202-e485-412c-897f-9cfe20629214)

Twenty Sixteen, frontend
![CleanShot 2023-12-28 at 11 14 40@2x](https://github.com/WordPress/gutenberg/assets/14153300/cc2525ac-0745-4908-aa73-9d0b4f9d6d92)

TT4, frontend
![CleanShot 2023-12-28 at 11 15 10@2x](https://github.com/WordPress/gutenberg/assets/14153300/2efd3a00-21de-480d-8c62-ee48df2797b4)

### Environment info

- WordPress 6.4, Gutenberg 17.3
- Chrome 120, Mac OS Sonoma

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

My understanding is that the Interactivity API is used for previewing the file.

It has been reported that this API does not work properly in the classic theme. This issue is fixed in #57396 and scheduled to ship in Gutenberg version 17.4.

I would like to close this issue, but if you are still experiencing issues with Gutenberg version 17.4, please comment.
