### ISSUE TITLE
Footnotes Block: Asterisk appear instead of number

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#57598]
### Description

When I apply footnotes to inline text, the asterisk appears instead of the sequential number. If I select the RichText with that asterisk in it, the correct number seems to display.

If I disable the Gutenberg plugin, this problem will not reappear.

When I used git bisect to find the cause, it seems that the problem first occurred in #43204.

### Step-by-step reproduction instructions

Check the text immediately after applying the footnote block.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/1408252c-82ed-4540-90a8-3b4060dbf50d

### Environment info

- Gutenberg version: 17.4.1
- WordPress version: 6..4.2
- Browser: 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mcsf** [comment]
Thanks for the report. I'm noticing something which feels similar, whereby indices aren't properly updated when blocks aren't reordered:


https://github.com/WordPress/gutenberg/assets/150562/760b3a91-64fe-48b1-9dc9-6ea39e83189e

**Comment by mcsf** [comment]
Very quick debugging: In both cases (with asterisks when inserting a new footnote, and with stale indices when reordering blocks) the actual updating of rich-text values is done at the time of the action. Which is as expected. So is the problem that the values aren't properly flushed elsewhere?

Since you bisected the bug down to #43204, some hypotheses come to mind:
- Now that we deal with RichTextData instances, some piece of the system is reusing the same object instance, which causes some strict equality check to wrongly assume that there are no changes.
- Alternatively, [RichTextData's interface](https://github.com/WordPress/gutenberg/pull/43204/files#diff-30f49ba076928df4fcb8cc0fc0e6123fe85a619dcd9721686f5429de8ab1a2ccR147-R178) is failing to update internal references.
