### ISSUE TITLE
Command Palette lets unauthorized users switch to Code Editor

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#57604]
### Description

When access to the Code Editor is disabled (via $settings['codeEditingEnabled'] = false; ), it can still be accessed using the Command Palette.

### Step-by-step reproduction instructions

1. Filter the Block Editor settings to disable codeEditingEnabled in the block_editor_settings_all filter

add_filter( 'block_editor_settings_all', 'disable_code_editor' ), 10, 2 );

function disable_code_editor( $settings, $context ) {
    $settings['codeEditingEnabled'] = false;
    return $settings;
}

3. See that Code Editing is disabled via traditional means. It's blurred out in the Menu, and ctrl-shit-alt-M does nothing.
4. Open the Command Palette and select "Toggle code editor"
5. See that you are now in the Code Editor

### Screenshots, screen recording, code snippet

![code-editor-disabled](https://github.com/WordPress/gutenberg/assets/945157/45338eab-11c6-4064-a4b3-cea1a80cc50c)

![toggle](https://github.com/WordPress/gutenberg/assets/945157/404cafe8-0410-469f-9176-b8386b388944)

![wrong](https://github.com/WordPress/gutenberg/assets/945157/9f5c8a8e-62ce-4f95-96c1-bcc8962ad3ed)

### Environment info

WP 6.4.2, no Gutenberg plugin

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.  I was also able to reproduce this problem.

Also, while looking for a solution, I discovered an issue with inconsistent command actions, and issues with the Site Editor.

In the Post Editor, there is only one action: "Toggle code editor".

![image](https://github.com/WordPress/gutenberg/assets/54422211/b164fc7a-416e-41a6-8feb-09bf974d1fef)

In the Site Editor, on the other hand, the commands change depending on the editor context.

![image](https://github.com/WordPress/gutenberg/assets/54422211/879fc98d-c58c-43d1-b768-bac856380ccb)

![image](https://github.com/WordPress/gutenberg/assets/54422211/9ce6f4fa-4950-4ab8-a253-644d6c9f1855)

Furthermore, in the Site Editor, the hook that disables the editor type does not seem to be applied.

```php
function disable_code_editor( $settings, $context ) {
	$settings['codeEditingEnabled'] = false;
	return $settings;
}
add_filter( 'block_editor_settings_all', 'disable_code_editor' , 10, 2 );
```

![image](https://github.com/WordPress/gutenberg/assets/54422211/cbfb2b26-14ca-4bb9-b474-41450c8e4e6a)

Therefore, in order to comprehensively resolve this issue, I think we will probably need to follow the steps below.

- [x] Improve command consistency in the Post Editor and the Site Editor:
  - #58148
- [ ] Ensure that `codeEditingEnabled` and `richEditingEnabled` block editor settings are correctly applied to the Site Editor as well.
- [x] When `codeEditingEnabled` or `richEditingEnabled` is `false`, disable command actions for it.
  - #59299

**Comment by t-hamano** [comment]
Update:

> In the Post Editor, there is only one action: "Toggle code editor".
> In the Site Editor, on the other hand, the commands change depending on the editor context.

This issue was resolved by #58148. It seems that it has been unified to `Open code editor/Exit code editor`.

**Comment by t-hamano** [comment]
Update: In #59299, switching modes via the command palette is now disabled when only one editor mode is available.

**Comment by senadir** [comment]
Hey! Is this issue is valid?

>  Ensure that codeEditingEnabled and richEditingEnabled block editor settings are correctly applied to the Site Editor as well.

Seems unrelated to this package maybe and should be a separate issue.

**Comment by ndiego** [comment]
> Ensure that codeEditingEnabled and richEditingEnabled block editor settings are correctly applied to the Site Editor as well.

I just tested and `codeEditingEnabled` is applied correctly in the Site Editor and disabling the Code Editor does also remove the option from the Command Palette. Since the original issue is now solved, I am going to close this issue. 

In my testing, I did notice that setting `richEditingEnabled` to `false` in the Site Editor does not work. It does in the Post Editor. I think this should be a separate issue, and I am not even sure you should be able to disable `richEditingEnabled` in the Site Editor. It's unclear to me what value this would provide 🤔

**Comment by t-hamano** [comment]
@ndiego Thanks for checking out this issue!

> In my testing, I did notice that setting `richEditingEnabled` to `false` in the Site Editor does not work.

This is because `richEditingEnabled` is forced to be true in the site editor:

https://github.com/WordPress/gutenberg/blob/c2a8564f6f8dda43d6931ca445ebfdc5352d77ca/packages/edit-site/src/components/block-editor/use-site-editor-settings.js#L155-L159

I would like to consider separately whether it is possible to disable this setting in the site editor as well, and whether doing so would be worthwhile.
