### ISSUE TITLE
How to open custom Media tab using MediaUpload?

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#5780]
Hi,

I've created a custom media tab : https://phpbits.d.pr/VrxLPJ and I want to open it automatically on button click using wp.blocks.MediaUpload. Checked and it seems that there are no other attributes that I can use. Would you mind enlightening me if this is possible? Thank you very much!

Tagging @aduth since you've been very helpful on my previous issues. Thanks :) 

Cheers,
Jeffrey

**Comment by aduth** [comment]
As best I can tell, the `<MediaUpload />` component does not include this functionality, and I'm not sure it's a common enough behavior to bake in, and also ties its implementation to the current UX of the media modal (preventing future design iterations).

Since `<MediaUpload />` is just a layer atop the existing media library code, you could similarly copy and adapt to your own needs.

Alternatively or in addition, the specific behavior you're looking for appears to be made possible by the "Library" mode state.

In classic editor, I can toggle active menu of the opened media modal by slug:

```js
wp.media.frame.setState( 'gallery' )
```

**Comment by phpbits** [comment]
@aduth No worries! I just used the core thickbox ;) Cheers!

**Comment by r-a-y** [comment]
@phpbits - Just came across this issue and was wondering how you ended up calling your custom wp.media state via thickbox for your Gutenberg block?

**Comment by isvictorious** [comment]
> @phpbits - Just came across this issue and was wondering how you ended up calling your custom wp.media state via thickbox for your Gutenberg block?
> 
> Update - I ended up following aduth's advice and adapted `<MediaUpload />` for my own needs.

Care to share how you solved?
