### ISSUE TITLE
Is there any way to change only the `fontWeight` of the `<summary>` part of the details block?

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#57970]
### Discussed in https://github.com/WordPress/gutenberg/discussions/57921

<div type='discussions-op-text'>

<sup>Originally posted by **kohheepeace** January 17, 2024</sup>
## Problem
As shown in the following video, changes to the font weight of the details block apply to the entire details block, **both `<summary>` part and `paragraph` part.**

https://github.com/WordPress/gutenberg/assets/29557494/5ba12882-9784-431f-9cae-ba5cae0e6682

## Question
Is there any way to change only the `fontWeight` of the `<summary>` part of the details block?

*P.S.
I also want to change `font-size` of only `<summary>` part.
</div>

**Comment by eric-michel** [comment]
Quite late to the party here, but @t-hamano you can accomplish what you're looking for like this:

- Set the styling you want for your `summary` element to the overall block (font weight, font size, etc).
- Add a `group` block into the "This is a paragraph part..." section
- Use that `group` block to override the font weight and font size settings that were set on the parent block

It's a bit clunky because the `<summary>` element is not its own block despite being its own tag, so the styling is set on the overall `<details>` element itself (and thus that styling then gets applied to all content within the `<details>` tag, not just the `<summary>` tag). A `group` block lets you override that styling.

**Comment by t-hamano** [comment]
@eric-michel Thanks for the reply.

I found that you submitted #59384 suggesting splitting the `summary` element. Therefore, let's close this issue and focus the discussion on #59384.
