### ISSUE TITLE
Text styling bleeding into placeholder states

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#58151]
I noticed today that the text stying is being applied inappropriately to the placeholder states. I would expect that no text styles should bleed into the editor UI. Even text-transform is being applied (tested via https://github.com/WordPress/gutenberg/pull/58142). 

https://github.com/WordPress/gutenberg/assets/1813435/adbe11bf-c2ef-470d-a0b0-90fb3cb61200

**Comment by MaggieCabrera** [comment]
I was thinking about this, and there are two ways I see to solve this: we either reset the CSS of the placeholder component (and we will have to do this again for every global style control that we introduce in the future that may affect the component) or we make the Global Styles CSS to target everything but the components, which is also very tricky to do, since what's affecting this is the rules we set into `body{}` directly. I'm not sure which I like the best of the two, to be honest...

**Comment by carolinan** [comment]
I am not sure if it is even related but the border radius on the image block is bleeding into the placeholder too. I did not discover it until yesterday but it also happens on 6.4 without Gutenberg active. Not on 6.2 or 6.3.

**Comment by MaggieCabrera** [comment]
> I am not sure if it is even related but the border radius on the image block is bleeding into the placeholder too. I did not discover it until yesterday but it also happens on 6.4 without Gutenberg active. Not on 6.2 or 6.3.

It must be for different reasons, in this case, when we style the text "element" what we are adding is CSS into the body tag, which then bleeds. The image block styles are targeting something different. Do you have an issue for that?
