### ISSUE TITLE
Post categories are re-fetched from the server with every render request

### ISSUE THREAD

**Issue by Clorith** [WordPress/gutenberg#5832]
## Issue Overview
Whenever the categories panel under Settings for a post is set to render, it re-fetches the categories from the back end. This happens if you toggle the Categories section to sow/hide, and even if you toggle the Settings slide-out panel visibility.

The time taken to fetch categories increases with the amount of categories available to a site, with 1-2 categories it's pretty much instant, with 4 I can see the lag before the content has been fetched.

## Steps to Reproduce (for bugs)
Add 4 or more categories to a site
Click the toggle the Categories picker for your post
Click again to hide it
Click a third time to re-display the categories

## Expected Behavior
The categories should be stored after being initially fetched, making subsequent toggles instant.

## Screenshots / Video
![categories-refetch](https://user-images.githubusercontent.com/468735/37999895-5513e386-3225-11e8-89be-3d5406282362.gif)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by johnwatkins0** [comment]
This happens because [the hierarchical terms selector component](https://github.com/WordPress/gutenberg/blob/master/editor/components/post-taxonomies/hierarchical-term-selector.js) mounts and unmounts each time the panel is opened/closed. The same applies to the non-hierarchical terms component. 

Would it make sense to move term-related fetch/create operations to the editor redux store so the data can persist between unmounting/mounting? I might give it a shot just to see how it goes. There might be a simpler alternative I'm not thinking of.

**Comment by danielbachhuber** [comment]
This has since been addressed by moving term fetching to `core-data`.
