### ISSUE TITLE
Link Control: Can't switch links in the same paragraph in Firefox

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#58322]
In Firefox, when I have multiple links in the same paragraph I cannot easily switch between them using my mouse:

https://github.com/WordPress/gutenberg/assets/275961/3f7db0d2-271b-4472-bb76-bc01caa07bea

This bug seems to only effect Firefox.

There is a potential fix here: https://github.com/WordPress/gutenberg/pull/58317#top though it doesn't work for me

**Comment by jeryj** [comment]
The fix doesn't work for me either. It seems related to the click caret placement being handled _on the editor_. On Chrome, when you click a new link, it moves the text caret to the location you clicked. On Firefox, it leaves the caret where it was before, thinking you are still clicking on the previous location.

Notice how the caret does not move to the new clicked location in this video:

https://github.com/WordPress/gutenberg/assets/967608/e7e9b235-11ff-40ad-ad45-86fea15b9ab1

**Comment by jeryj** [comment]
I think this is a deeper bug, and not related to LinkControl. The same issue of the caret not being moved to the new selection happens when you close a popover from the Block Toolbar as well. 

This video shows the caret, then clicking to open a popover in the block toolbar, then clicking a new spot _in the same paragraph_ and the caret is not moved to the new location.

https://github.com/WordPress/gutenberg/assets/967608/550ec9b3-0aa4-4f08-b0a6-28f0d62206d1

**Comment by scruffian** [comment]
This seems to NOT be a bug with Link Control - you can reproduce the same issue by opening the options menu for a block and then clicking inside the same paragraph

**Comment by scruffian** [comment]
I've done some exploration here but I don't have a solution yet. The difference is that when you focus back into the paragraph in Firefox, the calculations inside `applySelection` don't think that the range is equal, whereas in Chrome it does.
