### ISSUE TITLE
Embeds captions miss a "placeholder" text

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#5839]
While images, galleries, cover image, have a "placeholder text' for the caption field, e.g.:

<img width="337" alt="screen shot 2018-03-28 at 12 10 45" src="https://user-images.githubusercontent.com/1682452/38023516-d28e7a30-3282-11e8-8e80-3c1ff855f496.png">

...seems the embed block doesn't have any default "placeholder text":

<img width="951" alt="screen shot 2018-03-28 at 12 11 54" src="https://user-images.githubusercontent.com/1682452/38023557-ec5fe0e8-3282-11e8-8186-4552f4b6b7af.png">

making a bit difficult to even see there's an editable field.

**Comment by karmatosed** [comment]
If embeds can have a caption then they totally should have the same placeholder. I agree to fix that and make sure we have them on all blocks that have captions. Looking the video block without embed doesn't - which is why I think this hasn't come through.

![2018-03-28 at 12 41](https://user-images.githubusercontent.com/253067/38026824-77057ce2-3285-11e8-881b-a1f11d2f0c42.png)

**Comment by apmatthews** [comment]
It looks like this may have been indirectly addressed. I couldn't find a specific commit that would have addressed it. However, testing on master, I found that the audio, video, embed, image, and gallery blocks all had placeholder text for captions.

**Comment by ajitbohra** [comment]
works as expected on the master
