### ISSUE TITLE
Proposal: Standardize the layout of Component documentation

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#58566]
All of the @wordpress/components package components are documented in the [Component Reference](https://developer.wordpress.org/block-editor/reference-guides/components/). 

If you take a look at a few of the components ([BaseControl](https://developer.wordpress.org/block-editor/reference-guides/components/base-control/), [Animate](https://developer.wordpress.org/block-editor/reference-guides/components/animate/), [BoxControl](https://developer.wordpress.org/block-editor/reference-guides/components/box-control/), etc.) you will find that the documentation layout for each varies greatly. Let's standardize this. Not only will it make the documentation more readable for developers trying to use the docs, but it will also address numerous formatting issues. 

I am happy to take on this project, but welcome feedback so we can settle on a defined format, which we can then document for future components. As an initial suggestion, I propose we use a format like the following. It's simple to implement and will translate well from markdown to the Block Editor Handbook.

# [Title of component]

[Description of the component]

## Design guidelines (optional)

[Explanation of design guidelines]

### Subsection 1 (optional)

[More explanation of design guidelines]

## Usage

[Provide info on how to use the component with code examples]

### Prop 1

[Description of Prop 1]

- Required: Yes | No
- Type: `boolean`, `string`, etc.
- Default: (If applicable)
- Allowed values: (If applicable)

### Prop 2

[Description of Prop 2]

- Required: Yes | No
- Type: `boolean`, `string`, etc.
- Default: (If applicable)
- Allowed values: (If applicable)

**Comment by bph** [comment]
That's a great idea. Before going down the route, I am curious where you see [the storybook in this effort. ](https://wordpress.github.io/gutenberg/?path=/docs/docs-introduction--page)
At first glance, it's a much better developer experience, where you can find most of the information and see a live preview of the component. 

**Examples:** 

- [BaseControl](https://wordpress.github.io/gutenberg/?path=/docs/components-basecontrol--docs)
- [Animate](https://wordpress.github.io/gutenberg/?path=/docs/components-animate--docs)
- [BoxControl](https://wordpress.github.io/gutenberg/?path=/docs/components-experimental-boxcontrol--docs)

Those seem to be fairly standardized already.

**Comment by ndiego** [comment]
> Before going down the route, I am curious where you see [the storybook in this effort.](https://wordpress.github.io/gutenberg/?path=/docs/docs-introduction--page)

Yeah, Storybook is fantastic, but unless we were to remove the Component Reference from the Block Editor Handbook, we would still be left with the same issues, and these non-standardized readmes would still exist in GitHub.

With a defined format for the docs, I think I could take care of all the reformatting in less than a day. 🤞

**Comment by fabiankaegy** [comment]
To be honest I kind of thought this already was the standard 🙈😅

but therefore it’s probably a good thing to just document and enforce a little more.

**Comment by ndiego** [comment]
> To be honest I kind of thought this already was the standard 

Yeah, most of the component docs are 80-90% in this format, but some vary greatly.

**Comment by justintadlock** [comment]
Sounds like a good plan to me. Consistent patterns makes it easier to parse what's on the page and find what you're looking for.

**Comment by mirka** [comment]
> unless we were to remove the Component Reference from the Block Editor Handbook, we would still be left with the same issues, and these non-standardized readmes would still exist in GitHub.

It'd be great if anyone has the bandwidth to rework the ones with non-standard readmes! No issue with that.

I'll just note as some background context, @ciampo and I have been somewhat reluctant to spend too much time on reformatting, since we think ultimately it would be more sustainable to **drop** this duplicate maintenance of documentation. We've basically gone through the entire components package in these past two years, cleaning up inaccuracies in the manually maintained readmes. They are bound to accumulate inaccuracies and missing props over time. We've been investing in TypeScript and JSDoc annotations in a way that could possibly replace the manual readmes.

A low-effort way to achieve that right now would be to straight up replace the entire "Usage" section with a link to the respective Storybook docs page. As a downside, there would be searchability implications if anyone were searching for a prop name directly (in-site or in a wider search engine like Google). But I've floated this idea to some documentation and DevRel folks at WordCamps, and they generally seem ok with it.

A more high-effort approach would be to auto-generate the "Usage" section from JSDoc and TypeScript annotations in the code, similar to how the Storybook documentation is auto-generated.

I personally think we could try the low-effort approach first, and see if people still feel the need to invest in the high-effort approach.

What do folks think? How critical is it to have detailed component docs mirrored in the Block Editor Handbook, when a more visual, interactive, and likely accurate version is available one click away in Storybook?

**Comment by Mamaduka** [comment]
I really like the new React doc's structure, especially the overview section. Example:  https://react.dev/reference/react/Suspense.

If we decide to leverage auto-generated Storybook documentation, it would also be good to have a standardized layout there. I don't know if "layout muscle memory" is a thing, but it definitely helps to know where to look for specifics.
