### ISSUE TITLE
Desktop Navigation flashes briefly on load before Mobile Navigation JS kicks in

### ISSUE THREAD

**Issue by tomxygen** [WordPress/gutenberg#58724]
### Description

If the Gutenberg plugin is installed, when loading any page of a website on mobile, the mobile menu is briefly shown ad it is on desktop, and then collapsed in the hamburger menu.
See the attached screen recording.

### Step-by-step reproduction instructions

1. add a navigation menu 
2. open any page on mobile, the menu should look fine in its hamburger menu
3. install the Gutenberg plugin
4. reopen any page on mobile.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/47855768/07dcc688-0d68-4614-9b61-f40e5544bceb

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ResponsiveFlow** [comment]
@jordesign I saw the "needs testing" flag.
is there any way I can help with that?

**Comment by ResponsiveFlow** [comment]
the issue is now present in WordPress 6.5 beta 1, even without the Gutenberg plugin installed.
cc. @jordesign @fabiankaegy

**Comment by fabiankaegy** [comment]
I am able to replicate this in Beta 1 also. Thaks for the ping! 

You can see it happen if you enable network throteling. My assumption is that it happes because the JS only gets loaded initialized after the page loads here. 

https://github.com/WordPress/gutenberg/assets/20684594/8c4d3774-9438-4d4f-95d7-daf3966bb8ba


Pinging some of the Interactivity API folks: @luisherranz @juanmaguitar @gziolo @DAreRodz @c4rl0sbr4v0 @michalczaplinski

**Comment by fabiankaegy** [comment]
As far as I can tell the issue here is that the logic that determines whether the mobile menu should be shown now happens entirely in JS. It is invoked by the `data-wp-init` directive which calls this callback here:

https://github.com/WordPress/gutenberg/blob/01708f1990435c42b047078e1a8e928f808f3a2b/packages/block-library/src/navigation/view.js#L204-L223

I don't think we can pre set the `isCollapsed` context on the server since we don't know the actual viewport there. 

But I wonder if there isn't a way thtough a script in the head of the document to set the propper context not after the compoent renders but before it renders.

**Comment by DAreRodz** [comment]
Thanks for the ping, @fabiankaegy. 😊

I'm also able to reproduce the issue. Regarding what you mentioned about setting the context in advance, it wouldn't work either because the context is consumed during the interactive blocks hydration. You would need to wait for the browser to download and execute the Interactivity API runtime to see the Navigation block collapse.

However, I guess all this logic could be implemented using only CSS... 🤔

Pinging @scruffian as he was involved in the implementation.

**Comment by cbravobernal** [comment]
I can confirm that this error is not happening in 6.4.
I'm taking a look at it right now.

**Comment by cbravobernal** [comment]
It seems that this issue is caused by this PR.
https://github.com/WordPress/gutenberg/pull/57520/

Should we revert it or try to set the context before it renders?

**Comment by fabiankaegy** [comment]
@c4rl0sbr4v0 awesome find :) If we can revert that without too much hasstle I think we should. Unless anyone has an alternative fix for the issue that we can get tested and reployed in the next few days so that we can get it into 6.5 during the beta cycle :)

**Comment by DAreRodz** [comment]
A potential fix would be to add the `.is-collapsed` class to the `<nav>` element with an inline script. Such script would have to compute the `mediaQuery`, locate the `nav.wp-block-navigation` element, and add the `.is-collapsed` class to it, so the visitor doesn't have to wait for the Interactivity API runtime to be downloaded and executed.

In this case, though, I feel returning to a CSS-only implementation would be more appropriate than using directives to add/remove the `.is-collapsed` class. 🤔

**Comment by cbravobernal** [comment]
>  I feel returning to a CSS-only implementation would be more appropriate than using directives to add/remove the .is-collapsed class. 🤔

I've been investigating and it seems that people want the breakpoint to be an editable field. So for that case the CSS should be added in the `render_callback` rather than a file.

**Comment by huubl** [comment]
How about implementing something similar as the  [x-cloak](https://alpinejs.dev/directives/cloak) directive in AlpineJS? This directive hides elements until the framework is fully loaded.

**Comment by cbirdsong** [comment]
Scripts can still fail to run for a lot of reasons even if they're inline. It would be best to handle as much of this as possible in CSS.
