### ISSUE TITLE
Uploaded Fonts Are Not Reflected in Editor Canvas Immediately

### ISSUE THREAD

**Issue by okmttdhr** [WordPress/gutenberg#58765]
### Description

After uploading and activating new fonts through the Font Library modal in Gutenberg, changes are not immediately reflected in the editor's canvas. Specifically, when a new font is applied to a block, the canvas continues to display the default font until the browser tab is refreshed. It might be related to https://github.com/WordPress/gutenberg/issues/58764.

**Expected Behavior**:
After a font is uploaded, activated, and applied to an element in Gutenberg, the canvas should immediately reflect this change without requiring a page refresh.

**Actual Behavior**:
The canvas does not update to show the newly applied font until after the browser tab where Gutenberg is open is refreshed.

### Step-by-step reproduction instructions

1. Download the "Super Enjoy" font from https://www.dafont.com/super-enjoy.font.
2. Upload and activate the font in the Font Library modal.
3. Apply the newly activated font to a heading block in the Gutenberg editor.
4. Observe that the canvas does not update to show the new font; it continues to display the text in the default font. 
5. Refresh the browser tab. 
6. After refreshing, observe that the canvas now correctly displays the heading in the "Super Enjoy" font.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/5287479/4b86e014-c019-479b-9988-8fb19449e6dc

### Environment info

Gutenberg > 17.6

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by arthur791004** [comment]
It seems that the [loadFontFaceInBrowser](https://github.com/WordPress/gutenberg/blob/c8ddc57ba240f13e21deaa95d63364a0c49147e0/packages/edit-site/src/components/global-styles/font-library-modal/utils/index.js#L89) function loads the font family with the incorrect font family name, especially for [formatFontFamily](https://github.com/WordPress/gutenberg/blob/c8ddc57ba240f13e21deaa95d63364a0c49147e0/packages/edit-site/src/components/global-styles/font-library-modal/utils/index.js#L102C3-L102C19).

Here is the font we added to the document right after the installation:

![image](https://github.com/WordPress/gutenberg/assets/13596067/b8a994fe-f57d-4f68-b535-ea27a67a3130)

Note that the screenshot is from the value of `Array.from($0.contentDocument.fonts)` ($0: the iframe element) in the console.

However, it should be `"Super Enjoy"` instead of `\"Super Enjoy\"`

![image](https://github.com/WordPress/gutenberg/assets/13596067/e4b49959-9cc4-48ff-a366-0eb41ff44f62)

For example, if you make changes to styles manually after the installation, it works as expected.

```diff
- --wp--preset--font-family--super-enjoy: "Super Enjoy";
+ --wp--preset--font-family--super-enjoy: \"Super Enjoy\";
```

**Comment by juanfra** [comment]
I tested this one and can replicate it. It happens when the name of the uploaded font has a space (two or more words).

https://github.com/WordPress/gutenberg/assets/252415/aa2960d0-8c67-4b1f-9d92-950e9d20f206

This is because the `loadFontFaceInBrowser` is using the [formatFontFamily](https://github.com/WordPress/gutenberg/blob/c8ddc57ba240f13e21deaa95d63364a0c49147e0/packages/edit-site/src/components/global-styles/font-library-modal/utils/index.js#L102C3-L102C19) method intending to format the name, and that's when the [extra quotes are added](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-site/src/components/global-styles/font-library-modal/utils/preview-styles.js#L44). 

Unless I'm missing something, removing the use of `formatFontFamily` [here](https://github.com/WordPress/gutenberg/blob/c8ddc57ba240f13e21deaa95d63364a0c49147e0/packages/edit-site/src/components/global-styles/font-library-modal/utils/index.js#L102C3-L102C19) will make it. I've done a quick test, and the fix seems to be working fine.

https://github.com/WordPress/gutenberg/assets/252415/bb23eba2-b63d-4294-a590-37d69045e3a4

**Comment by richtabor** [comment]
Is this related to how theme style variations that define font families don't have fonts loaded, unless you refresh?

**Comment by matiasbenedetto** [comment]
> Is this related to how theme style variations that define font families don't have fonts loaded, unless you refresh?

I don't think so, it seems like there is a problem with how the font names are rendered to CSS.

**Comment by pbking** [comment]
Strange that I was unable to reproduce this with the suggested (or any) font.

**Comment by okmttdhr** [comment]
It appears that some fonts are problematic and others are not, regardless of whether they were uploaded by hand or not. The following Google Font also caused the problem, for example. 

- Bungee Shade
- Akaya Kanadaka
- ADLaM Display
- Abril Fatface

**Comment by juanfra** [comment]
From what I checked, the problem with installing multi-word fonts from Google happens in Google Chrome, because it needs to receive the literal name when adding the font to the browser. It wasn't happening on Firefox, for example.

I've [updated the PR](https://github.com/WordPress/gutenberg/pull/58853#issuecomment-1936242866) to cover both cases, and also to add the font to the browser (document and iframe) so that the font styles are reflected everywhere (also in the sidebar, when you install a Google font and see the font in the fonts list).

**Comment by getdave** [comment]
I moved this to "In Progress" because @juanfra's PR seems to be addressing this issue.

**Comment by matiasbenedetto** [comment]
I reported this in trac to add the fixes into core repo https://core.trac.wordpress.org/ticket/60541#ticket
