### ISSUE TITLE
Category, tag, and taxonomy controls don't respect the correct capabilities

### ISSUE THREAD

**Issue by johnbillion** [WordPress/gutenberg#5879]
## Issue Overview
If a user has the `assign_terms` capability for a given taxonomy, but not the `manage_terms` capability for the taxonomy, they are unable to assign terms.

## Steps to Reproduce (for bugs)
1. Create a custom taxonomy that uses the following capabilities array, or filter the capabilities for Categories or Tags to do the same:

	```php
	'capabilities' => array(
		'assign_terms' => 'edit_posts',
		'delete_terms' => 'do_not_allow',
		'edit_terms'   => 'do_not_allow',
		'manage_terms' => 'do_not_allow',
	),

	```
2. Create a new post and note that the taxonomy is not shown in the editor, despite the user having the `edit_posts` capability and therefore being allowed to assign terms.

## Expected Behavior
The user should be able to assign terms in the taxonomy.

## Current Behavior
The user cannot assign terms in the taxonomy, not see the currently assigned terms.

## Possible Solution
Respect the user's capabilities for `assign_terms`.

Note that there is quite a lot of logic in the Categories and Tags meta boxes on WordPress' current editing screen, all of which needs to be replicated in Gutenberg in order to respect the underlying capabilities API.

See:
* `post_tags_meta_box()`
* `post_categories_meta_box()`

## Related Issues and/or PRs
* #4787
* #2545

**Comment by danielbachhuber** [comment]
I'm going to approach this issue in this order:

1. Produce a table documenting (from the UI) what term management actions each role (contributor, author, editor) can perform (e.g. create a tag, assign a tag to a post, edit the tag description). This will serve as our reference point for 2 and 3.
2. Ensure REST API capability checks follow aforementioned table. I'm pretty sure they don't.
3. Ensure Gutenberg's displayed UI follows aforementioned table.

**Comment by danielbachhuber** [comment]
I did some research on this today. Here's my [table of UI-focused permission review](https://gist.github.com/danielbachhuber/da5d66da0b6672fd893b83b44994086d).

The key difference between categories and tags: contributors and authors can create tags, but they can't create categories. This distinction applies more broadly to non-hierarchical vs. hierarchical taxonomies.

_Fortunately_, the only low-level permissions check is in `wp_insert_post()`. More specifically:

```php
foreach ( $postarr['tax_input'] as $taxonomy => $tags ) {
	$taxonomy_obj = get_taxonomy( $taxonomy );
	// array = hierarchical, string = non-hierarchical.
	if ( is_array( $tags ) ) {
		$tags = array_filter( $tags );
	}
	if ( current_user_can( $taxonomy_obj->cap->assign_terms ) ) {
		wp_set_post_terms( $post_ID, $tags, $taxonomy );
	}
}
```

After this logic, `wp_set_post_terms()` calls `wp_set_object_terms()` and neither has permissions checks. Because of how `wp_set_object_terms()` behaves, strings passed for a non-hierarchical taxonomy will be magically transformed into terms. `wp_set_object_terms()` always expects an array of integers (representing valid terms) for hierarchical taxonomies.

I say "fortunately" because core's existing implementation also means we don't have to enter the rabbit hole of developer-defined custom taxonomy UI. `edit_post()` blindly accepts and processes data included in `tax_input`, regardless of whether a developer implemented some bespoke UI for the taxonomy.

Given this information, we can assume:

1. A user can set terms on a post if they have `assign_terms` for the taxonomy and can edit the post. This also means they can access _all_ terms (including empty, non-public ones).
2. A user can create new terms if they have `assign_terms` for a non-hierarchical taxonomy, or `edit_terms` for a hierarchical taxonomy.

However, now we run into #6361 because capabilities are evaluated at runtime.

**Comment by marybaum** [comment]
FWIW, I'm not seeing the categories and tags panel on [marybaum.com,](http://marybaum.com) my photo portfolio, logged in as admin, on Bluehost shared hosting. 
<img width="296" alt="screenshot 2018-05-24 10 50 08" src="https://user-images.githubusercontent.com/3679459/40496843-573c504c-5f40-11e8-8544-5ef5345b21f8.png">

**Comment by marybaum** [comment]
Sure!
