### ISSUE TITLE
WP 6.5 beta 1 - Can't edit front page on 1st try

### ISSUE THREAD

**Issue by draganescu** [WordPress/gutenberg#59026]
### Description

In websites that had a page set as homepage in WP 6.4 after upgrading to 6.5 beta 1 the content is initially locked in the editor. However after visiting the Frontpage template once, going back to the page makes it editable in the site editor again.

### Step-by-step reproduction instructions

1. Using WP 6.4:
2. Setup a front page template
3. Setup a page named "Home" with content
4. Make the Home page be the home in Settings>Reading
5. Check that the page named home is Front page and that it uses the Front page template
6. Upgrade to 6.5 beta 1
7. Go to appearace > editor
8. Notice the content is not editable
9. Click edit template
10. Go back via the site hub button
11. Go back to top level using the back button
12. Notice the content is editable

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/107534/1b87ed8f-4b0f-458d-972e-1e1ac83c10c9

### Environment info

WP 6.5 beta 1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by annezazu** [comment]
I can replicate this in 6.5 beta 2.

**Comment by getdave** [comment]
#### WP 6.4

On going to the Editor I saw that I was on the "Home" page and that the content (only) was editable:

<img width="2376" alt="Screen Shot 2024-02-28 at 15 33 08" src="https://github.com/WordPress/gutenberg/assets/444434/a54df74d-0b40-4704-ac66-911ce67da4c6">


#### WP 6.5 Beta 3

On going to the Editor I saw that I was on the "Home" page but that the content was not editable and clicking required "Edit template" to change contents:

<img width="2104" alt="Screen Shot 2024-02-28 at 15 35 55" src="https://github.com/WordPress/gutenberg/assets/444434/f52b7764-320b-4f64-badc-1739c6d0772c">

**Comment by getdave** [comment]
Testing it seems that if you do not create the `Frontpage` template then everything works.

However if Frontpage exists then it breaks.

**Comment by getdave** [comment]
From the description I'm am not completely clear on this bug.

@draganescu Can I confirm that in your video the heading `Welcome! I hope my blog finds you well and curious?` is the "Page Contents" coming from you "Home" Page?

Is this what you are saying is locked when you initially visit and then subsequrntly editable once you revisit the Template?

**Comment by youknowriad** [comment]
I haven't been able to reproduce so far personally. Do you need to create your home page ... in 6.4 or can you just create it directly in 6.5 and reload the page?

**Comment by getdave** [comment]
I think the bit about using WP 6.4 was to afford a comparison between what happens in 6.5.

I tried testing this yesterday. If I've understood @draganescu correctly then the bug seems to have been fixed.

In the screenshot below, I'm using a front page template which contains a `core/post-content` block (sorry it looks ugly!). I have a page called "Home" which is set to front page in the Reading settings under WP Admin.

When I load the Site Editor I _can_ edit the "Page Content" (i.e. within the `core/post-content`). Obviously if I try to edit the rest of the content then I have to click "Edit Template" because it's a template.

<img width="1508" alt="Screen Shot 2024-02-29 at 10 48 34" src="https://github.com/WordPress/gutenberg/assets/444434/bffeecce-4d39-418b-b221-7b86319589a4">

The whole thing about making it easier to "edit my homepage" is another story but not something we can fix for 6.6.

@annezazu as the only person who managed to replicate this, would it be possible for you to confirm whether it's still in evidence on Beta 3?

**Comment by annezazu** [comment]
Whew, this is a tricky one. I can replicate what you can and agree that the initial bug is technically fixed but the experience is one that's more of a design question: do we want what's shown by default to show the template or page editing view? Right now, it shows the page editing view since it's a page using the front page template. I'm not sure if that's right! Here's me talking it through/showing the current:

https://github.com/WordPress/gutenberg/assets/26996883/e58c37fe-f90c-4b6b-813d-eb8c0aa780c5

This experience stands in contrast to what's in place for 6.4.3 where when you have the same setup you aren't shown the front page template and instead are just shown the "home" page when you open the Site Editor. This changes that flow and IMO more accurately represents it. I'm curious to hear from @WordPress/gutenberg-design on this. In many ways, I can see how this current approach helps preserve the experience of a page set as a homepage but curious to hear from others.

**Comment by jameskoster** [comment]
To replicate the problem; set a static homepage and create a Front page template that does not include any content blocks (IE Title, Featured Image, Content). Then open the site editor and click the frame. You're taken to an editor instance where you cannot edit any blocks.

This is tricky because Front Page will resolve to display the homepage regardless of whether WP is configured to show latest posts or a static homepage. In many cases Front Page _will not_ include any content blocks, indeed _all_ the suggested patterns in TT4 are set up this way. In such cases the problem outlined above arises.

A possible workaround: If a static homepage is set, and Front Page includes content blocks (outside of Query Loops); send the user to the page edit experience. Otherwise, send them to the template edit experience. This should probably apply when clicking the Edit button from the homepage details panel too.

---

It's separate, but I think this is an issue in the TT4 patterns (or any theme that includes a Front Page template/patterns). Given to the resolution tree of the wp template hierarchy, ideally any Front Page template should be capable of serving as both types of homepage.

**Comment by getdave** [comment]
Thanks for the additional detail here. Very useful 👍 

What I'm not clear on is whether this is a bug introduced in 6.5 cycle, or a new behaviour that we are suggesting needs to be added.

**Comment by jasmussen** [comment]
Thanks for the clear description, thank you Anne for the added context of the video. From what I can tell, the issue at hand here is:

* If you go into the site editor, click the homepage without first choosing the Page or Template categories, the fullscreen editor defaults to _page editing mode_ for the static front page.
* In order for the fullscreen editor to default to opening in template editing mode, you have to first click Templates > Front Page.

Is that a correct read? If yes, then it isn't clear to me this is a bug, so much as a highlighting, yet again, of the importance for us to make clearer the template/content editing status of these. This is something @richtabor and I recently discussed as well, that there may be small things we can do, and these would also make it that much clearer. Even just keeping an eye on the Document Title interface will show you whether you're in one mode or the other — that's not clear enough delineation of course, but it does show that so far the code is working as it was written to do.

Since the Front Page template is assigned to a "static homepage", I would suggest not introducing any edgecases to address this but rather continue to focus on making progress on the template/content editing flows.

**Comment by getdave** [comment]
Related https://github.com/WordPress/gutenberg/issues/56244.

@draganescu Are you able to share your opinion on the above. Specifically whether there is a change in behaviour from 6.4 -> 6.5 which constitutes a bug.

This is as opposed to what you reported potentially being an existing suboptimal pattern that should be addressed in a future release.

Much appreciated.

**Comment by youknowriad** [comment]
I much agree with @jasmussen while it's not ideal, it's working as expected. I'm going to remove this one from 6.5 board for now.

**Comment by jameskoster** [comment]
If that's the direction we elect to follow then we should consider updating the patterns associated with the Front Page template in TT4. At the moment they're all focussed on displaying latest posts and do not work for static home pages. That's likely a large reason why this issue exists in the first place. 

cc @WordPress/theme-team

**Comment by draganescu** [comment]
From my perspective the issue was not about the UX but simply that I was unable to edit front page _page_ content on the initial landing in the site editor. Within beta 3 the problem is gone so we can as well close this issue.
