### ISSUE TITLE
Data Views: Bulk edit is hard to see as an option after selecting items

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#59043]
After selecting a few items, the bulk edit button, while it shifts to the items you select, it's very hard to see:

![Screenshot 2024-02-14 at 3 41 36 PM](https://github.com/WordPress/gutenberg/assets/26996883/315ba649-b680-4c90-88c7-b36e55ae04bb)

I'm not sure if we should make it change to a primary button but it seems hard to discover currently. I could see folks selecting items then not knowing what to do next @WordPress/gutenberg-design

**Comment by t-hamano** [comment]
At least, how about always making the label "Bulk actions" whether or not the item is selected, like in the classic editor?

Data Views:

![image](https://github.com/WordPress/gutenberg/assets/54422211/3faf5af1-4fd7-4df4-9565-5311579c7e23)

Classic Editor:

![image](https://github.com/WordPress/gutenberg/assets/54422211/06595b8e-dc54-4de1-a9e1-30e9469cb1d2)

Or we may want to move the button position itself. Since Bulk Edit is an action performed on checked items, I feel it is better to place it as close to the checkbox as possible.

![image](https://github.com/WordPress/gutenberg/assets/54422211/28f0620e-ccff-4c1f-9636-3da89dc2fc57)

**Comment by jameskoster** [comment]
> I feel it is better to place it as close to the checkbox as possible

I agree with the sentiment, but I don't like how the filters + bulk actions blend together. There's an argument to place search + filters closer in the DOM too. The composition is a bit tricky because the filter row can grow to be quite large so it needs a dedicated row. 

For this issue specifically, the intention was always to try a 'floating bulk actions toolbar' (https://github.com/WordPress/gutenberg/issues/55098), additional to the a11y-friendly menu that we have currently. This larger UI (which would ideally appear with some animation like a Snackbar to draw attention) should hopefully make the bulk actions more obvious. What do y'all think?

**Comment by t-hamano** [comment]
> The composition is a bit tricky because the filter row can grow to be quite large so it needs a dedicated row.

I certainly think so. Depending on other languages, the filter row will be longer.

The translation is not yet complete, but below is a screenshot comparing the length of the filter row in English and Japanese:

![filter-row](https://github.com/WordPress/gutenberg/assets/54422211/84ecccb4-a081-4474-9216-a7903c703fa5)

> For this issue specifically, the intention was always to try a 'floating bulk actions toolbar' (https://github.com/WordPress/gutenberg/issues/55098), additional to the a11y-friendly menu that we have currently. This larger UI (which would ideally appear with some animation like a Snackbar to draw attention) should hopefully make the bulk actions more obvious. What do y'all think?

I think this is a great idea! I also learned that an implementation is already being explored in #56476.

**Comment by jameskoster** [comment]
> I also learned that an implementation is already being explored in https://github.com/WordPress/gutenberg/pull/56476.

I think that PR also included the first attempt at general bulk action implementation. I wonder if it could be re-purposed to concentrate on the floating toolbar @jorgefilipecosta ?

**Comment by jorgefilipecosta** [comment]
Hi @jameskoster, are there still plans to explore a floating toolbar?

**Comment by jameskoster** [comment]
@jorgefilipecosta yes please 🙏 I think that's a good avenue to explore for this issue. Ideally the action bar would appear with some subtle animation to draw attention. We had this mockup before which can hopefully prove a good starting point:

<img width="1155" alt="Actions bar" src="https://github.com/WordPress/gutenberg/assets/846565/aa034fc2-5880-4373-98b4-254142b1243f">

**Comment by annezazu** [comment]
Closing this out as https://github.com/WordPress/gutenberg/pull/59714 landed!
