### ISSUE TITLE
DropdownMenu V2: Chevron icon position and orientation are incorrect when submenu is flipped

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#59077]
### Description

My understanding is that when a DropdownMenu V2 component has a submenu, a chevron icon is displayed to the right of the text. This icon should expect the submenu to expand to the right, as the chevron icon indicates.

![image](https://github.com/WordPress/gutenberg/assets/54422211/04468692-f3ea-4add-889e-efa2f248cb8a)

However, if this component is located at the right edge of the screen, the chevron icon will still point to the right, even though the submenu will appear on the left.

![image](https://github.com/WordPress/gutenberg/assets/54422211/dabbf3f9-a846-4977-bb81-07d89a41f8d9)

I may not call this a bug, but I would expect that when the submenu expands to the left, the chevron icon points to the left and appears to the left of the text.

### Step-by-step reproduction instructions

- Access the all template list page in the site editor.
- Click the "View options" icon at the top right of the data view to expand the submenu.

### Environment info

- WordPress Version: 6.5 Beta 1
- Gutenberg Version: 17.7 (Can be reproduced even if the plugin is disabled)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mirka** [comment]
Do you know any reference designs that do this? For example, nested submenus on macOS do not do chevron flipping according to popover placement (I'm sure they do it for RTL languages though).

From a UX standpoint, I'm afraid it might be more confusing because popover placement can be quite dynamic. If you imagine a somewhat narrow viewport, it would only take two nested levels for the popover placement to flip back. Then you'd have two different chevron placements in a single menu tree for something that is functionally the same. Or you could run into cases where a chevron for the next level submenu is pointing right back at the parent's chevron.

<img width="406" alt="A nested submenu opening to the right, then wrapping around to open the next level on the left" src="https://github.com/WordPress/gutenberg/assets/555336/f72a5fe2-2de6-4063-ab82-ff545f1285ea">

**Comment by t-hamano** [comment]
Thank you for your reply.

I thought about it calmly again, and the current behavior should be correct 😅 I've tested several apps that have a chevron icon inside a dropdown menu, but none of them seem to reverse the orientation or position of the chevron icon.

Windows:

![image](https://github.com/WordPress/gutenberg/assets/54422211/986e3558-91aa-4b88-a760-d3eb48a3482c)

Google spreadsheet:

![image](https://github.com/WordPress/gutenberg/assets/54422211/27b719d9-16c0-4da2-aa1c-b6561bbf89ec)

Notion:

![image](https://github.com/WordPress/gutenberg/assets/54422211/fd088730-42e8-4773-984a-ff2dbbcc6a95)

Chrome:

![image](https://github.com/WordPress/gutenberg/assets/54422211/3ef4cbba-33f4-4c35-ae34-5beec1354278)

Therefore, I think this issue can be closed.

**Comment by t-hamano** [comment]
I would like to close this issue as I have determined that the current behavior is correct. Sorry for confusing you 🙏
