### ISSUE TITLE
Navigation inline CSS gets injected despite `wp_dequeue_style( 'wp-block-navigation' );`

### ISSUE THREAD

**Issue by nextgenthemes** [WordPress/gutenberg#59142]
### Description

Using WP 6.4.3 without GB active does not have this issue.

I use
```php
add_action( 'wp_enqueue_scripts', __NAMESPACE__ . '\action_wp_enqueue_scripts', 15 );
function action_wp_enqueue_scripts(): void {

	wp_dequeue_style( 'wp-block-navigation' );
}
```
If I remember this right, dequeueing the styles should also remove the inline styles. I think it does so for different blocks, but I am not sure.

Some of the more recent versions of GB add this style that fucks up my styles. It should not be printed when the styles are dequeued.

How do I remove it? Is there a workaround?

```css
.wp-block-navigation a:where(:not(.wp-element-button)) {
  color: inherit;
}
```

### Step-by-step reproduction instructions

1. use wp_dequeue_style( 'wp-block-navigation' );
2. Activate GB plugin.
3. Look the style polluting the CSS anyway.

### Environment info

WP 6.4.3
GB 17.7.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by nextgenthemes** [comment]
Yes, still relevant, the style may come from core/button(s) or some general GB base styles.

**Comment by nextgenthemes** [comment]
....

**Comment by t-hamano** [comment]
Sorry for the late reply. The style is defined [here](https://github.com/WordPress/gutenberg/blob/a6908f4b3fc4bbf06916a3f36124660c856a8737/packages/block-library/src/navigation/block.json#L140-L148) and cannot be deleted with `wp_dequeue_style( 'wp-block-navigation' );` because it is output as part of the global style inline CSS.

However, upon closer inspection, this style itself appears to be unnecessary. I plan to submit a PR to remove this style.
