### ISSUE TITLE
@wordpress/env: Getting error on version 9.3.0 when run start command

### ISSUE THREAD

**Issue by ravinderk** [WordPress/gutenberg#59232]
### Description

I am getting the following error when running `wp-env start`:

<img width="1702" alt="image" src="https://github.com/WordPress/gutenberg/assets/1784821/07f4e8ef-b07f-411f-8df1-9a98761ddbd1">

**Comment by dmaziar** [comment]
The same problem on lower version (8.11.0). Any workaround for this problem?

**Comment by adimoldovan** [comment]
Probably caused by https://github.com/MariaDB/mariadb-docker/issues/560?

**Comment by ramonschriks** [comment]
> The same problem on lower version (8.11.0). Any workaround for this problem?

If you want quick workaround to make it work again for now, you could edit the file below:

`node_modules/@wordpress/env/lib/build-docker-compose-config.js`

to update the `mysql` and `tests-mysql` image from `mariadb` to `mariadb:11.2.2-jammy`
(or run: `sed -i -e "s/image: 'mariadb'/image: 'mariadb:11.2.2-jammy'/g" node_modules/@wordpress/env/lib/build-docker-compose-config.js`)


Run `wp-env stop` and `start` again will make it work again.

**Comment by sweber83** [comment]
I think the root of the issue here is that `@wordpress/env` implicitly uses the `mariadb:latest` tag, which is a development release.
So `@wordpress/env` should instead use a stable release, e.g. `mariadb:10.2`.

https://mariadb.com/kb/en/mariadb-server-release-dates/
https://hub.docker.com/_/mariadb

Edit:
I meant 11.2 not 10.2

**Comment by swissspidy** [comment]
`:latest` is the latest stable release, which at the moment is 11.3.2 (released yesterday). 11.4.x is the development version at the moment.

Choosing something like v10.2 doesn't make sense because that version is 7 years old and hasn't been supported for over 2 years. If anything, choose `mariadb:lts` to get the LTS version.

**Comment by sweber83** [comment]
@swissspidy 
11.3.x is also a dev release, just like 11.4.x.
See https://mariadb.com/kb/en/mariadb-server-release-dates/

**Comment by swissspidy** [comment]
IDK, their download page says it's the latest GA release, and 11.4 is marked as development.

![Screenshot 2024-02-21 at 14 25 45](https://github.com/WordPress/gutenberg/assets/841956/f572281f-60f1-4c77-a526-ce7fee34358b)

**Comment by sweber83** [comment]
The fact that `:latest` points to 11.3 also indicates it's a stable release 🤷‍♂️

**Comment by ravinderk** [comment]
@t-hamano When can we expect a release with this?

**Comment by t-hamano** [comment]
I'm not sure about the exact release date, but it looks like the RC version is already [ready](https://github.com/WordPress/gutenberg/releases/tag/v17.8.0-rc.1), so I believe it will be released soon.
