### ISSUE TITLE
List block: Cmd+A to select all items then paste fails, pasting nothing

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#59381]
Pulling this specific issue out of https://github.com/WordPress/gutenberg/issues/52743 as I can replicate with 6.5 beta 2. @ellatrix can you track this down?

**Replication steps:**

1. Create four list items.
2. Use Cmd + a to select them and copy.
3. Try to paste. Notice nothing pastes.

**Screen recording:**

https://github.com/WordPress/gutenberg/assets/26996883/f19e105f-92b7-4dca-a5f3-289aebedafd7

**Comment by t-hamano** [comment]
I was also able to reproduce this problem. The underlying problem seems to be caused by the difference between whether a block or text is selected.

- ✅ Select _text_ in the list with the cursor and copy and paste: In the received HTML, the `ul` element is present and pasted correctly
- ❌ Select _block_ via `Cmd+A` or the list view and copy and paste: In the received HTML, the `ul` element is not present and nothing is pasted.

https://github.com/WordPress/gutenberg/assets/54422211/dceac30e-26c3-432a-99ed-56f1c45d0673

**Comment by ellatrix** [comment]
Looking into it
