### ISSUE TITLE
"&hellip" visible in the "Publish" button

### ISSUE THREAD

**Issue by zacharyhickson** [WordPress/gutenberg#5939]
## Issue Overview
"`&hellip;`" text is being printed in the Publish button. 

## Steps to Reproduce (for bugs)
1. Brand new installation of WordPress on a local MAMP Pro setup.
2. WordPress Version: 4.9.4 (English Australia localisation)
3. Gutenberg Version: 2.5.0
4. No other active plugins

OS: macOS High Sierra 10.13.3
Browser: Google Chrome - Version 65.0.3325.181 (Official Build) (64-bit)
Tested in both Normal and Incognito modes.

## Expected Behavior
The "`&hellip;`" should not be outputted as text, but converted to HTML.

## Screenshots / Video
<img width="126" alt="screen shot 2018-04-03 at 12 08 19 pm" src="https://user-images.githubusercontent.com/811439/38226073-16e34c62-373b-11e8-8af0-6a5de783b410.png">
<img width="290" alt="screen shot 2018-04-03 at 12 34 46 pm" src="https://user-images.githubusercontent.com/811439/38226145-6d5e4858-373b-11e8-9658-279ae958da62.png">

**Comment by SuperGeniusZeb** [comment]
Possibly related since they both involve HTML entity parsing: #5717

**Comment by felipeelia** [comment]
Actually this seems to be a problem with the current translation of the string, as seen in [GlotPress](https://translate.wordpress.org/projects/wp-plugins/gutenberg/dev/en-au/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=5746810&sort%5Bby%5D=translation_date_added&sort%5Bhow%5D=asc).
GlotDict displays this warning:
`Warning: The translation contains a final ... that should be translated as &hellip;`
But in this case I think it should be translated just as is.

**Comment by danielbachhuber** [comment]
@felipeelia Sorry, I'm not sure I follow. Do you have a suggested resolution for this issue?

**Comment by felipeelia** [comment]
I think @zacharyhickson can already confirm if it's all right now, @danielbachhuber.
I've sent the correct string to GlotPress and @ntwb has already accepted it (thanks btw).

The problem seems to be in GlotPress or GlotDict, suggesting to translate strings containg `...` with `&hellip;`, when it's not always the case.

**Comment by ntwb** [comment]
I suspect this is due to the generation of strings for Gutenberg in using `json_encode()` in [`/lib/parser.php`](https://github.com/WordPress/gutenberg/blob/master/lib/parser.php), see [WP#32875:Comment#6](https://core.trac.wordpress.org/ticket/32875#comment:6) for further details on this.

**Comment by jorgefilipecosta** [comment]
The merge of https://github.com/WordPress/gutenberg/pull/6114 should have resolved the issue in the publish button. We should have used 'Publish…' ( … is a special char) instead of  'Publish...' (... three points) like we do in the other places.
As the main issue is solved I will close this issue. Thank you for the debugging I think It was useful and we may have some other problems where characters may be wrongly "translated".
Of course, if the issue persists in your tests feel free to reopen.
