### ISSUE TITLE
Pinterest URLs not embedding when not .com (.es, .it...)

### ISSUE THREAD

**Issue by alvarotrigo** [WordPress/gutenberg#59400]
## Description

Pinterest URLs that don't come from the .com domain won't be embedded.
Pinterest uses a different domain for different countries and people in those countries might find it difficult to use this block.

## Step-by-step reproduction instructions

For example, these URLs won't get embedded:
https://www.pinterest.es/pin/320670435980314659/
https://www.pinterest.it/pin/308004062030905959/

But changing the `.es` and `.it` for `.com`will make it work:
https://www.pinterest.com/pin/320670435980314659/
https://www.pinterest.com/pin/308004062030905959/

## Expected behaviour

Any URL coming from the existing interest domains in each country should work.
Having a list of them should be enough to deal with this.

## Actual behaviour

URLs won't embed if not coming from the .com domain.

## Screenshots or screen recording (optional)

<img width="762" alt="image" src="https://github.com/WordPress/gutenberg/assets/1706326/28345b5e-288a-40fa-9379-e2feb1d4ac94">

## WordPress information
- WordPress version:  6.4.3
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated?  Yes
- Are you using a default theme. Yes

**Comment by interdevel** [comment]
I found that when you try to embed the pin, the URL http://localhost:8888/index.php?rest_route=%2Foembed%2F1.0%2Fproxy&url=https%3A%2F%2Fwww.pinterest.es%2Fpin%2F659566307946923269%2F&_locale=user (using pinterest.es in this case) returns 404.
However the actual pin URL (https://www.pinterest.es/pin/659566307946923269/) returns 200.

**Comment by Mamaduka** [comment]
It looks like the Pinterest embed provider supports those URLs, but the [regex](https://github.com/WordPress/wordpress-develop/blob/2930212ff6bf6619d026f525ceab2719c5229597/src/wp-includes/class-wp-oembed.php#L108) used in Core limits URLs to `.com(.au|.mx)`.

@alvarotrigo, can you [create a core ticket](https://core.trac.wordpress.org/newticket) since this needs to be handled in a different repository?

Example embed - https://www.pinterest.com/oembed.json?url=https://www.pinterest.es/pin/320670435980314659/.

**Comment by Mamaduka** [comment]
Closing in favor of https://core.trac.wordpress.org/ticket/61558.
