### ISSUE TITLE
Global list block styles bleed into the Group block placeholder

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#59414]
### Description

If you add a background color to the list block in the Global styles interface, it affects the color of the group block placeholder, where you choose between group / row / stack/ grid.

**Untested** (I did not have time yet ), but this might be fixed by https://github.com/WordPress/gutenberg/pull/56469

### Step-by-step reproduction instructions

Activate a block theme.
Open the Site Editor, Styles sidebar, and select Blocks > List, and add a background color.
Save.
In the Site Editor or block editor, add a new group. 
See that part of the background has the same color that you chose for the list.

### Screenshots, screen recording, code snippet

<img width="901" alt="Group block placeholder with partial background color" src="https://github.com/WordPress/gutenberg/assets/7422055/4e00aca4-f7c3-4c7d-ac0a-657cc53d29a0">

### Environment info

Reproduced in WordPress 6.4.3, 6.5 alpha, with and without Gutenberg trunk.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by tellthemachines** [comment]
Thanks for opening this! I just came here to report the same 😄 

<img width="838" alt="Screenshot 2024-03-18 at 11 29 08 AM" src="https://github.com/WordPress/gutenberg/assets/8096000/093a8be2-37ef-4ff9-bf6c-a022afcdea98">

The issue would indeed be fixed by https://github.com/WordPress/gutenberg/pull/56469 because the problem is lack of scoping of the List block styles:

<img width="501" alt="Screenshot 2024-03-18 at 3 20 32 PM" src="https://github.com/WordPress/gutenberg/assets/8096000/5b760505-da19-41be-9d49-029ec0ec7ea3">

**Comment by ellatrix** [comment]
This would be fixed by #33494.

**Comment by carolinan** [comment]
I am not able to reproduce this issue any more. Is the linked PR correct?
