### ISSUE TITLE
Pattern: unable to set name of pattern when creating a pattern from wp-admin/edit.php?post_type=wp_block

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#59511]
When going through the pattern creation flow in wp-admin/edit.php?post_type=wp_block (not what's available in the site editor), there is no ability to set a title for the pattern. This is using WordPress 6.5 beta 3. If you use 6.4.3, a title field is available. Below is a video that walks (and talks) you through it:

https://github.com/WordPress/gutenberg/assets/26996883/ed6e1de7-0d2c-4439-94a8-945472e7cd8b

This is a regression and something that needs to be fixed for 6.5 so automatically adding to the to do column. Without a name, it becomes much harder to find the pattern you created!

**Comment by t-hamano** [comment]
@annezazu This issue should be fixed in WP6.5, right? It seems that it was added to the WP6.6 board, so I would like to move it to the WP6.5 board.

**Comment by annezazu** [comment]
Ah! Good catch. That was completely accidental (and likely due to me rushing to get this reported) :D

**Comment by youknowriad** [comment]
Just noting that in the site editor (block themes), the title of the patterns is not available either. So this issue is the result of the unification of the editors. 

For me we should either:

 - have the title in both
 - do not have the title at all
 - Maybe have the title in the sidebar or something.

This might require some design input. cc @jasmussen

**Comment by youknowriad** [comment]
There's also one stop gap solution potentially. 

For classic theme, when opening the pattern for creating, we show a specific "sync status" modal. Ideally this modal should be removed at some point but for now, it can be used to set the title as well, similarly to how we set the sync status. 

For both of these in the site editor, the modal is shown before going to the editor when creating a pattern.

**Comment by jasmussen** [comment]
Good one. It seems like the main place to set the pattern title is this one, from the site editor:

![Screenshot 2024-03-04 at 09 54 31](https://github.com/WordPress/gutenberg/assets/1204802/095df70c-9b06-4edd-a012-5c60243146d6)

There's also, in the site editor, the ellipsis option to rename:

![Screenshot 2024-03-04 at 09 55 39](https://github.com/WordPress/gutenberg/assets/1204802/7469d6f0-7b69-4cc4-ac83-2d04df0c44c4)

That does seem to be the main motivation for removing the title field in the editor. Though I'd agree with Riad, there needs to be a stop gap solution for other pathways. Is that primarily classic themes? And to Riad's suggestion, do we show that sync modal only for that flow? If yes, then that feels the obvious quick fix to this, since that modal will then conceptually be similar to the "New pattern" modal.

That said, it does seem like an omission to not have an ability to edit the title of the pattern in the editor, so regardless it could be good to have something there. Whether it's an interface that's unified with what we're thinking about for titleless pages or not, something in the inspector yes perhaps. It can even be the same ellipsis menu as shown above, in an ellipsis here:

![Screenshot 2024-03-04 at 10 07 37](https://github.com/WordPress/gutenberg/assets/1204802/940732d0-a4c5-447b-aadf-0db8ad319261)

After all, that inspector panel should eventually be able to absorb this details page:

![Screenshot 2024-03-04 at 10 08 13](https://github.com/WordPress/gutenberg/assets/1204802/f30c2ab9-60ac-4c87-af29-d6aff02c4563)

CC: @jameskoster for awareness.

Speaking of stop-gaps, though, another option could just be to resurface the title field for patterns, always. Visually we could maybe style it a little bit. I'd be happy to collab in a PR with you @youknowriad, to address this? Let me know. Regardless, we need to fix this layout shift:

![layout shift](https://github.com/WordPress/gutenberg/assets/1204802/0ea24b92-0bc0-4e53-816d-7a4192035255)

(It's probably margin present on the appender that disappears when replaced with the paragraph.)

**Comment by youknowriad** [comment]
cc @ntsekouras would you be able to help with this one?

**Comment by liviopv** [comment]
I noticed this as well when working with a customer today. They were used to manage patterns from /wp-admin/edit.php?post_type=wp_block (added https://github.com/WordPress/gutenberg/issues/59545 based on the feedback) and they were creating patterns from there, but then they had to go back to the Site Editor to rename each pattern.

> Just noting that in the site editor (block themes), the title of the patterns is not available either.

@youknowriad yes, but editing a Pattern from the Site Editor surfaces the Command Palette with the Pattern title and clicking on it will allow users to rename it:

![CleanShot 2024-03-04 at 10 44 50@2x](https://github.com/WordPress/gutenberg/assets/14153300/7e4d7440-5c06-4b8b-8aa0-e1afed9b0170)

But when starting from wp-admin, the Command Palette doesn't show up:

![CleanShot 2024-03-04 at 10 45 43@2x](https://github.com/WordPress/gutenberg/assets/14153300/5f7c0854-83e0-489e-b0f1-ab88ba81d5d3)

**Comment by youknowriad** [comment]
@liviopv Good point, currently the "Document Bar" is not shown in the post editor and it's one other thing we need to unify with the site editor. The command palette is loaded though and can be triggered using the shortcut.

**Comment by ntsekouras** [comment]
After reading the discussion, IMO we have to:
1. Add the `title` field in the modal of wp-admin create flow, similar to the modal in site editor.
2. Find a solution of renaming in a consistent way in both editors

Regarding the renaming I observed one more difference in the inspector panel, when we have the `pattern` tab selected. In post editor we show a `summary` and in site editor we just show the title.

@jasmussen should we show the summary in site editor too? I think we should probably show it in both editors and also add the pattern's name above with either an elipsis menu next to it with the rename action, or follow the same pattern with the `summary` and have something like `Title: ${title name}` which is a button that triggers the modal to appear.

Alternatively we could unify the `Document bar`.

**Comment by jasmussen** [comment]
> should we show the summary in site editor too? I think we should probably show it in both editors and also add the pattern's name above with either an elipsis menu next to it with the rename action, or follow the same pattern with the summary and have something like Title: ${title name} which is a button that triggers the modal to appear.

I'd tend toward unification, and I'd be tempted to just visually polish these up in the canvas, have the features remain, and _then_ look to potentially refactoring them into more permanent locations, such as a new and improved document inspector that would also be available in list views.

**Comment by ntsekouras** [comment]
@jasmussen sorry but it's not clear to me what is the suggestion for where to place the `rename` action and whether to add the `summary` panel in site editor too. Could you clarify?

**Comment by jasmussen** [comment]
This rename dropdown, currently available in the site editor for each individual pattern:

![Screenshot 2024-03-04 at 12 29 20](https://github.com/WordPress/gutenberg/assets/1204802/bbce70a2-12eb-4283-880d-bd0f584762dc)

This could be available here:

![Screenshot 2024-03-04 at 12 29 34](https://github.com/WordPress/gutenberg/assets/1204802/09c489ca-d2dc-41b8-8312-66904e2a2813)

just like it is for navigation:

![Screenshot 2024-03-04 at 12 30 49](https://github.com/WordPress/gutenberg/assets/1204802/3645a853-1f36-4a27-8598-bad23cbf826a)

However I could also see those detail drilldown pages being moved in the future, and be absorbed entirely into the fullscreen editor page inspector. So I could also see it being here:

![Screenshot 2024-03-04 at 12 29 41](https://github.com/WordPress/gutenberg/assets/1204802/cea2e70c-6437-45d5-a418-fccc25dc5147)

I.e. in that block description field it would be `[sync symbol] My lovely pattern           [ellipsis menu]`.

Let me know if that makes sense, I'm juggling a couple of other things otherwise I'd put together a better (than ASCII) mockup.

**Comment by youknowriad** [comment]
Let's try to split the work needed to two things:

 1- Mandatory things for 6.5: Solution could be to show the "title" within the pattern editor.
 2- Enhancements post 6.5 (adding UI to details panel, unify document actions, move renaming to the inspector...)

**Comment by jasmussen** [comment]
I'm happy to collaborate on a branch that simply unhides the title field from the canvas again. I believe I can CSS that up to work well.

**Comment by ntsekouras** [comment]
I'll open a PR soon and let's continue there to test things out.

**Comment by jp-imagines** [comment]
Just noting a temporary workaround for anyone using a classic (non-block) theme: the "code editor" view _does_ still show the title field:

![add title field](https://github.com/WordPress/gutenberg/assets/5630717/11dcd886-c92c-49c5-b9fd-6f4299c64d36)

**Comment by youknowriad** [comment]
Closing this one for now. Next step for 6.6 is to actually use the site editor page for patters for classic themes.
