### ISSUE TITLE
Link Control: allow double clicking to edit text of link

### ISSUE THREAD

**Issue by bacoords** [WordPress/gutenberg#59525]
### Description

When you have a link inside text (paragraph, list item, etc) placing the cursor inside the link shifts focus to the popup, so your cursor leaves the paragraph text. This is new behavior in version 17.8.0 

**Proposed behavior** : The way it has worked in the past: you click inside of a link and your cursor stays, allowing you to type inside the link without having to press `esc`

### Step-by-step reproduction instructions

1. Activate Gutenberg 17.8.0
2. Hyperlink some text inside of a paragraph block. 
3. Place your cursor somewhere else, then try to place it back inside the link.
4. Note that your cursor is gone and the link is focused

### Screenshots, screen recording, code snippet

_Ignore the weirdness of where the popovers sit on the screen, that's a separate Playground issue that's been reported_

https://github.com/WordPress/gutenberg/assets/6867360/bf5288d3-4be6-49a3-a66e-a5a6f021bc99

### Environment info

- Default theme,(tested in other themes as well)
- Only occurs when 17.8.0 is active

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
I can replicate this with 6.5 Beta 3:

https://github.com/WordPress/gutenberg/assets/26996883/9b1259b3-6006-4e53-af6c-dae51e104843

Adding to the 6.5 board as a result. cc @richtabor if you can help track this down!

**Comment by annezazu** [comment]
Dug into this and compared it to what was intended in the new Link Control UX for invoking the rich text link UI: https://github.com/WordPress/gutenberg/pull/57986 Here's a playground link that [opens up that specific PR](https://playground.wordpress.net/#%7B%22landingPage%22:%22/wp-admin/%22,%22steps%22:%5B%7B%22step%22:%22login%22,%22username%22:%22admin%22,%22password%22:%22password%22%7D,%7B%22step%22:%22mkdir%22,%22path%22:%22/wordpress/pr%22%7D,%7B%22step%22:%22writeFile%22,%22path%22:%22/wordpress/pr/pr.zip%22,%22data%22:%7B%22resource%22:%22url%22,%22url%22:%22/plugin-proxy.php?org=WordPress&repo=gutenberg&workflow=Build%2520Gutenberg%2520Plugin%2520Zip&artifact=gutenberg-plugin&pr=57986%22,%22caption%22:%22Downloading%20Gutenberg%20PR%2057986%22%7D,%22progress%22:%7B%22weight%22:2,%22caption%22:%22Applying%20Gutenberg%20PR%2057986%22%7D%7D,%7B%22step%22:%22unzip%22,%22zipPath%22:%22/wordpress/pr/pr.zip%22,%22extractToPath%22:%22/wordpress/pr%22%7D,%7B%22step%22:%22installPlugin%22,%22pluginZipFile%22:%7B%22resource%22:%22vfs%22,%22path%22:%22/wordpress/pr/gutenberg.zip%22%7D%7D%5D%7D). Note there's some weirdness on that branch that's specific to playground. In that experience, the result is the same as above. Essentially, you can use your keyboard to arrow into the link without invoking the rich text and, when you click on a linked item, the rich text UI opens. Here's a demo:

https://github.com/WordPress/gutenberg/assets/26996883/d749ec55-73ae-4a14-9589-dfbcbc569b20

All of this is to say that this is intended behavior with this change in mind! Here's the broader context an initial issue: https://github.com/WordPress/gutenberg/issues/57821 This was done with accessibility in mind. What seems to be missing though is the ability to click _again_ to then edit the text like so (using slack since that was part of the inspiration):

https://github.com/WordPress/gutenberg/assets/26996883/c2c7f551-6b85-4b44-b0de-2a69c923e224

Without that additional ability to click again to then edit the text, it is pretty annoying. Is this something we can fix? @jeryj  @alexstine @joedolson for broader awareness and discussion.

**Comment by annezazu** [comment]
Tried to update the title to better reflect what's going on. Since we're coming up on 6.5 RC1 tomorrow, I don't know how much this is a true "bug". I'm very much at the end of my day but wanted to note that since this is in the 6.5 board.

**Comment by getdave** [comment]
You are correct. This behaviour was added because if a popover appears then it should be focused because otherwise it's not clear to non-sighted users (or users of assistive tech) that it _exists_.

That said, this flow feels like it could be improved in a future release. As @annezazu suggested a Slack like interaction could work:

![Screen Capture on 2024-03-05 at 14-00-47](https://github.com/WordPress/gutenberg/assets/444434/0c43dbc8-2e1b-4724-838f-c7df4613d2e8)

That said, I'm not sure this constitutes a bug but rather a chance for future improvement. As we're now past the Beta stage for WP 6.5 we need to be pretty selective if we include bug fixes in the RC stage.

Perhaps someone would like to raise a PR to resolve this in the Gutenberg _Plugin_ though?

**Comment by bacoords** [comment]
> This was done with accessibility in mind. What seems to be missing though is the ability to click again to then edit the text like so (using slack since that was part of the inspiration):

Thanks for sharing. I'd never seen this interaction before but I think the Slack example is a great balance between accessibility and conventional practice. 

> That said, I'm not sure this constitutes a bug but rather a chance for future improvement. As we're now past the Beta stage for WP 6.5 we need to be pretty selective if we include bug fixes in the RC stage.

I just want to be clear that in the upcoming version of WordPress, you will be unable to place your cursor inside of linked text using only your mouse. The only workflow options would be: 

1. Using your keyboard to press the escape key to exit the modal
2. Selecting text outside of the link and then using the arrow keys to manually move the cursor into the linked text
3. Pressing the edit icon in the popover and modifying the text of the link inside a modal window

I just want to clarify that those are the intended interactions for users for the next WordPress release when we say this is not a bug.

**Comment by getdave** [comment]
> I just want to clarify that those are the intended interactions for users for the next WordPress release when we say this is not a bug.

Apologies I could have been clearer. What I'm saying is that the WordPress release process is clear that we need to be extremely selective about any bugfixes that land during the RC phase. We'd need buy-in from the entire release team in order to land any fix for this issue.

As far as I'm aware there is currently no PR to address this. Anyone is welcome to pick it up.

I'm now asking for wider opinions on the _severity_ of this issue bearing in mind that we'd need to be able to justify it to the WP 6.5 release team to allow it to land.

**Comment by youknowriad** [comment]
cc @ellatrix I would appreciate some eyes on this one.

**Comment by getdave** [comment]
It may be possible to invert the click handler that opens the popover so that a second click would close it.

https://github.com/WordPress/gutenberg/blob/1a5bdfeca75cf2a40ccbbac738492a4103bc6629/packages/format-library/src/link/index.js#L62

```
setAddingLink( ( currentValue ) => ! currentValue );
```

**Comment by draganescu** [comment]
> I just want to be clear that in the upcoming version of WordPress, you will be unable to place your cursor inside of linked text using only your mouse.

I want to acknowledge that this is **a bug** - it is not an improvement to make things as what they are everywhere else and were before.

However, in my opinion, given that as described there are at least three different ways to circumvent it, and without even an agreement on how to fix in terms of UX (maybe a second click?) it's hard to _confidently_ include it for next release at this stage. If some fix appears it could be considered for any dot releases.

It is regrettable tho that the problem was not surfaced earlier in the cycle. But given how much back and forth the linking experience has had recently it was bound to introduce some weirdness and bugs.

**Comment by richtabor** [comment]
Double-click makes sense to me. If possible, it's worth getting this into the release. I consider the current state of this particular flow a regression from the previous release.

**Comment by annezazu** [comment]
Agreed on double click and on trying to get this into the release. It's a pretty confusing/almost poor experience right now. @fabiankaegy for your thoughts as co-triage lead.

**Comment by fabiankaegy** [comment]
Yeah double click also makes sense to me 👍

Thanks for the ping :)

**Comment by youknowriad** [comment]
Ok for getting this back into the release. Can we get some testing for https://github.com/WordPress/gutenberg/pull/59599

**Comment by getdave** [comment]
Great thanks folks. Glad to see a consensus on this needing to land in WP 6.5. We do now need to add it back onto the board though so I went ahead and did that.

Lets see if we can tidy up my PR, hopefully with support from folks who were heavily involved in contributing to the revised Link UI 🙏

**Comment by getdave** [comment]
I have an alternative fix PR in progress over here which might end up being a better route

https://github.com/WordPress/gutenberg/pull/59635

**Comment by annezazu** [comment]
Thanks for the great work here, folks, to iterate quickly!
