### ISSUE TITLE
Pattern Overrides: No opt-out mechanism exists for named overrides

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#59812]
## Problem

Since the PR '[Use block naming for marking blocks as overridable in patterns](https://github.com/WordPress/gutenberg/pull/59268#top)' was merged, all a user has to do to mark a block within a pattern as overridable is to provide a block name—either using List View, or the input in the 'Advanced' inspector controls.

Currently there's no way to name a block for organizational purposes, and not have it be overridable, which is a problem.

Let's discuss potential solutions to this problem in the comments.

**Comment by talldan** [comment]
My idea to solve this would to implement this feature - [Add option for fully locking a block](https://github.com/WordPress/gutenberg/issues/51968#top)

Within the pattern blocks could be completely locked and this would be respected in instances of the pattern.

The option could also be surfaced as part of the naming process so that a user could name the block and also opt-out as part of one step.

Potentially in the future, this could be more granular and allow locking/unlocking individual attributes, but right now that seems like a longer term goal.

**Comment by fabiankaegy** [comment]
I still hold the opinion that the default state of whether something is overwritable should be false. Even when named.

The main interface for renaming a block is the list view. Not the advanced inspector controls. To me, this does not really solve the full UX issue. From my point of view, it is a bad experience to have a side-effect on a feature as common as renaming.

Like I've said before. Users are so used to the fact that they can rename files, layers, elements, etc. in other pieces of software / operating systems. And that action should not have a side-effect. I'm fine with using the name as the underlying API for us to determine what overrides are connected to instead of a unique ID (even though I still think that fixing a typo in a name should not mean that all instances lose the connection because it is really hard for users to understand why that happened)

(Originally shared this in #60066 but @kevin940726 shared it would be best to share here also :))

**Comment by jasmussen** [comment]
> I still hold the opinion that the default state of whether something is overwritable should be false. Even when named.

I don't yet personally have a full enough picture of the consequences one way or the other, but will say that if named overrides require opt-in, then [it could potentially allow us to show a modal warning when renaming](https://github.com/WordPress/gutenberg/issues/59813#issuecomment-2011763520).

**Comment by kevin940726** [comment]
Closing as since https://github.com/WordPress/gutenberg/pull/60234 this feature requires opt-in by default.
