### ISSUE TITLE
Publish button not visible for existing Gutenberg posts on Mobile

### ISSUE THREAD

**Issue by crunnells** [WordPress/gutenberg#5987]
## Issue Overview
On Gutenberg 2.5, if you edit an existing Gutenberg post on a mobile device (or in my case, Firefox with Responsive Design Mode enabled, viewport 320px wide) the only button visible up top is a "Switch to Draft" button (which doesn't seem to work).

## Steps to Reproduce

1. Install Gutenberg 2.5
2. On a mobile phone, write a new post, click Publish.
3. Navigate back to All Posts, then edit the post you just created
4. Notice the "Publish" button is missing from the header

## Expected Behavior
Publish/Update button should be available on mobile for all posts, not just new.

## Possible Solution
https://github.com/WordPress/gutenberg/blob/37ccb55641012694800610eb0216a6e9e9670628/edit-post/components/header/style.scss#L32 

There's some CSS above that hides the buttons unless the viewport is > 600px. Ideally, editing existing posts should match editing new posts (with the exception that "Publish" is changed to "Update"). This is the _cause_ of the issue, but probably not related to the fix.

## Screenshots / Video
<img width="403" alt="screen shot 2018-04-04 at 11 54 09 am" src="https://user-images.githubusercontent.com/4297811/38338447-5b944d0a-3805-11e8-95a0-44e07ad06f21.png">

**Comment by rahulsprajapati** [comment]
Here is some background of this issue, needed to be considered while adding a fix:

This button removed because of space issue in mobile to support better ui in all languages. But doing so I think now we don't have option to update post in mobile view.
Issue: https://github.com/WordPress/gutenberg/issues/4231
PR: https://github.com/WordPress/gutenberg/pull/5329
https://github.com/WordPress/gutenberg/pull/5329/files#diff-b983d291fe6562507995c8a9288eedbeR30


I think we can keep `Preview` button hidden but show the `Update` button and that should work for us. But we need to provide some option to see the preview of updated content as we have it in desktop view.

https://github.com/WordPress/gutenberg/blob/37ccb55641012694800610eb0216a6e9e9670628/edit-post/components/header/style.scss#L30-L37

We just need to remove this css for publish/update button, but I think even after this we might face issue in other languages. Need some better solution.
 
Remove L31:
> .editor-post-switch-to-draft + .editor-post-preview + .editor-post-publish-button

**Comment by jasmussen** [comment]
Pretty sure this issue was fixed recently when an Update button was unhidden on mobile (the fact that it was hidden was the bug). Closing as fixed, but please chime in if it wasn't, and we'll reopen.
