### ISSUE TITLE
Calendar styles are broken in the post publish panel

### ISSUE THREAD

**Issue by octaedro** [WordPress/gutenberg#59966]
### Description

The calendar styles in the post-publish panel, when expanding the scheduling section, look broken.

### Step-by-step reproduction instructions

1. In a brand new JN site, install GB 17.9.0
2. Go to Posts > Add New Post
3. Add a Title and press `Publish`.
4. The post-publish panel will be visible.
5. Press `Publish: Immediately`.
6. The calendar will be visible, but it will be cut.

### Screenshots, screen recording, code snippet

![Screen Recording on 2024-03-18 at 04-29-38](https://github.com/WordPress/gutenberg/assets/1314156/0d592d00-52e8-4b38-a897-4a262fa7638d)

### Environment info

It's happening on `GB 17.9.0`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
I can replicate this with 6.5 RC2. Adding to the board.

**Comment by t-hamano** [comment]
I believe this issue is a regression caused by #55502. This can be reproduced for the first time in WP6.5.

In #55502, the button size was increased from 28px to 32px, which seems to have caused it to overflow the sidebar width.

Below is a screenshot on Windows OS, but the Sunday column is completely hidden.

![image](https://github.com/WordPress/gutenberg/assets/54422211/670f1a2d-ecb5-46d4-bd9a-852c9286c268)

The following is a screenshot from WP6.4, and although the overflow itself does not occur, the calendar elements are sticking out of the grid layout, so some fundamental adjustment will be required.

![image](https://github.com/WordPress/gutenberg/assets/54422211/4f8710a3-0a86-4d70-b182-948523d35360)

**Comment by getdave** [comment]
> I believe this issue is a regression caused by https://github.com/WordPress/gutenberg/pull/55502.

Can we revert the change to day sizing introduced in that PR and see if it fixes? We can then ship that fix in 6.5 and seek a more robust solution to enlarging the text size during 6.6 cycle.

**Comment by t-hamano** [comment]
I submitted a PR: #59990

**Comment by t-hamano** [comment]
@getdave #59990, which fixes this issue, has been merged. We didn't make it in time to ship to RC3, but I don't think this issue is critical, so 6.5.1 might be fine.

**Comment by getdave** [comment]
I'm happy punting this to 6.5.1 - cc'ing @fabiankaegy and @annezazu for confirmation.

**Comment by annezazu** [comment]
I'm okay with that 👍🏼 The functionality still works so it feels less mission critical.
