### ISSUE TITLE
Make Add block icon permanently visible

### ISSUE THREAD

**Issue by helgatheviking** [WordPress/gutenberg#60263]
## What problem does this address?

The "Add block" plus icon is really fickle and it's much harder to get it to display than I think it should be. I cannot make it appear at all to insert a block at the beginning of a post if there's existing content.

![20240327_190505](https://github.com/WordPress/gutenberg/assets/507025/82414e7b-b87f-4ef4-a644-dd3aeb7dc4d3)

## What is your proposed solution?
Yes, there are workarounds like using the tree navigation, or selecting the block above/below and selecting "add before" or "add after". 

But I propose we make it _always_ visible so it's always a single click to add a block between two existing blocks. 

It can be very pale gray until hovered to make it not too distracting

**Comment by richtabor** [comment]
I do think it'd be a bit much seeing potentially tens of [+] icons between all blocks. But there's certainly some improvements we can do on discoverability. 

Perhaps it can render via proximity—when you're near it—rather than only when you're interacting with the space between blocks. 

And it's a bit slow to reveal currently, adding a bit of hesitation and lack of confidence in knowing if it's actually going to render.

**Comment by helgatheviking** [comment]
![image](https://github.com/WordPress/gutenberg/assets/507025/520d4d3e-f9f3-4ca5-8952-22bd5258c096)

It could be a lot... but also I think that's still better than _not_ being able to find it at all. Though appearing in proximity sounds better than appearing when you're hovered over that single, magic pixel (exaggeration, but still)

**Comment by bozzmedia** [comment]
In general mouse focus detection in the drag and drop canvas could use improvement. It is often difficult to try to get the focus or "Cursor" to place where you need it to go. I work in the block editor for hours each day and train users of various technical skill levels, this is a regular pain point in the editor.
