### ISSUE TITLE
The ? indicator is missing from the url site params in site editor

### ISSUE THREAD

**Issue by apeatling** [WordPress/gutenberg#60473]
### Description

When in the site editor, selecting the canvas to enter canvas editing mode the url looks like this: `wp-admin/site-editor.phpcanvas=edit`. The ? is missing.

### Step-by-step reproduction instructions

1. Open site editor
2. Select a page to edit
3. Click the canvas to enter editing mode
4. Notice the URL and missing ?
5. Refresh the page, the URL is busted.

### Environment info

Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by tyxla** [comment]
Have you tried running `npm install`, optionally with `npm run distclean` beforehand?

This is likely because of https://github.com/WordPress/gutenberg/pull/60271 which updated the package and the logic to add the `?` or not in the same PR.

We [did take a note](https://github.com/WordPress/gutenberg/pull/60271#issuecomment-2034654933) that in the future we should keep those 2 separate (dependency update and logic update)

**Comment by apeatling** [comment]
Yes this fixed it, thanks!
