### ISSUE TITLE
TextControl: Add 'show password' toggle to password input

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#60502]
<img width="1337" alt="Screenshot 2024-04-05 at 09 30 05" src="https://github.com/WordPress/gutenberg/assets/846565/d0af6c9a-8885-4e3c-aade-d8f43137dffd">

Adding support for an optional 'show password' toggle could be a nice enhancement for the password variant of the [TextControl](https://wordpress.github.io/gutenberg/?path=/docs/components-textcontrol--docs) component.

cc @WordPress/gutenberg-components

**Comment by mirka** [comment]
Do we already have a need for this in Gutenberg, by the way?

If we were to build this, I think we'd need to make it a new component (e.g. `PasswordControl`) since it's a bit presumptuous to automatically enhance it this way based on just `type="password"`.

On the other hand, this is very simple to implement using InputControl (not TextControl) — trivial enough that it might even be sufficient to just add a new example story in the Storybook docs for InputControl. So we can go that route if we don't have plans to reuse it multiple times in Gutenberg.

**Comment by jasmussen** [comment]
If it's trivial to add the story, I'd start there and upgrade to a component later on if we do find a need. At the moment, this is the only place where this is used.

**Comment by jameskoster** [comment]
Yeah, fine to start with a story.

There's no immediate need, but it will likely be useful when it comes to redesigning admin areas such as the edit profile page. I imagine plugin devs might find it useful too.
