### ISSUE TITLE
Back navigation in block chooser on mobile should close chooser, not navigate away from the page

### ISSUE THREAD

**Issue by Shelob9** [WordPress/gutenberg#6055]
## Issue Overview
I'm trying to write a post using Chrome for Android. My phone is a garbage phone and UI interactions can be slow. When I enter the new block chooser, the text based search is focused. As a result I see the block icons then they get covered by the keyboard. If I hit back once, the keyboard goes away and I can tap on the block I want.

But if I tap the back navigation button a second time, then the browser leaves the post editor. Keep in mind, my phone is slow, so it's hard to tell if the keyboard didn't close beacuse it's still working on it or I didn't actually hit the button. I lack patience so I hit it again and now I'm no longer in the post editor, hopefully an auto save happened.

I'm probably not the only impatient WordPress user editing content with an underpowered phone. Better handling of back navigation here would help :) 

## Ideas 
1. On mobile do not focus block search input when opening block chooser. Personally I'd prefer to scroll and tap on mobile, but I have no research to say others feel that way.
2. In the block chooser, change behavior of back button so that it closes the block chooser. This feels like what should be the expected behavior.

**Comment by nerrad** [comment]
There's been a number of changes since this issue was creataed, @Shelob9 any chance you can retest this and verify if this is still an issue?

**Comment by aduth** [comment]
I've tested this on iPhone XR Safari 12.1 (via XCode emulation).

When opening the inserter, the search field does become focused, but keyboard flyup does not occur immediately ([screenshot](https://user-images.githubusercontent.com/1779930/58705924-96c32480-837e-11e9-929b-5c0d09ada9f7.png)). I suspect this might be an OS-specific behavior, so I would like to keep this open pending verification of the original Android + Chrome report. It's likely that keyboard flyup could occur, since the input is assigned with an `autofocus` attribute ([source](https://github.com/WordPress/gutenberg/blob/69f100676c283f13e6c6ec56003682bd86a68f60/packages/block-editor/src/components/inserter/menu.js#L281)).

On the behavior of the back button: I can only see this working if these were separate navigable resources (separate addressable URLs). I can empathize with the inclination to use "Back" as an escape, but in this case it the open inserter is not an addressable state of the application. Without it being one, forcing the Back behavior to work this way would require hacking around [History#pushState](https://developer.mozilla.org/en-US/docs/Web/API/History_API#Adding_and_modifying_history_entries) in a way which I expect would have undesirable consequences both for mobile and desktop (e.g. if closing by "X", pressing Back would cause the inserter to open again). I would be inclined to assign this request as "wontfix".
