### ISSUE TITLE
Zoom-out mode issues on Safari

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#60601]
### Description

On Safari, I can see a number of issues in zoom-out mode.

Opening the zoom-out mode (either though global styles variations or patterns inserter), shows a white background  instead of the gray one.

<img width="1470" alt="Screenshot 2024-04-09 at 2 00 32 PM" src="https://github.com/WordPress/gutenberg/assets/272444/adcbc226-d59c-43a7-ad01-3a0253919d59">

Also, if you open both the global styles and the patterns inserter at the same time, you may see a bit of both.

![Screenshot 2024-04-09 at 1 43 36 PM](https://github.com/WordPress/gutenberg/assets/272444/443613d7-1023-4c4c-a746-f2c41146216f)

The third issue is that sometimes I see a huge padding on top of the canvas and I have to scroll down to actually see the template

<img width="1470" alt="Screenshot 2024-04-09 at 2 01 51 PM" src="https://github.com/WordPress/gutenberg/assets/272444/104f79b7-d70b-4a02-b64f-dfe85842ce48">

**Comment by richtabor** [comment]
Related? https://github.com/WordPress/gutenberg/pull/60550

**Comment by glendaviesnz** [comment]
> Opening the zoom-out mode (either though global styles variations or patterns inserter), shows a white background instead of the gray one.

In my [investigation into this here](https://github.com/WordPress/gutenberg/issues/60552), it appears that this is due to the different way in which Safari deals with background color on a transformed element. It seems that Safari does what you would expect and only applies the background to the transformed size of the div, whereas Chrome keeps the background color applied to the pre transformed size of the div. I think it sort if works in Chrome by accident so we probably need to add an additional `is-zoomed-out` class on the relevant `div` so we can explicitly apply the background color for this - but that was just a quick assessment, I may be wrong about this.

> The third issue is that sometimes I see a huge padding on top of the canvas and I have to scroll down to actually see the template

This should be fixed by [this revert](https://github.com/WordPress/gutenberg/pull/60616).

**Comment by MaggieCabrera** [comment]
https://github.com/WordPress/gutenberg/pull/60873 fixes the first issue, I don't think the second is relevant anymore (we can't have GS sidebar open at the same time as the patterns) and I can't reproduce the third anymore, so if my PR gets merged that should solve this whole issue unless I'm missing something in my testing
