### ISSUE TITLE
Documentation: List of keyboard shortcuts is out of date

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#60627]
### Description

Discovered while working on https://github.com/WordPress/gutenberg/issues/60567

The list of keyboard shortcuts at https://github.com/WordPress/gutenberg/blob/e5e2bd2a6db1e8d4648903f90d89640639fb7999/docs/getting-started/faq.md#are-there-keyboard-shortcuts-for-gutenberg is out of date.

For example, it misses the 'aliases' for the 'navigate region' and it misses the 'Add non breaking space' keyboard shortcut added in https://github.com/WordPress/gutenberg/pull/43150. Possibly, it misses more keyboard shortcuts.

On another hand, I'm not sure this list of keyboard shortcuts should be there in the first place, as this seems more documentation for developers rather than for end users. Anyways, this list should be either maintained and kept up to date or entirely removed.

### Step-by-step reproduction instructions

- Go to https://github.com/WordPress/gutenberg/blob/e5e2bd2a6db1e8d4648903f90d89640639fb7999/docs/getting-started/faq.md#are-there-keyboard-shortcuts-for-gutenberg
- Observe the list of keyboard shortcuts is incomplete, compared with the lists in the various keyboard shortcuts modal dialogs in the editors.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I have already submitted a PR to update the shortcut (#47920). I would like to resolve the conflict, recheck the current shortcuts, and update them.

**Comment by afercia** [comment]
Good to know @t-hamano. It's great you already submitted a PR.
Is this list of shortcuts in the best place in your opinion? It should be more prominent maybe?

**Comment by t-hamano** [comment]
To be honest, the current shortcut list is not completely accurate. This is because the available shortcuts differ slightly depending on the type of editor. Please refer to the table in #47920.

One approach might be to create a new page just for shortcuts and display a complete list of each editor. Then include a link to that page in the answer to the question in the FAQ content.

What's more, the content of this page itself appears to have remained unchanged for close to several years (see [the history of this file](https://github.com/WordPress/gutenberg/commits/fix/consolidate-synced-bindings-colors/docs/getting-started/faq.md)).

It might be time to overhaul this page itself.

cc @ndiego @justintadlock

**Comment by afercia** [comment]
> the content of this page itself appears to have remained unchanged for close to several years 

Yep, is there's no way to guarantee this page is maintained and updated regularly, I'd vote for entirely removing the table and just explain how to get the list of shortcuts in the editor(s).

**Comment by t-hamano** [comment]
> I'd vote for entirely removing the table and just explain how to get the list of shortcuts in the editor(s).

This is a good idea. This shortcut list is likely to become outdated frequently, and updating it manually each time is a bit of a hassle. Additionally, users are burdened with checking which column in the table their OS corresponds to.

On the other hand, the shortcut modal displays the shortcuts available in the current editor, as well as the key combinations that are actually available depending on the user's OS.

I would like to close https://github.com/WordPress/gutenberg/pull/47920 and submit a new PR.
