### ISSUE TITLE
Wrong select function types in @wordpress/data

### ISSUE THREAD

**Issue by szaleq** [WordPress/gutenberg#60666]
### Description

The types of `select` function exported from `@wordpres/data` directly differ from the `select` function passed as argument to `useSelect` hook callback. The first one (directly exported) works fine, while the second (inside the hook) doesn't. 

`select('core/editor')` gets proper type if imported directly, each selector is properly typed and returns typed value but when the exactly same call is used inside `useSelect` hook, the return type of `select(...)` is always `never`.

### Step-by-step reproduction instructions

1. Create empty typescript-react project
2. install `@wordpress/data@9.25.0`, `@wordpress/editor@13.32.9` and `@types/wordpress__editor@13.6.8`
3. Try to create a React component with `useSelect` hook and use any of the selectors from any store.

### This works
```typescript
import { select } from '@wordpress/data';

select('core/editor').getCurrentPostType();
```
![image](https://github.com/WordPress/gutenberg/assets/25011639/15846f8b-d137-4e8d-b9f2-75a3bfe66f67)
![Code_0MmPzS7Hqy](https://github.com/WordPress/gutenberg/assets/25011639/a662a6fb-bb89-4dd7-bc09-90a3a7608ae3)

### This doesn't work
```typescript
import { FC } from 'react';
import { useSelect } from '@wordpress/data';

const Example: FC = () => {
	const postType = useSelect(
		(select) => select('core/editor').getCurrentPostType(),
		[]
	);

	return null;
};
```
In the above code `select('core/editor')` is resolved as `never`, causes errors (despite returning correct selectors when built and run in browser as JS):
![image](https://github.com/WordPress/gutenberg/assets/25011639/ca9305a5-7e9f-4e79-9d46-6c459aab456e)

### Environment info

Package versions:
* @wordpress/data: `9.25.0`
* @wordpress/editor: `13.32.9`
* @types/wordpress__editor: `13.6.8`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by sirreal** [comment]
Thanks for the report!

[The issue here lies with the third-party types provided by definitely typed](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3d2ab3a26987437366ec637a5401e5bd08f67c43/types/wordpress__editor/index.d.ts#L5-L12). Gutenberg does not officially support those third-party types. To improve this, you'll need to file an issue or PR there.

There have been efforts to add more types (and official support) to packages in Gutenberg, unfortunately data has proven to be very difficult to type properly and progress has stalled.
