### ISSUE TITLE
Need of TextColor for inline formatting (single words/characters)

### ISSUE THREAD

**Issue by burnuser** [WordPress/gutenberg#6080]
In the moment, text color is a formatting option which can only used for a whole paragraph.

For myself I used text color many times, but only to emphasize single words or characters for special attention, mark as changed, mark as different, ...
(But I never used it for a whole paragraph.)

As you integrated text color in formatting of paragraphs, you agree, that text color is a useful formatting tool. So I suggest, to make text color an inline formatting option like Bold and Italic (at least for Paragraph, List and Quote blocks) instead or additional to the existing Paragraph block option.

**Comment by danielbachhuber** [comment]
Hi @burnuser,

Thanks for the suggestion! This sounds like a great idea for a plugin to me.

**Comment by aristath** [comment]
@danielbachhuber this is already possible right now in WordPress with the existing post editor.
Shouldn't Gutenberg at the very least make sure that no existing core capabilities are removed?

**Comment by danielbachhuber** [comment]
> this is already possible right now in WordPress with the existing post editor.

Ah, you are correct:

<img width="866" alt="image" src="https://user-images.githubusercontent.com/36432/38557352-a1dc79ce-3c81-11e8-8216-ec7e1c8186f3.png">

> Shouldn't Gutenberg at the very least make sure that no existing core capabilities are removed?

Gutenberg won't totally replicate the Classic Editor. However, the breaking changes should be documented at the very least. See #4186 #4190

Flagging this as `Needs Design Feedback` to verify text color isn't a button we want to add to the standard text toolbar. I'd suspect not, but I'll make sure there's a second opinion.

**Comment by SuperGeniusZeb** [comment]
It should also be noted that `<span>` tags, as well as `<code>`, `<kbd>`, `<time>`, `<abbr>`, and various other inline HTML tags are allowed in Paragraph, List, and Quote blocks, so you can add inline formatting manually using the "Edit as HTML" setting.

However, Classic blocks containing paragraphs, lists, and blockquotes with these inner formatting options have them removed when the "Convert to Blocks" setting is used. See #6102.

**Comment by karmatosed** [comment]
I think this could be a good option but it would have to for me reuse the background and text color settings, not add new. Maybe it's when highlighted those then apply to the highlighted text.

**Comment by karmatosed** [comment]
@SuperGeniusZeb interesting idea but I think adding a tab just for this probably isn't the simplest route. I think simply have when you highlight a section of text the 'text color' allows you to change that and background allows you to also change that as long as it's highlighted. We may need to explore how discoverable this is. If it's not discoverable we can add a section to the 'Color Settings' over adding a new tab to the top level.

![colorcombo2](https://user-images.githubusercontent.com/253067/39210608-20122c00-4801-11e8-8e8a-2f1eb3dc0ccf.png)

**Comment by gziolo** [comment]
It looks like this is something that could be optionally integrated when #4658 is implemented. @iseulde, actually it could be good for dogfooding to combine those two issues into one PR.

**Comment by karmatosed** [comment]
@gziolo that would be great. This really does seem like something people want and I would say it's a good to functionality to look into.

**Comment by GlennMartin1** [comment]
Consider that the paragraph block will be the **most common block**.

Hence, we need a very functional paragraph block.

In a similar vein, it's impossible to specify a different size for select text within a block.

**Comment by RayWaldo** [comment]
### I rather like Gutenberg overall. 
I have been using it for a week or so and the block functions are a true advancement. I understand that the present iteration is not the final product. I have been "limping" along trying to acquaint myself with it.

**However, I will dislike Gutenberg greatly if most core functions of the existing editor are dropped.** ESPECIALLY if the use of G. will REPLACE or eliminate inline formatting in existing posts when re-edited using G.
**_Gutenberg should be a step forward - not 5 steps back, as would be the case if G. would require the use of HTML tags to do what is in the core now._**
I use the text color formatting regularly and do not want it eliminated. Also, there is a downside to adding any plugin - so that should not be the response. Most of us are already using more plugins than we really want.

**Comment by jcklpe** [comment]
@RayWaldo  This issue is being worked on here https://github.com/WordPress/gutenberg/issues/4658 Please chime in and let the devs know that this is an important feature. To me, it's the single largest feature still missing from Gutenberg.

**Comment by shoelaced** [comment]
Not being able to highlight and color text is annoying and would be worse for the average user. I see no issue with the entire paragraph changing color when nothing is highlighted, and when text is highlighted, only the highlighted text would be colored, using the same "Text Color" area in the sidebar for both. It seems to me this would be completely expected behavior.

Yes, text color is available in the "Classic" block, but:

- It doesn't work with `add_theme_support( 'editor-color-palette', $colors );`.
- It doesn't even work with the `tiny_mce_before_init` hook, which is often used to change the available colors in the current editor.
- The "Classic" block doesn't let the user change the background color the way the paragraph block does.
- Users would never think "Hm, I need to change the color of just one word, so perhaps I can use the Classic block," especially users who start using WP after Gutenberg and have no idea what the classic editor is.

Tiny usability things like this may seem small but they're a big deal to clients.

**Comment by iseulde** [comment]
The plugin [Advanced Rich Text Tools](https://wordpress.org/plugins/advanced-rich-text-tools/) will now add inline text and background color controls.

**Comment by RhysMcW** [comment]
> 
> 
> The plugin [Advanced Rich Text Tools](https://wordpress.org/plugins/advanced-rich-text-tools/) will now add inline text and background color controls.

Thank you Ella, installed and did a very brief test and can now colour words as needed, yay

**Comment by gziolo** [comment]
@iseulde, thanks for sharing this plugin. It uses new Format API to implement all format controls, including text color for individual characters and resolves the issue 🎉

**Comment by jcklpe** [comment]
Yay! Thank you @iseulde !

**Comment by RAIMUNDOS54** [comment]
No option to change text color anywhere in Gutenberg.

**Comment by phpbits** [comment]
I've recently added text highlighting color options on EditorsKit plugin ( https://wordpress.org/plugins/block-options/ ) and I hope this solves this problem. Here's how my implementation works :

![Gutenberg Highlighted Text and Background Colors](https://user-images.githubusercontent.com/3365507/57937370-60a29100-78f8-11e9-8069-06a8ec43259d.gif)
