### ISSUE TITLE
Improve and align application of lock icon in list view

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#60834]
### Current state of affairs

When you edit a **page** with template preview on, list view shows the following:

<img width="382" alt="Screenshot 2024-04-17 at 18 11 01" src="https://github.com/WordPress/gutenberg/assets/846565/6e569104-67e5-4bc9-bd65-34c78f2d2aa0">

---

When you edit a **partially synced pattern** instance, list view shows:

<img width="346" alt="Screenshot 2024-04-17 at 18 12 21" src="https://github.com/WordPress/gutenberg/assets/846565/8656c4ce-3c13-49fe-bd28-0b79ff9b32b1">

---

### The problem
The lock icon is not entirely helpful for a couple of reasons:

1. Visual overlap with the user-controlled locking mechanism despite subtly different behavior.
2. Suggests the block is not editable at all which isn't the case.
3. Suggests the block can be unlocked in context which isn't the case.

Is there an alternative to the lock icon?
 
cc @WordPress/gutenberg-design

**Comment by talldan** [comment]
I personally think the two things are completely aligned here, though I agree the lock icons are confusing.

The header, footer, site title, featured image *are* editable. They can be selected and interacted with in a limited sense, but they can't be moved because the layout/design is provided by the template entity.

It's the same in a pattern with overrides, the blocks that have overrides can also be interacted with in a limited sense, but the layout/design is provided by the pattern entity.

In both cases these blocks are shown in list view with a lock icon. In both cases there might also be a lot of other blocks that are completely hidden from view (e.g. groups that provide a layout, or other design elements). The only additional part in a page is that it has a completely freeform area—post content—which patterns don't have (but it could be a cool feature).

The confusing thing for me is the way the locks in list view are shown, In both cases these blocks are only partially locked.

**Comment by jasmussen** [comment]
In adjacent apps traditionally the lock has denoted _completely locked_: entirely unselectable. Vs. here that's not necessarily the case. An extreme example is Photoshop, which allows locking multiple different properties individually:
![photoshop layer locking options](https://github.com/WordPress/gutenberg/assets/1204802/9923d8be-c773-43bf-8151-27d39bb2bae4)

We should definitely avoid that. It's also indeed behaving as built — the lock icon is shown in all of the following manual locking cases:
![lock paragraph modal](https://github.com/WordPress/gutenberg/assets/1204802/bf87d074-197f-4e32-8863-a0bead0f7694)

* Disable movement
* Prevent removal
* _Both_

It seems valid enough, _especially for manual locking_, to show the lock icon when one of those properties is chosen, otherwise it might be hard to denote the difference between blocks in the list. 

For me the primary headache is that traditionally, the lock icon means _nested items are also locked_. I.e. if a group is locked, so is everything inside. So I wonder if there's a way we can add nuance:

* Show the lock only for anything that's manually locked.
* Gray out / reduce opacity for blocks that are template locked (I.e. header/footer, TPs)
* Don't show the lock at all on blocks nested in partially synced patterns. The purple color and the sync icon on the parent should be enough to denote that _these behave differently_.

What do you think?

**Comment by jameskoster** [comment]
> I personally think the two things are completely aligned here

You're right, I think I was testing with a simple template here, and all blocks were appearing while page editing. On further testing I see list view does strip out uneditable template blocks which is consistent with with partially synced patterns. I'll update the issue to focus on the lock icon.

**Comment by jameskoster** [comment]
For reference here are all the states list view needs to entertain:

| State | Current treatment | Screenshot |
| --- | --- | --- |
| Fully locked <br>`"lock":{"move":true,"remove":false}` | Lock icon, ellipsis accessible | <img width="350" alt="Screenshot 2024-04-18 at 12 18 51" src="https://github.com/WordPress/gutenberg/assets/846565/3e0b9696-ba30-4a37-b08a-fd5ee7c093d5"> |
| Fully locked due to context (e.g. general template blocks in page editing) | Stripped from list view | n/a |
| Move locked | Lock icon, ellipsis accessible | <img width="350" alt="Screenshot 2024-04-18 at 12 18 51" src="https://github.com/WordPress/gutenberg/assets/846565/3e0b9696-ba30-4a37-b08a-fd5ee7c093d5"> |
| Remove locked | Lock icon, ellipsis accessible | <img width="350" alt="Screenshot 2024-04-18 at 12 18 51" src="https://github.com/WordPress/gutenberg/assets/846565/3e0b9696-ba30-4a37-b08a-fd5ee7c093d5"> |
| Content only editing | Lock icon, ellipsis hidden | <img width="349" alt="Screenshot 2024-04-18 at 12 20 36" src="https://github.com/WordPress/gutenberg/assets/846565/1cea7dcc-0740-4693-bd74-6a85e3b6c98e"> |
| Selectable but only editable after action (e.g. Template parts in page editing) | Lock icon, ellipsis hidden | <img width="349" alt="Screenshot 2024-04-18 at 12 22 09" src="https://github.com/WordPress/gutenberg/assets/846565/7163e246-87f3-4b6f-b91f-3b5b043c89e7"> |
| Fully editable (regular block) | n/a | <img width="349" alt="Screenshot 2024-04-18 at 12 21 28" src="https://github.com/WordPress/gutenberg/assets/846565/867c036b-2f39-43fc-86d5-a3a4a2e405f3"> |

Practically speaking content only editing is essentially the same as fully locked, so it's easy to see how we ended up with this treatment. But in the context of page editing, the lock icon appearing alongside blocks like title and featured image is a bit confusing – it suggests they aren't editable at all.

Some provocations:

* Given the wide variety of locking options, should the lock icon be more contextually placed? IE if a block is remove locked then show the lock icon next to the "Delete" action. If it's move locked do not show the `grab` cursor.
* Should we remove the lock icon for content only editing (I think that's part of what you're suggesting @jasmussen), in favor of the above? In the page editing context the ellipsis could be exposed but show a message on click:

<img width="691" alt="Page" src="https://github.com/WordPress/gutenberg/assets/846565/816ee439-76f7-4057-9ba8-f24efe2585cf">

**Comment by jasmussen** [comment]
> Should we remove the lock icon for content only editing (I think that's part of what you're suggesting @jasmussen), in favor of the above? In the page editing context the ellipsis could be exposed but show a message on click:

One additional argument in favor of this: we can think of contentOnly editing as "editing a custom block". It's not locked from being deleted, moved, or edited. Similar to synced patterns with overrides, this is the intended way to edit that particular block. 

I've argued separately that it would be interesting to explore a "flattening" of a contentOnly pattern so that it only shows up as a single block in the list view (unless you detach) — it might even be fun to allow a pattern author to choose the block icon. But that's a separate enhancement that would further diminish the need for a lock icon.

**Comment by talldan** [comment]
I'm wondering if this is now solved with the changes in https://github.com/WordPress/gutenberg/pull/61127 (and follow-ups)

I'll close the issue, but feel free to reopen if there's anything remaining.
