### ISSUE TITLE
Content Block: add justification to block toolbar in addition to sidebar

### ISSUE THREAD

**Issue by Nyiriland** [WordPress/gutenberg#60838]
**Suggestion:** 
Add justification options to the block toolbar in addition to the settings sidebar.

**Why:** 
- Because justification settings for other blocks (like text blocks) are in the toolbar. I overlooked this one many times, because I expected it to be in the toolbar, not the sidebar.
- And: there's lots of room for it.

<img width="1260" alt="image" src="https://github.com/WordPress/gutenberg/assets/3835008/1f9aba3f-8b05-4b50-bae9-528e0249100e">

**Comment by jasmussen** [comment]
Good issue, entirely valid. This omission feels unintentional, and would help consistency.

**Comment by shreya0204** [comment]
Hi @jasmussen 

I’m currently working on adding justification controls to the toolbar for the Group block. In my research, I noticed that to include these controls, the block might need to be set to a `flex` layout. However, I'm not completely sure if this is the right approach, especially since the Group block is used in a more generic way.

I've noticed that for Columns, the justification is added in the toolbar because the default layout is flex. 
> https://github.com/WordPress/gutenberg/blob/c3840cd1c66c393dc8bdc2ebb11a6ff50f3c54af/packages/block-library/src/columns/block.json#L49-L55

But, setting the Group block to a flex layout by default might not be ideal.

As the default schema states, it will add controls to sidebar for constrained layout.
> https://github.com/WordPress/gutenberg/blob/c3840cd1c66c393dc8bdc2ebb11a6ff50f3c54af/schemas/json/block.json#L471-L475


Could you help me understand why the Group block is set up the way it is and whether adding flex to enable toolbar justifications would be a good idea to better work on this issue?

**Comment by jasmussen** [comment]
Thanks for diving in, @shreya0204! The group block is intentionally an equivalent to CSS's `display: block;`. To get a flex container, it's an easy transform to the Stack block, which is a counterpart to CSS's `display: flex; flex-direction: column;`. 

The Content block, in this case, does appear to behave the same as the Group block, so great clarification that this issue affects not just the Content Block, but the group block aswell, since that also has the Layout panel and the justification tools.

So how does the Content and Group blocks justify left, center, or right, without being a flex container? In this case, it's got `is-layout-constrained` as a class, and all immediate child blocks then have a width, as well as their margins adjusted as a result. Here's a justified-left example in the editor:

![2024-06-21 09 19 39 local-wordpress local da6ccfa61221](https://github.com/WordPress/gutenberg/assets/1204802/d59a1c3e-d2eb-4ebc-8800-4bb97d53289e)

Here's the frontend result with margin visualization:

![Screenshot 2024-06-21 at 09 19 43](https://github.com/WordPress/gutenberg/assets/1204802/fa4d1cac-b337-4670-a396-88a3a1bdb9a5)

I think @tellthemachines may have worked on those particular rules, if you'd like to dive deeper. That said, I think the main task here isn't so much to change how those rules behave, but rather, add the block toolbar dropdown that's present on flex containers.

**Comment by shreya0204** [comment]
@jasmussen I have raised the PR for this. Can you please review? Thank you.

**Comment by jasmussen** [comment]
Thanks for the ping. I'm out for the day and AFK tomorrow. I can review Monday unless someone from @WordPress/gutenberg-design gets a chance to help. Thanks for contributing!
