### ISSUE TITLE
Converting a table in a classic block to a table block removes all inline styles

### ISSUE THREAD

**Issue by samfull** [WordPress/gutenberg#6096]
## Issue Overview

In the latest version of Gutenburg (Version 2.5.0 ). If you have a table set-up with in-line styles, Gutenburg will remove the styles when you convert it to a block.   

## Steps to Reproduce (for bugs)

1. Make a table with in-line styles without gutenburg
2. Enable gutenburg and edit the page
3. Now you will see the table is now a classic block
4. Convert this to blocks and all in-line styles are lost

## Expected Behavior

In-line CSS is kept, however you can change the values visually. You should also be able to delete rows and columns. 

It would be great if the visual editor displayed the colors and other CSS too. Also it would be nice to be able to change the colors. But for now, just being able to edit the values and not remove all the in-line CSS would be good for users who don't know how to code.

## Current Behavior

All of the in-line CSS for the table is removed when you convert a table from the classic block to the table block.

## Possible Solution

Don't remove the in-line CSS when converting to a table block. The data is kept, so why remove the CSS?

## Screenshots / Video

How the Gutenberg classic block looks like:

![before](https://user-images.githubusercontent.com/38245134/38549672-85065fc2-3cef-11e8-95ac-94819947afe1.png)

How the Gutenberg table block looks like after converting:

![after](https://user-images.githubusercontent.com/38245134/38549679-8b2e8f00-3cef-11e8-9d91-9d0b1bc4380d.png)

The HTML after converting (it has removed the in-line styles)

![after_html](https://user-images.githubusercontent.com/38245134/38549687-8f1668fe-3cef-11e8-9877-ff7ea7f537cf.png)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by danielbachhuber** [comment]
Thanks for the detailed report, @samfull.

It's intentional behavior to strip accessory inline HTML attributes at the moment. There's some room for discussion on:

1. Whether we leave more inline HTML attributes in-place.
2. Whether we need to have UX alerting the user to the fact their data is being stripped out.

See conversation in https://github.com/WordPress/gutenberg/pull/4522#issuecomment-378993956

Related #4498

**Comment by mtias** [comment]
I don't think this one should be a concern for the "try" milestone, since the Table block is completely new and doesn't have a corresponding feature set in core there's not many expectations of conversion capabilities.

It's also not clear if from a design point of view this is something that wants to be supported at all in the table block in general, so we should look at it as arbitrary HTML that upon converting to blocks might lose style attributes, with the option to undo.

**Comment by karmatosed** [comment]
Closing so we can focus on https://github.com/WordPress/gutenberg/issues/6923 for fixing tables.
