### ISSUE TITLE
Inserter: Pattern Category Selection Removes Pattern Tab

### ISSUE THREAD

**Issue by jeryj** [WordPress/gutenberg#60972]
### Description

I believe this is due to the pattern category entering zoom-out mode which selects a root block.

### Step-by-step reproduction instructions

1. Open main Block Inserter
2. Click Pattern Tab
3. Click a Pattern Category
4. Click Block Tab
5. Click Pattern Tab
6. Click Pattern Category
7. Bug: Pattern Category disappears and focus returns to Block tab

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/967608/20a4dc7f-c9f7-4bee-953e-9255c5776407

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jeryj** [comment]
@draganescu @ajlende - maybe caused by https://github.com/WordPress/gutenberg/pull/60909 or was it already there?

Update: It was already there.

**Comment by Mamaduka** [comment]
This also affects the "Media" tab. After the Patterns tab is gone, the Media tab renders no content, and it's no longer displayed when toggling the inserter.

The issue only affects the Site Editor.

## Screencast

https://github.com/WordPress/gutenberg/assets/240569/94cbb490-cf60-4404-b721-94905ca1bc5d

**Comment by draganescu** [comment]
It was there before https://github.com/WordPress/gutenberg/pull/60909 afaik, and the reason is the zoom out mode auto trigger which does something. I can investigate the cause.

**Comment by draganescu** [comment]
- I doesn't happen when editing pages, only when editing templates
- it's a block selection issue, I am uncertain what we should do because currently having a header selected in a page will result in an empty inserter
- for patterns what happens is that when switching to zoom out mode in templates the section root is selected, but when switching out the root element is selected.

We should always select the section root if there is no selection.
