### ISSUE TITLE
When a pattern is first saved, there is a notice that says "Site updated" instead of "Pattern saved".

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#60993]
### Description

When I go to Appearance > Editor > Patterns, select "Create pattern", add my changes and save, there is a notice that says "Site updated.".
This should probably say "Pattern saved." or similar?

### Step-by-step reproduction instructions

Go to Appearance > Editor > Patterns.
Select "Create pattern"
Add some changes and save.
Notice the notice in the bottom corner.

### Screenshots, screen recording, code snippet

<img width="1510" alt="The block editor with a user created pattern that has just been saved for the first time. There is a notice in the bottom left corner with the text: Site updated." src="https://github.com/WordPress/gutenberg/assets/7422055/5e179dee-9f56-48d3-8156-e386d3a57995">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by hbhalodia** [comment]
Hi @carolinan, This seems to be working as expected. I am not able to reproduce the issue with the steps mentioned.

[GB-Issue-60993.webm](https://github.com/WordPress/gutenberg/assets/58802366/c1a8a02a-4f65-4241-a6df-d08cb3a22b66)

Can you please test this again? So that we can confirm if this is solved.



Thank You.

**Comment by carolinan** [comment]
Thank you, I have test again and it has been fixed.
