### ISSUE TITLE
Custom HTML Block should display content in LTR layout for all languages

### ISSUE THREAD

**Issue by Amir-A-M** [WordPress/gutenberg#61324]
### Description

Hi, Thanks for this plugin.
### Pls try to read the numbers one to nine in the picture below. (**Remember that I wrote them in order**)
![image](https://github.com/WordPress/gutenberg/assets/60928821/6827c332-74ad-4fcc-b037-ecc923a06549)
This is a real mess. Isn't it?
Now imagine how can I read and edit a simple HTML! 

### **Just give the textarea `direction: ltr;` to fixe it**
![image](https://github.com/WordPress/gutenberg/assets/60928821/ce3f468c-73eb-418f-b894-991605379800)

### Step-by-step reproduction instructions

Just drag a **Custom HTML Block** or try to **edit a block in HTML**

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by t-hamano** [comment]
Thanks for the report.

Looking at the tickets and PRs below, it seems that the LTR layout is suitable for fields and text areas where codes are entered.

- [#26666 (Text in built-in file editor is RTL instead of LTR) – WordPress Trac](https://core.trac.wordpress.org/ticket/26666)
- [#18021 (Theme editor textarea direction (RTL) - Arabic) – WordPress Trac](https://core.trac.wordpress.org/ticket/18021)
- #50768

I don't understand RTL languages, but do you think it makes sense to have the title area in LTR layout as well?

**Comment by Amir-A-M** [comment]
Yes that right. LTR layout is suitable for codes

> I don't understand RTL languages, but do you think it makes sense to have the **title area** in LTR layout as well?

I'm not quite sure what the 'title area' refers to. Could you please provide a picture that showcases it? That would help me understand better. I'll be happy if I can help.

**Comment by t-hamano** [comment]
> I'm not quite sure what the 'title area' refers to.

Ah, somehow I seem to have mentioned a code editor title that is completely unrelated to this issue. Please ignore this question of mine 😅

![code-editor-title](https://github.com/WordPress/gutenberg/assets/54422211/9486cec5-c495-4980-9ba7-21c115de7dd0)

**Comment by narenin** [comment]
@t-hamano Hi, I have raised [PR](https://github.com/WordPress/gutenberg/pull/62083) with fix, could you please check.
