### ISSUE TITLE
Inserter menu items are vertically centered in panel

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#61393]
### Description

This might have been an intended design change, but my basic design instincts are telling me not given the way all other content in the sidebar is aligned top.

### Step-by-step reproduction instructions

1. Insert a block that only supports a few limited inner blocks (e.g. list, button)
2. Try inserting inner blocks with that parent using the main sidebar
3. Observe that the inserter items are vertically centered

### Screenshots, screen recording, code snippet

![Screenshot 2024-05-06 at 3 55 17 pm](https://github.com/WordPress/gutenberg/assets/677833/0af13fd2-80df-4fc4-b24f-6162acfd9ce8)

### Environment info

- Mac OS / Brave
- Latest Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jeryj** [comment]
Can you rebuild and see if it was fixed by https://github.com/WordPress/gutenberg/pull/61296? 

Here is what I see on trunk now:
<img width="463" alt="Inserter with list block selected and blocks stacked at top of inserter" src="https://github.com/WordPress/gutenberg/assets/967608/c3a53c46-cf2f-4643-bac1-e183b9cb19b4">

**Comment by talldan** [comment]
@jeryj Yep, it seems resolved now 👍
