### ISSUE TITLE
Drag and drop stuck mid-drag

### ISSUE THREAD

**Issue by braders** [WordPress/gutenberg#6145]
## Issue Overview

I attempted to re-order my blocks with the recent drag and drop feature. However, mid-drag the drag was "released". The system still thinks it is mid-drag (body has the is-draggable-components-draggable class), but the dragged component is no longer moving with my cursor. I am still able to interact with the blocks that I was not dragging, and with the adminbar/ navigation etc.

However, moving my mouse and/ or clicking does not move the dragged block back into position - it is stuck over the rest of the content.

![image](https://user-images.githubusercontent.com/1931323/38682000-f7a0e480-3e61-11e8-9a55-159319138c00.png)

Attempting to drag another block seems to "pick-up" both blocks, but the block that got stuck is never insterted back into its correct flow:

![2018-04-12_15h02_18](https://user-images.githubusercontent.com/1931323/38682248-82061cd0-3e62-11e8-9f4a-5b8a91c4bb9e.png)

(Notice the original list that has got stuck behind the paragraph that I am moving)

## Steps to Reproduce (for bugs)

I am not able to reliably reproduce this, but the issue occured at the same time that I received a browser notification (gmail). I suspect that the window focus was briefly transfered to the OS or Browser notification widget.

Firefox Developer Edition, Windows 10.

**Comment by karmatosed** [comment]
Unfortunately I was unable to replicate this. Is there anything else you can think of to provide as information to help us recreate?

**Comment by braders** [comment]
I have again been able to replicate this issue by triggering a Gmail browser notification whilst moving the blocks in Firefox developer edition (Firefox 60).

I would assume any notification would cause this issue (https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API)

**Comment by kpu23** [comment]
I've ran into this same problem multiple times but unfortunately I cannot reliably reproduce it.

**Comment by iseulde** [comment]
I can reproduce this as well, see #7081.

**Comment by nosolosw** [comment]
I've been testing this. I can only repro _sometimes_, and it seems to happen more often when I drop content before/after an embed block, or drag/drop the embed block itself. Couldn't repro with notifications (tried with google calendar ones, but I assume any other will do). When I can repro, the `dragend` event isn't fired.

Two potential paths to fix this are: 1) use a different "end" event (I'm testing with [`drop`](https://developer.mozilla.org/en-US/docs/Web/Events/drop) instead of `dragend` which seems to be more reliable) and 2) find out why `dragend` isn't always fired. I'll work on fixing this.

**Comment by nosolosw** [comment]
I think I've found the root cause: it's a [confirmed chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=737691#c8). The `dragend` event is not fired (sometimes) when an iframe is involved in a DOM operation - for example, the iframe is added/moved/removed, is made visible/hidden, etc. I couldn't reproduce in other browsers.

I have some ideas that may fix this besides what I mentioned in the above comment. @braders @kpu23 @iseulde Could I ask you to confirm that this happens to you only in chrome? That would be helpful in fixing the bug. These are the instructions that worked for me to reproduce it:

- create a post that contains some embed block like YouTube video (embeds use iframes).
- drag the embed block to a different position. If it works the first time, try again. The second one never works for me.

**Comment by nosolosw** [comment]
FWIW, Gecko/Firefox doesn't fire `dragevent` [either](https://bugzilla.mozilla.org/show_bug.cgi?id=460801) if the node being dragged is moved/removed during the drag operation. This shouldn't be an issue for us because of how we work with nodes, and I couldn't reproduce in Firefox. Thought it'd be worth mentioning nevertheless.

**Comment by kpu23** [comment]
Hi @nosolosw,

I've tested every browser I have. Here are the results.

**Chrome v68.0.3440.106**

The same issue occurs.

**FireFox v61.0.2** 

This bug does not happen for me in FireFox but there is something worth reporting. Following the same scenario I outlined above, the Twitter embed block lost its "structure" after moving the 2nd header block.

Before:
![image](https://user-images.githubusercontent.com/2415516/44912333-d11c6a00-acf7-11e8-9092-9bdde71074aa.png)

After:
![image](https://user-images.githubusercontent.com/2415516/44912240-88fd4780-acf7-11e8-84ac-2419f11c5acc.png)

**Internet Explorer v11.something**
Dragging doesn't work. Please don't waste time looking into this one though 😉

**Comment by nosolosw** [comment]
Potential fix at https://github.com/WordPress/gutenberg/pull/9511

**Comment by nosolosw** [comment]
@kpu23 note that the embed behavior you mention also happens when using the up/down mover so it's unrelated to this and may merit its own separate issue.

**Comment by kpu23** [comment]
Agreed. It is definitely not a part of this issue/ticket. Shall I create a new ticket for it? (Of course I'd check to make sure a ticket doesn't already exist first).

I appreciate all of your work for Gutenberg!

**Comment by nosolosw** [comment]
https://github.com/WordPress/gutenberg/pull/9511 fixes this and will be out on the 3.9 version.
