### ISSUE TITLE
Color variation: ensure editing color palette is reflected in the UI and changes aren't immediately reverted when clicking the same preset

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#61462]
While testing out [the early color and typography variations work](https://github.com/WordPress/gutenberg/issues/61215), I noticed that when editing the preset that the color changes aren't reflected in the preset and, if I click on the same one I'm editing, it overwrites the changes I just made without warning:

https://github.com/WordPress/gutenberg/assets/26996883/8d2add5a-ed06-467c-901f-74ee87d29c5d

I'd expect the changes to show up in the UI to the color preset _and_ that clicking the same preset wouldn't just overwrite without a warning. This ties into similar concerns with style variations overwriting changes made.

**Comment by richtabor** [comment]
I do think this flow is much clearer as implemented in https://github.com/WordPress/gutenberg/issues/61213 where the color palettes are in the same view, rather than within a sub-view. If you pull the lastest you should see that flow. 

When you choose an alternate color palette, it becomes your palette — which may be edited/manipulated. I don't think we need to warn people that colors are changing, when you change colors.

**Comment by annezazu** [comment]
Huzzah! I just went through that new flow and I agree. This is much clearer. Going to close this out. For clarity, here's what it looks like for others following:

https://github.com/WordPress/gutenberg/assets/26996883/badd4883-b8b9-44c6-af3e-0ccb636559f6

Thanks for connecting the dots there.
