### ISSUE TITLE
Try using synced color on the block icon for overrides

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#61515]
Instead of using the "connected" icon to indicate a synced pattern, in place of the block icon, let's try using the synced color applied to the block icon instead. Maintaining the block icon is helpful for understanding block selection when using list view or content only view. And this reduces adding a new icon/concept to comprehend. 

Iteration: #59819

### Visual
![CleanShot 2024-05-09 at 14 54 09](https://github.com/WordPress/gutenberg/assets/1813435/86ecf577-ffe1-48f2-9106-e6563c76ebb0)

![CleanShot 2024-05-09 at 16 02 47](https://github.com/WordPress/gutenberg/assets/7753001/20e62fd9-965f-4c5b-b60d-a7d0287937bd)

**Comment by annezazu** [comment]
I like this conceptually and am keen to try it out. My biggest question mark is around how we are creating a new mental model when you think about block connections. In this case, folks will see the connected icon and the block icon in different parts of the editing experience rather than just one unified option (connected icon). I also worry a bit that we're conflating mental models in that typically when items are purple, like a synced pattern or template part, that's because we're (trying) to communicate that it will be updated everywhere. In this case, we're saying the opposite: this block can be edited because of overrides and will be custom just to this instance of the pattern.

**Comment by annezazu** [comment]
Found this a11y issue related to the connections icon. Let's avoid the same problem: https://github.com/WordPress/gutenberg/issues/60810

**Comment by richtabor** [comment]
For reference, here's the current: ![CleanShot 2024-05-31 at 10 30 52](https://github.com/WordPress/gutenberg/assets/1813435/03eab86e-4dc8-48de-888b-5e43013ac4e5)
