### ISSUE TITLE
Image block: 'Insert link' is broken

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#6158]
## Issue Overview
The _Insert link_ functionality in an image block's toolbar is broken.

## Steps to Reproduce (for bugs)
1. Insert an image block
2. Click the _Insert link_ button in the toolbar
3. Type in the title of a published post

## Expected Behavior
A list of posts appear which can be selected with the arrow keys.

## Current Behavior
The toolbar disappears. 

## Possible Solution
Probably need to put an `event.stopPropagation()` into the `UrlInput` `onKeyPress` event. 

## Screenshots / Video
<img width="439" alt="screen shot 2018-04-12 at 11 01 05" src="https://user-images.githubusercontent.com/1204802/38670681-c2b82034-3e49-11e8-9214-136180edd158.png">

## Related Issues and/or PRs
It looks like https://github.com/WordPress/gutenberg/pull/5513 introduced this regression.

**Comment by JeroenSormani** [comment]
Can confirm its broken on version 2.6.0

Trying to type anything into the field doesn't work:
![screen recording 2018-04-15 at 12 42 pm](https://user-images.githubusercontent.com/5774447/38777578-9dd0f94a-40aa-11e8-92e7-024f739289e3.gif)

Navigating left/right or trying to remove something with backspace doesn't work as expected either:
![screen recording 2018-04-15 at 12 43 pm](https://user-images.githubusercontent.com/5774447/38777583-ae87e5aa-40aa-11e8-99bc-c724e9ed320b.gif)

Expected behaviour here would be to be able to move the cursor left/right to be able to edit a link.
Current behaviour it navigates the link options, even on input field focus

**Comment by youknowriad** [comment]
This has been fixed in 2.7
