### ISSUE TITLE
Developer documentation: wrong source is used as a reference

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/gutenberg#61657]
I recommend that the developer documentation relate to the current version of WordPress Core. As it stands, the current version relates to the Gutenberg plugin, which is not always in use. (Confirmed by @t-hamano in @WordPress/outreach.)

## What problem does this address?
Some of the documentation—e.g. https://developer.wordpress.org/block-editor/reference-guides/slotfills/plugin-document-setting-panel/—is for the code in the Gutenberg plugin, not in WordPress Core.

## What is your proposed solution?
The documentation should refer to the current version of core, not of the plugin.

**Comment by fabiankaegy** [comment]
It would be great to have the documentation versioned similar to how https://docusaurus.io for example does it. Where you have the latest stable core version but are then also able to see any changes in the alpha channel (in this case that would be the Gutenberg Plugin)

**Comment by Mamaduka** [comment]
Related #61651.

**Comment by juanmaguitar** [comment]
For reference, there's a current effort (see #61036) to integrate JavaScript functions into the [Functions Reference](https://developer.wordpress.org/reference/) system so they can be navigated and consulted just like PHP functions.

This implementation would enable some improvements for JS functions docs, like providing `@since` info from JSDocs comments for each JS function or allowing comments from users (in the same way docs for PHP functions do)

**Comment by youknowriad** [comment]
Can we close this issue and open one in http://meta.trac.wordpress.org/ 

The solution is just to follow what Core does for the Function reference... Use the "wp/6.5" branch instead of "trunk" when building the handbook.

The downside is that small typos and things like that won't be "live" until wp 6.6 is released but we can probably accept that, it's similar for the php functions anyway.

**Comment by markhowellsmead** [comment]
Migrated to https://meta.trac.wordpress.org/ticket/7642

**Comment by youknowriad** [comment]
Thanks :)
