### ISSUE TITLE
Media & text block: Placeholder buttons has the wrong size

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#61812]
### Description

When you place a media & text block, before selecting a media, there is a placeholder with three buttons.
With Gutenberg active, there is an unexpected change in the styling of the buttons, which are wider than in other placeholders.

### Step-by-step reproduction instructions

Activate Gutenberg.
Add a media & text block.

### Screenshots, screen recording, code snippet

With Gutenberg active:
<img width="640" alt="Media & text block in Gutenberg has full width buttons" src="https://github.com/WordPress/gutenberg/assets/7422055/1345b0e3-f216-4ae6-945c-f855a4fde78b">

Expected:
<img width="640" alt="Media & text block in WP version 6.5 has standard width buttons" src="https://github.com/WordPress/gutenberg/assets/7422055/a6a41032-e0d0-4246-a463-735f5594c8ad">

Image block placeholder for comparison:
<img width="640" alt="Image block placeholder with standard width buttons" src="https://github.com/WordPress/gutenberg/assets/7422055/124c2482-8eb7-4acc-8998-f601ab7b7606">

Cover block for comparison:
<img width="674" alt="cover block placeholder with standard width buttons" src="https://github.com/WordPress/gutenberg/assets/7422055/a0211dbc-b172-4425-b51d-3231128fe75c">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by philjo107** [comment]
Hey I'm new at this, which files am I supposed to make changes to?

**Comment by t-hamano** [comment]
I believe this is related to #59275 and is the intended change. If the placeholder itself is narrow, the buttons will be stacked vertically.

So if you change the Media & Text block to wide or full width and the placeholder size increases, the buttons will line up horizontally.

![image](https://github.com/WordPress/gutenberg/assets/54422211/a4ace168-074f-4cb2-9f4e-32fb52b73994)

On the other hand, if you change to the mobile viewport in other blocks, the buttons should be stacked vertically.

![image](https://github.com/WordPress/gutenberg/assets/54422211/408a2297-2133-45c3-9643-839e7e8fa724)

**Comment by hbhalodia** [comment]
Hi @carolinan, I am not sure if this is related to exactly media and text, because we have used the common media placeholder for all this to render as a placeholder. I do had checked the code and found that the button size depends on the width of the container on which these buttons are being show. Here is the reference,

https://github.com/WordPress/gutenberg/blob/7674a57870ec3e512c3d0d0edb42fe24ecc53cea/packages/components/src/placeholder/index.tsx#L64-L67

Based on this, since the media and text block tends to use the once side media and another side text, the placeholder container width falls in medium and small range, we can see that it is made to add it `100%` of width,

https://github.com/WordPress/gutenberg/blob/7674a57870ec3e512c3d0d0edb42fe24ecc53cea/packages/components/src/placeholder/style.scss#L109-L125 

In this case, let us say that, if the `image/cover` block is being used inside the columns, then these buttons in the placeholders would be of `100%` width you can check the difference in the below screenshots,

| If inside columns | If outside columns |
| :-------------: | :-------------: |
| <img width="1426" alt="Screenshot 2024-05-21 at 4 00 02 PM" src="https://github.com/WordPress/gutenberg/assets/58802366/1eb3a49f-aee9-494e-8b1e-1366fcc1b44c"> | <img width="1426" alt="Screenshot 2024-05-21 at 4 00 24 PM" src="https://github.com/WordPress/gutenberg/assets/58802366/7d87e716-d99f-44e7-8a44-7295d89fca34"> |

So I am not sure, if the issue should be valid for this case.

Thank You.

**Comment by hbhalodia** [comment]
> I believe this is related to #59275 and is the intended change. If the placeholder itself is narrow, the buttons will be stacked vertically.
> 
> So if you change the Media & Text block to wide or full width and the placeholder size increases, the buttons will line up horizontally.
> 
> ![image](https://private-user-images.githubusercontent.com/54422211/332390156-a4ace168-074f-4cb2-9f4e-32fb52b73994.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODc3NTEsIm5iZiI6MTcxNjI4NzQ1MSwicGF0aCI6Ii81NDQyMjIxMS8zMzIzOTAxNTYtYTRhY2UxNjgtMDc0Zi00Y2IyLTlmNGUtMzJmYjUyYjczOTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDEwMzA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1ZTMyMWU5ODU1NjdmZmRjZWYyNWYzNDEzOWJjYmJjYTU4OWI4NDE3NzM1MjJiYWNhOTUwZjRmODI4YjcwMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uvf8YDZYG4dcHx9uFWPrpu-HJksbNLLsQiGIn9Asdws)
> 
> On the other hand, if you change to the mobile viewport in other blocks, the buttons should be stacked vertically.
> 
> ![image](https://private-user-images.githubusercontent.com/54422211/332390477-408a2297-2133-45c3-9643-839e7e8fa724.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODc3NTEsIm5iZiI6MTcxNjI4NzQ1MSwicGF0aCI6Ii81NDQyMjIxMS8zMzIzOTA0NzctNDA4YTIyOTctMjEzMy00NWMzLTk2NDMtODM5ZTdlOGZhNzI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDEwMzA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNDgzZDE5YmYwNDg1MWZiNGQ5ZWM5ODg2Zjc1Y2NjMmQzY2U2OTRiZjIzODVhZWYyMjJhNjk2NTIyZmUwMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mnS5MKhXcS3eK4PY2Dlde8Nkj6NJtB_W26PgKkEzVyk)

Sorry @t-hamano, I guess I was adding the reply for this issue with the pointers you mentioned and did not check that you already replied for it. I need to just hit the comment button 😄.

**Comment by carolinan** [comment]
I think it looks bad, but let's close this then.
