### ISSUE TITLE
Block settings: Change "Apply globally" to secondary button styling to lower prominence 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#61834]
While testing overrides in synced patterns, I noticed that the prominence of "apply globally" really stands out even more when we have now the option to enable/disable overrides: 

![Screenshot 2024-05-21 at 12 33 12 PM](https://github.com/WordPress/gutenberg/assets/26996883/fb9cd520-b7e4-4076-94ed-7df5d0b6fcee)

To create more of a balance here, I propose we change the "apply globally" option to be a secondary button styling rather than primary like so:

![Screenshot 2024-05-21 at 12 33 50 PM](https://github.com/WordPress/gutenberg/assets/26996883/0546a928-bbec-41d3-94aa-ebf75fe5caf7)

If anything, I see creating overrides as being more of a common action than taking an individual styling and applying it globally but, at the least, we should have equal weighting here in my opinion. cc @WordPress/gutenberg-design for thoughts!

**Comment by jasmussen** [comment]
Yep, let's get a dev on this. Do we already have a confirm "are you sure" dialog when applying this? I don't personally think one is necessary, but it's a second step we can take if this in effect is a destructive action.

**Comment by t-hamano** [comment]
> Do we already have a confirm "are you sure" dialog when applying this?

There are currently no modal dialog. Should we add a dialog as suggested in #57740?

**Comment by jasmussen** [comment]
I'd love to probably follow up with a "don't show again" to such a dialog. That would be the only thing.

**Comment by amitraj2203** [comment]
> To create more of a balance here, I propose we change the "apply globally" option to be a secondary button styling rather than primary like so:

I have raised a [PR](https://github.com/WordPress/gutenberg/pull/61850) for changing the `Apply globally` button variant to secondary.

**Comment by amitraj2203** [comment]
> To create more of a balance here, I propose we change the "apply globally" option to be a secondary button styling rather than primary like so:

I noticed that the `Apply globally` button height is less than the `Enable overrides` button, probably because the props `__next40pxDefaultSize` is not passed to it. Let me know if that needs to be added for style consistency. 🙇

**Comment by jasmussen** [comment]
That would be good, while you're there.

**Comment by t-hamano** [comment]
In my experience, secondary buttons are used in either of the following contexts:

Are side actions: Examples of the Query Loop block and the Image block

![image](https://github.com/WordPress/gutenberg/assets/54422211/8c973302-7dad-468e-b7ae-1e4a86272bc8)

When opening a dialog: Example of the Font Library Modal button and the Patterns Modal button

![image](https://github.com/WordPress/gutenberg/assets/54422211/7a7ded0d-88b6-445b-8c05-12c1f26e3260)

![image](https://github.com/WordPress/gutenberg/assets/54422211/0c6a7f48-7cdb-4b16-8761-a661dd24dc0a)

When I think about it this way, I feel like the current style is fine. Or should we change the "Enable/Disable override" button to the primary button as well?

![image](https://github.com/WordPress/gutenberg/assets/54422211/1a493efe-9b0e-411f-89ca-fd7c03bd84e3)

In any case, I think the height of the buttons should be the same.

**Comment by hbhalodia** [comment]
> In my experience, secondary buttons are used in either of the following contexts:
> 
> Are side actions: Examples of the Query Loop block and the Image block
> 
> ![image](https://private-user-images.githubusercontent.com/54422211/332756624-8c973302-7dad-468e-b7ae-1e4a86272bc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzQyMjEsIm5iZiI6MTcxNjM3MzkyMSwicGF0aCI6Ii81NDQyMjIxMS8zMzI3NTY2MjQtOGM5NzMzMDItN2RhZC00NjhlLWI3YWUtMWU0YTg2MjcyYmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDEwMzIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2YWRjOWMwNjM1ZGIxMDg3MjQzODk3NDRmNjhkOTRkNDJhOWI1NGVmY2E1ZjRlNzMyMTViMzk1Zjk5NDAxN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dzh63k4Tgv6RuEe-1ibxwyf3Se-Z3iiKPNQKl7P48w4)
> 
> When opening a dialog: Example of the Font Library Modal button and the Patterns Modal button
> 
> ![image](https://private-user-images.githubusercontent.com/54422211/332756890-7a7ded0d-88b6-445b-8c05-12c1f26e3260.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzQyMjEsIm5iZiI6MTcxNjM3MzkyMSwicGF0aCI6Ii81NDQyMjIxMS8zMzI3NTY4OTAtN2E3ZGVkMGQtODhiNi00NDViLThjMDUtMTJjMWYyNmUzMjYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDEwMzIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwNDJhODEyZjNmNzk2OWU0Yjk4NDBkMjZiNDg0ODNlMDg4ZWY3MjgzNGI3ZmU5ZDFmNjc2OWY0YTU3ZDlhYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kdcB_Os2A2EWT3FND5UDi7CSdFPxLmJT8DMmDHTTObM)
> 
> ![image](https://private-user-images.githubusercontent.com/54422211/332757065-0c6a7f48-7cdb-4b16-8761-a661dd24dc0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzQyMjEsIm5iZiI6MTcxNjM3MzkyMSwicGF0aCI6Ii81NDQyMjIxMS8zMzI3NTcwNjUtMGM2YTdmNDgtN2NkYi00YjE2LTg3NjEtYTY2MWRkMjRkYzBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDEwMzIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4MTljZjAyNzJhMWQ4YzU4MjAwMzVhNGQ3ZTM2ZDcwODk5NDU0YWUyZDMzY2I5YTFjZTdjMzc5NmM5N2NhY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ciuE1WKPrXfmsrJuvX7cxBjGqmqTlXAAZy5ejOtksH4)
> 
> When I think about it this way, I feel like the current style is fine. Or should we change the "Enable/Disable override" button to the primary button as well?
> 
> ![image](https://private-user-images.githubusercontent.com/54422211/332757719-1a493efe-9b0e-411f-89ca-fd7c03bd84e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzQyMjEsIm5iZiI6MTcxNjM3MzkyMSwicGF0aCI6Ii81NDQyMjIxMS8zMzI3NTc3MTktMWE0OTNlZmUtOWIwZS00MTFmLTg5Y2EtZmQ3YzAzYmQ4NGUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDEwMzIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzNTUwOTQ5ZWQ0ZGE2YmQ3Nzc4ZTUyN2ZmZDM2ODQ0NjkzNWQ1OTBiYTJjZmVlYTM5YmM3NjdhZjdkYTNiYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TGHNGwS99NArMnrNt8ZpFD-tdcuWWwCwcsl9xd3dRKM)
> 
> In any case, I think the height of the buttons should be the same.

I agree with the @t-hamano, Secondary button styles are used when we need to do some side actions rather that what is "primary". So instead of making `Apply Globally` as secondary, One should make the `Disable Overrides` as the primary button. This could be the way better.

Further as an example, If we can select any block and check the `Advanced` tab you can see that `Apply Globally` is a primary button, so instead of changing this to the `Secondary`, We should make the change to `Disable Overrides` and make it primary. 

Also, If we made this change, `Apply Globally` button would get changed everywhere, since we are concerning only with patterns here, we should add a fix that would reflect at fewer places instead of multiple places.

Thank You ✨.

**Comment by amitraj2203** [comment]
Hi @t-hamano,

I agree with you, and I also have a suggestion regarding the button hierarchy for better clarity.

What if we make the `Enable overrides` button the primary button. The reasons for this are:

- This action affects multiple instances of a pattern, indicating a broader and more critical impact.
- It is likely to be a key feature that users will interact with frequently to enable global changes across instances.

~On the other hand, I suggest keeping the `Apply globally` button as secondary. This is because:~

- ~Although important, this action is more specific in scope compared to enabling changes across multiple instances.~
- ~Styling consistency across Paragraph blocks, while significant, might not be as foundational as the ability to change multiple instances of a pattern.~

Additionally, I see that the `Apply globally` button would have more impact at multiple places. Each and every block has an advanced tab and it has this button. So changing this would change all those occurrences, although currently since we are dealing with patterns, I do not think that `Apply globally` would be touched on because of the mentioned reason. Although I know that there would be no breaking changes, but still users may have some impact in a view if we change that.

> Or should we change the "Enable/Disable override" button to the primary button as well?

I believe it would not be ideal to keep both buttons as primary. Having two primary buttons can dilute the focus and importance of each action, potentially confusing users about which action is more critical in the given context.

> In any case, I think the height of the buttons should be the same.

For making both the buttons have consistent height, we can also remove the `__next40pxDefaultSize` from `Enable overrides` button to make it more consistent.

Let me know your thoughts on this approach.

**Comment by jasmussen** [comment]
My rule of thumb here is to apply these styles very judiciously according to context and prominence. In some cases, they need a fill or a border in order to distinguish themselves from the context, in others they need a box to make the grid align, and in still others it's useful to have a visual hierarchy. 

That's also to say, that I don't know that we can formulate a hard guideline for when to use this or that. Honestly I wish we had called the buttons something other than _primary, secondary, tertiary_, because those names suggest a hierarchy where none need to exist. Insofar as: these are not like headings, where you must only ever use an h3 if there's an h2 above it.

For this particular context, full-width buttons in the inspector, primary and secondary are both shapes that work well. However I would go with the outline/secondary style here, specifically to manage prominence. In this case, the hierarchy of the button names match that of their action: these actions are not primary.

**Comment by t-hamano** [comment]
Thank you everyone for your opinions.

I want to be clear here that the "Enable/Disable overrides" and "Apply globally" buttons are not always both visible.

Each button should be visible under the following conditions:

- "Enable/Disable overrides" button: when editing a synced pattern
- "Apply globally" button: if you are in the site editor

In other words, there are three layouts: With all this in mind, should we change both buttons to the secondary style?

| Blocks in the site editor　| When editing a synced pattern in the post editor | When editing a synced pattern in the site editor |
|--------|--------|--------|
| ![image](https://github.com/WordPress/gutenberg/assets/54422211/a9f30325-7fe9-4cca-b902-2f12664c231d) |  ![image](https://github.com/WordPress/gutenberg/assets/54422211/389f34f2-d91b-4de4-9968-568483b3076e)|  ![image](https://github.com/WordPress/gutenberg/assets/54422211/ca5e77f0-6099-47f0-b314-a003c2520c8b)|

**Comment by amitraj2203** [comment]
Hi folks, this is the [PR](https://github.com/WordPress/gutenberg/pull/61850) that is approved for this issue. But looking at the last comment, are there any changes required from my side?

**Comment by jasmussen** [comment]
> In other words, there are three layouts: With all this in mind, should we change both buttons to the secondary style?

Yes, I'd think we'd want to use the secondary style for all instances of these buttons, both enable overrides and apply globally, if they aren't already. Amit if you can check both the post editor and site editors, according to Aki's instructions, that would be useful, thank you.

**Comment by amitraj2203** [comment]
> Amit if you can check both the post editor and site editors, according to Aki's instructions, that would be useful, thank you.

I have verified that the [PR](https://github.com/WordPress/gutenberg/pull/61850) I created is correctly applying the secondary style to both the `Enable overrides` and `Apply globally` buttons. I have checked this in all three scenarios:

Blocks in the site editor | When editing a synced pattern in the post editor | When editing a synced pattern in the site editor
-- | -- | --
<img width="280" alt="image" src="https://github.com/WordPress/gutenberg/assets/77401999/d99c9511-c122-474c-972d-599599653025"> | <img width="281" alt="image" src="https://github.com/WordPress/gutenberg/assets/77401999/bbe485ad-8f5a-4dbe-b1b4-765e0298fd19"> | <img width="278" alt="image" src="https://github.com/WordPress/gutenberg/assets/77401999/cdaef226-ac1e-4e61-8922-9fcd6c768660">
