### ISSUE TITLE
Shadow Panel: slugs may conflict

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#61989]
### Description

The shadow slug uses the current number of shadows plus 1 as a suffix.

https://github.com/WordPress/gutenberg/blob/278810c1b987a6926fc41248f567d8bfa4230b70/packages/edit-site/src/components/global-styles/shadows-panel.js#L87

But with this logic, slugs can be duplicates.

I think we need to find the maximum value from all the shadow suffixes and add 1 to that value, [like in the `PaletteEdit` component](https://github.com/WordPress/gutenberg/blob/278810c1b987a6926fc41248f567d8bfa4230b70/packages/components/src/palette-edit/index.tsx#L92-L103).

### Step-by-step reproduction instructions

- Add three custom shadows. The labels are "Shadow 1", "Shadow 2", and "Shadow3" respectively.
- Delete "Shadow 2".
- Add shadow.
- A shadow labeled "Shadow 3" is added. This will cause a browser warning error because the slug matches the existing "Shadow 3".
- Also, editing one will affect the other.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/9517b4c7-7a4f-4afe-956a-840ec87ee0b9

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by amitraj2203** [comment]
Hi @t-hamano, I tried to replicate this issue and was able to do it. After applying the suggestion you mentioned, unique slugs are getting generated. Please take a look at this [PR](https://github.com/WordPress/gutenberg/pull/61997) at your convenience.

**Comment by vk17-starlord** [comment]
@t-hamano @amitraj2203 main purpose of this issue is to generate a unique slug , we can simply create a state called as counter / currentIndex which will keep incrementing on every addition of shadow , even if we delete it and next time add the new shadow it will have new index / counter value not the old one . e.g. you add shadow-1 , shadow-2 , shadow-3 the counter will be at 3 , when we delete a shadow and add a new shadow we will have shadow-4 as we will increment and add every time . 

@amitraj2203 - Regex logic can be bit complicated you can try this approach of counter .

**Comment by t-hamano** [comment]
@vk17-starlord Thanks for the suggestion.

> we can simply create a state called as counter / currentIndex which will keep incrementing on every addition of shadow

With this approach, wouldn't the counter have to be kept permanently in a database or something? I think we should avoid keeping data permanently just for the counter.
