### ISSUE TITLE
Unified publish flow: return revisions to more prominence 

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#62041]
In testing 6.6, I noticed that revisions is now a bit more hidden and doesn't include the number of revisions available after this PR was merged: https://github.com/WordPress/gutenberg/pull/61867

**Before:**

https://github.com/WordPress/gutenberg/assets/26996883/d22a1a4d-620f-45f7-835c-bbe6d6771d2e

**After:**

https://github.com/WordPress/gutenberg/assets/26996883/90336b83-1a34-41bc-97f2-45cbe531795b

In talking with enterprise folks, I imagine this might cause some panic and confusion. Revisions are a key part of the foundational experience of what WordPress offers and, when many folks are working on a piece, having easy access is important. Opening this issue partially to see if feedback comes up within the 6.6 cycle and to raise an initial flag.

**Comment by ntsekouras** [comment]
Thanks for raising this Anne! I just wanted to mention that the revisions number is going to be part of the label [here](https://github.com/WordPress/gutenberg/pull/61942). We're having some discussion about the API, but it will be fixed for 6.6.

--edit

The [PR](https://github.com/WordPress/gutenberg/pull/61942) that adds the revisions count was merged.

**Comment by annezazu** [comment]
Oh amazing! I think that'll be important to have.

**Comment by aaronjorbin** [comment]
I don't know if displaying the number of revisions is nearly as important as the findability of revisions from within the editor.

I also don't know if dataviews is enough of a place for the revisions since 1) It's currently limited to pages out of the box 2) it's not the default experience for navigating into the post editor. 

Before #61867, to know if a post has any revisions, you just needed to have the document inspector open. Now you need to click. So that process goes from zero clicks to one. If the goal is to reduce the prominence, putting it inline with the last edited timestamp might be worth exploring.

<img width="273" alt="Screenshot 2024-05-31 at 3 07 32 PM" src="https://github.com/WordPress/gutenberg/assets/622599/1d55bfa9-c3af-4469-aa04-01b101ca1762">

**Comment by ppolo99** [comment]
> Before #61867, to know if a post has any revisions, you just needed to have the document inspector open. Now you need to click. So that process goes from zero clicks to one. If the goal is to reduce the prominence, putting it inline with the last edited timestamp might be worth exploring.

I fully agree with this. Revisions are a key part of editorial teams as Anne mentions, and hiding them behind a menu doesn't make sense to me. I like the idea of having a timestamp or even a revisions icon in place of the text (Google Docs).

**Comment by smithjw1** [comment]
The original [issue](https://github.com/WordPress/gutenberg/pull/61867) says:

> Revisions are now accessible from the ellipsis menu which offers more appropriate prominence.

But I don't see any data or reasoning to support the second half of that statement. Do we know how often Revisions are accessed across sites? Does that vary by the average number of revisions on a post? How are we determining appropriate prominence?

With a shared understanding, we can have a more inclusive conversation about the proposed change vs. the original vs. @aaronjorbin's [suggestion](https://github.com/WordPress/gutenberg/issues/62041#issuecomment-2142117201) that strikes a middle ground.

**Comment by hrkhal** [comment]
What is the onus for moving the revisions out of sight? As @annezazu has already noted this isn't a good move for enterprise users. Information like this should remain visible for the editors at a glance.

6.5 already brought in post url truncation in the editor, which again limits the information available for editors and users without interaction. 

It now requires another click to see the full url for the post, if you add in the two clicks to see if there are any revisions and that's 3 extra clicks per editor per article per day. It adds up quick in an enterprise setting.

**Comment by annezazu** [comment]
Thanks, folks, for sharing broader context and thoughts to round out my initial instincts on the enterprise side. A PR is in progress to explore [making revisions more prominent again](https://github.com/WordPress/gutenberg/pull/62323). You can use [this Playground link](https://playground.wordpress.net/#%7B%22landingPage%22:%22/wp-admin/%22,%22steps%22:%5B%7B%22step%22:%22login%22,%22username%22:%22admin%22,%22password%22:%22password%22%7D,%7B%22step%22:%22mkdir%22,%22path%22:%22/wordpress/pr%22%7D,%7B%22step%22:%22writeFile%22,%22path%22:%22/wordpress/pr/pr.zip%22,%22data%22:%7B%22resource%22:%22url%22,%22url%22:%22/plugin-proxy.php?org=WordPress&repo=gutenberg&workflow=Build%2520Gutenberg%2520Plugin%2520Zip&artifact=gutenberg-plugin&pr=62323%22,%22caption%22:%22Downloading%20Gutenberg%20PR%2062323%22%7D,%22progress%22:%7B%22weight%22:2,%22caption%22:%22Applying%20Gutenberg%20PR%2062323%22%7D%7D,%7B%22step%22:%22unzip%22,%22zipPath%22:%22/wordpress/pr/pr.zip%22,%22extractToPath%22:%22/wordpress/pr%22%7D,%7B%22step%22:%22installPlugin%22,%22pluginZipFile%22:%7B%22resource%22:%22vfs%22,%22path%22:%22/wordpress/pr/gutenberg.zip%22%7D%7D%5D%7D) to test it.

**Comment by annezazu** [comment]
Thanks, Nik, for working on this and thank you everyone else for chiming in with feedback! Final state is a returned section in the sidebar like so:

![Screenshot 2024-06-09 at 10 53 08 PM](https://github.com/WordPress/gutenberg/assets/26996883/cf6f94eb-ec64-4d75-8519-4ea27e0aa82f)

**Comment by afercia** [comment]
> The original https://github.com/WordPress/gutenberg/pull/61867 says:

> > Revisions are now accessible from the ellipsis menu which offers more appropriate prominence.

> But I don't see any data or reasoning to support the second half of that statement.

Late to the party but I'd totally agree with @smithjw1 that recent design changes in the editor have been pretty arguable. Rather than intuition or 'vision', design in a widely used software like WordPress should be based on research, data, _and user testing_. My point is more about process rather than _personal views on design_. Direct user feedback collected by @annezazu proves that users struggle with many changes the design team introduced recently. I'm not sure keeping this approach that completely ignores user testing can be sustainable and lead to any good user experience.

It's a broader discussion that I think should be made at a higher level. I'm not sure that continuous, _totally untested_ changes to the UI are any good for this project. There's a huge cost in terms of development time, resources allocated and, more importantly, cost in terms of user experiences as users have to adapt to continuous changes of the editor UI. Reverts like this one, https://github.com/WordPress/gutenberg/pull/65087, and [the proposed revert for the Sticky setting](https://github.com/WordPress/gutenberg/issues/63386) prove that the process is less than ideal. I do realize a closed issue isn't the best place for such a discussion but I do think the design process in WordPress and the editor would greatly benefit from a radical shift towards a data-driven approach.
