### ISSUE TITLE
New block created with @wordpress/scripts@28 don't show up on wordpress

### ISSUE THREAD

**Issue by originaliko** [WordPress/gutenberg#62202]
### Description

I tried to create a new plugin / block with create-block and the block is not available in the back-end. There's no build error, php error or javascript error.

### Step-by-step reproduction instructions

1 : Create a new wordpress plugin "npx @wordpress/create-block test-plugin"
2: cd test-plugin
3 : npm start
3 : activate plugin test-plugin 
4 : edit a new page in wp-admin
5 : try to add the new block "/test-plugin"
6: nothing append 
---------
step to correct 
- edit package.json set devedepencies "@wordpress/scripts" to "^27.9.0" 
- npm install
- npm start
- refresh and edit a page
- add the new block "/test-plugin"

### Environment info

Wordpress 6.53.
@wordpress/scripts": "^28.0.0"
node  22.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by balazske96** [comment]
+1

However if you put the block inside a template html file with it's block name it appears on the front end.

**Comment by t-hamano** [comment]
Thanks for the report. I was able to reproduce this issue.

I built the block with scripts version 27 and 28 and found a difference in the contents of `index.asset.php`. `react` has been replaced with `react-jsx-runtime`.

version 27.9:

```php
<?php return array('dependencies' => array('react', 'wp-block-editor', 'wp-blocks', 'wp-i18n'), 'version' => 'd97fdb9bbdb79e4913a4');
```

version 28.0:

```php
<?php return array('dependencies' => array('react-jsx-runtime', 'wp-block-editor', 'wp-blocks', 'wp-i18n'), 'version' => 'b0e4f78143cfbd1f56d2');
```

If I manually change this to `react`, the block can be inserted into the editor, but a critical error occurs.

![image](https://github.com/WordPress/gutenberg/assets/54422211/85b027be-abb1-4ff7-82d8-0c5785a76692)

**Comment by realthemes** [comment]
With v28 scripts all my blocks in my custom block theme stop working, was there any drastic change that I had to take into account when moving from 27 to 28?

**Comment by erikyo** [comment]
Same here, after updating to v28 custom blocks completely disappeared. 

```
node v20.13.1
npm 10.3.0
```

reverting to `"@wordpress/scripts": "27.8.0"` (my last know working version) fixes the issue

--- edit ---
As noticed by @t-hamano, it seems that the JSX development runtime is required but never [enqueued in the editor.](https://github.com/WordPress/gutenberg/blob/ceb89495d22d0907e37faf170f052679e36f90aa/packages/dependency-extraction-webpack-plugin/lib/util.js#L46-L48) For that reason, the block will never be registered.

I just noticed that removing those lines:
https://github.com/WordPress/gutenberg/blob/ceb89495d22d0907e37faf170f052679e36f90aa/packages/dependency-extraction-webpack-plugin/lib/util.js#L46-L48

solves the issue. Maybe this is something related to [the-new-jsx-transform](https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#whats-different-in-the-new-transform)?

**Comment by akawsar711** [comment]
same problem here. If i replace pacakage-lock.json with 27.9.0 the block works but with 28.0.0 it disappears.

**Comment by mrleemon** [comment]
Same problem here. I downgraded to 27.9.0 to make my blocks work again.

**Comment by swissspidy** [comment]
cc @youknowriad @Mamaduka who worked on / reviewed the original PR.

The way it's currently built is not compatible with WP < 6.6

**Comment by gziolo** [comment]
> The way it's currently built is not compatible with WP < 6.6

The problem is going to exist for quite some time because many plugins target older major versions of WordPress. In WP 6.5 and older there is no `react-jsx-runtime` so there is no automatic way to declare `react` as a dependency. I think it’s what happens for folks if they don’t reference React directly.

**Comment by youknowriad** [comment]
Thanks for creating the issue and sharing your concern. It's clear that we overlooked a bit the impact of this change. Especially for the create-block package.

That said, the solution her is to actually stick to the old version of wp-scripts in the build tooling. Dev Tools and Production dependencies don't need to be updated at the same time. Plugin authors that already have a build tool in place don't need to touch their dependencies. 

I think there's a couple of things we should do here:

 1- First one is to fix @wordpress/create-block and stick to an old version of `@wordpress/scripts` in the generated code. At least until the release of WP 6.6 but maybe better until the release of WP 6.7 (Ensure the plugin support at least two WP versions)

 2- Write a post on make/core that serves as a dev note quickly to explain the change and the potential impact on build tools.

**Comment by justlevine** [comment]
@youknowriad might I also suggest updating the [CHANGELOG.md](https://github.com/WordPress/gutenberg/blob/HEAD/packages/scripts/CHANGELOG.md) file?

**Comment by youknowriad** [comment]
@justlevine The CHANGELOG already mentions the breaking change. Would you like to seem something else there?

**Comment by swissspidy** [comment]
`Use React's automatic runtime to transform JSX` in the changelog doesn't really make it clear what the implications are when it comes to WordPress versions. It could link to the dev note or something.

**Comment by justlevine** [comment]
> @justlevine The CHANGELOG already mentions the breaking change. Would you like to seem something else there?

If the minimum required WP version is changing to 6.6 (as I understood your [comment](https://github.com/WordPress/gutenberg/issues/62202#issuecomment-2144950937) to mean), this should be noted directly. Even if it was included in the PR description, I'd recommend this - more so since it seems to be a side effect that isnt called out explicitly in #61692

**Comment by anomiex** [comment]
It's not just `@wordpress/scripts`. Updating `@wordpress/dependency-extraction-webpack-plugin` to v6 in existing projects breaks too.

I don't know whether updating the other packages but keeping `@wordpress/dependency-extraction-webpack-plugin` locked to v5 will break anything.

**Comment by stefanfisk** [comment]
I also had to downgrade `@wordpress/dependency-extraction-webpack-plugin` because `6.0.0` broke my script deps. I'm using a plain `@wordpress/babel-preset-default` Babel config so I was quite surprised that the latest versions of these packages are not compatible with the latest version of WordPress.

**Comment by gziolo** [comment]
The same issue is also being discussed on WordPress Slack (link requires registration at https://make.wordpress.org/chat/): https://wordpress.slack.com/archives/C02QB2JS7/p1717340775169699.

**Comment by acicovic** [comment]
In the same vein, what should package consumers do regarding `@wordpress/babel-preset-default 8.0.0`, which has the same `Use React's automatic runtime to transform JSX` changelog entry?

From some quick testing, it doesn't seem to break anything by itself, at least in our case.

**Comment by youknowriad** [comment]
I've opened https://github.com/WordPress/gutenberg/pull/62265 to add a clearer note to the different impacted packages per the discussion above. Thanks for the suggestions.

**Comment by erikyo** [comment]
To address this issue, it would be nice to create a `postinstall` script that checks the current versions of the installed packages. 

What is needed is the post install script that parses the package.json and something akin to the `engines` field in `package.json` [as described in the npm documentation](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#engines), which specifies the versions of wordpress core and gutenberg that your package is compatible with. 

In this case if I had specified in my package.json 

`wp:{ gutenberg: 17.7, core: 6.5 }` 

it should have thrown an error and said it is not compatible with my version of wp

What do you think? I think it would be easy to implement and would be extremely beneficial.

**Comment by johnhooks** [comment]
The safest thing to do is to use `wp-scripts packages-update --dist=MIN_SUPPORTED_WP_VERSION` to manage the `@wordpress/*` package dependencies. They have compatibility requirements on each other and the targeted WordPress version. Reference [`packages-update`](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-scripts/#packages-update).

**Comment by amitsarkerr** [comment]
Got the same issue.
I was using 28.0.0 and no blocks were showing on the block editor.
To be honest, after Gutenberg and block editor, WordPress seems declining it's popularity.

Downgrading to 27.8.0 from 28.0.0 works good.

**Comment by justlevine** [comment]
> The safest thing to do is to use `wp-scripts packages-update --dist=MIN_SUPPORTED_WP_VERSION` to manage the `@wordpress/*` package dependencies. They have compatibility requirements on each other and the targeted WordPress version. Reference [`packages-update`](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-scripts/#packages-update).

@johnhooks 

Unless I'm misunderstanding, this seems very **un**safe, as`--dist-tag` sets the versions to the ones _released_ with that core WP version, not the ones that are minimally compatible with it. 
Beyond forcing you to use outdated scripts, this has the potential (and has IRL for me) to prevent forward-compatibility with later WordPress versions, especially if you need to support WordPress versions before all the 6.x Experimental API stabilization work.

**Comment by johnhooks** [comment]
@justlevine `wp-scripts` does not bundle the `@wordpress/*` dependencies but creates a dependency list for WordPress to load, the ones from whatever version of WordPress the site is running. So by "safest", I mean only use the APIs from the minimum WordPress version supported by project you are working on. By using `--dist-tag` the plugin/theme can be tested and developed in an environment similar to that lowest supported version of WordPress. 

@gziolo and @youknowriad please check my logic here, but I believe the project works hard to stay backwards compatible so using stable APIs from a targeted WordPress is the right thing for plugin/theme authors to do?

**Comment by youknowriad** [comment]
@johnhooks I think @justlevine is correct, if you use the dist tag, you're going to be using the packages that were released in that particular WP version. I would say that the version used doesn't really matter for the "production packages" because they are not going to be used, they're going to be replaced with the `wp.something` global. In fact you can probably remove these from your dependencies.

For the dev dependencies, if you pick the `dist-tag` version, these versions will be compatible with that particular version you picked (they are the one released at the same time) but they don't guarantee compatibility with previous WP versions. 

Since these are dev tools, breaking changes are possible and allowed, users won't notice issues when they upgrade their sites, these dependencies are updated manually by the developers.

---

For the current issue, I've started working on the dev note here to clarity things https://docs.google.com/document/d/1YyJQpP0M4rAtZC3zWN8P3eWdKr_KkZmeRnmaQCuaa6c/edit

I could use a review. Thanks.

**Comment by Luehrsen** [comment]
Same issue here. `@wordpress/dependency-extraction-webpack-plugin` just broke our block workflows. 

Downgrading now.

**Comment by johnhooks** [comment]
@youknowriad I find it vital to include the `@wordpress/*` dependencies in my project's `package.json` for the following reasons:

- Linting and type checking. Without the packages listed as dependencies the linter cannot verify imports, and TypeScript doesn't have access to the types (not all packages export types, but I do want to use the types that are available).

  This is also why I find it necessary to use `--dist-tag` for these packages, otherwise the linter and type checker will happily allow importing an using something that is missing from the desired minimum supported WordPress version of my projects.
  
- IDE autocompletion and inline documentation. Again without the packages being included in the project, these features would be unavailable. 

<hr />

The document you linked explains the issue well. Though just to make sure we understand it here, because of the concern @justlevine described:

> Beyond forcing you to use outdated scripts

Plugin/theme authors have to use the previous versions of the packages listed in the quote below, until  their projects have a minimum supported WordPress version of 6.6?

> When you’re ready to make WordPress 6.6 the minimum supported version of your plugin, you can update the following dependencies to use the new JSX transform.
> 
> @wordpress/scripts from version 28.
> @wordpress/babel-preset-default from version 8.
> @wordpress/dependency-extraction-webpack-plugin from version 6.

**Comment by youknowriad** [comment]
> Plugin/theme authors have to use the previous versions of the packages listed in the quote below, until their projects have a minimum supported WordPress version of 6.6?

Plugin authors have to use versions that are bellow the numbers mentioned here.

**Comment by youknowriad** [comment]
>  I find it vital to include the @wordpress/* dependencies in my project's package.json for the following reasons:

These are valid arguments indeed.

**Comment by johnhooks** [comment]
> Plugin authors have to use versions that are bellow the numbers mentioned here.

@youknowriad thank you for the confirmation.

**Comment by anomiex** [comment]
> I don't know whether updating the other packages but keeping `@wordpress/dependency-extraction-webpack-plugin` locked to v5 will break anything.

As far as I can tell, if you update `@wordpress/babel-preset-default` to v8 without `@wordpress/dependency-extraction-webpack-plugin` v6 it means your bundle will wind up including the react/jsx-runtime code (which appears to be <1k minified uncompressed). It's possible that could break if the bundled version of react/jsx-runtime is incompatible with the version of React provided by WordPress.

OTOH you may be including the jsx-runtime already, as if any of your bundled deps have switched their own builds to the new method then they'll already be bringing it. Looking back I see some of our plugins' bundles have been including some version of the jsx-runtime since June 2022.

Of the Gutenberg packages, looks like `@wordpress/icons` v10, `@wordpress/dataviews` v2, and `@wordpress/interface` v6 could bring it, as those dependencies aren't extracted by `@wordpress/dependency-extraction-webpack-plugin`  v5 and now have reference to react/jsx-runtime.

**Comment by ernilambar** [comment]
I have one question somewhat related to this issue. Is `@wordpress/scripts` supposed to be only used for block development? 

I have been using this in my plugin for simple react app as it handled bundling pretty elegantly. I stumbled here after my plugin broke after I updated `@wordpress/scripts` to latest version. And noticed:

```
Note If you're using @wordpress/scripts for building JS scripts to target WordPress 6.5 or earlier, you should not upgrade to this version and continue using @wordpress/scripts@27.
```

So, am I now stuck to `@27` forever?

**Comment by youknowriad** [comment]
@ernilambar Are you using `@wordpress/scripts` to bundle a JS application outside of WP or to bundle a plugin (not necessarily a block) for WordPress?

For the former, I'd say, don't use wp-scripts, it's not really its purpose
For the latter, yes, you should be using wp-scripts and you should be using `@27` until you're ready for your plugin to have WordPress 6.6 as the minimum supported version.

**Comment by ernilambar** [comment]
> @ernilambar Are you using `@wordpress/scripts` to bundle a JS application outside of WP or to bundle a plugin (not necessarily a block) for WordPress?

Second one: to bundle a plugin (not necessarily a block)
 
> For the former, I'd say, don't use wp-scripts, it's not really its purpose

Got it. 👍

**Comment by johnhooks** [comment]
@youknowriad will v27 still receive maintenance updates, to update dependencies?

**Comment by youknowriad** [comment]
@johnhooks I guess that's not clearly defined. If there are critical issues, that seems obvious (as it's part of WP 6.5 dependencies anyway, so would benefit from maintenance that goes there) but I don't expect it to gain new capabilities or things like that.

**Comment by johnhooks** [comment]
@youknowriad I wouldn't expect new capabilities, though using a package that depends on Webpack and not receiving updates for years (because that is the time frame we are discussing) seems wrong. I would expect it to receive dependency updates for as long as possible.

**Comment by justlevine** [comment]
> I guess that's not clearly defined.

@youknowriad What currently _is_ defined/documented (and where) regarding JS packages versioning, breaking changes, and forward/back-compatibility?

**Comment by youknowriad** [comment]
There's some details here https://developer.wordpress.org/block-editor/contributors/code/backward-compatibility/

**Comment by gziolo** [comment]
[JSX in WordPress 6.6](https://make.wordpress.org/core/2024/06/06/jsx-in-wordpress-6-6/) got published with the clarification about the challenges with dev tooling around the upcoming major WP release.

I also closed https://github.com/WordPress/gutenberg/issues/62327 as a duplicate as it contains similar reports as above.

**Comment by Mamaduka** [comment]
Do we need to do the package release to fix issue with `npx @wordpress/create-block@latest`?

**Comment by youknowriad** [comment]
@Mamaduka yes, I thought this would happen as part of the beta/RC backports.

**Comment by kstcovflw** [comment]
I am having the same error; my temporary walkaround to update wordpress to 6.6 Beta.

Here is how:

Follow [this](https://wordpress.org/news/2024/06/wordpress-6-6-beta-1/#:~:text=Install%20and%20activate%20the%20WordPress,%2FRC%20Only%E2%80%9D%20stream) to install the plugin.

on wp-admin page, if I install [WordPress Beta Tester](https://wordpress.org/plugins/wordpress-beta-tester/), then update WordPress version, I can see the plugin.

![image](https://github.com/WordPress/gutenberg/assets/163051045/b7d60c26-b60a-4e26-8600-597609979d8e)

If i go to edit a page:
![image](https://github.com/WordPress/gutenberg/assets/163051045/bd209173-29fd-459e-b4ff-76548ce8b77c)

**Comment by thelovekesh** [comment]
Instead of downgrading the packages, add a polyfill for WP versions below 6.6. This will be necessary anyway when upgrading to React 19 and ensuring compatibility with older WP versions.

Add the config to bundle the JSX runtime (webpack example here):
```js
const reactJSXRuntimePolyfill = {
	entry: {
		'react-jsx-runtime': {
			import: 'react/jsx-runtime',
		},
	},
	output: {
		path: path.resolve(__dirname, 'assets/js'),
		filename: 'react-jsx-runtime.js',
		library: {
			name: 'ReactJSXRuntime',
			type: 'window',
		},
	},
	externals: {
		react: 'React',
	},
        // Other config...
};

module.exports = [ reactJSXRuntimePolyfill ];
```

and later register the script for WP < 6.6 with `react` as a dependency.
```php
wp_register_script(
	'react-jsx-runtime',
	'path/to/react-jsx-runtime.js',
	[ 'react' ],
	'18.3.0',
	true
);
```

**Comment by youknowriad** [comment]
Great suggestion @thelovekesh that's indeed a valid solution as well. Would you mind sharing it as a comment on the dev note here https://make.wordpress.org/core/2024/06/06/jsx-in-wordpress-6-6/

I'm going to close this issue for now. Thanks all.

**Comment by thelovekesh** [comment]
Thanks @youknowriad. I have added a comment on the devnote - https://make.wordpress.org/core/2024/06/06/jsx-in-wordpress-6-6/#comment-46779.

**Comment by TobiasBg** [comment]
To add on to @thelovekesh's code suggestion:
I wrapped the `wp_register_script()` in a `wp_script_is()` check, to not have to compare WordPress versions:
```PHP
if ( ! wp_script_is( 'react-jsx-runtime', 'registered' ) ) {
	wp_register_script(
		'react-jsx-runtime',
		'path/to/react-jsx-runtime.js,
		[ 'react' ],
		'18.3.1',
		true
	);
}
```
I'm now running this in my plugin's action hook handler for the `enqueue_block_editor_assets` hook (for supporting blocks in the editors) and in my script registration routine for my plugin's admin screens that use React with WordPress components.

**Comment by l-schwitzkowski** [comment]
@thelovekesh I am sorry, which path is meant here?
path: path.resolve(__dirname, 'assets/js'),

since path and dirname where undefined I put in some hardcoded paths by try&error e.g. to the plugin, to my custom theme etc) but I always end up with "module is not defined" and I am really stuck. can you please explain what to do exactly?
The Block is built with create-block@latest.

**Comment by TobiasBg** [comment]
@l-schwitzkowski: You should be able to replace that line by
```js
path: `${ __dirname }/assets/js`,
```
and just the path for the file. `${ __dirname }` will be a reference to the main folder (which usually is where your webpack.config.js lives and from which you call your build process).

**Comment by l-schwitzkowski** [comment]
@TobiasBg Thank you, I really do appreciate any help at this point.
Downgrading didnt help, so I really need to figure that out.
The problem is that I dont have a webpack.config.js. 
I have a relatively clean wordpress environment (6.5.4, Node 21.5.0, npm 10.2.5 and React 18.2.0) with not more than one custom theme and that test-plugin. So I have one package.json in root that is just for tailwind for the templates, one in theme and one in the plugin.
The plugin is just a test since many things have changed in Gutenberg, so i just did this cli-command from wp tutorial: npx @wordpress/create-block@latest copyright-date-block --variant=dynamic ( https://developer.wordpress.org/block-editor/getting-started/tutorial/ )
I didnt change anything else, so the only dependency is wp/scripts.
So this is the default build command in my plugin: 	"build": "wp-scripts build --webpack-copy-php",
I really dont know about that --webpack-copy-php and it leads somewhere to wp-core.

**Comment by TobiasBg** [comment]
@l-schwitzkowski: Sorry, I don't have experience with using a manual build step like that. I use wp-scripts with a webpack.config.js, where I could then make the code changes from above.

**Comment by l-schwitzkowski** [comment]
@TobiasBg Thanks anyway :) Using wordpress 6.6 beta (1) solved the issue for now

**Comment by TobiasBg** [comment]
@l-schwitzkowski: Yes, that will work, but remember that files created that way now will not be able to run with WP < 6.6, without the polyfill.

**Comment by l-schwitzkowski** [comment]
@TobiasBg That is absolutely fine as its a new side-project. Still we are trying to figure out a solution to make our monolithic main project work within 6.6+ in the future. Until now i didnt have time to check the workarounds within this environment but hopefully there will be a solution until needed.

**Comment by mrkdevelopment** [comment]
This seems to have come back again as an issue when compiling blocks. It seems that I now again have to use "react" and not "react-jsx-runtime" when using the latest packages.

I was using the following

	"dependencies": {
		"@wordpress/create-block": "^4.44.0",
		"@wordpress/scripts": "^28.3.0"
	},

And when I compile the loader fails because it expects react instead of react-jsx-runtime.

**Comment by jlabs** [comment]
Not sure if this is related (it seems like it), but the editor page within WP is no longer loading. The browser console is flooded with errors like `Cannot read properties of undefined (reading 'jsx')`. All plug-ins (and WP) are up to date - which is what makes me think this is somewhat related.

**Comment by acicovic** [comment]
@thelovekesh, I wasn't able to make the polyfill solution work. However, without any extra webpack config, just loading the file from the core directory worked for me in WP 5.5, like so:

```php
if ( ! wp_script_is( 'react-jsx-runtime', 'registered' ) ) {
	wp_register_script(
		'react-jsx-runtime',
		'/wp-includes/js/dist/vendor/react-jsx-runtime.js',
		array( 'react' ),
		'18.2.0',
		true
	);
}
```

I'm trying to understand what the extra webpack config does and why we need it, since registering these files didn't seem to work in my case.

**Comment by jsnajdr** [comment]
> just loading the file from the core directory worked for me in WP 5.5

WP 5.5 doesn't have the `/wp-includes/js/dist/vendor/react-jsx-runtime.js` file, it's been added only 4 months ago in https://github.com/WordPress/gutenberg/pull/61692. That's why you need to polyfill it.

The `react-jsx-runtime` script can also be polyfilled by the Gutenberg plugin, then it will point to a `plugins/gutenberg` location.

If possible, you should avoid harcoding `<script>` tags that load the script for a given location, because the location is not certain. Instead, the server-side PHP code should generate the script tag with `wp_enqueue_script( 'react-jsx-runtime' )`.

**Comment by acicovic** [comment]
Somehow this was working for me, but @jsnajdr, thanks for pointing this out, what you say makes sense.

**Comment by acicovic** [comment]
It seems that many people opt to stay on the old branch instead of adopting a polyfill solution, and I understand that.

However, the old branch doesn't receive [security updates introduced later](https://github.com/WordPress/gutenberg/pull/64597), which becomes problematic.

@TobiasBg, have you actually managed to make this work? I visited your repo and couldn't find the code.

**Comment by jsnajdr** [comment]
Seeing how @acicovic and others struggle with adding a `react-jsx-runtime` polyfill to their plugins makes me think that the current situation with `@wordpress/scripts` using the new JSX transform by default is unacceptable.

We always encourage people to use the latest version of WordPress and everything related. It should be ok to use the latest version of `@wordpress/scripts`, too.

It's also common that plugins support several versions of WordPress back. Supporting only the very latest version is very rare if not nonexistent. Therefore, the standard version (i.e., the latest) of `@wordpress/scripts` should support creating standard (i.e., compatible few versions back) plugins. That's what the tool is here for.

Creating the `react-jsx-runtime` polyfill yourself is an expert task. You need to know how exactly the new React JSX runtime works and how to build it with webpack so that it's exposed on `ReactJSXRuntime` global. Very uncommon knowledge.

I don't know how to solve this yet. Currently the JSX `createElement`-like functions are also available in the `react` package, so `@wordpress/scripts` could get them from there. But with React 19 forward they won't be in that package anymore. For WordPress this is quite a big compatibility break. Normal users have the Babel transforms that hide the impl details from them, but in WordPress we're exposing the React APIs in a more direct way.

**Comment by thelovekesh** [comment]
Maintaining backward compatibility can be challenging sometime for various reasons. In the current setup, everything should function correctly with the latest version of WordPress and the `@wordpress/scripts` package. If you're managing a plugin that supports multiple WordPress versions, having a little understanding of polyfills makes sense.

For those who need it, here is an example of a polyfill implementation: [Polyfill Implementation](https://github.com/ampproject/amp-wp/blob/ad24bd7a82659427567e934081ffbcbe77b48fc8/webpack.config.js#L276-L300).

Additionally, include this PHP code to ensure the polyfill is loaded correctly: [PHP Code for Polyfill](https://github.com/ampproject/amp-wp/blob/ad24bd7a82659427567e934081ffbcbe77b48fc8/includes/amp-helper-functions.php#L985-L1001).

**Comment by acicovic** [comment]
@thelovekesh, thanks for the links, I'll take a look.

In the meantime, for anyone wanting to stay on the older version but get rid of the vulnerabilities, it's possible to add `"puppeteer-core": "^23.1.0"` in your `package.json`'s `overrides` section:

```json
	"overrides": {
		"puppeteer-core": "^23.1.0"
	},
```

You should test though that this change works well for your project.

**Comment by TobiasBg** [comment]
@acicovic: Yes, I have the polyfill code working fine, but unfortunately, it's not yet in a released branch of my plugin, which is why it's not yet in that repo. Sorry :-( But it's pretty much [what has been discussed above](https://github.com/WordPress/gutenberg/issues/62202#issuecomment-2156796649).

**Comment by acicovic** [comment]
The [code I had written in my attempt to update](https://github.com/Parsely/wp-parsely/compare/develop...try/update-wordpress-scripts?w=1) is already pretty close to the examples I'm seeing here. So I can only assume that there's something specific in my config that doesn't work as expected, and that I can't see it. This is my first time messing with webpack configs, so this doesn't help either.

I think that @jsnajdr makes some great points. If many developers are postponing a pollyfil solution, what will happen when we're forced to go that route with React 19? I think there should be some official form of docs for that, and people who can help out on GitHub issues.

**Comment by jsnajdr** [comment]
> If you're managing a plugin that supports multiple WordPress versions, having a little understanding of polyfills makes sense.

More or less _every_ WordPress plugin aims to support multiple versions, and I think it's not a reasonable ask that more or less everyone should understand the polyfills, be able to implement them themselves, or to be even aware that they are needed.

What if the `@wordpress/scripts` package itself added the common polyfills as part of the scaffolding and the build process it offers? Then a block author can install the latest `@wordpress/scripts` package, write only the value-adding code for their own block, and the package takes care of automatically producing a plugin that has some reasonable amount of backward-compatibility.

**Comment by johnhooks** [comment]
> What if the @wordpress/scripts package itself added the common polyfills as part of the scaffolding and the build process it offers? 

I totally agree, this would be very helpful.

**Comment by gziolo** [comment]
Would the following work for older versions of WordPress defined as an inline JS script with the `react-jsx-runtime` script handle?
```html
<script>
globalThis.ReactJSXRuntime = {
    jsx: React.createElement,
    jsxs: React.createElement,
    Fragment: React.Fragment,
};
</script>
```

The alternative would be to copy and adjust the production version, which is 859 bytes:

https://unpkg.com/browse/react@18.3.1/cjs/react-jsx-runtime.production.min.js

```js
'use strict';var f=require("react"),k=Symbol.for("react.element"),l=Symbol.for("react.fragment"),m=Object.prototype.hasOwnProperty,n=f.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner,p={key:!0,ref:!0,__self:!0,__source:!0};
function q(c,a,g){var b,d={},e=null,h=null;void 0!==g&&(e=""+g);void 0!==a.key&&(e=""+a.key);void 0!==a.ref&&(h=a.ref);for(b in a)m.call(a,b)&&!p.hasOwnProperty(b)&&(d[b]=a[b]);if(c&&c.defaultProps)for(b in a=c.defaultProps,a)void 0===d[b]&&(d[b]=a[b]);return{$$typeof:k,type:c,key:e,ref:h,props:d,_owner:n.current}}exports.Fragment=l;exports.jsx=q;exports.jsxs=q;
```

We could create a PHP file that conditionally enqueues such an inline script. It would live next to the webpack config in `@wordpress/scripts` and the build would copy it, if necessary, to the build folder and `require_once` from the asset file when needed.

**Comment by acicovic** [comment]
@gziolo, who would be the person that can give an answer to your question? Asking in case we can relay this to them more directly.

**Comment by jsnajdr** [comment]
> Would the following work for older versions of WordPress defined as an inline JS script with the `react-jsx-runtime` script handle?

Almost, but not quite 🙂 The API for `jsx` and `createElement` is similar, but significantly different. In how `key` and `children` are passed. `createElement` works like this:
```js
createElement( 'div', { className: 'box', key: 'k' }, child1, child2, child3 );
// or
createElement( 'div', { className: 'box', key: 'k' }, [ child1, child2, child3 ] );
```
while `jsx` has `children` as one of the props and `key` is a separate argument:
```js
jsx( 'div', { className: 'box', children: [ child1, child2, child3 ] }, 'k' );
// or for a single child
jsx( 'div', { className: 'box', children: child1 }, 'k' );
```

So, we'd need to do some extra work to implement the new runtime in terms of the old `createElement`. Other than that, the internal implementation are essentially identical. The checks and warnings in dev mode are slightly different, that's all I found.

**Comment by peterwilsoncc** [comment]
@jsnajdr @gziolo Would something like this work?

```js
import { createElement, Fragment as ReactFragment } from 'react';

const jsx = ( element, props = {}, key = '' ) => {
	let children = [];
	if ( props.children ) {
		children = Array.isArray( props.children ) ? props.children : [ props.children ];
		delete props.children;
	}

	if ( key ) {
		props.key = key;
	}

	return createElement( element, props, ...children );
};

const jsxs = ( element, props = {}, key = '' ) => {
	return jsx( element, props, key );
}

const Fragment = ReactFragment;

globalThis.ReactJSXRuntime = globalThis.ReactJSXRuntime || { jsx, jsxs, Fragment };
```

**Comment by jsnajdr** [comment]
@peterwilsoncc Yes, but there is one additional caveat where we need to be careful. There is a difference between:
```jsx
<div><br/><br/></div>
```
and
```jsx
<div>{ [ <br/>, <br/> ] }</div> // such array is typically created with a .map
```

In the first syntax the children are "static" and they don't have to have `key`s. This syntax is transpiled to:
```jsx
// classic runtime: children are spread
createElement( 'div', null, <br/>, <br/> )
// new runtime: uses jsxs function
jsxs( 'div', { children: [ <br/>, <br/> ] } )
```

With the second syntax children are checked for presence of a `key`. It's transpiled to:
```jsx
// classic runtime: children are array
createElement( 'div', null, [ <br/>, <br/> ] )
// new runtime: uses jsx function
jsx( 'div', { children: [ <br/>, <br/> ] } )
```

We need to take this into account when mapping `jsx`/`jsxs` to `createElement`. Other than that, your polyfill should be fine.

**Comment by acicovic** [comment]
Hello! Just wanted to ask if there any news or work on this, also taking into account the recent release of React 19?

**Comment by gziolo** [comment]
> Hello! Just wanted to ask if there any news or work on this, also taking into account the recent release of React 19?

The changes to how JSX is handled were done in anticipation of changes in React 19. There are [some other breaking changes coming in React 19](https://react.dev/blog/2024/04/25/react-19-upgrade-guide), so the impact will have to be assessed separately.
