### ISSUE TITLE
Post Editor Document Sidebar Publish Date causes horizontal overflow

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#62215]
I just noticed whilst testing Gutenberg version 18.5 RC1 that the Publish date control causes a horizontal scroll bar to appear in the document settings sidebar in the post editor. 
![CleanShot 2024-06-03 at 07 43 55@2x](https://github.com/WordPress/gutenberg/assets/20684594/a7b61d71-37a0-401f-a9d7-424cdcf296b1)

**Comment by fabiankaegy** [comment]
CC: @jameskoster as I believe I saw you were involved in the redesign work here :)

**Comment by t-hamano** [comment]
This is strange because this button has `text-wrap: pretty;` applied to it, so the text should wrap. And this style was added in #61954, which is part of Gutenberg 18.5.

![image](https://github.com/WordPress/gutenberg/assets/54422211/cb081e94-bdf2-42d2-9c03-6121d064f309)

- Do you have `text-wrap: pretty;` applied to that button?
- Do you have this problem with the latest Gutenberg?

**Comment by fabiankaegy** [comment]
@t-hamano safari doesn't support text wrap pretty. It only supports balance at this point

**Comment by t-hamano** [comment]
> safari doesn't support text wrap pretty

I see, that's certainly true.

@WordPress/gutenberg-design To prevent text overflow in Safari, it may be better to use something like `white-space: normal` instead of `text-wrap: pretty` for this panel only. Of course, the text wrapping position will change.

**Comment by jasmussen** [comment]
Can we do this?

```
text-wrap: balance;
text-wrap: pretty;
```

Presumably, that would cause Safari to fall back to balance if pretty isn't available.

**Comment by fabiankaegy** [comment]
@jasmussen Yeah that is how I commonly do it :) With a little comment explaining why the fallback is there =D
