### ISSUE TITLE
Bug in @wordpress/scripts

### ISSUE THREAD

**Issue by michaelbenker** [WordPress/gutenberg#62327]
### Description

There is problem with wp-scripts build

This worked not

```import { registerBlockType } from '@wordpress/blocks';

registerBlockType( metadata.name, {
	edit: () => {
		return (
			<div>Block Content</div>
		)
	}
} );
```

this worked
```import { registerBlockType } from '@wordpress/blocks';

registerBlockType( metadata.name, {
	edit: () => {
		return "Block Content"
	}
} );
```
i downgraded to "27.2.6" and everything worked.

### Step-by-step reproduction instructions

https://developer.wordpress.org/block-editor/getting-started/tutorial/

### Environment info

Fresh Wordpress 6.6.3

PHP 8.2
Node 20.14.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by scottmotion** [comment]
I saw your reply on SO and did a little digging. According to the changelog the latest version 28.0.0 contains breaking changes:

"Breaking Changes
Note If you're using @wordpress/scripts for building JS scripts to target WordPress 6.5 or earlier, you should not upgrade to this version and continue using @wordpress/scripts@27"

Downgrading to ^27.9.0 worked for me.

Should this release have been marked with a prerelease tag in order to prevent it becoming latest? I'm not an NPM expert but I just started using this package yesterday, so having the latest version being broken completely stifled my progress in the tutorial.

**Comment by gziolo** [comment]
Thank you for the report. It appears to the same issue as in #62202. There was public communication shared [JSX in WordPress 6.6](https://make.wordpress.org/core/2024/06/06/jsx-in-wordpress-6-6/) that tries to explain the problem and the proposed solution that is exactly the same as @scottmotion shared.

Closing this one as a duplicate.
