### ISSUE TITLE
Brackets are being read as a shortcode

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#6250]
This is an interesting note, when you use [ brackets ] in something you aren't always signifying a shortcode. Gutenberg gets a little keen when it sees this. Is there anything we can do to ease this?

**Comment by karmatosed** [comment]
Closing as see #3806 has this covered.

**Comment by iseulde** [comment]
@karmatosed I don't think this is the same issue?

**Comment by iseulde** [comment]
Reopening. I think the best thing to do here is get all registered short codes and match any of those instead of anything in between brackets.

**Comment by tofumatt** [comment]
Just to be clear, it seems the issue is that, for instance, text containing `[bracket]` that *isn't* already a Gutenberg block (no `wp:` comments around it), will show the classic editor and then when converted to a block change into a shortcode block even though no valid shortcode for that exists, right? I can reproduce that but I wasn't quite clear if that's what this issue is describing. 

If I type `[brackets]` into an empty new block, an existing block, etc. I don't see Gutenberg try to change it to a shortcode...

**Comment by iseulde** [comment]
See also #5695. I think we might have fixed the worst part with #6329. What is currently broken here?

**Comment by mtias** [comment]
@karmatosed anything pending here?

**Comment by karmatosed** [comment]
I can't replicate in latest version so lets close.
