### ISSUE TITLE
Site Editor : n.blocks is not iterable

### ISSUE THREAD

**Issue by nirmalkavaiya** [WordPress/gutenberg#62565]
### Description

Site Editor Page Edit  Add New Blocks Error show

https://prnt.sc/vWwUK0pXacN3

TypeError: n.blocks is not iterable
    at reducer.js:642:29
    at reducer.js:615:9
    at reducer.js:443:19
    at e.type (reducer.js:519:21)
    at reducer.js:745:9
    at combine-reducers.js:10:28
    at reducer.js:2107:21
    at combine-reducers.js:10:28
    at b (redux.js:288:22)
    at thunk-middleware.js:7:10

### Step-by-step reproduction instructions

Go to Site Editor Theme 
Edit Any Page and Add Block Error

### Environment info

WP : Version 6.5.4
With and Without Gutenberg Latest Plugin bug Generate 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thanks for the report.

From your screenshot, it looks like the issue is with a custom block and not a core block.

- Does this issue occur with core blocks too?
- Does this issue occur after upgrading to a specific WordPress version?

Maybe it would be a good idea to report this in the plugin’s forum.

**Comment by t-hamano** [comment]
@nirmalkavaiya This issue does not seem to occur with the core block, so I will close it. If you are experiencing the same error with other blocks, please comment.
