### ISSUE TITLE
Gallery Random images display missing

### ISSUE THREAD

**Issue by bahiirwa** [WordPress/gutenberg#6259]
Good job guys on the editor. It's really shaping up. Good experience so far.
 
I have not seen this below issue as far as research I have done in concerned.

In the classic/legacy editor, we have the option to have the images randomly display by simply checking the box. In the Gutenberg editor, the gallery block does not have this option. Is this becoming deprecated? I really like the feature.

**Screenshots**
Legacy editor with settings
![screenshot 2018-04-18 22 09 05](https://user-images.githubusercontent.com/7713923/38952854-9ef7db9c-4355-11e8-9f33-6ad4191dfccd.png)

Legacy editor with no settings
![screenshot 2018-04-18 22 09 58](https://user-images.githubusercontent.com/7713923/38952855-9f3ec160-4355-11e8-9060-d441e368ebc6.png)

**Comment by jorgefilipecosta** [comment]
In the classic editor galleries are a shortcode that can render different content each time it is called, Gutenberg generates a static HTML output for the gallery block. Unfortunately, I think, having the random order is not something achievable without adding a server-side render to the gallery (which I think it is not part of the plan).

**Comment by SolespireMarcus** [comment]
That's a shame, @jorgefilipecosta. I just mentioned in the #core-editor Slack chat how our team relies on this traditional server-side functionality of Gallery, where we can choose "Tiled Mosaic" as a Gallery Type. I feel like this soon-to-be-old shortcode strategy is the more flexible way in designing unique presentations, because you get the power of PHP being the engine. By losing this, we lose a certain creative outlet that was part of what made WordPress so great for custom galleries. I would ask your team to please re-consider on this issue.
![180609-0001](https://user-images.githubusercontent.com/31710444/41195034-d23771fe-6bda-11e8-8725-39541136c2c7.jpg)

**Comment by jorgefilipecosta** [comment]
>>  I feel like this soon-to-be-old shortcode strategy is the more flexible way in designing unique presentations, because you get the power of PHP being the engine. By losing this, we lose a certain creative outlet

Hi, @SolespireMarcus thank you for your inputs.
We understand that the power PHP as a rendering engine provides is important, and we are not taking that power away as with dynamic blocks https://wordpress.org/gutenberg/handbook/blocks/creating-dynamic-blocks/ it is possible to render blocks with PHP.
It would be possible for a plugin to implement a gallery that offers the random feature.
The question here is if that feature is so important that it should force galleries to be a dynamic block for all the users. Another possible path here is to include is to randomize the images on the client side with some JavaScript.

**Comment by mcsf** [comment]
Thanks for raising this issue, and also to @SolespireMarcus for sharing your team's flow.

There's a related conversation at #3852. At the heart of both, the issue lies in the fact that, currently, a dynamic block can't opt out of its dynamic character, i.e. it can't dynamically decide to use its static content. In a gist, there are two ways to change this:
- When `render_callback` is called, pass a new argument after `$attributes`: `$inner_html`
- When `render_callback` returns a specific empty value, default to outputting the static content. For this one, here is [a quick snippet](https://gist.github.com/mcsf/573fd7c42943f89c44ab31efe29d1a81).

However, there is no concrete plan to make this happen yet, as other pieces are being prioritized. For this reason, for your specific needs, I suggest that you:
- either keep the gallery shortcodes as they are (or wrapped in Shortcode blocks), since shortcode support will remain in the foreseeable future;
- or implement a dedicated Random Gallery block, tailored for your needs (the code could be based on the core Gallery block).

**Comment by mtias** [comment]
Also Jetpack is going to have a block for this functionality (Tiled Mosaic). Closing as you can treat the gallery as dynamic by using the `render_callback`.
