### ISSUE TITLE
Block toolbar removes bottom shadow of header

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#62639]
### Description

Reported in this comment: https://github.com/WordPress/gutenberg/pull/61835#issuecomment-2174482262

With any block selected, if you scroll the canvas up and part of the block toolbar overlaps with the header, the header shadow disappears.

I used `git bisect` to investigate the issue, and it looks like this issue first appeared in #61835.

### Step-by-step reproduction instructions

- Disable the Top Toolbar.
- Click any block.
- Scroll down the canvas.
- When the block is visible in the canvas, the block toolbar will be docked below the header.
- Scroll the canvas some more.
- As the block becomes invisible, the block toolbar will overlap the header.
- The shadow below the overlap should disappear.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/03fa7533-1023-4150-8206-f3246d759825

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by stokesman** [comment]
I've looked at this a little more as it’s pretty curious. I see that the block toolbar is in front of the header by z-index but doesn’t visibly overlap (besides the shadow) because its overflow is clipped by siblings of the header. Since the shadow isn’t part of the box model the overlap is possible (as opposed to when it was a border).

I also wanted to add that in case we want to consider a fix where we don’t have to fiddle about with z-index, I noticed applying `isolation: isolate;` on `.interface-interface-skeleton__body` or `.editor-visual-editor` solves it (not sure if which is the better place to put it).  Of course, it needs more testing to make sure there’s not some unintended effect, but I tested other popovers and they still go in front of the header as expected.

**Comment by t-hamano** [comment]
This is the first time I've heard of such CSS 😅 From what I've tested so quickly, it does seem to solve the problem.

**Comment by stokesman** [comment]
Well, I went ahead and made a PR of it ☝️.

Aki, it seems to me this would qualify as a regression since the last release and should be on the 6.6 board no?

**Comment by t-hamano** [comment]
> Aki, it seems to me this would qualify as a regression since the last release and should be on the 6.6 board no?

That's right, I'll add it to the board.
