### ISSUE TITLE
Block Remove button not visible on focus

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#6270]
After recent repositioning of the "Remove" control (the trash icon), seems the icon is not visible on focus when using a keyboard:

Starting from the more options button:

<img width="744" alt="screen shot 2018-04-19 at 08 56 10" src="https://user-images.githubusercontent.com/1682452/38976188-c6994270-43b0-11e8-9a9e-12a6699487ee.png">

Press the Tab key:

<img width="726" alt="screen shot 2018-04-19 at 08 56 13" src="https://user-images.githubusercontent.com/1682452/38976189-c6b62796-43b0-11e8-91a9-f606636ffc3b.png">

/Cc @jasmussen 

I'd also like to suggest to consider carefully the new positioning. While I understand the intent and I think having Remove as a first level control is a good thing, seems to me it's now dangerously close the the More Options button and could easily be pressed by mistake. Especially on mobile:

<img width="486" alt="screen shot 2018-04-19 at 08 56 39" src="https://user-images.githubusercontent.com/1682452/38976287-35da5098-43b1-11e8-8db8-945a5fae6773.png">

It's a destructive action without confirmation. Yes, there's "Undo" but as far as I see, "Undo/Redo" is not available on mobile?

**Comment by chthonic-ds** [comment]
> I'd also like to suggest to consider carefully the new positioning. While I understand the intent and I think having Remove as a first level control is a good thing, seems to me it's now dangerously close the the More Options button and could easily be pressed by mistake.

Exactly my experience today with a touchscreen, and this is after seeing the updated position and thinking, "I bet I accidentally hit the trash icon". The combined vertical height of the two icons is only slightly more than the height of my finger tip. It really does feel like there needs to be either more space between the icons, or, better still, the icons increased in size.

**Comment by jasmussen** [comment]
> I'd also like to suggest to consider carefully the new positioning. While I understand the intent and I think having Remove as a first level control is a good thing, seems to me it's now dangerously close the the More Options button and could easily be pressed by mistake. Especially on mobile:

For a little context, since the very start, one of the first things requested, was a delete button for blocks. For simplicities sake, and to keep things as "like an editor as possible", we hoped that backspace or delete when a block was selected, would be sufficient. This is why it's taken us so long to add the button, simple reluctance. Recent user tests, however, have suggested that the remove button is simply just not practical to bury in a menu, even if that incidentally happens to protect against a destructive action. 

Yes, there's undo for undoing a destructive action. On mobile, there is not, but there are revisions. This is not to say the point about mobile isn't good, it absolutely is, and we could consider a confirm on mobile. However the trash button has been and behaved like this on mobile for at least 3, maybe 4 months now. This doesn't automatically mean it's ideal, but it supports an argument I'd like to make: just because _we_ think it's going to be a problem in the future, doesn't always mean it will. Perhaps this is one of those situations where we should wait a release and see?

That said, I do think we should swap the icon places on mobile — the ellipsis should almost always be last.

**Comment by afercia** [comment]
Hm..  I'd tend to think the first goal of any software should be: avoid data loss 🙂 The only way to restore a removed block on mobile is revisions? Not sure that's good enough. Not saying it's necessarily a good argumentation but on my phone I get confirmation dialogs for any destructive action. That make sense to me, as mistakenly tapping some control it's easier than mistakenly pointing a mouse on a control.

> I do think we should swap the icon places on mobile — the ellipsis should almost always be last.

Yes please but not with CSS: visual order should match DOM order.

**Comment by jasmussen** [comment]
I don't disagree with you — I make a similar assessment. My suggestion is that it might be okay to wait and see if it's _actually_ an issue to prioritize, or not. There's no undo for writing text either — if you accidentally delete a word, you have to type it out again. Sure, apps can implement undo or confirm, and that's an option for us as well.

**Comment by afercia** [comment]
Sure, just wanted to be sure this is something under consideration (maybe to evaluate also during beta?). Closing as the main issue has been solved in #6279.
