### ISSUE TITLE
Text Block: activating drop cap option breaks further text entry

### ISSUE THREAD

**Issue by lsinger** [WordPress/gutenberg#6273]
## Issue Overview

When activating the drop cap option for a text blog with existing content, further writing in that block results in characters being replaced instead of added. 

## Steps to Reproduce

Using Gutenberg 2.7.0, Safari 11.1, macOS 10.13.4:

1. create a new post and write some text into the initial text block
2. activate the drop cap option
3. continue writing in the text block

## Expected Behavior

I expected the characters I'm typing to be added at the end of the block. 

## Current Behavior

The characters I type keep on replacing the last character. 

## Screenshots / Video

![dropcap-character-replacement](https://user-images.githubusercontent.com/23619/38983273-3e9c9dfe-43c4-11e8-9f0f-218bc4bf8ba7.gif)

I didn't find this issue reported elsewhere so opening it here now.

**Comment by brandonpayton** [comment]
This appears to be resolved due to #6359 but was reopened soon after merging. @iseulde, is there a reason we should keep this open?

Here's what I'm seeing due to hiding the drop cap on focus:
![drop-cap](https://user-images.githubusercontent.com/530877/46062496-d3b78700-c11e-11e8-9c2e-926b287893a7.gif)

**Comment by earnjam** [comment]
Closing this since the specific typing issue was resolved. Going to reopen #7292 as a possible future enhancement.
