### ISSUE TITLE
Last line Inserter is stuck at the top of previous Block, when using align:left in Block.

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#6288]
- Insert say Table block as latest in content area
- Use Align:left for Table block
- Inserter is not cleared under and is stuck at the top of last Table column.

I don't think it is something on purpose. As when using for instance Align:left for Image Block + Inserter icon "Add Block" is left of Image Block, other 3 icons right of Image Block.

**Comment by danielbachhuber** [comment]
Here's a GIF of the issue:

![tableui](https://user-images.githubusercontent.com/36432/41983048-d3bbbaac-79e1-11e8-835f-d3457dd22acd.gif)

Notably, a Table Block aligned left ends up in this state:

<img width="778" alt="image" src="https://user-images.githubusercontent.com/36432/41983087-ef8d296e-79e1-11e8-9708-e63aec31df72.png">

See the Inserter to the top left of the Table Block (instead of below). The ellipsis controls are also missing.

Flagging as `Needs Design Feedback` to get input on how this scenario should be handled.

**Comment by karmatosed** [comment]
Closing as this is same as this issue: https://github.com/WordPress/gutenberg/issues/7500
