### ISSUE TITLE
Customize Widgets: Editor hides when selecting some blocks

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#62898]
### Description

The customize widgets editor disappears leaving only a grey panel when selecting some blocks (paragraph works ok, blocks like image or latest posts cause an issue)

### Step-by-step reproduction instructions

1. Activate a classic theme like Twenty Twenty One
2. Go to Customize > Widgets
3. Select a non-paragraph block

Expected:
The block is selected and is still visible:
![Screenshot 2024-06-27 at 12 18 12 pm](https://github.com/WordPress/gutenberg/assets/677833/7f2e4fbc-2678-4b69-81b2-e98a1607e925)

Actual:
The editor disappears like this:

https://github.com/WordPress/gutenberg/assets/677833/9aa211c5-1fd4-47ba-9910-0b1a12e5ff02

Or maybe more like this:
![homer disappear](https://github.com/WordPress/gutenberg/assets/677833/f231c051-d140-4064-8cba-3e02d4f16a33)

### Environment info
It seems to only happen with the Gutenberg plugin active. It's ok when I check WP6.6

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by andrewserong** [comment]
I ran a `git bisect` which points to https://github.com/WordPress/gutenberg/pull/61943/ as the PR that introduced the regression in the widgets screen within the customizer.

From manually reverting part of that PR (just the [addition of `<StrictMode>`](https://github.com/WordPress/gutenberg/pull/61943/files#diff-b6ec05011df6210b0fc76d8db93fb2e615dc7c97d0fc0ce664e8f1d3c53768c4L95) in `customize-widgets/src/index.js`), I can get it working again locally.

@Mamaduka do you have an idea why the strict mode might affect this, and/or what a potential fix might be? I don't know much about strict mode, so that PR being the cause seemed a bit of a surprise to me!

**Comment by andrewserong** [comment]
Also, I double-checked and #61943 wasn't included in WP 6.6, and this feature appears to be working fine in 6.6 RC 1, so it looks like it's just Gutenberg that's affected.

**Comment by talldan** [comment]
It's probably related to the way strict mode re-runs effects to find bugs - https://react.dev/reference/react/StrictMode#fixing-bugs-found-by-re-running-effects-in-development.

So there might be an effect that works ok when it's run once, but the second run causes this issue.

The good thing is that it won't be an issue for production versions of code.

**Comment by Mamaduka** [comment]
Thanks for the ping!

Yeah, it's probably an effect or non-pure component issue, which StrictMode just highlighted. I fixed some bugs that the e2e tests caught.

I am assigning this to myself and will have a look later.

**Comment by andrewserong** [comment]
Thanks so much!
