### ISSUE TITLE
Paragraphs in Classic block lose ID during conversion

### ISSUE THREAD

**Issue by galbaras** [WordPress/gutenberg#63022]
### Description

When converting a Classic block, HTML elements with classes and/or IDs should retain those attributes (all of their attributes would be best). Lost classes in paragraphs were handled via #42172, so this is an new umbrella issue for retaining all reasonable attributes on all element types in Classic blocks when they are converted to blocks.

### Step-by-step reproduction instructions

1. Edit page created with Classic Editor
2. Check element classes and IDs
3. Convert Classic block to blocks
4. Compare classes and IDs of elements

### Environment info

WP 6.5.5
Vanilla Block Editor in WP 6.5.5

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by hbhalodia** [comment]
Hi @galbaras @ellatrix, I have raised the PR for the same - https://github.com/WordPress/gutenberg/pull/66520.

Thank You,

**Comment by hbhalodia** [comment]
Hi @ellatrix @galbaras, I am unsure for the above PR, because, I just give a try to reproduce the issue with latest trunk, but I am unable to reproduce it. Actually, it preserves the IDs, without any additional changes. Below is the screencast for the same.

https://github.com/user-attachments/assets/abefb06a-4b13-4e5e-8261-0a6c6a952c66

So converting the above PR in draft mode for now.

Thank You,

**Comment by galbaras** [comment]
That's a `h2` element, not a paragraph, but I repeated the test with `<p class="some-class" id="some-id">some text</p>` and both class and ID were retained. I think we're good.

**Comment by hbhalodia** [comment]
Hi @galbaras, I am sorry for that, I just checked the reference ticket where all headings and paragraphs were discussed. I checked with p tags and h tags, but showed h2 here.
