### ISSUE TITLE
Improve behaviour when saving content while offline

### ISSUE THREAD

**Issue by johnbillion** [WordPress/gutenberg#6322]
## Issue Overview

As Gutenberg is a JavaScript driven application that doesn't rely on traditional form submission like the current editor does, there's an opportunity to improve the end user experience when the client experiences connectivity problems or goes offline completely.

For example, if the saving action fails in any way, Gutenberg displays an error message that states `Updating failed`. It would be great if Gutenberg could inspect the `navigator.online` property at this point (or earlier), and if it returns `false` then display a more appropriate error message to the user, for example `You do not have an internet connection. Saving and previewing is not available offline`.

A further enhancement would be to fully save the post content in the browser in the same way that the current editor does, to avoid data loss in case the user decides to close their browser window. This happens in the current editor, but not in Gutenberg. I'm not sure if there's an existing ticket for that.

**Comment by johnbillion** [comment]
In addition, clicking the `Preview` button while offline results in a loading spinner that never stops spinning.

**Comment by johnbillion** [comment]
Core ticket here, but not very relevant to Gutenberg: https://core.trac.wordpress.org/ticket/41535

**Comment by westonruter** [comment]
It would indeed be a great improvement to show a warning when offline and to store the changes in `localStorage` to restore later. 

In addition to this, I think we also now have the opportunity go much father than having parity with the classic editor. With service workers we could provide an _entirely offline_ authoring experience:

* The service worker can cache the assets required by the editor (i.e. the old Turbo mode: https://github.com/xwp/pwa-wp/issues/34) as well as the HTML required to render the edit post screen (minus legacy metaboxes).
* The service worker can cache the REST API responses for any number of posts and media to allow them to be accessible for editing when offline. To access the list of offline-editable posts, there would probably need to be an REST API-driven post list table to which could leverage what @rmccue prototyped in [new-list-tables](https://github.com/WP-API/new-list-tables).
* If a user goes offline while editing and they attempt to save, the saved post can be scheduled for a [background sync](https://developers.google.com/web/updates/2015/12/background-sync) to automatically send back to the server when the user re-connects, even if they don't go back to the post edit screen they were on. The Workbox has a [background sync API](https://developers.google.com/web/tools/workbox/modules/workbox-background-sync) that looks well suited for this.

With this in place, if the user hits “Save Draft” when offline then a notice could appear as:

> You do not have an internet connection. Your changes will be synced once back online. Previewing and some editing is not available when offline.

Enabling offline editing in Gutenberg is one of the key use cases we've identified for service workers in core for the [PWA feature plugin](https://github.com/xwp/pwa-wp). It would be great to identify what Gutenberg would need from service workers to enable offline usage so that the feature plugin can be built to facilitate it.

**Comment by schmitzoide** [comment]
Weston how you’d know which items to cache (posts, media) in preparation for the potential offline situation?

**Comment by westonruter** [comment]
@schmitzoide I'm guessing the heuristics would probably include caching the X most recently-modified posts, in addition to caching all of a user's drafts (and their media). It could then use runtime caching to store any other posts that the user accesses. 

The biggest challenge here I think is what to do in the conflict scenario, when you make changes to one version of a post offline but that post has had other changes done to it once you go back online. I suppose we'd need a merge conflict resolution UI.

Another challenge for offline in WordPress is that some things would not be possible offline, including the uploading of new media and creation of new reusable blocks, since these would rely on obtaining new `AUTO_INCREMENTED` IDs.

**Comment by westonruter** [comment]
We could bypass the issues with conflicts by only doing background sync to push up changes to the user's _autosave revision_. That would then allow the user to restore the autosave which could then overwrite another user's changes. That's not great either as it just somewhat passes the buck, deferring the problem down the road. Instead of doing this the background sync could do a `PUT` request to the endpoint with an `If-Not-Modified-Since` header so that their changes would be saved as normally if nobody else edited the post (which would probably be the normal case) but then if that `PUT` request's precondition fails, it could then fallback to re-sending the pending changes into the autosave revision.

**Comment by getsource** [comment]
To me, this seems like a pretty big regression from the current editor. Why is it marked with Enhancement and not in the merge milestone?

**Comment by tofumatt** [comment]
I have started tackling a lot of accessibility stuff for the merge and have let this sit a bit, but I *would* like to get back to it and have at least the beginnings of offline support for the merge. I originally committed to that but then ended up wrangling a lot of accessibility issues. It's still on my radar though… I agree I would like to see it in the merge. I guess I'll add it in for now; you can blame me if it doesn't make it! 😅

**Comment by getsource** [comment]
Cool, thanks so much! Appreciate the attempt either way.

**Comment by designsimply** [comment]
#7367 proposes saving post date to the REST API offline so data isn't lost, and I think that covers the first point.

#4590 proposes better error messaging for the "Updating failed" error.

If you agree the issues you've raised are covered in the other two, I would like to close this issue in favor of those in order to consolidate to more specific issues because it helps keep them actionable (and this issue/discussion can still be a good reference point for the others). If I've missed anything in my read of the suggestions that isn't covered by the other two issues, then we should keep this issue open. These are important issues and I also would like to say thank you for raising them!

**Comment by designsimply** [comment]
Issues like these are certainly a tough call! 7367 does appear to need a dev that is not already dedicated elsewhere and that may not happen before 5.0. I'll leave this issue open just a bit longer as I agree offline saving is important but still want to get a check on whether we can consolidate these issues, even though 7367 slated for 5.1.

**Comment by getsource** [comment]
I'll also note that at least one of the two (this one, or the two you mention) should probably be marked back-compat, rather than enhancement.

**Comment by mtias** [comment]
There's a work in progress in https://github.com/WordPress/gutenberg/pull/9383 if anyone wants to help continue it (of note, `localForage` has incompatible license). I'd love to have offline compatibility sometime soon, personally, but I don't think it should block. In any case, let's consolidate the conversation in #7367 which has a bit more traction.

**Comment by westonruter** [comment]
I've opened a core ticket with patch for adding support for the `If-Unmodified-Since` request header when updating posts: https://core.trac.wordpress.org/ticket/47676

**Comment by miina** [comment]
Note: looking into this in terms of starting creating a small proof of concept based on Service Workers (see @westonruter's [comment ](https://github.com/WordPress/gutenberg/issues/6322#issuecomment-410578818) for specifics).

**Comment by miina** [comment]
Here's a PR (currently in full PoC state) for implementing very basic offline editing with Service Workers:
https://github.com/miina/gutenberg/pull/1

It basically:
- Allows editing a previously loaded post only.
- Displays a message about being offline upon clicking "Update" and lets the user know that the post will be updated later.
- For now, always updated the post content when online again, ignoring changes done by anyone else meanwhile.

Other notes:
- Requires https (since using Service Workers)
- Assumes that pretty permalinks are _not_ enabled.

**Comment by youknowriad** [comment]
Closing this issue cause I believe offline save is implemented now cc @mcsf 
Let me know if I'm missing anything.

**Comment by mcsf** [comment]
It's less ambitious than service workers, but local autosaves were added in #16490.
