### ISSUE TITLE
Inserter: white space at the very bottom of the results

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#63384]
Using 6.6 RC 3 on an InstaWP site, I noticed that if I searched for a block then scrolled down the inserter to see the block directory offerings, I could keep scrolling and end up in an endless white space:

https://github.com/WordPress/gutenberg/assets/26996883/241805b8-0a1f-46e5-83b0-bea989cb924f

Curious if others can replicate:

1) Add a new post
2) Open the inserter
3) Search for something like "blog"
4) Notice that there's a bunch of white space as you scroll down to the bottom of the inserter

**Comment by talldan** [comment]
> Curious if others can replicate:

Yep, I can. There were quite a lot of scroll related bugs in 6.6, seems like this is yet another.

**Comment by talldan** [comment]
I had massive deja vu with this one, and it seems like it was also a bug in 6.5, but was apparently fixed:
[Users can scroll off the bottom of the block editor into a forbidden void when searching in the inserter](https://github.com/WordPress/gutenberg/issues/56811#top)

Looks like there were two fixes:
- [Fix vertical overflow when inserter is open in post and site editor](https://github.com/WordPress/gutenberg/pull/57127#top)
- [Fix editor canvas overflow on search results with position: relative](https://github.com/WordPress/gutenberg/pull/60287#top)

Maybe those fixes were somehow undone.

**Comment by talldan** [comment]
As mentioned by @jeryj, it's the block directory results that cause the issue - https://github.com/WordPress/gutenberg/pull/57127#issuecomment-2024022161.

Specifically there's some visually hidden text in the the blocks in the block directory results that's set to `position: absolute`. You can get these weird scroll issues when there's an element set to `position: absolute;` if the element is positioned relative to something outside of the scroll container, so that's why setting `position: relative` on a parent fixes it.

This was really causing massive deja vu again. Seems like I also fixed another similar issue in that past - https://github.com/WordPress/gutenberg/pull/44853. 😄

**Comment by ellatrix** [comment]
@talldan Any reason this is moved out of Done?
