### ISSUE TITLE
canUser select does not work with the global styles post type.

### ISSUE THREAD

**Issue by jorgefilipecosta** [WordPress/gutenberg#63438]
### Description

When using the canUser selector against global styles the selector always returns false even for admin users with the capability.

### Step-by-step reproduction instructions

- Load the site editor with an admin user, and verify you can change global styles.
- Paste the following code in the browser console: ` await wp.data.resolveSelect('core').canUser('read', {kind: 'postType', name: 'wp_global_styles' });`, verify it returns false when it should be true.
- Paste the follow code in browser console: `await wp.data.resolveSelect('core').canUser( 'read', 'global_styles' );`, verify it returns false when it should be true.

### Environment info

- Gutenberg trunk with the latest WordPress trunk, also in WordPress trunk without the plugin.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
@jorgefilipecosta, it turns out we made a couple of wrong assumptions.

* The global styles entity is registered with `kind: 'root', name: 'globalStyles'`, not as a post type.
* It doesn't have a route for list items, with means the following selectors won't work - `select( 'core' ).canUser(  'read', { kind: 'root', name: 'globalStyles' } )` and `select( 'core' ).getEntityRecords( 'root', 'globalStyles' )`.

You can only check capabilities for individual global styles entities - `canUser( 'read', { kind: 'root', name: 'globalStyles', id: 41 } );`.

The `id` value can be obtained using `select( 'core' ).__experimentalGetCurrentGlobalStylesId()`, though I'm unsure if it works for low capability users.

**Comment by jorgefilipecosta** [comment]
Thank you for researching this @Mamaduka. I think we can close this issue. I used your findings to propose a simplification at https://github.com/WordPress/gutenberg/pull/63812.
