### ISSUE TITLE
Zoom out: cover block resize handler is misplaced

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#63522]
### Description

![image](https://github.com/user-attachments/assets/e96b95bd-52bf-41b1-b8b7-924246842445)

### Step-by-step reproduction instructions

Open a pattern category in the inserter and select a cover block

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by MaggieCabrera** [comment]
I found a bug I think might be related to this. We are assuming all sectioning elements are going to be groups but in this case it isn't and it's not behaving as it should. Also bear in mind, one of the core patterns is a cover block without a wrapping group block, this is what happens:

![Screen Capture on 2024-08-08 at 11-54-43](https://github.com/user-attachments/assets/59328562-38fe-464f-850c-76d83ace38e0)

**Comment by MaggieCabrera** [comment]
In the case of the cover block, the handle is missplaced because the scaling from zoom out is not applying to it. I wonder if on zoom out it should be showing at all. We are working under the assumption that on zoom out mode all top level blocks are groups but that's not always the case, even more so on the post/page editor. The image block is also showing handles, for example, and the cover block is allowing for that drag and drop replacement of the image that I reported earlier. This is all expected behavior given that those top level blocks are not really locked. Should they if they are not group blocks?

**Comment by MaggieCabrera** [comment]
> This is all expected behavior given that those top level blocks are not really locked. Should they if they are not group blocks?

Actually, top level blocks have getBlockEditingMode set to `default`, with everything inside them set to `disabled`. If we set the non group top level blocks to `disabled` the won't be selectable anymore, so that's not a good route to explore

**Comment by scruffian** [comment]
One option could be to apply the zoom out scaling to the handles.

**Comment by getdave** [comment]
> We are assuming all sectioning elements are going to be groups

I checked this and the logic no longer makes any assumptions about the block type of the actual sections themselves. These are defined as the immediate child blocks of the "section root block" (i.e. `sectionRootClientId`).

The only criteria in play for the Template post type, is that the "section root block" must be:

- a `core/group`.
- must have a `<main>` tag
