### ISSUE TITLE
Removing a Classic block in the code editor causes Blocks to be "Deleted or unavailable" in the Visual editor

### ISSUE THREAD

**Issue by 1naveengiri** [WordPress/gutenberg#6371]
## Issue Overview

I switched from visual editor to the code editor, it shows me a message on the already added block
**Block has been deleted or is unavailable**
although on page refresh the blocks are there and also on post update they also visible in the frontend. 
 
## Steps to Reproduce (for bugs)

1. go to edit post page
2. Add few blocks to post content with Gutenberg layout.
3. Change editor from visual to code from the option given beside setting in RHS.
4. add a new block through code editor. 
5. switch back from code editor to visual editor and you will see the message **Block has been deleted or is unavailable**  

Check the video below

## Screenshots / Video

https://drive.google.com/file/d/1DW4tOQ6007Q1hGciyXm5jmQxA1Nj7nR0/view

**Comment by danielbachhuber** [comment]
Thanks for the report, @1naveengiri.

To make your screencast more accessible...

### 1. Add some blocks to the Gutenberg editor

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/36432/40261944-adcd2530-5ab8-11e8-85b8-2724e689089c.png">

### 2. Remove the Classic block

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/36432/40261965-c96db02a-5ab8-11e8-9065-4c65fe9aa00a.png">

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/36432/40261971-d2ca0baa-5ab8-11e8-98d0-0b8c370dcab3.png">

### 3. "Block is deleted or unavailable" message appears

<img width="983" alt="image" src="https://user-images.githubusercontent.com/36432/40261985-e5644172-5ab8-11e8-8ded-23102c52c337.png">

I don't know the underlying implementation well-enough to comment on a solution, but I'm filing against `Merge Proposal: Editor` because I think this is a significant-enough problem that it should be addressed sooner rather than later. It seems to be similar to #4498

**Comment by danielbachhuber** [comment]
Closing in favor of #5754, which is an earlier report
