### ISSUE TITLE
Remove excess <p> from Tag Cloud edit function

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#63716]
In the edit function of the Tag Cloud block, there is a secondary `<p>` within the block, around the tags. This does not occur on the front-end. The extra `<p>` within the block is causing additional default browser margin to be applied within the block only within the editor. The front-end looks as expected. 

I propose the edit function is updated to accurately reflect the front end, which will bring these closer to 1:1.  

### Editor

![CleanShot 2024-07-18 at 12 39 49](https://github.com/user-attachments/assets/e3160d1e-bf3b-4631-bb4d-aadf98d2254e)

### Frontend
![CleanShot 2024-07-18 at 12 41 49](https://github.com/user-attachments/assets/44580922-aa9d-44f6-a58e-b895f8d80bcc)

**Comment by Mamaduka** [comment]
The block uses server-side rendering; the tag cloud markup is the same on both ends as a single `<p>` element wrapper.

**Comment by richtabor** [comment]
Right, but a block wrapper exists on the edit function, which moves the p inside, which causes it to get margin applied.

**Comment by akasunil** [comment]
Came here to report this issue. Glad to find out it already been noticed.
This also causes problems with this [global style support ](https://github.com/WordPress/gutenberg/pull/63592) for this block.

<img width="1251" alt="image" src="https://github.com/user-attachments/assets/54ba2c82-c1e8-43e5-9b3b-fbd35d44b4c3">

**Comment by aaronrobertshaw** [comment]
I can take a look into this one this week but I'm not sure there is a true fix unless we rewrite the Tag Cloud edit JS component to use the REST API for everything. 

A while ago, there was an effort to reduce some of the double-up of padding/margin etc when block supports were applied to server-side rendered blocks. The following PRs show a bit of that history.

- https://github.com/WordPress/gutenberg/pull/44491
- https://github.com/WordPress/gutenberg/pull/44439

The way the server-side rendering works, I don't think the wrapper can be removed. 

There might be two compromise options to move forward in the short term:

1. Remove the class name from the inner `<p>` tag and add some editor styles to make it as benign as possible.
2. Add editor styling to try and counter global styles on the wrapper instead

Any thoughts? 

Is there enough value in refactoring this block to use the REST API to warrant the dev time? There may need to be some updates to the REST API too if any functionality is missing.

**Comment by richtabor** [comment]
Maybe the simplest solution is to add block css to negate the <p> margin within the editor.

**Comment by ramonjd** [comment]
> Add editor styling to try and counter global styles on the wrapper instead


Second this!

**Comment by aaronrobertshaw** [comment]
A tentative fix is up in https://github.com/WordPress/gutenberg/pull/63832. 

Ultimately, I chose to apply the resets to the inner element rather than the wrapper because alignment classes with default padding are only applied on the outer wrapper. The approach in #63832 minimizes the required changes.

**Comment by akasunil** [comment]
@aaronrobertshaw we might have to do same for other block support attribute styles like background, colors, border etc.

**Comment by aaronrobertshaw** [comment]
Thanks @akasunil, this issue is a little more slanted towards the spacing issues caused by default and global styles.

Block supports should already be taken care of by the `skipBlockSupportAttributes` on the server-side render component [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/tag-cloud/edit.js?plain=1#L177). I believe global styles are ok given the class name on the inner wrapper.

If there is a problem with the skipping of block support attributes and classes that would be best as a separate issue as it would affect all blocks using server-side rendering. To be able to effectively debug further we need some steps to replicate the issue and a screenshot that shows the conflicting styles.

**Comment by akasunil** [comment]
@aaronrobertshaw I used the Tag Cloud Block to test color support, and I found that block and styles were not working properly. Here is video for reference.

[Blog-Home-‹-Template-‹-gutenberg-‹-Editor-—-WordPress (8).webm](https://github.com/user-attachments/assets/a83cdd21-5da6-481e-888e-814355fe9c50)



It appears that block style takes precedence over global styles applied to the block, it should be the other way around.

| Block style  | Global style |
| ------------- | ------------- |
| <img width="1099" alt="image" src="https://github.com/user-attachments/assets/1fce2de7-3402-4be7-9198-3982e8a87c81">  | <img width="1091" alt="image" src="https://github.com/user-attachments/assets/d67ff25d-c1ba-4484-9ee6-7c1ad57e4486">  |

**Comment by aaronrobertshaw** [comment]
@akasunil this discussion might be better over on your PR proposing to add color support to the Tag Cloud block.

> Here is video for reference.

It appears as though this video is highlighting the spacing issue https://github.com/WordPress/gutenberg/pull/63832 addresses in a superficial manner. I've only just merged that PR a minute ago so it should be resolved now.

> It appears that block style takes precedence over global styles applied to the block, it should be the other way around.

I think this is back-to-front. Block instance styles **should** take precedence over global styles.

The issue is that the color block support classes and inline styles aren't being inherited by the server-side rendered block markup. The best approach there might be to follow what was [done for the Latest Comments block](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/latest-comments/edit.js?plain=1#L31-L37). Rather than skip all block support attributes, the block manually filters problematic support styles (e.g. spacing) out.
