### ISSUE TITLE
Add help text support to individual radio button options

### ISSUE THREAD

**Issue by jarekmorawski** [WordPress/gutenberg#63735]
It'd be fantastic to add native support for a help text to the individual radio button options. We already use it in a few different places in the site editor and it will become even more important when we start building out forms and settings screens in the new admin.

<img width="701" alt="image" src="https://github.com/user-attachments/assets/2772d207-a2bb-4726-a9b4-c25e65f8db03">

Related to https://github.com/WordPress/gutenberg/issues/63734. cc @ciampo @mirka

**Comment by jameskoster** [comment]
To clarify, this is about adding help text to the _individual radio options_, correct? 

I agree this makes sense, and it would be good to bake into the component since – like you say – it has already been 'hacked' into existence in a few places:

<img width="371" alt="Screenshot 2024-07-19 at 09 28 14" src="https://github.com/user-attachments/assets/1f780b8a-eae0-498b-a912-c993a7ee74f0">
<img width="371" alt="Screenshot 2024-07-19 at 09 28 18" src="https://github.com/user-attachments/assets/f7e3047c-8b8d-41e0-ae2b-950faf5fbf76">

**Comment by jarekmorawski** [comment]
> To clarify, this is about adding help text to the individual radio options, correct?

Correct! I updated the OG post to reflect that.

**Comment by ciampo** [comment]
Trying it out in #63751

**Comment by ciampo** [comment]
Support for help text for individual options has landed in #63751
