### ISSUE TITLE
Zoom Out: Focus search when showing an insertion point

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#63867]
## What problem does this address?
In zoom out, when you click on the inserter button [+] the insertion marker shows, but it's not clear to users what is happening.

## What is your proposed solution?
When the inserter button is clicked we should focus the search input so users can see where their next action should be.

**Comment by getdave** [comment]
I've looked into this a bit. The search component is here

https://github.com/WordPress/gutenberg/blob/34b5219842367bb111cc010cb1db9a3a593812dd/packages/block-editor/src/components/inserter/menu.js#L155-L167

It is possible to wrap this in a `<div>` and use the `useFocusOnMount` hook to programmatically focus the search. This can be done conditionally by passing the `ref` returned from `useFocusOnMount` or just passing `null`.

The problem is how to do this conditionally? It will require some new global state to track whether or not to focus the search.

We already have `setIsInserterOpened`, but that is `Boolean`. We could add options to that action to allow consumers to control a separate focus state.

**Comment by scruffian** [comment]
I believe `setIsInserterOpened` uses `setInserterIsOpened` which takes whole load of options: 

https://github.com/WordPress/gutenberg/blob/34b5219842367bb111cc010cb1db9a3a593812dd/packages/block-editor/src/components/block-tools/zoom-out-mode-inserters.js#L104

**Comment by getdave** [comment]
Thanks. Funnily enough I just found that bit. I'm manipulating it now.
