### ISSUE TITLE
Remove the site logo block from core

### ISSUE THREAD

**Issue by Sam-Xronn** [WordPress/gutenberg#63954]
## Backstory
As the block editor and FSE editor in general has progressed the requirement for a site logo block has diminished. Replaced by new functionality the site logo block as it stands is a degraded version of the image block offering less functionality, and creating a whole range of problems both functional and user experiance. 

## What problem does this address?
The site logo block does not support a range of basic functionality which is already covered by the image block. See below a list of current examples;

### No ability to add a link
The site logo block cannot be used on WordPress installations run on a subdomain. This is due to the inability to link to the parent domain, despite a design system existing for this on the image block. Some common examples would be any sites running blog., .news, event., shop., jobs.
#56820 

### No aspect ratio controls
No option to select media aspect ratios e.g. a square logo
#63382 

### Confusion on bookmark/fav icon
A new feature has been added to Settings > General that allows you to upload a site icon removing the only unique feature the site logo block offered. It's now confusing from a users perspective as to where the correct location to add the media should be. 

### No support for light/dark site logos
If a website consists of different different coloured headers or a transparent header its common to see different coloured logos used. This isn't possible with the site logo block. Creating 2 headers and having 2 site logo blocks will override one another. See website example below; 
![demo](https://github.com/user-attachments/assets/25ceb5ed-7def-49bd-91df-be0e8fadbf5a)
 

## What is your proposed solution?
Remove the site logo block. It's a confusing block that doesn't add any new functionality rather limits the website editor. The block will continue to be used purely based on it's name.

**Comment by hanneslsm** [comment]
The big advantage of this block is, that when once a logo is added, the block can be reused and the exact same logo is included every time. You don't need to go through the media library and select the correct logo again.

I agree that the the missing features you pointed out should be added though.

**Comment by hanneslsm** [comment]
I'd like to add that the conversation about using the image block instead and adding a site logo option is actually quite interesting https://github.com/WordPress/gutenberg/issues/63382#issuecomment-2250208043 I'm not averse to that idea.

**Comment by Sam-Xronn** [comment]
> The big advantage of this block is, that when once a logo is added, the block can be reused and the exact same logo is included every time. You don't need to go through the media library and select the correct logo again.

While I do agree that is a benefit to using the block. I'm not sure how many different locations a site logo is typically displayed.

**Comment by richtabor** [comment]
> A new feature has been added to Settings > General that allows you to upload a site icon removing the only unique feature the site logo block offered. 

The site logo block is a critical block for the editing experience, for _most_ people. 

- You can use a site logo block anywhere, and it's updated everywhere. 
- Your site logo persists on theme switch, if that theme also has the site logo in the header (most do). 
- You don't have to find, or upload, a logo file whenever you want to add one — just add the logo block. 

> I'd like to add that the conversation about using the image block instead and adding a site logo option is actually quite interesting

The image block should not be more confusing imo, by adding a control to configure it as a block that already exists. Sure, with connections you could potentially choose the site logo as a source, or the home url as a link source, but that's a far cry from what most people will want to do, when instead they can add a block that has all that setup for them already. 

---

What's great about WordPress is that you can have your way of doing things, and it's totally cool. So if you want to use an image block instead of a site logo, then that's all good. But for most WordPress users, leaning in on simple and intuitive (like a block specifically for a site logo) is ideal.

**Comment by richtabor** [comment]
I'm going to close this issue as not-planned per my comment above. Thanks for bringing up the subject and opening the discussion.
