### ISSUE TITLE
Cursor keeps jumping to the end of text inputs

### ISSUE THREAD

**Issue by cameronjonesweb** [WordPress/gutenberg#6398]
## Issue Overview
When adding a link to an image block, the cursor continually jumps to the end of the input. This makes it impossible to alter text that's been typed without deleting it. Additionally, arrows cannot be used to move the cursor, instead the focus is moved to adjacent elements.
 I'm going to go out on a limb and say that there are likely many more interactions affected by this considering I discovered the exact same issue affecting image captions more than a year ago [(screencast)](https://www.youtube.com/watch?v=oZsIgi4FTqA).
Gutenberg 2.7.0

## Steps to Reproduce (for bugs)
1. Insert an image block
2. Add a link to the image
3. Move the cursor anywhere but the end of the link
4. Try to type multiple characters

## Expected Behavior
The the cursor should behave as it does with normal input fields

## Current Behavior
The cursor will jump to the end of the input after typing a single character

## Possible Solution
1. Make the text input behave like a text input
2. Prevent arrow keys from changing focus and instead use the tab key

## Screenshots / Video
* [Screencast of current issue, 25/4/18](https://youtu.be/y6Hr9epM4dA)
* [Orignal discovery of the issue affecting image captions during user testing in April 2017](https://www.youtube.com/watch?v=oZsIgi4FTqA)

## Related Issues and/or PRs
Couldn't see any issue open with a very quick search but obviously this is not the first time this problem has occured

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by designsimply** [comment]
I tested with WordPress 4.9.8 and Gutenberg 3.4.0 using Chrome and Firefox on macOS and Chrome 68 on Windows 8.1 could not see the cursor jump to the end of the text when adding text to the middle of a link for an image, a caption for an image or a link inside a paragraph block. ([1m2s](https://cloudup.com/cSE_8f5Dwcx) Chrome example)

Note: the link option in the image block toolbar is no longer present (screenshots: [2.7](https://user-images.githubusercontent.com/1119271/43791596-64f8f73e-9a33-11e8-8b8a-ea0de21def84.png) vs [3.4](https://user-images.githubusercontent.com/1119271/43791597-650e49ea-9a33-11e8-8fb4-981366b7cecc.png)).

Because I was unable to reproduce the problem as described and because this was originally reported several versions ago (2.7), I am going to close but happy to reopen if it comes up again.

**Comment by estebanwaseaten** [comment]
I have seen a very similar thing with the TextControl component in WP 5.2 (current Version).
The TextControl is used to access a meta field. The cursor jumps to the end of the input after each key-stroke. This effect only seems to appear if connected to an attribute with source "meta" (and blocks save() function returning null). I have posted the issue under #15739

**Comment by designsimply** [comment]
@estebanwaseaten thank you for the note and for adding a new issue with steps to reproduce!
