### ISSUE TITLE
Unexpected editor error when importing lodash to block

### ISSUE THREAD

**Issue by TinBoyko** [WordPress/gutenberg#6399]
## Steps to Reproduce (for bugs)

1. Create block
2. import { get } from 'lodash';
3. The editor has encountered an unexpected error.

`react-dom.min.b75d8b30.js:62 TypeError: this.activateMode is not a function
    at load-scripts.php?c=1&load[]=hoverIntent,common,admin-bar,svg-painter,heartbeat,wp-auth-check,backbone,wp-util,wp-backbone,media-models,wp-plupload,jquery-ui&load[]=-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,wp-mediaelement,media-views,postbox&ver=4.9.5:298`

Chrome

**Comment by roborourke** [comment]
@TinBoyko it's because lodash is already in a global context so you have to import the sub script directly eg:

```js
import get from 'lodash/get';
```

Just needs documenting I think.

**Comment by keesiemeijer** [comment]
related #4043

**Comment by aduth** [comment]
>1. Create block

Can you elaborate? Share some sample code?

**Comment by aduth** [comment]
In debugging this further, just as in #4043, this is nothing to do with Gutenberg itself, but rather the plugin's loading of Lodash causing Underscore to be overridden, therefore conflicting with expected usage. You'll see similar breakage on the classic editor if you allow your scripts to be loaded there.

You should do one of the following:

- Depend on the `lodash` script handle introduced (to Gutenberg) in #5933 (preferred because it avoids multiple copies of Lodash being bundled)
- Use the [`lodash-es` module](https://www.npmjs.com/package/lodash-es) to avoid having the `_` global being set
- Assist with the effort to port Underscore to Lodash: https://core.trac.wordpress.org/ticket/43733#ticket

**Comment by robertsheacole** [comment]
Just for anyone getting an error related to `_.pluck` is not defined in WordPress. I have a plugin using Vue.js and inside of one of my templates I am importing lodash. This caused a collision and the post editor in the admin broke. You could not see the content in the `view` tab, but you could in the `text` tab. When I remove lodash it worked and when I imported the specific name spaced version it worked.
This is kind of a ridiculous break. WordPress is importing `_` into the global namespace. this is unacceptable! They really need to keep it in their own scope.

**Comment by hybridwebdev** [comment]
5 years later, still an issue. @roborourke solution was what fixed it for me.
