### ISSUE TITLE
Make Block API compatible with the mobile native implementation

### ISSUE THREAD

**Issue by koke** [WordPress/gutenberg#6402]
We’ll need to do some adaptations to the block API to ensure blocks can also run [on the mobile apps](https://make.wordpress.org/mobile/2018/03/21/gutenberg-on-mobile/). This means building the block UI only with predefined primitives instead of HTML elements, and using a subset of CSS for styling. There might be other limitations around JavaScript  and the DOM that we don’t know about yet.

Since the mobile implementation will be based on React Native, this might also limit the React.js version that Gutenberg uses to one that is compatible.

**Comment by markkap** [comment]
I hope that I am reading the implications wrong, but right now this sounds like plugin developers will have to test their blocks on mobile, otherwise the result of editing on mobile might be undefined and at worst case lead to content corruption.

**Comment by koke** [comment]
@markkap that's a fair concern and something we've discussed although we don't have a concrete plan for it yet.

We want to make it easy for plugin developers to have their custom blocks work both on web and mobile, but also handle unsupported blocks gracefully. I don't know what that will look like yet: if we'll make developers explicitly declare mobile compatibility, or infer that from the block code.

**Comment by markkap** [comment]
My concern is not so much with people not being able to edit information related to a block created by a plugin, but that it will somehow fall from the content with the user not knowing at all that there is a problem.

**Comment by markkap** [comment]
@mcf, I do not know how the mobile apps work. Obviously the way the current apps work, content is being mangled. So this is something that happen already, claiming it should not be a concern for the future is a little weird for me.

Generally when people do not know what is it that they are editing they are more likely to do mistakes, so it is not only an issue of "we can know which blocks are problematic" but also an issue of UX.

I frankly do not use or care about the mobile apps, but I do develop plugins, and I do care about the users of my plugins, and I need to make a decision if I should implement a block in my plugins. (putting aside how hard or not it is for now) or leave it as shortcode based. If a shortcode provides more compatibility than the decision is very simple.
To write a block I need to know that I will not need to test it on all the various "mobile" OS. This issue right now is a total blocker for me.

**Comment by jasonbahl** [comment]
When (not if) Server Side Registration of blocks becomes the primary way to register blocks (#2751), and Gutenberg has a (much needed) official fields API (see: https://github.com/rtCamp/gutenberg-fields-middleware) then plugin developers can register blocks via a Server Registry that ANY client can interact with. As long as blocks exist only in the client, that client becomes the _only_ plugin that can interact with that block. 

Realistically, Gutenberg _needs_ to have a true Fields API and plugin developers should simply use that Server Side API to register blocks for the vast majority of use cases. *_Custom_ client side code should be the exception, not the rule*. 

The less custom JS plugin and theme developers write, the more compatible blocks can be with _any_ client, whether it’s Gutenberg in the WP-Admin or external clients like the iOS/Android  native apps, Calypso, WP-CLI, REST API, WPGraphQL, etc. 

What ANY client ultimately needs to know in order to interact with Blocks is what blocks exist for the particular context that’s being edited (post_type, page template, current_user, etc), what attributes the block is allowed to have and the intended way to interact with the attribute (Field definition, like you see in the middleware plugin), etc. Even the Save logic _should_ be determined centrally on the server to ensure _any_ client can properly interact with the blocks.

The only _custom_ JS ever needed should _only_ be related to the edit functionality, but for the most part edit functionality should still be derived from the Server Block Registry where the block should provide a description of how to interact with it for _any_ client to translate into a UI (or other method of interaction, like CLI commands).
