### ISSUE TITLE
Focus missing from `cover` block from key board navigation

### ISSUE THREAD

**Issue by up1512001** [WordPress/gutenberg#64035]
### Description

- When using a `cover` block in the editor, it has tab navigation. However, the same functionality does not work on the front end.

Nearly similar to this issue, but pressing tab on the front end is not skipping the whole 'cover' block. Instead, it is just missing the focus style here: https://github.com/WordPress/gutenberg/issues/41989

### Step-by-step reproduction instructions

1. open editor 
2. select cover block
3. add background image
4. In the editor, press the tab key and you will see that it is navigable using the tab key.
5. save post check same on the front end
6. press the tab on the front end and you will see the tab is not able to select the `cover` block.

### demo video

https://github.com/user-attachments/assets/3e57d9b9-1fce-4d24-af2c-00b3cc205503

### Environment info

- Using the latest Gutenberg trunk.
- command I run
- - `npm run wp-env start`
- - `npm run dev`

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by carolinan** [comment]
The block has tab navigation in the editor because it is editable. In the editor you need to be able to edit and add the inner blocks. The block itself is not editable on the front.

What part of the cover block do you expect to be focusable on the front? Why? The block itself is not an interactive element.
Did you add focusable elements inside the cover block, that are being ignored when tab is used?
