### ISSUE TITLE
Can't add cite in Quote block

### ISSUE THREAD

**Issue by samikeijonen** [WordPress/gutenberg#6404]
## Issue Overview
I guess blockquote is now using nested blocks. But I can't add cite in Quote block now.

## Steps to Reproduce (for bugs)

1. Add Quote block
2. Try to add `cite`.
3. Where is it?
4. Can't add it:)
5. Everything looks a mess.

## Screenshots / Video
<img width="655" alt="quote" src="https://user-images.githubusercontent.com/1820415/39240952-ff8913f8-488d-11e8-8e20-53f0f20c953b.png">

cc: @jasmussen

**Comment by jasmussen** [comment]
Thanks for reporting this. It seems to have been a regression from https://github.com/WordPress/gutenberg/pull/6054

**Comment by jasmussen** [comment]
It actually _is_ possible to add a citation, you have to select the quote _parent block_ in order to do so:

![selecting parent block](https://user-images.githubusercontent.com/1204802/39422315-22a678c0-4c6d-11e8-8025-1198c3903e4e.gif)

As more blocks get converted to using child blocks, we should find a better way than the hover breadcrumbs to select child blocks. 

Also related, #6459

**Comment by samikeijonen** [comment]
Ahaa, that's hidden  well:) _Write citation_ placeholder could just be there all the time.

**Comment by mcsf** [comment]
Closing per reverting of #6054
