### ISSUE TITLE
Include Javascript Functions in Editor Link Field

### ISSUE THREAD

**Issue by groovdigit** [WordPress/gutenberg#64068]
I am hoping that your WordPress team can add a “trigger javascript function” option that would allow users to enter a given javascript function into the URL text field. I can add that functionality in the CODE VIEW, but I believe adding this as an option in the LINK field would be a great tool. (If such an option already exists, how do I access it?)
https://groovdigit.com/wp-content/uploads/2024/07/link-field.png
https://groovdigit.com/wp-content/uploads/2024/07/link-script.png
Thanks for your help! Best wishes, Gabriel

**Comment by akasunil** [comment]
Thank you for your suggestion! You can achieve the functionality using event listener. You can follow below steps to implement this functionality by adding your custom JavaScript code.

- **Add an Event Listener**: You can add a JavaScript event listener to capture the click event on the link.
- **Trigger the JavaScript Function**: Within this event listener, you can trigger the desired JavaScript function.

**Comment by Mamaduka** [comment]
This is intentional to [prevent XSS](https://en.wikipedia.org/wiki/Cross-site_scripting). Users with access to Code Editor have `unfiltered_html` capabilities, while most users who can access Link Editor don't.

Closing this as "won't fix" / "not planned".

@akasunil, the suggested method can be used for JS events and user interactions.

**Comment by groovdigit** [comment]
Thanks for the advice concerning XSS vulnerability. This was a topic I had not heard of before and am glad now to have it in mind as I develop my websites.
