### ISSUE TITLE
Default paragraph block ignoring allowedBlocks parameter when searching for blocks

### ISSUE THREAD

**Issue by ssang** [WordPress/gutenberg#64411]
### Description

Not sure what changed to cause this but when a block allowed for the `core/paragraph` block and you use the `/` shortcut to type and insert other blocks, it used to only show the blocks that were available to the parent block. It doesn't allow for you to actually insert the block but you're able to view it in the list that is generated. From what I can tell, I get a list of blocks that don't explicitly define any allowable parents.

When you use the appender to open the block selector popup, you still see only the `allowedBlocks`

### Step-by-step reproduction instructions

1. Create a block that allows for a subset of blocks including the `core/paragraph` block as child blocks
2. Insert the paragraph block
3. Type `/` to start searching for other blocks
4. A list of all blocks that don't match the subset set in `allowedBlocks` seems to show up

### WordPress Version 6.5

![image](https://github.com/user-attachments/assets/cc74c37b-8afe-4828-9d09-02acf1318d16)

### WordPress Version 6.6.1

![image](https://github.com/user-attachments/assets/0945c583-be2b-403a-9683-0731ef2ec5c5)

### Environment info

I have a customized hybrid theme setup so it could be a compatibility issue on my part but I just don't see what could have changed to cause this and what I need to do to fix it. I've tried with the Gutenberg plugin as well to see if it's been fixed since but no luck.

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by ssang** [comment]
I've pinpointed it down to the Gutenberg version 18.5.0

Possibly related to this PR #62169

**Comment by talldan** [comment]
Thanks for reporting this, and especially for making a PR!

In terms of core blocks, I can also reproduce the issue in the navigation block (possibly others, I stopped at the first one I found):
![Screenshot 2024-08-13 at 1 31 31 PM](https://github.com/user-attachments/assets/1b6ca3fb-96be-4948-8107-af25ffb3fbce)

A lot of these blocks are not allowed in navigation and trying to insert one of them results in nothing happening. I'll give your PR a test and review, it might also be a fix to ship in the upcoming WordPress 6.6.2 given the fix is so tiny and the bug is quite bad. (though I need to check that it's an issue in 6.6.1 first)
