### ISSUE TITLE
Have only one place for transforms

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#6449]
Right now we have 2 places for transforming blocks:

![2018-04-26 at 16 51](https://user-images.githubusercontent.com/253067/39316869-241fdad2-4972-11e8-8ab3-c59a829bdab6.png)

![2018-04-26 at 16 52](https://user-images.githubusercontent.com/253067/39316892-302a2d0a-4972-11e8-9686-7e72bdca8be3.png)

I would suggest we reduce this to one place. My initial feelings are to only have it under the ellipsis - although that could be causing discovery issues. Whatever option we go for, we should go with just having one place.

**Comment by SuperGeniusZeb** [comment]
I would choose to remove the transform button from the toolbar... transforming a block does not feel like a primary action that is used very often, so it probably should only be shown under the ellipsis. Also, it is more clear that transformation options exist in the ellipsis, compared to the singular icon in the toolbar that is easily overlooked as just the icon of the current block (since that is what it looks like aside from the dropdown arrow). I often forget about the button in the toolbar since it does not immediately yell "transformation" to me, since its icon is just the icon of the block.

One of the reasons for having the transform button in the toolbar is to make it easier to write textual content quickly. But with Markdown support, slash commands, 2 insert block buttons, the sibling inserter, and the transform options under "More Options", I feel like that button will be rarely used once one of the other methods are learned.

On another note, removing the transform button in the toolbar would provide some extra space for another button or two in its place, like maybe a button to insert inline `<code>` formatting, or perhaps a button to select the parent block. And of course, just removing the button from the toolbar and not replacing it with any other button would make the block UI take up a bit less space.

**Comment by karmatosed** [comment]
@SuperGeniusZeb yeah my feelings are the toolbar is also right one to remove. I am not sure about adding extra buttons in though, I don't think that code formatting for example is a primary action for everyone. As you point out, having the toolbar take up less space is a really nice benefit here.

**Comment by SuperGeniusZeb** [comment]
@karmatosed Yeah, the `<code>` formatting does not feel like a thing that needs its own button in core to me either (I can just use markdown for that), but I saw it brought up in #6397 and thought I would use it as an example.

**Comment by mcsf** [comment]
Now that block settings menu is the only place for transformations, we should make sure it's not too busy. The menu doesn't very gracefully handle shorter viewports, in my experience, so something like a transformations drawer could be in order (I recall this being discussed in the past). cc @karmatosed

**Comment by karmatosed** [comment]
@mcsf hmm interesting do you have some past issues to reference as that could be good to consider?

**Comment by mcsf** [comment]
@karmatosed: I see #4467, for instance.

**Comment by jorgefilipecosta** [comment]
Reopening this issue because the changes that fixed it were reversed in https://github.com/WordPress/gutenberg/pull/6566.

**Comment by SuperGeniusZeb** [comment]
Related: #6781
