### ISSUE TITLE
Cover Block Should Allow Setting Color After an Image has been Used

### ISSUE THREAD

**Issue by MadtownLems** [WordPress/gutenberg#64516]
## What problem does this address?

Currently, when inserting a new Cover Block, you can choose a plain background color. However, once you choose an Image for the background, there is no way to go back to the color option.

![2024-08-14 10_18_13-Window](https://github.com/user-attachments/assets/e3f02f86-ee21-4aa8-a18d-290bc088bc97)

## What is your proposed solution?

An option to choose a color should exist in the Replace Media dropdown in the toolbar (or "Add Media" if the media has since been cleared)

![2024-08-14 10_19_54-Window](https://github.com/user-attachments/assets/014d4abe-ee31-4be6-b4e2-a95dca3a9933)
![2024-08-14 10_21_57-Window](https://github.com/user-attachments/assets/be8858a4-264d-4d6c-9b33-9aec5bb289b4)

**Comment by akasunil** [comment]
Thank you @MadtownLems for creating issue.

There is a "Clear Media" button in the block settings section of the sidebar panel. With that, we can cleanse the media. I think it should have been in the toolbar rather than the sidebar. It's easy to miss out. Add/Remove media option should be at one place for ease of use.
 
[Blog-Home-‹-Template-‹-gutenberg-‹-Editor-—-WordPress (3).webm](https://github.com/user-attachments/assets/663320ce-31ac-4808-a3f0-abf8db09bdf5)

**Comment by MadtownLems** [comment]
Ah, ok - thank you. It wasn't clear to me that the initial option to select a color simply set the Overlay color and the Overlay Opacity to 100%.  Given that, it IS possible to get back to this state, though I maintain the UI is confusing and could be improved.

**Comment by akasunil** [comment]
> UI is confusing and could be improved

Agree, There is PR https://github.com/WordPress/gutenberg/pull/64630 that addresses this issue.

**Comment by akasunil** [comment]
I'm closing this since the `Reset` option is available now in toggle bar for the cover block. Added through PR https://github.com/WordPress/gutenberg/pull/64630
