### ISSUE TITLE
Patterns in the Site Editor Design panel should have visible names

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#64632]
## What problem does this address?

I was writing testing instructions and I wanted to ask the tester / user to change the header template part to use the "Centered header" from the Design panel. But because the patterns do not have visible names, only aria-labels, the tester (who does not use assistive technology) would need to guess which pattern to insert.

Also, the notice in the bottom left corner only says that the header template part is updated, not which pattern that was inserted.

## What is your proposed solution?

- Show a visible tooltip with the name when a user hovers over/focuses on a pattern
- Or always show the name below the pattern.

**Comment by isuke01** [comment]
I think this is general issue to not be able see even current pattern.

I had situation where client was super confused how to achieve certain effect. Since he wanted to add another block like previous, but wasn't able, there is no setting visible, note nor info in the block tab panel, that could suggest it is an Pattern used in the block.

This lead to confusion among editors (especially not technical one) that are not used to work on "this exact" website. 

I feel like patterns are super hidden. It should be visible similar to Variation or Styles, if pattern is for particular block.
