### ISSUE TITLE
Site URL can overflow the pre-publish component when the URL exceeds a certain length

### ISSUE THREAD

**Issue by vcanales** [WordPress/gutenberg#64730]
### Description

When the site's URL is long, the pre-publish screen makes the sidebar scroll horizontally.

### Step-by-step reproduction instructions

1. Go to https://playground.wordpress.net/
2. Create a New Post
3. Click Publish; the Pre Publish screen should be shown.
4. Notice how the sidebar has become scrollable because the site's URL is long.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/fe7a1fca-b617-4546-a2a5-d0402cd18001

### Environment info

WordPress Playground, tested with WP 6.4, 6.5, 6.6.

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by t-hamano** [comment]
Note that this issue cannot be reproduced on a local site run with wp-env. This is because the URL is a site URL, and `localhost:8888` does not have a long enough length to cause an overflow:

![image](https://github.com/user-attachments/assets/d132fe7b-320f-4ccd-9ca7-b3aaf1c24a3a)


It should be possible to reproduce on the Playground, or on a site with a long domain that does not contain hyphens:

![image](https://github.com/user-attachments/assets/a1124f31-2348-449f-87ae-12d980e88cdc)

**Comment by imrraaj** [comment]
I can reproduce this issue. I have changed the CSS a bit and come up with the following solution. We can change the `.components-site-card` style to have an overflow-x set to scroll that way only the site-card will be scrollable and not the entire side panel

Let me know if I can proceed and submit a PR

https://github.com/user-attachments/assets/14a356e2-f03d-4f8c-af48-cf0337434844

**Comment by t-hamano** [comment]
@imrraaj Thanks for the suggestion.

My suggestion would be to do url wrapping, like the Link popover:

![image](https://github.com/user-attachments/assets/372f1e2c-4e0a-4cba-a451-2d8362ccc3d8)

In other words, apply `word-break: break-word;` to `.components-site-home`.

**Comment by imrraaj** [comment]
Hey @t-hamano I have raised the PR. Please can you review it?
