### ISSUE TITLE
Why not use querySelector instead of queryFirst

### ISSUE THREAD

**Issue by mitogh** [WordPress/gutenberg#65]
Looking into the code I found the usage of `queryFirst` but I believe `querySelector` already does this.

> Returns the first Element within the document (from the [docs](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector))

Is there any reason to not use `querySelector` instead? I would like to create a PR with the changes if required.

Thank you.

**Comment by widoz** [comment]
Have a look at the code and you'll see that queryFirst is a wrapper for query that return all of the element found using querySelectorAll.

I think that it's correct to use the **querySelectorAll** since most of the time you should manipulate all of the same objects within the page.

`
function query( selector ) {
	return Array.from( document.querySelectorAll( selector ) );
}

function queryFirst( selector ) {
	return query( selector )[ 0 ];
}`

**Comment by mitogh** [comment]
Yes thanks after I take a looked to the code I created the issue.

Because: 

```js
function queryFirst( selector ) {
	return query( selector )[ 0 ];
}
```

Creates the same result as `querySelector` so I think if `querySelector` already does that I don't see much benefit of creating a wrapper function for that. Unless the fact that if the selector is not found `queryFirst` is going to return `undefined` and `querySelector`  is going to return `null`.

And about:

> I think that it's correct to use the querySelectorAll since most of the time you should manipulate all of the same objects within the page.

I agree but in the cases where `queryFirst` is used there is no benefit or advantage in usage of `querySelectorAll` since you are first hand are requesting for the first element only.

**Comment by sirbrillig** [comment]
> I agree but in the cases where queryFirst is used there is no benefit or advantage in usage of querySelectorAll since you are first hand are requesting for the first element only.

I agree, unless the intent is to abstract using the DOM API directly. If that's the case, it would still be more efficient to change `queryFirst` to just be an alias for `document.querySelector`.

**Comment by mcsf** [comment]
Hey, @mitogh, thanks for raising a good question. Indeed it would be rather pointless to keep queryFirst as is, but there is a certain advantage to offering a separate interface. For instance, in #59, the following change:
https://github.com/WordPress/gutenberg/commit/8dd51767ae809d43878e9de75e6857582d978061

**Comment by mcsf** [comment]
To be clear, most of the advantage is to keep a common interface between `query` and `queryFirst`. Implementation-wise, we could rewrite it to use `querySelector` directly.

**Comment by mitogh** [comment]
I think that would be just change the code inside `queryFirst` I can send a PR with the changes if required.

**Comment by mcsf** [comment]
It's up to you, really, you're welcome to start a PR. Just bear in mind that the approach throughout this project has generally been "prototype first, code correctness _eventually_" 😄 , which is why you'll find tons of oddities in the code. We've been delaying refactoring up until the point where it's actually limiting us to implement something else.

**Comment by jasmussen** [comment]
Closing for now, we can reopen if/when it becomes an issue in the plugin phase.
