### ISSUE TITLE
Provide withSelect mocks for use in in JavaScript unit tests

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#6512]
Inspired by 7b65aa0e74a25e79825f00b998ee14005448747b

> danielbachhuber [4:58 PM] it'd be nice if there was a mocked `withSelect()` for the unit test suite though
> nerrad [4:59 PM] ya that looks good.  I agree about the mock but what would it do, just feed the props?
> I’m not sure that’d be much different than what you’re doing now right?
> danielbachhuber [4:59 PM] it'd be a centrally defined store of props, rather than making it up for each test (edited)
> nerrad [4:59 PM] oh so a set of knowns
> danielbachhuber [5:00 PM] right
> nerrad [5:00 PM] gotcha
> danielbachhuber [5:00 PM] if the API output ever changes, you only have to change in one place

Core does something along these lines right now, with PHP generating a schema for JavaScript to use.

**Comment by aduth** [comment]
Related Slack discussion in the 2018-05-01 Core JS Chat: https://wordpress.slack.com/archives/C5UNMSU4R/p1525183093000136

**Comment by aduth** [comment]
In revisiting this and re-reading my comment at https://github.com/WordPress/gutenberg/issues/6512#issuecomment-385682968 , the comment describes the encouraged approach to testing components. There should be no need to mock `withSelect` because one should not test the `withSelect`-bound component, but rather the component it wraps.

It can be reopened if it's still unclear or if there's a demonstrated benefit to an alternative approach, but I don't currently see any action item here.
