### ISSUE TITLE
"Set featured image" button border flashes on focus

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#65299]
## Steps to reproduce

In a post, go to the Post tab in the sidebar and move the keyboard focus onto the "Set featured image" button.

## Expected behavior

The focus ring shows like the other components.

## Actual behavior

There is a lag between the focus ring appearing and the normal border disappearing.

## Video

https://github.com/user-attachments/assets/bce6d0de-5f66-438a-a746-2030f6429da2

**Comment by t-hamano** [comment]
My guess is that this issue is related to #66007, because the "Set featured image" variation button also has [an inset box shadow applied by default](https://github.com/WordPress/gutenberg/blob/d809650edace0d7212e7cb0e274637e7e55560c2/packages/editor/src/components/post-featured-image/style.scss#L68).

**Comment by Vrishabhsk** [comment]
Hi @mirka 👋 
- I have resolved this issue in this PR : https://github.com/WordPress/gutenberg/pull/66092
- The solution implemented was discussed in this [`issue`](https://github.com/WordPress/gutenberg/issues/66007#issuecomment-2405194812) and [`PR`](https://github.com/WordPress/gutenberg/pull/66045#issuecomment-2410452388)

Let me know your thoughts on this. Thanks. cc: @tyxla

**Comment by tyxla** [comment]
Thanks for working to resolve the "Set featured image" issue @Vrishabhsk 🙌
