### ISSUE TITLE
Pattern Import Failure y.values ().find is not a function.

### ISSUE THREAD

**Issue by jasperf** [WordPress/gutenberg#65347]
### Description

I exported my WordPress block pattern, tried to import the pattern on other WordPress site and got this error:

```
y.values ().find is not a function. (In 'y.values).find ((e=>e.name===n)); 'y.values().find' is undefined
```

I validated the JSON at https://jsonlint.com/ and it is valid. File to be checked is here https://gist.github.com/jasperf/4747e963fc84871ea6f3482ddf37381e I added the [custom line block](https://github.com/wpvillain/line-block) it is  used as must-use plugin as well as the [cover filter](https://github.com/wpvillain/cover-filter) and with those deactivated still the same error on import. This is a major problem for me.

Worked on this menu pattern for a long time and I need to be able to export it. Using it locally and synch one used on a page with the actual pattern and that works well. But I need to be able to use it elsewhere. 

**NB** Also tried pattern with cover part turned into group https://gist.github.com/jasperf/f062895598240a4c4704e7b15057456f . But still same error

### Step-by-step reproduction instructions

1. go to patterns
2. import pattern json from https://gist.github.com/jasperf/4747e963fc84871ea6f3482ddf37381e
3. see error `(In 'y.values).find ((e=>e.name===n)); 'y.values().find' is undefined`

### Screenshots, screen recording, code snippet

<img width="1059" alt="Screenshot 2024-09-14 at 10 56 27" src="https://github.com/user-attachments/assets/caaa2808-05b8-47cb-b854-4121ec63facd">

### Environment info

macOS Sonoma, Safari 17.6, WordPress 6.6.2, PHP 8.2.15

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by jasperf** [comment]
I just tried import using the latest Chrome Version 128.0.6613.138 (Official Build) (arm64). And there import does work. Tried a few versions of the file. Only lose the custom fonts set but import location only uses basic Twenty Fourteen theme so makes sense.

**Comment by backit** [comment]
same here!! firefox 130.0.1 on linux ubuntu, wp 6.6.2

**Comment by ntsekouras** [comment]
I tested in both 6.6 and 6.7RC and could import the pattern without errors..

Noting though that I hadn't installed the line block.. I'm not sure if that would create some errors on parsing.

**Comment by jasperf** [comment]
@ntsekouras perhaps it has to be in tandem with the custom line block. Also, you did test on Safari, correct?

**Comment by ramonjd** [comment]
This bug was addressed some time back:

- https://github.com/WordPress/gutenberg/pull/64123

I retested with Gutenberg and without on Core trunk and couldn't replicate in Safari, Firefox or Chrome. 

I can confirm however that the bug is present in WordPress 6.6.2.

![Image](https://github.com/user-attachments/assets/77eb69c0-2f3e-47e6-8de8-2938d6da78eb)


So the verdict is that https://github.com/WordPress/gutenberg/pull/64123 didn't make it in time for the WordPress 6.6 release, which occurred on July 16, 2024, or any of the subsequent maintenance releases.

[WordPress 6.7 has been released](https://wordpress.org/news/2024/11/rollins/) and it contains the fix.

I'll close since the fix has made it to Core.
