### ISSUE TITLE
Zoom out view: Device preview button doesn't work when zoom out view is enabled

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#65411]
### Description

The device preview button is not clickable when the experimental zoom out view is enabled.

From my understanding, when the zoom out view is enabled, one of the following is the expected behavior:

- Disablethe device preview dropdown
- Turn off the zoom out mode when the device preview button is clicked

### Step-by-step reproduction instructions

- Enable "Zoom out experiments" on the Gutenberg Experiments page
- open the post editor
- Click the Zoom out mode button
- Click on Tablet or Mobile in the Device Preview dropdown

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/1190949b-a452-4edf-8b3c-0d3c0b22c768

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by AhmarZaidi** [comment]
Hey @t-hamano 👋,
I'd like to work on this issue.

I think this approach gives a more seamless experience:

> * Turn off the zoom out mode when the device preview button is clicked

To address this, we can modify the device type selection handler to turn off the zoom out mode before setting the new device type.
https://github.com/WordPress/gutenberg/blob/5f77458225b0ce1d4e5fdb2b1113a374d8bed189/packages/editor/src/components/preview-dropdown/index.js#L116

This can be done using:
```
import { store as blockEditorStore } from '@wordpress/block-editor';

const { __unstableSetEditorMode } = useDispatch( blockEditorStore );
const zoomOutExperimentEnabled = window.__experimentalEnableZoomOutExperiment;

if (zoomOutExperimentEnabled) {
    __unstableSetEditorMode( 'edit' ); // Turn off zoom out mode.
}
```

This will make sure that the zoom out mode is disabled when a user selects a device type from the preview dropdown.

---

Screen recording:

https://github.com/user-attachments/assets/fb3ea21a-797f-492a-8e7d-49b20281526a

**Comment by draganescu** [comment]
Is the best way to go here to
- hide/disable the device preview handle when zoomed out
- exit zoom out when changing device preview

Ideally "exit zoom out when changing device preview" so that we keep a fluid overall experienc, but I find it confusing that only desktop can be zoomed out and also, so when zoom out is engaged the device preview should have no active element.

**Comment by draganescu** [comment]
@AhmarZaidi @t-hamano can you help me and test out #65444 - given #65404 made the control universally available I rushed a fix for this one. 🙇🏻

**Comment by AhmarZaidi** [comment]
@draganescu I was about to make the same changes except for a check for `window.__experimentalEnableZoomOutExperiment;` which wouldn't be necessary now since it will be universally available.

Added a comment related to documentation [here](https://github.com/WordPress/gutenberg/pull/65444/files#r1764905621). 

Please feel free to ignore it if it's not necessary.
I think it's good to go.
