### ISSUE TITLE
Composite: Doesn't work when `render` is a `Tooltip`

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#65615]
Composite does not correctly manage roving tab index when `Composite.Item`'s `render` prop is a `Tooltip`. For example, when you have a composite item like this:

```jsx
<Composite.Item
  render={
    <Tooltip text="Tooltip">
      <button>Button</button>
    </Tooltip>
  }
/>
```

The workaround is to wrap the `Tooltip` around the `Composite.Item`:

```jsx
<Tooltip text="Tooltip">
  <Composite.Item render={<button>Button</button>} />
</Tooltip>
```

This problem does not manifest when the `Tooltip` is used internally in a component, like:

```jsx
<Ariakit.CompositeItem
  render={
    <Button label="Tooltip" showTooltip>
      Button
    </Button>
  }
/>
```

The problems reproduce in raw Ariakit Composite ([sandbox demo](https://stackblitz.com/edit/vitejs-vite-odmgdv?file=src%2FApp.tsx)).

## What is your proposed solution?

These may be limitations that don't necessarily need to be fixed, but we should at least document the workarounds.

**Comment by diegohaz** [comment]
Interestingly, if you click on the tooltip popup and press the left or right arrow, the focus moves to the previous or next composite item 😄

That's because the tooltip popup element is the one receiving the props and event listeners:

https://github.com/WordPress/gutenberg/blob/88d60e4f64b2391ba9e2965a721ade86aec0809b/packages/components/src/tooltip/index.tsx#L130-L131

While the anchor element receives the forwarded ref prop, so it is correctly registered as the composite item element.

---

> The workaround is to wrap the `Tooltip` around the `Composite.Item`:
> 
> ```js
> <Tooltip text="Tooltip">
>   <Composite.Item render={<button>Button</button>} />
> </Tooltip>
> ```

I'd say that's not just a workaround, but the proper way to use it given how `Tooltip` works. Personally, I'd just do `render={<button />}` and then pass `Button` as direct child of `Composite.Item`. Alternatively, you can also use the function version of the render prop to pass the props to the correct element (if, for some reason, you're unable to wrap `Composite.Item`):

```jsx
<Composite.Item
  render={(props) => (
    <Tooltip text="Tooltip">
      <button {...props}>Button</button>
    </Tooltip>
  )}
/>
```

Or:

```jsx
<Composite.Item
  render={(props) => (
    <Tooltip text="Tooltip">
      <button {...props} />
    </Tooltip>
  )}
>
  Button
</Composite.Item>
```

**Comment by mirka** [comment]
Thanks @diegohaz! We'll just update the documentation then.

**Comment by ciampo** [comment]
Opened #65817 to add a dedicated Storrybook example
