### ISSUE TITLE
Don't render tools control when getRenderingMode is set to post-only

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#65678]
The write and design tools selection UI is relevant when editing content like blog posts. The tools are most helpful in the context of templates. I propose the control is not rendered if `getRenderingMode()` is set to `post-only`. 

In trunk, this condition can be set via the Inspector's Template control, by choosing to change the template display with the "Show template" option (in both the post editor and site editor). 

### Tools UI
![CleanShot 2024-09-25 at 17 58 26](https://github.com/user-attachments/assets/cf9207f3-e8ed-40eb-8e2a-4142e16db93f)

### Showing and hiding a template with getRenderingMode
![CleanShot 2024-09-26 at 09 28 52](https://github.com/user-attachments/assets/a0097fc7-516f-4f85-adf2-6edf8c1ddfcb)

Ideally the UX for showing and hiding a template should be clearer (not buried in the Inspector). I'll open another issue to push that forward.

**Comment by draganescu** [comment]
Should we instead of hiding the control, switch out of post only if design is selected? Isn't that more fluid than disappearing UI elements?

It does conflict a bit with the saved pref thing - going the route I suggest above would mean that once you set design mode then all posts will be in template mode until you switch back to write mode. But I still think this is an easier thing to handle than hiding the control based on a settong in a list of settings in a tab in the inspector.

**Comment by richtabor** [comment]
Closing in favor of https://github.com/WordPress/gutenberg/issues/66775 (its more detailed/more current).

**Comment by richtabor** [comment]
> It does conflict a bit with the saved pref thing 

Yea, that's my hesitation there. I'm also aware of users accidentally triggering "Write" mode when the template is not previewed, resulting in a challenging experience.
