### ISSUE TITLE
Scaling not one to one when zooming out

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#65757]
The blocks within the canvas are not quite scaling properly when zooming out. 

Taking a look at the recording below, you'll see the space between the site title and the navigation does not maintain and text is reflowing in the columns below. 

https://github.com/user-attachments/assets/c28dcd0d-d148-4369-a5d8-dc901c928c1e

**Comment by ndiego** [comment]
I can confirm, and this does appear in 6.7 nightly, so I am adding it to the board.

**Comment by getdave** [comment]
Related:

https://github.com/WordPress/gutenberg/issues/64117
https://github.com/WordPress/gutenberg/pull/61465
https://github.com/WordPress/gutenberg/pull/63390

**Comment by talldan** [comment]
From what I can tell it's because of the border style here:
https://github.com/WordPress/gutenberg/blob/8477a6184055c3c8a62c77af354826645dcaf351/packages/block-editor/src/components/iframe/content.scss#L41-L43

Here's a video of it being toggled on and off:

https://github.com/user-attachments/assets/006ab8fe-2c72-4915-929b-835cc45c4151

I haven't managed to work out a good alternative that retains the space around the canvas in the way the border does.

**Comment by richtabor** [comment]
>  // Firefox and Safari don't render margin-bottom here and margin-bottom is needed for Chrome 

Is this valid? There’s no other way around this?
