### ISSUE TITLE
Global Styles: Unnecessary vertical scrollbar appears

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#65825]
### Description

**Note: This issue cannot be reproduced in WP6.7 Beta 1. It can be reproduced in the latest Gutenberg.**

A vertical scrollbar may appear in global styles even when the content does not need to scroll vertically.

This issue seems to occur when there is a `RangeControl` at the end of the content. You can see that the tooltip that appears when operating the slider overflows:

![image](https://github.com/user-attachments/assets/dd7723c9-ed4d-449c-8083-911aef5b5f1a)

The tooltip is there even though it is not visually visible, which is why the overflow appears to occur.

### Step-by-step reproduction instructions

The easiest steps to reproduce this issue are:

- Activate any block theme.
- Go to the site editor.
- Open the Global Styles > Typography > Font size presets > Click "Add font size" button
- Click "New Font Size 1" item > Enable both "Fluid typography" and "Custom fluid values".

The steps above will render a RangeControl component at the end of your content, which should allow you to reproduce the issue.

You may also need to change your scrollbar display settings to reproduce this issue on a Mac.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/fd5aac13-bef7-402f-be9d-bf3654209f45

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by ciampo** [comment]
While https://github.com/WordPress/gutenberg/pull/65522 surfaced this glitch, I believe that the root cause has always been there and is somehow related to some screen content overflowing on the x axis.

It looks like it could be somehow related to the range control that gets displayed when toggling the "Custom field values" control:

https://github.com/user-attachments/assets/77c29333-5a65-4efe-af58-e9ec99469173

Setting `overflow: hidden` on `RangeControl` seems to remove the scrollbar.

We should investigate a bit more to understand if effectively that's the root cause, and if that's the case, find out exactly which part of `RangeControl` is overflowing

**Comment by t-hamano** [comment]
> Setting `overflow: hidden` on `RangeControl` seems to remove the scrollbar.

This approach will result in parts of the tooltip and slider being cut off:

![Image](https://github.com/user-attachments/assets/9863cec4-976b-4f53-aa31-0ef04f69c3c9)

I think the cause is the presence of an invisible tooltip:

![Image](https://github.com/user-attachments/assets/1b045fae-dd8b-45c5-871c-fae79c3e374b)

What do you think about adding bottom padding to the screen? A value of `11px` or more seems to eliminate the overflow:

https://github.com/user-attachments/assets/eecafa3c-011b-407e-a217-8bc35013d6aa

**Comment by ciampo** [comment]
> This approach will result in parts of the tooltip and slider being cut off

Absolutely, that shouldn't be the fix. It was just a hint about where to look for the cultipt :) 

> I think the cause is the presence of an invisible tooltip:

Let me timebox an effort to see I can fix this properly.

**Comment by ciampo** [comment]
Proposed fix in #65875
