### ISSUE TITLE
Fix: add embed block descriptions to translation files

### ISSUE THREAD

**Issue by RobinRoelofsen** [WordPress/gutenberg#6590]
## Issue Overview

Just noticed that no embed block descriptions are in the translation files. Checked multiple languages, nowhere to be found. 
## Steps to Reproduce (for bugs)

1. go to https://translate.wordpress.org/projects/wp-plugins/gutenberg
2. select a language and click on eithe rdevelopment or stable
3. search for twitter or youtube

**Comment by ocean90** [comment]
The name is a placeholder that's why a search for both terms will not return a result. But the string for the description is actually there: https://translate.wordpress.org/projects/wp-plugins/gutenberg/dev/nl/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=6028146&sort%5Bby%5D=translation_date_added&sort%5Bhow%5D=asc.

**Comment by RobinRoelofsen** [comment]
Aha! Thanks. I did translate this line two days ago, it's just not in the
latest version yet, so it still showed up in English.

Op zo 6 mei 2018 13:26 schreef Dominik Schilling <notifications@github.com>:
