### ISSUE TITLE
Device preview button should be disabled in the pattern/template part editor

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#65931]
### Description

Device preview conflicts with resizable editors. If an editor is resizable, device preview should be disabled.

Specifically, the pattern editor/template part editor i**n the site editor**.

In WordPress 6.5, the device preview button was disabled, as shown in the screenshot below:

![Image](https://github.com/user-attachments/assets/bdcfea1c-a70d-41c5-ab3e-53b838b7621c)

This issue appears to have been present since WordPress 6.6.

### Step-by-step reproduction instructions

- Open the site editor.
- Open any template part or pattern.
- Switch to mobile view.
- The resizable editor becomes squashed and nearly inoperable.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/5abdbea3-d625-4c87-8e31-f71d7a37264b

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

**Comment by t-hamano** [comment]
After some investigation, it appears this issue occurred in #61273.

**Comment by draganescu** [comment]
It occured to me that the device preview for resizeable editors is basically setting presets for the editor size - or so it should. E.g. why shouldn't I be able to preview my header on a mobile viewport, and why for patterns, template parts or mobile menus I have to manually resize to tablet, when even _is_ tablet ...?

**Comment by t-hamano** [comment]
Perhaps the ideal specification would be for the device preview and the resizable editor to be "synchronized." This has been mentioned in the past in [this comment](https://github.com/WordPress/gutenberg/pull/53913#issuecomment-1694667942):

**Comment by draganescu** [comment]
Yes, that seems much better than disabling the control. We should try that I think.

**Comment by draganescu** [comment]
Now that [#65970](https://github.com/WordPress/gutenberg/pull/65970) is merged maybe we need a new issue to go to 

> the ideal specification [...] the device preview and the resizable editor to be "synchronized." 

Also it's my impression that [#65970](https://github.com/WordPress/gutenberg/pull/65970) also falls under the stuff #61622 tries to solve ([basically](https://github.com/WordPress/gutenberg/pull/65970/files#diff-b36330dafd3e1e769316e0d65d01c837dc28a1f52f0b62f663738113eaee2036R91) we check for post type to affect UI).

To undo a new hard coding I've recently tried #66600 which looks for a post type supprt to decide zoom out. In this case here the specification outlined by @t-hamano above is the way to go - makes more sense to [not remove](https://github.com/WordPress/gutenberg/issues/65931#issuecomment-2446526709) the feature ad hoc and also removes the need to check for post types.

cc @andrewserong @tellthemachines

**Comment by andrewserong** [comment]
Thanks for the ping! I like the idea of synchronising them and for the mobile / tablet sizes to be available for folks to set those sizes in the resizable editor. If we do, I think we'll still need some logic to factor in when to show/hide the template preview toggle being proposed in: https://github.com/WordPress/gutenberg/pull/66514 — although that one is now guarded behind a check for `templateId` so it might be fine 🤔

> To undo a new hard coding I've recently tried https://github.com/WordPress/gutenberg/pull/66600 which looks for a post type support to decide zoom out.

In principle I like the idea of making this more generic so that we don't have a hard-coded list. Would part of the value there be so that plugins can register post types that would default to using the resizable editor? As it stands, though, I don't mind the duplication of hard coding things if it's readable. One of the things I quite liked about #65970 is that although it is hard coding things there was a readability improvement for me in looking over that changeset.
