### ISSUE TITLE
Maximum number of nested column blocks?

### ISSUE THREAD

**Issue by stevejburge** [WordPress/gutenberg#6593]
It feels like there should be a maximum number of column blocks. 

At the moment you can have column blocks under column blocks under column blocks. This is what happens when you get 3 levels deep (so the page is divided into 8)

![overlays](https://user-images.githubusercontent.com/3868028/39635156-9d31f964-4f8a-11e8-94a4-cdc276372200.png)

I tried doing a 4th row under that and the overlay elements really started to get crossed-up

![screen shot 2018-05-04 at 10 58 58 am](https://user-images.githubusercontent.com/3868028/39635175-ad58cc82-4f8a-11e8-84b4-f2b73bb64c50.png)

Visually, it seems hard to image how the Gutenberg interface could be kept straight beyond the 2nd or perhaps 3rd level.

**Comment by stevejburge** [comment]
Thanks @SuperGeniusZeb. 

Yes, point taken. I'm not quite sure of the best approach here. 

Still, there's definitely a point at which things go very funky here. Add enough column blocks and the UI quickly becomes unworkable.

**Comment by danielbachhuber** [comment]
Filing against `Merge Proposal: Editor` because I feel like we need a yes / no decision against this:

> It feels like there should be a maximum number of column blocks.

**Comment by mtias** [comment]
There'll be a maximum set by virtue of the slider.

![image](https://user-images.githubusercontent.com/548849/41773748-681ba392-761d-11e8-9e56-96c8b35234b8.png)

What that is in final form remains to be seen.

**Comment by SuperGeniusZeb** [comment]
@mtias That is not what this issue was about. It was suggesting that there be a limit to how many levels of Columns blocks can be nested in each other.

Personally, I see no reason to limit the amount of nesting, since overly deep nesting would usually only occur in cases where the user is messing around and not seriously building a layout, and since the point where nested block UI becomes hard to use varies depending on the editor width set by the theme and the viewport width. Additionally, recent improvements have done a lot to make the UI/UX in nested contexts less confusing, so I think this is already less of a problem than when this issue was created.

**Comment by mtias** [comment]
Ah, sure, I don't think we should be restricting nesting levels.

**Comment by stevejburge** [comment]
Following up on my original bug-report ... the problem seems fixed. I've been trying without success to create the issue on the latest Gutenberg release.

To be honest, the UI also breaks down by the time you get to adding a 3rd nested column block:

![screen shot 2018-06-22 at 12 10 00 pm](https://user-images.githubusercontent.com/3868028/41787083-4f1fa878-7615-11e8-9725-021c839c5973.png)

**Comment by mrpritchett** [comment]
At the fifth level of nested column, the UI is 100% on top of the next column over. So unless we think people are magic, we should be fixing this issue or restricting the level to which blocks can be nested.
