### ISSUE TITLE
Javascript error when editing shadow after resetting styles

### ISSUE THREAD

**Issue by benniledl** [WordPress/gutenberg#65930]
### Description

Similar issue as #65774 exists for Shadows

For details visit #65774 

### Step-by-step reproduction instructions

1. Go to global styles
2. Shadows
3. add an inidvidual shadow
4. click on the individual shadow
5. reset styles
6. edit currently selected shadow

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/d6a622be-572a-4c8c-a286-7901908acd85

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

**Comment by nith53** [comment]
I am also able to replicate this issue.
![Image](https://github.com/user-attachments/assets/c6017bf1-f36c-4759-9683-bb3b7ad39960)

**Comment by ciampo** [comment]
My instinct tells me that this is not the same issue as #65774, since it's not triggered by leaving the shadows screen. I'll timebox an effort and see if I can come up with a fix

I believe the issue is that, when resetting styles, the current shadow entry gets removed. And therefore, and subsequent edit can't be applied (and triggers an error), because it's trying to edit a shadow that doesn't exist anymore in the settings. We should probably just navigate back to the parent screen when resetting styles.

**Comment by ciampo** [comment]
@benniledl @nith53 can you test if https://github.com/WordPress/gutenberg/pull/65935 fixes it? It's a draft for now, but I'm going to add a proper description/screencast in a bit

**Comment by benniledl** [comment]
@ciampo sorry I'm not sure how I can test a gutenberg PR,
How I would test PR's would be do just modify the files via FTP according to the PR. But I think the javascript files of gutenberg are minified in wordpress so I don't know how to modify the gutenberg source and then "build" the files. Could you share a link on how to test?

**Comment by t-hamano** [comment]
> I believe the issue is that, when resetting styles, the current shadow entry gets removed. And therefore, and subsequent edit can't be applied (and triggers an error), because it's trying to edit a shadow that doesn't exist anymore in the settings. We should probably just navigate back to the parent screen when resetting styles.

I think this is correct.

The font size preset implementation relies entirely on the `useGlobalSetting()` hook. Therefore, if we reset the global styles in a custom font size preset panel, a critical error occurs because it references a preset that does not exist.

On the other hand, the shadow panel logic is a little different, and [it keeps the preset obtained via the `useGlobalSetting()` hook in _the state_](https://github.com/WordPress/gutenberg/blob/d6a4c72606d97d4b9e1593cce28f6bf9d5448052/packages/edit-site/src/components/global-styles/shadows-edit-panel.js#L87-L88). So even if we reset the global styles in a custom shadow preset panel, the preset still exists in the state, so no critical error occurs. But of course this is not the intended behavior.

Shadow presets may need to be refactored in the future to not depend on the state, but the approach attempted in #65935 is similar to that of font size presets and I think it makes sense.

**Comment by ciampo** [comment]
> sorry I'm not sure how I can test a gutenberg PR, How I would test PR's would be do just modify the files via FTP according to the PR. But I think the javascript files of gutenberg are minified in wordpress so I don't know how to modify the gutenberg source and then "build" the files. Could you share a link on how to test?

The easiest way to test the changes is to visit https://playground.wordpress.net/gutenberg.html and input the PR number (ie. `65935`).

If you want to run a local version of the code on your machine, you can follow [this documentation](https://github.com/WordPress/gutenberg#developing-for-gutenberg).

**Comment by ciampo** [comment]
> Shadow presets may need to be refactored in the future to not depend on the state, but the approach attempted in [#65935](https://github.com/WordPress/gutenberg/pull/65935) is similar to that of font size presets and I think it makes sense.

Agreed, aki!

**Comment by nith53** [comment]
> [@benniledl](https://github.com/benniledl) [@nith53](https://github.com/nith53) can you test if [#65935](https://github.com/WordPress/gutenberg/pull/65935) fixes it? It's a draft for now, but I'm going to add a proper description/screencast in a bit

Tested via the Playground. The issue seems to be resolved.
