### ISSUE TITLE
Draft auto

### ISSUE THREAD

**Issue by Phoenix13real** [WordPress/gutenberg#6614]
Gutenberg 2.8.0
Last Wordpress version : 4.9.5
Theme : Beaver Builder Theme
Plugins : Beaver Themer, Beaver Builder, Imagify, Gravity Forms, SEO Framework, Code Snippets, Safe SVG, WP Mail SMTP, WP Rocket

Hello, I test Gutenberg …. The problem is this: the title of the page is always the same (Auto Draft). If I change, the title comes back.

Note: what I do in the page does not register. If I preview, nothing is displayed (except Auto Draft)

**Comment by danielbachhuber** [comment]
Hi @Phoenix13real,

Thanks for the report! I'm not quite sure I follow what the bug is. To help clarify further:

1. Can you share a screencast (or GIF) of the problem in action?
2. Can you share the debugging steps you've performed to try to track down the issue? And, on that note, can you try deactivating each plugin one-by-one to see if one of them is the source of the conflict?

**Comment by Phoenix13real** [comment]
hi @danielbachhuber,

I found the **solution** to the problem. In fact, it was a problem with Nginx. Wordpress runs on a Nginx server and the Plesk control panel.

On Plesk (17.8.11) , rewrite rules (for pretty urls Wordpress) : 

-BAD (issue Gutenberg)-

```
rewrite /wp-admin/$ /wp-admin/index.php break;
rewrite /$ /index.php break;
```

-GOOD (perfect for Gutenberg) -

```
	if (!-e $request_filename){
		rewrite ^(.*)$ /index.php break;
	}
```

**Comment by danielbachhuber** [comment]
Glad you sorted it out, @Phoenix13real

**Comment by Jayfrown** [comment]
This recently happened to me too - I could not create pages using the Gutenberg editor, it would change the title to `Auto Draft` and then show a spinning wheel of death apparently trying to save the page. I see no PHP processes taking any CPU time so I don't think it was doing anything.

Saving pages seemed to work, but opening the page reveals no changes, and subsequently re-opening the page in the editor shows that no changes have been saved.

@Phoenix13real is on the right track. The problem appears to occur due to a rewrite (mis)configuration [in nginx].

I use the following configuration to work around out-of-scope broken behavior observed in permalinks - it redirects anything that does not contain a `.` to the same location with a trailing `/`, so `/page` to `/page/` but not `/page.html` to `/page.html/`. It's a fairly common thing I use in most of my vhost configs.

```nginx
        location / {
         rewrite ^([^.]*[^/])$ $1/ permanent;
         try_files $uri /index.php$is_args$args;
        }
```

This somehow breaks saving any page/post in Gutenberg. By simply removing the rewrite rule (and reloading nginx), the problem disappears and I can save pages/posts within the Gutenberg editor just fine. I don't have much other debugging info, but would love to provide it - given someone tells me where to look.
