### ISSUE TITLE
Multiple Scrollbars Appear in Mobile/Tablet Responsive Preview Mode

### ISSUE THREAD

**Issue by dhruvang21** [WordPress/gutenberg#66156]
### Description

When switching to mobile or tablet responsive preview mode in the Gutenberg editor (trunk branch), multiple scrollbars appear on the screen, which creates a confusing and cluttered experience. This issue happens inconsistently but is more noticeable on smaller screen previews.

### Step-by-step reproduction instructions

1. Go to the Gutenberg editor.
2. Switch to either mobile or tablet preview mode.
3. Observe the multiple scrollbars that appear on the screen.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/70016b6b-02b9-4e91-865f-ff72c08caec8

### Environment info

- Gutenberg trunk branch
- Operating System:-  ubuntu
- Browser:  chrome 

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

**Comment by colorful-tones** [comment]
#66176 also seems to address this bug as well.

**Comment by stokesman** [comment]
Thanks to @talldan’s comment https://github.com/WordPress/gutenberg/pull/66176#issuecomment-2419691362, this is known to have regressed by #65977 and since that PR did get backported to 6.7 the issue is present there. I believe that means we can still get a fix in to 6.7 at this point. I’ve opened #66494 for it.
