### ISSUE TITLE
Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 262144 bytes)

### ISSUE THREAD

**Issue by LBeckX** [WordPress/gutenberg#66252]
### Description

I try to count the words of the current page with a gutenberg block.
This is how I try to get the content:

```php
<?php
global $post;
$content = apply_filters('the_content', $posts->post_content);

...

```

But I get the following error:

> Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 262144 bytes) ...

I think this is because the current block of mine also belongs to it and a loop may be generated as a result.

### Step-by-step reproduction instructions

1. Create a fresh block with

```bash

npx @wordpress/create-block@latest copyright-date-block --variant=dynamic

```

2. Go to `render.php`

3. Write down

```php

<?php
global $post;
$content = apply_filters('the_content', $posts->post_content);

```

4. Add the block to a page

5. Reload the site

6. There it is

### Environment info

- WordPress Version 6.6.2
- Gutenberg: Version 19.4.0

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

**Comment by awps** [comment]
Have you tried using the [`do_blocks`](https://developer.wordpress.org/reference/functions/do_blocks/) function? You can also take a look at the source and make your own version by adjusting the `the_content` filter. I think the filter ends up in an infinite loop.

**Comment by Mamaduka** [comment]
Thanks for reporting the issue, @LBeckX!

I would recommend the [`render_block_core_post_time_to_read`](https://github.com/WordPress/gutenberg/blob/413bf9bf423fba3e130f6f08551f0030d499e76d/packages/block-library/src/post-time-to-read/index.php#L16) method, which uses WP's native methods to get the word count for a post and calculate the time to read value.

The bug itself seems to be code-specific. WP or any other framework can't prevent users from introducing infinite loops.

I'm going to close the issue since it doesn't seem actionable on the framework level at the moment.
