### ISSUE TITLE
Resizable Editor: Unintended vertical scrollbar

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#66297]
### Description

In the resizable editor, if there is little content, the vertical scrollbar is not necessary, but it seems to always be displayed.

After investigating this issue, I found that it was caused by the top border added by #66041.

### Step-by-step reproduction instructions

- Open the site editor.
- Open the pattern or template part editor.

### Screenshots, screen recording, code snippet

![Image](https://github.com/user-attachments/assets/61f6dd87-a21a-4d29-ad16-e17546d5e238)

If I temporarily disable the top border this issue doesn't occur:

![Image](https://github.com/user-attachments/assets/01fd0dc1-22ed-4bc3-a2b7-e88084c0f394)

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

**Comment by andrewserong** [comment]
Oh, interesting, good catch!

It seems that the resize observer gives a rounded integer instead of the precise number of the actual size, and this border rule uses sub-pixels, which means we get a height of a resizable editor that is _just_ not tall enough for the content:

https://github.com/WordPress/gutenberg/blob/a90e35b0c4fe34acd87a2b205f66976771121dd2/packages/compose/src/hooks/use-resize-observer/legacy/index.tsx#L65

(I believe we're using the legacy implementation because [useResizeObserver is called](https://github.com/WordPress/gutenberg/blob/9b0f6aa0eba137530c594c442cfa8dca2748c499/packages/editor/src/components/visual-editor/index.js#L109) without passing in a callback).

So, I'm not sure if this is the right way to fix it, but it seems like we could always add `1` to the height in the visual editor to ensure that the height accounts for the border. Would that be a terrible approach?

```diff
diff --git a/packages/editor/src/components/visual-editor/index.js b/packages/editor/src/components/visual-editor/index.js
index 8ad9ce7fc97..fe261fed4b7 100644
--- a/packages/editor/src/components/visual-editor/index.js
+++ b/packages/editor/src/components/visual-editor/index.js
@@ -380,15 +380,17 @@ function VisualEditor( {
 					'is-iframed': shouldIframe,
 				}
 			) }
 		>
 			<ResizableEditor
 				enableResizing={ enableResizing }
 				height={
-					sizes.height && ! forceFullHeight ? sizes.height : '100%'
+					sizes.height && ! forceFullHeight
+						? sizes.height + 1
+						: '100%'
 				}
 			>
 				<BlockCanvas
 					shouldIframe={ shouldIframe }
 					contentRef={ contentRef }
 					styles={ iframeStyles }
 					height="100%"

```

I can throw that up in a quick PR if it helps.

**Comment by andrewserong** [comment]
Opened a PR in https://github.com/WordPress/gutenberg/pull/66301 — happy to close it out, though, if there's a better fix!

**Comment by stokesman** [comment]
Another day, another PR #66390 targeted to fix this.

**Comment by andrewserong** [comment]
> Another day, another PR https://github.com/WordPress/gutenberg/pull/66390 targeted to fix this.

Thank you @stokesman, I appreciate your persistence here! 🙇
