### ISSUE TITLE
IE11 blank page and JS error

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#664]
Noticed while testing https://github.com/WordPress/gutenberg/pull/578

At the moment, in IE11 all you get is a blank page and a JS error `Object doesn't support property or method "from"`.

![screenshot 87](https://cloud.githubusercontent.com/assets/1682452/25715624/62e99f94-30fc-11e7-8f51-fcdf0b5f21e3.png)

**Comment by aduth** [comment]
@iseulde It appears this error is occurring in your `dom-react` package because `[ ...arr ]` spread syntax expects `Array.from` to be defined. You can see it a few lines down in the source in `_toConsumableArray`:

https://unpkg.com/dom-react@2.1.0

To fix, you should just need to include Babel's runtime transform which substitutes a `core-js` polyfill by default:

https://babeljs.io/docs/plugins/transform-runtime/

Otherwise you could use ES5-isms like:

```js
Array.prototype.slice.call( nodeList )
```

https://github.com/iseulde/dom-react/blob/e57605e/index.js#L114

```
accumulator.push.apply( accumulator, child )
```

https://github.com/iseulde/dom-react/blob/e57605e/index.js#L118

```
createElement.apply( null, [ type, props ].concat( children ) )
```

https://github.com/iseulde/dom-react/blob/e57605e/index.js#L153

**Comment by iseulde** [comment]
@aduth How is it done for this package?

**Comment by aduth** [comment]
We use the runtime transform:

https://github.com/WordPress/gutenberg/blob/17a7a88/.babelrc#L28
