### ISSUE TITLE
Add support for "more" dropdown for additional tools in Write mode

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#66455]
When writing in contentOnly mode, selecting an image block will render tools for adding a link, adding alt text, and adding title text (if there is title text present on the block already. This proposal here is oriented towards keeping the "Write" tooling simple and intuitive, leveraging the existing "More" down caret employed within text blocks, for additional controls. 

This way we can continue flexing content blocks within Write mode, without introducing further complexity. 

### Visuals

Let's start with the Image block, moving the "Alternative text" control inside this more menu, as well as surfacing the "Title" control, instead of having it only render when a title exists previously. 

![Image](https://github.com/user-attachments/assets/74ef0b23-7c55-4b76-9192-f4f090010884)

![Image](https://github.com/user-attachments/assets/f6d32a35-48cd-47eb-bb4e-b80a052a5811)

### Requirements 

- Provide a mechanism for write mode block controls to be defined within a more menu. 
- When a block control in the more menu is engaged, it should be active in the toolbar and complete its associated action. For example, the "Alternative text" control engages the popover with the control for modifying the alternative text. 
- Modify the image block's write mode block controls as a basis for this effort.

Related to #66054 and #66116. 

Edited by @richtabor

**Comment by ntsekouras** [comment]
I opened a [draft PR ](https://github.com/WordPress/gutenberg/pull/66605/)to get some feedback, but I don't think the approach we have already started is scaleable. There are too many conditional display of controls and I'm not sure how we could abstract this. Maybe with declarative controls and DataForms in the future?

**Comment by t-hamano** [comment]
One idea I have is to always place the two items inside the More dropdown, and if data exists, apply the pressed state:

https://github.com/user-attachments/assets/8e49f0be-7a95-430e-862d-3da90e727de5

However, I think the problem is that there is no space between the two items when both data exists:

![Image](https://github.com/user-attachments/assets/c98a4e85-8ddd-4527-b068-755204bc3561)

Of course, we can inject space between the two items by using the `VStack` component or something, but that might break the consistency with other dropdowns.
