### ISSUE TITLE
WP 6.7RC-1: wp.mediaUtils.uploadMedia no longer returns Promise

### ISSUE THREAD

**Issue by elzadj** [WordPress/gutenberg#66551]
### Description

Hi all! 

We were testing our plugin on WordPress 6.7RC-1, and noticed that our media uploader no longer works. Managed to track it to the differences in wp.mediaUtils.uploadMedia between 6.6.2 and 6.7RC-1.

We use this simple code for tests (based on the [readme](https://github.com/WordPress/gutenberg/blob/648c458ac16188ca505bf9b04a2388b941fe9c62/packages/media-utils/README.md) ): 

``` 
wp.mediaUtils.uploadMedia( {
	filesList: [ new File( [ 'foo' ], 'foo.txt', { type: 'text/plain' } ) ],
	onFileChange: ( [ fileObj ] ) => console.log( fileObj ),
	onError: console.error,
} );
```
Compare the results between versions: 

6.7RC-1: 
![Image](https://github.com/user-attachments/assets/bcf845e9-db25-4f15-8231-209fb8a988e6)

6.6.2:
![Image](https://github.com/user-attachments/assets/4a3b0aa8-f13d-454a-a61a-840108912746)

We can adjust code in our plugin to make it work on both versions, but would be nice to know if this change was intentional.
Thanks.

### Step-by-step reproduction instructions

1. Update to 6.7RC-1
2. Open Gutenberg Editor.
3. Run 
``` 
wp.mediaUtils.uploadMedia( {
	filesList: [ new File( [ 'foo' ], 'foo.txt', { type: 'text/plain' } ) ],
	onFileChange: ( [ fileObj ] ) => console.log( fileObj ),
	onError: console.error,
} ); 
```

in your console.
4. Check the result.

### Environment info

- WordPress 6.7RC-1
- Chrome Version 130.0.6723.58 (Official Build) (64-bit)
- Ubuntu 24.04.02

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by Mamaduka** [comment]
@swissspidy, could this be related to the recent changes made to this utility method?

**Comment by swissspidy** [comment]
Yes. This was introduced in #64784.

Previously, it was an async function (thus returning a Promise with a `void` return value) because it uploaded files in a `for` loop with an `await` in it. That means all uploads were done in sequence, which is inefficient.

As part of the conversion, this was changed to use `Array.prototype.map` so the uploads are queued in parallel. That also meant there was no longer a need for the function to be `async`.

Note: awaiting `uploadMedia()` was never useful anyway, because it never returned anything. It solely relies on the `onFileChange` and `onError` callbacks. The readme also doesn't suggest using `await`.

I'm curious to learn why your code doesn't work anymore, since there is no return value. It sounds like you might have just relied on the coincidence that `onFileChange` or `onError` is called on the next tick in the event loop as soon as the Promise settled, instead of relying on the callback functions.

A short term fix would be to make `uploadMedia` `async` again, but that won't help you in the future, where files will first be processed in the browser in a queue-like system before sending them to the server (see #61447). So I'd advise against that.
