### ISSUE TITLE
Active menu item resembles a primary button

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#66554]
One of these blue elements is not like the others :)

<img src="https://github.com/user-attachments/assets/7982b0e5-d2ae-4d79-8561-696b0f60307e" width="600">

Let's explore alternative ways to indicate the active menu item that do not visually overlap with the primary button component, and does not draw an inappropriate amount of visual attention.

**Comment by jasmussen** [comment]
The simplest option that comes to mind, and perhaps worth trying in a PR, is gray active-state color. In principle, the pure white color exceeds the needed 3:1 contrast ratio of active vs. inactive states, but if additional emphasis is desired, making the active-state text semibold (same font-weight as "A new draft" title), that would add a shape change in addition to the color contrast.

**Comment by jameskoster** [comment]
Yup I don't mind that, but ideally the hover/active states have clear visual distinction. It's a bit tricky given the grays we have to work with at the darker end of the scale. We might have to remove the background on hover?

<img src="https://github.com/user-attachments/assets/f851ba48-86e4-4bf2-a7ac-ede14a9dd8f9" width="300">

**Comment by danielvann777** [comment]
If we remove the background on hover does that mean for someone with limited vision the hover/regular states have no distinction? (except for the cursor change)

**Comment by jameskoster** [comment]
Good question. My instinct is that it doesn't make any difference because the contrast between the sidebar and menu item backgrounds is minimal. And like you say, the cursor (and focus ring) is an additional affordance.

However, the difference between hover / active may not be adequate; an additional 'shape change' may be required. Options could be; increased font weight on the active item, or an additional shape (similar to wp-admin).

| Increased weight | Additional shape |
| --- | --- |
| ![Image](https://github.com/user-attachments/assets/0109371c-7dd6-4ab3-bc70-fe1dfcd200b8) | ![Image](https://github.com/user-attachments/assets/985955e9-79dc-46c8-980f-70583a2e8fec) |

**Comment by danielvann777** [comment]
I kinda like the second one better. I'm usually not a big fan of weight change on hover, although this is a very personal preference. We could also just move a few px to the right on hover to indicate it's been engaged. This is probably something best decided with the wider system context though.

**Comment by jameskoster** [comment]
The weight would only change for the _selected_ state, agree that can be trick to get right though. 

Subtle indentation on hover sounds like a good idea to explore too, with animation for folks who don't prefer reduced motion.

Edit: quick mockup:

<img src="https://github.com/user-attachments/assets/8ea8b5a5-92c0-41c3-b55d-b94b2b230a64" width="300">

**Comment by richtabor** [comment]
> We might have to remove the background on hover?

I think that'd be fine to try, before animating or introducing other shapes.

**Comment by ptesei** [comment]
I agree with @jameskoster from the accessibility point of view, adding an extra element of distinction is a best practice. And also it will look familiar to the "legacy" users ^^
I'm not a big fan of font weight changes because it changes the width of the text and in some cases with long titles can cause the text to wrap on multiple lines.

![Image](https://github.com/user-attachments/assets/ddcb9ae1-04f3-45cd-ae51-643d09cac83c)

![Image](https://github.com/user-attachments/assets/e16d189a-905c-4685-b8e5-3eeffb06dda1)

Here some A11y guidelines: 

https://www.w3.org/WAI/WCAG21/Techniques/failures/F73
Check that each link in the page that is identifiable by color (hue) is visually identifiable via some other means (e.g., underlined, bolded, italicized, sufficient difference in lightness, etc).

https://accessibility.huit.harvard.edu/technique-accessible-current-page-indication
So it's important to use an additional means to differentiate the "active" link. One way would be to provide an additional underline.



The other approach is to go in the opposite direction. In the gurenberg UI many selected items look like buttons. 
For example:
- current selected block
- current content
- current style
![Image](https://github.com/user-attachments/assets/65d7148c-f9ab-4b76-a75a-dacb46230a47)
![Image](https://github.com/user-attachments/assets/2c858ecd-e544-497e-bdee-af50cb736093)


So for consistency we could simply switch the save button to outline 
![Image](https://github.com/user-attachments/assets/65bed051-e423-4d01-b57f-d568cbffeda9)

**Comment by jasmussen** [comment]
The left border does not match any other pattern the editor uses, so I would not support doing that. Semibold text can work well and is common practice in similar cases. Though it's important to note that this is not an accessibility issue, because on _color alone_, the active menu item currently has more than 3:1 contrast ratio with inactive items, making it pass contrast checks.

**Comment by joedolson** [comment]
I'm inclined to agree that there is no accessibility issue here; having two components look visually similar isn't an accessibility issue. As long as the end result still meets accessibility expectations, I don't have any specific concerns. The suggestions seem sound.
