### ISSUE TITLE
Revisions: Fix focus ring on the item container

### ISSUE THREAD

**Issue by jarekmorawski** [WordPress/gutenberg#66642]
Hi there! I noticed the focus ring in the Revisions panel is on each item's upper part instead of the whole container. I understand it's structured this way to make it easy for users to navigate to the `Apply` button using the keyboard, but the whole item is a button and as such should probably be highlighted.

![Image](https://github.com/user-attachments/assets/2994d08c-8783-4316-87b3-e03fa374c024)

**Comment by ramonjd** [comment]
Thanks for reporting. 

This is due to there being two focusable buttons for each revision item: one to load the styles in the preview, and one for the Apply button. The border is from the former.
 https://github.com/WordPress/gutenberg/blob/4e6bd4dbe1f07a2f17b685c697f05db7f697f72d/packages/edit-site/src/components/global-styles/screen-revisions/revisions-buttons.js#L164-L164

Buttons can't be nested, so the were placed next to each other.

Citing @jasmussen 

>  it’s the “button” that lets you select that particular revision ... I’d also think it the better experience to surround the whole container

So we can try to make the list items focusable when navigating between list items, and then the buttons themselves would be tabbable children (?). 

Anyway, I'm sure there'll be a way... 👍🏻

**Comment by ramonjd** [comment]
Added to the general group of follow up tasks too: https://github.com/WordPress/gutenberg/issues/60450

**Comment by ramonjd** [comment]
I'm not sure if I'll get time to work on this anytime soon, but I had a quick play around adding the following props to the list elements:


```jsx
						tabIndex={ 0 }
						onKeyDown={ ( event ) => {
							if ( event.key === 'Enter' ) {
								onChange( revision );
							}
						} }
```

With active/focus styles on them it works as I'd expect, but there are some accessibility concerns, primarily making assigning a keyboard listener to a non-interactive element.
