### ISSUE TITLE
List View: automatically update after switching between Write and Design modes

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#66802]
If you open the Site Editor with Design mode enabled, open list view, and then switch into Write mode, the List View shows that blocks are locked. If you then refresh the page or enter/return, you'll then see when you open List View with Write mode enabled a much simpler view: 

https://github.com/user-attachments/assets/1203fafc-c9dd-44b6-b957-d882e556ed3c

List View when you first turn on Write mode:

![Image](https://github.com/user-attachments/assets/842da412-dc6f-43ac-b6bc-cb5614b2fcd4)
 
List View when you leave Write mode on and either refresh or exit/return:

![Image](https://github.com/user-attachments/assets/04918f73-f4f4-4642-8916-7e6682f71f18)

Note that you will see this bug in the video above: https://github.com/WordPress/gutenberg/issues/66463 That's a separate issue from what's being described here around the role and display of List View. I am marking this as a bug for now.

**Comment by tanjoymor** [comment]
The following video further demonstrates and explains the problem caused with the List View when switching between Write and Design mode:

I cannot get any version of this video to "upload" here so including the link instead: https://cln.sh/5t7kDlkT (I know we're not supposed to do this, if anyone can get it to upload in another comment I'll delete this link.)

Steps:
1. Open an editor
2. Check that it's in Design Mode and review the structure of the List View
3. Switch to Write Mode - note the locks show up, but the List View doesn't otherwise change
4. Refresh the screen
5. Note that the List View looks completely different now (all the locked design blocks are missing)
6. Switch to Design Mode - it _looks_ like nothing happens
7. Refresh the screen
8. Note that the proper full list of blocks show up again

If any user switches to Write Mode and leaves the editor, when they return they will have to _remember_ to switch back to Design Mode _and_ refresh their screen in order to access the full list of blocks in the proper structure.

Edit: I've only tested in Dotcom Simple and Atomic sites and whatever the current versions are there, which I think is WP 6.6.2 and GB 19.5.1.

**Comment by ntsekouras** [comment]
Hm.. I can't reproduce on trunk. Can someone else test in trunk too? I'll keep digging a bit more though to see if there was a PR that fixed that..

**Comment by jerrysarcastic** [comment]
Noting that I had this issue as well when helping a site owner.  Symptoms are the same as those reported here, but I was not able to get out of Write Mode, despite choosing the option and refreshing the browser window several times.  Ultimately I had to deactivate the Gutenberg plugin on their site so they could proceed.

**Comment by annezazu** [comment]
I can replicate this using [Gutenberg nightly (v-19.7.20241105)](https://gutenbergtimes.com/need-a-zip-from-master/) on WordPress Playground:

https://github.com/user-attachments/assets/f80102f3-6f6e-4299-8d35-5c70a110a927

**Comment by annezazu** [comment]
In testing this PR https://github.com/WordPress/gutenberg/pull/66833 for a different issue, I found this one was also fixed! 

https://github.com/user-attachments/assets/4de3bf1f-79d8-47ba-ac5e-54cc75fa7e18

Closing this out as a result.
