### ISSUE TITLE
Block validation fails for style.color property values not conforming to expected format

### ISSUE THREAD

**Issue by jonmarkhall** [WordPress/gutenberg#6691]
**Describe the bug**
For a custom block with an attribute that has a `property` source coming from a color value in the selected element's style attribute (i.e. the `style.color` property), block validation fails for color formats other than the following: `rgb(255, 255, 255)`. For example, block validation would fail if the element's style attribute has a color property with either of the following values:

- `#ffffff`
- `rgb(255,255,255)` (no spaces between color values)

**Expected behavior**
Block validation should accept CSS color properties specified using any valid format, including hex and RGB. This is necessary for using the ColorPalette control for specifying block color properties since that control returns a hex color value.

**Comment by aduth** [comment]
It's not clear to me why it's not possible to enforce a consistent value to be saved as the style? Why do you need to encode it in a format other than the hex, if that's what `ColorPalette` is expecting?

Not to say it _can't_ be supported, but I'm inclined to discourage the `property` attribute source altogether since it would pose to cause even more issues for server compatibility if ever it was desired to support the sourced attributes on the server. Special-casing specific properties, and specific equivalent value formats of those properties will make the validation increasingly fragile.

**Comment by jonmarkhall** [comment]
@aduth The problem I'm experiencing is that ColorPalette returns a hex color value while validation fails if the property doesn't have an rgb() value. I could convert the value from ColorPalette to rgb() prior to rendering the block but that seems like an unnecessary step. If a consistent format is going to be enforced then ColorPalette should use the format that the validator is expecting.

Are you suggesting we only use dynamic blocks so that attribute values are saved directly rather than extracted from the rendered HTML of the block?

**Comment by aduth** [comment]
No, not necessarily dynamic, just sourced in a way other than from the inline style attribute. It adds a bit of redundancy to the markup with the added advantage of... not using `property` 😄 

So essentially removing the `source`, `selector`, and `property` properties from your attribute definition, and instead allowing the value to be serialized to the comment delimiters (which is the default when no `source` is defined).

**Comment by karmatosed** [comment]
I am going to close this as we focus on phase one. However, it is worth noting any issue can always be reopened.
