### ISSUE TITLE
Replace Star Icon with Pin Icon for 'Pin to Toolbar'

### ISSUE THREAD

**Issue by jayclydeTags** [WordPress/gutenberg#66969]
Currently, the 'Pin to Toolbar' feature uses a star icon to represent pinning a Comment in this case.

![Image](https://github.com/user-attachments/assets/033927b5-9d66-4cae-8932-9f5059f3bddd)

I propose using a pin icon instead, as it more accurately represents the action of pinning.

![Image](https://github.com/user-attachments/assets/47f61dd6-92a4-420f-81b0-41a390a0bd85)

- A pin icon is a more widely recognized symbol for pinning items.
- It would provide a more intuitive user experience.

**Comment by jayclydeTags** [comment]
also remove the extra space here:

![Image](https://github.com/user-attachments/assets/83f49b11-cce0-4d78-abae-3815cad7f59d)

**Comment by Mamaduka** [comment]
cc @WordPress/gutenberg-design

**Comment by jasmussen** [comment]
The extra space definitely seems like a regression. 

Pinning and unpinning seems broken in a few ways for the moment: every single item that _can_ be pinned, should also have an item in the "More" menu, otherwise you can't open it on mobile. That doesn't seem part of the API at the moment, where it seems arbitrary whether a sidebar honors this or not. 

As far as star or pin, I'd still go with star for now. There's a larger question about pinning and unpinning that seems more important to fix in the near term, some larger pieces to improve, so just changing the star isn't going to fix that.

**Comment by t-hamano** [comment]
Regarding the extra space, it was fixed in #66677.

**Comment by Mamaduka** [comment]
Thanks, @t-hamano!

In that case, we can close this issue. As @jasmussen pointed out, changing the Star to Pin icon doesn't improve UX.
