### ISSUE TITLE
Add link button to Verse block toolbar

### ISSUE THREAD

**Issue by SuperGeniusZeb** [WordPress/gutenberg#6696]
## No links in Verse blocks?
The Cover Image, Heading, Image, List, Paragraph, Preformatted, Pullquote, Subheading, Table, and Quote blocks all have the link button in their block toolbars. For some reason, the Verse block currently does not.

## Solution
Add the link button to the block toolbar of the Verse block.

## Related Issues and/or PRs
- #3785
- #5635
- #5880
- #6447 & #6525
- #6673 & #6675
- #6695
- #6697
- #6698
- #6699

**Comment by nfmohit** [comment]
Thanks for creating the issue @SuperGeniusZeb! 

Achieving this'd require a pretty simple change but I'm wondering if the link control was intentionally not included in the "verse" block. I do not see a reason to do so personally though, it could be because I might be missing something. Awaiting some further feedback here from others regarding the link control in the "verse" block.

cc/ @karmatosed @gziolo (sorry to bump but would love to see your feedback here)

**Comment by gziolo** [comment]
@iseulde might be better suited to answer this question than I do :)

**Comment by iseulde** [comment]
@mtias removed the link button: https://github.com/WordPress/gutenberg/pull/1809/commits/bd676b5d91d621e8ee783e84c85b4b7945fd4574#r126746200

**Comment by karmatosed** [comment]
I'm not sure we should add this in, lets close for now and we can always review later.
