### ISSUE TITLE
filterable groups in InspectorControl

### ISSUE THREAD

**Issue by Lovor01** [WordPress/gutenberg#67053]
## Filterable groups

Groups defined in `packages/block-editor/src/components/inspector-controls/groups.js` should be filterable to allow developers adding their extensions (groups) to block sidebar.

**Comment by talldan** [comment]
This issue is a bit sparse, ideally there are some use cases and other details for this kind of extensibility request.

**Comment by Lovor01** [comment]
I agree this is a sparse issue, but I will try to elaborate. If proposition [#59115](https://github.com/WordPress/gutenberg/issues/59115) to add new tabs will be accepted, then mechanism to add groups inside will be needed. Further, it is possible for block author to have needs for another group which still doesn't fit into existing ones. Even core groups which were defined in WP6.2 are now extended with more groups, which means that new groups are neccessary with time. For example, I might need to have somewhere a place for entering configuration JSON, which controls configuration of slider which I am using for a block. Since JSON is long, the best place would be new tab and new group inside this tab. Having this new group will not only have a purpose of better organisation, but provide a way for other extenders to extend my block and add something to this group by using familiar interface:
```jsx
<InspectorControls group="newgroup">
...
</ InspectorControls>
```

**Comment by talldan** [comment]
> If proposition https://github.com/WordPress/gutenberg/issues/59115 to add new tabs will be accepted, then mechanism to add groups inside will be needed.

If https://github.com/WordPress/gutenberg/issues/59115 were solved then there would need to be a way to render stuff in the tab, so that seems like an implicit part of that issue.

Your other mention of a JSON control is still relevant to #59115 since you mention it being in a new tab.

I think I'd suggest adding the requirement of new inspector control groups for the tabs to that issue.

Outside of that, I'm not sure a valid use case for the filterable groups has been described.

> Even core groups which were defined in WP6.2 are now extended with more groups, which means that new groups are neccessary with time.

The groups *are* the extensibility mechanism, and more groups were added to allow core features and plugins to render controls in more places.

**Comment by Lovor01** [comment]
I think this whole issue is part of #59115, and can be moved there, like you said, it is an implicit part of this.

>>  Even core groups which were defined in WP6.2 are now extended with more groups, which means that new groups are neccessary with time.

> The groups are the extensibility mechanism, and more groups were added to allow core features and plugins to render controls in more places.

What I meant by that is that number of groups may increase with time and tool should be given to extender developers (non-core developers) to add additional groups to existing tabs and for new tabs if that is accepted.

I will continue discussion in #59115
