### ISSUE TITLE
Pagination on Blog Home broken

### ISSUE THREAD

**Issue by JBelthoff** [WordPress/gutenberg#67157]
### Description

Greetings,

On a fresh install of WordPress 6.7, in the theme editor I edited the Blog Home and selected "News blog with sidebar" from the Design dropdown.

This causes the pagination to create links like: /?query-44-page=2

The pagination links should be /page/2/

### Step-by-step reproduction instructions

1. Fresh install of WordPress 6.7
2. Import themeunittestdata.wordpress.xml
3. Goto Appearance -> Editor
4. Click Templates
5. Select Blog Home
6. Open the Design on the right sidebar for the template
7. Select News blog with sidebar
8. Visit the home page and inspect the pagination links.

### Environment info

WordPress 6.7 - TwentyTwentyFive

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by carolinan** [comment]
Hi
Is the pagination actually broken? In what way?
Please describe the bug and the expected result in more detail.


As far as I am aware, this URL is used because this design uses multiple query loops. So it needs to use the id of query.

The design described in the issue is from Twenty Twenty-Five, so to reproduce this, we would also need step by step instructions for reproducing the problem with any query loop.

**Comment by JBelthoff** [comment]
So, are you saying anytime there are multiple Query Loops in a page, or design, that one, or more of them, will create links like /?query-44-page=2 rather then /page/2/?

If so, then this is not a bug.

**Comment by JBelthoff** [comment]
Okay, I see. Closing this....
