### ISSUE TITLE
Zoom should be fixed at 100% in admin views

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#67166]
Currently navigating the 'Browse styles' in the site editor zooms out the canvas which feels a bit unexpected / clunky:

https://github.com/user-attachments/assets/d6997778-676f-4718-8239-6174bfb2e70b

**Comment by yogeshbhutkar** [comment]
Hi @jameskoster,

Thanks for reporting this issue. I believe the zoom-out might be intentional to provide a broader perspective when previewing the template. However, I'd be interested in contributing to any design discussions around this feature if they take place as we might need Design Feedback on this to proceed with the corresponding patch.

**Comment by talldan** [comment]
> I believe the zoom-out might be intentional to provide a broader perspective when previewing the template.

I think it was intentional in the main editor experience, but I don't think it was in this mode where the content is already of reduced size.

I've made a PR to fix it anyway (#67190)
