### ISSUE TITLE
Post title: if a name isn't set in the creation process, the page title isn't visible in the editor

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#67539]
Titling this for the Post Title block since it's the same as for the Page Title. Using Gutenberg nightly (Version 19.9.20241203) with WP 6.7.1 and TT5, I found that if I don't name a page when creating one, a post title block is not rendered in the template for me to then edit:

https://github.com/user-attachments/assets/2bae7bdb-1fba-4d89-8d71-1e33d0b8fb7f

**Replication steps**

1. Open Appearance > Editor
2. Head to Pages
3. Add a new page and don't give it a title
4. Notice there's no post title block to edit and name the page.

**Comment by carolinan** [comment]
isn't this expected though? I believe not having the title is something that many users are asking for.

**Comment by t-hamano** [comment]
This looks like a bug to me.

In Twenty Twenty-Five or Twenty Twenty-Four, there is a template called "Page No Title". When you create a new page without a title, somehow this template is automatically applied:

![Image](https://github.com/user-attachments/assets/56cb71c3-df05-4d40-b3a6-7544eb5db01f)

I think creating a page with an empty title is generally when we haven't decided a title yet, and doesn't mean applying a page template that has no title.

**Comment by benazeer-ben** [comment]
Hi everyone,

There is an option in the edit section to rename the page. Using this, you can add the desired name to the page.

I believe this option can be helpful in such scenarios where the template chosen is 'Page No Title'.

Please find the attached video for reference.

https://github.com/user-attachments/assets/bd28c30f-c175-43ec-9520-fce57ff61223

**Comment by t-hamano** [comment]
I found another problem. When creating a page in the site editor, enter the title `no-title`. In TT5 and TT4, the "Page No Title" template is applied. On the other hand, in TT3, a default Page template is applied:

https://github.com/user-attachments/assets/27bc3be8-bee1-425d-bde9-e7ec50b13681

The problem here is that the template applied by default changes depending on the type of template the theme has, or the title when creating a page.

[Here](https://github.com/WordPress/gutenberg/blob/cc5a2b70da24a3aa077a858319b4b127722e8e86/packages/edit-site/src/components/add-new-post/index.js#L32) is the process to create a post, but I don't understand why this behavior occurs.

cc @youknowriad @ramonjd @scruffian

**Comment by carolinan** [comment]
If you have a page with the slug "apple" and a custom page template named page-apple, that template will be used
https://developer.wordpress.org/themes/basics/template-hierarchy/#single-page

The default in WordPress for pages that has no title is not "No title" but "Untitled". My guess is Gutenberg may be using this wrong?

**Comment by t-hamano** [comment]
> If you have a page with the slug "apple" and a custom page template named page-apple, that template will be used

I see, thanks for letting me know. So does that mean that what's reported in this issue is actually the correct behavior?

**Comment by carolinan** [comment]
If users are finding it unexpected, then it is not the correct behavior, even if WP is mapping the template and page slug correctly.

**Comment by t-hamano** [comment]
After further investigation, it seems that the classic editor applies the default template regardless of the title or slug, so the behavior in Gutenberg seems odd:

https://github.com/user-attachments/assets/5779ce36-28eb-40cc-a2ae-5ea2f5cf4783

**Comment by carolinan** [comment]
Is the slug no-title? I think the slug is `page_id=142`?

I did not know that the classic editor even understood HTML templates, they do not have the page header that the PHP templates do.

**Comment by carolinan** [comment]
I was able to find some more time to test this. My suggestion would be to try to always create a unique slug when there is no title, because there could be many more themes with these types of page templates.

**Comment by annezazu** [comment]
Thank you all for digging in here! Just to recap, I don't see this as expected behavior when comparing it to the original add new page flow. I don't always want to title things when getting started and I don't think I'm alone there. I'd expect it would use the default template, unless I manually changed it, as I think it's a big leap for one to expect that not including a title would fully change a set template.

**Comment by ramonjd** [comment]
> The problem here is that the template applied by default changes depending on the type of template the theme has, or the title when creating a page.

As @carolinan mentions, this has been the [default behaviour in Core since 4.7](https://github.com/wordpress/wordpress-develop/blob/8eb8d634095e9b6716e977abd1085bab8d703e6f/src/wp-includes/template.php#L460-L460). 

If Gutenberg wanted to override this, there are filters in [get_query_template](https://developer.wordpress.org/reference/functions/get_query_template/) that could work.


> When you create a new page without a title, somehow this template is automatically applied:

Yeah. It's a bit inconsistent though, as if you create a second page with no title, it uses the default template. 🤔 

Updating the [default title text](https://github.com/WordPress/gutenberg/blob/cc5a2b70da24a3aa077a858319b4b127722e8e86/packages/edit-site/src/components/add-new-post/index.js#L48) (Currently 'No title') doesn't seem robust as there's the possibility of matching with anything you put there.

Maybe we could override default behaviour when creating new pages like this?

**Comment by t-hamano** [comment]
Let me summarize what I understand from this isue.

- I think the issue here is with **custom templates**, not the theme templates that are automatically determined based on the template hierarchy (`page.{html|php}`, `page-{slug}.{htmlphp|}`).
- A theme can have custom templates. In a classic theme, we define `Template Name:` as metadata. In a block theme, we define it in the `customTemplates` field of `theme.json`.
- Twenty Twenty-Four and Twenty Twenty-Five define a custom template called "Page No Title".
- When you create a new post with an empty or `no-title` title via the block editor or site editor, the "Page No Title" custom template is _automatically_ applied in Twenty Twenty-Four and Twenty Twenty-Five.
- This behavior does not occur in the classic editor.

Are these correct?

**Comment by carolinan** [comment]
`page-{slug}` is what is being used for "Page no title".

So when the second untitled page is created  its slug is `no-title-2`: This no longer match `page-no-title`. To do that, the template would need to be `page-no-title-2`.

All the `customTemplates` field in theme.json seem to do is add the readable name. Without it, the templates still exist, but the name is not "pretty", it shows with the slug (I have not tested this for a while).


I still think that, when the page is created, the editor should just avoid using a generic slug and use the post id if the user does not enter a title. What is shown to the user in the title fields can still be a readable label.

**Comment by carolinan** [comment]
And in cases when it is not untitled, but match an existing template, perhaps help the user with a notice?
If the page slug is apple and the page template is page-apple, perhaps tell the user what is happening?
"A matching page template was found, you can change the template in (instructions..)"

Plugins may still rely on this working as it has done, historically.

**Comment by youknowriad** [comment]
I think this auto-matching based on slug behavior is very arguable to be honest, that said, I think we should at least disable it entirely for pages/posts with "empty titles". So my question is why "pages without title" are being assigned the `no-title` slug. I believe they should be assigned some very random/internal temporary slug instead of `no-title` which can be a good slug to assign to a page.

**Comment by ramonjd** [comment]
I think we could safely delete this line:

https://github.com/WordPress/gutenberg/blob/cc5a2b70da24a3aa077a858319b4b127722e8e86/packages/edit-site/src/components/add-new-post/index.js#L48

It will fallback to the default behaviour we see in the post editor, and generate a unique slug using [wp_unique_post_slug](https://developer.wordpress.org/reference/functions/wp_unique_post_slug/) - usually a page with no title will be assigned `$post_id . $suffix` [here](https://github.com/wordpress/wordpress-develop/blob/8eb8d634095e9b6716e977abd1085bab8d703e6f/src/wp-includes/post.php#L5383-L5383)

What do folks think?

**Comment by t-hamano** [comment]
> I think we could safely delete this line:

I think so too 👍

**Comment by ramonjd** [comment]
I'll throw a PR up.
