### ISSUE TITLE
Refactor "Settings" panel of Page List block to use `ToolsPanel` instead of `PanelBody`

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#67932]
Part of #67813 

Convert the "Settings" panel of the Page List block to use the `ToolsPanel` instead of `PanelBody`

**Comment by t-hamano** [comment]
If this block is inside a Navigation block, performing certain operations seems to break the block. Here are the steps to reproduce:

- Activate the Twenty Twenty-Five theme.
- Open any template.
- Attempt to select the Page List block in the Navigation block.
- The block should break.

https://github.com/user-attachments/assets/21311c18-ac78-4b61-b6e3-d22531469ee9

Probably because the `hasVaue` prop is not defined [here](https://github.com/WordPress/gutenberg/blob/6893b2d87910bdc2f1c5dab899f0e352cd774c33/packages/block-library/src/page-list/edit.js#L359-L362). I will reopen this issue to resolve this issue.

**Comment by t-hamano** [comment]
Update: The critical error was resolved in #68076, but ideally the spec for the `ToolsPanelItem` component might need to be changed, as commented [here](https://github.com/WordPress/gutenberg/issues/67813#issuecomment-2544734526).

**Comment by aaronrobertshaw** [comment]
> Ideally the spec for the ToolsPanelItem component might need to be changed, as commented https://github.com/WordPress/gutenberg/issues/67813#issuecomment-2544734526.

In the case of the edit menu button for the Page List block, it shouldn't be being wrapped in `ToolsPanelItem` at all. Doing so will only add a useless menu item to the `ToolsPanel` menu. See this [comment](https://github.com/WordPress/gutenberg/issues/67813#issuecomment-2550739237) for more details.
