### ISSUE TITLE
Editing "Page" is broken for low capability users

### ISSUE THREAD

**Issue by Mamaduka** [WordPress/gutenberg#68053]
Nothing is rendered in the editor canvas when editing pages using a non-administrator user (Editor). The bug doesn't affect WP 6.7. I think this is a regression since #62304.

## Testing Instructions

1. Create a test user with an Editor role.
2. Switch to this user. You can use the [User Switching](https://wordpress.org/plugins/user-switching/) plugin.
3. Open a page.
4. Confirm that the editor canvas is blank.

## Screenshot
![Image](https://github.com/user-attachments/assets/fa9bd91b-27ff-4f3f-a27f-2ddb2cd1349c)

**Comment by Marc-pi** [comment]
confirmed there also 

### Description

Since 19.8, the Editor role gets a blank page only on Page when editing it (it's ok on story)
I tested on 19.9 also, the issue is the same

The solution is to deactivate the gutenberg plugin, to bring back the editing capability to users with the Editor role.

### Step-by-step reproduction instructions

1. Go to a Page, with a profile that has the Editor capability 
2. Edit it
3. the page opens, but with blank content
4. no message in the dev tool (FF or Chrome)

### Screenshots, screen recording, code snippet

_No response_

### Environment info

WP 6.7.1
Gutenberg 19.8 / 19.9
TT4 theme

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by vipul0425** [comment]
Hi @Marc-pi, for now, instead of deactivating `Gutenberg`, you can add the following code to the `functions.php` file in your theme:

```
add_filter(
	'post_type_page_default_rendering_mode',
	function () {
		return 'post-only';
	}
);
```
It will make the content visible for users with editor role.

The issue here is we are not getting any templates in non-admin roles (which seems to be a regression issue ) and in this https://github.com/WordPress/gutenberg/pull/62304 we have set the default rendering mode to `template-only` for pages.

**Comment by Marc-pi** [comment]
yep, i was just reading #62304 to understand what was done, and was about to undertstand i can fix with a filter ;-)
seems there was some discussion recently on it !
thanks for the turnaround !

**Comment by Mamaduka** [comment]
I would recommend using the `register_post_type_args` filter to hotfix the issue. The new filters probably will be removed in #67867.

```php
add_filter( 'register_post_type_args', function( $args ) {
	unset( $args['default_rendering_mode'] );
	return $args;
}, 20 );
```
