### ISSUE TITLE
Show responsive preview icons at the same level as the drop-down menu

### ISSUE THREAD

**Issue by MathieuGodard** [WordPress/gutenberg#68064]
## What problem does this address?
Could we remove a click to modify Gutenberg's responsive display?

## What is your proposed solution?
Remove the drop-down menu, add 4 icons (phone, tablet, desktop and frontend preview). Could this degrade accessibility?

**Comment by Mamaduka** [comment]
Thanks for contributing, @MathieuGodard!

I don't think that's possible at the moment due to the limited space in the document toolbar. However, WP 6.7 also shipped with an extensibility feature (#64644) for a preview dropdown, so more than four items can be in that dropdown.

> Could this degrade accessibility?

It can, and visible labels should be preferred over icons when space and design allow. Users can also enable the "Show button text labels" accessibility setting and "force" editor to show labels everywhere. The design also needs to account for this state.

I'll close this proposal as "won't fix" for now. We can get back to it if there are any significant design changes for the document toolbar.

## Screenshot
![Image](https://github.com/user-attachments/assets/b80972fa-d2ce-488f-a835-9933317c4f4d)

**Comment by MathieuGodard** [comment]
@Mamaduka i understand, you are right. maybe add keyboard shortcuts then? maybe even better. Thanks a lot for your time on WordPress!
