### ISSUE TITLE
Patterns: replace a synced pattern's underlying content (like video blocks) without having to detach first

### ISSUE THREAD

**Issue by arunsathiya** [WordPress/gutenberg#68094]
## What problem does this address?

Synced patterns are convenient as the design customization can be carried over to all the places that the pattern/block's used. But, if there's a need to change the underlying block content, there isn't a way to do that without detaching the pattern, thus losing the sync'd design.

Here's an example where a two columns block is published as a pattern, and when it's reused in another place, the only way to check the underlying content is by detaching:

https://github.com/user-attachments/assets/a5bda049-6b7b-4534-b120-6a6a05f5008e

## What is your proposed solution?

One of these two solutions would be ideal:

- Ability to change the underlying block content without having to detach
- Put the block back together into the same pattern, only if the content changed (**without design changes**)

Or perhaps patterns aren't designed for this use-case, in which case, is there a better way to approach this need?

**Comment by Mamaduka** [comment]
I think this can be combined into #65778.

cc @talldan

**Comment by talldan** [comment]
> Ability to change the underlying block content without having to detach

This sounds like the existing Pattern Overrides feature, the main issue is it doesn't support many blocks yet (it doesn't support video).

There's an intro to the feature here - https://developer.wordpress.org/news/2024/06/an-introduction-to-overrides-in-synced-patterns/

I think @SantosGuillamot and a few others are working on adding support for more blocks, so might be able to give an update of how that's going.

edit: This issue seems to discuss what's needed to support more blocks - #64189
The plan for WordPress 6.8 also mentions unlocking support for more blocks - #67520

**Comment by talldan** [comment]
@arunsathiya Are you happy for this issue to be closed given there are already issues where this is being tracked?

**Comment by arunsathiya** [comment]
Absolutely! Thanks for directing me to those other issues - I'll follow along there.
