### ISSUE TITLE
Multi-line Post title height is too short on load (intermittent)

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#6897]
**Describe the bug**

Couldn't reproduce consistently but _sometimes_ the post title height in Firefox is not correctly calculated, so the post title is not entirely visible.

I guess it has something to do with timings and the speed different browsers load content and execute JS. Worth also checking with other browsers. Regardless, seems the height calculation is not so reliable and some improvements should be considered.

What I often see in Firefox is this:

<img width="740" alt="screen shot 2018-05-22 at 17 00 20" src="https://user-images.githubusercontent.com/1682452/40371695-5ac84ff8-5de3-11e8-9f02-191dbec23169.png">

Them just refreshing the page fixes the title height:

<img width="779" alt="screen shot 2018-05-22 at 17 00 33" src="https://user-images.githubusercontent.com/1682452/40371696-5aebaf34-5de3-11e8-8e0a-805940b5fc61.png">

**To Reproduce**
- as said, doesn't happen consistently
- I'd suggest to empty the Firefox cache first
- then just go in the demo page
- try a few times, navigating away and then navigating back to the demo page
- the length of the content might play a role (increasing JS execution time)

Tested on a macbook pro and Firefox 60.

Worth also considering what might happen on a less performant machine (where the JS execution is likely slower).

**Comment by afercia** [comment]
One that doesn't make the title look cut-off 😉

**Comment by tofumatt** [comment]
> What improvements would you suggest?

It's okay to file an issue without an accompanying solution; we shouldn't make folks feel like they need to both file the issue and present the fix 😄

**Comment by tofumatt** [comment]
I was able to get this to reproduce but it is intermittent (so probably some kind of race condition).

On macOS it helped to throttle down Firefox's Web Content process using AppPolice.

I had to load the page about a dozen times in Firefox 61, but eventually it did happen.

**Comment by mcsf** [comment]
@afercia, is the issue still reproducible?

**Comment by afercia** [comment]
@mcsf I still can reproduce it, randomly. I've noticed it's easier to reproduce in Firefox after clearing the browser's cache. It happens also on Windows, randomly. Even when it works correctly, on Windows  there's a "jump" when the page loads that is always noticeable and unfortunately seeing a big Windows scrollbar in the title block is not that great:

![screenshot 39](https://user-images.githubusercontent.com/1682452/42953555-00a56d24-8b7b-11e8-9809-dbfa71902af7.png)

**Comment by designsimply** [comment]
Closed #8930 as a duplicate and noting that they tested with:

<blockquote>Safari 11.1.2
Mac OS 10.13.6
Screen Resolution 1680 x 1050
Web Browser Size 1579 x 931
Installed/activated browser extensions: Ghostery and 1Password</blockquote>

**Comment by tofumatt** [comment]
Based on #7255, it seems this can happen in browsers other than Firefox, but it's quite hard to reproduce. I still can't manage it though.

**Comment by designsimply** [comment]
I tried replicating the problem using Safari 12.0 on macOS 10.13.6 and the height of the title looks normal to me ([screenshot](https://user-images.githubusercontent.com/1119271/47953604-92986b00-df45-11e8-9a34-c99854ca2bf8.png)). I tested with WordPress 4.9.8 and Gutenberg 4.2.0-rc.1 using Safari 12.0 on macOS 10.13.6. I tried with Unified Toolbar on and off as well as Fullscreen Mode on and off.

I'm leaving the `Needs Testing` label for now because we still want to figure out reliable steps to reproduce the problem. If you can think of any browser settings you may have that are not standard (i.e. modified font size) or if you have a browser extension or add-on that modifies content or if you aren't using the latest stable version of your browser, please leave a note with details.

**Comment by GlennMartin1** [comment]
I used to have it happen frequently in Chrome (Windows), but I haven't seen it in a while.

I'm unable to replicate it now using 4.1 or 4.2.0-rc.1.

Some bugs fix themselves?! lol

**Comment by designsimply** [comment]
Noting some testing steps from a duplicate issue at #11580 that look worth trying out:

> 1. Add a new post
> 2. Give the post a long(ish) title
> 3. Open the settings
> 4. Height doesn't change, resulting in the text clipping
> 
> * OS: WIN10
> * Browser: Chrome
> * Version: Latest
> * Gutenberg 4.2

**Comment by NewJenk** [comment]
Here's a video showing this issue on Chrome, Edge and IE: https://www.useloom.com/share/63aa55f131de407ca4501c383908ffcf.

**Comment by youknowriad** [comment]
This bug is related to our `react-autosize-textarea` npm dependency. We're using a very old version of that dependency, we should try updating it to see if it fixes the issue.

**Comment by garretthyder** [comment]
Hi @youknowriad is there a way to test the npm dependancy on a local install?

On a clean install of trunk (post-5.3) going to the Privacy Policy page to edit while having the browser half-width of a mac pro laptop I'm able to consistently reproduce. If you click into the input area the height adjusts and upon reload it looks ok... but if you do a hard refresh (Chrome) cmd+shift+r the issue will return.

Screen;
![feaa80f65c55f848a266cb602c85145d](https://user-images.githubusercontent.com/8726005/68919425-efb52800-0726-11ea-893f-95772888b163.gif)

The clean install to reproduce is done as follows using MAMP;
`svn co https://develop.svn.wordpress.org/trunk/ .`
`npm install`
`grunt build`
Setup SQL
Install
Navigate to edit Privacy Policy page
Click into edit, reload (seems fixed)
hard refresh (cmd+shift+r) issue returns

Browser size 960w
Chrome 77.0.3865.90
Mac OS X 10.11.6

**Comment by youknowriad** [comment]
> Hi @youknowriad is there a way to test the npm dependency on a local install?

No, that's not possible because this dependency is bundled in the JS code.

**Comment by adamziel** [comment]
> This bug is related to our react-autosize-textarea npm dependency. We're using a very old version of that dependency, we should try updating it to see if it fixes the issue.

@youknowriad I just tried updating `react-autosize-textarea` to `7.0.0` (latest ATM) doesn't help. I traced the root cause of the problem:

* `react-autosize-textarea` uses `autosize` library to handle resizing.
* Resizing means setting a fixed height to fit all the content and `overflow: hidden`.
* Once the title textarea is initialized, adjusting it's height occurs only in response to a fixed set of events (`input`, `keyup`, `autosize:update` fired on the input, window `resize`).
* Opening the inspector does not trigger any of these events so the height is not adjusted. The problem is only apparent when the inspector is rendered after the input, and also if the screen width is just right in relation to the text content of the title.

To add to the complexity, manually dispatching window resize event won't help as `autosize` caches the `clientWidth` and only triggers a resize when it actually changes.

It seems like a proper fix would involve:
* Some kind of a `editorResize` event that would be dispatched in circumstances like opening the inspector.
* A wrapper around `<TextareAutosize />` that would listen to that event and then dispatch `autosize:update` on the textarea.

**Comment by youknowriad** [comment]
@adamziel yeah, no strong preferences there,  is there another library that already implement the right handlers maybe?

**Comment by ellatrix** [comment]
Ideally the post title should be a block using RichText or PlainText v2. There's some other issues with the post title that could benefit from this, like paste issues and special handling within writing flow.

**Comment by paaljoachim** [comment]
From my experience with using Twenty Twenty One lately with Gutenberg plugin 9.8 and WordPress 5.6.
It seems the problem has been fixed.
I might be mistaken.

If others could take a look at how this currently works that would be good.

**Comment by paaljoachim** [comment]
It would be great to get some forward movement here to find a solution so we can get this issue fixed.
Thanks!
