### ISSUE TITLE
Option to delete or dublicate a block

### ISSUE THREAD

**Issue by JohnPixle** [WordPress/gutenberg#70]
I have been exploring some ideas around actions that users may want to perform to a block (apart from editing it). Such actions may be to **clone (dublicate)** a block, or **delete** it.

If there is indeed a need for this, which would be the best placement for those elements / icons to appear? Directly accessible (on hover) or nested inside the block menus?

![example of nested](https://d3uepj124s5rcx.cloudfront.net/items/2Y0Y13310o3R172D0e2t/Screen%20Shot%202017-02-15%20at%2002.46.52.png)

Personally I believe they are crucial actions and they must more accessible. Should we perhaps extract a set of global actions that appeal to all blocks, and create a consistent UX for them?

I have added a draft of my work on this at inVision, with my comments, so if anyone wants to take a look and comment by point-and-click, feel free to do so _(make sure you enable comments mode from the bottom right of the screen)_

Here’s the link: https://invis.io/HYAGLFW8E#/219088646_TextBlockStates

Sorry, it’s all combined in one static image, and no interactivity for now.

**Comment by jasmussen** [comment]
Solid work, thank you for taking the time to create such good mockups and even animatics!

We [discussed these a little bit in slack](https://wordpress.slack.com/archives/core-editor/p1487144539003735), the key bit being that this is arguably the trickiest UI to get right because especially the hover UI has to tread the very careful balance of not being overly visually heavy, while still providing just the right controls that would let you rearrange blocks, possibly switch types, without having to "click into a block" first. 

E.g. you've written your post, inserted your content, and you're entering the layout phase of your blogging session: you might be moving around the images a bit, or converting select paragraphs to blockquotes. 

Should doing so be available through hover with a few clicks on the side controls? Is it okay that it happens on block-click? Should more stuff be available on hover? How can that be balanced UI wise so it doesn't feel _kitchen-sinky_? Really tricky, therefore extra appreciated that you made mockups & video prototype. 

Would be great to get lots of thoughts and opinions on this, to increase the chances of us picking the path that is the most right for WordPress.

🌟

**Comment by aduth** [comment]
Related to #62, if blocks were "selectable", I might imagine it being intuitive to hit "Backspace" while a block is selected to remove the entire block.

**Comment by melchoyce** [comment]
While I think it's good to think about block duplication, I'm not sure how necessary it is while writing a post. Does anyone commonly copy/paste the same item a couple times in a post?

**Comment by JohnPixle** [comment]
Hm, good point.  in the case of writing a post, you are right, rarely someone will want to duplicate one of the common post content elements. But if we want users to start creating more content-rich pages and layouts, then I believe that in the context of such a page, duplicating a block might come handy.

As Ma.tt metioned:

> image, parallax image, gallery, slideshow, google map, open street map, tweet (and variations), youtube, contact form, survey, gist, auto-playing video background, GIF, all of the above with a captions, wp post embed, fb embed, blockquote, spotify song/playlist

**Comment by jasmussen** [comment]
Let's close this for now as an idea we can revisit if the need surfaces!
