### ISSUE TITLE
Duplicating post does not work with Gutenberg

### ISSUE THREAD

**Issue by manooweb** [WordPress/gutenberg#7000]
When I create a post (post-new.php) by duplicating from another one, Gutenberg does not get the content from the origin post.

I developed a simple plugin to make it easy to test.
This plugin is developed to have a behavior close to Polylang feature.
I attached this plugin to the issue or it is accessible on github here
https://github.com/polylang/polylang-gutenberg-usecase2/blob/master/polylang-gutenberg-usecase2.php

The method uses the add_meta_boxes hook.
See : https://github.com/polylang/polylang-gutenberg-usecase2/blob/master/polylang-gutenberg-usecase2.php#L91
and
https://github.com/polylang/polylang-gutenberg-usecase2/blob/master/polylang-gutenberg-usecase2.php#L141-L148

Steps to reproduce the behavior without Gutenberg:
1. Go to 'posts'
2. Create a new post with the classic editor
3. Enter a title, a content and a excerpt
4. Save Draft
5. Click on the icon in the metabox 'Duplicate content'
6. See your are on 'Add New Post' page and the 3 fields are copied from the origin post

![origin-post-522-classic-editor](https://user-images.githubusercontent.com/1003778/40657586-b0fd5f7a-6348-11e8-9c2a-dfa7ae57a6fb.png)

![new-post-from-522-classic-editor](https://user-images.githubusercontent.com/1003778/40662154-dbecdc26-6355-11e8-82e0-9a7bef9c97e4.png)

Steps to reproduce the behavior with Gutenberg:
1. Go to 'posts'
2. Create a new post with Gutenberg
3. Enter a title, a content and a excerpt
4. Save Draft
5. Click on the icon in the metabox 'Duplicate content' at the bottom of Gutenberg sidebar in 'Extended Settings'
6. See your are on 'Add New Post' page but the 3 fields are not copied from the origin post

![origin-post-524-gutenberg](https://user-images.githubusercontent.com/1003778/40663268-98bc6c20-6358-11e8-8782-dd8c76931c76.png)

![new-post-from-524-gutenberg](https://user-images.githubusercontent.com/1003778/40664036-4ec890e2-635a-11e8-9df8-ec090d6d6a23.png)

What is the right way with Gutenberg to have the same behaviour ?

 - OS: Windows 10
 - Browser Chrome 66, or Firefox 60
 - WordPress: 4.9.6
 - Gutenberg: 2.9.2

[polylang-gutenberg-usecase2-master.zip](https://github.com/WordPress/gutenberg/files/2048556/polylang-gutenberg-usecase2-master.zip)

**Comment by Chouby** [comment]
I debugged this and discovered that Gutenberg introduces 3 issues to make this not work:

1. Gutenberg changes the order of the actions `'add_meta_boxes'` and `'admin_enqueue_scripts'`. Indeed, with the classic editor, the 2 actions are fired in the order:
* `add_meta_boxes`
* `admin_enqueue_scripts`
while with Gutenberg, they are fired in the order:
* `admin_enqueue_scripts`
* `add_meta_boxes`
Since the post data are sent to Javascript in a function hooked to `'admin_enqueue_scripts'`, everything done in functions hooked to `'add_meta_boxes'` is not taken into account anymore.

NB: According to this [comment](https://github.com/WordPress/gutenberg/blob/v3.0.1/lib/register.php#L22), it looks like metaboxes are added "as soon as possible". I don't know why it cannot be done as soon as in the classic editor but worry that changing the order of two of the most widely used actions (See [hooks usage statistics](https://onedrive.live.com/view.aspx?resid=CC833525E16E4683!205461&ithint=file%2cxlsx&app=Excel&authkey=!AM6ufd9Xl_WM0rg)) could introduce other various backward compatibility issues in the ecosystem. 

2. With the classic editor, modifying the post data to prefill with whatever we want is easily done by modifying the global `$post` variable. However, with Gutenberg, and supposing that the point above is solved, modifying the global `$post` variable has no effect because of https://github.com/WordPress/gutenberg/blob/v3.0.1/lib/client-assets.php#L994 
which reads the post directly from the database instead of using the `$post` variable.

3. Finally, and supposing that the two points above are solved, and thus that a plugin sucessfully prefilled the post title of a new post, these lines https://github.com/WordPress/gutenberg/blob/v3.0.1/lib/client-assets.php#L1001-L1007 will erase the title prefilled by the plugin, without any possibility to change that before the post data is passed to javascript.

Conclusion: I don't have enough knowledge of Gutenberg to know if it would be possible to handle this in a backward compatible way (by restoring the actions orders and keeping the global `$post` variable rather than resetting it with a REST request). I don't also know if other plugins than Polylang are impacted by this. But I'll propose a PR to introduce a filter on post data before it is passed to javascript to fix the Polylang issue in a non-backward compatible way.

**Comment by danielbachhuber** [comment]
Thanks for your detailed analysis, @Chouby.

Of the three items you identified, the first seems like it should be solved with Gutenberg. #4929 already tracks that issue.

The other two issues seem like they'll need to be handled within Polylang, which should be updated to use formal Gutenberg APIs. If no formal APIs exist yet, then we'll need to open some conversation about how we can accommodate (related #5958). The current implementation you've described seems to be quite hacky, and would be difficult to provide backwards compatibility for.

**Comment by Chouby** [comment]
Thanks for your feedback @danielbachhuber 

It's indeed probably easier to handle the compatibility from Polylang but we need Gutenberg allowing us access to data as we can not use the global `$post` anymore. I proposed to add a filter in #7421 which would  help you solving the issue.

**Comment by mcsf** [comment]
Closing per @danielbachhuber's note in favor of #4929
