### ISSUE TITLE
Custom block attributes are not saved

### ISSUE THREAD

**Issue by GenaBitu** [WordPress/gutenberg#7016]
**Describe the bug**
Custom block attributes are not saved

**To Reproduce**
1. Create a plugin with custom block
2. Add an attribute with no source to the block (according to the documentation this should mean the attribute is saved in the block comment)
3. In `edit` function, add an AJAX call which in the callback calls `props.setAttributes`

**Expected behavior**
The attribute is set: Switching to the code editor shows it in the comment and it is present after save and reload

**Actual behavior**
The attribute is set in the sense that it is in `props.attributes`, but it isn't present in the block comment in the code editor and isn't saved.

**Desktop (please complete the following information):**
 - Debian testing
 - Chromium 62.0.3202.89

**Additional context**
- Gutenberg version 2.9.2 (installed from the plugins screen)
- Source: https://github.com/skaut/skaut-google-drive-gallery/blob/9cc07c7e401bf63aaba1db978eed038340792637/plugin/frontend/js/block.js, particularly lines 11 and 85

**Comment by mitogh** [comment]
Facing the same problem when meta you have a block that has meta and updates are done independently.

The only change stored is the last one.

As on this line: 

- https://github.com/WordPress/gutenberg/blob/5a57e6fdda6e2d4f1380e391a78cbb463a77215e/editor/components/block-list/block.js#L207

The value of  `this.props.meta` fallbacks to the initial value of the post when loaded so if no `Update` (click on the button to save) happens this property will always be the initial value and in consequence updates from different blocks to the meta attributes of a post only saves the last value being set to the meta.

**Comment by GenaBitu** [comment]
Not sure if that's the same issue - in my case, the attributes are ok until saving.

**Comment by GenaBitu** [comment]
The issue is still present in 3.0.0 with the difference that the attribute isn't present in the `save` function (triggered by switching to the code editor)

**Comment by aduth** [comment]
@GenaBitu I was able to track down the issue here, and while it's admittedly not the most obvious, the issue here is [use of `Array#push`](https://github.com/skaut/skaut-google-drive-gallery/blob/9cc07c7e401bf63aaba1db978eed038340792637/plugin/frontend/js/block.js#L83) which modifies the reference value. Specifically, it conflicts with the block serialization behavior where a default value is not included in the serialized comments since its omission is inferred as being the default. For your block, when first inserted, the value is set to the default `[]`, you later call `Array#push`, and because the pushed value is still [strictly equal to the default](https://github.com/WordPress/gutenberg/blob/54d405a562e84ec9c521f818dd82a0fcec98734e/blocks/api/serializer.js#L154-L157), it is not included in the serialized comment.

The simple solution for you is to use [`Array#concat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat) and [`Array#slice`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice) to produce new array references:

```js
var newDir = $( this ).html();
if (newDir === "..") {
	// Mutates original `path`: 
	// path.pop();

	// Does not mutate original `path`:
	path = path.slice( 0, path.length - 1 );
} else {
	// Mutates original `path`: 
	// path.push( newDir );

	// Does not mutate original `path`:
	path = path.concat( newDir );
}
props.setAttributes({path: path});
ajax_query(props);
```

There's a bigger issue here which is that it's an easy situation for a developer to find themselves in, and not an easy to debug or avoid.

I might imagine a few improvements on Gutenberg's end:

- Use [`Object.freeze`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze) on the block default attribute value to avoid mutation
- Use [a deep equality check](https://lodash.com/docs/4.17.10#isEqual) to determine whether the default value is equal to its current value
   - This requires either preventing modification to the original default, or assigning the default into the block's initial attributes as a copy, to ensure the original remains intact.

**Comment by aduth** [comment]
Closing in favor of #7252 for future improvements, since the original question has been resolved here. Please let me know if you're still encountering issues.

**Comment by GenaBitu** [comment]
Thank you very much, it works, this would have never occurred to me...
I think it would make sense to have the defaults immutable - it would make it much more idiot-proof...
