### ISSUE TITLE
NUX: Allow user to re-enable tips

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#7039]
From https://github.com/WordPress/gutenberg/pull/6631#issuecomment-393069320:

> I like tips. In video games tips are usually togglable in an Options menu. Should we make an option in the More menu that is enabled by default for new users, and is disabled when you're done or dismiss it?

Let's definitely do this. Quick mockup:

<img width="270" alt="screen shot 2018-05-31 at 16 25 15" src="https://user-images.githubusercontent.com/612155/40765258-3abe5d20-64ef-11e8-9655-a50182f49e9f.png">

cc. @karmatosed @jasmussen

**Comment by karmatosed** [comment]
Thanks for rustling up this issue. I have tagged it for copy as we can check what we want to have said in that action. @melchoyce mentioned not just saying enable/disable - which I agree.

**Comment by noisysocks** [comment]
'Turn on tips' and 'Turn off tips' sounds good to me.

**Comment by jasmussen** [comment]
I hate to be difficult here, and the copy can certainly need work. But lets be _very careful_ and _super intentional_ if we change the verbiage in menus on toggle. Generally if we can avoid TWO sets of copy that's superior to one set. Besides, given we have a checkmark, it might be confusing:


```
✓ Turn on tips
```

and 

```
   Turn off tips
```

☝️ Both of those seem wrong to me. Which one should have the check mark?


The alternative is to use the same pattern as the editor choice, and do this:

```
✓ Turn on tips
   Turn off tips
```

This takes double the space, and requires its own section, and also seems bad to me. We do it for the Visual editor and Text editor because those two _require_ different labels in order to work.

If we did the following, we could have a single menu item whose label did not change, and in my opinion is easy to read. When tips are enabled:

```
✓ Enable tips
```

When tips are not enabled

```
    Enable tips
```

**Comment by jasmussen** [comment]
Google Docs is the inspiration here. Multiple options, non-boolean menu:

![screen shot 2018-06-04 at 08 36 10](https://user-images.githubusercontent.com/1204802/40901929-704c7428-67d2-11e8-85c7-7f67593aaaca.png)

Single option, boolean menu:

![screen shot 2018-06-04 at 08 36 24](https://user-images.githubusercontent.com/1204802/40901936-7560d90e-67d2-11e8-8f52-f903f4f4a5cd.png)

**Comment by karmatosed** [comment]
I agree with having a single action, maybe 'enable' or 'show' works. Perhaps we can get a copy review suggestion though.

**Comment by michelleweber** [comment]
Enable or Show or Display all work, depending on what language you're using for similar kinds of settings; just keep it consistent. (Personally, I like "Show" because it's the plainest and simplest.)
