### ISSUE TITLE
Insert Summary feature

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#7115]
I am not able to locate a summary issue even though I have seen one earlier, so that I am adding a new here.

The plugin Advanced Gutenberg https://www.joomunited.com/wordpress-products/advanced-gutenberg has included an insert summary feature. It looks like this:

![insert-summary-joomunited](https://user-images.githubusercontent.com/5323259/40905263-add4b7b4-67dd-11e8-80ae-63298692b2b0.png)

![summary-inserted-joomunited](https://user-images.githubusercontent.com/5323259/40905272-b286147e-67dd-11e8-924e-4827164dce5b.png)

**Comment by mtias** [comment]
The issue has been closed as not being considered for now for v1: https://github.com/WordPress/gutenberg/issues/1760
https://github.com/WordPress/gutenberg/pull/2871

If someone wants to do a branch and show how it'd work — the screenshot there seems to suggest you click on the toolbar button to refresh the content, which might be a bit awkward.

**Comment by anevins12** [comment]
I've installed this plugin (it's on the plugin repo): https://wordpress.org/plugins/advanced-gutenberg/

The behaviour of the Insert Summary button is as follows:
* The button has this markup:
`
<button class="button" style="position: absolute; bottom: 10px; right: 15px">Insert Summary</button>
`
* On pressing the button;
1) The Document Outline component disappears;
2) Focus is moved to a new block added for the summary;
3) This new block is pre-populated with links. These links are coupled with the heading level structure outlined in the Document Outline component.

There are a few improvements we could make when integrating this:
* The Document Outline component should remain expanded when focus is moved to the newly inserted block;
* We should include hidden text that describes its action of moving the focus to the newly inserted block;
* Maybe we need to take a step back and envisage how best this would be used from a UX perspective. The functionality is almost there, but I still think the journey isn't clear to a user. The journey that pressing "Insert Summary" creates a new block at the top of content, in which has links that represent heading levels - and when links are pressed they do X, Y and Z.
* The newly created block (by pressing "Insert Summary) is essentially another navigational aid to the user and should be marked up with a NAV and (aria-)label . I understand this is also an issue on the Document Outline component.
Example of expected markup:
`
<nav aria-label="Summary of page">
    <ul> ... </ul>
</nav>
`
* The newly inserted block needs a button to delete the block and not just rely on the Escape key;
* The newly inserted block does not identify itself as a Summary block and may not be identifiable as such to people in general;
* The "Insert Summary" button gets disabled after a summary has been inserted. This should be explained in plain text instead of relying on the user to know this - again some UX work needed.
