### ISSUE TITLE
Move block removal under ellipsis

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#7216]
Where block removal is placed right now it's easy to accidentally hit it when you are interacting with the menu. Removal of a block should be a deliberate process and this allows that.

![removeblock](https://user-images.githubusercontent.com/253067/41114053-297ca30a-6a7b-11e8-941c-ac602310f0fc.png)

**Comment by jasmussen** [comment]
I think this is a crucial step for mobile, where if you accidentally delete a block, it's gone, because the undo/redo buttons aren't present there. 

On desktop, this is less of an issue, because there are convenient undo shortcuts and buttons at the top, which means there are no truly destructive actions. Perhaps we can start with doing this for mobile, and revisit if it becomes necessary for desktop?

**Comment by SuperGeniusZeb** [comment]
The remove button was already removed once before and then re-added because it was convenient to have it around for quick block removal on hover. Of course, this only applies to desktop since you can not hover things on mobile, so given what @jasmussen pointed out, I think putting the remove option under the ellipsis is a good idea there, but the button should remain on desktop.

**Comment by karmatosed** [comment]
Whilst I get the idea of having just on mobile, on desktop there is still the potential issue of accidentally clicking delete. I'd be less forceful about having this on all devices if we had a check on deleting. I am not saying we should but as we don't we shouldn't have it able to so easily be hit.

**Comment by jasmussen** [comment]
I have no super strong opinions — for the longest time I hoped we could do without the button, because pressing Delete or Backspace should hopefully be sufficient and enough, and we have good undo/redo. Since then I've come to find it convenient.

**Comment by mtias** [comment]
One thing to consider here is the "shared" block menu, as there's an option to "delete shared block" and would overlap with "remove from the post". Would need to make sure that is clear.

**Comment by karmatosed** [comment]
I could be wrong but as the delete shared block removes the block, can't we just have a delete block?

**Comment by mtias** [comment]
Not sure I understand what you mean there. Deleting a shared block means removing it from the block library, removing from the post is just the regular "trash button" action.

**Comment by jaymanpandya** [comment]
I was thinking whether we can do this? It solves the problem of accidentally clicking the block and losing it and it can be implemented on both phones and desktops.

![delete-block](https://user-images.githubusercontent.com/4047909/41834209-03eff7dc-7871-11e8-8493-557ce93220ee.jpg)

**Comment by SuperGeniusZeb** [comment]
@jaymanpandya I feel like that undermines the purpose of the <kbd><samp>Remove</samp></kbd> button being on the side, which is really just convenience. By adding a confirmation, the convenience factor is much smaller, and you might as well just have the <kbd><samp>Remove</samp></kbd> option be in the ellipsis menu, which may be faster in some cases due to a lower amount of mouse travel from the ellipsis to the <kbd><samp>Remove</samp></kbd> option as opposed to from the <kbd><samp>Remove</samp></kbd> option button to the <kbd><samp>Delete</samp></kbd> button in a pop-up.

**Comment by karmatosed** [comment]
@jaymanpandya thanks for the suggestion but in this case I think adding a step doesn't really inform the user as much as cause a hitch. It also doesn't remove the fact it could get hit, even seeing a pop-up could be clicked and ignored.

@mtias ah right yes we probably need to have both and split by a separator in this case. Which avoids hopefully slippy fingers.

**Comment by designsimply** [comment]
I am in favor of moving the `Remove` icon to a menu item under the ellipsis because deleting a block should be a deliberate process. This may also help prevent data loss.
