### ISSUE TITLE
Block toolbar looks odd on mobile

### ISSUE THREAD

**Issue by iseulde** [WordPress/gutenberg#7256]
**Describe the bug**

When selecting a block, it looks like the toolbar appears for the next block. I’m guessing there’s some styling issues for the block toolbar, I’m not sure how it’s supposed to look.

**To Reproduce**
1. Select a block in Gutenberg on mobile

**Expected behavior**

Block toolbar to feel more connected.

**Screenshots**

![cd38cade-72b7-427a-a17c-8fe51f19b7cd](https://user-images.githubusercontent.com/4710635/41214576-686cbe64-6d4c-11e8-8d06-1884820eb679.png)
![9606fc18-6734-4f60-ae1f-aeb534cc4751](https://user-images.githubusercontent.com/4710635/41214577-689754e4-6d4c-11e8-8a2f-aa08936eb8b6.png)

The last picture shows also the two toolbars on desktop. Maybe on mobile these can be merge into one?

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS
 - Browser [e.g. chrome, safari] safari
 - Version [e.g. 22] latest

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by ZebulanStanphill** [comment]
There have been a lot of changes to the toolbar lately. Is this issue still relevant?

**Comment by designsimply** [comment]
Tested and confirmed using WordPress 4.9.8 and Gutenberg 4.2.0-rc.1 with iPhone 6S running iOS 12.0.1 that the toolbars appear below blocks on mobile.

<img src="https://user-images.githubusercontent.com/1119271/47953518-6e885a00-df44-11e8-8422-7d19cd938025.PNG" width="270"> <img src="https://user-images.githubusercontent.com/1119271/47953519-6e885a00-df44-11e8-8445-1190b144f798.PNG" width="270"> <img src="https://user-images.githubusercontent.com/1119271/47953516-6e885a00-df44-11e8-8ae8-71e40ee67873.PNG" width="270"> <img src="https://user-images.githubusercontent.com/1119271/47953517-6e885a00-df44-11e8-9219-2f2177d31204.PNG" width="270"> 

<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=13999&action=edit using iPhone 6S running iOS 12.0.1.</sup>

Notes: if you tap at the top of a long block, the toolbar can become obscured. I noticed the movers are missing for floated images (reported at https://github.com/WordPress/gutenberg/issues/11454).

**Comment by mtias** [comment]
@jasmussen @karmatosed can you look at this one please?

**Comment by jasmussen** [comment]
I need additional information here, because although I agree this feels odd compared to how it looks on desktop, sadly this implementation is a technical necessity. Reason 1: If you longpress to select text to make it bold, the bold button if above the text will be obscured by the mobile copy paste popout menu. Reason 2: we cannot fix the toolbar to the top due to the gory technical reasons outlined here: https://github.com/WordPress/gutenberg/issues/7479#issuecomment-410988762

As such, what you see on mobile right now is intentional, and the best we can do within the boundaries of Mobile Safari. I would again encourage reading through https://github.com/WordPress/gutenberg/issues/7479#issuecomment-410988762 in depth, because that comment outlines how we _want_ to make it better, but we really can't yet.

**Comment by jasmussen** [comment]
Closing this one as intentional pending changes to Mobile Safari. See https://github.com/WordPress/gutenberg/issues/7479#issuecomment-410988762.
