### ISSUE TITLE
Cannot scroll the inspector screen on mobile

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#7258]
**Describe the bug**

When expanding some fields in eg the document inspector, it’s not possible to scroll down.

**To Reproduce**
1. Click on the cog icon and expand some fields so there is overflow. Scrolling does not work, though I can see movement in the background.

**Expected behavior**

For scroll to work.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS
 - Browser [e.g. chrome, safari] safari 

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by jorgefilipecosta** [comment]
I think this problem is not happening now. @iseulde could you confirm if the problem is resolved?

**Comment by draganescu** [comment]
I can confirm, was able to reproduce, this also on:

iPhone SE
iOS 12.1.4
Safari

However on iPad iOS 12.1.4 Safari it works perfectly. 

Apparently it is not a touch issue, but something to do with the responsive overflow setting for small screens.

**Comment by draganescu** [comment]
Investigated and so far I got this:

- the document tab in the sidebar has no issues with touch scroll
- only the block inspector panel has the problem
- there appears to be no CSS issue easily visible

I thought initially that the new animations may have introduced a bug and pinged @kjellr about it, but on a deeper look (removed the animations) the problem is unrelated. Not sure yet what's special about this block tab that makes it not receive the scroll focus.

**Comment by draganescu** [comment]
@ellatrix I think @jasmussen added a PR that fixed this. I tested on device and the simulator and cannot reproduce anymore. Can you confirm please either that it's solved or that for you it is still broken? Thank you!

**Comment by jorgefilipecosta** [comment]
Closing the issue as according to the comments it looks resolved.
