### ISSUE TITLE
Grey color behind caption in Image Gallery

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#7260]
I am seeing a grey background behind the captions.

![caption-adds-grey](https://user-images.githubusercontent.com/5323259/41231951-14f8424c-6d85-11e8-8cb5-5258c5373714.gif)

**Desktop (please complete the following information):**
 - OS: OSX 10.13.4
 - Browser: Chrome
 - Version: Newest version 3.0.1

**Comment by anevins12** [comment]
@paaljoachim, What makes you think this is a bug? It looks like this is decision choice to ensure text always has enough colour contrast against background colour.

**Comment by paaljoachim** [comment]
@anevins12 
Hey Andrew.
The background grey color is something I did not decide to add. It feels really out of place. It made me think it was a bug. If it is forced on the user then it should also be up to the user if they want to add a color and if so which color.

**Comment by jasmussen** [comment]
We discussed this in Slack: https://wordpress.slack.com/archives/C02QB2JS7/p1528897452000879

For the time being, this is intentional, and something themes can override both in the frontend and using an editor style in the editor itself. Presumably plugins could provide options here as well. For now I'm closing this, and then we can revisit if need be.
