### ISSUE TITLE
Review Workflow: Featured Image not Selected when Reviewer Clicks Featured Image Already set

### ISSUE THREAD

**Issue by brysont** [WordPress/gutenberg#7309]
**Describe the bug**
The media library does not select the previously set featured image when opened for editing or checking, if another user set the featured image. See below for better description of the issue.

This is an issue because contributing users can be unpredictable, sometimes uploading several copies of the same image, only at different sizes and aspect ratios, which doesn't always make it easy to find the image they chose in the library. It's even worse if they searched the library and used an old image. My site, for example, is 9 years old with over 5,000 posts, each one with a featured image and over half with at least one image in the content. Tracking an old image down in that case to ensure the details are set right would be tedious, at best.

**To Reproduce**
1. Have a contributor create a new post draft and set a featured image for the post
2. Go into that same post as a user with publish ability
3. Click on the featured image to "edit" it (also jsut for viewing that it's a large enough image, checking description, alt, caption, etc.)
4. The previously set featured image should be selected in the media library when it opens, but it's not. Nothing is.

**Expected behavior**
The expected behavior is for the previously selected featured image (by contrib user) to be selected when the media library is opened by the reviewer.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 66

**Additional context**
- Gutenberg 3.0.1
- WordPress 4.9.6
- Searched open issues for "Featured Image" and found nothing describing this issue. My apologies if someone reported this under a different term that I missed.
- Screenshots not really useful. Steps to reproduce are more useful.

Thanks!

**Comment by AtrumGeost** [comment]
Hi there,

I tested this with Gutenberg 4.0, but with a contributor user I wasn't able to access any image when trying to add a "Featured Image". Whenever I try that it would keep loading forever:

![set featured image](https://user-images.githubusercontent.com/3696121/47183498-cc366880-d2ed-11e8-98df-0fa9c938edec.png)

However, I think this is because contributors don't have the option to add Featured Images in the classic editor:

![classic-editor](https://user-images.githubusercontent.com/3696121/47183568-01db5180-d2ee-11e8-9787-74c18d8e96eb.png)

So maybe the "Featured Image" option needs to be removed (or improved) in the Gutenberg editor:

![guten-editor](https://user-images.githubusercontent.com/3696121/47183602-1a4b6c00-d2ee-11e8-8729-a9caf7f7fe4a.png)

As a side note, this seems to be working properly with the Calypso editor and the contributor role:

![calypso](https://user-images.githubusercontent.com/3696121/47183898-cf7e2400-d2ee-11e8-8c3d-8b57ef29812a.png)

_WordPress 4.9.8 and Gutenberg 4.0.0 using Google Chrome Version 70.0.3538.67 (Official Build) (64-bit) on macOS 10.14 - Mac OS Mojave_

**Comment by brysont** [comment]
Gotta disagree on the part about contributors not being able to add FIs in the classic editor - have several dozen who have been doing it for years on my sites (then submitting for review). This was also not limited just to the Contributor role. Haven't tested on v4 but will give a quick try this evening and report back.

**Comment by youknowriad** [comment]
I'm not able to reproduce this issue.
