### ISSUE TITLE
Corrupted gallery recovers to empty list

### ISSUE THREAD

**Issue by koke** [WordPress/gutenberg#7344]
**Describe the bug**

While testing compatibility with the Aztec editors I found an issue where we were dropping a `class` attribute from gallery lists: https://github.com/wordpress-mobile/AztecEditor-iOS/issues/984

When Gutenberg encounters that, it doesn't recognize the block and offers the option to convert to blocks or edit as HTML. When you choose to convert to blocks, it turns into an empty list (more correctly, a list with empty items) instead of recovering the gallery.

**To Reproduce**
1. Insert a gallery with one image
2. Switch to HTML and remove the `class="blocks-gallery-item"` from the list item
3. Switch back to visual
4. Choose "Convert to Blocks"

**Expected behavior**

Choosing "Convert to blocks" should be able to recover the gallery.

**Additional context**

Tested with Gutenberg 3.0.1

**Comment by mcsf** [comment]
Perhaps related: https://github.com/WordPress/gutenberg/issues/6790

If so, @koke, feel free to close. Otherwise it can be looked at separately.

**Comment by koke** [comment]
It looks like it could be the same issue, but I don't know enough to be sure

**Comment by mtias** [comment]
@mcsf can you check if this should be still valid?

**Comment by mcsf** [comment]
Yes, still is. If I comment out the block deprecations for easier reading of the console output (image paths redacted for clarity):

```
Expected:

<ul class="wp-block-gallery columns-3 is-cropped"><li class="blocks-gallery-item"><figure><img src="B" alt="" data-id="227" class="wp-image-227"/></figure></li></ul>

Actual:

<ul class="wp-block-gallery columns-3 is-cropped"><li class=""><figure><img src="A" alt="" data-id="445" class="wp-image-445"/></figure></li><li class="blocks-gallery-item"><figure><img src="B" alt="" data-id="227" class="wp-image-227"/></figure></li></ul>
```

This makes some sense because the `images` attribute is sourced as `selector: 'ul.wp-block-gallery .blocks-gallery-item'`, so without the class no item can be inferred.

If I change the selector to `ul.wp-block-gallery li`, the parser does find all the images, and the "Expected" output corresponds to a full Gallery block's HTML. Oddly, this isn't enough for the block to self-correct, nor for the _Resolve_ action to work.

**Comment by noisysocks** [comment]
When I test this now, selecting _Convert to blocks_ turns the invalid gallery block into an image block. This doesn't feel so unreasonable to me. It avoids data loss and visually things look the same as before. I'm going to close this issue for now, but always happy to revisit.
