### ISSUE TITLE
Will the title be a block (movable)?

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#7359]
I want to position a block above the title but it's not movable.

So, I'm doing this bad workaround for now: (1) disable rendering of one block and (2) render it above the title via `do_action( 'place_before_the_title' )`. Not nice.

Related features that could help:
1. Add option "Additional CSS Classes" to the title
2. Add option "Additional CSS Classes" to the whole page

**Possible alternative solution**
Make `core/title` block which, when inserted, would disable `the_title()`'s output and print it in the place of the block. (But really this is also a bad workaround and a movable title block would be better.)

(Also this is a common use case to disable the title completely which is achievable only using meta boxes now.)

**Comment by leahkoerper** [comment]
In January @mtias [said](https://github.com/WordPress/gutenberg/issues/4482#issuecomment-357705649) the title would become a block in phase two when they handle page layouts. Assuming that's still true, it means we won't get a title block until a ways after the 5.0 release.

**Comment by manake** [comment]
Thank you.

Does anyone know if it's already established (or if there are any predictions) how this will be achieved? `add_theme_support( 'editor-the-title-is-a-block-in-this-theme' )`? And then page.php etc. should remove `the_title()` calls?

Is there any workaround for this for now? So far I had a "Content before the title" textarea in a meta box where a shortcode could be inserted but now this shortcode is a block. I guess my present workaround is the best that can be done for now?

**Comment by mtias** [comment]
@leahkoerper is correct. That's on the roadmap for v2.

Once gutenberg controls areas beyond the post_content the title would be just another block (together with post date, author byline, etc). Themes would likely start using another function like `do_blocks( $template_definition )` rather than `the_content()`.

If you want to achieve something similarly now, you'd just configure your theme to not output a title and include a block for it instead. You'd then include the title block for any new post as part of the default template. I'm not sure I would recommend this, though, unless you are comfortable making any necessary updates once v2 is in progress and taking on that overhead.

A good example might be the Google/AMP travel demo: https://amp-travel.xwp.io/
