### ISSUE TITLE
Tips bounce around when you click outside them

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#7447]
Tips if you click outside shouldn't progress to the next Tip. Ideally we would have them just stay where they are. If that's not possible then closing them and allowing people to just move on as you can re-enable now.

**Comment by Clorith** [comment]
This makes sense, especially as some of them make references to action items that you may wish to expand (often such tips expect you to click on the elements indicated to move on).

Especially noticeable with the new block (also the very first hint), and the side panel toggle.

I'd rather not close them if we are guiding someone through the experience, I may be new and not know how to re-enable them as the three small dots are not an obvious location to go to restart a "first-time guided tour".

**Comment by karmatosed** [comment]
@Clorith yes ideally I would like to them stay there and not be closed. @noisysocks maybe you have some insights here into how we can make this better?

**Comment by jasmussen** [comment]
No fiercely strong opinion here, but the reason I suggested a click outside to close was that this is the same behavior as modals. Additionally, as I was stepping through the flow, it felt weird that I could manipulate content outside of the tips, creating some weird situations:

<img src="https://user-images.githubusercontent.com/1204802/40707369-c99ea48c-63f0-11e8-9c76-d36c32860eca.gif" />

Also worth finding out if there are any issues with setting focus outside the tips box — if you click outside, that has focus — how do you get back to the tips box using the keyboard?

All that said, I have no strong opinion that should block improvements.

**Comment by noisysocks** [comment]
No strong opinion here either 🙂

In my mind a NUX tip should feel like a friend nudging us in the right direction rather than being an actual part of the user interface. To this end I wonder if we should try:

- Making it **not** modal. That is, clicking outside of the tip does nothing.
- Advancing the guide if the user clicks on what the tip is pointing to (e.g. the cog icon).

---

`<unrelated-ramblings>`

I'd also like to explore moving away from having NUX be a guide (e.g. remove the 'See next' button) and towards tips appearing when they're contextually useful. For me, the ideal flow for a new user would be:

1. _Creates a new post_
2. Tip appears next to Add Block button: "Hey friend! Here's where you add a block—give it a try!"
3. _Inserts a block, the tip disappears_
4. _Starts typing some content_
5. _Adds a second block, creates some more content_
6. _Adds a third block_
7. Tip appears next to Settings button: "Wow you're really getting the hang of this! You can see more block settings here"
8. _Clicks on Settings button, the tip disappears_
9. _Creates some more content_
10. _Some time passes_
11. Tip appears next to Preview button: "Wow, this is the best post I've ever seen! Smash this button to see what your users will see"
12. etc. etc. etc.

`</unrelated-ramblings>`

**Comment by Clorith** [comment]
I like your second thought there, about making them advance, and opens up the possibility of contextually displaying them based on the view to give more tailored tips.

I feel that WooCommerce does this rather well when adding a product for the first time, they're using pointers from core for the steps I believe.

![woocommerce-new-product](https://user-images.githubusercontent.com/468735/41963610-495d4922-79f8-11e8-803e-3c4ab3ca00fd.gif)

**Comment by karmatosed** [comment]
To me I think I would like to see:

> Making it not modal. That is, clicking outside of the tip does nothing.

Just as a version to experience and we can take from there?

The issue right now is the bouncing and clicking through that feels not the best experience.

> Advancing the guide if the user clicks on what the tip is pointing to (e.g. the cog icon).

This makes sense to me also as a 'well you've on track' notice of the user's behaviour. Unless I'm not mistaken we can do both of those things you suggest?

@noisysocks the way you are describing tips and the gentle encouragements are exactly where I want this to go - so excited there. I was thinking of even from feedback how a number of times doing something could also be triggers. This could beg good to also explore in an issue away from this of course. I like idea of building on this.
