### ISSUE TITLE
Tips text link border remains on next tip

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#7452]
If you click a tip the next one gets the text border around it. Ideally this should reset over having it on all Tips after the one you click.

![2018-06-21 at 21 42](https://user-images.githubusercontent.com/253067/41744627-45bf979e-759c-11e8-9e12-c2dd5f8c8e01.png)

**Comment by tofumatt** [comment]
This appears to have been a deliberate choice to focus the first tab-accessible element in the popover and then fallback to the whole popover itself. I can see the accessibility wins here so that you could keyboard navigate through a few tips at once, but I agree and think just using the fallback is nicer.
