### ISSUE TITLE
New Tooltips are inconsistent with existing core tips

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#7456]
WordPress core already has default Tooltips (Feature pointers). The new Gutenberg tooltips are styled completely differently which makes for an inconsistent experience in the Dashboard, especially for new users.

The Gutenberg tips should be styled to look exactly like the existing core Feature Pointers.

![screenshot_699](https://user-images.githubusercontent.com/2078245/41760549-55c021cc-7637-11e8-91be-134185bc4063.png)

![screenshot_700](https://user-images.githubusercontent.com/2078245/41760550-58379160-7637-11e8-9288-5de04adb6ea7.png)

_Gutenberg 3.1.0_

**Comment by karmatosed** [comment]
There is reason for this as they aren't the same UI element or have the same intent. This was discussed at a little length during the creation of Tips and is something for now let's keep as is. The thinking then came down to it being a different element with the interact. That's valid to standby. As a result this doesn't need design as this isn't going to change.

For context some of the points in that issue here: https://github.com/WordPress/gutenberg/issues/3670#issuecomment-351693483

> Is it like pointers in Core?
Looks like that, right? This is one of the situations where a UI can look like the same, yet it's radically different. Think for example the modern form of notifications: an app can use them for useful, valuable content, with a solid background logic — they are amazing. Another app uses them to nag and annoy the user over and over with no logic — holy pineapple, the rage!

**Comment by maddisondesigns** [comment]
I disagree with that. At their core, they're pointing out new functionality to the user, just like the core Feature Pointers. None of the points mentioned in that [#3670 Comment](https://github.com/WordPress/gutenberg/issues/3670#issuecomment-351693483) provide any valid reason for not styling them the same. Just because they're designed to have some smarter logic behind them, how does that automatically mean that they should be styled completely different to other tips/pointers in the rest of the interface? That makes no sense at all. Based on that logic, the _Create a new gallery button_ in the current Media popup window should be styled completely different to the Page _Update_ button. One button steps you through a process whereas the other button performs a specific action. Again, that logic obviously makes no sense.

In the previous comment Pento raises some valid points. Tips in UI's are mostly useless. This goes for the existing Feature Pointers. Not only are they disruptive to a users workflow, but if you need to tips to explain your UI, then it's a good indicator that your UI isn't well designed.

Not only that, popup tips like this cover the users interface and force the user to interact with them to get rid of them, and they're incredibly annoying when they jump all over the screen to different locations. I've never once clicked through a popup tip interface like this, and the first thing I look for is the "Do not show again" checkbox. Even leading usability expert Jakob Nielsen provides numerous reasons why popup tips like these are a bad idea. https://www.nngroup.com/articles/pop-up-adaptive-help/

The end user is not going to see any difference between these tips and the tips they see in the rest of the Dashboard, regardless of whether you think they have a different intent. What they will see though is the inconsistency that Gutenberg is continuing to introduce. Not only are they not attractive, but because they're styled so plainly, they're incredibly difficult to even notice. If you must have them, then they should at least be styled to match the rest of WP UI.
