### ISSUE TITLE
Locking a Block and Block Outlines

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#7469]
Not sure about this, but as part of reducing the visual weight in nested contexts, I think we should not render most of the UI on locked templates. For example, if we have a wrapper block, with some column blocks inside, and the wrapper is set to be locked, we should avoid rendering individual column outlines, or fade the outline further.

**Comment by karmatosed** [comment]
I would +1 to fading the outline. I also am very aware nesting rapidly becomes quite a concentrated heavy interface.

**Comment by kraftner** [comment]
But what if that wrapper block needs to be selectable because even though it is locked it has some attributes that have Inspector Controls?

**Comment by SuperGeniusZeb** [comment]
@kraftner I wonder if this is a situation where block breadcrumbs in the sidebar might be useful. See [this comment](https://github.com/WordPress/gutenberg/issues/6459#issuecomment-385097690) on #6459.

**Comment by kjellr** [comment]
👋 Block outlines have changed a bit since this issue was filed, and will likely change more if #14961 makes it in. In the meantime, I'm having a little trouble understanding the nature of this issue. I think a couple more examples (ideally visual ones, even if they're messy!) would help explain the concept here a little more clearly. Thanks!

**Comment by mtias** [comment]
@kjellr this is about using blocks to define structure, but preventing its UI (selection state, outlines, toolbar, etc) from showing up. Imagine the current "post content" as a container block that has no interface — it just transparently contains all the blocks.

**Comment by chrisvanpatten** [comment]
I would actually say this is even _more_ valuable if #14961 gets merged, because it gives container blocks an even greater visual weight/visibility. The changes in #14961 make a lot of sense _if visualising the container itself is important_, but in some cases the container itself is more of an implementation detail which should be invisible.

**Comment by karmatosed** [comment]
Linking this one to the exploration work going on here: https://github.com/WordPress/gutenberg/issues/18667

**Comment by ZebulanStanphill** [comment]
#18105 removed the dashed parent/child block outlines and padding, so I'm closing this issue since it is now irrelevant.
