### ISSUE TITLE
Sibling inserter doesn't show for focused blocks

### ISSUE THREAD

**Issue by nbrummerstedt** [WordPress/gutenberg#7519]
**Describe the bug**
When a block is focused, I don't see the sibling inserter when i hover the top of the block.

**To Reproduce**
Using 
Using 
Create a page, and create 2 blocks. Focus on the second block.
Sibling inserter will show upon hover of the upper border of the first block, but not the second.
Switch focus to the first block. Now the first block doesn't show inserter

**Expected behavior**
Inserter should be visible for focused blocks.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 67
 - Gutenberg 3.1.0

**Comment by chrisvanpatten** [comment]
This was changed intentionally in #7220 to better handle cases where the sibling inserter would be covered by the toolbar.

**Comment by nbrummerstedt** [comment]
Why not move the sibling inserter, then?

**Comment by gziolo** [comment]
@chrisvanpatten - I know that this change was intentional. However, it is now very counter-intuitive when you want to prepend a block. I'm not quite sure how much it is an issue in a regular flow, but definitely, it's inconvenient when doing some developer oriented testing. I wanted to share my observation, but please treat it as less important because I don't write at the moment as a regular user :)

**Comment by gziolo** [comment]
I just saw this screencast recorded by @bph in #7508:
http://recordit.co/x2XzEuyoLc

In my opinion, it only confirms, that it isn't the best UX.

**Comment by jasmussen** [comment]
The sibling inserter works below the focused block, or above and below any block. You can also choose the option to fix the toolbar to the top, in which case you can use the sibling inserter before and after a block. #7297 will also bring a menu option and keyboard shortcut inserting blocks before and after any selected block.

As such, this is intentional behavior, and it is for the time being the best solution we have for #7168. Alternate solutions are very much welcome, but they should be take into account the challenges outlined in #7168, such as making sure there are no conflicts with the toolbar on the selected block. As a bit of repo management, I'm closing this in favor of #7168 and would encourage thoughts on that ticket instead.

Noting that #7508 is a bug that we need to fix, which is definitely related to this, but separate.
