### ISSUE TITLE
Elementor (free) doesn't work with Gutenberg

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#7560]
**Describe the bug**
The hugely popular [Elementor Page Builder](https://wordpress.org/plugins/elementor/) can't be started when Gutenberg is active.

When creating a new page or when editing an existing Elementor page, like a lot of page builder plugins, Elementor provides a button to activate the editor itself (rather than just jumping straight into it. One of the benefits being that you can easily modify things like page templates etc, if need be). This button no longer appears.

**Editor page without Gutenberg activated**

![gutenberg_elementornewpage](https://user-images.githubusercontent.com/2078245/41954093-d45eba64-7a1c-11e8-8a9a-3a934842594f.png)

![gutenberg_elementorexistingpage](https://user-images.githubusercontent.com/2078245/41954095-d5c349e2-7a1c-11e8-902f-42ea31d8eb40.png)

**Editor page with Gutenberg activated**

![gutenberg_elementornewpagewithgutenberg](https://user-images.githubusercontent.com/2078245/41954202-7a3b7d46-7a1d-11e8-8f94-82cd83d597da.png)

![gutenberg_elementorexistingpagewithgutenberg](https://user-images.githubusercontent.com/2078245/41954211-7f134f92-7a1d-11e8-85d4-f7b2bcfd83ab.png)

**To Reproduce**
1. Activate Elementor Page Builder (.org link above)
2. Create a new page and try to start the editor

_Gutenberg 3.1.0
Firefox 60.0.2 (64-bit)
macOS Sierra 10.12.1_

**Comment by Soean** [comment]
So it seems Elementor 2.1.0 solves this problem. 
I am closing this issue now. If there is something we can do, please reopen this ticket or open a new one.

**Comment by cosquiere** [comment]
For me and i guess for a lot of people the problem still exist. 
When a new page is created you cant access elementor edit button in the new editor.
Once you edit first time, the button appears in the new editor.

TEMPORAL SOLUTION:
1. Click on edit post. Your url will look like that 

- **/wp-admin/post.php?post=7800&action=edit**


2. Edit the url in order to be able to action elementor editor.
- /wp-admin/post.php?post=7800&action=**elementor**

New page created, no elementor button appear.
<img width="1001" alt="screenshot 2018-12-07 at 09 35 57" src="https://user-images.githubusercontent.com/19712971/49636752-c7478880-fa03-11e8-8bcb-f89af64a212a.png">


After do the url manual action.

<img width="1280" alt="screenshot 2018-12-07 at 09 38 05" src="https://user-images.githubusercontent.com/19712971/49636814-f0681900-fa03-11e8-8345-787beae91380.png">


What if we want know to came back to de gutenberg editor? Its seem like once the elementor editor is set for the page, there is no way back. At least for now.

I hope it help to people and help to developers. 

Cheers

**Comment by truloveliaison** [comment]
@cosquire. I appreciate the offer of a possible potential fix regarding prevented access to an elementor edit upon a new page/post content creation.  I recently implemented a new WordPress install whereby the new WordPress version forces one to utilize the fairly new Gutenberg content builder/editor.  In being so unaccustomed to its ins & outs, particularly about navigating my way around, I could not see the intended streamline engagement; of which simply requires an additional plugin that plants an elementor block within Gutenberg, so that a user can easily plant elementor content and templates with also the use of an elementor search using the Gutenberg search field.  By way of using these components, a designer can easily locate saved elementor templates/content blocks, or even move to within the elementor design platform to create the desired design element.  Upon satisfaction of the design element/page or sectional-block template, the user simply will save the design and exit out of the elementor platform, thus returning to the WordPress Edit page/post specific platform window.  At which point, the user would resume with the build to repeat the initial procedure of using the Gutenberg search about the Elementor library for the recently, or long-since saved feature one desires to implement.  Upon locating, the user simply uses the Elementor blocks within Gutenberg (provisional by way of the Elementor blocks for Gutenberg plugin) to then insert whatever specific design element once created about the Elementor platform editor.  I see why the WordPress/Gutenberg designers configured the engagement in such a way for it maintains a priority for the user to primarily live or design within the WordPress/Gutenberg environment.  Although, it is a bit strange with being unaccustomed to such apparatus and being so adjusted to navigating back and forth between the editors by way of the button links, but by designing the CMS in this manner, the page/post never would assume an absolute attribute of predominantly associated to the Elementor plugin and always retains a WordPress-Gutenberg associated absolute attribute.  So, it makes since for the designers to want to retain their control over the enterprise of web development and positions the plugins as maintaining the supportive role in design.  I imagine there is less likely for errors or bugs that could arise in the template standardization amidst the themes and WordPress by not allowing the page builder or content builder plugins to exercise their design additions to be represented as the main contributors in the overall page/post templates and thereby similarly as in the overall Web design.  It essentially is matter of marketing and for the WordPress brand to protect its interest within the market of an Industry in somewhat of an exploding level of interest and growth.  It took some type to see how this works, but once I understood how it functions, I could then somewhat understand why it is configured this way.  In my future endeavors, I will definitely be using Elementor, for it is more user friendly with more features allowing for more intimate design elements, but I will keep in mind to perhaps design all of my Elementor design elements and templates prior to me setting about implementing my final design using Gutenberg...Thereby, I will simply be able to just slap all of my content, applying it to my page/post in one rip and rather quickly.  Afterward, tweaking and performing a final edit will be a breeze, but this will require more initial planning and predetermination rather than simply attacking a page/post design head on.  However, once I have my predesigns already stored, I can move about page by page and post by post , implementing the same, reusable elements or the specific elements recalled out of my initial Elementor design template library....
Best o Luck...

**Comment by Tofandel** [comment]
Latest elementor breaks gutenberg again, now all the blocks are not added to the gutenberg the iframe
