### ISSUE TITLE
Default block, but only within a parent/outer block

### ISSUE THREAD

**Issue by nb** [WordPress/gutenberg#7573]
When I press Tab after the last element in my inner block, Gutenberg helpfully creates a new paragraph for me. Unfortunately it's not one of the `allowedBlocks` for the parent and I would prefer that the default block is the one I choose. Is this possible?

My research showed that I could use `setDefaultBlockName()` and I could possible hack it to respect the context (based on focus), but I hope there is a better way.

**Comment by goldenapples** [comment]
Since #7732, the block inserter is no longer shown if the default block is not one of the blocks allowed in an InnerBlocks area. However, this makes the inner blocks area somewhat unusable unless it defines its own UI for adding child blocks, by modifying the template or some other method.

As an example, I have a carousel block which can accept a couple different types of blocks as inner blocks content, but not the default paragraph block. Up till now I've been using the default block appender as the mechanism for inserting new content slides (with some CSS hackery to make the block appender appear as a new slide, and to prevent inserting and any blocks but the blocks I wanted to allow...) The block appender provides a really consistent and user-friendly interface for adding content to nested blocks.

I think it would be really nice to be able to specify a default block for inner blocks areas that's different from the root default block, like this:

```
<InnerBlocks
    allowedBlocks={ [
        'custom/responsive-image',
        'custom/image-with-card',
    ] }
    defaultBlock={ 'custom/responsive-image' }
/>
```

which, along with some context-aware modifications to the logic in `canInsertDefaultBlock`, would allow these nested block regions to use a default block appender, and style it as needed for their own purposes.

**Comment by nerrad** [comment]
It looks like this functionality can be added via a custom appender added to `InnerBlocks`.  See [documentation here](https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/inner-blocks/README.md#renderappender) and the related pull here: https://github.com/wordpress/gutenberg/pull/14241
