### ISSUE TITLE
"Updating Failed" / "Publishing Failed" on latest Update

### ISSUE THREAD

**Issue by tvledesign** [WordPress/gutenberg#7652]
**Description:**

Upon updating to the recent version of Gutenberg, I haven't been able to save or publish posts. I keep getting an "_Updating Failed_" or "_Publishing Failed_" error. Tried this on a fresh install of WordPress as well as deactivating all plugins on the site I'm experiencing this on.

**To Reproduce**

1. With Gutenberg installed and updated, create a new post.
2. Try to save the new post as a Draft or Publish it.

**Expected behavior**

I've expected the post to save like it normally does.

**Screenshots**

Screenshot of post not saving.

![2018-06-30_21-13-01](https://user-images.githubusercontent.com/10258323/42130435-9500b238-7caa-11e8-9111-7ef188b16756.png)

Screenshot of the inspector.

![2018-06-30_21-07-22](https://user-images.githubusercontent.com/10258323/42130436-96472550-7caa-11e8-9ce5-d4b831a47227.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome (67.0.3396.99 (Official Build) (64-bit))

**Comment by designsimply** [comment]
Error in plain text for reference:

> The hook name can only contain numbers, letters, dashes, periods and underscores.
> index.js?ver=153025076:1

Noting a few other mentions of that same error message in past issues:

* https://github.com/WordPress/gutenberg/issues/6487#issuecomment-388418371
* https://github.com/WordPress/gutenberg/issues/7188#issuecomment-395449495

I believe https://github.com/WordPress/gutenberg/issues/6091 addresses the underlying problem, which appears to be that if another installed plugin uses `wp.hooks.addAction()` (such as [Advanced Custom Fields](https://wordpress.org/plugins/advanced-custom-fields/)) then editing will break.

@tvledesign, thank you for the report! If you'd like to reply here to note whether you are currently using the Advanced Custom Fields plugin (and the version), that'd be great to document! Past that, please subscribe to https://github.com/WordPress/gutenberg/issues/6091 if you'd like to follow progress on this issue.

**Comment by tvledesign** [comment]
@designsimply I have this running on a site without Advanced Custom Fields and it produced the same errors (as well as on a site that has ACF). Disabling all plugins with only Gutenburg activate yield the same results.

**Comment by designsimply** [comment]
🤔 For good measure, may I ask if you have tested with the default theme? I will also try testing from Chrome on Windows…

**Comment by tvledesign** [comment]
Actually, interestingly enough I deactivated everything just now and set it to the default theme and had an error the first time but it saved the second time. Then I switched back to my theme and turned all my plugins back on and it oddly worked.

**Comment by mattions** [comment]
For me the problem was because I had started serving the site using HTTPS, with a SSL certificate from lets encrypt, however I didn't update the urls on the Settings in the General Dashboard (Dashboard --> Settings). That was making Chrome not load a jetpack pluging, breaking the JS execution.

HIH

**Comment by markolbert** [comment]
I just ran into the same problem. Can someone explain how to diagnose what might be causing the problem? Things like "turn everything off" are not what I want to be doing with my time.

**Comment by sakyachen3** [comment]
I solved this problem
Just stop WP Cerber Security version 7.2, and update to version 7.7, 
then restart WP Cerber Security，everything is worked fine

**Comment by markolbert** [comment]
I’m at WP Cerber Security 7.6, which appears to be the latest available publicly. Where did you find 7.7?

Sent from my iPad

On Sep 20, 2018, at 7:00 AM, sakyachen3 <notifications@github.com<mailto:notifications@github.com>> wrote:


I solved this problem
Just stop WP Cerber Security version 7.2, and update to version 7.7,
then restart WP Cerber Security，everything is worked fine

**Comment by sakyachen3** [comment]
Sorry, it is version 7.6

**Comment by markolbert** [comment]
No worries.

For the benefit of anyone else running into this problem: I had already updated WP Cerber to 7.6 before encountering this issue. Deactivating Cerber and re-activating it seems to have fixed things. Please note that in the course of doing this I had to re-install Gutenberg (I forgot that I had deleted it at one point after running into the problem), so deleting and reinstalling Gutenberg may have played a role in solving the problem, too.

**Comment by sumitsuboink** [comment]
I just ran into the same problem too.
**ON MY FIRST TEST RUN**
just after my install and guide over.
because I'm never install "WP Cerber Security"...and I'm a WP newbie
so I have no idea what going on
anyone can help?

**Comment by noumanabbas** [comment]
I am having the same issue on my company website, https://www.DigitalBrandingCraftship.com. I found the issue is into my settings tab with the url. I changed it from http to https and the issue is resolved, Thanks to @mattions :-) who guided here.

**Comment by jutta-livingmiracles** [comment]
I have the same issue. "Updating failed" with latest version of Gutenberg plugin. I do not use WP Cerber. My site uses https:// and the settings in General (WordPress Address, Site Address) use https:// as well. 

What can I do to troubleshoot?

**Comment by JGuiselin** [comment]
Hi everyone ! I got the same prohlem and  solved it thanks to the method explained on this [article](https://support.cloudflare.com/hc/en-us/articles/203487280-How-do-I-fix-mixed-content-issues-or-the-infinite-redirect-loop-error-after-enabling-Flexible-SSL-with-WordPress-)
I installed the cloudfare Wordpress [plugin ](https://wordpress.org/plugins/cloudflare/)
It still didn't work so then I installed the  [SSL Insecure Content Fixer](https://en-gb.wordpress.org/plugins/ssl-insecure-content-fixer/)
And finally, as it didn't work, I installed [this one instead](https://en-gb.wordpress.org/plugins/really-simple-ssl/) and it finally worked

I have to mention that i also whitelisted my ip address on cloudfare, as explained above.
hope it could help someone
good luck

**Comment by decpress** [comment]
Check your domain registrar DNS settings and make sure there are no unfamiliar A records that could deny permission to publish. I had a SUCURII entry that was interfering with my ability to update and publish.

**Comment by JudahGabriel** [comment]
My WordPress site updated automatically today with the new Gutenberg editor and now everything is broke, I'm getting the "Updating Failed" for every post.

It's unrelated to HTTPS.

Very frustrated with WordPress' breaking the world.

**Comment by Kokoss666** [comment]
Hello i have installed 5.02 wordpress update and cant edit the posts same problem Updating failed. I have cloudfare HTTPS and its sitll working fine, i hade no problem since i didnt install that update. i also have the https set up in general settings. pls how can i solve it, i also updated all plugins. im desperate.

**Comment by anormore** [comment]
CAN CONFIRM that installing classic editor works -- but I had to revert a post back and forth to fix.  Could have been browser cache too.

This new editor looks like a bit of a blunder... yikes.

**Comment by AByteDoc** [comment]
Another confirmation on the Classic Editor plugin solving this problem.  Glad I found this thread in the wild.

**Comment by designsimply** [comment]
@JudahGabriel @Kokoss666 @anormore it sounds like the situation you've described may be different from this issue which mentions the following error and was determined later to be a plugin conflict with WP Cerber and resolved by an updated they provided:

> The hook name can only contain numbers, letters, dashes, periods and underscores.
> index.js?ver=153025076:1

If your issue does not involve that same error, may I please ask that you post the details of your case to https://wordpress.org/support/forum/how-to-and-troubleshooting/ and include any details you have such as the WordPress version you are currently running, any active plugins which might have a conflict (especially security related plugins) and if at all possible the error that appears in your web browsers developer tools in the console panel at the time you see the "updating failed" message. Providing details such as those and working with the support team to troubleshoot will help uncover the right details in the right place for a bug report that can hopefully help things get fixed up for you!

**Comment by JudahGabriel** [comment]
@designsimply Yeah, we're not running WP Cerber.

At this point, as for getting Gutenberg working, it's kind of too late for my users. I run a WP site used by non-technical users. When WP automatically updated to Gutenberg, my non-technical users couldn't post, couldn't save drafts even. The fix was reverting to the old editor.

I unfortunately don't have the time to spend debugging this issue for the WP team. My fix is simply to revert to the old editor. I suggest WP team does more work with regards to compatibility, and failing that, at least automatically report these problems so we, the users, don't become the QA team.

**Comment by designsimply** [comment]
Thanks for your feedback and sorry to hear about your situation! I understand that you are frustrated. It really sounds like your case is different than the one reported in this issue and I can't repeat the bug you reported in a test. In a case such as yours, sometimes a bit more troubleshooting is needed in order to figure out what's going on so that someone who is interested in helping with QA or debugging has an opportunity to step in and test with the needed details. For example, you mentioned:

> It's unrelated to HTTPS. I don't have WP Cerber installed. I don't know if my theme uses Advanced Fields or not.

The [support forums](https://wordpress.org/support/forum/how-to-and-troubleshooting/) can help you with troubleshooting to get the details that are needed!

**Comment by subhambapna** [comment]
I'm getting this issue one of my multi WordPress sites. So I opened the "Developer tools" and navigated to the network section and clicked on the update post button. While doing that it made 3 requests, one of the resources has a 302. When I clicked on the link of that resource, it opened the post in the old WordPress Editor style. 

<img width="1144" alt="screenshot 2019-02-07 at 1 56 08 pm" src="https://user-images.githubusercontent.com/8749944/52398807-4fb7d780-2ae0-11e9-9ba9-6c7c8768771b.png">

In another site, I got the mixed content error, but I don't know why. I've been using a Wild Card SSL for all of my websites from day 1, the entire setup was done with domains having SSL included. I'm attaching the screenshot, The developer who works for me is out of town, but how would someone who already had a full proof setup get an error like this!

<img width="1280" alt="screenshot 2019-02-07 at 1 59 29 pm" src="https://user-images.githubusercontent.com/8749944/52399029-ff8d4500-2ae0-11e9-9c81-02da979fc465.png">

I hope this issue gets resolved quickly, While I do love some features from the Gutenberg, I badly miss the old content-focused editor when it comes to editing the content, but I believe sticking to the latest tech, that's why not installing the classic editor.

**Comment by Tomygg** [comment]
Changing from Gutenberg to classic editor plugin fixed the issue for me on ([informertech.com]informertech.com(url)). One more thing: if you can't find the option to choose classic editor plugin in settings -> writing - then it means you don't have that plugin. Install the plugin (classic editor plugin), activate it and you will be able to switch between Gutenberg and classic editor plugin.

**Comment by latheva** [comment]
Thanks guys,
Changing from Gutenberg to Classic Editor plugin fixed the issue for me as well.

**Comment by subhambapna** [comment]
I could very well do that, but the theme I'm using is already Gutenberg ready. I contacted the theme developers and they said it's a WordPress issue, but they'll work on it. A few features which I use won't be available in the classic mode. Because I won't be able to add blocks and stuff.

Check the screenshot below: 

<img width="823" alt="screenshot 2019-02-21 at 3 04 42 pm" src="https://user-images.githubusercontent.com/8749944/53158637-173cf100-35ea-11e9-9809-b40ad946862c.png">

It's a block which is supported by the newest version of my theme, shifting back to classic editor won't help me get this feature. Here's the URL for reference: https://android.tutorials.how/boot-into-android-recovery-mode/

**Comment by daniellupascu** [comment]
Logging out and logging back in fixed the issue for me. Apparently there was some permission error

**Comment by blogxkomo** [comment]
> ck in fixed the issue for me. Apparently there was some per

Yes, i did it and now all fine and also worked again...

**Comment by midhunvnadh** [comment]
Finally found why this happened. It was due to another reason as of 2019.
I have prepared a video : https://www.youtube.com/watch?v=r_eVLUc70GY
This works for me :)

**Comment by watsocd** [comment]
For me the issue was HTTP vs HTTPS. I did not have a redirect set up to redirect all users to HTTPS.

If I used the HTTP version, I got this error.

If I used the HTTPS version (same files), all was good.

I installed an .htaccess file to redirect all users to HTTPS to eliminate this problem in the future.

**Comment by olereidar** [comment]
For me the issue was that I had a different "Wordpress Url" and "Web page Url" in the settings. 
Making sure both urls were the same solved the issue.

**Comment by tingyat** [comment]
Hmm, there's maybe more here than meets the eye. While the "Gutenberg" thing could largely be a newbie/new user thing - as in getting used to something that is or was new, it goes out further than that.

If the issues are related to HTTP/HTTPS, it comes back to much the same thing - as in .htaccess and the directives/settings there.
 
In my case, this issue was more of a Woocommerce thing and worse, a Woocommerce Admin thing. My "hook" was the REST.API - a Woocommerce thing.

In checking logs, error messages, WP Health Check and whatever, my issue lay within my virtual host config file. For others on shared hosting, look to your .htaccess file. In my config file, there's a part that starts off, <Directory /var/www/html...> or the equivalent thereof. In there, I had **AllowOverride None** instead of **AllowOverride All**. Changed this to **AllowOverride All** and, all is now as it should be - like working. No more, "Failed to update" while editing or managing WP pages or posts. Nor "Document not found" - as in a port 443 thing when trying at access web pages, etc.

A couple of pointers. Regarding, web-hosting, servers and security, the goal posts out there are shifting at a pace. The references here are specific to Apache and to PHP. Things in this regard deserves some serious study.

Regarding Apache, .htaccess and related stuff - there are some significant changes with many of the key directives here. No more "Deny, Allow, Deny" stuff. That's changed and largely for the better. Apache is also trying to ween users off .htaccess while WordPress seems to be happy to keep at it. With the majority of users on shared hosting, maybe there's little or no alternative. As it is, check out the Apache documentation - specifically in moving from Apache 2.2 to 2.4.xx.

Hope this helps...

**Comment by dansully** [comment]
I had these four lines in my wp-config: 
//define('WP_HOME', 'https://' . $_SERVER['HTTP_HOST']);
//define('WP_SITEURL', 'https://' . $_SERVER['HTTP_HOST']);
//define('WP_CONTENT_URL', 'https://www.MYURL.com/wp-content');
//define('DOMAIN_CURRENT_SITE', $_SERVER['HTTP_HOST']);

Note they are commented out now! Once I commented them out, I was able to set these in the settings and everything worked. Before that, they were greyed out in the settings. 

You may notice that they are greyed out in the settings. If they are, check your wp-config or a plugin to see if they are being set somewhere else.

**Comment by Abderrazzak-Hmx** [comment]
go to settings in general make sur in your wzbsite domain link that there is no www. if u add it then delete it

**Comment by ayush175** [comment]
I also faced this error in my earlier days. 
I think this article can help: https://wpbloggerbasic.com/blogs/fix-wordpress-updating-failed/

**Comment by sultanboss** [comment]
It looks like this problem is related to `https` update issue. If you are using `https` enabled via Cloudflare, all you need to update -

![image](https://user-images.githubusercontent.com/4982921/87514276-ce348380-c69b-11ea-9c75-3021f228e750.png)

Make sure links are `https`.
