### ISSUE TITLE
Empty paragraph should de-emphasize inline images

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#7661]
Not sure how best to approach this, but clicking on the plus button next to an empty paragraph with focus on the paragraph brings up inline element as the top choices:

![image](https://user-images.githubusercontent.com/548849/42161041-b1937214-7df9-11e8-9ea2-b98ea4e6a682.png)

**Comment by jasmussen** [comment]
The empty paragraph is our commandline or our "appender", and you use this commonly to insert new blocks. I think it'd be fine to de-emphasize inline blocks either by hiding the section entirely (requiring you to search if you really want it), or to at least move the Inline Elements panel down below "Most Used".

**Comment by karmatosed** [comment]
Looks like this has design feedback so closing.

**Comment by dottxado** [comment]
I have a problem with the appearing of the Inline Image block in the inserter. I always whitelist the blocks to have in the inserter just a set of needed blocks. The Inline Image block is not in my whitelist, but it keeps appearing at the top of the inserter as soon as i insert a block with a <p> inside. 
I have whitelisted the blocks both via PHP with the filter 'allowed_block_types', and via JS enqueuing the script on the 'enqueue_block_editor_assets' action. I see that the whitelist works because i have only my whitelisted blocks in the inserter, but, as described, the Inline Image keeps appearing.

**Comment by iseulde** [comment]
The Inserter seems to have changed in the meantime. Inline Elements is now moved further down. Closing, feel free to reopen if this is still an issue.

**Comment by mkaz** [comment]
Ignore any recent alerts/notifications I typed the wrong issue # in a PR.   :shakes-fist-at-automation:
