### ISSUE TITLE
Audio "Preload" settings copy in the editor are unclear

### ISSUE THREAD

**Issue by tofumatt** [WordPress/gutenberg#7726]
The audio preload settings are unclear because they are exposing implementation details from the `<audio>` tag. Instead of "Auto" and "Metadata", something like "Content" and "Metadata only".

See: https://github.com/WordPress/gutenberg/pull/7590#discussion_r200314923

**Comment by mapk** [comment]
It took me a second to figure out what was being discussed here, so I'm including a screencast of the Audio block's Inspector settings.

![audio](https://user-images.githubusercontent.com/617986/58671909-27572180-82f9-11e9-9bb0-55e22e2e47fc.gif)

**Comment by melchoyce** [comment]
This could be a good opportunity to add some help text, since this isn't a very intuitive setting:

![image](https://user-images.githubusercontent.com/2846578/59390943-8f5d2d00-8d27-11e9-8d92-e00ee42d5665.png)

**Comment by chrisvanpatten** [comment]
One other note might be that you can also opt to _not_ provide a preload setting. If you don't provide the setting, it allows the browser to determine how they want to preload the data. (Chrome uses "metadata" by default, for instance.)

Not sure how that might look — a "reset" button or something like that?

**Comment by melchoyce** [comment]
I wonder if "browser default" is worth adding as a fourth, default option in that case?

**Comment by mapk** [comment]
While I think the additional text helps, it feels like a lot to read. Here's a pass at trimming it down. We also call it "Preload" and then mention "Load." Does that cause any confusion?
Preload
1. File and metadata
2. Metadata only
3. Don't load anything

**Comment by michelleweber** [comment]
I don't love the preload/load thing; the preload seems a little pointless here, since functionally we're using preload/load to mean the same thing here and it's not like there are other load-specific settings that need to be distinguished. If we're going to use both terms, they should mean two different things.

For me, a relatively non-technical person, what would be more helpful than text explaining each choice would be text explaining why I should care about this options / why I'd make one choice over another -- all the help text in the world doesn't actually help me if it doesn't help me decide. That then gives context to the options, so you don't have to include help text for every option. So something like:

> **File Options**
> Decide how much of the audio file preloads with the page. The less you preload, the faster your page load speed.
> 
> -  Preload audio and metadata
> 
> - Preload metadata only
> 
> - Don't preload anything

**Comment by melchoyce** [comment]
Thanks @michelleweber, this helps a lot.

Here's the revised copy:

![image](https://user-images.githubusercontent.com/2846578/59474016-edf2db80-8df9-11e9-8e8f-0e3076cca23e.png)

I still think we need to somehow explain what "metadata" entails.

**Comment by michelleweber** [comment]
You could avoid metadata altogether and call it something like "Title and artist info" -- I know it's not 100% accurate, but I'm not sure it matters? Otherwise, I think explaining adds too much text, and I feel like you should rely on the link to do the explaining for you.

**Comment by melchoyce** [comment]
I wonder if we could use `abbr` to define metadata, or if that would be breaking the rules?

**Comment by melchoyce** [comment]
Minor copy adjustments: 

![image](https://user-images.githubusercontent.com/2846578/59474318-1af3be00-8dfb-11e9-87cb-97f530c50d0f.png)

**Comment by sarahmonster** [comment]
It feels like this is moving toward the right direction here—this is such a complicated concept to explain well! Maybe instead of "File Options", we call it "Load Options" or "Preload Options"?

Instead of "The less you preload...." we could put load speeds next to each option, so:

- Preload everything (slow)
- Preload file information (medium)
- Preload nothing (fast)

**Comment by mapk** [comment]
> Instead of "The less you preload...." we could put load speeds next to each option

What would each of those speeds be relative to? "Preload nothing" is _fast_ when loading the page, but _slower_ when trying to load the actual audio file. This could still work, but I feel if we remove that second sentence from the description, it becomes a bit too vague.

**Comment by chrisvanpatten** [comment]
And also, as a reminder, these are only _hints_ for the browser. Depending on your browser and configuration, browsers are allowed to completely ignore this setting and download whatever they want.

> Suggest that browsers preload some or all of your audio file when your page is opened.

**Comment by melchoyce** [comment]
Let's not overthink this — the goal is to explain _what_ this setting is, and _why_ it's important. We don't need to get super specific, and we can put technical details and additional information in the documentation.

**Comment by mtias** [comment]
Closing this for now, if we run into some better suggestions we can always revisit.
