### ISSUE TITLE
No indication that the inserter is scrollable

### ISSUE THREAD

**Issue by emcarru** [WordPress/gutenberg#776]
I only discovered that the inserter is scrollable by chance, because I  was tabbing through the options. I would suggest that the scrollbar is always visible, or at least there is some other indication that the user can scroll down in this box:
![inserter](https://cloud.githubusercontent.com/assets/2886550/25995013/94fcbb96-3710-11e7-8a13-6cf4de2b2f9d.jpg)

**Comment by aduth** [comment]
Can you clarify which browser and operating system (including versions) you use?

Wondering if this might be default MacOS behavior of hiding scrollbars. I force them to [always be visible](http://cdn.osxdaily.com/wp-content/uploads/2011/08/howto-always-show-scroll-bars-mac-os-x-610x568.jpg) and see the inserter as scrollable:

![image](https://cloud.githubusercontent.com/assets/1779930/25998906/141de3fc-36f1-11e7-9340-a7f0e55b1a0d.png)

**Comment by emcarru** [comment]
Yes sorry! You are correct, I'm on a mac (latest OS), and I would also assume this is the default behaviour, as I have not set them to always be visible (but I am now changing that!).

**Comment by aduth** [comment]
Okay, in which case I'd say this can be closed as expected operating system behavior. The only other option would be to create a custom scrollbar, but this tends to be fraught with all sorts of challenges and probably not necessary for what we want here (cc @jasmussen just in case).

**Comment by aduth** [comment]
In the prototypes there's also a "shadow" effect at the bottom of the panel to indicate that there's more to see. We probably want that in the plugin as well, and could help discoverability here.

Related: #98

Maybe we can reopen this one or #98 and repurpose as the task for implementing this?

**Comment by jasmussen** [comment]
I think it's a fair point. 

Noting that it's an issue only on Macs, where the scrollbars fade out. And yes, the shadow is meant to indicate that there's more content, however I can see how that might not be enough.

Since we also have #656 (scroll bleed) to worry about, perhaps we can group a bunch of tasks together into one that I can take care of? That would be:

- Make scroll indicator shadow more visible
- Perhaps show scrollbar all the time, and at the same time fix scroll bleed by using this trick https://codepen.io/joen/pen/wGbBoe

Thoughts?

**Comment by jasmussen** [comment]
Reopening.

**Comment by aduth** [comment]
>Perhaps show scrollbar all the time

Can you clarify what you mean by this @jasmussen ?

**Comment by jasmussen** [comment]
> Can you clarify what you mean by this @jasmussen ?

Yes. Since the autohiding fancy scrollbars are a Mac only thing, perhaps we can use the `::-webkit-scrollbar` CSS styles to style them, like in that codepen. They'll look exactly like native scrollbars, but they'll essentially be custom ones. Incidentally this forces the scrollbars present, even when MacOS sets them to being off.
