### ISSUE TITLE
Columns Block (beta): columns do not transition properly from 3.1 to 3.2, until after re-save

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#7825]
**Describe the bug**
I'm not sure how important this is, since the Columns have be designated "Beta."
None-the-less, columns created in 3.1 are corrupted in the front end in 3.2, until after resave.

**To Reproduce**
1. Create columns in 3.1, and add content
2. Upgrade to 3.2
3. See the columns (front-end) are corrupted
4. On back-end, re-save.
5. See the columns (front-end) are corrected

**Expected behavior**
It should have transitioned.
Again, not sure how super-important backward-compatibility is on a "Beta" block.

**Screenshots**
Back-end:
![backend](https://user-images.githubusercontent.com/30901407/42453585-337cc5a8-835b-11e8-99f6-79bbb54d216a.jpg)

Corrupted after upgrade to 3.2:
![project2](https://user-images.githubusercontent.com/30901407/42453621-4c8c27dc-835b-11e8-97ee-30ec920a119a.jpg)

Fixed after resave on 3.1:
![project1](https://user-images.githubusercontent.com/30901407/42453641-595f4c00-835b-11e8-8deb-ce573afae143.jpg)

**Comment by designsimply** [comment]
> Not sure how super-important backward-compatibility is on a "Beta" block.

This is a good point! It does seem like people may be ignoring the fact that the columns block is very much still in beta, and that puts us in a tough spot since it is a very cool concept and appears to be wanted! I think the best course of action for this case is to go forward without the expectation of backward compatibility since the feature (by nature of being beta) was never technically at a stable release to be backward compatible with.

Agree? Any 2nd opinions on this one? I'd love some input from others.

**Comment by chrisvanpatten** [comment]
@designsimply agreed although I also wonder if the underlying issue should be solved still, since similar deprecations might be necessary in the future, and might be desired by block implementers? Perhaps it should be opened as a separate issue..?

**Comment by GlennMartin1** [comment]
This only affects users running Gutenberg 3.1 and earlier AND only if they're using Columns (beta).

That is, no doubt, a very small subset of people. For those that this bug may still affect, all they need to do is resave that page/post, and this issue is forever fixed.

Plus, considering that Columns block was beta, the expectations shouldn't be too high.

Closing this issue.
