### ISSUE TITLE
Classic Editor plugin setting and label are confusing and misleading

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#7915]
After installing the Classic Editor plugin, it provides a new option on the **Settings > Writing** screen. The label and description for this checkbox are very confusing and misleading.

The setting is called `Classic editor settings` and the description says <em>"Do not replace the editor. Add alternate links to the Posts and Pages screens for editing with the Classic editor"</em>.

This leads me to believe that if the checkbox is ticked, then the Classic Editor will not be replaced. This is the exact opposite of what it does though. When the Checkbox <strong>is</strong> ticked, if I click on a Page/Post title, it starts editing with the new Block Editor (Gutenberg). When the Checkbox is <strong>NOT</strong> ticked, that's when I still get the Classic Editor.

I would like to propose that you change the wording to something along the lines of <em>"Replace Classic Editor with the new Block Editor. Add alternate links to the Posts and Pages screens for editing with the Classic editor."</em>

**Comment by designsimply** [comment]
Closing in favor of https://wordpress.org/support/topic/settings-and-label-are-confusing/ because this repo should not be used directly for plugin issues and the plugin support forum is the right place as you mentioned in that forum request!

Link for reference: https://wordpress.org/plugins/classic-editor/

Screenshot for reference: 

![screen shot 2018-07-16 at mon jul 16 10 43 20 am](https://user-images.githubusercontent.com/1119271/42771647-218f8d32-88e5-11e8-95fc-a799977d27b5.png)
<sup>Seen at http://alittletestblog.com/wp-admin/options-writing.php running WordPress 4.9.7, Gutenberg 3.2.0, and Classic Editor 0.2 using Firefox 61.0.1 on macOS 10.13.5.</sup>
