### ISSUE TITLE
Previews: "Save Draft" does not save title changes if more than one title change is made and previewed in the same session

### ISSUE THREAD

**Issue by Emilybkk** [WordPress/gutenberg#7927]
**Describe the bug**
After Save Draft I can't change the title anymore. No changes were apply.

**To Reproduce**

Add new post
Add Title
Save Draft
Preview
Back to Gutenberg and change title
Save Draft again
Preview 
- nothing change
Back to Gutenberg and Save again
Preview 
- nothing change
Back to Gutenberg and try to Save it again
- it ignore the changes! 
Preview
- nothing change

**Screenshots**
[https://youtu.be/vUY1FgtZ-v0](https://youtu.be/vUY1FgtZ-v0)

**Desktop (please complete the following information):**
Chrome

**Smartphone (please complete the following information):**
MAC High Sierra

**Additional context**
PHP 7.0
WordPress 4.9.7
No other plugins install, No Cache.

**Comment by designsimply** [comment]
I tested and this doesn't happen every time for me! I was able to reproduce the problem only for a brand new post and only if autosave isn't triggered.

**Video:** [1m38s](https://cloudup.com/cc2_EkqMrKn)
<sup>Tested and confirmed with WordPress 4.9.7 and Gutenberg 3.2.0 using Firefox 61.0.1 on macOS 10.13.5.</sup>

![title-not-saved](https://user-images.githubusercontent.com/1119271/42639072-6ade7fa2-85ac-11e8-8d0e-81e8adecb043.png)

I'm adding the `Needs Testing` label to this one to get help confirming the following:

* title updates work on previously saved and reopened drafts
* title updates always work if autosave triggers instead of clicking "Save Draft"
* can you think of any other oddities?

**Comment by Emilybkk** [comment]
@designsimply It happen for me with the previously saved drafts post. I have create post sometime ago and then for the final I try to change the title that is when I find out.

**Comment by Emilybkk** [comment]
And in my video it is brand new drafts.

**Comment by designsimply** [comment]
🤔 it works every time for me on previously saved drafts, I only see the problem for brand new posts.  Let's try to get another tester for that if we can.

@Emilybkk may I confirm one more thing with you? Does the problem only happen if you click "Save Draft" _before_ an autosave happens?

**Comment by Emilybkk** [comment]
@designsimply Yes confirm It happen when click "Save Draft" _before_ an autosave.

**Comment by designsimply** [comment]
Closed #8898 as a duplicate after re-testing and updated the title here to hopefully be a bit more accurate and helpful. ([3min](https://cloudup.com/cC6U6iNcGcS))

**Comment by jorgefilipecosta** [comment]
This bug is already fixed in master.

**Comment by couponrim** [comment]
I got this issue so many time one WordPress 5.0.3 but I don't know how to fix it. I hit the publish button then I check out the post the title got empty and the social media network got a lot of troubles when I using automation tools for sharing a new post after publishing. The social media network will look ugly with no title.
WOW. I'm not happy about this issue. Is it a plugin confliction?

**Comment by couponrim** [comment]
@designsimply Thanks for your reminder. I just searching for some helps. I can not login to my WordPress dot org account, so that why I can not submit my issues there. When I log in at the login screen, it says my account has been disabled. I don't login with wrong password but not sure what happened.  My WordPress org account opened in 2015 and I just using it recently. 

--------------------------------------------------------
Anyway, thank you so much for your helps. I will hire some freelancers fixing my issues.
Have a nice day.
