### ISSUE TITLE
Blocks unavailable when `new WP_Query` is used inside render callback

### ISSUE THREAD

**Issue by jomurgel** [WordPress/gutenberg#8035]
**Describe the bug**
Use of a `new WP_Query` throws no errors, but breaks admin render of blocks using them.

**To Reproduce**
1. Utilize `new WP_Query` over a `get_posts` or `get_recent_posts` function
2. Update block and save.
3. Refresh page (or exit and return)
4. Will see a random post or will return a post in class editor.

`post_content` does, in fact, save the block data as expected and front-end render is fine. This effects only admin-facing blocks.

**Potentially Related**
#5572 
#7427
#4733

**Expected behavior**
Reload/return to post, should see Gutenberg block.

**Screenshots**
Block added:
![screenshot 2018-07-18 13 18 19](https://user-images.githubusercontent.com/5230729/42902819-134515d6-8a8d-11e8-9d97-a80bcce59494.jpg)

Refresh (when `new WP_Query` is used instead of `wp_get_recent_posts` ):
![screenshot 2018-07-18 13 16 59](https://user-images.githubusercontent.com/5230729/42902845-24ce49e4-8a8d-11e8-801c-2ec833b7b671.jpg)

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.6
 - Browser ALL

**Additional context**
- Occurs with v 3.2

**Comment by chrisvanpatten** [comment]
I downloaded your block and messed around a bit. To be more specific, it's not exactly related to `WP_Query`, it's the use of `$query->the_post()`.

If you run the WP_Query and just use the `$query->posts` array directly (iterate over it, directly access `$post->title`, `$post->ID`, etc.) it will work okay, because it won't override the global `$post`.

Also related to #7582 and core [#18408](https://core.trac.wordpress.org/ticket/18408).
