### ISSUE TITLE
Documentation: wp-editor and wp-i18n dependencies

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#8071]
https://wordpress.org/gutenberg/handbook/blocks/writing-your-first-block-type/

This should list also at least these dependencies for scripts:
- wp-editor
- wp-i18n

It's best if you listed all Gutenberg-related JS and CSS.

**Comment by mkaz** [comment]
Those two packages are not a dependency of the initial block example, which is why they are not included. The block example is intentionally left as simple as possible to introduce the concepts, its better for the new developer to learn gradually than all at once.

The wp-i18n is documented [here in Gutenberg handbook]https://wordpress.org/gutenberg/handbook/designers-developers/developers/internationalization/) and [here in packages](https://wordpress.org/gutenberg/handbook/designers-developers/developers/packages/packages-i18n/) and being updated in #13909 

The wp-editor is documented [here in Gutenberg handbook](https://wordpress.org/gutenberg/handbook/designers-developers/developers/packages/packages-editor/).

I'm closing this issue, if there is something specific that needs updating or adding, please reopen with more information.
