### ISSUE TITLE
`illegal string offset` warnings in browser console

### ISSUE THREAD

**Issue by 375942753** [WordPress/gutenberg#8097]
When I open the article editor page, it will report the error message directly. 

Warning:illegal string offset 'name' in /gutenberg/lib/client-assets.php on line 1337
Warning:illegal string offset 'slug' in /gutenberg/lib/client-assets.php on line 1337

**Comment by 375942753** [comment]
yes of course！
When I start the plug-in and open the article to edit the page。

I'm sorry, I don't know how to insert pictures in 'GitHub'. Can you leave your mailbox? I send you the detailed information through the mailbox!
My mailbox is: 375942753@qq.com

My version of 'WordPress' is 4.9.7.



The version of the plug-in is: 3.3.0.



The browser is used: Firefox.



The operating system used is: window10.

**Comment by Soean** [comment]
This lines are about the custom colors and their slug.
Code: https://github.com/WordPress/gutenberg/blob/master/lib/client-assets.php#L1337

Which Theme are you using? Maybe there are some problems in the Color definition. See: [Block Color Palettes](https://wordpress.org/gutenberg/handbook/extensibility/theme-support/#block-color-palettes) for the right structur.

**Comment by designsimply** [comment]
To add an image in GitHub, just drag and drop the image onto your reply.

If you have any caching plugins or caching systems installed on your server, could you try clearing those?

Can you try updating to the latest available version of Gutenberg and test again? Several updates have been made since you first posted.

I will close this and we can continue the discussion even with the issue closed.
