### ISSUE TITLE
Concern regarding floating toolbars on small blocks of text

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#810]
I've been trying to spend some quality time with the prototypes these last couple days. The open feel of the editor is awesome, but I keep getting hung up on the number and placement of buttons and toolbars.

Early on in planning, there was the goal that the editor should make it easy to write. It shouldn't encourage too much formatting up front. Type type type type type.

Here are two screenshots from v3 of things I've come across that make me feel cramped, overwhelmed, and almost forced to format:

![image](https://cloud.githubusercontent.com/assets/1238696/26116777/293a8454-3a19-11e7-9127-f7bd96002452.png)

![image](https://cloud.githubusercontent.com/assets/1238696/26116779/2c75856a-3a19-11e7-8eaa-d88e35d72a2b.png)

I know we talk about trying things out to see how they feel and this feels like too many buttons too close together. v2 isn't as bad and uses a semi-fixed toolbar that feels a bit better but still encroaches on the block.

There will probably always be a debate about a fixed vs. floating formatting bar, but it feels like this is a moment to check in on that. I think there are two variations of "fixed" to consider:

1. Fixed to the top of a block (roughly what v2 does)
1. Fixed to the top of the window/"editor"/screen

I'd sure like to see a prototype with option 2 if there's interest.

I'll also throw out the point that while a floating toolbar may be closer to where someone's cursor is, the fact that it moves around may not actually make it faster or more efficient to use. Muscle memory is powerful and fixed toolbars have that going for them.

**Comment by jasmussen** [comment]
Thanks for testing. This seems to have been specific to the prototypes, which are admittedly the foundation for the plugin we're building. But can I kindly ask that you test again on the plugin? The easiest way to do that is to click the "Test Gutenberg Editor" link in the bottom of this page: https://testgutenberg.wpkonsulterna.se/ —  then you can try the full on plugin. There have been lots of improvements since the prototype days, including a sticky toolbar that scrolls with you down the page on long blocks. Curious to know which, if any, of your concerns are addressed there.

**Comment by jasmussen** [comment]
Closing for now as prototype specific, but let's reopen or refile if the problem reappears.
