### ISSUE TITLE
Insertion points get in the way of rich text inputs/etc

### ISSUE THREAD

**Issue by ktmn** [WordPress/gutenberg#8100]
**Describe the bug**
![](https://i.imgur.com/IiSoaeE.png)
The insertion points are marked in red. When you place the cursor in the red area the cursor will be `default`, while a little lower the cursor will be `text` allowing to select the rich text area and insert text. 
**You can only click on the lower half of the text to edit it.**

**Expected behavior**
Maybe there's a better way without overlaying things in the space that can potentially contain anything that may need to be interacted with (e.g. #8070).
It's mostly a problem with smaller blocks that may only have 1 line of text, and at small font sizes the rich text area may become completely unselectable via pointer.

**Screenshots**
![](https://i.imgur.com/0LlyMKY.png)

**Desktop (please complete the following information):**
 - OS: W10
 - Browser: Chrome
 - Version: 67

**Additional context**
Gutenberg 3.3.0

**Comment by youknowriad** [comment]
I think this is fixed. At least I can't reproduce (using Twenty Nineteen)

**Comment by ZebulanStanphill** [comment]
@youknowriad

Just to clarify, the inserter still covers up a portion of the blocks, but it is now vertically centered, rather than overlapping the blocks that follow but not the blocks above. With the core blocks, this means there isn't really any issues, since they all have margins/padding on their top and bottom. The inserter may still overlap blocks with smaller top/bottom margins/padding, however.

I made an issue for this general inserter issue: #8883. However, it was closed to consolidate discussion in #8881, which was technically a separate issue... actually, it was a duplicate of this issue (which I was not aware of at the time).

**Comment by ZebulanStanphill** [comment]
@youknowriad Good point. Unfortunately, this reduces the WYSIWYG-ness of the editor, doesn't it? I guess in a way this sort of ties into the whole changing-block-appearance-when-selected topic that has been discussed in #9628. By default, blocks should look like they do on the front-end, but the automatic margins are an obstacle to actually having this be a reality.

**Comment by youknowriad** [comment]
It does, I do think there were some discussions/PR about it but no consensus found as no ideal alternative at the moment.
