### ISSUE TITLE
Select control: null value to empty string

### ISSUE THREAD

**Issue by iamzozo** [WordPress/gutenberg#8138]
Here the select control simply gets the option value:
https://github.com/WordPress/gutenberg/blob/master/packages/components/src/select-control/index.js#L53

However, when using attributes with a null default value, the option value gets the label itself.
What do you think to check against null and use empty as default? Or just use empty strings for default?

`{ option.value || '' }`

Here is the example:
```
const options = [ { label: __( 'All' ), value: null }, ...categories ]
```
```
<select name="category">
    <option value>All</option>
    <option value="1">First category</option>
    <option value="2">Second category</option>
</select>
```

Here the value will be **All** by default, and ServerSideRenderer will send `All` as value.

**Comment by nerrad** [comment]
Hey there, sorry for the long time before getting a reply to your issue!

I think semantically, we want to keep current behaviour so that the provided value is explicitly used. I'm not sure that the expectation you gave for your example is correct (unless I'm reading things wrong).  If you have `<option value>All</option`, then the value received on a post is an empty string for the "All" option.  The only time "All" would get returned is if you had something like this `<option>All</option>`

If there are any additional reasons to add why this is a necessary enhancement to make feel free to add them to this issue but for now I'm going to close it.
