### ISSUE TITLE
Support subsets of block types in block templates

### ISSUE THREAD

**Issue by mboynes** [WordPress/gutenberg#8142]
As a theme and plugin developer, I want to be able to define positions in block templates that are restricted to a subset of block types so that I can maintain structure in page templates while still supporting flexibility for similar media.

---

When defining block templates, I've found myself wanting to support multiple block types in a template position, which as best I can tell is not yet possible. A straightforward example of this is defining a region in a post that can be either an image _or_ a video.

## Examples

This is an example of one option for how we might define a region that could be either an image or a video, using a new block type `block-set`:

```php
$post_type_object->template = [
    [ 'core/block-set', [
        [ 'core/image', [] ],
        [ 'core/video', [] ],
    ] ],
];
```

**Comment by SuperGeniusZeb** [comment]
Currently, the way you would do something like this is by using a block that only allows certain blocks as children, like the Media Area child block in #7414. Not sure if that is the best approach, though.

**Comment by designsimply** [comment]
@mboynes are you able to do what you're after using child blocks?

**Comment by mboynes** [comment]
@designsimply that's slightly different from what I'm suggesting -- or at least considerably more work. Going that route, and please correct me if I'm mistaken, requires one to create a custom block, in that custom block define the allowed child blocks, then use the new custom block in the template. I think this would be a useful enough feature to warrant core support, and not make developers go through that level of effort.

Possibly related: #7763, if `InnerBlocks` would eventually be used in the solution for this feature.

**Comment by nerrad** [comment]
I think you can now do something like what is requested here within template registration via [InnerBlocks](https://developer.wordpress.org/block-editor/developers/block-api/block-templates/#api) and also [nested templates](https://developer.wordpress.org/block-editor/developers/block-api/block-templates/#nested-templates).

If that is not the case please feel free to comment with more details about your use-case.  There's been a number of changes in the api since this issue was created and it's possible there may be an existing solution.  (We can re-open this issue if necessary).
