### ISSUE TITLE
'View post' links shown when post type is not publicly_queryable

### ISSUE THREAD

**Issue by jchristopher** [WordPress/gutenberg#8151]
**Describe the bug**
When working with a post type that has `publicly_queryable` set to `false` links are shown to view the post on the front end, which leads to a `404`

**To Reproduce**
1. Register custom post type with `'publicly_queryable' => false`
2. Add new post for that post type

**Expected behavior**
No 'view' links shown

**Screenshots**
![2018-07-23 at 4 58 pm](https://user-images.githubusercontent.com/10412/43102685-bfc3b1ae-8e99-11e8-9742-283ee6a59901.png)

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - Browser Firefox
 - 62.0b8

**Additional context**
Gutenberg version 3.3.0

**Comment by designsimply** [comment]
👋😊 hi @jchristopher!

**Comment by Soean** [comment]
This was implemented for the preview button in #6232. We have to implement it for the other preview links in the editor as well.

**Comment by danielbachhuber** [comment]
Flagging this as `Needs Design Feedback` because it's more than just disabling the preview link:

<img width="745" alt="image" src="https://user-images.githubusercontent.com/36432/43294350-ad069854-90f3-11e8-87a1-985a22983885.png">

We need some alternate UX for this:

<img width="376" alt="image" src="https://user-images.githubusercontent.com/36432/43294368-bf9f2666-90f3-11e8-9ce1-66659cccd76f.png">

**Comment by danielbachhuber** [comment]
@karmatosed What should be shown instead?

**Comment by karmatosed** [comment]
As discussed in core triage session, here is a mock of the button removal. It doesn't seem to make sense to both show link and buttons.

![postpublished](https://user-images.githubusercontent.com/253067/47110617-406b0080-d249-11e8-8031-fe48e0efa718.png)

**Comment by youknowriad** [comment]
Fixed in #12046
