### ISSUE TITLE
 has_cap was called with an argument that is deprecated

### ISSUE THREAD

**Issue by joyously** [WordPress/gutenberg#8215]
**Describe the bug**
Gutenberg 3.3 
There is a deprecation notice from gutenberg_init.
wp-includes/functions.php:4032 - has_cap was called with an argument that is deprecated since version 2.0.0! Usage of user levels is deprecated. Use capabilities instead.
apply_filters('replace_editor'), WP_Hook->apply_filters, call_user_func_array, gutenberg_init, require_once('wp-admin/admin-header.php'), require('wp-admin/menu-header.php'), _wp_menu_output, current_user_can, call_user_func_array, WP_User->has_cap, _deprecated_argument, do_action('deprecated_argument_run')

**To Reproduce**
1. Open the demo content.
2. Look at Debug Bar deprecated list.

**Expected behavior**
Nothing to see in Debug Bar.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Firefox 61.0.1

**Comment by pento** [comment]
Thank you for the bug report, @joyously!

Apart from Debug Bar and Gutenberg, do you have any other plugins installed?

Which theme are you using?

**Comment by joyously** [comment]
There are 15 other plugins, none of which affect the editor.
I'm using my own theme, which is not doing anything with Gutenberg.

**Comment by pento** [comment]
Do you see the error when you visit a different `wp-admin` page, or in the Classic Editor?

Could you please try deactivating your plugins, and seeing if the error still occurs?

If the error goes away, reactivate your plugins one at a time, to find which one is causing the issue.

If the error still occurs with your plugins deactivated, please switch your theme to one of the WordPress default themes, and see if the error still occurs.

The error is occurring when the admin menu is being generated: while Gutenberg function names appear in the call stack you posted, the error is not necessarily being caused by Gutenberg, it could be caused by any plugin that adds items to the admin menu.

**Comment by joyously** [comment]
OK, my mistake. It appears to be WP Auto-Suggest.
But even though I left Gutenberg activated (so it has menu items), it now isn't in the call stack of the notice.
Feel free to delete this issue.
