### ISSUE TITLE
Make custom HTML blocks resizable

### ISSUE THREAD

**Issue by Pikamander2** [WordPress/gutenberg#8245]
![image](https://user-images.githubusercontent.com/5246872/43305154-a65a7506-9144-11e8-8583-840ac4dfdf9b.png)

I don't always need to see every line of code in a custom HTML block, especially when I'm editing a completely different element. Sometimes I just want to minimize it or limit it to a certain height.

Please consider adding a stretch handle or minimize button.

**Comment by mtias** [comment]
We might also consider minimizing by default when the block is not focused.

**Comment by karmatosed** [comment]
I would 👍 the ides of resizing and also minimising by default.

**Comment by chrisvanpatten** [comment]
I'm happy to take a crack at this with the new `ResizableBox` component once #10396 lands.

**Comment by karmatosed** [comment]
Thanks @chrisvanpatten!

**Comment by nicolad** [comment]
Hello @chrisvanpatten, I noticed that this issue hasn't been updated in a while.
I've started a related PR: https://github.com/WordPress/gutenberg/pull/14730
Please advise on what was your initial thought of using `ResizableBox` in the context of this issue.

**Comment by noisysocks** [comment]
This issue is a little out of date as we removed CodeMirror from the HTML block in https://github.com/WordPress/gutenberg/pull/10396. 

#16187 adds a maximum height to the HTML block which fixes the poor UX of having every single line in the HTML block shown at all times.

I'll leave this as closed. We can look into further improvements to the HTML block when if we ever re-add syntax highlighting (see https://github.com/WordPress/gutenberg/issues/10423).
