### ISSUE TITLE
Ctrl+A unexpected behaviour

### ISSUE THREAD

**Issue by LZL0** [WordPress/gutenberg#8269]
**Describe the bug**
Ctrl+A unexpected behaviour
I believe this behaviour to be unexpected, please correct me if I am wrong.

https://www.youtube.com/watch?v=-jXVM5zH8Qg

Disclaimer: The first time it works, but after that it starts to act this way.

1. Click into a block.
2. Press Ctrl + A.
3. Gutenberg acts as expected, only the current paragraph is being selected.
4. Click into another block or exit the current one and click into it.
5. Press Ctrl + A again.
6. All the blocks are selected.
If you reload the page on the first Ctrl+A command it would function as expected.

Gutenberg version 3.3
WordPress version 4.9.7

**Comment by LZL0** [comment]
Must be connected with Issue #8268

**Comment by designsimply** [comment]
I found a description of the expected behavior in #4600:

<blockquote>Focus an Editable. meta+a should select all contents. Press meta+a once more to select all blocks.</blockquote>

@iseulde what is the expected behavior if you press `meta+a` then click on a different block and press `meta+a` again?

**Comment by jasmussen** [comment]
> what is the expected behavior if you press meta+a then click on a different block and press meta+a again?

The expected behavior is this:

- Set focus in a paragraph, press meta+a to select all contents in that paragraph
- Only when all the text of that paragraph is selected, should a subsequent meta+a expand the selection to all blocks.

This also means that if you select all text in one paragraph, select a different paragraph, you've effectively "unset" the selection for the previous block, and meta+a should select all the text in the new block before expanding.

Noting that if you _deselect all blocks_ and press meta+a, all blocks should be selected. 

Noting that this works as expected for me in the current release version of the plugin in Chrome, so this could be a browser or operating system specific bug. See also #7678 and discussion here https://github.com/WordPress/gutenberg/issues/4369#issuecomment-401211194

**Comment by mtias** [comment]
Closing as works as expected. There are some incosistencies in browsers that are still being worked on.
