### ISSUE TITLE
Clicking on "Post Settings" should not deselect a block

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#827]
When a block is selected, clicking on post settings is meant to open the inspector for that block, so it should not be deselected in the process. Also, clicking on the panel should not deselect the block.

Thinking of it, maybe only clicking on the white canvas of the editor deselects a block, not the toolbar or the sidebar.

**Comment by jasmussen** [comment]
> Thinking of it, maybe only clicking on the white canvas of the editor deselects a block, not the toolbar or the sidebar.

👍 

See also #657, #669 and #712.

**Comment by aduth** [comment]
>Thinking of it, maybe only clicking on the white canvas of the editor deselects a block, not the toolbar or the sidebar.

What does this mean in less clicky-cursor terminology? Currently, selection is bound to focus entering and leaving the block. Moving between adjacent blocks shifts selection because of a sequence of focus leaving the previous block and focus entering the next block. This works both for _clicking_ but importantly also for tab navigation. So when we say we want selection to be more sticky, what is it exactly that we want to happen? That a block isn't unselected when focus leaves? How does tab navigation work in this scenario, since it would never deselect a block?

**Comment by mtias** [comment]
It means that the concepts of "selected block" and "focused block" should be two slightly different ones, because if a block is focused and you click on the "post settings" item, we should lose focus but not selection.
