### ISSUE TITLE
Plus sign not showing up after enabling "Edit as HTML"

### ISSUE THREAD

**Issue by mintplugins** [WordPress/gutenberg#8273]
**Describe the bug**
I'm not sure where this started, but I believe it might be related to turning "Edit as HTML" mode on and off. Either way, the "plus" button to add a new block is not showing up for me, despite hovering my mouse all over the place below the current block. 

**To Reproduce**
1. Write in a block. 
2. Flip it to "Edit as HTML".
3. No plus sign shows up below. 

**Expected behavior**
I expect a plus sign to show up below the current block, in order to help me add a new block quickly. 

**Expected Screenshot:**
<img width="928" alt="screen shot 2018-07-29 at 3 39 09 pm" src="https://user-images.githubusercontent.com/1638128/43370019-a9a634cc-9345-11e8-937d-96a9c3bdfb78.png">

**Screenshot of (possible?) bug**
<img width="1163" alt="screen shot 2018-07-29 at 3 34 10 pm" src="https://user-images.githubusercontent.com/1638128/43369986-37792364-9345-11e8-9c55-f544874bf7bc.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: 67.0.3396.99

**Additional context**
- Please add the version of Gutenberg you are using in the description.
Version 3.3.0

**Comment by designsimply** [comment]
I tested inserters, the (+) icon, and found that I am able to see the inserter to the left in visual or html mode _if_ a placeholder for it already exists or if I add a block using the top toolbar while in html editing mode. I also found that the left block inserter doesn't appear in visual editing mode either unless it has already been added (but it's easier to add since simply pressing enter starts a new block in paragraph mode and it makes sense you would not want pressing enter to do the same in html editing mode). I don't think this is related to turning "Edit as HTML" mode on, and I think it's working as expected. Because of that I am closing this issue for now but will still see replies and we can re-open later if needed or if my explanation isn't sufficient.

**Video:** [2m17s](https://cloudup.com/cnnZEPgAaDq)
<sup>Tested on alittletestblog.com running WordPress 4.9.7 and Gutenberg 3.3.0 using Firefox 61.0.1 on macOS 10.13.6.</sup>

For reference, the following two screenshots show how to add new blocks with the inserter, the (+) icon, while in html editing mode:

![screen shot 2018-07-30 at mon jul 30 12 56 55 pm](https://user-images.githubusercontent.com/1119271/43417502-5fc1e474-93f8-11e8-92f6-06cc0e8edf19.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14083&action=edit running WordPress 4.9.7 and Gutenberg 3.3.0 using Firefox 61.0.1 on macOS 10.13.6.</sup>

**Comment by mintplugins** [comment]
@designsimply Do you know why the UX changes? Why isn't it consistently showing the (+) button below, as seen here:

https://user-images.githubusercontent.com/1638128/43370019-a9a634cc-9345-11e8-937d-96a9c3bdfb78.png

In my opinion, the UX should always be the same, regardless which which blocks you have on the page, and which state they are in. That (+) button should not be affected by blocks at all.

**Comment by mintplugins** [comment]
I guess the question here really is, why isn't there _always_ the placeholder? It should always be there, or it should never be there. Personally, I find it being there conditionally quite clunky.

**Comment by mintplugins** [comment]
P.S. thank you for posting the video - that definitely helped. But it highlights why this is quite confusing. 

Around 1:30, you click "Remove Block" on a block that does not yet exist, according to the "Add Block" (+) button. So I'm quite confused about what I am looking at. How can you remove a block that doesn't exist yet?

Is the block there? Or is it just a placeholder? If it's just a placeholder, why does the remove option say "Remove Block" when it should say "Remove Placeholder"?

In the placeholder, the "Add Block" text and the "Remove Block" text are on conflict with each other. 

The words "Add Block" indicate that the block _does not_ yet exist. 
The words "Remove Block" indicate that the block _does_ already exist. 

Perhaps the words "Add Block" should change to "Choose block type" and it should use a different icon than the (+) sign, since that's the action it seems to be prompting.

**Comment by mintplugins** [comment]
I'll open this as a new issue since the scope has now changed.
