### ISSUE TITLE
How to style alignfull and alignwide

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#8289]
The documentation https://wordpress.org/gutenberg/handbook doesn't contain information on how to style `alignfull` and `alignwide`.

- `jQuery('body').width()` returns `1884`
- `window.innerWidth` returns `1901`

When I do:

```
.alignfull {
	margin-left: calc( -100vw / 2 + 100% / 2 );
	margin-right: calc( -100vw / 2 + 100% / 2 );
	max-width: 100vw;
}
```

then the resulting container is `1901px` wide (thus producing horizontal scrollbar). To make it right it would have to be `1884px`.

Can you please clarify how themes should style `alignfull`?

These places (top google results) contain wrong styling information:
- https://themehybrid.com/weblog/align-wide-and-full-classes
- https://themeshaper.com/2018/02/15/styling-themes-for-gutenberg/
- https://richtabor.com/gutenberg-image-alignments/
- https://jasonyingling.me/implementing-gutenberg-image-alignment-options-theme/
- https://www.billerickson.net/getting-your-theme-ready-for-gutenberg/
- https://generatepress.com/forums/topic/styling-for-gutenberg-alignfull-and-alignwide/
- I can't find any blog with correct information?

**Comment by webmandesign** [comment]
Hi, shameless plug here ;) This might be of interest to you: https://codepen.io/webmandesign/post/gutenberg-full-width-alignment-in-wordpress-themes

**Comment by webmandesign** [comment]
Also, the issue you describe is actually related to Windows OS only from what I know. The only way around it would be to set `overflow: hidden;` on your website container (as stated in ["**Known issues**" section](https://codepen.io/webmandesign/project/full/AVakKM/) in examples accompanying the above article).

**Comment by manake** [comment]
+1 is for noticing different value for `100vw` on Mac vs Windows.

Shouldn't this be filed to Chrome/Firefox/Edge developers as a bug? `100vw` should return the same value on all systems, shouldn't it?

**Comment by webmandesign** [comment]
@manake According to https://cloudfour.com/thinks/breaking-out-with-viewport-units-and-calc/ the bugs were already reported&hellip;

**Comment by smerriman** [comment]
> 
> 
> Also, the issue you describe is actually related to Windows OS only from what I know. The only way around it would be to set `overflow: hidden;` on your website container (as stated in ["**Known issues**" section](https://codepen.io/webmandesign/project/full/AVakKM/) in examples accompanying the above article).

But that doesn't fix the problem. Yes, it prevents the horizontal scrollbars, but the content still overflows. You won't see the left and right edges of the image.

It seems there is no solution at all to this.

**Comment by webmandesign** [comment]
@smerriman That's true. However, there is no other way around, unfortunately.

**Comment by MichaelRise** [comment]
@smerriman @webmandesign I test another 2 solutions.
1. Option 1 - We can add CSS custom properties (variables) to the `:root` with "body width" value and use it in css. Cause various problems. Some browsers don't support CSS custom properties (variables).
2. Option 2 - We can appending style nodes with javascript.

I must optimize my code but currently it works fine.
I created simple tutorial on github. If you can please check it. https://github.com/MichaelRise/Gutenberg-Fullwidth-Alignment

**Comment by MichaelRise** [comment]
@manake Option 3 - We can get scrollbar width and use it as a CSS custom properties (variables).
Example:
`width: calc( 100vw - var(--scrollbarwidth) );`

**Comment by chrisvanpatten** [comment]
I'm not really sure this is something we should cover explicitly in our documentation, because how you style these can vary from site to site. On my own website I'm using a weird "reverse grid" with wildcard selectors and such, however on another site our full-width option doesn't actually stretch the full width, so it's styled with a simple max-width.

And when you factor in themes with sidebars it gets even more complicated because some pages may treat full alignment differently from others.

Definitely recognise that the world needs more examples, to be clear… I'm just not sure it should be in official documentation.

Thoughts from the CSS and themey folks? Should we prescribe a recommended/official method, or let other sites document the various approaches?

cc @kjellr @jasmussen

**Comment by kjellr** [comment]
I agree — I'm not sure it's necessary to have a preferred/recommended method in the docs. 

It has been helpful to have [the sidebar example](https://codepen.io/joen/pen/zLWvrW) that's linked from the handbook currently, but I imagine that'll get less useful once more and more themes exist to learn from.

**Comment by MichaelRise** [comment]
I agree - websites, themes have a unique design and do not always have the same solutions and needs. However, it would be helpful to have examples for programmers that can help them save some time

**Comment by smerriman** [comment]
I think in this case it would be useful to include something given it's a core feature with no actual valid CSS implementation. I see the twentythirteen theme cuts off the sides of full width images and use a rather nasty hack of 96vw for full width non-images - if this WordPress' official recommendation, it's probably worth mentioning.

**Comment by manake** [comment]
Best: They should include `100rvw` (real viewport width) in the browsers. This is the only real solution here.

Copy and paste code in the documentation is needed because look what I did in the first post: I opened 10 links from Google, wasted time and didn't find any solution.

**Comment by nickfmc** [comment]
I recently decided to go about this a bit of a different way, it needs more testing with other blocks I've only really tested with images and columns but so far seams to work. I removed the wrapper width that was applied around my the_content area so everything by default is full width then I used the following CSS to add a max width to wp-block(s) that don't have the class of alignfull.

`[class^="wp-block-"]:not(.alignfull) {
  width: 100%;
  max-width: 1200px;
  margin: auto;
}`

**Comment by nickfmc** [comment]
After doing much of the same research as most people did here I decided instead of trying to make the wide classes break outside of my wrapper I would add the following to add a max width to blocks without the classes.  I have not tested this thoroughly enough yet but it seams to work on columns, images, block quotes.  So I just removed the page templates wrapper and assume it as 100%.  Here is a pen with the WP markup as closely emulated as I could https://codepen.io/nickfmc/pen/vvbWQa

`.editor-content > [class^="wp-block-"]:not(.alignfull) {
  width: 100%;
  max-width: 1200px;
  margin: auto;
}

.editor-content > [class^="wp-block-"]:not(.alignfull).alignwide {
  max-width: 1400px;
}`

**Comment by nextgenthemes** [comment]
@nickfmc This is exactly what I will be going for and I thought of this b4 even reading your comment. I think its way more intuitive then these complicated negative margins combined with calc and you need overflow ...

But I think I just go with 
```css
.entry-content > div:not(.alignfull),
.entry-content > p:not(.alignfull) {
```
or even just

```css
.entry-content > *:not(.alignfull)
```

to make it independent of Gutenberg and just apply to all elements that are not specified to be wide (with Gutenberg or just by manually adding that class in). Not sure how the `*` star performance issues are at these days but I think CSS is read by the browser from right to left so I guess its fine.

**Comment by onetrev** [comment]
Agree @nextgenthemes ... in fact I'd say you _have to_ go with the star selector you suggested because it's not just `p` tags but also things like headings, ie, `h1` that are not wrapped in a `.wp-block-`. So the wildcard `*` selector is definitely the way to go.

`.entry-content > *:not(.alignfull)` 

I have yet to really encounter any drawbacks. It works perfectly, and no scrollbars for anyone!

**Comment by dnnsjsk** [comment]
Bravo, thanks guys! This solution is amazing!

**Comment by LABCAT** [comment]
I think there should definitely be a recommended way to implement these styles and it should be used by all default WordPress themes. 

Plugin creators need to implement default styles for their blocks and currently it seems impossible to ensure a block with wide or full alignment will work well on multiple themes. 

A combination of @nickfmc and @onetrev seems to be the way to go.

How do we go about getting some action on this?  Submit a ticket on core trac suggesting the change to all default themes?

**Comment by WraithKenny** [comment]
I tried to come up with a default, one-size-fits-all solution, and this is what I came up with (after checking out this article https://www.filamentgroup.com/lab/scrollbars/)

This is Progressive Enhancement, using `100vw` minus scrollbar, implemented straightforwardly with negative margins. 

It sets a default of `17px` for scrollbar width, which is the width of almost all browsers, and uses CSS Variables  to adjust for modern browsers, so if you have "unobtrusive" scrollbars (Mac auto-hiding for example), it sets the `--scrollbar-width` to `0`.

It doesn't have any tricky rules involving `overflow` or `:not()` that end up causing headaches or maintenance issues. Additionally, it's very small, has low specificity so it's easy to override. 

(Bonus example of `.alignwide` to go along with it.)

```PHP
<?php
add_action( 'after_setup_theme', function() {
	add_theme_support( 'align-wide' );
});

add_action( 'wp_body_open', function() {
	?>
	<style>
	:root {
		--scrollbar-width: 17px;
		--white-space: (100% - (100vw - var(--scrollbar-width)));
	}

	.alignwide {
		margin-left: calc((-100vw + 17px + 100%) / 4);
		margin-right: calc((-100vw + 17px + 100%) / 4);
		width: auto;
		max-width: none;
	}

	.alignfull {
		margin-left: calc((-100vw + 17px + 100%) / 2);
		margin-right: calc((-100vw + 17px + 100%) / 2);
		width: auto;
		max-width: none;
	}

	@supports (color: var(--)) {

		.alignwide {
			margin-left: calc(var(--white-space) / 4);
			margin-right: calc(var(--white-space) / 4);
		}

		.alignfull {
			margin-left: calc(var(--white-space) / 2);
			margin-right: calc(var(--white-space) / 2);
		}
	}
	</style>
	<script>
	(function(){
		var parent = document.createElement('div');
		parent.setAttribute('style', 'width:30px;height:30px;overscroll-behavior:contain;overflow-y:auto;-webkit-overflow-scrolling:touch;-ms-overflow-style:-ms-autohiding-scrollbar;position:absolute');
		var child = document.createElement('div');
		child.setAttribute('style', 'width:100%;height:40px');
		parent.appendChild(child);
		document.body.appendChild(parent);
		var scrollbarWidth = 30 - parent.firstChild.clientWidth;
		document.documentElement.style.setProperty('--scrollbar-width', scrollbarWidth + 'px');
		document.body.removeChild(parent);
	}());
	</script>
	<?php
} );
```

**Comment by LABCAT** [comment]
Scrollbars don't always show and you shouldn't need JavaScript for styling purposes.

**Comment by WraithKenny** [comment]
The javascript isn't needed. It's a progressive enhancement to remove the 8.5px that the css-only solution leaves on each side to be browser compatible.

I agree, the other solutions are nice, especially with sidebar layouts. I'm just allergic to 'direct descender into wildcard' css rules.

**Comment by onetrev** [comment]
Interesting solution @WraithKenny, thanks for posting! Myself I used the solutions posted by @nickfmc and @nextgenthemes but it never felt like the ideal fix. However, I just recently went back to using using `vw` similar to the setup of Twenty Twenty theme and it's working well and without scrollbars for me (Windows 10 testing only). 

```
.entry-content .fullwidth {
  max-width: 100vw;
  position: relative;
  width: 100%; 
}
```

**Comment by WraithKenny** [comment]
@onetrev Are you using Mac with the "Show Scrollbars" setting on hide? If so, your scrollbars are 0 width, but users with different settings will definitely cause horizontal overflow scrollbars, depending on the browser. (The standard has settled on that as intensional behavior that they won't fix.)

**Comment by onetrev** [comment]
No Mac here. See above, Windows 10 only. No horizontal scrollbar. You can as per Twenty Twenty use `overflow-x: hidden` to make sure. Just try the new WP default theme -- Twenty Twenty -- to test it out.

**Comment by WraithKenny** [comment]
@LABCAT The advantage of my solution over the other, is that you can simply drop it in and it'd work with **_any_** theme that has a single column layout and it'll work, making it ideal for a generic general purpose solution. Again, it's a simple class selector, with few basic statements to overwrite if you need to.

It even works if you are using Twitter Bootstrap and have your content nested in a `.container` or `.container-fluid` wrapper--no tweaking needed!

Looking at the statement: 
```CSS
.entry-content > :not(.alignfull) {
    width: 100%;
    max-width: 1200px;
    margin-left: auto;
    margin-right: auto;
    padding-left: 20px;
    padding-right: 20px;
}
```
I have lots of concerns.

These are _**not**_ fast selectors. https://css-tricks.com/efficiently-rendering-css/ Performance is going to take a hit in the real world. The rule starts right to left, with a universal selector which is the least efficient selector.

You also end up tightly coupling your markup, requiring a specific immediate wrapper div around `the_content()` but more troubling is you are just _begging for edge cases_, considering what plugins put into the content field. Every single possible direct descendent of `.entry-content` will need to avoid having a conflict on margin, padding, width and max-width, and whatever rules you might set on an independent container element.

That's not to dismiss the solution, because it's definitely interesting and clever, and might be useful for certain situations, but it's not as clean or efficient as you'd think. 

Consider TwentyTwenty, which adopted that technique: https://github.com/WordPress/twentytwenty/blob/master/style.css#L3508

`style.css` has **_134_** references to `.alignfull` and lots of bug reports around it. It also complicated tons of other rules . And, like I pointed out, these aren't efficient fast rendering selectors.

The hard lesson learned on TwentyTwenty is why I tried to come up with a better solution. My offered solution is nice and clean, small and performant, and more broadly applicable, and I think a good fit for a default recommendation, and maybe a replacement for TwentyTwenty.

**Comment by WraithKenny** [comment]
@onetrev Yes, lol, TwentyTwenty is what convinced me to find a better solution.

**Comment by strarsis** [comment]
Related: https://github.com/WordPress/gutenberg/issues/19331

**Comment by nextgenthemes** [comment]
@WraithKenny 

Quoting from your liked article: 

> That Mozilla article I linked to at the top? Literally 10 years old. Fact: computers were way slower 10 years ago. I have a feeling this stuff was more important back then. Ten years ago I was about to turn 21 and I don't think I even knew what CSS was, so I'm not going to get all old school on you... but I have a feeling we don't talk about this rendering efficiency stuff very much is because it's not that big of a problem anymore.
> 
> This is how I'm feeling about it: the best practices we covered above make sense no matter what. You might as well follow them, because they don't limit your abilities with CSS anyway. But you don't have to be all dogmatic about it. If you happen to be in the position where you need to eek out every last drop of performance out of a site and you have never considered this stuff before, it may be worth revisiting your stylesheets to see where you can do better. If you aren't seeing much rendering slowness in your site, then don't worry about it, just be aware for the future.

I think it's totally ridiculous to be concerned about a few `:not()` selectors. Computers and phones are getting faster and faster and so are browser engines. I like to see some real world examples of CSS performance that make a difference that is humanly noticeable. I gonna make a the claim that you need to got pretty crazy with A LOT of those "inefficient" selectors to see some real slowdowns.

I have not looked deeply at what TwentyTwenty is doing but that I and others are suggesting are a few basic CSS lines to make this happen. Not sure why that has to be that complicated.

**Comment by WraithKenny** [comment]
You know what? You're right. It's totally ridiculous of me. I've deleted all my ridiculous comments.

**Comment by youknowriad** [comment]
Sorry for missing this issue initially. I agree that alignments are hard to support these days. We're rethinking these to simplify things for theme authors in #20650

**Comment by esamakelariima** [comment]
I use this one 

.alignfull {
max-width:100vw!important;
width:100vw!important;
margin: 0 calc(50% - 50vw)!important;
}
