### ISSUE TITLE
wp.components.PanelColor has no indication for custom color

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#8292]
When a custom color is selected there is no indication what that color is:
<img src="https://i.imgur.com/ePyA0tv.png">

There should be better indications for all possible states (no color set, some pre-defined color set and custom color set).

Update: The following are already solved by Gutenberg 3.4.0:

It also has misaligned focus outline:
https://i.imgur.com/JgEkIKI.png

The color picker itself:
https://i.imgur.com/0ienhSu.png

**Comment by aduth** [comment]
The `PanelColor` component was removed in `@wordpress/components@6.0.0`:

https://github.com/WordPress/gutenberg/blob/master/packages/components/CHANGELOG.md#600-2018-11-12

The substitute [`ColorPalette` component](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/color-palette) will display a color indicator for custom colors.

![image](https://user-images.githubusercontent.com/1779930/58721658-735ea080-83a3-11e9-9c18-60ca9af20dc6.png)

Other bugs should ideally be reported to their own issues, as they may not receive equivalent prioritization as an enhancement request. That said, they are both resolved since (recalling history and in new testing).
