### ISSUE TITLE
Provide better handling when a post type doesn't support `editor`

### ISSUE THREAD

**Issue by wpscholar** [WordPress/gutenberg#8321]
At the moment, when a post type doesn't support the `editor` feature, we fall back to the "classic" experience with TinyMCE disabled. However, we should be giving the user the Gutenberg experience with the content portion of the editor disabled. A user should be able to edit the title, set the featured image, etc. from within Gutenberg but with the content portion of the editor not being initialized.

See https://github.com/WordPress/gutenberg/issues/3659#issuecomment-408953106

**Comment by designsimply** [comment]
I tested using the following steps:

1. Go to Settings > Reading > "Your homepage displays."
1. Select the option for "A static page."
1. Select a Homepage and a Posts page and save changes.
1. Open the posts page in the editor.

<strong>Result:</strong> it's possible to edit the content of a page set as a "Posts page" even though that content will not be displayed if you visit the post on the front end because it is set to display a list of posts (which takes over the content).

![screen shot 2018-07-31 at tue jul 31 11 35 09 am](https://user-images.githubusercontent.com/1119271/43476932-16573c16-94b7-11e8-9dbc-a8ca564b9ae7.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14092&action=edit running WordPress 4.9.7 and Gutenberg 3.4.0 using Firefox 61.0.1 on macOS 10.13.6.</sup>

I believe what you are asking for is a view similar to the one mentioned in https://github.com/WordPress/gutenberg/issues/3659#issuecomment-359052626 (note: I tried to figure out steps to see that view by activating the Twenty Seventeen theme, setting a static front page, then opening that page for editing but it didn't show the same view so I may be missing a step—I've copied the screenshot from the previous issue for reference.)

![35165882-c5a9ee66-fd04-11e7-9007-45066faecd46](https://user-images.githubusercontent.com/1119271/43476920-08785ae4-94b7-11e8-9add-20e436975106.png)
<sup>Source: https://github.com/WordPress/gutenberg/issues/3659#issuecomment-359052626</sup>

**Comment by wpscholar** [comment]
@designsimply This issue isn't about the editing of a blog page specifically, but what happens generically when a post type doesn't support the `editor` feature. The issue you've referenced has been resolved.

**Comment by mtias** [comment]
This was an explicit choice in the name of backwards compatibility and general feedback from developers. Considering that the primary motivation of Gutenberg is for content editing, if a CPT doesn't support content we think falling back to the administrative interface is better for now.

We might revisit this as Gutenberg becomes more ubiquitous and the expected interface in general for WordPress. We could also explore allowing CPT that disable content to still opt-in into the Gutenberg UI if that makes sense.

Thanks for sharing your point of view!

cc @pento for keeping it on the radar.
