### ISSUE TITLE
Block file, Download button text field -  the translation text is fixed

### ISSUE THREAD

**Issue by pix365** [WordPress/gutenberg#8351]
WordPress 4.9.8-RC3-43547 running Twenty Seventeen theme.
Gutenberg plugin Active
No other plugin active.
3 languages  en-US  fr-Fr  es-ES.

Core lang US english
Created post in english added file block(1st), added pdf, button text is "Download" 
changed core lang to FR added new file block (2nd) added same pdf file, button text was "Télécharger"
changed core lang to ES added new file block (3rd)  added same pdf file, button text was "Descargar"
when viewing the Post in any of the three languages 
The Button text did not change as it kept the text as per the Core language at time block was added to this post.  

Maybe this behavior can be considered as feature and not a bug? 
As a "feature" it would be extremely useful when running a multilingual site, but only if you can change the language within the Gutenberg editor (and or individual Block's) before you create a Page or Post.  It's not really practical on a live site to switch core Lang to create new content, however you can easily edit the HTML with Gutenberg,
![wordpress-3-langs](https://user-images.githubusercontent.com/8709475/43514748-22708c6c-9581-11e8-9201-dcc158edda34.png)
![wordpress-3-lang-html](https://user-images.githubusercontent.com/8709475/43514999-b9734546-9581-11e8-8ca9-8c8a32a29010.png)

.

**Comment by swissspidy** [comment]
> The Button text did not change as it kept the text as per the Core language at time block was added to this post.

That is expected behavior. The file block is not dynamic, which means the text is saved as-is to the database.

To make content creation easier on a multilingual site there would need to be some kind of filter to allow overriding the default download label.

**Comment by OsakaWebbie** [comment]
This is horrible behavior. Sure, those of us comfortable with HTML can click "Edit in HTML" and change the text, but:

- It's labor-intensive and prone to mistakes.
- If we want to get back to editing visually, we have to publish and then refresh the editor. (Many types of blocks lose their controls once you switch to HTML edit mode - another frustration with Gutenberg!)
- We really can't ask this of non-programmer content creators.

The file block is part of core, so why can't it be a string that is translated by the language packs? If that's too hard for some reason, include a field in the block settings in the right sidebar (right after the switch to turn on/off the button) to customize the button text. (Obviously you should only do one or the other, not both - if it's a translated string AND customizable in the sidebar, users might be confused when a slight change breaks translation.)

**Comment by swissspidy** [comment]
@OsakaWebbie I am not sure how you got to this conclusion, but:

* You don't have to use "Edit in HTML" are anything to change the text. You can just type and replace the default text with whatever you want.
* The string **is** translated by language packs.

**Comment by OsakaWebbie** [comment]
Oh, sorry. Somehow the highly stylized button didn't _look_ editable, so it didn't even occur to me to try. Yes, I see now that I can edit its text.

But as for the language pack, my site is in English plus the Japanese language pack (confirmed both by General Settings->Site Language->Installed and by seeing the files in `wp-content/languages`), but that button is not localized. That's not surprising, since (as you said two years ago) it's just straight text in the post content saved to the database. How could a language pack possibly translate that (without switching core language when creating the post, like @pix365 said)?

**Comment by swissspidy** [comment]
> How could a language pack possibly translate that (without switching core language when creating the post)

That's what you currently have to do.

In the _editor_, when _creating a new post_, the default download button text will be in whatever language you are using in WordPress admin.

Then, when you save the post, all that text is saved as-is and will be displayed the same on the frontend. Which kinda makes sense because then the button text is always in the same language as the rest of the post.

It's the same behavior like when you create an image block with a caption, or insert a button block with some text. That's because these blocks are not _dynamic_, and not rendered in PHP on the frontend.

To change this, you could register your own render callback for the block (to override the markup on the frontend), or put a proposal here to make the block dynamic. But in the two years since opening this issue there was apparently little interest to do so :-)

**Comment by OsakaWebbie** [comment]
Apparently I wasn't clear in my first comment - I was trying to suggest that it be dynamic in the _backend_ at the time the post is displayed, i.e. using `gettext()` to create the text based on the locale (like the text in the admin bar above the site when logged in). That's what I meant by using the language packs. But at the time I said that, I didn't realize the editor would allow the text to be rewritten in visual editing mode - essentially, my second idea is already a reality (the button text can be edited without looking at raw HTML), so that's good enough, and I know that a dynamic implementation would eliminate that simple editing ability.

And yeah, two years of silence says that no one considers this an issue. Thanks for the conversation, and have a good day.
