### ISSUE TITLE
Not possible to use tab for list indentations

### ISSUE THREAD

**Issue by Clorith** [WordPress/gutenberg#8356]
**Describe the bug**
When writing lists, it's often useful to have sub-lists as well in various places. This is possible in Gutenberg if you click on the indent buttons, but it's common practice to use tab and shift-tab to move indentations in/out.

Gutenberg just moves the cursor focus to the next block when tab is used.

It's expected that tab moves indentations in lists, and is the behavior of all other word processors.

**To Reproduce**
1. Create your ontent
2. Add a list block with a list item
3. Create a new list item and hit tab to move it in one step as a sub-list

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 68
 - Gutenberg 3.4.0

**Comment by SuperGeniusZeb** [comment]
Notably, there is a block that uses <kbd>Tab</kbd> for something other than navigation: the Custom HTML block. Pressing <kbd>Tab</kbd> inserts, well, a tab character. Pressing <kbd>Esc</kbd> and then <kbd>Tab</kbd> lets you exit the block as usual. That said, I doubt having to press <kbd>Esc</kbd> and then <kbd>Tab</kbd> in the List block to navigate to the next block is desirable behavior. I think some different keyboard shortcut should be implemented for indenting list items.

**Comment by afercia** [comment]
@youknowriad yes a while ago I've opened #7051 for the List block, as follow up to #4181. I'd invite everyone to continue the discussion there.

Currently, in the List block indentation is made via meta+[ for list outdent and meta+] for list indent.

> It's expected that tab moves indentations in lists, and is the behavior of all other word processors

@Clorith right: in word processors. I'd agree that would be the expected behavior in a desktop application or a full page editor, where navigation is provided by other means. However, Gutenberg is not a word processor, it's a web application and the native, expected, behavior of the Tab key on the Web is to navigate through focusable elements. In Google Docs, for example, the recommended shortcuts are meta+[ and meta+] (though Tab works too, but again Google Docs is a full page editor).

@SuperGeniusZeb right, that's a trade-off, an exception I'm not particularly happy with, but it was necessary to make the code editor (CodeMirror) in the HTML block work as an editor. It's the same trade-off solution core already uses in other places, for example the Plugin / Theme editors and the CSS editor in the Customizer. Without that, it would be impossible to tab away from the HTML block (there would be a so called "keyboard trap").

#7051 highlights the inconsistency with the Classic Block, I guess the Code block should be mentioned too.

**Comment by bph** [comment]
Hmmm, it's really hard to move away from current behavior when migrating to Gutenberg, I think there should be as little disruption as possible. And thank you @Clorith for filing an issue. It was on my list of little quirks for a while now. 

Not only in word processors. The WordPress editor really does support the tabbing in and tabbing out (shift+tab). In the video you don't see that I use the tab key, though... but I post it here anyway. 
http://recordit.co/zIgXrBkYTc

**Comment by afercia** [comment]
@bph hello 👋 yep, lists in the Classic Editor are a bit different though, mentioned in #7051.
