### ISSUE TITLE
Cannot Paste Into HTML Block on Mobile Device 

### ISSUE THREAD

**Issue by zgordon** [WordPress/gutenberg#8370]
## Issue Overview
When I am on a mobile device and click into an HTML block to paste in some embed code it seems to register as if I am trying to select the box and I never get the Paste menu option from my device. 

. 

## Steps to Reproduce (for bugs)

To duplicate the issue 

1. use an android device. 
2. Add a new post
3. Add an HTML block
4. Copy embed code from somewhere 
5. Try to paste that embed code into the HTML block 

For me this didn't work but I may be missing something

On Chrome on an android phone. 

## Expected Behavior

When you hold down to paste it should show the device paste menu options. 

## Current Behavior

It does not show the paste options when you hold down to paste. It seems to select the block. 

## Possible Solution

Not sure how this would be fixed, but it doesn't happen 

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by jorgefilipecosta** [comment]
Hi @zgordon, thank you for reporting this issue. I tried to reproduce the problem on the last version of Gutenberg, and I was not able to do it:
![Jun-06-2019 11-47-12](https://user-images.githubusercontent.com/11271197/59027455-f7f06980-8850-11e9-9821-303102407aa1.gif)

If the problem is still happening in your tests, feel free to reopen the issue and we will debug further.
