### ISSUE TITLE
Pasting at end of bold text block (but still within it) causes the pasted text to jump to the start of the block

### ISSUE THREAD

**Issue by josephrocca** [WordPress/gutenberg#8387]
1. Put some text in the editor
2. Make a bold section within that text
3. Place your cursor at the end of the bold block, but still *within* it and try to paste a bit of text there. 

Here's a video of the problem:
https://i.imgur.com/0ktY7LD.mp4

 - OS: Ubuntu 16.04
 - Browser: Chrome 67
 - Gutenberg: 3.4.0

**Comment by josephrocca** [comment]
And here's another related bug:

1. Put some text in the editor
2. Make a bold section within that text
3. Highlight part of that bold block and paste some text over it.
4. Now try undo it (ctrl+z).

Here's what happens:
https://i.imgur.com/RpgQSPr.mp4

**Comment by josephrocca** [comment]
Another one: [Here](https://i.imgur.com/MC13JXa.mp4) I'm trying to remove the first bullet point from the list. I first try backspacing the item itself, but that "explodes" the dot points into individual paragraphs. I then try to backspace at the start of the next item, but that does the same thing. Seems as though it's not possible unless I restart the list.

Thanks to all the contributors on this! Dispite a bunch of bugs, I can see that this is going to be a huge upgrade over the original editor!

**Comment by designsimply** [comment]
Thank you for your feedback! I tested with WordPress 4.9.8 and Gutenberg 3.5.0 using Firefox 61.0.2 and Chrome 67.0.3396.99 on macOS 10.13.6 and was able to reproduce the first issue where pasting into the end of the inline boundary for bold text results in text being added before the boundary instead of at the end of that text as expected, but I could only see that happen in Firefox ([26s](https://cloudup.com/ceRZ_siwJOq)) and not Chrome ([33s](https://cloudup.com/ciotFiQSPxx)).

Note: we are tracking the issue where backspacing over the first bullet in the list results in the rest of the list turning into paragraph blocks in #8803.

**Comment by krisgale** [comment]
it's oddly comforting to know others have noticed this strange behaviour.
