### ISSUE TITLE
Missing HTML id 'page_template' with Gutenberg

### ISSUE THREAD

**Issue by rinkuyadav999** [WordPress/gutenberg#8414]
**Describe the bug**

Missing HTML id 'page_template' on page edit screen for page template select option. Gutenberg
 adds different id and old editor adds 'page_template'. it is going to make problem for many themes and plugins, which do something using JS base on page_template id.

There should be same id so feature can work with both editor. or at least add a same class.

**To Reproduce**
1. Page Edit Screen.
2. Inspect and check HTML id of page template select option, it is page_template.
3. now check same id with gutenberg, it is different.

**Expected behavior**

Both editors should add same id so $('#page_template')..change can work with both. or add same class name.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by youknowriad** [comment]
I think relying on DOM ids/classes for plugins is never a good idea, it's better if you rely on proper extensibility APIs. Gutenberg has a lot of them https://wordpress.org/gutenberg/handbook/

There's nothing we can do here because it's not possible to keep the exact same DOM tree structure when you update the editor.
