### ISSUE TITLE
Page - Full Width

### ISSUE THREAD

**Issue by cTraderGURU** [WordPress/gutenberg#8416]
Only boxed layout, please add row and column options.

**Comment by tofumatt** [comment]
Could you please add screenshots or more information to your issue? We're happy to help and listen to issue feedback, but it's not clear from your issue what you would like to change. 😄

**Comment by smartsal** [comment]
@tofumatt indeed it isn't that hard. The question basically is "how to add full width rows/content" - I have the same question too, as I couldn't see any option to make content full width.

**Comment by designsimply** [comment]
Because the issue title here is "Page - Full Width," you may be looking for the Page Attributes option which is in Settings (gear icon) > Document and looks like this:

![screen shot 2018-08-03 at fri aug 3 12 07 21 pm](https://user-images.githubusercontent.com/1119271/43658385-fb712518-9715-11e8-8b9a-8e0683646d9c.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=13785&action=edit running WordPress 4.9.8 and Gutenberg 3.4.0 using Firefox 61.0.1 on macOS 10.13.6.</sup>

Some types of content, such as the Cover Block, can also be made full-width using a button in that block's toolbar. Note that this may depend on theme support ([ref](https://wordpress.org/gutenberg/handbook/extensibility/theme-support/#wide-alignment)).

Here is an example of a full width option for the Cover Image block while the Atomic Blocks theme is active:

![screen shot 2018-08-03 at fri aug 3 11 56 42 am](https://user-images.githubusercontent.com/1119271/43657956-883931d6-9714-11e8-9282-b04575e1a71e.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14102&action=edit running WordPress 4.9.7 and Gutenberg 3.4.0 using Firefox 61.0.1 on macOS 10.13.6.</sup>

**Comment by youknowriad** [comment]
Some blocks support wide alignments, others not. I suppose we will support this in the upcoming Section block.
