### ISSUE TITLE
No option to edit the permalink

### ISSUE THREAD

**Issue by Davian007** [WordPress/gutenberg#8417]
I want to be able to edit the link of my posts, this is not possible here. There is a button that sends you to the permalink page, but this is totally useless.

**Comment by pento** [comment]
Thank you for the report, @Davian007!

The button sends you to the Permalinks settings page, because you need to choose a permalink setting other than "Plain" (or if you have a custom permalink setting, it needs to contain `%postname%` or `%pagename%`), before Gutenberg is able to edit the permalink.

If you do have a custom permalink setting, could you please reply with it?

**Comment by Davian007** [comment]
I already have an adapted permalink setting
/archive/%year%/%monthnum%/%day%/%postname%.html/

What I need - en this is why I installed the classic version again - is to be able te adapt my permalink if necessary. For instance.

I write a review with the following title: **The Day After Tomorrow (2004) **½ Blu-ray review**

Since I want to use clean urls and do not want 
my post to be written as: 

https://defilmblog.be/archive/2018/07/29/the-day-after-tomorrow-2004-½-blu-ray-review.html/
but as:
https://defilmblog.be/archive/2018/07/29/the-day-after-tomorrow-2004-blu-ray-review.html/

Now in the classic version, you can simple edit this with an 'edit' button

**Comment by swissspidy** [comment]
> Now in the classic version, you can simple edit this with an 'edit' button

.... and in Gutenberg you can click on the post title and the permalink appears, together with a button to edit the permalink.

**Comment by pento** [comment]
@Davian007: Thank you for the extra information, I'll do some more investigating and see what I can find. The option to edit the permalink should appear with that permalink structure (it does on my test site), so there's evidently something more complex going on.

Do you have any plugins installed that you use to modify the permalink, or manage it in some way?

@swissspidy: We already covered that earlier in the issue. 😉

**Comment by swissspidy** [comment]
Wasn't really clear, but well ;)

**Comment by Davian007** [comment]
Problem solved, I got rid of some plugins affecting the editor. Now I can edit the url.

**Comment by pento** [comment]
Great to hear you solved it, @Davian007!

Just for our information, do you know which plugin was causing the problem? If it was a custom plugin you have, do you have a sample of the code we can use to reproduce this bug?

**Comment by Davian007** [comment]
I believe it was the WP Config File Editor , but I removed 2 others. Couldn't tell what effected what. 
In any case, I love to write html (text editor and not the visual editor) when I write my posts and the Gutenberg  update - correct me if I am wrong - is mainly for making it easier for people with no html background. Less buttons, easier content handling, ...

**Comment by SuperGeniusZeb** [comment]
Just so you are aware, there is a Custom HTML block that has syntax highlighting and is ideal for situations where you want to use a bunch of custom HTML that is not considered valid in other blocks.

![image](https://user-images.githubusercontent.com/19592990/43658621-117366c4-971f-11e8-8698-45d7615eb9f0.png)

Additionally, you can often manually edit the HTML of a block using the <kbd><samp>Edit as HTML</samp></kbd> option. You can use this to do stuff like adding in `<span>`s that set the color and other styles of a line of text in a Paragraph.

![image](https://user-images.githubusercontent.com/19592990/43658471-9ece5750-971e-11e8-950f-d0f46b09c3b2.png)

Check it out! You can view the HTML inside a block without viewing the HTML of the entire post/page!

![image](https://user-images.githubusercontent.com/19592990/43658567-e454c994-971e-11e8-926e-b5144157dedb.png)

Note that if you modify a block by adding attributes or content that is does not think are valid, or else simply break the HTML tags or something, the block will break and alert you that it has become invalid, prompting you to either remove the invalid content and try and convert it back into blocks (which does not always come out quite right) or convert it into a Custom HTML block. You can also just use the <kbd><samp>Undo</samp></kbd> button in the top bar of the editor to undo your breaking changes.

![image](https://user-images.githubusercontent.com/19592990/43658833-9195782e-971f-11e8-875d-861110df6111.png)

(I think that warning text could be improved... I do not think that using the <kbd><samp>Edit as HTML</samp></kbd> option counts as "modified externally".)

There are a couple issues currently where things that should be considered valid changes cause a block to become invalid. Here are a couple of open tickets regarding those issues:
- #6102
- #6878
- #7604
- #8450

You could also potentially install a plugin that adds more formatting buttons to the block toolbars to make coloring spans of inline text (and stuff like that) easier, though I am not sure if anyone has actually created a plugin that does that yet. Gutenberg is designed to be extensible and modular, like WordPress in general. If a feature appears to be missing, it may be because it was considered plugin territory, or it is still in the works and coming in a future update.

>Gutenberg update - correct me if I am wrong - is mainly for making it easier for people with no html background. Less buttons, easier content handling, ...

Sort of, but it goes further than that. The block system is designed to allow for more WYSIWYG content editing (its more WYSIWYG, What You See Is What You Get, if your theme styles the editor to look like the front-end), and dividing content up into... well, blocks, which allow controls to be more contextual (no need to show table controls when you are not editing a table).

Additionally, the block API allows for potential standardization of various kinds of ways of adding content in WordPress. Widgets could be replaced by blocks; in the future, sidebars will become areas that you can edit with Gutenberg. Headers? Footers? Both could become areas you edit with Gutenberg in the future... all being composed of blocks. Most shortcodes would also be replaced by blocks as well.

You know how current page builders all have separate, incompatible sets of modules/widgets that can only be used in their own builder? Well, what if they all used the same base APIs, and the modules worked on any WordPress website? That is what the Gutenberg block API could allow for in the future. Switching from one page builder to another would become way easier. Many page builders would simply become alternative visual interfaces that use the Gutenberg code behind-the-scenes. Page builders could be split up into smaller, more modular plugins... which is probably how they should have been in the first place.

Gutenberg is starting out with a focus on being a post editor for WordPress 5.0. But it already has the foundational APIs to start being a page builder as well in the future. Eventually, it will not just be a page builder, but a template builder, and then an entire website builder. It is not necessarily designed to replace existing page builder plugins. Instead, it is designed to make them more flexible and compatible with each other. Gutenberg will provide a default visual interface, but the back-end code can be used by other plugins with their own interfaces.

Gutenberg has the potential to even go beyond WordPress. The Gutenberg editor has been designed so that in the future, you could use a standalone instance of Gutenberg outside of WordPress entirely. It is possible that in the future, other content management systems could implement the basic Gutenberg block APIs, which could become a de-facto standard for content with higher-level semantics than HTML. Here is an experimental standalone instance of the Gutenberg editor. Note that it is based on a much older version of Gutenberg from March or earlier, so it is not as polished as the current version:

https://github.com/youknowriad/standalone-gutenberg
https://gutenberg-standalone.surge.sh/

I recommend checking out the Gutenberg handbook for more info:
https://wordpress.org/gutenberg/handbook/
