### ISSUE TITLE
Needs some improvements and also found a bug

### ISSUE THREAD

**Issue by etwordpress01** [WordPress/gutenberg#8424]
Hi,

I just install plugins and i am surprised that what a bad thing added in WordPress.  I know this is beta version and not ready for WordPress.

First bug i found that, I just install it and when i edit my own post then white screen appear after refresh page then content appear. 

![screenshot_9](https://user-images.githubusercontent.com/31212934/43632150-bf13b69a-971e-11e8-9a3b-7eae28b79358.png)

Next thing is this is not user friendly. To switch from Visual Editor to Code Editor i have to find options.
I am a developer but think if end user who don't know about WordPress? then he to spend some time to find this kind of options.

Post format in drop-down is not showing as well. Only one post format is showing.

![screenshot_8](https://user-images.githubusercontent.com/31212934/43632165-c83e154e-971e-11e8-926e-29d51bef3823.png)

Overall design is not user friendly. 

Most amazing thing is gallery and image options. I like it

Thanks

**Comment by youknowriad** [comment]
Hi and thanks for your feedback,

 - Regarding the white page issue: do you have more info on that? any error in the console?

> Not user-frindly?

I'm no designer but I think the reason to put the editor mode selector there is because one of the reasons of Gutenberg is to allow users to create content without the need to switch to the code editor. The code editor is important for developpers and people that understand HTML and those can find it but not important for everyone.

Also, note that there's a "code mode" per block, so you can tweak each block's HTML separately without going to the full code editor page, you can also use the "HTML" block if the content you want to add has no corresponding block. That way, you can directly change in the visual editor without having to look for it in the code editor.

I hope this helps

**Comment by etwordpress01** [comment]
Hell @youknowriad 

I installed it on another local site and it seems that visual editor takes time to load while page is fully loaded.

Sometime it takes 2 seconds and some time more than 6 second to load. But now it is working fine. 

Code block feature is awesome. My main concern was sidebar of panel

![screenshot_1](https://user-images.githubusercontent.com/31212934/43643712-ab98e6a4-9745-11e8-9418-725862c37cb8.png)

In classic editor sidebar was more user friendly than gutenberg. There needs some improvements. 

For example when i write a tag and hit enter then first it display then hide and then again appear. On tab close and open all settings comes via ajax i think and it takes 2 to 3 second to display.

I will check your plugins and come back with video for improvements and bugs( if found ).

Thanks for quick response

**Comment by youknowriad** [comment]
> Sometime it takes 2 seconds and some time more than 6 second to load. But now it is working fine.

What takes such a time to load, the Entire page or just the "content/gutenberg" area? In general we try to preload all the data needed to load Gutenberg as soon as the page loads but we may be missing some API calls.

> In classic editor sidebar was more user friendly than gutenberg. There needs some improvements.

It definitely needs improvements and we're working hard to improve it. But can I say that "user friendly" is very subjective, we need to find a balance. 

I also suggested to create issues per item and not just a big issue with several items, this makes it easier for us to address each point without missing the others. Also, check if an issue doesn't exist before creating a new one. Thanks for your feedback.
