### ISSUE TITLE
Knight Lab TimelineJS button above editor disappeared 

### ISSUE THREAD

**Issue by tuvelijn** [WordPress/gutenberg#8436]
The plugin Knight Lab TimelineJS, A simple shortcode to display TimelineJS, disappeared in the gutenberg version. 
I think there is a problem with customizing the new editor with extra elements.

**Comment by youknowriad** [comment]
Hi there!

Gutenberg doesn't support "media buttons" used by this kind of plugins to add content to the editor. That's because one of the goals of Gutenberg is to unify the way we add content using the "block inserter". 

I'd suggest you reach out to the plugin authors to check their plans for Gutenberg support and if they plan to build a timelineJS block. 

These differences between the classic editor and Gutenberg will be documented to ease migration 

Related https://github.com/WordPress/gutenberg/issues/4186
