### ISSUE TITLE
Where is 'add exercise' button for datacamp light?

### ISSUE THREAD

**Issue by engmrk** [WordPress/gutenberg#8452]
I have installed datacamp light plugin which can add exercise directly into your code. The button was displayed right next to add media button. In Gutenberg, I can't find my add exercise button.

**Comment by youknowriad** [comment]
Hi there!

Gutenberg doesn't support "media buttons" used by this kind of plugins to add content to the editor. That's because one of the goals of Gutenberg is to unify the way we add content using the "block inserter".

I'd suggest you reach out to the plugin authors to check their plans for Gutenberg support and if they plan to build an exercise block.

These differences between the classic editor and Gutenberg will be documented to ease migration

Related #4186

**Comment by engmrk** [comment]
Thanks for quick response.

**Comment by pcimule** [comment]
SOLVED: dataCamp plugin not working with latest Wordpress Gutenberg editor.

Enjoy my own solution, here:

https://skylinkce.com/2020/07/11/solved-datacamp-plugin-not-working-with-latest-wordpress-gutenberg-editor/
