### ISSUE TITLE
I have installed WordPress 4.9.8, Gutenberg 3.4.0 und Gallery Manager 1.3.28. If Gutenberg is activ i cannot see my galleries. When i deactivat gutenberg i can see my galleries. The bug is only in the edit mode. Is there any idea to fix this bug? 

### ISSUE THREAD

**Issue by Walter-Huber** [WordPress/gutenberg#8453]
I have installed WordPress 4.9.8, Gutenberg 3.4.0 und Gallery Manager 1.3.28. If Gutenberg is activ i cannot see my galleries. When i deactivat gutenberg i can see my galleries. The bug is only in the edit mode. Is there any idea to fix this bug?

**Comment by youknowriad** [comment]
Hi there and thanks for the report

The issue is more likely related to the fact that Gutenberg doesn't mangle the content, so it shows up properly on the frontend but don't offer the same "filters/actions" used in the previous editor which means the tweaks the plugin made to the old editor won't work here. 

I think you should probably try to reach out to the plugin author to see if they have plans to provide Gutenberg compatibility. One of the goals of Gutenberg is to provide a unique way to insert content using blocks, so most of plugins adding galleries, shortcodes... should be adapted to create blocks instead for a better experience.
