### ISSUE TITLE
Option to Delete a Block directly from 'Block' Settings section

### ISSUE THREAD

**Issue by mgarfath** [WordPress/gutenberg#8528]
I find it quite difficult to delete a block, the only option i see right now is to click on the '3 vertical dots icon' and choose 'Remove Block' option.

I would suggest that you add a 'delete block' option ( a text link) on the settings panel of every selected block, perhaps as a last option in the settings panel for every selected block.

This would make it easier for people to delete selected blocks.

I have created a draft of how it should look design wise, in the attached jpg to the extreme right bottom  you can see "Remove Block" option in red color text.
![suggested-design-draft](https://user-images.githubusercontent.com/14030089/43679870-0ac17f32-984b-11e8-9777-762c1f238d89.jpg)

Thanks

Mg Arfath

**Comment by Nigelballa** [comment]
I agree. On hover the option to remove a block could be added with a minus icon like the option to add a block

**Comment by mgarfath** [comment]
Based on suggestion of Nigelballa I have created another draft

A minus icon right below the '3 vertical dot' icon, when clicked this minus sign should 'remove' the block.
check the attached draft below:

PS: if this functionality is included don't forget to include an 'alert' browser action that asks user to confim the deletion of the block. it will help if someone accidentally clicks on remove block accidentally.

![suggestion-2](https://user-images.githubusercontent.com/14030089/43680267-30ba7870-9854-11e8-9513-9975d74938a6.jpg)

**Comment by designsimply** [comment]
> I find it quite difficult to delete a block.

I understand that a prior decision has already been made about the placement of the "remove block" action and I would like to include the reasons I have read about behind those decisions. The “remove block” action is in the more menu because that is the designated place for a short list of key actions for blocks. The reason it is not directly available as an icon is because  it kept getting hit by mistake and deleting content should be an explicit action that is not easily triggered by mistake. The reason it is not in the sidebar is that is that the sidebar can be hidden and is a place for secondary actions.

Does the suggestion to select content and press the backspace or delete key until the selected content and block are gone work for you?

I would like to close this issue because a prior decision has already been made, but I would also like to provide an opportunity for feedback in context of understanding the reasons behind the current UI.

**Comment by mgarfath** [comment]
Thank you all for the replies on my post, I would still like to see a 'Remove Block' option in the block settings at the bottom of settings panel, in red font just like my first draft shows, i think  the chance of mis-clicks when the text is in red color and at the bottom of the settings panel is very rare. thats my humble feedback. I'm closing the thread.
