### ISSUE TITLE
Can't edit my previous articles

### ISSUE THREAD

**Issue by smiskina** [WordPress/gutenberg#8529]
I can't edit the articles that have already been published now that I use Gutenberg. I can edit the text but :
- I can't save the changes. In fact all the buttons (save, preview...) are completely frozen
- I can't add a link
- I can't change the format (bold, underlined...)

Also my articles are displayed in only one block.

**Comment by youknowriad** [comment]
Hi there!

To keep the old content as is, we use a single "classic" block for that, that way it stays as is without changes. But you should be able to convert it to blocks if needed or add other blocks around it ...

Can you share a screenshot or a GIF of what you're seeing? do you have any JavaScript error in the console of your browser?

Thanks

**Comment by smiskina** [comment]
Hi, thanks for your reply.

I can't share a screenshot because you won't see anything: the issue is that all the buttons are frozen... I had to reverse to the old editor in order to edit my old articles!

That's too bad because I thought it looked good. It's just not working for me.

**Comment by designsimply** [comment]
I am closing this issue since there hasn't been a recent reply. If you are interested in working together again to try to discover the source of the problem in your case, please check for errors in the browser console and reply here with what you find or open a new issue if you would like.

Thank you for testing Gutenberg and for writing in about the trouble you're having!
