### ISSUE TITLE
Using ACF and Gutenberg - miscellaneous issues

### ISSUE THREAD

**Issue by keepsmilyn** [WordPress/gutenberg#8539]
This is my first post regarding Gutenberg issues. Testing Gutenberg 3.4.0 on WordPress version 4.9.8 as it just prompted us to install and test it out. 

1. Still some issues with using Gutenberg and ACF (Version 5.7.0) plugin which makes me nervous. I have a number of repeater ACF fields and there is no way to move around the position or order of the main editing area and the rows of ACF content blocks. I will try updating ACF to latest version which might fix those issues. 

2. When previewing my page after making some updates not all the ACF fields are displaying in preview mode, this makes me nervous to publish changes as it seems like things are not working. Updating ACF again might fix this too. 

3. Does the heading get displayed automatically now right near the content blog? Seems like there is no way to move / hide or separate this. Perhaps I am wrong and the theme design might dictate this. 

4. Why does the editor area display so narrow? Why not be the full width of the editing area? Seems odd to me, but perhaps its an isolated issue when using ACF again. 

5. Oh and minor annoyance, when you make a change on the page but decide to leave the page and not saving it there seems to be a continual loop with a popup asking if you are sure to want to leave without saving, but you cant seem to get out of this loop without force quitting the page / tab in the browser. 

 - OS: Windows 10. 
 - Browser: Chrome
 - Version:  67.0.3396.99 (64 bit)

**Comment by designsimply** [comment]
Thank you for the feedback! 

<blockquote>I will try updating ACF to latest version which might fix those issues.</blockquote>

Let us know how it goes!

<blockquote>Does the heading get displayed automatically now right near the content blog?</blockquote>

Are you talking about the spacing between headings and paragraphs for content on the front end? Can you include a screenshot or provide a link showing the problem?

<blockquote>Why does the editor area display so narrow?</blockquote>

I have not been following the project since the start but I believe this is done for readability.

> when you make a change on the page but decide to leave the page and not saving it there seems to be a continual loop

I tested this and found that I couldn't trigger a loop if I opened a post, made a change, did not save, and pressed the back button in the browser ([14s](https://cloudup.com/ctJlQegNLkg)). Do my steps match with yours? Is it possible for you to double check this one after updating to the latest ACF? If you're still having trouble at that point, let me know how you think I can modify my testing steps and I'll try it again.

**Comment by keepsmilyn** [comment]
Thanks for replying. 

1 & 2. Will need to retest with updated ACF plugin. 

3. "Does the heading get displayed automatically?"... I mean the page / post title / heading. Not all themes I have previously worked on display the heading / title above the body text. Gutenburg gives the impression that it will display above the body text either way. 

![image](https://user-images.githubusercontent.com/12670301/43808087-a4c23c16-9aee-11e8-9ac2-baeaa361923f.png)

4. Width of editor area... Surely this could be responsive. It looks silly with so much space either side on larger screens, see previous screenshot. 

5. I'll see if I can reproduce the steps. It was quite annoying. I think perhaps I had made a change to the page, then decided I didnt want to save and got the popup thereafter but couldnt seem to get out of it easily.

**Comment by keepsmilyn** [comment]
Thanks for replying.

1 & 2. Will need to retest with updated ACF plugin.

3. "Does the heading get displayed automatically?"... I mean the page / post title / heading. Not all themes I have previously worked on display the heading / title above the body text. Gutenburg gives the impression that it will display above the body text either way.

![image](https://user-images.githubusercontent.com/12670301/43808203-509d7550-9aef-11e8-96e9-8d9eab948d74.png)

4. Width of editor area... Surely this could be responsive. It looks silly with so much space either side on larger screens, see previous screenshot.

5. I'll see if I can reproduce the steps. It was quite annoying. I think perhaps I had made a change to the page, then decided I didnt want to save and got the popup thereafter but couldnt seem to get out of it easily.

**Comment by designsimply** [comment]
Thanks you for adding a screenshot and for explaining that question a bit more. I think I understand the question about titles now. To rephrase (so I can make sure I understand), you are asking if the title shown in the editor will exactly match the title shown on the front end if the theme you are using has customized how titles look. It's possible It's possible for a theme or plugin to customize how titles look in the editor but since Gutenberg is new it's likely that they won't have added support for that yet and I suspect probably will in the future but I think it will be up to the theme to do so.

**Comment by keepsmilyn** [comment]
Thank you. Yes I think that answers my question. So in short if a theme isn't updated to cater for Gutenburg's page title field then it likely wont display correctly in the theme, if for example it was being displayed somewhere other than just at the top of the body copy. Anyway, yes I think you answered my questions, so its important to test with all themes where possible.

**Comment by keepsmilyn** [comment]
1. I think not being able to re-position the gutenburg editor amongst ACF fields is one of my main annoyance. One site I have primarily focuses on the ACF fields being used over the classic editor box, so it was displayed further down the admin page, but now its top / front and centre and will confuse the site editors. If you can assign the load order of ACF fields you should be able to do the same with the gutenburg editor. 

![image](https://user-images.githubusercontent.com/12670301/44007748-3905c1a2-9ede-11e8-917c-0b5654b5894a.png)

2. I've updated all plugins and tested again and the ACF fields are now displaying in preview mode as expected.

**Comment by keepsmilyn** [comment]
4. Furthermore on the width of the editor, as previously mentioned displaying it "responsively" would solve this problem. But interestingly I couldn't figure out how to get the full-width / wide image to work like in the example Gutenberg post. This was the only thing full-width on the page but I don't know how it was assigned to display this way. Surely if an image can be made full-width so can content.

**Comment by designsimply** [comment]
Apologies for the delay in reply.

> So in short if a theme isn't updated to cater for Gutenburg's page title field then it likely wont display correctly in the theme

I think the title should display properly on the front-end just as before. Are you experiencing the opposite?

> I think not being able to re-position the gutenburg editor amongst ACF fields is one of my main annoyance.

I feel this is some thing to request from the ACF developers. I think it should be possible for them.

> I couldn't figure out how to get the full-width / wide image to work like in the example Gutenberg post.
> Surely if an image can be made full-width so can content.

Full-width and wide image support will depend on the theme. The theme also has the option to adjust the $content_width variable to change the width of the editor. This help page shows how:  https://wordpress.org/gutenberg/handbook/extensibility/theme-support/#changing-the-width-of-the-editor
