### ISSUE TITLE
/gutenberg/post-content.js needs to be translatable.

### ISSUE THREAD

**Issue by tobifjellner** [WordPress/gutenberg#8547]
**Describe the bug**
We're now asking people all over the world to test Gutenberg. But the sample content we offer still can't be translated. Needs to be fixed soon. /gutenberg/post-content.js should use the js-i18n functions.

**To Reproduce**
1. Use WordPress in any language except en_US.
2. While installing Gutenberg, note that information about Gutenberg is (can be) translated to your own language, as well as the text on, for instance, sv.wordpress.org/gutenberg
3. Hit the function for sample content. It will be in English (US)

**Expected behavior**
The sample content should be prepared for translation. This is important, since the visual feeling is very different between Japanese, any RTL language, and English.

**Comment by swissspidy** [comment]
Using the JS I18N package for this means `post-content.js` needs to be run through Babel as well, especially for the string extraction.

Since the JS file is so simple and is loaded directly using `file_get_contents()` and then passed to `wp_add_inline_script()`, we can just as well just do this in PHP. There's no downside to that.
