### ISSUE TITLE
How can I make the "feature this post" checkbox work for my custom theme?

### ISSUE THREAD

**Issue by almaqdessy** [WordPress/gutenberg#8568]
Hi, 

In my wp website http://www.almaqdessy.net - I have an attribute to feature the post on the home page top slider. With old wp editor it was great, with the new editor it shows a conflict. 

In the new editor if I select that option "feature this post" and then click save button, it becomes unchecked by itself!! I then I went to the old editor to be able to save it.

Kindly see below image
https://image.ibb.co/kTzxFe/Untitled.jpg

![untitled](https://user-images.githubusercontent.com/1119271/43726840-7af74f4e-995d-11e8-8484-b755f4fcb2d0.jpg)

Thanks indeed

**Comment by almaqdessy** [comment]
Hello again, the problem is that you have to access the site, everything is within the theme and can not share any piece of it.

It is wordpress website with a wp theme.

**Comment by almaqdessy** [comment]
I can share login with you privily

**Comment by designsimply** [comment]
My apologies. Custom consultations for code review are not a part of the open source development here. Perhaps you are able to modify one of the free open source themes to add a similar example of the "feature this post" checkbox and share that instead of your personal theme. If this is possible, please reply back here with the relevant details and we can re-open the issue to see if someone is able to help.
