### ISSUE TITLE
URLInput: Include date as context for link search results

### ISSUE THREAD

**Issue by JoaocsMagalhaes** [WordPress/gutenberg#8573]
When we insert a link on a word(s), in the list of related links we don't have anymore the date of the article published or if it's a page or event.
That kind of information is important because we may want to make interlinking to older pages or understand if we're not linking to a past event for mistake.

thanks
Joao

**Comment by aduth** [comment]
Testing this today. If I'm understanding correctly, the request is to include additional contextual information in the list of posts / pages presented as options when adding a link to text?

![image](https://user-images.githubusercontent.com/1779930/58723581-70b27a00-83a8-11e9-9b3a-d4844cb938d5.png)

**Comment by karmatosed** [comment]
I think we can go for a simple option using what classic editor has for now:

![classic](https://user-images.githubusercontent.com/253067/60289640-cda14180-990e-11e9-8d7b-c3b82f2f5e5c.png)

The option I am suggesting then would be:

<img width="928" alt="Exploration" src="https://user-images.githubusercontent.com/253067/60289649-d4c84f80-990e-11e9-8d0b-ca8e7927ec8f.png">

**Comment by sarahmonster** [comment]
+1 to this approach. How would it work for longer post titles? How would we indicate other CPTs, like pages?

This does add a bit of extra cognitive load to the UI. Would there be a way of only showing this information if it's relevant? For instance, if I just have one piece of content with the title I've searched for, I probably don't need any additional context, but if I have multiple pieces of content in a search result, I might need more information in order to make an informed decision. Is there a way of supporting both of these use cases without creating an inconsistent interaction pattern?

**Comment by paaljoachim** [comment]
A thought...a quick mockup.
I think of this similar to making a search in the future backend.
It will show posts, then pages and then CPTs.

![Link-box](https://user-images.githubusercontent.com/5323259/60906409-573e0100-a277-11e9-83fd-0568f95abf18.jpg)

**Comment by karmatosed** [comment]
@paaljoachim interesting, thanks for taking the time to mock this. I do think perhaps just showing date works as a starting point. Perhaps this is a solid exploration into the next iteration?

**Comment by sarahmonster** [comment]
Post type may be confusing for some users—many people aren't super aware of the distinction between posts and pages, and if I only have one piece of content named "Hello world", then displaying the post type doesn't really give me any additional information I didn't already have. It might make sense to show post types only as a way of clarifying the decision between two pieces of content with the same title.

In the same vein, it's probably only useful showing dates for posts—since pages and other types of content aren't tied to a date in the same way, this information just becomes visual clutter that doesn't help with the task at hand (selecting the right piece of content to link to.)

A better solution to the problem could be to show dates for posts, and post types for all other types of content:

![Post search](https://user-images.githubusercontent.com/376315/62312276-ae558100-b485-11e9-9990-262d1d546585.png)

Note that I've tweaked the colours here so they pass colour contrast checks, but we'll also want to consider how to make this interface as usable as possible for keyboard and screen reader users. There's some prior art in the original designs for the navigation menu block:

![image](https://user-images.githubusercontent.com/376315/62312462-24f27e80-b486-11e9-8132-b29198104670.png)

It would probably be good to double-check to see if this is the best approach, or if we're alright with just having the current focus styling, rather than adding an explicit button.

**Comment by enriquesanchez** [comment]
Discussed during [today's Gutenberg design triage](https://wordpress.slack.com/archives/C02S78ZAL/p1575394181149700) ([registration required](https://make.wordpress.org/chat/)).

We agreed that the classic editor approach (https://github.com/WordPress/gutenberg/issues/8573#issuecomment-506452198) seems to be the simplest and clearest solution.

**Comment by xnau** [comment]
+1 for me on this...does anyone know if it is possible to hook into this functionality and add something like this as a plugin?

**Comment by enriquesanchez** [comment]
I'm adding 'Needs Design Feedback' again because the link component has changed quite a bit since the creation of this issue and this issue needs to be reevaluated.

<img width="444" alt="Screen Shot 2020-03-13 at 12 43 04" src="https://user-images.githubusercontent.com/3276087/76650873-1181b880-6529-11ea-91fe-874fa25412f2.png">

**Comment by Ryokuhi** [comment]
This issues was discussed today during the Accessibility Team's weekly meeting: you can find the complete discussion here: [https://wordpress.slack.com/archives/C02RP4X03/p1584117146464800](https://wordpress.slack.com/archives/C02RP4X03/p1584117146464800).

As already pointed out by @enriquesanchez, the current version of Gutenberg already adds more information to each option (such as the URL and the post type), so new mockups to understand where to add the post/page date are needed.

During the discussion, more accessibility issues about the listing of available links where pointed out:

1. Below is an example of list of possible links to post/pages (the dark gray rectangle allows to visualize what is announced by a screen reader).

<img width="1019" alt="A list of options for posts/pages that can be linked to the page" src="https://user-images.githubusercontent.com/44094572/76655051-c093b380-656c-11ea-8db0-5fe5ed56c00e.png">

Here is the code of the corresponging element.

```
<button type="button" role="option" tabindex="-1" id="block-editor-url-input-suggestion-5-1" aria-selected="false" class=" ... ">
	<span class="block-editor-link-control__search-item-header">
		<span class=" ... ">Mark function</span>
		<span aria-hidden="true" class="block-editor-link-control__search-item-info">http://local.wordpress.test/mark-function/</span>
	</span>
	<span class=" ... ">post</span>
</button>
```

From a technical point of view, here is what is announced:
  * anything inside a `role="option"` gets “flattened” to a string and announced as such;
  * the URLs are not announced because they use `aria-hidden="true"`;
  * the “type” e.g. `post` is announced;
  * the rest is added by the screen reader e.g. `text (2 of 3) completion selected`.

The information provided is probably not very clear to understand for a screen reader user: adding some screen-reader-only text would probably be useful to add context (especially if also the date of the post/page is added to the information already provided).

2. The toggle to choose if the link should open in a new tab is located under the suggestion list: this would be unexpected for a screen reader user.

3. When typing the name of the post/page to be linked, the user can also create a link: the URL of such link would be what has been typed. In the screenshot below, the user typed "hello" and would be able to create a link to `http://hello`.

<img width="972" alt="The list of link options allows to add a URL link even if what is added is not a URL" src="https://user-images.githubusercontent.com/44094572/76654551-7f4ed400-656b-11ea-9bad-40f3b0089eb1.png">

Best solution would be to first check that the entered string is a valid URL and then offer the ability to insert it as a link. Also, the option to add the URL is the only one with an icon to the left, so there's no visual uniformity.

4. The background color of the highlighted option is a light gray, very similar to the white background of non-highlighted options.

<img width="438" alt="The highlighted option background has a very small contrast with respect to standard white background" src="https://user-images.githubusercontent.com/44094572/76654379-1a937980-656b-11ea-8f0e-02aa776896aa.png">

The points above can be discussed in the context of the current issue, or they can be separated into new issues for better discussion.

**Comment by johnstonphilip** [comment]
Just wanted to note that the permalink only provides useful information if permalinks are set to be pretty. 

For example, this is not helpful to the user`
`http://mysite.com/?p=9346897345`

But if set to be pretty it is helpful:
`http://mysite.com/my-posts-title`

Whereas a date would be helpful regardless of the site's permalink settings.

**Comment by paaljoachim** [comment]
Comparison.

Using the Classic Editor plugin:
Link module has focus on title, page and for posts date.
![Screen Shot 2020-03-24 at 21 45 10](https://user-images.githubusercontent.com/5323259/77475421-16901300-6e19-11ea-9ffd-808c8533417d.png)

Using Gutenberg plugin version 7.7.1.
Link module has focus on title, url and post/page/url.
+ Open in new tab.
![Screen Shot 2020-03-24 at 21 48 39](https://user-images.githubusercontent.com/5323259/77475518-417a6700-6e19-11ea-8217-2aa438cc421f.png)

What about removing the word post and instead inserting the date?

**Comment by karmatosed** [comment]
I actually, in this case, think the type is more useful potentially than the date. This was worked on within the new interface a bit and I would love to have that reviewed over the older one that's linked previously for accessibility. @enriquesanchez do you think you could see about that happening the weekly triages for a11y?

**Comment by enriquesanchez** [comment]
@karmatosed the new link creation UI was reviewed and discussed a couple of weeks ago (see https://github.com/WordPress/gutenberg/issues/8573#issuecomment-598903828 above). 

Is there anything else that you'd like us to check?

**Comment by paaljoachim** [comment]
I have associated this issue with the link control issue being updated here: https://github.com/WordPress/gutenberg/issues/23375

**Comment by mapk** [comment]
In [today's triage meeting in Slack](https://wordpress.slack.com/archives/C02S78ZAL/p1596556975098100), the Design Team thought it would be good to include this work in the new LinkControl UI being explored here: https://github.com/WordPress/gutenberg/pull/24021 and in the issue here: https://github.com/WordPress/gutenberg/issues/23375

Basically trying out a date in the results dropdown.

**Comment by karmatosed** [comment]
I think based on the work going on in navigation and the current link interface, that my advice would be to follow the work in #23375 and iterations there. Based on this and the new work going on with navigation, let me loop in @jasmussen for that consideration, I think swapping needs design for feedback label is good here.

**Comment by kellychoffman** [comment]
> I think based on the work going on in navigation and the current link interface, that my advice would be to follow the work in #23375 and iterations there. 

+1. Everyone okay to close this issue out in favor of the work going on there? Reopen if not.
