### ISSUE TITLE
Does not work with Recipe Plugins

### ISSUE THREAD

**Issue by big-boobs-mcgee** [WordPress/gutenberg#8599]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by youknowriad** [comment]
Hi there!

Thanks for the report, can you give us more information here:

 - Which recipe plugin is this?
 - What's the JavaScript error you see on the console?

Also, it might be a good idea to reach out to the plugin author to ask if they plan to work on Gutenberg compatibility.

Thanks.

**Comment by MadameThermomix** [comment]
Hello, I have the same issue so here is more info:

Describe the bug
Gutenberg editor does not support recipe plugins that have a clickable button to insert a recipe card or recipe block. I currently use WP Recipe Maker, Recipe Card and EasyRecipe plugins.

To Reproduce
Steps to reproduce the behavior:

Go to 'Add'
Click on 'New Post'
Expected behavior: I expect to see buttons (usually at top of classic editor) to insert recipe blocks (see screenshots). For plugins WP Recipe Maker, Recipe Card and EasyRecipe (among others I imagine).

In the classic editor I would 
- position my curser where I wish to insert a recipe and then
- click on one of the recipe plugin buttons to create an editable recipe block (as in screenshot 2)

In the Gutenberg editor I have no easily ascertainable way to insert a recipe block. This is not a good situation for a food and recipe blog ;-)

Screenshots
See below. 

<img width="838" alt="screenshot for gutenberg issue" src="https://user-images.githubusercontent.com/29141382/43770425-98d4fda6-9a3c-11e8-8240-e48883e1573b.png">

The above shows the insert buttons from the various plugins as shown in the classic editor.

<img width="1524" alt="screenshot for gutenberg 2" src="https://user-images.githubusercontent.com/29141382/43770659-522d5c76-9a3d-11e8-8f8f-5c37ab4d7e6b.png">

This screenshot shows the editable recipe card block that results from clicking on the insert button from the classic editor.

Desktop (please complete the following information):

OS:  High Sierra 10.13.6
Browser Chrome 
Version 67.0.3396.99 (Official Build) (64-bit)

I hope this helps. And I hope you can find a workaround for this issue ;-)

**Comment by youknowriad** [comment]
Oh I see now, Do you see these buttons in the "classic block"?

One of the goals of Gutenberg is to unify the way we add content: using the block inserter. And for this purpose some extensibility APIs are not available by design. For example the recipe card is a perfect use-case for a custom block. 

I'd encourage you reach out to the plugin author to see if he has plans on building custom blocks for his plugin.

Here's a snippet that can help to convert any shortcode into a block

https://gist.github.com/pento/cf38fd73ce0f13fcf0f0ae7d6c4b685d

I'm going to close this issue for now as there no plans to support these extensibility APIs in Gutenberg.

Thanks for your understanding.
