### ISSUE TITLE
Loss of category functionality in plugins Better Categories, Category to Pages WUD, Post Category Filter

### ISSUE THREAD

**Issue by richardiriwn** [WordPress/gutenberg#8601]
**Describe the bug**
Essential plugins that I use to create and categorise pages do not work with Gutenberg, but are essential for my work.

**To Reproduce**
The plugins I use to manage Categories are: 
* Better Categories - which gives a manageable list of categories with subcategories hidden until expanded.
* Category to Pages WUD - which gives me the same categories for Pages as well as Posts.
* Post Category Filter -  which allows me to Filter Categories in order to quickly find and select them

**Expected behavior**
Would like to retain current behaviour as with Classic Editor when working with Gutenberg. 

**Screenshots**

<a href="https://play.hymnswithoutwords.com/category-image/" rel="noopener" target="_blank">What category selection looks like on one of my web sites with Classic and Gutenberg.</a> We use 1000's of categories.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 67.0.3396.99 (Official Build) (64-bit)

**Additional context**
- Please add the version of Gutenberg you are using in the description. 3.4.0
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by youknowriad** [comment]
Hi Thanks for the report!

A lot of these plugins rely on the DOM directly to tweak the selectors and the UI. The problem with this is that relying on DOM is not an official API and it's error prone because any update to the DOM will break the said plugins which means it's quite impossible to ensure backwards compatibility for plugins relying on DOM Nodes.

That said, I'm not certain that all of these plugins fall into this category, it might be good to try to reach out to the plugin authors to see if they have plans to provide Gutenberg support. On our end, if you have details about specific APIs breaking, JavaScript errors in the console, we can try to debug and see what we can do.

Thanks

**Comment by richardiriwn** [comment]
Thanks for the response - I will ask the Plugin developers.

**Comment by chrisvanpatten** [comment]
Also for future plugin devs, this can be accomplished via the `editor.PostTaxonomyType` filter; see #8225.
