### ISSUE TITLE
Slider handle is misplaced inside of the slider bar on IE11

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#8620]
**Describe the bug**

On IE11, the handle (dot) of the [slider component](https://github.com/WordPress/gutenberg/blob/6928e41c8afd7daa3a709afdda7eee48218473b7/packages/components/src/range-control/README.md) we use in our Settings Sidebar appears clipped inside of the slider bar:

<img width="265" alt="screen shot 2018-08-06 at 2 48 52 pm" src="https://user-images.githubusercontent.com/1202812/43735644-1fe442ac-9989-11e8-81eb-0aef207d0c56.png">

The slider also appears to be only 1px tall. As a result, the slider is difficult to use in this case.

**To Reproduce**

1. Use IE11
2. Add one of the following blocks: paragraph, cover image, column, latest comments, latest posts, gallery.
3. Look in the block settings panel for the slider. 

**Appearance in Safari for reference**

<img width="266" alt="screen shot 2018-08-06 at 2 54 27 pm" src="https://user-images.githubusercontent.com/1202812/43735459-a458778e-9988-11e8-966c-8b2371027f9d.png">

<img width="271" alt="screen shot 2018-08-06 at 2 49 17 pm" src="https://user-images.githubusercontent.com/1202812/43735460-a4670592-9988-11e8-88b0-d154c777fe15.png">

**Appearance in IE11**

<img width="270" alt="screen shot 2018-08-06 at 2 54 09 pm" src="https://user-images.githubusercontent.com/1202812/43735468-ac1fde8a-9988-11e8-84d1-28a4de0a7163.png">

<img width="265" alt="screen shot 2018-08-06 at 2 48 52 pm" src="https://user-images.githubusercontent.com/1202812/43735469-ac35e9a0-9988-11e8-8ce8-4aa3286f28e2.png">

**Tested in**
Windows 7, IE 11.0.9600.19080
Gutenberg 3.4

**Comment by aduth** [comment]
Confirmed this is still an issue as of 2019-05-31.

Suggestions to explore for possible resolution:

- The thumb styles for the range are custom, and even include an Internet Explorer specific implementation. There may be an error in this implementation
   - https://github.com/WordPress/gutenberg/blob/1d2d1fc9dc88c97cb8f23472b03cc6a2d8241df0/packages/components/src/range-control/style.scss#L71-L78
- The slider has a height of `1px`, intentional for the non-thumb portion of the range control. I expect in other browsers, it's assumed (and working correctly) that the thumb would _overflow_ out of this container. See [CSS `overflow`](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow).

**Comment by jasmussen** [comment]
I'm unaware of why the slider may have regressed — I've a good VM set up, so I'm pretty confident that it must've worked when I shipped that PR. So I would also suggest that the 1px height is likely the issue.

**Comment by tellthemachines** [comment]
Lack of visibility of the slider is no longer an issue in IE, but the handle now appears incorrectly positioned:

![slider](https://user-images.githubusercontent.com/8096000/79824793-73f88f00-83da-11ea-95a9-60b1bfa5b2e5.png)

This can be easily fixed by removing the `padding-top: 15px;` from the parent `Wrapper`. Removing it has no effect on the other browsers.

**Comment by paaljoachim** [comment]
Is this issue still valid? What is the next step?

**Comment by youknowriad** [comment]
IE11 support is being dropped, context:

- https://make.wordpress.org/core/2021/03/04/discussion-dropping-support-for-ie11/
- https://make.wordpress.org/core/2021/03/25/discussion-summary-dropping-support-for-ie11/
- https://make.wordpress.org/core/2021/04/22/ie-11-support-phase-out-plan/ 

I'm closing this issue as it's not something we'll be investing in.
