### ISSUE TITLE
Gutenberg and Visual Composer/WP Bakery not compatible

### ISSUE THREAD

**Issue by MvcWebSeven** [WordPress/gutenberg#8669]
I Installed the Gutenberg plugin and the entire Visual Composer editing area disappeared in the "Edit Page" area. I was using the Artbees Jupiter theme, most current theme, all plugins were updated (WP Bakery/VC, Wordfence, Caldera forms, All-in-one SEO, and a few more). The WordPress version is 4.9.8. I disabled the Gutenburg plugin and Visual Composer worked fine. 

Any Thoughts?

**Comment by epakrat** [comment]
I submit that this is not a Gutenberg issue and rather a plugin Vendor issue. It's not the responsibility of the Gutenberg Team to make sure every page builder works with it regardless of popularity.

As such "WP Bakery Page Builder" and "Visual Composer" are now TWO distinctly different plugins / products offered by the same vendor. That vendor is 100% responsible for the decision to make the one or both of these plugins compatible. Combining them together into one issue is also not ideal for discussion since they will be confused. Not to mention the confusion that surrounds the recent name change already.

Until the plugin vendor shows public signs of being remotely interested in even beginning to address any current incompatibilities and communicate their intentions to their customers, this will continue to be a problem for those that still choose to use these products. 

**Posting here will likely not amount to much or resolve your issue(s). Instead, contact the plugin vendor and request that they start taking Gutenberg compatibility and integration seriously.** Demand a roadmap. If they can't provide any concrete development details, are unresponsive, brush you off, provide generic answers, etc then at this late stage then anyone would be wise to consider the plethora of other options ahead of Gutenberg's inclusion in WP v5.0

**Comment by MikeMitterer** [comment]
I think it's also your responsibility.
WB PageBuilder / VC is one of the most widely used editors for WP. Ignoring the incompatibility has a huge impact to all the users. I just tried Gutenberg on one of my sites and because of this issue I thought my whole site broke - it was a shock! The second thing I did was removing Gutenberg from plugins. I don't play with a new tool if it looks like it breaks everything. 

As and enduser I don't care if WP or WP Bakery is responsible for this - the only thing I see is that installing a new plugin breaks the whole system...

**Comment by epakrat** [comment]
WB PB / VC isn't just one plugin anymore. Again, it is two. Both need separate attention. Though I suspect more people are using WPPB than VC these days.

"As and enduser I don't care if WP or WP Bakery is responsible for this - the only thing I see is that installing a new plugin breaks the whole system..."

This is not new or exclusive territory for Gutenberg though. You can already install many plugins that "breaks the whole system" that have nothing to do with Gutenberg. To fix those issues, you contact those plugin authors, third party WordPress help, etc. 

Thankfully, the "Classic Editor" plugin highlighted by the recent "Try Gutenberg" message in WP v4.9.8 fully restores the dependencies of most plugins that require the old editor still -https://wordpress.org/plugins/classic-editor/

Installing the classic editor plugin in WP v5 will fix that "broken system" if the vendor still has yet to catch up and provide a fix by that time.

**Comment by pento** [comment]
Thank you for the discussion, everyone.

While we're working to make Gutenberg compatible with every plugin we can, page builder plugins like WP Bakery and Visual Composer rely heavily on the behaviour of the classic editor in ways that are wildly incompatible with Gutenberg.

For plugins like these, there are two options available:
- Require the [Classic Editor plugin](https://wordpress.org/plugins/classic-editor/) to be installed, so you can continue using them as before.
- Build their functionality in a Gutenberg-compatible way.

Of course, these are not mutually exclusive: they could release a small update to do the former, whilst continuing work on the latter.

In our discussions with folks representing various page builders, they've all expressed strong interest in supporting Gutenberg natively, so I'd recommend following their news blogs for updates.

**Comment by MinrexDev** [comment]
> I think it's also your responsibility.
> WB PageBuilder / VC is one of the most widely used editors for WP. Ignoring the incompatibility has a huge impact to all the users. I just tried Gutenberg on one of my sites and because of this issue I thought my whole site broke - it was a shock! The second thing I did was removing Gutenberg from plugins. I don't play with a new tool if it looks like it breaks everything.
> 
> As and enduser I don't care if WP or WP Bakery is responsible for this - the only thing I see is that installing a new plugin breaks the whole system...

Why not try the update in test envorinment first, so you can deal with this issues. Its now responsability of WP to fix plugins,  Of course if they choose unpopular features they'll get burn, but its not their fault if  we use VC (I do) and it doesnt work with new version of WP.  We should do our testing before upgrading and fixing whatever is not supported ourself. It's not like we payed for it anyway...

**Comment by beacabrera** [comment]
What if we were able to activate Gutenberg just for posts and not pages? I'd still have my full capabilities for using WP Bakery on page design, but write my posts under beautiful Gutenberg. Unless until this issue is resolved by vendors, which is going to take time since it involves a lot of redoing things and @pento points out.

**Comment by epakrat** [comment]
@beacabrera - You can already achieve this by installing the free "Gutenberg Manager" plugin from the WP Plugin Repository.

**Comment by beacabrera** [comment]
Awesome! Checking it out! Then I don't see a problem with this "incompatibility". I'm sure it'll be temporary and there's a very simple way to work around it.

**Comment by timeassistant** [comment]
I think there is a good point to this thread, given that gutenberg is forcefully installed and set as default if you don't have the classic editor plugin. Saying its not our problem its theirs is rather childish given that gutenberg has been forced upon many users regardless of what THEY WANT. 

Thanks for that team
