### ISSUE TITLE
Insert link: making a link target=“_blank” like walking a tightrope

### ISSUE THREAD

**Issue by frodojrr** [WordPress/gutenberg#8696]
Adding a link is fine. Trying to press that little button to open a link in a new browser window is like walking a tightrope. You need to be spot on. It’s annoying, frustrating, not user-friendly at all.

Think, there are people writing for our blogs who are not adept. Adding new features is nice. But a complete overhaul? I anticipate clients running away from WordPress.

To reproduce? Just add a link.

**Comment by VyxiFaye** [comment]
I just tried this on a post in my drafts and it worked fine for me (and im using a Samsung tablet). Haven't tried it on any other device yet.

**Comment by designsimply** [comment]
Adding a screenshot for reference:

![screen shot 2018-08-08 at wed aug 8 7 13 26 am](https://user-images.githubusercontent.com/1119271/43839305-045db6f0-9adb-11e8-8d3c-7cad8084a5c3.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14174&action=edit running WordPress 4.9.8 and Gutenberg 3.4.0 using Firefox 61.0.1 on macOS 10.13.6.</sup>

@frodojrr I've labeled this as an enhancement request. Thank you for your feedback. I also have some tips that may help you as a temporary workaround while this issue is considered. Try clicking on the text label for the option itself as it may be easier for you. You can also try using the keyboard to navigate from the link field to the setting by pressing `Tab` to navigate through the settings and `Space` to toggle them.

**Comment by EnzoTano** [comment]
I experienced the same issue.. And agree that it is difficult.  @frodojrr Thanks for the advice "Try clicking on the text label for the option itself as it may be easier for you."

**Comment by omaiyea** [comment]
When I commented, inserting links wasn't sticky when using the block editor. It's also not sticky when using the "classic" editor.

**Comment by mtias** [comment]
The current toggle is much more clear and easy to access:

![image](https://user-images.githubusercontent.com/548849/125471420-c7b56e9d-2385-46be-84bb-14cf2bc3761f.png)

**Comment by frodojrr** [comment]
Yes it does. Came a long way in 3 years since this ticket was opened.

Thanks for closing it.

Respectfully,

Gary Kopycinski
W: 708-755-7565 x1239
M: 708-808-0204
eNews Park Forest <http://www.enewspf.com>
<http://www.enewspf.net/>

ü Please consider the environment before printing this e-mail.
