### ISSUE TITLE
How can I make featured image a required field?

### ISSUE THREAD

**Issue by bianqui149** [WordPress/gutenberg#8713]
**Featured Image field Required**
Hi, I have some time tried to implement some hooks to set the featured image like a field required, I notice that this works with the old editor but whit gutenberg a create some conflicts.
Any idea of how can I fixed.
Regards!

**Comment by designsimply** [comment]
Are you able to provide a bit more detail or a code example to test? Specifically, can you talk more about the conflicts you mentioned?

**Comment by bianqui149** [comment]
I tried to set a featured image like a required fields, some while ago I used this plugin https://wordpress.org/plugins/require-featured-image/. 
But with Gutenberg I have problems.

**Comment by skorasaurus** [comment]
This can be accomplished with https://github.com/WordPress/gutenberg/pull/10649 although I don't know if that is the recommended way for designating fields to be required; also there doesn't appear to be documentation for it.

**Comment by designsimply** [comment]
@bianqui149 were you able to accomplish your goal using the info @skorasaurus pointed to in https://github.com/WordPress/gutenberg/pull/10649?

**Comment by designsimply** [comment]
Closing since a note was provided that this can be accomplished with the post save locking feature added in https://github.com/WordPress/gutenberg/pull/10649 and at least noted in the documentation at https://wordpress.org/gutenberg/handbook/designers-developers/developers/data/data-core-editor/#ispostsavinglocked

To get help with custom code or if you have further questions, technical help requests have their own section of the support forum at https://wordpress.org/support/forum/wp-advanced/ and you may also ask for technical support at https://wordpress.stackexchange.com/

We are working to prioritize new development for this repository and move help requests to the appropriate support forums. Thank you for your understanding!
