### ISSUE TITLE
Add Special Character Menu 

### ISSUE THREAD

**Issue by lizkarkoski** [WordPress/gutenberg#8782]
Low priority request. 

Add a special character menu to the Gutenberg menu tools. 

**Describe the solution you'd like**
A menu button for inserting special characters with Gutenberg.

**Describe alternatives you've considered**
The only way I can work out to add special characters when using Gutenberg is to switch over to the code editor, add the html for the desired character, and then switch back to the visual editor to continue working. 

Request brought to us through a forum post here: 
https://wordpress.org/support/topic/public-post-preview-special-characters/

**Comment by tofumatt** [comment]
By special characters, do you mean things like emojis? As a MacOS user I usually use the OS-wise special character menu accessed via Control + Command + Space. Does Windows/*NIX have something similar?

Something like:

![2018-08-09 23 36 46](https://user-images.githubusercontent.com/90871/43929493-22a7dc14-9c2d-11e8-9020-c25613a346b7.gif)

right?

**Comment by designsimply** [comment]
This was discussed in #1678 and ended with the character map being accessible in the Classic block and encouragement to implement in other areas as a plugin.

Thank you for the feedback, and if you still feel strongly, consider adding details about your use case in #1678 even though it has been closed.

**Comment by GlennMartin1** [comment]
The most-used block is the Paragraph block - so it needs to be highly functional and full-featured.

**This issue should definitely be reopened. There needs to be a solution to this.**

**Comment by JanPaulKleijn** [comment]
Why is this issue closed?
Until this plugin provides proper text tools it should not EVER be included standard in WordPress.
I live in Europe, and everytime I want to insert a euro symbol I need the special character tool to insert it because my keyboard does not support it.
But here I am talking about myself. Far more important is all the angry clients that are scolding me through the phone. Just because WP thought it would be wise to replace the editor with a handicapped one.
What were you thinking? Remove all this great functionality and maybe people won't notice?

**Comment by designsimply** [comment]
@JanPaulKleijn I closed this issue because I wanted to consolidate to https://github.com/WordPress/gutenberg/issues/1678 as this issue is a duplicate. I have added your use case to https://github.com/WordPress/gutenberg/issues/1678 and would like to say that I appreciate that you have voiced your concern and that even though this issue has been closed, I think it's worth listening to and documenting example use cases (specifics are helpful!) in one place.

**Comment by phpbits** [comment]
Hi everyone! I've just added Special Characters inserter format on [EditorsKit](https://wordpress.org/plugins/block-options/) plugin. Using this plugin you can now have the missing formats from Classic Editor to Gutenberg Block Editor. Here's the preview and I hope everyone will find this very helpful. Thanks!

![gutenberg-special-characters](https://user-images.githubusercontent.com/3365507/76080742-8fead180-5fe2-11ea-8b38-d26d7e54ab2d.gif)

**Comment by arielestigarribia** [comment]
Hi @phpbits , nice job! How can we have this features in the EditorsKit for [Drupal Gutenberg](https://www.drupal.org/project/gutenberg)?
