### ISSUE TITLE
1and1 white page

### ISSUE THREAD

**Issue by Tombost** [WordPress/gutenberg#8792]
**Describe the bug**
Hello,
I have just install a wordpress to my 1and1 webspace, but add page or add article page is blank.
I use cloudflare for the SSL, I have try to desactivate cache (js, css and html)

You can see : 
https://ibb.co/mn7fRU

**Comment by designsimply** [comment]
Thank you for the report! 

Sometimes blank pages were appearing when a race condition happened. This was reported in #8455 and fixed in #8578 and shipped in version 3.5. Can you make sure you have updated to the latest version of Gutenberg?

Cloudflare has also shipped an update on 8-Aug-2018 to prevent some problems with saving ([ref](https://github.com/WordPress/gutenberg/issues/2704#issuecomment-411621573)) and you should update to the latest version to take advantage of that change.

**Comment by Tombost** [comment]
Hi,

I have update to 3.5, same problem...
How i can update clouflare ? This is not automatic ?

**Comment by Tombost** [comment]
I have remove cloudlfare and it work again so the problem is cloudflare, any idea ?

**Comment by designsimply** [comment]
https://github.com/WordPress/gutenberg/issues/2704#issuecomment-411621573 says that Cloudflare implemented a fix before 8-Aug-2018 for problems with their `WP0025B` rule, and the #2704 issue has a some discussion about other possible causes (for errors such as "Prevent abuse against wp-json api Type B" and possibly the `100030` rule) which may also be affecting the WordPress editor. Good next steps would be to:

1. Find out if your Cloudflare WAF log indicates which rule is causing requests to be blocked.
1. Contact Cloudflare to let them know that you're having trouble, what WordPress and Gutenberg and Cloudflare versions you are using, which rule in the Cloudflare WAF logs are causing trouble, and you could also link them to https://github.com/WordPress/gutenberg/issues/2704 in case it helps them with context.
1. Add a comment to #2704 noting that you're still having trouble with Cloudflare and noting what you found in the logs and mention whether you've contacted Cloudflare about the problem.

Thank you for being willing to troubleshoot and work through the issue!
