### ISSUE TITLE
If I would like to add 2 pictures on y blog 330 + 330 . It does not seems possible?

### ISSUE THREAD

**Issue by stMiaux** [WordPress/gutenberg#8793]
If you have a question you have a few places that you can ask this:

- Support Forums: https://wordpress.org/support/plugin/gutenberg
- Handbook: https://wordpress.org/gutenberg/handbook
- https://chat.wordpress.org #core-editor

If you are unable to ask in those places you can ask here, however you will get faster responses through those recommended places.

**Comment by SuperGeniusZeb** [comment]
Could you clarify exactly what you mean? The title is kind of vague, and you did not provide a description for the ticket.

If you want to put 2 images next to each other, you could probably do that with the Gallery block.

You could also use Image blocks nested in a Columns block. Note that the latter is not ideal for responsive design since the Columns block does not yet have collapsing columns on mobile widths... hence the "(Beta)" in its title. See #6048.

Alternatively, I guess you _could_ use the float alignment options on the Image blocks, but floated blocks currently have some UI issues (floats are a pain to work with on the technical side):
- #4127
- #7491
- #7492
- #7500
- #8203
- #8293

There is actually yet another method, though this one is probably the least flexible of all: Inline Images. If your text cursor is in the text field of a Paragraph or other block that supports rich text formatting, you can use the inserter in the top bar of the editor to insert an "Inline Image" (located in the Inline Elements category). You _could_ put several images next to each other like this, but you don't get the ability to use captions or any other advanced features that the Image block has. Usually, you would only want to use Inline Images for things like custom emoji.

**Comment by tofumatt** [comment]
You can add an image using the `Image` block or add a gallery of images using the `Gallery` block. As @ZebulanStanphill mentioned you could try the *Experimental*/*Beta* Columns block. You should be able to specify image size when you add it using the controls on the right:

<img width="1076" alt="screenshot 2018-08-22 16 21 08" src="https://user-images.githubusercontent.com/90871/44473097-7d3ec080-a627-11e8-8b68-18336ccc1b86.png">

**Comment by stMiaux** [comment]
Thank you so much!

Skickat från min iPhone
