### ISSUE TITLE
Consider adding a kicker block used for adding text above the title

### ISSUE THREAD

**Issue by kaffeeringe** [WordPress/gutenberg#8824]
Hej!

Why does the title have to be the top element?

I love using kickers with my headlines: https://kaffeeringe.de/ 

They help making better headlines, because they set the context of the headline. 

I use custom fields for that and I created a hack that displays the kicker field abuve the headline: https://kaffeeringe.de/5647/dachzeilen-in-wordpress/

That doens't work anymore with Gutenberg, which is finde with me, as long as I had a better solution for it. One would be: A kicker block. That I could drag over the headline and that was also available in YoastSEOs titel field. 

It's not. Yet. Please build a solution for my problem. I think, it you also be interesting for some people to have a picture over the headline, or the author info, or some kind of disclaimer.

**Comment by designsimply** [comment]
This does sound like something useful for a subset of users, and because of that, it would be best added via a plugin (similar to the Yoast SEO plugin you mentioned!). I know that Yoast has been working on updates quite a bit, so I would also suggest reaching out to ask them about the feature you're interested in to see if it's something they are already working on or would consider updating.

**Comment by tofumatt** [comment]
I think there was the idea that even the title should be a block (right now it isn't), which would address you wanting to put content before the title, if I understand your request.

What do you mean by "kicker", sorry, I don't quite follow 😄

**Comment by kaffeeringe** [comment]
@tofumatt: In German a "kicker" is "Dachzeile". Literally translated that ist "roof-line". It's similar to a subtitle - only shorter and on top of the headline. 

Example: http://www.spiegel.de/international/ <- the black words on top of the red headlines.

"The title as a block" is a good idea.

**Comment by kaffeeringe** [comment]
@designsimply: Many things in Wordpress are for a subset of users. Making the title a block would change nothing for anybody, but it would enable my example use-cases...

**Comment by wsydney76** [comment]
See discussion in #8234

**Comment by kaffeeringe** [comment]
@wsydney76 Yes, that topic is related, but it's not the same. Subtitle are called subtitle, because they are below the title. What I need it above the title. 

Moreover it's not about kickers. It cloud be useful to be able to put disclaimer, pictures or author-infos on top of the title.

**Comment by afercia** [comment]
As I love good typography, I'm going to subscribe to this issue 🙂For definitions about what a "kicker / teaser / stand-first / deck" is, see https://github.com/WordPress/gutenberg/issues/8974#issuecomment-435575054

**Comment by designsimply** [comment]
<blockquote>@designsimply: Many things in WordPress are for a subset of users. Making the title a block would change nothing for anybody, but it would enable my example use-cases...</blockquote>

Yes, I agree, however, if the subset is small enough then it's traditionally favored to add as a plugin and not a core feature. In this case, it appears the functionality you're looking for could be solved by making the title field into a block and because of that I would like to close this issue in favor of the one @DevOnWheels opened at #11553. Thank you!
