### ISSUE TITLE
Checkbox styles are inconsistent

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#8825]
**Describe the bug**
There are so many inconsistencies within the Gutenberg UI. In 3.5.0 the toggle switches have been replaced with checkboxes and they've also been styled to make them more noticeable.

The UI should be consistent. If you have checkboxes in one part of the UI, then they should match checkboxes used in another part of the UI, especially when you're talking about the exact same screen.

The checkboxes in the _More_ menu look completely different to the checkboxes in the sidebar.

![screenshot_774](https://user-images.githubusercontent.com/2078245/43953881-d04ab4da-9cdd-11e8-93ee-fa9a773647c0.png)

**To Reproduce**
1. Edit a page and click on the _More_ menu
2. Compare with the checkboxes in the sidebar, in the _Document_ tab

**Expected behavior**
The UI should be consistent, and it's not. This is just one of many inconsistencies with the current UI.

**Desktop (please complete the following information):**
- OS: macOS Sierra 10.12.6
-  Browser: Firefox Quantum 61.0.1 (64-bit)
-  Gutenberg: 3.5.0

**Comment by chrisvanpatten** [comment]
They use different styles here because the "checkboxes" in the popover menu aren't actually checkbox form inputs.

They're just icons indicating the menu item is selected/active, like checkmarks in menus in the macOS menubar:

![screen shot 2018-08-10 at 10 43 42](https://user-images.githubusercontent.com/1231306/43967608-629a9dae-9c8a-11e8-8091-16c31489562e.png)

Perhaps there's an argument that the popover menu shouldn't use a checkmark symbol/icon, but it definitely shouldn't use the checkbox styles.

**Comment by ZebulanStanphill** [comment]
See #8588 for the reasoning behind the current look of checkboxes and why they are used where they are used.

**Comment by designsimply** [comment]
Closing due to the explanations in #8588.

**Comment by maddisondesigns** [comment]
That seems fair enough. Thanks.
