### ISSUE TITLE
NivoSlider Problem

### ISSUE THREAD

**Issue by markolbert** [WordPress/gutenberg#8849]
When I open an existing post in Gutenberg to edit it, I get the following error box:

Failed to load plugin url: http://council.olbert.com/wp-content/plugins/nivo-slider-pro/scripts/mce-nivoslider/nivoslider.js

**Comment by earnjam** [comment]
This sounds like an issue in the NivoSlider plugin and is probably something they will have to fix. Do you have a screenshot or any additional information?

**Comment by designsimply** [comment]
I don't have access to the Nivo Slider Pro plugin, but I found and tested the simpe NivoSlider from https://wordpress.org/plugins/simple-nivoslider/ using the following testing steps:

1. Create a new post and add a galllery.
1. Select "Edit as HTML" and surround the gallery code with `[simplenivoslider]` and `[/simplenivoslider]`.
1. Select "Keep as HTML" if prompted.
1. Publish and view the post.

<strong>Result:</strong> I was able to publish a post with a gallery without any errors.

First, make sure you have updated to the latest versions of everything because there have been a lot of recent updates. If you are still having trouble with your plugin after that, please ask the plugin developers for help. If https://themeisle.com/plugins/nivo-slider/ is the same plugin you are using, then the contact page at https://themeisle.com/contact/ might be the right place to ask.

Thank you for testing Gutenberg!
