### ISSUE TITLE
How do I set a featured image, share to social media, and add captions below photos instead of on top of them?

### ISSUE THREAD

**Issue by biselblog** [WordPress/gutenberg#8860]
**Is your feature request related to a problem? Please describe.**
There are some features missing in Gutenberg that are in the Classic Editor.

**Describe the solution you'd like**
In Gutenberg:

1. There is no way to set a featured image.
2. "Publish to..." social media options are missing for posts as they are published.
3. In an image gallery, there needs to be a way to add the captions to below the photos instead of on top of them.

**Comment by ZebulanStanphill** [comment]
>There is no way to set a featured image.

I can set a featured image:
![image](https://user-images.githubusercontent.com/19592990/43987199-bfd21ad0-9ce2-11e8-9b8a-46d5b88c10bb.png)

What do you see on your WordPress installation? Could you provide a screenshot? Do you see any errors in the JavaScript console of your browser's developer tools? What browser are you using? What theme are you using, and what plugins do you have active on your website?

>"Publish to..." social media options are missing for posts as they are published.

I think that is a Jetpack feature, not a core WordPress feature. If that is what you are referring to (and not something added by another plugin), then you'll be glad to know that the Jetpack team is working on getting this feature working with Gutenberg. Check out these pull requests for more info:
- https://github.com/Automattic/jetpack/issues/9039
- https://github.com/Automattic/jetpack/pull/9934
- https://github.com/Automattic/jetpack/pull/9955

>In an image gallery, there needs to be a way to add the captions to below the photos instead of on top of them.

As it turns out, there is a PR being worked on to implement this: #8344. Also note that themes can style blocks and provide alternate style variations that the user can switch between using the block style variations API. The Button, Quote, and Separator blocks provide some examples of this. Click on the block chip/icon on the far left of their toolbar to see not only the available transforms for the block, but also all the style variations registered by core and/or your theme and plugins.
![image](https://user-images.githubusercontent.com/19592990/43987289-3e484028-9ce4-11e8-8486-8b70b19ac277.png)

(Actually, themes can also change the default styles of all the blocks in the editor, and also change things like the content width in the editor to match the front-end. The [Atomic Blocks Theme](https://arraythemes.com/themes/atomic-blocks-wordpress-theme/) is a good example of this.)

There is also discussion of adding the ability for the user to register a CSS class as a custom style that can be selected from the transforms/styles UI. See #7551.

**Comment by tofumatt** [comment]
Looks like this issue is covered by:

* Automattic/jetpack#9039
* Automattic/jetpack#9934
* Automattic/jetpack#9955
* #8030

so I'm going to close it as the featured image part was addressed and the other issues are being tracked elsewhere. Please follow those issues for updates on these features being implemented, thanks!
