### ISSUE TITLE
Drag and drop modal box or UX improvement to more easily re-order blocks or put blocks into columns

### ISSUE THREAD

**Issue by babblebykev** [WordPress/gutenberg#8884]
There should be a button somewhere in the toolbar that would activate a modal box where blocks can be more easily re-ordered or placed into columns via drag-and-drop. The manual approach (the "move up and down" arrow buttons) feels more time-consuming.

**Comment by ZebulanStanphill** [comment]
You mean something like this?
https://oxygenbuilder.com/documentation/visual-editing/editor-overview/
![oxygen-page-part-hierarchy-example](https://user-images.githubusercontent.com/19592990/43997858-63b778aa-9dad-11e8-89d4-7fd1418d34ca.png)

That would be pretty neat. There is actually another open ticket about a similar thing (#5301), though it only includes document headings, rather than all blocks. I think a full block hierarchy that lists everything would be more useful for drag-and-drop reordering.

There is also an open issue (#7114) and corresponding work-in-progress pull request (#8764) to add a drag handle to the hover label, which is another way of adding drag-and-drop, though it does not apply to the selected block unless you make the hover label appear for selected blocks.

The outcome of #6224 may also end up adding a drag handle, which could make #7114/#8764 redundant, though it really depends on what ends up getting implemented.

I also think the movement arrows should double as drag handles for drag-and-drop. Actually, I think it would be nice if all the controls around a block doubled as drag handles, though I would be happy with just the up/down movers.

**Comment by babblebykev** [comment]
Close. I was thinking maybe something more like the "Reorder Project" window on Behance, because it matches Gutenberg being a highly visual-driven editor.
![screen shot 2018-08-12 at 10 55 27 am](https://user-images.githubusercontent.com/7627386/43998017-613c7258-9e1e-11e8-835c-a856c46e2995.jpg)

**Comment by chrisvanpatten** [comment]
Just to be sure — and please accept my apologies that this is slightly obvious, just want to be 100% sure! — @babblebykev are you aware of the existing Drag-and-drop capabilities in Gutenberg?

It's not 100% perfect (grabbing the drag areas can be tough, see #7114) but it might help.

Here's a GIF:

![kapture 2018-08-12 at 17 41 53](https://user-images.githubusercontent.com/1231306/44006719-04315a90-9e57-11e8-8dd9-432402630af3.gif)

**Comment by babblebykev** [comment]
@chrisvanpatten Now that you mentioned it, maybe it could be made more obvious on hover (same with the "Remove block" button, but that's for another time).

Then again, because my posts tend to get very long (I am working on a portfolio blog at the moment), it would feel a little time consuming to scroll the page while dragging a block, and I would like to see a sort-of bird's eye view of all the blocks I placed on a post, which is where the modal box idea comes in.

**Comment by chrisvanpatten** [comment]
@babblebykev Thanks! I agree it could be more obvious. I think for now because we're at feature freeze, a modal box to get that "birds eye view" would be best implemented as a plugin that could get merged in later.

I'm going to close this for now but I'll also add it to the Ideas project so we can revisit later. For discussion on making this existing drag & drop more visible, definitely comment over on #7114 or give it a thumbs up :)

**Comment by ZebulanStanphill** [comment]
For future discussion, it is worth noting that Divi has something pretty similar to this called Wireframe View:
![image](https://user-images.githubusercontent.com/19592990/44040135-3df2a994-9ee0-11e8-84fc-f46983724ba6.png)

Since Gutenberg does not have a strict section→row (with built-in columns)→module layout system (a block can not be nested at all, or it could be nested many levels deep, and any custom block could act like a row if desired), having blocks show up in a wireframe-style view in rows if they are laid out horzontally would probably be rather difficult to pull off. Therefore, a Gutenberg equivalent would probably just show all children blocks listed vertically, which ends up making it pretty similar to the Oxygen UI I showed earlier, albeit larger and with a different feel.
