### ISSUE TITLE
How do I add links to images within a gallery so the image is clickable?

### ISSUE THREAD

**Issue by Clemsou** [WordPress/gutenberg#8929]
I'm trying to add links to images within a gallery so the image is clickable and links to an internal page or an external site. I found how to add a link on each image but it appear written on the images when I want it hidden so it looks more aesthetic. Is there a way to do this?

**Comment by designsimply** [comment]
Hi @Clemsou! Thank you for your question. There is not currently a way to add links to images within a gallery, and there is a long-standing request for that in the core WordPress project at https://core.trac.wordpress.org/ticket/13429 

I am going to close this issue a duplicate since there is already a feature request open for it. If you would like to add your voice to the exiting feature request, please add your vote and optionally post a little bit of detail about why you are trying to add links to gallery images and why it is important to you at https://wordpress.org/ideas/topic/custom-links-on-images-within-a-gallery

If you have future questions about how Gutenberg works, can you please post at https://wordpress.org/support/plugin/gutenberg to ask there first? It will help us to keep this area streamlined and support forums are the recommended first place to ask for help with how to use the editor or if a feature has already been requested or not. Thank you so much and thanks for testing Gutenberg and asking questions!

**Comment by galinastgeorge** [comment]
Hello, what is the current situation on this feature? Are you planning to introduce it sometime soon? It makes the gallery feature pointless without the ability to link images to specific URLs.

**Comment by joostmollerus** [comment]
I have a related question. I have created the following page with the Column Shortcodes plug-in.  https://albarosavietor.com/musicians-alba-rosa-viva-2018/ When you click on the image of a musician you go to the bio page. Is there a way to do this is in Gutenberg without the plug-in? I had hoped that I could do this in the gallery block, but that is not possible.

**Comment by designsimply** [comment]
@joostmollerus you could do it by adding the images to a table or a columns block. If you need help or have questions about implementing something like that, please ask for help in the forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/.

**Comment by sasserc** [comment]
Although tedious, but simple (even for a non-developer), if you insert a gallery block and add gallery images and then set number of columns for block and set _**link to:**_ "Attachments", you can then go to the block and "edit in html" and just replace the _**href=urls**_ on each image with the link you want plus **_target="_blank"_** if you want to open in new tab, etc.  For a small gallery, it is not too bad but they do need to fix this.

**Comment by vilian** [comment]
I've had success wrapping the gallery's `<figure>` tags in `<a>` tags.

**Comment by sasserc** [comment]
I found a plugin that will do this: https://wordpress.org/plugins/gallery-custom-links/  and I also discovered I had another premium plugin I was already using that does this. WP Media Folders which is an awesome plugin to create folders in the media library and you can delete the plugin and everything goes back to normal. https://www.joomunited.com/wordpress-products/wp-media-folder

One thing to keep in mind when assigning a link to the image is that anywhere you use that image it will contain the link which may be the behavior you want or maybe not.  If not just create a second image with a different name.

**Comment by Romanskull** [comment]
> Although tedious, but simple (even for a non-developer), if you insert a gallery block and add gallery images and then set number of columns for block and set _**link to:**_ "Attachments", you can then go to the block and "edit in html" and just replace the _**href=urls**_ on each image with the link you want plus **_target="_blank"_** if you want to open in new tab, etc. For a small gallery, it is not too bad but they do need to fix this.

sasserc - this worked great - thank you!

**Comment by VonZubinski** [comment]
The wordpress team seems to be working on a solution right now https://github.com/WordPress/gutenberg/pull/25940

For a temporary workaround you can use @sasserc 's method above or one of the jQuery and CSS solutions mentioned here 
jQuery https://github.com/WordPress/gutenberg/issues/10057#issuecomment-697637513
CSS https://github.com/WordPress/gutenberg/issues/10057#issuecomment-737043001
