### ISSUE TITLE
Add in permalinks to the publishing flow

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#8949]
When someone publishes a post likely at that point they'd want to edit permalinks, let's add it in!

![links1](https://user-images.githubusercontent.com/253067/44058585-73f16c2c-9f46-11e8-94bf-d90e10be3d65.png)

![links2](https://user-images.githubusercontent.com/253067/44058586-741d07a6-9f46-11e8-9fae-60ce21d57a4b.png)

**Comment by danieltj27** [comment]
Agree with the above.

Please make the permalink setting available at all times, or in a much more user friendly location than the proposed solution. It's hidden as it is in 3.5.0, I'd prefer to not have to dig around loads of settings to find it.

**Comment by sarahmonster** [comment]
Whilst adding a check and option to adjust the permalink to the publishing flow *could* be helpful for people, I think it might be more immediately useful to include it in the document settings. 

The first place I would look for the permalink is likely in the Document Settings sidebar panel. That could be a function of having an already-existing mental model of how WordPress works, but given it's where all other post-level settings live, I think it'd be a sensible spot for a permalink setting.

It's worth noting as well that, given the current design suggested in #7602, that the pre-publish panel will be dismissable/skippable, so it's possible that users wouldn't see it at all. The current implementation only surfaces settings that exist elsewhere (almost entirely the document settings!) and is intended to act as a confidence check for people who may be a bit uncertain about pressing the "publish" button.

**Comment by maddisondesigns** [comment]
@sarahmonster I disagree. Gutenberg is intended to replace the editor in the .org software, so that's what we need to compare it against. If you're primarily using that software (as opposed to dot com), then the first place you would look is under the Post/Page Title, because that's where it is currently. Any other position, is forcing users to go searching for it, and hiding it altogether (like it is currently), or putting it behind a publish panel, is even worse.

Whilst putting it in the Document sidebar is better than the Publish Panel, I still don't think it's as good as simply making it visible in it's current location. Also, there's the obvious length restrictions in the sidebar as well. For a typical permalink, you're either going to have to cut it off or wrap it over multiple lines, and either of those options aren't great.

**Comment by danieltj27** [comment]
@sarahmonster 
> could be a function of having an already-existing mental model of how WordPress works

All the more reason to design for the people who aren't as familiar with where all the options are. If it's moved to somewhere more obvious and easy to use/find then the people who aren't as familiar with Gutenberg can still find it.

The focus should be on making those kinds of users happy as opposed to placing it somewhere the designers and developers are fine with. It's more important user aren't annoyed by where it is compared to the designers and developers working on the project.

@maddisondesigns 
> the first place you would look is under the Post/Page Title, because that's where it is currently. Any other position, is forcing users to go searching for it, and hiding it altogether (like it is currently), or putting it behind a publish panel, is even worse

100% agree.

Let's not hide it because it's just as important (arguably more) then the post title itself so it shouldn't be hidden away like an afterthought. It needs to be prominent and in full view.

**Comment by chrisvanpatten** [comment]
It's definitely becoming an issue — there was another report in [Slack](https://wordpress.slack.com/archives/C02QB2JS7/p1534329181000100) this morning.

I like the idea of it being in Document Settings because that's the "Right" place for it based on the Gutenberg UI. However I can also appreciate that it's a pretty big change of venue for such a critical feature.

Maybe it's worth trying in Document Settings for a few cycles as a proposal to see how that feels before going the full legacy route? Just trying to think of a good compromise approach :)

**Comment by danieltj27** [comment]
@chrisvanpatten 

> trying in Document Settings for a few cycles as a proposal to see how that feels before going the full legacy route

The issue with that approach is once it's already there, it probably wouldn't ever been moved again. Plus, once you've placed it somewhere, you shouldn't be moving it again otherwise you'll create more confusion than before.

It needs to be moved to an obvious and sensible location once and not moved again.

**Comment by chrisvanpatten** [comment]
@danieltj27 That might be true if Gutenberg was in WordPress core, but it's not — it's a beta, being developed iteratively. Other major components have changed dramatically throughout the dev process (the inserter, for instance, has been through at least 3 major redesigns and is undergoing another one right now) and there's no reason to think the permalink editor would be treated any differently.

**Comment by danieltj27** [comment]
@chrisvanpatten I disagree and challenge that because Gutenberg is (at this point), very much considered 'core-ready', maybe not technically speaking right now, but the wider community know to expect it to come to WordPress core very soon so I'd argue that most have readied themselves on how it works in preparation for the actual launch.

With that in mind, I insist that it's placed somewhere where everyone can agree and not moved after the fact to reduce any confusion there may be.

**Comment by ZebulanStanphill** [comment]
It is important to keep in mind that in the future, you should be able to edit the templates for the title area of posts. At that point, the post title would become a block. The question is, would you be able to edit the post title area from an individual post or not? The post title area is shared across all posts, so in a way it kind of acts like a reusable block, except with dynamic content dependent upon each individual post.

I would say that the post title area would not be directly editable from a single post. Perhaps a preview of it could be shown in the editor where it would appear with some sort of link to edit the template, though. Of course, this raises questions of how you would edit the title. Perhaps only the `post_content` area would be shown when editing a post, and the title template area would not be shown at all. In that case, the title would probably be shown and look pretty much like it does now, though it may be desirable to visually separate from the actual block editor area with a light dividing line or something to clarify that the title you are editing is _not_ a block, but just a field exposed in a different way than most other fields like categories/tags.

Essentially, that is what the title editor in Gutenberg already is. It is a special area of the editor dedicated to editing 2 fields: the post title and permalink. Most other fields are edited in the Document Sidebar, but these 2 are not. If you were to go by the post-meta-goes-in-sidebar train of thought, then not only does the permalink belong there, but so does the title.

I think you could argue that it makes sense for the title and permalink to be treated special, and I would definitely agree for the former, though I do not feel as strongly about the latter. I do think there should be a more clear division between the title/permalink editor and the content block editor, though, simply to make it more clear that the title is not a block, and its position/styling in the editor does not reflect its position/styling in the front-end.

It is also important to keep in mind that some post types may not use a title block since they do not show their titles, so a title editor _somewhere_ outside of the block editing area is essential. The current title editor is outside of the block editing area, but when you are eventually able to edit the post/page templates, you should continue to be able to edit the title/permalink of a post/page/CPT without using a block.

**Comment by jaclyntan** [comment]
I think the visual cues and icons of gutenberg as whole could be vastly improved on before making it core, including permalinks.  **It's a pretty big sign a design needs to be rethought when multiple people have to google how to change something as simple as the slug.** 

I wouldn't be opposed to seeing the permalink block in the settings - however I still think the settings sidebar needs more visual hierarchy because sorting through the different blocks at a glances currently gets tiring.

**Comment by joriki** [comment]
I agree with the above; it's astonishing that something so basic is so hard to find.

The problem is aggravated by the fact that the banner at the top that appears when there's an unsaved draft hides the permalink popup, so if you don't already know that that's where it's supposed to be, you'll never find it as long as that banner is there.

**Comment by karmatosed** [comment]
Whilst I understand people wanting to make the permalinks more obvious, this issue isn't just about having it in the publishing flow. Maybe a possible way forward is to add here and explore other options in making it more visible.

**Comment by jaclyntan** [comment]
If the easiest thing is to keep the permalink where it is now, I suggest:

- remove position:fixed from .edit-post-layout .components-notice-list so it does not ever hide the permalink
- always display .editor-post-permalink even when the title is unfocused

So it will look like below:
![screen shot 2018-09-05 at 5 51 27 pm](https://user-images.githubusercontent.com/18632934/45086028-cff29f00-b134-11e8-8e02-c1d38131db3b.png)

If that is deemed too messy for Gutenberg's layout then I think putting it in the settings sidebar is the best option, perhaps even under the Status & Visibility block.

**Comment by TheTracyL** [comment]
FYI, I looked all over the place in the editor to change the page slug and couldn't find it until I Googled it and came here :-) 

I was mostly looking in the Document sidebar. I thought it would be under Page attributes. It didn't occur to me to click on the page title.  I like the solution posted above by @jaclyntan

**Comment by maxshelley** [comment]
> FYI, I looked all over the place in the editor to change the page slug and couldn't find it until I Googled it and came here :-)

Same FYI here. It genuinely didn't occur to me to click the page title to see (and certainly not to edit) the slug.

I wouldn't normally leave a comment and create noise on an issue, but the comment above...

> It's a pretty big sign a design needs to be rethought when multiple people have to google how to change something as simple as the slug.

...rang so true that I thought it was worth making a little extra noise in reconsidering the current choice.

(overall Gutenberg looks great though, huge respect for the work going on 💛)

**Comment by johnnyfraisse** [comment]
Same here, not really user friendly ;)

**Comment by altrovideo** [comment]
I'm a supporter of this <img src="https://user-images.githubusercontent.com/1204802/27325218-01141346-55a8-11e7-88ce-c37ff08e00b1.png">

The righ button "Change Permalinks" could be misunderstood as it seams to allow editing that article's Permalink

**Comment by mryand** [comment]
In addition to all the other good reasons suggested above by other folks:

1. The current treatment of the permalink is hidden by the Post Saved dialog. If the Post Saved dialog is visible, users who click in the post title will not see the permalink interface.
2. Verbose slugs that match the title is a sensible default for non-hierarchical URLs. But for pages and other CPTs with hierarchical URLs they can get absurd quickly. When I add pages and custom post types I modify the permalink (and counsel my clients to do so as well) on almost every new page to avoid absurdly long URLs. The current interface makes this workflow much less straightforward than it is in the classic editor.

**Comment by karmatosed** [comment]
For now let's close this as no direct route was agreed. We can look to iterate in the next phases if we need. We should also see what the publishing flow changes planned in #7602 bring up.
