### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by asathoor** [WordPress/gutenberg#8956]
**Create table - 1 sek - crash**
When I create a table I'll see a draft table. Then a Screen of Death: "Oops something went wrong"

**To Reproduce**
1. Go to 'Create table'

**Expected behavior**
I'd like to create a table

**Desktop (please complete the following information):**
 - OS: Linux on localhost, also tried on a server 
 - Browser Chrome

**Comment by asathoor** [comment]
Perhaps I should add that the theme is based on _S.

**Comment by designsimply** [comment]
> Go to 'Create table'

To clarify, does this mean you are adding a table block using the "Add block (+)" button in the top toolbar or are you doing something different to create a table?

I tested adding a table block using WordPress 4.9.8 and Gutenberg 3.5.0 and it worked in my test. I might not be doing the same steps as you so that is the first thing to check. Another thing you can do is try checking the browser console tab to see if any errors appear there at the time you try to create a table. Sometimes that can give helpful context about what might be going wrong on your side.

**Comment by hesambayat** [comment]
Same thing is happening to me when I try to add a table, no error appears in the dev-console.

Wordpress 4.9.8 and Gutenberg 3.6.2

![table](https://user-images.githubusercontent.com/3007713/44298482-eefbcf00-a2f4-11e8-8a6e-9b02c85b1fba.gif)

**Comment by asathoor** [comment]
@designsimply : your descriptions is similar to what I tried to do. @hesambayat seems to get the same issue.

**Comment by mcsf** [comment]
@asathoor & @hesambayat, thanks for the reports. Meanwhile, the Table block has been basically rewritten for Gutenberg 3.7. Could you test in 3.7 and let us know if you're still experiencing this error?

**Comment by hesambayat** [comment]
@mcsf thanks for the update, the table block is working beautifully. Tested on Gutenberg 3.7

**Comment by mcsf** [comment]
Great, thanks for checking! Closing issue.

**Comment by asathoor** [comment]
@mcsf thanx for your work on the table-issue.
