### ISSUE TITLE
Block audit: More

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#8974]
_Note: We'll be doing these audits in waves and editing this as we work through the blocks, so this text will be updated and fleshed out as we progress. [See the full picture here](https://github.com/WordPress/gutenberg/projects/19)._

# Overview

<img width="51" alt="screenshot 2018-08-14 14 51 41" src="https://user-images.githubusercontent.com/376315/44095783-948f56ac-9fd1-11e8-959f-1131a5ba3402.png">

**Name:** More
**Description:** Want to show only part of this post on your blog’s home page? Insert a "More" block where you want the split.
***Category:** Layout elements
**CSS class:** `wp-block-more` in editor, none in frontend (uses a `#span-xx` ID)
**Can be converted to:** nothing

# States

*Empty:*
<img width="443" alt="screenshot 2018-08-14 14 06 07" src="https://user-images.githubusercontent.com/376315/44095813-a3d3aa6e-9fd1-11e8-8f9b-dc8a2734b2d6.png">

*Selected:*
<img width="443" alt="screenshot 2018-08-14 14 06 07" src="https://user-images.githubusercontent.com/376315/44095813-a3d3aa6e-9fd1-11e8-8f9b-dc8a2734b2d6.png">

*Unselected:*
<img width="405" alt="screenshot 2018-08-14 14 52 50" src="https://user-images.githubusercontent.com/376315/44095884-ce9414a0-9fd1-11e8-939f-780d68c124ad.png">

*Placeholder:*
<img width="405" alt="screenshot 2018-08-14 14 52 50" src="https://user-images.githubusercontent.com/376315/44095884-ce9414a0-9fd1-11e8-939f-780d68c124ad.png">

# Primary (toolbar) settings

None

# Secondary (sidebar) settings

`Hide the teaser before the "More" tag` switch

# Frontend appearance

The more tag isn't visible in posts on the front end, so Gutenberg isn't providing any styling here.

# Bugs/errors

_Individual issues will be opened for these soon_

- [ ] 

# Suggestions

_Individual issues will be opened for these soon_

- [ ] The switch isn't contained within any sort of panel in the secondary settings sidebar, which is unlike all other blocks.

- [ ] Should this have a more descriptive name, perhaps?

- [ ] Is there a way to have this block better preview its content/frontend appearance?

- [ ] I don't fully understand what `Hide the teaser before the "More" tag` switch does. Does this mean that the blog index just shows a "read more" link, and nothing else?

- [ ] Placeholder styling doesn't make it immediately obvious that you can edit the text of the read more tag.

- [ ] Typing "read more" in the slash inserter should pull up the more tag.

**Comment by swissspidy** [comment]
Uhm... there used to be a dashed line on the left and right side of the "read more". See https://github.com/WordPress/gutenberg/pull/1440

I can still see it in the CSS, but it's not visible. Sounds like a bug to me.

Also, when initially inserting the block, the label "read more" is cut off a few pixels on either side:

<img width="691" alt="screenshot 2018-10-02 at 11 00 55" src="https://user-images.githubusercontent.com/841956/46339198-76e23200-c632-11e8-879d-6bdefb14c4de.png">

**Comment by afercia** [comment]
Was going to create a new issue and then thought to report here.

> Individual issues will be opened for these soon

Wasn't able to find specific issues, I guess they haven't been created yet 🙂 

I'd recommend to consider to clarify what a "teaser" is and what this setting does, as also mentioned in the 4th suggestion above.

As a user, I'm not supposed to know what a "teaser" is. "Teaser" is a technical term related to typography. Also, I'm not sure how it can be correctly translated. Assuming translators know what a teaser is, typographic terms greatly varies across different countries and cultures.

The setting also doesn't clarify what it actually does: the part of the content _before_ the more tag will be hidden in the single post view.

<img width="301" alt="screenshot 2018-11-03 at 10 35 03" src="https://user-images.githubusercontent.com/1682452/47950577-8667da00-df54-11e8-864e-d50fac85bf0b.png">

After a quick research for the term "teaser", turns out it is also known as "kicker, stand-first, or deck". Definitions I've found about "teaser" or "kicker":

- Short, underlined phrase introducing a headline. Also called teaser.
- A short phrase — set in a small point size — above a main heading. Also known as a kicker.
- A short line of copy set in a distinctive type above a headline and intended to call attention to it.

So, strictly speaking, it's something that comes _before the main headline_, while in WordPress this piece of content is used differently. Thus, seems "teaser" is not a correct term in the first place. However, this doesn't help so much. For most users, this is just a portion of _content_. I'd tend to think the simpler option is to just use the term "content" and clarify it applies to the _single post_ view.

Or

Now that the "More" description a few lines above refers to the "excerpt" (it previously said "part of this post"), maybe leverage the term "excerpt". Considering the two text combined together, seems to me it would help in clarifying. For example:

```
Want to show only an excerpt of this post on your home page?
Use this block to define where you want the separation.

Hide the excerpt on the post page
```

Aside: Ideally, the term "post" should be avoided because it could be any custom post type, but this is a different issue... 🙂

**Comment by melchoyce** [comment]
Related: https://github.com/WordPress/gutenberg/pull/6561

**Comment by afercia** [comment]
The help text is changed now, but still not so clear:

```
More
Mark the excerpt of this content.
Content before this block will be
shown in the excerpt on your
archives page.


Hide the teaser before the "More" tag
```

I'd like to suggest to change it into:

```
More
Content before this block will be
shown in the excerpt on your
archives page.


Hide the excerpt on the post page
```

**Comment by karmatosed** [comment]
I have created an issue for #14103. Some other improvements have been made since the audit. For now, closing this, but if I missed anything I can create new ones please let me know.
