### ISSUE TITLE
Notify child blocks

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#8991]
Is there a mechanism in Gutenberg for notifying child blocks?
For example: A slider block should inform the child blocks of its slides when they are shown to user.
This can be used by the child block to e.g. run a fade-in.
Are there react- or gutenberg-specific notifications like `onVisible` or `onShow` for this?

**Comment by strarsis** [comment]
@earnjam: Are there any mechanisms planned for this in Gutenberg blocks?
This would be frontend-notifications of child Gutenblocks.
For interactivity and animations this can be extremely useful, even required.

**Comment by designsimply** [comment]
@strarsis I am not sure of the answer here, but since you posted your question some time ago, I was wondering if you were able to find a solution to your question in the mean time or if you still need help?

I did try searching for "inner blocks", which is the term I've seen most often used for what you're calling child blocks, at https://wordpress.org/gutenberg/?s=inner+blocks but didn't find anything that jumped out as a specific solution to what you are asking. The first result there though is a section about [creating dynamic blocks](https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/block-tutorial/creating-dynamic-blocks/), and I was wondering if that section has anything in it that is helpful to you?

**Comment by designsimply** [comment]
Thank you for clarifying a bit. I asked about this and found that Gutenberg doesn’t offer anything around inner blocks visibility, they’re just there. If you wanted to hide/reveal child blocks in a way like a slider, you would need to implement that as part of the code you write for the slider function you're wanting to create. 

If you need help with JavaScript itself, which it sounds like to me based on your description so far, I suggest posting to https://softwareengineering.stackexchange.com/questions/tagged/javascript or https://wordpress.stackexchange.com/ and including a code example for what you have tried already or something you come up with as a quick example (even if it's pseudo code). 

You might also try checking to see what similar block-enabled plugins at https://wordpress.org/plugins/browse/blocks/ are doing if you can find one with a similar functionality.

Thanks for asking your questions and good luck with your coding!
