### ISSUE TITLE
Code editor removes newline between text and closing </div> tag when saving or preview - related to Wistia video embed issue

### ISSUE THREAD

**Issue by De-Occultist** [WordPress/gutenberg#9002]
**Describe the bug**
Using Gutenberg Version 3.5.0
I am trying embed Wistia videos on my site and the URL is http://fantastic.wistia.com/medias/60cf0ufhoo?embedType=async&videoFoam=true&videoWidth=640 . 
In the classic editor, the visual editor would convert the & symbol to &amp; which will cause the video not to display correctly on the page. I would have to fix it in the code editor to change it to the actual & symbol and save it.

In the Gutenberg editor, both the visual and code editor will convert the & symbol to &amp; . This means I have no way to get around this unless I go back to the classic editor.

**To Reproduce**
1. Create a new page, change to code editor
2. Add the URL http://fantastic.wistia.com/medias/60cf0ufhoo?embedType=async&videoFoam=true&videoWidth=640 to the page
3. Click preview
4. It will automatically change to http://fantastic.wistia.com/medias/60cf0ufhoo?embedType=async&amp;videoFoam=true&amp;videoWidth=640
5. When saved this video will not embed or load on the page only the URL will show up.

**Expected behavior**
The ideal behavior for the gutenberg editor would be to be able to add the URL or text with & symobol so that it will not automatically change to &amp; in both the visual or code editor. 
But at least have the same behaviour as the classic code editor so that text with & symbol can stay as it is without automatically converted to &amp;

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser: Firefox
 - Version: 61.0.2

**Comment by designsimply** [comment]
I tested with the classic editor using WordPress 4.98 and compared it to the same test with WordPress 4.9.8 and Gutenberg 3.5.0 and the URL encoding looks the same to me. ([1m18s](https://cloudup.com/cYwNZ3y2qOa))

I checked https://codex.wordpress.org/Embeds and I don't see Wistia listed there. Are you using a plugin to facilitate embeds or when you embed are you using some `script` code?

I also noticed that if I visit http://fantastic.wistia.com/medias/60cf0ufhoo?embedType=async&videoFoam=true&videoWidth=640 directly it returns an error, "The requested item cannot be found." I am not sure if that's because I don't have permissions to view that video or if it is just a non-working sample URL. Do you have a publicly accessible sample URL we can use for testing by chance?

**Comment by De-Occultist** [comment]
Thanks for looking into this.
I use the [Wistia Wodpress Oembed Plugin](https://en-au.wordpress.org/plugins/wistia-wordpress-oembed-plugin/).

I had a closer look and found the embed issue is not related to the ampersand and actually related to the <div> being changed upon saving in visual and code mode.


For example 

1) In gutenberg "Code" mode, add this to a new page:

```
<div id="text" class="col-sm-8">
https://home.wistia.com/medias/e4a27b971d?embedType=async&amp;videoFoam=true&amp;videoWidth=640
</div>
```

2) Click preview or save it will turn into this and the embedded video does not show.
```
<div id="text" class="col-sm-8">
https://home.wistia.com/medias/e4a27b971d?embedType=async&amp;videoFoam=true&amp;videoWidth=640</div>
```
3) In the Classic "Code" editor:
Add this to a page
```
<div id="text" class="col-sm-8">
https://home.wistia.com/medias/e4a27b971d?embedType=async&amp;videoFoam=true&amp;videoWidth=640
</div>
```
Save or preview, the </div> will remain where it is on a new line. 
The embedded video will show.

This shows the different behaviour for the </div> tag in the classic code and gutenberg code editor.

The workaround is to add an extra new line between the tags and the URL.
```
<div id="text" class="col-sm-8">

https://home.wistia.com/medias/e4a27b971d?embedType=async&amp;videoFoam=true&amp;videoWidth=640

</div>
```

**Comment by tofumatt** [comment]
I checked the plugin page for that plugin and it seems like it hasn't been tested with recent versions of WordPress–the support forums are pretty quiet as well.

This seems like there is an issue with the way the Wistia plugin is checking for HTML–the HTML we are outputting is valid and *technically* the same in terms of parsing, so it could be their plugin isn't parsing HTML properly.

I don't see this as an issue with Gutenberg because we're still outputting HTML that should be parsed the same as what was pasted.
