### ISSUE TITLE
URL Embed not displaying as expected on Front End

### ISSUE THREAD

**Issue by Janna-Pieler** [WordPress/gutenberg#9025]
**Describe the bug**
When pasting an external url into the embed block, it appears as a hyperlink inside the editor, but only as unlinked text on the front end.

**To Reproduce**
1. Paste an external url into the classic Embed block
2. Publish
3. View on Front End

**Expected behavior**
To see the same thing previewed in the editor on the front end. The front end should display the full url with hyperlink like the editor displays.

**Screenshots**

As seen in editor:
<img width="816" alt="editor-externalurl-embedscreen shot 2018-08-15 at 9 35 55 am" src="https://user-images.githubusercontent.com/38333734/44154216-d391de44-a06f-11e8-9f02-f0619915bbd2.png">

As seen on front end:
<img width="776" alt="front-end-externalurl-embed-screen shot 2018-08-15 at 9 35 47 am" src="https://user-images.githubusercontent.com/38333734/44154217-d3a98940-a06f-11e8-9176-43d2878677e9.png">

Above example is shown with the embed feature used on top twice and a standard text hyperlink inside a paragraph block working as expected below.

**Desktop (please complete the following information):**
 - OS: OS X 10.13.6
 - Browser Chrome 86
 - Gutenburg Version 3.5.0

**Comment by designsimply** [comment]
Hi @Janna-Pieler. Thanks for posting! I tried testing with both an embed block in Gutenberg as well as pasting https://wordpress.com/ into a classic editor block and my results are a little different compared to yours. In my test, I wasn't able to use https://wordpress.com/ in an embed block because it's not a [supported embed](https://codex.wordpress.org/Embeds) and pasting https://wordpress.com/ into the classic block just inserted it as plain text. I'm sure I'm missing something in the testing steps! Could you have a look and let me know what's different in my testing compared to yours? ([35s](https://cloudup.com/ck36xLo0qg1))

**Comment by Janna-Pieler** [comment]
Hi @designsimply, sorry for my delay in getting back. When I tried to embed https://wordpress.com/ I did get an error message saying that it was unsupported, however, the issue was that it still displayed a hyperlink for me afterward in the editor, while the front end only appeared as plain text. I understand this isn't a supported embed, but it seems like it should still appear consistent editor to front end by either showing as a hyperlink in the front end, or with the editor only showing the plain text. Does that make sense? What do you think?

**Comment by youknowriad** [comment]
There has been some improvements for this kind of issues and right now we show a "convert to link" button for links that are not embeddable which should make them appear similarly in frontend/backend.
