### ISSUE TITLE
No chance to change the template of a page

### ISSUE THREAD

**Issue by hornisch** [WordPress/gutenberg#9026]
Hi all,
we have a template with acf pro includet. So most of our pages are build on a page template called page-builder. Within gutenberg we are not able to change this template to standard. Everytime we publish the changes, the editor displays an error message: Updating failed

**To Reproduce**
1. Go to page
2. Click on Document / Page Attributes / Template
3. Change the template (in our case an ACF based template) to a different template and press Publish
4. See error: Updating failed

**Desktop):**
 - OS: Win10
 - Browser Chrome

**Additional context**
ACF pro theme ACF latest version
Wordpress and Gutenberg latest version

**Comment by designsimply** [comment]
Thanks for reporting this! I tested with one of the default themes and without the ACF plugin installed to see if changing page templates works normally for Gutenberg and it worked properly in my test. ([30s](https://cloudup.com/cLaH76rE3Oc))

While it's good to report plugin conflicts here, would you also mind reporting this to the ACF plugin developers at https://support.advancedcustomfields.com/topics/ so that they are aware of the problem? If you are able to check the web developer tools console for errors in your browser at the time you try to change the page template and see the "Updating failed" message, it would be helpful to include that error in your help request.

**Comment by hornisch** [comment]
Ok - we found the cause of the problem :)
A membership module (we used CSSJockey Membership Modules - which apparently is no longer updated) caused the problem. 
We switched to AAM and now it is possible to change the page template in gutenberg and in standard editor again.

Best regards
