### ISSUE TITLE
Parent Selector on Page Doesn't Show All Pages

### ISSUE THREAD

**Issue by weslinda** [WordPress/gutenberg#9034]
**The Bug**

When testing Gutenberg, I came across an issue related to the parent selection on a page. When Gutenberg is enabled, there are only 10 pages available to select from. No option to scroll for additional pages is in place. 

When I disable Gutenberg, then all pages are selectable.

**How To Reproduce**
1. Go to edit a page
2. Click on page attributes
3. Click to select a parent

I have tested this on multiple sites with plugins active and with all plugins deactivated.

**Comment by chrisvanpatten** [comment]
Hi @weslinda, thanks for the report!

This is a known bug that will be fixed in Gutenberg 3.6, which is tentatively scheduled to be released tomorrow.

I'm going to close this up as it's a resolved bug, but if you have any questions don't hesitate to reply and we can always reopen it!

(PR: #8908; Dupe: #8848 #9004)

**Comment by Janatomy** [comment]
My parent categories are still not displaying when I am building a page using Gutenberg. When I switch to the Classic Editor, the categories are all there. 

Has this issue been resolved yet?
