### ISSUE TITLE
A post can no longer be edited with Gutenberg after block generating

### ISSUE THREAD

**Issue by SchneiderSam** [WordPress/gutenberg#9038]
**Describe the bug**
After I converted a quite simple post to Elementor in Gutenberg (Version 3.5.0), the post can no longer be opened at all: http://recordit.co/PiRkITF0PB

It's loading, but I'm getting nowhere.

**To Reproduce**
1. Go to 'Page' http://prntscr.com/kj0v8x
2. Click on 'Edit' http://prntscr.com/kj0vfi
3. Wait '....'
4. See error: nothing happens

**Expected behavior**
That I can continue to work on the content (only p- and h3-Tags, no images) with Gutenberg.

**Screenshots**
http://prntscr.com/kj0w62

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome 68 also tested with Firefox
 - Version 68

**Comment by designsimply** [comment]
Thanks for reporting this! While it's good to report plugin conflicts here, would you also mind reporting this to the Elementor developers at https://my.elementor.com/contact/ so that they are aware of the problem? If you are able to test turning off all other plugins to rule out a conflict with something else, that would be helpful to include in your help request. It may also be helpful to include any errors you see in your browser developer tools console and network tab at the time you see the blank post.

**Comment by SchneiderSam** [comment]
Ok done

**Comment by SchneiderSam** [comment]
Can be closed. It's done!
