### ISSUE TITLE
Add a button for no alignment

### ISSUE THREAD

**Issue by DannyCooper** [WordPress/gutenberg#9046]
There are buttons in <BlockAlignmentToolbar /> for full, wide, left, right, center. It would be useful to have a button to return to "no alignment"

For example in a block like this, where the developer has set 'wide' as the default. It's not obvious that clicking wide again will return to no alignment.

![image](https://user-images.githubusercontent.com/152804/44201455-275aac00-a141-11e8-8340-b8cf0a691ea3.png)

The setting wouldn't return to 'default' as in the example above the default is 'wide'. Ideally it would clear the align attribute so it's undefined.

**Comment by tofumatt** [comment]
Are there any blocks that have a default alignment set in the set of core blocks? I'm not sure we have documentation around default alignment, but my first instinct is that blocks shouldn't have them set by default, so the empty state is obvious and user interaction to set an alignment sets the expectation that you can unset it by clicking the set alignment (it still appears as a button so that's pretty clear).

I don't think adding a "remove alignment" button to the toolbar is worth it, unless there are blocks that, by default, ship with alignment and other users find the highlighted button to remove the alignment unclear.

I think this is a won't fix because it's not a common issue nor worth the toolbar space. I understand the concern but I think the current implementation works well enough.

**Comment by tofumatt** [comment]
To be clear: if there are default blocks that have default alignment set, I think this is worth at least discussing further… but if that's the case I'd argue for just removing default alignment and saying in the docs for writing blocks that default alignments shouldn't be set.

**Comment by DannyCooper** [comment]
That makes sense, thanks for explaining it Matt. I checked and you are right, even the cover block isn't alignfull by default.
