### ISSUE TITLE
Remove the two click publish requirement

### ISSUE THREAD

**Issue by danieltj27** [WordPress/gutenberg#9077]
This is more of a feature request as nothing is technically broken here, but the workflow to publish a post seems like a poor user experience. Currently, the workflow is to finish writing and building your post out and then click the blue publish button right in the top right.

Once clicked a panel slides out and asks you if you're sure you want to publish the post. Compare that to the TinyMCE experience where you click publish once (which is sort of inline with the content) and then you've publish the post.

My expectations here would be to remove this additional panel and have that button submit the changes there and then. This would also reduce the UI making it less complicated.

**Comment by danieltj27** [comment]
I would close this issue, although I feel very strongly that the points raised in the above issues miss the core issue here which is requiring an additional click to publish something doesn't aid/prevent anything in a particularly meaningful way. It just adds extra clutter to an already difficult UI.

**Comment by 0aveRyan** [comment]
Two-step publishing seems a fine idea, even as a default, so long as there's an easy-opt out and any functionality in the additional step can be completed elsewhere.

**Comment by danieltj27** [comment]
>  so long as there's an easy-opt out and any functionality in the additional step can be completed elsewhere

Having an additional step is not a good idea; you could even consider it a dark pattern. Additionally, providing options goes against WordPress' philosophy on '[_Decisions, not Options_](https://wordpress.org/about/philosophy/#decisions)'.

**Comment by earnjam** [comment]
I'm not against it per se, but just trying to think about it in the broader sense of what seems to me like the most common feedback since the Try Gutenberg callout—that its requirement of so many clicks gets in the way of writing/publishing and slows things down. 

I haven't looked into it enough to see, but if it's possible to disable/skip the extra step via a plugin, then it's probably fine. It would be kind of the opposite of the old editor, where it was possible to add an "are you sure" step via plugin, but it was not the default. 

Decisions like these where there isn't a "right answer" are impossible to make and have everyone be happy, but it's a much easier sell as long as the hooks are there to allow people to change the default functionality.

**Comment by youknowriad** [comment]
Opinions diverge a lot on this and a consensus seems impossible, it seems that a lot are leaning towards the publish in two clicks especially because it adds more space for Plugins interacting with the publishing phase (pre/post publish panels are extensible).

I'm going to closes as the decision seems final.

**Comment by earnjam** [comment]
@youknowriad I haven't looked into it yet, so pardon if this is obvious, but is there a way to intercept the click event on the initial publish button and bypass the pre-publish panel? 

If not, extending it to support that seems like a workable solution here that could satisfy diverging opinions.

**Comment by 0aveRyan** [comment]
+1 to @earnjam's point -- consensus isn't needed so long as there's an applyFilter to handle the click event.

**Comment by youknowriad** [comment]
Yes, it should be possible to monitor the `isPublishSidebarOpened` using the data module and programmatically trigger a save directly https://wordpress.org/gutenberg/handbook/data/data-core-edit-post/#ispublishsidebaropened

**Comment by earnjam** [comment]
Thanks! I'll look into that.

**Comment by Qoraiche** [comment]
> Yes, it should be possible to monitor the `isPublishSidebarOpened` using the data module and programmatically trigger a save directly https://wordpress.org/gutenberg/handbook/data/data-core-edit-post/#ispublishsidebaropened

You can use this `window.wp.data.dispatch('core/editor').disablePublishSidebar();`
