### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by KenBiron** [WordPress/gutenberg#9101]
**Describe the bug**
Blank screen upon edit and create post

**To Reproduce**
1. Go to 'edit existing post, create new post'
2. blank screen happens

**Expected behavior**
Was testing to create a new post with this plugin activated.  Open the "edit" and the "Create New" commands opened with a blank field where I am supposed to type information to the post.    Noticed this problem first time when it was newer, reported it.  Was told would be fixed upon update when reported.  2 updates later, same problem.  Could it be a conflict with my plugins already installed?  List below:

Accelerated Mobile Pages Version 0.9.97.9 
AddToAny Share Buttons Version 1.7.28
Akismet Anti-Spam Version 4.0.8 
All In One SEO Pack Version 2.7.3
Bluehost Affiliator Version 1.0.7
Broken Link Checker Version 1.11.5
Google Analytics Dashboard for WP (GADWP) Version 5.3.5
Google XML Sitemap Generator Version 1.3.4
Gutenberg Version 3.6.2
Insert Headers and Footers Version 1.4.3
Jetpack by WordPress.com Version 6.4.2
MailChimp for WordPress Version 1.1.1 
Press This Version 1.1.1
UpdraftPlus - Backup/Restore Version 1.14.13 
WordPress Editorial Calendar Version 3.6.8
WP Cerber Security, Antispam & Malware Scan Version 7.2 
WP RSS Aggregator Version 4.11.3
WP Translate Version 5.0.2
WP Word Count Version 3.0.0
WP-Optimize Version 2.2.4 
Yoast SEO Version 8.0 

**Screenshots**
![blank-screen-wp-gutenberg](https://user-images.githubusercontent.com/26168680/44282206-2728e200-a20f-11e8-985f-61b7970054a1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 68.0.3440.106 (Official Build) (64-bit)
**Additional context**
- Gutenberg V 3.6.2

**Comment by designsimply** [comment]
Thanks for posting and listing out your active plugins! A blank screen happen for several reasons. 

Do you see any errors in the JavaScript console of your browser at the time the problem happens?

Plugins which block access to the API could be the source of a conflict—would it be possible for you to try deactivating WP Cerber Security temporarily as a test?

**Comment by KenBiron** [comment]
No errors in Javascript come up.  I'll try deactivating that plugin temporarily and testing to see if that's the problem.  Ok now I have the edit screen running without that plugin.  Hmmmm, I need that plugin activated.  Do i need security, yes.  Do I need Gutenberg?  I will apparently.  What now?

**Comment by youknowriad** [comment]
In general these plugins are too aggressive by default and they block the REST API, not because the REST API is not secure but just because it's not really used in WordPress. But the thing is the REST API is being used in Gutenberg and it's being used in a lot of plugins too. So I'd recommend checking the options of the security plugin you have and disabling the "Disable REST API" setting.

**Comment by youknowriad** [comment]
Closing as there's nothing more we can do about it. Thanks

**Comment by KenBiron** [comment]
Yes, disabling the "REST API" did the trick, however I've yet to see how that will affect my security so perhaps that could be looked at to see why it's conflicting.  I'm not comfortable disabling a feature of my security but if I have to use this plugin, then that must be disabled.

**Comment by youknowriad** [comment]
Again, the REST API is a WordPress feature and shouldn't be disabled because of "security" concerns. If there's a security issue raised about the REST API, it would be fixed ASAP in WordPress itself like any other code of WordPress.

If WordPress introduces a new feature, like a new settings page, or a code editor, or something in the customizer, the security plugins won't disable it because it useful. The issue with the REST API is that these security plugins consider it "useless" because it wasn't used when it was first released in WordPress, so they disable it "per precaution" not because it's unsecure. With Gutenberg (and probably other WordPress features that will come in the future), this feature is at the center of how these features work and Gutenberg can't work without it, the same way future UI in WordPress won't work without it. So plugins shouldn't disable it anymore.

**Comment by KenBiron** [comment]
Thanks for all this, slowly writing a post to try this.  Looks good to use so far!

**Comment by Ofenbekenntnisse** [comment]
I do have the same issue. The problem occured after I had installed the version 3.6.2. I don't know where I can disable REST API.  And I don't think it is the best way of dealing with it. I mean, before the update it worked perfectly.  Ain't there another solution?

**Comment by gmstam** [comment]
I have the same problem after upgrading to 3.6.2. I disabled REST API with the plugin Disable REST API with no success.

**Comment by designsimply** [comment]
@Ofenbekenntnisse your case may be different. Do you have any security plugins installed? Can you try clearing browser cache as a troubleshooting step to see if that makes the problem go away? If you're still having trouble after that, are you able to check your the web console in your browser developer tools at the time the blank screen happens and check for errors there? Please open a new issue if you find any! I would love to see if I can help you sort out the problem!

@gmstam it sounds like you are using the WP Cerber Security plugin in your case, is that correct? If yes, does the problem go away if you temporarily disable that plugin completely?

**Comment by gmstam** [comment]
@designsimply Problem solved after I cleared all caches
