### ISSUE TITLE
Usability is kinda...odd

### ISSUE THREAD

**Issue by NinjaDoll** [WordPress/gutenberg#9145]
I'd like to comment simply from a user standpoint in case you'd like feedback in that regard. I work primarily on a desktop for corporate posts/pages, so lots of words and graphics, and I have a decent working knowledge of Wordpress functions, CSS, HTML, but I'm not a coder, I'm a writer. So, FWIW:

1. My writing scrolls up the screen in a narrow, centered ribbon of text, which makes composition a little taxing. It's no longer a true writing space. I'll miss the ability to fill an edit box nearly the full width of my screen (which matches my posts/pages look/feel), so I can deal with content and aesthetic relative to the whole document, the way it'll look when published. I have a lot of wasted white space on my desktop screen. Perhaps the editor width could scale?
2. On the document bar, there are drop-down menus that should only ever have one thing in them. Setting a featured image has no other options but now adds yet one more click to my writing time. At least for me, I'm looking for efficiency for my creative input, not fancy parallax options menus that plugins can exploit to give me even more clicks. Sometimes, you _can_ have too much of a good thing.
3. The style bar offers no new features; it's always been one of the weaker aspects of writing, so I'd hoped a major retool would include at least some of the better-used function of some plugins (text colors, tables,'sup','sub', hyperlinks, paragraph indents, line-spacing, font-face selector or at least some honest font pixel-sizing). Otherwise, I'd need to stay in code mode forever and simply HTML my way through my writing, it's faster. Please add a more robust style bar.

Thanks for reading.

**Comment by designsimply** [comment]
Thank you for the feedback!

> I have a lot of wasted white space on my desktop screen. Perhaps the editor width could scale?

Currently, the editor width can be modified by the theme and, at this time, I would recommend asking your theme author if they would be willing to make an adjustment to that if it makes sense for the theme you are using. See https://github.com/WordPress/gutenberg/issues/8643#issuecomment-410973542

> Setting a featured image has no other options but now adds yet one more click to my writing time. 

Is the problem you are trying to solve in this case that the featured image panel is is not already open by default in document settings or is the problem that the block settings make it so you have to do an extra click to get to the document settings? 

> Please add a more robust style bar.

The first iteration of the new editor restructures the underlying code in a way that will make WordPress more extensible for a variety of different use cases in the future—the current, foremost goal is to include functions based on what was previously offered combined with the design team's experiences with past work, user testing, and usability feedback from a variety of people and sources. Because of that, using a plugin to add functionality to the toolbars that isn't there by default is currently the best route. Some of the options you've recommended may be considered and added in the future, however, it is not a current focus and which items are worth including can sometimes fall to quite a bit of debate and that makes it so adding new defaults can become a long process.
