### ISSUE TITLE
Block Extension Documentation misses ESNext implementation

### ISSUE THREAD

**Issue by p2er** [WordPress/gutenberg#9158]
I've noticed that your block extension documentation (https://wordpress.org/gutenberg/handbook/extensibility/extending-blocks/) does not line up with the rest of the documentation providing ES5 demos as well as ESNext demos. This isn't very helpful if all other blocks for a project are written in ESNext syntax. 

It would make a lot of sense to have at least one operational example with slightly more complex logic. For instance extending the core image block to add a copyright layer on top. That would require to elaborate on filters to enhance the editor view and also render alternative markup.

**Comment by tofumatt** [comment]
There are seemingly two issues contained within the writeup here–one is about ES6 examples and one is a request for a more complex example.

For that file, I don't think adding an ES6 example would be worthwhile in the current form–the only thing that would change, from looking at the code, is the use of `const` and `let` over `var`. The examples otherwise wouldn't really change. So I don't think that's worth doing… though I suppose if a PR came through I wouldn't reject it 😆

Regarding a more complex example–do you have something in mind with an explicit example? I think it might be best to submit a pull request with the kind of example you'd like to see there.

I'm going to close this because the title mentioned ES6 examples which I don't think are worth tracking in an issue for that file, but if you wanted to make a PR with ES6 examples or more complex ones that'd be cool! 😄
