### ISSUE TITLE
Improve dirty detection

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#916]
__Updated:__ While the original issue below has since been resolved, we should investigate cases where changes may be unintentionally reflected in a new post. For #1059, I suspect it was because the list block was setting attributes immediately upon becoming mounted, causing the editor to consider itself dirty. We should look to make dirty detection more durable.

---

Original issue:

__Steps to reproduce:__

1. Visit Gutenberg page

__Expected result:__ There are no changes indicated.

__Actual result:__

![New post with changes](https://cloud.githubusercontent.com/assets/1779930/26509209/d07dbaba-4225-11e7-841d-ba85b8a7ba18.png)

**Comment by nylen** [comment]
It's a bit disheartening to see this happening already, even though we are taking a very simple approach to dirty detection.  Some related discussion on other issues/PRs:

- https://github.com/WordPress/gutenberg/pull/610#issuecomment-299193241
- https://github.com/WordPress/gutenberg/pull/848#issuecomment-303259849

Also, I'm not really sure how to debug this, due to the extremely annoying https://github.com/WordPress/gutenberg/issues/919.

**Comment by aduth** [comment]
The original steps are now resolved as of #1059, but I'm going to keep this open and rename the issue, as I'd like to consider how we might make dirty detection more durable.
