### ISSUE TITLE
Noto Serif, the default font in the Gutenberg Editor, lacks a proper apostrophe

### ISSUE THREAD

**Issue by field2** [WordPress/gutenberg#9181]
**Is your feature request related to a problem? Please describe.**
When typing an apostrophe in the editor, the single-quote key should display a proper, curly apostrophe character. Apparently, Noto Serif lacks such a character.

**Describe the solution you'd like**
Change the default font used in the Gutenberg Editor to something with a curly apostrophe

**Describe alternatives you've considered**
Ignoring the straight quote is impossible for me, but I admit I'm a type snob.

**Comment by chrisvanpatten** [comment]
Hi there Ben! 👋 

I see curly quote support in Noto Serif:

![edit_post_ _chris_van_patten_ _wordpress](https://user-images.githubusercontent.com/1231306/44370758-9588d100-a4a9-11e8-80b3-3786c8dcf275.png)

However, I had to explicitly copy and paste the curly quote characters (from the always helpful http://rsquo.net) to get them to display.

This is because Gutenberg doesn't convert apostrophes to curly quotes. However, to be fair, the Classic Editor doesn't either.

However, when your post is rendered, the quotes will be converted to curly quotes automatically by the `wptexturize` [function](https://developer.wordpress.org/reference/functions/wptexturize/) on the front-end (but not the backend, admittedly).

Let me know if this explanation helps!

**Comment by field2** [comment]
Hey Chris, yes it does. I'm so used to proper formatting of quotes in native apps, like Illustrator or Word, that it's weird they don't behave that way in the browser. I wonder why that is? Oh well, carry on!
