### ISSUE TITLE
This block has been modified externally

### ISSUE THREAD

**Issue by abhishekpc** [WordPress/gutenberg#9185]
**Describe the bug**
I have created several articles with Gutenberg. When I went to edit already published articles, suddenly, the posts created with Gutenberg started showing "This block has been modified externally". 
It gives two options: Convert to Block and Keep it as HTML. **(see screenshot 1)**
Irrespective of which option I choose, the said block disappears from the preview of the article and I believe it just gets deleted from the article even though I can see it in Gutenberg editor. 

For example, I tried editing an article and chose to keep it as block and keep it as HTML for first two blocks **(See Screenshot 2)**. But when I preview it, these two block disapeear **(see screenshot 3)**.

**To Reproduce**
Wild guess... try to disable Gutenberg and reenable it and then edit Gutenberg posts.

**Expected behavior**
I would expect the editor to behave normally and recognize the blocks as it is.

**Screenshots**
Secreenshot 1:
![screenshot from 2018-08-21 11-37-48](https://user-images.githubusercontent.com/3172915/44383795-a2ec9c80-a537-11e8-9541-260776d0cc8d.png)
Screenshot2: 
![screenshot from 2018-08-21 11-48-18](https://user-images.githubusercontent.com/3172915/44384069-7d13c780-a538-11e8-93bd-4bd56dea7f65.png)
Screenshot 3:
![screenshot from 2018-08-21 11-46-12](https://user-images.githubusercontent.com/3172915/44384078-856c0280-a538-11e8-86a4-774f166b0199.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser Google Chrome and Firefox
 - Version Latest

**Additional context**
I think I had disabled Guteberg to investigate a plugin conflict a few days back. Don't know if that made a difference.

**Comment by designsimply** [comment]
> But when I preview it, these two block disappear (see screenshot 3).

To clarify, the problem is that all blocks you have previously added with Gutenberg now show a "This block has been modified externally" notice and selecting either "Convert to Blocks" or "Keep as HTML" result in those blocks not showing up in previews? Note for testing: try to find out whether the blocks missing from previews reappear for the published post after an update (vs just being gone in previews only).

I will try to reproduce this in testing. May I ask for some extra information before that?

I noticed the HTML for the 2nd block in your example is a heading which has a very simple HTML:

`<h2>10 Interesting facts about Debian Linux</h2>`

If you re-open that post and see the "This block has been modified externally" notice, can you go to the more menu in the top toolbar next to the gear icon and open the Code Editor and let me know if the HTML looks different in any way compared to the simple HTML shown in your first screenshot?

> I think I had disabled Gutenberg to investigate a plugin conflict a few days back. Don't know if that made a difference.

Did you find a conflict? If yes, may I ask which plugin had the conflict?

Do you know if any of your plugins make modifications to existing content? Can you post a list of your plugins for reference? (I'm not sure if it will be helpful, but it seems like a good thing to document for this case.)

**Comment by designsimply** [comment]
> To Reproduce
> Wild guess... try to disable Gutenberg and reenable it and then edit Gutenberg posts.

I tried the following:

1. Create and publish a post using Gutenberg.
1. Deactivate Gutenberg.
1. Activate Gutenberg.
1. Try editing the post from step one.

<strong>Result:</strong> all blocks worked normally without any errors showing.

I also tried:

1. Create and publish a post using Gutenberg.
1. Deactivate Gutenberg.
1. Edit the post from step one and save any change to the content
1. Activate Gutenberg.
1. Try editing the post from step one.

<strong>Result:</strong> the blocks were consolidated into a classic block and I did not see any errors for the content.

<sup>Tested with WordPress 4.9.8 and Gutenberg 3.8.0 using Firefox 62.0 on macOS 10.13.6.</sup>

I am not sure what else to test. If this problem is still happening for you after updating to the latest version of Gutenberg, please reply here if you have any additional ideas for testing.

Thank you for testing Gutenberg and for reporting what you have found!
