### ISSUE TITLE
Avoid user / system files in generated zip

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#921]
Notably Mac writes `.DS_Store` files to opened folders. With our current plugin build script, these would be included in archived build folders:

https://github.com/WordPress/gutenberg/blob/master/bin/build-plugin-zip.sh

May be simple enough to add an `-x "*.DS_Store` argument to the `zip` command:

https://superuser.com/a/198593

Or we could try to be fancier in accounting for more ignored files / extensions.

**Comment by nylen** [comment]
I wonder if we could use `.gitignore` for this.

**Comment by aduth** [comment]
I thought about that too. Couple problems:

- `.DS_Store` is part of the global gitignore, not our project's
- Some gitignore we want in zip, like `build`

**Comment by nylen** [comment]
Ok then, probably we should just list out the included files more specifically, whether explicitly (one file per line) or using glob patterns like `blocks/build/*.{js,css,map}` (note, this requires switching the script from `#!/bin/sh` to `#!/bin/bash`).

Also I just noticed that this script uses spaces instead of tabs for indentation, we might as well fix that at the same time.

**Comment by jasmussen** [comment]
See also #952.
