### ISSUE TITLE
Youtube/Vimeo Video insert isn´t responsive

### ISSUE THREAD

**Issue by Richard-Notblank** [WordPress/gutenberg#9211]
**Describe the bug**
Youtube/Vimeo Video insert isn´t responsive

**Expected behavior**
Be responsive on Smartpnones and Computers

**Screenshots**
![screen-video-insert-non-responsive](https://user-images.githubusercontent.com/42587298/44424080-49f92480-a588-11e8-95a7-8965867740d1.jpg)

**Desktop (please complete the following information):**
 - OS: Win 7 & Android
 - Browser: Chrome
 

**Smartphone (please complete the following information):**
 - Device: BQ Aquaris
 - OS: Android 7.1.2
 - Browser Chrome
 -
**Additional context**
- Please add the version of Gutenberg you are using in the description: Versión 3.6.2
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by designsimply** [comment]
I tested using a Pixel on Android 8.1.0 and with the "Toggle device toolbar" option set to "Galaxy S5" in Chrome 68.0.3440.106 on macOS 10.13.6 and the videos were displayed as responsive in both of my tests.

<img src="https://user-images.githubusercontent.com/1119271/44435067-7d798600-a56b-11e8-8481-72700541183a.png" width="270">

![screen shot 2018-08-21 at tue aug 21 5 51 18 pm](https://user-images.githubusercontent.com/1119271/44435074-8407fd80-a56b-11e8-962a-a0fde1f04a63.png)

Since problem you described didn't happen when I tested, I wonder if the theme is the source of the trouble in this case. I tested with the Twenty Seventeen theme active. Are you able to temporarily switch to another theme such as Twenty Seventeen to see if the problem goes away in your case?

**Comment by designsimply** [comment]
Closing because I was unable to replicate in testing and because further work has been done since the time of this report including #8399, #9500, #10477.

If you're still having trouble, please re-open and please mention what WordPress and Gutenberg version you are using and what theme you are testing with. Thank you!
