### ISSUE TITLE
Insert Link: Open in a New Window sometimes does not apply too links in Paragraph block

### ISSUE THREAD

**Issue by ianbelanger79** [WordPress/gutenberg#9215]
When adding a link inside a paragraph block, occasionally "Open in a New Window" does not apply to links.

1. Add Paragraph Block with text.
2. Double-click or highlight any word and click add link button.
3. Add link and click apply button.
4. Click 3 dot button to open drop-down and apply Open in New Window to link.
5. Switch to edit HTML and check to see if target="_blank" has been added. It doesn't always get added.

**Expected behavior**
When I click on Open in New Window for any link it should always add target="_blank".

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 68.0.3440.106

**Additional context**
- Gutenberg 3.6.2
- WP 5.0-alpha-20180817.111643
- I also see that rel="noopener" has been added to some of the links in which I added target="_blank" with no conceivable pattern.

**Comment by ianbelanger79** [comment]
Possibly Related? #8696

**Comment by jorgefilipecosta** [comment]
Hi @ianbelanger79, thank you for reporting this issue. I inserted 10 paragraphs adding a link to each one with the opens in new window option enabled, and in all the links target="_blank" was added as expected. I guess the problem may have been solved as a side effect of other change. If the problem is still happening in your tests feel free to reopen the issue.
> I also see that rel="noopener" has been added to some of the links in which I added target="_blank" with no conceivable pattern.
When opens in new window option is enabled besides target="_blank" the editor also adds rel="noreferrer noopener" to the markup of the link.
