### ISSUE TITLE
Can copy but not cut text in Android/Chrome

### ISSUE THREAD

**Issue by rachelmcr** [WordPress/gutenberg#9237]
**Describe the bug**
In Chrome on Android devices, when you select and cut text it only cuts the last selected character (instead of the whole string).

**To Reproduce**
1. Start a new post.
2. Enter some text.
3. Select some text.
4. Select the "Cut" action.

**Expected behavior**
The selected text should be copied to the clipboard and removed from the editor.

**Screenshots**
Only the last character of the selected text is removed, although the entire text is copied.

**Mobile:**
 - Device: Nexus 9
 - OS: Android 7.1.1
 - Browser: Chrome
 - Version: 68.0.3440.91

Also reproduced on Android 8.1 and 9.0 in the same version of Chrome.

**Additional context**
This issue also affects TinyMCE but not other text fields. It was originally reported in https://github.com/Automattic/wp-calypso/issues/26736 and I'm moving it here as Gutenberg is under active development.

**Comment by designsimply** [comment]
Tested and confirmed that only the last character is removed after tapping "Cut" in Chrome on Android and noting that the full content does appear to be copied to the clipboard and can be pasted elsewhere even though "Cut" doesn't remove the highlighted content as expected.

<img src="https://user-images.githubusercontent.com/1119271/44474328-a6dbf580-a5ef-11e8-8304-5ddb18a3d0bc.png" width="270"> <img src="https://user-images.githubusercontent.com/1119271/44474327-a6dbf580-a5ef-11e8-8cfc-bbf265733c26.png" width="270">
<sup>Tested at alittletestblog.com with WordPress 4.9.8 and Gutenberg 3.6.2 using Pixel on Android 8.1.0.</sup>

**Comment by jorgefilipecosta** [comment]
Hi @rachelmcr, @designsimply thank you for reporting this issue and for the tests.

In my tests using an android emulator the problem does not seems to happen anymore, there were many rich text changes, so maybe this was fixed as a collateral effect.
![Jun-06-2019 10-50-11](https://user-images.githubusercontent.com/11271197/59024109-0f2b5900-8849-11e9-9157-972b4b14fbfd.gif)


If the problem is still happening in your tests feel free to reopen the issue and additional debugging will be performed.

**Comment by designsimply** [comment]
👍 tested and confirmed all looks well using Chrome on Android 9 with a site running WordPress 5.2.1 and no active plugins.
