### ISSUE TITLE
Can I already use the plugin for blogs that I want to keep?

### ISSUE THREAD

**Issue by Natuurlijklinda** [WordPress/gutenberg#9262]
I was wondering if I make a blog with the Gutenberg plugin now and I put that online, will it stay like this? Or is the plugin only for testing now and not really publishing it? The only thing that's not good for me yet is that I can not make nofollow links. The rest is fine. So I made a blog now with Gutenberg and I want to keep on using it in my next blogs. But is that ok to do?

**Comment by AndreaBarghigiani** [comment]
Hi @Natuurlijklinda,
I have a coupple of sites where I publish posts with Gutenberg and on my clients website I start straigh on installing it on the platform and customize the theme to better implement the new blocks.

The main problem is that right now there are not much themes with a high compatibility with Gutenberg blocks, but this will change soon.

If you want to keep your theme you can add this code `add_theme_support( 'wp-block-styles' );` into your `functions.php` to get the styles of the plugin into your theme as well. Really useful for quote blocks 😉 

Instead if you want start a blog or change the theme where you have a full Gutenberg experience I suggest you to have a look arond because I've started to see different themes that are declaring the support for this plugin.

The first example that comes to mind is the __Atomic Block Theme__ that you can find in the [repo WordPress](https://wordpress.org/themes/atomic-blocks/) that is 100% compatible with Gutenberg and with the blocks that you get installing the [companion plugin](https://wordpress.org/plugins/atomic-blocks/).

All that to say that IMHO you can start usign Gutenberg right now, the plugin is not stable yet but the roadmap is to fix all the bugs and inconsistency so you'll should be fine.

**Comment by Natuurlijklinda** [comment]
Hi! Thanks for  you answer! I think my theme is pretty ok with Gutenberg. I used the quotes already, as you can see here. :) https://www.natuurlijklinda.nl/ervaring-wim-hof-methode-ijsbad/ Sorry, it's in Dutch, but you can see the layout. :) I was just wondering whether it would not disappear when Wordpress is upgraded to Gutenberg. But as I understand from your answer, that will be fine right?

**Comment by AndreaBarghigiani** [comment]
Nothing shoud disappear, it supposed to get better 😉

**Comment by Natuurlijklinda** [comment]
That is good to know! :D Thanks!

**Comment by designsimply** [comment]
Gutenberg is in final testing stages and most themes are compatible by default regardless of `add_theme_support( 'wp-block-styles' );` which is something optional. A code change isn’t required to make a theme compatible. If your theme is working well already, then the content is stable and good to go! Thanks so much for testing it out!
