### ISSUE TITLE
Is it possible to include html code in a Block 

### ISSUE THREAD

**Issue by fdrouin** [WordPress/gutenberg#9272]
In my blog I manage English and french by two DIV
the first with class="french"  and the second with class="english
I switch French or English by a Button
how to include this code in a Block ?
Thanks 
PS my blog is  pele-mail.org

**Comment by Soean** [comment]
If you don't want to code your own block, you can use the HTML-block.

**Comment by AndreaBarghigiani** [comment]
Hi @fdrouin,
for each block there is an **Advanced** section in the sidebar where you can add the class you need.

![advanced](https://user-images.githubusercontent.com/190159/44529316-120af200-a6ec-11e8-9b86-734990526e96.png)

The screenshot has been taken from an Italian installation but I hope you can find the appropriate section.

If all you need to do is add a simple class, this is the way you can do it 😉

**Comment by tofumatt** [comment]
You can use the HTML block to create two divs with their own content, but as mentioned you could create your own block that had multiple language options: https://wordpress.org/gutenberg/handbook/blocks/

It would be a bit of work to create the block but it might save you manually writing `<div class="french">`. If you have JavaScript and WordPress experience it's worth a look, but otherwise you can use the HTML block to create your custom `<div>`s 😄
