### ISSUE TITLE
Add column padding option

### ISSUE THREAD

**Issue by camro** [WordPress/gutenberg#9296]
**Is your feature request related to a problem? Please describe.**
Currently, we can't have padding on columns unless we add it manually.

**Describe the solution you'd like**
Add the ability to have padding on columns

**Comment by mor10** [comment]
Columns are laid out using `flex` which means as of _right now_, each variant (2 columns, 3 columns, 4 columns, etc) needs its own rule to describe the width of each column. I say _right now_ because eventually the `gap` property will work with `flex` allowing us to set one value for the gap between columns. That is in the future though. For now, to create gaps between columns you must set the width of each of the items within the flexible box.

For reference: https://developer.mozilla.org/en-US/docs/Web/CSS/gap

**Comment by mtias** [comment]
Consolidating in #10730 which has a bit more activity.
