### ISSUE TITLE
Enhancement: Improve positioning of the publish buttons post publish

### ISSUE THREAD

**Issue by arunsathiya** [WordPress/gutenberg#9300]
**Steps to reproduce**: Follow the steps below to reproduce the issue. 

- Publish a post using the Gutenberg editor.
- Notice the `What's next?` region on the right sidebar.
- Notice that the `View Post` and `Copy Link` are crammed up to the field containing the post permalink.

**What happens at the moment:** This is how it looks at the moment. Notice that the two buttons do not have any space above them.

<img width="267" alt="screen shot 2018-08-24 at 12 57 33" src="https://user-images.githubusercontent.com/18581859/44571058-57d3c300-a79d-11e8-8a59-8300b6ccc242.png">

**What I am expecting to see instead:** I am hoping to see that the two buttons have a space at the top.

<img width="267" alt="screen shot 2018-08-24 at 12 57 42" src="https://user-images.githubusercontent.com/18581859/44571084-67530c00-a79d-11e8-9e1a-0c0bf03694cf.png">

--- 

## My suggested approach

This can be done introducing a padding at the top, as done using this CSS code.

```
.post-publish-panel__postpublish-buttons {
    padding: 6px 0px;
}
```

**Comment by designsimply** [comment]
Thank you for posting! The suggestion is good. The whole publishing flow is currently being redesigned in #7602 and so I would like to close this issue but only because of the other design work already in progress. If it doesn't go through quickly enough, we can re-open this issue. 

Here are recent design mockups showing how the post-publish panel could look, including those buttons you've mentioned: https://github.com/WordPress/gutenberg/issues/7602#issuecomment-412610277

**Comment by arunsathiya** [comment]
I didn't realize there was another major tracker! Thanks for the heads up! 👍🏽
