### ISSUE TITLE
i18N: Use letters for formatting buttons instead of SVG

### ISSUE THREAD

**Issue by webaxones** [WordPress/gutenberg#9313]
Hi,

A typical user does not necessarily know what are h1, h2, h3. It would be nice and easy to take advantage of an evolution like Gutenberg to make an interface improvement by not reproducing this HMI error and replacing the SVG icons with real letters that would make them translatable. 
Example for **French**:
H1, H2, H3 > T1, T2, T3
B> G
I> I
Before : 
![now](https://user-images.githubusercontent.com/17084006/44583735-e436b380-a7a6-11e8-882f-25456fce9988.jpg)
After : 
![then](https://user-images.githubusercontent.com/17084006/44583748-ef89df00-a7a6-11e8-9e3e-96cb70c5ceff.jpg)

**Comment by youknowriad** [comment]
I think one issue with that is that it creates inconsistency with the classic block where it's a TinyMCE toolbar not controlled by Gutenberg itself. I'm no designer though, other opinions would be good.

**Comment by jasmussen** [comment]
We now have a way to collapse panel groups into dropdowns. When we do that we can show more than 3 options for heading levels in the dropdown, and remove that from the sidebar. Additionally this will allow us to show the full "Heading 1" labels in that dropdown, which should fix this issue. 

CC: @gziolo because you had thoughts on this.

**Comment by gziolo** [comment]
Yeah, I second what @jasmussen said. I don't have time to look into it this week, but this seems like a good compromise. To have an icon and show full text when dropdown shows up.

**Comment by ghost** [comment]
@gziolo @jasmussen What's the status of this issue? Has the compromise been implemented and can the issue be closed, and if not, what else has to be done?

**Comment by jasmussen** [comment]
Here's what the dropdown looks like today:

<img width="463" alt="Screenshot 2023-03-13 at 10 57 26" src="https://user-images.githubusercontent.com/1204802/224668299-352aa2ac-3ce3-4ae6-a0c6-7620e3c6d1ff.png">

Because so much has changed, I'll tentatively close this one. Let me know if this was in error.
