### ISSUE TITLE
Convert: Image to File - File title shows placeholder after conversion despite having title available

### ISSUE THREAD

**Issue by eddhurst** [WordPress/gutenberg#9350]
**Describe the bug**
When converting an image into a file component, the image stops rendering as an img tag and instead renders as an a tag. Once converted, the placeholder "Write file name..." shows. If you click the edit button on the block, then save, without amending anything, the File block will correctly show the title as expected.

**To Reproduce**
1. Upload an image as image block.
2. Click to Change block type to "File"
3. Image block re-renders as file block.
4. See placeholder, instead of file title.
5. Click "edit file" button
6. Click blue "select" button (image already selected and meta filled.
7. See title update.

**Expected behavior**
Once an image has been changed to a file block, I would expect the image title to be used in the file title field, and to not see the placeholder text.

**Screenshots**
<img width="820" alt="screen shot 2018-08-25 at 13 17 18" src="https://user-images.githubusercontent.com/9933592/44618177-055fd880-a869-11e8-8e7f-9f143fd9ade5.png">

Changed image block to file block, then duplicated to show HTML. The file knows which image is selected (and the download button works) but the title isn't used.

**Desktop (please complete the following information):**
OS: Mac Sierra 10.12.5
Browser: Chrome
Version: 67.0.3396.99

**Additional context**
Gutenberg: 3.6.2

**Comment by j-rewerts** [comment]
Hey @eddhurst I've been able to reproduce this. I'll try to get a PR in soon.

**Comment by j-rewerts** [comment]
I have a branch [here](https://github.com/j-rewerts/gutenberg/tree/fix-9350). It changes the image block to file block transformation so that it makes use of the image blocks file name. Unfortunately, I introduce an unintended side effect. In the past, Gutenberg uses the image's caption to set the name of the file, so now when we switch back from the file to the image, we have a new caption.

**Image with no caption**
<img width="651" alt="screen shot 2018-08-28 at 9 43 15 am" src="https://user-images.githubusercontent.com/8295080/44734315-d767d780-aaa6-11e8-9075-fd73b8ffde7b.png">

**Transform to file**
<img width="688" alt="screen shot 2018-08-28 at 9 44 16 am" src="https://user-images.githubusercontent.com/8295080/44734370-fb2b1d80-aaa6-11e8-81a6-20a12653752f.png">

**Switch back to image**
<img width="647" alt="screen shot 2018-08-28 at 9 45 22 am" src="https://user-images.githubusercontent.com/8295080/44734429-23b31780-aaa7-11e8-86a2-f8d1de9c5c36.png">

Can anyone with more experience advise as to the ideal behaviour? Maybe just using caption is the best approach?

**Comment by andrewserong** [comment]
Resolved in #34256 (in the Image > File transform, use the image caption if available, and if not, fall back to using the image's filename).
