### ISSUE TITLE
categories missing

### ISSUE THREAD

**Issue by mggardner** [WordPress/gutenberg#9366]
classic editor has categories and tags available on right column.  I can't find categories anywhere with this editor.

**Comment by caxco93** [comment]
Hi! I hope this GIF helps you
![categories](https://user-images.githubusercontent.com/3190666/44641248-b78fc100-a98b-11e8-8d9f-121ad4767711.gif)

**Comment by designsimply** [comment]
In some cases, categories can go missing because of a theme or plugin conflict. For example, a conflict with iThemes Security plugin was noted at #8763. If you still cannot find categories and have that plugin installed, try temporarily disabling the plugin to confirm if that is the source of the problem—if it is, first make sure you have updated to the latest version and if you're still having problems after that please report the issue to the plugin developer. If you need help finding how to do that, let us know!

**Comment by a904guy** [comment]
For iThemes Security Pro

To fix this, it is under /wp-admin/admin.php?page=itsec&module_type=recommended

Click Configure Settings for WordPress Tweaks
![image](https://user-images.githubusercontent.com/404081/87318025-c63adf00-c4f5-11ea-89a2-c10710c99757.png)

Scroll down to Rest API, and set it to default access.
![image](https://user-images.githubusercontent.com/404081/87317963-b15e4b80-c4f5-11ea-9617-b6453be2c0e0.png)
