### ISSUE TITLE
Image Block Link Settings - Remember Link Settings

### ISSUE THREAD

**Issue by grappler** [WordPress/gutenberg#9404]
**Describe the bug**
The Image Block does not remember what the previous setting for the link setting was.

**To Reproduce**
1. Add an image block
2. Change the link setting to media
3. Add a new image and the link setting will be still at none instead of media.

**Expected behavior**
The image link setting should be remembered for future image blocks. This is currently done in the classic editor with the cookie `wp-settings-1` and value `%26urlbutton%3Dfile`

**Additional context**
- Gutenberg `3.6.2`

**Comment by draganescu** [comment]
Howdy @grappler I wonder if the new Variations API could solve this by adding an image block whose `linkDestination` attribute is fixed?

**Comment by paaljoachim** [comment]
Testing using

WordPress 5.7 beta 1
Testing with and without Gutenberg plugin 9.9.1 activated.
Theme: Twenty Twenty One
Local site
Chrome

OSX 10.15.7

Testing instructions:
1. Add an image block
2. Change the link setting to media
3. Add a new image and the link setting will be still at none instead of media.

I added an image block. Added an image. Clicked link and selected Media File. 
Clicked Replace image. The Media File link is still selected.

The Image block link settings is remembered even when switching image.
Issue has been fixed and I will close this issue.

**Comment by grappler** [comment]
Thank you @paaljoachim for testing this issue and the detailed documentation. 

I realised from your documentation that my steps were not very clear. The issue is not when replacing/changing the image in a block but when inserting a new image block.

The idea was to be able to change the default option for future image blocks.

I hope I was able to explain myself better.

**Comment by paaljoachim** [comment]
Ahh gotcha!
Adding Image block. Linking to Media File.
Adding another Image block. Linking to Media File is not remembered.

**Comment by draganescu** [comment]
This is an interesting ticket @grappler and it speaks about remembering per user settings for blocks. But, how far should this reach? Adding a whole feature just for the image block seems overkill. Would there be other similar settings that make sense to be automagically saved?

Would this be better saved by a plugin?

**Comment by grappler** [comment]
I did not look into it that far.  There seems to be an issue on saving the preference for the image size https://github.com/WordPress/gutenberg/issues/8663

As the discussion is continuing in https://github.com/WordPress/gutenberg/issues/23154 it may be best to pose those questions there.
