### ISSUE TITLE
Unable to edit the sharing message before publishing

### ISSUE THREAD

**Issue by Jebarson** [WordPress/gutenberg#9414]
**Describe the bug**
The message to post to social network is not shown

**To Reproduce**
Goto the editor and look for the message that would be posted to social networks

**Expected behavior**
I should be able to see the text which will be posted to the social networks before publishing. I should be able to edit the same.

**Screenshots**
The social message itself is not visible

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version 44.18219

**Additional context**
I am unable to find the text that would be posted to the social network. In the classic editor, I could edit the text before publishing

- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by designsimply** [comment]
Thank you for writing in! This sounds like a plugin feature that is perhaps not yet compatible. Can you please confirm which plugin you are using to create the sharing message? Perhaps Jetpack? Once you confirm which plugin you are using, I will help research whether that is being worked on or help you get it reported if it isn't already because it is probably a change that will need to be made on the plugin side.

**Comment by Jebarson** [comment]
Yes its the WordPress Jetpack I am using. So I am assuming that Jetpack team is yet to make it compatible with Gutenberg.

**Comment by youknowriad** [comment]
I'm closing, please consider opening an issue in JetPack if it's still not fixed.
