### ISSUE TITLE
Save Draft should have same style as all other publishing action. 

### ISSUE THREAD

**Issue by robertdall** [WordPress/gutenberg#9452]
When you are creating a draft post after creating some content you see a text link with a cloud that says _save draft_. This is intended to be a status update saying you can save a draft of this content (page/post etc). Screenshot below  
<img width="121" alt="screen shot 2018-08-29 at 2 10 11 pm" src="https://user-images.githubusercontent.com/1909677/44818579-5ee44200-ab9e-11e8-9dd8-bf804c3b2a05.png">

Once saving this text changes to show it has now been saved with a check mark and the text is no longer clickable. 
<img width="85" alt="screen shot 2018-08-29 at 3 19 12 pm copy" src="https://user-images.githubusercontent.com/1909677/44818787-15e0bd80-ab9f-11e8-8e68-e5ec615c492d.png">

While the _saved check mark_ is a great update and notification to the user that your draft has been saved. The previous linkable content isn't proper UI for an actionable button by the user. I am guessing this was done so we could have all js action happen in the same place. But having something clickable and then not will be confusing as well.  This might mean that we have to move the _saved check mark_ over but 

While Gutenberg is new it doesn't mean we have to stop using a design standard that will help users conversion to the new editor. 
<img width="290" alt="screen shot 2018-08-29 at 3 33 21 pm" src="https://user-images.githubusercontent.com/1909677/44819255-0b272800-aba1-11e8-9fc3-184babebcf17.png">

Here is that same save draft in the classic editor without a background and without a border. It looks really odd. Is it clickable? What does it do? This is essentially what we doing in the new editor. 

Here is the save back to draft without the background or border.
<img width="461" alt="screen shot 2018-08-29 at 4 04 36 pm" src="https://user-images.githubusercontent.com/1909677/44820372-7d9a0700-aba5-11e8-925c-dd847588e486.png">

Also here is a little change I made to Github button menu. The watch certainly seems out of place as appose to the other two.
<img width="520" alt="screen shot 2018-08-29 at 3 54 54 pm" src="https://user-images.githubusercontent.com/1909677/44820083-3e1eeb00-aba4-11e8-801b-2bce6a8d67eb.png">

> Consistency is not about making different things the same. It’s about making the same things the same. ~ Adam Silver, Interaction designer

This last quote sums up why I think we need this. We are not making something different the same, it accomplishes the same task in the same are and should be styled the same as other things that do the same thing. Just because it does something to a lesser degree doesn't mean it should be styled any different.

I did a bit a research on this before I wrote this issue

[Links vs. Buttons in Modern Web Applications by Marcy Sutton ](https://marcysutton.com/links-vs-buttons-in-modern-web-applications/)

[But sometimes links look like buttons (and buttons look like links)](https://medium.com/simple-human/but-sometimes-links-look-like-buttons-and-buttons-look-like-links-9b371c57b3d2)

**Comment by jasmussen** [comment]
Thanks for the ticket. I believe this has come up a couple of times in the past, but it's good to have one canonical location for the reasons it is as it is. And there are couple of reasons for why it is this way.


*1. There's a new pattern: the IconButton*. We use this pattern either for buttons that are used so often that we need to visually reduce their weight so as to not cause cognitive load (such as Add Block). Or we use this style for buttons that we deem less important than others, thus also wanting to de-emphasize them (such as _move block up_ or _more menu/ellipsis button_). This is especially important in an interface that has a lot of options. Balancing it all together is an important aspect of the design, making sure that the obvious buttons you need to know how to use are immediately accessible.

*2. It is meant to be automatic, and more of an affordance for letting you know the post is saved*. In modern web apps there are no save buttons. When you write in Google Docs, Office 365, or even use a mobile app, it is _assumed that your content is saved automatically and never lost_. Hitting ⌘S to save your content or else you risk losing it, this is a vestigial concern that through technology we are able to either ameliorate or get rid of entirely. 

And the save button is automatic. It's not as automatic as it should be, in fact due to the decade-long legacy of how WordPress saves content, we were not able to get rid of this button entirely. But this is still the ultimate goal: to make sure your content is always saved, all the time, and not have to concern you with doing this manually. I've personally lost so much work to Photoshop crashing without autosaves, I'm ready for this to be a non-issue. 

For that reason, the Save Draft button has been designed to be a "save state indicator". Like in Google Docs or Medium, there's always a little bit of gray text that says "Saved". You can glance at it and breathe out, good, if the tab crashes I'm fine. But because it has to do double duty with a button — notably legacy metabox support requires a manual save — every once in a while it will turn into a button so you can press it. 

Did that address your concerns? Thanks for the ticket Robert!

**Comment by jasmussen** [comment]
It's a totally fair feeling. How long have you been using Gutenberg? I'm wondering if it'll grow on you. The reason I ask is that we've had a few different stylings for this, and a while back it as a blue link instead of a button, and the change to an icon button (same type of button as movers, add block, etc) actually came from a consistencty ticket much like this.

**Comment by youknowriad** [comment]
Closing as stale. This UI changed a bit since and let's reopen if we want to update this UI once again.
