### ISSUE TITLE
saving page fails

### ISSUE THREAD

**Issue by nicofann** [WordPress/gutenberg#9461]
**Describe the bug**
When I click on page save (Mise à Jour en francais),  a red banner opens on the top of the page mentionning that saving had failed (Mise à jour échouée, en francais).

However the saving worked fine.

Then, when I want to work on another page of my website, I have to grant that I want to quit the page without saving, with a window (2 buttons: quit or cancel).

After several operations, it comes that this windows opens but immediately disappears. Consequence is that browser is stuck on the page, and it becomes no more possible to close the browser.

**To Reproduce**
do the same as described. 

**Screenshots**
NA

**Desktop (please complete the following information):**
Windows 10 v 1803
Chrome Version 68.0.3440.106 (Build officiel) (64 bits)

**Additional context**
-  version of Gutenberg you are using in the description : 3.6.2

**Comment by designsimply** [comment]
This type of problem is most likely caused by a security plugin or server-side setting. In the past, users have reported problems with Cloudflare, Wordfence, custom mod_security settings, or certain themes and you can see several examples at https://github.com/WordPress/gutenberg/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+in%3Atitle+%22Updating+Failed%22

First, if you do have any security plugins setup, check to make sure they are updated to the latest versions.

If that doesn't help, a good next step would be to temporarily disable any security plugins, or any plugins you think may be causing a conflict and re-testing. If the problem goes away, then re-activate each plugin one-by-one until you find the culprit.

If possible, another helpful bit of information to include would be to check the Network tab in your browser Developer Tools and try to find out if any API calls are failing. Sometimes they contain helpful clues to narrow down the source of the trouble! See https://github.com/WordPress/gutenberg/issues/8241#issuecomment-412395186 for a similar request on on a similar issue.

**Comment by mtias** [comment]
It's been a while since 3.6 which has improved multiple pieces that could be related to the issues you experienced. If there's still problems, please reopen with more information.
