### ISSUE TITLE
Change "Change Block Type" Icon 

### ISSUE THREAD

**Issue by jaclyntan** [WordPress/gutenberg#9471]
Writing in Gutenberg makes adding block types awkward and confusing. The process is very tedious and is made even more so by ambiguous icons everywhere (but that's another issue altogether).

One huge gripe I have with the layout is that the "change block type" icon looks VERY similar to the text alignment icons in the block editor toolbar.

When you are writing at a glance the "change block type" icon is not immediately obvious and I've found you really have to focus to identify the button and click on it.

I am proposing to change the icon to one that is made of actual blocks, straight from the dashicons icon set WordPress uses (https://developer.wordpress.org/resource/dashicons/#admin-multisite)

My mockup of the proposed change is below:
![changeblocktype](https://user-images.githubusercontent.com/18632934/44857369-43faf600-aca2-11e8-8442-731161423e3f.jpg)

(please note my mockup shows when a user actually clicks on the icon - I had to take a screenshot that way as GB removes inspector changes if you deselect the block)

I am interested to hear what other people think so let me know!

**Comment by chrisvanpatten** [comment]
Hi @jaclyntan —

Thanks for opening this issue! Gutenberg 3.7 will actually include a new approach for the block switcher which you can see in #9310. There's also a lot of discussion in #9127. 

To keep things streamlined, I'd definitely encourage you to share your mockup at #9127, and I'll close this issue to consolidate discussion there since that issue is a little older and has more ideas/chatter.

Thanks again for the mockup and definitely feel free to share it on the other ticket :)
