### ISSUE TITLE
Add text labels and code button to top left bar

### ISSUE THREAD

**Issue by jaclyntan** [WordPress/gutenberg#9480]
I think GB relies too heavily on icons in its interface and needs more text labels so people can know what's going on at a glance. 

The top left icon bar in particular needs more context so people are constantly aware of these functionalities and can refer to them really quickly while writing content.

I have mocked up an example of what I mean below:
![topbar](https://user-images.githubusercontent.com/18632934/44869688-cbeff880-acc0-11e8-916b-59e50b703f81.jpg)

Asides from adding labels I also added a code button at the end because I think there needs to be a super quick way to edit the document in html. I know you can access it from the settings but that's a lot of clicking and it currently **_feels_** like it is very hidden away.

Here's a full screen mockup for reference:
![screen_shot_2018_08_30_at_7_42_34_pm_by_electrifried-dcljqzk](https://user-images.githubusercontent.com/18632934/44870002-88e25500-acc1-11e8-8af1-f7c953c85339.jpg)

sidenote: this mockup also features a proposed sidebar change I requested here #9470

**Comment by kjellr** [comment]
Thanks for the proposal, @jaclyntan!

There was discussion around text labels for those icons (both situated next to and below the icons) in https://github.com/WordPress/gutenberg/issues/7221. In general, this was abandoned due to issues with long translations. We also have to take into consideration what happens if the "Unified Toolbar" option is active. In that case, there are potentially many more icons in the toolbar, and so the long label/translation problem becomes even more challenging:

<img width="1101" alt="screen shot 2018-09-03 at 10 49 57 am" src="https://user-images.githubusercontent.com/1202812/44980226-27dbab00-af67-11e8-89b0-91ac1f317653.png">

> Asides from adding labels I also added a code button at the end because I think there needs to be a super quick way to edit the document in html. I know you can access it from the settings but that's a lot of clicking and it currently feels like it is very hidden away.

We're reworking the way the Code Editor option is presented as part of 
https://github.com/WordPress/gutenberg/pull/9394 ([comment](https://github.com/WordPress/gutenberg/pull/9394#issuecomment-417049739)). That doesn't resolve this, but I don't think we'll end up making the Code option more prominent, as an element of the core design vision for Gutenberg is to limit the amount of custom HTML a user needs to use (["Code editing shouldn’t be necessary for customization"](https://wordpress.org/gutenberg/handbook/design/#vision)). That said, if power users want to access Code editor more quickly, there is a keyboard shortcut for it: `command-shift-option-M`. 🙂

I'm going to close this for now, but that doesn't mean this is closed for good. Feel free to weigh in further if you have additional thoughts.
