### ISSUE TITLE
Gutenberg unresponsive after update 8/30 -8/31 (plugin conflict fixed in Yoast SEO 8.1.1)

### ISSUE THREAD

**Issue by solutionsdiluted** [WordPress/gutenberg#9498]
**Describe the bug**
After updating to the latest version of Gutenberg this morning, My plug in is not working. I can't edit or view posts on the back end. Please help!

**Comment by GlennMartin1** [comment]
Are you using Yoast SEO?

If so, that's a likely culprit. Yoast will be releasing 8.1.1 shortly.

**Comment by Soean** [comment]
Hey @solutionsdiluted,
can you share a little more infos? What happens when you open the editor, do you see an error or just a white screen?

Are you using the Yoast Plugin? If Yes, see: https://github.com/WordPress/gutenberg/issues/9506#issuecomment-417688790

**Comment by solutionsdiluted** [comment]
Hey,
Yes I am using Yoast SEO. I will retry the latest Gutenberg plug in when
the new Yoast plugin is released and installed. For now I was able to
rollback Gutenberg to 3.6.2 and its working fine.

The original issue i was having, or the original message I got was:
I updated Gutenberg.
I went to edit a post.
White screen came up with 3 options form Gutenberg:restore post, copy post
text and another option I cant remember. None f the options worked and WP
crashed.

Thanks for reaching out,

Owen
Solutionsdiluted@gmail.com

**Comment by lenador** [comment]
No Yoast SEO installed on one of my websites and Gutenberg is definitely not loading after 3.7.0 update. I'm getting a blank page where the editor should be loading.

Turned off caching with Swift Performance Lite but no change.

Two minified React errors in Console pointing to this page
https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]=

**Comment by mtibesar** [comment]
After updating to Gutenberg 3.7
![screen shot 2018-08-31 at 2 10 59 pm](https://user-images.githubusercontent.com/6710693/44935993-d0033100-ad27-11e8-8752-0b8363167771.jpg)
 I am unable to edit a Page. When I edit a Page the Page Editor opens and it is blank (all white). I am using the latest version of Yoast SEO Premium and Yoast Local plugins. This is the page that I am unable to edit: https://www.hearingdynamicsaz.com/services/hearing-test-and-evaluation/

**Comment by GlennMartin1** [comment]
If you have Yoast installed, that may be the issue. They have 8.1.1 bring released on Monday to fix it.

Disable Yoast and see if the issue disappears.

**Comment by designsimply** [comment]
I have closed this issue since the original problem reported was likely solved by updating to Yoast 8.1.1. @solutionsdiluted, please reply back if that is not the case.

@lenador, your case may be a different plugin or theme conflict. We can continue discussing that issue here or you may open another issue if you'd like. I searched for the error you linked to and found two reports mentioning it. In both of those cases, they were creating custom blocks and had made a mistake in the code:

https://github.com/WordPress/gutenberg/issues/6460#issuecomment-384874544

https://github.com/WordPress/gutenberg/issues/7487#issuecomment-415833762

If you are working on custom blocks, does the problem go away if you temporarily remove that? This will help pinpoint the problem if it does. If you are not developing custom blocks, what you can do is check for a plugin or theme conflict by temporarily turning off all other plugins and switching to the default theme and then checking for the problem each time after re-enabling plugins one by one. If you still see the problem when Gutenberg is the only plugin active, please let me know your web host if you are able to share that information.
