### ISSUE TITLE
Pass Rendering Context to Server-Side Render Callback

### ISSUE THREAD

**Issue by fklein-lu** [WordPress/gutenberg#9510]
When using PHP to render blocks, it is useful to know in which context the rendering happens. A common scenario for this is to have slightly different output in the editor and the front end.

Currently there is no good way to determine in the PHP layer whether the render happens in the editor or on the front end.

I propose to pass an additional `context` argument to the callback function for rendering dynamic blocks.

It is possible to differentiate the two by other means, but these are rather inelegant.

**Comment by youknowriad** [comment]
Thanks for the issue,

> Currently there is no good way to determine in the PHP layer whether the render happens in the editor or on the front end.

`ServerSideRender` was explicitely meant to be used as a quick solution to transform existing shortcodes etc... but it shouldn't be the default for this reason exactly. Because the `editor` and the `frontend` may and should be different in a lot of cases. 

I'd suggest you just use JavaScript to render the `edit` function of your block instead of `ServerSideRender`.

**Comment by fklein-lu** [comment]
This feature request has originated from an actual client project that I'm working on. This is the second client project that I've worked on that uses Gutenberg in production. My experience shows that the GB team's views on how to build blocks, and the reality of actually building blocks for clients are miles apart.

The editor and the front end for sure look different. But the editor should at least _somewhat_ look like the front end. Else there's really no point in having Gutenberg. I could just use the classic editor and a shortcode.

You can't really expect people to build a template in PHP, complete with the logic and the styles, and then duplicate that same template in JavaScript, with all the logic (!), and of course with another set of styles to get the preview.

Feature requests like this should be evaluated based on how people actually use Gutenberg in the wild, and not your views how it should be used.

Especially because the developer experience of building blocks in JavaScript with Gutenberg, compared to building a standard React & Redux app, is horrible. I can give you an assignment of a block to be build, based on an actual client request, that will show you how horrible the experience is. Maybe then you'll understand why people aren't eager to let go of PHP based rendering.

**Comment by youknowriad** [comment]
> The editor and the front end for sure look different. But the editor should at least somewhat look like the front end. Else there's really no point in having Gutenberg. I could just use the classic editor and a shortcode.

Definitely, the should look the same, but you can't expect them to be the same. This flexibility is at the heart of Gutenberg. 

It would have been great to reuse the same logic but we're dealing with two different technologies for two differents purposes. Duplicating the logic is fine in that case. Users editing an attribute of block shouldn't have to wait for an XHR request to rerender the result of their block, it's not a great API. Imagine typing in a RichText/input and having the block refetch the preview on each typed character. 

> Feature requests like this should be evaluated based on how people actually use Gutenberg in the wild, and not your views how it should be used.

We can disagree on things and that's fine. Just because you think this is a great thing to do as a developer, doesn't mean we should do it. Sometimes you need to make DevX choices/compromises to achieve the best outcome for the final users and this is one of them.

> Especially because the developer experience of building blocks in JavaScript with Gutenberg, compared to building a standard React & Redux app, is horrible.

I'd be happy to hear what makes you think it's horrible and how we can improve it. If you have other suggestions feel free to open issues for them. We can disagree, we can agree and this would improve the overall experience.

**Comment by mcsf** [comment]
Hey @fklein-lu, long time no see.

I second Riad's argument on the edit/save dichotomy.

> I can give you an assignment of a block to be build, based on an actual client request, that will show you how horrible the experience is. 

I don't work on assignment 🙂, but we'd be grateful for some concrete code examples: what is horrible, what you have so far, etc.

**Comment by mcsf** [comment]
Closing this as stale.
