### ISSUE TITLE
Plugin: Let's get Gutenberg in the plugin repository 🎉

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#953]
It's time we get this baby out into the wider world. Let's look at what's required for us to ship this plugin in the repository. 

This would essentially fix #655 through other means.

**Comment by ntwb** [comment]
Creating a [new #meta ticket](https://meta.trac.wordpress.org/newticket) to have it added as a _featured plugin_ regularly sync'd has would be ideal:

https://meta.trac.wordpress.org/browser/sites/trunk/api.wordpress.org/public_html/dotorg/github-sync/feature-plugins.php#L17

**Comment by nylen** [comment]
One thing we need to do first is make sure our vendor scripts are bundled with the plugin and not re-downloaded every day, or on each page load.

**Comment by westonruter** [comment]
I don't think the featured plugin sync will work with Gutenberg as-is because it creates plugins from `master` without doing any build step (unless it is updated to support that). I think instead a Travis CI integration should be done which builds pushes to `master` and then commits them to plugin SVN (via credentials stored in encrypted environment vars, though these credentials could be leaked by a malicious contributor hacking the `.travis.yml` file).

**Comment by mtias** [comment]
I was planning on just pushing build manually on a weekly basis or so to the directory. Not sure if setting up something more complex is worth the time.

**Comment by mtias** [comment]
@nylen do you think you can handle the bundling tasks?

**Comment by westonruter** [comment]
Can part of this be to also exclude `React` and `ReactDOM` from being bundled into the app so that they can be re-used by other JS apps, such as in plugins that define their own blocks, to avoid multiple copies of React needing to be loaded? I believe this was already talked about in regards to JS modules in WP.

**Comment by aduth** [comment]
They shouldn't be bundled. They're [referenced as externals](https://github.com/WordPress/gutenberg/blob/9b72cc499a28a61b2c368785a0538cb7587670bb/webpack.config.js#L20-L22) to their respective globals [enqueued server-side](https://github.com/WordPress/gutenberg/blob/9b72cc499a28a61b2c368785a0538cb7587670bb/index.php#L161-L174).

**Comment by nylen** [comment]
We should be ready to do this now.  See https://github.com/WordPress/gutenberg/issues/1147 for other considerations for each release, such as git tagging.

**Comment by jasmussen** [comment]
Closing this as fixed. HOORAAAY! Great job everyone 🌟
