### ISSUE TITLE
Gallery block responsive thumbnail images improvement

### ISSUE THREAD

**Issue by RavanH** [WordPress/gutenberg#9620]
I noticed that when creating a gallery block, with the 3 default columns, the images used as thumbnails on the front end are the original, full size version. Not the thumbnail, not medium, not even large size version.  There is the srcset attribute but that does not help much because 100vw is set so it will generally only affect screen sizes smaller than the Large or Medium sizes set on WordPress Settings > Media.

Let's take for a theme that uses a maximum content width of 700px. On Settings > Media the sizes Thumbnail 150px - Medium 300px - Large 1024px are set.

Images in the Media Library are all 1600px wide. Now take a gallery with three columns, which will have a source code like this for each image:
`<img src="http://localhost/wp-content/uploads/2011/07/img_8399.jpg" alt="Boat Barco Texture" data-id="771" data-link="http://localhost/2010/09/post-format-gallery/img_8399/" class="wp-image-771" srcset="http://localhost/wp-content/uploads/2011/07/img_8399.jpg 1600w, http://localhost/wp-content/uploads/2011/07/img_8399-300x200.jpg 300w, http://localhost/wp-content/uploads/2011/07/img_8399-1024x682.jpg 1024w" sizes="(max-width: 1600px) 100vw, 1600px">`

Now visit that page on a browser with a screen width of around 1390px. The content width will be 700px which means a max width for each thumbnail of around 220px (due to margins between the images). A source size of 300px would suffice for normal 1x screen resolutions but instead the full 1600px size sources are fetched for each image by the browser.

When instead of `sizes="(max-width: 1600px) 100vw, 1600px` something more in correspondance with the gallery column size could be set to address this. Like `sizes="(max-width: 1600px) 30vw, 1600px"` so that a 30% image slot is assumed.

This leaves 50vw for two column galleries, and 100vw for 1 column galleries...

Thoughts ?

**Comment by RavanH** [comment]
Note that the classic gallery shortcode allows choosing a media size, so if one would select 3 columns and set size Medium, the resulting source code would use the attribute `sizes="(max-width: 300px) 100vw, 300px"` resulting in the default 300px format being used for all screen sizes. Much better for page speed but not ideal for flexibility (full width theme template on large screens) ...

What about something like `sizes="(max-width: 600px) 100vw, (max-width: $content_width) 33vw, $content_width/3"` ? Where $content_width is defined in the theme functions.php (if not, then fall back on the full size image width like it is now)

**Comment by ali1234** [comment]
All I can offers is a me too. In addition to using the full size images instead of thumbnails, it also doesn't make the thmbnails square like the old version did.

**Comment by bikubi** [comment]
This bug bugs me to no end, since it makes gallery block images essentially non-responsive - to me, an unfortunate dealbreaker for (serious) uses of the block gallery. Some thoughts on possible workarounds (because I don't see a solution yet)

- a `filter` that could inject/correct the `sizes` attribute for block gallery images, like [wp_get_attachment_image_attributes](https://developer.wordpress.org/reference/hooks/wp_get_attachment_image_attributes/), but I don't know if it even could get necessary context info (about being within a block gallery).
- akin to "Advanced / Additional CSS Class", a field for "Additional Child IMG attribute", or "IMG sizes attribute". You'd have to manually adjust it for every block gallery, though. No good for customer people.

The situation gets even uglier with nested blocks. To fake a masonry layout I have placed one-column galleries into column blocks. These would have to be aware of their parent's "`$content_width`"...

**Comment by designsimply** [comment]
Passing along a report of this seen in mobile support:

> I am using photo galleries on The Experiential Studios site. If I use Blocks, it loads way slow. If I use Classic editor, the photos shuffle within the editor itself ("random order" unclicked). I need them to stay in the order I put them. Once it shuffle, it takes an hour to put them back in the correct order. Please help!

<sup>(internal reference: 2281705-zen)</sup>

The problem with the Classic editor sounds like the issue at https://github.com/Automattic/wp-calypso/issues/14843 h/t @rachelmcr and the problem with the gallery block loading too slowly sounds like this issue.

**Comment by noisysocks** [comment]
Since `sizes` is set by `wp_calculate_image_sizes`, I'm moving this issue into the Media component in Core Trac.

https://core.trac.wordpress.org/ticket/49966
