### ISSUE TITLE
Things I don't like about Gutenberg

### ISSUE THREAD

**Issue by josephjcox** [WordPress/gutenberg#9669]
**Is your feature request related to a problem? Please describe.**

- I am frustrated when I select a bunch of text and hit paste and it keeps the old text (unlike any normal "writer's" text editor and leaves a mishmash.
- I am frustrated when I leave blank paragraphs and it just decides they should be skipped because spacing isn't managed that way
- I am frustrated at how difficult it is to select how things are formatted - forcing me into styles when I don't really want them
- The basic concept of moving blocks around just isn't how you write text. It is nice for interactive stuff, I get that. But it shouldn't get in the way of conventional text editing.
- Copy and pasting from a word processor often ends up stripping paragraph formatting (like indentation). I don't think the Classic editor did that.

**Describe the solution you'd like**

- When you copy over selected text, it should delete it
- Blank paragraphs should show up as space
- Old-style formatting should be easily available, as well as styles
- Perhaps allow movement of blocks over a non-blocky background

**Describe alternatives you've considered**
I'm probably going to reinstall the classic editor, even though I like some of the features Gutenberg introduces, it creates risks of messing up other text due to unnatural text flows.

**Comment by designsimply** [comment]
Thanks for posting feedback! 

For the copy/paste issue, may I ask your browser version for reference? I will also test that and make sure it's reported as a bug if needed.

About the blank paragraphs being skipped, I want to make sure I understand, do you mean that you are adding several blank paragraphs in a row and you expect those paragraphs to stay put when you save but that they are getting removed?

You might really like the full screen mode coming in 3.8. Would you consider testing again when 3.8 is released?

I am closing this issue because it isn't actionable directly and noting that  your feedback has been noted, thank you!, and we can continue the discussion even with the issues closed. This is something we're doing more of in order to keep a more streamlined list of open issues as the actionable ones as opposed to general feedback.

**Comment by josephjcox** [comment]
No problem, just sharing feedback which I figured you'd want. :)

Comments below:
On 9/6/2018 6:36:22 PM, Sheri Bigelow <notifications@github.com> wrote:
Thanks for posting feedback!
For the copy/paste issue, may I ask your browser version for reference? I will also test that and make sure it's reported as a bug if needed.
Joseph Cox: Vivaldi. I just did it in Chrome too though. Selected three paragraphs, hit Paste with text from this email. And it just added another paragraph without replacing the existing one. I think it is a feature, not a bug from the developer's perspective :)


About the blank paragraphs being skipped, I want to make sure I understand, do you mean that you are adding several blank paragraphs in a row and you expect those paragraphs to stay put when you save but that they are getting removed?
Joseph Cox: No, I mean that the space they represent is removed from the final product. It is like the blocks are carriage returns in HTML and not showing up on the final code like a <p> would.


You might really like the full screen mode coming in 3.8. Would you consider testing again when 3.8 is released?
Joseph Cox: Sure.


I am closing this issue because it isn't actionable directly and noting that your feedback has been noted, thank you!, and we can continue the discussion even with the issues closed. This is something we're doing more of in order to keep a more streamlined list of open issues as the actionable ones as opposed to general feedback.
Joseph Cox: No problem. My general issue is just that it has become a very unnatural way of editing text. On another blog (which really isn't a blog but a static site), I am using Elementor and it does a great job of non-text focused editing. But I wouldn't use it on a site where I was regularly adding text, even if I wanted to add some fun elements to it.

Thanks!

Joseph
