### ISSUE TITLE
The editor has encountered an unexpected error - still happening after Yoast update

### ISSUE THREAD

**Issue by marcusjwilson** [WordPress/gutenberg#9693]
When trying to Publish a new Page in WP (Gutenberg v3.7.0), I'm getting the "editor has encountered an unexpected error" message along with a console error _TypeError: n.types.some is not a function_.

![image](https://user-images.githubusercontent.com/2757625/45228379-f2162980-b2ba-11e8-9c17-891e77abd510.png)

This is despite updating Yoast to v8.1.2 (and disabling it).  I have a bunch of other plugins enabled, so there may be another conflict.

'Attempt recovery' just results in the console error being regenerated.

**Comment by designsimply** [comment]
Hello and thank you for including a screenshot of console errors in your post! Based on what you've said so far, it does sound like this may be a plugin or theme conflict.

I searched for the error and found one other issue which mentions it: #9629. Since that issue mentions something very specific about themes, would you be able to temporarily switch to a default theme such as Twenty Seventeen and try publishing a page again to see if the theme you are using is possibly the source of a conflict in this case?

If possible, would you note your theme name and version for reference? Or if we can rule out the theme as the source of the trouble, are you able to temporarily disable your other plugins in order to narrow down which one may be the culprit?

**Comment by marcusjwilson** [comment]
Thanks - I've tracked this back to the theme, which is a custom theme build on Underscores.

Are there any known issues with Underscores and Gutenberg?  If not, do you have recommendations what we should look for in our code that might cause the conflict?  We're registering a couple of Gutenberg blocks in our code, so maybe we should start with that.

Best

**Comment by marcusjwilson** [comment]
Okay - I can confirm the exact code in our theme that is causing the conflict with Gutenberg and generating an error when we trying to publish content from the editor:

```
/**
 * Remove Tags support from Posts
 */
function spl_unregister_tags() {
    unregister_taxonomy_for_object_type('post_tag', 'post');
}
add_action('init', 'spl_unregister_tags');
```

When we comment out this code, Pages publish successfully.

Is there an alternative method for unregistering core taxonomies from posts/pages as a workaround for now?

Thanks
Marcus

**Comment by youknowriad** [comment]
@marcusjwilson Even with the code above, I'm not able to personally reproduce the error. I don't know exactly why the `taxonomy.types` is not an array. That said, you can try the PR #9744 to see if it fixes your issues.
