### ISSUE TITLE
Gallery Block: Missing 'Random Order' setting

### ISSUE THREAD

**Issue by vr-gallagher** [WordPress/gutenberg#9701]
In the classic editor, when I go to set up a WordPress image gallery, there are "Gallery Settings" for "Link To", number of "Columns", "Random Order", "Size", and "Type" ("Thumbnail Grid", "Slideshow"). Those settings are missing in Gutenberg Version 3.7.0 when using the "Gallery" block. 

Related: The captions on the Gutenberg "Gallery" block are styled so that the caption hangs oddly over the image. The images also can't be clicked on (possibly because there is no "Link To" option, as mentioned). 

**To Reproduce**
1. Use the 'Gallery' block 
2. Click on 'Media Library'
3. Select Images
4. Click on 'Create a new gallery'
5. Now you are on the final gallery set-up page. Above the 'Insert Gallery' button is a blank area—in that blank area is where the settings I mentioned would normally appear in the classic editor. 

**Expected behavior**
I expected the Gutenberg "Gallery" block to have "Gallery Settings" so that I'd have control over the following options:  "Link To", number of "Columns", "Random Order", "Size", and "Type" ("Thumbnail Grid", "Slideshow").  

**Screenshots**
<img width="1380" alt="screen shot 2018-09-07 at 1 15 37 pm" src="https://user-images.githubusercontent.com/14908398/45241260-8e7f0280-b2a0-11e8-8e8b-bdc28950d2d3.png">
<img width="1378" alt="screen shot 2018-09-07 at 1 16 27 pm" src="https://user-images.githubusercontent.com/14908398/45241261-8e7f0280-b2a0-11e8-9e07-3b1b25065fa3.png">
<img width="604" alt="screen shot 2018-09-07 at 1 17 34 pm" src="https://user-images.githubusercontent.com/14908398/45241262-8e7f0280-b2a0-11e8-9c58-450cc5bdff70.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Firefox
 - Version: 61.0.2

**Additional Context**
 - I'm on the Genesis framework

**Comment by saulirajala** [comment]
Gallery settings were hidden in PR #1978, because Gutenberg didn't use them. I believe settings should now be made in post edit -screen after images are inserted to gallery:

![nayttokuva 2018-09-30 kello 14 54 50](https://user-images.githubusercontent.com/5536354/46257412-d10fb580-c4c1-11e8-90e0-e27136b6ccb4.png)

I wasn't able to replicate the front-end issue. I tested in desktop Chrome and Firefox with Gutenberg 3.9.0 (master branch) and twentyseventeen -theme. Could caption-gradient -issue be relating to Genesis framework?

**Comment by quicoto** [comment]
Aren't we missing the "order" settings? Like inverse order and such?

**Comment by cjyabraham** [comment]
> Aren't we missing the "order" settings? Like inverse order and such?

Yes.  It would be great to have back the `orderby` parameter like the [gallery shortcode](https://codex.wordpress.org/Gallery_Shortcode) has.  Any chance we could get this in?

**Comment by a4jp-com** [comment]
Please bring back the random order setting.

**Comment by noisysocks** [comment]
Here's what is in gallery settings when using the classic editor:

<img width="221" alt="Screen Shot 2020-04-21 at 17 03 44" src="https://user-images.githubusercontent.com/612155/79835484-21c36800-83f2-11ea-88e6-597ab514740f.png">

And here's what is in gallery settings using the latest development version of the block editor:

<img width="283" alt="Screen Shot 2020-04-21 at 17 03 53" src="https://user-images.githubusercontent.com/612155/79835507-28ea7600-83f2-11ea-89ed-7269d7f89e8d.png">

The only missing setting is _Random Order_. It's difficult to implement this in the gallery block right now, though, as it is a static block that does not use the `[gallery]` shortcode.

We could look into making the gallery block dynamic. I'm not totally convinced, though, that supporting _Random Order_ is worth the complexity and performance penalty that making this block dynamic would add.

One way around some of that complexity would be to wait until the gallery block uses inner blocks. The `render_callback` would then only have to shuffle an array instead of parse gallery HTML.

For now, the workaround here is to use the shortcode block to insert a `[gallery]` shortcode.

**Comment by a4jp-com** [comment]
I'm happy using the classic mode till something can be figured out but it would be nice if this was in the block settings. Having random images in sites is cool. Especially design sites.

**Comment by echivalent** [comment]
after 2 years of developing versions, there is still missing that random option, or I am doing something wrong?

**Comment by a4jp-com** [comment]
It still hasn't been added but I hope it can be added one day. I have so many sites I'd like to add dynamic galleries to. We can do lots of different things with blocks now that can't easily be done in classic mode any more as well.

**Comment by cagrimmett** [comment]
@noisysocks 
> The only missing setting is Random Order. It's difficult to implement this in the gallery block right now, though, as it is a static block that does not use the [gallery] shortcode.
> 
> We could look into making the gallery block dynamic. I'm not totally convinced, though, that supporting Random Order is worth the complexity and performance penalty that making this block dynamic would add.

I don't think the Gallery in the Classic editor did not randomize the order of the images displayed in the gallery in the editor when the Random Order option was checked, only on the published post/page. In the same spirit, one option would be to add the Random Order option setting back to the block and add in a conditional to shuffle the innerBlocks array before the foreach outputs them on the front-end. 

I think it is okay if the images are not in a random order in the editor if it avoids the complexity of making it a dynamic block. Perhaps changing the name of the option to "Randomize the order of the images in the published [posttype]" to make that clear would avoid user confusion.

**Comment by a4jp-com** [comment]
I need the random order for lots of sites I work on. It would be great if the gallery block could be made dynamic. The images only need to be randomized on the front end not in the editor as that makes work difficult.

**Comment by t-hamano** [comment]
Whether we want to implement this functionality in Gutenberg or not, I think it can be achieved using `render_block_data` hooks. For example, the following will shuffle the order of images in the front end if the gallery block contains the class name "random".

```php
function gutenberg_should_render_lightbox( $block ) {

	if ( 'core/gallery' !== $block['blockName'] ) {
		return $block;
	}

	if ( ! isset( $block['attrs']['className'] ) ) {
		return $block;
	}

	if ( false === strpos( $block['attrs']['className'], 'random' ) ) {
		return $block;
	}

	$inner_blocks = $block['innerBlocks'];
	shuffle( $inner_blocks );
	$block['innerBlocks'] = $inner_blocks;

	return $block;
}

add_filter( 'render_block_data', 'gutenberg_should_render_lightbox', 15, 1 );
```

The gallery shortcode also has options such as `orderby`, `order`, `id`, `include`, and `exclude`. However, in the case of the Gallery _block_, you can control what images are included and in what order they are displayed, so the only thing missing is the random option.

**Comment by a4jp-com** [comment]
Yes please.
