### ISSUE TITLE
Build a plugin zip of the PR for testing

### ISSUE THREAD

**Issue by tofumatt** [WordPress/gutenberg#9712]
Just at a contributor day where a Gutenberg user who works in education in Glashow where a lot of kids end up using Gutenberg on school-provided iPads was interested in testing on iPad. He mentioned that it would be cool to be able to test out a fix to any issue he filed without having to check out a pull request, set up a development environment, and test against a Docker build.

It's likely too much for us to try something like Calypso does with an entire live site, but maybe we could build a zip of the plugin and host it for people to try out?

Obviously we'd need a place to host it (temporarily? until the PR is closed I suppose) but I could see this maybe being handy… especially as more non-technical users file issues and want to test a fix on their site before we merge it.

**Comment by danielbachhuber** [comment]
Related #6285

**Comment by gziolo** [comment]
@aduth - is it something you have been working on recently? There is also this question is whether we can consolidate this issue with #6285 or replace both of them with your efforts to run the plugin from any branch.

**Comment by aduth** [comment]
#6285 and this issue are very similar, I agree. I'd assume one solution could probably resolve them both.

> @aduth - is it something you have been working on recently?

Previously: https://github.com/WordPress/gutenberg/pull/14289#issuecomment-472462545

>I'm working on a side-project which, while not directly related to this effort, could provide a plugin ZIP distributable for a given pull request at its latest HEAD SHA, to be used for this purpose.

Said project does exist, though it's quite unstable, and doesn't yet have this specific feature to offer a plugin ZIP, but it would be quite straight-forward to do since the underlying implementation of this service relies on creating plugin ZIPs at specific git commits ([source](https://github.com/aduth/gutenberg.run/blob/e843868379121d9fc946d244c6e14a46775a53ab/web/tasks/run/03-create-container.js#L142)).

- https://github.com/aduth/gutenberg.run
- http://gutenberg.run

**Comment by skorasaurus** [comment]
This is now possible thanks to the zip that is built during each PR - details at https://github.com/WordPress/gutenberg/pull/26746
