### ISSUE TITLE
Pullquote Block child has incorrect class name

### ISSUE THREAD

**Issue by tjtaylo** [WordPress/gutenberg#9724]
**Describe the bug**
Incorrect class name for wp-block-pullquote content child. Currently uses **block-library-pullquote__content** but should be **wp-block-pullquote__content**, as this is inconsistent with all other blocks and does not follow BEM standards.

**To Reproduce**
1. Create a pullquote block in the editor
2. Inspect the element

**Expected behavior**
**wp-block-pullquote__content**

**Comment by youknowriad** [comment]
Actually, its the correct className because it follows our guidelines (BEM like)

https://wordpress.org/gutenberg/handbook/reference/coding-guidelines/#css

`block-library` is the package name (root folder), `pullquote` is the component's folder. and `content` is a descendant.

The exception to our rules is actually the `wp-block-*` styles. And these are only allowed for classNames that end up in the frontend as well. (These classNames can be styled by themes as well).
