### ISSUE TITLE
When I click to edit or add a page or post I get a blank screen

### ISSUE THREAD

**Issue by ttaylor12345** [WordPress/gutenberg#9834]
We have a custom WP site. I activated the latest Gutenberg from the Dashboard today 09-12-18. In the WP dashboard if I click to edit or add a page or post I get a blank screen. There's no errors listed...just a completely blank white screen.

Site: http://cutest001.org

OS: Windows 7, 64 bit
Browser: Chrome Version 69.0.3497.92
  
I did a healthcheck and got the following:

WordPress Version | 4.9.8
-- | --
Plugin Versions | Your site has 30 active plugins, and they are all up to date. Your site has 5 inactive plugins, it is recommended to remove any unused plugins to enhance your site security.
Theme Versions | Your site has 4 installed themes, and they are all up to date. Your site has 2 inactive themes, other than twentyseventeen, the default WordPress theme, and Sage Starter Theme, your active theme. It is recommended to remove any unused themes to enhance your sites security.
PHP Version | 7.1.21 - For best performance we recommend using PHP 7.2 or higher.
Database Server version | 5.6.40-84.0-log
JSON Extension | Your PHP install supports JSON.
MySQL utf8mb4 support | Your MySQL version supports utf8mb4
Communication with WordPress.org | WordPress.org is reachable from your server.
HTTPS status | You are not using HTTPS to access this website.
Secure communication | Your WordPress install can communicate securely with other services.
Scheduled events | No scheduled events have been missed.
Background updates | The WP_AUTO_UPDATE_CORE constant is defined and enabled. A plugin has prevented updates by disabling wp_version_check(). No version control systems were detected. Your installation of WordPress doesn't require FTP credentials to perform updates. All of your WordPress files are writable. WordPress security and maintenance releases are blocked by define( 'WP_AUTO_UPDATE_CORE', false );.

**Comment by designsimply** [comment]
Can you please check the console tab in your browser developer tools and reply back with a copy of the errors if any are listed there?

May I ask who your web host is? I had some trouble with a blank screen during beta testing for 3.8 and the problem was traced back to a `Mod_Sec` rule blocking one of the polyfill files in my case. I contacted the host and they were able to fix the problem.

**Comment by ErikXXon** [comment]
I did have to inactivate the Yoast SEO plugin to get Gutenberg working.

**Comment by designsimply** [comment]
@ErikXXon you should not have to do that. I tested Yoast 8.1.1 with Gutenberg 3.8 in pre-release testing and didn't find any problems myself. Are you should the culprit is Yoast in your case? 🙂 Also, make sure you have the latest version install because Yoast is really awesome about updates and i know they've made recent changes both to fix a deprecated dependency and also they added Gutenberg blocks.

**Comment by designsimply** [comment]
@ttaylor12345 any chance you can double check for console errors in your browser developer tools at the time the white screen happens? I would like to try to help and have been unable to see the problem happen in testing so far.

**Comment by mcsf** [comment]
Closing this issue as stale. Feel free to reopen.
