### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by srinimf** [WordPress/gutenberg#9835]
After adding images, I cannot draw outline to that image.

**Comment by designsimply** [comment]
There is not a built-in way to add a border to an image in the image block at the moment.

Here is a quick workaround which may help you:

The Custom HTML block will allow you to write HTML including a `style` attribute for the image:

1. Insert an image in an image block.
1. Select "Edit as HTML" and copy the HTML.
1. Add a "Custom HTML" block.
1. Edit the HTML to add an attribute such as `style="border:2px solid black;"`
1. Adjust the attribute details as needed.

Or if you would like to add borders to all images with a certain CSS class, you can:

1. Insert an image in an image block.
1. Go to Block Settings > Advanced and add an "Additional CSS Class" name of your choice.
1. Add custom CSS to adjust the same style border as above.

**Comment by designsimply** [comment]
I've closed the issue since there is not an option to add borders currently and because workaround had been provided. If you would like to make a request for an option to add borders to images, please open a separate feature request and include details such as your use case and why you think the option is needed and whether you think it will benefit a large number of people. Collecting notes about why a feature like that is wanted is a good next step.
