### ISSUE TITLE
Fatal error: Call to undefined function get_current_screen() in gutenberg.php

### ISSUE THREAD

**Issue by jrohard** [WordPress/gutenberg#9899]
Hello,

I am new in website building just explore wordpress and pulgins for a week recently.
Now, when i tried to access **[my domain]/wp-admin**, i got an error like this one : 

**Fatal error: Call to undefined function get_current_screen() in /home/rohardon/public_html/wp-content/plugins/gutenberg/gutenberg.php on line 103**

I tried searching on google, and so far find the solution :  to access file manager from cpanel, and rename plugin Gutenberg. Now, i can not use Gutenberg, and just using WP Classic Editor.

How to solve my problem ? so i can back using Gutenberg again. 
I like Gutenberg concept and just getting used to it since yesterday.

Regards,
Jack

**Comment by designsimply** [comment]
Welcome to exploring WordPress!

The first thing I can think of to check is that all of your core WordPress files are installed properly and up-to-date. If you haven't already, can you try re-installing WordPress and then trying Gutenberg again? I have installed Gutenberg many times and have not seen this error and I check to see if anyone else has reported it here and they have not.

**Comment by nburlot** [comment]
I got the exact same error on a fresh wordpress, just installed yesterday. When opening admin this morning it showed the error on line 103.

The only other plugin I had installed was "all-in-one-wp-security", so I renamed the file on this one and it solved the issue, I can log in again.

I don't know what's happening as it worked perfectly yesterday. I've got the full message error with gutemberg if it helps ... ?


[err_wordpress.txt](https://github.com/WordPress/gutenberg/files/2418636/err_wordpress.txt)

**Comment by radius314** [comment]
I'm having the same issue on the wp 5 nightly.

**Comment by radius314** [comment]
I'm getting this on a plugin that I'm doing compatibility testing for.

**Comment by designsimply** [comment]
Thank you for the additional replies! Based on what I'm hearing and on another reply I saw at https://wordpress.stackexchange.com/questions/145670/call-to-undefined-function-get-current-screen-on-my-localhost it sounds like that error could be caused by calling `get_current_screen()` in a theme (or incorrectly in a plugin) when that shouldn't happen.

@jrohard can you confirm whether the problem goes away if you temporarily deactivate all other plugins and switch to the default theme?

@nburlot thank you for the update about which plugin was causing the trouble in your case!

@radius314 are you still having trouble? May I ask which plugin you're doing compatibility testing for?
